### ISSUE TITLE
Environment configuration for ultralytics library

### ISSUE THREAD

**Issue by Parsifal133** [ultralytics/ultralytics#10005]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to configure the environment, so that the ultralytics library called from local project, not from: `/root/miniconda3/envs/yolov8/lib/python3.9/site-packages/ultralytics/`

### Additional

Hello, I am new to yolov8 (but have used the v5 model).
I want to develop an open-world model (detect unknown) based on the excellent yolov8 model. This means I need to make some adjustments to the structure of the model.

I noticed that after running `pip install ultralytics`， the ultralytics library was installed to `/root/miniconda3/envs/yolov8/lib/python3.9/site-packages/ultralytics/,` and the code under ultralytics (such as `ultralytics/engine/trainer.py` and `ultralytics/engine/model.py` ) called during model training is also from this path, which means modifying the Ultralytics code in the local project (i.e. `/work/ow-yolo8/ultralytics/ultralytics` , my project path) will not produce any changes to the model training.

A little earlier, I had a yolov8 environment on another server that was no longer available, which used the ultralytics code in the current project. But I forgot how to configure the environment at that time.

So my question is: How to configure the environment so that the ultralytics library can be called from  the local project, not here: `/root/miniconda3/envs/yolov8/lib/python3.9/site-packages/ultralytics/`

**Comment by Parsifal133** [comment]
Thanks for any possible suggestions！

**Comment by Parsifal133** [comment]
Problem solved by running `pip install -e .` under `/work/ow-yolo8/ultralytics/` (my project path).

**Comment by glenn-jocher** [comment]
Fantastic! Using `pip install -e .` is indeed the right approach for your needs, as it installs the package in editable mode. This allows you to modify the code in your local project and have those changes reflected immediately, without the need to reinstall the package after each change. If you have any more questions or need further assistance as you continue developing your open-world model, feel free to reach out. Happy coding! 😊
