### ISSUE TITLE
BUG Report: Multi-GPU training using pretrained models doesn't work

### ISSUE THREAD

**Issue by PanJinquan** [ultralytics/ultralytics#10004]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Multi-GPU training using pretrained models doesn't work.
It's easy to reproduce this bug， `bug.py` code is 
```python
def train_single_gpu(device=[0]):
    model = YOLO('yolov8s-seg.yaml').load('yolov8s-seg.pt')
    results = model.train(data='coco128-seg.yaml', epochs=100, imgsz=640, batch=8, device=device)
    return results
if __name__ == "__main__":
    train_single_gpu()
```
bash `python bug.py `,  the LOG displayed during training is normal
![image](https://github.com/ultralytics/ultralytics/assets/31611317/90dec06d-fcc7-41c9-8f13-e93325b488bd)

```python
def train_multi_gpu(device=[0, 1]):
    model = YOLO('yolov8s-seg.yaml').load('yolov8s-seg.pt')
    results = model.train(data='coco128-seg.yaml', epochs=100, imgsz=640, batch=8, device=device)
    return results
if __name__ == "__main__":
    train_multi_gpu()
```
bash `python bug.py `,  but the LOG displayed during the training process is abnormal, the mAP is very low, and the pretrained model may be loaded unsuccessfully.
![image](https://github.com/ultralytics/ultralytics/assets/31611317/7f8e30eb-3cf4-4a63-a217-d49e6e481dd1)

how to fix this bug? Thank you very much

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@PanJinquan hey there! 👋 Thanks for bringing this to our attention and for your willingness to help with a PR.

Based on what you've described, it seems like the issue might be related to the model loading process when using multiple GPUs. Here's a quick suggestion you might find useful:

When training on multiple GPUs with a pretrained model, ensure that the model is correctly loaded on all devices. Adjusting your `train_multi_gpu` function could be a starting point. Try explicitly pushing the model to the desired devices after loading:

```python
def train_multi_gpu(device=[0, 1]):
    model = YOLO('yolov8s-seg.yaml').load('yolov8s-seg.pt')
    # Ensure model is on correct devices for multi-GPU training
    model.to(device)
    results = model.train(data='coco128-seg.yaml', epochs=100, imgsz=640, batch=8, device=device)
    return results
```

Make sure to replace `model.to(device)` with the correct method based on the Ultralytics framework to ensure the model gets distributed across the specified GPUs.

This is just a quick tip that might help! If this doesn't solve the issue, I'd recommend diving deeper into the model's `.train()` implementation to ensure that multi-GPU support is effectively handled. 

Let me know how it goes, and if you need further assistance, don't hesitate to ask. Your contribution and willingness to submit a PR is greatly appreciated! 🙌
