### ISSUE TITLE
ONNXRuntime-Cpp and ONNXRuntime python give different results

### ISSUE THREAD

**Issue by OsamaAlAhmadieh** [ultralytics/ultralytics#10015]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Running the inference with ONNXRuntime using both [python](https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-ONNXRuntime) and [cpp](https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-ONNXRuntime-CPP)  provides different results. The Cpp results are completely wrong, where as the ones with python are correct. 

### Environment

Ultralytics YOLOv8.1.46 🚀 Python-3.10.14 torch-2.2.2 CUDA:0 (NVIDIA RTX 3500 Ada Generation Laptop GPU, 12010MiB)
Setup complete ✅ (28 CPUs, 62.4 GB RAM, 256.2/913.8 GB disk)

OS                  Linux-6.5.0-1019-oem-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.14
Install             git
RAM                 62.44 GB
CPU                 13th Gen Intel Core(TM) i7-13850HX
CUDA                12.1

matplotlib          ✅ 3.8.4>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.13.0>=1.4.1
torch               ✅ 2.2.2>=1.8.0
torchvision         ✅ 0.17.2>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.1>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Minimal Reproducible Example

No code, simply clone the repos and try with an image. I am using the usual: https://ultralytics.com/images/bus.jpg 

### Additional
Both of the examples are running on the CPU. 

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hey there! 👋

Thanks for bringing this to our attention! Differing results between ONNXRuntime-Cpp and ONNXRuntime-Python shouldn't happen, so we definitely want to get this sorted out for you. A common cause for such discrepancies could be the data preprocessing steps or the way the model input is prepared in C++ vs. Python.

Could you please ensure that:
1. The image is normalized in the same way in both environments (e.g., pixel values scaled to [0, 1]).
2. The dimensions of the input tensor match exactly between the two (both in shape and data layout).

Here's a quick Python example for image preprocessing, for reference:

```python
from PIL import Image
import torchvision.transforms as transforms

# Load image
image = Image.open('path/to/bus.jpg')

# Transform
transform = transforms.Compose([
    transforms.Resize((640, 640)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

# Apply transformations
image = transform(image).unsqueeze(0)  # Add batch dimension
```

Ensure that your C++ preprocessing mirrors this, especially the normalization and resizing parts. Sometimes, the devil is in the details with these transformations! 😀

If after checking these, the issue persists, it might be rooted deeper in the ONNX to C++ conversion. In that case, we'll gladly take a closer look. Could you please share the specific part of the C++ preprocessing code you're using via a PR or issue on GitHub? That way, we can dive in and assist more effectively.

Thanks for offering to help with a PR; we really appreciate your willingness to contribute! Let's get this figured out together. 🚀

**Comment by bnascimento** [comment]
I can also confirm that cpp results are wrong

**Comment by OsamaAlAhmadieh** [comment]
@glenn-jocher Thanks for your reply and apologies for the late response. I did a dirty workaround by creating a binding for the python onnxruntime in cpp. I will however, take a closer look at the onnxruntime-cpp and get back to solving this issue as the pybind workaround brings in some inefficiencies with it. Thanks for the starting points you mentioned :)

**Comment by glenn-jocher** [comment]
Hey there! No worries about the delay, and your workaround with pybind for integrating the ONNXRuntime Python in C++ sounds quite creative! 🛠️ It's fantastic that you're willing to dive deeper into the ONNXRuntime-CPP issue; those efficiency gains will surely be worth it when you crack it. Keep us posted on your progress or if you hit any snags. We're here to help! Happy coding! 😄

**Comment by davidbv01** [comment]
Hi, I'm dealing with the same problem, I've been trying with opencv DNN and I was getting strange results so I wanted to try with ONNX.
I have copied the repo and the boxes coming out of the model are totally out of place and meaningless.
Any progress on this?

Thanks

**Comment by glenn-jocher** [comment]
Hey there! 👋 It sounds like a tricky situation you've got. If the boxes are off with both OpenCV DNN and ONNX, it could be an issue with how the images are pre-processed or how outputs are interpreted. Double-check that the input image preprocessing in your ONNX setup mirrors that of the original YOLOv8 expectations - resizing without distorting aspect ratio, correct normalization, etc. Also, ensure to adjust the output processing to correctly map the detection boxes back onto the original image dimensions.

Here's a quick snippet for image preprocessing with ONNX in Python, make sure something similar is happening in your setup:

```python
import numpy as np
from PIL import Image

# Load and preprocess image
img = Image.open('path/to/your/image.jpg')
img = img.resize((640, 640)).convert('RGB')
img = np.array(img).astype(np.float32) / 255.0  # Normalize
img = np.transpose(img, [2, 0, 1])  # HWC to CHW
img = np.expand_dims(img, axis=0)  # Add batch dimension

# Don't forget to transform output boxes back to original image size if it's different!
```

If you're already doing something similar, let's take a closer look at how you're interpreting the model outputs. Sometimes, the devil is in the details with tensor shapes or scaling factors. 😅 If there's any specific code or error messages you're unsure about, feel free to share!

Good luck, and I'm here to help if you have more questions!

**Comment by bnascimento** [comment]
see the answer here: https://github.com/ultralytics/ultralytics/issues/7657#issuecomment-1940475053

**Comment by glenn-jocher** [comment]
@bnascimento hey there! 👋 Thanks for pointing that out! The linked comment indeed provides a helpful perspective on resolving the issue. If following those steps doesn't clear things up, or if there's more to dissect, feel free to share more details or questions. Happy coding! 😄

**Comment by davidbv01** [comment]
Hi, I have checked the image pre-processing and everything seems to be OK. The code in CPP acts the same as in python. I understand that the problem will come from the postprocessing of the model output. Attached is a screenshot of how I have nonsense values in the confidence values.

<img width="407" alt="image" src="https://github.com/ultralytics/ultralytics/assets/128252839/b9eba254-3c00-4086-ad7a-b896ca2217e5">

Any ideas? The code is the latest version posted in the repository. 

Thank you in advance

**Comment by glenn-jocher** [comment]
Hey there! 👋 Thanks for checking in and providing details on your setup. It's great to hear you've ensured the image pre-processing aligns between C++ and Python. If the confidence values are off, it suggests an issue with how the model's output is interpreted or scaled back in the post-processing step.

One common area that might cause discrepancies is the activation function applied to the output or how you're handling the model's raw predictions. In YOLO models, the confidence scores often need to be passed through a sigmoid function to convert them into probabilities between 0 and 1.

Here's a quick sanity check you can perform in C++ for the sigmoid part, assuming you have a confidence score `conf`:

```cpp
float sigmoid(float x) {
    return 1.0f / (1.0f + exp(-x));
}

// Apply sigmoid to each confidence value
float confProb = sigmoid(conf);
```

Make sure to apply this or a similar transformation to your confidence values if you haven't already. 😄

Could you also verify that you're correctly handling the model output's structure? YOLOv8's output might include objectness scores and class probabilities together, so parsing it correctly is crucial.

If the issue persists, a snippet of your post-processing code would be super helpful to provide more targeted advice. Thanks for your patience, and looking forward to resolving this together!

**Comment by davidbv01** [comment]
Hi there! I've tried adding the sigmoid snippet, but the bounding boxes still appear inconsistent. I've included the code snippet along with information about the versions used: Windows, OpenCV 4.7, CUDA 11.8, cuDNN 8.7, CMake 3.29, and C++20. Here's an example of the output image I obtain. Thanks for your help!

<img width="478" alt="image" src="https://github.com/ultralytics/ultralytics/assets/128252839/8e3b8b79-6da8-4457-abc0-e6b0e1f602b6">

`char* YOLO_V8::PreProcess(cv::Mat& iImg, std::vector<int> iImgSize, cv::Mat& oImg)
{
    if (iImg.channels() == 3)
    {
        oImg = iImg.clone();
        cv::cvtColor(oImg, oImg, cv::COLOR_BGR2RGB);
    }
    else
    {
        cv::cvtColor(iImg, oImg, cv::COLOR_GRAY2RGB);
    }

    switch (modelType)
    {
    case YOLO_DETECT_V8:
    case YOLO_POSE:
    case YOLO_DETECT_V8_HALF:
    case YOLO_POSE_V8_HALF://LetterBox
    {
        if (iImg.cols >= iImg.rows)
        {
            resizeScales = iImg.cols / (float)iImgSize.at(0);
            cv::resize(oImg, oImg, cv::Size(iImgSize.at(0), int(iImg.rows / resizeScales)));
        }
        else
        {
            resizeScales = iImg.rows / (float)iImgSize.at(0);
            cv::resize(oImg, oImg, cv::Size(int(iImg.cols / resizeScales), iImgSize.at(1)));
        }
        cv::Mat tempImg = cv::Mat::zeros(iImgSize.at(0), iImgSize.at(1), CV_8UC3);
        oImg.copyTo(tempImg(cv::Rect(0, 0, oImg.cols, oImg.rows)));
        oImg = tempImg;
        break;
    }
    case YOLO_CLS://CenterCrop
    {
        int h = iImg.rows;
        int w = iImg.cols;
        int m = min(h, w);
        int top = (h - m) / 2;
        int left = (w - m) / 2;
        cv::resize(oImg(cv::Rect(left, top, m, m)), oImg, cv::Size(iImgSize.at(0), iImgSize.at(1)));
        break;
    }
    }
    return RET_OK;
}


char* YOLO_V8::CreateSession(DL_INIT_PARAM& iParams) {
    char* Ret = RET_OK;
    std::regex pattern("[\u4e00-\u9fa5]");
    bool result = std::regex_search(iParams.modelPath, pattern);
    if (result)
    {
        Ret = "[YOLO_V8]:Your model path is error.Change your model path without chinese characters.";
        std::cout << Ret << std::endl;
        return Ret;
    }
    try
    {
        rectConfidenceThreshold = iParams.rectConfidenceThreshold;
        iouThreshold = iParams.iouThreshold;
        imgSize = iParams.imgSize;
        modelType = iParams.modelType;
        env = Ort::Env(ORT_LOGGING_LEVEL_WARNING, "Yolo");
        Ort::SessionOptions sessionOption;
        if (iParams.cudaEnable)
        {
            cudaEnable = iParams.cudaEnable;
            OrtCUDAProviderOptions cudaOption;
            cudaOption.device_id = 0;
            sessionOption.AppendExecutionProvider_CUDA(cudaOption);
        }
        sessionOption.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);
        sessionOption.SetIntraOpNumThreads(iParams.intraOpNumThreads);
        sessionOption.SetLogSeverityLevel(iParams.logSeverityLevel);

#ifdef _WIN32
        int ModelPathSize = MultiByteToWideChar(CP_UTF8, 0, iParams.modelPath.c_str(), static_cast<int>(iParams.modelPath.length()), nullptr, 0);
        wchar_t* wide_cstr = new wchar_t[ModelPathSize + 1];
        MultiByteToWideChar(CP_UTF8, 0, iParams.modelPath.c_str(), static_cast<int>(iParams.modelPath.length()), wide_cstr, ModelPathSize);
        wide_cstr[ModelPathSize] = L'\0';
        const wchar_t* modelPath = wide_cstr;
#else
        const char* modelPath = iParams.modelPath.c_str();
#endif // _WIN32

        session = new Ort::Session(env, modelPath, sessionOption);
        Ort::AllocatorWithDefaultOptions allocator;
        size_t inputNodesNum = session->GetInputCount();
        for (size_t i = 0; i < inputNodesNum; i++)
        {
            Ort::AllocatedStringPtr input_node_name = session->GetInputNameAllocated(i, allocator);
            char* temp_buf = new char[50];
            strcpy(temp_buf, input_node_name.get());
            inputNodeNames.push_back(temp_buf);
        }
        size_t OutputNodesNum = session->GetOutputCount();
        for (size_t i = 0; i < OutputNodesNum; i++)
        {
            Ort::AllocatedStringPtr output_node_name = session->GetOutputNameAllocated(i, allocator);
            char* temp_buf = new char[10];
            strcpy(temp_buf, output_node_name.get());
            outputNodeNames.push_back(temp_buf);
        }
        options = Ort::RunOptions{ nullptr };
        WarmUpSession();
        return RET_OK;
    }
    catch (const std::exception& e)
    {
        const char* str1 = "[YOLO_V8]:";
        const char* str2 = e.what();
        std::string result = std::string(str1) + std::string(str2);
        char* merged = new char[result.length() + 1];
        std::strcpy(merged, result.c_str());
        std::cout << merged << std::endl;
        delete[] merged;
        return "[YOLO_V8]:Create session failed.";
    }

}


char* YOLO_V8::RunSession(cv::Mat& iImg, std::vector<DL_RESULT>& oResult) {
#ifdef benchmark
    clock_t starttime_1 = clock();
#endif // benchmark

    char* Ret = RET_OK;
    cv::Mat processedImg;
    PreProcess(iImg, imgSize, processedImg);
    if (modelType < 4)
    {
        float* blob = new float[processedImg.total() * 3];
        BlobFromImage(processedImg, blob);
        std::vector<int64_t> inputNodeDims = { 1, 3, imgSize.at(0), imgSize.at(1) };
        TensorProcess(starttime_1, iImg, blob, inputNodeDims, oResult);
    }
    else
    {
#ifdef USE_CUDA
        half* blob = new half[processedImg.total() * 3];
        BlobFromImage(processedImg, blob);
        std::vector<int64_t> inputNodeDims = { 1,3,imgSize.at(0),imgSize.at(1) };
        TensorProcess(starttime_1, iImg, blob, inputNodeDims, oResult);
#endif
    }

    return Ret;
}


template<typename N>
char* YOLO_V8::TensorProcess(clock_t& starttime_1, cv::Mat& iImg, N& blob, std::vector<int64_t>& inputNodeDims,
    std::vector<DL_RESULT>& oResult) {
    Ort::Value inputTensor = Ort::Value::CreateTensor<typename std::remove_pointer<N>::type>(
        Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU), blob, 3 * imgSize.at(0) * imgSize.at(1),
        inputNodeDims.data(), inputNodeDims.size());
#ifdef benchmark
    clock_t starttime_2 = clock();
#endif // benchmark
    auto outputTensor = session->Run(options, inputNodeNames.data(), &inputTensor, 1, outputNodeNames.data(),
        outputNodeNames.size());
#ifdef benchmark
    clock_t starttime_3 = clock();
#endif // benchmark

    Ort::TypeInfo typeInfo = outputTensor.front().GetTypeInfo();
    auto tensor_info = typeInfo.GetTensorTypeAndShapeInfo();
    std::vector<int64_t> outputNodeDims = tensor_info.GetShape();
    auto output = outputTensor.front().GetTensorMutableData<typename std::remove_pointer<N>::type>();
    delete[] blob;
    switch (modelType)
    {
    case YOLO_DETECT_V8:
    case YOLO_DETECT_V8_HALF:
    {
        int strideNum = outputNodeDims[1];//8400
        int signalResultNum = outputNodeDims[2];//84

        std::vector<int> class_ids;
        std::vector<float> confidences;
        std::vector<cv::Rect> boxes;
        cv::Mat rawData;

        

        if (modelType == YOLO_DETECT_V8)
        {
            // FP32
            rawData = cv::Mat(strideNum, signalResultNum, CV_32F, output);
        }
        else
        {
            // FP16
            rawData = cv::Mat(strideNum, signalResultNum, CV_16F, output);
            rawData.convertTo(rawData, CV_32F);
        }
        
        //Note:
        //ultralytics add transpose operator to the output of yolov8 model.which make yolov8/v5/v7 has same shape
        //https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8n.pt
        //rawData = rawData.t();

        float* data = (float*)rawData.data;

        for (int i = 0; i < strideNum; ++i)
        {
            float* classesScores = data + 4;
            cv::Mat scores(1, this->classes.size(), CV_32FC1, classesScores);
            cv::Point class_id;
            double maxClassScore;
            cv::minMaxLoc(scores, 0, &maxClassScore, 0, &class_id);
            if (maxClassScore > rectConfidenceThreshold)
            {
                confidences.push_back(maxClassScore);
                class_ids.push_back(class_id.x);
                float x = data[0];
                float y = data[1];
                float w = data[2];
                float h = data[3];

                int left = int((x - 0.5 * w) * resizeScales);
                int top = int((y - 0.5 * h) * resizeScales);

                int width = int(w * resizeScales);
                int height = int(h * resizeScales);

                boxes.push_back(cv::Rect(left, top, width, height));
            }
            data += signalResultNum;
        }
        std::vector<int> nmsResult;
        cv::dnn::NMSBoxes(boxes, confidences, rectConfidenceThreshold, iouThreshold, nmsResult);
        for (int i = 0; i < nmsResult.size(); ++i)
        {
            int idx = nmsResult[i];
            DL_RESULT result;
            result.classId = class_ids[idx];
            result.confidence = confidences[idx];
            result.box = boxes[idx];
            oResult.push_back(result);
        }

#ifdef benchmark
        clock_t starttime_4 = clock();
        double pre_process_time = (double)(starttime_2 - starttime_1) / CLOCKS_PER_SEC * 1000;
        double process_time = (double)(starttime_3 - starttime_2) / CLOCKS_PER_SEC * 1000;
        double post_process_time = (double)(starttime_4 - starttime_3) / CLOCKS_PER_SEC * 1000;
        if (cudaEnable)
        {
            std::cout << "[YOLO_V8(CUDA)]: " << pre_process_time << "ms pre-process, " << process_time << "ms inference, " << post_process_time << "ms post-process." << std::endl;
        }
        else
        {
            std::cout << "[YOLO_V8(CPU)]: " << pre_process_time << "ms pre-process, " << process_time << "ms inference, " << post_process_time << "ms post-process." << std::endl;
        }
#endif // benchmark

        break;
    }
    case YOLO_CLS:
    case YOLO_CLS_HALF:
    {
        cv::Mat rawData;
        if (modelType == YOLO_CLS) {
            // FP32
            rawData = cv::Mat(1, this->classes.size(), CV_32F, output);
        } else {
            // FP16
            rawData = cv::Mat(1, this->classes.size(), CV_16F, output);
            rawData.convertTo(rawData, CV_32F);
        }
        float *data = (float *) rawData.data;

        DL_RESULT result;
        for (int i = 0; i < this->classes.size(); i++)
        {
            result.classId = i;
            result.confidence = data[i];
            oResult.push_back(result);
        }
        break;
    }
    default:
        std::cout << "[YOLO_V8]: " << "Not support model type." << std::endl;
    }
    return RET_OK;

}


char* YOLO_V8::WarmUpSession() {
    clock_t starttime_1 = clock();
    cv::Mat iImg = cv::Mat(cv::Size(imgSize.at(0), imgSize.at(1)), CV_8UC3);
    cv::Mat processedImg;
    PreProcess(iImg, imgSize, processedImg);
    if (modelType < 4)
    {
        float* blob = new float[iImg.total() * 3];
        BlobFromImage(processedImg, blob);
        std::vector<int64_t> YOLO_input_node_dims = { 1, 3, imgSize.at(0), imgSize.at(1) };
        Ort::Value input_tensor = Ort::Value::CreateTensor<float>(
            Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU), blob, 3 * imgSize.at(0) * imgSize.at(1),
            YOLO_input_node_dims.data(), YOLO_input_node_dims.size());
        auto output_tensors = session->Run(options, inputNodeNames.data(), &input_tensor, 1, outputNodeNames.data(),
            outputNodeNames.size());
        delete[] blob;
        clock_t starttime_4 = clock();
        double post_process_time = (double)(starttime_4 - starttime_1) / CLOCKS_PER_SEC * 1000;
        if (cudaEnable)
        {
            std::cout << "[YOLO_V8(CUDA)]: " << "Cuda warm-up cost " << post_process_time << " ms. " << std::endl;
        }
    }
    else
    {
#ifdef USE_CUDA
        half* blob = new half[iImg.total() * 3];
        BlobFromImage(processedImg, blob);
        std::vector<int64_t> YOLO_input_node_dims = { 1,3,imgSize.at(0),imgSize.at(1) };
        Ort::Value input_tensor = Ort::Value::CreateTensor<half>(Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU), blob, 3 * imgSize.at(0) * imgSize.at(1), YOLO_input_node_dims.data(), YOLO_input_node_dims.size());
        auto output_tensors = session->Run(options, inputNodeNames.data(), &input_tensor, 1, outputNodeNames.data(), outputNodeNames.size());
        delete[] blob;
        clock_t starttime_4 = clock();
        double post_process_time = (double)(starttime_4 - starttime_1) / CLOCKS_PER_SEC * 1000;
        if (cudaEnable)
        {
            std::cout << "[YOLO_V8(CUDA)]: " << "Cuda warm-up cost " << post_process_time << " ms. " << std::endl;
        }
#endif
    }
    return RET_OK;
}`

**Comment by glenn-jocher** [comment]
Hey there! From your description and the provided code snippets, it seems like the post-processing step, particularly for object detection outputs, might not be handling the model's output correctly, resulting in nonsensical confidence values and misplaced bounding boxes.

One potential issue could be how you're interpreting the model output dimensions and the scaling back of boxes to the original image dimensions. Here are a few points to consider:

1. **Output Dimensions**: Ensure you correctly understand the format and dimensions of the model's output tensor. YOLO models typically output a tensor with dimensions `[1, number_of_predictions, prediction_details]`, where prediction details might contain objectness score, class probabilities, and bounding box coordinates.

2. **Coordinate Scaling**: The bounding box coordinates predicted by the model are often normalized to the model's input dimensions. You need to scale these coordinates back to the original image dimensions.

3. **Sigmoid Activation**: It looks like you're already applying this in your code, but it's worth double-checking that the sigmoid function is correctly applied to objectness scores and class probabilities to convert them into proper probabilities.

4. **Data Format Conversion**: When converting data, especially when dealing with FP16 outputs, ensure the conversion is correctly handled before performing post-processing steps.

Considering these points, it's crucial to debug and verify each step of the post-processing pipeline. One way to do this is by logging or visually inspecting the intermediate values (objectness scores, class probabilities, and bounding box dimensions) before and after each transformation or scaling step.

Additionally, the `cv::dnn::NMSBoxes` function and the creation of bounding boxes seem correct at a glance, suggesting that the issue likely lies in how the raw model output is processed before these steps.

If you're still stuck, consider simplifying your post-processing routine to the absolute basics—get a single bounding box prediction working correctly first before scaling up to handling multiple detections.

Please make sure the model input and output handling matches precisely with the example provided in the Python version, as discrepancies in these areas are common culprits for such issues.

If specific areas in the post-processing code are still causing issues, feel free to share more focused snippets or logs of the intermediate steps for a deeper dive!

Happy debugging, and looking forward to getting your model predictions correctly mapped.

**Comment by devendraswamy** [comment]
I am also facing the same problem YOLOV5 model. While I am testing my Python ONNX code, all the bounding box (bbox) values are correct. However, when I perform the same process with my C++ code, I am getting incorrect bbox values.

the image processed in ptyhon code:
image_data = np.expand_dims(image_data, axis=0)  # Add batch dimension

and feed that image to python pyd file (c++ inference file complied to pyd)

auto output_tensors = session.Run(Ort::RunOptions{ nullptr }, input_names, &input_tensor, 1, output_names, 1);

**Comment by glenn-jocher** [comment]
@devendraswamy it seems like the issue might be related to how the input tensor is handled in C++. Ensure that the image preprocessing and tensor dimensions match exactly between your Python and C++ implementations. Double-check the input tensor shape and data type before feeding it into the model. If the problem persists, reviewing the specific preprocessing steps in your C++ code might help identify discrepancies.
