### ISSUE TITLE
Does YoloV8 train have the option of "--img-weights" like yoloV5?

### ISSUE THREAD

**Issue by IronmanVsThanos** [ultralytics/ultralytics#10010]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Does YoloV8 train have the option of "--img-weights" like yoloV5?

**Comment by glenn-jocher** [comment]
Hello! 😊 The YOLOv8 model training currently does not include an `"--img-weights"` option similar to YOLOv5. YOLOv8 training is designed to be effective and efficient with its default settings and hyperparameters. However, we're always looking to improve and add features that the community finds valuable. Your feedback is appreciated, and we'll consider this for future updates! Thanks for checking in. 🌟
