### ISSUE TITLE
Possible bug when training with multiple GPUs

### ISSUE THREAD

**Issue by N0lanakis** [ultralytics/ultralytics#10019]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Searching on the internet i found this article about augmentations in YOLO.
https://medium.com/@k.sunman91/data-augmentation-on-ultralytics-for-training-yolov5-yolov8-97a8dab31fef

When using one GPU all augmentations work properly. when i add 2 gpus with the command

# Train the model with 2 GPUs
from ultralytics import YOLO
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)
results = model.train(data='coco128.yaml', epochs=100, imgsz=640, device=[0, 1])

augmentation added skipped and use only the default.

if i run only results = model.train(data='coco128.yaml', epochs=100, imgsz=640)

everything works properly

**Comment by glenn-jocher** [comment]
Hello! Thanks for reaching out and providing detailed information about your issue. 🌟

It seems like you're encountering a problem with data augmentations when training on multiple GPUs. This could potentially be related to how data is distributed and processed across the GPUs.

Could you please ensure that your augmentation settings in the `coco128.yaml` or any custom data configuration file are correctly set up for multi-GPU training? Sometimes, specific settings or flags might need to be adjusted when scaling from a single GPU to multiple GPUs.

If the issue persists, it might be helpful to share the specific augmentation settings you're using, so we can further investigate the problem. Here's a quick check you can also perform:

```python
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')

# Train the model with 2 GPUs, explicitly specifying augmentation if needed
results = model.train(data='coco128.yaml', epochs=100, imgsz=640, device=[0, 1], augment=True)
```

Make sure `augment=True` is explicitly set if it's not defined in your YAML file. Let us know how it goes!
