### ISSUE TITLE
KeyError: 'vanillanetBlock' when I try to change v8's BackBone

### ISSUE THREAD

**Issue by muqiu791** [ultralytics/ultralytics#10029]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I am trying to change the YOLOv8 bcakbone to VanillaNet.
1. I downlowned the vanillanet.py from offical github  https://github.com/huawei-noah/VanillaNet in ultralytics/nn
2. then in tasks.py I make such changes
![image](https://github.com/ultralytics/ultralytics/assets/108570297/ce2dee64-dad1-457c-9b4d-0aca79aa50da)

4. I create a custom yaml file , and change it contents as follows:
```
# Ultralytics YOLO 🚀, GPL-3.0 license
 
# Parameters
nc: 80  # number of classes
depth_multiple: 1  # scales module repeats
width_multiple: 0.5  # scales convolution channels
 
# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 4, 4 ]] # 0-P2/4
  - [-1, 1, vanillanetBlock, [128, 1, 2]]  # 1-P2/8
  - [-1, 1, vanillanetBlock, [256, 1, 2]]  # 2-P2/16
  - [-1, 1, vanillanetBlock, [512, 1, 2]]  # 3-P2/32
  - [-1, 1, vanillanetBlock, [512, 1, 1]]  # 4-P3/32
  
# YOLOv8.0s head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']] #1/16
  - [[-1, 2], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 7
 
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']] #1/8
  - [[-1, 1], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 10 (P3/8-small)
 
  - [-1, 1, Conv, [256, 3, 2]] #1/16
  - [[-1, 7], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 13 (P4/16-medium)
 
  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 4], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 16 (P5/32-large)
 
  - [[10, 13, 16], 1, Detect, [nc]]  # Detect(P3, P4, P5)
 ```

But when I try to run my command line:
```
/hy-tmp/ultralytics# yolo detect train data=datasets/data.yaml model=yolov8_cust.yaml epochs=500 imgsz=640
```

The following error was encountered:
```
                   from  n    params  module                                       arguments                     
  0                  -1  1      1600  ultralytics.nn.modules.conv.Conv             [3, 32, 4, 4]                 
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/cfg/__init__.py", line 420, in entrypoint
    model = YOLO(model, task=task)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/engine/model.py", line 95, in __init__
    self._new(model, task)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/engine/model.py", line 131, in _new
    self.model = (model or self._smart_load('model'))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/tasks.py", line 232, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/tasks.py", line 678, in parse_model
    m = getattr(torch.nn, m[3:]) if 'nn.' in m else globals()[m]  # get module
KeyError: 'vanillanetBlock'
```

I have tried search similarity issues, but haven't found an answer yet.

Looking forward to your reply, thanks!

**Comment by glenn-jocher** [comment]
Hello! It looks like the issue is that the model doesn't recognize `vanillanetBlock` because it hasn't been imported or defined properly in your script. 😊 When you add a new module like `vanillanetBlock`, you need to ensure it's accessible in the namespace where your model is trying to use it.

Since you've placed `vanillanet.py` in `ultralytics/nn`, make sure that this module is properly imported in `tasks.py` or wherever you're attempting to use `vanillanetBlock`. Here's how you might do it:

1. **Import your custom block in the right place**: This could be at the beginning of `tasks.py` or within your custom YAML under the `backbone` section.

For example, in `tasks.py`:
```python
from ultralytics.nn.vanillanet import vanillanetBlock
```
Or directly in your custom YAML by specifying a custom module (though this would normally require direct support or a workaround within the Ultralytics framework, which typically expects a known set of modules).

2. **Double-check the name and location**: Make sure the name `vanillanetBlock` matches exactly between your `vanillanet.py` file and your YAML configuration. Also, ensure `vanillanet.py` is correctly placed so your project can recognize it.

If you continue encountering issues, consider defining `vanillanetBlock` within the script you're working on directly, or ensure the import paths are absolutely correct. Unfortunately, without direct support for externally defined modules in the configuration files (YAML), you might have to adjust the framework's code itself to correctly integrate new blocks like `vanillanetBlock`.

Hope this helps clear things up! If you need further assistance, feel free to post more details or questions. 🚀

**Comment by muqiu791** [comment]
Hello， thank you for your advice！
I solved the Keyerror by copy my vanillanet.py and tasks.py to the "/usr/local/lib/python3.8/dist-packages/ultralytics/nn"

But it gets a new problem that
```
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 5, in <module>
    from ultralytics.cfg import entrypoint
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/models/__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/models/rtdetr/__init__.py", line 3, in <module>
    from .model import RTDETR
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/models/rtdetr/model.py", line 3, in <module>
    from ultralytics.engine.model import Model
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/engine/model.py", line 9, in <module>
    from ultralytics.hub.utils import HUB_WEB_ROOT
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/hub/__init__.py", line 5, in <module>
    from ultralytics.data.utils import HUBDatasetStats
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/data/__init__.py", line 3, in <module>
    from .base import BaseDataset
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/data/base.py", line 19, in <module>
    from .utils import HELP_URL, IMG_FORMATS
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/data/utils.py", line 19, in <module>
    from ultralytics.nn.autobackend import check_class_names
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/__init__.py", line 3, in <module>
    from .tasks import (BaseModel, ClassificationModel, DetectionModel, SegmentationModel, attempt_load_one_weight,
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/tasks.py", line 11, in <module>
    from ultralytics.nn.modules import (
ImportError: cannot import name 'OBB' from 'ultralytics.nn.modules' (/usr/local/lib/python3.8/dist-packages/ultralytics/nn/modules/__init__.py)
```
 I check the task.py:
```
from ultralytics.nn.modules import (
    AIFI,
    C1,
    C2,
    C3,
    C3TR,
    OBB,
    SPP,
    SPPELAN,
    SPPF,
    ADown,
    Bottleneck,
    BottleneckCSP,
    C2f,
    C2fAttn,
    C3Ghost,
    C3x,
    CBFuse,
    CBLinear,
    Classify,
    Concat,
    Conv,
    Conv2,
    ConvTranspose,
    Detect,
    DWConv,
    DWConvTranspose2d,
    Focus,
    GhostBottleneck,
    GhostConv,
    HGBlock,
    HGStem,
    ImagePoolingAttn,
    Pose,
    RepC3,
    RepConv,
    RepNCSPELAN4,
    ResNetLayer,
    RTDETRDecoder,
    Segment,
    Silence,
    WorldDetect,
)
```
When imported here there are many modules that are not in the ultralytics/nn/modules/__init__.py, which contains as follows:
```
# Ultralytics YOLO 🚀, AGPL-3.0 license
"""
Ultralytics modules.

Example:
    Visualize a module with Netron.
    ```python
    from ultralytics.nn.modules import *
    import torch
    import os

    x = torch.ones(1, 128, 40, 40)
    m = Conv(128, 128)
    f = f'{m._get_name()}.onnx'
    torch.onnx.export(m, x, f)
    os.system(f'onnxsim {f} {f} && open {f}')
    ```
"""

from .block import (C1, C2, C3, C3TR, DFL, SPP, SPPF, Bottleneck, BottleneckCSP, C2f, C3Ghost, C3x, GhostBottleneck,
                    HGBlock, HGStem, Proto, RepC3)
from .conv import (CBAM, ChannelAttention, Concat, Conv, Conv2, ConvTranspose, DWConv, DWConvTranspose2d, Focus,
                   GhostConv, LightConv, RepConv, SpatialAttention)
from .head import Classify, Detect, Pose, RTDETRDecoder, Segment
from .transformer import (AIFI, MLP, DeformableTransformerDecoder, DeformableTransformerDecoderLayer, LayerNorm2d,
                          MLPBlock, MSDeformAttn, TransformerBlock, TransformerEncoderLayer, TransformerLayer)

__all__ = ('Conv', 'Conv2', 'LightConv', 'RepConv', 'DWConv', 'DWConvTranspose2d', 'ConvTranspose', 'Focus',
           'GhostConv', 'ChannelAttention', 'SpatialAttention', 'CBAM', 'Concat', 'TransformerLayer',
           'TransformerBlock', 'MLPBlock', 'LayerNorm2d', 'DFL', 'HGBlock', 'HGStem', 'SPP', 'SPPF', 'C1', 'C2', 'C3',
           'C2f', 'C3x', 'C3TR', 'C3Ghost', 'GhostBottleneck', 'Bottleneck', 'BottleneckCSP', 'Proto', 'Detect',
           'Segment', 'Pose', 'Classify', 'TransformerEncoderLayer', 'RepC3', 'RTDETRDecoder', 'AIFI',
           'DeformableTransformerDecoder', 'DeformableTransformerDecoderLayer', 'MSDeformAttn', 'MLP')
```
In fact I haven't changed either of these parts, so why the mismatch?
I hope I can get your help.

**Comment by muqiu791** [comment]
I have sovled the problem!
"ImportError" is that I didn't create a virtual env to install ultralytics,  but in the default base environment.

**So the contents of the ultraltics file in the base environment conflict with the contents of the ultralytics file in the documentation project.**

when I run my project in virtual envs, it worked!

**Comment by glenn-jocher** [comment]
Awesome to hear you've solved the problem! 🎉 Using a virtual environment can indeed help avoid such conflicts by isolating dependencies. Great job figuring it out, and if you have any more questions or run into further issues, feel free to reach out. Happy coding with YOLOv8! 😊

**Comment by fqutishat** [comment]
@muqiu791  I don't see vanillanetBlock define in https://github.com/huawei-noah/VanillaNet

**Comment by muqiu791** [comment]
> @muqiu791 I don't see vanillanetBlock define in https://github.com/huawei-noah/VanillaNet

![image](https://github.com/ultralytics/ultralytics/assets/108570297/1148a180-252d-416e-8bcd-0b22cd9c521d)

**Comment by glenn-jocher** [comment]
Hey there! 😊 It seems like `vanillanetBlock` might not be directly referenced with that name in the [VanillaNet repository](https://github.com/huawei-noah/VanillaNet). Sometimes, the name or the functionality we're looking for might be encapsulated within a larger structure or with a different name.

For integrating VanillaNet or similar modules as a backbone for YOLOv8, you might need to define `vanillanetBlock` yourself based on the building blocks available in VanillaNet, or adapt one of their existing modules to fit your needs.

If you're trying to use a specific part of VanillaNet as a block in YOLOv8, you may need to look into how VanillaNet structures its layers and replicate that logic in a custom block. For example, if VanillaNet has a sequence of convolutions and activations that you want to encapsulate as `vanillanetBlock`, you'd define it something like this:

```python
import torch.nn as nn

class vanillanetBlock(nn.Module):
    def __init__(self, in_channels, out_channels, stride):
        super(vanillanetBlock, self).__init__()
        # Your layer definitions here, mimicking VanillaNet's architecture
        
    def forward(self, x):
        # Forward pass
        return x
```
And then, you could use `vanillanetBlock` as outlined in your YOLOv8 custom architecture. If you have any specific features or layers from VanillaNet you're looking to integrate, sharing those details might help point you in the right direction more precisely! Happy coding! 🚀

**Comment by fqutishat** [comment]
@glenn-jocher  @muqiu791  thank you for your response.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance as you work with YOLOv8, don't hesitate to reach out. Happy coding! 😊
