### ISSUE TITLE
print results from model.predict not returning

### ISSUE THREAD

**Issue by faizelkDatapost** [ultralytics/ultralytics#1003]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I am running this and I am not getting anything back.
I understand that "verbose" prints detections on console if parsed as True. 

`from ultralytics import YOLO`
`model = YOLO("yolov8s.pt")`
`results = model.predict(source="myStreams.streams", save=False, classes=[2,5,6,7], conf=0.5, show=True, verbose=False)`
`print('##############################################################')`
`print(results)`

### Minimal Reproducible Example

`from ultralytics import YOLO`
`model = YOLO("yolov8s.pt")`
`results = model.predict(source="myStreams.streams", save=False, classes=[2,5,6,7], conf=0.5, show=True, verbose=False)`
`print('##############################################################')`
`print(results)`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@faizelkDatapost please try:
```python
from ultralytics import YOLO
model = YOLO("yolov8s.pt")
results = model.predict(source="myStreams.streams", save=False, conf=0.5, show=True, verbose=False, stream=True)
for result in results:
    print(result)
```

**Comment by faizelkDatapost** [comment]
this work, I can get box confidence and box classes. But what other info can i get? is there a page or file that lists everything that comes back from results?

`for result in results:`
        `print('######## box conf ##########')`
        `print(result.boxes.conf)  # confidence scores`
        `print('######## box class ##########')`
        `print(result.boxes.cls)    # class`

**Comment by faizelkDatapost** [comment]
realized that results are actually just box info. If i wanted anything extra i would have to do that in predict.py

**Comment by Dhamu785** [comment]
I want to print the confidence scores, I tried lot's of methods but it does not works

**Comment by pderrenger** [comment]
@Dhamu785 you can access the confidence scores of the detected boxes using the following approach:

```python
for result in results.xyxy[0]:
    print(result[4])  # Confidence scores
```

In this code, `results.xyxy[0]` contains the detected boxes, and for each box, the confidence score can be accessed using the index 4.

If you have any further questions or need assistance with anything else, feel free to ask!
