### ISSUE TITLE
Export a YOLOv8n model to a different format like ONNX

### ISSUE THREAD

**Issue by aliaminibagh** [ultralytics/ultralytics#1004]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

when I use this method :

```
model = YOLO('./model/best.pt')
model.export(format="onnx")
```

It returns this :

```
Evaluating: model.export(format="onnx") did not finish after 3.00 seconds.
This may mean a number of things:
- This evaluation is really slow and this is expected.
    In this case it's possible to silence this error by raising the timeout, setting the
    PYDEVD_WARN_EVALUATION_TIMEOUT environment variable to a bigger value.

- The evaluation may need other threads running while it's running:
    In this case, it's possible to set the PYDEVD_UNBLOCK_THREADS_TIMEOUT
    environment variable so that if after a given timeout an evaluation doesn't finish,
    other threads are unblocked or you can manually resume all threads.

    Alternatively, it's also possible to skip breaking on a particular thread by setting a
    `pydev_do_not_trace = True` attribute in the related threading.Thread instance
    (if some thread should always be running and no breakpoints are expected to be hit in it).

- The evaluation is deadlocked:
    In this case you may set the PYDEVD_THREAD_DUMP_ON_WARN_EVALUATION_TIMEOUT
    environment variable to true so that a thread dump is shown along with this message and
    optionally, set the PYDEVD_INTERRUPT_THREAD_TIMEOUT to some value so that the debugger
    tries to interrupt the evaluation (if possible) when this happens.
```

**What should I do to convert my best.pt model to best.onnx?**

**Comment by JustasBart** [comment]
Hi @aliaminibagh If CLI is optional for you this is how I export my models to be ran via OpenCV::dnn::ONNX C++:
```
yolo export \
model='yolov8s.pt' \
imgsz=[H,W] \
format=onnx \
opset=12
```
Hope this helps, good luck! :rocket:

**Comment by Laughing-q** [comment]
@aliaminibagh can you also try exporting a official model to see if the issue still happens to you?
```python
from ultralytics import YOLO

model = YOLO('yolov8n.pt')
model.export(format="onnx")
```
the above export script works fine to me.
![pic-full-230216-2009-43](https://user-images.githubusercontent.com/61612323/219361032-a5b1f809-5661-41e4-bf3a-18adb96c9b2e.png)

**Comment by aliaminibagh** [comment]
> @aliaminibagh can you also try exporting a official model to see if the issue still happens to you?
> 
> ```python
> from ultralytics import YOLO
> 
> model = YOLO('yolov8n.pt')
> model.export(format="onnx")
> ```
> 
> the above export script works fine to me. ![pic-full-230216-2009-43](https://user-images.githubusercontent.com/61612323/219361032-a5b1f809-5661-41e4-bf3a-18adb96c9b2e.png)

thanks a lot. problem be solved. It was solved by changing onnx version
