### ISSUE TITLE
simple suggestion:  added index digest on dockerhub

### ISSUE THREAD

**Issue by fantab01** [ultralytics/ultralytics#10043]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I have a simple suggestion for improvement. Last month, Dockerhub finally added the feature to separately add index digest and manifest digest. like this:
![image](https://github.com/ultralytics/ultralytics/assets/45958766/ec89e52b-bfa4-46e1-ad5d-cd676a2ccf71)
However, the Dockerhub page of ultralytics still only displays the Manifest digest. But when users pull the image locally, what is displayed is the index digest, making it impossible for users to compare the sha256 to ensure the image is intact.
![image](https://github.com/ultralytics/ultralytics/assets/45958766/6228c48a-99ec-4e16-9c67-b4d824186206)
![image](https://github.com/ultralytics/ultralytics/assets/45958766/87879c54-dd1b-43e0-9ba3-d7618f7a61c5)
 I hope that when uploading new versions on Dockerhub, the Index digest can be added for users to verify.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Thank you for bringing this to our attention and for the suggestion! 🙌

We appreciate your effort in pointing out the new Dockerhub feature that allows adding both index digest and manifest digest separately. This indeed seems like a practical enhancement to streamline the verification process for users when pulling our images. We'll look into incorporating index digests on our Dockerhub page for future versions. This change should make it easier for users to ensure the integrity of the images they download.

For now, if you're pulling an image and wish to verify it, you could use Docker's inspection commands to obtain more detailed information about the image, although we understand this isn't as straightforward as having the index digest readily available on Dockerhub.

We value your feedback and strive to improve the user experience and reliability of our software distribution. Stay tuned for updates, and feel free to reach out if you have more suggestions or questions!
