### ISSUE TITLE
The difference between YOLOv8.1 and YOLOv8.0 in background image (negative sample) processing

### ISSUE THREAD

**Issue by ten-exa** [ultralytics/ultralytics#10047]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hello。 Why does YOLOv8.1 background image participate in training, while YOLOv8.0 directly ignores the background image and does not participate in the training process. Which part of the code has a different design?

**Comment by glenn-jocher** [comment]
Hello! 👋 Great question regarding the differences in background image processing between YOLOv8.1 and YOLOv8.0.

The primary difference comes from an update in handling negative samples (background images) to improve model robustness against false positives. While YOLOv8.0 skips these images during training, YOLOv8.1 incorporates them, allowing the model to better learn what **not** to detect.

The change in design can be traced back to the dataset loading and augmentation steps in the training pipeline. In YOLOv8.1, background images are treated as training data with no objects (zero bounding boxes), contrasting with YOLOv8.0's approach to exclude them altogether.

The specific code modifications occur in the dataset preparation sections, where images are loaded and prepared for the model training process. You might find these changes in files related to dataset handling, particularly in the sections where images are filtered and augmented for training.

I hope this clarifies the adjustments made in the newer version of YOLOv8! If you're looking into adapting or exploring this feature, reviewing the dataset loading and preprocessing segments would be a good start. 🚀

**Comment by ten-exa** [comment]
Thank you for your answer. Thank you for bringing me great convenience with your work

**Comment by ten-exa** [comment]
In the past few days, I conducted comparative experiments on the performance of models with and without negative samples in my dataset, and the results showed that the false positive of the YOLOv8.1 model with negative samples added was lower than that of YOLOv9 and YOLOv8.0. Thank you for your efforts on this project

**Comment by glenn-jocher** [comment]
Thanks for sharing your findings! It's great to hear that including negative samples in your dataset has effectively reduced false positives in YOLOv8.1 🎉. Your comparative experiments provide valuable insights into how different versions handle false positives, especially the advantages of YOLOv8.1 in this aspect. If there's anything more you're curious about or if you need further assistance, feel free to ask. Keep up the great work experimenting with YOLO models!🚀
