### ISSUE TITLE
How to add and label a customized class

### ISSUE THREAD

**Issue by brucehacker66** [ultralytics/ultralytics#10057]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to use yolov8 pose to predict two classes: the person class and the robot arm class. The robot class is pretrained in the YOLOv8 pretrained model, and robot arm class is a customized class. Currently, I labeled the robot arm class with four key points like this:
`0 0.541667 0.303254 0.333333 0.571006 0.451667 0.535503 2 0.485000 0.269231 2 0.668333 0.213018 2 0.651667 0.310651 2`
But the model I trained only shows the robot arm class. I want it to detect the person class as well, using it pretrained weight. Some images in my dataset contain only a robot arm, and some contain both robot arm and person. I want to know that how to annotate the dataset if both person and robot arm classes appear in the image? And How to annotate the dataset if only robot arm class appear? I want to use the pretrained weight for person class to save the effort for annotations.
In my data.yaml file, I use this for classes:
# Classes
names:
  0: robot-arm
  1: person
  
  Thank you so much!

**Comment by glenn-jocher** [comment]
Hey there! 🚀 It sounds like you're working on a fascinating project with YOLOv8. To use a combination of pretrained and custom classes (like your `person` and `robot-arm` classes) in your dataset, follow these guidelines:

1. **Annotate your Custom Class**: You've done this correctly for your `robot-arm`. Important to note, keypoints for custom classes are labelled following the format:

   ```plaintext
   <class_id> <x_center> <y_center> <width> <height> <keypoint1_x> <keypoint1_y> <keypoint1_vis> <keypoint2_x> <keypoint2_y> <keypoint2_vis> ...
   ```

   - `<class_id>` for your custom class should start from where the pretrained classes end. For example, if `person` is your last pretrained class, then `robot-arm` can be `1` assuming `person` is `0`.
   - `<keypoint_vis>` represents the visibility of each keypoint (typically set to `2` for visible keypoints).

2. **Annotate Pretrained Classes**: When a `person` class appears in an image, you can annotate it in a simpler format since it might not require keypoints (unless you're extending or modifying the existing keypoints). Use the standard bounding box annotation format for the YOLO model:

   ```plaintext
   <class_id> <x_center> <y_center> <width> <height>
   ```

   For images containing both `robot-arm` and `person`, ensure both types of annotations are present in the same label file, one annotation per line.

3. **Dataset YAML File**: Your `data.yaml` looks good. Just ensure the `names` correctly reflect the class IDs as mentioned:

   ```yaml
   # Classes
   names:
     0: person
     1: robot-arm
   ```

4. **Training**: When training, if you use both custom and pretrained classes, ensure your model knows which classes are which. Since YOLOv8 seamlessly integrates pretrained weights, it should automatically do so for the `person` class. Your custom `robot-arm` class will be learned during training.

For images with only the robot arm, include only `robot-arm` annotations. The model, when trained correctly, will recognize and distinguish between images with `persons`, `robot-arms`, and both.

This approach leverages pretrained weights where possible while allowing the model to learn about new classes. Keep rocking your project! 💪

**Comment by brucehacker66** [comment]
Thank you for this! It is really helpful. I have some questions based on your response.
1. Can I set 0 for robot-arm and 1 for person or I must use 0 for person and 1 for robot-arm?
2. If 2 classes appear in one image, if I do one annotation per line, do I need to extend the annotation for person class by 0 so that the length of the two lines match?
3. What 'kpt_shape' should I use in the data.yaml file? Currently for robot-arm only, I use `kpt_shape: [4, 3]`.
4. How do I ensure which classes are which in the training process? Do I need to change the weighs?

Thank you so much!!

**Comment by brucehacker66** [comment]
@glenn-jocher Please help me if you see this! Thanks

**Comment by glenn-jocher** [comment]
@brucehacker66 absolutely, happy to assist! 🌟

1. You're free to assign class IDs as you prefer; just ensure they are consistent across your annotations and `data.yaml`.

2. For annotations, no need to pad with zeros—the model distinguishes based on the format. Just annotate each object on a new line as per its type (with keypoints for `robot-arm`, without for `person`).

3. `kpt_shape` for `robot-arm` should indeed be `[4, 3]` if you have 4 keypoints per `robot-arm` instance. This indicates 4 keypoints, each with an `(x, y, visibility)` triplet.

4. The model automatically recognizes classes from your annotations and `data.yaml`. No need to alter weights for distinguishing classes; just ensure the pretrained model you're starting from supports pose estimation if you're integrating custom keypoints.

Let me know if there's anything more I can clarify!

**Comment by brucehacker66** [comment]
@glenn-jocher Thank you so much for your advice. I have the annotation 
`0 0.497656 0.732292 0.229688 0.527083 0.475000 0.829167 2 0.462500 0.564583 2 0.575000 0.618750 2 0.590625 0.685417 2
1 0.346094 0.732292 0.348437 0.514583
`
And in my data.yaml file I have:
`
kpt_shape: [4, 3]  
names:
  0: robot-arm
  1: person`

I got the error: ` File "D:\anaconda\envs\rspc\lib\site-packages\ultralytics\data\base.py", line 73, in __init__
    self.labels = self.get_labels()
  File "D:\anaconda\envs\rspc\lib\site-packages\ultralytics\data\dataset.py", line 127, in get_labels
    len_cls, len_boxes, len_segments = (sum(x) for x in zip(*lengths))
ValueError: not enough values to unpack (expected 3, got 0)
`

I have checked that all the images are labeled in the way you suggest. Could you help with this? Thanks!

**Comment by glenn-jocher** [comment]
@brucehacker66 hey there! 👋  Based on the error and your annotations, it seems like everything should be set correctly on your end as per our earlier conversation. However, the error suggests an issue when unpacking values for class lengths, bounding boxes, and segments, which hints at possibly empty or incorrectly formatted label files.

Here's a quick checklist to troubleshoot:
- Ensure all label files are non-empty and correctly formatted.
- Double-check paths to images and labels in your dataset declaration are accurate and accessible.
- Verify that every image has a corresponding label file, even if it contains no annotations (an empty label file is better than no file).

For your `data.yaml`, the setup looks right for using 4 keypoints for the `robot-arm` class. Just a reminder to make sure the indentations in the YAML file are correct, as YAML files are indentation-sensitive.

If the issue persists, a closer look at the specific dataset contents and perhaps a minimal reproducible example might help to dig deeper! Keep me posted. 😊

**Comment by brucehacker66** [comment]
@glenn-jocher Thank you so much for this. I have checked all the labels and images to ensured that the images are correctly labeled. The only thing that I am not sure is that in the data.yaml file, do we need to specify the path for labels folder? When I trained only one class for robot-arm, I could train successfully. Here's my data.yaml file:
![image](https://github.com/ultralytics/ultralytics/assets/88654703/e5d4fc2f-9dad-4178-b2ba-a42ee87fc5c9)
Thank you so much!

**Comment by glenn-jocher** [comment]
Hey there! 😊 It looks like you're making great progress with your project. Regarding your query about the `data.yaml` file, yes, you do need to specify paths for both your images and label folders under the train, val (and optionally test) sections in your `data.yaml` file. It usually looks something like this:

```yaml
train: path/to/your/train/images
val: path/to/your/val/images

# Your class names will follow here
names:
  0: robot-arm
  1: person
```

Make sure the paths are correct and point directly to the folders containing your images. For the labels, they should be in the same directory as their corresponding images, following the YOLO naming convention (`imagename.txt` for `imagename.extension`).

The warnings and errors you're encountering could likely result from the path mismatches or missing label files for some images. Double-check those paths in your `data.yaml`, and ensure each image file has a corresponding label file, even if it's empty for images with no detected objects.

Keep going; you're on the right path! 🚀 Let me know if there's anything else I can help with.

**Comment by brucehacker66** [comment]
@glenn-jocher Thank you for your response. I modify the data.yaml file as:
![image](https://github.com/ultralytics/ultralytics/assets/88654703/e12cd6e0-2f1a-4084-9735-49178a72e36e)
My train images have path:
`robot-safety-detection\testdata\train\images`
train labels:
`robot-safety-detection\testdata\train\labels`
Val images:
`robot-safety-detection\testdata\val\images`
Val labels:
`robot-safety-detection\testdata\val\labels`

I still have this issue. I am very confused because the same path works for my one class detection for robot-arm, but does not work for two classes. Could you help with this? Thank you so much.

**Comment by glenn-jocher** [comment]
Hey there! 😊 It sounds like you're almost there. Based on what you've shared, your directory structure looks correct for a YOLOv8 project. If it worked for one class but not for two, the issue could be related to the formatting or content of your label files for the second class.

One common pitfall is the class indices in the annotations. Ensure that for your two classes, the indices in your label files are correct, i.e., `0` for `robot-arm` and `1` for `person`. 

Also, double-check the `data.yaml` file format. It should look something like this, based on your directory paths:

```yaml
train: robot-safety-detection/testdata/train/images
val: robot-safety-detection/testdata/val/images

names:
  0: robot-arm
  1: person
```

Remember, both the path in the YAML and the format/class indices in your labels play a crucial role. If there's a minor typo or misconfiguration, it could lead to issues.

As a quick tip, try manually inspecting a few label files for both classes to confirm the formatting and class indices are consistent with your `data.yaml`. 

Keep the momentum going, and feel free to reach out with any updates or further questions! 👍

**Comment by brucehacker66** [comment]
@glenn-jocher Thank you so much for your advice. I can confirm that all the annotation I made have the following format:
![image](https://github.com/ultralytics/ultralytics/assets/88654703/7523d13d-15f1-40f6-9a1b-8dcf0a76a20e)
I have the data.yaml file unchanged and modified the annotation to just include class 0 (robot-arm), and the train was successful. But when I add the two rows of class 1 (person) back, the error occurs. I am thinking about if there's anything wrong with the person class annotation. Thanks!

**Comment by brucehacker66** [comment]
@glenn-jocher Thank you for your advice. I am confused about how you want me to change the annotation for person class. I want to detect the pose (keypoints) for both person and robot-arm, and I want to use the pretrained pose detection for person and add my customized robot-arm class. I already have the person class label as `class_id x_center y_center width height`  way and my robot-arm class will have 4 keypoints, How should I do that? Can you give me an example for an annotation with these two classes and how should I configure my data.yaml file? I think I already configured the dataset and yaml file as the way you described above. Thank you a lot.

**Comment by Gray-Stone** [comment]
I would like to follow up on this question:

What should I do if the pre-trained model have lots of existing labels ? For example the pretrained yolo model have 80 classes in it from COCO dataset. If I want to add the 81 th class, Do I only add 

```
names:
  81: new_class
```
or do I have to re-specify all the old classes? And what happen if I specified the existing class with different name?

**Comment by glenn-jocher** [comment]
Hey there! 😊 When adding a new 81st class to a pretrained model with 80 classes, you should include all original classes plus the new one in your `data.yaml`, like this:

```yaml
names:
  0: class0
  ...
  79: class79
  80: new_class
```

It's important to list all original classes to maintain the correct order and class IDs. Changing the names of existing classes is okay as long as their order is preserved because YOLO uses class IDs (not names) during training and inference. Just ensure the new class gets a unique ID following the last original class.

Happy model tuning! 🚀

**Comment by riubotin** [comment]
Hello everyone, How to Train YOLO Model for Specific Vehicle Types (e.g., 4-Wheel Truck, 6-Wheel Truck, Large Bus, Small Bus)?

I am currently using the YOLO object detection model to automatically annotate images of various vehicles. My dataset includes different types of trucks (e.g., 4-wheel, 6-wheel) and buses (e.g., large, small). However, the default YOLO model does not differentiate between these specific types of vehicles.

Could anyone guide me on how to train a YOLO model to recognize and label these specific vehicle types? Here are some specific questions I have:
1. Dataset Preparation: What is the best way to collect and annotate a dataset with these specific vehicle types? Are there any recommended tools or best practices for this?
2. Model Training: How should I configure the YOLO model for training with these new labels? Are there any specific parameters or settings I should be aware of?
3. Model Integration: Once the model is trained, how can I integrate it into my existing pipeline to replace the default YOLO model?
Performance Optimization: Any tips on optimizing the model's performance for detecting these specific vehicle types, especially in terms of accuracy and speed?
I appreciate any advice or resources you can provide. Thank you!
Best regards.
![Capture](https://github.com/ultralytics/ultralytics/assets/40457741/e9437bc1-0eec-44da-a8a8-6b242b1dfd90)
