### ISSUE TITLE
Can you help me write a full version of the YOLOv8-OpenCV-ONNX-Python file that identifies video streams?

### ISSUE THREAD

**Issue by liuliwenqing** [ultralytics/ultralytics#10051]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can you help me write a full version of the YOLOv8-OpenCV-ONNX-Python file that identifies video streams?

**Comment by glenn-jocher** [comment]
Certainly! Here's a concise example to get you started with using YOLOv8 with OpenCV and ONNX for video stream detection in Python. 😊

```python
import cv2
import numpy as np
import onnxruntime as ort

# Load the ONNX model
sess = ort.InferenceSession('path/to/your/model.onnx')

# Define the preprocessing function
def preprocess(image):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = cv2.resize(image, (640, 640))
    image = image / 255.0
    image = np.transpose(image, (2, 0, 1))
    image = np.expand_dims(image, axis=0).astype(np.float32)
    return image

# Process the video stream
cap = cv2.VideoCapture(0)  # Use 0 for the default webcam

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Preprocess the frame
    input_tensor = preprocess(frame)

    # Inference
    outputs = sess.run(None, {'images': input_tensor})
    detections = outputs[0]

    # TODO: Postprocess `detections` and visualize them on `frame`
    # This step depends on your model's output format

    cv2.imshow('YOLOv8 Detection', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):  # Press 'q' to quit
        break

cap.release()
cv2.destroyAllWindows()
```

Note: This script assumes you have an ONNX YOLOv8 model at `'path/to/your/model.onnx'`. You'd need to adjust the path to your actual model file. Furthermore, the visualization part (drawing the bounding boxes and labels on the frame) depends on your model's specific output format, so you'll need to tailor the postprocessing part accordingly.

Feel free to adjust the `cv2.VideoCapture(0)` parameter if you're streaming from another source besides the default webcam, and ensure you have `opencv-python` and `onnxruntime` installed. 

Happy coding! 🚀
