### ISSUE TITLE
Error for multiple GPU running

### ISSUE THREAD

**Issue by Jessica-hub** [ultralytics/ultralytics#10065]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I'm trying to run my trainning on two GPUs in one machine. It works when I use only one GPU by setting device=0 when I try to set it as device=[0,1]. An error came up. PS: It is an Ubuntu system. 

The GPU information on the machine is shown below. 
Mon Apr 15 23:32:34 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.171.04             Driver Version: 535.171.04   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A4000               Off | 00000000:03:00.0 Off |                  Off |
| 41%   35C    P8               6W / 140W |      8MiB / 16376MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A6000               Off | 00000000:B3:00.0  On |                  Off |
| 58%   70C    P8              50W / 300W |    248MiB / 49140MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1732      G   /usr/lib/xorg/Xorg                            4MiB |
|    1   N/A  N/A      1732      G   /usr/lib/xorg/Xorg                          213MiB |
|    1   N/A  N/A      1973      G   /usr/bin/gnome-shell                         27MiB |
+---------------------------------------------------------------------------------------+

Error information is below.

yolo task=obb mode=train model=./ultralytics/cfg/models/v8/yolov8l-obb.yaml  data=../datasets/pLdata640.yaml imgsz=640 epochs=2000  patience=500 batch=64 device=[0,1] single_cls=True project=../logs/ name=obb_imgsz640_2000 pretrained=yolov8l-obb.pt
Transferred 631/637 items from pretrained weights
Ultralytics YOLOv8.1.47 🚀 Python-3.10.9 torch-2.0.1+cu117 CUDA:0 (NVIDIA RTX A6000, 48669MiB)
                                                           CUDA:1 (NVIDIA RTX A4000, 16109MiB)
engine/trainer: task=obb, mode=train, model=./ultralytics/cfg/models/v8/yolov8l-obb.yaml, data=../datasets/pLdata640.yaml, epochs=2000, time=None, patience=500, batch=64, imgsz=640, save=True, save_period=-1, cache=False, device=[0, 1], workers=8, project=../logs/, name=obb_imgsz640_20002, exist_ok=False, pretrained=yolov8l-obb.pt, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=True, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=../logs/obb_imgsz640_20002
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments                     
  0                  -1  1      1856  ultralytics.nn.modules.conv.Conv             [3, 64, 3, 2]                 
  1                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  2                  -1  3    279808  ultralytics.nn.modules.block.C2f             [128, 128, 3, True]           
  3                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  4                  -1  6   2101248  ultralytics.nn.modules.block.C2f             [256, 256, 6, True]           
  5                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]              
  6                  -1  6   8396800  ultralytics.nn.modules.block.C2f             [512, 512, 6, True]           
  7                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]              
  8                  -1  3   4461568  ultralytics.nn.modules.block.C2f             [512, 512, 3, True]           
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  3   4723712  ultralytics.nn.modules.block.C2f             [1024, 512, 3]                
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  3   1247744  ultralytics.nn.modules.block.C2f             [768, 256, 3]                 
 16                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  3   4592640  ultralytics.nn.modules.block.C2f             [768, 512, 3]                 
 19                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  3   4723712  ultralytics.nn.modules.block.C2f             [1024, 512, 3]                
 22        [15, 18, 21]  1   6432406  ultralytics.nn.modules.head.OBB              [1, 1, [256, 512, 512]]       
YOLOv8l-obb summary: 390 layers, 44479446 parameters, 44479430 gradients, 169.1 GFLOPs

Transferred 631/637 items from pretrained weights
DDP: debug command /home/cetin/miniconda3/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 36659 /home/cetin/.config/Ultralytics/DDP/_temp_wxge7luz140258345716608.py
Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp-a34b3233.so.1 library.
	Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
Traceback (most recent call last):
  File "/home/cetin/miniconda3/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/cetin/Shuaiang/yolov8/ultralytics/cfg/__init__.py", line 582, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/cetin/Shuaiang/yolov8/ultralytics/engine/model.py", line 668, in train
    self.trainer.train()
  File "/home/cetin/Shuaiang/yolov8/ultralytics/engine/trainer.py", line 193, in train
    raise e
  File "/home/cetin/Shuaiang/yolov8/ultralytics/engine/trainer.py", line 191, in train
    subprocess.run(cmd, check=True)
  File "/home/cetin/miniconda3/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/cetin/miniconda3/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '36659', '/home/cetin/.config/Ultralytics/DDP/_temp_wxge7luz140258345716608.py']' returned non-zero exit status 1.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hey there! 👋 It seems like you're encountering an error when trying to run your training on multiple GPUs. Based on the error message you provided, it looks like there's a compatibility issue with MKL and OpenMP (libgomp). This is a known issue when using Intel's MKL with other libraries that rely on OpenMP.

Here's a quick workaround for your environment that might help resolve the issue. You can set the environment variable `MKL_SERVICE_FORCE_INTEL` to `TRUE` before running your training script to force MKL to use its own threading layer, which should be compatible. You can do this by running the following command in your terminal:

```bash
export MKL_SERVICE_FORCE_INTEL=TRUE
```

After setting this environment variable, try running your training command again:

```bash
yolo task=obb mode=train model=./ultralytics/cfg/models/v8/yolov8l-obb.yaml data=../datasets/pLdata640.yaml imgsz=640 epochs=2000 patience=500 batch=64 device=[0,1] single_cls=True project=../logs/ name=obb_imgsz640_2000 pretrained=yolov8l-obb.pt
```

This should help bypass the threading layer compatibility issue. If the problem persists, feel free to reply here. We're here to help! 🚀
