### ISSUE TITLE
How can I use cv2.fillPoly to draw masks ?

### ISSUE THREAD

**Issue by AndreiVoian** [ultralytics/ultralytics#1011]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! I want to draw masks with cv2.fillPoly. How can I achieve this?

Thanks!

**Comment by Laughing-q** [comment]
@AndreiVoian you mean you want to get the bounding coordinates of segment?
please check the docs, [https://docs.ultralytics.com/predict/#masks](https://docs.ultralytics.com/predict/#masks), `masks.segments` is the bounding coordinates.
