### ISSUE TITLE
yolov8 to detect and classify at the same time

### ISSUE THREAD

**Issue by islemgh25** [ultralytics/ultralytics#10114]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I need to train yolov8 to detect objects, and then classify if they are in the center of the frame or not. I can't add center detection post-process because I need to save the final model and deploy it in a mobile app, so how do I make this work using  yolov8?

**Comment by glenn-jocher** [comment]
Hello there! 🚀 It sounds like you're looking to leverage YOLOv8 for both object detection and a specialized form of classification based on object positioning. While directly training YOLO to classify objects as centered or not isn't a standard feature, you can approach this challenge creatively.

You could train a YOLOv8 model on a custom dataset that includes a new class label for objects that are "centered." These labels could be based on whether the object's bounding box intersects with a predefined "center" area of your images. Here's a simplified example of how you might prepare your dataset labeling for this:

1. Decide on what constitutes "center" in your frame (e.g., a central square that covers 25% of the frame).
2. Label your objects as usual with YOLO. For those within the center as defined above, append "_centered" to the class name or use a distinct class ID.

When deploying, the model will inherently learn to detect objects and discriminate based on their position relative to the frame's center.

Your training command can stay standard:

```bash
yolo detect train data=your_custom_dataset.yaml model=yolov8n.yaml epochs=100 imgsz=640
```

Ensure your `your_custom_dataset.yaml` correctly points to your dataset with the newly labeled classes.

This method encapsulates your "center detection" requirement directly into the detection framework, simplifying deployment on mobile by avoiding additional post-processing steps.

Hope this helps guide you in the right direction! Happy coding!

**Comment by islemgh25** [comment]
Thank you for recommending this interesting approach, I will be working on that and see where it will lead

**Comment by glenn-jocher** [comment]
I'm glad you found the approach interesting! 😊 If you hit any roadblocks or have further questions while implementing it, don't hesitate to reach out. Happy experimenting, and I'm excited to see what you'll achieve with YOLOv8!
