### ISSUE TITLE
botsort.yaml tracking args and ReID

### ISSUE THREAD

**Issue by AlbertFlorinus** [ultralytics/ultralytics#10113]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I was wondering how to interpret the arguments in botsort.yaml.

track_high_thresh: 0.5 # threshold for the first association
track_low_thresh: 0.1 # threshold for the second association
match_thresh: 0.8 # threshold for matching tracks

When calling track like this (agent Is a custom class)
results : Results = agent.model.track(source=frame, device=agent.device ,conf=agent.conf, iou=agent.iou, persist=True, verbose=True)[0]

1. Will track_high_thresh be set to agent.conf? Or is it set by the yaml file even when providing this argument? My intention is for agent.conf to only change the prediction thresholding, not tracking thresholding.

2. track_low_thresh. Is this value the absolute difference in confidence for that specific class from the previous frame?

3. match_thresh, how can I interpret this value?

# ReID model related thresh (not supported yet)
proximity_thresh: 0.5
appearance_thresh: 0.25
with_reid: False

4. are proximity_thresh and appearance_thresh related to ReID and thus not used atm?

5. Is there a planned release of ReID support? Or any tips for contributing to this feature? This feature would be crucial for my implementation. thanks

**Comment by glenn-jocher** [comment]
Hi there! 🖐️ Great questions about tracking parameters in the `botsort.yaml` config. Let's quickly go through your queries:

1. **track_high_thresh** and **track_low_thresh** are specified by the `botsort.yaml` and are separate from any `conf` argument you pass during tracking. The `conf` argument indeed modifies prediction confidence thresholding, not tracking thresholding.

2. **track_low_thresh** is not about the difference in confidence from the previous frame. It's a lower threshold for associating detections with existing tracks when the high confidence association (above `track_high_thresh`) fails.

3. **match_thresh** is used to decide if a detected object and an existing track are the same based on their feature similarity. A higher value means stricter matching criteria.

4. You're right; both **proximity_thresh** and **appearance_thresh** are related to a ReID feature that's not supported yet, meant to assess spatial closeness and appearance similarity.

5. Regarding ReID support, there’s no official release date yet, but the community and Ultralytics team are always working on enhancements! If you're interested in contributing, especially around ReID, that would be fantastic! The best way would be to discuss your thoughts or proposed approach in the [GitHub discussions](https://github.com/ultralytics/ultralytics/discussions) to get feedback from the community and the developers. 🚀

Hope this clarifies things! If you have more questions or need further assistance, feel free to ask.
