### ISSUE TITLE
YOLO8 program packaged with pyinstaller does not work properly

### ISSUE THREAD

**Issue by WISHF-Amoy** [ultralytics/ultralytics#10115]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I commented out the LOGGER in ultralytics to avoid not being able to pyinstaller packaged out of the program does not work, package command: pyinstaller --collect-data ultralytics -w new_main.py

However, the program now works, but when the function containing the YOLO model prediction is started, the program blinks twice, the console appears momentarily, and then a new My Programs screen appears, but the YOLO prediction doesn't work properly, and the program may flashback!

**Comment by WISHF-Amoy** [comment]
The strangest thing is why my program GUI appears a new one after starting YOLO predictions and YOLO predictions don't work right immediately, it needs some time to work after I close the new GUI.

**Comment by glenn-jocher** [comment]
Hi there! It sounds like you're encountering a unique issue with your PyInstaller-packaged program and YOLO predictions. Based on your description, it seems the problem might be related to how the packaged application handles subprocesses or console windows spawned by the YOLO model prediction.

It's possible that the PyInstaller configuration or environment settings may need adjustment to ensure compatibility with the way YOLO operates. One potential workaround is to investigate how the YOLO prediction function initiates and whether it's attempting to open a new console or GUI window inadvertently. 

If you're using Python's `subprocess` module or similar in your prediction function, ensuring that no new console windows are created might help. For instance, using `subprocess.Popen` with specific arguments to prevent window popping can be a good start:

```python
import subprocess

subprocess.Popen(..., creationflags=subprocess.CREATE_NO_WINDOW)
```

Please give this approach a try and let us know if it resolves the issue or if the problem persists. We're here to help! 🚀

**Comment by WISHF-Amoy** [comment]
> Hi there! It sounds like you're encountering a unique issue with your PyInstaller-packaged program and YOLO predictions. Based on your description, it seems the problem might be related to how the packaged application handles subprocesses or console windows spawned by the YOLO model prediction.
> 
> It's possible that the PyInstaller configuration or environment settings may need adjustment to ensure compatibility with the way YOLO operates. One potential workaround is to investigate how the YOLO prediction function initiates and whether it's attempting to open a new console or GUI window inadvertently.
> 
> If you're using Python's `subprocess` module or similar in your prediction function, ensuring that no new console windows are created might help. For instance, using `subprocess.Popen` with specific arguments to prevent window popping can be a good start:
> 
> ```python
> import subprocess
> 
> subprocess.Popen(..., creationflags=subprocess.CREATE_NO_WINDOW)
> ```
> 
> Please give this approach a try and let us know if it resolves the issue or if the problem persists. We're here to help! 🚀

I may not used `subprocess` module or similar, I only used `pyqt5` to complete a GUI, in which the user clicks on the `start` button, it will start to execute the recognition task using `YOLO8`, then according to the recognition results some data will be sent through the serial portto the hardware device.

The pseudo-code is as follows:
```
class Window(QMainWindow):
    def __init__(self):
        self.timer = QTimer()
        self.timer.timeout.connect(self.LoopFunction)


    def LoopFunction(self):
        predict_result = GetPredict(image)
        SendData(predict_result)

    def start_loop(self):
        self.timer.start(1000)

```

In the `LoopFunction` , it will call other fucntion to select target window to get screen-shot and then send to `GetPredict` for YOLO8 to predict:

```

def GetPredict(image):
    results = model(image)
    for i, r in enumerate(results):
        im_bgr = r.plot()  # BGR-order numpy array
        im_rgb = Image.fromarray(im_bgr[..., ::-1])  # RGB-order PIL image
        predict_result = None

        return predict_result

```

After my test, I find that `results = model(image)` cause the problem, that is YOLO8 function from `ultralytics` so I want to know where should I modify my code, thanks a lot for your help!

**Comment by glenn-jocher** [comment]
@WISHF-Amoy hey! Thanks for sharing more details. It seems like the `model(image)` function from Ultralytics YOLOv8 might be causing the issues you're experiencing. If it's about handling the GUI and predictions without interruptions, consider running YOLOv8 predictions in a separate thread or using a `QThread` in PyQt5. This approach prevents the main GUI thread from being blocked or causing unexpected behavior during predictions.

Here's a simplified example on how you could potentially structure it with `QThread`:

```python
from PyQt5.QtCore import QThread, pyqtSignal

class PredictionThread(QThread):
    prediction_done = pyqtSignal(object)  # Signal to emit with the prediction result

    def __init__(self, image):
        super().__init__()
        self.image = image

    def run(self):
        results = model(self.image)  # Assume model is accessible here
        predict_result = process_results(results)  # Your logic to process results
        self.prediction_done.emit(predict_result)  # Emit the signal with the result

def process_results(results):
    # Your logic to parse results and prepare data for sending
    predict_result = ...
    return predict_result
```

And then in your `Window` class, you can start this thread on button click:

```python
class Window(QMainWindow):
    def __init__(self):
        # Your initialization code
        
    def LoopFunction(self):
        self.prediction_thread = PredictionThread(image)
        self.prediction_thread.prediction_done.connect(self.SendData)  # Connect signal to your SendData function
        self.prediction_thread.start()

    def start_loop(self):
        # Update to start LoopFunction
```

This way, you ensure that your main GUI remains responsive, and you can handle the prediction results asynchronously via signals and slots.

It's crucial to adjust the snippet above to fit into your actual application structure. But I hope this gives you a direction to tackle the issue! Let us know how it goes. 🚀

**Comment by WISHF-Amoy** [comment]
> @WISHF-Amoy hey! Thanks for sharing more details. It seems like the `model(image)` function from Ultralytics YOLOv8 might be causing the issues you're experiencing. If it's about handling the GUI and predictions without interruptions, consider running YOLOv8 predictions in a separate thread or using a `QThread` in PyQt5. This approach prevents the main GUI thread from being blocked or causing unexpected behavior during predictions.
> 
> Here's a simplified example on how you could potentially structure it with `QThread`:
> 
> ```python
> from PyQt5.QtCore import QThread, pyqtSignal
> 
> class PredictionThread(QThread):
>     prediction_done = pyqtSignal(object)  # Signal to emit with the prediction result
> 
>     def __init__(self, image):
>         super().__init__()
>         self.image = image
> 
>     def run(self):
>         results = model(self.image)  # Assume model is accessible here
>         predict_result = process_results(results)  # Your logic to process results
>         self.prediction_done.emit(predict_result)  # Emit the signal with the result
> 
> def process_results(results):
>     # Your logic to parse results and prepare data for sending
>     predict_result = ...
>     return predict_result
> ```
> 
> And then in your `Window` class, you can start this thread on button click:
> 
> ```python
> class Window(QMainWindow):
>     def __init__(self):
>         # Your initialization code
>         
>     def LoopFunction(self):
>         self.prediction_thread = PredictionThread(image)
>         self.prediction_thread.prediction_done.connect(self.SendData)  # Connect signal to your SendData function
>         self.prediction_thread.start()
> 
>     def start_loop(self):
>         # Update to start LoopFunction
> ```
> 
> This way, you ensure that your main GUI remains responsive, and you can handle the prediction results asynchronously via signals and slots.
> 
> It's crucial to adjust the snippet above to fit into your actual application structure. But I hope this gives you a direction to tackle the issue! Let us know how it goes. 🚀

Hello! Thanks for your guide, but there still some thing wrong with my packaged exe. I use the `QThread` as you told to run my YOLO8 predict process. All thing goes very well in `PyCharm` as usual, but when I package these code by `pyinstaller`, the built exe run, when I click the `Start` to run YOLO8 predict, the console twinkle more times, and more GUI come out....Oh my god......

Also during the debug time, I fixed some bugs caused by `LOGGER`, I just comment or set all `LOOGER` to None, so that it will not print to console which avoid error when package with `pyinstaller` without console.

So, just come bakc to my codes:
```python

class GetPredict(QThread):
    prediction_done = pyqtSignal(object)

    def __init__(self, params):
        super().__init__()
        self.screenshot = None
        self.params = params

    def run(self):
        # get screen shot
        try:
            self.screenshot = SelectTargetWindow(self.params)
        except Exception as e:
            screenshot = None
        PredictContent = self.ProbPredict()
        self.prediction_done.emit(PredictContent)

    # using YOLO8 to get detection result
    def ProbPredict(self):
        if self.screenshot:
            results = model(self.screenshot)
        else:
            return None
        for i, r in enumerate(results):
            # Plot results image
            im_bgr = r.plot()  # BGR-order numpy array
            im_rgb = Image.fromarray(im_bgr[..., ::-1])  # RGB-order PIL image
            
            PredictContent = xxxx
            return PredictContent

```
Above is my `QThread` class to make predict by YOLO8, and below is my `QMainWindow` pseudo-code:

```python

class Window(QMainWindow):
    def __init__(self):
        super().__init__()
        self.get_predict_thread = None

        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.setWindowFlags(Qt.FramelessWindowHint)
        self.setAttribute(Qt.WA_TranslucentBackground)

        self.timer = QTimer()
        self.timer.timeout.connect(self.LoopFunction)

        self.ui.Start_Button.clicked.connect(self.start_loop)
        self.ui.Stop_Button.clicked.connect(self.stop_loop)

    def LoopFunction(self):
        self.get_predict_thread = GetPredict(self.cnt, self.target_folder, self.speed)
        # SimplePredictProcess is the function using the YOLO predict result to process reuslt and send my our data
        self.get_predict_thread.prediction_done.connect(SimplePredictProcess)
        self.get_predict_thread.start()

    def start_loop(self):
        self.timer.start(1000)  # tick

    def stop_loop(self):
        self.timer.stop()

```

The code runs very well through `PyCharm` without any extra windows appearing, but after packaging it through `pyinstaller`, there are always extra GUIs appearing, and even more after using `QThread`. I'm wondering if it's because YOLO threads don't work quite the same way in both environments? Or something else is causing this? I'm really puzzled by this strange phenomenon that occurs during packing the exe, and it seems that there are very few cases of this kind of error on the internet.

**Comment by WISHF-Amoy** [comment]
@glenn-jocher Hello! I just find out that add this code `multiprocessing.freeze_support()`:
```python
import multiprocessing

if __name__ == '__main__':
    # added
    multiprocessing.freeze_support()

    app = QApplication(sys.argv)
    window = Window()
    window.show()
    sys.exit(app.exec_())
```

And then there will not have extra GUIs! So that means it is the multi-thread in YOLO cause the problem? But though now no extra GUI come out anymore, even I package without console, the console will come out and twinkle twice, but then, my exe can work properly. So I am going to find out the how to avoid the strange console twinkle.

**Comment by WISHF-Amoy** [comment]
> @glenn-jocher Hello! I just find out that add this code :`multiprocessing.freeze_support()`
> 
> ```python
> import multiprocessing
> 
> if __name__ == '__main__':
>     # added
>     multiprocessing.freeze_support()
> 
>     app = QApplication(sys.argv)
>     window = Window()
>     window.show()
>     sys.exit(app.exec_())
> ```
> 
> And then there will not have extra GUIs! So that means it is the multi-thread in YOLO cause the problem? But though now no extra GUI come out anymore, even I package without console, the console will come out and twinkle twice, but then, my exe can work properly. So I am going to find out the how to avoid the strange console twinkle.

This is based on my orginal codes which do not using the QThread. And if in the code using `QThread`, the console will twinkle many many times, and exe may go wrong.

**Comment by WISHF-Amoy** [comment]
So if there any parallelism or multi-thread using in the YOLO8? I just want to find out the reason and solve it! Thanks a lot for your help!

**Comment by glenn-jocher** [comment]
Hey there! 😊 Thanks for reaching out with your question.

In YOLOv8, parallelism and multi-threading are indeed utilized to enhance performance, particularly during training and inference phases to efficiently process batches of data. However, the specific behavior you're experiencing with your GUI application might stem from how your environment handles processes and threads, especially when packaged with PyInstaller.

A good starting point for addressing the console flickering could involve tweaking the `subprocess` or thread creation parameters in your application. For instance, ensuring that any subprocesses initiated by your application (or indirectly by YOLOv8) have a suitable configuration to prevent undesired GUI or console windows from appearing. Here's a generic example on controlling a subprocess, though you mentioned not using `subprocess` directly:

```python
import subprocess

# Example for running a command silently without opening a new console window
subprocess.run(['your_command_here'], creationflags=subprocess.CREATE_NO_WINDOW)
```

Since PyInstaller and multi-threading complexities can vary widely across projects, examining how multi-threading is implemented related to YOLOv8's predictions in your app is crucial. Employing `QThread` as you did ensures GUI responsiveness but keep an eye on how these threads invoke YOLOv8's functionalities.

If you continue to face challenges, sharing more specific details or snippets could help the community provide more targeted advice. Happy coding! 🚀

**Comment by WISHF-Amoy** [comment]
Thanks for your help! But I am sorry that I do not know where is the proper place to add these code. Should this added after 
```python

results = model(self.screenshot)

```

I am really sorry I am not familiar with the usage of 
```python

subprocess.run()

```

I am trying to find out more knowledge of this function, but if you can give me more detail that will be great appreciate!

**Comment by glenn-jocher** [comment]
Hey there! No worries at all; we're here to help! 😊 The code snippet involving `subprocess.run()` was generally aimed at managing subprocesses that, when executed, might create additional unwanted console windows. However, considering your setup does not explicitly use `subprocess.run()`, it may not be directly applicable to handling the YOLOv8 prediction in your PyQt application.

From your description, it sounds like you're looking for a solution to avoid additional GUI windows that pop up due to multiprocessing when running predictions, correct? Since `multiprocessing.freeze_support()` helped with the extra GUI issues, and you're not directly dealing with `subprocess.run()`, you may not need to incorporate that particular example into your project.

Regarding integrating multiprocessing or subprocess handling directly related to YOLOv8, such usage typically happens under the hood. For making predictions with YOLOv8 in a PyQt application, continuing to use the `QThread` approach for running predictions asynchronously, as you've implemented, is indeed a good practice. This method ensures your GUI remains responsive while predictions are being processed.

Just to keep the focus on enhancing your current solution without diverging into `subprocess.run()`, it looks like you're on the right track! If you have any other questions or hit specific snags, feel free to drop a line. Happy coding! 🚀

**Comment by WISHF-Amoy** [comment]
Hello! I finally find out the solution to solve my problem that console will flash twice when `YOLO` start! That is in the `ultralytics` -> `utils` -> `torch_utils.py`:

https://github.com/ultralytics/ultralytics/blob/911a0edd2d1b47c28e1eef657859dbb9bcffb13f/ultralytics/utils/torch_utils.py#L164
https://github.com/ultralytics/ultralytics/blob/911a0edd2d1b47c28e1eef657859dbb9bcffb13f/ultralytics/utils/torch_utils.py#L73

The package `cpuinfo` may cause some subprocess, so I just change it to the package `wmi`, and simply get the `cpu` info to avoid subprocess problem. After that, my exe can run properly without strange flashing! Below is my change to origin code:

```python

def get_cpu_info():
	# """Return a string with system CPU information, i.e. 'Apple M2'."""
	# import cpuinfo  # pip install py-cpuinfo
	#
	# k = "brand_raw", "hardware_raw", "arch_string_raw"  # info keys sorted by preference (not all keys always available)
	# info = cpuinfo.get_cpu_info()  # info dict
	# string = info.get(k[0] if k[0] in info else k[1] if k[1] in info else k[2], "unknown")
	import wmi

	c = wmi.WMI()
 	string = c.Win32_Processor()[0].Name
	return string.replace("(R)", "").replace("CPU ", "").replace("@ ", "")
```

**Comment by glenn-jocher** [comment]
Hello! 🎉 That's fantastic news! Super glad to hear you found a workaround for the console flashing issue by using `wmi` instead of `cpuinfo`. This clever adjustment helps bypass the subprocesses that were leading to the unexpected behavior in your packaged exe. Appreciate your sharing this valuable solution with the community! Your code snippet certainly adds valuable insight for others who might face a similar challenge. Keep up the great work! Happy coding! 🚀
