### ISSUE TITLE
mean and std for yolov8-cls

### ISSUE THREAD

**Issue by mbenami** [ultralytics/ultralytics#10111]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi 
for `yolov8-cls` pre-trained weights 
1. is it trained on ImageNet? 
2. is it trained with the default mean/std of ImageNet 
```
mean = [0.485, 0.456, 0.406] and std = [0.229, 0.224, 0.225]
```

or with yolov8 default mean and std?
 https://github.com/ultralytics/ultralytics/blob/0fa42fbd7d7bd1535ebf627afff0385dea276147/ultralytics/data/augment.py#L22
 
Thanks for the help

**Comment by glenn-jocher** [comment]
Hi there! 😊

For the `yolov8-cls` pre-trained weights:
1. Yes, it's trained on the ImageNet dataset.
2. It uses the YOLOv8 default mean and std as specified in the `augment.py`, not the ImageNet defaults.

Hope this helps! If you have any more questions, feel free to ask.
