### ISSUE TITLE
can see detections in Window CLI but not the webcam stream

### ISSUE THREAD

**Issue by u1353279** [ultralytics/ultralytics#1012]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

when running the cli command i can see in my windows terminal that objects are being detected but the webcam is not displaying even though i have source="0"

so my full code is yolo predict model=yolov8n.pt source="0"

**Comment by AndreiVoian** [comment]
`yolo predict model=yolov8n.pt source="0" show=True`

**Comment by u1353279** [comment]
Thank you so much

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
