### ISSUE TITLE
Why is warmup_bias_lr set to 0.0 when use optimizer='auto'?

### ISSUE THREAD

**Issue by comlhj1114** [ultralytics/ultralytics#10130]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I set optimizer=auto, warmup_bias_lr is always set to 0.0.
I expected warmup_bias_lr=0.01 to update bias in warmup epochs.

From [this commit](https://github.com/ultralytics/ultralytics/pull/2969/commits/95d9c72fc305e1e2db8f720423ce33c7ba1ab1d9), this setting was changed and I wonder why the warmup_bias_lr is changed to 0.0 from 0.01.

Thanks for maintaining this wonderful library.

**Comment by glenn-jocher** [comment]
@comlhj1114 hey there! 👋 Great question. When `optimizer='auto'` is set, `warmup_bias_lr` defaults to `0.0` as part of a broader optimization strategy aimed at enhancing model training stability and performance. The idea is to avoid aggressive bias correction in the initial phase (warmup epochs), which can sometimes lead to instability in training dynamics, especially for complex datasets and models.

The change from `warmup_bias_lr=0.01` to `0.0` was made based on empirical observations and testing that showed improved training consistency across a wide range of scenarios. However, this is a somewhat empirical domain, and the optimal settings can vary depending on the specifics of your dataset and model architecture.

If you have a specific reason or find through experimentation that setting `warmup_bias_lr=0.01` (or another value) works better for your case, you can override the default behavior by explicitly specifying your desired value in your configuration file or command line arguments, like so:

```yaml
warmup_bias_lr: 0.01  # In your YAML configuration file
```
or
```bash
yolo train ... warmup_bias_lr=0.01  # Via the command line interface
```
The YOLOv8 community always appreciates feedback on configurations that work well, so please don't hesitate to share your findings or ask further questions. 🚀

And thanks for the kind words about the library – it's users like you who motivate us to keep improving!

**Comment by comlhj1114** [comment]
@glenn-jocher Thank you very much for your kind and solid answer!

**Comment by glenn-jocher** [comment]
@comlhj1114 you're welcome! 😊 If you have any more questions or need further assistance, feel free to ask. Happy modeling!
