### ISSUE TITLE
YOLOWorldPromptDetector Support?

### ISSUE THREAD

**Issue by dengbuqi** [ultralytics/ultralytics#10140]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

YOLOWorldPromptDetector Support！
Yolo-world is a talented developer of open-vocabulary object detection solutions. 
In the original solution, they also provided the function of YOLOWorldPromptDetector. That means we can find the object we need not only by text prompt but also by image prompt or even any prompt. We can also make a combination prompt of them. I think this is a very important idea that can be applied to many tasks(ReID, Open vocabulary object tracking and so on).

So I was wondering is possible to add this function in Ultralytics?

If so, that will be very thankfully!

### Use case

1. Multi-camera special feature person and special action detection.
2. ReID.
3. Open-vocabulary tracking.
4.  Suspect location in the city surveillance system.
5. Image searching
......

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello there! 👋

Thank you for bringing up the YOLOWorldPromptDetector feature and its potential integration within Ultralytics YOLO. It's thrilling to see interest in expanding the utility and versatility of YOLO through open-vocabulary capabilities and prompt-based detection. Certainly, features like these can significantly enhance the application of YOLO models across various domains including ReID, object tracking, and beyond.

As for now, integrating YOLOWorldPromptDetector, or similar prompt-based functionalities directly into Ultralytics YOLO, isn't part of our immediate roadmap. However, we're always exploring innovative ways to evolve and improve. Suggestions like yours are invaluable for guiding future developments! 🚀

In the meantime, I'd encourage the community to experiment with combining Ultralytics YOLO models with additional layers or external systems designed to handle prompts. This could offer a flexible, albeit more complex, approach to achieving similar outcomes.

If you're keen on contributing and have ideas or implementations you'd like to share, we're open to discussions and contributions on our GitHub repository. We look forward to possibly incorporating more dynamic and diverse ways of object detection in the future!

Thanks for your interest and enthusiasm towards making Ultralytics YOLO even better. Stay tuned for updates, and please feel free to share any more thoughts or questions you might have.

Happy detecting!
