### ISSUE TITLE
I want to get a yolo-world pt model file for detecting sidewalks. How do I do that?

### ISSUE THREAD

**Issue by lizhiwen19900709** [ultralytics/ultralytics#10145]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to get a yolo-world pt model file for detecting sidewalks. How do I do that?
Do you train yourself using the dataset, or is there another shortcut to get it?

**Comment by lizhiwen19900709** [comment]
from ultralytics import YOLOWorld
  
model = YOLOWorld("yolov8s-worldv2.pt")
model.train(data="ultralytics/cfg/datasets/coco128.yaml",epochs=20,imgsz=640)


![1713447158452](https://github.com/ultralytics/ultralytics/assets/15767823/f8ee6d48-5db3-4bba-b382-e426c5b0b869)

@glenn-jocher

**Comment by glenn-jocher** [comment]
Hey there! 😊 It looks like you're on the right path with training a YOLOWorld model on the COCO128 dataset. Just a quick note - the use of `"ultralytics/cfg/datasets/coco128.yaml"` seems correct, assuming you've got your dataset organized accordingly. Other parameters like `epochs` and `imgsz` are also set well for a start.

If the image you shared is supposed to illustrate an issue or a step in your process, it didn't come through properly. You might want to re-upload it directly on the GitHub issue or provide a bit more context to help us understand better.

For any specific questions or errors you're encountering, feel free to elaborate, and I'd be more than happy to help out! 

```python
from ultralytics import YOLOWorld
  
# Load the model
model = YOLOWorld("yolov8s-worldv2.pt")

# Start training
model.train(data="ultralytics/cfg/datasets/coco128.yaml", epochs=20, imgsz=640)
```

Keep up the great work! 🚀

**Comment by lizhiwen19900709** [comment]
> ```python
> coco128.yaml
> ```

coco128.yaml is in the ultralytics github open source library, all the context is explained, there is no other context

**Comment by lizhiwen19900709** [comment]
> Hey there! 😊 It looks like you're on the right path with training a YOLOWorld model on the COCO128 dataset. Just a quick note - the use of `"ultralytics/cfg/datasets/coco128.yaml"` seems correct, assuming you've got your dataset organized accordingly. Other parameters like `epochs` and `imgsz` are also set well for a start.
> 
> If the image you shared is supposed to illustrate an issue or a step in your process, it didn't come through properly. You might want to re-upload it directly on the GitHub issue or provide a bit more context to help us understand better.
> 
> For any specific questions or errors you're encountering, feel free to elaborate, and I'd be more than happy to help out!
> 
> ```python
> from ultralytics import YOLOWorld
>   
> # Load the model
> model = YOLOWorld("yolov8s-worldv2.pt")
> 
> # Start training
> model.train(data="ultralytics/cfg/datasets/coco128.yaml", epochs=20, imgsz=640)
> ```
> 
> Keep up the great work! 🚀

coco128.yaml is in the ultralytics github open source library, all the context is explained, there is no other context

**Comment by lizhiwen19900709** [comment]
Torch version reduced to 2.1.2 and returned to normal, torch latest version 2.2.2 compatibility problems

**Comment by glenn-jocher** [comment]
Hey there! 😊 Glad to hear adjusting the Torch version resolved your issue. Yes, sometimes newer versions of libraries can introduce compatibility issues. Here's a quick way to ensure you're using a compatible Torch version:

```python
pip install torch==2.1.2
```

If you encounter any more issues or have further questions, feel free to reach out. Happy coding! 🚀
