### ISSUE TITLE
How to stop Plotting in yolov8

### ISSUE THREAD

**Issue by ronit450** [ultralytics/ultralytics#10143]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have RGBD data which I want to train. I have made changes in the model and after the first epoch, the training stops. The error lies in the plotting 

### Additional

![image](https://github.com/ultralytics/ultralytics/assets/77673121/4883ea45-14e0-44ba-a052-e5cbc2c6beaf)
![image](https://github.com/ultralytics/ultralytics/assets/77673121/df65c4d8-72c3-4939-94db-a04e6c922682)
![image](https://github.com/ultralytics/ultralytics/assets/77673121/90093074-1031-4723-b4d5-40c53e2d9dcd)

**Comment by glenn-jocher** [comment]
@ronit450 to avoid plotting during your YOLOv8 training with RGBD data, you can use the `--no-plot` argument when running your training command. This will disable the plotting of results after each epoch, which seems to be where you're encountering the error. Here’s how you can modify your training command:

```bash
yolo train data=your_dataset.yaml model=your_custom_model.yaml --no-plot
```

Make sure to replace `your_dataset.yaml` and `your_custom_model.yaml` with the paths to your actual dataset and model configuration files. This should help bypass the plotting step and proceed with the training.

If you're using the Python API, you can achieve a similar effect by setting `plots=False` in the `train()` method options. 

Let us know if this solution works for you or if anything else comes up! 🚀
