### ISSUE TITLE
Labeled prediction.

### ISSUE THREAD

**Issue by tahamediouni1** [ultralytics/ultralytics#10144]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would like to know if I can get a labeled output just like the dataset I trained my model on, basically a txt file which contains the bounding boxes of the predicted image, and that to have a bigger dataset and to improve my model.

**Comment by glenn-jocher** [comment]
Hello there! 👋

Absolutely, you can obtain labeled prediction results in a `.txt` file similar to your training dataset format. After running predictions with YOLOv8, you can save the results in the desired format using the `save_txt=True` argument. Here's an example of how you can achieve this:

```python
from ultralytics import YOLO

# Load your trained model
model = YOLO('path/to/your/model.pt')

# Run prediction on an image and save results to txt
results = model.predict('path/to/your/image.jpg', save_txt=True)
```

This will save the detected bounding boxes, class IDs, and confidence scores in a `.txt` file in the same directory as your images, mimicking the format used for your training dataset. This file can then be used to augment your dataset or further analyze the model's predictions.

Happy modeling, and we hope this helps boost your dataset and model performance! 😊
