### ISSUE TITLE
Training Image Size Confusion

### ISSUE THREAD

**Issue by khoanguyen311202** [ultralytics/ultralytics#10159]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I am in a hurry. I would be grateful if someone could help me clarify these questions when training in YOLOv8:

**Q1. Case 1:**
- I have images with the exact size of 640x640
- I did not set imgsz in the code
- rect=False

**Q2. Case 2:**
- I have images with the exact size of 1280x1280
- I did set imgsz in the code: imgsz = 1280
- rect=False

**Q3. Case 3:**
- I have images with the exact size of 1440x960
- I did set imgsz in the code: imgsz = 1440
- rect=True
Note: Actually, I tried to set the image size in this case to be (1440,960) but received this warning: "WARNING ⚠️ updating to 'imgsz=1440'. 'train' and 'val' imgsz must be an integer, while 'predict' and 'export' imgsz may be a [h, w] list or an integer"

**Q4. Case 4:** 
- I have images with the exact size of 640x320
- I did not set imgsz in the code
- rect=False

**Q5. Case 5:** 
- I have images with the exact size of 640x320
- I did not set imgsz in the code
- rect=True

**Q6. Case 6:** 
- I have images with the exact size of 520x320
- I did not set imgsz in the code
- rect=False

=> My question is: **What image size was used for training in each case?**

Thank you very much for your assistance.

**Comment by glenn-jocher** [comment]
Hello!

I understand you're in a hurry, and I'm here to help clarify your confusion about image sizes when training with YOLOv8. Let's briefly go through your cases:

**Q1. Case 1:** If `imgsz` is not set, YOLOv8 defaults to `640x640`, matching your image size. So, it uses `640x640`.

**Q2. Case 2:** You set `imgsz=1280`, which means it uses `1280x1280` for training. 

**Q3. Case 3:** For mixed aspect ratio images with `rect=True`, YOLOv8 adjusts the training size to the nearest multiple of 32 that maintains the aspect ratio. With `imgsz=1440`, it essentially tries to use `1440` for the longer dimension. For `predict` and `export`, specific dimensions `[h,w]` can be used, but in `train` and `val`, it rounds/adjusts for the batch uniformity.

**Q4. Case 4:** Without `imgsz` set, YOLOv8 will use the default `640x640`, and images will be resized accordingly.

**Q5. Case 5:** With `rect=True`, YOLOv8 will adjust each image in a batch to have a uniform width or height, maximizing the area under the constraint of the specified `imgsz` (default `640x640`), but maintaining the aspect ratio of the images.

**Q6. Case 6:** Like in Case 4, without `imgsz` set, the default is `640x640`, and images are resized accordingly.

In cases where you don't specify `imgsz`, YOLOv8 uses the default `640x640`. For training with mixed aspect ratios (`rect=True`), YOLOv8 adjusts each image in a batch to have the same width or height while preserving the aspect ratio, guided by the `imgsz` setting.

I hope this clears up the confusion! If you have any more questions, feel free to ask. 🚀

**Comment by khoanguyen311202** [comment]
Hi @glenn-jocher, thank you so much for your quick reply. Now I understand more about YOLOv8 image size.
Happy learning!

P.S: Wouldn't it be better if the executed code could provide detailed dimensions used for training (with both [h,w])?

**Comment by glenn-jocher** [comment]
Hi there! 🌟 We're glad to hear you've gained a clearer understanding of how image sizes work in YOLOv8. Thanks for the great suggestion about providing detailed dimensions ([h,w]) used during training. It would indeed enhance clarity and aid in fine-tuning models effectively. I'll share this feedback with the Ultralytics team so we can consider it for future updates. Happy learning, and keep those awesome suggestions coming! 🚀

**Comment by feiqinaqian** [comment]
Hi @glenn-jocher, I have a question about imgsz.

I have added a new module in the Yolov8n network, which will fix the size of output tensor to [n,c,t,t]. When I was training with the imgsz=416, the process is normal. But when validating, it faces errors and shows that the tensor mismach during the concatetion process.

**My question is: Why this error happened?**

**Comment by feiqinaqian** [comment]
Hi @glenn-jocher .

In addition, I found that the input size of network will change to [256,416], while my settings of imgsz is 416. I want to know that whether the imgsz will change during validating, and how to solve this problem?

The error is shown as follows:
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    299/300     0.916G      1.438     0.6469     0.8189         11        416: 100%|██████████| 384/384 [00:16<00:00, 22.66it/s]

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    300/300     0.916G      1.448     0.6367     0.8229         15        416: 100%|██████████| 384/384 [00:16<00:00, 22.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/25 [00:00<?, ?it/s]Shape of batch['img']: torch.Size([16, 3, 224, 448])
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/25 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "\\?\D:\Anaconda\envs\py38\Scripts\yolo-script.py", line 33, in <module>
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())
  File "d:\work\pythonwork\ultralytics\ultralytics\cfg\__init__.py", line 444, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "d:\work\pythonwork\ultralytics\ultralytics\engine\model.py", line 341, in train
    self.trainer.train()
  File "d:\work\pythonwork\ultralytics\ultralytics\engine\trainer.py", line 192, in train
    self._do_train(world_size)
  File "d:\work\pythonwork\ultralytics\ultralytics\engine\trainer.py", line 386, in _do_train
    self.metrics, self.fitness = self.validate()
  File "d:\work\pythonwork\ultralytics\ultralytics\engine\trainer.py", line 490, in validate
    metrics = self.validator(self)
  File "D:\Anaconda\envs\py38\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "d:\work\pythonwork\ultralytics\ultralytics\engine\validator.py", line 169, in __call__
    preds = model(batch['img'], augment=augment)
  File "D:\Anaconda\envs\py38\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "d:\work\pythonwork\ultralytics\ultralytics\nn\tasks.py", line 42, in forward
    return self.predict(x, *args, **kwargs)
  File "d:\work\pythonwork\ultralytics\ultralytics\nn\tasks.py", line 59, in predict
    return self._predict_once(x, profile, visualize)
  File "d:\work\pythonwork\ultralytics\ultralytics\nn\tasks.py", line 83, in _predict_once
    x = m(x)  # run
  File "D:\Anaconda\envs\py38\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "d:\work\pythonwork\ultralytics\ultralytics\nn\modules\conv.py", line 438, in forward
    return torch.cat(x, self.d)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 26 but got size 14 for tensor number 1 in the list.


      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    300/300     0.916G      1.448     0.6367     0.8229         15        416: 100%|██████████| 384/384 [00:16<00:00, 22.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/25 [00:00<?, ?it/s]Shape of batch['img']: torch.Size([16, 3, 224, 448])
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/25 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "\\?\D:\Anaconda\envs\py38\Scripts\yolo-script.py", line 33, in <module>
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())
  File "d:\work\pythonwork\ultralytics\ultralytics\cfg\__init__.py", line 444, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "d:\work\pythonwork\ultralytics\ultralytics\engine\model.py", line 341, in train
    self.trainer.train()
  File "d:\work\pythonwork\ultralytics\ultralytics\engine\trainer.py", line 192, in train
    self._do_train(world_size)
  File "d:\work\pythonwork\ultralytics\ultralytics\engine\trainer.py", line 386, in _do_train
    self.metrics, self.fitness = self.validate()
  File "d:\work\pythonwork\ultralytics\ultralytics\engine\trainer.py", line 490, in validate
    metrics = self.validator(self)
  File "D:\Anaconda\envs\py38\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "d:\work\pythonwork\ultralytics\ultralytics\engine\validator.py", line 169, in __call__
    preds = model(batch['img'], augment=augment)
  File "D:\Anaconda\envs\py38\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "d:\work\pythonwork\ultralytics\ultralytics\nn\tasks.py", line 42, in forward
    return self.predict(x, *args, **kwargs)
  File "d:\work\pythonwork\ultralytics\ultralytics\nn\tasks.py", line 59, in predict
    return self._predict_once(x, profile, visualize)
  File "d:\work\pythonwork\ultralytics\ultralytics\nn\tasks.py", line 83, in _predict_once
    x = m(x)  # run
  File "D:\Anaconda\envs\py38\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "d:\work\pythonwork\ultralytics\ultralytics\nn\modules\conv.py", line 438, in forward
    return torch.cat(x, self.d)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 26 but got size 14 for tensor number 1 in the list.

**Comment by feiqinaqian** [comment]
Hi @glenn-jocher 
I found that the input size of network will change to [224,448], while my settings of imgsz is 416. I want to know that whether the imgsz will change during validating, and how to solve this problem?

The error is shown as follows:
Epoch GPU_mem box_loss cls_loss dfl_loss Instances Size
299/300 0.916G 1.438 0.6469 0.8189 11 416: 100%|██████████| 384/384 [00:16<00:00, 22.66it/s]

  Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
300/300     0.916G      1.448     0.6367     0.8229         15        416: 100%|██████████| 384/384 [00:16<00:00, 22.84it/s]
             Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/25 [00:00<?, ?it/s]Shape of batch['img']: torch.Size([16, 3, 224, 448])
             Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/25 [00:00<?, ?it/s]
Traceback (most recent call last):
File "\?\D:\Anaconda\envs\py38\Scripts\yolo-script.py", line 33, in
sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())
File "d:\work\pythonwork\ultralytics\ultralytics\cfg_init_.py", line 444, in entrypoint
getattr(model, mode)(**overrides) # default args from model
File "d:\work\pythonwork\ultralytics\ultralytics\engine\model.py", line 341, in train
self.trainer.train()
File "d:\work\pythonwork\ultralytics\ultralytics\engine\trainer.py", line 192, in train
self._do_train(world_size)
File "d:\work\pythonwork\ultralytics\ultralytics\engine\trainer.py", line 386, in _do_train
self.metrics, self.fitness = self.validate()
File "d:\work\pythonwork\ultralytics\ultralytics\engine\trainer.py", line 490, in validate
metrics = self.validator(self)
File "D:\Anaconda\envs\py38\lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "d:\work\pythonwork\ultralytics\ultralytics\engine\validator.py", line 169, in call
preds = model(batch['img'], augment=augment)
File "D:\Anaconda\envs\py38\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "d:\work\pythonwork\ultralytics\ultralytics\nn\tasks.py", line 42, in forward
return self.predict(x, *args, **kwargs)
File "d:\work\pythonwork\ultralytics\ultralytics\nn\tasks.py", line 59, in predict
return self._predict_once(x, profile, visualize)
File "d:\work\pythonwork\ultralytics\ultralytics\nn\tasks.py", line 83, in _predict_once
x = m(x) # run
File "D:\Anaconda\envs\py38\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "d:\work\pythonwork\ultralytics\ultralytics\nn\modules\conv.py", line 438, in forward
return torch.cat(x, self.d)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 26 but got size 14 for tensor number 1 in the list.

**Comment by glenn-jocher** [comment]
@feiqinaqian hi there! 🌞 It looks like the error you're encountering is due to a mismatch in tensor sizes during concatenation. This often happens when the dimensions of inputs or intermediate tensors do not align as expected in the model's layers, especially when custom changes are made to the network architecture.

The `imgsz` should technically remain consistent during training and validation phases. However, if you're finding discrepancies, especially with custom modules or modifications to the network, it's important to ensure that all parts of your model accommodate these user-defined `imgsz` settings appropriately across different phases. 

A mismatch like `Expected size 26 but got size 14` suggests that somewhere in your network, the operations or the modules are not handling the input/output sizes correctly relative to what's expected. Double-check your custom module and make sure it correctly processes the input tensor size, considering how YOLOv8 dynamically adjusts input sizes for efficiency and performance.

A quick way to debug might be to add print statements before the concatenation operation to log the shapes of all tensors involved, ensuring they match where expected, except for the dimension you intend to concatenate on.

If you've recently added or modified your network architecture, reviewing these changes closely could help spot where the size expectations diverge.

Hope this helps, and happy coding! 😊

**Comment by glenn-jocher** [comment]
Hi @feiqinaqian,

That's great to hear you've found the source of the error! You're correct, setting `rect=False` will prevent dynamical adjustments of image sizes during validation. Thanks for sharing your solution, and feel free to reach out if you have any more questions or run into additional issues. Happy coding! 😊

**Comment by AlanLi1997** [comment]
> Hi @glenn-jocher
> 
> Thank you for your kindly response. I have found the source of errors. When I set the rect as "False" in the following code:
> 
> ```
> def val(self, validator=None, **kwargs):
>     custom = {'**rect**': False}  # method defaults
> ```
> 
> The validating progress runs normal.
> 
> It seems that the "rect" will dynamically change the imgsz when validating.
> 
> Thanks again!☺

Hi, I faced this error also, but I can't find the code's location of the "def val(self, validator=None, **kwargs):". Which version of the Yolov8/11 were u used when u first time faced it? Thanks.

**Comment by glenn-jocher** [comment]
Hello, the `val(self, validator=None, **kwargs)` function is part of the Ultralytics `YOLO` class and can be found in the `ultralytics/engine/model.py` file. You can review the latest implementation of this function in the [Ultralytics repository](https://github.com/ultralytics/ultralytics). Ensure you are using the latest version of YOLO for the most up-to-date features and fixes. Let us know if you have further questions!

**Comment by AlanLi1997** [comment]
> Hello, the function is part of the Ultralytics class and can be found in the file. You can review the latest implementation of this function in the [Ultralytics repository](https://github.com/ultralytics/ultralytics). Ensure you are using the latest version of YOLO for the most up-to-date features and fixes. Let us know if you have further questions!`val(self, validator=None, **kwargs)``YOLO``ultralytics/engine/model.py`

Hi, thanks for your reply. I have solved this error by modify code: _ultralytics/yolo/data/build.py line 71_

        rect=cfg.rect if mode == "train" else True,  # rectangular batches   ->  rect=cfg.rect, # rectangular batches
And I found that a reasonable adjustment has been made in the latest version, [rect=cfg.rect or rect,  # rectangular batches](https://github.com/ultralytics/ultralytics/blob/1cfe60e1d3b080943110b6d052e61ac9b35ea54b/ultralytics/data/build.py#L93),when I plan to fork the project and adjust this unstable setup. I think maybe a new parameter _rect_val = True/False_ can be added to make the validation more flexible, if necessary.

**Comment by glenn-jocher** [comment]
Thanks for sharing your solution and the thoughtful suggestion about adding a `rect_val` parameter for more flexible validation control. The current implementation in the latest version indeed handles this better with `rect=cfg.rect or rect`. Your original fix and proposed enhancement make sense for providing more granular control over rectangular batching during validation. Feel free to open a feature request on the Ultralytics GitHub repository if you'd like to formally propose this enhancement.
