### ISSUE TITLE
Is there a way to output 'Speed' as a metric when running model.val()?

### ISSUE THREAD

**Issue by Vaevin** [ultralytics/ultralytics#1016]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would like to output and plot what the average inference time was for the validation dataset in my YOLO model (either from model.val() or .predict(). However, I don't currently see that available. I have found this from the YOLO docs which does list speed as an attribute of the BaseValidator class, however I do not know how I can directly output it:

![image](https://user-images.githubusercontent.com/60018242/219487363-3320bdb7-fb22-4766-bcb2-68f50338ce35.png)

**Comment by AyushExel** [comment]
You should get the avg speed of inference and processing at the end of validation. Are you not seeing that? What command are you using? Maybe you need verbose mode?

**Comment by pderrenger** [comment]
@Vaevin currently, direct access to the average inference time as an instance attribute is not available within the YOLOv8 API. The speed attribute is not directly accessible in the manner you've described. The speed metric is printed out at the end of the validation, but it is not stored as an instance attribute that can be accessed directly. If you need to programmatically access the speed, you may consider modifying the YOLOv8 source code to store the speed as an instance attribute for your specific use case.
