### ISSUE TITLE
Camera not opening inside the container when using CLI command

### ISSUE THREAD

**Issue by goodevile** [ultralytics/ultralytics#10164]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

**Hardware:** Raspberry pi 4b 4GB RAM
**Details:** 
```
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
```

I am using docker and I am running: ultralytics/ultralytics:latest-arm64

`sudo docker run -it --privileged -v /dev:/dev --ipc=host my-customized-image`

by using the command bellow, it is not able to open the camera:

`yolo track model='/usr/src/ultralytics/project/weights/best_saved_model/best_float16.tflite' source="0" imgsz=128 save_crop=True show=False conf=0.5 tracker="bytetrack.yaml" save=False  show_labels=False show_conf=False show_boxes=False`

Error:

```
[ WARN:0@14.466] global cap_v4l.cpp:2092 getProperty VIDEOIO(V4L2:/dev/video0): Unable to get camera FPS
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/usr/src/ultralytics/ultralytics/cfg/__init__.py", line 583, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/ultralytics/ultralytics/engine/model.py", line 481, in track
    return self.predict(source=source, stream=stream, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/ultralytics/ultralytics/engine/model.py", line 441, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/ultralytics/ultralytics/engine/predictor.py", line 178, in predict_cli
    for _ in gen:  # noqa, running CLI inference without accumulating any outputs (do not modify)
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/usr/src/ultralytics/ultralytics/engine/predictor.py", line 221, in stream_inference
    self.setup_source(source if source is not None else self.args.source)
  File "/usr/src/ultralytics/ultralytics/engine/predictor.py", line 193, in setup_source
    self.dataset = load_inference_source(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/ultralytics/ultralytics/data/build.py", line 175, in load_inference_source
    dataset = LoadStreams(source, vid_stride=vid_stride, buffer=buffer)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/ultralytics/ultralytics/data/loaders.py", line 108, in __init__
    raise ConnectionError(f"{st}Failed to read images from {s}")
ConnectionError: 1/1: 0... Failed to read images from 0
```

Does anyone knows if I am doing something wrong here? the camera does work with the command `rpicam-jpeg -o test.jpg`

![image](https://github.com/ultralytics/ultralytics/assets/46387951/a357a5ae-2e95-4868-8e2c-580b461fd22e)

**Comment by ambitious-octopus** [comment]
@lakshanthad Do you have any insight into this?

**Comment by lakshanthad** [comment]
Hi @goodevile,

From the commands you have highlighted, it seems that you are using Raspberry Pi Camera Module. Is that right?

The issue here is `source="0"`, `source="1"` will only work there are USB cameras connected to the Raspberry Pi (because USB cameras will be listed at `/dev/video0`, `/dev/video1` etc....). Since Raspberry Pi Camera Module is connected to the Raspberry Pi via the `MIPI CSI interface`, it does not get listed under `/dev/video` and therefore cannot use `source`. This is the same problem when using OpenCV code where `cv2.VideoCapture(0)` will not work.

Therefore, what you can do is you can initiate a TCP stream as we have explained in the official docs and proceed from there.
https://docs.ultralytics.com/guides/raspberry-pi/#use-raspberry-pi-camera

Hope it helps :)

**Comment by lakshanthad** [comment]
@goodevile Another workaround should be to use `picamera2` as follows. I will update our official docs with this methods too.

```python
import cv2
from picamera2 import Picamera2
picam2 = Picamera2()
picam2.preview_configuration.main.size = (1280,720)
picam2.preview_configuration.main.format = "RGB888"
picam2.preview_configuration.align()
picam2.configure("preview")
picam2.start()
while True:
    im= picam2.capture_array()
    cv2.imshow("Camera", im)
    if cv2.waitKey(1)==ord('q'):
        break
cv2.destroyAllWindows()
```
