### ISSUE TITLE
Changing device and epoch number during training

### ISSUE THREAD

**Issue by mnoroozii** [ultralytics/ultralytics#10162]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I set epoch and device for training, but after training a couple of epochs, I wanna change these settings and resume. But it gives me an error when I am changing the device. Regarding the epoch number also, it didn't recognize my settings when I was changing the epoch number, and the training procedure was already set to the previous settings. 
What should I do?

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mnoroozii resume generally only accepts changes to imgsz and batch arguments, it is never recommended to change ANY settings when resuming.

Resume is ONLY intended to finish and earlier training that was accidentally interrupted.

**Comment by mnoroozii** [comment]
@glenn-jocher 
But sometimes I am able to use for example 2 gpus, but some other times, I have access to 4 gpus. That's why it is better to give the option of changing the number of devices at least.

**Comment by glenn-jocher** [comment]
Hi there! 🙌 We understand the convenience of adapting the number of GPUs mid-training. Currently, the `resume` option is designed to pick up training exactly where it left off, including using the same hardware settings for consistency. 

However, for more flexibility, you can manually restart your training on a different number of devices by specifying the `device` argument. Although this won't be a seamless `resume`, you can start from the last saved checkpoint:

```bash
yolo train data=coco128.yaml model=path/to/last_checkpoint.pt device=0,1,2,3 epochs=100 imgsz=640
```

Just replace `path/to/last_checkpoint.pt` with your actual checkpoint path and adjust the `device` and other parameters as needed. Hope this helps!
