### ISSUE TITLE
how to find the path of data preprocessing  before training?

### ISSUE THREAD

**Issue by oscarhuang1117** [ultralytics/ultralytics#10173]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

After I read augmernt.py, I've already known that before **prediction**, we can decide image size as int or list, but if I use default imgsz which is 640 and my data size is 1920*1080, then I will get a unpadding image 640*360, after padding I can get 640*640. I notice that I can decide which padding color I want.
Now my question is where is the path that I can find to decide the padding color before **training**?
Are training and prediction using the same **LetterBox**?

**Comment by oscarhuang1117** [comment]
Thank you very much for your reply! I'll keep trying to figure it out

**Comment by glenn-jocher** [comment]
You're welcome! If you hit any snags or have more questions, don't hesitate to reach out. Happy coding! 😊
