### ISSUE TITLE
How to use a custom dataset class in Yolo8 for training?

### ISSUE THREAD

**Issue by yosikeller** [ultralytics/ultralytics#10174]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am looking for an example of how to use my custom dataset code in Yolo8 for training?
I am using the train() function for training.. A custom dataloader would allow to add augmentations, parse custom annotation files, etc.

**Comment by glenn-jocher** [comment]
Hello! Great to hear you're looking to train YOLOv8 with your custom dataset class. 😃 To use a custom dataset for training, you can create a dataset class by inheriting from `torch.utils.data.Dataset` and implement the `__init__`, `__len__`, and `__getitem__` methods. In your `__getitem__` method, you can include any custom augmentation or parsing logic.

Here's a simple example to get you started:

```python
from torch.utils.data import Dataset
import cv2
import numpy as np

class CustomDataset(Dataset):
    def __init__(self, image_paths, annotations, transforms=None):
        self.image_paths = image_paths
        self.annotations = annotations
        self.transforms = transforms

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, index):
        # Load image
        image = cv2.imread(self.image_paths[index])
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        
        # Get annotations
        boxes = self.annotations[index]['boxes'] # Example: assuming annotations contain boxes
        
        # Apply custom augmentations
        if self.transforms:
            augmented = self.transforms(image=image, bboxes=boxes)
            image = augmented['image']
            boxes = augmented['bboxes']

        # Convert everything into a torch.Tensor
        image = np.transpose(image, (2, 0, 1)).astype(np.float32)
        boxes = np.array(boxes).astype(np.float32)
        
        return {'image': image, 'bboxes': boxes}

# Example: Assuming you have lists of image paths and annotations
image_paths = ['path/to/image1.jpg', 'path/to/image2.jpg']
annotations = [{'boxes': [[10, 20, 30, 40]]}, {'boxes': [[50, 60, 70, 80]]}] # Example format

# Optionally include transformations
transforms = None 

# Instantiate the dataset
custom_dataset = CustomDataset(image_paths=image_paths, annotations=annotations, transforms=transforms)

# Use this custom dataset for training with YOLOv8
```

To integrate this `custom_dataset` with YOLOv8's training function `train(data=...)`, you would typically set up a DataLoader and then integrate it within the training process. For YOLOv8, ensure that you follow its data handling conventions, potentially modifying the training script to accept your custom DataLoader if necessary.

For specific modifications and integration with YOLOv8's training pipeline, you might need to delve into the training script provided by Ultralytics and adjust where the data is loaded to use your `custom_dataset`.

Happy training, and if you need more detailed guidance, consider checking out the examples in the YOLOv8 documentation or asking more in the discussions!

**Comment by ternaus** [comment]
> To integrate this custom_dataset with YOLOv8's training function train(data=...), you would typically set up a DataLoader and then integrate it within the training process. For YOLOv8, ensure that you follow its data handling conventions, potentially modifying the training script to accept your custom DataLoader if necessary.

@glenn-jocher could you please share code on how exactly to do that?

**Comment by glenn-jocher** [comment]
Hello! Here’s a brief example of how you can integrate a custom DataLoader with YOLOv8’s training function:

```python
from torch.utils.data import DataLoader

# Assuming 'custom_dataset' is already initialized as shown in previous examples
data_loader = DataLoader(custom_dataset, batch_size=16, shuffle=True, num_workers=4)

# Now, modify the training loop in YOLOv8
for epoch in range(epochs):
    for batch in data_loader:
        images, targets = batch['image'], batch['bboxes']
        # Proceed with your training steps, pass 'images' and 'targets' to your model, etc.
```

You might need to adjust the data structures in your custom dataset’s `__getitem__` method to match what YOLOv8 expects, especially in terms of bounding box and label formats. Hope this helps! If you have specific requirements or further questions, feel free to ask! 😊

**Comment by ternaus** [comment]
@glenn-jocher 

In the code that you provided, there no single line related to Ultralytics. It is just a general pytorch dataloader and training pipeline

**Comment by ternaus** [comment]
@glenn-jocher 

Here is doc about using Albumentations for Object Detection with HuggingFace

https://huggingface.co/docs/transformers/main/en/tasks/object_detection  

I wanted to create something similar for UltraLytics, meaning using existing implemented functionality, but replacing DataLoader with a custom one.

HuggingFace code has a lot of bolilerplate that could be avoided and I believe UltraLytics does pretty good job abstracting unnecessary code from user.

But there is no good answer, so far, in docs / issues or pull requests that says how to use Albumentations for images + masks + boxes + keypoints for augmentations, meaning it is unclear how to replace dartaloader with a custom one, but keep the rest of the trainning / validation code in place.

Creating a good tutorial will, probably increase adoption of UltraLytics and remove PRs and issues like:

https://github.com/ultralytics/ultralytics/pull/6624 https://github.com/ultralytics/ultralytics/pull/1005 https://github.com/ultralytics/ultralytics/pull/5690 https://github.com/ultralytics/ultralytics/issues/11303

**Comment by glenn-jocher** [comment]
Hello! It's great to see your interest in integrating Albumentations with Ultralytics for a comprehensive data augmentation setup. 🚀 At the moment, incorporating a custom DataLoader or augmentation pipeline like Albumentations directly with the `model.train()` function in Ultralytics isn't supported out of the box. However, you can definitely customize the workflow by defining your DataLoader and integrating it manually within the training loop, similar to the method detailed in earlier communications.

Here’s a condensed example to guide you on how to inject a custom DataLoader which makes use of Albumentations for augmentations:

```python
from ultralytics import YOLO
import albumentations as A
from albumentations.pytorch.transforms import ToTensorV2

# Define your Albumentations transformations
transforms = A.Compose([
    A.Resize(640, 640),
    A.HorizontalFlip(p=0.5),
    A.RandomBrightnessContrast(p=0.2),
    ToTensorV2()
], bbox_params=A.BboxParams(format='yolo', label_fields=['class_labels']))

# Custom dataset class using Albumentations
class CustomDataset(Dataset):
    def __init__(self, image_paths, annotations):
        self.image_paths = image_paths
        self.annotations = annotations

    def __getitem__(self, idx):
        image_path = self.image_paths[idx]
        boxes = self.annotations[idx]['boxes']
        image = cv2.imread(image_path)
        transformed = transforms(image=image, bboxes=boxes, class_labels=[0]*len(boxes))
        return transformed['image'], transformed['bboxes']

    def __len__(self):
        return len(self.image_paths)

# Initialize and load your dataset and dataloader
dataset = CustomDataset(image_paths, annotations)
dataloader = DataLoader(dataset, batch_size=16, shuffle=True)

# Set up and train your model
model = YOLO('yolov8n.pt')
for epoch in range(epochs):
    for images, targets in dataloader:
        results = model.train(images, targets)  # Adapt this pseudocode for proper API integration

```

This script requires slight adjustments based on your training routine setup and how Ultralytics implements their training function. Creating a guide or tutorial on this advanced customization might indeed be beneficial for many users, and I'll forward this as a suggestion to our team for future documentation improvements! Thank you for the insightful feedback and suggestions. 🌟

**Comment by ternaus** [comment]
Thanks for the answer

What about defining custom Detection trainer like

```python
from ultralytics.models.yolo.detect.train import DetectionTrainer

class AlbumentationsTrainer(DetectionTrainer):
    def build_dataset(self, img_path, mode="train", batch=None):
        return <define dataset with Albumentations here >
```

and pass it as:
```python
model.train(trainer=AlbumentationsTrainer())
```
Will something like that work?

**Comment by glenn-jocher** [comment]
Hello!

Thanks for sharing your idea! Currently, customizing the training process to that extent (such as directly extending and modifying a `DetectionTrainer` class) isn't directly supported by Ultralytics YOLOv8's API. The training functionality is generally encapsulated within the YOLO class without explicit support for swapping out components like the trainer or dataset builder in the manner you've described.

However, you can certainly integrate Albumentations by modifying the data loading process external to the model and then passing prepared batches to the model manually during the training loop, as demonstrated in previous examples. 

Here's a quick example of how you might prepare those batches:
```python
from ultralytics import YOLO
from your_custom_dataloader import CustomDataset, DataLoader

# Create DataLoader with Albumentations
dataset = CustomDataset(image_paths, annotations, transforms=your_albumentations_transforms)
dataloader = DataLoader(dataset, batch_size=16, shuffle=True)

# Load model
model = YOLO('yolov8n.pt')

# Training loop
for images, targets in dataloader:
    loss = model.train_step(images, targets)  # Pseudocode for illustration
```

For more sophisticated modifications, you might need to delve into the source code. Let us know if you need further assistance! 😊

**Comment by shay82** [comment]
Hi @glenn-jocher 

Thanks for all of your feedbacks, I just have quick questions
I return an image and annotations (labels) from __getitem__
some images has no annotations at all, while some has one or more.

boxes is an array of [[x1,y1,x2,y2]]

The problem is that I get following error later, during execution:

>  File "c:\repositories\AutoSpermRecorder\autosperm_venv\Lib\site-packages\torch\utils\data\_utils\collate.py", line 121, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\repositories\AutoSpermRecorder\autosperm_venv\Lib\site-packages\torch\utils\data\_utils\collate.py", line 174, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: stack expects each tensor to be equal size, but got [0] at entry 0 and [63, 4] at entry 2

Here is the relevant parts of the code:
> image = cv2.imread(img_path)
> image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
> folder_path = os.path.dirname(img_path)
> file_name_prefix = os.path.splitext(os.path.basename(img_path))[0]
> annotation_file = os.path.join(folder_path, f"{file_name_prefix}.txt")
> annotations_list = yolo_utils.read_annotation_file(annotation_file)
> annotations_list = ... _//convert each line to array of [x1,y1,x2,y2]_
> image = np.transpose(image, (2, 0, 1)).astype(np.float32)
> transformed_annotations = np.array(annotations_list ).astype(np.float32)        
> return image, transformed_annotations

Why does it expect that all boxes array would have the same shape size?
Any idea how work around it?

**Comment by glenn-jocher** [comment]
Hi @shay82,

The error occurs because `torch.stack` expects all tensors in the batch to have the same shape. To handle images with varying numbers of annotations, you can pad the annotations to a fixed size or use a custom collate function. Here's a minimal example of a custom collate function:

```python
def collate_fn(batch):
    images, targets = zip(*batch)
    images = torch.stack(images)
    targets = [torch.tensor(t) for t in targets]
    return images, targets

dataloader = DataLoader(dataset, batch_size=16, collate_fn=collate_fn)
```

This should help you avoid the `RuntimeError`. Let me know if you need further assistance!

**Comment by glenn-jocher** [comment]
Hi,

For the image dimensions mismatch, resizing images to a consistent size (e.g., 640x640) or using padding is recommended. For the batch creation issue, ensure your `collate_fn` returns a dictionary with keys matching the expected format. Overriding `plot_training_labels` with `pass` is acceptable if you don't need that functionality.

**Comment by shay82** [comment]
> Hi,
> 
> For the image dimensions mismatch, resizing images to a consistent size (e.g., 640x640) or using padding is recommended. For the batch creation issue, ensure your `collate_fn` returns a dictionary with keys matching the expected format. Overriding `plot_training_labels` with `pass` is acceptable if you don't need that functionality.


Thank you @glenn-jocher 
Is there any documentation regarding which keys should be included in the batch? (what is the expected format that you mentioned?)

Is there an example of a recommended way for image padding?

**Comment by glenn-jocher** [comment]
@shay82 thank you for your questions. The expected keys in the batch dictionary are typically `img`, `bbox`, and `cls`. For image padding, you can use `cv2.copyMakeBorder` to pad images to a consistent size. Unfortunately, we don't have specific documentation on this, but you can refer to the PyTorch DataLoader documentation for more details on custom collate functions.
