### ISSUE TITLE
My datasets Imge size is 2400*9600, what should i set the input imgsz?

### ISSUE THREAD

**Issue by xinsuinizhuan** [ultralytics/ultralytics#1018]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My datasets Imge size is 2400*9600, what should i set the input imgsz?

**Comment by knoppmyth** [comment]
You don't have to specify anything, training will be done at 640 x 640 be default.

**Comment by xinsuinizhuan** [comment]
but when resize the imge to 640 x 640, too much compression in the height direction, and the small object will lose

**Comment by pderrenger** [comment]
@xinsuinizhuan you can address this issue by setting the `--rect` flag during training. This will enable "rectangular multi-scale training," allowing your model to efficiently handle varied aspect ratios and preserve small objects during training.
