### ISSUE TITLE
Yolov9 Classification

### ISSUE THREAD

**Issue by GBHU753** [ultralytics/ultralytics#10186]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there going to be support for Yolov9 Classification like there is for detection and segmentation currently? If so what is the expected timeline? TIA

**Comment by glenn-jocher** [comment]
Hey there! 🚀 As of now, there aren't any public plans or timelines to include a specific YOLOv9 Classification model like the ones available for YOLOv8. However, updates and new features are constantly being considered based on user feedback and demand. Make sure to keep an eye on our [GitHub](https://github.com/ultralytics/ultralytics) and official [documentations](https://docs.ultralytics.com/) for any future announcements on this. Thanks for your interest!
