### ISSUE TITLE
NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend.

### ISSUE THREAD

**Issue by MuhammadSuhaib01** [ultralytics/ultralytics#10195]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, Meta, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, BatchedNestedTensor, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

### Environment

Ultralytics YOLOv8.1.32 🚀 Python-3.11.4 torch-2.2.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
Setup complete ✅ (12 CPUs, 13.9 GB RAM, 321.6/465.7 GB disk)

### Minimal Reproducible Example

import cv2
from ultralytics import YOLO

# Load your model
model = YOLO('D:/Work Space/Python Development/Virtual Enviroment/Pose Detection With Reps Count/yolov8s-pose.pt')

# Open the video
cap = cv2.VideoCapture("gymvideo.mp4")

# Process each frame
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Run model prediction
    results =  model('gymvideo.mp4',stream=False)

    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs      
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

    # Extract keypoints
    keypoints = results[0].keypoints

    # Draw keypoints on the frame
    for kpt in keypoints.xy:
        x = int(kpt[0][0]) 
        y = int(kpt[0][1])
        cv2.circle(frame, (x, y), radius=3, color=(0, 255, 0), thickness=-1)

    # Show the frame with keypoints
    cv2.imshow('Keypoints without lines', frame)
    
    # Break the loop if 'q' is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the video capture object and close all windows
cap.release()
cv2.destroyAllWindows()

### Additional

NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, Meta, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, BatchedNestedTensor, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

This is the complete error. I have re-installed cuda, cudnn and pytorch with several versions upgrading and downgrading their versions still i am facing the same issue can someone help me?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi there! 😊 It looks like you're encountering an issue with the Non-Maximum Suppression (NMS) function from torchvision not being compatible with the 'CUDA' backend. This issue may be related to the version compatibility between PyTorch, torchvision, and CUDA. Given your setup, here are a couple of things you might try:

1. **Ensure Compatibility:** Double-check that your PyTorch and torchvision versions are compatible with each other and with CUDA 12.1. PyTorch's [previous versions page](https://pytorch.org/get-started/previous-versions/) can be particularly helpful for finding compatible versions.

2. **Reinstall torchvision:** Sometimes, a fresh installation of torchvision may resolve backend issues. Be sure to match the torchvision version with your PyTorch installation:
```bash
pip install torch torchvision --upgrade
```

3. **Check CUDA Toolkit:** Make sure your system's CUDA toolkit version matches the version supported by PyTorch. Different versions of PyTorch may require specific versions of CUDA.

If you've tried these steps and the problem persists, it might help to provide more information on the versions of torchvision you've tried, as well as confirming the CUDA toolkit version installed on your system. Sometimes, the devil's in the details with version-specific issues. 

Keep us posted on how it goes, and we'll do our best to help you get it sorted! 🚀
