### ISSUE TITLE
MLflow change parameters

### ISSUE THREAD

**Issue by emanueleromito** [ultralytics/ultralytics#10208]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I'm calling an MLflow entrypoint which creates me a run, then does this:

`client = setup()`
`existing_run = *gets the run id whit a function*`
`train_task = [delayed(train_model)(epochs, batch, patience, optimizer, imgsz, existing_run)]`
`results = client.compute(train_task, sync=True, retries=0)`
`client.close()`

then the dask worker excecute this code:

  with mlflow.start_run(run_id=existing_run.info.run_id) as run:
      `model = YOLO('yolov8n.pt')`
      `model.train(
          name=existing_run.info.run_id,
          project="YOLO",
          data="coco8.yaml",
          epochs=epochs,
          batch=batch,
          patience=patience,
          optimizer=optimizer,
          imgsz=imgsz,
      )`

Everything is working, except for one thing: 2024-04-21 20:11:03 MLflow: WARNING ⚠️ Failed to initialize: INVALID_PARAMETER_VALUE: Changing param values is not allowed. Params were already logged='[{'key': 'name', 'old_value': 'train4', 'new_value': '169c1957c9274defaa5826cdf090315d'}]' for run ID='169c1957c9274defaa5826cdf090315d'.

For some reason, i've as old name of the rain directory some old directory name, so this results in mlflow not tracking my run.

**Comment by glenn-jocher** [comment]
Hi there! 👋

It seems like you're facing a challenge with changing parameter values in an MLflow run that has already logged parameters. This warning arises because MLflow restricts modifications to parameters after they've been logged for a run, to ensure data consistency and traceability.

A potential solution is to ensure parameters are set correctly before they're logged in MLflow for the first time. If you need to track changes or updates to parameters, consider logging these as new records or using tags, which can be more flexible.

For your specific case, when you initialize the `YOLO` model training, try setting the `name` parameter (which appears to be the `run_id` in your context) just once and avoid changing it throughout the session. Since MLflow is giving an error about changing the `name` parameter, ensure it aligns with the intended `run_id` before the training process starts. If you need to link the training to an existing run, make the `run_id` or `name` consistent from the onset.

Here's a quick check to ensure consistency:

```python
# Ensure the run_id is correctly set before initiating the training
desired_run_id = "your_desired_run_id"
# Use this desired_run_id consistently when starting the YOLO training
model.train(
    name=desired_run_id,
    project="YOLO",
    data="coco8.yaml",
    epochs=epochs,
    batch=batch,
    patience=patience,
    optimizer=optimizer,
    imgsz=imgsz,
)
```

Hope this helps! Let us know if you encounter any further issues.

**Comment by emanueleromito** [comment]
Hi glenn, thanks it worked! I just want to ask you one more thing:

I'm doing a tuning operations, and I want to know if it's possibile to change the directory name of where the tuner puts the best results. With param "name" i'm changing run names, but not the main dir where I could fine best_hyperparameters.yaml

**Comment by emanueleromito** [comment]
Actually if i set save_dir, it will be popped in this method: 

![image](https://github.com/ultralytics/ultralytics/assets/58727116/efde4712-00b0-4d0d-8507-684bc5b0513e)

**Comment by glenn-jocher** [comment]
@emanueleromito hi! Glad to hear you found a solution for naming the runs. Regarding the `tune_dir` and `save_dir`, thanks for highlighting this issue with the method popping `save_dir` as shown in the screenshot.

Currently, `save_dir` is indeed managed internally to organize results, and in the specific context of hyperparameter tuning, the output is organized by design to ensure a structured and consistent directory schema for tracking experiments.

For custom tuning directory control, a workaround could be to programmatically move or copy the relevant directories/files to your desired location after the tuning operation completes. This script snippet demonstrates a simple way to do this in Python:

```python
import shutil
# Suppose your tuning operation completes and the best hyperparameters are saved in 'runs/tune/exp'
source_dir = 'runs/tune/exp'
destination_dir = 'your/custom/path/best_hyperparameters_exp'

# Copy entire directory to your desired location
shutil.copytree(source_dir, destination_dir)
```

This approach allows you to maintain the integrity of the tuning process while also accommodating the need for customized directory management. 

Hope this helps, and we're continuously working to improve usability based on user feedback like yours! 🚀

**Comment by emanueleromito** [comment]
thanks glenn it was really helpful.

**Comment by glenn-jocher** [comment]
You're welcome! Glad I could help. If you have any more questions or run into issues, feel free to reach out. Happy coding! 😊

**Comment by afonsopastana** [comment]
Hello!

I'm experiencing a similar problem when training a YOLOv9 model with MLFlow tracking in AZURE ML.
I have this script where i trained a YOLOv8 model without any problems, and got a very good performance, but this time i'd like to try YOLOv9 to see if it's any better. But just by changing the model the training process crashes. 
I'm pasting the code here, it's a bit long but i'm not sure which part of it is causing this problem.
Right after im pasting the message error i got

`
    from ultralytics import YOLO
    from ultralytics.utils.downloads import unzip_file
    #from ultralytics.yolo.utils.metrics import ConfusionMatrix, DetMetrics, box_iou
    from sklearn.model_selection import train_test_split
    import mlflow
    import argparse
    import sys
    import os
    import yaml
    import azureml.core
    from azureml.core import Workspace
    from azure.ai.ml import MLClient
    from azure.identity import DefaultAzureCredential, InteractiveBrowserCredential, ManagedIdentityCredential
    import azure.identity
    import json
    import gc
    import torch
    import sklearn
    import time  
    import numpy as np
    import zipfile
    
    
    def main():
    
    #Vider la mémoire cahce de du compute cluster
    #gc.collect()
    #torch.cuda.empty_cache()
    #Id of the Azure Active Directory
    #os.environ["AZURE_TENANT_ID"] = ""
    #Id client of the Managed Identity
    #os.environ["AZURE_CLIENT_ID"] = ""
    
    #Passage de la valeur de timeout de 300 à 3000 pour éviter l'arreur timeout lors de la sauvegarde des artifacts
    os.environ["AZUREML_ARTIFACTS_DEFAULT_VALUE"] = "3000"


    #os.environ["PYTORCH_CUDA_ALLOC_CONF"]="max_split_size_mb:2048"

    #authentication package
    try:
        print('Try connect with ManagedIdentityCredential')
        default_identity_client_id = os.environ.get('DEFAULT_IDENTITY_CLIENT_ID')
        print('default_identity_client_id',default_identity_client_id)
        credential = DefaultAzureCredential(managed_identity_client_id=default_identity_client_id)

    except Exception as ex:
        # Fall back to InteractiveBrowserCredential in case DefaultAzureCredential not work
        print('Failed to connect with ManagedIdentityCredential')
        credential = InteractiveBrowserCredential()


    from azure.ai.ml import MLClient

    # Get a handle to the workspace

    
    ml_client = MLClient(
        subscription_id=subscription_id,
        resource_group_name=resource_group_name,
        workspace_name=workspace_name,
        credential=credential
    )
    
    ws = ml_client.workspaces.get(workspace_name)

    print("mlflow.get_tracking_uri()  ",mlflow.get_tracking_uri())
    mlflow.set_tracking_uri(ws.mlflow_tracking_uri)
    print("mlflow.get_tracking_uri()  ",mlflow.get_tracking_uri())


    # Récupération des arguments passés lors de l'appel de la fonction
    parser = argparse.ArgumentParser()
    parser.add_argument("--project_name", type=str, help="project_name")
    parser.add_argument("--experiment_name", type=str, help="comptage_YOLO_model")
    parser.add_argument("--train_images_ds", type=str, help="img dataset train")
    #parser.add_argument("--train_images_ds_2", type=str, help="img dataset train 2")
    parser.add_argument("--test_images_ds", type=str, help="img dataset train")
    parser.add_argument("--train_labels_ds", type=str, help="label dataset train")
    #parser.add_argument("--train_labels_ds_2", type=str, help="label dataset train 2")
    parser.add_argument("--test_labels_ds", type=str, help="label dataset test")
    parser.add_argument("--registered_model_name", type=str, help="Nom du modèle")
    parser.add_argument("--cuda_launch_blocking", type=str, help="CUDA_LAUNCH_BLOCKING")
    parser.add_argument("--nb_epoch", type=int, help="nombre d'époch d'entraînement")
    parser.add_argument("--save_period", type=int, help="intervale de sauvegarde du modèle")
    parser.add_argument("--batch_size", type=int, help="nombre d'images dans chaque batch")
    parser.add_argument("--loaded_model_name", type=str, help="nom du modèle à charger")
    parser.add_argument("--is_files_train_zipped_bool", type=int, help="bool si les fichiers trains sont zippés")
    parser.add_argument("--model_gen_save_bool", type=int, help="mode qui génère un model MLFlow à partir des poids")
    parser.add_argument("--pretrained_model_bool", type=int, help="chargement d'un modèle pre_trained")
    parser.add_argument("--train_model_bool", type=int, help="entrainement ou chargement")
    parser.add_argument("--transfer_learning_bool", type=int, help="Valeur qui gêle les layer du backbone pour n'entraîner que le classifieur")
    parser.add_argument("--val_images_ds", type=str, help="img dataset test")
    parser.add_argument("--val_labels_ds", type=str, help="label dataset train")
    parser.add_argument("--close_mosaic", type=int, help="booléen qui active ou pas l'augmentation mosaic")
    parser.add_argument("--patience_nb", type=int, help="epochs to wait for no observable improvement for early stopping of training")
    parser.add_argument("--model_lr0", type=float, help="initial learning rate")
    parser.add_argument("--model_lrf", type=float, help="final learning rate (lr0 * lrf)")
    parser.add_argument("--model_type", type=str, help="type d emodèle chargé, ex: n, s, m, l, x")

    args = parser.parse_args()


    #Si l'expérience est réalisée depuis AML
    if "AZUREML_RUN_ID" in os.environ:
        print('Lancement des autologgings')
        #mlflow.start_run(run_name=f"{args.registered_model_name}-bacth_size-{args.batch_size}-nb_epoch-{args.nb_epoch}-files_zipped-{args.is_files_train_zipped_bool}")
        mlflow.autolog()

    else:
        #Si lancé depuis Jupyter notebook par exemple
        mlflow.set_experiment(experiment_name="comptage_YOLO_exp_stage2")
        mlflow.start_run(run_name=f"{args.registered_model_name}-bacth_size-{args.batch_size}-nb_epoch-{args.nb_epoch}-files_zipped-{args.is_files_train_zipped_bool}") 

    #Set CUDA
    os.environ['CUDA_LAUNCH_BLOCKING'] = args.cuda_launch_blocking

    #Récupération de chemin absolu vers le dossier d'exécution
    root_mount_path = os.path.realpath('.')

    #Création du chemin vers les fichiers text et création du dossier
    img_txt_dir = os.path.join(root_mount_path,'images')

    ###################
    #<prepare the data>
    ###################

    #Vérifie s'il y a un jeu de données de validation, ou s'il faut le créer
    if args.val_images_ds==None :
        #Alors il faut scinder le train dataset en en un train et val dataset

        if args.is_files_train_zipped_bool==1:
            #définition des chemins de destinations des dossiers décompressés
            train_img_dir = os.path.join(root_mount_path,'images/train_data')
            train_label_dir = os.path.join(root_mount_path,'labels/train_data')

            #Création des dossiers correspondant à ces chemins
            os.makedirs(train_img_dir)
            os.makedirs(train_label_dir)

            #Décompression et envoi des dossiers résultants vers dossiers créés
            unzip_file(args.train_images_ds, path=train_img_dir)
            unzip_file(args.train_labels_ds, path=train_label_dir)

            path_to_train_images_ds_dir = os.path.join(train_img_dir,os.path.basename(args.train_images_ds).split(".")[0])

            #L'actual chemin vers les annotations ressemble à                               "./labels/train_data/generated_labels_grayscale_train"
            #Or le chemin vers les images ressemble à                                       "./images/train_data/generated_images_grayscale_train"
            #Le model YOLO va donc chercher un chemin pour les annotations ressemblant à    "./labels/train_data/generated_images_grayscale_train" 
            #c'est une règle interne à YOLO, qui veut que l'arborescence des dossiers soit "symétrique" entre le cheminement vers les image et celui vers les annotations
            #Il faut donc renommer le dossier contenant les annotations pour qu'il puisse être trouvé 

            actual_path_to_train_labels_ds_dir = os.path.join(train_label_dir,os.path.basename(args.train_labels_ds).split(".")[0])
            path_to_train_labels_ds_dir = os.path.join(train_label_dir,os.path.basename(args.train_images_ds).split(".")[0])
            os.rename(actual_path_to_train_labels_ds_dir, path_to_train_labels_ds_dir)

        else:
            path_to_train_images_ds_dir = args.train_images_ds
            path_to_train_labels_ds_dir = args.train_labels_ds
            #path_to_train_images_ds_dir_2 = args.train_images_ds_2
            #path_to_train_labels_ds_dir_2 = args.train_labels_ds_2
        


        print(f'path_to_train_images_ds_dir : {path_to_train_images_ds_dir}')
        print(f'path_to_train_labels_ds_dir : {path_to_train_labels_ds_dir}')

        #X_raw = os.listdir(path_to_train_images_ds_dir) + os.listdir(path_to_train_images_ds_dir_2)
        X_raw = os.listdir(path_to_train_images_ds_dir)

        X_jpg = [filename for filename in X_raw if filename.endswith(".jpg")]

        #y_raw = os.listdir(path_to_train_labels_ds_dir) + os.listdir(path_to_train_labels_ds_dir_2)
        y_raw = os.listdir(path_to_train_labels_ds_dir)

        y_txt = [filename for filename in y_raw if filename.endswith(".txt")]

        print(f'X_jpg : {X_jpg}')
        print(f'Taille X_jpg : {len(X_jpg)}')
        print(f'y_txt : {y_txt}')
        print(f'Taille y_txt : {len(y_txt)}')

        #Séparation des données d'entrées et cibles en deux jeux train et val
        X_train, X_val, y_train, y_val = train_test_split(X_raw, y_raw, test_size=0.3, random_state=2)

        #Récupération de chemin absolu vers le dossier d'exécution
        root_mount_path = os.path.realpath('.')

    
        #Création du fichier txt avec les chemins vers les images de train
        with open(os.path.join(img_txt_dir,'train.txt'),'w') as f:
            for item in X_train:
                f.write("%s\n" % os.path.join(path_to_train_images_ds_dir,item))

        #Création du fichier txt avec les chemins vers les images de val
        with open(os.path.join(img_txt_dir,'val.txt'),'w') as f:
            for item in X_val:
                f.write("%s\n" % os.path.join(path_to_train_images_ds_dir,item))

        #Je souhaite évaluer la performance de mon model sur le test dataset
        #Comme la méthode val() se fait par défaut sur le dataset déclaré en val, alors je déclare mon test dataset en val

        X_test = os.listdir(args.test_images_ds)

        # Définition du contenu du fichier YAML
        train_src="train.txt"
        val_src="val.txt"
        test_src="test_data"


    else:
        # Définition du contenu du fichier YAML
        train_src="train_data"
        val_src="val_data"
        test_src="test_data"



    # Définition du contenu du fichier YAML
    data = {
        'path': f'{os.path.realpath("./images")}',
        'train': f'{train_src}',
        'val': f'{val_src}',
        'test': f'{test_src}',
        'names': {
            0: 'larve altise',
            1: 'autre'
        }
    }


    # Écriture du fichier YAML pour l'entrainement
    with open('./larves_altise_dataset.yaml', 'w') as file:
        yaml.dump(data, file)




    ####################
    #</prepare the data>
    ####################

    ##################
    #<train the model>
    ##################

    #def on_train_epoch_start_time(trainer):  # results -> List[batch_size]
    #    time_stamp = time.time()
    #    prev_time_stamp = time_stamp
    #    mlflow.log_metric("epoch_start_time",time_stamp)

    #def on_train_epoch_end_time(trainer):  # results -> List[batch_size]
    #    time_stamp = time.time()
    #    mlflow.log_metric("epoch_end_time",time_stamp)
    #    mlflow.log_metric("epoch_duration",time_stamp-prev_time_stamp)

    #model_yolo.add_callback("on_train_epoch_start", on_train_epoch_start_time)
    #model_yolo.add_callback("on_train_epoch_end", on_train_epoch_end_time)


    #log des paramètres
    dataset_file_name = "larves_altise_dataset.yaml"
    nb_epochs = args.nb_epoch
    img_size = 640
    batch_size = args.batch_size
    project_name = args.project_name
    experiment_name = args.experiment_name
    registered_model_name = f'trained_{args.registered_model_name}'
    model_path = "model"
    optimizer_model = "SGD"
    is_training = args.train_model_bool

    params = vars(args)
    print("dictionnaires de params")
    print(params)
    mlflow.log_params(params)
    
    # création d'une fonction de compression qui sert à compresser les résultats des prédictions
    def compress_folder(folder_path, zip_name):
        with zipfile.ZipFile(zip_name, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for root, _, files in os.walk(folder_path):
                for file in files:
                    file_path = os.path.join(root, file)
                    zipf.write(file_path, os.path.relpath(file_path, folder_path))

    compressed_predictions_zipped_file = 'prediction_compressed.zip'


    weights_saving_nb = 0
    
    if args.train_model_bool==1:

        if args.pretrained_model_bool==1 and args.loaded_model_name == "default":
            #Chargement d'un modèle pré-entraîné sur COCO
            print(f"Chargement model : yolov8{args.model_type}.pt")
            model_yolo = YOLO(f"yolov8{args.model_type}.pt")
        elif args.pretrained_model_bool==1 and args.loaded_model_name != "default":
            print("Chargement model : ", args.loaded_model_name)
            model_yolo = YOLO(args.loaded_model_name)
        else:
            #Chargement d'un modèle non pré-entraîné avec des poids initialisés aléatoirement
            print("Chargement model non pré-entraîné : yolov8n.yaml")
            model_yolo = YOLO('yolov8n.yaml')
        
        #Fonction appelée au démarrage de l'entrainement
        def on_train_start(trainer):
            global weights_saving_nb
            weights_saving_nb = 0

        model_yolo.add_callback("on_train_start", on_train_start)

        #https://docs.ultralytics.com/usage/callbacks/
        #Fonction appelée à la fin d'une époque d'entrainement
        def on_train_epoch_end(trainer):
            print(trainer.loss_names)
            #box_loss: bounding box regression loss (Mean Squared Error)
            #cls_loss: the confidence of object presence is the objectness loss
            #dfl_loss: the classification loss (Cross Entropy)
            loss_dict = trainer.label_loss_items(trainer.tloss, prefix="train")
            mlflow.log_metrics(loss_dict)

        model_yolo.add_callback("on_train_epoch_end", on_train_epoch_end)

        # Fonction appelée au moment de la sauvegarde du model
        def on_model_save(trainer):
            print(trainer.last)
            print(trainer.wdir)
            print(trainer.save_dir)

            global weights_saving_nb
            weights_saving_nb = weights_saving_nb + 1
            save_period = args.save_period
            print(f'{registered_model_name}-epoch-{weights_saving_nb*save_period}')

            mlflow.log_artifacts(os.path.join(project_name,experiment_name,"epoch{weights_saving_nb*save_period}.pt"),f"save-trained-weights-epoch-{weights_saving_nb*save_period}")
        
        #model_yolo.add_callback("on_model_save", on_model_save)


        #on_pretrain_routine_start 	Triggered at the beginning of pre-training routine
        #on_pretrain_routine_end 	Triggered at the end of pre-training routine
        #on_train_start 	Triggered when the training starts

        def on_pretrain_routine_start(trainer):
            print('on_pretrain_routine_start')

        model_yolo.add_callback("on_pretrain_routine_start",on_pretrain_routine_start)

        def on_pretrain_routine_end(trainer):
            print('on_pretrain_routine_end')
            # Freeze 
            freeze = [f'model.{x}.' for x in range(0,10)]  # layers to freeze 
            for k, v in model_yolo.model.named_parameters(): 
                v.requires_grad = True  # train all layers 
                if any(x in k for x in freeze): 
                    print(f'freezing {k}') 
                    v.requires_grad = False 

        if args.transfer_learning_bool==1:
            model_yolo.add_callback("on_pretrain_routine_end",on_pretrain_routine_end)

        def on_train_start(trainer):
            print('on_train_start')
        
        model_yolo.add_callback("on_train_start",on_train_start)

        # définition de l'option close_mosaic selon si elle est activée ou non
        if args.close_mosaic==1:
            close_mosaic = args.nb_epoch
        else:
            close_mosaic = 10

        #https://docs.ultralytics.com/usage/cfg/#train
        print('Start training')
        train_results = model_yolo.train(
            data=dataset_file_name,
            epochs=nb_epochs, 
            imgsz=img_size,
            batch= int(batch_size),
            project=project_name,
            name=experiment_name,
            verbose=True,
            optimizer=optimizer_model,
            save_period=args.save_period,
            close_mosaic=close_mosaic,
            patience=args.patience_nb,
            lr0=args.model_lr0,
            lrf=args.model_lrf
        )

        mlflow.log_artifacts(os.path.join(project_name,experiment_name),"train_result")

        evaluation_folder_path = os.path.join(project_name,f'{experiment_name}2')

        prediction_folder_path = os.path.join(project_name,f'{experiment_name}3')

        
    else:
        print('Chargement des poids du modèle')
        if args.loaded_model_name == "default":
            model_yolo = YOLO("yolov8n.pt")
        else:
            model_yolo = YOLO(args.loaded_model_name)

        evaluation_folder_path = "runs/detect/val"
        prediction_folder_path = 'runs/detect/predict'  


    # Définition du contenu du fichier YAML pour l'evaluation
    data = {
        'path': f'{os.path.realpath("./images")}',
        'train': f'{train_src}',
        'val': f'{test_src}',
        'test': f'{test_src}',
        'names': {
            0: 'larve altise',
            1: 'autre'
        }
    }

    # Écriture du fichier YAML pour l'evaluation
    with open('./larves_altise_dataset.yaml', 'w') as file:
        yaml.dump(data, file)

     #J'écrase le fichier avec les chemins vers les images val.txt avec les chemin vers les images de test 
    with open(os.path.join(img_txt_dir,'val.txt'),'w') as f:
        for item in X_test:
            f.write("%s\n" % os.path.join(args.test_images_ds,item))

    #Evaluation sur les images test
    val_results = model_yolo.val() 
    
    mlflow.log_artifacts(evaluation_folder_path,"evaluation_result")  


    #Prédiction sur les images test
    predict_results = model_yolo.predict(source=args.test_images_ds, save=True, save_txt=True)

    compress_folder(prediction_folder_path, compressed_predictions_zipped_file)

    print(os.path.realpath('.'))
    print(os.listdir(os.path.realpath('.')))
    mlflow.log_artifact(compressed_predictions_zipped_file,"predict_result")

    #Création d'un fichier txt avec les résultats des prédiction
    with open('prediction_results.txt','w') as f:
        for index, result in enumerate(predict_results):
            print("result.boxes.xywhn",result.boxes.xywhn)
            print("result.boxes.conf",result.boxes.conf)

            #f.write("boxes.xywhn : %s\n" % result.boxes.xywhn)
            for indice in result.boxes.conf:
                f.write("%s\n" % indice.item())
    
    mlflow.log_artifact('prediction_results.txt',"predict_result")


    res = {}
    for r in predict_results:
        path = r.path
        confs = r.boxes.conf
        clss = r.boxes.cls
        xyxys = r.boxes.xyxy

        res[path] = {'confidence': confs.tolist(), 'classe': clss.tolist(), 'bbox(xyxy)': xyxys.tolist()}

    with open('prediction-results.json', 'w') as f:
        json.dump(res, f)

    mlflow.log_artifact('prediction-results.json', "predict_result")


    if args.model_gen_save_bool == 1:
        print("Registering the model via MLFlow")

        # Définition de la classe YOLOWrapper qui permet d'encapsuler 
        #le modèle YOLO avec la librairie Ultralytics
        class YOLOWrapper(mlflow.pyfunc.PythonModel):

            def load_context(self, context):
                from ultralytics import YOLO
                model_path = context.artifacts["model_pt_file"]
                self.YOLO_model = YOLO(model_path)

            def predict(self, context, model_input):
                try:
                    #results = self.YOLO_model.predict(model_input)
                    results = self.YOLO_model(model_input)
                    return results
                except Exception as err:
                    raise Exception(err)
                    return None



        
        #Création des différentes variables pour l'enregistrement du model
        registered_model_name = f'trained_{args.registered_model_name}'
        
        # Create a Conda environment for the new MLflow Model that contains all necessary dependencies.
        conda_env = {
            "channels": ["defaults"],
            "dependencies": [
                "python=3.8.16",
                "pip<=23.0.1",
                {
                    "pip": [
                        "mlflow<3,>=2.3",
                        "cffi==1.15.1",
                        "cloudpickle==2.2.1",
                        "ipython==8.12.0",
                        "torch==1.11.0",
                        "ultralytics==8.2.0"
                    ],
                },
            ],
            "name": "mlflow-env",
        }

        artifacts = {
            "model_pt_file" : "yolov9c.pt"
        }

        # Save the MLflow Model
        mlflow.pyfunc.log_model(
            python_model = YOLOWrapper(),
            artifact_path = "model",
            conda_env = conda_env,
            registered_model_name = registered_model_name,
            artifacts = artifacts
        )
            
    #print("liste des fichiers et dossiers à la racine")
    #print(os.listdir("./outputs"))
    ###########################
    #</save and register model>
   
    
    # Stop Logging si lancé depuis un notebook Jupyter
    if 'AZUREML_RUN_ID' not in os.environ:
        mlflow.end_run()
`

The error message is the following:

`[34m[1mMLflow: [0mdisable with 'yolo settings mlflow=False'
[34m[1mMLflow: [0mWARNING ⚠️ Failed to initialize: INVALID_PARAMETER_VALUE: Response: {'Error': {'Code': 'ValidationError', 'Severity': None, 'Message': 'A given key of Parameters can not modify its value after it is set', 'MessageFormat': None, 'MessageParameters': None, 'ReferenceCode': None, 'DetailsUri': None, 'Target': None, 'Details': [], 'InnerError': None, 'DebugInfo': None, 'AdditionalInfo': None}, 'Correlation': {'operation': 'a376f6285f62418eb861268dd21e34b5', 'request': '94ad812ef4e99252'}, 'Environment': 'francecentral', 'Location': 'francecentral', 'Time': '2024-07-31T13:54:24.5458567+00:00', 'ComponentName': 'mlflow', 'statusCode': 400, 'error_code': 'INVALID_PARAMETER_VALUE'}
[34m[1mMLflow: [0mWARNING ⚠️ Not tracking this run`


The error message is slightly different from the one above from @emanueleromito, but it's also about a change in a parameter value. I can't figure it out which one. 
the `name` parameter in `model.train` is always the same.
The strange thing is that the same code works for YOLOv8. 
Could this be a bug? 

Thank you very much for any help
