### ISSUE TITLE
YOLOv8-ONNXRuntime-CPP,Suggest adding examples,Segment Pose OBB

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#10212]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

https://github.com/ultralytics/ultralytics/blob/main/examples/YOLOv8-ONNXRuntime-CPP/main.cpp

Suggest adding examples

Segment
Pose
OBB

### Additional

https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@monkeycc hello there! 🌟 Thank you for your suggestion. We'll definitely consider adding more examples for utilizing YOLOv8 with ONNXRuntime in C++ for tasks like segmentation, pose estimation, and Oriented Bounding Box (OBB) detection. Your input helps us make our documentation more valuable for everyone. Keep an eye on the repository for updates. Meanwhile, if you're eager to contribute, we're always open to community contributions. Feel free to share any progress or examples you've developed. Your efforts could inspire others in the YOLO community! Keep exploring and creating awesome stuff! ✨
