### ISSUE TITLE
How to get specific iou

### ISSUE THREAD

**Issue by Haoran1234567** [ultralytics/ultralytics#10216]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to test the map under a specific IOU indicator on my own data set. For example, I want to know map85. How to operate it?
I have tried two methods. The first method is to add the parameter iou=0.85 to model.val(), and the result is still map50-90. The second method, I print 'iou_score = metrics.metrics['box' ].iou', the error '''AttributeError: 'DetMetrics' object has no attribute 'metrics'.''' will be reported

**Comment by glenn-jocher** [comment]
Hello! 😊 To evaluate the mAP at a specific IoU threshold, such as IoU=0.85 for your case, you should modify the `iou_thres` parameter in the model validation call. Here is how you can specify the IoU threshold:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('path/to/your/model.pt')

# Validate the model with a specific IoU threshold
results = model.val(iou_thres=0.85)
```

Make sure you're using the correct parameter `iou_thres` to set the IoU threshold for validation. This should give you the mAP at IoU=0.85 for your dataset. If you encounter any errors, ensure you're using the latest version of our library. 

We appreciate your contribution to the Ultralytics community. Let us know if you have further questions or need more assistance! 🚀
