### ISSUE TITLE
How to Train Model Segmentation Models by Masks?

### ISSUE THREAD

**Issue by Creayhhh** [ultralytics/ultralytics#10218]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi!
I have a dataset with some mask annotations.It is PNG format.
Can this dataset be directly used for training?or does it need to be converted to YOLO format?

Here is my dataset folder structure
```
meter_seg/
├── images/
│   ├── train/
│   │   ├── image1.jpg
│   │   ├── image2.jpg
│   │   └── ...
│   └── val/
│       ├── image1.jpg
│       ├── image2.jpg
│       └── ...
└── masks/
    ├── train/
    │   ├── image1.png
    │   ├── image2.png
    │   └── ...
    └── val/
        ├── image1.png
        ├── image2.png
        └── ...
```

And my ```data.yaml```
```
train: /root/meter_seg/images/train
val: /root/meter_seg/images/val
 
names:
  0: background
  1: pointer
  2: scale
```

And my train log
```
train: Scanning /root/meter_seg/labels/train... 0 images, 374 backgrounds, 0 corrupt: 100%|██████████| 374/374 [00:00<00:00, 3491.71it/s]
train: WARNING ⚠️ No labels found in /root/meter_seg/labels/train.cache. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
train: WARNING ⚠️ Cache directory /root/meter_seg/labels is not writeable, cache not saved.
WARNING ⚠️ No labels found in /root/meter_seg/labels/train.cache, training may not work correctly. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
val: Scanning /root/meter_seg/labels/val... 0 images, 40 backgrounds, 0 corrupt: 100%|██████████| 40/40 [00:00<00:00, 3470.02it/s]
val: WARNING ⚠️ No labels found in /root/meter_seg/labels/val.cache. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
val: WARNING ⚠️ Cache directory /root/meter_seg/labels is not writeable, cache not saved.
WARNING ⚠️ No labels found in /root/meter_seg/labels/val.cache, training may not work correctly. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.

.........

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
    12/1000      17.6G          0          0     0.4671          0          0        640: 100%|██████████| 6/6 [00:01<00:00,  3.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 13.38it/s]
                   all         40          0          0          0          0          0          0          0          0          0
WARNING ⚠️ no labels found in segment set, can not compute metrics without labels

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
    13/1000      17.6G          0          0     0.1232          0          0        640: 100%|██████████| 6/6 [00:01<00:00,  3.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 19.01it/s]
Traceback (most recent call last):
  File "/root/miniconda3/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/root/miniconda3/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 582, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/root/miniconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 673, in train
    self.trainer.train()
  File "/root/miniconda3/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 199, in train
    self._do_train(world_size)
  File "/root/miniconda3/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 419, in _do_train
    self.metrics, self.fitness = self.validate()
  File "/root/miniconda3/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 560, in validate
    metrics = self.validator(self)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/ultralytics/engine/validator.py", line 195, in __call__
    stats = self.get_stats()
  File "/root/miniconda3/lib/python3.10/site-packages/ultralytics/models/yolo/detect/val.py", line 170, in get_stats
    stats = {k: torch.cat(v, 0).cpu().numpy() for k, v in self.stats.items()}  # to numpy
  File "/root/miniconda3/lib/python3.10/site-packages/ultralytics/models/yolo/detect/val.py", line 170, in <dictcomp>
    stats = {k: torch.cat(v, 0).cpu().numpy() for k, v in self.stats.items()}  # to numpy
RuntimeError: torch.cat(): expected a non-empty list of Tensors

```

My annotations image like this
![5](https://github.com/ultralytics/ultralytics/assets/25573004/280d6b8a-b4ce-4ecc-99a2-74c9d8c48a77)
Color added
![mask1](https://github.com/ultralytics/ultralytics/assets/25573004/09fef50c-5c3b-4665-b5ba-2babf7125e5d)

**Comment by Creayhhh** [comment]
> Hey there! 👋 It looks like there's a small adjustment needed for your setup. For training segmentation models with YOLOv8 and mask annotations, you're on the right track with organizing your image and mask directories.
> 
> However, the path in your `data.yaml` for labels should point towards the `masks` directories rather than a non-existent `labels` directory. Here's a quick fix for your `data.yaml`:
> 
> ```yaml
> train: /root/meter_seg/images/train
> val: /root/meter_seg/images/val
> masks:  # Add this line
>   train: /root/meter_seg/masks/train  # and this line
>   val: /root/meter_seg/masks/val  # and this one too
>   
> names:
>   0: background
>   1: pointer
>   2: scale
> ```
> 
> With these corrections, YOLOv8 should correctly locate your mask annotations for training. No need to convert your dataset to another format; your PNG masks can be directly used. 🚀
> 
> Good luck with your training! If you have any more questions, feel free to ask.

Um,It's not work, It still prompts that the label cannot be found
But I found other method to transform mask annotations to yolo annotations，and successfully trained my model.
Thank you for your reply!

**Comment by glenn-jocher** [comment]
@Creayhhh hey! 🌟 I'm glad to hear you found a workaround by converting your mask annotations to the YOLO format and successfully trained your model. That's awesome problem-solving right there! If you ever need further assistance or have more questions, we're here to help. Happy training, and keep up the great work!

**Comment by MuhammadIrzam447** [comment]
@Creayhhh can you please share the method that worked for you for the conversion of the png masks to yolo label format.

**Comment by aouissaoui26** [comment]
@Creayhhh can you please share the method to convert the png masks to yolo label format.

**Comment by Creayhhh** [comment]
@MuhammadIrzam447  @aouissaoui26 
Hey! This is a python script that convert masks to yolo label, you can refer to it.
https://github.com/Creayhhh/mask2yolo

**Comment by aouissaoui26** [comment]
@Creayhhh  It worked! .Thank you so much for this script! It's been an absolute lifesaver for me.
