### ISSUE TITLE
How to change the batch?

### ISSUE THREAD

**Issue by qq978358810** [ultralytics/ultralytics#10228]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to use yolo model for batch prediction.

**Comment by glenn-jocher** [comment]
Hello! 👋 To use YOLOv8 for batch predictions, you can simply set the `batch_size` argument when running your model. If you're working from the command line, use the `batch` parameter like so:

```bash
yolo detect predict model=yolov8n.pt source=path/to/images batch=16
```

And if you're working in Python, you can adjust the `batch_size` during model loading or prediction like this:

```python
from ultralytics import YOLO

# Load model
model = YOLO('yolov8n.pt')

# Predict with specified batch size
results = model.predict(path/to/images, batch_size=16)
```

Just replace `path/to/images` with your images' directory or a list of image paths. Hope this helps! 😊

**Comment by qq978358810** [comment]
> Hello! 👋 To use YOLOv8 for batch predictions, you can simply set the `batch_size` argument when running your model. If you're working from the command line, use the `batch` parameter like so:
> 
> ```shell
> yolo detect predict model=yolov8n.pt source=path/to/images batch=16
> ```
> 
> And if you're working in Python, you can adjust the `batch_size` during model loading or prediction like this:
> 
> ```python
> from ultralytics import YOLO
> 
> # Load model
> model = YOLO('yolov8n.pt')
> 
> # Predict with specified batch size
> results = model.predict(path/to/images, batch_size=16)
> ```
> 
> Just replace `path/to/images` with your images' directory or a list of image paths. Hope this helps! 😊

I want to convert to onnx format for batch prediction, is that OK?

**Comment by glenn-jocher** [comment]
@qq978358810 absolutely! To export your YOLOv8 model to ONNX format for batch prediction, you can use the `export` mode and specify the batch size during the export. Here's how you can do it in the command line:

```shell
yolo export model=yolov8n.pt format=onnx imgsz=640 batch=16
```

And for Python, you'd do it like this:

```python
from ultralytics import YOLO

# Load model
model = YOLO('yolov8n.pt')

# Export to ONNX with specified batch size
model.export(format='onnx', imgsz=640, batch_size=16)
```

Just make sure to adjust the `imgsz` (image size) and `batch_size` according to your needs. Happy coding! 😊
