### ISSUE TITLE
How to Plot Training Results for YOLOv8 Using Excel Outputs?

### ISSUE THREAD

**Issue by khoanguyen311202** [ultralytics/ultralytics#10223]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, is there a way to plot the training results graph using the output Excel files?

I resumed training my model on Kaggle by hitting "Save & Run all (Commit)". Due to the model's complexity, it required up to three training sessions to complete within Kaggle's 12-hour limit. Each session produced a separate Excel file containing the results for that set of epochs. As a result, the final Excel file does not include data for all epochs.

Could you please advise on a method to re-plot the graphs? I plan to manually combine the Excel files to include data for all epochs.

Thank you for your assistance; I really appreciate it.

P.S. Do you have any suggestions for resuming training on Kaggle when it exceeds the 12-hour limit? If so, please share.

### Additional

![results](https://github.com/ultralytics/ultralytics/assets/85776466/7c4c499a-5407-4060-a71d-ce013a4b86a0)
The result file that I am mentioning about.

**Comment by glenn-jocher** [comment]
Hello!

Combining your Excel files manually and plotting the results is a good approach. Here's a concise way to achieve this using Python, which might be easier and more precise than doing everything manually in Excel:

1. **Combine Excel Files**: First, load all your Excel files using `pandas` and concatenate them into a single DataFrame. Assuming all files have the same structure:

```python
import pandas as pd

# List of your Excel file paths
files = ['session1.xlsx', 'session2.xlsx', 'session3.xlsx']

# Read and concatenate all files
df = pd.concat((pd.read_excel(file) for file in files), ignore_index=True)

# Optionally, save the combined DataFrame to a new Excel file
df.to_excel('combined_results.xlsx', index=False)
```

2. **Plotting**: Now, you can use the `matplotlib` library to plot your data directly from the combined DataFrame:

```python
import matplotlib.pyplot as plt

# Example of plotting the 'loss' column
plt.figure(figsize=(10, 6))
plt.plot(df['epoch'], df['loss'], marker='o', linestyle='-', color='b')
plt.title('Training Loss per Epoch')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.grid(True)
plt.show()
```

Make sure you adjust `'epoch'`, `'loss'`, and any other column names based on your actual Excel data.

🛠 **For resuming training on Kaggle** beyond the 12-hour limit, ensure you save checkpoints periodically (`--save_period`) to export your model's state. When resuming, simply load the latest checkpoint as the `model` argument for continued training:

```bash
yolo train data=mydata.yaml model=last.pt epochs=...
```

This way, you can pick up from where you left off in the next Kaggle session.

Hope this helps! Let us know if you have further questions. 😊

**Comment by khoanguyen311202** [comment]
@glenn-jocher Thank you for your wonderful help!

**Comment by glenn-jocher** [comment]
@khoanguyen311202 you're welcome! I'm glad I could assist. If you have any more questions down the line, feel free to reach out. Happy coding! 😊

**Comment by khoanguyen311202** [comment]
Hi, I just read Kaggle's doc about plotting. We can actually call the plotting function to plot the training results with the Excel file.

Here are the codes that I used: 

```
%pip install ultralytics
import ultralytics
ultralytics.checks()
```
Next, we have to move the Excel file from Input to Output folder. Otherwise, we'll face **OSError: [Errno 30] Read-only file system**.
```
import shutil
src_path = r"/kaggle/input/result-total/results.csv"
dst_path = r"/kaggle/working/"
shutil.copy(src_path, dst_path)
print('Copied')
```
Plotting:
```
from ultralytics.utils.plotting import plot_results
plot_results('/kaggle/working/results.csv', segment=True)
```


**Reference:** 
https://www.kaggle.com/code/abdurrakibmollah/move-files-from-input-to-output-folder
https://docs.ultralytics.com/reference/utils/plotting/#ultralytics.utils.plotting.plot_results

**Comment by glenn-jocher** [comment]
@khoanguyen311202 hey there! 🌟 Thanks for sharing these snippets; they're super handy for generating insightful plots directly from YOLOv8's exported CSV files!

Your approach to creating both separated and combined plots offers great flexibility in visualizing training progress. Additionally, organizing the plots into different directories keeps things neat and tidy, which is awesome! 📊

For anyone else looking into this, these snippets demonstrate a great way to dive deep into your model's performance metrics across epochs. Just remember to adjust the `file_path` and `columns_to_plot` based on your specific needs.

Happy plotting, and thanks again for contributing this! If you've got more tips or questions, feel free to share. Happy coding! 👩‍💻🚀
