### ISSUE TITLE
Built in Object Tracking

### ISSUE THREAD

**Issue by faizelkDatapost** [ultralytics/ultralytics#1022]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Could we in future have a built in tracking module like SORT.
So that every detection we get is assigned with a unique tracking ID

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
It's already available it's just not documented right now.
I'll work on it and it should be available by this weekend

**Comment by faizelkDatapost** [comment]
Thanks, really appreciate it, just a side not, will the trackingIDs be unique on each stream if you are running multiple streams?

**Comment by AyushExel** [comment]
I think currently we only support a single stream at a time. But it can be extended however you like for your projects.
@Laughing-q

**Comment by Laughing-q** [comment]
@faizelkDatapost @AyushExel each stream is having its own tracker so I think the trackIDs is unique for each stream.

**Comment by Laughing-q** [comment]
@pax7 it'll be very helpful if you provide more info about your issue .i.e which detection model and tracker you are using and also the configs, and probably the visualized img. :)

**Comment by AyushExel** [comment]
@pax7 does that happen with other models too like s, m, or l?

**Comment by AyushExel** [comment]
Then I think it a performance limitation and not a bug. The data you're testing on requires a more powerful model than the nano

**Comment by Laughing-q** [comment]
@AyushExel @pax7 yeah I think so, tracker also works good to me in my tests.

**Comment by faizelkDatapost** [comment]
@AyushExel have you managed to document how to use the tracker? no pressure, just following up

**Comment by AyushExel** [comment]
I'll do it later Today 😉

**Comment by andyg2** [comment]
I've been researching tracking for a while and I believe this is worth considering.

https://github.com/NirAharon/BOT-SORT

I'm not associated with the project, I looked though a bunch of [these](https://github.com/luanshiyinyang/awesome-multiple-object-tracking) and singled bot sort out for it's improved Kalman filter

**Comment by Laughing-q** [comment]
@andyg2 We've supported bot-sort! yeah it improved Kalman filter, that's why we implemented it.

**Comment by andyg2** [comment]
> @andyg2 We've supported bot-sort! yeah it improved Kalman filter, that's why we implemented it. :)

Oh I see!! I didn't realize it's already integrated [here](https://github.com/ultralytics/ultralytics/commit/ed6c54da7aaa6c491e41946d9cdee45d4662a5b5), that's just awesome!

**Comment by faizelkDatapost** [comment]
@AyushExel Hi Ayush just me following up again on the tracker document

**Comment by AyushExel** [comment]
Hey. It's live now. Please visit the docs :)

**Comment by faizelkDatapost** [comment]
Fantastic work great, Thanks a million.
However after making a git pull and installing ultralytics via 
`pip install ultralytics` 
I then executed as usual and it gave error  
`no module named lap` 
 i then did 
`pip install lap` 
and everything is good. 
Thought I should let you know maybe add lap in requirements file

**Comment by Laughing-q** [comment]
@faizelkDatapost oh I actually added a `check_requirements('lap')` there, but seems it doesn't work. I'll take a look at that.

**Comment by faizelkDatapost** [comment]
@Laughing-q  Thanks, closing this. Thanks a lot.

**Comment by Laughing-q** [comment]
@Laughing-q ok I added a patch in this PR #1078 .

**Comment by faizelkDatapost** [comment]
Awesome, tested it and it works with no manual intervention

**Comment by pderrenger** [comment]
@faizelkDatapost glad to hear that! If you encounter any further issues or have other feedback, feel free to let us know.
