### ISSUE TITLE
Multi-label detection

### ISSUE THREAD

**Issue by qbhnkkk** [ultralytics/ultralytics#10231]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to know if yolov8 supports multi-label detection, where an object in the data set has multiple labels.

**Comment by glenn-jocher** [comment]
Hello there! 😊 Yes, YOLOv8 does support multi-label detection. This means that a single object can indeed be assigned multiple labels during your detection tasks. You can structure your dataset accordingly, ensuring each instance is annotated with all relevant labels.

For your dataset annotation, you’d format each object’s annotation line in your labels file like so, with each label separated by a space:

```
<object-class1> <x_center> <y_center> <width> <height> <object-class2> <object-class3>...
```

Ensure that your dataset is correctly prepared, and you should be good to go with multi-label detection using YOLOv8. Happy detecting! 🚀

**Comment by sarpx** [comment]
@glenn-jocher We have been waiting for this for a long time. When did this come and is it valid for segmentation and other perceptions? Are there any issues that need attention? What is the success rate?
For example, red apple and red bicycle.. they are different objects but have a common red label and does this red really work properly for apple and bicycle?

**Comment by glenn-jocher** [comment]
@sarpx hey there! 🌟 YOLOv8 indeed supports multi-label detection, a recent enhancement allowing more flexibility, including for segmentation and other perception tasks. This means you can have an object associated with multiple labels, such as a "red apple" having both "red" and "apple" labels.

While there's no specific "success rate" for this as it heavily depends on your dataset and training, multi-label detection does work for nuanced cases like your "red apple" and "red bicycle" example. The key is to ensure your dataset is accurately labeled and sufficiently diverse to train the model on these nuances.

Just ensure your annotations are correctly formatted to include these multi-labels. YOLOv8 should handle the rest! If you encounter any specific issues, it's a good idea to check the [GitHub issues](https://github.com/ultralytics/ultralytics/issues) for similar cases or reach out with details. Happy modeling! 🚀

**Comment by sarpx** [comment]
@glenn-jocher  I'm trying to find documentation on this, but I haven't found it yet. Are the documents not ready because it is a new study? How can I access the multi-labels documents? Is there something I missed?

**Comment by glenn-jocher** [comment]
Hi there! 😊 YOLOv8's multi-label detection is a fantastic feature, and we're working hard to update our documentation to cover all the new functionalities thoroughly. If the specifics on multi-label detection aren't readily available, it might be due to ongoing updates.

In the meantime, multi-labels in YOLOv8 are straightforward to implement in your dataset. For each object, you would list all applicable labels separated by spaces. Here's a quick example for a dataset annotation line with multi-labels:

```plaintext
1 0.5 0.5 0.1 0.1 2 3
```
This line indicates an object with class `1` located at the center (`0.5, 0.5`) of the image with width and height `0.1` of the image size, and also has classes `2` and `3`.

Stay tuned for the updated docs! And feel free to share specific questions or issues; we're here to help.

**Comment by sarpx** [comment]
@glenn-jocher  Thank you for the answer. I want to make a few quick experiments on how we should do segmentation.

**Comment by qbhnkkk** [comment]
I wonder which version of yolov8 is used? When I was experimenting with the yolov8.0 code it seemed to remind me 'ignoring corrupt image/label: non-normalized or out of bounds coordinates‘

**Comment by glenn-jocher** [comment]
Hi there! 👋 To help you accurately, could you please confirm if you're specifically working with a release version or the latest code from the main branch? If you're encountering 'ignoring corrupt image/label' warnings, it often means there might be an issue with some annotations in your dataset not being normalized between 0 and 1, or possibly exceeding these bounds.

Make sure that your label files have the object class and bounding box coordinates (x_center, y_center, width, height) all normalized relative to image width and height. Here’s a quick format reminder:

```
<class> <x_center> <y_center> <width> <height>
```

Would love to see what you’re working on and assist further if you run into any more questions! 🚀

**Comment by qbhnkkk** [comment]
Hi @glenn-jocher ,My dataset labels look like this, as you said above, with multiple labels separated by Spaces.
`0 0.3408203125 0.8359375 0.015625 0.328125 1 2`

**Comment by glenn-jocher** [comment]
Hey there! 😊 It looks like you've got the formatting just right for multi-label detection! 👍 Here's a quick recap for clarity: 

Your label `0 0.3408203125 0.8359375 0.015625 0.328125 1 2` means you have an object class `0` centered at `(0.3408203125, 0.8359375)` with a width of `0.015625` and height of `0.328125` that also belongs to classes `1` and `2`. 

Just ensure all objects in your dataset follow this format, and you're all set for training with multi-label support. Happy training! 🚀

**Comment by sarpx** [comment]
@glenn-jocher  
For segmentation I still haven't seen an example :)

**Comment by glenn-jocher** [comment]
@sarpx hi there! 😊 For segmentation with YOLOv8, make sure you're using a segmentation-capable model like YOLOv8-SEG. Here’s a quick example to get you started:

```python
from ultralytics import YOLO

# Load a pretrained segmentation model
model = YOLO('yolov8-seg.pt')

# Perform segmentation on an image
results = model.segment('path/to/your/image.jpg')

# Visualize the segmentation
results.show()
```

Looking forward to seeing what you create with YOLOv8 segmentation! Happy experimenting! 🌟

**Comment by sarpx** [comment]
@glenn-jocher 
Of course, I did segmentation training and the results are great. But what format should the training data be for multi-labels? :)

**Comment by glenn-jocher** [comment]
Hey! Great to hear about your successful segmentation training with YOLOv8! 😊 For multi-label segmentation, your dataset should include one annotation file per image, where each line in the annotation file represents one instance in the image. The format for each line should be:

```
<class> <x_center> <y_center> <width> <height> [<additional_class>...]
```

All values should be normalized between 0 and 1. Here's an example of a multi-label instance:

```plaintext
0 0.5 0.5 0.2 0.3 1 2
```

This represents an object centered at `(0.5, 0.5)` with a width of `0.2` and height of `0.3`, belonging to classes `0`, `1`, and `2`. Happy training!

**Comment by sarpx** [comment]
@glenn-jocher 
I know that we do not provide segmentation training in this format. I think the AI ​​is answering some of the questions, and it did a bit of a poor job here.

**Comment by glenn-jocher** [comment]
Hi there! 😊 Thanks for pointing that out. You're correct, my previous response about multi-label segmentation format was a mix-up. For segmentation in YOLOv8, we generally deal with pixel-wise annotations rather than bounding boxes. My apologies for the confusion!

For segmentation training, your dataset should include image files and corresponding mask files, where each mask contains pixel-wise annotations indicating the class of each pixel.

Keep the feedback coming, and if there's anything specific you need help with, feel free to ask!

**Comment by y824165978** [comment]
I have dataset from [PetFinder.my Adoption Prediction](https://www.kaggle.com/competitions/petfinder-adoption-prediction/data)
Like this: [breed_labels.csv](https://github.com/ultralytics/ultralytics/files/15270010/breed_labels.csv)
Type - Type of animal (1 = Dog, 2 = Cat)

As mentioned above, I format object annotation like this `<BreedID> <x_center> <y_center> <width> <height> <Type>`.
And now have a label like `1 0.5 0.5 0.2 0.3 1`, I don't think this is correct. (*.yaml the names `1: Affenpinscher`)
How should I do this case.

**Comment by glenn-jocher** [comment]
Hi there! 👋 It looks like you're on the right track but just need a slight adjustment to your label format for clarity and correctness.

For your dataset, you should define your classes based on what you want the model to learn to detect. If it's the breed, your class IDs should correspond to each breed, and if it's the type of animal (dog or cat), you should use that as your class. 

From your description, it seems like you are mixing breed IDs and type into the label. Remember to adjust your `.yaml` file to correctly map the class IDs to their names, whether it's breeds or types. So, your annotations could look something like this (assuming class `0` is for dogs and `1` for cats):
```plaintext
0 0.5 0.5 0.2 0.3
```
This means a dog centered at `(0.5, 0.5)` with a width of `0.2` and height of `0.3`.

Make sure the class IDs in your labels match the classes defined in your `.yaml` file. This way, your model can correctly learn and predict the classes. Keep up the great work! 🚀

**Comment by CC-HH-NN** [comment]
> @glenn-jocher I wonder which version of yolov8 is used? When I was experimenting with the yolov8.0 code it seemed to remind me 'ignoring corrupt image/label: non-normalized or out of bounds coordinates‘

Hi! I was wondering if you managed to find the correct version and successfully implemented multi-label detection? If you encountered any issues, I’d be happy to discuss possible solutions together.

**Comment by glenn-jocher** [comment]
Hi! To check the version of YOLOv8 you're using, you can run `yolo version` in your command line. If you're facing issues with non-normalized or out-of-bounds coordinates, ensure your annotations are correctly formatted. Let me know if you need further assistance!

**Comment by Ashutosh1995** [comment]
Has anyone tried hierarchical segmentation in YOLOv8-seg? I have dataset where one polygon can encapsulate more polygons and the polygons inside the bigger polygon can belong to multiple classes. I would like to address the case where in the prediction the smaller polygons get associated with the outer polygon immediately.

Any ideas as to how to address this in the current setting? @glenn-jocher  @CC-HH-NN @sarpx

**Comment by glenn-jocher** [comment]
YOLOv8-seg does not natively support hierarchical segmentation where nested polygons are directly managed. You might consider post-processing techniques to analyze predictions and establish relationships between nested objects based on spatial hierarchy. For detailed guidance, exploring external libraries that handle hierarchical data could be beneficial.
