### ISSUE TITLE
How to remove P3 in YOLOv8

### ISSUE THREAD

**Issue by trangterra** [ultralytics/ultralytics#10235]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to optimize the YOLOv8 model. So I want to remove the P3 part in YOLOv8. I did it as follows,
![image](https://github.com/ultralytics/ultralytics/assets/123054626/a7694118-4134-4bd0-aef6-f88e0347167d)
 but after retraining the model, I encountered this error.
![image](https://github.com/ultralytics/ultralytics/assets/123054626/0dfc76bd-df94-4d02-ad9d-22809889dd15)

**Comment by Kayzwer** [comment]
@trangterra there are some blocks in head refer to the blocks that you removed, thats why the output shape is not compatible for the layers
