### ISSUE TITLE
Yolov8 - TensorRT performance 

### ISSUE THREAD

**Issue by KevsernurE** [ultralytics/ultralytics#1023]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I've just started using Yolov8, before that i was using Yolov5. I compared the speed of this two versions. I used Yolov5m and Yolov8s, I converted these to TensorRT half. Yolov5's speed increased by more than x2 but Yolov8's speed increased only for x1.5. Is there a reason for this low increase? And also is there any way I can make it faster on GPU?

**Comment by triple-Mu** [comment]
If you want to speed up by tensorrt, you can try https://github.com/triple-Mu/YOLOv8-TensorRT.
It contains python/c++ detection or segment inference demo.
It also has end2end method for detection, simple method for segment.

**Comment by triple-Mu** [comment]
> Thank you for your help. I've tried your codes and I get faster fps. I neet to make it predict given frames list, not one frame at a time. In standart yolo code i used something like 'results = model(frames)', can I do that in infer-det.py?

Sure you can save every frame in a list, and then:
``` python
for frame in frame_lists:
    tensor = process_to_torch_tensor(frame)
    data = Engine(tensor)
    ...
```

**Comment by KevsernurE** [comment]
> > Thank you for your help. I've tried your codes and I get faster fps. I neet to make it predict given frames list, not one frame at a time. In standart yolo code i used something like 'results = model(frames)', can I do that in infer-det.py?
> 
> Sure you can save every frame in a list, and then:
> 
> ```python
> for frame in frame_lists:
>     tensor = process_to_torch_tensor(frame)
>     data = Engine(tensor)
>     ...
> ```

Well I need more like batching the frames and make a prediction at the same time. Like above:
```
frames = [frame1, frame2]
tensor = process_to_torch_tensor(frames)
data = Engine(tensor)
```
or 
```
tensor1 = process_to_torch_tensor(frame1)
tensor2 = process_to_torch_tensor(frame2)
tensors = [tensor1, tensor2]
data = Engine(tensors)
``` 
Can I do something like this? Also thank you for your attention.

**Comment by triple-Mu** [comment]
> > > Thank you for your help. I've tried your codes and I get faster fps. I neet to make it predict given frames list, not one frame at a time. In standart yolo code i used something like 'results = model(frames)', can I do that in infer-det.py?
> 
> > 
> 
> > Sure you can save every frame in a list, and then:
> 
> > 
> 
> > ```python
> 
> > for frame in frame_lists:
> 
> >     tensor = process_to_torch_tensor(frame)
> 
> >     data = Engine(tensor)
> 
> >     ...
> 
> > ```
> 
> 
> 
> Well I need more like batching the frames and make a prediction at the same time. Like above:
> 
> ```
> 
> frames = [frame1, frame2]
> 
> tensor = process_to_torch_tensor(frames)
> 
> data = Engine(tensor)
> 
> ```
> 
> or 
> 
> ```
> 
> tensor1 = process_to_torch_tensor(frame1)
> 
> tensor2 = process_to_torch_tensor(frame2)
> 
> tensors = [tensor1, tensor2]
> 
> data = Engine(tensors)
> 
> ``` 
> 
> Can I do something like this? Also thank you for your attention. 

Got it.
You can export onnx with dynamic batch. 
There will be a difference about preprocess and postprocess. You need to concat all images as a batch. And split batch outputs to every images.

**Comment by KevsernurE** [comment]
Is there something like a documentation or example codes you can recommend about batching?

**Comment by pderrenger** [comment]
@KevsernurE for batching with YOLOv8, you can refer to the YOLOv8 documentation on how to **[export](https://docs.ultralytics.com/modes/export)** a model to a deployment-ready format, as it allows for exporting ONNX models with dynamic batch sizes, suitable for batch processing multiple images at a time.

You can also check out the Ultralytics' **[TensorRT repository](https://github.com/ultralytics/yolov5/issues)** for further guidance and example codes specifically tailored to YOLOv8 and TensorRT integration. This will provide you with detailed technical insights and practical implementation examples for performing batched inference with YOLOv8.

Feel free to reach out if you have any more questions or need additional assistance. Happy coding!
