### ISSUE TITLE
convtranspose2d out of memory.

### ISSUE THREAD

**Issue by N0lanakis** [ultralytics/ultralytics#10233]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hey,

when i use in yolov8.yaml the layers [-1, 1, nn.ConvTranspose2d, [512,512,2,2,0]] the output says that i am out of memory.
![εικόνα](https://github.com/ultralytics/ultralytics/assets/166864880/a98388d0-0d4a-4691-8c50-e4f5a2af8343)

RuntimeError: [enforce fail at alloc_cpu.cpp:117] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 274877906944 bytes. Error code 12 (Cannot allocate memory)

when i use  [-1, 1, nn.ConvTranspose2d, [512,2,2,0]] it works and when the model prints it structure in the terminal via training it says
![εικόνα](https://github.com/ultralytics/ultralytics/assets/166864880/b5cc1693-d983-4505-a270-90fab3ca9b4b)

What is happened here?

Thanks,

**Comment by Kayzwer** [comment]
@N0lanakis well, thats a lot, and thats why you run out of memory

**Comment by N0lanakis** [comment]
@Kayzwer As you can see when i define only the input channels to 512 it automatically set output channels to 512.

Why it cannot accept it from the beginning?

**Comment by glenn-jocher** [comment]
@N0lanakis hey there! 🌟 Yes, using `[-1, 1, nn.ConvTranspose2d, [512,2,2,0]]` as your arguments should work just fine for your case. It looks like the model is able to understand and set the appropriate number of output channels based on your input, bypassing the memory issue you encountered earlier. If it trains well and you're not seeing any errors or unexpected behavior, then you're good to go! Happy training!
