### ISSUE TITLE
Put txt file image path and label path into yolov8 traning

### ISSUE THREAD

**Issue by aTunass** [ultralytics/ultralytics#10249]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I have a question about putting the txt file to yaml in training
My Image folderand label collection are in two completely different folders. I want to pass image paths from txt file to the file_yaml and refer to Coco-pose file_yaml. However, I have not seen any examples of passing the path of the label. Is this possible and how can it be done?

**Comment by aTunass** [comment]
Let me update the question
My current problem is that I have two sets of images belonging to two different data sets. Each photo set has a different labeling style and is saved into 2 folders label1 and label2 for each photo set. I found a way to modify the names of labels in ultralytics/data/utils.py:
![image](https://github.com/ultralytics/ultralytics/assets/119738823/a2fc40d8-863c-4571-ab24-ee1ea3e595b7)
so I was able to train more conveniently. However, when I take the image paths from these two folder to the txt file and pass it to the yaml file:
**txt file**
_/AIHCM/FileShare/Public-AI/Public/AI_Member/team_data/CV/DeepFashion2/validation/images/000001.jpg
/AIHCM/FileShare/Public-AI/Public/AI_Member/team_data/CV/Open_images_v7/train/data/images/000002b66c9c498e.jpg_
**yaml file**
_path:  # dataset root dir
train: /AIHCM/AI_Member/workspace/tuannha/yolov8/config/DFV2pathtxt/train_image_DFV2_abs_path.txt # train images (relative to 'path') 1743042 images
val: /AIHCM/AI_Member/workspace/tuannha/yolov8/config/DFV2pathtxt/validation_image_DFV2_abs_path_sub.txt # val images (relative to 'path') 41620 images
test:_
then when I try to train or validate, the program crashes and pauses there. Can you explain it to me?

**Comment by aTunass** [comment]
Thanks for your quick response, the example you gave is great and I am now able to handle the problem. However, I still have some issues that need to be clarified:
1. If I use the method you suggested, I can put the label folder at any top, it doesn't need to be in the same folder as the images, right?
2. If I have 2 different label folders, will 2 label.cache files be created?

**Comment by aTunass** [comment]
Thanks for the feedback, I appreciate the enthusiastic support

**Comment by glenn-jocher** [comment]
@aTunass you're welcome! We're here to help. If you have more questions or need further assistance, don't hesitate to reach out. Happy coding! 😊
