### ISSUE TITLE
Conversion of dataset from coco json format to yolo pose format

### ISSUE THREAD

**Issue by Habib0905** [ultralytics/ultralytics#10246]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am working on car pose estimation and the dataset is in coco json format. However i need to convert it to yolo pose format.  I used this below script to convert my data to yolo format.
----------------------------------------------------------------------------------------------------------------------------------
import argparse
import json
import os
from pathlib import Path
import numpy as np

parser = argparse.ArgumentParser()

# Number of keypoints for car pose estimation
numOfKpts = 14  # Update this with the number of keypoints in your dataset

parser.add_argument(
    "--coco_json_path",
    default="G:/Desktop/root/Annotations/COCO/car_keypoints_train.json",
    type=str,
    help="Input: COCO format JSON file containing car pose annotations",
)

parser.add_argument(
    "--yolo_save_root_dir",
    default="G:/Desktop/root/Annotations/YOLO/labels/train",
    type=str,
    help="Specify where to save the output directory of labels in YOLO pose format",
)

def convert_keypoints_to_list(keypoints, img_width, img_height):
    min_x = min(keypoints[i] for i in range(0, len(keypoints), 3))
    min_y = min(keypoints[i + 1] for i in range(0, len(keypoints), 3))

    keypoints_list = []
    for i in range(0, len(keypoints), 3):
        x, y, v = keypoints[i], keypoints[i + 1], keypoints[i + 2]
        x_adjusted = max(x + abs(min_x), 0)
        y_adjusted = max(y + abs(min_y), 0)
        x_normalized = x_adjusted / img_width
        y_normalized = y_adjusted / img_height
        keypoints_list.extend([x_normalized, y_normalized, v])
    return keypoints_list

def main(json_file, yolo_save_root_dir):
    os.makedirs(yolo_save_root_dir, exist_ok=True)

    data = json.load(open(json_file, "r"))

    id_map = {}  # Remap category IDs if necessary

    for category in data["categories"]:
        id_map[category["id"]] = len(id_map)

    images = {image["id"]: image for image in data["images"]}
    annotations_by_image_id = {}

    for annotation in data["annotations"]:
        image_id = annotation["image_id"]
        if image_id not in annotations_by_image_id:
            annotations_by_image_id[image_id] = []
        annotations_by_image_id[image_id].append(annotation)

    for image_id, annotations in annotations_by_image_id.items():
        image_info = images[image_id]
        img_filename = image_info["file_name"]
        img_width, img_height = image_info["width"], image_info["height"]

        with open(os.path.join(yolo_save_root_dir, f"{image_id}.txt"), "w") as label_file:
            for annotation in annotations:
                bbox = annotation["bbox"]
                x, y, w, h = bbox[0] / img_width, bbox[1] / img_height, bbox[2] / img_width, bbox[3] / img_height

                keypoints = annotation.get("keypoints", [])  # Get keypoints or empty list if not present
                if len(keypoints) != numOfKpts * 3:  # Ensure correct number of keypoints
                    print(f"Warning: Incorrect number of keypoints for image {image_id}")
                    continue

                keypoints_list = convert_keypoints_to_list(keypoints, img_width, img_height)

                cls = id_map.get(annotation["category_id"], -1)  # Get class index or -1 if not found
                if cls == -1:
                    print(f"Warning: Category ID not found for annotation in image {image_id}")
                    continue

                line = f"{cls} {x} {y} {w} {h} {' '.join(map(str, keypoints_list))}\n"
                label_file.write(line)

if __name__ == "__main__":
    args = parser.parse_args()
    main(args.coco_json_path, args.yolo_save_root_dir)
----------------------------------------------------------------------------------------------------------------------------

After converting my dataset using the above script, I tried to train the yolo pose model with it. However I am running into some Value Error. I think my converted yolo text files has some issues. But visually it complies with the yolo pose dataset format. So i suspect the above script has some issues. Please guide me on this. Do provide any available script which i can use. I have also provided the error messages i have come across during training below.

----------------------------------------------------------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)
[<ipython-input-4-e59c60531ce2>](https://localhost:8080/#) in <cell line: 7>()
      5 model = YOLO('yolov8s-pose.pt')
      6 
----> 7 model.train(data = '/content/gdrive/My Drive/car_pose/config.yaml', epochs =1, imgsz = 640)

9 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py](https://localhost:8080/#) in train(self, trainer, **kwargs)
    671 
    672         self.trainer.hub_session = self.session  # attach optional HUB session
--> 673         self.trainer.train()
    674         # Update model and cfg after training
    675         if RANK in {-1, 0}:

[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py](https://localhost:8080/#) in train(self)
    197 
    198         else:
--> 199             self._do_train(world_size)
    200 
    201     def _setup_scheduler(self):

[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py](https://localhost:8080/#) in _do_train(self, world_size)
    311         if world_size > 1:
    312             self._setup_ddp(world_size)
--> 313         self._setup_train(world_size)
    314 
    315         nb = len(self.train_loader)  # number of batches

[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py](https://localhost:8080/#) in _setup_train(self, world_size)
    275         # Dataloaders
    276         batch_size = self.batch_size // max(world_size, 1)
--> 277         self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode="train")
    278         if RANK in {-1, 0}:
    279             # Note: When training DOTA dataset, double batch size could get OOM on images with >2000 objects.

[/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/detect/train.py](https://localhost:8080/#) in get_dataloader(self, dataset_path, batch_size, rank, mode)
     47         assert mode in {"train", "val"}, f"Mode must be 'train' or 'val', not {mode}."
     48         with torch_distributed_zero_first(rank):  # init dataset *.cache only once if DDP
---> 49             dataset = self.build_dataset(dataset_path, mode, batch_size)
     50         shuffle = mode == "train"
     51         if getattr(dataset, "rect", False) and shuffle:

[/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/detect/train.py](https://localhost:8080/#) in build_dataset(self, img_path, mode, batch)
     41         """
     42         gs = max(int(de_parallel(self.model).stride.max() if self.model else 0), 32)
---> 43         return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == "val", stride=gs)
     44 
     45     def get_dataloader(self, dataset_path, batch_size=16, rank=0, mode="train"):

[/usr/local/lib/python3.10/dist-packages/ultralytics/data/build.py](https://localhost:8080/#) in build_yolo_dataset(cfg, img_path, batch, data, mode, rect, stride, multi_modal)
     87     """Build YOLO Dataset."""
     88     dataset = YOLOMultiModalDataset if multi_modal else YOLODataset
---> 89     return dataset(
     90         img_path=img_path,
     91         imgsz=cfg.imgsz,

[/usr/local/lib/python3.10/dist-packages/ultralytics/data/dataset.py](https://localhost:8080/#) in __init__(self, data, task, *args, **kwargs)
     62         self.data = data
     63         assert not (self.use_segments and self.use_keypoints), "Can not use both segments and keypoints."
---> 64         super().__init__(*args, **kwargs)
     65 
     66     def cache_labels(self, path=Path("./labels.cache")):

[/usr/local/lib/python3.10/dist-packages/ultralytics/data/base.py](https://localhost:8080/#) in __init__(self, img_path, imgsz, cache, augment, hyp, prefix, rect, batch_size, stride, pad, single_cls, classes, fraction)
     73         self.fraction = fraction
     74         self.im_files = self.get_img_files(self.img_path)
---> 75         self.labels = self.get_labels()
     76         self.update_labels(include_class=classes)  # single_cls and include_class
     77         self.ni = len(self.labels)  # number of images

[/usr/local/lib/python3.10/dist-packages/ultralytics/data/dataset.py](https://localhost:8080/#) in get_labels(self)
    159         # Check if the dataset is all boxes or all segments
    160         lengths = ((len(lb["cls"]), len(lb["bboxes"]), len(lb["segments"])) for lb in labels)
--> 161         len_cls, len_boxes, len_segments = (sum(x) for x in zip(*lengths))
    162         if len_segments and len_boxes != len_segments:
    163             LOGGER.warning(

ValueError: not enough values to unpack (expected 3, got 0)

**Comment by glenn-jocher** [comment]
Hello! It seems like there might be an issue with how the keypoints are being converted or read during training. To ensure compatibility with YOLOv8's pose estimation format, each keypoint needs to be normalized and properly aligned with the corresponding bounding box coordinates in the label files.

Here's a quick check you can do:
1. Ensure each label file (`*.txt` in your `--yolo_save_root_dir`) has lines in the format: `class x_center y_center width height keypoints`, where `keypoints` are `x, y, visibility` for each keypoint normalized by the image width and height.
2. Verify if there's an equal number of keypoints for each annotation as expected by your model.

Since you've already taken a good step by converting COCO JSON format to YOLO format, I recommend double-checking the output label files for any discrepancies in the expected format.

If you continue to face issues, feel free to share a few lines from your converted `.txt` files or any specific error messages seen during the conversion process. This might help pinpoint the problem. 👀

In the meantime, here's a simplified snippet to ensure keypoints conversion aligns with YOLOv8 pose format expectations:

```python
def convert_keypoints_to_list(keypoints, img_width, img_height):
    keypoints_list = []
    for i in range(0, len(keypoints), 3):
        x, y, v = keypoints[i:i+3]
        x_normalized = x / img_width
        y_normalized = y / img_height
        keypoints_list.extend([x_normalized, y_normalized, v])
    return keypoints_list
```

This snippet optimizes the normalization process, ensuring all keypoints are correctly scaled down to the `[0, 1]` range according to image dimensions.

If this doesn't solve your issue, please share more details or reach out again! Happy to help further. 🚗💨

**Comment by Habib0905** [comment]
1) In my coco json file there are some keypoint values which are negative. However during conversion of it to the yolo format I made sure to normalize it between 0 and 1. Can it be the source of the issue?  
2) I have provided a snippet of the coco json file of a single image and its corresponding yolo text file. Can you tell me what is the issue in my yolo text file.
3) I would appreciate if you provide a script to convert coco json format to yolo format.

The following is the snippet of the text file in coco json format:
{"image_id": 101100001, "category_id": 1, "iscrowd": 0, "id": 0, "area": 235572, "bbox": [806, 497, 879, 268], "num_keypoints": 12, "keypoints": [913, 708, 1, 989, 734, 1, 1395, 689, 1, 1474, 715, 2, 877, 642, 1, 894, 665, 1, 1524, 604, 1, 1581, 599, 2, 0, 0, 0, 1152, 532, 1, 1190, 539, 2, 1340, 519, 1, 1405, 527, 2, 0, 0, 0], "segmentation": [[1340, 519, 1152, 532, 877, 642, 913, 708, 989, 734, 1474, 715, 1581, 599, 1405, 527]]}, 
{"image_id": 101100001, "category_id": 1, "iscrowd": 0, "id": 1, "area": 657150, "bbox": [316, 405, 975, 674], "num_keypoints": 6, "keypoints": [894, 1070, 2, 959, 945, 1, -250, 1090, 0, -148, 1001, 0, 1174, 866, 2, 1130, 754, 1, -456, 862, 0, -339, 819, 0, 0, 0, 0, 394, 476, 2, 459, 466, 2, -136, 444, 0, -29, 434, 0, 0, 0, 0], "segmentation": [[459, 466, 394, 476, 894, 1070, 1174, 866, 1130, 754]]}

The following is the yolo text file of the above mentioned image:
0 0.4197916666666667 0.4601851851851852 0.4578125 0.24814814814814815 0.47552083333333334 0.6555555555555556 1 0.5151041666666667 0.6796296296296296 1 0.7265625 0.637962962962963 1 0.7677083333333333 0.6620370370370371 2 0.45677083333333335 0.5944444444444444 1 0.465625 0.6157407407407407 1 0.79375 0.5592592592592592 1 0.8234375 0.5546296296296296 2 0.0 0.0 0 0.6 0.4925925925925926 1 0.6197916666666666 0.49907407407407406 2 0.6979166666666666 0.48055555555555557 1 0.7317708333333334 0.487962962962963 2 0.0 0.0 0

0 0.16458333333333333 0.375 0.5078125 0.6240740740740741 0.703125 0.9907407407407407 2 0.7369791666666666 0.875 1 0.10729166666666666 1.0092592592592593 0 0.16041666666666668 0.9268518518518518 0 0.8489583333333334 0.8018518518518518 2 0.8260416666666667 0.6981481481481482 1 0.0 0.7981481481481482 0 0.0609375 0.7583333333333333 0 0.2375 0.0 0 0.4427083333333333 0.44074074074074077 2 0.4765625 0.43148148148148147 2 0.16666666666666666 0.4111111111111111 0 0.22239583333333332 0.40185185185185185 0 0.2375 0.0 0

**Comment by glenn-jocher** [comment]
@Habib0905 hey there! Thanks for sharing your process and details 🚗. Let's tackle your questions one by one:

1) **Negative Keypoints Values in COCO JSON**: Yes, negative values could potentially lead to issues if they aren't handled properly during conversion. For keypoints, ensure they're normalized only if they're visible (`v > 0`). Invisible or missing keypoints (`v=0`) typically don't need adjusting since they don't contribute to the final keypoint representation.

2) **Issue in YOLO Text File**: From your YOLO text files, it seems the format aligns with the expectations, containing a class ID followed by normalized bounding box and keypoint coordinates. However, an ideal YOLO pose file should not contain keypoints with `0.0` values unless they're intentionally marking invisible points. If your COCO JSON contains negative coordinates for some keypoints, consider setting the visibility flag (`v`) to `0` instead of attempting to normalize these values.

3) **Conversion Script**: The script you've provided generally follows the right approach for converting COCO keypoints to YOLO format. To handle negative keypoints specifically, you might need to introduce a check before normalization:
   - If a keypoint is negative or falls outside the image bounds, you could set its visibility flag to `0` and avoid writing coordinates to the YOLO label file.

The critical part is ensuring each keypoint is correctly normalized based on the image dimensions and omitting or flagging keypoints not usable (due to negative values or being outside the image boundaries). 

For pose estimation, proper handling of visibility flags (`v`) is also essential. If keypoints are not visible or outside the expected range, setting visibility to `0` typically indicates that to the model without having to normalize or adjust their coordinates.

Hope this helps clarify! If there's any further detail required or a snippet, let me know. Happy coding! 🚀

**Comment by Habib0905** [comment]
I was able to solve the issue. Thanks a lot to you.

**Comment by Gnoot01** [comment]
> * **Issue in YOLO Text File**: From your YOLO text files, it seems the format aligns with the expectations, containing a class ID followed by normalized bounding box and keypoint coordinates. However, an ideal YOLO pose file should not contain keypoints with `0.0` values unless they're intentionally marking invisible points. If your COCO JSON contains negative coordinates for some keypoints, consider setting the visibility flag (`v`) to `0` instead of attempting to normalize these values.
> * **Conversion Script**: The script you've provided generally follows the right approach for converting COCO keypoints to YOLO format. To handle negative keypoints specifically, you might need to introduce a check before normalization:
>   
>   * If a keypoint is negative or falls outside the image bounds, you could set its visibility flag to `0` and avoid writing coordinates to the YOLO label file.

@glenn-jocher hi, does this mean it would be ... <x_unnormalized or 0> <y_unnormalized or 0> <0> if a point in the coco .json format is 0? is the way I'm understanding it correct? Please refer for more context: https://github.com/ultralytics/JSON2YOLO/issues/109

**Comment by glenn-jocher** [comment]
@Gnoot01 for undetected or unannotated keypoints, set the coordinates to `0` and the visibility flag to `0` in the YOLO format. This indicates the keypoint is not visible or outside the image bounds.
