### ISSUE TITLE
Load stream fails

### ISSUE THREAD

**Issue by pornpra** [ultralytics/ultralytics#10257]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I tested YOLOv8 with multiple streams. One stream is working fine, but another stream is currently offline because the camera is broken. After running the code for inference, I received the following log in my terminal:

![rtsp_error](https://github.com/ultralytics/ultralytics/assets/59501173/b5192d8b-11a5-40f1-8e80-cd8cabc5477a)

and in log file:

**2024-04-23 15:10:37, 191 root ERROR Error reading video frames: 2/2: rtsp://xxxxxxxxxxxxxxxx... Failed to read images from rtsp://xxxxxxxxxxxxxxxx**

Why doesn't YOLOv8 skip the failed stream and continue processing only the available stream? To address this issue, which part of the Ultralytics code needs to be modified? Should I look into the LoadStreams class under loaders.py?

### Environment

Python: 3.8.10
Ultralytics: 8.2.2 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@pornpra hey there! 😊 Thanks for reaching out and providing a detailed description of your issue. 

It looks like you're encountering problems when one of the streams is offline in a multi-stream setup. Currently, YOLOv8 tries to process all provided streams, and if any of them is not available, it could indeed lead to such errors.

A potential workaround is to individually check the availability of each stream before passing them to the model for inference. You could use a simple pre-check function for each RTSP stream. Here's a rough idea:

```python
import cv2

def check_stream(url):
    cap = cv2.VideoCapture(url)
    ret, frame = cap.read()
    cap.release()
    return ret

# Example usage
stream_urls = ["rtsp://stream1", "rtsp://stream2"] # Your streams
active_streams = [url for url in stream_urls if check_stream(url)]

# Then pass `active_streams` to your YOLOv8 inference code
```

This method ensures that only active (available) streams are processed, and offline ones are skipped gracefully.

As for modifying the Ultralytics code, your instinct is correct! `LoadStreams` class under `loaders.py` is where the streams are managed. Implementing a check there, similar to the one above, could automate the process within the YOLOv8 pipeline. However, this might require a bit of tweaking to integrate smoothly.

Hope this helps! If you're comfortable with it, contributions for handling such cases more gracefully in the future are always welcome. 🌟

**Comment by pornpra** [comment]
Thanks for your answer.

Based on your suggestions, do you mean that I can pass active_streams (a list that collects only active streams) to the source argument like this:

results = vehicle_detection.track(**source=active_streams**, device=device, stream=True, tream_buffer=True, tracker=byte_track)

Am I correct ?

**Comment by glenn-jocher** [comment]
@pornpra yes, exactly! You can pass `active_streams`, your filtered list of streams, to the `source` argument just like you've shown:

```python
results = vehicle_detection.track(source=active_streams, device=device, stream=True, stream_buffer=True, tracker=byte_track)
```
Just ensure that `active_streams` only contains URLs of the streams that are currently active. Your approach looks spot on! 😊
