### ISSUE TITLE
How are Segmentation and Classification data prepared /how does the code know where  and what it is?

### ISSUE THREAD

**Issue by bdv29** [ultralytics/ultralytics#1025]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

So I was able to get yolov8 to train fine for box bounding since it was identical to yolov5
however im not sure how you train this segmentation of classification, the guide is very short and not clear on this. 
is it done the same way where i have a training and val list that points the location of the images and labels?
Im not sure how this works with segmentation since label here would be a file that contains pixel information?

**Comment by glenn-jocher** [comment]
@bdv29 see segmentation and classification docs:

https://docs.ultralytics.com/tasks/segmentation
https://docs.ultralytics.com/tasks/classification

**Comment by patrickwasp** [comment]
This isn't documented as far as I can see. 

Each label is a single text line. The first number is the class ID and the subsequent numbers are pairs of x y coordinates of each vertex in a polygon representing the segmentation. The x y values are normalized to the size of the image so they will all go between 0-1 regardless of pixel dimensions. 

<ClassID> <x1 y1> <x2 y2> ...

The <> are only shown for clarity, the real label does not have them.

**Comment by pderrenger** [comment]
@patrickwasp got it! For segmentation, each label is represented as a single line of text, where the first number is the class ID, and the subsequent numbers are pairs of x, y coordinates of each vertex in a polygon representing the segmentation. These x, y values are normalized to the size of the image, ranging from 0 to 1, irrespective of the pixel dimensions. As for classification, you can refer to the official YOLOv8 documentation for additional details.
