### ISSUE TITLE
How to detect objects with different detection models in one video?

### ISSUE THREAD

**Issue by Easonliuuuuu** [ultralytics/ultralytics#10266]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In [https://docs.ultralytics.com/modes/track/#tracker-selection](url) Streaming for-loop with tracking, I know that I can show the bounding box result on a video file with a detection model,how do I plot the bounding box but this time with two detection models? I have trained a yolov8 detection model for football and a yolov8 detection model for football players.

**Comment by glenn-jocher** [comment]
Hello there!

To detect objects with two detection models in one video, you'll essentially load and use both models sequentially for each frame and then combine the results before plotting or further processing. Here's a quick example to guide you:

```python
import cv2
from ultralytics import YOLO

# Load your trained models
model_football = YOLO('path/to/football_model.pt')
model_players = YOLO('path/to/players_model.pt')

# Open your video
cap = cv2.VideoCapture('path/to/video.mp4')

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Detect footballs
    results_football = model_football(frame)

    # Detect football players
    results_players = model_players(frame)

    # Combine detections (example: plotting all detections together)
    combined_frame = results_football[0].plot()
    combined_frame = results_players[0].plot(img=combined_frame)

    # Show the frame (optional): Hit 'q' to quit the window
    cv2.imshow("Detections", combined_frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
```

Make sure to replace `'path/to/football_model.pt'`, `'path/to/players_model.pt'`, and `'path/to/video.mp4'` with your actual file paths. Good luck and have fun with your object detection project! 😊

**Comment by Easonliuuuuu** [comment]
Thanks for replying such a basic question I asked!

**Comment by glenn-jocher** [comment]
@Easonliuuuuu you're welcome! Don't hesitate to ask any question, big or small. We're here to help. 😊 If you have more questions or need further assistance, just let us know. Happy coding!
