### ISSUE TITLE
I ran this example on Nvidia Jeton nx without any results, and all xywh values were 0.

### ISSUE THREAD

**Issue by zhang7249** [ultralytics/ultralytics#10262]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

examples/YOLOv8-CPP-Inference/main.cpp

I ran this example on Nvidia Jeton nx without any results, and all xywh values were 0.
Opencv: 4.9.0
I downloaded yolov8m. pt from the official website and used the command yolo export model=/ Yolov8m. pt format=onnx dynamic=False converted it to onnx, then modified the path in main.cc, used bus.jpg, ran the demo, and displayed an output. But I printed the log and found that all the output's xywh is 0.
Please help solve it. Thank you very much

### Environment

Ultralytics YOLOv8.2.2 🚀 Python-3.8.10 torch-2.2.1 CPU (ARMv8 Processor rev 0 (v8l))
Setup complete ✅ (6 CPUs, 6.7 GB RAM, 126.3/468.5 GB disk)

OS                  Linux-5.10.104-tegra-aarch64-with-glibc2.29
Environment         Linux
Python              3.8.10
Install             pip
RAM                 6.70 GB
CPU                 ARMv8 Processor rev 0 (v8l)
CUDA                None

matplotlib          ✅ 3.7.5>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 5.3.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.2.1>=1.8.0
torchvision         ✅ 0.17.1>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by VdLMV** [comment]
Your log suggests that you run PyTorch on Orin cpu. I had similar problems caused by output tensor is filled with NaNs and found this [https://forums.developer.nvidia.com/t/nvidia-torch-cuda-produces-only-nan-on-cpu/232798](url) statement from Nvidia Jetson SDK moderator: "Due to limited resources, we will focus on the GPU mode support of the prebuilt PyTorch package". Running PyTorch on Orin gpu works fine for me.

**Comment by glenn-jocher** [comment]
Thanks for sharing your experience! It seems like the issue with getting NaNs in the output tensor when running PyTorch on Orin CPU might indeed stem from the focus on GPU mode support for the prebuilt PyTorch package on Jetson devices, as pointed out in the Nvidia forum. Running your model on Orin's GPU instead of the CPU could potentially resolve this issue. To do this, make sure your environment is set up to utilize CUDA, and adjust your model initialization to ensure it's leveraging the GPU:

```python
# Example of how to use CUDA if available
import torch
from ultralytics import YOLO

device = 'cuda' if torch.cuda.is_available() else 'cpu'
model = YOLO('yolov8n.pt', device=device)  # Replace 'yolov8n.pt' with your model

# Now your model will run on GPU if CUDA is available
```

Would be great to hear if switching to GPU resolves the issue for you as well! 🚀

**Comment by zhang7249** [comment]
> 你好！`xywh`在 Nvidia Jetson NX 上运行示例后，您似乎遇到了值为零的问题。这可能是由于模型转换过程或 CPP 推理代码中处理输出的方式造成的。首先，确保转换为 ONNX`yolo export model=yolov8m.pt format=onnx dynamic=False`成功且没有错误。
> 
> 有时，模型转换的细微差别可能会导致意外的行为。确保模型已正确加载到您的 CPP 推理代码中。验证 C++ 示例中的输入预处理是否与模型的预期相匹配也很有帮助，特别是图像标准化步骤。
> 
> 如果问题仍然存在，请考虑在导出期间使用不同的设置进行测试，或尝试运行简单的 Python 推理脚本来检查模型在 C++ 环境之外的行为是否符合预期`format`。`dynamic`🕵️
> 
> ```c++
> // Example of verifying loaded model in a minimal Python script
> from ultralytics import YOLO
> 
> # Load and test the ONNX model
> model = YOLO('path/to/your/model.onnx', format='onnx')
> results = model.predict('path/to/bus.jpg')
> print(results.boxes)
> ```
> 
> 比较此测试的结果可以帮助缩小问题是否出在模型转换或 C++ 代码上。如果您仍然遇到困难，请考虑分享详细的代码片段或错误日志以获得更有针对性的帮助。 🛠️



> Hello! It looks like you're facing an issue where the `xywh` values are zero after running an example on Nvidia Jetson NX. This could potentially be due to the model conversion process or how the outputs are handled in the CPP inference code. First, ensure the conversion to ONNX with `yolo export model=yolov8m.pt format=onnx dynamic=False` is successful and without errors.
> 
> Sometimes, model conversion nuances can lead to unexpected behaviors. Ensure the model is correctly loaded in your CPP inference code. It's also helpful to verify that the input pre-processing in the C++ example matches what's expected by the model, particularly the image normalization steps.
> 
> If the issue persists, consider testing with a different `format` or `dynamic` setting during the export or try running a simple Python inference script to check if the model behaves as expected outside of the C++ environment. 🕵️
> 
> ```c++
> // Example of verifying loaded model in a minimal Python script
> from ultralytics import YOLO
> 
> # Load and test the ONNX model
> model = YOLO('path/to/your/model.onnx', format='onnx')
> results = model.predict('path/to/bus.jpg')
> print(results.boxes)
> ```
> 
> Comparing results from this test can help narrow down whether the issue lies with the model conversion or the C++ code. If you're continuing to experience difficulties, consider sharing detailed code snippets or error logs for more targeted assistance. 🛠️

----------------------------------------------------------------------------------------------------------------------------------

I ran your code on Jeston and it seems to have the correct result

```
root@nvidia-desktop:~# python3.8
Python 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> from ultralytics import YOLO

>>> 
>>> model = YOLO('/root/esdk_deploy/yolov8/wuliao/yolov8m.onnx', format='onnx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'format'
>>> model = YOLO('/root/esdk_deploy/yolov8/wuliao/yolov8m.onnx')
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify','pose' or 'obb'.
>>> 
>>> 
>>> 
>>> model = YOLO('/root/esdk_deploy/yolov8/wuliao/yolov8m.onnx',task=detect)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'detect' is not defined
>>> model = YOLO('/root/esdk_deploy/yolov8/wuliao/yolov8m.onnx',task='detect')
>>> 
>>> 
>>> 
>>> 
>>> 
>>> results = model.predict('/root/esdk_deploy/yolov8/wuliao/bus.jpg')
Loading /root/esdk_deploy/yolov8/wuliao/yolov8m.onnx for ONNX Runtime inference...
requirements: Ultralytics requirement ['numpy==1.23.5'] not found, attempting AutoUpdate...
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
onnxruntime-gpu 1.16.0 requires numpy>=1.24.4, but you have numpy 1.23.5 which is incompatible.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting numpy==1.23.5
  Downloading https://mirrors.aliyun.com/pypi/packages/bf/d1/1017fe3f5d65c4fe054a793f18f940d913868bb2846a02d3f6244a829a30/numpy-1.23.5-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 1.0 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.4
    Uninstalling numpy-1.24.4:
      Successfully uninstalled numpy-1.24.4
Successfully installed numpy-1.23.5

requirements: AutoUpdate success ✅ 27.9s, installed 1 package: ['numpy==1.23.5']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect


image 1/1 /root/esdk_deploy/yolov8/wuliao/bus.jpg: 640x640 4 persons, 1 bus, 2064.1ms
Speed: 35.6ms preprocess, 2064.1ms inference, 3810.1ms postprocess per image at shape (1, 3, 640, 640)
>>> print(result.boxes)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'result' is not defined
>>> print(results.boxes)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'list' object has no attribute 'boxes'
>>> print(results)
[ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
masks: None
names: {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted plant', 59: 'bed', 60: 'dining table', 61: 'toilet', 62: 'tv', 63: 'laptop', 64: 'mouse', 65: 'remote', 66: 'keyboard', 67: 'cell phone', 68: 'microwave', 69: 'oven', 70: 'toaster', 71: 'sink', 72: 'refrigerator', 73: 'book', 74: 'clock', 75: 'vase', 76: 'scissors', 77: 'teddy bear', 78: 'hair drier', 79: 'toothbrush'}
obb: None
orig_img: array([[[122, 148, 172],
        [120, 146, 170],
        [125, 153, 177],
        ...,
        [157, 170, 184],
        [158, 171, 185],
        [158, 171, 185]],

       [[127, 153, 177],
        [124, 150, 174],
        [127, 155, 179],
        ...,
        [158, 171, 185],
        [159, 172, 186],
        [159, 172, 186]],

       [[128, 154, 178],
        [126, 152, 176],
        [126, 154, 178],
        ...,
        [158, 171, 185],
        [158, 171, 185],
        [158, 171, 185]],

       ...,

       [[185, 185, 191],
        [182, 182, 188],
        [179, 179, 185],
        ...,
        [114, 107, 112],
        [115, 105, 111],
        [116, 106, 112]],

       [[157, 157, 163],
        [180, 180, 186],
        [185, 186, 190],
        ...,
        [107,  97, 103],
        [102,  92,  98],
        [108,  98, 104]],

       [[112, 112, 118],
        [160, 160, 166],
        [169, 170, 174],
        ...,
        [ 99,  89,  95],
        [ 96,  86,  92],
        [102,  92,  98]]], dtype=uint8)
orig_shape: (1080, 810)
path: '/root/esdk_deploy/yolov8/wuliao/bus.jpg'
probs: None
save_dir: 'runs/detect/predict'
speed: {'preprocess': 35.61091423034668, 'inference': 2064.149856567383, 'postprocess': 3810.0733757019043}]
>>> 
>>> 
>>> 

```

**Comment by zhang7249** [comment]
> Your log suggests that you run PyTorch on Orin cpu. I had similar problems caused by output tensor is filled with NaNs and found this [https://forums.developer.nvidia.com/t/nvidia-torch-cuda-produces-only-nan-on-cpu/232798](url) statement from Nvidia Jetson SDK moderator: "Due to limited resources, we will focus on the GPU mode support of the prebuilt PyTorch package". Running PyTorch on Orin gpu works fine for me.

-----------------------------------------

Thank you for your reply. My project is based on C++and is part of the code for modification detection in the esdk_demo provided by DJI. In order to minimize changes, I can only use OpenCV to load the onnx model. Do you mean NVIDIA recommends using PyTorch to load YOLOv8's ONNX model for detection? Does it not support loading OpenCV? Looking forward to your reply, thank you!

**Comment by zhang7249** [comment]
> Thanks for sharing your experience! It seems like the issue with getting NaNs in the output tensor when running PyTorch on Orin CPU might indeed stem from the focus on GPU mode support for the prebuilt PyTorch package on Jetson devices, as pointed out in the Nvidia forum. Running your model on Orin's GPU instead of the CPU could potentially resolve this issue. To do this, make sure your environment is set up to utilize CUDA, and adjust your model initialization to ensure it's leveraging the GPU:
> 
> ```python
> # Example of how to use CUDA if available
> import torch
> from ultralytics import YOLO
> 
> device = 'cuda' if torch.cuda.is_available() else 'cpu'
> model = YOLO('yolov8n.pt', device=device)  # Replace 'yolov8n.pt' with your model
> 
> # Now your model will run on GPU if CUDA is available
> ```
> 
> Would be great to hear if switching to GPU resolves the issue for you as well! 🚀

------------------------------------------------
```
>>> import torch
>>> from ultralytics import YOLO
>>> device = 'cuda' if torch.cuda.is_available() else 'cpu'
>>> print(device);
cpu
```
It seems that there is a problem with my CUDA, but the result shows that it is running on the CPU. Is it a problem with my local environment?

But when I checked Jeston's information through JTOP, it showed that Cuda exists
![image](https://github.com/ultralytics/ultralytics/assets/23712584/448b8e48-a1f0-47d7-ba5f-6438469bc4ae)


I'm a bit confused. Could you please provide me with your professional advice? Thank you very much

**Comment by zhang7249** [comment]
```
opencv version = 4.9.0

Running on CUDA
[DEBUG:0@1.206] global parallel.cpp:107 createDefaultParallelForAPI core(parallel): Initializing parallel backend...
[DEBUG:0@1.206] global registry_parallel.impl.hpp:69 ParallelBackendRegistry core(parallel): Builtin backends(3): ONETBB(1000); TBB(990); OPENMP(980)
[DEBUG:0@1.206] global registry_parallel.impl.hpp:94 ParallelBackendRegistry core(parallel): Available backends(3): ONETBB(1000); TBB(990); OPENMP(980)
[ INFO:0@1.206] global registry_parallel.impl.hpp:96 ParallelBackendRegistry core(parallel): Enabled backends(3, sorted by priority): ONETBB(1000); TBB(990); OPENMP(980)
[DEBUG:0@1.206] global parallel.cpp:65 createParallelForAPI core(parallel): trying backend: ONETBB (priority=1000)
[DEBUG:0@1.206] global plugin_parallel_wrapper.impl.hpp:219 getPluginCandidates core(parallel): ONETBB plugin's glob is 'libopencv_core_parallel_onetbb*.so', 1 location(s)
[DEBUG:0@1.210] global plugin_parallel_wrapper.impl.hpp:229 getPluginCandidates     - /usr/local/opencv44/lib: 0
[DEBUG:0@1.210] global plugin_parallel_wrapper.impl.hpp:233 getPluginCandidates Found 0 plugin(s) for ONETBB
[DEBUG:0@1.210] global parallel.cpp:65 createParallelForAPI core(parallel): trying backend: TBB (priority=990)
[DEBUG:0@1.210] global plugin_parallel_wrapper.impl.hpp:219 getPluginCandidates core(parallel): TBB plugin's glob is 'libopencv_core_parallel_tbb*.so', 1 location(s)
[DEBUG:0@1.213] global plugin_parallel_wrapper.impl.hpp:229 getPluginCandidates     - /usr/local/opencv44/lib: 0
[DEBUG:0@1.213] global plugin_parallel_wrapper.impl.hpp:233 getPluginCandidates Found 0 plugin(s) for TBB
[DEBUG:0@1.213] global parallel.cpp:65 createParallelForAPI core(parallel): trying backend: OPENMP (priority=980)
[DEBUG:0@1.213] global plugin_parallel_wrapper.impl.hpp:219 getPluginCandidates core(parallel): OPENMP plugin's glob is 'libopencv_core_parallel_openmp*.so', 1 location(s)
[DEBUG:0@1.216] global plugin_parallel_wrapper.impl.hpp:229 getPluginCandidates     - /usr/local/opencv44/lib: 0
[DEBUG:0@1.216] global plugin_parallel_wrapper.impl.hpp:233 getPluginCandidates Found 0 plugin(s) for OPENMP
[DEBUG:0@1.216] global parallel.cpp:93 createParallelForAPI core(parallel): fallback on builtin code
[ INFO:0@4.515] global op_cuda.cpp:80 initCUDABackend CUDA backend will fallback to the CPU implementation for the layer "_input" of type __NetInputLayer__

yolov8 = 1
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
x= 0
y= 0
w= 0
h= 0
Number of detections:1

```
This is the log I opened for OpenCV and printed on the console using CUDA. What can I see

**Comment by glenn-jocher** [comment]
Hi there! It looks like you're running into a situation where all detected object dimensions (`xywh`) are returning as `0`. Based on the logs and your debug output, it seems the core issue might be with how the model's outputs are being interpreted or parsed in your environment.

Given you're using OpenCV `4.9.0` for ONNX model inference with CUDA enabled, here are a couple things to consider:

1. **Model Loading:** Ensure the model is loaded correctly without any errors. Pay particular attention to any warnings or errors related to CUDA initialization or model compatibility that might suggest issues with using the GPU.

2. **Preprocessing:** Verify that the input image is properly preprocessed (normalized and resized) similar to how it was during the training phase. Differences in preprocessing can have a significant impact on the model's output.

3. **Library Compatibility:** Although you're focused on using OpenCV due to project constraints, it might be beneficial to test the inference with PyTorch to ensure the model itself is functioning correctly. This could help determine if the issue lies within OpenCV handling or a deeper issue with the model or environment.

    ```cpp
    // Pseudo code for inference check with PyTorch (Python)
    import torch
    model = torch.load('model_path.pt')
    model.eval()
    // Perform inference
    ```

4. **CUDA Check:** Since your device is showing that CUDA exists but PyTorch is falling back to the CPU, there might be an issue with PyTorch's CUDA bindings or its detection of CUDA in your environment. Ensure your PyTorch installation is compatible with CUDA and that CUDA is accessible by PyTorch.

5. **OpenCV Backend:** Even though the log indicates the use of CUDA, it's crucial to ensure that the DNN module is indeed leveraging CUDA for operations. Confirm this by explicitly setting the preferable backend and target as CUDA when using the Net object.

    ```cpp
    net.setPreferableBackend(cv::dnn::DNN_BACKEND_CUDA);
    net.setPreferableTarget(cv::dnn::DNN_TARGET_CUDA);
    ```

Lastly, if after thorough investigation the issue persists, consider reaching out on platforms like NVIDIA's forums or OpenCV's support channels where you might find more specialized assistance related to CUDA and OpenCV's DNN module.

Hope this gives you a good direction to proceed and solve the issue! Keep experimenting and don't hesitate to share any updates or further inquiries.🚀

**Comment by zhang7249** [comment]
Let me ask you another question. If I can't get results with CUDA, but I can see normal results with CPU (there is a box in the picture and there is confidence), does that mean it has nothing to do with YOLOv8, it's a problem with the system environment?
Your answer is very useful to me. If it can be proven that it is not related to YOLOv8, I will post on the NVIDIA forum to inquire. Looking forward to your reply！

**Comment by glenn-jocher** [comment]
@zhang7249 hello! 🌟

Yes, if you're getting correct results on the CPU but encountering issues when using CUDA, it indeed points towards an environment or CUDA setup issue rather than a problem with YOLOv8 itself. YOLOv8 is designed to be hardware agnostic as long as the underlying libraries (like PyTorch or OpenCV) correctly leverage the available hardware. 

I'd recommend ensuring your CUDA, cuDNN, and respective drivers are correctly installed and compatible with your version of PyTorch or OpenCV. Posting on the NVIDIA forum is a good next step since they can offer more tailored advice for environment-specific settings. 

Happy coding, and good luck with your debugging! 👩‍💻🚀
