### ISSUE TITLE
How to save results to my own folder?

### ISSUE THREAD

**Issue by NewerZeus** [ultralytics/ultralytics#10264]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

@glenn-jocher Hi! As the title indicates, when I use `results = model.predict(source='a/path', save=True)` to predict, the  results will be saved in the directory where the image is located. Is there a way to save the results to my own directory?

**Comment by glenn-jocher** [comment]
Hello! 😊 You can easily save the results to your preferred directory by specifying the `project` and `name` arguments in your `predict()` call. Here's a quick example:

```python
results = model.predict(source='a/path', save=True, project='my_directory', name='my_results')
```

This will save the results in `my_directory/my_results`. If the directories don't exist, they'll be created automatically. Happy coding! 🚀

**Comment by glenn-jocher** [comment]
@NewerZeus glad I could help! 😊 Don't worry, mastering all the parameters takes some time, but you're on the right track. If you have any more questions or need examples, feel free to ask. Happy coding! 🚀

**Comment by NewerZeus** [comment]
If I save the predicted images in the way like `results = model.predict(source='a/path', save=True, project='my_directory', name='my_results')`, the predicted images will save in a folder as you say. However, if I only want to save the predicted images to my own folder (don't save as a folder), is there any way to do this?

**Comment by NewerZeus** [comment]
If I save the predicted images in the way like `results = model.predict(source='a/path', save=True, project='my_directory', name='my_results')`, the predicted images will save in a folder as you say. However, if I only want to save the predicted images to my own folder (don't save as a folder), is there any way to do this?

**Comment by glenn-jocher** [comment]
Hello! You can directly specify the exact path and filename for each saved result using the `filename` parameter in your `predict()` method. For example:

```python
results = model.predict(source='a/path', save=True, project='my_directory', name='my_results', filename='my_directory/my_custom_filename.jpg')
```

This command will save the predicted images directly into your specified directory with your chosen filename. Just make sure to handle filename specifications when processing multiple images to avoid overwriting.

**Comment by NewerZeus** [comment]
I want to use the code `model.predict(source=img, save=True, conf=0.01, project='E:/project/blade/my_alo/1',name='1',filename='E:/project/blade/my_alo/1/1.bmp')` to save the predicted image in folder `E:/project/blade/my_alo/1` with name `1.bmp`. But I get an Error `'filename' is not a valid YOLO argument. Similar arguments are i.e. ['name'].` By the way, I am using the YOLOv8.0.72.

**Comment by glenn-jocher** [comment]
Hello! It seems like there was a little confusion with the usage of the `filename` parameter. In YOLOv8, the `filename` argument isn't available directly within the `predict()` method.

However, you can easily save your results in the desired directory by using the `project` and `name` parameters. Here's how you can adjust your code:

```python
results = model.predict(source=img, save=True, conf=0.01, project='E:/project/blade/my_alo/1', name='your_desired_filename_without_extension')
```

This will save the result in `'E:/project/blade/my_alo/1'` with the name you specify plus the appropriate file extension. Just replace `your_desired_filename_without_extension` with the name you want, like `'1'`, and it will save as `1.jpg` or another format depending on the output. Hope this helps! 😊
