### ISSUE TITLE
How can i load data and train it through roboflow APIS

### ISSUE THREAD

**Issue by RosterMouch** [ultralytics/ultralytics#1027]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The question is as title when i spececifed the training code like this:
```python
from ultralytics import YOLO
model = YOLO("yolov8s.pt")
model.train(
    data=dataset.location+"/data.yaml",
    imgsz=640,
    batch=4,
    epochs=100,
)
```
It raised error like below:
```
FileNotFoundError: 
Dataset '/home/elin/model_training/yolov8/ClassAction-1/data.yaml' not found ⚠️, missing paths ['/home/elin/model_training/yolov8/datasets/ClassAction-1/valid/images']
```
But i think that must be have a path called valid in this dataset cause i download it through roboflow APIs directly.
So how should i training yolov8 correctly?

### Additional

Fully reproduce code here:
```python
from roboflow import Roboflow
rf = Roboflow(api_key=input("Please Provide API Key"))
project = rf.workspace("<WorkSpace>").project("<ProjectName>")
dataset = project.version(1).download("yolov8")
import os 
from IPython.display import clear_output
if os.path.exists("ClassAction-1"):  
    clear_output()
    print("Dataset already downloaded")
else:
    clear_output()
    print("Failed to download dataset due to invalid API key or network error")

```

    Dataset already downloaded

```python
from ultralytics import checks
checks()
```

    Ultralytics YOLOv8.0.20 🚀 Python-3.9.13 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 2060, 6144MiB)
    Setup complete ✅ (12 CPUs, 15.5 GB RAM, 137.0/1006.9 GB disk)

```python
from ultralytics import YOLO
model = YOLO("yolov8s.pt")
model.train(
    data=dataset.location+"/data.yaml",
    imgsz=640,
    batch=4,
    epochs=100,
)
```

    Ultralytics YOLOv8.0.20 🚀 Python-3.9.13 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 2060, 6144MiB)
    [34m[1myolo/engine/trainer: [0mtask=detect, mode=train, model=yolov8s.yaml, data=/home/elin/model_training/yolov8/ClassAction-1/data.yaml, epochs=100, patience=50, batch=4, imgsz=640, save=True, cache=False, device=, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=False, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=False, val=True, save_json=False, save_hybrid=False, conf=0.001, iou=0.7, max_det=300, half=False, dnn=False, plots=False, source=ultralytics/assets/, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.001, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, save_dir=runs/detect/train3

    ---------------------------------------------------------------------------

    FileNotFoundError                         Traceback (most recent call last)

    /tmp/ipykernel_1976/1704976871.py in <module>
          1 from ultralytics import YOLO
          2 model = YOLO("yolov8s.pt")
    ----> 3 model.train(
          4     data=dataset.location+"/data.yaml",
          5     imgsz=640,

    ~/anaconda3/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py in train(self, **kwargs)
        201             overrides["resume"] = self.ckpt_path
        202 
    --> 203         self.trainer = self.TrainerClass(overrides=overrides)
        204         if not overrides.get("resume"):  # manually set model only if not resuming
        205             self.trainer.model = self.trainer.get_model(weights=self.model if self.ckpt else None, cfg=self.model.yaml)

    ~/anaconda3/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py in __init__(self, cfg, overrides)
        120         self.data = self.args.data
        121         if self.data.endswith(".yaml"):
    --> 122             self.data = check_det_dataset(self.data)
        123         elif self.args.task == 'classify':
        124             self.data = check_cls_dataset(self.data)

    ~/anaconda3/lib/python3.9/site-packages/ultralytics/yolo/data/utils.py in check_det_dataset(dataset, autodownload)
        235                 LOGGER.warning(msg)
        236             else:
    --> 237                 raise FileNotFoundError(msg)
        238             t = time.time()
        239             if s.startswith('http') and s.endswith('.zip'):  # URL

    FileNotFoundError: 
    Dataset '/home/elin/model_training/yolov8/ClassAction-1/data.yaml' not found ⚠️, missing paths ['/home/elin/model_training/yolov8/datasets/ClassAction-1/valid/images']

```python
!tree -L 2
```

    .
    ├── ClassAction-1
    │   ├── README.dataset.txt
    │   ├── README.roboflow.txt
    │   ├── data.yaml
    │   ├── test
    │   ├── train
    │   └── valid
    ├── runs
    │   └── detect
    ├── train.ipynb
    └── yolov8s.pt
    
    6 directories, 5 files

**Comment by yeldarby** [comment]
Could you see if it’s fixed if you upgrade the version of the `roboflow` package you’re using and re-download the dataset?

We [pushed an update](https://github.com/roboflow/roboflow-python/pull/113) last night to address a change in the `ultralytics` yaml parsing introduced in `0.0.30`. It now dynamically detects the `ultralytics` version and rewrites the yaml to the new format if `>=0.0.30`

**Comment by RosterMouch** [comment]
> Could you see if it’s fixed if you upgrade the version of the `roboflow` package you’re using and re-download the dataset?
> 
> We [pushed an update](https://github.com/roboflow/roboflow-python/pull/113) last night to address a change in the `ultralytics` yaml parsing introduced in `0.0.30`. It now dynamically detects the `ultralytics` version and rewrites the yaml to the new format if `>=0.0.30`

Hi,is that means i need to upgrade the ultralytics package to the latest version and retry?

**Comment by RosterMouch** [comment]
> Could you see if it’s fixed if you upgrade the version of the `roboflow` package you’re using and re-download the dataset?
> 
> We [pushed an update](https://github.com/roboflow/roboflow-python/pull/113) last night to address a change in the `ultralytics` yaml parsing introduced in `0.0.30`. It now dynamically detects the `ultralytics` version and rewrites the yaml to the new format if `>=0.0.30`

Finaly worked with these configurations,ToT : 
![image](https://user-images.githubusercontent.com/75596885/219867261-23d1ff98-e298-480b-a478-52ef8734c82f.png)
![image](https://user-images.githubusercontent.com/75596885/219867281-85781ee6-5434-41c0-8a58-94b24c2ae601.png)

**Comment by RosterMouch** [comment]
Close this issuse since fix that

**Comment by pderrenger** [comment]
@ElinLiu0 i'm glad to hear that the issue has been resolved! If you have any more questions or encounter any further issues, feel free to ask. The Ultralytics community is always here to help!
