### ISSUE TITLE
How to install ultralytics solutions for object distance estimation

### ISSUE THREAD

**Issue by jsaffyvtti** [ultralytics/ultralytics#10278]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm trying to test out to see if I could use the distance estimation for our use case with automotive vehicle tracking.  But I can't get past the import 

from ultralytics.solutions import distance_calculation

but I get:

ModuleNotFoundError: No module named 'ultralytics.solutions'

I can import Yolo and ultralytics just fine but solutions is not available.

I'm running python 3.8 with ultralytics==8.0.207

**Comment by glenn-jocher** [comment]
@jsaffyvtti hello! 🌟

For the object distance estimation feature, ensuring you're using the correct version of the Ultralytics package is crucial. It seems like the feature you're trying to access might not be available in the version (`8.0.207`) you're using.

First, I recommend checking the official Ultralytics GitHub repository for any updates or instructions on accessing the `ultralytics.solutions` module, as this might be a newer addition or require a specific branch.

However, if `distance_calculation` is not directly accessible or provided as a built-in feature in the Ultralytics package you have, you might have to implement the distance estimation logic on top of the object detection results obtained from YOLOv8. This usually involves camera calibration and some geometric computations based on the detected object's dimensions and known real-world measurements.

As an immediate workaround, ensure your Ultralytics package is up to date with the latest version if it's available:

```bash
pip install --upgrade ultralytics
```

If the direct module for `distance_calculation` is still not accessible, consider reaching out on the Ultralytics GitHub Issues or Discussions with your specific use case. The team or community might offer advice or alternative methods for achieving your goals with vehicle tracking and distance estimation.

Keep exploring and happy coding!

**Comment by jsaffyvtti** [comment]
@glenn-jocher Oh wow it was really that simple XD.  Thanks for the help Glenn!
