### ISSUE TITLE
Model tune problem

### ISSUE THREAD

**Issue by TTT52** [ultralytics/ultralytics#10283]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I used tune to tune the parameters, there were two errors that I did not expect, I do not understand why such errors occurred, I can train normally with this data set, This is the location of my data set data_brain_tumor/brain_tumor.yaml This data set is the data provided in the model I downloaded, but it is not normal when it is put into tune. I hope you can help me understand why such errors occur and tell me the solution. The following is the output of the console error message.
C:\Users\ParcelOS\.conda\envs\YOLOV8\python.exe D:\code\YOLOV8_4\ultralytics-main\test.py 
Tuner: Initialized Tuner instance with 'tune_dir=runs\detect\tune27'
Tuner: 💡 Learn about tuning at https://docs.ultralytics.com/guides/hyperparameter-tuning
Tuner: Starting iteration 1/300 with hyperparameters: {'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'box': 7.5, 'cls': 0.5, 'dfl': 1.5, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.3, 'fliplr': 0.5, 'bgr': 0.0, 'mosaic': 1.0, 'mixup': 0.0, 'copy_paste': 0.0}
WARNING ❌️ training failure for hyperparameter tuning iteration 1
[WinError 2] 系统找不到指定的文件。
Saved runs\detect\tune27\tune_scatter_plots.png
Saved runs\detect\tune27\tune_fitness.png
![微信图片_20240424102033](https://github.com/ultralytics/ultralytics/assets/119116322/3c07c27f-dd28-4759-8852-7a119a339291)

**Comment by glenn-jocher** [comment]
Hello! 😊 It looks like you're encountering a "file not found" error (WinError 2) during the hyperparameter tuning process, which suggests the issue might be related to the path or specific files the tuner is trying to access.

A common cause for this type of error could be an incorrect path to your dataset or issues with accessing specific files required for tuning. Could you please verify that the path provided in your `data_brain_tumor/brain_tumor.yaml` file is correct and accessible? Ensure that all paths in your YAML file are correct, especially considering absolute vs. relative paths based on where you execute your tuning script.

```yaml
# Example structure of your dataset YAML file
path: data_brain_tumor  # Ensure this path is correct
train: images/train  # Verify these directories exist and contain your data
val: images/val
test: images/test  # Optional
```

Also, consider running a simple file access test in Python to confirm the accessibility of your dataset path:

```python
import os

# Example to check the existence of your dataset directory
dataset_path = 'path/to/your/data_brain_tumor/brain_tumor.yaml'
print("Dataset path exists:", os.path.exists(dataset_path))
```

If paths and accessibility are confirmed and the issue persists, it may help to review the tuner's log files for more specific error messages that could guide further troubleshooting.

Let us know how it goes, and we'll be here to assist further if needed!

**Comment by yaoergogo** [comment]
> ### 询问后搜索
> * [x] 我搜索了 YOLOv8 [问题](https://github.com/ultralytics/ultralytics/issues)和[讨论](https://github.com/ultralytics/ultralytics/discussions)，没有发现类似的问题。
> 
> ### 问题
> 当我使用 tune 来调整参数时，有两个我没有预料到的错误，我不明白为什么会发生这样的错误，我可以用这个数据集正常训练，这是我的数据集的位置 data_brain_tumor/brain_tumor.yaml 这个数据集是我下载的模型中提供的数据， 但当它被调谐时，这是不正常的。我希望你能帮助我理解为什么会发生这样的错误，并告诉我解决方案。以下是控制台错误消息的输出。 C：\Users\ParcelOS.conda\envs\YOLOV8\python.exe D：\code\YOLOV8_4\ultralytics-main\test.py Tuner：使用“tune_dir=runs\detect\tune27”调谐器初始化的调谐器实例：💡在 https://docs.ultralytics.com/guides/hyperparameter-tuning Tuner 上了解有关调谐的信息：使用超参数开始迭代 1/300：{'lr0'： 0.01， 'lrf'： 0.01， 'momentum'： 0.937， 'weight_decay'： 0.0005， 'warmup_epochs'： 3.0， 'warmup_momentum'： 0.8， 'box'： 7.5， 'cls'： 0.5， 'dfl'： 1.5， 'hsv_h'： 0.015， 'hsv_s'： 0.7， 'hsv_v'： 0.4， 'degrees'： 0.0， 'translate'： 0.1， 'scale'： 0.5， 'shear'： 0.0， 'perspective'： 0.0， 'flipud'： 0.3， 'fliplr'： 0.5， 'bgr'： 0.0， 'mosaic'： 1.0， 'mixup'： 0.0， 'copy_paste'： 0.0} 警告 ❌️ 超参数优化迭代 1 的训练失败 [WinError 2] 系统找不到指定的文件。保存的运行\detect\tune27\tune_scatter_plots.png 保存的运行\detect\tune27\tune_fitness.png ![微信图片_20240424102033](https://private-user-images.githubusercontent.com/119116322/325051599-3c07c27f-dd28-4759-8852-7a119a339291.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNDIxNjksIm5iZiI6MTcxNDA0MTg2OSwicGF0aCI6Ii8xMTkxMTYzMjIvMzI1MDUxNTk5LTNjMDdjMjdmLWRkMjgtNDc1OS04ODUyLTdhMTE5YTMzOTI5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxMDQ0MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWQ0NjAyYmM1ZjA2YmU0NmQ1YWI1MTBmZWMxZmQxMjgwZjM2ZmIwNzEyMGZhNzg0MWRjZDUyNWJjZjJjYWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LKZlH0v_5NupQuxkkjQ_8_lrUcZLbHiYYxRe-XUTou8)
> 
> ### 附加
> _没有回应_

你有解决吗楼主，我也是这样

**Comment by TTT52** [comment]
还没有解决呢，我这两天没去调试，在做另外的东西

**Comment by glenn-jocher** [comment]
@TTT52 hello! 😊 It looks like you're busy with other tasks at the moment. When you get a chance to focus on this issue again, I suggest verifying the dataset's path and ensuring all required files are accessible as mentioned earlier. Sometimes, the devil is in the details with paths and file accessibility. If you encounter any specific errors or need further assistance when you're back on this, please feel free to share more details, and we'll be here to help. Good luck with your current tasks!

**Comment by 8720** [comment]
同样的问题，操作系统是win11+anaconda+py38+torch2.3.1+cu121。
运行官网上的示例:
`from ultralytics import YOLO`
`model = YOLO("yolov8n.pt")`
`result_grid = model.tune(data="coco8.yaml", use_ray=True)`

控制台抛出错误
`FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\username\\AppData\\Local\\Temp\\ray\\session_2024-07-28_13-19-03_079600_32024\\artifacts\\2024-07-28_13-19-07\\_tune_2024-07-28_13-19-07\\driver_artifacts\\_tune_e9ab7_00000_0_bgr=0.5384,box=0.0466,cls=0.8277,copy_paste=0.8218,degrees=26.9491,fliplr=0.9799,flipud=0.9095,hsv_h=0.0197,hs_2024-07-28_13-19-07'`

在操作系统中能够找到这个路径。

但奇怪的是，同样的代码，在另外一台win11和同样的环境下，就是正常运行的。

**Comment by 8720** [comment]
> @TTT52 hello! 😊 It looks like you're busy with other tasks at the moment. When you get a chance to focus on this issue again, I suggest verifying the dataset's path and ensuring all required files are accessible as mentioned earlier. Sometimes, the devil is in the details with paths and file accessibility. If you encounter any specific errors or need further assistance when you're back on this, please feel free to share more details, and we'll be here to help. Good luck with your current tasks!

我也遇到了同样的问题，但不是yaml中路径的问题，使用同样的yaml文件，model.train()和model.predict()是正常的。但是model.tune()就报错。

os and env : win11+anaconda+py38+torch2.3.1+cu121。

尝试运行运行官网上的示例:
`from ultralytics import YOLO`
`model = YOLO("yolov8n.pt")`
`result_grid = model.tune(data="coco8.yaml", use_ray=True)`

控制台抛出错误
`2024-07-28 13:47:31,054	WARNING trial.py:648 -- The path to the trial log directory is too long (max length: 260. Consider using 'trial_dirname_creator' to shorten the path. Path: C:\Users\pinot\AppData\Local\Temp\ray\session_2024-07-28_13-47-27_083297_19956\artifacts\2024-07-28_13-47-31\_tune_2024-07-28_13-47-31\driver_artifacts\_tune_e1521_00000_0_bgr=0.1749,box=0.1181,cls=2.0375,copy_paste=0.0376,degrees=22.4397,fliplr=0.1247,flipud=0.5703,hsv_h=0.0722,hs_2024-07-28_13-47-31`

`FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\username\\AppData\\Local\\Temp\\ray\\session_2024-07-28_13-19-03_079600_32024\\artifacts\\2024-07-28_13-19-07\\_tune_2024-07-28_13-19-07\\driver_artifacts\\_tune_e9ab7_00000_0_bgr=0.5384,box=0.0466,cls=0.8277,copy_paste=0.8218,degrees=26.9491,fliplr=0.9799,flipud=0.9095,hsv_h=0.0197,hs_2024-07-28_13-19-07'`

在操作系统中能够找到这个路径。

但奇怪的是：同样的代码，在另外一台win11和同样的环境下，就是正常运行的。

**Comment by 8720** [comment]
不知道我遇到的情况和你们是否一致，运行官网上coco数据集的tune代码时，

```
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

result_grid = model.tune(data="coco8.yaml", use_ray=True)
```

出现了同样的提示。但问题说的更清楚一点，文件夹路径太长，超过了windows的260个字符的限制。
调整操作系统的相关设置无效，于是将anaconda设置中的env目录，从C:\Users\username\.conda，调整到了D盘根目录，缩短目录路径后，问题解决。

**Comment by pderrenger** [comment]
@8720 感谢分享您的解决方案！确实，Windows的路径长度限制可能导致类似的问题。将Anaconda环境目录移到更短的路径是一个有效的解决方法。如果其他用户遇到类似问题，也可以尝试这种方法来解决路径长度限制的问题。如果问题仍然存在，请确保使用的是最新版本的软件包，并随时在这里分享更多细节。谢谢！
