### ISSUE TITLE
How to save and then reload a custom finetuned YOLO model (with custom classes)

### ISSUE THREAD

**Issue by strickvl** [ultralytics/ultralytics#10297]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm training a YOLOv8 model using:

```python
model.train(
            data=data_path,
            epochs=epochs,
            batch=batch_size,
            imgsz=imgsz,
            device=[0, 1],
            verbose=True,
        )
```

The `data_path` is a YAML file like so:

```yaml
names:
  0: ship
path: path/to/data
test: images/test
train: images/train
val: images/val
```

I then export this as a PyTorch image using `model.save('path/to/somefilename.pt')`. So these weights are saved locally then.

I then try to load the model with `YOLO('path/to/somefilename.pt')` and then I get a YOLO model, but it has all the default YOLO classes and not the custom one I used for training any more.

Any idea how to export the model such that when I reload it, the classes are preserved?

I saw [in the docs](https://docs.ultralytics.com/modes/train/#usage-examples) that I could try:

```python
model = YOLO('yolov8n.yaml').load('yolov8n.pt')  # build from YAML and transfer weights
```

But when I do that I get an error saying that the `backbone` isn't available etc...

**Comment by glenn-jocher** [comment]
Hey there! 🌟 It seems like you've done a great job with training your custom YOLOv8 model. To export your model and ensure that the custom classes are preserved when reloading, here's a small tweak you can try:

After training, instead of using `model.save('path/to/somefilename.pt')`, simply use the `.pt` file that gets automatically saved in your runs directory (usually found under `runs/train/exp*/weights/best.pt` or `last.pt` for the last saved weights).

To load your fine-tuned model with custom classes preserved, you can directly load this `.pt` file like so:

```python
model = YOLO('runs/train/exp*/weights/best.pt')
```

This will load the model with all its configurations, including your custom classes as it uses the weights file which already contains information about the number of classes. 

Regarding the error you encountered with loading using the YAML file and `.pt` weight, it typically occurs if there's a mismatch or if the YAML file does not accurately represent the model configuration used during the training. Hence, directly loading the saved `.pt` file is more straightforward for your use case. 

Hope this helps, happy detecting! 🚀

**Comment by strickvl** [comment]
Thanks @glenn-jocher! Is there somewhere I can set where those runs get saved? For me locally it was set inside my pyenv environment somewhere hidden, but not sure where that would be on a different OS. If there was a way to specify that runs directory, that'd be great...

**Comment by strickvl** [comment]
Might be nicer just to have `.save` work to actually save the model in the same format etc as the one stored in that `runs` directory?

**Comment by MarsaouiAmjad** [comment]
hello @glenn-jocher  , am working on custom yolo model on kaggel and after the training i saved the model and when trying to reload it and use it it won't recognize my custom classes and the model wont work . any help and thanks for your time

**Comment by glenn-jocher** [comment]
@MarsaouiAmjad When saving a custom YOLO model with your own classes, you need to ensure those class definitions are included in the saved model file. Based on your situation with a DINOv2 backbone and Kaggle environment, try this approach:

```python
# After training is complete
model.save("custom_model.pt")  # This saves the model state

# To verify classes are preserved, you can reload and check
loaded_model = YOLO("custom_model.pt")
print(loaded_model.model.names)  # Should show your custom classes
```

If your classes aren't preserved, you may need to manually set them after loading:

```python
# Option 1: Directly set the names attribute
loaded_model = YOLO("custom_model.pt")
loaded_model.model.names = {0: 'your_class_name', 1: 'another_class', ...}

# Option 2: Save with class names explicitly included
from copy import deepcopy
from datetime import datetime
from ultralytics import __version__

# Get your class names from your data.yaml or define them
class_names = {0: 'your_class_name', 1: 'another_class', ...}

# Create updated checkpoint with class names
updates = {
    "model": deepcopy(model.model).half(),
    "names": class_names,
    "date": datetime.now().isoformat(),
    "version": __version__,
    "license": "AGPL-3.0 License (https://ultralytics.com/license)",
    "docs": "https://docs.ultralytics.com/"
}

# Save with class names included
torch.save({**model.ckpt, **updates}, "custom_model_with_classes.pt")
```

This should help preserve your custom class names when reloading the model.

**Comment by MarsaouiAmjad** [comment]
Thank you @glenn-jocher

**Comment by glenn-jocher** [comment]
@MarsaouiAmjad I'm glad that helped! For anyone else facing similar issues with saving custom class names in YOLO models, here's another approach specifically recommended for custom class preservation:

```python
# After training your model
model = YOLO("your_trained_model.pt")

# Set your custom classes explicitly
model.set_classes(["ship"])  # Replace with your actual class names

# Save the model with classes embedded
model.save("custom_model_with_classes.pt")
```

This approach leverages the `set_classes()` method which embeds your class definitions directly into the model file, similar to how YOLO-World models handle custom vocabulary. When you load this saved model later, your custom classes should be preserved without additional configuration.
