### ISSUE TITLE
how to get the average IOU result for a trained Object detection model

### ISSUE THREAD

**Issue by rasha4113** [ultralytics/ultralytics#10299]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm trying to evaluate my model and I'm trying to find the IOU results for my training to see what my model is doing wrong and if I can improve my dataset or my model training, I could not find and way to find such information not in the docs or any of the dsiscussions. ie. How can I get the average IOU for my test set?

**Comment by glenn-jocher** [comment]
Hello there! 🌟 You're on the right track wanting to evaluate your model's performance using the average IOU. It provides vital insight into how well your model is predicting the bounding boxes compared to the ground truth.

To get the average IOU for your test set during validation, you just need to run the validation (`val`) mode using the command line interface (CLI) or Python. After validation is complete, you'll find the average IOU (Intersection over Union) metric among the printed stats. Here's how you can do it:

### Using CLI
```bash
yolo val model=yolov8n.pt data=your_dataset.yaml
```

### Using Python
```python
from ultralytics import YOLO

model = YOLO('path/to/your_model.pt')
results = model.val(data='path/to/your_dataset.yaml')
print(f"Average IOU: {results.box.iou}")
```

Replace `'path/to/your_model.pt'` with the path to your trained model and `'path/to/your_dataset.yaml'` with the path to your dataset configuration file. 

The `results.box.iou` will give you the average IOU metric that you're looking for. 😊 Let us know if you have any more questions!

**Comment by rasha4113** [comment]
hello, thank you for the fast reply. but I seem to have a problem as this error message is shown when I try and run the provided code: 
'Metric' object has no attribute 'iou'. See valid attributes below 
Class for computing evaluation metrics for YOLOv8 model.

    Attributes:
        p (list): Precision for each class. Shape: (nc,).
        r (list): Recall for each class. Shape: (nc,).
        f1 (list): F1 score for each class. Shape: (nc,).
        all_ap (list): AP scores for all classes and all IoU thresholds. Shape: (nc, 10).
        ap_class_index (list): Index of class for each AP score. Shape: (nc,).
        nc (int): Number of classes.

    Methods:
        ap50(): AP at IoU threshold of 0.5 for all classes. Returns: List of AP scores. Shape: (nc,) or [].
        ap(): AP at IoU thresholds from 0.5 to 0.95 for all classes. Returns: List of AP scores. Shape: (nc,) or [].
        mp(): Mean precision of all classes. Returns: Float.
        mr(): Mean recall of all classes. Returns: Float.
        map50(): Mean AP at IoU threshold of 0.5 for all classes. Returns: Float.
        map75(): Mean AP at IoU threshold of 0.75 for all classes. Returns: Float.
        map(): Mean AP at IoU thresholds from 0.5 to 0.95 for all classes. Returns: Float.
        mean_results(): Mean of results, returns mp, mr, map50, map.
        class_result(i): Class-aware result, returns p[i], r[i], ap50[i], ap[i].
        maps(): mAP of each class. Returns: Array of mAP scores, shape: (nc,).
        fitness(): Model fitness as a weighted combination of metrics. Returns: Float.
        update(results): Update metric attributes with new evaluation results.

**Comment by glenn-jocher** [comment]
Hello! Thanks for reaching out and sharing the details of the issue you've encountered. It looks like there's been a slight misunderstanding regarding the attribute for obtaining the IOU directly. 

The evaluation metrics for YOLOv8 don't include a direct `iou` attribute accessible in the manner you've tried. Instead, the Intersection Over Union (IoU) can be inferred indirectly through other metrics like AP at specific IoU thresholds (for example, `map50()` for mAP at IoU threshold of 0.5).

To get a sense of how your model's predictions align with the ground truth in terms of IoU, you might consider looking at the mean Average Precision (mAP) over a range of IoU thresholds, which is provided by the `map()` method. If you're specifically interested in a single IoU threshold, `map50()` might be useful as it gives the mAP value at the 0.5 IoU threshold.

Here’s a small snippet on how you can obtain these metrics:
```python
from ultralytics import YOLO

# Load your trained model
model = YOLO('path/to/your_model.pt')

# Validate model and get metrics
results = model.val(data='path/to/your_dataset.yaml')

# Get mAP at IoU threshold of 0.5
map50 = results.map50()
print(f"mAP at IoU=0.5: {map50}")

# For overall mAP across multiple IoU thresholds
mean_ap = results.map()
print(f"Mean AP across IoU thresholds from 0.5 to 0.95: {mean_ap}")
```

These metrics should give you a comprehensive understanding of your model's performance across various IoU thresholds. 🚀 If you have any more questions or need further clarification, feel free to ask!
