### ISSUE TITLE
AttributeError: module 'psutil_posix' has no attribute 'getpagesize'

### ISSUE THREAD

**Issue by 873900204** [ultralytics/ultralytics#1030]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug
Found this problem during training:
![image](https://user-images.githubusercontent.com/79824658/219846677-ffb6a710-304c-498a-8427-20892d7d6e1e.png)

### Environment

![image](https://user-images.githubusercontent.com/79824658/219846719-20000b8e-925d-45e0-8d48-acab4b9bde33.png)

### Additional

Is it caused by the problem of the psutil version? Which version is appropriate?

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
please provide the command to reproduce.

**Comment by 873900204** [comment]
> 
Thank you for your reply. My command is：
yolo task=detect mode=train model=yolov8s.yaml data=data.yaml epochs=300 batch=32

**Comment by glenn-jocher** [comment]
Maybe update your psutil, i.e. `pip install -U psutil`

**Comment by beyondpzk** [comment]
I have met the same question, my version of pyutil is 5.9.4, and I try "python3 -m pip install psutil==5.9.1", it works!

**Comment by glenn-jocher** [comment]
@beyondpzk great to hear that downgrading the `psutil` package to version `5.9.1` worked for you, and helped you resolve the issue. Different versions of packages sometimes have incompatibilities with each other which can cause unexpected errors. It's always a good idea to check compatibility issues in various packages when encountering errors while working with different libraries or frameworks. If you encounter any further problems or have any other questions, please don't hesitate to ask. We are always here to help.
