### ISSUE TITLE
arg.yaml is not accepting image_weight and v5loader 

### ISSUE THREAD

**Issue by MrWhiteBeardd** [ultralytics/ultralytics#10304]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

 attempted to continue training my dataset using YOLOv8. However, I encountered an error message that says: ‘SyntaxError: ‘image_weights’ is not a valid YOLO argument. ‘v5loader’ is not a valid YOLO argument.’ I removed these lines from the args.yaml file, but they keep reappearing, and the file itself is regenerated after deletion. How can I resolve this issue?”

### Environment

Ultralytics YOLOv8.2.1 🚀 Python-3.11.6 torch-2.2.2+cu121 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 8188MiB)
Setup complete ✅ (12 CPUs, 15.2 GB RAM, 201.8/205.8 GB disk)

OS                  Windows-10-10.0.22631-SP0
Environment         Windows
Python              3.11.6
Install             pip
RAM                 15.19 GB
CPU                 AMD Ryzen 5 7640HS w/ Radeon 760M Graphics
CUDA                12.1

matplotlib          ✅ 3.8.4>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.13.0>=1.4.1
torch               ✅ 2.2.2+cu121>=1.8.0
torchvision         ✅ 0.17.2+cu121>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Minimal Reproducible Example

from ultralytics import YOLO
import torch 

def main():
    # Load a partially trained model
    model = YOLO('D:\\GDP\\YOLO\\runs\\pose\\train26\\weights\\last.pt')

    # Check if GPU is available and if so, use it
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    model.to(device)

    # Continue training the model with a smaller batch size
    results = model.train(data="config.yaml", epochs=1200, resume=True)
    #    results = model.train(data="config.yaml", epochs=1200, resume=True, batch_size=16)
# Save the model
   # model.save()
if __name__ == '__main__':
    main() 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by MrWhiteBeardd** [comment]
this didnt do much help

**Comment by glenn-jocher** [comment]
@MrWhiteBeardd i'm sorry to hear you're still having trouble! 😟 Let's tackle this step by step. It looks like `image_weights` and `v5loader` are not recognized options for YOLOv8. These arguments might be remnants from older versions or configurations not supported in your current setup.

Firstly, ensure your `config.yaml` for training does not include `image_weights` and `v5loader`. They are not needed for training with YOLOv8 and can safely be removed. Your training command and setup seem correct, but please double-check your dataset configuration (`config.yaml`) to ensure it's properly formatted for YOLOv8.

If the issue persists or if there are any other specific errors or messages you encounter, please share them. Often, the devil is in the details, and those additional info can give us a clearer path to a solution. 

Remember, we're here to help! 🚀

**Comment by MrWhiteBeardd** [comment]
The config file is simply the paths of my training :

path: D:\GDP\YOLO\Dataset\New folder1  # dataset root dir
train: train\images  # train images (relative to 'path')
val: val\images  # val images (relative to 'path')
#test: test\images
# Keypoints
kpt_shape: [21, 3] # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)

# Classes
names:
  0: human_hand


so there is no v5loader and weight loss as i am training hand pose estimation , so what can i do as i gone a big way in the training process?
Thanks
________________________________

**Comment by glenn-jocher** [comment]
@MrWhiteBeardd hey there! 👋

Thanks for providing your configuration details, it really helps! If `image_weights` and `v5loader` are not included in your `config.yaml` and you're still seeing errors related to them, it suggests the issue might be elsewhere, possibly in the training script or a default setting being incorrectly applied.

Given that you're working on hand pose estimation, your config looks just right for such a task. The keypoints configuration is accurately defined for hand poses, which is great.

Since `image_weights` and `v5loader` aren't relevant to your current project or YOLOv8's expected parameters, you can safely ignore any automatic references to them from the system or warnings about their absence. 

Should the system keep regenerating arguments or files mentioning them, this could be a caching issue, or an older version of a script might still be running. Double-check you're using the latest version of the YOLOv8 codes and scripts for your training process.

Keep pushing with your training! And remember, if specific error messages come up or there's anything else that catches your attention, don't hesitate to reach out. We're here to make sure your project succeeds! 🚀

Warm

**Comment by MrWhiteBeardd** [comment]
![Screenshot 2024-04-26 174209](https://github.com/ultralytics/ultralytics/assets/146958928/e4cd2c70-1851-4d3d-81d5-97e00ebb5856)
i began the training from scratch but encountered an error - there seemed to be no progress in the pose loss, which led to the training stopping automatically. Can you assist me in locating the error?
Thanks in advance

**Comment by glenn-jocher** [comment]
Hey there! 😊

It looks like you're having a hiccup with the pose loss not improving during training. This can happen for a few reasons, such as an issue with the data labels or perhaps the learning parameters needing a tweak.

Could you double-check your dataset to ensure the keypoints are correctly labeled and consistent across your dataset? Sometimes, a small discrepancy can throw off the training.

Also, playing around with the learning rate or batch size might help. For instance, you could try reducing the learning rate:

```python
model.train(data="config.yaml", epochs=1200, lr0=0.001)
```

Or adjusting the batch size if you haven't already:

```python
model.train(data="config.yaml", epochs=1200, batch_size=16)
```

Hope this gives you a good starting point! Let me know how it goes, and we'll take it from there. Happy training! 🚀
