### ISSUE TITLE
Can't export yolov8 in tflite with NMS

### ISSUE THREAD

**Issue by AbdalaDiasse** [ultralytics/ultralytics#10303]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to know why yoloV8 can't export tflite model with NMS , With yoloV5 we can easily export it with NMS but with YoloV8 even if you set nms=true the model is still exported without NMS. 

Thanks in advance .

**Comment by glenn-jocher** [comment]
Hello! 👋

Thanks for reaching out. In YOLOv8, exporting a `.tflite` model with NMS (Non-Maximum Suppression) directly integrated is not currently supported, unlike YOLOv5. The core reason involves the inherent differences in architectural optimizations and export capabilities between YOLOv5 and YOLOv8.

A common workaround is to perform NMS as a post-processing step after running the model inference in TensorFlow Lite. This approach allows you to leverage TensorFlow Lite's efficiency while maintaining control over NMS and other processing steps.

Here's an example snippet on how you might do NMS post-processing with TensorFlow in Python:

```python
import tensorflow as tf

# Assuming 'boxes' and 'scores' are the output from your TFLite model inference
boxes = ...  # Your detected bounding boxes
scores = ...  # Corresponding confidence scores

selected_indices = tf.image.non_max_suppression(
    boxes=boxes, scores=scores, max_output_size=5, iou_threshold=0.5, score_threshold=0.5
)

selected_boxes = tf.gather(boxes, selected_indices)
```
This snippet uses TensorFlow's `non_max_suppression` function to filter out boxes based on the IOU threshold and confidence scores.

If you're looking for more specific advice or alternatives tailored to your application, our community and docs are excellent resources to explore.

Hope this helps! Let us know if you have more questions. 😊

**Comment by yousefvalify** [comment]
How can I export yolov5 model to tflite with nms?

**Comment by pderrenger** [comment]
@yousefvalify to export a YOLOv5 model to TFLite with NMS, you can use the `export.py` script provided in the YOLOv5 repository. Ensure you are using the latest version of YOLOv5 for the best compatibility and features. If you encounter any issues, please verify if the problem persists with the latest updates. For detailed instructions, refer to the YOLOv5 export documentation. If you need further assistance, feel free to ask.

**Comment by KnightHawk06** [comment]
Any plans to support exporting a tflite model with NMS with yoloV8?

I'm trying to train a voloV8 model for a voxl2 board.

https://gitlab.com/voxl-public/support/voxl-train-yolov8
