### ISSUE TITLE
Precision and recall for every classes

### ISSUE THREAD

**Issue by Enryuwashere** [ultralytics/ultralytics#10319]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello Im new with yolo, I want to know is there any way to see the result of precision and recall for every classes?

**Comment by glenn-jocher** [comment]
@Enryuwashere hello! Welcome to YOLOv8! 😊

Yes, you can obtain precision and recall values for each class with our training scripts. After training your model, the precision and recall metrics for each class are available in your results CSV file (`results.csv`). This file is saved in the same directory where your weights are saved (`yolov8/runs/train/exp*/results.csv`).

You can also visualize these metrics using TensorBoard, which is launched automatically during training. The TensorBoard logs are located in your runs directory (`yolov8/runs/train/exp*`) and can give you a comprehensive visualization of precision, recall, and many other metrics!

If you need more detailed insights, consider exploring the validation outputs. For example, after training, you can run validation to see detailed performance metrics:

```bash
yolo val model=yolov8n.pt data=your_dataset.yaml imgsz=640
```

This will give you a summary including precision and recall values. Hope this helps, and best of luck with your YOLO journey! 🚀
