### ISSUE TITLE
Tracking doesn't always return object IDs 

### ISSUE THREAD

**Issue by maciejkr** [ultralytics/ultralytics#10314]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I have the following python code, when I run it objects are identified but in some cases they are not assigned tracking ID until the second frame. Am I doing something wrong or is this a bug?

First frame:
<img width="863" alt="image" src="https://github.com/ultralytics/ultralytics/assets/118856309/87050188-2543-4b7f-8e08-bdac628a9bdb">

Second frame:
<img width="1004" alt="image" src="https://github.com/ultralytics/ultralytics/assets/118856309/49c9007b-3c69-472a-b4dd-4351c747ede9">

### Minimal Reproducible Example

import cv2
import json
import argparse
from ultralytics import YOLO

# Create an argument parser to accept the video ID from the command line
parser = argparse.ArgumentParser()
parser.add_argument('--video_id', type=str, required=True, help='ID of the video')
args = parser.parse_args()

# Load the YOLOv8 model
model = YOLO('model/best.pt')

# Open the video file
video_path = "fwaking.mp4"
cap = cv2.VideoCapture(video_path)

# Get the video frame rate and total frame count
fps = cap.get(cv2.CAP_PROP_FPS)
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

# Set the starting frame number
start_frame = 2010
cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)

# Initialize the frame number and start time
frame_number = start_frame
start_time = start_frame / fps

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()
    if success:
        # Calculate the current time in seconds
        current_time = frame_number / fps

        # Run YOLOv8 tracking on the frame, persisting tracks between frames
        results = model.track(frame, persist=True)

        # Create a JSON object to store the frame information
        frame_info = {
            'video_id': args.video_id,
            'frame_number': frame_number,
            'start_time': start_time,
            'end_time': current_time,
            'objects': []
        }

        # Iterate over the detected objects
        for result in results:
            for box in result.boxes:
                # Skip processing if box.id is None
                if box.id is None:
                    continue

                # Extract the object ID and bounding box coordinates
                object_id = int(box.id.item())
                x1, y1, x2, y2 = map(int, box.xyxy[0].tolist())

                # Add the object information to the JSON object
                frame_info['objects'].append({
                    'object_id': object_id,
                    'bbox': [x1, y1, x2, y2]
                })

        # Print the JSON response for the current frame
        print(json.dumps(frame_info))

        # Display the frame with bounding boxes
        for result in results:
            annotated_frame = result.plot()
        cv2.imshow('YOLOv8 Tracking', annotated_frame)

        # Increment the frame number
        frame_number += 1

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

    # Update the start time for the next frame
    start_time = current_time

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hey there! 🌟 It seems like you've encountered a situation where object IDs are not being assigned immediately in the first frame. This behavior may not necessarily indicate a bug but could be related to how the tracking algorithm initializes and starts tracking objects. 

In tracking algorithms, especially those dealing with real-time video streams, object IDs are assigned based on object detection and the successful association of these objects across successive frames. Sometimes, an object might not be assigned an ID immediately if the tracking algorithm requires additional frames to confidently link the detection across time. 

You're not doing anything wrong in your code; this behavior can be specific to the tracking algorithm's design and how it handles object initialization and tracking confidence. If this behavior significantly impacts your application, consider submitting a detailed issue on the Ultralytics YOLOv8 GitHub page with examples and the specific challenges it poses. This feedback can help improve the model!

Keep experimenting, and thanks for using Ultralytics YOLOv8! If you have any more questions or run into other issues, feel free to reach out.

**Comment by Laughing-q** [comment]
@maciejkr no worries! that's how tracker algorithms work, matching predictions of current frame and predictions from previous frame, hence the predictions from first frame don't have IDs yet.
