### ISSUE TITLE
How to retrieve angles of rotated bbox in OBB model architecture ? 

### ISSUE THREAD

**Issue by leejejang** [ultralytics/ultralytics#10328]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, thank you for awesome works ! 

Regarding  a YOLO-OBB, I wonder how did you retrieve the rotated BBox angles in the model architecture?

**Comment by glenn-jocher** [comment]
Hi there! Thanks for reaching out and for your kind words. 😊

For retrieving rotated bounding box (bbox) angles in a YOLO-OBB model, the angles are part of the output predictions. When working with models that output Oriented Bounding Boxes (OBB), the model typically predicts an additional angle parameter along with the standard bbox coordinates. This angle represents the rotation of the bbox.

In Python, assuming you have predictions from a YOLO-OBB model, you can access the angle of a rotated bbox directly from the predictions. Here is a simplified example:

```python
from ultralytics import YOLO

# Load your trained model
model = YOLO('path/to/your/obb-model.pt')

# Perform prediction on an image
results = model('path/to/your/image.jpg')

# Accessing the rotated bbox angle for each detection
for det in results.obb:
    x, y, w, h, angle = det  # x, y, width, height, rotation angle
    print(f"Rotated bbox angle: {angle}")
```
In this example, `results.obb` would give you the detections with oriented bounding boxes, where `angle` represents the rotation of the bbox (Usually in radians or degrees based on how model is trained).

Please, ensure to adjust paths to your specific model and image for actual use. Don't hesitate to ask if you have more questions!

**Comment by Zyjer888** [comment]
Hello, I will still report an error when I follow your operation.
AttributeError: 'list' object has no attribute 'OBB'

**Comment by Zyjer888** [comment]
AttributeError: 'list' object has no attribute 'obb'

**Comment by glenn-jocher** [comment]
@Zyjer888 hello! It looks like there may have been a little misunderstanding in accessing the oriented bounding box (OBB) data. 😊 Instead of accessing it directly as an attribute, you would typically parse the results like this:

```python
from ultralytics import YOLO

# Load the model
model = YOLO('path/to/your/obb-model.pt')

# Run prediction
results = model('path/to/your/image.jpg')

# Assuming you have OBB results in your outputs
for result in results:
    if hasattr(result, 'obb'):
        x, y, w, h, angle = result.obb.xyxy[0], result.obb.xyxy[1], result.obb.xyxy[2], result.obb.xyxy[3], result.obb.orientation
        print(f"OBB coordinates: {x}, {y}, {w}, {h} with angle {angle}")
```
Please make sure you're using the correct version of the Ultralytics YOLO model that supports OBB. Let me know if this resolves the issue!

**Comment by longmao666** [comment]
> @Zyjer888 hello! It looks like there may have been a little misunderstanding in accessing the oriented bounding box (OBB) data. 😊 Instead of accessing it directly as an attribute, you would typically parse the results like this:
> 
> ```python
> from ultralytics import YOLO
> 
> # Load the model
> model = YOLO('path/to/your/obb-model.pt')
> 
> # Run prediction
> results = model('path/to/your/image.jpg')
> 
> # Assuming you have OBB results in your outputs
> for result in results:
>     if hasattr(result, 'obb'):
>         x, y, w, h, angle = result.obb.xyxy[0], result.obb.xyxy[1], result.obb.xyxy[2], result.obb.xyxy[3], result.obb.orientation
>         print(f"OBB coordinates: {x}, {y}, {w}, {h} with angle {angle}")
> ```
> 
> Please make sure you're using the correct version of the Ultralytics YOLO model that supports OBB. Let me know if this resolves the issue!

I find that if we want to get 'xywhangle',we should   parse the results like this
`        for result in results:
            if hasattr(result, 'obb'):
                x= result.obb.xywhr[0][0]
                y= result.obb.xywhr[0][1]
                w= result.obb.xywhr[0][2]
                h= result.obb.xywhr[0][3]
                angle= result.obb.xywhr[0][4]
                print(f"OBB coordinates: {x}, {y}, {w}, {h} with angle {angle}")`

**Comment by CarlosAmaral** [comment]
> [@Zyjer888](https://github.com/Zyjer888) hello! It looks like there may have been a little misunderstanding in accessing the oriented bounding box (OBB) data. 😊 Instead of accessing it directly as an attribute, you would typically parse the results like this:
> 
> from ultralytics import YOLO
> 
> # Load the model
> model = YOLO('path/to/your/obb-model.pt')
> 
> # Run prediction
> results = model('path/to/your/image.jpg')
> 
> # Assuming you have OBB results in your outputs
> for result in results:
>     if hasattr(result, 'obb'):
>         x, y, w, h, angle = result.obb.xyxy[0], result.obb.xyxy[1], result.obb.xyxy[2], result.obb.xyxy[3], result.obb.orientation
>         print(f"OBB coordinates: {x}, {y}, {w}, {h} with angle {angle}")
> Please make sure you're using the correct version of the Ultralytics YOLO model that supports OBB. Let me know if this resolves the issue!

Is ` result.obb.orientation` still available in YOLO's 11n-obb model because I can't seem to be able to extract it so understand what's the angle of the box.

**Comment by glenn-jocher** [comment]
Hello! For accessing rotation angles in YOLO11 OBB models, the recommended method is indeed through the `xywhr` property as you've discovered. The `orientation` attribute isn't directly exposed - instead, the rotation angle is the 5th element in `xywhr` (x_center, y_center, width, height, rotation). Your current approach using `result.obb.xywhr[0][4]` is correct. For complete details, see the OBB Results documentation section on xywhr format.

**Comment by CarlosAmaral** [comment]
@glenn-jocher Thank you! I'd like to also ask, how to ask how to interpret the angle value. Is it in rad or degrees and can it be a negative value?

**Comment by glenn-jocher** [comment]
The rotation angle in YOLO-OBB models is **in radians** and ranges between **-π/2 to π/2** (equivalent to -90° to 90°), representing the clockwise rotation from the horizontal axis. This format allows precise orientation representation while maintaining compatibility with standard geometric conventions. For full details, see the [OBB Results documentation section](https://docs.ultralytics.com/tasks/obb/#results). Thank you for your question! 😊
