### ISSUE TITLE
check_amp should use model argument and not download a new model

### ISSUE THREAD

**Issue by trianta2** [ultralytics/ultralytics#10325]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

This thread describes the issue: https://github.com/ultralytics/ultralytics/issues/7915

In short, the line:

https://github.com/ultralytics/ultralytics/blob/dae4ce8307fc38990b959cd5e783a7e3cd82eb3d/ultralytics/utils/checks.py#L652

creates a new model which causes a new model to be downloaded. The `check_amp` function:

https://github.com/ultralytics/ultralytics/blob/dae4ce8307fc38990b959cd5e783a7e3cd82eb3d/ultralytics/utils/checks.py#L612

does not even use the provided `model` argument to perform the check.

So the unnecessary download can be avoided if the provided `model` is used in the check.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@trianta2 thank you for pointing out the issue with `check_amp` function not utilizing the passed `model` argument and unnecessarily downloading a new model. You're absolutely right, and addressing this could optimize the process by avoiding redundant downloads. We'll look into how we can improve this function by making use of the provided `model` argument directly to perform the check accordingly. 

Your contribution to making YOLOv8 better is much appreciated! 🙌 If you have any further suggestions or notice anything else, feel free to share.

**Comment by ManuelZ** [comment]
Just noticed this while pointing my training script towards a model in certain path and ending up with a new downloaded model in my root directory.
