### ISSUE TITLE
OBB Tracking

### ISSUE THREAD

**Issue by serwansj** [ultralytics/ultralytics#10321]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Does tracking with the YOLO OBB model work right out of the box? 

I saw this [PR](https://github.com/ultralytics/ultralytics/pull/7731) and imagined that by running the following code I would now obtain tracks, however, `results[0].obb.id` is not populated:

```python
model = YOLO('./checkpoints/yolov8x-obb.pt')
annotate_frames = []

for image in images[:-5]:
    results = model.track(image, persist=True)
    annotated_frame = results[0].plot()
    annotate_frames.append(annotated_frame)
```

The same car is visible in every frame and it is being detected correctly, but as mentioned there is no track.

**Comment by serwansj** [comment]
Figured it out: The problem was that the frames were to far apart from each other, so the object could not be tracked.

**Comment by glenn-jocher** [comment]
Glad to hear you figured it out! 🎉 It's an important point for object tracking — ensuring the frames are close enough temporally for the tracker to maintain continuity in object identification. If the frames are too far apart, the tracker might perceive them as separate instances. Thank you for sharing your solution; it might help others facing a similar issue. If you need further assistance or have more questions, feel free to ask!
