### ISSUE TITLE
Does YOLOv8 has an option to use Transformer Block like the YOLOv5?

### ISSUE THREAD

**Issue by sammgithub** [ultralytics/ultralytics#10327]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,
Could you please help me understand, if I want to use a transformer block in YOLOv8 how can I do so? For example, in YOLOv5 the transformer block is used in ```class TransformerLayer(nn.Module):``` function in the ```models/common.py```, how can I do so in YOLOv8? 

What changes/updates I have to make, and where they should be made, and perhaps a procedure to use my custom block using the YOLOv8? Thank you.

### Additional

I am trying to work on a custom Transformer block in YOLOv8. I was able to use my custom block in YOLOv5 by making changes in ```models/common.py```, where it is implemented in quite a straight forward way. I was looking for similar structure in YOLOv8, which seems to be different. I.E., in ```ultralytics/models``` there is ```redetr``` which seems to be a DETR implementation.

**Comment by glenn-jocher** [comment]
@sammgithub hello there! 😊

I'm glad to see your interest in experimenting with YOLOv8 and custom Transformer blocks! 

Indeed, YOLOv8 introduces a structured approach to incorporating different model architectures, including transformers like DETR, within its framework. If you're looking to integrate a custom Transformer block into YOLOv8, you might consider following the approach similar to how `redetr` (our DETR implementation) is integrated.

You can create a custom module for your Transformer block in a similar manner to `redetr`. Then, to use this in your model, you'd modify the appropriate configuration file (`*.yaml`) under the `ultralytics/models` directory to include your transformer block in the architecture definition.

For example, if you've created a file named `my_transformer.py` that contains your custom Transformer block class `MyTransformerBlock`, you would:

1. Import and use it in the model definition YAML file:
   
```yaml
# In your model.yaml
...
backbone: MyTransformerBlock
...
```

2. Ensure that `MyTransformerBlock` is properly imported in the YAML parsing script.

Please make sure that your custom Transformer block adheres to the inputs and outputs expected by YOLOv8's architecture to ensure seamless integration.

While this is a high-level overview, the exact implementation can vary based on your custom block's specifics. If you run into specific challenges or have more detailed questions as you proceed, feel free to ask here!

Happy coding! 🚀

**Comment by sammgithub** [comment]
@glenn-jocher thank you for the suggestion with detailed steps. I am working on it. I will followup soon.

**Comment by glenn-jocher** [comment]
@sammgithub Great to hear that you're making progress! Looking forward to your follow-up. If you have any more questions along the way, just let us know. Happy coding! 😊

**Comment by sammgithub** [comment]
Hi @glenn-jocher,  could you please re-open this issue (sorry for being late with this issue) as I need help to solve a problem!
I am trying to use `yolov8-rtdetr.yaml` from `ultralytics/ultralytics/cfg/models/v8/`, however, I am getting the following error!

```KeyError                                  Traceback (most recent call last)
[/content/ultralytics/ultralytics/engine/model.py](https://localhost:8080/#) in _smart_load(self, key)
    806         try:
--> 807             return self.task_map[self.task][key]
    808         except Exception as e:

KeyError: None

The above exception was the direct cause of the following exception:

NotImplementedError                       Traceback (most recent call last)
4 frames
[/content/ultralytics/ultralytics/engine/model.py](https://localhost:8080/#) in _smart_load(self, key)
    809             name = self.__class__.__name__
    810             mode = inspect.stack()[1][3]  # get the function name.
--> 811             raise NotImplementedError(
    812                 emojis(f"WARNING ⚠️ '{name}' model does not support '{mode}' mode for '{self.task}' task yet.")
    813             ) from e
NotImplementedError: WARNING ⚠️ 'YOLO' model does not support '_new' mode for 'None' task yet.```

for all other such as, `yolov8.yaml`, `yolov8-ghost.yaml`, `yolov8-seg.yaml`, `yolov8-cls-resnet50.yaml`, etc., I am able to train though. Any suggestions! please?

**Comment by pderrenger** [comment]
Hi @sammgithub, thanks for reaching out! It looks like the error is due to the `yolov8-rtdetr.yaml` configuration not being fully supported yet. For now, you might want to ensure you're using the latest version of the Ultralytics package, as updates often include fixes and new features. If the issue persists, consider using other supported configurations like `yolov8.yaml` or `yolov8-seg.yaml` for your experiments. Integrating ViT with YOLOv8 might require some custom modifications. If you need further assistance, feel free to ask!

**Comment by sammgithub** [comment]
Hi @glenn-jocher,
I saw that `ultralytics/nn/modules/transformer.py` includes the Transformer block recently, which I wanted to use, however, I got the following error:

```
KeyError                                  Traceback (most recent call last)

<ipython-input-7-8bd95aabbe50> in <cell line: 1>()
----> 1 model = YOLO("yolov8m.yaml")
4 frames
/content/ultralytics/ultralytics/nn/tasks.py in parse_model(d, ch, verbose)
    902     layers, save, c2 = [], [], ch[-1]  # layers, savelist, ch out
    903     for i, (f, n, m, args) in enumerate(d["backbone"] + d["head"]):  # from, number, module, args
--> 904         m = getattr(torch.nn, m[3:]) if "nn." in m else globals()[m]  # get module
    905         for j, a in enumerate(args):
    906             if isinstance(a, str):

KeyError: 'TransformerBlock'
```

in YOLOv8.yaml added the TransformerBlock as follows:

```
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, TransformerBlock, [512, 512, 8, 1]] <<<<< here
  - [-1, 1, SPPF, [1024, 5]] # 9
   ```
in the `ultralytics/nn/tasks.py`, within `def parse_model` function, I added TransformerBlock as follows:
```if m in {
    Classify, Conv, ConvTranspose, GhostConv, Bottleneck, GhostBottleneck, SPP, SPPF, DWConv, Focus,
    BottleneckCSP, C1, C2, C2f, RepNCSPELAN4, ELAN1, ADown, AConv, SPPELAN, C2fAttn, C3, C3TR, C3Ghost,
    nn.ConvTranspose2d, DWConvTranspose2d, C3x, RepC3, PSA, SCDown, C2fCIB, TransformerBlock,
}:
```
but still the same error!
I am running in google colab for my custom dataset.
could you please help?

**Comment by glenn-jocher** [comment]
Hi @sammgithub,

It looks like you're on the right track by adding the `TransformerBlock` to your model configuration and modifying the `parse_model` function. However, the error suggests that the `TransformerBlock` is not being recognized. Ensure that the `TransformerBlock` is correctly imported in the relevant files. Additionally, please verify that you're using the latest version of the Ultralytics package, as updates may include necessary fixes or improvements. If the issue persists, consider sharing more details or any additional modifications you've made.
