### ISSUE TITLE
Direct support for AMG GPUs/ ROCm

### ISSUE THREAD

**Issue by swarupbc** [ultralytics/ultralytics#10323]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

As ultralytics direct supports Nvidia Cuda, please implement native support for AMD ROCm.

### Use case

Training models with AMD Radeon GPUs with ROCm.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! Thanks for bringing this up. 🌟 

Currently, YOLOv8 primarily supports Nvidia CUDA for GPU acceleration. Integrating AMD ROCm support is indeed an interesting proposal that would widen the accessibility and usability of YOLO models across different hardware platforms.

While we don't have native ROCm support at the moment, this is something we might consider for the future. We appreciate your interest and the community's effort in enhancing the YOLOv8 ecosystem. Although we can't promise an immediate implementation, we always welcome contributions and discussions on how we might expand support to include AMD GPUs.

If anyone in the community is experienced with ROCm and interested in contributing towards this feature, we encourage you to share your thoughts or progress. Though you've indicated you're not ready to submit a PR currently, ongoing community input is invaluable for such developments.

Stay tuned to our GitHub issues and pull requests for updates on this and other features! 🚀

**Comment by sk1ddy** [comment]
I'm also interested in this! Are there plans to include support for ROCm?

**Comment by glenn-jocher** [comment]
@sk1ddy thanks for your interest! At this time, Ultralytics YOLO focuses on NVIDIA CUDA for GPU acceleration as seen in our existing GPU documentation. While we don't have immediate plans for native ROCm support, we welcome community contributions through GitHub pull requests if you'd like to explore this direction. For those needing AMD GPU support today, you might consider investigating PyTorch's ROCm compatibility layers as an interim solution.

**Comment by ncw2k69** [comment]
on debian (linux), what works for me (like 8x times faster than CPU on a 370), after install all the project dependencies, i do an upgrade
```
pip3 install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm7.1
```
then you can check it with
```
python3 -c "import torch; print(f'CUDA available: {torch.cuda.is_available()}'); print(f'Device: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else "None"}')"
```
if ti says the following, then you can use rocm
```
CUDA available: True
Device: AMD Radeon 890M
```
you need to update the python script and include the "cuda" device, i have the following
```python
# Use ROCm if available
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device.upper()} - {torch.cuda.get_device_name(0) if torch.cuda.is_available() else "None"}")

results = model(inputVideo, 
                stream=True, 
                device=device,   # <-- HERE
                imgsz=(frameHeight,frameWidth),
                conf=0.145,
                iou=0.9,
            )
```
more about full setup on linux, you can find here https://github.com/ncw2k69/linux/blob/main/rocm.md

**Comment by glenn-jocher** [comment]
Thanks for sharing this—Ultralytics YOLO will generally work on ROCm as long as your installed `torch` reports `torch.cuda.is_available()` (ROCm uses the same `torch.cuda` API), so you can use `device="cuda:0"`/`device=0` and confirm the environment with `yolo checks` or `ultralytics.utils.checks.collect_system_info()` from the loaded install ([checks utilities reference](https://docs.ultralytics.com/reference/utils/checks/)); if you hit any Ultralytics-specific failures on ROCm, please open a new issue (this one is closed/stale) with the full text traceback and `yolo checks` output so we can track it. For AMD/Intel GPU inference without ROCm, exporting to NCNN and running with Vulkan `device="vulkan:0"` is also supported ([NCNN + Vulkan guide](https://docs.ultralytics.com/integrations/ncnn/)).

```python
from ultralytics import YOLO

model = YOLO("yolo26n.pt")
_ = model("path/to/image.jpg", device="cuda:0")  # ROCm builds usually map here
```
