### ISSUE TITLE
confusion_matrix

### ISSUE THREAD

**Issue by Pandaliaojing** [ultralytics/ultralytics#10337]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val

### Bug

After I updated the new ultralytics version, the confusion matrix graph had no data except for the first column when validated, and I printed the other positions with data.
![image](https://github.com/ultralytics/ultralytics/assets/143798298/21a31d72-8cb9-4c95-b8ec-dd84d311dcbd)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Pandaliaojing** [comment]
I tried an older version of ultralytics and didn't have the above issues

**Comment by glenn-jocher** [comment]
Hello! It seems like the update may have introduced a disparity in how confusion matrices are generated or displayed in your setup. Let's try a couple of things to troubleshoot:

1. Ensure that your dataset is correctly loaded and labels are properly assigned. Sometimes, mislabeling or discrepancies in data loading can lead to unexpected results in confusion matrices.

2. Double-check the validation command you're using for any possible differences from your previous setup.

If the issue persists, would you mind sharing a snippet of your validation command and a brief description of your dataset (e.g., number of classes)? This information might help us pinpoint the discrepancy more accurately. Thanks for bringing this to our attention! 🚀

**Comment by ScotfaAI** [comment]
Hi just wanted to add I also am getting the same issue, I was using a v9c model with 8.2.10, 8.2.2 and 8.1.34:
![confusion_matrix](https://github.com/ultralytics/ultralytics/assets/22196833/2a684e87-9b83-4cf4-aec9-33460b81dbce)
Which version worked for you? @Pandaliaojing
