### ISSUE TITLE
It should only return results that are greater than 0.

### ISSUE THREAD

**Issue by sarpx** [ultralytics/ultralytics#10342]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I am trained in classification and have hundreds of labels. When I look at the results, I see that all non-existent classes are given as 0. This means unnecessary data growth for thousands of files. I want a parametric structure that can only take values ​​greater than 0 in the results, because sometimes it needs to come with a value of 0.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hey there! 👋

It seems like you're interested in filtering your classification results to exclude class predictions with scores of 0. You can achieve this by iterating over your results and only keeping those with scores greater than 0.

Here's a quick Python example assuming `results` is your classification output:

```python
filtered_results = {k: v for k, v in results.items() if v > 0}
```

This line creates a new dictionary only with classes that have a score greater than 0, effectively reducing your data size for easier handling.

Hope this helps! Let us know if you have any more questions. 😊

**Comment by sarpx** [comment]
@glenn-jocher  
Thanks for the answer.
I can do this too, but I want it to be built into YoloV8 because every time the version changes, I have to change these codes again. Many people are probably dealing with this.

**Comment by glenn-jocher** [comment]
@sarpx hey! 🌟

Absolutely understand where you're coming from. Making results filtering a built-in feature of YOLOv8 could indeed streamline workflows for many users.

I'll pass this feedback to the team to consider for future updates. Your input helps us improve. Keep those suggestions coming!

Thanks for reaching out! 🚀
