### ISSUE TITLE
Let the classification model be able to read directories and subdirectories.

### ISSUE THREAD

**Issue by sarpx** [ultralytics/ultralytics#10343]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I can successfully provide classification training. But there are directories and subdirectories that I want to test, and in order to pass them through the classification model, I need to export each image directory separately. This causes a lot of work and errors. I want to be able to pass the images in a directory and subdirectory through the model according to the same folder structure and get the results according to the same directory.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sarpx hello! Thank you for reaching out with your feature request. 🚀 

Currently, YOLOv8 supports processing multiple input sources, including directories, for classification tasks. To classify images in a directory and its subdirectories, you can directly use the glob pattern `**/*` to include all image files recursively. Here's a quick example in CLI for classification:

```bash
yolo classify predict model=yolov8n-cls.pt source='path/to/your/directory/**/*.jpg'
```

This command will process all JPG images in the specified directory and its subdirectories. Note: You might need to adjust the `source` pattern according to your file types (e.g., `.png`, `.bmp`).

This approach should simplify testing your images without the need to manually export each directory. If you encounter any specific issues or errors using this method, feel free to share more details, and we'll be happy to help!

Best regards.

**Comment by sarpx** [comment]
`yolo classify predict model=yolov8n-cls.pt source='path/to/your/directory/**/*.*'` 
I tried it this way and it worked great, thank you.

**Comment by glenn-jocher** [comment]
@sarpx You're welcome! Glad to hear it worked out for you. If you have any more questions or need further assistance, don't hesitate to reach out. Happy classifying! 🚀
