### ISSUE TITLE
Empty ultralytics.engine.results.OBB result but result.save() properly shows predictions

### ISSUE THREAD

**Issue by mgcrea** [ultralytics/ultralytics#10357]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I have trained a YOLO8m-obb model and when using `model()` to predict I properly see valid detections on the `result.save()` file.

However the result is totally empty (None boxes, None masks, etc.):

```
0: 640x640 14.5ms
Speed: 2.4ms preprocess, 14.5ms inference, 2.7ms postprocess per image at shape (1, 3, 640, 640)
Boxes: None Masks: None Keypoints: None Probs: None
```

### Environment

Ultralytics YOLOv8.2.3 🚀 Python-3.12.2 torch-2.3.0 CPU (Apple M1 Max)
Setup complete ✅ (10 CPUs, 32.0 GB RAM, 728.7/926.4 GB disk)

OS                  macOS-14.4.1-arm64-arm-64bit
Environment         Darwin
Python              3.12.2
Install             git
RAM                 32.00 GB
CPU                 Apple M1 Max
CUDA                None

matplotlib          ✅ 3.8.4>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.13.0>=1.4.1
torch               ✅ 2.3.0>=1.8.0
torchvision         ✅ 0.18.0>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
(.venv) 

### Minimal Reproducible Example

```
from ultralytics import YOLO

# Load a model
model = YOLO('./runs/obb/train12/weights/best.pt')  # load a custom model

# Predict with the model
# https://docs.ultralytics.com/modes/predict/#inference-sources
results = model(['/home/jovyan/transforms/Base/019.640.jpg'])  # predict on an image

# Process results list
for result in results:
    boxes = result.boxes  # Boxes object for bounding box outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Probs object for classification outputs
    # result.show()  # display to screen
    print(f"Boxes: {boxes} Masks: {masks} Keypoints: {keypoints} Probs: {probs}")
    result.save(filename='result.jpg')  # save to disk
 ```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mgcrea** [comment]
Just had to use the `.obb` instead of `.boxes`.

**Comment by glenn-jocher** [comment]
Glad you found the solution! 🚀 That's correct, for YOLOv8 models trained for oriented bounding box (OBB) detection, you would explore the `.obb` attribute to access the predictions. If you have any more questions or run into issues, feel free to reach out. Happy coding!
