### ISSUE TITLE
How to extract class(label) from webcam recognition results?

### ISSUE THREAD

**Issue by KatherineMae0115** [ultralytics/ultralytics#10350]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, good day. I want to extract the class (label) from the webcam recognition. Then, I'll turn on the green LED (Bio) or red LED (Non-bio) and display the type of waste (Bio or Non-bio) on the LCD.

this is the code that I use:

    while True:
           success, img = cap.read()
           results = model(img, stream = True)
    #coordinates
    for r in results:
        boxes = r.boxes
        
        for box in boxes:
            #bounding box
            x1, y1, x2, y2 = box.xyxy[0]
            x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2) # convert to int values
        
            #put box in cam
            cv2.rectangle(img, (x1, y1), (x2, y2), (255, 0, 255), 3)
        
            #confidence
            confidence = math.ceil((box.conf[0]*100))/100
            print("Confidence ---> ", confidence)
        
            #classname
            cls = int(box.cls[0])
            print("Class Name ---> ", classNames[cls])
        
            #object details
            org = [x1, y1]
            color =(255, 0, 0)
            thickness = 2
            font =cv2.FONT_HERSHEY_SIMPLEX
            fontScale = 1
            
        
            cv2.putText( img, classNames[cls], org, font, fontScale, color, thickness)

          if cls == 0 and classNames == "Non-Biodegradable":
                test.Bio()
          
        
            elif cls == 1 and classNames == "Non-Biodegradable":
                test.Nonbio()

    
          

    
          

### Additional

But the output is: 
![438083783_294990700363896_7638367887461522688_n](https://github.com/ultralytics/ultralytics/assets/114711105/b9ce8d8d-084b-4768-b3a6-3c700f0d3e0d)

**Comment by glenn-jocher** [comment]
@KatherineMae0115 hello! It looks like you're on the right track with extracting class labels from webcam results. Here's a compact way to improve your code for identifying and acting upon specific classes:

First, ensure your class names are correctly mapped, e.g., `classNames = ["Bio", "Non-Bio"]`. Then, in your loop where you process each detection, you can directly access the class name and perform actions accordingly:

```python
for r in results:
    boxes = r.boxes
    for box in boxes:
        # Other processing...

        cls_index = int(box.cls[0])  # Class index
        class_name = classNames[cls_index]  # Get class name
        print("Class Name ---> ", class_name)

        # Now you can directly use the class_name to make decisions
        if class_name == "Bio":
            test.Bio()
            print("Turning on GREEN LED for Bio.")
        elif class_name == "Non-Bio":
            test.Nonbio()
            print("Turning on RED LED for Non-Bio.")
```

Ensure that the string comparison in if-else blocks exactly matches the classes defined in your `classNames` array.

Please adjust the GPIO or LED control logic (`test.Bio()` and `test.Nonbio()`) as per your hardware setup. Happy coding! 🚀

**Comment by KatherineMae0115** [comment]
Thank you so much. I finally got it

**Comment by glenn-jocher** [comment]
@KatherineMae0115 That's awesome to hear! 😊 If you have any more questions or run into issues later on, feel free to reach out. Happy coding!
