### ISSUE TITLE
close

### ISSUE THREAD

**Issue by khanhjt** [ultralytics/ultralytics#10362]
close

**Comment by glenn-jocher** [comment]
Certainly! To calculate the mAP (mean Average Precision) at IoU=0.95 (mAP@.95) for YOLOv8, you can use the `val` mode with your model. Here's a quick example using CLI:

```bash
yolo detect val model=yolov8n.pt data=your_dataset.yaml --imgsz=640 --conf-thres=0.001 --iou-thres=0.95
```

Ensure you replace `your_dataset.yaml` with your dataset configuration file and adjust `--imgsz`, `--conf-thres`, and other parameters as needed. This command evaluates the model on the validation set defined in `your_dataset.yaml`, specifically calculating mAP at IoU threshold of 0.95.

For more detailed insights on validation and performance metrics, you might find our [documentation](https://docs.ultralytics.com/modes/val) helpful! 📚

Let us know if you need further clarification or assistance!
