### ISSUE TITLE
How to write a custom dataloader to do fusion from two data folders

### ISSUE THREAD

**Issue by wink94** [ultralytics/ultralytics#10365]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to write a data loader to train the Yolov8 model, from two data sources, combine each image from data sources and concatenate into 3 + 3 = 6 channel input, that means let's say i have two registered image folder sets with the same scene, and same image names, I want to write a data loader to train, by fetching both images from two folders and concatenate and feed to the network, is this possible in yolov8 model

**Comment by glenn-jocher** [comment]
@wink94 hello! 🙌 Yes, you can customize a data loader to combine images from two folders into a single 6-channel image for training with YOLOv8. Here’s a concise way to achieve this using PyTorch, assuming your dataset structure allows for straightforward pairing of the corresponding images by filename:

```python
import os
import cv2
import torch
from torch.utils.data import Dataset, DataLoader
from torchvision.transforms import ToTensor

class CustomDataset(Dataset):
    def __init__(self, folder1, folder2, transform=None):
        self.folder1 = folder1
        self.folder2 = folder2
        self.filenames = os.listdir(folder1)
        self.transform = transform

    def __len__(self):
        return len(self.filenames)

    def __getitem__(self, idx):
        img_name = self.filenames[idx]
        img_path1 = os.path.join(self.folder1, img_name)
        img_path2 = os.path.join(self.folder2, img_name)

        img1 = cv2.imread(img_path1, cv2.IMREAD_GRAYSCALE)  # or cv2.IMREAD_COLOR for 3-chan
        img2 = cv2.imread(img_path2, cv2.IMREAD_GRAYSCALE)  # Use IMREAD_COLOR as needed

        combined_img = np.concatenate((img1, img2), axis=2)  # Concatenating along channel

        if self.transform:
            combined_img = self.transform(combined_img)

        return combined_img

transform = ToTensor()  # Add more transformations as needed
custom_dataset = CustomDataset(folder1='path/to/folder1', folder2='path/to/folder2', transform=transform)
data_loader = DataLoader(custom_dataset, batch_size=4, shuffle=True)  # Adjust batch_size as per your requirement
```

This code snippet creates a PyTorch `Dataset` class that automatically fetches corresponding images from two folders, combines them along the channel dimension, and optionally applies any transformations passed to it. Ensure that the `cv2.imread()` method's flag matches your images' channel requirement (e.g., `cv2.IMREAD_GRAYSCALE` for grayscale images or `cv2.IMREAD_COLOR` for three-channel images).

You’d have to adapt the labeling process in this loader to match your 6-channel inputs, and ensure your YOLOv8 model can handle 6-channel input, which might require some modification to the model's initial convolutional layer to accept the different channel size.

It perfectly integrates into your PyTorch-based YOLOv8 pipeline. I hope this helps! 😊

**Comment by wink94** [comment]
@glenn-jocher  thank you for the response, where should I pass this dataloader? 

`model.train(data=dataloaders, epochs=50)`

above code doesn't seem to work
