### ISSUE TITLE
Testing trained yolov8 model on multiple images

### ISSUE THREAD

**Issue by CoffeeJ0126** [ultralytics/ultralytics#10367]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have finished training my yolov8 model and i would like to test its abilities on multiple images that i have saved in a folder. I am wondering, can i test my model on all the images in one go? 

yolo task=detect mode=predict model=best.pt show=True conf=0.3 source=image.jpg line_width=1

Or should i do this for every image one by one?

**Comment by glenn-jocher** [comment]
Absolutely, you can test your YOLOv8 model on all the images in a folder in one go! Instead of specifying a single image in the source, provide the path to your folder containing the images. Simply change the `source` argument to the folder path. Here's how:

```bash
yolo task=detect mode=predict model=best.pt show=True conf=0.3 source=/path/to/your/images/ line_width=1
```

Just ensure that `/path/to/your/images/` is the correct path to your folder. This will process all the images in the folder using the settings you specified. Happy detecting! 😊

**Comment by CoffeeJ0126** [comment]
> Absolutely, you can test your YOLOv8 model on all the images in a folder in one go! Instead of specifying a single image in the source, provide the path to your folder containing the images. Simply change the `source` argument to the folder path. Here's how:
> 
> ```shell
> yolo task=detect mode=predict model=best.pt show=True conf=0.3 source=/path/to/your/images/ line_width=1
> ```
> 
> Just ensure that `/path/to/your/images/` is the correct path to your folder. This will process all the images in the folder using the settings you specified. Happy detecting! 😊

Thanks alot Glenn!, i will trying it out right now.

**Comment by glenn-jocher** [comment]
@CoffeeJ0126 you're welcome! I'm glad to help. If you have any more questions or need assistance as you go along, feel free to reach out. Enjoy testing your model, and I'm here if you need any further support. Happy detecting! 😊

**Comment by CoffeeJ0126** [comment]
Hi there, i have seem to encountered a problem while trying to test the model on a whole folder.

The command i used is as shown below 
yolo task=detect mode=predict model=best.pt show=True conf=0.3 source=D:\Username\Wood Defect\runs(Really Final)\runs\detect\train\weights\images line_width=1

It returned with this specific error code, did i incorrectly copy the file path to my images?

SyntaxError: 'Use\Wood' is not a valid YOLO argument.
