### ISSUE TITLE
val mode for classification models

### ISSUE THREAD

**Issue by tjasmin111** [ultralytics/ultralytics#10360]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I evaluate a classification model using this command, it only prints the `top1_acc` and `top5_acc` metrics for all.

`yolo classify val model=path/to/best.pt  # val custom model
`

               classes   top1_acc   top5_acc: 100%|██████████| 70/70 [00:04<00:00, 16.40it/s]
                   all      0.821      0.925

How can I get the detailed **per-class** accuracies?

**Comment by glenn-jocher** [comment]
Hello! 🌟 To get detailed **per-class** accuracies for a classification model in YOLOv8, you might need to use the Python API. The CLI provides a summary of the overall results, but for more detailed metrics like per-class accuracies, the Python approach allows for greater flexibility and detailed analysis.

Here's a quick example of how you might start accessing per-class accuracies using Python:

```python
from ultralytics import YOLO, Classify

# Load your model
model = Classify('path/to/best.pt')

# Run validation
results = model.val()

# Accessing the detailed results
for class_id, metrics in enumerate(results.metrics['per_class']):
    print(f"Class ID: {class_id}, Accuracy: {metrics['accuracy']}")
```

This example assumes that the `results` object holds per-class metrics in a detailed manner. Adapt this snippet to fit your specific needs, especially focusing on how the `results` object structures its data. Note that the actual implementation may depend on the specific outputs of your model's validation method. Happy coding! ✨

**Comment by tjasmin111** [comment]
Thanks. 2 questions:

1. How can I measure F1, Precision and Recall?
2. What does Accuracy represent here? Is it F1?

**Comment by glenn-jocher** [comment]
Hi there! 🌈 Let's address your queries:

1. **Measuring F1, Precision, and Recall:**
   Currently, YOLOv8 focuses on top-1 and top-5 accuracies for classification tasks. To compute F1, Precision, and Recall, you'd typically need the true positives, false positives, and false negatives from your predictions. This detailed level of evaluation isn't directly available through the YOLOv8 `Classify` class for classification tasks, but you can manually calculate these metrics if you compare predictions with ground truths.

2. **About Accuracy:**
   Here, accuracy refers to the proportion of correct predictions (both top-1 and top-5 accuracies) among the total number of cases evaluated. It doesn't equate to the F1 score. The F1 score is a harmonic mean of Precision and Recall, offering a balance between them, especially useful when the class distribution is uneven.

Regarding the error from the code snippet, my apologies for the confusion earlier. It seems there was a misunderstanding in accessing metric details. The YOLOv8 framework underwent several updates, and it's essential to rely on the official documentation for the most accurate and updated ways to validate models. For classification models, the primary metrics provided are top-1 and top-5 accuracies, directly obtained from the model's validation results without accessing a `.metrics` attribute.

Here's a simpler way to use and understand the provided `top1` and `top5` accuracies:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('path/to/best.pt')

# Validate your model
results = model.val()

# Accessing top-1 and top-5 accuracies directly
print(f"Top-1 Accuracy: {results.top1}")
print(f"Top-5 Accuracy: {results.top5}")
```

This should work without running into the issue you encountered. Again, apologies for the initial confusion and thank you for bringing it to our attention! Happy coding! 🚀

**Comment by tjasmin111** [comment]
Ah too bad cls only has top1 and top5. But can we at least get the per-class top1 accuracies? Any ways to get that?

**Comment by glenn-jocher** [comment]
Hi there! 👋 Absolutely, you can get the per-class top-1 accuracies, but you'll need to script this manually since it's not directly provided by the YOLOv8 `Classify.val()` method. Here's a quick way to do it in Python using a loop to compare your model's predictions with the ground truth labels:

```python
from ultralytics import YOLO
import numpy as np

# Load your model
model = YOLO('path/to/best.pt')

# Assuming you have your data loaded as 'dataset'
# And it's a list of tuples like [(img, class_idx), ...]
predictions, targets = [], []
for img, class_idx in dataset:
    pred = model.predict(img)[0]  # Getting the top prediction
    predictions.append(pred)
    targets.append(class_idx)

# Calculating per-class accuracies
unique_classes = np.unique(targets)
accuracies = {}
for cls in unique_classes:
    cls_indices = [i for i, x in enumerate(targets) if x == cls]
    cls_predictions = [predictions[i] for i in cls_indices]
    cls_targets = [targets[i] for i in cls_indices]
    accuracies[cls] = np.mean(np.array(cls_predictions) == np.array(cls_targets))

print("Per-class Top-1 Accuracies:", accuracies)
```

Remember to adjust this snippet to match your dataset structure and model output. This should give you a good starting point to get those accuracies! 🚀
