### ISSUE TITLE
How to obtain real-time video stream addresses after video monitoring using RTSP prediction

### ISSUE THREAD

**Issue by WWTBNBWN** [ultralytics/ultralytics#10364]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, may I ask a question.
I want to use YOLOv8 to predict the camera's real-time video interview. My relevant code is:

Source=“ rtsp://admin:qazwsx2022 @192.168.21.128:554/Streaming/Channels/1“
Results=model. predict (source, show=True, save=False, stream=True, conf=0.3)

I found that the pop-up window shows a very low real-time video delay after prediction, and the effect is very good. I want to transfer the predicted video stream address to a browser where I can view the real-time predicted video. How to operate it?
I have looked at some solutions to use ffmpeg streaming, but the results are not ideal. One is that after a period of time, it will prompt that there is insufficient memory, and the other is that after a period of time, the streaming delay is very high. May I ask if you have any good plans? Thank you. Looking forward to your reply

**Comment by glenn-jocher** [comment]
Hello! 😊

I'm glad to hear you're seeing great results with YOLOv8 on your real-time video streams! For streaming the predicted video to a web browser, one effective approach is using Flask, which is a lightweight Python web framework. Here's a simplified example to get you started:

```python
from flask import Flask, Response
from ultralytics import YOLO
import cv2

app = Flask(__name__)

def generate_frames(source):
    model = YOLO('yolov8n.pt')  # Load your model
    cap = cv2.VideoCapture(source)
    
    while True:
        success, frame = cap.read()
        if not success:
            break
        else:
            # Make predictions
            results = model.predict(frame, conf=0.3)
            # Convert results to image
            frame = results[0].render()[0]
            _, buffer = cv2.imencode('.jpg', frame)
            frame = buffer.tobytes()
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')
 @WWTBNBWN.route('/video')
def video():
    source = "rtsp://admin:qazwsx2022@192.168.21.128:554/Streaming/Channels/1"
    return Response(generate_frames(source), mimetype='multipart/x-mixed-replace; boundary=frame')

if __name__ == '__main__':
    app.run(debug=True)
```

This Flask app creates an endpoint at `/video` that streams the processed video frames as a continuous stream of JPEG images. You can view the stream by navigating to `http://localhost:5000/video` in your web browser.

For scenarios with memory issues or high latency, ensuring efficient memory management and possibly adjusting streaming parameters may help. Yet, keep in mind that real-time video processing can be demanding, and hardware limitations might play a significant role in the performance you observe.

I hope this helps! Let me know if you have more questions.

**Comment by WWTBNBWN** [comment]
> Hello! 😊
> 
> I'm glad to hear you're seeing great results with YOLOv8 on your real-time video streams! For streaming the predicted video to a web browser, one effective approach is using Flask, which is a lightweight Python web framework. Here's a simplified example to get you started:
> 
> ```python
> from flask import Flask, Response
> from ultralytics import YOLO
> import cv2
> 
> app = Flask(__name__)
> 
> def generate_frames(source):
>     model = YOLO('yolov8n.pt')  # Load your model
>     cap = cv2.VideoCapture(source)
>     
>     while True:
>         success, frame = cap.read()
>         if not success:
>             break
>         else:
>             # Make predictions
>             results = model.predict(frame, conf=0.3)
>             # Convert results to image
>             frame = results[0].render()[0]
>             _, buffer = cv2.imencode('.jpg', frame)
>             frame = buffer.tobytes()
>             yield (b'--frame\r\n'
>                    b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')
>  @WWTBNBWN.route('/video')
> def video():
>     source = "rtsp://admin:qazwsx2022@192.168.21.128:554/Streaming/Channels/1"
>     return Response(generate_frames(source), mimetype='multipart/x-mixed-replace; boundary=frame')
> 
> if __name__ == '__main__':
>     app.run(debug=True)
> ```
> 
> This Flask app creates an endpoint at `/video` that streams the processed video frames as a continuous stream of JPEG images. You can view the stream by navigating to `http://localhost:5000/video` in your web browser.
> 
> For scenarios with memory issues or high latency, ensuring efficient memory management and possibly adjusting streaming parameters may help. Yet, keep in mind that real-time video processing can be demanding, and hardware limitations might play a significant role in the performance you observe.
> 
> I hope this helps! Let me know if you have more questions.

First of all, thank you for your answer. Perhaps I am not very clear in my expression. I would like to obtain the stream address of the recognized video that can be directly played in the video, such as FLV, M3U8, or other addresses. thanks

**Comment by glenn-jocher** [comment]
Hello!

Ah, I see what you're aiming for now. To stream the predicted video in formats like FLV or M3U8 directly to a browser, you might want to look into more advanced streaming servers like **NGINX with the RTMP module**, or use media servers like **Wowza Streaming Engine** or **Adobe Media Server**. 

A simplified way to achieve this with NGINX and FFmpeg would involve pushing the processed frames from your application to an NGINX server configured with RTMP, which then allows you to access the stream via an FLV or M3U8 URL. Here's a high-level concept:

1. Configure NGINX with the RTMP module to accept video streams.
2. Within your Python application, after processing the frames, use FFmpeg (via subprocess or similar) to push the frames to your NGINX RTMP URL. For example:
   ```python
   import subprocess

   # Command to push frames to NGINX using FFmpeg (ensure FFmpeg is installed)
   command = [
       'ffmpeg',
       '-i', '-',  # Input from stdin
       '-c:v', 'libx264',
       '-f', 'flv',  # FLV format
       'rtmp://localhost/live/stream'  # Your NGINX RTMP URL
   ]

   # Open a subprocess with FFmpeg command, pipe in the processed frames
   p = subprocess.Popen(command, stdin=subprocess.PIPE)

   for frame in generate_frames(source):
       p.stdin.write(frame)
   ```

3. The stream can now be accessed from a URL like `http://localhost:8080/live/stream.flv` or transformed into an M3U8 playlist if your server supports HLS.

This approach requires a bit more setup, especially with NGINX and FFmpeg, but it can robustly serve your requirement to make the streams accessible directly through a browser in popular formats. Be sure to consider the performance and resource management aspect since real-time video processing and streaming can be quite resource-intensive! 😊

Hope this points you in the right direction!

**Comment by MYWpro** [comment]
> Hello! 😊
> 
> I'm glad to hear you're seeing great results with YOLOv8 on your real-time video streams! For streaming the predicted video to a web browser, one effective approach is using Flask, which is a lightweight Python web framework. Here's a simplified example to get you started:
> 
> ```python
> from flask import Flask, Response
> from ultralytics import YOLO
> import cv2
> 
> app = Flask(__name__)
> 
> def generate_frames(source):
>     model = YOLO('yolov8n.pt')  # Load your model
>     cap = cv2.VideoCapture(source)
>     
>     while True:
>         success, frame = cap.read()
>         if not success:
>             break
>         else:
>             # Make predictions
>             results = model.predict(frame, conf=0.3)
>             # Convert results to image
>             frame = results[0].render()[0]
>             _, buffer = cv2.imencode('.jpg', frame)
>             frame = buffer.tobytes()
>             yield (b'--frame\r\n'
>                    b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')
>  @WWTBNBWN.route('/video')
> def video():
>     source = "rtsp://admin:qazwsx2022@192.168.21.128:554/Streaming/Channels/1"
>     return Response(generate_frames(source), mimetype='multipart/x-mixed-replace; boundary=frame')
> 
> if __name__ == '__main__':
>     app.run(debug=True)
> ```
> 
> This Flask app creates an endpoint at `/video` that streams the processed video frames as a continuous stream of JPEG images. You can view the stream by navigating to `http://localhost:5000/video` in your web browser.
> 
> For scenarios with memory issues or high latency, ensuring efficient memory management and possibly adjusting streaming parameters may help. Yet, keep in mind that real-time video processing can be demanding, and hardware limitations might play a significant role in the performance you observe.
> 
> I hope this helps! Let me know if you have more questions.

May I ask if in this way, the backend only predicts real-time video streams when "/video" is called, and does not make predictions when not called? What should I do if I need to constantly predict real-time video streams (because I need to constantly detect certain events and issue alarm messages in a timely manner), and then display the predicted video streams on the front end when users need to view them? Thank you very much.
