### ISSUE TITLE
Changing YOLOv8 detection output

### ISSUE THREAD

**Issue by islemghod** [ultralytics/ultralytics#10374]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,
I want to change the output of the detection in YOLOV8, and other than the initial outputs, I want to add the cooordiantes of the center of the detected object . 
But I can't figure out what are all the files that I need to change to do that, so I need your help.

**Comment by glenn-jocher** [comment]
Hello! 😊

To add the coordinates of the detected object's center to YOLOv8's output, you can simply modify the post-processing step where the detections are handled. Specifically, for each detected bounding box `[x1, y1, x2, y2]`, you can calculate the center coordinates as `[(x1 + x2) / 2, (y1 + y2) / 2]`. 

Here's a quick example assuming you have a detection result `detections` with bounding box coordinates:

```python
for det in detections:
    x1, y1, x2, y2 = det['bbox']
    center_x, center_y = (x1 + x2) / 2, (y1 + y2) / 2
    print(f"Center coordinates: ({center_x}, {center_y})")
```

This snippet calculates the center coordinates of each detected object. If you're working within the Ultralytics YOLOv8 framework, you would typically add this in the section of the code where detections are parsed or right after the inference calls, depending on how you’re deploying or using the model (e.g., via Python script, CLI).

Keep in mind, depending on your specific setup or if you're looking to further process or output these center coordinates (like adding them to a file or directly integrating into the model’s output structure), you might need to modify where this snippet is placed. However, this should give you a good start towards achieving your goal!

If you have more detailed requirements or specific files you’re looking into, feel free to elaborate!
