### ISSUE TITLE
How to install project.optional-dependencies?

### ISSUE THREAD

**Issue by wux024** [ultralytics/ultralytics#10396]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to use "export", but "pip" don't auto-install some dependencies. How to install project.optional-dependencies easyly?

**Comment by glenn-jocher** [comment]
@wux024 hello! 😊 To easily install the project's optional dependencies for features like "export", you can use the following command with pip:

```bash
pip install ultralytics[yolo]
```

This will ensure all optional dependencies needed for the export functionality are installed. Let us know if you need any more help!
