### ISSUE TITLE
Add mutiples line in the line counter solution !

### ISSUE THREAD

**Issue by Rasantis** [ultralytics/ultralytics#10403]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hi ultralytics, im using the line counter solution, and i would need to add a secondary line to count people who are come/going in the other direction. how could i do that ?

**Comment by glenn-jocher** [comment]
Hi there! 👋

For adding a secondary line to count people moving in another direction using the line counter solution, you can simply define another line and apply the same counting logic to it. 

Here is a brief snippet on how you could approach it:

```python
# Assume line1 and line2 are defined with their respective points
line1 = [(x1, y1), (x2, y2)]  # First line coordinates
line2 = [(x3, y3), (x4, y4)]  # Second line coordinates

# Detect intersections with line1
for obj in objects:  # Assuming "objects" contains detected objects
    if intersects(obj, line1):  # Pseudo-function to check for intersection
        count_line1 += 1

# Detect intersections with line2
for obj in objects:
    if intersects(obj, line2):
        count_line2 += 1
```

This is a simplified approach, and the function `intersects(obj, line)` needs to be defined to check if an object intersects with the line. Also, ensure to keep track of objects already counted to avoid double counting.

Hope this helps! Feel free to reach out if you have further questions or need more details. 🚀
