### ISSUE TITLE
How to get the result's filename?

### ISSUE THREAD

**Issue by hjk789** [ultralytics/ultralytics#1041]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When iterating the results returned from a prediction over a directory, how can I get the name of the file that got a match? It seems that you can only know whether there's a match and which class got matched, but not in what image.

A temporary solution I found is not using the returned results, but enabling the save_txt and save_conf parameters and iterating the files instead, reading one by one to get the results of each image.

Is there a better way to do this? I tried relating the list returned by `listdir()` but the file order is different, as YOLO reads the images in a unique order that nothing can mimic.

**Comment by AyushExel** [comment]
@hjk789 you want the input image's file name or the saved result's file name?

**Comment by hjk789** [comment]
When using the `predict()` function it returns the results. To get the class number and the confidence you can do something like

```
results = YOLO("best.pt").predict(source=".")

for result in results:
    for cls, conf in zip(result.boxes.cls, result.boxes.conf)
        print(cls, conf)
```

What I would like to know is if there's any way to do something like 
```
for cls, conf, imgname in zip(result.boxes.cls, result.boxes.conf, result.filename)
    print(cls, conf, imgname)
```

**Comment by glenn-jocher** [comment]
@AyushExel this is what we talked about before, I also mentioned that YOLOv5 AutoShape already supports this by default here with `self.files`
https://github.com/ultralytics/yolov5/blob/7a972e86c4e5009830d5e6faacadfe6e1ed2efff/models/common.py#L722-L740

**Comment by AyushExel** [comment]
https://github.com/ultralytics/ultralytics/pull/1064
@hjk789 This PR should fix your issue. result.path will give you the path to input the image

**Comment by hjk789** [comment]
@AyushExel I tested here and the path is always `/`.

**Comment by AyushExel** [comment]
<img width="1030" alt="Screenshot 2023-02-21 at 9 00 03 AM" src="https://user-images.githubusercontent.com/15766192/220240366-44935971-bad9-4642-a188-1a19913e3dfb.png">
It works for me

**Comment by hjk789** [comment]
@AyushExel  Yeah, it was on my side, I was printing only the first character. I fixed it and now it's working as intended.

**Comment by seeseeyour** [comment]
> @hjk789您想要输入图像的文件名还是保存结果的文件名？

how to get the saved result's file name? Thanks!
