### ISSUE TITLE
Object ID assignment problem

### ISSUE THREAD

**Issue by AlaaArboun** [ultralytics/ultralytics#10422]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm encountering an issue with my object tracking algorithm, particularly with ID assignment. Despite having the same object in the same position, the algorithm consistently assigns new IDs to them.

Here's a simplified overview of my process:

I convert detections into a format suitable for matching with existing tracks.
I convert existing tracks into a format compatible with detection matching.
I match detections with tracks based on bounding box intersection over union (IOU).
After post-processing, which includes confidence thresholding and non-maximum suppression (NMS), I update the tracks and attempt to match detections with tracks again.
However, even though the same objects are detected in subsequent frames, the algorithm assigns new IDs to them instead of updating the existing IDs.

I've checked the integrity of my data structures and the logic of my code, but I'm unable to pinpoint the exact issue. Could someone please provide insights or suggestions on what might be causing this behavior and how I could resolve it?

Thanks in advance for your help! 
bash ```
 class BYTETrackerArgs:
    track_thresh: float = 0.25

   
    track_buffer: int = 30
    match_thresh: float = 0.7
    aspect_ratio_thresh: float = 3.0
    min_box_area: float = 1.0
    mot20: bool = False
   
   # converts Detections into format that can be consumed by match_detections_with_tracks function
    def detections2boxes(self,detections: Detections) -> np.ndarray:
        return np.hstack((
            detections.xyxy,
            detections.confidence[:, np.newaxis]
        ))

    # converts List[STrack] into format that can be consumed by match_detections_with_tracks function
    def tracks2boxes(self,tracks: List[STrack]) -> np.ndarray:
        return np.array([
            track.tlbr
            for track
            in tracks
        ], dtype=float)

    # matches our bounding boxes with predictions
    def match_detections_with_tracks(self,
        detections: Detections,
        tracks: List[STrack]
    ) -> Detections:
        if not np.any(detections.xyxy) or len(tracks) == 0:
            return np.empty((0,))

        tracks_boxes =self.tracks2boxes(tracks=tracks) 
        iou = box_iou_batch(tracks_boxes, detections.xyxy)
        track2detection = np.argmax(iou, axis=1)

        tracker_ids = [None] * len(detections)

        for tracker_index, detection_index in enumerate(track2detection):
            if iou[tracker_index, detection_index] != 0:
                tracker_ids[detection_index] = tracks[tracker_index].track_id

        return tracker_ids
   
    def postprocess(self, input_image, output):
        boxes = []
        scores = []
        class_ids = []

        # Vectorized operations
        output = np.transpose(output, (0, 2, 1))
        x, y, w, h = output[:, :, :4].T
        x1 = x - w / 2
        y1 = y - h / 2
        boxes = np.column_stack([x1, y1, x1 + w, y1 + h])  # [x_min, y_min, x_max, y_max]
        class_probs = output[:, :, 4:]

        # Find class IDs and scores
        idx = np.argmax(class_probs, axis=2)
        max_probs = np.max(class_probs, axis=2)
        scores = max_probs.flatten()
        class_ids = idx.flatten()

        # Apply confidence threshold
        high_confidence_indices = np.where(scores > self.confidence_thres)[0]
        boxes = boxes[high_confidence_indices]
        scores = scores[high_confidence_indices]
        class_ids = class_ids[high_confidence_indices]
        detections = Detections(xyxy=boxes, confidence=scores, class_id=class_ids.astype(int))

        # Perform Non-Maximum Suppression
        nms_indices = cv2.dnn.NMSBoxes(boxes.tolist(), scores.tolist(), self.confidence_thres, self.iou_thres)
        boxes = [boxes[i] for i in nms_indices]
        scores = [scores[i] for i in nms_indices]
        class_ids = [class_ids[i] for i in nms_indices]

        # Update detections with NMS results
        detections.xyxy = np.array(boxes)
        detections.confidence = np.array(scores)
        detections.class_id = np.array(class_ids)

        # Rest of your code...
        tracks = self.tracker.update(
            output_results=self.detections2boxes(detections=detections),
            img_info=input_image.shape,
            img_size=input_image.shape
        )
        print("tracks :", tracks)

        tracker_id = self.match_detections_with_tracks(detections=detections, tracks=tracks)
        detections.tracker_id = np.array(tracker_id)
        print("detections :", detections)

        for box, confidence, class_id, tracker_id in zip(detections.xyxy, detections.confidence, detections.class_id,
                                                        detections.tracker_id):
            # Process each detection
            # Draw the bounding box
            self.draw_detections(input_image, box, confidence, class_id, tracker_id)

        return input_image
    
output.shape =>(1,84,1344)
                 
      
tracks : [OT_2629_(1-1), OT_2630_(1-1), OT_2631_(1-1), OT_2632_(1-1), OT_2633_(1-1), OT_2634_(1-1), OT_2635_(1-1), OT_2636_(1-1), OT_2637_(1-1), OT_2638_(1-1), OT_2639_(1-1), OT_2640_(1-1), OT_2641_(1-1), OT_2642_(1-1), OT_2643_(1-1), OT_2644_(1-1), OT_2645_(1-1), OT_2646_(1-1), OT_2647_(1-1)]
detections : Detections(xyxy=array([[   0.043394,     0.53075,     0.34382,     0.99139],
       [   0.053408,     0.53075,     0.34715,     0.99139],
       [   0.046732,     0.53075,     0.34048,     0.99139],
       [   0.043394,     0.52741,     0.34382,     0.99473],
       [   0.053408,     0.53075,     0.34715,     0.99139],
       [   0.046732,     0.53075,     0.34048,     0.99139],
       [   0.046732,     0.53075,     0.34048,      1.0047],
       [   0.053408,     0.53075,     0.34715,      1.0047],
       [   0.046732,     0.54076,     0.34048,      1.0081],
       [   0.043394,     0.52741,     0.34382,     0.99473],
       [     0.3338,      0.3338,      1.0014,      1.0014],
       [    0.34048,      0.3338,     0.99473,      1.0014],
       [    0.33714,      0.3338,     0.98472,      1.0014],
       [     0.3338,     0.33046,      1.0014,      1.0047],
       [    0.33714,     0.33046,     0.99807,      1.0047],
       [    0.33714,     0.33046,     0.99807,      1.0047],
       [     0.3338,     0.32379,      1.0014,     0.99807],
       [    0.34715,     0.32379,      1.0014,     0.99807],
       [    0.34048,     0.32713,     0.99473,     0.98138],
       [    0.33714,      0.3338,     0.99807,      1.0014]], dtype=float32), mask=None, confidence=array([    0.87456,     0.84118,     0.20028,     0.80113,     
0.80113,     0.69431,     0.80113,     0.80113,     0.69431,     0.74772,     0.87456,     0.80113,     0.74772,     0.87456,     0.87456,     0.84118,     0.90127,     0.90127,     0.84118,     0.87456], dtype=float32), class_id=array([39, 39, 39, 39, 39, 39, 39, 39, 39, 39,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]), tracker_id=array([2629, 2632, 2633, 2637, None, None, 2634, 2635, 2636, None, 2638, 2639, 2640, 2641, 2643, None, 2644, 2645, 2646, 2647], dtype=object), data={})        
---

**Comment by glenn-jocher** [comment]
@AlaaArboun it looks like your ID matching algorithm (`match_detections_with_tracks`) assigns new IDs for two main reasons:

1. **IoU Thresholding**: When the IoU between a track and a detection doesn't meet the threshold, even if it's the highest among all matches, it results in creating a new ID. This might be too strict in some cases, especially in fast-moving objects or when the detection slightly misses the perfect bounding box due to model inaccuracies.

2. **Max Argument Indexing with `np.argmax`**: This method will always return an index (even if the highest IoU is very low), potentially leading to incorrect associations between tracks and detections. Consider using a more dynamic matching threshold that can adjust based on detection confidence or the dynamics of the scene.

To improve your tracking and ID consistency, consider the following adjustments:

- **Dynamic IoU Thresholding**: Instead of a fixed `match_thresh`, dynamically adjust the threshold based on detection confidence or the average IoU of recent frames. This can help to be more lenient in tougher scenarios and stricter when the model is more confident.
  
- **Use `np.where` for Conditional Indexing**: After computing IoUs and before assigning IDs, filter out matches where the IoU is below a certain threshold. This prevents any match with an insufficiently high IoU from being considered:

```python
iou = box_iou_batch(tracks_boxes, detections.xyxy)
# Get matching pairs with sufficient IoU
valid_pairs = np.where(iou > self.match_thresh)

# Find IDs for valid matches
for tracker_index, detection_index in zip(*valid_pairs):
    tracker_ids[detection_index] = tracks[tracker_index].track_id
```

- **Track Management**: Incorporate mechanisms to handle lost tracks, such as age, time since last seen, or prediction-based tracking when a detection is momentarily missing.

These adjustments aim to enhance your tracker's robustness and reliability in maintaining consistent IDs across frames. If you continue to experience challenges, sharing more details or specific scenarios where it fails could help pinpoint further improvements. 🙂

**Comment by AlaaArboun** [comment]
Thanks a lot @glenn-jocher , but the problem of incrementing the ID for the object in the same location appears in the tracks output from the update function in the bytrack tracker algorithm before using the match_detections_with_tracks function.

bash ```
import argparse
from typing import List
import cv2
import numpy as np
import time
from tflite_runtime import interpreter as tflite
from tflite_runtime.interpreter import load_delegate
from ultralytics.utils import ASSETS, yaml_load
from ultralytics.utils.checks import check_yaml
import imageio
from yolox.tracker.byte_tracker import BYTETracker, STrack
from onemetric.cv.utils.iou import box_iou_batch
from yolox.tracker.byte_tracker import BYTETracker, STrack
from supervision.detection.core import Detections
import supervision as sv 

from PIL import Image
# Enable OpenCL in OpenCV if supported
cv2.ocl.setUseOpenCL(True)
import os
from tqdm import tqdm
# Declare as global variables, can be updated based trained model image size
img_width = 256
img_height = 256
import threading

class ImageLoader(threading.Thread):
    def __init__(self, path):
        threading.Thread.__init__(self)
        self.path = path
        self.image = None

    def run(self):
        if isinstance(self.path, str):
            self.image = cv2.imread(self.path)
        else:
            self.image = self.path



from yolox.tracker.byte_tracker import BYTETracker, STrack

from dataclasses import dataclass


@dataclass(frozen=True)
class BYTETrackerArgs:
    track_thresh: float = 0.5  # Increase this value to be more permissive
    track_buffer: int = 30
    match_thresh: float = 0.1  # Decrease this value to be more permissive
    aspect_ratio_thresh: float = 3.0
    min_box_area: float = 1.0
    mot20: bool = False

class Yolov8TFLite:
    def __init__(self, tflite_model, input_image, confidence_thres, iou_thres):
        """
        Initializes an instance of the Yolov8TFLite class.

        Args:
            tflite_model: Path to the TFLite model.
            input_image: Path to the input image.
            confidence_thres: Confidence threshold for filtering detections.
            iou_thres: IoU (Intersection over Union) threshold for non-maximum suppression.
        """

        self.tflite_model = tflite_model
        self.input_image = input_image
        self.confidence_thres = confidence_thres
        self.iou_thres = iou_thres
        self.image_cache = {}
        #self.byte_tracker = BYTETracker(BYTETrackerArgs())
        # Initialize the BYTETracker
        self.tracker = BYTETracker(BYTETrackerArgs(
                track_thresh=0.5,
                match_thresh=0.5
            ))

        # Load the class names from the COCO dataset
        self.classes = yaml_load(check_yaml("coco128.yaml"))["names"]

        # Generate a color palette for the classes
        self.color_palette = np.random.uniform(0, 255, size=(len(self.classes), 3))
        # Initialize interpreter and input shape
        self.make_interpreter()

    def make_interpreter(self):
        # Create an interpreter for the TFLite model
        interpreter = tflite.Interpreter(model_path=self.tflite_model, experimental_delegates=[load_delegate('edgetpu.dll')])
        self.model = interpreter
        interpreter.allocate_tensors()

        # Get the model inputs
        self.input_details = interpreter.get_input_details()
        self.output_details = interpreter.get_output_details()
        self.input_shape = self.input_details[0]["shape"]

        # Access quantization parameters and update accordingly
        self.input_zero = self.input_details[0]['quantization'][1]
        self.input_scale = self.input_details[0]['quantization'][0]
        self.output_zero = self.output_details[0]['quantization'][1]
        self.output_scale = self.output_details[0]['quantization'][0]

        # If the model isn't quantized then these should be zero
        # Check against small epsilon to avoid comparing float/int
        if self.input_scale < 1e-9:
            self.input_scale = 1.0

        if self.output_scale < 1e-9:
            self.output_scale = 1.0

    def get_expected_input_size(self):
        """
        Returns the expected size of the input image tensor.

        Returns:
            tuple: Expected height and width of the input image tensor.
        """
        return self.input_shape[1], self.input_shape[2]

    def draw_detections(self, img, box, score, class_id,tracked_id):
        # Extract the coordinates of the bounding box
        x1, y1, w, h = box

        # Scale up the coordinates
        x1 *= img.shape[1]
        y1 *= img.shape[0]
        w *= img.shape[1]
        h *= img.shape[0]

        # Retrieve the color for the class ID
        color = self.color_palette[class_id]

        # Draw the bounding box on the image
        cv2.rectangle(img, (int(x1), int(y1)), (int(x1 + w), int(y1 + h)), color, 2)

        # Create the label text with class name and score
        label = f"{self.classes[class_id]}: {score:.2f} #{tracked_id}"

        # Calculate the dimensions of the label text
        (label_width, label_height), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 1)

        # Calculate the position of the label text
        label_x = x1
        label_y = y1 - 10 if y1 - 10 > label_height else y1 + 10

        # Draw a filled rectangle as the background for the label text
        cv2.rectangle(
            img,
            (int(label_x), int(label_y - label_height)),
            (int(label_x + label_width), int(label_y + label_height)),
            color,
            cv2.FILLED,
        )

        # Draw the label text on the image
        cv2.putText(img, label, (int(label_x), int(label_y)), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1, cv2.LINE_AA)

   
   

    def load_image(self, input_image):
        self.image_loader = ImageLoader(input_image)
        self.image_loader.start()

    def get_image(self):
        if self.image_loader:
            self.image_loader.join()
            return self.image_loader.image
        return None
    def preprocess(self):
        """
        Preprocesses the input image before performing inference.

        Returns:
            image_data: Preprocessed image data ready for inference.
        """

        read_start_time = time.time()
        
       # Get the loaded image from the ImageLoader thread
        img = self.get_image()
        if img is None:
            raise ValueError("Input image not loaded.")

        read_end_time = time.time()
        read_img_time = read_end_time - read_start_time

        # Resize the image using OpenCV
        resize_start_time = time.time()
        if img.shape[:2] != (self.input_shape[1], self.input_shape[2]):
            # Resize the input image to match the model's input shape
            img = cv2.resize(img, (self.input_shape[1], self.input_shape[2]))

        resize_end_time = time.time()
        resize_time = resize_end_time - resize_start_time

        # Convert image to float32 and normalize
        normalize_start_time = time.time()
        img = img.astype(float) / 255.0
        
        normalize_end_time = time.time()
        normalize_time = normalize_end_time - normalize_start_time

        # Apply scale and zero point quantization
        quantize_start_time = time.time()
        img = (img / self.input_scale) + self.input_zero
        quantize_end_time = time.time()
        quantize_time = quantize_end_time - quantize_start_time

        # Convert to the desired data type (int8)
        convert_start_time = time.time()
      
        img = img[np.newaxis].astype(np.int8)
        convert_end_time = time.time()
        convert_time = convert_end_time - convert_start_time

        # Add batch dimension
        #img = np.expand_dims(img, axis=0)

        return img, read_img_time, resize_time, normalize_time, quantize_time, convert_time


   # converts Detections into format that can be consumed by match_detections_with_tracks function
    def detections2boxes(self,detections: Detections) -> np.ndarray:
        return np.hstack((
            detections.xyxy,
            detections.confidence[:, np.newaxis]
        ))


    # converts List[STrack] into format that can be consumed by match_detections_with_tracks function
    def tracks2boxes(self,tracks: List[STrack]) -> np.ndarray:
        return np.array([
            track.tlbr
            for track
            in tracks
        ], dtype=float)


    
    def match_detections_with_tracks(self,
        detections: Detections,
        tracks: List[STrack]
    ) -> Detections:
        if not np.any(detections.xyxy) or len(tracks) == 0:
            return np.empty((0,))

        tracks_boxes = self.tracks2boxes(tracks=tracks)
        print("tracks_boxes :" ,tracks_boxes)
        print("detection boxes",detections.xyxy)
        iou = box_iou_batch(tracks_boxes, detections.xyxy)
        print("iou" , iou)
        valid_pairs = np.where(iou > 0.3)

        tracker_ids = [None] * len(detections)

        for tracker_index, detection_index in zip(*valid_pairs):
            tracker_ids[detection_index] = tracks[tracker_index].track_id

        return tracker_ids

    def compute_dynamic_threshold(self, detections: Detections, iou: np.ndarray) -> float:
        # Compute dynamic threshold based on detection confidence or average IoU
        # Adjust the logic based on your specific requirements
        confidence_threshold = 0.5
        average_iou = np.mean(iou)
        match_thresh = confidence_threshold * average_iou

        return match_thresh
   
    def postprocess(self, input_image, output):
        boxes = []
        scores = []
        class_ids = []
        print(output.shape)

        # Vectorized operations
        output = np.transpose(output, (0, 2, 1))
        x, y, w, h = output[:, :, :4].T
        x1 = x - w / 2
        y1 = y - h / 2
        boxes = np.column_stack([x1, y1, x1 + w, y1 + h])  # [x_min, y_min, x_max, y_max]
        print("boxes",boxes)
        class_probs = output[:, :, 4:]

        # Find class IDs and scores
        idx = np.argmax(class_probs, axis=2)
        max_probs = np.max(class_probs, axis=2)
        scores = max_probs.flatten()
        class_ids = idx.flatten()

        # Apply confidence threshold
        high_confidence_indices = np.where(scores > self.confidence_thres)[0]
        boxes = boxes[high_confidence_indices]
        scores = scores[high_confidence_indices]
        class_ids = class_ids[high_confidence_indices]
        detections = Detections(xyxy=boxes, confidence=scores, class_id=class_ids.astype(int))

        # Perform Non-Maximum Suppression
        nms_indices = cv2.dnn.NMSBoxes(boxes.tolist(), scores.tolist(), self.confidence_thres, self.iou_thres)
        boxes = [boxes[i] for i in nms_indices]
        scores = [scores[i] for i in nms_indices]
        class_ids = [class_ids[i] for i in nms_indices]

        # Update detections with NMS results
        detections.xyxy = np.array(boxes)
        detections.confidence = np.array(scores)
        detections.class_id = np.array(class_ids)
        # Scale up the coordinates
        """detections.xyxy[:, 0] *= input_image.shape[1]  # x_min
        detections.xyxy[:, 1] *= input_image.shape[0]  # y_min
        detections.xyxy[:, 2] *= input_image.shape[1]  # x_max
        detections.xyxy[:, 3] *= input_image.shape[0]  # y_max"""

        # Rest of your code...
        tracks = self.tracker.update(
            output_results=self.detections2boxes(detections=detections),
            img_info=input_image.shape,
            img_size=input_image.shape
        )
        print("tracks :", tracks)

        tracker_id = self.match_detections_with_tracks(detections=detections, tracks=tracks)
        detections.tracker_id = np.array(tracker_id)
        print("detections :", detections)

        for box, confidence, class_id, tracker_id in zip(detections.xyxy, detections.confidence, detections.class_id,
                                                        detections.tracker_id):
            # Process each detection
            # Draw the bounding box
            self.draw_detections(input_image, box, confidence, class_id, tracker_id)

        return input_image
    

                
                        
                            

            

    def main(self):
        """
        Performs inference using a TFLite model and returns the output image with drawn detections.

        Returns:
            output_img: The output image with drawn detections.
            
        """
        # Load the input image in a separate thread
        self.load_image(self.input_image)


        # Preprocess the image data and measure the time
        start_preprocess = time.time()
        img_data,read_img_time, resize_time, normalize_time, quantize_time, convert_time= self.preprocess()
        
        end_preprocess = time.time()

        preprocess_time = end_preprocess - start_preprocess

        # Set the input tensor to the interpreter
        self.model.set_tensor(self.input_details[0]["index"], img_data)

        # Run inference and measure the time
        # Run inference and measure the time
        start_inference = time.time()
        self.model.invoke()
        end_inference = time.time()
       
        inference_time = end_inference - start_inference
        # Get the output tensor from the interpreter
        #output = self.model.get_tensor(self.output_details[0]["index"])
       
        
        output = (self.output_scale * ((self.model.get_tensor(self.output_details[0]["index"])).astype('float32') -self.output_zero))

        # Perform post-processing on the outputs to obtain output image.
        # Get the input image from the ImageLoader thread
        input_image = self.get_image()
        if input_image is None:
            raise ValueError("Input image not loaded.")

        # Measure the time for post-processing
        start_postprocess = time.time()
        output_image = self.postprocess(input_image, output)
        end_postprocess = time.time()

        postprocess_time = end_postprocess - start_postprocess

         # Display times for each step
        print("---")
        print("Read Image Time: {:.5f} ms".format(read_img_time*1000))
        print("Resize Time: {:.5f} ms".format(resize_time*1000))
        print("Normalize Time: {:.5f} ms".format(normalize_time*1000))
        print("Quantize Time: {:.5f} ms".format(quantize_time*1000))
        print("Convert Time: {:.5f} ms".format(convert_time*1000))
        print("Preprocess Time: {:.5f} ms".format(preprocess_time*1000))
        print("Inference Time: {:.5f} ms".format(inference_time*1000))
        print("Postprocess Time: {:.5f} ms".format(postprocess_time*1000))


        return output_image,preprocess_time,postprocess_time,inference_time



if __name__ == "__main__":
    # Create an argument parser to handle command-line arguments
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--model", type=str, default="yolov8n_full_integer_quant.tflite", help="Input your TFLite model."
    )
    parser.add_argument("--input-type", type=str, default="image", choices=["image", "video", "camera"],
                        help="Type of input (image, video, or camera)")
    parser.add_argument("--input-path", type=str, default=str(ASSETS / "bus.jpg"),
                        help="Path to input image or video. Ignored if input-type is camera.")
    parser.add_argument("--conf-thres", type=float, default=0.2, help="Confidence threshold")
    parser.add_argument("--iou-thres", type=float, default=0.5, help="NMS IoU threshold")
    args = parser.parse_args()



    result_dir = "result_images"
    if not os.path.exists(result_dir):
        os.makedirs(result_dir)

    # Initialize Yolov8TFLite object
    detection = Yolov8TFLite(args.model, args.input_path, args.conf_thres, args.iou_thres)
    if args.input_type == "image":
        

        # Nombre d'itérations pour le test
        iterations = 100

        # Initialisez les tableaux numpy pour suivre le temps total d'inférence et le nombre total de frames
        total_time = np.zeros(iterations)
        total_fps = np.zeros(iterations)
        total_preprocess_time = np.zeros(iterations)
        total_postprocess_time = np.zeros(iterations)
        total_inference_time = np.zeros(iterations)

        # Initialize progress_bar outside the loop
        progress_bar = tqdm(total=iterations, desc="Performing test run", unit=" iterations")

        # Temps de début avant la boucle
        start_time_all = time.time()

        for i in range(iterations):
            start_time = time.time()
            output_image, preprocess_time, postprocess_time, inference_time = detection.main()  # Perform inference
            end_time = time.time()

            total_time[i] = end_time - start_time  # Correct assignment to the numpy array
            fps = 1 / total_time[i]  # Calculate FPS for this iteration
            total_fps[i] = fps
            total_time[i] *= 1000  # Convert to milliseconds

            # Update progress bar
            progress_bar.update(1)

            # Track preprocess and postprocess times
            total_preprocess_time[i] = preprocess_time
            total_postprocess_time[i] = postprocess_time
            total_inference_time[i]=inference_time

        # Temps de fin après la boucle
        end_time_all = time.time()

        # Close the progress bar
        progress_bar.close()

        # Calculate average inference time and FPS
        average_total_time = np.mean(total_time)
        average_fps = np.mean(total_fps)

        average_preprocess_time = np.mean(total_preprocess_time)
        average_postprocess_time = np.mean(total_postprocess_time)
        average_inference_time=np.mean(total_inference_time)

        print("Average total Time:", average_total_time, "ms")
        print("Average inference Time:", average_inference_time*1000, "ms")

        print("Average FPS:", average_fps)
        
        print("Average Preprocess Time:", average_preprocess_time * 1000, "ms")
        print("Average Postprocess Time:", average_postprocess_time*1000, "ms")

        # Display the last output image
        cv2.imshow("Output", output_image)
        cv2.waitKey(0)

        # Save annotated image
        output_path = os.path.join(result_dir, os.path.basename(args.input_path))
        cv2.imwrite(output_path, output_image)
        print("Annotated image saved at:", output_path)

        
    elif args.input_type == "video":
        cap = cv2.VideoCapture(args.input_path)

        while cap.isOpened():
            ret, frame = cap.read()
            if not ret:
                break
            detection = Yolov8TFLite(args.model, frame, args.conf_thres, args.iou_thres)
            output_image, preprocess_time, postprocess_time, inference_time = detection.main()
           
            cv2.imshow("Output", output_image)
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break
        cap.release()
        cv2.destroyAllWindows()

    elif args.input_type == "camera":
        fps =30
        #cap = cv2.VideoCapture(0)  # 0 for default camera, change if needed
        cap = imageio.get_reader('<video0>',  format='ffmpeg', ffmpeg_params=['-video_size', '640x480'])
        #cap = imageio.get_reader('<video1>', format='ffmpeg', ffmpeg_params=['-framerate', str(fps)])



        try:
            for frame in cap:
                # Convert the frame to BGR color format expected by OpenCV
                frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
                
                detection = Yolov8TFLite(args.model, frame, args.conf_thres, args.iou_thres)
                start_time = time.time()
                output_image, preprocess_time, postprocess_time, inference_time = detection.main()
                end_time = time.time()

                fps = 1 / (end_time - start_time)
                
                print("FPS:", fps)
                # Display FPS and resolution on the frame
                # Note: If you want to display text, output_image should be used
                # Ensure output_image is in the correct format and not None
                if output_image is not None:
                    cv2.putText(output_image, f"FPS: {fps:.2f}", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
                    cv2.imshow("Output", output_image)
                else:
                    cv2.imshow("Output", frame)

                if cv2.waitKey(1) & 0xFF == ord('q'):
                    break
        except Exception as e:
            print(f"Error: {e}")
        finally:
            # Cleanup
            cap.close()
            cv2.destroyAllWindows()                                                                                                                                                                         tracks : [OT_18_(1-1)]
tracks_boxes : [[   0.003338     0.13686     0.98472     0.99807]]
detection boxes [[   0.003338     0.13686     0.98472     0.99807]]
iou [[          1]]
detections : Detections(xyxy=array([[   0.003338,     0.13686,     0.98472,     0.99807]], dtype=float32), mask=None, confidence=array([    0.95467], dtype=float32), class_id=array([0], dtype=int64), tracker_id=array([18]), data={})
---

(1, 84, 1344)
boxes [[   0.006676           0     0.03338    0.040056]
 [   0.010014    0.006676     0.13686    0.046732]
 [    0.01669    0.003338     0.17024     0.05007]
 ...
 [   0.013352     0.13352      0.9747      1.0014]
 [   0.013352     0.77776      0.9747     0.99807]
 [   -0.12684     0.82115      1.0615      1.0081]]
tracks : [OT_19_(1-1)]
tracks_boxes : [[   0.003338     0.14687     0.98472      1.0014]]
detection boxes : [[   0.003338     0.14687     0.98472      1.0014]]
iou : [[          1]]
detections : Detections(xyxy=array([[   0.003338,     0.14687,     0.98472,      1.0014]], dtype=float32), mask=None, confidence=array([    0.95467], dtype=float32), class_id=array([0], dtype=int64), tracker_id=array([19]), data={})
---


(1, 84, 1344)
boxes [[   0.006676    0.003338    0.046732     0.05007]
 
tracks : [OT_20_(1-1)]
tracks_boxes : [[   0.013352     0.14687      0.9747      1.0014]]
detection boxes : [[   0.013352     0.14687      0.9747      1.0014]]
iou : [[          1]]
detections : Detections(xyxy=array([[   0.013352,     0.14687,      0.9747,      1.0014]], dtype=float32), mask=None, confidence=array([    0.95467], dtype=float32), class_id=array([0], dtype=int64), tracker_id=array([20]), data={})
---

(1, 84, 1344)
boxes [[   0.003338           0    0.036718    0.040056]
 [   0.006676    0.010014     0.11349    0.043394]
 [  -0.003338    0.006676     0.16356    0.046732]
 ...
 [   0.013352     0.13686      0.9747     0.99807]
 [   0.010014     0.76775     0.96469     0.99473]
 [   -0.16356     0.80113      1.0448      1.0014]]
tracks : [OT_21_(1-1)]
tracks_boxes : [[-5.5511e-17     0.13686      0.9747     0.99807]]
detection boxes [[          0     0.13686      0.9747     0.99807]]
iou : [[          1]]
detections : Detections(xyxy=array([[          0,     0.13686,      0.9747,     0.99807]], dtype=float32), mask=None, confidence=array([    0.95467], dtype=float32), class_id=array([0], dtype=int64), tracker_id=array([21]), data={})
---

**Comment by glenn-jocher** [comment]
@AlaaArboun hey there! It sounds like the challenge you're facing with the BYTETRACK tracker assigning new IDs, even before employing `match_detections_with_tracks`, might stem from how the tracker is initializing and updating tracks versus detections. A couple of thoughts come to mind: 

- Correctly tuning **BYTETrackerArgs**: Sometimes, fine-tuning the parameters (e.g., `track_thresh`, `match_thresh`) based on your specific dataset and scenario can play a significant role. Notably, the `track_thresh` controls how likely we are to keep a track, and `match_thresh` affects how we decide matches based on IoUs.

- Unique IDs for each detection: If each detection is consistently being assigned a new ID, it might be worthwhile to examine how the tracker manages and maintains its list of active tracks. There could be clues in behaviors like prematurely ending tracks or not adequately accounting for temporal consistency.

- Spatial and Temporal Consistencies: Ensuring the tracker sufficiently leverages both spatial (IoU, bbox sizes) and temporal (movement patterns, velocities) consistencies could help mitigate abrupt ID changes. 

Given the problem appears before `match_detections_with_tracks`, focusing on how tracks are initialized, updated, and maintained based on detections within the `BYTETracker` itself could yield solutions. Happy to delve deeper if more specifics are shared! Keep up the great work! 🚀
