### ISSUE TITLE
ultralytics mess up camera with openCV

### ISSUE THREAD

**Issue by mgabell** [ultralytics/ultralytics#10437]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Install

### Bug

I have a Jetson AGX Orin and install Jetpack 5.1.2 (must have for deepstream)
This include DS 6.3
Additional installation packages:

```
sudo apt install -y libgstrtspserver-1.0-0
sudo apt install -y libjansson4

sudo apt install -y python3-gst-1.0
sudo apt install -y python-gi-dev
sudo apt install -y git libglib2.0-dev
sudo apt install -y libgirepository1.0-dev
sudo apt install -y libcairo2-dev
sudo apt install -y python3-pip

export TORCH_INSTALL=https://developer.download.nvidia.com/compute/redist/jp/v512/pytorch/torch-2.1.0a0+41361538.nv23.06-cp38-cp38-linux_aarch64.whl
python3 -m pip install --no-cache $TORCH_INSTALL

sudo apt-get install -y libjpeg-dev
sudo apt-get install -y zlib1g-dev
sudo apt-get install -y libpython3-dev
sudo apt-get install -y libopenblas-dev
sudo apt-get install -y libavcodec-dev
sudo apt-get install -y libavformat-dev
sudo apt-get install -y libswscale-dev

git clone --branch v0.16.1 https://github.com/pytorch/vision torchvision
cd torchvision
export BUILD_VERSION=0.16.0  # where 0.x.0 is the torchvision version  
python3 setup.py install --user

export PYDS_INSTALL=https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/releases/download/v1.1.8/pyds-1.1.8-py3-none-linux_aarch64.whl
python3 -m pip install --no-cache $PYDS_INSTALL

cd /opt/nvidia/deepstream/deepstream-6.3/sources
git clone https://github.com/NVIDIA-AI-IOT/deepstream_python_apps
cd ~

python3 -c "import torchvision as tv; print(tv.__version__); import torch as t; print(t.__version__)"
python3 -c "import torch; print('Is Cuda support available: ' + str(torch.cuda.is_available()))"

mkdir Development
sudo apt install -y libcanberra-gtk-module 
sudo apt install -y libcanberra-gtk3-module

sudo apt-get update
sudo apt-get install -y v4l-utils

sudo apt install -y terminator

gst-launch-1.0 v4l2src device=/dev/video0 ! 'video/x-raw , width=(int)1280 , height=(int)720, format=(string)GRAY8 , framerate=(fraction)60/1' ! nvvidconv ! 'video/x-raw(memory:NVMM),  width=(int)1280, height=(int)720, format=I420' ! nvvidconv ! 'video/x-raw, format=BGRx' !  videoconvert ! 'video/x-raw, format=BGR, width=(int)640 , height=(int)360' ! videoconvert ! xvimagesink -e

```

After this the Gstreamer produces image.
Running a simple cv example also produces image.
```
import cv2

cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)
if not (cap.isOpened()):
    print("Could not open video device")
else:
    while(1):
        _,image = cap.read()
        cv2.imshow("Wndow",image)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
```

The problem occurs after instaling ultralytics:
pip install ultralytics.

I dont know what in the package that messes up the installation but the images is black but moving the camera indicate that there is something there but very dark. v4l2 to set exposure does no longer work.

### Environment

ltralytics YOLOv8.2.5 🚀 Python-3.8.10 torch-2.1.0a0+41361538.nv23.06 CUDA:0 (Orin, 30572MiB)
Setup complete ✅ (8 CPUs, 29.9 GB RAM, 20.7/53.8 GB disk)

OS                  Linux-5.10.192-tegra-aarch64-with-glibc2.29
Environment         Linux
Python              3.8.10
Install             pip
RAM                 29.86 GB
CPU                 ARMv8 Processor rev 1 (v8l)
CUDA                11.4

matplotlib          ✅ 3.7.5>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 5.3.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.1.0a0+41361538.nv23.6>=1.8.0
torchvision         ✅ 0.18.0>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.5.1
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Minimal Reproducible Example

Run installation on jetson and install ultralytics.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hey there! 😊 It seems you're encountering an issue with camera image darkness after installing the `ultralytics` package on your Jetson AGX Orin setup. This is quite unusual, as the Ultralytics installation should generally not interfere with OpenCV's camera functionalities.

One possibility is that the installation or dependencies of Ultralytics might be causing unexpected changes in the camera settings or conflicts with certain GStreamer elements. Here's something you can try:

1. Verify if resetting the camera settings or using `v4l2-ctl` to adjust exposure and brightness settings directly helps.
2. Consider isolating the environment for Ultralytics and OpenCV by using Python virtual environments. This way, you can ensure that the installations do not interfere with each other.

   For creating and activating a virtual environment, you can use:
   ```bash
   python3 -m venv ultralytics_venv
   source ultralytics_venv/bin/activate
   ```

   Then, install Ultralytics in this isolated environment:
   ```bash
   pip install ultralytics
   ```

3. Ensure that there's no conflict with GStreamer pipeline elements — try running your GStreamer pipeline from the terminal to ensure it's not affected by the Python environment.

If the issue persists, it might be beneficial to delve deeper into any changes in library versions or dependencies introduced during the installation. Please keep us posted on your progress or if you discover any specific triggers for this issue!

👩‍💻 If further investigation leads to a potential bug or fix, we're here to support any contributions or insights you might have.
