### ISSUE TITLE
Pretrained model usage

### ISSUE THREAD

**Issue by asudemerveekiz** [ultralytics/ultralytics#10430]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to train with a custom dataset using YOLOV8n. I have two questions. The first one is which of the following is the correct way to load the pretrained model in such a task? 
Option 1: **YOLO('yolov8n.pt')**
Option 2: **YOLO('yolov8n.yaml').load('yolov8n.pt')**

(After loading the model with one of the two options above, I train it with my own custom dataset as below.
**model.train(data="/content/WildfireSmokeYoloV8/data.yaml", epochs=50)** )

My second question: Let's say I train the model with my own data using one of the two options above and save the weights. Then, when using my trained model by loading these weights, should I directly load best.pt and use it or should I include the yaml file again? So which of the following is correct?

->**YOLO("/content/runs/detect/train/weights/best.pt")**
->**YOLO('yolov8n.yaml').load("/content/runs/detect/train/weights/best.pt")**

I would be very grateful if you could explain with reasons.
Thank you in advance.

**Comment by glenn-jocher** [comment]
@asudemerveekiz hello! 🌟

Great questions! Let's dive straight into the answers:

1. **Pretrained Model Loading**: Both options you mentioned will ultimately have the same outcome, but for clarity and simplicity, it's typically more straightforward to use **Option 1**: `YOLO('yolov8n.pt')`. This way, you load the pretrained model directly and can proceed with training on your custom dataset. 

    ```python
    from ultralytics import YOLO
    
    # Load a pretrained model
    model = YOLO('yolov8n.pt')
    # Proceed with custom training
    model.train(data="/content/WildfireSmokeYoloV8/data.yaml", epochs=50)
    ```

2. **Using Trained Models**: After training with your custom dataset, when you save your model's weights, they include both the architecture and the trained weights. Therefore, you should directly load the `.pt` file like in your first suggested approach: `YOLO("/content/runs/detect/train/weights/best.pt")`. This will be enough to utilize your model with the custom-trained weights.

    ```python
    from ultralytics import YOLO
    
    # Load a custom trained model
    model = YOLO("/content/runs/detect/train/weights/best.pt")
    ```

In brief, your intuition towards using `.pt` files for both loading pretrained models for further training and utilizing the trained models is spot-on. Using the `.pt` file directly simplifies the process and encapsulates everything needed for deployment or further training.

I hope this clarifies things for you! If you have any more questions, feel free to ask. Happy coding! 😊
