### ISSUE TITLE
mlflow.tracking.registry.UnsupportedModelRegistryStoreURIException

### ISSUE THREAD

**Issue by wink94** [ultralytics/ultralytics#10438]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

`mlflow.tracking.registry.UnsupportedModelRegistryStoreURIException:  Model registry functionality is unavailable; got unsupported URI <path>\runs\mlflow' for model registry data storage. Supported URI schemes are: ['', 'file', 'databricks', 'databricks-uc', 'http', 'https', 'postgresql', 'mysql', 'sqlite', 'mssql']. See https://www.mlflow.org/docs/latest/tracking.html#storage for how to run an MLflow server against one of the supported backend storage locations.`

i get this bug when trying to a simple training with ultralytics yolo8

### Environment

Ultralytics YOLOv8.2.2 🚀 Python-3.10.10 torch-2.1.2+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 Ti Laptop GPU, 4096MiB)

### Minimal Reproducible Example

`        
model = YOLO("yolov8n-cls.pt")  
results = model.train(data=args['dataset'], epochs=int(args['epochs']),augment=True,fliplr=0.2,auto_augment='randaugment')
 `

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wink94 hi there! 👋 It looks like the issue you're encountering is related to MLflow's model registry URI configuration. The error suggests that the URI provided for MLflow's model registry is unsupported. The supported URI schemes include `file`, `http`, `https`, `postgresql`, `mysql`, `sqlite`, `mssql`, and some others.

Since you're experiencing this issue while training a model with Ultralytics YOLOv8, here's a quick suggestion: please ensure your MLflow tracking URI is set correctly, and it's using one of the supported schemes mentioned in the error message. You can set the tracking URI using MLflow's `set_tracking_uri` function, like so:

```python
import mlflow

# Set to one of the supported schemes
mlflow.set_tracking_uri('file:///path/to/your/mlruns')
```

Insert this code before starting your model training to correctly configure the MLflow tracking URI. Make sure to replace `'/path/to/your/mlruns'` with your actual path, ensuring it uses a supported scheme.

If this doesn't directly address your issue, or there's any more information that could help, please provide more specifics. Happy to help further! 😊

And thanks for your willingness to contribute with a PR! The community appreciates your efforts.

**Comment by pierrickBERTHE** [comment]
Hello Glenn,
I have exactly the same problem :
```UnsupportedModelRegistryStoreURIException:  Model registry functionality is unavailable; got unsupported URI 'c:\Users\pierr\VSC_Projects\Projet8_OCR_DataScientist\runs\mlflow' for model registry data storage. Supported URI schemes are: ['', 'file', 'databricks', 'databricks-uc', 'http', 'https', 'postgresql', 'mysql', 'sqlite', 'mssql']. See https://www.mlflow.org/docs/latest/tracking.html#storage for how to run an MLflow server against one of the supported backend storage locations.```

My current directory is :
````
c:\Users\pierr\VSC_Projects\Projet8_OCR_DataScientist
````

You can see my library env :
```
Python        : 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]

Version des librairies utilisées :
Matplotlib    : 3.8.4
Mlflow        : 2.10.2
NumPy         : 1.26.4
Pandas        : 1.5.3
Scikit-learn  : 1.2.2
Seaborn       : 0.13.2
Tensorflow    : 2.16.1
Ultralytics   : 8.2.7
```

I load the nano Yolov8 :

```
model_yolo = YOLO('yolov8n-cls.pt')
model_yolo.info()
```

output : ```YOLOv8n-cls summary: 99 layers, 2719288 parameters, 0 gradients, 4.4 GFLOPs```

I launch the train:
```
mlflow.set_tracking_uri('file:./runs')

model_yolo.train(
    data='data/cleaned',
    epochs=1
)
```
My image folders are correctly organized in the folder ```data/cleaned``` => ```train``` / ```val``` / ```test```
And a folder ```runs``` is correctly created in my current directory with a folder ```classify``` inside and the train inside this. 

**How can I resolve this problem please?**

Thanks for your help.

**Comment by glenn-jocher** [comment]
@pierrickBERTHE hello! It seems like the issue might be related to how MLflow expects the URI for the tracking server. In your script, you've set the MLflow tracking URI with a relative path, which may lead to issues depending on the environment.

Try setting the tracking URI to an absolute file path instead. For example:

```python
import mlflow

# Use an absolute path
mlflow.set_tracking_uri('file:///c:/Users/pierr/VSC_Projects/Projet8_OCR_DataScientist/runs/mlflow')
```

Make sure that the path points to a directory where MLflow can write its tracking information. Using an absolute path helps avoid any relative path confusion across different environments or when the working directory changes unexpectedly.

Give this a shot and see if it resolves the issue! 😊 If the problem persists, please check the permissions for the directory to ensure that your application has write access.

**Comment by glenn-jocher** [comment]
Thank you for the detailed report. The issue appears to be related to how the MLflow tracking URI is being set. Try explicitly setting the tracking URI with the file protocol like this:

```python
mlflow.set_tracking_uri("file:///C:/Users/lftob/ultralytics/runs/mlflow")
```

Make sure to use forward slashes and include the triple forward slashes after `file:` when specifying the absolute path. This format is required by MLflow when using the file storage backend. The rest of your training configuration looks correct.

Feel free to report back if you still encounter issues after making this change.
