### ISSUE TITLE
Ultralytics pip install messes up openCV and camera capture [ACCIDENTAL DUPLICATION, REMOVE!!]

### ISSUE THREAD

**Issue by mgabell** [ultralytics/ultralytics#10436]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Install

### Bug

I have a Jetson AGX Orin and install Jetpack 5.1.2 (must have for deepstream)
This include DS 6.3
Additional installation packages:

```
sudo apt install -y libgstrtspserver-1.0-0
sudo apt install -y libjansson4

sudo apt install -y python3-gst-1.0
sudo apt install -y python-gi-dev
sudo apt install -y git libglib2.0-dev
sudo apt install -y libgirepository1.0-dev
sudo apt install -y libcairo2-dev
sudo apt install -y python3-pip

export TORCH_INSTALL=https://developer.download.nvidia.com/compute/redist/jp/v512/pytorch/torch-2.1.0a0+41361538.nv23.06-cp38-cp38-linux_aarch64.whl
python3 -m pip install --no-cache $TORCH_INSTALL

sudo apt-get install -y libjpeg-dev
sudo apt-get install -y zlib1g-dev
sudo apt-get install -y libpython3-dev
sudo apt-get install -y libopenblas-dev
sudo apt-get install -y libavcodec-dev
sudo apt-get install -y libavformat-dev
sudo apt-get install -y libswscale-dev

git clone --branch v0.16.1 https://github.com/pytorch/vision torchvision
cd torchvision
export BUILD_VERSION=0.16.0  # where 0.x.0 is the torchvision version  
python3 setup.py install --user

export PYDS_INSTALL=https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/releases/download/v1.1.8/pyds-1.1.8-py3-none-linux_aarch64.whl
python3 -m pip install --no-cache $PYDS_INSTALL

cd /opt/nvidia/deepstream/deepstream-6.3/sources
git clone https://github.com/NVIDIA-AI-IOT/deepstream_python_apps
cd ~

python3 -c "import torchvision as tv; print(tv.__version__); import torch as t; print(t.__version__)"
python3 -c "import torch; print('Is Cuda support available: ' + str(torch.cuda.is_available()))"

mkdir Development
sudo apt install -y libcanberra-gtk-module 
sudo apt install -y libcanberra-gtk3-module

sudo apt-get update
sudo apt-get install -y v4l-utils

sudo apt install -y terminator

gst-launch-1.0 v4l2src device=/dev/video0 ! 'video/x-raw , width=(int)1280 , height=(int)720, format=(string)GRAY8 , framerate=(fraction)60/1' ! nvvidconv ! 'video/x-raw(memory:NVMM),  width=(int)1280, height=(int)720, format=I420' ! nvvidconv ! 'video/x-raw, format=BGRx' !  videoconvert ! 'video/x-raw, format=BGR, width=(int)640 , height=(int)360' ! videoconvert ! xvimagesink -e

```

After this the Gstreamer produces image.
Running a simple cv example also produces image.
```
import cv2

cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)
if not (cap.isOpened()):
    print("Could not open video device")
else:
    while(1):
        _,image = cap.read()
        cv2.imshow("Wndow",image)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
```

The problem occurs after instaling ultralytics:
pip install ultralytics.

I dont know what in the package that messes up the installation but the images is black but moving the camera indicate that there is something there but very dark. v4l2 to set exposure does no longer work.

### Minimal Reproducible Example

Run installation on jetson and install ultralytics.
Then try simple cam source.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mgabell hi there! Thanks for bringing this to our attention. It seems like the installation of the `ultralytics` package might be causing some conflicts with your OpenCV camera capture setup. While we investigate this further, you might want to try a few steps to see if it helps resolve the issue:

1. Try reinstalling OpenCV after installing the `ultralytics` package. Sometimes, reinstalling can help resolve any overwritten or conflicting dependencies.

2. Check if there are any specific OpenCV versions recommended for the `ultralytics` package and ensure that your installed version matches.

3. If the issue persists, installing the `ultralytics` package in a virtual environment might help isolate and prevent it from interfering with the global packages like OpenCV.

Here's a quick way to create and use a Python virtual environment:

```bash
python3 -m venv ultralytics-venv
source ultralytics-venv/bin/activate
pip install ultralytics
```

Then try running your OpenCV camera capture code to see if the issue still occurs within the virtual environment.

We'll also look into the installation process of our package to identify any potential causes for this behavior. Thanks for your patience and contribution to improving the Ultralytics ecosystem. If you find out more or have any additional information, please feel free to share! 🌟

**Comment by mgabell** [comment]
Hi, Thanks for answering...

1. I have reinstalled the system from scratch 3 times. Logging every step of the way. The system works just fine after installation using SDK manager and the above stated main script. The console application show the image perfectly using gst-launch-1.0 and with the test script. Reinstalling openCV has messed up more than helping. 
2. The OpenCV used comes from nVidia SDK Manager and is 4.9.0
3. Tried with virtual environment and installed ultralytics. Still black camera. This also creates a problem with torch and GPU support. I can only run on CPU not GPU so that adds on the problem...

What I found is that sudo infront of python3, when running a test script as mentioned in the first post, I get the camera to work. So somewhere in the installation of ultralytics it does something strange. I don't understand yet why it changes permissions to access the camera. 

I will reinstall AGAIN and create a new venv and see if I can isolate the problem to a virtual environment. So far it has not been the case...

**Comment by mgabell** [comment]
Hi,

I checked the user in video group and that does not work.
I reinstalled with a later Jetpack and that did not do the trick.

I Create the virtual environment as you says, directly on the fresh system.
I then run installation of openCV using apt, sudo apt install python3-opencv. This did not work to include cv2 in python.
Installed  using pip3 (pip3 install opencv-python). This creates a black screen. The test program can not read the image.

I exit the venv and try the code and it still works in "normal" environment.

I recreate a new venv (**python3 -m venv test2**) and activate it: **source test2/bin/activate**.

Then I try the program and cv2 is missing. I the ONLY run **pip3 install opencv-python**
Running the test program creates a black screen.
I then run **sudo python3 cvTest.py**
This works. I get image when running sudo.


Below is the code I get the first time I run the program, but not after that.
```
(gst-plugin-scanner:9060): GStreamer-WARNING **: 15:52:57.496: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_inferserver.so': libtritonserver.so: cannot open shared object file: No such file or directory

(gst-plugin-scanner:9060): GStreamer-WARNING **: 15:52:57.506: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_deepstream_bins.so': libgstrtspserver-1.0.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:9060): GStreamer-WARNING **: 15:52:57.512: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_udp.so': librivermax.so.0: cannot open shared object file: No such file or directory
[ WARN:0] global ./modules/videoio/src/cap_gstreamer.cpp (1100) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1

```

**Comment by glenn-jocher** [comment]
@mgabell hi there! 😊 Thanks for sharing the detailed steps and the issues you encountered. It's intriguing that running with `sudo` allows the camera feed to work, pointing towards a permissions or environment issue. Here are a couple of thoughts:

1. **GStreamer Errors**: The warnings you're getting from GStreamer suggest there might be missing dependencies or mismatches in library versions. Since running with `sudo` works, this could mean that `sudo` has access to some environment variables or libraries that the regular user doesn't.

2. **OpenCV Installation**: `pip install opencv-python` installs pre-built OpenCV binaries that might not be fully compatible with the Jetson's GPU or specific setup. Installing OpenCV through `apt` should theoretically work better since it's more integrated with the system, but it seems like the Python bindings are not correctly linked in your case.

3. **Environment Variables**:
    - Before running your Python script in the virtual environment, try exporting the `LD_LIBRARY_PATH` to include paths to CUDA and other necessary libraries. For example:
      ```bash
      export LD_LIBRARY_PATH=/usr/local/cuda/lib64:/path/to/other/libs:$LD_LIBRARY_PATH
      ```
    - Check whether `sudo` is preserving these variables by running `sudo env` and comparing the output with `env`. If they differ significantly, especially around paths to libraries, it might explain the discrepancy.

4. **Python Virtual Environment and System Libraries**:
    - Virtual environments in Python are great for isolating package installations, but they may unintentionally isolate necessary system libraries too. One way to approach this is to ensure that the `venv` module creates the environment without including its own copies of system site packages using:
      ```bash
      python3 -m venv --system-site-packages test2
      ```

Considering the complexity of the Jetson environment and the nuanced interaction between Python packages and system libraries, it's often challenging to pinpoint the exact cause. No need to dive into building OpenCV from source immediately, as it indeed can complicate things further.

Since running as `sudo` resolves the issue temporarily, you might want to further investigate the environment and permissions differences `sudo` introduces. Hopefully, these ideas give you a good starting point, and feel free to keep us posted on your progress!

**Comment by mgabell** [comment]
Hi,

So your step 1-2 does not work. But I created a venv and installed openCV. That messed up the installation.
So i uninstalled openCV from the environment and then used the argument "--system-site-packages" and now I have
cv2 working. I installed some more dependencies manually. I git cloned the ultralytics repo and ran analysis on the bus image.
It worked, I cant tell if it used the GPU but that works.

Now to camera. I get the following error:
```

1/1: 0... Success ✅ (inf frames of shape 1600x1300 at 60.00 FPS)


WARNING ⚠️ inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    main()
  File "main.py", line 6, in main
    model.predict(source, save=True, imgsz=320, conf=0.5, show=True)
  File "/home/aiadmin/Development/ultralytics/ultralytics/engine/model.py", line 452, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/aiadmin/Development/ultralytics/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/aiadmin/Development/test2/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/aiadmin/Development/ultralytics/ultralytics/engine/predictor.py", line 244, in stream_inference
    im = self.preprocess(im0s)
  File "/home/aiadmin/Development/ultralytics/ultralytics/engine/predictor.py", line 125, in preprocess
    im = im[..., ::-1].transpose((0, 3, 1, 2))  # BGR to RGB, BHWC to BCHW, (n, 3, h, w)
ValueError: axes don't match array
terminate called without an active exception
Aborted (core dumped)

```

My hunch is thatmy image format is not appreciated by Ultralytics. The pixelformat is gray8??

**Comment by glenn-jocher** [comment]
Hi there! 😊 Glad to hear you've made some progress with the OpenCV and dependency installations using the `--system-site-packages` option for your venv!

About the issue you're experiencing with the camera, it looks like the camera is using a grayscale image format (`gray8`), but our model expects color images (BGR or RGB). This is causing the mismatch error during preprocessing, as the array doesn't have the expected three channels.

To resolve this, you could convert your grayscale images to RGB format before passing them to the model. You can modify your capture and preprocessing code like this:

```python
import cv2
from ultralytics import YOLO

def main():
    cap = cv2.VideoCapture(0)  # open video capture
    ret, frame = cap.read()  # read one frame
    if ret:
        frame_rgb = cv2.cvtColor(frame, cv2.COLOR_GRAY2RGB)  # convert grayscale to RGB
        model = YOLO('yolov8n.pt')
        results = model.predict(frame_rgb, imgsz=320, conf=0.5)  # predict
        results.show()  # show the results
    cap.release()

if __name__ == "__main__":
    main()
```

This modification will ensure the image fed into the predictor has three channels, which should align with the model’s requirements. Hope this helps, and let me know if there's anything more I can do for you.

**Comment by mgabell** [comment]
Hi,

That works. I get the inference to work. So to conclude I would say that the problem lies with the installation of OpenCV on Jetson.
It collides and does not work with the Original from nVidia. It does not work even with the virtual environment. So the solution is to manually install the dependencies in a virtual environment using:

`python3 -m venv --system-site-packages test2`

To create the environment. The git clone the library and run the code. In my case, if someone else reads this, you should convert the format to be accepted by ultralytics.

Question: Would the below code be a correct implementation of a continuous feed?

```
import cv2
from ultralytics import YOLO

def main():
    model = YOLO('yolov8n.pt')
    cap = cv2.VideoCapture(0)  # open video capture
    while(1):
        ret, frame = cap.read()  # read one frame
        if ret:
            frame_rgb = cv2.cvtColor(frame, cv2.COLOR_GRAY2RGB)  # convert grayscale to RGB
            results = model.predict(frame_rgb, imgsz=320, conf=0.5)  # predict
            cv2.imshow("Window", results)
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break
    cap.release()

if __name__ == "__main__":
    main()
```

My concern is how you ensure that the inference is properly implemented? The results.show() did not work.
I added show=True to the model prediction to see the image.

Secondly I would like to know if you have code to implement concurrency? I have three cameras that I need to run 
at the same time with the same model.

**Comment by glenn-jocher** [comment]
@mgabell hi there! 🚀

Glad to hear you've solved the installation issue and got the inference working on Jetson! For the continuous camera feed with the YOLO model, here's a slight modification to ensure `results.show()` functions correctly by using the `Results` display method instead of directly with `cv2.imshow()`:

```python
import cv2
from ultralytics import YOLO

def main():
    model = YOLO('yolov8n.pt')  # load the model
    cap = cv2.VideoCapture(0)  # open video capture
    while True:
        ret, frame = cap.read()  # read frame
        if ret:
            frame_rgb = cv2.cvtColor(frame, cv2.COLOR_GRAY2RGB)  # convert to RGB
            results = model.predict(frame_rgb, imgsz=320, conf=0.5)  # predict
            results.show()  # show the results using YOLO's method
            if cv2.waitKey(1) & 0xFF == ord('q'):  # quit on 'q' key
                break
    cap.release()
    cv2.destroyAllWindows()  # close all cv2 windows

if __name__ == "__main__":
    main()
```

Regarding threading, threading issues might arise due to resource contention among threads, especially with GPU resources. Ensure each thread safely manages its resources, or consider using processes instead, which don't share the same memory space. The concept of using Python's `multiprocessing` library instead of `threading` might be a better fit for such a heavy I/O operation.

Feel free to move further questions to a forum thread, as that could also benefit others in the community facing similar challenges! Keep up the great work! 🌟
