### ISSUE TITLE
bounding box, label, confidence score missing.

### ISSUE THREAD

**Issue by aiyafi** [ultralytics/ultralytics#10463]
### Discussed in https://github.com/orgs/ultralytics/discussions/10348

<div type='discussions-op-text'>

<sup>Originally posted by **aiyafi** April 26, 2024</sup>
I need help, I want to make a program about “Loitering Detection in an Intelligent Surveillance System using YOLO-based Methods”. Where I have made it as in the following picture:
![image](https://github.com/ultralytics/ultralytics/assets/63116789/60b1e72f-cd98-4370-aa9f-5d08a1440731)

Then on the centroid feature I have created and it works. But I want the bounding box, label, and confidence score to remain. Then how do I make it exist?

Just look like this repository:
[https://github.com/ultralytics/yolov5/issues/6636](url)

I want to run the code, but there is an error and this is still using Yolo version 5, while in my project using Yolo version 8n. So please, can someone help me out?

and here's the full code:

```
from ultralytics import YOLO, engine
import cv2

# Model setup
#confidence_threshold = 0.8
model = YOLO('yolov8n.pt')
result = model.predict(source="./PGM.mp4", save=True, save_txt=True, classes=[0], stream=True)  # save=True saves the results to a folder

# Video loading
video_path = './PGM-normal_cewek_sore_2.mp4'
cap = cv2.VideoCapture(video_path)

# Get video dimensions
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

# Main processing loop
while True:
    ret, frame = cap.read()
    if not ret:
        break  # End of video

    # Optional resizing
    frame = cv2.resize(frame, (960, 540)) 

    # Object detection and centroid calculation
    results = model.predict(frame, save=True, save_txt=True, classes=[0])  

    for r in results:  
        for box in r.boxes.xyxy:
            centroid_x = (box[0] + box[2]) / 2
            centroid_y = (box[1] + box[3]) / 2

            # Print and/or draw on the frame
            print(f"Centroid Coordinates: ({centroid_x}, {centroid_y})")
            cv2.circle(frame, (int(centroid_x), int(centroid_y)), radius=2, color=(0, 0, 255), thickness=3) # Draw centroid

    # Display the frame with bounding boxes and centroids
    cv2.imshow('frame', frame) 

    # Exit condition
    if cv2.waitKey(25) & 0xFF == ord('q'):
        break

# Release resources
cap.release()
cv2.destroyAllWindows()
```</div>

**Comment by glenn-jocher** [comment]
Hello ** @aiyafi**! It looks like you're doing interesting work with YOLOv8 for your surveillance system project. I see you want to include bounding boxes, labels, and confidence scores along with centroids. Here's a quick tip to make sure these elements are displayed:

To retain and draw bounding boxes, labels, and confidence scores, you can adjust your loop where you process the results. The `r.boxes.xyxy` provides bounding box coordinates, and you already use it to calculate centroids. You can also access class labels via `r.boxes.cls` and confidence scores with `r.boxes.conf`. Here’s how you could incorporate drawing these elements:

```python
    for r in results:  
        for i, box in enumerate(r.boxes.xyxy):
            # Calculate centroid
            centroid_x = (box[0] + box[2]) / 2
            centroid_y = (box[1] + box[3]) / 2
            label = r.names[int(r.boxes.cls[i])]
            confidence = round(float(r.boxes.conf[i]), 2)

            # Draw bounding box and centroid
            cv2.rectangle(frame, (int(box[0]), int(box[1])), (int(box[2]), int(box[3])), (255, 0, 0), 2)
            cv2.circle(frame, (int(centroid_x), int(centroid_y)), radius=2, color=(0, 0, 255), thickness=3)
            
            # Put label and confidence
            cv2.putText(frame, f"{label} {confidence}", (int(box[0]), int(box[1]-10)), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (36,255,12), 2)

    # Display frame with bounding boxes, labels, centroids, and confidence scores
    cv2.imshow('frame', frame) 
```

This should help you draw the bounding boxes with labels and confidence scores on your frames along with the centroids. Make sure you adjust the colors, thickness, or font size according to your preference.

Happy coding, and best of luck with your project! 😊
