### ISSUE TITLE
[Example issue]Yolov8_CPP_Inference Detection. Assignee - JustasBart

### ISSUE THREAD

**Issue by CasparTheGhost** [ultralytics/ultralytics#1046]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I followed all steps starting with cloning the repo.
Then pip install .
Then i exported the yolov8s.pt to onnx with the opset 12 like explained. I ran the Python examples and it worked.
When trying the same for The CPP Inference it also executed but no detections where drawn with the same exported onnx model. I tried the sizes used in the example [480,640] and 640,640 for my export but nothing helped. Is there maybe something i could have done wrong in the process. By manually printing some detections i tested whether anything is functioning and yes it is.

### Environment

Newest Repo version downloaded 8.0.40
Cuda: 11.3
Cudnn 8.4.1
Cmake: 3.26.0
Opencv: 4.7.0
OS: Win 10
GPU: rtx 3070ti

### Minimal Reproducible Example

```
for (int i = 0; i < detections; ++i)
        {
            Detection detection = output[i];

            cv::Rect box = detection.box;
            cv::Scalar color = detection.color;

            // Detection box
            cv::rectangle(frame, box, color, 2);

            // Detection box text
            std::string classString = detection.className + ' ' + std::to_string(detection.confidence).substr(0, 4);
            std::cout << classString << std::endl;
            cv::Size textSize = cv::getTextSize(classString, cv::FONT_HERSHEY_DUPLEX, 1, 2, 0);
            cv::Rect textBox(box.x, box.y - 40, textSize.width + 10, textSize.height + 20);

            cv::rectangle(frame, textBox, color, cv::FILLED);
            cv::putText(frame, classString, cv::Point(box.x + 5, box.y - 10), cv::FONT_HERSHEY_DUPLEX, 1, cv::Scalar(0, 0, 0), 2, 0);
        }
```
I added that little cout and the output is:
```
Running on CUDA
Number of detections:1
bus 0.92
```

This output comes from the bus image. Tried finding other people with the same problem but didnt find anyone. Is there maybe a workaround necessary like in yolov7 with hyperparametization?

![Unbenannt](https://user-images.githubusercontent.com/52799640/219957620-e8e25884-a8c5-489f-a3a5-7513365c4e0c.PNG)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Hey @JustasBart can you take a look?

**Comment by CasparTheGhost** [comment]
Ty for fast response @AyushExel :)

**Comment by JustasBart** [comment]
Hi @CasparTheGhost I've never seen an issue like this before and it seems a bit odd, but let's see if we can figure it out!
The simplest first test that I could suggest for you to try would be to clone the [original repo](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX.git) that has the exported models (Or just grab the **yolov8s.onnx** model).

In theory if you just follow the instructions on how to build/execute this example via CMake it should reveal if whether the problem could be on the setup of your machine or your particular project setup.

The next thing that I would recommend would be to try and run the sample on your **CPU** that is to have the 'runOnGPU' flag set to **false**. This should in theory reveal if perhaps the issue occurs when introducing any **CUDA** based drivers.

In addition I hope that you're aware that when you're exporting a yolov8/5 model the export command expects a {H, W] size whereas when running inference via the CPP example it expects a [W, H] size. Though it would also just crash unless you had it correctly so I this is likely not an issue.

It's really hard to tell considering that we don't have a whole lot to go with here such as a segmentation fault dump or anything as the project actually runs. So again try see if running the sample on the CPU fixes it and if not then perhaps we can discuss on how your OpenCV was built and perhaps we can catch out the potential issue that way.

Lastly see if you can print out the [x, y, w, h] of the box that it finds and let's see if that could give us a clue.

Please get back to me once you have tried some of the things suggested here and let's see :rocket:

**Comment by CasparTheGhost** [comment]
I already tried this repo you linked there but its literally the same. I tried building it with cmake and bymyself by just linking everything together but result is still the same. Everywhere where i could find models pre exported i did that but even with the given .pt files exported after the instructions i cant get a good result or even any detections drawn. Im a bit confused.

And when trying https://github.com/triple-Mu/YOLOv8-TensorRT with the given already exported onnx models it worked. But my goal wasnt to use TensorRT but OpencvDNN since its way faster somehow

**Comment by JustasBart** [comment]
@CasparTheGhost And have you tried running on CPU opposed to GPU?

**Comment by CasparTheGhost** [comment]
I did not try that. Will report results later

**Comment by CasparTheGhost** [comment]
Sorry for the late response but it seems like it doesnt change the behavior when using cpu as backend. The weird thing is that its working in yolov8-tensorRT using opencv. Just needs to be the way the model is exported:
i did the exact same cmd
```yolo export model=yolov8s.pt format=onnx imgs=640 opset=12```
Even tried different opset versions and imgsz but doesnt change anything. There are basically always bugs when a new yolo version comes out because its just supported for onnx runtime and python until some genius finds a work around for the fastest way Opencv dnn in c++ ;)

**Comment by JustasBart** [comment]
@CasparTheGhost I see, I still suspect that it's your OpenCV build in particular the DNN/CUDA setup within your OpenCV build... But hey at least you have something working!

The last thing that I could offer you is this:

![OpenCV build](https://user-images.githubusercontent.com/40023722/220768215-e1f5f834-c828-4f44-996a-c9562e6f4efb.png)

As again I've tried the CPP inference on at least 6 different machines and it works just fine assuming that you've built your OpenCV as described on the diagram so I wish you all the best :rocket:

**Comment by CasparTheGhost** [comment]
Amazing diagram never seen that one before. In exception of the QT stuff I
got everything In my 4.7 build. I even have yolov4 to yolk v7 working in
Opencv dnn just not the v8. So it needs to be the model. As you said you
got the thing working. Could you maybe post a .onnx file with it’s exported
imgsize and I can test it. Then I could know whether my export part is
wrong or something else
