### ISSUE TITLE
readNetFromONNX() crash

### ISSUE THREAD

**Issue by anzenchitai** [ultralytics/ultralytics#1047]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Integrations, Other

### Bug

1. Train YOLOv8n on a custom dataset.
`!yolo train model=yolov8n.pt data=kek.yaml epochs=128 imgsz=960`

2. Export the model to ONNX.
`!yolo export model=best.pt format=onnx opset=12`

3. Read the model using an absolute path.
`cv::dnn::readNetFromONNX("C:\\Users\\nginx\\Desktop\\ai\\best.onnx");`

4.
`OpenCV(4.7.0) C:\Users\nginx\Downloads\cvbuild\modules\dnn\src\onnx\onnx_importer.cpp:270: error: (-5:Bad argument) Can't read ONNX file: C:\Users\nginx\Desktop\ai\ in function 'cv::dnn::dnn4_v20221220::ONNXImporter::ONNXImporter'`

I spent hours annotating and training stuff. Now I can't even load any model. I can't load anything using other formats too. Please help me.

Best regards.

### Environment

- YOLO: Ultralytics YOLOv8.0.40  Python-3.9.13 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3080, 10239MiB)
- OpenCV2: 4.7.0
- OS: Windows 10 19045.2546

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Please take a look here at ONNX python opencv example -> https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-OpenCV-ONNX-Python
You might find the correct usage here.

**Comment by anzenchitai** [comment]
> Please take a look here at ONNX python opencv example -> https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-OpenCV-ONNX-Python You might find the correct usage here.

Hello. I am using the CPP example as is yet it still can't read the model.

**Comment by anzenchitai** [comment]
Solved.

**Comment by soloplayl** [comment]
How did you solve it? I also met the same problem.

**Comment by soloplayl** [comment]
hi@anzenchitai ,this my bug content :
global /home/soloplayl/下载/opencv-4.6.0/modules/dnn/src/onnx/onnx_importer.cpp (1018) handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [Add]:(onnx_node!/model.22/Add) from domain='ai.onnx'
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.6.0) /home/soloplayl/下载/opencv-4.6.0/modules/dnn/src/onnx/onnx_importer.cpp:1040: error: (-2:Unspecified error) in function 'handleNode'
> Node [Add@ai.onnx]:(onnx_node!/model.22/Add) parse error: OpenCV(4.6.0) /home/soloplayl/下载/opencv-4.6.0/modules/dnn/src/onnx/onnx_importer.cpp:1464: error: (-215:Assertion failed) blob_0.size == blob_1.size in function 'parseBias'
> 

I also have the same problem in the same code, but my error is different from yours. My environment is Ubuntu, can I hear some of your solutions? Thank you, my friend.
