### ISSUE TITLE
Running train.py got the error \ultralytics\yolo\utils\tal.py", line 215, in make_anchors      _, _, h, w = feats[i].shape

### ISSUE THREAD

**Issue by YFforever2022** [ultralytics/ultralytics#1048]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Running train.py got the error \ultralytics\yolo\utils\tal.py", line 215, in make_anchors
     _, _, h, w = feats[i].shape
ValueError: not enough values to unpack (expected 4, got 3) in version 8.0.40, but everything works fine in version 8.0.31

Traceback (most recent call last):
  File "D:\ultralytics-main-20230219\ultralytics\yolo\v8\detect\train.py", line 217, in <module>
    train()
  File "D:\ultralytics-main-20230219\ultralytics\yolo\v8\detect\train.py", line 213, in train
    trainer.train()
  File "D:\ultralytics-main-20230219\ultralytics\yolo\engine\trainer.py", line 187, in train
    self._do_train(RANK, world_size)
  File "D:\ultralytics-main-20230219\ultralytics\yolo\engine\trainer.py", line 306, in _do_train
    self.loss, self.loss_items = self.criterion(preds, batch)
  File "D:\ultralytics-main-20230219\ultralytics\yolo\v8\detect\train.py", line 76, in criterion
    return self.compute_loss(preds, batch)
  File "D:\ultralytics-main-20230219\ultralytics\yolo\v8\detect\train.py", line 169, in __call__
    anchor_points, stride_tensor = make_anchors(feats, self.stride, 0.5)
  File "D:\ultralytics-main-20230219\ultralytics\yolo\utils\tal.py", line 215, in make_anchors
    _, _, h, w = feats[i].shape
ValueError: not enough values to unpack (expected 4, got 3)

### Environment

Ultralytics YOLOv8.0.40  Python-3.7.9 torch-1.10.0+cu113 CUDA:0 (NVIDIA GeForce RTX 3060, 12287MiB)
win10

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by YFforever2022** [comment]
Sorry, I modified part of the source code to export the ncnn-supporting model. I commented out lines 398-411 in ultralytics/nn/modules.py and replaced them with the following:
# def forward(self, x):
    #     shape = x[0].shape  # BCHW
    #     for i in range(self.nl):
    #         x[i] = torch.cat((self.cv2[i](x[i]), self.cv3[i](x[i])), 1)
    #     if self.training:
    #         return x
    #     elif self.dynamic or self.shape != shape:
    #         self.anchors, self.strides = (x.transpose(0, 1) for x in make_anchors(x, self.stride, 0.5))
    #         self.shape = shape
    # 
    #     box, cls = torch.cat([xi.view(shape[0], self.no, -1) for xi in x], 2).split((self.reg_max * 4, self.nc), 1)
    #     dbox = dist2bbox(self.dfl(box), self.anchors.unsqueeze(0), xywh=True, dim=1) * self.strides
    #     y = torch.cat((dbox, cls.sigmoid()), 1)
    #     return y if self.export else (y, x)

    def forward(self, x):
        z = []  # inference output
        for i in range(self.nl):
            boxes = self.cv2[i](x[i]).permute(0, 2, 3, 1)
            scores = self.cv3[i](x[i]).sigmoid().permute(0, 2, 3, 1)
            feat = torch.cat((boxes, scores), -1)
            z.append(feat)
        return tuple(z)

Restore the source code and everything works fine

**Comment by lyb36524** [comment]
Hello, I have encountered the same problem. Is there a solution now?

**Comment by lyb36524** [comment]
refer to this：https://github.com/FeiGeChuanShu/ncnn-android-yolov8/issues/8#issuecomment-1553399271
When you need recognition or training, you need to change back to the original version, otherwise an error will be reported, and only modifications need to be made during conversion.

**Comment by glenn-jocher** [comment]
@lyb36524 hello,

Thank you for bringing this issue to our attention. We would recommend that you restore the original source code if you encounter this error during recognition or training with YOLOv8.  Modifications for conversion purposes can be made separately. 

Please let us know if you have any further questions or concerns.

Best regards,
Glenn Jocher (maintainer of Ultralytics YOLOv8 repo)
