### ISSUE TITLE
Need to analyze label probability distribution

### ISSUE THREAD

**Issue by nikbobo** [ultralytics/ultralytics#1049]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

In YOLOv5 we can see the label probability distribution in label*.jpg

### Use case

Auto generate label*.jpg like YOLOv5

### Additional

In YOLOv5 it seems using plot_labels to generate that, but not in YOLOv8.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@nikbobo hi thanks for the reporting! I've made a PR to add this functionality. :) #1078
