### ISSUE TITLE
Error in CPP Inference Example

### ISSUE THREAD

**Issue by anzenchitai** [ultralytics/ultralytics#1050]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Integrations, Other

### Bug

`Running on CUDA
[ERROR:0@0.122] global net_impl.cpp:1164 cv::dnn::dnn4_v20221220::Net::Impl::getLayerShapesRecursively OPENCV/DNN: [Reshape]:(onnx_node!/model.22/dfl/Reshape): getMemoryShapes() throws exception. inputs=1 outputs=1/1 blobs=0
[ERROR:0@0.122] global net_impl.cpp:1167 cv::dnn::dnn4_v20221220::Net::Impl::getLayerShapesRecursively     input[0] = [ 1 64 6300 ]
[ERROR:0@0.122] global net_impl.cpp:1171 cv::dnn::dnn4_v20221220::Net::Impl::getLayerShapesRecursively     output[0] = [ ]
[ERROR:0@0.122] global net_impl.cpp:1177 cv::dnn::dnn4_v20221220::Net::Impl::getLayerShapesRecursively Exception message: OpenCV(4.7.0) C:\Users\nginx\Downloads\cvbuild\modules\dnn\src\layers\reshape_layer.cpp:109: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'cv::dnn::computeShapeByReshapeMask'

OpenCV(4.7.0) C:\Users\nginx\Downloads\cvbuild\modules\dnn\src\layers\reshape_layer.cpp:109: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'cv::dnn::computeShapeByReshapeMask'`

### Environment

YOLO: Ultralytics YOLOv8.0.40 Python-3.9.13 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3080, 10239MiB)
OpenCV2: 4.7.0
OS: Windows 10 19045.2546

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by JustasBart** [comment]
Hi @anzenchitai I can see the mention of **[1, 64, 6300]** in your seg fault, can you confirm if you are using a custom exported model as the yolov8s.pt ONNX should look like this **[1, 84, 6300]**. If you are using a custom exported model please make sure that your export command looks something similar to:
```
yolo export \
model=yolov8s.pt \
imgsz=[480,640] \
format=onnx \
opset=12
```

Other than that I've seen a seg fault that looked very similar to this:
**(-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'cv::dnn::computeShapeByReshapeMask'**

in the past and had fixed it by re-building my OpenCV. If you're able to rebuild your OpenCV and if you would like to try I don't have a full guide out as of yet, but you can look [here for clues](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX/issues/2) as per the main outlines of how it's done.

There's also no harm if you were to try running the sample on your **CPU** just to make sure.

Feel free to follow up on this and good luck :rocket:

**Comment by anzenchitai** [comment]
> Hi @anzenchitai I can see the mention of **[1, 64, 6300]** in your seg fault, can you confirm if you are using a custom exported model as the yolov8s.pt ONNX should look like this **[1, 84, 6300]**. If you are using a custom exported model please make sure that your export command looks something similar to:
> 
> ```
> yolo export \
> model=yolov8s.pt \
> imgsz=[480,640] \
> format=onnx \
> opset=12
> ```
> 
> Other than that I've seen a seg fault that looked very similar to this: **(-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'cv::dnn::computeShapeByReshapeMask'**
> 
> in the past and had fixed it by re-building my OpenCV. If you're able to rebuild your OpenCV and if you would like to try I don't have a full guide out as of yet, but you can look [here for clues](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX/issues/2) as per the main outlines of how it's done.
> 
> There's also no harm if you were to try running the sample on your **CPU** just to make sure.
> 
> Feel free to follow up on this and good luck 🚀

Thank you for the reply. I spent hours re-doing all the steps to no avail. After many hours of depression and pain, turns out it was zlib missing from my system all along.

**Comment by JustasBart** [comment]
Good man @anzenchitai! I'm glad you were able to sort it out!

Sorry it took you a while, but you got it in the end and can now enjoy running YOLO models via C++ :rocket:

**Comment by anzenchitai** [comment]
> Good man @anzenchitai! I'm glad you were able to sort it out!
> 
> Sorry it took you a while, but you got it in the end and can now enjoy running YOLO models via C++ 🚀

Hello again. I've been having problems with performance using ONNX. I tried to infer with TensorRT but failed every single time. Is it possible that you could provide us with a TensorRT example in C++ as well? Thanks for your work.

**Comment by JustasBart** [comment]
Hi @anzenchitai I haven't touched TensorRT at all, I mean I can give it a shot just to see what's going on, but I wouldn't be too hopeful about it...
