### ISSUE TITLE
YoloV8 export to tensorflowlite doen't work

### ISSUE THREAD

**Issue by endersonO** [ultralytics/ultralytics#1054]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

I just followed a tutorial and ran the following command. 

!yolo export model=yolov8n.pt format=tflite

Even though I didn't use my custom model, I obtained this result:

ONNX: starting export with onnx 1.13.0...
ONNX: export success  0.7s, saved as yolov8n.onnx (12.2 MB)
WARNING:absl:Please consider providing the trackable_obj argument in the from_concrete_functions. Providing without the trackable_obj argument is deprecated and it will use the deprecated conversion path.
TensorFlow SavedModel: export failure  24.2s: [Errno 2] No such file or directory: '\\tmp\\meta.txt'

I looked into your documentation, but I couldn't find anything about this issue. 

### Minimal Reproducible Example

yolo export model=yolov8n.pt format=tflite

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@endersonO thanks for the bug report! This is a windows bug that has been resolved in the latest 8.0.41 release.

Be aware tho that while you will be able to export to TF formats with 8.0.41 there is a bounding box silent error still present in #992, #1059.

Closing as original issue is now resolved. Please re-open or let us know if 8.0.41 does not resolve this issue for you, thank you!

**Comment by glenn-jocher** [comment]
@endersonO YOLOv8 TensorFlow exports are now fully working on Windows :)

**Comment by endersonO** [comment]
thanks. I'm try to export one yolov8 model to tflite and use it in an app android example (tflite documentation), and it doesn't work. I'm really don't know if the problem if with the app example or the model exported. If you know about one example exporting yolo model to tflite for use in an android app.  I would really appreciate it.

**Comment by glenn-jocher** [comment]
Yes you can deploy to Android using HUB to see how your model performs on mobile at https://hub.ultralytics.com.

@sergiossm is our lead mobile developer on HUB.

**Comment by endersonO** [comment]
I tried to start this new issue:
with ultralitics hub, I have trained my own model with my custom data. 
In my computer show this
![image](https://user-images.githubusercontent.com/42153113/221927858-4a9da0dd-6603-4e09-b8aa-0a89522c5bd9.png)

but in ultralitics hub show this
![image](https://user-images.githubusercontent.com/42153113/221927977-395d106e-b47c-4151-ad27-c222e53956bb.png)

![image](https://user-images.githubusercontent.com/42153113/221928031-3a4cdc49-de08-44a8-9fbd-5dfc9210aca5.png)
![image](https://user-images.githubusercontent.com/42153113/221928088-726e8ae3-68f1-4d83-9025-f33e7cb42e5c.png)

the problem happens when I use my devices in local. 

another thing is I cannot train with yolov8 just with yoloV5

**Comment by camachoandres88** [comment]
@endersonO were you able to use yolov8 on  your own android app ??

**Comment by glenn-jocher** [comment]
@camachoandres88 As of the current version of Ultralytics, our primary focus has been to optimize performance and features in YOLOv8 models when used natively. Therefore, exporting YOLOv8 models to be used in an Android app may not work as expected as it's not our main usage.

However, support and improvements for much broader deployment options, including usage in an Android app, is something that we plan to work on in the future. We understand the importance of incorporating YOLOv8 in various applications and are committed to extending its compatibility. For now, we appreciate your patience and encourage you to continue using YOLOv8 in the recommended environment.

Stay tuned for future updates! And of course, if you happen to find a solution or workaround in the meantime, we'd love to hear about it.

**Comment by cbiras** [comment]
@glenn-jocher any updates on the Android/Mobile work in progress for yolov8?

**Comment by glenn-jocher** [comment]
Hi @cbiras, thanks for checking in! 🚀 We're actively working on enhancing mobile compatibility for YOLOv8, including Android support. While I don't have a specific timeline to share at this moment, rest assured that it's a priority for us. We'll definitely keep the community updated as soon as we have significant developments. Stay tuned!
