### ISSUE TITLE
accuracy dose not showing up

### ISSUE THREAD

**Issue by s4ki3f** [ultralytics/ultralytics#1055]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I am working on a classification model and I saved the best weight in Google drive connected to google colab. In my previous run a few days back it was showing top 5 accuracy confidence based on the dataset.
![image](https://user-images.githubusercontent.com/29111757/219982475-5f8b69f9-5a50-443b-8746-f59136ce4123.png)
today, when I get back to work it is not showing.
![image](https://user-images.githubusercontent.com/29111757/219982514-17f38e5d-9b8c-40ab-b1d1-a496f553f742.png)
It can be something wrong from my end.. If I am help me to fix it

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@s4ki3f we had double-softmax bug was resolved in 8.0.41, so just upgrade your ultralytics with pip install -U ultralytics and this should be resolved.

Closing now but let us know if your issue is not resolved in the latest version of the package, thanks!
