### ISSUE TITLE
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.HalfTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

### ISSUE THREAD

**Issue by jia0511** [ultralytics/ultralytics#1056]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

from ultralytics import YOLO
import os
# Load a model
model = YOLO("./yolov8m.yaml")  # build a new model from scratch
model = YOLO("/home/ubuntu/project/YOLOv8/runs/detect/train8/weights/best.pt")  # load a pretrained model (recommended for training)
results = model.predict(source="./8cffd70d71baab6d72b2c1082e7ebcab.jpg", save=True, save_txt=True)

print(results)
success = model.export(format="onnx")  # export the model to ONNX format

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@jia0511 hi, I can't reproduce the issue with the following script:
```python
model = YOLO("yolov8n.pt") # load a pretrained model (recommended for training)
results = model.predict(source="ultralytics/assets/bus.jpg", save=True, save_txt=True)

print(results)
success = model.export(format="onnx") # export the model to ONNX format

```
![image](https://user-images.githubusercontent.com/61612323/220023380-9465c26f-a713-4f35-962a-1b1852ad224e.png)

**Comment by glenn-jocher** [comment]
@Laughing-q oh that's really strange, your screenshot shows recommended commands with task=segment but your model is `yolov8n.pt`

**Comment by glenn-jocher** [comment]
@Laughing-q @jia0511 everything looks good on Colab for me. Model exports successfully and with correct task:
<img width="957" alt="Screenshot 2023-02-20 at 11 31 03" src="https://user-images.githubusercontent.com/26833433/220080774-10435a02-8022-48ac-aef5-e2a069233d76.png">

**Comment by glenn-jocher** [comment]
@jia0511 I also tried to predict before export like you showed and everything also works correctly:
<img width="1134" alt="Screenshot 2023-02-20 at 11 34 12" src="https://user-images.githubusercontent.com/26833433/220081472-100d4b09-cda4-4660-a39c-e906589aeaa4.png">

**Comment by Laughing-q** [comment]
@glenn-jocher oh I think that's because my local pt is outdated, and I re-downloaded the weight and tested again it looks correct!
![pic-selected-230220-1842-33](https://user-images.githubusercontent.com/61612323/220083229-4cbf2118-a23f-4a23-9bd5-a66ffe5fe56d.png)
