### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by gitillbr** [ultralytics/ultralytics#1060]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

yolo predict model=yolov8n.pt source="https://ultralytics.com/images/bus.jpg"

Then report an error
Traceback (most recent call last):
  File "/root/miniconda3/bin/yolo", line 33, in <module>
    sys.exit(load_entry_point('ultralytics==8.0.41', 'console_scripts', 'yolo')())
  File "/root/miniconda3/bin/yolo", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration

### Additional

'ultralytics==8.0.41

**Comment by Laughing-q** [comment]
@gitillbr the same command work fine to me.
![image](https://user-images.githubusercontent.com/61612323/220022669-3d291546-9a49-4971-adc7-d6da49276c23.png)
