### ISSUE TITLE
Exporting ONNX models

### ISSUE THREAD

**Issue by taojishou** [ultralytics/ultralytics#10660]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Exporting ONNX models: does it support int8 quantization? NNCF supports Post-Training Quantization of YOLOv8 ONNX Model.

**Comment by glenn-jocher** [comment]
@taojishou hi there! 👋

Great question! Yes, YOLOv8 supports exporting models to ONNX with INT8 quantization. This can greatly reduce the model size and potentially increase inference speed, especially on devices optimized for low-precision computations. 

Here's a snippet on how to export a YOLOv8 model to ONNX format with INT8 quantization:

```python
from ultralytics import YOLO

# Load your YOLOv8 model
model = YOLO('yolov8n.pt')

# Export to ONNX with INT8 quantization
model.export(format='onnx', int8=True)
```

Or using the CLI:

```bash
yolo export model=yolov8n.pt format=onnx int8=True
```

Ensure to validate the implementation and performance of the quantized model, as quantization may slightly affect the accuracy.

Let us know how it goes! 🚀

**Comment by taojishou** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/20332592/00dbd232-116e-4531-a0b9-a8e032792d17)

It seems to be ineffective, with the addition of int8 parameters, the model size has not changed much
yolo export model=/home/tao/runs/detect/train9/weights/best.pt format=onnx int8=True

**Comment by glenn-jocher** [comment]
@taojishou hi there! 😊

It looks like you've successfully used the INT8 quantization for your ONNX export. However, if you're seeing minimal changes in the model size, it could be due to how the quantization process was applied or the specific content of your model.

Here are a couple of things you might want to check:
- **Review Model Complexity**: Simpler models or models with fewer trainable parameters might not see as significant a reduction in size.
- **Ensure Successful Quantization**: Make sure that the quantization process is applying as intended. You can verify this by examining the details of the exported ONNX model to confirm if the data types of the layers are indeed INT8.

Here’s a quick way to check the data types in your ONNX model:
```python
import onnx

# Load your ONNX model
model = onnx.load('/path/to/your/model.onnx')

# Check data types of each layer
for tensor in model.graph.initializer:
    print(tensor.name, tensor.data_type)
```

This script helps you identify what data types are being used in your model. Let us know if everything checks out or if you need further assistance! 🚀

**Comment by taojishou** [comment]
model.0.conv.weight 1
model.0.conv.bias 1
model.1.conv.weight 1
model.1.conv.bias 1
model.2.cv1.conv.weight 1
model.2.cv1.conv.bias 1
model.2.cv2.conv.weight 1
model.2.cv2.conv.bias 1
model.2.m.0.cv1.conv.weight 1
model.2.m.0.cv1.conv.bias 1
model.2.m.0.cv2.conv.weight 1
model.2.m.0.cv2.conv.bias 1
model.3.conv.weight 1
model.3.conv.bias 1
model.4.cv1.conv.weight 1
model.4.cv1.conv.bias 1
model.4.cv2.conv.weight 1
model.4.cv2.conv.bias 1
model.4.m.0.cv1.conv.weight 1
model.4.m.0.cv1.conv.bias 1
model.4.m.0.cv2.conv.weight 1
model.4.m.0.cv2.conv.bias 1
model.4.m.1.cv1.conv.weight 1
model.4.m.1.cv1.conv.bias 1
model.4.m.1.cv2.conv.weight 1
model.4.m.1.cv2.conv.bias 1
model.5.conv.weight 1
model.5.conv.bias 1
model.6.cv1.conv.weight 1
model.6.cv1.conv.bias 1
model.6.cv2.conv.weight 1
model.6.cv2.conv.bias 1
model.6.m.0.cv1.conv.weight 1
model.6.m.0.cv1.conv.bias 1
model.6.m.0.cv2.conv.weight 1
model.6.m.0.cv2.conv.bias 1
model.6.m.1.cv1.conv.weight 1
model.6.m.1.cv1.conv.bias 1
model.6.m.1.cv2.conv.weight 1
model.6.m.1.cv2.conv.bias 1
model.7.conv.weight 1
model.7.conv.bias 1
model.8.cv1.conv.weight 1
model.8.cv1.conv.bias 1
model.8.cv2.conv.weight 1
model.8.cv2.conv.bias 1
model.8.m.0.cv1.conv.weight 1
model.8.m.0.cv1.conv.bias 1
model.8.m.0.cv2.conv.weight 1
model.8.m.0.cv2.conv.bias 1
model.9.cv1.conv.weight 1
model.9.cv1.conv.bias 1
model.9.cv2.conv.weight 1
model.9.cv2.conv.bias 1
model.12.cv1.conv.weight 1
model.12.cv1.conv.bias 1
model.12.cv2.conv.weight 1
model.12.cv2.conv.bias 1
model.12.m.0.cv1.conv.weight 1
model.12.m.0.cv1.conv.bias 1
model.12.m.0.cv2.conv.weight 1
model.12.m.0.cv2.conv.bias 1
model.15.cv1.conv.weight 1
model.15.cv1.conv.bias 1
model.15.cv2.conv.weight 1
model.15.cv2.conv.bias 1
model.15.m.0.cv1.conv.weight 1
model.15.m.0.cv1.conv.bias 1
model.15.m.0.cv2.conv.weight 1
model.15.m.0.cv2.conv.bias 1
model.16.conv.weight 1
model.16.conv.bias 1
model.18.cv1.conv.weight 1
model.18.cv1.conv.bias 1
model.18.cv2.conv.weight 1
model.18.cv2.conv.bias 1
model.18.m.0.cv1.conv.weight 1
model.18.m.0.cv1.conv.bias 1
model.18.m.0.cv2.conv.weight 1
model.18.m.0.cv2.conv.bias 1
model.19.conv.weight 1
model.19.conv.bias 1
model.21.cv1.conv.weight 1
model.21.cv1.conv.bias 1
model.21.cv2.conv.weight 1
model.21.cv2.conv.bias 1
model.21.m.0.cv1.conv.weight 1
model.21.m.0.cv1.conv.bias 1
model.21.m.0.cv2.conv.weight 1
model.21.m.0.cv2.conv.bias 1
model.22.cv2.0.0.conv.weight 1
model.22.cv2.0.0.conv.bias 1
model.22.cv2.0.1.conv.weight 1
model.22.cv2.0.1.conv.bias 1
model.22.cv2.0.2.weight 1
model.22.cv2.0.2.bias 1
model.22.cv2.1.0.conv.weight 1
model.22.cv2.1.0.conv.bias 1
model.22.cv2.1.1.conv.weight 1
model.22.cv2.1.1.conv.bias 1
model.22.cv2.1.2.weight 1
model.22.cv2.1.2.bias 1
model.22.cv2.2.0.conv.weight 1
model.22.cv2.2.0.conv.bias 1
model.22.cv2.2.1.conv.weight 1
model.22.cv2.2.1.conv.bias 1
model.22.cv2.2.2.weight 1
model.22.cv2.2.2.bias 1
model.22.cv3.0.0.conv.weight 1
model.22.cv3.0.0.conv.bias 1
model.22.cv3.0.1.conv.weight 1
model.22.cv3.0.1.conv.bias 1
model.22.cv3.0.2.weight 1
model.22.cv3.0.2.bias 1
model.22.cv3.1.0.conv.weight 1
model.22.cv3.1.0.conv.bias 1
model.22.cv3.1.1.conv.weight 1
model.22.cv3.1.1.conv.bias 1
model.22.cv3.1.2.weight 1
model.22.cv3.1.2.bias 1
model.22.cv3.2.0.conv.weight 1
model.22.cv3.2.0.conv.bias 1
model.22.cv3.2.1.conv.weight 1
model.22.cv3.2.1.conv.bias 1
model.22.cv3.2.2.weight 1
model.22.cv3.2.2.bias 1
model.22.dfl.conv.weight 1    


when converting, I didn't notice calling nncm

**Comment by taojishou** [comment]
when I output OpenVino format, it's ok

**Comment by taojishou** [comment]
But  I need is Int8 quantization in onnx format~  not openvino

**Comment by glenn-jocher** [comment]
Hello! 👋

For INT8 quantization in the ONNX format with YOLOv8, you'll need to use an external tool as YOLOv8's export functionality currently doesn't include direct INT8 support for ONNX. One common approach is to use tools like ONNX Runtime or leverage the post-training quantization features of NVIDIA's TensorRT after converting the model to ONNX. Here’s a quick guide on how you could potentially do this using TensorRT:

1. First, export your model to ONNX:
   ```bash
   yolo export model=yolov8n.pt format=onnx imgsz=640 simplify
   ```

2. Then, use TensorRT’s `trtexec` command or write a custom script in Python to apply INT8 quantization.

While this adds an extra step, it allows for flexibility with quantization precision and compatibility across various devices. Let me know if you have any more questions! 🚀

**Comment by taojishou** [comment]
Hope future   support ONNX's Int8 quantization

**Comment by glenn-jocher** [comment]
Hey there!

We appreciate your interest in enhancing YOLOv8 with ONNX INT8 quantization support! 🚀 It's definitely on our radar for future enhancements. For now, you can manually apply INT8 quantization using tools like ONNX Runtime or TensorRT after exporting the model to ONNX format.

Thanks for your suggestion, and keep your eyes peeled for updates! 🌟
