### ISSUE TITLE
loading yolov5su.pt but gives wrong type?

### ISSUE THREAD

**Issue by mrsahabu** [ultralytics/ultralytics#1067]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

`In [10]: m = YOLO('yolov5su.pt')
In [11]: m.type
Out[11]: 'v8'
`

**Comment by AyushExel** [comment]
Don't worry about the type. It's a hardcoded placeholder when we decide to enable different types of architectures. It should not effect execution in any way
