### ISSUE TITLE
Implement `yolo test` feature

### ISSUE THREAD

**Issue by validatedev** [ultralytics/ultralytics#1068]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

As we talked in https://github.com/ultralytics/ultralytics/pull/704#issuecomment-1409367229, the issue belongs to the `yolo test` feature.

### Use case

If someone wants to use their test dataset without touching anything, it's going to be handy.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by validatedev** [comment]
It is not stale and work in progress.

**Comment by validatedev** [comment]
I'll open a new PR for the feature. Sorry about being that late as I had some work to do and couldn't really allocate time to do the PR.

**Comment by glenn-jocher** [comment]
@validatedev thank you for letting us know, and there's no need to apologize. We appreciate your contribution and understand that everyone has other responsibilities outside of open source contributions. When you're ready to submit the new PR, please make sure it has a clear description of the feature, its use case, and implementation details if applicable. Let us know if you need any assistance or have any questions along the way. We look forward to reviewing your PR and keeping YOLOv8 moving forward!

**Comment by validatedev** [comment]
@glenn-jocher Thanks for your kindness and understanding, I appreciate it 🙌 For the PR-related topics, I absolutely will!

**Comment by glenn-jocher** [comment]
@validatedev You're welcome! We're always here to help and support our community. As for your PR, we look forward to seeing your proposed feature and hope it can be a valuable addition to the YOLOv8 project. Don't hesitate to reach out if you have any questions or encounter any issues during the PR process, and please remember to follow our documentation and guidelines for contributing to YOLOv8. Thank you for your contributions and support!

**Comment by validatedev** [comment]
It is not stale and work in progress.

**Comment by glenn-jocher** [comment]
@validatedev hi there, thank you for letting us know that the issue is still being worked on and is not stale. We appreciate your dedication and commitment to contributing to YOLOv8. If you have any questions or need any further assistance as you continue working on this feature, please don't hesitate to reach out. We're always here to help and support our community. Thank you again for your contributions to YOLOv8!

**Comment by validatedev** [comment]
Thank you @glenn-jocher, finally created a PR for the issue :) Looking forward to get the PR merged!

**Comment by glenn-jocher** [comment]
@validatedev That's great news, thank you for submitting a PR for the `yolo test` feature. We appreciate your contribution and look forward to reviewing your changes. Our team will give it the attention it deserves and respond as soon as possible, but please note that it may take some time for us to thoroughly review and test your code. In the meantime, keep up the great work, and feel free to continue contributing to YOLOv8 in any way you can. Thank you again for your contribution and support!

**Comment by validatedev** [comment]
Closing as it is not accepted, could be seen from https://github.com/ultralytics/ultralytics/pull/3006#issuecomment-1775819363.

**Comment by glenn-jocher** [comment]
@validatedev thank you for understanding our decision on this issue. After careful consideration and internal discussions, the team has decided not to further pursue this proposal at this time. We appreciate your dedication and effort in proposing new features and improvements to YOLOv8. Rest assured that all input is valuable in helping us shape the roadmap of the project. Feel free to continue providing valuable insights and suggestions, you're an important part of our community.
