### ISSUE TITLE
How to save the timestamp at which the YOLOv8 detects an object in a non live detection video and how to add it into the video?

### ISSUE THREAD

**Issue by ratfyp6** [ultralytics/ultralytics#10694]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

please also tell me where in the code do i need to replace with my own path

### Additional

ur help will be greatly appreciated and that u can get back to me as soon as possible.

**Comment by glenn-jocher** [comment]
@ratfyp6 certainly! To save the timestamp when YOLOv8 detects an object in your video and include it in the video output, you can follow these generalized steps:

1. Obtain the frame rate of your video using a package like OpenCV.
2. As you process each frame for detection, calculate the current timestamp by dividing the current frame number by the frame rate.
3. Use OpenCV's `cv2.putText()` method to draw the timestamp onto each frame where a detection occurs.

Here's a simple code snippet to illustrate these steps:

```python
import cv2
from ultralytics import YOLO

# Load the model
model = YOLO('yolov8n.pt')

# Open video
cap = cv2.VideoCapture('path/to/your/video.mp4')
frame_rate = cap.get(cv2.CAP_PROP_FPS)

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Get current frame number
    frame_num = int(cap.get(cv2.CAP_PROP_POS_FRAMES))
    
    # Process frame for detections
    results = model(frame)
    
    # If detections occur, calculate current timestamp and add to frame
    if len(results) > 0:
        timestamp = frame_num / frame_rate
        cv2.putText(frame, f'Timestamp: {timestamp:.2f}s', (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 
                    1, (255, 255, 255), 2, cv2.LINE_AA)
    
        # Here you can save the frame or timestamp if needed

    # Display the frame
    cv2.imshow('Frame', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
```

To save the modified video, you may use OpenCV's `VideoWriter` class. Ensure you replace `'path/to/your/video.mp4'` with the path to your video file.

This should answer your query! Keep exploring, and if there’s anything more we can do to help, please reach out 🚀.
