### ISSUE TITLE
Inquiry Regarding Cropping Objects from YOLOv8 Instance Segmentation Predictions Images 

### ISSUE THREAD

**Issue by divyvijay** [ultralytics/ultralytics#10702]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Question
I am currently working on an object detection project using YOLOv8 instance segmentation, and I have successfully trained my model. To crop or save images, I am using the following code, i.e., save_crops=true. However, this will provide the whole cropped image instead of the predicted object.I want to save only the predicted instance object from the image, not the whole image. For reference, I have shared the images.
![Detected_obj_instace_seg](https://github.com/ultralytics/ultralytics/assets/154326633/203e0b55-b386-4396-997f-1ba7d05d0b26)
![cropped_image](https://github.com/ultralytics/ultralytics/assets/154326633/27f08e57-2989-4b28-820e-2e79f78c52b8)

**Comment by glenn-jocher** [comment]
Hey there! 👋

It looks like you're interested in saving just the segmented object from your YOLOv8 instance segmentation predictions. For this purpose, after obtaining the segmentation masks, you can apply the mask on the original image to get only the area of the detected object. Here's a quick example of how you might achieve this:

```python
from PIL import Image
import numpy as np

# Assuming 'results' is the output from your model prediction
for i, (mask, box) in enumerate(zip(results.masks, results.boxes)):
    # Convert boolean mask to uint8 binary mask
    binary_mask = mask.numpy().astype(np.uint8) * 255
    mask_img = Image.fromarray(binary_mask)

    # Crop the original image to the bounding box
    original_img_cropped = original_img.crop((box.xyxy))

    # Apply the mask to the cropped image
    object_img = Image.composite(original_img_cropped, Image.new('RGB', original_img_cropped.size, 0), mask_img)
    
    # Save the object image
    object_img.save(f'object_{i}.png')
```

In this example, we're iterating over each detected object, converting the mask to a binary format, and then applying that mask to the area of the original image defined by the bounding box. This way, you get just the object itself, not the entire image. You might need to adjust the code slightly based on your exact setup but this should give you a good starting point. 

Hope that helps! Let us know if you have further questions. 🚀

**Comment by divyvijay** [comment]
Hello, I am using CLI commands to get results and results are saved in other folders. In above code, do i need to pass the folder path or else. Furthermore, once passed, it shows an error "AttributeError: 'str' object has no attribute 'masks'". Also is this masking is same as instance label after prediction ?

**Comment by glenn-jocher** [comment]
Hello! 👋

It sounds like you're running into a couple of issues using the CLI commands and handling the results in Python. Let's address your questions:

1. **Folder Path:** If you're getting results saved in other folders and want to process them in your Python code, you indeed need to load these images using something like `PIL.Image.open('path/to/your/image.jpg')` before you apply any operations.

2. **Attribute Error:** The error you're seeing suggests that a string object is being used where a `Results` object is expected. Make sure you're loading your model and running predictions in Python as shown below, and not just passing image paths as strings:
   ```python
   from ultralytics import YOLO

   model = YOLO('path/to/model.pt')
   results = model('path/to/image.jpg')  # This returns a 'Results' object
   ```

3. **Masking vs. Instance Label:** The masks obtained from instance segmentation represent the shape of each object instance as a binary mask. It's different from just the class label since it provides the exact outline of the object within the bounding box.

If you're continuing to face issues, consider checking the way you're managing file paths or how you're invoking the CLI commands to ensure alignment with your Python script context. 

Hope this clears things up! Let me know if there's anything else you need. 😊

**Comment by divyvijay** [comment]
Thank you for the response. Here, I am facing another challenge. As I am unable to get mask after the prediction, how could I get the masks after prediction. After the prediction, all I get is the cropped image (not the cropped object) along with txt file. How could I use this to get the predicted object? Below is my code along with result.

```
class ABCDataset:
    def __init__(self, masks, boxes, original_image):
        self.masks = masks
        self.boxes = boxes
        self.original_image = original_image

    def __len__(self):
        return len(self.masks)

    def __getitem__(self, idx):
        mask = self.masks[idx]
        box = self.boxes[idx]

        # Convert boolean mask to uint8 binary mask
        binary_mask = np.array(mask.cpu()).astype(np.uint8) * 255
        mask_img = Image.fromarray(binary_mask)

        # Convert box tensor to a tuple of coordinates
        box_coords = box.int().tolist()

        # Crop the original image to the bounding box
        original_img_cropped = self.original_image.crop(box_coords)

        # Apply the mask to the cropped image
        mask_img_resized = mask_img.resize(original_img_cropped.size)
        object_img = Image.composite(original_img_cropped, Image.new('RGB', original_img_cropped.size, 0), mask_img_resized)

        return object_img, box

# Load the YOLO model
model = YOLO("path/to/model//best.pt")  # load a custom model
# Predict with the model
results = model("/Test_dataset/1.jpg",save_crop=True, save_txt=True, conf=0.50)  # predict on an image
# Debug: print the structure of results
print(results)

# Extract masks and bounding boxes from the results
masks = []
boxes = []

for result in results:
    if hasattr(result, 'masks') and result.masks is not None:
        masks.extend(result.masks.data.cpu().numpy())
    if hasattr(result, 'boxes') and result.boxes is not None:
        boxes.extend(result.boxes.xyxy.cpu().numpy())

# Check if masks and boxes have been correctly extracted
if not masks or not boxes:
    raise ValueError("No masks or boxes found in the results")
    
for i, (mask, box) in enumerate(zip(results.masks, results.boxes)):
    # Convert boolean mask to uint8 binary mask
    binary_mask = mask.numpy().astype(np.uint8) * 255
    mask_img = Image.fromarray(binary_mask)

    # Crop the original image to the bounding box
    original_img_cropped = original_img.crop((box.xyxy))

    # Apply the mask to the cropped image
    object_img = Image.composite(original_img_cropped, Image.new('RGB', original_img_cropped.size, 0), mask_img)
    
    # Save the object image
    object_img.save(f'object_{i}.png')
# Load the original image
original_image = Image.open('1.jpg')

# Initialize the dataset
dataset = RBCDataset(masks, boxes, original_image)

# Loop over the dataset and process each sample
for i, (object_img, box) in enumerate(dataset):
    # Save the object image
    object_img.save(f'object_{i}.png')
```

Terminal Result :
`set/1.jpg: 416x416 1 HYPOCHROMIC, 19.8ms
Speed: 0.6ms preprocess, 19.8ms inference, 0.7ms postprocess per image at shape (1, 3, 416, 416)
Results saved to runs/detect/predict3
1 label saved to runs/detect/predict3/labels
[ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
masks: None
names: {0: 'HYPOCHROMIC', 1: 'MACROCYTE', 2: 'MICROCYTE', 3: 'NORMOCHROMIC', 4: 'NORMOCYTE', 5: 'Ovalocyte'}
obb: None
orig_img: array([[[208, 221, 199],
        [212, 225, 203],
        [214, 226, 206],
        ...,
        [210, 220, 203],
        [210, 220, 203],
        [210, 220, 203]],

       [[209, 222, 200],
        [211, 223, 203],
        [212, 224, 204],
        ...,
        [212, 222, 205],
        [212, 222, 205],
        [211, 221, 204]],

       [[210, 226, 203],
        [211, 223, 203],
        [211, 223, 203],
        ...,
        [212, 222, 205],
        [212, 222, 205],
        [212, 222, 205]],

       ...,

       [[212, 225, 203],
        [212, 225, 203],
        [212, 225, 203],
        ...,
        [179, 176, 191],
        [179, 176, 191],
        [180, 177, 192]],

       [[212, 225, 203],
        [210, 223, 201],
        [209, 222, 200],
        ...,
        [181, 178, 193],
        [181, 178, 193],
        [181, 178, 193]],

       [[212, 225, 203],
        [209, 222, 200],
        [208, 222, 198],
        ...,
        [179, 179, 193],
        [180, 180, 194],
        [180, 180, 194]]], dtype=uint8)
orig_shape: (167, 163)
path: '/home/divyvijay/Divyvijay_Resources_Linux/project/New_Model_Total10Cases_dataset_1/RBC_Sub_types/RBC_subtypes_Instance/Test_dataset/1.jpg'
probs: None
save_dir: 'runs/detect/predict3'
speed: {'preprocess': 0.6213188171386719, 'inference': 19.83165740966797, 'postprocess': 0.6666183471679688}]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[23], line 57
     55 # Check if masks and boxes have been correctly extracted
     56 if not masks or not boxes:
---> 57     raise ValueError("No masks or boxes found in the results")
     59 for i, (mask, box) in enumerate(zip(results.masks, results.boxes)):
     60     # Convert boolean mask to uint8 binary mask
     61     binary_mask = mask.numpy().astype(np.uint8) * 255

ValueError: No masks or boxes found in the results
Selection deleted
`

**Comment by glenn-jocher** [comment]
Hey there! 👋

It looks like the masks aren't being generated as expected. This could be due to a few reasons, such as the model not being configured for instance segmentation or the specific settings used during prediction.

To ensure that your model is set up correctly for instance segmentation and that it generates masks, you should:

1. Verify that your model is indeed an instance segmentation model. If you trained a detection model, it won't generate masks.
2. Ensure that you're using the correct model file that includes segmentation capabilities (e.g., `yolov8n-seg.pt`).

Here's a simplified example of how you might load and run predictions with a segmentation model to ensure masks are included:

```python
from ultralytics import YOLO

# Load the segmentation model
model = YOLO("path/to/your/segmentation_model.pt")

# Run prediction
results = model("path/to/your/image.jpg")

# Check if masks are present
if results.masks:
    print("Masks are available!")
    for i, mask in enumerate(results.masks):
        # Process each mask
        print(f"Processing mask {i}")
else:
    print("No masks found in the results.")
```

Make sure the model file you're loading (`segmentation_model.pt`) is correctly trained for segmentation. If you continue to face issues, it might be helpful to revisit your model training process to ensure it includes segmentation tasks.

Hope this helps! Let me know if there's anything else you need. 😊
