### ISSUE TITLE
Callback functions not called in DDP training

### ISSUE THREAD

**Issue by haimat** [ultralytics/ultralytics#1072]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Multi-GPU

### Bug

When I use callbacks (tested with "on_fit_epoch_end") with YOLOv8, then they are only called when I train with one GPU. As soon as I train with multiple GPUs, the callback functions are not being called anymore.

### Environment

Tested with latest Github version **Ultralytics YOLOv8.0.42 🚀 Python-3.8.10 torch-1.13.0+cu116**

### Minimal Reproducible Example

```python
from ultralytics import YOLO

def yolo_cb_fit_epoch_end(trainer):
    print("\n>>>>>>> YOLO CALLBACK >>>>>>>\n")

model = YOLO("yolov8n.pt")
model.add_callback("on_fit_epoch_end", yolo_cb_fit_epoch_end)
model.train(data="coco128.yaml", device="0,1,2,3", imgsz=640, epochs=1, batch=100)  # with device="0" it works
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@haimat thanks for the bug report. We'll look into it.

**Comment by AyushExel** [comment]
@glenn-jocher I might be missing something simple but the callbacks aren't being called when using loggers?

**Comment by AyushExel** [comment]
@glenn-jocher @Laughing-q @haimat I think this line might be the culprit here https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/engine/model.py#L76
It should be enclosed in `if RANK in [-1, 0]` I think

**Comment by haimat** [comment]
> @haimat @AyushExel this is a great question. This might be very difficult since DDP processes are launched in their own environment. For right now I don't see a clear solution to this. @Laughing-q what do you think?
> 
> <img width="765" alt="Screenshot 2023-02-20 at 20 30 36" src="https://user-images.githubusercontent.com/26833433/220186109-df27db3c-85bc-4f93-b063-498eb6526864.png">
> 

Hmm... Am I wrong or isn't this possible with YOLOv5?

**Comment by Laughing-q** [comment]
> @glenn-jocher @Laughing-q @haimat I think this line might be the culprit here https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/engine/model.py#L76 It should be enclosed in `if RANK in [-1, 0]` I think

I tried to comment this line but it still doesn't work. Also the loggers-related callbacks are internally built and it's not a custom callback so I think that's why our loggers works fine.

**Comment by Laughing-q** [comment]
@haimat hi we'll look into this and try to find a better solution. Until then there's a temporary solution for you that you can explicitly launch DDP:
```python
python -m torch.distributed.run --nproc_per_node 4 your_training_script.py
```

**Comment by haimat** [comment]
@Laughing-q Well, for such a solution we would need a custom training script. But before we write somthing like that, it would be great to know about your plans in this regard. Do you intend to fix this issue within the next days, then we would wait for it - or do you think that a solution might come "someday"?

**Comment by Laughing-q** [comment]
@haimat I'll make a PR today. :)

**Comment by Laughing-q** [comment]
@haimat hi I think the issue has been solved in this PR. :) #1133 
![T9EsMOzjuV](https://user-images.githubusercontent.com/61612323/221120754-caa99eec-6147-40cc-b9fe-27a1d76956bf.png)

**Comment by haimat** [comment]
@Laughing-q Awesome, thanks a lot.
How long does it usually take for such a PR to end up in the main branch?

**Comment by Laughing-q** [comment]
@haimat usually in one day. :) like this PR would be merged later today.

**Comment by haimat** [comment]
@Laughing-q Thanks, I can confirm that the callbacks are working in DDP training now 👍 
Which callback is called once after every training epoch though, even with multiple GPUs in DDP training?
I mean the one closest to where the training script updates the `results.csv` file.

**Comment by Laughing-q** [comment]
@haimat well we don't really build callbacks in `RANK in {0,1}`, but I think this would help you:
```python
from ultralytics import YOLO
from ultralytics.yolo.utils import RANK

def yolo_cb_fit_epoch_end(trainer):
    if RANK in {0, 1}:
        print("\n>>>>>>> YOLO CALLBACK >>>>>>>\n")

model = YOLO("yolov8n.pt")
model.add_callback("on_fit_epoch_end", yolo_cb_fit_epoch_end)
model.train(data="coco128.yaml", device="0,1,2,3", imgsz=640, epochs=1, batch=100)  # with device="0" it works
```

**Comment by haimat** [comment]
Using the `on_model_save` callback seems to be my best option.

**Comment by pderrenger** [comment]
@haimat Absolutely, the `on_model_save` callback will indeed be triggered after each epoch when the model is saved. It's a reliable choice for your requirement. If you have any further questions or need assistance with anything else, feel free to ask!
