### ISSUE TITLE
test_predict_callback_and_setup returns an incorrect shape image

### ISSUE THREAD

**Issue by auspicious-youth** [ultralytics/ultralytics#1074]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

https://github.com/ultralytics/ultralytics/blob/main/tests/test_python.py

Ultralytics YOLOv8.0.41 🚀 Python-3.10.9 torch-1.13.1+cu117 CUDA:0 (Quadro RTX 8000, 48601MiB)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

on_predict_batch_end (810, 3)
test_callback (810, 3)
test_callback 1
tensor([[1.70000e+01, 2.31000e+02, 8.02000e+02, 7.68000e+02, 8.70545e-01, 5.00000e+00],
        [4.90000e+01, 3.99000e+02, 2.45000e+02, 9.03000e+02, 8.68980e-01, 0.00000e+00],
        [6.70000e+02, 3.80000e+02, 8.10000e+02, 8.76000e+02, 8.53604e-01, 0.00000e+00],
        [2.21000e+02, 4.06000e+02, 3.45000e+02, 8.57000e+02, 8.19305e-01, 0.00000e+00],
        [0.00000e+00, 2.55000e+02, 3.20000e+01, 3.25000e+02, 3.46069e-01, 1.10000e+01],
        [0.00000e+00, 5.51000e+02, 6.70000e+01, 8.74000e+02, 3.01294e-01, 0.00000e+00]], device='cuda:0')
image 1/1 /home/root/yolo/yolov8/bus.jpg: 640x480 4 persons, 1 bus, 1 stop sign, 11.7ms
Speed: 1.4ms preprocess, 11.7ms inference, 1.6ms postprocess per image at shape (1, 3, 640, 640)

### Environment

- YOLO : Ultralytics YOLOv8.0.41 🚀 Python-3.10.9 torch-1.13.1+cu117 CUDA:0 (Quadro RTX 8000, 48601MiB)
- OS : Ubuntu20.0.4
- Python : 3.10.9

### Minimal Reproducible Example

```
def test_predict_callback_and_setup():

    def on_predict_batch_end(predictor):
        # results -> List[batch_size]
        path, _, im0s, _, _ = predictor.batch
        print('on_predict_batch_end', im0s[0].shape)
        bs = [predictor.dataset.bs for _ in range(len(path))]
        predictor.results = zip(predictor.results, im0s, bs)

    model = YOLO(MODEL)
    model.add_callback('on_predict_batch_end', on_predict_batch_end)

    dataset = load_inference_source(source=SOURCE, transforms=model.transforms)
    bs = dataset.bs  # noqa access predictor properties
    results = model.predict(dataset, stream=True)  # source already setup
    for _, (result, im0, bs) in enumerate(results):
        print('test_callback', im0.shape)
        cv2.imwrite(f'./runs/{bs}.jpg', im0)
        print('test_callback', bs)
        boxes = result.boxes  # Boxes object for bbox outputs
        print(boxes)

test_predict_callback_and_setup()
```

### Additional

Running the test_predict_callback_and_setup function of this file reveals that the shape of the image has only two return values, one missing, resulting in a distorted saved image with incorrect results.
The value returned in Example is (810, 3); the correct value should be (1080, 810, 3).

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@auspicious-youth thanks for the nice catch! adding the code in the following screenshot should work,
![20230221-144507](https://user-images.githubusercontent.com/61612323/220268006-cd710980-e88e-4516-adb7-c251399b92fc.png)

BTW we've upgraded the `Result` and you can access the im0(ori_img) by the following usage:
```python
model = YOLO(MODEL)
dataset = load_inference_source(source=SOURCE, transforms=model.transforms)
bs = dataset.bs  # noqa access predictor properties
results = model.predict(dataset, stream=True)  # source already setup
for result in results:
    print(result.orig_img.shape)
```
The test script is kind of outdated and we'll update it soon. :)

**Comment by auspicious-youth** [comment]
Yes, it's ok, thanks.

**Comment by pderrenger** [comment]
@auspicious-youth you're welcome! If you have any more questions or need further assistance, feel free to ask. Happy coding!
