### ISSUE TITLE
Get different score every validation with same model, dataset.

### ISSUE THREAD

**Issue by yellowjs0304** [ultralytics/ultralytics#1075]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, thank you for sharing nice work. I'm a beginner of Yolo.
I wondered why score is changed every time.
At first, I compared both of A(the score when validating immediately after training) and score B(testing with validation command, yolo "task=val").
It returns same data specification
- score A `yolo task=segment mode=train data=myData.yaml`
![image](https://user-images.githubusercontent.com/30281608/220247299-b1fda760-8b72-4283-b8d8-09d1811a5e17.png)

- score B : `yolo task=segment mode=val model=myBest.pt data=myData.yaml`
![image](https://user-images.githubusercontent.com/30281608/220247443-1cbfec6a-e306-4031-81e5-bce62e7244f4.png)

So, I tried same command `yolo task=segment mode=val model=myBest.pt data=myData.yaml` in three times.
- 1st
![image](https://user-images.githubusercontent.com/30281608/220248409-581dc4eb-c2d8-4cf9-a603-9aacc941c916.png)

- 2nd
![image](https://user-images.githubusercontent.com/30281608/220248468-e0c5e537-8190-4529-b88b-9b2e5fcc3a1e.png)

- 3rd
![image](https://user-images.githubusercontent.com/30281608/220248495-8f2f34dd-26ca-45b2-ad1f-9f8db3c15aa7.png)

I also checked the visualization results in "runs/val_batchN_pred.jpg", but it looks same prediction.
Why is the score is different every time?

**Comment by Laughing-q** [comment]
@yellowjs0304 I tried the following command(same as yours except `model=yolov8n-seg.pt` and `data=coco128.yaml` 3 times but all the metrics looks the same.
```bash
yolo task=segment mode=val model=yolov8n-seg.pt data=coco128.yaml
```
can't reproduce the issue, I recommend you to use the latest version of package and try again.

**Comment by yellowjs0304** [comment]
@Laughing-q Thank you for fast reply. I already using the latest version.
but, I installed it by "pip install -e .", because I need to modify some of the visualize option(like font, color, ...)

my command `CUDA_VISIBLE_DEVICES=1 yolo task=segment mode=val model=myBest.pt data=myData.yaml imgsz=640 batch=4 workers=1 device=\'0\'`

```
task: segment
mode: train
model: null,
data: myData.yaml
epochs: 500
patience: 50
batch: 2
imgsz: 640
save: true
save_period: -1
cache: false
device: '0'
workers: 2
project: null
name: myModel
exist_ok: false
pretrained: false
optimizer: AdamW
verbose: true
seed: 0
deterministic: true
single_cls: false
image_weights: true
rect: false
cos_lr: false
close_mosaic: 10
resume: false
min_memory: false
overlap_mask: true
mask_ratio: 4
dropout: 0.0
val: true
split: val
save_json: false
save_hybrid: false
conf: null
iou: 0.7
max_det: 300
half: false
dnn: false
plots: true
source: null
show: false
save_txt: false
save_conf: false
save_crop: false
hide_labels: false
hide_conf: false
vid_stride: 1
line_thickness: 3
visualize: false
augment: false
agnostic_nms: false
classes: null
retina_masks: false
boxes: true
format: torchscript
keras: false
optimize: false
int8: false
dynamic: false
simplify: false
opset: null
workspace: 4
nms: false
lr0: 5.0e-05
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 7.5
cls: 0.5
dfl: 1.5
fl_gamma: 0.0
label_smoothing: 0.0
nbs: 64
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.0
copy_paste: 0.0
cfg: null
v5loader: false
tracker: botsort.yaml
save_dir: runs/segment/mymodel

```

**Comment by Laughing-q** [comment]
@yellowjs0304 can you also try the command I used multi-times to see if the metrics are still different?

**Comment by yellowjs0304** [comment]
I got some error like this [issue](https://github.com/ultralytics/ultralytics/issues/585).
But I clone this repo yesterday(23 hours)...Is there any difference between it?
![image](https://user-images.githubusercontent.com/30281608/220265737-0ad558e4-3110-418a-af26-c992cc47464e.png)

**Comment by Laughing-q** [comment]
@yellowjs0304 are you trying this command?
```bash
yolo task=segment mode=val model=yolov8n-seg.pt data=coco128.yaml
```

**Comment by yellowjs0304** [comment]
Yeap, and it return above issue.
`yolo task=segment mode=val model=yolov8n-seg.pt data=coco128.yaml`

**Comment by Laughing-q** [comment]
@yellowjs0304 oh sorry my bad, my local `coco128` actually is segmentation labels, so it works fine to me. You should update `coco128.yaml` to `coco128-seg.yaml`. :)

**Comment by yellowjs0304** [comment]
I found it. It looks like maybe related with the batch size.. 😂
I got different score when i change the batch size to 1,4, 32...

I used the below command.
`CUDA_VISIBLE_DEVICES=1 yolo task=segment mode=val model=yolov8x-seg.pt data=coco128-seg.yaml imgsz=640 batch=1 workers=1 device=\'0\'`

**Comment by Laughing-q** [comment]
@yellowjs0304 yeah `batch-size` could affect the mAP, because we're using `rect` inference when doing evaluation and the rect shape can be a little different across different batch-size.
You can get the same mAP with `rect=False`.

**Comment by yellowjs0304** [comment]
Got it :) Thank you for your help.

**Comment by pderrenger** [comment]
@yellowjs0304 you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with your YOLOv8 segmentation tasks! 😊

**Comment by glenn-jocher** [comment]
You're welcome, @pderrenger! Happy to help. Good luck with your projects, and don't hesitate to reach out if you need more assistance. 😊👍
