### ISSUE TITLE
Slow FPS on GPU

### ISSUE THREAD

**Issue by invo-mwiseman** [ultralytics/ultralytics#1081]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, 

I'm making some FPS comparisons between using YoloV4 Tiny (via darknet), verses YoloV8s (via pytorch/ultralytics). 

I'm trying to keep my product up-to-date with the latest yolo versions, except I'm experiencing a loss of over a half when using Yolov8 (pytorch), when compared to Yolov4 (darknet).

**Here are some code examples of using predict with ultralytics:**
```
model = YOLO("yolov8test.pt", "v8")
# loop ...
results = model.predict(source=frame, verbose=False, imgsz=640, dnn=True, half=True)  
```

Here is the output FPS readings a YoloV8s model via Ultralytics (focus detection FPS): 
![image](https://user-images.githubusercontent.com/98943093/220336369-c86e2ac6-221e-48ae-9698-304a5c4e137d.png)
Stabilizes at around 40 after initial load.

Here is the output FPS readings a small YoloV4 Tiny model via Darknet (focus detection FPS): 
![image](https://user-images.githubusercontent.com/98943093/220335928-856a2f4d-0761-47fc-952a-49b8f5748525.png)
Stabilizes at around 92 after initial load.

I understand that they're two different libraries, but is there anything I can do to to better increase the FPS using Ultralytics? Because the accuracy trade off, verses the more than half FPS drop... Kind of makes the jump to YoloV8 disappointingly pointless.

**Comment by AyushExel** [comment]
What is the number of params in v4 tiny variant that you're using? 
Also, another difference is that you're running v4 tiny on c darknet and v8 in python pytorch right? I guess a better comparison would be if you export it to engine/other formats supported by a c++ runtime and then run inference. 
In terms of usability, what fps are you considering "usable". Imo anything more than 25-30fps is sufficient for real World tasks right? Or is this for a specialised use case?

**Comment by invo-mwiseman** [comment]
> What is the number of params in v4 tiny variant that you're using? Also, another difference is that you're running v4 tiny on c darknet and v8 in python pytorch right? I guess a better comparison would be if you export it to engine/other formats supported by a c++ runtime and then run inference. In terms of usability, what fps are you considering "usable". Imo anything more than 25-30fps is sufficient for real World tasks right? Or is this for a specialised use case?

I wasn't sure if pytorch used c++ like darknet did when predicting. I suppose that may just come down to c++ being a whole lot faster than python. I will export to engine and give this a try, and report back.

As for what's deemed as usable in a commercial application, if I'm video capturing at 120 FPS, I'd expect detection FPS no less than half that. For example the application may move something, lower FPS results in staggered movements that look un-natural.

**Comment by invo-mwiseman** [comment]
> 

I'm not sure what you're referring to as params, can you please give an example? Both sets of weights, in PyTorch and darknet, were run at performance size 640.

**Comment by AyushExel** [comment]
I'm on phone right now. I'll respond with screenshots later tonight which might make things clear

**Comment by AyushExel** [comment]
So v4-tiny has 6M params and v8s has more than 22M params hence the speed difference. A fair comparison would be if you use v8n model which has less than 4M params

**Comment by glenn-jocher** [comment]
@invo-mwiseman YOLOv8s is a much more accurate model than YOLOv4-tiny, so I don't understand the apples to oranges comparison you're doing.


@AyushExel YOLOv8s has 11M params, not 22M, see https://github.com/ultralytics/ultralytics#models

**Comment by AyushExel** [comment]
Oh Yeah! my bad I was looking at the m model. Thanks for correcting!

**Comment by invo-mwiseman** [comment]
> @invo-mwiseman YOLOv8s is a much more accurate model than YOLOv4-tiny, so I don't understand the apples to oranges comparison you're doing.
> 
> @AyushExel YOLOv8s has 11M params, not 22M, see https://github.com/ultralytics/ultralytics#models

I am not comparing accuracy. I'm comparing the computation speeds, which are much slower in pytorch verses darknet.



> So v4-tiny has 6M params and v8s has more than 22M params hence the speed difference. A fair comparison would be if you use v8n model which has less than 4M params

I will give a nano model a try and see.

**Comment by anzenchitai** [comment]
I am using Win32 BitBlt to capture my screen at 165 FPS and somehow I can't get YOLOv8n to detect faster than 55-65 FPS.

**Comment by invo-mwiseman** [comment]
> 

YoloV4-Tiny has 22M params, and I've just tried a YoloV8n model which as 6M params, and as suspected v4 model is still much faster when running through darknet. The AP of both these models are about the same.

So there appears to be a clear performance issue, when comparing PyTorch to Darknet, in regards to predicting via Ultralytics.

**Comment by AyushExel** [comment]
V4 tiny has 6.06 M params with 21 mAP
V8n has 3.2 M params with 37 mAP 
Where are you getting your numbers from?

**Comment by invo-mwiseman** [comment]
It doesn't matter. Everyone has different figures it seems on this thread.

PyTorch is just a lot slower than Darknet. Which is disappointing considering that YoloV8 has better accuracy. FPS matters a lot, it's a shame that the FPS differences between PyToch and Darknet is so significant.

On 22 Feb 2023 20:38, Ayush Chaurasia ***@***.***> wrote:

V4 tiny has 6.06 M params with 21 mAP
V8n has 3.2 M params with 37 mAP
Where are you getting your numbers from?

**Comment by StanleyWQX** [comment]
> It doesn't matter. Everyone has different figures it seems on this thread. PyTorch is just a lot slower than Darknet. Which is disappointing considering that YoloV8 has better accuracy. FPS matters a lot, it's a shame that the FPS differences between PyToch and Darknet is so significant. On 22 Feb 2023 20:38, Ayush Chaurasia ***@***.***> wrote: V4 tiny has 6.06 M params with 21 mAP V8n has 3.2 M params with 37 mAP Where are you getting your numbers from? — Reply to this email directly, view it on GitHub<https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fultralytics%2Fultralytics%2Fissues%2F1081%23issuecomment-1440766120&data=05%7C01%7Cmarcus%40involution.co.uk%7Cf84f2b64342f444a961a08db1514c843%7Ce51e871a93f74056bbe8ff647931b4fe%7C0%7C0%7C638126951228928626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jHLQrYbkROLFnsPUso353xunQTWpSBu3mHVMHMw9IYo%3D&reserved=0>, or unsubscribe<https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXS4A5IL3JYT4UEHSVGGBXDWYZ2M7ANCNFSM6AAAAAAVC6GUYQ&data=05%7C01%7Cmarcus%40involution.co.uk%7Cf84f2b64342f444a961a08db1514c843%7Ce51e871a93f74056bbe8ff647931b4fe%7C0%7C0%7C638126951228928626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yTUwwKrr2wo5A6XRM6lOyBc2mULi3%2BiFvLC19J23Y%2BQ%3D&reserved=0>. You are receiving this because you were mentioned.Message ID: ***@***.***>

Try to use the newly added .engine infer in yolov8n.

I am getting 120+FPS on my 4090 compare to .pt models which were ~80

**Comment by AyushExel** [comment]
Yes exactly. Its super simple to get higher fps after exporting the model to .engine.

**Comment by AyushExel** [comment]
> It doesn't matter. Everyone has different figures it seems on this thread. PyTorch is just a lot slower than Darknet. Which is disappointing considering that YoloV8 has better accuracy. FPS matters a lot, it's a shame that the FPS differences between PyToch and Darknet is so significant. On 22 Feb 2023 20:38, Ayush Chaurasia ***@***.***> wrote: V4 tiny has 6.06 M params with 21 mAP V8n has 3.2 M params with 37 mAP Where are you getting your numbers from? — Reply to this email directly, view it on GitHub<https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fultralytics%2Fultralytics%2Fissues%2F1081%23issuecomment-1440766120&data=05%7C01%7Cmarcus%40involution.co.uk%7Cf84f2b64342f444a961a08db1514c843%7Ce51e871a93f74056bbe8ff647931b4fe%7C0%7C0%7C638126951228928626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jHLQrYbkROLFnsPUso353xunQTWpSBu3mHVMHMw9IYo%3D&reserved=0>, or unsubscribe<https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXS4A5IL3JYT4UEHSVGGBXDWYZ2M7ANCNFSM6AAAAAAVC6GUYQ&data=05%7C01%7Cmarcus%40involution.co.uk%7Cf84f2b64342f444a961a08db1514c843%7Ce51e871a93f74056bbe8ff647931b4fe%7C0%7C0%7C638126951228928626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yTUwwKrr2wo5A6XRM6lOyBc2mULi3%2BiFvLC19J23Y%2BQ%3D&reserved=0>. You are receiving this because you were mentioned.Message ID: ***@***.***>

It actually matters quite a bit. The AP of v8n is almost double of v4 tiny. And the speed you're getting can be improved by exporting things to engine format. The R&D is done to improve the speed accuracy tradeoff and not one or the other. Try the engine export for speed improvement i as mentioned by @StanleyWQX above. Thanks!

**Comment by anzenchitai** [comment]
@AyushExel Is there an example for .engine files in C++? I spent hours trying to get it to work but I just couldn't get everything to work in the end.

**Comment by AyushExel** [comment]
Trt speeds are there on the readme but we haven't compared it against v4 as it has too low AP to be compared in that chart.

**Comment by invo-mwiseman** [comment]
Params aside, YoloV8 might have less params, but it's still a much slower model run through PyTorch. Commercially, this is non-viable, since Darknet is much quicker option.

I already tried converting to .onnx, this produced errors when loading the model via OpenCV (4.7.0). 
![image](https://user-images.githubusercontent.com/98943093/220867960-7ecf6077-7dff-439e-a72c-e2f5a369eec6.png)

Then I tried converting to .engine and running through TensorRT(8.5.3.1), which still produced errors when loading the model.

So Ultralytics export functionality currently has failed to help on two accounts.

**Comment by invo-mwiseman** [comment]
> > It doesn't matter. Everyone has different figures it seems on this thread. PyTorch is just a lot slower than Darknet. Which is disappointing considering that YoloV8 has better accuracy. FPS matters a lot, it's a shame that the FPS differences between PyToch and Darknet is so significant. On 22 Feb 2023 20:38, Ayush Chaurasia _**@**_._**> wrote: V4 tiny has 6.06 M params with 21 mAP V8n has 3.2 M params with 37 mAP Where are you getting your numbers from? — Reply to this email directly, view it on GitHubhttps://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fultralytics%2Fultralytics%2Fissues%2F1081%23issuecomment-1440766120&data=05%7C01%7Cmarcus%40involution.co.uk%7Cf84f2b64342f444a961a08db1514c843%7Ce51e871a93f74056bbe8ff647931b4fe%7C0%7C0%7C638126951228928626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jHLQrYbkROLFnsPUso353xunQTWpSBu3mHVMHMw9IYo%3D&reserved=0, or unsubscribehttps://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXS4A5IL3JYT4UEHSVGGBXDWYZ2M7ANCNFSM6AAAAAAVC6GUYQ&data=05%7C01%7Cmarcus%40involution.co.uk%7Cf84f2b64342f444a961a08db1514c843%7Ce51e871a93f74056bbe8ff647931b4fe%7C0%7C0%7C638126951228928626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yTUwwKrr2wo5A6XRM6lOyBc2mULi3%2BiFvLC19J23Y%2BQ%3D&reserved=0. You are receiving this because you were mentioned.Message ID: _**@**_.**_>
> 
> Try to use the newly added .engine infer in yolov8n.
> 
> I am getting 120+FPS on my 4090 compare to .pt models which were ~80

What version of TensorRT did you use?

**Comment by AyushExel** [comment]
> Params aside, YoloV8 might have less params, but it's still a much slower model run through PyTorch. Commercially, this is non-viable, since Darknet is much quicker option.
> 
> I already tried converting to .onnx, this produced errors when loading the model via OpenCV (4.7.0). ![image](https://user-images.githubusercontent.com/98943093/220867960-7ecf6077-7dff-439e-a72c-e2f5a369eec6.png)
> 
> Then I tried converting to .engine and running through TensorRT(8.5.3.1), which still produced errors when loading the model.
> 
> So Ultralytics export functionality currently has failed to help on two accounts.

Please see the examples folder. It has tested examples for onnx export, c++, python and c# inference. We've also confirmed trt inference. It could be that you're library versions are not compatible as other users seem to be having no trouble with it
