### ISSUE TITLE
train own custom data for classification

### ISSUE THREAD

**Issue by osamaalschame** [ultralytics/ultralytics#1082]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

how to prepare the data.ymal file for classification.  is it same for object detect data file 

ex:
train: path
val: path

nc: 

names:

**Comment by AyushExel** [comment]
The format is same as the folder structure as a torchvision dataset. Just pass the location of your dataset folder as data=path

**Comment by glenn-jocher** [comment]
@osamaalschame classification is super simple, you just point data= to your classification dataset directory, i.e. try this:

`yolo train model=yolov8n-cls.pt data=imagenet100` to see an auto-downloaded example and then you can point data directly to the imagenet100 directory (or any other custom dataset directory).

**Comment by binn77** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> ### Question
> how to prepare the data.ymal file for classification. is it same for object detect data file
> 
> ex: train: path val: path
> 
> nc:
> 
> names:
> 
> ### Additional
> _No response_

yolo classify train model=yolov8n-cls.pt data=C:/Users/Admin/Desktop/dataset/ epochs=5 batch=128 imgsz=128 workers=8 patience=10 cache=True device=0

<img width="215" alt="Screenshot_1" src="https://user-images.githubusercontent.com/97234755/220440740-14e300b0-ac28-452b-a93d-4e71b40c55ad.png">

**Comment by pderrenger** [comment]
@binn77 for classification using YOLOv8, your `data.yaml` file should specify the paths for both the training and validation datasets, the number of classes (`nc`), and the class names (`names`). Here's a basic example structure for the `data.yaml` file:

```yaml
train: path_to_training_data
val: path_to_validation_data
nc: number_of_classes
names: class_names
```

For your specific command, it seems like you're already using the `data` argument to specify the dataset directory, which is correct. However, make sure that your `data.yaml` file is correctly formatted as described above.

Also, consider verifying that the paths to your training and validation datasets are accurate and that the data.yaml file is placed in the correct directory.

Once your `data.yaml` file is correctly set up, you should be able to proceed with the classification training command.

Best of luck with your classification training using YOLOv8!
