### ISSUE TITLE
chnages in the yolov8.yaml file

### ISSUE THREAD

**Issue by h-rajpoot309** [ultralytics/ultralytics#10837]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello! I am using yolov8 for sign recognition. i want to freeze the last 3 layers and add new layers. can i do this by making changes in the yolov8.yaml file. 

this is the yolov8.yaml file from the official ultralytics github page
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2f, [512]] # 12

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2f, [256]] # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2f, [512]] # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2f, [1024]] # 21 (P5/32-large)

  - [[15, 18, 21], 1, Detect, [nc]]

i want t change or modify the last three layers. Is it possible to do this?

**Comment by glenn-jocher** [comment]
@h-rajpoot309 hello! 😊 It's great to see you diving into customizing YOLOv8 for sign recognition.

Yes, you can modify the YOLOv8 configuration by altering the `yolov8.yaml` file. To freeze the last three layers and add new layers, you'll first need to decide which layers to freeze and the specifics of the new layers you wish to add.

Freezing layers directly in the `.yaml` file isn't straightforward, as this file mainly defines the architecture. Freezing layers typically involves modifying the training code to prevent weight updates to the specified layers during the training process.

However, you can certainly add or modify layers in the `yolov8.yaml` file. For example, if you wish to add new convolutional layers at the end, you might append something like this to the `head` section:

```yaml
  - [-1, 1, Conv, [512, 3, 1]]
  - [-1, 1, Conv, [256, 3, 1]]
  - [-1, 1, Conv, [nc, 1, 1]]
```

📝 **Note:** The parameters in `[nc, 1, 1]` represent the number of output channels (for your classes), kernel size, and stride, respectively.

To freeze layers during training, you'll need to adjust the training script. For example, in PyTorch, you could set `requires_grad` to `False` for the parameters of the layers you want to freeze by accessing them through the model's `state_dict` or another mechanism depending on how your model is structured.

If you're modifying the base YOLOv8 architecture significantly, consider defining a custom model class that loads the pretrained YOLOv8 and appends your modifications. 

Let us know if you need guidance on specific code implementations for freezing layers or further customizing the architecture!

**Comment by jihunddok** [comment]
I tried to change the yolov8-seg.yaml layer structure through the previously defined TransformerBlock, but ran into the following problem.

.yolov8\Lib\site-packages\ultralytics\nn\tasks.py", line 750, in parse_model
    m = getattr(torch.nn, m[3:]) if "nn." in m else globals()[m] # get module
                                                    ~~~~~~~~~^^^
KeyError: 'TransformerBlock'

**Comment by glenn-jocher** [comment]
Hello @jihunddok! 😊

It looks like the `TransformerBlock` isn't recognized in the `globals()` scope. To resolve this, you need to ensure that `TransformerBlock` is properly imported and available in the scope where the model is being parsed.

Here's a quick way to address this:

1. **Import the TransformerBlock**: Ensure that `TransformerBlock` is imported at the beginning of your script or module where the model is being defined.

2. **Add to globals()**: Explicitly add `TransformerBlock` to the `globals()` dictionary.

Here's an example:

```python
from your_module import TransformerBlock  # Adjust the import as necessary

globals()['TransformerBlock'] = TransformerBlock
```

Place this code snippet before the model parsing line in your script. This should make `TransformerBlock` available when the model is being parsed.

Feel free to reach out if you have any more questions or run into further issues. Happy coding! 🚀
