### ISSUE TITLE
Inference time with time.time()

### ISSUE THREAD

**Issue by juanvillacres** [ultralytics/ultralytics#1087]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I detected some objects in one image using:

`a55 = model(camIMG[0])`

The output indicates:

Speed: 1.2ms pre-process, 13.1ms inference, 13.2ms postprocess per image at shape (1, 3, 640, 640)

However, when I timed with the next code:

```
t0 = time.time()
a55 = model(camIMG[0])
t1 = time.time()
print("The time for MODEl is {} ------------------ ".format(t1-t0))
```
The output is (~147 ms):
The time for MODEl is 0.14662861824035645 ------------------ 

Please advise me on the difference between the two times.

**Comment by glenn-jocher** [comment]
@juanvillacres profiling times are based on ops.Profile() instances and applied here in predictor:

https://github.com/ultralytics/ultralytics/blob/fe61018975182f4d7645681b4ecc09266939dbfb/ultralytics/yolo/engine/predictor.py#L164-L177
