### ISSUE TITLE
Unable to Use MPS to Run Pre-trained Object Detection Model on GPU

### ISSUE THREAD

**Issue by Leotrimlota** [ultralytics/ultralytics#1090]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am using MAC and trying to run Ultralytics YOLOv8 pre-trained model to detect objects in my project. However, despite trying to use MPS, I am still seeing the CPU being used in torch even after running the Python code. Specifically, the output I see is: "Ultralytics YOLOv8.0.43 🚀 Python-3.9.16 torch-1.13.1 CPU".
I wanted to know if has support for MPS in YOLOv8, and how can I use it?

**Comment by glenn-jocher** [comment]
@Leotrimlota MPS support is experimental and may not work correctly for many tasks and modes. You specify mps as any other device, i.e.
```
yolo predict device=mps
```

**Comment by jlognn** [comment]
Hi @glenn-jocher - just tried this on M1 Ultra:

`Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead`

I will have a look around and see what I can find

**Comment by jlognn** [comment]
FYI I just tried to train YOLOv8 on custom data

**Comment by glenn-jocher** [comment]
@jlognn as the torch messages say you can use PYTORCH_ENABLE_MPS_FALLBACK=1 to sidestep any ops not supported on MPS, though this returns silent errors in some tasks like detection and segmentation. 

MPS works correctly for classification models, i.e.:
```bash
PYTORCH_ENABLE_MPS_FALLBACK=1 yolo predict model=yolov8n-cls.pt

WARNING ⚠️ 'source' is missing. Using default 'source=/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets'.
Ultralytics YOLOv8.0.45 🚀 Python-3.10.6 torch-1.13.1 CPU
YOLOv8n-cls summary (fused): 73 layers, 2715880 parameters, 0 gradients, 4.3 GFLOPs

image 1/4 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus.jpg: 224x224 minibus 0.51, police_van 0.31, recreational_vehicle 0.03, ambulance 0.02, minivan 0.01, 10.3ms
image 2/4 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus_4ch.png: 224x224 minibus 0.51, police_van 0.31, recreational_vehicle 0.03, ambulance 0.02, minivan 0.01, 9.5ms
image 3/4 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus_greyscale.jpg: 224x224 ambulance 0.16, minibus 0.13, fire_engine 0.12, police_van 0.09, passenger_car 0.04, 8.9ms
image 4/4 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/zidane.jpg: 224x224 rugby_ball 0.11, suit 0.09, stage 0.05, bow_tie 0.05, ping-pong_ball 0.05, 9.0ms
Speed: 0.0ms preprocess, 9.4ms inference, 0.0ms postprocess per image at shape (1, 3, 224, 224)
```

We're happy to accept contributions here for the outstanding MPS issues, so feel free to submit PRs with fixes.

**Comment by jlognn** [comment]
@glenn-jocher yes it appears that there are a number of MPS operations that are unsupported by Torch. There was a link to an open issue with the PyTorch team but I can't find it anymore.  This doesn't seem to be an issue with Ultralytics/YOLO but with PyTorch's MPS support.  From my side I am just going to keep pulling the nightly builds from PyTorch and keeping an eye on the forums.

**Comment by GameTL** [comment]
Please add MPS support to YOLOV8, I use my macbook for coding in general and train the model on Google Colab. I usually run predict on my macbook pro m2 pro with the 19-core gpu and I'm only getting around 2.5fps for YOLOV8n-seg, whereas it's around 30fps on my CUDA PC.

**Comment by glenn-jocher** [comment]
Hello @krishnachowdary96, please note that we provide experimental MPS support in our YOLOv8 implementation. You can enable MPS by simply adding `device=mps` when running the predict function to perform object detection by your model. 

Currently, there are some limitations and some operations may not work correctly for every device and task. There may also be performance drawbacks as MPS is experimental and not optimized for every task. In any case, feel free to try it out and let us know your experience while using it.

**Comment by GameTL** [comment]
Right thank you for the quick response really appreciate the good work you guys are doing. Currently I'm using openCV to load model for prediction, so I will have a look on how to do that. But it's good to know if I see to test run with the terminal device=mps
________________________________

**Comment by 25benjaminli** [comment]
When I write device=mps, it says it is still detecting with CPU. In your example with the classification, it also says `Python-3.10.6 torch-1.13.1 CPU`. Is there a way to determine whether it is actually using MPS?

**Comment by glenn-jocher** [comment]
@25benjaminli hello, you're correct that the MPS (Metal Performance Shaders) are a feature of the GPU on devices that support Metal, like your Mac. However, note that MPS is not a separate device like CPU or GPU. Rather, it is a framework that enables specific GPU operations and it is treated as a CPU device by PyTorch. So when you see `device=mps`, the computation is actually performed on the GPU with MPS, even if it mentions "CPU".

Unfortunately, at the moment there isn't a way to directly confirm through PyTorch that MPS is being used. However, if you're seeing a significant performance increase when using `device=mps` as opposed to not using it, then MPS is likely being utilised.

Remember, MPS support in YOLOv8 is still experimental, and as such, not all operations may be optimised to run faster on MPS, and thus you may not always see improved performance. We appreciate your feedback and patience as we continue to refine support for a wider variety of devices and configurations.

**Comment by quietbamboo** [comment]
Hello, we observed that for the same detection model, and same code, using cpu gives correct results, however, when using mps for detection, the bounding box location is not correct. Any clue on how to fix this bug? Is it because the version of some pip lib I'm using is incompatible?

**Comment by romellfudi** [comment]
Hello @glenn-jocher. In light of your response, could you provide a comprehensive list of features currently supported by MPS in ultralytics?

**Comment by glenn-jocher** [comment]
@romellfudi hello! Thanks for reaching out. 😊 Currently, MPS support in Ultralytics YOLOv8 is experimental and primarily aimed at enabling GPU acceleration on macOS devices. Key features like object detection, segmentation, and classification can leverage MPS for improved performance on compatible Mac devices. However, detailed specifics on operations and layers supported by MPS are evolving as we continue to test and optimize.

For running a model with MPS, you can simply specify the device as 'mps' in your code like so:

```python
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt', device='mps')  # Use MPS

# Run inference
results = model.predict('path/to/image.jpg')
```

Keep in mind, since MPS support is still under development, results and performance may vary. We're actively working on expanding and refining MPS capabilities, so stay tuned for updates!

**Comment by romellfudi** [comment]
Thanks again for your help.

**Comment by glenn-jocher** [comment]
@romellfudi hi there! Thanks for reaching out 😊. If you're running into issues with bounding box locations during MPS-based detections, ensure your Ultralytics and PyTorch libraries are updated. MPS support is indeed experimental, and we're constantly improving it. For now, you can try specifying MPS with:

```python
from ultralytics import YOLO

model = YOLO('yolov8n.pt', device='mps')  # Using MPS
```

And remember, we're here to help as you explore MPS capabilities with YOLOv8. Stay tuned for more updates!

**Comment by openminded-oscar** [comment]
First of all I want to thank this repo contributors for their great work!
And one more vote to improve support on mps!
