### ISSUE TITLE
AttributeError: 'YOLO' object has no attribute 'track'

### ISSUE THREAD

**Issue by littlebig-balala** [ultralytics/ultralytics#1092]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

"I downloaded Ultralytics using pip, and both Detection and Segmentation tasks can be run successfully. However, when I followed the Multi-Object Tracking guide in the YOLOv8 official manual, the program reported an error 'AttributeError: 'YOLO' object has no attribute 'track''. Can you please tell me how to implement the target tracking function in YOLOv8?"
![image](https://user-images.githubusercontent.com/53027914/220541121-9ba7bf2c-6d9f-47b7-9ffd-0850be5be860.png)

**Comment by Laughing-q** [comment]
@littlebig-balala hi I think the package version you installed is outdated which does not include the track part, please upgrade the package and try again.

**Comment by littlebig-balala** [comment]
Thank you for your reply and suggestions, and I also appreciate the projects you have contributed, which have been very helpful to us.
&nbsp;


夏已苍凉、
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月22日(星期三) 下午3:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ultralytics/ultralytics] AttributeError: &#39;YOLO&#39; object has no attribute &#39;track&#39; (Issue #1092)





 
@littlebig-balala hi I think the package version you installed is outdated which does not include the track part, please upgrade the package and try again.

**Comment by Kutayykilic** [comment]
For people who have encountered this issue, check your pip version if it's not the updated version. Make sure you have updated it.
`python -m pip install --upgrade pip`

**Comment by glenn-jocher** [comment]
@Kutayykilic thank you for sharing your experience with updating pip to resolve the issue. It is always important to keep our software packages up to date to avoid these types of errors. Additionally, it is recommended to refer to the official documentation for any further troubleshooting steps or for additional information regarding the usage of Ultralytics YOLOv8.
