### ISSUE TITLE
Incorrect number of classes with multi-gpu training in classifier

### ISSUE THREAD

**Issue by zldrobit** [ultralytics/ultralytics#1094]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Multi-GPU

### Bug

When training yolov8 classifers with 
```
yolo classify train data=mnist160 model=yolov8n-cls.pt epochs=3 imgsz=64
```
, I could get a model with 10 classes. While training with multiple gpus as
```
yolo classify train data=mnist160 model=yolov8n-cls.pt epochs=3 imgsz=64 device=0,1
```
, the output shape of `best.pt` is 1000 (`out_features`) as the following image.

![image](https://user-images.githubusercontent.com/3896992/220549697-8e365064-b3b3-4d40-90b7-12dc0fd8d6f0.png)

### Environment

- YOLOv8: Ultralytics YOLOv8.0.43 🚀 Python-3.10.8 torch-1.13.1 CUDA:0 (NVIDIA A100 80GB PCIe, 81085MiB)        
                                                      CUDA:1 (NVIDIA A100 80GB PCIe, 81085MiB)
- Python: 3.10.8
- OS: Ubuntu 18.04.6 LTS

### Minimal Reproducible Example

```
yolo classify train data=mnist160 model=yolov8n-cls.pt epochs=3 imgsz=64 device=0,1
```

### Additional

It is frustrating that even the output number of classes is 1000, the output log still contains 
```
Overriding model.yaml nc=1000 with nc=10
```

![image](https://user-images.githubusercontent.com/3896992/220550605-389aaad4-bdcd-4662-8a6c-39c3ea58c350.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@zldrobit fix should be merged to main in #1088 and new 8.0.44 release later today. Please let us know if this resolves your issue, thank you!
