### ISSUE TITLE
yolov8 export as onnx issue (8.0.43)

### ISSUE THREAD

**Issue by JustasBart** [ultralytics/ultralytics#1097]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

It appears that something might've changed with the latest yolov8.0.43 as by running the script:
```
yolo export \
model=yolov8m.pt \
imgsz=640 \
format=onnx
```
Which I've done basically a million times by now is now giving me the following warnings:

![image](https://user-images.githubusercontent.com/40023722/220562824-81a4d1ec-19d1-4850-a93d-e20143a2a8b3.png)

And I'm unable to run inference on these models anymore:

![image](https://user-images.githubusercontent.com/40023722/220563230-38e5bfa8-057e-493f-ac32-80661b62a89a.png)

Whereas switching to the ones prior to the update and prior to the warnings seems to work just fine:

![image](https://user-images.githubusercontent.com/40023722/220563513-a5dbe71a-45dc-4201-bcd7-341c22656107.png)

### Environment

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

OpenCV
Version control:               4.7.0
Version control (extra):       4.7.0

CMake:                         3.16.3

NVIDIA CUDA:                   YES (ver 11.2, CUFFT CUBLAS FAST_MATH)
NVIDIA GPU arch:               35 37 50 52 60 61 70 75 80 86
cuDNN:                         YES (ver 8.7.0)
```

### Minimal Reproducible Example

Export any model as .onnx, run the CPP example (Assuming your setup is working in the first place).

### Additional

I can confirm that my setup did not change since the last few days and also any previous prior examples are working fine :rocket: 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@JustasBart can you tell me which version works correctly to you?

**Comment by JustasBart** [comment]
Hi @Laughing-q how would I roll-back? Is it to clone, checkout, and install?

**Comment by JustasBart** [comment]
@Laughing-q Never mind I was able to play around with pip install on different packages and was able to resolve this, so perhaps it wasn't a bug after all and or one of the packages is the wrong version? The last thing I ran was 'pip install protobuf==3.20.*' but it seems to be resolved on my system now so I can't really tell what changed...

**Comment by Laughing-q** [comment]
@JustasBart ok got it! But actually I encountered the same issue here😂. Using the onnx model exported by latest version(with the warning message) to export another format is not successful to me, but using the onnx exported by the version without the warning message works correctly to me...

**Comment by JustasBart** [comment]
@Laughing-q Yeah, that's what I've observed as well, I've closed the issue for now as it doesn't seem to be too major, but perhaps be aware of this @glenn-jocher in case more people start seeing this...

**Comment by Laughing-q** [comment]
@JustasBart oh I see that's because it's using the latest opset by default when exporting onnx, just point a lower version opset would solve this issue.

**Comment by JustasBart** [comment]
@Laughing-q Oh! I had forgotten about that altogether!

**Comment by glenn-jocher** [comment]
@JustasBart @Laughing-q hi guys. Yes exports in general have undergone rapid changes in the last few versions. ONNX will use the latest version available, i.e. opset=17 if opset is not defined on L313:
https://github.com/ultralytics/ultralytics/blob/fe61018975182f4d7645681b4ecc09266939dbfb/ultralytics/yolo/engine/exporter.py#L308-L318

We now also have export benchmarks that run on all CI, and ONNX results seem good:
https://github.com/ultralytics/ultralytics/actions/runs/4248488350/jobs/7387714086
<img width="1363" alt="Screenshot 2023-02-23 at 05 53 35" src="https://user-images.githubusercontent.com/26833433/220927316-6c8e8c4c-8d95-410c-b77e-226110299968.png">

**Comment by JustasBart** [comment]
@glenn-jocher Thanks a mil for your input! I just forgot to use the **opset=12** altogether and got a good bit confused so figured I'd put it up as a potential issue but no it was just on my end (Which is good in a way) but yeah it's all working!

Cheers :rocket:
