### ISSUE TITLE
I need to modify the algorithm code to convert the detection frame of the prediction code into a point

### ISSUE THREAD

**Issue by nmanhong** [ultralytics/ultralytics#1098]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Here is my code
“from ultralytics import YOLO
model = YOLO("best.pt")  # load a custom model

results = model("20201229095228783_202012174A24A04612_6.tif", save=True, device=cpu)  # predict on an image
########### results = results.cpu()”

This is my error, I don't know how to use this method in cpu reasoning
“Traceback (most recent call last):
  File "pre.py", line 8, in <module>
    results = model("20201229095228783_202012174A24A04612_6.tif", save=True, device=cpu)  # predict on an image
NameError: name 'cpu' is not defined”

### Additional

Here is my code
“from ultralytics import YOLO
model = YOLO("best.pt")  # load a custom model
results = model("20201229095228783_202012174A24A04612_6.tif", save=True, device=cpu)  # predict on an image
This is my error, I don't know how to use this method in cpu reasoning
“Traceback (most recent call last):
  File "pre.py", line 8, in <module>
    results = model("20201229095228783_202012174A24A04612_6.tif", save=True, device=cpu)  # predict on an image
NameError: name 'cpu' is not defined”

**Comment by Laughing-q** [comment]
@nmanhong just add quotation mark should work to you.
```python
results = model("20201229095228783_202012174A24A04612_6.tif", save=True, device="cpu")
```

**Comment by nmanhong** [comment]
Thank you so much

**Comment by pderrenger** [comment]
@nmanhong you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with your project! 😊

**Comment by 1Yleng** [comment]
![~(INOO~20`C2$(}M}Q1~K{Q](https://github.com/ultralytics/ultralytics/assets/99109288/ab5ea277-b668-45d6-a8df-f55202e0597d)
![MCF5 Y_QY5LB3G3JPZ5N99A](https://github.com/ultralytics/ultralytics/assets/99109288/f9d251a8-bf28-4718-8e1d-712641bfc6e8)
@Laughing-q Why is this error still happening？
