### ISSUE TITLE
[Yolov8x-worldv2] How am I able to extract bounding box from the results?

### ISSUE THREAD

**Issue by Yhu98** [ultralytics/ultralytics#10988]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I've been trying to acquire the bounding boxes generated using Yolov8x-worldv2. The result was pretty good, but I did not know how to extract the bounding box coordinates. I've searched some issues and tried one of the solutions but it did not work. An AttributeError was returned saying that "'list' object has no attribute 'detections'". 
```python
from ultralytics import YOLO
model = YOLO('./weights/yolov8x-worldv2.pt')
model.set_classes(["traffic cone"])
results = model.predict(f'{output_path}no5_{file_name}.jpg')

for det in results.detections:
    x1, y1, x2, y2 = det.box.xyxy  # Bounding box coordinates
    conf = det.conf  # Confidence
    cls = det.cls  # Detected class ID
    print(f"Coordinates: {x1}, {y1}, {x2}, {y2}, Conf: {conf}, Class: {cls}")
```
Could you help me get bounding boxes for object detection, at least in YOLO format like this:

> cls x_center y_center width height

**Comment by glenn-jocher** [comment]
Hello there! 😊 It looks like there's a small issue in how you're accessing the results. When using `model.predict()`, the results are actually a list of `Results` objects, one for each image predicted. To extract bounding boxes from these results, you should iterate over this list first. Here's a quick fix to your code that should work:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('./weights/yolov8x-worldv2.pt')
results = model.predict('path/to/your/image.jpg')

# Since predict() returns a list of Results objects, we need to iterate through it
for result in results:
    # Now we can iterate through detections in each result
    for det in result.boxes:
        # Get normalized xywh (YOLO format) and class confidence
        x_center, y_center, width, height = det.xywhn
        conf = det.conf
        cls = det.cls
        # Print in the desired format
        print(f"cls: {cls}, x_center: {x_center}, y_center: {y_center}, width: {width}, height: {height}, conf: {conf}")
```

This code iterates through the list of `Results` objects returned by the `model.predict()` method, then for each image, it iterates through the `boxes` attribute to access each detection. You were on the right track; just needed to adjust how to access those detections! Let me know if you need further assistance. Happy detecting! 🚀

**Comment by glenn-jocher** [comment]
@Yhu98 you're welcome! I'm glad to hear that you found the information helpful. If you have any more questions or run into issues down the line, feel free to ask. Happy coding! 😊🚀
