### ISSUE TITLE
Plot boxes

### ISSUE THREAD

**Issue by christian-hiebl** [ultralytics/ultralytics#1099]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

As outlined [here](https://github.com/ultralytics/ultralytics/blob/main/docs/predict.md), plotting should be implemented.

```
res_plotted = results[0].plot()
cv2.imshow("result", res_plotted)
```
but the error I get is:

```
'Results' object has no attribute 'plot'. Valid 'Results' object attributes and properties are:

            Attributes:
                boxes (Boxes, optional): A Boxes object containing the detection bounding boxes.
                masks (Masks, optional): A Masks object containing the detection masks.
                probs (torch.Tensor, optional): A tensor containing the detection class probabilities.
                orig_shape (tuple, optional): Original image size.
```

### Environment

- YOLO: YOLOv8.0.25
- OS: Ubuntu 20.04
- Python 3.9

### Minimal Reproducible Example

```
img_pth = "path/to/img"
model = YOLO("yolov8x.yaml")  # build a new model from scratch
model = YOLO("yolov8x.pt") 
results = model(img_pth)
res_plotted = results[0].plot()
cv2.imshow("result", res_plotted)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@christian-hiebl this feature was introduced recently. Please update your package and everything should work correctly.

**Comment by christian-hiebl** [comment]
Thank you very much! I will update the Ultralytics package then.

**Comment by F0l1k** [comment]
The problem is still relevant, are there any solutions?
ultralytics updated, but still the same

Python 3.10

**Comment by Laughing-q** [comment]
@F0l1k it works correctly to me.
```python
import cv2
from ultralytics import YOLO
img_pth = "ultralytics/assets/bus.jpg"
model = YOLO("yolov8x.pt") 
results = model(source=img_pth)
res_plotted = results[0].plot()
cv2.imshow("result", res_plotted)
cv2.waitKey(0)
```
![pic-full-230223-1834-43](https://user-images.githubusercontent.com/61612323/220882989-2f38ad7e-df2f-4099-a787-40e417538b1f.png)

**Comment by F0l1k** [comment]
I literally copied the code (replacing the image), but this error still occurs, what could be the problem?
The image is working, yolo even outputs the result of processing, but there is no .plot attribute in the List

VS Studio, Windows 10
![image](https://user-images.githubusercontent.com/79876780/220888785-040a00a7-2bd9-44d8-afe3-8008dbf387b5.png)

**Comment by Laughing-q** [comment]
@F0l1k ah please upgrade your package.
```bash
pip install --upgrade ultralytics
```

**Comment by F0l1k** [comment]
Ah, that's how it works...
thank you very much ;3

**Comment by pderrenger** [comment]
@01bui to plot both predicted and ground truth bounding boxes, you can use ultralytics' YOLOv8 `Val` mode. This mode will automatically plot the ground truth bounding boxes as well as the predicted bounding boxes on top of the input image. You can use the `with_labels` argument set to `True` to display the class labels along with the bounding boxes. More detailed usage and options are available in the [YOLOv8 documentation for Val mode](https://docs.ultralytics.com/modes/val).

**Comment by glenn-jocher** [comment]
@pderrenger, to visualize both predicted and ground truth bounding boxes, you can run your model in `Val` mode with the `--plot` flag. This will overlay both the predictions and ground truths on your validation dataset images. For class labels, ensure `--with_labels` is set to `True`. Check out the Val mode section in our documentation for more details. 📊🔍

**Comment by VelDia** [comment]
> How do you plot both predicted and ground truth bounding boxes?

Hey, @01bui have you found a way to do this? Can you give any directions?

**Comment by glenn-jocher** [comment]
To plot both predicted and ground truth bounding boxes, you can overlay them on the image using different colors for distinction. Use the `plot()` method for predictions and a library like OpenCV to draw the ground truth boxes. If you need further assistance, let me know!
