### ISSUE TITLE
How must a dataset.yaml external for classification

### ISSUE THREAD

**Issue by Petopp** [ultralytics/ultralytics#1101]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,
I am trying to run a classification with Yolov8. But I don't understand how the dataset file has to be structured. Does anyone have an example?

Currently mine looks like this:
```
train: C:/Users/xx/Downloads/Bananatrain
val: C:/Users/xx/Downloads/Bananavalid
test: C:/Users/xx/Downloads/Bananatest
nc: 4
names:
  0: overripe
  1: ripe
  2: rotten
  3: unripe
```

However, this is not recognised for tranieren, it always comes the message that this is not available.

Thanks a lot

Peter

**Comment by Petopp** [comment]
Okay, you only have to specify the path to the files. So you don't need the dataset file. Problem solved

**Comment by pderrenger** [comment]
@Petopp glad to hear you resolved the issue! Just to clarify, for running a classification task with YOLOv8, the dataset file is not necessary. Simply specifying the paths to the train, val, and test image directories along with the number of classes and class names should be sufficient. If you have any other questions, feel free to ask!

**Comment by haimat** [comment]
> @Petopp glad to hear you resolved the issue! Just to clarify, for running a classification task with YOLOv8, the dataset file is not necessary. Simply specifying the paths to the train, val, and test image directories along with the number of classes and class names should be sufficient. If you have any other questions, feel free to ask!

If one does not need the dataset file for a classification task, how to speficy number of classes and their names then?
