### ISSUE TITLE
How can I apply websocket communication to YOLO?

### ISSUE THREAD

**Issue by alstn2196** [ultralytics/ultralytics#1102]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to stream multiple webcams to the web using the websockets module.
The basic code is below.
I want to know how to apply this code to YOLO.

I tried modifying the code myself, but I got an error due to synchronization issues.

### Additional

import sys
import asyncio
import websockets
import cv2

async def stream_camera(websocket, camera_num):
    vid = cv2.VideoCapture(camera_num, cv2.CAP_DSHOW)
    if not vid.isOpened():
        print(f"Failed to open camera {camera_num}")
        return

    try:
        while vid.isOpened():
            ret, frame = vid.read()
            if not ret:
                print(f"Failed to read frame from camera {camera_num}")
                break

            frame = cv2.resize(frame, (640, 640))
            encode_param = [int(cv2.IMWRITE_JPEG_QUALITY), 65]
            _, img = cv2.imencode('.jpg', frame, encode_param)
            await websocket.send(img.tobytes())

    except Exception as e:
        print(f"Exception while streaming camera {camera_num}: {e}")
        pass

async def serve_camera(websocket, path):
    camera_num = int(path.strip('/'))
    await stream_camera(websocket, camera_num)

port = int(sys.argv[1]) if len(sys.argv) > 1 else 8000

start_server = websockets.serve(serve_camera, "127.0.0.1", port)

#start_server = websockets.serve(serve_camera, "192.168.0.10", port)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()

**Comment by glenn-jocher** [comment]
@alstn2196 To apply YOLO to the stream of webcams, you can modify the code by adding YOLO detection inside the stream_camera function. You can load the YOLO model inside the stream_camera function, then for each frame read from the camera, you can run the detection on the frame and send the detection results to the client over the websocket connection. Here's an example modification to the stream_camera function:

```python
async def stream_camera(websocket, camera_num):
    # Load YOLO model
    model = YOLOv5(weights='yolov5s.pt')
    vid = cv2.VideoCapture(camera_num, cv2.CAP_DSHOW)
    if not vid.isOpened():
        print(f"Failed to open camera {camera_num}")
        return

    try:
        while vid.isOpened():
            ret, frame = vid.read()
            if not ret:
                print(f"Failed to read frame from camera {camera_num}")
                break

            # Run YOLO detection on the frame
            results = model(frame)

            # Send the detection results to the client over the websocket connection
            await websocket.send(results)

    except Exception as e:
        print(f"Exception while streaming camera {camera_num}: {e}")
        pass
```
