### ISSUE TITLE
are these images good for object detetction ?

### ISSUE THREAD

**Issue by totoadel** [ultralytics/ultralytics#1108]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i will do object detection on cats and dogs , i found a dataset for that, but as you see in images the cat or the dog are taking  90% of the image  .i will work on live camera and object will be far from camera
so can i use them in object detection or they are for classification ? 
![c](https://user-images.githubusercontent.com/23275255/220785159-24f399fb-7dee-4156-9301-b05256483298.jpg)

**Comment by Laughing-q** [comment]
@totoadel hi, in your case I think it won't work well if you're going to use these images for object detection. These images are better for classification.

**Comment by totoadel** [comment]
@Laughing-q so i have to change my strategy , i work on 8 classes and cat and dogs are making problem because they are detected as one of my 8 objects with high accuracy , what if i add them as background while training , is this will good to my network

**Comment by totoadel** [comment]
i use it as background

**Comment by pderrenger** [comment]
@VYRION-Ai adding cats and dogs as background classes during training could indeed help improve the performance of your network, as it may reduce the likelihood of cats and dogs being detected as your other 8 classes. This approach may help the network focus on detecting the other classes more accurately.
