### ISSUE TITLE
Is there any way to get accuracy of model based on bbox size?

### ISSUE THREAD

**Issue by majnas** [ultralytics/ultralytics#1110]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

It would be great if we have report regarding who model perform in detecting small / mideum / large bboxes :confused:
```
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/50      40.3G      1.626      1.565      1.552         29       1280: 100%|██████████| 3306/3306 [1:16:03<00:00
                 Class             Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 25/25 [00:17<
                   all             640       1127      0.449      0.342      0.324      0.145
                   all (small)     640       1127      0.449      0.342      0.324      0.145
                   all (mid)       640       1127      0.449      0.342      0.324      0.145
                   all (large)     640       1127      0.449      0.342      0.324      0.145
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@majnas thanks for the feedback! This is not possible now but we are working on better validation introspection tools in the future.

**Comment by glenn-jocher** [comment]
@AyushExel this is another area we need to improve, viewing validation results better, i.e. smartchecks or lakera.ai
