### ISSUE TITLE
Any plans to add 'rknn' to export.py?

### ISSUE THREAD

**Issue by June1124** [ultralytics/ultralytics#1111]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

An example is the NPU deployed in the RK3588.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@June1124 I don't have experience with this myself but if you submit a PR we can evaluate it. Thank you!
