### ISSUE TITLE
Quantization-Aware Training for YOLOv8

### ISSUE THREAD

**Issue by hamedgorji** [ultralytics/ultralytics#11130]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi YOLOv8 Team,

I'm a user of YOLOv8 and have been impressed with its capabilities. However, I noticed that YOLOv8 does not currently support quantization-aware training, a feature that could significantly enhance model performance, especially in deployment scenarios where hardware constraints are a factor.
Could you please consider adding quantization-aware training to the future roadmap of YOLOv8? I believe many users would benefit from this enhancement.
Thanks

### Use case

Quantization-aware training in YOLOv8 would optimize model deployment on edge devices by minimizing size and computational load while preserving accuracy

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@hamedgorji hi there! 👋

Thanks so much for reaching out and for your kind words about YOLOv8. We truly appreciate your suggestion regarding quantization-aware training. It’s feedback like yours that helps us push the boundaries of what YOLOv8 can achieve, especially for edge deployment scenarios where model size and computational efficiency are crucial.

We'll definitely consider adding quantization-aware training to our roadmap. Enhancements that facilitate efficient deployment without sacrificing accuracy are always on our radar. 🚀

While we don't have quantization-aware training at this moment, we are open to community contributions and ideas. Although you've indicated you might not be able to submit a PR, if you or anyone in the community wish to discuss this further or explore potential implementations, we'd love to see those discussions in our issues or discussions section.

Stay tuned for updates, and thanks again for your support!

**Comment by GISScience** [comment]
> @hamedgorji hi there! 👋
> 
> Thanks so much for reaching out and for your kind words about YOLOv8. We truly appreciate your suggestion regarding quantization-aware training. It’s feedback like yours that helps us push the boundaries of what YOLOv8 can achieve, especially for edge deployment scenarios where model size and computational efficiency are crucial.
> 
> We'll definitely consider adding quantization-aware training to our roadmap. Enhancements that facilitate efficient deployment without sacrificing accuracy are always on our radar. 🚀
> 
> While we don't have quantization-aware training at this moment, we are open to community contributions and ideas. Although you've indicated you might not be able to submit a PR, if you or anyone in the community wish to discuss this further or explore potential implementations, we'd love to see those discussions in our issues or discussions section.
> 
> Stay tuned for updates, and thanks again for your support!

_ I want to work on PR for QAT , BUT I NEED HELP . ATLEAST YOU TELL WHERE TO START ? WHICH FILES AND LINE OF CODE TO START. with some basic help , development is really difficulty.  _

**Comment by GISScience** [comment]
QAT  is really important if ultralytics want to penitrate the EDGE computing market. I really need this functionality and want to help in PR feature enhancement.
