### ISSUE TITLE
Cropped Image size mismatches the bounding box Width and Height in the text file

### ISSUE THREAD

**Issue by hareem-nisar** [ultralytics/ultralytics#11140]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I am having issues stitching the final segmentation mask (obtained from DL on cropped images) to the original image shape (256x256)

For example:

Original image with full body or x-ray of size = 256  x  256
YOLOv8 detects lung saves a cropped image of size = 161 x   148

YOLOv8 also saves a bounding box information which I use to restructure the mask e.g. 

x_center = 0.444064 
y_center = 0.55608 
width       = 0.577013     
height      = 0.525868

These values are normalized by the original image size according to Ultralytics docs (https://docs.ultralytics.com/modes/predict/)

I multiply with 256 to get the original values in pixels
x_center = 113.67
y_center = 142.68  
width       = 147.71
height      = 134.6

Here is the descrepency:

Image saved directly by the YOLO was            161 x  148
Image dimensions according to YOLO txt file is    147 x 134

Similarly, caluculating the top-left and bottom-right edges of the cropped image wrt original is slightly different.,

calculated from YOLO coordinates:
left, top, right, bottom
39, 75, 187, 209

Manually, coordinates should be:
left, top
34, 68, 194, 215

Here is what this slight shift looks like.

![image](https://github.com/ultralytics/ultralytics/assets/35270988/6d1ce595-a11b-435d-9b70-767e987a22f0)

**Comment by hareem-nisar** [comment]
I am sure that the segmentation is correct because I verified that earlier on the cropped lung image separately.

**Comment by glenn-jocher** [comment]
@hareem-nisar thank you for bringing this to our attention! 🙏 It seems like the discrepancy between the dimensions of the cropped image saved by YOLOv8 and the bounding box dimensions calculated from the text file might stem from the manner in which the bounding box coordinates are interpreted and the image cropping process.

One potential source of discrepancy is that the box dimensions in the text file represent the center coordinates and the width/height as a fraction of the image dimensions. When converting these back to pixel dimensions for cropping or masking, rounding errors can occur, especially if not consistently applied.

To ensure consistency between your calculated bounding box sizes and the actual cropped images, please consider using the exact same method for cropping as YOLOv8 does internally. Here's a Python example using the bounding box values from YOLO's output:

```python
import cv2

# Original image dimensions
orig_width, orig_height = 256, 256

# Bounding box coordinates (normalized)
x_center, y_center, width, height = 0.444064, 0.55608, 0.577013, 0.525868

# Convert normalized coordinates to pixels
x_center, y_center, width, height = [x_center * orig_width, y_center * orig_height, width * orig_width, height * orig_height]

# Calculate top left and bottom right coordinates
left = int(x_center - (width / 2))
top = int(y_center - (height / 2))
right = int(x_center + (width / 2))
bottom = int(y_center + (height / 2))

# Load original image
img = cv2.imread('path/to/original/image.jpg')

# Crop image
crop_img = img[top:bottom, left:right]

# Verify cropped image size
print(crop_img.shape)
```

Also, ensure that when you're applying this for generating segmentation masks, use identical dimensions to avoid any mismatch. Consistency in rounding and applying transformations is key to aligning outputs perfectly. Let us know how it goes or if there's anything else we can assist you with!

**Comment by hareem-nisar** [comment]
@glenn-jocher 
I don't think precision and rounding off is the issue here. 
I have checked the bounding box parameters generated by yolo functions and they give the same answers. 

Example output from result.boxes is:
```

cls: tensor([0.])
conf: tensor([0.8436])
data: tensor([[ 39.8228,  75.0454, 187.5381, 209.6675,   0.8436,   0.0000]])
id: None
is_track: False
orig_shape: (256, 256)
shape: torch.Size([1, 6])
xywh: tensor([[113.6805, 142.3564, 147.7153, 134.6221]])
xywhn: tensor([[0.4441, 0.5561, 0.5770, 0.5259]])
xyxy: tensor([[ 39.8228,  75.0454, 187.5381, 209.6675]])
xyxyn: tensor([[0.1556, 0.2931, 0.7326, 0.8190]])
```

size of the save cropped image was:  161, 148
size calculated according to text file as well as given by the boxes function: 147.7153, 134.6221

**Comment by glenn-jocher** [comment]
Hi @hareem-nisar,

Thanks for sharing the detailed output! It looks like the discrepancy might be related to how the bounding box coordinates are being converted and used for cropping. The `xyxy` tensor shows pixel coordinates that should ideally match the cropped image dimensions, but there's a slight variation possibly due to how pixels are counted during the cropping process (inclusive vs exclusive pixel indexing).

To ensure the cropping matches the bounding box exactly as intended, you might want to adjust the cropping logic to explicitly match the bounding box coordinates. Here’s a quick example of how you might adjust the cropping:

```python
import cv2
import numpy as np

# Assuming 'img' is your loaded image
x1, y1, x2, y2 = map(int, [39.8228, 75.0454, 187.5381, 209.6675])
cropped_img = img[y1:y2+1, x1:x2+1]  # Adjusting to include the endpoint

print(f'Cropped image size: {cropped_img.shape[:2]}')  # Should now match the expected size
```

This adjustment ensures that the endpoint is included in the crop, which might resolve the size mismatch issue. Let me know if this helps or if there's anything else you'd like to explore! 😊
