### ISSUE TITLE
Can't Load yoloV5 model in yoloV8  prediction

### ISSUE THREAD

**Issue by cr-velox-git** [ultralytics/ultralytics#1114]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

YoloV8 is unable to load yolov5 model for detection given error 
I'm using colab

Error ----->

`
requirements: YOLOv8 requirement "models" not found, attempting AutoUpdate...
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
requirements: ❌ Command 'pip install "models"  ' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/tasks.py", line 332, in torch_safe_load
    return torch.load(file, map_location='cpu')  # load
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/cfg/__init__.py", line 230, in entrypoint
    model = YOLO(model)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/model.py", line 60, in __init__
    {'.pt': self._load, '.yaml': self._new}[suffix](model)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/model.py", line 90, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/tasks.py", line 384, in attempt_load_one_weight
    ckpt = torch_safe_load(weight)  # load ckpt
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/tasks.py", line 340, in torch_safe_load
    return torch.load(file, map_location='cpu')  # load
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models'
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
`

### Minimal Reproducible Example

import os
HOME = os.getcwd()
print(HOME)

!pip install ultralytics==8.0.20

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import yolo

from IPython.display import display, Image

%cd {HOME}
!yolo task=detect mode=predict model=/content/hyp.pt conf=0.25 source=tttt.jpg save=True

#hyp.pt was created using yoloV5

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by JustasBart** [comment]
Hi @cr-velox-git I might be completely wrong here, but I believe that you're supposed to use these models for what you're describing:

![image](https://user-images.githubusercontent.com/40023722/220854685-772c02c0-f2f6-4dbc-a3e5-5275e0a8d183.png)

These are basically yolov5 models but wrapped in the yolov8 architecture.

Could that explain the issue that you're exeriencing?

Good luck! :rocket:

**Comment by cr-velox-git** [comment]
> Hi @cr-velox-git I might be completely wrong here, but I believe that you're supposed to use these models for what you're describing:
> 
> ![image](https://user-images.githubusercontent.com/40023722/220854685-772c02c0-f2f6-4dbc-a3e5-5275e0a8d183.png)
> 
> These are basically yolov5 models but wrapped in the yolov8 architecture.
> 
> Could that explain the issue that you're exeriencing?
> 
> Good luck! 🚀

Sir, I have created a custom model for object detection based on yolov5x.pt nd also added some hyper parameters, and I'm trying to use that model in yolov8.

**Comment by JustasBart** [comment]
Hi @cr-velox-git as already mentioned you cannot directly use yolov5 models within yolov8. Either run your **yolov5x.pt** model with yolov5 or you will have to re-train a **yolov5xu.pt** model in order to be used with yolov8.

Good luck! :rocket:

**Comment by PerveevEvgen** [comment]
I found that [HUB](https://ultralytics.com/hub) v5 (without '6" suffix) derived models also incompatible with the same error.
I already invest into google-collab training and ... I cannot use the result.

**Comment by cr-velox-git** [comment]
> Hi @cr-velox-git as already mentioned you cannot directly use yolov5 models within yolov8. Either run your **yolov5x.pt** model with yolov5 or you will have to re-train a **yolov5xu.pt** model in order to be used with yolov8.
> 
> Good luck! 🚀

Thank You @JustasBart and @glenn-jocher for explaining and guiding me through
