### ISSUE TITLE
Visualize in predict.py code. (visualization quality bad)

### ISSUE THREAD

**Issue by yellowjs0304** [ultralytics/ultralytics#1116]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I wondered why the output visualization image's quality is poor in "segment/predict.py"
![image](https://user-images.githubusercontent.com/30281608/220863204-1682cd97-d5b3-4592-bc01-4b66d1d6b8d4.png)

the original image's quality is not that bad, but the output made from `ultralytics/yolo/utils/plotting.py` is really bad.
(It looks like related with  box_label function in Annotator class..)
I also checked the output image size(w,h pixels), but it is same with original image ;(

Do you know any tips about this issue?

**Comment by glenn-jocher** [comment]
@yellowjs0304 if you're asking about predict for detection models, this is annotated at original image size. For segment predict the masks are plotted at a downsample ratio of 4, sot he masks may be of lower quality. You can improve the quality of masks with `segment predict retina_masks=True` to plot at inference resolution at the expense of mask plotting speed.
```
yolo predict model=yolov8n-seg.pt retina_masks save
```
![zidane](https://user-images.githubusercontent.com/26833433/221231482-f21a9b8a-974a-4c40-b5d4-c633cb13f1d9.jpg)

**Comment by yellowjs0304** [comment]
Thank you for fast reply! :)

**Comment by pderrenger** [comment]
@yellowjs0304 you're welcome! If you have any more questions or need further assistance, feel free to ask. Have a great day! 😊
