### ISSUE TITLE
Model type mismatch after export

### ISSUE THREAD

**Issue by Wenlong0913** [ultralytics/ultralytics#1117]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

After exporting a custom trained model to onnx format, it reports that the `model.type` is mismatch.
Please see the following attached image. We have trained a custom classify model and exported it to onnx.

<img width="1647" alt="image" src="https://user-images.githubusercontent.com/17941167/220883870-b4856848-9db8-4c1b-a68e-4f6d81c1eb45.png">

### Environment

- YOLO ultralytics  8.0.43
- OS Ubuntu 22.04
- Python 3.10.6

### Minimal Reproducible Example

yolo classify train data=airport  model=yolov8m-cls.pt epochs=100 workers=0 imgsz=400,125 batch=64
yolo export model=runs/classify/train/weights/best.pt format=onnx
yolo predict task=classify model=runs/classify/train/weights/best.onnx imgsz=416 source=./test.jpg

### Additional

The pt model works as expected.
<img width="1660" alt="image" src="https://user-images.githubusercontent.com/17941167/220885627-c1b58a37-e58c-4049-8b2e-914eb0fa496a.png">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@Wenlong0913 Thanks for the reporting! We'll fix it soon. :)

**Comment by glenn-jocher** [comment]
@Wenlong0913 got it, thanks for the bug report! I'll work on a fix for this. In the meantime @Laughing-q solution will also work.

**Comment by glenn-jocher** [comment]
@Laughing-q @AyushExel this specific issue will now be fixed in #1088 as I've added slightly more robust guessing from path, so now if 'classify' is in model path's parts it will be guessed correctly, but #1088 will not resolve #866 since that path is just i.e. `/home/models/best.pt`. 

For #866 we need a bigger change, we need to leave task uninitialized until a mode is run, and then we determine task at mode runtime.

```
    # Guess from model filename
    if isinstance(model, (str, Path)):
        model = Path(model)
        if '-seg' in model.stem or 'segment' in model.parts:
            return 'segment'
        elif '-cls' in model.stem or 'classify' in model.parts:
            return 'classify'
        else:
            return 'detect'
```

**Comment by glenn-jocher** [comment]
@Laughing-q what should we use for keypoints, i.e. runs/keypoints/... and yolov8n-kpt or runs/pose/... and yolov8n-pose?

**Comment by Laughing-q** [comment]
@glenn-jocher yeah and probably we should rename all the keypoints in the code to pose as the `keypoints` there is actually for pose task only.
