### ISSUE TITLE
How to switch off augumentations ?

### ISSUE THREAD

**Issue by deepukr007** [ultralytics/ultralytics#11187]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi , I am trying to analyse the effect of different augumentaions on validation performance.
As a part of it, first I want to train the model without augumentaions first , I know by default the augment hyp is false as seens args.yaml but even though it is false I can see the message right before last 10 epochs which says switching off the mosaic augumentations ...

I also tried setting mosaic to 0.0 in the intitial hyp setting , but I am still getting the same message.

In what way I can make sure that training loop is not using augumented data ? or how to switch off augumentaions ?

**Comment by glenn-jocher** [comment]
@deepukr007 hello! 👋 To turn off all augmentations during training with YOLOv8, you can modify the hyperparameters (hyp) file that you pass to the training command. Here's a simple way to do it:

1. Make a copy of your current hyp file and open it for editing.
2. Set all augmentation-related parameters to `0` or `False`, depending on the parameter type. This includes `mosaic`, `mixup`, `flipud`, `fliplr`, and any other augmentation flags.
3. Save the modified hyp file.
4. When starting the training, specify your custom hyp file using the `hyp` argument, like this:

```bash
yolo train --data coco.yaml --cfg yolov8.yaml --weights yolov8.pt --hyp your_custom_hyp.yaml
```

This command ensures your model trains without using any data augmentations. 

Just a note, if you're specifically seeing a message about turning off mosaic augmentation in the last epochs, that's part of a designed behavior to stabilize training towards the end. By setting the augments to `0` or `False` as mentioned, you're ensuring they're off throughout all epochs.

Let me know if this helps or if you have more questions!
