### ISSUE TITLE
How to hide warning log "potential out-of-memory errors..."

### ISSUE THREAD

**Issue by SimplyOliv3r** [ultralytics/ultralytics#11192]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to supress this warning:

WARNING ⚠️ inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs
        
when tracking as:
 
model.track(source = videoPath, verbose = False, stream = False)

For i specific reason I want to use "stream = False" and I aware of the warning and do not want to display it in console.

**Comment by glenn-jocher** [comment]
Hello! To suppress the mentioned warning while using `stream=False` in your tracking setup, an option is to temporarily redirect standard output, which captures these warnings. Here's a quick way to achieve this in Python:

```python
import sys
import os

# Suppress warnings
sys.stderr = open(os.devnull, 'w')

# Your tracking code
model.track(source=videoPath, verbose=False, stream=False)

# Re-enable warnings
sys.stderr = sys.__stderr__
```

This code essentially diverts the `stderr` stream (where warnings are typically output) to `os.devnull`, effectively "muting" them. After running your tracking code, it's good practice to revert `stderr` back to its original setting to avoid missing out on other important warnings or errors.

Keep experimenting and happy coding! 😊

**Comment by SimplyOliv3r** [comment]
I do not know if I am doing something wrong, but I am using the exact code you provided and I still see the warning... I did try to catch error, redirect stderr, redirect stdout but nothing works for me. Any other suggestions?

**Comment by SimplyOliv3r** [comment]
That is what I have mentioned in my last response. Saying "I did try to catch error" I ment I did the exact same thing you just wrote and it did not stop warning from displaying. Im using anaconda prompt where I am running my program as python main.py. I am using python 3.11 if it helps you.

**Comment by glenn-jocher** [comment]
Hello @SimplyOliv3r,

Thank you for the clarification and additional details about your environment. Given the persistence of the warning even after using the `warnings` module, it appears that the warning might be output by the underlying system or library in a manner that bypasses standard Python warning controls.

As an alternative solution, could you try adjusting the environment variable for Python logging to suppress warnings? Here’s a quick snippet:

```python
import os
import logging

os.environ['PYTHONWARNINGS'] = 'ignore'
logging.getLogger('py.warnings').setLevel(logging.ERROR)

# Your tracking code
model.track(source=videoPath, verbose=False, stream=False)
```

This code attempts to configure the logging level directly as well as the environment settings to ignore Python warnings. Let's see if this method works in your case.

**Comment by JAEarly** [comment]
The solution that I got to work:
```
import logging
logging.disable(logging.WARNING)
# Model call
...
logging.disable(logging.NOTSET)
```
This disables all logging at warning and below just for the model inference call.

**Comment by glenn-jocher** [comment]
Thanks for sharing—your approach works; if you’d like to limit the scope to Ultralytics only, add a targeted logger filter for that specific message:

```python
import logging

class _SuppressStreamMsg(logging.Filter):
    def filter(self, record):
        return "inference results will accumulate in RAM unless `stream=True`" not in record.getMessage()

ultra_logger = logging.getLogger("ultralytics")
ultra_logger.addFilter(_SuppressStreamMsg())
# or: ultra_logger.setLevel(logging.ERROR)  # silence Ultralytics warnings only

model.track(source=videoPath, stream=False)
```

More on our logger is in the [Ultralytics logger reference](https://docs.ultralytics.com/reference/utils/logger/).
