### ISSUE TITLE
embedding projector

### ISSUE THREAD

**Issue by bonseong11** [ultralytics/ultralytics#11198]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can you implement that function with yolov8 like tensorboard embedding projector? You can also use tensorboard.

**Comment by glenn-jocher** [comment]
Hello! Thanks for reaching out with your question. 👋

Currently, YOLOv8 does not have a built-in feature exactly like TensorBoard's Embedding Projector. However, you can certainly use TensorBoard with YOLOv8 models for visualizing embeddings by extracting them separately during your model's evaluation stages and logging them to TensorBoard.

Here’s a quick code snippet on how you might log embeddings:

```python
from torch.utils.tensorboard import SummaryWriter
import torch

# Example tensor of embeddings and labels
embeddings = torch.randn(100, 512)  # example embeddings
labels = torch.randint(0, 10, (100,))  # example labels

writer = SummaryWriter()
writer.add_embedding(embeddings, metadata=labels)
writer.close()
```

Make sure to align this with how you handle your YOLOv8 outputs! If you need more specific guidance on integrating this with YOLOv8 or any other tasks, feel free to ask. 😊

**Comment by bonseong11** [comment]
What should I do if I apply the embedding value to the learning data using the yolo(detect) best.pt model?

**Comment by glenn-jocher** [comment]
Hello! To apply the embedding values from a YOLO model trained for detection (like your `best.pt` model), you'd typically first extract the embeddings during or after inference, then use these embeddings accordingly in your learning data. 

Here’s a concise example of how you might extract these embeddings from the model:

```python
from ultralytics import YOLO
import torch

# Load your trained model
model = YOLO('path/to/best.pt')

# Assuming 'images' is your batch of input images
images = torch.rand((1, 3, 640, 640))  # dummy data, replace with actual image tensor

# Get embeddings
with torch.no_grad():
    model.eval()
    embeddings = model(images, embed=True)  # Set embed=True to get embeddings

# Now you can use 'embeddings' in your learning data
```

Make sure that your `best.pt` model is set up to return embeddings. If it isn't, you may need to modify the model definition slightly. If you need more specific help on this, don't hesitate to ask. Happy coding! 😊

**Comment by udit7395** [comment]
@glenn-jocher As per [documentation](https://docs.ultralytics.com/modes/predict/#inference-arguments) mentioned over here embed seems to be taking list of ints? You shared here that embed is of type bool. I tried using it but got an error.

**Comment by glenn-jocher** [comment]
@udit7395 hello! Thanks for reaching out and for your detailed question. 😊

It looks like there might be a slight misunderstanding regarding the `embed` parameter usage. In YOLOv8, the `embed` parameter is indeed intended to be a boolean. When set to `True`, it typically enables the extraction of embeddings from a predefined layer or set of layers within the model.

The list of integers you're passing (`embed = [15, 18, 21]`) seems to be intended for specifying specific layers from which to extract embeddings. However, this functionality isn't directly supported through the `predict` method as you've tried.

To extract embeddings from specific layers, you would need to modify the model's forward method or access the intermediate layers directly using hooks or by modifying the model architecture.

Here's a quick example of how you might set up a forward hook to extract embeddings:

```python
import torch

def get_embeddings(module, input, output):
    global embeddings
    embeddings = output.detach()

# Assuming 'model' is your YOLOv8 model and 'layer_name' is the name of the layer you're interested in
layer = model.get_layer(layer_name)
hook = layer.register_forward_hook(get_embeddings)

# Run your prediction
result = model.predict(source=img, imgsz=480)

# 'embeddings' will now hold the output from the specified layer
hook.remove()  # Don't forget to remove the hook when you're done
```

Please replace `layer_name` with the actual name or index of the layer you're interested in. If you need further clarification on how to identify or use specific layers, feel free to ask!

**Comment by yu123596** [comment]
@glenn-jocher I had try your example code to get tensorboard embedding projector but it didn't work. I was expect to see the result like this. (MNIST with embedding projector)  
![messageImage_1722321084988](https://github.com/user-attachments/assets/416369df-68b3-48cb-a760-9d773a70bc99)

Can you check my code please? My custom classification have two classes. I use get_filelist function to get all image path in train file. Then turn image to tensor and input to model. 

`from ultralytics import YOLO
import torch
import os
import cv2
def get_filelist(dir, Filelist):
    newDir = dir
    if os.path.isfile(dir):
        Filelist.append(dir)
    elif os.path.isdir(dir):
        for s in os.listdir(dir):
            newDir=os.path.join(dir,s)
            get_filelist(newDir, Filelist)
    return Filelist

if __name__ == '__main__':
    model = YOLO("./runs/classify/NXPD_train/train6/weights/best.pt")
    img_dir = "./datasets/NX-DP_ver2/train/"
    img_list = get_filelist(img_dir,[])
    for img_path in img_list:
        images = torch.tensor((cv2.imread(img_path)))
        with torch.no_grad():
            model.eval()
            embeddings = model.predict(images, embed=True)

Final I get this error message after the "Starting training for 100 epochs...". It should not be start training right?

`  File ".....\lib\site-packages\torch\autograd\graph.py", line 744, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn)`

Also if I want to get a result like the MNIST with embedding projector, the best model must to go through training process again? Thank you!

**Comment by yu123596** [comment]
Not stale

**Comment by glenn-jocher** [comment]
It looks like you're encountering an issue with extracting embeddings from your trained YOLO model. The error you're seeing suggests that there's a problem with the gradient computation, which shouldn't be necessary for inference.

First, ensure you're using the latest version of the Ultralytics package. If the issue persists, it might be due to how the images are being processed and passed to the model. The `embed` parameter should be set correctly, but it seems there might be a misunderstanding in its usage.

Regarding your question about the embedding projector, you don't need to retrain the model to extract embeddings. You can extract embeddings from the trained model directly. However, ensure that the images are preprocessed correctly and match the input requirements of the model.

If you continue to face issues, please provide more details about the specific steps you're taking, and we can look into it further.

**Comment by nsriniva03** [comment]
@glenn-jocher ,

For YOLOv8, you mention that 'embed' should be a boolean. However, when I use model.predict('/path/to/image/', embed=True), I encounter the error: AttributeError: 'tuple' object has no attribute 'size'. But if I modify it to embed=[True], I get a feature vector of size 160.

Is this the correct embedding for similarity search? How can I extract embeddings to find visually similar objects in a custom dataset/model?

**Comment by Y-T-G** [comment]
@nsriniva03 `model.embed` is correct. And it's going to be image-level embedding, not object-level.

**Comment by nsriniva03** [comment]
@Y-T-G ,Thank you for your response.  Do you know how to get object level embedding? And why is there a difference in embedding size between the two approaches? What's the main difference between calling model.embed and model.predict(..,embed=True)

**Comment by Y-T-G** [comment]
`embed=[True]` is not correct. You're supposed pass the layer number. It treats `True` as 1, so it returns the second layer as embedding.

`model.embed()` returns the second last layer embedding. 

Getting object-level embeddings isn't directly supported. You can try this. But it's more complex.

https://y-t-g.github.io/tutorials/yolo-object-features/
