### ISSUE TITLE
Is TTA activated when augment=True during training/validation?

### ISSUE THREAD

**Issue by rusvagzur** [ultralytics/ultralytics#1119]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The question says it all pretty much.Is TTA activated when augment=True during training/validation? Or TTA is still to be implemented with Yolov8? Thanks

**Comment by glenn-jocher** [comment]
@rusvagzur augment=True is intended for predict mode only. It has no effect on train or val modes.

**Comment by rusvagzur** [comment]
Ok thanks! However, what's the type of augmentation happening? When I look at the training folder, I see, for example, in train_batch0.jpg, that the images are combined in a mosaic multiple times.
