### ISSUE TITLE
Add inference time as an attribute to the model.predict() class method.

### ISSUE THREAD

**Issue by joshleiph** [ultralytics/ultralytics#1121]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I'd like to be able to directly access the inference time whenever I call the predict() class method from YOLO. Currently it will print out to the console the inference time for a single pass, but it can not output inference time as a class attribute. Currently, the only result attributes I know of are:
- boxes
- masks
- prob
- cls
Having one simply be 'inference_time' as well would be very helpful for a lot of people I think.

### Use case

Having inference time directly as an attribute is essential to verify that your model is running at your desired frames per second when deployed.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@joshleiph thanks for raising this issue! Yes I agree all profiling times should be easily accessable. I think we made an update a few versions ago to add inference time to val results objects, if they are missing from predict Results I'll try to add them.

**Comment by glenn-jocher** [comment]
@joshleiph prediction profiling results now added to Result objects in https://github.com/ultralytics/ultralytics/pull/1141/commits/ee278ae4c4ed470fe863faa9ad99a782d1cdd7cb for deployment to 8.0.46 this weekend. 

<img width="795" alt="Screenshot 2023-02-24 at 19 02 00" src="https://user-images.githubusercontent.com/26833433/221332851-bf1ffcc1-20c3-488d-9fcf-4b047026e96c.png">


<img width="740" alt="Screenshot 2023-02-24 at 19 02 57" src="https://user-images.githubusercontent.com/26833433/221332886-7ee7131a-6323-4a39-b5b2-e6e2c4277aaa.png">

**Comment by joshleiph** [comment]
Just updated and tried it out; working exactly as I imagined it would, thank you!

**Comment by pderrenger** [comment]
@Vaevin glad to hear it's working as expected! Your feedback is greatly appreciated. If you have any more questions or suggestions, feel free to reach out. Happy detecting!
