### ISSUE TITLE
Multi-GPU Prediction

### ISSUE THREAD

**Issue by BogdanMarghescu** [ultralytics/ultralytics#1122]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello people! Could you please tell me if multi-GPU prediction is available? If yes, could you please tell me how exactly should I use it? Thank you very much in advance, have a great day!

**Comment by glenn-jocher** [comment]
@BogdanMarghescu Multi-GPU is reserved for training, but you can run prediction on any device and thread an inference workflow in that way, i.e. for GPU 3:

```
model('https://ultralytics.com/images/bus.jpg', device=3)
```

**Comment by BogdanMarghescu** [comment]
Understood, thank you very much!

**Comment by pderrenger** [comment]
@OMEGAMAX10 you're welcome! If you have any more questions or need further assistance, feel free to ask. Happy predicting!

**Comment by glenn-jocher** [comment]
@pderrenger Glad to help! Don't hesitate to reach out if you need more guidance. Happy predicting! 🚀
