### ISSUE TITLE
CUDA out of memory for running predictions

### ISSUE THREAD

**Issue by mehran66** [ultralytics/ultralytics#1123]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I am running predictions on 600 images of 1152*1152 on a GPU. I get the following CUDA out of memory error after about 200 successful predictions. Although slower, the predcition goes all fine on CPU. It does look like there is a bug on some sort of memory leak because the predictions are running sequentially and batch size does not matter here.

Traceback (most recent call last):
  File "/shared/data/personal_data/experiments/yolo_training/train.py", line 124, in <module>
    train_val_test(args)
  File "/shared/data/personal_data/experiments/yolo_training/train.py", line 84, in train_val_test
    _ = model.predict(**args)
  File "/shared/data/personal_data/experiments/yolo_training/ultralytics/ultralytics/yolo/engine/model.py", line 202, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/shared/data/personal_data/experiments/yolo_training/ultralytics/ultralytics/yolo/engine/predictor.py", line 116, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
  File "/shared/data/personal_data/experiments/yolo_training/ultralytics/ultralytics/yolo/engine/predictor.py", line 185, in stream_inference
    s += self.write_results(i, self.results, (p, im, im0))
  File "/shared/data/personal_data/experiments/yolo_training/ultralytics/ultralytics/yolo/v8/segment/predict.py", line 71, in write_results
    self.annotator.masks(
  File "/shared/data/personal_data/experiments/yolo_training/ultralytics/ultralytics/yolo/utils/plotting.py", line 118, in masks
    mcs = (masks_color * inv_alph_masks).sum(0) * 2  # mask color summand shape(n,h,w,3)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 486.00 MiB (GPU 0; 22.20 GiB total capacity; 20.15 GiB already allocated; 36.06 MiB free; 20.84 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Environment

Ultralytics YOLOv8.0.42 🚀 Python-3.10.6 torch-1.13.0
CUDA:0 (NVIDIA A10G, 22732MiB)
CUDA:1 (NVIDIA A10G, 22732MiB)
CUDA:2 (NVIDIA A10G, 22732MiB)
CUDA:3 (NVIDIA A10G, 22732MiB)
CUDA:4 (NVIDIA A10G, 22732MiB)
CUDA:5 (NVIDIA A10G, 22732MiB)
CUDA:6 (NVIDIA A10G, 22732MiB)
CUDA:7 (NVIDIA A10G, 22732MiB)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by mehran66** [comment]
and I am running the code from a recently cloned repo of yolo. I did notice this there is a relevant fix, but not sure if mine is different:
https://github.com/ultralytics/ultralytics/pull/723

**Comment by glenn-jocher** [comment]
@mehran66 thanks for the bug report! Can you provide exact code to reproduce?

**Comment by glenn-jocher** [comment]
@mehran66 I've tried to improve this in https://github.com/ultralytics/ultralytics/pull/1088/commits/8bd8fad9ee54a872681b3286fb73d307e084ecdd by moving all Results to CPU by default rather than keeping them on a CUDA device. This will be a part of 8.0.44 today.

Note you will eventually run out of memory (RAM or CUDA) if you try to process too many images at once, especially for segmentation since all result masks are saved. 

You can also try stream=True to handle results one at a time without accumulating them in your Results. @AyushExel can you explain a bit more about this?

**Comment by glenn-jocher** [comment]
@AyushExel @Laughing-q I noticed for masks results we have two identical tensors here. I couldn't figure out where this `masks.data` is coming from, but the contents are identical to `masks.masks`

```python
from ultralytics import YOLO

y=YOLO('yolov8n-seg')('ultralytics/assets')

y[0].masks.data == y[0].masks.masks).all()
Out[6]: tensor(True)
```

<img width="509" alt="Screenshot 2023-02-23 at 16 27 44" src="https://user-images.githubusercontent.com/26833433/221062266-8887a82a-3f86-4afc-9c4f-1b9aac10a09c.png">

**Comment by mehran66** [comment]
@glenn-jocher thanks! I think your changes by moving the results to cpu would solve the cuda memory issue, but still the out of the ram memory can be a potential issue as you mentioned. So I'm planning to run the predictions this way:

  for i in range(0, len(image_list), args['batch']):
      images_npy = [cv2.imread(image_path) for image_path in image_list[i:i + batch_size]]
      args['source'] = images_npy
      _ = model.predict(**args)

**Comment by Laughing-q** [comment]
@mehran66 hi can you share me your command or script that caused `cuda out of memory`?

**Comment by Laughing-q** [comment]
> @glenn-jocher thanks! I think your changes by moving the results to cpu would solve the cuda memory issue, but still the out of the ram memory can be a potential issue as you mentioned. So tried to run the predictions this way, but found another bug; the images/txts saved by running the predictions ignore the original image names and save them as image0, image1, etc and so predictions for each batch gets overwritten.
> 
> ```
> for i in range(0, len(image_list), args['batch']):
>     image_samples = image_list[i:i + args['batch']]
>     args['source'] = image_samples
>     _ = model.predict(**args)
> ```

the source from this script is numpy or filename?

**Comment by mehran66** [comment]
> > @glenn-jocher thanks! I think your changes by moving the results to cpu would solve the cuda memory issue, but still the out of the ram memory can be a potential issue as you mentioned. So tried to run the predictions this way, but found another bug; the images/txts saved by running the predictions ignore the original image names and save them as image0, image1, etc and so predictions for each batch gets overwritten.
> > ```
> > for i in range(0, len(image_list), args['batch']):
> >     image_samples = image_list[i:i + args['batch']]
> >     args['source'] = image_samples
> >     _ = model.predict(**args)
> > ```
> 
> the `source` in this script is numpy or filename?

@Laughing-q I have tried both numpy and filename and the results are the same...image0, image1, ....

**Comment by mehran66** [comment]
> @mehran66 hi can you share me your command or script that caused `cuda out of memory`?

Here is part the function runs train/val/test. The test part runs predictions for about 200 images and gives the cuda error.
  
    def train_val_test(args):

      device = 'cuda' if torch.cuda.is_available() else 'cpu'
  
      ######### load a pretrained model
      model = YOLO(args['model'])
      model.to(device)
  
      _ = model.train(**args)
  
      print('***********evaluate model performance on the test set***********')
       if torch.cuda.device_count() > 1:
           nbr_gpus = torch.cuda.device_count()
           args['batch'] = int(args['batch']/nbr_gpus)
           if args['batch'] < nbr_gpus:
               args['batch'] = nbr_gpus
              
       log_parent_dir = str(model.trainer.save_dir.parent)
       train_name = str(model.trainer.save_dir).split('/')[-1]
       args['name'] = train_name + '_val'
       args['mode'] = 'val'
       args['split'] = 'test'
       _ = model.val(**args)
  
      print('***********run inference on the test set***********')
      if args['source'] is None:
          args['source'] = model.trainer.data['test'] + r'/images'
      args['name'] = train_name + '_test'
      args['mode'] = 'predict'
      args['conf'] = 0.25
      args['iou'] = 0.45
      args['split'] = 'test'
      _ = model.predict(**args)
  
  
    if __name__ == '__main__':
        freeze_support()
  
      # args (get the config file from the command line)
      parser = argparse.ArgumentParser()
      parser.add_argument('--config', type=str, default='configs/config_training.yaml', help='path to config file')
      args_parser = parser.parse_args()
      config_file = args_parser.config
       args = utils.yaml_load(file=config_file, append_filename=False)
  
       train_val_test(args)





and the config is :
# Ultralytics YOLO 🚀, GPL-3.0 license
# Default training settings and hyperparameters for medium-augmentation COCO training

task: segment  # inference task, i.e. detect, segment, classify
mode: train  # YOLO mode, i.e. train, val, predict, export

# Train settings -------------------------------------------------------------------------------------------------------
model: yolov8x-seg.pt # path to model file, i.e. yolov8n.pt, yolov8n.yaml
data: '/shared/data/personal_data/experiments/yolo_training/data/sample_data_bf.yaml' # path to data file, i.e. i.e. coco128.yaml
epochs: 5  # number of epochs to train for
patience: 50  # epochs to wait for no observable improvement for early stopping of training
batch: 32  # number of images per batch (-1 for AutoBatch)
imgsz: 1152  # size of input images as integer or w,h
save: True  # save train checkpoints and predict results
save_period: 30 # Save checkpoint every x epochs (disabled if < 1)
cache: True  # True/ram, disk or False. Use cache for data loading
device: 0,1,2,3,4,5,6,7  # device to run on, i.e. cuda device=0 or device=0,1,2,3 or device=cpu
workers: 16  # number of worker threads for data loading (per RANK if DDP)
project:  # project name
name: ex1 # experiment name
exist_ok: False  # whether to overwrite existing experiment
pretrained: False  # whether to use a pretrained model
optimizer: SGD  # optimizer to use, choices=['SGD', 'Adam', 'AdamW', 'RMSProp']
verbose: True  # whether to print verbose output
seed: 0  # random seed for reproducibility
deterministic: True  # whether to enable deterministic mode
single_cls: False  # train multi-class data as single-class
image_weights: False  # use weighted image selection for training
rect: False  # support rectangular training if mode='train', support rectangular evaluation if mode='val'
cos_lr: False  # use cosine learning rate scheduler
close_mosaic: 30  # disable mosaic augmentation for final 10 epochs
resume: False  # resume training from last checkpoint
min_memory: False  # minimize memory footprint loss function, choices=[False, True, <roll_out_thr>]
# Segmentation
overlap_mask: False  # masks should overlap during training (segment train only)
mask_ratio: 1  # mask downsample ratio (segment train only)
# Classification
dropout: 0.0  # use dropout regularization (classify train only)

# Val/Test settings ----------------------------------------------------------------------------------------------------
val: True  # validate/test during training
split: val  # dataset split to use for validation, i.e. 'val', 'test' or 'train'
save_json: False  # save results to JSON file
save_hybrid: False  # save hybrid version of labels (labels + additional predictions)
conf:  # object confidence threshold for detection (default 0.25 predict, 0.001 val)
iou: 0.7  # intersection over union (IoU) threshold for NMS
max_det: 300  # maximum number of detections per image
half: False  # use half precision (FP16)
dnn: False  # use OpenCV DNN for ONNX inference
plots: True  # save plots during train/val

# Prediction settings --------------------------------------------------------------------------------------------------
source: /shared/data/personal_data/experiments/yolo/full_data_bf/test/images # source directory for images or videos
show: False  # show results if possible
save_txt: True  # save results as .txt file
save_conf: True  # save results with confidence scores
save_crop: False  # save cropped images with results
hide_labels: False  # hide labels
hide_conf: False  # hide confidence scores
vid_stride: 1  # video frame-rate stride
line_thickness: 1  # bounding box thickness (pixels)
visualize: False  # visualize model features
augment: False  # apply image augmentation to prediction sources
agnostic_nms: False  # class-agnostic NMS
classes:  # filter results by class, i.e. class=0, or class=[0,2,3]
retina_masks: False  # use high-resolution segmentation masks
boxes: True  # Show boxes in segmentation predictions

# Export settings ------------------------------------------------------------------------------------------------------
format: torchscript  # format to export to
keras: False  # use Keras
optimize: False  # TorchScript: optimize for mobile
int8: False  # CoreML/TF INT8 quantization
dynamic: False  # ONNX/TF/TensorRT: dynamic axes
simplify: False  # ONNX: simplify model
opset:  # ONNX: opset version (optional)
workspace: 4  # TensorRT: workspace size (GB)
nms: False  # CoreML: add NMS

# Hyperparameters ------------------------------------------------------------------------------------------------------
lr0: 0.01  # initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
lrf: 0.01  # final learning rate (lr0 * lrf)
momentum: 0.937  # SGD momentum/Adam beta1
weight_decay: 0.0005  # optimizer weight decay 5e-4
warmup_epochs: 3.0  # warmup epochs (fractions ok)
warmup_momentum: 0.8  # warmup initial momentum
warmup_bias_lr: 0.1  # warmup initial bias lr
box: 7.5  # box loss gain
cls: 0.5  # cls loss gain (scale with pixels)
dfl: 1.5  # dfl loss gain
fl_gamma: 0.0  # focal loss gamma (efficientDet default gamma=1.5)
label_smoothing: 0.0  # label smoothing (fraction)
nbs: 64  # nominal batch size
hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # image HSV-Value augmentation (fraction)
degrees: 45.0  # image rotation (+/- deg)
translate: 0.1  # image translation (+/- fraction)
scale: 0.5  # image scale (+/- gain)
shear: 0.0  # image shear (+/- deg)
perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
flipud: 0.0  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)
mosaic: 1.0  # image mosaic (probability)
mixup: 0.0  # image mixup (probability)
copy_paste: 0.1  # segment copy-paste (probability)

# Custom config.yaml ---------------------------------------------------------------------------------------------------
cfg:  # for overriding defaults.yaml

# Debug, do not modify -------------------------------------------------------------------------------------------------
v5loader: False  # use legacy YOLOv5 dataloader

# Tracker settings ------------------------------------------------------------------------------------------------------
tracker: botsort.yaml  # tracker type, ['botsort.yaml', 'bytetrack.yaml']

**Comment by Laughing-q** [comment]
> @Laughing-q I have tried both numpy and filename and the results are the same...image0, image1, ....
It would be great if the predictions have the name of input image list

We are supporting the following usage and this is how we designed this part:
```python
model.predict(source=["filename", numpy, PIL])
```
So for now we don't remember the filename if the `source` is a list since `numpy` and `PIL` do not include filename info and we can't predict what users will put in the list, i.e `numpy`, `PIL` or `filename`.

**Comment by Laughing-q** [comment]
@mehran66 Thanks for the script sharing! Yeah like @glenn-jocher said, you will always eventually run out of memory if there're too many images or you are running a video/stream, that's because the resolution of the predicted masks can be high and the number of it also might be a lot. 
Strongly recommend you to use `stream=True` when predicting with a segmentation model.

BTW v5 repo do not have this issue, but that's because we don't return predicted masks in v5. Basically we introduce this feature in v8 repo but actually there are some issues that we can not 100% avoid.

**Comment by Laughing-q** [comment]
@nikky4D Well, actually batch inference should work properly in most cases as long as we only keep one batch's predicted masks in memory, and this is how we do in v5 repo and in this repo with `stream=True`.
But since we're returning predicted masks here, which we need to keep all the predicted masks in memory and return it in the end instead of keeping just one batch's masks.

For example:
let's say here's a `folder` including 500 images:
in v5 repo with `python segment/predict.py --weights .. --source folder`, there will always be only one image's predicted masks in memory while predicting, but does not return the predicted masks in the end.

In this repo with:
```python
results=model.predict(source=folder)
```
since results is returned here, the process by default is keeping adding predicted masks of each image until it's gone through all the 500 images. So there will be predicted masks of 500 images in the memory which could easily cause `run out of memory`.

In this repo with `stream=True`:
```python
for result in model.predict(source=folder, stream=True):
    pass
```
in this way the predicted masks is still returned and also there's predicted masks of only one image in memory.

That's why we recommand `stream=True` when there're many images or the source is a video/stream.

**Comment by Arshadoid** [comment]
@Laughing-q  I'm currently getting out of memory error for validation. Before opening an issue, wanted  to check first. Do you think the solution you provided might be valid for validation as well?

**Comment by glenn-jocher** [comment]
@Arshadoid yes, the solution of using `stream=True` should also work for the validation data. Since the validation data is typically a smaller subset of the entire dataset, we may not always face this out of memory issue. However, if the validation data is large enough, it could still cause an out of memory error. In such cases, using `stream=True` can help by processing data in batches and reducing memory requirements. Additionally, we can also reduce the batch size or use a smaller model if the issue persists.

**Comment by Laughing-q** [comment]
@Arshadoid do you mean val mode? I believe `stream` only works for predict mode.

**Comment by Arshadoid** [comment]
@Laughing-q  Yes, you are right, it didn't work for validation. 
@glenn-jocher Reducing the batch size helped with the issue. 

Thanks for the help!

**Comment by glenn-jocher** [comment]
@Arshadoid glad to hear that reducing the batch size has helped with the issue you faced. This is a common solution for addressing the out of memory error during training or validation. By reducing the batch size, you can limit the number of samples processed in each forward and backwards pass, which in turn requires less memory usage. However, reducing the batch size also means reducing the number of samples being trained at once, which can result in slower learning and longer training time. It's always recommended to find a balance between the batch size and training time to optimize the training process. Additionally, you can also consider using hardware capable of handling large batch sizes or using mixed precision training, which can help you train using larger batch sizes without running out of memory.
