### ISSUE TITLE
Problems using DDP with CustomTrainer

### ISSUE THREAD

**Issue by silvada95** [ultralytics/ultralytics#1124]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

By some reason when I try to use DDP with a CustomTrainer the code does not work

Here an example:

from ultralytics.yolo.v8.detect import DetectionTrainer

class CustomTrainer(DetectionTrainer):
  def get_model(self, cfg=None, weights=None, verbose=True):
     model = DetectionModel(cfg, ch=3, nc=self.data['nc'], verbose=verbose and RANK == -1)   
     if weights:
        model.load(weights)
     return model
trainer = CustomTrainer(overrides={"device":"0,1","project":"test_ultralytics","data":"my_data.yaml"})
trainer.train()

The error is:

" File "/home/silvada/.config/Ultralytics/DDP/_temp_1mtd3yii23013075682544.py", line 3
    from ultralytics. import CustomTrainer
                      ^
SyntaxError: invalid syntax"

I was checking, and it seems to come from the function "generate_ddp_file" from "ultralytics/yolo/utils/dist.py"

The command " from ultralytics.{import_path}" seems to not be pointing to the proper place.

What should I do?

**Comment by glenn-jocher** [comment]
@silvada95 thanks for the bug report! I've updated DDP file generator in PR #1141 commit https://github.com/ultralytics/ultralytics/pull/1141/commits/d8af3cad9c2ae4880b2962bccaa83a523cc0bb0e to accomodate this use case. This update will merge to main land deploy with 8.0.46 later today. Please let us know if this resolves your issue and if you have any other problems.

**Comment by silvada95** [comment]
Thank you very much for your attention. Besides this, everything is working perfectly fine. I was able to run my python script adding the "torch.distributed.run" the beginning, then bypassing the execution of the mentioned function.

**Comment by pderrenger** [comment]
You're welcome, @silvada95! I'm glad to hear that you were able to find a workaround for the issue and that everything else is working fine for you. Don't hesitate to reach out if you encounter any other challenges or have further questions. Happy coding!
