### ISSUE TITLE
<A bug in Data Augmentation>YOLOv8-OBB  

### ISSUE THREAD

**Issue by Wangfeng2394** [ultralytics/ultralytics#11246]

**Comment by glenn-jocher** [comment]
@Wangfeng2394 hi there! Thanks for bringing this to our attention. It looks like there might be an issue with the OBB labels in the data augmentation process for specific images.

To better diagnose and potentially resolve this issue, could you please provide a snippet of the code you're using for the data augmentation? Additionally, checking if the problematic images have anything in common (such as unusual aspect ratios or annotations) might be helpful.

Here's a general check you can perform to ensure that your annotations are being read correctly:
```python
from ultralytics import YOLO
model = YOLO('path/to/your/model.yaml').load('path/to/your/model.weights')
dataset = model.load_data('path/to/your/data.yaml')
print(dataset[0]['labels'])  # Check the first image labels
```
This will help confirm whether the issue is occurring during the initial data loading or during the augmentation process.

Let me know if this helps or if you need further assistance!

**Comment by Wangfeng2394** [comment]
Thanks for your attention！！
Give you my files as follows：
Jpg picture file as：
![RkShagou_09420](https://github.com/ultralytics/ultralytics/assets/42164696/96159fa5-1217-40eb-881e-d38f8c55a983)

and label as：
45 0.128909 0.778827 0.257771 0.760667 0.145893 0.89935 0.274755 0.881191


then my train parameters as:

from ultralytics import YOLO
 
import torch
device = torch.device("cuda")

def main():
    model = YOLO('models/v8/yolov8-obb.yaml').load('Traning_Large/best.pt')  # build from YAML and transfer weights
    model.train(data='datasets/my.yaml', 
    pretrained=True,#预训练   (bool | str) whether to use a pretrained model (bool) or a model to load weights from (str)
    resume= False, # (bool) resume training from last checkpoint
    project='Traning_Large', # (str, optional) project name
    lr0=0.015,  # (float) initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
    lrf=0.005,  # (float) final learning rate (lr0 * lrf)
    epochs=230, 
    imgsz=1024, 
    batch=8, 
    workers=16,
    degrees=180,
    hsv_s= 0.18,
    hsv_v= 0.23,
    hsv_h= 0.12,
    flipud= 0.5,
    fliplr= 0.5,
    patience=100,# int型，设置没有明显的性能提升则停止训练
    cache= False,# (bool) True/ram, disk or False. Use cache for data loading
    device= 0,
    mosaic= 0.45,# (float) image mosaic (probability)
    box= 9.5, # (float) box loss gain
    cls= 0.5, # (float) cls loss gain (scale with pixels)
    dfl= 1.5, # (float) dfl loss gain
    translate= 0.15, # (float) dfl loss gain
    close_mosaic= 57, # (int) disable mosaic augmentation for final epochs (0 to disable)
    auto_augment= 'randaugment',# (str) auto augmentation policy for classification (randaugment, autoaugment, augmix)
    mixup= 0.0, # (float) image mixup (probability)
    scale= 0.34, # (float) image scale (+/- gain)
    erasing=  0.1,# 遮挡(float) probability of random erasing during classification training (0-0.9), 0 means no erasing, must be less than 1.0.
    show= True,
    nbs= 64,
    label_smoothing=0.03, # (float) label smoothing (fraction)
    visualize= True,
    perspective= 0.00003 # (float) image perspective (+/- fraction), range 0-0.001
    )
if __name__ == '__main__':
    main()

**Comment by Wangfeng2394** [comment]
I try to confirm as your according to your guidance, but It seem like my "YOLO" object has no attribute 'load_data'.
![image](https://github.com/ultralytics/ultralytics/assets/42164696/e7441ffb-af1d-469a-a127-0deb135ece9d)

**Comment by glenn-jocher** [comment]
Hey there! 👋 It looks like there's a small confusion. The correct method to load data directly isn’t available like that. Instead, you can verify your dataset's labels during training with the displayed batch samples in your `train_batch0.jpg` or by utilizing the DataLoader like this:

```python
from ultralytics import YOLO, Dataloader

# Load your model
model = YOLO('models/v8/yolov8-obb.yaml').load('Traning_Large/best.pt')

# Create a DataLoader
loader = Dataloader('datasets/my.yaml', img_size=model.imgsz, batch_size=model.batch, stride=model.stride)

# Access an image and its labels
img, labels, _, _ = next(iter(loader))
print(labels)  # Display labels
```

This way, you can check if labels are loaded correctly as part of your verification process. Let me know if this clears things up or if there's anything else you need! 😊

**Comment by Wangfeng2394** [comment]
Thanks for your help and patience patience！

ImportError: cannot import name 'Dataloader' from 'ultralytics' (C:\Users\admin\.conda\envs\yolov8\lib\site-packages\ultralytics\__init__.py)

so how can I get Dataloader ？ It seem like 'Dataloader'  in my  'ultralytics' 。

**Comment by Wangfeng2394** [comment]
Could you please use the data I provided above to check it？😊

**Comment by glenn-jocher** [comment]
@Wangfeng2394 hi there! 😊

Thank you for providing the data! Since you've already shared some data details in previous comments, I'll use that information for debugging. I recommend running local checks or visual inspections on specific data samples you're concerned about to see if there's a clear discrepancy or error in how labels are being applied during training.

In the meantime, if you wish to test out specific scenarios, feel free to adjust your code as needed and re-check the outputs. If you continue to encounter problems, providing more data examples, or describing in detail the discrepancies you notice, can help us assist you better!

Thanks for your cooperation! 🚀

**Comment by Wangfeng2394** [comment]
> @Wangfeng2394 hi there! 😊
> 
> Thank you for providing the data! Since you've already shared some data details in previous comments, I'll use that information for debugging. I recommend running local checks or visual inspections on specific data samples you're concerned about to see if there's a clear discrepancy or error in how labels are being applied during training.
> 
> In the meantime, if you wish to test out specific scenarios, feel free to adjust your code as needed and re-check the outputs. If you continue to encounter problems, providing more data examples, or describing in detail the discrepancies you notice, can help us assist you better!
> 
> Thanks for your cooperation! 🚀
Okay, please let me know as soon as possible. Thank you
I will also continue to provide feedback on my information

**Comment by Wangfeng2394** [comment]
> @Wangfeng2394 hi there! 😊
> 
> Thank you for providing the data! Since you've already shared some data details in previous comments, I'll use that information for debugging. I recommend running local checks or visual inspections on specific data samples you're concerned about to see if there's a clear discrepancy or error in how labels are being applied during training.
> 
> In the meantime, if you wish to test out specific scenarios, feel free to adjust your code as needed and re-check the outputs. If you continue to encounter problems, providing more data examples, or describing in detail the discrepancies you notice, can help us assist you better!
> 
> Thanks for your cooperation! 🚀

Okay, please let me know as soon as possible. Thank you
I will also continue to provide feedback on my information

**Comment by glenn-jocher** [comment]
@Wangfeng2394 Thanks for your response and willingness to keep the feedback coming! 🌟 I'll get back to you as soon as I have an update based on the debugging. In the meantime, any additional information you provide will be incredibly helpful. Happy testing! 😊
