### ISSUE TITLE
RTSP path is changed from the defined url when inference

### ISSUE THREAD

**Issue by pornpra** [ultralytics/ultralytics#11244]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I ran object tracking using YOLOv8 with an RTSP URL.

```python
model = YOLO('yolov8s.pt', task='detect')
results = model.track(source, device=device, stream=True, classes=classes, verbose=False, stream_buffer=True, tracker=byte_track)
for pred in results:
    path = pred.path
```
During inference, I printed the path from the prediction results and noticed a change in the stream URL where certain characters were replaced e.g. : changed to _, = changed to _, and @ changed to _.

Original URL: rtsp://abcd:abcd123456@xx.xx.xx.x:yyy/trackID=1&streamID=1
Changed URL: rtsp_//abcd_abcd123456_xx.xx.xx.x_yyy/trackID_1_streamID_1

How can I return the original stream URL during inference ?

**Comment by pornpra** [comment]
@glenn-jocher Do you have any updates for this issue ?

**Comment by glenn-jocher** [comment]
Hi there! I'm here to help with the issue.

Regarding the changes in the RTSP URL: it appears that URL sanitization is happening somewhere within the processing pipeline. This might be part of the logging or handling mechanism in the software to make URLs safe for display or storage.

To assist you further, could you confirm if you viewed this changed URL in logs or as output in your environment? Getting this detail could help pinpoint if it's a display issue or if the URL is being modified internally.

Looking forward to your response to help resolve this effectively!

**Comment by pornpra** [comment]
Hi

Today I tested four stream URLs, and I can confirm that all of them changed when I printed path from pred.path to my terminal. 

Original URL: rtsp://abcd:abcd123456@xx.xx.xx.x:yyy/trackID=1&streamID=1
Changed URL: rtsp_//abcd_abcd123456_xx.xx.xx.x_yyy/trackID_1_streamID_1

(I am using Ultralytics version 8.0.200).

**Comment by VM8198** [comment]
@glenn-jocher this url is returned in result response as path if the source is RTSP stream. So, if anyone would like to compare the source RTSP stream with results to get the channel Id  after result than it is not getting possible. if you can provide how the stream url is getting sanitized than it would be helpful.

**Comment by glenn-jocher** [comment]
Hello!

Thanks for sharing your observations. It seems like the URL is being sanitized internally, possibly to ensure file system compatibility when saving logs or outputs. This behavior is typical in many systems to avoid issues with special characters in paths.

If you need to use the original URL during your processing, you might consider maintaining a separate variable to store the original URL string for reference, or you could map the sanitized version back to the original using a dictionary if the transformations are consistent.

Here's a quick example of how you might handle this:

```python
original_urls = {
    'rtsp_//abcd_abcd123456_xx.xx.xx.x_yyy/trackID_1_streamID_1': 'rtsp://abcd:abcd123456 @pornpra.xx.xx.x:yyy/trackID=1&streamID=1'
}

# When you need to use the original URL
sanitized_url = pred.path  # from your results
original_url = original_urls.get(sanitized_url, 'Default or error handling URL')
```

This way, you can ensure you're working with the correct format for your needs. Let me know if this helps or if you have any more questions! 😊
