### ISSUE TITLE
YOLO V8 in Predict 

### ISSUE THREAD

**Issue by SirishaJP** [ultralytics/ultralytics#1125]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, 

Good day! Great Job with YOLO V8, I have a small query on Yolo v8's predict, while I was working with YOLO V5, the inference output was the resultant image with a bounding box and confidence value. However, for yolo v8, it prints the pixel values on the image. Please find the attachment of the screenshot below.

I tried plotting using matplotlib and PIL. But, I couldn't get the desired output. I was wondering if I'm missing out on anything or if it's a bug, I have tried all the solutions as per the discussion in the Issues session. I'm looking forward to your reply. 

Thank you. 

<img width="740" alt="Screenshot 2023-02-24 at 01 36 11" src="https://user-images.githubusercontent.com/104147973/221063708-779a90ad-7123-47b3-85a1-34947fb34484.png">

**Comment by glenn-jocher** [comment]
@SirishaJP you are showing results from a classification model, i.e. `yolov8n-cls.pt` If you want bounding boxes then you want to use a detection model, i.e. `yolov8n.pt`:

```bash
from ultralytics import YOLO

model = YOLO('yolov8n.pt')
results = model('https://ultralytics.com/images/bus.jpg', save=True)
```

See classification and detection usage examples see https://docs.ultralytics.com/
