### ISSUE TITLE
detect task ddp run is failed

### ISSUE THREAD

**Issue by pyl62112991** [ultralytics/ultralytics#1126]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

![3C6549C5-7A44-41ba-8E2B-13D3724888E0](https://user-images.githubusercontent.com/47971541/221070990-a022ca50-2341-4ab2-817e-3eba61799613.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@pyl62112991 can you share the command you used and the full error log? Thanks!

**Comment by pyl62112991** [comment]
yolo task=detect mode=train model='./last.pt' data=/home/liyuping/program/ultralytics/coco.yaml epochs=300 batch=12  device=4,5,6,7   workers=8  imgsz=1280 

this is the command

**Comment by pyl62112991** [comment]
yolo task=detect mode=train model='./last.pt' data=/program/ultralytics/coco.yaml epochs=300 batch=12  device=4,5,6,7   workers=8  imgsz=1280

this is the command

**Comment by Laughing-q** [comment]
@pyl62112991 is there also a full error log? 
actually the `FileNotFoundError` in you above picture probably is not the exact error you encountered which I'm working on fixing this misleading information.

**Comment by pyl62112991** [comment]
![微信图片编辑_20230224155846](https://user-images.githubusercontent.com/47971541/221124296-6ac2f50e-37d2-453d-b148-2287f0988c2d.jpg)
ok ,thanks.

**Comment by Laughing-q** [comment]
@pyl62112991 so the real error is `TypeError: barrier() got an unexpected keyword argument ‘device_ids’` which I think it's related to you torch version. please upgrade your torch package version. :)
BTW I'm using torch-1.10.2 which works correctly to me.

**Comment by pyl62112991** [comment]
ok thanks , i will  have a try

**Comment by pderrenger** [comment]
@pyl62112991 you're welcome! If you encounter any further issues, feel free to ask for assistance. Good luck with your training!
