### ISSUE TITLE
imgsz not working properly on onnx format predict

### ISSUE THREAD

**Issue by Wenlong0913** [ultralytics/ultralytics#1131]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

If the input image size is not a square shape, the `imgsz` argument seems like not working properly on onnx format.
After training a custom model with custom input size, we exported it to onnx format.
```
yolo classify train data=airport model=yolov8m-cls.pt epochs=100 workers=0 imgsz=416,128 batch=64
yolo export model=runs/classify/train/weights/best.pt format=onnx imgsz=128,416
```
imgsz on task `train` requires to be an integer or `[w,h]`, however, imgsz on `export` requires to be an integer or `[h,w]`. Hope it can be consistent in the future.

The tricky thing is that when we try to do inference work, the console tells the input dimensions are not correct, no matter [h,w] or [w,h] is used.
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/17941167/221085679-f8fe47fa-9140-497d-8834-30f570074982.png">
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/17941167/221085784-9faa988c-81ff-40ae-a9da-1df181e19526.png">

### Environment

- YOLO ultralytics  8.0.44
- OS Ubuntu 22.04
- Python 3.10.6

### Minimal Reproducible Example

```
yolo classify train data=airport model=yolov8m-cls.pt epochs=100 workers=0 imgsz=416,128 batch=64
yolo export model=runs/classify/train/weights/best.pt format=onnx imgsz=128,416
yolo predict task=classify model=runs/classify/train/weights/best.onnx imgsz=416,128 source=./test.jpg
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@Wenlong0913 hi, we only support square images as input for classify for now.
Since we have a `CenterCrop` operation here as a preprocess operation for classify.
@AyushExel

**Comment by glenn-jocher** [comment]
@Wenlong0913 thanks for the bug report! You can try to export onnx with dynamic to allow for dynamic input shapes, but yes for classification models these should be square inputs since we use a centercrop transform.

All imgsz inputs in YOLO should be of the same h,w order. Can you point out where this is different?

**Comment by Wenlong0913** [comment]
Oh, I see. In our case, the solution is to generate a square inputs and fill the blank. Thanks, I'll close this issue soon.
@glenn-jocher The doc says the imgsz should be `integer or w,h`.
https://docs.ultralytics.com/cfg/
<img width="794" alt="image" src="https://user-images.githubusercontent.com/17941167/221336915-928eff42-2de9-4785-8674-e489aab3f49f.png">
Do you mean within all yolo tasks, we should keep the imgsz in h,w order?

**Comment by Wenlong0913** [comment]
@glenn-jocher H
