### ISSUE TITLE
yolov8 segment head

### ISSUE THREAD

**Issue by zhangming8** [ultralytics/ultralytics#1145]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, thanks for your greate work.
I am reading your segment code, and could you tell me which paper do you refer to in the implement of "YOLOv8 Segment head"?

**Comment by glenn-jocher** [comment]
@zhangming8 Segment() head used in YOLOv8 is here:
https://github.com/ultralytics/ultralytics/blob/3765f4f6d94d4915123d5b866a327838b3fc096b/ultralytics/nn/modules.py#L433-L454

And usage example and documentation for Segmentation models are here: https://docs.ultralytics.com/tasks/segmentation

**Comment by zhangming8** [comment]
> @zhangming8 Segment() head used in YOLOv8 is here:
> 
> https://github.com/ultralytics/ultralytics/blob/3765f4f6d94d4915123d5b866a327838b3fc096b/ultralytics/nn/modules.py#L433-L454
> 
> And usage example and documentation for Segmentation models are here: https://docs.ultralytics.com/tasks/segmentation

Yeah, thanks, and could you tell me which paper propose this method?

**Comment by glenn-jocher** [comment]
It's built from YOLOv5 segment head which in turn was inspired by other segment architecture like yolact

**Comment by zhangming8** [comment]
Got it, thanks

**Comment by pderrenger** [comment]
@zhangming8 you're welcome! If you have any more questions or need further assistance, feel free to ask. Happy coding!

**Comment by glenn-jocher** [comment]
You're welcome, @pderrenger! If you need further assistance, don't hesitate to reach out. Happy coding! 😊👍
