### ISSUE TITLE
Where does the pip installed cli save prediction runs?

### ISSUE THREAD

**Issue by netrosec** [ultralytics/ultralytics#1146]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm making use of the cli. I found documentation for the new arg parser.
What I can't seem to find is the save location of the video when using the `pip install ultralytics` version in cli.

**Comment by AyushExel** [comment]
It should save results in the current working dir ( the directory from which you're runnning the command). The format is something like this - > `runs/{TASK}/{MODE}` which for a detection prediction will be `runs/detect/predict`.
Also, remember to enable saving by passing `save=True`

**Comment by netrosec** [comment]
Thanks @AyushExel. where can i find all the updated command flags for v8?

**Comment by AyushExel** [comment]
The configuration section of the docs
