### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by zyakubova86** [ultralytics/ultralytics#1147]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

when i run the code to train segmentation runtime error occurring. image attached.

### Minimal Reproducible Example

![image](https://user-images.githubusercontent.com/74640447/221358137-00bba890-a6d2-4375-b501-6f71becce77c.png)

### Additional

how can i fix this?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@zyakubova86 thanks for the bug report. This error appears because you are attempting to train a segmentation model on a detection dataset. If you train a segmentation model on a segmentation dataset the error disappears.

```python
from ultralytics import YOLO

results = YOLO('yolov8n-seg.pt').train(data='coco128.yaml')  # INCORRECT, user error
results = YOLO('yolov8n-seg.pt').train(data='coco128-seg.yaml')  # CORRECT
```

Removing bug tag as not a bug. Please let us know if this resolves your error for you.

**Comment by glenn-jocher** [comment]
@zyakubova86 also see Segmentation docs for additional usage examples at https://docs.ultralytics.com/tasks/segmentation/

**Comment by zyakubova86** [comment]
@glenn-jocher, thanks a lot. it worked. But when I run custom model on ip camera another error throwing:

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 24.00 GiB total capacity; 16.06 GiB already allocated; 11.62 MiB free; 16.99 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF.

I added this to my main file: os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:1024"
How can I fix this? I need to run 4 cameras to predict.

**Comment by zyakubova86** [comment]
![image](https://user-images.githubusercontent.com/74640447/221491601-4e5b9228-2558-447e-ad2e-91f515ee7c98.png)


running on windows 10 pro. gpu nvidia geforce rtx 3090

**Comment by Laughing-q** [comment]
@zyakubova86 I recommend you to set `stream=True` when predicting a video/stream with segmentation model.
related issus: [https://github.com/ultralytics/ultralytics/issues/1123](https://github.com/ultralytics/ultralytics/issues/1123)

**Comment by zyakubova86** [comment]
thanks

**Comment by zyakubova86** [comment]
I have one more question. Can I run a file as a source like in yolov5 streams.txt?

**Comment by Laughing-q** [comment]
@zyakubova86 sure! but with suffix  `.streams` instead of `.txt` for multiple streams.
here're the formats we support:
```python
Usage - sources:
    $ yolo mode=predict model=yolov8n.pt --source 0                               # webcam
                                                  img.jpg                         # image
                                                  vid.mp4                         # video
                                                  screen                          # screenshot
                                                  path/                           # directory
                                                  list.txt                        # list of images
                                                  list.streams                    # list of streams
                                                  'path/*.jpg'                    # glob
                                                  'https://youtu.be/Zgi9g1ksQHc'  # YouTube
                                                  'rtsp://example.com/media.mp4'  # RTSP, RTMP, HTTP stream
```

**Comment by zyakubova86** [comment]
I am getting a runtime error again while training custom segmentation model ((
How can I fix this? 


![image](https://user-images.githubusercontent.com/74640447/221948195-f6d43ad6-7698-4373-b1d3-f7cda7f9325d.png)

**Comment by Laughing-q** [comment]
@zyakubova86 like @glenn-jocher has said above [https://github.com/ultralytics/ultralytics/issues/1147#issuecomment-1445146391](https://github.com/ultralytics/ultralytics/issues/1147#issuecomment-1445146391), please make sure your dataset is segment label instead of detection label when you want to train a segmentation model.
