### ISSUE TITLE
All Losses are NAN in YOLOV8 training in Anaconda

### ISSUE THREAD

**Issue by lokeshfallen** [ultralytics/ultralytics#1149]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

While Training the model in v8 with GPU all the losses becomes **nan** and all the evaluation metrics becomes **zero**. 

Under Anaconda Environment with Pytorch 1.13.1+cu116, Python 3.6
Is there any possible solutions for this issue.

![v8-error](https://user-images.githubusercontent.com/99633614/221360048-25a7d6c8-b256-4233-ab3d-73dbf2790e6e.png)

### Environment

- YOLOV8
- Anaconda Environment
- Python 3.9.16
- PyTorch 1.13.1+cu116

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@lokeshfallen if this is reproducible with a common dataset, i..e `yolo train data=coco128.yaml` please provide us exact code to reproduce, otherwise it's likely the issue may rest with your dataset or any non-default arguments you've introduced..

**Comment by lokeshfallen** [comment]
@glenn-jocher  Thanks for replying. The same errors are reproduced with coco128.yaml. 
`yolo task=detect mode=train data=coco128.yaml model=yolov8s.pt epochs=5 batch=4 workers=3 imgsz=640`
![Screenshot (7)](https://user-images.githubusercontent.com/99633614/221369535-defb2188-85a2-4153-b3bc-d690a190b2c6.png)

With Custom dataset
`yolo task=detect mode=train data=custom.yaml model=yolov8s.pt epochs=5 batch=4 workers=3 imgsz=640`
![Screenshot (9)](https://user-images.githubusercontent.com/99633614/221369844-949c42b4-5108-4491-ba89-016a8ead5780.png)

**Comment by Laughing-q** [comment]
@lokeshfallen can't really reproduce the issue with the same command `yolo task=detect mode=train data=coco128.yaml model=yolov8s.pt epochs=5 batch=4 workers=3 imgsz=640
` here:
![pic-full-230227-1602-38](https://user-images.githubusercontent.com/61612323/221507048-ed08d966-53d5-4986-b37e-9141797f704c.png)

**Comment by nikbobo** [comment]
@lokeshfallen Could you tell me which GPU device(ie. GTX1080) is using to training? I found sometimes is not a YOLO problem, it’s PyTorch Autocast problem, which is NaN in some device and some PyTorch version.
Generally, it cloud fix it by changing the PyTorch or CUDA version, changing the GPU device(ie. A100), and modifying code to close the Autocast.
Autocast is the training strategy which is mixed the FP16 and FP32, it enabled in YOLO by default in global.

**Comment by lokeshfallen** [comment]
@nikbobo Thanks for the suggestion. Actually the GPU I am working with is NVIDIA GTX 1650ti. 
Also, It would be helpful if the alterations that are needed in Autocast is stated.

**Comment by lokeshfallen** [comment]
> @lokeshfallen can't really reproduce the issue with the same command `yolo task=detect mode=train data=coco128.yaml model=yolov8s.pt epochs=5 batch=4 workers=3 imgsz=640 ` here: ![pic-full-230227-1602-38](https://user-images.githubusercontent.com/61612323/221507048-ed08d966-53d5-4986-b37e-9141797f704c.png)

Can you please mention the specifications under which you are running YOLOv8...
Thank You

**Comment by 634739726** [comment]
> ### Search before asking
> 
>     * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.
> 
> 
> ### YOLOv8 Component
> 
> Training
> ### Bug
> 
> While Training the model in v8 with GPU all the losses becomes **nan** and all the evaluation metrics becomes **zero**.
> 
> Under Anaconda Environment with Pytorch 1.13.1+cu116, Python 3.6 Is there any possible solutions for this issue.
> 
> ![v8-error](https://user-images.githubusercontent.com/99633614/221360048-25a7d6c8-b256-4233-ab3d-73dbf2790e6e.png)
> ### Environment
> 
>     * YOLOV8
> 
>     * Anaconda Environment
> 
>     * Python 3.9.16
> 
>     * PyTorch 1.13.1+cu116
> 
> 
> ### Minimal Reproducible Example
> 
> _No response_
> ### Additional
> 
> _No response_
> ### Are you willing to submit a PR?
> 
>     * [ ]  Yes I'd like to help by submitting a PR!

oh, I have the same problem as you. 
My  python environment is Python-3.7.9 torch-1.9.1+cu111 CUDA:0 (GeForce GTX 1660, 6144MiB)
How do you fix it?

**Comment by TonyCarrick** [comment]
Hi all,
I have the same issue.  Running in coda environment.  CUDA is 11.6, GPU is Geforce GTX 1660.  Python version 3.8.16, torch 1.13.1.  I remember that yolov5 had this issue and it seemed to go away by ensuring the amp=False.
In YoloV8 i attempted to replicate this by modifying trainer.py on line 114 by commenting out 
"self.amp = self.device.type != 'cpu' 
and replacing with 
self.amp= False

This did not seem to work, but there is also a high chance i have not done this in the right spot.

**Comment by Florioo** [comment]
I also have the same issue

Reproduced with:

```
yolo task=detect mode=train data=coco128.yaml model=yolov8s.pt epochs=5 batch=4 workers=3 imgsz=640

Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
1/5      1.15G        nan        nan        nan         40        640:   9%|▉         | 3/32 [00:08<01:23,  2.89s/it]
```


- GPU: NVIDIA T1000
- CUDA: CUDA Version: 11.6
- Nvidia driver: 510.108.03
- ultralytics==8.0.48
- Python 3.10.9

**Comment by glenn-jocher** [comment]
In YOLOv5 we have an AMP check that catches many of these torch/CUDA issues and automatically disables AMP, @Laughing-q @AyushExel we need to port this over to v8, which I think should resolve most of these occurrences.

I can try to do that today.

**Comment by rusvagzur** [comment]
> In YOLOv5 we have an AMP check that catches many of these torch/CUDA issues and automatically disables AMP, @Laughing-q @AyushExel we need to port this over to v8, which I think should resolve most of these occurrences.
> 
> I can try to do that today.

@glenn-jocher Hi, are there updates regarding this?

**Comment by Kjellmd** [comment]
@glenn-jocher Any updates on this problem?

**Comment by glenn-jocher** [comment]
@Kjellmd yes, I've introduced an AMP check in 8.0.50, so if you `pip install -U ultralytics` then your new trainings should first check that your system is compatible with AMP training, and disable AMP if not.

If AMP is the source of the problem this may resolve most of these issues. Be aware though that disabling AMP will require more CUDA memory, though we have a CUDA-memory TAL update coming soon in 8.0.52 that should improve CUDA utilization for many training scenarios.

**Comment by mucozcan** [comment]
@glenn-jocher  Testing version 8.0.53 on GTX 1660 Ti with torch version 1.13.1+cu117. The problem is still occurring.
Tested code:
```python
from ultralytics import YOLO
# Load a model
model = YOLO("yolov8m-seg.yaml")  # build a new model from scratch
# Train the model
model.train(data="coco8-seg.yaml", epochs=100, imgsz=640)
```
Output:
```
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
optimizer: SGD(lr=0.01) with parameter groups 86 weight(decay=0.0), 97 weight(decay=0.0005), 96 bias
train: Scanning /home/muco/workspace/git-repos/autolo/datasets/coco8-seg/labels/train.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
val: Scanning /home/muco/workspace/git-repos/autolo/datasets/coco8-seg/labels/val.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
Plotting labels to runs/segment/train29/labels.jpg... 
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/segment/train29
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
      1/100      2.37G        nan        nan        nan        nan         16        640: 100%|██████████| 1/1 [00:02<00:00,  2.42s/it]
```

**Comment by Tommyisr** [comment]
I disabled cudnn in PyTorch and it solved the issue with nan values, but I'm not sure whether it'll affect perfomance of training process. 

   ` torch.backends.cudnn.enabled = False`

Windows 10
YOLOv8
Nvidia GTX 1660 Super
Conda env
Python3.9
cudatoolkit-11.3.1
pytorch-1.12

![image](https://user-images.githubusercontent.com/37695491/224848472-23e0f76c-b19f-439d-89b4-2f13b5abf1f0.png)

**Comment by glenn-jocher** [comment]
> @glenn-jocher Testing version 8.0.53 on GTX 1660 Ti with torch version 1.13.1+cu117. The problem is still occurring. Tested code:
> 
> ```python
> from ultralytics import YOLO
> # Load a model
> model = YOLO("yolov8m-seg.yaml")  # build a new model from scratch
> # Train the model
> model.train(data="coco8-seg.yaml", epochs=100, imgsz=640)
> ```
> 
> Output:
> 
> ```
> AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
> AMP: checks passed ✅
> optimizer: SGD(lr=0.01) with parameter groups 86 weight(decay=0.0), 97 weight(decay=0.0005), 96 bias
> train: Scanning /home/muco/workspace/git-repos/autolo/datasets/coco8-seg/labels/train.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
> val: Scanning /home/muco/workspace/git-repos/autolo/datasets/coco8-seg/labels/val.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
> Plotting labels to runs/segment/train29/labels.jpg... 
> Image sizes 640 train, 640 val
> Using 4 dataloader workers
> Logging results to runs/segment/train29
> Starting training for 100 epochs...
> 
>       Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
>       1/100      2.37G        nan        nan        nan        nan         16        640: 100%|██████████| 1/1 [00:02<00:00,  2.42s/it]
> ```

If the issue doesn't occur in COCO or COCO128 then it's likely you have problems in your dataset.

**Comment by mucozcan** [comment]
> > @glenn-jocher Testing version 8.0.53 on GTX 1660 Ti with torch version 1.13.1+cu117. The problem is still occurring. Tested code:
> > ```python
> > from ultralytics import YOLO
> > # Load a model
> > model = YOLO("yolov8m-seg.yaml")  # build a new model from scratch
> > # Train the model
> > model.train(data="coco8-seg.yaml", epochs=100, imgsz=640)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Output:
> > ```
> > AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
> > AMP: checks passed ✅
> > optimizer: SGD(lr=0.01) with parameter groups 86 weight(decay=0.0), 97 weight(decay=0.0005), 96 bias
> > train: Scanning /home/muco/workspace/git-repos/autolo/datasets/coco8-seg/labels/train.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
> > val: Scanning /home/muco/workspace/git-repos/autolo/datasets/coco8-seg/labels/val.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
> > Plotting labels to runs/segment/train29/labels.jpg... 
> > Image sizes 640 train, 640 val
> > Using 4 dataloader workers
> > Logging results to runs/segment/train29
> > Starting training for 100 epochs...
> > 
> >       Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
> >       1/100      2.37G        nan        nan        nan        nan         16        640: 100%|██████████| 1/1 [00:02<00:00,  2.42s/it]
> > ```
> 
> If the issue doesn't occur in COCO or COCO128 then it's likely you have problems in your dataset.

It occurs on coco8-seg.yaml config you provided in the repository.

**Comment by glenn-jocher** [comment]
COCO8-seg trains correctly in Colab:

<img width="1287" alt="Screenshot 2023-03-15 at 13 02 09" src="https://user-images.githubusercontent.com/26833433/225303387-d556a23a-7464-4b2c-a3d9-5b36821417d3.png">

I'd use one of our verified environments if you are having issues locally:

## Environments

YOLOv8 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/GCP-Quickstart)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/AWS-Quickstart)
- **Docker Image**. See [Docker Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

**Comment by naseemap47** [comment]
I also faced the same issue, when I train yolov8 model using
```
yolo task=detect mode=train data=coco128.yaml model=yolov8n.pt epochs=5 batch=4 imgsz=640
```
in my laptop with **NVIDIA GeForce GTX 1650 Ti**
But when I reduce **batch=2**, Its worked.

But in my desktop with **NVIDIA GeForce RTX 2080**, I didn't face any issue.

**Comment by glenn-jocher** [comment]
@naseemap47 thanks for reporting this issue. It seems like reducing the batch size has helped solve the problem for you on your laptop with NVIDIA GeForce GTX 1650 Ti. This could be due to the limited memory of your GPU, which is causing the training to fail when a larger batch size is used. 

However, on your desktop with NVIDIA GeForce RTX 2080, you did not face any issues. This could be because the RTX 2080 has more available memory and can handle larger batch sizes during training.

We recommend experimenting with different batch sizes to find the optimal value for your specific system. You can also try reducing the image size `imgsz` as an alternative to reducing the batch size, as smaller image sizes require less memory.

Hope this helps! Let us know if you have any additional questions or concerns.

**Comment by naseemap47** [comment]
@glenn-jocher thanks for your replay.
If we reduce `imgsz` < 640 or `imgsz` > 640 it will effect the performance of the model ?
Because I can't compromise on model performance.

**Comment by glenn-jocher** [comment]
@naseemap47 reducing the `imgsz` can have an impact on the performance of the YOLOv8 model. When the `imgsz` is reduced, the model may lose some accuracy in detecting smaller objects. The trade-off is that smaller `imgsz` can fit more images within the GPU's memory, allowing for a potentially larger batch size and faster training.

We recommend finding a balance between `imgsz`, batch size, and training time to achieve the best performance for your use case. You may want to experiment with different `imgsz` values and monitor the model's performance metrics closely to determine the optimal value that meets your needs.

Hope this helps! Let us know if you have any additional questions or concerns.

**Comment by naseemap47** [comment]
@glenn-jocher Thank you for your replay. :hugs:

**Comment by glenn-jocher** [comment]
@naseemap47 you're welcome! :blush: If you have any more questions or run into any issues, feel free to ask and we'll do our best to help you out. :smile:

**Comment by willyfh** [comment]
> I also faced the same issue, when I train yolov8 model using
> 
> ```
> yolo task=detect mode=train data=coco128.yaml model=yolov8n.pt epochs=5 batch=4 imgsz=640
> ```
> 
> in my laptop with **NVIDIA GeForce GTX 1650 Ti** But when I reduce **batch=2**, Its worked.
> 
> But in my desktop with **NVIDIA GeForce RTX 2080**, I didn't face any issue.

I confirmed this on my laptop with NVIDIA GeForce GTX 1650. reducing batch size or reducing image size or reducing the using smaller YOLO model can help to avoid the issues.

**Comment by glenn-jocher** [comment]
@willyfh thank you for sharing your experience. It seems that reducing the batch size or image size can help to avoid the issues you encountered when training the YOLOv8 model on your laptop with an NVIDIA GeForce GTX 1650 Ti. This is likely due to the limited memory on your GPU.

On your desktop with an NVIDIA GeForce RTX 2080, you did not encounter the same issues. This is likely because the RTX 2080 has more available memory and can handle larger batch sizes during training.

To mitigate these issues, you can experiment with different batch sizes, image sizes, or even try using a smaller YOLOv8 model variant. Finding the right balance for your specific GPU and training requirements is important.

If you have any further questions or concerns, please let us know.

**Comment by SeifMejri21** [comment]
Hello, i think i'm late to the party at this point!
But since i got the same error of having nan training metrics on a similar setup (nvidia 1650 Ti ), i wanted to share it anyways.
I'm tying to detect a small object so going under 640 in image size was not a possibility.
I found out that by just  defining amp= False in training command, i was able to train the model on my custom dataset on 640 image size a batch size of 8.

`import subprocess

epochs = 3
image_size = 640
device = '0'
amp =False
dataset_path = "/fooball-ball/data.yaml"
batch= 8

cmd = f"""yolo task=detect mode=train model=yolov8s.pt data={dataset_path} 
epochs={epochs} imgsz={image_size} device={device} plots=True  batch={batch} amp={amp}"""

subprocess.run(cmd)
`

**Comment by glenn-jocher** [comment]
@SeifMejri21 hello! Thanks for sharing your experience and workaround with us, it's never too late to contribute!

Indeed, setting amp (Automatic Mixed Precision) to False can help with the "NaN" error during training. The Automatic Mixed Precision (amp) training feature can speed up computation on modern GPUs, but it might cause numerical stability issues, resulting in NaN values, especially in environments with GPUs that have less memory, such as your NVIDIA GeForce 1650 Ti.

With that said, it's crucial to note that deactivating amp may slightly slow down the training process because it disables the mixed-precision training. However, it seems in your case the ability to increase the image size and batch size without getting NaN errors outweighs the potential decrease in training speed, which is great!

Again, thank you for sharing this valuable information with the community! It's possible your solution will come in handy for others experiencing a similar issue. Feel free to let us know about any other issues or discoveries you make in the future.

**Comment by BirenMer** [comment]
All my losses are nan so does this mean that my model is not learning ?

**Comment by glenn-jocher** [comment]
@BirenMer hey there! 😊 Yes, if all your losses are showing as `NAN`, it typically means that the model is encountering numerical stability issues during training, which prevents it from learning effectively. This can happen for a few reasons, such as too high a learning rate or insufficient data normalization.

A quick thing you might try is reducing the learning rate. Here's a snippet on how you could adjust it:

```python
model.train(data='your_dataset.yaml', epochs=100, lr0=0.001)  # Adjust lr0 to a lower value
```

Hope this helps! Let us know how it goes.

**Comment by BirenMer** [comment]
Thank you so much @glenn-jocher adjusted the lr0 and now it is working and showing all the losses.

**Comment by glenn-jocher** [comment]
That's fantastic to hear, @BirenMer! 😊 I'm glad adjusting the learning rate did the trick. If you have any more questions or need further assistance as you continue with your YOLOv8 journey, don't hesitate to reach out. Happy training!

**Comment by RajaAhsan97** [comment]
Encountered Nan values loss while training model using CPU, I have reduced batch size to 8, while image size is 64 and also set lr0=0.001. But while model training the message prompted "ignoring 'lr0=0.001' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...". Still the same issue Nan for losses

**Comment by RajaAhsan97** [comment]
Issue resolved while training the model on google colab with the same command as mentioned above. Previously tried training on my local agent, i think the issue caused by memory which cause losses to be NaN from second epoch

**Comment by RajaAhsan97** [comment]
@glenn-jocher thanks, the issue is resolved . Maybe reducing batch size to 4 in local machine resolves this...

**Comment by Petros626** [comment]
> [@lokeshfallen](https://github.com/lokeshfallen) Could you tell me which GPU device(ie. GTX1080) is using to training? I found sometimes is not a YOLO problem, it’s PyTorch Autocast problem, which is NaN in some device and some PyTorch version. Generally, it cloud fix it by changing the PyTorch or CUDA version, changing the GPU device(ie. A100), and modifying code to close the Autocast. Autocast is the training strategy which is mixed the FP16 and FP32, it enabled in YOLO by default in global.

isn't this via `amp=False` possible to deactivate?

**Comment by glenn-jocher** [comment]
Yes, you can deactivate automatic mixed precision (AMP) in YOLO by setting `amp=False` in your training command. This disables Autocast, which can help resolve NaN issues on certain devices or configurations. For more details, you can refer to the [Ultralytics AMP documentation](https://docs.ultralytics.com/reference/utils/torch_utils/#ultralyticsutilsautocast).

**Comment by glenn-jocher** [comment]
Setting amp=False disables mixed precision training so your model runs in full FP32 precision, which can improve numerical stability but may slow training and increase memory usage.
