### ISSUE TITLE
multi-dimensional imgsz not supported?

### ISSUE THREAD

**Issue by ajtao** [ultralytics/ultralytics#1152]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/engine/trainer.py#L211

### Bug

WARNING ⚠️ updating to 'imgsz=512'. 'train' and 'val' imgsz must be an integer, while 'predict' and 'export' imgsz may be a [h, w] list or an integer, i.e. 'yolo export imgsz=640,480' or 'yolo export imgsz=640'

### Minimal Reproducible Example

model.train(... imgsz=[512,256])

### Additional

I can see that max_dim is hardcoded to '1' in https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/engine/trainer.py#L211.

Does this codebase not support different w/h image dimensions?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ajtao** [comment]
Hmm it looks like the code, such as augment.py is hardcoded to assume images are square :(.

**Comment by glenn-jocher** [comment]
@ajtao YOLOv8 does automatic rectangular inference when appropriate, i.e. validation. imgsz=640 defines the long side and we handle the short side automatically.

**Comment by ajtao** [comment]
Thanks, so if my images are tall (256w x 512h), imgsz=512. If they're wide (512w x 256h), imgsz=512 too?

**Comment by ajtao** [comment]
Thanks for the help @glenn-jocher ! 

By the way, kudos on the vastly simpler framework with v8. I have been impressed with the training efficiency as well. Looks like you put a lot of work into it!
