### ISSUE TITLE
ONNX With OpenCV 4.6

### ISSUE THREAD

**Issue by tvbao1979** [ultralytics/ultralytics#1154]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I exported yolo model to ONNX format:

"from ultralytics import YOLO
model = YOLO("yolov8n.pt")  # load an official detection model
success = model.export(format="onnx",simplify=True, opset= 12, device = 'cpu')  # export the model to ONNX format "

When  use OpenCV 4.7, result is good.
but with openCV 4.6 i get error like this:
"OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\include\opencv2/dnn/shape_utils.hpp:171: error: (-215:Assertion failed) start <= (int)shape.size() && end <= (int)shape.size() && start <= end in function 'cv::dnn::dnn4_v20220524::total'" when model.forward()

How can i use Onnx with OpenCV4.6

**Comment by nikbobo** [comment]
Oh, I also have this question.

**Comment by glenn-jocher** [comment]
@tvbao1979 @nikbobo ONNX models export and run inference correctly with cv2 4.6.0.66, which is what Colab has installed by default.

Also you don't need to manually specify an opset, it's handled automatically, so unless you are an expert user and have a good reason for requiring opset 12 I'd leave it alone.

**Comment by nikbobo** [comment]
> @tvbao1979 @nikbobo ONNX models export and run inference correctly with cv2 4.6.0.66, which is what Colab has installed by default.
> 
> Also you don't need to manually specify an opset, it's handled automatically, so unless you are an expert user and have a good reason for requiring opset 12 I'd leave it alone.

I am using OpenCV C++ not Python, because of the limited support in the embedded device using RK3568 GPU (not NPU), it only can use the opset 12, and set it could make the device can using the YOLOv8 classification model, but using the detection model will get this error, it also can reproduce in my windows laptop.
If not custom opset, the classification and detection model also get this error.
I checked the exporter.py, and saw the warning about DNN inference with torch>=1.12 may require do_constant_folding=False in line 320, do we set it false? I will set it false to export and try again later on.

**Comment by binn77** [comment]
> ONNX

Hello, could you give your example of classification using ONNX. I have a low percentage of recognition when using ONNX.

**Comment by nikbobo** [comment]
> 

The example:

`
OpenCV.loadLocally();
Net classifyModel = Dnn.readNetFromONNX("best.onnx");
for (Path imagePath : getImages(Path.of(Objects.requireNonNull(DnnYoloV8.class.getResource("net")).toURI()).toAbsolutePath())) {
        Mat inputImage = Imgcodecs.imread(imagePath.toAbsolutePath().toString());
        Imgproc.resize(inputImage, inputImage, new Size(224, 224));
        Imgproc.cvtColor(inputImage, inputImage, Imgproc.COLOR_BGR2RGB);
        inputImage.convertTo(inputImage, CvType.CV_32FC3, 1.0 / 255.0);
        Mat input = Dnn.blobFromImage(inputImage, 1, new Size(224, 224));
        classifyModel.setInput(input);
        Mat output = classifyModel.forward();
        System.out.println(output);
}
`

**Comment by tvbao1979** [comment]
@nikbobo Oh, I also have this question.
Dis you solve this issue. i user window platform too

**Comment by ashray21** [comment]
@tvbao1979 @glenn-jocher 
My issue is also related with opencv verison.  I'm using opencv==4.6
My yolo8.onnx file is able to inference when I'm using backend as "cuda" but it gives nan value when I'm setting backend as "cpu".

I exported onnx model like this 

model.export(format="onnx",opset=12)

**Comment by pigfishgogogo** [comment]
bro，did you solve the problem? i have the same issue but without any idea to solve it.

**Comment by glenn-jocher** [comment]
@pigfishgogogo hello! If you're encountering issues with ONNX models on OpenCV, especially regarding discrepancies between CPU and GPU backends or errors specific to openCV 4.6, I suggest first ensuring that the ONNX export was performed successfully without any opset version constraints unless you have a specific requirement for that opset.

Also, while we don't typically handle device-specific issues within this repo, I recommend confirming if your device has any known compatibility issues with specific ONNX opsets or OpenCV versions. For NaN values on 'cpu' backend, make sure the models are operating with the correct preprocessing and that there aren't any per-operation discrepancies causing computational errors in OpenCV.

For those working on embedded devices and finding errors or a performance mismatch in OpenCV, you might want to verify with the manufacturer's resources or the device's community.

Lastly, it's always a good practice to check the error messages and warnings carefully, as they may guide you towards specific flags or settings adjustment like `do_constant_folding=False` which might solve your problem.

If none of these steps resolve your issue, seeking help from OpenCV forums or the repository issues where the community might have encountered similar device-specific scenarios could be beneficial. Keep in mind that device-specific support is often community-driven, and you might find workarounds or patches this way.
