### ISSUE TITLE
After exporting to onnx, it incorrectly defines the class when classifying.

### ISSUE THREAD

**Issue by binn77** [ultralytics/ultralytics#1163]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

After exporting to onnx, it incorrectly defines the class when classifying.
Tell me how to use the onnx model correctly.

`yolo export model=C:/temp/best.pt format=onnx  imgsz=128 device=0`

```
    image = cv2.cvtColor(orig_image, cv2.COLOR_BGR2RGB)
    image = cv2.resize(image, (128, 128))
    image_mean = np.array([127, 127, 127])
    image = (image - image_mean) / 128
    image = np.transpose(image, [2, 0, 1])
    image = np.expand_dims(image, axis=0)
    image = image.astype(np.float32)         

    input_name = model.get_inputs()[0].name
    confidences = model.run(None, {input_name: image})
```

**Comment by AyushExel** [comment]
See the ONNX python example here that uses opencv https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-OpenCV-ONNX-Python

**Comment by binn77** [comment]
> See the ONNX python example here that uses opencv https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-OpenCV-ONNX-Python

I tried exporting with the opset=12 parameter, the result is the same.

**Comment by pderrenger** [comment]
@binn77 it's great to hear that you've already tried exporting with the opset=12 parameter. 🙌 This indicates that the issue might not be related to the export process itself. Have you considered checking the class definitions within the ONNX model? This could be a potential area where the incorrect class definitions are originating.

**Comment by glenn-jocher** [comment]
@pderrenger, it sounds like the issue may lie in the post-processing of the ONNX model's outputs. Ensure that the class labels are correctly aligned with the model's output and that any necessary normalization or scaling is applied consistently with the training phase. If the problem persists, reviewing the pre-processing and inference steps for any discrepancies with the original model's requirements could be beneficial. 🕵️‍♂️
