### ISSUE TITLE
【BUG?】Angle error issue

### ISSUE THREAD

**Issue by Wangfeng2394** [ultralytics/ultralytics#11633]

**Comment by Wangfeng2394** [comment]
May I ask you a question？？

What is the angle range I should send into the trainer？
0~180？
-180~180？
0~3.14？

Or else？

**Comment by glenn-jocher** [comment]
Hello! 😊

For angle input into the YOLOv8 trainer, you should use the range of 0 to 360 degrees. This range ensures that the trainer processes the orientation information uniformly across all possible angles.

If you have any more questions or need further assistance, feel free to ask. Happy training!

**Comment by Wangfeng2394** [comment]
> Hello! 😊
> 
> For angle input into the YOLOv8 trainer, you should use the range of 0 to 360 degrees. This range ensures that the trainer processes the orientation information uniformly across all possible angles.
> 
> If you have any more questions or need further assistance, feel free to ask. Happy training!

thanks ,I will try as your guidance

**Comment by glenn-jocher** [comment]
You're welcome! If you encounter any further issues or have more questions, just let us know. Happy training! 😊
