### ISSUE TITLE
How can i detect a subclass only when its inside another class!?

### ISSUE THREAD

**Issue by Mobin-khorushi** [ultralytics/ultralytics#1164]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi i have some simple question i used to search in google but didn’t find any answers 

Think of case i have two objects as square and triangle my model detects them perfectly but i want my model to detect the triangle only if it’s inside the detected square so only one square should not be detected as well as one triangle but if we detect a square and the triangle inside it is detected too and that case the object should be detected as one square and triangle inside ! Is it possible with training techniques I don’t know!? Any suggestions!?

I hope i could explain my problem perfectly

**Comment by yash-khurana** [comment]
I think you could achieve this by training the model to detect both and simply placing a condition (IoU of the square and triangle greater than threshold) from the outputs of the network. Hope that helps.

**Comment by pderrenger** [comment]
@yash-khurana absolutely, what you're looking for is a form of nested object detection, where the detection of one object influences the detection of another. Although YOLOv8 doesn't directly support this feature, you can indeed achieve it by post-processing the detection results. One approach is to use the output bounding boxes' coordinates and calculate the Intersection over Union (IoU) between the detected square and triangle. By setting a threshold for the IoU, you can filter out the cases where the triangle is not inside the square. This kind of custom post-processing allows you to enforce the relationship between the objects, achieving the behavior you described. Hope this helps! 👍

**Comment by mukunthan007** [comment]
> @yash-khurana absolutely, what you're looking for is a form of nested object detection, where the detection of one object influences the detection of another. Although YOLOv8 doesn't directly support this feature, you can indeed achieve it by post-processing the detection results. One approach is to use the output bounding boxes' coordinates and calculate the Intersection over Union (IoU) between the detected square and triangle. By setting a threshold for the IoU, you can filter out the cases where the triangle is not inside the square. This kind of custom post-processing allows you to enforce the relationship between the objects, achieving the behavior you described. Hope this helps! 👍


@pderrenger I am training a similar type of model but with different object. By training a model with nested object annotated datasets, will it reduce the accuracy of the predictions? (I am not asking about any post processing methods).
