### ISSUE TITLE
video object detection

### ISSUE THREAD

**Issue by wyfshr** [ultralytics/ultralytics#11665]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

When using YOLOv8 for video object detection, how to use the time context information of the video, is it necessary to change the input tensor, change (batch-size, channels, height, weight) to (batch-size, channels, time, height, weight), so where do you need to change in the code?

### Use case

The temporal context information of the video is used to enhance the feature information contained in the current frame

### Additional

no

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wyfshr hello,

Thanks for reaching out with your query about using time context information in video object detection with YOLOv8.

Currently, YOLOv8 does not natively support the incorporation of time or sequence data (like `(batch-size, channels, time, height, width)`) directly into its models. The standard input format is `(batch-size, channels, height, width)` for individual image frames or video frames processed independently.

To include time context, you might consider approaches external to the YOLOv8 framework such as feature engineering or using sequence models (like LSTM or GRU) on top of the YOLO outputs to incorporate temporal dynamics. These adjustments would be in the post-processing stage after running detections with YOLOv8.

If you're willing to contribute, enhancing YOLOv8 to natively handle video sequences might involve significant modifications to how data is loaded and processed. If you're seriously considering this, I'd recommend discussing it further in the GitHub discussions to outline a robust plan.

We appreciate your willingness to contribute and look forward to any further questions or proposals you might have!

**Comment by Bhavay-2001** [comment]
Hi @glenn-jocher, can I work on this issue? I would be happy to discuss it by opening a draft PR and then discussing possible suggestions.
Thanks

**Comment by Bhavay-2001** [comment]
Hi @glenn-jocher, can I work on this one? 
Thanks

**Comment by glenn-jocher** [comment]
Hi @Bhavay-2001,

Absolutely, we'd be thrilled to have your contribution on this! 🚀 Please feel free to open a draft PR, and we can start discussing the implementation details there. Looking forward to seeing your ideas in action!

Thanks for stepping up to help enhance YOLOv8!

**Comment by Bhavay-2001** [comment]
Hi @glenn-jocher, I have already opened a discussion session on the same. Would love to discuss ideas there. 

For now, I don't have any ideas myself. I have worked with video data on top of a Backbone model which can be used to extract features from the video data but I don't know if it will fit this use case. We can discuss this further on discussions.

Thanks

**Comment by glenn-jocher** [comment]
Hi @Bhavay-2001,

Great to hear that you've initiated a discussion! 🌟 I'll join in there to explore how your experience with Backbone models could potentially be adapted for YOLOv8. Let's brainstorm and see what innovative solutions we can come up with together.

Looking forward to our collaboration!

Thanks!

**Comment by Bhavay-2001** [comment]
Hi @glenn-jocher, any good starting points on how can I integrate it? Soo we basically want to add the outputs of our CNN layers to the RNN layers to include the temporal information. Any possible code or paper which can help me getting started?

Thanks

**Comment by glenn-jocher** [comment]
Hi @Bhavay-2001,

Great question! Integrating CNN outputs into RNN layers for temporal analysis is a common approach in video processing. A good starting point would be to look into the architecture of models like ConvLSTM or ConvGRU, which are designed specifically for this purpose.

For code, you might check out implementations of these models in frameworks like PyTorch or TensorFlow. Here’s a simple example using PyTorch:

```python
import torch
import torch.nn as nn

class ConvLSTMCell(nn.Module):
    def __init__(self, input_dim, hidden_dim, kernel_size, bias):
        super(ConvLSTMCell, self).__init__()
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        self.kernel_size = kernel_size
        self.padding = kernel_size // 2
        self.bias = bias
        self.conv = nn.Conv2d(in_channels=self.input_dim + self.hidden_dim,
                              out_channels=4 * self.hidden_dim,
                              kernel_size=self.kernel_size,
                              padding=self.padding,
                              bias=self.bias)

    def forward(self, input_tensor, cur_state):
        h_cur, c_cur = cur_state
        combined = torch.cat([input_tensor, h_cur], dim=1)
        combined_conv = self.conv(combined)
        cc_i, cc_f, cc_o, cc_g = torch.split(combined_conv, self.hidden_dim, dim=1)
        i = torch.sigmoid(cc_i)
        f = torch.sigmoid(cc_f)
        o = torch.sigmoid(cc_o)
        g = torch.tanh(cc_g)
        c_next = f * c_cur + i * g
        h_next = o * torch.tanh(c_next)
        return h_next, c_next

    def init_hidden(self, batch_size, image_size):
        height, width = image_size
        return (torch.zeros(batch_size, self.hidden_dim, height, width, device=self.conv.weight.device),
                torch.zeros(batch_size, self.hidden_dim, height, width, device=self.conv.weight.device))
```

This is a basic ConvLSTM cell you can build upon. For papers, you might want to read "Convolutional LSTM Network: A Machine Learning Approach for Precipitation Nowcasting" by Xingjian Shi et al., which is a seminal work in this area.

Hope this helps, and looking forward to seeing what you come up with!

Thanks!

**Comment by Linengyao** [comment]
@Bhavay-2001 hi, i am doing the same search about how to use yolov8 to train video(time sequence) object detection,do u have any process now?(any idea or code?)
