### ISSUE TITLE
Is yolov8 good for continual learning!?

### ISSUE THREAD

**Issue by Mobin-khorushi** [ultralytics/ultralytics#1166]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have simple question can i do continual learning with yolov8!?
Think a case i have model trained on custom dataset containing 10,000 images and 100 validation images including many many labels and 18 classes 

my problem is i want to retrain my model with new images only so i want to train my old model with 1000 new images and 100 validations
And in other hand i want to retain my model for one class which accuracy is low so i want a new retrain on one class of my 18 classes 

Can i use the old best pt file to do retrain with new images or i need to include all old images which already trained !?

**Comment by AyushExel** [comment]
Right now these models are not intended for continual learning. If you do re-train a trained model, it'll be just like training a pre-trained model and if the domain of data is completely different it'll be forgotten eventually. 
I'm not an expert in continual learning but we're open to PR and suggestions for supporting continual learning.
