### ISSUE TITLE
Training with uint16

### ISSUE THREAD

**Issue by christianayala10** [ultralytics/ultralytics#11675]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am training YOLOv8 with satellite images, which are usually in the uint16 data format and comprise several bands. However, **YOLO only supports training with images of 3 channels in the uint8 format**. This limitation hinders our model from fully utilizing the information contained in these images.

**I have successfully modified the source code to allow input of images with an arbitrary number of channels. However, I am struggling to switch from uint8 to uint16.** I have looked into previous issues, and while some ask about training with other data types, none of them provide a solution.

I have managed to modify the source code to read uint16 TIFF files. However, **I have encountered an issue where the ultralytics library clips my data to the range [0, 255]**. **Can anyone provide guidance on which specific files I should modify to address this?**

**Comment by glenn-jocher** [comment]
Hi there! 🚀 It's great to hear about your efforts to adapt YOLOv8 for satellite imagery with more channels and uint16 data types.

Regarding the issue with the data being clipped to [0, 255], you would likely need to adjust the normalization and possibly the image loading functions within the YOLOv8 codebase. Specifically, check the part of your modified code where images are loaded into the model. Make sure the datatype is preserved and not forcefully scaled or converted to uint8.

A common place to look would be in the image pre-processing step, especially where you handle or adjust incoming image arrays before they enter the model's network layers. You might also need to check how tensors are formed from image data and see if there's an explicit conversion to uint8 that mandates the [0, 255] range.

Keep an eye on ensuring your modifications align with how the network expects data, not just in format but in range and scaling too. If you still face issues, consider sharing a bit of the code snippet you have modified for a more detailed look!

Hope this helps, and looking forward to seeing your success with it!
