### ISSUE TITLE
yoloworld offline use , set_classes adds specified weight path parameters

### ISSUE THREAD

**Issue by reynaldliu** [ultralytics/ultralytics#11681]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

The program needs to be used offline when there is no network. It is expected that set_classes can specify the path of the clip model so that the clip weight file can be downloaded at the specified location in advance when offline. The current default location is ~/.cache/clip. It is expected that this can be changed. Location

```

class WorldModel(DetectionModel):
    """YOLOv8 World Model."""

    def __init__(self, cfg="yolov8s-world.yaml", ch=3, nc=None, verbose=True):
        """Initialize YOLOv8 world model with given config and parameters."""
        self.txt_feats = torch.randn(1, nc or 80, 512)  # placeholder
        super().__init__(cfg=cfg, ch=ch, nc=nc, verbose=verbose)

    def set_classes(self, text):
        """Perform a forward pass with optional profiling, visualization, and embedding extraction."""
        try:
            import clip
        except ImportError:
            check_requirements("git+https://github.com/openai/CLIP.git")
            import clip

        model, _ = clip.load("ViT-B/32")
        device = next(model.parameters()).device
        text_token = clip.tokenize(text).to(device)
 
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@reynaldliu hello! Thanks for reaching out with your request about modifying the default path for loading the clip model weights for offline usage.

You can achieve this by manually specifying the path when loading the model using `clip.load()`. You can pass an additional `jit` parameter pointing to your pre-downloaded weights file. Here's a modified snippet of your code:

```python
import clip

def set_classes(self, text, clip_model_path):
    """Load custom CLIP model from a specific path."""
    model, _ = clip.load("ViT-B/32", jit=clip_model_path)
    device = next(model.parameters()).device
    text_token = clip.tokenize(text).to(device)
```

When calling `set_classes`, provide the local path to your pre-downloaded CLIP model file as the `clip_model_path` argument:

```python
model.set_classes("Some classes text", clip_model_path="/local/path/to/your/clip/model.pt")
```

This should allow your application to run offline by leveraging the CLIP weights stored at a specified location. If you have any further questions or need additional assistance, please don't hesitate to ask! 🌐🚀

**Comment by yerol89** [comment]
Hi All,

Now I face the same issue. I try to get a zero shot inference and finetune yoloworld with my own data in an offline environment.

But before all these, I installed necessary libs like clip etc. with internet connection. Then we disabled the internet connection in the working environment and tried to finetune and inference without internet as I stated.

But when I try to do these operations I got this error for both of the cases:

`URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>`

Here are my imports:

```
import numpy as np
import pandas as pd
from PIL import Image
import os
from ultralytics import YOLOWorld,SAM,YOLO
from ultralytics.data.annotator import auto_annotate
from transformers import CLIPProcessor, CLIPModel
import clip
```

My Questions are:

1.  You stated customizing the set_classes() function by giving a path would solve the problem. The problem is I couldn't find the set_classes function in the source code. Maybe it is due to different version. Can you please explain how to figure this problem out in my current ultralytics version? Here is the code I use:

```
# Initialize a YOLO-World model
model = YOLO("yolov8x-world.pt")  # or choose yolov8m/l-world.pt

# Define custom classes
model.set_classes(["Crack"])

# Execute prediction for specified categories on an image
results = model.predict(r'my_image.jpg')

# Show results
results[0].show()
```

2. I also face with the same error message when I try to finetune the model with my custom dataset. Here is the code for finetuning:

```
# Load a pretrained YOLOv8s-worldv2 model
model = YOLOWorld("my_dir\yolov8x-world.pt") # 

# Train the model on the COCO8 dataset for 200 epochs
results = model.train(data="my_yaml.yaml", epochs=200, imgsz=640)
```

Thanks for your help in advance...

**Comment by glenn-jocher** [comment]
@yerol89 thank you for your detailed inquiry. Here's how you can address the issues:

1. **Customizing `set_classes` for Offline Use:**
   The `set_classes` function is supported in YOLO-World models for specifying detection classes dynamically. If you're encountering issues finding the function in your version of Ultralytics, ensure you have the latest version installed. Update using:
   ```
   pip install -U ultralytics
   ```
   If you're working offline, you'll need to pre-download the required CLIP weights and ensure they are accessible locally. Modify the `set_classes` function in your script to specify the weights' path manually. This can be done by storing the weights in a specific directory and ensuring the model points to that local path.

2. **Fine-Tuning in an Offline Environment:**
   The `URLError` indicates that the model, during fine-tuning, is attempting to download resources (e.g., CLIP weights or datasets). To resolve this:
   - Pre-download all required resources (e.g., model weights, datasets) in an environment with internet access.
   - Ensure the paths to these resources are correctly specified in your script and `data` YAML file.
   - For fine-tuning, ensure the `clip` library and weights are properly cached locally. You can cache the CLIP weights manually by running the necessary commands in an online environment and then transferring the cached files to your offline environment.

   Specifically for YOLO-World, verify that the `clip` model is properly initialized and cached locally to avoid internet dependency during fine-tuning.

3. **Error Resolution:**
   To address potential version mismatches or missing functionality, utilize the latest Ultralytics YOLO repository codebase. If the issue persists, consider customizing your script to manually handle any required resource loading.

Let us know if further clarification is needed or if the issue persists. You can also review the YOLO-World documentation for more on setting custom classes: [YOLO-World Docs](https://docs.ultralytics.com/models/yolo-world/).

**Comment by yerol89** [comment]
Thanks for your respond @glenn-jocher...

I believe I use one of the latest versions of ultralytics.

The only set_classes() func. I managed to find is under the directory of  ulyralytics/models/yolo/model.py and it is very different from what @reynaldliu shared at the beginning of this post.  I believe it has been updated since the last post. 

Here what I have under this directory:

```
    def set_classes(self, classes):
        """
        Set classes.

        Args:
            classes (List(str)): A list of categories i.e. ["person"].
        """
        self.model.set_classes(classes)
        # Remove background if it's given
        background = " "
        if background in classes:
            classes.remove(background)
        self.model.names = classes

        # Reset method class names
        # self.predictor = None  # reset predictor otherwise old names remain
        if self.predictor:
            self.predictor.model.names = classes
```

There is no parameter to customize  for ViT-B/32 weight path.

Only func. I managed to find for customizing ViT-B/32 weight path would be on_pretrain_routine_end() which is under ulyralytics/models/yolo/world/train.py directory.

```
def on_pretrain_routine_end(trainer):
    """Callback."""
    if RANK in {-1, 0}:
        # NOTE: for evaluation
        names = [name.split("/")[0] for name in list(trainer.test_loader.dataset.data["names"].values())]
        de_parallel(trainer.ema.ema).set_classes(names, cache_clip_model=False)
    device = next(trainer.model.parameters()).device
    trainer.text_model, _ = trainer.clip.load("ViT-B/32", device=device)
    for p in trainer.text_model.parameters():
        p.requires_grad_(False)
```

Is it enough to change the trainer.clip.load("ViT-B/32", device=device) part with a local directory? If yes, should I still use **jit**
parameter for new path? Or should I do something else? 

Thanks for your help in advance...

**Comment by glenn-jocher** [comment]
@yerol89 thank you for your detailed follow-up. You are correct that the `set_classes()` function you found in `ultralytics/models/yolo/model.py` and the `on_pretrain_routine_end` function in `ultralytics/models/yolo/world/train.py` are relevant to your use case. To customize the `ViT-B/32` weight path, modifying the `trainer.clip.load("ViT-B/32", device=device)` in `on_pretrain_routine_end()` to point to your local directory is indeed the correct approach.

Here’s how you can proceed:

1. Replace the `trainer.clip.load("ViT-B/32", device=device)` line with:
   ```python
   trainer.text_model, _ = trainer.clip.load("path/to/local/ViT-B-32.pt", device=device)
   ```

2. There’s no need to use the `jit` parameter unless your local model file specifically requires it.

Make sure your local file contains the correct `ViT-B/32` weights. This change should allow you to use the model in an offline environment without requiring internet access. Let us know if you encounter further issues!

**Comment by yerol89** [comment]
Hi @glenn-jocher ,

First of all, I would like to thank you for your time.

I have managed to figure this problem out using the cache file as you advised. Most probably many people have `.cache` folder under the directory of `C/Users/YourUserName`.  It is enough to put the ViT-B/32 weights file under a folder named clip. So the final directory for the weights file is `C:\Users\YourUserName\.cache\clip\ViT-B/32.pt`. 

I did not changed any source code in my case. As a result, YOLO WORLD fine tuning works fine now.

Thanks.

**Comment by glenn-jocher** [comment]
You're welcome! I'm glad to hear that using the `.cache` directory resolved your issue and that fine-tuning YOLO-World is now working smoothly. If you have any further questions or run into any other challenges, don't hesitate to reach out. Great work!

**Comment by couriouse** [comment]
In `Lib\site-packages\clip\clip.py` find this line:
`model_path = _download(_MODELS[name], download_root or os.path.expanduser("~/.cache/clip"))`
and change `os.path.expanduser("~/.cache/clip")` with any path you want.

**Comment by glenn-jocher** [comment]
@couriouse thank you for sharing this solution! 🙌 For those seeking to modify CLIP's cache path without altering source files, you can also set the `CLIP_CACHE_DIR` environment variable to your preferred directory. This approach maintains compatibility with future updates. For YOLO-World usage details, see our [YOLO-World documentation](https://docs.ultralytics.com/models/yolo-world/).
