### ISSUE TITLE
Yolov8 not working in example ultralytics/examples/YOLOv8-CPP-Inference

### ISSUE THREAD

**Issue by mohkan1** [ultralytics/ultralytics#11688]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

The project structure of ultralytics/examples/YOLOv8-CPP-Inference

![image](https://github.com/ultralytics/ultralytics/assets/43953894/a34254cb-f58a-4327-ae2b-9aca8182962d)

The code in the example ultralytics/examples/YOLOv8-CPP-Inference/main.cpp

```c

#include <iostream>
#include <vector>
#include <getopt.h>

#include <opencv2/opencv.hpp>

#include "inference.h"

using namespace std;
using namespace cv;

int main(int argc, char ** argv)
{
    std::string projectBasePath =
      "/home/bober/Desktop/douchebag/ultralytics/examples/YOLOv8-CPP-Inference/";                             // Set your ultralytics base path

    bool runOnGPU = true;

    //
    // Pass in either:
    //
    // "yolov8s.onnx" or "yolov5s.onnx"
    //
    // To run Inference with yolov8/yolov5 (ONNX)
    //

    // Note that in this example the classes are hard-coded and 'classes.txt' is a place holder.
    Inference inf(projectBasePath + "yolov5s.onnx", cv::Size(640, 480),
      projectBasePath + "classes.txt",
      runOnGPU);

    std::vector<std::string> imageNames;
    imageNames.push_back(projectBasePath + "bus.jpg");
    imageNames.push_back(projectBasePath + "zidane.jpg");

    for (int i = 0; i < imageNames.size(); ++i) {
        cv::Mat frame = cv::imread(imageNames[i]);

        // Inference starts here...
        std::vector<Detection> output = inf.runInference(frame);

        int detections = output.size();
        std::cout << "Number of detections:" << detections << std::endl;

        for (int i = 0; i < detections; ++i) {
            Detection detection = output[i];

            cv::Rect box = detection.box;
            cv::Scalar color = detection.color;

            // Detection box
            cv::rectangle(frame, box, color, 2);

            // Detection box text
            std::string classString = detection.className + ' ' + std::to_string(
                detection.confidence).substr(0, 4);
            cv::Size textSize = cv::getTextSize(classString, cv::FONT_HERSHEY_DUPLEX, 1, 2, 0);
            cv::Rect textBox(box.x, box.y - 40, textSize.width + 10, textSize.height + 20);

            cv::rectangle(frame, textBox, color, cv::FILLED);
            cv::putText(
                frame, classString, cv::Point(
                    box.x + 5,
                    box.y - 10), cv::FONT_HERSHEY_DUPLEX, 1, cv::Scalar(
                    0, 0, 0), 2, 0);
        }
        // Inference ends here...

        // This is only for preview purposes
        float scale = 0.8;
        cv::resize(frame, frame, cv::Size(frame.cols * scale, frame.rows * scale));
        cv::imshow("Inference", frame);

        cv::waitKey(-1);
    }
}

```

When using yolov5, it yeilds the following results:

![image](https://github.com/ultralytics/ultralytics/assets/43953894/3775c166-30fe-423e-9213-9b804339baff)

But when using the yolov8, it yields the following:

![image](https://github.com/ultralytics/ultralytics/assets/43953894/2d7bf10b-f6a0-42ca-a0db-402d756ad19d)

Any idea why the model yolov8 not working here ?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mohkan1 hey there! Thanks for providing detailed information about the issue you're encountering with YOLOv8 in the YOLOv8-CPP-Inference example.

From your description, it looks like when switching models from YOLOv5 to YOLOv8, you encounter distinct results or possibly an error. A common cause of such problems can be related to differences in model inputs and outputs structure, or ONNX model conversion specificities.

Let's start troubleshooting with the following:

1. **Model Input/Output Check**: Ensure the model inputs and outputs are correctly configured for YOLOv8. Differences in input dimensions or preprocessing could cause issues.

2. **ONNX Model Verification**: Double-check that the YOLOv8 ONNX model was correctly converted and isn't corrupted. Re-export it if necessary.

3. **Code Adjustments**: Make sure all model-specific parameters (e.g., input size, class names, anchors etc.) align with YOLOv8's specifications.

4. **Dependencies**: Confirm that all dependencies particularly OpenCV and ONNX are up to date, as outdated versions might lead to unexpected behaviors.

If these steps don't resolve the issue, please provide any error messages or odd behaviors you notice when you switch to YOLOv8. This will help further narrow down the problem! 🛠️

**Comment by mohkan1** [comment]
@glenn-jocher Thanks for your suggestions, I have solved the issue. It was wrong model input output.

But now I got a new issue and wondering if you have any idea about why this is happening and how one can solve it ?

I have sat the variable runOnGPU to true but it will always switches to CPU.
![image](https://github.com/ultralytics/ultralytics/assets/43953894/a3ae133e-ef4a-426a-8fbe-aa3da3ec2a38)

**Comment by glenn-jocher** [comment]
Hey @mohkan1, glad to hear you resolved the model input/output issue! 🎉 Regarding your new problem with the `runOnGPU` variable, it sounds like the GPU isn't being recognized or utilized properly.

Here are a couple of quick checks and fixes you might consider:
- **CUDA Availability**: Ensure CUDA is properly installed and recognized by running `torch.cuda.is_available()` in your Python environment. This will confirm if PyTorch can access your GPU.
- **Device Specification**: Directly specify the device when setting up your model or during inference. For example:
  ```python
  device = 'cuda' if torch.cuda.is_available() else 'cpu'
  model.to(device)
  ```
- **Environment Check**: Make sure that your environment has the necessary GPU drivers and CUDA compatible PyTorch installation.

If these steps don't help, providing the specific error messages or behavior when attempting to use the GPU could give more clues on what might be going wrong. Keep us posted!
