### ISSUE TITLE
Different val results when save_hybrid=True

### ISSUE THREAD

**Issue by Alyetama** [ultralytics/ultralytics#11698]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val

### Bug

The results of model.val() is different based on whether `save_hybrid` is True or False. Please see `Minimal Reproducible Example` for details.

### Environment

```
>>> ultralytics.checks()
Found existing installation: wandb 0.16.6
Uninstalling wandb-0.16.6:
  Successfully uninstalled wandb-0.16.6
Ultralytics YOLOv8.2.10 🚀 Python-3.11.9 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 4090, 24195MiB)
Setup complete ✅ (32 CPUs, 62.5 GB RAM, 395.4/960.2 GB disk)
```

### Minimal Reproducible Example

```
In [1]: from ultralytics import YOLO
In [2]: model = YOLO('birds/birds-yolov9ev32/weights/best.pt')
```

The val results I get when `save_hybrid=True`:

```
In [3]: metrics = model.val(save_hybrid=True)
Ultralytics YOLOv8.2.1 🚀 Python-3.10.13 torch-2.2.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4090, 24195MiB)
YOLOv9e summary (fused): 687 layers, 57385652 parameters, 0 gradients, 189.2 GFLOPs
val: Scanning /media/biodiv/crucial/birds/project-6-at-2024-05-05-11-25-u9GOGinr/labels/val.cache... 1682 images, 71 backgrounds, 0 corrupt: 100%|██
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 106/106 [00:09<00:00, 10.90it/s]
                   all       1682       2060          1          1      0.995      0.995
American Goldfinch (Spinus tristis)       1682          2          1          1      0.995      0.995
Brown-headed Cowbird (Molothrus ater)       1682         11          1          1      0.995      0.995
Carolina Chickadee (Poecile carolinensis)       1682        445          1          1      0.995      0.995
Chipping Sparrow (Spizella passerina)       1682        546          1          1      0.995      0.995
Downy Woodpecker (Dryobates pubescens)       1682         97          1          1      0.995      0.995
House Finch (Haemorhous mexicanus)       1682        362          1          1      0.995      0.995
Northern Cardinal (Cardinalis cardinalis)       1682         58          1          1      0.995      0.995
Red-bellied Woodpecker (Melanerpes carolinus)       1682         12          1          1      0.995      0.995
Song Sparrow (Melospiza melodia)       1682          4          1          1      0.995      0.995
Squirrels (Eutamias sibiricus)       1682        173          1          1      0.995      0.995
Tufted Titmouse (Baeolophus bicolor)       1682        325          1          1      0.995      0.995
White-throated Sparrow (Zonotrichia albicollis)       1682         25          1          1      0.995      0.995
Speed: 0.1ms preprocess, 4.7ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /home/biodiv/crucial/birds/detect/val30
```

Using the exact same model object, no changes whatsoever other than setting `save_hybrid` to False. I get these results (which appears to be realistic):

```
In [4]: metrics = model.val(save_hybrid=False)
Ultralytics YOLOv8.2.1 🚀 Python-3.10.13 torch-2.2.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4090, 24195MiB)
val: Scanning /media/biodiv/crucial/birds/project-6-at-2024-05-05-11-25-u9GOGinr/labels/val.cache... 1682 images, 71 backgrounds, 0 corrupt: 100%|██
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 106/106 [00:09<00:00, 11.20it/s]
                   all       1682       2060      0.929       0.95      0.962      0.825
American Goldfinch (Spinus tristis)       1682          2          1          1      0.995      0.895
Brown-headed Cowbird (Molothrus ater)       1682         11      0.912      0.939       0.98      0.741
Carolina Chickadee (Poecile carolinensis)       1682        445      0.987      0.995       0.99      0.884
Chipping Sparrow (Spizella passerina)       1682        546      0.974      0.967      0.986       0.86
Downy Woodpecker (Dryobates pubescens)       1682         97          1          1      0.995      0.895
House Finch (Haemorhous mexicanus)       1682        362      0.959      0.967      0.978      0.881
Northern Cardinal (Cardinalis cardinalis)       1682         58      0.844      0.897       0.91      0.773
Red-bellied Woodpecker (Melanerpes carolinus)       1682         12          1      0.947      0.995      0.884
Song Sparrow (Melospiza melodia)       1682          4      0.779          1      0.945      0.799
Squirrels (Eutamias sibiricus)       1682        173      0.775      0.815      0.806      0.554
Tufted Titmouse (Baeolophus bicolor)       1682        325      0.973      0.991      0.992      0.884
White-throated Sparrow (Zonotrichia albicollis)       1682         25      0.943       0.88      0.966      0.851
Speed: 0.1ms preprocess, 4.7ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /home/biodiv/crucial/birds/detect/val31
```

### Additional

The training command I ran before running val:
```
yolo task=detect mode=train model=yolov9e.pt data=project-6-at-2024-05-05-11-25-u9GOGinr/data.yaml epochs=1000 patience=100 batch=-1 imgsz=640 verbose=True val=True save_period=-1 save_json=True save_hybrid=True save_conf=True save_txt=True plots=True optimizer=auto project=birds name=birds-yolov9ev3 augment=False cache=memory cls=1.0
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello, and thank you for the detailed report!

The difference in validation results when using `save_hybrid=True` versus `False` is certainly intriguing. The `save_hybrid=True` setting combines ground truth and predictions into a single label file for easier comparison and visualization, which should not alter the model's val performance metrics.

However, this anomaly might warrant a more in-depth investigation into how the merging of predicted labels and actual labels might be influencing the validation metrics calculation or visualization in some unforeseen way.

If it's not too much trouble, could you please check if there are any discrepancies in the processed labels or any unusual behaviors during validation when `save_hybrid` is toggled? Additionally, verifying that all other environmental variables and configurations remain constant between runs would be helpful.

For the time being, here is a simple snippet where you might add some logging to observe the changes directly:

```python
# Simple diagnostics to compare label handling between hybrid modes.
import logging

logging.basicConfig(level=logging.INFO)

def validate_model(save_hybrid):
    model = YOLO('path/to/best.pt')
    metrics = model.val(save_hybrid=save_hybrid)
    logging.info(f"Validation with save_hybrid={save_hybrid}: {metrics}")

validate_model(True)
validate_model(False)
```

This setup can help to quickly examine if the data handling during validation is subtly altered by `save_hybrid`.

**Next Steps:**

I recommend creating an issue in our repository with your findings from the revised logging. Any detailed logs or behavior discrepancies will be useful for diagnosing the issue further.

Thank you very much for your contribution towards improving YOLOv8! 🚀

**Comment by Alyetama** [comment]
@glenn-jocher Hello, thank you for your prompt response. I followed your instructions and ran the code again. Seems like the results remained the same.

```

In [1]: import logging

In [2]: from ultralytics import YOLO

In [3]: def validate_model(save_hybrid):
   ...:     model = YOLO('birds/birds-yolov9ev32/weights/best.pt')
   ...:     metrics = model.val(save_hybrid=save_hybrid)
   ...:     logging.info(f"Validation with save_hybrid={save_hybrid}: {metrics}")
   ...:

In [4]: validate_model(True)
   ...: validate_model(False)
Ultralytics YOLOv8.2.10 🚀 Python-3.11.9 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 4090, 24195MiB)

YOLOv9e summary (fused): 687 layers, 57385652 parameters, 0 gradients, 189.2 GFLOPs
val: Scanning /media/biodiv/crucial/birds/project-6-at-2024-05-05-11-25-u9GOGinr/labels/val.cache... 1682 images, 71 backgrounds, 0 corrupt: 100%|████████
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):  99%|█████████▉| 105/106 [00:55<00:00,  2.75it/s]/home/biodiv/mambaforge/envs/yolov8v2/lib/python3.11/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 106/106 [00:56<00:00,  1.89it/s]
                   all       1682       2060          1          1      0.995      0.995
American Goldfinch (Spinus tristis)       1682          2          1          1      0.995      0.995
Brown-headed Cowbird (Molothrus ater)       1682         11          1          1      0.995      0.995
Carolina Chickadee (Poecile carolinensis)       1682        445          1          1      0.995      0.995
Chipping Sparrow (Spizella passerina)       1682        546          1          1      0.995      0.995
Downy Woodpecker (Dryobates pubescens)       1682         97          1          1      0.995      0.995
House Finch (Haemorhous mexicanus)       1682        362          1          1      0.995      0.995
Northern Cardinal (Cardinalis cardinalis)       1682         58          1          1      0.995      0.995
Red-bellied Woodpecker (Melanerpes carolinus)       1682         12          1          1      0.995      0.995
Song Sparrow (Melospiza melodia)       1682          4          1          1      0.995      0.995
Squirrels (Eutamias sibiricus)       1682        173          1          1      0.995      0.995
Tufted Titmouse (Baeolophus bicolor)       1682        325          1          1      0.995      0.995
White-throated Sparrow (Zonotrichia albicollis)       1682         25          1          1      0.995      0.995
Speed: 1.9ms preprocess, 9.6ms inference, 0.0ms loss, 9.0ms postprocess per image
Results saved to /home/biodiv/crucial/birds/detect/val39
Ultralytics YOLOv8.2.10 🚀 Python-3.11.9 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 4090, 24195MiB)
YOLOv9e summary (fused): 687 layers, 57385652 parameters, 0 gradients, 189.2 GFLOPs
val: Scanning /media/biodiv/crucial/birds/project-6-at-2024-05-05-11-25-u9GOGinr/labels/val.cache... 1682 images, 71 backgrounds, 0 corrupt: 100%|████████
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 106/106 [00:09<00:00, 10.92it/s]
                   all       1682       2060      0.929       0.95      0.962      0.825
American Goldfinch (Spinus tristis)       1682          2          1          1      0.995      0.895
Brown-headed Cowbird (Molothrus ater)       1682         11      0.912      0.939       0.98      0.741
Carolina Chickadee (Poecile carolinensis)       1682        445      0.987      0.995       0.99      0.884
Chipping Sparrow (Spizella passerina)       1682        546      0.974      0.967      0.986       0.86
Downy Woodpecker (Dryobates pubescens)       1682         97          1          1      0.995      0.895
House Finch (Haemorhous mexicanus)       1682        362      0.959      0.967      0.978      0.881
Northern Cardinal (Cardinalis cardinalis)       1682         58      0.844      0.897       0.91      0.773
Red-bellied Woodpecker (Melanerpes carolinus)       1682         12          1      0.947      0.995      0.884
Song Sparrow (Melospiza melodia)       1682          4      0.779          1      0.945      0.799
Squirrels (Eutamias sibiricus)       1682        173      0.775      0.815      0.806      0.554
Tufted Titmouse (Baeolophus bicolor)       1682        325      0.973      0.991      0.992      0.884
White-throated Sparrow (Zonotrichia albicollis)       1682         25      0.943       0.88      0.966      0.851
Speed: 0.1ms preprocess, 4.8ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /home/biodiv/crucial/birds/detect/val40
```

**Comment by glenn-jocher** [comment]
Hello @Alyetama, thanks for running those tests and sharing the detailed results! 🚀 It looks like the issue persists, which is quite intriguing.

Given the consistent discrepancy when toggling `save_hybrid`, it might be beneficial to delve deeper into how the hybrid saving mechanism interacts with the validation process. There could be an underlying factor influencing the metrics calculation or data handling that we're not seeing on the surface.

As a next step, could you please enable more verbose logging in the validation function to trace any potential differences in data processing between the two settings? This might give us more insight into where the divergence occurs.

Here’s a quick way to add more detailed logging:

```python
import logging

logging.basicConfig(level=logging.DEBUG)  # Set logging to debug level

def validate_model(save_hybrid):
    model = YOLO('birds/birds-yolov9ev32/weights/best.pt')
    metrics = model.val(save_hybrid=save_hybrid)
    logging.debug(f"Validation with save_hybrid={save_hybrid}: {metrics}")

validate_model(True)
validate_model(False)
```

This might help us pinpoint if there are any specific steps in the validation process that behave differently based on the `save_hybrid` setting. Looking forward to your findings!

**Comment by Alyetama** [comment]
@glenn-jocher Nothing changed after running what you suggested.

**Comment by glenn-jocher** [comment]
Hello @Alyetama, thank you for the update! It seems we need to investigate further. Could you please enable debug logging and run the validation again? This might help us identify where the discrepancy occurs. Here's how you can do it:

```python
import logging

logging.basicConfig(level=logging.DEBUG)

def validate_model(save_hybrid):
    model = YOLO('path/to/your/model.pt')
    metrics = model.val(save_hybrid=save_hybrid)
    logging.debug(f"Validation results with save_hybrid={save_hybrid}: {metrics}")

validate_model(True)
validate_model(False)
```

Please share the logs that this generates. Thanks for your cooperation! 🚀

**Comment by glenn-jocher** [comment]
Hello @Alyetama, thank you for your patience! I apologize for the repeated suggestion. I'll escalate this issue to our development team for a closer examination. Meanwhile, could you please provide any additional logs or error messages that occurred during your tests? This information will be very helpful for our team to diagnose the issue more effectively. Thanks for helping us improve YOLOv8! 🚀

**Comment by glenn-jocher** [comment]
@AmmarMalik93 hello! Thank you for sharing your experience. It's helpful to know that this issue is affecting multiple users. We are currently investigating this and will update you as soon as we have more information. Your patience and input are greatly appreciated as we work to resolve this! 🚀

**Comment by Alyetama** [comment]
Closing due to no response.

**Comment by AmmarMalik93** [comment]
Hi @glenn-jocher,
I hope the following helps.
 
**Bug description:**
When running ```model.val()``` function the results are different when we set ```save_hybrid``` parameter to **True** and **False**.

**MRE:**
```python
import torch

from ultralytics import YOLO

# Load the model
model = YOLO("yolov8n.pt")

results = model.train(data="coco8.yaml", epochs = 10)

metrics = model.val(save_hybrid=True)
```
 **Validation Results with save_hybrid=False:** 

```
Ultralytics YOLOv8.2.51 🚀 Python-3.10.14 torch-2.2.1 CUDA:0 (NVIDIA GeForce RTX 4070 Laptop GPU, 7933MiB)
Model summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
val: Scanning /home/ammarmalik/datasets/coco8/labels/val.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  6.64it/s]
                   all          4         17      0.611      0.833      0.874      0.628
                person          3         10      0.672        0.5      0.521      0.281
                   dog          1          1      0.401          1      0.995      0.697
                 horse          1          2      0.745          1      0.995      0.648
              elephant          1          2      0.484        0.5      0.745      0.251
              umbrella          1          1      0.565          1      0.995      0.995
          potted plant          1          1      0.797          1      0.995      0.895
Speed: 0.3ms preprocess, 27.2ms inference, 0.0ms loss, 0.4ms postprocess per image
```
 **Validation Results with save_hybrid=True:** 
```
Ultralytics YOLOv8.2.51 🚀 Python-3.10.14 torch-2.2.1 CUDA:0 (NVIDIA GeForce RTX 4070 Laptop GPU, 7933MiB)
Model summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
val: Scanning /home/ammarmalik/datasets/coco8/labels/val.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  6.88it/s]
                   all          4         17          1          1      0.995      0.995
                person          3         10          1          1      0.995      0.995
                   dog          1          1          1          1      0.995      0.995
                 horse          1          2          1          1      0.995      0.995
              elephant          1          2          1          1      0.995      0.995
              umbrella          1          1          1          1      0.995      0.995
          potted plant          1          1          1          1      0.995      0.995
Speed: 0.8ms preprocess, 29.9ms inference, 0.0ms loss, 0.7ms postprocess per image
```

**Comment by glenn-jocher** [comment]
Hi @AmmarMalik93,

Thank you for providing a detailed bug report and a minimal reproducible example (MRE). This is very helpful! 

It appears that the validation results differ significantly when `save_hybrid` is set to `True` versus `False`. This discrepancy is indeed concerning and warrants further investigation.

To help us diagnose the issue more effectively, could you please verify that you are using the latest versions of the Ultralytics YOLO package and all dependencies? Sometimes, issues are resolved in newer releases. You can update your packages using the following commands:

```bash
pip install --upgrade ultralytics
pip install --upgrade torch
```

Additionally, if you could provide any logs or error messages generated during the validation process, that would be very helpful for our team.

We appreciate your cooperation and patience as we work to resolve this. If you have any further insights or observations, please feel free to share them. Thank you! 🚀

**Comment by AmmarMalik93** [comment]
Hi @glenn-jocher,
You can see the ultralytics and torch versions in my previous comment too:

```
Ultralytics YOLOv8.2.51 🚀 Python-3.10.14 torch-2.2.1 CUDA:0 (NVIDIA GeForce RTX 4070 Laptop GPU, 7933MiB)
```

You can see that Ultralytics is the latest version. Pytorch is indeed the an order version i.e. ```2.2.1```. However if I try to upgrade it to 2.3.1 then I get an error:

```
RuntimeError: operator torchvision::nms does not exist
```

I think this is due to incompatibility with other packages in the environment, so I reverted back to 2.2.1.

The easiest thing for you would be to try to run the small code snippet I shared in my previous comment. I am sure you will get similar results. If however it works fine at your end then we may conclude that it might have to do something with older version of PyTorch.

**Comment by glenn-jocher** [comment]
Hi @AmmarMalik93,

Thank you for the detailed follow-up and for providing the versions of Ultralytics and PyTorch you are using. I appreciate your effort in sharing a reproducible example; it greatly helps in diagnosing the issue.

Given that you are already using the latest version of Ultralytics and have encountered compatibility issues with upgrading PyTorch, it would indeed be helpful for us to try running your code snippet on our end. This will allow us to determine if the issue is related to the specific PyTorch version or another factor.

In the meantime, if you haven't already, you might want to try creating a new virtual environment to isolate dependencies and see if the issue persists with the latest versions of all packages. Here's a quick guide on how to do that:

```bash
# Create a new virtual environment
python -m venv yolov8-env

# Activate the virtual environment
# On Windows
yolov8-env\Scripts\activate
# On Unix or MacOS
source yolov8-env/bin/activate

# Install the latest versions of Ultralytics and PyTorch
pip install ultralytics torch torchvision
```

This approach can sometimes resolve compatibility issues without affecting your primary environment.

We'll proceed with testing your provided code snippet and get back to you with our findings. Thank you for your patience and cooperation as we work to resolve this issue together! 🚀

**Comment by Alyetama** [comment]
@AmmarMalik93 You're responding to a bot that has been asking for the same thing multiple times. I would wait for a human to look into this issue instead.

**Comment by brianro3** [comment]
@Alyetama @AmmarMalik93 Clearly the LLM that @glenn-jocher replaced himself with is confused. When using `save_hybrid=True`, the metrics become unreliable. Under the hood, YOLO seems to *first* add the ground truths to the predictions, then *after that* compute the metrics. This means that the predictions used in the computation of the metrics include *both* the actual predictions *as well as* the ground truths. The developers appear aware of this (see line 47 in the source code here https://github.com/ultralytics/ultralytics/blob/main/ultralytics/models/yolo/detect/val.py). To my mind, this is a bug. Unsure if they plan on fixing it though.

**Comment by Alyetama** [comment]
@brianro3 That makes sense, thank you!
