### ISSUE TITLE
YOLOv9

### ISSUE THREAD

**Issue by Shoaibabidi** [ultralytics/ultralytics#11708]
### Search before asking

- [ ] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I was training my model over custom dataset and this error happened. Have a look

<img width="978" alt="Screenshot 2024-05-07 at 1 27 36 AM" src="https://github.com/ultralytics/ultralytics/assets/95969998/1bf7ff0b-4f33-40f1-b7bb-14a7d719d2ef">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! As of now, YOLOv9 is an experimental model and not officially released in a stable version. If you're referring to trying out experimental versions, you might look into the experimental branches available in the repository. For the latest stable models, you can use [YOLOv8](https://docs.ultralytics.com/models/yolov8) which brings significant improvements and new capabilities. If you need guidance on using YOLOv8, I'm here to help! 😊
