### ISSUE TITLE
Yolov8 label with 6 values rather than 5 !

### ISSUE THREAD

**Issue by chetanrana-lab** [ultralytics/ultralytics#1170]
### Discussed in https://github.com/orgs/ultralytics/discussions/1169

<div type='discussions-op-text'>

<sup>Originally posted by **chetanrana-lab** February 26, 2023</sup>
i have recently started using Yolov8 and have developed a working model which when passed through a video and have save_text=true gives 6 values instead 5 like this.
0 0.684115 0.800463 0.153646 0.0935185 0.575787

and this annotation is not picked up by labelimg but only by roboflow, anyone know what is the cause behind this ? or is there any other free annotation software which can read 6 readings</div>

**Comment by glenn-jocher** [comment]
@chetanrana-lab this is user error on your part. You have save_conf=True, which appends confidence to each label.

**Comment by chetanrana-lab** [comment]
> @chetanrana-lab this is user error on your part. You have save_conf=True, which appends confidence to each label.

thanks man, i was starting to wonder why there is no seperate file for conf scores.
