### ISSUE TITLE
Dynamic vid_stride with multiple RTSPs

### ISSUE THREAD

**Issue by pornpra** [ultralytics/ultralytics#11723]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi

If I have a file named source.stream that contains four stream URLs (e.g., rtsp1, rtsp2, rtsp3, rtsp4), how can I set a dynamic vid_stride with the below code such that rtsp1 and rtsp2 use vid_stride = 1, and rtsp3 and rtsp4 use vid_stride = 5? 

```python
model = YOLO('yolov8s.pt', task='detect')
results = model.track(source, device=device, stream=True, classes=classes, verbose=False, stream_buffer=True, tracker=byte_track, vid_stride=x)
for pred in results:
    print(pred)
```

If Ultralytics doesn't support this, could you advise or share any Python code on how to perform this task?

**Comment by glenn-jocher** [comment]
Hello!

Currently, Ultralytics YOLOv8 does not support setting a `vid_stride` dynamically for different streams within a single tracking command. Each instance of model tracking would need to use the same `vid_stride`.

However, you can achieve this functionality by running separate instances for each stream with the respective `vid_stride` settings. Here's a simple way to manage this using threading:

```python
import threading
from ultralytics import YOLO

def track_stream(source, vid_stride):
    model = YOLO('yolov8s.pt', task='detect')
    results = model.track(source, device=device, stream=True, classes=classes, verbose=False, stream_buffer=True, tracker=byte_track, vid_stride=vid_stride)
    for pred in results:
        print(pred)

# Define your streams and corresponding stride values
streams = {'rtsp1': 1, 'rtsp2': 1, 'rtsp3': 5, 'rtsp4': 5}

# Create and start a separate thread for each stream
threads = []
for stream, stride in streams.items():
    t = threading.Thread(target=track_stream, args=(stream, stride))
    t.start()
    threads.append(t)

# Wait for all threads to finish
for t in threads:
    t.join()
```

This script will allow each stream to process at its specific `vid_stride`, running concurrently in separate threads. Let us know if you need further assistance! 🚀

**Comment by pornpra** [comment]
Thanks for your response.

Can I use OpenCV to pre-process video streams and skip frames such that rtsp1 and rtsp2 skip every frame, and rtsp3 and rtsp4 skip every 5 frames before passing them to the YOLO model, instead of using threading?

```python
import cv2
from ultralytics import YOLO

def process_stream(stream_url, frame_skip, device):
    cap = cv2.VideoCapture(stream_url)
    model = YOLO('yolov8s.pt', task='detect')
    frame_count = 0

    while True:
        ret, frame = cap.read()
        if not ret:
            break
        if frame_count % (frame_skip + 1) == 0:  # frame_skip + 1 because we include the current frame in the count
            results = model.track([frame], device=device, stream=True, classes=None, verbose=False, stream_buffer=True, tracker='byte_track', vid_stride=1)
            for pred in results:
                path = pred.path
                print(f"Processed frame from {stream_url} saved to {path}")
        frame_count += 1

    cap.release()

# Device configuration
device = 'cuda'  # or 'cpu'

# Define your streams and their respective frame skips (corresponding to vid_stride - 1)
streams = {
    'rtsp1': 0,  # Process every frame
    'rtsp2': 0,  # Process every frame
    'rtsp3': 4,  # Skip 4 frames
    'rtsp4': 4,  # Skip 4 frames
}

# Loop for processing each stream one at a time
for stream_url, skip in streams.items():
    print(f"Starting processing for {stream_url}")
    process_stream(stream_url, skip, device)
    print(f"Finished processing for {stream_url}")
```

Can this approach simulate the effect of using different vid_stride values directly in the YOLO tracking function? 
I am asking about this method because I am concerned about RAM usage when using threads.

**Comment by glenn-jocher** [comment]
@pornpra hi there! 😊

Yes, your approach of using OpenCV to pre-process and skip frames before feeding them into the YOLO model absolutely works as a good alternative to manage different frame skips without threading. By setting `vid_stride=1` in the YOLO model and handling the frame skipping manually in your script as you've outlined, you effectively simulate various `vid_stride` behaviors.

Your code example correctly adjusts the frequency of frames processed from each stream by changing the `frame_skip` parameter. This will help control the RAM usage as you process one stream at a time, rather than handling multiple streams concurrently with threading. Just ensure your system is capable of handling the looped single-stream processing without lagging, especially when processing higher-resolution video streams.

Let us know how this works out, or if there's anything else you'd like to optimize! 👍
