### ISSUE TITLE
AttributeError: 'Segment' object has no attribute 'detect'

### ISSUE THREAD

**Issue by 807xuan** [ultralytics/ultralytics#11727]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

from ultralytics import YOLO
model = YOLO('weights/best.pt')
results = model('1.jpg')
# model.predict('1.jpg', save=True, imgsz=640, conf=0.5)
for r in results:
    print(r.masks)
Here's my simple test case.
I used yolov8s-seg.pt to train the custom dataset and then ran a simple test case, but the error was as follows:
AttributeError: 'Segment' object has no attribute 'detect'

But the best.pt trained a week ago can be used normally . Its very strange!!!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by 807xuan** [comment]
I have found the cause of the problem. The reason is: the versions of ultralytics and yolov8 do not match. My yolov8 is version 8.1 and ultralytics is version 8.2. I downgraded ultralytics to 8.1. After training again, I got best.pt and no error was reported after running the test case.

**Comment by glenn-jocher** [comment]
@807xuan great job pinpointing the version mismatch issue! Matching the versions of YOLOv8 and the Ultralytics library often resolves such errors. If you have any more questions or face further issues, feel free to reach out. Happy coding! 😊

**Comment by Salmanshu4** [comment]
how to check yolo version?

**Comment by rajaram6052150** [comment]
C:\Users\Rr>yolo version
8.2.5

C:\Users\Rr>ultralytics version
8.2.5

My versions are same but still I got this error.

**Comment by kaikcoder** [comment]
怎么区分yolo版本和ultralytics版本

**Comment by glenn-jocher** [comment]
To check your Ultralytics library version, run `pip show ultralytics` in CLI or `import ultralytics; print(ultralytics.__version__)` in Python. YOLO model versions (like YOLOv8/YOLO11) are specified in their filenames (e.g., `yolov8n.pt`) and can also be viewed via `model.task` after loading the model.
