### ISSUE TITLE
save pr curve

### ISSUE THREAD

**Issue by Youareabigpig** [ultralytics/ultralytics#11728]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

how can I save the data of the horizontal and vertical coordinates of the pr curve in results.csv?

**Comment by glenn-jocher** [comment]
@Youareabigpig hello! To save the precision and recall data into a `results.csv` file, you can modify the validation code to extract these metrics directly after they are computed within the validation loop.

Here's a simplified example of how you might approach this:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('path/to/your/model.pt')

# Validate the model and get metrics
metrics = model.val()

# Extracting precision and recall
precision = metrics['precision']
recall = metrics['recall']

# Saving the data to a CSV
import pandas as pd
df = pd.DataFrame({'Precision': precision, 'Recall': recall})
df.to_csv('results.csv', index=False)
```

Make sure to adapt the paths and details according to your specific setup and data handling needs. 🚀

**Comment by Youareabigpig** [comment]
![Image_1715127469846](https://github.com/ultralytics/ultralytics/assets/139609277/34da53a9-2a6f-4b51-9fac-1f4732f41d12)
Maybe I'm not describing the problem accurately enough, what I'm asking is how to get the data for the horizontal coordinates of the p-r curve, and the data for the vertical coordinates of the p-r curve, and save them in results.csv.

**Comment by Youareabigpig** [comment]
![Image_1715127469846](https://github.com/ultralytics/ultralytics/assets/139609277/6e593f0b-16b7-47bc-a3b8-58b293d16117)
Maybe I didn't describe the problem accurately enough. What I'm asking is, for example, for this p-r graph above, how to get the horizontal coordinate data of the p-r curve, and its vertical coordinate data, and save them in results.csv.

**Comment by glenn-jocher** [comment]
@Youareabigpig hey there! To save the precision-recall (P-R) curve data into a `results.csv`, you can extract the precision and recall values from your model’s validation metrics and write them directly to a CSV. Here’s a brief example on how you might do that:

```python
from ultralytics import YOLO
import pandas as pd

# Load your model
model = YOLO('path/to/your/model.pt')

# Validate the model and get metrics
metrics = model.val()

# Extracting precision and recall values
precision = metrics['precision']
recall = metrics['recall']

# Create DataFrame and save as CSV
df = pd.DataFrame({'Recall': recall, 'Precision': precision})
df.to_csv('results.csv', index=False)
```

This script collects the precision and recall values after validation, and places them in a `results.csv` file. Each row corresponds to a different threshold setting used during model validation. Hope this helps! 😊

**Comment by Youareabigpig** [comment]
I run the code and it reports an error:

Traceback (most recent call last):
  File "pr.py", line 11, in <module>
    precision = metrics['precision']
TypeError: 'DetMetrics' object is not subscriptable

**Comment by glenn-jocher** [comment]
Hey there! It looks like you're trying to access the attributes of the `DetMetrics` object using dictionary keys which isn’t the correct method for this type of object. You should access the attributes directly as properties of the object. Here’s how you can do it correctly:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('path/to/your/model.pt')

# Validate the model and get metrics
metrics = model.val()

# Extracting precision and recall values
precision = metrics.precision
recall = metrics.recall
```

Give this a try and it should resolve the error you're encountering! 😊 Let me know if you need any more help.
