### ISSUE TITLE
How to optimize the model,NMS,IOU

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#11720]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![222](https://github.com/ultralytics/ultralytics/assets/6490927/2afa7ec6-99ea-478b-8915-f5d847674abd)
How to optimize the model

`NMS`
`IoU`

**Comment by achuntelolan** [comment]
Hii  @monkeycc you can use Iou as arguments and you can optimize the model please refer the documents for more idea about it 
https://docs.ultralytics.com/usage/cfg/#train-settings
