### ISSUE TITLE
Does exporting NCNN support dynamic size input?

### ISSUE THREAD

**Issue by zqstdy** [ultralytics/ultralytics#11726]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I didn't find any current support for dynamic dimensions
`    model=ultralytics.YOLO("I:/Code/runs/detect/train16/weights/best.pt")
    model.export(format='ncnn',imgsz=640,  dynamic=True,half=True)`

I tried to modify the param file and ran an error message after making the changes

![image](https://github.com/ultralytics/ultralytics/assets/62828617/6de254ef-d198-4f9c-97ef-70b766fecd37)
The trained model is yolov8-ghost.yaml

**Comment by glenn-jocher** [comment]
@zqstdy hello! Unfortunately, dynamic dimension input is not supported when exporting to NCNN format at this time. The `dynamic=True` flag works for formats like ONNX and TensorRT but is not applicable for NCNN, which might cause the error you encountered after modifying the param file.

For now, you would need to specify the exact input dimensions when exporting YOLO models for use with NCNN. If adaptation or support for dynamic input dimensions in NCNN is essential for your project, please consider watching our repository for updates as we continue to improve and add features based on user needs. 🌟

**Comment by zqstdy** [comment]
Okay, thank you
I'll check if there are any other solutions

**Comment by glenn-jocher** [comment]
@zqstdy You're welcome! If you have any further questions or need assistance as you explore other solutions, feel free to reach out. Happy coding! 😊
