### ISSUE TITLE
Class Name using Tracking Id

### ISSUE THREAD

**Issue by saadan1234** [ultralytics/ultralytics#11732]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there anyway I can get the class name, given the tracking Id. Forexampls: 

    results = model.track(im0, persist=True, classes=[0,2])
    boxes = results[0].boxes.xyxy.cpu()

    if results[0].boxes.id is not None:
        track_ids = results[0].boxes.id.int().cpu().tolist()

        for box, track_id in zip(boxes, track_ids):
            annotator.box_label(box, label=str(track_id), color=bbox_clr)
            print(str(track_id))
            annotator.visioneye(box, center_point)
            annotator.visioneye(box, center_point_2)

Can I print the name of class inside for loop?
I have tried using box.cls.item() it does not work.

### Additional

I am tring to get the type of object being tracked.

**Comment by glenn-jocher** [comment]
To retrieve and print the class name using the tracking ID in your loop, you can utilize the `names` attribute from the `results` object which contains the class names for the IDs. Make sure to convert the `cls` tensor to an integer and use it to index the `names` list. Here's how you can modify your loop:

```python
results = model.track(im0, persist=True, classes=[0,2])
boxes = results[0].boxes.xyxy.cpu()

if results[0].boxes.id is not None:
    track_ids = results[0].boxes.id.int().cpu().tolist()
    classes = results[0].boxes.cls.int().cpu().tolist()  # Get class indices
    names = results[0].names  # List of class names

    for box, track_id, cls_idx in zip(boxes, track_ids, classes):  # include classes in your loop
        class_name = names[cls_idx]  # Get the class name using class index
        annotator.box_label(box, label=f'{track_id}:{class_name}', color=bbox_clr)
        print(f'Track ID: {track_id}, Class: {class_name}')
        annotator.visioneye(box, center_point)
        annotator.visioneye(box, center_point_2)
```

This snippet will print both the tracking ID and the corresponding class name for each tracked object.
