### ISSUE TITLE
How to get the estimated time it takes to train a yolov8 model 

### ISSUE THREAD

**Issue by ssunyoung2** [ultralytics/ultralytics#11748]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

After training starts, can I know the time from when 1 epoch has not progressed until it is completed?

The final goal is to obtain the expected training time up to 100 epochs from the training run.

**Comment by glenn-jocher** [comment]
Hey there! To estimate the time taken for training up to 100 epochs, you can follow this simple method:

After commencing the training using YOLOv8, the time for each epoch is logged. Once the first epoch completes, it will display the elapsed time. This time can give you a rough estimate.

If you're running it via Python, you can calculate this using:

```python
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.yaml')  # adjust model specification as needed

# Train the model
results = model.train(data='coco128.yaml', epochs=100, imgsz=640)

# Access training time for epochs
print(f'Average Epoch Duration: {results.times.mean()} seconds')
print(f'Estimated Total Training Time for 100 epochs: {results.times.mean() * 100} seconds')
```

This script provides an average duration per epoch and estimates the total time for 100 epochs.

Feel free to tweak the model path and data specifics to suit your requirements! 🚀
