### ISSUE TITLE
How does yolov8 achieved to use terminal excution?

### ISSUE THREAD

**Issue by georgelele1** [ultralytics/ultralytics#11740]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have looked over yolov5 and v8 ,in yolov5 we used parse to make terminal excution available, however i did not seen such feature in the v8, i see the yolov8 seems make the teminal CLI as import class , such as yolo detect train as 3 different classes to import and use a map function to located all the related elements, so i just wonder how did yolov8 realistic such feature! if there is any misunderstanding please correct me thanks !

**Comment by glenn-jocher** [comment]
Hi! Great question! 🚀 In YOLOv8, the CLI functionality is handled differently than in YOLOv5. We utilize a centralized CLI system in `yolo.py` where a common entry point dispatches the execution across multiple modules based on the command line arguments.

Here is a simplified breakdown:
- The main CLI script interprets the task (`detect`, `train`, etc.) and relevant arguments (`model`, `source`, etc.).
- It uses a mapper to link each task with the corresponding Python module.
- Instead, each functionality (such as training or detection) is encapsulated in separate classes that the CLI dynamically interacts with depending on the input command.

This allows for clear separation of concerns and easier code maintenance. You can explore this setup in the repository under `ultralytics/cli`.

I hope this clears things up! Let me know if you have any more questions. Happy coding!👨‍💻
