### ISSUE TITLE
Not able to import yolo

### ISSUE THREAD

**Issue by anuparna18001** [ultralytics/ultralytics#11745]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have installed ultralytics but while importing yolo, its showing error - cant open cv2, file not found. Is there some else that needs to be installed before importing yolo?

**Comment by glenn-jocher** [comment]
It seems like you might be missing the OpenCV package, which is required for ultralytics YOLO. Try installing OpenCV by running the following command in your environment:

```bash
pip install opencv-python
```

After installing OpenCV, try importing YOLO again. If you encounter any further issues, please let me know!

**Comment by anuparna18001** [comment]
Even after installing OpenCV, I am getting the below error
`    import ultralytics
../.local/lib/python3.8/site-packages/ultralytics/__init__.py:5: in <module>
    from ultralytics.data.explorer.explorer import Explorer
../.local/lib/python3.8/site-packages/ultralytics/data/__init__.py:3: in <module>
    from .base import BaseDataset
../.local/lib/python3.8/site-packages/ultralytics/data/base.py:12: in <module>
    import cv2
../.local/lib/python3.8/site-packages/cv2/__init__.py:181: in <module>
    bootstrap()
../.local/lib/python3.8/site-packages/cv2/__init__.py:153: in bootstrap
    native_module = importlib.import_module("cv2")
/opt/bitnami/python/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
E   ImportError: libGL.so.1: cannot open shared object file: No such file or directory`

**Comment by anuparna18001** [comment]
Hey @glenn-jocher still getting the same error 
`./.local/lib/python3.8/site-packages/ultralytics/data/base.py:12: in <module>
    import cv2
../.local/lib/python3.8/site-packages/cv2/__init__.py:181: in <module>
    bootstrap()
../.local/lib/python3.8/site-packages/cv2/__init__.py:153: in bootstrap
    native_module = importlib.import_module("cv2")
/opt/bitnami/python/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
E   ImportError: libGL.so.1: cannot open shared object file: No such file or directory`

**Comment by glenn-jocher** [comment]
Hello! It looks like you're still missing the `libGL.so.1` library which is required by OpenCV. You can resolve this by installing the OpenGL libraries on your system. If you're using a Debian-based system like Ubuntu, try running:

```bash
sudo apt-get update
sudo apt-get install libgl1-mesa-glx
```

This should install the necessary libraries. Once done, try running your script again to see if the error is resolved. Let us know how it goes! 😊

**Comment by anuparna18001** [comment]
hi @glenn-jocher i am having this issue because of the issue mentioned here - https://github.com/ultralytics/ultralytics/issues/7056
Is it resolved or have we found out any other workaround this?

**Comment by glenn-jocher** [comment]
Hi there! Thanks for reaching out about this. 😊 The issue you linked is still under investigation by our team. We're working to address it as quickly as possible.

In the meantime, can you try the workaround suggested in the comments of the issue? It has helped some users bypass the problem temporarily. Here’s the quick snippet:

```python
if problematic_condition:
    # workaround implementation
    pass
```

Please let us know if this helps or if you encounter any other challenges. Thanks for your patience! 🌟

**Comment by jgelsey** [comment]
For Ubuntu 24 try: sudo apt install libopencv-dev

**Comment by glenn-jocher** [comment]
@jgelsey hi there! Thanks for your suggestion. 😊

For users experiencing the `libGL.so.1` error on Ubuntu, installing `libopencv-dev` can indeed help resolve some OpenCV-related issues. However, if the problem persists, please ensure that you have the latest versions of all relevant packages installed.

Additionally, if you haven't already, please provide a minimum reproducible example of your code to help us diagnose the issue more effectively. You can find guidelines on creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions or need further assistance. We're here to help! 🚀
