### ISSUE TITLE
yolo_world

### ISSUE THREAD

**Issue by FengJin-cv** [ultralytics/ultralytics#11750]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why can't yolo_world detect any targets in the image, still only having 80 categories

**Comment by glenn-jocher** [comment]
Hello!

It sounds like you're encountering an issue where `yolo_world` is not detecting targets despite having 80 categories. This is likely related to the specifics of the image or model settings. Here are a few things you can check:

- **Input Image:** Ensure the input image is properly preprocessed and sized according to the model requirements.
- **Model Weights:** Make sure the model is loaded with the correct pretrained weights.
- **Threshold Settings:** Check if the confidence threshold and non-max suppression settings are appropriately configured.

You could try adjusting the confidence threshold with a simple code snippet if using the Python API:

```python
from ultralytics import YOLO

# Load the model
model = YOLO('yolo_world.pt')

# Detect with a lower confidence threshold
results = model('path/to/image.jpg', conf=0.1)
results.show()
```

If you’re still facing issues, please provide some details about the implementation or errors for more specific guidance.

Best regards!

**Comment by eliabntt** [comment]
Hi @glenn-jocher are there two different confidence thresholds for text and boxes or just one?

**Comment by glenn-jocher** [comment]
@eliabntt hi! There is typically one confidence threshold that applies to both text and boxes in YOLO models. If you have further questions, feel free to ask!
