### ISSUE TITLE
What is the native underlaying/implementation framework of Yolov8?

### ISSUE THREAD

**Issue by ErwinVanDijkMotiveEngineering** [ultralytics/ultralytics#11752]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,
I have a question about Yolov8. What is the native underlaying/implementation framework. It seems to be pytorch.
Is that correct? I couldn't find it in the docs. https://docs.ultralytics.com/integrations/torchscript/?h=torch#key-features-of-torchscript-models
sort of suggests it is. But I would like to be sure.

The reason I would like to know this, is that I want to host Yolov8 models for inference inside a C++ aplication without any export steps. 
So just like the default python way. (No exports to ONNX, TensorRT. We already played with these).
Is this even possible? or do you need to export it anyway if you want to host the model(s) inside a C++ program?

For extra information and to so see if I'm going the right direction, let me describe what I would like to achieve:
Currently we have a C++ application which hosts non-yolo inference models. Images are provided via a socket, results (classifications, bboxes, contours) are send back via a socket
We do want to extend the existing application with native yolo support without any conversion.

**Comment by glenn-jocher** [comment]
Hello!

Yes, you are correct. YOLOv8 is natively implemented in PyTorch. If you're looking to integrate YOLOv8 models directly into a C++ application without exporting, the best approach is to use TorchScript. TorchScript allows you to run your PyTorch models in a C++ environment.

Here's a basic example of how you can convert a YOLOv8 model to TorchScript:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('yolov8n.pt')

# Convert to TorchScript
model.to_torchscript('yolov8n.torchscript')
```

After this, you can load this TorchScript model in your C++ application. Check out the [TorchScript documentation](https://pytorch.org/docs/stable/jit.html) for more details on how to load and run models in C++.

Let me know if you need further guidance!

**Comment by ErwinVanDijkMotiveEngineering** [comment]
Ok, thank you very much for your fast response!

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to ask. Happy coding! 😊
