### ISSUE TITLE
predict save location

### ISSUE THREAD

**Issue by enesagu** [ultralytics/ultralytics#11759]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to learn where did i save my predicted image file

from ultralytics import YOLO
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

image_path = 'car3.jpg'
model = YOLO('license_plate_detector.pt')
results = model(image_path,save=True,show_labels=False)
save_dir_ = results.save_dir
print("Save Path:", save_dir_)

im=Image.open(f"{save_dir_}/{image_path}")
plt.imshow(np.array(im))
plt.axis("off")
plt.show()

**Comment by glenn-jocher** [comment]
Hey there! 👋

From the code snippet you shared, it seems you want to know where your prediction results are stored. You can find the location in the `save_dir` attribute of the `results` object. After performing predictions with `save=True`, all the result images will be saved in the directory specified by this `save_dir`. Here is how you can check it:

```python
print("Save Path:", results.save_dir)
```

Just a small note: the `save_dir_` variable you've created and the actual attribute name `save_dir` are slightly different. Be sure to use `results.save_dir` to accurately reference the results path. 

Happy coding! 🚀

**Comment by enesagu** [comment]
Solved. Thank you :)

**Comment by glenn-jocher** [comment]
You're welcome! 😊 If you have any more questions in the future, feel free to ask. Happy coding! 🚀
