### ISSUE TITLE
export to tensorrt with version 10.0.6

### ISSUE THREAD

**Issue by aTunass** [ultralytics/ultralytics#11753]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I tried exporting from pytorch to onnx according to your document and it works with my library versions as follows:
**pytorch: 2.1.0
onnx: 1.15.0
tensorrt: 8.5.3.1
cuda: 11.6
ultralytics: 8.1.47
hardware:**
![image](https://github.com/ultralytics/ultralytics/assets/119738823/794dee1c-fa4e-408e-b531-3fff5d06e2d1)
But when I change the version of tensorrt to 10.0.6 installed by [,](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-pip) to see if the speed improves further and the following error appears:
![image](https://github.com/ultralytics/ultralytics/assets/119738823/444d4dad-50a2-430b-a91b-a4fa4c477060)
so I want to ask what could be the cause of this error. Maybe it's because of my hardware or ultralytics doesn't yet support tensorrt version 10

**Comment by aTunass** [comment]
In addition, when I successfully converted to tensorrt, I tested its speed a bit by:
**Pytorch 2.1.0:**
![image](https://github.com/ultralytics/ultralytics/assets/119738823/62bc3c56-e0d2-47d4-abec-eb46726733c3)
**Tensorrt 8.5.3.1:**
![image](https://github.com/ultralytics/ultralytics/assets/119738823/9334b570-267f-4367-953b-50527f338ef7)
the inference time i get from both is 24ms and they are almost equal. Can you explain to me about this?

**Comment by glenn-jocher** [comment]
It's great to hear that you've successfully converted the model to TensorRT and are conducting performance tests! 🚀

Regarding the similar inference times for PyTorch and TensorRT, there are a couple of factors to consider:

1. **Model Complexity and Size**: Smaller and less complex models may not show as significant speed improvements in TensorRT compared to larger, more complex models.

2. **Optimization Levels**: Ensure that when converting to TensorRT, optimizations like layer fusions, precision calibration (FP16/INT8), and other TensorRT specific optimizations are properly utilized.

3. **Batch Size**: TensorRT improvements are often more noticeable at larger batch sizes. If you're testing with a batch size of 1, try increasing this to see if performance gains become more apparent.

4. **System Overheads**: The time to copy data to/from the GPU and other system overheads might mask improvements in the actual model inference time.

If you've checked all the above and the times remain similar, it could also be interesting to profile your model's GPU utilization to see if there are any bottlenecks or inefficiencies.

For detailed profiling, you can use tools like NVIDIA's Nsight Systems or the profiling features available in TensorRT to get a deeper insight into where the time is being spent during inference. This can offer clues on further optimization or adjustments needed.

**Comment by aTunass** [comment]
Thanks for your response, i'm use half=True when export to tensorrt with batch_size=1. May be i will try it agian. And about my first question about using tensorrt 10, I still don't seem to get an explanation here. Can you assist me on this

**Comment by johnnynunez** [comment]
> Thanks for your response, i'm use half=True when export to tensorrt with batch_size=1. May be i will try it agian. And about my first question about using tensorrt 10, I still don't seem to get an explanation here. Can you assist me on this

You have to update all packages to the latest version.
I’m using jetson agx orin with tensorrt 10.0.1.6 without problems.

**Comment by glenn-jocher** [comment]
@johnnynunez hi there!

Regarding the TensorRT 10 issue you're experiencing, it should be compatible with YOLOv8 provided that all associated packages are up-to-date. Sometimes package version mismatches can lead to unexpected errors.

Could you please confirm that all your software, including CUDA and cuDNN, are compatible with TensorRT 10? Sometimes, distinct specificities of the installation environment, like what is seen with different Jetson devices, could affect this compatibility. Please ensure that your environment aligns with what is expected for TensorRT 10 operation.

If everything is properly updated and the error persists, the logs from your current failed attempt could help diagnose the issue. Feel free to share those for further assistance!

Keep tweaking, and let’s get this resolved! 🛠️🚀

**Comment by aTunass** [comment]
Currently I have switched to using tensorrt 8.5.1.3 and can use it and see good performance of tensorrt compared to pytorch, so I will close my issue here. Thanks for your feedback and supporting me

**Comment by glenn-jocher** [comment]
That's great to hear! I'm glad you're seeing improved performance with TensorRT 8.5.1.3. If you have any more questions or need further assistance in the future, feel free to reach out. Happy coding! 😊🚀
