### ISSUE TITLE
Unable to test without training

### ISSUE THREAD

**Issue by AlphaIcarus** [ultralytics/ultralytics#11765]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello. I was trying to test the yolov8m model with the YCB dataset, without training the model previously, and it won't allow me. If I'm correct, the `yolov8m.pt` model is pretrained, and all I need to do is check on the precision of the predictions on this dataset.

I want to do the following, but some error pops up:

`
model = YOLO('yolov8m.pt')
results = model.val(data="./YCB/data.yaml")
print results
`

I want to make predictions and then check how they went with the annotation files of each image, without training before on that dataset, and obtain result metrics.

**Comment by glenn-jocher** [comment]
Hello! Thank you for reaching out.

It looks like you're trying to validate (`val`) a model without previously training it on the specific dataset (YCB) you're interested in. While `yolov8m.pt` is indeed a pretrained model, it's only been trained on its original dataset (likely COCO). To validate with the YCB dataset, it would actually need to be trained on that dataset first or at least fine-tuned if seeking meaningful metrics.

However, if you just want to make predictions (without obtaining validation metrics), you can directly use the `predict` mode. Here's how you can do it:

```python
model = YOLO('yolov8m.pt')
results = model.predict(source='path/to/your/images')  # Directory or single image path
for result in results:
    result.show()  # Displays the image with predictions
    print(result.xyxy)  # Print bounding box coordinates
```

If you want to compare these predictions against annotations to get precision or similar metrics, you would typically need a custom script that reads the annotations and compares them to the model's predictions.

I hope this clarifies! Let me know if there's anything else you need help with. 😊
