### ISSUE TITLE
In DDP, pretrained model won't be loaded.

### ISSUE THREAD

**Issue by comlhj1114** [ultralytics/ultralytics#11769]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Multi-GPU

### Bug

In DDP mode, pretrained model cannot be loaded.

There are three cases.

Case 1: CLI (NOT Working)
yolo detect train model=yolov8s.yaml pretrained=my_model.pt devices=0,1

Case 2: Python (NOT Working)
model = YOLO('yolov8s.yaml').load('my_model.pt')
model.train(...., device=[0,1])

Case 3: Python (ONLY Working)
model = YOLO('my_model.pt')
model.train(...., device=[0,1])

I think the generated python file for DDP makes problem, because it uses `trainer = DetectionTrainer(cfg=cfg, overrides=overrides)` but there is not a code for load pretrained model in DetectionTrainer.__init__.

This makes a problem in multi-GPU experiments, because there is no way to load a similar model, not exactly same model.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@comlhj1114 hello! Thanks for reporting this issue with loading pretrained models in DDP mode. It looks like you're correct about the behavior you've observed.

For your Case 1 and Case 2 where the model isn't loading properly, it seems there might be a need for additional handling in our DDP setup to enable loading pretrained weights directly when initializing a model from a YAML file. 

The common workaround for now, as you've found, is to load the model directly from the pretrained `.pt` file before calling `.train()`, as shown in your Case 3. That's a valid approach when deploying to a multi-GPU setting.

Meanwhile, I'll forward this issue to our development team to consider improving the handling of pretrained models in DDP configurations. If you have further insights or would like to contribute to a solution, we encourage you to follow and possibly contribute to this discussion on GitHub. Your feedback is invaluable! 😊

**Comment by comlhj1114** [comment]
@glenn-jocher Thank you for your rapid and valuable feedback. I will try to contribute!

**Comment by glenn-jocher** [comment]
@comlhj1114 thanks for the PR, we have a review by @Laughing-q pending on it, and if everything looks good we should have it merged this week :)
