### ISSUE TITLE
Yolov8-pose is not returning the "id" when the triton is used

### ISSUE THREAD

**Issue by karemdm** [ultralytics/ultralytics#11760]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I am using thus code to run yolov8-pose with triton. However, the network always returns the id None and the is_track as False.
When I run the model without pose, that is, just the object detector, the "id" is returned.
I followed this documentation to convert the model to onnx and create the triton container.
[https://docs.ultralytics.com/pt/guides/triton-inference-server/#running-triton-inference-server](url)

```import cv2 
from ultralytics import YOLO
import numpy as np
from collections import defaultdict 
import time
import tritonclient.http as triton_http
from ultralytics.utils.plotting import colors, Annotator

def yolov8_triton_test():
    model = YOLO("http://localhost:8000/yolo", task="pose")

    # Open the video file
    video_path = "/home/harsh/camera_output_udp1.mp4"
    cap = cv2.VideoCapture(video_path)
    frame_cnt = 0
    # Define o frame desejado
    cap.set(cv2.CAP_PROP_POS_FRAMES, 900)

    # Define o codec e o objeto VideoWriter para salvar o vídeo processado
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')  # Codec padrão do OpenCV
    fps = cap.get(cv2.CAP_PROP_FPS)
    frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    out = cv2.VideoWriter('output.mp4', fourcc, fps, (frame_width, frame_height))
    
    # Loop through the video frames
    while cap.isOpened():
        frame_cnt += 1
        frame_start = time.time()

        # Read a frame from the video
        success, frame = cap.read()

        if success:
            # results = model(frame)
            # Run YOLOv8 tracking on the frame, persisting tracks between frames
            model.predictor = model._smart_load("predictor")()
            model.predictor.setup_model(model=model.model)
            model.predictor.model.names = {0:'person'}
            model.predictor.model.kpt_shape = [17, 3]
            results = model.track(frame, device=0, conf=0.3, iou=0.5, persist=True)

            # Get the boxes and track IDs
            boxes = results[0].boxes.xywh.cpu()
            track_ids = results[0].boxes.id.int().cpu().tolist()

            # Visualize the results on the frame
            annotated_frame = results[0].plot()
            out.write(annotated_frame)
           
            # Verifica se alcançou o frame alvo
            if frame_cnt == 1200:
                break
        else:
            break

    # Release the video capture object and close the display window
    cap.release()
    out.release()
    cv2.destroyAllWindows()   
    
yolov8_triton_test()
```

I am also including the contents of the config.pbtxt file. However, I had to change the output, because the values in the documentation were causing an error.

```name: "YoloPose"
platform: "onnxruntime_onnx"
max_batch_size : 0
input {
  name: "images"
  data_type: TYPE_FP32
  dims: 1
  dims: 3
  dims: 640
  dims: 640
  reshape {
    shape: 1
    shape: 3
    shape: 640
    shape: 640
  }
}
output {
  name: "output0"
  data_type: TYPE_FP32
  dims: 1
  dims: 56
  dims: 8400
}
instance_group {
  count: 4
  kind: KIND_GPU
}
parameters: {
    key: "kpt_shape"
    value: {
        string_value: "[17, 3]"
    }
}
parameters: {
    key: "names"
    value: {
        string_value: "person"
    }
}
```

**Comment by glenn-jocher** [comment]
Thanks for reaching out with the details of your issue regarding tracking IDs not returning in YOLOv8-pose when using Triton. 🕵️‍♂️

From what you've described, it seems the issue might be related to the model configuration in Triton, specifically how the outputs are being handled. When converting your model to ONNX and deploying with Triton, it’s crucial that the output settings in `config.pbtxt` correctly map to the specific outputs needed for pose estimation, including tracking IDs.

Here's a general step you could consider:
- **Adjust the Output Configurations in Triton:** Ensure that the output specifications in your `config.pbtxt` file correctly correspond to the expected outputs from the YOLOv8-pose model. This includes ensuring that the dimensions and data types align properly with what YOLOv8-pose outputs, which should include tracking IDs as well.

Also, make sure that your deployment environment has properly aligned dependencies for Triton and the YOLOv8-pose model to communicate effectively.

If you continue to face issues, consider consulting the specific output format and structure that YOLOv8-pose generates natively, and replicate this in your Triton output settings. This might involve some trial and error to align everything.

Hope this helps! Keep us posted on your progress. 🚀

**Comment by karemdm** [comment]
Thanks for the feedback.
I made all the necessary adjustments to the config.pbtxt file and I continue to have problems with the ID on track. From what I noticed, within the returned object, the content of "is_track" is always "False" and when I manually change it to "True", the content of ID automatically changes to the same value contained in y2 of data.

**Comment by glenn-jocher** [comment]
Thanks for the update! It sounds like there might be an issue with how the tracking information is being parsed or handled in your setup. If `is_track` is not being set correctly, it could indicate that the model or the server setup isn't properly configured to handle tracking.

A quick check you can do is to ensure that your model is indeed outputting the tracking information and that it's being correctly interpreted by your application. Here’s a small snippet to help you debug the output directly from the model:

```python
results = model.predict(frame)
print("Tracking status:", results.is_track)
print("IDs:", results.boxes.id)
```

This will help confirm if the issue is with the model output or further downstream in your processing pipeline. If the model outputs are correct, you might need to adjust how these outputs are handled in your application logic. Keep us posted! 🛠️

**Comment by karemdm** [comment]
When I use the mentioned commands:
`results2 = model.predict(frame)
print("Tracking status:", results2[0].boxes.is_track)
print("IDs:", results2[0].boxes.id)
`
I have the following output:
`0: 640x640 1 person, 28.8ms
Speed: 2.3ms preprocess, 28.8ms inference, 12.5ms postprocess per image at shape (1, 3, 640, 640)
Tracking status: False
IDs: None`

When I change is_track manually I have the following output:
`results2[0].boxes.is_track = True
print("Tracking status:", results2[0].boxes.is_track)
print("Data:", results2[0].boxes.data)
print("IDs:", results2[0].boxes.id)`

`Tracking status: True
Data: tensor([[113.0000, 249.0000, 205.0000, 495.0000,   0.9134,   0.0000]])
IDs: tensor([495.])`

I noticed that ID receives the same value as y2 of date. However, when I change the value of y2, the ID value automatically changes.

`import copy
result = copy.deepcopy(results2)
result[0].boxes.data[0][3] = 1
print("Tracking status:", result[0].boxes.is_track)
print("Data:", result[0].boxes.data)
print("IDs:", result[0].boxes.id)`

`Tracking status: True
Data: tensor([[113.0000, 249.0000, 205.0000,   1.0000,   0.9134,   0.0000]])
IDs: tensor([1.])`

With yolo for object detection, tracking is done correctly. I'm only having this ID problem with the pose version.

**Comment by karemdm** [comment]
When inference is performed in the onnx model, there is no problem identifying the ID. 
`model = YOLO('model.onnx', task="pose")`

The loss of the ID occurs when I use the triton.
I do not know if it could be some information in the config or something else.
`model = YOLO("grpc://localhost:8001/YoloPose", task="pose")`

**Comment by glenn-jocher** [comment]
Thank you for the additional information! It’s helpful to know that the ID is correctly identified when using the ONNX model directly. This indicates that the issue likely lies within the Triton configuration or how Triton handles the model outputs.

To troubleshoot further, please double-check the `config.pbtxt` file for Triton to ensure it accurately reflects the model's output specifications. Additionally, ensure that Triton is correctly set up to handle the pose task outputs, including tracking IDs.

If the problem persists, it might be beneficial to consult the Triton documentation or reach out to their support for more detailed guidance on configuring models for pose estimation with tracking IDs.

Feel free to share any updates or further questions. We're here to help! 😊

**Comment by karemdm** [comment]
I found the ID problem but I could not solve it.

I have the `config.pbtxt` file. However, when running the initial code, the following error occurs:
```ultralytics/utils/ops.py", line 235, in non_max_suppression
output = [torch.zeros((0, 6 + nm), device=prediction.device)] * bs
RuntimeError: Trying to create tensor with negative dimension -941: [0, -941]
```

To overcome this problem, I included the following lines (https://github.com/ultralytics/ultralytics/pull/6477):

```
var_names = {0: 'person'}
model.predictor = model._smart_load("predictor")()
model.predictor.setup_model(model=model.model)
model.predictor.model.names = var_names
model.predictor.model.kpt_shape = [17, 3]
```

The problem is that when I infer the model `results = model.track(frame, device=0, conf=0.3, iou=0.5, persist=True)`, it doesn't track.

Any suggestions on how to fix the negative dimension problem so that I don't need to include these lines that cancel the track?

**Comment by glenn-jocher** [comment]
Hello!

Thank you for sharing the details of the issue you're encountering. It seems like the negative dimension error in `non_max_suppression` is quite peculiar. This typically suggests that there might be an unexpected value or computation happening before this function call.

To address this, I recommend checking the inputs to the `non_max_suppression` function. Ensure that the predictions being passed do not contain any unexpected negative values or shapes. This might involve adding some checks or print statements before this function is called to inspect the shape and content of the predictions.

As for the workaround you've implemented, it's a good temporary fix, but it seems to interfere with the tracking functionality. This might be due to how the model's configuration is being manually set, which could be overriding some necessary initial setup for tracking.

If possible, try to trace back to what changes in the predictions or model setup lead to the negative dimension issue without the manual intervention. This could provide a clue on a more permanent and less intrusive fix.

Let us know how it goes, or if you uncover any more insights that could help diagnose the issue further!

**Comment by karemdm** [comment]
From what I noticed, I need this temporary solution, the algorithm cannot read the parameters passed in the `config.pbtxt` file.
```
parameters: {
    key: "kpt_shape"
    value: {
        string_value: "[17, 3]"
    }
}
parameters: {
    key: "names"
    value: {
        string_value: "person"
    }
}
```

I would like to know how I can read this data and not need the solution mentioned above.

**Comment by glenn-jocher** [comment]
Hello!

Thank you for sharing your observations regarding the `config.pbtxt` file. It seems like the parameters you've defined aren't being recognized as expected by the Triton server.

To address this, you might need to ensure that the client code that loads and uses the model is explicitly reading these parameters. Depending on the client setup, you may need to modify the code to extract these parameters from the model's metadata and apply them accordingly.

If you haven't already, please review the section of the Triton documentation that discusses handling custom parameters for models. It provides guidance on how to properly configure and retrieve these values within your inference script.

Let us know if this helps or if you encounter any further issues!

**Comment by karemdm** [comment]
This is how the tracker for the yolov8 pose is working:

```
var_names = {0: 'person'}
model.predictor = model._smart_load("predictor")(_callbacks=model.callbacks)
model.predictor.setup_model(model=model.model, verbose=False)
model.predictor.model.__dict__.update({"names": var_names, "kpt_shape": [17, 3]})
```

**Comment by glenn-jocher** [comment]
Hello!

Thank you for sharing your approach to configuring the tracker for YOLOv8 pose. It looks like you've found a method to manually set the necessary parameters directly in the model's dictionary. This is a clever workaround!

Just ensure that this setup aligns with your application's requirements and maintains stability during your tracking tasks. If you encounter any further issues or have more insights to share, please feel free to continue the discussion here.

Happy tracking! 😊

**Comment by zhanghx0905** [comment]
Hi, thanks for sharing your thoughts. I'm using YOLOv8 for instance segmentation with triton inference server.
I'm experiencing the exact same issue as you mentioned for YOLOv8-Pose. So is the key to solving the problem passing in `(_callbacks=model.callbacks)`, isn't it?
Thanks, I'm going to try that.

**Comment by glenn-jocher** [comment]
Hi there,

Thank you for reaching out and sharing your experience with YOLOv8 and Triton Inference Server. It sounds like you're encountering a similar issue with instance segmentation as described for YOLOv8-Pose.

Yes, incorporating `(_callbacks=model.callbacks)` in your setup can indeed help address the issue. Here's a snippet to illustrate how you might integrate this:

```python
var_names = {0: 'person'}
model.predictor = model._smart_load("predictor")(_callbacks=model.callbacks)
model.predictor.setup_model(model=model.model, verbose=False)
model.predictor.model.__dict__.update({"names": var_names, "kpt_shape": [17, 3]})
```

This approach ensures that the necessary parameters are correctly set up, allowing the model to function as expected.

If you continue to experience issues, please ensure you are using the latest versions of `torch` and `ultralytics`. If the problem persists, providing a minimum reproducible code example would be very helpful for us to investigate further. You can find more details on creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to try this out and let us know how it goes! 😊
