### ISSUE TITLE
Instance Segmentation 

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#11774]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Instance Segmentation 
How to achieve minimum mask bounding rectangle
Want the implementation of green boxes

![a](https://github.com/ultralytics/ultralytics/assets/6490927/9b7787f1-c3ed-48e7-a370-3eb80aa1e73c)

Not considering obb
Sometimes the recognition effect is not very good
So I want to use Instance Segmentation
But I'm not sure how to handle the mask

```python

from ultralytics import YOLO

# Load a model
model = YOLO('yolov8s-seg.pt')  # pretrained YOLOv8n model

# Run batched inference on a list of images
results = model(['im1.jpg', 'im2.jpg'])  # return a list of Results objects

# Process results list
for result in results:
    boxes = result.boxes  # Boxes object for bounding box outputs
    masks = result.masks  # Masks object for segmentation masks outputs

```

**Comment by glenn-jocher** [comment]
@monkeycc hello! 👋 To achieve the minimum bounding rectangle from instance segmentation masks, you can follow this approach:

1. **Convert Masks to Binary**: Each mask should be a binary array where the mask is 1s and the background is 0s.
2. **Find Contours**: Utilize OpenCV's `findContours` to extract the contours from these binary masks.
3. **Bounding Rectangle**: Use OpenCV's `boundingRect` to get the smallest rectangle that fits around the detected contour.

Here's a code snippet to guide you:

```python
import cv2
import numpy as np

for result in results:
    masks = result.masks.numpy()  # Ensure masks are in numpy array
    for i, mask in enumerate(masks):
        # Find contours
        contours, _ = cv2.findContours(mask.astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        # Get the bounding rectangle and draw it
        if contours:
            x, y, w, h = cv2.boundingRect(contours[0])
            # Now (x, y, w, h) is the rectangle, draw using cv2.rectangle or store it for later use
```

Ensure that each mask is processed individually to draw or calculate its specific bounding rectangle. If you require further customization or clarification, feel free to ask. Happy coding! 🚀

**Comment by monkeycc** [comment]
```python
    masks = result.masks.numpy()  # Ensure masks are in numpy array
  File "E:\anaconda3\envs\intsoft_310\lib\site-packages\ultralytics\engine\results.py", line 47, in numpy
    return self if isinstance(self.data, np.ndarray) else self.__class__(self.data.numpy(), self.orig_shape)
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```
1. Unable to obtain mask data for YOLOv8
2. x, y, w, h=cv2. boundingRect (boundaries [0]) is a mask rectangle and cannot be drawn as a rectangular box on the original image

**Comment by glenn-jocher** [comment]
Hey there! It looks like you're encountering an issue where you can't directly convert a CUDA tensor to a numpy array. Let's fix that! You just need to move your tensor to CPU memory first. Here's how you can update your code:

```python
    masks = result.masks.cpu().numpy()  # Move tensor to CPU, then convert to numpy
```

Regarding your second issue, once you have the bounding box coordinates `(x, y, w, h)`, you can draw this rectangle on your original image using OpenCV. Make sure the image and the masks are aligned in size. Here's a quick example how you can draw the rectangle:

```python
    cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 2)  # Draw rectangle in green
```
Just replace `img` with your actual image array.

Hopefully, this helps! Let me know if you have any more questions! 🌟

**Comment by monkeycc** [comment]
```PYTHON
for result in results:
    masks = result.masks.cpu().numpy()  # Move tensor to CPU, then convert to numpy

```



'Masks' object has no attribute 'xy'. See valid attributes below.

    A class for storing and manipulating detection masks.

    Attributes:
        xy (list): A list of segments in pixel coordinates.
        xyn (list): A list of normalized segments.

    Methods:
        cpu(): Returns the masks tensor on CPU memory.
        numpy(): Returns the masks tensor as a numpy array.
        cuda(): Returns the masks tensor on GPU memory.
        to(device, dtype): Returns the masks tensor with the specified device and dtype.

**Comment by glenn-jocher** [comment]
Hello 👋! It looks like there was a little mix-up with attribute names in the `Masks` object. The attributes you've mentioned, `xy` and `xyn`, don't exist directly on the `Masks` object itself as attributes. Instead, they are properties you can access for specific functionalities.

Here's a corrected snippet demonstrating how you might access and utilize the 'masks' data:

```python
for result in results:
    # Ensure masks are on CPU and converted to numpy arrays
    masks = result.masks.cpu().numpy()

    # Example usage: process each mask
    for mask in masks:
        # use mask directly depending on your requirement
        process_mask(mask)
```

If you need to work with the mask data directly, you should call `.cpu().numpy()` as you did to convert the tensor before processing it further!

Let me know if this helps or if you have any more questions! 🚀

**Comment by monkeycc** [comment]
Useless

```
'Masks' object has no attribute 'xy'. See valid attributes below.

    A class for storing and manipulating detection masks.

    Attributes:
        xy (list): A list of segments in pixel coordinates.
        xyn (list): A list of normalized segments.

    Methods:
        cpu(): Returns the masks tensor on CPU memory.
        numpy(): Returns the masks tensor as a numpy array.
        cuda(): Returns the masks tensor on GPU memory.
        to(device, dtype): Returns the masks tensor with the specified device and dtype.
```

**Comment by glenn-jocher** [comment]
Hello! 👋 It looks like there’s been a bit of confusion. The `Masks` object doesn't have `xy` or `xyn` attributes exposed directly for use. Instead, these properties are part of the underlying handlers for the mask data. Here’s a specific way you can directly work with the masks from the `Results` object:

```python
for result in results:
    masks = result.masks.cpu().numpy()  # Get masks as a numpy array on CPU
    for mask in masks:
        # Process each mask (example: just a placeholder function)
        process_mask(mask)
```
This code snippet demonstrates how you can retrieve the masks and then deal with them according to your needs.

Let me know if this helps or if there's anything else you'd like to know!

**Comment by volks73** [comment]
Hello! I was experiencing the same problem and trying to feed the segmentation results into OpenCV's `findContours` function. I am using Ultralytics v8.2.17. Using this code:

```python
for result in results:
    masks = result.masks.cpu().numpy()
    for mask in masks:
        print(f"mask={mask}")
```

I would receive the same error as @monkeycc:

```
'Masks' object has no attribute 'xy'. See valid attributes below.

    A class for storing and manipulating detection masks.

    Attributes:
        xy (list): A list of segments in pixel coordinates.
        xyn (list): A list of normalized segments.

    Methods:
        cpu(): Returns the masks tensor on CPU memory.
        numpy(): Returns the masks tensor as a numpy array.
        cuda(): Returns the masks tensor on GPU memory.
        to(device, dtype): Returns the masks tensor with the specified device and dtype.
```

I was able to get it to work with the following modifications:

```python
for result in results:
     masks = results.masks.cpu()
     for mask in masks:
         chw_mask = mask.data.numpy().astype(np.uint8)
         hwc_mask = np.transpose(chw_mask, (1, 2, 0))
         contours, _ = cv2.findContours(hwc_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
         print(contours)
```

It appears the `numpy()` function does not work at the "Masks" class and it must be used on the `data` property. This is weird because the `numpy()` method is doing `self.data.numpy()`. I am not familiar with the `Results` architecture to go much further than this.

Another issue was the numpy array is in Channel-Height-Width (CHW) order/shape, while OpenCV is expecting Height-Width-Channel (HWC) order.

**Comment by kisstea** [comment]
> Hello! I was experiencing the same problem and trying to feed the segmentation results into OpenCV's `findContours` function. I am using Ultralytics v8.2.17. Using this code:
> 
> ```python
> for result in results:
>     masks = result.masks.cpu().numpy()
>     for mask in masks:
>         print(f"mask={mask}")
> ```
> 
> I would receive the same error as @monkeycc:
> 
> ```
> 'Masks' object has no attribute 'xy'. See valid attributes below.
> 
>     A class for storing and manipulating detection masks.
> 
>     Attributes:
>         xy (list): A list of segments in pixel coordinates.
>         xyn (list): A list of normalized segments.
> 
>     Methods:
>         cpu(): Returns the masks tensor on CPU memory.
>         numpy(): Returns the masks tensor as a numpy array.
>         cuda(): Returns the masks tensor on GPU memory.
>         to(device, dtype): Returns the masks tensor with the specified device and dtype.
> ```
> 
> I was able to get it to work with the following modifications:
> 
> ```python
> for result in results:
>      masks = results.masks.cpu()
>      for mask in masks:
>          chw_mask = mask.data.numpy().astype(np.uint8)
>          hwc_mask = np.transpose(chw_mask, (1, 2, 0))
>          contours, _ = cv2.findContours(hwc_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
>          print(contours)
> ```
> 
> It appears the `numpy()` function does not work at the "Masks" class and it must be used on the `data` property. This is weird because the `numpy()` method is doing `self.data.numpy()`. I am not familiar with the `Results` architecture to go much further than this.
> 
> Another issue was the numpy array is in Channel-Height-Width (CHW) order/shape, while OpenCV is expecting Height-Width-Channel (HWC) order.

masks are n * w * h , n is the number of objects, each mask is 1 * w * h
