### ISSUE TITLE
使用yolov8 :print(results.pandas().xyxy[0]) AttributeError: 'list' object has no attribute 'pandas'

### ISSUE THREAD

**Issue by systembreakdown** [ultralytics/ultralytics#11770]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\pythonProject1\HW5 Single Degree of Freedom System Response.py", line 28, in <module>
    print(results.pandas().xyxy[0])
AttributeError: 'list' object has no attribute 'pandas'

### Minimal Reproducible Example

# 导入必要的库
from ultralytics import YOLO  # YOLO模型
from PIL import Image  # 用于图像处理的库
import cv2  # 用于视频处理的OpenCV库
import glob  # 用于文件路径匹配的库

# 指定预训练模型文件的路径
model_path = 'C:/Users/User/PycharmProjects/pythonProject1/V11.pt'

# 指定图片目录路径
image_directory_path = 'C:/charuco800-600'

# 加载YOLO模型
model = YOLO(model_path)

# 使用glob库获取指定目录下所有的.jpg文件路径
image_paths = glob.glob(f'{image_directory_path}/*.jpg')

# 对获取的图片路径列表进行遍历进行预测
for image_path in image_paths:
    # 显示正在处理的图片路径
    print(f'正在处理图片: {image_path}')

    # 进行预测，并显示结果
    results = model.predict(source=image_path, show=True)

    # 打印预测得到的包含边界框、得分、类别的详细信息
    print(results.pandas().xyxy[0])

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! It looks like you're trying to call `.pandas()` on a `list` of `Results` object directly, which is the cause of the error. The `.pandas()` method should be called on each individual `Results` object in the list. Here’s how you can fix your loop:

```python
# 对获取的图片路径列表进行遍历进行预测
for image_path in image_paths:
    print(f'正在处理图片: {image_path}')
    
    # 进行预测
    results = model.predict(source=image_path, show=True)
    
    # Ensure `results` is not a list to use `.pandas()`
    if isinstance(results, list):
        results = results[0]

    # 打印预测得到的包含边界框、得分、类别的详细信息
    print(results.pandas().xyxy[0])
```

Make sure the model predict call (`model.predict()`) returns individual `Results` objects. Adjust the example as needed based on if your model call returns a list or a single `Results` object. If the list contains multiple `Results` objects (for example, if predicting on batches), you'll need to handle each `Results` object in the list.
