### ISSUE TITLE
Why set the coordinates of keypoints with confidence less than 0.5 to 0?

### ISSUE THREAD

**Issue by kleopard** [ultralytics/ultralytics#11799]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In lines 590 to 592 of the `https://github.com/ultralytics/ultralytics/tree/main/ultralytics/engine/results.py`, you set the coordinates of keypoints with confidence less than 0.5 to 0. 
The specific code is as follows:
```python
if keypoints.shape[2] == 3:  # x, y, conf
    mask = keypoints[..., 2] < 0.5  # points with conf < 0.5 (not visible)
    keypoints[..., :2][mask] = 0
```
What is the reason for doing this?

**Comment by glenn-jocher** [comment]
The thresholding of keypoints with a confidence of less than 0.5 to coordinates of 0 is a method to enhance the reliability of the keypoints detected by the model. Here, keypoints with low confidence are typically considered unreliable or 'not visible,' thus setting them to 0 helps in disregarding these points for further processing or analysis.

This implementation effectively filters out less confident detections, ensuring that only keypoints with a reasonably high confidence influence downstream tasks, such as pose estimation, thereby improving accuracy and robustness of results.

If keypoint precision is crucial for your application and you wish to handle low confidence keypoints differently, consider adjusting the confidence threshold or modifying how such keypoints are utilized in your workflow. Here's how you might adjust the confidence threshold:

```python
confidence_threshold = 0.3  # Example threshold
mask = keypoints[..., 2] < confidence_threshold
keypoints[..., :2][mask] = 0
```

I hope this clarifies your query! 😊

**Comment by sronilsson** [comment]
Hey! I just bumped into this one - what would be the reasons for not defaulting to 0.5 and exposing this parameter at predict?

**Comment by glenn-jocher** [comment]
Good question—thanks for raising it. We keep the 0.5 cutoff internal to `Results.Keypoints` as a simple, consistent “visibility” default and to avoid adding yet another CLI arg to `predict`; raw confidences are still available so users can apply any policy in post-processing. You can verify the behavior and available accessors in the Keypoints docs, including `xy/xyn` and `conf` properties, in [Keypoints in Results](https://docs.ultralytics.com/reference/engine/results/#ultralytics.engine.results.Keypoints), and note that plotting already exposes its own `conf_thres` in [plotting.kpts](https://docs.ultralytics.com/reference/utils/plotting/#kpts). If you’d like this to be a user-facing option, please open a small feature request or PR proposing an optional override (e.g., `keypoint_vis_thres`) so we can discuss scope.

**Comment by sronilsson** [comment]
Thanks @glenn-jocher makes sense. just for context: not using CLI, I ran .predict() with 0.5 confidence for months, wrongly assuming was applied independently to both bboxes and keypoints. When use cases expanded and others manipulated conf, I noticed changes only affected bbox data. Long thought I had a bug in my wrapper code, until I found this line in source.

**Comment by Y-T-G** [comment]
This is no longer the case in the latest version. The keypoints are no longer zeroed.

**Comment by sronilsson** [comment]
Ah thanks @Y-T-G good to know 👍
