### ISSUE TITLE
IndexError for YOLOWorld model in LVIS and Objects365 datasets

### ISSUE THREAD

**Issue by abionics** [ultralytics/ultralytics#11809]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val

### Bug

There is an `IndexError` error in `metrics` module while validating YOLOWorld model. I take this [code from docs](https://docs.ultralytics.com/models/yolo-world/#val-usage) and change dataset to another. See minimal reproducible example bellow

### Environment

```python
>>> ultralytics.checks()
Ultralytics YOLOv8.2.11 🚀 Python-3.10.12 torch-2.3.0+cu121 CUDA:0 (NVIDIA A100 80GB PCIe, 81051MiB)
Setup complete ✅ (24 CPUs, 216.2 GB RAM, 11.3/61.8 GB disk)
# Ubuntu 22.04.3 LTS
# Python 3.10.12
```

### Minimal Reproducible Example

```python
>>> from ultralytics import YOLOWorld
>>> model = YOLOWorld('yolov8s-worldv2.pt')
>>> metrics = model.val(data='lvis.yaml')
Ultralytics YOLOv8.2.11 🚀 Python-3.10.12 torch-2.3.0+cu121 CUDA:0 (NVIDIA A100 80GB PCIe, 81051MiB)
YOLOv8s-worldv2 summary (fused): 195 layers, 12749288 parameters, 509208 gradients, 50.8 GFLOPs

Dataset 'lvis.yaml' images not found ⚠️, missing path '/storage/YOLO-WORLD/datasets/lvis/val.txt'
Downloading https://github.com/ultralytics/yolov5/releases/download/v1.0/lvis-labels-segments.zip to '/storage/YOLO-WORLD/datasets/lvis-labels-segments.zip'...
Unzipping /storage/YOLO-WORLD/datasets/lvis-labels-segments.zip to /storage/YOLO-WORLD/datasets/lvis...: 100%
Downloading http://images.cocodataset.org/zips/train2017.zip to '/storage/YOLO-WORLD/datasets/lvis/images/train2017.zip'...
Downloading http://images.cocodataset.org/zips/test2017.zip to '/storage/YOLO-WORLD/datasets/lvis/images/test2017.zip'...
Downloading http://images.cocodataset.org/zips/val2017.zip to '/storage/YOLO-WORLD/datasets/lvis/images/val2017.zip'...
Dataset download success ✅ (362.1s), saved to /storage/YOLO-WORLD/datasets

val: Scanning /storage/YOLO-WORLD/datasets/lvis/labels/train2017... 19626 images, 0 backgrounds, 0 corrupt: 100%
val: New cache created: /storage/YOLO-WORLD/datasets/lvis/labels/train2017.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/1227 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/storage/YOLO-WORLD/venv/lib/python3.10/site-packages/ultralytics/engine/model.py", line 527, in val
    validator(model=self.model)
  File "/storage/YOLO-WORLD/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/storage/YOLO-WORLD/venv/lib/python3.10/site-packages/ultralytics/engine/validator.py", line 189, in __call__
    self.update_metrics(preds, batch)
  File "/storage/YOLO-WORLD/venv/lib/python3.10/site-packages/ultralytics/models/yolo/detect/val.py", line 152, in update_metrics
    self.confusion_matrix.process_batch(predn, bbox, cls)
  File "/storage/YOLO-WORLD/venv/lib/python3.10/site-packages/ultralytics/utils/metrics.py", line 366, in process_batch
    self.matrix[detection_classes[m1[j]], gc] += 1  # correct
IndexError: index 961 is out of bounds for axis 1 with size 81
```

### Additional

Objects365 dataset has the same issue, but it will take forever to download. The exception in this case will be:
```python
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/5000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/storage/YOLO-WORLD/venv/lib/python3.10/site-packages/ultralytics/engine/model.py", line 527, in val
    validator(model=self.model)
  File "/storage/YOLO-WORLD/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/storage/YOLO-WORLD/venv/lib/python3.10/site-packages/ultralytics/engine/validator.py", line 189, in __call__
    self.update_metrics(preds, batch)
  File "/storage/YOLO-WORLD/venv/lib/python3.10/site-packages/ultralytics/models/yolo/detect/val.py", line 152, in update_metrics
    self.confusion_matrix.process_batch(predn, bbox, cls)
  File "/storage/YOLO-WORLD/venv/lib/python3.10/site-packages/ultralytics/utils/metrics.py", line 366, in process_batch
    self.matrix[detection_classes[m1[j]], gc] += 1  # correct
IndexError: index 109 is out of bounds for axis 1 with size 81
```

Some related issues:
https://github.com/ultralytics/ultralytics/issues/866#issuecomment-1441473192
https://github.com/ultralytics/ultralytics/issues/2937

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
It looks like the `IndexError` you're encountering is due to a mismatch between the number of classes in your model and the class indices in your dataset labels. The error indicates that the class index in the dataset exceeds the size of your model's output tensor specific for classes.

One common reason this can happen is if the dataset configuration does not properly match the number of classes your model was trained on. Ensure your `lvis.yaml` and `Objects365.yaml` files have the correct `nc` (number of classes) specified, and that it matches the number of classes the YOLOWorld model expects.

Here's an example of what the dataset configuration might need to include:

```yaml
# Example dataset configuration entry
nc: 123   # number of classes
names: ['class1', 'class2', ..., 'class123']
```

Make sure this configuration aligns with your model's training conditions. If you continue to experience issues, consider re-verifying the dataset class indices and the associated class labels in your training setup.

**Comment by abionics** [comment]
@glenn-jocher I take default build-in datasets (see [lvis.yaml](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/datasets/lvis.yaml) and [Objects365.yaml](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/datasets/Objects365.yaml)). They don't have `nc` param in their description

The reason is that YOLOWorld (V2) model by default has classes from COCO dataset. The following code helps me to run validation on another datasets:
```python
from ultralytics import YOLOWorld
model = YOLOWorld('yolov8s-worldv2.pt')
model.set_classes(["Person", "Car", ...])  # include here a list of classes from lvis.yaml
# see https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/datasets/lvis.yaml#L17-L1223
metrics = model.val(data='lvis.yaml')
```

**Comment by glenn-jocher** [comment]
Hi @abionics! 👋 It looks like you've found a good workaround by manually setting the class labels to match the dataset. This is indeed necessary when the dataset configuration does not specify the `nc` parameter and the model's default class set differs from the dataset you're using.

For future reference, ensuring that the model's class settings align with the dataset's classes, as you've done, is key when switching between datasets not originally configured for the specific model. Your approach to explicitly set the classes is spot on! 🎯

If you encounter any more issues or have further questions, feel free to ask. Happy coding! 🚀
