### ISSUE TITLE
Issue with Running Yolo V8 Offline (No internet connection)

### ISSUE THREAD

**Issue by luckystar2794** [ultralytics/ultralytics#1180]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi there, I would like to understand if it is possible to disable this connection while using yolov8 offline? There's no issue when I connect my wifi and execute it, however after I switch off my wifi all this error appear. Any way I can work around it? Thanks in advance for any advice!

Best Regards
Eason

`Exception in thread Thread-13:
Traceback (most recent call last):
  File "C:\Users\Anaconda3\envs\yolov8\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Anaconda3\envs\yolov8\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\Anaconda3\envs\yolov8\lib\socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed`

**Comment by glenn-jocher** [comment]
@luckystar2794 hi there! You should be able to use YOLO offline with no problems. I'm not able to reproduce any issues locally when I disconnect from the internet, i.e. all tests run correctly. 

Do you know what file or function is causing this problem inside the repo and how we can reproduce it? Thanks!

**Comment by luckystar2794** [comment]
Hi @glenn-jocher , what I did to reproduce the issue was to enable and disable the prediction under no internet connection from my laptop. I am using the same yolov8 from your repo.
`results = model.predict(source=img_path)`

Below is my setting for the configuration while using yolov8 weight
`parser = argparse.ArgumentParser()
parser.add_argument('--weights', nargs='+', type=str, default='./weights/best.pt', help='model.pt path(s)')
parser.add_argument('--source', type=str, default=f'inference/images', help='source')  # file/folder, 0 for webcam
parser.add_argument('--output', type=str, default='inference/output', help='output folder')  # output folder
parser.add_argument('--img-size', type=int, default=416, help='inference size (pixels)')
parser.add_argument('--conf-thres', type=float, default=0.5, help='object confidence threshold')
parser.add_argument('--iou-thres', type=float, default=0.5, help='IOU threshold for NMS')
parser.add_argument('--device', default='cpu', help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
parser.add_argument('--view-img', action='store_true', help='display results')
parser.add_argument('--save-txt', action='store_true', help='save results to *.txt')
parser.add_argument('--classes', nargs='+', type=int, help='filter by class: --class 0, or --class 0 2 3')
parser.add_argument('--agnostic-nms', action='store_true', help='class-agnostic NMS')
parser.add_argument('--augment', action='store_true', help='augmented inference')
parser.add_argument('--update', action='store_true', help='update all models')
opt = parser.parse_args()
opt.conf_thres = 0.25
# model = attempt_load(opt.weights, map_location=opt.device)  # load FP32 model  # Allen
model = YOLO('best.pt')`

**Comment by luckystar2794** [comment]
> 

Could I also understand why does it need to create connection while running yolov8 structure offline?
Once I turn off my wifi, the error message appear

**Comment by AyushExel** [comment]
@glenn-jocher it seems either a windows specific network problem. It occurs on a separate thread so could it be related to the traces?

**Comment by luckystar2794** [comment]
I suspect is something to do with the utils.py but I'll look into it again

**Comment by luckystar2794** [comment]
Thanks @AyushExel and @glenn-jocher , I've resolved it. It was due to one of the utils file sending analytic data to ultralytics hence result in the error under no internet connection.

Cheers!
Best Regards
Eason

**Comment by glenn-jocher** [comment]
@luckystar2794 hmm got it! I'll double check those to make sure they are disabled when offline.

**Comment by AaronRustad** [comment]
> Thanks @AyushExel and @glenn-jocher , I've resolved it. It was due to one of the utils file sending analytic data to ultralytics hence result in the error under no internet connection.

What analytics are being sent to Ultralytics? While I don't mind sharing my personal usage of the product, my company might have a problem with it.  Is it possible to turn it off completely regardless of whether we're online or off?

**Comment by glenn-jocher** [comment]
@AaronRustad anonymized crashes and usage analytics are aggregated to help us debug problems faster. You can opt-out by settings `sync: False` in your settings.yaml. 

I'm working on easier settings.yaml updates, but for now you'll have to edit the file manually. You can see the location and settings with `yolo settings`

**Comment by BenMaslen** [comment]
I have downloaded the latest version of yolo (as of today), and set sync: false in the settings.yaml file, yet am still getting the same connection errors. I am trying to run on a HPC which does not have access to the internet and hence is giving me connection errors. Do you know which util files specifically try to connect to the internet so I can try turning it off there?

_requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/ultralytics/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1554bc05fbe0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))_

**Comment by glenn-jocher** [comment]
@BenMaslen oh interesting. This probably originates on a version check run prior to training to make users aware of ultralytics updates:

https://github.com/ultralytics/ultralytics/blob/9e58c32c15835e54e57f7b8c925367a64cb94951/ultralytics/yolo/utils/checks.py#L137-L151

**Comment by glenn-jocher** [comment]
@BenMaslen checked some more, and this pypi check only runs if the environment is online. Maybe your package is out of date, you should try updating it and see if the problem persists:

https://github.com/ultralytics/ultralytics/blob/9e58c32c15835e54e57f7b8c925367a64cb94951/ultralytics/yolo/engine/model.py#L156-L162

If I disconnect from WiFi and train a model this function is never called.

**Comment by BenMaslen** [comment]
Hi @glenn-jocher tried updating pypi, but didn't help things. When I removed the package version check in ultralytics/ultralytics/yolo/utils/checks.py (and just replaced with return False), it was able to run though!

**Comment by glenn-jocher** [comment]
@BenMaslen got it. I've implemented a fix in https://github.com/ultralytics/ultralytics/pull/1347/commits/2bb178a253d24f76af3926566311f356ed8b4619 that should go out this week.

**Comment by Arshadoid** [comment]
Hi, I was wondering if the issue I'm having is related to this problem.
FYI I cloned the latest repo and just using ultralytics folder without installation in HPC.  
Currently getting below error:

`
Traceback (most recent call last):
  File "/home/arshad/.local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/arshad/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/arshad/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arshad/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/arshad/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/arshad/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/arshad/.local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/arshad/.local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x2b7096cdf1c0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arshad/.local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/arshad/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/arshad/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/ultralytics/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b7096cdf1c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/6054799/arshad/YOLO/ultralytics/yolov8_train_TTPLA.py", line 5, in <module>
    model.train(data='dataset_TTPLA.yaml', epochs=2, imgsz=640, batch=4)
  File "/project/6054799/arshad/YOLO/ultralytics/ultralytics/yolo/engine/model.py", line 311, in train
    check_pip_update_available()
  File "/project/6054799/arshad/YOLO/ultralytics/ultralytics/yolo/utils/checks.py", line 147, in check_pip_update_available
    latest = check_latest_pypi_version()
  File "/project/6054799/arshad/YOLO/ultralytics/ultralytics/yolo/utils/checks.py", line 131, in check_latest_pypi_version
    response = requests.get(f'https://pypi.org/pypi/{package_name}/json')
  File "/home/arshad/.local/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/arshad/.local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/arshad/.local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/arshad/.local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/arshad/.local/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/ultralytics/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b7096cdf1c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
`

**Comment by Arshadoid** [comment]
Hi @glenn-jocher I was able to solve the previous issue (the previous comment)  by setting ONLINE= FALSE, and now I get this output. Seems like it's still trying to connect. Could you please suggest any workaround for this. 


```
Ultralytics YOLOv8.0.58 ðŸš€ Python-3.9.6 torch-1.13.1 CUDA:0 (Tesla P100-PCIE-12GB, 12198MiB)
[34m[1myolo/engine/trainer: [0mtask=segment, mode=train, model=yolov8x-seg.pt, data=dataset_TTPLA.yaml, epochs=2, patience=50, batch=4, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=/project/6054799/arshad/YOLO/ultralytics/runs/segment/train
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments                     
  0                  -1  1      2320  ultralytics.nn.modules.Conv                  [3, 80, 3, 2]                 
  1                  -1  1    115520  ultralytics.nn.modules.Conv                  [80, 160, 3, 2]               
  2                  -1  3    436800  ultralytics.nn.modules.C2f                   [160, 160, 3, True]           
  3                  -1  1    461440  ultralytics.nn.modules.Conv                  [160, 320, 3, 2]              
  4                  -1  6   3281920  ultralytics.nn.modules.C2f                   [320, 320, 6, True]           
  5                  -1  1   1844480  ultralytics.nn.modules.Conv                  [320, 640, 3, 2]              
  6                  -1  6  13117440  ultralytics.nn.modules.C2f                   [640, 640, 6, True]           
  7                  -1  1   3687680  ultralytics.nn.modules.Conv                  [640, 640, 3, 2]              
  8                  -1  3   6969600  ultralytics.nn.modules.C2f                   [640, 640, 3, True]           
  9                  -1  1   1025920  ultralytics.nn.modules.SPPF                  [640, 640, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]                           
 12                  -1  3   7379200  ultralytics.nn.modules.C2f                   [1280, 640, 3]                
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]                           
 15                  -1  3   1948800  ultralytics.nn.modules.C2f                   [960, 320, 3]                 
 16                  -1  1    922240  ultralytics.nn.modules.Conv                  [320, 320, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]                           
 18                  -1  3   7174400  ultralytics.nn.modules.C2f                   [960, 640, 3]                 
 19                  -1  1   3687680  ultralytics.nn.modules.Conv                  [640, 640, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]                           
 21                  -1  3   7379200  ultralytics.nn.modules.C2f                   [1280, 640, 3]                
 22        [15, 18, 21]  1  12317171  ultralytics.nn.modules.Segment               [1, 32, 320, [320, 640, 640]] 
YOLOv8x-seg summary: 401 layers, 71751811 parameters, 71751795 gradients, 344.5 GFLOPs

Transferred 651/657 items from pretrained weights
[34m[1mAMP: [0mrunning Automatic Mixed Precision (AMP) checks with YOLOv8n...
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to yolov8n.pt...
âš ï¸ Download failure, retrying 1/3 https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt...
```

**Comment by glenn-jocher** [comment]
> 

In regards to this message, it seems that errors were not being handled correctly, so I'm implemented improvements in 8.0.60 for release tomorrow that should resolve this.

**Comment by glenn-jocher** [comment]
> Arshadoid

If there is no error then this can be ignored. If you are seeing an error when offline, please raise a new bug report, thank you.

**Comment by glenn-jocher** [comment]
> Hi @glenn-jocher I was able to solve the previous issue (the previous comment) by setting ONLINE= FALSE, and now I get this output. Seems like it's still trying to connect. Could you please suggest any workaround for this.
> 
> ```
> Ultralytics YOLOv8.0.58 ðŸš€ Python-3.9.6 torch-1.13.1 CUDA:0 (Tesla P100-PCIE-12GB, 12198MiB)
> �[34m�[1myolo/engine/trainer: �[0mtask=segment, mode=train, model=yolov8x-seg.pt, data=dataset_TTPLA.yaml, epochs=2, patience=50, batch=4, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=/project/6054799/arshad/YOLO/ultralytics/runs/segment/train
> Overriding model.yaml nc=80 with nc=1
> 
>                    from  n    params  module                                       arguments                     
>   0                  -1  1      2320  ultralytics.nn.modules.Conv                  [3, 80, 3, 2]                 
>   1                  -1  1    115520  ultralytics.nn.modules.Conv                  [80, 160, 3, 2]               
>   2                  -1  3    436800  ultralytics.nn.modules.C2f                   [160, 160, 3, True]           
>   3                  -1  1    461440  ultralytics.nn.modules.Conv                  [160, 320, 3, 2]              
>   4                  -1  6   3281920  ultralytics.nn.modules.C2f                   [320, 320, 6, True]           
>   5                  -1  1   1844480  ultralytics.nn.modules.Conv                  [320, 640, 3, 2]              
>   6                  -1  6  13117440  ultralytics.nn.modules.C2f                   [640, 640, 6, True]           
>   7                  -1  1   3687680  ultralytics.nn.modules.Conv                  [640, 640, 3, 2]              
>   8                  -1  3   6969600  ultralytics.nn.modules.C2f                   [640, 640, 3, True]           
>   9                  -1  1   1025920  ultralytics.nn.modules.SPPF                  [640, 640, 5]                 
>  10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
>  11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]                           
>  12                  -1  3   7379200  ultralytics.nn.modules.C2f                   [1280, 640, 3]                
>  13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
>  14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]                           
>  15                  -1  3   1948800  ultralytics.nn.modules.C2f                   [960, 320, 3]                 
>  16                  -1  1    922240  ultralytics.nn.modules.Conv                  [320, 320, 3, 2]              
>  17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]                           
>  18                  -1  3   7174400  ultralytics.nn.modules.C2f                   [960, 640, 3]                 
>  19                  -1  1   3687680  ultralytics.nn.modules.Conv                  [640, 640, 3, 2]              
>  20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]                           
>  21                  -1  3   7379200  ultralytics.nn.modules.C2f                   [1280, 640, 3]                
>  22        [15, 18, 21]  1  12317171  ultralytics.nn.modules.Segment               [1, 32, 320, [320, 640, 640]] 
> YOLOv8x-seg summary: 401 layers, 71751811 parameters, 71751795 gradients, 344.5 GFLOPs
> 
> Transferred 651/657 items from pretrained weights
> �[34m�[1mAMP: �[0mrunning Automatic Mixed Precision (AMP) checks with YOLOv8n...
> Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to yolov8n.pt...
> âš ï¸� Download failure, retrying 1/3 https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt...
> ```

If there is no error then this can be ignored. If you are seeing an error when offline, please raise a new bug report, thank you.
