### ISSUE TITLE
Output ID when using Tracking

### ISSUE THREAD

**Issue by skhavari** [ultralytics/ultralytics#1181]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Unless I am overlooking something, I don't see a way for ID's to be output when using `yolo track` (the tracking added in #1022).  Should the IDs be included when `save_text=TRUE`? Thanks!

**Comment by glenn-jocher** [comment]
@skhavari yes that's correct, there are no outputs from yolo CLI commands for track IDs. You may want to create a python script for this and they should be included in `Results` objects. See https://docs.ultralytics.com/tasks/tracking/

**Comment by Cristofhersj** [comment]
I had the same question, where exactly in the code for the tracking the id is assigned? That would make easier to create a script for printing the ID with all the other information

**Comment by Laughing-q** [comment]
@Cristofhersj you can get the id by the follow script:
```python
results = model.track(source=..., stream=True)
for result in results:
    id = result.boxes.id
```

**Comment by ChaoYuanNMFC** [comment]
@Laughing-q I have the same question as above. I want to know which file should I add this script to. Is that possible we add another column in the output file (from save_txt) showing tracking ID, along with the category and other information.

**Comment by Laughing-q** [comment]
@ChaoYuanNMFC you probably need to modify this line [https://github.com/ultralytics/ultralytics/blob/3861e6c82aaa1bbb214f020ece3a4bd4712eacbe/ultralytics/yolo/v8/detect/predict.py#L68-L69](https://github.com/ultralytics/ultralytics/blob/3861e6c82aaa1bbb214f020ece3a4bd4712eacbe/ultralytics/yolo/v8/detect/predict.py#L68-L69)
add `d.id` in the saving line.

**Comment by ryouchinsa** [comment]
[RectLabel](https://rectlabel.com) is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel, you can save a track id for each box, using an attribute of "Text input" type and combine with the object name such as "sneakers-1", the attribute name should be set as "track id" on the setting.
For the YOLO Detection Track format, see the [CVAT document](https://docs.cvat.ai/docs/manual/advanced/formats/format-yolo-ultralytics/).

```
class_index center_x center_y width height track_id
0 0.464615 0.594724 0.680000 0.769784 1
```

<video src="https://github.com/user-attachments/assets/d752055e-6ec8-4879-a170-e468e59182ec" controls="controls" muted="muted" class="width-fit" style="max-height:640px; min-height: 200px"></video>

**Comment by glenn-jocher** [comment]
Thank you for sharing this annotation approach with track IDs! For Ultralytics YOLO tracking implementations, we recommend using the native `results.boxes.id` property shown in our [Object Tracking documentation](https://docs.ultralytics.com/modes/track/). The ID is automatically generated during inference when using `model.track()`, and can be accessed programmatically or integrated into output formats through our Python API.
