### ISSUE TITLE
Adding a FC layer to Yolov8?

### ISSUE THREAD

**Issue by luhgit** [ultralytics/ultralytics#1183]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, 
I have some numerical data in addition to image data so I was planning to feed this numerical information to the yolov8 network by adding an FC layer. Has anyone tried to achieve that?
Thanks.

**Comment by glenn-jocher** [comment]
@luhgit Yes, it is possible to feed numerical data to YOLOv8 network by adding an FC layer. This is commonly known as a fusion approach where the features from different sources are combined to improve the performance of the network. However, it's important to note that this requires modifying the architecture of the YOLOv8 network and retraining it with the new input.

**Comment by luhgit** [comment]
@glenn-jocher: Could you please point me to some docs on modifying yolov8 architecture to fuse this additional input?

**Comment by MohamedAtef321** [comment]
> @glenn-jocher: Could you please point me to some docs on modifying yolov8 architecture to fuse this additional input?

+1

**Comment by MohamedAtef321** [comment]
> @glenn-jocher: Could you please point me to some docs on modifying yolov8 architecture to fuse this additional input?

heey, is that what you are looking for ?
https://github.com/ultralytics/ultralytics/tree/3861e6c82aaa1bbb214f020ece3a4bd4712eacbe/ultralytics/models/v8
