### ISSUE TITLE
NMS default behavior

### ISSUE THREAD

**Issue by deepukr007** [ultralytics/ultralytics#11847]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I see that in args.yaml file nms is False by deafult , does this mean  NMS is not appplied while training ?
Or am I missing something ?

**Comment by glenn-jocher** [comment]
@deepukr007 hello,

Great question! By default, Non-Maximum Suppression (NMS) is not applied during the training phase (`nms=False`). NMS is typically used during the prediction or inference stage to refine the detection bounding boxes by removing overlaps and retaining only the most probable boxes. 

When `nms=False` in the configuration, it doesn't impact the model training but affects how detections are handled during prediction. If you need NMS during inference, you'd set `nms=True` in your configuration or explicitly enable it when you run predictions.

Hope that clears things up! 😊 If you have any more questions, feel free to ask.
