### ISSUE TITLE
Error when training Yolo-NAS

### ISSUE THREAD

**Issue by alvaro-lopes-daedalus** [ultralytics/ultralytics#11842]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I got a error when trying to train a  Yolo-NAS model, using the following code:

The error:

```python
  File "/root/yolov5/venv/lib/python3.10/site-packages/ultralytics/engine/model.py", line 647, in train
    "model": self.overrides["model"],
KeyError: 'model
```

I was able to train a YOLOv8 model using similar script.

### Minimal Reproducible Example

```python
from ultralytics import NAS

# Load a COCO-pretrained YOLO-NAS-s model
model = NAS('yolo_nas_s.pt')

# Validate the model on the COCO8 example dataset
results = model.train(data='dataset/data.yaml')
```

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by MarkhamLee** [comment]
YOLO-NAS is made by a different company, I think you're looking for this: https://github.com/Deci-AI/super-gradients/tree/master

**Comment by glenn-jocher** [comment]
Hi there! 

It looks like there's a bit of confusion about the YOLO-NAS models supported by Ultralytics. You can find documentation and support for YOLO-NAS directly from Ultralytics [here](https://docs.ultralytics.com/models/yolo-nas). If you have more questions or need further assistance, feel free to ask!

Happy coding! 😊

**Comment by MarkhamLee** [comment]
My bad, I deleted my prior comment to avoid creating more confusion.

**Comment by glenn-jocher** [comment]
@MarkhamLee no worries at all! If you have any more questions or need further clarification, feel free to ask. Happy to help! 😊

**Comment by alvaro-lopes-daedalus** [comment]
Hey guys, thank you for the reply.

From what I can see in the link that @glenn-jocher shared, ultralytics does not support **Training**. Correct?
Do you guys have any guidance on how I can train this model?

I believe that would be great to have a better error message when trying to use the method/task that the model doesn't support.

**Comment by glenn-jocher** [comment]
Hi there!

You're correct, the YOLO-NAS models currently do not support training directly through the Ultralytics framework. They are optimized for inference and validation tasks only.

For training similar models, you might consider using other YOLO models that support training, such as YOLOv8, which can be trained on custom datasets using the Ultralytics framework.

Regarding the error message, that's a great suggestion! Improving error handling to provide clearer messages would definitely enhance the user experience. We appreciate your feedback and will consider it for future updates.

If you need further assistance or have more suggestions, feel free to share! 😊
