### ISSUE TITLE
Unexpected slow training speed

### ISSUE THREAD

**Issue by Laughing-q** [ultralytics/ultralytics#11858]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Training process occasionally stutters and slowing down. The issue seems to be introduced by https://github.com/ultralytics/ultralytics/pull/11195.

### Environment

Linux

### Minimal Reproducible Example

The commit from the [PR](https://github.com/ultralytics/ultralytics/pull/11195):
```bash
git checkout dda78692
yolo train detect data=coco.yaml model=yolov8s.yaml batch=8
```
The training occasionally stuttered and eventually finished one epoch with 4mins:
![image](https://github.com/ultralytics/ultralytics/assets/61612323/74eefa67-c133-43be-8596-d5fa3a2ddb03)

The commit right before the PR:
```bash
git checkout 83510016
yolo train detect data=coco.yaml model=yolov8s.yaml batch=8
```
The training worked smoothly and finished one epoch with 2mins:
![image](https://github.com/ultralytics/ultralytics/assets/61612323/30abb76d-4623-42c5-8ca7-00a19f4eeda6)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@Burhan-Q Can you try to reproduce it on your system since currently our server is occupied? and please make a PR to revert the PR I mentioned if the strange slow down appears to you. Thanks!
I'll be off my system for next two days.

**Comment by Burhan-Q** [comment]
## Windows 10 COCO128 (main branch)

<details><summary>Training Command</summary>
<p>

```py
from ultralytics import YOLO
model = YOLO("yolov8n.pt")
results = model.train(data="coco128.yaml")
```

</p>
</details> 

Seems like the first few epochs were slow, but after that seemed quite normal to me.

![image](https://github.com/ultralytics/ultralytics/assets/62214284/3621221a-2c86-451a-9bad-a3c898bab15c)

## Linux COCO128 (main branch)

> [!NOTE]
> This machine has lower specs than the Windows 10 machine

<details><summary>Training command</summary>
<p>

```bash
yolo train detect data=coco128.yaml model=yolov8s.yaml batch=8
```

</p>
</details> 

![image](https://github.com/ultralytics/ultralytics/assets/62214284/670f332f-7105-454e-b082-dc2b869b91a7)

Again a little slower on the first few epochs, but overall not terrible training times or throughput / epoch (for this hardware).

**Comment by Burhan-Q** [comment]
For consistency, I also tested the CLI command on Windows and result is more or less the same. The first few epochs were a bit slow, but after that the training time seemed normal with a _bit_ higher throughput for each epoch (that the previous test).

```bash
yolo train detect data=coco128.yaml model=yolov8s.yaml batch=8
```

**Comment by Laughing-q** [comment]
@Burhan-Q got it! could you try with some larger dataset? i.e I was testing it using the val2017 go by 5000 images, since I figured a tiny dataset like coco128 might not get very different results.

**Comment by Burhan-Q** [comment]
@Laughing-q I'm working on running VisDrone now on both machines for 15 epochs. Will be able to post results soon.

**Comment by Burhan-Q** [comment]
## Summary

First epoch was a _bit_ slower than the rest, but overall seems pretty good. It's been a while since I've run a VisDrone training but I think (not certain) one epoch _used_ to take longer 

## Linux VisDrone (main branch)

```bash
yolo train detect data=VisDrone.yaml model=yolov8s.yaml batch=8 epochs=15
```

![image](https://github.com/ultralytics/ultralytics/assets/62214284/43c4f1ec-b2ed-4d05-a4fa-69cdd5c6b70d)

## Windows 10 VisDrone (main branch)

```bash
yolo train detect data=VisDrone.yaml model=yolov8s.yaml batch=8 epochs=15
```

![image](https://github.com/ultralytics/ultralytics/assets/62214284/7644d76d-3a6e-4562-bb54-04a56b0a3628)

**Comment by Burhan-Q** [comment]
@Laughing-q see results above ☝. I'm going to rerun VisDrone with `git checkout 83510016` to see if there's any difference on either system

**Comment by Burhan-Q** [comment]
## Summary

@Laughing-q using the same commands as before for training VisDrone, the results more or less look quite similar. On Windows 10, the per epoch speed is a little faster on the `main` branch (specifically after the dataloader mosaic closed), but the overall training time on `83510016` checkout was $0.001 \text{ hours}$ faster. The result on my Linux machine appear to be practically the same as from `main` (hasn't finished the full training yet so I can't speak on the overall time yet).

## Linux VisDrone (`83510016` checkout)

![image](https://github.com/ultralytics/ultralytics/assets/62214284/8421d7ad-afd9-4d3c-bb28-eb5c62908c54)

## Windows 10 VisDrone (`83510016` checkout)

![image](https://github.com/ultralytics/ultralytics/assets/62214284/6776b13d-e920-4745-9573-0ba0bd55fbdd)

**Comment by Laughing-q** [comment]
@Burhan-Q ok got it! much appreciate! so it looks like it's not reproducible to you. Might be the case related to my machine of something, let's leave this issue here for now. And perhaps pick it up again when there's similar issue reported by users. :)

**Comment by glenn-jocher** [comment]
@Laughing-q @Burhan-Q hey guys, thanks for the effort to reproduce here. 

I think since it's impacting one environment it's likely that it may be impacting others, though clearly not all. 

The original PR was opened to address train slowdowns ironically but that PR itself was not thoroughly tested in different environments so to be on the safe side I think we should revert for now and link to this issue in that original PR as the reason for reverting.

**Comment by Laughing-q** [comment]
@glenn-jocher make sense!
