### ISSUE TITLE
Monitor YOLOv8 training with Comet

### ISSUE THREAD

**Issue by erwanlenagard** [ultralytics/ultralytics#1187]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, 

Do you have any tutorial / documentation to monitor training with Comet ML ? 

I don't understand how to initialize properly Comet ML to manage my experiments on YOLOv8. By default, it creates a project "yolov8" and all my experiments are stored in this project. 

If I create a new experiment in another project, it stops the current experiment and add a new one in "yolov8" project. 

```
from comet_ml import Experiment
from ultralytics import YOLO

experiment = Experiment(project_name="NewProject")

model = YOLO("yolov8n.yaml") 
model = YOLO("yolov8n.pt")  
results = model.train(
                      "data.yaml",
                      epochs=3,
                      batch=16, 
                      imgsz=640, 
                      device=0,
                      plots=True, 
                      name="train_v1",
                      exist_ok=True,
                      cache=False,
                      save_period=1,
                      optimizer='SGD')
                     
experiment.end()
```

**Comment by glenn-jocher** [comment]
@erwanlenagard yes, Comet should be using the YOLOv8 `project` and `name` arguments to create experiments automatically for you, i.e. once you've logged into Comet:

```
yolo train project=PROJECT name=NAME
```

The code is here:
https://github.com/ultralytics/ultralytics/blob/a58f766f9433ca68a99242b50230260060228a78/ultralytics/yolo/utils/callbacks/comet.py#L14-L20

Looking at the above code though it appears that only the `project` argument is utilized.

**Comment by synthdatagit** [comment]
I am not able to log other images or artifacts other than the ones already mentioned in the callback.

How do I log e.g the confusion matrix or F1 curves?

**Comment by glenn-jocher** [comment]
@synthdatagit these should log automatically. If they aren't logging please update the Comet callbacks here in a PR and we can review there, thank you!

https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/utils/callbacks/comet.py

**Comment by lukasugar** [comment]
> @erwanlenagard yes, Comet should be using the YOLOv8 `project` and `name` arguments to create experiments automatically for you, i.e. once you've logged into Comet:

It seems that `name` is not used. Experiment name in Comet is randomly generated. Is it possible to set the Experiment name in Comet from YOLO's side? This would be a very nice feature to have!

Adding [this](https://www.comet.com/docs/v2/api-and-sdk/python-sdk/reference/Experiment/#experimentset_name) in `[ultralytics/ultralytics/yolo/utils/callbacks/comet.py](https://github.com/ultralytics/ultralytics/blob/a58f766f9433ca68a99242b50230260060228a78/ultralytics/yolo/utils/callbacks/comet.py#L14-L20)` should make this possible

**Comment by glenn-jocher** [comment]
@lukasugar Thank you for your suggestion. Currently, YOLOv8 uses the `project` parameter to set the project name in Comet. However, I understand that being able to set the `name` parameter directly from YOLOv8 would be a useful feature. We will investigate adding support for this in a future release.

As for the suggested code change, we appreciate the contribution but we need to ensure that any changes made to the repository follow certain guidelines and are thoroughly reviewed before merging. Therefore, I encourage you to open an issue on our GitHub repository proposing this change and detailing your pull request.

Thank you for using YOLOv8 and for your interest in improving it!

**Comment by dsblank** [comment]
@glenn-jocher @lukasugar At the time that model.train() has finished, the Comet experiment has ended and is no longer "alive". 

However, you can still access the experiment, and set the name by following up directly after the model.train() has completed with the following:

```python
import comet_ml
old_experiment = comet_ml.get_global_experiment()
experiment = comet_ml.ExistingExperiment(previous_experiment=old_experiment.id)
experiment.set_name("My New Name")
```

You can actually do quite a bit with an [ExistingExperiment()](https://www.comet.com/docs/v2/api-and-sdk/python-sdk/reference/ExistingExperiment/), including logging images, and additional information.

When you are done, you can issue `experiment.end()`

**Comment by glenn-jocher** [comment]
@dsblank Thank you for your question. You can access the Comet experiment and set its name by following up directly after `model.train()` has completed with the following:
```python
import comet_ml
old_experiment = comet_ml.get_global_experiment()
experiment = comet_ml.ExistingExperiment(previous_experiment=old_experiment.id)
experiment.set_name("My New Name")
```
From there you can do more with an `ExistingExperiment()`, including logging images and additional information. When you are done, you can call `experiment.end()` to end the experiment. 
I hope this helps. Let us know if you have any further questions or need additional assistance. Thank you for using YOLOv8!
