### ISSUE TITLE
Yolov5/6/7/8/9 int8 QAT training & onnx exporting 

### ISSUE THREAD

**Issue by DeeperNCheaper** [ultralytics/ultralytics#11871]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

INT8 model on nvidia gpu can increase 2x throughput. 
QAT can get more stable accuracy result of Int8 model than PTQ
So, we need the belows
- QAT Finetuning feature after normal training
- Exporting Onnx with Q/DQ layers
- Converting TensorRT engine with Int8 precision
- Benchmark test comparision

### Use case

For deploying faster model on GPU, they fine tune their datset with QAT, export and converting to tensorrt engine

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@DeeperNCheaper thanks for your feature request and for your willingness to contribute! Currently, YOLOv8 supports ONNX exporting, but it doesn't directly support exporting with Q/DQ layers or INT8 precision via Quantization Aware Training (QAT) out of the box.

For now, you can export the YOLOv8 model to ONNX and then use tools like NVIDIA's TensorRT for optimizing the model with INT8 precision. Here's a basic example of how to export a model to ONNX:

```bash
yolo export model=yolov8n.pt format=onnx
```

We appreciate your input on the potential performance gains and better accuracy with QAT. We consider such features based on community feedback and demand. If you're willing to start working on this integration, feel free to ping the maintainers for guidance in the PR or discussion section.

Looking forward to seeing your contributions! 🚀

**Comment by 904557558** [comment]
@DeeperNCheaper 

I desperately need this feature, can you tell me roughly how you changed the code?Thank you

**Comment by DeeperNCheaper** [comment]
If you need code snippet, please refer this my post series. 

I need time to code work for this PR. So I think you can read this posts first. 

It can help. Thanks. 

https://medium.com/@DeeperAndCheaper/quantization-yolov8-qat-x2-speed-up-on-your-jetson-orin-nano-1-why-quantization-e052a72c506d

**Comment by glenn-jocher** [comment]
Thanks for sharing your post series, @DeeperNCheaper! 🌟 It sounds like a great resource for the community. We appreciate your effort in preparing the PR and guiding others. If anyone has questions or needs further clarification, checking out these posts is a fantastic start. Looking forward to your contributions!

**Comment by djdll** [comment]
@DeeperNCheaper I checked the link of your article, but I still don't understand how to do QAT. Can you provide some source code to learn
