### ISSUE TITLE
Detect a specific person

### ISSUE THREAD

**Issue by biruwon** [ultralytics/ultralytics#1188]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am asking just to know if this is the right tool for the job as I am not sure. I am using yolov8 to detect people in a video which works perfectly. Then, I would like to actually know who are those people. I am thinking that maybe I should train my own model with a dataset of every person on that video.

- Is that the right thing to do? So every class would be a person's name
- Do you have any example of how to generate those dataset? As I can not find it in the docs.

### Additional

Edit: sorry, I am new to github discussion, so probably this should have been asked there. Let me know, and I will close this one

**Comment by bit-scientist** [comment]
Detecting a specifc person would essentially be a recognition task. Person (people) recognition is a different topic to detection as it mainly focuses on person's facial features. You, of course, can try detection models like yolo for face detection (and recognition only if you have few people), however it totally depends on your specific use case.

**Comment by AyushExel** [comment]
Agreed @bit-scientist 

Another approach that I would try if you don't want to train another model is to use detection/segmentation embeddings from the pre-trained model and pass it to tracker and get an ID from it. But I think that'll require a reid version of the tracker which we don't currently have. But the non-reid version should give you a sense of things.

**Comment by biruwon** [comment]
> Detecting a specifc person would essentially be a recognition task. Person (people) recognition is a different topic to detection as it mainly focuses on person's facial features. You, of course, can try detection models like yolo for face detection (and recognition only if you have few people), however it totally depends on your specific use case.

@bit-scientist my use case is a video stream where multiple people are in. For example, imagine the US senate, or whatever country. To recognise all those people. Do you know any better alternative for that?

> Another approach that I would try if you don't want to train another model is to use detection/segmentation embeddings from the pre-trained model and pass it to tracker and get an ID from it. But I think that'll require a reid version of the tracker which we don't currently have. But the non-reid version should give you a sense of things.

But what I understood from the [tracking docs](https://docs.ultralytics.com/tasks/tracking/) is that you can follow up an object in a video, but it can not detect which object is. How would you compare that tracking ID to a face? I am not against training another model, but was not sure if by training a YOLO model with faces is the solution for this? So, I will have a class per person on that video?

**Comment by arad2022** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> ### Question
> I am asking just to know if this is the right tool for the job as I am not sure. I am using yolov8 to detect people in a video which works perfectly. Then, I would like to actually know who are those people. I am thinking that maybe I should train my own model with a dataset of every person on that video.
> 
> * Is that the right thing to do? So every class would be a person's name
> * Do you have any example of how to generate those dataset? As I can not find it in the docs.
> 
> ### Additional
> Edit: sorry, I am new to github discussion, so probably this should have been asked there. Let me know, and I will close this one

Hi there. I have the same questions and I'm looking for solutions about real-time face recognition. Did you find any answer for them?
