### ISSUE TITLE
TensorRT segmentation model inference Result object disapearing

### ISSUE THREAD

**Issue by guillermoecn** [ultralytics/ultralytics#1189]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Hello, im having some problems doing inference with TensorRT segmentation model, the first is that is giving me only boxes as output, and it disapears when i use it in my code.
![image](https://user-images.githubusercontent.com/106102260/221683513-29a25756-e2f8-4001-9d65-069065b038f0.png)

### Minimal Reproducible Example

import cv2
from pathlib import Path
import os
from ultralytics import YOLO

IMGS_PATH = r"C:\Users\Guillermo\Desktop\Guillermo Velazquez\GBB\SCRAP\segmentation\data\scrap_23feb\test\images"
path = Path(IMGS_PATH)
imgs = os.listdir(path)

img = cv2.imread(str(path / "20221125_160845_796_jpg.rf.d5c1fbd6c23a7593aeccf3dc12227a86.jpg"))

model = r"runs\segment\yolov8s-seg_imgsz416_bs4_50ep_23feb\weights\best.engine"

model = YOLO(model)
results = model(img, verbose=False)
print(results[0].boxes.xyxy[0].int().tolist())
print(results)
print(results)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@guillermoecn I tried this with a PyTorch model and everyting works correctly, i.e.:

<img width="764" alt="Screenshot 2023-02-27 at 16 38 30" src="https://user-images.githubusercontent.com/26833433/221721972-1f2db1d6-ff8d-464e-a027-b8bedb6caa83.png">

If you have no results maybe your model is not detecting anything?

**Comment by glenn-jocher** [comment]
@guillermoecn if you can provide a reproducible example using a common model on a common image, i.e. YOLOv8n-seg on bus.jpg please let us know, otherwise there's nothing for us to do since we can't reproduce this.

**Comment by glenn-jocher** [comment]
@guillermoecn tested with engine also, no problems:

<img width="715" alt="Screenshot 2023-02-27 at 16 52 53" src="https://user-images.githubusercontent.com/26833433/221723808-88518e4e-d4ef-438f-8c1e-c54b04227a2c.png">
