### ISSUE TITLE
How to use model.val() on dataset test part

### ISSUE THREAD

**Issue by TrinityNeo99** [ultralytics/ultralytics#1190]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Dear author, I want to evaluate models on test set, however, model.val() only works on validate set, I read the docs using the argument "split" but it doesn't work.
![image](https://user-images.githubusercontent.com/49897919/221743405-229400e6-3516-4aaf-864c-5854d6c0fae0.png)
![image](https://user-images.githubusercontent.com/49897919/221743254-74a54c10-d8fd-4f85-b999-6f586b9ce14c.png)
Thanks a lot.

**Comment by glenn-jocher** [comment]
@TrinityNeo99 it looks like your code is out of date, just update your pip package with `pip install -U ultralytics` and this should work.

Let us know if this solves your issue!
