### ISSUE TITLE
NoneType' object has no attribute 'segments'

### ISSUE THREAD

**Issue by rvbabera** [ultralytics/ultralytics#1191]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained yolov8n-seg.pt model for my custom dataset while getting segmentation mask data from results i get this error

Traceback (most recent call last):
  File "1_predict.py", line 196, in <module>
    masks = masks.segments
AttributeError: 'NoneType' object has no attribute 'segments'

**Comment by Laughing-q** [comment]
@rvbabera please provide the command or the script you were using.

**Comment by rvbabera** [comment]
It was giving this error when there was no object detected in results now i fixed that with checking len(result) 
my script was 
`
results = model.predict("img.jpg", 0.7)

for result in results:
    boxes = result.boxes
    masks = result.masks
    masks = masks.segments
`

now i did it like

`
results = model.predict("img.jpg", 0.7)

for result in results:
    if(len(result) < 1):
        continue
    boxes = result.boxes
    masks = result.masks
    masks = masks.segments
`

**Comment by pderrenger** [comment]
@rvbabera got it! It looks like you resolved the issue by adding a check for the length of the result before accessing the masks. Feel free to reach out if you need any further assistance with YOLOv8! 😊
