### ISSUE TITLE
Bug: The expanded size of the tensor (4) must match the existing size (5) at non-singleton dimension 0

### ISSUE THREAD

**Issue by wangss533** [ultralytics/ultralytics#1195]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello！ After serveral epochs training，the bug was showed as following. What's the reason resulting the problem? Thanks for your response!
![image](https://user-images.githubusercontent.com/40136816/221795633-65a4c0df-a37a-4b76-88e3-f99a9254d0ff.png)

**Comment by glenn-jocher** [comment]
@wangss533 hi! Thanks for the bug report. To diagnose a problem we need to be able to reproduce it on our side. If this happens with a common dataset like COCO128 please provide us exact code to reproduce, i.e.:

```
yolo train data=coco128.yaml seed=0
```

**Comment by wangss533** [comment]
Ok! I used the my own dataset. I trained with DDP and 4 GPUs. When the total data numbers were 1331, the batch-size 256, the problem ocurred after several epochs. However, when the data numbers changed to 1280 and batch-size was 256, the program was able to  run normally. Whether the total data numbers should be n times of batch-size, as 5 (1280/256) times I set.

**Comment by wangss533** [comment]
Sorry to bother you. I found  this bug  was caused by the function 'torch.unique'. This function can work well in CPU device, but it would bring problem in GPU server. I do not sure if it is an issue with my operating environment in GPU server. When I replaced this function, the program was able to run normally  in GPU server.

**Comment by pderrenger** [comment]
@wangss533 thank you for the update! It's great to hear that you were able to identify the issue. It seems like there might be a compatibility issue with the 'torch.unique' function on your GPU server. By replacing the function, you were able to overcome the problem. If you encounter any more issues or have any further questions, feel free to reach out!
