### ISSUE TITLE
Disabling check_pip_update() in an offline environment

### ISSUE THREAD

**Issue by limwenyao** [ultralytics/ultralytics#1196]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am running yolov8 installed within a container. I am running the container in a non-internet environment. It is installed with the requirements.txt and ultralytics pip library, and a local copy of yolov8m.pt. I have a simple train.py file:

``` python
from ultralytics import YOLO
model = YOLO("yolov8m.pt")
model.train(data="coco.yaml", imgsz=640)
```

In the training logs, I can see that initialization of ultralytics/yolo/engine/model.py includes self._check_pip_update() and the code fails here as I do not have access to pip repo in this environment. Is there arguments we can use rather than commenting out the line in the source code?
```
Traceback (most recent call last):
  File "train/main.py", line 19, in <module>
    model.train(data="coco.yaml",
  File "/usr/local/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 301, in train
    self._check_pip_update()
  File "/usr/local/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 161, in _check_pip_update
    check_pip_update()
  File "/usr/local/lib/python3.8/site-packages/ultralytics/yolo/utils/checks.py", line 139, in check_pip_update
    latest = check_latest_pypi_version()
  File "/usr/local/lib/python3.8/site-packages/ultralytics/yolo/utils/checks.py", line 131, in check_latest_pypi_version
    response = requests.get(f'https://pypi.org/pypi/{package_name}/json')
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/ultralytics/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f41e5b159d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Comment by glenn-jocher** [comment]
@limwenyao ah, thanks for the bug report! We have a new global `ONLINE` variable in `ultralytics.yolo.utils` we can use to disable this. I've made a fix that uses this in https://github.com/ultralytics/ultralytics/pull/1197, which should go out in 8.0.49 today.

**Comment by YOLOLover** [comment]
```
import importlib
import ultralytics.hub.utils as hub_utils

# Directly modify the ONLINE attribute of the hub_utils module
hub_utils.ONLINE = False

# Reload the module to ensure the change takes effect
importlib.reload(hub_utils)

# Now, import other modules from ultralytics
from ultralytics import RTDETR, YOLO
from pathlib import Path

```

Made this change however it doesnt seems to work.

**Comment by glenn-jocher** [comment]
@YOLOLover apologies for the confusion. The `ONLINE` variable should be set in `ultralytics.yolo.utils`, not `ultralytics.hub.utils`. Please set `ultralytics.yolo.utils.ONLINE = False` before importing the `YOLO` class. This should resolve the issue. If the problem persists after making this change, please let us know.
