### ISSUE TITLE
How to use partial weights from a pre-trained model?

### ISSUE THREAD

**Issue by LingsiDS** [ultralytics/ultralytics#1199]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

If I want to use partial weight from a pretrained model.
In YOLOv5, when I remove some blocks, and use commond as follow
```python train.py  --data data.yaml --cfg yolov5s_removed.yaml --img 640--weights ./yolov5s.pt ```

In the log, we can see
> Transferred 306/311 items from yolov5s.pt
It looks like the weight of the unchanged part is reused. Am I understanding this right?

**But how can I reuse the weight of unchanged part from a pretrained model like yolov8s.pt?**
```python
model = YOLO("yolov8s_removed.yaml")
model = YOLO("yolov8s.pt")  # It seems to **override** the model definition from yolov8s.pt
```
or In CLI
args: model either xxx.pt file or xxx.yml file
Whether it is possible to specify the model structure and then **load the weights from another place**

**Comment by glenn-jocher** [comment]
@LingsiDS this is not currently possible. You can pass a YAML or a *.pt file for training.

**Comment by phoawb** [comment]
@LingsiDS This is very much late in the game, but it is possible to do partial transferring of weights by going through PyTorch: 


```python
import torch
from ultralytics import YOLO

# load custom model architecture
model = YOLO("yolo11n-global_context.yaml")

# load pre-trained weights for the base model (requires that you have them downloaded locally beforehand)
pretrained_dict = torch.load("yolo11n.pt")["model"].state_dict()

# extract randomly initialised custom model weights
model_dict = model.state_dict()

# make both dict keys on the same format. The keys for the model dict was on the format "model.model" for some reason
pretrained_dict = {f"model.{k}": v for k, v in pretrained_dict.items()}

# Filter out weights with matching names and shapes
filtered_dict = {k: v for k, v in pretrained_dict.items() if k in model_dict and v.shape == model_dict[k].shape}

# Print stats to verify
print(f"Pretrained weights available: {len(pretrained_dict)}")
print(f"Model weights needed: {len(model_dict)}")
print(f"Weights transferred: {len(filtered_dict)}")


# Update model weights
model_dict.update(filtered_dict)
model.load_state_dict(model_dict, strict=False)

```

This should selectively load the pre-trained weights while preserving your original model architecture.
