### ISSUE TITLE
shortcut in backbone and neck

### ISSUE THREAD

**Issue by yang-0201** [ultralytics/ultralytics#1200]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I noticed that in yolov5 and yolov8, the C3 module and C3f module of the backbone network both use shortcut, but in the neck structure uniformly do not use shortcut, what is the reason for this, is it more accurate if the neck is not used?

**Comment by glenn-jocher** [comment]
@yang-0201 in general all architecture choices like the one mention above are guided by empirical results, i.e. trial and error experiments for what works best.
