### ISSUE TITLE
How to decrease the time of detection when the target is small and stable?

### ISSUE THREAD

**Issue by 00ffcc** [ultralytics/ultralytics#1202]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to search for a small figure with stable size(16 * 16) and shape. Is there anyway to do it fast (maybe within 100ms)? I think this task is too simple to yolov8.
btw, my image's sive is 1280*720, so I train my model with yolov8n.pt,imgsz=1280. It works but it's too slow (600ms for one detection, opencv.dnn, cpp, onnx). The figure is so small that I can't simply let imgsz=640 (which will greatly decrease the recall rate).

**Comment by 00ffcc** [comment]
I try to replace yolov8n.pt with yolov8n.yaml since I only need to search for one simple figure. But the recall rate is still 0 after 1000 epochs😒. Should I continue to do this?

**Comment by yash-khurana** [comment]
Maybe try modifying the architecture a bit? Remove a few layers? Maybe someone with more expertise can comment how to do that

**Comment by pderrenger** [comment]
@yash-khurana hey there! 🌟 Modifying the architecture can indeed help with speeding up the detection for small, stable targets. You can try optimizing the architecture by removing some layers or adjusting the model's hyperparameters. Also, considering the specialized nature of your task, tuning the model to better suit your specific requirements might be beneficial. Feel free to experiment with the architecture and let us know how it goes! If you encounter any challenges or need further assistance, don't hesitate to ask. Good luck with your experiments!
