### ISSUE TITLE
Save crops without bounding box

### ISSUE THREAD

**Issue by brianspiesman** [ultralytics/ultralytics#1203]
Is there a way to save cropped images without the bounding box? I tried setting the line_thickness=0, box=False, hide_labels=False, and hide_conf=False but I'm still seeing the colored bounding box at the edges of my cropped images. Am I missing something?

Thanks for any help!

**Comment by glenn-jocher** [comment]
@brianspiesman code to reproduce?

I don't see crops anywhere with `yolo predict save_crop`
<img width="1445" alt="Screenshot 2023-02-28 at 13 35 45" src="https://user-images.githubusercontent.com/26833433/221986098-23e19539-9b93-470d-8e6b-2a3a17a5f8f8.png">

**Comment by Laughing-q** [comment]
@brianspiesman this could be a bug we had already solved, please use the latest version and try again. :)
