### ISSUE TITLE
Cannot Avoid Number of Classes Override When Instantiating YOLO with Classification YAML

### ISSUE THREAD

**Issue by paulguerrie** [ultralytics/ultralytics#1205]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Hey @glenn-jocher ! I'm trying to instantiate a classification model using `YOLO` and a yaml file.  When I load it like this: `model = YOLO(yaml_file)` I see this output: `Overriding model.yaml nc=3 with nc=1000`.  I looked at the code in `ultralytics/nn/tasks` for `ClassificationModel` and it looks like if you provide a yaml, `nc` will always get overridden by the default value `1000`.  And since you can't pass `nc` to the `YOLO` constructor, you can't load a classification model and maintain the correct number of classes.  Am I missing something here?

For a fix, I would suggest either:

1. Add `nc` as an optional parameter to `YOLO` that gets passed to the model instantiation in `_new()`
2. Set the default value of `nc=None` in the `ClassificationModel` so that it only gets overridden if `nc` is provided.

I'd be happy to make a PR for either of these if you agree with my assessment.

Edit: I went ahead and created the PRs for both options above.  I think option 1 is the better option. 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@paulguerrie closing as PR merged :)
