### ISSUE TITLE
Cannot release Gpu Memory after detect training

### ISSUE THREAD

**Issue by max82645235** [ultralytics/ultralytics#1207]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I need to use yolov8 train  in a long-running python application, application use yolov8 with  torch.
What confused me was when I finished my detect train function call, there has some gpu  memory cannot release,
I tried a few solutions, such as  torch.cuda.empty_cache(), but  can not work.
My question is when I finish calling, how to clean up Gpu Memory 
`
 train_config = {
               "model":"yolov8s.pt",
                "data": data_yaml,
                "epochs": meta.epochs,
                "imgsz": meta.imageSize,
                "batch": batch_size,
                "device": format(",".join(yaml_config['yolo']['device'])),
                "project": user_base_dir,
                "name": meta.businessId,
                "image_weights": meta.imageWeightOpen,
                "exist_ok": True,
 }

    yolo_model = ultralytics.YOLO(model=train_config['model'])

    yolo_model.train(**train_config)

    torch.cuda.empty_cache()

    print(torch.cuda.memory_summary())
`
<img width="994" alt="image" src="https://user-images.githubusercontent.com/7369375/222026561-47334e78-a341-4f12-85d9-e84066ce879a.png">

### Environment

- YOLO: Ultralytics YOLOv8.0.43 🚀 Python-3.8.13 torch-1.12.1 CUDA:1 (NVIDIA GeForce RTX 3080, 10018MiB)
- OS: Ubuntu 20.04
- Python: 3.8.10

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@max82645235 we haven't evaluated CUDA usage after training in long running python environments. Have you tried simply deleting the model in memory, i.e. `del model`?

**Comment by max82645235** [comment]
hi, @glenn-jocher 
I tried to do so, but the single card training still could not be released. My solution now is to open the child process and put the training service in it for execution. When the training is completed, the memory can be released normally.

`

def yolo_model_train(config: typing.Dict):
    ...
    yolo_model = ultralytics.YOLO(model=train_config['model'])
    yolo_model.train(**train_config)

    # end function


 trainProcess = torch.multiprocessing.Process(target=yolo_model_train,
                                                                 args=(json.loads(train_config),))
                    trainProcess.name = "yoloTrainProcess"
                    trainProcess.start()
                    trainProcess.join()
`

**Comment by glenn-jocher** [comment]
@max82645235 oh that's strange. I didn't know torch had a torch.multiprocessing library. Why not just use a Python daemon thread?
