### ISSUE TITLE
tensorflow SavedModel

### ISSUE THREAD

**Issue by shba007** [ultralytics/ultralytics#1209]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

when loading model in tensorflow

WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.

### Minimal Reproducible Example

Simply export the model in save_model format and import it in tensorflow

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@shba007 hi there! Please raise an issue on the onnx2tf repository with this question, and we export to ONNX and then use onnx2tf for all TF exports. Let us know if we need any changes on our side! Thanks.

https://github.com/PINTO0309/onnx2tf
