### ISSUE TITLE
Ultralytics: HTTP Error 404: Not Found 

### ISSUE THREAD

**Issue by u1353279** [ultralytics/ultralytics#1212]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I'm trying to use the ultralytics hub for training in colab, when i use teh api key given via Ultralytics hub  i get this error

![Screenshot 2023-03-01 105633](https://user-images.githubusercontent.com/59260499/222120024-0097dbf2-5fae-426a-9904-6fe6b288d352.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@u1353279 that's strange. There may be a temporary connection issue. Can you retry your command with a new model and see if this persists?

**Comment by u1353279** [comment]
Yes it’s working now, thanks.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
