### ISSUE TITLE
Better evaluation results show.

### ISSUE THREAD

**Issue by sunmooncode** [ultralytics/ultralytics#12149]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Is it more reasonable to print the number of images for each category in the current evaluation script results, rather than uniformly printing the total number of evaluation images?

### Use case

This is the current result.
![image](https://github.com/ultralytics/ultralytics/assets/86471590/1d0ab787-f4cc-4c8e-9113-9a659edb9f04)

This is the modified result.
![image](https://github.com/ultralytics/ultralytics/assets/86471590/f728291c-1d9b-467c-9870-7ec2b3ddad3c)

### Additional

I am not sure if this optimization is beneficial.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! Thanks for contributing to the discussion with such thoughtful suggestions. 🌟

Displaying the number of images per category during evaluation sounds like a reasonable enhancement for gaining more granular insights into model performance across different classes. This can definitely help users better understand the specific areas where the model excels or requires more training data.

If you are willing to submit a PR for this feature, it would be a fantastic addition to the project. Please ensure your changes maintain the current functionality as an option, perhaps through a user-defined flag in the evaluation script. This way, users can choose the output format that best suits their needs.

Looking forward to seeing your contribution!

**Comment by sunmooncode** [comment]
@glenn-jocher I have implemented this feature and used the `per_class_img` parameter to select whether to output the number of images for each class. I would appreciate some suggestions for better parameter naming.

**Comment by glenn-jocher** [comment]
Hello @sunmooncode! Great to hear that you've implemented the feature. 🚀 For the parameter name, how about `detail_per_class`? It's concise and clearly indicates that additional details will be provided for each class. Let us know if you need further assistance!

**Comment by glenn-jocher** [comment]
@sunmooncode thanks for the update! Looking forward to your PR. If you need any help, just let us know! 😊
