### ISSUE TITLE
Segmentation training

### ISSUE THREAD

**Issue by martin0496** [ultralytics/ultralytics#1215]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to train the model on a custom dataset using segmentation mode. I am using the same dataset for object detection with the same data.yaml file .
I am receiving the following error : RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 272 but got size 0 for tensor number 1 in the list.

Do i need to change the format of the dataset or the yaml file if I am switching from detect to segment ?

**Comment by glenn-jocher** [comment]
@martin0496 Switching from object detection to segmentation requires a different format for the dataset and yaml file. In object detection mode, the dataset is expected to contain images with bounding box annotations, while in segmentation mode, the dataset is expected to contain images with corresponding segmentation masks. Therefore, you would need to create segmentation masks for your custom dataset and update your data.yaml file accordingly, specifying the path to the mask images. It is also important to ensure that the sizes of the tensors in the dataset match the expected input size of the model.

**Comment by martin0496** [comment]
Thank you for your reply. It is working now with the mask data.

**Comment by pderrenger** [comment]
@martin0496 you're welcome! Glad to hear that it's working now with the mask data. If you have any more questions or need further assistance, feel free to ask. Good luck with your segmentation training!
