### ISSUE TITLE
problem in predict yolov8

### ISSUE THREAD

**Issue by antigravity233** [ultralytics/ultralytics#12162]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question
Hello, i want predict my video in vehicle counting in jupyter notebook by follow tutorial in youtube and face this problem in
python predict.py model='best.pt' source='test4.mp4'
youtube link:https://www.youtube.com/watch?v=nkptX_vXJKo

[2024-05-11 13:55:22,816][root.tracker][INFO] - Loading weights from deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7... Done!

Ultralytics YOLOv8.2.12 ðŸš€ Python-3.11.5 torch-2.3.0+cpu CPU (13th Gen Intel Core(TM) i5-13450HX)
Model summary (fused): 268 layers, 43614318 parameters, 0 gradients, 164.9 GFLOPs
Error executing job with overrides: ["model='best.pt'", "source='test4.mp4'"]

Traceback (most recent call last):
  File "C:\Users\kingy\YOLOv8-DeepSORT-Object-Tracking-main\ultralytics\yolo\v8\detect\predict.py", line 250, in predict
    predictor()
  File "C:\Users\kingy\anaconda3\Lib\site-packages\ultralytics\engine\predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kingy\anaconda3\Lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "C:\Users\kingy\anaconda3\Lib\site-packages\ultralytics\engine\predictor.py", line 220, in stream_inference
    self.setup_source(source if source is not None else self.args.source)
  File "C:\Users\kingy\anaconda3\Lib\site-packages\ultralytics\engine\predictor.py", line 182, in setup_source
    self.imgsz = check_imgsz(self.args.imgsz, stride=self.model.stride, min_dim=2)  # check image size
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kingy\anaconda3\Lib\site-packages\ultralytics\utils\checks.py", line 147, in check_imgsz
    raise TypeError(
TypeError: 'imgsz=[640, 640]' is of invalid type ListConfig. Valid imgsz types are int i.e. 'imgsz=640' or list i.e. 'imgsz=[640,640]'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by glenn-jocher** [comment]
@antigravity233 hello! It seems like there's an issue with how the image size (`imgsz`) is being specified. Based on the error message, you should double-check the format of the `imgsz` parameter in your prediction command. 

From the error:
```
TypeError: 'imgsz=[640, 640]' is of invalid type ListConfig. Valid imgsz types are int i.e. 'imgsz=640' or list i.e. 'imgsz=[640,640]'
```

It suggests that the format should either be a single integer or a properly formatted list. Here’s an example of how you can format your command correctly:

```python
python predict.py model='best.pt' source='test4.mp4' imgsz=640
```
or
```python
python predict.py model='best.pt' source='test4.mp4' imgsz=[640,640]
```

Try adjusting this parameter, and it should resolve the issue you’re encountering. If the problem persists, ensure your model file `best.pt` is correctly pathed and accessible. Happy coding! 🚀
