### ISSUE TITLE
Albumentation don't give results

### ISSUE THREAD

**Issue by JasseurHadded1** [ultralytics/ultralytics#1222]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Hello,

I'm working on an object detection problem, I have wanted to use the albumentation augmentation but using it does not change anything in my training set! I'm not sure why I have that, I have searched here but couldn't find an answer!

I don't have segmentation labels, could this be the cause of the problem?

Thanks,

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@JasseurHadded1 please provide a minimum reproducible example.

**Comment by JasseurHadded1** [comment]
> @JasseurHadded1 please provide a minimum reproducible example.

Thanks for your answer, it was my error! I have found the solution
