### ISSUE TITLE
Where is the output list generated by model.predict() method?

### ISSUE THREAD

**Issue by yagnikposhiya** [ultralytics/ultralytics#1224]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![issue_1](https://user-images.githubusercontent.com/89079815/222209888-3242057a-4479-4757-8134-6d03172dd322.png)

Here, I'm using a pre-trained **yolov8l** model to find objects in a webcam live feed. I want to explicitly store in a local python variable the total **number of objects and the class name** returned in the form of list by **ultralytics.yolo.engine.results.Results**. I tried every conceivable combination of the code, but I was unable to obtain the explicit list that contained the total number of objects and pertinent classes. So, where is it situated **(formation of list)?**  so that I can extract number of objects and pertinent classes. 

### Additional

`import ultralytics`
`from ultralytics import YOLO`
`model = YOLO("yolov8l.pt")`
`model.predict(source="0", show=False)`

This is the code I'm playing with.

**Comment by AyushExel** [comment]
You can interact with results like mentioned in the docs -> https://docs.ultralytics.com/predict/
You can access the predictions, classes and all the things needed to calculate the information

**Comment by oriaj3** [comment]
In my code I'm calculating that data manually, I get all the labels of the found objects and then I go through it to count each type of object. If you want I could pass you my code.

**Comment by yagnikposhiya** [comment]
> You can interact with results like mentioned in the docs -> https://docs.ultralytics.com/predict/ You can access the predictions, classes and all the things needed to calculate the information

Link is not working !!!

**Comment by oriaj3** [comment]
> Here is the link, but if you go to the main documentation website and browse through it you will find everything you need. 
https://docs.ultralytics.com/modes/predict/

https://docs.ultralytics.com/

**Comment by yagnikposhiya** [comment]
> > 
> 
> > > You can interact with results like mentioned in the docs -> https://docs.ultralytics.com/predict/ You can access the predictions, classes and all the things needed to calculate the information
> > 
> > 
> > Link is not working !!!
> 
> Here is the link, but if you go to the main documentation website and browse through it you will find everything you need. https://docs.ultralytics.com/modes/predict/ https://docs.ultralytics.com/

```
import ultralytics
from ultralytics import YOLO
import cv2

model = YOLO("yolov8l.pt")
img = cv2.imread("bus.jpg")
print("starting 1")
result = model(img)
print("ending 1")

for i in result:
    print("starting 2")
    print(i.probs)
    print("ending 2")
```

I have tried this code from the docs. And i want to print the probability of the detected object but it is returning the "None" in the output.

![Screenshot from 2023-03-17 20-00-51](https://user-images.githubusercontent.com/89079815/225934315-ff4735a0-6c9c-4362-9da5-8034c2e591e6.png)

**Comment by dige-mothership** [comment]
@oriaj3 The problem seems to be that you guys are printing to `stderr` instead of `stdout`. 
Working:
`results=$(yolo predict model=yolov8n.pt source='168.jpg' device=4 2>&1) 
echo "..................."
echo $results
echo "why"`

Not working:

`
results=$(yolo predict model=yolov8n.pt source='168.jpg' device=4) 
echo "..................."
echo $results
echo "why"
`

**Comment by dige-mothership** [comment]
`results=$(yolo predict model=yolov8n.pt source='i1.jpg' device=0 2>&1)
filtered_result=$(echo $number | sed 's/ persons//')
echo "$filtered_result"
`

**Comment by yagnikposhiya** [comment]
Thanks a lot !!!
It works ...

**Comment by glenn-jocher** [comment]
@yagnikposhiya you are welcome. I'm glad I could help. If you have any more questions or need further assistance, feel free to ask.

**Comment by yagnikposhiya** [comment]
@dige-mothership 

I'm trying to integrate the text to speech in the output of the YOLO model. So, basically if output of the model is "2 person, 1 bottle" then using text to speech, it will speak "2 person, 1 bottle". So, for the achievement of mentioned scenario, I have tried with python script and shell script (as you have suggested above) and it works greatly !!! **(for single image)**. now, I want to do the same thing **(want to apply text to speech)** when source is **"live video stream"**. So, how can I achieve that ?

**Comment by glenn-jocher** [comment]
@yagnikposhiya to apply text to speech for a live video stream, you can do the following:

1. Capture the frames from the live video stream using OpenCV capture.
2. Send the frames to the YOLOv8 model for object detection prediction.
3. Extract the labels and the corresponding confidence scores from the YOLOv8 results using detection results notations as shown in https://docs.ultralytics.com/predict/.
4. Concatenate the labels and the confidence scores into a formatted string.
5. Pass the concatenated string to your chosen text-to-speech API for a spoken output.
6. Repeat steps 2-5 indefinitely while the video stream is live.

You can find more information about text-to-speech APIs online, as there are multiple APIs available for Python.

**Comment by yagnikposhiya** [comment]
> @yagnikposhiya to apply text to speech for a live video stream, you can do the following:
> 
>     1. Capture the frames from the live video stream using OpenCV capture.
> 
>     2. Send the frames to the YOLOv8 model for object detection prediction.
> 
>     3. Extract the labels and the corresponding confidence scores from the YOLOv8 results using detection results notations as shown in https://docs.ultralytics.com/predict/.
> 
>     4. Concatenate the labels and the confidence scores into a formatted string.
> 
>     5. Pass the concatenated string to your chosen text-to-speech API for a spoken output.
> 
>     6. Repeat steps 2-5 indefinitely while the video stream is live.
> 
> 
> You can find more information about text-to-speech APIs online, as there are multiple APIs available for Python.

Thanks a lot!!! It works...

**Comment by glenn-jocher** [comment]
@yagnikposhiya you're welcome! I'm glad I could help. If you have any more questions or problems, feel free to ask.
