### ISSUE TITLE
Number of model parameters and FLOPs based on Ultralytics

### ISSUE THREAD

**Issue by melader111** [ultralytics/ultralytics#12254]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The YOLOv3-tiny model based on Ultralytics has a parameter count of 12.1M, but the official count is 8.7M; the YOLOv5n model  based on Ultralytics has a parameter count of 2.5M, but the official count is 1.9M. Should I use the Ultralytics-based model or the official model code to do comparison experiments for the YOLO series?

**Comment by glenn-jocher** [comment]
@melader111 hello!

In such cases where discrepancies occur in parameter counts between Ultralytics models and officially reported values, it typically involves how certain operations or layers are accounted, or potential enhancements made in our implementations.

For consistency in comparisons, especially in academic or controlled studies, I would recommend sticking with one source for all model implementations. If you're aiming for a comparison with official metrics and publications, using official model code and numbers might be easier to align with reported results.

However, if you're evaluating based on performance or integration capabilities, Ultralytics models are optimized for implementation and might provide practical advantages.

Hope this helps! 😊
