### ISSUE TITLE
Prediction on SAM Model doesn't support specifying classes to predict

### ISSUE THREAD

**Issue by zoltanmaric** [ultralytics/ultralytics#12275]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I'd like to run prediction using the `sam_b.pt` model only using a small subset of classes. Passing the `classes` parameter seems to have no effect though.

Is there a way to define the set of classes I'd like to predict (and ideally define names for them, which then get plotted, instead of the class indexes)?

### Environment

```bash
Ultralytics YOLOv8.2.8 🚀 Python-3.12.2 torch-2.2.1 CPU (Apple M1)
Setup complete ✅ (8 CPUs, 16.0 GB RAM, 216.0/228.3 GB disk)

OS                  macOS-14.5-arm64-arm-64bit
Environment         Darwin
Python              3.12.2
Install             pip
RAM                 16.00 GB
CPU                 Apple M1
CUDA                None

matplotlib          ✅ 3.8.3>=3.3.0
opencv-python       ✅ 4.9.0>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.2.1>=1.8.0
torchvision         ✅ 0.17.1>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.1>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
```

### Minimal Reproducible Example

```python
from ultralytics import SAM

model = SAM('sam_b.pt')
results = model.predict('[../test_images/wu-tang-trailer.jpg](https://www.rollingstone.com/wp-content/uploads/2023/01/wu-tang-trailer.jpg?w=1581&h=1054&crop=1)', classes=[1, 3, 6])
```

### Additional

I think one of the issues is that - unless I specify an override for bounding boxes, points, or masks, the model will always run the [`generate` function](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/models/sam/predict.py#L148), which [always sets `self.segment_all = True`](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/models/sam/predict.py#L251).

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@zoltanmaric hello!

Thank you for reaching out with your query. Currently, the SAM model in YOLOv8 doesn't directly support the `classes` parameter for limiting the range of classes detected during predictions. The behavior you observed is linked to how the SAM model is configured to handle predictions broadly, without filtering by specific classes post-training.

However, a potential workaround is to manually filter the output results after predictions are made. Here's a quick example of how you might do this:

```python
from ultralytics import SAM

model = SAM('sam_b.pt')
results = model.predict('path/to/image.jpg')
filtered_results = [r for r in results if r['class'] in (1, 3, 6)]
```

This approach involves filtering the results to include only the desired classes after the prediction has been run. While this isn't as efficient as direct class filtering in the predict function, it provides a method to achieve your goal.

We acknowledge the need for this feature and will consider it for future updates. If you have any more suggestions or need further assistance, feel free to ask.

Best regards!

**Comment by zoltanmaric** [comment]
Thanks @glenn-jocher.

Yeah, filtering the results after-the-fact is what I also did, but I noticed the SAM model is quite slow at inference (taking 2-5 minutes on a MacBook Air with an M1 processor), so I was hoping to speed it up some by restricting the number of classes it's looking for. Thanks anyway!

**Comment by glenn-jocher** [comment]
Hi @zoltanmaric,

Thanks for your follow-up! Indeed, filtering post-prediction isn't the most efficient for speed, especially with the SAM model's comprehensive segmentation capabilities. Currently, there isn't a built-in feature to limit classes pre-inference in the SAM model, which could indeed help speed things up as you mentioned.

As a potential alternative, you might consider using a more lightweight model if your use case permits, or exploring hardware acceleration options that could handle the SAM model's demands more effectively.

We appreciate your input and will keep it in mind for future updates to enhance performance and usability. Thanks for using Ultralytics YOLO! 🚀

Best regards!
