### ISSUE TITLE
object detection datasets: ImageNET 

### ISSUE THREAD

**Issue by dmddmd** [ultralytics/ultralytics#1227]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Can you provide an imageNET object detection dataset 
(with more than one image per label)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Classification task already supports imagenet dataset `yolo classify train data=imagenet`

**Comment by glenn-jocher** [comment]
@dmddmd yes I think you've confused tasks. ImageNet is for classification and COCO for detection.

**Comment by glenn-jocher** [comment]
@dmddmd see https://docs.ultralytics.com/tasks/classification/

![image](https://user-images.githubusercontent.com/26833433/222926093-619baf1b-05df-449e-a55f-722a611b2610.png)
