### ISSUE TITLE
Predict command makes an issue, after pulling latest commit

### ISSUE THREAD

**Issue by yellowjs0304** [ultralytics/ultralytics#1234]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thanks for the continuous updates.

I got an error when exporting the onnx, regarding this [issue](https://github.com/ultralytics/ultralytics/issues/866#issuecomment-1442672573).

So I needed to Pull latest commit, for fixing the onnx inference issue.

But after that, It got an CUDA issue. During inference multiple images, an issue occurs randomly.
```
File "/home/hjs/ultralytics/ultralytics/yolo/engine/predictor.py", line 191, in stream_inference
    s += self.write_results(i, self.results, (p, im, im0))
  File "/home/hjs/ultralytics/ultralytics/yolo/v8/segment/predict.py", line 74, in write_results
    self.annotator.masks(masks=mask.masks, colors=[colors(x, True) for x in det.cls], im_gpu=im_gpu)
  File "/home/hjs/ultralytics/ultralytics/yolo/utils/plotting.py", line 125, in masks
    mcs = (masks_color * inv_alph_masks).sum(0) * 2  # mask color summand shape(n,h,w,3)
RuntimeError: CUDA out of memory. Tried to allocate 1.70 GiB (GPU 0; 23.69 GiB total capacity; 6.44 GiB already allocated; 151.62 MiB free; 9.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```
I didn't have this issue before pull, in same GPU.
I used below command.

```
CUDA_VISIBLE_DEVICES=3 yolo task=segment mode=predict model=mybest.pt(best.onnx) source="./data/myimages/" imgsz=640 workers=2 device=\'0\' save conf=0.5 retina_masks=True
```
Also, the when i use the "save" option in onnx inference command, the results is saved in wrong directory.
Before pulling, the results made in same task(in my case, it's segment) But, now It made sub-dir in "detect"
![image](https://user-images.githubusercontent.com/30281608/222367641-40139079-b6d7-4efb-a1bf-eda08a97e1c2.png)

Could you tell me the solution?

**Comment by glenn-jocher** [comment]
@yellowjs0304 your model is a detect model, but you've passed task=segment, so task=segment is ignored. This is what the warnings show you in your console printout.

```
yolo task=segment mode=predict imgsz=640 save conf=0.5 retina_masks=True 

WARNING ⚠️ 'model' is missing. Using default 'model=yolov8n.pt'.
WARNING ⚠️ conflicting 'task=segment' passed with 'task=detect' model. Ignoring 'task=segment' and updating to 'task=detect' to match model.
WARNING ⚠️ 'source' is missing. Using default 'source=/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets'.
Ultralytics YOLOv8.0.50 🚀 Python-3.10.6 torch-1.13.1 CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

image 1/2 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus.jpg: 640x480 3 persons, 1 bus, 100.6ms
image 2/2 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/zidane.jpg: 384x640 2 persons, 39.0ms
Speed: 2.6ms preprocess, 69.8ms inference, 2.9ms postprocess per image at shape (1, 3, 640, 640)
Results saved to /Users/glennjocher/PycharmProjects/ultralytics/runs/detect/predict
```

**Comment by glenn-jocher** [comment]
Also you don't need extra characters around device, and you don't need to pass CUDA_VISIBLE_DEVICES, just pass device=3 directly to yolo

**Comment by yellowjs0304** [comment]
@glenn-jocher No.. I think something is wrong in latest commit. 

As you can see, it's the segmentation task. Not detection results. The results are made in "detect" folder, Not "segment" folder. 
Of course, no warning also.
<img width="981" alt="image" src="https://user-images.githubusercontent.com/30281608/222960278-83b8a4e9-bf79-40f2-8396-314ec1ca8224.png">
<img width="121" alt="image" src="https://user-images.githubusercontent.com/30281608/222960124-cb5bbf44-1962-482b-8b36-0befa7b9d24b.png">
Also, It only happens when i loading the onnx model. this issue is not happening when using the .pt file.
