### ISSUE TITLE
Where should i modify when training some of parts of classes in custom dataset.

### ISSUE THREAD

**Issue by yellowjs0304** [ultralytics/ultralytics#1236]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I wondered where should i modify in Yolov8, like this [issue](https://github.com/ultralytics/yolov5/issues/1978)(referenced in yolov5)

I wanna train specific classes in my dataset.
```
0 0.00475594300630158 0.7151455927652908 0.9992383128629915 0.7151455927652908 0.9992383128629915 0.8626347866854197 0.00475594300630158 0.8626347866854197
1 0.8647255613720259 0.018674381034945398 0.9346355586715483 0.018674381034945398 0.9346355586715483 0.9794143971359162 0.8647255613720259 0.9794143971359162
1 0.9351224325517384 0.017900524229638153 0.9999091168756978 0.017900524229638153 0.9999091168756978 0.9801048459276309 0.9351224325517384 0.9801048459276309
4 0.00485575549842902 0.8646976090014065 0.5845004875454304 0.8646976090014065 0.5845004875454304 0.9766041030117855 0.00485575549842902 0.9766041030117855
3 0.004968082955431675 0.023296828331673985 0.9985846740417664 0.023296828331673985 0.9985846740417664 0.1598350163561371 0.004968082955431675 0.1598350163561371
2 0.18670483460559797 0.003551696921862668 0.2926844783715013 0.004498816101026046 0.29497455470737916 0.9949486977111286 0.18848600508905855 0.9947119179163377
```
There are 5 classes in my custom data, but i wanna train only "1, 2" class.
Could you please tell me the way of modify it??

**Comment by glenn-jocher** [comment]
@yellowjs0304 thanks for asking. I don't think this feature is supported yet in YOLOv8 dataloader, but if your dataset is a detect dataset then you can use v5loader=true and simply apply the same list of include classes you applied in YOLOv5 here on L535.

https://github.com/ultralytics/ultralytics/blob/3861e6c82aaa1bbb214f020ece3a4bd4712eacbe/ultralytics/yolo/data/dataloaders/v5loader.py#L534-L545

@Laughing-q this is probably something we want to add to YOLOv8, sometimes users might only want to i.e. train COCO on a few classes, so we could use i.e. classes=[0,1,2] to select only labels that fall into that class. This is a quick fix as it doesn't actually restructure the model outputs, it just removes all labels not in the include list from training.

**Comment by yellowjs0304** [comment]
@glenn-jocher Thank you for fast reply. Does it also can be applying segmentation dataset also? my dataset is for segmentation
