### ISSUE TITLE
plot function not working

### ISSUE THREAD

**Issue by moured** [ultralytics/ultralytics#1237]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Thanks for the great work. When I get the results from the model. predict then I do results[0].plot(show_conf=True, pil=True, line_width=1, example='abc') it gets an empty image although I have many bounding boxes in results[0] with high confidence. The plot function is not returning pil image nor draw anything just an empty image is returned. 

**The problem occur only when pil=True**

Best,
Omar

### Environment

Conda yolov8 as described in your repo. Ubuntu 18, python 3.7 

### Minimal Reproducible Example

results[0].plot(show_conf=True, pil=True, line_width=1, example='abc') 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by rvbabera** [comment]
yes it doesn't worked for me also

**Comment by AyushExel** [comment]
This works for me:
```
model = YOLO('yolov8n.pt')
res = model(SOURCE)
plt = res[0].plot()
cv2.imshow("plt", plt)
cv2.waitKey(0)
```
<img width="406" alt="Screenshot 2023-03-02 at 4 14 34 PM" src="https://user-images.githubusercontent.com/15766192/222406440-cb57792e-63bd-49cb-8de1-a70f6b73c272.png">

**Comment by moured** [comment]
I further debugged the function. Try to add pil=True you will get the original image as numpy without bounding boxes. The problem is only when pil=True.

**Comment by glenn-jocher** [comment]
@moured thanks for the bug report. I'll add a TODO to add this issue to our tasks. Fix PRs are also welcome.

**Comment by Laughing-q** [comment]
@AyushExel @glenn-jocher @moured guys I think the pil issue had been solved. Closing the issue!
tested with the following code and it works correctly.
```python
from ultralytics import YOLO
import cv2

model = YOLO('yolov8n.pt')
res = model("ultralytics/assets")
plt = res[0].plot(pil=True)
cv2.imshow("plt", plt)
cv2.waitKey(0)
```
@moured feel free to reopen it if you still have related issue. :)
