### ISSUE TITLE
Not able to pass frame to cv2

### ISSUE THREAD

**Issue by GianniVanHavermaet** [ultralytics/ultralytics#1239]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

When running the code below, my cv2.imshow() shows a black screen when the 'show' parameter in model.track() is not set to True.If it is set to True, i get two windows, the windows from model.track(show=True) and the cv2.imshow window.

The main goal is to put center dot in the dected boxes, put custom labels and text on the frame.
```
from ultralytics import YOLO
import cv2



source = "test2.mp4"
model = YOLO("yolov8n.pt")


def on_predict_batch_end(predictor):
    # results -> List[batch_size]
    _, _, im0s, _, _ = predictor.batch
    im0s = im0s if isinstance(im0s, list) else [im0s]
    predictor.results = zip(predictor.results, im0s)

model.add_callback("on_predict_batch_end", on_predict_batch_end)

for (result,frame) in model.track(source=source, stream=True, verbose=True):

    for obj in result.boxes.boxes.cpu().numpy():
        x1 = int(obj[0])
        y1 = int(obj[1])
        x2 = int(obj[2])
        y2 = int(obj[3])

        id = int(obj[4])
        conf = int(obj[5])
        cat = int(obj[6])

        cx=int(x1+x2)//2
        cy=int(y1+y2)//2

        cv2.circle(frame,(cx,cy),10,(0,0,255),-1)

    frame = cv2.resize(frame, (frame.shape[1]//4, frame.shape[0]//4))
    cv2.imshow("Tracking", frame)
```

### Environment

Ultralytics YOLOv8.0.42  Python-3.10.10 torch-1.13.1+cpu CPU

### Minimal Reproducible Example

See above

### Additional

- Is it possible to change plot custom labels, text, objects (lines, rectangles, circles) without the need of cv2?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by GianniVanHavermaet** [comment]
Had to add:

    if cv2.waitKey(1)&0xFF==27:
        break

**Comment by pderrenger** [comment]
@GianniVanHavermaet adding the code snippet:

```python
if cv2.waitKey(1) & 0xFF == 27:
    break
```

will allow you to break the loop when the 'Esc' key is pressed. Regarding the possibility of customizing labels, text, and objects without using cv2, YOLOv8 currently relies on cv2 for such customizations. If you have any further questions or need additional assistance, feel free to ask!
