### ISSUE TITLE
Label images that contain partially occluded objects for custom training

### ISSUE THREAD

**Issue by Linkanblomman** [ultralytics/ultralytics#1240]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I was wondering if there is a preferred way of dealing with partial occlusion when creating a custom dataset for YOLOv8?

For example, in the image below. Should one use "pixel-based bounding boxes" (left) or "amodal bounding boxes" (right) when labeling images?

![image](https://user-images.githubusercontent.com/11296710/222476498-18fb9e14-592d-49d4-b28c-c89ac629a23f.png)

**Comment by Laughing-q** [comment]
@Linkanblomman For me I'd like to recommend `pixel-based`, with each box does not contain many parts of other boxes which is better for training. But if it's a special case that you want to detect the whole part of the car(including visible and invisible parts), you can also take the `amodal` way, it could work.

**Comment by Linkanblomman** [comment]
@Laughing-q Thank you for your input!
