### ISSUE TITLE
About yolov8 output and its post processing

### ISSUE THREAD

**Issue by s1030512149** [ultralytics/ultralytics#1248]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

model = YOLO("best.onnx")
result= model.predict(img,task="segment",imgsz=1280)[0]

I used the yolov8-seg for predict, and i tried to get the original results without NMS. Actually i dont know how to get the original result, but I tried to set the conf=0, iou=1 ,as follow:
result= model.predict(img,task="segment",imgsz=1280,conf=0.iou=1)[0]

In my opinion, this result could be the original result without NMS. But when I code like this, the post process is too much time consuming, the postprocess cosume almost 2500 ms.  So i want to ask how can i get the original masks and bbox results without any NMS process. Thank u very much!

**Comment by AyushExel** [comment]
NMS post-processing is hardcoded in the v8 predictor. You can change this behaviour by implementing your own predictor. Here's an example with trainer https://docs.ultralytics.com/engine/

**Comment by nikbobo** [comment]
> NMS post-processing is hardcoded in the v8 predictor. You can change this behaviour by implementing your own predictor. Here's an example with trainer https://docs.ultralytics.com/engine/

Could you add an option or method to get without nms result?

**Comment by s1030512149** [comment]
> NMS post-processing is hardcoded in the v8 predictor. You can change this behaviour by implementing your own predictor. Here's an example with trainer https://docs.ultralytics.com/engine/

Thanks, i am trying to solve it.

**Comment by pderrenger** [comment]
@s1030512149 you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with your implementation!
