### ISSUE TITLE
DEFAULT_CFG has no save_dir key

### ISSUE THREAD

**Issue by fhqjwyk** [ultralytics/ultralytics#1249]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

![image](https://user-images.githubusercontent.com/47907486/222627917-e62f975f-f96d-4968-b4ad-7dd5a4d7e07f.png)
![image](https://user-images.githubusercontent.com/47907486/222628258-21407b32-7c62-4849-a60c-d95135fceb3f.png)
first picture show that 'save_dir' can be set, but 'DEFAULT_CFG' has no save_dir key, the second picture 'check_cfg_mismatch(cfg, overrides)' will run error.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by ZeroAct** [comment]
This is not bug.
I think they intentionally remove `save_dir` to avoid redundant option.
You can use `project` argument instead of `save_dir`.

**Comment by fhqjwyk** [comment]
> ok, thanks, I guess so

**Comment by pderrenger** [comment]
@fhqjwyk you're welcome! If you have any more questions or need further assistance, feel free to ask. Happy to help! 😊
