### ISSUE TITLE
All results are drawed to first image when predict images list. 

### ISSUE THREAD

**Issue by captainconquer** [ultralytics/ultralytics#1251]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

\ultralytics\yolo\v8\segment\predict.py

    def postprocess(self, preds, img, orig_img):
        # TODO: filter by classes
        p = ops.non_max_suppression(preds[0],
                                    self.args.conf,
                                    self.args.iou,
                                    agnostic=self.args.agnostic_nms,
                                    max_det=self.args.max_det,
                                    nc=len(self.model.names),
                                    classes=self.args.classes)
        results = []
        proto = preds[1][-1] if len(preds[1]) == 3 else preds[1]  # second output is len 3 if pt, but only 1 if exported
        for i, pred in enumerate(p):
            orig_img = orig_img[i] if isinstance(orig_img, list) else orig_img
            shape = orig_img.shape

====>>>> change the parameter name from orig_img to orig_imgs

    def postprocess(self, preds, img, orig_imgs):
        # TODO: filter by classes
        p = ops.non_max_suppression(preds[0],
                                    self.args.conf,
                                    self.args.iou,
                                    agnostic=self.args.agnostic_nms,
                                    max_det=self.args.max_det,
                                    nc=len(self.model.names),
                                    classes=self.args.classes)
        results = []
        proto = preds[1][-1] if len(preds[1]) == 3 else preds[1]  # second output is len 3 if pt, but only 1 if exported
        for i, pred in enumerate(p):
            orig_img = orig_imgs[i] if isinstance(orig_imgs, list) else orig_imgs
            shape = orig_img.shape

### Minimal Reproducible Example

from ultralytics import YOLO
import cv2

if __name__ == '__main__':
    model = YOLO("./runs/segment/train3/weights/best.pt")  # load a custom model

    img1 = cv2.imread('img1.jpg')
    img2 = cv2.imread('img2.jpg')
    img3 = cv2.imread('img3.jpg')

    # Predict with the model
    results = model([img1,img2,img3],conf = 0.5)  # predict on image list
    cv2.imwrite('img1_output.jpg', results[0].plot())
    cv2.imwrite('img2_output.jpg', results[1].plot())
    cv2.imwrite('img3_output.jpg', results[2].plot())

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@captainconquer got it, thanks for the bug report! I've pushed a fix for this in https://github.com/ultralytics/ultralytics/pull/1263/commits/feba6343150bdc986f85a186f8c52994d10e4463 which should be out in 8.0.50 this weekend. Let me know if this commit looks good and if you spot any other problem.

**Comment by captainconquer** [comment]
> Thanks for quick feedback. The fix is good enough :)

**Comment by pderrenger** [comment]
You're welcome, @captainconquer! Glad the fix looks good to you. If you have any more feedback or run into other issues, feel free to reach out. Happy to help! 😊
