### ISSUE TITLE
Attempting to unscale FP16 gradients ?

### ISSUE THREAD

**Issue by wangtao2668129173** [ultralytics/ultralytics#1253]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hello, thank you for your contribution to the code. I integrated distillation loss on yolov5 without any bugs,However, we will have this problem when we get the FPN layer features of the model in Yolov8 and do the loss. We locate it as scaler.unscale_ (optimizer), the optimizer gradients are fp16, but the first epoch can run normally, and the second epoch directly reports an error

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wangtao2668129173 the forward, backward, optimize sequence in here:
https://github.com/ultralytics/ultralytics/blob/3861e6c82aaa1bbb214f020ece3a4bd4712eacbe/ultralytics/yolo/engine/trainer.py#L305-L322

And the gradients are unscaled for clipping here, which is unchanged from YOLOv5. It's possible some of the new layers like softmax in DFL are causing issues.
https://github.com/ultralytics/ultralytics/blob/3861e6c82aaa1bbb214f020ece3a4bd4712eacbe/ultralytics/yolo/engine/trainer.py#L426-L434

**Comment by wangtao2668129173** [comment]
@glenn-jocher hello,my implementation is as follows，I am very confused and hope to get your help.
1. features_loss = self.adapt_module(student_features,teacher_features) # compute  features(FPN layer) loss between teacher and student model
2.  self.loss, self.loss_items = self.criterion(preds, batch, features_loss) # features loss+ task_loss
optimizer:
# add features loss(papameter) to optimizer
for v in module.modules():
            if hasattr(v, 'bias') and isinstance(v.bias, nn.Parameter):  # bias (no decay)
                g[2].append(v.bias)
            if isinstance(v, bn):  # weight (no decay)
                g[1].append(v.weight)
            elif hasattr(v, 'weight') and isinstance(v.weight, nn.Parameter):  # weight (with decay)
                g[0].append(v.weight)
  train one epoch all       4952      12032      0.781       0.77      0.824      0.627             
                                                                                                     
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size                        
  0%|          | 0/259 [00:00<?, ?it/s] 
and then 
   raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.

**Comment by nameless-2019302413** [comment]
Did I also encounter the same problem? Have you solved this problem in the end?

**Comment by nameless-2019302413** [comment]
> @glenn-jocher hello,my implementation is as follows，I am very confused and hope to get your help.
> 
> 1. features_loss = self.adapt_module(student_features,teacher_features) # compute  features(FPN layer) loss between teacher and student model
> 2. self.loss, self.loss_items = self.criterion(preds, batch, features_loss) # features loss+ task_loss
>    optimizer:
> 
> # add features loss(papameter) to optimizer
> for v in module.modules(): if hasattr(v, 'bias') and isinstance(v.bias, nn.Parameter): # bias (no decay) g[2].append(v.bias) if isinstance(v, bn): # weight (no decay) g[1].append(v.weight) elif hasattr(v, 'weight') and isinstance(v.weight, nn.Parameter): # weight (with decay) g[0].append(v.weight) train one epoch all 4952 12032 0.781 0.77 0.824 0.627
> 
> ```
>   Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size                        
> ```
> 
> 0%| | 0/259 [00:00<?, ?it/s] and then raise ValueError("Attempting to unscale FP16 gradients.") ValueError: Attempting to unscale FP16 gradients.

Did I also encounter the same problem? Have you solved this problem in the end?

**Comment by nameless-2019302413** [comment]
> @glenn-jocher hello,my implementation is as follows，I am very confused and hope to get your help.
> 
> 1. features_loss = self.adapt_module(student_features,teacher_features) # compute  features(FPN layer) loss between teacher and student model
> 2. self.loss, self.loss_items = self.criterion(preds, batch, features_loss) # features loss+ task_loss
>    optimizer:
> 
> # add features loss(papameter) to optimizer
> for v in module.modules(): if hasattr(v, 'bias') and isinstance(v.bias, nn.Parameter): # bias (no decay) g[2].append(v.bias) if isinstance(v, bn): # weight (no decay) g[1].append(v.weight) elif hasattr(v, 'weight') and isinstance(v.weight, nn.Parameter): # weight (with decay) g[0].append(v.weight) train one epoch all 4952 12032 0.781 0.77 0.824 0.627
> 
> ```
>   Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size                        
> ```
> 
> 0%| | 0/259 [00:00<?, ?it/s] and then raise ValueError("Attempting to unscale FP16 gradients.") ValueError: Attempting to unscale FP16 gradients.

I also encountered the same problem. Have you solved this problem in the end?

**Comment by glenn-jocher** [comment]
@nameless-2019302413 hello, it seems like you are getting an error regarding unscaled floating point 16 (FP16) gradients. This usually occurs when attempting to perform an operation that requires scaled gradients on unscaled ones.

From the implementation details you've shared, it seems that you're adding the features loss to the optimizer, and bias and weight variations are being identified correctly. 

However, a potential cause of this issue could be that some new layers, such as SoftMax in Deep Feature Loss (DFL), are causing an error in the unscale_() operation, which is trying to unscale FP16 gradients.

I would suggest troubleshooting by checking the layers where you've applied unscale_() operation. Also, be informed that the unscale_ operation is mainly needed if you are performing gradient clipping. If you're not, you may not need to unscale the gradients. 

Remember that integrated features loss or other novel loss functions could make the system more complex and prone to errors in specific cases or edge scenarios. Always double-check your implementation against the base model to ensure compatibility. I hope you find this information helpful. If you have any further issues or questions, please let us know. We are here to help!
