### ISSUE TITLE
yolov9 export paddle error

### ISSUE THREAD

**Issue by KingerFzb** [ultralytics/ultralytics#12602]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

yolov9 export paddle error

PaddlePaddle: export failure ❌ 14.6s: In transformed code:

    File "XXX\weights\last_paddle_model\x2paddle_code.py", line 796, in forward
        x1140 = self.conv2d85(x0)
        x1141 = self.silu80(x1140)
        x1146 = paddle.nn.functional.interpolate(x=x1045, size=[320, 320], mode='nearest')
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        x1148 = paddle.nn.functional.interpolate(x=x1062, size=[320, 320], mode='nearest')
        x1150 = paddle.nn.functional.interpolate(x=x1081, size=[320, 320], mode='nearest')

    File "D:\Miniconda\envs\pt_2.1.2\lib\site-packages\paddle\nn\functional\common.py", line 399, in interpolate
        if resample in ['NEAREST'] and len(x.shape) != 4 and len(x.shape) != 5:

    AttributeError: 'list' object has no attribute 'shape'

### Additional

_No response_

**Comment by glenn-jocher** [comment]
@KingerFzb hi there! It looks like there's an issue with the input format being passed to the `paddle.nn.functional.interpolate` function. Make sure the input `x1045` is a Paddle Tensor rather than a list, as the interpolate function is expecting a tensor with a `.shape` attribute. 

Here's a quick fix to ensure your input is a tensor:
```python
x1045 = paddle.to_tensor(x1045)
```
Insert this line before your interpolate call. This should solve the AttributeError you're encountering. Give it a try and let us know if you face any other issues!

**Comment by KingerFzb** [comment]
thanks for your response,it works! but the code is generate on time, so i try a stupid way, i inset a input func in after it generate the code to pause the progress, and modify the code to export success


site-packages/paddle/jit/dy2static/program_translator.py
```
def __getitem__(self, item):
        if not isinstance(item, CacheKey):
            raise ValueError(
                'type(item) should be CacheKey, but received %s'
                % type_name(item)
            )
        item_id = hash(item)
        self._recent_cache_key = item
        self._recent_key = item_id
        if item_id not in self._caches:
            input('psuse to modify the x2paddle_code.py')   # insert
            self._caches[item_id] = self._build_once(item)
            # Note: raise warnings if number of traced program is more than `max_tracing_count`
            current_tracing_count = len(self._caches)
            if current_tracing_count > MAX_TRACED_PROGRAM_COUNT:
                logging_utils.warn(
                    "Current traced program number: {} > `max_tracing_count`:{}. Too much cached programs will bring expensive overhead. "
                    "The reason may be: (1) passing tensors with different shapes, (2) passing python objects instead of tensors.".format(
                        current_tracing_count, MAX_TRACED_PROGRAM_COUNT
                    )
                )
```
