### ISSUE TITLE
Loading engine file on GPU whenever call predict method on a frame of CSI camera even stream=True

### ISSUE THREAD

**Issue by erfansafaie** [ultralytics/ultralytics#12604]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a True while loop that read CSI camera and inference frames using TensorRT yolov8n in engine format. When I inference by predict method it loads engine file on GPU again even stream=True. It creates a much lag in my pipeline. Beside I use multiple model in my pipeline. Is there anyway just load the model one time and predict the frame in loop?

### Additional

If there is more docs about library we can use it with lower memory leakage and faster usage.

**Comment by glenn-jocher** [comment]
Hello! It sounds like the repeated model loading is indeed causing an inefficiency in your frame processing pipeline. Ideally, the model should be loaded into the GPU memory once, and then you can continuously pass the frames to it.

Here's a simplified approach to ensure that the model is only loaded once:

```python
from ultralytics import YOLO

# Load the model once
model = YOLO('path/to/your/yolov8n.engine')

#Assuming 'cap' is your camera capture object
while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Run inference
    results = model.predict(frame, stream=True)
    # Process results here
```

With this setup, the `YOLO` engine is loaded before entering the loop, and then you can use the `predict` method continually on the streaming frames. If you're using multiple models, ensure each model is similarly loaded once before the loop.

Regarding further optimizing for memory and efficiency, ensure you are using the appropriate model size (like 'yolov8n', 'yolov8s', etc.), appropriate batch sizes, and experiment with different precision modes (e.g., FP16 if your hardware supports it).

Let us know if this helps or if you run into any more issues!

**Comment by erfansafaie** [comment]
Thanks a lot for your response and answer!
Is there any way or modification to infer CUDA image? I can store my camera data directly on GPU, so I want use this method to avoid copying frame.
Best regards.

**Comment by glenn-jocher** [comment]
Hello!

Great to hear from you! If your camera frames are already on the GPU, you can directly feed them to the model without copying them back to CPU. Make sure your frames are in the appropriate format (e.g., CUDA tensors). Here's a quick example of how you might do this:

```python
from ultralytics import YOLO
import torch

# Load the model
model = YOLO('path/to/model.engine')

# Assuming `frame_gpu` is your CUDA tensor directly from the camera
results = model(frame_gpu)  # Directly pass the CUDA tensor
```

Just ensure that `frame_gpu` is in the format expected by the model (e.g., `torch.Tensor` on the correct device). This should help in utilizing GPU memory more efficiently and speed up the inference process.

Best regards!
