### ISSUE TITLE
error when i try to run train yolov8 with GPU 1650

### ISSUE THREAD

**Issue by HauNguyen27** [ultralytics/ultralytics#12601]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

1. my environment:
    pycharm 2023.2.5 
    Ultralytics YOLOv8.2.13 🚀 Python-3.9.13 torch-2.3.0+cu118 CUDA:0 (GeForce GTX 1650, 4096MiB)
2. this is my train code:
from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)
if __name__ == '__main__':
    from multiprocessing import freeze_support
    freeze_support()
# Use the model
    model.train(data="coco128.yaml", epochs=3, device='0', batch=2, workers=2)  # train the model
![z5433612327168_2a0ee03f433c93cb40f7a483668e9c64](https://github.com/ultralytics/ultralytics/assets/135089161/b160d36d-65e5-4cb8-8b27-884f9af9bdfa)

### Environment
![z5433613380076_5ac9686f7111f79c7d7b088761e306c2](https://github.com/ultralytics/ultralytics/assets/135089161/fd411f61-0b41-408c-b14c-0534045215d4)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by HauNguyen27** [comment]
![Uploading z5433613380076_5ac9686f7111f79c7d7b088761e306c2.jpg…]()

**Comment by HauNguyen27** [comment]
![z5433613380076_5ac9686f7111f79c7d7b088761e306c2](https://github.com/ultralytics/ultralytics/assets/135089161/4857153b-34a8-4d53-bfbb-474f37b1de52)

**Comment by glenn-jocher** [comment]
It seems like you're trying to share an image or a screenshot that might depict an error or issue you're experiencing. Unfortunately, the link to the image seems to be broken or incorrectly formatted, so I cannot view it. Could you please re-upload the image directly here, or describe the issue in text form? This will help me understand the problem better and provide you with a more accurate solution. Thanks!
