### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by hamedgorji** [ultralytics/ultralytics#1261]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I installed the yolov8 based on the instructon and tried to run the following example:

```
from ultralytics import YOLO
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

# Use the model
model.train(data="coco128.yaml", epochs=3)
```
But I keep getting the following error. Could you please let me know what can be the problem

```
OS: Windows 10
Ultralytics YOLOv8.0.49  Python-3.10.9 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24576MiB)
```
```

Transferred` 355/355 items from pretrained weights
optimizer: SGD(lr=0.01) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias
train: Scanning D:\Hamed\Project\Codes\Yolo\yolov8\datasets\coco128\labels\train2017... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<00:00, 1300.73it/s]
train: New cache created: D:\Hamed\Project\Codes\Yolo\yolov8\datasets\coco128\labels\train2017.cache
val: Scanning D:\Hamed\Project\Codes\Yolo\yolov8\datasets\coco128\labels\train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]
Plotting labels to runs\detect\train2\labels.jpg... 
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs\detect\train2
Starting training for 3 epochs...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Hamed\miniconda3\envs\yolov8\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Hamed\miniconda3\envs\yolov8\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Hamed\miniconda3\envs\yolov8\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Hamed\miniconda3\envs\yolov8\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Hamed\miniconda3\envs\yolov8\lib\runpy.py", line 288, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\Hamed\miniconda3\envs\yolov8\lib\runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
OSError: [Errno 22] Invalid argument: `'D:\\Hamed\\Project\\Codes\\Yolo\\yolov8\\<input>'
```

**Comment by hamedgorji** [comment]
I solved this problem by installing ipython.
`pip install ipython`

**Comment by pderrenger** [comment]
@hamedgorji glad to hear that you were able to resolve the issue! The error you encountered seems to be related to the multiprocessing module, and installing `ipython` likely resolved the underlying dependency problem. If you have any more questions or need further assistance, feel free to ask!

**Comment by glenn-jocher** [comment]
@pderrenger, fantastic to know the issue is resolved! Your experience might be helpful to others facing similar problems. If anything else comes up, don't hesitate to reach out. Happy coding! 😊👍

**Comment by HoseinHashemi** [comment]
> I solved this problem by installing ipython. `pip install ipython`

This solves the problem. Misleading error.

**Comment by glenn-jocher** [comment]
@HoseinHashemi great to hear you've found a solution, and thanks for sharing it! 🎉 Indeed, some errors can be quite misleading. If anyone else encounters a similar issue, trying out `pip install ipython` might just do the trick. Happy coding with YOLOv8! 🚀
