### ISSUE TITLE
How to print Accuracy of the detected object 

### ISSUE THREAD

**Issue by SivaBodapati** [ultralytics/ultralytics#1262]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

How to print Accuracy of the detected object 

### Use case

To know the Accuracy of detected object for comparing with other versions results

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
By accuracy do you mean mAP? 
It should be printed when running validation. See docs here -> https://docs.ultralytics.com/tasks/detection/#val

**Comment by SivaBodapati** [comment]
![k](https://user-images.githubusercontent.com/126906353/222906463-80f75d71-4105-4d04-a112-f7d72d851f7f.jpg)

In the above image we can see conf as 0.89 like that, how we can print accuracy of Red Chilli

**Comment by mraselamin** [comment]
@SivaBodapati your project look cool, can you share your repository, or you can make documentation
