### ISSUE TITLE
Yolov8 SDK run OK in debug but after convert to exe its run as a loop (create unlimited train section)

### ISSUE THREAD

**Issue by nghiakthp2401** [ultralytics/ultralytics#12637]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When run as exe file it create unlimited train section till ram is full. 
![image](https://github.com/ultralytics/ultralytics/assets/135792797/f7831077-1f21-468f-8e1e-1dd81afb207f)
Full video description about this : [https://drive.google.com/file/d/1639oRAFH8MveZy9p-IygH5DRgpCyGK-G/view?usp=sharing]
But when run in debug mode it works OK
![image](https://github.com/ultralytics/ultralytics/assets/135792797/c805dfce-9275-4a62-a36b-46d8a37596fa)

Here is my code

`
from ultralytics import YOLO
import configparser
from os import path, getcwd
import cv2 as cv

def ModifyDataYamlFile(filePath, UseTrainAsVal):

    StartUpPath = getcwd()
    with open(filePath, "r") as file:
        lines = file.readlines()
        lines[0] = "train: " + StartUpPath + "\\Dataset\\train\\images\n"
        if UseTrainAsVal:
            lines[1] = "val: " + StartUpPath + "\\Dataset\\train\\images\n"
        else :
            lines[1] = "val: " + StartUpPath + "\\Dataset\\val\\images\n"
        lines[2] = "test: " + StartUpPath + "\\Dataset\\test\\images\n"
    with open(filePath, "w") as file:
        file.writelines(lines)
   
if __name__ == '__main__':

    # Load Config Data
    if path.exists("Config.cfg"):
        config = configparser.RawConfigParser()  
        config.read("Config.cfg")

        WeightPath = config.get("Config","WeightPath")
        DatasetPath = config.get("Config","DatasetPath")
        Task = config.get("Config","Task")
        Epoch = (int)(config.get("Config","Epoch"))
        Batch = (int)(config.get("Config","Batch"))
        ImageSize = (int)(config.get("Config","ImageSize"))
        Patience = (int)(config.get("Config","Patience"))
        ExportFormat = config.get("Config","ExportFormat")
        TrainDevice = config.get("Config","TrainDevice")
        UseTrainAsVal = (bool)(config.get("Config","UseTrainAsVal"))
        
        ModifyDataYamlFile(DatasetPath, UseTrainAsVal)
        weightPath = path.join(getcwd(), WeightPath)

        if(TrainDevice == "GPU"):
            device = "0"
        
        elif(TrainDevice == "CPU"):
            device = "cpu"
        

        #Tranning Pharse
        model = YOLO(weightPath)

    if path.exists("Config.cfg"):
        results = model.train(data=DatasetPath, epochs=Epoch, batch = Batch, 
                        patience= Patience, imgsz = ImageSize,  device=device)
        cv.waitKey(0)
    else: print("Not Found Config Folder")
`

**Comment by nghiakthp2401** [comment]
I uesed Auto-py-to-exe as to convert

**Comment by glenn-jocher** [comment]
Hello!

It sounds like you're observing a different behavior between your debug and executable versions, which is not entirely uncommon when using tools like Auto-py-to-exe. A few quick tips that might help:

1. Ensure all file paths are correctly handled in the executable. Paths managed differently could cause loops if the program continually looks for a file not found in its path.
2. Check if the environment configurations are consistent between your debug and production setups.
3. Consider catching and logging detailed errors or exceptions that may only occur in the executable environment. This will help explore whether specific parts of the code cause the loop.

If you still run into issues, feel free to share a snippet where you set up your execution loop or manage configurations, and we might spot something specific that's going off-track!

Good luck!
