### ISSUE TITLE
FPS drop while using Ultralytics 

### ISSUE THREAD

**Issue by kunal270902** [ultralytics/ultralytics#12647]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I was using Ultralytics v8.2.14 and Flask on Ubuntu 22 for a project and was getting around 40-45 FPS. But then I had some problems with Ubuntu and had to reinstall the OS. I used the same code I pushed on GIT and the same hardware but this time I am getting 4-5 FPS for the same code. I even tried using an older 8.2.0 version but am getting the same issue. Please help!!!!!

### Environment

AMD Ryzen 5300H, 4 Core CPU, NVDIA GTX  GPU, 16 GB RAM.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! It sounds like you're experiencing a significant drop in FPS after reinstalling Ubuntu, which must be quite frustrating!

One likely reason for the drop in FPS could be differences in the GPU drivers installed during the OS reinstallation. I recommend checking if your NVIDIA drivers are up to date and correspond to the version you had previously when your setup was achieving higher FPS.

Here’s how you can check and update your NVIDIA drivers:
1. Open a terminal and run `nvidia-smi` to check your current driver version.
2. Visit the NVIDIA website to compare your current driver version with the latest available for your GTX GPU.
3. If an update is needed, you can download and install the latest drivers from NVIDIA's official site.

Additionally, verify if CUDA and cuDNN are properly installed and match the versions required by YOLOv8, as these can also significantly affect processing speed.

If issues persist after updating your drivers, let’s troubleshoot further or examine other system configurations that might be impacting performance.

Looking forward to your PR, and hoping this helps get your FPS back up! 🚀
