### ISSUE TITLE
model.engine speed is slowest than model.pt

### ISSUE THREAD

**Issue by shaimaahamam** [ultralytics/ultralytics#12653]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

when convert model from **model.pt** to **model.engine** the size of model is increased and takes more time in prediction step.

**Comment by shaimaahamam** [comment]
I have RTX 3060 TI
driver version : 545.29.06
GPU 8 GB 
Cuda version :12.3
Ubuntu 22.4
Ram size : 98 GB
CPU X86-64 AMD Ryzen 9 5900X 12-Core Processor



which version of python , tensorRT compatible with and number of workspace and batches ?

**Comment by glenn-jocher** [comment]
Hello! For your setup with an RTX 3060 Ti, here’s a quick guide to get you started:

- **Python Version:** Python 3.8 or newer should work well.
- **TensorRT Version:** With CUDA 12.3, you should use TensorRT 8.x. Make sure to download the version compatible with CUDA 12.3 from the [NVIDIA website](https://developer.nvidia.com/tensorrt).
- **Workspace Size:** Starting with a workspace size of 4 GB is generally a good balance. You can adjust this if needed:
  ```bash
  yolo export model=yolov8n.pt format=engine workspace=4
  ```
- **Batch Size:** If you're not facing memory issues, you can start with a batch size of 2 or more depending on your specific use case. Remember, larger batch sizes might increase throughput but also memory usage:
  ```bash
  yolo export model=yolov8n.pt format=engine batch=2
  ```

Feel free to tweak these settings based on your performance and accuracy needs! 🚀
