### ISSUE TITLE
How to crop detected object from image using YOLOv8 model without saving it. 

### ISSUE THREAD

**Issue by DucTran2511** [ultralytics/ultralytics#12658]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am using the YOLO model for training. After training, I continue to use the detected objects for my tasks, so I just want to use an array of detected objects without saving it in physical memory. How can I use detected objects without saving them?

**Comment by glenn-jocher** [comment]
Hi there!

You can easily crop detected objects from an image using the YOLOv8 model and handle them directly in memory! Here’s how you can do it:

```python
from ultralytics import YOLO
import cv2

# Load the model
model = YOLO('yolov8n.pt')

# Load your image
image = cv2.imread('path/to/image.jpg')

# Run inference
results = model(image)

# Access the cropped detected objects
for obj in results[0].masks.crop():
    # obj is a cropped image of each detected object
    # You can now use obj directly in your tasks!
    pass
```

This code will give you an array of the cropped images of detected objects which you can use right away without needing to save them. Hope this helps! 🚀
