### ISSUE TITLE
export openvino with `--static_shape` when `int8=true`

### ISSUE THREAD

**Issue by VShawn** [ultralytics/ultralytics#12669]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

when I running a openvino test with

```
yolo export model=yolov8m.pt format=openvino int8=true imgsz=1280
```

cli works great and int8 IR was successfully built.

But when I infer the IR, the cpp test app result with the following error:

```
Error occurred: get_shape was called on a descriptor::Tensor with dynamic shape
```

so may be `--static_shape` option is needed in this case.

### Additional

similar ticket: https://github.com/openvinotoolkit/openvino/issues/1386

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! It looks like exporting the model with a fixed shape could resolve the issue you're encountering. When using INT8 quantization, specifying a static shape often helps in handling the model's optimized version properly. Here's how you can include the static shape during export:

```bash
yolo export model=yolov8m.pt format=openvino int8=true imgsz=1280 static_shape=true
```

Give this a try and let me know if it solves the error! If you need further assistance, feel free to ask. 🚀

**Comment by knoppmyth** [comment]
@glenn-jocher I just ran into this issue and tried "static_shape=true". However, I get "SyntaxError: 'static_shape' is not a valid YOLO argument" this is with 8.2.28.

**Comment by glenn-jocher** [comment]
Hello! It seems there was a misunderstanding in my previous message. Currently, the `static_shape` argument is not supported directly via the YOLO CLI for exporting models. My apologies for the confusion.

For handling the dynamic shape issue in OpenVINO with INT8 models, you might need to manually adjust the model's configuration to specify static dimensions post-export using OpenVINO's tools. This typically involves modifying the model using OpenVINO's Model Optimizer to set the input shape statically.

Thank you for bringing this to our attention, and sorry for any inconvenience caused. If you have further questions or need more detailed guidance, please let us know!
