### ISSUE TITLE
rtdetr weight problem

### ISSUE THREAD

**Issue by S-7-12** [ultralytics/ultralytics#12663]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

For the rtdetr model, I would like to train the model using the backbones of resnet50 and 101, but have not found the corresponding pre-training weights.

### Additional

no

**Comment by glenn-jocher** [comment]
Hello! For training RT-DETR models with ResNet backbones, pre-trained weights might not be directly available from the Ultralytics repository. You can utilize pre-trained ResNet models from PyTorch repository as an alternative. Here's a code snippet on how you can do this:

```python
import torch
from ultralytics import YOLO

# Load RT-DETR model and specify the backbone
model = YOLO('rtdetr.yaml', backbone='resnet50')  # Change to 'resnet101' as needed

# Load pre-trained weights from PyTorch
pretrained_weights = torch.load('resnet50.pth')  # Adjust path and filename as necessary
model.load_state_dict(pretrained_weights, strict=False)

# Continue with your training setup
```

Replace `'resnet50.pth'` with the file path to your downloaded PyTorch weights, and ensure your YAML configuration file (`rtdetr.yaml`) correctly configures the model to use the desired ResNet backbone. Hope this helps! 😊

**Comment by S-7-12** [comment]
Traceback (most recent call last):
    model = YOLO('rtdetr.yaml', backbone='resnet50') # Change to 'resnet101' as needed
TypeError: __init__() got an unexpected keyword argument 'backbone'
The parameter backbone does not seem to be set when the model is initialized

**Comment by S-7-12** [comment]
```
from ultralytics import RTDETR

# Load RT-DETR model and specify the backbone
model = RTDETR('ultralytics/cfg/models/rt-detr/rtdetr-resnet50.yaml') 

# Train the model on the COCO8 example dataset for 100 epochs
model.train（

）
```
I noticed that the rtdetr r-50.yaml file already exists in the ultralytics repository and can be trained that way, but the weighting issue is still not resolved.

**Comment by glenn-jocher** [comment]
Hi there! It's great to see that you've found the appropriate `rtdetr-resnet50.yaml` file for training. If you're encountering issues with loading the specific weights for the ResNet-50 backbone in the RT-DETR model, you should first ensure that you have the correct pre-trained weights available. If they're not present, you might need to download them separately.

For training with pre-trained ResNet weights, you'll have to load these weights manually before the training starts. Here's a simple way to do it using PyTorch:

```python
import torch
from ultralytics import RTDETR

# Load the RTDETR model configuration
model = RTDETR('ultralytics/cfg/models/rt-detr/rtdetr-resnet50.yaml')

# Load pre-trained weights
weights = torch.load('path_to_resnet50_weights.pth')
model.model.load_state_dict(weights, strict=False)

# Train the model
model.train(data='path_to_coco128.yaml', epochs=100)
```

Make sure to replace `'path_to_resnet50_weights.pth'` with the path to your ResNet-50 PyTorch weights file, and adjust the data path and epochs as necessary. This should resolve the issue with the weights not being loaded properly. Let us know if you need further assistance! 😊

**Comment by yingyu13** [comment]
@glenn-jocher ,hi, the pre-trained ResNet weights cannot be loaded correctly, as the parameter names of pre-trained ResNet models from PyTorch repository is consistent with backbone defined in rtdetr r-50.yaml of ultralytics repository. How to resolve this issue?

**Comment by S-7-12** [comment]
> Hi there! It's great to see that you've found the appropriate `rtdetr-resnet50.yaml` file for training. If you're encountering issues with loading the specific weights for the ResNet-50 backbone in the RT-DETR model, you should first ensure that you have the correct pre-trained weights available. If they're not present, you might need to download them separately.
> 
> For training with pre-trained ResNet weights, you'll have to load these weights manually before the training starts. Here's a simple way to do it using PyTorch:
> 
> ```python
> import torch
> from ultralytics import RTDETR
> 
> # Load the RTDETR model configuration
> model = RTDETR('ultralytics/cfg/models/rt-detr/rtdetr-resnet50.yaml')
> 
> # Load pre-trained weights
> weights = torch.load('path_to_resnet50_weights.pth')
> model.model.load_state_dict(weights, strict=False)
> 
> # Train the model
> model.train(data='path_to_coco128.yaml', epochs=100)
> ```
> 
> Make sure to replace `'path_to_resnet50_weights.pth'` with the path to your ResNet-50 PyTorch weights file, and adjust the data path and epochs as necessary. This should resolve the issue with the weights not being loaded properly. Let us know if you need further assistance! 😊

https://github.com/ultralytics/ultralytics/issues/12663#issuecomment-2117023663
There is indeed this problem, there is indeed a problem with the code you provided, it really doesn't load the backbone weights successfully, hopefully you can give a solution for this

**Comment by S-7-12** [comment]
> @S-7-12 hi! Thanks for pointing out the issue with loading the backbone weights. It seems like the parameter names in the pre-trained ResNet model might not match directly with those expected by the RT-DETR model configuration. To resolve this, you can map the ResNet weights to the expected names in the RT-DETR model.
> 
> Here’s a quick way to adapt the weights:
> 
> ```python
> import torch
> from ultralytics import RTDETR
> 
> # Load the RTDETR model configuration
> model = RTDETR('ultralytics/cfg/models/rt-detr/rtdetr-resnet50.yaml')
> 
> # Load pre-trained weights
> resnet_weights = torch.load('path_to_resnet50_weights.pth')
> adapted_weights = {k if 'backbone' in k else 'backbone.' + k: v for k, v in resnet_weights.items()}
> 
> # Load adapted weights into the model, ignoring incompatible keys
> model.model.load_state_dict(adapted_weights, strict=False)
> 
> # Now you can proceed with training
> model.train(data='path_to_coco128.yaml', epochs=100)
> ```
> 
> This script prepends 'backbone.' to the keys of the ResNet weights, aligning them with the expected format in the RT-DETR model. Adjust the string manipulation as necessary based on the exact mismatch pattern. Let me know if this helps or if you need further adjustments! 😊

`import warnings
import torch
warnings.filterwarnings('ignore')

from ultralytics import RTDETR

# Load RT-DETR model and specify the backbone
model = RTDETR('ultralytics/cfg/models/rt-detr/rtdetr-resnet101.yaml') # Change to 'resnet101' as needed
# Display model information (optional)

# Train the model on the COCO8 example dataset for 100 epochs
model.train(data='/home/rendoudou/swx/pycharm/v5-ours/yolov5-master/data/our.yaml', 
                      imgsz=640,
                      cache=False,
                      epochs=300,
                      pretrained='resnet101.pth',
                      batch=16,
                      device='1',
                      project='runs-test/rtdetr-r101-train',
                      name='rtdetr-ours-',
                    #   project='runs-ours-rtdetr-r50/rtdetr-r50-train',
                    #   name='rtdetr-ours-',
                      patience=30,
                      )
`
Thanks, I found out that I can introduce weights this way, the code is currently running with no error messages, do you see any errors in the code?

**Comment by glenn-jocher** [comment]
Hey @S-7-12-12! Glad to hear that you've managed to get your code running smoothly! 🚀 From the snippet you've shared, everything looks in order. Just ensure that the path to your dataset and the pretrained weights are correctly specified. Also, keep an eye on the device configuration to match your available hardware. If any issues arise during training or if you need further assistance, feel free to reach out. Happy training! 😊

**Comment by Rbrq03** [comment]
Hey there, are u guys sure this way can load the pretrained weight correctly? IMP, this pretrained weights is ignored so no error messages occurs, while its behavior is to train the model from scratch.

When I try to train RTDETR-ResNet101 on coco with 
```
from ultralytics import YOLOv10, RTDETR

model = RTDETR(
    "ultralytics/cfg/models/rt-detr/rtdetr-resnet101.yaml"
)

gpus = [0, 1, 2, 3, 4, 5, 6, 7]

model.train(
    data="coco.yaml",
    epochs=72,
    save_period=5,
    batch=48,
    imgsz=640,
    optimizer="AdamW",
    lr0=3e-4,
    plots=True,
    deterministic=False,
    workers=8,
    pretrained="resnet101.pth",
    device=[0, 1, 2, 3, 4, 5, 6, 7],
)
```
There is a very large gap between the training logs and the training logs from the loaded backbone using official code. A temporary solution is to load a pretrained backbone with a random(or init) weights of other part and save them as a `.pth` file.

**Comment by pderrenger** [comment]
@Rbrq03 thank you for your detailed observation. It appears that the pretrained weights might not be loading as expected. To ensure the weights are correctly loaded, please verify that the parameter names in the pretrained ResNet model align with those expected by the RT-DETR model. If there's a mismatch, you may need to adapt the weights accordingly. Additionally, ensure you are using the latest version of the Ultralytics package, as updates may resolve such issues. If the problem persists, please share more details so we can further investigate.

**Comment by Rbrq03** [comment]
I am not sure, but imp, we cannot train rtdetr-resnet50 from scratch while maintaining the perf. I think you can load the weight from official weight of RTDETR repo

**Comment by pderrenger** [comment]
Thank you for your question. To train RT-DETR with ResNet-50 or ResNet-101 backbones, you should use the official pre-trained weights from the RT-DETR repository. This ensures that the backbone is correctly initialized, maintaining performance. If you encounter issues, please ensure you are using the latest version of the Ultralytics package. If the problem persists, feel free to provide more details for further assistance.

**Comment by felipetobars** [comment]
@Rbrq03 @gladdduck Hello, I wanted to ask if you were able to train RT-DETR ResNet (50 and 101). I understand that passing the path in the pretrained parameter when calling train() just ignores the weights and trains from scratch. Did the same thing happen to you with the method suggested by @glenn-jocher ? Here's the method:
```
import torch
from ultralytics import RTDETR

# Load the RTDETR model configuration
model = RTDETR('ultralytics/cfg/models/rt-detr/rtdetr-resnet50.yaml')

# Load pre-trained weights
resnet_weights = torch.load('path_to_resnet50_weights.pth')
adapted_weights = {k if 'backbone' in k else 'backbone.' + k: v for k, v in resnet_weights.items()}

# Load adapted weights into the model, ignoring incompatible keys
model.model.load_state_dict(adapted_weights, strict=False)

# Now you can proceed with training
model.train(data='path_to_coco128.yaml', epochs=100)
```

**Comment by Rbrq03** [comment]
Hey @felipetobars,
I am sorry that I cannot actually remember what will happen when using this method since it has been a while since this issue. But seems that this method doesn't work (not sure if it's because the training is still from scratch or other bugs) so I have changed all my projects to the official RT-DETR repo.
You can give this method a try by yourself if you are still interested.

**Comment by felipetobars** [comment]
@Rbrq03 Thank you, I will start training to see if the results are worse, better, or the same compared to using the standard RT-DETR from Ultralytics, which does provide pretrained weights.

**Comment by Rbrq03** [comment]
BTW, if you want to compare the performance of the model using YOLO and official repo, it seems to be unfair since they use different data augments. But if you want to verify if the pre-training weight is used in this method, I think it's ok.
