### ISSUE TITLE
Model does not see the GPUS

### ISSUE THREAD

**Issue by behroozazarkhalili** [ultralytics/ultralytics#1267]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Multi-GPU

### Bug

I'm running the following code:
# Load the dataset
`data_info = os.path.join(dataset_dir, 'data.yaml')`

# Create the desired path to save the training results
`save_dir = os.path.join(parent_dir, "runs", "detect", "train")`

# Training the model
`yolo_model.train(data=data_info, epochs=10, imgsz=800, plots=True, batch=16, optimizer="Adam", device='0, 1', save_dir=save_dir)`

```
Ultralytics YOLOv8.0.49 🚀 Python-3.10.9 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 4090, 24217MiB) CUDA:1 (NVIDIA GeForce RTX 4090, 24215MiB)
```

However, the `nvidia-smi` shows that GPUs have not been utilized.
![image](https://user-images.githubusercontent.com/80390531/222883958-d4bd8ad3-8873-4f40-8e58-fc1d2205e96f.png)

Could you please let me know how I can use multi-GPU in training my own model?
                                                                                                                                                                                                

### Environment

- YOLO: Ultralytics YOLOv8.0.49 🚀 Python-3.10.9 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 4090, 24217MiB) CUDA:1 (NVIDIA GeForce RTX 4090, 24215MiB)

- OS: Ubuntu 22.04

- Python: Python-3.10.9

### Minimal Reproducible Example

```
# Load the dataset
data_info = os.path.join(dataset_dir, 'data.yaml')

# Create the desired path o save the training results
save_dir = os.path.join(parent_dir, "runs", "detect", "train")

# Training the model
yolo_model.train(data=data_info, epochs=10, imgsz=800, plots=True, batch=16, optimizer="Adam", device='0, 1')
```

### Additional

Nothing special

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Can you check if your pytorch has cuda enabled?
```
import torch

print(torch.cuda.is_available())
```

**Comment by behroozazarkhalili** [comment]
> import torch
> 
> print(torch.cuda.is_available())

```
import torch

print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))
print(torch.cuda.get_device_name(1))
```
```
True
2
NVIDIA GeForce RTX 4090
NVIDIA GeForce RTX 4090
```

**Comment by AyushExel** [comment]
@glenn-jocher @Laughing-q the syntax looks correct. Can this be related to recent DDP changes?

**Comment by behroozazarkhalili** [comment]
> 
@glenn-jocher @Laughing-q @AyushExel 
Any update?

**Comment by glenn-jocher** [comment]
Your GPUs are correctly identified and utilized. The purpose of this console output is to provide confirmation to the user of that.

You've shown this output, so everything is correct.

YOLO: Ultralytics YOLOv8.0.49 🚀 Python-3.10.9 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 4090, 24217MiB) CUDA:1 (NVIDIA GeForce RTX 4090, 24215MiB)

**Comment by behroozazarkhalili** [comment]
> Your GPUs are correctly identified and utilized. The purpose of this console output is to provide confirmation to the user of that.
> 
> You've shown this output, so everything is correct.
> 
> YOLO: Ultralytics YOLOv8.0.49 🚀 Python-3.10.9 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 4090, 24217MiB) CUDA:1 (NVIDIA GeForce RTX 4090, 24215MiB)

@glenn-jocher thanks for the update. However my code does not run on GPUs and the output of the nvidia-smi command is the same as above figure.

Corps you please let me know what the issue is?

What do you require to reproduce the issue? I can provide the whole code if you require.

**Comment by Laughing-q** [comment]
@behroozazarkhalili the gpu works fine to me.
```python
from ultralytics import YOLO

model = YOLO("yolov8s.yaml")
# Train the model
model.train(data="coco128.yaml", epochs=500, imgsz=640, device="0,1")
```
![image](https://user-images.githubusercontent.com/61612323/223004741-939d9492-814e-4dd2-b255-a377af9320e4.png)

**Comment by behroozazarkhalili** [comment]
> @behroozazarkhalili the gpu works fine to me.
> 
> ```python
> from ultralytics import YOLO
> 
> model = YOLO("yolov8s.yaml")
> # Train the model
> model.train(data="coco128.yaml", epochs=500, imgsz=640, device="0,1")
> ```
> 
> ![image](https://user-images.githubusercontent.com/61612323/223004741-939d9492-814e-4dd2-b255-a377af9320e4.png)

@Laughing-q 
This code does not use GPUs in my system. Think the problem is my own side.

```python
from ultralytics import YOLO

model = YOLO("yolov8s.yaml")
# Train the model
model.train(data="coco128.yaml", epochs=500, imgsz=640, device="0,1")
```
keep it open to update from my side.
