### ISSUE TITLE
Example for YOLO-World - ONNX

### ISSUE THREAD

**Issue by AtiChetsurakul** [ultralytics/ultralytics#12674]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

In `examples` directories, I would like to request a example on how to use a ONNX format of yolo-world. Thank you.

### Use case

Just like the Yolo- V8 example.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! Thanks for reaching out with your request for an ONNX example with YOLO-World. Here's a quick example of how you can use the ONNX format of the YOLO-World model:

```python
import onnxruntime as ort
import numpy as np

# Load the ONNX model
session = ort.InferenceSession("path_to_yolo-world.onnx")

# Assuming you have a preprocessed image
img = np.random.rand(1, 3, 640, 640).astype("float32")

# Run inference
outputs = session.run(None, {'input': img})

# Process outputs
print(outputs)
```

This simple script loads the YOLO-World model in ONNX format, executes inference on a dummy image, and prints the outputs. Make sure to replace `"path_to_yolo-world.onnx"` with the actual path to your ONNX model file and also replace the dummy input image with your actual preprocessed image data.

I hope this helps! If you need more details or have any other questions, feel free to ask. 😊
