### ISSUE TITLE
OnnxSlim support

### ISSUE THREAD

**Issue by inisis** [ultralytics/ultralytics#12681]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi, we have developed a tool called [onnxslim](https://github.com/WeLoveAI/OnnxSlim), which can help slim exported onnx model, and it's pure python, and it works well on yolo, should we intergrate it into awesome [ultralytics](https://github.com/ultralytics/ultralytics).

### Use case

when export to onnx, we can use onnxslim to slim our exported model

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by inisis** [comment]
@glenn-jocher Can you take a look, I have tested on yolov8n model, and it works really good for reducing number of operators.

![image](https://github.com/ultralytics/ultralytics/assets/46103969/e03fa2b1-1fcb-4b8f-aa11-5c8e6bb241fb)

**Comment by Kayzwer** [comment]
@inisis does OnnxSlim also speed up for TensorRT (since model have to be convert to onnx first) ?

**Comment by inisis** [comment]
> @inisis does OnnxSlim also speed up for TensorRT (since model have to be convert to onnx first) ?

I do believe so, onnxslim depends on nv onnx-graphsurgeon, but have better perfromance.

**Comment by Kayzwer** [comment]
> > @inisis does OnnxSlim also speed up for TensorRT (since model have to be convert to onnx first) ?
> 
> I do believe so, onnxslim depends on nv onnx-graphsurgeon, but have better perfromance.

does it works with onnx-simplify?

**Comment by Kayzwer** [comment]
@inisis [pull request](https://github.com/ultralytics/ultralytics/pull/12683) for the integration, thanks for the tool :)

**Comment by inisis** [comment]
@Kayzwer Hi, CI failed, but I think it's not a problem with onnxslim, and how can I compare the performance with/without onnxslim, and one thing to mention, onnxslim can be used in arm devices.

**Comment by Kayzwer** [comment]
> @Kayzwer Hi, CI failed, but I think it's not a problem with onnxslim, and how can I compare the performance with/without onnxslim, and one thing to mention, onnxslim can be used in arm devices.

```
from ultralytics import YOLO

model = YOLO("yolov8n.pt")
model.export(format="onnx", slim=True) # slimmed

model.export(format="onnx")
```

**Comment by Kayzwer** [comment]
> > @Kayzwer Hi, CI failed, but I think it's not a problem with onnxslim, and how can I compare the performance with/without onnxslim, and one thing to mention, onnxslim can be used in arm devices.
> 
> ```
> from ultralytics import YOLO
> 
> model = YOLO("yolov8n.pt")
> model.export(format="onnx", slim=True) # slimmed
> 
> model.export(format="onnx")
> ```

make sure to rename the output onnx model and run the functions separately

**Comment by inisis** [comment]
> > > @Kayzwer Hi, CI failed, but I think it's not a problem with onnxslim, and how can I compare the performance with/without onnxslim, and one thing to mention, onnxslim can be used in arm devices.
> > 
> > 
> > ```
> > from ultralytics import YOLO
> > 
> > model = YOLO("yolov8n.pt")
> > model.export(format="onnx", slim=True) # slimmed
> > 
> > model.export(format="onnx")
> > ```
> 
> make sure to rename the output onnx model and run the functions separately

@Kayzwer thank you! But I think I have seen the benchmark performance before, and it's generated by CI.

**Comment by inisis** [comment]
> @inisis [pull request](https://github.com/ultralytics/ultralytics/pull/12683) for the integration, thanks for the tool :)

@glenn-jocher can you please review it

**Comment by glenn-jocher** [comment]
@inisis Thanks for the heads up! The PR is on Glenn's radar, and he'll review it as soon as possible. Thanks for your contribution! 🚀

**Comment by Kayzwer** [comment]
> @inisis Thanks for the heads up! The PR is on Glenn's radar, and he'll review it as soon as possible. Thanks for your contribution! 🚀

thanks LLM
