### ISSUE TITLE
yolov8 tags=8.2 The model could not be loaded

### ISSUE THREAD

**Issue by dzz-gg** [ultralytics/ultralytics#12687]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

![image](https://github.com/ultralytics/ultralytics/assets/123388591/779d2812-f1cb-4e57-8f93-a49ac9783b5b)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@dzz-gg see valid tags at https://github.com/ultralytics/ultralytics/tags
