### ISSUE TITLE
For running yolov8 on onnxruntime, would you consider enabling DML provider?

### ISSUE THREAD

**Issue by peterer0625** [ultralytics/ultralytics#12695]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

For running yolov8 on onnxruntime, would you consider enabling DML provider?

### Use case

Currently, for onnxruntime, yolov8 only enables CUDA and CPU providers.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! Thanks for bringing up the idea of enabling the DML provider for YOLOv8 on ONNX Runtime. Currently, we support CUDA and CPU providers, but we're always looking to enhance the accessibility and performance of our models across different platforms.

While we don't have immediate plans to integrate DML provider support, we appreciate your suggestion and will consider it for future updates. If you're interested in contributing to this feature, we welcome community contributions and would be happy to review a PR from you!

Feel free to keep the suggestions coming! 🚀
