### ISSUE TITLE
Make Yolo8 colab output not a mess

### ISSUE THREAD

**Issue by satyrmipt** [ultralytics/ultralytics#12699]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Have you ever seen how yolo train process output looks in Google Colab?
Could you make table with intermediate results more stuctured?
![Capture](https://github.com/ultralytics/ultralytics/assets/113777913/c269faa1-8748-4054-8723-38c644c81d53)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi there! Thanks for reaching out with your feedback on the YOLOv8 outputs in Google Colab.

I understand your concern about the structure of the output tables during training. Enhancing readability is indeed crucial, especially for monitoring model progress effectively.

A quick tip to improve the current display in Colab might involve using Python’s `rich` library to print more visually structured tables. Here is a small example of how you could format the output more neatly:

```python
from rich.console import Console
from rich.table import Table

console = Console()

table = Table(show_header=True, header_style="bold magenta")
table.add_column("Epoch", style="dim", width=12)
table.add_column("Loss")
table.add_column("Accuracy", justify="right")

# Assuming you fetch these values from the training process
table.add_row("1", "0.456", "85%")
table.add_row("2", "0.342", "88%")
table.add_row("3", "0.310", "90%")

console.print(table)
```

This approach should streamline the visual presentation of your logs in Colab. If you have more suggestions or need further modifications, please feel free to share! 😊
