### ISSUE TITLE
Yolov9-e and yolov9 -c configuration difference between official repo and ultralytics

### ISSUE THREAD

**Issue by deepukr007** [ultralytics/ultralytics#12693]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,
Thank you so much for great repo,

I was comparing yolov9 yaml files between ultralytics and the official implementation from WongKinYiu

I see that yolov9-e is same between two repos , except there is anchor in original yaml file which is missing in ultralytics.
but , 
There is a huge difference in the configuration of yolov9-c i,e Auxillary reversible branch is not included in the ultralytics.

why is this so ? 
It would be great if this information was in ultralytics docs somewhere.

**Comment by glenn-jocher** [comment]
Hello,

Thanks for reaching out and for your keen observations! 🌟

Indeed, the differences you've noted in the YOLOv9-e and YOLOv9-c configurations between the Ultralytics version and WongKinYiu's official implementation are accurate. In Ultralytics, we occasionally adapt configurations and model architectures to optimize for performance and ease of use in diverse application scenarios, which may explain the absence of certain implementation details like the anchor in the YOLOv9-e and the reversible auxiliary branch in YOLOv9-c.

We appreciate your suggestion about including these details in the Ultralytics documentation. It's feedback like yours that helps us improve and better serve the community. I will relay this to our documentation team for consideration in future updates.

If you have further questions or need more assistance, feel free to ask!
