### ISSUE TITLE
YOLOv8 OBB detection angle issue

### ISSUE THREAD

**Issue by CCCCccc8825** [ultralytics/ultralytics#12696]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello! First of all, thank you very much for your team's outstanding contributions! I am using YOLOv8OBB to complete my own project, but I have noticed some issues: the angle of the detection object is always between [0180 °], and there is no distinction between the head and tail of the object recognition. I am not sure if it is because the model itself cannot recognize the difference between 0 ° and 180 °, or if it is a problem with my own dataset or operation. How can I achieve directed detection of yolov8-OBB to detect the head and tail of the target object? What modifications should I make to which item in the source file?

### Additional

Secondly, I read the head.py in the model and found that according to theory, the output angle after detection should be between -45 ° and 135 °, but my output angle is between 0 ° and 180 °. What is the reason for this?

**Comment by glenn-jocher** [comment]
Hello! Thanks for reaching out and for your kind words about the project. It’s great to hear you're making use of YOLOv8 OBB for your own projects!

Regarding the OBB angle outputs, the model itself provides angle predictions that typically cover the 0° to 180° range, leveraging cosine and sine encoding which inherently consider angles symmetrical around 180° (making 0° indistinguishable from 180°). To enable directed detection and differentiate between the head and tail of objects, you might need to adjust or extend the model architecture to encode additional directional information or consider post-processing techniques that incorporate context or sequence data.

For the discrepancy in angle ranges from what you expected based on `head.py`, it’s possible that the observed behavior might result from different configurations or interpretations. OBB outputs use the atan2 function, which should provide a range of [−π, π] (or in degrees, -180° to 180°), adjusted to [0°, 180°] for practical use and symmetry. If this isn’t the case, I recommend reviewing the data preprocessing and augmentation stages and how the angles are manipulated or constrained during these phases.

Your insights and queries help improve YOLOv8, so I appreciate your detailed exploration. If this doesn't resolve your issue, consider providing a minimal reproduction of the error, and we can investigate further! 😊
