### ISSUE TITLE
Failed to export a YOLOv8-det model to onnx with fp16.

### ISSUE THREAD

**Issue by LorenzoSun-V** [ultralytics/ultralytics#12721]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I used the command to export onnx with fp16:
```
yolo export model=/path/to/my/best.pt format=onnx imgsz=640 half=True
```
But it seems to be fp32 when I open it by Netron:
![image](https://github.com/ultralytics/ultralytics/assets/42413198/b143aba1-1f2c-4b66-b3be-d05956f27555)
In addition, the size of exported onnx model doesn't get smaller.
Do you have any ideas about this phenomenon?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! Thanks for reaching out. It appears that you encountered an issue where the exported ONNX model remains in FP32 despite specifying FP16. This can happen since some model components might not fully support FP16, or implementation may default back to FP32 for stability. 

It's essential to verify that all components of your model are compatible with FP16. For now, please ensure you're using the latest version of the export tool and YOLOv8, as updates might contain fixes or enhancements for such features.

If all else seems correct, please consider opening an issue with more detailed environment information so we can help diagnose the problem more effectively!

**Comment by LorenzoSun-V** [comment]
Hi, the ultralytics pkg version in my environment is 8.2.15:
![image](https://github.com/ultralytics/ultralytics/assets/42413198/e42374c1-4a04-4215-ab24-71c5d5e8b424)

And my train file is:
```
import argparse
from ultralytics import YOLO


def parse_opt():
    parser = argparse.ArgumentParser()
    parser.add_argument('--weights', type=str, default='yolov8s.pt', help='path to model file, i.e. yolov8n.pt, yolov8n.yaml')
    parser.add_argument('--data', type=str, default='ultralytics/cfg/datasets/coco128.yaml', help='dataset.yaml path')
    parser.add_argument('--epochs', type=int, default=300)
    parser.add_argument('--batch', type=int, default=16, help='total batch size for all GPUs')
    parser.add_argument('--workers', type=int, default=8, help='maximum number of dataloader workers')
    parser.add_argument('--imgsz', '--img', '--img-size', nargs='+', type=int, default=[640], help='inference size h,w')
    parser.add_argument('--device', default=None, help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
    parser.add_argument('--project', default='runs/train', help='save to project/name')
    parser.add_argument('--name', default='exp', help='save to project/name')
    parser.add_argument('--patience', type=int, default=50, help='epochs to wait for no observable improvement for early stopping of training')
    parser.add_argument('--close-mosaic', type=int, default=10, help='(int) disable mosaic augmentation for final epochs (0 to disable)')
    parser.add_argument('--resume', action='store_true', help='resume training from last checkpoint')
    parser.add_argument('--lr0', type=float, default=0.01, help='initial learning rate (i.e. SGD=1E-2, Adam=1E-3)')
    parser.add_argument('--lrf', type=float, default=0.01, help='final learning rate (lr0 * lrf)')
    parser.add_argument('--exist-ok', action='store_true', help='existing project/name ok, do not increment')
    parser.add_argument('--box', type=float, default=7.5, help='box loss gain')
    parser.add_argument('--cls', type=float, default=0.5, help='cls loss gain (scale with pixels)')
    parser.add_argument('--dfl', type=float, default=1.5, help='dfl loss gain')
    opt = parser.parse_args()
    opt.imgsz *= 2 if len(opt.imgsz) == 1 else 1  # expand
    return opt


def main(opt):
    model = YOLO(f"{opt.weights}")

    model.train(data=opt.data, 
                epochs=opt.epochs, 
                batch=opt.batch,
                workers=opt.workers,
                imgsz=opt.imgsz,
                device=opt.device,
                project=opt.project,
                name=opt.name,
                patience=opt.patience,
                close_mosaic=opt.close_mosaic,
                resume=opt.resume,
                lr0=opt.lr0,
                lrf=opt.lrf,
                exist_ok=opt.exist_ok,
                box=opt.box,
                cls=opt.cls,
                dfl=opt.dfl
    )


if __name__ == "__main__":
    opt = parse_opt()
    main(opt)
```
The train script is:
```
python tools/train.py \
    --weights ${pretrained} \
    --data ${data} \
    --epochs ${epochs} \
    --batch ${batch} \
    --imgsz ${imgsz} \
    --device ${device} \
    --project ${project} \
    --name ${name} \
    --patience 50
```

I used `yolo export model=/path/to/my/best.pt format=onnx imgsz=640 half=True` to export onnx.

It seems that everything is right but I don't get expected results.

**Comment by LorenzoSun-V** [comment]
The versions of related onnx pkgs are showed as following:
![image](https://github.com/ultralytics/ultralytics/assets/42413198/a35f0abc-bf5c-4602-aea4-21708d25af30)

**Comment by glenn-jocher** [comment]
@LorenzoSun-V hello! Thank you for sharing the version details of your ONNX packages. From the versions you've listed, it seems your setup should be compatible with exporting ONNX models in FP16. However, if the export still doesn’t reflect FP16 precision, you might want to ensure that all the operations in your model are supported in FP16 on ONNX. Sometimes, specific operations can cause the model to revert to FP32.

Additionally, please double-check the export command for any typos, especially around the `half=True` argument (it should be `half=true` in lowercase) to guarantee that FP16 is being requested correctly.

If issues persist, this might be specific to how ONNX handles FP16 conversion internally for certain operations. Upgrading to the latest version of the ONNX library might also help if not already using it.

Hope this helps! 😊

**Comment by LorenzoSun-V** [comment]
Hi, I firgue out the points failing to export fp16 onnx model.
In export code:
![image](https://github.com/ultralytics/ultralytics/assets/42413198/4a7709ef-17e5-4718-bfab-afa80e14c59b)
![image](https://github.com/ultralytics/ultralytics/assets/42413198/aeada143-1710-4f9e-96d6-ec94fbe756a8)

So I used `yolo export model=/path/to/my/best.pt format=onnx imgsz=640 half=true device=0` to export fp16 onnx model successfully. 
![image](https://github.com/ultralytics/ultralytics/assets/42413198/d9e16009-e85e-43ea-bc0a-2c2eacde86dc)

Hence I encounter another qusetion, can this fp16 onnx model run on CPU?

**Comment by LorenzoSun-V** [comment]
I use this [example](https://github.com/ultralytics/ultralytics/blob/main/examples/YOLOv8-ONNXRuntime/main.py) to infer image by FP16 onnx model successfully on CPU. But failed on CUDA:
![image](https://github.com/ultralytics/ultralytics/assets/42413198/48886322-c979-4b37-97ea-edb8c209b498)

**Comment by glenn-jocher** [comment]
Hello! It's great to hear that you've successfully run the FP16 ONNX model on the CPU. Regarding the issue with CUDA, it seems like there might be a compatibility issue with FP16 and your CUDA setup. 

Could you please ensure that your GPU supports FP16 operations and that the latest drivers and CUDA versions are installed? Sometimes, updating these can resolve such issues.

If the problem persists, consider using the FP32 model for CUDA inference, as it generally has broader support across different GPU architectures. Here's a quick example of how to force FP32 during the export if needed:

```bash
yolo export model=/path/to/my/best.pt format=onnx imgsz=640 half=false device=0
```

Hope this helps! 😊 Let us know how it goes!

**Comment by LorenzoSun-V** [comment]
Hi, the code in [example](https://github.com/ultralytics/ultralytics/blob/main/examples/YOLOv8-ONNXRuntime/main.py) doesn't include `letterbox` so the results of ONNX are quite different from those of pt. The results of ONNX are much closer to those of pt after adding `letterbox` in preprocess function. I suppose it's better to add `letterbox` in preprocess function.

**Comment by glenn-jocher** [comment]
Hello! Thanks for pointing this out. You're absolutely right; including `letterbox` in the preprocessing function can help align the ONNX model's results more closely with the PyTorch model's outputs, especially since it maintains the aspect ratio of the original images.

Here's a quick example of how you might modify the preprocessing function to include `letterbox`:

```python
def preprocess(img_path):
    img = Image.open(img_path)
    img = letterbox(img, new_shape=(640, 640))[0]
    img = img.transpose((2, 0, 1))  # HWC to CHW
    img = np.ascontiguousarray(img)
    return img
```

This should help standardize the input and improve the model's performance consistency across different formats. Thanks for your suggestion! 😊

**Comment by LorenzoSun-V** [comment]
Thanks for your patient reply! Everything is running correctly now.

**Comment by glenn-jocher** [comment]
That's great to hear! If you have any more questions or need further assistance in the future, feel free to reach out. Happy coding! 😊

**Comment by Petros626** [comment]
@glenn-jocher how to specify `data` when exporting to FP16? Dataset calibration isn't needed, but the exporter uses `coco8.yaml` by default. How to avoid this default behaviour for FP16?

Additionally how to influence the size of the calibration dataset for INT8 via `data=kitti_bev.yaml` argument. How many samples are taken for calibration?

**Comment by glenn-jocher** [comment]
For FP16 exports, the `data` argument isn't used - you can safely omit it as no calibration occurs. The default `coco8.yaml` is simply a placeholder. For INT8 calibration, the exporter uses **all images from the validation split** of your specified dataset (e.g., `data=kitti_bev.yaml`). The number of calibration samples equals your val set size in the YAML. 

To control calibration size:
1. Ensure your dataset YAML's `val` split contains desired number of images
2. The exporter will warn if <300 samples but still proceed

For implementation details see the [TensorRT calibration logic](https://docs.ultralytics.com/integrations/tensorrt/#configuring-int8-export) in our docs.

**Comment by Petros626** [comment]
Okay a placeholder makes sense, because I thought the code tries to take the `coco8.yaml` for FP16, which would lead to false use of my dataset.

1. What you mean by `val` split contains desired number of images? My yaml contains just the paths to the images:
```yaml
path: /home/heizung1/ultralytics_yolov8-obb_ob_kitti/ultralytics/cfg/datasets/kitti # dataset root dir
train: images/train/ # train images (relative to 'path') 18560 images (3712 training images extended with data augmentation)
val: images/val/ # val images (relative to 'path') 3769 images
test: # test images (optional)
```
2. The val data are 3769 images so no worries :)

**Comment by glenn-jocher** [comment]
Great! For **FP16 exports**, the `data` argument is indeed ignored as no calibration occurs. For **INT8 calibration**, your `kitti.yaml` val split with 3769 images is perfect since TensorRT will use all val images automatically. The warning only appears if <300 images. You're all set! 😊

**Comment by Petros626** [comment]
okay the argument `data` doesn't play a role for FP16. 
Thank you very much.

**Comment by glenn-jocher** [comment]
@Petros626 you're welcome! That's correct, the `data` argument isn't needed for FP16 exports since no calibration is required. Let us know if you have any other questions about Ultralytics YOLO exports! 😊

**Comment by Petros626** [comment]
Got it!

**Comment by glenn-jocher** [comment]
Great! For **FP16 exports**, the `data` argument isn't needed since no calibration occurs. For **INT8 calibration**, your `kitti.yaml` val split with 3769 images is perfect since TensorRT will use all val images automatically. The warning only appears if <300 images. You're all set! 😊 

For implementation details, see [TensorRT calibration logic](https://docs.ultralytics.com/integrations/tensorrt/#configuring-int8-export) in our docs.

**Comment by Petros626** [comment]
@glenn-jocher the `simplify` argument for exporting is default `True`. Is it required when exporting to `TensorRT` or only `ONNX`?
Is multi GPU export supported, to test the model later on two devices (device=[0,1])?

**Comment by glenn-jocher** [comment]
1. The `simplify` argument applies only to ONNX exports and doesn't affect TensorRT exports. For ONNX, it's enabled by default to optimize the graph.  
2. Correct, `optimize=True` is specific to TorchScript exports for mobile optimization and doesn't impact TensorRT exports.  
3. Multi-GPU export isn't currently supported. TensorRT exports must target a single GPU device (e.g., `device=0`).  

For implementation details, see the [TensorRT export arguments](https://docs.ultralytics.com/integrations/tensorrt/#export-arguments) and [export configuration docs](https://docs.ultralytics.com/modes/export/#arguments).

**Comment by Petros626** [comment]
Thank you, I'm good to go now.

**Comment by glenn-jocher** [comment]
Great to hear you're all set! For future reference, you can find detailed export guidance in the Ultralytics YOLO [Export Documentation](https://docs.ultralytics.com/modes/export/). Happy coding! 😊

**Comment by Petros626** [comment]
you mentioned the use of all validation images with INT8, why are only so many batches displayed then?

```txt
TensorRT: collecting INT8 calibration images from 'data=/home/heizung1/ultralytics_yolov8-obb_ob_kitti/ultralytics/cfg/datasets/kitti_bev.yaml'
Scanning /home/heizung1/ultralytics_yolov8-obb_ob_kitti/ultralytics/cfg/datasets/kitti/labels/val.cache... 3699 images, 0 backgrounds, 0 corrupt: 100%|██████████| 3699/3699 [00:00<?, ?it/s]

[02/27/2025-15:04:41] [TRT] [I] Starting Calibration.
[02/27/2025-15:04:42] [TRT] [I]   Calibrated batch 0 in 0.902334 seconds.
[02/27/2025-15:04:43] [TRT] [I]   Calibrated batch 1 in 0.897787 seconds.
[02/27/2025-15:04:44] [TRT] [I]   Calibrated batch 2 in 0.836568 seconds.
.
.
.
.
[02/27/2025-15:08:24] [TRT] [I]   Calibrated batch 230 in 0.853519 seconds.
[02/27/2025-15:08:25] [TRT] [I]   Calibrated batch 231 in 0.903413 seconds.
[02/27/2025-15:08:45] [TRT] [I]   Post Processing Calibration data in 19.986 seconds.
[02/27/2025-15:08:45] [TRT] [I] Calibration completed in 248.102 seconds.
```

Did the exporter just took 231 images from the 3699 images to calibrate the `INT8` model or how is it meant.

**Comment by glenn-jocher** [comment]
The calibration process uses **all 3699 validation images** from your dataset. The displayed batches (0-231) represent **232 batches** of `batch=2 * [your specified batch size]` as mentioned in the [TensorRT calibration logic](https://docs.ultralytics.com/integrations/tensorrt/#configuring-int8-export). For example, with default `batch=1`, TensorRT uses `batch=2` during calibration, resulting in `3699/2≈1850` batches. Your logs show fewer batches because you likely set a higher `batch` value, which we automatically double during calibration.

**Comment by Petros626** [comment]
Thanks for the clarification!

**Comment by Petros626** [comment]
I'll test which batch size in my case lead to the best metrics.

**Comment by glenn-jocher** [comment]
Great approach! For INT8 calibration, your selected `batch` value will determine how many images are used per calibration batch (2x your specified batch size). We recommend experimenting with different values while monitoring validation metrics like mAP50/mAP50-95. The [TensorRT INT8 calibration docs](https://docs.ultralytics.com/integrations/tensorrt/#configuring-int8-export) show how batch size impacts both calibration quality and inference speed. Happy testing! 😊

**Comment by Petros626** [comment]
I choose to stay with `batch=1` for FP16 model and `batch=8` for INT8 model. Important note that `dynamic=True` is enforced, when using INT8 export.

**Comment by Petros626** [comment]
@glenn-jocher I'm now experimenting with the batch size and found for FP16 `batch=1` good enough `mAP` values. 
How can I limit the number of calibration images in the exporter, so that instead of my 3699 validation images only e.g. 1500 are taken?

**Comment by glenn-jocher** [comment]
Great question! TensorRT requires fixed dimensions (batch, height, width) when `dynamic=False`, meaning the exported model will be locked to the exact batch size and image size used during export. We enable `dynamic=True` by default for INT8/F16 exports to maintain flexibility in batch/input sizes. For implementation details, see the [TensorRT export arguments](https://docs.ultralytics.com/integrations/tensorrt/#export-arguments) in our docs.

**Comment by glenn-jocher** [comment]
The error occurs because **TensorRT requires fixed dimensions when `dynamic=False`**. Your export locked the model to `batch=16`, but validation is attempting a smaller batch (3 in your error). To resolve:

1. **Keep `dynamic=True`** during export to handle variable batch sizes flexibly.
2. If using `dynamic=False`, ensure **all validation batches exactly match `batch=16`** (no partial batches).

For details, see the [TensorRT dynamic axes documentation](https://docs.ultralytics.com/integrations/tensorrt/#export-arguments).

**Comment by Petros626** [comment]
but why validation is attempting `batch=3` when I set in to 16 in `model.val()`?

**Comment by glenn-jocher** [comment]
The partial batch of 3 occurs because your validation dataset's total images (3699) aren't perfectly divisible by `batch=16`, creating a final partial batch. When using `dynamic=False`, TensorRT requires exact batch matching. To resolve:

1. Ensure your dataset length is divisible by the batch size (e.g., 3696 images for `batch=16`), **or**
2. Use `dynamic=True` during export to handle variable batch sizes natively

This behavior stems from TensorRT's fixed-dimension requirements when `dynamic=False`, as outlined in the [TensorRT export arguments documentation](https://docs.ultralytics.com/integrations/tensorrt/#export-arguments).

**Comment by Petros626** [comment]
I stay with `dynamic=True` and `batch=16` for export. It works.

**Comment by glenn-jocher** [comment]
Great to hear that worked! Using `dynamic=True` is indeed recommended for TensorRT exports to handle variable batch sizes effectively. For more details on optimizing TensorRT exports, check out our [TensorRT integration guide](https://docs.ultralytics.com/integrations/tensorrt/). 😊
