### ISSUE TITLE
Customizing TTA mode.

### ISSUE THREAD

**Issue by mandal4** [ultralytics/ultralytics#12722]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'd like to customize TTA mode during prediction.
I searched previous issues like [this](https://github.com/ultralytics/ultralytics/issues/1469#issuecomment-1596485895).
But still i can find where is the implementation of the TTA. (test_transforms function do not exists in the models.py..!)

**Comment by mandal4** [comment]
I found it in _predict_augment function in ultralytics/nn/task.py.

**Comment by glenn-jocher** [comment]
Great find! Yes, that is the correct location where test-time augmentation (TTA) is implemented in the newer YOLO versions. The `_predict_augment` function in `ultralytics/nn/task.py` handles the augmentation logic for predictions. If you have any further questions about customizing it or need additional help, feel free to ask! 🚀

**Comment by lsh9** [comment]
> Great find! Yes, that is the correct location where test-time augmentation (TTA) is implemented in the newer YOLO versions. The `_predict_augment` function in `ultralytics/nn/task.py` handles the augmentation logic for predictions. If you have any further questions about customizing it or need additional help, feel free to ask! 🚀

hello! this function returns None as proto for segmentation tasks, as #15763, does it mean tta hasn't finished for segmentation tasks?

**Comment by glenn-jocher** [comment]
Hello! The `_predict_augment` function currently does not fully support TTA for segmentation tasks. This feature is still under development. If you encounter issues, please check for updates in future releases.
