### ISSUE TITLE
![k](https://user-images.githubusercontent.com/126906353/222906463-80f75d71-4105-4d04-a112-f7d72d851f7f.jpg)

### ISSUE THREAD

**Issue by SivaBodapati** [ultralytics/ultralytics#1272]
![k](https://user-images.githubusercontent.com/126906353/222906463-80f75d71-4105-4d04-a112-f7d72d851f7f.jpg)

In the above image we can see conf as 0.89 like that, how we can print accuracy of Red Chilli

_Originally posted by @SivaBodapati in https://github.com/ultralytics/ultralytics/issues/1262#issuecomment-1454750449_

**Comment by glenn-jocher** [comment]
@SivaBodapati accuracy is a classification metrics applied on a population of many images in a validation or test set.

You are showing a detection result on a single image. The two topics are not related.
