### ISSUE TITLE
Trying to connect a new module to yolov8 architecture

### ISSUE THREAD

**Issue by N0lanakis** [ultralytics/ultralytics#12731]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey,

im trying to connect to the current yolov8 architecture a new module 

class mymodule(nn.Module):
    def __init__(self, test_size):
        super(mymodule, self).__init__()
        self.C = test_size
        self.dcl = dcl(self.C, self.C)
    def forward(self, input1, input2):
        .........
        return x
        
        
i want this module to take input from 2 previous layers for example [-1,10].

in the yaml file i write

   - [[-1,10], 1, mymodule, [512]]

in tasks.py i write
.....
 elif m is AIFI:
            args = [ch[f], *args]
elif m is mymodule: 
            args = [ch[1]]
            
Also i register my block to every possible file.

when i try to train i got

File "/usr/src/ultralytics/ultralytics/nn/tasks.py", line 91, in forward
    return self.predict(x, *args, **kwargs)
  File "/usr/src/ultralytics/ultralytics/nn/tasks.py", line 109, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "/usr/src/ultralytics/ultralytics/nn/tasks.py", line 130, in _predict_once
    x = m(x)  # run
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: mymodule.forward() missing 1 required positional argument: 'input2'
            

what may happens?

**Comment by glenn-jocher** [comment]
Hello!

It looks like you've done a good job implementing your custom module and integrating it with the YOLOv8 architecture. The error you're facing suggests that the `mymodule` isn't receiving the second required input `input2` during the forward pass.

In your `tasks.py` file, make sure that when you call `mymodule`, both input tensors are passed correctly. From your description, it seems you want to fetch outputs from two layers for use as inputs. Here's how you can adjust that:

```python
elif m is mymodule:
    args = [ch[-1], ch[10]]  # This will pass the outputs from layers indexed at -1 and 10
```

Make sure that the indices `-1` and `10` correctly refer to the outputs from the specific layers you intend to use as inputs.

After adjusting this in `tasks.py`, your module should receive both inputs as expected. Please try this modification, and I hope your training runs smoothly! Let me know if you encounter any further issues.

**Comment by N0lanakis** [comment]
Thanks for the answer.

i tried to fix that but it still not work.

i add

elif m is mymodule: #temporary dependancy
            args = [ch[-1],ch[10]]
            
   File "/usr/src/ultralytics/myutils/train.py", line 9, in <module>
    model = YOLO('/usr/src/ultralytics/myutils/yolov8l-seg-test.yaml')
  File "/usr/src/ultralytics/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/usr/src/ultralytics/ultralytics/engine/model.py", line 140, in __init__
    self._new(model, task=task, verbose=verbose)
  File "/usr/src/ultralytics/ultralytics/engine/model.py", line 211, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "/usr/src/ultralytics/ultralytics/nn/tasks.py", line 369, in __init__
    super().__init__(cfg=cfg, ch=ch, nc=nc, verbose=verbose)
  File "/usr/src/ultralytics/ultralytics/nn/tasks.py", line 299, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in forward(torch.zeros(1, ch, s, s))])  # forward
  File "/usr/src/ultralytics/ultralytics/nn/tasks.py", line 298, in <lambda>
    forward = lambda x: self.forward(x)[0] if isinstance(m, (Segment, Pose, OBB)) else self.forward(x)
  File "/usr/src/ultralytics/ultralytics/nn/tasks.py", line 91, in forward
    return self.predict(x, *args, **kwargs)
  File "/usr/src/ultralytics/ultralytics/nn/tasks.py", line 109, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "/usr/src/ultralytics/ultralytics/nn/tasks.py", line 130, in _predict_once
    x = m(x)  # run
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: VisualAttentionBlock.forward() missing 1 required positional argument: 'input2'

also if i fix this problem i want to be able to change the inputs to this block becaues it will be used more times. so pushing args = [ch[-1], ch[10]] makes me not able to changed them later?

**Comment by glenn-jocher** [comment]
@N0lanakis hey,

Thanks for the update! It appears that the issue lies with how the inputs are passed to your custom module in the forward pass. In your `tasks.py`, ensure that you are actually passing both required inputs when you call your `mymodule`. Based on the details you've provided, instead of setting `args` directly in the conditional block, you should modify how `mymodule` is invoked with these inputs:

```python
x = m(x, args[0], args[1]) if isinstance(m, mymodule) else m(x)
```

For greater flexibility in changing the inputs dynamically, consider managing the inputs outside the static indices directly in your configuration or setup logic, allowing you to modify which layers are connected without changing the code every time.

Give these adjustments a try, and let me know how it goes! 🚀
