### ISSUE TITLE
Is Yolo v8 faster than mobile ssd 

### ISSUE THREAD

**Issue by totoadel** [ultralytics/ultralytics#1274]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Are Yolo v8 faster than mobile ssd?

**Comment by AyushExel** [comment]
I've not used mobile ssd but you can compare their inference & training speeds by running a simple example on both

**Comment by totoadel** [comment]
@AyushExel ok thank you
