### ISSUE TITLE
Model load results in 'indexerror : list out of range '

### ISSUE THREAD

**Issue by palmcorp** [ultralytics/ultralytics#12758]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Folks,
Am continuing to pull this error: list index out of range.   Have searched blogs and did not find a similar problem.
Suggestions would be welcome
Best,
Paul Petronelli
[palm@palmcorp.com](mailto:palm@palmcorp.com)

Similar Problems:
Indexerror: list out of range while training in YOLOv8 #5085 

Environment:
1.	Python 3.10.12
2.	Platform CoLab
3.	Ultralytics  v8.2.16
4.	Nvidia Tesla T4
5.	CVAT running on a docker image

Background:
1.	Program based on flow demonstrated in:  https://[github.com/ultralytics/ultralytics/issues/1915](http://github.com/ultralytics/ultralytics/issues/1915)"
2.	Keypoints defined using CVAT
3.	Keypoints exported as COCO Keypont 1.0
4.	The keypoints converted to yolo keypoint using :  https://github.com/ultralytics/JSON2YOLO/issues/45
5.	The program runs well on the coco dataset.
6.	Running similar data organization on a custom dataset is always exits on the index problem.  
7.	The number of classes in the data.yaml were drawn from the export file: classes.txt which is from the CVAT export

Detailed flow follows:

Error stops:

model = YOLO(ECHO_YAMAL)

 [/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py](https://localhost:8080/) in <listcomp>(.0)
    915             c2 = sum(ch[x] for x in f)
    916         elif m in {Detect, WorldDetect, Segment, Pose, OBB, ImagePoolingAttn}:
--> 917             args.append([ch[x] for x in f])
    918             if m is Segment:c
    919                 args[2] = make_divisible(min(args[2], max_channels) * width, 8)

IndexError: list index out of range

Data.yaml follows:
ECHO_YAMAL =/content/YAML/data.yaml.v3.yaml
model = YOLO(ECHO_YAMAL)
#keypoint data sets

# Data
#path: D:POSE/data
path: /content/datasets/echo-pose
train: images/train2017   # subsets to D
val:   images/val2017 # relative to path

# Keypoints
kpt_shape: [4,3]  # number of keypoints, number of dim
flip_indx: [0,1,2,3]  # no flipping

#backbone:  uskng standard backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9
#usn standard head

head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 8], 1, Concat, [1]] # cat backbone P5
  - [-1, 3, C2, [768, False]] # 14

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2, [512, False]] # 17

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2, [256, False]] # 20 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 17], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2, [512, False]] # 23 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 14], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2, [768, False]] # 26 (P5/32-large)

  - [-1, 1, Conv, [768, 3, 2]]
  - [[-1, 11], 1, Concat, [1]] # cat head P6
  - [-1, 3, C2, [1024, False]] # 29 (P6/64-xlarge)

  - [[20, 23, 26, 29], 1, Pose, [nc, kpt_shape]] # Pose(P3, P4, P5, P6)

# Classes
names:
  0: class0
  1: class1
  2: class2
  3: class3
  4: class4

**Comment by glenn-jocher** [comment]
Hello Paul,

It looks like you're encountering an `IndexError` during model initialization which often points to a mismatch between the defined layers in your model configuration and the indexed referencing in the script.

Given your traceback and the details in `args.append` within the `error stops` section of your description, it seems like the list `ch` might not be correctly populated or its length is shorter than the indices being accessed (`x` in your list comprehension).

Check to make sure that:

1. The number of output channels (`ch`) matches the references in your model configuration. It seems the script expects a certain length of this list which isn't met.
2. In your YAML configurations, all references to indices `x` match up to actual defined layers. Each `-1` refers to the immediate last layer output, so make sure any direct indices are accurately pointing to an existing layer's output.

You might want to print/debug the actual length and contents of `ch` just before the line causing the error to see if it aligns with expectations from the YAML.

If issues persist, feel free to share here more snippets around where `ch` is defined or manipulated.

Hope this helps!

**Comment by palmcorp** [comment]
Thanks glenn-jocher  -appreciated.  Will look into your suggestions

**Comment by palmcorp** [comment]
Hey Glenn,

Appreciate the fast response.  Am working on a new startup and Yolov8 is at the core of our product.  Will keep the team informed when we publish the results.

Best,

Paul

 

-- 

==============================

Paul L Petronelli

CEO

PALM Associates, Inc.

***@***.***

 

paul.petronelli [skype]

(408) 582-8056 [cell]

http://www.palmcorp.com

 

These statements are subject to the PALM Associates, Inc.  Proprietary &

Confidentiality Agreement a.k.a. NDA. This is not an offer, even if terms

of an offer are discussed hypothetically. Pursuant to the express terms of

the NDA, only offers for sale that are the subject of a written definitive

agreement, signed by all the parties to that agreement, shall have any

legal effect. Prior to such definitive agreements, if any, no discussion

between and among the parties shall have any legal effect whatsoever.

**Comment by glenn-jocher** [comment]
Hey Paul,

Great to hear that YOLOv8 is playing a pivotal role in your startup! We're excited to see the innovative ways you'll leverage it. Looking forward to your published results and wishing your team all the best. If you need further assistance or have more insights to share as you progress, feel free to reach out. 🚀

**Comment by palmcorp** [comment]
Hi Glenn,

Thanks for the advice.  After adjusting the yaml file, the model load was successful.  Now a curious problem: labels are being rejected.

Any suggestions would be appreciated.

Best,

Paul

 

Labels are being rejected with this error: 

train: WARNING ⚠️ /content/datasets/echo-pose/images/train2017/frame_000126.PNG: ignoring corrupt image/label: labels require 13 columns each

 

It seems that we  have 13:

Classes: cls = 5

Keypoints = 4 

Box: 4 

Total = 13

 

Sample labels:

Frame 126:

0 0.530067 0.595424 0.291592 0.107217 0.38427 0.649032 2 0.530625 0.582648 2 0.601607 0.558288 2 0.675863 0.541815 2 0.451339 0.599032 2

Frame 127:

0 0.571176 0.576868 0.255804 0.0676042 0.443273 0.610669 2 0.587857 0.573154 2 0.646458 0.554479 2 0.699077 0.543065 2 0.510907 0.58238 2

 

My interpretation of the labels:

0                                                               CLASS

0.530067 0.595424 0.291592 0.107217      BOX

0.38427  0.649032 2                                   KEYPOINTS + VISIBILITY

0.530625 0.582648 2 

0.601607 0.558288 2 

0.675863 0.541815 2 

0.451339 0.599032 2

 

 

Enclosed:

data.yaml

**Comment by glenn-jocher** [comment]
Hey Paul,

Great to hear the YAML adjustment worked out! Regarding the label issue, it seems there might be a mismatch in the expected format. Each label should strictly follow the format required by YOLOv8, including the correct number of columns for classes, bounding boxes, and keypoints.

Make sure each line in your label files strictly adheres to the expected format without any additional spaces or separators that might be interpreted as extra columns. Also, ensure that the visibility flag for keypoints (if used) is correctly formatted.

If the problem persists, it might help to manually verify a few label files to ensure they match the expected structure exactly. Sometimes, even a small deviation can cause such errors.

**Comment by palmcorp** [comment]
Thanks again.

Will update a couple of labels and see if they pass the test.

Best,

Paul

 

==============================

Paul L Petronelli

Solution Architect

PALM Associates, Inc.

***@***.***

 

paul.petronelli[skype]

(408) 582-8056 [cell]

http://www.palmcorp.com

 

These statements are subject to the PALM Associates, Inc.  Proprietary &

Confidentiality Agreement a.k.a. NDA. This is not an offer, even if terms

of an offer are discussed hypothetically. Pursuant to the express terms of

the NDA, only offers for sale that are the subject of a written definitive

agreement, signed by all the parties to that agreement, shall have any

legal effect. Prior to such definitive agreements, if any, no discussion

between and among the parties shall have any legal effect whatsoever.

**Comment by palmcorp** [comment]
Hi Glenn & co:

This error persists:

 

train: WARNING ⚠️ /content/datasets/echo-pose/images/train2017/frame_000000.PNG: ignoring corrupt image/label: labels require 13 columns each

 

Here is an example of the original label converted from CVAT export:

 

0 0.672969 0.600513 0.240104 0.0716815 0.552916 0.636354 2 0.695014 0.614136 2 0.753377 0.597619 2 0.79302 0.564672 2 0.621607 0.631577 2 

 

I added null key points to labels   000, 001,002  to see if that helped, but didn’t pass.

 

3 of the labels were expanded manually to include null keypoints. For example:

 

0 0.683393 0.603251 0.211935 0.0538542 0.577425 0.630178 2 0.70613 0.604702 2 0.762752 0.590238 2 0.78936 0.576324 2 0.655357 0.617142 2 0000 00000 0  0000 00000 0   0000 00000 0

 

Per your earlier discussion, the Coco labels have this format:  - (class id, box, box, box, box, 17x3 keypoints)

 

QUESTION: Since we are not using COCO, where is the expected format defined?  Should all of our labels be expanded to meet the coco requirement?

 

From analyzing our labels, we seem to have 13 columns:

Classes: cls = 5

Keypoints = 4 

Box: = 4 

Total = 13

 

Any advice or correction would be appreciated.

Best,

Paul

**Comment by glenn-jocher** [comment]
@palmcorp hey Paul,

It sounds like the format issue is still a bit tricky. The expected format for labels in YOLOv8 should indeed match the structure you've outlined (class, bounding box, keypoints), and each label line should strictly adhere to this without additional null values unless specified in your model's configuration.

If you're not using COCO keypoints and have a different number of keypoints, you need to adjust the `kpt_shape` in your YAML configuration to match your actual data format. For example, if you have 4 keypoints, your `kpt_shape` should reflect that, and each keypoint should have its visibility flag.

Here's a quick check you can do:
- Ensure each line in your label files matches the exact number of expected values.
- Double-check that there are no extra spaces or formatting issues.

If you continue to see errors, it might help to post a few lines of your label files and the corresponding part of your YAML configuration for a more detailed look.

**Comment by palmcorp** [comment]
Thanks all.  The hints were helpful in solving this issue.

**Comment by glenn-jocher** [comment]
@palmcorp hi Paul,

I'm glad to hear that the hints were helpful in resolving your initial issue! 🎉

Regarding the label format error you're encountering, it seems there might still be a mismatch between the expected and provided label formats. Each label line should strictly follow the format required by YOLOv8, which includes the class, bounding box, and keypoints with their visibility flags.

Given your label structure:
- **Class ID**: 1 column
- **Bounding Box**: 4 columns (x_center, y_center, width, height)
- **Keypoints**: Each keypoint should have 3 columns (x, y, visibility)

For example, if you have 4 keypoints, each label line should have:
1 (class) + 4 (bbox) + 4 * 3 (keypoints) = 17 columns.

Here's a sample label line for 4 keypoints:
```
0 0.530067 0.595424 0.291592 0.107217 0.38427 0.649032 2 0.530625 0.582648 2 0.601607 0.558288 2 0.675863 0.541815 2
```

Ensure that each keypoint has its visibility flag, and the total number of columns matches the expected format. If your keypoints are fewer or more, adjust the `kpt_shape` in your YAML configuration accordingly.

If the issue persists, please provide a few lines of your label files and the corresponding part of your YAML configuration for a more detailed look. This will help us pinpoint the exact cause and provide a more accurate solution.

For further guidance on creating reproducible examples, you can refer to our [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example) guide.
