### ISSUE TITLE
Error in W&B Callback

### ISSUE THREAD

**Issue by Pikus16** [ultralytics/ultralytics#12750]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Integrations

### Bug

I am training a YOLOv8 segmentation model, and logging metrics to W&B. I find that sometimes, randomly, I get the below error. This error doesn't always occur, and when it does, it doesn't always occur at the same point. Any ideas? One possible solution I see is to make a copy of `plots.items()`, but this seems somewhat hacky.

**Error**
```
8151 Error executing job with overrides: []
8152 Traceback (most recent call last):
8153   File "/home/qasim/code/e2e_pipeline_eval/gen_image.py", line 335, in main
8154     eval_graphs, model_weights_path = run_real_and_syn(
8155   File "/home/qasim/code/e2e_pipeline_eval/src/utils/ultralytics/train_ultralytics.py", line 105, in run_real_and_syn
8156     metrics_just_real, model_weights = do_model_run(tmpdirname, **kwargs)
8157   File "/home/qasim/code/e2e_pipeline_eval/src/utils/ultralytics/train_ultralytics.py", line 184, in do_model_run
8158     model.train(data=yolo_cfg_path, epochs=num_epochs, imgsz=image_size) # model logs saved under runs/segment/
8159   File "/home/qasim/miniconda3/envs/webserver/lib/python3.10/site-packages/ultralytics/engine/model.py", line 673, in train
8160     self.trainer.train()
8161   File "/home/qasim/miniconda3/envs/webserver/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 199, in train
8162     self._do_train(world_size)
8163   File "/home/qasim/miniconda3/envs/webserver/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 440, in _do_train
8164     self.run_callbacks("on_fit_epoch_end")
8165   File "/home/qasim/miniconda3/envs/webserver/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 162, in run_callbacks
8166     callback(self)
8167   File "/home/qasim/miniconda3/envs/webserver/lib/python3.10/site-packages/ultralytics/utils/callbacks/wb.py", line 118, in on_fit_epoch_end
8168     _log_plots(trainer.plots, step=trainer.epoch + 1)
8169   File "/home/qasim/miniconda3/envs/webserver/lib/python3.10/site-packages/ultralytics/utils/callbacks/wb.py", line 103, in _log_plots
8170     for name, params in plots.items():
8171 RuntimeError: dictionary changed size during iteration
```

### Environment

```
Ultralytics YOLOv8.2.5 🚀 Python-3.10.13 torch-2.1.2+cu121 CUDA:0 (NVIDIA H100 PCIe, 81090MiB)
Setup complete ✅ (32 CPUs, 188.4 GB RAM, 1286.9/3519.3 GB disk)

OS                  Linux-5.15.0-91-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.13
Install             pip
RAM                 188.40 GB
CPU                 AMD EPYC 9124 16-Core Processor
CUDA                12.1

matplotlib          ✅ 3.8.2>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 2.1.2>=1.8.0
torchvision         ✅ 0.16.2>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.7
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.1.4>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
```

### Minimal Reproducible Example

```
from ultralytics import YOLO
model = YOLO('yolov8n-seg.pt', task='segment')
model.train(data='path/to/manifest.yaml')
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
It seems like the error might be occurring due to concurrent modification of the `plots` dictionary while it's being iterated over in the W&B callback. This can happen if the training process or another part of the code modifies the `plots` dictionary during logging to W&B.

A potential workaround could be to capture a shallow copy of `plots.items()` before the loop starts in your callback function. Here's a quick modification you can try:

```python
def _log_plots(plots, step):
    items = list(plots.items())  # take a snapshot of items
    for name, params in items:
        # your logging code here
```

This change ensures that you're iterating over a static list of items, and any modifications to the original `plots` dictionary during iteration won't affect the loop. Although it feels a bit hacky, it is a common practice to avoid such runtime errors and should resolve the issue. Give this a try and see if it stabilizes your training logging!

**Comment by Pikus16** [comment]
Makes sense, thank you for your response! I submitted a PR with your change in it here: https://github.com/ultralytics/ultralytics/pull/12779

**Comment by glenn-jocher** [comment]
@Pikus16 PR merged, thank you for your contributions!

**Comment by Pikus16** [comment]
Thank you for all your help!

**Comment by glenn-jocher** [comment]
@Pikus16 you're welcome! If you have any more questions or need further assistance down the road, feel free to reach out. Happy coding! 😊
