### ISSUE TITLE
Tensorrt c++ inference

### ISSUE THREAD

**Issue by parthapn98** [ultralytics/ultralytics#12756]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm setting up a c++ inference Pipeline with exported yolo8 models and would like to test tensorrt as well. 

Can any of the existing cpp examples be reused for a tensorrt implementation with regard to the following
- Image preprocess+results unpacking

If not, can you make any recommendations on how to approach?

**Comment by glenn-jocher** [comment]
Hi there! Great to hear you're exploring YOLOv8 with TensorRT! 🚀

Currently, we don't have a specific C++ example for TensorRT implementation directly in the YOLOv8 repository. However, the preprocessing and results unpacking stages generally remain consistent across different inference backends. Thus, you can utilize the existing C++ examples for these parts.

For integrating TensorRT, you would typically:

1. Convert the model using `yolo export model=yolov8n.pt format=engine`.
2. Load the `.engine` file in your C++ code.
3. Follow the TensorRT documentation for setting up the inference context and executing the inference.

Please refer to the [NVIDIA TensorRT documentation](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html) for detailed guidance on integrating TensorRT in your pipeline.

If there's anything more specific you need help with, feel free to ask. Happy coding! 🖥️✨
