### ISSUE TITLE
How to run YOLOv8 .engine but only need to obtain the output of the model in Jetson Xavier NX?

### ISSUE THREAD

**Issue by pu9730962** [ultralytics/ultralytics#12759]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to write my own YOLOv8 post-processing. I have currently exported it to .engine. Could you please advise on how to execute the .engine and only obtain the network's output?

**Comment by glenn-jocher** [comment]
@pu9730962 hello! To run your YOLOv8 `.engine` model on a Jetson Xavier NX and obtain only the network's output, you can use the following Python code snippet. This example assumes you've already loaded your model and are ready to perform inference:

```python
import cv2
from ultralytics import YOLO

# Load your TensorRT engine
model = YOLO("path/to/your/model.engine")

# Load an image
img = cv2.imread("path/to/your/image.jpg")

# Perform inference (assuming batch size of 1 for simplicity)
results = model.predict([img], verbose=False)

# Access the raw output
output = results.xyxy[0]  # raw output tensor
print("Raw model output:", output)
```

This code will load your `.engine` model, run an inference on a specified image, and print the raw output tensor directly. Adjust the path to your model and image as necessary. If you have any more questions or need further assistance, feel free to ask! 🚀
