### ISSUE TITLE
About loading model weights

### ISSUE THREAD

**Issue by tongchangD** [ultralytics/ultralytics#12761]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

 torch.load("./240103.pt",map_location=torch.device('cpu'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "*./ultralytics_last/lib/python3.8/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "*./ultralytics_last/lib/python3.8/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "*./ultralytics_last/lib/python3.8/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'ultralytics.yolo'

### Environment

ultralytics==8.1.44

### Minimal Reproducible Example

import ultralytics # ultralytics ==8.1.44
import torch
torch.load("./*.pth") # *.pth is saved in ultralytics==8.0.106

### Additional

The weight was saved in the ultralytics version 8.1.106, and the above error occurs when attempting to load this weight in version 8.1.44. How can this issue be resolved?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi there! It seems like the issue might be related to incompatible versions between the one used to save the model (ultralytics==8.1.106) and the one you're trying to load it with (ultralytics==8.1.44). You might be able to resolve this error by ensuring both the saving and loading are performed with the same version of the library. If you cannot run the same older version, consider upgrading your current environment to match the version used for saving the model. Here’s how you can upgrade the library:

```bash
pip install ultralytics==8.1.106
```

Just make sure that the version number matches exactly to the one used for saving the model weights. Let me know if this helps or if you encounter any other issues! 🚀

**Comment by tongchangD** [comment]
I am aware that the upgrade to 8.1.106 is capable of reading this weight, but I would like to read this weight under 8.1.44 for retraining.

**Comment by tongchangD** [comment]
@glenn-jocher  I came up with a solution,
Only the pure model parameters are saved in version 8.1.106, and then the pure model parameters are obtained under 8.1.44.

**Comment by glenn-jocher** [comment]
@tongchangD hi there! That sounds like a great approach! By saving only the model parameters in version 8.1.106 and then loading them in version 8.1.44, you should be able to bypass the module compatibility issues. Here's a quick example of how you can do this:

### Saving model parameters in 8.1.106
```python
# Assuming 'model' is your trained model
torch.save(model.state_dict(), 'model_weights.pth')
```

### Loading model parameters in 8.1.44
```python
# Make sure to initialize the model architecture similarly as it was in 8.1.106
model.load_state_dict(torch.load('model_weights.pth', map_location=torch.device('cpu')))
model.eval()
```

This method ensures that you're only dealing with the raw weights and biases, independent of any specific module structure that might have changed between versions. Let me know if this works for you! 😊
