### ISSUE TITLE
Implement Resnet Backbone into YOLOv3 and YOLOv5

### ISSUE THREAD

**Issue by LNG89811** [ultralytics/ultralytics#12769]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi everybody,

I am new in the computer vision and YOLO. I am trying to implement Resnet models as a backbone of YOLOv3 and v5 for object detection. I have cloned the [repo](https://github.com/ultralytics/ultralytics) and get into cfg folder and modified the model.

This is the directory of my yolov3.yaml and this is my modification for yolov3.
`/content/ultralytics/ultralytics/cfg/models/v3/yolov3.yaml`

However, I got the problem with indexError: list index out of range below:
`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-6-ae5e60a1e8f7>](https://localhost:8080/#) in <cell line: 2>()
      1 from ultralytics import YOLO
----> 2 model = YOLO('/content/ultralytics/ultralytics/cfg/models/v3/yolov3.yaml')

5 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/model.py](https://localhost:8080/#) in __init__(self, model, task, verbose)
     21         else:
     22             # Continue with default YOLO initialization
---> 23             super().__init__(model=model, task=task, verbose=verbose)
     24 
     25     @property

[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py](https://localhost:8080/#) in __init__(self, model, task, verbose)
    148         # Load or create new YOLO model
    149         if Path(model).suffix in {".yaml", ".yml"}:
--> 150             self._new(model, task=task, verbose=verbose)
    151         else:
    152             self._load(model, task=task)

[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py](https://localhost:8080/#) in _new(self, cfg, task, model, verbose)
    217         self.cfg = cfg
    218         self.task = task or guess_model_task(cfg_dict)
--> 219         self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
    220         self.overrides["model"] = self.cfg
    221         self.overrides["task"] = self.task

[/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py](https://localhost:8080/#) in __init__(self, cfg, ch, nc, verbose)
    285             LOGGER.info(f"Overriding model.yaml nc={self.yaml['nc']} with nc={nc}")
    286             self.yaml["nc"] = nc  # override YAML value
--> 287         self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
    288         self.names = {i: f"{i}" for i in range(self.yaml["nc"])}  # default names dict
    289         self.inplace = self.yaml.get("inplace", True)

[/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py](https://localhost:8080/#) in parse_model(d, ch, verbose)
    915             c2 = sum(ch[x] for x in f)
    916         elif m in {Detect, WorldDetect, Segment, Pose, OBB, ImagePoolingAttn}:
--> 917             args.append([ch[x] for x in f])
    918             if m is Segment:
    919                 args[2] = make_divisible(min(args[2], max_channels) * width, 8)

[/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py](https://localhost:8080/#) in <listcomp>(.0)
    915             c2 = sum(ch[x] for x in f)
    916         elif m in {Detect, WorldDetect, Segment, Pose, OBB, ImagePoolingAttn}:
--> 917             args.append([ch[x] for x in f])
    918             if m is Segment:
    919                 args[2] = make_divisible(min(args[2], max_channels) * width, 8)

IndexError: list index out of range`

Do we have any solution for this to modify the backbone for YOLO.

Thank you so much,
![Screenshot 2024-05-17 184221](https://github.com/ultralytics/ultralytics/assets/168504087/f212264e-d22e-4751-950c-1b8e583c82ab)
S
![Screenshot 2024-05-17 184304](https://github.com/ultralytics/ultralytics/assets/168504087/a56f05e4-f1b6-46b8-88f7-c08b509159ee)

**Comment by LNG89811** [comment]
Fixed

**Comment by glenn-jocher** [comment]
Great to hear that you resolved the issue! If you have any more questions or need further assistance in the future, feel free to ask. Happy coding! 😊

**Comment by UltralyticsAssistant** [comment]
A potential fix for this issue has now been merged into the `main` branch via [PR #18564](https://github.com/ultralytics/ultralytics/pull/18564). Huge thanks to the author of the PR and contributor for the improvements!

### Key Changes Relevant to This Issue:
- **New `TorchVision` Module**: Provides the ability to integrate and customize pretrained models from the `torchvision` library, which may directly enhance usability or solve any related model customization challenges.
- **New `Index` Module**: Adds support for efficiently handling structured data by enabling extraction of specific elements (e.g., tensors) from a list during a model's forward pass.
- **New YOLO11 ResNet18 Classification Configuration**: A lightweight and scalable classification model has been introduced, which may improve performance or address any classification-specific requirements.
- **Version bump and Documentation Updates**: Ensures the latest version (8.3.59) includes all fixes and comes with detailed documentation to guide any new implementations.

### Testing the Fix:
To test if these changes resolve the issue:
1. Install the latest changes from the `main` branch:
   ```bash
   pip install git+https://github.com/ultralytics/ultralytics.git@main
   ```
2. Alternatively, wait for the next official PyPI release to use the updated version.

### Feedback Request:
Please let us know if the changes in this PR resolve the issue. If the problem persists, feel free to provide additional details so further improvements can be made.

Thanks again for raising this issue and helping make the project better! 🙏 Your feedback is always welcome and greatly appreciated.

**Comment by JAtharva22** [comment]
> Fixed

Hello I am trying something similar 
will you be willing to share your resnet implementation of yolo please
Thanks

**Comment by glenn-jocher** [comment]
Hi there! 👋 For ResNet implementations with YOLO, we recommend exploring our new [TorchVision module integration](https://docs.ultralytics.com/reference/nn/tasks/#torchvision) which supports direct use of torchvision models as backbones. This approach maintains compatibility with YOLO architectures while leveraging pretrained vision models. 

For custom implementations, please note that any modifications to Ultralytics code/models require either:
1. Open-sourcing your entire project under AGPL-3.0, or  
2. Obtaining an [Ultralytics Enterprise License](https://ultralytics.com/license)

You can find starter templates in our [model configuration files](https://github.com/ultralytics/ultralytics/tree/main/ultralytics/cfg/models). Let us know if you encounter specific technical issues!

**Comment by glenn-jocher** [comment]
Hi there! 👋 We're glad you resolved your issue! For custom implementations like ResNet backbones in YOLO models, we encourage community members to share their contributions through our [Contributing Guide](https://docs.ultralytics.com/help/contributing). This helps others benefit from your work while maintaining compatibility with the main repository. Feel free to submit a Pull Request if you'd like to share your implementation! 🚀

**Comment by tempsecacc** [comment]
@LNG89811  it is possible to share your approach how do u change the backbone for yolo3 i wanna customize my backbone but don't know where to start 

> Fixed
