### ISSUE TITLE
Can not extract predicted classes from the results as a variable.

### ISSUE THREAD

**Issue by coozywana** [ultralytics/ultralytics#12778]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can not extract predicted classes from the results as a variable.

**Comment by glenn-jocher** [comment]
@coozywana hello! To extract predicted classes from the results, you can access the `classes` attribute from the `boxes` object in your results. Here's a quick example using Python:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('yolov8n.pt')

# Run predictions
results = model('path/to/your/image.jpg')

# Extract predicted classes
predicted_classes = results[0].boxes.cls

print(predicted_classes)
```

This will give you a tensor of class IDs for each detection. Let me know if you need further assistance! 😊

**Comment by glenn-jocher** [comment]
Hi @coozywana,

You're welcome! 😊 If you need further assistance or have any more questions, feel free to ask. We're here to help!
