### ISSUE TITLE
Angle representation method of YOLOV8-obb

### ISSUE THREAD

**Issue by yywjacson** [ultralytics/ultralytics#12771]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I have a question while reading the source code. How is the angle of yolov8-obb ​​expressed? Is it based on the angle between the long side and the x-axis or the angle between the short side and the y-axis?
I wish you a happy work and life

**Comment by glenn-jocher** [comment]
Hello! Thank you for your inquiry and the kind wishes! 😊

In YOLOv8-obb, the angle is expressed as the rotation of the bounding box relative to the x-axis. This angle is associated with the long side of the bounding box, indicating how much the long side deviates from being parallel to the x-axis.

If you have any more questions or need further clarification, feel free to ask. Happy coding! 🚀
