### ISSUE TITLE
yolov8n's coco pre-training?

### ISSUE THREAD

**Issue by HuKai97** [ultralytics/ultralytics#12777]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can you send me a copy of the training parameter configuration of yolov8n's coco pre-training?

**Comment by glenn-jocher** [comment]
Hello! 👋

For the YOLOv8n model pre-trained on the COCO dataset, you can find the training parameter configuration in the `coco.yaml` file. Here's a quick example of how you might load and train the model using this configuration:

```python
from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO('yolov8n.pt')

# Train the model with COCO dataset configuration
results = model.train(data='coco.yaml', epochs=100, imgsz=640)
```

This will train the model for 100 epochs with an image size of 640. You can adjust the `epochs` and `imgsz` as needed for your specific requirements.

If you need the exact configuration file, it's typically located in the `data` directory of the repository or can be specified directly in your training script as shown above.

Hope this helps! Let me know if you have any more questions. 😊
