### ISSUE TITLE
cv::dnn::readNetFromONNX

### ISSUE THREAD

**Issue by soloplayl** [ultralytics/ultralytics#1277]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

example

### Bug

[ERROR:0@0.089] global /home/soloplayl/下载/opencv-4.6.0/modules/dnn/src/onnx/onnx_importer.cpp (1018) handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [Add]:(onnx_node!/model.22/Add) from domain='ai.onnx'
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.6.0) /home/soloplayl/下载/opencv-4.6.0/modules/dnn/src/onnx/onnx_importer.cpp:1040: error: (-2:Unspecified error) in function 'handleNode'
> Node [Add@ai.onnx]:(onnx_node!/model.22/Add) parse error: OpenCV(4.6.0) /home/soloplayl/下载/opencv-4.6.0/modules/dnn/src/onnx/onnx_importer.cpp:1464: error: (-215:Assertion failed) blob_0.size == blob_1.size in function 'parseBias'
> 

### Environment

YOLOv8
OS: ubuntu 22.04
opencv4.5.4

### Minimal Reproducible Example

yolo task=detect mode=export model=best.pt format=onnx dynamic=False 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
See the usage in the official ONNX-opencv example. I've verified and this is working for me -> https://github.com/ultralytics/ultralytics/tree/4b866c97180842b546fe117610869d3c8d69d8ae/examples/YOLOv8-OpenCV-ONNX-Python

**Comment by soloplayl** [comment]
hi @AyushExel but i ran it in c++,i guess my error is due to the version probelm of OpenCV

**Comment by AyushExel** [comment]
Ohh I see. Yeah we have a c++ example in the examples/ folder too. Please check it out

**Comment by soloplayl** [comment]
@AyushExel i know,i'm using that c++ example,but it yep reported error. So,i'm rebuilding my OpenCV.

**Comment by AyushExel** [comment]
Yeah then it's your version. Good luck!

**Comment by JustasBart** [comment]
@soloplayl Can refer to this:

![OpenCV build](https://user-images.githubusercontent.com/40023722/223087467-adc03820-aa62-46db-8db7-13d5cd90de6d.png)

Good luck! :rocket:

**Comment by JustasBart** [comment]
Hi @mabasith can you provide more information on how you've exported your ONNX model? Did you set the opset to 12?

**Comment by glenn-jocher** [comment]
Hi @mabasith, the error message you're experiencing typically shows up when the input data for the network is not matching the required shape of the network. Please make sure that your input and network structures for the exported ONNX model match. Furthermore, please note that YOLOv8 requires the ONNX opset version to be at least 12. Let us know if that resolves the issue.

**Comment by zeno0119** [comment]
I have same issue with OpenCV (4.2.0) and find a solution for this (maybe)
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.2.0) /home/zeno0119/opencv/opencv/modules/dnn/src/onnx/onnx_importer.cpp:110: error: (-215:Assertion failed) !tensor_proto.raw_data().empty() || !tensor_proto.float_data().empty() || !tensor_proto.double_data().empty() || !tensor_proto.int64_data().empty() in function 'getMatFromTensor'.

I exported onnx with yolo command `yolo export model=yolov8n-seg.pt format=onnx imgsz=320,320 opset=12`

Solution: Update OpenCV from 4.2.0 to 4.7.0
After updating OpenCV, there is no problem for inference with yolov8n-seg.onnx on C++. 
FYI

**Comment by glenn-jocher** [comment]
@zeno0119 hi there, thank you for sharing your solution! Updating OpenCV indeed often resolves such issues. The YOLOv8 model uses some newer features and fixes in the OpenCV library so it's always recommended to use the most recent stable version of OpenCV. I'm glad you were able to resolve the issue and hope your experience helps others facing similar problems. Your contribution is valued!

Let us know if you have any other questions or issues. We're here to help. Enjoy using YOLOv8!
