### ISSUE TITLE
Cannot interpret tf_saved_model prediction output.

### ISSUE THREAD

**Issue by TimbusCalin** [ultralytics/ultralytics#1278]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

**NOTE* I can see in the output of the network that it's of the format (1,5,8400) and the same for TorchScript. How can I extract the bounding boxes from the output (1,5,8400)?**

I converted the model to TensorFlow because of this issue: https://github.com/ultralytics/ultralytics/issues/1270

Since I now predict with TensorFlow, I want to correlate the results and make sure that all runs smooth.

However, I cannot understand the result, basically I load the model, I read the image and then the output prediction is of shape `(1,5,8400)`.

Am I making a mistake in my "one-image" prediction code?

Thank you in advance.

```
# Load the saved model
# Model was trained on 640x640
model = tf.saved_model.load('./best_saved_model/')
image = cv2.imread("test_image.jpeg")
image_float32 = tf.cast(image,dtype=tf.float32)
image_float32_resized = tf.image.resize(image_float32, (640,640))
result = model(tf.expand_dims(image_float32_resized,axis=0))
print(result.shape) (prints (1,5,8400)
```

### Additional
NOTE* I can see in the output of the network that it's of the format (1,5,8400) and the same for TorchScript. How can I extract the bounding boxes from the output (1,5,8400)?

**Comment by AyushExel** [comment]
The output dimension is same as ONNX. It is (1,5,8400) because NMS module isn't exported. See this ONNX -python example where the bounding boxes are interpreted from the outputs after passing them through NMS https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-OpenCV-ONNX-Python

**Comment by TimbusCalin** [comment]
@AyushExel thank you. I managed to go through the code and understand the process, also check the output with Netron and know now the subsequent steps. Thank you!
