### ISSUE TITLE
Padding images with value=(114, 114, 114) in LetterBox

### ISSUE THREAD

**Issue by mehran66** [ultralytics/ultralytics#1279]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Padding for images is added by these values (114, 114, 114). Given that (0, 0, 0) is widely used for image background, I was wondering if there is any reason for using (114, 114, 114):

        img = cv2.copyMakeBorder(img, top, bottom, left, right, cv2.BORDER_CONSTANT,
                                 value=(114, 114, 114))

https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/data/augment.py#:~:text=))-,img,)),-%23%20add%20border

**Comment by glenn-jocher** [comment]
@mehran66 114 is imagenet mean averaged over RGB

**Comment by mehran66** [comment]
Thanks @glenn-jocher 
another related question....Does Yolo run any image normalization? I did notice that the only preprocessing for detection and segmentation is dividing by 255.
