### ISSUE TITLE
Train the selected model structure for your dataset

### ISSUE THREAD

**Issue by smallMantou** [ultralytics/ultralytics#12792]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I have some questions about training my own dataset. I want to start training my dataset from scratch. How do I know if my model is based on n, s, m, or l? How can I make changes to train S? Does the following image indicate that I am based on n
<img width="1104" alt="n" src="https://github.com/ultralytics/ultralytics/assets/156918297/42c8d82f-432a-48ce-bb05-b0ff26cb4a96">

**Comment by deepukr007** [comment]
I think AMP check always happens on yolov8n, I see the same thing everytime.. You can ignore it.
If your YAML file has name such as yolov8s_{....} .yaml your model will be based on yolov8s..
You can also cross check this by looking at the total model parameters .

**Comment by smallMantou** [comment]
How can I change it to be based on YOLOv8S?

**Comment by glenn-jocher** [comment]
Hello! To switch your model base to YOLOv8s, you'll need to use a YOLOv8s model configuration file. You can specify this in your training command by replacing the model argument with the path to a YOLOv8s YAML file. For example:

```bash
yolo detect train data=your_dataset.yaml model=yolov8s.yaml epochs=100 imgsz=640
```

Make sure you have the `yolov8s.yaml` file in your directory, or you can download it from the Ultralytics repository if it's not already included. This will set up your training to use the YOLOv8s architecture. Happy training! 🚀
