### ISSUE TITLE
Image prediction

### ISSUE THREAD

**Issue by smallMantou** [ultralytics/ultralytics#12791]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I would like to ask how to use the weight file trained from my own dataset to predict multiple images in a folder.

**Comment by Kayzwer** [comment]
@smallMantou model.predict("path/to/imga")

**Comment by smallMantou** [comment]
Do I need to list each image for detecting multiple images?

**Comment by Kayzwer** [comment]
> Do I need to list each image for detecting multiple images?

no just give the path to the img directory

**Comment by smallMantou** [comment]
Thank you for your answer.How do I know which model I am using when training my dataset, because I want to start training from scratch, but the yolo. yaml file contains n \ s \ m \ l.Grayscale_yolov5s.yaml is yolov8.yaml that I copied.
<img width="829" alt="train" src="https://github.com/ultralytics/ultralytics/assets/156918297/ec6db80f-7bc1-4f2c-aaa6-8e934cc74594">

**Comment by glenn-jocher** [comment]
Hello! To determine which model configuration you are using when training from scratch, you should look at the YAML file you are specifying in your training command. Each model variant (n, s, m, l) has its own YAML file that defines the model's architecture and settings. If you've copied and renamed a YAML file, make sure to check its contents to see which model it's configured for.

For example, if you're using `Grayscale_yolov5s.yaml` and you've renamed it from a YOLOv8 model configuration, you should open that YAML file and review the parameters to confirm which model size it corresponds to (n, s, m, l). The model size is typically indicated by the depth and width parameters in the YAML file.

Here's a quick way to start training from scratch using a specific model configuration:

```bash
yolo train data=your_dataset.yaml model=your_model.yaml
```

Replace `your_dataset.yaml` with your dataset configuration file and `your_model.yaml` with the model configuration file you intend to use. This will ensure you are training with the correct model setup. Happy training! 🚀
