### ISSUE TITLE
How to train on multiple machine using CLI commnd?

### ISSUE THREAD

**Issue by majnas** [ultralytics/ultralytics#1282]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have three machine each with single GPU, how to train a model using CLI commnd?
All machines are in a same network.

```bash
WORLD_SIZE=3
MASTER_ADDR=192.168.44.173
MASTER_PORT=9020
NGPU_PER_NODE=1
BATCH_PER_GPU=12
```
what should I add to this command? :confused: 
```bash
yolo detect train model=yolov8x.pt data=POT.yaml batch=12 project="runs/Y8" name="POT" 
```

**Comment by AyushExel** [comment]
We only support torch DDP training for multi-GPU training. I don't think it's possible to train across nodes (devices) on a network using torch DDP. You might want to use something like Anyscale's Ray for your use case. You can easily create your custom trainer - https://docs.ultralytics.com/engine/

**Comment by glenn-jocher** [comment]
@majnas YOLOv5 is multi-node capable, we had users training there successfully, but we don't validate multi-node ourselves, so I'm not how you'd configure YOLOv8 for this. If you have expertise here you could help us debug multi-node for other users, PRs are welcome!

The distributed training functions called by the trainer are here:
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/utils/dist.py
