### ISSUE TITLE
training log in COCO

### ISSUE THREAD

**Issue by violet2422** [ultralytics/ultralytics#1285]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I admire YOLOv8's brilliant work on object detection tasks! May I ask if you can provide the training log on the COCO dataset, I can refer to the changes of dfl/cls/box loss to adjust the parameters! Thanks!!!

**Comment by glenn-jocher** [comment]
@violet2422 yes these will be available soon on HUB at https://hub.ultralytics.com/. We are working to add YOLOv8 support and then once we do you'll have a public projects page showing training logs :)
