### ISSUE TITLE
Image size during training

### ISSUE THREAD

**Issue by martin0496** [ultralytics/ultralytics#1287]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I run the training script using imgsz=[1024,320] , the training only detects 1024 as the size of the image. How can I train the model with selecting the original size of the image (1024,320) ? or it is mandatory to have square images during training automatically ?

**Comment by glenn-jocher** [comment]
@martin0496 you can use `imgsz=1024 rect=True` when training to automatically resolve the short side and train on rectangular images, but this will disable mosaic augmentation and is not recommended.
