### ISSUE TITLE
## Area of Instance Segmented Object Using Yolov8 instance model

### ISSUE THREAD

**Issue by divyvijay** [ultralytics/ultralytics#12907]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I need to find out the area of the instance segmented **object** using the Yolov8 instance model. Is there any way to figure out using yolo models? I perfectly trained my model to predict the object, but I am having difficulties calculating the area of the predicted object. Also how to get the mask from the results.All I get the cropped imaged along with labels.

![predicted](https://github.com/ultralytics/ultralytics/assets/154326633/0429e4e6-b381-4eb6-b6ee-6d80f8ca6a44)
![1](https://github.com/ultralytics/ultralytics/assets/154326633/c58f9ca2-c549-4285-921d-e9f8667e2bdb)

**Comment by glenn-jocher** [comment]
@divyvijay hi there! 👋

To calculate the area of an instance-segmented object using a YOLOv8 instance model, you can utilize the segmentation masks that the model provides. Here's a quick guide on how to extract the mask and compute the area:

1. **Extract the Mask**: After running inference, the `Results` object will contain a `masks` attribute if your model supports segmentation. You can access it like this:

   ```python
   results = model(source)  # source can be an image or video frame
   masks = results.masks  # This will give you the segmentation masks
   ```

2. **Calculate the Area**: You can calculate the area of the segmented object by summing up the pixels in the mask:

   ```python
   # Assuming `masks` is not empty and you're interested in the first detected object
   object_mask = masks[0].numpy()  # Convert to numpy array if not already
   area = object_mask.sum()  # Each '1' in the mask represents a pixel in the original image
   print(f"Area of the segmented object: {area} pixels")
   ```

This should give you the area of your segmented object in terms of pixel count. If you need the area in physical units (like square cm), you'll need to know the scaling factors from pixels to real-world units based on your specific setup.

Hope this helps! Let us know if you have any more questions. 😊
