### ISSUE TITLE
using triangular distribution instead of uniform distribution for scale and degrees

### ISSUE THREAD

**Issue by mehran66** [ultralytics/ultralytics#1290]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I was wondering if it makes more sense to use triangular distribution instead of uniform distribution for scale and degrees given that we are more interested in the target image size and original image orientations.

        a = random.triangular(-self.degrees, self.degrees, 0)
        s = random.triangular(1 - self.scale, 1 + self.scale, 1)

https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/data/augment.py#:~:text=Rotation%20and%20Scale-,R,),-%23%20s%20%3D%202%20**%20random

**Comment by glenn-jocher** [comment]
@mehran66 you're free to update the distribution here, though I doubt reducing scale jitter will improve COCO training. 

On the rotation side we've not been able to show improvement with larger rotations, so we've left it at zero degrees.
