### ISSUE TITLE
Does YOLO perform object detection on jp2 image format?

### ISSUE THREAD

**Issue by nathbhargav** [ultralytics/ultralytics#12928]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I want to perform object detection on jp2 image. Does YOLO perform object detection on jp2 image format?
Please help me
Thank you in advance

**Comment by glenn-jocher** [comment]
Hello! YOLOv8 does not natively support the jp2 (JPEG 2000) image format for object detection. You'll need to convert your jp2 images to a supported format like JPG, PNG, or BMP before running detection. Here's a quick example using Python with the Pillow library to convert a jp2 image to JPG:

```python
from PIL import Image

# Load jp2 image
image = Image.open('image.jp2')

# Save as JPG
image.save('image.jpg', 'JPEG')
```

After converting your images, you can then use YOLOv8 to perform object detection on them. If you have any more questions or need further assistance, feel free to ask! 🚀
