### ISSUE TITLE
How to train on a custom PyTorch Dataloader?

### ISSUE THREAD

**Issue by alevangel** [ultralytics/ultralytics#1292]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to train on a custom pytorch dataloader?
In particular, my dataloader generates synthetic images on the fly, so there is no folder where they are saved (so I don't think using the configuration yaml is appropriate)

**Comment by glenn-jocher** [comment]
@alevangel I think all dataloaders generate augmented images during runtime. The YOLOv8 dataloaders are in:
https://github.com/ultralytics/ultralytics/tree/main/ultralytics/yolo/data

**Comment by alevangel** [comment]
> @alevangel I think all dataloaders generate augmented images during runtime. The YOLOv8 dataloaders are in:
> https://github.com/ultralytics/ultralytics/tree/main/ultralytics/yolo/data

Thanks @glenn-jocher . Would like to know if there is a method to do the training on a custom dataset using a dataloader as straight forward as the config.yaml

**Comment by AyushExel** [comment]
@alevangel here's how you can use a custom dataloader https://docs.ultralytics.com/engine/

**Comment by alevangel** [comment]
@AyushExel ok thank you! If i override the get_dataloader() method, I will still have default YOLO augmentations on the images or do I need to implement them again? (like mosaic augmentations)

**Comment by Phyrokar** [comment]
I would also be very interested in the topic. In my case I would like to gradually pull data from a database, augment it with existing methods and train it.

**Comment by AyushExel** [comment]
Hey guys. The augmentation is built into the dataloader. You can build your own dataloder based on the default dataloaders also. I think that'll be a simpler approach.

**Comment by alevangel** [comment]
> Hey guys. The augmentation is built into the dataloader. You can build your own dataloder based on the default dataloaders also. I think that'll be a simpler approach.

I see thanks. Can you please point where is the code for the default dataloaders?

**Comment by pderrenger** [comment]
@alevangel the code for the default dataloaders can be found in the YOLOv8 repository at `ultralytics/yolo/data`. You can explore the code there to understand how the default dataloaders are implemented.

**Comment by glenn-jocher** [comment]
@pderrenger, you can find the default dataloaders within the `ultralytics/yolo/data` directory in the YOLOv8 repo. They serve as a good reference for implementing your custom dataloader with the desired augmentations.
