### ISSUE TITLE
not working when using multi-GPU training in jupyter notebook

### ISSUE THREAD

**Issue by da2so** [ultralytics/ultralytics#1295]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I got no response and no progress anymore like below when using multi-gpu training in jupyter notebook. 

<img width="1598" alt="image" src="https://user-images.githubusercontent.com/47438617/223287033-6cd05fba-ee4f-4580-b88b-ec8a29ad225e.png">

### Environment

Ultralytics YOLOv8.0.49 🚀 Python-3.8.12 torch-1.9.1+cu111 CUDA:0 (Tesla V100-PCIE-32GB, 32510MiB)
Setup complete ✅ (56 CPUs, 376.4 GB RAM, 3063.8/8893.3 GB disk)

### Minimal Reproducible Example

```
from ultralytics import YOLO


model = YOLO("yolov8n.yaml")
model.train(data="coco128.yaml", epochs=5)
```

**Comment by glenn-jocher** [comment]
@da2so your command isn't a DDP command, it doesn't define a device, so YOLO will use device 0 by default in Multi-GPU environments. Your screenshot shows DDP training though, which is strange.

**Comment by da2so** [comment]
@glenn-jocher  I set `device=0,1` in `default.yaml`.

**Comment by weihongwei-zg** [comment]
Me too

**Comment by ZZHOO1** [comment]
hello, how to solove this problem @da2so

**Comment by da2so** [comment]
@glenn-jocher yes, I got stuck when DDP training. And, when I force to stop the program, i got an error message below:
<img width="528" alt="image" src="https://user-images.githubusercontent.com/47438617/229411816-ae6f1ed7-6cdf-482a-8064-f27b107b22f5.png">

- yolov8 version: 8.0.61
- pytorch version: 1.9.1+cu111
- GPU num: 2

**Comment by glenn-jocher** [comment]
@philippart-s you're welcome! Yes, in some cases, Multi-GPU training may not work as expected in a Jupyter Notebook but it should work correctly when using a command-line interface or a separate Python file. However, this behavior can depend on various factors, like the specific environment and machine you are using. While it may be a bit less convenient to switch between a Jupyter Notebook and a terminal, it can be a good option to ensure that Multi-GPU training works as intended. If you have any further questions or concerns, please let us know.
