### ISSUE TITLE
run yolov8 using gpu

### ISSUE THREAD

**Issue by thanbai7189** [ultralytics/ultralytics#12967]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I'm a novice to computer vision. I've looked up many forums/guides and couldn't find any sufficient solution. Here's my code:

from ultralytics import YOLO
import cv2 as cv
import box_style
import math
import torch

cap = cv.VideoCapture("path/to/video")

torch.cuda.set_device(0)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = YOLO('yolov8s.pt', task='detect')
model.to(device=device)

while cap.isOpened():
    ret, frame = cap.read()

    frame = cv.resize(frame, (1280,720))

    results = model.predict(frame, stream=True)
   
    cv.imshow('frame', frame)
    if cv.waitKey(40) & 0xFF == ord('q'):
        break

cap.release()
cv.destroyAllWindows()

This appeared in vscode terminal:
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1716249209.436909   16692 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

I assume this means my gpu was not utilized. I used CUDA toolkit and cudnn v12.4, gpu NVIDIA rtx 2060 super, window 10, pytorch CUDA v12.1. Please help.

**Comment by glenn-jocher** [comment]
Hello! It looks like you're on the right track by setting the device to GPU with `torch.device("cuda" if torch.cuda.is_available() else "cpu")`. However, to ensure that your GPU is actually being utilized for inference, you can make a small adjustment to your code by explicitly specifying the device when you load the model:

```python
from ultralytics import YOLO
import cv2 as cv

# Set up your video capture
cap = cv.VideoCapture("path/to/video")

# Load the model and specify the device directly
model = YOLO('yolov8s.pt', task='detect', device='cuda')

while cap.isOpened():
    ret, frame = cap.read()
    frame = cv.resize(frame, (1280,720))

    # Perform prediction
    results = model.predict(frame, stream=True)
   
    # Display the frame
    cv.imshow('frame', frame)
    if cv.waitKey(40) & 0xFF == ord('q'):
        break

cap.release()
cv.destroyAllWindows()
```

This modification ensures that the model uses the GPU (if available) right from the initialization. The warnings you see in the terminal are related to TensorFlow, which might not be relevant if you're using PyTorch and Ultralytics YOLO. If you continue to see issues or the GPU is not utilized, double-check your PyTorch installation with CUDA support by running `torch.cuda.is_available()` to confirm it returns `True`. If it doesn't, you may need to reinstall PyTorch with the correct CUDA version.

**Comment by thanbai7189** [comment]
Hello Glenn. This is what I tried:
torch.cuda.set_device(0)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = YOLO('../yolo-weights/yolov8s.pt', task='detect', device='cuda')
model.to(device=device)

This is what it returned:
TypeError: YOLO.__init__() got an unexpected keyword argument 'device'

I also tried: 
import torch
print(torch.cuda.is_available())

to which it returned True, so I think my installation was fine. Is there any other way to work around this issue? Mind you I've tried to install and reinstall multiple times, I have my requirements.txt here:
absl-py==2.1.0
antlr4-python3-runtime==4.9.3
attrs==23.2.0
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
colorama==0.4.6
contourpy==1.2.1
cycler==0.12.1
filelock==3.13.1
filterpy==1.4.5
flatbuffers==24.3.25
fonttools==4.51.0
fsspec==2024.2.0
hydra-core==1.3.2
idna==3.7
imageio==2.34.1
intel-openmp==2021.4.0
jax==0.4.28
jaxlib==0.4.28
Jinja2==3.1.3
kiwisolver==1.4.5
lapx==0.5.9
lazy_loader==0.4
MarkupSafe==2.1.5
matplotlib==3.9.0
mediapipe==0.10.14
mkl==2021.4.0
ml-dtypes==0.4.0
mpmath==1.3.0
networkx==3.2.1
numpy==1.26.3
omegaconf==2.3.0
opencv-contrib-python==4.9.0.80
opencv-python==4.9.0.80
opt-einsum==3.3.0
packaging==24.0
pandas==2.2.2
pillow==10.2.0
protobuf==4.25.3
psutil==5.9.8
py-cpuinfo==9.0.0
pycparser==2.22
pyparsing==3.1.2
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
requests==2.32.0
scikit-image==0.23.2
scipy==1.13.0
seaborn==0.13.2
six==1.16.0
sounddevice==0.4.6
sympy==1.12
tbb==2021.11.0
thop==0.1.1.post2209072238
tifffile==2024.5.10
**torch==2.3.0+cu121
torchaudio==2.3.0+cu121
torchvision==0.18.0+cu121**
tqdm==4.66.4
typing_extensions==4.9.0
tzdata==2024.1
ultralytics==8.2.18
urllib3==2.2.1

**Comment by glenn-jocher** [comment]
@thanbai7189 hello! It looks like you're trying to pass the `device` parameter directly to the `YOLO` constructor, which is causing the `TypeError`. In the current setup of the Ultralytics YOLO API, the device should be set when you load the model, not passed as an argument. Here's how you can do it correctly:

```python
from ultralytics import YOLO
import torch

# Ensure CUDA device is specified
torch.cuda.set_device(0)

# Load the model and specify the device using the 'device' parameter in the load function
model = YOLO('../yolo-weights/yolov8s.pt', task='detect').to('cuda')
```

This should correctly load your model onto the GPU. Your installation seems fine since `torch.cuda.is_available()` returns `True`. Just make sure to use the `.to('cuda')` method to move your model to the GPU after loading it. Let me know if this helps! 😊

**Comment by thanbai7189** [comment]
Hello, I tried the solution above but no use. The "INFO: Created TensorFlow Lite XNNPACK delegate for CPU." still popped up.

**Comment by glenn-jocher** [comment]
Hello! It seems like the TensorFlow Lite message you're seeing is unrelated to the use of PyTorch and YOLOv8, as it pertains to TensorFlow operations. If your goal is to ensure that YOLOv8 is utilizing the GPU with PyTorch, you can verify this by checking the device allocation of your model directly:

```python
print(model.device)  # This will show you where the model is currently allocated
```

If it outputs 'cuda', your model is using the GPU. Otherwise, ensure you've moved your model to the GPU with `.to('cuda')`. If you have any TensorFlow-related code or dependencies that might be causing the message, you might want to isolate or remove them if they are not needed. Let me know if this clears things up! 😊

**Comment by thanbai7189** [comment]
Hello, got it! it output 'cuda' when I ran the code. Thank you!

**Comment by glenn-jocher** [comment]
Great to hear that it's working and your model is utilizing the GPU! If you have any more questions or need further assistance as you continue with your project, feel free to reach out. Happy coding! 😊
