### ISSUE TITLE
Incorrect device on Google Colab

### ISSUE THREAD

**Issue by aqeeljanjua** [ultralytics/ultralytics#12966]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Ultralytics YOLOv8.0.196 🚀 Python-3.10.12 torch-2.2.1+cu121 
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 445, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 336, in train
    self.trainer = (trainer or self._smart_load('trainer'))(overrides=args, _callbacks=self.callbacks)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 85, in __init__
    self.device = select_device(self.args.device, self.args.batch)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/utils/torch_utils.py", line 119, in select_device
    raise ValueError(f"Invalid CUDA 'device={device}' requested."
ValueError: Invalid CUDA 'device=3,4' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: None
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.

### Environment

Ultralytics YOLOv8.0.196 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (NVIDIA L4, 22700MiB)
Setup complete ✅ (16 CPUs, 62.8 GB RAM, 36.1/201.2 GB disk)

### Minimal Reproducible Example

-  Runtime :  Google Colab L4 GPU
``` yolo detect train model=yolov8l.pt data={HOME}/data.yaml epochs=100 imgsz=640 plots=True batch=64 cache=True project={HOME}/training device=0 workers=0 resume=True```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by aqeeljanjua** [comment]
It happens only when I am using resume=True. Now it is working fine without using resume=True

**Comment by glenn-jocher** [comment]
Hello! It sounds like the issue might be related to the state saved in the checkpoint when using `resume=True`. If the checkpoint was saved with specific device settings that aren't available in your current environment, it could cause this error. 

To avoid this, ensure that the device settings match or reset them appropriately when resuming training. If you need to change the device when resuming, you might have to manually adjust the device setting in your checkpoint file or specify the correct device in your command.

If the problem persists, please let us know!
