### ISSUE TITLE
YOLOv8 multi-GPU training with GPUs in multiple machines.

### ISSUE THREAD

**Issue by purv2100** [ultralytics/ultralytics#12969]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello all!

How can I train yolov8 model in multi-GPU setup where GPUs are in multiple machine? I found that there is a way to train yolov5 in multiple machine setup(https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training/) but was not able to find anything for yolov8.

I also found an issue(#3308) related to it but it did not delve much into multiple machine setup. It did mention that proper setup needs to be there for machines to communicate but I couldn't find any code or guide, similar to yolov5, to setup that environment. Is there anyway I can train yolov8 in multiple machine setup?

Thanks for the time!

**Comment by glenn-jocher** [comment]
Hello!

Currently, YOLOv8 does not natively support multi-machine GPU training out of the box like YOLOv5. However, you can achieve this by setting up a distributed training environment manually using PyTorch's `DistributedDataParallel` (DDP). Here's a brief outline on how you might set it up:

1. Ensure all machines are networked together and can communicate.
2. Set up a shared file system that all machines can access for data and model checkpoints.
3. Launch your training script on each machine with the appropriate `CUDA_VISIBLE_DEVICES` set for each machine's GPUs.
4. Use `torch.distributed.launch` with the `--nproc_per_node` argument set to the number of GPUs per machine.

Here's a simple example to start the training on each machine:
```bash
python -m torch.distributed.launch --nproc_per_node=NUM_GPUS_PER_NODE --nnodes=NUM_NODES --node_rank=NODE_RANK --master_addr="MASTER_NODE_IP" --master_port=12345 train.py --data coco.yaml --cfg yolov8.yaml
```

Replace `NUM_GPUS_PER_NODE`, `NUM_NODES`, `NODE_RANK`, `MASTER_NODE_IP` with your specific setup details.

For more detailed guidance, you might need to adapt the setup from the PyTorch DDP documentation to fit YOLOv8's training script.

Hope this helps! Let us know if you have further questions. 😊
