### ISSUE TITLE
 Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build).

### ISSUE THREAD

**Issue by Cherub1Zhuang** [ultralytics/ultralytics#1297]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

 Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build).

**Comment by AyushExel** [comment]
This seems like an issue with your pytorch/CUDA installation as it's not reproducible on colab.
