### ISSUE TITLE
ERROR: label-studio 1.7.1 has requirement pytz~=2019.3, but you'll have pytz 2022.7.1 why update  version not support?

### ISSUE THREAD

**Issue by mraselamin** [ultralytics/ultralytics#1298]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

ERROR: label-studio 1.7.1 has requirement pytz~=2019.3, but you'll have pytz 2022.7.1 which is incompatible.
ERROR: label-studio 1.7.1 has requirement requests<2.28,>=2.22.0, but you'll have requests 2.28.2 which is incompatible.

**Comment by AyushExel** [comment]
Label studio is a different tool. Please open an issue on their repo and they might be able to assist you with this.
