### ISSUE TITLE
How to chose what metrics use as goal for model.tune?

### ISSUE THREAD

**Issue by medphisiker** [ultralytics/ultralytics#12983]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I read new tutorial about model hyperparameters tuning ([link](https://docs.ultralytics.com/guides/hyperparameter-tuning/)).
When using `optuna`, we can set a function that will measure some metric that we minimize or maximize.

Documentation also tell us "Determine the metrics you will use to evaluate the model's performance. This could be AP50, F1-score, or others."

How can we set metric which we want to evaluate? )
There is a `fitness` metric as I understand in `https://github.com/ultralytics/ultralytics/blob/c8b6a8bc37ce196a6b7e0c153539402db4383c16/ultralytics/engine/tuner.py#L33`.

```
        if self.tune_csv.exists():  # if CSV file exists: select best hyps and mutate
            # Select parent(s)
            x = np.loadtxt(self.tune_csv, ndmin=2, delimiter=",", skiprows=1)
            fitness = x[:, 0]  # first column
            n = min(n, len(x))  # number of previous results to consider
            x = x[np.argsort(-fitness)][:n]  # top n mutations
            w = x[:, 0] - x[:, 0].min() + 1e-6  # weights (sum > 0)
            if parent == "single" or len(x) == 1:
                # x = x[random.randint(0, n - 1)]  # random selection
                x = x[random.choices(range(n), weights=w)[0]]  # weighted selection
            elif parent == "weighted":
                x = (x * w.reshape(n, 1)).sum(0) / w.sum()  # weighted combination
 ```
 
 fitness = x[:, 0]  # first column
 
As I understand we get first column from model's results.csv (first metric) ?
If I understood everything correctly, it might be convenient to be able to specify the metric that we are optimizing as a parameter.

And if we use code with data validation, then perhaps we would like to set the label obtained from validation as such a metric.
I run this code:

```
from ultralytics import YOLO

# Initialize the YOLO model
model = YOLO("yolov8l-pose.pt")

# Tune hyperparameters on COCO8 for 30 epochs
model.tune(
    data="my_data.yaml",
    epochs=5,
    iterations=5,
    optimizer="AdamW",
    plots=False,
    save=False,
    val=True
)
```
 
And I get this result
```
Tuner: Best fitness=0.04088 observed at iteration 4
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.02043, 'metrics/recall(B)': 0.2568, 'metrics/mAP50(B)': 0.01292, 'metrics/mAP50-95(B)': 0.00302, 'metrics/precision(P)': 0.06191, 'metrics/recall(P)': 0.59819, 'metrics/mAP50(P)': 0.05638, 'metrics/mAP50-95(P)': 0.0347, 'val/box_loss': nan, 'val/pose_loss': nan, 'val/kobj_loss': nan, 'val/cls_loss': nan, 'val/dfl_loss': nan, 'fitness': 0.04088}
```
All validations metrics are set as `nan`.

**Comment by glenn-jocher** [comment]
@medphisiker hello!

In the current implementation of the `model.tune()` method in Ultralytics YOLO, the fitness metric used for hyperparameter tuning is predefined and typically represents a composite score derived from several performance metrics (like precision, recall, mAP, etc.). This composite score is what's used to guide the optimization process.

Currently, there isn't a built-in option to specify a custom metric directly via the `model.tune()` function. The fitness metric is automatically calculated and used internally. If you're looking to optimize based on a specific metric from the validation results, you would need to modify the source code of the tuning process to adjust which metrics are considered for calculating fitness.

For handling `nan` values in your validation metrics, ensure that your dataset is correctly annotated and that the model is receiving the right inputs. `nan` often indicates issues with input data or configuration settings.

If customizing the fitness function is crucial for your application, you might consider contributing to the repository or creating a fork where you can implement this functionality. The community or the Ultralytics team could also find this feature beneficial.

Hope this helps! Let us know if you have further questions.

**Comment by medphisiker** [comment]
Thank you Glenn, for your quick and detailed reply)
Now I understand how it counts fitness metric)
Thanks, I'll experiment with the source code, if something good turns out, I'll send a Pull Request)

Also I wanted to ask about the comment in the 78th line of the file [link](https://github.com/ultralytics/ultralytics/blob/c8b6a8bc37ce196a6b7e0c153539402db4383c16/ultralytics/engine/tuner.py).

```
    def __init__(self, args=DEFAULT_CFG, _callbacks=None):
        """
        Initialize the Tuner with configurations.

        Args:
            args (dict, optional): Configuration for hyperparameter evolution.
        """
        self.space = args.pop("space", None) or {  # key: (min, max, gain(optional))
            # 'optimizer': tune.choice(['SGD', 'Adam', 'AdamW', 'NAdam', 'RAdam', 'RMSProp']),
            "lr0": (1e-5, 1e-1),  # initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
            "lrf": (0.0001, 0.1),  # final OneCycleLR learning rate (lr0 * lrf)
  ```
  
  There is interesting comment about 
```
# 'optimizer': tune.choice(['SGD', 'Adam', 'AdamW', 'NAdam', 'RAdam', 'RMSProp'])
```

I wanted to clarify, can we set parameters to iterate over parameters using `ray tune`'s methods?
For example
```
from ultralytics import YOLO
from ray import tune

# Initialize the YOLO model
model = YOLO("yolov8l-pose.pt")

# Tune hyperparameters on COCO8 for 30 epochs
model.tune(
    project="tuner_runs_test",
    data="data.yaml",
    epochs=30,
    iterations=300,
    optimizer="Adam",
    plots=False,
    save=False,
    val=True,
    space={"param1": (1e-5, 1e-1), 
        "param2": tune.grid_search([0.001, 0.01, 0.1, 1.0]),
        "param3": tune.choice([1, 2, 3]}
)
```

**Comment by glenn-jocher** [comment]
Hello @medphisiker,

Absolutely! You can indeed use Ray Tune's methods to iterate over different hyperparameters, including using functions like `tune.grid_search` and `tune.choice` as you've shown in your example. This allows for a more dynamic and extensive exploration of the parameter space, which can be very beneficial for optimizing your model's performance.

Just ensure that the `space` parameter in your `model.tune()` call correctly defines the search space using Ray Tune's search space definitions, as you've done. This should enable you to experiment with various configurations effectively.

If you have any more questions or need further assistance, feel free to ask. Good luck with your tuning experiments! 😊🚀

**Comment by medphisiker** [comment]
Thank you, Glenn )

**Comment by glenn-jocher** [comment]
@medphisiker you're welcome! If you have any more questions or need further assistance as you experiment with the source code, feel free to reach out. Happy coding! 😊🚀

**Comment by javierselva** [comment]
Hi! I recently wanted to play around with this fitness function as well, as I need to ensure high recall over precise detection, so here's my two cents. As far as I know, the fitness metric is reported by the validator class. And I think that [this is the metric being used](https://github.com/ultralytics/ultralytics/blob/5cf31ada2dcf7b8ec474f18e2849618855c8cdc1/ultralytics/utils/metrics.py#L894) to optimize the evolutionary algorithm (as well as, for instance, selecting best.pt).  

I see that they seem to be working on this "custom fitness" on [this pull request](https://github.com/ultralytics/ultralytics/pull/18269). In the meantime, here's the workaround I'm using:

In [utils/\__init\__.py ](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/__init__.py) I added this class:
```
# Define singleton fitness config so it can be used globally in the package.
class FitnessConfig:
    _weights = [0.0, 0.4, 0.3, 0.3]  # set this with whatever default weights you need

    @classmethod
    def set_weights(cls, weights):
        cls._weights = weights

    @classmethod
    def get_weights(cls):
        return cls._weights
```

In my custom main.py which calls either tune or train etc. I set the parameters like this:
```
from utils import FitnessConfig

# .... (set args.fitP and so on) ...

FitnessConfig.set_weights([args.fit_P, args.fit_R, args.fit_M5, args.fit_M95])

```

Finally, modify the Metric class in [metrics.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/metrics.py):
```
from utils import FitnessConfig
```
within [\__init\__](https://github.com/ultralytics/ultralytics/blob/5cf31ada2dcf7b8ec474f18e2849618855c8cdc1/ultralytics/utils/metrics.py#L799)
```
self.weights = FitnessConfig.get_weights()
```
within Metric.fitness(), replace [this line](https://github.com/ultralytics/ultralytics/blob/5cf31ada2dcf7b8ec474f18e2849618855c8cdc1/ultralytics/utils/metrics.py#L896) with:
```
w = self.weights
```

So far it seems to be working for me. I hope it can help someone!
