### ISSUE TITLE
How can i use MPII dataset for YoloV8-pose training 

### ISSUE THREAD

**Issue by Mukhammadkhasnen** [ultralytics/ultralytics#12982]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

so i am trying to use MPII dataset to train yolov8-pose but i seem to not find the Bounding Box value in MPII dataset if there is anyway that i could convert it to yolov8 format for training or any way that i can get the Bounding box value from MPII please let me know

**Comment by glenn-jocher** [comment]
Hello! To use the MPII dataset for training YOLOv8-pose, you'll need to generate bounding boxes since MPII primarily provides keypoints. You can calculate the bounding boxes from the keypoints by determining the minimum and maximum coordinates for each set of keypoints to form a box.

Here's a basic Python snippet to help you get started:

```python
import numpy as np

def keypoints_to_bbox(keypoints):
    # Assuming keypoints is a list of (x, y) tuples
    keypoints = np.array(keypoints)
    x_coords = keypoints[:, 0]
    y_coords = keypoints[:, 1]
    bbox = [np.min(x_coords), np.min(y_coords), np.max(x_coords), np.max(y_coords)]
    return bbox

# Example usage
keypoints = [(100, 100), (150, 200), (100, 200), (150, 100)]
bbox = keypoints_to_bbox(keypoints)
print("Bounding Box:", bbox)
```

After generating bounding boxes, format your dataset labels according to the YOLOv8 pose requirements, which include class index, bounding box coordinates, and keypoints.

If you need further assistance or have more questions, feel free to ask! 🚀

**Comment by Song-Jie-ing** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> ### Question
> so i am trying to use MPII dataset to train yolov8-pose but i seem to not find the Bounding Box value in MPII dataset if there is anyway that i could convert it to yolov8 format for training or any way that i can get the Bounding box value from MPII please let me know
> 
> ### Additional
> _No response_

Hello, I have encountered the same problem as you. Has your issue been resolved?

**Comment by Mukhammadkhasnen** [comment]
Hello, Yes i had my Issue resolved had to generate the Bounding Box values by writing a script to calculate it by getting the **max(x,y)** values from **keypoints** and **min(x,y)** value from the **keypoints** data as the MPII dataset doesn't have Bounding box value provided. There was still one problem as the Bounding box was not exactly what i wanted so i didn't continue with the MPII dataset for long you can try it if you want one such script was mentioned by @glenn-jocher or you can write your own

**Comment by Mukhammadkhasnen** [comment]
> > > > ### Search before asking
> > > > 
> > > > * [x]     I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> > > > 
> > > > ### Question
> > > > so i am trying to use MPII dataset to train yolov8-pose but i seem to not find the Bounding Box value in MPII dataset if there is anyway that i could convert it to yolov8 format for training or any way that i can get the Bounding box value from MPII please let me know
> > > > ### Additional
> > > > _No response_
> > > 
> > > 
> > > Hello, I have encountered the same problem as you. Has your issue been resolved?
> > 
> > 
> > Hello, Yes i had my Issue resolved had to generate the Bounding Box values by writing a script to calculate it by getting the **max(x,y)** values from **keypoints** and **min(x,y)** value from the **keypoints** data as the MPII dataset doesn't have Bounding box value provided. There was still one problem as the Bounding box was not exactly what i wanted so i didn't continue with the MPII dataset for long you can try it if you want one such script was mentioned by @glenn-jocher or you can write your own
> 
> Actually, I am currently processing a dataset that converts MPII to YOLO format. How did you convert it? Can I obtain the dataset that you have processed?

Are you trying to convert it from the Matlab version or Json version? i have both right now. Which one are you trying to convert?

**Comment by Song-Jie-ing** [comment]
> > > > > ### Search before asking
> > > > > 
> > > > > * [x]      I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> > > > > 
> > > > > ### Question
> > > > > so i am trying to use MPII dataset to train yolov8-pose but i seem to not find the Bounding Box value in MPII dataset if there is anyway that i could convert it to yolov8 format for training or any way that i can get the Bounding box value from MPII please let me know
> > > > > ### Additional
> > > > > _No response_
> > > > 
> > > > 
> > > > Hello, I have encountered the same problem as you. Has your issue been resolved?
> > > 
> > > 
> > > Hello, Yes i had my Issue resolved had to generate the Bounding Box values by writing a script to calculate it by getting the **max(x,y)** values from **keypoints** and **min(x,y)** value from the **keypoints** data as the MPII dataset doesn't have Bounding box value provided. There was still one problem as the Bounding box was not exactly what i wanted so i didn't continue with the MPII dataset for long you can try it if you want one such script was mentioned by @glenn-jocher or you can write your own
> > 
> > 
> > Actually, I am currently processing a dataset that converts MPII to YOLO format. How did you convert it? Can I obtain the dataset that you have processed?
> 
> Are you trying to convert it from the Matlab version or Json version? i have both right now. Which one are you trying to convert?

I want to convert from Matlab format to yolo txt format and train with yolopose

**Comment by Mukhammadkhasnen** [comment]
> > > > > > ### Search before asking
> > > > > > 
> > > > > > * [x]       I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> > > > > > 
> > > > > > ### Question
> > > > > > so i am trying to use MPII dataset to train yolov8-pose but i seem to not find the Bounding Box value in MPII dataset if there is anyway that i could convert it to yolov8 format for training or any way that i can get the Bounding box value from MPII please let me know
> > > > > > ### Additional
> > > > > > _No response_
> > > > > 
> > > > > 
> > > > > Hello, I have encountered the same problem as you. Has your issue been resolved?
> > > > 
> > > > 
> > > > Hello, Yes i had my Issue resolved had to generate the Bounding Box values by writing a script to calculate it by getting the **max(x,y)** values from **keypoints** and **min(x,y)** value from the **keypoints** data as the MPII dataset doesn't have Bounding box value provided. There was still one problem as the Bounding box was not exactly what i wanted so i didn't continue with the MPII dataset for long you can try it if you want one such script was mentioned by @glenn-jocher or you can write your own
> > > 
> > > 
> > > Actually, I am currently processing a dataset that converts MPII to YOLO format. How did you convert it? Can I obtain the dataset that you have processed?
> > 
> > 
> > Are you trying to convert it from the Matlab version or Json version? i have both right now. Which one are you trying to convert?
> 
> I want to convert from Matlab format to yolo txt format and train with yolopose

If you just want the MPII dataset i can provide you the Json version of it and you can convert it to YOLO format but have to write the script for that. During the conversion in Matlab there was some issues in reading and getting data as most of the data is missing in Matlab Annotations so had to skip those data.

**Comment by Song-Jie-ing** [comment]
Thank you very much. If you could provide me with the JSON format, it would be of great help to me

**Comment by Mukhammadkhasnen** [comment]
hussnainnaveed17@gmail.com kindly send a mail on this so i can sent the json to you through mail

**Comment by glenn-jocher** [comment]
Sure, I can provide you with the JSON format of the MPII dataset. Please let me know how you'd like to receive it.

**Comment by Song-Jie-ing** [comment]
> Sure, I can provide you with the JSON format of the MPII dataset. Please let me know how you'd like to receive it.

2013270272@qq.com


Thank you very much.

**Comment by glenn-jocher** [comment]
For data sharing and support, please refer to the official MPII dataset website or relevant repositories. We do not provide direct data transfers. Thank you for understanding.
