### ISSUE TITLE
Run Yolov8 on Jetson Nano with TensorRt

### ISSUE THREAD

**Issue by Ahelsamahy** [ultralytics/ultralytics#12988]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I managed to make a docker image that can run Yolov8 on Jetson nano dev kit, using TensorRt. I'm sharing here so no one would have to go through the building time I had to go through (the pain is real)

You can find the image [here](https://github.com/MWLCDev/BYODR/blob/RFC0008_Following/docker/bionic-torch1.11-cp38-cuda10.2-TRT.Dockerfile) if you want to build it yourself. You can save the effort and pull directly from [dockerhub ](https://hub.docker.com/repository/docker/mwlvdev/jetson-nano-ubuntu/tags) under `docker pull mwlvdev/jetson-nano-ubuntu:bionic-torch1.10-cp38-cuda10.2-TRT` 

### Use case

I did run some tests, and the `.engine` model is faster than the `.pt` model by nearly 42% when running inference 300 times on the bus image. I attached image for the full result.

![onnx vs pt1](https://github.com/ultralytics/ultralytics/assets/10195309/f8c12942-8f61-4b28-8711-53ee42e6724d)

One thing I noticed is that `.engine` inference time is slower when it boots, but after that it is steady 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Ahelsamahy thanks for sharing your Docker image for running YOLOv8 on Jetson Nano with TensorRT! 🚀 This is a fantastic contribution to the community, especially highlighting the performance boost with the `.engine` model. Your observation about the initial slow inference times is typical with TensorRT as it optimizes the execution plan on the first run.

For those looking to replicate or extend your work, they can pull your Docker image directly or build it using your Dockerfile. This should indeed save a lot of setup time and pain!

If you encounter any specific issues or have further optimizations, feel free to discuss them here or contribute improvements through a PR. Your efforts are greatly appreciated! 🙌

**Comment by Ahelsamahy** [comment]
Hi @glenn-jocher, I would be happy to contribute with it. Is there a way to make it into the code base. Maybe have it as a ready made docker image in the docker hub repo?

I would be happy to submit a PR with it if needed

**Comment by glenn-jocher** [comment]
Hi @Ahelsamahy, that sounds like a great idea! 🌟 Having a ready-made Docker image available on Docker Hub would definitely streamline the setup process for many users. 

To proceed, you can submit a PR with the Dockerfile and any necessary documentation or scripts. Please ensure the documentation clearly explains how to use the Docker image. Once reviewed, we can look into hosting it officially under the Ultralytics Docker Hub account.

Thanks for your willingness to contribute! Looking forward to your PR. 🚀

**Comment by Ahelsamahy** [comment]
Hi @glenn-jocher, I submited the docker image https://github.com/ultralytics/ultralytics/pull/13100. Feel free to mention there if there are extra docs you would need

**Comment by glenn-jocher** [comment]
Hi @Ahelsamahy, thanks for submitting the PR for the Docker image! 🎉 I'll review it and let you know if we need any additional documentation or changes. Great work!

**Comment by glenn-jocher** [comment]
Hi @jasonlytehouse,

Thank you for sharing your project! It's great to see more resources available for running Ultralytics YOLO models on Jetson Nano. Your Docker image with Python 3.11 support could indeed be very useful for those needing higher Python versions.

For anyone interested, you can check out @jayfalls' project [here](https://github.com/jayfalls/jetson_nano_ubuntu20_docker/tree/main).

If you encounter any issues or have further questions, feel free to reach out. Happy coding! 🚀

**Comment by lakshanthad** [comment]
Closing issue since the PR is merged.
https://github.com/ultralytics/ultralytics/pull/13100
