### ISSUE TITLE
Have to convert best.pt model to tflite format

### ISSUE THREAD

**Issue by mayurkatre18** [ultralytics/ultralytics#12985]
from ultralytics import YOLO
model = YOLO('path_to_yolov8n.pt')
model.export(format='tflite')

# I went for solution but didn't find it
TensorFlow SavedModel: export failure ❌ 19.1s: generic_type: cannot initialize type "StatusCode": an object with that name is already defined
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-15-fc02ec6f5ea5>](https://localhost:8080/#) in <cell line: 4>()
      2 
      3 model  = YOLO("/content/runs/segment/train/weights/best.pt")
----> 4 model.export(format='tflite')

11 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow_lite_support/python/task/vision/core/tensor_image.py](https://localhost:8080/#) in <module>
     17 
     18 from tensorflow_lite_support.python.task.vision.core import color_space_type
---> 19 from tensorflow_lite_support.python.task.vision.core.pybinds import image_utils
     20 
     21 

ImportError: generic_type: cannot initialize type "StatusCode": an object with that name is already defined

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by glenn-jocher** [comment]
It looks like you're encountering an `ImportError` during the export process to TFLite format. This error might be related to conflicting TensorFlow versions or duplicate imports in your environment.

Here's a quick suggestion to potentially resolve this issue:

1. Ensure that your environment has the correct TensorFlow and TensorFlow Lite versions installed. You might need to uninstall and then reinstall TensorFlow to avoid conflicts:
   ```bash
   pip uninstall tensorflow tensorflow-lite
   pip install tensorflow==2.x tensorflow-lite
   ```

2. After adjusting your TensorFlow installation, try exporting your model again:
   ```python
   from ultralytics import YOLO
   model = YOLO('path_to_best.pt')
   model.export(format='tflite')
   ```

If the problem persists, consider isolating your Python environment using virtual environments like `venv` or `conda` to manage dependencies more effectively.

**Comment by mayurkatre18** [comment]
Yes I have install necessary packages only. And I'm training this model on google collab so it is clear environment only. Help me with this.

**Comment by glenn-jocher** [comment]
@mayurkatre18 it seems like there might be a version conflict or a specific issue with TensorFlow Lite in the Google Colab environment. To potentially resolve this, you could try explicitly installing a compatible version of TensorFlow and TensorFlow Lite. Here's a quick snippet you can run in your Colab notebook:

```python
!pip install tensorflow==2.8.0
!pip install tflite-support
```

After installation, try exporting your model again:

```python
from ultralytics import YOLO
model = YOLO('path_to_
