### ISSUE TITLE
Bug in torch.unique(return_counts=True) on MPS device results in incorrect counts and negative tensor dimensions

### ISSUE THREAD

**Issue by ZelinBobyard** [ultralytics/ultralytics#12999]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

In the preprocess() function within loss.py:

```
print("i.unique(return_counts=True)", i.unique(return_counts=True))
# Output: (tensor([0.], device='mps:0'), tensor([9223372036854775807], device='mps:0'))
# This results in 'counts' being 'tensor([9223372036854775807], device='mps:0')'.

counts = counts.to(dtype=torch.int32)
# Output: tensor([-1], device='mps:0', dtype=torch.int32)

out = torch.zeros(batch_size, counts.max(), 5, device=self.device)
# Raises RuntimeError: Trying to create tensor with negative dimension -1: [2, -1, 5]
```

### Environment

Ultralytics YOLOv8.2.17 🚀 Python-3.11.9 torch-2.3.0 CPU (Apple M3 Pro)
Setup complete ✅ (12 CPUs, 18.0 GB RAM, 102.5/460.4 GB disk)

OS                  macOS-14.3-arm64-arm-64bit
Environment         Darwin
Python              3.11.9
Install             pip
RAM                 18.00 GB
CPU                 Apple M3 Pro
CUDA                None

matplotlib          ✅ 3.8.4>=3.3.0
opencv-python       ✅ 4.7.0.72>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.13.0>=1.4.1
torch               ✅ 2.3.0>=1.8.0
torchvision         ✅ 0.18.0>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Minimal Reproducible Example

Inside the ultralytics.utils.loss.py, the preprocess() function, reproduce the bug by adding:

```
wzl_cpu = torch.tensor([0.0]).to('cpu')
wzl_mps = torch.tensor([0.0]).to('mps')
print(wzl_cpu.unique(return_counts=True))
# Output: (tensor([0.]), tensor([1]))

print(wzl_mps.unique(return_counts=True))
# Output: (tensor([0.], device='mps:0'), tensor([9223372036854775807], device='mps:0'))
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ZelinBobyard hello! Thanks for the detailed report. It seems like you've encountered a known issue with `torch.unique(return_counts=True)` on MPS devices, which results in incorrect count values.

As a workaround, you might consider performing this operation on the CPU and then transferring the results back to the MPS device. Here's a quick example:

```python
# Perform unique operation on CPU
wzl_mps = torch.tensor([0.0]).to('mps')
wzl_cpu = wzl_mps.to('cpu')
unique_values, counts = wzl_cpu.unique(return_counts=True)

# Convert back to MPS device if necessary
unique_values_mps = unique_values.to('mps')
counts_mps = counts.to('mps')

print("Unique values:", unique_values_mps)
print("Counts:", counts_mps)
```

This should provide the correct counts. We appreciate your patience and are looking into a more permanent fix for this issue. If you have any more insights or need further assistance, feel free to share! 🚀

**Comment by Y-T-G** [comment]
Can you open an issue on PyTorch repo about this if it still occurs?
