### ISSUE TITLE
Get results as YOLO annotation

### ISSUE THREAD

**Issue by gillonba** [ultralytics/ultralytics#12998]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a script that runs detection with a custom model against collections of images, but I am looking to streamline the training for my model.  Ideally, I would like to automatically flag and save images where one or more detections has a low confidence, along with the detected bounding boxes.  This way I can later go through with an annotator and verify and/or adjust the annotations to re-train the model.  

Is there a way to output the current detection results in YOLO format?  Since it is the default format for training, it seems like the kind of thing Ultralytics would have built already but I can't seem to find it in the docs.  Yes, I know I can collect the data from the results object and build the YOLO file myself, but I would prefer to avoid duplicating work if possible.  Thank you

**Comment by glenn-jocher** [comment]
Hello! It sounds like you're looking to automate the process of saving detections with low confidence scores for further annotation. Currently, YOLOv8 does not directly output detections in YOLO annotation format, but you can easily extract this information from the `Results` object and format it accordingly.

Here's a quick example of how you might do this in Python:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('path/to/your/custom_model.pt')

# Run predictions
results = model.predict(source='path/to/your/images')

# Save low confidence detections
threshold = 0.25  # Set your confidence threshold
for result in results:
    for box in result.boxes:
        if box.conf < threshold:
            with open('low_conf_detections.txt', 'a') as file:
                # Format: class x_center y_center width height
                x_center, y_center, width, height = (box.xywh / result.orig_img.shape[1::-1]).tolist()
                file.write(f'{int(box.cls)} {x_center} {y_center} {width} {height}\n')
```

This script will append the low confidence detections to a text file in the YOLO format. You can adjust the `threshold` as needed to capture the detections you're interested in reviewing. Hope this helps!
