### ISSUE TITLE
how to write a self-defined .yaml file for HICO-DET dataset

### ISSUE THREAD

**Issue by safsfsvvea** [ultralytics/ultralytics#12992]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to test yolov8's detection performance on HICO-DET, and finetune it on HICO-DET. I already transform the annotation file of HICO-DET to a json file in the format of COCO, and I want to use model.val for evaluation and model.train for training. However, I find some difficulty writing .yaml file for my local HICO-DET dataset. 
Below is my .yaml file:
# hico.yaml

# Path to the dataset root
path: ~/data/hico_20160224_det

# Relative paths to train, validation, and test image directories
train: images/train2015
val: images/test2015
test: images/test2015

# Path to the annotations file
annotations:
  train: ~/data/hico_20160224_det/coco_train.json
  val: ~/data/hico_20160224_det/coco_test.json
  test: ~/data/hico_20160224_det/coco_test.json

# Classes
names:
same as COCO

but when running 
results = model.val(data="hico.yaml", workers=2)
I encounter the following error:
val: Scanning ~/data/hico_20160224_det/labels/test2015.cache... 0 images, 9658 backgrounds, 0 corrupt
WARNING ⚠️ No labels found in ~/RLIPv2/data/hico_20160224_det/labels/test2015.cache, training may not work correctly. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 604/604 [04:58<00:00,  2.02it/s]
                   all       9658          0          0          0          0          0
WARNING ⚠️ no labels found in detect set, can not compute metrics without labels
Speed: 0.2ms preprocess, 8.0ms inference, 0.0ms loss, 7.1ms postprocess per image
Results saved to ~/ultralytics/runs/detect/val11
Traceback (most recent call last):
  File "~/ultralytics/test.py", line 25, in <module>
    print(results)
  File "~/ultralytics/ultralytics/utils/__init__.py", line 145, in __str__
    v = getattr(self, a)
  File "~/ultralytics/ultralytics/utils/__init__.py", line 162, in __getattr__
    raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
AttributeError: 'DetMetrics' object has no attribute 'curves_results'. See valid attributes below.

    This class is a utility class for computing detection metrics such as precision, recall, and mean average precision
    (mAP) of an object detection model.

    Args:
        save_dir (Path): A path to the directory where the output plots will be saved. Defaults to current directory.
        plot (bool): A flag that indicates whether to plot precision-recall curves for each class. Defaults to False.
        on_plot (func): An optional callback to pass plots path and data when they are rendered. Defaults to None.
        names (tuple of str): A tuple of strings that represents the names of the classes. Defaults to an empty tuple.

    Attributes:
        save_dir (Path): A path to the directory where the output plots will be saved.
        plot (bool): A flag that indicates whether to plot the precision-recall curves for each class.
        on_plot (func): An optional callback to pass plots path and data when they are rendered.
        names (tuple of str): A tuple of strings that represents the names of the classes.
        box (Metric): An instance of the Metric class for storing the results of the detection metrics.
        speed (dict): A dictionary for storing the execution time of different parts of the detection process.

    Methods:
        process(tp, conf, pred_cls, target_cls): Updates the metric results with the latest batch of predictions.
        keys: Returns a list of keys for accessing the computed detection metrics.
        mean_results: Returns a list of mean values for the computed detection metrics.
        class_result(i): Returns a list of values for the computed detection metrics for a specific class.
        maps: Returns a dictionary of mean average precision (mAP) values for different IoU thresholds.
        fitness: Computes the fitness score based on the computed detection metrics.
        ap_class_index: Returns a list of class indices sorted by their average precision (AP) values.
        results_dict: Returns a dictionary that maps detection metric keys to their computed values.
        curves: TODO
        curves_results: TODO

I think maybe it is the problem of the format of .yaml file, so I wonder how to write the correct .yaml file for HICO-DET dataset

**Comment by glenn-jocher** [comment]
It looks like your `.yaml` file is mostly correct, but you might be encountering issues due to the `names` field and the label paths. Here's a quick guide to ensure your `.yaml` file is set up correctly:

1. **Names Field**: Make sure to explicitly list all class names under the `names` field instead of using "same as COCO". This ensures clarity and prevents potential parsing errors.

2. **Label Paths**: Your error suggests that the labels are not being found. Ensure that your `annotations` paths in the `.yaml` file are correct and accessible. Also, verify that the JSON files are properly formatted according to the COCO format.

Here’s a revised snippet of your `.yaml` file:

```yaml
# hico.yaml

# Path to the dataset root
path: ~/data/hico_20160224_det

# Relative paths to train, validation, and test image directories
train: images/train2015
val: images/test2015
test: images/test2015

# Path to the annotations file
annotations:
  train: annotations/coco_train.json
  val: annotations/coco_test.json
  test: annotations/coco_test.json

# Classes
names:
  - person
  - bicycle
  - car
  # Add all other classes as needed
```

Make sure your annotations are stored in the `annotations` folder under your dataset root and that the JSON files are correctly referenced in your `.yaml` file. If the issue persists, double-check the JSON format and ensure it matches the expected COCO format.

**Comment by safsfsvvea** [comment]
@glenn-jocher thank you very much for your help.
I find that I need to follow https://docs.ultralytics.com/datasets/detect/#port-or-convert-label-formats to transformer the json file from normal coco format to yolo format.

**Comment by glenn-jocher** [comment]
You're welcome! Yes, following the guide on converting the COCO format to the YOLO format is the right approach. If you encounter any issues during the conversion, feel free to ask for help here. Happy coding! 🚀
