### ISSUE TITLE
Ideal first-principles usage examples

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/ultralytics#13]
### YOLOv8
```python
from ultralytics import YOLO
# from ultralytics import YOLOv8 (where YOLO == YOLOv8)

# Model (DetectionModel, ClassificationModel, SegmentationModel)
model = YOLO('YOLOv8s.pt')  # load local/official/URL autodownload model including yolov5s.pt etc.
model = YOLO('YOLOv8s.yaml')  # new model from yaml

model.reset_weights()  # reset all weights, i.e. for pretrained=False from-scratch trainings
model.fuse()  # fuse for inference
model.info()  # show parameters, FLOPs, layers
model.names  # class names dict, i..e {0: 'person', 1: 'bus', ...}

# Train
results = model.train(data='data.yaml', epochs=300, imgsz=640, device=[0,1,2,4])  # or  model.resume_train()

# Train Roboflow
from roboflow import Roboflow
rf = Roboflow(api_key="kZidXHHHrAAr7GFJBcI1")
project = rf.workspace("roboflowyolov5moon").project("v5-mushrooms")
dataset = project.version(1).download("yolov5")
results = model.train(data=dataset, epochs=300, imgsz=640, device=[0,1,2,4])

results = model.train(data='https://app.roboflow.com/roboflowyolov5moon/v5-mushrooms/1', epochs=300, imgsz=640, device=[0,1,2,4])

# Val and Test  (remembers training settings, evaluates at same imgsz, on same dataset, etc.)
results = model.val(conf_thresh=0.001)
results = model.test(conf_thresh=0.001)

# Inference (DetectionResults, ClassificationResults, SegmentationResults)
results = model(source='path/to/images/')

# Save
success = model.save('model.pt', optimizer=False, ema=False)

# Export
results = model.export(format='coreml|onnx|torchscript|tflite|tfjs...')

# ADVANCED / NOT MVP / TODO AFTER LAUNCH
results = model.evolve()  # or  model.resume_evolve()
api_url = model.deploy(dest='HUB|aws|google|azure', credentials='...')
model_url = model.upload('HUB_KEY')
```

### HUB Python
```python
from ultralytics import HUB, YOLO

# Usage 1: Train from HUB
HUB.login('API_KEY')  # only required once
model = YOLO('https://hub.ultralytics.com/models/MODEL_KEY')
model.train()

# Usage 2: Train normally (sync to HUB)
model = YOLO('yolov8n.pt')
model.train(data='coco128.yaml', hub=False) # hub defaults to True if logged in

HUB.logout()
```

### HUB CLI

```python
# Auth
yolo hub login API_KEY  # only required once

# Usage 1: Train from HUB 
yolo train model='https://hub.ultralytics.com/models/MODEL_KEY'

# Usage 2: Train normally (sync to HUB)
yolo train model=yolov8n.pt data=coco128.yaml hub=False # hub defaults to True if logged in

yolo hub logout
```

### Prediction

| source     | stream  | model(arg)                                 | type           | notes            |
|------------|---------|--------------------------------------------|----------------|------------------|
| image      |         | `'im.jpg'`                                 | `str`, `Path`  |                  |
| URL        |         | `'https://ultralytics.com/images/bus.jpg'` | `str`          |                  |
| screenshot |         | `'screen'`                                 | `str`          |                  |
| PIL        |         | `Image.open('im.jpg')`                     | `PIL.Image`    | HWC, RGB         |
| OpenCV     |         | `cv2.imread('im.jpg')[:,:,::-1]`           | `np.ndarray`   | HWC, BGR to RGB  |
| numpy      |         | `np.zeros((640,1280,3))`                   | `np.ndarray`   | HWC              |
| torch      |         | `torch.zeros(16,3,320,640)`                | `torch.Tensor` | BCHW, RGB        |
| CSV        |         | `'sources.csv'`                            | `str`, `Path`  | RTSP, RTMP, HTTP |         
| video      | &check; | `'vid.mp4'`                                | `str`, `Path`  |                  |
| directory  | &check; | `'path/'`                                  | `str`, `Path`  |                  |
| glob       | &check; | `path/*.jpg'`                              | `str`          | Use `*` operator |
| YouTube    | &check; | `'https://youtu.be/Zgi9g1ksQHc'`           | `str`          |                  |
| stream     | &check; | `'rtsp://example.com/media.mp4'`           | `str`          | RTSP, RTMP, HTTP |

#### Single-batch
```python
file:        ims = 'data/images/zidane.jpg'  # str or Path
URL:             = 'https://ultralytics.com/images/zidane.jpg'
        #   screenshot  = 'screen'
        #   OpenCV:          = cv2.imread('image.jpg')[:,:,::-1]  # HWC BGR to RGB x(640,1280,3)
        #   PIL:             = Image.open('image.jpg') or ImageGrab.grab()  # HWC x(640,1280,3)
        #   numpy:           = np.zeros((640,1280,3))  # HWC
        #   torch:           = torch.zeros(16,3,320,640)  # BCHW (scaled to size=640, 0-1 values)
        #   multiple:        = [Image.open('image1.jpg'), Image.open('image2.jpg'), ...]  # list of images
```

#### Multi-batch/streaming
```python
0 # webcam
vid.mp4  # video
path/  # directory
path/*.jpg'  # glob
'https://youtu.be/Zgi9g1ksQHc'  # YouTube
'rtsp://example.com/media.mp4'  # RTSP, RTMP, HTTP stream
```

**Comment by AI-P-K** [comment]
@glenn-jocher  Hi, how do you extract bounding boxes and classes from results = model.predict(source='path/to/images/')
results = model(source='path/to/images/') ?

**Comment by glenn-jocher** [comment]
@AI-P-K you can type print(results) to see what's available in the object, or see Docs at https://docs.ultralytics.com/modes/predict
