### ISSUE TITLE
Shift of focus. version 8 gives very interesting results.

### ISSUE THREAD

**Issue by sarpx** [ultralytics/ultralytics#1300]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying v5,v6.2,v7 before and now v8.
Previously, we were teaching the oranges in the large plate in focus, as in the picture below, and we had no problems. The V8 started to catch the oranges on the left and right plates together with it, and this is not something we want. How can I solve this in v8.

### Additional

![k_17002942_IMG_20201216_201749](https://user-images.githubusercontent.com/73984193/223357969-9a8d1ff0-70a7-4eb9-bd47-f27ae5dfbea7.jpg)

**Comment by glenn-jocher** [comment]
@sarpx ideally an object detection model will detect all instances of all objects in an image, so there is nothing wrong, this is a good result.

If you want to scope detections to a certain part of an image then I suggest you crop that part and feed only that to the model.

**Comment by sarpx** [comment]
@glenn-jocher 
Thank you for the answer.
But you think he has to find everything he sees. I think it would be more flexible for him to give what we teach. In normal life, we are selective in perception. We see the people in our focus, not all the people on the road. Others are out of our perception when we do not pay attention. But yolo was already doing that and it was successful. I'm trying to understand why we compromised on that.
