### ISSUE TITLE
Is the angle value given by OBB correct?

### ISSUE THREAD

**Issue by Zzzxi** [ultralytics/ultralytics#13003]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I referenced the method of obtaining the angle from other problems with the following code：
for result in results:
    if hasattr(result, 'obb'):
        x = result.obb.xywhr[0][0]
        y = result.obb.xywhr[0][1]
        w = result.obb.xywhr[0][2]
        h = result.obb.xywhr[0][3]
        angle = result.obb.xywhr[0][4]
        print(f"OBB coordinates: {x}, {y}, {w}, {h} with angle {angle}")

But according to the resultant graph I got from my reasoning, the angle value is not correct, I would like to ask how the rotation is defined in xywhr? Isn't it an angle value in algebra?

![7c01bd149928b6ced6e177ba4649a136_720](https://github.com/ultralytics/ultralytics/assets/114201963/37b9ca0c-ab58-46cb-878e-1c4e50626b42)

Here is the output：
    OBB coordinates: 205.39146423339844, 431.62542724609375, 308.4459228515625, 108.02287292480469 with angle 
0.5296990275382996

**Comment by glenn-jocher** [comment]
Hello! Thanks for reaching out with your question about the angle value in the OBB (Oriented Bounding Box) output.

In YOLOv8's OBB format, the angle is defined in radians and represents the rotation of the bounding box relative to the horizontal axis. The rotation is clockwise, where an angle of 0 indicates no rotation.

If the visual output doesn't match your expectations, it might be helpful to verify the visualization method you're using. Sometimes discrepancies can arise from how the angles are interpreted or drawn in the visualization layer.

Here's a quick snippet on how you might convert the angle from radians to degrees for a clearer understanding:

```python
import math

# Assuming 'angle' is in radians from your OBB output
angle_degrees = angle * (180 / math.pi)
print(f"Angle in degrees: {angle_degrees}")
```

If the issue persists, please ensure that the visualization tool or method correctly interprets these values. Let us know if you need further assistance! 🚀

**Comment by Zzzxi** [comment]
You're right, I wasn't thinking carefully enough. Thank you.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further clarification, feel free to ask. Happy coding! 😊
