### ISSUE TITLE
Batch prediction not working with NCNN model

### ISSUE THREAD

**Issue by BDhaese** [ultralytics/ultralytics#13010]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Using : `model = YOLO('yolov8s.pt')` it works fine to pass a list to model.predict()
However when using `model = YOLO('yolov8s_ncnn_model')` it produces the following error:

![image](https://github.com/ultralytics/ultralytics/assets/62749510/f59d9d28-899a-498b-81fd-1a32bdd91090)

yolov8s_ncnn_model was made following the docs using model.export(format='ncnn')

### Environment

Ultralytics YOLOv8.2.15 🚀 Python-3.10.0 torch-2.3.0+cpu CPU (Intel Core(TM) i5-8300H 2.30GHz)
Setup complete ✅ (8 CPUs, 15.9 GB RAM, 550.8/930.3 GB disk)
None

### Minimal Reproducible Example

`import cv2
from ultralytics import YOLO

cap = cv2.VideoCapture(0)
i = 0
model_ncnn = YOLO('yolov8s_ncnn_model')
model_ncnn.classes = [0]

frames= []
while(i<5):

    ret, frame = cap.read()
    frames.append(frame)
    i += 1

results = model_ncnn.predict(source=frames)
cap.release()
`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@BDhaese hello! Thanks for reaching out with your issue regarding batch prediction with the NCNN model. 🌟

It seems like the NCNN model might not support batch predictions in the same way the PyTorch model does. NCNN is generally optimized for single-image inference on mobile and embedded devices, which could explain the discrepancy you're experiencing.

As a workaround, you might consider running a loop to process each frame individually, like this:

```python
import cv2
from ultralytics import YOLO

cap = cv2.VideoCapture(0)
model_ncnn = YOLO('yolov8s_ncnn_model')
model_ncnn.classes = [0]

results = []
while True:
    ret, frame = cap.read()
    if not ret:
        break
    result = model_ncnn.predict(source=frame)
    results.append(result)

cap.release()
```

This approach processes each frame as it's captured, which should avoid the batch processing issue.

Let us know if this helps or if you have any more questions! 🚀
