### ISSUE TITLE
TensorFlow.js: export failure

### ISSUE THREAD

**Issue by MahitejVardhan** [ultralytics/ultralytics#13026]
Ultralytics YOLOv8.2.19 🚀 Python-3.10.12 torch-2.3.0+cu121 CPU (Intel Xeon 2.00GHz)
Model summary (fused): 218 layers, 25840339 parameters, 0 gradients, 78.7 GFLOPs

PyTorch: starting from '/content/runs/detect/train4/weights/best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 5, 8400) (49.6 MB)

TensorFlow SavedModel: starting export with tensorflow 2.13.1...

ONNX: starting export with onnx 1.16.0 opset 17...
ONNX: simplifying with onnxsim 0.4.36...
ONNX: export success ✅ 8.0s, saved as '/content/runs/detect/train4/weights/best.onnx' (98.7 MB)
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.17.5...
TensorFlow SavedModel: export success ✅ 36.8s, saved as '/content/runs/detect/train4/weights/best_saved_model' (247.1 MB)

TensorFlow GraphDef: starting export with tensorflow 2.13.1...
TensorFlow GraphDef: export success ✅ 3.4s, saved as '/content/runs/detect/train4/weights/best.pb' (98.8 MB)
WARNING:root:TensorFlow Decision Forests 1.9.1 is compatible with the following TensorFlow Versions: ['2.16.1']. However, TensorFlow 2.13.1 was detected. This can cause issues with the TF API and symbols in the custom C++ ops. See the TF and TF-DF compatibility table at https://github.com/tensorflow/decision-forests/blob/main/documentation/known_issues.md#compatibility-table.
WARNING:root:Failure to load the inference.so custom c++ tensorflow ops. This error is likely caused the version of TensorFlow and TensorFlow Decision Forests are not compatible. Full error:/usr/local/lib/python3.10/dist-packages/tensorflow_decision_forests/tensorflow/ops/inference/inference.so: undefined symbol: _ZN10tensorflow20OpKernelConstruction21CtxFailureWithWarningEPKciRKN4absl12lts_202308026StatusE
TensorFlow.js: export failure ❌ 0.0s: /usr/local/lib/python3.10/dist-packages/tensorflow_decision_forests/tensorflow/ops/inference/inference.so: undefined symbol: _ZN10tensorflow20OpKernelConstruction21CtxFailureWithWarningEPKciRKN4absl12lts_202308026StatusE
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
[<ipython-input-22-f2102609a61e>](https://localhost:8080/#) in <cell line: 4>()
      2 
      3 # Export the model
----> 4 model.export(format='tfjs')

18 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/load_library.py](https://localhost:8080/#) in load_op_library(library_filename)
     52     RuntimeError: when unable to load the library or get the python wrappers.
     53   """
---> 54   lib_handle = py_tf.TF_LoadLibrary(library_filename)
     55   try:
     56     wrappers = _pywrap_python_op_gen.GetPythonWrappers(

NotFoundError: /usr/local/lib/python3.10/dist-packages/tensorflow_decision_forests/tensorflow/ops/inference/inference.so: undefined symbol: _ZN10tensorflow20OpKernelConstruction21CtxFailureWithWarningEPKciRKN4absl12lts_202308026StatusE

**Comment by glenn-jocher** [comment]
@MahitejVardhan you need to downgrade your TF, see your warning message:

WARNING:root:TensorFlow Decision Forests 1.9.1 is compatible with the following TensorFlow Versions: ['2.16.1']. However, TensorFlow 2.13.1 was detected.

**Comment by MahitejVardhan** [comment]
What I have to downgrade
Either Tensorflow or tensorflow decision forests?

**Comment by glenn-jocher** [comment]
You should upgrade your TensorFlow to version 2.16.1 to ensure compatibility with TensorFlow Decision Forests 1.9.1. This should resolve the compatibility issues you're experiencing. Here's how you can upgrade:

```bash
pip install tensorflow==2.16.1
```

Let us know if this helps or if you encounter any further issues! 🚀

**Comment by MahitejVardhan** [comment]
Thank you for your help!

**Comment by glenn-jocher** [comment]
@MahitejVardhan you're welcome! If upgrading to TensorFlow 2.16.1 resolves the issue or if you have any more questions, feel free to reach out. Happy coding! 🚀

**Comment by gangula-karthik** [comment]
> @MahitejVardhan you're welcome! If upgrading to TensorFlow 2.16.1 resolves the issue or if you have any more questions, feel free to reach out. Happy coding! 🚀

I'm trying to fix this issue as stated on #5161 and they say that we need to downgrade tensorflow to 2.13.1 for it to work. If you upgrade it you will not be able to export to even tflite format from the pt format. Is there another solution for this fix as it is quite frustrating to export models from pt to tfjs from any of the yolo versions.

**Comment by gangula-karthik** [comment]
never mind, I have managed to fix the issue and have updated the thread in #5161. To fix the issue I installed the below package versions inside the google colab environment: 

```
!pip install ultralytics==8.2.2
!pip install tensorflow==2.13.1
!pip install tensorflow-decision-forests==1.5.0
```

Below are some of the package versions that I am using: 
```
tensorflow==2.13.1
tensorflow-datasets==4.9.6
tensorflow-decision-forests==1.5.0
tensorflow-estimator==2.13.0
tensorflow-gcs-config==2.15.0
tensorflow-hub==0.16.1
tensorflow-io-gcs-filesystem==0.37.1
tensorflow-metadata==1.15.0
tensorflow-probability==0.23.0
tensorflowjs==4.20.0
ultralytics==8.2.2
```

Proof that it works: 

<img width="1071" alt="Screenshot 2024-07-16 at 11 11 41 PM" src="https://github.com/user-attachments/assets/f741f58b-58e1-4ed7-a502-afa973a49523">

**Comment by pderrenger** [comment]
@gangula-karthik great to hear you managed to resolve the issue! Thanks for sharing the solution and package versions you used. This will definitely help others facing similar problems. If you encounter any more issues or have further questions, feel free to reach out. Happy coding! 🚀
