### ISSUE TITLE
How to get the coordinate of the bounding box?

### ISSUE THREAD

**Issue by MikeHawkIsGold** [ultralytics/ultralytics#1302]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

```
from ultralytics import YOLO
from PIL import Image
import torch
import os

os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"


if __name__ == '__main__':
    # Load a model
    model = YOLO("runs\\detect\\train\\weights\\best.pt")  # load a pretrained model (recommended for training)

    # model.train(data="G:\BiShe\\ultralytics\\data.yaml", epochs=200)
    # model.val()
    # Use the model
    fileToUse = "test\\lvxiaojun.mp4"
    results = model.track(source=fileToUse,save=True)
    # model.export(format="torchscript")
```

Here is my code.
The model is used to track a barbell in a video. And I want to draw the motion trajectory of the barbell. So I think I must get the coordinate of bounding box.
Any solutions?

**Comment by glenn-jocher** [comment]
@MikeHawkIsGold box coordinates are available in your `results` object. 

See https://docs.ultralytics.com/predict/#working-with-results
