### ISSUE TITLE
why CPU always 100% 

### ISSUE THREAD

**Issue by TonightGo** [ultralytics/ultralytics#13022]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, thanks for your great work.
There are so many threads, and my cpu is nearly 100%. I set: 
torch.set_num_threads(1)
cv2.setNumThreads(1)
NUM_THREADS = 2
but it does not work.
![image](https://github.com/ultralytics/ultralytics/assets/20351057/60a28989-bf90-4811-ad84-99aa6fb12c8f)

**Comment by TonightGo** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/20351057/421075eb-7cdc-4443-b0c3-7f1dd6b8ea7c)

**Comment by TonightGo** [comment]
Thank you for your reply. I set workers=4, it works. Maybe my batch_size(512) is too large.

**Comment by glenn-jocher** [comment]
You're welcome! I'm glad to hear that setting `workers=4` helped. Indeed, a large `batch_size` like 512 can significantly increase CPU usage, especially during data loading and preprocessing. Reducing the batch size or optimizing the number of workers can help balance the load. If you have any more questions or need further assistance, feel free to ask! 😊
