### ISSUE TITLE
Training custom data and Find the coordinates of the bounding box

### ISSUE THREAD

**Issue by mazik1496** [ultralytics/ultralytics#1303]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Currently using ubuntu 20.04 and downloaded ultralytics to write yolo in gazebo virtual environment. I want to create a custom dataset, but would a dataset of around 2000 be enough?

![image0](https://user-images.githubusercontent.com/80936392/223402294-c850bed8-053e-4444-bd0f-a21c9608c37e.jpg)
And I learned the dataset through basic examples and detected objects in images based on it. Is there a way to get the coordinates (x,y,w,h) constituting the bounding box as you can see?

**Comment by glenn-jocher** [comment]
@mazik1496 yes 2000 images is sufficient to get started. For dataset guidelines see https://github.com/ultralytics/yolov5/wiki/Tips-for-Best-Training-Results

For handling detection results including retrieving bounding box coordinates see https://docs.ultralytics.com/predict/#working-with-results

**Comment by mazik1496** [comment]
Thank you for answers. Referring to the answer, I wrote the code as follows. But it doesn't seem to produce results for the bounding box. Can you tell me where to fix it?


----source code-----
from ultralytics import YOLO
import cv2

model = YOLO('yolov8n.pt")
img = cv2.imread('/home/user/python_code/bus.jpg')

results = model(img,show=True)
boxes = results[0].boxes
box = boxes[0]
box.xyxy

**Comment by pderrenger** [comment]
@mazik1496 the code you've written seems to be mostly correct. However, the method call `box.xyxy` should actually be `box.xyxy[0]` to retrieve the individual bounding box coordinates for the first detected object. Additionally, ensure that the correct YOLO model is loaded and that the image path is accurate. If you encounter any further issues, please refer to the YOLOv8 documentation for more detailed information on working with detection results.
