### ISSUE TITLE
How to run YOLOv8 predict on GPU without CUDA?

### ISSUE THREAD

**Issue by dy113g** [ultralytics/ultralytics#13033]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'd like to run YOLOv8.2 training and prediction models but without the use of CUDA. I have tried setting the device to GPU but I keep getting an attribute error. It's using CPU by default. How can I give it access to GPU but without CUDA?

![image](https://github.com/ultralytics/ultralytics/assets/143950634/75996d6e-b663-437f-ac9f-9ddeb82f099a)

![image](https://github.com/ultralytics/ultralytics/assets/143950634/072cba0b-5251-4302-b83c-2bf4a0505375)

![image](https://github.com/ultralytics/ultralytics/assets/143950634/cac3df50-015f-4bc4-abd9-f98d466e7386)

**Comment by glenn-jocher** [comment]
@dy113g hello! 👋

To run YOLOv8 on a GPU without using CUDA, you can utilize the MPS (Metal Performance Shaders) backend if you're on an Apple device with an M1 or M2 chip. Here's how you can specify the device as 'mps' in your code:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('yolov8n.pt')

# Set the device to MPS for Apple Silicon
results = model.predict('path/to/image.jpg', device='mps')
```

This will allow you to leverage the GPU capabilities of Apple Silicon without needing CUDA. If you're not on an Apple device, running YOLOv8 on a GPU generally requires CUDA as it relies on NVIDIA's GPU architecture.

Let me know if this helps or if you have any other questions!
