### ISSUE TITLE
FPN code 

### ISSUE THREAD

**Issue by MrFahad** [ultralytics/ultralytics#13032]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I have gone through the whole repo, but I couldn't find the feature pyramid network architecture code (the PANet) in the Ultralytics repository.  

Are we using this into YOLOv8 or any other version of YOLO or not???    If yes please show me the path.

**Comment by Zephyr69** [comment]
FPN backbone and PAN neck structures are already built-in block by block using the configuration file.

**Comment by MrFahad** [comment]
@Zephyr69 please share the path , as I couldn't find it.
