### ISSUE TITLE
Why my result predicted object has no bounding box?

### ISSUE THREAD

**Issue by dayangkunurfaizah** [ultralytics/ultralytics#13034]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello. I'm new user for google colab. Here's my full codes.

```
!nvidia-smi

!pip install ultralytics==8.0.196

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="9J4r7wGQ2iahmrEqr5lp")
project = rf.workspace("dayangkunurfaizah92-gmail-com").project("benign-malignat-detection")
version = project.version(1)
dataset = version.download("yolov8")

!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs=20 imgsz=640

Image(filename=f'/content/runs/detect/train/confusion_matrix.png', width=600)

Image(filename=f'/content/runs/detect/train/results.png', width=600)

!yolo task=detect mode=val model=/content/runs/detect/train/weights/best.pt data={dataset.location}/data.yaml

!yolo task=detect mode=predict model=/content/runs/detect/train/weights/best.pt conf=0.5 source={dataset.location}/test/images save=True

import glob
from IPython.display import Image, display

for image_path in glob.glob(f'/content/runs/detect/predict/*.jpg'):
      display(Image(filename=image_path, width=600))
      print("\n")
```
I'm using this sample from _https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/train-yolov8-object-detection-on-custom-dataset.ipynb_

**Comment by glenn-jocher** [comment]
Hello! It looks like you're doing everything right in setting up and running your model. If the predicted objects have no bounding boxes, it might be due to a few reasons:

1. **Low Confidence Threshold**: The model might be detecting objects but with a confidence lower than the threshold you've set (`conf=0.5`). Try lowering the threshold to see if the boxes appear, for example, `conf=0.25`.

2. **Model Training**: If the model is not well-trained or the dataset is too small, the model might not be able to make accurate predictions. Ensure your model has trained adequately on a sufficiently large and representative dataset.

3. **Post-Processing**: Ensure that the post-processing steps in the prediction phase are correctly handling the output. This includes correct parsing of the bounding box coordinates.

You can also check the output directly after prediction to see if any detections are being made at all:

```python
results = model.predict(source={dataset.location}/test/images, conf=0.5, save=True)
print(results.xyxy)  # This will print out the bounding box coordinates if there are any detections
```

If you're still facing issues, consider visualizing the training loss and accuracy to ensure the model is learning effectively. Let me know how it goes!

**Comment by dayangkunurfaizah** [comment]
Hello Sir. Thank you for your reply. Which line can I put the code that you mentioned above?

```
results = model.predict(source={dataset.location}/test/images, conf=0.5, save=True)
print(results.xyxy)
```
This is my full code.
```

!nvidia-smi

!pip install ultralytics==8.0.196

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="9J4r7wGQ2iahmrEqr5lp")
project = rf.workspace("dayangkunurfaizah92-gmail-com").project("benign-malignat-detection")
version = project.version(1)
dataset = version.download("yolov8")

!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs=20 imgsz=640

Image(filename=f'/content/runs/detect/train/confusion_matrix.png', width=600)

Image(filename=f'/content/runs/detect/train/results.png', width=600)

!yolo task=detect mode=val model=/content/runs/detect/train/weights/best.pt data={dataset.location}/data.yaml

!yolo task=detect mode=predict model=/content/runs/detect/train/weights/best.pt conf=0.5 source={dataset.location}/test/images save=True

import glob
from IPython.display import Image, display

for image_path in glob.glob(f'/content/runs/detect/predict/*.jpg'):
      display(Image(filename=image_path, width=600))
      print("\n")
```

I got this error when I put the results=predict ... in the last line my codes

**_NameError: name 'model' is not defined_** here's the ERROR MENTIONED.

**Comment by dayangkunurfaizah** [comment]
Also Sir. In my line code here

`!yolo task=detect mode=predict model=/content/runs/detect/train/weights/best.pt conf=0.25 source={dataset.location}/test/images save=True`

**_image 1/2 /content/Benign-Malignat-Detection-1/test/images/18_245_jpg.rf.60b2a08068a27ba8390c62dd4f45372c.jpg: 640x640 (no detections), 39.3ms
image 2/2 /content/Benign-Malignat-Detection-1/test/images/7_247_jpg.rf.1ca5ee1df4c166d8980d7e8936273526.jpg: 640x640 (no detections), 60.5ms_**

Its look line its says here (no detections) on image 1/2 and image 2/2. How to fix this Sir?

**Comment by glenn-jocher** [comment]
@dayangkunurfaizah hello! It seems like your model isn't detecting any objects in the images provided. Here are a couple of suggestions to help troubleshoot this issue:

1. **Lower the Confidence Threshold**: Try reducing the confidence threshold to see if the model can detect objects at a lower confidence level. You can adjust this in your prediction command:
   ```bash
   !yolo task=detect mode=predict model=/content/runs/detect/train/weights/best.pt conf=0.1 source={dataset.location}/test/images save=True
   ```

2. **Check Model Training**: Ensure that your model has been trained sufficiently and is generalizing well. Sometimes, if the training isn't adequate or the model hasn't converged, it might not perform well on the test data.

3. **Review the Training Data**: Make sure that the training data is correctly labeled and representative of the test images you're evaluating.

If these adjustments don't help, you might need to revisit your training process or consider using more training data. Good luck! 👍

**Comment by dayangkunurfaizah** [comment]
Hello Sir. I have changed the confidence threshold to 0.1, and it worked. But now the problem is that the bounding box detected a wrong/inaccurate position. How can I fix this to make the bounding box detected correctly? Here's the result that I got. Suppose the YOLOv8 could detect benign cases, but not as malignant cases. 

**_image 1/2 /content/Benign-Malignat-Detection-1/test/images/18_245_jpg.rf.60b2a08068a27ba8390c62dd4f45372c.jpg: 640x640 1 malignant, 37.1ms
image 2/2 /content/Benign-Malignat-Detection-1/test/images/7_247_jpg.rf.1ca5ee1df4c166d8980d7e8936273526.jpg: 640x640 2 malignants, 37.1ms
Speed: 2.3ms preprocess, 37.1ms inference, 295.1ms postprocess per image at shape (1, 3, 640, 640)_**

![Screenshot from 2024-05-26 08-14-05](https://github.com/ultralytics/ultralytics/assets/29174024/78262a75-894c-45ec-b56d-50d251fba846)

I have certainly checked for the training data labeling. Do I need to increase the training and testing data? Because I'm only using 20 images for this task.

**Comment by glenn-jocher** [comment]
@dayangkunurfaizah hello! Great to hear that lowering the confidence threshold helped! 🎉

For improving the accuracy of your bounding boxes, consider the following:

1. **Increase Training Data**: Using only 20 images is quite limited. More data can help the model learn better.
2. **Data Augmentation**: Apply data augmentation techniques to increase the diversity of your training set.
3. **Fine-Tuning**: Ensure your model is fine-tuned properly. You might need more epochs or a different learning rate.

Here's a quick example of how to apply data augmentation in your training script:

```python
model.train(data="/path/to/your/data.yaml", epochs=50, imgsz=640, augment=True)
```

Keep experimenting, and you'll get there! 🚀

**Comment by dayangkunurfaizah** [comment]
Hello Sir. I have increased training data by about 200 images. The result is getting better. Thank you, Sir. And now how to crop the detected object after training using YOLO? I want it to be cropped into 256x256 pixels and saved the image in the folder. Could you please show me how? Below are my codes:- where can I put the code for the cropping and save it?

`
!nvidia-smi

!pip install ultralytics==8.0.196

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="9J4r7wGQ2iahmrEqr5lp")
project = rf.workspace("dayangkunurfaizah92-gmail-com").project("benign-malignat-detection")
version = project.version(1)
dataset = version.download("yolov8")

!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs=20 imgsz=640

Image(filename=f'/content/runs/detect/train/confusion_matrix.png', width=600)

Image(filename=f'/content/runs/detect/train/results.png', width=600)

!yolo task=detect mode=val model=/content/runs/detect/train/weights/best.pt data={dataset.location}/data.yaml

!yolo task=detect mode=predict model=/content/runs/detect/train/weights/best.pt conf=0.5 source={dataset.location}/test/images save=True

import glob
from IPython.display import Image, display

for image_path in glob.glob(f'/content/runs/detect/predict/*.jpg'):
      display(Image(filename=image_path, width=600))
      print("\n")`

**Comment by glenn-jocher** [comment]
Hello @dayangkunurfaizah,

I'm glad to hear that increasing your training data has improved your results! Now, let's move on to cropping the detected objects and saving them as 256x256 pixel images.

You can achieve this by modifying your prediction code to include object cropping. Below is an example of how you can integrate object cropping into your existing code:

```python
!nvidia-smi

!pip install ultralytics==8.0.196

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="9J4r7wGQ2iahmrEqr5lp")
project = rf.workspace("dayangkunurfaizah92-gmail-com").project("benign-malignat-detection")
version = project.version(1)
dataset = version.download("yolov8")

!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs=20 imgsz=640

Image(filename=f'/content/runs/detect/train/confusion_matrix.png', width=600)

Image(filename=f'/content/runs/detect/train/results.png', width=600)

!yolo task=detect mode=val model=/content/runs/detect/train/weights/best.pt data={dataset.location}/data.yaml

!yolo task=detect mode=predict model=/content/runs/detect/train/weights/best.pt conf=0.5 source={dataset.location}/test/images save=True

import os
import cv2
import glob
from IPython.display import Image, display

# Create a directory to save cropped images
crop_dir_name = "cropped_images"
if not os.path.exists(crop_dir_name):
    os.mkdir(crop_dir_name)

# Load the model
model = YOLO("/content/runs/detect/train/weights/best.pt")

# Predict and crop objects
for image_path in glob.glob(f'{dataset.location}/test/images/*.jpg'):
    im0 = cv2.imread(image_path)
    results = model.predict(im0, conf=0.5)
    boxes = results[0].boxes.xyxy.cpu().tolist()
    clss = results[0].boxes.cls.cpu().tolist()

    for idx, (box, cls) in enumerate(zip(boxes, clss)):
        x1, y1, x2, y2 = map(int, box)
        crop_obj = im0[y1:y2, x1:x2]
        crop_obj_resized = cv2.resize(crop_obj, (256, 256))
        cv2.imwrite(os.path.join(crop_dir_name, f"{os.path.basename(image_path).split('.')[0]}_crop_{idx}.png"), crop_obj_resized)

# Display cropped images
for image_path in glob.glob(f'{crop_dir_name}/*.png'):
    display(Image(filename=image_path, width=256))
    print("\n")
```

### Explanation:
1. **Directory Creation**: We create a directory named `cropped_images` to save the cropped images.
2. **Model Loading**: Load the trained YOLO model.
3. **Prediction and Cropping**: For each image in the test set, we run predictions, extract bounding boxes, crop the detected objects, resize them to 256x256 pixels, and save them in the `cropped_images` directory.
4. **Display Cropped Images**: Finally, we display the cropped images.

Feel free to adjust the confidence threshold and other parameters as needed. If you have any further questions or run into issues, don't hesitate to ask. Happy coding! 😊

For more detailed information on object cropping, you can refer to our [Object Cropping Guide](https://docs.ultralytics.com/guides/object-cropping/).

**Comment by dayangkunurfaizah** [comment]
Hello Sir. Seems all worked for me. Now, where can I check the folder saved image after right away cropped the detected image, Sir? Are the folder cropped images in the Google Drive? Where can I find the "cropped images" folder?

**Comment by glenn-jocher** [comment]
Hello @dayangkunurfaizah,

Great to hear that everything worked for you! 😊

The "cropped_images" folder is created in the same directory where your Colab notebook is running, typically within the `/content` directory. If you want to save the cropped images directly to your Google Drive, you can mount your Google Drive and specify the path accordingly.

Here's how you can do it:

1. **Mount Google Drive**:
   ```python
   from google.colab import drive
   drive.mount('/content/drive')
   ```

2. **Specify the Google Drive Path**:
   ```python
   crop_dir_name = "/content/drive/MyDrive/cropped_images"
   if not os.path.exists(crop_dir_name):
       os.mkdir(crop_dir_name)
   ```

This will ensure that the "cropped_images" folder is created in your Google Drive, and all cropped images will be saved there.

Feel free to reach out if you have any more questions!

**Comment by dayangkunurfaizah** [comment]
Hello Sir, I have already mounted my own Google Drive. The folder "cropped images" appears but the images do not save into the folder. How can I save the image detected by Yolov8? I need to rename each of the images detected by Yolov8 in sequences and then put the image in the folder cropped images.

**Comment by glenn-jocher** [comment]
Hello @dayangkunurfaizah,

Thank you for your question! It sounds like you're almost there. Let's ensure that the cropped images are saved correctly to your Google Drive and renamed sequentially.

Here's an updated version of your code to save the cropped images in your Google Drive with sequential filenames:

```python
from google.colab import drive
import os
import cv2
import glob
from IPython.display import Image, display
from ultralytics import YOLO

# Mount Google Drive
drive.mount('/content/drive')

# Create a directory to save cropped images in Google Drive
crop_dir_name = "/content/drive/MyDrive/cropped_images"
if not os.path.exists(crop_dir_name):
    os.mkdir(crop_dir_name)

# Load the model
model = YOLO("/content/runs/detect/train/weights/best.pt")

# Predict and crop objects
image_counter = 0
for image_path in glob.glob(f'{dataset.location}/test/images/*.jpg'):
    im0 = cv2.imread(image_path)
    results = model.predict(im0, conf=0.5)
    boxes = results[0].boxes.xyxy.cpu().tolist()
    clss = results[0].boxes.cls.cpu().tolist()

    for idx, (box, cls) in enumerate(zip(boxes, clss)):
        x1, y1, x2, y2 = map(int, box)
        crop_obj = im0[y1:y2, x1:x2]
        crop_obj_resized = cv2.resize(crop_obj, (256, 256))
        image_counter += 1
        cv2.imwrite(os.path.join(crop_dir_name, f"crop_{image_counter}.png"), crop_obj_resized)

# Display cropped images
for image_path in glob.glob(f'{crop_dir_name}/*.png'):
    display(Image(filename=image_path, width=256))
    print("\n")
```

### Key Changes:
1. **Mount Google Drive**: Ensure your Google Drive is mounted.
2. **Create Directory in Google Drive**: Create the "cropped_images" directory in your Google Drive.
3. **Sequential Filenames**: Use a counter to rename each cropped image sequentially.

This should save each detected object as a cropped image in your Google Drive with filenames like `crop_1.png`, `crop_2.png`, etc.

If you encounter any further issues, please ensure you are using the latest versions of `torch` and `ultralytics`. If the problem persists, feel free to share a minimum reproducible example so we can investigate further. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Happy coding! 😊

**Comment by dayangkunurfaizah** [comment]
Hello Sir, here I am again. I want to ask some questions about this issue.

Let's say, on my roboflow task got,  
train set = 1802 images
valid set = 509 images
test set = 259 images

so the cropped images detected will be how many its saved into my google drive file? 259 images? is it following the test set?

**Comment by glenn-jocher** [comment]
Hello, the number of cropped images saved to your Google Drive will depend on the number of detected objects in your test set images, not the number of test images themselves. If each of your 259 test images has multiple detected objects, the total number of cropped images will be higher.

**Comment by dayangkunurfaizah** [comment]
Hello Sir. Thank you for your response. 

So, according to the question that I'm asking above. I've added 3 more augmentation methods (for example Flip: Horizontal, Vertical 90° Rotate: Clockwise, Counter-Clockwise, Upside Down Rotation: Between -45° and +45°) on roboflow. Then my train data increased to 3thousand+ images, valid data increased to 900+ images and test data increased to 400+ images. 

I've divided my dataset into 70% for train data, 20% for valid data, and 10% for test data. The augmentations method that I've used couldn't show a good result, while it getting worse. The result of train and valid detections as the picture below:

![Screenshot from 2024-09-07 17-00-46](https://github.com/user-attachments/assets/154b2e6b-e660-407f-ae35-7dc06dcadf73)

![Screenshot from 2024-09-07 17-04-58](https://github.com/user-attachments/assets/c6e99c59-8eac-426b-8050-889ff9b0b9a9)

What else method can I use for small datasets? Transfer learning method? Could you please help me? Thanks.

**Comment by glenn-jocher** [comment]
Thank you for reaching out. For small datasets, transfer learning can be highly effective. You can start with a pre-trained model and fine-tune it on your data. Additionally, consider experimenting with different augmentation techniques and hyperparameters to improve results. If the issue persists, ensure you're using the latest version of the Ultralytics package.

**Comment by dayangkunurfaizah** [comment]
Hello Sir. Its me, again. Could you please tell me how to convert this code whne using the pre-trained model of YOLOv8?

`!nvidia-smi

!pip install ultralytics==8.0.196

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="9J4r7wGQ2iahmrEqr5lp")
project = rf.workspace("dayangkunurfaizah92-gmail-com").project("benign-malignat-detection")
version = project.version(1)
dataset = version.download("yolov8")

!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs=20 imgsz=640

Image(filename=f'/content/runs/detect/train/confusion_matrix.png', width=600)

Image(filename=f'/content/runs/detect/train/results.png', width=600)

!yolo task=detect mode=val model=/content/runs/detect/train/weights/best.pt data={dataset.location}/data.yaml

!yolo task=detect mode=predict model=/content/runs/detect/train/weights/best.pt conf=0.5 source={dataset.location}/test/images save=True

import os
import cv2
import glob
from IPython.display import Image, display

# Create a directory to save cropped images
crop_dir_name = "cropped_images"
if not os.path.exists(crop_dir_name):
    os.mkdir(crop_dir_name)

# Load the model
model = YOLO("/content/runs/detect/train/weights/best.pt")

# Predict and crop objects
for image_path in glob.glob(f'{dataset.location}/test/images/*.jpg'):
    im0 = cv2.imread(image_path)
    results = model.predict(im0, conf=0.5)
    boxes = results[0].boxes.xyxy.cpu().tolist()
    clss = results[0].boxes.cls.cpu().tolist()

    for idx, (box, cls) in enumerate(zip(boxes, clss)):
        x1, y1, x2, y2 = map(int, box)
        crop_obj = im0[y1:y2, x1:x2]
        crop_obj_resized = cv2.resize(crop_obj, (256, 256))
        cv2.imwrite(os.path.join(crop_dir_name, f"{os.path.basename(image_path).split('.')[0]}_crop_{idx}.png"), crop_obj_resized)

# Display cropped images
for image_path in glob.glob(f'{crop_dir_name}/*.png'):
    display(Image(filename=image_path, width=256))
    print("\n")`

is this code run from scratch or a pre-trained model of YOLOv8? I have read so many questions and answers from here, that if the model=model.yaml is that train from scratch?

I want to use the model as a pre-trained model because the computational power is not enough (insufficient data)| to run all the dataset since I got a small dataset.

**Comment by glenn-jocher** [comment]
@dayangkunurfaizah to use a pre-trained YOLOv8 model, ensure you're loading the `.pt` file directly, like `model = YOLO('yolov8m.pt')`. This uses the pre-trained weights rather than training from scratch.

**Comment by dayangkunurfaizah** [comment]
where can I get the .pt file directly, Sir? Could you please show me?

**Comment by dayangkunurfaizah** [comment]
Hello Sir. Why my coding get error ?

_TypeError: unhashable type: 'numpy.ndarray'_

Before this, run all these codes ok, but today it's shown error numpy.ndarray. I did not change anything from this codes before.


`!nvidia-smi

import os
HOME = os.getcwd()
print(HOME)

# Pip install method (recommended)

!pip install ultralytics==8.0.196

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="9J4r7wGQ2iahmrEqr5lp")
project = rf.workspace("dayangkunurfaizah92-gmail-com").project("benign-malignat-detection")
version = project.version(11)
dataset = version.download("yolov8")

!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs=20 imgsz=640`

**Comment by dayangkunurfaizah** [comment]
Hello Sir. I found that the versions of YOLOv8.0.196 and YOLOv8.3.5 cannot run the coding at all. How to fix this, Sir? 

Thank you.

**Comment by Y-T-G** [comment]
@dayangkunurfaizah You should upgrade `ultralytics` to the latest version and restart the notebook after upgrade.

**Comment by dayangkunurfaizah** [comment]
> @dayangkunurfaizah You should upgrade `ultralytics` to the latest version and restart the notebook after upgrade.

hello sir.  I have upgraded ultralytics to the latest version and restarted it. Now I have problem in the line of

`!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs=20 imgsz=640`

The error is here:

```
Ultralytics 8.3.11 🚀 Python-3.10.12 torch-2.4.1+cu121 CUDA:0 (Tesla T4, 15102MiB)
engine/trainer: task=detect, mode=train, model=yolov8m.pt, data=/content/Benign-Malignat-Detection-4/data.yaml, epochs=20, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train2, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train2
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 557, in get_dataset
    data = check_det_dataset(self.args.data)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/utils.py", line 329, in check_det_dataset
    raise FileNotFoundError(m)
FileNotFoundError: 
Dataset '/content/Benign-Malignat-Detection-4/data.yaml' images not found ⚠️, missing path '/content/Benign-Malignant-Detection-4/Benign-Malignat-Detection-4/valid/images'
Note dataset download directory is '/content/datasets'. You can update this in '/root/.config/Ultralytics/settings.json'

```
How can I solve this?

**Comment by Y-T-G** [comment]
@dayangkunurfaizah You need add

`path: /content/Benign-Malignat-Detection-4` at the end of your `data.yaml` file

**Comment by dayangkunurfaizah** [comment]
> @dayangkunurfaizah You need add
> 
> `path: /content/Benign-Malignat-Detection-4`
> 
> at the end of your `data.yaml` file

I have add to this codes:

`data={dataset.location}/content/Benign-Malignat-Detection-4/data.yaml`

is this correct way?

**Comment by Y-T-G** [comment]
@dayangkunurfaizah No, you have to edit the `data>yaml` file and add what I posted.

**Comment by dayangkunurfaizah** [comment]
you that 
`
!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml path: /content/Benign-Malignat-Detection-4 epochs=20 imgsz=640` 

this code?

**Comment by dayangkunurfaizah** [comment]
> @dayangkunurfaizah No, you have to edit the `data.yaml` file and add what I posted.

you that

` !yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml path:/content/Benign-Malignat-Detection-4 epochs=20 imgsz=640`

this code?

**Comment by Y-T-G** [comment]
@dayangkunurfaizah Just run this in a cell:

`!echo "path: /content" >> /content/Benign-Malignat-Detection-4/data.yaml`

And then use the old command that you were using to start training:

`!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs=20 imgsz=640`

**Comment by dayangkunurfaizah** [comment]
hello sir. I have more questions to ask. I'm using yolov8 for my experiment, so the detected images using what set to predict the image? Is it using test set or valid set?

**Comment by Y-T-G** [comment]
@dayangkunurfaizah val set

**Comment by dayangkunurfaizah** [comment]
hello sir. i want to ask one more question regarding for this. i want crop my ground truth ROI image same as the result from detection using yolov8 val set and test set. could you please help me how can i crop my ground truth ROI image automatically? tq

**Comment by glenn-jocher** [comment]
You can crop ground truth ROI images by reading the annotation files (e.g., in YOLO format) and using the bounding box coordinates directly to extract ROIs from your images. This ensures the crops align with your ground truth. If the YOLOv8 detections differ from your ground truth, review your dataset annotations and training configurations for consistency. Let me know if you need further clarification!
