### ISSUE TITLE
segmentation fault(core dumped)

### ISSUE THREAD

**Issue by gysocool** [ultralytics/ultralytics#13037]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

<img width="651" alt="29D5994BF27EFBDC1F395AD03D5A1B2C" src="https://github.com/ultralytics/ultralytics/assets/67081852/a77da8bd-846e-4044-82f9-441b79ee6b46">

### Environment

Ultralytics YOLOv8.2.19 python-3.10.14 torch-2.3.0+cu118 CUDA:0 (NVIDIA A3 MIG 2g.12gb, 11968MiB)

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
It looks like you're encountering a segmentation fault, which could be related to memory issues or incompatible library versions. Here are a couple of steps you can try:

1. **Check GPU Memory**: Ensure that your GPU has enough memory available before running the model. You can monitor it using `nvidia-smi`.
2. **Update/Reinstall Libraries**: Sometimes, simply updating or reinstalling PyTorch and CUDA can resolve these issues. Make sure they are compatible with each other.

```bash
pip install torch==2.3.0+cu118 --upgrade
```

If the issue persists, please provide a minimal reproducible example, and I'll look into it further! Thanks for offering to help with a PR; that's greatly appreciated! 🚀
