### ISSUE TITLE
how to save and load my custom model

### ISSUE THREAD

**Issue by iyzyi** [ultralytics/ultralytics#13036]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In #10297, you point:

> After training, instead of using model.save('path/to/somefilename.pt'), simply use the .pt file that gets automatically saved in your runs directory (usually found under runs/train/exp*/weights/best.pt or last.pt for the last saved weights).
>
> To load your fine-tuned model with custom classes preserved, you can directly load this .pt file like so:
>
> model = YOLO('runs/train/exp*/weights/best.pt')
> This will load the model with all its configurations, including your custom classes as it uses the weights file which already contains information about the number of classes.
> 
> Regarding the error you encountered with loading using the YAML file and .pt weight, it typically occurs if there's a mismatch or if the YAML file does not accurately represent the model configuration used during the training. Hence, directly loading the saved .pt file is more straightforward for your use case.

But I wanna to know is there a way to save the custom model by python code instead of using best.pt, because we cannot get the abslute path of best.pt during a run time.

**Comment by Kayzwer** [comment]
model.save("/path") with doc

        Loads parameters from the specified weights file into the model.

        This method supports loading weights from a file or directly from a weights object. It matches parameters by
        name and shape and transfers them to the model.

        Args:
            weights (str | Path): Path to the weights file or a weights object. Defaults to 'yolov8n.pt'.

        Returns:
            self (ultralytics.engine.model.Model): The instance of the class with loaded weights.

        Raises:
            AssertionError: If the model is not a PyTorch model.

**Comment by iyzyi** [comment]
> `model.save("/path")` with doc
> 
> ```
>     Loads parameters from the specified weights file into the model.
> 
>     This method supports loading weights from a file or directly from a weights object. It matches parameters by
>     name and shape and transfers them to the model.
> 
>     Args:
>         weights (str | Path): Path to the weights file or a weights object. Defaults to 'yolov8n.pt'.
> 
>     Returns:
>         self (ultralytics.engine.model.Model): The instance of the class with loaded weights.
> 
>     Raises:
>         AssertionError: If the model is not a PyTorch model.
> ```

Thanks.
But my problem is the same as #10297, and I quote:

> I then export this as a PyTorch image using model.save('path/to/somefilename.pt'). So these weights are saved locally then.
>
> I then try to load the model with YOLO('path/to/somefilename.pt') and then I get a YOLO model, but it has all the default YOLO classes and not the custom one I used for training any more.
>
> Any idea how to export the model such that when I reload it, the classes are preserved?

**Comment by Kayzwer** [comment]
@iyzyi this should not happen, probably a bug, are you using the latest version of ultralytics?

**Comment by iyzyi** [comment]
@Kayzwer I'm using 8.2.18. 

However it happen even if i upgrade to 8.2.19.

`my code`:

```
from ultralytics import YOLO

yolo_model = 'model/yolov8n.pt'
custom_yaml = 'dataset/dataset.yaml'
custom_model = 'model/blue_focus.pt'

model = YOLO(yolo_model)
model.train(data=custom_yaml, epochs=3)
model.save(custom_model)
print('**********************saved**********************')

model = YOLO(custom_model)
model.val()
```

`custom yaml`:

```
path: my_path
train: images/train
val: images/val   
test: images/test

names:
  0: blue_focus
```

This code will output:

```
...... (some output) ...... 
Results saved to runs\detect\train14

**********************saved**********************

Dataset 'coco.yaml' images not found ⚠️, missing path 'C:\Users\xxxxx\AppData\Roaming\Ultralytics\datasets\coco\val2017.txt'
Downloading https://github.com/ultralytics/yolov5/releases/download/v1.0/coco2017labels-segments.zip to 'C:\Users\xxxxx\AppData\Roaming\Ultralytics\datasets\coco2017labels-segments.zip'...
100%|██████████| 169M/169M [01:46<00:00, 1.66MB/s]
Unzipping C:\Users\xxxxx\AppData\Roaming\Ultralytics\datasets\coco2017labels-segments.zip to C:\Users\xxxxx\AppData\Roaming\Ultralytics\datasets\coco...: 100%|██████████| 122232/122232 [01:10<00:00, 1727.47file/s]
Downloading http://images.cocodataset.org/zips/train2017.zip to 'C:\Users\xxxxx\AppData\Roaming\Ultralytics\datasets\coco\images\train2017.zip'...
Downloading http://images.cocodataset.org/zips/val2017.zip to 'C:\Users\xxxxx\AppData\Roaming\Ultralytics\datasets\coco\images\val2017.zip'...
Downloading http://images.cocodataset.org/zips/test2017.zip to 'C:\Users\xxxxx\AppData\Roaming\Ultralytics\datasets\coco\images\test2017.zip'...
```

I never use `coco.yaml`. It seemed that I get a YOLO model, but it has all the default YOLO classes and not the custom one I used for training any more. Just like #10297

Looking forward to your reply. Thanks!

**Comment by iyzyi** [comment]
I am sure my dataset is right because I can use bset.pt to do my custom predict.

**Comment by glenn-jocher** [comment]
Hello! It sounds like you're doing everything correctly with your dataset. If you're able to use `best.pt` for predictions successfully, your training process is likely fine. 

It seems there might be an issue with how the model is being saved or loaded. Ensure you're using the latest version of the Ultralytics library, as updates often fix such issues. If the problem persists, consider explicitly specifying the `data` argument when loading the model for validation to ensure it uses the correct dataset configuration:

```python
model = YOLO('path/to/
