### ISSUE TITLE
How cna I validate my model with no-square 【640*384(w*h)】image size?

### ISSUE THREAD

**Issue by 123456dad** [ultralytics/ultralytics#13049]

**Comment by glenn-jocher** [comment]
You can validate your model with a non-square image size by specifying the `imgsz` argument in the `val` command. Here's how you can do it for a 640x384 image size:

```bash
yolo val model=yolov8n.pt imgsz=640,384
```

This sets the width to 640 and the height to 384 for the validation process. Make sure your model has been trained with similar dimensions for best results!

**Comment by 123456dad** [comment]
But i get same problem like #11860， set imgsz=384，640 failed
