### ISSUE TITLE
Install ultralytics with pre-installed Pytorch

### ISSUE THREAD

**Issue by jaysontree** [ultralytics/ultralytics#13040]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a cuda11.8 enviroment with py3.8. The pytorch 2.1.2 with cu118 and torchvision is already installed and functioning well.
my environment should fulfill its requirements as py>=3.8 and pytorch>=1.8

but when i try installing ultralytics by `pip install ultralytics`,  it will download pytorch again and reinstall pytorch==2.3 with cuda12 which i suppose its the newest version by default. 
unfortunately, this cant work because my nvidia driver version is a bit old, not compatible with cuda12. 

after installing ultralytics, i have to manully uninstall torch and torchvision and then install back torch==2.1.2cu118, so that i can enjoy the mighty yolov8. But this is anoying especially when I want to build docker image.

Does anyone know how to avoid the reinstall of pytorch when installing ultralytics?
I know this is more like a package tool issue,
Please help! Thanks! 

### Additional

ps
Thanks for the great work from ultralyctis team.

**Comment by glenn-jocher** [comment]
Hello! Thanks for reaching out and for your kind words about our work. 😊

To avoid reinstalling PyTorch when you install `ultralytics`, you can use the `--no-deps` flag with pip to prevent it from installing any dependencies. This way, it won't attempt to overwrite your existing PyTorch installation. Here's how you can do it:

```bash
pip install ultralytics --no-deps
```

After running this command, you should manually ensure that all necessary dependencies other than PyTorch are installed. You can check the required packages in our `requirements.txt` file and install any missing ones individually.

Hope this helps! Let us know if you have any more questions.

**Comment by jaysontree** [comment]
> Hello! Thanks for reaching out and for your kind words about our work. 😊
> 
> To avoid reinstalling PyTorch when you install `ultralytics`, you can use the `--no-deps` flag with pip to prevent it from installing any dependencies. This way, it won't attempt to overwrite your existing PyTorch installation. Here's how you can do it:
> 
> ```shell
> pip install ultralytics --no-deps
> ```
> 
> After running this command, you should manually ensure that all necessary dependencies other than PyTorch are installed. You can check the required packages in our `requirements.txt` file and install any missing ones individually.
> 
> Hope this helps! Let us know if you have any more questions.

Thanks! It solves my problem perfectly! 😄

**Comment by jaysontree** [comment]
> Hello! Thanks for reaching out and for your kind words about our work. 😊
> 
> To avoid reinstalling PyTorch when you install `ultralytics`, you can use the `--no-deps` flag with pip to prevent it from installing any dependencies. This way, it won't attempt to overwrite your existing PyTorch installation. Here's how you can do it:
> 
> ```shell
> pip install ultralytics --no-deps
> ```
> 
> After running this command, you should manually ensure that all necessary dependencies other than PyTorch are installed. You can check the required packages in our `requirements.txt` file and install any missing ones individually.
> 
> Hope this helps! Let us know if you have any more questions.

Thanks! It solves my problem perfectly! 😄

**Comment by glenn-jocher** [comment]
You're very welcome! I'm glad to hear that it worked for you. 😄 If you have any more questions or need further assistance, feel free to reach out. Happy coding!
