### ISSUE TITLE
Yolov9 pytorch model is empty, as in not the folder, the loaded pytorch model. 

### ISSUE THREAD

**Issue by rlewkowicz** [ultralytics/ultralytics#13064]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

I'm using some other tool chains and I don't know what a "normal" pt object should be. Is model supposed to be populated? It exists and is populated in other tool chains. 
```
device = torch.device("cuda:0") 
model = torch.load("last.pt", map_location=device)  # Load FP32 weights
model["model"].float
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'float'
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Burhan-Q** [comment]
@rlewkowicz is `last.pt` in the working directory where this runs? After downloading a `yolo9c.pt` model (also checked with `yolov8n.pt`) into my working directory, I tested quickly with:

```py
import torch

device = torch.device("cuda:0")
model = torch.load("yolov9c.pt", map_location=device)

type(model["model"])
>>> <class 'ultralytics.nn.tasks.DetectionModel'>

model["model"].float()
>>> DetectionModel(
  (model): Sequential(
    (0): Conv(
    ...
```

Additionally, if `last.pt` hasn't completed training, the model isn't considered finalized, and so the `model` key of the dictionary will be `None`

**Comment by namdvt** [comment]
Try this
`(model.get("ema") or model["model"]).float()`

**Comment by glenn-jocher** [comment]
Thank you for the suggestion! 😊

Indeed, using `(model.get("ema") or model["model"]).float()` can help ensure you're accessing the correct model object, whether it's the Exponential Moving Average (EMA) model or the standard model. This approach is particularly useful if the EMA model is present.

If you continue to encounter issues, please ensure that your `last.pt` file is correctly saved and fully trained. Let us know if you need further assistance!
