### ISSUE TITLE
YOLOv8 with KAN

### ISSUE THREAD

**Issue by danielsyahputra** [ultralytics/ultralytics#13097]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi, everyone

I just do some experiments related integrated YOLOv8 and KAN (Kolmogorov Arnold Networks). So, basically, I was just trying to change the convolution that was used in YOLOv8 into Conv with KAN. For example, I made a new Conv block named `ConvWithKAN` that is basically replace `nn.Conv2d` into `ConvKAN` (Convolutional with KAN implementation).  As we know, `Conv` block in current implemetation is really crucial because it is used in many block such as `SPFF`, `C2f`, etc. So, I tried to make  new blocks named `C2fKAN` and `SPPFWithKAN` that are basically only change the `Conv` component that is used in these blocks into `ConvWithKAN` that I made before.

Now, you can custom your `yolov8.yaml` config by changing the name of the block that you want to used. 

You can see my work in this [Repository - https://github.com/danielsyahputra/ultralytics](https://github.com/danielsyahputra/ultralytics)

### Use case

The use case:

- Opens up the possibilities for integrating the YOLO technology with KAN (Kolmogorov Arnold Networks)

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi there! 👋

Great work on experimenting with integrating KAN into YOLOv8! It's exciting to see innovative approaches like yours that push the boundaries of what's possible with these models. Your custom `ConvWithKAN` block sounds like a promising development.

For those interested in trying out or contributing to this integration, check out the repository linked in your message. Contributions and further experimentation are always welcome!

If you have specific questions or need further assistance, feel free to ask. Keep up the fantastic work! 🚀

**Comment by tranleanh** [comment]
Yo bro ~

A KAN-based YOLO is what I am starting to work on. It's very nice to hear any new findings on this. I also visited your forked repo, nice work. I am staying tuned for your work.

Good luck,

LA Tran

**Comment by glenn-jocher** [comment]
@tranleanh hi LA Tran,

Thank you for your kind words and interest in integrating KAN with YOLOv8! It's fantastic to see the community exploring new frontiers like this. If you have any specific questions or run into any issues during your implementation, feel free to share them here. Providing a reproducible example can be very helpful for us to assist you better. You can find more details on creating one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Best of luck with your project, and we're excited to see what you come up with! 🚀
