### ISSUE TITLE
Syntax: how to only predict on several classes with the CLI

### ISSUE THREAD

**Issue by dmddmd** [ultralytics/ultralytics#1309]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I tried
`yolo detect predict model=yolov8n.pt classes=\46, 47, 49\, source="../images" save=True conf=0.25 device=\0,1,2,4
`
but got

> WARNING ⚠️ 'classes=46,' does not require trailing comma ',', updating to 'classes=46'.
> WARNING ⚠️ '47,' does not require trailing comma ',', updating to '47'.
> Traceback (most recent call last):
>   File "/home/miniconda3/bin/yolo", line 8, in <module>
>     sys.exit(entrypoint())
>   File "/home/miniconda3/lib/python3.10/site-packages/ultralytics/yolo/cfg/__init__.py", line 258, in entrypoint
>     check_cfg_mismatch(full_args_dict, {a: ''})
>   File "/home/miniconda3/lib/python3.10/site-packages/ultralytics/yolo/cfg/__init__.py", line 151, in check_cfg_mismatch
>     raise SyntaxError(string + CLI_HELP_MSG) from e
> SyntaxError: '47' is not a valid YOLO argument.

How can I pass the classes arg?

### Additional

ultralytics v 8.0.50

**Comment by glenn-jocher** [comment]
@dmddmd any list inputs can just be passed like this at the CLI (including classes and device for DDP):

```bash
yolo predict classes=0,1,2

WARNING ⚠️ 'model' is missing. Using default 'model=yolov8n.pt'.
WARNING ⚠️ 'source' is missing. Using default 'source=/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets'.
Ultralytics YOLOv8.0.51 🚀 Python-3.10.6 torch-1.13.1 CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

image 1/4 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus.jpg: 640x480 4 persons, 53.5ms
image 2/4 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus_4ch.png: 640x480 4 persons, 50.7ms
image 3/4 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus_greyscale.jpg: 640x480 3 persons, 48.3ms
image 4/4 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/zidane.jpg: 384x640 2 persons, 36.8ms
Speed: 0.4ms preprocess, 47.3ms inference, 2.2ms postprocess per image at shape (1, 3, 640, 640)
```

**Comment by glenn-jocher** [comment]
@dmddmd oh but also note that Multi-GPU is reserved for training only. Inference should just pass a single GPU argument, i.e. `yolo predict device=3`

**Comment by dmddmd** [comment]
thanks a lot!

**Comment by pderrenger** [comment]
You're welcome, @dmddmd! If you have any more questions or need further assistance, feel free to ask. Happy coding!
