### ISSUE TITLE
Will you support YOLOv10 in the future?

### ISSUE THREAD

**Issue by Lornatang** [ultralytics/ultralytics#13095]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have seen this article in [arxiv](https://arxiv.org/abs/2405.14458). I look forward to your reply~

**Comment by glenn-jocher** [comment]
Hello! Thanks for your interest in future YOLO versions. As of now, we don't have specific plans to support YOLOv10, but we continuously evaluate and consider integrating the latest advancements in our offerings. Keep an eye on our GitHub repository for any updates or announcements regarding new model support! 🚀

**Comment by wangqiqi** [comment]
Looking forward to it

**Comment by Lornatang** [comment]
If I have time, I will submit PR about YOLOV10 in this library

**Comment by glenn-jocher** [comment]
@Lornatang that sounds fantastic! We appreciate your willingness to contribute. Looking forward to your PR! 🌟 If you need any guidance, don't hesitate to reach out. Happy coding!
