### ISSUE TITLE
Please change this misleading tip

### ISSUE THREAD

**Issue by alsozatch** [ultralytics/ultralytics#13106]
On https://docs.ultralytics.com/integrations/tensorrt/#configuring-int8-export you say:

"Aim to use the minimum workspace value required as this prevents testing algorithms that require more workspace from being considered by the TensorRT builder. Setting a higher value for workspace may take considerably longer to calibrate and export."

The whole point of quantization is to spend a lot of time now in order to cut inference time costs later. To that end, you want to maximize the space allocated to allow for testing as many tactics as possible and to find the ones that offer the greatest speedup and the least accuracy loss. Minimizing the workspace results is a slower quantized model, a less accurate quantized model, or both.

Please specify these ramifications in your tip, so people understand that reducing the workspace size can get them something quicker but will give them a worse quality quantized model, and that in a production setting you should maximize the resources allocated for quantization.

**Comment by glenn-jocher** [comment]
@alsozatch thank you for your feedback on the TensorRT integration documentation. We appreciate your insights and agree that clarity is essential for users to make informed decisions about the `workspace` configuration during INT8 quantization.

We'll update the documentation to reflect the trade-offs between calibration time and model performance more clearly. Here's a revised version of the tip:

"Adjust the `workspace` value according to your calibration needs and resource availability. While a larger `workspace` may increase calibration time, it allows TensorRT to explore a wider range of optimization tactics, potentially enhancing model performance and accuracy. Conversely, a smaller `workspace` can reduce calibration time but may limit the optimization strategies, affecting the quality of the quantized model."

Thank you for helping us improve our documentation! 🚀

**Comment by glenn-jocher** [comment]
@alsozatch see https://github.com/ultralytics/ultralytics/pull/13138.

Please submit a PR directly in the future yourself if you spot room for improvement in the docs, thank you!
