### ISSUE TITLE
Tracking with 1 model and N multi-stream

### ISSUE THREAD

**Issue by abelBEDOYA** [ultralytics/ultralytics#13107]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I'm trying to inference some video feeds with just one model. The most efficient way to do so I've got with just one model is batch inference. That is, parsing a list of images (one for each video feed) and run: `model.predict([img1, img2, img3, ..., imgN])`.  However, I would like to do tracking: an independent tracking for each video feed. 

I've run `model.track([img1, img2, img3, ..., imgN], persist=True)`  and it behaves as if each image belong to a single sequential video feed. I would need that it takes a different tracker for each list of images index. How can it be done?

I would like to use BOT-SORT as tracker (it is the one that `yolo.track()` uses by default) which I've read it takes into account some features of the detected object in addition to bbox, IoU, ...

My code:

```
## More code.....
while True:
        frames = [capture.read()[1] for capture in captures]
        results = model.track(frames, persist=True, verbose=False)
## More code....
```

A similar issue was open but a practical answer wasn't given.
 
Thank you!

**Comment by abelBEDOYA** [comment]
Thanks for the response! It's a good option. I have tried it and, as you say, the detections and tracking are independent. However, if you pay attention to VRAM usage, it increases the same amount as it would do if you load several models. To be precise, the VRAM used memory increases approximately n_threads * single_model_size (my GPU memory only allows loading 10 models yolov8m doing this) . 

Is there a way to do so without loading several models in the VRAM?

At the end of the day they are necessary several trackers but just one model.

**Comment by glenn-jocher** [comment]
@abelBEDOYA you're right, using multiple model instances does increase VRAM usage significantly. Unfortunately, YOLOv8's current implementation doesn't support independent tracking for multiple streams with a single model instance.

A potential solution is to use a single model for inference and manage separate trackers manually. Here's a simplified example:

```python
from ultralytics import YOLO
import cv2

# Initialize model
model = YOLO('yolov8n.pt')

# Initialize video captures
captures = [cv2.VideoCapture(path) for path in video_paths]

# Initialize trackers
trackers = [YOLO('yolov8n.pt') for _ in captures]

while True:
    frames = [capture.read()[1] for capture in captures]
    results = model(frames)  # Single model inference

    for i, result in enumerate(results):
        trackers[i].track([result], persist=True)  # Independent tracking
        # Process tracker results

    # Display or further process results
```

This way, you only load the model once, but maintain separate trackers for each video feed. Hope this helps! 😊

**Comment by abelBEDOYA** [comment]
Looks good! But I've tried it and the method model.track() doesn't support: `[result]`, `result`, `result[0]`,... It is meant to receive a string path, a numpy array, camera direction, etc. The error:

![Screenshot from 2024-05-26 11-55-51](https://github.com/ultralytics/ultralytics/assets/89113493/a7f03208-d078-4ab8-a3bd-87c19b7e58a2)

Besides, as far as I know, BOT-Sort tracker takes into acount some image features of the detection and I suppose that if you only parse the detection result (bboxes) to do tracking with model.track(), it will rely on a "distances" or "IoU" criterion for matching detections from one frame to another, rather than using high-level features.

**Comment by glenn-jocher** [comment]
@abelBEDOYA thanks for pointing that out! You're correct that `model.track()` expects a path or image input. To handle multiple streams with a single model and independent trackers, you can manually manage the trackers. Here's a revised approach:

1. Perform inference with the model.
2. Update each tracker with the detection results.

Here's an example:

```python
from ultralytics import YOLO
import cv2

# Initialize model
model = YOLO('yolov8n.pt')

# Initialize video captures
captures = [cv2.VideoCapture(path) for path in video_paths]

# Initialize trackers
trackers = [YOLO('yolov8n.pt') for _ in captures]

while True:
    frames = [capture.read()[1] for capture in captures]
    results = model(frames)  # Single model inference

    for i, frame in enumerate(frames):
        trackers[i].track(frame, persist=True)  # Independent tracking
        # Process tracker results

    # Display or further process results
```

This way, you use a single model for inference and maintain independent trackers for each video feed. Let me know if this helps! 😊

**Comment by abelBEDOYA** [comment]
> @abelBEDOYA thanks for pointing that out! You're correct that `model.track()` expects a path or image input. To handle multiple streams with a single model and independent trackers, you can manually manage the trackers. Here's a revised approach:
> 
>     1. Perform inference with the model.
> 
>     2. Update each tracker with the detection results.
> 
> 
> Here's an example:
> 
> ```python
> from ultralytics import YOLO
> import cv2
> 
> # Initialize model
> model = YOLO('yolov8n.pt')
> 
> # Initialize video captures
> captures = [cv2.VideoCapture(path) for path in video_paths]
> 
> # Initialize trackers
> trackers = [YOLO('yolov8n.pt') for _ in captures]
> 
> while True:
>     frames = [capture.read()[1] for capture in captures]
>     results = model(frames)  # Single model inference
> 
>     for i, frame in enumerate(frames):
>         trackers[i].track(frame, persist=True)  # Independent tracking
>         # Process tracker results
> 
>     # Display or further process results
> ```
> 
> This way, you use a single model for inference and maintain independent trackers for each video feed. Let me know if this helps! 😊

As I said, doing so, they are loaded several models  in GPU memory, as many as capture objects or video feeds. It would be great to have just one model in GPU. How can it be done? I've seen some threading solutions but it is loaded a model in GPU for each thread and I run into the same memory problem...

**Comment by glenn-jocher** [comment]
Thank you for your feedback, @abelBEDOYA! You're right; the approach I suggested does indeed load multiple models into GPU memory, which isn't ideal for your use case.

To achieve independent tracking for each video feed while using only one model in GPU memory, you can manually manage the tracking logic. Here's a more refined approach:

1. Perform inference with the single model.
2. Use separate tracker instances for each video feed, but only load the model once.

Here's an example:

```python
from ultralytics import YOLO
import cv2
from collections import defaultdict

# Initialize model
model = YOLO('yolov8n.pt')

# Initialize video captures
captures = [cv2.VideoCapture(path) for path in video_paths]

# Initialize trackers
trackers = [defaultdict(lambda: None) for _ in captures]

while True:
    frames = [capture.read()[1] for capture in captures]
    results = model(frames)  # Single model inference

    for i, result in enumerate(results):
        # Extract detections for the current frame
        detections = result.boxes.xywh.cpu().numpy()
        confidences = result.boxes.conf.cpu().numpy()
        class_ids = result.boxes.cls.cpu().numpy()

        # Update the tracker for each video feed
        if trackers[i]['tracker'] is None:
            trackers[i]['tracker'] = YOLO('yolov8n.pt')  # Initialize tracker
        trackers[i]['tracker'].update(detections, confidences, class_ids)

        # Process tracker results
        # ...

    # Display or further process results
```

This way, you only load the model once into GPU memory and manage independent trackers for each video feed. Let me know if this helps! 😊
