### ISSUE TITLE
Unable to Export RTDETR Large Model(best.pt) to TFLite or NCNN for Raspberry Pi 4 Deployment

### ISSUE THREAD

**Issue by Youssef-100** [ultralytics/ultralytics#13111]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

I am encountering issues while attempting to export my trained RTDETR model (large variant) from Ultralytics to either TFLite or NCNN formats. My goal is to deploy this model on a Raspberry Pi 4 with 8GB of RAM for a road damage detection project. The dataset used for training includes two classes: pothole and crack.

Environment
Model: RTDETR Large
Custom Dataset: Road damage detection with 2 classes (pothole, crack)
Deployment Target: Raspberry Pi 4, 8GB RAM
Ultralytics Version: 8.2.19
TensorFlow Lite Version: TensorFlow Lite Version: 2.16.1
NCNN Version: NCNN Version: 1.0.20240410
Python Version: [3.11.2]

tflite export error:
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/home/youssef/project/project/lib/python3.11/site-packages/onnx2tf/utils/common_functions.py", line 288, in print_wrapper_func
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/youssef/project/project/lib/python3.11/site-packages/onnx2tf/utils/common_functions.py", line 361, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/youssef/project/project/lib/python3.11/site-packages/onnx2tf/ops/Conv.py", line 246, in make_node
    input_tensor = get_padding_as_op(
                   ^^^^^^^^^^^^^^^^^^
  File "/home/youssef/project/project/lib/python3.11/site-packages/onnx2tf/utils/common_functions.py", line 2009, in get_padding_as_op
    return tf.pad(x, padding)
           ^^^^^^^^^^^^^^^^^^
  File "/home/youssef/project/project/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/youssef/project/project/lib/python3.11/site-packages/keras/src/backend/common/keras_tensor.py", line 91, in __tf_tensor__
    raise ValueError(
ValueError: A KerasTensor cannot be used as input to a TensorFlow function. A KerasTensor is a symbolic placeholder for a shape and dtype, used when constructing Keras Functional models or Keras Functions. You can only use it as input to a Keras layer or a Keras operation (from the namespaces `keras.layers` and `keras.operations`). You are likely doing something like:

```
x = Input(...)
...
tf_fn(x)  # Invalid.
```
What you should do instead is wrap `tf_fn` in a layer:
```
class MyLayer(Layer):
    def call(self, x):
        return tf_fn(x)

x = MyLayer()(x)
```
ERROR: input_onnx_file_path: best.onnx
ERROR: onnx_op_name: /model.0/stem1/conv/Conv
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.

ncnn error:
Ultralytics YOLOv8.2.19 🚀 Python-3.11.2 torch-2.3.0 CPU (Cortex-A72)
rt-detr-l summary: 498 layers, 31987850 parameters, 0 gradients, 103.4 GFLOPs

PyTorch: starting from 'best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 6) (63.1 MB)

TorchScript: starting export with torch 2.3.0...
TorchScript: export success ✅ 54.9s, saved as 'best.torchscript' (122.8 MB)

NCNN: starting export with NCNN 1.0.20240410...
NCNN: running '/home/youssef/project/project/lib/python3.11/site-packages/ultralytics/pnnx best.torchscript ncnnparam=best_ncnn_model/model.ncnn.param ncnnbin=best_ncnn_model/model.ncnn.bin ncnnpy=best_ncnn_model/model_ncnn.py pnnxparam=best_ncnn_model/model.pnnx.param pnnxbin=best_ncnn_model/model.pnnx.bin pnnxpy=best_ncnn_model/model_pnnx.py pnnxonnx=best_ncnn_model/model.pnnx.onnx fp16=0 device=cpu inputshape="[1, 3, 640, 640]"'

NCNN: export failure ❌ 90.8s: Command '['/home/youssef/project/project/lib/python3.11/site-packages/ultralytics/pnnx', 'best.torchscript', 'ncnnparam=best_ncnn_model/model.ncnn.param', 'ncnnbin=best_ncnn_model/model.ncnn.bin', 'ncnnpy=best_ncnn_model/model_ncnn.py', 'pnnxparam=best_ncnn_model/model.pnnx.param', 'pnnxbin=best_ncnn_model/model.pnnx.bin', 'pnnxpy=best_ncnn_model/model_pnnx.py', 'pnnxonnx=best_ncnn_model/model.pnnx.onnx', 'fp16=0', 'device=cpu', 'inputshape="[1, 3, 640, 640]"']' died with <Signals.SIGABRT: 6>.
Traceback (most recent call last):
  File "/home/youssef/project/export.py", line 5, in <module>
    model.export(format='ncnn')
  File "/home/youssef/project/project/lib/python3.11/site-packages/ultralytics/engine/model.py", line 602, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/youssef/project/project/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/youssef/project/project/lib/python3.11/site-packages/ultralytics/engine/exporter.py", line 320, in __call__
    f[11], _ = self.export_ncnn()
               ^^^^^^^^^^^^^^^^^^
  File "/home/youssef/project/project/lib/python3.11/site-packages/ultralytics/engine/exporter.py", line 142, in outer_func
    raise e
  File "/home/youssef/project/project/lib/python3.11/site-packages/ultralytics/engine/exporter.py", line 137, in outer_func
    f, model = inner_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/youssef/project/project/lib/python3.11/site-packages/ultralytics/engine/exporter.py", line 588, in export_ncnn
    subprocess.run(cmd, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/youssef/project/project/lib/python3.11/site-packages/ultralytics/pnnx', 'best.torchscript', 'ncnnparam=best_ncnn_model/model.ncnn.param', 'ncnnbin=best_ncnn_model/model.ncnn.bin', 'ncnnpy=best_ncnn_model/model_ncnn.py', 'pnnxparam=best_ncnn_model/model.pnnx.param', 'pnnxbin=best_ncnn_model/model.pnnx.bin', 'pnnxpy=best_ncnn_model/model_pnnx.py', 'pnnxonnx=best_ncnn_model/model.pnnx.onnx', 'fp16=0', 'device=cpu', 'inputshape="[1, 3, 640, 640]"']' died with <Signals.SIGABRT: 6>.

I need to deploy the model on a Raspberry Pi 4, and the available formats (PyTorch) are not suitable for this lightweight device.
The documentation for exporting to TFLite and NCNN is followed as per Ultralytics guidelines.
If there are any specific configurations or steps required for these export processes, please provide detailed guidance.

Could you provide support or a workaround to successfully export the RTDETR large model to TFLite and NCNN formats? Any help or pointers would be greatly appreciated.

Thank you for your assistance!

### Environment

Ultralytics YOLOv8.2.19 🚀 Python-3.11.2 torch-2.3.0 CPU (Cortex-A72)
Setup complete ✅ (4 CPUs, 7.6 GB RAM, 15.8/58.2 GB disk)

### Minimal Reproducible Example

from ultralytics import RTDETR

model=RTDETR('best.pt')

model.export(format='tflite')

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! It looks like you're facing some challenges exporting the RTDETR large model to TFLite and NCNN formats for deployment on a Raspberry Pi 4. Exporting large models to these formats can indeed be tricky due to their complexity and the limitations of the target platforms.

For TFLite, the error you're encountering suggests there might be compatibility issues with certain operations in the model. One workaround could be to simplify the model or modify the layers that are causing the export issues. You can also try using the `simplify=True` option in the export function to see if it resolves the issue:

```python
model.export(format='tflite', simplify=True)
```

For NCNN, the error seems related to the subprocess handling within the export function. This could be due to resource limits or specific operations that NCNN does not support directly. Ensure that all required libraries are correctly installed and consider adjusting the `inputshape` or using the `fp16=1` option to reduce the model size:

```python
model.export(format='ncnn', fp16=1, inputshape="[1, 3, 320, 320]")
```

If these suggestions do not resolve the issues, I recommend checking for any updates or patches in the Ultralytics repository that might address these export challenges. Additionally, consulting the [Ultralytics TFLite integration guide](https://docs.ultralytics.com/integrations/tflite/) might provide further insights or alternative approaches.

Let me know if there's anything else I can help with!

**Comment by Youssef-100** [comment]
Hello! Thank you very much for your fast reply. Unfortunately the issue has not been resolved ,It shows the same error in both cases

**Comment by glenn-jocher** [comment]
Hi there! Sorry to hear the issue persists. Let's try a couple more things:

1. For TFLite, try using the `dynamic=True` option:
    ```python
    model.export(format='tflite', dynamic=True)
    ```

2. For NCNN, ensure all dependencies are up-to-date and try reducing the input size further:
    ```python
    model.export(format='ncnn', fp16=1, inputshape="[1, 3, 224, 224]")
    ```

If these don't work, please share more details or logs. We're here to help! 😊

**Comment by Youssef-100** [comment]
Hi Glenn! I am really sorry to bother you!
The NCNN shows the error below:
(force batch axis 233 for operand 241
force batch axis 233 for operand 242
binaryop tensor0 with rank 6 is not supported yet!
binaryop tensor1 with rank 6 is not supported yet!
binaryop tensor0 with rank 6 is not supported yet!
munmap_chunk(): invalid pointer
NCNN: export failure ❌ 62.9s
subprocess.CalledProcessError: Command '['/home/youssef/project/project/lib/python3.11/site-packages/ultralytics/pnnx', 'best.torchscript', 'ncnnparam=best_ncnn_model/model.ncnn.param', 'ncnnbin=best_ncnn_model/model.ncnn.bin', 'ncnnpy=best_ncnn_model/model_ncnn.py', 'pnnxparam=best_ncnn_model/model.pnnx.param', 'pnnxbin=best_ncnn_model/model.pnnx.bin', 'pnnxpy=best_ncnn_model/model_pnnx.py', 'pnnxonnx=best_ncnn_model/model.pnnx.onnx', 'fp16=1', 'device=cpu', 'inputshape="[1, 3, 224, 224]"']' died with <Signals.SIGABRT: 6>.)

While for the TFLITE ERROR:
ValueError: A KerasTensor cannot be used as input to a TensorFlow function. A KerasTensor is a symbolic placeholder for a shape and dtype, used when constructing Keras Functional models or Keras Functions. You can only use it as input to a Keras layer or a Keras operation (from the namespaces `keras.layers` and `keras.operations`). You are likely doing something like:
 input_onnx_file_path: best.onnx
ERROR: onnx_op_name: /model.0/stem1/conv/Conv
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.

Thank You so much for your help!

**Comment by glenn-jocher** [comment]
Hi there!

No bother at all! 😊 Thank you for providing the detailed error messages.

For the NCNN export issue, it seems like the model's tensor rank is causing problems. This might be due to the complexity of the RTDETR model. Unfortunately, NCNN might not fully support all operations used in this model.

For the TFLite export, the error suggests a problem with the ONNX to TensorFlow conversion. You might want to try the suggested parameter replacements or static shape rewrites as mentioned in the error message. Additionally, using the `-kt` or `-kat` options could help if the input OP has an irregular channel arrangement.

If these solutions don't work, consider simplifying the model or using a different model architecture that is known to be compatible with TFLite and NCNN.

Feel free to reach out if you need further assistance!
