### ISSUE TITLE
YOLO

### ISSUE THREAD

**Issue by microchila** [ultralytics/ultralytics#13118]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The YOLO V10 is so good, will different versions be developed in the future for different types of tasks? For example, segmentation.

**Comment by glenn-jocher** [comment]
Hello! Thanks for your interest in YOLO models! 🚀

As of now, YOLOv10 hasn't been officially released or discussed in our repository. However, for segmentation tasks, you might want to explore models like YOLOv9-seg which are specifically designed for instance segmentation. We continuously work on improving and adapting our models for various tasks, so keep an eye on our updates!

For any further questions or updates, feel free to check out our [GitHub repository](https://github.com/ultralytics/ultralytics). Happy coding!

**Comment by Fritskee** [comment]
@glenn-jocher any chance that yolo-v10 obb will be released in the future?

**Comment by glenn-jocher** [comment]
Hello! Thanks for your interest in YOLO models! 🚀

While we don't have specific details on the release of YOLOv10 with oriented bounding boxes (OBB) at the moment, we are always working on advancements and new features. Stay tuned for updates from the Ultralytics team and the YOLO community. Your enthusiasm and support are greatly appreciated!

**Comment by jurijsnazarovsambientai** [comment]
Could you clarify if yolo v10 is supported now in this repo, and if yes, can we run pose estimation on top of it?

**Comment by glenn-jocher** [comment]
Hello!

As of now, YOLOv10 is not supported in this repository. For pose estimation tasks, you might want to explore using YOLOv8, which includes support for pose/keypoint estimation. We appreciate your interest and encourage you to keep an eye on future updates for new model releases and features!

Thank you for reaching out! 🌟
