### ISSUE TITLE
Custom tracker weight

### ISSUE THREAD

**Issue by MaxwellFB** [ultralytics/ultralytics#13128]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Searching ByteTrack (https://github.com/ifzhang/ByteTrack) I saw that exists many model versions and it is possible to train using my own dataset, so I have the follow questions:
- What version of the ByteTrack model is being used by default in Ultralytics?
- How do I use my own custom ByteTrack weight in Ultralytics?

Thank you!!

**Comment by glenn-jocher** [comment]
Hi there! 😊

1. **ByteTrack Version**: Ultralytics uses the default ByteTrack configuration as specified in the `bytetrack.yaml` file.
2. **Custom ByteTrack Weights**: To use your custom ByteTrack weights, you can modify the `tracker` argument in your tracking command. Here's an example:

```python
from ultralytics import YOLO

# Load your custom model
model = YOLO('path/to/your/custom_model.pt')

# Use custom ByteTrack weights
results = model.track(source='path/to/your/video.mp4', tracker='path/to/your/custom_bytetrack.yaml')
```

Feel free to reach out if you have more questions! 🚀

**Comment by MaxwellFB** [comment]
Hi!
I tried to change .yaml to use a custom ByteTrack pth, but returned "AssertionError: Only 'bytetrack' and 'botsort' are supported for now, but got 'bytetrack_x_mot17.pth'". Looks like it is not possible by Ultralytics, I will do it manual. Thank you!

**Comment by glenn-jocher** [comment]
@MaxwellFB got it! Good luck with your implementation, and feel free to visit https://docs.ultralytics.com/modes/track/ for more information on tracking.
