### ISSUE TITLE
onnx detect

### ISSUE THREAD

**Issue by 2516455367** [ultralytics/ultralytics#13124]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Can you write a demo that uses go, python, and cpp to perform onnx target detection and target classification?

### Use case

Developers using python go cpp

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@2516455367 hello! Thanks for your willingness to contribute with a PR! Here's a simple demo outline for using a YOLOv8 ONNX model in Python, Go, and C++. For full examples, you might need to adapt the code based on your specific setup and environment.

### Python
```python
from ultralytics import YOLO

# Load the ONNX model
model = YOLO("yolov8n.onnx")

# Run inference
results = model("path/to/image.jpg")
print(results.pandas().xyxy[0])  # print predictions
```

### C++
You'll need to use an ONNX Runtime C++ API. Here's a very basic snippet:
```cpp
#include <onnxruntime_cxx_api.h>

int main() {
    Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test");
    Ort::SessionOptions session_options;
    session_options.SetIntraOpNumThreads(1);

    Ort::Session session(env, "yolov8n.onnx", session_options);

    // Add code to prepare input tensor and run session
    // Print outputs

    return 0;
}
```

### Go
For Go, you'll need a Go binding for ONNX Runtime. Here's a pseudo-code:
```go
package main

import (
    "github.com/owulveryck/onnx-go"
    "gonum.org/v1/gonum/mat"
)

func main() {
    backend := onnx.NewTensorRTBackend()
    model := onnx.NewModel(backend)
    
    // Load the model
    model.UnmarshalBinary("yolov8n.onnx")

    // Prepare input and run
    // Print the output
}
```

These are just starting points. You'll need to handle data preprocessing and output parsing according to the YOLOv8 model's requirements. Good luck with your PR! 🚀
