### ISSUE TITLE
Custom model cannot export onnx from pt file

### ISSUE THREAD

**Issue by thinker310** [ultralytics/ultralytics#13126]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I add a new moudule into YOLOv8 and trained it. The pretrained model was saved as a .pt file and I want to export it to .onnx file. But an IndexError happended as the picture showed below:
![image](https://github.com/ultralytics/ultralytics/assets/62609436/8f6fbf3d-b223-4c8f-9ebc-8aff2e87c675)
the convert code as follows:
from ultralytics import YOLO
model=YOLO('./best.pt')
model.export(format='onnx',opset=17)
Additionally, I tried many arguments (opset=17,16,15... or imgsz=[640,640]) for exporting but it didnot work. 
Could you help me? Thank you in advance!

**Comment by glenn-jocher** [comment]
Hi there! 😊

It looks like you're encountering an issue with exporting your custom YOLOv8 model to ONNX. The error might be related to the custom module you added. 

First, ensure your custom module is compatible with ONNX export. You might need to modify the module to support ONNX operations.

Here's a quick example to try:

```python
from ultralytics import YOLO

# Load your custom model
model = YOLO('./

**Comment by glenn-jocher** [comment]
Hi there! 👋

It looks like you're encountering an issue with exporting your custom YOLOv8 model to ONNX. The error might be related to the new module you added. Here's a quick suggestion to help you troubleshoot:

1. **Check the Custom Module**: Ensure that the custom module you added is compatible with ONNX export. Some PyTorch operations may not be supported by ONNX.

2. **Simplify the Export**: Try exporting without additional arguments first to see if the basic export works:
    ```python
    from ultralytics import YOLO

    model = YOLO('./best.pt')
    model.export(format='onnx')
    ```

3. **Debugging**: If the error persists, you might want to isolate the issue by removing the custom module temporarily and trying the export again.

If you continue to face issues, please share more details about the custom module or any specific operations it includes. This will help us provide more targeted assistance.

Good luck, and feel free to reach out if you need further help! 😊
