### ISSUE TITLE
Issue with model.export(format="tflite")

### ISSUE THREAD

**Issue by hamedgorji** [ultralytics/ultralytics#1312]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I trained my model successfully, and I could also export it as a `tflite` file. But when I want to use the following link to convert the `tflite` to `edgetpu` I get the following error. 
(I use Windows 10 which is why I cannot directly export my model as edgetpu)

[https://colab.research.google.com/github/google-coral/tutorials/blob/master/compile_for_edgetpu.ipynb](url)

```
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
ERROR: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
ERROR: Node number 11 (FlexSplitV) failed to prepare.

Compilation failed: Model failed in Tflite interpreter. Please ensure model can be loaded/run in Tflite interpreter.
Compilation child process completed within timeout period.
Compilation failed! 
```

The tflite exported files (`best_float32.tflite` and `best_float16.tflite`) are uploaded here:
[https://easyupload.io/m/55pzzr](url)

Here is what I get when I run `model.export(format="tflite")`

```
Ultralytics YOLOv8.0.51  Python-3.10.9 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24576MiB)

model = YOLO("runs/detect/train2/weights/best.pt")
model.export(format="tflite")
Ultralytics YOLOv8.0.51  Python-3.10.9 torch-1.13.1+cu117 CPU
YOLOv8n summary (fused): 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
PyTorch: starting from runs\detect\train2\weights\best.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 5, 8400) (5.9 MB)
TensorFlow SavedModel: starting export with tensorflow 2.11.0...
ONNX: starting export with onnx 1.12.0...
ONNX: simplifying with onnxsim 0.4.17...
ONNX: export success  0.9s, saved as runs\detect\train2\weights\best.onnx (11.6 MB)
TensorFlow SavedModel: running onnx2tf -i runs\detect\train2\weights\best.onnx -o runs\detect\train2\weights\best_saved_model -nuo --non_verbose 
WARNING:absl:Please consider providing the trackable_obj argument in the from_concrete_functions. Providing without the trackable_obj argument is deprecated and it will use the deprecated conversion path.
2023-03-07 15:13:22.540298: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
TensorFlow SavedModel: export success  8.9s, saved as runs\detect\train2\weights\best_saved_model (29.2 MB)
TensorFlow Lite: starting export with tensorflow 2.11.0...
TensorFlow Lite: export success  0.0s, saved as runs\detect\train2\weights\best_saved_model\best_float32.tflite (11.6 MB)
Export complete (9.2s)
Results saved to D:\Project\Codes\Yolo\yolov8\runs\detect\train2\weights
Predict:         yolo predict task=detect model=runs\detect\train2\weights\best_saved_model\best_float32.tflite imgsz=640 
Validate:        yolo val task=detect model=runs\detect\train2\weights\best_saved_model\best_float32.tflite imgsz=640 data=Data/data.yaml 
Visualize:       https://netron.app
Out[4]: 'runs\\detect\\train2\\weights\\best_saved_model\\best_float32.tflite'

```
I would appreciate it if you could help me to solve this issue.

**Comment by glenn-jocher** [comment]
@hamedgorji export directly to edgetpu, you don't need a 2 step process:

```python
model.export(format="edgetpu")
```

**Comment by hamedgorji** [comment]
> @hamedgorji export directly to edgetpu, you don't need a 2 step process:
> 
> ```python
> model.export(format="edgetpu")
> ```

I cannot. Because I use windows and it gives me the following error: 

```
Ultralytics YOLOv8.0.51  Python-3.10.9 torch-1.13.1+cu117 CPU
Traceback (most recent call last):
  File "C:\Users\Hamed\miniconda3\envs\yolov8\lib\site-packages\IPython\core\interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-15f06b77d0c6>", line 1, in <module>
    model.export(format="edgetpu")
  File "C:\Users\Hamed\miniconda3\envs\yolov8\lib\site-packages\ultralytics\yolo\engine\model.py", line 292, in export
    return Exporter(overrides=args)(model=self.model)
  File "C:\Users\Hamed\miniconda3\envs\yolov8\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Hamed\miniconda3\envs\yolov8\lib\site-packages\ultralytics\yolo\engine\exporter.py", line 178, in __call__
    raise SystemError('Edge TPU export only supported on Linux. See https://coral.ai/docs/edgetpu/compiler/')
SystemError: Edge TPU export only supported on Linux. See https://coral.ai/docs/edgetpu/compiler/
```

**Comment by glenn-jocher** [comment]
@hamedgorji oh ok, then try one of our environments below, they're all Linux:

## Environments

YOLOv8 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

 - **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/GCP-Quickstart)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/AWS-Quickstart)
- **Docker Image**. See [Docker Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

**Comment by hamedgorji** [comment]
> @hamedgorji oh ok, then try one of our environments below, they're all Linux (Colab is probably the easiest):
> ## Environments
> 
> YOLOv8 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):
> 
>     * **Notebooks** with free GPU: [![Run on Gradient](https://camo.githubusercontent.com/c9931a1689c37ab786edd3e1e5f59b9a6f7d097628c4689ce2432563ef884524/68747470733a2f2f6173736574732e706170657273706163652e696f2f696d672f6772616469656e742d62616467652e737667)](https://console.paperspace.com/github/ultralytics/ultralytics) [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/ultralytics/yolov8)
> 
>     * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/GCP-Quickstart)
> 
>     * **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/AWS-Quickstart)
> 
>     * **Docker Image**. See [Docker Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart) [![Docker Pulls](https://camo.githubusercontent.com/7401823bed1473d6db1ff60b933d51cd1534c448488f06c446c322227d31d966/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f756c7472616c79746963733f6c6f676f3d646f636b6572)](https://hub.docker.com/r/ultralytics/ultralytics)

Great. It solved my problem. Thank you so much.

**Comment by glenn-jocher** [comment]
You're welcome!

**Comment by hamedgorji** [comment]
Hi Glenn,
By using your suggestion I could successfully generate edgetpu format. But there is another issue and I would appreciate it if you could help me. 
Here is the log, and as can be seen, there are some problems `(More than one subgraph is not supported)`. That is why when I upload my model into the hardware it doesn't work.
I have searched a bit and found out it can be solved by adding `-a` in compiling command (`edgetpu_compiler -sa model.tflite`)
Source: [https://github.com/google-coral/edgetpu/issues/317](url)
Since I am using your environment to convert the format, may I ask you to add this to your compiling code to fix the problem?
Thank you.
```
Edge TPU Compiler version 16.0.384591198
Input: /content/drive/MyDrive/Yolo/best_saved_model/best_full_integer_quant.tflite
Output: /content/drive/MyDrive/Yolo/best_saved_model/best_full_integer_quant_edgetpu.tflite

Operator                       Count      Status

QUANTIZE                       1          More than one subgraph is not supported
QUANTIZE                       2          Mapped to Edge TPU
SUB                            2          More than one subgraph is not supported
LOGISTIC                       57         Mapped to Edge TPU
LOGISTIC                       1          More than one subgraph is not supported
MAX_POOL_2D                    3          Mapped to Edge TPU
TRANSPOSE                      4          Operation is otherwise supported, but not mapped due to some unspecified limitation
TRANSPOSE                      1          Mapped to Edge TPU
STRIDED_SLICE                  16         Mapped to Edge TPU
STRIDED_SLICE                  2          Operation is otherwise supported, but not mapped due to some unspecified limitation
STRIDED_SLICE                  2          More than one subgraph is not supported
CONCATENATION                  2          More than one subgraph is not supported
CONCATENATION                  1          Operation is otherwise supported, but not mapped due to some unspecified limitation
CONCATENATION                  16         Mapped to Edge TPU
RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
CONV_2D                        63         Mapped to Edge TPU
CONV_2D                        1          More than one subgraph is not supported
MUL                            57         Mapped to Edge TPU
MUL                            2          More than one subgraph is not supported
ADD                            6          Mapped to Edge TPU
ADD                            2          More than one subgraph is not supported
RESHAPE                        2          More than one subgraph is not supported
RESHAPE                        1          Mapped to Edge TPU
RESHAPE                        2          Operation is otherwise supported, but not mapped due to some unspecified limitation
SOFTMAX                        1          More than one subgraph is not supported
PAD     
```                       7          Mapped to Edge TPU

**Comment by glenn-jocher** [comment]
Yes, please submit a PR to update exporter.py with this change, thank you.

**Comment by thusinh1969** [comment]
Actually none of the tflite/edgetpu export work at all after exporting. Is there anyway to run from command line with the change that @hamedgorji suggested ?!?

**Comment by glenn-jocher** [comment]
@thusinh1969 incorrect. 

TFLite exports work, we test them every 24 hours and on every commit, and CI fails if they are not working correctly. You can see the latest benchmarking results anytime you want:

https://github.com/ultralytics/ultralytics/actions/runs/4421401533/jobs/7752155376
<img width="1304" alt="Screenshot 2023-03-15 at 13 16 31" src="https://user-images.githubusercontent.com/26833433/225306468-1f72b660-b160-4031-87bc-536892183fce.png">

**Comment by hamedgorji** [comment]
@glenn-jocher @thusinh1969 
Hi Glenn,
To my understanding, the benchmark shows that the model is exported successfully in edgetpu tflite format, while our problem is this model doesn't work when we want to use it for inference. Since last week I've been debugging my codes to figure out what could be the problem.  I believe the problem with the implementation of this model on coral edge TPU (I use `USB Accelerator`) is the nature of the yolov8 output format. Let me explain: 
Usually, when you want to use the model for coral TPU, the output should contain information about `scores`, `boxes`, `count`, and `class_ids`.
```
scores = common.output_tensor(interpreter, 0)[0]
boxes = common.output_tensor(interpreter, 1)[0]      
count = (int)(common.output_tensor(interpreter, 2)[0])
class_ids = common.output_tensor(interpreter, 3)[0]
```
You can find it in this directory: `coral\pycoral\pycoral\adapters\detect.py  (please take a look at lines 204 to 224)`
```
mkdir coral && cd coral
git clone https://github.com/google-coral/pycoral.git
```

While the converted yolov8 edgetpu file seems does not contain this information. 
I also attached the input and output information of two different models. One is our yolov8 model, and another is a model that works fine with the coral tpu. 
I would appreciate it if you could look at this information and help us to solve this issue. 
If we could find a way to extract information about `scores`, `boxes`, `count`, and `class_ids`, from the converted edgetpu model, the problem will be solved. 
[yolov8.txt](https://github.com/ultralytics/ultralytics/files/10983123/yolov8.txt)
[mobilenet_v2.txt](https://github.com/ultralytics/ultralytics/files/10983125/mobilenet_v2.txt)

**Comment by glenn-jocher** [comment]
@hamedgorji oh, you don't a 3rd party python script to run Edge TPU inference. You run Edge TPU inference directly using the `ultralytics` package:

```
from ultralytics import YOLO

model = YOLO('yolov8n_edge_tpu_model_here.tflite')
results = model(image)
```

**Comment by hamedgorji** [comment]
@glenn-jocher Thanks for your comment. I tried to use your suggestion. But it didn't work.

```
model = YOLO('best_saved_model/best_full_integer_quant_edgetpu.tflite', task='detect')
results = model('test_data/test.jpg',  save=True)

Loading best_saved_model\best_full_integer_quant_edgetpu.tflite for TensorFlow Lite Edge TPU inference...
Traceback (most recent call last):
  File "C:\Users\Hamed\miniconda3\envs\edgetpu\lib\site-packages\tensorflow\lite\python\interpreter.py", line 174, in load_delegate
    delegate = Delegate(library, options)
  File "C:\Users\Hamed\miniconda3\envs\edgetpu\lib\site-packages\tensorflow\lite\python\interpreter.py", line 112, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3.2\plugins\python-ce\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "C:\Users\Hamed\miniconda3\envs\edgetpu\lib\site-packages\ultralytics\yolo\engine\model.py", line 99, in __call__
    return self.predict(source, stream, **kwargs)
  File "C:\Users\Hamed\miniconda3\envs\edgetpu\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Hamed\miniconda3\envs\edgetpu\lib\site-packages\ultralytics\yolo\engine\model.py", line 218, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "C:\Users\Hamed\miniconda3\envs\edgetpu\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 227, in setup_model
    self.model = AutoBackend(model,
  File "C:\Users\Hamed\miniconda3\envs\edgetpu\lib\site-packages\ultralytics\nn\autobackend.py", line 221, in __init__
    interpreter = Interpreter(model_path=w, experimental_delegates=[load_delegate(delegate)])
  File "C:\Users\Hamed\miniconda3\envs\edgetpu\lib\site-packages\tensorflow\lite\python\interpreter.py", line 176, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from edgetpu.dll
```
I also need to mention that some models work using your suggested way to run inference`(best_dynamic_range_quant.tflite, best_float16.tflite, best_float32.tflite, best_full_integer_quant.tflite, best_integer_quant.tflite, best_integer_quant_with_int16_act.tflite)`, but they are not edgetpu models `(best_full_integer_quant_edgetpu.tflite)`.

**Comment by glenn-jocher** [comment]
@hamedgorji we don't have Edge TPU hardware ourselves, so we can't assist in debugging Edge TPU inference, but I can point you to the code. If you can debug the problem in our Edge TPU inference code here please submit a PR to help other users.

Edge TPU model loading:
https://github.com/ultralytics/ultralytics/blob/701fba47700dee7a6bd8ff4d219eca91adc9d3be/ultralytics/nn/autobackend.py#L209-L232

Edge TPU inference:
https://github.com/ultralytics/ultralytics/blob/701fba47700dee7a6bd8ff4d219eca91adc9d3be/ultralytics/nn/autobackend.py#L365-L385

**Comment by hamedgorji** [comment]
@glenn-jocher Sure, I will work on it to figure our what the issue can be.

**Comment by kubikub** [comment]
> @glenn-jocher Sure, I will work on it to figure our what the issue can be.

Hello @glenn-jocher  did you figure out the problem, I got the same issue on my project.

**Comment by glenn-jocher** [comment]
@faisalhazry the error message that you have shared suggests that there might be some issues with the conversion of a PyTorch YOLOv8 model to a TensorFlow Lite file format using `onnx2tf` and `TFLiteConverter`. Specifically, it mentions an error relating to the `MaxPool` function and difficulty in inferring the type of a tensor. 

It is difficult to provide a specific solution without more information on the model architecture, input data, and conversion script. However, there are a few things you could try. Firstly, you could verify that the model and input data are correct and that there are no syntax or other errors when you run the conversion script. Secondly, you could try different conversion scripts or tools, such as `MMdnn`, to convert the PyTorch model to TensorFlow Lite. Lastly, you could check if there are any issues with the installed packages you are using and try to update or reinstall them.

**Comment by Klinefelters** [comment]
> @glenn-jocher Sure, I will work on it to figure our what the issue can be.

Hey, I seem to be exploring this issue as well, could I ask if you have made any progress?

**Comment by glenn-jocher** [comment]
@Klinefelters hi, please check the latest updates in the repository and documentation for any improvements or solutions related to your issue.
