### ISSUE TITLE
classification .pt to onnx predict error

### ISSUE THREAD

**Issue by centurions** [ultralytics/ultralytics#13123]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hello
I have trained yolov8x-cls on custom data with this script

from ultralytics import YOLO

# Load a model
model = YOLO("yolov8x-cls.pt")  # load a pretrained model (recommended for training)

# Train the model
results = model.train(data="./data", epochs=20, imgsz=416, workers=0 , batch=32)

best.pt works well but when I convert it to onnx with this command:

yolo export model=best.pt format=onnx imgsz=416

I get an error in prediction : yolo predict model=best.onnx source=1.jpg imgsz=416

Traceback (most recent call last):
  File "C:\finalall\ok\convert.py", line 6, in <module>
    model.predict(imgsz=416)
  File "C:\finalall\torchcpu\lib\site-packages\ultralytics\engine\model.py", line 453, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "C:\finalall\torchcpu\lib\site-packages\ultralytics\engine\predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "C:\finalall\torchcpu\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\finalall\torchcpu\lib\site-packages\ultralytics\engine\predictor.py", line 255, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "C:\finalall\torchcpu\lib\site-packages\ultralytics\models\yolo\detect\predict.py", line 25, in postprocess
    preds = ops.non_max_suppression(
  File "C:\finalall\torchcpu\lib\site-packages\ultralytics\utils\ops.py", line 230, in non_max_suppression
    prediction[..., :4] = xywh2xyxy(prediction[..., :4])  # xywh to xyxy
  File "C:\finalall\torchcpu\lib\site-packages\ultralytics\utils\ops.py", line 413, in xywh2xyxy
    assert x.shape[-1] == 4, f"input shape last dimension expected 4 but input shape is {x.shape}"
AssertionError: input shape last dimension expected 4 but input shape is torch.Size([7, 1])

### Environment

Ultralytics YOLOv8.2.21 🚀 Python-3.9.13 torch-2.3.0+cpu CPU (Intel Core(TM) i7-4720HQ 2.60GHz)
Setup complete ✅ (8 CPUs, 15.9 GB RAM, 313.6/341.2 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.9.13
Install             pip
RAM                 15.93 GB
CPU                 Intel Core(TM) i7-4720HQ 2.60GHz
CUDA                None

matplotlib          ✅ 3.9.0>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.2>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.3.0>=1.8.0
torchvision         ✅ 0.18.0>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@centurions hello! It looks like the issue you're encountering during prediction with the ONNX model might be related to the output tensor dimensions expected by the post-processing function. The error suggests that the output tensor shape does not match the expected shape, which is causing the assertion error.

A potential solution is to verify the output shapes of your ONNX model to ensure they match what the YOLOv8 framework expects for classification tasks. You can use tools like Netron to visualize the ONNX model and check the output dimensions.

If the dimensions are indeed different, you might need to adjust the export settings or modify the post-processing code to handle the shape returned by your ONNX model. Here's a quick way to check the output shape using ONNX:

```python
import onnx
import onnxruntime as ort

# Load your model
onnx_model = onnx.load("best.onnx")
onnx.checker.check_model(onnx_model)

# Create a session and get the output
ort_session = ort.InferenceSession("best.onnx")
outputs = ort_session.run(None, {'input': your_input_tensor})
print('Output shape:', outputs[0].shape)
```

Adjust `your_input_tensor` to match the input size your model expects. This snippet will help you confirm if the output dimensions are as expected.

If you continue to experience issues, please provide more details about the output shapes, and we can explore further adjustments!

**Comment by glenn-jocher** [comment]
Hello @centurions,

Thank you for your patience. The issue seems to be consistent across multiple export formats, indicating it might be related to the output tensor dimensions expected by the post-processing function.

To troubleshoot further, I recommend checking the output shapes of your exported models. You can use tools like Netron to visualize the model and ensure the output dimensions match what YOLOv8 expects for classification tasks.

Additionally, you can inspect the output shapes using the following code snippet for ONNX:

```python
import onnx
import onnxruntime as ort

# Load your model
onnx_model = onnx.load("best.onnx")
onnx.checker.check_model(onnx_model)

# Create a session and get the output
ort_session = ort.InferenceSession("best.onnx")
outputs = ort_session.run(None, {'input': your_input_tensor})
print('Output shape:', outputs[0].shape)
```

Replace `your_input_tensor` with the appropriate input tensor for your model. This will help confirm if the output dimensions are as expected.

If the issue persists, please share the output shapes, and we can explore further adjustments. Feel free to reach out if you need more assistance! 😊

**Comment by Burhan-Q** [comment]
@centurions perhaps you could try downgrading your `torch` install? I've seen other users having some issues with `torch==2.3.0` and I was able to successful export and run inference using some of the standard assets.

![image](https://github.com/ultralytics/ultralytics/assets/62214284/04a14aad-52de-4147-a723-0d5518d8f7a6)
