### ISSUE TITLE
Training slow with large training imgsz

### ISSUE THREAD

**Issue by fuqianya** [ultralytics/ultralytics#13121]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hi,

We found that when training with large imgsz (e.g., 3000) using DDP  (e.g., 8xA100), the training is very slow. And the time is spend almostly on the data preprocessing. Any solutions to speed up the data preprocessing? 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by fuqianya** [comment]
Thanks a lot. This works for me. But why the first card consumes larger memory than other cards

<img width="293" alt="image" src="https://github.com/ultralytics/ultralytics/assets/45023083/e706e019-d659-4a99-882b-d5d99b9e1786">

**Comment by glenn-jocher** [comment]
Glad to hear it worked! The first GPU often handles additional tasks like data loading and coordination, which can lead to higher memory usage. This is typical in multi-GPU setups. If you have any more questions, feel free to ask! 😊
