### ISSUE TITLE
YOLOv8 Pose estimation - Adjust label size

### ISSUE THREAD

**Issue by WLi0777** [ultralytics/ultralytics#13131]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! I am trying to use trained model to predict new videos, how do I adjust the size of the dots? Thanks!!

```
    while cap.isOpened():

        success, frame = cap.read()
        if success:
            results = model(frame)
            annotated_frame = results[0].plot(font_size=1)
            out.write(annotated_frame)
        else:
            break

    cap.release()
```

**Comment by WLi0777** [comment]
Found it: 
```
kpt_radius (int, optional): Radius of the drawn keypoints. Default is 5.
```

**Comment by glenn-jocher** [comment]
@WLi0777 hi! Glad you found the `kpt_radius` parameter. You can adjust the size of the dots by setting it in the `plot` method. Here's how you can do it:

```python
while cap.isOpened():
    success, frame = cap.read()
    if success:
        results = model(frame)
        annotated_frame = results[0].plot(kpt_radius=10)  # Adjust the radius as needed
        out.write(annotated_frame)
    else:
        break

cap.release()
```

Happy coding! 😊
