### ISSUE TITLE
RuntimeError: invalid shape when training YOLOWorld on MixedGrounding Dataset

### ISSUE THREAD

**Issue by CJBuzz** [ultralytics/ultralytics#13147]
When trying to finetune my YOLOWorld model on a MixedGrounding Dataset, I encountered the following error:

RuntimeError: shape '[32, 71, -1]' is invalid for input of size 29491200

This occured when I used the .train() method on the initialised YOLOWorld model class. Tracing the error, it led to the file ultralytics\utils\loss.py at line 204. I'm using the latest ultralytics version 8.2.22.

`model = YOLOWorld("yolov8l-worldv2.pt")`
`model.train(data={
                    "train": {
                        "grounding_data": [{
                            "img_path": "./datasets/train_ds/images/",
                            "json_file":"./datasets/train_ds/yoloworld_mixedgrounding.json"
                        }]
                        },
                    "val": {
                        "yolo_data": ["./datasets/train_ds/finetuning.yaml"]
                        }
                  },
            batch=32, epochs=1, trainer=WorldTrainerFromScratch, device=0)`
            
This code is based on what is provided in the ultralytics docs for finetuning YOLOWorld models.

**Comment by CJBuzz** [comment]
Hi, thanks for the reply! I have adopted the above steps but the issue remains unresolved. However, I have can provide more details of the error.

The error seems to come from this line `pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split((self.reg_max * 4, self.nc), 1)`. When printing feats[0].size(), it returns a tensor of shape (32, 144, 80, 80). 

I also noticed that when I replaced the `grounding_data` argument with the same `finetuning.yaml` file, the training seems to work. Here, printing out feats[0].size() results in a tensor of shape (32, 71, 80, 80). This ‘71’ may correspond to the ‘71’ present in runtime error.

Looking more closely at `ultralytics/utils/loss.py`, I noticed that ‘71’ came as a result of `self.no` which was initialised as `self.no = m.nc + m.reg_max * 4` in line 161. Printing out `m.nc` and `m.reg_max` yields 7 and 16 respectively. The 7 might be due to the 7 classes present in finetuning.yaml.

I have tried a lower batch size to no avail. I have also tried using `pip install -U ultralytics`, but the error persists.

Attached is the error traceback.
![traceback2](https://github.com/ultralytics/ultralytics/assets/120005745/33c72817-ada3-4708-951d-d559b459f1ba)
![traceback1](https://github.com/ultralytics/ultralytics/assets/120005745/30e7830b-eec7-417b-a3f5-8e4aea56d916)

**Comment by glenn-jocher** [comment]
Hi,

Thank you for the detailed follow-up and for providing additional information. It’s very helpful! 😊

From your observations, it seems the issue might be related to the `grounding_data` configuration. The difference in tensor shapes when using `grounding_data` versus `finetuning.yaml` suggests a potential mismatch in the expected number of classes or the structure of the dataset.

Here are a few additional steps to try:

1. **Verify Class Consistency**: Ensure that the number of classes (`nc`) in your `grounding_data` matches the number of classes in `finetuning.yaml`. Any discrepancy here can lead to shape mismatches.

2. **Inspect `grounding_data`**: Double-check the `yoloworld_mixedgrounding.json` file for any inconsistencies or errors in the annotations. Make sure the format aligns with what the model expects.

3. **Debugging Shapes**: Add print statements to log the shapes of tensors at various points in the `loss.py` file. This can help pinpoint where the shape mismatch occurs.

4. **Model Configuration**: Ensure that the model configuration aligns with the dataset. Sometimes, custom datasets require specific adjustments in the model’s configuration.

If the issue persists, please consider sharing a minimal reproducible example or more details about the `grounding_data` setup. This will help us provide more targeted assistance.

Thank you for your patience and cooperation. Let’s get this resolved! 🚀

**Comment by CJBuzz** [comment]
Hello. Thanks for the reply. I have made further headway into the issue I faced. 

I have double checked class consistency and realised that for a mixed-grounding dataset, only validation data with 80 classes (number of classes in coco dataset) seem to lead to no error as it would result in a tensor of shape (32, 144, 80, 80) for `feats[0].size()`. Any other number would seem to result in a shape mismatch. This becomes a problem as my `finetuning.yaml` file only had 7 classes. Does this mean that when training on mixed-grounding datasets, the only available validation data are datasets with 80 fixed classes? Would that also mean that if I am fine-tuning my model with a mixed-grounding dataset for a specific use case, I am unable to use a more representative validation set with fewer classes?

I am also providing a small sample of the mixed grounding dataset, as well as the training code. To replicate my original error, replace `coco128.yaml` in the validation part of the `data` dictionary with the `.yaml` file to another dataset with a number of classes that isn't 80. 

Thanks! 

Attached below are 2 zip files. `mre.zip` contains 1 image of the mixed-grounding dataset and its corresponding annotations. `mre python script.zip` contains the training script.
[mre.zip](https://github.com/ultralytics/ultralytics/files/15462374/mre.zip)
[mre python script.zip](https://github.com/ultralytics/ultralytics/files/15462382/mre.python.script.zip)

**Comment by glenn-jocher** [comment]
Hello,

Thank you for the detailed update and for sharing the sample dataset and training script. Your observations are indeed correct. When working with mixed-grounding datasets, the validation data must align with the expected number of classes, which in this case is 80 (as per the COCO dataset). This ensures that the tensor shapes match correctly during training.

To address your concerns:
- **Validation Data with 80 Classes**: Yes, for mixed-grounding datasets, the validation data should have 80 classes to avoid shape mismatches.
- **Fine-Tuning with Fewer Classes**: If you are fine-tuning for a specific use case with fewer classes, you might need to adjust the dataset or the model configuration to ensure compatibility.

We appreciate your patience and the provided materials. We will review the sample dataset and script to further investigate and provide a more tailored solution.

Thank you for your cooperation! 😊

**Comment by CJBuzz** [comment]
Thanks so much for the help! I would indeed appreciate if I am able to use a mixed-grounding dataset for validation in future, instead of being constrained to use a fixed-classes dataset with strictly 80 classes.

**Comment by glenn-jocher** [comment]
@CJBuzz you're welcome! 😊 We understand the importance of flexibility in using mixed-grounding datasets for validation. We'll take your feedback into consideration for future updates to enhance support for diverse class configurations. If you have any more questions or need further assistance, feel free to reach out. Happy training! 🚀

**Comment by Daniel595** [comment]
Hello, 
I got the same Error when training Yolov8-seg and wanted to share the source of my problem.
For Detection training I'm providing a `CustomTrainer` inheriting `DetectionTrainer`. 
Using this `CustomTrainer` for seg training I get the above Error. Inheriting from `SegmentationTrainer` fixed it of course. 
Maybe it helps someone :)

**Comment by glenn-jocher** [comment]
Hello,

Thank you for sharing your experience and solution! It's great to hear that inheriting from `SegmentationTrainer` resolved the issue for your segmentation training. This is indeed valuable information for anyone encountering similar problems. 😊

For those who might be facing the same error, it's crucial to ensure that the appropriate trainer class is being used for the specific task. Here's a quick summary of the correct inheritance for different tasks:

- **Detection Training**:
  ```python
  from ultralytics.models.yolo.detect import DetectionTrainer

  class CustomTrainer(DetectionTrainer):
      ...
  ```

- **Segmentation Training**:
  ```python
  from ultralytics.models.yolo.segment import SegmentationTrainer

  class CustomTrainerSeg(SegmentationTrainer):
      ...
  ```

If anyone continues to experience issues, please ensure you are using the latest versions of `torch` and `ultralytics`. You can update your packages with the following commands:
```bash
pip install --upgrade torch ultralytics
```

Additionally, if you encounter any further errors, providing a minimum reproducible example will greatly assist us in diagnosing and resolving the issue. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Thank you again for your contribution to the community! If you have any more questions or need further assistance, feel free to reach out.

Happy training! 🚀

**Comment by xiexie007** [comment]
hello, has this problem fixed? 
as i see, the number 80 is not the coco class number. it's the parameter max_samples set in randomloadtext augment.  
if not with this augment, the text length is varied  among different image annotations. so the augment help to fix the text length as 80, maybe sutable for batch inference in training. 
 however，nc of the model is set as the class number of validation dataset, maybe not 80. so it encounters error when inference as shape is not consistent.

**Comment by glenn-jocher** [comment]
Hello, thank you for your insights. The issue you're describing relates to the `randomloadtext` augmentation setting a fixed text length, which can cause shape mismatches if `nc` doesn't align with the validation dataset's class count. Adjusting the augmentation or ensuring class consistency should help resolve this. If you have further questions, feel free to ask!

**Comment by ddz16** [comment]
By changing the `max_samples` parameter of `RandomLoadText` in the `build_transforms` function of the `ultralytics.data.dataset.GroundingDataset` class to the number of categories in my own dataset, I solved this issue. See the figure below:
![image](https://github.com/user-attachments/assets/0e284f84-93d0-4c83-9c6f-58271864131f)

**Comment by glenn-jocher** [comment]
Thank you for sharing your solution. Adjusting the `max_samples` parameter to match your dataset's categories is a great approach to resolving the issue. If you have any more questions, feel free to ask!
