### ISSUE TITLE
How to predict image with original size?

### ISSUE THREAD

**Issue by xiaolinyezi** [ultralytics/ultralytics#1314]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In training phase, we used set the imgsz=1536 to train the yolov8. However, actually, the original image size is 1920*1080? How to predict image with orginal size instead of the training size?

**Comment by totoadel** [comment]
@xiaolinyezi i think you just add imgsz=[1920,1080]   try this
