### ISSUE TITLE
What file is required for classification classes weights?

### ISSUE THREAD

**Issue by haimat** [ultralytics/ultralytics#13141]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have created a training folder for an image classification task. Within I have three sub folders, `train`, `val`, `test`, and within those I have sub folders named after the image classes. When I now call `train(data=<path_to_training_folder)`, then I get this error message from YOLOv8:

> Found no valid file for the classes weights. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp

What is this classes weights file, where to save it and what content does it need?

**Comment by glenn-jocher** [comment]
@haimat hello,

Thank you for reaching out! It sounds like you've set up your dataset structure correctly for image classification. The error message you're encountering suggests that YOLOv8 is not finding any valid image files within your specified directories.

To resolve this, please ensure the following:
1. **File Extensions**: Verify that your image files have one of the supported extensions: `.jpg`, `.jpeg`, `.png`, `.ppm`, `.bmp`, `.pgm`, `.tif`, `.tiff`, or `.webp`.
2. **Directory Structure**: Double-check that your `train`, `val`, and `test` directories contain subdirectories named after your classes, and that these subdirectories contain the image files.

Here's a quick example of the expected directory structure:
```
dataset/
|-- train/
|   |-- class1/
|   |   |-- image1.jpg
|   |   |-- image2.png
|   |-- class2/
|       |-- image1.jpg
|       |-- image2.png
|-- val/
|   |-- class1/
|   |   |-- image1.jpg
|   |   |-- image2.png
|   |-- class2/
|       |-- image1.jpg
|       |-- image2.png
|-- test/
|   |-- class1/
|   |   |-- image1.jpg
|   |   |-- image2.png
|   |-- class2/
|       |-- image1.jpg
|       |-- image2.png
```

If your structure and file extensions are correct, the training command should work without issues:
```bash
yolo classify train data=path/to/dataset
```

For more detailed guidance on setting up your dataset, you can refer to the [Ultralytics documentation](https://docs.ultralytics.com/datasets/classify/).

If you continue to experience issues, please feel free to share more details, and we'll be happy to assist further! 😊

**Comment by haimat** [comment]
Moving the discussion to https://github.com/ultralytics/ultralytics/issues/8837

**Comment by glenn-jocher** [comment]
@haimat, thank you for the update! I'll follow the discussion over on issue #8837 and provide further assistance there. 😊

**Comment by haimat** [comment]
> @haimat, thank you for the update! I'll follow the discussion over on issue #8837 and provide further assistance there. 😊

Thanks - I am looking forward to your reply on the `nc` issue.

**Comment by glenn-jocher** [comment]
@haimat, I'm on it! I'll review the details regarding the `nc` issue and respond shortly on issue #8837. Thanks for your patience! 🚀
