### ISSUE TITLE
guides/object-counting/

### ISSUE THREAD

**Issue by RedWojak** [ultralytics/ultralytics#13156]
Hello! I was planning to creat a counter that separates stream of people that chose certain path in the street. Is there a way to have 3 or more regions and check in what order objects cross those regions? It also would be useful for a case to determine what pecentage of cars took a certain turn et.c. Any best practice on how to do this efficiently ?

**Comment by glenn-jocher** [comment]
Hello!

Absolutely, you can create a counter to track the order in which objects cross multiple regions using Ultralytics YOLOv8. You can define three or more regions and monitor the sequence in which objects pass through them. This can be particularly useful for analyzing pedestrian paths or vehicle turns.

For best practices:
1. **Define Regions Clearly**: Ensure each region is well-defined and non-overlapping to avoid ambiguity.
2. **Track Object IDs**: Use object tracking to maintain consistent IDs for objects across frames.
3. **Log Crossings**: Maintain a log of the order in which each object crosses the regions.
4. **Analyze Patterns**: Post-process the logs to determine patterns and percentages.

You can start by cloning the Ultralytics repository and using the `yolov8_region_counter.py` script. This script allows you to define and move regions interactively during video playback. For more detailed guidance, check out our [Object Counting in Regions Guide](https://docs.ultralytics.com/guides/region-counting/) 📘.

Feel free to reach out if you have any more questions! 🚀
