### ISSUE TITLE
How to not automatically download and train models

### ISSUE THREAD

**Issue by starsky68** [ultralytics/ultralytics#1315]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to not automatically download and train models？After the download in yaml is deleted, it is still downloaded by default. Do you need to add False?

**Comment by glenn-jocher** [comment]
@starsky68 please provide a minimum reproducible example of the problem you are encountering.

Assets like datsets and models are only downloaded **if you request them** and they are not already present locally.
