### ISSUE TITLE
code issue 

### ISSUE THREAD

**Issue by bhaveshbohra** [ultralytics/ultralytics#13155]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

issue to load this module 
""from torchvision.models.utils import load_state_dict_from_url""

error message 
No module named 'torchvision.models.utils'

**Comment by glenn-jocher** [comment]
Hi there,

It looks like the `torchvision.models.utils` module has been deprecated. You can replace it with `torch.hub.load_state_dict_from_url` to resolve this issue. Here's a quick example:

```python
from torch.hub import load_state_dict_from_url
```

If you continue to experience issues, please ensure you have the latest versions of `torch` and `torchvision` installed. You can update them using:

```bash
pip install --upgrade torch torchvision
```

Feel free to reach out if you have any more questions! 😊
