### ISSUE TITLE
YOLOv10 branch doesn't exist in newer ultralytics versions

### ISSUE THREAD

**Issue by ChilledFerrum** [ultralytics/ultralytics#13168]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Install, Train, Val, Predict, Other

### Bug

YOLOv10 branch doesn't exist in ultralytic's latest update '8.2.23'... but exists in the ultralytics version '8.1.34' where YOLOv10 was built

No error in version 8.1.34
Please replicate and fix, thank you.

### Environment

Ultralytics version '8.2.23' and YOLOv10 repository

### Minimal Reproducible Example

```
from ultralytics import YOLOv10
```
Error in version 8.2.23:
``ImportError: cannot import name 'YOLOv10' from 'ultralytics' ``

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello,

Thank you for bringing this to our attention. The YOLOv10 branch is indeed experimental and may not be available in the latest stable release. To access YOLOv10, please ensure you are using the correct version where it was initially introduced, such as '8.1.34'.

If you need further assistance or have any more questions, feel free to ask. We appreciate your understanding and support! 😊

**Comment by ChilledFerrum** [comment]
> Hello,
> 
> Thank you for bringing this to our attention. The YOLOv10 branch is indeed experimental and may not be available in the latest stable release. To access YOLOv10, please ensure you are using the correct version where it was initially introduced, such as '8.1.34'.
> 
> If you need further assistance or have any more questions, feel free to ask. We appreciate your understanding and support! 😊

Hello Glen, thank you for clarifying.
Hope to see it on the main branch in the future.

**Comment by glenn-jocher** [comment]
Hello,

Thank you for your understanding, Glen. We're continuously working on improvements and hope to integrate YOLOv10 into the main branch soon. If you have any more questions or need further assistance, feel free to reach out. 😊

**Comment by RATHOD-SHUBHAM** [comment]
To solve the issue I did this:
1. git clone https://github.com/THU-MIG/yolov10.git
2. cd yolov10
3. pip install .

Now try:
from ultralytics import  YOLOv10

also, I had previously installed 
* pip install huggingface huggingface_hub, in case the huggingface_hub error comes up

**Comment by glenn-jocher** [comment]
@RATHOD-SHUBHAM hello,

Thank you for sharing your solution! It's great to see community members actively helping each other and contributing valuable insights. Your detailed steps will surely assist others facing similar issues. If there are any more questions or further assistance needed, feel free to reach out. Happy coding! 😊
