### ISSUE TITLE
'dict' object has no attribute 'project'

### ISSUE THREAD

**Issue by xinsuinizhuan** [ultralytics/ultralytics#1317]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I want to val my model, then i run the xxx\ultralytics-main\ultralytics\yolo\v8\detect\val.py, i also change the xxx\ultralytics-main\ultralytics\yolo\cfg\default.yaml, then i break,as follow:
Traceback (most recent call last):
  File "xxx/ultralytics-main/ultralytics/yolo/v8/detect/val.py", line 251, in <module>
    val()
  File "xxx/ultralytics-main/ultralytics/yolo/v8/detect/val.py", line 246, in val
    validator = DetectionValidator(args=args)
  File "xxx/ultralytics-main/ultralytics/yolo/v8/detect/val.py", line 22, in __init__
    super().__init__(dataloader, save_dir, pbar, args)
  File "xxx\ultralytics-main\ultralytics\yolo\engine\validator.py", line 79, in __init__
    project = self.args.project or Path(SETTINGS['runs_dir']) / self.args.task
AttributeError: 'dict' object has no attribute 'project'

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@xinsuinizhuan for val suage examples see https://docs.ultralytics.com/tasks/detection/#val

**Comment by Jayne-Shane** [comment]
I had the same problem too.

**Comment by Laughing-q** [comment]
@xinsuinizhuan @KonxYin @Jayne-Shane hey guys, it would be really helpful if you could provide the command or script you used, then we're able to reproduce the your error. :)

**Comment by Jayne-Shane** [comment]
@Laughing-q Hello, there is a problem with validation in this release: [ultralytics-main.zip](https://github.com/ultralytics/ultralytics/files/10940440/ultralytics-main.zip)

**Comment by Laughing-q** [comment]
@Jayne-Shane well it works correctly to me:
![image](https://user-images.githubusercontent.com/61612323/224276285-296f4f7f-810e-4b25-b9cd-4a4f7523e979.png)

**Comment by Jayne-Shane** [comment]
@Laughing-q Thanks for your example. I was able to run it successfully on python. The above problems occur when run on pycharm, but not on the python compiler. If conditions permit, it is recommended that you try pycharm. However, I think the problem has been solved. Thank you for your help.

**Comment by Miichael-tan** [comment]
> 

thkx a lot, your solutoin helps !!
