### ISSUE TITLE
NCHW vs NHWC

### ISSUE THREAD

**Issue by johnnynunez** [ultralytics/ultralytics#13179]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Source: https://docs.nvidia.com/deeplearning/performance/dl-performance-convolutional/index.html#tensor-layout
Convolutions typically operate on four-dimensional tensors: a batch composed of N "images" of C channels of H x W feature maps.

Deep learning frameworks commonly use NCHW and NHWC layouts in memory (the acronym lists the dimensions from the slowest to the fastest varying in memory). Layout choice has an effect on performance, as convolutions implemented for Tensor Cores require NHWC layout and are fastest when input tensors are laid out in NHWC.

Note:
NCHW layouts can still be operated on by Tensor Cores, but include some overhead due to automatic transpose operations, as shown in [Figure 2](https://docs.nvidia.com/deeplearning/performance/dl-performance-convolutional/index.html#tensor-layout__fig18). Transpose overhead tends to be more significant when input and output tensors are larger or the amount of calculation required is lower (such as when filter sizes are smaller). To maximize performance, we recommend using the NHWC tensor layout.

Why?
he Tensor Cores in NVIDIA GPUs are optimized to work with data in the “channels last” format (i.e., NHWC), rather than the “channels first” format (NCHW), due to how they are designed to access and process memory. Here is a detailed explanation of why the NHWC format is preferred:

Memory Access Optimization

	1.	Memory Coalescing: Tensor Cores are designed to maximize coalesced memory access, meaning multiple threads in a warp can access memory in patterns that minimize scattered accesses and maximize effective bandwidth. In the NHWC format, data from different channels at the same spatial position (H, W) are together in memory, facilitating this coalesced access.
	2.	Memory Layout: The NHWC layout places channels as the fastest-access dimension (the last in the list), which is more natural for the sequential accesses that Tensor Cores perform. This results in better cache utilization and less overhead in data reorganization during computations.

Kernel Execution and Vectorized Operations

	3.	Computational Efficiency: In convolution operations, it is common for data to be accessed in blocks corresponding to contiguous regions of the image. With the NHWC format, these blocks can be processed more efficiently by Tensor Cores, which are designed for highly parallelized, matrix-intensive operations.
	4.	Compatibility with High-Performance Algorithms: Many high-performance libraries and frameworks, such as NVIDIA’s cuDNN, are optimized for the NHWC format due to these memory access and execution advantages. Using the NHWC format allows direct leverage of these optimizations.

Hardware Physics

	5.	Hardware Design: The physical design of Tensor Cores and the arrangement of registers and processing units within the GPU are made to work more efficiently with data that has the channel dimension last. This reduces latency and improves the overall throughput of operations.

Format Examples

	•	NCHW (Channels First):
	•	Order: (N, C, H, W)
	•	Data stored in memory: first all samples of all channels of the first spatial position (H, W), then the next spatial position, and so on.
	•	NHWC (Channels Last):
	•	Order: (N, H, W, C)
	•	Data stored in memory: first all samples of the first spatial position (H, W) for all channels, then the next spatial position, and so on.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@johnnynunez thank you for your detailed explanation on NCHW vs NHWC tensor layouts and their impact on performance, especially in the context of NVIDIA Tensor Cores. Your insights on memory access optimization, kernel execution, and hardware design are very valuable.

Currently, Ultralytics YOLO models primarily use the NCHW format, which is widely supported across various deep learning frameworks. However, we are always looking to improve performance and efficiency. Your suggestion to consider NHWC for better optimization with Tensor Cores is noted and appreciated.

If you have any further questions or need assistance, feel free to ask. We're here to help! 😊

**Comment by Burhan-Q** [comment]
@johnnynunez I've tested this out some with our PyTorch models, and did not notice any appreciable benefit in putting channels first. Have you had any success in using channel-first layout that showed any performance improvements?

**Comment by johnnynunez** [comment]
> @johnnynunez I've tested this out some with our PyTorch models, and did not notice any appreciable benefit in putting channels first. Have you had any success in using channel-first layout that showed any performance improvements?

It is only when it is used in tensor engine format.
If you look with nsight you can see that exists a recurrent conversion kernel that take some time. This kernel exists to make compatible model operations with tensor cores. Tensor cores are very special

**Comment by glenn-jocher** [comment]
Thank you for the insight, @johnnynunez! 😊

It's great to know that the performance benefits of the NHWC format become evident when using Tensor Cores. The recurrent conversion kernel you mentioned highlights the importance of optimizing tensor layouts for specific hardware capabilities. We'll certainly consider this in our ongoing performance evaluations.

If you have any further observations or need assistance, feel free to share. Your contributions are highly valued!
