### ISSUE TITLE
Does the Augmentation Settings process corrects labels?

### ISSUE THREAD

**Issue by dreambit** [ultralytics/ultralytics#13172]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Does the Augmentation Settings process change labels as well together with an image? Especially degrees, translate, perspective. For yolov8-obb model.

Thanks

**Comment by glenn-jocher** [comment]
@dreambit hello,

Yes, the augmentation settings in YOLOv8 do adjust the labels to match the transformations applied to the images. This includes operations like rotation (degrees), translation, and perspective changes. This ensures that the bounding boxes or keypoints remain accurate and aligned with the augmented images, including for the YOLOv8-OBB model.

If you have any more questions or need further clarification, feel free to ask! 😊

**Comment by dreambit** [comment]
@glenn-jocher Thank you so much. Is it possible to see how my dataset looks when these transformations are applied during the training?

**Comment by glenn-jocher** [comment]
@dreambit Absolutely! You can visualize how your dataset looks with transformations applied by enabling the `--show` flag during training or using the `--save-conf` option to save images with transformations to disk. This will allow you to see the augmented images and their corresponding labels directly, helping you verify the accuracy of the transformations and annotations. If you need more detailed steps or additional help, just let me know! 😊

**Comment by dreambit** [comment]
@glenn-jocher Thanks. I am not sure i understand, if i have a dataset of 100 images, and i set mosaic to 1, how many images will be used for training? 100 but each will be a set of 4 images cut? and for example if i set translate to 0.1. Thanks

**Comment by glenn-jocher** [comment]
@dreambit Great questions!

When you set `mosaic=1`, all 100 images in your dataset can potentially be used for training. Each training image will be a composite of 4 randomly selected images from your dataset, pieced together in a mosaic pattern. This effectively increases the diversity of training scenarios for the model.

For the `translate=0.1` setting, each image (including those in mosaics) will be randomly shifted horizontally and vertically by up to 10% of the image's width and height. This helps the model learn to recognize objects that are partially out of frame or shifted.

If you have more questions or need further clarification, feel free to ask! 😊

**Comment by dreambit** [comment]
@glenn-jocher To make it more clear :) Could you choose with one is correct :))

Dataset: 100 images

Example 1: mosaic=1, all other augmentation settings are = 0

1. Outcome 1: The final dataset will contain **100** images where each image will be a composite of 4 randomly selected images
2. Outcome 2: The final dataset will contain **200** images where first 100 images will be a composite of 4 randomly selected images, other 100 is original images


Example 2: mosaic=0, translate=0.5, degree=90, fliphr=0.5
1. Outcome 1: The final dataset will contain **100** images with all applied transformations
2. Outcome 2: The final dataset will contain **400** images, 100 original, 100 with translate transformation, 100 with defree transformation, 100 with fliphr transformation

Thank you
