### ISSUE TITLE
how to save the count output in a folder

### ISSUE THREAD

**Issue by shahbazahmed108** [ultralytics/ultralytics#13183]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello All,
I am running yolov8 in cmd and when I run the predict command, the count of objects detected in an image is displayed in the cmd too as an output (image attached, the count output is in line 5 ). how could I save this count output in the prediction folder? 
![Screenshot 2024-05-28 151502](https://github.com/ultralytics/ultralytics/assets/57543325/2dceb33b-9860-469f-9589-664f619eed13)
thank you for the help

**Comment by glenn-jocher** [comment]
Hello,

Thank you for your question! To save the count output in a folder, you can modify the script to write the count to a file after each prediction. Here's a simple way to do it:

1. **Modify the `predict` function**: Add code to save the count to a text file in the prediction folder.

Here's an example modification in Python:

```python
from ultralytics import YOLO

# Load the model
model = YOLO('yolov8n.pt')

# Run prediction
results = model.predict(source='path/to/your/image.jpg')

# Extract the count of detected objects
count = len(results[0].boxes)

# Save the count to a file
with open('path/to/prediction_folder/count.txt', 'w') as f:
    f.write(f'Count: {count}\n')
```

2. **Run the modified script**: Use the command line to execute your modified script.

```bash
python your_modified_script.py
```

This will save the count of detected objects to a `count.txt` file in the specified prediction folder. If you need further customization or assistance, feel free to ask!

Happy coding! 🚀
