### ISSUE TITLE
How many layers is the backbone in the segmentation model of YoloV8?

### ISSUE THREAD

**Issue by nachoogriis** [ultralytics/ultralytics#13180]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am working in a person segmentation problem with a personal dataset. To obtain good results I want to do some fine-tuning. As the amount of data I have is not extremely high, I would want to perform fine-tuning while freezing some layers.

For freezing, I was considering to freeze the backbone, while fine-tuning the heads. My questions are:

1. Which has to be the value of the `freeze` parameter in training in order to freeze the backbone of the model? The `freeze` parameter freezes the first $N$ layers.

2. Is there any better place to place the freezing. This is, which might be a good value for the `freeze` parameter?

**Comment by glenn-jocher** [comment]
@nachoogriis hello,

Thank you for your question! The backbone in the YOLOv8 segmentation model consists of 12 layers. To freeze the backbone during fine-tuning, you can set the `freeze` parameter to 12. This will freeze the first 12 layers, allowing you to fine-tune the head layers.

Here's an example of how to set the `freeze` parameter:

```bash
yolo segment train data=your_dataset.yaml model=yolov8n-seg.pt epochs=100 freeze=12
```

Freezing the backbone while fine-tuning the head layers is a common approach, especially when working with a limited amount of data. It helps in retaining the learned features from the backbone while adapting the head layers to your specific dataset.

If you have any further questions or need additional assistance, feel free to ask. Happy training! 🚀

**Comment by glenn-jocher** [comment]
Hello @nachoogriis,

Thank you for reaching out with your query. It seems there might be a misunderstanding in how the model initialization is handled in your code.

When you specify `pretrained=False`, it should indeed initialize the model with random weights rather than loading pretrained weights. If you're observing that the results are the same in both cases, it's possible that the model is not correctly recognizing the `pretrained` flag due to how the model is instantiated.

To ensure that the model starts with random weights, you might want to explicitly load a model configuration file (YAML) rather than a pre-trained model file (PT). Here’s how you can modify your code:

```python
model = YOLO('path/to/model.yaml')  # Ensure this is a YAML file, not a PT file

model.train(data=config_file_path, epochs=150, patience=50, imgsz=640, pretrained=False, name="YOLO random weights base hyps")
```

This approach ensures that the model is initialized as defined in the YAML configuration, without loading any pretrained weights. Please try this and let me know if it resolves the issue!

**Comment by BhanuPrasadCh** [comment]
Hello @glenn-jocher, 

I'm working with the [YOLOv8x-seg](yolov8x-seg.pt) trained for a building footprints segmentation task for my study area and am currently setting up transfer learning for a different region. I want to freeze the entire backbone during training and have set freeze=12 in my training configuration. This freezes the first 12 layers, but I'm unsure if this includes all layers in the backbone.

Could someone clarify:
1. How many layers are there in the backbone of the YOLOv8 segmentation model?
2. What is the correct freeze value I should use to freeze the entire backbone during training?
3. Which sections (backbone, neck, head) do the frozen layers belong to when using freeze=12?

Additionally, I have the following questions regarding transfer learning: 
4. Should I freeze only the backbone layers, or should I also consider freezing the neck layers for transfer learning? (What is the correct freeze value I should use to freeze the entire backbone+neck during training?)
5. How does freezing the backbone versus freezing both the backbone and neck layers impact model accuracies?

Ideally, I'm more interested in increasing the Recall.

Any guidance on these points would be greatly appreciated!
Thanks in advance!!
![Model_Parameters](https://github.com/user-attachments/assets/e862271b-f579-43a3-8cbf-934123d45637)
![Frozen Parameters](https://github.com/user-attachments/assets/ce2b7b11-8258-4bbf-a5e0-6248dceaf616)

**Comment by glenn-jocher** [comment]
Hello @BhanuPrasadCh,

The YOLOv8 segmentation model's backbone consists of 12 layers. Setting `freeze=12` will indeed freeze the entire backbone. To freeze both the backbone and neck, you should set `freeze=18`. Freezing the backbone helps retain learned features, while freezing both backbone and neck can further stabilize training but may limit adaptability. For increasing Recall, focus on fine-tuning the head layers after freezing the backbone.
