### ISSUE TITLE
Can't export model with 8.2.24

### ISSUE THREAD

**Issue by MatC91** [ultralytics/ultralytics#13181]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hi , i type in the commande to export the model with the last version but it still run 8.2.22 version
![yolo](https://github.com/ultralytics/ultralytics/assets/169962353/e1923928-376e-40d8-bb9f-c2f2eb12c29d)
I do the upgrade ...
![yolo 2](https://github.com/ultralytics/ultralytics/assets/169962353/92705e95-8503-4c65-8f5f-2d58a595945a)
But Still run the 8.2.22
![yolo3](https://github.com/ultralytics/ultralytics/assets/169962353/94268ab0-330e-4eb6-b0e6-5d2e5191cdb6)
Some one can help me plz ? :/

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Burhan-Q** [comment]
@MatC91 a bit difficult to know how to help without an example, but I just tested an ONNX export and it's working.
![image](https://github.com/ultralytics/ultralytics/assets/62214284/d1b7873f-fc2c-4f94-b776-f2b0644b5cbf)

You can also view if all our CI tests are passing (which includes export tests) on [this docs page](https://docs.ultralytics.com/help/CI/#ci-results).

Also, you should **always** use a python virtual environment when installing packages and make sure it's active for each project environment. Without doing so, you'll find that managing packages will be quite difficult and cumbersome. [This is a good reference](https://www.dataquest.io/blog/a-complete-guide-to-python-virtual-environments/) if you need one.

**Comment by MatC91** [comment]
@Burhan-Q Thank you for you help :) They say i have Cuda 12.1 but i got the 12.5 (maybe its because of this) and this is the command i use yolo export model="models/matc.1.3.pt" format=engine device=0 imgsz=640 half=True workspace=6

**Comment by Burhan-Q** [comment]
Don't worry about the CUDA versions. The driver CUDA version and the software CUDA version is cross compatible. I still recommend downgrading to a PyTorch 2.2 version, but if you're also attempting to export to a TensorRT `engine` model, you'll need to make sure you have TensorRT installed.

**Comment by MatC91** [comment]
@Burhan-Q  Yes i have the TensorRt 10.0.1 , every thing work fine can make new model and run yolo with no issue but it still run in the 8.2.22
