### ISSUE TITLE
Add resnet18 classification model

### ISSUE THREAD

**Issue by Lornatang** [ultralytics/ultralytics#13198]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Can you support a model definition method and model weight of the ResNet18? Thank you so much!

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! Thank you for your interest in contributing to the Ultralytics project with a ResNet18 classification model. We appreciate your willingness to submit a PR.

Before you start, please ensure that your implementation aligns with our existing model architecture standards and coding practices. It would be great if you could also provide documentation and tests for your model to ensure its integration and performance consistency.

Once you're ready, please submit your PR, and we'll review it promptly. If you have any questions or need further guidance, feel free to ask. We're excited to see your contribution!

Thank you for supporting the Ultralytics community! 🚀

**Comment by Lornatang** [comment]
#13258 
This is the PR of this Issue, which has been submitted

**Comment by glenn-jocher** [comment]
@Lornatang hello! Thank you for submitting the PR for issue #13258. We'll review it soon and provide feedback or merge it if everything checks out. Your contribution is greatly appreciated! 🌟
