### ISSUE TITLE
YoloV8 results have no 'box', 'max' properties in it

### ISSUE THREAD

**Issue by paulohss** [ultralytics/ultralytics#13192]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

ve trained a YOLOV8 model to identify objects in an intersection (ie cars, roads etc). It is working OK and I can get the output as an image with the objects of interested segmented.

However, what I need to do is to capture the raw geometries (polygons) so I can save them on a txt file later on.

I tried what Ive found in the documentation (https://docs.ultralytics.com/modes/predict/#key-features-of-predict-mode) however the returning object is not the same as the documentation says.

Here's my code:

```
import argparse
import cv2
import numpy as np
from pathlib import Path
from ultralytics.yolo.engine.model import YOLO    
    
# Parse command line arguments
parser = argparse.ArgumentParser()
parser.add_argument('--source', type=str, required=True, help='Source image directory or file')
parser.add_argument('--output', type=str, default='output', help='Output directory')
args = parser.parse_args()

# Create output directory if it doesn't exist
Path(args.output).mkdir(parents=True, exist_ok=True)

# Model path
model_path = r'C:\\_Projects\\best_100img.pt'

# Load your model directly
model = YOLO(model_path)
model.fuse()

# Load image(s)
if Path(args.source).is_dir():
    image_paths = list(Path(args.source).rglob('*.tiff'))
else:
    image_paths = [args.source]

# Process each image
for image_path in image_paths:
    img = cv2.imread(str(image_path))
    if img is None:
        continue

    # Perform inference
    predictions = model.predict(image_path, save=True, save_txt=True)
    
print("Processing complete.")
```
Here's the problem: the return object (predictions variable) has no boxes, masks, keypoints and etc.
In fact, the result is a list of tensorflow numbers: https://i.sstatic.net/Fy4lI1sV.png

I guess my questions are:

Why the result is so different from the documentation?
Is there a conversion step?

**Comment by glenn-jocher** [comment]
Hello,

Thank you for reaching out and providing detailed information about your issue. It seems like there might be a misunderstanding or a mismatch between the expected output format and what is being returned by the model.

From your description, it appears that you are expecting to access attributes such as `boxes`, `masks`, and `keypoints` directly from the `predictions` object. However, these attributes are part of the `Results` object that the YOLO model returns when using the `predict()` method correctly.

Please ensure that you are processing the `Results` object to extract these attributes. Here's a quick example of how you might access these properties:

```python
results = model.predict(img)  # Assuming img is your preprocessed image tensor
for result in results:
    boxes = result.boxes.xyxy  # Access bounding box coordinates
    # Process boxes or save to txt as needed
```

Make sure that your image input to the `predict()` method is correctly preprocessed if necessary, and that you are using the latest version of the Ultralytics YOLO library, as updates might affect functionality.

If the issue persists, please provide more details about the output you are currently receiving and any error messages. This will help in diagnosing the problem more effectively.

**Comment by paulohss** [comment]
Hi @glenn-jocher glenn-jocher,
thanks for the reply,

As described in my message, there was no misconception. I've followed what is explained by the documentation.
I've tried the very same code this morning in a fresh python environment, and it work.

Using the latest version of the Ultralytics YOLO library did the trick.

**Comment by paulohss** [comment]
Case closed as per my latest comment.

**Comment by paulohss** [comment]
Problem solved by updating YOLO.

**Comment by glenn-jocher** [comment]
@paulohss great to hear that updating to the latest version of the Ultralytics YOLO library resolved the issue! If you have any more questions or run into further issues, feel free to reach out. Happy detecting! 🚀
