### ISSUE TITLE
error "ignoring corrupt image/label: negative laberl value"

### ISSUE THREAD

**Issue by IgorGoldberg** [ultralytics/ultralytics#13203]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello Glen.
As usual, first I want to thank you  for previous answers to my questions. Appreciate it a lot.

I have  an issue with a labeling script that creates sometimes bounding boxes which size used to exceed  the image size
Thus while training I was getting such an error message:
`"ignoring corrupt image/label: negative label value"`
I will fix it it is not the issue...

**Question:**
Since unfortunately I have already trained a few models with such problematic labels I want to know something:
From the message it is not clear whether in this specific case YOLO ignores all the image and it is not being used at all while training (which could be great in my case)
Or it just ignores the current troublemaker bounding box ? ( This makes things worse since a Ground Truth object is not labeled as a legal object ).
Thank you very much!

**Comment by glenn-jocher** [comment]
Hello,

Thank you for reaching out and for your kind words! I'm glad to assist you again.

Regarding your question about the error message `"ignoring corrupt image/label: negative label value"`, YOLOv8 ignores the entire image and its associated labels when this error occurs. It does not use the problematic image for training at all. This means that none of the bounding boxes, even if some are correct, will be considered during the training process for that specific image.

This should ideally prevent the model from learning from incorrectly labeled data, which in your case seems to be beneficial as it avoids incorporating those problematic labels.

If you have any more questions or need further clarification, feel free to ask. Happy training!
