### ISSUE TITLE
Move TF conversion from onnx2tf to nobuco

### ISSUE THREAD

**Issue by Boulaouaney** [ultralytics/ultralytics#13229]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I think it would be great to ditch [onnx2tf](https://github.com/PINTO0309/onnx2tf) in favor of [nobuco](https://github.com/AlexanderLutsenko/nobuco).

I am willing to open a PR and try to work on it.

Other than the clear performance improvements and simplicity offered by `nobuco`, the maintainer of onnx2tf also recommends it as the optimal choice going forward:

> - Considering the compatibility of Pythonic code with TensorFlow/Keras/TFLite and the beauty of the conversion workflow, [nobuco](https://github.com/AlexanderLutsenko/nobuco) is the most optimal choice going forward.
>- The role of onnx2tf will end within the next one to two years. I don't intend to stop the maintenance of onnx2tf itself anytime soon, but I will continue to maintain it little by little as long as there is demand for it from everyone. The end of onnx2tf will be when TensorRT and other runtimes support porting from FX Graph based models.

### Use case

Models converted using `nobuco` directly from pytorch result in much simpler graphs and offer great speedups especially on GPU.

Reference: [But was it worth it?](https://github.com/AlexanderLutsenko/nobuco?tab=readme-ov-file#but-was-it-worth-it)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Boulaouaney thank you for your suggestion and willingness to contribute! 🚀

Switching from `onnx2tf` to `nobuco` for TensorFlow conversion sounds promising, especially considering the performance improvements and the recommendation from the `onnx2tf` maintainer. Your initiative to open a PR is greatly appreciated.

Please ensure that your changes are thoroughly tested with our models to maintain compatibility and performance standards. Looking forward to your pull request and collaboration on this enhancement! If you have any questions or need further assistance as you work on this, feel free to reach out.

Thanks again for your proactive approach and contribution to the community! 🌟

**Comment by Boulaouaney** [comment]
after further testing, it seems that for now onnx2tf is still the better option. Conversion with nobuco works but the resulting TFLite models end up with operators unsupported on the GPU, so it runs much slower. It will need further testing and more changes before being the better option for YOLO

**Comment by glenn-jocher** [comment]
Thank you for your detailed feedback and for taking the time to test the conversion with `nobuco`. It's valuable to understand the current limitations and performance differences between `onnx2tf` and `nobuco`.

Given your observations, it seems prudent to continue using `onnx2tf` for now, especially if the resulting TFLite models from `nobuco` are encountering unsupported operators on the GPU, leading to slower performance. Ensuring optimal performance is crucial, and your insights help us maintain the best possible user experience.

If you have any specific examples or reproducible code that highlight the issues with `nobuco`, please share them. This will help us and the community better understand the challenges and work towards potential solutions. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details on how to provide this information.

We appreciate your willingness to contribute and test new approaches. If you have any further findings or suggestions, please feel free to share. Your collaboration is highly valued! 😊

Thanks again for your efforts and for being an active member of the YOLO community! 🌟
