### ISSUE TITLE
Installing ultralytics in editable mode in Google Colab

### ISSUE THREAD

**Issue by JensOHI** [ultralytics/ultralytics#13237]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello 

I am trying to install ultralytics in Google Colab in editable mode. I do it by cloning the ultralytics repo and using pip to install:

```
!git clone https://github.com/ultralytics/ultralytics.git
%cd /content/ultralytics
!pip install -e .
%cd ..
```

If I when try to run:
```
from ultralytics import YOLO
model = YOLO('yolov8n-obb.pt') 
```

I get the following error:

```
ImportError                               Traceback (most recent call last)
[<ipython-input-5-48a3a2587d69>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from ultralytics import YOLO
      2 model = YOLO('yolov8n-obb.pt')

ImportError: cannot import name 'YOLO' from 'ultralytics' (unknown location)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
```
I does not matter what directory I am in. It can never find YOLO from ultralytics.

So my question is how do I install ultralytics in editable mode in Google colab.

PS: The reason I want to install it in editable mode is because I want to be able to change how the loss is calculated.

I have gotten it to work before, but I can never get it to work consistently. Also restarting runtime in Google Colab does not help

**Comment by JensOHI** [comment]
Sadly any of these approaches does not seem to work (atleast not consistently).

What I have found worked for me was just to clone the repo, make my changes and then install normally using pip `!pip install .`

**Comment by glenn-jocher** [comment]
@JensOHI hello,

Thank you for sharing your workaround. It's great to hear that you found a method that works consistently for you by installing directly with `!pip install .` after making your changes. This approach indeed ensures that the changes are packaged and recognized by the Python environment immediately.

If you encounter any more inconsistencies or have further questions, feel free to reach out. We're here to help! 🚀
