### ISSUE TITLE
'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by bhushangawde** [ultralytics/ultralytics#1323]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

> pip install ultralytics
> yolo predict model=yolov8n.pt source="https://ultralytics.com/images/bus.jpg"

These are the only two commands I have run. But I am facing the following error on running the second command. Please help.

This issue occurs while running the import command in script.
> import ultralytics

Matplotlib created a temporary config/cache directory at /tmp/matplotlib-xyoimbmv because the default path (/home/bare/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bare/data/kvn/miniconda3/envs/yoloV8/lib/python3.9/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.yolo.engine.model import YOLO
  File "/home/bare/data/kvn/miniconda3/envs/yoloV8/lib/python3.9/site-packages/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/home/bare/data/kvn/miniconda3/envs/yoloV8/lib/python3.9/site-packages/ultralytics/yolo/v8/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8 import classify, detect, segment
  File "/home/bare/data/kvn/miniconda3/envs/yoloV8/lib/python3.9/site-packages/ultralytics/yolo/v8/classify/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
  File "/home/bare/data/kvn/miniconda3/envs/yoloV8/lib/python3.9/site-packages/ultralytics/yolo/v8/classify/predict.py", line 6, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "/home/bare/data/kvn/miniconda3/envs/yoloV8/lib/python3.9/site-packages/ultralytics/yolo/engine/predictor.py", line 35, in <module>
    from ultralytics.nn.autobackend import AutoBackend
  File "/home/bare/data/kvn/miniconda3/envs/yoloV8/lib/python3.9/site-packages/ultralytics/nn/autobackend.py", line 15, in <module>
    from ultralytics.yolo.utils import LOGGER, ROOT, yaml_load
  File "/home/bare/data/kvn/miniconda3/envs/yoloV8/lib/python3.9/site-packages/ultralytics/yolo/utils/__init__.py", line 575, in <module>
    SETTINGS = get_settings()
  File "/home/bare/data/kvn/miniconda3/envs/yoloV8/lib/python3.9/site-packages/ultralytics/yolo/utils/__init__.py", line 541, in get_settings
    settings.keys() == defaults.keys() \
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by glenn-jocher** [comment]
@bhushangawde the line your error message refers to does not exist in utils/init, so you've either modified the file or are using out of date code. Update your package with `pip install -U ultralytics`

**Comment by bhushangawde** [comment]
@glenn-jocher 
Thank you for your reply.
I updated the package. 
I am still facing the same issue while importing ultralytics.

**Comment by glenn-jocher** [comment]
@bhushangawde please provide a minimum reproducible example. See https://stackoverflow.com/help/minimal-reproducible-example

**Comment by jvivian** [comment]
> @bhushangawde please provide a minimum reproducible example. See https://stackoverflow.com/help/minimal-reproducible-example

Posted a reproduction in this duplicate issue: https://github.com/ultralytics/ultralytics/issues?q=is%3Aissue+is%3Aopen+nonetype+keys#issuecomment-1465305823

**Comment by xzyxiaohaha** [comment]
@bhushangawde 
This is because the local settings.yaml file is empty.
I solved this problem by modifying "ultra-tics/yolo/utils/init.py".
1.delete those code:
`correct = \
                    settings.keys() == defaults.keys() #\
                and all(type(a) == type(b) for a, b in zip(settings.values(), defaults.values())) \
                and check_version(settings['settings_version'], version)`
2.add code:
`correct = None`
The modified content is：
```
 # correct = \
        #             settings.keys() == defaults.keys() \
        #         and all(type(a) == type(b) for a, b in zip(settings.values(), defaults.values())) \
        #         and check_version(settings['settings_version'], version)
correct = None
        if not correct:
            LOGGER.warning('WARNING ⚠️ Ultralytics settings reset to defaults. This is normal and may be due to a '
                           'recent ultralytics package update, but may have overwritten previous settings. '
                           f"\nView and update settings with 'yolo settings' or at '{file}'")
            settings = defaults  # merge **defaults with **settings (prefer **settings)
            yaml_save(file, settings)  # save updated defaults
```
hope it can help you.

**Comment by bhushangawde** [comment]
@xzyxiaohaha 
Hey,
Thanks, it works now with the changes you suggested.
Thanks a lot.

**Comment by bhushangawde** [comment]
Closing this issue.

**Comment by pderrenger** [comment]
@bhushangawde great to hear that the issue is resolved! If you have any more questions or run into any other issues, feel free to ask. Happy coding!
