### ISSUE TITLE
When will training multi-object tracking be available

### ISSUE THREAD

**Issue by plotnine1219** [ultralytics/ultralytics#13232]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When will training multi-object tracking be available？When can I train my own dataset. I really need it，

**Comment by glenn-jocher** [comment]
Hello,

Thank you for your inquiry about training capabilities for multi-object tracking with YOLOv8. As of now, training multi-object trackers directly is not yet supported, but it is on our roadmap for future updates. We understand the importance of this feature and are working towards making it available.

Currently, you can utilize pre-trained detection, segmentation, or pose models for tracking purposes. We will definitely announce updates related to this feature through our GitHub repository and documentation as soon as they are available.

Stay tuned for future releases, and thank you for your interest in Ultralytics YOLO!
