### ISSUE TITLE
pretrained models with smaller input resolution

### ISSUE THREAD

**Issue by chamecall** [ultralytics/ultralytics#13240]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

could someone pls share pretrained model with smaller input resolution trained on COCO?
thanks in advance

**Comment by glenn-jocher** [comment]
Hello!

Thanks for reaching out. Currently, all our official pretrained models are optimized for specific input resolutions as detailed in our documentation. We don't have a variant trained on COCO with a smaller input resolution readily available.

However, you can easily adjust the input size and retrain the model using the existing pretrained weights as a starting point. This approach allows you to customize the model to better fit your requirements. If you need guidance on how to do this, please refer to the training section of our documentation.

If you have any more questions or need further assistance, feel free to ask!

**Comment by chamecall** [comment]
> Hello!
> 
> Thanks for reaching out. Currently, all our official pretrained models are optimized for specific input resolutions as detailed in our documentation. We don't have a variant trained on COCO with a smaller input resolution readily available.
> 
> However, you can easily adjust the input size and retrain the model using the existing pretrained weights as a starting point. This approach allows you to customize the model to better fit your requirements. If you need guidance on how to do this, please refer to the training section of our documentation.
> 
> If you have any more questions or need further assistance, feel free to ask!

thanks)

**Comment by glenn-jocher** [comment]
You're welcome! If you decide to adjust and retrain the model and have any questions along the way, don't hesitate to reach out. Happy modeling! 😊
