### ISSUE TITLE
default mean/std for yolov8-cls model

### ISSUE THREAD

**Issue by baotou5937** [ultralytics/ultralytics#13247]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/ultralytics/ultralytics/assets/167690931/d9325df8-5991-4a54-93f8-7b5324fd0eef)
[link1](https://github.com/ultralytics/ultralytics/issues/10397#issuecomment-2088068765)
<br><br><br>

![image](https://github.com/ultralytics/ultralytics/assets/167690931/3a02c904-5b41-4a61-949b-8840c85a4861)
[link2](https://github.com/ultralytics/ultralytics/issues/10111#issuecomment-2061524746)
<br><br><br>

I see two different answers, which one is right?（note: I debugged step by step and found that during inference, the values mean = [0, 0, 0] and std = [1, 1, 1] in the second image were used, but I'm not sure if I was wrong）

**Comment by glenn-jocher** [comment]
Hello! Thanks for reaching out with your question.

For the YOLOv8-cls model, the default normalization values used during inference are indeed `mean = [0, 0, 0]` and `std = [1, 1, 1]`. This setting effectively means that no normalization is applied to the input images before passing them through the network. Your observation from debugging is correct.

If you have any more questions or need further clarification, feel free to ask. Happy coding! 🚀
