### ISSUE TITLE
Adding epochs after training is done

### ISSUE THREAD

**Issue by xzxorb** [ultralytics/ultralytics#13257]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! I am using the yolov8 to train my model with 100 epochs, after training it, I want to adding more epochs but I don't want to retrain it, how can I adding more epochs based on the previous 100 epochs and combine the result file with previous one? Thank you very much.

**Comment by glenn-jocher** [comment]
Hello! Thanks for reaching out with your question. 🌟

To continue training your model for additional epochs without starting from scratch, you can simply use the `resume` argument. This will load the last saved checkpoint (including weights, optimizer state, and epoch count) and continue training from there.

Here’s how you can do it:

```bash
yolo detect train data=coco128.yaml model=path/to/last.pt resume=True epochs=total_epochs
```

Replace `total_epochs` with the total number of epochs you want to train, including those already completed. For example, if you've trained for 100 epochs and want to add 50 more, set `epochs=150`.

This approach ensures that your training picks up right where it left off, using the saved model state from the last epoch of your previous training session.

Happy training! 🚀

**Comment by xzxorb** [comment]
It doesn't work.

```
AssertionError: D:\Desktop\yolov8\ultralytics\runs\pose\test\weights\last.pt training to 1 epochs is finished, nothing to resume.
Start a new training without resuming, i.e. 'yolo train model=D:\Desktop\yolov8\ultralytics\runs\pose\test\weights\last.pt'
```

**Comment by glenn-jocher** [comment]
Hello!

It looks like the training session you're trying to resume has already completed the specified number of epochs. If you want to continue training beyond the current epoch count, you'll need to increase the `epochs` parameter to a number greater than the epochs already trained.

For example, if your last training was for 100 epochs and you want to add more, specify a number greater than 100 in the `epochs` argument when you resume. Here’s how you can modify your command:

```bash
yolo detect train data=your_dataset.yaml model=D:\Desktop\yolov8\ultralytics\runs\pose\test\weights\last.pt epochs=150
```

This command sets the total epochs to 150, allowing for an additional 50 epochs of training based on your last checkpoint.

Let me know if this helps or if you have any more questions!

**Comment by xzxorb** [comment]
So I need to remove"resume=true"? But the result will not be generated in the previous folder and wil create a new folder, the epoch will start at 1 and the precision in the new epoch is much lower than the last checkpoint.
If I don't remove "resume=true", even I input greater epochs, it still shows "training is finished, nothing to resume." I think it only works when the training is terminated but not completed.

**Comment by JoanneLin168** [comment]
@xzxorb Try this? https://github.com/ultralytics/ultralytics/issues/802#issuecomment-1616631122

**Comment by seungbo** [comment]
@xzxorb I'm having the same problem. Have you resolved that issue?

**Comment by xzxorb** [comment]
Maybe need to modify the code,  you can refer to this website using translator   
https://jishuzhan.net/article/1769214871271903233

**Comment by glenn-jocher** [comment]
Thank you for the suggestion. We recommend following the official documentation and guidelines for any code modifications. If you have specific questions, feel free to ask here.

**Comment by seungbo** [comment]
@glenn-jocher 
<img width="178" alt="스크린샷 2024-09-22 오후 2 25 38" src="https://github.com/user-attachments/assets/ab6db738-87a9-4352-a9e1-1509b724d238">

What is the difference between with and without the number '2'?

**Comment by glenn-jocher** [comment]
The number '2' typically indicates a second instance or version of a file or model. It might be a duplicate or a modified version. Check the context or documentation for specifics.
