### ISSUE TITLE
Yolov8 Confusion Matrix FN, FP, TP, TN values

### ISSUE THREAD

**Issue by suleymanVR** [ultralytics/ultralytics#1325]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I trained a model on yolov8 using yolov8n-seg. It created a confusion matrix in .png format in my Runs folder. I want to access fp,fn,tp,tn values of this created confusion matrix and find accuracy. How can I do that?

### Additional

I used the yolov8 model training code shared by ultralytics as the code.

**Comment by glenn-jocher** [comment]
@suleymanVR you can access them directly in the confusion matrix class here:
https://github.com/ultralytics/ultralytics/blob/790f9c067c9a3548acf7c6925cea14de9ad77787/ultralytics/yolo/utils/metrics.py#L169-L266

**Comment by suleymanVR** [comment]
> @suleymanVR you can access them directly in the confusion matrix class here:
> 
> https://github.com/ultralytics/ultralytics/blob/790f9c067c9a3548acf7c6925cea14de9ad77787/ultralytics/yolo/utils/metrics.py#L169-L266

Actually, I looked at these codes in metrics.py, but I couldn't pull the values. Can you help with this? How exactly can I pull these values?

**Comment by suleymanVR** [comment]
@glenn-jocher Actually, I looked at these codes in metrics.py, but I couldn't pull the values. Can you help with this? How exactly can I pull these values?

**Comment by mehran66** [comment]
I made a PR for this issue:
https://github.com/ultralytics/ultralytics/pull/1353

**Comment by glenn-jocher** [comment]
@suleymanVR confusion matrix should now be available in val metrics starting in 8.0.52, i.e.

```python
metrics = model.val()
metrics.confusion_matrix
```

**Comment by apsai** [comment]
I am on 8.0.53 and trying to do the below and I get this error:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 metrics.confusion_matrix

File ~/ultralytics/yolo/utils/metrics.py:752, in ClassifyMetrics.__getattr__(self, attr)
    750 def __getattr__(self, attr):
    751     name = self.__class__.__name__
--> 752     raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")

AttributeError: 'ClassifyMetrics' object has no attribute 'confusion_matrix'. See valid attributes below.

    Class for computing classification metrics including top-1 and top-5 accuracy.

    Attributes:
        top1 (float): The top-1 accuracy.
        top5 (float): The top-5 accuracy.
        speed (Dict[str, float]): A dictionary containing the time taken for each step in the pipeline.

    Properties:
        fitness (float): The fitness of the model, which is equal to top-5 accuracy.
        results_dict (Dict[str, Union[float, str]]): A dictionary containing the classification metrics and fitness.
        keys (List[str]): A list of keys for the results_dict.

    Methods:
        process(targets, pred): Processes the targets and predictions to compute classification metrics.`

> @suleymanVR confusion matrix should now be available in val metrics starting in 8.0.52, i.e.
> 
> ```python
> metrics = model.val()
> metrics.confusion_matrix
> ```

**Comment by glenn-jocher** [comment]
@apsai confusion matrix is only implemented for detect and segment models. Please feel free to submit a PR extending this to classify models if you have time. Thank you!

**Comment by Mohaliyet** [comment]
Did I made a mistake? 

1. I used the `model.val()` and obtained the following Precision-Recall pairs for a four-class object detector. 
    ![image](https://user-images.githubusercontent.com/63839820/230877103-6eacf216-2fb1-4e85-a6ab-b897c7f2487b.png)
2. Displayed the confusion matrix using `metrics.confusion_matrix.matrix`
    ![image](https://user-images.githubusercontent.com/63839820/230876922-42455bdf-7269-41b3-8c86-cef5b2cb9ce4.png)
3. To double-check, I calculated the Precision-Recall pairs by referring to the confusion matrix values. However, the results I obtained do not match the ones generated by model.val(). Did I miss something?
   ![image](https://user-images.githubusercontent.com/63839820/230877726-5bd19ca4-3b33-45ee-a114-c73485a04771.png)

**Comment by glenn-jocher** [comment]
@mohaliyet you are probably getting slightly different results because the console metrics are output at the maximum mean F1 confidence, whereas the confusion matrix is computed at a fixed conf=0.25.

**Comment by JeanN00B** [comment]
I have a problem, when I do validation, sometimes the confusion matrix is plotted incomplete and I don't know how to solve this :c
![confusion_matrix_normalized](https://github.com/ultralytics/ultralytics/assets/71253306/20bfad14-f8e7-4a45-87ee-16a4d9621364)

**Comment by glenn-jocher** [comment]
@JeanN00B thanks for reaching out, it's great to hear you are using YOLOv8!

Regarding the incomplete confusion matrix during validation, this issue can occur when using a larger dataset as it requires more memory to plot the entire matrix. One way to potentially solve this would be to reduce the image size and batch size during validation, which should help lower the memory requirements. If you continue to face issues, please provide more details about your data and system specs and we can further investigate the issue.

**Comment by ceciler7** [comment]
> @mohaliyet you are probably getting slightly different results because the console metrics are output at the maximum mean F1 confidence, whereas the confusion matrix is computed at a fixed conf=0.25.

Is there a possibility to get a confusion matrix which reflects my input for conf and iou in val with split = 'test'? I use conf = 0.2 and iou = 0.5 but if the confusion matrix is computed at a fixed conf = 0.25 it won't reflect those inputs and is not useful for me

**Comment by mohaliyet** [comment]
> > @mohaliyet you are probably getting slightly different results because the console metrics are output at the maximum mean F1 confidence, whereas the confusion matrix is computed at a fixed conf=0.25.
> 
> Is there a possibility to get a confusion matrix which reflects my input for conf and iou in val with split = 'test'? I use conf = 0.2 and iou = 0.5 but if the confusion matrix is computed at a fixed conf = 0.25 it won't reflect those inputs and is not useful for me

```
results = model.val(data='data.yaml',conf=0.2,iou=0.5,split='test')
results.confusion_matrix.matrix
```

**Comment by ceciler7** [comment]
> > > @mohaliyet you are probably getting slightly different results because the console metrics are output at the maximum mean F1 confidence, whereas the confusion matrix is computed at a fixed conf=0.25.
> > 
> > 
> > Is there a possibility to get a confusion matrix which reflects my input for conf and iou in val with split = 'test'? I use conf = 0.2 and iou = 0.5 but if the confusion matrix is computed at a fixed conf = 0.25 it won't reflect those inputs and is not useful for me
> 
> ```
> results = model.val(data='data.yaml',conf=0.2,iou=0.5,split='val')
> results.confusion_matrix.matrix
> ```

When I run this code (with split = 'test' because I want to test on my test data), then I get the following results:

![image](https://github.com/ultralytics/ultralytics/assets/138725957/ac52b463-0cee-4774-b9df-5a0edc7b54a8)
![image](https://github.com/ultralytics/ultralytics/assets/138725957/2f48285f-58c1-43c1-913d-b54480362ecf)

The confusion matrix doesn't match the precision and recall scores that my model has as output. According to the confusion matrix:
Precision = 396 / (396+169) = 0.701
Recall = 396 / (396+111) = 0.781

This is probably due to the confusion matrix having a fixed conf = 0.25. Nevertheless, I would like to know if there is a possibility to get a confusion matrix which represents my conf and iou. I think this would be really helpful.

**Comment by ceciler7** [comment]
Also, when I try with the default values of val or with conf = 0.25 and iou = 0.45, the output (precision and recall) do not match with the precision and recall calculated from the model.

**Comment by glenn-jocher** [comment]
@mohaliyet hello,

Thank you for bringing this issue to our attention.

The confusion matrix in YOLOv8 is currently computed at a fixed confidence threshold of 0.25. This means that the confusion matrix does not directly reflect the input values of `conf` and `iou` that you specify during validation.

To obtain precision and recall scores that align with your input values of `conf` and `iou`, you can use the returned predictions from `model.val()` and compute precision and recall manually. This can be done by comparing the predicted bounding boxes with the ground truth annotations, using the specified `conf` and `iou` thresholds.

Additionally, please note that the confusion matrix may not always match the precision and recall scores exactly due to the nature of the computation and the complexity of object detection tasks.

If you have further questions or need assistance, please let us know.

**Comment by ceciler7** [comment]
Hi @glenn-jocher,

I'm currently using `model.val()` in Jupyter Notebook. Are the precision, recall etc provided in the output cell correct or do I need to calculate them by comparing the predicted labels to my ground truth data (as you mentioned)? Also, where can I access the predicted bounding boxes?

Another issue: Currently, I only got one image that I test and if I look at val_batch0_pred.jpg, I find 56 predicted labels. But according to the precision and recall values that I got in the output cell, I calculated that TP = 34 and FP = 6. Therefore, 40 predicted labels should appear on  val_batch0_pred.jpg. But if I look at TP and FP of the confusion matrix, it fits the number of 56 predicted labels. So, is also val_batch0_pred.jpg not reflecting the input values of `conf` and `iou`?

**Comment by titowp** [comment]
Hi Glenn.  after following the instance segmentation tutorial with yolov8 using roboflow, I found that the train mode output contained one confusion matrix.  My question is, does the CM belong to the box or the mask?  Thank You

**Comment by glenn-jocher** [comment]
@titowp hi,

Thank you for reaching out. 

In YOLOv8, the confusion matrix (CM) generated during training belongs to the bounding boxes, not the masks. The CM provides information about the accuracy of the bounding box predictions in terms of true positives (TP), true negatives (TN), false positives (FP), and false negatives (FN).

However, it's important to note that YOLOv8 does not directly generate pixel-level masks. Instead, it focuses on bounding box object detection. If you are specifically interested in instance segmentation with masks, you may need to explore other models or techniques that are designed for that purpose.

Please let me know if you have any further questions.

**Comment by saikrishna0203** [comment]
i want FN, FP, TP, TN  ,recall,precision,accuracy for yolov8 classfication model using yolov8 
class ClassifyMetrics(SimpleClass):
    """
    Class for computing classification metrics including top-1 and top-5 accuracy.

    Attributes:
        top1 (float): The top-1 accuracy.
        top5 (float): The top-5 accuracy.
        speed (Dict[str, float]): A dictionary containing the time taken for each step in the pipeline.

    Properties:
        fitness (float): The fitness of the model, which is equal to top-5 accuracy.
        results_dict (Dict[str, Union[float, str]]): A dictionary containing the classification metrics and fitness.
        keys (List[str]): A list of keys for the results_dict.

    Methods:
        process(targets, pred): Processes the targets and predictions to compute classification metrics.
    """

    def _init_(self) -> None:
        """Initialize a ClassifyMetrics instance."""
        self.top1 = 0
        self.top5 = 0
        self.speed = {'preprocess': 0.0, 'inference': 0.0, 'loss': 0.0, 'postprocess': 0.0}
        self.task = 'classify'

    def process(self, targets, pred):
        """Target classes and predicted classes."""
        pred, targets = torch.cat(pred), torch.cat(targets)
        correct = (targets[:, None] == pred).float()
        acc = torch.stack((correct[:, 0], correct.max(1).values), dim=1)  # (top1, top5) accuracy
        self.top1, self.top5 = acc.mean(0).tolist()

    @property
    def fitness(self):
        """Returns mean of top-1 and top-5 accuracies as fitness score."""
        return (self.top1 + self.top5) / 2

    @property
    def results_dict(self):
        """Returns a dictionary with model's performance metrics and fitness score."""
        return dict(zip(self.keys + ['fitness'], [self.top1, self.top5, self.fitness]))

    @property
    def keys(self):
        """Returns a list of keys for the results_dict property."""
        return ['metrics/accuracy_top1', 'metrics/accuracy_top5']

    @property
    def curves(self):
        """Returns a list of curves for accessing specific metrics curves."""
        return []

    @property
    def curves_results(self):
        """Returns a list of curves for accessing specific metrics curves."""
        return [] this is sub code of metrics.py here classfication only containc top 1 and tp 5 i need all curves and values please change code and send me sir pls

**Comment by glenn-jocher** [comment]
@saikrishna0203 hi there,

Thank you for reaching out!

In your provided code, the `ClassifyMetrics` class is calculating the top-1 and top-5 accuracy. However, getting confusion matrix metrics such as True Positives (TP), False Positives (FP), True Negatives (TN) and False Negatives (FN) requires comparison of predicted and actual class labels for each class in your model, not just the top predicted classes. Also, Recall, Precision, and Accuracy can be computed from the confusion matrix.

Unfortunately, we do not update the code according to individual requests as it becomes hard to maintain and follow. But don’t worry, if you want to customize it for your own needs, here's a little guidance.

To get the FN, FP, TP, TN, recall, precision and accuracy in classification models, you have to modify your `process` method significantly. Particularly, you need to compare every prediction with the ground truth on a class-by-class basis, so you can tally the true positives, false positives, true negatives, and false negatives for each class. From these values, you can then calculate recall, precision, and accuracy.

Remember, implementing these changes will require a good understanding of PyTorch, YOLOv8, and the specifics of your classification problem. Please proceed with caution and feel free to pose any possible difficulties you face during this process.

Thanks and good luck with your project!

**Comment by iMJalalKhan** [comment]
@glenn-jocher Thanks for all the information.

I am looking to generate a confusion matrix for test data. For train and val modes, we are able to get the confusion matrix and PR-curves, but for predict mode, I could not find the confusion matrix and PR-Curve. I have also tried the above results.confusion_matrix.matrix for predict rather than for val, and tried to modify a few things here and there, but could not solve to get confusion matrix for test dataset. Can you please guide ?

**Comment by glenn-jocher** [comment]
@iMJalalKhan hi there,

While the current implementation of YOLOv8 does generate a confusion matrix and PR-curves for training and validation data, it does not generate these directly for the test data in predict mode. This is due to the nature of the predict mode, which is focused on producing predictions rather than evaluating model performance.

However, there is a way to work around this. You can use the test set as if it was your validation set by substituting 'val' with 'test' in your yaml file, and then run your model in validation mode on your test set. This way, the model will compute and output the confusion matrix and PR-curves for your test data.

Remember, even though it's not a conventional approach, it can be an effective solution when you need to evaluate model performance on a test set. As always, make sure you are mindful of not using your test set too frequently to avoid model bias towards this set.

Hope this provides you a way forward!

**Comment by saikrishna0203** [comment]
Hello sir please tell me where I can find yolov8 architecture for detection
and classification pls help for that atleast

**Comment by glenn-jocher** [comment]
@saikrishna0203 hello,

The YOLOv8 architecture for both detection and classification can be found in the model files in the 'models' directory of the GitHub repository. The architecture of YOLOv8 specifically for detection is illustrated in the detection model files, usually named like 'yolov8*.yaml', where '*' can be different depending on specifics of the model. Similarly, for the classification task, the architecture is outlined in the classification model files, generally with names like 'resnet*.yaml'.

In these YAML files, you'll find the structure of the network including the configuration of each layer, the order of layers, and specifics about each type of layer used (convolutional, batch normalization, activation, etc.).

Take the time to peruse through these files thoroughly to understand the architecture. You can also look at the code in the repository that constructs and uses this architecture in training, validation, and testing.

Let me know if you have any more inquiries. Happy learning!

**Comment by saikrishna0203** [comment]
I am unable to find architecture for detection and classification sir
could please give me link

**Comment by glenn-jocher** [comment]
@saikrishna0203 

Hi there, 

The architecture for the YOLOv8 detection and classification model is located in the 'models' directory of this same GitHub repository where you found the code. In this directory, you'll find YAML files that detail the architecture of the models used by YOLOv8. 

For the detection model, look for a file with a name like 'yolov8*.yaml', and similarly, for the classification model, look for a file with a name like 'resnet*.yaml'. These YAML files contain the structure of the network, including the configuration of each layer, their types (like convolutional, batch normalization, and activation layers), and the order in which they're arranged.

Please keep in mind that the specifics of each model can differ, so the '*' in the filenames represents variations in the models, so the actual names might be slightly different.

To fully understand the architecture, look through these files thoroughly and also examine the code in the main repository that uses this architecture during the training, validation, and testing phases.

Please let me know if you have any further questions. Happy coding!

**Comment by cparcerisas** [comment]
Hi @ceciler7, did you find a solution? I am facing the same problem here :) 
Thanks!

**Comment by Alperemrehas** [comment]
> @apsai confusion matrix is only implemented for detect and segment models. Please feel free to submit a PR extending this to classify models if you have time. Thank you!

I modify the val.py and now I am able to work on the values overall and class level in classification. Does that solve the problem?

**Comment by mobin3399** [comment]
I trained a yolov8 network for classification, now I want to run it on test data and calculate the confusion matrix for it.
please guide me.

**Comment by glenn-jocher** [comment]
@mobin3399 for generating a confusion matrix for a YOLOv8 model trained for classification when running on test data, you would typically use the validation ('val') mode with your test data treated as the validation set. This can be done by specifying your test dataset in place of the validation set in your dataset configuration file, then running the 'val' mode which will yield a confusion matrix, among other metrics.

To do this practically, adjust your dataset YAML file to point 'val' to your test dataset path and use the following command:

```bash
python val.py --weights path/to/your/weights.pt --data path/to/your/dataset.yaml --img 640
```
(Use the required image size instead of 640 if different for your model)

This will evaluate your test data and provide you with the confusion matrix. The matrix, precision-recall curve, and additional metrics will be saved in your runs folder.

For further assistance, you can refer to the documentation, which can be found at `https://docs.ultralytics.com`.

**Comment by mobin3399** [comment]
> @mobin3399 for generating a confusion matrix for a YOLOv8 model trained for classification when running on test data, you would typically use the validation ('val') mode with your test data treated as the validation set. This can be done by specifying your test dataset in place of the validation set in your dataset configuration file, then running the 'val' mode which will yield a confusion matrix, among other metrics.
> 
> To do this practically, adjust your dataset YAML file to point 'val' to your test dataset path and use the following command:
> 
> ```shell
> python val.py --weights path/to/your/weights.pt --data path/to/your/dataset.yaml --img 640
> ```
> 
> (Use the required image size instead of 640 if different for your model)
> 
> This will evaluate your test data and provide you with the confusion matrix. The matrix, precision-recall curve, and additional metrics will be saved in your runs folder.
> 
> For further assistance, you can refer to the documentation, which can be found at `https://docs.ultralytics.com`.

Thanks.

**Comment by glenn-jocher** [comment]
@mobin3399 To calculate a confusion matrix for your YOLOv8 classification model on test data:
1. Alter your dataset YAML to list your test data under 'val'.
2. Run `val.py` with your model's weights and your updated dataset YAML.
3. Check your runs folder for the confusion matrix.

Consult the documentation for more details.

**Comment by mobin3399** [comment]
> @mobin3399 To calculate a confusion matrix for your YOLOv8 classification model on test data:
> 1. Alter your dataset YAML to list your test data under 'val'.
> 2. Run `val.py` with your model's weights and your updated dataset YAML.
> 3. Check your runs folder for the confusion matrix.
> 
> Consult the documentation for more details.

Thanks 🙏.

**Comment by glenn-jocher** [comment]
You're welcome, @mobin3399! If you have any more questions or need further assistance, feel free to ask. Good luck with your project! 😊👍

**Comment by yuju13488** [comment]
May I ask where the val.py file is?
I have completed the object detection training, but want to get the AP, AP50, AP75, APs, mAP, etc. of the test image.
It has been possible to make predictions on jupyter and obtain prediction data, but the evaluation of test data by metrics cannot be found.
Thanks a lot.

**Comment by glenn-jocher** [comment]
@yuju13488 the `val.py` file is located in the root directory of the YOLOv8 repository. To evaluate your object detection model and get metrics like AP, AP50, AP75, and mAP, you can run `val.py` with the appropriate flags for your trained weights and dataset. The results will be saved in the runs folder. For detailed instructions, please refer to the documentation.

**Comment by Alperemrehas** [comment]
> May I ask where the val.py file is? I have completed the object detection training, but want to get the AP, AP50, AP75, APs, mAP, etc. of the test image. It has been possible to make predictions on jupyter and obtain prediction data, but the evaluation of test data by metrics cannot be found. Thanks a lot.

Sorry for the late response. Your previous questions have already been replied. You may find the val.py directly under the "ultralytics/models/yolo/classify/val.py" directory. But if you didn't clone the ultralytics repo and install it with the command into your environment, then you can find the same directory under the environment directory in the specific workspace.

**Comment by glenn-jocher** [comment]
@Alperemrehas the `val.py` script is included in the YOLOv8 repository. After training, use this script with your test dataset to compute metrics like AP, AP50, AP75, and mAP. The results will be output to the runs folder. For step-by-step guidance, please refer to the documentation.

**Comment by HaTrungTn23** [comment]
@glenn-jocher Hello. I have a question: I am using YOLOv8-cls model. When using model.val(), top1_accurancy = 0.65. But when using best.pt to predict on val dataset, the accurancy is significantly low (0.22). Can you explain this phenomenon? What is the evaluation algorithm of YOLO cls?

**Comment by glenn-jocher** [comment]
It sounds like there might be a discrepancy between the validation and prediction processes. Ensure that the same preprocessing steps and data augmentations are applied during both validation and prediction. The evaluation algorithm for YOLO classification models typically involves calculating accuracy based on the top-1 and top-5 predictions. For more details, please refer to the Ultralytics documentation.

**Comment by hjammous** [comment]
@glenn-jocher: Thank you for all the details you've provided in this thread. I'm training a YOLOv8 segmentation model and I've noticed that the confusion matrix (CM) obtained at the validation stage doesn't correspond to the segmentation results (when running validation on a single image).

1. Is there a way to configure the model to output a confusion matrix based on the masks rather than the bounding boxes?
2. I understand that both box and mask metrics are calculated simultaneously during training. Does the training of this segmentation model rely on box metrics or mask metrics? And will the best model retained be based on box (B) or mask (M) performance?

**Comment by glenn-jocher** [comment]
@hjammous for your first question, currently, the confusion matrix in YOLOv8 is based on bounding boxes. For mask-based metrics, you might need to implement custom evaluation logic. Regarding your second question, the training of the segmentation model primarily relies on mask metrics, and the best model retained is based on mask performance.

**Comment by MarjanNoushinfar** [comment]
Hi,I trained YOLOv8 object detector on 1 class (apples). The confusion matrix shows 0 false negatives, thus a recall of 1. How ever the recall given after training and its curve is not 1 and based on that I should have around 164 FNs. Does anyone know what is the problem?                                 
p.s. the recall given after training and the curve are almost equal, considering the thresholds.
![confusion_matrix](https://github.com/user-attachments/assets/b2f43b21-c309-498f-b0bb-a9fd09bb91a3)
![R_curve](https://github.com/user-attachments/assets/ced63ea1-a970-45e9-9ab0-08645667606e)

**Comment by glenn-jocher** [comment]
It seems there might be a discrepancy between the confusion matrix and the recall metrics. Ensure that the evaluation thresholds and dataset splits are consistent. If the issue persists, please verify with the latest package version.

**Comment by GasparinFabrin** [comment]
I am a beginner in programming. I trained a detector using YOLOv8x, which had 2421 'train' images and 458 'val' images, with a single class:
My question;
- the number of images is not the same as that presented in the confusion matrix;
- the values ​​of the evaluation metrics presented by YOLO after simulation are not the same if the values ​​of the confusion matrix are used.


values ​​presented by YOLOV8x
fitness: 0.7487382332594785
maps: array([    0.73914])
metrics/precision(B)': 0.7914984798130403, 
'metrics/recall(B)': 0.646521473525693,
'metrics/mAP50(B)': 0.8351149987361939, '
metrics/mAP50-95(B)': 0.7391408148731768,


Code used: 
from google.colab import drive
drive.mount('/content/gdrive')

!pip install ultralytics

# Load a model
from ultralytics import YOLO
model = YOLO('yolov8x.pt')

from enum import auto
model.train(data='/content/gdrive/MyDrive/IsoladoresVidro/data.yaml', epochs=100)

imagen da matriz confusão:
![confusion_matrix (5)](https://github.com/user-attachments/assets/93a849c0-4b61-454c-8709-d64a26fa35dd)
![R_curve](https://github.com/user-attachments/assets/ab1cab4b-57d3-4564-9c4a-aef7312ed99d)

**Comment by GasparinFabrin** [comment]
> Olá, treinei o detector de objetos YOLOv8 em 1 classe (maçãs). A matriz de confusão mostra 0 falsos negativos, portanto, um recall de 1. No entanto, o recall fornecido após o treinamento e sua curva não é 1 e, com base nisso, devo ter cerca de 164 FNs. Alguém sabe qual é o problema? ps o recall fornecido após o treinamento (0,837 a 0,25) e a curva são quase iguais, considerando os limites. ![matriz_de_confusão](https://private-user-images.githubusercontent.com/63363351/361149455-b2f43b21-c309-498f-b0bb-a9fd09bb91a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2OTM2MDksIm5iZiI6MTcyNDY5MzMwOSwicGF0aCI6Ii82MzM2MzM1MS8zNjExNDk0NTUtYjJmNDNiMjEtYzMwOS00OThmLWIwYmItYTlmZDA5YmI5MWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDE3MjgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNjAzZmEzZDFkNWUzOGZhZjE2ZWNhZmNkZGFkNGUxMDhjMDYyNTU3MDY1NWY2MGIwZWUzNDczNDJhY2Y0YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fm4HLlj91SorFSocsQdXvUDbBmIq7l5gOoc9D8AMWEg) ![Curva R](https://private-user-images.githubusercontent.com/63363351/361149462-ced63ea1-a970-45e9-9ab0-08645667606e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2OTM2MDksIm5iZiI6MTcyNDY5MzMwOSwicGF0aCI6Ii82MzM2MzM1MS8zNjExNDk0NjItY2VkNjNlYTEtYTk3MC00NWU5LTlhYjAtMDg2NDU2Njc2MDZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDE3MjgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhODc2ODU1NWM3Y2Y2OWVkYmE5N2ZmZmViMDdkNTNjMzc3MmE0NTVhNWYxMWI1ZDQwYmUyNTRmMjhiNzE0YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5LZxQk7OM388yOC65z80jGVi1075E07eLtU2pEPpoyQ)

Hello, I have the same problem, did you manage to solve it?

**Comment by JensVor** [comment]
I encountered the issue that i trained a detection and a segmentation Yolov8n. I want to create a customized confusion matrix with less classes to compare the models performance on critical classes better. I cant manage that, to be more precise i can not create a normal one with all classes, i tried multiple things but nothing worked. This is what i got from this forum here but its not working:
results = model.val(data='Test.yaml',split='val')
results.confusion_matrix.matrix

Can anyone help me ( relatively new to programming) thanks in advance

**Comment by glenn-jocher** [comment]
Please ensure you are using the latest version of the Ultralytics package. For creating a customized confusion matrix, you can filter the classes after obtaining the full confusion matrix. If the issue persists, please refer to the [Ultralytics documentation](https://docs.ultralytics.com) for detailed guidance.

**Comment by JensVor** [comment]
@glenn-jocher now it works, is there any chance i can filter out classes that i dont want to be shown?
model = YOLO(".../best.pt")
results = model.val(data='Segmentation.yaml',split='val')
results.confusion_matrix.matrix

**Comment by JensVor** [comment]
It works now but i am trying to understand what Yolo uses/adds as
background. My model performs poorely and i receive a lot of detection
confusions with the background. Can you explain me what those images are?

Glenn Jocher ***@***.***> schrieb am Di., 27. Aug. 2024,
07:06:

**Comment by glenn-jocher** [comment]
@JensVor yOLO does not explicitly add background images; it treats any area not containing an object as background. If your model is confusing objects with the background, consider improving your dataset with more diverse background examples and ensuring accurate annotations. For further details, please refer to the Ultralytics documentation.

**Comment by fazrigading** [comment]
> [@mohaliyet](https://github.com/mohaliyet) you are probably getting slightly different results because the console metrics are output at the maximum mean F1 confidence, whereas the confusion matrix is computed at a fixed conf=0.25.

I want to visualize the Confusion Matrix using maximum mean F1 confidence. Is it possible? If yes, how can I do that?

**Comment by glenn-jocher** [comment]
Yes, you can generate a confusion matrix at the maximum F1 confidence by modifying the `conf` parameter during validation. Here's how:

```python
from ultralytics import YOLO

model = YOLO('yolov8n.pt')
model.val(conf=0.5)  # Set conf to your optimal F1 threshold
```

The optimal confidence threshold can be found in your `F1_curve.png` plot from training results. For implementation details, see the [ConfusionMatrix class](https://docs.ultralytics.com/reference/utils/metrics/#ultralytics.utils.metrics.ConfusionMatrix) in our docs.

**Comment by fazrigading** [comment]
> Yes, you can generate a confusion matrix at the maximum F1 confidence by modifying the `conf` parameter during validation. Here's how:
> 
> from ultralytics import YOLO
> 
> model = YOLO('yolov8n.pt')
> model.val(conf=0.5)  # Set conf to your optimal F1 threshold
> The optimal confidence threshold can be found in your `F1_curve.png` plot from training results. For implementation details, see the [ConfusionMatrix class](https://docs.ultralytics.com/reference/utils/metrics/#ultralytics.utils.metrics.ConfusionMatrix) in our docs.

Optimal confidence threshold that can be found in `F1_curve.png` from either training results or validation results **will be different** with max f1 index (variable `i`) at line 654 in metrics.py.
https://github.com/ultralytics/ultralytics/blob/b0dfb0cdf7516a147651b359a8dc797649a95e03/ultralytics/utils/metrics.py#L654

Here's the proof when compared to `F1_curve.png` from `model.val()` or validation result:
![Image](https://github.com/user-attachments/assets/90b884b6-e065-43b2-9b84-e287b770ebcf)

And here's the proof when compared to `F1_curve.png` from the training result:
![Image](https://github.com/user-attachments/assets/8eaf41a7-447f-474c-80a0-336ddc5be8fc)

I checked the max f1 index `i` value is 380 from the code in `ap_per_class()` function, while the optimal `conf` threshold in `F1_curve.png` shows 0.369 from validation results and 0.365 from training results.

Meanwhile, I have tried using 0.380 `conf` value in model.val(). proof is shown below.
![Image](https://github.com/user-attachments/assets/40e3fb71-eaa9-4182-8739-3372824e0a7c)

TP and FP from second class have the same value, but TP and FP from the first class is **different**. This makes my Precision values for the first class from Confusion Matrix plot resulted different with the actual validation results shown in the logger after `model.val()`.

@glenn-jocher So, my questions are:
1. Why the TP and FP values from ConfusionMatrix class resulted different with `model.val()` validation results despite using the same `conf` value that would be applied to ConfusionMatrix class according to this line 119 of val.py?  https://github.com/ultralytics/ultralytics/blob/b0dfb0cdf7516a147651b359a8dc797649a95e03/ultralytics/models/yolo/detect/val.py#L119 
2. Why the `F1_curve.png` shows optimal confidence threshold differently? Could you fix this so others could see the optimal confidence threshold easier? I think the problem is located here: https://github.com/ultralytics/ultralytics/blob/b0dfb0cdf7516a147651b359a8dc797649a95e03/ultralytics/utils/metrics.py#L526-L527
3. Why the TP and FP values in ConfusionMatrix class are computed without optimal confidence threshold on default? Isn't it better if we just use the optimal `conf` threshold to plot the ConfusionMatrix after we use `model.val(conf=0.380)`?

I apologize for asking too much questions to you. Thank you in advance.

Note: I forked the repo and added `print` after the f1 variables at `metrics.py`, check in my profile if you interested.

**Comment by glenn-jocher** [comment]
Thank you for your detailed analysis. The differences you're observing stem from how confidence thresholds are applied during metric calculations vs. visualization. The `F1_curve.png` uses smoothed interpolation for visualization purposes, while the actual metric calculations use raw precision-recall data. To align confusion matrix results with validation metrics, manually set the `conf` parameter to your optimal threshold from the F1 curve when calling `model.val()`. 

We'll review your observations about threshold consistency in our metrics pipeline. For immediate needs, you can explicitly specify your desired confidence threshold via the `conf` argument in `model.val()`, which directly controls the ConfusionMatrix calculation. Feel free to submit a PR with your proposed improvements if you've identified specific code adjustments that enhance this behavior.
