### ISSUE TITLE
Dataloader not reading TIFF file properly, how to change it to so that loading is done properly. 

### ISSUE THREAD

**Issue by trendi4** [ultralytics/ultralytics#1326]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to train a YOLO model on some TIFF files. The TIFF files are of shape [512, 512, 3], a stack of 3 grayscale images not color channels. 

YOLO currently loads the files using OpenCV, which basically takes the first image of my TIFF file [512, 512] and stacks this same image 3 times, completely ignoring the two other channels of the original image. The solution to proper loading is using a library called tifffile to load the image instead of OpenCV. 

So, I am trying to turn this: `im = cv2.imread(f)` into this: `im = tifffile.imread(f)` however for some reason, it does not work. 

Can you please point me to what lines of code should I change for the model to reflect these changes?

**Comment by glenn-jocher** [comment]
@trendi4 there are different dataloaders for train/val and predict, so you'd want to update all instances of cv2.imread() ops in all the dataloaders. You can find all dataloader code in this directory:
https://github.com/ultralytics/ultralytics/tree/main/ultralytics/yolo/data

**Comment by trendi4** [comment]
@glenn-jocher thanks for your quick response. Does this include the dataloaders directory there with v5 Dataloaders?

**Comment by glenn-jocher** [comment]
@trendi4 oh, yes the v5 loaders are in there also, but only support detection dataset and require an opt-in argument v5loader=True

**Comment by Y-T-G** [comment]
Duplicate of https://github.com/ultralytics/ultralytics/issues/6929
