### ISSUE TITLE
Instance segmentation with yolov8

### ISSUE THREAD

**Issue by sejr1996** [ultralytics/ultralytics#1327]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to use instance segmentation on overlapping objects with yolov8, however until now I am not able to train correctly the models. Can you help me with this please ?

The masks that are obtained by running the inference are cut between the overlapping objects.

Using the yolo cli directly the segmentation is correct. While doing it with ultralytics the masks are cut between the objects.

**Comment by sejr1996** [comment]
This is what we get with the yolov8 cli, we have two classes a body and a head.

![Captura de pantalla 2023-03-08 a la(s) 10 29 50](https://user-images.githubusercontent.com/75812071/223756182-f79936d1-014f-4bdd-bc25-6009777af839.png)

While using ultralytics the classes are cut, obtaining the following result.

![Captura de pantalla 2023-03-08 a la(s) 10 30 08](https://user-images.githubusercontent.com/75812071/223756534-d14e8de6-dc20-421c-92fe-f9ef762be545.png)

We need your help, thank you.

**Comment by pderrenger** [comment]
@sejr1996 it seems like you're observing an issue with instance segmentation using YOLOv8 through Ultralytics. Let's ensure that the environment and settings are aligned to achieve the comparable results obtained with the YOLOv8 CLI.

Firstly, ensure that the input parameters and settings for the custom model are consistent between both the YOLOv8 CLI and Ultralytics. This includes the model configuration, input images, and any preprocessing steps.

To mitigate the issue you're experiencing, it might also be beneficial to review the post-processing steps in the inference pipeline, such as the handling of overlapping objects and how the masks are generated.

Furthermore, you may want to check if there are any differences in the inference implementation between the YOLOv8 CLI and Ultralytics, including potential variations in the NMS (non-maximum suppression) strategies or object merging techniques.

By carefully aligning the parameters and inspecting the inference pipeline, we can work towards ensuring that the segmentation results obtained with Ultralytics are consistent with those from the YOLOv8 CLI.
