### ISSUE TITLE
ultralytics 8.2.26 export to openvino int8 quantization, performance drop significantly

### ISSUE THREAD

**Issue by qiangxinglin** [ultralytics/ultralytics#13270]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

When use yolo export to openvino, the model performance dropped significantly when running on openvino intel `GPU` device, but if I switch `ultralytics` back to `8.1.19`, to problem disappear.  
I guess in `8.1.19`, the model was firstly export to `onnx` format, then quantized to openvino model. But in the latest `8.2.26`, there's no intermediate `onnx` model.  
Maybe this indeed is an `openvino` bug, but I think it's worthy for ultralytics teams know this thing and make some workaround.

### Environment

```
Ultralytics YOLOv8.2.26 🚀 Python-3.9.19 torch-2.3.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)
Setup complete ✅ (48 CPUs, 125.4 GB RAM, 6.0/10.0 GB disk)

OS                  Linux-3.10.0-1160.80.1.el7.x86_64-x86_64-with-glibc2.27
Environment         Docker
Python              3.9.19
Install             pip
RAM                 125.40 GB
CPU                 Intel Xeon Silver 4214 2.20GHz
CUDA                11.8

matplotlib          ✅ 3.9.0>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.3.0+cu118>=1.8.0
torchvision         ✅ 0.18.0+cu118>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
```

### Minimal Reproducible Example

Use `ultralytics 8.2.26` any `yolov8n.pt`, then
```
yolo export model=yolov8n.pt format=openvino int8=True
```
Then, use `openvino==2024.1.0` or `openvino==2024.0.0`,  
```
import openvino as ov

core = ov.Core()
model = core.compile_model('PATH_TO_XML', 'GPU')
```
Then, any subsequent call to model inference would significantly slower than `ultralytics 8.1.19`.

### Additional

The model was export from my linux workstation (above), and the testing machine (run openvino) is my windows PC with `CPU Intel i7-9700 @ 3.00GHz`
I noticed the exported `xml` is different, here attached 2 versions of the xml.
[openvino_xml.zip](https://github.com/user-attachments/files/15511811/openvino_xml.zip)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@qiangxinglin thanks for your feedback here! You're right we recently eliminated the intermediate ONNX export. I've CC'd @adrianboguszewski, our Intel expert who helped make the change here for his feedback on your comments.

**Comment by adrianboguszewski** [comment]
@qiangxinglin when you say performance do you mean inference time or accuracy? Can you observe the same for the CPU?

**Comment by qiangxinglin** [comment]
@adrianboguszewski   
- I mean the **inference time**, also including the constructor time.
- For the previous version, the `GPU core.compile_model` would normally take about 5~8 seconds, but with the latest version, it would take more than 10 seconds. The inference time is also slower, but I haven't performed concise benchmark for it since the inference part is embeded in a larger program.
- The constructor time for CPU is hard to compare, because both of them took less than 1 second.

**Comment by glenn-jocher** [comment]
@qiangxinglin can you please profile your results with this code using both versions?

```
pip install ultralytics==YOUR_VERSION_HERE

yolo export model=yolov8n.pt format=openvino int8
yolo val model=yolov8n_int8_openvino_model data=coco.yaml  # record speeds
```

**Comment by glenn-jocher** [comment]
@qiangxinglin @adrianboguszewski I get these results on our server. Yes, slightly slower and less accurate with the latest version, though we now also have available batched inference. I'll do that and add it to compare.

```
Ultralytics YOLOv8.1.19 🚀 Python-3.11.6 torch-2.3.0+cpu CPU (AMD EPYC 7502 32-Core Processor)
Loading yolov8n_int8_openvino_model for OpenVINO inference...
...
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.371
Speed: 0.6ms preprocess, 15.0ms inference, 0.0ms loss, 1.7ms postprocess per image

Ultralytics YOLOv8.2.27 🚀 Python-3.11.6 torch-2.3.0+cpu CPU (AMD EPYC 7502 32-Core Processor)
Using OpenVINO LATENCY mode for batch=1 inference...
...
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.369
Speed: 2.5ms preprocess, 16.7ms inference, 0.0ms loss, 2.0ms postprocess per image
```

**Comment by glenn-jocher** [comment]
@adrianboguszewski I also get these warnings that I had not seen before, `mbind failed`
<img width="1634" alt="Screenshot 2024-06-02 at 00 00 34" src="https://github.com/ultralytics/ultralytics/assets/26833433/3950a21b-7db8-4523-915a-64b6489d22f5">

**Comment by adrianboguszewski** [comment]
@glenn-jocher could you test on Intel CPU to be sure?

**Comment by glenn-jocher** [comment]
@adrianboguszewski Absolutely, I'll run the tests on an Intel CPU setup and share the results here shortly. Thanks for the suggestion! 👍

**Comment by qiangxinglin** [comment]
@glenn-jocher Some further guess, the performance drop is related to "**dynamic input size**". The previous version input size is fixed to `[1,3,640,640]`, but the latest version is `[-1,3,-1,-1]`. The `batch` and `imgsz` arguments for `YOLO.export` seem being ignored.

**Comment by glenn-jocher** [comment]
@qiangxinglin Thanks for the additional insights! The dynamic input size could indeed be impacting the performance as it introduces more complexity in model optimization. We'll investigate the handling of the `batch` and `imgsz` arguments during the export process to ensure they are applied correctly. Your feedback is invaluable in helping us improve. Stay tuned for updates! 👍

**Comment by Roszczyk** [comment]
I tested interfering the model on OpenVINO 2024.0 and OpenVINO 2024.1 on a few different devices. The newer version seems to be always faster. Although, I tested it using equally shaped inputs. Dynamic input size may be the reason for your problems.

**Comment by glenn-jocher** [comment]
@Roszczyk thank you for sharing your observations! It's great to hear that you've tested the model on different OpenVINO versions and found the newer version to be faster with equally shaped inputs. Your insight about dynamic input size potentially causing performance issues is very valuable.

To further investigate, could you please provide a minimal reproducible example? This will help us replicate the issue on our end and identify a solution more effectively. You can refer to our [Minimum Reproducible Example Guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details on how to create one.

Additionally, please ensure that you are using the most recent versions of `torch` and `ultralytics`. If not, upgrading your packages might resolve the issue:

```bash
pip install --upgrade torch ultralytics
```

If the problem persists, you can try explicitly setting the input size and batch size during export to see if it mitigates the performance drop:

```python
from ultralytics import YOLO

# Load a YOLOv8n PyTorch model
model = YOLO("yolov8n.pt")

# Export the model with fixed input size and batch size
model.export(format="openvino", imgsz=(640, 640), batch=1)
```

Your feedback is crucial in helping us improve, so please keep us updated on your findings. If you have any further questions or need additional assistance, feel free to ask! 😊
