### ISSUE TITLE
how to change a label's name?

### ISSUE THREAD

**Issue by zp2546265641** [ultralytics/ultralytics#13286]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

for my urge need, when i change a label's name in coco8.yaml, and then i run "yolo task=detect mode=predict model=/home/zp/test/yolov8n.pt data=/home/zp/test/coco8.yaml source=/home/zp/图片  device=0 save=True show=True", it still show this label's last name instead of that i change later.
names:
  71: sink
  72: refrigerator
  73: book
  74: Rotor(before is clock)
  75: vase
  76: scissors
  and so? is adress that needed to change error? is there anything more to change?

**Comment by zp2546265641** [comment]
and now i haven't learned to train a new model, just due to my task, i do this operation

**Comment by zp2546265641** [comment]
> and now i haven't learned to train a new model, just due to my task, i do this operation
i run it on ubuntu20.04, and use it with pip install

**Comment by glenn-jocher** [comment]
Hello!

If you've updated the label names in your `coco8.yaml` file but still see the old names during predictions, it's likely that the model you are using (`yolov8n.pt`) was trained with the original label names and thus retains them internally.

For immediate changes in label names without retraining, you can manually adjust the `names` attribute of your model after loading it, before running predictions. Here's a quick Python snippet to help you do that:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('/home/zp/test/yolov8n.pt')

# Update class names directly
model.names = {71: 'sink', 72: 'refrigerator', 73: 'book', 74: 'Rotor', 75: 'vase', 76: 'scissors'}

# Now run prediction
results = model.predict(source='/home/zp/图片', save=True, show=True)
```

This way, you can ensure the predictions use the updated labels. Let me know if this helps or if you have any more questions!

**Comment by zp2546265641** [comment]
> Hello!
> 
> If you've updated the label names in your `coco8.yaml` file but still see the old names during predictions, it's likely that the model you are using (`yolov8n.pt`) was trained with the original label names and thus retains them internally.
> 
> For immediate changes in label names without retraining, you can manually adjust the `names` attribute of your model after loading it, before running predictions. Here's a quick Python snippet to help you do that:
> 
> ```python
> from ultralytics import YOLO
> 
> # Load your model
> model = YOLO('/home/zp/test/yolov8n.pt')
> 
> # Update class names directly
> model.names = {71: 'sink', 72: 'refrigerator', 73: 'book', 74: 'Rotor', 75: 'vase', 76: 'scissors'}
> 
> # Now run prediction
> results = model.predict(source='/home/zp/图片', save=True, show=True)
> ```
> 
> This way, you can ensure the predictions use the updated labels. Let me know if this helps or if you have any more questions!
thank you very much！i can realize my goal now！

**Comment by glenn-jocher** [comment]
Hello!

I'm glad to hear that the solution worked for you! If you have any more questions or need further assistance as you continue working with the YOLO models, feel free to reach out. Happy detecting! 🚀

**Comment by zp2546265641** [comment]
> Hello!
> 
> I'm glad to hear that the solution worked for you! If you have any more questions or need further assistance as you continue working with the YOLO models, feel free to reach out. Happy detecting! 🚀

thank you for your help！i am glad to join such a big family! i have a new problem today and i just  raise a new question in community! wishes for your reply!

**Comment by glenn-jocher** [comment]
Hello!

It's great to have you in the community! I'll take a look at your new question and respond there shortly. Keep the queries coming, and we're here to help! 🌟

Happy detecting!

**Comment by yqt** [comment]
Traceback (most recent call last):
  File "/mnt/d/work/object_detection/validation.py", line 8, in <module>
    model.names = {0: 'h'}
  File "/home/hackaday/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1788, in __setattr__
    super().__setattr__(name, value)
AttributeError: can't set attribute

Ultralytics 8.3.25 🚀 Python-3.9.2 torch-2.4.0+cu124 CUDA:0

not working now

**Comment by glenn-jocher** [comment]
It seems you're encountering an issue with setting the `names` attribute directly. Instead, try updating the `model.model.names` attribute to change class names. If you need further assistance, feel free to ask!
