### ISSUE TITLE
ImportError: cannot import name 'YOLOv10' from 'ultralytics IDE: VisualStudio

### ISSUE THREAD

**Issue by mrortach** [ultralytics/ultralytics#13295]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Yolov10 i cant test realtime with custom dataset

### Additional

from ultralytics import YOLOv10
ImportError: cannot import name 'YOLOv10' from 'ultralytics'

**Comment by mrortach** [comment]
TThat didn't work for me.

**Comment by glenn-jocher** [comment]
@mrortach hi there,

I'm sorry to hear that the solution didn't work for you. Could you please provide more details about the steps you followed and any error messages you received? This information will help us better understand the issue and assist you more effectively.

Looking forward to your response!

**Comment by mrortach** [comment]
I watched this video and got stuck while trying to test it in real-time. I think I trained it incorrectly, so I'm retraining according to the video, and then I will test it again.
https://www.youtube.com/watch?v=29tnSxhB3CY&lc=Ugx_VAIr6rnql3azjEB4AaABAg.A48IvOrFodXA48QhHgX88q

**Comment by glenn-jocher** [comment]
Hello @mrortach,

It seems like there's a misunderstanding regarding the available models. Currently, YOLOv10 is not a part of the Ultralytics YOLO series. Our latest version is YOLOv8, which you can use for real-time object detection tasks.

Please ensure you're using the correct model name in your import statement. For example, if you're working with YOLOv8, you should use:

```python
from ultralytics import YOLO
model = YOLO('yolov8n.pt')  # Load a pretrained YOLOv8n model
```

Retraining your model as per the guidance in the video is a good step. Make sure to follow the training instructions closely to optimize your model's performance.

If you have any more questions or need further assistance, feel free to ask. Happy coding! 😊

**Comment by mrortach** [comment]
I just wanted to test YOLOv10 and I followed the steps in the video and the problem was solved.

**Comment by RATHOD-SHUBHAM** [comment]
To solve the issue I did this:
1. git clone https://github.com/THU-MIG/yolov10.git
2. cd yolov10
3. pip install .

Now try:
from ultralytics import  YOLOv10

also, I had previously installed 
* pip install huggingface huggingface_hub, in case the huggingface_hub error comes up

**Comment by glenn-jocher** [comment]
@RATHOD-SHUBHAM hello,

Thank you for sharing your solution with the community! It's great to see you've successfully resolved the issue by cloning the YOLOv10 repository and handling the dependencies. Your detailed steps will definitely help others who might encounter similar issues.

If you have any more questions or insights as you continue working with the model, feel free to share them here!

Happy coding! 😊

**Comment by naomiconcept** [comment]
Hello, just to clarify, is Yolov10 a thing now or its not from ultralytics?

**Comment by glenn-jocher** [comment]
Hello @naomiconcept,

Thank you for your question! YOLOv10 is indeed a new model, but it is not developed by Ultralytics. It has been introduced by researchers at Tsinghua University and is available through their repository.

For Ultralytics models, the latest version we support is YOLOv8. If you are interested in exploring YOLOv10, you can follow the steps you mentioned to clone and install it from the Tsinghua University repository.

If you have any further questions or need assistance with Ultralytics models, feel free to ask. Happy experimenting! 😊

**Comment by frompotenza** [comment]
Maybe I misunderstood when you said "the latest version we support is YOLOv8," but I'm able to use YOLO("yolov9c.pt") for training. Wouldn't this be YOLOv9 > YOLOv8?
```
from ultralytics import YOLO
model = YOLO("yolov9c.pt")
model.train(
  pretrained=True,
  task='detect',
  ... some other parameters
)
```
I haven't tried running the trained model in real-time yet, though.

**Comment by glenn-jocher** [comment]
Hello @frompotenza,

Thank you for your question! I understand the confusion. YOLOv9 is indeed an experimental model that has been trained on the Ultralytics YOLOv5 codebase, implementing Programmable Gradient Information (PGI). However, YOLOv8 remains the latest stable release from Ultralytics, offering enhanced capabilities and support.

Your code snippet for training YOLOv9c looks correct. If you plan to run the trained model in real-time, you can use the `predict` method similarly to how you would with YOLOv8:

```python
from ultralytics import YOLO

# Load the trained model
model = YOLO("yolov9c.pt")

# Run inference on an image
results = model.predict(source="path/to/image.jpg")

# Display the results
results.show()
```

If you encounter any issues or have further questions, please ensure you are using the latest version of the Ultralytics package and provide a reproducible example if needed. You can find more details on creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you need any more assistance. Happy training! 😊

**Comment by frompotenza** [comment]
When you say it's experimental, is it worth using it (i.e., is it reliable enough to use it) or are there still many errors?

**Comment by glenn-jocher** [comment]
Hello @frompotenza,

Thank you for your question! The term "experimental" indicates that YOLOv9 is still in the testing phase and may not have the same level of stability and support as our stable releases like YOLOv8. While it incorporates innovative features such as Programmable Gradient Information (PGI), it might still have some unresolved issues or limitations.

If your project requires a highly reliable and well-supported model, I recommend using YOLOv8, which has been thoroughly tested and optimized for various tasks. However, if you are interested in exploring cutting-edge features and are comfortable with potential instability, YOLOv9 could be a valuable option for experimentation.

To ensure the best experience, always use the latest version of the Ultralytics package and keep an eye on updates and community feedback regarding YOLOv9.

Feel free to share any specific issues or feedback you encounter while using YOLOv9, and we will do our best to assist you. 😊

**Comment by Kush-nagar** [comment]
So i am running a custom model using YOLOV10 and i am getting this error:
```
Traceback (most recent call last):
  File "webcam_inference.py", line 33, in <module>
    cv2.imshow('Webcam', frame)
  File "path\to\site-packages\ultralytics\utils\patches.py", line 56, in imshow
    _imshow(winname.encode("unicode_escape").decode(), mat)
cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1301: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'
```


this is my code:
`import cv2
import os

import supervision as sv
from ultralytics import YOLOv10

model = YOLOv10(f'best.pt')

bounding_box_annotator = sv.BoundingBoxAnnotator()
label_annotator = sv.LabelAnnotator()

cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print("Camera open failed")

img_counter = 0

while True:
    ret, frame = cap.read()

    if not ret:
        break

    results = model(frame)[0]
    detections = sv.Detections.from_ultralytics(results)
    
    annotated_image = bounding_box_annotator.annotate(
        scene=frame, detections=detections)
    annotated_image = label_annotator.annotate(
        scene=annotated_image, detections=detections)

    cv2.imshow('Webcam', frame)

    k = cv2.waitKey(1)

    if k%256 == 27:
        print("Escape hit, closing...")
        break

cap.release()
cv2.destroyAllWindows()
`

**Comment by glenn-jocher** [comment]
Hello @Kush-nagar,

Thank you for sharing the details of your issue and providing the code snippet. It looks like you're encountering an OpenCV error related to the display window functionality. This error typically occurs when the OpenCV library is not built with GUI support on your platform.

Here are a few steps to help resolve this issue:

1. **Verify OpenCV Installation**: Ensure that OpenCV is installed with the necessary GUI support. You can try reinstalling OpenCV with the following command:
   ```bash
   pip uninstall opencv-python-headless
   pip install opencv-python
   ```

2. **Check for GTK+ Support**: If you're on Ubuntu or Debian, you might need to install additional packages:
   ```bash
   sudo apt-get update
   sudo apt-get install libgtk2.0-dev pkg-config
   ```

3. **Update Packages**: Ensure you are using the latest versions of all packages. You can update them using:
   ```bash
   pip install --upgrade ultralytics opencv-python
   ```

4. **Provide a Reproducible Example**: If the issue persists, please provide a minimum reproducible example. This helps us diagnose the problem more effectively. You can find guidelines on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Here's a slightly modified version of your code to ensure the frame is displayed correctly:
```python
import cv2
import os
import supervision as sv
from ultralytics import YOLOv10

model = YOLOv10('best.pt')

bounding_box_annotator = sv.BoundingBoxAnnotator()
label_annotator = sv.LabelAnnotator()

cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print("Camera open failed")

while True:
    ret, frame = cap.read()

    if not ret:
        break

    results = model(frame)[0]
    detections = sv.Detections.from_ultralytics(results)
    
    annotated_image = bounding_box_annotator.annotate(
        scene=frame, detections=detections)
    annotated_image = label_annotator.annotate(
        scene=annotated_image, detections=detections)

    cv2.imshow('Webcam', annotated_image)  # Display the annotated image

    if cv2.waitKey(1) & 0xFF == 27:  # Press 'ESC' to exit
        print("Escape hit, closing...")
        break

cap.release()
cv2.destroyAllWindows()
```

If you continue to face issues, please let us know, and we'll be happy to assist further. 😊
