### ISSUE TITLE
cannot set tensor for ultralytics/examples/YOLOv8-OpenCV-int8-tflite-Python /main.py

### ISSUE THREAD

**Issue by czy10383** [ultralytics/ultralytics#13304]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

In the example examples/YOLOv8-OpenCV-int8-tflite-Python/main.py

If I run this code with the default model = yolov8n_full_integer_quant.tflite, I get this error

ValueError: Cannot set tensor: Got value of type FLOAT32 but expected type INT8 for input 0, name: serving_default_images:0 

this error occurs at the following at line 260/261
scale, zero_point = input_details[0]["quantization"]
interpreter.set_tensor(input_details[0]["index"], img_data)

I believe this error will be resolved if we add the following change so that the input to the interpreter is INT8:

scale, zero_point = input_details[0]["quantization"]
img_data_int8 = (img_data / scale + zero_point).astype(np.int8)
interpreter.set_tensor(input_details[0]["index"], img_data_int8)

thank you for reviewing this.

### Environment

Ultralytics YOLOv8.2.27 🚀 Python-3.9.18 torch-2.1.2+cu121 CUDA:0 (NVIDIA GeForce GTX 1060 with Max-Q Design, 6072MiB)
Setup complete ✅ (12 CPUs, 31.0 GB RAM, 177.3/233.2 GB disk)

OS                  Linux-5.15.0-107-generic-x86_64-with-glibc2.31
Environment         Linux
Python              3.9.18
Install             pip
RAM                 31.03 GB
CPU                 Intel Core(TM) i7-8750H 2.20GHz
CUDA                12.1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@czy10383 hello! Thank you for the detailed report and the suggested fix for the `ValueError` you encountered with the YOLOv8 OpenCV-int8-tflite example. Your approach to adjust the data type to INT8 by scaling and adding the zero point is correct for handling quantized models.

We appreciate your contribution to improving the example code. If you're willing, you can directly contribute by submitting a pull request with your proposed changes. This would be a great help to the community, ensuring that others do not encounter the same issue.

If you prefer not to submit a PR, we'll review the issue internally and update the example accordingly.

Thank you again for your input and for using Ultralytics YOLOv8! 🚀

**Comment by czy10383** [comment]
@glenn-jocher thank you for the confirmation. I have submitted a PR, thank you :)

**Comment by glenn-jocher** [comment]
@czy10383, thank you for submitting the PR! We appreciate your contribution to improving the project. The team will review it shortly. 😊🚀
