### ISSUE TITLE
About weight file

### ISSUE THREAD

**Issue by super-song-sir** [ultralytics/ultralytics#13318]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Excuse me.I found that during the training process, the weight file will be larger, but when the training is over, the file will be smaller, what is the reason for this?

**Comment by glenn-jocher** [comment]
Hello! During training, the weight file includes not only the model weights but also additional information such as optimizer states and potentially other metadata necessary for resuming training. Once training completes, only the model weights are saved, which results in a smaller file size. This is a normal behavior intended to optimize the storage of trained models. If you have any more questions or need further clarification, feel free to ask. Happy coding! 😊

**Comment by super-song-sir** [comment]
> Hello! During training, the weight file includes not only the model weights but also additional information such as optimizer states and potentially other metadata necessary for resuming training. Once training completes, only the model weights are saved, which results in a smaller file size. This is a normal behavior intended to optimize the storage of trained models. If you have any more questions or need further clarification, feel free to ask. Happy coding! 😊

Thank you very much for your reply.By the way，When will ultralytics support YOLOv10.😊

**Comment by glenn-jocher** [comment]
Hello! We're glad the explanation was helpful! Regarding YOLOv10, we continuously work on integrating the latest advancements into our offerings. Keep an eye on our official channels for any updates on new model support. Your interest and support for Ultralytics are much appreciated! 😊 If you have any more questions, feel free to reach out. Happy coding!
