### ISSUE TITLE
Loading a custom trained detectron2 model?

### ISSUE THREAD

**Issue by horsto** [ultralytics/ultralytics#1331]
I have a few models trained with https://github.com/facebookresearch/detectron2
Now I discovered that YOLO implements pretty fantastic multi object trackers (https://docs.ultralytics.com/tasks/tracking/). 
The question I have is: Is it possible to somehow combine the trained detectron2 models I have with the YOLO interface / API to segment videos to finally use the multi object trackers available in YOLO? Does that even make sense?

**Comment by glenn-jocher** [comment]
@horsto no this is not possible.

You can get started with tracking very easily though, and once you train a new model you can swap that one in for the official model here:

```python
pip install ultralytics

yolo track model=yolov8n.pt source=0 show
```

**Comment by horsto** [comment]
Thanks, make sense. I think the creation of a custom dataset from my image data scares me away from it and it would have been great to have a simple "transfer" solution (detectron2 -> yolo).

**Comment by glenn-jocher** [comment]
@horsto we love PRs, so if you build a feature like that please consider contributing it! :)

**Comment by horsto** [comment]
Cool, yes, I would love - let's see ...
