### ISSUE TITLE
Transfer weights from yolov8l-seg.pt to a new architecture

### ISSUE THREAD

**Issue by N0lanakis** [ultralytics/ultralytics#13325]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey,

i want to know if its possible to get the weights from a pretrained yolo segmentation model you provide in order to use them in a custom segmentation architecture i have created. More specific i added a new block between head and decoder output. So i want if its possible to get all the weights from all the layers before decoder and train again the model in another dataset.

can you please provide me some instructions?

Thanks,
Nol

**Comment by glenn-jocher** [comment]
@N0lanakis hello Nol,

Yes, you can transfer weights from a pretrained YOLOv8 segmentation model (`yolov8l-seg.pt`) to a custom architecture. Here's a general approach using PyTorch:

1. **Load the Pretrained Model**: First, load the pretrained YOLOv8 segmentation model.
   ```python
   from ultralytics import YOLO
   model = YOLO('yolov8l-seg.pt')
   ```

2. **Modify Your Custom Model**: Ensure your custom model architecture is defined in a way that it can accept the weights from the pretrained model. The layers you've added should be initialized but left without pretrained weights.

3. **Transfer Weights**: You can transfer the weights to your custom model by iterating over both model's state dictionaries (assuming they share common layer names for the layers you want to transfer).
   ```python
   custom_model_dict = custom_model.state_dict()
   pretrained_dict = {k: v for k, v in model.state_dict().items() if k in custom_model_dict}
   custom_model_dict.update(pretrained_dict)
   custom_model.load_state_dict(custom_model_dict)
   ```

4. **Train on New Dataset**: Now, you can train your custom model on the new dataset.

Make sure the layer names match between the models for the weights to be correctly transferred. If the architectures differ significantly, you might need to manually adjust which weights are transferred or modify the architecture to better accommodate the pretrained weights.

Best of luck with your project!

**Comment by N0lanakis** [comment]
@glenn-jocher  How can i be sure that weights are loaded? Im asking because i make the changes you tell me and the model dont start from a bigger mAP value.

**Comment by glenn-jocher** [comment]
Hello @N0lanakis,

To verify that the weights are correctly loaded into your model, you can check the state of the model before and after loading the weights. Here’s a quick way to do this:

1. **Before Loading Weights**: Print the weights of a specific layer or several layers to see their initial state.
   ```python
   print("Weights before loading:", custom_model.layer_name.weight)
   ```

2. **Load the Weights**: Execute your weight transfer code.

3. **After Loading Weights**: Print the same weights again to see if they have changed.
   ```python
   print("Weights after loading:", custom_model.layer_name.weight)
   ```

If the weights have changed, then they have been successfully loaded. Keep in mind that starting with a higher mAP depends not only on loading the weights but also on how well the new block integrates with the existing architecture and the specific characteristics of the new dataset.

If you continue to see unexpected results, consider evaluating if the new block requires specific tuning or initialization strategies. 🛠️
