### ISSUE TITLE
choose specific set of classes for training in COCO dataset

### ISSUE THREAD

**Issue by chamecall** [ultralytics/ultralytics#13329]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hello, is it possible to train model on COCO dataset using only some subset of classes not all of 80?
maybe it could be done somehow using your dataset config (coco.yaml) like simple remove of other classes from there or somehow else?
or it should be done with direct dataset filtering?
thanks in advance

**Comment by glenn-jocher** [comment]
Hello! Yes, you can train a model on a subset of classes from the COCO dataset. You can achieve this by modifying the `coco.yaml` dataset configuration file. Here’s how you can do it:

1. **Edit the `coco.yaml` file**: In the `names` section of the YAML file, list only the classes you want to train on. Remove any classes you do not wish to include.
2. **Filter the dataset**: You might also need to filter your annotations to only include those that correspond to your selected classes. This ensures that the model does not receive data from the classes you've excluded.

By following these steps, you can customize the training process to focus only on your classes of interest. If you need further assistance, feel free to ask. Happy training! 🚀

**Comment by chamecall** [comment]
> Hello! Yes, you can train a model on a subset of classes from the COCO dataset. You can achieve this by modifying the `coco.yaml` dataset configuration file. Here’s how you can do it:
> 
>     1. **Edit the `coco.yaml` file**: In the `names` section of the YAML file, list only the classes you want to train on. Remove any classes you do not wish to include.
> 
>     2. **Filter the dataset**: You might also need to filter your annotations to only include those that correspond to your selected classes. This ensures that the model does not receive data from the classes you've excluded.
> 
> 
> By following these steps, you can customize the training process to focus only on your classes of interest. If you need further assistance, feel free to ask. Happy training! 🚀

thanks for your answer, gonna try it)

**Comment by glenn-jocher** [comment]
@chamecall you're welcome! If you encounter any issues or have more questions as you proceed, don't hesitate to reach out. Good luck with your training! 🌟

**Comment by RobinHeitz** [comment]
Hi, question from my side:
if the data.yaml has:
`names: ['BatteryTop', 'Busbar', 'Cable', 'JuctionBlock', 'LeafCell', 'ServicePlug', 'screw']`

And I remove all but **screw**, I need to delete the annotations as well. I tried to do that but I'm not quite sure about the label format.

E.g.:
```
6 0.5156813890625 0.4760073546875 0.51781389375 0.47547204687500005 0.52141141875 0.47200527656249996 0.5197426953125001 0.466014884375 0.510752425 0.46183516874999997 0.4983201015625 0.46586250937499996 0.495778328125 0.4741155359375 0.5024742062499999 0.4807749421875 0.5096176125 0.47881135468749997 0.5138826265625001 0.47774073906250003 0.5156813890625 0.4760073546875
6 0.489829084375 0.39486733749999997 0.491961590625 0.39433202968750003 0.4955591140625 0.390865259375 0.493890390625 0.3848748671875 0.48490012031249996 0.3806951515625 0.472467796875 0.384722490625 0.469926028125 0.3929755171875 0.47662190156250006 0.39963492343749996 0.483765309375 0.3976713390625 0.48803032343749997 0.3966007234375 0.489829084375 0.39486733749999997
6 0.42622150468750003 0.19606179375 0.42835401093750003 0.1955264890625 0.4319515359375 0.19205971718749998 0.43028281249999994 0.1860693234375 0.421292540625 0.18188960781250002 0.40886021718750004 0.185916946875 0.40631844375000004 0.1941699734375 0.413014321875 0.20082938125 0.4201577328125 0.19886579375 0.42442274375 0.1977951796875 0.42622150468750003 0.19606179375
6 0.42622150468750003 0.19606179375 0.42835401093750003 0.1955264890625 0.4319515359375 0.19205971718749998 0.43028281249999994 0.1860693234375 0.421292540625 0.18188960781250002 0.40886021718750004 0.185916946875 0.40631844375000004 0.1941699734375 0.413014321875 0.20082938125 0.4201577328125 0.19886579375 0.42442274375 0.1977951796875 0.42622150468750003 0.19606179375
6 0.57679295 0.6670538265625 0.57892545625 0.6665185203124999 0.5825229796875 0.6630517499999999 0.58085425625 0.6570613578125 0.5718639859375 0.6528816421875 0.5594316609375001 0.6569089796875 0.5568898921875001 0.6651620078125 0.5635857640624999 0.6718214125 0.5707291750000001 0.6698578281249999 0.5749941875 0.6687872125000001 0.57679295 0.6670538265625
6 0.5655288578125 0.8215669046875 0.5676613640625 0.8210315984375001 0.5712588875 0.817564828125 0.5629513625 0.8102559375 0.56338656875 0.810146690625 0.5481675703125 0.811422059375 0.545625796875 0.8196750875 0.552321675 0.8263344921875 0.559465084375 0.8243709046875001 0.563730096875 0.823300290625 0.5655288578125 0.8215669046875
4 1 0.3515030625 0.99755815 0.3427372890625 0.9491651937500001 0.1690159171875 0.9368166453125 0.1246870140625 0.9318841453125 0.12336147187499999 0.934146690625 0.1151023890625 0.9036241140625 0.120200528125 0.8505715359374999 0.11813564843749999 0.8377764984375 0.1213474890625 0.8062526890624999 0.1228513953125 0.7711313578125 0.127822071875 0.7392738046875 0.12812789687499998 0.6665648890625 0.137406478125 0.6475023703125 0.1345004625 0.565929684375 0.1447221921875 0.5542659203125 0.14380449374999998 0.5166783374999999 0.1481123984375 0.43770194218749997 0.151273121875 0.415709390625 0.1542300328125 0.398649340625 0.158512490625 0.385390521875 0.1682500328125 0.3855942265625 0.17717188749999999 0.378732925 0.1853035078125 0.38173662343750003 0.19608621406249999 0.3702765640625 0.20409036875000003 0.380418940625 0.23230894531250001 0.3884851796875 0.23669341406250002 0.386092596875 0.252676278125 0.39723620625 0.2844890875 0.40216870781249997 0.28581463125 0.41676250625 0.2808694015625 0.426627509375 0.2835204890625 0.424772375 0.3096232859375 0.4374373734375 0.314135221875 0.43537853281250005 0.3313161625 0.42378843593750004 0.34704409531249997 0.4320583828125 0.360350421875 0.4279970765625 0.37034289062500003 0.42986950156250003 0.3852551421875 0.4407357390625 0.3915004625 0.4338744359375 0.39963208125 0.4432192828125 0.43317827812500004 0.462949290625 0.43848045 0.4747430921875 0.43167437187499996 0.942112990625 0.3566552703125 0.9721717812499999 0.35808283125 0.996630584375 0.3557886890625 1 0.35473713125 1 0.3515030625
4 1 0.3759935359375 0.4975000984375 0.4520262546875 0.56955276875 0.69306725625 1 0.6086103046875 1 0.3759935359375
4 1 0.6995901718749999 0.5546154343749999 0.789165615625 0.6062522203125 0.9895981546874999 1 0.890758615625 1 0.6995901718749999
```
This means I have several annotations for class with indexes 4 and 6, right?
So I need to remove all lines that contain 4 at the first element, then replace the leading 6 with 0?

I did this with a little python script for all files, but in training mode I get warnings like

> 1 duplicate labels removed

I think that I might have misunderstood the label format and thats where the err is coming from?

**Comment by glenn-jocher** [comment]
Hi there! Great question. You're on the right track with modifying the annotations, but let's clarify the label format and the steps to ensure everything works smoothly.

### Label Format
In YOLO, the label format for each object in an image is typically:
```
<class_id> <x_center> <y_center> <width> <height>
```
For polygons or more complex shapes, the format can include additional coordinates, but the first element is always the `class_id`.

### Steps to Modify Annotations
1. **Filter Annotations**: Remove lines with class IDs you don't need.
2. **Reindex Class IDs**: If you only keep the class `screw` (originally class `6`), you need to reindex it to `0` since it will be the only class.

### Python Script Example
Here's a Python script to help you filter and reindex your annotations:

```python
import os

# Define the path to your annotations directory
annotations_dir = 'path/to/annotations'

# Define the class you want to keep (e.g., 'screw' with original class_id 6)
target_class_id = 6
new_class_id = 0

# Iterate over all annotation files
for filename in os.listdir(annotations_dir):
    if filename.endswith('.txt'):
        file_path = os.path.join(annotations_dir, filename)
        
        with open(file_path, 'r') as file:
            lines = file.readlines()
        
        new_lines = []
        for line in lines:
            parts = line.strip().split()
            class_id = int(parts[0])
            
            if class_id == target_class_id:
                parts[0] = str(new_class_id)
                new_lines.append(' '.join(parts))
        
        # Write the filtered and reindexed annotations back to the file
        with open(file_path, 'w') as file:
            file.write('\n'.join(new_lines))

print("Annotations updated successfully!")
```

### Handling Duplicate Labels
The warning `1 duplicate labels removed` suggests that there might be overlapping annotations. This can happen if multiple annotations are very close to each other. To address this, you can:

1. **Check for Overlaps**: Ensure that your annotations do not overlap significantly.
2. **Use Non-Maximum Suppression (NMS)**: During training, NMS can help filter out duplicate detections.

### Final Steps
1. **Verify Dataset**: After modifying the annotations, verify that your dataset is correctly formatted and that the annotations correspond to the images.
2. **Update `data.yaml`**: Ensure your `data.yaml` file reflects the changes, listing only the `screw` class.

If you follow these steps and still encounter issues, please provide a minimum reproducible example so we can investigate further. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Happy training! 🚀

**Comment by RobinHeitz** [comment]
Thanks for the quick reply!

Is there a good way to validate my 'new' dataset, e.q. to open it in a annotation program and check whether cls/boxes are right? Can you recommend something?

I've done the exact same as your little python script, so I think I've been on the right track then.

**Comment by glenn-jocher** [comment]
@RobinHeitz you're welcome! 😊

To validate your 'new' dataset and ensure that the class labels and bounding boxes are correct, you can use annotation tools that allow you to visualize and edit your annotations. Here are a couple of popular options:

1. **LabelImg**: A free, open-source graphical image annotation tool that supports YOLO format. You can load your images and annotations to visually inspect and edit them if necessary.
   - [LabelImg GitHub](https://github.com/tzutalin/labelImg)

2. **Roboflow**: An online platform that provides tools for dataset management, including visualization, annotation, and conversion between different formats.
   - [Roboflow](https://roboflow.com/)

Both tools will help you ensure that your annotations are correctly formatted and aligned with your images. If you encounter any issues or need further assistance, feel free to reach out. Happy annotating! 🚀

**Comment by RobinHeitz** [comment]
Thanks.
I've checked the dataset in roboflow. Turns out that every annotation was a polygon with > 15 points. Thats why I got confused about the format.

**Comment by glenn-jocher** [comment]
@RobinHeitz hello!

Thank you for the update. It's great to hear that you used Roboflow to check your dataset. Polygons with more than 15 points can indeed be a bit tricky to handle.

To ensure everything is in order, you might want to simplify the polygons if your use case allows it. Simplifying polygons can reduce the complexity and help in faster processing. Here's a quick example using the `shapely` library to simplify polygons:

```python
from shapely.geometry import Polygon

# Example polygon with many points
coords = [(0, 0), (1, 1), (2, 2), ...]  # Add your coordinates here
polygon = Polygon(coords)

# Simplify the polygon
simplified_polygon = polygon.simplify(tolerance=0.01, preserve_topology=True)

# Get simplified coordinates
simplified_coords = list(simplified_polygon.exterior.coords)
print(simplified_coords)
```

This will help you reduce the number of points while maintaining the shape's integrity.

If you encounter any further issues or need additional assistance, feel free to reach out. Happy annotating and training! 🚀
