### ISSUE TITLE
Batch Size per GPU options

### ISSUE THREAD

**Issue by parthapn98** [ultralytics/ultralytics#13328]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

1. Is it currently possible to set per GPU batch sizes when training?
For cases when Multiple GPU's are not of same memory sizes.

3. Also how do we edit validation batch sizes as mentioned in https://github.com/ultralytics/ultralytics/issues/3308#issuecomment-1690353865

**Comment by glenn-jocher** [comment]
Hello!

1. YOLOv8 does not currently support different batch sizes per GPU directly through its API. All GPUs involved in the training will use the same batch size as specified by the `batch` argument. For GPUs with varying memory sizes, you might consider setting the batch size according to the GPU with the smallest memory to avoid out-of-memory errors.

2. To adjust the validation batch size, you can use the `batch` argument in the validation function. This allows you to specify a different batch size for validation compared to training. For example, if you're using the CLI, you can specify `yolo val model=yolov8n.pt batch=32` to set the validation batch size to 32.

I hope this helps! Let us know if you have any more questions.
