### ISSUE TITLE
camera resolution for real time detection

### ISSUE THREAD

**Issue by lurunawjan** [ultralytics/ultralytics#13320]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I want to ask, I have a trained model with size 640x640 and 1280x1280. And I want to use the trained model for real time detection. I have intelsense camera model D435i and the resolution for the RGB is 1920x1080. Can I used my 640x640 size with the resolution of the camera? or how to know the good resolution from the camera to detect the object ( in my case)

Thank you

**Comment by Kayzwer** [comment]
@lurunawjan ultralytics autobackend will resize the image to proper size before feed into the model, but of course the higher the resolution the better, but with slower inference speed.
