### ISSUE TITLE
Accuracy Plot

### ISSUE THREAD

**Issue by Mary14-design** [ultralytics/ultralytics#13327]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I'd like to know if it's possible to share instructions/code for the following accuracy plot.

![accuracy](https://github.com/ultralytics/ultralytics/assets/54886321/91d833f9-12cb-498a-a7f5-eebd5805b96c)

**Comment by glenn-jocher** [comment]
Hello! 👋

To generate an accuracy plot like the one you've shown, you can use TensorBoard, which integrates seamlessly with our training process. Here’s a quick guide on how to set it up:

1. **Enable TensorBoard Logging:** When you start your training with YOLOv8, ensure that TensorBoard logging is enabled. This is usually done by setting the `--tensorboard` flag or ensuring the logging is set up in your training script.

2. **Start TensorBoard:** Once training is underway, you can launch TensorBoard by running the following command in your terminal:
   ```bash
   tensorboard --logdir=runs
   ```
   Replace `runs` with the directory where your logs are saved.

3. **View the Plots:** Open your browser and go to `http://localhost:6006/` to view your accuracy plot, along with other useful metrics.

This should help you visualize the accuracy of your model throughout the training process. If you have any more questions or need further assistance, feel free to ask!

Happy training! 🚀
