### ISSUE TITLE
Setting width of bouding box

### ISSUE THREAD

**Issue by HAOHANZHOU** [ultralytics/ultralytics#13334]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there a way to set the width of bounding box when predicting? For example: yolo predict model={XXX} source={XXX} width=1

**Comment by glenn-jocher** [comment]
Hello! 👋

In YOLOv8, the width of the bounding box lines during prediction visualization is not directly adjustable via the CLI command as you described. However, you can modify the line thickness by altering the source code for visualization.

If you're comfortable editing the Python code, you can adjust the `line_thickness` parameter in the visualization function within the YOLOv8 codebase. This change will allow you to set the desired thickness for the bounding box lines.

If you need further guidance on which file or function to modify, feel free to ask!

Happy coding! 😊
