### ISSUE TITLE
How much data to pass for YOLO if we have the same object in our dataset we want to detect

### ISSUE THREAD

**Issue by Avv22** [ultralytics/ultralytics#13335]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have to detect object in a video where the video no matter how much we retake always result in identical frames, I mean the object on assembly line looks identical to all other objects on the assembly line. I just want to make sure that I detect that object the assembly line.

Since I can not have a lot of variety in data collection as I am dealing with limited environment that has one object only, how many images you think I need to train yolov8 in this case please?

**Comment by glenn-jocher** [comment]
@Avv22 hello!

For training YOLOv8 to detect objects in a highly consistent environment, such as an assembly line with identical objects, the quantity of data required might be less than in scenarios demanding high variability recognition. However, ensuring robust detection still requires a decent dataset size.

A good starting point could be around 500-1000 images of the object in various conditions of the assembly line, if possible. This includes slight variations in lighting, angles, and occlusions that might occur. Additionally, leveraging data augmentation techniques can effectively increase your dataset's diversity without physically capturing more unique samples.

If your initial results aren't satisfactory, consider incrementally adding more images or adjusting your training parameters. Remember, the quality and diversity of the dataset can significantly impact the model's performance, even in a controlled environment.

Best of luck with your training! 🚀
