### ISSUE TITLE
Yolov8 obb training label bbox show wrong

### ISSUE THREAD

**Issue by favorxin** [ultralytics/ultralytics#13336]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I am training yolov8 obb for region detect as shown in picture. The second img's box is: "1 0.03741  0.17815  0.96496  0.17815  0.96496  0.88907 0.0374109 0.8890", image shape: 1684*1190. But the plot image cannot show the correct box.
![image](https://github.com/ultralytics/ultralytics/assets/31987475/c60ec575-ae84-46b0-8f57-b21e4401efd1)
My part dataset is following:
[table_train.zip](https://github.com/user-attachments/files/15537291/table_train.zip)

**Comment by glenn-jocher** [comment]
Hello,

Thank you for reaching out and providing detailed information about your issue. It seems like there might be a problem with how the bounding box coordinates are being interpreted or plotted. 

To assist you better, could you please confirm if you have verified the format of your bounding box coordinates against the expected format in YOLOv8 OBB? The coordinates should be normalized and in the order `[class_id, x_center, y_center, width, height, angle]`.

If your format aligns correctly, it might be helpful to check if there's any transformation or preprocessing step that might be altering the coordinates unexpectedly.

Looking forward to your response to help resolve this issue effectively!

**Comment by favorxin** [comment]
Thank you for response. I checked the input data format (class_id, x1/w, y1/h, x2/w, y2/h, x3/w, y3/h, x4/w, y4/h), and I visualize the points as following.
![image](https://github.com/ultralytics/ultralytics/assets/31987475/69f2ba99-85a6-4ce4-a05e-f9aa6eaee38d)
But when I get the points info in training batch, the order of points has changed.
![image](https://github.com/ultralytics/ultralytics/assets/31987475/4f0bc8b5-6fd2-4ce7-84fe-858a25f27aef)
 I found that input are points(xyxyxyxy), when convert to xywhr (the radian r often be 1.5*).

**Comment by glenn-jocher** [comment]
@favorxin hello,

Thank you for the update and the additional details. It appears that the issue might be related to how the points are being processed or transformed during the conversion from the (xyxyxyxy) format to (xywhr). The change in the order of points and the radian value suggests there might be a transformation error in the conversion logic.

Could you please check the function or script handling this conversion to ensure that the coordinates are being correctly calculated and maintained in the proper order? It might also be helpful to add some logging at this step to trace how each coordinate is transformed throughout the process.

Let us know if you find anything unusual or if further assistance is needed!

**Comment by favorxin** [comment]
Hello!
1. I found loading the dataset in file (ultralytics/data/dataset.py) convert original segments points(N, 4, 2) to new segments (N, 100，2) in line 220 the update_labels_info function as shown following. 
![image](https://github.com/ultralytics/ultralytics/assets/31987475/e9fd5a31-c4ef-4495-afbb-d0f2810a049d)
2. After resampling segments, it will use xyxyxyxy2xywhr to convert instances.segments(N, 100, 2) to bboxes (xywhr N, 5) in line 1043 the function __call__ of the class Format (ultralytics/data/augment.py ).  Then the radian r will different from original segments(N, 4, 2)
![image](https://github.com/ultralytics/ultralytics/assets/31987475/87710fad-cae1-403f-aa65-148fc0c3e9fc)
Thank you for response.

**Comment by glenn-jocher** [comment]
@favorxin hello!

Thank you for the detailed observation. It seems like the resampling process in `update_labels_info` and the subsequent conversion in `Format.__call__` could indeed be affecting the integrity of the original segment data, particularly the radian values.

We appreciate you pointing this out. We'll review the mentioned functions to ensure that the transformations preserve the original data's accuracy more closely. Your input is invaluable in helping us improve YOLOv8.

If you have any more insights or suggestions, please feel free to share! 🚀

**Comment by favorxin** [comment]
Thanks!
I found that maybe two issues:
1. The xyxyxyxy2xywhr function in ultralytics/utils/ops.py use cv2.minAreaRect() may change the points' order.
2. When using the dataset transforms to flip left and right to up and down, the flipud and filplr will change the points' order in class Instances (in file ultralytics/utils/instance.py). 
I will check soon.

**Comment by glenn-jocher** [comment]
Hello @favorxin,

Great detective work! Identifying potential issues with the `xyxyxyxy2xywhr` function and the flipping transformations in the `Instances` class is a significant step towards resolving the bounding box discrepancies.

Your approach to further investigate these areas sounds excellent. Please keep us updated on your findings or if you need any further assistance. Your contributions are greatly helping to enhance the robustness of YOLOv8.

Looking forward to your updates! 🌟
