### ISSUE TITLE
How can I get FLOPs when I changed the model 

### ISSUE THREAD

**Issue by yaoergogo** [ultralytics/ultralytics#13351]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When I change the structure of the model and add new modules, how do I get the FLOPs of the model?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@yaoergogo to calculate the FLOPs (Floating Point Operations) of your modified YOLOv8 model, you can use the `benchmark` mode provided by Ultralytics. This mode not only measures the model's inference speed but also computes the FLOPs. Here’s how you can do it:

```bash
yolo benchmark model=path/to/your/custom_model.pt
```

This command will output the FLOPs along with other performance metrics. Make sure your model path is correctly specified. If you encounter any issues, feel free to share the error messages or details here! 🚀

**Comment by glenn-jocher** [comment]
@yaoergogo also just run `yolo predict model=YOUR_MODEL_HERE` and the FLOPs will be displayed before prediction.

**Comment by glenn-jocher** [comment]
@yaoergogo hello! To ensure you can view the FLOPs for your custom model with added blocks, you might need to make sure that the benchmarking tool recognizes these new components. If the standard `yolo benchmark` command isn't capturing the FLOPs due to the customizations, you may need to manually add support for these blocks in the benchmarking script.

You can do this by modifying the script to include calculations for the new operations introduced by your blocks. If you're not sure how to modify the script, you could provide details about the blocks you've added, and I can guide you on integrating them into the FLOP calculation process.

Let me know if you need further assistance or specific guidance on modifying the benchmark script!

**Comment by yaoergogo** [comment]
> 你好！为确保您可以查看添加模块的自定义模型的 FLOP，您可能需要确保基准测试工具识别这些新组件。如果标准命令由于自定义而无法捕获 FLOP，则可能需要在基准测试脚本中手动添加对这些块的支持。`yolo benchmark`
> 
> 为此，您可以修改脚本以包含模块引入的新操作的计算。如果您不确定如何修改脚本，可以提供有关已添加块的详细信息，我可以指导您将它们集成到 FLOP 计算过程中。
> 
> 如果您需要进一步的帮助或有关修改基准测试脚本的具体指导，请告诉我！

您好，我想知道我该怎么确保benchmark识别这些新组建，我添加了swin-transformer的模块，希望您可以知道我该怎么集成进去，谢谢~

**Comment by glenn-jocher** [comment]
@yaoergogo 您好！要确保 `yolo benchmark` 工具能识别并计算您添加的 swin-transformer 模块的 FLOPs，您需要在基准测试脚本中手动添加对这些新操作的支持。这通常涉及到扩展现有的 FLOP 计算逻辑以包括 swin-transformer 操作的特定计算。

如果您需要具体的代码修改指导，我可以帮助您理解 swin-transformer 模块中各个操作的计算方式，并指导您如何在脚本中实现这些计算。请准备好您的模块细节和当前的基准脚本，我们可以从那里开始。

期待您的回复，以便我们进一步协助！🚀

**Comment by yaoergogo** [comment]
> @yaoergogo 您好！要确保 `yolo benchmark` 工具能识别并计算您添加的 swin-transformer 模块的 FLOPs，您需要在基准测试脚本中手动添加对这些新操作的支持。这通常涉及到扩展现有的 FLOP 计算逻辑以包括 swin-transformer 操作的特定计算。
> 
> 如果您需要具体的代码修改指导，我可以帮助您理解 swin-transformer 模块中各个操作的计算方式，并指导您如何在脚本中实现这些计算。请准备好您的模块细节和当前的基准脚本，我们可以从那里开始。
> 
> 期待您的回复，以便我们进一步协助！🚀

import torch
from thop import clever_format, profile
from torchinfo import summary
from ultralytics import YOLO

if __name__ == "__main__":
    input_shape = [640, 640]
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    m = YOLO("/home/fby/YOLOv8-multi-trans/mid-transformer.yaml")
    dummy_input = torch.randn(1, 3, input_shape[0], input_shape[1]).to(device)
    flops, params = profile(m.to(device), (dummy_input), verbose=False)
    flops, params = clever_format([flops, params], "%.3f")
    print('Total GFLOPS: %s' % (flops))
    print('Total params: %s' % (params))

这是我的基准脚本

class WindowAttention(nn.Module):
 
    def __init__(self, dim, window_size, num_heads, qkv_bias=True, qk_scale=None, attn_drop=0., proj_drop=0.):
 
        super().__init__()
        self.dim = dim
        self.window_size = window_size  # Wh, Ww
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = qk_scale or head_dim ** -0.5
 
        # define a parameter table of relative position bias
        self.relative_position_bias_table = nn.Parameter(
            torch.zeros((2 * window_size[0] - 1) * (2 * window_size[1] - 1), num_heads))  # 2*Wh-1 * 2*Ww-1, nH
 
        # get pair-wise relative position index for each token inside the window
        coords_h = torch.arange(self.window_size[0])
        coords_w = torch.arange(self.window_size[1])
        coords = torch.stack(torch.meshgrid([coords_h, coords_w]))  # 2, Wh, Ww
        coords_flatten = torch.flatten(coords, 1)  # 2, Wh*Ww
        relative_coords = coords_flatten[:, :, None] - coords_flatten[:, None, :]  # 2, Wh*Ww, Wh*Ww
        relative_co ords = relative_coords.permute(1, 2, 0).contiguous()  # Wh*Ww, Wh*Ww, 2
        relative_coords[:, :, 0] += self.window_size[0] - 1  # shift to start from 0
        relative_coords[:, :, 1] += self.window_size[1] - 1
        relative_coords[:, :, 0] *= 2 * self.window_size[1] - 1
        relative_position_index = relative_coords.sum(-1)  # Wh*Ww, Wh*Ww
        self.register_buffer("relative_position_index", relative_position_index)
 
        self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)
 
        nn.init.normal_(self.relative_position_bias_table, std=.02)
        self.softmax = nn.Softmax(dim=-1)
 
    def forward(self, x, mask=None):
 
        B_, N, C = x.shape
        qkv = self.qkv(x).reshape(B_, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        q, k, v = qkv[0], qkv[1], qkv[2]  # make torchscript happy (cannot use tensor as tuple)
 
        q = q * self.scale
        attn = (q @ k.transpose(-2, -1))
 
        relative_position_bias = self.relative_position_bias_table[self.relative_position_index.view(-1)].view(
            self.window_size[0] * self.window_size[1], self.window_size[0] * self.window_size[1], -1)  # Wh*Ww,Wh*Ww,nH
        relative_position_bias = relative_position_bias.permute(2, 0, 1).contiguous()  # nH, Wh*Ww, Wh*Ww
        attn = attn + relative_position_bias.unsqueeze(0)
 
        if mask is not None:
            nW = mask.shape[0]
            attn = attn.view(B_ // nW, nW, self.num_heads, N, N) + mask.unsqueeze(1).unsqueeze(0)
            attn = attn.view(-1, self.num_heads, N, N)
            attn = self.softmax(attn)
        else:
            attn = self.softmax(attn)
 
        attn = self.attn_drop(attn)
 
        # print(attn.dtype, v.dtype)
        try:
            x = (attn @ v).transpose(1, 2).reshape(B_, N, C)
        except:
            # print(attn.dtype, v.dtype)
            x = (attn.half() @ v).transpose(1, 2).reshape(B_, N, C)
        x = self.proj(x)
        x = self.proj_drop(x)
        return x
 
 
class SwinTransformer(nn.Module):
    # CSP Bottleneck https://github.com/WongKinYiu/CrossStagePartialNetworks
    def __init__(self, c1, c2, n=1, shortcut=True, g=1, e=0.5):  # ch_in, ch_out, number, shortcut, groups, expansion
        super(SwinTransformer, self).__init__()
        c_ = int(c2 * e)  # hidden channels
        self.cv1 = Conv(c1, c_, 1, 1)
        self.cv2 = Conv(c1, c_, 1, 1)
        self.cv3 = Conv(2 * c_, c2, 1, 1)
        num_heads = c_ // 32
        self.m = SwinTransformerBlock(c_, c_, num_heads, n)
        # self.m = nn.Sequential(*[Bottleneck(c_, c_, shortcut, g, e=1.0) for _ in range(n)])
 
    def forward(self, x):
        y1 = self.m(self.cv1(x))
        y2 = self.cv2(x)
        return self.cv3(torch.cat((y1, y2), dim=1))
 
 
class SwinTransformerB(nn.Module):
    # CSP Bottleneck https://github.com/WongKinYiu/CrossStagePartialNetworks
    def __init__(self, c1, c2, n=1, shortcut=False, g=1, e=0.5):  # ch_in, ch_out, number, shortcut, groups, expansion
        super(Swin_Transformer_B, self).__init__()
        c_ = int(c2)  # hidden channels
        self.cv1 = Conv(c1, c_, 1, 1)
        self.cv2 = Conv(c_, c_, 1, 1)
        self.cv3 = Conv(2 * c_, c2, 1, 1)
        num_heads = c_ // 32
        self.m = SwinTransformerBlock(c_, c_, num_heads, n)
        # self.m = nn.Sequential(*[Bottleneck(c_, c_, shortcut, g, e=1.0) for _ in range(n)])
 
    def forward(self, x):
        x1 = self.cv1(x)
        y1 = self.m(x1)
        y2 = self.cv2(x1)
        return self.cv3(torch.cat((y1, y2), dim=1))
 
 
class SwinTransformerC(nn.Module):
    # CSP Bottleneck https://github.com/WongKinYiu/CrossStagePartialNetworks
    def __init__(self, c1, c2, n=1, shortcut=True, g=1, e=0.5):  # ch_in, ch_out, number, shortcut, groups, expansion
        super(Swin_Transformer_C, self).__init__()
        c_ = int(c2 * e)  # hidden channels
        self.cv1 = Conv(c1, c_, 1, 1)
        self.cv2 = Conv(c1, c_, 1, 1)
        self.cv3 = Conv(c_, c_, 1, 1)
        self.cv4 = Conv(2 * c_, c2, 1, 1)
        num_heads = c_ // 32
        self.m = SwinTransformerBlock(c_, c_, num_heads, n)
        # self.m = nn.Sequential(*[Bottleneck(c_, c_, shortcut, g, e=1.0) for _ in range(n)])
 
    def forward(self, x):
        y1 = self.cv3(self.m(self.cv1(x)))
        y2 = self.cv2(x)
        return self.cv4(torch.cat((y1, y2), dim=1))
 
 
class Mlp(nn.Module):
 
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.SiLU, drop=0.):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)
 
    def forward(self, x):
        x = self.fc1(x)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x
 
 
def window_partition(x, window_size):
    B, H, W, C = x.shape
    assert H % window_size == 0, 'feature map h and w can not divide by window size'
    x = x.view(B, H // window_size, window_size, W // window_size, window_size, C)
    windows = x.permute(0, 1, 3, 2, 4, 5).contiguous().view(-1, window_size, window_size, C)
    return windows
 
 
def window_reverse(windows, window_size, H, W):
    B = int(windows.shape[0] / (H * W / window_size / window_size))
    x = windows.view(B, H // window_size, W // window_size, window_size, window_size, -1)
    x = x.permute(0, 1, 3, 2, 4, 5).contiguous().view(B, H, W, -1)
    return x
 
 
class SwinTransformerLayer(nn.Module):
 
    def __init__(self, dim, num_heads, window_size=8, shift_size=0,
                 mlp_ratio=4., qkv_bias=True, qk_scale=None, drop=0., attn_drop=0., drop_path=0.,
                 act_layer=nn.SiLU, norm_layer=nn.LayerNorm):
        super().__init__()
        self.dim = dim
        self.num_heads = num_heads
        self.window_size = window_size
        self.shift_size = shift_size
        self.mlp_ratio = mlp_ratio
        # if min(self.input_resolution) <= self.window_size:
        #     # if window size is larger than input resolution, we don't partition windows
        #     self.shift_size = 0
        #     self.window_size = min(self.input_resolution)
        assert 0 <= self.shift_size < self.window_size, "shift_size must in 0-window_size"
        self.norm1 = norm_layer(dim)
        self.attn = WindowAttention(
            dim, window_size=(self.window_size, self.window_size), num_heads=num_heads,
            qkv_bias=qkv_bias, qk_scale=qk_scale, attn_drop=attn_drop, proj_drop=drop)
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.norm2 = norm_layer(dim)
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.mlp = Mlp(in_features=dim, hidden_features=mlp_hidden_dim, act_layer=act_layer, drop=drop)
    def create_mask(self, H, W):
        # calculate attention mask for SW-MSA
        img_mask = torch.zeros((1, H, W, 1))  # 1 H W 1
        h_slices = (slice(0, -self.window_size),
                    slice(-self.window_size, -self.shift_size),
                    slice(-self.shift_size, None))
        w_slices = (slice(0, -self.window_size),
                    slice(-self.window_size, -self.shift_size),
                    slice(-self.shift_size, None))
        cnt = 0
        for h in h_slices:
            for w in w_slices:
                img_mask[:, h, w, :] = cnt
                cnt += 1
        mask_windows = window_partition(img_mask, self.window_size)  # nW, window_size, window_size, 1
        mask_windows = mask_windows.view(-1, self.window_size * self.window_size)
        attn_mask = mask_windows.unsqueeze(1) - mask_windows.unsqueeze(2)
        attn_mask = attn_mask.masked_fill(attn_mask != 0, float(-100.0)).masked_fill(attn_mask == 0, float(0.0))
        return attn_mask
    def forward(self, x):
        # reshape x[b c h w] to x[b l c]
        _, _, H_, W_ = x.shape
        Padding = False
        if min(H_, W_) < self.window_size or H_ % self.window_size != 0 or W_ % self.window_size != 0:
            Padding = True
            # print(f'img_size {min(H_, W_)} is less than (or not divided by) window_size {self.window_size}, Padding.')
            pad_r = (self.window_size - W_ % self.window_size) % self.window_size
            pad_b = (self.window_size - H_ % self.window_size) % self.window_size
            x = F.pad(x, (0, pad_r, 0, pad_b))
        # print('2', x.shape)
        B, C, H, W = x.shape
        L = H * W
        x = x.permute(0, 2, 3, 1).contiguous().view(B, L, C)  # b, L, c
        # create mask from init to forward
        if self.shift_size > 0:
            attn_mask = self.create_mask(H, W).to(x.device)
        else:
            attn_mask = None
        shortcut = x
        x = self.norm1(x)
        x = x.view(B, H, W, C)
        # cyclic shift
        if self.shift_size > 0:
            shifted_x = torch.roll(x, shifts=(-self.shift_size, -self.shift_size), dims=(1, 2))
        else:
            shifted_x = x
        # partition windows
        x_windows = window_partition(shifted_x, self.window_size)  # nW*B, window_size, window_size, C
        x_windows = x_windows.view(-1, self.window_size * self.window_size, C)  # nW*B, window_size*window_size, C
        # W-MSA/SW-MSA
        attn_windows = self.attn(x_windows, mask=attn_mask)  # nW*B, window_size*window_size, C
        # merge windows
        attn_windows = attn_windows.view(-1, self.window_size, self.window_size, C)
        shifted_x = window_reverse(attn_windows, self.window_size, H, W)  # B H' W' C
        # reverse cyclic shift
        if self.shift_size > 0:
            x = torch.roll(shifted_x, shifts=(self.shift_size, self.shift_size), dims=(1, 2))
        else:
            x = shifted_x
        x = x.view(B, H * W, C)
        # FFN
        x = shortcut + self.drop_path(x)
        x = x + self.drop_path(self.mlp(self.norm2(x)))
        x = x.permute(0, 2, 1).contiguous().view(-1, C, H, W)  # b c h w
        if Padding:
            x = x[:, :, :H_, :W_]  # reverse padding
        return x
class SwinTransformerBlock(nn.Module):
    def __init__(self, c1, c2, num_heads, num_layers, window_size=8):
        super().__init__()
        self.conv = None
        if c1 != c2:
            self.conv = Conv(c1, c2)
        # remove input_resolution
        self.blocks = nn.Sequential(*[SwinTransformerLayer(dim=c2, num_heads=num_heads, window_size=window_size,
                                                           shift_size=0 if (i % 2 == 0) else window_size // 2) for i in
                                      range(num_layers)])
    def forward(self, x):
        if self.conv is not None:
            x = self.conv(x)
        x = self.blocks(x)
        return x

这是我的模块代码
我找到了相关模块代码
![image](https://github.com/ultralytics/ultralytics/assets/118654036/b54dd178-b443-40d5-83d7-86fda3e54666)
想知道我的swin-transformer模块应该怎么导入呢

**Comment by glenn-jocher** [comment]
@yaoergogo 您好！感谢您提供详细的代码和基准脚本。为了确保 `yolo benchmark` 工具能够识别并计算您添加的 Swin-Transformer 模块的 FLOPs，您需要在基准测试脚本中手动添加对这些新操作的支持。以下是您可以采取的步骤：

1. **安装 `thop` 库**：`thop` 是一个用于计算 PyTorch 模型 FLOPs 的库。您已经在脚本中使用了它，但请确保它已安装。
    ```bash
    pip install thop
    ```

2. **修改基准脚本**：确保您的基准脚本能够正确处理 Swin-Transformer 模块。以下是一个示例脚本，展示了如何计算 FLOPs 和参数：

    ```python
    import torch
    from thop import clever_format, profile
    from ultralytics import YOLO

    # 定义 Swin-Transformer 模块
    class SwinTransformerBlock(nn.Module):
        def __init__(self, c1, c2, num_heads, num_layers, window_size=8):
            super().__init__()
            self.conv = None
            if c1 != c2:
                self.conv = Conv(c1, c2)
            self.blocks = nn.Sequential(*[SwinTransformerLayer(dim=c2, num_heads=num_heads, window_size=window_size,
                                                               shift_size=0 if (i % 2 == 0) else window_size // 2) for i in
                                          range(num_layers)])

        def forward(self, x):
            if self.conv is not None:
                x = self.conv(x)
            x = self.blocks(x)
            return x

    # 定义模型
    class CustomModel(nn.Module):
        def __init__(self):
            super(CustomModel, self).__init__()
            self.backbone = YOLO('mydata.yaml').model
            self.swin_transformer = SwinTransformerBlock(c1=256, c2=512, num_heads=8, num_layers=2)

        def forward(self, x):
            x = self.backbone(x)
            x = self.swin_transformer(x)
            return x

    if __name__ == "__main__":
        input_shape = [640, 640]
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        model = CustomModel().to(device)
        dummy_input = torch.randn(1, 3, input_shape[0], input_shape[1]).to(device)
        flops, params = profile(model, inputs=(dummy_input,), verbose=False)
        flops, params = clever_format([flops, params], "%.3f")
        print('Total GFLOPS: %s' % (flops))
        print('Total params: %s' % (params))
    ```

3. **运行基准测试脚本**：运行上述脚本以计算您的自定义模型的 FLOPs 和参数。

    ```bash
    python benchmark.py
    ```

通过这些步骤，您应该能够成功计算包含 Swin-Transformer 模块的自定义模型的 FLOPs。如果您在此过程中遇到任何问题，请随时告知我们！🚀
