### ISSUE TITLE
YOLOv8.pt - onnx to param & bin have different format

### ISSUE THREAD

**Issue by larrywal-express** [ultralytics/ultralytics#1336]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

[file.txt](https://github.com/ultralytics/ultralytics/files/10927407/file.txt)
I converted my yolov8n.pt to onnx to param & bin successfully. However, my obtained param format is different as attached. Can you please provide me the solution to this problem. Thanks.

**Comment by glenn-jocher** [comment]
@larrywal-express ONNX export and usage examples all work correctly as you can see from our green badge above (ONNX is part of our tests). If you have a reproducible example please provide a minimum reproducible example following https://stackoverflow.com/help/minimal-reproducible-example
