### ISSUE TITLE
YOLOv9 and YOLOv10

### ISSUE THREAD

**Issue by ZeeRizvee** [ultralytics/ultralytics#13369]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi. The pre-trained weights for YOLOv9s and YOLOv10s are not currently provided. Can you please give an idea when they will be made available?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! Thank you for reaching out regarding the pre-trained weights for YOLOv9 and YOLOv10. As of now, we don't have a specific timeline for when these weights will be available. We recommend keeping an eye on our GitHub repository for updates. Your interest in these models is greatly appreciated, and we'll make sure to communicate any updates as they become available. If you have any more questions or need further assistance, feel free to ask. Happy coding! 🚀

**Comment by HeadTriXz** [comment]
> Hello! Thank you for reaching out regarding the pre-trained weights for YOLOv9 and YOLOv10. As of now, we don't have a specific timeline for when these weights will be available. We recommend keeping an eye on our GitHub repository for updates. Your interest in these models is greatly appreciated, and we'll make sure to communicate any updates as they become available. If you have any more questions or need further assistance, feel free to ask. Happy coding! 🚀

YOLOv9's pretrained models are now available.

**Comment by glenn-jocher** [comment]
Hello! Thanks for the update. We appreciate your contribution to keeping the community informed. For those interested, you can now access the YOLOv9 pretrained models. If there are any further questions or additional assistance needed, please don't hesitate to reach out. Happy coding! 🚀

**Comment by ZeeRizvee** [comment]
@HeadTriXz not all YOLOv9 models are available yet. I was specifically looking for YOLOv9s

**Comment by HeadTriXz** [comment]
> @HeadTriXz not all YOLOv9 models are available yet. I was specifically looking for YOLOv9s

I meant that the YOLOv9 models are available in the official repo from WongKinYiu (since a day or two). Ultralytics doesn't seem to have any support for them yet, however.

**Comment by ZeeRizvee** [comment]
> > @HeadTriXz not all YOLOv9 models are available yet. I was specifically looking for YOLOv9s
> 
> I meant that the YOLOv9 models are available in the official repo from WongKinYiu (since a day or two). Ultralytics doesn't seem to have any support for them yet, however.

Ohh I see what you mean. Thanks for letting me know! I did run training using YOLOv9c under Ultralytics package and it was working fine. Seems like I will have to wait for Ultralytics to release the other pre-trained weights before I can use them with the Ultralytics library.

**Comment by mpolinowski** [comment]
The missing scales are [now added](https://github.com/ultralytics/ultralytics/releases/tag/v8.2.35). But I am getting an error message when I try to import them. To reproduce:

1. Download weights

```
!wget -P weights https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov9t.pt
!wget -P weights https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov9s.pt
!wget -P weights https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov9m.pt
!wget -P weights https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov9c.pt
````

2. Update the installation:

```
pip install --upgrade ultralytics huggingface_hub dill

...

Installing collected packages: dill, huggingface_hub, ultralytics
  Attempting uninstall: ultralytics
    Found existing installation: ultralytics 8.1.34
    Uninstalling ultralytics-8.1.34:
      Successfully uninstalled ultralytics-8.1.34
Successfully installed dill-0.3.8 huggingface_hub-0.23.4 ultralytics-8.2.35
```

2. Load the `yolov9c.pt` or `yolov9e.pt` weights works - no error message:

```
model_9c = YOLO("weights/yolov9c.pt") 
```

3. Loading `yolov9t.pt`, `yolov9s.pt` or `yolov9m.pt` weights gives me an error message:

```
model_9t = YOLO("weights/yolov9t.pt")
```

```
AttributeError: Can't get attribute 'AConv' on <module 'ultralytics.nn.modules.block' from '/opt/conda/lib/python3.10/site-packages/ultralytics/nn/modules/block.py'>
```

Complete error log:

https://gist.github.com/mpolinowski/03af35d278834055709dba18889fdb59


Anyone else running into this?

**Comment by glenn-jocher** [comment]
Hello @mpolinowski,

Thank you for bringing this to our attention and for providing a detailed reproducible example. It’s very helpful!

It seems like the issue might be related to the recent updates in the Ultralytics package. Here are a few steps you can try to resolve this:

1. **Ensure Latest Versions**: Verify that you are using the most recent versions of both `torch` and `ultralytics`. You can update them using the following commands:
    ```bash
    pip install --upgrade torch ultralytics
    ```

2. **Clear Cache**: Sometimes, clearing the cache can help resolve such issues. You can clear the cache by running:
    ```bash
    pip cache purge
    ```

3. **Reinstall Ultralytics**: Try uninstalling and then reinstalling the Ultralytics package to ensure a clean installation:
    ```bash
    pip uninstall ultralytics
    pip install ultralytics
    ```

4. **Check for Model Compatibility**: Ensure that the models you are trying to load are compatible with the current version of the Ultralytics package. Sometimes, models from different versions might not be fully compatible.

If the issue persists after trying the above steps, please let us know. We will investigate further to find a solution.

Thank you for your patience and understanding. If you have any more questions or need further assistance, feel free to ask. Happy coding! 🚀

**Comment by mpolinowski** [comment]
Hmm - I am using a pyTorch container with a Jupyter notebook. I just tried to run it outside of my container without the notebook and it worked:

```
pip install --upgrade torch ultralytics huggingface_hub dill

Installing collected packages: py-cpuinfo, mpmath, sympy, scipy, pyparsing, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, networkx, kiwisolver, fsspec, fonttools, dill, cycler, contourpy, nvidia-cusparse-cu12, nvidia-cudnn-cu12, matplotlib, huggingface_hub, seaborn, nvidia-cusolver-cu12, torch, ultralytics-thop, torchvision, ultralytics
Successfully installed contourpy-1.2.1 cycler-0.12.1 dill-0.3.8 fonttools-4.53.0 fsspec-2024.6.0 huggingface_hub-0.23.4 kiwisolver-1.4.5 matplotlib-3.9.0 mpmath-1.3.0 networkx-3.3 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvjitlink-cu12-12.5.40 nvidia-nvtx-cu12-12.1.105 py-cpuinfo-9.0.0 pyparsing-3.1.2 scipy-1.13.1 seaborn-0.13.2 sympy-1.12.1 torch-2.3.1 torchvision-0.18.1 ultralytics-8.2.35 ultralytics-thop-2.0.0
```

```
❯ cat ./yolo.py
import torch
from ultralytics import YOLO

model_9c = YOLO("yolov9c.pt")

❯ python ./yolo.py
Downloading https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov9c.pt to 'yolov9c.pt'...
100%|████████████████████████████████████████████████████████████████████████████| 49.4M/49.4M [00:05<00:00, 10.1MB/s]

❯ cat ./yolo.py
import torch
from ultralytics import YOLO

model_9s = YOLO("yolov9s.pt")

❯ python ./yolo.py
Downloading https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov9s.pt to 'yolov9s.pt'...
100%|████████████████████████████████████████████████████████████████████████████| 14.6M/14.6M [00:03<00:00, 4.07MB/s]

❯ cat ./yolo.py
import torch
from ultralytics import YOLO

model_9t = YOLO("yolov9t.pt")

❯ python ./yolo.py
Downloading https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov9t.pt to 'yolov9t.pt'...
100%|█████████████████████████████████████████████████████████████████████████████| 4.70M/4.70M [00:05<00:00, 868kB/s]
```

I will look into it  ¯\\_ (ツ)_/¯ The only think I did not try inside the container was updating torch. I will give feedback when I get it to work.

**Comment by glenn-jocher** [comment]
Hello @mpolinowski,

Thank you for the detailed follow-up and for sharing your findings! It’s great to hear that updating the dependencies, especially `torch`, resolved the issue within your Docker container. 🎉

For others who might encounter similar issues, here are a few key steps to ensure smooth operation:

1. **Ensure Latest Versions**: Always make sure you are using the latest versions of `torch` and `ultralytics`. You can update them using:
    ```bash
    pip install --upgrade torch ultralytics
    ```

2. **Rebuild Docker Container**: If you are using a Docker container, rebuilding it with updated dependencies can often resolve compatibility issues.

3. **Check Environment**: Verify that your environment (whether it’s a Jupyter notebook, Docker container, or local setup) is correctly configured and that all necessary packages are installed.

If anyone else experiences similar issues, please ensure you follow these steps. If the problem persists, feel free to provide a minimum reproducible example so we can investigate further. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Thank you for your patience and for contributing to the community. If you have any more questions or need further assistance, feel free to ask. Happy coding! 🚀
