### ISSUE TITLE
Comet ML Integration for Hyperparameter Tuning

### ISSUE THREAD

**Issue by wereign** [ultralytics/ultralytics#13377]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Aloha Folks!

CometML has been my platform of choice for experiment tracking till now, and since I have multiple runs, I had an entire pipeline setup for setting the name of the projects and experiments.

When using the hyperparameter tuning, this pipelines becomes useless as the tuner is automatically creating cometml experiments per iteration of the tuning procedure.

There are three relatively straightforward methods I can think of:
1. Pass in the arguments for setting up the experiment attributes 
2. Pass in a function that constructs and returns the experiment that can be used for logging
3. Use the project name set + indexing as the comet ml experiment name 

The inability is however not restricted to the naming. It also applies to other configurations for the experiment made in the script.

For example, if my script sets a different API Key than the one set in the environment variable, the experiment i start in my code will follow the api key I have set, but the tuning iterations will use the comet api key in the environment variable, which is inconsistent

I do believe this is a vital part of making the comet ml integration useful to organizations and teams that perform hyperparameter tuning, as it will allow us to organize and view the results from the tuning in a better way

**Comment by glenn-jocher** [comment]
@wereign aloha!

Thank you for your detailed inquiry regarding the integration of Comet ML with YOLOv8 for hyperparameter tuning. Your suggestions for enhancing the flexibility of experiment tracking during the tuning process are indeed valuable.

Currently, the Comet ML integration with our YOLOv8 models does not directly support custom configurations for each tuning iteration out-of-the-box. However, your proposed methods are interesting and could potentially be implemented as enhancements to our existing framework.

For now, as a workaround, you might consider manually controlling the experiment creation within your tuning loop by using the Comet ML API directly in your script. This way, you can set custom names, API keys, or any other configuration parameters for each experiment iteration.

We appreciate your feedback as it helps us improve the integration features. I'll forward your suggestions to our development team for consideration in future updates.

Thank you for using Ultralytics YOLO models and for your proactive approach to enhancing the toolset!
