### ISSUE TITLE
Error when installing and importing ultralytics==8.0.20

### ISSUE THREAD

**Issue by loucif01** [ultralytics/ultralytics#1337]
### Search before asking

- [ ] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

OSError: symbol cublasLtHSHMatmulAlgoInit, version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

### Environment

ultralytics==8.0.20
Python==3.10

### Additional

I tried other version also of ultralytics, but still same error.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Although this seems unrelated, but you're using an older version of the package. Please upgrade using `pip install --upgrade ultralytics`
I think the underlying problem here is the CUDA installation. You might have some issues there. Try installing CUDA if the issue still persists after upgrading the package

**Comment by adnanahmad339** [comment]
@AyushExel Hi bro! 
In am facing an issue while installing requirement.txt file for YOLOv5 on Jetson nano. 

It throws the error:
**ERROR: Couldn't find a version that satisfies the requirement ultralytics(from version: none)
 ERROR: NO matching distribution found for ultralytics** 

I tried to install using **pip3 install ultralytics** , **python3 -m pip install ultralytics** and **pip3 install ultralytics --user**. But couldn't install. Please help me!

**Comment by adnanahmad339** [comment]
@AyushExel nope. It didn't work for me. I think i had to upgrade to python version 3.7 for installing ultralytics. But i am using 3.6.9. 

Well my model just got deployed few minutes ago. I downgraded the Yolov5 repo using **git checkout v7.0**. And then i bypass the ultralytics library installation.

**Comment by glenn-jocher** [comment]
@adnanahmad339 thank you for your response. 

Yes, upgrading your Python version to 3.7 or higher may resolve the issue. However, I'm glad to hear that you were able to successfully deploy your model by checking out the v7.0 version of the YOLOv5 repository and bypassing installation of the Ultralytics library. 

If you encounter any further issues or have any questions, please feel free to reach out to the YOLOv8 community. We are always happy to help!

**Comment by huazihang1** [comment]
ubuntu18.04 cuda10.2 torch1.7.1 pip3 install ultralytics、python3 -m pip install ultralytics和pip3 install ultralytics --user都试过无法装ultralytics，是版本问题吗

**Comment by glenn-jocher** [comment]
@huazihang1 根据你的描述和你正在使用的环境，问题可能是由于Python版本太旧。 `ultralytics`需要Python 3.7或更高版本才能正常工作，你所使用的Ubuntu 18.04可能默认安装的是Python 3.6。

为了解决此问题，你可能需要升级你的Python版本到3.7或更高。可以通过下载并安装官方的Python发行版或使用`pyenv`等工具来管理你的Python版本。

另外，记得在安装了新的Python版本后，再次运行`pip install --upgrade pip`来确保你的pip版本也是最新的，这可能有助于解决一些安装问题。如果你仍然遇到问题，欢迎随时向我们反馈。
