### ISSUE TITLE
Does the Benchmarks changed According yolov8.2 changed

### ISSUE THREAD

**Issue by sulaiman1988** [ultralytics/ultralytics#13378]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Related different updated on yolov8.1 performance so does the becnchmark metrics updated 
![image](https://github.com/ultralytics/ultralytics/assets/89999880/34be818b-bb70-43a7-a24f-511e8c569953)

**Comment by glenn-jocher** [comment]
Hello! Thank you for reaching out with your question.

Yes, with each update to the YOLOv8 models, including the transition from YOLOv8.1 to YOLOv8.2, the benchmark metrics are typically updated to reflect performance changes. These updates ensure that the benchmarks accurately represent the improvements or modifications made in the latest version of the model.

For the most current benchmark results and details on how they may have changed with YOLOv8.2, I recommend checking the latest documentation and release notes associated with the new model version.

If you have any more questions or need further assistance, feel free to ask. Happy coding!

**Comment by sulaiman1988** [comment]
BTW I checked the documentation but I didn't find what I need as numbers like what in image above
