### ISSUE TITLE
Font Size not Working

### ISSUE THREAD

**Issue by Crear12** [ultralytics/ultralytics#13386]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

The fonts are too big and occluded with each other. I tried to pass a "font_size=1.0" into the plot (following this: https://github.com/ultralytics/ultralytics/issues/9094), but it doesn't work (neither does font).
<img width="1629" alt="Screenshot 2024-06-05 at 09 52 59" src="https://github.com/ultralytics/ultralytics/assets/39162855/ca0fa65d-bff5-4598-9ea8-92d09e0a3870">

### Environment

Ultralytics YOLOv8.2.28 🚀 Python-3.11.5 torch-2.3.0 MPS (Apple M1 Max)
YOLOv8x summary (fused): 268 layers, 68200608 parameters, 0 gradients, 257.8 GFLOPs

### Minimal Reproducible Example

```
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 tracking on the frame, persisting tracks between frames
        results = model.track(frame, persist=True,device="mps")

        # Visualize the results on the frame
        annotated_frame = results[0].plot(font_size=10)
        annotated_frame_5 = results[0].plot(font_size=5)
        # Write the annotated frame to the output video
        cv2.imshow("YOLOv8 Tracking with Font Size: 10", annotated_frame)
        cv2.imshow("YOLOv8 Tracking with Font Size: 5", annotated_frame_5)
        
        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! Thanks for reaching out and providing detailed information about the issue you're experiencing with the `font_size` parameter in the `plot()` method.

It seems like there might be a misunderstanding or an issue with how the `font_size` is being applied. The `font_size` parameter should indeed control the size of the text in the plot, and your usage appears correct based on your script.

To help resolve this, could you please try the following:
1. Ensure that there are no local overrides or modifications in your environment that could affect the rendering of the font sizes.
2. Check if updating to the latest version of the Ultralytics YOLOv8 library helps, as there might have been fixes or improvements related to this issue.

If the problem persists, it would be helpful if you could open an issue on our GitHub with this detailed description and any additional observations you might have. This will allow our development team to investigate further and provide a fix or a workaround.

Thank you for using Ultralytics YOLO, and we appreciate your contribution to improving the library! 🚀

**Comment by Crear12** [comment]
> Hello! Thanks for reaching out and providing detailed information about the issue you're experiencing with the `font_size` parameter in the `plot()` method.
> 
> It seems like there might be a misunderstanding or an issue with how the `font_size` is being applied. The `font_size` parameter should indeed control the size of the text in the plot, and your usage appears correct based on your script.
> 
> To help resolve this, could you please try the following:
> 
> 1. Ensure that there are no local overrides or modifications in your environment that could affect the rendering of the font sizes.
> 2. Check if updating to the latest version of the Ultralytics YOLOv8 library helps, as there might have been fixes or improvements related to this issue.
> 
> If the problem persists, it would be helpful if you could open an issue on our GitHub with this detailed description and any additional observations you might have. This will allow our development team to investigate further and provide a fix or a workaround.
> 
> Thank you for using Ultralytics YOLO, and we appreciate your contribution to improving the library! 🚀

Thanks for responding!
I tested it on two different computers (Windows and macOS) with latest ultralytics (pip install —upgrade ultralytics), both of them seem to have this issue. I’ve not manually configured anything so I’m not sure if there are any “local overrides or modifications in your environment”, and I don’t know how to check if there are any…

**Comment by glenn-jocher** [comment]
Thank you for the update and for checking the installation on different systems.

To further diagnose the issue, could you please verify the following:
- Ensure no custom configurations in your Python environment might be influencing the `plot()` behavior. A fresh virtual environment could help isolate the issue.
- Check if any console warnings or errors appear that might give us more insight.

If the issue remains unresolved, please consider opening a detailed issue on our GitHub repository. This will allow our team to replicate the problem and work on a targeted solution.

We appreciate your efforts in helping us enhance the YOLOv8 experience! 🌟

**Comment by Crear12** [comment]
Look at this. I'm using Colab with the code here:

import cv2
from ultralytics import YOLO
from google.colab.patches import cv2_imshow

# Load the YOLOv8 model
model = YOLO("yolov8x.pt")
video_path = "https://njtpk-wink.xcmdata.org/njta/203/public/hls/WF05-24AF-4D24-2558-F999_nj.m3u8"
cap = cv2.VideoCapture(video_path)

# Get the width, height, and frame rate of the video
frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
frame_rate = int(cap.get(cv2.CAP_PROP_FPS))

# annotator = Annotator(font_size=0.0000001, font="Times New Roman")
# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 tracking on the frame, persisting tracks between frames
        results = model.track(frame, persist=True,device="cuda")

        # Visualize the results on the frame
        annotated_frame = results[0].plot(font_size=100)
        annotated_frame_5 = results[0].plot(font_size=5)
        # Write the annotated frame to the output video
                # Display the annotated frame
        cv2_imshow(annotated_frame)
        cv2_imshow(annotated_frame_5)

    else:
        # Break the loop if the end of the video is reached
        break

![Screenshot 2024-06-06 at 00 25 01](https://github.com/ultralytics/ultralytics/assets/39162855/53bf0e6f-d063-49ae-9e3b-f98ae082dee2)

I'd appreciate it if I can find any successful results from Github. I need to know what works and how it should look like.

**Comment by glenn-jocher** [comment]
Hello! Thanks for sharing your code snippet and the details of your setup on Colab. It looks like you're doing everything right to visualize the tracking results using YOLOv8.

From your screenshot and description, if you're not seeing the expected results or if the font sizes are not adjusting as intended, it might be due to how the `plot()` function is handling the `font_size` parameter in the Colab environment.

A few suggestions:
- Ensure that the `font_size` values are within a reasonable range for your video's resolution. Extreme values might cause display issues.
- If the issue persists, consider testing with default settings (without setting `font_size`) to see if the annotations display correctly.
- It might also be helpful to check if there are any errors or warnings in the output that could give more insight into what might be going wrong.

If you continue to face difficulties, please feel free to open an issue on our GitHub repository with these details, and we'll look into it further. Your feedback is invaluable in improving YOLOv8, and we're here to help you get the best results possible! 🚀
