### ISSUE TITLE
python train.py but didn't get the right parameters what I set in default.yaml

### ISSUE THREAD

**Issue by MangoloD** [ultralytics/ultralytics#1338]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I try to execute the file in this way： `python train.py`，I found that I didn't get the parameters which I have set. 
I found those parameters  are default parameters.
![SY{%J236@@IWNN7)3%X7U1B](https://user-images.githubusercontent.com/52820275/223918130-cb4250a7-c13e-4c7a-9905-95df22fb2d54.png)
my default.yaml：
![image](https://user-images.githubusercontent.com/52820275/223918283-98a7a5e9-612c-487f-8421-6a18947cd533.png)

So，how can I use this way to train by my own parameters

**Comment by AyushExel** [comment]
You're using the python script which is causing problems. The intended way to use the commandline is to install the package. 
`pip install ultralytics` and then follow the commandline usage here - https://docs.ultralytics.com/cli/

**Comment by MangoloD** [comment]
> You're using the python script which is causing problems. The intended way to use the commandline is to install the package. `pip install ultralytics` and then follow the commandline usage here - https://docs.ultralytics.com/cli/

I know what you mean. It can be worked correctly with `yolo` command.
```bash
yolo task=detect    mode=train    model=yolov8n.pt        args...
          classify       predict        yolov8n-cls.yaml  args...
          segment        val            yolov8n-seg.yaml  args...
                         export         yolov8n.pt        format=onnx  args...
```

But how can I use `python train.py` command to run correctly in the directory where the file( `train.py`) is located.

It seems that this command can't get the parameters from `default.yaml` which I have modified .
