### ISSUE TITLE
Add support for `bitsandbytes` 8-bit optimizers

### ISSUE THREAD

**Issue by umarbutler** [ultralytics/ultralytics#13383]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I would like to request that support be added for [`bitsandbytes` 8-bit optimizers](https://huggingface.co/docs/bitsandbytes/main/en/index) which are much more memory efficient and faster than standard 32-bit optimizers yet come at no performance cost.

At present, it is actually possible to use `bitsandbytes` optimizers by hackily overwriting standard `torch` optimizers like so:
```py
import torch
import bitsandbytes

torch.optim.SGD = bitsandbytes.optim.SGD8bit
torch.optim.Adam = bitsandbytes.optim.Adam8bit
torch.optim.AdamW = bitsandbytes.optim.AdamW8bit
torch.optim.RMSprop = bitsandbytes.optim.RMSprop8bit

from ultralytics import YOLO
```

### Use case

It would be used to replace standard 32-bit implementations of popular `torch` optimizers and thereby speed up training.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Thank you for your suggestion and willingness to contribute to the Ultralytics repository! 🚀

Integrating `bitsandbytes` 8-bit optimizers sounds like a promising enhancement for optimizing memory usage and speeding up training without sacrificing performance. Your approach to overwrite standard `torch` optimizers is quite innovative.

We welcome your contribution! Please feel free to submit a PR with your proposed changes. Make sure to include any necessary documentation updates and unit tests to ensure compatibility and stability. If you need any guidance or have further questions as you work on your PR, don't hesitate to reach out.

Looking forward to your contribution!
