### ISSUE TITLE
Extract and save faces without duplication with yolov8

### ISSUE THREAD

**Issue by Rasantis** [ultralytics/ultralytics#13394]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I need a yolov8 script that detects the face and extracts it but with as little duplication as possible? someone have a code snippet or something that can help ? I alredy have my face.pt model trained

**Comment by glenn-jocher** [comment]
Hello! 👋

To achieve face detection and extraction with minimal duplication using your trained `face.pt` model, you can utilize the `predict` mode of YOLOv8. Here's a basic script snippet that might help:

```python
from ultralytics import YOLO
import numpy as np

# Load your trained model
model = YOLO('path/to/face.pt')

# Run prediction on an image or video
results = model('path/to/image_or_video.jpg')

# Extract faces without duplication
faces = []
seen = set()
for result in results:
    if result.boxes:
        for box in result.boxes.xyxy:
            # Create a hashable representation of the box
            box_tuple = tuple(map(int, box.tolist()))
            if box_tuple not in seen:
                seen.add(box_tuple)
                face = results.orig_img[int(box[1]):int(box[3]), int(box[0]):int(box[2])]
                faces.append(face)

# Now you can use the faces list as needed
```

This script checks for unique bounding boxes before extracting the face, which helps in reducing duplicates. Adjust the paths and parameters as necessary for your specific setup.

Hope this helps! Let us know if you have any more questions. 😊
