### ISSUE TITLE
Can I use YOLOv8 in back-end (not Python)?

### ISSUE THREAD

**Issue by MikeHawkIsGold** [ultralytics/ultralytics#1339]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I get a video from front-end (web), receive it by back-end like springboot(JAVA) or nodejs(JavaScript). Then use YOLOv8 to predict the video, after that I export the result to web.
So I must use YOLOv8 by back-end and pass some parameters to YOLOv8. However I notice that docs say I could only use that by Python or CLI. So what could I do? Should I just use JAVA to call a Python file or CLI to use YOLOv8?

**Comment by salt00n9** [comment]
CLI will also use python, i think you have to make your backend ready with python and the requirements.
After that you have 2 ways to achieve this:

1- receive the video using java and save it somewhere, then call the CLI command using java, this will save results ( --save-txt)
and you can read the txt file for detections using java.

2- create a python script that scans a folder for new videos and runs yolov8 on the video.

**Comment by MikeHawkIsGold** [comment]
I use node.js and multer to send parameters to Python file but it did not work. So I give up using js or Java, instead of Flask...

**Comment by pderrenger** [comment]
@s3xysteak flask is a feasible approach for integrating YOLOv8 into your backend. You can use Flask to create a Python web application, receive the video using routes, and then process the video with YOLOv8. This way, you can avoid the complications of integrating YOLOv8 directly into Java or Node.js, and seamlessly transfer the results back to your front-end. Keep in mind that YOLOv8 can be seamlessly integrated into your Flask app for streamlined video processing.
