### ISSUE TITLE
TypeError: model='yolov8x.yaml' is not a supported model format.

### ISSUE THREAD

**Issue by chenganhsieh** [ultralytics/ultralytics#13395]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

train

### Bug
When I use the wandb callback and only load 'yolov8x.yaml', it shows the error: TypeError: model='yolov8x.yaml' is not a supported model format.

### Minimal Reproducible Example

```
model = YOLO("yolov8x.yaml")
add_wandb_callback(model, enable_model_checkpointing=True)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! It looks like you're trying to load a model configuration file directly as a model. In YOLOv8, you should first build the model from the YAML configuration and then load the pretrained weights if necessary. Here’s how you can adjust your code:

```python
model = YOLO('yolov8x.yaml')  # Build a new model from YAML
model = model.load('yolov8x.pt')  # Optionally load pretrained weights
add_wandb_callback(model, enable_model_checkpointing=True)
```

Make sure you have the corresponding `.pt` file for the pretrained weights if you choose to load them. If you're starting training from scratch, you can omit the `.load()` part. Let me know if this helps or if you have any more questions! 😊

**Comment by chenganhsieh** [comment]
Yes, I want to train the model from scratch. But if I omit the `.load()` part, it shows the error:
 `TypeError: model='yolov8x.yaml' is not a supported model format.`

Here is my code:
```python
# Load a model
model = YOLO("yolov8x.yaml")
add_wandb_callback(model, enable_model_checkpointing=True)

params = {
    'project':'ACNE',
    'data':'data/ACNE/data.yaml',
    'imgsz':640,
    'batch':16,
    'epochs':100,
    'optimizer':'Adam',
    'pretrained':False,
    'lr0': 0.001,
    'lrf': 0.00001,
    'cos_lr': True,
    'single_cls': True
}
model.train(**params)
```

My ultralytics version is 8.2.28

**Comment by glenn-jocher** [comment]
@chenganhsieh hello! It seems like there might be a misunderstanding in the model instantiation process. When you're initializing a model to train from scratch using a YAML configuration file, make sure that the YAML file is correctly formatted and located. Here's how you should structure your code:

```python
from ultralytics import YOLO

# Build a new model from YAML
model = YOLO('yolov8x.yaml')

# Add wandb callback
add_wandb_callback(model, enable_model_checkpointing=True)

# Set training parameters
params = {
    'project': 'ACNE',
    'data': 'data/ACNE/data.yaml',
    'imgsz': 640,
    'batch': 16,
    'epochs': 100,
    'optimizer': 'Adam',
    'pretrained': False,  # Ensure this is set to False for training from scratch
    'lr0': 0.001,
    'lrf': 0.00001,
    'cos_lr': True,
    'single_cls': True
}

# Start training
model.train(**params)
```

Please ensure that your `yolov8x.yaml` file is in the correct directory and properly formatted. If the issue persists, it might be helpful to check the YAML file for any syntax errors or misconfigurations. Let me know if this resolves the issue or if you need further assistance!

**Comment by trantuankhoi** [comment]
Hi @chenganhsieh, have you resolved this issue?

**Comment by trantuankhoi** [comment]
I found that `wandb` causes this issue. 
You can work around it by downgrading `ultralytics` version to the versions was supported by `wandb` or use another visualizer

**Comment by pderrenger** [comment]
Thank you for your input. To address this issue, please ensure you are using the latest versions of both `ultralytics` and `wandb`. Compatibility issues can often be resolved by updating to the most recent releases. If the problem persists, consider using an alternative visualization tool as a temporary workaround. Let us know if you need further assistance.
