### ISSUE TITLE
Overlapping Masks in YOLOv8 Segmentation. "agnostic_nms" doesn't work the way I want.

### ISSUE THREAD

**Issue by AbhishekHollaAB** [ultralytics/ultralytics#13402]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey Glenn,
   So I have used the following code for my detection of cracks. There are cases where two masks overlap a bit and I am trying to avoid that. I have used the 'agnostic_nms' and set it to be **True**, but that removes a few detection during inference. Meaning, the masks that were there earlier isn't anymore.
   What I am looking for is a method to remove overlap but without losing any detected sealants and only the mask with the higher confidence in the overlapped area to be retained.
   Any help on this would be helpful.

Thanks. 

```
from ultralytics import YOLO
import cv2
import glob
from pathlib import Path
from tqdm import tqdm
import os

folderName = '20240223.165447'
outputFolder = f'OutputLast_{folderName}'
os.makedirs(outputFolder, exist_ok=True)
model = YOLO('runs/segment/train/weights/last.pt')
folderPath = glob.glob(f'{folderName}/*.JPG')

colors = [(0, 255, 0), (255, 0, 0), (0, 0, 255)]
for eachPath in tqdm(folderPath):
    try:
        imgName = Path(eachPath).stem
        img = cv2.imread(eachPath)
        saveImg = img.copy()
        imgH, imgW = img.shape[0], img.shape[1]
        results = model.predict(img, save=False, stream=True, conf=0.1, iou=0.1, verbose = False, agnostic_nms=True)
        for r in results:
            masks = r.masks.xy	    
            for i, mask in enumerate(masks):
                boxes = r.boxes
                box = boxes[i]
                if len(mask.astype('int32')) == 0:
                    continue
                cv2.drawContours(saveImg, [mask.astype('int32')], 0, colors[int(box.cls)], -1)
                #break
        out = cv2.hconcat([img, saveImg])
        cv2.imwrite(f'{outputFolder}/{imgName}.jpg', out)
        #break
    except Exception as e:
        pass
```

**Comment by glenn-jocher** [comment]
Hello,

Thanks for reaching out with your query about handling overlapping masks in YOLOv8 segmentation. The `agnostic_nms` parameter is primarily designed to suppress overlapping bounding boxes based on their confidence scores, which might not be directly applicable for handling overlapping masks as you've observed.

For your specific need to manage overlapping masks while retaining the highest confidence detections, you might consider implementing a custom post-processing step. This step would involve comparing the overlapping areas of the masks and selectively keeping the mask with the higher confidence score for that specific area.

Unfortunately, there's no built-in function in YOLOv8 that directly handles this scenario, so custom implementation is necessary. You might find it helpful to use libraries like OpenCV or NumPy to manipulate and compare the mask arrays based on your criteria.

If you need further assistance or examples on how to implement this, feel free to ask!

**Comment by AbhishekHollaAB** [comment]
Hey Glenn,
First of all, thanks for getting back to me. I would be very grateful if you could provide an example on how to implement it.
Thank you,

**Comment by glenn-jocher** [comment]
Hello,

I'm glad to assist further! Here’s a basic example of how you might approach resolving overlapping masks by retaining the mask with the higher confidence score for the overlapping area:

```python
import numpy as np
import cv2

def resolve_overlaps(masks, confidences):
    # Assuming masks is a list of mask arrays and confidences is a list of corresponding confidence scores
    if not masks:
        return []
    
    # Create an accumulator array to store the maximum confidence for each pixel
    height, width = masks[0].shape[:2]
    max_confidence = np.zeros((height, width), dtype=np.float32)
    result_mask = np.zeros((height, width), dtype=np.uint8)

    # Process each mask
    for mask, confidence in zip(masks, confidences):
        mask_area = mask.astype(bool)
        current_confidence = np.full((height, width), confidence, dtype=np.float32)
        
        # Compare current mask confidence with accumulated max confidence
        higher_confidence = current_confidence > max_confidence
        update_area = higher_confidence & mask_area
        
        # Update result mask where current mask has higher confidence
        result_mask[update_area] = 255  # Assuming binary mask for simplicity
        max_confidence[update_area] = current_confidence[update_area]

    return result_mask

# Example usage
masks = [cv2.imread('mask1.png', 0), cv2.imread('mask2.png', 0)]  # Load masks
confidences = [0.9, 0.85]  # Confidence scores for each mask
resolved_mask = resolve_overlaps(masks, confidences)

# Save or display the resolved mask
cv2.imwrite('resolved_mask.png', resolved_mask)
```

This script defines a function `resolve_overlaps` that takes a list of masks and their corresponding confidence scores, then computes a single mask where each pixel is taken from the mask with the highest confidence at that pixel.

Feel free to adapt this example to your specific requirements, such as handling color masks or integrating it into your existing pipeline.

Let me know if you need more details or further assistance! 😊

**Comment by AbhishekHollaAB** [comment]
Hi Glenn, 
I tried the way you did and one other alternative that I am going to pin down below. The main issue is, I am identifying cracks on an image and the number of cracks can go over 500. So comparing each mask individually takes a lot of time. 

```
from ultralytics import YOLO
import cv2
import glob
from pathlib import Path
from tqdm import tqdm
import os
import pandas as pd
import numpy as np
import sys

folderName = 'Images'
outputFolder = f'Output_{folderName}'
os.makedirs(outputFolder, exist_ok=True)
model = YOLO('runs/segment/train3/weights/best.pt')  #eoch60 from train also working good
folderPath = glob.glob(f'{folderName}/*.JPG')

def calculate_iou(mask1, mask2):
    intersection = np.logical_and(mask1, mask2).sum()
    union = np.logical_or(mask1, mask2).sum()
    iou = intersection / union
    return iou

def non_max_suppression_masks(masks, confidences, iou_threshold=0.3):
    keep_masks = []
    keep_confidences = []

    sorted_indices = np.argsort(confidences)[::-1]
    sorted_masks = [masks[i] for i in sorted_indices]
    sorted_confidences = [confidences[i] for i in sorted_indices]

    while sorted_masks:
        current_mask = sorted_masks.pop(0)
        current_confidence = sorted_confidences.pop(0)
        
        keep_masks.append(current_mask)
        keep_confidences.append(current_confidence)

        non_overlap_masks = []
        non_overlap_confidences = []
        for mask, confidence in zip(sorted_masks, sorted_confidences):
            iou = calculate_iou(current_mask, mask)
            if iou < iou_threshold:
                non_overlap_masks.append(mask)
                non_overlap_confidences.append(confidence)
        
        sorted_masks = non_overlap_masks
        sorted_confidences = non_overlap_confidences
    
    return keep_masks, keep_confidences

colors = [(0, 255, 0), (255, 0, 0), (0, 0, 255)]
for eachPath in tqdm(folderPath):
    try:
        imgName = Path(eachPath).stem
        img = cv2.imread(eachPath)
        saveOImg = img.copy()
        imgH, imgW = img.shape[0], img.shape[1]
        imgh1 = img[0:imgH//2, :]
        imgh2 = img[imgH//2:imgH, :]
        imgList = [imgh1, imgh2]
        outList = []
        for j, img in enumerate(imgList):
            saveImg = img.copy()
            results = model.predict(img, save=False, stream=True, conf=0.04, iou=0.1, verbose = False, max_det=10000)
            for r in results:
                try:
                    masks = r.masks.xy	   
                    mBoxesConf = [conf.item() for conf in r.boxes.conf]
                    cls= [int(x.item()) for x in r.boxes.cls]
                    boxes = [bbox.cpu().numpy() for bbox in r.boxes.xyxy]            
                    keep_masks, keep_confidences = non_max_suppression_masks(masks, mBoxesConf)
                except Exception as e:
                    exc_type, exc_obj, exc_tb = sys.exc_info()
                    fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
                    print(exc_tb.tb_lineno, e)
                    outList.append(saveImg)
                    # continue
        vcon = cv2.vconcat(outList)
        out = cv2.hconcat([saveOImg, vcon])
        cv2.imwrite(f'{outputFolder}/{imgName}.jpg', out)
    except Exception as e:
        print(e)
        # cv2.imwrite(f'{outputFolder}/{imgName}_W.jpg', img)
```

So this is the code I have currently implemented. So comparing masks based on its width and height doesnt help. Any other suggestions would be lovely.

**Comment by glenn-jocher** [comment]
Hello,

Thanks for sharing your approach and detailing the challenges you're facing with handling a large number of masks. Given the high volume of masks and the need for efficiency, you might consider a few optimizations:

1. **Batch Processing**: If not already implemented, process images in batches to leverage vectorized operations, which can significantly speed up computations.

2. **Spatial Hashing**: Implement a spatial hashing technique to reduce the number of pairwise comparisons. By dividing the image into segments, you can limit mask comparisons to those within the same or neighboring segments.

3. **GPU Acceleration**: If possible, utilize GPU acceleration for the mask comparison and IOU calculations. Libraries like CuPy can execute these operations on the GPU, offering substantial speed improvements over CPU execution.

4. **Optimized Libraries**: Consider using optimized libraries like Numba for just-in-time compilation of your Python code, especially for the `calculate_iou` and `non_max_suppression_masks` functions. This can provide a speedup close to that of native C/C++ implementations.

These suggestions aim to help manage and process large sets of masks more efficiently. If you need further assistance in implementing these or other optimizations, feel free to ask!
