### ISSUE TITLE
Request for Official C++ and TensorRT Support

### ISSUE THREAD

**Issue by auner2456889** [ultralytics/ultralytics#13405]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hey I found out that YOLO can be sped up using C++ and TensorRT, but I see that the official support is only for Python, and the C++ part is all from third parties. Just wondering, are there any plans to add official C++ and TensorRT support?

### Use case

This feature would be used by developers who need high-performance inference for real-time applications. Official C++ and TensorRT support would allow for better integration and performance optimization in various projects, particularly those requiring low-latency and high-throughput processing. This would be beneficial for applications in fields like autonomous driving, robotics, and any other use case where real-time object detection is critical.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@auner2456889 hello!

Thank you for your interest in enhancing YOLOv8 with official C++ and TensorRT support. We appreciate your suggestion and understand the importance of high-performance inference for real-time applications.

Currently, our official support is indeed focused on Python, as it allows for rapid development and broad accessibility. However, we recognize the value of C++ and TensorRT for certain use cases, especially in production environments where performance is critical.

While we don't have immediate plans to add official C++ and TensorRT support, we are always evaluating ways to improve our models and expand their usability. Your feedback is invaluable and helps us prioritize future developments.

We encourage you and the community to contribute via PRs if you have specific implementations or enhancements. Contributions are a fantastic way to accelerate the inclusion of such features.

Thanks again for your input!

**Comment by rwdsji** [comment]
> @auner2456889 hello!
> 
> Thank you for your interest in enhancing YOLOv8 with official C++ and TensorRT support. We appreciate your suggestion and understand the importance of high-performance inference for real-time applications.
> 
> Currently, our official support is indeed focused on Python, as it allows for rapid development and broad accessibility. However, we recognize the value of C++ and TensorRT for certain use cases, especially in production environments where performance is critical.
> 
> While we don't have immediate plans to add official C++ and TensorRT support, we are always evaluating ways to improve our models and expand their usability. Your feedback is invaluable and helps us prioritize future developments.
> 
> We encourage you and the community to contribute via PRs if you have specific implementations or enhancements. Contributions are a fantastic way to accelerate the inclusion of such features.
> 
> Thanks again for your input!

Such an AI-generated reply :)

Anyway, they are not going to bother with C++ because of skill issues.
