### ISSUE TITLE
no model summary

### ISSUE THREAD

**Issue by Yee0717** [ultralytics/ultralytics#1341]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Why does the model summary not appear when I use my own dataset（voc format） to train yolov8s
![image](https://user-images.githubusercontent.com/81677344/223959469-479776a7-9f50-4dd5-bf39-b785ac48a3d8.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Yee0717 thank you for the bug report! I'm able to reproduce. Will investigate.

**Comment by glenn-jocher** [comment]
@Yee0717 should be resolved now in https://github.com/ultralytics/ultralytics/pull/1333/commits/d5dddd182247bfc345f75cb4b974ef26f0c9f909 which will deploy with 8.0.52 today. 

Thank you for letting us know about this problem and please inform us of any other issues you spot!
