### ISSUE TITLE
How do I get the coordinates of detected objects in yolov8 in real time and print?

### ISSUE THREAD

**Issue by jules-cp** [ultralytics/ultralytics#13419]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How do I get the coordinates of detected objects in yolov8 in real time and print?

### Additional

I would like you to help me with the code, there is already another discussion in this forum but that code does not work for me and I don't know what I am doing wrong, I am using prediction mode and only one class:

This is the code that I got from a previous discussion:

from ultralytics import YOLO

# Initialize and run predictions
# Load a pretrained YOLOv8n model
model = YOLO('best.pt')
# Run prediction
results = model('WEED100151.jpg')

# Loop through detections
for det in results.detections:
    x1, y1, x2, y2 = det.box.xyxy.int().tolist()  # Bounding box coordinates
        
    print(f"Coordinates: {x1}, {y1}, {x2}, {y2}")
    
results.show() 

but i have this error

AttributeError: 'list' object has no attribute 'detections'

I appreciate that you can help me

**Comment by glenn-jocher** [comment]
Hello,

Thank you for reaching out with your question. It looks like there's a small issue in the way you're trying to access the detection results. In YOLOv8, the results from the model prediction are stored in a `Results` object, not directly as a list. Here's how you can modify your code to correctly access and print the bounding box coordinates:

```python
from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO('best.pt')

# Run prediction
results = model('WEED100151.jpg')

# Loop through detections
for result in results:
    for det in result.boxes:
        x1, y1, x2, y2 = det.xyxy.int().tolist()  # Bounding box coordinates
        print(f"Coordinates: {x1}, {y1}, {x2}, {y2}")

result.show()  # Display the image with bounding boxes
```

Make sure to iterate over `results` and then access `boxes` for each `result`. This should resolve the `AttributeError` you're encountering.

If you have any more questions or need further assistance, feel free to ask. Happy coding! 🚀

**Comment by jules-cp** [comment]
Thank you very much for the help, I tested the code you provided me, but I got the following error:

    x1, y1, x2, y2 = det.xyxy.int().tolist()  # Bounding box coordinates

ValueError: not enough values to unpack (expected 4, got 1)

I don't know if it's a problem with the image I'm using for the test or if it's a code problem?

**Comment by jules-cp** [comment]
I add an example of the object that I am detecting and that I want to obtain its coordinates

![results](https://github.com/ultralytics/ultralytics/assets/171988085/abf509a0-6dbe-425b-852e-94553ddde76a)
