### ISSUE TITLE
Bug heatmap  ultralytics 8.1.34

### ISSUE THREAD

**Issue by kakaz1n** [ultralytics/ultralytics#13417]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Integrations

### Bug

heatmap_obj =  heatmap.Heatmap(imw=w,
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: Heatmap.__init__() got an unexpected keyword argument 'imw'

### Minimal Reproducible Example
```python
import cv2
from ultralytics import YOLO, solutions

model = YOLO("yolov8n.pt")
cap = cv2.VideoCapture("path/to/video/file.mp4")
assert cap.isOpened(), "Error reading video file"
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

# Video writer
video_writer = cv2.VideoWriter("heatmap_output.avi", cv2.VideoWriter_fourcc(*"mp4v"), fps, (w, h))

classes_for_heatmap = [0, 2]  # classes for heatmap

# Init heatmap
heatmap_obj =  heatmap.Heatmap(imw=w,
                     imh=h,
                     view_img=True,
                     shape="rect",
                     classes_names=model.names,
                     heatmap_alpha=0.6,
                     colormap=cv2.COLORMAP_JET)

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break
    tracks = model.track(im0, persist=True, show=False, classes=classes_for_heatmap)

    im0 = heatmap_obj.generate_heatmap(im0, tracks)
    video_writer.write(im0)

cap.release()
video_writer.release()
cv2.destroyAllWindows()
```

### Additional

works after
Installing collected packages: ultralytics
  Attempting uninstall: ultralytics
    Found existing installation: ultralytics 8.1.34
    Uninstalling ultralytics-8.1.34:
      Successfully uninstalled ultralytics-8.1.34
Successfully installed ultralytics-8.2.28

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ambitious-octopus** [comment]
Hey @kakaz1n thanks for opening the issue, unfortunately i can't reproduce the error. 
This line should be:
```python
heatmap_obj =  solutions.heatmap.Heatmap(imw=w,
                     imh=h,
                     view_img=True,
                     shape="rect",
                     classes_names=model.names,
                     heatmap_alpha=0.6,
                     colormap=cv2.COLORMAP_JET)
```

**Comment by glenn-jocher** [comment]
@ambitious-octopus thanks for the bug reviews here! Please add any Labels to the bug reports that make sense like 'non-reproducible' if the problem isn't reproducible, or 'TODO' if it's reproducible and we want to mark as important for fixing.
