### ISSUE TITLE
Multiple streams breaks once the model is converted to ONNX

### ISSUE THREAD

**Issue by LordSizzz** [ultralytics/ultralytics#13415]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict, Export

### Bug

.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: images for the following indices
 index: 0 Got: 6 Expected: 1
 Please fix either the inputs/outputs or the model.

### Environment

Ultralytics YOLOv8.2.28 🚀 Python-3.12.2 torch-2.3.0+cpu CPU (Intel Core(TM) i7-7700 3.60GHz)
Setup complete ✅ (8 CPUs, 32.0 GB RAM, 232.8/238.4 GB disk)
------
Ultralytics YOLOv8.2.28 🚀 Python-3.10.12 torch-2.3.1 CPU (Cortex-A55)
Setup complete ✅ (8 CPUs, 15.3 GB RAM, 24.7/226.7 GB disk)

### Minimal Reproducible Example

```python
# Exporting to ONNX
from ultralytics import YOLO

model = YOLO("yolo-Weights/yolov8n.pt")
model.export(format="onnx")
```
```python
# Prediction code

model = YOLO("yolo-Weights/yolov8n.onnx")
RTSP_URLS="list.streams" # each line containing an RTSP link

results = model(RTSP_URLS,stream=True,conf=0.5,show_boxes=True,show_labels=True,show_conf=True,imgsz=(640,640),show=True)
```

### Additional

I tried to use the yolov8n model to do predictions in real time with my RTSP streams, it works fine with the .pt model but once I convert it to .ONNX it throws an error `index: 0 Got: 6 Expected: 1` index : 0 being the streams sources.
I ran the code both on my linux SBC and windows desktop systems with python 3.10.12 on linux and 3.11.9 on windows.
the models were converted using the python method provided in the docs.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@LordSizzz hello,

Thank you for providing detailed information about the issue you're encountering with ONNX and multiple RTSP streams. The error message you're seeing suggests that there's a mismatch in the expected input dimensions for your model. The ONNX model is expecting a single input stream (batch size of 1), but it seems to be receiving multiple streams simultaneously (batch size of 6).

This can occur if the model was exported with a specific batch size that doesn't match the number of streams you're trying to process. Here are a couple of steps you can take to resolve this:

1. **Re-export the Model with Dynamic Axes**: When exporting your model to ONNX, ensure that you enable dynamic axes to allow for variable batch sizes. This can be done by setting the `dynamic=True` parameter in the `model.export()` function. This will allow the model to handle varying numbers of input streams.

2. **Adjust the Input Feed**: Ensure that the input to the model is correctly batched according to the model's expected input dimensions. If your model expects a batch size of 1, you might need to process each stream individually or modify the model to accept the actual number of streams you intend to use.

Here's an example of how you might adjust the export code:
```python
model.export(format="onnx", dynamic=True)
```

Please try these adjustments and let us know if the issue persists. We're here to help!

**Comment by LordSizzz** [comment]
@glenn-jocher  thank you for the quick response, what you just mentioned whas indeed the issue, due to my lack of knowledge and the fact that it worked just before the conversion caused me to think that, so yes, adding `,dynamic=True` in the export code did fix my problem, thank you for your help.

**Comment by glenn-jocher** [comment]
@LordSizzz, I'm glad to hear that the solution worked for you! If you have any more questions or run into other issues, feel free to reach out. Happy coding! 🚀
