### ISSUE TITLE
Using OBB for pick and place on a robotic arm

### ISSUE THREAD

**Issue by KennethEladistu** [ultralytics/ultralytics#13425]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I am new to AI and is planning to use OBB for a pick and place sequence, I will be annotating and training parcel picture datasets  and load it into OBB model for pick and place detection. May I ask if it's possible?

**Comment by glenn-jocher** [comment]
Hello! Welcome to the world of AI and thanks for considering Ultralytics YOLO for your project. 🚀

Yes, using Oriented Bounding Boxes (OBB) for a pick and place task with a robotic arm is definitely possible and a great application of our YOLO models. You can annotate your parcel picture datasets in the YOLO OBB format, which uses the four corner points of objects. After annotation, you can train a model like YOLOv8n-OBB to recognize and precisely localize the parcels.

For training, you'll need to set up your dataset in the correct format as described in our documentation on OBB datasets. Once your model is trained, it can be integrated into your robotic system to guide the pick and place operations.

If you need further guidance on setting up your dataset or any other specifics, feel free to ask. Good luck with your project! 🤖
