### ISSUE TITLE
custom model architecture plot 

### ISSUE THREAD

**Issue by sergenerbay** [ultralytics/ultralytics#13429]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, 
I configure yolov8 architecture. I have configured the YOLOv8 architecture and I want to visualize the layer structures of the model.
Is this possible with ultralytics ?

**Comment by glenn-jocher** [comment]
@sergenerbay hello!

Yes, you can visualize the layer structures of your YOLOv8 model. You can use the `model.info()` method in Python after loading your model with the `YOLO()` class. This will print a detailed summary of the model layers, their types, and other relevant information.

Here's a quick example:

```python
from ultralytics import YOLO

# Load your custom model
model = YOLO('path/to/your/custom_model.pt')

# Display model information
model.info()
```

This should provide you with a clear visualization of the model's architecture in your console.

If you need further customization in the visualization, you might consider using tools like `torchviz` or `netron` which can provide graphical representations of the model.

Hope this helps! Let us know if you have any more questions.
