### ISSUE TITLE
How to display OKS scores

### ISSUE THREAD

**Issue by s0966066980** [ultralytics/ultralytics#13424]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm trying to get the OKS indicator to show up when I use val.py, how to do it?

![image](https://github.com/ultralytics/ultralytics/assets/45198905/f3a8c507-2e99-4d3f-be16-861087d2b7a1)

**Comment by glenn-jocher** [comment]
Hello! To display OKS (Object Keypoint Similarity) scores during validation with YOLOv8, you'll need to ensure that your model is configured for pose estimation tasks and that the validation dataset includes keypoint annotations.

If you're using a pose estimation model like YOLOv8n-pose, you can activate OKS scoring by setting the appropriate flag in your validation command. For example:

```bash
yolo val model=yolov8n-pose.pt --pose
```

Make sure your dataset configuration (`data.yaml`) includes paths to the keypoint annotations and that the annotations are in the correct format expected by the model.

If you encounter any issues or need further customization, please refer to the pose estimation section in the documentation or reach out again. Happy modeling! 🚀

**Comment by s0966066980** [comment]
> Hello! To display OKS (Object Keypoint Similarity) scores during validation with YOLOv8, you'll need to ensure that your model is configured for pose estimation tasks and that the validation dataset includes keypoint annotations.
> 
> If you're using a pose estimation model like YOLOv8n-pose, you can activate OKS scoring by setting the appropriate flag in your validation command. For example:
> 
> ```shell
> yolo val model=yolov8n-pose.pt --pose
> ```
> 
> Make sure your dataset configuration (`data.yaml`) includes paths to the keypoint annotations and that the annotations are in the correct format expected by the model.
> 
> If you encounter any issues or need further customization, please refer to the pose estimation section in the documentation or reach out again. Happy modeling! 🚀

Executing `yolo val model=yolov8n-pose.pt --pose` did not get the answer

![image](https://github.com/ultralytics/ultralytics/assets/45198905/046bb73d-6cbb-4a28-b03a-b4892a04b0a4)

**Comment by glenn-jocher** [comment]
Hello! Thank you for the update and the screenshot. It seems there might be a specific issue with the configuration or the command syntax.

Please ensure that your `data.yaml` is correctly set up with the paths to the keypoint annotations and that these annotations are formatted correctly. Also, verify that the model you are using is indeed configured for pose estimation.

If the issue persists, it could be helpful to check the logs for any error messages that might give more insight into what might be going wrong. If you're still stuck, could you please provide the content of your `data.yaml` and any error messages you see in the logs? This will help us diagnose the problem more effectively.

Looking forward to your response!
