### ISSUE TITLE
NCNN model - passing config parameters

### ISSUE THREAD

**Issue by MarkhamLee** [ultralytics/ultralytics#13449]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I've discovered an issue related to Rockchip devices using the RK3588 system on a chip, and potentially other Linux devices using a big/little CPU configuration, namely:

If you invoke an NCNN model you will get very slow performance as the device tries to use all the cores on the RK3588, in my case I was getting about 4 FPS for a 640 x 320 video. However, if you make a small change to autobackend.py, in the model load section for ncnn, namely adding a line limiting the number of threads to the number of big cores: 

`       
    net.opt.num_threads = 4
`
Setting the number of threads to eight is slower, six is slower. 

I don't think this is specific to Ultralytics or YOLO as I've observed similar things with TorchScript and other models, I think its just how my operating system and python handle the big/little configuration. 

My question is: is there an efficient way to pass this parameter to autobackend.py when the model is loaded from 

`model = YOLO("path/to/ncnn/model")` 

I was thinking of overriding methods and/or just writing a custom implementation, but figured I'd ask the question here before I wrote dozens of line of code just to pass a single parameter to ncnn.Net(). I.e., why reinvent the wheel if I can just pass a parameter, and always installing Ultralytics in editable model and then changing the source code whenever I want to use NCNN + the RK3588 for a project seems less than idea? 

Other technical details:

- I'm running Ubuntu 22.04, community distro: https://github.com/Joshua-Riek/ubuntu-rockchip
- The Rockchip RK3588 chip has eight cores and my device has 16 GB of RAM
- I tested this via cloning the Ultralytics repo and installing it into a conda environment via "pip3 install -e ."
- The tests were with yolov8n.pt converted to NCNN
- When running things the standard way all of my cores are above 95% and I get 4 FPS, when I make the small change to the # of threads four cores run at 70-80% and the rest are basically idle 

Finally, if it matters, here is the code I was running 
```

import asyncio
import cv2
import json
import ncnn
import os
import sys
from ultralytics import YOLO

parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(parent_dir)

from common_utils.logging_utils import LoggingUtilities  # noqa: E402

logger = LoggingUtilities.console_out_logger("NCNN Tracker")


IMG_SIZE = (640, 640)


class ObjectTracker:

    def __init__(self, model_name: str, file_path: str):

        self.logger = logger

        self.model = self.get_model(model_name)

        self.stream_object = self.get_streaming_object(file_path)

        # analyze video
        asyncio.run(self.analyze_video(self.stream_object))

    def get_model(self, model_name: str) -> object:

        # create model
        model = YOLO(model_name)

        return model

    def get_streaming_object(self, file_path: str):

        cap = cv2.VideoCapture(file_path)
        assert cap.isOpened(), "Error reading video file"

        return cap

    def read_video(self, stream_object: object):

        success, frame = stream_object.read()

        if not success:
            logger.info('No file or processing complete')
            self.shutdown()

        return self.pre_process(frame)

    def pre_process(self, frame):

        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        shape = frame.shape[:2]

        if shape != IMG_SIZE:
            frame = self.letter_box(frame, shape, (640, 640), (0, 0, 0))

        return frame

    def letter_box(self, frame, shape, new_shape, pad_color):

        # Resize and pad image while meeting stride-multiple constraints
        # Scale ratio
        r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])

        # Compute padding
        # ratio = r  # width, height ratios
        new_unpad = int(round(shape[1] * r)), int(round(shape[0] * r))
        dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]

        dw /= 2  # divide padding into 2 sides
        dh /= 2

        if shape[::-1] != new_unpad:  # resize
            frame = cv2.resize(frame, new_unpad,
                               interpolation=cv2.INTER_LINEAR)

        top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
        left, right = int(round(dw - 0.1)), int(round(dw + 0.1))
        frame = cv2.copyMakeBorder(frame, top, bottom, left, right,
                                   cv2.BORDER_CONSTANT, value=pad_color)

        return frame

    async def analyze_video(self, stream_object: object):

        frame_count = 0
        avg_fps = 0
        total_latency = 0
        fps_sum = 0

        while stream_object.isOpened():

            frame = self.read_video(stream_object)
            frame_count += 1

            # the video data object contains extensive data on each frame of
            # the video video shape, xy coordintes for each object, object
            # classes and data on inferencing and processing speed.
            video_data = self.inference(frame)

            # parse out key data from the video data object
            fps_sum, total_latency, avg_fps, \
                avg_latency, frame_message =\
                await self.parse_video_data(video_data,
                                            frame_count,
                                            fps_sum,
                                            total_latency)

            await self.write_on_frame(frame, frame_message, (5, 25))

            # create JSON payload
            await self.build_payload(avg_fps,
                                     avg_latency,
                                     frame_count)

            # Visualize the results on the frame
            annotated_frame = video_data[0].plot()

            # Display the annotated frame
            cv2.imshow("YOLOv8 Tracking", annotated_frame)

            # Break the loop if 'q' is pressed
            if cv2.waitKey(1) & 0xFF == ord("q"):
                self.shutdown()
                break

    def inference(self, frame: object):

        return self.model(frame, task="detect", verbose=False)

    async def write_on_frame(self, frame: object, text: str,
                             coordinates: tuple):

        cv2.putText(frame, text, coordinates,
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

    async def parse_video_data(self, data: object,
                               frame_count: int,
                               fps_sum: int,
                               total_latency: float) -> dict:

        inferencing_latency = round((sum(data[0].speed.values())), 2)
        fps = round((1000 / inferencing_latency), 2)

        fps_sum = fps_sum + fps
        total_latency += inferencing_latency

        avg_fps = round((fps_sum/frame_count), 2)
        avg_latency = round((total_latency/frame_count), 2)
        frame_message = (f'Avg FPS: {avg_fps}')

        return fps_sum, total_latency, avg_fps, avg_latency, frame_message

    async def build_payload(self, avg_fps: float,
                            inferencing_latency: float,
                            frame_count: int) -> dict:

        payload = {"avg_fps": avg_fps,
                   "avg_inferencing_latency(ms)": inferencing_latency}

        if frame_count % 200 == 0:
            self.logger.info(f'Current payload: {payload}')

        # convert to json
        return json.dumps(payload)

    def shutdown(self):

        self.stream_object.release()
        cv2.destroyAllWindows()
        sys.exit()


# pass the model name, path to video and list of classes to be tracked

tracking = ObjectTracker("./yolov8n_ncnn_model",
                         "../videos/1171461-sd_640_360_30fps.mp4")
```

Thanks in advance. 

Also, happy to submit a PR if this is something best handled by updating the code base so that users can pass number of threads for certain models. 

-M

**Comment by glenn-jocher** [comment]
Hello @MarkhamLee,

Thank you for your detailed report and for sharing your insights on optimizing NCNN model performance on Rockchip RK3588 devices. Your observations and proposed solution are very valuable.

To address your question, currently, the `YOLO` class does not directly support passing custom configuration parameters like `num_threads` to the NCNN backend. However, your approach to modifying `autobackend.py` is a valid workaround. 

Given the importance of this feature for users with similar hardware configurations, I recommend submitting a Pull Request (PR) to the Ultralytics repository. This would allow us to review and potentially integrate your solution, making it easier for others to benefit from this enhancement.

In the meantime, you can create a custom implementation to pass the `num_threads` parameter. Here's a concise example of how you might achieve this by subclassing the `YOLO` class and overriding the model loading method:

```python
from ultralytics import YOLO

class CustomYOLO(YOLO):
    def __init__(self, model_path, num_threads=4):
        super().__init__(model_path)
        self.num_threads = num_threads

    def load_model(self, model_path):
        # Load the NCNN model with custom number of threads
        self.model = ncnn.Net()
        self.model.opt.num_threads = self.num_threads
        self.model.load_param(model_path + ".param")
        self.model.load_model(model_path + ".bin")

# Usage
model = CustomYOLO("path/to/ncnn/model", num_threads=4)
results = model("https://ultralytics.com/images/bus.jpg")
```

This approach allows you to specify the number of threads when initializing the model, ensuring optimal performance on your specific hardware setup.

If you encounter any issues or have further questions, please feel free to reach out. We appreciate your willingness to contribute to the codebase, and we look forward to your PR!

**Comment by glenn-jocher** [comment]
@MarkhamLee also I remembered that we do have a parameter here for the maximum number of workers to use. If this value is correctly set to 4 on your device, you could pass this directly for NCNN inference:
https://github.com/ultralytics/ultralytics/blob/1b26838def20ea34889b6a8de2fe394023739ee1/ultralytics/utils/__init__.py#L39


@lakshanthad please take a look, thank you!

**Comment by glenn-jocher** [comment]
@MarkhamLee @lakshanthad I've created https://github.com/ultralytics/ultralytics/pull/13454 as a potential fix, can you please profile and provide NCNN benchmarks with `main` vs PR branch on your device?

**Comment by 1716775457damn** [comment]
The code you provided is a Python class called `CustomYOLO` that inherits from the `YOLO` class from the `ultralytics` library. It appears to be designed to work with NCNN (a high-performance neural network inference framework) models.

Here's a breakdown of the code:

1. `from ultralytics import YOLO`: This line imports the `YOLO` class from the `ultralytics` library.

2. `class CustomYOLO(YOLO):`: This line defines a new class called `CustomYOLO` that inherits from the `YOLO` class.

3. `def __init__(self, model_path, num_threads=4):`: This is the constructor method for the `CustomYOLO` class. It takes two arguments: `model_path` (the path to the NCNN model) and `num_threads` (the number of threads to use for inference, with a default value of 4).

4. `super().__init__(model_path)`: This line calls the constructor of the parent class (`YOLO`) with the `model_path` argument.

5. `self.num_threads = num_threads`: This line sets the `num_threads` attribute of the `CustomYOLO` instance to the value provided in the constructor.

6. `def load_model(self, model_path):`: This method is responsible for loading the NCNN model using the provided `model_path`.

7. `self.model = ncnn.Net()`: This line creates a new instance of the `ncnn.Net` class, which represents the NCNN model.

8. `self.model.opt.num_threads = self.num_threads`: This line sets the number of threads for the NCNN model to the value of the `num_threads` attribute.

9. `self.model.load_param(model_path + ".param")`: This line loads the NCNN model parameters from the `.param` file specified by `model_path`.

10. `self.model.load_model(model_path + ".bin")`: This line loads the NCNN model weights from the `.bin` file specified by `model_path`.

11. `# Usage`: This is a comment indicating how to use the `CustomYOLO` class.

12. `model = CustomYOLO("path/to/ncnn/model", num_threads=4)`: This line creates a new instance of the `CustomYOLO` class with the specified model path and number of threads.

13. `results = model("https://ultralytics.com/images/bus.jpg")`: This line calls the `CustomYOLO` instance with a URL to an image, which presumably performs object detection using the loaded NCNN model, and stores the results in the `results` variable.

Overall, this code appears to be a custom implementation of the `YOLO` class from the `ultralytics` library, specifically designed to work with NCNN models. It allows you to specify the number of threads to use for inference, which can potentially improve performance on systems with multiple CPU cores.

**Comment by glenn-jocher** [comment]
Thank you for your detailed breakdown of the `CustomYOLO` class! Your understanding is spot-on, and it's great to see such a thorough analysis.

To address your initial question about passing configuration parameters like `num_threads` to the NCNN backend more efficiently, your approach of subclassing the `YOLO` class and overriding the model loading method is indeed a practical solution. This ensures that each instance of the model can be configured with the desired number of threads, optimizing performance on your specific hardware setup.

If you haven't already, please ensure you're using the latest versions of `torch` and `ultralytics` to benefit from the latest features and fixes. You can update them using:
```bash
pip install --upgrade torch ultralytics
```

Additionally, if you encounter any issues or have further questions, feel free to share a minimum reproducible example. This will help us investigate and provide a more targeted solution. You can find more details on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Here's a refined version of your implementation for clarity:

```python
from ultralytics import YOLO
import ncnn

class CustomYOLO(YOLO):
    def __init__(self, model_path, num_threads=4):
        super().__init__(model_path)
        self.num_threads = num_threads

    def load_model(self, model_path):
        # Load the NCNN model with custom number of threads
        self.model = ncnn.Net()
        self.model.opt.num_threads = self.num_threads
        self.model.load_param(model_path + ".param")
        self.model.load_model(model_path + ".bin")

# Usage
model = CustomYOLO("path/to/ncnn/model", num_threads=4)
results = model("https://ultralytics.com/images/bus.jpg")
```

This approach ensures that each thread has its own isolated model instance, preventing any race conditions and ensuring thread-safe inference.

If you believe this feature would benefit the broader community, we encourage you to submit a Pull Request (PR) to the Ultralytics repository. This would allow us to review and potentially integrate your solution, making it easier for others to benefit from this enhancement.

Thank you for your contribution and for helping improve the Ultralytics ecosystem! If you have any further questions or need assistance, feel free to reach out. 🚀

**Comment by lakshanthad** [comment]
Closing issue as PR closed
https://github.com/ultralytics/ultralytics/pull/13454
