### ISSUE TITLE
Get mAP on precomputed results?

### ISSUE THREAD

**Issue by AaspiralMoon** [ultralytics/ultralytics#13465]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi there, I'm not sure if I can get mAP on precomputed results (e.g., saved as .txt for each image), without running the models.

If there is a feature already, how should I prepare the format of results and ground truth?

Thanks in advance.

**Comment by glenn-jocher** [comment]
@AaspiralMoon hello!

Thank you for reaching out with your question. To calculate mAP on precomputed results without running the models, you can indeed use the Ultralytics YOLO framework. However, you'll need to ensure that your precomputed results and ground truth data are in the correct format.

### Preparing the Format

1. **Precomputed Results**: Your detection results should be saved in a text file for each image. Each line in the text file should follow the format:
   ```
   class_id x_center y_center width height confidence
   ```
   This format is consistent with YOLO's output format.

2. **Ground Truth**: The ground truth annotations should also be in a similar text file format for each image, but without the confidence score:
   ```
   class_id x_center y_center width height
   ```

### Calculating mAP

To calculate mAP using these precomputed results, you can use the `val` mode in the Ultralytics YOLO framework. Here's a step-by-step guide:

1. **Organize Your Data**: Ensure that your precomputed results and ground truth files are organized in directories.

2. **Custom Dataset Configuration**: Create a custom dataset configuration file (`data.yaml`) that points to your ground truth and precomputed results directories.

3. **Validation Script**: Use the following script to run the validation:

    ```python
    from ultralytics import YOLO

    # Load a model (you can use any model here, as we are not running inference)
    model = YOLO('yolov8n.pt')

    # Validate the model using your custom dataset
    results = model.val(data='path/to/data.yaml', save_json=True)
    
    # Print mAP results
    print(f"mAP50-95: {results.box.map:.4f}")
    print(f"mAP50: {results.box.map50:.4f}")
    print(f"mAP75: {results.box.map75:.4f}")
    ```

### Example `data.yaml` Configuration

```yaml
path:  # path to your dataset
  train: path/to/train/images
  val: path/to/val/images
  test: path/to/test/images
names:
  0: class_name_1
  1: class_name_2
  ...
```

### Important Notes

- Ensure you are using the latest versions of `torch` and `ultralytics` packages. You can upgrade them using:
  ```bash
  pip install --upgrade torch ultralytics
  ```

- If you encounter any issues, please provide a minimum reproducible example so we can better assist you. You can find more details on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any further questions or run into any issues. Happy coding! 😊

**Comment by AaspiralMoon** [comment]
@glenn-jocher Thanks for your response! I'm still confused where should I place the precomputed results, since in the example data.yaml, I don't see any directory pointing to them.

**Comment by glenn-jocher** [comment]
Hello @AaspiralMoon,

Thank you for your patience and for providing more context! Let's clarify how to organize your precomputed results for mAP evaluation.

### Organizing Precomputed Results

To calculate mAP using precomputed results, you need to ensure that your results are stored in a specific directory structure. Here's how you can set it up:

1. **Directory Structure**:
   - Create a directory for your precomputed results.
   - Inside this directory, create subdirectories for each image, where each subdirectory contains a text file with the detection results for that image.

2. **Example Structure**:
   ```
   precomputed_results/
   ├── image1.txt
   ├── image2.txt
   ├── image3.txt
   └── ...
   ```

3. **Content of Each Text File**:
   Each text file should contain lines in the format:
   ```
   class_id x_center y_center width height confidence
   ```

### Updating `data.yaml`

You should update your `data.yaml` to include paths to your ground truth annotations and your precomputed results. Here’s an example of how you can do this:

```yaml
path:  # path to your dataset
  train: path/to/train/images
  val: path/to/val/images
  test: path/to/test/images
results: path/to/precomputed_results  # Add this line to point to your precomputed results
names:
  0: class_name_1
  1: class_name_2
  ...
```

### Running Validation

With your `data.yaml` updated, you can now run the validation script to calculate mAP:

```python
from ultralytics import YOLO

# Load a model (you can use any model here, as we are not running inference)
model = YOLO('yolov8n.pt')

# Validate the model using your custom dataset
results = model.val(data='path/to/data.yaml', save_json=True)

# Print mAP results
print(f"mAP50-95: {results.box.map:.4f}")
print(f"mAP50: {results.box.map50:.4f}")
print(f"mAP75: {results.box.map75:.4f}")
```

### Important Notes

- Ensure you are using the latest versions of `torch` and `ultralytics`. You can upgrade them using:
  ```bash
  pip install --upgrade torch ultralytics
  ```

- If you encounter any issues, please provide a minimum reproducible example so we can better assist you. You can find more details on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any further questions or run into any issues. We're here to help! 😊

**Comment by AaspiralMoon** [comment]
@glenn-jocher Thanks for the reply. The following is the .yaml I prepared:

path:
  train: /home/remote_datasets/MOT17_Det_YOLO/datasets_combined/train
  val: /home/remote_datasets/MOT17_Det_YOLO/datasets_combined/val
  test: /home/remote_datasets/MOT17_Det_YOLO/datasets_combined/test
results: /home/projects/yolov8/my/runs/detect/predict200/labels
names:
  0: person

But I got this error:
SyntaxError: /home/projects/yolov8/my/runs/detect/predict200/test.yaml 'train:' key missing ❌.
'train' and 'val' are required in all data YAMLs.

Then, I modified the .yaml as follows:

train: /home/remote_datasets/MOT17_Det_YOLO/datasets_combined/train
val: /home/remote_datasets/MOT17_Det_YOLO/datasets_combined/val
test: /home/remote_datasets/MOT17_Det_YOLO/datasets_combined/test
results: /home/projects/yolov8/my/runs/detect/predict200/labels

nc: 1
names: ['person']

The validation runs well, but it still runs the model, which I don't want.

**Comment by glenn-jocher** [comment]
Hello @AaspiralMoon,

Thank you for providing the detailed information and the YAML configurations. I understand the issue you're facing with using precomputed results for mAP calculation without running the model.

### Clarification and Solution

Currently, the Ultralytics YOLO framework does not directly support evaluating mAP using precomputed results through the `val` mode. The `val` mode is designed to run the model on the validation dataset and then compute the metrics.

However, you can achieve your goal by using a custom script to calculate mAP from your precomputed results. Here's a step-by-step guide to help you:

1. **Ensure Your Precomputed Results and Ground Truths are in the Correct Format**:
   - **Precomputed Results**: Each line in the text file should follow the format:
     ```
     class_id x_center y_center width height confidence
     ```
   - **Ground Truth**: Each line in the text file should follow the format:
     ```
     class_id x_center y_center width height
     ```

2. **Custom Script for mAP Calculation**:
   You can use a custom script to read your precomputed results and ground truth files, and then calculate the mAP. Below is an example script using the `pycocotools` library:

   ```python
   import os
   import json
   from pycocotools.coco import COCO
   from pycocotools.cocoeval import COCOeval

   def load_annotations(annotations_path):
       coco = COCO(annotations_path)
       return coco

   def load_detections(detections_path):
       with open(detections_path, 'r') as f:
           detections = json.load(f)
       return detections

   def evaluate(coco, detections):
       coco_dt = coco.loadRes(detections)
       coco_eval = COCOeval(coco, coco_dt, 'bbox')
       coco_eval.evaluate()
       coco_eval.accumulate()
       coco_eval.summarize()

   if __name__ == "__main__":
       annotations_path = 'path/to/annotations.json'  # Path to your ground truth annotations in COCO format
       detections_path = 'path/to/detections.json'    # Path to your precomputed results in COCO format

       coco = load_annotations(annotations_path)
       detections = load_detections(detections_path)
       evaluate(coco, detections)
   ```

3. **Convert Your Results to COCO Format**:
   If your precomputed results are not in COCO format, you will need to convert them. Here’s an example of how to convert YOLO format to COCO format:

   ```python
   import os
   import json

   def yolo_to_coco(yolo_results_dir, output_file):
       coco_format = {
           "images": [],
           "annotations": [],
           "categories": [{"id": 0, "name": "person"}]
       }
       annotation_id = 0

       for txt_file in os.listdir(yolo_results_dir):
           if txt_file.endswith('.txt'):
               image_id = int(txt_file.split('.')[0])
               with open(os.path.join(yolo_results_dir, txt_file), 'r') as f:
                   for line in f:
                       class_id, x_center, y_center, width, height, confidence = map(float, line.strip().split())
                       coco_format["annotations"].append({
                           "id": annotation_id,
                           "image_id": image_id,
                           "category_id": int(class_id),
                           "bbox": [
                               x_center - width / 2,
                               y_center - height / 2,
                               width,
                               height
                           ],
                           "score": confidence,
                           "area": width * height,
                           "iscrowd": 0
                       })
                       annotation_id += 1
               coco_format["images"].append({
                   "id": image_id,
                   "file_name": f"{image_id}.jpg"
               })

       with open(output_file, 'w') as f:
           json.dump(coco_format, f, indent=4)

   yolo_to_coco('path/to/precomputed_results', 'path/to/detections.json')
   ```

### Next Steps

1. **Convert your precomputed results to COCO format** using the provided script.
2. **Prepare your ground truth annotations** in COCO format.
3. **Run the custom mAP calculation script** to evaluate your precomputed results.

Feel free to reach out if you have any further questions or need additional assistance. We're here to help! 😊

**Comment by AaspiralMoon** [comment]
@glenn-jocher Problem solved. Thanks for the help!

**Comment by glenn-jocher** [comment]
Hello @AaspiralMoon,

That's fantastic to hear! 🎉 I'm glad the solution worked for you.

If you have any more questions or run into any other issues, feel free to reach out. We're here to help! Also, if you have any insights or improvements based on your experience, we'd love to hear about them. Sharing your learnings can be incredibly valuable to the community.

Happy coding and best of luck with your projects! 😊
