### ISSUE TITLE
Resume training pretrained yolov8 segmentation model.

### ISSUE THREAD

**Issue by gzavalishin** [ultralytics/ultralytics#13474]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to train the pretrained model yolov8s-seg with new data with 3 new classes and save old weights. I updated the nc parameter in the .yaml file to 83 and added my new classes to the end of the class list. I use the following line to train the model:
` model.train(
    data=data_path,
    epochs=100,
    device='0',
    resume=True
)`

But because of the resume parameter I get the following error:

`SyntaxError: 'image_weights' is not a valid YOLO argument. 
'fl_gamma' is not a valid YOLO argument. 
'v5loader' is not a valid YOLO argument.`

If this parameter is not specified, there will be no error.

Thanks in advance.

**Comment by gzavalishin** [comment]
> Hello,
> 
> Thank you for reaching out and for providing detailed information about your issue. It looks like you're encountering an error when trying to resume training with the `resume=True` parameter. This error might be due to the presence of deprecated or invalid arguments in the checkpoint file.
> 
> To address this, please follow these steps:
> 
> 1. **Ensure Latest Versions**: First, make sure you are using the latest versions of `torch` and `ultralytics`. You can upgrade them using the following commands:
>    ```shell
>    pip install --upgrade torch ultralytics
>    ```
> 2. **Modify Training Command**: Instead of using the `resume=True` parameter, you can manually load the pretrained weights and continue training without the deprecated arguments. Here’s how you can do it:
>    ```python
>    from ultralytics import YOLO
>    
>    # Load the pretrained model
>    model = YOLO('yolov8s-seg.pt')
>    
>    # Update the model configuration for new classes
>    model.model.nc = 83  # Update number of classes
>    model.names += ['new_class1', 'new_class2', 'new_class3']  # Add new class names
>    
>    # Train the model with new data
>    results = model.train(
>        data='path/to/your/data.yaml',
>        epochs=100,
>        device='0'
>    )
>    ```
> 3. **Check YAML Configuration**: Ensure that your dataset YAML file is correctly configured with paths to your new dataset and the updated class list.
> 4. **Save Checkpoints**: If you want to save the model weights periodically, you can use the `save_period` argument to specify the frequency of saving checkpoints:
>    ```python
>    results = model.train(
>        data='path/to/your/data.yaml',
>        epochs=100,
>        device='0',
>        save_period=10  # Save checkpoint every 10 epochs
>    )
>    ```
> 
> By following these steps, you should be able to continue training your YOLOv8 segmentation model with new data and classes without encountering the deprecated argument error.
> 
> If the issue persists, please provide a minimum reproducible example of your code and dataset configuration. This will help us investigate further. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.
> 
> Feel free to reach out if you have any more questions or need further assistance. Happy training! 🚀

If I use your code from step 2, I get the following error:

`model.names += ['new_class1', 'new_class2', 'new_class3'] # Add new class names
TypeError: unsupported operand type(s) for +=: 'dict' and 'list'`

I decided to use the following code:
`model.names[80] = 'Round-manhole-cover' # Add new class names
model.names[81] = 'Square-manhole-cover'
model.names[82] = 'pothole'`

But debugging, after executing these lines, no new entries are added to the names dictionary. What can be wrong?

**Comment by glenn-jocher** [comment]
Hello,

Thank you for your detailed follow-up and for providing the code snippet you used. I appreciate your effort in troubleshooting the issue. Let's address the problem you're encountering with updating the class names.

The error you encountered (`TypeError: unsupported operand type(s) for +=: 'dict' and 'list'`) indicates that `model.names` is a dictionary, and you cannot use the `+=` operator to add new entries to a dictionary. Your approach to directly assigning new class names using dictionary indexing is correct, but it seems the changes are not being reflected.

Let's ensure that the model's class names are updated correctly. Here’s a refined approach:

1. **Load the Pretrained Model**: Ensure the model is loaded correctly.
2. **Update the Number of Classes**: Set the `nc` attribute to the new number of classes.
3. **Update Class Names**: Modify the `names` dictionary to include the new class names.

Here’s the updated code:

```python
from ultralytics import YOLO

# Load the pretrained model
model = YOLO('yolov8s-seg.pt')

# Update the model configuration for new classes
model.model.nc = 83  # Update number of classes

# Update the names dictionary with new class names
model.names.update({
    80: 'Round-manhole-cover',
    81: 'Square-manhole-cover',
    82: 'pothole'
})

# Verify the changes
print(model.names)

# Train the model with new data
results = model.train(
    data='sa.yaml',
    epochs=100,
    device='0'
)
```

### Key Points:
- **Updating the Dictionary**: Use the `update` method to add new entries to the `names` dictionary.
- **Verification**: Print the `model.names` to verify that the new class names have been added correctly.

### Additional Tips:
- **Ensure Data Consistency**: Make sure your dataset YAML file (`sa.yaml`) is correctly configured with paths to your new dataset and includes the updated class list.
- **Check for Errors**: If you encounter any further issues, please provide a minimum reproducible example of your code and dataset configuration. This will help us investigate further.

If you continue to experience issues, please ensure you are using the latest versions of `torch` and `ultralytics` by running:
```shell
pip install --upgrade torch ultralytics
```

Feel free to reach out if you have any more questions or need further assistance. Happy training! 🚀

**Comment by gzavalishin** [comment]
Hi, thanks for the detailed response. Tried to use the updated code, but the classes are still not added. Here is what I can see in the terminal:
![image](https://github.com/ultralytics/ultralytics/assets/113890858/848b2b17-e1b4-4306-a2e2-fbba85d33299)
What else could be wrong?
Thanks in advance

**Comment by glenn-jocher** [comment]
Hello,

Thank you for your patience and for providing the screenshot. Let's dive deeper to ensure we get this resolved for you.

### Steps to Verify and Resolve

1. **Ensure Latest Versions**:
   First, let's make sure you are using the latest versions of `torch` and `ultralytics`. This ensures that any recent bug fixes or improvements are included:
   ```bash
   pip install --upgrade torch ultralytics
   ```

2. **Verify Model Configuration**:
   Let's double-check that the model configuration is being updated correctly. Here’s a refined version of the code to ensure the changes are applied:

   ```python
   from ultralytics import YOLO

   # Load the pretrained model
   model = YOLO('yolov8s-seg.pt')

   # Update the model configuration for new classes
   model.model.nc = 83  # Update number of classes

   # Update the names dictionary with new class names
   new_classes = {
       80: 'Round-manhole-cover',
       81: 'Square-manhole-cover',
       82: 'pothole'
   }
   model.names.update(new_classes)

   # Verify the changes
   print("Updated class names:", model.names)

   # Train the model with new data
   results = model.train(
       data='sa.yaml',
       epochs=100,
       device='0'
   )
   ```

3. **Check Dataset Configuration**:
   Ensure your `sa.yaml` dataset configuration file is correctly set up with the new classes. Here’s an example of what it should look like:

   ```yaml
   train: path/to/train/images
   val: path/to/val/images

   nc: 83
   names:
     0: 'person'
     1: 'bicycle'
     ...
     80: 'Round-manhole-cover'
     81: 'Square-manhole-cover'
     82: 'pothole'
   ```

4. **Minimum Reproducible Example**:
   If the issue persists, could you please provide a minimum reproducible example of your code and dataset configuration? This will help us investigate further. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

### Additional Tips:
- **Print Statements**: Use print statements to debug and ensure that the class names are being updated correctly before training starts.
- **Checkpoints**: Ensure that any checkpoints or saved models are not overriding your changes.

Feel free to reach out if you have any more questions or need further assistance. We're here to help! 😊

**Comment by gzavalishin** [comment]
Hi! 
I have checked, I have the latest versions of torch and ultralytics installed:
![image](https://github.com/ultralytics/ultralytics/assets/113890858/e979998c-c6b5-4291-9f9c-857d4085ceda)

I also checked if the dataset is configured correctly:
train: path/to/train/images
val: path/to/val/images

`nc: 83
names:
  0: 'person'
  1: 'bicycle'
  ...
  80: 'Round-manhole-cover'
  81: 'Square-manhole-cover'
  82: 'pothole'`

I used the following code to configure the model:
```python
from ultralytics import YOLO

# Load the pretrained model
model = YOLO('yolov8s-seg.pt')

# Update the model configuration for new classes
model.model.nc = 83  # Update number of classes

# Update the names dictionary with new class names
new_classes = {
    80: 'Round-manhole-cover',
    81: 'Square-manhole-cover',
    82: 'pothole'
}
model.names.update(new_classes)

# Verify the changes
print("Updated class names:", model.names)

# Train the model with new data
results = model.train(
    data='sa.yaml',
    epochs=100,
    device='0'
)
```
But in print I see the following, no new classes are added to the model:
![image](https://github.com/ultralytics/ultralytics/assets/113890858/5ff591e1-11a7-4303-8a80-508a0d5420e2)

What could be the error. Thanks in advance!

**Comment by glenn-jocher** [comment]
Hi there!

Thank you for providing the detailed information and screenshots. It's great to see that you have the latest versions of `torch` and `ultralytics` installed and that your dataset configuration seems to be in order.

Let's address the issue with updating the class names. It appears that the new classes are not being reflected in the model's `names` dictionary. Let's take a closer look at the process to ensure everything is set up correctly.

### Steps to Resolve

1. **Ensure Model Configuration Update**:
   Let's make sure the model configuration is updated correctly before starting the training. Here’s a refined version of your code to ensure the changes are applied:

   ```python
   from ultralytics import YOLO

   # Load the pretrained model
   model = YOLO('yolov8s-seg.pt')

   # Update the model configuration for new classes
   model.model.nc = 83  # Update number of classes

   # Update the names dictionary with new class names
   new_classes = {
       80: 'Round-manhole-cover',
       81: 'Square-manhole-cover',
       82: 'pothole'
   }
   model.names.update(new_classes)

   # Verify the changes
   print("Updated class names:", model.names)

   # Train the model with new data
   results = model.train(
       data='sa.yaml',
       epochs=100,
       device='0'
   )
   ```

2. **Check Dataset Configuration**:
   Ensure your `sa.yaml` dataset configuration file is correctly set up with the new classes. Here’s an example of what it should look like:

   ```yaml
   train: coco8-seg/images/train
   val: coco8-seg/images/val

   nc: 83
   names:
     0: 'person'
     1: 'bicycle'
     ...
     80: 'Round-manhole-cover'
     81: 'Square-manhole-cover'
     82: 'pothole'
   ```

3. **Verify Changes Before Training**:
   Use print statements to debug and ensure that the class names are being updated correctly before training starts. This will help confirm that the changes are applied as expected.

### Additional Tips:
- **Print Statements**: Use print statements to debug and ensure that the class names are being updated correctly before training starts.
- **Checkpoints**: Ensure that any checkpoints or saved models are not overriding your changes.

If the issue persists, please provide a minimum reproducible example of your code and dataset configuration. This will help us investigate further. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

Feel free to reach out if you have any more questions or need further assistance. We're here to help! 😊

Happy training! 🚀

**Comment by HANSHIKA28** [comment]
%cd {HOME}

!yolo task=detect mode=train model=yolov8m.pt data=/content/datasets/EEP_Detection/data.yaml epochs=5 imgsz=640 save_period=1 save_dir=results

how can i modify this, so that i can train this for 30 epochs at a time such that after first 30, on resuming it will start from 31 epoch, KINDLY HELP

**Comment by glenn-jocher** [comment]
@HANSHIKA28 hello!

Thank you for your question. To achieve training in stages and resume from a specific epoch, you can follow these steps:

1. **Initial Training**: Train your model for the first 30 epochs and save the checkpoints.
2. **Resume Training**: Resume training from the saved checkpoint, continuing from epoch 31.

Here’s how you can do it:

### Step 1: Initial Training for 30 Epochs
```bash
%cd {HOME}

!yolo task=detect mode=train model=yolov8m.pt data=/content/datasets/EEP_Detection/data.yaml epochs=30 imgsz=640 save_period=1 save_dir=results
```

### Step 2: Resume Training from Epoch 31
After the initial training, you can resume training from the last saved checkpoint:
```bash
%cd {HOME}

!yolo task=detect mode=train model=results/weights/last.pt data=/content/datasets/EEP_Detection/data.yaml epochs=60 imgsz=640 save_period=1 save_dir=results
```
In this command, `epochs=60` means the total number of epochs you want to train, so it will continue from epoch 31 to 60.

### Important Notes:
- Ensure you have the latest versions of `torch` and `ultralytics` installed to avoid any compatibility issues.
- Verify that your dataset configuration file (`data.yaml`) is correctly set up.

If you encounter any issues, please provide a minimum reproducible example of your code and dataset configuration. This will help us investigate further. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

Happy training! 🚀

Feel free to reach out if you have any more questions or need further assistance. 😊

**Comment by HANSHIKA28** [comment]
I did the same, gave this command line:

%cd {HOME}

!yolo task=detect mode=train model=yolov8m.pt data=/content/datasets/EEP_Detection/data.yaml epochs=30 imgsz=640 save_period=1 save_dir=results

But got:

/content
save_period is not a valid key. Similar keys: ['save_hybrid', 'save_crop', 'save_json']
save_dir is not a valid key. Similar keys: ['save_crop', 'save', 'save_hybrid']

Kindly help!

**Comment by glenn-jocher** [comment]
Hello,

Thank you for your message. It looks like there are some issues with the command-line arguments you're using. Specifically, `save_period` and `save_dir` are not recognized keys.

To save checkpoints periodically and specify the save directory, you can use the following corrected command:

```bash
%cd {HOME}

!yolo task=detect mode=train model=yolov8m.pt data=/content/datasets/EEP_Detection/data.yaml epochs=30 imgsz=640 project=results name=exp save_period=1
```

### Explanation:
- **`project`**: Specifies the directory where the results will be saved.
- **`name`**: Specifies the name of the experiment, creating a subdirectory within the project directory.
- **`save_period`**: Correctly used to save checkpoints periodically.

If you continue to experience issues, please ensure you are using the latest versions of `torch` and `ultralytics` by running:
```bash
pip install --upgrade torch ultralytics
```

If the issue persists, providing a minimum reproducible example would be very helpful. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

Feel free to reach out if you have any more questions or need further assistance. Happy training! 🚀
