### ISSUE TITLE
Question: Is there a way to use yolov8 to multiple streaming sources ?

### ISSUE THREAD

**Issue by Anas-Inam** [ultralytics/ultralytics#1350]
How to load multiple video streams from two different sources (in my case two different IP cameras) with two different models (one for vehicle/people detection and the other for license plate detection ) using a single python script ?

Right now I have two different scripts that are doing that but I was wondering if you could do this in a single python script.

**Comment by glenn-jocher** [comment]
@Anas-Inam yes you can do this by adding multiple sources to a sources.csv file. See https://docs.ultralytics.com/predict/

**Comment by Anas-Inam** [comment]
How can I do that if I want to use two different models ?

**Comment by mriamnobody** [comment]
> @Anas-Inam yes you can do this by adding multiple sources to a sources.csv file. See https://docs.ultralytics.com/predict/

This is link is working no more. Here is the new link https://docs.ultralytics.com/modes/predict/

**Comment by WoutMommen** [comment]
What is the format of such streaming sources in the .csv file?

At the moment I have two videos of which I put the paths in the .csv file:
![image](https://github.com/ultralytics/ultralytics/assets/57433859/61d6cf15-a205-4593-ba96-d48b75358d7f)
Next, I just use the predict function as explained in the documentation (the .csv file is located in the same directory as both videos):
![image](https://github.com/ultralytics/ultralytics/assets/57433859/23d92372-3552-449a-bb64-fcaed0f02b42)
However, the following error is given:
![image](https://github.com/ultralytics/ultralytics/assets/57433859/770c1aa8-5d17-475e-ad8c-6b811d010c6e)

I also tried writing paths without quotes and/or using a relative path, but that did not work.

**Comment by glenn-jocher** [comment]
@WoutMommen hello and thank you for your question!

Regarding the format of the streaming sources in the `sources.csv` file, each separate line should contain a single source, specified by either the direct path to the video file, a number representing a webcam device ID (e.g. 0 or 1 for first or second webcam), or a URL for RTSP, HLS or HTTP streams. You don't need to put quotes around the paths. 

Regarding the error you're encountering, it seems like the source path is not found. It could be a problem related to relative or absolute paths. Please make sure your paths are correctly specified, and that the source files are accessible from the directory where you're running the script. Also, please ensure that there are no mistakes in the file names or extensions. 

Lastly, remember to also ensure that the required libraries for video reading (like opencv-python) are correctly installed.

**Comment by pedromoraesh** [comment]
> @Anas-Inam yes you can do this by adding multiple sources to a sources.csv file. See https://docs.ultralytics.com/predict/

Glenn, I trying to process multiple mp4 video files, 1 hour each every day, every hour. My question is: When I use a CSV file as the source where I put one video for each line, how does the Yolov8 handle the inference on multiple sources? There is only one model object wich processes all of them simultaneously similar to batch processing or it will process only one file at a time?
That behavior is the same when I write all my sources in an array and send it to the YOLO object? 

Thanks in advance

**Comment by glenn-jocher** [comment]
@pedromoraesh your question pertains to how YOLOv8 handles multiple sources and whether it processes them simultaneously or one at a time. When you use a CSV file with each line as a different video source, YOLOv8 processes them sequentially - one at a time, not simultaneously. The same holds true when you provide multiple sources as an array. The model infers the videos one after another rather than all at once. I hope this helps. Please feel free to ask if you have further questions!

**Comment by kashrupee** [comment]
For those who are having issues with getting paths to work using CSV files, try changing the file extension to .txt instead of .csv.  I was banging my head against the wall for days until I decided to open the predictor.py file and read the comments.  Screenshot below.

~\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\predictor.py

![Screenshot 2023-10-14 230141](https://github.com/ultralytics/ultralytics/assets/147588370/94ccb433-6b0d-479c-ae70-33e01ac1f788)

**Comment by KicoSVK** [comment]
@kashrupee Many, many thanks man! I am going to try it now.

**Comment by glenn-jocher** [comment]
@KicoSVK, you're welcome! If you have any more questions or run into any issues, don't hesitate to reach out. Good luck with your development!

**Comment by Nishanth21D** [comment]
Hello Every1,

I have one small doubt and I need help from you guys. Let's say I am running a detection algorithm on 10 streams using 10 threading. Is it possible to get output results from those threading without finishing? Let's say I am detecting bikes on 10 streams, and if a bike is detected on stream 3, can I get the result from stream 3 alone meanwhile other threads still detecting?

If there are other methods please do let me know.

Thanks in advance.

**Comment by glenn-jocher** [comment]
Hello!

Great question! Yes, you can achieve this by utilizing a concurrent approach that allows each thread to independently handle its respective video stream. In Python, you can use the `queue` module to manage the outputs from each thread effectively. Here's a brief example:

```python
from threading import Thread
import queue

def detect_bikes(stream_id, output_queue):
    # Your detection logic here
    if bike_detected:
        output_queue.put((stream_id, 'Bike detected'))

output_queue = queue.Queue()
threads = []

for i in range(10):  # Assuming 10 streams
    thread = Thread(target=detect_bikes, args=(i, output_queue))
    thread.start()
    threads.append(thread)

# Retrieve results as they become available
while any(t.is_alive() for t in threads):
    while not output_queue.empty():
        stream_id, message = output_queue.get()
        print(f'Result from stream {stream_id}: {message}')

for t in threads:
    t.join()
```

This setup allows each thread to independently post results to a shared queue that you can monitor and process results from, even as other threads continue detection. This should help you get results from individual streams without waiting for all to complete.

Hope this helps! Let me know if you need further assistance. Happy coding! 😊

**Comment by Nishanth21D** [comment]
Thank you @glenn-jocher, I feel this will resolve my issue. Thanks for the code snippet too it sure helps.

Happy Coding & Learing :-)

**Comment by glenn-jocher** [comment]
You're welcome! I'm glad to hear that the snippet is helpful. If you have any more questions down the road, feel free to ask. Happy coding and learning to you too! 😊🚀

**Comment by Rizwanali324** [comment]
@glenn-jocher  
i am confused regarding the models 
I have different streams (camera locations ) one for cup shelves and others for customer walking. 

do I need to build one model for these two streams or two ?

**Comment by Rizwanali324** [comment]
> You can use a single YOLO11 model if you train it on both classes (cups and people). For optimal performance across different camera angles/scenarios, we recommend training one unified model. The Predict documentation shows how to handle multiple streams with a single model using threading or batched inference. If you need separate specialized models, see the Multithreaded Tracking example for simultaneous processing of different models/streams.

can you suggest me edge devices for this which can run 6 stream with one model ?
I'm planing use to use jetson nano . and any future direction  for web app dashboard deployments on it for real time  analytics

**Comment by glenn-jocher** [comment]
For 6-stream edge deployment with YOLO11, consider NVIDIA Jetson Orin Nano Super (see [DeepStream on NVIDIA Jetson](https://docs.ultralytics.com/guides/deepstream-nvidia-jetson/)) or Jetson Orin NX 16GB for higher throughput. While Jetson Nano works for lightweight tasks, Orin devices offer 5-10X performance gains for multi-stream workloads. For web dashboards, explore FastAPI/Flask backends with Streamlit/Gradio frontends, or integrate Ultralytics HUB SDK for real-time analytics. The [Ultralytics Deployment Guide](https://docs.ultralytics.com/guides/model-deployment-options/) outlines web deployment strategies.
