### ISSUE TITLE
Confidence threshold 

### ISSUE THREAD

**Issue by prasen832** [ultralytics/ultralytics#13512]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

What is default confidence threshold of YOLO v8.2 model and how to change it ?

**Comment by glenn-jocher** [comment]
Hello!

Thank you for your question and for checking the existing issues and discussions before posting. The default confidence threshold for YOLOv8.2 is set to `0.25`. This threshold determines the minimum confidence score for detections to be considered valid.

To change the confidence threshold, you can adjust the `conf` parameter when running predictions. Here’s how you can do it using both the Python API and the Command Line Interface (CLI):

### Python Example
```python
from ultralytics import YOLO

# Load a YOLOv8 model
model = YOLO("yolov8n.pt")

# Run predictions with a custom confidence threshold
results = model.predict(source="path/to/your/image.jpg", conf=0.5)  # Set confidence threshold to 0.5
```

### CLI Example
```bash
yolo predict model=yolov8n.pt source=path/to/your/image.jpg conf=0.5
```

Feel free to adjust the `conf` value to suit your specific needs. If you encounter any issues or have further questions, please don't hesitate to ask. Happy experimenting! 😊

**Comment by prasen832** [comment]
Thanks

**Comment by glenn-jocher** [comment]
@prasen832 hello!

Thank you for reaching out. To address your question about the default confidence threshold and how to change it:

The default confidence threshold for YOLOv8.2 is set to `0.25`. This threshold determines the minimum confidence score for detections to be considered valid. If you wish to adjust this threshold, you can do so using the `conf` parameter.

### Changing Confidence Threshold

#### Python Example
```python
from ultralytics import YOLO

# Load a YOLOv8 model
model = YOLO("yolov8n.pt")

# Run predictions with a custom confidence threshold
results = model.predict(source="path/to/your/image.jpg", conf=0.5)  # Set confidence threshold to 0.5
```

#### CLI Example
```bash
yolo predict model=yolov8n.pt source=path/to/your/image.jpg conf=0.5
```

If you encounter any issues or have further questions, please don't hesitate to ask. We're here to help! 😊
