### ISSUE TITLE
Joint angle detection

### ISSUE THREAD

**Issue by srinidhi0476** [ultralytics/ultralytics#13517]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Good evening
I am using YOLOv8 AIGYM model for calculating the joint angle. Elbow and Shoulder angle is detecting. I want Hip, Knee, Neck angles. Below I provided the code. Suggest me how to get knee, hip, neck angles for video file

### Additional

from ultralytics import YOLO
from ultralytics.solutions import ai_gym
import cv2

model = YOLO("yolov8n-pose.pt")
cap = cv2.VideoCapture("S:\Field video for RULA and REBA\Sudha Babai\Sudha digging traditional right.mp4")
assert cap.isOpened(), "Error reading video file"
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

gym_object1 =  ai_gym.AIGym()
gym_object1.set_args(line_thickness=2, view_img=True, pose_type="pullup", kpts_to_check=[8, 6, 12])

# Initialize AI Gym module for elbow angle measurement
gym_object2 =  ai_gym.AIGym()
gym_object2.set_args(line_thickness=2, view_img=True, pose_type="pullup", kpts_to_check=[10, 8, 6])

gym_object3 = ai_gym.AIGym()
gym_object3.set_args(line_thickness=2, view_img=True, pose_type="pushup", kpts_to_check=[6, 4, 2])

frame_count = 0
while cap.isOpened():
    success, im0 = cap.read()
    print(success)
    if not success:
      print("Video frame is empty or video processing has been successfully completed.")
      break
    frame_count += 1
    results = model.track(im0, verbose=False)  # Tracking recommended
    
    results = model.predict(im0)  # Prediction also supported
    im0 = gym_object1.start_counting(im0, results, frame_count)
    im1 = gym_object2.start_counting(im0, results, frame_count)
    im3 = gym_object2.start_counting(im0, results, frame_count)
    if (frame_count%20)==0:
      cv2.imwrite("Frame_" + str(frame_count)+".png",im0)
     
cv2.destroyAllWindows()

**Comment by srinidhi0476** [comment]
Good evening
I am using YOLOv8 AIGYM model for calculating the joint angle. Elbow and Shoulder angle is detecting. I want Hip, Knee, Neck angles. Below I provided the code. Suggest me how to get knee, hip, neck angles for video file. Do needfull

**Comment by glenn-jocher** [comment]
Good evening!

Thank you for reaching out and providing your code example. It's great to hear that you're using the YOLOv8 AIGYM model for joint angle detection! To calculate the angles for the hip, knee, and neck, you can adjust the `kpts_to_check` parameter to include the keypoints corresponding to these joints.

Here's a brief guide on how to set up the keypoints for hip, knee, and neck angles:

- **Hip Angle**: Typically involves keypoints for the hip, knee, and shoulder.
- **Knee Angle**: Involves keypoints for the knee, hip, and ankle.
- **Neck Angle**: Involves keypoints for the neck, shoulder, and head.

Below is an updated version of your code to include these angles:

```python
from ultralytics import YOLO
from ultralytics.solutions import ai_gym
import cv2

model = YOLO("yolov8n-pose.pt")
cap = cv2.VideoCapture("S:/Field video for RULA and REBA/Sudha Babai/Sudha digging traditional right.mp4")
assert cap.isOpened(), "Error reading video file"
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

# Initialize AI Gym module for hip angle measurement
gym_object_hip = ai_gym.AIGym()
gym_object_hip.set_args(line_thickness=2, view_img=True, pose_type="pushup", kpts_to_check=[12, 14, 16])  # Hip, Knee, Ankle

# Initialize AI Gym module for knee angle measurement
gym_object_knee = ai_gym.AIGym()
gym_object_knee.set_args(line_thickness=2, view_img=True, pose_type="pushup", kpts_to_check=[14, 12, 24])  # Knee, Hip, Shoulder

# Initialize AI Gym module for neck angle measurement
gym_object_neck = ai_gym.AIGym()
gym_object_neck.set_args(line_thickness=2, view_img=True, pose_type="pushup", kpts_to_check=[0, 6, 8])  # Head, Shoulder, Neck

frame_count = 0
while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break
    frame_count += 1
    results = model.track(im0, verbose=False)  # Tracking recommended
    
    # Calculate angles
    im0 = gym_object_hip.start_counting(im0, results, frame_count)
    im0 = gym_object_knee.start_counting(im0, results, frame_count)
    im0 = gym_object_neck.start_counting(im0, results, frame_count)
    
    if frame_count % 20 == 0:
        cv2.imwrite("Frame_" + str(frame_count) + ".png", im0)
     
cv2.destroyAllWindows()
```

In this code:
- `kpts_to_check` for the hip angle is set to `[12, 14, 16]` (hip, knee, ankle).
- `kpts_to_check` for the knee angle is set to `[14, 12, 24]` (knee, hip, shoulder).
- `kpts_to_check` for the neck angle is set to `[0, 6, 8]` (head, shoulder, neck).

Feel free to adjust the keypoint indices based on your specific requirements. For more detailed information on keypoints and their indices, you can refer to the [Ultralytics documentation](https://docs.ultralytics.com/guides/workouts-monitoring/).

If you encounter any issues or need further assistance, please let us know. We're here to help! 😊

**Comment by srinidhi0476** [comment]
Yes sir. I got the angles thank you. another one question how to remove the white rectangular box in which  joint angle text is indicating and I want to remove the step and up , down display on screen. I will attach the image below.
![Uploading Frame_200.png…]()

**Comment by glenn-jocher** [comment]
@srinidhi0476 hello!

I'm glad to hear that you were able to get the angles working! 😊

To remove the white rectangular box displaying the joint angle text and to hide the step and up/down indicators, you can modify the `AIGym` class to skip the drawing of these elements. Below is an example of how you can achieve this:

1. **Remove the White Rectangular Box and Text**:
   - You can comment out or remove the lines in the `plot_angle_and_count_and_stage` method that draw the box and text.

2. **Remove the Step and Up/Down Display**:
   - Similarly, you can comment out or remove the lines that draw the step and up/down indicators.

Here's an example of how you can modify the `AIGym` class:

```python
class AIGym:
    """A class to manage the gym steps of people in a real-time video stream based on their poses."""

    def __init__(
        self,
        kpts_to_check,
        line_thickness=2,
        view_img=False,
        pose_up_angle=145.0,
        pose_down_angle=90.0,
        pose_type="pullup",
    ):
        # Initialization code remains the same
        ...

    def start_counting(self, im0, results, frame_count):
        # Function used to count the gym steps
        ...

        for ind, k in enumerate(reversed(self.keypoints)):
            # Estimate angle and draw specific points based on pose type
            if self.pose_type in {"pushup", "pullup", "abworkout", "squat"}:
                self.angle[ind] = self.annotator.estimate_pose_angle(
                    k[int(self.kpts_to_check[0])].cpu(),
                    k[int(self.kpts_to_check[1])].cpu(),
                    k[int(self.kpts_to_check[2])].cpu(),
                )
                self.im0 = self.annotator.draw_specific_points(k, self.kpts_to_check, shape=(640, 640), radius=10)

                # Check and update pose stages and counts based on angle
                if self.pose_type in {"abworkout", "pullup"}:
                    if self.angle[ind] > self.poseup_angle:
                        self.stage[ind] = "down"
                    if self.angle[ind] < self.posedown_angle and self.stage[ind] == "down":
                        self.stage[ind] = "up"
                        self.count[ind] += 1

                elif self.pose_type in {"pushup", "squat"}:
                    if self.angle[ind] > self.poseup_angle:
                        self.stage[ind] = "up"
                    if self.angle[ind] < self.posedown_angle and self.stage[ind] == "up":
                        self.stage[ind] = "down"
                        self.count[ind] += 1

                # Comment out or remove the following lines to hide the text and boxes
                # self.annotator.plot_angle_and_count_and_stage(
                #     angle_text=self.angle[ind],
                #     count_text=self.count[ind],
                #     stage_text=self.stage[ind],
                #     center_kpt=k[int(self.kpts_to_check[1])],
                # )

            # Draw keypoints
            self.annotator.kpts(k, shape=(640, 640), radius=1, kpt_line=True)

        # Display the image if environment supports it and view_img is True
        if self.env_check and self.view_img:
            cv2.imshow("Ultralytics YOLOv8 AI GYM", self.im0)
            if cv2.waitKey(1) & 0xFF == ord("q"):
                return

        return self.im0
```

By commenting out the `plot_angle_and_count_and_stage` method call, you will remove the white rectangular box and the step/up/down display from the output.

Feel free to adjust the code further based on your specific requirements. If you have any more questions or need further assistance, don't hesitate to ask. We're here to help! 🚀

**Comment by srinidhi0476** [comment]
Good afternoon sir, I tried the method that you had mentioned above and I
am facing two problems
1. For a single frame/image the angles were changing instead of being
constant
2. Along with stage and count text, angle was also got removed

So, could you please tell me the solutions for the above mentioned problems?

**Comment by srinidhi0476** [comment]
![Frame_20](https://github.com/ultralytics/ultralytics/assets/172388575/9851042d-a425-44b9-9b76-5503067e0fe0)
Above mentioned problem are not getting solved . please will you suggest me how to resolve this issues

**Comment by glenn-jocher** [comment]
Good afternoon @srinidhi0476,

Thank you for your patience and for providing additional details. Let's address the issues you're facing:

1. **Angles Changing for a Single Frame/Image**:
   - This issue might be due to the way the angles are being calculated and displayed. Ensure that the keypoints are correctly identified and that the angle calculation is consistent. If the keypoints are fluctuating, it could cause the angles to change. You might want to add some smoothing or averaging to stabilize the keypoints.

2. **Removing the White Rectangular Box and Stage/Count Text**:
   - To remove the stage and count text while keeping the angle display, you can modify the `plot_angle_and_count_and_stage` method to only draw the angle text. Here's how you can do it:

```python
class AIGym:
    """A class to manage the gym steps of people in a real-time video stream based on their poses."""

    def __init__(
        self,
        kpts_to_check,
        line_thickness=2,
        view_img=False,
        pose_up_angle=145.0,
        pose_down_angle=90.0,
        pose_type="pullup",
    ):
        # Initialization code remains the same
        ...

    def start_counting(self, im0, results, frame_count):
        # Function used to count the gym steps
        ...

        for ind, k in enumerate(reversed(self.keypoints)):
            # Estimate angle and draw specific points based on pose type
            if self.pose_type in {"pushup", "pullup", "abworkout", "squat"}:
                self.angle[ind] = self.annotator.estimate_pose_angle(
                    k[int(self.kpts_to_check[0])].cpu(),
                    k[int(self.kpts_to_check[1])].cpu(),
                    k[int(self.kpts_to_check[2])].cpu(),
                )
                self.im0 = self.annotator.draw_specific_points(k, self.kpts_to_check, shape=(640, 640), radius=10)

                # Check and update pose stages and counts based on angle
                if self.pose_type in {"abworkout", "pullup"}:
                    if self.angle[ind] > self.poseup_angle:
                        self.stage[ind] = "down"
                    if self.angle[ind] < self.posedown_angle and self.stage[ind] == "down":
                        self.stage[ind] = "up"
                        self.count[ind] += 1

                elif self.pose_type in {"pushup", "squat"}:
                    if self.angle[ind] > self.poseup_angle:
                        self.stage[ind] = "up"
                    if self.angle[ind] < self.posedown_angle and self.stage[ind] == "up":
                        self.stage[ind] = "down"
                        self.count[ind] += 1

                # Modify this method to only display the angle text
                self.annotator.plot_angle_only(
                    angle_text=self.angle[ind],
                    center_kpt=k[int(self.kpts_to_check[1])],
                )

            # Draw keypoints
            self.annotator.kpts(k, shape=(640, 640), radius=1, kpt_line=True)

        # Display the image if environment supports it and view_img is True
        if self.env_check and self.view_img:
            cv2.imshow("Ultralytics YOLOv8 AI GYM", self.im0)
            if cv2.waitKey(1) & 0xFF == ord("q"):
                return

        return self.im0
```

And in the `annotator` class, you can add the `plot_angle_only` method:

```python
class Annotator:
    def plot_angle_only(self, angle_text, center_kpt):
        # Draw the angle text without the box and other text
        cv2.putText(
            self.im0,
            f"{angle_text:.1f}",
            (int(center_kpt[0]), int(center_kpt[1])),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.5,
            (255, 255, 255),
            2,
            cv2.LINE_AA,
        )
```

This should help in displaying only the angle text without the white rectangular box and the stage/count text.

If you continue to face issues, please ensure you are using the latest versions of `torch` and `ultralytics`. If the problem persists, providing a minimum reproducible code example would be very helpful for further investigation. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

Feel free to reach out if you have any more questions or need further assistance. We're here to help! 😊
