### ISSUE TITLE
how to validate my model on different MAP values ? for ex: at 0.7 , 0.9

### ISSUE THREAD

**Issue by Amr-Abdellatif** [ultralytics/ultralytics#13526]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm wondering if i could evaluate my model on evaluation dataset with different MAP values , the default value is at 0.5 and 0.5-95 ,, can these be modified to look at different MAP's like at 0.7 , 0.8 , 0.85 and so ...
@glenn-jocher

**Comment by glenn-jocher** [comment]
Hello!

Thank you for your question and for checking the existing issues and discussions beforehand. To evaluate your model at different mAP (mean Average Precision) thresholds, you can indeed modify the thresholds to get a more detailed performance analysis.

By default, YOLOv8 evaluates mAP at 0.5 (mAP50) and across a range from 0.5 to 0.95 (mAP50-95). However, you can customize this to evaluate at specific thresholds like 0.7, 0.8, 0.85, etc.

Here's how you can do it:

### Using Python

You can specify the `iou` (Intersection Over Union) threshold when calling the `val` method in Python:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('path/to/your/model.pt')

# Validate the model at different IoU thresholds
results_07 = model.val(iou=0.7)
results_08 = model.val(iou=0.8)
results_085 = model.val(iou=0.85)

# Print the results
print(f"mAP at IoU 0.7: {results_07.box.map}")
print(f"mAP at IoU 0.8: {results_08.box.map}")
print(f"mAP at IoU 0.85: {results_085.box.map}")
```

### Using CLI

If you prefer using the command line interface, you can specify the `iou` argument directly:

```bash
# Validate at IoU 0.7
yolo val model=path/to/your/model.pt iou=0.7

# Validate at IoU 0.8
yolo val model=path/to/your/model.pt iou=0.8

# Validate at IoU 0.85
yolo val model=path/to/your/model.pt iou=0.85
```

### Important Notes

1. **Ensure Latest Versions**: Make sure you are using the latest versions of `torch` and `ultralytics` to avoid any compatibility issues. You can upgrade them using:
    ```bash
    pip install --upgrade torch ultralytics
    ```

2. **Reproducible Example**: If you encounter any issues or bugs while performing these evaluations, please provide a minimum reproducible code example. This helps us investigate and resolve the issue more efficiently. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions or run into any issues. Happy validating! 🚀

**Comment by Amr-Abdellatif** [comment]
Thanks alot, that helped much, so I was wondering can I do that also in training ?

**Comment by Amr-Abdellatif** [comment]
@glenn-jocher,  Thanks A lot glenn.

**Comment by glenn-jocher** [comment]
@Amr-Abdellatif hello!

You're very welcome! 😊

To validate your model at different mAP thresholds like 0.7, 0.8, and 0.85, you can adjust the `iou` parameter during the validation process. This will allow you to evaluate your model's performance at these specific thresholds.

### Using Python

Here's how you can do it in Python:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('path/to/your/model.pt')

# Validate the model at different IoU thresholds
results_07 = model.val(iou=0.7)
results_08 = model.val(iou=0.8)
results_085 = model.val(iou=0.85)

# Print the results
print(f"mAP at IoU 0.7: {results_07.box.map}")
print(f"mAP at IoU 0.8: {results_08.box.map}")
print(f"mAP at IoU 0.85: {results_085.box.map}")
```

### Using CLI

Alternatively, you can use the command line interface:

```bash
# Validate at IoU 0.7
yolo val model=path/to/your/model.pt iou=0.7

# Validate at IoU 0.8
yolo val model=path/to/your/model.pt iou=0.8

# Validate at IoU 0.85
yolo val model=path/to/your/model.pt iou=0.85
```

### Important Notes

1. **Ensure Latest Versions**: Make sure you are using the latest versions of `torch` and `ultralytics`. You can upgrade them using:
    ```bash
    pip install --upgrade torch ultralytics
    ```

2. **Reproducible Example**: If you encounter any issues or bugs, please provide a minimum reproducible code example. This helps us investigate and resolve the issue more efficiently. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions or run into any issues. Happy validating! 🚀
