### ISSUE TITLE
Ultralytics support v9 and v10 at the same package?

### ISSUE THREAD

**Issue by HduHestin** [ultralytics/ultralytics#13530]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, i want to build an api using v9 model and v10 model at the same time.
Some pypi version:
```
ultralytics                       8.2.31
ultralytics-thop                  0.2.8
```
There is my fisrt step code, it comes from 
[https://docs.ultralytics.com/zh/models/yolov9/#usage-examples](https://docs.ultralytics.com/zh/models/yolov9/#usage-examples)
[https://docs.ultralytics.com/zh/models/yolov10/#comparisons](https://docs.ultralytics.com/zh/models/yolov10/#comparisons)
```
from ultralytics import YOLO

v10_model=YOLO('yolov10m_handheld_20240611.pt')

v9_model=YOLO('yolov9-c.yaml')
v9_model = YOLO("yolov9c.pt")
v9_model.info()
```
Terminal outputs:
```
Traceback (most recent call last):
  File "C:\Users\chenyu\Desktop\yolo_api\api.py", line 3, in <module>
    v10_model=YOLO('yolov10m_handheld_20240611.pt')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "D:\Anaconda3\Lib\site-packages\ultralytics\engine\model.py", line 152, in __init__
    self._load(model, task=task)
  File "D:\Anaconda3\Lib\site-packages\ultralytics\engine\model.py", line 241, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\ultralytics\nn\tasks.py", line 806, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\ultralytics\nn\tasks.py", line 732, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\torch\serialization.py", line 1025, in load
    return _load(opened_zipfile,
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\torch\serialization.py", line 1446, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\torch\serialization.py", line 1439, in find_class
    return super().find_class(mod_name, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'YOLOv10DetectionModel' on <module 'ultralytics.nn.tasks' from 'D:\\Anaconda3\\Lib\\site-packages\\ultralytics\\nn\\tasks.py'>
```
different .pt model need different 'ultralytics' ? or two model must be divided into two environment? Hope someone can help me with this.

**Comment by Hestinorwu** [comment]
My problem is that i hope use "from ultralytics import YOLO" to load two different model.or use 'import YOLOv10'. because the precess and postcess of ultralytics is convenient.I can eastily get results.

**Comment by glenn-jocher** [comment]
Hello @Hestinorwu,

Thank you for reaching out! It's great to hear that you find the Ultralytics YOLO models convenient for your tasks. Let's address the issue you're encountering with loading both YOLOv9 and YOLOv10 models simultaneously.

The error you're seeing, `AttributeError: Can't get attribute 'YOLOv10DetectionModel'`, suggests that there might be a compatibility issue with the specific versions of the models and the `ultralytics` package you are using.

Here are a few steps to help resolve this:

1. **Ensure Latest Versions**: First, make sure you are using the latest versions of both `torch` and `ultralytics`. You can upgrade them using the following commands:
    ```bash
    pip install --upgrade torch ultralytics
    ```

2. **Separate Environments**: If the issue persists, it might be due to the fact that YOLOv9 and YOLOv10 models require different versions of the `ultralytics` package. In such cases, using separate virtual environments for each model can be a good solution. Here’s how you can set it up:

    - **Create Virtual Environments**:
        ```bash
        # Create a virtual environment for YOLOv9
        python -m venv yolov9_env
        # Activate the environment
        yolov9_env\Scripts\activate  # On Windows
        source yolov9_env/bin/activate  # On macOS/Linux
        # Install the required packages
        pip install ultralytics==<specific_version_for_v9> torch

        # Create a virtual environment for YOLOv10
        python -m venv yolov10_env
        # Activate the environment
        yolov10_env\Scripts\activate  # On Windows
        source yolov10_env/bin/activate  # On macOS/Linux
        # Install the required packages
        pip install ultralytics==<specific_version_for_v10> torch
        ```

3. **Example Code**: Here’s an example of how you can load and use both models in separate environments:

    - **YOLOv9 Environment**:
        ```python
        # Activate YOLOv9 environment
        yolov9_env\Scripts\activate  # On Windows
        source yolov9_env/bin/activate  # On macOS/Linux

        from ultralytics import YOLO

        v9_model = YOLO('yolov9c.pt')
        v9_results = v9_model('path/to/image.jpg')
        print(v9_results)
        ```

    - **YOLOv10 Environment**:
        ```python
        # Activate YOLOv10 environment
        yolov10_env\Scripts\activate  # On Windows
        source yolov10_env/bin/activate  # On macOS/Linux

        from ultralytics import YOLO

        v10_model = YOLO('yolov10m_handheld_20240611.pt')
        v10_results = v10_model('path/to/image.jpg')
        print(v10_results)
        ```

By using separate environments, you can ensure that each model has the appropriate dependencies and versions without conflicts.

If you continue to face issues, please provide a minimum reproducible example of your code so we can further investigate. You can refer to our [Minimum Reproducible Example Guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

I hope this helps! If you have any further questions, feel free to ask. 😊

**Comment by Hestinorwu** [comment]
Thanks a lot!!! i try to download the folder'ultralytics' of yolov10,and use `from ultralytics import yolov10` and successfully adapt it to my project. and i realize that v9 and v10 need different environment.So if i still to use yolov9 at the same time,i need to seperate both to exec each . Thanks again!

**Comment by glenn-jocher** [comment]
Hello @Hestinorwu,

You're very welcome! I'm glad to hear that you successfully adapted YOLOv10 to your project. 🎉

Indeed, separating the environments for YOLOv9 and YOLOv10 is a practical approach to avoid any compatibility issues. This way, you can ensure that each model operates with the appropriate dependencies and versions.

If you have any further questions or run into any issues, feel free to reach out. We're here to help! 😊

Happy coding and best of luck with your project!

**Comment by Hestinorwu** [comment]
Thanks for your reply,now i encounter a new problem. How to use Yolov9 cli to train data. it seems that in [https://github.com/WongKinYiu/yolov9](https://github.com/WongKinYiu/yolov9) the usage of cli is not supported.
Only usage like below:
`python train_dual.py --workers 8 --device 0 --batch 16 --data data/coco.yaml --img 640 --cfg models/detect/yolov9-c.yaml --weights '' --name yolov9-c --hyp hyp.scratch-high.yaml --min-items 0 --epochs 500 --close-mosaic 15`

![image](https://github.com/ultralytics/ultralytics/assets/89848374/74d0ac77-ca92-4297-839c-310bbcd52457)

**Comment by glenn-jocher** [comment]
Hello @HduHestin,

Thank you for your question! It appears that the YOLOv9 repository you mentioned ([WongKinYiu/yolov9](https://github.com/WongKinYiu/yolov9)) does not support CLI commands in the same way as Ultralytics YOLO models. Instead, it uses Python scripts for training.

To train a YOLOv9 model using the provided script, you can follow the example command you mentioned:

```bash
python train_dual.py --workers 8 --device 0 --batch 16 --data data/coco.yaml --img 640 --cfg models/detect/yolov9-c.yaml --weights '' --name yolov9-c --hyp hyp.scratch-high.yaml --min-items 0 --epochs 500 --close-mosaic 15
```

Here's a brief breakdown of the command:
- `--workers 8`: Number of data loading workers.
- `--device 0`: GPU device to use.
- `--batch 16`: Batch size.
- `--data data/coco.yaml`: Path to the dataset configuration file.
- `--img 640`: Image size.
- `--cfg models/detect/yolov9-c.yaml`: Path to the model configuration file.
- `--weights ''`: Path to the weights file (empty string for training from scratch).
- `--name yolov9-c`: Name of the training run.
- `--hyp hyp.scratch-high.yaml`: Path to the hyperparameters file.
- `--min-items 0`: Minimum number of items.
- `--epochs 500`: Number of training epochs.
- `--close-mosaic 15`: Number of epochs to disable mosaic augmentation before training ends.

If you encounter any issues or have specific questions about the training process, please provide more details or a minimum reproducible example so we can assist you better. You can refer to our [Minimum Reproducible Example Guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more information.

Feel free to reach out if you have any further questions. Happy training! 😊
