### ISSUE TITLE
A problem with slow first startup recognition using Gpus

### ISSUE THREAD

**Issue by qinsehm1128** [ultralytics/ultralytics#13545]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My main question is why the delay is very high when the image is loaded for recognition for the first time, the subsequent recognition speed will be normal, only the first time this problem will occur, the following is my code

```python
from ultralytics import YOLO
import time

if __name__ == '__main__':
    t = time.time()
    model = YOLO(
        r'C:\Users\Administrator\PycharmProjects\pythonProject\runs\detect\train4\weights\best.pt')

    print((time.time() - t) * 1000, "ms")
    for i in range(10):
        t = time.time()
        metrics = model.predict(source="0.png",
                                project='runs/detect',
                                name='exp',
                                save=True,
                                
                                # visualize=True # visualize model features maps
                                )
        print((time.time() - t) * 1000, "ms")
        for m in metrics:
            box = m.boxes
            for cls_idx, xyxy in zip(box.cls.tolist(), box.xyxy.tolist()):
                class_name = model.names[int(cls_idx)]
                x1, y1, x2, y2 = xyxy
                print(f"{class_name}: {x1:.2f} {y1:.2f} {x2:.2f} {y2:.2f}")
```

When I do not use mode.to("cuda"), the first recognition speed is 8200ms, the subsequent speed will drop to the normal level, here is the cmd print:

``` cmd 
image 1/1 D:\yolov8_py\ultralytics-main\ultralytics-main\0.png: 288x512 1 0, 1 1, 159.9ms
Speed: 2.0ms preprocess, 159.9ms inference, 3.0ms postprocess per image at shape (1, 3, 288, 512)
Results saved to runs\detect\exp84
8240.462303161621 ms
1: 257.90 97.21 377.45 218.20
0: 4.22 100.11 125.73 221.62

image 1/1 D:\yolov8_py\ultralytics-main\ultralytics-main\0.png: 288x512 1 0, 1 1, 13.0ms
Speed: 1.0ms preprocess, 13.0ms inference, 3.0ms postprocess per image at shape (1, 3, 288, 512)
Results saved to runs\detect\exp85
35.98642349243164 ms
1: 257.90 97.21 377.45 218.20
0: 4.22 100.11 125.73 221.62

image 1/1 D:\yolov8_py\ultralytics-main\ultralytics-main\0.png: 288x512 1 0, 1 1, 13.1ms
Speed: 1.0ms preprocess, 13.1ms inference, 2.9ms postprocess per image at shape (1, 3, 288, 512)
Results saved to runs\detect\exp86
34.99007225036621 ms
1: 257.90 97.21 377.45 218.20
0: 4.22 100.11 125.73 221.62

image 1/1 D:\yolov8_py\ultralytics-main\ultralytics-main\0.png: 288x512 1 0, 1 1, 14.0ms
Speed: 1.0ms preprocess, 14.0ms inference, 2.0ms postprocess per image at shape (1, 3, 288, 512)
Results saved to runs\detect\exp87
36.98873519897461 ms
1: 257.90 97.21 377.45 218.20
0: 4.22 100.11 125.73 221.62

```

When I use model.to("cuda") the code and cmd print as follows:

code:
```python 
   .........


    model = YOLO(
        r'C:\Users\Administrator\PycharmProjects\pythonProject\runs\detect\train10\weights\best.pt').to("cuda")


   .........



```

cmd :
```cmd 

image 1/1 D:\yolov8_py\ultralytics-main\ultralytics-main\0.png: 288x512 1 0, 1 1, 187.9ms
Speed: 1.9ms preprocess, 187.9ms inference, 496.8ms postprocess per image at shape (1, 3, 288, 512)
Results saved to runs\detect\exp94
3021.0299491882324 ms
1: 257.90 97.21 377.45 218.20
0: 4.22 100.11 125.73 221.62

image 1/1 D:\yolov8_py\ultralytics-main\ultralytics-main\0.png: 288x512 1 0, 1 1, 13.0ms
Speed: 2.0ms preprocess, 13.0ms inference, 3.0ms postprocess per image at shape (1, 3, 288, 512)
Results saved to runs\detect\exp95
36.986351013183594 ms
1: 257.90 97.21 377.45 218.20
0: 4.22 100.11 125.73 221.62

image 1/1 D:\yolov8_py\ultralytics-main\ultralytics-main\0.png: 288x512 1 0, 1 1, 13.0ms
Speed: 1.0ms preprocess, 13.0ms inference, 2.1ms postprocess per image at shape (1, 3, 288, 512)
Results saved to runs\detect\exp96
34.99007225036621 ms
1: 257.90 97.21 377.45 218.20
0: 4.22 100.11 125.73 221.62


```

The first recognition time has been reduced from 8600ms to 3000ms, so I am very confused. I don't know what causes this problem

**Comment by glenn-jocher** [comment]
@qinsehm1128 hello,

Thank you for reaching out and providing a detailed description of your issue along with the code and command outputs. The initial delay you are experiencing is a common occurrence and can be attributed to several factors, especially when using GPUs.

### Explanation

1. **Model Loading and Initialization**: The first time you load a model and perform inference, there are several initialization steps that take place, such as loading the model weights into memory, initializing CUDA kernels, and setting up the computational graph. These steps can be time-consuming but are necessary for the model to function correctly.

2. **CUDA Context Initialization**: When you use `model.to("cuda")`, the CUDA context is initialized, which can take a significant amount of time. This is a one-time cost, and subsequent inferences are much faster because the context is already set up.

### Recommendations

1. **Warm-Up Inference**: To mitigate the initial delay, you can perform a "warm-up" inference right after loading the model. This will initialize all necessary components, and subsequent inferences will be faster. Here's how you can modify your code:

    ```python
    from ultralytics import YOLO
    import time

    if __name__ == '__main__':
        t = time.time()
        model = YOLO(r'C:\Users\Administrator\PycharmProjects\pythonProject\runs\detect\train4\weights\best.pt').to("cuda")
        print((time.time() - t) * 1000, "ms")

        # Warm-up inference
        model.predict(source="0.png")

        for i in range(10):
            t = time.time()
            metrics = model.predict(source="0.png",
                                    project='runs/detect',
                                    name='exp',
                                    save=True)
            print((time.time() - t) * 1000, "ms")
            for m in metrics:
                box = m.boxes
                for cls_idx, xyxy in zip(box.cls.tolist(), box.xyxy.tolist()):
                    class_name = model.names[int(cls_idx)]
                    x1, y1, x2, y2 = xyxy
                    print(f"{class_name}: {x1:.2f} {y1:.2f} {x2:.2f} {y2:.2f}")
    ```

2. **Ensure Latest Versions**: Make sure you are using the latest versions of `torch` and `ultralytics`. You can upgrade them using the following commands:
    ```bash
    pip install --upgrade torch ultralytics
    ```

### Additional Resources

For more detailed information on optimizing performance and handling similar issues, you can refer to our [FAQ section](https://docs.ultralytics.com/help/FAQ/).

I hope this helps! If you have any further questions or need additional assistance, feel free to ask. 😊

**Comment by qinsehm1128** [comment]
> 你好
> 
> 感谢您伸出援手，并详细描述您的问题以及代码和命令输出。您遇到的初始延迟很常见，可归因于多种因素，尤其是在使用 GPU 时。
> 
> ### 解释
> 1. **模型加载和初始化**：首次加载模型并执行推理时，会执行几个初始化步骤，例如将模型权重加载到内存中、初始化 CUDA 内核以及设置计算图。这些步骤可能很耗时，但对于模型正常运行是必要的。
> 2. **CUDA 上下文初始化**：使用 时，将初始化 CUDA 上下文，这可能需要大量时间。这是一次性成本，后续推理要快得多，因为上下文已经设置好了。`model.to("cuda")`
> 
> ### 建议
> 1. **预热推理**：为了减轻初始延迟，您可以在加载模型后立即执行“预热”推理。这将初始化所有必要的组件，后续推理将更快。下面介绍如何修改代码：
>    ```python
>    from ultralytics import YOLO
>    import time
>    
>    if __name__ == '__main__':
>        t = time.time()
>        model = YOLO(r'C:\Users\Administrator\PycharmProjects\pythonProject\runs\detect\train4\weights\best.pt').to("cuda")
>        print((time.time() - t) * 1000, "ms")
>    
>        # Warm-up inference
>        model.predict(source="0.png")
>    
>        for i in range(10):
>            t = time.time()
>            metrics = model.predict(source="0.png",
>                                    project='runs/detect',
>                                    name='exp',
>                                    save=True)
>            print((time.time() - t) * 1000, "ms")
>            for m in metrics:
>                box = m.boxes
>                for cls_idx, xyxy in zip(box.cls.tolist(), box.xyxy.tolist()):
>                    class_name = model.names[int(cls_idx)]
>                    x1, y1, x2, y2 = xyxy
>                    print(f"{class_name}: {x1:.2f} {y1:.2f} {x2:.2f} {y2:.2f}")
>    ```
> 2. **确保最新版本**：确保您使用的是最新版本的 和 。您可以使用以下命令升级它们：`torch``ultralytics`
>    ```shell
>    pip install --upgrade torch ultralytics
>    ```
> 
> ### 其他资源
> 有关优化性能和处理类似问题的更多详细信息，您可以参考我们的[常见问题解答部分](https://docs.ultralytics.com/help/FAQ/)。
> 
> 我希望这会有所帮助！如果您有任何其他问题或需要其他帮助，请随时提问。😊






Thanks for your advice! I prepared a picture of base64 to preheat what you said has solved the problem perfectly!

**Comment by glenn-jocher** [comment]
Hello @qinsehm1128,

Thank you for your kind words! 😊 I'm glad to hear that the warm-up inference suggestion helped resolve the initial delay issue.

Using a base64-encoded image for preheating is a clever approach and can indeed streamline the process. If you have any further questions or run into any other issues, feel free to reach out. The YOLO community and the Ultralytics team are always here to help!

Happy coding! 🚀
