### ISSUE TITLE
How to use Flask to build a YOLOv8 video predict platform?

### ISSUE THREAD

**Issue by MikeHawkIsGold** [ultralytics/ultralytics#1354]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am a tyro...
```
model = YOLO("model.pt") 
results = model.predict(source="videopath", save=True)
```
I read the docs and it said I can use codes like the above to make YOLOv8 work. 
So should I just push the result file to frond-end, or any other ways?
And I do not get that how to customize the result file's filename and save_dir ...

Any better solutions?

**Comment by glenn-jocher** [comment]
@MikeHawkIsGold you can use these 3 arguments to customize output directories, i.e. results will be saved to a
```
PROJECT/NAME
```
https://github.com/ultralytics/ultralytics/blob/790f9c067c9a3548acf7c6925cea14de9ad77787/ultralytics/yolo/cfg/default.yaml#L19-L21

**Comment by MikeHawkIsGold** [comment]
> Is there any solutions to change save_dir and file name by python?
I receive files which will be predicted from back-end to YOLOv8. The name of those files includes a timestamp, which means that the name of each file is unique. However, I found that the save_dir always be like
"predict/xxx.mp4"
"predict2/xxx.mp4"
"predictCount/xxx.mp4".
I can not get the folder_name by the timestamp, which makes me so confused. Because I need the result_path.
