### ISSUE TITLE
results object attributes and methods missing

### ISSUE THREAD

**Issue by lapllibary** [ultralytics/ultralytics#13546]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When running the following code:
model = YOLO("yolov8n.pt")  
results = model.predict("face1.jpeg")      
results[0].plot()

AttributeError:
            'Results' object has no attribute 'plot'. Valid 'Results' object attributes and properties are:

            Attributes:
                boxes (Boxes, optional): A Boxes object containing the detection bounding boxes.
                masks (Masks, optional): A Masks object containing the detection masks.
                probs (torch.Tensor, optional): A tensor containing the detection class probabilities.
                orig_shape (tuple, optional): Original image size.

According to documentation results object should have method plot.
I can draw the boxes myself but I'm confused about why this is happening.
This works on my other computer but not on this one. Both have the same version of ultralytics 8.2.31,
matplotlib>=3.2.2
numpy>=1.18.5
opencv-python>=4.6.0
Pillow>=7.1.2
PyYAML>=5.3.1
requests>=2.23.0
scipy>=1.4.1
torch>=1.7.0
torchvision>=0.8.1
tqdm>=4.64.0

**Comment by lapllibary** [comment]
Done all of the above before. Previous issues regarding this also didn't solve the problem.

**Comment by harshdhamecha** [comment]
I think you might have had a look at the old docs. I have referred [this code](https://docs.ultralytics.com/modes/predict/#plotting-results) and it works on my machine. You can try the following code:

```
from ultralytics import YOLO
from PIL import Image

model = YOLO('yolov8n.pt')
results = model('./assets/bus.jpg')

# Visualize the results
for i, r in enumerate(results):
    # Plot results image
    im_bgr = r.plot()  # BGR-order numpy array
    im_rgb = Image.fromarray(im_bgr[..., ::-1])  # RGB-order PIL image

    # Show results to screen (in supported environments)
    r.show()

    # Save results to disk
    r.save(filename=f"results{i}.jpg")
```

**Comment by glenn-jocher** [comment]
@harshdhamecha hi there,

Thank you for reaching out! It sounds like you're encountering an issue with the `plot` method on the `Results` object. Let's ensure we're on the same page and troubleshoot this together.

### Steps to Verify and Troubleshoot:

1. **Ensure Latest Versions**: First, please verify that you are using the latest versions of `torch` and `ultralytics`. You can upgrade them using the following commands:
    ```bash
    pip install --upgrade torch ultralytics
    ```

2. **Minimum Reproducible Example**: If the issue persists, please provide a minimum reproducible code example. This helps us understand the context and reproduce the issue on our end. You can refer to [this guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details on creating a reproducible example.

3. **Code Example**: Here's a code snippet that should work with the latest versions:
    ```python
    from ultralytics import YOLO
    from PIL import Image

    # Load the model
    model = YOLO('yolov8n.pt')

    # Run inference on an image
    results = model('face1.jpeg')

    # Visualize the results
    for i, r in enumerate(results):
        # Plot results image
        im_bgr = r.plot()  # BGR-order numpy array
        im_rgb = Image.fromarray(im_bgr[..., ::-1])  # RGB-order PIL image

        # Show results to screen (in supported environments)
        r.show()

        # Save results to disk
        r.save(filename=f"results{i}.jpg")
    ```

4. **Check Dependencies**: Ensure all required dependencies are installed and up-to-date. Here are the key dependencies:
    ```bash
    pip install matplotlib numpy opencv-python Pillow PyYAML requests scipy torch torchvision tqdm
    ```

5. **Environment Consistency**: Since the code works on one machine but not the other, ensure that both environments are consistent in terms of Python version and installed packages.

If you follow these steps and still encounter issues, please share the exact error message and any additional context. This will help us assist you more effectively.

Looking forward to your response, and thank you for your patience! 😊

**Comment by lapllibary** [comment]
![Screenshot 2024-06-14 090832](https://github.com/ultralytics/ultralytics/assets/65261936/eb51b64a-a876-48fd-bdf0-26d338c5a59a)
Ran the two updates, still the above error for both of the above code.
I installed python 3.10 via miniconda.

**Comment by glenn-jocher** [comment]
Hi @lapllibary,

Thank you for the update and for providing the screenshot. Let's get this sorted out!

### Next Steps:

1. **Minimum Reproducible Example**: To help us investigate further, could you please provide a minimum reproducible code example? This will allow us to replicate the issue on our end. You can refer to our [guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details on creating one.

2. **Environment Check**: Since you mentioned using Miniconda, let's ensure your environment is clean and consistent. You can create a new environment and install the necessary packages:
    ```bash
    conda create -n yolov8_env python=3.10
    conda activate yolov8_env
    pip install torch ultralytics matplotlib numpy opencv-python Pillow PyYAML requests scipy torchvision tqdm
    ```

3. **Verify Installation**: After setting up the new environment, try running the following code:
    ```python
    from ultralytics import YOLO
    from PIL import Image

    # Load the model
    model = YOLO('yolov8n.pt')

    # Run inference on an image
    results = model('face1.jpeg')

    # Visualize the results
    for i, r in enumerate(results):
        # Plot results image
        im_bgr = r.plot()  # BGR-order numpy array
        im_rgb = Image.fromarray(im_bgr[..., ::-1])  # RGB-order PIL image

        # Show results to screen (in supported environments)
        r.show()

        # Save results to disk
        r.save(filename=f"results{i}.jpg")
    ```

If the issue persists, please share the exact error message and any additional context. This will help us assist you more effectively.

Looking forward to your response, and thank you for your patience! 😊

**Comment by lapllibary** [comment]
Thank you for your timely reply. Doing the exact steps given(copying the exact program):
After creating new environment:
added / updated specs:
    - python=3.10


The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/win-64::bzip2-1.0.8-h2bbff1b_6
  ca-certificates    pkgs/main/win-64::ca-certificates-2024.3.11-haa95532_0
  libffi             pkgs/main/win-64::libffi-3.4.4-hd77b12b_1
  openssl            pkgs/main/win-64::openssl-3.0.13-h2bbff1b_2
  pip                pkgs/main/win-64::pip-24.0-py310haa95532_0
  python             pkgs/main/win-64::python-3.10.14-he1021f5_1
  setuptools         pkgs/main/win-64::setuptools-69.5.1-py310haa95532_0
  sqlite             pkgs/main/win-64::sqlite-3.45.3-h2bbff1b_0
  tk                 pkgs/main/win-64::tk-8.6.14-h0416ee5_0
  tzdata             pkgs/main/noarch::tzdata-2024a-h04d1e81_0
  vc                 pkgs/main/win-64::vc-14.2-h2eaa2aa_1
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.29.30133-h43f2093_3
  wheel              pkgs/main/win-64::wheel-0.43.0-py310haa95532_0
  xz                 pkgs/main/win-64::xz-5.4.6-h8cc25b3_1
  zlib               pkgs/main/win-64::zlib-1.2.13-h8cc25b3_1


Proceed ([y]/n)? y

I enterd y, activated yolo and installed the packages copying your code directly.
I get:
(... line 1, in <module>
    from ultralytics import YOLO)
ModuleNotFoundError: No module named 'IPython'

After pip install ipython:
(... line 1, in <module>
    from ultralytics import YOLO)
ModuleNotFoundError: No module named 'sentry_sdk'
After pip install sentry_sdk

line 8, in <module>
    results = model('face1.jpeg')
ModuleNotFoundError: No module named 'tensorboard'
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-Break to quit

After installing tensorboard:
![Screenshot 2024-06-14 172520](https://github.com/ultralytics/ultralytics/assets/65261936/637a7008-c342-4dbd-9d9c-0a1d45811a9d)

**Comment by harshdhamecha** [comment]
> Ran the two updates, still the same error for both of the above code. I installed python 3.10 via miniconda. ![Screenshot 2024-06-14 090832](https://private-user-images.githubusercontent.com/65261936/339597126-a25dd161-52c4-46a9-9422-85b4bc6a7ebf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTc3MjgsIm5iZiI6MTcxODM1NzQyOCwicGF0aCI6Ii82NTI2MTkzNi8zMzk1OTcxMjYtYTI1ZGQxNjEtNTJjNC00NmE5LTk0MjItODViNGJjNmE3ZWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5MzAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZTMxNzYyOWQ1ZTVkMDMzMDQ4N2FlYjEyNWY5NDY0MzVmYWVjYTg5ZGI2ODQ0MWVmNmY3MDA0ODk1OGY0ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C1G86Pf2kVZm1e-1OYwANuKBFrW_khr9RJj7fTKFTbA)

The very first line in the terminal shows Ultralytics version 8.0.17. That might be the issue. Try running it on the latest version. I ran it on v8.2.31

**Comment by glenn-jocher** [comment]
Hi @harshdhamecha,

Thank you for the detailed update and for providing the screenshot. It looks like the issue might be related to the version of the `ultralytics` package you're using. The terminal shows that you're on version 8.0.17, while the latest version is 8.2.31.

### Steps to Resolve:

1. **Upgrade Ultralytics Package**: Let's ensure you're using the latest version of the `ultralytics` package. You can upgrade it using the following command:
    ```bash
    pip install --upgrade ultralytics
    ```

2. **Verify Installation**: After upgrading, verify the installation by checking the version:
    ```bash
    python -c "import ultralytics; print(ultralytics.__version__)"
    ```

3. **Run the Code Again**: Once you've confirmed that you're on the latest version, try running the code again:
    ```python
    from ultralytics import YOLO
    from PIL import Image

    # Load the model
    model = YOLO('yolov8n.pt')

    # Run inference on an image
    results = model('face1.jpeg')

    # Visualize the results
    for i, r in enumerate(results):
        # Plot results image
        im_bgr = r.plot()  # BGR-order numpy array
        im_rgb = Image.fromarray(im_bgr[..., ::-1])  # RGB-order PIL image

        # Show results to screen (in supported environments)
        r.show()

        # Save results to disk
        r.save(filename=f"results{i}.jpg")
    ```

If you continue to face issues, please ensure that all dependencies are up-to-date and consistent across your environments. If the problem persists, providing a minimum reproducible example will help us investigate further. You can refer to our [guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details on creating one.

Thank you for your patience, and I hope this resolves the issue! 😊

**Comment by lapllibary** [comment]
> > Ran the two updates, still the same error for both of the above code. I installed python 3.10 via miniconda. ![Screenshot 2024-06-14 090832](https://private-user-images.githubusercontent.com/65261936/339597126-a25dd161-52c4-46a9-9422-85b4bc6a7ebf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTc3MjgsIm5iZiI6MTcxODM1NzQyOCwicGF0aCI6Ii82NTI2MTkzNi8zMzk1OTcxMjYtYTI1ZGQxNjEtNTJjNC00NmE5LTk0MjItODViNGJjNmE3ZWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5MzAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZTMxNzYyOWQ1ZTVkMDMzMDQ4N2FlYjEyNWY5NDY0MzVmYWVjYTg5ZGI2ODQ0MWVmNmY3MDA0ODk1OGY0ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C1G86Pf2kVZm1e-1OYwANuKBFrW_khr9RJj7fTKFTbA)
> 
> The very first line in the terminal shows Ultralytics version 8.0.17. That might be the issue. Try running it on the latest version. I ran it on v8.2.31

That's very strange, when I try ultralytics -version I get:
![Uploading image.png…]()

**Comment by glenn-jocher** [comment]
Hi @lapllibary,

Thank you for the update! It looks like the version discrepancy might be causing the issue. Let's ensure you're using the latest version of the `ultralytics` package.

### Steps to Resolve:

1. **Upgrade Ultralytics Package**: Please upgrade to the latest version of `ultralytics`:
    ```bash
    pip install --upgrade ultralytics
    ```

2. **Verify Installation**: After upgrading, verify the installation by checking the version:
    ```bash
    python -c "import ultralytics; print(ultralytics.__version__)"
    ```

3. **Run the Code Again**: Once you've confirmed that you're on the latest version, try running the code again:
    ```python
    from ultralytics import YOLO
    from PIL import Image

    # Load the model
    model = YOLO('yolov8n.pt')

    # Run inference on an image
    results = model('face1.jpeg')

    # Visualize the results
    for i, r in enumerate(results):
        # Plot results image
        im_bgr = r.plot()  # BGR-order numpy array
        im_rgb = Image.fromarray(im_bgr[..., ::-1])  # RGB-order PIL image

        # Show results to screen (in supported environments)
        r.show()

        # Save results to disk
        r.save(filename=f"results{i}.jpg")
    ```

If the issue persists, please ensure all dependencies are up-to-date and consistent across your environments. If the problem continues, providing a minimum reproducible example will help us investigate further. You can refer to our [guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details on creating one.

Thank you for your patience, and I hope this resolves the issue! 😊

**Comment by lapllibary** [comment]
After updating still:
![image](https://github.com/ultralytics/ultralytics/assets/65261936/202e2442-911b-4d39-9e29-187408a8193f)
I guess the latest ultralytics isn't compatible with python 3.10

**Comment by glenn-jocher** [comment]
Hi @lapllibary,

Thank you for the update and for providing the screenshot. Let's get this sorted out!

### Steps to Resolve:

1. **Verify Minimum Reproducible Example**: Could you please provide a minimum reproducible code example? This helps us replicate the issue on our end. You can refer to our [guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

2. **Ensure Latest Versions**: Please ensure you're using the latest versions of both `torch` and `ultralytics`. You can upgrade them using the following commands:
    ```bash
    pip install --upgrade torch ultralytics
    ```

3. **Check Python Compatibility**: The latest version of `ultralytics` should be compatible with Python 3.10. Let's verify the installation:
    ```bash
    python -c "import ultralytics; print(ultralytics.__version__)"
    ```

4. **Run the Code Again**: Once you've confirmed that you're on the latest version, try running the code again:
    ```python
    from ultralytics import YOLO
    from PIL import Image

    # Load the model
    model = YOLO('yolov8n.pt')

    # Run inference on an image
    results = model('face1.jpeg')

    # Visualize the results
    for i, r in enumerate(results):
        # Plot results image
        im_bgr = r.plot()  # BGR-order numpy array
        im_rgb = Image.fromarray(im_bgr[..., ::-1])  # RGB-order PIL image

        # Show results to screen (in supported environments)
        r.show()

        # Save results to disk
        r.save(filename=f"results{i}.jpg")
    ```

If the issue persists, please share the exact error message and any additional context. This will help us assist you more effectively.

Thank you for your patience, and I hope this resolves the issue! 😊

**Comment by lapllibary** [comment]
Sorry for the late reply :
After running pip install --upgrade torch ultralytics
and python -c "import ultralytics; print(ultralytics.__version__)"
![image](https://github.com/ultralytics/ultralytics/assets/65261936/44340df4-9633-42f3-966b-86d6019c4f4e)
Same environment (yolo) as created above. I don't get why the version isn't correct.

**Comment by glenn-jocher** [comment]
Hi @lapllibary,

Thank you for your patience and for providing the details. Let's get this resolved!

### Steps to Resolve:

1. **Verify Environment**: Ensure you're in the correct environment where `ultralytics` and `torch` were upgraded. You can activate the environment using:
    ```bash
    conda activate yolov8_env
    ```

2. **Check Installed Packages**: Verify the installed versions of `ultralytics` and `torch`:
    ```bash
    pip show ultralytics torch
    ```

3. **Reinstall Ultralytics**: If the version is still incorrect, try reinstalling `ultralytics`:
    ```bash
    pip uninstall ultralytics
    pip install ultralytics
    ```

4. **Run the Code Again**: Once confirmed, run the code again:
    ```python
    from ultralytics import YOLO
    from PIL import Image

    # Load the model
    model = YOLO('yolov8n.pt')

    # Run inference on an image
    results = model('face1.jpeg')

    # Visualize the results
    for i, r in enumerate(results):
        # Plot results image
        im_bgr = r.plot()  # BGR-order numpy array
        im_rgb = Image.fromarray(im_bgr[..., ::-1])  # RGB-order PIL image

        # Show results to screen (in supported environments)
        r.show()

        # Save results to disk
        r.save(filename=f"results{i}.jpg")
    ```

If the issue persists, please provide a minimum reproducible code example to help us investigate further. You can refer to our [guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

Thank you for your cooperation, and I hope this helps! 😊

**Comment by lapllibary** [comment]
The following two ways of getting ultralytics version show different results:
![image](https://github.com/ultralytics/ultralytics/assets/65261936/12f1812e-1cec-4f23-9b63-404beabf1a57)

![image](https://github.com/ultralytics/ultralytics/assets/65261936/8591415a-27d2-47f4-8c7c-46c7ff748e28)

**Comment by glenn-jocher** [comment]
Hi @lapllibary,

Thank you for bringing this to our attention. It looks like there might be a discrepancy between the versions shown by different methods. Let's address this step-by-step:

1. **Environment Verification**: Ensure that you are in the correct environment where `ultralytics` was installed. You can activate your environment using:
    ```bash
    conda activate yolov8_env
    ```

2. **Check Installed Packages**: Verify the installed versions of `ultralytics` and `torch`:
    ```bash
    pip show ultralytics torch
    ```

3. **Reinstall Ultralytics**: If the version is still incorrect, try reinstalling `ultralytics`:
    ```bash
    pip uninstall ultralytics
    pip install ultralytics
    ```

4. **Run the Code Again**: Once confirmed, run the code again to ensure everything is working as expected.

If the issue persists, please provide a minimum reproducible code example to help us investigate further. You can refer to our [guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

Thank you for your cooperation, and I hope this helps! 😊

**Comment by lapllibary** [comment]
After reinstalling:
![image](https://github.com/ultralytics/ultralytics/assets/65261936/38baeee6-c160-4853-bbb8-a64ed10f3f7a)

![image](https://github.com/ultralytics/ultralytics/assets/65261936/f49b4d71-27b3-4dd4-99e1-479c81038bfc)
Same error running the code (no surprise there)

**Comment by glenn-jocher** [comment]
Hi @lapllibary,

Thank you for the detailed update and for your patience. It seems like there might still be an issue with the environment setup.

### Steps to Resolve:

1. **Verify Environment**: Ensure you're in the correct environment where `ultralytics` was installed:
    ```bash
    conda activate yolov8_env
    ```

2. **Check Installed Packages**: Verify the installed versions of `ultralytics` and `torch`:
    ```bash
    pip show ultralytics torch
    ```

3. **Reinstall Ultralytics**: If the version is still incorrect, try reinstalling `ultralytics`:
    ```bash
    pip uninstall ultralytics
    pip install ultralytics
    ```

4. **Run the Code Again**: Once confirmed, run the code again to ensure everything is working as expected.

If the issue persists, please provide a minimum reproducible code example to help us investigate further. You can refer to our [guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

Thank you for your cooperation, and I hope this helps! 😊

**Comment by lapllibary** [comment]
Thank you for all your time and patience.
The suggestions are the exact same as the last one which I tried. I have an environment/version issue but reinstalling/creating new environment didn't help it.

**Comment by glenn-jocher** [comment]
Hi @lapllibary,

Thank you for your patience and for providing detailed updates. It seems like we're dealing with a persistent environment/version issue. Let's try a few more steps to resolve this:

1. **Verify Environment Activation**: Ensure that the correct environment is activated before running your commands:
    ```bash
    conda activate yolov8_env
    ```

2. **Check Installed Packages**: Verify the installed versions of `ultralytics` and `torch`:
    ```bash
    pip show ultralytics torch
    ```

3. **Create a Fresh Environment**: Sometimes, starting from scratch can help. Let's create a new environment and install the necessary packages:
    ```bash
    conda create -n new_yolo_env python=3.10
    conda activate new_yolo_env
    pip install ultralytics torch
    ```

4. **Run the Code**: Once the new environment is set up, try running your code again:
    ```python
    from ultralytics import YOLO
    from PIL import Image

    # Load the model
    model = YOLO('yolov8n.pt')

    # Run inference on an image
    results = model('face1.jpeg')

    # Visualize the results
    for i, r in enumerate(results):
        # Plot results image
        im_bgr = r.plot()  # BGR-order numpy array
        im_rgb = Image.fromarray(im_bgr[..., ::-1])  # RGB-order PIL image

        # Show results to screen (in supported environments)
        r.show()

        # Save results to disk
        r.save(filename=f"results{i}.jpg")
    ```

If the issue persists, could you please provide a minimum reproducible code example? This will help us investigate further. You can refer to our [guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

Thank you for your cooperation, and I hope this helps! 😊

**Comment by lapllibary** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/65261936/0b339ad8-694a-431d-ac06-2f64496a162b)
![image](https://github.com/ultralytics/ultralytics/assets/65261936/3d6c3e4b-b5a9-40ab-907d-3b0472b7f657)

**Comment by lapllibary** [comment]
Complete stupidity on my part, I had a local ultralytics 8.10.17 version in the folder. Thanks for all your help

**Comment by glenn-jocher** [comment]
Hi @lapllibary,

No worries at all—these things happen! 😊 I'm glad we could help you identify the issue. It's great to hear that you've pinpointed the local version conflict.

If you encounter any more issues or have further questions, feel free to reach out. We're here to help!

Happy coding! 🚀
