### ISSUE TITLE
YOLOv8-ONNXRuntime doesn't applied to yolo-obb

### ISSUE THREAD

**Issue by fuhao96** [ultralytics/ultralytics#13551]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

[ultralytics](https://github.com/ultralytics/ultralytics/tree/f92bd9dea119715ced09d0b6ca6241cdadb8397b)/[examples](https://github.com/ultralytics/ultralytics/tree/f92bd9dea119715ced09d0b6ca6241cdadb8397b/examples)/[YOLOv8-ONNXRuntime](https://github.com/ultralytics/ultralytics/tree/f92bd9dea119715ced09d0b6ca6241cdadb8397b/examples/YOLOv8-ONNXRuntime)
/main.py

This seem doesn't apply to obb onnx model. When I run a obb onnx on it, it just provide lots useless boxes and can't draw a rotation box.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@fuhao96 hello,

Thank you for bringing this to our attention! Let's work together to resolve this issue.

Firstly, could you please provide a minimal reproducible code example? This will help us understand the exact scenario and reproduce the bug on our end. You can refer to our guide on creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example). This step is crucial for us to investigate and address the issue effectively.

Additionally, please ensure that you are using the latest versions of `torch` and `ultralytics`. You can update your packages using the following commands:

```bash
pip install --upgrade torch ultralytics
```

Once you've updated, try running your code again to see if the issue persists.

Regarding the specific problem with the YOLOv8-ONNXRuntime example not working with OBB models, it’s possible that the current implementation does not fully support the oriented bounding box (OBB) format. The OBB models, such as `yolov8n-obb.pt`, are designed to handle rotated bounding boxes and may require additional handling in the ONNXRuntime script to properly interpret and draw these boxes.

Here’s a quick example of how you might modify the prediction script to handle OBB models:

```python
from ultralytics import YOLO

# Load the OBB model
model = YOLO("yolov8n-obb.onnx")

# Run predictions
results = model.predict("path/to/your/image.jpg")

# Process and visualize the results
for result in results:
    obb_boxes = result.obb  # Access the oriented bounding boxes
    result.plot()  # This should now correctly plot the rotated boxes
```

If you continue to experience issues, please share the specific error messages or unexpected behaviors you encounter. This additional information will be very helpful.

Looking forward to your response with the reproducible example and any further details you can provide.

**Comment by APeFerreira** [comment]
@fuhao96 did you manage to build a ONNXRUNTIME script for OBB?
