### ISSUE TITLE
resume training always download dataset coco!

### ISSUE THREAD

**Issue by tms2003** [ultralytics/ultralytics#1355]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

this is my resume training cli:
yolo detect train data=data/drone.yaml model=yolov8l.pt epochs=
400 imgsz=640  batch=16  cache=true resume=true

I want reume training ,but i got this:
Dataset 'coco.yaml' images not found _, missing paths ['/tangcan/source/ultralytics/datasets/coco/val2017.txt']
Downloading https://github.com/ultralytics/yolov5/releases/download/v1.0/coco2017labels-segments.zip to /tangcan/source/
ultralytics/datasets/coco2017labels-segments.zip...
_ Download failure, retrying 1/3 https://github.com/ultralytics/yolov5/releases/download/v1.0/coco2017labels-segments.zi
p...
#############  

this will be slow...

so ,I think it's a bug .

### Environment

YOLO:8.0.51
pytorch:'1.12.1+cu113'
ubuntu 20.04

### Minimal Reproducible Example

yolo detect train data=data/drone.yaml model=yolov8l.pt epochs=
400 imgsz=640  batch=16  cache=true resume=true

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@tms2003 hi, you should use your interrupted `last.pt` file instead of `yolov8l.pt` if you're going to use resume. :)

**Comment by tms2003** [comment]
@Laughing-q In yolov5, the nearest train can be found automatically, and then resume. I hope yolov8 is the same. The documentation also seems to mean this (there is also a resume in the code), but it has not been done. Thank u, I've resumed with specified weights.

**Comment by Xiuyee-d** [comment]
Hi, I still have some uncertainty. I also encountered this problem when I tried to set `resume=True` during the first training, it always downloads the coco dataset. Does this mean that ‘resume’ does not need to be turned on during the first training, and can be continued directly through `data=last.pt resume=true` when needed?

**Comment by Xiuyee-d** [comment]
> Hi, I still have some uncertainty. I also encountered this problem when I tried to set `resume=True` during the first training, it always downloads the coco dataset. Does this mean that ‘resume’ does not need to be turned on during the first training, and can be continued directly through `data=last.pt resume=true` when needed?

However, I tried `data=last.pt resume=true` and the result is still downloading the coco, I don't know where the error is.

**Comment by Xiuyee-d** [comment]
@glenn-jocher, Thank you for your reply, it clarified my doubts! In addition, I made a mistake, I should set `model=last.pt` instead of `data=last.pt`

**Comment by glenn-jocher** [comment]
You're welcome, @Xiuyee-d! It's great to hear that I could clear up your doubts regarding the use of the `resume=True` option. And you're correct, the correct argument to use to load a model checkpoint is `model=last.pt`. It's important to make sure that the correct model checkpoint file of the same architecture being trained is being used by the `resume=True` option. If you have any further questions or issues, feel free to ask!
