### ISSUE TITLE
yolov8n is the latest when using pip install ultralytics? what about v9 and v10??

### ISSUE THREAD

**Issue by AntDX316** [ultralytics/ultralytics#13558]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

yolov8n is the latest when using pip install ultralytics? what about v9 and v10??

### Environment

windows 10 x64 latest

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AntDX316 hello,

Thank you for reaching out! To answer your question, when you use `pip install ultralytics`, it installs the latest stable release of the Ultralytics package, which currently includes YOLOv8 as the latest official version. 

YOLOv9 and YOLOv10 are experimental models and are not included in the standard `pip` installation. If you are interested in experimenting with these versions, you can clone the repository directly from GitHub and switch to the respective branches or tags that contain these models.

Here’s a quick guide on how to do that:

1. **Clone the Repository:**
   ```bash
   git clone https://github.com/ultralytics/ultralytics.git
   cd ultralytics
   ```

2. **Checkout the Desired Version:**
   For YOLOv9:
   ```bash
   git checkout yolov9
   ```
   For YOLOv10:
   ```bash
   git checkout yolov10
   ```

3. **Install the Dependencies:**
   ```bash
   pip install -r requirements.txt
   ```

This will give you access to the experimental versions of YOLOv9 and YOLOv10.

If you encounter any issues or bugs while using these versions, please ensure you provide a minimum reproducible example as outlined in our [documentation](https://docs.ultralytics.com/help/minimum_reproducible_example). This helps us investigate and resolve the issue more efficiently.

Additionally, please make sure you are using the latest versions of `torch` and `ultralytics` by running:
```bash
pip install --upgrade torch ultralytics
```

Feel free to reach out if you have any more questions or need further assistance. We're here to help! 😊
