### ISSUE TITLE
NotImplementedError: WARNING ⚠️ 'YOLO' model does not support '_new' mode for 'None' task yet.  when use yolov10

### ISSUE THREAD

**Issue by tms2003** [ultralytics/ultralytics#13569]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Error in training yolov10 according to the documentation:
I trained yolov10 according to the official documentation https://docs.ultralytics.com/models/yolov10/#accuracy-enhancements
Using the latest yolov8 master branch.
pip install -e .
After that, I used the following code for training:
```
from ultralytics import YOLO

# Load YOLOv10n model from scratch
model = YOLO("yolov10n.yaml")


model.info()
# Train the model
results = model.train(data="data/coco11.yaml")
```
The result is an error:
```
Traceback (most recent call last):
  File "/tangcan/source/ultralytics/ultralytics/engine/model.py", line 829, in _smart_load
    return self.task_map[self.task][key]
KeyError: None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tangcan/source/ultralytics/v10train.py", line 4, in <module>
    model = YOLO("yolov10n.yaml")
  File "/tangcan/source/ultralytics/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/tangcan/source/ultralytics/ultralytics/engine/model.py", line 150, in __init__
    self._new(model, task=task, verbose=verbose)
  File "/tangcan/source/ultralytics/ultralytics/engine/model.py", line 219, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "/tangcan/source/ultralytics/ultralytics/engine/model.py", line 833, in _smart_load
    raise NotImplementedError(
NotImplementedError: WARNING ⚠️ 'YOLO' model does not support '_new' mode for 'None' task yet.
```
Did I miss anything?My version is:ultralytics             8.2.31

**Comment by glenn-jocher** [comment]
Hi @tms2003,

Thank you for reaching out and providing detailed information about the issue you're encountering. It looks like you're trying to train a YOLOv10 model but are running into a `NotImplementedError`.

To help us investigate this further, could you please provide a minimum reproducible code example? This will allow us to replicate the issue on our end. You can find guidelines on creating a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of both `torch` and `ultralytics`. You can update your packages using the following commands:

```bash
pip install --upgrade torch ultralytics
```

Once you've updated the packages, please try running your code again to see if the issue persists.

If the problem continues, please share the exact versions of `torch` and `ultralytics` you are using, along with the complete stack trace. This information will be invaluable in diagnosing the issue.

Thank you for your cooperation, and we look forward to resolving this for you!

**Comment by tms2003** [comment]
> Hi @tms2003,
> 
> Thank you for reaching out and providing detailed information about the issue you're encountering. It looks like you're trying to train a YOLOv10 model but are running into a `NotImplementedError`.
> 
> To help us investigate this further, could you please provide a minimum reproducible code example? This will allow us to replicate the issue on our end. You can find guidelines on creating a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> Additionally, please ensure that you are using the latest versions of both `torch` and `ultralytics`. You can update your packages using the following commands:
> 
> ```shell
> pip install --upgrade torch ultralytics
> ```
> 
> Once you've updated the packages, please try running your code again to see if the issue persists.
> 
> If the problem continues, please share the exact versions of `torch` and `ultralytics` you are using, along with the complete stack trace. This information will be invaluable in diagnosing the issue.
> 
> Thank you for your cooperation, and we look forward to resolving this for you!

Thank you, I found the problem. I should use the v10 branch and I can train.

**Comment by glenn-jocher** [comment]
Hi @tms2003,

Thank you for the update! I'm glad to hear that you've identified the issue and are now able to train using the v10 branch. 🎉

If you encounter any further questions or run into other issues, please don't hesitate to reach out. The YOLO community and the Ultralytics team are always here to help.

Happy training! 🚀

**Comment by Jss666** [comment]
> > > 你好@tms2003，
> > > 感谢您联系我们并提供有关您遇到的问题的详细信息。您似乎正在尝试训练 YOLOv10 模型，但遇到了`NotImplementedError`。
> > > 为了帮助我们进一步调查此问题，您能否提供一个最小可重现的代码示例？这将使我们能够在我们这边复制该问题。您可以在此处找到有关创建最小可重现示例的指南：[最小可重现示例](https://docs.ultralytics.com/help/minimum_reproducible_example)。此外，请确保您使用的是和
> > > 的最新版本。您可以使用以下命令更新您的软件包：`torch``ultralytics`
> > > ```shell
> > > pip install --upgrade torch ultralytics
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 更新软件包后，请尝试再次运行代码，看看问题是否仍然存在。
> > > 如果问题仍然存在，请分享您使用的确切版本`torch`以及`ultralytics`完整的堆栈跟踪。这些信息对于诊断问题非常有用。
> > > 感谢您的合作，我们期待为您解决这个问题！
> > 
> > 
> > 谢谢，我找到了问题所在。我应该使用 v10 分支，这样我就可以进行训练了。
> 
> 你是如何解决这个问题的？我在 YOLOv8 中更换检测头时遇到了类似的问题。 ![图像](https://private-user-images.githubusercontent.com/55795398/341012580-48450f01-f83f-4f16-8f74-610f7bfe9fae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNzU0NTEsIm5iZiI6MTcyMTE3NTE1MSwicGF0aCI6Ii81NTc5NTM5OC8zNDEwMTI1ODAtNDg0NTBmMDEtZjgzZi00ZjE2LThmNzQtNjEwZjdiZmU5ZmFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDAwMTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMzgxOTk3NThkZDRiZTY2YTUyYTI4OWE4ZTU4YWIyZWU5YTVjMmQ2OTc1OTQwZGNkMDEzYzFiMDFiOWY0NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pC2wzTcMZtmM2r1EJxZ53yeBjHnlR4l_irU47AWL_ww)

您好，请问是如何解决的？

**Comment by pderrenger** [comment]
你好！你可以尝试使用最新的 `torch` 和 `ultralytics` 版本来解决这个问题。确保你已经切换到 v10 分支并按照文档中的步骤进行操作。如果问题仍然存在，请提供更多详细信息，我们会尽力帮助你解决。

**Comment by Michael-24** [comment]
我是用v8 来训练的 torch 版本为 2.1.0 ultralytics 版本为 8.3.20. (这是用了pip install --upgrade torch ultralytics 之后的版本了)。但依旧报错
![Snipaste_2024-10-23_09-29-04](https://github.com/user-attachments/assets/fcd8cbb5-25a4-4fd3-a596-c2c84478a922)

**Comment by Y-T-G** [comment]
@Michael-24 You have an `ultralytics` folder inside the folder you're running from. You have to delete that.

**Comment by Michael-24** [comment]
My entire project directory structure is like this.
![Snipaste_2024-10-24_11-04-30](https://github.com/user-attachments/assets/c3f06bdf-55ff-4cf3-a697-d41b59b8f1d0)
![Snipaste_2024-10-24_11-05-22](https://github.com/user-attachments/assets/d0b8af7f-8358-4d27-8a7f-de7e7c025932)

**Comment by Y-T-G** [comment]
Delete the folder or pull the latest changes from git

**Comment by Michael-24** [comment]
thx, I solved the problem.

**Comment by glenn-jocher** [comment]
@Michael-24 great to hear you resolved it! If you have any more questions, feel free to ask.

**Comment by woshidamow5534** [comment]
I also encountered the same problem. How can I solve it?
![Image](https://github.com/user-attachments/assets/936bc18f-18ae-4fb9-a41a-1a75aab2575b)

**Comment by woshidamow5534** [comment]
I also encountered the same problem. How can I solve it?
![Image](https://github.com/user-attachments/assets/33e1996c-7a32-479c-b62b-ef9b982e9987)

**Comment by Y-T-G** [comment]
That's not Ultralytics code. That's the code from YOLOv10 fork.

**Comment by woshidamow5534** [comment]
Successfully installed ultralytics-8.1.34

I am using ultralytics code. There is a problem when modifying the detection header of yolov10

**Comment by woshidamow5534** [comment]
Do you have any good suggestions?

**Comment by Y-T-G** [comment]
> Successfully installed ultralytics-8.1.34
> 
> I am using ultralytics code. There is a problem when modifying the detection header of yolov10

This is not official Ultralytics. Install official latest Ultralytics.

**Comment by woshidamow5534** [comment]
I tried to use the official code, but 。。。

**Comment by woshidamow5534** [comment]
![Image](https://github.com/user-attachments/assets/e72f91fe-db2c-4bc6-a87d-cf0475557867)

**Comment by Y-T-G** [comment]
If it's a custom yaml, you need to use `task="detect"` inside `YOLO()` function
