### ISSUE TITLE
Could I use yolov8-pose as Detector + Pose Estimator?

### ISSUE THREAD

**Issue by ynkim0** [ultralytics/ultralytics#13579]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, Thank You for Great Work!

I want to use yolov8-pose as Detector, and at the same time, pose estimator. What I'm curious about is whether it is possible to obtain detection results for objects other than id 0(person). like... car or something in COCO dataset. When I print the result, it only returns cls 0 boxes. But I need other ones, too. Because resources are limited, I can use only one yolo model. How can I get some other objects?

**Comment by glenn-jocher** [comment]
@ynkim0 hello,

Thank you for your kind words and for reaching out with your question! 😊

Currently, YOLOv8-pose models are specifically designed for human pose estimation and are trained to detect and estimate poses for class 0 (person) only. This means that the model will not provide detection results for other object classes like cars or other categories from the COCO dataset.

If you need to detect multiple object classes (e.g., cars, animals) along with human poses, you would typically need to use two separate models: one for general object detection (e.g., YOLOv8) and another for pose estimation (e.g., YOLOv8-pose). However, as you mentioned that resources are limited and you can only use one model, here are a couple of suggestions:

1. **Custom Training**: You can train a custom YOLO model that includes both object detection and pose estimation. This would involve creating a custom dataset that includes annotations for both bounding boxes and keypoints for the objects of interest. This approach requires significant effort in dataset preparation and training but would allow you to have a single model that performs both tasks.

2. **Sequential Inference**: Run the object detection model first to detect all objects, and then selectively run the pose estimation model on the detected persons. This approach uses two models sequentially but can be optimized to minimize resource usage.

Here's a brief example of how you might implement sequential inference in Python:

```python
from ultralytics import YOLO

# Load the object detection model
det_model = YOLO("yolov8n.pt")  # General object detection model

# Load the pose estimation model
pose_model = YOLO("yolov8n-pose.pt")  # Pose estimation model

# Run object detection
det_results = det_model("image.jpg")

# Filter detections for persons (class 0)
person_detections = [det for det in det_results if det.cls == 0]

# Run pose estimation on detected persons
for person in person_detections:
    x1, y1, x2, y2 = person.xyxy
    person_image = original_image[y1:y2, x1:x2]  # Crop the person from the image
    pose_results = pose_model(person_image)
    # Process pose_results as needed
```

For more detailed guidance on creating custom datasets and training models, you can refer to our [documentation on pose estimation datasets](https://docs.ultralytics.com/datasets/pose/).

I hope this helps! If you have any further questions or need additional assistance, feel free to ask.

**Comment by han-minhee** [comment]
> 1. **Custom Training**: You can train a custom YOLO model that includes both object detection and pose estimation. This would involve creating a custom dataset that includes annotations for both bounding boxes and keypoints for the objects of interest. This approach requires significant effort in dataset preparation and training but would allow you to have a single model that performs both tasks.

Could you elaborate on this? Should I modify the internal code, or is it doable by a suitable training script?

**Comment by glenn-jocher** [comment]
Hello @han-minhee,

Great question! You can indeed achieve this by preparing a custom dataset and using a suitable training script without modifying the internal code of YOLOv8.

### Steps to Train a Custom Model for Both Object Detection and Pose Estimation:

1. **Prepare Your Dataset**:
   - **Annotations**: Ensure your dataset annotations include both bounding boxes and keypoints. The format should follow the Ultralytics YOLO format for pose estimation.
   - **YAML Configuration**: Create a YAML file to define your dataset paths and keypoint details. Here’s an example:

     ```yaml
     path: ../datasets/custom-pose  # dataset root dir
     train: images/train  # train images (relative to 'path')
     val: images/val  # val images (relative to 'path')
     test:  # test images (optional)

     # Keypoints
     kpt_shape: [17, 3]  # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)
     flip_idx: [0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15]

     # Classes dictionary
     names:
       0: person
       1: car
       2: bicycle
       # Add other classes as needed
     ```

2. **Training Script**:
   - Use the Ultralytics YOLO training script to train your model. Here’s a Python example:

     ```python
     from ultralytics import YOLO

     # Load a model
     model = YOLO("yolov8n-pose.pt")  # Start with a pretrained pose model

     # Train the model
     results = model.train(data="custom-pose.yaml", epochs=100, imgsz=640)
     ```

   - Or via CLI:

     ```bash
     yolo detect train data=custom-pose.yaml model=yolov8n-pose.pt epochs=100 imgsz=640
     ```

### Additional Tips:
- **Dataset Preparation**: Ensure your dataset is well-annotated with both bounding boxes and keypoints for all classes.
- **Hyperparameter Tuning**: You may need to adjust hyperparameters to balance the training for both detection and pose estimation tasks.

By following these steps, you can train a single YOLO model to perform both object detection and pose estimation. If you encounter any issues or need further assistance, feel free to ask!

Best of luck with your training! 🚀

**Comment by Nasaravira20** [comment]
@han-minhee  Have you tried to create the model, If it was a success can you explain the steps you did followed and if you had experienced any issues while creating such a model, I'm curious to know, what are those

**Comment by han-minhee** [comment]
@Nasaravira20 Sorry for the late reply. It has been a while, so I'm not sure how I managed to do that, or whether I actually made it or not 🤔

For the detection of additional object, I probably made the dataset like the usual pose estimation dataset,
but set the kpt shape to 0 or to some dummy values like (0, 0).
