### ISSUE TITLE
add save_id option for track

### ISSUE THREAD

**Issue by ZeroAct** [ultralytics/ultralytics#1357]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I cannot find the option for saving track id in text file.
I'd like to contribute about this feature.

Let me know if i miss something.
Thank you!

### Use case
```
yolo track source=... save_txt=True
# cls *bbox
yolo track source=... save_txt=True save_id=True
# cls *bbox track_id
yolo track source=... save_txt=True save_id=True save_conf=True
# cls *bbox conf track_id
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ZeroAct I think the best way to save tracks would be in Python rather than using the CLI, i.e. 

```python
from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.pt")  # load an official detection model

# Track with the model
results = model.track(source="https://youtu.be/Zgi9g1ksQHc", show=True) 
```

See https://docs.ultralytics.com/modes/track for full tracking documentation.

**Comment by ZeroAct** [comment]
@glenn-jocher 
Thank you for your response, and I always appreciate your great work 😊

I believe there are use cases for saving track IDs with CLI.
Despite its importance and usefulness, this feature is not currently provided.
Sure, I can implement this feature in Python, but, wouldn't it be better to provide an interface for saving track IDs?

Thank you again!

**Comment by glenn-jocher** [comment]
@ZeroAct yes, if the changes to the predict function minimal then it might be a good idea. I see you have a PR open, are the changes implemented in both Segmentation and Detection predict.py files?

**Comment by ZeroAct** [comment]
@glenn-jocher I missed the Segmentation predict.py file.
I'll add it, too.

**Comment by ZeroAct** [comment]
8f6541d done in here.

I tested it in both CLIs and Python code.
``` shell
yolo track model=yolov8n.pt source=https://ultralytics.com/assets/decelera_portrait_min.mov save_txt=True save_conf=True save_id=True
yolo track model=yolov8n-seg.pt source=https://ultralytics.com/assets/decelera_portrait_min.mov save_txt=True save_conf=True save_id=True
```
``` python
from ultralytics import YOLO

model = YOLO("yolov8n.pt")
model.track(
    source="https://ultralytics.com/assets/decelera_portrait_min.mov",
    save_txt=True,
    save_conf=True,
    save_id=True
)

model = YOLO("yolov8n-seg.pt")
model.track(
    source="https://ultralytics.com/assets/decelera_portrait_min.mov",
    save_txt=True,
    save_conf=True,
    save_id=True
)
```
