### ISSUE TITLE
how to add my posprocess to val

### ISSUE THREAD

**Issue by Linengyao** [ultralytics/ultralytics#13571]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I want to add my own post-processing part to YOLOv8's inference and prediction (that is, after the model is output through non-maximum suppression to obtain the final bbox and conf vectors, and then further process the bbox and conf vectors to obtain my own bbox and conf vectors), which files should I modify? I know that the general verification and prediction process is as follows:
1. Input the image to the model to get the output (bbox and confidence)
2. Use the obtained bbox and confidence to calculate some indicators, such as mAP, etc.
What I want to do is to insert a post-processing step between 1 and 2 to process the bbox and confidence.How can I add my code？

### Environment

none

### Minimal Reproducible Example

none

### Additional

none

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @Linengyao,

Thank you for your question! To add your custom post-processing step to YOLOv8's validation process, you can modify the `postprocess` method in the `DetectionPredictor` class. This method is responsible for handling the model's output after non-maximum suppression (NMS) and before calculating metrics like mAP.

Here's a step-by-step guide to help you integrate your custom post-processing:

1. **Locate the `DetectionPredictor` Class:**
   The `DetectionPredictor` class is defined in `ultralytics/models/yolo/detect/predict.py`. You can extend this class to include your custom post-processing.

2. **Extend the `postprocess` Method:**
   You can override the `postprocess` method to include your custom logic. Below is an example of how you might do this:

   ```python
   from ultralytics.models.yolo.detect import DetectionPredictor

   class CustomPredictor(DetectionPredictor):
       def postprocess(self, preds, img, orig_imgs):
           # Call the original postprocess method
           results = super().postprocess(preds, img, orig_imgs)
           
           # Add your custom post-processing here
           for result in results:
               # Example: Modify bbox and conf vectors
               result.boxes = your_custom_bbox_processing(result.boxes)
               result.conf = your_custom_conf_processing(result.conf)
           
           return results

       def your_custom_bbox_processing(self, boxes):
           # Implement your custom bbox processing logic here
           return boxes

       def your_custom_conf_processing(self, conf):
           # Implement your custom confidence processing logic here
           return conf
   ```

3. **Use Your Custom Predictor:**
   Replace the default predictor with your custom predictor in your validation script:

   ```python
   from ultralytics import YOLO
   from path.to.your.custom_predictor import CustomPredictor

   model = YOLO('yolov8n.pt')
   predictor = CustomPredictor(model=model)
   results = predictor.predict(source='path/to/your/data')
   ```

This approach allows you to seamlessly integrate your custom post-processing logic into the YOLOv8 validation pipeline.

If you encounter any issues or need further assistance, please ensure you are using the latest versions of `torch` and `ultralytics`. You can update your packages using:
```bash
pip install --upgrade torch ultralytics
```

Feel free to submit a PR if you have improvements or additional features to contribute. Your contributions are always welcome!

**Comment by Linengyao** [comment]
I found in the ultralytics\models\yolo\detect\val.py file that the default value of multi_label in the NMS processing of the post-processing function is True. Does this mean that YOLOv8 outputs multi-labels by default? However, none of my training and validation data are multi-label, but I still use this default multi-label setting, multi_label=True, so does this affect my results?
    ```
def postprocess(self, preds):
        """Apply Non-maximum suppression to prediction outputs."""
        
        return ops.non_max_suppression(
            preds,
            self.args.conf,
            self.args.iou,
            labels=self.lb,
            multi_label=True,
            agnostic=self.args.single_cls,
            max_det=self.args.max_det,
            )
```

**Comment by glenn-jocher** [comment]
Hello @Linengyao,

Thank you for your question! The `multi_label=True` setting in the `non_max_suppression` function allows the model to output multiple labels for a single bounding box if it detects multiple classes with high confidence. However, if your training and validation data are not multi-label, this setting should not negatively impact your results.

When `multi_label=True`, the model will still perform as expected for single-label data. It will simply not find multiple labels for each bounding box unless the confidence scores for multiple classes are high enough, which is unlikely if your data is single-label.

If you want to be absolutely certain, you can set `multi_label=False` to ensure that each bounding box is assigned only one label. Here’s how you can modify the `postprocess` function:

```python
def postprocess(self, preds):
    """Apply Non-maximum suppression to prediction outputs."""
    
    return ops.non_max_suppression(
        preds,
        self.args.conf,
        self.args.iou,
        labels=self.lb,
        multi_label=False,  # Change this to False
        agnostic=self.args.single_cls,
        max_det=self.args.max_det,
    )
```

This change will ensure that each bounding box is assigned a single label, which aligns with your single-label dataset.

If you encounter any issues or have further questions, please ensure you are using the latest versions of `torch` and `ultralytics`. You can update your packages using:
```bash
pip install --upgrade torch ultralytics
```

Feel free to reach out if you need more assistance. Happy coding! 😊

**Comment by Linengyao** [comment]
> 你好 ，
> 
> 谢谢你的提问！函数中的设置允许模型在以高置信度检测多个类时为单个边界框输出多个标签。但是，如果训练和验证数据不是多标签的，则此设置不会对结果产生负面影响。`multi_label=True``non_max_suppression`
> 
> 当 时，模型仍将按预期执行单标签数据。除非多个类的置信度分数足够高，否则它根本不会为每个边界框找到多个标签，如果您的数据是单标签的，则不太可能这样做。`multi_label=True`
> 
> 如果要绝对确定，可以设置以确保每个边界框仅分配一个标签。修改函数的方法如下：`multi_label=False``postprocess`
> 
> ```python
> def postprocess(self, preds):
>     """Apply Non-maximum suppression to prediction outputs."""
>     
>     return ops.non_max_suppression(
>         preds,
>         self.args.conf,
>         self.args.iou,
>         labels=self.lb,
>         multi_label=False,  # Change this to False
>         agnostic=self.args.single_cls,
>         max_det=self.args.max_det,
>     )
> ```
> 
> 此更改将确保为每个边界框分配一个与单标签数据集一致的单个标签。
> 
> 如果您遇到任何问题或有其他疑问，请确保您使用的是最新版本的 和 。您可以使用以下方法更新程序包：`torch``ultralytics`
> 
> ```shell
> pip install --upgrade torch ultralytics
> ```
> 
> 如果您需要更多帮助，请随时与我们联系。祝您编码愉快！😊
Tankyou for reply！I understand.
And I encountered a problem during verification. My post-processing involves timing information, so I need the input images to not be disrupted. My dataset consists of segments of videos (of course, there are also images that make up each video and the corresponding image annotations), and I need each video to form a batch. For example, I have a total of 10 videos, batch_size=1, then each batch has a video. The data loader puts the images that make up this video into the model frame by frame, and passes through the model and my custom post-processing output with timing. When all the images of this video have passed through the model and post-processing, the corresponding indicators such as mAP are calculated. At this time, a batch ends and the next batch is carried out. What should I do? Do I need to reconstruct your data loading? If so, which files should I modify? (Currently only for the verifier part, training is still trained in the original way, and verification is verified according to the video input method I mentioned above)

**Comment by glenn-jocher** [comment]
Hello @Linengyao,

Thank you for your detailed question! It sounds like you have a unique requirement for processing video segments in batches during validation, and you need to ensure the temporal order of frames is preserved for your custom post-processing.

To achieve this, you will indeed need to customize the data loading and validation process. Here’s a step-by-step guide to help you:

1. **Custom DataLoader:**
   You will need to create a custom DataLoader that ensures each batch consists of frames from a single video. You can extend the existing DataLoader to handle this.

2. **Modify the Validation Loop:**
   You will need to modify the validation loop to process each batch (video) frame by frame, applying your custom post-processing and then calculating the metrics.

### Step-by-Step Implementation

1. **Custom DataLoader:**
   Create a custom dataset class that loads frames from a video and ensures they are batched correctly.

   ```python
   from torch.utils.data import Dataset, DataLoader
   import os
   import cv2

   class VideoDataset(Dataset):
       def __init__(self, video_paths, transform=None):
           self.video_paths = video_paths
           self.transform = transform

       def __len__(self):
           return len(self.video_paths)

       def __getitem__(self, idx):
           video_path = self.video_paths[idx]
           cap = cv2.VideoCapture(video_path)
           frames = []
           while cap.isOpened():
               ret, frame = cap.read()
               if not ret:
                   break
               if self.transform:
                   frame = self.transform(frame)
               frames.append(frame)
           cap.release()
           return frames

   def collate_fn(batch):
       return batch
   ```

2. **Modify the Validation Loop:**
   Modify the validation loop to process each batch (video) frame by frame.

   ```python
   from ultralytics import YOLO
   from torch.utils.data import DataLoader

   # Load your model
   model = YOLO('yolov8n.pt')

   # Define your video paths
   video_paths = ['path/to/video1.mp4', 'path/to/video2.mp4', ...]

   # Create the dataset and dataloader
   dataset = VideoDataset(video_paths)
   dataloader = DataLoader(dataset, batch_size=1, collate_fn=collate_fn)

   # Custom validation loop
   for batch in dataloader:
       for frames in batch:
           for frame in frames:
               results = model.predict(frame)
               # Apply your custom post-processing here
               # ...
           # Calculate metrics for the entire video
           # ...
   ```

3. **Integrate with YOLOv8:**
   You may need to integrate this custom DataLoader and validation loop into the YOLOv8 framework. This might involve modifying the `val.py` file in `ultralytics/models/yolo/detect/`.

### Files to Modify:
- **Custom DataLoader:** You can create a new file for your custom DataLoader.
- **Validation Script:** Modify the `val.py` file in `ultralytics/models/yolo/detect/` to incorporate your custom validation loop.

By following these steps, you should be able to process each video as a batch, maintain the temporal order of frames, and apply your custom post-processing.

If you encounter any issues or need further assistance, please ensure you are using the latest versions of `torch` and `ultralytics`. You can update your packages using:
```bash
pip install --upgrade torch ultralytics
```

Feel free to reach out if you need more help. Happy coding! 😊

**Comment by Linengyao** [comment]
I have created a custom predictor：
```
class VidPredictor(BasePredictor):
    def postprocess(self, preds, img, orig_imgs):
        """Post-processes predictions and returns a list of Results objects."""
        print("\n VVVVVVVVVVVVVVV \n")
        preds = ops.non_max_suppression(
            preds,
            self.args.conf,
            self.args.iou,
            agnostic=self.args.agnostic_nms,
            max_det=self.args.max_det,
            classes=self.args.classes,
        )

        if not isinstance(orig_imgs, list):  # input images are a torch.Tensor, not a list
            orig_imgs = ops.convert_torch2numpy_batch(orig_imgs)

        results = []
        for i, pred in enumerate(preds):
            orig_img = orig_imgs[i]
            pred[:, :4] = ops.scale_boxes(img.shape[2:], pred[:, :4], orig_img.shape)
            img_path = self.batch[0][i]
            results.append(Results(orig_img, path=img_path, names=self.model.names, boxes=pred))
        return results
    
    def __call__(self, source=None, model=None, stream=False, *args, **kwargs):
        """Performs inference on an image or stream."""
        self.stream = stream
        if stream:
            print("\n OOOOOOOOO \n")
            c = self.test()
            return self.stream_inference(source, model, *args, **kwargs)
        else:
            print("\n UUUUUUUUU \n")
            return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
        
    def test(self):
        print("\npppppppppppppppppp\n")
        return 1
    
    # @smart_inference_mode()
    def stream_inference(self, source=None, model=None, *args, **kwargs):
        print("\nSSSSSSSSSSSSSSSSSS\n")
        """Streams real-time inference on camera feed and saves results to file."""
        if self.args.verbose:
            LOGGER.info("")

        # Setup model
        if not self.model:
            self.setup_model(model)

        with self._lock:  # for thread-safe inference
            # Setup source every time predict is called
            self.setup_source(source if source is not None else self.args.source)

            # Check if save_dir/ label file exists
            if self.args.save or self.args.save_txt:
                (self.save_dir / "labels" if self.args.save_txt else self.save_dir).mkdir(parents=True, exist_ok=True)

            # Warmup model
            if not self.done_warmup:
                self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
                self.done_warmup = True

            self.seen, self.windows, self.batch = 0, [], None
            profilers = (
                ops.Profile(device=self.device),
                ops.Profile(device=self.device),
                ops.Profile(device=self.device),
            )
            self.run_callbacks("on_predict_start")
            for self.batch in self.dataset:
                self.run_callbacks("on_predict_batch_start")
                paths, im0s, s = self.batch

                # Preprocess
                with profilers[0]:
                    im = self.preprocess(im0s)

                # Inference
                with profilers[1]:
                    preds = self.inference(im, *args, **kwargs)
                    if self.args.embed:
                        yield from [preds] if isinstance(preds, torch.Tensor) else preds  # yield embedding tensors
                        continue

                # Postprocess
                with profilers[2]:
                    self.results = self.postprocess(preds, im, im0s)
                self.run_callbacks("on_predict_postprocess_end")

                # Visualize, save, write results
                n = len(im0s)
                for i in range(n):
                    self.seen += 1
                    self.results[i].speed = {
                        "preprocess": profilers[0].dt * 1e3 / n,
                        "inference": profilers[1].dt * 1e3 / n,
                        "postprocess": profilers[2].dt * 1e3 / n,
                    }
                    if self.args.verbose or self.args.save or self.args.save_txt or self.args.show:
                        s[i] += self.write_results(i, Path(paths[i]), im, s)

                # Print batch results
                if self.args.verbose:
                    LOGGER.info("\n".join(s))

                self.run_callbacks("on_predict_batch_end")
                yield from self.results

        # Release assets
        for v in self.vid_writer.values():
            if isinstance(v, cv2.VideoWriter):
                v.release()

        # Print final results
        if self.args.verbose and self.seen:
            t = tuple(x.t / self.seen * 1e3 for x in profilers)  # speeds per image
            LOGGER.info(
                f"Speed: %.1fms preprocess, %.1fms inference, %.1fms postprocess per image at shape "
                f"{(min(self.args.batch, self.seen), 3, *im.shape[2:])}" % t
            )
        if self.args.save or self.args.save_txt or self.args.save_crop:
            nl = len(list(self.save_dir.glob("labels/*.txt")))  # number of labels
            s = f"\n{nl} label{'s' * (nl > 1)} saved to {self.save_dir / 'labels'}" if self.args.save_txt else ""
            LOGGER.info(f"Results saved to {colorstr('bold', self.save_dir)}{s}")
        self.run_callbacks("on_predict_end")
```
but i find when i set stream=True, i will only output "OOOOOOOOO" and "pppppppppppppppppp".
when i set stream=False, it will output "UUUUUUUUU"  "SSSSSSSSSSSSSSSSSS" and "VVVVVVVVVVVVVVV"
it looks like when stream=True **stream_inference**will not be entered?Will he be executed?

I need to get the result of the current image by modifying the **postprocess** function, but this situation confuses me. I don't know whether my modifications to the postprocess and __call__ functions will work?

**Comment by glenn-jocher** [comment]
Hello @Linengyao,

Thank you for sharing your custom predictor code and the detailed explanation of your issue. It looks like you've done a great job creating a custom predictor class. Let's address your concerns about the `stream=True` behavior and the `postprocess` function.

### Understanding the Issue

From your description, it seems that when `stream=True`, the `stream_inference` method is not being executed as expected. This might be due to how the `__call__` method is structured. Let's break down the potential issues and provide a solution.

### Potential Issue

The `__call__` method in your `VidPredictor` class is designed to handle both streaming and non-streaming modes. However, it seems that the `stream_inference` method is not being called when `stream=True`.

### Solution

1. **Ensure `stream_inference` is Called:**
   Make sure that the `stream_inference` method is correctly called when `stream=True`.

2. **Debugging Prints:**
   Use print statements to debug and ensure that the correct methods are being called.

Here’s an updated version of your `VidPredictor` class with additional debugging prints and a slight restructuring to ensure `stream_inference` is called correctly:

```python
class VidPredictor(BasePredictor):
    def postprocess(self, preds, img, orig_imgs):
        """Post-processes predictions and returns a list of Results objects."""
        print("\n VVVVVVVVVVVVVVV \n")
        preds = ops.non_max_suppression(
            preds,
            self.args.conf,
            self.args.iou,
            agnostic=self.args.agnostic_nms,
            max_det=self.args.max_det,
            classes=self.args.classes,
        )

        if not isinstance(orig_imgs, list):  # input images are a torch.Tensor, not a list
            orig_imgs = ops.convert_torch2numpy_batch(orig_imgs)

        results = []
        for i, pred in enumerate(preds):
            orig_img = orig_imgs[i]
            pred[:, :4] = ops.scale_boxes(img.shape[2:], pred[:, :4], orig_img.shape)
            img_path = self.batch[0][i]
            results.append(Results(orig_img, path=img_path, names=self.model.names, boxes=pred))
        return results
    
    def __call__(self, source=None, model=None, stream=False, *args, **kwargs):
        """Performs inference on an image or stream."""
        self.stream = stream
        if stream:
            print("\n OOOOOOOOO \n")
            return self.stream_inference(source, model, *args, **kwargs)
        else:
            print("\n UUUUUUUUU \n")
            return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
        
    def test(self):
        print("\npppppppppppppppppp\n")
        return 1
    
    # @smart_inference_mode()
    def stream_inference(self, source=None, model=None, *args, **kwargs):
        print("\nSSSSSSSSSSSSSSSSSS\n")
        """Streams real-time inference on camera feed and saves results to file."""
        if self.args.verbose:
            LOGGER.info("")

        # Setup model
        if not self.model:
            self.setup_model(model)

        with self._lock:  # for thread-safe inference
            # Setup source every time predict is called
            self.setup_source(source if source is not None else self.args.source)

            # Check if save_dir/ label file exists
            if self.args.save or self.args.save_txt:
                (self.save_dir / "labels" if self.args.save_txt else self.save_dir).mkdir(parents=True, exist_ok=True)

            # Warmup model
            if not self.done_warmup:
                self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
                self.done_warmup = True

            self.seen, self.windows, self.batch = 0, [], None
            profilers = (
                ops.Profile(device=self.device),
                ops.Profile(device=self.device),
                ops.Profile(device=self.device),
            )
            self.run_callbacks("on_predict_start")
            for self.batch in self.dataset:
                self.run_callbacks("on_predict_batch_start")
                paths, im0s, s = self.batch

                # Preprocess
                with profilers[0]:
                    im = self.preprocess(im0s)

                # Inference
                with profilers[1]:
                    preds = self.inference(im, *args, **kwargs)
                    if self.args.embed:
                        yield from [preds] if isinstance(preds, torch.Tensor) else preds  # yield embedding tensors
                        continue

                # Postprocess
                with profilers[2]:
                    self.results = self.postprocess(preds, im, im0s)
                self.run_callbacks("on_predict_postprocess_end")

                # Visualize, save, write results
                n = len(im0s)
                for i in range(n):
                    self.seen += 1
                    self.results[i].speed = {
                        "preprocess": profilers[0].dt * 1e3 / n,
                        "inference": profilers[1].dt * 1e3 / n,
                        "postprocess": profilers[2].dt * 1e3 / n,
                    }
                    if self.args.verbose or self.args.save or self.args.save_txt or self.args.show:
                        s[i] += self.write_results(i, Path(paths[i]), im, s)

                # Print batch results
                if self.args.verbose:
                    LOGGER.info("\n".join(s))

                self.run_callbacks("on_predict_batch_end")
                yield from self.results

        # Release assets
        for v in self.vid_writer.values():
            if isinstance(v, cv2.VideoWriter):
                v.release()

        # Print final results
        if self.args.verbose and self.seen:
            t = tuple(x.t / self.seen * 1e3 for x in profilers)  # speeds per image
            LOGGER.info(
                f"Speed: %.1fms preprocess, %.1fms inference, %.1fms postprocess per image at shape "
                f"{(min(self.args.batch, self.seen), 3, *im.shape[2:])}" % t
            )
        if self.args.save or self.args.save_txt or self.args.save_crop:
            nl = len(list(self.save_dir.glob("labels/*.txt")))  # number of labels
            s = f"\n{nl} label{'s' * (nl > 1)} saved to {self.save_dir / 'labels'}" if self.args.save_txt else ""
            LOGGER.info(f"Results saved to {colorstr('bold', self.save_dir)}{s}")
        self.run_callbacks("on_predict_end")
```

### Key Changes:
1. **Ensure `stream_inference` is Called:**
   The `return self.stream_inference(source, model, *args, **kwargs)` line ensures that `stream_inference` is called when `stream=True`.

2. **Debugging Prints:**
   Added print statements to confirm the flow of execution.

### Next Steps:
1. **Verify the Bug:**
   Ensure you are using the latest versions of `torch` and `ultralytics`. If not, please upgrade:
   ```bash
   pip install --upgrade torch ultralytics
   ```

2. **Test the Modified Code:**
   Run your code with the updated `VidPredictor` class and check if the `stream_inference` method is executed as expected.

If you continue to face issues, please provide a minimal reproducible example so we can investigate further. You can refer to our [Minimum Reproducible Example Guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

Feel free to reach out if you need more assistance. Happy coding! 😊
