### ISSUE TITLE
Inconsistencies with `max_det`

### ISSUE THREAD

**Issue by fbarbe00** [ultralytics/ultralytics#13598]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I was playing around with a YOLO v8 model and the `max_det` parameter and found the following issue: if you once set `max_det=1`, it will keep returning only one prediction even if the argument is removed.

As you can see, in the code example, if you once set `max_det=1`, it will keep returning only one prediction until the model is loaded again. When testing, I also came across some inconsistencies with the confidence being different with and without `max_det=1`, but I was not able to replicate them, so it might just have been something off in my code.

The model I'm using is a trained YOLOv8 model that predicts both keypoints and boxes. I can't unfortunately shared the model as it is part of my work.

### Environment

Ultralytics YOLOv8.2.31 🚀 Python-3.8.10 torch-2.2.2+cu121 CPU (Intel Core(TM) i7-9750H 2.60GHz)
Setup complete ✅ (12 CPUs, 15.5 GB RAM, 102.4/195.8 GB disk)

### Minimal Reproducible Example

```py
model = YOLO(f"../{CURRENT_MODEL}.pt")
result = model(image, iou=0.9, conf=0.01)[0]
print(f"1. Loaded model, no max_det - Number of predictions: {len(result.boxes.conf)}") # 32

result = model(image, iou=0.9, conf=0.01, max_det=1)[0]
print(f"2. Same model obj, max_det=1 - Number of predictions: {len(result.boxes.conf)}") # 1


result = model(image, iou=0.9, conf=0.01)[0]
print(f"3. Same model obj, no max_det - Number of predictions: {len(result.boxes.conf)}") # 1

model = YOLO(f"../{CURRENT_MODEL}.pt")
result = model(image, iou=0.9, conf=0.01)[0]

print(f"4. Loaded model, no max_det - Number of predictions: {len(result.boxes.conf)}") # 32
```

The output of the above code is:
```
0: 640x640 32 part_7s, 425.1ms
Speed: 1.7ms preprocess, 425.1ms inference, 0.9ms postprocess per image at shape (1, 3, 640, 640)
1. Loaded model, no max_det - Number of predictions: 32

0: 640x640 1 part_7, 407.9ms
Speed: 1.5ms preprocess, 407.9ms inference, 0.8ms postprocess per image at shape (1, 3, 640, 640)
2. Same model obj, max_det=1 - Number of predictions: 1

0: 640x640 1 part_7, 407.5ms
Speed: 2.1ms preprocess, 407.5ms inference, 0.7ms postprocess per image at shape (1, 3, 640, 640)
3. Same model obj, no max_det - Number of predictions: 1

0: 640x640 32 part_7s, 451.2ms
Speed: 2.8ms preprocess, 451.2ms inference, 0.9ms postprocess per image at shape (1, 3, 640, 640)
4. Loaded model, no max_det - Number of predictions: 32
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@fbarbe00 hi there,

Thank you for bringing this to our attention and providing a detailed report along with a reproducible code example. This is very helpful! 😊

It appears that the `max_det` parameter is being retained across subsequent predictions even when it is not explicitly set. This behavior is indeed unexpected and could be indicative of a bug.

To help us investigate further, could you please confirm the following:
1. Are you using the latest versions of `torch` and `ultralytics`? If not, please upgrade to the latest versions and try running your code again:
    ```bash
    pip install --upgrade torch ultralytics
    ```

2. If the issue persists after upgrading, please provide any additional details that might help us reproduce the bug, such as the specific model architecture and any custom modifications you might have made.

In the meantime, as a workaround, you can reinitialize the model object before each prediction to ensure that the `max_det` parameter does not carry over:
```python
from ultralytics import YOLO

model = YOLO(f"../{CURRENT_MODEL}.pt")
result = model(image, iou=0.9, conf=0.01)[0]
print(f"1. Loaded model, no max_det - Number of predictions: {len(result.boxes.conf)}") # 32

model = YOLO(f"../{CURRENT_MODEL}.pt")
result = model(image, iou=0.9, conf=0.01, max_det=1)[0]
print(f"2. Reinitialized model, max_det=1 - Number of predictions: {len(result.boxes.conf)}") # 1

model = YOLO(f"../{CURRENT_MODEL}.pt")
result = model(image, iou=0.9, conf=0.01)[0]
print(f"3. Reinitialized model, no max_det - Number of predictions: {len(result.boxes.conf)}") # 32
```

This should ensure that each prediction is independent of the previous ones.

Please let us know if this resolves the issue or if you need further assistance. We appreciate your patience and cooperation as we work to improve our models.

**Comment by fbarbe00** [comment]
Hey! Thanks for your reply. As I wrote in the environment section, this was with Ultralytics v8.2.31 and torch-2.2.2+cu121
I have updated both ultralytics and torch, and can confirm that the issue still persists

**Comment by glenn-jocher** [comment]
Hi @fbarbe00,

Thank you for the update and for confirming that you're using the latest versions of `ultralytics` and `torch`. We appreciate your diligence in testing this.

Given that the issue persists, it seems there might be a bug with how the `max_det` parameter is being retained across predictions. To ensure we can investigate this thoroughly, could you please provide a minimal reproducible example that demonstrates the issue? This will help us reproduce the bug on our end and work towards a solution. You can find guidelines for creating a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

In the meantime, as a workaround, you can reinitialize the model object before each prediction to ensure that the `max_det` parameter does not carry over:

```python
from ultralytics import YOLO

model = YOLO(f"../{CURRENT_MODEL}.pt")
result = model(image, iou=0.9, conf=0.01)[0]
print(f"1. Loaded model, no max_det - Number of predictions: {len(result.boxes.conf)}") # 32

model = YOLO(f"../{CURRENT_MODEL}.pt")
result = model(image, iou=0.9, conf=0.01, max_det=1)[0]
print(f"2. Reinitialized model, max_det=1 - Number of predictions: {len(result.boxes.conf)}") # 1

model = YOLO(f"../{CURRENT_MODEL}.pt")
result = model(image, iou=0.9, conf=0.01)[0]
print(f"3. Reinitialized model, no max_det - Number of predictions: {len(result.boxes.conf)}") # 32
```

This should ensure that each prediction is independent of the previous ones.

Thank you for your patience and cooperation. We're here to help, so please let us know if you need any further assistance!

**Comment by fbarbe00** [comment]
Hi,

Thank you for the effort of reading and answering most issues.
However, have you guys actually read my initial issue? I had already provided both the version and code to replicate the issue. I actually also already provided the workaround you suggested.

Here's an even more minimal version of the code, that you can run directly:
```py
import torch
from ultralytics import YOLO
model = YOLO("yolov8n.pt")
image = torch.rand(1, 3, 640, 640)
result = model(image, iou=0.9, conf=0.01)[0]
print(f"1. Loaded model, no max_det - Number of predictions: {len(result.boxes.conf)}")

result = model(image, iou=0.9, conf=0.01, max_det=1)[0]
print(f"2. Same model obj, max_det=1 - Number of predictions: {len(result.boxes.conf)}")


result = model(image, iou=0.9, conf=0.01)[0]
print(f"3. Same model obj, no max_det - Number of predictions: {len(result.boxes.conf)}")

model = YOLO("yolov8n.pt")
result = model(image, iou=0.9, conf=0.01)[0]

print(f"4. Loaded model, no max_det - Number of predictions: {len(result.boxes.conf)}")
```

Note that since the image is random, it might not always return more than one box (but usually does, since the conf is so low)

**Comment by glenn-jocher** [comment]
Hi @fbarbe00,

Thank you for your detailed follow-up and for providing a more minimal code example. We appreciate your effort in helping us understand and reproduce the issue. 😊

I have reviewed your code and can confirm that the behavior you're experiencing with the `max_det` parameter being retained across predictions is indeed unexpected. This looks like a bug that needs further investigation.

Here’s a concise summary of the issue:
1. Setting `max_det=1` limits the number of predictions to one.
2. Subsequent predictions without `max_det` still return only one prediction until the model is reloaded.

Your minimal reproducible example is very helpful. We will investigate this behavior further to identify the root cause and work on a fix.

In the meantime, as a workaround, reinitializing the model before each prediction, as you mentioned, ensures that the `max_det` parameter does not carry over. Here’s a quick reminder of that approach:

```python
from ultralytics import YOLO
import torch

model = YOLO("yolov8n.pt")
image = torch.rand(1, 3, 640, 640)

# Initial prediction without max_det
result = model(image, iou=0.9, conf=0.01)[0]
print(f"1. Loaded model, no max_det - Number of predictions: {len(result.boxes.conf)}")

# Prediction with max_det=1
result = model(image, iou=0.9, conf=0.01, max_det=1)[0]
print(f"2. Same model obj, max_det=1 - Number of predictions: {len(result.boxes.conf)}")

# Reinitialize model to reset parameters
model = YOLO("yolov8n.pt")
result = model(image, iou=0.9, conf=0.01)[0]
print(f"3. Reinitialized model, no max_det - Number of predictions: {len(result.boxes.conf)}")
```

We appreciate your patience and understanding as we work to resolve this issue. If you have any further questions or additional details to share, please feel free to let us know.
