### ISSUE TITLE
Are there any Yolov8 Pose model implmentation with coreml?

### ISSUE THREAD

**Issue by samxu29** [ultralytics/ultralytics#13603]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am doing an academic research project that require using a 2D pose estimation as first step of pipline for ios edge device.
I have successfully converted the model into coreml format, but I have no idea how to use them.

Here is a screenshot of the input and output size/format for the mlpackage.
<img width="864" alt="image" src="https://github.com/ultralytics/ultralytics/assets/22229980/1333adbc-3d89-4ac2-8619-9896a5fc298c">

I am not proficient with swift or xcode, therefore I am asking if there is any project out there that utilizing yolov8-pose model in coreml format for inference in ios environment?

**Comment by glenn-jocher** [comment]
@samxu29 hello,

Thank you for reaching out and for your interest in using YOLOv8 Pose models with CoreML for your academic research project! It's great to hear that you've successfully converted the model to CoreML format. 

To help you get started with using the YOLOv8 Pose model in an iOS environment, here are some steps and resources that might be useful:

### Using CoreML Models in iOS

1. **Importing the CoreML Model into Xcode**:
   - Drag and drop the `.mlpackage` file into your Xcode project.
   - Xcode will automatically generate a Swift class for your model.

2. **Setting Up the Model in Swift**:
   - You can use the generated Swift class to perform inference. Here’s a basic example of how to set up and use the model in your iOS app:

    ```swift
    import CoreML
    import Vision
    import UIKit

    class ViewController: UIViewController {
        var model: YOLOv8nPose?

        override func viewDidLoad() {
            super.viewDidLoad()
            // Load the model
            model = try? YOLOv8nPose(configuration: MLModelConfiguration())
        }

        func predict(image: UIImage) {
            guard let model = model else { return }
            guard let pixelBuffer = image.pixelBuffer() else { return }

            // Create a CoreML request
            let request = VNCoreMLRequest(model: VNCoreMLModel(for: model.model)) { (request, error) in
                if let results = request.results as? [VNRecognizedObjectObservation] {
                    // Handle the results
                    for result in results {
                        print(result)
                    }
                }
            }

            // Perform the request
            let handler = VNImageRequestHandler(cvPixelBuffer: pixelBuffer, options: [:])
            try? handler.perform([request])
        }
    }

    extension UIImage {
        func pixelBuffer() -> CVPixelBuffer? {
            // Convert UIImage to CVPixelBuffer
            // Implementation here...
        }
    }
    ```

3. **Handling Model Inputs and Outputs**:
   - Ensure that the input image is preprocessed to match the model’s expected input size and format.
   - Post-process the model’s output to extract the pose keypoints.

### Resources

- **CoreML Tools**: [CoreML Tools Documentation](https://apple.github.io/coremltools/)
- **Apple Developer Documentation**: [Integrating a Core ML Model into Your App](https://developer.apple.com/documentation/coreml/integrating_a_core_ml_model_into_your_app)
- **Vision Framework**: [Using Vision with Core ML](https://developer.apple.com/documentation/vision/using_vision_in_real_time_with_a_core_ml_model)

These resources should provide you with a comprehensive guide on how to integrate and use CoreML models within your iOS applications.

If you encounter any specific issues or have further questions, feel free to ask. The YOLO community and the Ultralytics team are here to help!

Best of luck with your research project! 🚀

**Comment by glenn-jocher** [comment]
Hello @samxu29,

Thank you for your question and for providing the output array. To translate the `var_1035` output into keypoints, you can follow these steps:

1. **Understand the Output Format**:
   The `var_1035` array likely contains the keypoint coordinates and possibly their confidence scores. Typically, keypoints are represented as (x, y) pairs, and sometimes with an additional confidence score.

2. **Reshape the Array**:
   Depending on the model's output format, you may need to reshape the array to extract the keypoints. For example, if each keypoint is represented by three values (x, y, confidence), you can reshape the array accordingly.

3. **Extract Keypoints**:
   Iterate through the reshaped array to extract the keypoints.

Here’s a Python code example to help you get started:

```python
import numpy as np

# Example output from the model
output = {'var_1035': np.array([[[1.08046875e+01, 1.92031250e+01, 2.46250000e+01, ...,
                                 5.16000000e+02, 5.46000000e+02, 5.78000000e+02],
                                [2.10312500e+01, 1.43437500e+01, 1.32031250e+01, ...,
                                 5.56000000e+02, 5.52000000e+02, 4.95000000e+02],
                                [3.71875000e+01, 4.70625000e+01, 4.84375000e+01, ...,
                                 2.59250000e+02, 2.05000000e+02, 1.29500000e+02],
                                ...,
                                [3.49218750e+00, 1.32187500e+01, 1.70468750e+01, ...,
                                 5.48500000e+02, 6.18500000e+02, 6.25500000e+02],
                                [3.53437500e+01, 2.96718750e+01, 2.82031250e+01, ...,
                                 6.37500000e+02, 6.36000000e+02, 6.31000000e+02],
                                [1.11572266e-01, 1.36962891e-01, 1.31713867e-01, ...,
                                 1.32293701e-02, 1.97601318e-02, 3.91540527e-02]]], dtype=np.float32)}

# Assuming each keypoint is represented by (x, y, confidence)
keypoints = output['var_1035'].reshape(-1, 3)

# Print keypoints
for i, (x, y, conf) in enumerate(keypoints):
    print(f"Keypoint {i}: x={x}, y={y}, confidence={conf}")
```

This code assumes that each keypoint is represented by three values (x, y, confidence). Adjust the reshaping and extraction logic based on your specific model's output format.

If you encounter any issues or need further assistance, please ensure you are using the latest versions of `torch` and `ultralytics` packages. You can update them using:

```bash
pip install --upgrade torch ultralytics
```

For more detailed guidance on using CoreML models, you can refer to the [CoreML documentation](https://docs.ultralytics.com/integrations/coreml/).

Feel free to reach out if you have any more questions. Best of luck with your project! 🚀

**Comment by samxu29** [comment]
Thank you so much for your help!
I have got 
```
Keypoint 156787: x=0.024139404296875, y=0.01486968994140625, confidence=0.00937652587890625
Keypoint 156788: x=0.00957489013671875, y=0.01120758056640625, confidence=0.01169586181640625
Keypoint 156789: x=0.026702880859375, y=0.13720703125, confidence=0.419189453125
Keypoint 156790: x=0.62255859375, y=0.640625, confidence=0.5107421875
Keypoint 156791: x=0.21923828125, y=0.06396484375, confidence=0.048095703125
Keypoint 156792: x=0.0340576171875, y=0.013885498046875, confidence=0.0236968994140625
Keypoint 156793: x=0.043731689453125, y=0.037017822265625, confidence=0.0247955322265625
Keypoint 156794: x=0.01465606689453125, y=0.00904083251953125, confidence=0.0094757080078125
Keypoint 156795: x=0.01203155517578125, y=0.0152587890625, confidence=0.0225982666015625
Keypoint 156796: x=0.045928955078125, y=0.125732421875, confidence=0.2440185546875
Keypoint 156797: x=0.255126953125, y=0.2008056640625, confidence=0.107666015625
Keypoint 156798: x=0.046844482421875, y=0.031646728515625, confidence=0.02117919921875
Keypoint 156799: x=0.0132293701171875, y=0.0197601318359375, confidence=0.039154052734375
...
```
but mapping to the image I get 
<img width="639" alt="image" src="https://github.com/ultralytics/ultralytics/assets/22229980/24ca29d6-1e25-4d19-afe9-a30b13490e78">

this is the code I have used below 
```
import coremltools
from PIL import Image
import cv2
import numpy as np

# Load the Core ML model
coreml_model = coremltools.models.MLModel("models-pose/yolov8n-pose.mlpackage")

# Load the image
image = Image.open("pose.jpg")

# Resize the image to a specific size
target_size = (640, 640)  # Specify the desired size
image = image.resize(target_size)

# Create an input dictionary
input_dict = {"image": image}

# Perform inference using the Core ML model
output_dict = coreml_model.predict(input_dict)

print(output_dict)

# Assuming each keypoint is represented by (x, y, confidence)
keypoints = output_dict['var_1035'].reshape(-1, 3)
    
# Convert PIL image to OpenCV image
image_cv = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)

# Draw skeleton on the image
skeleton_image = image_cv.copy()
for i, (x, y, conf) in enumerate(keypoints):
    print(f"Keypoint {i}: x={x}, y={y}, confidence={conf}")
    
    if conf > 0.9:  # Only draw points with confidence above 0.9
        cv2.circle(skeleton_image, (int(x), int(y)), 5, (0, 255, 0), -1)

# Display the image with skeleton overlay
cv2.imshow("Skeleton Overlay", skeleton_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

```

The reason why I am trying to avoid using `ultralytics` library is that I don't think I am able to use the library in xcode/ios environment. I am using only simple `coremltools` is because I want to able to understand deeper on the implementation of the model output.

**Comment by glenn-jocher** [comment]
Hello @samxu29,

Thank you for sharing the details and the code snippet. It looks like you're on the right track with using `coremltools` for inference. The issue you're encountering with the keypoints mapping might be due to the normalization of the coordinates. Typically, the keypoints are normalized to the range [0, 1], and you need to scale them back to the original image dimensions.

Here's an updated version of your code that scales the keypoints correctly:

```python
import coremltools
from PIL import Image
import cv2
import numpy as np

# Load the Core ML model
coreml_model = coremltools.models.MLModel("models-pose/yolov8n-pose.mlpackage")

# Load the image
image = Image.open("pose.jpg")

# Resize the image to a specific size
target_size = (640, 640)  # Specify the desired size
image = image.resize(target_size)

# Create an input dictionary
input_dict = {"image": image}

# Perform inference using the Core ML model
output_dict = coreml_model.predict(input_dict)

print(output_dict)

# Assuming each keypoint is represented by (x, y, confidence)
keypoints = output_dict['var_1035'].reshape(-1, 3)

# Convert PIL image to OpenCV image
image_cv = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)

# Draw skeleton on the image
skeleton_image = image_cv.copy()
for i, (x, y, conf) in enumerate(keypoints):
    print(f"Keypoint {i}: x={x}, y={y}, confidence={conf}")
    
    # Scale the keypoints back to the image size
    x = int(x * target_size[0])
    y = int(y * target_size[1])
    
    if conf > 0.5:  # Only draw points with confidence above 0.5
        cv2.circle(skeleton_image, (x, y), 5, (0, 255, 0), -1)

# Display the image with skeleton overlay
cv2.imshow("Skeleton Overlay", skeleton_image)
cv2.waitKey(0)
cv2.destroyAllWindows()
```

### Key Changes:
1. **Scaling Keypoints**: The keypoints are likely normalized to the range [0, 1]. To map them correctly to the image, multiply the x and y coordinates by the image width and height, respectively.
2. **Confidence Threshold**: Adjusted the confidence threshold to 0.5 for better visualization.

This should help you map the keypoints correctly onto the image. If you have any further questions or run into other issues, feel free to ask. The YOLO community and the Ultralytics team are here to support you! 😊

Best of luck with your project! 🚀

**Comment by samxu29** [comment]
Hello, Sorry for keeping asking same dumb questions.

I think the reshape size you proved might not work as expected. 
```python
keypoints = output['var_1035'].reshape(-1, 3)
```

Because I am getting the similar results after playing around with the keypoints normalization based on the code you proved above.
<img width="640" alt="image" src="https://github.com/ultralytics/ultralytics/assets/22229980/54721fc2-382f-4857-b0ca-35c12f315d29">

compares to the results I got from using `ultralytics` library with code:
```python
from ultralytics import YOLO
from PIL import Image

# Load a model
# model = YOLO("models-pose/yolov8n-pose.pt")  # load an official model
model = YOLO("yolov8n-pose.mlpackage")  # load a custom model

# Open the image
image = Image.open("pose0.jpg")

# # Resize the image to the allowed size
resize = (640, 640)
image = image.resize(resize)

# Predict with the model
results = model(image)

# Show the image results
results[0].show()
```

<img width="640" alt="image" src="https://github.com/ultralytics/ultralytics/assets/22229980/c8ae794f-327b-4a25-b297-5a0570ab9d71">



Finally, are there any documents out there address the actual size the output need to be reshape to with coreml?

Just side note the coreml model I got was directly using `ultralytics` as example below:

```python
from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n-pose.pt")  # load an official model

# Export the model
model.export(format="coreml")
```

**Comment by glenn-jocher** [comment]
Hello @samxu29,

Thank you for your patience and for providing detailed information. No worries at all—your questions are valuable and help us improve our support!

### Clarifying the Keypoints Reshape Issue

It seems like the reshaping of the keypoints might not be aligning correctly with the expected format. Let's address this step-by-step.

1. **Verify Model Output Dimensions**:
   The output dimensions from the CoreML model should match the expected keypoints format. Typically, for pose estimation, the output might be in the form of `[num_keypoints, 3]` where each keypoint has `(x, y, confidence)`.

2. **Check the Shape of `var_1035`**:
   Before reshaping, let's inspect the shape of `var_1035` to ensure we are reshaping it correctly.

Here’s an updated approach to help you debug and reshape the keypoints correctly:

```python
import coremltools
from PIL import Image
import cv2
import numpy as np

# Load the Core ML model
coreml_model = coremltools.models.MLModel("models-pose/yolov8n-pose.mlpackage")

# Load the image
image = Image.open("pose.jpg")

# Resize the image to a specific size
target_size = (640, 640)  # Specify the desired size
image = image.resize(target_size)

# Create an input dictionary
input_dict = {"image": image}

# Perform inference using the Core ML model
output_dict = coreml_model.predict(input_dict)

# Check the shape of the output
print(f"Output shape: {output_dict['var_1035'].shape}")

# Assuming each keypoint is represented by (x, y, confidence)
keypoints = output_dict['var_1035'].reshape(-1, 3)

# Convert PIL image to OpenCV image
image_cv = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)

# Draw skeleton on the image
skeleton_image = image_cv.copy()
for i, (x, y, conf) in enumerate(keypoints):
    print(f"Keypoint {i}: x={x}, y={y}, confidence={conf}")
    
    # Scale the keypoints back to the image size
    x = int(x * target_size[0])
    y = int(y * target_size[1])
    
    if conf > 0.5:  # Only draw points with confidence above 0.5
        cv2.circle(skeleton_image, (x, y), 5, (0, 255, 0), -1)

# Display the image with skeleton overlay
cv2.imshow("Skeleton Overlay", skeleton_image)
cv2.waitKey(0)
cv2.destroyAllWindows()
```

### Documentation and Resources

Currently, there isn't a specific document detailing the exact reshape size for CoreML outputs, as this can vary depending on the model architecture. However, the general approach is to inspect the output dimensions and reshape accordingly.

### Using Ultralytics Library for Reference

Your results using the `ultralytics` library look correct. You can use the output from the library as a reference to validate your CoreML model's output. If the results differ significantly, it might indicate an issue with the CoreML conversion or the reshaping process.

### Ensuring Latest Versions

Please ensure you are using the latest versions of `torch` and `ultralytics` packages. You can update them using:

```bash
pip install --upgrade torch ultralytics
```

If you continue to face issues, please provide a minimum reproducible example so we can investigate further. You can find more details on creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions. We're here to help! 😊
