### ISSUE TITLE
I have downloaded kitti dataset the labels are both in string and float format I cannot covert into float as it has 7000 images and labels 

### ISSUE THREAD

**Issue by Jananiyar** [ultralytics/ultralytics#13615]
![Screenshot 2024-06-15 095237](https://github.com/ultralytics/ultralytics/assets/170570266/e88628c1-a4a3-43ff-88dc-ff2340f2b648)
![Screenshot 2024-06-15 095125](https://github.com/ultralytics/ultralytics/assets/170570266/35c483db-8874-4f7f-8c05-d5d4cd6eb734)

**Comment by glenn-jocher** [comment]
@Jananiyar hi there!

Thank you for reaching out. It looks like you're facing an issue with mixed data types in your KITTI dataset labels. To help you efficiently convert all labels to a consistent format, you can use a script to automate this process. Below is a Python example that reads the label files, converts the necessary fields to float, and saves them back:

```python
import os

def convert_labels_to_float(label_dir):
    for label_file in os.listdir(label_dir):
        if label_file.endswith('.txt'):
            file_path = os.path.join(label_dir, label_file)
            with open(file_path, 'r') as file:
                lines = file.readlines()
            
            with open(file_path, 'w') as file:
                for line in lines:
                    parts = line.split()
                    # Assuming the coordinates are in columns 4 to 7
                    parts[4:8] = map(float, parts[4:8])
                    file.write(' '.join(map(str, parts)) + '\n')

label_directory = 'path/to/your/label/directory'
convert_labels_to_float(label_directory)
```

This script will iterate over all `.txt` files in your specified label directory, convert the relevant parts to float, and save the changes.

Before running this script, please ensure you have the latest versions of `torch` and `ultralytics` installed. You can update them using:

```bash
pip install --upgrade torch ultralytics
```

If you encounter any issues or need further assistance, please provide a minimum reproducible code example as outlined in our [documentation](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us better understand and address your problem.

Happy coding! 😊
