### ISSUE TITLE
to tensorrt  error

### ISSUE THREAD

**Issue by stupidme123** [ultralytics/ultralytics#13621]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

**After I converted the generated pt model to tensorrt, I got the following error message:**

[06/15/2024-14:43:42] [TRT] [E] 3: [executionContext.cpp::validateInputBindings::2103] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::validateInputBindings::2103, condition: profileMaxDims.d[i] >= dimensions.d[i]. Supplied binding dimension [1,3,640,640] for bindings[0] exceed min ~ max range at index 2, maximum dimension in profile is 224, minimum dimension in profile is 224, but supplied dimension is 640.
)
Traceback (most recent call last):
  File "/home/jetson/yolov8/data/testp/p4.py", line 111, in <module>
    results = model.predict(pp, device=0)
  File "/home/jetson/third/ultralytics/ultralytics/engine/model.py", line 453, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/jetson/third/ultralytics/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/jetson/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/jetson/third/ultralytics/ultralytics/engine/predictor.py", line 261, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "/home/jetson/third/ultralytics/ultralytics/models/yolo/detect/predict.py", line 25, in postprocess
    preds = ops.non_max_suppression(
  File "/home/jetson/third/ultralytics/ultralytics/utils/ops.py", line 220, in non_max_suppression
    xc = prediction[:, 4:mi].amax(1) > conf_thres  # candidates
IndexError: amax(): Expected reduction dim 1 to have non-zero size.

I tried to change the parameter "imgsz" to 224, but it didn't work

### Environment

Ultralytics YOLOv8.2.32 🚀 Python-3.10.12 torch-2.3.0 CUDA:0 (Orin, 7620MiB)
Setup complete ✅ (6 CPUs, 7.4 GB RAM, 51.8/232.2 GB disk)

OS                  Linux-5.15.136-tegra-aarch64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             git
RAM                 7.44 GB
CPU                 aarch64
CUDA                12.2

matplotlib          ✅ 3.5.1>=3.3.0
opencv-python       ✅ 4.10.0.82>=4.6.0
pillow              ✅ 9.0.1>=7.1.2
pyyaml              ✅ 5.4.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.8.0>=1.4.1
torch               ✅ 2.3.0>=1.8.0
torchvision         ✅ 0.18.0>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 1.3.5>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 0.2.8>=0.2.5

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@stupidme123 hi there,

Thank you for reporting this issue and providing detailed information about your environment. It looks like you're encountering a dimension mismatch error when running inference with a TensorRT model.

To help us investigate and resolve this issue, could you please provide a minimal reproducible example? This will allow us to reproduce the bug on our end. You can find guidelines for creating a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example). This step is crucial for us to understand the context and specifics of the problem.

Additionally, please ensure that you are using the latest versions of both `torch` and `ultralytics`. You can update them using the following commands:
```bash
pip install --upgrade torch ultralytics
```

From the error message, it seems that the input dimensions for the TensorRT model are not matching the expected dimensions. Specifically, the model expects dimensions within the range of `[1, 3, 224, 224]`, but you are providing `[1, 3, 640, 640]`. To resolve this, you can try setting the `imgsz` parameter to 224 during both the export and inference stages.

Here’s an example of how to export the model with the correct image size and then run inference:
```python
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO("yolov8n.pt")

# Export the model to TensorRT format with the correct image size
model.export(format="engine", imgsz=224)  # creates 'yolov8n.engine'

# Load the exported TensorRT model
tensorrt_model = YOLO("yolov8n.engine")

# Run inference with the correct image size
results = tensorrt_model("https://ultralytics.com/images/bus.jpg", imgsz=224)
```

If you continue to experience issues, please share the minimal reproducible example, and we will be happy to assist further.

**Comment by davy-blavette** [comment]
@glenn-jocher  hi there,

I have the same error but i another context. I use triton-server with this code :

`    model = YOLO(f"http://localhost:8000/P0031_ensemble", task="detect")
    results = model(img, imgsz=352, save=False, conf=0.5)
    print(results)
`
with this error code : 

`
Traceback (most recent call last):
  File "/Models/Server/clients/yolo.py", line 126, in <module>
    main(args())
  File "/Models/Server/clients/yolo.py", line 28, in main
    predict(args.bench)
  File "/Models/Server/clients/yolo.py", line 108, in predict
    results = model(img, imgsz=352, save=False, conf=0.5)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/ultralytics/engine/model.py", line 177, in __call__
    return self.predict(source, stream, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/ultralytics/engine/model.py", line 453, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 261, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/ultralytics/models/yolo/detect/predict.py", line 25, in postprocess
    preds = ops.non_max_suppression(
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/ultralytics/utils/ops.py", line 220, in non_max_suppression
    xc = prediction[:, 4:mi].amax(1) > conf_thres  # candidates
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: amax(): Expected reduction dim 1 to have non-zero size.
`

My models is onnx format with :

```
model = YOLO(best + ".pt")
model.export(format="onnx", dynamic=True, imgsz=352)

```
 
![image](https://github.com/ultralytics/ultralytics/assets/3437490/1b4ed85a-ee0f-47ba-ac8a-29159a74b1b1)

and my config.pbtxt :

`name: "P0031_ensemble"
platform: "ensemble"
max_batch_size: 0
input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [ 1,3,352,352  ]
  }
]
output [
    {
      name: "num_detections"
      data_type: TYPE_INT32
      dims: [1 ]
    },
    {
      name: "detection_boxes"
      data_type: TYPE_FP32
      dims: [1000,4 ]
    },
    {
      name: "detection_scores"
      data_type: TYPE_FP32 
      dims: [1000]
    },
    {
      name: "detection_classes"
      data_type: TYPE_INT32
      dims: [1000 ]
    }
]
ensemble_scheduling {
  step [
    {
      model_name: "P0031_onnx"
      model_version: -1
      input_map {
        key: "images"
        value: "images"
      }
      output_map {
        key: "output0"
        value: "output0"
      }
    },
    {
      model_name: "postprocess"
      model_version: -1
      input_map {
        key: "INPUT_0"
        value: "output0"
      }
      output_map {
        key: "num_detections"
        value: "num_detections"
      },
      output_map {
        key: "detection_boxes"
        value: "detection_boxes"
      },
      output_map {
        key: "detection_scores"
        value: "detection_scores"
      },
      output_map {
        key: "detection_classes"
        value: "detection_classes"
      }
    }
  ]
}`

**Comment by stupidme123** [comment]
> 嘿，你好
> 
> 感谢您报告此问题并提供有关您的环境的详细信息。在使用 TensorRT 模型运行推理时，您似乎遇到了维度不匹配错误。
> 
> 为了帮助我们调查和解决此问题，您能否提供一个最小的可重复示例？这将使我们能够在我们这边重现错误。您可以[在此处](https://docs.ultralytics.com/help/minimum_reproducible_example)找到创建最小可重现示例的指南。这一步对于我们了解问题的背景和细节至关重要。
> 
> 此外，请确保您使用的是 和 的最新版本。您可以使用以下命令更新它们：`torch``ultralytics`
> 
> ```shell
> pip install --upgrade torch ultralytics
> ```
> 
> 从错误消息来看，TensorRT 模型的输入维度似乎与预期维度不匹配。具体而言，模型需要 范围内的维度，但您提供的是 。要解决此问题，您可以尝试在导出和推理阶段将参数设置为 224。`[1, 3, 224, 224]``[1, 3, 640, 640]``imgsz`
> 
> 下面是如何导出具有正确图像大小的模型，然后运行推理的示例：
> 
> ```python
> from ultralytics import YOLO
> 
> # Load the YOLOv8 model
> model = YOLO("yolov8n.pt")
> 
> # Export the model to TensorRT format with the correct image size
> model.export(format="engine", imgsz=224)  # creates 'yolov8n.engine'
> 
> # Load the exported TensorRT model
> tensorrt_model = YOLO("yolov8n.engine")
> 
> # Run inference with the correct image size
> results = tensorrt_model("https://ultralytics.com/images/bus.jpg", imgsz=224)
> ```
> 
> 如果您继续遇到问题，请分享最小可重现的示例，我们将很乐意为您提供进一步的帮助。

I tried changing the imgsz parameter, but it still didn't work. Maybe it's a problem with my model and images. I tried to retrain

**Comment by glenn-jocher** [comment]
Hi @stupidme123,

Thank you for providing additional context and details about your setup. It appears that you're encountering a dimension mismatch error when running inference with a TensorRT model on Triton Server.

To help us investigate and resolve this issue, please ensure that you are using the latest versions of both `torch` and `ultralytics`. You can update them using the following commands:
```bash
pip install --upgrade torch ultralytics
```

From the error message, it seems that the input dimensions for the TensorRT model are not matching the expected dimensions. Specifically, the model expects dimensions within the range of `[1, 3, 224, 224]`, but you are providing `[1, 3, 640, 640]`. To resolve this, you can try setting the `imgsz` parameter to 224 during both the export and inference stages.

Here’s an example of how to export the model with the correct image size and then run inference:
```python
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO("yolov8n.pt")

# Export the model to TensorRT format with the correct image size
model.export(format="engine", imgsz=224)  # creates 'yolov8n.engine'

# Load the exported TensorRT model
tensorrt_model = YOLO("yolov8n.engine")

# Run inference with the correct image size
results = tensorrt_model("https://ultralytics.com/images/bus.jpg", imgsz=224)
```

If you continue to experience issues, please share the minimal reproducible example, and we will be happy to assist further.
