### ISSUE TITLE
TensorRT  Python Examples

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#13630]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

https://github.com/ultralytics/ultralytics/tree/main/examples

TensorRT  Python Examples:
[Tasks]
[Detect]
[Segment]
[Classify]
[Pose]
[OBB]

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@monkeycc hello,

Thank you for reaching out and for your interest in TensorRT examples for YOLOv8! It looks like you're looking for Python examples for various tasks such as detection, segmentation, classification, pose estimation, and oriented bounding boxes (OBB) using TensorRT.

To get you started, here's a basic example of how to export a YOLOv8 model to TensorRT format and run inference using Python:

```python
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO("yolov8n.pt")

# Export the model to TensorRT format
model.export(format="engine")  # creates 'yolov8n.engine'

# Load the exported TensorRT model
tensorrt_model = YOLO("yolov8n.engine")

# Run inference
results = tensorrt_model("https://ultralytics.com/images/bus.jpg")
```

For more detailed instructions and examples, you can refer to our [TensorRT integration guide](https://docs.ultralytics.com/integrations/tensorrt/).

If you encounter any issues or have specific questions, please provide a minimum reproducible code example so we can better assist you. You can find more information on how to create one [here](https://docs.ultralytics.com/help/minimum_reproducible_example). Additionally, ensure you are using the latest versions of `torch` and `ultralytics` packages.

Feel free to reach out if you need further assistance. We're here to help!
