### ISSUE TITLE
Tracker always outputs new IDs when run in online mode

### ISSUE THREAD

**Issue by jerafs** [ultralytics/ultralytics#1363]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

The tracker seems to always output new IDs for each detected object in every
frame when the frames are iterated over a loop. However, it works as expected
when the source in a video file.

### Environment

- YOLO: Ultralytics YOLOv8.0.52
- Python: Python 3.9.15
- PyTorch: 1.13.1+cu117
- CUDA:0: Nvidia GeForce 3070 Mobile 8192 MiB
- Nvidia Driver Version: 525.85.0
- OS: Ubuntu 22.04.2 LTS

### Minimal Reproducible Example

Replace the `video.avi` in the snippet below with a small video and run.

```python
import glob

import cv2
from ultralytics import YOLO
from ultralytics.tracker import register_tracker

# Extract frames from a video file
cap = cv2.VideoCapture("./video.avi")
images_path = "./frames"
frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
i = 1
while (cap.isOpened()):
    ret, frame = cap.read()
    if ret == False:
        break
    fnum = str(i).zfill(4)
    cv2.imwrite(f"./frames/frame_{fnum}.jpeg", frame)
    cv2.imwrite(f"{images_path}/frame_{fnum}.jpeg", frame)
    if i % 100 == 0:
        print(f"{i}/{frame_count} processed")
    i += 1

cap.release()
cv2.destroyAllWindows()
image_files = sorted(glob.glob(f"{images_path}/*.jpeg"))

# Create YOLO model and register tracker
model = YOLO("yolov8l.pt")
kwargs = dict(show=True, conf=0.1, mode="track")
register_tracker(model)

yolo_results = dict()
for i in range(1, len(image_files) + 1, 1):
    fnum = str(i).zfill(4)
    img = cv2.imread(f"{images_path}/frame_{fnum}.jpeg")
    results = model.predict(source=img, stream=False, **kwargs)
    yolo_results[fnum] = results

print("DONE!")
for results in yolo_results.values():
    for result in results:
        ids = [int(box.id) for box in result.boxes]
        print(ids)
```

### Additional

For my use case, I need to be able to run the tracker in online mode (not all frames of the video are available at once - I receive them one by one over a network). From looking at how the tracker is used [here](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/engine/model.py#L223), I thought just registering a tracker with `register_tracker` on the YOLO model would work as expected. But, I seem to get new tracking IDs every time. Am I missing something here or is it a bug?

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jerafs most of the tracking work was implemented by @Laughing-q and @AyushExel, so I can't say for sure that your usage is correct, but please take a look at https://docs.ultralytics.com/modes/track/ for best practices. Tracking on a video should not need all the additional steps you have above, simply something like this as shown in the docs:

```python
from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.pt")  # load an official detection model

# Track with the model
results = model.track(source="https://youtu.be/Zgi9g1ksQHc", show=True) 
```

**Comment by jerafs** [comment]
@glenn-jocher Thanks for the response. I understand that providing the video source directly is recommended. The problem is that, for my use case, I cannot provide the entire video source in a single `model.track(...)` call. I receive the frames of the video one by one from another application. It seems like it should be possible by just registering a tracker on the model outside the loop and making multiple `model.predict(...)` calls inside the loop with the individual frames as the source, but the tracker seems simply output new tracking IDs for each detected object in every new frame.

**Comment by Laughing-q** [comment]
@jerafs hi, the tracker will be registered everytime you run `model.track` or `model.predict` in your case. You might need a global tracker in your case which we do not support for now.

Modify the following code [https://github.com/ultralytics/ultralytics/blob/9e58c32c15835e54e57f7b8c925367a64cb94951/ultralytics/tracker/track.py#L20-L24](https://github.com/ultralytics/ultralytics/blob/9e58c32c15835e54e57f7b8c925367a64cb94951/ultralytics/tracker/track.py#L20-L24)
to:
```python
    if not hasattr(predictor, "trackers"):
        trackers = []
        for _ in range(predictor.dataset.bs):
            tracker = TRACKER_MAP[cfg.tracker_type](args=cfg, frame_rate=30)
            trackers.append(tracker)
        predictor.trackers = trackers
```
should help you. :)

**Comment by jerafs** [comment]
@Laughing-q Yes, that did the trick. Thanks a lot! :)

**Comment by uzumakinaruto19** [comment]
How long does it persist, can he have a timer for that like 10 mins or an hour?
or how to do that!!

**Comment by Laughing-q** [comment]
@uzumakinaruto19 well as long as `persist` is still True, I think you can make it last 10 mins by manually setting `persist=False`, something like this:
```
if min < 10:
    model.track(frame, persist=True)
else:
    model.track(frame, persist=False)
```
the logic here is that trackers will be recreated if `persist=False`.

**Comment by uzumakinaruto19** [comment]
but it won't be possible with a live stream, right? I'm getting the data from an RTSP stream and I would like to reset the unique ID for like every hour .

> @uzumakinaruto19 well as long as `persist` is still True, I think you can make it last 10 mins by manually setting `persist=False`, something like this:
> 
> ```
> if min < 10:
>     model.track(frame, persist=True)
> else:
>     model.track(frame, persist=False)
> ```
> 
> the logic here is that trackers will be recreated if `persist=False`.

**Comment by glenn-jocher** [comment]
@uzumakinaruto19, if you're working with a live stream from an RTSP source and you want to reset the unique IDs every hour, you can achieve this by setting `persist=False` after the desired time has elapsed. The code snippet you provided could work for this purpose. By setting `persist=False`, the trackers will be recreated, essentially resetting the tracking IDs. So, in your case, you could modify the logic to check if an hour has passed, and if so, set `persist=False` when calling `model.track(frame, persist=False)`. This will reset the tracking IDs for your live stream every hour.

**Comment by uzumakinaruto19** [comment]
This my code for detection and tracking

```import cv2
import numpy as np
from ultralytics import YOLO
import supervision as sv
from typing import Dict
from counter import LineZone
import time



VIDEO_FPS = 24
frame_index = 0

# Initialize YOLO model and object tracker outside the main loop
model = YOLO("yolov8n.pt")



# Timer variables
reset_interval = 30 * 60  # 30 minutes
start_time = time.time()

def reset_variables():
    global frame_index, line_counter_values, in_zone_state, in_zone_time, start_time
    frame_index = 0


def main(input_data, frame):
    global model, frame_index

    input_data = {
        'frame_index': frame_index,
        'time_stamp': 0,  # You can replace 0 with an appropriate timestamp
        'demo_run': False
    }


    if time.time() - start_time >= reset_interval:
        result = model.track(frame, classes=0, imgsz=480, show=False, stream=False, agnostic_nms=True, tracker="bytetrack.yaml", persist=False)
        reset_variables()
        start_time = time.time()
    else:
        result = model.track(frame, classes=0, imgsz=480, show=False, stream=False, agnostic_nms=True, tracker="bytetrack.yaml", persist=True)

    result = result[0]
    frame = result.orig_img
    detections = sv.Detections.from_yolov8(result)

    if result.boxes.id is not None:
        detections.tracker_id = result.boxes.id.cpu().numpy().astype(int)
    else:
        detections.tracker_id = np.array([])
        detections.conf = np.array([])
        detections.xyxy = np.array([])

    labels = [str(id) for id in detections.tracker_id]

    try:
        in_zone = zone.trigger(detections=detections)
        detections_in_zone = detections[in_zone]
        curr_in_zone = set(detections_in_zone.tracker_id)
        prev_in_zone = set(in_zone_state.keys())

        new = curr_in_zone.difference(prev_in_zone)
        old = prev_in_zone.difference(curr_in_zone)

        for tracker_id in new:
            in_zone_state[tracker_id] = frame_index
            in_zone_time[tracker_id] = 0

        for tracker_id in old:
            in_zone_frame_count = frame_index - in_zone_state[tracker_id]
            in_zone_time[tracker_id] = in_zone_frame_count * 1 / VIDEO_FPS
            del in_zone_state[tracker_id]

    except Exception as e:
        print(f"Error occurred: {str(e)}")

    total_wait_time = sum(in_zone_time.values())
    num_objects = len(in_zone_time)



    new_ids = detections.tracker_id.astype(int).tolist()
    new_box = detections.xyxy.astype(int).tolist()

    i = 0
    while i < len(new_box):
        new_box[i][2] = new_box[i][2] - new_box[i][0]
        new_box[i][3] = new_box[i][3] - new_box[i][1]
        i = i + 1

    total_people = len(new_ids)
    output = {
        'frame_index': frame_index,
        'detections': new_box,
        'demo_run': input_data['demo_run'],
        'ids': new_ids,
        'labels': labels,
    }
    frame_index += 1
    print(output)

    # Check if reset interval has passed
    if time.time() - start_time >= reset_interval:
        reset_variables()
        start_time = time.time()

    return output
```

is this how you are suggesting but its not resetting !! i tried with every 2 minutes?
@glenn-jocher 


> @uzumakinaruto19, if you're working with a live stream from an RTSP source and you want to reset the unique IDs every hour, you can achieve this by setting `persist=False` after the desired time has elapsed. The code snippet you provided could work for this purpose. By setting `persist=False`, the trackers will be recreated, essentially resetting the tracking IDs. So, in your case, you could modify the logic to check if an hour has passed, and if so, set `persist=False` when calling `model.track(frame, persist=False)`. This will reset the tracking IDs for your live stream every hour.
