### ISSUE TITLE
Tensors misshaped when loading yolo8X.engine files

### ISSUE THREAD

**Issue by MrYanMYN** [ultralytics/ultralytics#13633]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I am trying to load the TensorRT version of the yolo8s model using ultralytics on my Jetson Orin AGX.

Now I followed the instructions in the official Ultralytics documentation: https://docs.ultralytics.com/integrations/tensorrt/#installation

But I got an error when loading up the model:
```
Traceback (most recent call last):
  File "/home/argu/Documents/DetectionAndTrackingService/tracking_and_detection.py", line 383, in <module>
    detect_objects_video_file(video_path, output_path, opt)
  File "/home/argu/Documents/DetectionAndTrackingService/tracking_and_detection.py", line 316, in detect_objects_video_file
    plotted_img, _, _, _, _ = detector_and_tracker.update(frame)
  File "/home/argu/Documents/DetectionAndTrackingService/tracking_and_detection.py", line 136, in update
    result = self.model.track(frame, persist=True, show=False, conf=self.conf, iou=self.iou)
  File "/home/argu/Documents/DetectionAndTrackingService/ultralytics_master/ultralytics/engine/model.py", line 492, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "/home/argu/Documents/DetectionAndTrackingService/ultralytics_master/ultralytics/engine/model.py", line 452, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/argu/Documents/DetectionAndTrackingService/ultralytics_master/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/argu/Documents/DetectionAndTrackingService/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/argu/Documents/DetectionAndTrackingService/ultralytics_master/ultralytics/engine/predictor.py", line 255, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "/home/argu/Documents/DetectionAndTrackingService/ultralytics_master/ultralytics/models/yolo/detect/predict.py", line 25, in postprocess
    preds_for_all_conf = preds.copy()
AttributeError: 'Tensor' object has no attribute 'copy'. Did you mean: 'copy_'?
```

I checked in debug and I saw the shape of preds in DetectionPredictor.postprocess is:
Tensor(1, 84, 8400)

Instead of : 
List (2)
In normal .pt predictions.

Normal predict4ions runs fine but for some reason this happens with TRT models

### Environment

Jetson Orin AGX. Jetpack 6,0

### Minimal Reproducible Example

```
self.model = YOLO(opt.detector_weights_path)

        # Export the model
        self.model.export(format="engine")

        # Load the exported TensorRT model
        tensorrt_model_path = opt.detector_weights_path[:-3] + ".engine"
        self.model = YOLO(tensorrt_model_path)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @MrYanMYN,

Thank you for reporting this issue and providing detailed information. It looks like you're encountering an error when loading and using the TensorRT version of the YOLOv8 model on your Jetson Orin AGX.

To help us investigate this further, could you please confirm the following:

1. **Reproducible Code Example**: The provided code snippet is helpful, but we need a minimal reproducible example that we can run to replicate the issue. Please refer to our [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example) guide for more details on how to structure this.

2. **Package Versions**: Ensure you are using the latest versions of `torch` and `ultralytics`. You can update your packages using:
   ```bash
   pip install --upgrade torch ultralytics
   ```

3. **Model Export and Inference**: Verify that the model export and inference steps are correctly implemented. Here is a concise example for exporting and loading a TensorRT model:
   ```python
   from ultralytics import YOLO

   # Load the YOLOv8 model
   model = YOLO("yolov8n.pt")

   # Export the model to TensorRT format
   model.export(format="engine")  # creates 'yolov8n.engine'

   # Load the exported TensorRT model
   tensorrt_model = YOLO("yolov8n.engine")

   # Run inference
   results = tensorrt_model("https://ultralytics.com/images/bus.jpg")
   ```

If the issue persists after ensuring the above steps, please provide the updated code and any additional error messages you encounter. This will help us diagnose and resolve the problem more effectively.

Looking forward to your response!

**Comment by MrYanMYN** [comment]
So the minimal amount of code for reproduction of the issue is just the normal snippet your provided for export and inference.

For some reason even when running it purely alone I get the same error

**Comment by glenn-jocher** [comment]
Hello @MrYanMYN,

Thank you for your prompt response and for confirming that the issue persists with the minimal code snippet provided.

To help us investigate further, could you please ensure the following:

1. **Minimum Reproducible Example**: Please provide a minimal reproducible example that we can run to replicate the issue. This is crucial for us to diagnose the problem effectively. You can refer to our [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example) guide for more details.

2. **Package Versions**: Make sure you are using the latest versions of `torch` and `ultralytics`. You can update your packages using:
   ```bash
   pip install --upgrade torch ultralytics
   ```

3. **Model Export and Inference**: Verify that the model export and inference steps are correctly implemented. Here is a concise example for exporting and loading a TensorRT model:
   ```python
   from ultralytics import YOLO

   # Load the YOLOv8 model
   model = YOLO("yolov8n.pt")

   # Export the model to TensorRT format
   model.export(format="engine")  # creates 'yolov8n.engine'

   # Load the exported TensorRT model
   tensorrt_model = YOLO("yolov8n.engine")

   # Run inference
   results = tensorrt_model("https://ultralytics.com/images/bus.jpg")
   ```

If the issue persists after ensuring the above steps, please provide the updated code and any additional error messages you encounter. This will help us diagnose and resolve the problem more effectively.

Looking forward to your response! 😊

**Comment by MrYanMYN** [comment]
Hey , as I said. I am running the most up to date version of torch and ultralytics while using the provided minimum viable code on a Jetson Orin AGX.

**Comment by glenn-jocher** [comment]
Hello @MrYanMYN,

Thank you for confirming that you're using the latest versions of `torch` and `ultralytics` and for providing the minimal code example. Given that the issue persists, let's delve a bit deeper.

It appears that the error might be related to the TensorRT model handling on the Jetson Orin AGX. Here are a few steps to help troubleshoot and potentially resolve the issue:

1. **TensorRT Version**: Ensure that the TensorRT version installed on your Jetson Orin AGX is compatible with the versions of `torch` and `ultralytics` you are using. Sometimes, mismatched versions can cause unexpected behavior.

2. **Model Export Verification**: Double-check the export process to ensure the model is correctly exported to TensorRT format. You can try running the export and inference on a different machine with an NVIDIA GPU to see if the issue is specific to the Jetson Orin AGX.

3. **Debugging Tensor Shapes**: The error message indicates a tensor shape mismatch. You can add some debug prints to check the shapes of the tensors at different stages of the inference process. This might help pinpoint where the shape mismatch occurs.

Here's an example of how you might add debug prints:
```python
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO("yolov8n.pt")

# Export the model to TensorRT format
model.export(format="engine")  # creates 'yolov8n.engine'

# Load the exported TensorRT model
tensorrt_model = YOLO("yolov8n.engine")

# Run inference with debug prints
image = "https://ultralytics.com/images/bus.jpg"
results = tensorrt_model(image)
print("Inference results:", results)
```

4. **Ultralytics Documentation**: For additional guidance, you can refer to the [Ultralytics TensorRT Integration Guide](https://docs.ultralytics.com/integrations/tensorrt/).

If the issue persists, please provide any additional error messages or observations you encounter. This will help us assist you more effectively.

Thank you for your patience and cooperation! 😊
