### ISSUE TITLE
long loading time for model

### ISSUE THREAD

**Issue by shrinand1996** [ultralytics/ultralytics#13632]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I am using jetson tx2 for deployment. 
it takes a lot of time (30 mins) to load the model and do its first inference. after that it works fine and i get the result in 200ms. but the startup time is  causing a lot of issue. 
What could be causing this?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi there,

Thank you for reaching out and providing details about the issue you're facing with the long loading time on your Jetson TX2.

To assist you better, could you please provide a minimal reproducible code example? This will help us understand the context and reproduce the issue on our end. You can refer to our guide on creating a minimal reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of `torch` and `ultralytics`. You can upgrade your packages using the following commands:

```bash
pip install --upgrade torch
pip install --upgrade ultralytics
```

Once you've updated the packages, please try running your code again to see if the issue persists.

Looking forward to your response with the reproducible example so we can investigate further. 😊
