### ISSUE TITLE
Export YOLOv8 to TFLite with Bounding Box!

### ISSUE THREAD

**Issue by DroneAIRecognition** [ultralytics/ultralytics#13631]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a trained model in YOLOv8n format. I need to export it to TFLite while preserving the bounding box information in the model. How can I do this?

**Comment by glenn-jocher** [comment]
@DroneAIRecognition hello!

Thank you for reaching out with your question about exporting your YOLOv8n model to TFLite while preserving bounding box information. Let's get you sorted out!

To export your YOLOv8n model to TFLite, you can follow these steps:

1. **Ensure you have the latest versions of `torch` and `ultralytics` installed**:
   ```bash
   pip install --upgrade torch ultralytics
   ```

2. **Export your model to TFLite format**:
   You can do this using either Python or the CLI. Here are both methods:

   **Python**:
   ```python
   from ultralytics import YOLO

   # Load your trained YOLOv8 model
   model = YOLO("yolov8n.pt")

   # Export the model to TFLite format
   model.export(format="tflite")  # This will create 'yolov8n_float32.tflite'
   ```

   **CLI**:
   ```bash
   yolo export model=yolov8n.pt format=tflite  # This will create 'yolov8n_float32.tflite'
   ```

3. **Verify the exported TFLite model**:
   You can load the exported TFLite model and run inference to ensure that the bounding box information is preserved:
   ```python
   from ultralytics import YOLO

   # Load the exported TFLite model
   tflite_model = YOLO("yolov8n_float32.tflite")

   # Run inference
   results = tflite_model("https://ultralytics.com/images/bus.jpg")

   # Display results
   results.show()
   ```

For more detailed instructions, you can refer to our [TFLite export documentation](https://docs.ultralytics.com/integrations/tflite/).

If you encounter any issues during the export process, please ensure you provide a minimum reproducible example so we can investigate further. You can find more information on how to create one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions. Happy coding! 😊

**Comment by DroneAIRecognition** [comment]
> @DroneAIRecognition привет!
> 
> Благодарим вас за обращение с вопросом об экспорте вашей модели YOLOv8n в TFLite с сохранением информации о ограничивающей рамке. Давайте разберемся с вами!
> 
> Чтобы экспортировать вашу модель YOLOv8n в TFLite, вы можете выполнить следующие действия:
> 
> 1. **Убедитесь, что у вас установлены `torch` последние версии `ultralytics` и**:
>    ```shell
>    установка pip -- обновление torch ultralytics
>    ```
> 2. **Экспортируйте вашу модель в формат TFLite**: вы можете сделать это с помощью Python или командной строки. Вот оба метода.:
>    **Python**:
>    ```python
>    YOLO = модель # Загрузите обученную модель YOLOv8
>    
>    YOLO
>    импортируйте ultralytics из("yolov8n.pt ")
>    
>    # Экспортируйте модель в формат TFLite
>    model.export(format="tflite") # Это создаст 'yolov8n_float32.tflite'
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    **CLI**:
>    ```shell
>    yolo export model =yolov8n.pt format = tflite # Это создаст 'yolov8n_float32.tflite'
>    ```
> 3. **Проверьте экспортированную модель TFLite**: Вы можете загрузить экспортированную модель TFLite и выполнить вывод, чтобы убедиться, что информация о ограничивающей рамке сохранена:
>    ```python
>    YOLO = tflite_model # Загрузить экспортированную модель TFLite
>    
>    YOLO
>    импортирует ultralytics из("yolov8n_float32.tflite")
>    
>    # Выполнить вывод
>    результатов = tflite_model("https://ultralytics.com/images/bus.jpg")
>    
>    # Отобразить результаты
>    results.показать()
>    ```
> 
> Для получения более подробных инструкций вы можете обратиться к нашей [документации по экспорту TFLite](https://docs.ultralytics.com/integrations/tflite/).
> 
> Если у вас возникнут какие-либо проблемы в процессе экспорта, пожалуйста, убедитесь, что вы предоставили минимально воспроизводимый пример, чтобы мы могли продолжить расследование. Дополнительную информацию о том, как его создать, вы можете найти [здесь](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> Не стесняйтесь обращаться, если у вас возникнут еще какие-либо вопросы. Приятного кодирования! 😊

Greetings. What you described is the standard procedure for exporting from a .PT model to .TFLITE. I have no issues with that. The problem is different. During the export to the final .TFLITE model, it is necessary to add metadata. That is, similar to how it is done when exporting from YOLOv5 to TFLITE.

**Comment by carltoro** [comment]
Hi, same problem as mentioned above here, trying to do inference with the tflite yolov8 model is not straightforward, there are decoding steps, does someone found any documentation for this?.

**Comment by glenn-jocher** [comment]
Hello @carltoro,

Thank you for your question!

To perform inference with a YOLOv8 TFLite model, you indeed need to handle the decoding steps manually, as TFLite models do not include the post-processing steps (like NMS) by default. Here's a concise guide to help you with this process:

1. **Export your YOLOv8 model to TFLite**:
   ```python
   from ultralytics import YOLO

   # Load your trained YOLOv8 model
   model = YOLO("yolov8n.pt")

   # Export the model to TFLite format
   model.export(format="tflite")  # This will create 'yolov8n_float32.tflite'
   ```

2. **Run inference with the TFLite model**:
   ```python
   import tensorflow as tf
   import numpy as np

   # Load the TFLite model
   interpreter = tf.lite.Interpreter(model_path="yolov8n_float32.tflite")
   interpreter.allocate_tensors()

   # Get input and output tensors
   input_details = interpreter.get_input_details()
   output_details = interpreter.get_output_details()

   # Prepare your input data
   input_data = np.expand_dims(your_image, axis=0).astype(np.float32)

   # Run inference
   interpreter.set_tensor(input_details[0]['index'], input_data)
   interpreter.invoke()

   # Get the output
   output_data = interpreter.get_tensor(output_details[0]['index'])
   ```

3. **Post-process the output**:
   You will need to decode the output tensor to get the bounding boxes, class scores, and apply Non-Maximum Suppression (NMS). This step is crucial to filter out overlapping boxes and get the final detections.

For detailed steps on post-processing, you can refer to the [TensorFlow Lite Object Detection](https://www.tensorflow.org/lite/examples/object_detection/overview) documentation, which provides examples of how to handle the output tensors and apply NMS.

If you encounter any specific issues or need further assistance, please provide a minimum reproducible example so we can help you more effectively. You can find more information on how to create one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Happy coding! 😊
