### ISSUE TITLE
I want to convert the segmentation result from YOLOv8 into a mask, where regions with targets are true and areas without targets are false.

### ISSUE THREAD

**Issue by Zzz777777** [ultralytics/ultralytics#13658]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to convert the segmentation result from YOLOv8 into a mask, where regions with targets are true and areas without targets are false.I need to combine the segmentation results of multiple objects from an image into a single mask, which is sized equally to the original image.Does YOLOv8 provide a function for this purpose?
```
seg_model = YOLO("yolov8n-seg.pt")
results = seg_model.predict(source=image_src, conf=0.3)
if results[0].masks is not None:
    merge_mask = np.zeros_like(image_src[:, :, 0], dtype=np.uint8)
    for mask_data in results[0].masks.data:
        binary_mask_cpu = mask_data.cpu().numpy()
        binary_mask = (binary_mask_cpu > 0).astype(np.uint8) * 255
        merge_mask = cv2.bitwise_or(merge_mask, binary_mask)
```
Here is the code I have written so far, yet the size of binary_mask_cpu remains at the model's output dimensions (640, 360), which does not match the original image size (1920, 1080).

**Comment by glenn-jocher** [comment]
@Zzz777777 hello,

Thank you for reaching out with your question! It looks like you're on the right track with your code. To address the issue of mismatched dimensions between the model's output and the original image, you can resize the binary masks to match the original image size before combining them. Here's an updated version of your code that includes this resizing step:

```python
import cv2
import numpy as np
from ultralytics import YOLO

# Load the segmentation model
seg_model = YOLO("yolov8n-seg.pt")

# Run inference
results = seg_model.predict(source=image_src, conf=0.3)

if results[0].masks is not None:
    # Initialize an empty mask with the same size as the original image
    merge_mask = np.zeros_like(image_src[:, :, 0], dtype=np.uint8)
    
    for mask_data in results[0].masks.data:
        # Convert mask to numpy array
        binary_mask_cpu = mask_data.cpu().numpy()
        
        # Resize the mask to match the original image size
        binary_mask_resized = cv2.resize(binary_mask_cpu, (image_src.shape[1], image_src.shape[0]), interpolation=cv2.INTER_NEAREST)
        
        # Convert to binary mask
        binary_mask = (binary_mask_resized > 0).astype(np.uint8) * 255
        
        # Combine the masks
        merge_mask = cv2.bitwise_or(merge_mask, binary_mask)

# Now merge_mask contains the combined mask of all detected objects
```

This code ensures that each mask is resized to the original image dimensions before combining them. The `cv2.resize` function with `interpolation=cv2.INTER_NEAREST` is used to maintain the binary nature of the mask.

If you encounter any further issues or have additional questions, please ensure you are using the latest versions of `torch` and `ultralytics`. You can update them using:
```bash
pip install --upgrade torch ultralytics
```

For more detailed guidance on isolating segmentation objects, you can refer to our [Isolating Segmentation Objects Guide](https://docs.ultralytics.com/guides/isolating-segmentation-objects/).

Feel free to reach out if you need further assistance. Happy coding! 😊

**Comment by Zzz777777** [comment]
> @Zzz777777 hello,
> 
> Thank you for reaching out with your question! It looks like you're on the right track with your code. To address the issue of mismatched dimensions between the model's output and the original image, you can resize the binary masks to match the original image size before combining them. Here's an updated version of your code that includes this resizing step:
> 
> ```python
> import cv2
> import numpy as np
> from ultralytics import YOLO
> 
> # Load the segmentation model
> seg_model = YOLO("yolov8n-seg.pt")
> 
> # Run inference
> results = seg_model.predict(source=image_src, conf=0.3)
> 
> if results[0].masks is not None:
>     # Initialize an empty mask with the same size as the original image
>     merge_mask = np.zeros_like(image_src[:, :, 0], dtype=np.uint8)
>     
>     for mask_data in results[0].masks.data:
>         # Convert mask to numpy array
>         binary_mask_cpu = mask_data.cpu().numpy()
>         
>         # Resize the mask to match the original image size
>         binary_mask_resized = cv2.resize(binary_mask_cpu, (image_src.shape[1], image_src.shape[0]), interpolation=cv2.INTER_NEAREST)
>         
>         # Convert to binary mask
>         binary_mask = (binary_mask_resized > 0).astype(np.uint8) * 255
>         
>         # Combine the masks
>         merge_mask = cv2.bitwise_or(merge_mask, binary_mask)
> 
> # Now merge_mask contains the combined mask of all detected objects
> ```
> 
> This code ensures that each mask is resized to the original image dimensions before combining them. The function with is used to maintain the binary nature of the mask.`cv2.resize``interpolation=cv2.INTER_NEAREST`
> 
> If you encounter any further issues or have additional questions, please ensure you are using the latest versions of and . You can update them using:`torch``ultralytics`
> 
> ```shell
> pip install --upgrade torch ultralytics
> ```
> 
> For more detailed guidance on isolating segmentation objects, you can refer to our [Isolating Segmentation Objects Guide](https://docs.ultralytics.com/guides/isolating-segmentation-objects/).
> 
> Feel free to reach out if you need further assistance. Happy coding! 😊

This piece of code is highly effective!Thank you very much for your response! I apologize for troubling you again. This section of code for merging masks seems to be more time-consuming compared to the detection part. Are there any means or strategies to optimize it? Many thanks once again.😊

**Comment by glenn-jocher** [comment]
Hello @Zzz777777,

Thank you for your kind words! 😊 I'm glad to hear that the provided solution was helpful. Regarding your concern about the time-consuming nature of merging masks, there are a few strategies you can employ to optimize this process:

1. **Batch Processing**: Instead of processing each mask individually, you can try to batch process them. This can reduce the overhead associated with multiple function calls.

2. **GPU Acceleration**: Utilize GPU acceleration for operations like resizing and bitwise operations. Libraries such as `cupy` can be used as a drop-in replacement for NumPy to leverage GPU capabilities.

3. **Efficient Data Structures**: Ensure that the data structures you are using are optimized for the operations you are performing. For example, using boolean arrays instead of uint8 arrays can save memory and potentially speed up operations.

Here's an example of how you might implement some of these optimizations:

```python
import cv2
import numpy as np
from ultralytics import YOLO

# Load the segmentation model
seg_model = YOLO("yolov8n-seg.pt")

# Run inference
results = seg_model.predict(source=image_src, conf=0.3)

if results[0].masks is not None:
    # Initialize an empty mask with the same size as the original image
    merge_mask = np.zeros((image_src.shape[0], image_src.shape[1]), dtype=np.bool)
    
    for mask_data in results[0].masks.data:
        # Convert mask to numpy array
        binary_mask_cpu = mask_data.cpu().numpy()
        
        # Resize the mask to match the original image size
        binary_mask_resized = cv2.resize(binary_mask_cpu, (image_src.shape[1], image_src.shape[0]), interpolation=cv2.INTER_NEAREST)
        
        # Combine the masks using logical OR
        merge_mask = np.logical_or(merge_mask, binary_mask_resized > 0)

    # Convert the boolean mask to uint8
    merge_mask = (merge_mask.astype(np.uint8)) * 255

# Now merge_mask contains the combined mask of all detected objects
```

If you have access to a GPU and want to leverage it for these operations, you might consider using `cupy`:

```python
import cupy as cp
import cv2
from ultralytics import YOLO

# Load the segmentation model
seg_model = YOLO("yolov8n-seg.pt")

# Run inference
results = seg_model.predict(source=image_src, conf=0.3)

if results[0].masks is not None:
    # Initialize an empty mask with the same size as the original image
    merge_mask = cp.zeros((image_src.shape[0], image_src.shape[1]), dtype=cp.bool)
    
    for mask_data in results[0].masks.data:
        # Convert mask to cupy array
        binary_mask_gpu = cp.asarray(mask_data.cpu().numpy())
        
        # Resize the mask to match the original image size
        binary_mask_resized = cv2.resize(binary_mask_gpu.get(), (image_src.shape[1], image_src.shape[0]), interpolation=cv2.INTER_NEAREST)
        
        # Combine the masks using logical OR
        merge_mask = cp.logical_or(merge_mask, binary_mask_resized > 0)

    # Convert the boolean mask to uint8
    merge_mask = (merge_mask.astype(cp.uint8)) * 255

# Now merge_mask contains the combined mask of all detected objects
```

These optimizations should help reduce the time taken to merge the masks. If you continue to experience performance issues, consider profiling your code to identify any additional bottlenecks.

Feel free to reach out if you have any more questions or need further assistance. Happy coding! 🚀
