### ISSUE TITLE
[Classification] Top 5 Logged classes don't match the results after using fine-tuned yolov8n-cls on a custom dataset

### ISSUE THREAD

**Issue by NohaAhmad** [ultralytics/ultralytics#1365]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

I have a problem with the fine-tuned classification model yolov8n-cls
The top probability logged doesn't match the top probability obtained from the results

**which one is the correct one ? and why there's a conflict ?**
![yolo_issue](https://user-images.githubusercontent.com/45567574/224414885-adf241e5-f275-482a-a45e-917a92b18146.png)

### Environment

- YOLOv8.0.36 🚀 Python-3.8.10 torch-1.13.1+cu117 CUDA:0 (Tesla T4, 14910MiB)
- OS: ubuntu 20.04

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by NohaAhmad** [comment]
Thanks for your response.
I have already checked the Docs but couldn't find anything related to this conflict in results between the logged and the obtained from the predict function

**Comment by glenn-jocher** [comment]
@NohaAhmad cls confidence bugs were fixed in previous versions, so I'd recommend updating to the latest using `pip install -U ultralytics`

**Comment by NohaAhmad** [comment]
Ok, Thank you!!

**Comment by pderrenger** [comment]
You're welcome, @NohaAhmad! If you encounter any other issues or have further questions, feel free to ask. Good luck with your fine-tuned classification model!
