### ISSUE TITLE
Capturing Yolo8 Training Terminal Output

### ISSUE THREAD

**Issue by TaKuSaInc** [ultralytics/ultralytics#13659]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to capture the YOLOv8 training output and perform string manipulation. Instead of showing everything generated by YOLOv8, I want to print output based on the current status of the model. For example, if epoch 1 is in progress, I'll print "Epoch 1 training started" (without the progress bar). One way to achieve this is by using subprocess.Popen(), but I do not want to create another child process. I want to do this using Python only. Additionally, I want the output to print in real-time. Following is the code. I'm using for the subprocess.Popen

### Additional

```import subprocess

def run_command_in_conda(command):
    try:
        with subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, shell=True) as proc:
            for line in proc.stdout:
                print(line, end='') 
    except subprocess.CalledProcessError as e:
        print(f"Error while running command: {e}")


if __name__ == "__main__":
    command_to_run = "conda activate test && python train.py" 
    run_command_in_conda(command_to_run)```

**Comment by glenn-jocher** [comment]
Hello,

Thank you for your question! Capturing and manipulating the YOLOv8 training output in real-time without using `subprocess.Popen` is indeed possible using Python's logging capabilities. You can achieve this by redirecting the standard output and error streams to a custom handler. Below is an example of how you can do this:

```python
import sys
import threading
from ultralytics import YOLO

class StreamToLogger:
    def __init__(self, logger, log_level):
        self.logger = logger
        self.log_level = log_level
        self.linebuf = ''

    def write(self, buf):
        for line in buf.rstrip().splitlines():
            self.logger.log(self.log_level, line.rstrip())

    def flush(self):
        pass

def train_model():
    model = YOLO('yolov8n.yaml')  # or load a pretrained model with 'yolov8n.pt'
    model.train(data='coco128.yaml', epochs=100, imgsz=640)

if __name__ == "__main__":
    import logging

    logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger('YOLOv8')

    sys.stdout = StreamToLogger(logger, logging.INFO)
    sys.stderr = StreamToLogger(logger, logging.ERROR)

    train_thread = threading.Thread(target=train_model)
    train_thread.start()
    train_thread.join()
```

In this example, `StreamToLogger` redirects the output to a logger, which you can then manipulate as needed. This approach avoids creating a new child process and allows you to handle the output in real-time.

Please ensure you are using the latest versions of `torch` and `ultralytics` to avoid any compatibility issues. If you encounter any bugs, kindly provide a minimum reproducible example as outlined in our [documentation](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any further questions. Happy coding! 😊

**Comment by TaKuSaInc** [comment]
Thanks for the help. One thing I'm still not understanding is which variable I should use to get the output. Is it self.log_level? When I ran this code, it printed output, but I'm not able to understand how it is generating the output.

**Comment by glenn-jocher** [comment]
@TaKuSaInc hello,

Thank you for your follow-up question! I'm glad to hear that the code is printing the output. Let's clarify how the `StreamToLogger` class works.

In the `StreamToLogger` class, the `write` method is responsible for capturing the output. Here's a quick breakdown:

- **`write` Method**: This method is called whenever there is output to be written to `stdout` or `stderr`. It takes the buffer (`buf`) as input, splits it into lines, and logs each line using the specified logger and log level.
- **`self.log_level`**: This is not the variable that generates the output. Instead, it specifies the logging level (e.g., `logging.INFO` or `logging.ERROR`) at which the output should be logged.

Here's a simplified explanation of how the output is captured and logged:

1. **Redirection**: `sys.stdout` and `sys.stderr` are redirected to instances of `StreamToLogger`.
2. **Logging**: When the `write` method is called, it logs the output lines using the provided logger and log level.

If you want to manipulate or access the output directly, you can modify the `write` method to store the output in a variable. Here's an example:

```python
import sys
import threading
from ultralytics import YOLO

class StreamToLogger:
    def __init__(self, logger, log_level):
        self.logger = logger
        self.log_level = log_level
        self.linebuf = ''
        self.output = []  # Store output lines

    def write(self, buf):
        for line in buf.rstrip().splitlines():
            self.logger.log(self.log_level, line.rstrip())
            self.output.append(line.rstrip())  # Store each line

    def flush(self):
        pass

def train_model():
    model = YOLO('yolov8n.yaml')  # or load a pretrained model with 'yolov8n.pt'
    model.train(data='coco128.yaml', epochs=100, imgsz=640)

if __name__ == "__main__":
    import logging

    logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger('YOLOv8')

    stream_logger = StreamToLogger(logger, logging.INFO)
    sys.stdout = stream_logger
    sys.stderr = stream_logger

    train_thread = threading.Thread(target=train_model)
    train_thread.start()
    train_thread.join()

    # Access the captured output
    print("Captured Output:", stream_logger.output)
```

In this example, the `output` list in the `StreamToLogger` class stores each line of the output. You can access this list after the training completes to perform any string manipulation or further processing.

I hope this clarifies how the output is generated and captured. If you have any more questions, feel free to ask. Happy coding! 😊

**Comment by TaKuSaInc** [comment]
Thanks. @glenn-jocher. For providing such detailed answers. My problem is resolved

**Comment by glenn-jocher** [comment]
Hello @TaKuSaInc,

I'm glad to hear that your problem is resolved! 🎉 If you have any more questions or need further assistance in the future, feel free to reach out. The YOLO community and the Ultralytics team are always here to help.

Happy coding and best of luck with your projects! 😊
