### ISSUE TITLE
masks  Cropping

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#13654]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

```python
from ultralytics import YOLO

# Load a pretrained YOLOv8n-seg Segment model
model = YOLO("yolov8n-seg.pt")

# Run inference on an image
results = model("bus.jpg")  # results list

# View results
for r in results:
    print(r.masks)  # print the Masks object containing the detected instance masks
```

How to save mask images
Crop the mask image from the original image
Crop out the mask area and fill the background with black

**Comment by glenn-jocher** [comment]
@monkeycc hello!

Thank you for reaching out with your question about cropping mask images using YOLOv8. It looks like you're on the right track with your code. Below is a detailed example to help you achieve your goal of cropping the mask area from the original image and filling the background with black.

First, ensure you have the latest versions of `torch` and `ultralytics` installed:
```bash
pip install --upgrade torch ultralytics
```

Here's a complete example to isolate and save the mask images with a black background:

```python
from pathlib import Path
import cv2
import numpy as np
from ultralytics import YOLO

# Load a pretrained YOLOv8n-seg Segment model
model = YOLO("yolov8n-seg.pt")

# Run inference on an image
results = model("bus.jpg")  # results list

# Iterate over the results
for r in results:
    img = np.copy(r.orig_img)
    img_name = Path(r.path).stem  # source image base-name

    # Iterate each object contour (multiple detections)
    for ci, c in enumerate(r):
        # Get detection class name
        label = c.names[c.boxes.cls.tolist().pop()]

        # Create binary mask
        b_mask = np.zeros(img.shape[:2], np.uint8)

        # Extract contour result
        contour = c.masks.xy.pop().astype(np.int32).reshape(-1, 1, 2)

        # Draw contour onto mask
        _ = cv2.drawContours(b_mask, [contour], -1, (255, 255, 255), cv2.FILLED)

        # Create 3-channel mask
        mask3ch = cv2.cvtColor(b_mask, cv2.COLOR_GRAY2BGR)

        # Isolate object with binary mask
        isolated = cv2.bitwise_and(mask3ch, img)

        # OPTIONAL: Crop the image to the bounding box region
        x1, y1, x2, y2 = c.boxes.xyxy.cpu().numpy().squeeze().astype(np.int32)
        iso_crop = isolated[y1:y2, x1:x2]

        # Save isolated object to file
        _ = cv2.imwrite(f"{img_name}_{label}-{ci}.png", iso_crop)
```

This script will:
1. Load the YOLOv8 segmentation model.
2. Run inference on the image.
3. Iterate through the detected objects.
4. Create a binary mask for each object.
5. Isolate the object using the mask and fill the background with black.
6. Optionally crop the image to the bounding box region.
7. Save the isolated object to a file.

For more detailed information on isolating segmentation objects, you can refer to our [Isolating Segmentation Objects Guide](https://docs.ultralytics.com/guides/isolating-segmentation-objects/).

If you encounter any issues or have further questions, please provide a minimum reproducible example so we can assist you better. You can find more details on creating one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Happy coding! 😊
