### ISSUE TITLE
[Classification] [Image URL Assumed as video stream]

### ISSUE THREAD

**Issue by NohaAhmad** [ultralytics/ultralytics#1366]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

**Input:**
```
from ultralytics import YOLO
import time
import urllib.request
import cv2
import numpy as np

IMAGE_SIZE = 224

image_url = 'https://scontent.fcai19-5.fna.fbcdn.net/v/t39.30808-6/274651135_1357855464663283_2785250809914982421_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=8bfeb9&_nc_ohc=5Vnn11wi3vsAX9mVmBV&_nc_ht=scontent.fcai19-5.fna&oh=00_AfDPVr8jvb-PIO70I0JZbE0jyvSBoKKK_tgspjjBgQek-g&oe=641049D2'

#model = YOLO(model="runs/classify/train13/weights/best.pt")  # load a pretrained model (recommended for training)
model = YOLO(model="yolov8n-cls.pt") 
results = model.predict(source=image_url, conf=0.25)
print(results)`
```
**I get this response**
![image](https://user-images.githubusercontent.com/45567574/224427324-54b6fcb5-746f-4790-9218-71b524fb1471.png)

### Environment

-YOLO: YOLOv8.0.36 🚀 Python-3.8.10 torch-1.13.1+cu117 CUDA:0 (Tesla T4, 14910MiB

### Minimal Reproducible Example

```
from ultralytics import YOLO
import time
import urllib.request
import cv2
import numpy as np

IMAGE_SIZE = 224

image_url = 'https://scontent.fcai19-5.fna.fbcdn.net/v/t39.30808-6/274651135_1357855464663283_2785250809914982421_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=8bfeb9&_nc_ohc=5Vnn11wi3vsAX9mVmBV&_nc_ht=scontent.fcai19-5.fna&oh=00_AfDPVr8jvb-PIO70I0JZbE0jyvSBoKKK_tgspjjBgQek-g&oe=641049D2'

#model = YOLO(model="runs/classify/train13/weights/best.pt")  # load a pretrained model (recommended for training)
model = YOLO(model="yolov8n-cls.pt") 
results = model.predict(source=image_url, conf=0.25)
print(results)`
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by NohaAhmad** [comment]
![image](https://user-images.githubusercontent.com/45567574/224428355-bf0d67ab-9a6c-41c7-b7e5-cf540e1b6a05.png)

**Comment by glenn-jocher** [comment]
@NohaAhmad your URL is not a valid image URL. Valid image URLs end with a valid image suffix, i.e. zidane.jpg at https://ultralytics.com/images/zidane.jpg

**Comment by NohaAhmad** [comment]
You can open the url and check if it's an image or not and also when I try to download the image using any python library, it gets downloaded 
This is an image from Facebook

**Comment by NohaAhmad** [comment]
Do you check the url for the ".jpg" or any valid image extension? 
I mean there are other cases like the one I sent before, and its a valid image

**Comment by glenn-jocher** [comment]
@NohaAhmad yes, ultralytics has a list of valid image and video suffixes here. Images in training datasets or inference sources must contain one of these suffixes to be identified as an image or a video. 
https://github.com/ultralytics/ultralytics/blob/177a68b39ffe7f87c5bc17a78fa5322af9f77c0b/ultralytics/yolo/data/utils.py#L26-L27

Your URL will not be correctly identified since it does not end in a valid image suffix from the list above.
