### ISSUE TITLE
Converting Yolov8 Segmentation Labels To Be Suitable For Maskrcnn Segmentation

### ISSUE THREAD

**Issue by userwatch** [ultralytics/ultralytics#13663]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question
Hello,

`{"Ferrari04101.jpg314637":{"filename":"Ferrari04101.jpg","size":314637,"regions":[{"shape_attributes":{"name":"polygon","all_points_x":[461,482,495,668,675,1062,1058,1069,1211,1235,1208,967,695],"all_points_y":[594,366,285,302,170,180,234,322,315,519,641,611,600]},"region_attributes":{"name":"not_defined","type":"unknown","image_quality":{"good":true,"frontal":true,"good_illumination":true},"names":"Car"}}],"file_attributes":{"caption":"","public_domain":"no","image_url":""}},"Ferrari04121.jpg242498":{"filename":"Ferrari04121.jpg","size":242498,"regions":[{"shape_attributes":{"name":"polygon","all_points_x":[1106,787,750,692,583,543,577,723,719,940,1119,1153,1157,1218,1357,1357,1364,1404,1408,1547,1574,1594,1391,1119,997,943,807],"all_points_y":[624,658,594,526,539,482,319,309,193,187,180,197,265,319,319,427,472,472,414,404,563,641,651,648,645,645,655]},"region_attributes":{"name":"not_defined","type":"unknown","image_quality":{"good":true,"frontal":true,"good_illumination":true},"names":"Car"}}],"file_attributes":{"caption":"","public_domain":"no","image_url":""}}
`

This is an example of a compatible label.json file for Mask-RCNN. I use this file for segmentation in Mask-RCNN.

I have .txt files labeled for segmentation with YOLOV8. My goal is to convert labels into something suitable for Mask-RCNN. 

`0 0.6279592515625 0.6233164906249999 0.4153357015625 0.2886618859375 0.2571378171875 0.6744846109375 0.6279592515625 0.6233164906249999`

This is an example from the .txt file I used in the segmentation model in yolov8.

How can I make the .txt files used for the Yolov8 segmentation model suitable for Mask-RCNN?

I would be very happy if you could give me advice.

Thanks a lot.

**Comment by userwatch** [comment]
Hello @glenn-jocher thank you for reply.
My label folder:
![image](https://github.com/ultralytics/ultralytics/assets/69357065/0458574e-43ea-41f3-97e1-c7256b2b0ee7)
 0 0.2732418109375 0.7351379015624999 0.5583769140625 0.628994696875 0.723205971875 0.55991714375 0.7667815 0.6761694078125 0.8293026703124999 0.7182898015625 0.9950788890625001 0.686278325 0.9998153390625 0.11681075468749999 0.9401359765624999 0.093223328125 0.8766673265625 0.093223328125 0.8747726828125 0.0544726328125 0.9344522046874999 0.03593959375 0.9268737890625 0.0005584906249999999 0.782885334375 0.0005584906249999999 0.7374153203125 0.057842225000000004 0.7156275562500001 0.1943122171875 0.6985762421875 0.1909425890625 0.696681678125 0.12186524843749999 0.6493170203124999 0.1184955515625 0.5905849 0.111756296875 0.5924794640625 0.0056129140625 0.493961021875 0 0.0029592515625 0.0052609359375 0.0032632968749999997 0.9238373109375001 0.076204846875 0.8968801515625 0.1226221828125 0.75367086875 0.2732418109375 0.7351379015624999 
--------------------------
0 0.5507985796875 0.708180884375 0.566902571875 0.74693175625 0.6265820140625 0.762094990625 0.8160406421875 0.7401923609375001 0.8226715765625 0.7048113625 0.9278212703125 0.694702375 0.9979208546875 0.74861648125 0.9941317265625 0.027515509375000004 0.7999368078125 0.012352239062500001 0.7430990921875 0.044363681249999995 0.6786831203125 0.014036999999999999 0.4958555859375 0.007297745312499999 0.4930137 0.26507453124999997 0.4257559234375 0.26507453124999997 0.337657703125 0.2684440875 0.3206063875 0.23643261093749998 0.20882583906250002 0.2381174421875 0.1813543828125 0.28192266718750003 0.1643030671875 0.694702375 0.1804070609375 0.73682276875 0.2571378171875 0.73345310625 0.281605084375 0.7899831578125001 0.4653848625 0.7805119984375 0.479594290625 0.7030105359375 0.5507985796875 0.708180884375

--------------------------
0 0.30166058906250004 0.47904601874999997 0.3821804734375 0.4975789875 0.4153357015625 0.573395653125 0.6028996859375 0.603722475 0.8321446343750001 0.6020375375 0.8065677421874999 0.37121780625 0.7137329125 0.4099686078125 0.6947871140624999 0.2886618859375 0.6171091140625 0.2802378 0.5962687515625 0.2583352046875 0.59540716875 0.178872046875 0.37839126562500003 0.1791488765625 0.37270749375 0.2970859359375 0.30166058906250004 0.2954011390625 0.30166058906250004 0.47904601874999997


-------------------
0 0.3575508234375 0.6138312499999999 0.4295451296875 0.603722475 0.44943825156250006 0.6256249640625 0.5792173578125 0.6155160468750001 0.7326788718749999 0.6003527421875 0.71941684375 0.3577393671875 0.65689535625 0.3392063296875 0.6483698578125 0.2684440875 0.55269314375 0.2701289171875 0.54795669375 0.3004555984375 0.53374734375 0.3004555984375 0.5318527 0.24991111875 0.5460621296875 0.21116038750000002 0.53848379375 0.1067018375 0.2950294953125 0.12018034687500001 0.292187609375 0.266759290625 0.18655300156250001 0.28766834218750004 0.18419626718749998 0.531275259375 0.23440281093749998 0.531275259375 0.24292838906249997 0.612146525 0.3575508234375 0.6138312499999999

**Comment by glenn-jocher** [comment]
Hello @userwatch,

Thank you for providing the details and the example labels. It looks like you're on the right track with converting YOLOv8 segmentation labels to a format suitable for Mask R-CNN.

To help you further, here's a Python script that will loop through your YOLOv8 label files and convert them to the JSON format required by Mask R-CNN:

```python
import os
import json

def yolo_to_maskrcnn(yolo_txt_path, image_width, image_height, output_json_path):
    maskrcnn_format = {}
    
    for txt_file in os.listdir(yolo_txt_path):
        if txt_file.endswith('.txt'):
            with open(os.path.join(yolo_txt_path, txt_file), 'r') as file:
                lines = file.readlines()
                
                for line in lines:
                    parts = line.strip().split()
                    class_id = parts[0]
                    points = list(map(float, parts[1:]))
                    
                    all_points_x = [int(points[i] * image_width) for i in range(0, len(points), 2)]
                    all_points_y = [int(points[i] * image_height) for i in range(1, len(points), 2)]
                    
                    filename = txt_file.replace('.txt', '.jpg')  # Assuming your image files are .jpg
                    size = os.path.getsize(os.path.join(yolo_txt_path, filename))
                    
                    maskrcnn_format[filename + str(size)] = {
                        "filename": filename,
                        "size": size,
                        "regions": [{
                            "shape_attributes": {
                                "name": "polygon",
                                "all_points_x": all_points_x,
                                "all_points_y": all_points_y
                            },
                            "region_attributes": {
                                "name": "not_defined",
                                "type": "unknown",
                                "image_quality": {
                                    "good": True,
                                    "frontal": True,
                                    "good_illumination": True
                                },
                                "names": "Car"  # Replace with your actual class name
                            }
                        }],
                        "file_attributes": {
                            "caption": "",
                            "public_domain": "no",
                            "image_url": ""
                        }
                    }
    
    with open(output_json_path, 'w') as json_file:
        json.dump(maskrcnn_format, json_file, indent=4)

# Example usage
yolo_txt_path = 'path/to/your/yolo_labels_folder'
image_width = 1280  # Replace with your actual image width
image_height = 720  # Replace with your actual image height
output_json_path = 'maskrcnn_labels.json'

yolo_to_maskrcnn(yolo_txt_path, image_width, image_height, output_json_path)
```

This script will:
1. Loop through all `.txt` files in your YOLOv8 label folder.
2. Read each file and convert the normalized coordinates to absolute pixel values.
3. Format the data into the JSON structure required by Mask R-CNN.
4. Save the output to a JSON file.

Make sure to adjust the `image_width`, `image_height`, and paths according to your setup.

If you encounter any issues or need further assistance, please provide a minimum reproducible code example as outlined in our [guide](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us investigate and provide a solution more effectively.

Happy coding! 😊

**Comment by userwatch** [comment]
Thank you so much, you are a hero :)

Best wishes,

**Comment by userwatch** [comment]
Hello again,  I made the convert and encountered this error while training.
That's my json file.
https://github.com/userwatch/convert/blob/main/result.json 
Thats my error
![image](https://github.com/ultralytics/ultralytics/assets/69357065/7ec76373-def2-4dd5-b3a1-9d1ebdaa6c7f)
Any ideas about this error?

Thanks,

**Comment by glenn-jocher** [comment]
Hello @userwatch,

Thank you for providing the JSON file and the error screenshot. It looks like there might be an issue with the format or content of the JSON file used for training.

To help us investigate further, could you please provide a minimum reproducible code example that demonstrates how you are loading and using the JSON file for training? This will help us understand your setup better and pinpoint the issue. You can refer to our guide on creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of `torch` and `ultralytics`. If not, please upgrade your packages and try again to see if the issue persists.

In the meantime, here are a few things you can check:
1. **JSON Structure**: Ensure that the JSON structure matches the expected format for Mask R-CNN. Verify that all required fields are present and correctly formatted.
2. **Image Paths and Sizes**: Confirm that the image paths in the JSON file are correct and that the image sizes match the dimensions specified in the JSON.
3. **Coordinate Conversion**: Ensure that the coordinates in the JSON file are correctly converted from YOLOv8 format to the Mask R-CNN format.

If you need further assistance, please provide the requested code example, and we'll be happy to help you troubleshoot the issue.

Best wishes and happy coding! 😊

**Comment by userwatch** [comment]
image_width = 640 
image_height = 640 
When tagged in roboflow, the image size was 640x640.  I updated the width and height values.
and training started.
Thank you :)

**Comment by glenn-jocher** [comment]
Hello @userwatch,

Thank you for the update! I'm glad to hear that updating the width and height values to match the 640x640 dimensions resolved the issue and allowed you to start training. 🎉

If you encounter any further issues or have additional questions, feel free to reach out. We're here to help!

Happy training and

**Comment by userwatch** [comment]
Hello again, 
I have a project with a folder structure like this.
june folder
   test
    123-abc-part
                images
                      13.11.jpg
                labels
                     13-11.txt

       345-cde-part
                 images
                      18.14.jpg
                      18.17.jpg
                      18.14.jpg
                      18.14.jpg 
                 labels
                     18-17.txt
                     19-12.txt 
                     20-11.txt 
                     45-21.txt  
   train
       123-abc-part
                images
                      13.11.jpg
                labels
                     13-11.txt

       345-cde-part
                 images
                      18.14.jpg
                      18.17.jpg
                      18.14.jpg
                      18.14.jpg 
                 labels
                     18-17.txt
                     19-12.txt 
                     20-11.txt 
                     45-21.txt  
       987-xyc-part
       .
       .
       .


    valid
     123-abc-part
                images
                      13.11.jpg
                labels
                     13-11.txt

       345-cde-part
                 images
                      18.14.jpg
                      18.17.jpg
                      18.14.jpg
                      18.14.jpg 
                 labels
                     18-17.txt
                     19-12.txt 
                     20-11.txt 
                     45-21.txt  



How should I change the code for a structure like this?
