### ISSUE TITLE
Dependency of ray tune

### ISSUE THREAD

**Issue by jjerry-k** [ultralytics/ultralytics#13667]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Hyperparameter Tuning

### Bug

Hi. I'm Jerry. 
Thank you for your good framework.
I have one issue about dependency.
If you turn on the `use_ray` when running model.tune, it will install ray[tune]. 
In this time, the installation of numpy 2.0 seems to cause problems with other packages.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jjerry-k hi Jerry,

Thank you for your kind words and for bringing this to our attention! 😊

To help us investigate the issue more effectively, could you please provide a minimal reproducible example? This will allow us to replicate the problem on our end. You can find guidelines on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of `torch` and `ultralytics`. You can upgrade your packages using the following commands:

```bash
pip install --upgrade torch ultralytics
```

Regarding the dependency issue with `numpy 2.0`, it might be causing conflicts with other packages. As a temporary workaround, you can try specifying an earlier version of `numpy` that is compatible with your other dependencies. For example:

```bash
pip install numpy==1.21.0
```

Then, proceed with installing `ray[tune]`:

```bash
pip install "ray[tune]"
```

If the issue persists after these steps, please share the specific error messages or conflicts you are encountering. This information will be invaluable in diagnosing and resolving the problem.

Looking forward to your response!
