### ISSUE TITLE
[Detection] Results misbehave with torch.tensor as input

### ISSUE THREAD

**Issue by hotfur** [ultralytics/ultralytics#1371]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detector

### Bug

Reproduce: Call ultralytics.yolo.engine.model.YOLO.predict with input source as a batch of images in the form of Tensor[B, C, H, W]. Please make sure that the batch images contains as least one valid object so that the model can output a detection.

Expected behavior: The call returns a B long list containing Results objects. Each Results object have attribute orig_shape=[H, W], and attribute boxes containing the detection bounding boxes.

Observed behavior: The call returns a B long list containing Results objects. Each Results object have attribute orig_shape=[B, C]. These Results object have attribute boxes containing the detection bounding boxes, which has the correct classes and confidence values, but coordinates (xyxy, xyhw,...) all based on the incorrect assumption that original image shape is [B,C].

### Environment

ultralytics==8.0.52
torch==1.11.0+cu113

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@hotfur thanks for the bug report!

@AyushExel can you take a look at this? It seems original image shape is being computed incorrectly for BCHW tensor inputs.
