### ISSUE TITLE
Batch size with fraction does not work.

### ISSUE THREAD

**Issue by sodeso-nl** [ultralytics/ultralytics#13750]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

According to the documentation:

https://docs.ultralytics.com/modes/train/#train-settings

We can supply batch size in three different manners:
batch=20, for a fixed batch size.
batch=-1, for a calculated batch size which does not utilise more then 60% of available GPU memory
batch=0.70, for a calculated batch size where the fraction is the percentage of available GPU memory.

When I try option three I get the error that the batch size must be an INT.

Did I mis read the documentation?

### Environment

Ultralytics YOLOv8.2.28 Python-3.11.9 torch-2.3.1 CUDA:0 (NVIDIA GeForce RTX 4090, 24215MiB)

### Minimal Reproducible Example

```
model = YOLO('yolov8n.pt')

results = model.train(
  data='./ANPR-NL/data.yaml',
  name='1025_nr_b_09',
  seed=42,
  batch=0.90,
  epochs=EPOCHS,
  exist_ok=True,
  imgsz=(1024,768),
  rect=False)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by knoppmyth** [comment]
You misread... It is a colon (:) not a period (.). So it should be batch=0:90 not batch=0.90.

**Comment by sodeso-nl** [comment]
Then there is a small error in the documentation, it states:

`Batch size, with three modes: set as an integer (e.g., batch=16), auto mode for 60% GPU memory utilization (batch=-1), or auto mode with specified utilization fraction (batch=0.70).`

**Comment by glenn-jocher** [comment]
@sodeso-nl thank you for pointing that out! It appears there is indeed a small error in the documentation. The correct syntax for specifying the batch size with a utilization fraction is `batch=0:70` rather than `batch=0.70`.

Here's how you can set it in your code:

```python
results = model.train(
  data='./ANPR-NL/data.yaml',
  name='1025_nr_b_09',
  seed=42,
  batch='0:90',
  epochs=EPOCHS,
  exist_ok=True,
  imgsz=(1024,768),
  rect=False)
```

This should resolve the issue. If you encounter any further problems, please ensure you are using the latest versions of `torch` and `ultralytics`. If the issue persists, feel free to provide additional details or a minimal reproducible example so we can assist you further. 😊

Thank you for your understanding and for helping us improve our documentation!

**Comment by sodeso-nl** [comment]
I did not have the chance to try this, but If I do:

`results = model.train(
  data='./ANPR-NL/data.yaml',
  name='1025_nr_b_09',
  seed=42,
  batch='0:90',
  epochs=EPOCHS,
  exist_ok=True,
  imgsz=(1024,768),
  rect=False)`

Then I get the error message:

'batch=0:95' is of invalid type str. 'batch' must be an int (i.e. 'batch=8')

I think the issue is caused by the following code:

ultralytics/cfg/__init__.py:

`
CFG_INT_KEYS = {  # integer-only arguments
    ...
    "batch",
}
`

Which checks if the argument is in fact an Integer. The 'batch' has now been moved to the CFG_FLOAT_KEYS (since the 9th of June), so now we will get an error that it is not a float.

**Comment by ambitious-octopus** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.
> 
> ### YOLOv8 Component
> Train
> 
> ### Bug
> According to the documentation:
> 
> https://docs.ultralytics.com/modes/train/#train-settings
> 
> We can supply batch size in three different manners: batch=20, for a fixed batch size. batch=-1, for a calculated batch size which does not utilise more then 60% of available GPU memory batch=0.70, for a calculated batch size where the fraction is the percentage of available GPU memory.
> 
> When I try option three I get the error that the batch size must be an INT.
> 
> Did I mis read the documentation?
> 
> ### Environment
> Ultralytics YOLOv8.2.28 Python-3.11.9 torch-2.3.1 CUDA:0 (NVIDIA GeForce RTX 4090, 24215MiB)
> 
> ### Minimal Reproducible Example
> ```
> model = YOLO('yolov8n.pt')
> 
> results = model.train(
>   data='./ANPR-NL/data.yaml',
>   name='1025_nr_b_09',
>   seed=42,
>   batch=0.90,
>   epochs=EPOCHS,
>   exist_ok=True,
>   imgsz=(1024,768),
>   rect=False)
> ```
> 
> ### Additional
> _No response_
> 
> ### Are you willing to submit a PR?
> * [ ]  Yes I'd like to help by submitting a PR!

Hey @sodeso-nl,
What error do you get when running the code you provided?

**Comment by sodeso-nl** [comment]
Specifically I get the following error:

`TypeError                                 Traceback (most recent call last)
Cell In[14], line 4
      2 model.info()
      3 # model 1
----> 4 results = model.train(
      5   data='./ANPR-NL/data.yaml',
      6   name='model1',
      7   seed=42,
      8   batch='0:90',
      9   epochs=EPOCHS,
     10   exist_ok=True,
     11   imgsz=(1024,768),
     12   rect=False)

File ~/anaconda3/envs/anpr-nl/lib/python3.11/site-packages/ultralytics/engine/model.py:655, in Model.train(self, trainer, **kwargs)
    652 if args.get("resume"):
    653     args["resume"] = self.ckpt_path
--> 655 self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
    656 if not args.get("resume"):  # manually set model only if not resuming
    657     self.trainer.model = self.trainer.get_model(weights=self.model if self.ckpt else None, cfg=self.model.yaml)

File ~/anaconda3/envs/anpr-nl/lib/python3.11/site-packages/ultralytics/engine/trainer.py:99, in BaseTrainer.__init__(self, cfg, overrides, _callbacks)
     91 def __init__(self, cfg=DEFAULT_CFG, overrides=None, _callbacks=None):
     92     """
     93     Initializes the BaseTrainer class.
     94 
   (...)
     97         overrides (dict, optional): Configuration overrides. Defaults to None.
     98     """
---> 99     self.args = get_cfg(cfg, overrides)
    100     self.check_resume(overrides)
    101     self.device = select_device(self.args.device, self.args.batch)

File ~/anaconda3/envs/anpr-nl/lib/python3.11/site-packages/ultralytics/cfg/__init__.py:224, in get_cfg(cfg, overrides)
    221     LOGGER.warning(f"WARNING ⚠️ 'name=model' automatically updated to 'name={cfg['name']}'.")
    223 # Type and Value checks
--> 224 check_cfg(cfg)
    226 # Return instance
    227 return IterableSimpleNamespace(**cfg)

File ~/anaconda3/envs/anpr-nl/lib/python3.11/site-packages/ultralytics/cfg/__init__.py:253, in check_cfg(cfg, hard)
    251 elif k in CFG_INT_KEYS and not isinstance(v, int):
    252     if hard:
--> 253         raise TypeError(
    254             f"'{k}={v}' is of invalid type {type(v).__name__}. " f"'{k}' must be an int (i.e. '{k}=8')"
    255         )
    256     cfg[k] = int(v)
    257 elif k in CFG_BOOL_KEYS and not isinstance(v, bool):

TypeError: 'batch=0:90' is of invalid type str. 'batch' must be an int (i.e. 'batch=8')`

This is with version 8.2.28 of Ultralytics package, I have not tried the latest 8.2.35 version yet since it is not available on conda-forge yet.

**Comment by ambitious-octopus** [comment]
Try with this please:

```python
model = YOLO('yolov8n.pt')

results = model.train(
  data='./ANPR-NL/data.yaml',
  name='1025_nr_b_09',
  seed=42,
  batch=0.90,
  epochs=EPOCHS,
  exist_ok=True,
  imgsz=(1024,768),
  rect=False)
```

**Comment by sodeso-nl** [comment]
I think this would solve it with the newer versions of Ultralytics > 8.2.28 since the argument was changed from int to float. So the issue might be solved, however at the moment I can't test it yet. The newer versions are not yet available through Conda. I'll close the issue for now.

**Comment by glenn-jocher** [comment]
Thank you for your understanding and for closing the issue. Indeed, the batch size argument was updated to accept float values in newer versions of Ultralytics. If you encounter any further issues once you can test with the latest version, please feel free to reopen the issue or create a new one. We appreciate your patience and cooperation. 😊

If you have any other questions or need further assistance, the YOLO community and the Ultralytics team are always here to help!

**Comment by blackCmd** [comment]
> Thank you for your understanding and for closing the issue. Indeed, the batch size argument was updated to accept float values in newer versions of Ultralytics. If you encounter any further issues once you can test with the latest version, please feel free to reopen the issue or create a new one. We appreciate your patience and cooperation. 😊
> 
> If you have any other questions or need further assistance, the YOLO community and the Ultralytics team are always here to help!


I just downloaded the latest version from GitHub. However, I still cannot use a float value like batch=0.7.

Error log is here.
`  File "C:\Users\J5330-3\Miniconda\envs\ictcoc_py310\lib\site-packages\torch\utils\data\sampler.py", line 267, in __init__
    raise ValueError(f"batch_size should be a positive integer value, but got batch_size={batch_size}")
ValueError: batch_size should be a positive integer value, but got batch_size=0.0
`

**Comment by pderrenger** [comment]
@blackCmd thank you for updating to the latest version. It appears the issue persists with the batch size argument. This might be due to an internal handling of the batch size parameter. Please ensure you are using the correct syntax and try using an integer value for now. If the problem continues, we recommend opening a new issue with detailed logs and steps to reproduce so we can investigate further. Your feedback is valuable to us, and we appreciate your patience.
