### ISSUE TITLE
How to crop the detected object from image using YOLOv8 model?

### ISSUE THREAD

**Issue by karndeepsingh** [ultralytics/ultralytics#1376]
Hi,
I am trying to train model using YOLOv8 Weights. How I can crop the detected images from the image like we use to do in yolov5 models?

I also have following questions:
1. Does all the functionality of YOLOv5 repo is available for this YOLOv8 repo as well like image prediction analytics and traingn and test mAP or Precision recall curve etc?
2.  Can we use Yolov8 weights and use Yolov5 way of training the model using `!python train.py --weights yolov8n.pt`  script?

**Comment by karndeepsingh** [comment]
> @karndeepsingh yes, most YOLOv5 functionality is in place in YOLOv8, with the remainder in our roadmap. To crop images with YOLOv8:
> 
> ```shell
> pip install ultralytics
> 
> yolo predict model=yolov8n.pt source='https://ultralytics.com/images/zidane.jpg' save_crop
> ```
> 
> For training usage examples see https://docs.ultralytics.com/tasks/detection/#train

Thanks @glenn-jocher for replying.
 I just had one more question, What will be the better way deploy the trained YOLOv8 model on cloud for faster inferencing and maintain good accuracy ?

**Comment by glenn-jocher** [comment]
@karndeepsingh CPU deployments should be done with ONNX or OpenVINO for fastest speeds, and TensorRT for CUDA-available environments (i.e. if you have a GPU). You can see export benchmark speeds in our daily CI:

https://github.com/ultralytics/ultralytics/actions/runs/4389525168/jobs/7687165310

<img width="1283" alt="Screenshot 2023-03-11 at 17 54 11" src="https://user-images.githubusercontent.com/26833433/224497314-10713e51-d4e1-4a16-af33-f2bdd6f7cc96.png">

**Comment by karndeepsingh** [comment]
> @karndeepsingh CPU deployments should be done with ONNX or OpenVINO for fastest speeds, and TensorRT for CUDA-available environments (i.e. if you have a GPU). You can see export benchmark speeds in our daily CI:
> 
> https://github.com/ultralytics/ultralytics/actions/runs/4389525168/jobs/7687165310
> 
> <img alt="Screenshot 2023-03-11 at 17 54 11" width="1283" src="https://user-images.githubusercontent.com/26833433/224497314-10713e51-d4e1-4a16-af33-f2bdd6f7cc96.png">

Thanks @glenn-jocher

**Comment by karndeepsingh** [comment]
> ```shell
> yolo predict model=yolov8n.pt source='https://ultralytics.com/images/zidane.jpg' save_crop
> ```

1. How I can save the predicted results into different folder by using CLI and Python commands?
2. Also, I can see predicted results are coming with index number over detected Region, how I can add class to detected region of interest?

**Comment by glenn-jocher** [comment]
@karndeepsingh I don't understand your other question but Python usage is just like CLI, all arguments are always the same between the two:
```python
model.predict(source=..., save_crop=True)
```

**Comment by Laughing-q** [comment]
@karndeepsingh 
save_dir is composed of `project` and `name`. You can change save_dir by modify these two args. :)
`save_dir=project/name`.
like:
```python
results = model.predict(source=xxx, project="xxx", name="xxx")
```
BTW I don't think we support JSON format in predict field.

**Comment by karndeepsingh** [comment]
> @karndeepsingh save_dir is composed of `project` and `name`. You can change save_dir by modify these two args. :) `save_dir=project/name`. like:
> 
> ```python
> results = model.predict(source=xxx, project="xxx", name="xxx")
> ```
> 
> BTW I don't think we support JSON format in predict field.

@Laughing-q Thanks for reply.

**Comment by Laughing-q** [comment]
@karndeepsingh strange, I'm able to access this link.
![image](https://user-images.githubusercontent.com/61612323/234465173-d2278d16-92a1-4f25-b11f-c9c284b2acf3.png)

**Comment by Nithishrish23** [comment]
I need crop file.

I don't need crop folder to save. How can I do that

**Comment by glenn-jocher** [comment]
@Nithishrish23 sure, you can control where you want to save the cropped images using the `project` and `name` parameters. These parameters allow you to define a custom path where the predicted, cropped images are saved. While predicting, along with other parameters, you can specify these two parameters to save the results in the desired location. Please note that the save directory is composed as `save_dir=project/name`. 

Regarding the bounding box information, currently YOLOv8 does not directly support output in JSON format. However, the model's `predict` function does return the bounding box and class predictions, which you could use to create your own JSON format if necessary. I hope this answers your questions. Let us know if you have any more!

**Comment by Nithishrish23** [comment]
@glenn-jocher Thank You glenn-jocher. But I have used this command **`save_dir=project/name`** still saving crops folder only i don't save my crops images in crops folder.How can i do that

**Comment by glenn-jocher** [comment]
@Nithishrish23 The `save_dir` is meant to specify the parent directory where the folders like 'labels' and 'crops' get saved. The YOLOv8 model by default mandates the structure to save the results in a way that each different type of output (like labels, crops, etc) are stored in separate folders for better organization. As a result, regardless of the `save_dir` you specify, the cropped images will be saved in a 'crops' sub-folder within the specified `save_dir`.

While I understand you may wish for a way to directly save the cropped images in a single folder without the extra sub-folders, currently this is not directly supported by the YOLOv8 implementation. Based on your use case, an alternative could be to programmatically move the files from the 'crops' folder to your desired location post prediction. This can be easily achieved using a few lines of code in Python, utilizing the built-in `os` or `shutil` libraries.

**Comment by 89243982** [comment]
Hello, how to save the screenshot of the corresponding file name can contain coordinate information

**Comment by 89243982** [comment]
Because I want to get the corresponding target coordinates

**Comment by 89243982** [comment]
@glenn-jocher

**Comment by glenn-jocher** [comment]
Hello @89243982, to save the detections with the corresponding coordinates, you do not need to alter the default saving behavior of YOLOv8. When you run predictions with YOLOv8, the model saves a `.txt` file for each image within the `labels` subfolder in your `project/name` directory. Each `.txt` file contains the class and normalized bounding box coordinates (x_center, y_center, width, height) for every detection in the corresponding image.

So, if your aim is to obtain the detected target's coordinates, simply inspect the contents of these `.txt` label files. You'll find all the coordinate information you need without requiring any additional flags or parameters during prediction.

If you require this information to be stored following a specific format or in a single file, you might need to process these `.txt` files post-prediction to aggregate the coordinates as per your specifications. This can be done using a simple script in Python or another programming language capable of file I/O operations.

**Comment by weirdtux** [comment]
@glenn-jocher have a way to take the cropped image direct in memory without saving it on disk? Also when the program is running we can control de loop when is stream or control the inference to do each X frames? I know that it is possible using OpenCV, but we can do it out of the box only using de model.predict()?

**Comment by 89243982** [comment]
The algorithm can be considered to support custom saving of cropped images. However, making modifications is not difficult; I have already implemented it on my own.@glenn-jocher

**Comment by 89243982** [comment]
In the process of developing specific applications, more detailed information is often required

**Comment by glenn-jocher** [comment]
@89243982 it's great to hear that you've implemented custom saving of cropped images tailored to your specific application requirements. Indeed, YOLOv8, like many other machine learning models, offers a basic structure for prediction and output, which can and often should be extended or modified to fit the particular use cases developers are working on.

In development, especially in the domain of computer vision, the need for detailed information such as precise object coordinates, classification labels, and metadata is common. This can involve not just saving the images but also annotating them with additional information or integrating the model's output into larger systems.

To achieve these detailed outputs, developers typically make use of the results returned from the model's inference in their own custom scripts, extracting all necessary data and handling it as per the needs of their specific application, including saving outputs to databases, further processing, or real-time decision making.

Remember to always consider the licensing of YOLOv8 and redistribute your modifications in accordance with the AGPL-3.0 License, or consider obtaining an Enterprise License if your use case falls outside of what AGPL-3.0 permits.

If you have further questions or need insights about how to leverage YOLOv8 for your particular use case, feel free to reach out. The community and the Ultralytics team are here to support developers like you in pushing the boundaries of what's possible with state-of-the-art object detection models. 😊🚀

**Comment by Nithishrish23** [comment]
@glenn-jocher how to crop in plot
` for r in prediction:
        boxes = r.boxes.cpu().numpy()
        im_array = r.plot(labels=False, conf=False, boxes=False)
        im = Image.fromarray(im_array[..., ::-1])
        im.save(image_file_path, "JPEG")`
                                        
        Is it possible to crop in directly or i need to get box cordinates xyxy for crop. any easy way to crop directly in this code

**Comment by glenn-jocher** [comment]
@Nithishrish23 For cropping directly while iterating over the predictions, you would indeed need to use the bounding box coordinates to extract the specific area of the image that each detection represents. Currently, there is no built-in method in YOLOv8 to crop detected objects within the `plot()` function; you extract the bounding box coordinates (`xyxy`) from each detection and use these to crop the image using standard image processing libraries like PIL or OpenCV.

Your current loop with the `plot()` function seems to be visualizing detections rather than cropping. To crop the images, modify the loop to include the cropping logic after getting the box coordinates. Keep up the good work with custom developments! 👍🔧

**Comment by Nithishrish23** [comment]
@glenn-jocher Thank You Sir

**Comment by glenn-jocher** [comment]
@Nithishrish23 you're welcome! If you have any more questions, feel free to ask. Happy coding! 😊👨‍💻

**Comment by ssathees2412** [comment]
Need help understanding the naming conventions of cropped files. 
If my testdata folder has multiple image files (e.g., image_01, image_02, image_03) and each image file consists of multiple objects of interest that are cropped using the following code:
**CODE used:**
source = 'testdata path' results = model(source, stream=True)
model = YOLO(r'Custom model\best.pt') model.predict(source, save=True, conf=0.50, save_crop=True)
How can I identify the source of the cropped images?


EX for image_01;  
![cropped_images](https://github.com/ultralytics/ultralytics/assets/157847188/f0abd57e-2623-4024-ae85-1fc2e9e810ef)

My objective is to divide all the cropped images from the first attempt strips into one folder and those from the second attempt strips into another folder.(with reference to the attached image)

**Comment by glenn-jocher** [comment]
@ssathees2412 hi there! 👋

When you use `save_crop=True`, YOLOv8 saves the crops with a naming convention that includes the parent image's name and indices for the detected objects. For example, crops from `image_01.jpg` would be named like `image_01_1.jpg`, `image_01_2.jpg`, etc., where `_1`, `_2` denote different detected objects in `image_01.jpg`.

To organize cropped images based on their source file, you could use a script to move these files into respective folders after running the prediction. Python's `os` and `shutil` libraries could be really handy for this:

```python
import os
import shutil

# Define the folder paths
source_crops = 'path/to/cropped/images'
folder1 = 'path/to/first_attempt_folder'
folder2 = 'path/to/second_attempt_folder'

# Ensure the destination folders exist
os.makedirs(folder1, exist_ok=True)
os.makedirs(folder2, exist_ok=True)

# Move each cropped image to the respective folder
for filename in os.listdir(source_crops):
    if filename.startswith("image_01"):  # Customize this condition as needed
        shutil.move(os.path.join(source_crops, filename), folder1)
    else:
        shutil.move(os.path.join(source_crops, filename), folder2)
```

Customize the `startswith` condition depending on how your images are named or on other criteria relevant to your use case. Happy coding! 😊

**Comment by ssathees2412** [comment]
Thank you for clarifying the doubt. When setting save_crop=True for YOLOv8 output, the filenames of the cropped images are not consistently numbered in the order expected. Specifically, the naming convention leads to confusion since odd-numbered occurrences represent the first attempt, while even-numbered ones denote the second attempt. This arrangement doesn't reflect the sequential order of detection, making it difficult to associate each cropped image with its corresponding 1st or 2nd strip.

**Comment by glenn-jocher** [comment]
@ssathees2412 hello! 😀

Thanks for reaching out and mentioning your concern with the cropped image filenames when using `save_crop=True` in YOLOv8. I understand how this naming convention might cause some confusion, especially when you're trying to differentiate between first and second attempts based on odd and even numbering.

A simple workaround could involve custom logic in your script to rename or sort these files post-prediction, based on your specific needs. For example, you might sort and then rename files to ensure they reflect the sequential order of detection:

```python
import os
import re

# Directory containing the cropped images
cropped_img_dir = 'path/to/cropped/images'

# Sorting filenames based on numerical order embedded in the name
file_list = os.listdir(cropped_img_dir)
sorted_files = sorted(file_list, key=lambda x: int(re.findall('\d+', x.split('_')[-1])[0]))

# Rename files or move them accordingly here
# e.g., adding your logic to differentiate and arrange files based on odd/even numbering

```

This approach allows you to manually impose order and categorization on the cropped images as needed. Hope this guideline offers a handy strategy to manage your filenames more effectively! If you have any more questions or need further assistance, feel free to ask. Happy coding! 🚀

**Comment by ssathees2412** [comment]
I am assuming that the aforementioned method would only function correctly if:
The odd-numbered cropped image corresponds to the first strip, and the even-numbered image corresponds to the second strip.
However, this assumption does not hold true. I have observed that both the cropped images from the first attempt and those from the second attempt possess both odd and even numbers.

**Comment by glenn-jocher** [comment]
@ssathees2412 hey there! 👋

Got it, thanks for clarifying that bit about the odd and even numbers not aligning with the first and second attempts as expected. 

In this case, I'd suggest including a custom identifier in your filenames directly within your processing script, right after detection and cropping. Unfortunately, YOLOv8's `save_crop` functionality doesn't directly support custom naming based on the detection attempt. However, you could modify the saved filenames right after detection by embedding your own logic. Here's a quick example of how you might do it:

```python
import os

# Path to your cropped images
cropped_images_path = 'path/to/cropped_images'
# Go through each file and rename it
for filename in os.listdir(cropped_images_path):
    new_name = filename.replace('_crop', '_attempt1' if int(filename.split('_')[-1].split('.')[0]) % 2 != 0 else '_attempt2')
    os.rename(os.path.join(cropped_images_path, filename), os.path.join(cropped_images_path, new_name))
```

This script snippet is a basic starting point. Adjust according to your file naming pattern. Hope this helps you manage your files more effectively! If you run into more issues or have other questions, feel free to reach out. Happy coding! 😊

**Comment by Nithishrish23** [comment]
```
    prediction = model.predict(image_file_path, conf=0.2)
    for i, r in enumerate(prediction):
        boxes = r.boxes.cpu().numpy()
        im_array = r.plot(labels=False, conf=False, boxes=False)
        im = Image.fromarray(im_array[..., ::-1])
        im.save(image_file_path, "JPEG", optimize=True, quality=50, jfif_unit=1,
                dpi=(96, 96))
        imcrop = im.crop((boxes.xyxy[i][0], boxes.xyxy[i][1], boxes.xyxy[i][2], boxes.xyxy[i][3]))

        imcrop.save(image_file_path, "JPEG")//by save use logic of <for filename in os.listdir(cropped_images_path)>

```

try this bro

**Comment by glenn-jocher** [comment]
@Nithishrish23 hey there! 😄 Thanks for reaching out with your question. It seems like you're almost there, but there's a little mix-up in your code snippet. When saving cropped images, especially if you're iterating through multiple detections in an image, you'd want to ensure each cropped image is saved with a unique filename. Here's a quick fix:

```python
from PIL import Image
import numpy as np

prediction = model.predict(image_file_path, conf=0.2)
for i, r in enumerate(prediction):
    boxes = r.boxes.cpu().numpy()
    im_array = r.plot(labels=False, conf=False, boxes=False)
    # Convert the BGR image to RGB.
    im = Image.fromarray(im_array[..., ::-1])
    
    # For saving the original detection plot
    im.save(f"detected_{i}.jpg", "JPEG", optimize=True, quality=50, jfif_unit=1, dpi=(96, 96))

    for j, box in enumerate(boxes):
        # Cropping logic here
        imcrop = im.crop((box[0], box[1], box[2], box[3]))
        # Ensure each crop has a unique filename
        imcrop.save(f"crop_{i}_{j}.jpg", "JPEG")
```

This adjustment ensures each cropped image and detection plot is saved as a separate file. Happy coding, and feel free to reach out if you need more help! 🚀

**Comment by vj1234567890** [comment]
all work well with image input but in case of video it crops same objects images from each frame how to prevent it

**Comment by glenn-jocher** [comment]
@vj1234567890 hey there! 👋

Ah, I see what you're pointing out with video inputs and cropping the same object across frames. A quick strategy to prevent saving repeats is to track objects across frames and only save crops for new detections. This might involve a bit of custom logic, comparing the current frame's detections to the previous ones.

Here's a simplified snippet that illustrates a basic approach:

```python
from ultralytics import YOLO
from PIL import Image
import numpy as np

model = YOLO('path/to/model.pt')
video_path = 'path/to/video.mp4'
previous_boxes = []

res = model.predict(source=video_path, stream=True)
for frame_results in res:
    current_boxes = frame_results.boxes.xyxy.cpu().numpy()
    for box in current_boxes:
        if not any(np.allclose(box, prev_box, atol=10) for prev_box in previous_boxes):
            # This is a new detection
            im = Image.fromarray(frame_results.orig_img)
            imcrop = im.crop(box[:4])
            imcrop.save(f"crop_{len(previous_boxes)}.jpg", "JPEG")
            previous_boxes.append(box)

# Update this snippet as needed, especially how you decide box similarity.
```

This approach uses `np.allclose` with a tolerance to check similarity between boxes, preventing near-duplicate crops. You might need to adjust the tolerance (`atol`) based on your video's specifics. Hope this helps! Keep experimenting and feel free to reach out if you have more questions. Happy coding! 😊

**Comment by Christian-lyc** [comment]
I want to ask if I want to save the cropped image with a larger crop size than the predicted bounding box. How can I do that?

**Comment by glenn-jocher** [comment]
Hello, to save screenshots with coordinate information, you can modify the prediction script to include coordinates in the filename. Use the `results` object to access bounding box data and append it to the filename when saving. Let me know if you need further assistance!

**Comment by glenn-jocher** [comment]
@89243982 to save screenshots with coordinate information, you can modify the prediction results to include coordinates in the filename. After prediction, use Python to extract the coordinates and rename the files accordingly.

**Comment by glenn-jocher** [comment]
Hello! To save screenshots with coordinate information, you can modify the prediction script to include coordinates in the filename. Use the `results` object to extract bounding box coordinates and append them to the filename when saving. Let me know if you need further assistance!

**Comment by glenn-jocher** [comment]
@89243982 to save screenshots with coordinate information, you can modify the filename to include coordinates after obtaining them from the model's predictions. You can use Python to automate this process. If you need further assistance, please refer to the documentation or community forums.

**Comment by glenn-jocher** [comment]
To save screenshots with coordinate information, you can modify the prediction script to include coordinates in the filename or save them in a separate file. If you need further assistance, feel free to ask!
