### ISSUE TITLE
Convert ONNX into BLOB format for integration on camera

### ISSUE THREAD

**Issue by KennethEladistu** [ultralytics/ultralytics#13763]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello may I ask, currently I am using YOLO V8 OBB, and will be using it on our OAK-D-Pro camera, since the OAK-D-Pro only accepts blob file to use its depth feature, I already converted my .pt file into .onnx file and I am struggling to convert the .onnx file into .blob file. I already tried the documentation on the luxonis website but it still does not convert my .onnx file into.blob. May I ask if you have any idea on how to convert this? Thank you!

**Comment by glenn-jocher** [comment]
@KennethEladistu hello,

Thank you for reaching out! It's great to hear that you're working with YOLOv8 OBB and integrating it with the OAK-D-Pro camera. Converting an ONNX model to a BLOB format for use with Luxonis devices can indeed be a bit tricky. Here are some steps and tips that might help you with the conversion:

1. **Ensure Latest Versions**: First, make sure you are using the latest versions of `torch` and `ultralytics`. This ensures compatibility and access to the latest features and bug fixes. You can update your packages using:
    ```bash
    pip install --upgrade torch ultralytics
    ```

2. **Convert ONNX to BLOB**: Luxonis provides a tool called `depthai` that can be used to convert ONNX models to BLOB format. Here’s a general approach you can follow:
    - Install the `depthai` package:
        ```bash
        pip install depthai
        ```
    - Use the `depthai` model conversion tool:
        ```bash
        depthai_model_converter -i yolov8n.onnx -o yolov8n.blob
        ```

3. **Luxonis Documentation**: If you encounter issues, I recommend revisiting the Luxonis documentation for detailed instructions and troubleshooting tips. Sometimes, specific model configurations or additional parameters are needed for successful conversion.

4. **Community Support**: If the above steps do not resolve your issue, consider reaching out to the Luxonis community or forums. They might have more specific insights or updates regarding the conversion process.

If you continue to face challenges, please provide more details or any error messages you encounter. This will help us assist you better.

Best of luck with your integration, and feel free to reach out if you have any more questions! 😊

**Comment by KennethEladistu** [comment]
> @KennethEladistu hello,
> 
> Thank you for reaching out! It's great to hear that you're working with YOLOv8 OBB and integrating it with the OAK-D-Pro camera. Converting an ONNX model to a BLOB format for use with Luxonis devices can indeed be a bit tricky. Here are some steps and tips that might help you with the conversion:
> 
>     1. **Ensure Latest Versions**: First, make sure you are using the latest versions of `torch` and `ultralytics`. This ensures compatibility and access to the latest features and bug fixes. You can update your packages using:
>        ```shell
>        pip install --upgrade torch ultralytics
>        ```
> 
>     2. **Convert ONNX to BLOB**: Luxonis provides a tool called `depthai` that can be used to convert ONNX models to BLOB format. Here’s a general approach you can follow:
>        
>        * Install the `depthai` package:
>          ```shell
>          pip install depthai
>          ```
>        * Use the `depthai` model conversion tool:
>          ```shell
>          depthai_model_converter -i yolov8n.onnx -o yolov8n.blob
>          ```
> 
>     3. **Luxonis Documentation**: If you encounter issues, I recommend revisiting the Luxonis documentation for detailed instructions and troubleshooting tips. Sometimes, specific model configurations or additional parameters are needed for successful conversion.
> 
>     4. **Community Support**: If the above steps do not resolve your issue, consider reaching out to the Luxonis community or forums. They might have more specific insights or updates regarding the conversion process.
> 
> 
> If you continue to face challenges, please provide more details or any error messages you encounter. This will help us assist you better.
> 
> Best of luck with your integration, and feel free to reach out if you have any more questions! 😊

Currently I tried other ways without converting it, I tried a script to directly use the ".pt" file and run it on the OAK-D=PRO camera, here is my script 

`#!/usr/bin/env python3

import cv2
import depthai as dai
from submodule.calc import HostSpatialsCalc
from submodule.utility import *
import numpy as np
import math
from ultralytics import YOLO


# Load a pretrained YOLOv8n model
cap = cv2.VideoCapture(0)
model = YOLO("model/best.pt")

# Create pipeline
pipeline = dai.Pipeline()

# Define source and output
camRgb = pipeline.create(dai.node.ColorCamera)
xoutRgb = pipeline.create(dai.node.XLinkOut)
xoutRgb.setStreamName("rgb")

# Properties
camRgb.setPreviewSize(640, 400)
camRgb.setResolution(dai.ColorCameraProperties.SensorResolution.THE_1080_P)
camRgb.setInterleaved(False)
camRgb.setColorOrder(dai.ColorCameraProperties.ColorOrder.RGB)

# Linking
camRgb.preview.link(xoutRgb.input)

# Define sources and outputs
monoLeft = pipeline.create(dai.node.MonoCamera)
monoRight = pipeline.create(dai.node.MonoCamera)
stereo = pipeline.create(dai.node.StereoDepth)

# Properties
monoLeft.setResolution(dai.MonoCameraProperties.SensorResolution.THE_400_P)
monoLeft.setBoardSocket(dai.CameraBoardSocket.LEFT)
monoRight.setResolution(dai.MonoCameraProperties.SensorResolution.THE_400_P)
monoRight.setBoardSocket(dai.CameraBoardSocket.RIGHT)

stereo.initialConfig.setConfidenceThreshold(255)
# stereo.setDefaultProfilePreset(dai.node.StereoDepth.PresetMode.HIGH_DENSITY)
stereo.setDepthAlign(dai.CameraBoardSocket.CAM_A)
stereo.setLeftRightCheck(True)
stereo.setOutputSize(monoLeft.getResolutionWidth(), monoLeft.getResolutionHeight())
stereo.setSubpixel(False)
stereo.setExtendedDisparity(True)

# Linking
monoLeft.out.link(stereo.left)
monoRight.out.link(stereo.right)

xoutDepth = pipeline.create(dai.node.XLinkOut)
xoutDepth.setStreamName("depth")
stereo.depth.link(xoutDepth.input)

xoutDepth = pipeline.create(dai.node.XLinkOut)
xoutDepth.setStreamName("disp")
stereo.disparity.link(xoutDepth.input)

# Connect to device and start pipeline
with dai.Device(pipeline) as device:
    # Output queue will be used to get the depth frames from the outputs defined above
    depthQueue = device.getOutputQueue(name="depth")
    dispQ = device.getOutputQueue(name="disp")
    # Output queue will be used to get the rgb frames from the output defined above
    qRgb = device.getOutputQueue(name="rgb", maxSize=4, blocking=False)

    text = TextHelper()
    rgbtext= TextHelper()
    hostSpatials = HostSpatialsCalc(device)
    y = 200
    x = 300
    # w = 0
    # h = 0
    step = 3
    delta = 5
    hostSpatials.setDeltaRoi(delta)

    print("Use WASD keys to move ROI.\nUse 'r' and 'f' to change ROI size.")

    while True:
        inRgb = qRgb.get()  # blocking call, will wait until a new data has arrived
        frame = inRgb.getCvFrame()

         # Calculate spatial coordinates from depth frame (assuming this part works correctly)
        depthData = depthQueue.get()
        spatials, centroid = hostSpatials.calc_spatials(depthData, (x, y))  # Calculate spatial coordinates

        # Calculate spatial coordiantes from depth frame
        # ret, frame = cap.read() 
        results = model(frame)
        
        # Check if there are any detections
        if results[0].boxes is not None:
        # Extract the detections
         detections = results[0].boxes.xyxy.cpu().numpy()  # xyxy format (xmin, ymin, xmax, ymax, confidence, class)

        # Loop over detections and draw bounding boxes
        for det in detections:
            xmin, ymin, xmax, ymax, confidence, class_id = det
            if confidence > 0.30:  # Confidence threshold
                cv2.rectangle(frame, (int(xmin), int(ymin)), (int(xmax), int(ymax)), (0, 255, 0), 2)
                label = f"{model.names[int(class_id)]}: {confidence:.2f}"
                cv2.putText(frame, label, (int(xmin), int(ymin) - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

        key = cv2.waitKey(1)
        if key == ord('q'):
            break
        elif key == ord('w'):
            y -= step
        elif key == ord('a'):
            x -= step
        elif key == ord('s'):
            y += step
        elif key == ord('d'):
            x += step
        elif key == ord('r'): # Increase Delta
            if delta < 50:
                delta += 1
                hostSpatials.setDeltaRoi(delta)
        elif key == ord('f'): # Decrease Delta
            if 3 < delta:
                delta -= 1
                hostSpatials.setDeltaRoi(delta)`  

It displays on the live view of OAK-D-Pro but there are no bounding box that is showing currently even if I trained my data sets on parcel data sets. I want it so that when it displays in the oak-d-pro and it detects a parcel there will be a bounding box that will show also.  Thanks!

**Comment by glenn-jocher** [comment]
Hello @KennethEladistu,

Thank you for sharing your script and providing detailed information about your setup. It's great to see your progress with integrating YOLOv8 OBB on the OAK-D-Pro camera. Let's address the issue of the bounding boxes not displaying.

### Steps to Troubleshoot and Resolve:

1. **Verify Model and Data Compatibility**:
   - Ensure that the model (`best.pt`) is correctly trained and validated on your dataset.
   - Confirm that the model can detect objects correctly when run outside the OAK-D-Pro environment, using a simple script to test predictions on sample images.

2. **Check for Detection Results**:
   - Ensure that the `results[0].boxes` object is not empty and contains valid detections.
   - Add print statements to debug and verify the detection results:
     ```python
     results = model(frame)
     print(results)  # Print the entire results object to inspect
     ```

3. **Adjust Confidence Threshold**:
   - Lower the confidence threshold to ensure that detections are not being filtered out:
     ```python
     if confidence > 0.30:  # Try lowering this threshold to 0.20 or 0.10
     ```

4. **Ensure Correct Frame Processing**:
   - Verify that the frame being processed by the model is correctly captured and formatted:
     ```python
     frame = inRgb.getCvFrame()
     ```

5. **Update and Test with Latest Versions**:
   - Ensure you are using the latest versions of `torch` and `ultralytics`:
     ```bash
     pip install --upgrade torch ultralytics
     ```

6. **Sample Code for Debugging**:
   - Here’s a simplified version of your script with added debug statements:
     ```python
     from ultralytics import YOLO
     import cv2
     import depthai as dai

     # Load a pretrained YOLOv8n model
     model = YOLO("model/best.pt")

     # Create pipeline
     pipeline = dai.Pipeline()
     camRgb = pipeline.create(dai.node.ColorCamera)
     xoutRgb = pipeline.create(dai.node.XLinkOut)
     xoutRgb.setStreamName("rgb")
     camRgb.setPreviewSize(640, 400)
     camRgb.setResolution(dai.ColorCameraProperties.SensorResolution.THE_1080_P)
     camRgb.setInterleaved(False)
     camRgb.setColorOrder(dai.ColorCameraProperties.ColorOrder.RGB)
     camRgb.preview.link(xoutRgb.input)

     # Connect to device and start pipeline
     with dai.Device(pipeline) as device:
         qRgb = device.getOutputQueue(name="rgb", maxSize=4, blocking=False)
         while True:
             inRgb = qRgb.get()  # blocking call, will wait until a new data has arrived
             frame = inRgb.getCvFrame()
             results = model(frame)
             print(results)  # Debug: Print results to inspect

             # Check if there are any detections
             if results[0].boxes is not None:
                 detections = results[0].boxes.xyxy.cpu().numpy()
                 for det in detections:
                     xmin, ymin, xmax, ymax, confidence, class_id = det
                     if confidence > 0.30:
                         cv2.rectangle(frame, (int(xmin), int(ymin)), (int(xmax), int(ymax)), (0, 255, 0), 2)
                         label = f"{model.names[int(class_id)]}: {confidence:.2f}"
                         cv2.putText(frame, label, (int(xmin), int(ymin) - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

             cv2.imshow("OAK-D-Pro Live View", frame)
             if cv2.waitKey(1) & 0xFF == ord('q'):
                 break
         cv2.destroyAllWindows()
     ```

If the issue persists, please provide any error messages or additional details from the debug output. This will help us further diagnose the problem.

Best of luck with your integration, and feel free to reach out if you have any more questions! 😊

**Comment by KennethEladistu** [comment]
> Hello @KennethEladistu,
> 
> Thank you for sharing your script and providing detailed information about your setup. It's great to see your progress with integrating YOLOv8 OBB on the OAK-D-Pro camera. Let's address the issue of the bounding boxes not displaying.
> ### Steps to Troubleshoot and Resolve:
> 
>     1. **Verify Model and Data Compatibility**:
>        
>        * Ensure that the model (`best.pt`) is correctly trained and validated on your dataset.
>        * Confirm that the model can detect objects correctly when run outside the OAK-D-Pro environment, using a simple script to test predictions on sample images.
> 
>     2. **Check for Detection Results**:
>        
>        * Ensure that the `results[0].boxes` object is not empty and contains valid detections.
>        * Add print statements to debug and verify the detection results:
>          ```python
>          results = model(frame)
>          print(results)  # Print the entire results object to inspect
>          ```
> 
>     3. **Adjust Confidence Threshold**:
>        
>        * Lower the confidence threshold to ensure that detections are not being filtered out:
>          ```python
>          if confidence > 0.30:  # Try lowering this threshold to 0.20 or 0.10
>          ```
> 
>     4. **Ensure Correct Frame Processing**:
>        
>        * Verify that the frame being processed by the model is correctly captured and formatted:
>          ```python
>          frame = inRgb.getCvFrame()
>          ```
> 
>     5. **Update and Test with Latest Versions**:
>        
>        * Ensure you are using the latest versions of `torch` and `ultralytics`:
>          ```shell
>          pip install --upgrade torch ultralytics
>          ```
> 
>     6. **Sample Code for Debugging**:
>        
>        * Here’s a simplified version of your script with added debug statements:
>          ```python
>          from ultralytics import YOLO
>          import cv2
>          import depthai as dai
>          
>          # Load a pretrained YOLOv8n model
>          model = YOLO("model/best.pt")
>          
>          # Create pipeline
>          pipeline = dai.Pipeline()
>          camRgb = pipeline.create(dai.node.ColorCamera)
>          xoutRgb = pipeline.create(dai.node.XLinkOut)
>          xoutRgb.setStreamName("rgb")
>          camRgb.setPreviewSize(640, 400)
>          camRgb.setResolution(dai.ColorCameraProperties.SensorResolution.THE_1080_P)
>          camRgb.setInterleaved(False)
>          camRgb.setColorOrder(dai.ColorCameraProperties.ColorOrder.RGB)
>          camRgb.preview.link(xoutRgb.input)
>          
>          # Connect to device and start pipeline
>          with dai.Device(pipeline) as device:
>              qRgb = device.getOutputQueue(name="rgb", maxSize=4, blocking=False)
>              while True:
>                  inRgb = qRgb.get()  # blocking call, will wait until a new data has arrived
>                  frame = inRgb.getCvFrame()
>                  results = model(frame)
>                  print(results)  # Debug: Print results to inspect
>          
>                  # Check if there are any detections
>                  if results[0].boxes is not None:
>                      detections = results[0].boxes.xyxy.cpu().numpy()
>                      for det in detections:
>                          xmin, ymin, xmax, ymax, confidence, class_id = det
>                          if confidence > 0.30:
>                              cv2.rectangle(frame, (int(xmin), int(ymin)), (int(xmax), int(ymax)), (0, 255, 0), 2)
>                              label = f"{model.names[int(class_id)]}: {confidence:.2f}"
>                              cv2.putText(frame, label, (int(xmin), int(ymin) - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
>          
>                  cv2.imshow("OAK-D-Pro Live View", frame)
>                  if cv2.waitKey(1) & 0xFF == ord('q'):
>                      break
>              cv2.destroyAllWindows()
>          ```
> 
> 
> If the issue persists, please provide any error messages or additional details from the debug output. This will help us further diagnose the problem.
> 
> Best of luck with your integration, and feel free to reach out if you have any more questions! 😊

Hello it's already working but I cannot get the "depth" feature which is the Z to be displayed using the OAK-D-Pro, this is my code currently 

`from ultralytics import YOLO
import cv2
import depthai as dai

# Load a pretrained YOLOv8n model
model = YOLO("C:/Users/KennethAaronEladistu/oak_d/oak_d/best.pt")

# Create pipeline
pipeline = dai.Pipeline()
camRgb = pipeline.create(dai.node.ColorCamera)
xoutRgb = pipeline.create(dai.node.XLinkOut)
xoutRgb.setStreamName("rgb")
camRgb.setPreviewSize(640, 400)
camRgb.setResolution(dai.ColorCameraProperties.SensorResolution.THE_1080_P)
camRgb.setInterleaved(False)
camRgb.setColorOrder(dai.ColorCameraProperties.ColorOrder.RGB)
camRgb.preview.link(xoutRgb.input)

# Connect to device and start pipeline
with dai.Device(pipeline) as device:
    qRgb = device.getOutputQueue(name="rgb", maxSize=4, blocking=False)
    while True:
        inRgb = qRgb.get()  # blocking call, will wait until a new data has arrived
        frame = inRgb.getCvFrame()
        results = model(frame)
        img = results[0].plot()
        cv2.imshow('YOLOv8 Box Detection' ,img)
        print(results)  # Debug: Print results to inspect

            # Check if there are any detections
        if results[0].boxes is not None:
            # Extract the detections
            detections = results[0].boxes.xyxy.cpu().numpy()  # xyxy format (xmin, ymin, xmax, ymax, confidence, class)
        try:
            for result in results:
                if hasattr(result, 'obb'):
                    x= result.obb.xywhr[0][0] 
                    y= result.obb.xywhr[0][1]
                    w= result.obb.xywhr[0][2]
                    h= result.obb.xywhr[0][3]
                    angle= result.obb.xywhr[0][4]
                    print(f"OBB coordinates: {x}, {y}, {w}, {h} with angle {angle}")
        except:
            print ("no detection")
        # Break the loop on 'q' key press
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cv2.destroyAllWindows()
`

do you have any idea on how to also get the depth when detecting an object? so that it can detect the x y z thank you 

btw this is the result when detecting an object:
![Screenshot 2024-06-19 134315](https://github.com/ultralytics/ultralytics/assets/168053014/4ec69c4a-e8e0-4c95-95cc-dc8c26cf7e3b)

**Comment by glenn-jocher** [comment]
Hello @KennethEladistu,

Thank you for the update and for sharing your current progress. It's great to hear that the bounding boxes are now displaying correctly! Let's work on integrating the depth feature to get the Z-coordinate for your detections.

To achieve this, you need to utilize the depth information from the OAK-D-Pro camera. Here's how you can modify your script to include depth calculations:

1. **Add Depth Stream to the Pipeline**:
   - You need to add the depth stream to your pipeline to get depth information.

2. **Calculate Depth for Detected Objects**:
   - Use the depth information to calculate the Z-coordinate for each detected object.

Here's an updated version of your script with these modifications:

```python
from ultralytics import YOLO
import cv2
import depthai as dai

# Load a pretrained YOLOv8n model
model = YOLO("C:/Users/KennethAaronEladistu/oak_d/oak_d/best.pt")

# Create pipeline
pipeline = dai.Pipeline()

# Define sources and outputs
camRgb = pipeline.create(dai.node.ColorCamera)
xoutRgb = pipeline.create(dai.node.XLinkOut)
xoutRgb.setStreamName("rgb")
camRgb.setPreviewSize(640, 400)
camRgb.setResolution(dai.ColorCameraProperties.SensorResolution.THE_1080_P)
camRgb.setInterleaved(False)
camRgb.setColorOrder(dai.ColorCameraProperties.ColorOrder.RGB)
camRgb.preview.link(xoutRgb.input)

# Define depth sources and outputs
monoLeft = pipeline.create(dai.node.MonoCamera)
monoRight = pipeline.create(dai.node.MonoCamera)
stereo = pipeline.create(dai.node.StereoDepth)
xoutDepth = pipeline.create(dai.node.XLinkOut)
xoutDepth.setStreamName("depth")

# Properties
monoLeft.setResolution(dai.MonoCameraProperties.SensorResolution.THE_400_P)
monoLeft.setBoardSocket(dai.CameraBoardSocket.LEFT)
monoRight.setResolution(dai.MonoCameraProperties.SensorResolution.THE_400_P)
monoRight.setBoardSocket(dai.CameraBoardSocket.RIGHT)
stereo.setDepthAlign(dai.CameraBoardSocket.RGB)
stereo.setOutputSize(monoLeft.getResolutionWidth(), monoLeft.getResolutionHeight())
stereo.setLeftRightCheck(True)
stereo.setSubpixel(False)
stereo.setExtendedDisparity(True)

# Linking
monoLeft.out.link(stereo.left)
monoRight.out.link(stereo.right)
stereo.depth.link(xoutDepth.input)

# Connect to device and start pipeline
with dai.Device(pipeline) as device:
    qRgb = device.getOutputQueue(name="rgb", maxSize=4, blocking=False)
    qDepth = device.getOutputQueue(name="depth", maxSize=4, blocking=False)

    while True:
        inRgb = qRgb.get()  # blocking call, will wait until a new data has arrived
        frame = inRgb.getCvFrame()
        results = model(frame)
        img = results[0].plot()
        cv2.imshow('YOLOv8 Box Detection', img)
        print(results)  # Debug: Print results to inspect

        # Get depth frame
        depthFrame = qDepth.get().getFrame()

        # Check if there are any detections
        if results[0].boxes is not None:
            detections = results[0].boxes.xyxy.cpu().numpy()  # xyxy format (xmin, ymin, xmax, ymax, confidence, class)
            for det in detections:
                xmin, ymin, xmax, ymax, confidence, class_id = det
                if confidence > 0.30:
                    # Calculate depth (Z-coordinate)
                    x_center = int((xmin + xmax) / 2)
                    y_center = int((ymin + ymax) / 2)
                    z = depthFrame[y_center, x_center]
                    print(f"Depth (Z): {z} mm")

                    # Draw bounding box and label
                    cv2.rectangle(frame, (int(xmin), int(ymin)), (int(xmax), int(ymax)), (0, 255, 0), 2)
                    label = f"{model.names[int(class_id)]}: {confidence:.2f}, Z: {z} mm"
                    cv2.putText(frame, label, (int(xmin), int(ymin) - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

        cv2.imshow("OAK-D-Pro Live View", frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cv2.destroyAllWindows()
```

### Key Points:
- **Depth Calculation**: The depth value is retrieved from the depth frame at the center of the bounding box.
- **Depth Display**: The depth (Z-coordinate) is displayed along with the bounding box label.

This should help you get the depth information for each detected object. If you encounter any issues or need further assistance, feel free to ask! 😊

Best of luck with your project!
