### ISSUE TITLE
yolov10-SCDown return error

### ISSUE THREAD

**Issue by pgmsuper** [ultralytics/ultralytics#13774]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

![image](https://github.com/ultralytics/ultralytics/assets/49860192/c2868f96-faab-417c-b11a-b2e4f277736a)
yolov10-SCDown return error，it have 2 return

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@pgmsuper hi there,

Thank you for bringing this to our attention! To assist you effectively, we need a bit more information.

1. **Minimal Reproducible Example**: Could you please provide a minimal code snippet that reproduces the error? This will help us understand the issue better. You can refer to our guide on creating a minimal reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

2. **Environment Details**: Ensure you are using the latest versions of `torch` and `ultralytics`. You can update your packages using the following commands:
   ```bash
   pip install --upgrade torch ultralytics
   ```
   After updating, please try running your code again to see if the issue persists.

Once we have this information, we can investigate further and work towards a solution. Thank you for your cooperation!

**Comment by prammmoe** [comment]
I've also experienced an issue with the SCDown where it returns `AttributeError: Can't get attribute 'SCDown' on <module 'ultralytics.nn.modules.block' from 'C:\\Users\\PC\\AppData\\Roaming\\Python\\Python311\\site-packages\\ultralytics\\nn\\modules\\block.py'>` when I'm trying to predict. I've tried upgrading the ultralytics and torch but still doesn't works. 

![image](https://github.com/ultralytics/ultralytics/assets/95534357/a641ee10-767b-4c7a-9136-18da10293c80)

**Comment by glenn-jocher** [comment]
Hi @prammmoe,

Thank you for reporting this issue and for providing the error message. To help us investigate further, could you please provide a minimal reproducible code example? This will allow us to better understand the context and reproduce the error on our end. You can refer to our guide on creating a minimal reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure you are using the latest versions of `torch` and `ultralytics`. You can update your packages using the following commands:
```bash
pip install --upgrade torch ultralytics
```

If the issue persists after updating, please share the minimal code example, and we'll be happy to assist you further.

Thank you for your cooperation! 😊
