### ISSUE TITLE
High CPU usage with Google Coral tflite model

### ISSUE THREAD

**Issue by n1mda** [ultralytics/ultralytics#13773]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am continuously streaming camera frames from an RTSP camera into a python application.
I am using a `yolov8s_320x320_edgetpu.tflite` model I found online. I have been unable to convert a model myself.
If I use `yolov8s.pt` the object detection is successful on the CPU, and it consumes a lot of CPU % (as expected).
When I use the tflite model inference runs on the Coral (It blinks and inference time is much faster) but the CPU % is still high.
If I uncomment the `self.model.predict()` method the application does not consume as much CPU % so I have confirmed that this CPU usage comes from the `ultralytics` package.

What could be wrong?

```python
import math
from ultralytics import YOLO
from typing import List
from .inference import InferenceInterface, DetectionResult

class UltralyticsInference(InferenceInterface):
    def __init__(self, model_path: str):
        self.model = YOLO(model_path, task="detect")
        self.classes = {
            0: "person",
            2:  "car",
            5:  "bus",
            7:  "truck"
        }
        self.classes_to_detect = list(self.classes.keys())
    
    def run(self, frame) -> List[DetectionResult]:
        results = []
        detections = self.model.predict(frame, conf=0.5, imgsz=320, verbose=False, classes=self.classes_to_detect)
        for detection in detections:
            for box in detection.boxes:
                min_x, min_y, max_x, max_y = box.xyxy[0]
                min_x, min_y, max_x, max_y = int(min_x), int(min_y), int(max_x), int(max_y)
                conf = math.ceil((box.conf[0]*100))
                class_id = int(box.cls)
                class_name = self.classes.get(class_id, "unknown")
                results.append(DetectionResult(
                    label=class_name,
                    confidence=conf,
                    x_min=min_x,
                    y_min=min_y,
                    x_max=max_x,
                    y_max=max_y
                ))
        return results
    
    def stop(self):
        pass
```

The same thing occurs when running the yolo CLI:
`yolo track model=yolov8s.pt source=sample_video.mp4 imgsz=320` (800% CPU)
`Speed: 0.7ms preprocess, 33.6ms inference, 2.4ms postprocess per image at shape (1, 3, 192, 320)`

`yolo track model=yolov8s_320x320_edgetpu.tflite source=sample_video.mp4 imgsz=320` (800% CPU but fast inference)
`Speed: 1.2ms preprocess, 28.9ms inference, 2.7ms postprocess per image at shape (1, 3, 320, 320)`

My host computer is a M1 Macbook.

Download model:
[yolov8s_320x320_edgetpu.tflite.zip](https://github.com/user-attachments/files/15883566/yolov8s_320x320_edgetpu.tflite.zip)

**Comment by glenn-jocher** [comment]
@n1mda hi there! 👋

Thank you for providing a detailed description of your issue along with the code example. It’s very helpful for diagnosing the problem.

### Steps to Troubleshoot High CPU Usage

1. **Verify Package Versions**:
   Ensure you are using the latest versions of `torch` and `ultralytics`. You can upgrade them using:
   ```bash
   pip install --upgrade torch ultralytics
   ```

2. **Model Export**:
   Since you mentioned difficulties in converting the model yourself, I recommend exporting your model using the latest Ultralytics tools. Here’s how you can do it:
   ```python
   from ultralytics import YOLO

   # Load a model
   model = YOLO("yolov8s.pt")  # Load an official model or custom model

   # Export the model to Edge TPU format
   model.export(format="edgetpu")
   ```

3. **Optimize Inference Code**:
   Ensure that the inference code is optimized for the Coral Edge TPU. The `tflite-runtime` should be used instead of `tensorflow` for better performance:
   ```bash
   pip uninstall tensorflow tensorflow-aarch64
   pip install -U tflite-runtime
   ```

4. **Profiling**:
   Profile your code to identify the exact bottleneck. You can use Python’s `cProfile` module to get detailed statistics on where the CPU time is being spent.

5. **Edge TPU Utilization**:
   Ensure that the Coral Edge TPU is being utilized correctly. The high CPU usage might be due to preprocessing or postprocessing steps. You can try to offload some of these tasks to the TPU if possible.

### Example Code for Running Inference
Here’s an example of how you can run inference using the exported Edge TPU model:
```python
from ultralytics import YOLO

# Load the exported Edge TPU model
model = YOLO("path/to/yolov8s_320x320_edgetpu.tflite")

# Run prediction
results = model.predict("path/to/source.png")
```

### Additional Resources
For a more detailed guide on setting up and using the Coral Edge TPU with a Raspberry Pi, please refer to our [Coral Edge TPU on Raspberry Pi Guide](https://docs.ultralytics.com/guides/coral-edge-tpu-on-raspberry-pi/).

If the issue persists after trying these steps, please let us know, and we can further investigate. Your feedback is invaluable in helping us improve our tools and documentation.

Best regards and happy coding! 🚀

**Comment by n1mda** [comment]
Thank you @glenn-jocher 

> ### Steps to Troubleshoot High CPU Usage
> 1. **Verify Package Versions**:
>    Ensure you are using the latest versions of `torch` and `ultralytics`. You can upgrade them using:
>    ```shell
>    pip install --upgrade torch ultralytics
>    ```

I am running the latest version of ultralytics and the version of torch that ultralytics is dependent on.

> 2. **Model Export**:
>    Since you mentioned difficulties in converting the model yourself, I recommend exporting your model using the latest Ultralytics tools. Here’s how you can do it:
>    ```python
>    from ultralytics import YOLO
>    
>    # Load a model
>    model = YOLO("yolov8s.pt")  # Load an official model or custom model
>    
>    # Export the model to Edge TPU format
>    model.export(format="edgetpu")
>    ```

I have successfully done this now in a Google Colab Workspace, it was not possible to do on a Mac.

> 3. **Optimize Inference Code**:
>    Ensure that the inference code is optimized for the Coral Edge TPU. The `tflite-runtime` should be used instead of `tensorflow` for better performance:
>    ```shell
>    pip uninstall tensorflow tensorflow-aarch64
>    pip install -U tflite-runtime
>    ```

tflite-runtime is used and tensorflow is uninstalled.

> 4. **Profiling**:
>    Profile your code to identify the exact bottleneck. You can use Python’s `cProfile` module to get detailed statistics on where the CPU time is being spent.
> 5. **Edge TPU Utilization**:
>    Ensure that the Coral Edge TPU is being utilized correctly. The high CPU usage might be due to preprocessing or postprocessing steps. You can try to offload some of these tasks to the TPU if possible.

I took a video file and manually resized it into 320x320px and then fed that into yolov8. As the model no longer needs to resize the frame(s) CPU drastically dropped.

I then took my original video and resized it myself as a preprocess-step before feeding it into yolov8: `cv2.resize(frame, (320, 320))`.
This too drastically lowered the CPU %.

I believe the resizing method in ultralytics consume much more CPU than a simple resize with opencv. Is there some other pre-processing it does during resize that is resource exhaustive?

**Comment by glenn-jocher** [comment]
Hi @n1mda,

Thank you for the detailed follow-up! It's great to hear that you've successfully exported your model and verified the use of `tflite-runtime`.

### Addressing High CPU Usage During Resizing

Your observation about the high CPU usage during the resizing step is insightful. The Ultralytics library does include additional preprocessing steps beyond a simple resize, which might be contributing to the increased CPU usage. These steps can include normalization, padding, and other transformations to ensure the input data is in the optimal format for the model.

### Custom Preprocessing

To mitigate this, you can indeed handle the resizing and preprocessing manually using OpenCV, as you've already started doing. Here's a concise example of how you can integrate custom preprocessing into your inference pipeline:

```python
import cv2
from ultralytics import YOLO
from typing import List
from .inference import InferenceInterface, DetectionResult

class UltralyticsInference(InferenceInterface):
    def __init__(self, model_path: str):
        self.model = YOLO(model_path, task="detect")
        self.classes = {
            0: "person",
            2: "car",
            5: "bus",
            7: "truck"
        }
        self.classes_to_detect = list(self.classes.keys())
    
    def run(self, frame) -> List<DetectionResult]:
        # Custom preprocessing
        frame_resized = cv2.resize(frame, (320, 320))
        
        results = []
        detections = self.model.predict(frame_resized, conf=0.5, imgsz=320, verbose=False, classes=self.classes_to_detect)
        for detection in detections:
            for box in detection.boxes:
                min_x, min_y, max_x, max_y = box.xyxy[0]
                min_x, min_y, max_x, max_y = int(min_x), int(min_y), int(max_x), int(max_y)
                conf = math.ceil((box.conf[0]*100))
                class_id = int(box.cls)
                class_name = self.classes.get(class_id, "unknown")
                results.append(DetectionResult(
                    label=class_name,
                    confidence=conf,
                    x_min=min_x,
                    y_min=min_y,
                    x_max=max_x,
                    y_max=max_y
                ))
        return results
    
    def stop(self):
        pass
```

### Further Optimization

If you continue to experience high CPU usage, consider the following additional optimizations:
1. **Batch Processing**: If feasible, process multiple frames in a batch to reduce the overhead of individual frame processing.
2. **Asynchronous Processing**: Utilize asynchronous processing to handle preprocessing and inference in parallel, reducing the overall CPU load.

### Profiling

For a deeper dive into where the CPU time is being spent, you can use Python’s `cProfile` module to get detailed statistics. This can help identify other potential bottlenecks in your code.

If you have any further questions or need additional assistance, feel free to ask. We're here to help! 😊
