### ISSUE TITLE
Can .val use test data from custom yaml for evaluation?

### ISSUE THREAD

**Issue by yasinda-s** [ultralytics/ultralytics#13779]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained my model using the following config: 

```
path: /opt/ml/input/data
train: train
val: val

names:
  0: smoke
```
This is so that I train my model on the _train_ dataset whilst validating with my _val_ dataset

However after the model is trained, I want to load it and evaluate (using `model.val()`) it's performance on the test dataset I also have. This is so I can generate the metrics for the test dataset.

How can I do so? I am aware that `model.val()` does not need a data path as it recalls the settings but does that mean I need to mention `test: test` on my config file?

**Comment by glenn-jocher** [comment]
@yasinda-s hello,

Thank you for your question and for providing the configuration details. Yes, you can use the `.val()` method to evaluate your model on a custom test dataset. To do this, you need to specify the `data` argument with the path to your custom YAML file that includes the test dataset.

Here's how you can modify your YAML file to include the test dataset:

```yaml
path: /opt/ml/input/data
train: train
val: val
test: test  # Add this line to include the test dataset

names:
  0: smoke
```

Then, you can use the `model.val()` method and specify the `data` argument to point to this updated YAML file:

```python
from ultralytics import YOLO

# Load your trained model
model = YOLO("path/to/your/trained/model.pt")

# Validate the model on the test dataset
metrics = model.val(data="path/to/your/custom.yaml", split='test')

# Access the metrics
print(metrics.box.map)  # mAP50-95
print(metrics.box.map50)  # mAP50
print(metrics.box.map75)  # mAP75
print(metrics.box.maps)  # List of mAP50-95 for each category
```

By specifying `split='test'`, you ensure that the validation is performed on the test dataset defined in your YAML file.

If you encounter any issues or have further questions, please ensure you are using the latest versions of `torch` and `ultralytics` packages. You can update them using:

```bash
pip install --upgrade torch ultralytics
```

Feel free to reach out if you need any more assistance. Happy validating! 😊
