### ISSUE TITLE
how can i display the bounding box of detection in arabic language 

### ISSUE THREAD

**Issue by 7assanx7** [ultralytics/ultralytics#1377]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The first time I used yolo v5 to detect sign language but when defining the data in config.yaml and training the model when testing the model the label appears in Arabic but the letters are separate

Right now I'm using Yolo v8 but when testing the model the label of signs language appears question marks

so i want to display the output of detection in arabic language

**Comment by glenn-jocher** [comment]
@7assanx7 arabic should work correctly by default, so we may have a bug in YOLOv8. Can you please provide your data.yaml, the example commands you are using and an example of the exact image that the text appears incorrectly in?

**Comment by 7assanx7** [comment]
> @7assanx7 arabic should work correctly by default, so we may have a bug in YOLOv8. ![Screenshot 2023-03-11 221359](https://user-images.githubusercontent.com/118318017/224509680-61281d87-e68c-44b0-9c38-42c020d6903c.png)

![Untitled](https://user-images.githubusercontent.com/118318017/224509519-f36300e1-0cf8-4b5e-bd93-4e09ad0d367f.jpg)

**********************************************************************************************
iam use this code to use model with webcam
`import cv2
import argparse

from ultralytics import YOLO
import supervision as sv

import numpy as np

def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="YOLOv8 live")
    parser.add_argument(
        "--webcam-resolution",
        default=[1280, 720],
        nargs=2,
        type=int
    )
    args = parser.parse_args()
    return args


def main():
    args = parse_arguments()
    frame_width, frame_height = args.webcam_resolution

    cap = cv2.VideoCapture(0)
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, frame_width)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, frame_height)

    #model = YOLO("runs/detect/train37/weights/best.pt")
    model = YOLO(r"E:\GradProject\SignLanguage\best.pt")


    box_annotator = sv.BoxAnnotator(
        thickness=2,
        text_thickness=2,
        text_scale=1
    )

    while True:
        ret, frame = cap.read()
        font = cv2.FONT_HERSHEY_SIMPLEX

        result = model(frame, agnostic_nms=True)[0]
        detections = sv.Detections.from_yolov8(result)
        labels = [
            f"{model.model.names[class_id]} {confidence:0.75f}"
            for _, confidence, class_id, _
            in detections
        ]
        frame = box_annotator.annotate(
            scene=frame,
            detections=detections,
            labels=labels
        )

        cv2.imshow("yolov8", frame)

        if (cv2.waitKey(30) == 27):
            break

if __name__ == "__main__":
    main()`
**********************************************************

**Comment by glenn-jocher** [comment]
@7assanx7 oh I see. We don't assist in debugging custom code. We have automatic webcam inference with `yolo predict source=0`.

**Comment by 7assanx7** [comment]
> @7assanx7 oh I see. We don't assist in debugging custom code. We have automatic webcam inference with `yolo predict source=0`.

![Untitled1](https://user-images.githubusercontent.com/118318017/224563793-7f105823-725b-492b-84a8-8304f2a6f61f.jpg)
Thank you. I have solved the problem of question marks, but the letters are still separated and reversed. They are supposed to be like this (أسوان), but they appear like this (ن ا و س أ)

please i want to fix this iam working on graduation project
