### ISSUE TITLE
Confusion metrix

### ISSUE THREAD

**Issue by berinbalci** [ultralytics/ultralytics#13786]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I couldn't analyze this metric. How can I calculate tp, tn, fp, fn values? 

### Additional

[i
![IMG_4694](https://github.com/ultralytics/ultralytics/assets/165471429/c49e8686-35bf-43c2-9255-318b6ca84554)

**Comment by glenn-jocher** [comment]
@berinbalci hello,

Thank you for reaching out! To analyze the confusion matrix and calculate the true positives (TP), true negatives (TN), false positives (FP), and false negatives (FN), you can follow these steps:

1. **True Positives (TP):** The number of correct predictions that an instance is positive.
2. **True Negatives (TN):** The number of correct predictions that an instance is negative.
3. **False Positives (FP):** The number of incorrect predictions that an instance is positive.
4. **False Negatives (FN):** The number of incorrect predictions that an instance is negative.

In the context of object detection, these values are derived from the bounding box predictions compared to the ground truth boxes.

Here's a simple way to calculate these values using the confusion matrix:

```python
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Example confusion matrix
confusion_matrix = np.array([[50, 10], [5, 35]])

# Extracting TP, TN, FP, FN
TP = confusion_matrix[1, 1]
TN = confusion_matrix[0, 0]
FP = confusion_matrix[0, 1]
FN = confusion_matrix[1, 0]

print(f"True Positives (TP): {TP}")
print(f"True Negatives (TN): {TN}")
print(f"False Positives (FP): {FP}")
print(f"False Negatives (FN): {FN}")

# Visualizing the confusion matrix
sns.heatmap(confusion_matrix, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()
```

If you are using the latest version of the `ultralytics` package, you can generate and visualize the confusion matrix directly using the `model.val()` method, which will save the confusion matrix as an image file. This can help you better understand the performance of your model.

For more detailed information on performance metrics and how to interpret them, you can refer to our [Performance Metrics Guide](https://docs.ultralytics.com/guides/yolo-performance-metrics/).

If you encounter any issues or need further assistance, please ensure you are using the latest versions of `torch` and `ultralytics`. If the problem persists, kindly provide a minimum reproducible example as outlined [here](https://docs.ultralytics.com/help/minimum_reproducible_example) so we can investigate further.

Best regards and happy coding! 😊

The Ultralytics Team
