### ISSUE TITLE
Questions about YOLOv8 positive sample assignment algorithm

### ISSUE THREAD

**Issue by RunXun** [ultralytics/ultralytics#1378]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

After reading the code, I found that YOLOv8 seems to use TaskAlignedAssigner (from TOOD) as the positive sample matching strategy directly from the beginning of model training. yolov8 does not use ATSSAssigner as an aid in the initial training.

YOLOv6 and p-YOLOE both use ATSSAssigner as an aid, I would like to know how yolov8 considers this issue.

**Comment by glenn-jocher** [comment]
@RunXun this is a good question. @Laughing-q might know more about this, but I believe we investigated ATSS and ultimately were not able to produce improvements using it, hence the current TAL implementation.

**Comment by RunXun** [comment]
Thank you very much for your answer.

**Comment by pderrenger** [comment]
@RunXun you're welcome! If you have any more questions or need further assistance, feel free to ask. Happy to help!
