### ISSUE TITLE
Get masks from model output0 and output1

### ISSUE THREAD

**Issue by YoussephAhmed** [ultralytics/ultralytics#13784]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,
I found this issue while searching 
https://github.com/ultralytics/ultralytics/issues/480
but in the discussion it was mentioned that i can get the results.masks from output1 specifically but no code is added can you add the code to do so? 
why I need this?
Because I Deployed the .onnx on triton and only have access to the raw output0 and output1,
Thanks in advance

**Comment by glenn-jocher** [comment]
@YoussephAhmed hello,

Thank you for reaching out! To extract masks from the model outputs when using ONNX with Triton, you can follow the approach below. Assuming `output0` contains the bounding boxes and `output1` contains the masks, you can process these outputs as follows:

1. **Load the ONNX model and perform inference:**
   ```python
   import onnxruntime as ort
   import numpy as np

   # Load the ONNX model
   session = ort.InferenceSession("path/to/your/model.onnx")

   # Prepare your input data
   input_data = {"input_name": np.random.randn(1, 3, 640, 640).astype(np.float32)}

   # Perform inference
   outputs = session.run(None, input_data)
   output0, output1 = outputs[0], outputs[1]
   ```

2. **Process the outputs to extract masks:**
   ```python
   # Assuming output1 contains the masks
   masks = output1  # Process this as needed for your application

   # Example: Convert masks to a more usable format
   masks = np.squeeze(masks)  # Remove unnecessary dimensions if needed
   ```

3. **Visualize or use the masks:**
   ```python
   import matplotlib.pyplot as plt

   # Example: Display the first mask
   plt.imshow(masks[0], cmap='gray')
   plt.show()
   ```

This code snippet provides a basic framework for extracting and visualizing masks from the ONNX model outputs. You may need to adjust the processing steps based on the specific structure of your model's outputs.

If you encounter any issues or need further assistance, please ensure you are using the latest versions of `torch` and `ultralytics`. If the problem persists, providing a minimum reproducible example will help us investigate further. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions. Happy coding! 😊

**Comment by YoussephAhmed** [comment]
Hello @glenn-jocher 
first of all than you for the fast response and for the awesome work,
after I tried your code it does not work as I need:
here is the code I use:
```
        print("inputs.shape: ", inputs.shape)

        infer_input = InferInput('images', inputs.shape, 'FP32')
        infer_input.set_data_from_numpy(inputs)

        output0 = InferRequestedOutput('output0')
        output1 = InferRequestedOutput('output1')

        results = triton_client.infer(model_name='yolov8x-seg', inputs=[infer_input], outputs=[output0,output1], model_version="", timeout=None)

        output0 = results.as_numpy('output0')
        output1 = results.as_numpy('output0')
        
        # Assuming output1 contains the masks
        masks = output1  # Process this as needed for your application
        print("masks.shape: ", masks.shape)
```
and here is the output shapes:
inputs.shape:  (6, 3, 480, 480)
masks.shape:  (6, 116, 4725)
where 6 is my batch size..
I want it to be something like:
Result shape: torch.Size([6,3, 640, 640])
where:

- 6 is the batch size
- 3 is the number of persons 
- 640*640 is the mask dimension 
again thank you very much!

**Comment by glenn-jocher** [comment]
Hello @YoussephAhmed,

Thank you for your kind words and for providing the code snippet and output shapes. It helps a lot in understanding the issue you're facing.

From your description, it looks like you want to reshape the masks to have the dimensions `[batch_size, num_persons, height, width]`. Given your current `masks.shape` of `(6, 116, 4725)`, it seems like the masks need to be reshaped and possibly interpolated to match the desired dimensions.

Here's a code snippet to help you achieve the desired result:

```python
import numpy as np
import torch
import torch.nn.functional as F

# Assuming output1 contains the masks
masks = results.as_numpy('output1')  # Corrected to 'output1'

# Reshape masks to [batch_size, num_persons, height, width]
batch_size, num_masks, mask_size = masks.shape
height, width = 640, 640  # Desired dimensions

# Reshape and interpolate masks
masks = masks.reshape(batch_size, num_masks, int(np.sqrt(mask_size)), int(np.sqrt(mask_size)))
masks = torch.tensor(masks).float()  # Convert to torch tensor
masks = F.interpolate(masks, size=(height, width), mode='bilinear', align_corners=False)

print("masks.shape: ", masks.shape)  # Should be [6, 116, 640, 640]
```

This code snippet reshapes the masks to a 2D square format and then uses bilinear interpolation to resize them to the desired dimensions. Note that the number of masks (116) may need to be adjusted based on your specific use case.

If you continue to experience issues, please ensure you are using the latest versions of `torch` and `ultralytics`. If the problem persists, providing a minimum reproducible example will help us investigate further. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions. Happy coding! 😊

**Comment by YoussephAhmed** [comment]
@glenn-jocher  Hello again,
when corrected to output1 it have the following:
(6, 32, 120, 120) 
and btw it is the same shape shown here
https://github.com/ultralytics/ultralytics/issues/480#issuecomment-1396676782
no I got the following error due to mismatch in shapes from output0 to output1
    batch_size, num_masks, mask_size = masks.shape
ValueError: too many values to unpack (expected 3)
can you edit your code to match the new shape of (6,32,120,120)
Also if u have the post processing needed to convert the 32 masks to the number of persons detected that will help me a lot thanks :)

**Comment by YoussephAhmed** [comment]
Given this code:
    `     masks = results.as_numpy('output1')  # Corrected to 'output1'
        print(masks.shape)

        # Reshape masks to [batch_size, num_persons, height, width]
        batch_size, num_masks, mask_size, mask_size = masks.shape
        height, width = 640, 640  # Desired dimensions

        # Reshape and interpolate masks
        # masks = masks.reshape(batch_size, num_masks, int(np.sqrt(mask_size)), int(np.sqrt(mask_size)))
        masks = torch.tensor(masks).float()  # Convert to torch tensor
        masks = F.interpolate(masks, size=(height, width), mode='bilinear', align_corners=False)

        print("masks.shape: ", masks.shape)  # Should be [6, 116, 640, 640]

        import matplotlib.pyplot as plt

        # Example: Display the first mask
        plt.imshow(masks[0][1], cmap='gray')
        plt.show()`

where masks[0][1]
0: for the first image in the batch
1: for the first filter in the 32 filter
my question is how i can get the final mask out from these 32 masks ?

the print statements outputs are:
inputs.shape:  (6, 3, 480, 480)
(6, 32, 120, 120)
masks.shape:  torch.Size([6, 32, 640, 640])
![image](https://github.com/ultralytics/ultralytics/assets/22798967/dab629f5-0b80-4141-9cc7-d35cba45caff)

also I attached an image of the mask number 1 and it looks like a heatmap or something

**Comment by glenn-jocher** [comment]
Hello @YoussephAhmed,

Thank you for providing the detailed information and the code snippet. It looks like you're on the right track with reshaping and interpolating the masks. To address your question about obtaining the final mask from the 32 masks, you can use a post-processing step to combine these masks. Typically, this involves applying a threshold to each mask and then combining them to form the final mask for each detected object.

Here's an updated version of your code to help you achieve this:

```python
import numpy as np
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

# Assuming output1 contains the masks
masks = results.as_numpy('output1')
print(masks.shape)  # (6, 32, 120, 120)

# Convert to torch tensor and interpolate to the desired size
masks = torch.tensor(masks).float()
masks = F.interpolate(masks, size=(640, 640), mode='bilinear', align_corners=False)
print("masks.shape: ", masks.shape)  # Should be [6, 32, 640, 640]

# Apply a threshold to each mask to create binary masks
threshold = 0.5
binary_masks = (masks > threshold).float()

# Combine the binary masks to form the final mask for each detected object
# Here, we use a simple max operation to combine the masks
final_masks = torch.max(binary_masks, dim=1)[0]

# Visualize the final mask for the first image in the batch
plt.imshow(final_masks[0], cmap='gray')
plt.show()
```

In this code:
1. We apply a threshold to each mask to create binary masks.
2. We combine the binary masks using a simple max operation to form the final mask for each detected object.

This should give you a clearer final mask for each detected object. If you have any further questions or need additional assistance, please let us know. We're here to help! 😊

**Comment by YoussephAhmed** [comment]
inputs.shape:  (6, 3, 480, 480)
(6, 32, 120, 120)
masks.shape:  torch.Size([6, 32, 640, 640])
[          1]
I got the following output with a black mask from im.show although the unique values are 1 only from your code and I added this debugging message of np.unique and I make the threshold higher (0.7)
`
        results = triton_client.infer(model_name='yolov8x-seg', inputs=[infer_input], outputs=[output0, output1], model_version="", timeout=None)
        # Assuming output1 contains the masks
        masks = results.as_numpy('output1')
        print(masks.shape)  # (6, 32, 120, 120)

        # Convert to torch tensor and interpolate to the desired size
        masks = torch.tensor(masks).float()
        masks = F.interpolate(masks, size=(640, 640), mode='bilinear', align_corners=False)
        print("masks.shape: ", masks.shape)  # Should be [6, 32, 640, 640]

        # Apply a threshold to each mask to create binary masks
        threshold = 0.7
        binary_masks = (masks > threshold).float()

        # Combine the binary masks to form the final mask for each detected object
        # Here, we use a simple max operation to combine the masks
        final_masks = torch.max(binary_masks, dim=1)[0]

        print(np.unique(final_masks))

        # Visualize the final mask for the first image in the batch
        plt.imshow(final_masks[0], cmap='gray')
        plt.show()
`

**Comment by YoussephAhmed** [comment]
instead this is the correct output that I want from this code :
`
        results = model.predict(faces, device='cuda', classes=[0], stream=True)
        masks = []
        for result in results:

            if result.masks is None:
                mask = np.zeros_like(faces[0], dtype=np.uint8)
            else:
                segmentation_mask = result.masks.data.cpu().numpy()

                print(segmentation_mask.shape)

                segmentation_mask = segmentation_mask.transpose((1, 2, 0))

                print(segmentation_mask.shape)

                print("type=>", type(segmentation_mask))

                plt.imshow(segmentation_mask[:,:,0], cmap='gray')
                plt.show()
`
![image](https://github.com/ultralytics/ultralytics/assets/22798967/2a4d0983-d784-4c95-91ec-634f05e465ed)

**Comment by glenn-jocher** [comment]
Hello @YoussephAhmed,

Thank you for sharing your detailed observations and the code snippet. It looks like you're aiming to achieve a similar output to what you get from the `model.predict` method in your Triton deployment. Let's refine the approach to ensure the masks are correctly processed and visualized.

Given your requirements, here's an updated version of your code to help you achieve the desired output:

```python
import numpy as np
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

# Assuming output1 contains the masks
masks = results.as_numpy('output1')
print(masks.shape)  # (6, 32, 120, 120)

# Convert to torch tensor and interpolate to the desired size
masks = torch.tensor(masks).float()
masks = F.interpolate(masks, size=(640, 640), mode='bilinear', align_corners=False)
print("masks.shape: ", masks.shape)  # Should be [6, 32, 640, 640]

# Apply a threshold to each mask to create binary masks
threshold = 0.7
binary_masks = (masks > threshold).float()

# Combine the binary masks to form the final mask for each detected object
# Here, we use a simple max operation to combine the masks
final_masks = torch.max(binary_masks, dim=1)[0]

# Ensure the final mask is in the correct format for visualization
final_masks = final_masks.cpu().numpy()

print(np.unique(final_masks))

# Visualize the final mask for the first image in the batch
plt.imshow(final_masks[0], cmap='gray')
plt.show()
```

This code should help you achieve the desired output by:
1. Interpolating the masks to the desired size.
2. Applying a threshold to create binary masks.
3. Combining the binary masks using a max operation.
4. Converting the final masks to a format suitable for visualization.

If you continue to experience issues, please ensure you are using the latest versions of `torch` and `ultralytics`. If the problem persists, providing a minimum reproducible example will help us investigate further. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions. Happy coding! 😊

**Comment by YoussephAhmed** [comment]
I have another question when using your implementation of NMS:
`
        results = triton_client.infer(model_name='yolov8x-seg', inputs=[infer_input], outputs=[output0, output1], model_version="", timeout=None)
    
        output0_results = results.as_numpy('output0')  # (6, 116, 4725)
        output1_reslts = results.as_numpy('output1')  # (6, 32, 120, 120)


        output0_results = torch.from_numpy(output0_results)
        filtered = ops.non_max_suppression(output0_results)
        print(np.array(filtered).shape)`
        print(filtered[0][0])
        
     (6, 300, 6)
tensor([195.8924, 376.5114, 252.3042, 472.1788,   5.8524, 105.0000])

given the return type and shape by non_max_suppression 
    Returns:
        (List[torch.Tensor]): A list of length batch_size, where each element is a tensor of
            shape (num_boxes, 6 + num_masks) containing the kept boxes, with columns
            (x1, y1, x2, y2, confidence, class, mask1, mask2, ...).
    """
    here https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/ops.py#L162
    how could the confidence be larger than 1 here?
    also what is the class of the id=105?

**Comment by YoussephAhmed** [comment]
@glenn-jocher also according to your comment here 
https://github.com/ultralytics/ultralytics/issues/2953#issuecomment-1573030054
is this a correct implementation of the method?
`        results = triton_client.infer(model_name='yolov8x-seg', inputs=[infer_input], outputs=[output0, output1], model_version="", timeout=None)
    
        output0_results = results.as_numpy('output0')  # (6, 116, 4725)
        output1_results = results.as_numpy('output1')  # (6, 32, 120, 120)
        
        # Apply sigmoid to the raw outputs
        output0_results = sigmoid(output0_results)
        output1_results = sigmoid(output1_results)
        
        first_image_data_output0 = output0_results[0]  # Shape: (116, 4725)
        first_image_masks_output1 = output1_results[0]  # Shape: (32, 120, 120)

        boxes = first_image_data_output0[:4]  # Shape: (4, 4725)
        class_confidences = first_image_data_output0[4:84]  # Shape: (80, 4725)
        mask_weights = first_image_data_output0[84:116]  # Shape: (32, 4725)

        no_boxes = mask_weights.shape[1]
        final_masks = np.zeros(first_image_masks_output1.shape[1:], dtype=np.float32)

        for i in range(no_boxes):
            mask = np.zeros_like(first_image_masks_output1[0], dtype=np.float32)
            for j in range(32):
                mask += mask_weights[j, i] * first_image_masks_output1[j]
            final_masks = np.maximum(final_masks, mask)
            final_masks = sigmoid(final_masks)

        # Apply threshold to get binary mask
        binary_mask = (final_masks > 0.5).astype(np.uint8) * 255
        binary_mask = cv2.resize(binary_mask, (640, 640))

        cv2.imwrite(mask_path, binary_mask)`

**Comment by glenn-jocher** [comment]
Hello @YoussephAhmed,

Thank you for your detailed question and for sharing the code snippet. It looks like you're on the right track with your implementation. Let's address your concerns and refine the approach.

### Confidence Values and Class IDs
Regarding the confidence values being larger than 1, this is unusual as confidence scores should typically range between 0 and 1. This might be due to a missing sigmoid activation on the raw outputs. Applying the sigmoid function to the raw outputs should normalize these values.

### Implementation Refinement
Your implementation for generating the final masks seems mostly correct. However, let's ensure that the process is clear and correctly applied. Here's a refined version of your code:

```python
import numpy as np
import torch
import torch.nn.functional as F
import cv2

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Apply sigmoid to the raw outputs
output0_results = sigmoid(output0_results)
output1_results = sigmoid(output1_results)

first_image_data_output0 = output0_results[0]  # Shape: (116, 4725)
first_image_masks_output1 = output1_results[0]  # Shape: (32, 120, 120)

boxes = first_image_data_output0[:4]  # Shape: (4, 4725)
class_confidences = first_image_data_output0[4:84]  # Shape: (80, 4725)
mask_weights = first_image_data_output0[84:116]  # Shape: (32, 4725)

no_boxes = mask_weights.shape[1]
final_masks = np.zeros(first_image_masks_output1.shape[1:], dtype=np.float32)

for i in range(no_boxes):
    mask = np.zeros_like(first_image_masks_output1[0], dtype=np.float32)
    for j in range(32):
        mask += mask_weights[j, i] * first_image_masks_output1[j]
    
    final_masks = np.maximum(final_masks, mask)

final_masks = sigmoid(final_masks)

# Apply threshold to get binary mask
binary_mask = (final_masks > 0.5).astype(np.uint8) * 255
binary_mask = cv2.resize(binary_mask, (640, 640))

cv2.imwrite(mask_path, binary_mask)

print("Mask generation complete.")
```

### Explanation
1. **Sigmoid Activation**: Ensure that the sigmoid function is applied to both `output0_results` and `output1_results` to normalize the values.
2. **Mask Generation**: The loop combines the mask weights with the masks from `output1_results` to generate the final mask.
3. **Thresholding**: Apply a threshold to create a binary mask and resize it to the desired dimensions.

### Debugging High Confidence Values
If you still encounter high confidence values across the entire mask, consider verifying the following:
- Ensure that the raw outputs from the model are correctly processed.
- Check if the mask weights and masks are correctly aligned and combined.

If the issue persists, please provide a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example) to help us investigate further.

Feel free to reach out if you have any more questions. Happy coding! 😊
