### ISSUE TITLE
When I install torch_image, imgsz doesn't work.

### ISSUE THREAD

**Issue by kadirnar** [ultralytics/ultralytics#13796]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I want to add the ultralytics library to the ComfyUI tool. I have to upload images in tensor format. But when I change the imgsz value, it doesn't change. The original image gives you the output value.

### Environment

```
Ultralytics YOLOv8.2.29 🚀 Python-3.10.14 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4090, 24207MiB)
Setup complete ✅ (16 CPUs, 46.9 GB RAM, 1491.2/1832.2 GB disk)

OS                  Linux-6.5.0-35-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.14
Install             pip
RAM                 46.88 GB
CPU                 unknown
CUDA                12.1

matplotlib          ✅ 3.9.0>=3.3.0
opencv-python       ✅ 4.8.0.76>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.3.1+cu121>=1.8.0
torchvision         ✅ 0.18.1+cu121>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 3.3.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 0.2.7>=0.2.5
```

### Minimal Reproducible Example

image.shape: torch.Size([1, 1024, 1024, 3])

```
    def inference(self, model, image, conf=0.25, iou=0.7, imgsz=640, device="cuda:0", half=False, augment=False, agnostic_nms=False):
        yolo_image = image.permute(0, 3,1,2)
        results = model.predict(yolo_image, conf=conf, iou=iou, imgsz=imgsz, device=device, half=half, augment=augment, agnostic_nms=agnostic_nms)[0]

        boxes = results.boxes.xywh
        masks = results.masks

        return (results, image, boxes, masks,)
  ```

### Additional

When I upload an image in str format, the resize value changes. It doesn't change just for torch.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kadirnar hello,

Thank you for reaching out and providing detailed information about the issue you're encountering. It appears that the `imgsz` parameter isn't functioning as expected when you upload images in tensor format.

To better assist you, could you please ensure the following:

1. **Reproducible Code Example**: The provided code snippet is helpful, but could you please share a minimal reproducible example that includes the model loading and any other relevant parts? This will help us replicate the issue on our end. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

2. **Package Versions**: Verify that you are using the latest versions of both `torch` and `ultralytics`. You can upgrade them using the following commands:
    ```bash
    pip install --upgrade torch ultralytics
    ```

Regarding your specific issue with the `imgsz` parameter, it seems that the resizing might not be applied correctly when the input is a tensor. Here’s a quick workaround you can try:

```python
import torch
from ultralytics import YOLO

# Load the model
model = YOLO('yolov8n.pt')

def inference(model, image, conf=0.25, iou=0.7, imgsz=640, device="cuda:0", half=False, augment=False, agnostic_nms=False):
    # Resize the tensor manually
    yolo_image = torch.nn.functional.interpolate(image.permute(0, 3, 1, 2), size=(imgsz, imgsz), mode='bilinear', align_corners=False)
    results = model.predict(yolo_image, conf=conf, iou=iou, imgsz=imgsz, device=device, half=half, augment=augment, agnostic_nms=agnostic_nms)[0]

    boxes = results.boxes.xywh
    masks = results.masks

    return (results, image, boxes, masks)

# Example usage
image = torch.randn(1, 1024, 1024, 3)  # Dummy image tensor
results, image, boxes, masks = inference(model, image)
```

This code manually resizes the tensor before passing it to the `model.predict` function, which should ensure that the `imgsz` parameter is respected.

Please try this and let us know if it resolves the issue. If the problem persists, providing the additional details mentioned above will help us investigate further.

Thank you for your cooperation and understanding. We look forward to your response!

**Comment by kadirnar** [comment]
It worked when I added the torch.nn.function function ❤️  But I would love for it to do the Ultralytics library instead of adding it manually. Installing and running the ComfyUI library can be a bit complicated. I can tell you how to do it if you want. Or you can try uploading a tensor image and changing the image-size values.

logs:
```
0: 640x640 5 persons, 399.2ms
Speed: 4.1ms preprocess, 399.2ms inference, 115.4ms postprocess per image at shape (1, 3, 640, 640)
Prompt executed in 1.63 seconds
got prompt

0: 1024x1024 5 persons, 344.2ms
Speed: 2.1ms preprocess, 344.2ms inference, 6.5ms postprocess per image at shape (1, 3, 1024, 1024)
Prompt executed in 0.49 seconds
got prompt

0: 1280x1280 6 persons, 210.1ms
Speed: 3.5ms preprocess, 210.1ms inference, 9.3ms postprocess per image at shape (1, 3, 1280, 1280)
Prompt executed in 0.42 seconds
```

**Comment by glenn-jocher** [comment]
Hello @kadirnar,

Thank you for the update! I'm glad to hear that the manual resizing with `torch.nn.functional.interpolate` worked for you ❤️.

We understand the convenience of having the Ultralytics library handle the resizing internally, and we appreciate your feedback. This is something we can consider for future updates to improve user experience.

For now, your approach is a solid workaround. If you encounter any further issues or have additional suggestions, please feel free to share them. Your input is invaluable in helping us enhance the library.

Regarding the installation and running of the ComfyUI library, we appreciate your offer to assist. However, we aim to keep our support focused on the Ultralytics library itself. If you have any specific issues or questions related to Ultralytics, please don't hesitate to ask.

Thank you for your understanding and for contributing to the community!
