### ISSUE TITLE
Oriented Bounding box health check

### ISSUE THREAD

**Issue by IgorGoldberg** [ultralytics/ultralytics#13799]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello dear Glen, as always first I want to thank you for your previous quick and professional answers. Thank you!
I have red the https://docs.ultralytics.com/datasets/obb/#dota-dataset-format-to-yolo-obb-format your answer and the explanation regarding how to create labels in yolov8 considering the L2 vs L1 lengths as described there and I thing I understand the point.
But is there actually a way to make sure I did all correct and that  YOLOv8  DOES understand my labels right? Is it only via inferencing or there is a shortcut?
Thank you very much!

**Comment by glenn-jocher** [comment]
@IgorGoldberg hello,

Thank you for your kind words and for reaching out with your question! 😊

To ensure that your Oriented Bounding Box (OBB) labels are correctly formatted and understood by YOLOv8, you can indeed perform a few checks beyond just inferencing. Here are some steps you can follow:

1. **Visualize the Labels**: Before training or inferencing, you can visualize the OBB labels on your images to ensure they are correctly placed. This can be done using a simple script to draw the bounding boxes based on your label files.

    ```python
    import cv2
    import matplotlib.pyplot as plt

    def draw_obb(image_path, label_path):
        image = cv2.imread(image_path)
        with open(label_path, 'r') as file:
            for line in file:
                parts = line.strip().split()
                cls, points = int(parts[0]), list(map(float, parts[1:]))
                points = [(int(points[i] * image.shape[1]), int(points[i+1] * image.shape[0])) for i in range(0, len(points), 2)]
                points = np.array(points, np.int32).reshape((-1, 1, 2))
                cv2.polylines(image, [points], isClosed=True, color=(0, 255, 0), thickness=2)
        plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
        plt.show()

    draw_obb('path/to/your/image.jpg', 'path/to/your/label.txt')
    ```

2. **Run a Small Training Session**: Train your model on a small subset of your dataset and validate the results. This can help you quickly identify any issues with the labels without committing to a full training session.

    ```bash
    yolo detect train data=your_dataset.yaml model=yolov8n-obb.yaml epochs=10 imgsz=640
    ```

3. **Check for Errors in Conversion**: If you converted your dataset from another format (e.g., DOTA to YOLO OBB), ensure that the conversion script ran without errors and that the output files are correctly formatted.

    ```python
    from ultralytics.data.converter import convert_dota_to_yolo_obb
    convert_dota_to_yolo_obb("path/to/DOTA")
    ```

4. **Inference on a Few Samples**: Perform inference on a few sample images to visually inspect the predictions. This can help you confirm that the model is interpreting the labels correctly.

    ```bash
    yolo detect predict model=your_trained_model.pt source='path/to/sample_image.jpg'
    ```

By following these steps, you can confidently verify that your OBB labels are correctly formatted and understood by YOLOv8. If you encounter any issues, please ensure you are using the latest versions of `torch` and `ultralytics` packages. If the problem persists, feel free to share a minimum reproducible example so we can assist you further. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Best of luck with your project, and feel free to reach out if you have any more questions!

**Comment by IgorGoldberg** [comment]
Thank you very much for the answer.
Regarding the first way to check, sounds like a good idea, but are you sure that this way fits specifically for checking the
L2>L1  vs L2<L1 cases?
I am asking this since as far as I remember drawing a polyline with CV2 takes just a point coordinates without any importance which point is a first one, while in yolov8 OBB this seems to be an issue.

**Comment by glenn-jocher** [comment]
Hello @IgorGoldberg,

Thank you for your follow-up! 😊

You're correct that the order of points is crucial for OBBs in YOLOv8, especially for distinguishing between L2 > L1 and L2 < L1 cases. To ensure the correct order, you can modify the visualization script to explicitly handle the point order as defined in your labels.

Here's an updated version of the script that considers the point order:

```python
import cv2
import numpy as np
import matplotlib.pyplot as plt

def draw_obb(image_path, label_path):
    image = cv2.imread(image_path)
    with open(label_path, 'r') as file:
        for line in file:
            parts = line.strip().split()
            cls, points = int(parts[0]), list(map(float, parts[1:]))
            points = [(int(points[i] * image.shape[1]), int(points[i+1] * image.shape[0])) for i in range(0, len(points), 2)]
            points = np.array(points, np.int32).reshape((-1, 1, 2))
            cv2.polylines(image, [points], isClosed=True, color=(0, 255, 0), thickness=2)
    plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    plt.show()

draw_obb('path/to/your/image.jpg', 'path/to/your/label.txt')
```

This script ensures that the points are drawn in the order they appear in your label file, which should help you verify the correct orientation.

If you encounter any issues or need further assistance, please ensure you are using the latest versions of `torch` and `ultralytics`. If the problem persists, providing a minimum reproducible example would be very helpful for us to investigate further. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Best of luck with your project, and feel free to reach out if you have any more questions!

**Comment by Petros626** [comment]
@glenn-jocher sorry, but I compared both test codes for visualizing the labels and both seem to be the same. Is that the intention?

The labels are expected in the typical yolov8 obb format: [cls, x1, y1, x2, y2, x3, y3, x4, y4] , box defined as:
```txt
              Λ YOLOv8 OBB Box (heading direction)
      (x4,y4)---(x1,y1)
         |    |    |
         |    x    |
         |         |
       (x3,y3)---(x2,y2)
```

**Comment by glenn-jocher** [comment]
Thank you for your question. Yes, the labels are expected in the YOLOv8 OBB format `[cls, x1, y1, x2, y2, x3, y3, x4, y4]`. For the L2 > L1 vs. L1 > L2 check, ensure that the points in the label files follow the correct clockwise order as defined in the YOLOv8 OBB specification. You can visualize the labeled boxes using the `rotated=True` option in the `Annotator.box_label()` method, as it explicitly respects the point order and will help verify the correctness of your annotations. For further reference, you can review the documentation here: https://docs.ultralytics.com/reference/utils/plotting/. Let us know if you encounter any issues!

**Comment by Petros626** [comment]
Pedestrian (your code):
![image](https://github.com/user-attachments/assets/47f4c323-2f85-4e0c-9e23-ef0cde0a26fa)
Pedestrian with gt_sampling (your code):
![image](https://github.com/user-attachments/assets/09117929-4936-4384-8b1c-6fe85694ba61)
Pedestrian (my custom vis code):
![image](https://github.com/user-attachments/assets/28d7d6c2-d986-4fa5-8a2b-c8119b18648b)


Seems it worked, without problems. For my opinion the precision of the bounding box is with `OpenCV` better than via `Matplotlib` (a few pixels of Pedestrian example are outside the box, the box coordinates already have an offset of 0.3 in length and width)

**Comment by glenn-jocher** [comment]
@Petros626 thank you for sharing your results and observations. It's great to hear that the visualization worked well for your KITTI BEV images. OpenCV can indeed provide more precise pixel-level rendering compared to Matplotlib due to differences in how they handle coordinates and scaling. If you prefer higher precision for your use case, OpenCV is an excellent choice. Let us know if you have any further questions!

**Comment by glenn-jocher** [comment]
@Petros626 to visualize validation results in `xywhr` format, you can use the following approach:

```python
import cv2
import numpy as np
from ultralytics.utils.plotting import Annotator, colors

def draw_xywhr_boxes(image_path, xywhr_results):
    image = cv2.imread(image_path)
    ann = Annotator(image)
    
    for result in xywhr_results:
        x_center, y_center, width, height, rotation = result[:5]
        conf = result[5] if len(result) > 5 else 1.0
        cls = int(result[6]) if len(result) > 6 else 0
        
        # Convert xywhr to 4-point format
        cos_r, sin_r = np.cos(rotation), np.sin(rotation)
        corners = np.array([
            [-width/2, -height/2], [width/2, -height/2],
            [width/2, height/2], [-width/2, height/2]
        ])
        
        # Rotate and translate
        rot_matrix = np.array([[cos_r, -sin_r], [sin_r, cos_r]])
        rotated_corners = corners @ rot_matrix.T
        final_corners = rotated_corners + [x_center, y_center]
        
        label = f"cls{cls} {conf:.2f}"
        ann.box_label(final_corners, label, color=colors(cls, True), rotated=True)
    
    return ann.result()
```

This converts the `xywhr` format to the 4-point format that the Annotator expects for rotated boxes.
