### ISSUE TITLE
Address Discord badge error

### ISSUE THREAD

**Issue by Burhan-Q** [ultralytics/ultralytics#13801]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Discord badge in Readme and Docs site is showing (static screenshot):
![image](https://github.com/ultralytics/ultralytics/assets/62214284/e04c7d5f-586e-4532-a014-1a4920f90aaa)
for some time. Here's a live preview:
<a href="https://ultralytics.com/discord"><img alt="Ultralytics Discord" src="https://img.shields.io/discord/1089800235347353640?logo=discord&logoColor=white&label=Discord&color=blue"></a>

This is using `shields.io/discord` and it seems that they've been seeing this issue on their platform for a while, according to this issue https://github.com/badges/shields/issues/10223

We need to establish a viable replacement option for this badge.

## Shield
![Discord shield](https://discordapp.com/api/guilds/1089800235347353640/widget.png?style=shield)
## Banner 1
![Discord banner1](https://discordapp.com/api/guilds/1089800235347353640/widget.png?style=banner1)
## Banner 2
![Discord banner2](https://discordapp.com/api/guilds/1089800235347353640/widget.png?style=banner2)
## Banner 3
![Discord banner3](https://discordapp.com/api/guilds/1089800235347353640/widget.png?style=banner3)
## Banner 4
![Discord banner4](https://discordapp.com/api/guilds/1089800235347353640/widget.png?style=banner4)

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Burhan-Q my goodness. Ok thanks for the options here!
