### ISSUE TITLE
Is OBB available for yolov9 and v10 ?

### ISSUE THREAD

**Issue by QuantumForgeEngineer** [ultralytics/ultralytics#13829]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello everyone, 

I checked the cfg folder and I did not find a OBB config file for yolov9. Does it mean that there is no OBB support for higher versions of yolo ?

Thanks

**Comment by glenn-jocher** [comment]
@QuantumForgeEngineer hello,

Thank you for your question! Currently, Oriented Bounding Boxes (OBB) support is available for YOLOv8 models, specifically with the `-obb` suffix (e.g., `yolov8n-obb.pt`). These models are pretrained on the DOTAv1 dataset and are designed to provide more accurate localization of objects by including orientation information.

As of now, there is no official OBB support for YOLOv9 and YOLOv10 models. The OBB functionality has been specifically developed and optimized for YOLOv8. If you are looking to use OBB for your projects, I recommend using the YOLOv8-OBB models.

If you have any further questions or need assistance with YOLOv8-OBB, feel free to ask! 😊

**Comment by curtis18** [comment]
Hello @glenn-jocher @QuantumForgeEngineer, for YOLOv10 OBB, it is available on https://github.com/hamhanry/YOLOv10-OBB

**Comment by curtis18** [comment]
@glenn-jocher Thanks for your update and hope official OBB support of YOLOv10 will come soon.

**Comment by glenn-jocher** [comment]
Thank you for your interest! Currently, OBB support is officially available for YOLOv8. Please stay tuned to the Ultralytics documentation and updates for any future enhancements.

**Comment by QuantumForgeEngineer** [comment]
> Hello @glenn-jocher @QuantumForgeEngineer, for YOLOv10 OBB, it is available on https://github.com/hamhanry/YOLOv10-OBB

I'll give it a try

**Comment by glenn-jocher** [comment]
@QuantumForgeEngineer for implementing OBB on YOLOv10, I recommend reaching out directly to the repository's maintainer for specific guidance, as the official Ultralytics support for OBB is currently limited to YOLOv8.

**Comment by QuantumForgeEngineer** [comment]
> @QuantumForgeEngineer for implementing OBB on YOLOv10, I recommend reaching out directly to the repository's maintainer for specific guidance, as the official Ultralytics support for OBB is currently limited to YOLOv8.

It seems that yolov11 has the OBB feature ! I'll try it out. Thanks for this

**Comment by glenn-jocher** [comment]
You're welcome! If you have any questions about YOLOv8 or need further assistance, feel free to ask.
