### ISSUE TITLE
confusion matrix single 

### ISSUE THREAD

**Issue by WeisonWEileen** [ultralytics/ultralytics#13838]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I don't know why My confusion matrix only have one class. I have confirm that the model perform well in realtime test.
![image](https://github.com/ultralytics/ultralytics/assets/124496507/c945c247-b4fd-4068-9cab-31d2bb239739)
however，in my test set, there are actually multiple classes. Did I misunderstand anything？
![image](https://github.com/ultralytics/ultralytics/assets/124496507/01f47d14-ffd8-4ff2-b38a-33a17eacfc80)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @WeisonWEileen,

Thank you for reaching out and providing detailed information about your issue. It looks like you're encountering a problem where your confusion matrix only shows one class despite having multiple classes in your test set.

To help us investigate this further, could you please provide a minimum reproducible code example? This will allow us to better understand the context and reproduce the issue on our end. You can find guidelines on how to create a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the most recent versions of `torch` and `ultralytics`. You can upgrade your packages using the following commands:

```bash
pip install --upgrade torch
pip install --upgrade ultralytics
```

Once you've confirmed that you're on the latest versions, please try running your test again and let us know if the issue persists.

Looking forward to your response!

**Comment by Bhavay-2001** [comment]
Hi @WeisonWEileen, If I understood this correctly, you are saying that your confusion matrix is only showing numerical values for the first class i.e. `basket` and not all the classes? If this is your question/issue, then I think the problem lies with your `matplotlib` version. Please check the version of `matplotlib` and it should be `3.7.3`, then it will give you values for all the boxes.
