### ISSUE TITLE
Yolo8-OnnxRuntime-CPP-Inference awful output

### ISSUE THREAD

**Issue by EjenY-Poltavchiny** [ultralytics/ultralytics#13836]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

I'm new to CV, so i decided to  begin with model inferencing. Due to the fact that I am using c++ language, your examples came in handy. But from the start i faced this kind of problem. I'm trying to run [this example](https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-ONNXRuntime-CPP).
![image](https://github.com/ultralytics/ultralytics/assets/105213181/e4081b73-eb03-4028-9ac1-eb077c9df78e)
I have a lot of outputs like this. And (kind of strange) other models (of course after some size/classes manipultaions) give me the same...
I want to run inferences with CPU, so i just running your code.
I've decided not to clone the whole repo, but only this example. I've installed `openCV` with this command
```bash
opencv_ver=4.5.4
wget -O opencv-${opencv_ver}.zip https://github.com/opencv/opencv/archive/${opencv_ver}.zip && \
    wget -O opencv_contrib-${opencv_ver}.zip https://github.com/opencv/opencv_contrib/archive/${opencv_ver}.zip && \
    unzip opencv-${opencv_ver}.zip && \
    unzip opencv_contrib-${opencv_ver}.zip && \
    mkdir opencv-${opencv_ver}/build && cd opencv-${opencv_ver}/build && \
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D INSTALL_C_EXAMPLES=OFF \
    -D WITH_OPENCL=OFF \
    -D WITH_OPENJPEG=OFF \
    -D WITH_JASPER=OFF \
    -D WITH_OPENEXR=OFF \
    -D WITH_V4L=OFF \
    -D WITH_FFMPEG=ON \
    -D WITH_GSTREAMER=OFF \
    -D BUILD_JAVA=OFF \
    -D BUILD_TESTS=OFF \
    -D ENABLE_FAST_MATH=1 \
    -D CUDA_FAST_MATH=1 \
    -D OPENCV_EXTRA_MODULES_PATH=/opencv_contrib-${opencv_ver}/modules \
    -D HAVE_opencv_python3=ON \
    -D BUILD_EXAMPLES=OFF .. && \
    make install -j12 && \
    ldconfig && \
    rm -rf /opencv-${opencv_ver}.zip /opencv_contrib-${opencv_ver}.zip \
    /opencv-${opencv_ver} /opencv_contrib-${opencv_ver}
```
Also i've installed `OnnxRuntime` v1.18.0 according to [this](https://stackoverflow.com/questions/63420533/setting-up-onnx-runtime-on-ubuntu-20-04-c-api) manual. 
I have no build or runtime problems (i guess so), just this type of outputs.
Could you help me with this problem please?

### Environment

Ultralytics YOLOv8.2.36 🚀 Python-3.8.10 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060, 12036MiB)
Setup complete ✅ (16 CPUs, 31.2 GB RAM, 451.3/456.9 GB disk)

OS                  Linux-5.4.0-176-generic-x86_64-with-glibc2.29
Environment         Linux
Python              3.8.10
Install             pip
RAM                 31.20 GB
CPU                 AMD Ryzen 7 5700G with Radeon Graphics
CUDA                12.1

numpy               ✅ 1.24.4<2.0.0
matplotlib          ✅ 3.7.5>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 5.3.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.3.1>=1.8.0
torchvision         ✅ 0.18.1>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.5.1
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi @EjenY-Poltavchiny,

Thank you for reaching out and providing detailed information about your setup and the issue you're encountering. Let's work through this together to get your YOLOv8 ONNXRuntime CPP inference running smoothly.

### Steps to Troubleshoot

1. **Minimum Reproducible Example**:
   To better understand and reproduce the issue, could you please provide a minimal reproducible example of your code? This will help us investigate the problem more effectively. You can refer to our [Minimum Reproducible Example Guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details on how to create one.

2. **Verify Versions**:
   Ensure you are using the latest versions of `torch` and `ultralytics`. You can update them using the following commands:
   ```bash
   pip install --upgrade torch ultralytics
   ```

3. **Check ONNX Model**:
   Verify that the ONNX model you are using is correctly exported and compatible with the ONNXRuntime. You can do this by running a simple inference in Python to ensure the model outputs are as expected.

4. **ONNXRuntime and OpenCV Installation**:
   Your installation steps for OpenCV and ONNXRuntime look comprehensive. However, ensure that all dependencies are correctly installed and there are no version mismatches. Sometimes, using a virtual environment can help isolate and manage dependencies better.

### Example Code for Verification

Here’s a basic example to verify the ONNX model inference in Python before moving to C++:

```python
import onnxruntime as ort
import numpy as np
import cv2

# Load the ONNX model
session = ort.InferenceSession("path/to/your/model.onnx")

# Prepare an input image
image = cv2.imread("path/to/your/image.jpg")
input_image = cv2.resize(image, (640, 640))  # Resize to model input size
input_image = input_image.transpose(2, 0, 1)  # Convert to CHW format
input_image = input_image[np.newaxis, :, :, :].astype(np.float32)  # Add batch dimension

# Run inference
outputs = session.run(None, {"images": input_image})

# Process outputs
print(outputs)
```

If the outputs are as expected in Python, the issue might be specific to the C++ implementation or environment setup.

### Additional Resources

For further troubleshooting, you can refer to our [Common Issues Guide](https://docs.ultralytics.com/guides/yolo-common-issues/), which covers a wide range of potential problems and their solutions.

Please provide the minimal reproducible example and let us know if updating the packages resolves the issue. We're here to help!

**Comment by EjenY-Poltavchiny** [comment]
Hi there!
Thanks for quick respond. With your script I've compared `python` and `C++` outputs and understood the essence of the bug. The problem was connected with postprocessing. I should've use transpose to result matrix (in your code there was commended line):
```c++
rawData = rawData.t(); 
```
Also i had to change output cv::Mat structure (its shape). After all of that your `yolov8n` shows beautiful output. Like this:
![image](https://github.com/ultralytics/ultralytics/assets/105213181/de0851a9-922c-42cf-ae97-dcaec34ed328)

**Comment by glenn-jocher** [comment]
@EjenY-Poltavchiny hi there!

I'm glad to hear that you resolved the issue with the postprocessing and that your `yolov8n` model is now producing beautiful outputs! 🎉

Regarding your new question about handling different confidence thresholds for various classes during postprocessing, you can achieve this by applying class-specific thresholds after obtaining the raw outputs from the model. Here's a concise example to illustrate this in C++:

### Example Code for Class-Specific Confidence Thresholds

```cpp
#include <opencv2/opencv.hpp>
#include <vector>

// Assuming `detections` is a vector of detected objects with their class IDs and confidence scores
std::vector<cv::Rect> applyClassSpecificThresholds(const std::vector<cv::Rect>& detections, const std::vector<int>& classIds, const std::vector<float>& confidences, const std::vector<float>& classThresholds) {
    std::vector<cv::Rect> filteredDetections;

    for (size_t i = 0; i < detections.size(); ++i) {
        int classId = classIds[i];
        float confidence = confidences[i];

        // Apply class-specific confidence threshold
        if (confidence >= classThresholds[classId]) {
            filteredDetections.push_back(detections[i]);
        }
    }

    return filteredDetections;
}

int main() {
    // Example usage
    std::vector<cv::Rect> detections;  // Your detections
    std::vector<int> classIds;         // Class IDs for each detection
    std::vector<float> confidences;    // Confidence scores for each detection
    std::vector<float> classThresholds = {0.5, 0.6, 0.7};  // Example thresholds for 3 classes

    std::vector<cv::Rect> filteredDetections = applyClassSpecificThresholds(detections, classIds, confidences, classThresholds);

    // Process filteredDetections as needed
    return 0;
}
```

In this example, `classThresholds` is a vector where each index corresponds to a class ID and its associated confidence threshold. The `applyClassSpecificThresholds` function filters the detections based on these thresholds.

For more detailed guidance, you can refer to the [Ultralytics documentation](https://docs.ultralytics.com) and explore the sections on postprocessing and custom inference logic.

Feel free to reach out if you have any more questions. Happy coding! 😊

**Comment by EjenY-Poltavchiny** [comment]
Thank you for help !!!

**Comment by glenn-jocher** [comment]
Hi @EjenY-Poltavchiny,

You're very welcome! 😊 I'm glad to hear that the adjustments to the postprocessing resolved your issue and that you're now seeing great results with your `yolov8n` model.

### Handling Class-Specific Confidence Thresholds

To address your question about applying different confidence thresholds for various classes during postprocessing, here's a concise approach you can implement in C++:

```cpp
#include <opencv2/opencv.hpp>
#include <vector>

// Function to apply class-specific confidence thresholds
std::vector<cv::Rect> applyClassSpecificThresholds(const std::vector<cv::Rect>& detections, const std::vector<int>& classIds, const std::vector<float>& confidences, const std::vector<float>& classThresholds) {
    std::vector<cv::Rect> filteredDetections;

    for (size_t i = 0; i < detections.size(); ++i) {
        int classId = classIds[i];
        float confidence = confidences[i];

        // Apply class-specific confidence threshold
        if (confidence >= classThresholds[classId]) {
            filteredDetections.push_back(detections[i]);
        }
    }

    return filteredDetections;
}

int main() {
    // Example usage
    std::vector<cv::Rect> detections;  // Your detections
    std::vector<int> classIds;         // Class IDs for each detection
    std::vector<float> confidences;    // Confidence scores for each detection
    std::vector<float> classThresholds = {0.5, 0.6, 0.7};  // Example thresholds for 3 classes

    std::vector<cv::Rect> filteredDetections = applyClassSpecificThresholds(detections, classIds, confidences, classThresholds);

    // Process filteredDetections as needed
    return 0;
}
```

This code snippet demonstrates how to filter detections based on class-specific confidence thresholds. Adjust the `classThresholds` vector to match the thresholds for your specific classes.

If you encounter any further issues or have additional questions, please don't hesitate to ask. We're here to help!
