### ISSUE TITLE
How to add the bounding box values to the labels text files during prediction with a trained YOLO-V8 instance segmentation model?  

### ISSUE THREAD

**Issue by sivaramakrishnan-rajaraman** [ultralytics/ultralytics#13845]
Hi, 
I am using the CLI to predict on the test data using the saved weights of a YOLO-V8n instance segmentation model. 

`!yolo task=segment mode=predict model='/weights/best.pt' conf=0.25 source='/test/images' imgsz=1024 save=True save_txt=True save_conf=True`

The label files contain the class index followed by the polygonal coordinates and finally the confidence score of the bounding box predictions. However, I would also like to include the bounding box coordinates, that is, x-center, y-center, width, height to each of the labels file since I would like to use these bounding box coordinates later for post-processing. A sample label file content looks like this:

`0 0.21582 0.0898438 0.214844 0.0908203 0.213867 0.0908203 0.210938 0.09375 0.210938 0.0947266 0.203125 0.102539 0.203125 0.103516 0.201172 0.105469 0.200195 0.105469 0.199219 0.106445 0.199219 0.113281 0.200195 0.114258 0.200195 0.115234 0.203125 0.115234 0.204102 0.116211 0.223633 0.116211 0.224609 0.117188 0.227539 0.117188 0.228516 0.118164 0.230469 0.118164 0.231445 0.119141 0.234375 0.119141 0.235352 0.120117 0.248047 0.120117 0.249023 0.121094 0.251953 0.121094 0.25293 0.12207 0.254883 0.0927734 0.260742 0.0917969 0.256836 0.0917969 0.255859 0.0908203 0.233398 0.0908203 0.232422 0.0898438 0.910849`

I am not saving the predictions to any 'result' variable here and I am running the predictions only in the CLI.

**Comment by glenn-jocher** [comment]
@sivaramakrishnan-rajaraman hi there,

Thank you for reaching out! To include bounding box coordinates (x-center, y-center, width, height) in the label files during prediction with your YOLOv8 instance segmentation model, you can modify the code to save these additional details. 

While the CLI currently does not directly support adding bounding box coordinates to the label files, you can achieve this by using the Python API. Below is an example of how you can modify your prediction script to include the bounding box coordinates in the label files:

```python
from ultralytics import YOLO

# Load the model
model = YOLO('/weights/best.pt')

# Run prediction
results = model.predict(source='/test/images', conf=0.25, imgsz=1024, save=True, save_txt=True, save_conf=True)

# Save predictions with bounding box coordinates
for result in results:
    for i, (box, mask, conf, cls) in enumerate(zip(result.boxes.xywh, result.masks.xy, result.boxes.conf, result.boxes.cls)):
        # Prepare the label content
        label_content = f"{int(cls)} " + " ".join(map(str, mask.flatten().tolist())) + f" {conf:.6f} " + " ".join(map(str, box.tolist()))
        
        # Save to file
        label_file = f"{result.path.stem}_{i}.txt"
        with open(label_file, 'w') as f:
            f.write(label_content)
```

This script will save the bounding box coordinates along with the polygonal coordinates and confidence scores in the label files.

If you prefer to stick with the CLI, you might need to run the predictions first and then post-process the results to add the bounding box coordinates to the label files. However, using the Python API as shown above provides a more streamlined approach.

Please ensure you are using the latest versions of `torch` and `ultralytics` to avoid any compatibility issues. You can update your packages using:
```bash
pip install --upgrade torch ultralytics
```

For further details, you can refer to the [Ultralytics documentation](https://docs.ultralytics.com/reference/models/yolo/detect/val/).

Feel free to reach out if you have any more questions. Happy coding! 😊

**Comment by sivaramakrishnan-rajaraman** [comment]
Thanks, it works this way :)

**Comment by glenn-jocher** [comment]
Hi @sivaramakrishnan-rajaraman,

I'm glad to hear that it worked for you! 😊 If you have any more questions or run into any other issues, feel free to reach out. We're here to help!

Happy coding and best of luck with your project!
