### ISSUE TITLE
Yolo8 not using GPU

### ISSUE THREAD

**Issue by Bstrum36** [ultralytics/ultralytics#1384]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm running Windows 10 of an I9 with a 3080 TI GPU

I am using Anaconda with PyCharm  IDE  with Python 3.9

Yolo8 is not using the GPU.

Please advise on what needs to ne done.
Otherwise Yolo8 is running with no issues
THanks.

**Comment by glenn-jocher** [comment]
@Bstrum36 you should just be able to pass device=0 when running a command, i.e.

```
yolo train model=yolov8n.pt device=0
```

**Comment by mareksubocz** [comment]
> @Bstrum36 you should just be able to pass device=0 when running a command, i.e.
> 
> ```
> yolo train model=yolov8n.pt device=0
> ```

is there a way to do it in pytorch code?

**Comment by glenn-jocher** [comment]
@mareksubocz yes:

```python
from ultralytics import YOLO

model = YOLO('yolov8n.pt')
model('https://ultralytics.com/images/bus.jpg', device=0)
```

**Comment by mareksubocz** [comment]
It didn't work for me, but I updated the library and not it's all good, thank you :)

**Comment by Bstrum36** [comment]
When you said you "updated the library" what exactly did you do? Thanks

**Comment by glenn-jocher** [comment]
```pip install -U ultralytics```

**Comment by Bstrum36** [comment]
Thanks!

**Comment by Bstrum36** [comment]
I am still not utilizing the GPU.

I ran the requirements.tx form pip, the results where all requirements met.
I uninstalled and reinstalled  the ultralytics package, still no GPU.

Is there an anaconda compatible utralytics package?

mage 1/1 C:\Users\User\Project1\soccer.jpg: 448x640 5 persons, 1 sports
ball, 91.1ms
Speed: 1.0ms preprocess, 91.1ms inference, 3.0ms post process per image at
shape (1, 3, 640, 640)

I am planning a three article series on Yolov8 with a very slick user
interface

[image: image.png]
Next step here are transparent masks.

[image: image.png]
Contours and data points.  I will have some make it easy helper functions.
I convess I was tortured trying to get the segment data.  I suggest a
tutorial
[image: image.png]
[image: image.png]
The slider control of confidence and IOU provides real time interaction
with the detections.  This one was done with yolv3 so no segmenting

I hope to provide workflow examples that result in the creation of
super-scaled .masked clip art.
The example above interfaced with a face detector and manage predictor
(just for fun)

I want to build a "swiss army knife" of computer vision utilities
all sitting on ultralytics.
I really want the GPU to be accessible.
I will be adding model selection, segmentation and mask output.

And as a final thought:
Mask Data tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],

What is this data and how would one use it?

Thank

**Comment by glenn-jocher** [comment]
@Bstrum36 if you are having issues locally you can get started with one of the official environments below.

## Environments

YOLOv8 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/GCP-Quickstart)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/AWS-Quickstart)
- **Docker Image**. See [Docker Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

**Comment by Bstrum36** [comment]
Not quite the answer I was looking for.
I'm running on a windows 10 I9 with a GTX 3080 TI

What should I be looking for as a cause of the problem.

**Comment by TTAyanlade** [comment]
Hey @Bstrum36 I believe the most probable reason your training is not using gpu if you have one and have done everything as recommended is because your training images are very large, causing a bottle neck in the data loading process. 

You can use pillow to resize all images to (640,640) then retrain. I am sure you'd see a significant in training speed.

PS: You can run your python code in background and use nvidia-smi to track gpu usage before and after implementing my answer to confirm if you see full utilization of gpu
