### ISSUE TITLE
Replace confidence score for forward pass for. yolov8. Default is 0.25

### ISSUE THREAD

**Issue by jurijsnazarovsambientai** [ultralytics/ultralytics#13850]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, when I run youlo model forward pass, to make a prediction as this: 
```bash
self.model = YOLO(model_path, task="detect")
result = self.model(images, verbose=False)
```
Then the smallest confidence score in my result is 0.25. Is there a way to use direct forward pass with `self.model(images)` and still provide a confidence score, instead of using `self.model.predict`?

**Comment by glenn-jocher** [comment]
@jurijsnazarovsambientai hello,

Thank you for reaching out! To adjust the confidence score threshold for predictions directly in the forward pass, you can modify the `conf` parameter within the `predict` method. However, if you want to set this parameter during the model initialization or forward pass, you can do so by specifying it in the `predict` method call.

Here's an example of how you can achieve this:

```python
from ultralytics import YOLO

# Load the model
self.model = YOLO(model_path, task="detect")

# Run the forward pass with a custom confidence threshold
result = self.model.predict(images, conf=0.1, verbose=False)
```

In this example, the `conf` parameter is set to `0.1`, which means that only predictions with a confidence score of 0.1 or higher will be included in the results.

If you need further customization or encounter any issues, please ensure you are using the latest versions of `torch` and `ultralytics` packages. You can update them using the following commands:

```bash
pip install --upgrade torch ultralytics
```

If the issue persists, please provide a minimum reproducible code example so we can investigate further. You can refer to our guide on creating a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions or need further assistance. Happy coding! 😊

**Comment by jurijsnazarovsambientai** [comment]
If I don't want to use predict, but direct forward, is that the same? For example:

```bash
from ultralytics import YOLO
self.model = YOLO(model_path, task="detect")
result = self.model(images, conf=0.1, verbose=False)
```

**Comment by glenn-jocher** [comment]
Hello @jurijsnazarovsambientai,

Thank you for your question! If you prefer to use the direct forward pass instead of the `predict` method, you can still achieve the same result by setting the confidence threshold within the forward pass. However, the `conf` parameter is specifically designed for the `predict` method.

To use the direct forward pass and set the confidence threshold, you can modify the model's configuration before running the forward pass. Here's how you can do it:

```python
from ultralytics import YOLO

# Load the model
self.model = YOLO(model_path, task="detect")

# Update the model's confidence threshold
self.model.overrides['conf'] = 0.1  # Set confidence threshold to 0.1

# Run the forward pass
result = self.model(images, verbose=False)
```

This way, you can adjust the confidence threshold for the direct forward pass without using the `predict` method.

If you encounter any issues or need further assistance, please ensure you are using the latest versions of `torch` and `ultralytics`. You can update them using:

```bash
pip install --upgrade torch ultralytics
```

Feel free to reach out if you have any more questions. Happy coding! 😊

**Comment by jurijsnazarovsambientai** [comment]
Thanks!

**Comment by glenn-jocher** [comment]
Hello @jurijsnazarovsambientai,

Thank you for your question! To set the confidence threshold for a direct forward pass without using the `predict` method, you can modify the model's configuration before running the forward pass. Here's how you can do it:

```python
from ultralytics import YOLO

# Load the model
self.model = YOLO(model_path, task="detect")

# Update the model's confidence threshold
self.model.overrides['conf'] = 0.1  # Set confidence threshold to 0.1

# Run the forward pass
result = self.model(images, verbose=False)
```

This approach allows you to adjust the confidence threshold directly within the forward pass.

If you encounter any issues, please ensure you are using the latest versions of `torch` and `ultralytics`. You can update them using:

```bash
pip install --upgrade torch ultralytics
```

If the issue persists, please provide a minimum reproducible code example so we can investigate further. You can refer to our guide on creating a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions. Happy coding! 😊
