### ISSUE TITLE
image 1/1 D:\yolov8\ultralytics-main\ultralytics\assets\bus.jpg: 640x480 (no detections), 510.2ms Speed: 15.5ms preprocess, 510.2ms inference, 18.0ms postprocess per image at shape (1, 3, 640, 480)

### ISSUE THREAD

**Issue by lndabgjk** [ultralytics/ultralytics#13854]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

我的代码：
from ultralytics import YOLO
yolo = YOLO("yolov8n.yaml")
result = yolo(source='ultralytics/assets/bus.jpg')
结果检测不出来，检测的图片就是官网的图片，我使用yolo task=detect mode=predict conf=0.25 model=yolov8n.pt source='ultralytics/assets/bus.jpg'是可以识别成功的，怎么办？
![屏幕截图 2024-06-21 082526](https://github.com/ultralytics/ultralytics/assets/173172283/54461cc8-35f8-434d-882a-5f5d372e1268)
![屏幕截图 2024-06-21 082622](https://github.com/ultralytics/ultralytics/assets/173172283/4e54eead-bda0-4aa0-8b86-67f050f7f26e)

### Environment

Ultralytics YOLOv88.2.38 
python-3.8.19
torch-2.3.1 
CPU 12th Gen Intel(R) Core(TM) i7-12700H   2.30 GHz
 
OS windows11
Environment conda24.5.0
Python 3.8
Not installed git
RAM 16GB
CPU Intel Core(TM) i7-12700H
CUDA None

### Minimal Reproducible Example

from ultralytics import YOLO
yolo = YOLO("yolov8n.yaml")
result = yolo(source='ultralytics/assets/bus.jpg')

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@lndabgjk hello,

Thank you for reaching out and providing detailed information about the issue you're encountering. It appears that you're experiencing a problem with detecting objects using a model built from the `yolov8n.yaml` configuration file, while the pre-trained `yolov8n.pt` model works as expected.

To assist you better, could you please confirm the following:
1. Ensure you are using the latest versions of the `ultralytics` and `torch` packages. You can update them using:
   ```bash
   pip install --upgrade ultralytics torch
   ```

2. Verify that the model built from `yolov8n.yaml` has been trained before making predictions. The `yolov8n.yaml` file only defines the model architecture and does not include pre-trained weights. You need to train the model on a dataset before it can make accurate predictions. Here’s an example of how to train the model:
   ```python
   from ultralytics import YOLO

   # Load a model from YAML and train it
   model = YOLO('yolov8n.yaml')
   model.train(data='coco128.yaml', epochs=100, imgsz=640)
   ```

3. After training, you can then use the trained model to make predictions:
   ```python
   result = model.predict(source='ultralytics/assets/bus.jpg')
   ```

If you have already trained the model and are still facing issues, please provide any additional details or errors you might be encountering. This will help us reproduce the issue and investigate further.

Thank you for your cooperation, and we look forward to resolving this for you! 😊

**Comment by lndabgjk** [comment]
解决了，因为用的pycharm2024版本，配置conda环境时不能直接设置conda环境，于是选择了系统解释器，但是现在我可以直接设置conda环境了，成功运行出想要的结果。

**Comment by glenn-jocher** [comment]
Hello @lndabgjk,

I'm glad to hear that you resolved the issue by configuring the conda environment correctly in PyCharm! 🎉

If you encounter any further questions or need additional assistance, feel free to reach out. We're here to help!

Happy coding! 😊
