### ISSUE TITLE
Inference Time

### ISSUE THREAD

**Issue by NohaAhmad** [ultralytics/ultralytics#1385]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The time logged at inference which is preprocessing + inference + post-processing doesn't match the time calculated using the time module and it's also variant sometimes its 6 msec and others its 12 msec for a fine-tuned yolov8n-cls [classifier] 
This behavior was observed with the 8.0.52 version and wasn't observed with the 8.0.36

Any possible reason for this ?

**Comment by glenn-jocher** [comment]
@NohaAhmad that's because the time module is unreliable for torch profiling. 

See https://discuss.pytorch.org/t/how-to-measure-execution-time-in-pytorch/111458
