### ISSUE TITLE
Superfluous line in Model

### ISSUE THREAD

**Issue by AlexPasqua** [ultralytics/ultralytics#13852]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I believe there might be a superfluous line in [the Model's constructor](https://github.com/ultralytics/ultralytics/blob/ecfcdf12c9841e7fa2cda65d703bb5245def9875/ultralytics/engine/model.py#L145) in `ultralytics/engine/model.py`: `self.task = task` is already executed outside the `if` statement, and `task` is untouched in the meanwhile.

Should this line be removed? (I can do it, in case)

### Additional

I report the snipped here for clarity:
```python
class Model(nn.Module):
    def __init__(
        self,
        model: Union[str, Path] = "yolov8n.pt",
        task: str = None,
        verbose: bool = False,
    ) -> None:
        super().__init__()
        self.callbacks = callbacks.get_default_callbacks()
        self.predictor = None  # reuse predictor
        self.model = None  # model object
        self.trainer = None  # trainer object
        self.ckpt = None  # if loaded from *.pt
        self.cfg = None  # if loaded from *.yaml
        self.ckpt_path = None
        self.overrides = {}  # overrides for trainer object
        self.metrics = None  # validation/training metrics
        self.session = None  # HUB session
        self.task = task  # task type
        model = str(model).strip()

        # Check if Ultralytics HUB model from https://hub.ultralytics.com
        if self.is_hub_model(model):
            # Fetch model from HUB
            checks.check_requirements("hub-sdk>=0.0.6")
            self.session = self._get_hub_session(model)
            model = self.session.model_file

        # Check if Triton Server model
        elif self.is_triton_model(model):
            self.model_name = self.model = model
            self.task = task
            return
```
As you can see, `self.task = task` is already executed in the first group of instructions in the constructor, before the `if-elif` statement, but then also within the `elif`.

**Comment by glenn-jocher** [comment]
@AlexPasqua hi there,

Thank you for bringing this to our attention! You are correct in observing that the line `self.task = task` appears to be redundant within the `elif` block, as it is already set earlier in the constructor. 

To ensure we maintain clean and efficient code, it would be beneficial to remove this superfluous line. If you would like to contribute by making this change, we would greatly appreciate it! You can submit a pull request, and our team will review it promptly.

Here's a quick guide on how to submit a pull request:
1. Fork the repository.
2. Create a new branch for your changes.
3. Make the necessary edits.
4. Commit your changes with a descriptive message.
5. Push the changes to your fork.
6. Open a pull request from your fork's branch to the main repository.

Thank you again for your keen observation and willingness to contribute! If you have any further questions or need assistance, feel free to ask.
