### ISSUE TITLE
Cannot find custom_tracker.yaml file for object tracking tasks

### ISSUE THREAD

**Issue by ZijueChen** [ultralytics/ultralytics#1386]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello there,

I am trying to use YOLOv8 to do object tracking. I want to add some extra prediction heads on top of the current model. I read the following instruction from the document:

'We also support using a modified tracker config file, just copy a config file i.e custom_tracker.yaml from [ultralytics/tracker/cfg](https://github.com/ultralytics/ultralytics/tree/main/ultralytics/tracker/cfg) and modify any configurations(expect the tracker_type) you need to.'

However, I cannot find this 'custom_tracker.yaml' file from [ultralytics/tracker/cfg]. Where can I find this file?

Thank you very much,
Zijue

**Comment by AyushExel** [comment]
There is no custom_tracker.yaml present. That's just an example name. You can basically create a file with its own config based on the other 2 configs present here and pass that as your custom tracker if needed https://github.com/ultralytics/ultralytics/tree/main/ultralytics/tracker/cfg

**Comment by ZijueChen** [comment]
Thanks for your reply. If I understand correctly, these config files only
define the tracker (mainly the threshold). However, I'd like to change the
structure of the prediction branches (add extra branches to predict more
features of the objects, e.g. velocity prediction). Could you please let me
know which file I should modify to change the model structure?

Thank you very much.
