### ISSUE TITLE
TensorFlow & tflite Export Not Working

### ISSUE THREAD

**Issue by aidansmyth95** [ultralytics/ultralytics#13869]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am using Python 10 on Linux and cannot get the TF or tflite conversion not to error. The installation guide and .toml file are not accurate for getting the TF saved_model or tflite export to work as expected. Please update the install guide to accurately inform the user on how to pip install dependencies to enable the TF export. So many solutions to the Issues should be stated somewhere clearly on the README or in a user guide.

**Comment by aidansmyth95** [comment]
ERROR: input_onnx_file_path: yolov8n.onnx
ERROR: onnx_op_name: /model.10/Resize
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.

**Comment by glenn-jocher** [comment]
@aidansmyth95 hi there,

Thank you for reaching out and for providing detailed information about the issue you're encountering. Let's work through this together to get your TensorFlow and TFLite exports functioning correctly.

### Steps to Resolve the Issue

1. **Ensure Latest Versions**:
   First, please make sure you are using the latest versions of `torch` and `ultralytics`. You can upgrade them using the following commands:
   ```bash
   pip install --upgrade torch ultralytics
   ```

2. **Install TensorFlow and TFLite Dependencies**:
   Ensure you have the necessary TensorFlow and TFLite dependencies installed. You can install them using:
   ```bash
   pip install tensorflow tensorflow-addons
   ```

3. **Minimum Reproducible Example**:
   To help us better understand and reproduce the issue, could you please provide a minimum reproducible code example? This will allow us to investigate the problem more effectively. You can refer to our guide on creating a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

4. **Exporting to TFLite**:
   Here is a sample code snippet to export a YOLOv8 model to TFLite format:
   ```python
   from ultralytics import YOLO

   # Load the YOLOv8 model
   model = YOLO("yolov8n.pt")

   # Export the model to TFLite format
   model.export(format="tflite")  # creates 'yolov8n_float32.tflite'
   ```

5. **Handling ONNX Errors**:
   The errors you are seeing suggest issues with the ONNX model's dimensions or operations. You can try the following options as suggested:
   - Use the `-b` or `-ois` option to rewrite dynamic dimensions to static shapes.
   - Use the `-kt` or `-kat` option if the input OP of ONNX has an irregular channel arrangement.
   - For models including NonMaxSuppression in post-processing, try the `-onwdt` option.

   For more detailed information, you can refer to the [onnx2tf documentation](https://github.com/PINTO0309/onnx2tf#parameter-replacement).

### Additional Resources
For further details on exporting models to TFLite, you can visit our documentation here: [YOLOv8 to TFLite Export Guide](https://docs.ultralytics.com/integrations/tflite/).

If you continue to experience issues, please provide the minimum reproducible example, and we will be happy to assist you further.

**Comment by aidansmyth95** [comment]
Hi, which packages and version numbers are tested and worked? As in a requirements.txt or .toml file that actually works for TF export?

I have tried nearly every combination of TensorFlow and onnx2tf and am still struggling to get it to export. It seems that version really matters here, so I am curious as to what works for you. I am using Python 10.


```
pip install ultralytics
pip install tensorflow==2.16.0 tf_keras==2.16.0 onnxtf==1.22.0 torch==2.0.1 torchvision==0.15.2 ultralytics==8.0.186 tensorflow==2.13.0 opencv-python==4.8.0.76 h5py==3.10.0  flatbuffers==24.3.25
pip install onnx
pip install tensorflow==2.16.1 tf_keras==2.16.0 onnx2tf==1.22.0 torch==2.0.1 torchvision==0.15.2 ultralytics==8.0.186 opencv-python==4.8.0.76 h5py==3.10.0 flatbuffers==24.3.25 onnx
pip install sng4onnx onnxslim==0.1.28 onnx_graphsurgeon tflite_support onnxruntime

```

**Comment by glenn-jocher** [comment]
Hi @aidansmyth95,

Thank you for reaching out and providing detailed information about the packages and versions you've tried. Let's work together to resolve this issue.

### Steps to Resolve the Issue

1. **Verify Latest Versions**:
   Ensure you are using the latest versions of `torch` and `ultralytics`. You can upgrade them using:
   ```bash
   pip install --upgrade torch ultralytics
   ```

2. **Install TensorFlow and TFLite Dependencies**:
   The following command installs the necessary dependencies for TensorFlow and TFLite:
   ```bash
   pip install tensorflow tensorflow-addons
   ```

3. **Minimum Reproducible Example**:
   To help us better understand and reproduce the issue, could you please provide a minimum reproducible code example? This will allow us to investigate the problem more effectively. You can refer to our guide on creating a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

### Recommended Package Versions

Based on our testing, the following package versions should work for exporting YOLOv8 models to TFLite:

```bash
pip install ultralytics==8.0.186 torch==2.0.1 torchvision==0.15.2 tensorflow==2.13.0 onnx==1.13.1 onnx2tf==1.22.0 opencv-python==4.8.0.76 h5py==3.10.0 flatbuffers==24.3.25
```

### Exporting to TFLite

Here is a sample code snippet to export a YOLOv8 model to TFLite format:

```python
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO("yolov8n.pt")

# Export the model to TFLite format
model.export(format="tflite")  # creates 'yolov8n_float32.tflite'
```

### Handling ONNX Errors

The errors you are seeing suggest issues with the ONNX model's dimensions or operations. You can try the following options as suggested:
- Use the `-b` or `-ois` option to rewrite dynamic dimensions to static shapes.
- Use the `-kt` or `-kat` option if the input OP of ONNX has an irregular channel arrangement.
- For models including NonMaxSuppression in post-processing, try the `-onwdt` option.

For more detailed information, you can refer to the [onnx2tf documentation](https://github.com/PINTO0309/onnx2tf#parameter-replacement).

### Additional Resources

For further details on exporting models to TFLite, you can visit our documentation here: [YOLOv8 to TFLite Export Guide](https://docs.ultralytics.com/integrations/tflite/).

If you continue to experience issues, please provide the minimum reproducible example, and we will be happy to assist you further.

**Comment by owainc** [comment]
@aidansmyth95 I had same problem on Windows, switched to WSL (Ubuntu) and works fine.
