### ISSUE TITLE
broken hub link

### ISSUE THREAD

**Issue by ahmadmughees** [ultralytics/ultralytics#13876]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

The Ultralytics hub link has been broken and needs a fix I think.

![image](https://github.com/ultralytics/ultralytics/assets/13232862/54e42900-0424-4861-a0a6-c59ad9b7cbb1)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sergiuwaxmann
