### ISSUE TITLE
Detecting objects on multiple RTSP streams

### ISSUE THREAD

**Issue by PacketTrace** [ultralytics/ultralytics#1387]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I'm working on a project that will allow me to detect several different types of objects in real-time using yolov8 and Python. The idea is that this will be running 24/7 and I'll send a webhook if a certain object is detected. I'm able to load 1 RTSP stream right now and view the output in real-time, but since the results are ongoing my code never gets past the line below:

results = model.predict(source="rtsp://ipaddress:8554/standard", show=True)

The stream loads and overlays the data I need, but I need that data to make it into a variable to hit my first if statement. Should I be thinking about this in a different way? Possibly a while loop?

**Comment by glenn-jocher** [comment]
@PacketTrace you can try `stream=True`, see https://docs.ultralytics.com/modes/predict

**Comment by william-bohannan** [comment]
tried using the documentation, however getting the following error if i switch from input to multiple inputs.

not working: No such file or directory: 'rtsp://user:password@192.168.0.170:554/Streaming/Channels/101/'

```
model = yolo_model(yolo_weight)
input = rtsp_urls[2]                          # works
inputs = [rtsp_urls[1], rtsp_urls[2]]  # not working
results = model(source=inputs, stream=True, verbose=False)
```

**Comment by glenn-jocher** [comment]
Glad to hear that you were able to resolve your issue and use threading to process multiple streams. Regarding your input issue, it seems that the `model()` function may not be able to read your multiple input files properly. Here are a few things to check or try for next time:

1. Make sure that each entry in your `inputs` list points to a valid file or URL. The error message you received suggests that it couldn't find the file `rtsp://user:password @william-bohannan.168.0.170:554/Streaming/Channels/101/`, so it's possible that there's a typo or it's formatted incorrectly.
2. Try passing the `inputs` list directly to `model.predict()` instead of `model()`. For example:
   ```
   model = yolo_model(yolo_weight)
   inputs = [rtsp_urls[1], rtsp_urls[2]]
   results = model.predict(inputs, stream=True, verbose=False)
   ```
   This should give you the same output as calling `model()` with the `source` parameter set to `inputs`.
3. If neither of the above solutions work, it's possible that there's a bug or limitation in the `model()` function. In that case, you could consider breaking the list up into individual streams and processing each with a separate instance of `model()`, as you've done with threading.

I hope this helps, and please don't hesitate to ask if you have any further questions!

**Comment by jsammarco** [comment]
Hi, I'm dealing with the same problem. Seems like the source list option is just chaining.
I recommend opening both streams yourself with OpenCV and then take turns passing frames into the model.
Let me know if anyone knows of a better solution.

**Comment by glenn-jocher** [comment]
@jsammarco hi there! Thank you for sharing your experience with this issue. Although `model()` provides the ability to process multiple inputs with the `source` parameter, it appears that it may not be working as expected in some cases. Your suggestion of using OpenCV to manually open and send frames from each stream to the model separately is a good workaround. This can still be multi-threaded and performant if implemented correctly. However, keep in mind that this approach may not be as convenient as passing a list of sources to `model()`. If anyone has any input or suggestions for a better solution, please chime in. Let us know if you have any further questions or concerns!

**Comment by jsammarco** [comment]
> @jsammarco hi there! Thank you for sharing your experience with this issue. Although `model()` provides the ability to process multiple inputs with the `source` parameter, it appears that it may not be working as expected in some cases. Your suggestion of using OpenCV to manually open and send frames from each stream to the model separately is a good workaround. This can still be multi-threaded and performant if implemented correctly. However, keep in mind that this approach may not be as convenient as passing a list of sources to `model()`. If anyone has any input or suggestions for a better solution, please chime in. Let us know if you have any further questions or concerns!

Thank you Glenn, I was able to get sources.streams file to work with stream=True. So much better although now I have issues with handling dropped stream connections and latency still. Running a 4090 and only getting ~15% usage and FPS is like 0.5 with 2 streams at 3072x1720. Any idea to further optimize or have it use more GPU and Ram? Only uses 2GB out of 24GB available at 15% load.

**Comment by glenn-jocher** [comment]
Hi @jsammarco, glad to hear that setting the `streams` source with `stream=True` worked for you! However, it sounds like you might be experiencing dropped connection and latency issues. This is a known issue with real-time video processing, especially with RTSP streams over WiFi or other unreliable network connections. One potential solution is to use OpenCV to manually handle dropped connections and latency by checking the status of the stream and buffering frames as needed. It's also worth mentioning that setting `vid_stride=1` can improve performance by reducing redundancy in frame processing. If you have any further questions or concerns, please feel free to ask!

**Comment by denguir** [comment]
Hi @PacketTrace,

Try to create a file named __sources.streams__ in which you enter each RTSP address line by line. Then execute this code
```python3
from ultralytics import YOLO

model = YOLO("yolov8n.pt")
results = model("sources.streams", stream=True)

for result in results:
    print(result.path)
    print(result.speed)
    print("\n")
```

**Comment by jsammarco** [comment]
> Hi @PacketTrace,
> 
> Try to create a file named **sources.streams** in which you enter each RTSP address line by line. Then execute this code
> 
> ```python
> from ultralytics import YOLO
> 
> model = YOLO("yolov8n.pt")
> results = model("sources.streams", stream=True)
> 
> for result in results:
>     print(result.path)
>     print(result.speed)
>     print("\n")
> ```

Thank you. Yes I did figure that out but you would also assume that passing an array of 2 streams and setting stream=True should do the very same thing. Seems silly that you have to programmiclly write a sources.stream file just to have it treat a list of streams as a list of streams, depending on your app if you need to change the streams dynamically.

**Comment by glenn-jocher** [comment]
@denguir thank you for your feedback on the YOLOv8 library's streams functionality. It can definitely be frustrating when the expected behavior of a piece of code doesn't match up with what actually happens, and we appreciate your patience in working through this issue. 
Regarding the ability to pass multiple streams as a list to `YOLO().predict()`, we understand that this would be a convenient feature to have, especially for dynamically changing streams. At the moment, it seems that manually writing a `sources.streams` file is the recommended method for processing multiple streams. However, we appreciate your suggestion and will take it into account for future updates to the library. If you have any further questions or suggestions, please don't hesitate to reach out!

**Comment by Rafhael369** [comment]
Hello,

Has anyone come up with an efficient solution for multiple rtsp streams? If there is a repository and you want to share it, it will be of great help.

Thanks.

**Comment by glenn-jocher** [comment]
@Rafhael369 hello,

There have been several discussions and suggestions regarding efficient handling of multiple RTSP streams in YOLOv8. Here are few of them:

- One approach is to use threading. You can create a separate thread for each RTSP stream. Each of these threads would then be responsible for running the object detection on its corresponding stream. This way, you can process multiple RTSP streams simultaneously.
  
- Another approach you might consider is using a `.streams` file. Essentially, you'd create a file where each line is a different RTSP stream URL. You can then use that file as the source when calling the `predict` method of your YOLO model.

Please note: Depending on how many streams you have and the hardware resources of your machine, you may encounter performance or latency issues with either of these approaches. I would recommend starting with a small number of streams, monitoring the usage of resources, and then adding more as your system can handle.

I hope this helps. Let us know if you have any other questions.

**Comment by syenpark** [comment]
Hi @glenn-jocher, thank you for your great support first. I'm bit confusing whether `*.streams` file and `model.predict(source=*.streams)` way also processes multiple RTSP streams in parallel as batch inference. I know a list of images fed into the model supports the batch inference by [this issue](https://github.com/ultralytics/ultralytics/issues/1310) but not sure for multiple RTSP streams based on your comment here  . Thank you in advance!

> @Rafhael369 hello,
> 
> There have been several discussions and suggestions regarding efficient handling of multiple RTSP streams in YOLOv8. Here are few of them:
> 
> * One approach is to use threading. You can create a separate thread for each RTSP stream. Each of these threads would then be responsible for running the object detection on its corresponding stream. This way, you can process multiple RTSP streams simultaneously.
> * Another approach you might consider is using a `.streams` file. Essentially, you'd create a file where each line is a different RTSP stream URL. You can then use that file as the source when calling the `predict` method of your YOLO model.
> 
> Please note: Depending on how many streams you have and the hardware resources of your machine, you may encounter performance or latency issues with either of these approaches. I would recommend starting with a small number of streams, monitoring the usage of resources, and then adding more as your system can handle.
> 
> I hope this helps. Let us know if you have any other questions.

**Comment by glenn-jocher** [comment]
Yes that's correct! If you pass in 8 streams addresses in your *.streams file then YOLO will run batched inference at shape(8,3,640,640)

**Comment by jsammarco** [comment]
Gotta bump this as it is a nessisary bug fix / feature. No one wants a hung
program because a camera drops out temporary.

**Comment by glenn-jocher** [comment]
@jsammarco hi there,

Thanks for your feedback and for bumping this issue. We understand the importance of handling temporary camera dropouts without hindering the whole program flow. We're looking into how we best can accommodate this in YOLOv8 and appreciate your patience as we work on it. Your input is valuable and contributes to improving the functionality of this model. We will keep you updated on any progress. 

Again, thank you for your input and for being part of the YOLOv8 community.

**Comment by ahmed-danjuma-ibn-harun** [comment]
> > Hi @PacketTrace,
> > Try to create a file named **sources.streams** in which you enter each RTSP address line by line. Then execute this code
> > ```python
> > from ultralytics import YOLO
> > 
> > model = YOLO("yolov8n.pt")
> > results = model("sources.streams", stream=True)
> > 
> > for result in results:
> >     print(result.path)
> >     print(result.speed)
> >     print("\n")
> > ```
> 
> Thank you. Yes I did figure that out but you would also assume that passing an array of 2 streams and setting stream=True should do the very same thing. Seems silly that you have to programmiclly write a sources.stream file just to have it treat a list of streams as a list of streams, depending on your app if you need to change the streams dynamically.



Hello, i tried using the list.streams method for inferencing but it only takes in 1 address at a time,
![Screenshot (229)](https://github.com/ultralytics/ultralytics/assets/89584924/dd8af46f-a91d-4e81-bd9f-d7adee3e1981)

 if i use multiple address it stops immediately after loading the batches
![Screenshot (230)](https://github.com/ultralytics/ultralytics/assets/89584924/269bf149-c5e4-4561-8f0a-45745d052dc0)

**Comment by NQHuy1905** [comment]
@syenpark @glenn-jocher what if i want to use usb camera, can i pass each line in *.streams file with each camera index. For example:

0
1
2
...

**Comment by glenn-jocher** [comment]
@NQHuy1905 hello, thanks for your question. Yes, you can indeed use a similar approach for USB camera inputs. Each line in the *.streams file represents a different source, so you could specify each of your USB cameras by their respective indices (0, 1, 2, etc.) in different lines of the file. This way, the YOLOv8 model will be able to ingest multiple USB camera streams concurrently, similar to the way it does with RTSP streams. Please ensure each camera is properly connected and accessible.

**Comment by epigraphe** [comment]
> @jsammarco hi there,
> 
> Thanks for your feedback and for bumping this issue. We understand the importance of handling temporary camera dropouts without hindering the whole program flow. We're looking into how we best can accommodate this in YOLOv8 and appreciate your patience as we work on it. Your input is valuable and contributes to improving the functionality of this model. We will keep you updated on any progress.
> 
> Again, thank you for your input and for being part of the YOLOv8 community.

Good day.
I wanted to clarify whether there are any changes in the work plan on the problem of temporary shutdown of streams?

**Comment by glenn-jocher** [comment]
@epigraphe hello,

Thank you for reaching out for an update on the handling of temporary camera dropouts in YOLOv8. Our team is aware of how crucial this feature is for a seamless and robust application, especially when dealing with multiple video streams. We are actively investigating the best way to implement a solution that can gracefully handle connection issues without disrupting the entire inference process.

At present, there are several strategies we are considering to address stream dropouts. We're exploring options that will allow the inference on active streams to continue while attempting to reconnect to the ones that have dropped out. Rest assured that we are taking this matter seriously and are working to keep the integrity of the program intact, even when dealing with unstable inputs.

While we do not have a fixed timeline for this feature at the moment, we want to assure you that it is on our roadmap and is being prioritized accordingly. As soon as we have any significant updates or improvements in this area, we will be sure to inform the community.

Thank you once again for your engagement and support. Your feedback helps us to focus on what matters most to our users. We look forward to continuing to make YOLOv8 the best it can be.

Best regards,
The YOLOv8 Development Team

**Comment by hgospodar** [comment]
**It seems some problems in showwing mutiple RTSP streams in realtime**
I'm using following code to inference multiple streams, and to show the result image
```python
from ultralytics import YOLO
import cv2
from PIL import Image

model = YOLO('yolov8m-pose.pt')
source = './list.streams'

results = model(source, stream=True)

for result in results:
    annotated_image = result.plot()
    cv2.imshow(f'{result.path}', annotated_image)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cv2.destroyAllWindows()

```
the list.streams is like
```
rtsp://user:password@172.20.0.183:554/Streaming/Channels/101
rtsp://user:password@172.20.4.214:554/Streaming/Channels/101
rtsp://user:password@172.20.3.40:554/Streaming/Channels/101

```
run the upper code, the terminal print like:
_rtsp://user:password@172.20.0.183:554/Streaming/Channels/101 Success ✅ (inf frames of shape 1920x1080 at 25.00 FPS)_
_rtsp://user:password@172.20.4.214:554/Streaming/Channels/101 Success ✅ (inf frames of shape 1920x1080 at 25.00 FPS)_
_rtsp://user:password@172.20.3.40:554/Streaming/Channels/101 Success ✅ (inf frames of shape 1920x1080 at 25.00 FPS)_

But, when i think the `cv2.imshow` function will show the three different streams inference results, it JUST show the three windows render the same video stream. 

is there some friends meet the same problem like me. how did you solve the problem?

**Comment by glenn-jocher** [comment]
@hgospodar hello,

It appears there might be an issue with the stream handling in your code. When using `cv2.imshow`, ensure that each window has a unique name corresponding to each stream. If the window names are not unique, OpenCV may display the same stream in all windows. The `result.path` should provide a unique identifier for each stream, but you might want to verify that each `result` object indeed corresponds to a different stream.

If the problem persists, it could be related to how the streams are being processed internally. Please check the Ultralytics documentation for any additional configuration that might be required for handling multiple streams. If you're still experiencing issues, consider opening an issue on the Ultralytics YOLOv8 GitHub repository with detailed information so that the community can assist you further.

**Comment by jinyu-118** [comment]
hello， @glenn-jocher ,When trying multi weight and multi rtsp streams, I used a multi process loading model, and added a process that reads the rtsp stream using loadstream and allocates the rtsp stream to the corresponding process through queue. Do you think this framework is feasible?

**Comment by franklinselva** [comment]
@jinyu-118 I am writing something similar to help share the resources between the available RTSP streams for consistent behavior. Did you experience any limitations with the approach you have mentioned?

**Comment by jinyu-118** [comment]
> @jinyu-118 I am writing something similar to help share the resources between the available RTSP streams for consistent behavior. Did you experience any limitations with the approach you have mentioned?
The limitation is that there is a certain delay difference compared to the real stream, usually around 1 second, but compared to loading multiple RTSP streams, I don't know if this is a good thing.

**Comment by jinyu-118** [comment]
@franklinselva The limitation is that there is a certain delay difference compared to the real stream, usually around 1 second, but compared to loading multiple RTSP streams, I don't know if this is a good thing.

**Comment by franklinselva** [comment]
> @franklinselva The limitation is that there is a certain delay difference compared to the real stream, usually around 1 second, but compared to loading multiple RTSP streams, I don't know if this is a good thing.

@jinyu-118 Thanks. I think the limitation is not strictly confining depending on the application. I have one more card, to use simple load-balancing mechanisms to optimise runtime between the inference and output frequency. I will continue in this direction to see if it helps.
