### ISSUE TITLE
RT-DETR load other pretrained weights 

### ISSUE THREAD

**Issue by SoraJung** [ultralytics/ultralytics#13872]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I tried to load the pretrained weight from rtdetr_r101vd_2x_coco_objects365_from_paddle.pth (https://github.com/lyuwenyu/RT-DETR/tree/main/rtdetr_pytorch)
I changed the weight name, resnet101_coco_objects365.pt

```shell
yolo train model=rtdetr-resnet101.yaml ...
```
I modfied ymal file too, `pretrained: resnet101_coco_objects365.pt`
However. the following bug appears:

```shell
Traceback (most recent call last):
  File "/opt/conda/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/src/ultralytics/ultralytics/cfg/__init__.py", line 558, in entrypoint
    model.load(overrides["pretrained"])
  File "/usr/src/ultralytics/ultralytics/engine/model.py", line 307, in load
    weights, self.ckpt = attempt_load_one_weight(weights)
  File "/usr/src/ultralytics/ultralytics/nn/tasks.py", line 808, in attempt_load_one_weight
    model = (ckpt.get("ema") or ckpt["model"]).to(device).float()  # FP32 model
AttributeError: 'dict' object has no attribute 'to'
```
I wonder if ultralytics can load other pretrained weights too.

**Comment by glenn-jocher** [comment]
@SoraJung hello,

Thank you for reaching out and providing detailed information about the issue you're encountering. It seems like you're trying to load a custom pretrained weight file for the RT-DETR model, and you're running into an error.

To assist you better, could you please confirm the following:
1. Are you using the latest versions of `torch` and `ultralytics`? If not, please update them and try again:
    ```bash
    pip install --upgrade torch ultralytics
    ```

2. Could you provide a minimum reproducible code example? This will help us understand the context better and reproduce the issue on our end. You can refer to our guide on creating a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Regarding the error you're seeing, it appears that the structure of the checkpoint file might not be compatible with the expected format. The `attempt_load_one_weight` function expects the checkpoint to have a specific structure, including an attribute that can be moved to a device using `.to(device)`.

Here are a few steps you can try to resolve this:

1. **Verify Checkpoint Structure**: Ensure that the checkpoint file (`resnet101_coco_objects365.pt`) has the correct structure. It should contain the model weights in a format that Ultralytics expects. Typically, this includes keys like `model` or `ema`.

2. **Manual Loading**: If the checkpoint structure is different, you might need to manually load the weights into the model. Here’s an example of how you can do this:
    ```python
    from ultralytics import RTDETR
    import torch

    # Load the model architecture
    model = RTDETR('rtdetr-resnet101.yaml')

    # Load the custom weights
    checkpoint = torch.load('resnet101_coco_objects365.pt')
    model.load_state_dict(checkpoint['model'])

    # Continue with training or inference
    model.train(data='coco8.yaml', epochs=100, imgsz=640)
    ```

3. **Modify YAML Configuration**: Ensure that the YAML configuration file (`rtdetr-resnet101.yaml`) is correctly set up to match the architecture of the pretrained weights you are loading.

If you continue to face issues, please share the exact steps and code snippets you used, so we can provide more targeted assistance.

Looking forward to your response!
