### ISSUE TITLE
custom dataset trained model not able to be open in yolov8

### ISSUE THREAD

**Issue by benjamineqin** [ultralytics/ultralytics#13889]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

custom dataset trained model not able to be open in yolov8. I am using CPU and the dataset was created by me. Below is the traing.py : 
from ultralytics import YOLO
# try:
    # Load YOLOv8 model
model = YOLO('yolov8.yaml', task='detect')  # Load a YOLOv8 model configuration
     # Train the model
model.train(data='dataset/dataset.yaml', epochs=10, imgsz=320, device='cpu')
        # Save the trained model weights
model.save('yolov8n.pt')
print("Training completed and model saved successfully.")

Here is the dataset.yaml
path: /Development/ODOCB/Yolov4/dataset
train: /Development/ODOCB/Yolov4/dataset/images/train
val: /Development/ODOCB/Yolov4/dataset/images/validation
nc: 2
names: ['egg_class_1', 'egg_class_2']

Here is the yolov8.yaml:
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters

nc: 2 # number of classes

# Depth and width multiples
depth_multiple: 0.33
width_multiple: 0.50

scales: 'n'
# model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  #n: [0.33, 0.25, 1024] # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  #s: [0.33, 0.50, 1024] # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  #m: [0.67, 0.75, 768] # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  #l: [1.00, 1.00, 512] # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  #x: [1.00, 1.25, 512] # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2f, [512]] # 12

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2f, [256]] # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2f, [512]] # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2f, [1024]] # 21 (P5/32-large)

  - [[15, 18, 21], 1, Detect, [nc]] # Detect(P3, P4, P5)

### Environment

windows10, CPU, 
Python 3.11.9
PIP 24.1
Pip list: 
Package                      Version
---------------------------- -----------
absl-py                      2.1.0
albucore                     0.0.12
albumentations               1.4.10
annotated-types              0.7.0
astunparse                   1.6.3
certifi                      2024.6.2
charset-normalizer           3.3.2
colorama                     0.4.6
contourpy                    1.2.1
cycler                       0.12.1
filelock                     3.15.3
flatbuffers                  24.3.25
fonttools                    4.53.0
fsspec                       2024.6.0
gast                         0.5.4
google-pasta                 0.2.0
grpcio                       1.64.1
h5py                         3.11.0
idna                         3.7
imageio                      2.34.1
intel-openmp                 2021.4.0
Jinja2                       3.1.4
joblib                       1.4.2
keras                        3.3.3
kiwisolver                   1.4.5
lapx                         0.5.9.post1
lazy_loader                  0.4
libclang                     18.1.1
Markdown                     3.6
markdown-it-py               3.0.0
MarkupSafe                   2.1.5
matplotlib                   3.9.0
mdurl                        0.1.2
mkl                          2021.4.0
ml-dtypes                    0.3.2
mpmath                       1.3.0
namex                        0.0.8
networkx                     3.3
numpy                        1.26.4
opencv-python                4.10.0.84
opencv-python-headless       4.10.0.84
opt-einsum                   3.3.0
optree                       0.11.0
packaging                    24.1
pandas                       2.2.2
pillow                       10.3.0
pip                          24.1
protobuf                     4.25.3
psutil                       6.0.0
py-cpuinfo                   9.0.0
pydantic                     2.7.4
pydantic_core                2.18.4
Pygments                     2.18.0
pyparsing                    3.1.2
python-dateutil              2.9.0.post0
pytz                         2024.1
PyYAML                       6.0.1
requests                     2.32.3
rich                         13.7.1
scikit-image                 0.24.0
scikit-learn                 1.5.0
scipy                        1.13.1
seaborn                      0.13.2
setuptools                   69.5.1
shapely                      2.0.4
six                          1.16.0
sympy                        1.12.1
tbb                          2021.13.0
tensorboard                  2.16.2
tensorboard-data-server      0.7.2
tensorflow                   2.16.1
tensorflow-intel             2.16.1
tensorflow-io-gcs-filesystem 0.31.0
termcolor                    2.4.0
threadpoolctl                3.5.0
tifffile                     2024.6.18
tomli                        2.0.1
torch                        2.3.1
torchaudio                   2.3.1
torchvision                  0.18.1
tqdm                         4.66.4
typing_extensions            4.12.2
tzdata                       2024.1
ultralytics                  8.2.39
ultralytics-thop             2.0.0
urllib3                      2.2.2
Werkzeug                     3.0.3
wheel                        0.43.0
wrapt                        1.16.0

### Minimal Reproducible Example

>>> import torch
>>> from ultralytics import YOLO
>>> model = YOLO('yolyv8n.pt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Development\ODOCB\Yolov4\myvenv\Lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__      
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Development\ODOCB\Yolov4\myvenv\Lib\site-packages\ultralytics\engine\model.py", line 151, in __init__
    self._load(model, task=task)
  File "C:\Development\ODOCB\Yolov4\myvenv\Lib\site-packages\ultralytics\engine\model.py", line 240, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Development\ODOCB\Yolov4\myvenv\Lib\site-packages\ultralytics\nn\tasks.py", line 849, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Development\ODOCB\Yolov4\myvenv\Lib\site-packages\ultralytics\nn\tasks.py", line 775, in torch_safe_load       
    ckpt = torch.load(file, map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Development\ODOCB\Yolov4\myvenv\Lib\site-packages\torch\serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Development\ODOCB\Yolov4\myvenv\Lib\site-packages\torch\serialization.py", line 444, in _open_file_like        
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Development\ODOCB\Yolov4\myvenv\Lib\site-packages\torch\serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'yolyv8n.pt'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by benjamineqin** [comment]
i installed every thing suggested above, the issue persisted. I guess the problem is the dictionary of the model I trained is not match with the default setting for the model. Here is the dict_key for reference: dict_keys(['model', 'date', 'version', 'license', 'docs']). Could you help to check if the dict_key is correct? or how can i use the model with this dict_key?

**Comment by glenn-jocher** [comment]
@benjamineqin hi there! 👋

Thank you for providing the details. It looks like the issue might be related to the structure of the saved model file. The `dict_keys` you mentioned (`['model', 'date', 'version', 'license', 'docs']`) seem correct for a YOLOv8 model checkpoint.

To help diagnose the issue further, please ensure you are using the latest versions of `torch` and `ultralytics`. You can upgrade them using the following commands:

```bash
pip install --upgrade torch ultralytics
```

Additionally, it seems there might be a typo in your file name when loading the model. You are saving the model as `yolov8n.pt` but trying to load `yolyv8n.pt`. Please ensure the file name matches exactly.

Here's a quick example to ensure everything is set up correctly:

```python
from ultralytics import YOLO

# Load the trained model
model = YOLO('yolov8n.pt')

# Run inference to test if the model loads correctly
results = model('path/to/your/test/image.jpg')
results.show()
```

If the issue persists, please provide a minimal reproducible example so we can investigate further. You can find more details on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Let us know how it goes! 😊
