### ISSUE TITLE
On the issue of adding a CBAM attention mechanism

### ISSUE THREAD

**Issue by super-song-sir** [ultralytics/ultralytics#13880]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I've read a few issues and found that when they add a CBAM attention mechanism, they add it to the parse_model function in the task.py when they parse the model:
`# elif m is CBAM:
        #     c1, c2 = ch[f], args[0]
        #     if c2 != nc:
        #         c2 = make_divisible(min(c2, max_channels) * width, 8)
        #     args = [c2, *args]`
I don't think this is well written, this need to add the number of channels in the args of CBAM when writing the config file. And there is no need to assign values to c1 and c2. So it only needs to be added in the parse_model function
`        elif m in {CBAM,}:
            c2 = ch[f]
            args = [c2,*args]`
In this way, if you need to change the size of the kernel when configuring the model, you only need to write - [-1, 1, CBAM, [3]], and you don't need to write the number of channels at all. And it's also handy when adding other attention mechanisms.What do you think?

**Comment by glenn-jocher** [comment]
@super-song-sir hi there,

Thank you for your thoughtful suggestion on integrating the CBAM attention mechanism into the `parse_model` function. Your approach to simplifying the configuration by avoiding the explicit assignment of `c1` and `c2` and directly modifying the `args` list is indeed interesting.

Before we proceed further, could you please provide a minimum reproducible code example that demonstrates your implementation? This will help us better understand your proposal and ensure that we can reproduce any potential issues or improvements. You can find guidelines on how to create a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of `torch` and `ultralytics`. If not, kindly upgrade your packages and try your implementation again to see if the issue persists.

Looking forward to your code example and further details. Thanks for contributing to the YOLO community! 😊
