### ISSUE TITLE
 YOLOv8 Inference Time Increases from Stable 1ms to 15ms over Continuous Runs

### ISSUE THREAD

**Issue by auner2456889** [ultralytics/ultralytics#13882]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hi everyone,

I'm experiencing a significant issue with YOLOv8 inference times during continuous runs. Initially, the inference time is stable at around 1ms, but it gradually increases to 15ms after 500 to 1000 iterations. Here are the code:

from ultralytics import YOLO

model = YOLO("yolov8s.engine", task="detect")

for i in range(1000):
    results = model.predict("cat.jpg", conf = .7)
    
 Issue:
At the beginning, the inference time is around 1ms per image. However, after running the inference continuously, the time gradually increases and can reach up to 15ms.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@auner2456889 hi there,

Thank you for reporting this issue. To help us investigate further, could you please provide a minimal reproducible code example? This will allow us to replicate the problem on our end. You can find guidelines for creating a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of `torch` and `ultralytics`. You can update your packages using the following commands:

```bash
pip install --upgrade torch ultralytics
```

Once you've updated, please run your code again to see if the issue persists. If it does, kindly share the updated code and any additional details about your environment (e.g., hardware specifications, operating system).

Looking forward to your response so we can assist you further!
