### ISSUE TITLE
On the issue of adding a CBAM attention mechanism

### ISSUE THREAD

**Issue by super-song-sir** [ultralytics/ultralytics#13881]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I've read a few issues and found that when they add a CBAM attention mechanism, they add it to the parse_model function in the task.py when they parse the model:
`        elif m is CBAM:`
`            c1, c2 = ch[f], args[0]`
`            if c2 != nc:`
`                c2 = make_divisible(min(c2, max_channels) * width, 8)`
`            args = [c2, *args]`
I don't think this is well written, this need to add the number of channels in the args of CBAM when writing the config file. And there is no need to assign values to c1 and c2. So it only needs to be added in the parse_model function
`        elif m in {CBAM,}:`
`            c2 = ch[f]`
`            args = [c2,*args]`
In this way, if you need to change the size of the kernel when configuring the model, you only need to write - [-1, 1, CBAM, [3]], and you don't need to write the number of channels at all. And it's also handy when adding other attention mechanisms.What do you think?

**Comment by glenn-jocher** [comment]
@super-song-sir hi there,

Thank you for your insightful suggestion regarding the integration of the CBAM attention mechanism into the `parse_model` function. Your approach to simplifying the configuration by removing the need to specify the number of channels directly in the config file is indeed interesting and could streamline the process for users.

To better evaluate and potentially implement your suggestion, could you please provide a minimum reproducible code example? This will help us understand the context and ensure that we can reproduce the behavior you're describing. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details on what to include.

Additionally, please ensure that you are using the latest versions of `torch` and `ultralytics`. If you haven't already, upgrading to the most recent versions might resolve some issues or provide new features that could be relevant to your implementation.

Looking forward to your code example and further details!
