### ISSUE TITLE
yolov8 keypoint model predicting 0,0 for some skeleton points in response object but directly plotting works as expected on m1 AND colab notebook.

### ISSUE THREAD

**Issue by bs7280** [ultralytics/ultralytics#13892]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

When I use a yolo8 pose model, and use the output to directly plot the output with `results[0].plot()` everything looks as expected, but when accessing the data from the response, some of the keypoints are 0 which is strange.

I encountered this bug in two ways.
1) On my local machine (m1 max)
2) on a colab notebook

## Colab notebook - voxel51 hello world 
First example - voxel51 is presumably using the prediction data and rendering with its own tools - and you can see several keypoints at 0,0 in the top left corner.  

Also - apologies for weird screenshot, the voxel51 notebook UI render acts weird when I try to screenshot it.

![Screenshot by Dropbox Capture](https://github.com/ultralytics/ultralytics/assets/3701087/a75ab283-be1f-4699-b56d-1840d6569430)

Data from same image + prediction + model:  **Note the 0,0 rows**
![Screenshot by Dropbox Capture](https://github.com/ultralytics/ultralytics/assets/3701087/54ca23b5-a236-409a-88d5-1fdbf8c17743)

Next I use the same model object in the same notebook and have the ultralytics library directly render the pose output, which is successful. 
![Screenshot by Dropbox Capture](https://github.com/ultralytics/ultralytics/assets/3701087/59d54094-c5fe-4102-b669-2b7b6fda9f26)

this implies the model is working but theres a bug in how the response object is created?

## Local M1

I don't have as much info handy, and the images i've been working with shouldn't be published online, but heres an example of the keypoint result object. I have confirmed the results_pose[0].plot()

Breakpoint output:

```p results_pose[0].keypoints
ultralytics.engine.results.Keypoints object with attributes:

conf: tensor([[0.8101, 0.2188, 0.8745, 0.0752, 0.9433, 0.9104, 0.9989, 0.6514, 0.9987, 0.6405, 0.9940, 0.9936, 0.9993, 0.9811, 0.9976, 0.9345, 0.9783]])
data: tensor([[[9.0006e+02, 3.3033e+02, 8.1006e-01],
         [0.0000e+00, 0.0000e+00, 2.1878e-01],
         [8.9456e+02, 3.1332e+02, 8.7449e-01],
         [0.0000e+00, 0.0000e+00, 7.5221e-02],
         [8.5343e+02, 2.9837e+02, 9.4333e-01],
         [8.0723e+02, 3.4817e+02, 9.1035e-01],
         [7.8433e+02, 3.6088e+02, 9.9894e-01],
         [7.9516e+02, 4.7195e+02, 6.5142e-01],
         [8.0357e+02, 5.0610e+02, 9.9874e-01],
         [8.3797e+02, 5.8924e+02, 6.4053e-01],
         [8.4981e+02, 6.0123e+02, 9.9397e-01],
         [7.2485e+02, 5.6023e+02, 9.9362e-01],
         [7.0025e+02, 5.7105e+02, 9.9927e-01],
         [7.6943e+02, 7.2473e+02, 9.8114e-01],
         [6.9514e+02, 7.5936e+02, 9.9757e-01],
         [7.6255e+02, 8.8743e+02, 9.3446e-01],
         [6.8944e+02, 9.5484e+02, 9.7831e-01]]])
has_visible: True
orig_shape: (1080, 1920)
shape: torch.Size([1, 17, 3])
xy: tensor([[[900.0571, 330.3291],
         [  0.0000,   0.0000],
         [894.5585, 313.3198],
         [  0.0000,   0.0000],
         [853.4297, 298.3660],
         [807.2343, 348.1710],
         [784.3300, 360.8765],
         [795.1593, 471.9487],
         [803.5692, 506.0955],
         [837.9719, 589.2352],
         [849.8090, 601.2253],
         [724.8543, 560.2279],
         [700.2515, 571.0484],
         [769.4324, 724.7350],
         [695.1448, 759.3569],
         [762.5483, 887.4346],
         [689.4436, 954.8414]]])
xyn: tensor([[[0.4688, 0.3059],
         [0.0000, 0.0000],
         [0.4659, 0.2901],
         [0.0000, 0.0000],
         [0.4445, 0.2763],
         [0.4204, 0.3224],
         [0.4085, 0.3341],
         [0.4141, 0.4370],
         [0.4185, 0.4686],
         [0.4364, 0.5456],
         [0.4426, 0.5567],
         [0.3775, 0.5187],
         [0.3647, 0.5287],
         [0.4007, 0.6711],
         [0.3621, 0.7031],
         [0.3972, 0.8217],
         [0.3591, 0.8841]]])
```

Image out with .plot() works fine

![Screenshot by Dropbox Capture](https://github.com/ultralytics/ultralytics/assets/3701087/625ebc60-8f15-4d18-81ce-4d8e35ea054b)

## local m1
```
Ultralytics YOLOv8.2.35 🚀 Python-3.11.9 torch-2.3.1 CPU (Apple M1 Max)
Setup complete ✅ (10 CPUs, 64.0 GB RAM, 898.7/926.4 GB disk)
```

## Colab
`ultralytics.checks()` returns None on colab? Sorry for that, not sure what to do. Here's my pipe freeze though:

```
absl-py==1.4.0
aiofiles==23.2.1
aiohttp==3.9.5
aiosignal==1.3.1
alabaster==0.7.16
albumentations==1.3.1
altair==4.2.2
annotated-types==0.7.0
anyio==3.7.1
argcomplete==3.4.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
array_record==0.5.1
arviz==0.15.1
astropy==5.3.4
astunparse==1.6.3
async-timeout==4.0.3
atpublic==4.1.0
attrs==23.2.0
audioread==3.0.1
autograd==1.6.2
Babel==2.15.0
backcall==0.2.0
beautifulsoup4==4.12.3
bidict==0.23.1
bigframes==1.8.0
bleach==6.1.0
blinker==1.4
blis==0.7.11
blosc2==2.0.0
bokeh==3.3.4
boto3==1.34.131
botocore==1.34.131
bqplot==0.12.43
branca==0.7.2
Brotli==1.1.0
build==1.2.1
CacheControl==0.14.0
cachetools==5.3.3
catalogue==2.0.10
certifi==2024.6.2
cffi==1.16.0
chardet==5.2.0
charset-normalizer==3.3.2
chex==0.1.86
click==8.1.7
click-plugins==1.1.1
cligj==0.7.2
cloudpathlib==0.18.1
cloudpickle==2.2.1
cmake==3.27.9
cmdstanpy==1.2.4
colorcet==3.1.0
colorlover==0.3.0
colour==0.1.5
community==1.0.0b1
confection==0.1.5
cons==0.4.6
contextlib2==21.6.0
contourpy==1.2.1
cryptography==42.0.8
cuda-python==12.2.1
cudf-cu12 @ https://pypi.nvidia.com/cudf-cu12/cudf_cu12-24.4.1-cp310-cp310-manylinux_2_28_x86_64.whl#sha256=57366e7ef09dc63e0b389aff20df6c37d91e2790065861ee31a4720149f5b694
cufflinks==0.17.3
cupy-cuda12x==12.2.0
cvxopt==1.3.2
cvxpy==1.3.4
cycler==0.12.1
cymem==2.0.8
Cython==3.0.10
dacite==1.7.0
dask==2023.8.1
datascience==0.17.6
db-dtypes==1.2.0
dbus-python==1.2.18
debugpy==1.6.6
decorator==4.4.2
defusedxml==0.7.1
Deprecated==1.2.14
dill==0.3.8
distributed==2023.8.1
distro==1.7.0
dlib==19.24.4
dm-tree==0.1.8
dnspython==2.6.1
docstring_parser==0.16
docutils==0.18.1
dopamine_rl==4.0.9
duckdb==0.10.3
earthengine-api==0.1.407
easydict==1.13
ecos==2.0.14
editdistance==0.6.2
eerepr==0.0.4
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl#sha256=86cc141f63942d4b2c5fcee06630fd6f904788d2f0ab005cce45aadb8fb73889
entrypoints==0.4
et-xmlfile==1.1.0
etils==1.7.0
etuples==0.3.9
exceptiongroup==1.2.1
fastai==2.7.15
fastcore==1.5.46
fastdownload==0.0.7
fastjsonschema==2.20.0
fastprogress==1.0.3
fastrlock==0.8.2
fiftyone==0.24.1
fiftyone-brain==0.16.1
fiftyone_db==1.1.3
filelock==3.15.1
fiona==1.9.6
firebase-admin==5.3.0
Flask==2.2.5
flatbuffers==24.3.25
flax==0.8.4
folium==0.14.0
fonttools==4.53.0
frozendict==2.4.4
frozenlist==1.4.1
fsspec==2023.6.0
ftfy==6.2.0
future==0.18.3
gast==0.5.4
gcsfs==2023.6.0
GDAL==3.6.4
gdown==5.1.0
geemap==0.32.1
gensim==4.3.2
geocoder==1.38.1
geographiclib==2.0
geopandas==0.13.2
geopy==2.3.0
gin-config==0.5.0
glob2==0.7
google==2.0.3
google-ai-generativelanguage==0.6.4
google-api-core==2.11.1
google-api-python-client==2.84.0
google-auth==2.27.0
google-auth-httplib2==0.1.1
google-auth-oauthlib==1.2.0
google-cloud-aiplatform==1.56.0
google-cloud-bigquery==3.21.0
google-cloud-bigquery-connection==1.12.1
google-cloud-bigquery-storage==2.25.0
google-cloud-core==2.3.3
google-cloud-datastore==2.15.2
google-cloud-firestore==2.11.1
google-cloud-functions==1.13.3
google-cloud-iam==2.15.0
google-cloud-language==2.13.3
google-cloud-resource-manager==1.12.3
google-cloud-storage==2.8.0
google-cloud-translate==3.11.3
google-colab @ file:///colabtools/dist/google-colab-1.0.0.tar.gz#sha256=b065b56e03e174042256860688869a922c200f064b60c144ebaa786a3c20a574
google-crc32c==1.5.0
google-generativeai==0.5.4
google-pasta==0.2.0
google-resumable-media==2.7.1
googleapis-common-protos==1.63.1
googledrivedownloader==0.4
graphql-core==3.2.3
graphviz==0.20.3
greenlet==3.0.3
grpc-google-iam-v1==0.13.0
grpcio==1.64.1
grpcio-status==1.48.2
gspread==6.0.2
gspread-dataframe==3.3.1
gym==0.25.2
gym-notices==0.0.8
h11==0.14.0
h2==4.1.0
h5netcdf==1.3.0
h5py==3.9.0
holidays==0.51
holoviews==1.17.1
hpack==4.0.0
html5lib==1.1
httpcore==1.0.5
httpimport==1.3.1
httplib2==0.22.0
httpx==0.27.0
huggingface-hub==0.23.4
humanize==4.7.0
Hypercorn==0.17.3
hyperframe==6.0.1
hyperopt==0.2.7
ibis-framework==8.0.0
idna==3.7
imageio==2.31.6
imageio-ffmpeg==0.5.1
imagesize==1.4.1
imbalanced-learn==0.10.1
imgaug==0.4.0
immutabledict==4.2.0
importlib_metadata==7.1.0
importlib_resources==6.4.0
imutils==0.5.4
inflate64==1.0.0
inflect==7.0.0
iniconfig==2.0.0
intel-openmp==2023.2.4
ipyevents==2.0.2
ipyfilechooser==0.6.0
ipykernel==5.5.6
ipyleaflet==0.18.2
ipython==7.34.0
ipython-genutils==0.2.0
ipython-sql==0.5.0
ipytree==0.2.2
ipywidgets==7.7.1
itsdangerous==2.2.0
jax==0.4.26
jaxlib @ https://storage.googleapis.com/jax-releases/cuda12/jaxlib-0.4.26+cuda12.cudnn89-cp310-cp310-manylinux2014_x86_64.whl#sha256=813cf1fe3e7ca4dbf5327d6e7b4fc8521e92d8bba073ee645ae0d5d036a25750
jeepney==0.7.1
jellyfish==1.0.4
jieba==0.42.1
Jinja2==3.0.3
jmespath==1.0.1
joblib==1.4.2
jsonlines==4.0.0
jsonpickle==3.2.1
jsonschema==4.19.2
jsonschema-specifications==2023.12.1
jupyter-client==6.1.12
jupyter-console==6.1.0
jupyter-server==1.24.0
jupyter_core==5.7.2
jupyterlab_pygments==0.3.0
jupyterlab_widgets==3.0.11
kaggle==1.6.14
kagglehub==0.2.5
kaleido==0.2.1
keras==2.15.0
keyring==23.5.0
kiwisolver==1.4.5
langcodes==3.4.0
language_data==1.2.0
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lazy_loader==0.4
libclang==18.1.1
librosa==0.10.2.post1
lightgbm==4.1.0
linkify-it-py==2.0.3
llvmlite==0.41.1
locket==1.0.0
logical-unification==0.4.6
lxml==4.9.4
malloy==2023.1067
marisa-trie==1.2.0
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.7.1
matplotlib-inline==0.1.7
matplotlib-venn==0.11.10
mdit-py-plugins==0.4.1
mdurl==0.1.2
miniKanren==1.0.3
missingno==0.5.2
mistune==0.8.4
mizani==0.9.3
mkl==2023.2.0
ml-dtypes==0.2.0
mlxtend==0.22.0
mongoengine==0.24.2
more-itertools==10.1.0
motor==3.4.0
moviepy==1.0.3
mpmath==1.3.0
msgpack==1.0.8
multidict==6.0.5
multipledispatch==1.0.0
multitasking==0.0.11
multivolumefile==0.2.3
murmurhash==1.0.10
music21==9.1.0
natsort==8.4.0
nbclassic==1.1.0
nbclient==0.10.0
nbconvert==6.5.4
nbformat==5.10.4
nest-asyncio==1.6.0
networkx==3.3
nibabel==4.0.2
nltk==3.8.1
notebook==6.5.5
notebook_shim==0.2.4
numba==0.58.1
numexpr==2.10.0
numpy==1.25.2
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.5.40
nvidia-nvtx-cu12==12.1.105
nvtx==0.2.10
oauth2client==4.1.3
oauthlib==3.2.2
opencv-contrib-python==4.8.0.76
opencv-python==4.8.0.76
opencv-python-headless==4.10.0.84
openpyxl==3.1.4
opt-einsum==3.3.0
optax==0.2.2
orbax-checkpoint==0.4.4
osqp==0.6.2.post8
packaging==24.1
pandas==2.0.3
pandas-datareader==0.10.0
pandas-gbq==0.19.2
pandas-stubs==2.0.3.230814
pandocfilters==1.5.1
panel==1.3.8
param==2.1.0
parso==0.8.4
parsy==2.1
partd==1.4.2
pathlib==1.0.1
patsy==0.5.6
peewee==3.17.5
pexpect==4.9.0
pickleshare==0.7.5
Pillow==9.4.0
pip-tools==6.13.0
platformdirs==4.2.2
plotly==5.15.0
plotnine==0.12.4
pluggy==1.5.0
polars==0.20.2
pooch==1.8.2
portpicker==1.5.2
pprintpp==0.4.0
prefetch-generator==1.0.3
preshed==3.0.9
prettytable==3.10.0
priority==2.0.0
proglog==0.1.10
progressbar2==4.2.0
prometheus_client==0.20.0
promise==2.3
prompt_toolkit==3.0.47
prophet==1.1.5
proto-plus==1.23.0
protobuf==3.20.3
psutil==5.9.5
psycopg2==2.9.9
ptyprocess==0.7.0
py-cpuinfo==9.0.0
py4j==0.10.9.7
py7zr==0.21.0
pyarrow==14.0.2
pyarrow-hotfix==0.6
pyasn1==0.6.0
pyasn1_modules==0.4.0
pybcj==1.0.2
pycocotools==2.0.8
pycparser==2.22
pycryptodomex==3.20.0
pydantic==2.7.4
pydantic_core==2.18.4
pydata-google-auth==1.8.2
pydot==1.4.2
pydot-ng==2.0.0
pydotplus==2.0.2
PyDrive==1.3.1
PyDrive2==1.6.3
pyerfa==2.0.1.4
pygame==2.5.2
Pygments==2.16.1
PyGObject==3.42.1
PyJWT==2.3.0
pymc==5.10.4
pymongo==4.7.3
pymystem3==0.2.0
pynvjitlink-cu12==0.2.4
PyOpenGL==3.1.7
pyOpenSSL==24.1.0
pyparsing==3.1.2
pyperclip==1.8.2
pyppmd==1.1.0
pyproj==3.6.1
pyproject_hooks==1.1.0
pyshp==2.3.1
PySocks==1.7.1
pytensor==2.18.6
pytest==7.4.4
python-apt @ file:///backend-container/containers/python_apt-0.0.0-cp310-cp310-linux_x86_64.whl#sha256=b209c7165d6061963abe611492f8c91c3bcef4b7a6600f966bab58900c63fefa
python-box==7.2.0
python-dateutil==2.8.2
python-louvain==0.16
python-slugify==8.0.4
python-utils==3.8.2
pytz==2023.4
pyviz_comms==3.0.2
PyWavelets==1.6.0
PyYAML==6.0.1
pyzmq==24.0.1
pyzstd==0.16.0
qdldl==0.1.7.post3
qudida==0.0.4
rarfile==4.2
ratelim==0.1.6
referencing==0.35.1
regex==2024.5.15
requests==2.31.0
requests-oauthlib==1.3.1
requirements-parser==0.9.0
retrying==1.3.4
rich==13.7.1
rmm-cu12==24.4.0
rpds-py==0.18.1
rpy2==3.4.2
rsa==4.9
s3transfer==0.10.1
safetensors==0.4.3
scikit-image==0.19.3
scikit-learn==1.2.2
scipy==1.11.4
scooby==0.10.0
scs==3.2.4.post2
seaborn==0.13.1
SecretStorage==3.3.1
Send2Trash==1.8.3
sentencepiece==0.1.99
shapely==2.0.4
shellingham==1.5.4
simple_parsing==0.1.5
six==1.16.0
sklearn-pandas==2.2.0
smart-open==7.0.4
sniffio==1.3.1
snowballstemmer==2.2.0
sortedcontainers==2.4.0
soundfile==0.12.1
soupsieve==2.5
soxr==0.3.7
spacy==3.7.5
spacy-legacy==3.0.12
spacy-loggers==1.0.5
Sphinx==5.0.2
sphinxcontrib-applehelp==1.0.8
sphinxcontrib-devhelp==1.0.6
sphinxcontrib-htmlhelp==2.0.5
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.7
sphinxcontrib-serializinghtml==1.1.10
SQLAlchemy==2.0.30
sqlglot==20.11.0
sqlparse==0.5.0
srsly==2.4.8
sse-starlette==0.10.3
sseclient-py==1.8.0
stanio==0.5.0
starlette==0.37.2
statsmodels==0.14.2
strawberry-graphql==0.138.1
StrEnum==0.4.15
sympy==1.12.1
tables==3.8.0
tabulate==0.9.0
taskgroup==0.0.0a4
tbb==2021.12.0
tblib==3.0.0
tenacity==8.4.1
tensorboard==2.15.2
tensorboard-data-server==0.7.2
tensorflow @ https://storage.googleapis.com/colab-tf-builds-public-09h6ksrfwbb9g9xv/tensorflow-2.15.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=a2ec79931350b378c1ef300ca836b52a55751acb71a433582508a07f0de57c42
tensorflow-datasets==4.9.6
tensorflow-estimator==2.15.0
tensorflow-gcs-config==2.15.0
tensorflow-hub==0.16.1
tensorflow-io-gcs-filesystem==0.37.0
tensorflow-metadata==1.15.0
tensorflow-probability==0.23.0
tensorstore==0.1.45
termcolor==2.4.0
terminado==0.18.1
text-unidecode==1.3
textblob==0.17.1
texttable==1.7.0
tf-slim==1.1.0
tf_keras==2.15.1
thinc==8.2.4
threadpoolctl==3.5.0
tifffile==2024.5.22
tinycss2==1.3.0
tokenizers==0.19.1
toml==0.10.2
tomli==2.0.1
toolz==0.12.1
torch @ https://download.pytorch.org/whl/cu121/torch-2.3.0%2Bcu121-cp310-cp310-linux_x86_64.whl#sha256=0a12aa9aa6bc442dff8823ac8b48d991fd0771562eaa38593f9c8196d65f7007
torchaudio @ https://download.pytorch.org/whl/cu121/torchaudio-2.3.0%2Bcu121-cp310-cp310-linux_x86_64.whl#sha256=38b49393f8c322dcaa29d19e5acbf5a0b1978cf1b719445ab670f1fb486e3aa6
torchsummary==1.5.1
torchtext==0.18.0
torchvision @ https://download.pytorch.org/whl/cu121/torchvision-0.18.0%2Bcu121-cp310-cp310-linux_x86_64.whl#sha256=13e1b48dc5ce41ccb8100ab3dd26fdf31d8f1e904ecf2865ac524493013d0df5
tornado==6.3.3
tqdm==4.66.4
traitlets==5.7.1
traittypes==0.2.1
transformers==4.41.2
triton==2.3.0
tweepy==4.14.0
typer==0.12.3
types-pytz==2024.1.0.20240417
types-setuptools==70.0.0.20240524
typing_extensions==4.12.2
tzdata==2024.1
tzlocal==5.2
uc-micro-py==1.0.3
ultralytics==8.2.39
ultralytics-thop==2.0.0
universal-analytics-python3==1.1.1
uritemplate==4.1.1
urllib3==2.0.7
vega-datasets==0.9.0
voxel51-eta==0.12.6
wadllib==1.3.6
wasabi==1.1.3
wcwidth==0.2.13
weasel==0.4.1
webcolors==24.6.0
webencodings==0.5.1
websocket-client==1.8.0
Werkzeug==3.0.3
widgetsnbextension==3.6.6
wordcloud==1.9.3
wrapt==1.14.1
wsproto==1.2.0
xarray==2023.7.0
xarray-einstats==0.7.0
xgboost==2.0.3
xlrd==2.0.1
xmltodict==0.13.0
xyzservices==2024.6.0
yarl==1.9.4
yellowbrick==1.5
yfinance==0.2.40
zict==3.0.0
zipp==3.19.2
```

### Minimal Reproducible Example

Colab notebook:

https://colab.research.google.com/drive/1OVD6G4sU-_X_EQXFIMEh1VRyyPnLa5BI?usp=sharing

Local code: 

```python
from ultralytics import YOLO
model_pose = YOLO("yolov8m-pose.pt")
result_pose = model_pose(img_path)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@bs7280 hello,

Thank you for providing a detailed report and the minimal reproducible example. It’s great to see your thorough investigation into the issue. Let's address the key points:

1. **Reproducibility**: You've provided a Colab notebook and local code example, which is very helpful. This allows us to replicate the issue on our end.

2. **Environment**: You've mentioned that the issue occurs on both an M1 Mac and a Colab notebook. This suggests that the problem is not hardware-specific.

3. **Observations**: The keypoints are correctly plotted using `results[0].plot()`, but accessing the keypoints data directly shows some points as `(0,0)`.

### Steps to Verify and Troubleshoot

1. **Ensure Latest Versions**:
   - Please make sure you are using the latest versions of `ultralytics` and `torch`. You can upgrade them using:
     ```bash
     pip install --upgrade ultralytics torch
     ```

2. **Check Keypoint Confidence**:
   - It appears that the keypoints with `(0,0)` coordinates have low confidence scores. This might be an intentional filtering mechanism. You can filter out low-confidence keypoints manually:
     ```python
     keypoints = result_pose[0].keypoints
     high_confidence_keypoints = keypoints[keypoints.conf > 0.1]  # Adjust threshold as needed
     ```

3. **Plotting vs. Data Extraction**:
   - The `plot()` method might be handling low-confidence keypoints differently. To ensure consistency, you can visualize the keypoints with confidence filtering:
     ```python
     import matplotlib.pyplot as plt

     keypoints = result_pose[0].keypoints
     high_confidence_keypoints = keypoints[keypoints.conf > 0.1]  # Adjust threshold as needed

     plt.imshow(result_pose[0].orig_img)
     for kp in high_confidence_keypoints:
         plt.scatter(kp[0], kp[1], c='r')
     plt.show()
     ```

### Next Steps

1. **Run the Updated Code**:
   - Please run the above code snippets in your environment to see if filtering out low-confidence keypoints resolves the issue.

2. **Provide Feedback**:
   - If the issue persists, please let us know. We can further investigate and provide additional support.

For more detailed information on handling keypoints and other features, you can refer to our [documentation](https://docs.ultralytics.com/hub/inference-api/).

Thank you for your cooperation and understanding. We look forward to resolving this issue together.

**Comment by bs7280** [comment]
Thank you @glenn-jocher  for the detailed response. This explains some subtle features of the model. I'm seeing low confidence values for the problem keypoints, but im surprised the model doesn't try to predict those points. I think the core issue im now realizing is that the v8 pose model will NOT estimate keypoints that aren't visible? 

This is surprising to me - as I came from using the v7 model which did predict all keypoints even if they weren't visible. For example, my second image where the left arm, shoulder, and ear are not visible. 

Am I understanding this limitation of v8 pose models correctly? Is there a way to force the model to try and estimate them?

**Comment by glenn-jocher** [comment]
Hello @bs7280,

Thank you for your detailed follow-up and observations. It's great to see your engagement and understanding of the model's behavior.

### Keypoint Visibility in YOLOv8 Pose Models

You are correct in noting that YOLOv8's pose model behavior differs from YOLOv7 in terms of keypoint prediction. YOLOv8 is designed to provide more accurate and reliable predictions by not estimating keypoints that it deems to have low confidence, which often corresponds to keypoints that are not visible or are highly occluded.

### Addressing Your Concerns

1. **Low Confidence Keypoints**:
   - The model's decision to not predict certain keypoints is based on the confidence threshold. This is intended to avoid false positives and ensure the reliability of the detected keypoints.

2. **Differences from YOLOv7**:
   - As you mentioned, YOLOv7 might predict all keypoints regardless of visibility, which can sometimes lead to less accurate results for occluded keypoints. YOLOv8 aims to improve this by being more conservative in its predictions.

### Potential Solutions

While YOLOv8 does not natively support forcing the prediction of all keypoints regardless of visibility, you can experiment with the following approaches:

1. **Lowering the Confidence Threshold**:
   - You can adjust the confidence threshold to include more keypoints, though this might introduce some noise.
     ```python
     keypoints = result_pose[0].keypoints
     low_confidence_threshold = 0.05  # Adjust as needed
     all_keypoints = keypoints[keypoints.conf > low_confidence_threshold]
     ```

2. **Post-Processing**:
   - Implement a post-processing step to estimate the positions of missing keypoints based on the visible ones. This can be done using interpolation or other heuristic methods.

### Example Code

Here's a snippet to help you get started with lowering the confidence threshold:
```python
from ultralytics import YOLO

# Load the model
model_pose = YOLO("yolov8m-pose.pt")

# Run prediction
result_pose = model_pose("path/to/your/image.jpg")

# Extract keypoints with a lower confidence threshold
keypoints = result_pose[0].keypoints
low_confidence_threshold = 0.05  # Adjust as needed
all_keypoints = keypoints[keypoints.conf > low_confidence_threshold]

# Visualize the keypoints
import matplotlib.pyplot as plt

plt.imshow(result_pose[0].orig_img)
for kp in all_keypoints:
    plt.scatter(kp[0], kp[1], c='r')
plt.show()
```

### Conclusion

While YOLOv8's approach to keypoint prediction is designed to enhance accuracy by avoiding low-confidence predictions, we understand the need for flexibility in certain applications. Experimenting with confidence thresholds and post-processing techniques can help achieve the desired results.

If you have any further questions or need additional assistance, feel free to reach out. We're here to help! 😊

**Comment by bs7280** [comment]
Thank you, that makes sense. Is this a side effect of the training data used to make the v8 pose models, or a limitation on the architecture itself. If I were to hypothetically train my own pose model (fine tuning existing pose models or on a custom skeleton from scratch) would I be able to get an estimation of every keypoint every time? Albeit inaccurate?

**Comment by glenn-jocher** [comment]
Hello @bs7280,

Thank you for your insightful question! The behavior you're observing is primarily influenced by the training data and the model's architecture. YOLOv8's pose models are designed to prioritize accuracy and reliability, which is why they may not predict keypoints with low confidence, especially when they are occluded or not visible.

### Training Data vs. Model Architecture

1. **Training Data**:
   - The datasets used to train YOLOv8 pose models likely contain annotations that emphasize visible keypoints, leading the model to focus on predicting keypoints it can confidently identify.

2. **Model Architecture**:
   - The architecture itself is optimized to provide high-confidence predictions, which can result in not estimating keypoints that are not clearly visible.

### Custom Training and Fine-Tuning

If you decide to train your own pose model, either by fine-tuning existing models or training from scratch with a custom skeleton, you can indeed influence the model's behavior:

1. **Custom Training**:
   - By using a dataset where all keypoints are annotated, even if they are not visible, you can encourage the model to predict all keypoints. This might result in less accurate predictions for occluded keypoints, but it will attempt to estimate them.

2. **Fine-Tuning**:
   - Fine-tuning an existing model with a dataset that includes annotations for all keypoints, regardless of visibility, can help achieve your goal. However, be mindful that this might introduce some noise in the predictions.

### Example Code for Custom Training

Here's a simplified example to get you started with fine-tuning a YOLOv8 pose model:

```python
from ultralytics import YOLO

# Load a pre-trained YOLOv8 pose model
model = YOLO("yolov8m-pose.pt")

# Fine-tune the model on your custom dataset
model.train(data="path/to/your/custom_dataset.yaml", epochs=50, imgsz=640)
```

### Conclusion

By customizing your training data and fine-tuning the model, you can influence its behavior to estimate all keypoints, even if they are not visible. This approach provides flexibility but may come at the cost of reduced accuracy for occluded keypoints.

If you have any further questions or need additional assistance, feel free to reach out. We're here to help! 😊

**Comment by bs7280** [comment]
ok awesome, thankyou. One last question - do you suggest a tool to manually label / tweak keypoint data from model predictions? Ive looked at a handful of tools online but having a hard time finding one that specifically lets me import YOLO8 predictions for pose models. I've seen tools that let me annotate from scratch but thats a LOT of extra work, when I just need to fix some frames here and there.

**Comment by glenn-jocher** [comment]
Hello @bs7280,

Great to hear that the previous information was helpful! For your current need to manually label or tweak keypoint data from model predictions, there are indeed some tools that can streamline this process without starting from scratch.

### Recommended Tools for Keypoint Annotation

1. **Label Studio**:
   - Label Studio is a versatile tool that supports various annotation tasks, including keypoint annotation. You can import your YOLOv8 predictions and adjust them as needed.
   - [Label Studio](https://labelstud.io/)

2. **CVAT (Computer Vision Annotation Tool)**:
   - CVAT is another robust tool that supports keypoint annotation. It allows you to import existing annotations and modify them, which can save you a lot of time.
   - [CVAT](https://cvat.org/)

3. **Supervisely**:
   - Supervisely offers a comprehensive platform for various annotation tasks, including keypoints. It supports importing pre-annotated data, making it easier to tweak existing predictions.
   - [Supervisely](https://supervise.ly/)

### Example Workflow with Label Studio

Here’s a brief example of how you might use Label Studio to tweak your YOLOv8 keypoint predictions:

1. **Install Label Studio**:
   ```bash
   pip install label-studio
   ```

2. **Start Label Studio**:
   ```bash
   label-studio start
   ```

3. **Import Your Data**:
   - Export your YOLOv8 predictions to a format supported by Label Studio (e.g., JSON).
   - Import the JSON file into Label Studio and start tweaking the keypoints.

### Conclusion

These tools should help you efficiently adjust your keypoint annotations without the need to start from scratch. If you have any further questions or need additional assistance, feel free to reach out. We're here to help! 😊
