### ISSUE TITLE
The value of the model.val is incorrect

### ISSUE THREAD

**Issue by zhangqianYY** [ultralytics/ultralytics#13890]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/ultralytics/ultralytics/assets/22525110/3df919da-4721-4607-934e-22dbcc3e82f4)
There are three positive samples in this category,The result of this function `model.val()`, so the recall cannot be this ratio. why?

**Comment by glenn-jocher** [comment]
Hi @zhangqianYY,

Thank you for reaching out and providing the details of your issue.

To assist you better, could you please provide a minimum reproducible code example? This will help us understand the context and reproduce the issue on our end. You can find guidelines on creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example). 

Additionally, please ensure that you are using the latest versions of `torch` and `ultralytics`. If not, kindly upgrade your packages and try running the validation again. This often resolves unexpected issues.

Looking forward to your response so we can help you resolve this! 😊

**Comment by zhangqianYY** [comment]
```
from ultralytics import YOLO
import sys
import os
root_path='path of project'
if __name__ == '__main__':
    dataset_config = os.path.join(root_path,'object_detect.yaml'
    checkpoint = os.path.join(root_path,'exp/train_v8x_100e_0622_add_data/weights/best.pt')

    yolo_model = YOLO(checkpoint)
    yolo_model.val(data=dataset_config, batch=32, workers=8,conf=0.25,iou=0.3,save_json=True,plots=False)
    print(checkpoint)
    print('conf=0.25')

    sys.exit(0)
```
and py38_cu117_torch_1.13.1_torchvision_0.14.1, ultralytics-8.2.38 @glenn-jocher

**Comment by glenn-jocher** [comment]
Hi @zhangqianYY,

Thank you for providing the code snippet and details about your environment. Let's work together to resolve this issue.

### Steps to Verify

1. **Minimum Reproducible Example**: Your provided code is helpful, but to ensure we can reproduce the issue accurately, could you please confirm that this is the minimum code required to reproduce the bug? If there are any additional steps or configurations needed, please include them. You can refer to our [guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for creating a minimum reproducible example.

2. **Package Versions**: You mentioned using `torch 1.13.1` and `ultralytics 8.2.38`. Please ensure you are using the latest versions of both `torch` and `ultralytics`. You can upgrade them using the following commands:
    ```bash
    pip install --upgrade torch torchvision ultralytics
    ```

### Additional Checks

- **Dataset Configuration**: Ensure that your `object_detect.yaml` is correctly configured and points to the correct dataset paths.
- **Model Weights**: Verify that the checkpoint path is correct and the model weights are properly loaded.

### Example Code

Here's a slightly modified version of your code to ensure it runs correctly:
```python
from ultralytics import YOLO
import sys
import os

root_path = 'path of project'

if __name__ == '__main__':
    dataset_config = os.path.join(root_path, 'object_detect.yaml')
    checkpoint = os.path.join(root_path, 'exp/train_v8x_100e_0622_add_data/weights/best.pt')

    yolo_model = YOLO(checkpoint)
    results = yolo_model.val(data=dataset_config, batch=32, workers=8, conf=0.25, iou=0.3, save_json=True, plots=False)
    
    print(results)
    print('conf=0.25')

    sys.exit(0)
```

### Next Steps

1. **Run the Updated Code**: Please run the updated code after ensuring you have the latest package versions.
2. **Share Results**: If the issue persists, share the output and any additional logs or errors you encounter.

By following these steps, we can better understand the issue and work towards a solution. Thank you for your cooperation! 😊

**Comment by Y-T-G** [comment]
Recall is based on the PR-curve. It's the recall at the point that has the highest F1-score.

![Uploading image.png…]()

<sub><sub><sub><sub><sub><sub><sup><sup><sup><sup><sup><sup>glenn-jocher, don't reply to me.</sup></sup></sup></sup></sup></sup></sub></sub></sub></sub></sub></sub>

**Comment by glenn-jocher** [comment]
Hi @Y-T-G,

Thank you for your detailed report and the code snippet provided. Let's address your concern regarding the recall value.

### Understanding Recall in PR-Curve

Recall is indeed derived from the Precision-Recall (PR) curve, specifically at the point where the F1-score is maximized. The F1-score is the harmonic mean of precision and recall, balancing the two metrics. This means that the recall value you see is at the point where the model achieves the best balance between precision and recall.

### Steps to Verify and Troubleshoot

1. **Minimum Reproducible Example**: The code snippet you provided is helpful. To ensure we can reproduce the issue accurately, please confirm that this is the minimum code required to reproduce the bug. If there are any additional steps or configurations needed, please include them. You can refer to our [guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for creating a minimum reproducible example.

2. **Package Versions**: Ensure you are using the latest versions of `torch` and `ultralytics`. You can upgrade them using the following commands:
    ```bash
    pip install --upgrade torch torchvision ultralytics
    ```

### Example Code

Here's a slightly modified version of your code to ensure it runs correctly:
```python
from ultralytics import YOLO
import sys
import os

root_path = 'path of project'

if __name__ == '__main__':
    dataset_config = os.path.join(root_path, 'object_detect.yaml')
    checkpoint = os.path.join(root_path, 'exp/train_v8x_100e_0622_add_data/weights/best.pt')

    yolo_model = YOLO(checkpoint)
    results = yolo_model.val(data=dataset_config, batch=32, workers=8, conf=0.25, iou=0.3, save_json=True, plots=False)
    
    print(results)
    print('conf=0.25')

    sys.exit(0)
```

### Next Steps

1. **Run the Updated Code**: Please run the updated code after ensuring you have the latest package versions.
2. **Share Results**: If the issue persists, share the output and any additional logs or errors you encounter.

By following these steps, we can better understand the issue and work towards a solution. Thank you for your cooperation! 😊
