### ISSUE TITLE
yolov8 exported to openvino lacks .mapping file

### ISSUE THREAD

**Issue by ddeddedere** [ultralytics/ultralytics#13899]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

model = YOLO("best.pt")
model.export(format='openvino')
I used these codes to generate only .xml, .bin, .yaml

**Comment by glenn-jocher** [comment]
Hi @ddeddedere,

Thank you for bringing this to our attention! It looks like you're encountering an issue with the `.mapping` file not being generated during the OpenVINO export process.

To assist you better, could you please confirm the following:
1. Are you using the latest versions of `torch` and `ultralytics`? If not, please update your packages and try exporting again.
2. Could you provide a minimum reproducible code example? This will help us investigate the issue more effectively. You can refer to our guide on creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Here's a quick example of how the export process should look:

```python
from ultralytics import YOLO

# Load a YOLOv8 model
model = YOLO("best.pt")

# Export the model to OpenVINO format
model.export(format="openvino")
```

This should generate the `.xml`, `.bin`, and `.mapping` files. If the issue persists after updating and providing the reproducible example, we'll be able to dive deeper into the problem.

Looking forward to your response!
