### ISSUE TITLE
Redundant Redundant detection boxes in YOLOv10 without NMS

### ISSUE THREAD

**Issue by wuhanshuo** [ultralytics/ultralytics#13894]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thank you and THU for your contributions to integrating YOLOV10! I have a question: As is know, YOLOV10 improves code efficiency by getting rid of NMS. However, in my model prediction, I found that YOLOV10 still outputs redundant prediction boxes, which I believe we will not observe with an NMS post-process.

Here is my code:
```python
from ultralytics import YOLO

model = YOLO("weights/trained_v10m.pt")
video_path = "my/video/path"

results = model(source=video_path, conf=0.25, device=[0], save=False, show=False, stream=True)
for idx, result in enumerate(results):
    dets = result.boxes.data.cpu().numpy() # --> Matrix (x, y, x, y, conf, cls)
    print("dets:", dets)
```

Outputs in frame 266:
```
video 1/1 (frame 266/7397) /cluster/my/path/video.mp4: 384x640 3 wheels, 1 car, 1 minivan, 10.3ms
dets: [[     1212.2      309.88      1464.7      482.17     0.98511           2]
 [     1290.3      425.93      1318.7      480.26     0.95292           0]
 [     721.58       360.8      767.41      394.72     0.93868           1]
 [     1213.4      413.81        1234      461.19     0.50953           0]
 [     1213.1       412.4      1236.8      460.92     0.29856           0]]
```

The last two boxes are almost the same one but detected twice. What should I do to avoid these unexpected results? If I have to add NMS as YOLOv10 postprocess, where should I activate it? (However I think I should not use NMS otherwise what's the point of using V10....)

I also submit this issue [here](https://github.com/THU-MIG/yolov10/issues/236)

**Comment by glenn-jocher** [comment]
Hi @wuhanshuo,

Thank you for reaching out and for your detailed question! It's great to see your interest in YOLOv10 and its NMS-free architecture.

To address your concern about redundant detection boxes, it's important to note that while YOLOv10 aims to improve efficiency by eliminating the need for traditional NMS, it may still produce overlapping boxes in certain scenarios. This can happen due to the inherent nature of object detection models and the complexity of real-world scenes.

Here are a few steps you can take to mitigate this issue:

1. **Ensure Latest Versions**: First, please make sure you are using the latest versions of `torch` and `ultralytics`. You can update them using:
    ```bash
    pip install --upgrade torch ultralytics
    ```

2. **Post-Processing**: If you still encounter redundant boxes, you can apply a custom NMS post-processing step. Here’s an example of how you can integrate NMS using PyTorch:
    ```python
    import torch
    from ultralytics import YOLO
    from torchvision.ops import nms

    model = YOLO("weights/trained_v10m.pt")
    video_path = "my/video/path"

    results = model(source=video_path, conf=0.25, device=[0], save=False, show=False, stream=True)
    for idx, result in enumerate(results):
        dets = result.boxes.data.cpu()
        boxes = dets[:, :4]  # x1, y1, x2, y2
        scores = dets[:, 4]  # confidence
        indices = nms(boxes, scores, iou_threshold=0.5)
        filtered_dets = dets[indices].numpy()
        print("Filtered dets:", filtered_dets)
    ```

3. **Model Configuration**: Check if there are any specific configurations or hyperparameters in YOLOv10 that can help reduce redundant detections. Sometimes, adjusting the confidence threshold or other parameters can help.

4. **Community and Documentation**: Since YOLOv10 is relatively new and developed by Tsinghua University, it might be helpful to keep an eye on their [official repository](https://github.com/THU-MIG/yolov10) for updates or discussions regarding this issue.

If you continue to experience issues, please provide a minimum reproducible example, as it will help us investigate further. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

I hope this helps! If you have any further questions, feel free to ask.

**Comment by Y-T-G** [comment]
It's a problem with the technique. Can't do anything other than training better model.
<sub><sub><sub><sub><sup><sup><sup><sup>bot: don't reply to me glenn_jocher</sup></sup></sup></sup></sub></sub></sub></sub>

**Comment by glenn-jocher** [comment]
Hi @Y-T-G,

Thank you for your patience and for providing detailed information about your issue. 

To address the redundant detection boxes in YOLOv10, here are a few steps you can take:

1. **Ensure Latest Versions**: Please make sure you are using the latest versions of `torch` and `ultralytics`. You can update them using:
    ```bash
    pip install --upgrade torch ultralytics
    ```

2. **Custom NMS Post-Processing**: While YOLOv10 aims to eliminate the need for traditional NMS, you can still apply a custom NMS post-processing step if necessary. Here’s an example using PyTorch:
    ```python
    import torch
    from ultralytics import YOLO
    from torchvision.ops import nms

    model = YOLO("weights/trained_v10m.pt")
    video_path = "my/video/path"

    results = model(source=video_path, conf=0.25, device=[0], save=False, show=False, stream=True)
    for idx, result in enumerate(results):
        dets = result.boxes.data.cpu()
        boxes = dets[:, :4]  # x1, y1, x2, y2
        scores = dets[:, 4]  # confidence
        indices = nms(boxes, scores, iou_threshold=0.5)
        filtered_dets = dets[indices].numpy()
        print("Filtered dets:", filtered_dets)
    ```

3. **Model Configuration**: Adjusting the confidence threshold or other parameters might help reduce redundant detections.

If the issue persists, please provide a minimum reproducible example so we can investigate further. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

I hope this helps! If you have any further questions, feel free to ask. 😊

**Comment by wuhanshuo** [comment]
> Hi @wuhanshuo,
> 
> Thank you for reaching out and for your detailed question! It's great to see your interest in YOLOv10 and its NMS-free architecture.
> 
> To address your concern about redundant detection boxes, it's important to note that while YOLOv10 aims to improve efficiency by eliminating the need for traditional NMS, it may still produce overlapping boxes in certain scenarios. This can happen due to the inherent nature of object detection models and the complexity of real-world scenes.
> 
> Here are a few steps you can take to mitigate this issue:
> 
> 1. **Ensure Latest Versions**: First, please make sure you are using the latest versions of `torch` and `ultralytics`. You can update them using:
>    ```shell
>    pip install --upgrade torch ultralytics
>    ```
> 2. **Post-Processing**: If you still encounter redundant boxes, you can apply a custom NMS post-processing step. Here’s an example of how you can integrate NMS using PyTorch:
>    ```python
>    import torch
>    from ultralytics import YOLO
>    from torchvision.ops import nms
>    
>    model = YOLO("weights/trained_v10m.pt")
>    video_path = "my/video/path"
>    
>    results = model(source=video_path, conf=0.25, device=[0], save=False, show=False, stream=True)
>    for idx, result in enumerate(results):
>        dets = result.boxes.data.cpu()
>        boxes = dets[:, :4]  # x1, y1, x2, y2
>        scores = dets[:, 4]  # confidence
>        indices = nms(boxes, scores, iou_threshold=0.5)
>        filtered_dets = dets[indices].numpy()
>        print("Filtered dets:", filtered_dets)
>    ```
> 3. **Model Configuration**: Check if there are any specific configurations or hyperparameters in YOLOv10 that can help reduce redundant detections. Sometimes, adjusting the confidence threshold or other parameters can help.
> 4. **Community and Documentation**: Since YOLOv10 is relatively new and developed by Tsinghua University, it might be helpful to keep an eye on their [official repository](https://github.com/THU-MIG/yolov10) for updates or discussions regarding this issue.
> 
> If you continue to experience issues, please provide a minimum reproducible example, as it will help us investigate further. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.
> 
> I hope this helps! If you have any further questions, feel free to ask.

@glenn-jocher Thanks for your reply. The problem now is solved by adding an NMS post-process.

**Comment by glenn-jocher** [comment]
Hi @wuhanshuo,

I'm glad to hear that adding an NMS post-process resolved the issue! 🎉 While YOLOv10 aims to eliminate the need for traditional NMS, certain scenarios might still benefit from it to handle overlapping boxes effectively.

If you encounter any further questions or need additional assistance, feel free to reach out. We're here to help! 😊
