### ISSUE TITLE
Multiple questions including getting Yolo data in real time and more

### ISSUE THREAD

**Issue by mazik1496** [ultralytics/ultralytics#1389]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to get Yolo custom data in real time through opencv in the gazebo environment. I roughly implemented the code, but it is not accepted as a real-time video. I would like to know the cause and solution for this (source code is attached below).

Also, this is a question I'm curious about, and I'm also curious about whether coco128's yolo data set can be applied in a virtual environment like gazebo, and whether coco128 and custom data can be combined.

------------Yolo data in real time source code--------------
#!/usr/bin/env python3
import sys
import rospy
import time
import matplotlib.pyplot as plt
from geometry_msgs.msg import Twist
from std_msgs.msg import Float32
from vrx_gazebo.srv import BallShooter
from std_msgs.msg import Empty
from sensor_msgs.msg import Image 
from cv_bridge import CvBridge, CvBridgeError 
import cv2
import numpy as np
from ultralytics import YOLO

bridge_object = CvBridge() # create the cv_bridge object 
image_received = 0 #Flag to indicate that we have already received an image 
cv_image1 = 0 #This is just to create the global variable cv_image
cv_image2 = 0 #This is just to create the global variable cv_image 
distance = 0
x_left = 0
x_right = 0

class Node():
    def __init__(self,linear_scaling,angular_scaling):
        self.linear_scaling = linear_scaling
        self.angular_scaling = angular_scaling
        self.left_pub = None
        self.right_pub = None
        self.left_msg =None
        self.right_msg =None
        #self.keyboard = keyboard
        self.shooter_pub = None

    def callback(self,data):
        rospy.logdebug("RX: Twist "+rospy.get_caller_id())
        rospy.logdebug("linear:")   
        rospy.logdebug("x:%f,y:%f,z:%f"%(data.linear.x,data.linear.y,data.linear.z))                                   
        rospy.logdebug("angular:")
        rospy.logdebug("x:%f,y:%f,z:%f"%(data.angular.x,data.angular.y,data.angular.z))
           
        # scaling factors
        linfac = self.linear_scaling
        angfac = self.angular_scaling
        
def show_image(): 
    global distance
    global disparity
    global x_left
    global x_right
    
    while not rospy.is_shutdown():  
        if image_received:
            model = YOLO("/home/user/vrx_ws/src/vrx/vrx_gazebo/nodes/runs/detect/train14/weights/best.pt")
            
      	    # resize image 800x400
            cv_image1_resize = cv2.resize(cv_image1,(800,400))
            cv_image2_resize = cv2.resize(cv_image2,(800,400))
            
            image1 = cv_image1_resize.copy()
            image2 = cv_image2_resize.copy()

            result1=model(image1,show=True)
            result2=model(image2,show=True)
            cv2.imshow('Image from robot left camera', image1)
            cv2.imshow('Image from robot right camera', image2)
            #cv2.imshow('HSV left camera', img_plus1)
            #cv2.imshow('HSV right camera', img_plus2)
            #cv2.imshow('Erosion left camera', result1)
            #cv2.imshow('Erosion right camera', result2)
            #cv2.imwrite('/home/user/Pictures/Result1.png', img_plus1)
            #cv2.imwrite('/home/user/Pictures/Result_of_Original.png', cv_image1_resize)
            #cv2.imwrite('/home/user/Pictures/Result2.png', img_plus2)
            cv2.waitKey(0) 
            r.sleep()  
            #rospy.Subscriber("cmd_vel",Twist,node.callback)
    cv2.destroyAllWindows()  
    
def camera_left_callback(data): 
    global bridge_object 
    global cv_image1 
    global image_received 
    image_received=1 
    try: 
        # We select bgr8 because its the OpenCV encoding by default 
        cv_image1 = bridge_object.imgmsg_to_cv2(data,"bgr8")
    except CvBridgeError as e: 
        print(e)
        
def camera_right_callback(data): 
    global bridge_object 
    global cv_image2 
    global image_received 
    image_received=1 
    try: 
        # We select bgr8 because its the OpenCV encoding by default 
        cv_image2 = bridge_object.imgmsg_to_cv2(data,"bgr8")
    except CvBridgeError as e: 
        print(e)

if __name__ == '__main__': 
    rospy.init_node('onekw_cam', anonymous=True)
    left_image_sub = rospy.Subscriber("left_camera/image_raw_left",Image,camera_left_callback)
    right_image_sub = rospy.Subscriber("right_camera/image_raw_right",Image,camera_right_callback)
    r = rospy.Rate(10)
    plt.figure()
    show_image()

**Comment by glenn-jocher** [comment]
@mazik1496 see https://docs.ultralytics.com/modes/predict for inference examples.
