### ISSUE TITLE
The ‘classes’ method in model.predict() seems to be not applicable to the yolov10 model.

### ISSUE THREAD

**Issue by Andy718811** [ultralytics/ultralytics#13907]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

When I set classes in predict function like this "results= model.predict(img,conf=0.01,half=True,classes=[1],imgsz=640)", the yolov10 model still detected the classes other than the class 1, and this problem only happens when I using yolov10 model like this "from ultralytics import YOLO

# Load a pre-trained YOLOv10n model
model = YOLO("yolov10n.pt")"

### Environment

My python version is 3.8.19.
And here is my environment in anaconda
----------------------------------------------------------
absl-py                      1.0.0
albucore                     0.0.9
albumentations               1.4.8
annotated-types              0.7.0
anylabeling                  0.3.3
asttokens                    2.4.1
astunparse                   1.6.3
backcall                     0.2.0
cachetools                   4.2.4
certifi                      2024.2.2
charset-normalizer           3.3.2
click                        8.1.7
clip                         1.0
colorama                     0.4.6
coloredlogs                  15.0.1
comm                         0.2.2
contourpy                    1.1.1
cycler                       0.12.1
darkdetect                   0.8.0
debugpy                      1.8.1
decorator                    5.1.1
dill                         0.3.8
executing                    2.0.1
filelock                     3.13.3
filterpy                     1.4.5
fire                         0.6.0
flatbuffers                  2.0
fonttools                    4.50.0
ftfy                         6.2.0
func-timeout                 4.3.5
gast                         0.4.0
genetic-algorithm            1.0.0
geneticalgorithm             1.0.2
gitdb                        4.0.11
GitPython                    3.1.43
google-auth                  2.3.3
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grpcio                       1.43.0
humanfriendly                10.0
idna                         3.6
imageio                      2.34.1
imgviz                       1.7.5
importlib-metadata           4.10.0
importlib_resources          6.4.0
ipykernel                    6.29.3
ipython                      8.12.2
jedi                         0.19.1
Jinja2                       3.1.3
joblib                       1.4.0
jupyter_client               8.6.1
jupyter_core                 5.7.2
Keras-Preprocessing          1.1.2
keyboard                     0.13.5
kiwisolver                   1.4.5
lapx                         0.5.9
lazy_loader                  0.4
libclang                     12.0.0
Markdown                     3.3.6
markdown-it-py               3.0.0
MarkupSafe                   2.1.5
matplotlib                   3.7.5
matplotlib-inline            0.1.6
mdurl                        0.1.2
MouseInfo                    0.1.3
mpmath                       1.3.0
mss                          6.0.0
natsort                      8.4.0
nest_asyncio                 1.6.0
networkx                     3.1
numpy                        1.24.4
nvidia-cuda-runtime-cu12     12.4.127
oauthlib                     3.2.2
onnx                         1.13.1
onnxruntime                  1.14.1
onnxruntime-gpu              1.17.1
onnxsim                      0.4.36
onnxslim                     0.1.28
opencv-contrib-python        4.4.0.46
opencv-python                4.9.0.80
opencv-python-headless       4.9.0.80
opt-einsum                   3.3.0
packaging                    24.0
pandas                       2.0.3
parso                        0.8.4
pickleshare                  0.7.5
pillow                       10.3.0
pip                          23.3.1
platformdirs                 4.2.0
prompt-toolkit               3.0.42
protobuf                     3.20.3
psutil                       5.9.8
pure-eval                    0.2.2
py-cpuinfo                   9.0.0
pyasn1                       0.6.0
pyasn1_modules               0.4.0
PyAutoGUI                    0.9.54
pybboxes                     0.1.6
pycocotools                  2.0.7
pydantic                     2.7.3
pydantic_core                2.18.4
PyGetWindow                  0.0.9
Pygments                     2.17.2
PyMsgBox                     1.0.9
pynput                       1.7.6
pyparsing                    3.1.2
pyperclip                    1.8.2
pypid                        0.4
PyQt5                        5.15.10
PyQt5-Qt5                    5.15.2
PyQt5-sip                    12.13.0
pyreadline3                  3.4.1
PyRect                       0.2.0
PyScreeze                    0.1.30
python-dateutil              2.9.0
pytweening                   1.2.0
pytz                         2024.1
PyWavelets                   1.4.1
pywin32                      306
PyYAML                       6.0.1
pyzmq                        25.1.2
qimage2ndarray               1.10.0
regex                        2024.4.28
requests                     2.31.0
requests-oauthlib            2.0.0
rich                         13.7.1
rsa                          4.9
sahi                         0.11.15
scikit-image                 0.21.0
scikit-learn                 1.3.2
scipy                        1.10.1
seaborn                      0.13.2
setuptools                   68.2.2
shapely                      2.0.4
simple-pid                   2.0.0
six                          1.16.0
smmap                        5.0.1
stack-data                   0.6.2
sympy                        1.12
tensorboard                  2.7.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.0
tensorflow                   2.7.0
tensorflow-estimator         2.7.0
tensorflow-io-gcs-filesystem 0.23.1
tensorrt                     8.6.0
tensorrt-cu12                10.0.1
tensorrt-cu12_bindings       10.0.1
tensorrt-cu12_libs           10.0.1
termcolor                    1.1.0
terminaltables               3.1.10
thop                         0.1.1.post2209072238
threadpoolctl                3.4.0
tifffile                     2023.7.10
tomli                        2.0.1
torch                        1.13.1+cu117
torchaudio                   0.13.1+cu117
torchvision                  0.14.1+cu117
tornado                      6.4
tqdm                         4.66.2
traitlets                    5.14.2
typing_extensions            4.10.0
tzdata                       2024.1
ultralytics                  8.2.38
ultralytics-thop             2.0.0
urllib3                      2.2.1
wcwidth                      0.2.13
Werkzeug                     3.0.2
wheel                        0.41.2
xgboost                      2.0.3
yolov6                       0.0.1
zipp                         3.17.0

### Minimal Reproducible Example

Load model like this 
"from ultralytics import YOLO

# Load a pre-trained YOLOv10n model
model = YOLO("yolov10n.pt")"

And then set classes=[1] in model.predict like this "results= model.predict(img,conf=0.01,half=True,classes=[1],imgsz=640)", and you will probably see it detected classes other than class 1.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Andy718811 hello,

Thank you for bringing this issue to our attention. To better assist you, could you please provide a minimum reproducible code example? This will help us investigate the problem more effectively. You can find guidelines on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of `torch` and `ultralytics`. You can update your packages using the following commands:

```bash
pip install --upgrade torch
pip install --upgrade ultralytics
```

If the issue persists after updating, please let us know so we can further investigate. Your cooperation is greatly appreciated! 😊

**Comment by Andy718811** [comment]
Thank you for your reply, I have confirmed that my Ultralytics is the latest version 8.2.41, and my Torch version is compatible with the Ultralytics installation package.

Here is the picture for testing
![bus](https://github.com/ultralytics/ultralytics/assets/87431291/c8a9021a-e340-4a72-9416-9a8c2d0c2345)

And the following is the minimum reproducible code, it compares the results between two different models.
The result I got is like this
![image](https://github.com/ultralytics/ultralytics/assets/87431291/4d158056-a672-48d6-8e87-126fc4729fbd)

````from ultralytics import YOLO
model = YOLO(r'yolov10s.pt')

img=cv2.imread(f'bus.jpg')

results= model.predict(img,conf=0.01,half=True,classes=[0],imgsz=640)

model = YOLO(r'yolov8s.pt')

results= model.predict(img,conf=0.01,half=True,classes=[0],imgsz=640)```

**Comment by glenn-jocher** [comment]
Hello @Andy718811,

Thank you for providing the additional details and the reproducible code example. This is very helpful! 😊

It appears that the `classes` parameter is not being respected when using the YOLOv10 model. Let's delve into this further.

First, let's ensure that the `classes` parameter is correctly applied by adding a print statement to check the filtered classes:

```python
from ultralytics import YOLO
import cv2

# Load the image
img = cv2.imread('bus.jpg')

# Load YOLOv10 model
model_v10 = YOLO('yolov10s.pt')
results_v10 = model_v10.predict(img, conf=0.01, half=True, classes=[0], imgsz=640)
print("YOLOv10 Results:", results_v10)

# Load YOLOv8 model
model_v8 = YOLO('yolov8s.pt')
results_v8 = model_v8.predict(img, conf=0.01, half=True, classes=[0], imgsz=640)
print("YOLOv8 Results:", results_v8)
```

If the issue persists, it might be a bug specific to the YOLOv10 implementation. In that case, we will need to investigate further. 

Meanwhile, as a workaround, you can manually filter the results to include only the desired classes:

```python
# Filter results manually for YOLOv10
filtered_results_v10 = [res for res in results_v10 if res['class'] == 0]
print("Filtered YOLOv10 Results:", filtered_results_v10)

# Filter results manually for YOLOv8
filtered_results_v8 = [res for res in results_v8 if res['class'] == 0]
print("Filtered YOLOv8 Results:", filtered_results_v8)
```

We appreciate your patience and understanding as we work to resolve this issue. If you have any further questions or need additional assistance, please feel free to ask!

**Comment by Andy718811** [comment]
@glenn-jocher Thank you for your reply.

I ran this code, and I got this result

"0: 640x480 6 persons, 1 bus, 1 traffic light, 2 stop signs, 3 handbags, 2 ties, 1 potted plant, 21.5ms
Speed: 4.9ms preprocess, 21.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 480)
YOLOv10 Results: [ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
masks: None
names: {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 
'cake', 56: 'chair', 57: 'couch', 58: 'potted plant', 59: 'bed', 60: 'dining table', 61: 'toilet', 62: 'tv', 63: 'laptop', 64: 'mouse', 65: 'remote', 66: 'keyboard', 67: 'cell phone', 68: 'microwave', 69: 'oven', 70: 'toaster', 71: 
'sink', 72: 'refrigerator', 73: 'book', 74: 'clock', 75: 'vase', 76: 'scissors', 77: 'teddy bear', 78: 'hair drier', 79: 'toothbrush'}
obb: None
orig_img: array([[[119, 146, 172],
        [121, 148, 174],
        [122, 152, 177],
        ...,
        [161, 171, 188],
        [160, 170, 187],
        [160, 170, 187]],

       [[120, 147, 173],
        [122, 149, 175],
        [123, 153, 178],
        ...,
        [161, 171, 188],
        [160, 170, 187],
        [160, 170, 187]],

       [[123, 150, 176],
        [124, 151, 177],
        [125, 155, 180],
        ...,
        [161, 171, 188],
        [160, 170, 187],
        [160, 170, 187]],

       ...,

       [[183, 182, 186],
        [179, 178, 182],
        [180, 179, 183],
        ...,
        [121, 111, 117],
        [113, 103, 109],
        [115, 105, 111]],

       [[165, 164, 168],
        [173, 172, 176],
        [187, 186, 190],
        ...,
        [102,  92,  98],
        [101,  91,  97],
        [103,  93,  99]],

       [[123, 122, 126],
        [145, 144, 148],
        [176, 175, 179],
        ...,
        [ 95,  85,  91],
        [ 96,  86,  92],
        [ 98,  88,  94]]], dtype=uint8)
orig_shape: (1080, 810)
path: 'image0.jpg'
probs: None
save_dir: 'runs\\detect\\predict'
speed: {'preprocess': 4.878997802734375, 'inference': 21.47221565246582, 'postprocess': 0.9756088256835938}]        

0: 640x480 11 persons, 16.6ms
Speed: 2.9ms preprocess, 16.6ms inference, 4.9ms postprocess per image at shape (1, 3, 640, 480)
YOLOv8 Results: [ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
masks: None
names: {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 
'cake', 56: 'chair', 57: 'couch', 58: 'potted plant', 59: 'bed', 60: 'dining table', 61: 'toilet', 62: 'tv', 63: 'laptop', 64: 'mouse', 65: 'remote', 66: 'keyboard', 67: 'cell phone', 68: 'microwave', 69: 'oven', 70: 'toaster', 71: 
'sink', 72: 'refrigerator', 73: 'book', 74: 'clock', 75: 'vase', 76: 'scissors', 77: 'teddy bear', 78: 'hair drier', 79: 'toothbrush'}
obb: None
orig_img: array([[[119, 146, 172],
        [121, 148, 174],
        [122, 152, 177],
        ...,
        [161, 171, 188],
        [160, 170, 187],
        [160, 170, 187]],

       [[120, 147, 173],
        [122, 149, 175],
        [123, 153, 178],
        ...,
        [161, 171, 188],
        [160, 170, 187],
        [160, 170, 187]],

       [[123, 150, 176],
        [124, 151, 177],
        [125, 155, 180],
        ...,
        [161, 171, 188],
        [160, 170, 187],
        [160, 170, 187]],

       ...,

       [[183, 182, 186],
        [179, 178, 182],
        [180, 179, 183],
        ...,
        [121, 111, 117],
        [113, 103, 109],
        [115, 105, 111]],

       [[165, 164, 168],
        [173, 172, 176],
        [187, 186, 190],
        ...,
        [102,  92,  98],
        [101,  91,  97],
        [103,  93,  99]],

       [[123, 122, 126],
        [145, 144, 148],
        [176, 175, 179],
        ...,
        [ 95,  85,  91],
        [ 96,  86,  92],
        [ 98,  88,  94]]], dtype=uint8)
orig_shape: (1080, 810)
path: 'image0.jpg'
probs: None
save_dir: 'runs\\detect\\predict'
speed: {'preprocess': 2.9282569885253906, 'inference': 16.591787338256836, 'postprocess': 4.879474639892578}]  "

```
from ultralytics import YOLO
import cv2

# Load the image
img = cv2.imread('bus.jpg')

# Load YOLOv10 model
model_v10 = YOLO('yolov10s.pt')
results_v10 = model_v10.predict(img, conf=0.01, half=True, classes=[0], imgsz=640)
print("YOLOv10 Results:", results_v10)

# Load YOLOv8 model
model_v8 = YOLO('yolov8s.pt')
results_v8 = model_v8.predict(img, conf=0.01, half=True, classes=[0], imgsz=640)
print("YOLOv8 Results:", results_v8)
```

And I ran the second code, I got this error
"Traceback (most recent call last):
  File "c:\Users\User\Blockade3d_yolo\測試模型預測結果.py", line 45, in <module>
    filtered_results_v10 = [res for res in results_v10 if res['class'] == 0]
  File "c:\Users\User\Blockade3d_yolo\測試模型預測結果.py", line 45, in <listcomp>
    filtered_results_v10 = [res for res in results_v10 if res['class'] == 0]
  File "C:\Users\User\.conda\envs\blockade\lib\site-packages\ultralytics\engine\results.py", line 128, in __getitem__
    return self._apply("__getitem__", idx)
  File "C:\Users\User\.conda\envs\blockade\lib\site-packages\ultralytics\engine\results.py", line 165, in _apply    
    setattr(r, k, getattr(v, fn)(*args, **kwargs))
  File "C:\Users\User\.conda\envs\blockade\lib\site-packages\ultralytics\engine\results.py", line 63, in __getitem__    return self.__class__(self.data[idx], self.orig_shape)
IndexError: too many indices for tensor of dimension 2"

**Comment by glenn-jocher** [comment]
Hello @Andy718811,

Thank you for providing the detailed information and the reproducible code example. This is very helpful! 😊

It appears that the `classes` parameter is not being respected when using the YOLOv10 model. Let's delve into this further.

First, let's ensure that the `classes` parameter is correctly applied by adding a print statement to check the filtered classes:

```python
from ultralytics import YOLO
import cv2

# Load the image
img = cv2.imread('bus.jpg')

# Load YOLOv10 model
model_v10 = YOLO('yolov10s.pt')
results_v10 = model_v10.predict(img, conf=0.01, half=True, classes=[0], imgsz=640)
print("YOLOv10 Results:", results_v10)

# Load YOLOv8 model
model_v8 = YOLO('yolov8s.pt')
results_v8 = model_v8.predict(img, conf=0.01, half=True, classes=[0], imgsz=640)
print("YOLOv8 Results:", results_v8)
```

If the issue persists, it might be a bug specific to the YOLOv10 implementation. In that case, we will need to investigate further. 

Meanwhile, as a workaround, you can manually filter the results to include only the desired classes:

```python
# Filter results manually for YOLOv10
filtered_results_v10 = [res for res in results_v10 if res['class'] == 0]
print("Filtered YOLOv10 Results:", filtered_results_v10)

# Filter results manually for YOLOv8
filtered_results_v8 = [res for res in results_v8 if res['class'] == 0]
print("Filtered YOLOv8 Results:", filtered_results_v8)
```

We appreciate your patience and understanding as we work to resolve this issue. If you have any further questions or need additional assistance, please feel free to ask!

**Comment by glenn-jocher** [comment]
@Andy718811 fixed now in https://github.com/ultralytics/ultralytics/pull/13971

**Comment by Andy718811** [comment]
Thank you, this helps alot!

**Comment by glenn-jocher** [comment]
Hello @Andy718811,

Thank you for providing the detailed information and the reproducible code example. This is very helpful! 😊

It appears that the `classes` parameter is not being respected when using the YOLOv10 model. This might be a bug specific to the YOLOv10 implementation. We appreciate your patience as we investigate this further.

In the meantime, you can manually filter the results to include only the desired classes. Here's an example of how you can do this:

```python
from ultralytics import YOLO
import cv2

# Load the image
img = cv2.imread('bus.jpg')

# Load YOLOv10 model
model_v10 = YOLO('yolov10s.pt')
results_v10 = model_v10.predict(img, conf=0.01, half=True, imgsz=640)

# Manually filter results for class 0
filtered_boxes_v10 = [box for box in results_v10[0].boxes if box.cls == 0]
print("Filtered YOLOv10 Results:", filtered_boxes_v10)

# Load YOLOv8 model
model_v8 = YOLO('yolov8s.pt')
results_v8 = model_v8.predict(img, conf=0.01, half=True, imgsz=640)

# Manually filter results for class 0
filtered_boxes_v8 = [box for box in results_v8[0].boxes if box.cls == 0]
print("Filtered YOLOv8 Results:", filtered_boxes_v8)
```

Please let us know if this workaround helps, and we'll keep you updated on the progress of the investigation. If you have any further questions or need additional assistance, feel free to ask!

**Comment by SoumyaratnaDebnath** [comment]
Hi @glenn-jocher, 
I was facing a similar problem with yolov10. I upgraded my ultralytics installation using `pip install ultralytics --upgrade`, and it seems to work fine now!

**Comment by glenn-jocher** [comment]
Hi @SoumyaratnaDebnath,

Thank you for the update. I'm glad to hear that upgrading your Ultralytics installation resolved the issue with YOLOv10. If you encounter any further problems or have additional questions, feel free to reach out.
