### ISSUE TITLE
Ignoring Corrupt Image/Label Error: Non-Normalized or Out of Bounds Coordinates in DOTA Dataset

### ISSUE THREAD

**Issue by xiawuhen** [ultralytics/ultralytics#13924]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am encountering an issue while training the YOLOv8 model using the DOTA dataset. The training process throws an error saying, "ignoring corrupt image/label: non-normalized or out of bounds coordinates [1.0371]". This seems to indicate that some coordinates in my label files are not normalized or are out of the expected [0, 1] range.
Could you please provide guidance on how to resolve this issue? Any suggestions or examples of pre-processing steps would be greatly appreciated.
![屏幕截图 2024-06-24 170412](https://github.com/ultralytics/ultralytics/assets/94815747/66204d3a-da97-4968-a2bc-85814c076622)

**Comment by glenn-jocher** [comment]
Hello @xiawuhen,

Thank you for reaching out and providing details about the issue you're encountering with the DOTA dataset. The error message you're seeing, "ignoring corrupt image/label: non-normalized or out of bounds coordinates [1.0371]", indicates that some of your label coordinates are not within the expected range of [0, 1]. This is a common issue when working with custom datasets.

Here are some steps to help you resolve this:

1. **Verify Data Normalization**: Ensure that all your label coordinates are normalized to the range [0, 1]. This means that the coordinates should be relative to the image dimensions. For example, if your image width is 1024 pixels and a bounding box's x-coordinate is 512, the normalized x-coordinate should be 512/1024 = 0.5.

2. **Pre-processing Script**: You can use a pre-processing script to normalize your coordinates. Here is a simple example in Python:

    ```python
    import os
    import glob

    def normalize_labels(label_path, image_width, image_height):
        with open(label_path, 'r') as file:
            lines = file.readlines()
        
        normalized_lines = []
        for line in lines:
            parts = line.strip().split()
            class_id = parts[0]
            x_center = float(parts[1]) / image_width
            y_center = float(parts[2]) / image_height
            width = float(parts[3]) / image_width
            height = float(parts[4]) / image_height
            
            if 0 <= x_center <= 1 and 0 <= y_center <= 1 and 0 <= width <= 1 and 0 <= height <= 1:
                normalized_lines.append(f"{class_id} {x_center} {y_center} {width} {height}\n")
        
        with open(label_path, 'w') as file:
            file.writelines(normalized_lines)

    # Example usage
    label_files = glob.glob('path/to/labels/*.txt')
    image_width = 1024  # Replace with your image width
    image_height = 1024  # Replace with your image height

    for label_file in label_files:
        normalize_labels(label_file, image_width, image_height)
    ```

3. **Check for Outliers**: Sometimes, there might be outliers or incorrect annotations in your dataset. Ensure that all annotations are correct and within the image boundaries.

4. **Update Packages**: Ensure that you are using the latest version of the Ultralytics YOLO package. Sometimes, updates include fixes for issues that might be causing your problem. You can update the package using:
    ```bash
    pip install --upgrade ultralytics
    ```

5. **Minimum Reproducible Example**: If the issue persists, it would be helpful to provide a minimum reproducible example. This will allow us to better understand the problem and provide more specific guidance. You can refer to our guide on creating a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

By following these steps, you should be able to resolve the issue with non-normalized or out-of-bounds coordinates in your DOTA dataset. If you have any further questions or need additional assistance, feel free to ask!

**Comment by trung-kien-pham** [comment]
Hi @glenn-jocher,
I got this problem when I trained the model on the OBB task.
/our-data-obb/our_data_obb/train/images/image_96_ML_10.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [ 1.0402]
As I understand the YOLO-OBB process, it uses xywhr internally, so could you help clarify why this problem is occurring?

**Comment by glenn-jocher** [comment]
For OBB, the loader still validates the on-disk labels before any internal `xywhr` conversion, so a value like `1.0402` means at least one polygon corner in `cls x1 y1 x2 y2 x3 y3 x4 y4` is outside the normalized `[0,1]` range; please verify your conversion against the [`convert_dota_to_yolo_obb()` reference](https://docs.ultralytics.com/reference/data/converter/) or the split/save logic in [`crop_and_save()`](https://docs.ultralytics.com/reference/data/split_dota/), then delete any `labels/*.cache` files and retry, and since this is a closed stale issue please open a new issue with the full traceback and `yolo checks` output if it still reproduces.
