### ISSUE TITLE
parse prediction from yolo8.onnx in opencv

### ISSUE THREAD

**Issue by Etty-Cohen** [ultralytics/ultralytics#13923]
### Question

I saw that guide [https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-ONNXRuntime](url)
 Do you have it in C++?

**Comment by glenn-jocher** [comment]
@Etty-Cohen no problem at all! I'm glad you found the solution you were looking for. If you have any other questions or need further assistance, feel free to ask. The YOLO community and the Ultralytics team are always here to help! 😊

For future reference, if you need to parse predictions from a YOLOv8 ONNX model using OpenCV in C++, you can refer to the [Ultralytics documentation](https://docs.ultralytics.com/tasks/obb/) for additional resources and examples.

Happy coding! 🚀

**Comment by Etty-Cohen** [comment]
@glenn-jocher Why in c++ size is cv::Size(640, 480) nor (640,640)?
In model converting you used only 640 for size

**Comment by glenn-jocher** [comment]
Hi @Etty-Cohen,

Great question! The discrepancy arises from the way image dimensions are handled in different contexts. When converting the model, the size `640` typically refers to a square input dimension (640x640), which is common for YOLO models. This ensures that the model receives a consistent input size, which is crucial for maintaining performance and accuracy.

In OpenCV, `cv::Size(640, 480)` specifies a rectangular dimension (width x height). If you want to match the model's expected input size, you should use `cv::Size(640, 640)` in your C++ code. Here's a quick example:

```cpp
cv::Mat img = cv::imread("image.jpg");
cv::resize(img, img, cv::Size(640, 640));  // Resize to 640x640
```

This ensures that the input image matches the dimensions used during model conversion.

If you continue to experience issues, please provide a minimum reproducible example so we can assist you better. You can find more details on creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Also, ensure you are using the latest versions of the packages to avoid any compatibility issues.

Feel free to reach out if you have any more questions!

**Comment by Etty-Cohen** [comment]
@glenn-jocher Thank you very much!!

**Comment by glenn-jocher** [comment]
Hi @Etty-Cohen,

You're very welcome! 😊 If you have any more questions or run into any other issues, feel free to ask. We're here to help!

If you encounter any bugs or need further assistance, providing a minimum reproducible example can greatly help us diagnose and resolve the issue more efficiently. You can find guidelines on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Also, please ensure you're using the latest versions of all relevant packages to avoid any compatibility issues.

Happy coding, and thanks for being a part of the YOLO community! 🚀

**Comment by Etty-Cohen** [comment]
@glenn-jocher 
Hello,

I ran the code shown here: [<>](https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-CPP-Inference) with slight structural changes to adapt it to an existing project of mine. 
I will adjust the header files later as needed, so the current order in the code does not matter—only its correctness does. 
I took an image, ran it with the Python code, and got excellent results as expected. However, with the C++ code, no objects are found. 
I emphasize that the model used in both Python and C++ is the same. 
I also executed your code without my structural changes, and it also did not detect anything.

What could be the problem?

Here is also a link to my C++ code [(I](https://colab.research.google.com/drive/1mOG3KF3m25O8FQYbsDpCuGP3Do3mi8l2#scrollTo=cIcVzWFzHHqZ) used a notebook just for the text file, not for execution).

Additionally, the results returned from the model after applying transpose and reshape are as follows:
.....
.....
271.93393, 219.59474, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
 326.56842, 219.69348, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
 ....

Thank you very much.

**Comment by glenn-jocher** [comment]
Hi @Etty-Cohen,

Thank you for reaching out and providing detailed information about your issue. It's great to hear that the Python code is working well for you. Let's try to resolve the discrepancy with the C++ implementation.

### Steps to Troubleshoot:

1. **Ensure Consistent Preprocessing**:
   - Verify that the image preprocessing steps (resizing, normalization, etc.) are identical in both Python and C++ implementations. Differences here can lead to varying results.

2. **Model Input Size**:
   - Confirm that the input size for the model in C++ matches the size used in Python. For YOLOv8, this is typically 640x640.

3. **Check Model Output**:
   - The output you shared seems to have many zeros, which might indicate an issue with the model inference or post-processing steps. Ensure that the model's output is being correctly interpreted and processed.

4. **Debugging Output**:
   - Print intermediate results at various stages (e.g., after preprocessing, after model inference) to ensure each step is producing the expected output.

5. **Library Versions**:
   - Ensure that the versions of the libraries used in C++ (e.g., OpenCV, ONNX runtime) are compatible with the model. Sometimes, version mismatches can cause issues.

### Example Code for Consistent Preprocessing in C++:

Here’s a snippet to ensure consistent preprocessing in C++:

```cpp
cv::Mat img = cv::imread("image.jpg");
cv::resize(img, img, cv::Size(640, 640));  // Resize to 640x640
img.convertTo(img, CV_32F, 1.0 / 255);  // Normalize to [0, 1]
cv::Mat blob = cv::dnn::blobFromImage(img);
```

### Minimum Reproducible Example:
If the issue persists, it would be very helpful if you could provide a minimal reproducible example. This will allow us to better understand the problem and provide a more accurate solution. You can find guidelines on creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

### Verify Latest Versions:
Please ensure that you are using the latest versions of all relevant packages to avoid any compatibility issues.

Feel free to share any additional details or code snippets if you need further assistance. We're here to help!

**Comment by Etty-Cohen** [comment]
@glenn-jocher I think it is bug.
because in your cpp code without changes it is not working. 
I checked all of your 5 tips - but they didn't help
I think the model is good cause in python it works amazing.
In the link to code I put in my previous  appeal to you, you can see all the code.

Minimum Reproducible Example:
```

cv::Mat classify(cv::Mat org_img) {

  cv::dnn::Net *net;
  Mat blob, prob;

  net = new Net();
  std::cout<<"classify start loading yolo\n";
  *net = readNet("640_yolo_collage_nchw.onnx");

  net->setPreferableBackend(DNN_BACKEND_CUDA);
  net->setPreferableTarget(DNN_TARGET_CUDA);

  Scalar meanValues = Scalar(0, 0, 0);
  blob = blobFromImage(org_img, 1.0/255.0, Size(640, 640), meanValues , true);
  net->setInput(blob);
  prob = net->forward();

  int rows = prob.size[2];
  int dimensions = prob.size[1];
  std::cout<<"rows="<<rows<<" . dimensions="<<dimensions<<'\n';
  prob = prob.reshape(1, dimensions);
  std::cout << "After reshape: rows = " << prob.rows << " columns = " << prob.cols << '\n';
  cv::Mat transposeResult;
  cv::transpose(prob, transposeResult);
  std::cout << "After transpose: rows = " <<transposeResult.rows<<" columns = "<<transposeResult.cols <<'\n';
  std::cout<<"transposeResult= "<<transposeResult<<'\n';

  return transposeResult;
}
```

it printing:
```
rows= 8400 dimension=84
After reshape: rows = 84 columns = 8400
After transpose: rows = 8400 columns = 84
transposeResult= [5.1562109, 10.473678, -3405.3015, -2.137685e-33, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
 18.60218, 8.2517223, -2.0848554e+08, -2.5749221e-32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
 24.777039, 14.146791, -1.3540737e+10, -1.5222464e-36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
 31.836327, 9.3321877, -13880264, inf, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
 34.241776, 8.5658598, -8.4654157e+08, -1.5019122e-36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
 40.156559, 8.5461836, -5.6291804e+13, -3.9901102e-31,......
```

You can see that most of the output is zeros, so the rest of the postprocess code is irrelevant, because of course no objects were found in it.
Do you have an explanation for that? It looks like a bug in the processing of the results in C++

**Comment by glenn-jocher** [comment]
Hi @Etty-Cohen,

Thank you for providing the detailed information and the reproducible example. I understand the frustration when the same model works perfectly in Python but not in C++. Let's try to troubleshoot this issue together.

### Potential Issues and Solutions:

1. **Model Input Preprocessing**:
   Ensure that the preprocessing steps in C++ match exactly with those in Python. This includes resizing, normalization, and blob creation.

   ```cpp
   cv::Mat img = cv::imread("image.jpg");
   cv::resize(img, img, cv::Size(640, 640));  // Resize to 640x640
   img.convertTo(img, CV_32F, 1.0 / 255);  // Normalize to [0, 1]
   cv::Mat blob = cv::dnn::blobFromImage(img);
   ```

2. **Model Output Interpretation**:
   The output you shared indicates many zeros, which might suggest an issue with the model inference or post-processing steps. Ensure that the output tensor is being correctly interpreted.

   ```cpp
   cv::Mat prob = net->forward();
   int rows = prob.size[2];
   int dimensions = prob.size[1];
   prob = prob.reshape(1, dimensions);
   cv::Mat transposeResult;
   cv::transpose(prob, transposeResult);
   ```

3. **Check for NaNs and Infs**:
   The presence of `inf` and extremely large negative values suggests numerical instability. Ensure that the input data is correctly normalized and that the model is not encountering any unexpected values.

4. **Library Versions**:
   Ensure that the versions of OpenCV and ONNX runtime used in C++ are compatible with the model. Sometimes, version mismatches can cause issues.

5. **Debugging Intermediate Steps**:
   Print intermediate results at various stages (e.g., after preprocessing, after model inference) to ensure each step is producing the expected output.

### Example Code for Consistent Preprocessing in C++:

Here’s a snippet to ensure consistent preprocessing in C++:

```cpp
cv::Mat img = cv::imread("image.jpg");
cv::resize(img, img, cv::Size(640, 640));  // Resize to 640x640
img.convertTo(img, CV_32F, 1.0 / 255);  // Normalize to [0, 1]
cv::Mat blob = cv::dnn::blobFromImage(img);
```

### Verify Latest Versions:
Please ensure that you are using the latest versions of all relevant packages to avoid any compatibility issues.

If the issue persists, please provide any additional details or code snippets. We're here to help! 😊
