### ISSUE TITLE
cv::OutOfMemoryError

### ISSUE THREAD

**Issue by JavieYuan** [ultralytics/ultralytics#1392]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

![v8-1](https://user-images.githubusercontent.com/84179587/224631017-7d4fe4e2-835f-4562-a2f2-8e733f145e88.png)
I run the program in the Windows environment      python test.py     How can I solute it?

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by JavieYuan** [comment]
> 👋 Hello @JavieYuan, thank you for your interest in YOLOv8 🚀! We recommend a visit to the [YOLOv8 Docs](https://docs.ultralytics.com) for new users where you can find many [Python](https://docs.ultralytics.com/python/) and [CLI](https://docs.ultralytics.com/cli/) usage examples and where many of the most common questions may already be answered.
> 
> If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us debug it.
> 
> If this is a custom training ❓ Question, please provide as much information as possible, including dataset image examples and training logs, and verify you are following our [Tips for Best Training Results](https://github.com/ultralytics/yolov5/wiki/Tips-for-Best-Training-Results).
> 
> ## Install
> Pip install the `ultralytics` package including all [requirements.txt](https://github.com/ultralytics/ultralytics/blob/main/requirements.txt) in a [**Python>=3.7**](https://www.python.org/) environment with [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/).
> 
> ```shell
> pip install ultralytics
> ```
> 
> ## Environments
> YOLOv8 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):
> 
> * **Notebooks** with free GPU: [![Run on Gradient](https://camo.githubusercontent.com/c9931a1689c37ab786edd3e1e5f59b9a6f7d097628c4689ce2432563ef884524/68747470733a2f2f6173736574732e706170657273706163652e696f2f696d672f6772616469656e742d62616467652e737667)](https://console.paperspace.com/github/ultralytics/ultralytics) [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/ultralytics/yolov8)
> * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/GCP-Quickstart)
> * **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/AWS-Quickstart)
> * **Docker Image**. See [Docker Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart) [![Docker Pulls](https://camo.githubusercontent.com/7401823bed1473d6db1ff60b933d51cd1534c448488f06c446c322227d31d966/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f756c7472616c79746963733f6c6f676f3d646f636b6572)](https://hub.docker.com/r/ultralytics/ultralytics)
> 
> ## Status
> [![Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg)](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule)
> 
> If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing. CI tests verify correct operation of all YOLOv8 modes and tasks on macOS, Windows, and Ubuntu every 24 hours and on every commit.

I have no way to solute this question，I hope someone can help me.

**Comment by JavieYuan** [comment]
> Try passing `stream=True` in your predict call. It might solve the issue of you're running out of system memory.

The program can not run after I add this parameter.
![v8-2](https://user-images.githubusercontent.com/84179587/224874501-9173ad83-5270-49a1-83ec-f956ea8277ff.png)

**Comment by Laughing-q** [comment]
@JavieYuan With `stream=True` it returns a generator of `Results` objects which is memory efficient, for a generator you might need a for loop to launch it.
```python
for result in model.track(..., stream=True):
    pass
```
please refer to our docs [https://docs.ultralytics.com/modes/predict/](https://docs.ultralytics.com/modes/predict/) for more info.

**Comment by JavieYuan** [comment]
> @JavieYuan With `stream=True` it returns a generator of `Results` objects which is memory efficient, for a generator you might need a for loop to launch it.
> 
> ```python
> for result in model.track(..., stream=True):
>     pass
> ```
> 
> please refer to our docs https://docs.ultralytics.com/modes/predict/ for more info.

Thank you!  A new issue，How should I cut and save the tracked and detected persons in the video according to the time sequence? The same person is saved into a folder by the id of bbox.
![v8-3](https://user-images.githubusercontent.com/84179587/224929282-bf58a5cb-8001-44f2-8390-57815cfc3d23.png)

**Comment by Laughing-q** [comment]
@JavieYuan well `save_txt` might help you, it'll save object's id and bbox.
```python
for result in model.track(..., stream=True, save_txt=True):
    pass
```
I suppose the folder won't be separated by id like you expected, the folder will be like:
```
└── save-dir/labels
    ├── video_1.txt
    ├── video_2.txt
    ├── video_3.txt
    ├── ...
```
The number represents the frame, and each line in each txt file is:
```
x y w h id
```
But as you've already got the all the information i.e track_id, frame_id, then you're able to write a script to read each txt file and move all the person with the same id into one folder.

**Comment by JavieYuan** [comment]
> @JavieYuan well `save_txt` might help you, it'll save object's id and bbox.
> 
> ```python
> for result in model.track(..., stream=True, save_txt=True):
>     pass
> ```
> 
> I suppose the folder won't be separated by id like you expected, the folder will be like:
> 
> ```
> └── save-dir/labels
>     ├── video_1.txt
>     ├── video_2.txt
>     ├── video_3.txt
>     ├── ...
> ```
> 
> The number represents the frame, and each line in each txt file is:
> 
> ```
> x y w h id
> ```
> 
> But as you've already got the all the information i.e track_id, frame_id, then you're able to write a script to read each txt file and move all the person with the same id into one folder.

What I want is to save the detected person as a picture（.jpg） instead of text. How to write the script? Where should I write the script?

**Comment by a5336033** [comment]
解决了吗？ 我也遇到了同样的问题

**Comment by glenn-jocher** [comment]
@a5336033 hello! Yes, if you're aiming to save detected persons from a video as individual images, you can leverage the `results.save_crop()` function within your tracking loop. Here's a simple example to guide you:

```python
# Assuming you're inside the loop where 'result' is each frame's tracking output
for frame_idx, result in enumerate(model.track(source='path/to/video.mp4', stream=True)):
    # Save cropped detections
    result.save_crop(save_dir=f'person_crops/frame_{frame_idx}')
```

This script will store cropped images of detected persons in folder `person_crops` under respective `frame_{frame_idx}` directories. Be sure to adjust `frame_idx` as per your requirements for organizing the images.

By adjusting this script, you can tailor the saving mechanism as needed. Hope this helps with your issue! 😊
