### ISSUE TITLE
Detect specific object and show XY prediction of that object 

### ISSUE THREAD

**Issue by KennethEladistu** [ultralytics/ultralytics#13921]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello currently I trained 1k data sets on parcels, and the detection is great. Currently I have 2 classes one for "parcel" and the other one for "other-object". This is the sample output on my inference using OAK-D-PRO camera

![Screenshot 2024-06-24 164401](https://github.com/ultralytics/ultralytics/assets/168053014/5621e05d-b9f5-420b-8221-877eadfdf4a8)

I want it so that it will only detect "parcel" and filter our the "other-object" and filter out confidence scores below 0.90

This is the output on my terminal:

It says 

boxes: None
keypoints: None
masks: None
names: {0: 'other-objects', 1: 'parcel'}
obb: ultralytics.engine.results.OBB object
orig_img: array([[[4, 1, 0],
        [3, 0, 0],
        [1, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[4, 1, 0],
        [3, 0, 0],
        [1, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[3, 0, 0],
        [3, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)
orig_shape: (400, 640)
path: 'image0.jpg'
probs: None
save_dir: 'C:\\Users\\KennethAaronEladistu\\ultralytics\\runs\\obb\\predict8'
speed: {'preprocess': 0.9939670562744141, 'inference': 21.998882293701172, 'postprocess': 1.0008811950683594}]
no detection

It says that boxes are :none, keypoints:none and no xy data. Can you help me on how to detect the xy data of the parcels

This is my current code that I am using:

`from ultralytics import YOLO
import cv2
import depthai as dai

# Load a pretrained YOLOv8n model
model = YOLO("C:/Users/KennethAaronEladistu/oak_d/oak_d/best(3).pt")

# Create pipeline
pipeline = dai.Pipeline()

# Define sources and outputs
camRgb = pipeline.create(dai.node.ColorCamera)
xoutRgb = pipeline.create(dai.node.XLinkOut)
xoutRgb.setStreamName("rgb")
camRgb.setPreviewSize(640, 400)
camRgb.setResolution(dai.ColorCameraProperties.SensorResolution.THE_1080_P)
camRgb.setInterleaved(False)
camRgb.setColorOrder(dai.ColorCameraProperties.ColorOrder.RGB)
camRgb.preview.link(xoutRgb.input)

# Connect to device and start pipeline
with dai.Device(pipeline) as device:
    qRgb = device.getOutputQueue(name="rgb", maxSize=4, blocking=False)
    
    while True:
        inRgb = qRgb.get()  # blocking call, will wait until a new data has arrived
        frame = inRgb.getCvFrame()
        results = model(frame)
        img = results[0].plot()
        cv2.imshow('YOLOv8 Box Detection' ,img)
        print(results)  # Debug: Print results to inspect

            # Check if there are any detections
        if results[0].boxes is not None:
            # Extract the detections
            detections = results[0].boxes.xyxy.cpu().numpy()  # xyxy format (xmin, ymin, xmax, ymax, confidence, class)
        try:
            for result in results:
                if hasattr(result, 'obb'):
                    x= result.obb.xywhr[0][0] 
                    y= result.obb.xywhr[0][1]
                    w= result.obb.xywhr[0][2]
                    h= result.obb.xywhr[0][3]
                    angle= result.obb.xywhr[0][4]
                    print(f"OBB coordinates: {x}, {y}, {w}, {h} with angle {angle}")
        except:
            print ("no detection")
        # Break the loop on 'q' key press
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cv2.destroyAllWindows()`

**Comment by glenn-jocher** [comment]
@KennethEladistu hello,

Thank you for reaching out and providing detailed information about your setup and the issue you're encountering. It's great to hear that your model is performing well on your custom dataset! Let's address your requirements and the issue with detecting and filtering specific objects.

### Filtering Detections by Class and Confidence

To filter out detections based on class and confidence score, you can modify your inference loop to include these conditions. Here's an updated version of your code that filters detections to only include "parcel" objects with a confidence score above 0.90:

```python
from ultralytics import YOLO
import cv2
import depthai as dai

# Load a pretrained YOLOv8n model
model = YOLO("C:/Users/KennethAaronEladistu/oak_d/oak_d/best(3).pt")

# Create pipeline
pipeline = dai.Pipeline()

# Define sources and outputs
camRgb = pipeline.create(dai.node.ColorCamera)
xoutRgb = pipeline.create(dai.node.XLinkOut)
xoutRgb.setStreamName("rgb")
camRgb.setPreviewSize(640, 400)
camRgb.setResolution(dai.ColorCameraProperties.SensorResolution.THE_1080_P)
camRgb.setInterleaved(False)
camRgb.setColorOrder(dai.ColorCameraProperties.ColorOrder.RGB)
camRgb.preview.link(xoutRgb.input)

# Connect to device and start pipeline
with dai.Device(pipeline) as device:
    qRgb = device.getOutputQueue(name="rgb", maxSize=4, blocking=False)
    
    while True:
        inRgb = qRgb.get()  # blocking call, will wait until a new data has arrived
        frame = inRgb.getCvFrame()
        results = model(frame)
        img = results[0].plot()
        cv2.imshow('YOLOv8 Box Detection', img)
        print(results)  # Debug: Print results to inspect

        # Check if there are any detections
        if results[0].boxes is not None:
            # Extract the detections
            detections = results[0].boxes.xyxy.cpu().numpy()  # xyxy format (xmin, ymin, xmax, ymax, confidence, class)
            for detection in detections:
                xmin, ymin, xmax, ymax, confidence, cls = detection
                if cls == 1 and confidence > 0.90:  # Class 1 is "parcel"
                    print(f"Parcel detected at ({xmin}, {ymin}, {xmax}, {ymax}) with confidence {confidence}")

        # Extract OBB coordinates if available
        try:
            for result in results:
                if hasattr(result, 'obb'):
                    x = result.obb.xywhr[0][0]
                    y = result.obb.xywhr[0][1]
                    w = result.obb.xywhr[0][2]
                    h = result.obb.xywhr[0][3]
                    angle = result.obb.xywhr[0][4]
                    print(f"OBB coordinates: {x}, {y}, {w}, {h} with angle {angle}")
        except:
            print("No detection")

        # Break the loop on 'q' key press
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cv2.destroyAllWindows()
```

### Key Points:
1. **Filtering by Class and Confidence**: The code now includes a condition to filter detections by class (`cls == 1` for "parcel") and confidence (`confidence > 0.90`).
2. **Printing Coordinates**: The coordinates of the detected parcels are printed if they meet the filtering criteria.

### Additional Resources:
- Ensure you are using the latest version of the Ultralytics YOLO package to benefit from the latest features and bug fixes.
- For more detailed information on working with detection results, you can refer to the [Ultralytics YOLO documentation](https://docs.ultralytics.com/modes/predict/).

If you continue to experience issues or have further questions, please provide additional details or a reproducible example as outlined in our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us assist you more effectively.

**Comment by KennethEladistu** [comment]
> @KennethEladistu hello,
> 
> Thank you for reaching out and providing detailed information about your setup and the issue you're encountering. It's great to hear that your model is performing well on your custom dataset! Let's address your requirements and the issue with detecting and filtering specific objects.
> ### Filtering Detections by Class and Confidence
> 
> To filter out detections based on class and confidence score, you can modify your inference loop to include these conditions. Here's an updated version of your code that filters detections to only include "parcel" objects with a confidence score above 0.90:
> 
> ```python
> from ultralytics import YOLO
> import cv2
> import depthai as dai
> 
> # Load a pretrained YOLOv8n model
> model = YOLO("C:/Users/KennethAaronEladistu/oak_d/oak_d/best(3).pt")
> 
> # Create pipeline
> pipeline = dai.Pipeline()
> 
> # Define sources and outputs
> camRgb = pipeline.create(dai.node.ColorCamera)
> xoutRgb = pipeline.create(dai.node.XLinkOut)
> xoutRgb.setStreamName("rgb")
> camRgb.setPreviewSize(640, 400)
> camRgb.setResolution(dai.ColorCameraProperties.SensorResolution.THE_1080_P)
> camRgb.setInterleaved(False)
> camRgb.setColorOrder(dai.ColorCameraProperties.ColorOrder.RGB)
> camRgb.preview.link(xoutRgb.input)
> 
> # Connect to device and start pipeline
> with dai.Device(pipeline) as device:
>     qRgb = device.getOutputQueue(name="rgb", maxSize=4, blocking=False)
>     
>     while True:
>         inRgb = qRgb.get()  # blocking call, will wait until a new data has arrived
>         frame = inRgb.getCvFrame()
>         results = model(frame)
>         img = results[0].plot()
>         cv2.imshow('YOLOv8 Box Detection', img)
>         print(results)  # Debug: Print results to inspect
> 
>         # Check if there are any detections
>         if results[0].boxes is not None:
>             # Extract the detections
>             detections = results[0].boxes.xyxy.cpu().numpy()  # xyxy format (xmin, ymin, xmax, ymax, confidence, class)
>             for detection in detections:
>                 xmin, ymin, xmax, ymax, confidence, cls = detection
>                 if cls == 1 and confidence > 0.90:  # Class 1 is "parcel"
>                     print(f"Parcel detected at ({xmin}, {ymin}, {xmax}, {ymax}) with confidence {confidence}")
> 
>         # Extract OBB coordinates if available
>         try:
>             for result in results:
>                 if hasattr(result, 'obb'):
>                     x = result.obb.xywhr[0][0]
>                     y = result.obb.xywhr[0][1]
>                     w = result.obb.xywhr[0][2]
>                     h = result.obb.xywhr[0][3]
>                     angle = result.obb.xywhr[0][4]
>                     print(f"OBB coordinates: {x}, {y}, {w}, {h} with angle {angle}")
>         except:
>             print("No detection")
> 
>         # Break the loop on 'q' key press
>         if cv2.waitKey(1) & 0xFF == ord('q'):
>             break
> 
>     cv2.destroyAllWindows()
> ```
> 
> ### Key Points:
> 
>     1. **Filtering by Class and Confidence**: The code now includes a condition to filter detections by class (`cls == 1` for "parcel") and confidence (`confidence > 0.90`).
> 
>     2. **Printing Coordinates**: The coordinates of the detected parcels are printed if they meet the filtering criteria.
> 
> 
> ### Additional Resources:
> 
>     * Ensure you are using the latest version of the Ultralytics YOLO package to benefit from the latest features and bug fixes.
> 
>     * For more detailed information on working with detection results, you can refer to the [Ultralytics YOLO documentation](https://docs.ultralytics.com/modes/predict/).
> 
> 
> If you continue to experience issues or have further questions, please provide additional details or a reproducible example as outlined in our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us assist you more effectively.

Hello thanks for the help! currently my model is detecting 2 objects. "parcel" and "other-objects", since I labeled 2 objects in RoboFlow when annotating my objects, how can I filter our the"other-objects" and make it only draw bounding box and detect "parcel"

**Comment by KennethEladistu** [comment]
Also I have another question, when detecting the parcel my output everytime in the terminal is this one

Example:

boxes: None
keypoints: None
masks: None
names: {0: 'other-objects', 1: 'parcel'}
obb: ultralytics.engine.results.OBB object
orig_img: array([[[ 20,  23,  25],
        [ 22,  25,  27],
        [ 24,  30,  31],
        ...,
        [248, 251, 248],
        [248, 251, 248],
        [248, 251, 248]],

       [[ 21,  24,  26],
        [ 24,  27,  29],
        [ 26,  32,  33],
        ...,
        [249, 252, 249],
        [248, 251, 248],
        [248, 251, 248]],

       [[ 22,  25,  27],
        [ 26,  29,  31],
        [ 26,  31,  34],
        ...,
        [249, 252, 249],
        [248, 251, 248],
        [248, 251, 248]],

       ...,

       [[ 98, 117, 144],
        [103, 122, 149],
        [109, 127, 152],
        ...,
        [ 84,  98, 116],
        [ 82,  95, 115],
        [ 82,  95, 115]],

       [[ 98, 115, 143],
        [103, 120, 148],
        [105, 123, 148],
        ...,
        [ 83,  96, 116],
        [ 81,  94, 114],
        [ 81,  94, 114]],

       [[ 97, 114, 142],
        [ 99, 116, 144],
        [104, 122, 147],
        ...,
        [ 82,  95, 115],
        [ 83,  96, 116],
        [ 84,  97, 117]]], dtype=uint8)
orig_shape: (400, 640)
path: 'image0.jpg'
probs: None
save_dir: 'C:\\Users\\KennethAaronEladistu\\ultralytics\\runs\\obb\\predict8'
speed: {'preprocess': 0.9889602661132812, 'inference': 10.061502456665039, 'postprocess': 0.9989738464355469}]
prediction ultralytics.engine.results.OBB object with attributes:

cls: tensor([], device='cuda:0')
conf: tensor([], device='cuda:0')
data: tensor([], device='cuda:0', size=(0, 7))
id: None
is_track: False
orig_shape: (400, 640)
shape: torch.Size([0, 7])
xywhr: tensor([], device='cuda:0', size=(0, 5))
xyxy: tensor([], device='cuda:0', size=(0, 4))
xyxyxyxy: tensor([], device='cuda:0', size=(0, 4, 2))
xyxyxyxyn: tensor([], device='cuda:0', size=(0, 4, 2))



why does it say that
 boxes: None
 keypoints: None 
and mask:None

this is my code for that 

`from ultralytics import YOLO
import cv2
import depthai as dai

# Load a pretrained YOLOv8n model
model = YOLO("C:/Users/KennethAaronEladistu/oak_d/oak_d/best(3).pt")

# Create pipeline
pipeline = dai.Pipeline()

# Define sources and outputs
camRgb = pipeline.create(dai.node.ColorCamera)
xoutRgb = pipeline.create(dai.node.XLinkOut)
xoutRgb.setStreamName("rgb")
camRgb.setPreviewSize(640, 400)
camRgb.setResolution(dai.ColorCameraProperties.SensorResolution.THE_1080_P)
camRgb.setInterleaved(False)
camRgb.setColorOrder(dai.ColorCameraProperties.ColorOrder.RGB)
camRgb.preview.link(xoutRgb.input)

# Connect to device and start pipeline
with dai.Device(pipeline) as device:
    qRgb = device.getOutputQueue(name="rgb", maxSize=4, blocking=False)
    
    while True:
        inRgb = qRgb.get()  # blocking call, will wait until a new data has arrived
        frame = inRgb.getCvFrame()
        results = model(frame)
        img = results[0].plot()
        cv2.imshow('YOLOv8 Box Detection', img)
        print(results)  # Debug: Print results to inspect

        # predict data of detection
        pred_boxes = results[0].obb
        print("prediction",pred_boxes)

        # Check if there are any detections
        if results[0].boxes is not None:
            # Extract the detections
            detections = results[0].boxes.xyxy.cpu().numpy()  # xyxy format (xmin, ymin, xmax, ymax, confidence, class)
            for detection in detections:
                xmin, ymin, xmax, ymax, confidence, cls = detection
                if cls == 1 and confidence > 0.90:  # Class 1 is "parcel"
                    print(f"Parcel detected at ({xmin}, {ymin}, {xmax}, {ymax}) with confidence {confidence}")
                    # Optionally, you can draw the bounding box on the image 'img' here if needed
                
                    # Extract OBB coordinates if available and get 'xywhangle' 
                    try:
                        for result in results:
                            if hasattr(result, 'obb'):
                                x = result.obb.xywhr[0][0]
                                y = result.obb.xywhr[0][1]
                                w = result.obb.xywhr[0][2]
                                h = result.obb.xywhr[0][3]
                                angle = result.obb.xywhr[0][4]
                                print(f"OBB coordinates: {x}, {y}, {w}, {h} with angle {angle}")
                    except:
                        print("No OBB detection")

        # Break the loop on 'q' key press
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

cv2.destroyAllWindows()
`

**Comment by glenn-jocher** [comment]
Hello @KennethEladistu,

Thank you for your detailed follow-up. It's great to see your progress and the detailed output you've provided. Let's address your questions and refine your code to ensure it meets your requirements.

### Filtering Out "Other-Objects" and Detecting Only "Parcel"

To filter out the "other-objects" and ensure that only "parcel" detections are processed, you can modify your code to include a condition that checks the class of each detection. Additionally, let's address the issue where `boxes`, `keypoints`, and `masks` are `None`.

### Updated Code Example

Here's an updated version of your code that filters out "other-objects" and processes only "parcel" detections with confidence scores above 0.90:

```python
from ultralytics import YOLO
import cv2
import depthai as dai

# Load a pretrained YOLOv8n model
model = YOLO("C:/Users/KennethAaronEladistu/oak_d/oak_d/best(3).pt")

# Create pipeline
pipeline = dai.Pipeline()

# Define sources and outputs
camRgb = pipeline.create(dai.node.ColorCamera)
xoutRgb = pipeline.create(dai.node.XLinkOut)
xoutRgb.setStreamName("rgb")
camRgb.setPreviewSize(640, 400)
camRgb.setResolution(dai.ColorCameraProperties.SensorResolution.THE_1080_P)
camRgb.setInterleaved(False)
camRgb.setColorOrder(dai.ColorCameraProperties.ColorOrder.RGB)
camRgb.preview.link(xoutRgb.input)

# Connect to device and start pipeline
with dai.Device(pipeline) as device:
    qRgb = device.getOutputQueue(name="rgb", maxSize=4, blocking=False)
    
    while True:
        inRgb = qRgb.get()  # blocking call, will wait until a new data has arrived
        frame = inRgb.getCvFrame()
        results = model(frame)
        img = results[0].plot()
        cv2.imshow('YOLOv8 Box Detection', img)
        print(results)  # Debug: Print results to inspect

        # Check if there are any detections
        if results[0].boxes is not None:
            # Extract the detections
            detections = results[0].boxes.xyxy.cpu().numpy()  # xyxy format (xmin, ymin, xmax, ymax, confidence, class)
            for detection in detections:
                xmin, ymin, xmax, ymax, confidence, cls = detection
                if cls == 1 and confidence > 0.90:  # Class 1 is "parcel"
                    print(f"Parcel detected at ({xmin}, {ymin}, {xmax}, {ymax}) with confidence {confidence}")
                    # Optionally, you can draw the bounding box on the image 'img' here if needed

        # Extract OBB coordinates if available and get 'xywhangle' 
        try:
            for result in results:
                if hasattr(result, 'obb') and result.obb.xywhr.numel() > 0:
                    x = result.obb.xywhr[0][0]
                    y = result.obb.xywhr[0][1]
                    w = result.obb.xywhr[0][2]
                    h = result.obb.xywhr[0][3]
                    angle = result.obb.xywhr[0][4]
                    print(f"OBB coordinates: {x}, {y}, {w}, {h} with angle {angle}")
        except Exception as e:
            print(f"No OBB detection: {e}")

        # Break the loop on 'q' key press
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cv2.destroyAllWindows()
```

### Key Points:
1. **Filtering by Class and Confidence**: The code now includes a condition to filter detections by class (`cls == 1` for "parcel") and confidence (`confidence > 0.90`).
2. **Handling Empty Detections**: Added a check to ensure that `result.obb.xywhr` is not empty before attempting to access its elements.
3. **Debugging Output**: The code prints detailed information about the detections and OBB coordinates.

### Addressing `boxes`, `keypoints`, and `masks` Being `None`:
- Ensure that your model is correctly trained and that the dataset annotations are accurate.
- Verify that the model is capable of detecting the objects and that the confidence threshold is not too high, which might filter out valid detections.

If the issue persists, please provide a minimum reproducible example as outlined in our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us assist you more effectively.

Feel free to reach out if you have any further questions or need additional assistance. Happy coding! 😊

**Comment by KennethEladistu** [comment]
Hello I am trying to test again, since I am using the yolov8 obb model and trained my data set  on parcel, how can I extract the XY values of bounding box when there is a parcel detected? currently I am gonna be using just my webcam.

**Comment by glenn-jocher** [comment]
Hello @KennethEladistu,

Thank you for your detailed question! To extract the XY values of the bounding box when a parcel is detected using your YOLOv8 OBB model, you can follow the steps below. This example assumes you are using a webcam for real-time detection.

Here's a concise code snippet to help you get started:

```python
from ultralytics import YOLO
import cv2

# Load your trained YOLOv8 OBB model
model = YOLO("path/to/your/best.pt")

# Initialize webcam
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Run inference
    results = model(frame)

    # Process results
    for result in results:
        if result.boxes is not None:
            detections = result.boxes.xyxy.cpu().numpy()  # xyxy format (xmin, ymin, xmax, ymax, confidence, class)
            for detection in detections:
                xmin, ymin, xmax, ymax, confidence, cls = detection
                if cls == 1 and confidence > 0.90:  # Class 1 is "parcel"
                    print(f"Parcel detected at ({xmin}, {ymin}, {xmax}, {ymax}) with confidence {confidence}")

    # Display the frame with detections
    img = results[0].plot()
    cv2.imshow('YOLOv8 OBB Detection', img)

    # Break the loop on 'q' key press
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
```

### Key Points:
- **Filtering by Class and Confidence**: The code filters detections to only include "parcel" objects with a confidence score above 0.90.
- **Real-time Detection**: The script captures frames from the webcam, runs inference, and displays the results in real-time.

If you encounter any issues, please ensure you are using the latest version of the Ultralytics YOLO package. If the problem persists, providing a minimum reproducible example will help us assist you more effectively. You can find guidance on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any further questions. Happy coding! 😊

**Comment by KennethEladistu** [comment]
> Hello @KennethEladistu,
> 
> Thank you for your detailed question! To extract the XY values of the bounding box when a parcel is detected using your YOLOv8 OBB model, you can follow the steps below. This example assumes you are using a webcam for real-time detection.
> 
> Here's a concise code snippet to help you get started:
> 
> ```python
> from ultralytics import YOLO
> import cv2
> 
> # Load your trained YOLOv8 OBB model
> model = YOLO("path/to/your/best.pt")
> 
> # Initialize webcam
> cap = cv2.VideoCapture(0)
> 
> while True:
>     ret, frame = cap.read()
>     if not ret:
>         break
> 
>     # Run inference
>     results = model(frame)
> 
>     # Process results
>     for result in results:
>         if result.boxes is not None:
>             detections = result.boxes.xyxy.cpu().numpy()  # xyxy format (xmin, ymin, xmax, ymax, confidence, class)
>             for detection in detections:
>                 xmin, ymin, xmax, ymax, confidence, cls = detection
>                 if cls == 1 and confidence > 0.90:  # Class 1 is "parcel"
>                     print(f"Parcel detected at ({xmin}, {ymin}, {xmax}, {ymax}) with confidence {confidence}")
> 
>     # Display the frame with detections
>     img = results[0].plot()
>     cv2.imshow('YOLOv8 OBB Detection', img)
> 
>     # Break the loop on 'q' key press
>     if cv2.waitKey(1) & 0xFF == ord('q'):
>         break
> 
> cap.release()
> cv2.destroyAllWindows()
> ```
> 
> ### Key Points:
> 
>     * **Filtering by Class and Confidence**: The code filters detections to only include "parcel" objects with a confidence score above 0.90.
> 
>     * **Real-time Detection**: The script captures frames from the webcam, runs inference, and displays the results in real-time.
> 
> 
> If you encounter any issues, please ensure you are using the latest version of the Ultralytics YOLO package. If the problem persists, providing a minimum reproducible example will help us assist you more effectively. You can find guidance on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> Feel free to reach out if you have any further questions. Happy coding! 😊

hello I tried your code but it still detects the "other-object" 

![Screenshot 2024-06-28 151325](https://github.com/ultralytics/ultralytics/assets/168053014/ccecf06d-fabe-4177-8c0f-3d1bda5f87ea)


When training  my data sets in roboflow, I put 2 classes which are "other-objects" and "parcels" my "other-objects" are class = 0 and my "parcels" are =1. I just want to filter out other detections especially "other-objects" and make it so that if the confidence level is 0.80 above it will only detect that for parcels, is this possible for YOLOV8 OBB? because from the documentation of yolo v8 they used supervision

**Comment by glenn-jocher** [comment]
Hello @KennethEladistu,

Thank you for your follow-up and for providing additional context. It's great to see your dedication to refining your model's performance! Let's address your requirement to filter out "other-objects" and ensure that only "parcels" with a confidence level above 0.80 are detected.

### Updated Code Example

Here's an updated version of your code that explicitly filters out "other-objects" and processes only "parcels" with a confidence score above 0.80:

```python
from ultralytics import YOLO
import cv2

# Load your trained YOLOv8 OBB model
model = YOLO("path/to/your/best.pt")

# Initialize webcam
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Run inference
    results = model(frame)

    # Process results
    for result in results:
        if result.boxes is not None:
            detections = result.boxes.xyxy.cpu().numpy()  # xyxy format (xmin, ymin, xmax, ymax, confidence, class)
            for detection in detections:
                xmin, ymin, xmax, ymax, confidence, cls = detection
                if cls == 1 and confidence > 0.80:  # Class 1 is "parcel"
                    print(f"Parcel detected at ({xmin}, {ymin}, {xmax}, {ymax}) with confidence {confidence}")
                    # Optionally, you can draw the bounding box on the image 'img' here if needed

    # Display the frame with detections
    img = results[0].plot()
    cv2.imshow('YOLOv8 OBB Detection', img)

    # Break the loop on 'q' key press
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
```

### Key Points:
1. **Filtering by Class and Confidence**: The code now includes a condition to filter detections by class (`cls == 1` for "parcel") and confidence (`confidence > 0.80`).
2. **Real-time Detection**: The script captures frames from the webcam, runs inference, and displays the results in real-time.

### Additional Considerations:
- **Ensure Latest Version**: Please verify that you are using the latest version of the Ultralytics YOLO package to benefit from the latest features and bug fixes.
- **Reproducible Example**: If the issue persists, providing a minimum reproducible example will help us assist you more effectively. You can find guidance on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

If you have any further questions or need additional assistance, feel free to reach out. We're here to help! 😊

Happy coding!
