### ISSUE TITLE
Yolo parameters

### ISSUE THREAD

**Issue by Joeyabuki99** [ultralytics/ultralytics#13932]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi!! I want to use YOLOv8 just as detector, ignoring the classification phase. At the end of the training on my dataset, which parameters should I care about through the ones that are in the result.csv file? Thanks

**Comment by glenn-jocher** [comment]
@Joeyabuki99 hello!

Thank you for reaching out with your question. If you want to use YOLOv8 solely as a detector and ignore the classification phase, you'll primarily be interested in metrics that evaluate the detection performance. Here are the key parameters from the `results.csv` file that you should focus on:

1. **mAP50 (mean Average Precision at IoU=0.50)**: This metric gives you an overall measure of the model's precision and recall at a specific Intersection over Union (IoU) threshold of 0.50. It's a good indicator of how well your model is detecting objects.

2. **mAP50-95 (mean Average Precision at IoU=0.50:0.95)**: This is a more stringent metric that averages the precision and recall over multiple IoU thresholds (from 0.50 to 0.95). It provides a more comprehensive evaluation of your model's detection capabilities.

3. **Precision**: This metric indicates the proportion of true positive detections among all detections made by the model. High precision means fewer false positives.

4. **Recall**: This metric measures the proportion of true positive detections among all actual objects in the dataset. High recall means fewer false negatives.

5. **F1 Score**: This is the harmonic mean of precision and recall, providing a single metric that balances both aspects.

These metrics will give you a good understanding of how well your YOLOv8 model is performing as a detector. If you have any further questions or need additional assistance, feel free to ask!

For more detailed information on these metrics and how to interpret them, you can refer to the [Ultralytics documentation](https://docs.ultralytics.com/).
