### ISSUE TITLE
Documenting the validation process in table

### ISSUE THREAD

**Issue by saroshpatel** [ultralytics/ultralytics#13947]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I have a custom trained model, for simplicity I am restricting it to a single class. When I do the validation using best.pt I get reasonable metrics and confusion matrix.

As I run the validation I would like to push the each of the inference results into csv file, such that each row is setup like this

Filename,  Right_Prediction, False_Positive, False_Negative 

Is there a straight forward way to implement this

Thank you

**Comment by glenn-jocher** [comment]
@saroshpatel hello,

Thank you for reaching out with your question! It's great to hear that you're getting reasonable metrics and a confusion matrix with your custom-trained model. To achieve your goal of exporting validation results into a CSV file, you can extend the validation process to include CSV logging.

Here's a concise way to implement this:

1. **Modify the `update_metrics` method**: You can extend this method to log the results into a CSV file.

2. **Use Python's `csv` module**: This will help you write the results in the desired format.

Below is an example of how you can modify the `update_metrics` method to include CSV logging:

```python
import csv
from pathlib import Path

class DetectionValidator(BaseValidator):
    # Existing methods...

    def update_metrics(self, preds, batch):
        """Metrics."""
        csv_file = Path(self.save_dir) / "validation_results.csv"
        with open(csv_file, mode='a', newline='') as file:
            writer = csv.writer(file)
            for si, pred in enumerate(preds):
                self.seen += 1
                npr = len(pred)
                stat = dict(
                    conf=torch.zeros(0, device=self.device),
                    pred_cls=torch.zeros(0, device=self.device),
                    tp=torch.zeros(npr, self.niou, dtype=torch.bool, device=self.device),
                )
                pbatch = self._prepare_batch(si, batch)
                cls, bbox = pbatch.pop("cls"), pbatch.pop("bbox")
                nl = len(cls)
                stat["target_cls"] = cls
                stat["target_img"] = cls.unique()
                if npr == 0:
                    if nl:
                        for k in self.stats.keys():
                            self.stats[k].append(stat[k])
                        if self.args.plots:
                            self.confusion_matrix.process_batch(detections=None, gt_bboxes=bbox, gt_cls=cls)
                    continue

                # Predictions
                if self.args.single_cls:
                    pred[:, 5] = 0
                predn = self._prepare_pred(pred, pbatch)
                stat["conf"] = predn[:, 4]
                stat["pred_cls"] = predn[:, 5]

                # Evaluate
                if nl:
                    stat["tp"] = self._process_batch(predn, bbox, cls)
                    if self.args.plots:
                        self.confusion_matrix.process_batch(predn, bbox, cls)
                for k in self.stats.keys():
                    self.stats[k].append(stat[k])

                # Save to CSV
                for i, p in enumerate(predn):
                    filename = batch["im_file"][si]
                    right_prediction = int(stat["tp"][i].any())
                    false_positive = int(not right_prediction and p[4] > self.args.conf)
                    false_negative = int(not right_prediction and p[4] <= self.args.conf)
                    writer.writerow([filename, right_prediction, false_positive, false_negative])

                # Save
                if self.args.save_json:
                    self.pred_to_json(predn, batch["im_file"][si])
                if self.args.save_txt:
                    file = self.save_dir / "labels" / f'{Path(batch["im_file"][si]).stem}.txt'
                    self.save_one_txt(predn, self.args.save_conf, pbatch["ori_shape"], file)
```

This code snippet will append each inference result to a CSV file named `validation_results.csv` in the specified `save_dir`. Each row will contain the filename, right prediction, false positive, and false negative.

If you haven't already, please ensure you are using the latest version of the Ultralytics packages to avoid any compatibility issues.

For more detailed information on the validation process, you can refer to the [Ultralytics documentation](https://docs.ultralytics.com/reference/models/yolo/detect/val/).

I hope this helps! If you have any further questions, feel free to ask.

**Comment by saroshpatel** [comment]
Thank you so much for our help, this is great ! Mine was too convoluted  :p

**Comment by glenn-jocher** [comment]
@saroshpatel you're welcome! 😊 I'm glad to hear that the solution was helpful to you. If you encounter any more issues or have further questions, feel free to ask. 

For future reference, if you run into any bugs or need to report an issue, providing a minimum reproducible example can greatly expedite the troubleshooting process. You can find more details on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Also, please ensure you're using the latest version of the Ultralytics packages to benefit from the latest fixes and features.

Happy coding! 🚀

**Comment by saroshpatel** [comment]
Hello,

I tried to integrate the functionality within update_metrics method however I notice that these two self.niou and the method self._prepare_batch() are not defined in the BaseValidator()

I am using version 8.2.45 

Thank you once again for your help !

**Comment by glenn-jocher** [comment]
Hello @saroshpatel,

Thank you for your feedback! It looks like you're encountering an issue with undefined attributes and methods in the `BaseValidator` class.

To address this, please ensure you're using the latest version of the Ultralytics packages, as updates often include important fixes and enhancements. You can update your packages using:
```bash
pip install --upgrade ultralytics
```

If the issue persists, it would be very helpful if you could provide a minimum reproducible example. This allows us to better understand the context and offer more precise assistance. You can find guidance on creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

In the meantime, you might want to check if the `DetectionValidator` class (or another specific validator class) includes the attributes and methods you're looking for. Sometimes, these functionalities are defined in more specialized classes rather than the base class.

Here's a quick example of how you might adapt the code to use `DetectionValidator`:

```python
from ultralytics.yolo.v8.detect import DetectionValidator

class CustomDetectionValidator(DetectionValidator):
    def update_metrics(self, preds, batch):
        # Your custom implementation here
        pass

# Use your custom validator
validator = CustomDetectionValidator()
```

I hope this helps! If you have any further questions or need additional assistance, feel free to ask. 😊
