### ISSUE TITLE
YoloV8 Adding a new class without disturbing the trained classes

### ISSUE THREAD

**Issue by prajwal-radome** [ultralytics/ultralytics#13965]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

So I have trained a model for instance segmentation with 2 classes. Now, I want to add another class and train the model. But I dont want to simply add the images and train the entire dataset again. I have gone through transfer learning with freezing the backbone layers generally, but what I want to understand is what layers can be frozen and how do we know which layers are the backbone to freeze them?

**Comment by glenn-jocher** [comment]
@prajwal-radome hi there,

Thank you for your question! Adding a new class to a pre-trained YOLOv8 model without disturbing the existing classes is a common scenario that can be effectively handled using transfer learning techniques.

To achieve this, you can freeze certain layers of the model to retain the learned features for the existing classes while allowing the model to learn the new class. Typically, you would freeze the backbone layers, which are responsible for feature extraction, and fine-tune the head layers, which are responsible for classification and detection.

Here's a concise guide on how to proceed:

1. **Identify the Backbone Layers**: In YOLOv8, the backbone layers are generally the initial layers of the model that extract features from the input images. These layers are followed by the head layers that perform the final classification and detection tasks.

2. **Freezing the Backbone Layers**: You can freeze the backbone layers by setting their `requires_grad` attribute to `False`. This ensures that their weights are not updated during training. Here's an example of how to do this in code:

    ```python
    from ultralytics import YOLO

    # Load your pre-trained model
    model = YOLO('path/to/your/model.pt')

    # Freeze the backbone layers
    for name, param in model.named_parameters():
        if 'backbone' in name:
            param.requires_grad = False

    # Train the model with the new class
    model.train(data='path/to/your/dataset.yaml', epochs=50, imgsz=640)
    ```

3. **Fine-Tuning the Model**: After freezing the backbone layers, you can proceed to fine-tune the model with your new dataset that includes the additional class. This approach allows the model to retain the knowledge of the existing classes while learning to detect the new class.

4. **Verify the Latest Versions**: Ensure you are using the latest versions of the Ultralytics packages to benefit from the latest features and bug fixes. You can update your packages using:
    ```bash
    pip install --upgrade ultralytics
    ```

For more detailed information on creating a reproducible example, please refer to our [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example) guide.

I hope this helps! If you have any further questions, feel free to ask. 😊

**Comment by laugh12321** [comment]
@prajwal-radome 一种简单的方法是预留一些额外的空类别给模型，但如果新增的类别数量超过了预留的空间，这种方法就无法满足需求了。然而，有一种更灵活的方式可以动态预留类别的空间。
在YOLO系列中，模型的Backbone用于提取特征，而分类则是在Detect Head中完成的。因此，要实现新增类别，只需在Detect Head中动态添加新的类别即可。

```python
def update_checkpoint_with_new_classes(source: Union[Path, str], target: Union[Path, str], new_classes: List[str]) -> None:
    """
    Update checkpoint with new classes.

    Args:
        source (Union[Path, str]): Path to the source checkpoint file.
        target (Union[Path, str]): Path to save the target checkpoint file.
        new_classes (List[str]): List of new classes to be added.
    """
    # Load checkpoint
    ckpt = torch.load(source, map_location="cpu")

    # Add new classes to names
    names = ckpt["model"].names
    max_key = max(names.keys())
    for i, new_class in enumerate(new_classes, start=max_key + 1):
        names[i] = new_class
    ckpt["model"].names = names

    # Update parameters in the model
    add_nc = len(new_classes)
    for name, module in ckpt["model"].named_modules():
        # Get Detect Module
        if isinstance(module, torch.nn.modules.module.Module) and hasattr(module, 'nc') and name:
            module.nc += add_nc
            module.no = 64 + module.nc
            for n, m in module.named_modules():
                # Get classify conv head
                if isinstance(m, torch.nn.modules.conv.Conv2d) and "cv3" in n and "conv" not in n:
                    for param in m.parameters():
                        flatten_data = param.data.view(-1)
                        min_value = torch.min(flatten_data)
                        max_value = torch.max(flatten_data)
                        random_data = (max_value - min_value) * torch.rand((add_nc, *param.data.shape[1:])) + min_value
                        param.data = torch.cat((param.data, random_data), dim=0)

    # Save updated checkpoint
    torch.save(ckpt, target)
```

**Comment by glenn-jocher** [comment]
Hi @prajwal-radome,

Thank you for your follow-up! 😊

To dynamically add new classes to your YOLOv8 model via the CLI, you would indeed need to create a custom script to update the model checkpoint with the new classes. Once you have this script, you can run it as part of your workflow.

Here's a concise approach to achieve this:

1. **Create the Custom Script**: Save the script provided earlier to a file, for example, `update_checkpoint.py`.

2. **Run the Script**: Execute the script to update your model checkpoint with the new classes. You can do this directly from the command line.

Here’s a quick example of how you can run the script:

```bash
python update_checkpoint.py --source path/to/your/model.pt --target path/to/updated_model.pt --new_classes "new_class1,new_class2"
```

3. **Continue Training**: Use the updated model checkpoint to continue training with the new classes:

```bash
yolo train model=path/to/updated_model.pt data=path/to/your/dataset.yaml epochs=50 imgsz=640
```

This way, you can seamlessly integrate the addition of new classes into your existing CLI-based workflow without disrupting your current setup.

If you encounter any issues or need further assistance, feel free to ask. Happy training! 🚀
