### ISSUE TITLE
How to run tensorrt model on a specific device id, let's say device='1'.

### ISSUE THREAD

**Issue by alaap001** [ultralytics/ultralytics#13961]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey, when I try to load tensorRT model on a second GPU I get the following error:

`model = YOLO(trtModel, task="detect", device= device1)`

*Error:* `TypeError: YOLO.__init__() got an unexpected keyword argument 'device'`

and if I do 
`items_model = YOLO(items_weight, task="detect").to(torch.device(f"cuda:{device1}"))`

I get: 
```
TypeError: model='trtModel.engine' should be a *.pt PyTorch model to run this method, but is a different format. PyTorch models can train, val, predict and export, i.e. 'model.train(data=...)', but exported formats like ONNX, TensorRT etc. only support 'predict' and 'val' modes, i.e. 'yolo predict model=yolov8n.onnx'.

To run CUDA or MPS inference please pass the device argument directly in your inference command, i.e. 'model.predict(source=..., device=0)'  
```

if I pass directly device=1 in inference it still runs on device 0. So this becomes a problem as I am not able to load model on correct device and this can be a basic requirement to run trt model on a different GPU than 0.

Thanks.

**Comment by glenn-jocher** [comment]
Hello,

Thank you for reaching out with your question. It looks like you're encountering issues when trying to run a TensorRT model on a specific GPU device. The error messages indicate that the `device` argument is not recognized in the `YOLO` class initialization for TensorRT models.

To run inference on a specific GPU with a TensorRT model, you should specify the device directly in the `predict` method. Here's how you can do it:

```python
from ultralytics import YOLO

# Load the TensorRT model
model = YOLO("path/to/your/model.engine")

# Run inference on a specific device (e.g., device 1)
results = model.predict(source="path/to/your/image.jpg", device=1)
```

This approach ensures that the inference runs on the specified GPU. If you continue to experience issues with the model running on the wrong device, please ensure that your environment is correctly set up to recognize multiple GPUs and that the CUDA drivers are properly installed.

Additionally, make sure you are using the latest version of the Ultralytics package, as updates often include bug fixes and improvements. You can update the package using:

```bash
pip install --upgrade ultralytics
```

If the issue persists, providing a minimum reproducible example would be very helpful for further investigation. You can find guidelines on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions or need further assistance. 😊

**Comment by glenn-jocher** [comment]
@alaap001 hello,

Thank you for the additional information. It seems like you're encountering a persistent issue with specifying the GPU device for TensorRT models. Let's address this step-by-step.

Firstly, it's great to hear that you're using the latest version of the Ultralytics package. Given that the issue persists, it would be helpful to have a minimum reproducible example to better understand and diagnose the problem. You can find guidelines on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

In the meantime, let's try a workaround to ensure the model runs on the specified GPU. You can set the CUDA_VISIBLE_DEVICES environment variable to control which GPU is visible to your application. Here's how you can do it:

```python
import os
from ultralytics import YOLO

# Set the environment variable to specify the GPU
os.environ["CUDA_VISIBLE_DEVICES"] = "1"  # Replace '1' with your desired GPU ID

# Load the TensorRT model
model = YOLO("path/to/your/model.engine")

# Run inference
results = model.predict(source="path/to/your/image.jpg")
```

This approach ensures that only the specified GPU is visible to the application, effectively forcing the model to run on that GPU.

If this workaround does not resolve the issue, please provide a reproducible example, and we will investigate further. Your feedback is invaluable in helping us improve the Ultralytics experience for everyone.

Thank you for your patience and cooperation! 😊

**Comment by will319** [comment]
In \ultralytics\utils\torch_utils.py line 99
`arg = 'cuda:0'`
When I change it to `arg = 'cuda:{device[0]}'`, it doesn't switch gpu, it runs on the gpu I specify
Is that the reason?
