### ISSUE TITLE
Get coordinates for bounding box in real time

### ISSUE THREAD

**Issue by mazik1496** [ultralytics/ultralytics#1397]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Using supervision, I created a bounding box in the video output with cv2 for the custom data learned with yolov8. 

![image](https://user-images.githubusercontent.com/80936392/224684311-584cabf0-7cc9-4ca7-8cbe-b379ce14eae6.png)

Now, what I'm curious about here is that according to yolov8 docs, the coordinates for the bounding box can be created as follows, but when the video is output in real time through cv2, the number and coordinates of the bounding box change. How should I output the coordinates of the bounding box for this? Also, at this time, how can I get the value of i from result.boxes[i]?

**Comment by glenn-jocher** [comment]
@mazik1496 you can automatically show or save an annotated video with `yolo predict source=video.mp4 show save`

**Comment by Laughing-q** [comment]
@mazik1496 for a video you can get the result this way:
```python
for result in model.predict(source="video.mp4", stream=True):
    box = result.boxes
```
each `result` here is the predictions for each frame.

**Comment by Laughing-q** [comment]
@glenn-jocher 
```python
results = model.predict(source="video.mp4", stream=True)
```
this command returns a generator, with `stream=True` it won't do anything if users do not go on with a for loop.
```python
for result in results:
    pass
```
Probably it's better we stick with `stream=False` as default. I think most users are used to the current usage `results=model.predict()` which returns a list of predictions, they might ask why there's nothing happening if we set `stream=True` as default..

**Comment by glenn-jocher** [comment]
@Laughing-q ah got it!
