### ISSUE TITLE
Validation results 

### ISSUE THREAD

**Issue by martin0496** [ultralytics/ultralytics#1398]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I trained the model on a custom dataset for object detection and the projection results on the test data are good.
the problem is with the validation results. when I do the validation multiple times on the same data and using the same model and params, I am getting different results for mAP that are reaching 0.25 difference in some trials. 
How this is explained and how to detect which validation result is revealing the true performance of the model ?

**Comment by glenn-jocher** [comment]
@martin0496 validation is deterministic, you will get the same exact result every time. If this is not the case for you then there is a problem and you should submit a new bug report with a minimum reproducible example of the bug you are seeing.
