### ISSUE TITLE
Fail to run on videos from some specific cameras

### ISSUE THREAD

**Issue by wuhanshuo** [ultralytics/ultralytics#13989]

**Comment by glenn-jocher** [comment]
@wuhanshuo hi there,

Thank you for bringing this to our attention. To help us diagnose the issue, could you please provide a minimum reproducible example? This will allow us to better understand the problem and offer a more precise solution. You can find guidance on creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of all relevant packages, as updates often include important bug fixes and improvements.

Looking forward to your response so we can assist you further! 😊
