### ISSUE TITLE
Object of type Masks is not JSON serializable

### ISSUE THREAD

**Issue by sarpx** [ultralytics/ultralytics#1399]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I can't convert segmentation results to json format for Rest Api.
What could I be overlooking? Can you write a simple example?

Error:Object of type Masks is not JSON serializable

**Comment by glenn-jocher** [comment]
@sarpx 👋 hi, thanks for letting us know about this possible problem with YOLO🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub, and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved.
- ✅ **Unmodified** – Your problem must be reproducible using official YOLO code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by sarpx** [comment]
@glenn-jocher 
m = YOLO(f'/yolo/sonuclar/son/best.pt')
model = m.predict
results = model(source=IMAGE, device=0, retina_masks=True, save=True, save_txt=True) 
labels text:
`0 0.364062 0.716667 0.3625 0.71875 0.3625 0.770833 0.364062 0.772917 0.376563 0.772917 0.378125 0.775 0.573438 0.775 0.578125 0.76875 0.576563 0.766667 0.576563 0.754167 0.575 0.752083 0.575 0.725 0.573438 0.722917 0.573438 0.71875 0.571875 0.716667 0.786607
57 0.239063 0.691667 0.2375 0.69375 0.2375 0.745833 0.239063 0.747917 0.239063 0.752083 0.240625 0.754167 0.240625 0.75625 0.242188 0.758333 0.242188 0.760417 0.24375 0.7625 0.24375 0.770833 0.248437 0.777083 0.248437 0.779167 0.25 0.78125 0.25 0.785417 0.259375 0.797917 0.260938 0.797917 0.265625 0.804167 0.267188 0.804167 0.26875 0.80625 0.271875 0.80625 0.273438 0.808333 0.275 0.808333 0.278125 0.8125 0.28125 0.8125 0.282813 0.814583 0.2875 0.814583 0.289062 0.816667 0.292188 0.816667 0.29375 0.81875 0.296875 0.81875 0.296875 0.814583 0.298438 0.8125 0.298438 0.729167 0.296875 0.727083 0.296875 0.725 0.295312 0.725 0.292188 0.720833 0.290625 0.720833 0.289062 0.71875 0.2875 0.71875 0.285937 0.716667 0.28125 0.716667 0.279687 0.714583 0.276563 0.714583 0.273438 0.710417 0.271875 0.710417 0.270312 0.708333 0.265625 0.708333 0.264062 0.70625 0.2625 0.70625 0.260938 0.704167 0.259375 0.704167 0.257812 0.702083 0.25625 0.702083 0.254687 0.7 0.251563 0.7 0.246875 0.69375 0.245312 0.69375 0.24375 0.691667 0.787156
41 0.248437 0.458333 0.246875 0.460417 0.245312 0.460417 0.24375 0.4625 0.24375 0.464583 0.240625 0.46875 0.240625 0.470833 0.23125 0.483333 0.23125 0.485417 0.225 0.49375 0.225 0.497917 0.223438 0.5 0.223438 0.502083 0.220313 0.50625 0.220313 0.508333 0.21875 0.510417 0.21875 0.575 0.220313 0.577083 0.220313 0.579167 0.221875 0.58125 0.226562 0.58125 0.232812 0.589583 0.234375 0.589583 0.239063 0.595833 0.240625 0.595833 0.242188 0.597917 0.24375 0.597917 0.245312 0.6 0.246875 0.6 0.251563 0.60625 0.253125 0.60625 0.254687 0.608333 0.25625 0.608333 0.260938 0.614583 0.264062 0.614583 0.265625 0.616667 0.267188 0.616667 0.270312 0.620833 0.271875 0.620833 0.273438 0.622917 0.275 0.622917 0.276563 0.625 0.278125 0.625 0.282813 0.63125 0.285937 0.63125 0.295312 0.64375 0.296875 0.64375 0.296875 0.639583 0.298438 0.6375 0.298438 0.635417 0.296875 0.633333 0.296875 0.622917 0.295312 0.620833 0.295312 0.61875 0.29375 0.616667 0.29375 0.6125 0.292188 0.610417 0.292188 0.597917 0.290625 0.595833 0.290625 0.591667 0.289062 0.589583 0.289062 0.5875 0.2875 0.585417 0.2875 0.58125 0.285937 0.579167 0.285937 0.570833 0.284375 0.56875 0.284375 0.566667 0.282813 0.564583 0.282813 0.5625 0.28125 0.560417 0.28125 0.558333 0.279687 0.55625 0.279687 0.545833 0.278125 0.54375 0.278125 0.541667 0.276563 0.539583 0.276563 0.5375 0.275 0.535417 0.275 0.533333 0.273438 0.53125 0.273438 0.522917 0.271875 0.520833 0.271875 0.51875 0.26875 0.514583 0.26875 0.510417 0.267188 0.508333 0.267188 0.502083 0.265625 0.5 0.265625 0.497917 0.2625 0.49375 0.2625 0.489583 0.260938 0.4875 0.260938 0.48125 0.259375 0.479167 0.259375 0.477083 0.25625 0.472917 0.25625 0.470833 0.254687 0.46875 0.254687 0.460417 0.253125 0.460417 0.251563 0.458333 0.826209
74 0.226562 0.585417 0.225 0.5875 0.225 0.6375 0.226562 0.639583 0.226562 0.647917 0.228125 0.65 0.228125 0.65625 0.229687 0.658333 0.229687 0.666667 0.23125 0.66875 0.23125 0.679167 0.232812 0.68125 0.232812 0.683333 0.235938 0.6875 0.2375 0.6875 0.239063 0.689583 0.240625 0.689583 0.242188 0.691667 0.24375 0.691667 0.245312 0.69375 0.246875 0.69375 0.25 0.697917 0.253125 0.697917 0.254687 0.7 0.25625 0.7 0.257812 0.702083 0.259375 0.702083 0.260938 0.704167 0.2625 0.704167 0.264062 0.70625 0.26875 0.70625 0.270312 0.708333 0.273438 0.708333 0.276563 0.7125 0.279687 0.7125 0.28125 0.714583 0.284375 0.714583 0.285937 0.716667 0.289062 0.716667 0.290625 0.71875 0.292188 0.71875 0.295312 0.722917 0.296875 0.722917 0.298438 0.720833 0.298438 0.716667 0.3 0.714583 0.3 0.689583 0.298438 0.6875 0.298438 0.652083 0.296875 0.65 0.296875 0.647917 0.29375 0.64375 0.29375 0.641667 0.289062 0.635417 0.2875 0.635417 0.285937 0.633333 0.282813 0.633333 0.278125 0.627083 0.276563 0.627083 0.275 0.625 0.273438 0.625 0.271875 0.622917 0.270312 0.622917 0.267188 0.61875 0.265625 0.61875 0.264062 0.616667 0.260938 0.616667 0.25625 0.610417 0.254687 0.610417 0.253125 0.608333 0.251563 0.608333 0.25 0.60625 0.248437 0.60625 0.246875 0.604167 0.246875 0.602083 0.245312 0.602083 0.24375 0.6 0.242188 0.6 0.240625 0.597917 0.239063 0.597917 0.234375 0.591667 0.232812 0.591667 0.229687 0.5875 0.229687 0.585417 0.826909
65 0.301562 0.758333 0.3 0.760417 0.3 0.81875 0.303125 0.822917 0.307813 0.822917 0.309375 0.825 0.314063 0.825 0.315625 0.827083 0.31875 0.827083 0.320312 0.829167 0.326562 0.829167 0.328125 0.83125 0.348437 0.83125 0.35 0.833333 0.364062 0.833333 0.365625 0.835417 0.373437 0.835417 0.375 0.8375 0.39375 0.8375 0.395312 0.839583 0.426562 0.839583 0.428125 0.841667 0.471875 0.841667 0.473437 0.84375 0.503125 0.84375 0.504687 0.841667 0.529688 0.841667 0.53125 0.839583 0.567187 0.839583 0.56875 0.8375 0.582812 0.8375 0.584375 0.835417 0.590625 0.835417 0.592188 0.833333 0.604688 0.833333 0.60625 0.83125 0.623438 0.83125 0.625 0.829167 0.63125 0.829167 0.632812 0.827083 0.635938 0.827083 0.6375 0.825 0.642187 0.825 0.64375 0.822917 0.646875 0.822917 0.65 0.81875 0.65 0.7875 0.648438 0.785417 0.648438 0.7625 0.645312 0.758333 0.603125 0.758333 0.601562 0.760417 0.582812 0.760417 0.579687 0.764583 0.579687 0.76875 0.575 0.775 0.573438 0.775 0.571875 0.777083 0.529688 0.777083 0.528125 0.775 0.515625 0.775 0.514063 0.777083 0.40625 0.777083 0.404687 0.775 0.364062 0.775 0.360938 0.770833 0.360938 0.76875 0.359375 0.766667 0.359375 0.764583 0.35625 0.760417 0.354688 0.760417 0.353125 0.758333 0.834414
69 0.30625 0.65 0.304688 0.652083 0.303125 0.652083 0.301562 0.654167 0.301562 0.660417 0.3 0.6625 0.3 0.741667 0.301562 0.74375 0.301562 0.747917 0.303125 0.75 0.328125 0.75 0.329688 0.752083 0.339063 0.752083 0.340625 0.754167 0.353125 0.754167 0.354688 0.752083 0.354688 0.745833 0.35625 0.74375 0.35625 0.741667 0.354688 0.739583 0.354688 0.720833 0.35625 0.71875 0.35625 0.716667 0.357812 0.714583 0.3625 0.714583 0.364062 0.7125 0.370313 0.7125 0.371875 0.714583 0.571875 0.714583 0.575 0.71875 0.575 0.73125 0.576563 0.733333 0.576563 0.752083 0.58125 0.758333 0.601562 0.758333 0.603125 0.75625 0.639063 0.75625 0.640625 0.754167 0.64375 0.754167 0.646875 0.75 0.646875 0.74375 0.648438 0.741667 0.648438 0.6625 0.646875 0.660417 0.646875 0.652083 0.64375 0.652083 0.642187 0.65 0.625 0.65 0.623438 0.652083 0.620313 0.652083 0.61875 0.654167 0.617188 0.654167 0.615625 0.65625 0.6125 0.65625 0.610937 0.658333 0.598437 0.658333 0.596875 0.660417 0.59375 0.660417 0.592188 0.6625 0.590625 0.6625 0.589063 0.664583 0.585938 0.664583 0.584375 0.666667 0.56875 0.666667 0.567187 0.66875 0.5625 0.66875 0.560938 0.670833 0.559375 0.670833 0.557813 0.672917 0.553125 0.672917 0.551562 0.675 0.540625 0.675 0.539062 0.677083 0.532812 0.677083 0.53125 0.679167 0.528125 0.679167 0.526563 0.68125 0.51875 0.68125 0.517187 0.683333 0.501562 0.683333 0.5 0.685417 0.421875 0.685417 0.420312 0.683333 0.398438 0.683333 0.396875 0.68125 0.392188 0.68125 0.390625 0.679167 0.3875 0.679167 0.385938 0.677083 0.382812 0.677083 0.38125 0.675 0.373437 0.675 0.371875 0.672917 0.367188 0.672917 0.365625 0.670833 0.3625 0.670833 0.360938 0.66875 0.35625 0.66875 0.354688 0.666667 0.346875 0.666667 0.345313 0.664583 0.342187 0.664583 0.340625 0.6625 0.339063 0.6625 0.3375 0.660417 0.334375 0.660417 0.332812 0.658333 0.326562 0.658333 0.325 0.65625 0.321875 0.65625 0.31875 0.652083 0.315625 0.652083 0.314063 0.65 0.844116
52 0.795313 0.658333 0.79375 0.660417 0.789062 0.660417 0.782812 0.66875 0.78125 0.66875 0.78125 0.670833 0.779688 0.672917 0.778125 0.672917 0.776563 0.675 0.775 0.675 0.770312 0.68125 0.76875 0.68125 0.767187 0.683333 0.765625 0.683333 0.764063 0.685417 0.7625 0.685417 0.759375 0.689583 0.757812 0.689583 0.75625 0.691667 0.753125 0.691667 0.751562 0.69375 0.75 0.69375 0.748438 0.695833 0.746875 0.695833 0.745313 0.697917 0.74375 0.697917 0.742188 0.7 0.739062 0.7 0.7375 0.702083 0.734375 0.702083 0.732813 0.704167 0.73125 0.704167 0.729688 0.70625 0.726562 0.70625 0.725 0.708333 0.720312 0.708333 0.71875 0.710417 0.715625 0.710417 0.714063 0.7125 0.710938 0.7125 0.709375 0.714583 0.70625 0.714583 0.704687 0.716667 0.696875 0.716667 0.695312 0.71875 0.689062 0.71875 0.6875 0.720833 0.684375 0.720833 0.682813 0.722917 0.678125 0.722917 0.676562 0.725 0.66875 0.725 0.667188 0.727083 0.6625 0.727083 0.660937 0.729167 0.659375 0.729167 0.657812 0.73125 0.657812 0.733333 0.65625 0.735417 0.65625 0.81875 0.657812 0.820833 0.665625 0.820833 0.667188 0.81875 0.66875 0.81875 0.670313 0.816667 0.675 0.816667 0.676562 0.814583 0.685938 0.814583 0.6875 0.8125 0.690625 0.8125 0.692187 0.810417 0.695312 0.810417 0.696875 0.808333 0.701563 0.808333 0.703125 0.80625 0.709375 0.80625 0.710938 0.804167 0.7125 0.804167 0.714063 0.802083 0.715625 0.802083 0.71875 0.797917 0.720312 0.797917 0.751562 0.75625 0.753125 0.75625 0.754687 0.754167 0.75625 0.754167 0.759375 0.75 0.760938 0.75 0.7625 0.747917 0.765625 0.747917 0.767187 0.745833 0.76875 0.745833 0.771875 0.741667 0.775 0.741667 0.776563 0.739583 0.779688 0.739583 0.78125 0.7375 0.782812 0.7375 0.7875 0.73125 0.789062 0.73125 0.790625 0.729167 0.790625 0.722917 0.792188 0.720833 0.792188 0.702083 0.79375 0.7 0.79375 0.691667 0.795313 0.689583 0.795313 0.685417 0.796875 0.683333 0.796875 0.672917 0.798437 0.670833 0.798437 0.6625 0.857206
81 0.801562 0.56875 0.8 0.570833 0.798437 0.570833 0.796875 0.572917 0.79375 0.572917 0.792188 0.575 0.7875 0.575 0.785937 0.577083 0.78125 0.577083 0.779688 0.579167 0.764063 0.579167 0.760938 0.583333 0.759375 0.583333 0.757812 0.585417 0.75625 0.585417 0.754687 0.5875 0.753125 0.5875 0.751562 0.589583 0.75 0.589583 0.746875 0.59375 0.745313 0.59375 0.740625 0.6 0.739062 0.6 0.732813 0.608333 0.73125 0.608333 0.729688 0.610417 0.728125 0.610417 0.725 0.614583 0.723437 0.614583 0.721875 0.616667 0.720312 0.616667 0.71875 0.61875 0.717188 0.61875 0.715625 0.620833 0.714063 0.620833 0.7125 0.622917 0.709375 0.622917 0.707812 0.625 0.701563 0.625 0.7 0.627083 0.69375 0.627083 0.692187 0.629167 0.6875 0.629167 0.685938 0.63125 0.68125 0.63125 0.679688 0.633333 0.678125 0.633333 0.676562 0.635417 0.675 0.635417 0.673437 0.6375 0.665625 0.6375 0.664062 0.639583 0.660937 0.639583 0.657812 0.64375 0.657812 0.645833 0.65625 0.647917 0.65625 0.720833 0.657812 0.722917 0.657812 0.727083 0.660937 0.727083 0.6625 0.725 0.665625 0.725 0.667188 0.722917 0.675 0.722917 0.676562 0.720833 0.68125 0.720833 0.682813 0.71875 0.685938 0.71875 0.6875 0.716667 0.69375 0.716667 0.695312 0.714583 0.703125 0.714583 0.704687 0.7125 0.709375 0.7125 0.710938 0.710417 0.7125 0.710417 0.714063 0.708333 0.71875 0.708333 0.720312 0.70625 0.725 0.70625 0.726562 0.704167 0.729688 0.704167 0.73125 0.702083 0.732813 0.702083 0.734375 0.7 0.7375 0.7 0.739062 0.697917 0.742188 0.697917 0.74375 0.695833 0.745313 0.695833 0.746875 0.69375 0.748438 0.69375 0.75 0.691667 0.751562 0.691667 0.753125 0.689583 0.754687 0.689583 0.75625 0.6875 0.759375 0.6875 0.7625 0.683333 0.764063 0.683333 0.765625 0.68125 0.767187 0.68125 0.76875 0.679167 0.770312 0.679167 0.773438 0.675 0.775 0.675 0.776563 0.672917 0.778125 0.672917 0.782812 0.666667 0.784375 0.666667 0.7875 0.6625 0.789062 0.6625 0.796875 0.652083 0.796875 0.65 0.798437 0.647917 0.798437 0.635417 0.8 0.633333 0.8 0.622917 0.801562 0.620833 0.801562 0.614583 0.803125 0.6125 0.803125 0.6 0.804688 0.597917 0.804688 0.5875 0.80625 0.585417 0.80625 0.58125 0.807813 0.579167 0.807813 0.572917 0.809375 0.570833 0.809375 0.56875 0.860329`

for segmentation.
I want to get this as json data over a method, not as text. We used to be able to get it as follows.. But we can't anymore. results.pandas().xyxy[0].to_json(orient="records")

**Comment by glenn-jocher** [comment]
@sarpx that's incorrect, YOLOv5 torch hub models are not capable of returning segmentation results, so there's never been this capability, at least in Ultralytics YOLO models.

Your code above is not reproducible as 'labels text' is not a command. 

@sarpx 👋 hi, thanks for letting us know about this possible problem with YOLO🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub, and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved.
- ✅ **Unmodified** – Your problem must be reproducible using official YOLO code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by sarpx** [comment]
Took a while as I don't master the code:

m = YOLO(f'./yolov8/sn/best.pt') model = m.predict results = model(source=IMAGE, device=0, conf=0.10, retina_masks=True)  a = [] det, mask = results[0].boxes.cpu(), results[0].masks.cpu() for j, d in enumerate(reversed(det)): cls, conf = d.cls.squeeze(), d.conf.squeeze() seg = mask.segments[len(det) - j - 1].copy()  # reversed mask.segments seg = seg.reshape(-1)  # (n,2) to (n*2) line = (cls, *seg, conf) a.append(('%g ' * len(line)).rstrip() % line)

**Comment by pderrenger** [comment]
@sarpx it looks like you're trying to obtain segmentation results from YOLOv8 using the `predict` method. However, the code you provided doesn't seem to align with the typical usage of YOLOv8 for segmentation.

If you are looking to obtain segmentation results, I would recommend using the `model.predict` method with the `retina_masks=True` argument, which should provide you with the segmentation masks.

Here's an example of how you might achieve this:

```python
m = YOLO(f'./yolov8/sn/best.pt')
model = m.predict

results = model(source=IMAGE, device=0, conf=0.10, retina_masks=True)

segmentation_results = results.xyxy[0].to_json(orient="records")
```

This code snippet assumes that you have already loaded the YOLOv8 model, and `IMAGE` represents the input image for which you want to obtain the segmentation results.

Please give this a try and let me know if you encounter any further issues.

**Comment by glenn-jocher** [comment]
@pderrenger, it seems there's a bit of confusion regarding the output format for segmentation masks. In YOLOv8, when you enable `retina_masks`, the results object should contain the segmentation masks you're looking for.

To extract and serialize the segmentation masks to JSON, you'll need to process the masks into a serializable format manually, as the masks object is not directly serializable to JSON.

You can iterate over the masks and convert them to a suitable format (like a list of coordinates for each mask) and then use a JSON library to serialize that list.

Remember to handle the conversion carefully to maintain the structure you need for your application. If you need further assistance, please refer to the documentation or consider opening an issue with a minimal reproducible example.
