### ISSUE TITLE
Confidence Labels

### ISSUE THREAD

**Issue by connerlacey7** [ultralytics/ultralytics#13998]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am currently using a model to predict one class using bounding boxes. The photos I am using are narrow and because of this my labels are being cut off to where I can't see the confidence label. I have tried using the show_labels = False and show_conf = True but using this hides the label entirely. Is there a way to make it fit better or only display the confidence?

**Comment by glenn-jocher** [comment]
@connerlacey7 hi there,

Thank you for reaching out and for providing a clear description of your issue. It sounds like you're encountering a problem with the display of confidence labels on narrow images. Let's see how we can address this.

To customize the display of labels and confidence scores, you can use the `plot()` method with specific arguments to control the appearance of the annotations. Here's an example of how you can adjust the display to show only the confidence scores:

```python
from ultralytics import YOLO

# Load your model
model = YOLO("path/to/your/model.pt")

# Run inference on your images
results = model.predict("path/to/your/image.jpg")

# Customize the plot to show only confidence scores
for result in results:
    result.plot(show_labels=False, show_conf=True)
```

In this example, `show_labels=False` hides the class labels, and `show_conf=True` ensures that only the confidence scores are displayed. This should help in making the confidence labels fit better on narrow images.

If you continue to experience issues, please ensure you are using the latest version of the Ultralytics package, as updates often include bug fixes and improvements. If the problem persists, providing a minimum reproducible example can greatly assist in diagnosing the issue. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any further questions or need additional assistance. 😊

**Comment by connerlacey7** [comment]
I just tried running the for loop on a prediction and i got the error that says 
ypeError                                 Traceback (most recent call last)
Cell In[8], line 4
      2 results = model.predict(image, save=True, save_txt=True, conf = 0.5)
      3 for result in results:
----> 4     result.plot(show_labels=False, show_conf=True)

TypeError: Results.plot() got an unexpected keyword argument 'show_labels'

**Comment by glenn-jocher** [comment]
Hi @connerlacey7,

Thank you for bringing this to our attention! It looks like there might be a small issue with the `plot()` method's arguments.

The `plot()` method does not accept `show_labels` and `show_conf` directly. Instead, you can control the display of labels and confidence scores using the `save` and `show` parameters. Here's an updated example to help you achieve your goal:

```python
from ultralytics import YOLO

# Load your model
model = YOLO("path/to/your/model.pt")

# Run inference on your images
results = model.predict("path/to/your/image.jpg")

# Customize the plot to show only confidence scores
for result in results:
    result.plot(show=True)  # This will display the results
```

If you need to hide labels and only show confidence scores, you might need to manually adjust the annotations after plotting. Unfortunately, the current version might not support this directly through the `plot()` method.

Please ensure you are using the latest version of the Ultralytics package, as updates might include improvements and bug fixes. If the issue persists, providing a minimum reproducible example can greatly assist in diagnosing the problem. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any further questions or need additional assistance. 😊

**Comment by kira-pareser** [comment]
> Hi @connerlacey7,
> 
> Thank you for bringing this to our attention! It looks like there might be a small issue with the `plot()` method's arguments.
> 
> The `plot()` method does not accept `show_labels` and `show_conf` directly. Instead, you can control the display of labels and confidence scores using the `save` and `show` parameters. Here's an updated example to help you achieve your goal:
> 
> ```python
> from ultralytics import YOLO
> 
> # Load your model
> model = YOLO("path/to/your/model.pt")
> 
> # Run inference on your images
> results = model.predict("path/to/your/image.jpg")
> 
> # Customize the plot to show only confidence scores
> for result in results:
>     result.plot(show=True)  # This will display the results
> ```
> 
> If you need to hide labels and only show confidence scores, you might need to manually adjust the annotations after plotting. Unfortunately, the current version might not support this directly through the `plot()` method.
> 
> Please ensure you are using the latest version of the Ultralytics package, as updates might include improvements and bug fixes. If the issue persists, providing a minimum reproducible example can greatly assist in diagnosing the problem. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> Feel free to reach out if you have any further questions or need additional assistance. 😊

hi, i want to show conf and id only in ```model.track`` but it's not work
 Im trying to hide labels and show confidence in model.track but it's still showing the class, can you show me some instruction plesase?

```
        results = model.track(source=frame, conf = conf, show_labels=False, show_conf=True, persist=True, verbose=True, tracker='botsort.yaml', cls=0)
        # Annotated frame from YOLO
        annotated_frame = results[0].plot()
```
![image](https://github.com/user-attachments/assets/55324aed-8a25-4fdc-bd9a-2e6a1ff48516)

**Comment by glenn-jocher** [comment]
Hi @kira-pareser,

The `show_labels` and `show_conf` arguments are not valid for the `track` method or the `plot` function. To hide class labels and display only confidence scores, you can use the `plot()` method's `labels` and `conf` arguments as follows:

```python
annotated_frame = results[0].plot(labels=False, conf=True)
```

Please make sure you're using the correct arguments for the `plot()` method. If you encounter further issues, consider updating to the latest Ultralytics version as newer releases may include fixes or enhancements. For more details, refer to the [Results.plot() documentation](https://docs.ultralytics.com/reference/engine/results/#plot).

**Comment by kira-pareser** [comment]
hi @glenn-jocher 
I tried to put   `labels=False, conf=True` to `plot()`but it's not showing the `conf`, i'm detecting single class only

```annotated_frame = results[0].plot(labels=False, conf=True)```

![image](https://github.com/user-attachments/assets/f39e41b2-f2dc-460a-aa18-157362461ed4)

**Comment by glenn-jocher** [comment]
Thank you for your detailed explanation. The `plot()` method's `labels` and `conf` arguments should work as intended to hide labels and display only confidence scores. However, this behavior may depend on the Ultralytics version you're using. Ensure you're using the latest release (`pip install ultralytics --upgrade`) and try again. If the issue persists, please provide a minimal reproducible example so we can investigate further. For more details, refer to the [Results.plot() documentation](https://docs.ultralytics.com/reference/engine/results/#plot).
