### ISSUE TITLE
Getting all the mAP50-95 interval values for IoU thresholds ranging from 0.50 to 0.95.

### ISSUE THREAD

**Issue by ResearcherWork** [ultralytics/ultralytics#14000]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I’m not sure if I’m confused, but I want to get all the values of AP50-95 or mAP50-95 for IoU thresholds ranging from 0.50 to 0.95. Typically, this involves an interval that contains all values for each threshold from 0.50 to 0.95 with a step of 0.05. Please, how can I obtain this interval?

**Comment by glenn-jocher** [comment]
@ResearcherWork hello,

Thank you for reaching out! To obtain the mAP values for IoU thresholds ranging from 0.50 to 0.95 in increments of 0.05, you can use the `val` method in the Ultralytics YOLO framework. The `val` method computes these metrics by default and stores them in the `metrics` attribute of the results.

Here's a concise example of how you can achieve this using Python:

```python
from ultralytics import YOLO

# Load your trained model
model = YOLO('path/to/your/model.pt')

# Validate the model
metrics = model.val()

# Access the mAP values for IoU thresholds from 0.50 to 0.95
map50_95 = metrics.box.maps  # This is a list of mAP values for each class
```

The `metrics.box.maps` attribute will contain the mAP values for each class at the specified IoU thresholds. If you need to access the overall mAP, you can use `metrics.box.map` for mAP50-95 and `metrics.box.map50` for mAP50.

If you encounter any issues or have further questions, please ensure you are using the latest version of the Ultralytics packages. Additionally, providing a minimum reproducible example can help us assist you more effectively. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you need any more assistance! 😊

**Comment by ResearcherWork** [comment]
Hello, thank you for the answer! Here, I'm getting one mAP50-95 value for each class, but I want mAP50-95 values with increments of 0.05. So, for each class, I need an interval of 10 values, for each IoU threshold in the range [0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90, 0.95]. Please, how can I get this interval?

**Comment by glenn-jocher** [comment]
Hello @ResearcherWork,

Thank you for your follow-up! I understand that you need the mAP values for each class at specific IoU thresholds ranging from 0.50 to 0.95 in increments of 0.05. 

To achieve this, you can access the detailed metrics stored in the `metrics` attribute after running the `val` method. Here's how you can extract these values:

```python
from ultralytics import YOLO

# Load your trained model
model = YOLO('path/to/your/model.pt')

# Validate the model
metrics = model.val()

# Access the mAP values for each IoU threshold
iou_thresholds = [0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90, 0.95]
map_values = metrics.box.maps  # This is a list of mAP values for each class

# Extract mAP values for each IoU threshold
map_iou_intervals = {iou: [] for iou in iou_thresholds}
for iou in iou_thresholds:
    index = int((iou - 0.50) / 0.05)
    map_iou_intervals[iou] = [class_map[index] for class_map in map_values]

# Print the mAP values for each IoU threshold
for iou, values in map_iou_intervals.items():
    print(f"IoU {iou}: {values}")
```

This code snippet will give you the mAP values for each class at the specified IoU thresholds. The `map_iou_intervals` dictionary will contain the mAP values for each IoU threshold, allowing you to analyze the performance of your model in more detail.

If you encounter any issues or need further assistance, please ensure you are using the latest version of the Ultralytics packages. Providing a minimum reproducible example can also help us assist you more effectively. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions! 😊

**Comment by ResearcherWork** [comment]
Hello,

Thank you for the answer! However, the following line of code does not work:

`[class_map[index] for class_map in map_values]`

The `map_values` variable is a simple list like this:

`map_values: [      0.796      0.2985           0]`

Here, `class_map` is a simple float value (e.g., 0.796). Therefore, we cannot do `class_map[i]`.

**Comment by glenn-jocher** [comment]
Hello @ResearcherWork,

Thank you for your feedback! I apologize for the confusion. It seems I misunderstood the structure of `map_values`. Let's correct that.

To get the mAP values for each IoU threshold ranging from 0.50 to 0.95 in increments of 0.05, you can directly access the `metrics.box.maps` attribute, which provides the mAP values for each class at these IoU thresholds. Here's the corrected approach:

```python
from ultralytics import YOLO

# Load your trained model
model = YOLO('path/to/your/model.pt')

# Validate the model
metrics = model.val()

# Access the mAP values for each IoU threshold
iou_thresholds = [0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90, 0.95]
map_values = metrics.box.maps  # This is a list of mAP values for each IoU threshold

# Print the mAP values for each IoU threshold
for iou, value in zip(iou_thresholds, map_values):
    print(f"IoU {iou}: {value}")
```

This should give you the mAP values for each IoU threshold directly. If you encounter any further issues, please ensure you are using the latest version of the Ultralytics packages. Additionally, providing a minimum reproducible example can help us assist you more effectively. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions! 😊
