### ISSUE TITLE
What are the input layer name and output layer name of yolov8?

### ISSUE THREAD

**Issue by kimcheolhee80** [ultralytics/ultralytics#14006]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

What are the input layer name and output layer name of yolov8?

### Additional

.

**Comment by glenn-jocher** [comment]
@kimcheolhee80 hello! 

For YOLOv8 models, the input and output layer names can vary depending on the export format. Here’s a general guide:

### Input Layer Name
- Typically, the input layer is named `images` or `input` in most export formats.

### Output Layer Names
- For detection tasks, the output layers are usually named `output` or `output0` for bounding boxes and `output1` for class scores.

If you are exporting to ONNX, you can inspect the model to get the exact layer names using the following code snippet:

```python
import onnx

# Load the ONNX model
model = onnx.load("path/to/your/model.onnx")

# Print the input and output layer names
print("Input Layer Names:", [input.name for input in model.graph.input])
print("Output Layer Names:", [output.name for output in model.graph.output])
```

For more detailed information on exporting models and working with different formats, you can refer to the [YOLOv8 Export Documentation](https://docs.ultralytics.com/models/yolov8/#export).

If you encounter any issues or need further assistance, please provide a reproducible example as outlined in our [Minimum Reproducible Example Guide](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us assist you more effectively.

Best of luck with your project! 🚀
