### ISSUE TITLE
TensorRT export image size

### ISSUE THREAD

**Issue by its-jd** [ultralytics/ultralytics#1400]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hello,

I have exported the model in tensorrt format using the below line:

```
# load yolo model
model_path = "best.pt"
model = YOLO(model_path) 
# export
success = model.export(format='engine', device='0', half=True, imgsz=768)
```
It generates best.engine model file

```
# later for prediction:
model = YOLO("best.engine")
model.predict(my_image.jpg)  # my_image.jpg --> (768,768,3)
```

I am getting the below error:
`AssertionError: input size torch.Size([1, 3, 640, 640]) not equal to max model size (1, 3, 768, 768)`

Even though I am specifying size during export, it's going back to the default size of yolo models - 640
Does anyone know the possible reason for this or how can I use .engine for specific/dynamic size?

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@its-jd `model.predict(imgsz=768)`

**Comment by its-jd** [comment]
Thanks a lot, that worked!

Is there a way to allow dynamic image size... or it must be fixed for TensorRT export?
>>  I tried dynamic=True in export but it fails in the export step...

**Comment by glenn-jocher** [comment]
@its-jd yes, you can pass `dynamic=True` when exporting to TensorRT. Then your exported model will accept variable image and batch sizes.

**Comment by its-jd** [comment]
export fails if I specify dynamic=True

I tried dynamic=True 
- Once with imgsz=768 and 
- Once without specifying any imgsz -- Export failed in both cases

### Have a look at the below example:

![image](https://user-images.githubusercontent.com/41875270/225266531-77e06414-567d-4e70-86d6-2548c4ac065d.png)

**Comment by glenn-jocher** [comment]
@its-jd I think half and dynamic are mutually exclusive, you can pick or the other.

**Comment by glenn-jocher** [comment]
<img width="928" alt="Screenshot 2023-03-15 at 13 04 38" src="https://user-images.githubusercontent.com/26833433/225303864-5008906b-028c-4b8d-8191-012d170b8f90.png">

**Comment by glenn-jocher** [comment]
@its-jd well you could try to debug the issue. We've forced dynamic=True to CPU here. You could uncomment and see if you can debug to a solution that works. If you do find one please let us know and submit a PR to help other users!

https://github.com/ultralytics/ultralytics/blob/30fc4b537ff1d9b115bc1558884f6bc2696a282c/ultralytics/yolo/engine/exporter.py#L312-L314

**Comment by blackCmd** [comment]
> 알겠습니다. 설명해 주셔서 감사합니다.
> 
> 우리가 half=True를 사용하지 않으면 TensorRT가 추론 속도를 그다지 높이지 않는다는 것은 잘 알려져 있습니다. 때로는 원래 pytorch 모델보다 훨씬 느립니다.
> 
> 추론 속도를 높이고 동적 이미지 크기를 선택할 수 있는 다른 방법을 추천하시겠습니까?

Exporting a Tensor model with the 'half' parameter has no impact on performance, as it is unrelated.

**Comment by glenn-jocher** [comment]
@blackCmd certainly, I think it's important to understand that when exporting to TensorRT, using the 'half' parameter is independent of dynamic input sizes. If you want to use dynamic input sizes, it may require debugging or finding workarounds as the current implementation in YOLOv8 can be problematic with TensorRT export. It's also important to consider that while TensorRT may not always provide significant speed-ups in inference, there are other ways to optimize performance, such as pruning, quantization, and more powerful hardware.

**Comment by Sachi9soni** [comment]
@glenn-jocher 

same issue i am facing if i use only dynamic export

AssertionError: input size torch.Size([1, 3, 640, 640]) not equal to max model size (1, 3, 1088 1088)

`yolo export model=v8_p2x_2_1080_50.pt format=engine dynamic=True
`

**Comment by glenn-jocher** [comment]
@Sachi9soni hi there! It looks like you're encountering an issue with dynamic export sizes. When using `dynamic=True`, ensure that your inference code dynamically adjusts the input size to match the model's expected input dimensions. For TensorRT with dynamic inputs, you might need to specify the input size explicitly during inference, as the model now supports variable sizes.

Here's a quick example of how you might adjust the input size for inference:

```python
from ultralytics import YOLO

# Load your TensorRT model
model = YOLO('v8_p2x_2_1080_50.engine')

# Adjust the input size to match your model's expected size
model.imgsz = (1088, 1088)  # Update this to your model's size

# Now you can run prediction
results = model.predict('path/to/your/image.jpg')
```

Remember, the key with `dynamic=True` is ensuring that the input size during prediction matches one of the sizes your model was exported to handle. Hope this helps! 😊

**Comment by glenn-jocher** [comment]
Hi @Sachi9soni! It looks like the model is still expecting an input size of 640x640 despite the adjustments. When using a TensorRT model with dynamic input sizes, you should ensure the input images are resized to the expected dimensions before prediction. Here's a quick fix using `PIL` for image resizing:

```python
from PIL import Image
from ultralytics import YOLO

# Load your TensorRT model
model = YOLO("tensorRT/v8_p2x_2_1080_50.engine", task="detect")

# Resize your image to the model's expected size
img_path = "1200-20240213T123328Z-001/1200/1.jpg"
img = Image.open(img_path).resize((1088, 1088))

# Now you can run prediction
results = model(img)
```

This ensures the input image matches the expected size of 1088x1088. Let me know if this helps! 😊
