### ISSUE TITLE
AttributeError: "OBB" object has no attribute "xyxy". See valid attributes below.

### ISSUE THREAD

**Issue by HoanNhi** [ultralytics/ultralytics#14004]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I used Yolov8 OBB detection for detecting the control panel area of washing machines. However, when I tried to convert the attributes results.obb.cpu().numpy(), an error appeared as below:

    Traceback (most recent call last):
      File "/home/thomas/Downloads/community_change_maker_codes_and_exp/merge_two_models.py", line 15, in <module>
        print(result.obb.cpu().numpy())
      File "/home/thomas/.conda/envs/thomas/lib/python3.9/site-packages/ultralytics/utils/__init__.py", line 140, in __str__
        v = getattr(self, a)
      File "/home/thomas/.conda/envs/thomas/lib/python3.9/site-packages/ultralytics/utils/__init__.py", line 157, in __getattr__
        raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
    AttributeError: 'OBB' object has no attribute 'xyxy'. See valid attributes below.

    A class for storing and manipulating Oriented Bounding Boxes (OBB).

    Args:
        boxes (torch.Tensor | numpy.ndarray): A tensor or numpy array containing the detection boxes,
            with shape (num_boxes, 7) or (num_boxes, 8). The last two columns contain confidence and class values.
            If present, the third last column contains track IDs, and the fifth column from the left contains rotation.
        orig_shape (tuple): Original image size, in the format (height, width).

    Attributes:
        xywhr (torch.Tensor | numpy.ndarray): The boxes in [x_center, y_center, width, height, rotation] format.
        conf (torch.Tensor | numpy.ndarray): The confidence values of the boxes.
        cls (torch.Tensor | numpy.ndarray): The class values of the boxes.
        id (torch.Tensor | numpy.ndarray): The track IDs of the boxes (if available).
        xyxyxyxyn (torch.Tensor | numpy.ndarray): The rotated boxes in xyxyxyxy format normalized by orig image size.
        xyxyxyxy (torch.Tensor | numpy.ndarray): The rotated boxes in xyxyxyxy format.
        xyxy (torch.Tensor | numpy.ndarray): The horizontal boxes in xyxyxyxy format.
        data (torch.Tensor): The raw OBB tensor (alias for `boxes`).

    Methods:
        cpu(): Move the object to CPU memory.
        numpy(): Convert the object to a numpy array.
        cuda(): Move the object to CUDA memory.
        to(*args, **kwargs): Move the object to the specified device.

The error does not make sense, as the documentations for OBB result object clearly states that it supports conversion from cuda() to cpu() and to numpy(). 

Also, if I try to convert the results.obb to numpy(), skipping the step cpu(), then it shows an error of not supporting direct conversion to numpy from cuda, which is understandable. 

### Environment

Ultralytics YOLOv8.1.37 🚀 Python-3.9.19 torch-2.2.2+cu121 CUDA:0 (NVIDIA GeForce RTX 3090, 24161MiB)
Setup complete ✅ (56 CPUs, 157.3 GB RAM, 412.6/468.2 GB disk)

OS                  Linux-6.5.0-35-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.9.19
Install             pip
RAM                 157.27 GB
CPU                 Intel Xeon E5-2683 v3 2.00GHz
CUDA                12.1

matplotlib          ✅ 3.8.3>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.2.2>=1.8.0
torchvision         ✅ 0.17.2>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.1.4>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Minimal Reproducible Example

```
from ultralytics import YOLO
from copy import deepcopy
import cv2
import numpy as np

panel_detection = YOLO('cover_whole_control/train4/weights/best.pt')
result_panel = panel_detection.predict('washing_machine_l1309.mp4', device = [0,1])

for result in result_panel:
    print(result.obb.cpu().numpy())
```

### Additional

Here is the data, as well as the weight of the model:
[Data](https://drive.google.com/file/d/1PbT5x8k2BhEuDLyaSi0C2df5DNfdlldn/view?usp=sharing)
[Model](https://drive.google.com/file/d/17oKQLIM3PO7vNnSe4Irs5DhJdT-C56pf/view?usp=sharing)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@HoanNhi hi there,

Thank you for reaching out and providing detailed information about the issue you're encountering. It looks like you're running into an `AttributeError` when trying to convert the `results.obb` to a numpy array. Let's address this step-by-step.

Firstly, it's important to ensure that you are using the latest version of the Ultralytics YOLOv8 package. If you haven't already, please update to the latest version to ensure that any recent bug fixes or improvements are included:
```bash
pip install --upgrade ultralytics
```

Regarding the error, the `OBB` class indeed supports conversion to CPU and numpy, but it seems there might be a misunderstanding about the attributes. The `OBB` class does not have a direct `xyxy` attribute. Instead, it has `xywhr`, `xyxyxyxy`, and `xyxyxyxyn` attributes for different bounding box formats.

Here's a revised version of your code that should work correctly:

```python
from ultralytics import YOLO

# Load the model
panel_detection = YOLO('cover_whole_control/train4/weights/best.pt')

# Run prediction
result_panel = panel_detection.predict('washing_machine_l1309.mp4', device=[0, 1])

# Process results
for result in result_panel:
    obb_cpu = result.obb.cpu()  # Move to CPU
    obb_numpy = obb_cpu.xyxyxyxy.numpy()  # Convert to numpy array
    print(obb_numpy)
```

In this example, `xyxyxyxy` is used to get the oriented bounding boxes in the correct format. If you need a different format, you can replace `xyxyxyxy` with `xywhr` or `xyxyxyxyn` as needed.

If the issue persists, please provide a minimal reproducible example and ensure that the provided links to data and model are accessible. This will help us diagnose the problem more effectively. You can find more information on creating a minimal reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Thank you for your cooperation, and I hope this helps resolve your issue! If you have any further questions, feel free to ask.

**Comment by glenn-jocher** [comment]
@Laughing-q I can reproduce locally with:

```
from ultralytics import YOLO

model = YOLO('yolov8n-obb.pt')
results = model.predict()

for result in results[0]:
    print(result.obb.cpu().numpy())
```

**Comment by glenn-jocher** [comment]
Base error message is

```
Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3614, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-611e931f851f>", line 7, in <module>
    print(result.obb.cpu().numpy())
  File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/utils/__init__.py", line 145, in __str__
    v = getattr(self, a)
        ^^^^^^^^^^^^^^^^
  File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/engine/results.py", line 746, in xyxy
    x1 = self.xyxyxyxy[..., 0].min(1).values
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'numpy.ndarray' object has no attribute 'values'
```

**Comment by Laughing-q** [comment]
@glenn-jocher strange..I do remember I tested the implementation and specially tested `.values` for numpy and it worked properly to me. oh I guess it's probably related to the version of numpy, the version I used to test(which I don't remember the exact version) worked for the implementation.

**Comment by HoanNhi** [comment]
> @Laughing-q I can reproduce locally with:
> 
> ```python
> from ultralytics import YOLO
> 
> model = YOLO('yolov8n-obb.pt')
> results = model.predict()
> 
> for result in results[0]:
>     print(result.obb.cpu().numpy())
> ```



> Base error message is
> 
> ```
> Traceback (most recent call last):
>   File "/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3614, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-2-611e931f851f>", line 7, in <module>
>     print(result.obb.cpu().numpy())
>   File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/utils/__init__.py", line 145, in __str__
>     v = getattr(self, a)
>         ^^^^^^^^^^^^^^^^
>   File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/engine/results.py", line 746, in xyxy
>     x1 = self.xyxyxyxy[..., 0].min(1).values
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'numpy.ndarray' object has no attribute 'values'
> ```

This is also strange to me. I did not encounter this issue also. The code stopped at somewhere around the line 
`v = getattr(self, a)
`
in my case. 

I have not yet found the reason for this, but a temporary work around I am using at the moment is to manually convert all attributes of OBB objects into a numpy array and then work on that array. Specifically:
```python
x, y, w, h, r = obj.xywhr.cpu().numpy()[0]
conf = obj.conf.cpu().numpy()[0]
cls = obj.cls.cpu().numpy()[0]
result_obb_ac = np.array([x, y, w, h, r, conf, cls])
```
In my case, the usage of the numpy array is to update the OBB of the results after inference, i.e. 
```python
result.update(obb=result_obb_ac) #Update the result, keeping the one with the most texts
```
