### ISSUE TITLE
Libraries misalignment in ultralytics and super_gradients required for model YOLO-NAS

### ISSUE THREAD

**Issue by VelDia** [ultralytics/ultralytics#14016]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Install

### Bug

I was trying to use ultralytics for uploading NAS (yolo_nas_l.pt) model in my code and it required to install super_gradients. When I attempted to install super_gradients I run into this issue (see the screenshot). 

"ultralytics 8.2.42 requires numpy<2.0.0,>=1.23.5, but you have numpy 1.23.0 which is incompatible"

<img width="821" alt="Screenshot 2024-06-26 at 11 32 23 AM" src="https://github.com/ultralytics/ultralytics/assets/68444337/037eaf00-4ee3-4128-8f67-2fb2ed918454">

I have also uninstalled both libraries and installed them in a different order, but run into similar error (see the screenshot).

"super-gradients 3.7.1 requires numpy<=1.23, but you have numpy 1.26.4 which is incompatible."

<img width="820" alt="Screenshot 2024-06-26 at 11 37 50 AM" src="https://github.com/ultralytics/ultralytics/assets/68444337/c9408012-dbde-4ea5-b581-02ebc78b2ea6">

It seems like there is a misalignment in libraries requirements between the two, even though module super_gradients is required in ultralytics/models/nas/model.py

Correct me if I am doing something wrong. Also, if you could recommend me the version of ultralytics that doesn't have such a high requirement for numpy, I would appreciate it. Thank you for reviewing!

### Environment

Ultralytics YOLOv8.2.44 🚀 Python-3.9.6 torch-2.3.1 CPU (Apple M3)
Setup complete ✅ (8 CPUs, 16.0 GB RAM, 156.3/926.4 GB disk)

### Minimal Reproducible Example

from ultralytics import NAS
model = NAS("yolo_nas_l.pt")

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by VelDia** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.
> 
> ### YOLOv8 Component
> Install
> 
> ### Bug
> I was trying to use ultralytics for uploading NAS (yolo_nas_l.pt) model in my code and it required to install super_gradients. When I attempted to install super_gradients I run into this issue (see the screenshot).
> 
> "ultralytics 8.2.42 requires numpy<2.0.0,>=1.23.5, but you have numpy 1.23.0 which is incompatible"
> 
> <img alt="Screenshot 2024-06-26 at 11 32 23 AM" width="821" src="https://private-user-images.githubusercontent.com/68444337/343227456-037eaf00-4ee3-4128-8f67-2fb2ed918454.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MTgxMzMsIm5iZiI6MTcxOTQxNzgzMywicGF0aCI6Ii82ODQ0NDMzNy8zNDMyMjc0NTYtMDM3ZWFmMDAtNGVlMy00MTI4LThmNjctMmZiMmVkOTE4NDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDE2MDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyYjVkMWQyNDA1YjBhYWZkYzdiYzM3MzBiOTNlYjA2M2IxM2VjNGYxZTljYTRkNmY5ZDc3MDYwOTRhODRkNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZwymRPL9hpeoO6LTruzJK8GUb5QRsFeEl04sHV7XZvo">
> I have also uninstalled both libraries and installed them in a different order, but run into similar error (see the screenshot).
> 
> "super-gradients 3.7.1 requires numpy<=1.23, but you have numpy 1.26.4 which is incompatible."
> 
> <img alt="Screenshot 2024-06-26 at 11 37 50 AM" width="820" src="https://private-user-images.githubusercontent.com/68444337/343229409-c9408012-dbde-4ea5-b581-02ebc78b2ea6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MTgxMzMsIm5iZiI6MTcxOTQxNzgzMywicGF0aCI6Ii82ODQ0NDMzNy8zNDMyMjk0MDktYzk0MDgwMTItZGJkZS00ZWE1LWI1ODEtMDJlYmM3OGIyZWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDE2MDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNzUwMGJjZTU4NTg4NzU4Yzg5NTU1N2QzZjE0NTY1OWYxODI0Y2M0MjJkN2JmMDQxYmI4YjVhM2FlNzNjODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4RIibeQO3B1V-HRM2f7cYxpsT___DHTvN9CPVLjKaMo">
> It seems like there is a misalignment in libraries requirements between the two, even though module super_gradients is required in ultralytics/models/nas/model.py
> 
> Correct me if I am doing something wrong. Also, if you could recommend me the version of ultralytics that doesn't have such a high requirement for numpy, I would appreciate it. Thank you for reviewing!
> 
> ### Environment
> Ultralytics YOLOv8.2.44 🚀 Python-3.9.6 torch-2.3.1 CPU (Apple M3) Setup complete ✅ (8 CPUs, 16.0 GB RAM, 156.3/926.4 GB disk)
> 
> ### Minimal Reproducible Example
> from ultralytics import NAS model = NAS("yolo_nas_l.pt")
> 
> ### Additional
> _No response_
> 
> ### Are you willing to submit a PR?
> * [ ]  Yes I'd like to help by submitting a PR!

I figured the list of libraries that I have installed might be helpful, find file "list_libs.txt" enclosed.
[list_libs.txt](https://github.com/user-attachments/files/15991985/list_libs.txt)

**Comment by glenn-jocher** [comment]
@VelDia got it. I think we can stretch the lower bound down to accommodate this dependency. I'll open a PR.

**Comment by VelDia** [comment]
> @VelDia got it. I think we can stretch the lower bound down to accommodate this dependency. I'll open a PR.

Thank you a lot!!! Have a good day!

**Comment by glenn-jocher** [comment]
You're welcome, @VelDia! We're glad to help. 😊

In the meantime, please ensure that you are using the latest versions of both the Ultralytics and SuperGradients packages. This can often resolve compatibility issues. If you encounter any further issues or have additional questions, feel free to reach out.

Have a great day! 🚀

**Comment by VelDia** [comment]
Thank you for the recommendation! 
After posting I did _pip install --upgrade_ of both libraries, though it did not solve an issue. 
Now I am waiting for your merge to be accepted, thank you again for your help!

**Comment by glenn-jocher** [comment]
Hi @VelDia,

Thank you for your patience and for upgrading both libraries. It's great to hear that you're keeping your environment up-to-date. 

In the meantime, if you encounter any further issues or have additional questions, please don't hesitate to reach out. We're here to help! 😊
