### ISSUE TITLE
How to train my own model for multi-target tracking with yolo-8?

### ISSUE THREAD

**Issue by wynshiter** [ultralytics/ultralytics#1402]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

If I label a new category lets say object-1, use yolov8n as base model
get yolov8n-own.pt
can I track multiple targets use the following code?

```python
from ultralytics import YOLO

#Load a model
model_path = r'D:\code\python\yolov8\yolov8n-own.pt'
model = YOLO(model_path)  # load an official detection model


# Track with the model
results = model.track(source="0", show=True)
```

did not find the train own model detail in 
[https://docs.ultralytics.com/modes/track/](https://docs.ultralytics.com/modes/track/)

any one can help? many thanks

**Comment by glenn-jocher** [comment]
@wynshiter yes your usage example is correct. Tracking can be performed on any detect or segment model. No extra training is required. For a webcam demo just run `yolo track source=0 show`
