### ISSUE TITLE
How to use YOLOv8 model trained on my custom dataset?

### ISSUE THREAD

**Issue by Burhan-Ahmed** [ultralytics/ultralytics#14023]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

## Hello, Below is my code and I was trying to use my trained model(Trash mode for Plastic, Paper and Metal) for testing purposes but it still makes predictions using its default dataset instead of my trash detection dataset.

from ultralytics import YOLO

print("Initializing YOLO model...")
model = YOLO('Trashmodel.pt')

video_path = './assets/videos/paper.mp4' 
results=model(source=video_path,show=True,conf=0.3,save=True)

**Comment by glenn-jocher** [comment]
Hello,

Thank you for reaching out! It looks like you're on the right track with your code. To ensure that your custom-trained YOLOv8 model is used correctly for predictions, please verify the following steps:

1. **Model Loading**: Ensure that `Trashmodel.pt` is indeed the model trained on your custom dataset. You can do this by checking the training logs or the model metadata.

2. **Prediction Code**: Your current code should work as expected, but let's make sure the model is correctly loaded and used for predictions. Here’s a refined version of your code:

    ```python
    from ultralytics import YOLO

    # Initialize the YOLO model with your custom-trained weights
    print("Initializing YOLO model...")
    model = YOLO('Trashmodel.pt')

    # Define the path to your video
    video_path = './assets/videos/paper.mp4'

    # Run predictions on the video
    results = model.predict(source=video_path, show=True, conf=0.3, save=True)

    # Optionally, print results for debugging
    for result in results:
        print(result)
    ```

3. **Check Model Metadata**: Ensure that the model file `Trashmodel.pt` contains the correct class names (Plastic, Paper, Metal). You can inspect the model’s metadata using:

    ```python
    print(model.names)
    ```

4. **Verify Predictions**: If the model still seems to predict using the default dataset, double-check that the correct model file is being loaded and that there are no issues with the file path.

5. **Latest Version**: Make sure you are using the latest version of the Ultralytics package. You can update it using:
    ```bash
    pip install --upgrade ultralytics
    ```

If the issue persists, please provide a minimum reproducible example as outlined in our [documentation](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us diagnose the problem more effectively.

Feel free to reach out if you have any further questions. Happy coding! 😊

**Comment by Burhan-Ahmed** [comment]
## Thanks Mate...
My Bad that i was suing the wrong file.. i was directly using the saved model. however, I was supposed to use the best.pt from the runs folder.
Now, it works fine..
