### ISSUE TITLE
YoloV8-OBB Onnx-Simplifier Error

### ISSUE THREAD

**Issue by SwEngine** [ultralytics/ultralytics#14030]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

While converting yolov8-obb.pt to onnx file with simplifying argument, I got the error below. What can be the problem? 

ONNX: simplifier failure: FLOAT8E4M3FN

**Comment by glenn-jocher** [comment]
@SwEngine hi there,

Thank you for reaching out and providing details about the issue you're encountering with the ONNX simplifier. The error message `FLOAT8E4M3FN` suggests that there might be an issue with the data type conversion during the simplification process.

To help us better understand and resolve the issue, could you please provide a minimum reproducible example? This will allow us to replicate the problem on our end and investigate further. You can find guidelines on how to create a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of all relevant packages, including the Ultralytics YOLO repository and the ONNX simplifier. Sometimes, issues like these are resolved in newer releases.

Here's a basic example of how you might attempt the conversion:

```python
from ultralytics import YOLO

# Load the model
model = YOLO("yolov8-obb.pt")

# Export the model to ONNX with simplification
model.export(format="onnx", simplify=True)
```

If the issue persists after updating and providing a reproducible example, we can delve deeper into potential solutions.

Thank you for your cooperation and patience! 😊

**Comment by Nash973** [comment]
I'm having the same problem right now.

**Comment by SwEngine** [comment]
@glenn-jocher your answer is not helpful

**Comment by inisis** [comment]
@Nash973 @SwEngine I will check it

**Comment by inisis** [comment]
I'm using follwoing code, and can not reproduce your error
```
wget https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8n-obb.pt

from ultralytics import YOLO

model = YOLO("yolov8n-obb.pt")
model.export(format="onnx", simplify=True)
```

```
Ultralytics YOLOv8.2.45 🚀 Python-3.10.14 torch-2.2.1+cu121 CPU (Intel Xeon Platinum 8352V 2.10GHz)
YOLOv8n-obb summary (fused): 187 layers, 3080144 parameters, 0 gradients, 8.3 GFLOPs

PyTorch: starting from 'yolov8n-obb.pt' with input shape (1, 3, 1024, 1024) BCHW and output shape(s) (1, 20, 21504) (6.2 MB)

ONNX: starting export with onnx 1.16.0 opset 17...
ONNX: slimming with onnxslim 0.1.31...
ONNX: export success ✅ 2.2s, saved as 'yolov8n-obb.onnx' (12.1 MB)

Export complete (5.1s)
Results saved to /root
Predict:         yolo predict task=obb model=yolov8n-obb.onnx imgsz=1024  
Validate:        yolo val task=obb model=yolov8n-obb.onnx imgsz=1024 data=runs/DOTAv1.0-ms.yaml  
Visualize:       https://netron.app
```

Can you provide your code @Nash973 @SwEngine

**Comment by SwEngine** [comment]
When I upgraded onnx version from 1.13.1 to 1.16.1, the problem is gone. Thanks!

**Comment by glenn-jocher** [comment]
Hi @SwEngine,

Thank you for the update! I'm glad to hear that upgrading ONNX to version 1.16.1 resolved the issue. Keeping dependencies up-to-date is crucial for avoiding compatibility problems and benefiting from the latest features and bug fixes.

If you encounter any other issues or have further questions, feel free to reach out. Happy coding! 😊

**Comment by Nash973** [comment]
> When I upgraded onnx version from 1.13.1 to 1.16.1, the problem is gone. Thanks!

wow，me too！it works，Thanks! I upgraded onnx version from 1.13.1 to 1.15.1

**Comment by glenn-jocher** [comment]
Hi @Nash973 and @Nash973,

That's fantastic to hear! 🎉 Upgrading to the latest versions often resolves compatibility issues and brings in new improvements. If you encounter any more questions or need further assistance, feel free to reach out. We're here to help!

Happy coding and best of luck with your projects! 😊

**Comment by DWendou** [comment]
> I'm using follwoing code, and can not reproduce your error
> 
> ```
> wget https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8n-obb.pt
> 
> from ultralytics import YOLO
> 
> model = YOLO("yolov8n-obb.pt")
> model.export(format="onnx", simplify=True)
> ```
> 
> ```
> Ultralytics YOLOv8.2.45 🚀 Python-3.10.14 torch-2.2.1+cu121 CPU (Intel Xeon Platinum 8352V 2.10GHz)
> YOLOv8n-obb summary (fused): 187 layers, 3080144 parameters, 0 gradients, 8.3 GFLOPs
> 
> PyTorch: starting from 'yolov8n-obb.pt' with input shape (1, 3, 1024, 1024) BCHW and output shape(s) (1, 20, 21504) (6.2 MB)
> 
> ONNX: starting export with onnx 1.16.0 opset 17...
> ONNX: slimming with onnxslim 0.1.31...
> ONNX: export success ✅ 2.2s, saved as 'yolov8n-obb.onnx' (12.1 MB)
> 
> Export complete (5.1s)
> Results saved to /root
> Predict:         yolo predict task=obb model=yolov8n-obb.onnx imgsz=1024  
> Validate:        yolo val task=obb model=yolov8n-obb.onnx imgsz=1024 data=runs/DOTAv1.0-ms.yaml  
> Visualize:       https://netron.app
> ```
> 
> Can you provide your code @Nash973 @SwEngine

I have a question, why did the weight change from 6M to 12M? Will this change affect the speed of model inference？

**Comment by inisis** [comment]
This is not related to onnxslim, if you set simplify=False, the exported onnx model is sitll 12MB.

**Comment by glenn-jocher** [comment]
Hi @inisis,

Great observation! The increase in model size from 6MB to 12MB during the ONNX export process is indeed intriguing. This size change can be attributed to several factors, including the inclusion of additional metadata, optimizations, or changes in the way the model's weights and architecture are stored in the ONNX format.

Regarding the impact on inference speed, the size of the model file itself doesn't necessarily correlate directly with inference speed. The performance can be influenced by various factors such as:
- **Model Architecture**: The complexity and depth of the model layers.
- **Hardware**: The capabilities of the GPU or CPU being used for inference.
- **Optimizations**: Specific optimizations applied during the export process, such as quantization or graph simplification.

To ensure optimal performance, you might want to run some benchmarks comparing the inference times of the original PyTorch model and the exported ONNX model. This will give you a clearer picture of any performance differences.

If you have any further questions or need additional assistance, feel free to ask. We're here to help! 😊

**Comment by DWendou** [comment]
> Hi @inisis,
> 
> Great observation! The increase in model size from 6MB to 12MB during the ONNX export process is indeed intriguing. This size change can be attributed to several factors, including the inclusion of additional metadata, optimizations, or changes in the way the model's weights and architecture are stored in the ONNX format.
> 
> Regarding the impact on inference speed, the size of the model file itself doesn't necessarily correlate directly with inference speed. The performance can be influenced by various factors such as:
> 
> * **Model Architecture**: The complexity and depth of the model layers.
> * **Hardware**: The capabilities of the GPU or CPU being used for inference.
> * **Optimizations**: Specific optimizations applied during the export process, such as quantization or graph simplification.
> 
> To ensure optimal performance, you might want to run some benchmarks comparing the inference times of the original PyTorch model and the exported ONNX model. This will give you a clearer picture of any performance differences.
> 
> If you have any further questions or need additional assistance, feel free to ask. We're here to help! 😊

Thank you for your reply. I just read the configuration file of train.py, there is a parameter amp default value is true, mixed precision is not supported in the conversion to onnx, it will be directly converted to fp32, I guess this reason led to the weight from 6MB to 12MB. As for whether it has an effect on the model reasoning speed, I will also test it.
