### ISSUE TITLE
YOLOv8 - Unexpected Behavior When Training with Custom Dataset

### ISSUE THREAD

**Issue by nidhin7100** [ultralytics/ultralytics#14033]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm experiencing an issue where the YOLOv8 model fails to detect objects correctly when trained on my custom dataset(top door of fridge and bottom door of fridge). The training process completes without errors, but the detection accuracy is very low when tested with an unseen dataset manually.

I have used around 3000 images in my dataset and split it with 80% for training, 10% for testing, and 10% for validation. Despite this, the model's detection performance on new, unseen images is poor.

### Additional

The below if my data.yaml folder
path: /home/gpu/Annotation/door/Train_Test_Folder
train: train/images 
test: test/images
val: val/images

nc: 2
names: ['top door open', 'bottom door open']

This is the command i have given for starting the training:
 yolo detect train data=data.yaml model=yolov8m.yaml pretrained=yolov8m.pt imgsz=640 batch=16 epochs=500 hsv_h=0.015 hsv_s=0.7 hsv_v=0.4 degrees=0.4 translate=0.3 scale=0.5 shear=0.01 flipud=0.3 fliplr=0.5 mosaic=1

Please do let me know what might be the issue. Your assistance is very highly appreciated.

**Comment by glenn-jocher** [comment]
@nidhin7100 hi there,

Thank you for reaching out and providing detailed information about your issue. Let's work together to improve your model's performance.

### Steps to Troubleshoot

1. **Verify Dataset Quality**:
   - Ensure that your annotations are accurate and consistent. Mislabeling or inconsistent labeling can significantly impact model performance.
   - Check for class imbalance. If one class is underrepresented, consider augmenting your dataset to balance it.

2. **Hyperparameter Tuning**:
   - While your current hyperparameters seem reasonable, sometimes fine-tuning them can lead to better performance. For instance, you might want to experiment with different learning rates, batch sizes, or augmentation parameters.

3. **Model Validation**:
   - Ensure that the validation process is correctly set up. Use the validation dataset to monitor the model's performance during training and adjust accordingly.

4. **Check for Overfitting**:
   - Given that you have 500 epochs, it's possible that the model might be overfitting. Monitor the training and validation loss curves. If the validation loss starts increasing while the training loss decreases, consider implementing early stopping or reducing the number of epochs.

### Example Code for Monitoring Training

Here's an example of how you can monitor training and validation metrics using TensorBoard:

```python
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8m.yaml').load('yolov8m.pt')

# Train the model with TensorBoard logging
results = model.train(data='data.yaml', epochs=500, imgsz=640, batch=16, 
                      hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.4, 
                      translate=0.3, scale=0.5, shear=0.01, flipud=0.3, 
                      fliplr=0.5, mosaic=1, project='runs/train', name='exp', 
                      exist_ok=True, tensorboard=True)
```

### Reproducible Example

If the issue persists, it would be highly beneficial to provide a minimum reproducible example. This helps us diagnose the problem more effectively. You can find guidance on creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

### Update to Latest Versions

Lastly, ensure that you are using the latest versions of all relevant packages. Sometimes, issues are resolved in newer releases.

Feel free to share any additional insights or observations you might have. We're here to help! 😊

**Comment by nidhin7100** [comment]
> @nidhin7100 hi there,
> 
> Thank you for reaching out and providing detailed information about your issue. Let's work together to improve your model's performance.
> 
> ### Steps to Troubleshoot
> 1. **Verify Dataset Quality**:
>    
>    * Ensure that your annotations are accurate and consistent. Mislabeling or inconsistent labeling can significantly impact model performance.
>    * Check for class imbalance. If one class is underrepresented, consider augmenting your dataset to balance it.
> 2. **Hyperparameter Tuning**:
>    
>    * While your current hyperparameters seem reasonable, sometimes fine-tuning them can lead to better performance. For instance, you might want to experiment with different learning rates, batch sizes, or augmentation parameters.
> 3. **Model Validation**:
>    
>    * Ensure that the validation process is correctly set up. Use the validation dataset to monitor the model's performance during training and adjust accordingly.
> 4. **Check for Overfitting**:
>    
>    * Given that you have 500 epochs, it's possible that the model might be overfitting. Monitor the training and validation loss curves. If the validation loss starts increasing while the training loss decreases, consider implementing early stopping or reducing the number of epochs.
> 
> ### Example Code for Monitoring Training
> Here's an example of how you can monitor training and validation metrics using TensorBoard:
> 
> ```python
> from ultralytics import YOLO
> 
> # Load a model
> model = YOLO('yolov8m.yaml').load('yolov8m.pt')
> 
> # Train the model with TensorBoard logging
> results = model.train(data='data.yaml', epochs=500, imgsz=640, batch=16, 
>                       hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.4, 
>                       translate=0.3, scale=0.5, shear=0.01, flipud=0.3, 
>                       fliplr=0.5, mosaic=1, project='runs/train', name='exp', 
>                       exist_ok=True, tensorboard=True)
> ```
> 
> ### Reproducible Example
> If the issue persists, it would be highly beneficial to provide a minimum reproducible example. This helps us diagnose the problem more effectively. You can find guidance on creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> ### Update to Latest Versions
> Lastly, ensure that you are using the latest versions of all relevant packages. Sometimes, issues are resolved in newer releases.
> 
> Feel free to share any additional insights or observations you might have. We're here to help! 😊

Thank you so much for the response. I will try these technique and get back to you. :)

**Comment by glenn-jocher** [comment]
You're welcome, @nidhin7100! 😊

I'm glad to hear that you're going to try out the suggestions. If you encounter any further issues or have additional questions, please don't hesitate to reach out. Providing a minimum reproducible example, as mentioned earlier, will be very helpful if the problem persists.

Also, make sure to keep your packages up-to-date to benefit from the latest improvements and bug fixes.

Looking forward to hearing about your progress! 🚀

**Comment by nidhin7100** [comment]
Hi @glenn-jocher , i have one more doubt. If i'm using the above tensor flow board that you suggested, Am i able to see or confirm whether the images that I've provide for training are flipping, rotated ,i.e whether the are augmented or not while performing the training?

**Comment by glenn-jocher** [comment]
Hi @nidhin7100,

Great question! Yes, TensorBoard can indeed help you visualize the data augmentation applied during training. To confirm that your images are being augmented (flipped, rotated, etc.), you can log the augmented images to TensorBoard. Here’s how you can do it:

### Example Code to Log Augmented Images

You can modify your training script to include a callback that logs augmented images to TensorBoard:

```python
from ultralytics import YOLO
from torch.utils.tensorboard import SummaryWriter
import torchvision.transforms as T

# Initialize TensorBoard writer
writer = SummaryWriter('runs/augmented_images')

# Define a custom callback to log augmented images
class LogAugmentedImagesCallback:
    def __init__(self, writer):
        self.writer = writer

    def __call__(self, model):
        # Get a batch of training data
        data_loader = model.train_loader
        images, _ = next(iter(data_loader))

        # Apply augmentations
        transform = T.Compose([
            T.RandomHorizontalFlip(p=0.5),
            T.RandomVerticalFlip(p=0.3),
            T.RandomRotation(degrees=0.4),
            T.RandomAffine(degrees=0.4, translate=(0.3, 0.3), scale=(0.5, 1.5), shear=0.01)
        ])
        augmented_images = transform(images)

        # Log augmented images to TensorBoard
        grid = T.utils.make_grid(augmented_images)
        self.writer.add_image('Augmented Images', grid)

# Load a model
model = YOLO('yolov8m.yaml').load('yolov8m.pt')

# Train the model with the custom callback
log_callback = LogAugmentedImagesCallback(writer)
results = model.train(data='data.yaml', epochs=500, imgsz=640, batch=16, 
                      hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.4, 
                      translate=0.3, scale=0.5, shear=0.01, flipud=0.3, 
                      fliplr=0.5, mosaic=1, project='runs/train', name='exp', 
                      exist_ok=True, tensorboard=True, callbacks=[log_callback])
```

### Steps to View Augmented Images in TensorBoard

1. Run your training script with the above modifications.
2. Open TensorBoard by running `tensorboard --logdir=runs` in your terminal.
3. Navigate to the "Images" tab in TensorBoard to see the logged augmented images.

This should help you verify that the augmentations are being applied correctly during training. If you have any more questions or need further assistance, feel free to ask! 😊

Best of luck with your training!

**Comment by nidhin7100** [comment]
Hi @glenn-jocher , I have a query regarding the use of learning rate in training.
 When specifying parameters such as lr0 = 0.001 and cos_lr = True in my training command, it appears that these settings are being ignored because the optimizer is set to 'auto'. To ensure that the learning rate is applied correctly, should I explicitly choose an optimizer like SGD or Adam instead of leaving it on 'auto'?

**Comment by glenn-jocher** [comment]
Hi @nidhin7100,

Thank you for your questions! Let's address them one by one.

### Learning Rate and Optimizer

When using the `auto` setting for the optimizer, YOLOv8 automatically selects an optimizer based on the model configuration. If you want to ensure that specific learning rate settings like `lr0=0.001` and `cos_lr=True` are applied, you can explicitly choose an optimizer such as SGD or Adam. Here's an example:

```bash
yolo detect train data=data.yaml model=yolov8m.yaml pretrained=yolov8m.pt imgsz=640 batch=16 epochs=500 hsv_h=0.015 hsv_s=0.7 hsv_v=0.4 degrees=0.4 translate=0.3 scale=0.5 shear=0.01 flipud=0.3 fliplr=0.5 optimizer=Adam lr0=0.001 cos_lr=True
```

### Pretrained Argument

Using the `pretrained` argument is indeed a good practice as it allows you to leverage pre-trained weights, which can significantly speed up the training process and improve performance. The `pretrained` argument loads weights from a pre-trained model, while the `model` argument specifies the model architecture.

- **`model`**: Defines the architecture of the model (e.g., `yolov8m.yaml`).
- **`pretrained`**: Loads pre-trained weights into the model. If set to `True`, it uses default pre-trained weights. You can also specify a custom path to pre-trained weights.

In your command, using both `model=yolov8m.yaml` and `pretrained=yolov8m.pt` is correct and beneficial.

If you encounter any further issues or have additional questions, please feel free to ask. Also, ensure you are using the latest versions of the packages to benefit from recent updates and bug fixes.

Best of luck with your training! 🚀

**Comment by nidhin7100** [comment]
Hi @glenn-jocher , I have encountered with one more issue with my new training model. So right now I'm trying to detect person, cap and helmet . So while doing annotation, the number of person is greater than the number of cap's and helmet(because obviously while marking a person wearing helmet/cap, i have to mark helmet/cap along with the and person; and in some cases , there are only person) which leads me to class imbalance. So the accuracy of person is pretty good, but the accuracy of cap and helmet is not. I have tried augmentation techniques as well but still the accuracy of cap and helmet has not improved(because while flipping, scaling or rotating, as i increase the number of cap/helmet, the number of person's are also increasing). Please suggest any solution as to tackle this problem. 
Thanks in advance! :)

**Comment by nidhin7100** [comment]
Hello, I'm starting with a new project, where i want to annotate sitting images . I have given my command line same as above . Also i have performed Data Augmentation, Hyper parameter tuning like reducing learning rate etc but still some of the images (2 out of 6 are ,missed out) while detecting. Please help me to solve this issue.

**Comment by pderrenger** [comment]
Hello,

To address the issue of missed detections, ensure your dataset is well-annotated and balanced. Verify that your training images cover a wide range of scenarios. Additionally, consider increasing the number of training epochs and experimenting with different augmentation techniques. If the problem persists, please check if the issue is reproducible with the latest version of the Ultralytics package. This can often resolve unexpected behavior.

**Comment by nidhin7100** [comment]
Thank you @pderrenger  for the response. I have another doubt, so initially i had 15000 images which had been trained with 750 epochs where i got best.pt and last.pt. To this images, I'm adding again 1000 more null images so approximately how much more epochs should i use?

**Comment by pderrenger** [comment]
Thank you for the detailed information. Given that you are adding 1000 more images to your dataset, you might not need as many epochs as your initial training. A good starting point could be around 100-200 additional epochs, but this can vary based on how well the model is performing during training.

For continuing training from your last checkpoint, you can indeed use the `resume` parameter to ensure the training picks up from where it left off. Your command would look like this:

```bash
yolo detect train data=data.yaml model=last.pt resume=True imgsz=640 batch=16 epochs=150 lr0=0.001 weight_decay=0.0001 cos_lr=True patience=50 hsv_h=0.01 hsv_s=0.5 hsv_v=0.3 degrees=0.2 translate=0.1 scale=0.3 shear=0.01 flipud=0.1 fliplr=0.2
```

This will continue training from the last saved state, preserving the optimizer state and other training parameters. If you encounter any issues, please ensure you are using the latest version of the Ultralytics package.

**Comment by nidhin7100** [comment]
While i gave the above command, i got the following error: Traceback (most recent call last):
  File "/home/officegpu/virtualenv/v8/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/officegpu/virtualenv/v8/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 594, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/officegpu/virtualenv/v8/lib/python3.10/site-packages/ultralytics/engine/model.py", line 657, in train
    self.trainer.train()
  File "/home/officegpu/virtualenv/v8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 213, in train
    self._do_train(world_size)
  File "/home/officegpu/virtualenv/v8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 381, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File "/home/officegpu/virtualenv/v8/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/officegpu/virtualenv/v8/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/officegpu/virtualenv/v8/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 93, in forward
    return self.loss(x, *args, **kwargs)
  File "/home/officegpu/virtualenv/v8/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 275, in loss
    return self.criterion(preds, batch)
  File "/home/officegpu/virtualenv/v8/lib/python3.10/site-packages/ultralytics/utils/loss.py", line 723, in __call__
    one2many = preds["one2many"]
TypeError: list indices must be integers or slices, not str

**Comment by pderrenger** [comment]
Thank you for reporting this issue. It appears to be related to the handling of predictions in the loss function. To help us diagnose the problem, please ensure you are using the latest version of the Ultralytics package. If the issue persists, could you provide more details about your environment and any custom modifications you might have made? This will help us better understand and address the problem.

**Comment by nidhin7100** [comment]
Hi @pderrenger , the problem was rectified once i gave pretrained=last.pt instead of model=last.pt.

**Comment by pderrenger** [comment]
Hi @nidhin7100, glad to hear the issue was resolved by using `pretrained=last.pt` and removing the `resume` command. If you encounter any further issues or need additional assistance, feel free to reach out. Always ensure you're using the latest version of the Ultralytics package for the best performance and bug fixes.

**Comment by glenn-jocher** [comment]
@nidhin7100 yes, you can specify augmentation parameters directly in the CLI during training, and they will be applied to the training images.

**Comment by nidhin7100** [comment]
Alright, Thanks for the reply @glenn-jocher !!

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions, feel free to ask.
