### ISSUE TITLE
KeyError: 5995

### ISSUE THREAD

**Issue by maheshs11** [ultralytics/ultralytics#1403]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

model trained using yolov5 and exported to onnx. while loading with ultralytics YOLO throws error.

ultralytics\yolo\engine\predictor.py", line 191, in stream_inference
    s += self.write_results(i, self.results, (p, im, im0))

\ultralytics\yolo\v8\detect\predict.py", line 62, in write_results
    log_string += f"{n} {self.model.names[int(c)]}{'s' * (n > 1)}, "

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@maheshs11 this repo is not backwards compatible with YOLOv5. You can train a new YOLOv8 model and then repeat your steps and everything will work.
