### ISSUE TITLE
yolov8 resume not working

### ISSUE THREAD

**Issue by Payback80** [ultralytics/ultralytics#1404]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Hello, resume (at least on google colab) is not working, it starts to download the coco dataset and other yolo models

my cli string is this one: 
!yolo  task=detect mode=train epochs=200 data=data_custom_colab.yaml resume=last.pt  imgsz=640 batch=-1 save_period=50  shear=20 perspective=0.0001 flipud=0.1 mixup=0 copy_paste=0.2 

last.pt is in the main directory , i've also tried with absolute path , same results

thanks and bye 

### Environment

google colab gpu 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@Payback80 hi, please try:
```bash
yolo detect train resume model=last.pt  # resume training
```
For more info please refer to our docs [https://docs.ultralytics.com/usage/cli/?h=resume#train](https://docs.ultralytics.com/usage/cli/?h=resume#train) :)

**Comment by alpha-31** [comment]
same issue got by me

**Comment by Payback80** [comment]
got the solution:
yolo detect train resume model=/path_to_file/last.pt data=your_yaml_config

**Comment by fcitil** [comment]
If you are having this issue in colab, in order to use 'resume' argument you need to have existing corresponding 'train' folder in 'runs' folder which includes files of stopped training file such as last.pt, best.pt. Then you can run the command:
yolo detect train resume model=/content/runs/detect/train/weights/last.pt
Otherwise it did not work on my colab.

**Comment by 315386775** [comment]
```
model = YOLO("last.pt")
model.train(resume=True)
```
it works. no need other paramters.

**Comment by ookinim** [comment]
I need help regrading the following:
What about the best.pt? where will the updated file be? or else how can testing and validating be done after resumed training

**Comment by glenn-jocher** [comment]
@ookinim hello,

When using the `resume` argument in YOLOv8, it will load the checkpoint file specified (e.g., `last.pt`) and resume training from that point onwards. The updated weights file, including the changes made during resumed training, will be saved in the same location as the original checkpoint file.

After resuming training, you can still perform testing and validation using the resumed model. You can load the model using the updated weights file (e.g., `last.pt`) and evaluate it on your testing/validation dataset to assess its performance.

Please note that it is important to ensure the training and testing/validation datasets are separate to avoid any data leakage.

If you have any further questions or need additional assistance, feel free to ask.

Best regards,
[Ultralytics Team]

**Comment by Amir-Nassimi** [comment]
> @ookinim hello,
> 
> When using the `resume` argument in YOLOv8, it will load the checkpoint file specified (e.g., `last.pt`) and resume training from that point onwards. The updated weights file, including the changes made during resumed training, will be saved in the same location as the original checkpoint file.
> 
> After resuming training, you can still perform testing and validation using the resumed model. You can load the model using the updated weights file (e.g., `last.pt`) and evaluate it on your testing/validation dataset to assess its performance.
> 
> Please note that it is important to ensure the training and testing/validation datasets are separate to avoid any data leakage.
> 
> If you have any further questions or need additional assistance, feel free to ask.
> 
> Best regards, [Ultralytics Team]

hello @glenn-jocher and many thanks for developing Ultralytics YOLOv8.0.208.
I have found that in the ultralytics/engine/trainer.py you have intentionally initialized the self.resume=False. therefore, even when I tried to set the resume to True, the model wont recognized it.
the question is: should set that to true manually whenever I wanted to resume a training? a detection task.
![Screenshot 2023-11-09 143830](https://github.com/ultralytics/ultralytics/assets/100153039/0007fb50-51d5-4d39-b446-b70594a08711)

**Comment by Laughing-q** [comment]
@Amir-Nassimi I just tested this, and the `self.resume=False` here wouldn't affect anything but only a log printing:
https://github.com/ultralytics/ultralytics/blob/795b95bdcb22d788c1a062b47d1fe871d768c806/ultralytics/engine/trainer.py#L597-L602
@glenn-jocher I see this line was introduced in #6111, probably we should remove this line?

**Comment by Amir-Nassimi** [comment]
> @Amir-Nassimi I just tested this, and the `self.resume=False` here wouldn't affect anything but only log printing:
> https://github.com/ultralytics/ultralytics/blob/795b95bdcb22d788c1a062b47d1fe871d768c806/ultralytics/engine/trainer.py#L597-L602
> @glenn-jocher I see this line was introduced in #6111, probably we should remove this line even it would only affect log printing?

Many thanks for your response on such short notice.

**Comment by glenn-jocher** [comment]
Hello @Amir-Nassimi,

Thank you for your message and for closely inspecting the code in the YOLOv8 repository.

Yes, you are correct that the line `self.resume=False` in the section of the code you mentioned is primarily aimed at logging purposes, setting a default state before the actual value is determined based on the presence of a checkpoint file.

In terms of whether this line should be changed or removed, it is actually part of a larger control flow that ensures the correct logging and state management during the resume process. It is important to have this default state as it helps in various checks and balances in the training flow. Modifying this without fully understanding the implications might lead to unexpected behaviors during the process.

If you encounter any issues with resuming training or any logging discrepancies, please provide specific details about the problem, and we will certainly look into it. Your feedback is invaluable in helping us to continually improve YOLOv8.

Thank you for your contributions to the YOLO community and for your vigilance in ensuring our code quality.

Best wishes,
[Ultralytics Team]

**Comment by jpsaturnino** [comment]
someone has a solution? even if resume=True, still starting from scratch.

So in my case I trained 48/50, and after that, passing resume as argument, "resumes" at 1/50 and creates a new detect folder with my project name + i

im running:
`!yolo train resume=True model=/content/drive/MyDrive/Projects/ultralytics/runs/detect/YOLOv8n502/weights/last.pt `

**Comment by glenn-jocher** [comment]
@jpsaturnino hello,

When using `resume=True`, ensure that the path to your `last.pt` weights file is correct and that the `runs/train` folder structure from the previous session is intact. The training process should continue from the last saved epoch if these conditions are met. If it's creating a new project directory, double-check the paths and structure.

If issues persist, submit an issue on the Ultralytics YOLOv8 GitHub repository with specific details so we can investigate further.
