### ISSUE TITLE
How to make object detected flag or Bool

### ISSUE THREAD

**Issue by cdram09** [ultralytics/ultralytics#1405]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I am trying to use Yolov8 in python to detect an object, and once an object is detected, another function will trigger, so I was wondering how I can set the object being detected as a true false variable or condition, thank you for any assistance anyone can provide

**Comment by glenn-jocher** [comment]
@cdram09 see Docs for inference example and retrieving results: https://docs.ultralytics.com/modes/predict

**Comment by cdram09** [comment]
Thank you for taking the time to respond to the above question, I have looked through the documentation but am still confused on how I would do this.
For example, if I were to detect an object on the COCO dataset, and were using the python code provided, how could I use the object being detected to trigger another function or print statement? 
Is there a way to store it into a variable as object detected is true or false?

**Comment by Laughing-q** [comment]
@cdram09 once you get the result according to our docs then you're able to get the trigger of object being detected by `len(result) > 0`.
len(result) > 0 means there are objects being detected.

**Comment by cdram09** [comment]
That didnt work, but Im going to try and look in the other python files to see if I can trigger it there 
Can someone tell me where the print statements for the ms and detected objects are? 
For object detection I see that the no detect statement is in the predict.py , but I can not find where the milliseconds value comes from

**Comment by Laughing-q** [comment]
@cdram09 
[https://github.com/ultralytics/ultralytics/blob/30fc4b537ff1d9b115bc1558884f6bc2696a282c/ultralytics/yolo/engine/predictor.py#L212-L215](https://github.com/ultralytics/ultralytics/blob/30fc4b537ff1d9b115bc1558884f6bc2696a282c/ultralytics/yolo/engine/predictor.py#L212-L215)
[https://github.com/ultralytics/ultralytics/blob/30fc4b537ff1d9b115bc1558884f6bc2696a282c/ultralytics/yolo/v8/detect/predict.py#L62](https://github.com/ultralytics/ultralytics/blob/30fc4b537ff1d9b115bc1558884f6bc2696a282c/ultralytics/yolo/v8/detect/predict.py#L62)

**Comment by cdram09** [comment]
Thank you very much

**Comment by pderrenger** [comment]
@cdram09 you're welcome! If you have any more questions, feel free to ask. Good luck with your project!

**Comment by glenn-jocher** [comment]
@pderrenger Glad to help! Don't hesitate to reach out if you need further assistance. Happy coding! 🚀
