### ISSUE TITLE
Hub classification custom dataset upload problems

### ISSUE THREAD

**Issue by leeyunjai82** [ultralytics/ultralytics#14067]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Other

### Bug

Ultralytics Hub
 I uploaded the classification dataset,
The class name I distinguished and the actual uploaded class name are different.

Uploaded as a zip file,
data
 - train (none, rock, scissors, paper)
 - val (none, rock, scissors, paper)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by leeyunjai82** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/68631024/d8305fe8-0957-4973-a667-3df225ba663a)

**Comment by glenn-jocher** [comment]
@leeyunjai82 hello,

Thank you for bringing this to our attention. It looks like there might be an issue with the class names in your uploaded classification dataset. To help us diagnose and resolve this issue, could you please provide a minimal reproducible example? This will allow us to better understand the problem and offer a more accurate solution. You can find guidelines on how to create a minimal reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest version of the Ultralytics packages, as updates often include important bug fixes and improvements.

In the meantime, here are a few steps to verify your dataset structure:

1. **Dataset Structure**: Ensure that your dataset follows the correct structure. For example:
    ```
    dataset_name/
    ├── train/
    │   ├── none/
    │   ├── rock/
    │   ├── scissors/
    │   └── paper/
    ├── val/
    │   ├── none/
    │   ├── rock/
    │   ├── scissors/
    │   └── paper/
    └── dataset_name.yaml
    ```

2. **YAML File**: Make sure your `dataset_name.yaml` file correctly references the paths and class names. For example:
    ```yaml
    path: ../datasets/dataset_name
    train: images/train
    val: images/val
    names:
      0: none
      1: rock
      2: scissors
      3: paper
    ```

3. **Validation**: Use the `check_dataset` function to validate your dataset before uploading:
    ```python
    from ultralytics.hub import check_dataset

    check_dataset("path/to/dataset.zip", task="classify")
    ```

If the issue persists after these checks, please share the details, and we'll be happy to assist further.
