### ISSUE TITLE
Read data in sequence

### ISSUE THREAD

**Issue by Linengyao** [ultralytics/ultralytics#14078]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i want to val pictures one by one. so i write like this:
```
    # Validate the model
    metrics = model.val(data='D:/F/VScodeProject/YOLOv8/ultralytics/my_val_dataset.yaml',batch=1)  # no arguments needed, dataset and settings remembered

    metrics.box.map  # map50-95
    metrics.box.map50  # map50
    metrics.box.map75  # map75
    metrics.box.maps  # a list contains map50-95 of each category
```

and i found dataloader in ultralytics\models\yolo\detect\val.py:
```
    def get_dataloader(self, dataset_path, batch_size):
        """Construct and return dataloader."""
        dataset = self.build_dataset(dataset_path, batch=batch_size, mode="val")
        return build_dataloader(dataset, batch_size, self.args.workers, shuffle=False, rank=-1)  # return dataloader
```
it already set shuffle=False,But I found that the images are still not loaded in order.
in ultralytics\engine\validator.py function  :
```
def __call__(self, trainer=None, model=None)
.....
        for batch_i, batch in enumerate(bar):
            self.run_callbacks("on_val_batch_start")
```
when i debug this sentence.
when batch_i=0, batch['im_file'] = 00000.jpg
when batch_i=1, batch['im_file'] = 00202.jpg
when batch_i=2, batch['im_file'] = 00201.jpg
it is not in order,why?
what should i do ,so he can run like this:
when batch_i=0, batch['im_file'] = 00000.jpg
when batch_i=1, batch['im_file'] = 00001.jpg
when batch_i=2, batch['im_file'] = 00002.jpg

**Comment by glenn-jocher** [comment]
@Linengyao hello,

Thank you for reaching out with your question. It looks like you're trying to validate images in a specific sequential order, but the images are not being processed in the order you expect.

The `shuffle=False` parameter in the dataloader should indeed prevent shuffling, but the order of images might still be affected by other factors such as how the dataset is read or the underlying file system order.

To ensure that your images are processed in the exact order you want, you can sort the dataset explicitly before passing it to the dataloader. Here's a modified version of your code to achieve this:

```python
from ultralytics import YOLO
from ultralytics.data import build_dataloader

# Load the model
model = YOLO('path/to/your/model.pt')

# Define a custom function to sort the dataset
def get_sorted_dataloader(dataset_path, batch_size):
    dataset = model.build_dataset(dataset_path, batch=batch_size, mode="val")
    dataset.img_files.sort()  # Sort the image files
    return build_dataloader(dataset, batch_size, model.args.workers, shuffle=False, rank=-1)

# Use the custom dataloader for validation
dataloader = get_sorted_dataloader('D:/F/VScodeProject/YOLOv8/ultralytics/my_val_dataset.yaml', batch_size=1)
metrics = model.val(dataloader=dataloader)

# Access the metrics
print(metrics.box.map)    # map50-95
print(metrics.box.map50)  # map50
print(metrics.box.map75)  # map75
print(metrics.box.maps)   # a list contains map50-95 of each category
```

This approach ensures that the images are loaded in the sorted order you desire. If the issue persists, please ensure you are using the latest version of the Ultralytics YOLO package, as updates may contain important bug fixes and improvements.

For more detailed guidance on creating a minimum reproducible example, you can refer to our documentation [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

I hope this helps! If you have any further questions, feel free to ask. 😊

**Comment by Linengyao** [comment]
> @Linengyao hello,
> 
> Thank you for reaching out with your question. It looks like you're trying to validate images in a specific sequential order, but the images are not being processed in the order you expect.
> 
> The `shuffle=False` parameter in the dataloader should indeed prevent shuffling, but the order of images might still be affected by other factors such as how the dataset is read or the underlying file system order.
> 
> To ensure that your images are processed in the exact order you want, you can sort the dataset explicitly before passing it to the dataloader. Here's a modified version of your code to achieve this:
> 
> ```python
> from ultralytics import YOLO
> from ultralytics.data import build_dataloader
> 
> # Load the model
> model = YOLO('path/to/your/model.pt')
> 
> # Define a custom function to sort the dataset
> def get_sorted_dataloader(dataset_path, batch_size):
>     dataset = model.build_dataset(dataset_path, batch=batch_size, mode="val")
>     dataset.img_files.sort()  # Sort the image files
>     return build_dataloader(dataset, batch_size, model.args.workers, shuffle=False, rank=-1)
> 
> # Use the custom dataloader for validation
> dataloader = get_sorted_dataloader('D:/F/VScodeProject/YOLOv8/ultralytics/my_val_dataset.yaml', batch_size=1)
> metrics = model.val(dataloader=dataloader)
> 
> # Access the metrics
> print(metrics.box.map)    # map50-95
> print(metrics.box.map50)  # map50
> print(metrics.box.map75)  # map75
> print(metrics.box.maps)   # a list contains map50-95 of each category
> ```
> 
> This approach ensures that the images are loaded in the sorted order you desire. If the issue persists, please ensure you are using the latest version of the Ultralytics YOLO package, as updates may contain important bug fixes and improvements.
> 
> For more detailed guidance on creating a minimum reproducible example, you can refer to our documentation [here](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> I hope this helps! If you have any further questions, feel free to ask. 😊

i did as u suggest but it wrong:

my file:
```
def get_sorted_dataloader(dataset_path, batch_size, model):
    dataset = model.build_dataset(dataset_path, batch=batch_size, mode="val")
    dataset.img_files.sort()  # Sort the image files
    return build_dataloader(dataset, batch_size, model.args.workers, shuffle=False, rank=-1)


if __name__ == '__main__':
    # Load a model
    # model = YOLO("/root/autodl-tmp/Code/ultralytics/yolov8n-my.yaml")  # load an official model
    model = YOLO("D:/F/VScodeProject/YOLOv8/ultralytics/yolov8n-my.yaml").load("D:/F/VScodeProject/YOLOv8/ultralytics/runs/train/exp/weights/best.pt")  # load a custom model

    # Validate the model
    # metrics = model.val(data='D:/F/VScodeProject/YOLOv8/ultralytics/my_val_dataset.yaml',batch=1)  # no arguments needed, dataset and settings remembered
    # Use the custom dataloader for validation
    dataloader = get_sorted_dataloader('D:/F/VScodeProject/YOLOv8/ultralytics/my_val_dataset.yaml', batch_size=1, model=model)
    metrics = model.val(dataloader=dataloader)

    metrics.box.map  # map50-95
    metrics.box.map50  # map50
    metrics.box.map75  # map75
    metrics.box.maps  # a list contains map50-95 of each category
```
but it cant run ,it comes:

Exception has occurred: AttributeError
'YOLO' object has no attribute 'build_dataset'
  File "D:\F\VScodeProject\YOLOv8\ultralytics\val.py", line 5, in get_sorted_dataloader
    dataset = model.build_dataset(dataset_path, batch=batch_size, mode="val")
  File "D:\F\VScodeProject\YOLOv8\ultralytics\val.py", line 18, in <module>
    dataloader = get_sorted_dataloader('D:/F/VScodeProject/YOLOv8/ultralytics/my_val_dataset.yaml', batch_size=1, model=model)
AttributeError: 'YOLO' object has no attribute 'build_dataset'
how can i solve it?

**Comment by glenn-jocher** [comment]
Hi @Linengyao,

Thank you for your detailed follow-up. It seems like the `YOLO` object does not have a `build_dataset` method, which is causing the `AttributeError`. Let's address this by using the appropriate methods provided by the Ultralytics library.

To sort the dataset and ensure images are processed in the desired order, we can directly manipulate the dataset before passing it to the dataloader. Here's an updated approach:

1. **Create a custom dataset class** that sorts the images.
2. **Use this custom dataset** in the dataloader.

Here's how you can do it:

```python
from ultralytics import YOLO
from ultralytics.data import build_dataloader, build_yolo_dataset

# Define a custom function to sort the dataset
def get_sorted_dataloader(dataset_path, batch_size, model):
    # Build the dataset
    dataset = build_yolo_dataset(model.args, dataset_path, batch=batch_size, data=model.data, mode="val", rect=True, stride=32)
    
    # Sort the image files
    dataset.img_files.sort()
    
    # Return the dataloader
    return build_dataloader(dataset, batch_size, model.args.workers, shuffle=False, rank=-1)

if __name__ == '__main__':
    # Load the model
    model = YOLO("D:/F/VScodeProject/YOLOv8/ultralytics/yolov8n-my.yaml").load("D:/F/VScodeProject/YOLOv8/ultralytics/runs/train/exp/weights/best.pt")

    # Use the custom dataloader for validation
    dataloader = get_sorted_dataloader('D:/F/VScodeProject/YOLOv8/ultralytics/my_val_dataset.yaml', batch_size=1, model=model)
    metrics = model.val(dataloader=dataloader)

    # Access the metrics
    print(metrics.box.map)    # map50-95
    print(metrics.box.map50)  # map50
    print(metrics.box.map75)  # map75
    print(metrics.box.maps)   # a list contains map50-95 of each category
```

In this code:
- We use `build_yolo_dataset` to create the dataset.
- We sort the `img_files` attribute of the dataset to ensure the images are processed in the desired order.
- We then pass this sorted dataset to `build_dataloader` to create the dataloader.

This should resolve the issue and ensure your images are processed in the correct order.

If you encounter any further issues, please ensure you are using the latest version of the Ultralytics YOLO package. You can update it using:
```bash
pip install -U ultralytics
```

For more detailed guidance on creating a minimum reproducible example, you can refer to our documentation [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

I hope this helps! If you have any further questions, feel free to ask. 😊

**Comment by Linengyao** [comment]
> Hi @Linengyao,
> 
> Thank you for your detailed follow-up. It seems like the `YOLO` object does not have a `build_dataset` method, which is causing the `AttributeError`. Let's address this by using the appropriate methods provided by the Ultralytics library.
> 
> To sort the dataset and ensure images are processed in the desired order, we can directly manipulate the dataset before passing it to the dataloader. Here's an updated approach:
> 
> 1. **Create a custom dataset class** that sorts the images.
> 2. **Use this custom dataset** in the dataloader.
> 
> Here's how you can do it:
> 
> ```python
> from ultralytics import YOLO
> from ultralytics.data import build_dataloader, build_yolo_dataset
> 
> # Define a custom function to sort the dataset
> def get_sorted_dataloader(dataset_path, batch_size, model):
>     # Build the dataset
>     dataset = build_yolo_dataset(model.args, dataset_path, batch=batch_size, data=model.data, mode="val", rect=True, stride=32)
>     
>     # Sort the image files
>     dataset.img_files.sort()
>     
>     # Return the dataloader
>     return build_dataloader(dataset, batch_size, model.args.workers, shuffle=False, rank=-1)
> 
> if __name__ == '__main__':
>     # Load the model
>     model = YOLO("D:/F/VScodeProject/YOLOv8/ultralytics/yolov8n-my.yaml").load("D:/F/VScodeProject/YOLOv8/ultralytics/runs/train/exp/weights/best.pt")
> 
>     # Use the custom dataloader for validation
>     dataloader = get_sorted_dataloader('D:/F/VScodeProject/YOLOv8/ultralytics/my_val_dataset.yaml', batch_size=1, model=model)
>     metrics = model.val(dataloader=dataloader)
> 
>     # Access the metrics
>     print(metrics.box.map)    # map50-95
>     print(metrics.box.map50)  # map50
>     print(metrics.box.map75)  # map75
>     print(metrics.box.maps)   # a list contains map50-95 of each category
> ```
> 
> In this code:
> 
> * We use `build_yolo_dataset` to create the dataset.
> * We sort the `img_files` attribute of the dataset to ensure the images are processed in the desired order.
> * We then pass this sorted dataset to `build_dataloader` to create the dataloader.
> 
> This should resolve the issue and ensure your images are processed in the correct order.
> 
> If you encounter any further issues, please ensure you are using the latest version of the Ultralytics YOLO package. You can update it using:
> 
> ```shell
> pip install -U ultralytics
> ```
> 
> For more detailed guidance on creating a minimum reproducible example, you can refer to our documentation [here](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> I hope this helps! If you have any further questions, feel free to ask. 😊

i have find why.
cz val will set rect=True as default.and it will use function:
```
    def set_rectangle(self):
        """Sets the shape of bounding boxes for YOLO detections as rectangles."""
        bi = np.floor(np.arange(self.ni) / self.batch_size).astype(int)  # batch index
        nb = bi[-1] + 1  # number of batches

        s = np.array([x.pop("shape") for x in self.labels])  # hw
        ar = s[:, 0] / s[:, 1]  # aspect ratio
        irect = ar.argsort()
        self.im_files = [self.im_files[i] for i in irect]
        self.labels = [self.labels[i] for i in irect]
        ar = ar[irect]

        # Set training image shapes
        shapes = [[1, 1]] * nb
        for i in range(nb):
            ari = ar[bi == i]
            mini, maxi = ari.min(), ari.max()
            if maxi < 1:
                shapes[i] = [maxi, 1]
            elif mini > 1:
                shapes[i] = [1, 1 / mini]

        self.batch_shapes = np.ceil(np.array(shapes) * self.imgsz / self.stride + self.pad).astype(int) * self.stride
        self.batch = bi  # batch index of image
```
        irect = ar.argsort()
        self.im_files = [self.im_files[i] for i in irect] 
        These two sentences will disrupt the order of the pictures. i dont know why rect=True need to disrupt the order of the pictures?

**Comment by Linengyao** [comment]
> > Hi @Linengyao,
> > Thank you for your detailed follow-up. It seems like the `YOLO` object does not have a `build_dataset` method, which is causing the `AttributeError`. Let's address this by using the appropriate methods provided by the Ultralytics library.
> > To sort the dataset and ensure images are processed in the desired order, we can directly manipulate the dataset before passing it to the dataloader. Here's an updated approach:
> > 
> > 1. **Create a custom dataset class** that sorts the images.
> > 2. **Use this custom dataset** in the dataloader.
> > 
> > Here's how you can do it:
> > ```python
> > from ultralytics import YOLO
> > from ultralytics.data import build_dataloader, build_yolo_dataset
> > 
> > # Define a custom function to sort the dataset
> > def get_sorted_dataloader(dataset_path, batch_size, model):
> >     # Build the dataset
> >     dataset = build_yolo_dataset(model.args, dataset_path, batch=batch_size, data=model.data, mode="val", rect=True, stride=32)
> >     
> >     # Sort the image files
> >     dataset.img_files.sort()
> >     
> >     # Return the dataloader
> >     return build_dataloader(dataset, batch_size, model.args.workers, shuffle=False, rank=-1)
> > 
> > if __name__ == '__main__':
> >     # Load the model
> >     model = YOLO("D:/F/VScodeProject/YOLOv8/ultralytics/yolov8n-my.yaml").load("D:/F/VScodeProject/YOLOv8/ultralytics/runs/train/exp/weights/best.pt")
> > 
> >     # Use the custom dataloader for validation
> >     dataloader = get_sorted_dataloader('D:/F/VScodeProject/YOLOv8/ultralytics/my_val_dataset.yaml', batch_size=1, model=model)
> >     metrics = model.val(dataloader=dataloader)
> > 
> >     # Access the metrics
> >     print(metrics.box.map)    # map50-95
> >     print(metrics.box.map50)  # map50
> >     print(metrics.box.map75)  # map75
> >     print(metrics.box.maps)   # a list contains map50-95 of each category
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In this code:
> > 
> > * We use `build_yolo_dataset` to create the dataset.
> > * We sort the `img_files` attribute of the dataset to ensure the images are processed in the desired order.
> > * We then pass this sorted dataset to `build_dataloader` to create the dataloader.
> > 
> > This should resolve the issue and ensure your images are processed in the correct order.
> > If you encounter any further issues, please ensure you are using the latest version of the Ultralytics YOLO package. You can update it using:
> > ```shell
> > pip install -U ultralytics
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For more detailed guidance on creating a minimum reproducible example, you can refer to our documentation [here](https://docs.ultralytics.com/help/minimum_reproducible_example).
> > I hope this helps! If you have any further questions, feel free to ask. 😊
> 
> i have find why. cz val will set rect=True as default.and it will use function:
> 
> ```
>     def set_rectangle(self):
>         """Sets the shape of bounding boxes for YOLO detections as rectangles."""
>         bi = np.floor(np.arange(self.ni) / self.batch_size).astype(int)  # batch index
>         nb = bi[-1] + 1  # number of batches
> 
>         s = np.array([x.pop("shape") for x in self.labels])  # hw
>         ar = s[:, 0] / s[:, 1]  # aspect ratio
>         irect = ar.argsort()
>         self.im_files = [self.im_files[i] for i in irect]
>         self.labels = [self.labels[i] for i in irect]
>         ar = ar[irect]
> 
>         # Set training image shapes
>         shapes = [[1, 1]] * nb
>         for i in range(nb):
>             ari = ar[bi == i]
>             mini, maxi = ari.min(), ari.max()
>             if maxi < 1:
>                 shapes[i] = [maxi, 1]
>             elif mini > 1:
>                 shapes[i] = [1, 1 / mini]
> 
>         self.batch_shapes = np.ceil(np.array(shapes) * self.imgsz / self.stride + self.pad).astype(int) * self.stride
>         self.batch = bi  # batch index of image
> ```
> 
> ```
>     irect = ar.argsort()
>     self.im_files = [self.im_files[i] for i in irect] 
>     These two sentences will disrupt the order of the pictures.
> ```
> 
> i dont know why rect=True need to disrupt the order of the pictures? i already set batch=1.
thats means when i set **batch=1, rect=True**, it will disrupt the order of the pictures.**i think it is wrong,** when batch=1, although rect=true, the order of the pictures should not be disrupted

**Comment by glenn-jocher** [comment]
Hi @Linengyao,

Thank you for your detailed investigation and for pointing out the behavior with `rect=True`. You are correct that the `rect=True` setting is designed to optimize the aspect ratio of images for batch processing, which can inadvertently disrupt the order of images even when `batch=1`.

To ensure that your images are processed in the exact order you want, you can explicitly set `rect=False` when calling the validation function. This will prevent the reordering of images based on their aspect ratios.

Here's how you can modify your code:

```python
from ultralytics import YOLO

if __name__ == '__main__':
    # Load the model
    model = YOLO("D:/F/VScodeProject/YOLOv8/ultralytics/yolov8n-my.yaml").load("D:/F/VScodeProject/YOLOv8/ultralytics/runs/train/exp/weights/best.pt")

    # Validate the model with rect=False to preserve the order of images
    metrics = model.val(data='D:/F/VScodeProject/YOLOv8/ultralytics/my_val_dataset.yaml', batch=1, rect=False)

    # Access the metrics
    print(metrics.box.map)    # map50-95
    print(metrics.box.map50)  # map50
    print(metrics.box.map75)  # map75
    print(metrics.box.maps)   # a list contains map50-95 of each category
```

By setting `rect=False`, the images will be processed in the order they are listed in your dataset, without any reordering based on aspect ratios.

I hope this resolves the issue! If you have any further questions or need additional assistance, feel free to ask. 😊
