### ISSUE TITLE
AttributeError: Can't get attribute 'v10DetectLoss' on <module 'ultralytics.utils.loss'>

### ISSUE THREAD

**Issue by mrortach** [ultralytics/ultralytics#14072]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I encountered an `AttributeError` when trying to load my custom-trained YOLOv10x model. However, there is no issue when loading the pre-trained `yolov10s.pt` model.

### Error Message
plaintext
    result = unpickler.load()
(***_env) PS D:\***\***\***\***> & C:/Users/***/anaconda3/envs/***_env/python.exe d:/***/***/***/***.py
Traceback (most recent call last):
  File "d:\***\***\***\***.py", line 4, in <module>
    model = YOLO("yolov10x.pt")
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***/anaconda3/envs/***_env\Lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Users\***/anaconda3/envs/***_env\Lib\site-packages\ultralytics\engine\model.py", line 149, in __init__
    self._load(model, task=task)
  File "C:\Users\***/anaconda3/envs/***_env\Lib\site-packages\ultralytics\engine\model.py", line 230, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***/anaconda3/envs/***_env\Lib\site-packages\ultralytics\nn\tasks.py", line 855, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***/anaconda3/envs\***_env\Lib\site-packages\ultralytics\nn\tasks.py", line 781, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***/AppData\Roaming\Python\Python312\site-packages\torch\serialization.py", line 1026, in load
    return _load(opened_zipfile,
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***/AppData\Roaming\Python\Python312\site-packages\torch\serialization.py", line 1438, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "C:\Users\***/AppData\Roaming\Python\Python312\site-packages\torch\serialization.py", line 1431, in find_class
    return super().find_class(mod_name, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'v10DetectLoss' on <module 'ultralytics.utils.loss' from 'C:\\Users\\***/anaconda3/envs\\***_env\\Lib\\site-packages\\ultralytics\\utils\\loss.py'>

### Environment Information:

Python version: 3.12
Ultralytics version: 8.2.45
Operating System: Windows

```python
from ultralytics import YOLO

# Load a pre-trained YOLOv10 model
model = YOLO("yolov10x.pt")

# Perform object detection on an image
results = model.track(0, save=True, show=True, conf=0.15)

**Comment by markyang19** [comment]
Hi, everyone
I have encountered similar questions about fail attribute of loss.

Considering appropriate libraries dependency for yolov8 and v10, respectively.

The yolov8 and yolov10 can use the same procedure for assemble custom training data, but different clean environments for training and inference/prediction.

(1) for training yolov8 (eg. yolov8n.pt) 
    pip install  ultralytics==8.1.34 

(2) for training yolov10 (eg. yolov10x.pt)
    pip install ultralytics==8.2.45

(3)   for inferecne prediction of yolov10
(3.1) # create new env, eg. Python 3.9.19
      conda create -p E:\pythonEnv\yolov10 python=3.9   

(3.2) # install compatible ultralytics 
      activate E:\pythonEnv\yolov10
      pip install ultralytics==8.2.83 (pip install ultralytics==8.2.45 ?)

(3.3) # install compatible pytorch for pytorch GPU
      pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

(3.4) in main_inference.py
       from ultralytics import YOLO    # Not use    from ultralytics import YOLOv10
       model = YOLO(model_file_path)   # Not use    model = YOLOv10(model_file_path)

(4) # use this version for Yolov10 model.pt to onnx.pt
     pip install onnx==1.16.1
     yolo export model= ./best.pt format=onnx

Warm Regards,

**Comment by glenn-jocher** [comment]
@markyang19 hi,

Thank you for sharing your insights. To address the attribute error with the loss function, please ensure you're using the latest version of the Ultralytics package. You can update it with:
```bash
pip install --upgrade ultralytics
```
If the issue persists, consider re-training your model with the updated package.

**Comment by KpLBaTMaN** [comment]
I had the same problem trying to get on of the following models working from: https://huggingface.co/omoured/YOLOv10-Document-Layout-Analysis

How I fixed it:

pip uninstall ultralytics

Then I add the following to the requirements and pip install requirements.txt: 
git+https://github.com/THU-MIG/yolov10.git

**Comment by glenn-jocher** [comment]
Thank you for sharing your solution. For others experiencing similar issues, please ensure you're using the latest version of the Ultralytics package. If the problem persists, consider trying the approach you've outlined.
