### ISSUE TITLE
I want to retrain the yolov8m model for my new classes, but when using resume=True an error appears

### ISSUE THREAD

**Issue by bohhuu1337** [ultralytics/ultralytics#14073]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component
Is it possible to remove unnecessary classes from 80 and keep only the ones you need and retrain the model, for example, I want to train the model to recognize people and trams, people are already in the list of classes, but there are no trams, so I want to add a new class and retrain
Train

### Bug

%cd {HOME}

!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs=100 imgsz=640 plots=True batch=8 resume=True
WARNING ⚠️ 'hide_labels' is deprecated and will be removed in 'ultralytics 8.399999999999999' in the future. Please use 'show_labels' instead.
WARNING ⚠️ 'hide_conf' is deprecated and will be removed in 'ultralytics 8.399999999999999' in the future. Please use 'show_conf' instead.
WARNING ⚠️ 'line_thickness' is deprecated and will be removed in 'ultralytics 8.399999999999999' in the future. Please use 'line_width' instead.
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 591, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 650, in train
    self.trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 204, in train
    self._do_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 323, in _do_train
    self._setup_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 293, in _setup_train
    self.validator = self.get_validator()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/detect/train.py", line 96, in get_validator
    return yolo.detect.DetectionValidator(
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/detect/val.py", line 33, in __init__
    super().__init__(dataloader, save_dir, pbar, args, _callbacks)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/validator.py", line 79, in __init__
    self.args = get_cfg(overrides=args)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 220, in get_cfg
    check_dict_alignment(cfg, overrides)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 331, in check_dict_alignment
    raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'image_weights' is not a valid YOLO argument. 
'v5loader' is not a valid YOLO argument. 
'fl_gamma' is not a valid YOLO argument.

### Environment

Ultralytics YOLOv8.2.45 🚀 Python-3.10.12 torch-2.3.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 30.2/78.2 GB disk)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zhixuwei** [comment]
Can you post your configuration file `data.yaml`

**Comment by bohhuu1337** [comment]
> Can you post your configuration file data.yaml
data.yaml
names:
- car
- human
- tram
nc: 3
roboflow:
  license: CC BY 4.0
  project: tram-4nfq3
  url: https://universe.roboflow.com/tram-5ob3b/tram-4nfq3/dataset/15
  version: 15
  workspace: tram-5ob3b
test: ../test/images
train: ../train/images
val: ../valid/images

**Comment by bohhuu1337** [comment]
I did it as described in this link https://docs.ultralytics.com/help/minimum_reproducible_example. The same error comes up. Below is the entire output with error.
ltralytics YOLOv8.2.45 🚀 Python-3.11.2 torch-2.3.1+cu118 CUDA:0 (NVIDIA GeForce GTX 1650, 4096MiB)
engine\trainer: task=detect, mode=train, model=yolov8n.pt, data=C:\Users\damir\OneDrive\Desktop\Damir\andrey\dataset1\coco8.yaml, epochs=500, time=None, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=disk, device=0, workers=8, project=YOLOv8, name=yolov8n2, exist_ok=False, pretrained=False, optimizer=SGD, verbose=False, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=yolov8n.pt, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=False, val=True, split=val, save_json=False, save_hybrid=False, conf=0.001, iou=0.7, max_det=300, half=True, dnn=False, plots=True, source=ultralytics/assets/, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.001, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, image_weights=False, hide_labels=False, hide_conf=False, line_thickness=3, fl_gamma=0.0, v5loader=True, save_dir=YOLOv8\yolov8n2
TensorBoard: Start with 'tensorboard --logdir YOLOv8\yolov8n2', view at http://localhost:6006/

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]           
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]                  
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]                
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]                 
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 22        [15, 18, 21]  1    897664  ultralytics.nn.modules.head.Detect           [80, [64, 128, 256]]          
Model summary: 225 layers, 3157200 parameters, 3157184 gradients, 8.9 GFLOPs

Transferred 355/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning C:\Users\damir\OneDrive\Desktop\Damir\andrey\dataset1\labels\train.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
train: Caching images (0.0GB Disk): 100%|██████████| 4/4 [00:00<00:00, 3997.43it/s]
val: Scanning C:\Users\damir\OneDrive\Desktop\Damir\andrey\dataset1\labels\val.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
val: Caching images (0.0GB Disk): 100%|██████████| 4/4 [00:00<00:00, 3998.38it/s]
WARNING ⚠️ 'hide_labels' is deprecated and will be removed in 'ultralytics 8.399999999999999' in the future. Please use 'show_labels' instead.
WARNING ⚠️ 'hide_conf' is deprecated and will be removed in 'ultralytics 8.399999999999999' in the future. Please use 'show_conf' instead.
WARNING ⚠️ 'line_thickness' is deprecated and will be removed in 'ultralytics 8.399999999999999' in the future. Please use 'line_width' instead.
Traceback (most recent call last):
  File "C:\Users\damir\OneDrive\Desktop\Damir\andrey\Program\yolo.py", line 19, in <module>
    main()
  File "C:\Users\damir\OneDrive\Desktop\Damir\andrey\Program\yolo.py", line 8, in main
    results = model.train(
              ^^^^^^^^^^^^
  File "C:\Users\damir\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 650, in train
    self.trainer.train()
  File "C:\Users\damir\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\trainer.py", line 204, in train
    self._do_train(world_size)
  File "C:\Users\damir\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\trainer.py", line 323, in _do_train
    self._setup_train(world_size)
  File "C:\Users\damir\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\trainer.py", line 293, in _setup_train
    self.validator = self.get_validator()
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\damir\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\models\yolo\detect\train.py", line 96, in get_validator
    return yolo.detect.DetectionValidator(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\damir\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\models\yolo\detect\val.py", line 33, in __init__
    super().__init__(dataloader, save_dir, pbar, args, _callbacks)
  File "C:\Users\damir\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\validator.py", line 79, in __init__
    self.args = get_cfg(overrides=args)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\damir\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\cfg\__init__.py", line 220, in get_cfg
    check_dict_alignment(cfg, overrides)
  File "C:\Users\damir\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\cfg\__init__.py", line 331, in check_dict_alignment
    raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'image_weights' is not a valid YOLO argument. 
'fl_gamma' is not a valid YOLO argument. 
'v5loader' is not a valid YOLO argument.

**Comment by glenn-jocher** [comment]
Thank you for providing the detailed output and your `data.yaml` file. It looks like the issue is related to deprecated or invalid arguments being passed during the training process. Specifically, the arguments `'image_weights'`, `'fl_gamma'`, and `'v5loader'` are not recognized by the current version of the Ultralytics YOLOv8 package.

Here are some steps to resolve the issue:

1. **Update to the Latest Version**: Ensure you are using the latest version of the Ultralytics YOLOv8 package. You can update it using:
   ```bash
   pip install --upgrade ultralytics
   ```

2. **Remove Deprecated Arguments**: Review your training script and remove any deprecated or invalid arguments. Based on the error message, you should remove `'image_weights'`, `'fl_gamma'`, and `'v5loader'`.

3. **Simplify the Training Command**: Start with a minimal training command to ensure the basics are working, and then incrementally add other parameters. For example:
   ```python
   from ultralytics import YOLO

   def main():
       # Load the model
       model = YOLO('yolov8n.pt')

       # Train the model
       results = model.train(
           data='C:\\Users\\damir\\OneDrive\\Desktop\\Damir\\andrey\\dataset1\\coco8.yaml',
           imgsz=640,
           epochs=10,
           name='C:\\Users\\damir\\OneDrive\\Desktop\\Damir\\model',
           resume=True
       )

   if __name__ == '__main__':
       from multiprocessing import freeze_support
       freeze_support()
       main()
   ```

4. **Verify Dataset Paths**: Ensure that the paths specified in your `data.yaml` file are correct and accessible. For example:
   ```yaml
   train: C:\\Users\\damir\\OneDrive\\Desktop\\Damir\\andrey\\dataset1\\images\\train
   val: C:\\Users\\damir\\OneDrive\\Desktop\\Damir\\andrey\\dataset1\\images\\val
   ```

5. **Check for Additional Deprecated Warnings**: Address any additional warnings related to deprecated arguments such as `hide_labels`, `hide_conf`, and `line_thickness`. Replace them with `show_labels`, `show_conf`, and `line_width` respectively.

If the issue persists, please provide a minimal reproducible example as outlined in our [documentation](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us diagnose the problem more effectively.

Feel free to reach out if you have any further questions or need additional assistance. Happy training! 🚀

**Comment by bohhuu1337** [comment]
If you run the model in train mode with the resume=True parameter, then the following parameters appear in the default parameter line in the train method: hide_labels=False, hide_conf=False, line_thickness=3, fl_gamma=0.0, v5loader=True. If you do not change the resume parameter, then the above parameters do not appear. How to solve this problem?
engine\trainer: task=detect, mode=train, model=yolov8n.pt, data=C:\Users\damir\OneDrive\Desktop\Damir\andrey\dataset1\coco8.yaml, epochs=500, time=None, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=disk, device=0, workers=8, project=YOLOv8, name=yolov8n5, exist_ok=False, pretrained=False, optimizer=SGD, verbose=False, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=yolov8n.pt, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=False, val=True, split=val, save_json=False, save_hybrid=False, conf=0.001, iou=0.7, max_det=300, half=True, dnn=False, plots=True, source=ultralytics/assets/, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.001, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, image_weights=False, hide_labels=False, hide_conf=False, line_thickness=3, fl_gamma=0.0, v5loader=True, save_dir=YOLOv8\yolov8n5

**Comment by glenn-jocher** [comment]
@bohhuu1337 hi there,

Thank you for reaching out and providing detailed information about the issue you're encountering. It seems like the `resume=True` parameter is introducing deprecated or invalid arguments into the training process, which is causing the error.

To address this, please follow these steps:

1. **Update to the Latest Version**: Ensure you are using the latest version of the Ultralytics YOLOv8 package. You can update it using:
   ```bash
   pip install --upgrade ultralytics
   ```

2. **Remove Deprecated Arguments**: The arguments `hide_labels`, `hide_conf`, `line_thickness`, `fl_gamma`, and `v5loader` are deprecated or invalid. Ensure these are not being passed in your training script. Instead, use the updated arguments `show_labels`, `show_conf`, and `line_width`.

3. **Simplify the Training Command**: Start with a minimal training command to ensure the basics are working, and then incrementally add other parameters. For example:
   ```python
   from ultralytics import YOLO

   def main():
       # Load the model
       model = YOLO('yolov8n.pt')

       # Train the model
       results = model.train(
           data='C:\\Users\\damir\\OneDrive\\Desktop\\Damir\\andrey\\dataset1\\coco8.yaml',
           imgsz=640,
           epochs=10,
           name='C:\\Users\\damir\\OneDrive\\Desktop\\Damir\\model',
           resume=True
       )

   if __name__ == '__main__':
       from multiprocessing import freeze_support
       freeze_support()
       main()
   ```

4. **Verify Dataset Paths**: Ensure that the paths specified in your `data.yaml` file are correct and accessible. For example:
   ```yaml
   train: C:\\Users\\damir\\OneDrive\\Desktop\\Damir\\andrey\\dataset1\\images\\train
   val: C:\\Users\\damir\\OneDrive\\Desktop\\Damir\\andrey\\dataset1\\images\\val
   ```

If the issue persists, please provide a minimal reproducible example as outlined in our [documentation](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us diagnose the problem more effectively.

Feel free to reach out if you have any further questions or need additional assistance. Happy training! 🚀

**Comment by Y-T-G** [comment]
https://y-t-g.github.io/tutorials/yolov8n-add-classes/

**Comment by glenn-jocher** [comment]
Hi @Y-T-G,

Thank you for sharing the link. It looks like you're encountering issues when using the `resume=True` parameter during training, which introduces deprecated or invalid arguments.

To address this, please ensure you are using the latest version of the Ultralytics YOLOv8 package by running:
```bash
pip install --upgrade ultralytics
```

If the issue persists, it's crucial to provide a minimal reproducible example to help us diagnose the problem effectively. You can find guidelines for creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

In the meantime, try simplifying your training command to exclude deprecated arguments and ensure paths in your `data.yaml` are correct. Here's a streamlined example:
```python
from ultralytics import YOLO

def main():
    model = YOLO('yolov8n.pt')
    results = model.train(
        data='C:\\Users\\damir\\OneDrive\\Desktop\\Damir\\andrey\\dataset1\\coco8.yaml',
        imgsz=640,
        epochs=10,
        name='C:\\Users\\damir\\OneDrive\\Desktop\\Damir\\model',
        resume=True
    )

if __name__ == '__main__':
    from multiprocessing import freeze_support
    freeze_support()
    main()
```

Please let us know if the issue persists after these steps. We're here to help! 🚀

**Comment by zhixuwei** [comment]
The issue may be related to the version. When I tested the most recent version of the program, I did not encounter this problem. The parameters in question are documented in relatively earlier versions. After conducting a preliminary analysis of their potential calls, I did not identify any obvious issues. I recommend changing your working directory and downloading the latest program.

**Comment by bohhuu1337** [comment]
Indeed, reinstalling the library solved the problem, but the following error appeared. How to continue further training the yolov8n model on your data set

Traceback (most recent call last):
  File "C:\Users\damir\PycharmProjects\TestYoloV8\main.py", line 18, in <module>
    main()
  File "C:\Users\damir\PycharmProjects\TestYoloV8\main.py", line 5, in main
    results = model.train(
              ^^^^^^^^^^^^
  File "C:\Users\damir\PycharmProjects\TestYoloV8\venv\Lib\site-packages\ultralytics\engine\model.py", line 650, in train
    self.trainer.train()
  File "C:\Users\damir\PycharmProjects\TestYoloV8\venv\Lib\site-packages\ultralytics\engine\trainer.py", line 204, in train
    self._do_train(world_size)
  File "C:\Users\damir\PycharmProjects\TestYoloV8\venv\Lib\site-packages\ultralytics\engine\trainer.py", line 323, in _do_train
    self._setup_train(world_size)
  File "C:\Users\damir\PycharmProjects\TestYoloV8\venv\Lib\site-packages\ultralytics\engine\trainer.py", line 315, in _setup_train
    self.resume_training(ckpt)
  File "C:\Users\damir\PycharmProjects\TestYoloV8\venv\Lib\site-packages\ultralytics\engine\trainer.py", line 690, in resume_training
    assert start_epoch > 0, (
           ^^^^^^^^^^^^^^^
AssertionError: yolov8n.pt training to 500 epochs is finished, nothing to resume.
Start a new training without resuming, i.e. 'yolo train model=yolov8n.pt'
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.001), 63 bias(decay=0.0)

Process finished with exit code 1

code:
from ultralytics import YOLO

def main():
    model = YOLO('yolov8n.pt')
    model.train(
        data='C:\\Users\\damir\\PycharmProjects\\TestYoloV8\\data.yaml',
        imgsz=640,
        epochs=10,
        name='C:\\Users\\damir\\OneDrive\\Desktop\\Damir\\model',
        resume=True
    )

if __name__ == '__main__':
    from multiprocessing import freeze_support
    freeze_support()
    main()

data.yaml:
train: C:\Users\damir\PycharmProjects\TestYoloV8\train\images
val: C:\Users\damir\PycharmProjects\TestYoloV8\valid\images
test: C:\Users\damir\PycharmProjects\TestYoloV8\test\images

names: 
  0: avtobus
  1: marshrutka
  2: tramvay
  3: trolleybus

**Comment by Y-T-G** [comment]
You can't do that. You can't "add" more classes to an existing model. You can add a new head and add classes to that head like I show here:

> https://y-t-g.github.io/tutorials/yolov8n-add-classes/

**Comment by glenn-jocher** [comment]
Hi @Y-T-G-G,

Thank you for your message and for sharing the link to your tutorial. It looks like you're encountering an issue when trying to resume training with the `resume=True` parameter, which results in an `AssertionError` indicating that the training is already completed.

To address this, you can start a new training session without the `resume=True` parameter. This will allow you to continue training the model on your dataset with the new classes. Here's how you can do it:

```python
from ultralytics import YOLO

def main():
    model = YOLO('yolov8n.pt')
    model.train(
        data='C:\\Users\\damir\\PycharmProjects\\TestYoloV8\\data.yaml',
        imgsz=640,
        epochs=10,
        name='C:\\Users\\damir\\OneDrive\\Desktop\\Damir\\model'
    )

if __name__ == '__main__':
    from multiprocessing import freeze_support
    freeze_support()
    main()
```

By removing the `resume=True` parameter, you can start a fresh training session, which should resolve the issue.

If you encounter any further issues or have additional questions, please feel free to provide a minimal reproducible example as outlined in our [documentation](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us diagnose and address the problem more effectively.

Thank you for your understanding, and happy training! 🚀

**Comment by bohhuu1337** [comment]
thanks for the answer
