### ISSUE TITLE
How can I perform a training with two different machines?

### ISSUE THREAD

**Issue by dariogonle** [ultralytics/ultralytics#14075]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Due to lack of memory in the GPUs I want to use two machines to distribute the load. This way the batch will be distributed between two machines. 

I have used the example for yolov5 [(https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training/#multi-gpu-distributeddataparallel-mode-recommended)](url) but it does not work for me. The machines are on the same network so it can't be a connection problem.

How can I perform a distributed training between two machines connected by network?

**Comment by glenn-jocher** [comment]
@dariogonle hello,

Thank you for your question and for searching the existing issues and discussions before posting.

To perform distributed training across two machines, you can leverage PyTorch's DistributedDataParallel (DDP) functionality, which is supported by YOLOv8. Here's a step-by-step guide to help you set up distributed training:

1. **Ensure Latest Versions**: First, make sure you are using the latest versions of YOLOv8 and PyTorch. This ensures you have all the latest features and bug fixes.

2. **Set Up Environment**: Both machines need to have the same environment setup, including the same versions of Python, PyTorch, and YOLOv8.

3. **Network Configuration**: Ensure that both machines can communicate with each other over the network. You might need to configure firewall settings to allow traffic on the ports used by PyTorch DDP.

4. **Distributed Training Script**: Modify your training script to use PyTorch's DDP. Here is an example script to get you started:

    ```python
    import torch
    import torch.distributed as dist
    from torch.nn.parallel import DistributedDataParallel as DDP
    from ultralytics import YOLO

    def setup(rank, world_size):
        dist.init_process_group("nccl", rank=rank, world_size=world_size)

    def cleanup():
        dist.destroy_process_group()

    def main(rank, world_size):
        setup(rank, world_size)
        
        # Load your model
        model = YOLO('yolov8n.yaml')
        
        # Move model to GPU
        model.to(rank)
        
        # Wrap model in DDP
        model = DDP(model, device_ids=[rank])
        
        # Define your dataset and dataloader
        # Ensure to use DistributedSampler
        train_dataset = ...
        train_sampler = torch.utils.data.distributed.DistributedSampler(train_dataset, num_replicas=world_size, rank=rank)
        train_loader = torch.utils.data.DataLoader(dataset=train_dataset, sampler=train_sampler, ...)
        
        # Training loop
        for epoch in range(num_epochs):
            train_sampler.set_epoch(epoch)
            for batch in train_loader:
                # Training step
                ...
        
        cleanup()

    if __name__ == "__main__":
        world_size = 2  # Number of machines
        torch.multiprocessing.spawn(main, args=(world_size,), nprocs=world_size, join=True)
    ```

5. **Launch Training**: Run the script on both machines. You will need to specify the rank of each machine (0 or 1) and the total number of processes (world_size). For example:
    ```bash
    python -m torch.distributed.launch --nproc_per_node=1 --nnodes=2 --node_rank=0 --master_addr="MASTER_IP" --master_port=12345 your_script.py
    ```

    Replace `MASTER_IP` with the IP address of the master node.

For more detailed information, you can refer to the [PyTorch Distributed Training documentation](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html).

If you encounter any issues, please provide a minimum reproducible example as outlined [here](https://docs.ultralytics.com/help/minimum_reproducible_example) so we can assist you further.

Happy training! 🚀
