### ISSUE TITLE
YOLOv8 bounding box detection

### ISSUE THREAD

**Issue by Joeyabuki99** [ultralytics/ultralytics#14076]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hi! I'm using yolov8 only as a detector, I taake the bounding boxes from an input video like that:

    `results = detector(frame)         
    detections = results[0].boxes  

    for box in detections:
        x1, y1, x2, y2 = box.xyxy[0].tolist()`
       
  now I want to understand when an object into the video stops.... how can I do that?? I noticed that the bounding boxes is not fixed even with the item stopped, so I cannot compare the coordinates between frames... how can I understand if an object stopped from the bounding boxes?? maybe there is a method to stabilize the bounding boxes?

**Comment by glenn-jocher** [comment]
@Joeyabuki99 hi there! Thanks for reaching out with your question.

To detect when an object in a video stops, you can use object tracking in conjunction with your YOLOv8 detector. Tracking allows you to maintain the identity of objects across frames, which can help in determining if an object has stopped moving.

Here's a basic approach to achieve this:

1. **Integrate Object Tracking**: Use a tracking algorithm like ByteTrack or BoT-SORT with YOLOv8 to track objects across frames. This will help you maintain consistent object IDs.

2. **Calculate Movement**: For each tracked object, calculate the movement by comparing the bounding box coordinates between consecutive frames. If the movement is below a certain threshold for a specified number of frames, you can consider the object as stopped.

Here's an example using ByteTrack:

```python
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO("yolov8n.pt")

# Initialize the tracker
tracker = model.track(source="path/to/video.mp4", tracker="bytetrack.yaml")

# Define a threshold for detecting stopped objects
movement_threshold = 5  # pixels
frames_threshold = 10  # number of frames

# Dictionary to store the movement history of each object
movement_history = {}

for frame in tracker:
    results = model(frame)
    detections = results[0].boxes
    for box in detections:
        obj_id = box.id
        x1, y1, x2, y2 = box.xyxy[0].tolist()
        center = ((x1 + x2) / 2, (y1 + y2) / 2)

        if obj_id not in movement_history:
            movement_history[obj_id] = []

        movement_history[obj_id].append(center)

        # Check if the object has stopped
        if len(movement_history[obj_id]) > frames_threshold:
            recent_movements = movement_history[obj_id][-frames_threshold:]
            distances = [((recent_movements[i][0] - recent_movements[i-1][0]) ** 2 +
                          (recent_movements[i][1] - recent_movements[i-1][1]) ** 2) ** 0.5
                         for i in range(1, len(recent_movements))]
            if all(dist < movement_threshold for dist in distances):
                print(f"Object {obj_id} has stopped.")

    # Visualize or save the results as needed
    results[0].plot()

```

This code initializes a tracker and calculates the movement of each object. If an object's movement is below the `movement_threshold` for `frames_threshold` consecutive frames, it is considered stopped.

If you encounter any issues or need further assistance, please provide a reproducible example as described [here](https://docs.ultralytics.com/help/minimum_reproducible_example). Also, ensure you are using the latest version of the packages.

I hope this helps! 😊
