### ISSUE TITLE
How to get the masks for segmentation and visualized the segmented part only in a new image?

### ISSUE THREAD

**Issue by rzamarefat** [ultralytics/ultralytics#1407]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I know that there is a numpy() method which returns the segmentation numpy array. But I am not able to make a new image with just the segmented part. I am using the following code in order to get the prediction, but how can I finally get a segmented image out of the results given by the predict method.
```
import cv2
from ultralytics import YOLO
img = cv2.imread("path_to_image.py")
model = YOLO(path_to/yolov8n-seg.pt")  
result = model.predict(img)
print(type(result[0].masks.numpy()))
```
When I print the type of the "result[0].masks.numpy()", it is still a "Masks" object, but I want a raw np.array in order to apply the mask on the original image.

Thanks in advance for your help.

**Comment by mehran66** [comment]
result[0].masks.segments

**Comment by glenn-jocher** [comment]
Or also results[0].masks.masks

Just look inside the instance to find out where everything is:

<img width="755" alt="Screenshot 2023-03-14 at 02 22 33" src="https://user-images.githubusercontent.com/26833433/224868081-cef6e891-e3b3-46b5-9435-aae6ebbc01b3.png">

**Comment by Bstrum36** [comment]
How do I get the masks into arrays so I can use them?

Can you provide a code example.

Thanks

**Comment by glenn-jocher** [comment]
@Bstrum36 the mask arrays are shown above in the segment Results object.

**Comment by r8420** [comment]
@Bstrum36 You can use `results[0].masks.data.numpy().transpose(1, 2, 0)` to be able to use it with OpenCV. That is to get the mask, if you want to get only the segmented part of the image you'll have to apply the mask to the image.

**Comment by Aravinth-Natarajan** [comment]
I would appreciate if someone could give a code example of this

**Comment by r8420** [comment]
> I would appreciate if someone could give a code example of this

This example could use some improvements but anyway here you go:

```Python
results = model(frame)

if(len(results[0].masks) > 0):
    # Convert mask to single channel image
    mask_raw = results[0].masks.cpu().data.numpy().transpose(1, 2, 0)

    # Only use the first channel
    mask_raw = mask_raw[:, :, 0]
    
    # Convert single channel grayscale to 3 channel image
    mask_3channel = cv2.merge((mask_raw,mask_raw,mask_raw))

    # Get the size of the image (height, width, channels)
    h2, w2, c2 = results[0].orig_img.shape
    
    # Resize the mask to the same size as the image
    mask = cv2.resize(mask_3channel, (w2, h2), interpolation = cv2.INTER_AREA)

    # Convert BGR to HSV
    hsv = cv2.cvtColor(mask, cv2.COLOR_BGR2HSV)

    # Define range of brightness in HSV
    lower_black = np.array([0,0,0])
    upper_black = np.array([0,0,1])

    # Create a mask. Threshold the HSV image to get everything black
    mask = cv2.inRange(mask, lower_black, upper_black)

    # Invert the mask to get everything but black
    mask = cv2.bitwise_not(mask)

    # Apply the mask to the original image
    masked = cv2.bitwise_and(results[0].orig_img, results[0].orig_img, mask=mask)

    # Show the masked part of the image
    cv2.imshow("mask", masked)
```

**Comment by glenn-jocher** [comment]
@Aravinth-Natarajan sure! Here's an example that demonstrates how to get the masks into arrays and apply them to the original image to visualize the segmented part only:

```python
import cv2
from ultralytics import YOLO

# Load the image
img = cv2.imread("path_to_image.jpg")

# Create the YOLOv8 model
model = YOLO("path_to/yolov8.pt")

# Perform the prediction
results = model.predict(img)

# Check if masks are available in the result
if results[0].masks is not None:
    # Convert mask to numpy array
    masks = results[0].masks.numpy()

    # Get the first mask
    mask = masks[0]

    # Apply the mask to the image
    segmented_img = cv2.bitwise_and(img, img, mask=mask)

    # Display the segmented image
    cv2.imshow("Segmented Image", segmented_img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
```

In this example, we first load the image and create an instance of the YOLOv8 model. We then use the `predict` method to obtain the prediction results, including the masks. We check if masks are available and if so, we convert them to a numpy array. We take the first mask and apply it to the original image using the `cv2.bitwise_and` function. Finally, we display the segmented image.

Please note that this is a basic example and may require further customization based on your specific use case.

**Comment by Aravinth-Natarajan** [comment]
@glenn

> @Aravinth-Natarajan sure! Here's an example that demonstrates how to get the masks into arrays and apply them to the original image to visualize the segmented part only:
> 
> ```python
> import cv2
> from ultralytics import YOLO
> 
> # Load the image
> img = cv2.imread("path_to_image.jpg")
> 
> # Create the YOLOv8 model
> model = YOLO("path_to/yolov8.pt")
> 
> # Perform the prediction
> results = model.predict(img)
> 
> # Check if masks are available in the result
> if results[0].masks is not None:
>     # Convert mask to numpy array
>     masks = results[0].masks.numpy()
> 
>     # Get the first mask
>     mask = masks[0]
> 
>     # Apply the mask to the image
>     segmented_img = cv2.bitwise_and(img, img, mask=mask)
> 
>     # Display the segmented image
>     cv2.imshow("Segmented Image", segmented_img)
>     cv2.waitKey(0)
>     cv2.destroyAllWindows()
> ```
> 
> In this example, we first load the image and create an instance of the YOLOv8 model. We then use the `predict` method to obtain the prediction results, including the masks. We check if masks are available and if so, we convert them to a numpy array. We take the first mask and apply it to the original image using the `cv2.bitwise_and` function. Finally, we display the segmented image.
> 
> Please note that this is a basic example and may require further customization based on your specific use case.

Hi, thanks for helping. When I try this, I get the following error which doesn't make much sense to me since masks was converted to a numpy array in the code.

cv2.error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'bitwise_and'
> Overload resolution failed:
>  - mask is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'mask'

**Comment by Aravinth-Natarajan** [comment]
> r8420

Thanks, this ended up working. I had to tweak the code a bit, adding 

    cv2.waitKey(0)
    cv2.destroyAllWindows()

**Comment by glenn-jocher** [comment]
Hi @Aravinth-Natarajan, I'm glad that the code tweak helped! Adding `cv2.waitKey(0)` and `cv2.destroyAllWindows()` is necessary for displaying the segmented image window. 

`cv2.waitKey(0)` waits for a key event and `cv2.destroyAllWindows()` closes all the open windows. This ensures that the segmented image window remains open until a key is pressed. Once a key is pressed, the window is closed.

I hope this clarifies the usage of `cv2.waitKey()` and `cv2.destroyAllWindows()` in the code. Let me know if you have any further questions or need additional assistance.

**Comment by Aravinth-Natarajan** [comment]
> Hi @Aravinth-Natarajan, I'm glad that the code tweak helped! Adding `cv2.waitKey(0)` and `cv2.destroyAllWindows()` is necessary for displaying the segmented image window.
> 
> `cv2.waitKey(0)` waits for a key event and `cv2.destroyAllWindows()` closes all the open windows. This ensures that the segmented image window remains open until a key is pressed. Once a key is pressed, the window is closed.
> 
> I hope this clarifies the usage of `cv2.waitKey()` and `cv2.destroyAllWindows()` in the code. Let me know if you have any further questions or need additional assistance.

Thank you, Sorry for the dumb mistake

**Comment by Aravinth-Natarajan** [comment]
Sorry about the dumb mistake. thanks a lot for all of your help

**Comment by glenn-jocher** [comment]
@Aravinth-Natarajan thank you for reaching out to us. Please don't worry about the mistake; we are here to help. We appreciate your understanding.

If you have any further questions or need assistance with YOLOv8, please feel free to ask.

**Comment by pfcouto** [comment]
HI @glenn-jocher, I was actually trying to do something similar, so I will take a better look into this issue. But, in the meantime, can you tell me how you look into the results variable as you have shown in the picture? VSCode and Jupyter have a similar functionality, but I can open the object. Thanks!

![image](https://github.com/ultralytics/ultralytics/assets/69256195/c27baa6c-077b-4b4e-aad0-b74e816f304e)
 

> Or also results[0].masks.masks
> 
> Just look inside the instance to find out where everything is:
> 
> <img alt="Screenshot 2023-03-14 at 02 22 33" width="755" src="https://user-images.githubusercontent.com/26833433/224868081-cef6e891-e3b3-46b5-9435-aae6ebbc01b3.png">

**Comment by pfcouto** [comment]
Hi @glenn-jocher, I don't know which version you are using. However, I have new options that substitute masks (new is data) and segmentes (xy and xyn).

Can you explain what are masks (or data) and segments (or xy, xyn) and their differences? I don't quite underdstantd them.

Also, I tried your code and it gives this error: `can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first..`

And checking my output I have cuda mentions, how can I fix this issue? Thanks!

```
data: tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0')
masks: tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0')
```


If possible, can you update the code, so it works with the new variables? Thanks!

**Comment by ghux** [comment]
> > I would appreciate if someone could give a code example of this
> 
> This example could use some improvements but anyway here you go:
> 
> ```python
> results = model(frame)
> 
> if(results[0].masks is not None):
>     # Convert mask to single channel image
>     mask_raw = results[0].masks[0].cpu().data.numpy().transpose(1, 2, 0)
>     
>     # Convert single channel grayscale to 3 channel image
>     mask_3channel = cv2.merge((mask_raw,mask_raw,mask_raw))
> 
>     # Get the size of the original image (height, width, channels)
>     h2, w2, c2 = results[0].orig_img.shape
>     
>     # Resize the mask to the same size as the image (can probably be removed if image is the same size as the model)
>     mask = cv2.resize(mask_3channel, (w2, h2))
> 
>     # Convert BGR to HSV
>     hsv = cv2.cvtColor(mask, cv2.COLOR_BGR2HSV)
> 
>     # Define range of brightness in HSV
>     lower_black = np.array([0,0,0])
>     upper_black = np.array([0,0,1])
> 
>     # Create a mask. Threshold the HSV image to get everything black
>     mask = cv2.inRange(mask, lower_black, upper_black)
> 
>     # Invert the mask to get everything but black
>     mask = cv2.bitwise_not(mask)
> 
>     # Apply the mask to the original image
>     masked = cv2.bitwise_and(results[0].orig_img, results[0].orig_img, mask=mask)
> 
>     # Show the masked part of the image
>     cv2.imshow("mask", masked)
> ```

Thanks for sharing this example, it has been really useful. It is working great in my instance segmentation usecase, but when there are multiple detections per image it only visualises one segment. I assume I need to loop through the masks numpy array? Any advice would be greatly appreciated

**Comment by glenn-jocher** [comment]
@ghux hi, that's correct! If the prediction result contains multiple masks, i.e., there are multiple detection segments per image, you would ideally need to loop through the Masks numpy array to apply each mask and visualize each segmented part.

In an instance segmentation scenario, each mask corresponds to a particular object detected in the image. By looping through the masks array, you can segment the image for each detected object individually. You can then visualize or further process each segment as per your requirements. 

Keep in mind to manage overlapping masks, as multiple objects can share space in the image. This can influence how you handle individually segmented pieces. 

Let me know if you need more clarification or help with anything else!

**Comment by ghux** [comment]
> @ghux hi, that's correct! If the prediction result contains multiple masks, i.e., there are multiple detection segments per image, you would ideally need to loop through the Masks numpy array to apply each mask and visualize each segmented part.
> 
> In an instance segmentation scenario, each mask corresponds to a particular object detected in the image. By looping through the masks array, you can segment the image for each detected object individually. You can then visualize or further process each segment as per your requirements.
> 
> Keep in mind to manage overlapping masks, as multiple objects can share space in the image. This can influence how you handle individually segmented pieces.
> 
> Let me know if you need more clarification or help with anything else!

Thanks @glenn-jocher . I have the following code, based on parts of this thread. 
I see that in `mask_raw = results[0].masks[0].cpu().data.numpy().transpose(1, 2, 0)` if I change the `masks[]` integer from 0 to 1 or 2 etc. then the a different mask is returned. However, I am lost as to how to create the loop that cycles through the masks list until the end, processing them all and therefore returning a single binary image with all segmentation masks. If you have the time I would really appreciate an help you could offer!

```
import cv2
from ultralytics import YOLO
import numpy as np
from PIL import Image

# Load the image
img = cv2.imread("x.jpg")
# Create the YOLOv8 model
model = YOLO("last.pt")

results = model.predict(img)

if(results[0].masks is not None):
    # Convert mask to single channel image
    mask_raw = results[0].masks[0].cpu().data.numpy().transpose(1, 2, 0)
    # Convert single channel grayscale to 3 channel image
    mask_3channel = cv2.merge((mask_raw,mask_raw,mask_raw))
    # Get the size of the original image (height, width, channels)
    h2, w2, c2 = results[0].orig_img.shape
    # Resize the mask to the same size as the image
    mask = cv2.resize(mask_3channel, (w2, h2))
    # Convert BGR to HSV
    hsv = cv2.cvtColor(mask, cv2.COLOR_BGR2HSV)
    # Define range of brightness in HSV
    lower_black = np.array([0,0,0])
    upper_black = np.array([0,0,1])
    # Create a mask. Threshold the HSV image to get everything black
    mask = cv2.inRange(mask, lower_black, upper_black)
    # Invert the mask to get everything but black
    mask = cv2.bitwise_not(mask)
    # Apply the mask to the original image
    masked = cv2.bitwise_and(results[0].orig_img, results[0].orig_img, mask=mask)

    # Save the images
    cv2.imwrite("binmask.jpg", mask)
    cv2.imwrite("clrmask.jpg", masked)
```

**Comment by glenn-jocher** [comment]
Hello @ghux! Indeed, you're on the right path. When you change the index in `results[0].masks[0]`, it allows you to access different detected masks. To process all masks and return a single binary image with all segmentation masks, you would ideally need to set up a loop.

In your case, you can create a loop that goes through the entire `results[0].masks` list. Inside this loop, the operations you're currently performing on a single mask will be performed on every mask. After processing, you can combine these masks into a single binary image. 

For handling overlapping masks, you have to decide how you want to combine them. A simple approach would be to use a logical 'OR' operation, so that if a pixel is part of any mask, it will be part of the cumulative mask.

Remember to initialise your mask outside the loop to avoid any issues.

I hope this helps! Let me know if you have any other questions.

**Comment by crapthings** [comment]
```py
import cv2
from PIL import Image, ImageDraw, ImageFilter

fn = './67751689328912_.pic.jpg'

img = Image.open(fn).convert('RGB')
mask = Image.new('RGB', img.size, color = (0, 0, 0))

results = model(img)

def mask_dilate (image, value = 4):
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (value, value))
    dilated = cv2.dilate(np.array(image), kernel)
    return Image.fromarray(dilated)

for result in results:
    masks = result.masks.xy
    
    smoothed_masks = [cv2.approxPolyDP(mask, 4, True) for mask in masks]
    
    for smoothed_mask in smoothed_masks:
        M = cv2.moments(smoothed_mask)
        cx = int(M['m10'] / M['m00'])
        cy = int(M['m01'] / M['m00'])
        
        scale_ratio = 1.1
        resized_mask = smoothed_mask.copy()
        
        for p in resized_mask:
            p[0][0] = (p[0][0] - cx) * scale_ratio + cx
            p[0][1] = (p[0][1] - cy) * scale_ratio + cy
            
        xy = [(p[0][0], p[0][1]) for p in resized_mask]
        
        # draw on original image
        # draw = ImageDraw.Draw(img)
		 # draw.polygon(xy, fill = 'gray', outline = 'red')	

        # draw on new mask image file
        draw = ImageDraw.Draw(img)        
        # draw.polygon(xy, outline = 'red')
        # draw.polygon(xy, fill = 'white')

# you can save img or mask by img.save(filename), mask.save(filename), its just pil object

# works with notebook
display(mask)
mask = mask_dilate(mask, value = 4) 
display(mask)
mask = mask.filter(ImageFilter.GaussianBlur(radius = 4))
display(mask)
```

**Comment by glenn-jocher** [comment]
@crapthings hello! Nice to see you making good use of the YOLOv8 model for your instance segmentation task. Your usage of cv2 library for applying masks to the original image, dilating them and smoothing via Gaussian blur is clear and we anticipate that it should work successfully. 

The crucial point of your code is iterating over the results generated by the model prediction. For each result, you're focusing particularly on the mask attribute. This attribute is found within the xy coordinates of the masks for each detected object. You're then dilating and applying Gaussian blur to these masks to hopefully achieve a smoother edge on the resulting segmentation.

Now, I see that you have scaled and repositioned the mask according to some centroid coordinates. This is an interesting approach to potentially handle variations in detected objects size and positioning, and should help you tailor the mask more appropriately to different detection cases.

Lastly, you draw these processed masks back onto your original image, effectively overlaying the detected objects with their corresponding masks. 

So overall, your approach seems quite comprehensive! Just make sure that the approxPolyDP() function is providing the result you desire and that the moments() function works as expected on your masks. Also, be mindful of the potential effects of dilation and blurring, to make sure they align with your specific project requirements.

I hope I managed to interpret your strategy right. If you have further clarifications, please let us know!

**Comment by jose-cisco** [comment]
@ghux before if(results[0].masks is not None): 
please print len(masks) to see how many masks in image
then you have to create 
   for i ,masks in len(masks):
    if(results[0].masks is not None):
        # Convert mask to single channel image
        mask_raw = results[0].masks[i].cpu().data.numpy().transpose(1, 2, 0)

like this

**Comment by r8420** [comment]
> Thanks for sharing this example @r8420 , it has been really useful. It is working great in my instance segmentation usecase, but when there are multiple detections per image it only visualises one segment. I assume I need to loop through the masks numpy array? Any advice would be greatly appreciated

@ghux If you want to combine multiple detections to a single mask, you could try something like this:
```Python
 if len(results[0].boxes) > 0:
    # Get the size of the original image (height, width, channels)
    h2, w2, _ = results[0].orig_img.shape
    masks = None

    # Define range of brightness in HSV
    lower_black = np.array([0,0,0])
    upper_black = np.array([0,0,1])
    
    for mask in results[0].masks:
        mask_raw = mask.cpu().data.numpy().transpose(1, 2, 0)

        # Convert single channel grayscale to 3 channel image
        mask_3channel = cv2.cvtColor(mask_raw, cv2.COLOR_GRAY2BGR)

        # Resize the mask to the same size as the image (can probably be removed if image is the same size as the model)
        mask = cv2.resize(mask_3channel, (w2, h2))

        # Create a mask. Threshold the HSV image to get everything black
        mask = cv2.inRange(mask, lower_black, upper_black)

        # Invert the mask to get everything but black
        mask = cv2.bitwise_not(mask)

        if masks is None:
            masks = mask
        else:
            masks = cv2.bitwise_or(mask, masks)
    
    # Apply the mask to the original image
    masked = cv2.bitwise_and(results[0].orig_img, results[0].orig_img, mask=masks)

    # Show the masked part of the image
    cv2.imshow("mask", masked)
                
```

**Comment by Little-knownmuhammad** [comment]
> [@Bstrum36](https://github.com/Bstrum36) You can use `results[0].masks.data.numpy().transpose(1, 2, 0)` to be able to use it with OpenCV. That is to get the mask, if you want to get only the segmented part of the image you'll have to apply the mask to the image.





https://stackdev.space/questions/utilizing-arrays-to-store-information-and-display-them-efficiently

**Comment by glenn-jocher** [comment]
@Little-knownmuhammad great approach! 🚀 Your code correctly handles multiple masks by using `cv2.bitwise_or` to combine them. For CUDA users, remember masks might be on GPU - your `.cpu()` conversion fixes that. The official [Isolating Segmentation Objects](https://docs.ultralytics.com/guides/isolating-segmentation-objects/) guide shows similar techniques using contours. For high-resolution images (like 3456x3456), ensure masks are properly scaled using `results[0].orig_shape`.
