### ISSUE TITLE
I am getting error! Help Me to Fix it i am confused

### ISSUE THREAD

**Issue by kismatTech** [ultralytics/ultralytics#14089]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

 File "d:\yolov8\predict_modified.py", line 128, in predict
    cfg.imgsz = check_imgsz(cfg.imgsz, min_dim=2)  # Check image size
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\yolov8\ultralytics\yolo\utils\checks.py", line 146, in check_imgsz
    raise TypeError(
TypeError: 'imgsz=[640, 640]' is of invalid type ListConfig. Valid imgsz types are int i.e. 'imgsz=640' or list i.e. 'imgsz=[640,640]

**Comment by glenn-jocher** [comment]
@kismatTech hi there,

Thank you for reaching out! It looks like you're encountering a `TypeError` related to the `imgsz` parameter in your script. This error suggests that the `imgsz` parameter is being passed as a `ListConfig` type, which is not valid. The `imgsz` should be either an integer (e.g., `imgsz=640`) or a list of integers (e.g., `imgsz=[640, 640]`).

To help you more effectively, could you please provide a minimum reproducible example of your code? This will allow us to better understand the context and pinpoint the issue. You can find guidelines on how to create a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

In the meantime, please ensure that you are using the latest version of the Ultralytics YOLO package, as updates often include bug fixes and improvements. You can update the package using the following command:
```bash
pip install --upgrade ultralytics
```

Here's a quick example of how you might set the `imgsz` parameter correctly:
```python
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')

# Set image size
imgsz = [640, 640]  # or imgsz = 640

# Run prediction
results = model.predict(source='path/to/image.jpg', imgsz=imgsz)
```

If you continue to experience issues, please share more details about your environment and the specific code snippet causing the error. This will help us assist you more effectively.
