### ISSUE TITLE
ROS

### ISSUE THREAD

**Issue by zai1318** [ultralytics/ultralytics#1408]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there any docker file of YOLOv8 Instance Segmentation for ROS ?

**Comment by glenn-jocher** [comment]
@zai1318 Docker images for CPU, GPU and ARM are available at https://hub.docker.com/r/ultralytics/ultralytics/tags
