### ISSUE TITLE
export yolov8 format 

### ISSUE THREAD

**Issue by bhralzz** [ultralytics/ultralytics#14090]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,
having a trained yolo v8 segmentaiton model and want to have yolo v8 segmentation format output for a given image, is it possible?
consider that the objects are not in rectangular boxes and I want to have exact segmentation perimeters for any blobs.

raw image -> trained model -> segmentation in yolo v8 format

**Comment by glenn-jocher** [comment]
Hello,

Thank you for reaching out! Yes, you can achieve this with a trained YOLOv8 segmentation model. The model can provide precise segmentation masks for objects, which are not limited to rectangular bounding boxes but can outline the exact perimeters of the objects.

Here's a concise example of how you can use a trained YOLOv8 segmentation model to get segmentation outputs for a given image:

### Python Example

```python
from ultralytics import YOLO

# Load your trained YOLOv8 segmentation model
model = YOLO("path/to/your/trained/model.pt")

# Perform segmentation on an image
results = model("path/to/your/image.jpg")

# Access the segmentation masks
masks = results[0].masks  # This will give you the segmentation masks for the objects

# Optionally, visualize the results
results[0].plot()  # This will display the image with segmentation masks overlaid
```

### CLI Example

If you prefer using the command line interface, you can achieve the same with the following command:

```bash
yolo segment predict model=path/to/your/trained/model.pt source=path/to/your/image.jpg
```

This command will run the segmentation model on the specified image and provide the segmentation output.

For more detailed information on segmentation tasks, you can refer to our [Segmentation Documentation](https://docs.ultralytics.com/tasks/segment/).

If you encounter any issues or have further questions, please provide a minimum reproducible example as outlined [here](https://docs.ultralytics.com/help/minimum_reproducible_example) to help us assist you better. Also, ensure you are using the latest version of the Ultralytics packages to avoid any known issues.

**Comment by bhralzz** [comment]
thanks for your kind replying,
I mean is there any option for exporting the model output in yolo v8 text format?

**Comment by glenn-jocher** [comment]
@bhralzz hello,

Thank you for the clarification! Yes, you can export the model output in YOLOv8 text format, which includes the class labels, bounding box coordinates, and confidence scores. This is particularly useful for further processing or integration with other systems.

Here's how you can achieve this using the Python API:

### Python Example

```python
from ultralytics import YOLO

# Load your trained YOLOv8 segmentation model
model = YOLO("path/to/your/trained/model.pt")

# Perform segmentation on an image
results = model("path/to/your/image.jpg")

# Save the results in YOLOv8 text format
results[0].save_txt("path/to/save/directory")
```

### CLI Example

Alternatively, you can use the command line interface to save the predictions in YOLOv8 text format:

```bash
yolo segment predict model=path/to/your/trained/model.pt source=path/to/your/image.jpg save_txt=True
```

This command will save the predictions in the specified directory in YOLOv8 text format.

If you encounter any issues or need further assistance, please ensure you are using the latest version of the Ultralytics packages. Additionally, providing a minimum reproducible example can greatly help us diagnose and resolve any issues you might face. You can find more details on how to create one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions! 😊

**Comment by bhralzz** [comment]
> consider that the objects are not in rectangular boxes and I want to have exact segmentation perimeters for any blobs.

Please consider that I am searching for contour of non rectangular segmented objects as I said in the first question.
However, I think its not generating such output at the moment, am I right?

**Comment by glenn-jocher** [comment]
Hello,

Thank you for the clarification! YOLOv8 segmentation models indeed provide precise segmentation masks that outline the exact perimeters of objects, not just rectangular bounding boxes. These masks can be used to extract contours of non-rectangular segmented objects.

To get the contours from the segmentation masks, you can use the following approach in Python:

### Python Example

```python
import cv2
from ultralytics import YOLO

# Load your trained YOLOv8 segmentation model
model = YOLO("path/to/your/trained/model.pt")

# Perform segmentation on an image
results = model("path/to/your/image.jpg")

# Access the segmentation masks
masks = results[0].masks

# Convert masks to contours
for mask in masks:
    mask_np = mask.numpy()  # Convert mask to numpy array
    contours, _ = cv2.findContours(mask_np.astype('uint8'), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    for contour in contours:
        print(contour)  # Each contour is a numpy array of (x, y) coordinates
```

This code will give you the exact contours of the segmented objects.

If you believe the model is not generating the expected output, please ensure you are using the latest version of the Ultralytics packages. If the issue persists, providing a minimum reproducible example would be very helpful. You can find more details on how to create one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions! 😊

**Comment by bhralzz** [comment]
thanks for your kind replying!
let me explain again:
I am searching for yolo v8 text format output for segmented object as precise as possible and not rectangular area.
please consider a similar files like  input file we provide in training phase

as another explanation let me say that suppose a scenario which we have a test set containing images and labels and want to calculate some extra customized performance metrics based on comparison between the model output yolo v8 format with the test set ones. {both in yolo v8 format}

**Comment by glenn-jocher** [comment]
Hello,

Thank you for the additional details! I understand that you are looking for a way to obtain YOLOv8 text format outputs for segmented objects that match the precision of the input label files used during training. Specifically, you want to generate outputs that include the exact contours of segmented objects, not just rectangular bounding boxes.

Currently, YOLOv8 provides segmentation masks that can be converted to contours. While the default text output format includes bounding boxes, you can extract and save the precise contours using the following approach:

### Python Example

Here's how you can extract and save the contours of segmented objects in a custom text format:

```python
import cv2
import numpy as np
from ultralytics import YOLO

# Load your trained YOLOv8 segmentation model
model = YOLO("path/to/your/trained/model.pt")

# Perform segmentation on an image
results = model("path/to/your/image.jpg")

# Access the segmentation masks
masks = results[0].masks

# Function to save contours to a text file
def save_contours_to_txt(contours, filename):
    with open(filename, 'w') as f:
        for contour in contours:
            contour_str = ' '.join([f'{point[0][0]},{point[0][1]}' for point in contour])
            f.write(f'{contour_str}\n')

# Convert masks to contours and save them
for i, mask in enumerate(masks):
    mask_np = mask.numpy()  # Convert mask to numpy array
    contours, _ = cv2.findContours(mask_np.astype('uint8'), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    save_contours_to_txt(contours, f"output_contours_{i}.txt")
```

This script will save the contours of each segmented object in a separate text file, with coordinates in a format similar to the input label files.

If you encounter any issues or need further assistance, please ensure you are using the latest version of the Ultralytics packages. Providing a minimum reproducible example can greatly help us diagnose and resolve any issues you might face. You can find more details on how to create one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions! 😊

**Comment by bhralzz** [comment]
thanks for your help.
Yes its ok now.

**Comment by glenn-jocher** [comment]
You're welcome! I'm glad to hear that it's working for you now. 😊

If you have any more questions or run into any other issues, feel free to reach out. We're here to help!

Happy coding! 🚀
