### ISSUE TITLE
When training in google colab environment, it won't show the precision as well as recall, mAP during training process.

### ISSUE THREAD

**Issue by Andy718811** [ultralytics/ultralytics#14116]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When training in google colab environment, it won't show the precision as well as recall, map during training process, is that a bug?
The situation is like this, I tried to train my model in colab, but after almost 100 epochs, it still doesn't showed the precision and recall and mAP

I trained with this command.

```
from ultralytics import YOLO

# Load a model
model = YOLO('/content/drive/MyDrive/Blockade3d_yolo/models/yolov10_ultralytics/best_shield_2.pt')  # load a partially trained model

results = model.train(data='/content/drive/MyDrive/colab/colab_blockade/blockade.yaml',epochs=1000,patience=300,batch=32,project='/content/drive/MyDrive/colab/yolov8')
```
![image](https://github.com/ultralytics/ultralytics/assets/87431291/677be1f5-7ecb-4131-9334-265c482c29fd)

**Comment by glenn-jocher** [comment]
@Andy718811 hi there,

Thank you for reaching out and providing detailed information about your issue. It sounds like you're encountering a problem with the display of precision, recall, and mAP metrics during training in Google Colab.

To help us better understand and resolve the issue, could you please provide a minimum reproducible example? This will allow us to replicate the problem on our end and investigate further. You can find guidance on creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

In the meantime, please ensure that you are using the latest versions of all relevant packages, including Ultralytics and PyTorch. Sometimes, updating to the latest version can resolve unexpected issues.

Additionally, you might want to check if the metrics are being logged correctly but not displayed in the Colab output. You can use tools like TensorBoard to visualize these metrics. Here's a quick example of how to set it up:

```python
# Install TensorBoard
!pip install tensorboard

# Import TensorBoard
from torch.utils.tensorboard import SummaryWriter

# Initialize TensorBoard writer
writer = SummaryWriter('/content/drive/MyDrive/colab/yolov8/tensorboard_logs')

# Train the model and log metrics to TensorBoard
results = model.train(data='/content/drive/MyDrive/colab/colab_blockade/blockade.yaml',
                      epochs=1000, patience=300, batch=32,
                      project='/content/drive/MyDrive/colab/yolov8',
                      loggers=['tensorboard'])

# Launch TensorBoard
%load_ext tensorboard
%tensorboard --logdir /content/drive/MyDrive/colab/yolov8/tensorboard_logs
```

This setup will allow you to visualize the training metrics in TensorBoard, which can be very helpful for monitoring the training process.

If you continue to experience issues, please share any additional error messages or logs that might provide more context.
