### ISSUE TITLE
When will it be online to train its own target tracking dataset?

### ISSUE THREAD

**Issue by plotnine1219** [ultralytics/ultralytics#14119]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When will it be online to train its own target tracking dataset?

**Comment by glenn-jocher** [comment]
@plotnine1219 hello,

Thank you for your interest in training custom target tracking datasets with Ultralytics YOLO! Currently, our multi-object tracking feature supports using pre-trained detection, segmentation, or pose models directly for tracking tasks. Training trackers alone is a feature that is in development and will be available soon.

In the meantime, you can leverage pre-trained models for tracking by following the example below:

```python
from ultralytics import YOLO

model = YOLO("yolov8n.pt")
results = model.track(source="https://youtu.be/LNwODJXcvt4", conf=0.3, iou=0.5, show=True)
```

For more details and updates, please keep an eye on our [documentation](https://docs.ultralytics.com/datasets/track/).

If you encounter any issues or have further questions, feel free to reach out. Your feedback is invaluable to us! 😊
