### ISSUE TITLE
How to crop the segment images from image using YOLOv8-seg model？

### ISSUE THREAD

**Issue by Snailgoo** [ultralytics/ultralytics#1411]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to crop the segment images from image using YOLOv8-seg model？

### Additional

save_crop only save the bbox images，but i want crop the mask area from the images， how can i do？

**Comment by Laughing-q** [comment]
@Snailgoo hi, we don't have an internal support for this functionality but I think you can easily do it yourself once you have the predicted masks and original image.
Here's a simple example:
```python
from ultralytics import YOLO
import cv2
import numpy as np

model = YOLO('yolov8n-seg.pt')
results = model.predict(stream=True, retina_masks=True)
for result in results:
    mask = result.masks.cpu().numpy()
    masks = mask.masks.astype(bool)
    ori_img = result.orig_img
    for m in masks:
        new = np.zeros_like(ori_img, dtype=np.uint8)
        new[m] = ori_img[m]
        cv2.imshow('p', new)
        if cv2.waitKey(0) == ord('q'):
            break
```

**Comment by chandanmanna48** [comment]
Just use this code to crop a image with its coordinates.
`
for box in result.boxes:
  cords = box.xyxy[0].tolist()
  cords = [round(x) for x in cords]
  img = Image.fromarray(result.plot()[..., :: -1])  ## Original image
  img2 = img.crop(cords)  ##Croped image 
  img2.save() 
`

**Comment by glenn-jocher** [comment]
@chandanmanna48 hello,

You seem to be on the right track with your code. Your current code takes the bounding box coordinates produced from a model prediction, rounds them to the nearest integer (since they can come as floats), and applies those as arguments to the `crop()` method of a `PIL.Image` object, which is the original image.

One thing to note, `.crop()` expects a tuple of left, upper, right, and lower pixel coordinates. So, ensure your `cords` variable is in this format. Also, make sure that your coordinates are within the image dimensions to avoid any errors.

Lastly, you might want to specify a filename when calling `img2.save()`. Without an argument, it might raise an error.

Please let me know if this helps, or if you have any other questions.

**Comment by senthurram03** [comment]
The above code didn't work for me, but the code from this link works perfectly fine. 
[](https://docs.ultralytics.com/guides/isolating-segmentation-objects/#recipe-walk-through)
I believe there might be some changes in the SegmentationPredictor object

```
for r in results:
    img = np.copy(r.orig_img)
    img_name = Path(r.path).stem

    # iterate each object contour 
    for ci,c in enumerate(r):
        label = c.names[c.boxes.cls.tolist().pop()]

        b_mask = np.zeros(img.shape[:2], np.uint8)

        # Create contour mask 
        contour = c.masks.xy.pop().astype(np.int32).reshape(-1, 1, 2)
        _ = cv.drawContours(b_mask, [contour], -1, (255, 255, 255), cv.FILLED)

        # Choose one:

        # OPTION-1: Isolate object with black background
        mask3ch = cv.cvtColor(b_mask, cv.COLOR_GRAY2BGR)
        isolated = cv.bitwise_and(mask3ch, img)

        # OPTION-2: Isolate object with transparent background (when saved as PNG)
        isolated = np.dstack([img, b_mask])

        # OPTIONAL: detection crop (from either OPT1 or OPT2)
        x1, y1, x2, y2 = c.boxes.xyxy.cpu().numpy().squeeze().astype(np.int32)
        iso_crop = isolated[y1:y2, x1:x2]
```

**Comment by glenn-jocher** [comment]
@senthurram03, glad to hear you found a solution that works for you! Yes, the code snippet you've referenced from our documentation is a more detailed example of how to isolate objects using segmentation masks. It's great to see you've adapted it successfully.

The `SegmentationPredictor` class and the way segmentation results are handled may have evolved, so it's always a good idea to check the latest documentation or release notes for updates. If you have any further questions or need assistance with new features, feel free to reach out. Happy coding! 🚀
