### ISSUE TITLE
yolov8 trt exporting question

### ISSUE THREAD

**Issue by hongin13** [ultralytics/ultralytics#14126]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I exported yolov8 model by the command below:
yolo export yolov8x.pt format=engine int8=True

however, the data type written in the output logs was float.
I want to check if the model is successfully exported to int8 type or not
how can i check it?

Here is a part of the log

Layer(ElementWise): Sub_391, Tactic: 0x0000000000000001, onnx::Add_654[Float(8,2,8400)], onnx::Add_652[Float(8,2,8400)] -> onnx::Mul_659[Float(8,2,8400)]
Layer(Constant): onnx::Mul_660 + (Unnamed Layer* 376) [Shuffle], Tactic: 0x0000000000000000,  -> (Unnamed Layer* 376) [Shuffle]_output[Float(1,1,8400)]
Layer(ElementWise): Mul_394, Tactic: 0x0000000000000001, onnx::Mul_659[Float(8,4,8400)], (Unnamed Layer* 376) [Shuffle]_output[Float(1,1,8400)] -> output0[Float(8,4,8400)]
Layer(PointWiseV2): PWN(Sigmoid_395), Tactic: 0x000000000000001c, x_cat[Float(8,80,8400)] -> output0[Float(8,80,8400)]

**Comment by glenn-jocher** [comment]
@hongin13 hello,

Thank you for reaching out with your question regarding the TensorRT export of your YOLOv8 model. To verify if your model has been successfully exported to INT8 precision, you can follow these steps:

1. **Check the Export Logs**: The logs you provided indicate that the data type is still `Float`. This suggests that the INT8 calibration might not have been applied correctly. Ensure that you have provided the necessary calibration dataset using the `data` argument during export. For example:
    ```bash
    yolo export model=yolov8x.pt format=engine int8=True data=coco.yaml
    ```

2. **Inspect the Model**: You can inspect the exported TensorRT model to verify its precision. One way to do this is by using the TensorRT Python API to load the model and check the layer precisions. Here is a sample code snippet to help you get started:
    ```python
    import tensorrt as trt

    TRT_LOGGER = trt.Logger(trt.Logger.WARNING)
    engine_path = "yolov8x.engine"

    with open(engine_path, "rb") as f, trt.Runtime(TRT_LOGGER) as runtime:
        engine = runtime.deserialize_cuda_engine(f.read())

    for binding in engine:
        print(f"Binding: {binding}, Data Type: {engine.get_binding_dtype(binding)}")
    ```

3. **Ensure Latest Versions**: Make sure you are using the latest versions of the Ultralytics and TensorRT packages. Sometimes, issues are resolved in newer releases, so it's always a good idea to update.

4. **Reproducible Example**: If the issue persists, providing a minimum reproducible example can greatly help in diagnosing the problem. You can refer to our guide on creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

If you follow these steps and still encounter issues, please share more details or any additional logs, and we will be happy to assist further.

**Comment by LeonCheung1997** [comment]
> @hongin13 hello,
> 
> Thank you for reaching out with your question regarding the TensorRT export of your YOLOv8 model. To verify if your model has been successfully exported to INT8 precision, you can follow these steps:
> 
> 1. **Check the Export Logs**: The logs you provided indicate that the data type is still `Float`. This suggests that the INT8 calibration might not have been applied correctly. Ensure that you have provided the necessary calibration dataset using the `data` argument during export. For example:
>    ```shell
>    yolo export model=yolov8x.pt format=engine int8=True data=coco.yaml
>    ```
> 2. **Inspect the Model**: You can inspect the exported TensorRT model to verify its precision. One way to do this is by using the TensorRT Python API to load the model and check the layer precisions. Here is a sample code snippet to help you get started:
>    ```python
>    import tensorrt as trt
>    
>    TRT_LOGGER = trt.Logger(trt.Logger.WARNING)
>    engine_path = "yolov8x.engine"
>    
>    with open(engine_path, "rb") as f, trt.Runtime(TRT_LOGGER) as runtime:
>        engine = runtime.deserialize_cuda_engine(f.read())
>    
>    for binding in engine:
>        print(f"Binding: {binding}, Data Type: {engine.get_binding_dtype(binding)}")
>    ```
> 3. **Ensure Latest Versions**: Make sure you are using the latest versions of the Ultralytics and TensorRT packages. Sometimes, issues are resolved in newer releases, so it's always a good idea to update.
> 4. **Reproducible Example**: If the issue persists, providing a minimum reproducible example can greatly help in diagnosing the problem. You can refer to our guide on creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> If you follow these steps and still encounter issues, please share more details or any additional logs, and we will be happy to assist further.

Hi, I also met the issue when convert pt to int8 engine. the env is list below:
ultralytics: 8.2.102
tensorrt: 10.2.0.19


the log seem to be error like this:
[09/30/2024-01:16:59] [TRT] [V] =============== Computing costs for ONNXTRT_ShapeSlice_209
[09/30/2024-01:16:59] [TRT] [V] *************** Autotuning format combination: Float(1) -> Float(1) ***************
[09/30/2024-01:16:59] [TRT] [V] --------------- Timing Runner: ONNXTRT_ShapeSlice_209 (Slice[0x8000001b])
[09/30/2024-01:16:59] [TRT] [V] Setting a default quantization params because quantization data is missing for ONNXTRT_ShapeSlice_209
[09/30/2024-01:16:59] [TRT] [V] Tactic: 0x0000000000000000 Time: 0.00768485
[09/30/2024-01:16:59] [TRT] [V] ONNXTRT_ShapeSlice_209 (Slice[0x8000001b]) profiling completed in 0.00343906 seconds. Fastest Tactic: 0x0000000000000000 Time: 0.00768485
[09/30/2024-01:16:59] [TRT] [V] Skipping Padding: No valid tactics for ONNXTRT_ShapeSlice_209
