### ISSUE TITLE
Memory leak occurred while running the YOLO.track

### ISSUE THREAD

**Issue by Yakuho** [ultralytics/ultralytics#1413]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

log:
```
...
video 1/1 (1774/10946) /media/1.mp4: 384x640 3 persons, 11.8ms
video 1/1 (1775/10946) /media/1.mp4: 384x640 3 persons, 11.7ms
video 1/1 (1776/10946) /media/1.mp4: 384x640 3 persons, 12.7ms
video 1/1 (1777/10946) /media/1.mp4: 384x640 3 persons, 13.1ms
video 1/1 (1778/10946) /media/1.mp4: 384x640 3 persons, 10.3ms
video 1/1 (1779/10946) /media/1.mp4: 384x640 3 persons, 11.7ms
video 1/1 (1780/10946) /media/1.mp4: 384x640 3 persons, 10.1ms
Killed
```
As I ran the code and looked at the resource console, I saw that memory usage was increasing until it ran out of memory and was killed by the system

### Minimal Reproducible Example

```python
from ultralytics import YOLO

engine = YOLO(model='weights/yolov8n.pt')

results = engine.track(source="/media/1.mp4", show=False, tracker="bytetrack.yaml", device="0", classes=[0], save=True)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@Yakuho please refer to our docs [https://docs.ultralytics.com/modes/predict/](https://docs.ultralytics.com/modes/predict/) and try to use the generator way which set `stream=True` and it's memory efficient. This also works to track.

**Comment by Yakuho** [comment]
This is perfect. Sorry I didn't read the document carefully

**Comment by pderrenger** [comment]
@Yakuho no problem at all! The documentation is extensive, and it's easy to miss certain details. If you have any more questions or run into any issues, feel free to ask here. We're here to help! 😊

**Comment by alexbarnadas** [comment]
Hello I had the same problem, I am using the code provided in the tracking documentation, specifically the one used in multithrteading and modified with the changes suggested, it goes like this:
```
results = model.track(frame, persist=True, verbose=False, stream=True)
annotated_frame = results.plot()
```

I added the attribute `stream=True` and removed the index in `results[0]`

but now it still says this error and I can't find out anything about it in the docs, what am I doing wrong?
`AttributeError: 'generator' object has no attribute 'plot'`

**Comment by glenn-jocher** [comment]
@alexbarnadas the `model.track()` method with `stream=True` returns a generator, which yields results per frame. To access and plot these results, you need to iterate over the generator. The `.plot()` method should be called on the individual results within the loop, not on the generator itself. Here's a concise way to handle this:

```python
for result in model.track(frame, persist=True, verbose=False, stream=True):
    annotated_frame = result.plot()
    # Now you can use annotated_frame as needed
```

This will correctly call `.plot()` on each result yielded by the generator.

**Comment by alexbarnadas** [comment]
Yess, great, I did find out that. The Idea of turning the `stream=True` was to avoid a memory leak. But somehow the iteration keeps storing more and mode memory, I found out that the part that is increasing memory is in the results variable. Check the results of the memory tracking tool `memory_profiler`.

```
    80                                                 # Run YOLOv8 tracking on the frame, persisting tracks between frames
    81   4422.3 MiB    218.6 MiB        1201           results = model.track(frame, persist=True, verbose=False, stream=True)
    82                                         
    83                                                 # Get the boxes and track IDs
    84   4425.0 MiB   3581.1 MiB        2402           for result in results:
    85                                                     # Visualize the results on the frame
    86   4425.0 MiB     38.1 MiB        1201               annotated_frame = result.plot()
```

This is with 1200 frames processed, where results variable increases 3581.1MB, while in the 900th, is only 2737MB. 
My computer resource manager indicates that the memory increases linearly in time.

**Comment by glenn-jocher** [comment]
@alexbarnadas, it seems like there might be an issue with memory not being released during the tracking process. To mitigate this, ensure you're not unintentionally holding references to large objects and allow Python's garbage collector to free up memory. If the problem persists, consider profiling your code to identify the exact source of the memory leak.

If you've confirmed that the memory increase is associated with the `results` variable and it's not due to accumulating references in your code, this might require a deeper investigation into the `track` method's implementation. Please open an issue on the Ultralytics YOLOv8 repo with the details of your memory profiling so that our team can look into it.

**Comment by alleszaehler** [comment]
I have exactly the same issue - with just 4 lines of code - after a minute 24GB of RAM are completely used ...

from ultralytics import YOLO
model = YOLO('yolov8m.pt'
source = 'rtsp:// ...'
results = model(source, show=True, conf=0.4, save=True)

**Comment by alexbarnadas** [comment]
> @alexbarnadas, it seems like there might be an issue with memory not being released during the tracking process. To mitigate this, ensure you're not unintentionally holding references to large objects and allow Python's garbage collector to free up memory. If the problem persists, consider profiling your code to identify the exact source of the memory leak.
> 
> If you've confirmed that the memory increase is associated with the `results` variable and it's not due to accumulating references in your code, this might require a deeper investigation into the `track` method's implementation. Please open an issue on the Ultralytics YOLOv8 repo with the details of your memory profiling so that our team can look into it.

My bad, I was stacking a variable derived from results at every frame, that’s why I was not seeing it. Thank you for taking it into account.

**Comment by glenn-jocher** [comment]
Hey @alexbarnadas, glad you figured it out! 😊 Storing large objects in variables indeed can sometimes lead us down that tricky path of memory issues. If anything else pops up or you have more questions, feel free to reach out. Happy coding with YOLOv8!

**Comment by alleszaehler** [comment]
With stream =True and a for-loop for the elements it runs fine :-)

from ultralytics import YOLO
model = YOLO('yolov8x.pt')
source = 'rtsp:// ...'

results = model(source, show=True, conf=0.4,save=True,**stream=True)**
for r in results:
    boxes = r.boxes
    masks=r.masks
    probs=r.probs

**Comment by glenn-jocher** [comment]
@alleszaehler that's fantastic to hear! 😊 It looks like using `stream=True` and iterating over the results works well for managing RAM usage effectively. Thanks for sharing your approach - it could definitely help others facing similar issues. Happy detecting with YOLOv8!

**Comment by gtk-gh** [comment]
I'm using a RTSP stream my code is like that :

```python
while index < 1500:
    index += 1
    success, frame = cap.read()
    if success:
        for result in model(frame, stream=True, device="cuda", conf=0.45, verbose=False):
            annoted_frame = result.plot()
        camerabuffer_bbox.append(annoted_frame)

cap.release()
```
So I'm using the stream option, and I don't stack any variable.
When I use memory-profiler : 

```
    26    552.7 MiB      0.0 MiB           1       index = 0
    27
    28  10203.6 MiB      0.0 MiB        1501       while index < 1500:
    29  10197.5 MiB      0.0 MiB        1500           index += 1
    30  10201.3 MiB   5916.0 MiB        1500           success, frame = cap.read()
    31  10201.3 MiB      0.0 MiB        1500           if success:
    32  10203.6 MiB   3721.0 MiB        3000               for result in model(frame, stream=True, device="cuda", conf=0.45, verbose=False):
    33  10203.6 MiB     13.8 MiB        1500                   annoted_frame = result.plot()
    34  10203.6 MiB      0.0 MiB        1500               camerabuffer_bbox.append(annoted_frame)
    35
    36  10198.0 MiB     -5.6 MiB           1       cap.release()
```

First of all i tough the issues was from opencv but when I run the same code without predicting I've got this memory usage :
```
    26    552.7 MiB      0.0 MiB           1       index = 0
    27
    28    665.7 MiB     -3.5 MiB        1501       while index < 1500:
    29    665.7 MiB     -3.4 MiB        1500           index += 1
    30    665.7 MiB    109.5 MiB        1500           success, frame = cap.read()
    31    659.7 MiB     -6.1 MiB           1       cap.release()
```
And when I type the bash command free -m I see my memory used increasing.
The program need to run days long but just after like 5 minutes all my ram memory is used and my server crash (64Gb)

I've tried to put the RTSP stream in model source but first i need to process the image with openCV and it didn't work for my test ..
