### ISSUE TITLE
How would I go converting the model to tfjs

### ISSUE THREAD

**Issue by JijaProGamer** [ultralytics/ultralytics#14135]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

It's a pretty known fact around here that

`from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO("yolov8n.pt")

# Export the model to TF.js format
model.export(format="tfjs") `

A code repeated a lot on the ultralytics documentation isn't actually working.

My question then is, how can I convert it to tfjs?

I've tried:

1) Keras/TF SavedModel -> TFJS directly, but ultralytics isn't formatting the model correctly and I get this error https://github.com/ultralytics/ultralytics/issues/8537

2) ONNX -> TF -> TFJS, but it requires the output name of the last layer, and I'm not sure what to put there

3) TLite -> ONNX -> TF -> TFJS, doesn't have the same problem as 2, but it seems like tf2onnx.convert is faulty

I cannot run it in onnx since onnx is extremely slow, taking over 200 ms (on the web) even with gpu, but a model of the same size in tfjs take <= 15ms (with NMS)

**Comment by JijaProGamer** [comment]
I've gotten a way to transform the model this way to tfjs, and I suggest the ultralytics devs do the same:

From your training, export it as such:

`
from ultralytics import YOLO
model = YOLO("yolov8n.pt")
model.export(format="tflite") 
`

Firstly, I'm in a google colab (python 3.10)

1) I have this script for installing utilities:

`
!pip install tensorflowjs
!pip install onnx2tf
!pip install tf2onnx
!pip install onnx
!pip install protobuf==3.20
!pip install onnx-graphsurgeon
!pip install sng4onnx
`

2) I have this code for copying the model from the previous training folder to a folder to modify it:

`
from google.colab import drive
drive.mount('/content/drive')

!mkdir /content/model/
!cp -r "/content/drive/MyDrive/Colab Notebooks/Brawl Stars Full Character-Circle Detection V2/" /content/saved_model
`

3) I transform the model to ONNX, then to SavedModel, then to a tfjs_graph, then put the output back on google drive:

`
!python -m tf2onnx.convert --opset 11 --tflite  /content/saved_model/best_float32.tflite --dequantize --output "/content/saved_model/best.onnx"
!onnx2tf -i /content/saved_model/best.onnx -ois input:1,3,172,382 -osd
!tensorflowjs_converter --input_format tf_saved_model --output_format tfjs_graph_model saved_model tfjs_model

!cp -r /content/tfjs_model "/content/drive/MyDrive/Colab Notebooks/Brawl Stars Full Character-Circle Detection V2/tfjs_model"
`

Now, here comes my issue.
I use this package for testing yolov8 on the web with tfjs: https://github.com/Hyuto/yolov8-tfjs
If I use the default yolo trained on coco from public/model then it detects good, but if I use the model transformed by me (which is a valid tfjs model, just the output is in a different order I belive) I get this error:


chunk-W43QHE4A.js?v=942153cf:1723 Uncaught (in promise) Error: The shape of dict['inputs_0'] provided in model.execute(dict) must be [1,384,3,192], but was [1,384,3,3]
    at Object.assert (chunk-W43QHE4A.js?v=942153cf:1723:11)
    at @tensorflow_tfjs.js?v=942153cf:24268:22
    at Array.forEach (<anonymous>)
    at GraphExecutor.checkInputShapeAndType (@tensorflow_tfjs.js?v=942153cf:24261:25)
    at GraphExecutor.execute (@tensorflow_tfjs.js?v=942153cf:23999:10)
    at GraphModel.execute (@tensorflow_tfjs.js?v=942153cf:24546:34)
    at detect (detect.js:128:25)
    at onLoad (App.jsx:69:25)
    at HTMLUnknownElement.callCallback2 (react-dom_client.js?v=942153cf:3575:22)
    at Object.invokeGuardedCallbackDev (react-dom_client.js?v=942153cf:3600:24)
    
    Any help is appreciated!

**Comment by JijaProGamer** [comment]
Or maybe export to tfjs works but I have the wrong version tf/onxx/ultralytics?

**Comment by JijaProGamer** [comment]
https://github.com/ultralytics/ultralytics/issues/9175

I've followed this and this fixed export to tfjs, it was a package version error.

**Comment by glenn-jocher** [comment]
Hello,

Thank you for your update and for sharing your solution! It's great to hear that you were able to resolve the issue by addressing the package version error. Ensuring compatibility between different package versions can indeed be crucial for a smooth export process.

For anyone else encountering similar issues, please ensure that you have the latest versions of the required packages installed. If you continue to face problems, providing a minimum reproducible example can significantly help in diagnosing and resolving the issue. You can refer to our guide on creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example).

If there are any further questions or if you need additional assistance, feel free to ask. We're here to help!

**Comment by DaCheng1823** [comment]
![image](https://github.com/user-attachments/assets/5c85aceb-64f3-42b8-ab2a-03dddbd008f7)
![image](https://github.com/user-attachments/assets/e4be34e5-aa1b-4e36-8517-79595fe869e2)
Hello, I would like to ask why the onnx model I converted looks like this. From the general onnx model diagram, is there a problem?

**Comment by pderrenger** [comment]
Thank you for reaching out. To better assist you, please ensure that you are using the latest versions of the Ultralytics and ONNX packages. If the issue persists, could you provide more details about the conversion process and any specific errors you encountered? This will help us diagnose the problem more effectively.
