### ISSUE TITLE
Which epoch is best.pt?

### ISSUE THREAD

**Issue by mandyxiaomeng** [ultralytics/ultralytics#14137]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, 

I wonder how to find out which epoch produced my 'best.pt' model?

**Comment by glenn-jocher** [comment]
@mandyxiaomeng hi there,

To determine which epoch produced your `best.pt` model, you can check the training logs that are saved during the training process. These logs typically contain detailed information about each epoch, including metrics like validation loss and accuracy.

If you have the training logs, look for the epoch with the best validation performance, as `best.pt` is saved based on the highest validation metric (e.g., mAP for object detection).

Alternatively, you can load the `best.pt` model and inspect its metadata using the following code snippet:

```python
from ultralytics import YOLO

# Load the best.pt model
model = YOLO('path/to/best.pt')

# Print the epoch information
print(f"Best model was saved at epoch: {model.epoch}")
```

This will display the epoch number at which the `best.pt` model was saved.

If you encounter any issues or need further assistance, please provide more details or a reproducible example as outlined [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

**Comment by mandyxiaomeng** [comment]
Hi,

Thank you for the answer!

I think my training log (results.csv) contains the following information:
`                epoch,         train/box_loss,         train/cls_loss,         train/dfl_loss,   metrics/precision(B),      metrics/recall(B),       metrics/mAP50(B),    metrics/mAP50-95(B),           val/box_loss,           val/cls_loss,           val/dfl_loss,                 lr/pg0,                 lr/pg1,                 lr/pg2`
                
Is the best.pt saved based on the highest metrics/mAP50(B)? or is it also considered preventing overfitting, so I should also look into the value/loss?

As for the code you provided, I was able to load the model, but unfortunately got the following error:
```  
raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'YOLO' object has no attribute 'epoch'
```

**Comment by glenn-jocher** [comment]
Hi @mandyxiaomeng,

Thank you for your follow-up! 😊

The `best.pt` model is typically saved based on the highest `metrics/mAP50(B)` during the validation phase, as this metric is a common indicator of model performance in object detection tasks. However, it's also important to monitor other metrics like `val/box_loss`, `val/cls_loss`, and `val/dfl_loss` to ensure that the model is not overfitting.

Regarding the error you encountered, it seems I made an oversight in my previous response. The `YOLO` object does not directly store the epoch information. Instead, you can find the epoch information in the training logs or by inspecting the `results.csv` file.

Here's a more accurate way to determine the epoch for `best.pt`:

1. Open the `results.csv` file and look for the epoch with the highest `metrics/mAP50(B)`.
2. Alternatively, you can use a script to parse the `results.csv` file and find the best epoch:

```python
import pandas as pd

# Load the training log
results = pd.read_csv('path/to/results.csv')

# Find the epoch with the highest mAP50(B)
best_epoch = results['metrics/mAP50(B)'].idxmax()
best_map50 = results['metrics/mAP50(B)'].max()

print(f"Best model was saved at epoch: {best_epoch} with mAP50(B): {best_map50}")
```

This script will help you identify the epoch at which the `best.pt` model was saved based on the highest `metrics/mAP50(B)`.

If you have any further questions or need additional assistance, feel free to ask! We're here to help. 🚀

**Comment by mandyxiaomeng** [comment]
I see! Thank you very much for the help!

**Comment by glenn-jocher** [comment]
You're welcome, @mandyxiaomeng! 😊

I'm glad I could help. If you have any more questions or run into any other issues, feel free to reach out. Remember, providing a reproducible example can greatly assist in diagnosing any problems you encounter. You can find more details on creating one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Also, make sure you're using the latest version of the Ultralytics packages to benefit from the latest features and bug fixes.

Happy training! 🚀

**Comment by glenn-jocher** [comment]
Thank you for pointing that out. You're correct; adding 1 to the index aligns the epoch numbering with the logs.

**Comment by sgaumi** [comment]
Hello,
If you want to know using only the `best.pt` (or any other .pt file from training), you can do
```
from ultralytics import YOLO

# Load the best.pt model
model = YOLO('path/to/best.pt')

# Print the epoch
print(f"Best model was saved at epoch: {model.ckpt['train_results']['epoch'][-1]}")
```

**Comment by glenn-jocher** [comment]
Thank you for your suggestion. However, the `YOLO` object doesn't directly store epoch information. You can find the best epoch by checking your training logs or `results.csv` file. If you need further assistance, feel free to ask!

**Comment by pgrudzinska** [comment]
> Hi @mandyxiaomeng,
> 
> Thank you for your follow-up! 😊
> 
> The `best.pt` model is selected based on the highest `fitness` value that is obtained by getting a weighted sum of multiple metrics:
> 
> https://github.com/ultralytics/ultralytics/blob/8154a27e9b332dd2dac7a107003462f0e20f6179/ultralytics/utils/metrics.py#L745-L748
> 
> Regarding the error you encountered, it seems I made an oversight in my previous response. The `YOLO` object does not directly store the epoch information. Instead, you can find the epoch information in the training logs or by inspecting the `results.csv` file.
> 
> Here's a more accurate way to determine the epoch for `best.pt`:
> 
> 1. Open the `results.csv` file and calculate fitness.
> 2. Alternatively, you can use a script to parse the `results.csv` file and find the best epoch:
> 
> ```python
> import pandas as pd
> 
> # Load the training log
> results = pd.read_csv('path/to/results.csv')
> 
> # Strip spaces
> results.columns = results.columns.str.strip()
> 
> # Calculate fitness
> results["fitness"] = results["metrics/mAP50(B)"] * 0.1 + results["metrics/mAP50-95(B)"] * 0.9
> 
> # Find the epoch with the highest fitness
> best_epoch = results['fitness'].idxmax() + 1
> 
> print(f"Best model was saved at epoch: {best_epoch}")
> ```
> 
> This script will help you identify the epoch at which the `best.pt` model was saved based on the highest `fitness`. But this only works for `Detect` and `OBB` models since `Segment` and `Pose` have additional mAP that require a separate fitness calculation.
> 
> If you have any further questions or need additional assistance, feel free to ask! We're here to help. 🚀

Hey Glenn,  is it possible to change weights for fitness?

**Comment by samrere** [comment]
> Hello, If you want to know using only the `best.pt` (or any other .pt file from training), you can do
> 
> ```
> from ultralytics import YOLO
> 
> # Load the best.pt model
> model = YOLO('path/to/best.pt')
> 
> # Print the epoch
> print(f"Best model was saved at epoch: {model.ckpt['train_results']['epoch'][-1]}")
> ```

This is incorrect as `model.ckpt['train_results']` saves same information as in results.csv, so `model.ckpt['train_results']['epoch'][-1]` will always be the last epoch. 

Not sure if this is correct, but I found `model.ckpt['train_metrics']` seems to save the metrics at best epoch. For a pose estimation task it looks something like:
```
{'metrics/precision(B)': 0.97211,
 'metrics/recall(B)': 0.97561,
 'metrics/mAP50(B)': 0.98939,
 'metrics/mAP50-95(B)': 0.93317,
 'metrics/precision(P)': 0.95318,
 'metrics/recall(P)': 0.92205,
 'metrics/mAP50(P)': 0.95058,
 'metrics/mAP50-95(P)': 0.65319,
 'val/box_loss': 0.3805,
 'val/pose_loss': 1.5847,
 'val/kobj_loss': 0.28558,
 'val/cls_loss': 0.2301,
 'val/dfl_loss': 0.83763,
 'fitness': 1.62172}
```
and then you can find which epoch by comparing the values with `results.csv` or `model.ckpt['train_results']`. You may also deduce the fitness calculation, so in this example `fitness = 0.1 x mAP50(B) + 0.9 x mAP50-95(B) + 0.1 x mAP50(P) + 0.9 x mAP50-95(P)`

**Comment by glenn-jocher** [comment]
You are correct that `model.ckpt['train_results']['epoch'][-1]` reflects the final epoch recorded in that specific checkpoint file, and thus differs between `

**Comment by Petros626** [comment]
> Just a note, I think it should be `best_epoch = results['metrics/mAP50(B)'].idxmax() + 1` because we count epochs from 1 but the first epoch is 0. This seemed to match up with what I was seeing in the logs.

Both returns the same epoch for me or was your point just the starting.
```python
best_epoch_50 = results['metrics/mAP50(B)'].idxmax() + 1
best_epoch = results['fitness'].idxmax() + 1
```

**Comment by horsto** [comment]
It would be really great to have an easier way of determining what is "best.pt" (I am running segmentation training). I do not have access to `model.ckpt['train_results']` and would need to run validation again to then - via `.metrics` find out which values match the `results.csv` output at which epoch. 

Any tips?

**Comment by Petros626** [comment]
You mean after training with the post-training validation? Then somewhere the values must be stored to finally calculate one best epoch directly after the training.

**Comment by horsto** [comment]
After training, yes. All metrics should be saved in `results.csv` but the algorithm to find / reproduce results of `best.pt` (the selection) is not clear to me (and ideally the epoch index should be saved alongside the selection of `best.pt`).

**Comment by Petros626** [comment]
You can take a look in my best_epoch.py in my forked repo.

**Comment by horsto** [comment]
@Petros626 Thank you, I found your [code](https://github.com/Petros626/ultralytics_yolov8-obb_ob_kitti/blob/c7f4a306ac0dcffdeb440177d63102ff69bc88ac/ultralytics/best_epoch.py). 


However, what does ultralytics do internally and for segmentation?

**Comment by Petros626** [comment]
What you mean ultralytics do internally? And what it should do for segmentation?

**Comment by horsto** [comment]
What is the algorithm ultralytics uses internally to determine "best". 
And segmentation results span both box and mask results, so 
```
    results["fitness"] = (
        results["metrics/mAP50(B)"] * 0.1
        + results["metrics/mAP70(B)"] * 0.1 
        + results["metrics/mAP50-95(B)"] * 0.9
```

won't do it.

**Comment by Petros626** [comment]
It's not an algorithm it's idmax() which searches the highest value among mAP50 or mAP70 in my case. The fitness is a weighted sum.

**Comment by horsto** [comment]
> It's not an algorithm it's idmax() which searches the highest value among mAP50 or mAP70 in my case. The fitness is a weighted sum. 

And once more (sorry if I'm not being clear!): I want to know how ultralytics calculates best - and how to retrieve the epoch. Thanks for showing me your weighted sum - but that's not what I'm asking for.

**Comment by Petros626** [comment]
The solution isn't here: https://github.com/ultralytics/ultralytics/issues/14137#issuecomment-2201432148?

**Comment by glenn-jocher** [comment]
@horsto For segmentation models, ultralytics uses the [`SegmentMetrics.fitness`](https://docs.ultralytics.com/reference/utils/metrics/#ultralytics.utils.metrics.SegmentMetrics.fitness) property which combines both box and mask metrics to determine the best epoch. The fitness calculation includes both bounding box mAP and segmentation mask mAP values, unlike detection models which only use box metrics.

You can find the best epoch for segmentation by parsing `results.csv` and calculating the combined fitness using both box and mask metrics, similar to how the internal fitness calculation works.
