### ISSUE TITLE
yolov8n onnx model outputs [1, 84, 8400 ] when using with onnxruntime

### ISSUE THREAD

**Issue by jifeng632** [ultralytics/ultralytics#14131]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

yolov8n onnx model outputs [1, 84, 8400 ] when using with onnxruntime, so i can't use it directly in mobile web app , it's also very slow. how to get the [100, 6] like results

**Comment by jifeng632** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/165781509/57e659b9-3d20-4557-9b6d-f840ccb5a4c4)

**Comment by Y-T-G** [comment]
Follow the example to create the post-processing function:

https://github.com/ultralytics/ultralytics/blob/266861e880f936802c862ee096c0423d6e84865f/examples/YOLOv8-OpenCV-ONNX-Python/main.py#L34

**Comment by jifeng632** [comment]
tks  let me try to convert the above code  into  js code , i need to deploy the js code into mobile device

**Comment by jifeng632** [comment]
can we export the onnx format model with nms directly , coz it will be very slow on mobile app with H5 as runtime

**Comment by jifeng632** [comment]
and i tried a lof of images, why its 8400  i dont know why 8400 bbox

**Comment by Y-T-G** [comment]
> can we export the onnx format model with nms directly , coz it will be very slow on mobile app with H5 as runtime

You can try adding `nms=True` during export. But not sure if it works for onnx export.

**Comment by jifeng632** [comment]
nms=true, 
doesnt work

**Comment by glenn-jocher** [comment]
Hello,

Thank you for your patience and for trying out the suggestions. Unfortunately, the `nms=True` option is not supported for ONNX export directly. This means that the Non-Maximum Suppression (NMS) needs to be handled separately in your application code.

Regarding the output shape `[1, 84, 8400]`, the `8400` represents the total number of anchor boxes used by the model. This is a design choice in the YOLOv8 architecture to ensure comprehensive coverage of the image for object detection.

To address the performance concerns on mobile devices, you can consider the following options:

1. **Post-Processing in JavaScript**:
   Convert the provided Python post-processing code to JavaScript. This will allow you to handle NMS and other post-processing steps directly on the client side. Here's a basic structure to get you started:

   ```javascript
   function postprocess(output, confThreshold = 0.25, iouThreshold = 0.45) {
       // Reshape and process the output
       // Implement NMS and other post-processing steps here
   }

   // Example usage
   const output = ...; // Your model output
   const detections = postprocess(output);
   console.log(detections);
   ```

2. **Quantization**:
   Use quantization techniques to reduce the model size and improve inference speed. You can export the model with `int8` quantization if supported by your deployment framework.

3. **Edge Computing**:
   Offload the heavy computation to an edge server and send only the necessary data to the mobile device. This can significantly reduce the processing load on the mobile device.

For more detailed instructions on exporting and deploying YOLOv8 models, please refer to the [Ultralytics documentation](https://docs.ultralytics.com/integrations/ncnn/).

If you encounter any further issues, please ensure you are using the latest versions of the packages and provide a reproducible example if the problem persists. You can find more information on creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions or need further assistance. 😊
