### ISSUE TITLE
Check classes from onnx version of yolov8 (custom trained).

### ISSUE THREAD

**Issue by Nas-Azzam** [ultralytics/ultralytics#14145]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

How do we get classes from onnx exported version of yolov8 model model. 

### Additional

I tried this code but got a lot of errors.

https://github.com/ultralytics/yolov5/discussions/11240

import onnx,ast
m = onnx.load(<ONNX file>)
props = { p.key : p.value for p in m.metadata_props }
if 'names' in props:
    names = ast.literal_eval(props['names'])

import cv2

model = cv2.dnn.readNetFromONNX("path/to/yolov8.onnx")

layer_names = model.getLayerNames()
output_layers = [layer_names[i[0] - 1] for i in model.getUnconnectedOutLayers()]

num_classes = model.getLayer(output_layers[0]).outputShape[1]

print("Number of classes:", num_classes)

**Comment by glenn-jocher** [comment]
@Nas-Azzam hello,

Thank you for reaching out with your question! To retrieve the class names from an ONNX-exported YOLOv8 model, you can follow a slightly different approach. The metadata properties of the ONNX model should contain the class names, but it seems the method you tried encountered some issues. Here’s a refined approach to help you extract the class names:

First, ensure you have the latest versions of the necessary packages:
```bash
pip install onnx onnxruntime
```

Next, you can use the following code to load the ONNX model and extract the class names from the metadata:

```python
import onnx
import ast

# Load the ONNX model
model_path = "path/to/yolov8.onnx"
model = onnx.load(model_path)

# Extract metadata properties
props = {p.key: p.value for p in model.metadata_props}

# Retrieve class names
if 'names' in props:
    class_names = ast.literal_eval(props['names'])
    print("Class names:", class_names)
else:
    print("Class names not found in the metadata properties.")
```

This code snippet should help you extract the class names directly from the ONNX model's metadata. If you continue to encounter errors, please provide a minimum reproducible example of your issue. This will help us diagnose the problem more effectively. You can find guidance on creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, ensure that you are using the latest version of the YOLOv8 model and the ONNX runtime to avoid any compatibility issues.

Feel free to reach out if you have any further questions or run into any issues!
