### ISSUE TITLE
add last_hidden_state function get last layer vector

### ISSUE THREAD

**Issue by blackhu** [ultralytics/ultralytics#14156]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

add last_hidden_state  function get last layer emabdding

### Use case

This emabdding can be used for image similarity detection

### Additional

-

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@blackhu hi there,

Thank you for your suggestion! Adding a `last_hidden_state` function to retrieve the last layer embeddings for image similarity detection is an interesting idea. This could indeed be valuable for various applications.

To help us better understand and implement this feature, could you please provide a bit more detail on your use case? Additionally, if you have any example code or a minimum reproducible example, that would be very helpful. You can refer to our guide on creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Also, please ensure you are using the latest version of the Ultralytics YOLO package to avoid any compatibility issues.

Looking forward to your input!

**Comment by Burhan-Q** [comment]
See the `embed` argument for prediction mode in the [inference arguments of the docs](https://docs.ultralytics.com/modes/predict/#inference-arguments).
