### ISSUE TITLE
Annotation for keypoint detection

### ISSUE THREAD

**Issue by fschvart** [ultralytics/ultralytics#1415]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I have a custom keypoint detection dataset I want to train a YOLO v8 model on. (not body poses)
I was wondering how should the annotations txt file format look like?

**Comment by pderrenger** [comment]
@fschvart hi there!

For keypoint detection with YOLOv8, the annotations file format should contain the coordinates of the keypoints in addition to the bounding box coordinates. Each line in the annotations file should include the class index, center coordinates of the bounding box, its width and height, and then the coordinates of each keypoint.

I hope this helps! If you have further questions or need additional assistance, feel free to ask. Good luck with your YOLOv8 model training!

**Comment by glenn-jocher** [comment]
Hello @pderrenger 👋,

For keypoint detection, your annotation files should include both bounding box and keypoint information. Each annotation line should start with the class index, followed by the bounding box center coordinates (x, y), width, and height, and then the keypoint coordinates (x, y) for each keypoint.

If you need more detailed guidance, please refer to our documentation on pose/keypoint estimation at https://docs.ultralytics.com/tasks/pose.

Best of luck with your training! 🚀
