### ISSUE TITLE
Hi, is yolov8 is anchors free?

### ISSUE THREAD

**Issue by sdimantsd** [ultralytics/ultralytics#1416]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question
I am training yolov8, and in one of my datasets, the results are worse then the training in yolov5.
In yolov5, the network adjust the anchors, but I dont see it in yolov8, so, is yolov8 is anchors free?

**Comment by JustasBart** [comment]
Hi @sdimantsd yolov8 is indeed anchor-free, good luck! :rocket:

**Comment by sdimantsd** [comment]
Thanks

**Comment by pderrenger** [comment]
@sdimantsd you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with your YOLOv8 training! 🚀
