### ISSUE TITLE
How to reduce to 100 epochs without retraining after 200 epochs of simulation?

### ISSUE THREAD

**Issue by tien0717** [ultralytics/ultralytics#14165]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to reduce to 100 epochs without retraining after 200 epochs of simulation?

**Comment by glenn-jocher** [comment]
@tien0717 hello!

To reduce the number of epochs to 100 without retraining after already completing 200 epochs, you can simply use the weights from the 100th epoch. If you have saved the model checkpoints during training, you should have a checkpoint file for each epoch. 

Here's how you can do it:

1. **Locate the Checkpoint**: Find the checkpoint file corresponding to the 100th epoch. It should be named something like `epoch_100.pt` or similar, depending on your configuration.

2. **Load the Checkpoint**: Use this checkpoint to initialize your model. This way, you can continue using the model as if it was trained for only 100 epochs.

Here's an example in Python:

```python
from ultralytics import YOLO

# Load the model from the 100th epoch checkpoint
model = YOLO('path/to/epoch_100.pt')

# Now you can use this model for further validation, prediction, or fine-tuning
results = model.val(data='coco128.yaml')  # Example validation
```

If you didn't save intermediate checkpoints, unfortunately, you would need to retrain the model up to the desired number of epochs.

For future training sessions, consider enabling the `save_period` parameter to save checkpoints at regular intervals:

```bash
yolo train data=coco128.yaml model=yolov8n.pt epochs=200 save_period=10
```

This will save a checkpoint every 10 epochs, making it easier to revert to an earlier state if needed.

Feel free to reach out if you have any more questions! 😊

**Comment by tien0717** [comment]
@glenn-jocher If I finish training for 200epoch, but I only want to interrupt the training at 100epoch, how can I redraw my results graph to only 100epoch?(including recall, precision indicators, confusion matrix etc.)

**Comment by glenn-jocher** [comment]
Hello @tien0717,

To redraw your results graph to reflect only the first 100 epochs, you can follow these steps:

1. **Locate the Training Logs**: Find the training logs that were generated during your training process. These logs typically contain the metrics for each epoch, including recall, precision, and confusion matrix data.

2. **Extract the First 100 Epochs**: Extract the data corresponding to the first 100 epochs from these logs. This data will be used to recreate your graphs.

3. **Plot the Metrics**: Use a plotting library like Matplotlib to plot the metrics for the first 100 epochs. Here's an example in Python:

```python
import matplotlib.pyplot as plt
import json

# Load your training log (assuming it's in JSON format)
with open('path/to/training_log.json', 'r') as f:
    log_data = json.load(f)

# Extract metrics for the first 100 epochs
epochs = list(range(1, 101))
precision = [log_data['precision'][epoch] for epoch in epochs]
recall = [log_data['recall'][epoch] for epoch in epochs]

# Plot precision and recall
plt.figure(figsize=(10, 5))
plt.plot(epochs, precision, label='Precision')
plt.plot(epochs, recall, label='Recall')
plt.xlabel('Epoch')
plt.ylabel('Metric')
plt.title('Precision and Recall over First 100 Epochs')
plt.legend()
plt.show()
```

4. **Confusion Matrix**: If you have confusion matrix data for each epoch, you can similarly extract and plot it for the 100th epoch.

If you haven't saved intermediate logs or metrics, you might need to retrain the model up to the 100th epoch and ensure you save the logs this time.

For future training, consider enabling logging and saving intermediate checkpoints to make this process easier. You can use the `save_period` parameter to save checkpoints at regular intervals:

```bash
yolo train data=coco128.yaml model=yolov8n.pt epochs=200 save_period=10
```

This will save a checkpoint every 10 epochs, allowing you to easily revert to an earlier state if needed.

If you encounter any issues or need further assistance, please ensure you are using the latest version of the Ultralytics packages and provide a minimum reproducible example as outlined [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Best regards and happy training! 😊
