### ISSUE TITLE
UnboundLocalError for 'ckpt_file' while running model.tune() 

### ISSUE THREAD

**Issue by srik15** [ultralytics/ultralytics#14166]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Hyperparameter Tuning

### Bug

Tuner: Starting iteration 2/30 with hyperparameters: {'lr0': 0.01, 'lrf': 0.00761, 'momentum': 0.98, 'weight_decay': 0.00045, 'warmup_epochs': 3.69135, 'warmup_momentum': 0.71979, 'box': 7.5, 'cls': 0.45748, 'dfl': 1.5, 'hsv_h': 0.01259, 'hsv_s': 0.7, 'hsv_v': 0.47212, 'degrees': 0.0, 'translate': 0.10296, 'scale': 0.48352, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0, 'copy_paste': 0.0}
WARNING ❌️ training failure for hyperparameter tuning iteration 2
Command '['yolo', 'train', 'task=detect', 'mode=train', 'model=yolov8n.pt', 'data=content/datasets/Final_dataset-2/data.yaml', 'epochs=5', 'patience=50', 'batch=16', 'imgsz=640', 'save=False', 'save_period=-1', 'cache=False', 'device=None', 'workers=8', 'project=None', 'name=None', 'exist_ok=False', 'pretrained=True', 'optimizer=AdamW', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'rect=False', 'cos_lr=False', 'close_mosaic=10', 'resume=False', 'amp=True', 'fraction=1.0', 'profile=False', 'freeze=None', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=False', 'split=val', 'save_json=False', 'save_hybrid=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=False', 'source=None', 'show=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'show_labels=True', 'show_conf=True', 'vid_stride=1', 'stream_buffer=False', 'line_width=None', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'boxes=True', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=False', 'opset=None', 'workspace=4', 'nms=False', 'lr0=0.01', 'lrf=0.00761', 'momentum=0.98', 'weight_decay=0.00045', 'warmup_epochs=3.69135', 'warmup_momentum=0.71979', 'warmup_bias_lr=0.1', 'box=7.5', 'cls=0.45748', 'dfl=1.5', 'pose=12.0', 'kobj=1.0', 'label_smoothing=0.0', 'nbs=64', 'hsv_h=0.01259', 'hsv_s=0.7', 'hsv_v=0.47212', 'degrees=0.0', 'translate=0.10296', 'scale=0.48352', 'shear=0.0', 'perspective=0.0', 'flipud=0.0', 'fliplr=0.5', 'mosaic=1.0', 'mixup=0.0', 'copy_paste=0.0', 'cfg=None', 'tracker=botsort.yaml']' returned non-zero exit status 1.
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
[<ipython-input-6-56fddac40ba8>](https://localhost:8080/#) in <cell line: 7>()
      5 
      6 # Tune hyperparameters on COCO8 for 30 epochs
----> 7 model.tune(data="content/datasets/Final_dataset-2/data.yaml", epochs=5, iterations=30, optimizer="AdamW", plots=False, save=False, val=False)

1 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/tuner.py](https://localhost:8080/#) in __call__(self, model, iterations, cleanup)
    205                     shutil.copy2(ckpt, self.tune_dir / 'weights')
    206             elif cleanup:
--> 207                 shutil.rmtree(ckpt_file.parent)  # remove iteration weights/ dir to reduce storage space
    208 
    209             # Plot tune results

**UnboundLocalError**: local variable 'ckpt_file' referenced before assignment

### Environment

Ultralytics YOLOv8.0.196 🚀 Python-3.10.12 torch-2.3.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 30.4/78.2 GB disk)

### Minimal Reproducible Example

from ultralytics import YOLO

# Initialize the YOLO model
model = YOLO("yolov8n.pt")

# Tune hyperparameters on COCO8 for 30 epochs
model.tune(data="coco.yaml", epochs=5, iterations=30, optimizer="AdamW", plots=False, save=False, val=False)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@srik15 thank you for reporting this issue and providing detailed information. The `UnboundLocalError` for `ckpt_file` during hyperparameter tuning appears to be a bug in the code. To help us diagnose and resolve this issue, could you please provide a minimal reproducible example? This will allow us to replicate the problem on our end. You can find guidance on creating a minimal reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure you are using the latest version of the Ultralytics YOLO package, as updates often include bug fixes and improvements. You can update to the latest version using the following command:

```bash
pip install --upgrade ultralytics
```

In the meantime, here's a quick workaround you can try to avoid the `UnboundLocalError`. Modify the `tuner.py` file to ensure `ckpt_file` is defined before it is referenced:

```python
# Ensure ckpt_file is defined
ckpt_file = None

# Your existing code
if cleanup and ckpt_file:
    shutil.rmtree(ckpt_file.parent)  # remove iteration weights/ dir to reduce storage space
```

If the issue persists after trying the above steps, please let us know, and we will further investigate. Thank you for your patience and for contributing to the improvement of Ultralytics YOLO! 🚀

For more detailed guidance on hyperparameter tuning, you can refer to our [Hyperparameter Tuning Guide](https://docs.ultralytics.com/guides/hyperparameter-tuning/).

Feel free to reach out if you have any more questions or need further assistance! 😊

**Comment by rhalder2023** [comment]
> @srik15 thank you for reporting this issue and providing detailed information. The `UnboundLocalError` for `ckpt_file` during hyperparameter tuning appears to be a bug in the code. To help us diagnose and resolve this issue, could you please provide a minimal reproducible example? This will allow us to replicate the problem on our end. You can find guidance on creating a minimal reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> Additionally, please ensure you are using the latest version of the Ultralytics YOLO package, as updates often include bug fixes and improvements. You can update to the latest version using the following command:
> 
> ```shell
> pip install --upgrade ultralytics
> ```
> 
> In the meantime, here's a quick workaround you can try to avoid the `UnboundLocalError`. Modify the `tuner.py` file to ensure `ckpt_file` is defined before it is referenced:
> 
> ```python
> # Ensure ckpt_file is defined
> ckpt_file = None
> 
> # Your existing code
> if cleanup and ckpt_file:
>     shutil.rmtree(ckpt_file.parent)  # remove iteration weights/ dir to reduce storage space
> ```
> 
> If the issue persists after trying the above steps, please let us know, and we will further investigate. Thank you for your patience and for contributing to the improvement of Ultralytics YOLO! 🚀
> 
> For more detailed guidance on hyperparameter tuning, you can refer to our [Hyperparameter Tuning Guide](https://docs.ultralytics.com/guides/hyperparameter-tuning/).
> 
> Feel free to reach out if you have any more questions or need further assistance! 😊

Hi, I am getting the same error, when i run the model.tune() with the resume=True, but the error doesn't pop up if that argument is false, can i confirm the location of tune.py, is it inside the utils directory because, i just saw a ray_tune function, i wasnt sure if that is the actual tuner?
