### ISSUE TITLE
Picking instance segmentation in roboflow for yolov8-obb 

### ISSUE THREAD

**Issue by KennethEladistu** [ultralytics/ultralytics#14172]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/ultralytics/ultralytics/assets/168053014/e44087d3-5e96-4506-8d55-66560e2c336c)

Hello is it ok if I chose "Instance Segmentation" for yolov8-obb for annotating my data sets I will still be using the polygon tool. I just need tio get the XY coordinates of my data set.

**Comment by glenn-jocher** [comment]
@KennethEladistu hello!

Yes, you can certainly use "Instance Segmentation" for annotating your datasets with YOLOv8-OBB (Oriented Bounding Boxes). Using the polygon tool to get the XY coordinates is a valid approach. YOLOv8-OBB models are designed to handle oriented bounding boxes, and the polygon annotations will provide the necessary coordinates for training and inference.

If you encounter any issues or need further assistance, please ensure you are using the latest version of the Ultralytics packages. Additionally, if you run into any specific problems, providing a minimum reproducible example can greatly help in diagnosing and resolving the issue. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Happy annotating and training! 🚀

**Comment by KennethEladistu** [comment]
> @KennethEladistu hello!
> 
> Yes, you can certainly use "Instance Segmentation" for annotating your datasets with YOLOv8-OBB (Oriented Bounding Boxes). Using the polygon tool to get the XY coordinates is a valid approach. YOLOv8-OBB models are designed to handle oriented bounding boxes, and the polygon annotations will provide the necessary coordinates for training and inference.
> 
> If you encounter any issues or need further assistance, please ensure you are using the latest version of the Ultralytics packages. Additionally, if you run into any specific problems, providing a minimum reproducible example can greatly help in diagnosing and resolving the issue. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> Happy annotating and training! 🚀

![image](https://github.com/ultralytics/ultralytics/assets/168053014/54a98f28-8d6a-4749-a56b-28da59b6cc81)

Hello Currently I integrated the yolov8-obb model for detecting parcels and with XYZ. My only problem is that it only reads the X and Z and it gives the ORB coordinates in the terminal but I'm not sure if its correct. How can I display the XYZ of the bounding box when it detects an object. I am currently also using OAK-D-Pro 


This is my code:

`import cv2
import depthai as dai
from submodule.calc import HostSpatialsCalc
from submodule.utility import *
import numpy as np
import math
from ultralytics import YOLO  # Assuming you have YOLOv8 with OBB support

# Load a pretrained YOLOv8 OBB model (ensure it's trained for OBB)
model = YOLO("C:/Users/KennethAaronEladistu/oak_d/oak_d/best(3).pt")  # Replace with your model path

# Create pipeline
pipeline = dai.Pipeline()

# Define source and output (RGB camera)
camRgb = pipeline.create(dai.node.ColorCamera)
xoutRgb = pipeline.create(dai.node.XLinkOut)
xoutRgb.setStreamName("rgb")

# Properties
camRgb.setPreviewSize(640, 640)
camRgb.setResolution(dai.ColorCameraProperties.SensorResolution.THE_1080_P)
camRgb.setInterleaved(False)
camRgb.setColorOrder(dai.ColorCameraProperties.ColorOrder.RGB)

# Linking (RGB camera)
camRgb.preview.link(xoutRgb.input)

# Define sources and outputs (Stereo Depth)
monoLeft = pipeline.create(dai.node.MonoCamera)
monoRight = pipeline.create(dai.node.MonoCamera)
stereo = pipeline.create(dai.node.StereoDepth)

# Properties (Stereo Depth)
monoLeft.setResolution(dai.MonoCameraProperties.SensorResolution.THE_400_P)
monoLeft.setBoardSocket(dai.CameraBoardSocket.LEFT)
monoRight.setResolution(dai.MonoCameraProperties.SensorResolution.THE_400_P)
monoRight.setBoardSocket(dai.CameraBoardSocket.RIGHT)

stereo.initialConfig.setConfidenceThreshold(255)
stereo.setDefaultProfilePreset(dai.node.StereoDepth.PresetMode.HIGH_DENSITY)
stereo.setDepthAlign(camera=dai.CameraBoardSocket.CAM_A)
stereo.setLeftRightCheck(True)
stereo.setOutputSize(monoLeft.getResolutionWidth(), monoLeft.getResolutionHeight())
stereo.setSubpixel(False)
stereo.setExtendedDisparity(True)

# Linking (Stereo Depth)
monoLeft.out.link(stereo.left)
monoRight.out.link(stereo.right)

xoutDepth = pipeline.create(dai.node.XLinkOut)
xoutDepth.setStreamName("depth")
stereo.depth.link(xoutDepth.input)

xoutDepth = pipeline.create(dai.node.XLinkOut)
xoutDepth.setStreamName("disp")
stereo.disparity.link(xoutDepth.input)

# Connect to device and start pipeline
with dai.Device(pipeline) as device:
    depthQueue = device.getOutputQueue(name="depth", maxSize=10, blocking=False)
    dispQ = device.getOutputQueue(name="disp", maxSize=10, blocking=False)
    qRgb = device.getOutputQueue(name="rgb", maxSize=4, blocking=False)

    text = TextHelper()
    rgbtext = TextHelper()
    hostSpatials = HostSpatialsCalc(device)
    y = 200
    x = 300
    w = 400
    h = 5
    delta = 5

    hostSpatials.setDeltaRoi(delta)

    print("Use 'r' and 'f' to change ROI size.")

    while True:
        inRgb = qRgb.get()  # Blocking call for new RGB frame
        depthData = depthQueue.get()
        frame = inRgb.getCvFrame()
      
        
        results = model.predict(source=frame, classes=[1])  # Filter to only detect class 1 (parcels)

        try:
            for result in results:
             if hasattr(result, 'obb'):
                xmin = int(result.obb.xyxy[0][0])
                ymin = int(result.obb.xyxy[0][1])
                xmax = int(result.obb.xyxy[0][2])
                ymax = int(result.obb.xyxy[0][3])
                rgbtext.rectangle(frame, (xmin, ymin), (xmax, ymax))
                # rgbxmin = int(result.boxes.xyxy[0,0])
                # rgbymin = int(result.boxes.xyxy[0,1])
                # rgbxmax = int(result.boxes.xyxy[0,2])
                # rgbymax = int(result.boxes.xyxy[0,3])
                print(f"OBB Coordinates: {xmin}, {ymin}, {xmax}, {ymax}")
            
        except:
            print("nothing detected")

        spatials, centroid = hostSpatials.calc_spatials(depthData, (x,y)) # centroid == x/y in our case

        # Get disparity frame for nicer depth visualization
        disp = dispQ.get().getFrame()
        disp = (disp * (255 / stereo.initialConfig.getMaxDisparity())).astype(np.uint8)
        disp = cv2.applyColorMap(disp, cv2.COLORMAP_JET)

        text.rectangle(disp, (x-delta, y-delta), (x+delta, y+delta))
        text.putText(disp, "X: " + ("{:.1f}mm".format(spatials['x']) if not math.isnan(spatials['x']) else "--"), (x + 10, y + 20))
        text.putText(disp, "Y: " + ("{:.1f}mm".format(spatials['y']) if not math.isnan(spatials['y']) else "--"), (x + 10, y + 35))
        text.putText(disp, "Z: " + ("{:.1f}mm".format(spatials['z']) if not math.isnan(spatials['z']) else "--"), (x + 10, y + 50))

        # # draw bounding box 
        # rgbtext.rectangle(frame, (x-w, y-h), (x+w, y+h))
      
        # Show the frame
        cv2.imshow("depth", disp)
        cv2.imshow("rgb", frame)
        
        key = cv2.waitKey(1)
        if key == ord('q'):
            break

        elif key == ord('r'): # Increase Delta
            if delta < 50:
                delta += 1
                hostSpatials.setDeltaRoi(delta)

        elif key == ord('f'): # Decrease Delta
            if 3 < delta:
                delta -= 1
                hostSpatials.setDeltaRoi(delta)`

**Comment by glenn-jocher** [comment]
Hello @KennethEladistu,

Thank you for sharing your code and providing detailed information about your setup. It looks like you're making great progress with integrating YOLOv8-OBB for detecting parcels using the OAK-D-Pro.

To display the XYZ coordinates of the bounding box when an object is detected, you can modify your code to calculate the spatial coordinates for each detected object and then overlay this information on the frame. Here's a refined version of your code that includes these enhancements:

```python
import cv2
import depthai as dai
from submodule.calc import HostSpatialsCalc
from submodule.utility import *
import numpy as np
import math
from ultralytics import YOLO  # Assuming you have YOLOv8 with OBB support

# Load a pretrained YOLOv8 OBB model (ensure it's trained for OBB)
model = YOLO("C:/Users/KennethAaronEladistu/oak_d/oak_d/best(3).pt")  # Replace with your model path

# Create pipeline
pipeline = dai.Pipeline()

# Define source and output (RGB camera)
camRgb = pipeline.create(dai.node.ColorCamera)
xoutRgb = pipeline.create(dai.node.XLinkOut)
xoutRgb.setStreamName("rgb")

# Properties
camRgb.setPreviewSize(640, 640)
camRgb.setResolution(dai.ColorCameraProperties.SensorResolution.THE_1080_P)
camRgb.setInterleaved(False)
camRgb.setColorOrder(dai.ColorCameraProperties.ColorOrder.RGB)

# Linking (RGB camera)
camRgb.preview.link(xoutRgb.input)

# Define sources and outputs (Stereo Depth)
monoLeft = pipeline.create(dai.node.MonoCamera)
monoRight = pipeline.create(dai.node.MonoCamera)
stereo = pipeline.create(dai.node.StereoDepth)

# Properties (Stereo Depth)
monoLeft.setResolution(dai.MonoCameraProperties.SensorResolution.THE_400_P)
monoLeft.setBoardSocket(dai.CameraBoardSocket.LEFT)
monoRight.setResolution(dai.MonoCameraProperties.SensorResolution.THE_400_P)
monoRight.setBoardSocket(dai.CameraBoardSocket.RIGHT)

stereo.initialConfig.setConfidenceThreshold(255)
stereo.setDefaultProfilePreset(dai.node.StereoDepth.PresetMode.HIGH_DENSITY)
stereo.setDepthAlign(camera=dai.CameraBoardSocket.CAM_A)
stereo.setLeftRightCheck(True)
stereo.setOutputSize(monoLeft.getResolutionWidth(), monoLeft.getResolutionHeight())
stereo.setSubpixel(False)
stereo.setExtendedDisparity(True)

# Linking (Stereo Depth)
monoLeft.out.link(stereo.left)
monoRight.out.link(stereo.right)

xoutDepth = pipeline.create(dai.node.XLinkOut)
xoutDepth.setStreamName("depth")
stereo.depth.link(xoutDepth.input)

xoutDepth = pipeline.create(dai.node.XLinkOut)
xoutDepth.setStreamName("disp")
stereo.disparity.link(xoutDepth.input)

# Connect to device and start pipeline
with dai.Device(pipeline) as device:
    depthQueue = device.getOutputQueue(name="depth", maxSize=10, blocking=False)
    dispQ = device.getOutputQueue(name="disp", maxSize=10, blocking=False)
    qRgb = device.getOutputQueue(name="rgb", maxSize=4, blocking=False)

    text = TextHelper()
    rgbtext = TextHelper()
    hostSpatials = HostSpatialsCalc(device)
    delta = 5

    hostSpatials.setDeltaRoi(delta)

    print("Use 'r' and 'f' to change ROI size.")

    while True:
        inRgb = qRgb.get()  # Blocking call for new RGB frame
        depthData = depthQueue.get()
        frame = inRgb.getCvFrame()
      
        results = model.predict(source=frame, classes=[1])  # Filter to only detect class 1 (parcels)

        try:
            for result in results:
                if hasattr(result, 'obb'):
                    xmin = int(result.obb.xyxy[0][0])
                    ymin = int(result.obb.xyxy[0][1])
                    xmax = int(result.obb.xyxy[0][2])
                    ymax = int(result.obb.xyxy[0][3])
                    rgbtext.rectangle(frame, (xmin, ymin), (xmax, ymax))
                    print(f"OBB Coordinates: {xmin}, {ymin}, {xmax}, {ymax}")

                    # Calculate spatial coordinates
                    center_x = (xmin + xmax) // 2
                    center_y = (ymin + ymax) // 2
                    spatials, centroid = hostSpatials.calc_spatials(depthData, (center_x, center_y))
                    text.putText(frame, f"X: {spatials['x']:.1f}mm", (xmin, ymin - 20))
                    text.putText(frame, f"Y: {spatials['y']:.1f}mm", (xmin, ymin - 10))
                    text.putText(frame, f"Z: {spatials['z']:.1f}mm", (xmin, ymin))
            
        except Exception as e:
            print(f"Error: {e}")

        # Get disparity frame for nicer depth visualization
        disp = dispQ.get().getFrame()
        disp = (disp * (255 / stereo.initialConfig.getMaxDisparity())).astype(np.uint8)
        disp = cv2.applyColorMap(disp, cv2.COLORMAP_JET)

        text.rectangle(disp, (center_x-delta, center_y-delta), (center_x+delta, center_y+delta))
        text.putText(disp, f"X: {spatials['x']:.1f}mm", (center_x + 10, center_y + 20))
        text.putText(disp, f"Y: {spatials['y']:.1f}mm", (center_x + 10, center_y + 35))
        text.putText(disp, f"Z: {spatials['z']:.1f}mm", (center_x + 10, center_y + 50))

        # Show the frame
        cv2.imshow("depth", disp)
        cv2.imshow("rgb", frame)
        
        key = cv2.waitKey(1)
        if key == ord('q'):
            break

        elif key == ord('r'):  # Increase Delta
            if delta < 50:
                delta += 1
                hostSpatials.setDeltaRoi(delta)

        elif key == ord('f'):  # Decrease Delta
            if 3 < delta:
                delta -= 1
                hostSpatials.setDeltaRoi(delta)
```

This code calculates the spatial coordinates (X, Y, Z) for the center of each detected object and overlays this information on the RGB frame. It also displays the depth information in a separate window.

If you encounter any issues or need further assistance, please ensure you are using the latest version of the Ultralytics packages. Additionally, providing a minimum reproducible example can greatly help in diagnosing and resolving any issues. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Happy coding! 🚀

**Comment by KennethEladistu** [comment]
> Hello @KennethEladistu,
> 
> Thank you for sharing your code and providing detailed information about your setup. It looks like you're making great progress with integrating YOLOv8-OBB for detecting parcels using the OAK-D-Pro.
> 
> To display the XYZ coordinates of the bounding box when an object is detected, you can modify your code to calculate the spatial coordinates for each detected object and then overlay this information on the frame. Here's a refined version of your code that includes these enhancements:
> 
> ```python
> import cv2
> import depthai as dai
> from submodule.calc import HostSpatialsCalc
> from submodule.utility import *
> import numpy as np
> import math
> from ultralytics import YOLO  # Assuming you have YOLOv8 with OBB support
> 
> # Load a pretrained YOLOv8 OBB model (ensure it's trained for OBB)
> model = YOLO("C:/Users/KennethAaronEladistu/oak_d/oak_d/best(3).pt")  # Replace with your model path
> 
> # Create pipeline
> pipeline = dai.Pipeline()
> 
> # Define source and output (RGB camera)
> camRgb = pipeline.create(dai.node.ColorCamera)
> xoutRgb = pipeline.create(dai.node.XLinkOut)
> xoutRgb.setStreamName("rgb")
> 
> # Properties
> camRgb.setPreviewSize(640, 640)
> camRgb.setResolution(dai.ColorCameraProperties.SensorResolution.THE_1080_P)
> camRgb.setInterleaved(False)
> camRgb.setColorOrder(dai.ColorCameraProperties.ColorOrder.RGB)
> 
> # Linking (RGB camera)
> camRgb.preview.link(xoutRgb.input)
> 
> # Define sources and outputs (Stereo Depth)
> monoLeft = pipeline.create(dai.node.MonoCamera)
> monoRight = pipeline.create(dai.node.MonoCamera)
> stereo = pipeline.create(dai.node.StereoDepth)
> 
> # Properties (Stereo Depth)
> monoLeft.setResolution(dai.MonoCameraProperties.SensorResolution.THE_400_P)
> monoLeft.setBoardSocket(dai.CameraBoardSocket.LEFT)
> monoRight.setResolution(dai.MonoCameraProperties.SensorResolution.THE_400_P)
> monoRight.setBoardSocket(dai.CameraBoardSocket.RIGHT)
> 
> stereo.initialConfig.setConfidenceThreshold(255)
> stereo.setDefaultProfilePreset(dai.node.StereoDepth.PresetMode.HIGH_DENSITY)
> stereo.setDepthAlign(camera=dai.CameraBoardSocket.CAM_A)
> stereo.setLeftRightCheck(True)
> stereo.setOutputSize(monoLeft.getResolutionWidth(), monoLeft.getResolutionHeight())
> stereo.setSubpixel(False)
> stereo.setExtendedDisparity(True)
> 
> # Linking (Stereo Depth)
> monoLeft.out.link(stereo.left)
> monoRight.out.link(stereo.right)
> 
> xoutDepth = pipeline.create(dai.node.XLinkOut)
> xoutDepth.setStreamName("depth")
> stereo.depth.link(xoutDepth.input)
> 
> xoutDepth = pipeline.create(dai.node.XLinkOut)
> xoutDepth.setStreamName("disp")
> stereo.disparity.link(xoutDepth.input)
> 
> # Connect to device and start pipeline
> with dai.Device(pipeline) as device:
>     depthQueue = device.getOutputQueue(name="depth", maxSize=10, blocking=False)
>     dispQ = device.getOutputQueue(name="disp", maxSize=10, blocking=False)
>     qRgb = device.getOutputQueue(name="rgb", maxSize=4, blocking=False)
> 
>     text = TextHelper()
>     rgbtext = TextHelper()
>     hostSpatials = HostSpatialsCalc(device)
>     delta = 5
> 
>     hostSpatials.setDeltaRoi(delta)
> 
>     print("Use 'r' and 'f' to change ROI size.")
> 
>     while True:
>         inRgb = qRgb.get()  # Blocking call for new RGB frame
>         depthData = depthQueue.get()
>         frame = inRgb.getCvFrame()
>       
>         results = model.predict(source=frame, classes=[1])  # Filter to only detect class 1 (parcels)
> 
>         try:
>             for result in results:
>                 if hasattr(result, 'obb'):
>                     xmin = int(result.obb.xyxy[0][0])
>                     ymin = int(result.obb.xyxy[0][1])
>                     xmax = int(result.obb.xyxy[0][2])
>                     ymax = int(result.obb.xyxy[0][3])
>                     rgbtext.rectangle(frame, (xmin, ymin), (xmax, ymax))
>                     print(f"OBB Coordinates: {xmin}, {ymin}, {xmax}, {ymax}")
> 
>                     # Calculate spatial coordinates
>                     center_x = (xmin + xmax) // 2
>                     center_y = (ymin + ymax) // 2
>                     spatials, centroid = hostSpatials.calc_spatials(depthData, (center_x, center_y))
>                     text.putText(frame, f"X: {spatials['x']:.1f}mm", (xmin, ymin - 20))
>                     text.putText(frame, f"Y: {spatials['y']:.1f}mm", (xmin, ymin - 10))
>                     text.putText(frame, f"Z: {spatials['z']:.1f}mm", (xmin, ymin))
>             
>         except Exception as e:
>             print(f"Error: {e}")
> 
>         # Get disparity frame for nicer depth visualization
>         disp = dispQ.get().getFrame()
>         disp = (disp * (255 / stereo.initialConfig.getMaxDisparity())).astype(np.uint8)
>         disp = cv2.applyColorMap(disp, cv2.COLORMAP_JET)
> 
>         text.rectangle(disp, (center_x-delta, center_y-delta), (center_x+delta, center_y+delta))
>         text.putText(disp, f"X: {spatials['x']:.1f}mm", (center_x + 10, center_y + 20))
>         text.putText(disp, f"Y: {spatials['y']:.1f}mm", (center_x + 10, center_y + 35))
>         text.putText(disp, f"Z: {spatials['z']:.1f}mm", (center_x + 10, center_y + 50))
> 
>         # Show the frame
>         cv2.imshow("depth", disp)
>         cv2.imshow("rgb", frame)
>         
>         key = cv2.waitKey(1)
>         if key == ord('q'):
>             break
> 
>         elif key == ord('r'):  # Increase Delta
>             if delta < 50:
>                 delta += 1
>                 hostSpatials.setDeltaRoi(delta)
> 
>         elif key == ord('f'):  # Decrease Delta
>             if 3 < delta:
>                 delta -= 1
>                 hostSpatials.setDeltaRoi(delta)
> ```
> 
> This code calculates the spatial coordinates (X, Y, Z) for the center of each detected object and overlays this information on the RGB frame. It also displays the depth information in a separate window.
> 
> If you encounter any issues or need further assistance, please ensure you are using the latest version of the Ultralytics packages. Additionally, providing a minimum reproducible example can greatly help in diagnosing and resolving any issues. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> Happy coding! 🚀

Hello thank you for the reply! Gladly it worked this is the result:

![image](https://github.com/ultralytics/ultralytics/assets/168053014/9ff9ee57-296c-4e33-b539-7bce87c6cb63)

My next problem is that if there is multiple it can only detect one box and give its XYZ coordinates (sometimes if there are 2-3 boxes), the bounding box switches from one box to another box, is there a way on how I can make it that it can detect multiple boxes and give their XYZ coordinates at the same time real-time

**Comment by glenn-jocher** [comment]
Hello @KennethEladistu,

I'm glad to hear that the solution worked for you! 🎉 Your next challenge of detecting multiple boxes and displaying their XYZ coordinates simultaneously is definitely achievable. The key is to iterate over all detected objects and calculate their spatial coordinates individually.

Here's an updated version of your code that handles multiple detections and displays their XYZ coordinates in real-time:

```python
import cv2
import depthai as dai
from submodule.calc import HostSpatialsCalc
from submodule.utility import *
import numpy as np
import math
from ultralytics import YOLO  # Assuming you have YOLOv8 with OBB support

# Load a pretrained YOLOv8 OBB model (ensure it's trained for OBB)
model = YOLO("C:/Users/KennethAaronEladistu/oak_d/oak_d/best(3).pt")  # Replace with your model path

# Create pipeline
pipeline = dai.Pipeline()

# Define source and output (RGB camera)
camRgb = pipeline.create(dai.node.ColorCamera)
xoutRgb = pipeline.create(dai.node.XLinkOut)
xoutRgb.setStreamName("rgb")

# Properties
camRgb.setPreviewSize(640, 640)
camRgb.setResolution(dai.ColorCameraProperties.SensorResolution.THE_1080_P)
camRgb.setInterleaved(False)
camRgb.setColorOrder(dai.ColorCameraProperties.ColorOrder.RGB)

# Linking (RGB camera)
camRgb.preview.link(xoutRgb.input)

# Define sources and outputs (Stereo Depth)
monoLeft = pipeline.create(dai.node.MonoCamera)
monoRight = pipeline.create(dai.node.MonoCamera)
stereo = pipeline.create(dai.node.StereoDepth)

# Properties (Stereo Depth)
monoLeft.setResolution(dai.MonoCameraProperties.SensorResolution.THE_400_P)
monoLeft.setBoardSocket(dai.CameraBoardSocket.LEFT)
monoRight.setResolution(dai.MonoCameraProperties.SensorResolution.THE_400_P)
monoRight.setBoardSocket(dai.CameraBoardSocket.RIGHT)

stereo.initialConfig.setConfidenceThreshold(255)
stereo.setDefaultProfilePreset(dai.node.StereoDepth.PresetMode.HIGH_DENSITY)
stereo.setDepthAlign(camera=dai.CameraBoardSocket.CAM_A)
stereo.setLeftRightCheck(True)
stereo.setOutputSize(monoLeft.getResolutionWidth(), monoLeft.getResolutionHeight())
stereo.setSubpixel(False)
stereo.setExtendedDisparity(True)

# Linking (Stereo Depth)
monoLeft.out.link(stereo.left)
monoRight.out.link(stereo.right)

xoutDepth = pipeline.create(dai.node.XLinkOut)
xoutDepth.setStreamName("depth")
stereo.depth.link(xoutDepth.input)

xoutDepth = pipeline.create(dai.node.XLinkOut)
xoutDepth.setStreamName("disp")
stereo.disparity.link(xoutDepth.input)

# Connect to device and start pipeline
with dai.Device(pipeline) as device:
    depthQueue = device.getOutputQueue(name="depth", maxSize=10, blocking=False)
    dispQ = device.getOutputQueue(name="disp", maxSize=10, blocking=False)
    qRgb = device.getOutputQueue(name="rgb", maxSize=4, blocking=False)

    text = TextHelper()
    rgbtext = TextHelper()
    hostSpatials = HostSpatialsCalc(device)
    delta = 5

    hostSpatials.setDeltaRoi(delta)

    print("Use 'r' and 'f' to change ROI size.")

    while True:
        inRgb = qRgb.get()  # Blocking call for new RGB frame
        depthData = depthQueue.get()
        frame = inRgb.getCvFrame()
      
        results = model.predict(source=frame, classes=[1])  # Filter to only detect class 1 (parcels)

        try:
            for result in results:
                if hasattr(result, 'obb'):
                    for obb in result.obb:
                        xmin = int(obb.xyxy[0][0])
                        ymin = int(obb.xyxy[0][1])
                        xmax = int(obb.xyxy[0][2])
                        ymax = int(obb.xyxy[0][3])
                        rgbtext.rectangle(frame, (xmin, ymin), (xmax, ymax))
                        print(f"OBB Coordinates: {xmin}, {ymin}, {xmax}, {ymax}")

                        # Calculate spatial coordinates
                        center_x = (xmin + xmax) // 2
                        center_y = (ymin + ymax) // 2
                        spatials, centroid = hostSpatials.calc_spatials(depthData, (center_x, center_y))
                        text.putText(frame, f"X: {spatials['x']:.1f}mm", (xmin, ymin - 20))
                        text.putText(frame, f"Y: {spatials['y']:.1f}mm", (xmin, ymin - 10))
                        text.putText(frame, f"Z: {spatials['z']:.1f}mm", (xmin, ymin))
            
        except Exception as e:
            print(f"Error: {e}")

        # Get disparity frame for nicer depth visualization
        disp = dispQ.get().getFrame()
        disp = (disp * (255 / stereo.initialConfig.getMaxDisparity())).astype(np.uint8)
        disp = cv2.applyColorMap(disp, cv2.COLORMAP_JET)

        text.rectangle(disp, (center_x-delta, center_y-delta), (center_x+delta, center_y+delta))
        text.putText(disp, f"X: {spatials['x']:.1f}mm", (center_x + 10, center_y + 20))
        text.putText(disp, f"Y: {spatials['y']:.1f}mm", (center_x + 10, center_y + 35))
        text.putText(disp, f"Z: {spatials['z']:.1f}mm", (center_x + 10, center_y + 50))

        # Show the frame
        cv2.imshow("depth", disp)
        cv2.imshow("rgb", frame)
        
        key = cv2.waitKey(1)
        if key == ord('q'):
            break

        elif key == ord('r'):  # Increase Delta
            if delta < 50:
                delta += 1
                hostSpatials.setDeltaRoi(delta)

        elif key == ord('f'):  # Decrease Delta
            if 3 < delta:
                delta -= 1
                hostSpatials.setDeltaRoi(delta)
```

In this updated code, the loop iterates over each detected object and calculates the spatial coordinates for each one. The coordinates are then displayed on the RGB frame.

If you continue to experience issues or have further questions, please ensure you are using the latest version of the Ultralytics packages. Additionally, providing a minimum reproducible example can greatly help in diagnosing and resolving any issues. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Keep up the great work! 🚀
