### ISSUE TITLE
clean small objects

### ISSUE THREAD

**Issue by sdimantsd** [ultralytics/ultralytics#1417]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, in yolov5 there is an options to clean small objects ([here](https://github.com/ultralytics/yolov5/blob/0322bb31962d68caefa0c0c5880d80d27e8ab8ec/utils/autoanchor.py#L125)).
in yolov8 I don't see it. why is that?

**Comment by glenn-jocher** [comment]
@sdimantsd ah, this check was performed during anchor evolution, but YOLOv8 is anchor-free, so this code was not ported over to v8.

**Comment by frabob2017** [comment]
where can I find more detail about the anchor free concept? I still do not understand this anchor-free concept very well. 

With anchor box, the H,W are regression, in which Pw, Ph are predefined anchor box width and height. 
![image](https://user-images.githubusercontent.com/57141860/225123012-421af9a8-f6cf-4665-9fc4-734ceae916c1.png)

**Comment by glenn-jocher** [comment]
@frabob2017 YOLOv8 uses DFL loss for regression of boxes at multiple scales. The final output box is a weighted combination of many input boxes at different scales. The YOLOv8 detect head does this:

https://github.com/ultralytics/ultralytics/blob/30fc4b537ff1d9b115bc1558884f6bc2696a282c/ultralytics/nn/modules.py#L382-L432

**Comment by frabob2017** [comment]
Distribution Focal Loss (DFL), I will study this concept. After I study, I think YOLO is more complex than UNET. The concept of UNet is relatively quite straightforward.

**Comment by sdimantsd** [comment]
@glenn-jocher 
Thanks.
Do you plan to add this feature to yolo 8?

**Comment by glenn-jocher** [comment]
@sdimantsd a small object warning? We have no plans to add it, but it should not be too hard.

@Laughing-q we might want to add this YOLOv5 small object warning to YOLOv8 dataloader.

**Comment by glenn-jocher** [comment]
@Laughing-q ah that's true, we reject these as not being suitable detection candidates for training.
