### ISSUE TITLE
AttributeError: Can't get attribute 'v10DetectLoss' on <module 'ultralytics.utils.loss' from 'C:\\Users\\JFerreira\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\ultralytics\\utils\\loss.py'

### ISSUE THREAD

**Issue by JoaoLopesFerreira99** [ultralytics/ultralytics#14170]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

PS C:\Users\JFerreira\Desktop\Models\_testing> & C:/Users/JFerreira/AppData/Local/Programs/Python/Python310/python.exe c:/Users/JFerreira/Desktop/Models/_testing/inf_test.py
8.2.48
Traceback (most recent call last):
  File "c:\Users\JFerreira\Desktop\Models\_testing\inf_test.py", line 16, in <module>
    main()
  File "c:\Users\JFerreira\Desktop\Models\_testing\inf_test.py", line 7, in main
    model = ultralytics.YOLO('C:/Users/JFerreira/Desktop/Models/_testing/models/YOLOv10n.pt')
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__       
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\model.py", line 149, in __init__
    self._load(model, task=task)
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\model.py", line 230, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\nn\tasks.py", line 855, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\nn\tasks.py", line 781, in torch_safe_load        
    ckpt = torch.load(file, map_location="cpu")
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1025, in load
    return _load(opened_zipfile,
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1446, in _load
    result = unpickler.load()
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1439, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'v10DetectLoss' on <module 'ultralytics.utils.loss' from 'C:\\Users\\JFerreira\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\ultralytics\\utils\\loss.py'>
PS C:\Users\JFerreira\Desktop\Models\_testing> 

### Minimal Reproducible Example

import torch
import ultralytics

def main():
    # Load the trained model
    print(ultralytics.__version__)
    model = ultralytics.YOLO('C:/Users/JFerreira/Desktop/Models/_testing/models/YOLOv10n.pt')

    # Dataset path
    dataset_path = 'C:/Users/JFerreira/Desktop/Models/_testing/test_dataset/airsim.yaml'

    # Run inference on the dataset and gather metrics
    model.val(data=dataset_path)

if __name__ == '__main__':
    main()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi @JoaoLopesFerreira99,

Thank you for reporting this issue and providing the detailed traceback and code snippet. It looks like you're encountering an `AttributeError` related to the `v10DetectLoss` attribute when attempting to load your YOLOv10 model.

To help us diagnose and resolve this issue more effectively, could you please verify the following:

1. **Ensure Latest Version**: Make sure you are using the latest version of the Ultralytics package. You can update it using:
    ```bash
    pip install --upgrade ultralytics
    ```

2. **Reproducible Example**: It's crucial to have a minimal reproducible example to pinpoint the problem accurately. Your provided code is a great start. Please ensure that the issue persists with the latest package version and provide any additional context if necessary. More details on creating a minimal reproducible example can be found [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

3. **Model Compatibility**: Verify that the model file `YOLOv10n.pt` is compatible with the version of the Ultralytics package you are using. Sometimes, models trained or saved with different versions might have compatibility issues.

Here's a slightly modified version of your script to ensure it aligns with the latest package updates:

```python
import torch
import ultralytics

def main():
    # Print the version of Ultralytics
    print(ultralytics.__version__)

    # Load the trained model
    model = ultralytics.YOLO('C:/Users/JFerreira/Desktop/Models/_testing/models/YOLOv10n.pt')

    # Dataset path
    dataset_path = 'C:/Users/JFerreira/Desktop/Models/_testing/test_dataset/airsim.yaml'

    # Run inference on the dataset and gather metrics
    model.val(data=dataset_path)

if __name__ == '__main__':
    main()
```

If the issue persists after these steps, please let us know. Providing any additional logs or context will be helpful. We appreciate your cooperation and look forward to resolving this issue promptly.
