### ISSUE TITLE
Use obs virtual camera, prompt"WARNING  Video stream unresponsive, please check your IP camera connection.", show command, black screen

### ISSUE THREAD

**Issue by kkive** [ultralytics/ultralytics#1418]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello author, I want to get my own computer screen content recognition in real time, so I thought of using the function of OBS virtual camera to realize, but I encountered a problem. Yolov8 cannot open the obs virtual camera, and reported the content "WARNING Video stream unresponsive, please check your IP camera connection." I searched all the questions, and there is no same, so I hope you can answer, thank you
I fill in this parameter as 1, because 0 is my laptop's camera `source="1"`

This picture is my code and running output
![image](https://user-images.githubusercontent.com/51246778/224950550-5cb4bf13-c382-4346-8051-e986097ea2aa.png)

This picture shows that OBS has turned on the virtual camera
![image](https://user-images.githubusercontent.com/51246778/224951342-04a96940-9f9c-4a89-9831-266de5a3b493.png)

Here is my complete code
```python
from ultralytics import YOLO
model = YOLO(r"D:\python\yolov8\yolov8n.pt")
def main():
    for results in model.predict(source="1", show=True, stream=True): # stream为TUre输出boxes
        pass
        # return results.boxes#  边框坐标
main()
```

This is the output content
```python
WARNING  Video stream unresponsive, please check your IP camera connection.
0: 480x640 (no detections), 100.1ms
0: 480x640 (no detections), 102.9ms
0: 480x640 (no detections), 107.1ms
0: 480x640 (no detections), 99.7ms
0: 480x640 (no detections), 98.6ms
0: 480x640 (no detections), 100.2ms
0: 480x640 (no detections), 102.1ms
0: 480x640 (no detections), 99.3ms
0: 480x640 (no detections), 102.5ms
0: 480x640 (no detections), 103.3ms
0: 480x640 (no detections), 106.6ms
0: 480x640 (no detections), 101.4ms
WARNING  Video stream unresponsive, please check your IP camera connection.
```

**Comment by JustasBart** [comment]
Hi @kkive I'm pretty sure that each Camera occupies 2 ports.

As in:
Camera 'A' -> Port 0, Port 1.
Camera 'B' -> Port 2, Port 3.
Camera 'C' -> Port 4, Port 5.
Etc...

Can you please quickly confirm whether port '2' works?

**Comment by kkive** [comment]
@JustasBart
Hello, I just tried 2, 3 and 4 to report this error 
```
"raise ConnectionError (f '{st} Failed to open {s}')
ConnectionError: 1/1: 2... Failed to open 2”
```


I use opencv to open obs, which is also black

![image](https://user-images.githubusercontent.com/51246778/224986287-6523bd49-e931-4e34-9335-96b89edad28c.png)

I use opencv with the number of 1. I can find out whether the obs is turned on or not displayed as a black screen

![无标题](https://user-images.githubusercontent.com/51246778/224988959-bf8e21ee-02cb-4229-aac7-97937076c5f4.png)

**Comment by JustasBart** [comment]
@kkive Ok, I wouldn't know then... Sorry... Perhaps try looking for some alternative or make something yourself using for example using `img = pyautogui.screenshot()` to take an image of your screen?

Good luck! :rocket:

**Comment by DavidTWynn** [comment]
I am getting the same where my OBS Virtual Camera is not picked up by yolov8.

I use OBS, make a scene, make a source for one of my displays and preview it. In OBS I can record to disk and see the output is correct. I click "Start Virtual Camera" and Output Type is set to "Internal". I can go into Discord and select my camera as the first camera and it works, then select the second camera in Discord and it opens the virual obs camera correctly.

In the yolov8 command line I tried a detect against source=0 and that was my webcam, and it worked. Also tried all available cameras 0-5, cameras 1-5 say "WARNING Video stream unresponsive, please check your IP camera connection". I think it would be best if we could use this obs virtual web cam so there isn't additional latency of an additional later to get yolo reading it.

One interesting thing is when using the windows camera app it only detects my webcam and not the OBS virtual camera, even though discord detects multiple virtual cameras. So maybe there are two types of cameras in windows, physical and virtual, and yolo is only pulling physically connected cameras? I looked through device manager and do not see an entry for the obs virtual camera, but do see under "Universal Serial bus controllers" an entry for my physical camera.

OBS

![image](https://user-images.githubusercontent.com/50935601/229366842-d593b19e-3eda-4190-b268-28f9293fb551.png)

Discord showing OBS

![image](https://user-images.githubusercontent.com/50935601/229366891-8fcd2227-2b38-404a-a13a-95b2ab764f04.png)

yolov8 Video stream unresponsive

![image](https://user-images.githubusercontent.com/50935601/229366940-29b3fad5-8914-4d3a-a6b9-4f21931ca452.png)

**Comment by DavidTWynn** [comment]
This issue says that xsplit works as a virtual camera https://github.com/ultralytics/ultralytics/issues/1029.
I tried output xsplit and I was able to point xsplit to OBS, then use xsplit as a source for yolo. This isn't ideal though because xsplit adds a watermark and adds additional latency.

I see that xsplit acts differently in that the windows device manager now has a new device as Imaging devices > XSplit VCam
and the windows camera can use xsplit.

I am wondering if there is a way we can change the windows camera detection in yolov8 to use the process discord is using to get the virtual obs webcam, and not just physical cameras.

**Comment by DavidTWynn** [comment]
Tried this with streamlabs virtual camera and got the same results.

**Comment by glenn-jocher** [comment]
@deardeer87, thank you for the detailed information and sharing your attempts to use OBS virtual camera, as well as Streamlabs and XSplit virtual cameras. Currently, YOLOv8 supports only physical connected cameras, and  virtual cameras are not officially supported at this time. 

It is possible that each software may implement the virtual camera in a slightly different way, making it difficult to create a universal solution for them. Nonetheless, Your feedback has been noted and it provides a valuable opportunity for Ultralytics developers to research possible solutions for a future version of YOLOv8. 

As a workaround, you could try using physical cameras, or using other application solutions, as you have tried with XSplit. Alternatively, you could use a separate script to detect video from virtual cameras and send the results to YOLOv8.

If you have any further questions, please do not hesitate to ask.

**Comment by DavidTWynn** [comment]
After reading through these two issues I see that OBS has problems with its virtual camera in other programs such as OpenCV as well.

https://github.com/obsproject/obs-studio/issues/3635
https://github.com/opencv/opencv/issues/19746

There was some discussion about using an older version of OBS. I went from the newest OBS 29.02 to OBS version 27.2.4 and manually installed the obs-virtual-cam plugin. This worked for my issue with OpenCV not using the OBS virtual camera, and now the camera works with yolov8.

https://github.com/obsproject/obs-studio/releases/tag/27.2.4
https://github.com/Fenrirthviti/obs-virtual-cam/releases/tag/2.0.5

**Comment by pderrenger** [comment]
@DavidTWynn that's some excellent investigative work! Your findings and the successful workaround using OBS version 27.2.4 with the obs-virtual-cam plugin are insightful and valuable to other users experiencing similar issues with OBS virtual camera compatibility. Thank you for sharing the specific versions and releases that resolved the problem with YOLOv8. Your feedback and contributions are greatly appreciated, and they will certainly help others encountering similar challenges. If you have any further insights or feedback to share, please feel free to do so.
