### ISSUE TITLE
camera changing input resolution 

### ISSUE THREAD

**Issue by jakubkotecki6** [ultralytics/ultralytics#14214]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I have this problem when i try to detect objects on my thermal camera. To make it run proparely I need to change frame height, width and rate, but when i input this frame into model.predict(), it displays 1 frame then goes to miniconda3\Lib\site-packages\ultralytics\assets\ and picks up bus.jpg and zidane.jpg, then breaks down. Also when i run it on my regular webcam it does the same thing. Is there any solution to run detection on set frame height/width/rate?

https://github.com/ultralytics/ultralytics/assets/113249947/1e1a7885-7bfc-4fcb-95d5-42653cdb0b39

### Minimal Reproducible Example

from ultralytics import YOLO
import cv2

model = YOLO("yolov10n.pt")

cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 256)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 192)
cap.set(cv2.CAP_PROP_FPS, 50)

if not (cap.isOpened()):
    print("Could not open video device")

while True:
    ret, frame = cap.read()

    # Perform object detection on an image
    results = model.predict(frame, save=True, show=True, conf=0.15)

    cv2.imshow("frame", frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    cap.release()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @jakubkotecki6,

Thank you for reaching out and providing a detailed description of the issue you're facing. It seems like you're encountering a problem when trying to detect objects using your thermal camera with specific frame dimensions and frame rate settings.

To better assist you, could you please verify the following:
1. Ensure you are using the latest version of the Ultralytics YOLO package. Sometimes, issues are resolved in newer releases.
2. Provide a minimal reproducible example that consistently demonstrates the issue. This helps us diagnose the problem more effectively. You can refer to our guide on creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example).

From your description, it appears that the model is defaulting to sample images (`bus.jpg` and `zidane.jpg`) from the Ultralytics assets directory. This might happen if the input frame is not being read correctly or if there's an issue with the video capture setup.

Here are a few suggestions to troubleshoot and potentially resolve the issue:

1. **Check Video Capture Initialization:**
   Ensure that the video capture device is correctly initialized and that frames are being read properly.
   ```python
   if not cap.isOpened():
       print("Could not open video device")
       exit()
   ```

2. **Verify Frame Read:**
   Add a check to ensure that frames are being read correctly before passing them to the model.
   ```python
   while True:
       ret, frame = cap.read()
       if not ret:
           print("Failed to read frame")
           break

       # Perform object detection on the frame
       results = model.predict(frame, save=True, show=True, conf=0.15)

       cv2.imshow("frame", frame)
       if cv2.waitKey(1) & 0xFF == ord('q'):
           break
   cap.release()
   ```

3. **Set Correct Frame Dimensions:**
   Ensure that the frame dimensions and frame rate are set correctly and supported by your camera.
   ```python
   cap.set(cv2.CAP_PROP_FRAME_WIDTH, 256)
   cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 192)
   cap.set(cv2.CAP_PROP_FPS, 50)
   ```

4. **Debugging:**
   Print out the frame dimensions and type to ensure they are as expected.
   ```python
   print(f"Frame dimensions: {frame.shape}")
   print(f"Frame type: {type(frame)}")
   ```

If the issue persists after these checks, please provide any additional error messages or logs that might help us diagnose the problem further.

Feel free to reach out with any more details or questions. We're here to help!
