### ISSUE TITLE
'AutoBackend' object has no attribute 'kpt_shape' when inferring with pose model

### ISSUE THREAD

**Issue by muneeb-ds** [ultralytics/ultralytics#14215]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I trained a bbox detection model and then used that to initialize a separate model which was later fine-tuned on a pose dataset. Once the model was trained, now when I infer the trained model on an image I get the following error:

### Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/pinpoint/lib/python3.9/site-packages/ultralytics/engine/model.py", line 442, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/root/miniconda3/envs/pinpoint/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/root/miniconda3/envs/pinpoint/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/miniconda3/envs/pinpoint/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 261, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "/root/miniconda3/envs/pinpoint/lib/python3.9/site-packages/ultralytics/models/yolo/pose/predict.py", line 52, in postprocess
    pred_kpts = pred[:, 6:].view(len(pred), *self.model.kpt_shape) if len(pred) else pred[:, 6:]
  File "/root/miniconda3/envs/pinpoint/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'AutoBackend' object has no attribute 'kpt_shape'
```

### data.yaml:

```
flip_idx:
- 0
kpt_shape:
- 1
- 3
task: pose
names:
- tip
nc: 1
test: ../test/images
train: train/images
val: valid/images
```

### Environment

Ultralytics YOLOv8.2.48 🚀 Python-3.9.19 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4090, 24217MiB)
Setup complete ✅ (32 CPUs, 62.0 GB RAM, 9.8/32.0 GB disk)

OS                  Linux-5.15.0-113-generic-x86_64-with-glibc2.35
Environment         Docker
Python              3.9.19
Install             pip
RAM                 61.98 GB
CPU                 AMD Ryzen 9 7950X3D 16-Core Processor
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.3.1>=1.8.0
torchvision         ✅ 0.18.1>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

```
model = YOLO("detection/model.pt") 

model.train('data.yaml',epochs=100,imgsz=(1600, 1200),device=[0,1],batch=20,save=True,workers=36,patience=50, task='pose', hsv_h=0, hsv_v=0, hsv_s=0, scale=0, shear=0, translate=0)

pose_model = YOLO("pose/model.pt")
pose_model.predict("random/image.jpg")
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@muneeb-ds hi there,

Thank you for reporting this issue and providing detailed information. It seems like the error is related to the `kpt_shape` attribute not being properly set in the `AutoBackend` object during inference with your pose model.

To help us diagnose and resolve this issue, could you please provide a minimal reproducible example? This will allow us to replicate the problem on our end and identify the root cause more effectively. You can find guidelines for creating a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest version of the Ultralytics YOLO package. Sometimes, issues are resolved in newer releases, and updating might fix the problem.

Here's a quick checklist to verify:
1. Ensure you have the latest version of the Ultralytics YOLO package:
   ```bash
   pip install --upgrade ultralytics
   ```
2. Confirm that the `kpt_shape` attribute is correctly defined in your `data.yaml` file, as it appears to be correctly set in the snippet you provided.

If the issue persists after these steps, please share the minimal reproducible example, and we will investigate further.

Thank you for your cooperation and understanding! 😊

**Comment by Y-T-G** [comment]
You did the wrong way.

It should be:
```
model = YOLO("yolov8n-pose.yaml").load("detect_model.pt")
model.train()
```

Use the same yaml as the original variant and edit the yaml and change the number of classes `nc` to the number of classes in your trained model.

**Comment by glenn-jocher** [comment]
Hi @Y-T-G,

Thank you for your input! Your suggestion to use the `YOLO("yolov8n-pose.yaml").load("detect_model.pt")` approach is indeed a valid method to initialize a pose model with pre-trained weights from a detection model. This ensures that the model architecture is correctly set up for pose estimation.

To further assist you, here’s a refined example based on your suggestion:

```python
from ultralytics import YOLO

# Load the detection model weights into the pose model architecture
model = YOLO("yolov8n-pose.yaml").load("detect_model.pt")

# Ensure the data.yaml file is correctly configured for pose estimation
# Adjust the number of keypoints (nc) and other relevant parameters
model.train(data="data.yaml", epochs=100, imgsz=640)
```

Please make sure your `data.yaml` file is properly configured for pose estimation, including the correct number of keypoints (`nc`) and any other necessary parameters.

If you continue to experience issues, providing a minimal reproducible example would be very helpful. You can find guidelines for creating one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, ensure you are using the latest version of the Ultralytics YOLO package by running:
```bash
pip install --upgrade ultralytics
```

If the problem persists, please share more details, and we’ll be happy to assist further. 😊
