### ISSUE TITLE
how to export engine with dynamic batch but not with dynamic hw?

### ISSUE THREAD

**Issue by lzcchl** [ultralytics/ultralytics#14220]
I use the code to export engine, but 

1. got model with (-1,3,-1,-1)
model.export(format="engine", dynamic=True, simplify=True, imgsz=(640,640), batch=2)

2. got model with (2,3,640,640)
model.export(format="engine", dynamic=False, simplify=True, imgsz=(640,640), batch=2)

I just want the engine with (-1,3,640,640), what should I do?

**Comment by Y-T-G** [comment]
You can edit it:

https://github.com/ultralytics/ultralytics/blob/ea80b14d72472b1e938c493eb586499105442075/ultralytics/engine/exporter.py#L678

**Comment by lzcchl** [comment]
did you mean that edit min_shape and max_shape in exporter.py ? or edit max_workspace_size ?

**Comment by lzcchl** [comment]
did you mean that edit min_shape and max_shape in exporter.py ? or edit max_workspace_size ?

**Comment by Y-T-G** [comment]
Sorry, wrong line

https://github.com/ultralytics/ultralytics/blob/ea80b14d72472b1e938c493eb586499105442075/ultralytics/engine/exporter.py#L678

**Comment by Y-T-G** [comment]
Sorry wrong line

https://github.com/ultralytics/ultralytics/blob/ea80b14d72472b1e938c493eb586499105442075/ultralytics/engine/exporter.py#L368

**Comment by glenn-jocher** [comment]
@Y-T-G thank you for the clarification! To achieve an engine with a dynamic batch size but fixed height and width, you can indeed modify the `min_shape` and `max_shape` parameters in the `exporter.py` file. Specifically, you want to set the batch dimension to be dynamic while keeping the spatial dimensions fixed.

Here's a step-by-step guide:

1. **Locate the Export Code**: Open the `exporter.py` file and locate the section where the `min_shape` and `max_shape` are defined.

2. **Modify the Shapes**: Adjust the `min_shape` and `max_shape` to reflect a dynamic batch size while keeping the height and width fixed. For example:
    ```python
    min_shape = (1, 3, 640, 640)
    max_shape = (batch_size, 3, 640, 640)  # Replace batch_size with your desired maximum batch size
    ```

3. **Export the Model**: Use the modified script to export your model. Ensure that `dynamic=True` is set to enable dynamic batching.

Here is a code snippet to illustrate the changes:
```python
# In exporter.py

# Define min and max shapes
min_shape = (1, 3, 640, 640)
max_shape = (batch_size, 3, 640, 640)  # Replace batch_size with your desired maximum batch size

# Export the model with dynamic batch size
model.export(format="engine", dynamic=True, simplify=True, imgsz=(640, 640), batch=batch_size)
```

This should give you an engine with a dynamic batch size while keeping the height and width fixed at 640x640.

If you encounter any issues or need further assistance, please provide a minimum reproducible example, and ensure you are using the latest version of the Ultralytics package. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions! 😊

**Comment by lzcchl** [comment]
thank you!

**Comment by glenn-jocher** [comment]
You're welcome! 😊

To achieve an engine with a dynamic batch size but fixed height and width, you can modify the `min_shape` and `max_shape` parameters in the `exporter.py` file. Here's how you can do it:

1. **Locate the Export Code**: Open the `exporter.py` file and find the section where `min_shape` and `max_shape` are defined.

2. **Modify the Shapes**: Adjust the `min_shape` and `max_shape` to reflect a dynamic batch size while keeping the height and width fixed. For example:
    ```python
    min_shape = (1, 3, 640, 640)
    max_shape = (batch_size, 3, 640, 640)  # Replace batch_size with your desired maximum batch size
    ```

3. **Export the Model**: Use the modified script to export your model. Ensure that `dynamic=True` is set to enable dynamic batching.

Here is a code snippet to illustrate the changes:
```python
# In exporter.py

# Define min and max shapes
min_shape = (1, 3, 640, 640)
max_shape = (batch_size, 3, 640, 640)  # Replace batch_size with your desired maximum batch size

# Export the model with dynamic batch size
model.export(format="engine", dynamic=True, simplify=True, imgsz=(640, 640), batch=batch_size)
```

This should give you an engine with a dynamic batch size while keeping the height and width fixed at 640x640.

If you encounter any issues or need further assistance, please provide a minimum reproducible example, and ensure you are using the latest version of the Ultralytics package. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions! 😊
