### ISSUE TITLE
Label position when extending beyond image

### ISSUE THREAD

**Issue by SheffeyG** [ultralytics/ultralytics#14225]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

When I try to validate the models, the results plot such as val_batch0_labels.jpg looks like this:
![val_batch0_labels](https://github.com/ultralytics/ultralytics/assets/57262511/2b3d2db7-ea3e-4e67-b21b-01ccca9aef26)
the labels on the second column's width is wrong, so they are shown at the first column.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@SheffeyG hi there,

Thank you for reporting this issue and for your willingness to contribute a PR! To help us better understand and address the problem, could you please provide a minimal reproducible example? This will allow us to replicate the issue on our end and ensure a more effective resolution. You can find guidelines on how to create a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please make sure you are using the latest version of the Ultralytics YOLOv8 package, as updates often include important bug fixes and improvements. You can update your package using the following command:

```bash
pip install --upgrade ultralytics
```

Once we have the reproducible example, we can investigate further and work towards a solution. Thank you for your cooperation and for being an active part of the YOLO community! 😊
