### ISSUE TITLE
Calculate APsmall

### ISSUE THREAD

**Issue by xxqqdd** [ultralytics/ultralytics#14222]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I calculate APsmall, which is the average precision (AP) for all target boxes with pixel areas smaller than 32x32?

**Comment by glenn-jocher** [comment]
@xxqqdd hello!

To calculate APsmall (average precision for small objects with areas smaller than 32x32 pixels), you can use the built-in evaluation metrics provided by the Ultralytics YOLO models. The `val` mode in YOLOv8 automatically calculates AP for different object sizes, including small objects.

Here's a concise way to validate your model and get the APsmall metric:

1. **Ensure you have the latest version of the Ultralytics package**:
    ```bash
    pip install ultralytics --upgrade
    ```

2. **Run the validation**:
    ```bash
    yolo val model=path/to/your/model.pt data=path/to/your/data.yaml
    ```

The validation output will include metrics for APsmall, APmedium, and APlarge. If you need to extract these metrics programmatically, you can use the Python API:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('path/to/your/model.pt')

# Validate the model
metrics = model.val(data='path/to/your/data.yaml')

# Access APsmall
ap_small = metrics.box.maps[0]  # AP for small objects
print(f"APsmall: {ap_small:.4f}")
```

If you encounter any issues or need further assistance, please provide a minimum reproducible example as outlined [here](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us diagnose and resolve your issue more effectively.

Happy coding! 🚀
