### ISSUE TITLE
ModuleNotFoundError: No module named 'deep_sort_pytorch'

### ISSUE THREAD

**Issue by Ishidaseiji** [ultralytics/ultralytics#14234]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

HI！　I'm not sure how to solve this problem. Could you tell me ?

07/05/2024 23:30:51 - INFO - numexpr.utils -   NumExpr defaulting to 8 threads.
Traceback (most recent call last):
  File "/Users/ishidaseiji/ultralytics/examples/YOLOv8-SAHI-Inference-Video/yolov8_sahi.py", line 11, in <module>
    from ultralytics.utils.files import increment_path
  File "/Users/ishidaseiji/Downloads/YOLOv8-DeepSORT-Object-Tracking-main/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import checks
  File "/Users/ishidaseiji/Downloads/YOLOv8-DeepSORT-Object-Tracking-main/ultralytics/hub/__init__.py", line 15, in <module>
    from ultralytics.yolo.v8.detect import DetectionTrainer
  File "/Users/ishidaseiji/Downloads/YOLOv8-DeepSORT-Object-Tracking-main/ultralytics/yolo/v8/detect/__init__.py", line 3, in <module>
    from .predict import DetectionPredictor, predict
  File "/Users/ishidaseiji/Downloads/YOLOv8-DeepSORT-Object-Tracking-main/ultralytics/yolo/v8/detect/predict.py", line 19, in <module>
    from deep_sort_pytorch.utils.parser import get_config
ModuleNotFoundError: No module named 'deep_sort_pytorch'

**Comment by glenn-jocher** [comment]
Hi @Ishidaseiji,

Thank you for reaching out! It looks like you're encountering a `ModuleNotFoundError` for the `deep_sort_pytorch` module. This error typically occurs when the required module is not installed in your environment.

To resolve this issue, you can install the `deep_sort_pytorch` package using the following command:

```bash
pip install deep_sort_realtime
```

If you continue to experience issues, please ensure that you are using the latest version of the Ultralytics repository and all related packages. You can update the Ultralytics package with:

```bash
pip install --upgrade ultralytics
```

Additionally, if the problem persists, providing a minimum reproducible example would be very helpful. This allows us to better understand the context and reproduce the issue on our end. You can find guidance on creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any further questions or need additional assistance. We're here to help! 😊

**Comment by LiuYFxixi** [comment]
ERROR: Could not find a version that satisfies the requirement deep_sort_realtime (from versions: none)
ERROR: No matching distribution found for deep_sort_realtime
How can i solve this question

**Comment by glenn-jocher** [comment]
@LiuYFxixi it seems like `deep_sort_realtime` is not available in your package index. Please try installing `deep_sort_pytorch` directly from its GitHub repository using: `pip install git+https://github.com/ZQPei/deep_sort_pytorch.git`.

**Comment by raselsarker69** [comment]
good

**Comment by glenn-jocher** [comment]
The error occurs because the `deep_sort_pytorch` package isn't installed correctly. To resolve this, please ensure you're using the correct installation command from the official repository:  
```bash
pip install git+https://github.com/ZQPei/deep_sort_pytorch.git
```  
If issues persist, verify your Python environment and dependencies. For Ultralytics-related support, explore our [documentation](https://docs.ultralytics.com) or open a GitHub Issue with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example).
