### ISSUE TITLE
tflite model not inferencing right

### ISSUE THREAD

**Issue by RwGrid** [ultralytics/ultralytics#1423]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

ValueError: Cannot set tensor: Dimension mismatch. Got 640 but expected 320 for dimension 1 of input 0.

In tensorflow lite loaded model cannot load model and inference

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@RwGrid you exported your TFLite model at imgsz=320 but your're trying to run inference at the default imgsz=640. You need to pass imgsz=320 when predicting with this model.
