### ISSUE TITLE
Reducing size of labels produced on detect.py

### ISSUE THREAD

**Issue by MoussaGRICHE** [ultralytics/ultralytics#1424]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can i reduce the size of the labels and confidence that are drawn with the bboxes so that i can display each label with its associated confidence clearly in the image?
![test_image_3](https://user-images.githubusercontent.com/103992437/225032625-fe9153be-9692-436d-b25c-bae69943bf9e.jpg)

It will be better if i could keep the label and the confidence.

I am using yolov8 with api.

Thank you

**Comment by glenn-jocher** [comment]
@MoussaGRICHE you can change linewidth and annotation settings to suit your needs. See available arguments here:
https://github.com/ultralytics/ultralytics/blob/30fc4b537ff1d9b115bc1558884f6bc2696a282c/ultralytics/yolo/cfg/default.yaml#L51-L67

**Comment by MoussaGRICHE** [comment]
@glenn-jocher thank you so much, it works perfectly now.

A quick question please, the count function with the tracking, does it available with yolov8?

Thank you.

**Comment by glenn-jocher** [comment]
@MoussaGRICHE there's no high-order count functionality built-in yet, we could add an abstraction layer above tracking for that. Of course you can also just count the number of total track IDs in a video as a proxy for counting, but ideally you want to establish a line across the image space and only increment a counter when track IDs over two frames intersect the line. This would be more accurate.
