### ISSUE TITLE
YOLONAS  bug

### ISSUE THREAD

**Issue by KTXKIKI** [ultralytics/ultralytics#14254]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Val, Predict

### Bug

CustomizableDetector.forward() got an unexpected keyword argument 'augment'\n",

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@KTXKIKI hello,

Thank you for reporting this issue and for your willingness to contribute a PR! To better assist you, could you please provide a minimal reproducible example? This will help us diagnose the problem more effectively. You can find guidelines on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of all relevant packages, as updates often include important bug fixes.

Looking forward to your response and thank you for your collaboration! 😊
