### ISSUE TITLE
get training progress

### ISSUE THREAD

**Issue by ylfmsn** [ultralytics/ultralytics#14258]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, is there an API interface that can get the training progress? Or get the current training status? I need to integrate yolov8 into my web application, but it is difficult to get the progress or status of the training.

**Comment by ylfmsn** [comment]
Thank you very much. Your answer is very helpful to me. I just want to ask another question. Is it possible to pass a log path variable in the API Integration? In other words, how to modify the training_progress.json file where the log is written into a log path variable? I want each training to have its own independent log output. Thanks again.

**Comment by ylfmsn** [comment]
> @ylfmsn hello,
> 
> Thank you for reaching out! Yes, you can monitor the training progress of YOLOv8 models using the built-in logging and callback functionalities. Here's a concise guide on how you can achieve this:
> 
> ### Using Callbacks
> YOLOv8 supports custom callbacks that can be used to track the training progress. You can define a custom callback to log the training status and progress. Here’s an example:
> 
> ```python
> from ultralytics import YOLO
> from ultralytics.yolo.engine.trainer import BaseTrainer
> 
> class ProgressCallback(BaseTrainer):
>     def on_epoch_end(self, epoch, results):
>         print(f"Epoch {epoch + 1}/{self.epochs} - Loss: {results['loss']:.4f}")
> 
> # Load a model
> model = YOLO("yolov8n.pt")
> 
> # Train the model with the custom callback
> model.train(data="coco128.yaml", epochs=100, callbacks=[ProgressCallback])
> ```
> 
> ### Using TensorBoard
> Another way to monitor training progress is by using TensorBoard. YOLOv8 integrates seamlessly with TensorBoard, allowing you to visualize training metrics in real-time.
> 
> ```shell
> # Start training with TensorBoard logging
> yolo train model=yolov8n.pt data=coco128.yaml epochs=100 --logdir runs/train
> ```
> 
> Then, you can start TensorBoard to visualize the progress:
> 
> ```shell
> tensorboard --logdir runs/train
> ```
> 
> ### API Integration
> For integrating YOLOv8 into your web application, you might want to periodically check the status of the training process. You can achieve this by logging the progress to a file or a database and then querying this information from your web application.
> 
> ```python
> import json
> 
> class ProgressCallback(BaseTrainer):
>     def on_epoch_end(self, epoch, results):
>         progress = {
>             "epoch": epoch + 1,
>             "total_epochs": self.epochs,
>             "loss": results['loss']
>         }
>         with open("training_progress.json", "w") as f:
>             json.dump(progress, f)
> 
> # Load a model
> model = YOLO("yolov8n.pt")
> 
> # Train the model with the custom callback
> model.train(data="coco128.yaml", epochs=100, callbacks=[ProgressCallback])
> ```
> 
> This way, you can read the `training_progress.json` file from your web application to get the current training status.
> 
> I hope this helps! If you have any further questions, feel free to ask. 😊

Thank you very much. Your answer is very helpful to me. I just want to ask another question. Is it possible to pass a log path variable in the API Integration? In other words, how to modify the training_progress.json file where the log is written into a log path variable? I want each training to have its own independent log output. Thanks again.

**Comment by ylfmsn** [comment]
@glenn-jocher Thank you very much. Your answer is very helpful to me. I just want to ask another question. Is it possible to pass a log path variable in the API Integration? In other words, how to modify the training_progress.json file where the log is written into a log path variable? I want each training to have its own independent log output. Thanks again.

**Comment by glenn-jocher** [comment]
Hello @ylfmsn,

I'm glad to hear that the previous response was helpful! Yes, you can certainly customize the log path for each training session to ensure that each run has its own independent log output. You can achieve this by passing a log path variable to your custom callback. Here’s an example of how you can do this:

```python
import json
from ultralytics import YOLO
from ultralytics.yolo.engine.trainer import BaseTrainer

class ProgressCallback(BaseTrainer):
    def __init__(self, log_path, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.log_path = log_path

    def on_epoch_end(self, epoch, results):
        progress = {
            "epoch": epoch + 1,
            "total_epochs": self.epochs,
            "loss": results['loss']
        }
        with open(self.log_path, "w") as f:
            json.dump(progress, f)

# Load a model
model = YOLO("yolov8n.pt")

# Define the log path
log_path = "path/to/your/log/training_progress.json"

# Train the model with the custom callback
model.train(data="coco128.yaml", epochs=100, callbacks=[ProgressCallback(log_path)])
```

In this example, you can specify a different `log_path` for each training session, ensuring that each run has its own log file. This approach provides flexibility and helps in organizing logs for different training sessions.

Feel free to reach out if you have any more questions. Happy training! 😊
