### ISSUE TITLE
Prohibit color enhancement, but it does not take effect

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#14250]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![aaaaaaaaaaaaaaaaaaaa](https://github.com/ultralytics/ultralytics/assets/6490927/0b8b36aa-c355-433f-8b4f-c2d3edf38f5f)
Image Classification

model.train(data="home", epochs=100, imgsz=224,hsv_h: 0.0 ,hsv_s: 0.0,hsv_v: 0.0)

`auto_augment`
(randaugment, autoaugment, augmix)
How to customize and adjust the type of enhancement, without color enhancement

**Comment by glenn-jocher** [comment]
@monkeycc hello,

Thank you for reaching out! It looks like you're trying to disable color augmentation during training, but it's not taking effect. To ensure that color augmentations such as hue, saturation, and value adjustments are disabled, you can set the corresponding hyperparameters to zero in your training configuration.

Here's a more detailed example of how you can achieve this:

```python
from ultralytics import YOLO

# Load your model
model = YOLO("yolov8n.pt")

# Train the model with color augmentations disabled
results = model.train(
    data="home",
    epochs=100,
    imgsz=224,
    hsv_h=0.0,
    hsv_s=0.0,
    hsv_v=0.0,
    auto_augment=None  # Ensure no auto augmentation is applied
)
```

In this example, `hsv_h`, `hsv_s`, and `hsv_v` are set to `0.0` to disable hue, saturation, and value augmentations. Additionally, setting `auto_augment=None` ensures that no automatic augmentation policies like `randaugment`, `autoaugment`, or `augmix` are applied.

If the issue persists, please ensure you are using the latest version of the Ultralytics package. If you continue to encounter problems, providing a minimum reproducible example would be very helpful for us to diagnose the issue further. You can find more information on creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions or need further assistance. Happy training! 😊
