### ISSUE TITLE
Change mosaic_min_rate

### ISSUE THREAD

**Issue by ZooKangaroo** [ultralytics/ultralytics#14260]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I change the hyp of mosaic_min_ratio when training? I found that there's not the hyp. Should I download all the codes, deactivate the python-envs, and change it in the funcion? Is there any easier way to set the parameter in "yolo train model=.pt data=.yaml mosaic=1"

I found that every time in train_batch.jpg, some boxes with too small size also exist, which should be ignored

### Additional
![image](https://github.com/ultralytics/ultralytics/assets/52917842/9a5721de-b7ca-44b6-886d-dd7bd1330b8b)

_No response_

**Comment by glenn-jocher** [comment]
Hello,

Thank you for reaching out! You can indeed adjust the `mosaic_min_ratio` hyperparameter without needing to download and modify the source code directly. Instead, you can specify this parameter in your training command using the `--hyp` argument to point to a custom YAML file where you define your hyperparameters.

Here's a step-by-step guide:

1. **Create a Custom Hyperparameters File**: Create a YAML file (e.g., `custom_hyp.yaml`) and include the `mosaic_min_ratio` parameter along with any other hyperparameters you wish to customize. For example:
    ```yaml
    mosaic_min_ratio: 0.2  # Adjust this value as needed
    # Add other hyperparameters here
    ```

2. **Run the Training Command**: Use the `--hyp` argument to specify your custom hyperparameters file in the training command:
    ```bash
    yolo train model=your_model.pt data=your_data.yaml hyp=custom_hyp.yaml
    ```

This approach allows you to easily modify hyperparameters without altering the core codebase or environment.

Additionally, if you haven't already, please ensure you are using the latest version of the Ultralytics packages to benefit from the latest features and bug fixes.

If you encounter any further issues or have more questions, feel free to ask. Happy training! 🚀
