### ISSUE TITLE
Low performance and big inference time 

### ISSUE THREAD

**Issue by XuliGan4eg2006** [ultralytics/ultralytics#14278]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Hello, I have faced with issue that my cpu is in 20% of load while model running detection.
![image](https://github.com/ultralytics/ultralytics/assets/62839426/2c301555-b219-42f2-8a2b-65d5069dad7f)
![image](https://github.com/ultralytics/ultralytics/assets/62839426/4cdfec9f-b41a-4c77-a2c1-15bb5053927f)
![image](https://github.com/ultralytics/ultralytics/assets/62839426/f371c91d-3409-4443-b5fb-c74136798b70)
I know that I can use my gpu to make it faster, but I want to know why performance on cpu is so low

### Environment

Ultralytics YOLOv8.2.51 🚀 Python-3.12.4 torch-2.3.1+cpu CPU (AMD Ryzen 5 4500 6-Core Processor)
Setup complete ✅ (12 CPUs, 31.9 GB RAM, 97.3/953.1 GB disk)

OS                  Windows-11-10.0.22631-SP0
Environment         Windows
Python              3.12.4
Install             pip
RAM                 31.87 GB
CPU                 AMD Ryzen 5 4500 6-Core Processor
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.3.1>=1.8.0
torchvision         ✅ 0.18.1>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

``` from ultralytics import YOLO
import cv2

cap = cv2.VideoCapture("http://192.168.0.137:8080/video")
model = YOLO("yolov8n.pt")

id_map = {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted plant', 59: 'bed', 60: 'dining table', 61: 'toilet', 62: 'tv', 63: 'laptop', 64: 'mouse', 65: 'remote', 66: 'keyboard', 67: 'cell phone', 68: 'microwave', 69: 'oven', 70: 'toaster', 71: 'sink', 72: 'refrigerator', 73: 'book', 74: 'clock', 75: 'vase', 76: 'scissors', 77: 'teddy bear', 78: 'hair drier', 79: 'toothbrush'}


while True:
    # Read the frame from the webcam
    ret, frame = cap.read()

    # Detect objects in the frame
    results = model.predict(source=frame, classes=[0, 17], stream=True)
    for result in results:
        for box in result.boxes:
            cv2.rectangle(frame, (int(box.xyxy[0][0]), int(box.xyxy[0][1])), (int(box.xyxy[0][2]), int(box.xyxy[0][3])), (0, 255, 0), 2)
            cv2.putText(frame, id_map[int(box.cls[0])], (int(box.xyxy[0][0]), int(box.xyxy[0][1])), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
    # Show the frame
    cv2.imshow("Webcam", frame)

    # Check for the 'q' key to exit the loop
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the webcam and close the window
cap.release()
cv2.destroyAllWindows()

```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
You can convert to ONNX. One Python process can only utilize one core of CPU, so you won't reach 100% CPU usage.

**Comment by glenn-jocher** [comment]
@Y-T-G hello,

Thank you for reaching out and providing detailed information about your issue. It's great to see your interest in optimizing YOLOv8 performance on CPU.

As you mentioned, converting your model to ONNX can indeed help improve performance. ONNX models can be optimized and run efficiently on various hardware, including CPUs, using frameworks like ONNX Runtime.

Here's a quick guide on how to export your YOLOv8 model to ONNX and run inference using ONNX Runtime:

1. **Export the model to ONNX:**
   ```python
   from ultralytics import YOLO

   # Load your YOLOv8 model
   model = YOLO("yolov8n.pt")

   # Export the model to ONNX format
   model.export(format="onnx")
   ```

2. **Run inference using ONNX Runtime:**
   ```python
   import onnxruntime as ort
   import numpy as np
   import cv2

   # Load the ONNX model
   ort_session = ort.InferenceSession("yolov8n.onnx")

   # Function to preprocess the image
   def preprocess(image):
       image = cv2.resize(image, (640, 640))
       image = image.transpose(2, 0, 1)  # HWC to CHW
       image = image.astype(np.float32) / 255.0
       image = np.expand_dims(image, axis=0)
       return image

   # Capture video
   cap = cv2.VideoCapture("http://192.168.0.137:8080/video")

   while True:
       ret, frame = cap.read()
       if not ret:
           break

       # Preprocess the frame
       input_image = preprocess(frame)

       # Run inference
       outputs = ort_session.run(None, {"images": input_image})

       # Process outputs (this will depend on your specific model and task)
       # ...

       # Display the frame
       cv2.imshow("Webcam", frame)
       if cv2.waitKey(1) & 0xFF == ord('q'):
           break

   cap.release()
   cv2.destroyAllWindows()
   ```

This approach should help you utilize your CPU more efficiently and potentially reduce inference time. Additionally, ensure you are using the latest versions of all relevant packages to benefit from the latest optimizations and bug fixes.

If you continue to experience issues or have further questions, feel free to ask. We're here to help!
