### ISSUE TITLE
Support for ROCm training (upgrade to pytorch 2.3 and tf16 or so)

### ISSUE THREAD

**Issue by JijaProGamer** [ultralytics/ultralytics#14279]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

As pytorch 2.3 seems to support ROC https://pytorch.org/docs/stable/notes/hip.html

With minimal code changes (only TF32 support is not present, but it uses the same cuda device as before), there should be a way to set up ultralytics to work with a amd gpu on Linux, especially when the changes should be minimal.

### Use case

AMD GPUs are 2-3x cheaper and have 2-3x more VRAM than their Nvidia counterparts, the only thing holding them back is the ROCm support in ultralytics.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by canadarob** [comment]
you can install the official rocm container. Then within that container install ultralytics.
That worked for me.

**Comment by JijaProGamer** [comment]
> you can install the official rocm container. Then within that container install ultralytics. That worked for me.

Thank you, can you go into more detail please? Did you install the ROCm container, or pytorch ROCm container, and on what OS?

**Comment by glenn-jocher** [comment]
@JijaProGamer thank you for sharing your experience! To provide more clarity for others who might benefit from this setup, could you please specify the exact steps you followed? For instance:

1. Did you use the official ROCm container or the PyTorch ROCm container?
2. Which operating system are you running this on?
3. Any specific versions of ROCm or PyTorch that you used?

Your detailed insights could be incredibly valuable for the community. Thank you! 🙌

**Comment by JijaProGamer** [comment]
> @JijaProGamer thank you for sharing your experience! To provide more clarity for others who might benefit from this setup, could you please specify the exact steps you followed? For instance:
> 
> 1. Did you use the official ROCm container or the PyTorch ROCm container?
> 2. Which operating system are you running this on?
> 3. Any specific versions of ROCm or PyTorch that you used?
> 
> Your detailed insights could be incredibly valuable for the community. Thank you! 🙌

I didn't end up using Docker, but I did get (training) to work

This are the following steps:

1. Install Ubuntu 22.04 (Ubuntu 20.04 didn't work due to python 3.8 being installed, ubuntu 22.04 has python 3.10 which works) on bare metal or a OS with a GPU passed
2. Install ROCm 6.0 (Has to be 6.0, other versions fail)
3.  Run this code to install dependencies:

`
pip install -U ultralytics
pip install roboflow
pip install -U tensorflow==2.15
pip install --upgrade tensorflow tensorflow-decision-forests tensorflowjs
`

4. make a folder in desktop, where you create a file main.py inside and place this code:

`
import os
from roboflow import Roboflow
from ultralytics import YOLO

roboflow_key = 'your roboflow key'
dataset_version = 1
dataset_name = "your dataset name (with the correct casing)"

os.system(f"rm -rf ./{dataset_name}-{dataset_version}")  

rf = Roboflow(api_key=roboflow_key)
project = rf.workspace().project(dataset_name.lower())
dataset = project.version(dataset_version).download('yolov8')

os.system(f"mv {dataset.location}/data.yaml {dataset.location}/../data.yaml")

model = YOLO("yolov8s.pt")

train_results = model.train(data=f"{dataset.location}/../data.yaml", epochs=1, batch=150, patience=50, device=0, imgsz=(320, 448), scale=0, rect=True)

metrics = model.val(save_json=True)

test_results = model.predict(source="https://youtu.be/eRGMiecRjik", imgsz=(320,448), conf=0.5, save=True)

model.export(format='tfjs', imgsz=(320,448))

os.system(f"mv {dataset.location}/../data.yaml {dataset.location}/data.yaml")
`

This does train the model correctly and does validation correctly, but fails at model.predict, since for some reason it cannot automatically download the video, but you can remove that line.

I suggest for the roboflow team to make a page on their website (or if I can make a PR or so), with these instructions.

**Comment by glenn-jocher** [comment]
Thank you for sharing your detailed steps, @JijaProGamer! This is incredibly helpful for the community. Here’s a concise summary of your process for getting Ultralytics training to work with ROCm on an AMD GPU:

1. **Install Ubuntu 22.04**: Ensure you have Python 3.10, as Python 3.8 on Ubuntu 20.04 didn't work.
2. **Install ROCm 6.0**: This specific version is required.
3. **Install Dependencies**:
    ```bash
    pip install -U ultralytics
    pip install roboflow
    pip install -U tensorflow==2.15
    pip install --upgrade tensorflow tensorflow-decision-forests tensorflowjs
    ```
4. **Create a Python Script** (`main.py`):
    ```python
    import os
    from roboflow import Roboflow
    from ultralytics import YOLO

    roboflow_key = 'your roboflow key'
    dataset_version = 1
    dataset_name = "your dataset name (with the correct casing)"

    os.system(f"rm -rf ./{dataset_name}-{dataset_version}")  

    rf = Roboflow(api_key=roboflow_key)
    project = rf.workspace().project(dataset_name.lower())
    dataset = project.version(dataset_version).download('yolov8')

    os.system(f"mv {dataset.location}/data.yaml {dataset.location}/../data.yaml")

    model = YOLO("yolov8s.pt")

    train_results = model.train(data=f"{dataset.location}/../data.yaml", epochs=1, batch=150, patience=50, device=0, imgsz=(320, 448), scale=0, rect=True)

    metrics = model.val(save_json=True)

    test_results = model.predict(source="https://youtu.be/eRGMiecRjik", imgsz=(320,448), conf=0.5, save=True)

    model.export(format='tfjs', imgsz=(320,448))

    os.system(f"mv {dataset.location}/../data.yaml {dataset.location}/data.yaml")
    ```
5. **Run the Script**:
    ```bash
    HSA_OVERRIDE_GFX_VERSION=10.3.0 PYTORCH_ROCM_ARCH="gfx1031" HIP_VISIBLE_DEVICES=0 ROCM_PATH=/opt/rocm python3 main.py
    ```
    Adjust `PYTORCH_ROCM_ARCH` and `HSA_OVERRIDE_GFX_VERSION` based on your AMD GPU model.

This setup successfully trains and validates the model, though there is an issue with `model.predict` when downloading videos. You can remove that line if needed.

For more detailed guidance on setting up Docker environments, you can refer to our [Docker Quickstart Guide](https://docs.ultralytics.com/guides/docker-quickstart/).

If you encounter any issues or have further questions, feel free to ask. Your contributions are greatly appreciated! 🚀
