### ISSUE TITLE
How can I implement tracking in a Yolov8 project that does not have all the images from the start

### ISSUE THREAD

**Issue by Cristofhersj** [ultralytics/ultralytics#1427]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a very similar problem to the one in this link: https://github.com/ultralytics/ultralytics/issues/1363

I have a project that generates images over time and I need to track the objects that appear in those images. The thing is that when I run the model.track() command in a cycle, the tracking gets reseted.

As Laughing-q says in one of the responses in the git question. My case needs a global tracker but I don't know how to implement it

Doing research about it I found out that using SORT could be a way to implement it but I'm not sure if its adecuate.

**Comment by pderrenger** [comment]
@Cristofhersj to implement object tracking in a YOLOv8 project where images are generated over time, a global tracker can be utilized to maintain consistency across frames. YOLOv8's `track()` command, when run in a cycle, resets the tracking, but you can maintain a global tracker outside the cycle to handle this.

One possible approach could be to use a global tracker like SORT (Simple Online and Realtime Tracking) to seamlessly track objects across frames. Essentially, SORT associates detections in different frames to track objects over time, providing a continuous tracking experience.

By arranging the YOLOv8's detection outputs and feeding them to the SORT algorithm, you can achieve consistent object tracking across sequentially generated images.

Feel free to reach out if you need further assistance integrating SORT or if you have any other questions!
