### ISSUE TITLE
Shifted bounding box after converting xview geojson annotation to yolo txt format

### ISSUE THREAD

**Issue by Raghavrs1999** [ultralytics/ultralytics#14287]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i had downloaded xview dataset from 'https://challenge.xviewdataset.org/download-links'  and i used code : 
'''
import json
import os
import cv2
from tqdm import tqdm

# Path to the GeoJSON file
geojson_path = 'E:/raghav/satellite_imagery/dataset/xview/xView_train.geojson'

# Directory to save YOLO annotations
output_dir = 'E:/raghav/satellite_imagery/dataset/xview/yolo_annotations'
os.makedirs(output_dir, exist_ok=True)
image_folder = "E:/raghav/satellite_imagery/dataset/xview/train_images/"
img_name = [os.path.basename(i) for i in os.listdir(image_folder)]

# Helper function to convert bounding box to YOLO format
def convert_to_yolo(bbox, img_width, img_height):
    x_min, y_min, x_max, y_max = bbox
    x_center = (x_min + x_max) / 2.0 / img_width
    y_center = (y_min + y_max) / 2.0 / img_height
    width = (x_max - x_min) / img_width
    height = (y_max - y_min) / img_height
    return x_center, y_center, width, height

# Load GeoJSON data
with open(geojson_path, 'r') as f:
    geojson_data = json.load(f)

# Get the dimensions of the first image
sample_img = cv2.imread(os.path.join(image_folder, img_name[0]))
image_height ,image_width = sample_img.shape[:2]

# Process each feature in the GeoJSON
annotations = {}
for feature in tqdm(geojson_data['features'], desc="Processing features"):
    properties = feature['properties']
    bounds_imcoords = list(map(float, properties['bounds_imcoords'].split(',')))
    class_id = properties['type_id']
    image_id = properties['image_id']
    
    if image_id in img_name:
        # Convert bounding box to YOLO format
        x_center, y_center, width, height = convert_to_yolo(bounds_imcoords, image_width, image_height)
        
        # YOLO annotation line
        yolo_annotation = f"{class_id} {x_center:.6f} {y_center:.6f} {width:.6f} {height:.6f}"
        
        if image_id not in annotations:
            annotations[image_id] = []
        annotations[image_id].append(yolo_annotation)

# Write annotations to files
for image_id, yolo_annotations in tqdm(annotations.items(), desc="Saving annotations"):
    annotation_path = os.path.join(output_dir, f"{os.path.splitext(image_id)[0]}.txt")
    with open(annotation_path, 'w') as f:
        for annotation in yolo_annotations:
            f.write(f"{annotation}\n")

print("YOLO annotations have been saved.")
'''

After converting the annotation i used :
''' import os
import cv2
from tqdm import tqdm

def visualize_yolo_annotations(image_folder, yolo_folder, classes, output_path):
    # Get a list of image and YOLO file paths
    image_paths = [os.path.join(image_folder, file) for file in os.listdir(image_folder) if file.lower().endswith(('.png', '.jpg', '.jpeg', '.tif'))]
    yolo_paths = [os.path.join(yolo_folder, file) for file in os.listdir(yolo_folder) if file.lower().endswith('.txt')]
    classes_discovered = []
    image_paths.sort()
    yolo_paths.sort()

    image_files = {os.path.splitext(os.path.basename(file))[0]: file for file in image_paths}
    yolo_files = {os.path.splitext(os.path.basename(file))[0]: file for file in yolo_paths}

    common_files = set(image_files.keys()).intersection(set(yolo_files.keys()))
    extra_images = set(image_files.keys()).difference(set(yolo_files.keys()))
    extra_labels = set(yolo_files.keys()).difference(set(image_files.keys()))

    print(f"Images without labels: {len(extra_images)}")
    print(f"Labels without images: {len(extra_labels)}")

    common_image_paths = [image_files[key] for key in common_files]
    common_yolo_paths = [yolo_files[key] for key in common_files]

    os.makedirs(output_path, exist_ok=True)

    current_index = 0
    total_images = len(common_image_paths)

    while True:
        image_path = common_image_paths[current_index]
        yolo_path = common_yolo_paths[current_index]
        
        # Read the image using OpenCV
        image = cv2.imread(image_path)
        # image = cv2.resize(image, (1280, 1280))

        # Get image width and height
        height,width, _ = image.shape

        # Read the YOLO file
        with open(yolo_path, "r") as yolo_file:
            lines = yolo_file.readlines()

        # Iterate through each line in the YOLO file
        for line in lines:
            values = line.split()
            class_id = int(values[0])
            if class_id > 59:
                label = "other"
            else:
                label = classes[class_id]
            x_center, y_center, box_width, box_height = map(float, values[1:5])

            if label not in classes_discovered:
                classes_discovered.append(label)

            # Convert YOLO format to absolute coordinates
            xmin = int((x_center - box_width / 2) * width)
            ymin = int((y_center - box_height / 2) * height)
            xmax = int((x_center + box_width / 2) * width)
            ymax = int((y_center + box_height / 2) * height)

            # Draw the bounding box using OpenCV
            color = (0, 0, 255)  # BGR format
            thickness = 1
            image = cv2.rectangle(image, (xmin, ymin), (xmax, ymax), color, thickness)
            cv2.putText(image, label, (xmin, ymin - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.4, color, thickness)
        # Write the image
        cv2.imwrite(f"{output_path}/{current_index}.jpg", image)
        # Display the image
        image = cv2.resize(image, (1600, 820))
        cv2.imshow("Image with YOLO Annotations", image)
        key = cv2.waitKey()  # You can put the wait time instead of pressing any button

        if key == ord('q') or key == 27:  # 'q' or 'ESC' to quit
            cv2.destroyAllWindows()
            break
        elif key == ord("a"):  # Left arrow key to go to previous image
            current_index = (current_index - 1) % total_images
        elif key == ord("d"):  # Right arrow key to go to next image
            current_index = (current_index + 1) % total_images

    cv2.destroyAllWindows()
    print("😊\nYou have watched: ", classes_discovered, " classes till window get closed.")

image_folder = "E:/raghav/satellite_imagery/dataset/xview/train_images"  # Enter the path where images are stored
yolo_folder = "E:/raghav/satellite_imagery/dataset/xview/yolo_annotations"  # Enter the path of your txt file 
classes = ['Fixed-wing Aircraft', 'Small Aircraft', 'Cargo Plane', 'Helicopter', 'Passenger Vehicle', 'Small Car', 'Bus', 'Pickup Truck', 'Utility Truck', 'Truck', 'Cargo Truck', 'Truck w/Box', 'Truck Tractor', 'Trailer', 'Truck w/Flatbed', 'Truck w/Liquid', 'Crane Truck', 'Railway Vehicle', 'Passenger Car', 'Cargo Car', 'Flat Car', 'Tank car', 'Locomotive', 'Maritime Vessel', 'Motorboat', 'Sailboat', 'Tugboat', 'Barge', 'Fishing Vessel', 'Ferry', 'Yacht', 'Container Ship', 'Oil Tanker', 'Engineering Vehicle', 'Tower crane', 'Container Crane', 'Reach Stacker', 'Straddle Carrier', 'Mobile Crane', 'Dump Truck', 'Haul Truck', 'Scraper/Tractor', 'Front loader/Bulldo zer', 'Excavator', 'Cement Mixer', 'Ground Grader', 'Hut/Tent', 'Shed', 'Building', 'Aircraft Hangar', 'Damaged Building', 'Facility', 'Construction Site', 'Vehicle Lot', 'Helipad', 'Storage Tank', 'Shipping container lot', 'Shipping Container', 'Pylon', 'Tower']
output_path = "E:/raghav/satellite_imagery/dataset/xview/annotated"
visualize_yolo_annotations(image_folder, yolo_folder, classes, output_path)
'''
for visualization. I saw shifted annotation boxes like:

 
![2](https://github.com/ultralytics/ultralytics/assets/88829086/907b6027-97c6-4d19-a85c-08c5e6bdf6d8)
![3](https://github.com/ultralytics/ultralytics/assets/88829086/a4c16f68-fea7-40bc-8459-6c2cc575a293)

Please help out it find the bug

**Comment by glenn-jocher** [comment]
@Raghavrs1999 hi there! 👋

Thank you for providing detailed information and code snippets. It looks like you're encountering an issue with shifted bounding boxes after converting xView GeoJSON annotations to YOLO format. Let's troubleshoot this together.

### Potential Issues and Solutions

1. **Bounding Box Conversion**:
   Ensure that the bounding box coordinates are correctly converted from the GeoJSON format to the YOLO format. The conversion function looks correct, but it's good to double-check the input values and the conversion logic.

2. **Image Dimensions**:
   Verify that the image dimensions used in the conversion are accurate. The dimensions should match the actual size of each image being processed. If the dimensions are incorrect, the bounding boxes will be misaligned.

3. **Class Mapping**:
   Ensure that the class IDs are correctly mapped from the xView dataset to the YOLO format. The class ID conversion logic should be consistent with the dataset's annotation scheme.

### Suggested Debugging Steps

1. **Print Debug Statements**:
   Add print statements to check the intermediate values during the conversion process. This can help identify where the values might be going wrong.

2. **Visualize Intermediate Results**:
   Visualize the bounding boxes on the images before saving them to ensure they are correctly aligned.

3. **Check Image Dimensions**:
   Ensure that the dimensions used in the `convert_to_yolo` function match the actual image dimensions.

Here's a refined version of your conversion script with added debug statements:

```python
import json
import os
import cv2
from tqdm import tqdm

# Path to the GeoJSON file
geojson_path = 'E:/raghav/satellite_imagery/dataset/xview/xView_train.geojson'

# Directory to save YOLO annotations
output_dir = 'E:/raghav/satellite_imagery/dataset/xview/yolo_annotations'
os.makedirs(output_dir, exist_ok=True)
image_folder = "E:/raghav/satellite_imagery/dataset/xview/train_images/"
img_name = [os.path.basename(i) for i in os.listdir(image_folder)]

# Helper function to convert bounding box to YOLO format
def convert_to_yolo(bbox, img_width, img_height):
    x_min, y_min, x_max, y_max = bbox
    x_center = (x_min + x_max) / 2.0 / img_width
    y_center = (y_min + y_max) / 2.0 / img_height
    width = (x_max - x_min) / img_width
    height = (y_max - y_min) / img_height
    return x_center, y_center, width, height

# Load GeoJSON data
with open(geojson_path, 'r') as f:
    geojson_data = json.load(f)

# Process each feature in the GeoJSON
annotations = {}
for feature in tqdm(geojson_data['features'], desc="Processing features"):
    properties = feature['properties']
    bounds_imcoords = list(map(float, properties['bounds_imcoords'].split(',')))
    class_id = properties['type_id']
    image_id = properties['image_id']
    
    if image_id in img_name:
        # Get the dimensions of the current image
        image_path = os.path.join(image_folder, image_id)
        image = cv2.imread(image_path)
        image_height, image_width = image.shape[:2]

        # Convert bounding box to YOLO format
        x_center, y_center, width, height = convert_to_yolo(bounds_imcoords, image_width, image_height)
        
        # YOLO annotation line
        yolo_annotation = f"{class_id} {x_center:.6f} {y_center:.6f} {width:.6f} {height:.6f}"
        
        if image_id not in annotations:
            annotations[image_id] = []
        annotations[image_id].append(yolo_annotation)

# Write annotations to files
for image_id, yolo_annotations in tqdm(annotations.items(), desc="Saving annotations"):
    annotation_path = os.path.join(output_dir, f"{os.path.splitext(image_id)[0]}.txt")
    with open(annotation_path, 'w') as f:
        for annotation in yolo_annotations:
            f.write(f"{annotation}\n")

print("YOLO annotations have been saved.")
```

### Visualization Script

Ensure that the visualization script correctly reads the image dimensions and annotations:

```python
import os
import cv2
from tqdm import tqdm

def visualize_yolo_annotations(image_folder, yolo_folder, classes, output_path):
    image_paths = [os.path.join(image_folder, file) for file in os.listdir(image_folder) if file.lower().endswith(('.png', '.jpg', '.jpeg', '.tif'))]
    yolo_paths = [os.path.join(yolo_folder, file) for file in os.listdir(yolo_folder) if file.lower().endswith('.txt')]
    classes_discovered = []
    image_paths.sort()
    yolo_paths.sort()

    image_files = {os.path.splitext(os.path.basename(file))[0]: file for file in image_paths}
    yolo_files = {os.path.splitext(os.path.basename(file))[0]: file for file in yolo_paths}

    common_files = set(image_files.keys()).intersection(set(yolo_files.keys()))
    extra_images = set(image_files.keys()).difference(set(yolo_files.keys()))
    extra_labels = set(yolo_files.keys()).difference(set(image_files.keys()))

    print(f"Images without labels: {len(extra_images)}")
    print(f"Labels without images: {len(extra_labels)}")

    common_image_paths = [image_files[key] for key in common_files]
    common_yolo_paths = [yolo_files[key] for key in common_files]

    os.makedirs(output_path, exist_ok=True)

    current_index = 0
    total_images = len(common_image_paths)

    while True:
        image_path = common_image_paths[current_index]
        yolo_path = common_yolo_paths[current_index]
        
        # Read the image using OpenCV
        image = cv2.imread(image_path)
        height, width, _ = image.shape

        # Read the YOLO file
        with open(yolo_path, "r") as yolo_file:
            lines = yolo_file.readlines()

        # Iterate through each line in the YOLO file
        for line in lines:
            values = line.split()
            class_id = int(values[0])
            if class_id > 59:
                label = "other"
            else:
                label = classes[class_id]
            x_center, y_center, box_width, box_height = map(float, values[1:5])

            if label not in classes_discovered:
                classes_discovered.append(label)

            # Convert YOLO format to absolute coordinates
            xmin = int((x_center - box_width / 2) * width)
            ymin = int((y_center - box_height / 2) * height)
            xmax = int((x_center + box_width / 2) * width)
            ymax = int((y_center + box_height / 2) * height)

            # Draw the bounding box using OpenCV
            color = (0, 0, 255)  # BGR format
            thickness = 1
            image = cv2.rectangle(image, (xmin, ymin), (xmax, ymax), color, thickness)
            cv2.putText(image, label, (xmin, ymin - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.4, color, thickness)
        
        # Write the image
        cv2.imwrite(f"{output_path}/{current_index}.jpg", image)
        # Display the image
        image = cv2.resize(image, (1600, 820))
        cv2.imshow("Image with YOLO Annotations", image)
        key = cv2.waitKey()

        if key == ord('q') or key == 27:  # 'q' or 'ESC' to quit
            cv2.destroyAllWindows()
            break
        elif key == ord("a"):  # Left arrow key to go to previous image
            current_index = (current_index - 1) % total_images
        elif key == ord("d"):  # Right arrow key to go to next image
            current_index = (current_index + 1) % total_images

    cv2.destroyAllWindows()
    print("😊\nYou have watched: ", classes_discovered, " classes till window get closed.")

image_folder = "E:/raghav/satellite_imagery/dataset/xview/train_images"
yolo_folder = "E:/raghav/satellite_imagery/dataset/xview/yolo_annotations"
classes = ['Fixed-wing Aircraft', 'Small Aircraft', 'Cargo Plane', 'Helicopter', 'Passenger Vehicle', 'Small Car', 'Bus', 'Pickup Truck', 'Utility Truck', 'Truck', 'Cargo Truck', 'Truck w/Box', 'Truck Tractor', 'Trailer', 'Truck w/Flatbed', 'Truck w/Liquid', 'Crane Truck', 'Railway Vehicle', 'Passenger Car', 'Cargo Car', 'Flat Car', 'Tank car', 'Locomotive', 'Maritime Vessel', 'Motorboat', 'Sailboat', 'Tugboat', 'Barge', 'Fishing Vessel', 'Ferry', 'Yacht', 'Container Ship', 'Oil Tanker', 'Engineering Vehicle', 'Tower crane', 'Container Crane', 'Reach Stacker', 'Straddle Carrier', 'Mobile Crane', 'Dump Truck', 'Haul Truck', 'Scraper/Tractor', 'Front loader/Bulldozer', 'Excavator', 'Cement Mixer', 'Ground Grader', 'Hut/Tent', 'Shed', 'Building', 'Aircraft Hangar', 'Damaged Building', 'Facility', 'Construction Site', 'Vehicle Lot', 'Helipad', 'Storage Tank', 'Shipping container lot', 'Shipping Container', 'Pylon', 'Tower']
output_path = "E:/raghav/satellite_imagery/dataset/xview/annotated"
visualize_yolo_annotations(image_folder, yolo_folder, classes, output_path)
```

### Additional Resources

For more details on converting and visualizing annotations, you can refer to the [xView dataset documentation](https://docs.ultralytics.com/datasets/detect/xview/).

If the issue persists, please ensure you are using the latest versions of the packages and provide a minimum reproducible example as outlined [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

I hope this helps! If you have any further questions, feel free to ask. 😊

**Comment by Raghavrs1999** [comment]
Thanks @glenn-jocher it worked😊

**Comment by glenn-jocher** [comment]
Hi @Raghavrs1999,

I'm glad to hear that it worked! 😊 If you have any more questions or run into any other issues, feel free to ask. We're here to help!

For future reference, if you encounter any other issues or have suggestions, providing a minimum reproducible example can greatly expedite the troubleshooting process. You can find more details on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Keep up the great work with your project, and happy coding!
