### ISSUE TITLE
Write Segmentation on another image in Python 

### ISSUE THREAD

**Issue by vincenzomarotta** [ultralytics/ultralytics#14305]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello! I'd like to achive something here but I don't know if it's possible.
I want to detect a specific object (a car, for example) and I want to write car segmentation on another image that I already have. Just the segmentation.

Is it possible to achive something like that in Python? If not, is there a workaround?

Thank you for your time

**Comment by glenn-jocher** [comment]
@vincenzomarotta hello! 👋

Yes, it's definitely possible to achieve what you're aiming for using Ultralytics YOLOv8 in Python. You can detect a specific object, such as a car, and then overlay the segmentation mask onto another image. Here's a step-by-step guide to help you get started:

1. **Load the YOLOv8 Segmentation Model and Run Inference:**
   ```python
   from ultralytics import YOLO

   # Load the YOLOv8 segmentation model
   model = YOLO("yolov8n-seg.pt")

   # Run inference on the source image
   results = model.predict(source="path/to/your/source_image.jpg")
   ```

2. **Extract the Segmentation Mask:**
   ```python
   import numpy as np
   import cv2

   # Get the original image and the segmentation mask
   img = np.copy(results[0].orig_img)
   b_mask = np.zeros(img.shape[:2], np.uint8)
   
   # Assuming you want the first detected object
   contour = results[0].masks.xy[0].astype(np.int32).reshape(-1, 1, 2)
   cv2.drawContours(b_mask, [contour], -1, (255, 255, 255), cv2.FILLED)
   ```

3. **Overlay the Segmentation Mask onto Another Image:**
   ```python
   # Load the target image where you want to overlay the segmentation
   target_img = cv2.imread("path/to/your/target_image.jpg")

   # Ensure the target image is the same size as the source image
   target_img_resized = cv2.resize(target_img, (img.shape[1], img.shape[0]))

   # Convert the binary mask to a 3-channel mask
   mask3ch = cv2.cvtColor(b_mask, cv2.COLOR_GRAY2BGR)

   # Overlay the mask on the target image
   overlay = cv2.bitwise_and(mask3ch, target_img_resized)

   # Save or display the result
   cv2.imwrite("path/to/save/overlayed_image.jpg", overlay)
   cv2.imshow("Overlayed Image", overlay)
   cv2.waitKey(0)
   cv2.destroyAllWindows()
   ```

This code will detect the car in the source image, create a segmentation mask, and then overlay that mask onto another image. You can adjust the code to handle multiple detections or specific classes as needed.

For more detailed guidance, you can refer to our [guide on isolating segmentation objects](https://docs.ultralytics.com/guides/isolating-segmentation-objects/).

If you encounter any issues, please ensure you are using the latest version of the Ultralytics package. If the problem persists, providing a reproducible example will help us assist you better. You can find more information on creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Happy coding! 😊

**Comment by vincenzomarotta** [comment]
> @vincenzomarotta hello! 👋
> 
> Yes, it's definitely possible to achieve what you're aiming for using Ultralytics YOLOv8 in Python. You can detect a specific object, such as a car, and then overlay the segmentation mask onto another image. Here's a step-by-step guide to help you get started:
> 
> 1. **Load the YOLOv8 Segmentation Model and Run Inference:**
>    ```python
>    from ultralytics import YOLO
>    
>    # Load the YOLOv8 segmentation model
>    model = YOLO("yolov8n-seg.pt")
>    
>    # Run inference on the source image
>    results = model.predict(source="path/to/your/source_image.jpg")
>    ```
> 2. **Extract the Segmentation Mask:**
>    ```python
>    import numpy as np
>    import cv2
>    
>    # Get the original image and the segmentation mask
>    img = np.copy(results[0].orig_img)
>    b_mask = np.zeros(img.shape[:2], np.uint8)
>    
>    # Assuming you want the first detected object
>    contour = results[0].masks.xy[0].astype(np.int32).reshape(-1, 1, 2)
>    cv2.drawContours(b_mask, [contour], -1, (255, 255, 255), cv2.FILLED)
>    ```
> 3. **Overlay the Segmentation Mask onto Another Image:**
>    ```python
>    # Load the target image where you want to overlay the segmentation
>    target_img = cv2.imread("path/to/your/target_image.jpg")
>    
>    # Ensure the target image is the same size as the source image
>    target_img_resized = cv2.resize(target_img, (img.shape[1], img.shape[0]))
>    
>    # Convert the binary mask to a 3-channel mask
>    mask3ch = cv2.cvtColor(b_mask, cv2.COLOR_GRAY2BGR)
>    
>    # Overlay the mask on the target image
>    overlay = cv2.bitwise_and(mask3ch, target_img_resized)
>    
>    # Save or display the result
>    cv2.imwrite("path/to/save/overlayed_image.jpg", overlay)
>    cv2.imshow("Overlayed Image", overlay)
>    cv2.waitKey(0)
>    cv2.destroyAllWindows()
>    ```
> 
> This code will detect the car in the source image, create a segmentation mask, and then overlay that mask onto another image. You can adjust the code to handle multiple detections or specific classes as needed.
> 
> For more detailed guidance, you can refer to our [guide on isolating segmentation objects](https://docs.ultralytics.com/guides/isolating-segmentation-objects/).
> 
> If you encounter any issues, please ensure you are using the latest version of the Ultralytics package. If the problem persists, providing a reproducible example will help us assist you better. You can find more information on creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> Happy coding! 😊

Hi  @glenn-jocher , thank you for your time.

Thanks, the solution works but I've got a problem, it's like I write on the image everything except the contour. I'll show you:
OG image:
![car](https://github.com/ultralytics/ultralytics/assets/59702640/ad0f4113-7e20-46af-b84d-bbd6965e31d6)

Target Image (just a white wallpaper):
![white](https://github.com/ultralytics/ultralytics/assets/59702640/7d8ba93f-675b-49da-8fcc-b434126af7d6)

Result:
![over](https://github.com/ultralytics/ultralytics/assets/59702640/e6e53913-b128-4703-9cb9-87797134336d)

I'd like to achive the opposite, on the white image write the black contour because I need to write a contour on a pose detection and like that I cover everything up

**Comment by glenn-jocher** [comment]
Hi @vincenzomarotta,

Thank you for sharing the details and images. I understand that you want to draw only the contour of the detected object on the target image. Here's how you can achieve that:

1. **Load the YOLOv8 Segmentation Model and Run Inference:**
   ```python
   from ultralytics import YOLO

   # Load the YOLOv8 segmentation model
   model = YOLO("yolov8n-seg.pt")

   # Run inference on the source image
   results = model.predict(source="path/to/your/source_image.jpg")
   ```

2. **Extract the Segmentation Mask and Draw the Contour:**
   ```python
   import numpy as np
   import cv2

   # Get the original image and the segmentation mask
   img = np.copy(results[0].orig_img)
   b_mask = np.zeros(img.shape[:2], np.uint8)
   
   # Assuming you want the first detected object
   contour = results[0].masks.xy[0].astype(np.int32).reshape(-1, 1, 2)
   cv2.drawContours(b_mask, [contour], -1, (255, 255, 255), cv2.FILLED)
   ```

3. **Draw the Contour on the Target Image:**
   ```python
   # Load the target image where you want to draw the contour
   target_img = cv2.imread("path/to/your/target_image.jpg")

   # Ensure the target image is the same size as the source image
   target_img_resized = cv2.resize(target_img, (img.shape[1], img.shape[0]))

   # Draw the contour on the target image
   cv2.drawContours(target_img_resized, [contour], -1, (0, 0, 0), 2)  # Draw contour with black color and thickness 2

   # Save or display the result
   cv2.imwrite("path/to/save/contour_image.jpg", target_img_resized)
   cv2.imshow("Contour Image", target_img_resized)
   cv2.waitKey(0)
   cv2.destroyAllWindows()
   ```

This code will draw only the contour of the detected object on the target image, which should give you the desired result. If you encounter any further issues, please ensure you are using the latest version of the Ultralytics package. If the problem persists, providing a reproducible example will help us assist you better. You can find more information on creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Happy coding! 😊

**Comment by vincenzomarotta** [comment]
@glenn-jocher Thank you! I've tried it and it works how I wanted it!

**Comment by glenn-jocher** [comment]
Hi @vincenzomarotta,

That's fantastic to hear! 🎉 I'm glad the solution worked for you as intended. If you have any more questions or need further assistance with your project, feel free to reach out. We're here to help!

Happy coding and best of luck with your work! 😊
