### ISSUE TITLE
impact of gpt4 on object detection?

### ISSUE THREAD

**Issue by akashAD98** [ultralytics/ultralytics#1432]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

GPT-4 is a large multimodal model (accepting image and text inputs, emitting text outputs)

its detects complex images, even sometimes its hard in object detection to detect these objects,but gpt4 is doing it. 

<img width="415" alt="image" src="https://user-images.githubusercontent.com/62583018/225205384-c37a1501-61c1-45a8-8111-735b4db460e7.png">

**Comment by AyushExel** [comment]
Well, the real use case is not detecting objects. It is getting a model that is capable of detecting objects accurately enough to be used for real-world scenarios AND can be trained on any custom dataset easily AND can be deployed on edge/cpu devices locally without breaking the bank.
A lot of models can claim to be more accurate than yolo like maskrcnn etc but you cannot deploy them on cpu/edge in real time which is what most companies need to avoid cloud bills. Transformer models at this point are neither more accurate nor can be deployed sustainably for CV tasks. It's mostly for big companies to play around.
I think it is a similar case with GPT/GPT4. You keep paying recurring fees to for getting the API which is not the case with yolo models. And you cannot train it on a custom dataset when needed.
Transformers are great but they are not ready for prime time yet.

**Comment by akashAD98** [comment]
@AyushExel got it your point. thanks amazing work by yolo team
