### ISSUE TITLE
Why is the inference on the initial frame significantly slower compared to subsequent frames?

### ISSUE THREAD

**Issue by hdnh2006** [ultralytics/ultralytics#14332]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am working on an application where, due to infrastructure constraints, I need to pass each frame from an RTSP camera to an API where YOLO is deployed.

When streaming the camera feed as shown below:
```
from ultralytics import YOLO
from ultralytics.data import load_inference_source

model = YOLO('yolov8n.pt')
dataset = load_inference_source(2) # some webcam
results = model(dataset, stream=True)

for result in results:
    pass
``` 

I observe the following output:
``` 
1/1: 2... Success ✅ (inf frames of shape 640x480 at 30.00 FPS)

0: 480x640 1 person, 1 keyboard, 268.2ms
0: 480x640 1 person, 1 keyboard, 4.6ms
0: 480x640 1 person, 1 keyboard, 3.7ms
0: 480x640 1 person, 1 keyboard, 4.2ms
...
``` 

Notice that the first frame takes 268.2ms! Since I am evaluating frame-by-frame, each frame is treated as the first, resulting in poor inference performance.

For example:
```
import cv2
from ultralytics import YOLO
from ultralytics.data import load_inference_source


model = YOLO('yolov8n.pt')

img = cv2.imread('frame0.jpg') # or zidane.jpg, whatever

dataset = load_inference_source(img)

results = model(dataset, stream=True)

for result in results:
    pass
``` 

This gives:
```
0: 480x640 1 person, 88.3ms
Speed: 2.0ms preprocess, 88.3ms inference, 76.0ms postprocess per image at shape (1, 3, 480, 640)
``` 

Notice that the inference process takes 88.3ms, which is significantly high for the yolov8n.pt model. My question is:
Is there a way to improve the inference performance for the first frame?

Thanks in advance.

**Comment by Y-T-G** [comment]
> Since I am evaluating frame-by-frame, each frame is treated as the first, resulting in poor inference performance.

What does this mean? You can just initialize the model once and pass a dummy frame for the first inference. Are you recreating the model every time?

**Comment by glenn-jocher** [comment]
@Y-T-G hello,

Thank you for your detailed question and for providing the example code. The initial frame taking significantly longer for inference is a common observation due to the model's initial setup and optimization processes. Here are a few strategies to mitigate this issue:

1. **Model Initialization**: Ensure that the model is initialized only once and reused for subsequent frames. This avoids the overhead of reinitializing the model for each frame.

2. **Warm-Up Frame**: You can pass a dummy frame through the model once at the start to handle any initial setup. This way, the subsequent frames will benefit from the optimized state of the model.

Here's an example of how you can implement these strategies:

```python
import cv2
from ultralytics import YOLO

# Initialize the model once
model = YOLO('yolov8n.pt')

# Pass a dummy frame to warm up the model
dummy_frame = cv2.imread('dummy.jpg')
model(dummy_frame)

# Now process the actual frames
cap = cv2.VideoCapture('rtsp://your_camera_stream')
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    
    # Perform inference
    results = model(frame)
    
    # Process results
    for result in results:
        pass
    
    # Display or further process the frame if needed
    # cv2.imshow('Frame', frame)
    # if cv2.waitKey(1) & 0xFF == ord('q'):
    #     break

cap.release()
cv2.destroyAllWindows()
```

3. **OpenVINO Optimization**: If you are using OpenVINO for inference, consider enabling model caching and using the `AUTO` device selection mode to reduce the first-inference latency. You can find more details on optimizing OpenVINO inference in our [guide](https://docs.ultralytics.com/guides/optimizing-openvino-latency-vs-throughput-modes/).

By implementing these strategies, you should see a significant reduction in the inference time for the initial frame and improved performance for subsequent frames.

Feel free to reach out if you have any further questions or need additional assistance. Happy coding! 😊

**Comment by hdnh2006** [comment]
Thanks @glenn-jocher for your detailed explanation.

I already tried the dummy frame to do the warmpup. And as I commented when I opened the "issue", I am calling an API where YOLO is deployed.

I am sending as much frames as I can to that API, which is similar to this one: https://github.com/hdnh2006/YOLOv8API. So basically the frame I send i always the first one, so I don't know why if I send for example, 5 frames per second, why the model takes each frame as the first one. 

Of course if I pass to the model the rtsp url instead of each image, I get a similar output like this:
```
1/1: 2... Success ✅ (inf frames of shape 640x480 at 30.00 FPS)

0: 480x640 1 person, 1 keyboard, 268.2ms
0: 480x640 1 person, 1 keyboard, 4.6ms
0: 480x640 1 person, 1 keyboard, 3.7ms
0: 480x640 1 person, 1 keyboard, 4.2ms
...
```

So I would like to know if there's something behind ultralytics that makes some extra calculations while inferencing, because it is the inference process that is taking a lot of time:
```
0: 480x640 1 person, 88.3ms
Speed: 2.0ms preprocess, 88.3ms inference, 76.0ms postprocess per image at shape (1, 3, 480, 640)
``` 

Thanks in advance

**Comment by Y-T-G** [comment]
You should be using Triton Inference Server instead.

**Comment by glenn-jocher** [comment]
Hello @Y-T-G-G,

Thank you for the additional context. Given that you're sending frames to an API where YOLO is deployed, it's likely that each frame is being treated as a new request, causing the model to reinitialize certain processes for each frame. This can lead to the observed latency for each "first" frame.

To address this, you might consider using a more efficient inference server setup, such as NVIDIA's Triton Inference Server. Triton is designed to handle high-throughput inference workloads and can maintain model states across multiple requests, which might help mitigate the latency issue you're experiencing.

Here's a brief overview of how you can set up Triton Inference Server for your YOLO models:

1. **Model Conversion**: Ensure your YOLO model is in a format supported by Triton, such as ONNX or TensorRT.
2. **Model Repository**: Organize your models in a directory structure that Triton can read.
3. **Server Configuration**: Configure Triton to optimize for your specific use case, whether it's latency or throughput.

For more details on setting up Triton, you can refer to the [Triton Inference Server documentation](https://github.com/triton-inference-server/server).

Additionally, if you haven't already, please ensure that you are using the latest versions of the Ultralytics YOLO and related packages to benefit from the latest performance improvements and bug fixes.

If you have any further questions or need additional assistance, feel free to ask. We're here to help! 😊

**Comment by hdnh2006** [comment]
> You should be using Triton Inference Server instead.

Thanks @Y-T-G for your suggestion.

Just to other people that face with the same issue, there's a Ultralytics documentation that allow you to set YOLO on Triton server: https://docs.ultralytics.com/guides/triton-inference-server/. I'll check it out.

I'm gonna close this "issue" because I think it is out of the Ultralytics support due to my case is so particular.

Thanks Ultralytics team!

**Comment by hdnh2006** [comment]
> You should be using Triton Inference Server instead.

Sorry for opening again this issue.

I have tried Triton Inference Server following the documentation provided by Ultralytics: https://docs.ultralytics.com/guides/triton-inference-server/ 

It is a wonderful solution, but I am experiencing some issues with time inference also. While running with the classic CLI command, I see:
```
yolo predict detect source=video_streams/ model=yolov8n.pt
Ultralytics YOLOv8.2.70 🚀 Python-3.11.0rc1 torch-2.4.0+cu121 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 7940MiB)
YOLOv8n summary (fused): 168 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs

video 1/4 (frame 1/71997) /home/henry/Projects/CV_solutions/os-vision-architecture/deployer/src/predict/video_streams/20221007T090502_cam15.mp4: 384x640 4 persons, 31.1ms
video 1/4 (frame 2/71997) /home/henry/Projects/CV_solutions/os-vision-architecture/deployer/src/predict/video_streams/20221007T090502_cam15.mp4: 384x640 4 persons, 4.2ms
video 1/4 (frame 3/71997) /home/henry/Projects/CV_solutions/os-vision-architecture/deployer/src/predict/video_streams/20221007T090502_cam15.mp4: 384x640 4 persons, 4.2ms
video 1/4 (frame 4/71997) /home/henry/Projects/CV_solutions/os-vision-architecture/deployer/src/predict/video_streams/20221007T090502_cam15.mp4: 384x640 4 persons, 4.1ms
video 1/4 (frame 5/71997) /home/henry/Projects/CV_solutions/os-vision-architecture/deployer/src/predict/video_streams/20221007T090502_cam15.mp4: 384x640 4 persons, 4.9ms
video 1/4 (frame 6/71997) /home/henry/Projects/CV_solutions/os-vision-architecture/deployer/src/predict/video_streams/20221007T090502_cam15.mp4: 384x640 4 persons, 4.2ms
video 1/4 (frame 7/71997) /home/henry/Projects/CV_solutions/os-vision-architecture/deployer/src/predict/video_streams/20221007T090502_cam15.mp4: 384x640 4 persons, 4.1ms
video 1/4 (frame 8/71997) /home/henry/Projects/CV_solutions/os-vision-architecture/deployer/src/predict/video_streams/20221007T090502_cam15.mp4: 384x640 4 persons, 4.5ms
```

Now, I server the model in a remote server following the instructions from [docs](https://docs.ultralytics.com/guides/triton-inference-server/):
```
from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.pt")  # load an official model

# Export the model
onnx_file = model.export(format="onnx", dynamic=True)


from pathlib import Path

# Define paths
model_name = "yolo"
triton_repo_path = Path("tmp") / "triton_repo"
triton_model_path = triton_repo_path / model_name

# Create directories
(triton_model_path / "1").mkdir(parents=True, exist_ok=True)



from pathlib import Path

# Move ONNX model to Triton Model path
Path(onnx_file).rename(triton_model_path / "1" / "model.onnx")

# Create config file
(triton_model_path / "config.pbtxt").touch()



import contextlib
import subprocess
import time

from tritonclient.http import InferenceServerClient

# Define image https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tritonserver
tag = "nvcr.io/nvidia/tritonserver:23.09-py3"  # 6.4 GB

# Pull the image
subprocess.call(f"docker pull {tag}", shell=True)

# Run the Triton server and capture the container ID
container_id = (
    subprocess.check_output(
        f"docker run -d --gpus all --name triton --rm -v $PWD/{triton_repo_path}:/models -p 8000:8000 {tag} tritonserver --model-repository=/models",
        shell=True,
    )
    .decode("utf-8")
    .strip()
)

# Wait for the Triton server to start
triton_client = InferenceServerClient(url="0.0.0.0:8000", verbose=False, ssl=False)

# Wait until model is ready
for _ in range(10):
    with contextlib.suppress(Exception):
        assert triton_client.is_model_ready(model_name)
        break
    time.sleep(1)
 ```
 
Then I run inference in my local:
``` 
from ultralytics import YOLO

# Load the Triton Server model
model = YOLO("http://remote.ip:8000/yolo", task="detect")

# print(model.info()docker t

# Run inference on the server
results = model("video_streams", stream = True)

for det in results:
    print(det.speed)
```

And I get this slow inference time:
```
python inference.py 

video 1/4 (frame 1/71997) local_path/video_streams/20221007T090502_cam15.mp4: 640x640 4 class0s, 191.4ms
{'preprocess': 4.03141975402832, 'inference': 191.39742851257324, 'postprocess': 1.1897087097167969}
video 1/4 (frame 2/71997) local_path/video_streams/20221007T090502_cam15.mp4: 640x640 4 class0s, 148.8ms
{'preprocess': 3.919363021850586, 'inference': 148.7598419189453, 'postprocess': 1.1067390441894531}
video 1/4 (frame 3/71997) local_path/video_streams/20221007T090502_cam15.mp4: 640x640 4 class0s, 151.5ms
{'preprocess': 2.960205078125, 'inference': 151.5219211578369, 'postprocess': 0.6220340728759766}
video 1/4 (frame 4/71997) local_path/video_streams/20221007T090502_cam15.mp4: 640x640 4 class0s, 148.8ms
``` 

is there a way to make this time inference faster? @Y-T-G

**Comment by Y-T-G** [comment]
In Triton, you're using ONNX CPU inference. 

Add this to your config.pbtxt to make it use TensorRT and GPU.

```
optimization { execution_accelerators {
  gpu_execution_accelerator : [{
    name : "tensorrt"
    parameters { key: "precision_mode" value: "FP16" }
    parameters { key: "max_workspace_size_bytes" value: "1073741824" }
    parameters { key: "trt_engine_cache_enable" value: "1" }
  }]
}}
```

**Comment by hdnh2006** [comment]
Thanks @Y-T-G for your reply.
Effectively there's something wrong with the GPU usage. If I send a video from local to remote server I can see this:
![image](https://github.com/user-attachments/assets/53918061-8321-4157-94a2-b1845ad2f928)
So, it seems the model is being loaded into the GPU but then the inference is poor and just 1% of the GPU is used (previous image):
![image](https://github.com/user-attachments/assets/9f5338d6-dca1-4cfe-a121-e6e0daef1161)

However, if I run the same `inference.py` code but this time on remote server where the model is deployed, I can see the inference is absolutely fast:
![image](https://github.com/user-attachments/assets/4cb10963-abd3-4bc9-a85c-f5bc7c4d7f15)
And at least 11% of the GPU is used:
![image](https://github.com/user-attachments/assets/7fd7bb1d-e71b-4f65-a802-40b0b1743043)

So, it is definitely a problem when I send images from my local to the remote server. I definitely have a good connection on local (1Gbps) and a wonderful connection on remote (Cloud provider).

Any idea what could be happening in this situation? 

I really appreciate your help

**Comment by Y-T-G** [comment]
What's the ping latency to your remote server from local?

It's not just about speed.

**Comment by hdnh2006** [comment]
Thank your @Y-T-G

I have this ping:
![image](https://github.com/user-attachments/assets/971927b2-32ba-4ea2-be3c-e4ce63d228c2)

It doens't look like to be excesive, have you ever experienced something similar? I mean, slow inference on remote servers?

**Comment by Y-T-G** [comment]
Can you try checking latency using this?

https://pypi.org/project/tcp-latency/

Have you tried using flask with that server before? How is the latency like?

**Comment by Y-T-G** [comment]
You can use this method for Flask server:

https://github.com/ultralytics/ultralytics/issues/14855#issuecomment-2262134660

**Comment by hdnh2006** [comment]
Thanks again @Y-T-G for your invaluable help, I have decided to use my own Flask server. 

Your help and dedication to provide a solution to my problem have been wonderful.

I'm speechless, thank you.
