### ISSUE TITLE
While generating detection results using Yolo8 for segmentation, wanted to hide everything except masks.

### ISSUE THREAD

**Issue by nebuchadnezzar26** [ultralytics/ultralytics#1433]

**Comment by pderrenger** [comment]
@nebuchadnezzar26 hi there! It sounds like you want to generate segmentation results using YOLOv8 and only display the masks without anything else. YOLOv8 support both detection and segmentation tasks, and it's possible to extract the segmented regions from the detection results to display only the masks. You can achieve this by post-processing the detection output to isolate the masks and visualize them separately. If you need further assistance with this, feel free to ask! Keep up the great work! 😊
