### ISSUE TITLE
While generating detection results using Yolo8 for segmentation, wanted to hide everything except masks. please help?

### ISSUE THREAD

**Issue by nebuchadnezzar26** [ultralytics/ultralytics#1434]
I have used arguments as below

save=True, hide_labels=True,hide_conf=True,max_det=1000,box=False

but still getting bbox in output. 

if i try line_thikness = 0, boxes are still there, but passing 1 the thickness get reduced

**Comment by glenn-jocher** [comment]
@nebuchadnezzar26 thanks for the bug report! Should be fixed in https://github.com/ultralytics/ultralytics/pull/1473

**Comment by nebuchadnezzar26** [comment]
Thanks for the update @glenn-jocher , 

shall I re-install/update ultralytics "pip install --upgrade ultralytics" or I have to clone the implementation from git to get updated code?

**Comment by Laughing-q** [comment]
@glenn-jocher @nebuchadnezzar26 guys, the arg should be `boxes` instead of `box`. And it works fine.
```bash
yolo segment predict boxes=False save
```
![bus](https://user-images.githubusercontent.com/61612323/226265658-a8559c81-e042-4fa9-b5df-2501f8219793.jpg)

**Comment by nebuchadnezzar26** [comment]
Thanks @Laughing-q , It is working . This issue can be closed.
