### ISSUE TITLE
Convert to onnx

### ISSUE THREAD

**Issue by ianc1964** [ultralytics/ultralytics#14343]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am finding that when I use a standard export to onnx function on a custom model (best.pt to best.onnx I am losing one class. My custom model has 19 classes and the onnx model shows 18. Is there an obvious reason for this?

**Comment by glenn-jocher** [comment]
@ianc1964 hello,

Thank you for reaching out and for your detailed question! It sounds like you're encountering an issue where one of your classes is missing after exporting your custom model to ONNX format. Let's troubleshoot this together.

1. **Verify Class Count in Original Model**: First, ensure that your original `best.pt` model indeed has 19 classes. You can do this by loading the model and checking the class names:
    ```python
    from ultralytics import YOLO

    # Load your custom model
    model = YOLO("path/to/best.pt")

    # Print the class names
    print(model.names)
    ```

2. **Check Export Command**: Make sure you are using the correct export command. Here’s a quick example:
    ```python
    from ultralytics import YOLO

    # Load your custom model
    model = YOLO("path/to/best.pt")

    # Export to ONNX
    model.export(format="onnx")
    ```

3. **Inspect ONNX Model**: After exporting, you can inspect the ONNX model to verify the class count. Tools like Netron can be very helpful for visualizing ONNX models.

4. **Reproducible Example**: If the issue persists, it would be very helpful if you could provide a minimum reproducible example. This will allow us to better understand the problem and provide a more accurate solution. You can find guidance on creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

5. **Update to Latest Version**: Ensure you are using the latest version of the Ultralytics package. Sometimes, issues are resolved in newer releases, so updating might fix the problem:
    ```bash
    pip install --upgrade ultralytics
    ```

If you follow these steps and still encounter issues, please share the reproducible example, and we’ll be happy to assist you further. Thank you for your cooperation and understanding!

**Comment by ZeroLelouch1205** [comment]
> @ianc1964 hello,
> 
> Thank you for reaching out and for your detailed question! It sounds like you're encountering an issue where one of your classes is missing after exporting your custom model to ONNX format. Let's troubleshoot this together.
> 
> 1. **Verify Class Count in Original Model**: First, ensure that your original `best.pt` model indeed has 19 classes. You can do this by loading the model and checking the class names:
>    ```python
>    from ultralytics import YOLO
>    
>    # Load your custom model
>    model = YOLO("path/to/best.pt")
>    
>    # Print the class names
>    print(model.names)
>    ```
> 2. **Check Export Command**: Make sure you are using the correct export command. Here’s a quick example:
>    ```python
>    from ultralytics import YOLO
>    
>    # Load your custom model
>    model = YOLO("path/to/best.pt")
>    
>    # Export to ONNX
>    model.export(format="onnx")
>    ```
> 3. **Inspect ONNX Model**: After exporting, you can inspect the ONNX model to verify the class count. Tools like Netron can be very helpful for visualizing ONNX models.
> 4. **Reproducible Example**: If the issue persists, it would be very helpful if you could provide a minimum reproducible example. This will allow us to better understand the problem and provide a more accurate solution. You can find guidance on creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 5. **Update to Latest Version**: Ensure you are using the latest version of the Ultralytics package. Sometimes, issues are resolved in newer releases, so updating might fix the problem:
>    ```shell
>    pip install --upgrade ultralytics
>    ```
> 
> If you follow these steps and still encounter issues, please share the reproducible example, and we’ll be happy to assist you further. Thank you for your cooperation and understanding!

does nms=true work for yolo-obb when I'm exporting the model？When the parameter takes effect，should I need code NMS in C++ when I post-process onnx output?

**Comment by ZeroLelouch1205** [comment]
> @ianc1964 hello,
> 
> Thank you for reaching out and for your detailed question! It sounds like you're encountering an issue where one of your classes is missing after exporting your custom model to ONNX format. Let's troubleshoot this together.
> 
> 1. **Verify Class Count in Original Model**: First, ensure that your original `best.pt` model indeed has 19 classes. You can do this by loading the model and checking the class names:
>    ```python
>    from ultralytics import YOLO
>    
>    # Load your custom model
>    model = YOLO("path/to/best.pt")
>    
>    # Print the class names
>    print(model.names)
>    ```
> 2. **Check Export Command**: Make sure you are using the correct export command. Here’s a quick example:
>    ```python
>    from ultralytics import YOLO
>    
>    # Load your custom model
>    model = YOLO("path/to/best.pt")
>    
>    # Export to ONNX
>    model.export(format="onnx")
>    ```
> 3. **Inspect ONNX Model**: After exporting, you can inspect the ONNX model to verify the class count. Tools like Netron can be very helpful for visualizing ONNX models.
> 4. **Reproducible Example**: If the issue persists, it would be very helpful if you could provide a minimum reproducible example. This will allow us to better understand the problem and provide a more accurate solution. You can find guidance on creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 5. **Update to Latest Version**: Ensure you are using the latest version of the Ultralytics package. Sometimes, issues are resolved in newer releases, so updating might fix the problem:
>    ```shell
>    pip install --upgrade ultralytics
>    ```
> 
> If you follow these steps and still encounter issues, please share the reproducible example, and we’ll be happy to assist you further. Thank you for your cooperation and understanding!

when I'm training model, it always print log:
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n
How to switch YOLOv8n to YOLOv8x, my pretrain model is YOLOv8x-obb.pt

**Comment by ianc1964** [comment]
Thanks. I've tried that and a few other things. There are definitely 19 classes in the yolo model, so 0 to 18 classes (yolo starts at 0 and I wondered if this could be part of the issue). One of the classes is a two word class as in 'black cat' with no underscore or hyphen between the two words. Does that make a difference?

I used two scripts to get the following responses:
(env) E:\env>python check_onnx_model.py
Number of classes in ONNX model: 18

Model Inputs:
Name: images, Shape: [1, 3, 640, 640]

Model Outputs:
Name: output0, Shape: [1, 23, 8400]

(env) E:\env>python check_pt_model.py
Task: detect
Number of classes: 19

**Comment by glenn-jocher** [comment]
Hello @ianc1964,

Thank you for providing additional details. It sounds like you've done a thorough job troubleshooting the issue. The fact that one of your classes has a two-word name without an underscore or hyphen should not inherently cause a problem, but let's explore a few more steps to pinpoint the issue.

### Steps to Troubleshoot

1. **Class Names with Spaces**: While class names with spaces should generally be fine, it's worth testing if replacing the space with an underscore or hyphen affects the export. This can help rule out any unexpected behavior related to class name formatting.

2. **Check for Warnings or Errors**: Ensure there are no warnings or errors during the export process that might hint at why a class is missing.

3. **Inspect ONNX Model Metadata**: Use a tool like Netron to inspect the ONNX model and verify the class names and structure. This can help confirm if the issue lies within the model export or the ONNX model itself.

4. **Re-export with Simplified Names**: Try re-exporting the model after simplifying the class names to see if the issue persists:
    ```python
    from ultralytics import YOLO

    # Load your custom model
    model = YOLO("path/to/best.pt")

    # Simplify class names
    model.names = {i: name.replace(" ", "_") for i, name in model.names.items()}

    # Export to ONNX
    model.export(format="onnx")
    ```

5. **Verify with Latest Version**: Ensure you are using the latest version of the Ultralytics package. Sometimes, issues are resolved in newer releases:
    ```bash
    pip install --upgrade ultralytics
    ```

### Example Code to Check ONNX Model
Here’s a script to help you inspect the ONNX model:
```python
import onnx

# Load the ONNX model
onnx_model = onnx.load("path/to/best.onnx")

# Check the model's inputs and outputs
print("Model Inputs:")
for input in onnx_model.graph.input:
    print(f"Name: {input.name}, Shape: {input.type.tensor_type.shape.dim}")

print("\nModel Outputs:")
for output in onnx_model.graph.output:
    print(f"Name: {output.name}, Shape: {output.type.tensor_type.shape.dim}")

# Check the number of classes
num_classes = onnx_model.graph.output[0].type.tensor_type.shape.dim[1].dim_value
print(f"\nNumber of classes in ONNX model: {num_classes}")
```

### Addressing AMP and Model Switching
Regarding your question about switching models and AMP:
- **Switching Models**: To switch to a different pretrained model like `YOLOv8x-obb.pt`, simply load it as follows:
    ```python
    from ultralytics import YOLO

    # Load the YOLOv8x-obb model
    model = YOLO("yolov8x-obb.pt")
    ```

- **AMP Checks**: The message about AMP checks is informational. If you want to disable AMP, you can set `amp=False` during training:
    ```python
    results = model.train(data="your_dataset.yaml", epochs=100, imgsz=640, amp=False)
    ```

If the issue persists, please provide a minimum reproducible example as it will greatly help in diagnosing the problem. You can find guidance on creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Thank you for your patience and cooperation! 😊
