### ISSUE TITLE
 How to get higher recall ？

### ISSUE THREAD

**Issue by xuanandsix** [ultralytics/ultralytics#1435]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I compare v5 and v8 on multiple own datasets， v8 always has higher mAP50 value and mAP50-95  value, but the Recall value and Precision will be lower than v5。 How to adjust parameters to get a higher Recall value without considering other values？

**Comment by glenn-jocher** [comment]
@xuanandsix mAP is an absolute metric measured across all confidences, all precisions and all recalls, so you want to measure your results by mAP and not by P and R, which are easily manipulated simply by varying the confidence threshold used to evaluate them.
