### ISSUE TITLE
Docker image for NVIDIA Jetson Orin Nano

### ISSUE THREAD

**Issue by pornpra** [ultralytics/ultralytics#14350]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I have already deployed YOLOv8 (FP16 in .engine format) on an NVIDIA Jetson Orin Nano (JetPack: 5.1.2 and Python: 3.8.10). Currently, I use l4t-tensorrt:r8.5.2.2-devel, which includes TensorRT 8.5.2.2, CUDA 11.4.315, and PyCUDA 2022 from NVIDIA as the base image (9.56 GB), to build my custom Docker image (totaling around 12.8 GB). I am concerned about the large image size. My specific dependencies include:

1. ultralytics: 8.2.18
2. torch: 2.1.0a0+41361538.nv23.06
3. torchvision: 0.16.0+fbb4cc5

How can I use **ultralytics:8.2.53-jetson-jetpack5** instead of l4t-tensorrt:r8.5.2.2-devel to deploy YOLOv8 on NVIDIA Jetson Orin Nano?

**Comment by glenn-jocher** [comment]
@pornpra hello,

Thank you for reaching out with your question regarding deploying YOLOv8 on an NVIDIA Jetson Orin Nano. It's great to hear that you've already made significant progress with your deployment!

To address your concern about the large image size and to help you switch to the **ultralytics:8.2.53-jetson-jetpack5** Docker image, you can follow these steps:

1. **Pull the Ultralytics Jetson Docker Image**:
   First, pull the optimized Docker image for Jetson devices from Docker Hub:
   ```bash
   sudo docker pull ultralytics/ultralytics:8.2.53-jetson-jetpack5
   ```

2. **Run the Docker Container**:
   You can run the container with GPU support using the following command:
   ```bash
   sudo docker run -it --runtime nvidia --network host ultralytics/ultralytics:8.2.53-jetson-jetpack5
   ```

3. **Install Specific Dependencies**:
   If the image does not include all your specific dependencies, you can install them within the running container. For example:
   ```bash
   sudo docker run -it --runtime nvidia --network host ultralytics/ultralytics:8.2.53-jetson-jetpack5
   # Inside the container
   pip install torch==2.1.0a0+41361538.nv23.06 torchvision==0.16.0+fbb4cc5
   ```

4. **Build a Custom Dockerfile**:
   If you need to customize the image further, you can create a Dockerfile based on the Ultralytics image:
   ```Dockerfile
   FROM ultralytics/ultralytics:8.2.53-jetson-jetpack5

   RUN pip install torch==2.1.0a0+41361538.nv23.06 torchvision==0.16.0+fbb4cc5
   ```

   Then, build your custom image:
   ```bash
   sudo docker build -t my-custom-ultralytics-image .
   ```

5. **Run Your Custom Image**:
   Finally, run your custom Docker image:
   ```bash
   sudo docker run -it --runtime nvidia --network host my-custom-ultralytics-image
   ```

By using the **ultralytics:8.2.53-jetson-jetpack5** image, you should be able to reduce the overall size of your Docker image while still meeting your deployment requirements.

If you encounter any issues or need further assistance, please feel free to ask. Happy deploying! 🚀

**Comment by pornpra** [comment]
@glenn-jocher 

Does the ultralytics:8.2.53-jetson-jetpack5 image include TensorRT 8.5.2.2?

**Comment by glenn-jocher** [comment]
Hello @pornpra,

Thank you for your question! The **ultralytics:8.2.53-jetson-jetpack5** Docker image is designed to be optimized for Jetson devices and includes essential dependencies for running YOLOv8. However, it does not include TensorRT 8.5.2.2 by default.

If you require TensorRT 8.5.2.2, you can install it within the running container. Here’s how you can do it:

1. **Run the Docker Container**:
   ```bash
   sudo docker run -it --runtime nvidia --network host ultralytics/ultralytics:8.2.53-jetson-jetpack5
   ```

2. **Install TensorRT 8.5.2.2**:
   Inside the container, you can follow the installation steps for TensorRT. Typically, this involves downloading the TensorRT tar file from NVIDIA's website and following their installation instructions.

If you encounter any issues or need further assistance, please let us know. We're here to help! 😊
