### ISSUE TITLE
How can I get the information saved in the text file in json format?

### ISSUE THREAD

**Issue by sarpx** [ultralytics/ultralytics#1437]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

```
m = YOLO(f'/yolo/s/best.pt')
model = m.predict
results = model(source=IMAGE, device=0, retina_masks=True, save=True, save_txt=True)
```
labels text:
`0 0.364062 0.716667 0.3625 0.71875 0.3625 0.770833 0.364062 0.772917 0.376563 0.772917 0.378125 0.775 0.573438 0.775 0.578125 0.76875 0.576563 0.766667 0.576563 0.754167 0.575 0.752083 0.575 0.725 0.573438 0.722917 0.573438 0.71875 0.571875 0.716667 0.786607 57 0.239063 0.691667 0.2375 0.69375 0.2375 0.745833 0.239063 0.747917 0.239063 0.752083 0.240625 0.754167 0.240625 0.75625 0.242188 0.758333 0.242188 0.760417 0.24375 0.7625 0.24375 0.770833 0.248437 0.777083 0.248437 0.779167 0.25 0.78125 0.25 0.785417 0.259375 0.797917 0.260938 0.797917 0.265625 0.804167 0.267188 `

I tried to customize it in results.py, it didn't work.

I tried to save the file somewhere and read it from there and convert it to json format. Too many files created at this time. When I say delete the files after reading the created files, this time there is a lot of slowdown.

Wouldn't it be great if he could return these results to me directly as a method instead of printing them to a text file?

```
For example:
m = YOLO(f'/yolo/s/best.pt')
model = m.predict
results = model(source=IMAGE, device=0, retina_masks=True, **json=True**)
jsn = results[0].masks.json
return jsn
```

**Comment by sarpx** [comment]
Took a while as I don't master the code:

`m = YOLO(f'./yolov8/sn/best.pt')
model = m.predict
results = model(source=IMAGE, device=0, conf=0.10, retina_masks=True) 
a = []
det, mask = results[0].boxes.cpu(), results[0].masks.cpu()
for j, d in enumerate(reversed(det)):
    cls, conf = d.cls.squeeze(), d.conf.squeeze()
    seg = mask.segments[len(det) - j - 1].copy()  # reversed mask.segments
    seg = seg.reshape(-1)  # (n,2) to (n*2)
    line = (cls, *seg, conf)
    a.append(('%g ' * len(line)).rstrip() % line)`

**Comment by pderrenger** [comment]
@sarpx it seems like you're trying to obtain the segmentation results in JSON format directly from your YOLOv8 model's prediction. Currently, YOLOv8 doesn't support a direct method to return segmentation results in JSON format. However, you can achieve this by converting the `a` array into a JSON format using Python's `json` module. 

Here is an example of how you could achieve this:
```python
import json

# ... (your code)

# Convert the `a` array to JSON
json_data = json.dumps(a)

# Now `json_data` contains the JSON formatted segmentation results
```

You can then use the `json_data` variable within your application as needed. I hope this helps! Let me know if you need further assistance. 😊
