### ISSUE TITLE
Not all parameters in the hyperparamter evolution are changed

### ISSUE THREAD

**Issue by DP1701** [ultralytics/ultralytics#14378]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I am in the process of performing a hyperparamter evolution to test something. I have noticed that certain hyperparameters are not changed at all. For example copy and paste or mixup. Why is that?

In the[ tuner class](https://github.com/ultralytics/ultralytics/blob/40137785ec8b5bcd3836c8fed455a0a46c58f200/ultralytics/engine/tuner.py#L101), for example, the value range from 0 to 1 is enabled for copy and paste.

These are my settings:

```
   model = YOLO("yolov8s-seg.pt")  
 
    model.tune(data=dataset,
                batch=-1,
                epochs=100,
                iterations=300,
                optimizer='AdamW',
                plots=False,
                save=False,
                val=False,
                device=1,
                project=result_directory)
```

![tune_scatter_plots](https://github.com/user-attachments/assets/1930d39c-2456-465d-bfb0-37c565beabed)

**Comment by glenn-jocher** [comment]
@DP1701 hello,

Thank you for reaching out and for providing detailed information about your hyperparameter tuning process. It's great to see your proactive approach in exploring hyperparameter evolution with YOLOv8.

Regarding your observation, certain hyperparameters like `copy_paste` and `mixup` might not be changing during the evolution process. This could be due to their initial values being set to zero. In the context of YOLOv8's hyperparameter tuning, hyperparameters initialized to zero are not mutated. This is a design choice to avoid unnecessary computations for parameters that are not intended to be used.

To ensure these hyperparameters are included in the tuning process, you can initialize them with non-zero values. Here’s how you can modify your settings to include `copy_paste` and `mixup` in the evolution:

```python
from ultralytics import YOLO

# Initialize the YOLO model
model = YOLO("yolov8s-seg.pt")

# Set initial values for hyperparameters
initial_hyperparameters = {
    'copy_paste': 0.1,  # Set a non-zero initial value
    'mixup': 0.1,       # Set a non-zero initial value
    # Add other hyperparameters if needed
}

# Tune hyperparameters on your dataset
model.tune(
    data=dataset,
    batch=-1,
    epochs=100,
    iterations=300,
    optimizer='AdamW',
    plots=False,
    save=False,
    val=False,
    device=1,
    project=result_directory,
    hyperparameters=initial_hyperparameters  # Pass the initial hyperparameters
)
```

Additionally, please ensure you are using the latest version of the Ultralytics package to benefit from any recent updates or bug fixes.

For more detailed guidance on hyperparameter tuning, you can refer to our [Hyperparameter Tuning Guide](https://docs.ultralytics.com/guides/hyperparameter-tuning/).

If you have any further questions or need additional assistance, feel free to ask. Happy tuning! 🚀

**Comment by DP1701** [comment]
Thanks for the answer but unfortunately this does not work. I get the message that the parameter ```hyperparameters`` is not known.


``` python
    # Load a model
    model = YOLO(yolo_model) 

    # Set initial values for hyperparameters
    initial_hyperparameters = {
        'copy_paste': 0.1,  # Set a non-zero initial value
        'mixup': 0.1,       # Set a non-zero initial value
        'flipud' : 0.5,     # Set a non-zero initial value
        'shear' : 0.5,
        'degrees': 1,
        # Add other hyperparameters if needed
    } 
 
    model.tune(data=dataset,
                batch=-1,
                epochs=100,
                iterations=300,
                optimizer='AdamW',
                plots=False,
                save=False,
                val=False,
                device=0,
                hyperparameters = initial_hyperparameters,
                project=result_directory)
    
```


![Bildschirmfoto 2024-07-13 um 12 41 18](https://github.com/user-attachments/assets/da2e15fc-f210-4d86-978d-5edabd02bd3d)

**Comment by DP1701** [comment]
I use ultralytics 8.2.55

**Comment by glenn-jocher** [comment]
Hello @DP1701,

Thank you for the update. It appears that the `hyperparameters` argument is not recognized in the `model.tune()` method. My apologies for the confusion.

To address the issue of certain hyperparameters not being mutated, you can directly modify the `default.yaml` configuration file to set initial non-zero values for `copy_paste`, `mixup`, and other parameters. Here’s how you can do it:

1. **Copy the Default Configuration:**
   ```bash
   yolo copy-cfg
   ```

2. **Edit the `default_copy.yaml` File:**
   Open the `default_copy.yaml` file and set initial non-zero values for the hyperparameters you want to include in the tuning process:
   ```yaml
   copy_paste: 0.1
   mixup: 0.1
   flipud: 0.5
   shear: 0.5
   degrees: 1
   ```

3. **Run the Tuning with the Custom Configuration:**
   ```python
   from ultralytics import YOLO

   # Load the model
   model = YOLO("yolov8s-seg.pt")

   # Tune hyperparameters using the custom configuration file
   model.tune(
       data=dataset,
       batch=-1,
       epochs=100,
       iterations=300,
       optimizer='AdamW',
       plots=False,
       save=False,
       val=False,
       device=0,
       cfg='default_copy.yaml',  # Use the custom configuration file
       project=result_directory
   )
   ```

This approach ensures that the specified hyperparameters are included in the mutation process.

If the issue persists, please ensure you are using the latest version of the Ultralytics package. If you encounter any further issues, feel free to provide additional details.

Happy tuning! 🚀

**Comment by glenn-jocher** [comment]
@DP1701 just set these values to a non-zero starting point. Any values initialized to zero will stay that way.

**Comment by glenn-jocher** [comment]
For more details please see https://docs.ultralytics.com/guides/hyperparameter-tuning

**Comment by DP1701** [comment]
Thank you for your help. It works now. For anyone encountering the same question, this works for me:

``` python
    model = YOLO(yolo_model) 

    model.tune(data=dataset,
                batch=-1,
                epochs=100,
                iterations=300,
                optimizer='AdamW',
                plots=False,
                save=False,
                val=False,
                device=0,
                project=result_directory,
                copy_paste=0.1,
                mixup=0.1)
```


I have one more question. I want to combine the whole thing later with transfer learning in order to carry out several experiments. 

But now I'm wondering which strategy makes sense:

1. hyperparametric evolution and then training with transfer learning
2. perform hyperparamter evolution together with the freeze option. In other words, both at the same time during the hyperparamter evolution. Does that make sense?

**Comment by DP1701** [comment]
Does it make sense to freeze the entire backbone directly with freeze=10 for transfer learning, or is it better to start smaller (first 5 layers)? I haven't had much experience with transfer learning so far, so I'm looking for good starting values.

**Comment by pderrenger** [comment]
@DP1701 great to hear that the initial setup worked for you! For transfer learning, freezing the backbone can be a good strategy, but the extent to which you freeze it depends on your specific use case and dataset. Starting with `freeze=10` can be effective if your new dataset is similar to the original dataset the model was trained on. However, if your dataset is quite different, you might want to start smaller, like `freeze=5`, to allow more layers to adapt to the new data. Experimenting with different values will help you find the optimal balance. Happy experimenting!
