### ISSUE TITLE
TFLite export fails due to Out-Of-Memory

### ISSUE THREAD

**Issue by AndreaBrg** [ultralytics/ultralytics#1438]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

It appears that the TFLite export process is quite memory intensive. When trying to export my model, it fails during the `TensorFlow SavedModel: running 'onnx2tf -i /.../best.onnx -o /.../best_saved_model -nuo --non_verbose'` step.
I've checked using htop and it appears that the RAM (32GB) is completely saturated during this process.

This is the log of the export operations:
 
```
TensorFlow SavedModel: starting export with tensorflow 2.11.0...

ONNX: starting export with onnx 1.13.1...
ONNX: simplifying with onnxsim 0.4.17...
ONNX: export success ✅ 10.3s, saved as /data/checkpoints/yolov8/detect/products/weights/best.onnx (99.0 MB)

TensorFlow SavedModel: running 'onnx2tf -i /data/checkpoints/yolov8/detect/products/weights/best.onnx -o /data/checkpoints/yolov8/detect/products/weights/best_saved_model -nuo --non_verbose'
Killed
TensorFlow SavedModel: export failure ❌ 62.5s: SavedModel file does not exist at: /data/checkpoints/yolov8/detect/products/weights/best_saved_model/{saved_model.pbtxt|saved_model.pb}

TensorFlow Lite: starting export with tensorflow 2.11.0...
TensorFlow Lite: export success ✅ 0.0s, saved as /data/checkpoints/yolov8/detect/products/weights/best_saved_model/best_float16.tflite (0.0 MB)

Export complete (82.7s)
Results saved to /data/checkpoints/yolov8/detect/products/weights
Predict:         yolo predict task=detect model=/data/checkpoints/yolov8/detect/products/weights/best_saved_model/best_float16.tflite imgsz=800 
Validate:        yolo val task=detect model=/data/checkpoints/yolov8/detect/products/weights/best_saved_model/best_float16.tflite imgsz=800 data=/data/yolov8-cfg/Lotto2_v6.yaml 
Visualize:       https://netron.app
```

Am I doing something wrong? Thanks for the help.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AndreaBrg** [comment]
After further investigation, I found out that the problem **does not** appear using the following code:

```
# Load a model
model = YOLO(os.environ["MODEL"])  # load a custom trained
# Export the model
model.export(format="tflite", imgsz=os.environ["IMGSZ"])
```
while it happened with:

```
model = YOLO(os.environ["MODEL"])
model.fuse()

exporter = Exporter(cfg=os.environ["CFG"])
exporter(model=model.model)
```

**Comment by glenn-jocher** [comment]
@AndreaBrg that's odd, but I would use the default usage we have in the docs and what you're showing in your first example. See https://docs.ultralytics.com/modes/export
