### ISSUE TITLE
Mosaic Augmentation with Parameters such as `min_visibility` in Albumentations

### ISSUE THREAD

**Issue by Jacfger** [ultralytics/ultralytics#14384]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

A similar discussion with visual examples can be found here.
https://github.com/ultralytics/ultralytics/issues/3049 

In Albuemntations, there's a parameter called `min_visibility` which is what I'm looking for. In Perspective transform, I saw `area_th` was what I'm looking for, but for some reason it's applied on perspective trasnform only but not mosaic transform.

### Use case

Consider a large long rectangular object (a rod in extreme case) that's it's basically placed diagonally in the bounding box, which leads to large empty space. Consider a mosaic operations which moved to one corner of the object, which left only background to show to the model. To filter this case with the absolute threshold `wh_thr`, it necessitate a large `wh_thr`, but consider another same type of object that's placed far away from the scene. Due to perspective projection it'd look extremely small, and there could be no cropping but still get rejected due to the object being too small. 

There's no perfect solution but a better one would be to filter it base on the iou before and after filtering. (Which again, perspective did consider with `area_thr` parameter but just not mosaic.

Example: filtering new_bbox using `wh_thr` would also definitly remove the small object without `area_thr` in Mosaic itself.
![image](https://github.com/user-attachments/assets/978ccb73-6b58-44f8-87ae-0c940b0fae68)

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by Jacfger** [comment]
So after some more digging into the library, I realize in RandomPerspective, there were some code for clipping, and it also responsible for some filtering. But because mosaic itself also did clipping, woudln't it lead to a wrong size calculation? Can it just defer the calculation to randomperspective so that the `area_thr` is more intuitive?

**Comment by glenn-jocher** [comment]
@Jacfger thank you for your detailed observation! You are correct that the `RandomPerspective` transformation in Albumentations includes clipping and filtering mechanisms, which might lead to unintended size calculations when combined with Mosaic augmentation.

To address this, one approach could be to defer the size calculation to `RandomPerspective` after the Mosaic transformation. This would ensure that the `area_thr` parameter is applied more intuitively, considering the cumulative effect of both transformations.

Here's a conceptual example of how you might adjust the pipeline to achieve this:

```python
import albumentations as A

# Define the augmentations
transform = A.Compose([
    A.Mosaic(p=1.0),
    A.RandomPerspective(p=1.0, area_thr=0.1)
])

# Apply the transformations
augmented = transform(image=image, bboxes=bboxes)
```

In this setup, the `Mosaic` transformation is applied first, followed by `RandomPerspective`, which handles the final clipping and filtering based on the `area_thr` parameter.

If you believe this enhancement would be beneficial for the broader community, we encourage you to submit a Pull Request (PR) with your proposed changes. Your contribution could help improve the robustness of the augmentation pipeline for everyone.

For further guidance on submitting a PR, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing).

Thank you for your valuable input! 😊
