### ISSUE TITLE
export error

### ISSUE THREAD

**Issue by wuhuaqing** [ultralytics/ultralytics#14403]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

When I use the CLI to export `yolov8n.pt` to ONNX, the Python environment crashes, showing the following message: 

"PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)
[1]    36482 segmentation fault  yolo export model=yolov8n.pt format=onnx"

### Environment

Ultralytics YOLOv8.2.51 🚀 Python-3.11.9 torch-2.2.2 CPU (Intel Core(TM) i5-1038NG7 2.00GHz)
![image](https://github.com/user-attachments/assets/fd3ccbbe-58d7-4dfe-bd34-c436ac582191)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by wuhuaqing** [comment]
only one CLI to export:yolo export model=yolov8n.pt format=onnx

**Comment by wuhuaqing** [comment]
is my onnx version not match: use 1.15.0 success!

**Comment by glenn-jocher** [comment]
@wuhuaqing thank you for the update! It's great to hear that using ONNX version 1.15.0 resolved the issue. Compatibility between different versions of libraries can sometimes cause unexpected errors, so it's always a good idea to ensure that you're using compatible versions.

For future reference, if you encounter similar issues, providing a minimal reproducible example can be very helpful. You can find more information on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

If you have any more questions or run into further issues, feel free to ask. Happy exporting! 🚀
