### ISSUE TITLE
How to instantiate model and do prediction with certain device(gpu0, gpu1, cpu)

### ISSUE THREAD

**Issue by shunmian** [ultralytics/ultralytics#1440]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, Is there a way to instantiate and do prediction with device (gpu0, gpu1, cpu, similar to [pytorch device](https://pytorch.org/docs/stable/generated/torch.cuda.device.html) or [yolov7 device](https://github.com/WongKinYiu/yolov7/blob/3b41c2cc709628a8c1966931e696b14c11d6db0c/detect.py#L30)) arg?

I see in the [doc](https://docs.ultralytics.com/usage/python/)

- instantiate: `model = YOLO("model.pt")` has no device arg
- prediction: `results = model.predict(source="0")` also has no device arg

probably once instantiate specify the device, the prediction defaults to that device. So the question is how to instantiate with device arg?

**Comment by shunmian** [comment]
Hi, I don't see the device usage for model instantiate in the doc

**Comment by glenn-jocher** [comment]
Try `model.to(device)`
