### ISSUE TITLE
Documentation mismatch in val.py#L200-L214

### ISSUE THREAD

**Issue by HarinKhakhi** [ultralytics/ultralytics#14401]
I found documentation mismatch from code [here](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/models/yolo/detect/val.py#L200-L214): 
![Screenshot 2024-07-12 at 5 17 19 PM](https://github.com/user-attachments/assets/56eb8f15-0c48-4a52-8d7b-0bbc55c4ce7a)

The correct documentation should be as following,
```python
"""
Return correct prediction matrix.

Args:
    detections (torch.Tensor): Tensor of shape [N, 6] representing detections.
        Each detection is of the format: x1, y1, x2, y2, conf, class.
    gt_bboxes (torch.Tensor): Tensor of shape [M, 4] representing bounding box coordinates.
        Each label is of the format: x1, y1, x2, y2.
    gt_cls (torch.Tensor): Target class indices of shape(M,).

Returns:
    (torch.Tensor): Correct prediction matrix of shape [N, 10] for 10 IoU levels.
"""
```

Sorry, I haven't used a template because this is not a bug / question / security issue.

**Comment by glenn-jocher** [comment]
@HarinKhakhi thank you for pointing out the documentation mismatch in `val.py`. Your attention to detail is greatly appreciated! 🛠️

The suggested documentation update indeed provides clearer and more accurate descriptions for the arguments and return values. We'll review this internally and make the necessary adjustments to ensure the documentation aligns with the code.

If you encounter any other discrepancies or have further suggestions, please feel free to share. Your contributions help improve the project for everyone!

**Comment by glenn-jocher** [comment]
@HarinKhakhi

**Comment by glenn-jocher** [comment]
@HarinKhakhi PR opened in https://github.com/ultralytics/ultralytics/issues/14401 to resolve this, but please help in the future by submitting your own PR!
