### ISSUE TITLE
Trainning not improving: Decreasing mAP and Early Stopping at Epoch 100

### ISSUE THREAD

**Issue by davidbv01** [ultralytics/ultralytics#14419]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi there,

I write this question after trying over 10 different trainings. I want to make a model that detects different products in retail stores. The dataset that I've been using is the Retail Product Checkout Dataset ([source](https://www.kaggle.com/datasets/diyer22/retail-product-checkout-dataset)), and now I've tried to combine it with two more datasets: SKU110K and GroZi120 ([source](https://github.com/tobiagru/ObjectDetectionGroceryProducts)).

In total, the dataset contains 50,000 images. I have carefully reviewed the labels and confirmed their correctness, including those used for validation. I have experimented with both binary (one class) and multi-class models, testing with both the small and medium YOLOv8 models.

However, my issue is that during training, both the mAP50 and mAP50-95 metrics consistently decrease and stabilize around 0.3 and 0.2, respectively. I validate using images from the Kaggle dataset.

By epoch 100, the training halts due to the patience value set to 100.

I would greatly appreciate any advice or insights on how to improve performance or if this performance is typical given my setup.

Thank you!

**Comment by glenn-jocher** [comment]
@davidbv01 it's not possible to provide an expected performance since your dataset is unique, but for starters I would try to train on SKU-110K by itself and see how this fares. If your combined dataset is near that then I think you have your answer.

For better accuracy you can always scale to a larger model or a larger imgsz or both.
