### ISSUE TITLE
GPT comments are a problem and people who speak up about it get their issues deleted

### ISSUE THREAD

**Issue by Skillnoob** [ultralytics/ultralytics#14421]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

Since many people have found issues with @glenn-jocher using a LLM/GPT to answer Github issues, I have created a issue talking about the problems and have proposed very simple solutions that should take less than an hour to implement.
But after a few users agreed with me and a few of @glenn-jocher's AI responses, the issue was promptly deleted. Any other Github issue I referenced in that issue was also suddenly deleted.

This is not good behavior. Instead of choosing to talk about it with your community you choose to oppress the people who talk about it? Instead of implementing a simple fix that can significantly improve the user experience on the Ultralytics Github repositories you choose to ignore the issue?

I am trying to help improve Ultralytics, since i really like Ultralytics and what it provides.

Please have a normal discussion about it in this Github issue and don't delete issues, it doesn't help.

Here are archived versions of 2 of the Github issues that were deleted:

My issue:
https://web.archive.org/web/20240712151225/https://github.com/ultralytics/ultralytics/issues/14391

My issue through google's cache (has a few extra messages):
https://web.archive.org/web/20240714123343/https://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fgithub.com%2Fultralytics%2Fultralytics%2Fissues%2F14391%23issuecomment-2226576945

@egeakman's issue:
https://web.archive.org/web/20240712131629/https://github.com/ultralytics/ultralytics/issues/6470

Another issue that talked about the problem but I don't have an archived version of it:
https://github.com/ultralytics/ultralytics/issues/4654

You can read about the problems/possible solutions in these issues.

Again, please have a normal discussion in the comments with the community. Without the use of an AI chatbot. I do not expect you to reply immediately or constantly check for it.

On a side note, using a bot on a human's account to automate responses possibly breaks multiple Github rules or guidelines, listed below:

**Spam or inauthentic Activity:**
Inauthentic use of the service such as rank abuse, star abuse, the use of bots, fake accounts or other deceptive uses of the service.

**Impersonation:**
Misrepresenting your identity or association with another person or organization.

**Disruptive Content (Maybe since the bot often steers discussions away from another discussion going on):**
Off-topic comments, using platform features to cause disruption.

Including [this](https://docs.github.com/en/site-policy/github-terms/github-community-code-of-conduct#reasonable-use-of-ai-generated-content) GitHub Community Code of Conduct entry.

Moving the automated replies to a account like @UltralyticsAssistant with a Github (BOT) label would resolve pretty much all of these issues (more solutions listed in the archived github issue). You could change it to a similar system like https://github.com/apps/dosubot. I think they have a great system which allows the users to choose to engage with the bot and give feedback on the responses.

**Comment by glenn-jocher** [comment]
@Skillnoob removing as off-topic to YOLO, which is our primary purpose. We are aiming to address your concerns as we scale our small team to accommodate the surge in demand that we are experiencing. Thank you for your patience.
