### ISSUE TITLE
The effect of the random function

### ISSUE THREAD

**Issue by hefangnan** [ultralytics/ultralytics#14449]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to improve the Mosaic data enhancement algorithm by adding the following code to the Mosaic_4 function               
 if y1a > 480.
                    extra =True
                    index = random.choices(list(self.dataset.buffer), k=1)
                    extra_label = self.dataset.get_image_and_label(index[0])
                    h_1, w_1 = extra_label.pop("resized_shape")
                    x1c, y1c, x2c, y2c = max(xc - w_1, 0), max(y1a - h_1, 0), xc, y1a
                    x1d, y1d, x2d, y2d = w_1 - (x2c - x1c), h_1 - (y2c - y1c), w_1, h_1
The datasets are not loaded in the same order when the seeds are the same, what could be the reason for this?

Translated with DeepL.com (free version)
![Snipaste_2024-07-15_16-02-26](https://github.com/user-attachments/assets/b524031d-9cbd-4117-9a7e-28b8c7771cd7)
![Snipaste_2024-07-15_16-02-26](https://github.com/user-attachments/assets/8971bb7b-587a-47da-92a3-185a2a02eebb)
![Snipaste_2024-07-15_16-03-05](https://github.com/user-attachments/assets/82ee054f-7f1b-418a-b9de-73366cd73b6c)

**Comment by hefangnan** [comment]
![1](https://github.com/user-attachments/assets/fc05c575-6dc7-41bc-b413-a41aeacffd44)

**Comment by pderrenger** [comment]
@hefangnan it sounds like you're encountering an issue with dataset loading order despite setting the same seed. This can happen if there are other sources of randomness in your data pipeline or if the seed isn't being set consistently across all random functions (e.g., `random`, `numpy`, `torch`). Make sure to set the seed for all libraries involved. Additionally, check if the dataset shuffling or augmentation introduces any non-deterministic behavior. If the issue persists, try updating to the latest version of the Ultralytics package to see if it resolves the problem.
