### ISSUE TITLE
Found no valid file for the classes labels on a Roboflow dataset with YoloV8 classifier

### ISSUE THREAD

**Issue by GeorgeCoblisan** [ultralytics/ultralytics#1445]
Hello! I followed the tutorial from this link: https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/train-yolov8-classification-on-custom-dataset.ipynb and when I try to train the model I am getting this error: 

![image](https://user-images.githubusercontent.com/72258139/225397277-4b3a7291-a137-4823-aa3a-294af02f431f.png)

I definitely followed all the steps that are presented there to correctly export a dataset from roboflow. What I noticed is that the labels are in txt format, but then how could I train in this case? I thought that the example should be followed quite straight forward and work.

**Comment by GeorgeCoblisan** [comment]
> Could you link me to your project on Roboflow?

Thank you very much for your response. I'm not sure how it can be the correct way to share my project to you. Should I export it in "Yolo v5 Pytorch" format and share the download code?

**Comment by GeorgeCoblisan** [comment]
> Could you link me to your project on Roboflow?

I uploaded the archive of my project via wetransfer. Please check this link: https://we.tl/t-aj3c9AVpHp

**Comment by pderrenger** [comment]
@GeorgeCoblisan thank you for sharing the project archive. YOLOv8 requires the class labels to be in a specific format. You can create the class labels file in the YOLO format by listing your classes, with each class on a separate line. Once you have the class labels in a text file, you can use it for training with the YOLOv8 classifier. Let me know if you need further assistance with the class labels file or any other aspect of the training process!

**Comment by rafaelmozo1** [comment]
I just encountered the same problem, did you manage to solve it @GeorgeCoblisan ?
