### ISSUE TITLE
Erro when export yolo8n.pt to yolov8n.engine

### ISSUE THREAD

**Issue by jsbluekitty** [ultralytics/ultralytics#14455]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

When i use `yolo export model=./yolov8n.pt format=engine` in linux,
It raise an erro like
![image](https://github.com/user-attachments/assets/218729de-2871-4922-9d07-e1272d9b341a)

 `AttributeError: 'tensorrt_bindings.tensorrt.IBuilderConfig' object has no attribute 'max_workspace_size'`
So i edit the code like
![image](https://github.com/user-attachments/assets/3b38eace-e4df-4af5-aa32-8c51c232234d)

Then it raise another problem
![image](https://github.com/user-attachments/assets/02db05b6-9596-40ef-b5ba-416958304d83)

So i edit the code like
![image](https://github.com/user-attachments/assets/66b304ab-b383-477a-b7b9-4ab39ed5e9dc)
 
there is another problem show again
![image](https://github.com/user-attachments/assets/9230e64c-08fe-41fe-bb98-a23681ba6730)

### Environment

Ultralytics YOLOv8.0.170 🚀 Python-3.10.13 torch-2.3.1+cu121 CUDA:0 (NVIDIA A100 80GB PCIe, 81051MiB)
Setup complete ✅ (128 CPUs, 503.5 GB RAM, 1703.0/3519.2 GB disk)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
You need to downgrade your TensorRT Python package.

**Comment by Y-T-G** [comment]
Upgrade ultralytics first.

**Comment by Y-T-G** [comment]
> AttributeError: 'tensorrt_bindings.tensorrt.IBuilderConfig' object has no attribute 'max_workspace_size'

You get this when you use higher TensorRT python package but lower TensorRT version in your system.

**Comment by jsbluekitty** [comment]
Thanks a lot!
I upgrade ultralytics into Ultralytics YOLOv8.2.58
And it still raise a erro like
![image](https://github.com/user-attachments/assets/f347f9d1-d302-4dff-bfd4-31ba9e10a90f)
 
This is my yolo check info now
![image](https://github.com/user-attachments/assets/3152e7d9-5db7-49ca-b71c-cb73a7a5ffac)

**Comment by jsbluekitty** [comment]
And this is my `conda list` info 
![image](https://github.com/user-attachments/assets/6ae65bb1-009b-43ac-b433-fde526b7becc)

I checked my TensoRT verison is TensorRT-10.0.1.6
![image](https://github.com/user-attachments/assets/1fe2982c-4043-432b-be75-03ce01f7c461)

**Comment by pderrenger** [comment]
@jsbluekitty thanks for the update! It looks like there's a mismatch between your TensorRT Python package and the system version. Ensure both are aligned at version 10.0.1.6. If the issue persists, try reinstalling TensorRT or consult the TensorRT documentation for compatibility details. Let me know how it goes!

**Comment by Y-T-G** [comment]
Run `dpkg -l | grep TensorRT`

**Comment by Y-T-G** [comment]
Can show the output of `/home/wyf/.conda/envs/yolov8/bin/pip show tensorrt`?

**Comment by jsbluekitty** [comment]
> Can show the output of `/home/wyf/.conda/envs/yolov8/bin/pip show tensorrt`?

yes,it look like this
![image](https://github.com/user-attachments/assets/39405b62-1ba3-43f8-81ec-af4c731b187e)

**Comment by jsbluekitty** [comment]
> @jsbluekitty thanks for the update! It looks like there's a mismatch between your TensorRT Python package and the system version. Ensure both are aligned at version 10.0.1.6. If the issue persists, try reinstalling TensorRT or consult the TensorRT documentation for compatibility details. Let me know how it goes!

thanks,i will try it!!

**Comment by glenn-jocher** [comment]
Adding a non-reproducible tag as this appears to be isolated to the user environment and we are unable to reproduce locally.

**Comment by Y-T-G** [comment]
Maybe you have multiple TensorRT versions in your environment. You should probably remove all of the TensorRT packages first from the system, recreate the environment and only install using `pip install tensorrt`

What's your GPU? Does it support TensorRT 10?

**Comment by jsbluekitty** [comment]
Thanks, i solved the problem by keep tensorrt and TensorRT both in 10.1!

**Comment by pderrenger** [comment]
Great to hear that you resolved the issue by aligning both TensorRT versions to 10.1! If you encounter any more questions or need further assistance, feel free to reach out. Happy coding!
