### ISSUE TITLE
Custom Data Training for Action Recognition with YOLOv8

### ISSUE THREAD

**Issue by bhavyajoshi-mahindra** [ultralytics/ultralytics#14461]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I tried Action Recognition with YOLOv8 on my videos and it works like a charm to identify general activities like walking, standing, sitting etc. Right now I am working on Mechanic Activity Recognition in Vehicle Service Centers. In my case, I am trying to classify whether a person is working on a vehicle (servicing the vehicle) or not. So there are only two activities as of now, "Working", and "Ideal" which can be achieved. But down the line, I plan to have a similar looking yet different set of activities I need to recognize. For example, a person working on repairing a particular part of a vehicle (in a service station), which can be changing oil, changing tires, working on the engine inside the bonnet, or maybe repairing broken windshields ets (I know I have to prepare dataset accordingly which can be arranged). So, for such particular use cases, are you guys planning to add a custom dataset training for Action recognition?   

### Use case

It can be used to classify similar-looking activities as mentioned. Other use cases can be, Driver Monitoring, Gesture Recognition for infotainment Controls, Personalized In-Car Experience, etc. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@bhavyajoshi-mahindra it's great to hear that YOLOv8 is working well for your action recognition tasks! For your specific use case of recognizing mechanic activities in vehicle service centers, you can indeed train YOLOv8 on a custom dataset tailored to your needs. While we currently don't have a dedicated feature for action recognition, you can leverage the existing classification capabilities of YOLOv8.

To train YOLOv8 on your custom dataset, ensure your dataset is structured correctly with separate directories for each class (e.g., "Working" and "Idle"). You can then use the `train` function to train the model on your dataset. Here's a brief example to get you started:

```python
from ultralytics import YOLO

# Load a pretrained model
model = YOLO("yolov8n-cls.pt")

# Train the model on your custom dataset
results = model.train(data="path/to/your/dataset", epochs=100, imgsz=640)
```

This approach should allow you to classify various activities as you expand your dataset. If you encounter any issues or have further questions, feel free to reach out here. Happy training!

**Comment by glenn-jocher** [comment]
@fcakyon may also have some insights here.

**Comment by fcakyon** [comment]
Hello @bhavyajoshi-mahindra, ultralytics currently does not support action recognition finetuning.

You can follow the tutorial below to finetune a hugging face video classification model, then use that model in the ultralytics action recognition pipeline! 

https://colab.research.google.com/github/huggingface/notebooks/blob/main/examples/video_classification.ipynb

**Comment by pderrenger** [comment]
@bhavyajoshi-mahindra you're welcome! If you have any further questions or need additional assistance in the future, feel free to open a new issue. Good luck with your project!

**Comment by omi2809** [comment]
Hi @bhavyajoshi-mahindra , I am also willing to know how to train my data on activity recognition using yolov8, can you guide me on the same? also can you share me the scripts which you prepared to do inference on the videos, I want to detect human walking on videos. 

Thanks for your contribution :)
