### ISSUE TITLE
2-step detection validation

### ISSUE THREAD

**Issue by YOOHYOJEONG** [ultralytics/ultralytics#14469]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to use two yolov8 models to detect objects.
   
After detecting a person in the entire frame, the detected person's bbox is cropped to detect a person's face in the cropped person's bbox.
   
I used cropped images of people in the whole frame to train facial models.   
But validation can't use the model.val() provided by ultralytics because I want to evaluate the human face for the whole frame.
   
When I make an inference using 2 models, the face of the person detected by the face model is transformed into coordinates for the entire frame.

How should we evaluate the face model in this situation?

**Comment by pderrenger** [comment]
@YOOHYOJEONG it sounds like you're working on a multi-step detection pipeline, which is a fascinating approach! For evaluating your face model within the context of the whole frame, you can follow a custom validation process. First, run your person detection model to get bounding boxes for people. Then, crop these regions and pass them to your face detection model. Finally, map the detected face coordinates back to the original frame for evaluation. While `model.val()` is designed for single-step validation, you can script this custom validation loop to suit your needs. If you encounter any issues, ensure you're using the latest version of the package. Good luck with your project!
