### ISSUE TITLE
Got a wrong result in onnx C++ detect YoloV8

### ISSUE THREAD

**Issue by EkilGitHub** [ultralytics/ultralytics#14465]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

when i use python onnx can get a right result 
![46-2-2](https://github.com/user-attachments/assets/85275f6e-b3b3-49a8-99ca-7b5c78166a64)
but when i use c++ to do this, it give me that:
![test1](https://github.com/user-attachments/assets/34613ae9-7ac7-45f7-b79b-8366a35d3694)

**Comment by pderrenger** [comment]
@EkilGitHub thanks for reaching out! It looks like you're encountering discrepancies between Python and C++ ONNX results. First, ensure you're using the latest versions of the ONNX runtime and YOLOv8. Differences in preprocessing steps or model handling between the two environments could also cause this issue. Double-check that the input data is processed identically in both cases. If the problem persists, please provide more details about your C++ implementation for further assistance.
