### ISSUE TITLE
Invalid parameter settings during training？

### ISSUE THREAD

**Issue by angel-yi** [ultralytics/ultralytics#14463]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

train yolov8m
![image](https://github.com/user-attachments/assets/d9a7e6d6-9a88-4fab-9891-3f2ca546c71d)
![image](https://github.com/user-attachments/assets/660634bf-f531-42af-829e-32011dbd64d0)

**Comment by angel-yi** [comment]
![image](https://github.com/user-attachments/assets/dd7aaa39-b169-472d-9387-7b7b12be38d3)

**Comment by pderrenger** [comment]
@angel-yi it looks like you're encountering an issue with parameter settings during training. Please ensure you're using the latest version of the Ultralytics package, as updates often resolve such issues. If the problem persists, double-check your configuration file for any typos or incorrect values. Feel free to share more details if you need further assistance!
