### ISSUE TITLE
Pre & Post Processing (Yolov8 OBB, TFLite C++)

### ISSUE THREAD

**Issue by TalonBvV** [ultralytics/ultralytics#14478]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Good day, I hope you are all well.
I am rather confused by the output structure used in yolov8 obb model.
I have managed to figure out what info the output contains (position[4], confidence[1], rotation[1]) baring in mind I only have a single class.

But after postprocessing and rendering the bboxes/polygons, I get results that do not alien at all with the output given in predict model.

Please can someone give me some guidance on what I am doing wrong.

Please do not answer me with a ChatGPT response, I have read through a lot of questions on the yolo repo's and I see a lot of unreliable info.

[main-tflite.cpp.txt](https://github.com/user-attachments/files/16249270/main-tflite.cpp.txt)
[ObjectDetector.cpp.txt](https://github.com/user-attachments/files/16249271/ObjectDetector.cpp.txt)
[ObjectDetector.h.txt](https://github.com/user-attachments/files/16249272/ObjectDetector.h.txt)

**Comment by Y-T-G** [comment]
The output would be in (1, 6, num_anchors) format and you will have to reshape to (1, num_anchors, 6) before processing it.

**Comment by Logeshmuthu** [comment]
same thing i want oBB for post processing only coreml iOS swift 

i got tensor output like: `Float32 1 × 20 × 21504 array ` this format

**Comment by Rofeena-Taj** [comment]
how to reshape and interpret the tensor output format (Float32 1 × 20 × 21504) which I got when printed the result using VNCoreMLFeatureValueObservation.NOw how to post process it to extract the bounding boxes,confidence scores,class count and rotation angles of yolov8s-obb.mlmodel which got converted from yolov8s-obb.pt on iOS in Swift using XCode

**Comment by pderrenger** [comment]
To reshape and interpret the tensor output (Float32 1 × 20 × 21504) from your YOLOv8s-OBB model in Swift, you'll need to map the tensor dimensions to the bounding boxes, confidence scores, class counts, and rotation angles. Typically, the first dimension is the batch size, the second dimension represents the number of attributes (like position, confidence, rotation), and the third dimension is the number of anchors. Ensure you correctly parse these values to extract the necessary information. If you encounter specific issues, feel free to share more details!

**Comment by Rofeena-Taj** [comment]
How to parse these tensor value to extract those OBB annotations.Could you help me with the post processing script of iOS using Swift to convert the tensors into bbox attributes.
Please don't give any suggestions to interpret other than any Python/Swift post processing techniques.

**Comment by pderrenger** [comment]
To parse the tensor values and extract OBB annotations in iOS using Swift, you'll need to reshape the tensor and map the values to bounding box attributes, confidence scores, and rotation angles. The tensor format you mentioned (Float32 1 × 20 × 21504) typically includes these attributes. For a detailed post-processing script, I recommend referring to the YOLOv8 documentation and adapting the Python post-processing techniques to Swift. If you encounter specific issues, please share more details, and I'll be happy to assist further.

**Comment by Logeshmuthu** [comment]
please give me simple extraction script example for (Float32 1 × 20 × 21504) this shape for oBB

**Comment by TalonBvV** [comment]
@Y-T-G Thanks, your feedback was on point.
To anyone wondering how to pull off post processing, please read through what's going on within my source code attached (apologies for the mess), this will give you good idea on what the implementation looks like, and just remember that output must be reshaped before any post processing takes place.

Also, most people will see that the original output shape will be slightly different depending on the number of classes that are used, for a single class (Float32 1 × 6 × 21504), for 2 classes (Float32 1 × 7 × 21504).
