### ISSUE TITLE
Detection Validator not working for YOLOv10 models

### ISSUE THREAD

**Issue by SilverStarCoder** [ultralytics/ultralytics#14471]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When running the detection validator for YOLOv10 models, I get the following error:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
File <command-3717519490746351>:1
----> 1 stats = validator(model=model.model)
      2 metrics = validator.metrics

File /databricks/python/lib/python3.9/site-packages/torch/autograd/grad_mode.py:27, in _DecoratorContextManager.__call__.<locals>.decorate_context(*args, **kwargs)
     24 @functools.wraps(func)
     25 def decorate_context(*args, **kwargs):
     26     with self.clone():
---> 27         return func(*args, **kwargs)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/ultralytics/engine/validator.py:189, in BaseValidator.__call__(self, trainer, model)
    186 with dt[3]:
    187     preds = self.postprocess(preds)
--> 189 self.update_metrics(preds, batch)
    190 if self.args.plots and batch_i < 3:
    191     self.plot_val_samples(batch, batch_i)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/ultralytics/models/yolo/detect/val.py:160, in DetectionValidator.update_metrics(self, preds, batch)
    158 # Save
    159 if self.args.save_json:
--> 160     self.pred_to_json(predn, batch["im_file"][si])
    161 if self.args.save_txt:
    162     file = self.save_dir / "labels" / f'{Path(batch["im_file"][si]).stem}.txt'

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/ultralytics/models/yolo/detect/val.py:280, in DetectionValidator.pred_to_json(self, predn, filename)
    275 box[:, :2] -= box[:, 2:] / 2  # xy center to top-left corner
    276 for p, b in zip(predn.tolist(), box.tolist()):
    277     self.jdict.append(
    278         {
    279             "image_id": image_id,
--> 280             "category_id": self.class_map[int(p[5])]
    281             + (1 if self.is_lvis else 0),  # index starts from 1 if it's lvis
    282             "bbox": [round(x, 3) for x in b],
    283             "score": round(p[4], 5),
    284         }
    285     )

IndexError: list index out of range
```

I do not get this error for V8 or V9 models. 

### Environment

Latest version of ultralytics

### Additional

I am not sure if this is related to https://github.com/ultralytics/ultralytics/pull/13761

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@SilverStarCoder without an actual MRE there is no action for us take on this issue. 

https://docs.ultralytics.com/help/minimum_reproducible_example/

**Comment by SilverStarCoder** [comment]
> @SilverStarCoder without an actual MRE there is no action for us take on this issue.
> 
> https://docs.ultralytics.com/help/minimum_reproducible_example/

Hi @glenn-jocher, sorry, after trying to create a reproducible piece of code, I discovered that the issue was due to our custom implementation and not related to the Ultralytics library. It has now been resolved. Thank you and apologies for the inconvenience caused.

**Comment by glenn-jocher** [comment]
Hi @SilverStarCoder, no problem at all. I'm glad to hear you were able to resolve the issue. If you have any other questions or run into further issues, feel free to reach out. Thank you for your understanding.
