### ISSUE TITLE
It has been modified to receive a total of 3 inputs: RGB, Depth, and thermal image.

### ISSUE THREAD

**Issue by mcw1217** [ultralytics/ultralytics#14470]
Based on the YOLOv8 model, the code was modified to perform object detection with a total of 3 images (RGB, Depth, and Thermal) as input. We extracted the feature map during the learning process and confirmed that accurate learning was possible. However, when loading a dataset, the augmentation train, validation, and test datasets each have different coefficients. How can we all have the same augmentation?

**Comment by pderrenger** [comment]
@mcw1217 to ensure consistent augmentation across your train, validation, and test datasets, you can set a fixed random seed before applying augmentations. This will help maintain uniformity in the transformations applied. Additionally, make sure the augmentation parameters are identical across all datasets. If you continue to face issues, please verify with the latest version of the package. If the problem persists, feel free to provide more details.
