### ISSUE TITLE
error reporting using VFL loss

### ISSUE THREAD

**Issue by WuChuhan** [ultralytics/ultralytics#1448]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Hello, I would like to ask what is the specific meaning of target_labels in VFL. When I try to use VFL to calculate the classification loss, the following error occurs. The dimensions do not match. How can I solve it? I went to see the source code of VFL Loss and found that there is no target_labels parameter. How should I use VFL Loss correctly?（my num_classes=7）

Traceback (most recent call last):
File "D:\code\ultralytics-main_8.0.43_20230222\ultralytics\yolo\v8\detect\train.py", line 241, in
train()
File "D:\code\ultralytics-main_8.0.43_20230222\ultralytics\yolo\v8\detect\train.py", line 237, in train
trainer.train()
File "D:\code\ultralytics-main_8.0.43_20230222\ultralytics\yolo\engine\trainer.py", line 189, in train
self._do_train(RANK, world_size)
File "D:\code\ultralytics-main_8.0.43_20230222\ultralytics\yolo\engine\trainer.py", line 311, in _do_train
self.loss, self.loss_items = self.criterion(preds, batch)
File "D:\code\ultralytics-main_8.0.43_20230222\ultralytics\yolo\v8\detect\train.py", line 83, in criterion
return self.compute_loss(preds, batch)
File "D:\code\ultralytics-main_8.0.43_20230222\ultralytics\yolo\v8\detect\train.py", line 210, in call
loss[1] = self.varifocal_loss(pred_scores, target_scores, target_labels) / target_scores_sum # VFL way
File "C:\Users\wuchu\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File "D:\code\ultralytics-main_8.0.43_20230222\ultralytics\yolo\utils\loss.py", line 17, in forward
weight = alpha * pred_score.sigmoid().pow(gamma) * (1 - label) + gt_score * label
RuntimeError: The size of tensor a (7) must match the size of tensor b (8400) at non-singleton dimension 2

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@WuChuhan hi, VFL is no longer maintained since we don't use it. If I remember this correctly you have to generator a one-hot vector first based on the current `target_labels` before passing it to VFL.

**Comment by WuChuhan** [comment]
> @WuChuhan hi, VFL is no longer maintained since we don't use it. If I remember this correctly you have to generate a one-hot vector first based on the current `target_labels` before passing it to VFL.

Hello, why don't you use VFL anymore? Is it because the effect is not good? Is there an official explanation?

**Comment by Laughing-q** [comment]
@WuChuhan yeah it doesn't show any improvements in our experiments.

**Comment by JiangnanCai** [comment]
> @WuChuhan hi, VFL is no longer maintained since we don't use it. If I remember this correctly you have to generate a one-hot vector first based on the current `target_labels` before passing it to VFL.

hi @Laughing-q
I still would like to have a try to apply vfl on my imbalanced dataset. 

Current `target_labels` with shape (16, 8400):
`tensor([[11, 11, 11,  ..., 11, 11, 11],
        [11, 11, 11,  ..., 11, 11, 11],
        [ 0,  0,  0,  ...,  0,  0,  0],
        ...,
        [ 9,  9,  9,  ...,  9,  9,  9],
        [ 8,  8,  8,  ...,  8,  8,  8],
        [ 2,  2,  2,  ...,  2,  2,  2]], device='cuda:0')` 

so i use following code to conver it to a one-hot tensor with same shape as `pred_scores` and `targets_scores`, which is in shape  (16, 8400, 13).

`target_labels = target_labels.unsqueeze(-1).expand(-1, -1, self.nc)
one_hot = torch.zeros(target_labels.size(), device=self.device)
one_hot.scatter_(-1, target_labels, 1)`

after the conversion, the `target_labels` is in shape (16, 8400, 13). In the third dimension, all are set to zero and only index==label would be set to one. 

is that the correct operation?

**Comment by hellowqc** [comment]
> @WuChuhan hi, VFL is no longer maintained since we don't use it. If I remember this correctly you have to generate a one-hot vector first based on the current `target_labels` before passing it to VFL.

Hello, may I ask how to set the target_ Convert labels to one hot vector?
