### ISSUE TITLE
How to use FASTSAM with camera

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/ultralytics#14481]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

how to use FASTSAM with camera ,with text prompet

**Comment by pderrenger** [comment]
@VYRION-Ai to use FastSAM with a camera and text prompts, you can set up a video capture stream and process each frame with the model. Make sure you have the latest version of the Ultralytics package. If you need further assistance, please refer to the [FastSAM documentation](https://docs.ultralytics.com/models/fast-sam/) for detailed guidance.

**Comment by VYRION-Ai** [comment]
@pderrenger but the documentation did not say how to get the segment object (like in detection we can save cropped object)\
like here i want to save the prombt results image 
```
`from ultralytics import FastSAM
from ultralytics.models.fastsam import FastSAMPrompt

# Define an inference source
source = "path/to/bus.jpg"

# Create a FastSAM model
model = FastSAM("FastSAM-s.pt")  # or FastSAM-x.pt

# Run inference on an image
everything_results = model(source, device="cpu", retina_masks=True, imgsz=1024, conf=0.4, iou=0.9)

# Prepare a Prompt Process object
prompt_process = FastSAMPrompt(source, everything_results, device="cpu")

# Text prompt
ann = prompt_process.text_prompt(text="a photo of a dog")
```
`
i want the line after this to get the images and the mask of the segment to crop it

**Comment by pderrenger** [comment]
@VYRION-Ai to save the prompt results image and mask, you can use the `plot` method from the `FastSAMPrompt` class. After generating the annotations with your text prompt, you can save the results like this:

```python
prompt_process.plot(annotations=ann, output="./output_directory/")
```

This will save the annotated image with the segmentation mask to the specified output directory. If you encounter any issues, please ensure you're using the latest version of the Ultralytics package. For more details, you can refer to the [FastSAM documentation](https://docs.ultralytics.com/models/fast-sam/).

**Comment by Laughing-q** [comment]
Hi @VYRION-Ai, the output `ann` variable is a `Results` object which you can use our api `masks` and `orig_img` to access the masks and source image.
```python
ann = prompt_process.text_prompt(text="a photo of a dog")
masks = ann[0].masks
source_image = ann[0].orig_img
```
More information please take a look at the `Results` section in our docs page: https://docs.ultralytics.com/modes/predict/#working-with-results
