### ISSUE TITLE
How to train from scratch to reproduce the results of instance segmentation (YOLOv8n-seg) in the project.

### ISSUE THREAD

**Issue by zyxunh** [ultralytics/ultralytics#1449]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can you introduce the details of your parameters in detail to train YOLOv8n-seg, such as batch size, how many GPUs were used, how many epochs were trained, and whether the model needs to be pre-trained on imagenet. And can I directly use the script ultralytics/yolo/v8/segment/train.py to train? Thank you so much.

**Comment by Laughing-q** [comment]
@zyxunh hi, all the segmentation models are trained from scratch without any pretrained weights. For yolov8n-seg, I think its batch-size and epochs are 128 and 500 separately, and other args are using the default value in default.yaml.
@glenn-jocher

**Comment by glenn-jocher** [comment]
@zyxunh you can see all training arguments by loading a model and printing it's args, i.e.

```python
from ultralytics import YOLO

model = YOLO('yolov8n-seg.pt')
print(model.ckpt['train_args'])

{'task': 'segment', 'mode': 'train', 'model': 'yolov8n-seg.yaml', 'data': 'coco.yaml', 'epochs': 500, 'patience': 50, 'batch': 16, 'imgsz': 640, 'save': True, 'cache': 'disk', 'device': 2, 'workers': 8, 'project': 'YOLOv8', 'name': 'yolov8n-seg', 'exist_ok': False, 'pretrained': False, 'optimizer': 'SGD', 'verbose': False, 'seed': 0, 'deterministic': True, 'single_cls': False, 'image_weights': False, 'rect': False, 'cos_lr': False, 'close_mosaic': 10, 'resume': False, 'overlap_mask': True, 'mask_ratio': 4, 'dropout': False, 'val': True, 'save_json': False, 'save_hybrid': False, 'conf': 0.001, 'iou': 0.7, 'max_det': 300, 'half': False, 'dnn': False, 'plots': True, 'source': 'ultralytics/assets/', 'show': False, 'save_txt': False, 'save_conf': False, 'save_crop': False, 'hide_labels': False, 'hide_conf': False, 'vid_stride': 1, 'line_thickness': 3, 'visualize': False, 'augment': False, 'agnostic_nms': False, 'retina_masks': False, 'format': 'torchscript', 'keras': False, 'optimize': False, 'int8': False, 'dynamic': False, 'simplify': False, 'opset': 17, 'workspace': 4, 'nms': False, 'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.937, 'weight_decay': 0.001, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 7.5, 'cls': 0.5, 'dfl': 1.5, 'fl_gamma': 0.0, 'label_smoothing': 0.0, 'nbs': 64, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0, 'copy_paste': 0.0, 'cfg': None, 'v5loader': False}
```

**Comment by glenn-jocher** [comment]
@zyxunh @Laughing-q the args above all look normal except for batch. All our detect, segment and pose models are trained at batch=128.

**Comment by zyxunh** [comment]
@glenn-jocher @Laughing-q Thank you very much for your reply, I will try to train my model with these cfg.

**Comment by unrue** [comment]
What about non-seg models? How to train from scratch? Thanks.

**Comment by glenn-jocher** [comment]
@unrue you're welcome to try training non-segmentation models from scratch! For non-segmentation models like detection (YOLOv8n), you can use the same training script `train.py` with the appropriate model configuration file (e.g., `yolov8n.yaml`) and dataset configuration file (e.g., `coco.yaml`). Here's a quick example to get you started:

```bash
yolo detect train data=coco.yaml model=yolov8n.yaml
```

This will train a YOLOv8n detection model on the COCO dataset. Just make sure to adjust the `batch size`, `epochs`, and any other parameters as needed for your specific use case. Happy training! 😊🚀

**Comment by unrue** [comment]
Hi Glenn,
trying from scratch and with augmentations I get:
```

yolo cfg=default_copy.yaml detect train data=dataset.yaml model=models/yolov8.yaml epochs=100 imgsz=1280 batch=64 device=0,1,2,3 2

    for i, (f, n, m, args) in enumerate(d["backbone"] + d["head"]):  # from, number, module, args
KeyError: 'backbone'
```

**Comment by glenn-jocher** [comment]
@unrue hi there! It looks like there might be an issue with the model configuration file you're using. The error suggests that the 'backbone' key is missing from your `yolov8.yaml` file. Please double-check that your YAML file is correctly formatted and includes all necessary sections, including the 'backbone'. Here's a snippet of what the beginning of a typical YOLOv8 YAML file should look like:

```yaml
# parameters
nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

# backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Focus, [64, 3]], ...]
```

Make sure your `yolov8.yaml` contains a similar structure. If you're still encountering issues, feel free to share more details or the content of your YAML file, and I'll be happy to help you further! 😊👍

**Comment by unrue** [comment]
Yes, It was a trivial file formatting problem. Now it works, thanks!

**Comment by glenn-jocher** [comment]
@unrue great to hear that it's working now! If you have any more questions or run into any other issues, just let us know. Happy training! 😊🚀

**Comment by Cung-AGA** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> ### Question
> Can you introduce the details of your parameters in detail to train YOLOv8n-seg, such as batch size, how many GPUs were used, how many epochs were trained, and whether the model needs to be pre-trained on imagenet. And can I directly use the script ultralytics/yolo/v8/segment/train.py to train? Thank you so much.
> 
> ### Additional
> _No response_

Have you done it yet? Can you guide me?

**Comment by glenn-jocher** [comment]
Hi @Cung-AGA,

Absolutely, I'd be happy to help guide you through training the YOLOv8n-seg model!

### Training Details:
- **Batch Size**: For optimal performance, we recommend a batch size of 128.
- **GPUs Used**: Typically, training is done using multiple GPUs. You can specify the GPUs using the `device` argument, e.g., `device=0,1,2,3`.
- **Epochs**: Training for 100 epochs is a good starting point, but this can be adjusted based on your dataset and convergence criteria.
- **Pre-trained on ImageNet**: Yes, starting with a model pre-trained on ImageNet can significantly speed up convergence and improve performance.

### Example Command:
You can use the following command to start training:

```bash
yolo segment train data=dataset.yaml model=yolov8n-seg.yaml epochs=100 imgsz=1280 batch=128 device=0,1,2,3
```

### Using the Training Script:
Yes, you can directly use the `ultralytics/yolo/v8/segment/train.py` script to train your model. Just ensure your dataset and model configuration files are correctly set up.

If you encounter any issues, please ensure you are using the latest versions of `torch` and `ultralytics`. If the problem persists, providing a minimum reproducible example would be very helpful. You can find more details on creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions. Happy training! 😊

**Comment by Cung-AGA** [comment]
> Hi @Cung-AGA,
> 
> Absolutely, I'd be happy to help guide you through training the YOLOv8n-seg model!
> 
> ### Training Details:
> * **Batch Size**: For optimal performance, we recommend a batch size of 128.
> * **GPUs Used**: Typically, training is done using multiple GPUs. You can specify the GPUs using the `device` argument, e.g., `device=0,1,2,3`.
> * **Epochs**: Training for 100 epochs is a good starting point, but this can be adjusted based on your dataset and convergence criteria.
> * **Pre-trained on ImageNet**: Yes, starting with a model pre-trained on ImageNet can significantly speed up convergence and improve performance.
> 
> ### Example Command:
> You can use the following command to start training:
> 
> ```shell
> yolo segment train data=dataset.yaml model=yolov8n-seg.yaml epochs=100 imgsz=1280 batch=128 device=0,1,2,3
> ```
> 
> ### Using the Training Script:
> Yes, you can directly use the `ultralytics/yolo/v8/segment/train.py` script to train your model. Just ensure your dataset and model configuration files are correctly set up.
> 
> If you encounter any issues, please ensure you are using the latest versions of `torch` and `ultralytics`. If the problem persists, providing a minimum reproducible example would be very helpful. You can find more details on creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> Feel free to reach out if you have any more questions. Happy training! 😊

I want to understand the problem, how to process data, like training from scratch.
It would be good if there was any document or video for this. Thank you very much.

**Comment by Cung-AGA** [comment]
> Hi @Cung-AGA,
> 
> Thank you for your interest in training YOLOv8n-seg from scratch! Here’s a concise guide to help you get started:
> 
> ### Data Preparation:
> 1. **Dataset Format**: Ensure your dataset is in the correct format. YOLOv8 expects datasets in the YOLO format, which includes:
>    
>    * **Images**: Stored in a directory.
>    * **Labels**: Corresponding `.txt` files with annotations in the format `[class_id, x_center, y_center, width, height]`.
> 2. **Dataset Configuration File**: Create a `dataset.yaml` file specifying paths to your training and validation datasets, and the number of classes. Here’s an example:
>    ```yaml
>    train: path/to/train/images
>    val: path/to/val/images
>    nc: 80  # number of classes
>    names: ['class1', 'class2', ...]  # list of class names
>    ```
> 
> ### Training from Scratch:
> To train from scratch, you can use the following command:
> 
> ```shell
> yolo segment train data=dataset.yaml model=yolov8n-seg.yaml epochs=100 imgsz=1280 batch=128 device=0,1,2,3
> ```
> 
> This command initializes a new model and starts training on your dataset.
> 
> ### Resources:
> For a detailed walkthrough, you can refer to the [Ultralytics YOLOv8 Documentation](https://docs.ultralytics.com/modes/train/) which covers various aspects of training, including data preparation, hyperparameter tuning, and more.
> 
> Additionally, you might find this [video tutorial](https://www.youtube.com/watch?v=example) helpful for visual guidance on training YOLOv8 models.
> 
> If you encounter any issues, please ensure you are using the latest versions of `torch` and `ultralytics`. If the problem persists, providing a minimum reproducible example would be very helpful. You can find more details on creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> Feel free to reach out if you have any more questions. Happy training! 😊

Oh, I mean you can have a certain guide for training from scratch with pytorch or not, from data processing steps, model building model architecture, model processing of the model, ...

**Comment by glenn-jocher** [comment]
Hi @Cung-AGA,

Thank you for your patience and for clarifying your request. Here's a more detailed guide to training YOLOv8n-seg from scratch, covering data processing, model building, and training steps.

### Data Processing:
1. **Dataset Preparation**:
   - **Images**: Store your images in a directory.
   - **Labels**: Create corresponding `.txt` files for each image with annotations in the format `[class_id, x_center, y_center, width, height]`.

2. **Dataset Configuration File**:
   Create a `dataset.yaml` file specifying paths to your training and validation datasets, and the number of classes. Example:
   ```yaml
   train: path/to/train/images
   val: path/to/val/images
   nc: 80  # number of classes
   names: ['class1', 'class2', ...]  # list of class names
   ```

### Model Building:
1. **Model Configuration**:
   Create a `yolov8n-seg.yaml` file defining the model architecture. Ensure it includes the backbone and head sections. Example:
   ```yaml
   nc: 80  # number of classes
   depth_multiple: 1.0
   width_multiple: 1.0

   backbone:
     [[-1, 1, Focus, [64, 3]], ...]

   head:
     [[-1, 1, Conv, [256, 3, 1]], ...]
   ```

### Training:
1. **Training Command**:
   Use the following command to start training:
   ```bash
   yolo segment train data=dataset.yaml model=yolov8n-seg.yaml epochs=100 imgsz=1280 batch=128 device=0,1,2,3
   ```

### Additional Resources:
For a comprehensive guide, refer to the [Ultralytics YOLOv8 Documentation](https://docs.ultralytics.com/modes/train/). This resource covers various aspects of training, including data preparation, hyperparameter tuning, and more.

If you encounter any issues, please ensure you are using the latest versions of `torch` and `ultralytics`. If the problem persists, providing a minimum reproducible example would be very helpful. You can find more details on creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions. Happy training! 😊

**Comment by Cung-AGA** [comment]
thank you very much

Vào Th 6, 21 thg 6, 2024 vào lúc 23:53 Glenn Jocher <
***@***.***> đã viết:

**Comment by glenn-jocher** [comment]
Hi @Cung-AGA,

You're very welcome! 😊

If you have any further questions or run into any issues, please ensure you're using the latest versions of `torch` and `ultralytics`. If the problem persists, providing a minimum reproducible example would be very helpful for us to investigate. You can find more details on creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Happy training, and feel free to reach out if you need more assistance!
