### ISSUE TITLE
Convert YOLO models to Torchscript GPU Half Precision

### ISSUE THREAD

**Issue by ganessh22** [ultralytics/ultralytics#14504]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm trying to convert to torchscript for GPU with FP16. 
```python
from ultralytics import YOLO
import torch

world_model = YOLO("yolov8x-worldv2.pt")
world_model.set_classes(["person", "car", "bus", "truck", "vehicle"])
world_model.save("custom_yolo_world.pt")
model = YOLO("custom_yolo_world.pt")
model.export(format="torchscript", imgsz=1280, half=True, batch=1, dynamic=False)
im = torch.zeros((5, 3, 1280, 1280), dtype=torch.half, device=torch.device("cuda:0"))
model_ts = torch.jit.load("custom_yolo_world.torchscript", _extra_files={"config.txt": ""})
model_ts(im)
```
I got it working by modifying `ultralytics/engine/exporter.py` L373 to make `self.model = self.model.cuda().half()` and `self.im = self.im.cuda().half()` but I keep getting this error on inference afterwards : 
```bash
RuntimeError: tensor_inputs_to_check.size() INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/graph_fuser.cpp":1494, please report a bug to PyTorch. CudaFusionGuard expects at least one tensor input
```
I can get one forward to run sometimes but afterwards I'm stuck with this error. I am using torch1.12+cu11.6. Do I have to switch to torch 2.0+?

**Comment by pderrenger** [comment]
@ganessh22 it sounds like you're on the right track with converting your YOLO model to TorchScript with FP16 precision. The error you're encountering is likely related to the specific PyTorch version you're using. Upgrading to PyTorch 2.0+ could resolve this issue, as it includes numerous improvements and bug fixes for TorchScript and CUDA operations. Please try updating your PyTorch version and see if the problem persists. If the issue continues, ensure you're using the latest version of the Ultralytics package. Let us know how it goes!

**Comment by ganessh22** [comment]
It works fine with torch 2.3.1. Thank you. I will update my codes to use a newer torch version.

**Comment by pderrenger** [comment]
@ganessh22 great to hear that updating to torch 2.3.1 resolved the issue! If you encounter any further questions or need additional assistance, feel free to reach out. Happy coding!

**Comment by ajeevi32189** [comment]
i am convert yolov8n in torchscripts modal this modal not work no detect person please help

**Comment by glenn-jocher** [comment]
@ajeevi32189 to help diagnose why your YOLOv8n TorchScript model isn't detecting people, could you share your export and inference code? Common issues include incorrect input preprocessing (image normalization, resizing) or missing postprocessing steps. Also verify that your original .pt model works correctly before conversion.
