### ISSUE TITLE
train

### ISSUE THREAD

**Issue by 1178413203** [ultralytics/ultralytics#1450]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to add some background image training with empty labels, but I found that the model will skip the background image training directly, what should I do?

**Comment by Laughing-q** [comment]
@1178413203 hi background images with empty labels are included while training. :)

**Comment by 1178413203** [comment]
Training an empty txt label file, what training parameters do I need to modify?

**Comment by Laughing-q** [comment]
@1178413203 don't need to modify anything, just do not provide the corresponding txt files in the labels folder.

**Comment by 1178413203** [comment]
Thank you for your answer

**Comment by pderrenger** [comment]
@1178413203 you're welcome! If you have any more questions, feel free to ask. Good luck with your training!

**Comment by glenn-jocher** [comment]
@pderrenger Happy to help! Good luck with your project! 🚀

**Comment by glenn-jocher** [comment]
@pderrenger You're welcome! Happy to help. 😊 Good luck with your project!
