### ISSUE TITLE
Attention model in YOLOv8

### ISSUE THREAD

**Issue by furycurry** [ultralytics/ultralytics#14515]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Greetings.

I am trying to include [EMA](https://github.com/YOLOonMe/EMA-attention-module) in yolov8 but its giving out an error stating 
```
Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/553 [00:00<?, ?it/s]/usr/local/anaconda3/envs/john/lib/python3.10/site-packages/torch/autograd/__init__.py:200: UserWarning: adaptive_avg_pool2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
      1/300      2.28G      4.763      5.294      5.133          5        640:  
```

Will be very much helpful if you can guide how to avoid the error and run the model.
I have included the changes made to the original **ultralytics** folder.

### 2. Made changes to parse_model
```
        elif m in {EMA}:
            args = [ch[f], *args]

```

### 3. Created YAML file
```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
#  n: [0.33, 0.25, 1024] # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
#  s: [0.33, 0.50, 1024] # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768] # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
#  l: [1.00, 1.00, 512] # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
#  x: [1.00, 1.25, 512] # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

backbone:

  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2f, [512]] # 12
  - [-1, 1, EMA, [8]] #13

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2f, [256]] # 15 (P3/8-small)
  - [-1, 1, EMA, [8]] #16

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 13], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2f, [512]] # 19 (P4/16-medium)
  - [-1, 1, EMA, [8]] # 20

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2f, [1024]] # 23 (P5/32-large)
  - [-1, 1, EMA, [8]] #24

  - [[17, 21, 25], 1, Detect, [nc]] # Detect(P3, P4, P5)
```

**Comment by pderrenger** [comment]
@furycurry greetings,

The warning you're encountering is related to the deterministic algorithms setting in PyTorch. This setting ensures reproducibility but can cause issues with certain operations that do not have deterministic implementations. To resolve this, you can disable deterministic algorithms by setting `torch.use_deterministic_algorithms(False)` in your script. This should bypass the warning and allow your model to run without errors.

Additionally, ensure that your custom EMA module is correctly integrated and compatible with the rest of the YOLOv8 architecture. If the issue persists, please verify that you are using the latest versions of Ultralytics and PyTorch, as updates may include fixes for such issues.

For further assistance, you can refer to the [YOLO Common Issues Guide](https://docs.ultralytics.com/guides/yolo-common-issues/).

**Comment by Y-T-G** [comment]
Pass `deterministic=False`

https://github.com/ultralytics/ultralytics/blob/bfcd85323da7137c031b5104d5f651d949862600/docs/en/modes/train.md?plain=1#L199

**Comment by furycurry** [comment]
@pderrenger @Y-T-G Thank you for the reply.

I have passed `deterministic=False` in the **train.py**. Its working now.

**Comment by pderrenger** [comment]
Great to hear that it's working now! If you encounter any further issues or have additional questions, feel free to reach out. Always ensure you're using the latest versions of Ultralytics and PyTorch for the best experience. Happy training!
