### ISSUE TITLE
AutoBatch on nano fails memory allocation after a few epochs

### ISSUE THREAD

**Issue by Simzie** [ultralytics/ultralytics#1451]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

[Output.txt](https://github.com/ultralytics/ultralytics/files/10986579/Output.txt)

AutoBatch: Computing optimal batch size for imgsz=480
AutoBatch: CUDA:0 (NVIDIA GeForce RTX 4090) 23.99G total, 0.22G reserved, 0.05G allocated, 23.71G free
      Params      GFLOPs  GPU_mem (GB)  forward (ms) backward (ms)                   input                  output
     3011043       4.609         0.285         76.89         15.98        (1, 3, 480, 480)                    list
     3011043       9.218         0.445         17.64         12.85        (2, 3, 480, 480)                    list
     3011043       18.44         0.470         18.99         14.43        (4, 3, 480, 480)                    list
     3011043       36.87         0.719         21.39          16.5        (8, 3, 480, 480)                    list
     3011043       73.75         1.197         20.45         17.97       (16, 3, 480, 480)                    list
AutoBatch: Using batch-size 281 for CUDA:0 16.87G/23.99G (70%) ✅

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/2 [00:33<?, ?it/s]

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.41 GiB (GPU 0; 23.99 GiB total capacity; 17.92 GiB already allocated; 0 bytes free; 21.17 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Environment

Ultralytics YOLOv8.0.53 🚀 Python-3.8.10 torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce RTX 4090, 24564MiB)
WSL2 Ubuntu 20.04.6 LTS
Torch '2.0.0+cu117'
Tensorflow '2.11.0'

### Minimal Reproducible Example

!yolo task=detect mode=train model=yolov8n.pt imgsz=480 data=v8.yaml epochs=100 batch=-1 patience = 20 name=runs/detect/result_1

### Additional

It seems the auto batch is flying too close to the sun, and while it starts off ok after 2-4 epochs it gives a memory allocation error. Scaling back the batch size will allow it to train. I've only seen this with the nano model, i guess a the smaller size generally allows for a more finely tuned batch size.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Simzie oh interesting. Yes, CUDA allocation is super hard to estimate ahead of time. I'll reduce autobatch default to 2/3 of the space then at 0.67 based on your results above.

**Comment by glenn-jocher** [comment]
@Simzie updated in https://github.com/ultralytics/ultralytics/pull/1447/commits/c8b7265a064f99798bf4c050ccb5e82679268d9b for 8.0.54
