### ISSUE TITLE
How to get total mAP without confidence score limits

### ISSUE THREAD

**Issue by YOOHYOJEONG** [ultralytics/ultralytics#14514]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi.

I want to get the full mAP value.

It seems that the mAP values obtained through the model.val of ultralytics are mAPs for those with confidence score thresholds between 0.5 and 0.95, or only mAPs for those with 0.5 or 0.75 or higher.

I want to get mAP for the whole result without limiting the confidence score value.

What should I do?

Thank you.

**Comment by Y-T-G** [comment]
That would 100%

**Comment by YOOHYOJEONG** [comment]
@Y-T-G Oh, Sorry. 
It's not IoU threshold, it's confidence score threshold. It was my mistake.

**Comment by Y-T-G** [comment]
mAP is based on the whole confidence range. There's no limit used.

**Comment by YOOHYOJEONG** [comment]
Oh.. I totally understand.
I only now know that I asked a stupid question.

Thank you.

**Comment by pderrenger** [comment]
No problem at all! Your question was valid and it's great that you're seeking to understand the details. If you have any more questions or need further clarification, feel free to ask. We're here to help!
