### ISSUE TITLE
how can i extract bbox classid and confidence scores 

### ISSUE THREAD

**Issue by Vinaygoudasp7** [ultralytics/ultralytics#14520]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

# Prepare your input data
img_path = 'D:/AIML/Tensorflow_FW/realtimetrafficlightand_vehicles-8/train/images/192_168_1_34_ch1_20240614_175127_mp4-0000_jpg.rf.5fbc9329362f75a9e44e59431da11bf0.jpg'
img = Image.open(img_path).resize((640, 640))  # Resize image to the size expected by the model
img_array = np.array(img, dtype=np.float32)
img_array = img_array / 255.0  # Normalize if required by the model
img_array = img_array[None, ...]  # Add batch dimension

model=tf.saved_model.load("D:/AIML/Tensorflow_FW/yolov8m_saved_model")
input_tensor = tf.convert_to_tensor(img_array)  # Convert numpy array to tensor
predictions = model(input_tensor)
print(predictions) help me how to solve this problem

**Comment by Kayzwer** [comment]
```
from ultralytics import YOLO

model = YOLO("/path/to/model")
result = model("/path/to/img")
result[0].boxes #  this is the object that contains bbox info
```

**Comment by Vinaygoudasp7** [comment]
@Kayzwer  thank  you for responce is it works in tenserflow frame work bcz i am curently working on tenserflow

**Comment by Y-T-G** [comment]
https://github.com/ultralytics/ultralytics/blob/bfcd85323da7137c031b5104d5f651d949862600/examples/YOLOv8-OpenCV-int8-tflite-Python/main.py#L181

**Comment by Vinaygoudasp7** [comment]
@Y-T-G  thnks it works
