### ISSUE TITLE
Is there any solutions to change save_dir and file name by python?

### ISSUE THREAD

**Issue by MikeHawkIsGold** [ultralytics/ultralytics#1453]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I receive files which will be predicted from back-end to YOLOv8. The name of those files includes a timestamp, which means that the name of each file is unique. However, I found that the save_dir always be like
"predict/xxx"
"predict2/xxx"
"predictCount/xxx".
I can not get the folder_name by the timestamp, which makes me so confused. Because I need the result_path.

**Comment by Laughing-q** [comment]
@MikeHawkIsGold save_dir is composed of `project` and `name`. You can change save_dir by modify these two args. :)
`save_dir=project/name`.

**Comment by MikeHawkIsGold** [comment]
> @MikeHawkIsGold save_dir is composed of `project` and `name`. You can change save_dir by modify these two args. :) `save_dir=project/name`.

You mean I can modify it like that?
`results = model.predict(source=xxx, project="xxx", name="xxx")`
I am sorry that I still do not understand your mean exactly...

**Comment by Laughing-q** [comment]
@MikeHawkIsGold yes!
