### ISSUE TITLE
xywh returns wrong result while xyxy returns right result

### ISSUE THREAD

**Issue by dvdcjw** [ultralytics/ultralytics#14539]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

xywh returns wrong result while xyxy returns right result

### Environment

windows, python3.10

### Minimal Reproducible Example

import time

start = time.perf_counter()
import dxcam
import cv2

confidence_threshold = 0.5

from ultralytics import YOLO

model = YOLO()
camera = dxcam.create()
camera.start()

print('init time', time.perf_counter() - start)

while True:
    time.sleep(2)
    frameBGR = camera.get_latest_frame()
    frameRGB = cv2.cvtColor(frameBGR, cv2.COLOR_BGR2RGB)
    cv2.imwrite('tmp.jpeg', frameRGB)
    # frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
    results = model(frameRGB)[0]
    for i in results:
        x, y, w, h = [int(i) for i in i.boxes.xywh[0]]
        name = i.names[int(i.boxes.cls[0])]
        conf = round(float(i.boxes.conf[0]), 2)

### Additional

the bug isn't caused by dxcam, it returns the right screenshot I need. Since I imwrite it into a file and double checked.
the imwrite photo: (Blocked unnecessary detail.)
![tmp](https://github.com/user-attachments/assets/43948e7a-bb12-477e-994f-d7a4e618d436)

In this case,
[int(i) for i in i.boxes.xywh[0]] returns
[1416, 838, 520, 763]
[int(i) for i in i.boxes.xyxy[0]] returns
[1155, 457, 1676, 1220]
It's very obvious that they conflict with eachother.
after manual checking, 
I found out that the xyxy returned the right result，while xywh's wh is correct but xy is not

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@dvdcjw Hi, thanks for the reporting! however from your sample:
```bash
[int(i) for i in i.boxes.xywh[0]] returns
[1416, 838, 520, 763]
[int(i) for i in i.boxes.xyxy[0]] returns
[1155, 457, 1676, 1220]
```
I don't see any incorrect results of xywh. The `xy` in `xywh` format here we are using represents for the coordinate of center point.
`xyxy` format represents left-top coordinate and right-down.

**Comment by abhaysjuneja** [comment]
I think the issue is in the documentation of the xywh.
See here: https://github.com/ultralytics/ultralytics/blob/62094bd03fc6d14726a8362ccb7e2872fe6b7909/ultralytics/engine/results.py#L995

The current docstring says it returns x,y as the coordinates of the top-left vertex of the box, whereas in reality it returns x,y as the coordinates of the centroid of the box.

**Comment by glenn-jocher** [comment]
@abhaysjuneja thank you for pointing that out. You are correct; the `xywh` format returns the coordinates of the centroid of the box, not the top-left vertex. We will update the documentation to reflect this accurately. Please verify if the issue persists with the latest package version.

**Comment by Laughing-q** [comment]
@abhaysjuneja Nice catch! I've submitted a [PR](https://github.com/ultralytics/ultralytics/pull/15765) to fix the docstring! Thanks for the reporting!

**Comment by glenn-jocher** [comment]
@Laughing-q good fix!
