### ISSUE TITLE
FedAvg with YOLO

### ISSUE THREAD

**Issue by atahmih** [ultralytics/ultralytics#14535]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I understand there is an [implementation of Federated Learning with Flower](https://github.com/orgs/ultralytics/discussions/9440). But I want to manually average the weights myself. 

I use the following code to achieve this, but for some reason, the averaged model does not have any different performance from a local model (literally!!). The results for all epochs are exactly the same in both cases. 

I'd like to know if I have missed something in the implementation of weight averaging.  Thanks in advance.

```
# Load the models
client_models = {}
for i in range(num_clients):
    client_models[f'{i+1}'] = YOLO(f'client{i+1}/saved_model/yolo-last.pt')

state_dicts = [client_models[f'{i+1}'].model.state_dict() for i in range(num_clients)]

# Get the set of all keys present in the state dictionaries
all_keys = set(state_dicts[0].keys())
for state_dict in state_dicts:
    all_keys.update(state_dict.keys())

# Step 3: Average the Weights
print("Averaging model weights")
avg_state_dict = {}

# Initialize the averaged state dict with zeros of the same type
for key in all_keys:
    # Check if the key exists in all state_dicts, otherwise skip
    if all(key in state_dict for state_dict in state_dicts):
        avg_state_dict[key] = torch.zeros_like(state_dicts[0][key], dtype=torch.float32)
    else:
        # If the key is missing in any state_dict, raise an error or handle as needed
        print(f"Warning: Key {key} is missing in some state dictionaries")

# Sum the weights from each client
for state_dict in state_dicts:
    for key in avg_state_dict.keys():
        avg_state_dict[key] += state_dict[key].float()

# Divide by the number of clients to get the average
for key in avg_state_dict.keys():
    avg_state_dict[key] = torch.div(avg_state_dict[key], num_clients)
    # avg_state_dict[key] /= num_clients

# Convert back to original data types
for key in avg_state_dict.keys():
    avg_state_dict[key] = avg_state_dict[key].to(state_dicts[0][key].dtype)

for i in range(num_clients):
    client_models[f'{i+1}'].model.load_state_dict(avg_state_dict)
    # Save the updated model if needed
    print("Save client models")
    client_models[f'{i+1}'].save(f'client{i+1}/saved_model/yolo-avg.pt')
```

**Comment by pderrenger** [comment]
@atahmih thank you for your detailed question. It appears you are correctly averaging the weights of the models. However, if the performance remains unchanged, it might be due to several factors. Ensure that the models are indeed different before averaging. If they are identical, averaging won't change the outcome. Also, verify that the training data for each client is diverse enough to benefit from federated learning. Lastly, check if there are any issues with the state_dict keys or data types that might affect the averaging process. If the issue persists, please try updating to the latest version of the Ultralytics package to see if it resolves the problem.

**Comment by Y-T-G** [comment]
Saving like that won't work.

```python
model.ckpt = dict(model=model.model)
model.save("saved.pt")
```

**Comment by atahmih** [comment]
@Y-T-G This works perfect!! Thanks! 
I have trained for a few rounds of the federated step and the results are different. Could you explain why this method of saving works while the previous one doesn't?

Thanks for the suggestion too @pderrenger

**Comment by pderrenger** [comment]
@atahmih i'm glad to hear it's working for you now! The difference lies in how the model's state is saved. By using `model.ckpt = dict(model=model.model)` and then saving, you're ensuring that the model's state is correctly encapsulated and preserved. The previous method might not have captured all necessary components of the model's state, leading to inconsistencies. If you have further questions or need additional clarification, feel free to ask!

**Comment by Y-T-G** [comment]
No idea why it doesn't work the other way. I just know it out of experience.

**Comment by sanjaiiv04** [comment]
I used the code by @atahmih and I am facing an issue. There is a mismatch in the weights of the clients and it is unable to aggregate. Here is my version of the code:


import torch
from ultralytics import YOLO

NUM_CLIENTS = 3  # Define the number of clients
MODEL_PATH_TEMPLATE = "/content/client_{}/yolo_training/client_{}.pt"

# Load the trained YOLO models from each client
client_models = {}

for i in range(NUM_CLIENTS):
    client_id = i + 1
    model_path = MODEL_PATH_TEMPLATE.format(client_id, client_id)  # Get model path
    client_models[f'{client_id}'] = YOLO(model_path)  # Load trained YOLO model

# Extract state_dicts from each client model
state_dicts = [client_models[f'{i+1}'].model.state_dict() for i in range(NUM_CLIENTS)]

# Get the complete set of all keys in the model state_dicts
all_keys = set(state_dicts[0].keys())
for state_dict in state_dicts:
    all_keys.update(state_dict.keys())

# Step 3: Securely Average the Weights
print("🔄 Averaging model weights...")

avg_state_dict = {}

# Initialize the averaged state dictionary with zeros of the correct type
for key in all_keys:
    # Check if the key exists in all client state_dicts
    if all(key in state_dict for state_dict in state_dicts):
        avg_state_dict[key] = torch.zeros_like(state_dicts[0][key], dtype=torch.float32)
    else:
        print(f"⚠️ Warning: Key {key} is missing in some state dictionaries, skipping it.")

# Sum the weights from each client
for state_dict in state_dicts:
    for key in avg_state_dict.keys():
        avg_state_dict[key] += state_dict[key].float()  # Convert to float32 to avoid dtype errors

# Compute the average weight
for key in avg_state_dict.keys():
    avg_state_dict[key] /= NUM_CLIENTS  # Divide by number of clients

# Convert back to original data types
for key in avg_state_dict.keys():
    avg_state_dict[key] = avg_state_dict[key].to(state_dicts[0][key].dtype)

# Load the averaged weights into the global model
global_model = YOLO("yolov8n.pt")  # Load a fresh YOLO model for global aggregation
global_model.load_state_dict(avg_state_dict)  # Load aggregated weights

# Save the aggregated model
global_model_path = "/content/global_yolo.pt"
global_model.ckpt = dict(model=global_model.model)
global_model.save("/content/saved.pt")

print(f"✅ Federated aggregation complete. Global model saved at {global_model_path}")

This is the error I am encountering: 

🔄 Averaging model weights...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-33-55976d9660f4>](https://localhost:8080/#) in <cell line: 0>()
     49 # Load the averaged weights into the global model
     50 global_model = YOLO("yolov8n.pt")  # Load a fresh YOLO model for global aggregation
---> 51 global_model.load_state_dict(avg_state_dict)  # Load aggregated weights
     52 
     53 # Save the aggregated model

[/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in load_state_dict(self, state_dict, strict, assign)
   2582 
   2583         if len(error_msgs) > 0:
-> 2584             raise RuntimeError(
   2585                 "Error(s) in loading state_dict for {}:\n\t{}".format(
   2586                     self.__class__.__name__, "\n\t".join(error_msgs)

RuntimeError: Error(s) in loading state_dict for YOLO:
	Missing key(s) in state_dict: "model.model.0.conv.weight", "model.model.0.bn.weight", "model.model.0.bn.bias", "model.model.0.bn.running_mean", "model.model.0.bn.running_var", "model.model.1.conv.weight", "model.model.1.bn.weight", "model.model.1.bn.bias", "model.model.1.bn.running_mean", "model.model.1.bn.running_var", "model.model.2.cv1.conv.weight", "model.model.2.cv1.bn.weight", "model.model.2.cv1.bn.bias", "model.model.2.cv1.bn.running_mean", "model.model.2.cv1.bn.running_var", "model.model.2.cv2.conv.weight", "model.model.2.cv2.bn.weight", "model.model.2.cv2.bn.bias", "model.model.2.cv2.bn.running_mean", "model.model.2.cv2.bn.running_var", "model.model.2.m.0.cv1.conv.weight", "model.model.2.m.0.cv1.bn.weight", "model.model.2.m.0.cv1.bn.bias", "model.model.2.m.0.cv1.bn.running_mean", "model.model.2.m.0.cv1.bn.running_var", "model.model.2.m.0.cv2.conv.weight", "model.model.2.m.0.cv2.bn.weight", "model.model.2.m.0.cv2.bn.bias", "model.model.2.m.0.cv2.bn.running_mean", "model.model.2.m.0.cv2.bn.running_var", "model.model.3.conv.weight", "model.model.3.bn.weight", "model.model.3.bn.bias", "model.model.3.bn.running_mean", "model.model.3.bn.running_var", "model.model.4.cv1.conv.weight", "model.model.4.cv1.bn.weight", "model.model.4.cv1.bn.bias", "model.model.4.cv1.bn.running_mean", "model.model.4.cv1.bn.running_var", "model.model.4.cv2.conv.weight", "model.model.4.cv2.bn.weight", "model.model.4.cv2.bn.bias", "model.model.4.cv2.bn.running_mean", "model.model.4.cv2.bn.runnin...
	Unexpected key(s) in state_dict: "model.6.m.1.cv2.bn.running_mean", "model.8.m.0.cv1.conv.weight", "model.22.cv2.2.0.conv.weight", "model.8.m.0.cv2.bn.bias", "model.2.cv1.bn.num_batches_tracked", "model.8.m.0.cv1.bn.running_var", "model.2.m.0.cv2.bn.running_mean", "model.22.cv2.1.1.bn.running_var", "model.16.bn.bias", "model.5.conv.weight", "model.18.m.0.cv2.bn.num_batches_tracked", "model.8.m.0.cv2.bn.num_batches_tracked", "model.22.cv2.2.1.bn.bias", "model.9.cv1.bn.running_var", "model.12.cv1.bn.weight", "model.18.cv2.bn.bias", "model.6.m.1.cv1.bn.bias", "model.5.bn.running_mean", "model.22.cv2.2.1.conv.weight", "model.15.cv2.bn.weight", "model.15.m.0.cv2.bn.running_var", "model.15.cv2.bn.num_batches_tracked", "model.22.cv3.0.0.bn.num_batches_tracked", "model.22.cv3.0.1.bn.num_batches_tracked", "model.22.cv3.2.1.bn.num_batches_tracked", "model.22.cv2.0.1.bn.bias", "model.2.cv2.conv.weight", "model.6.m.0.cv1.bn.running_var", "model.22.cv3.0.0.bn.bias", "model.2.cv1.bn.running_var", "model.21.m.0.cv2.conv.weight", "model.16.bn.running_mean", "model.22.cv3.0.0.bn.running_var", "model.15.cv2.bn.running_var", "model.7.bn.running_var", "model.22.cv3.1.0.bn.running_mean", "model.22.cv2.0.0.bn.num_batches_tracked", "model.22.cv3.2.0.bn.num_batches_tracked", "model.6.cv2.bn.bias", "model.22.cv2.1.1.bn.bias", "model.0.bn.num_batches_tracked", "model.4.m.1.cv2.conv.weight", "model.22.cv3.1.1.bn.num_batches_tracked", "model.6.m.1.cv2.bn.running_var", "model.12.m.0.cv2.conv.weight",...

**Comment by sanjaiiv04** [comment]
For reference, here is my training script for the clients:

import torch
import threading
from pathlib import Path

def train_client(client_id):
    print(f"🔄 Training YOLO model for {client_id}...")

    model = YOLO("yolov8n.pt")
    model.train(data=YAML_PATH, epochs=5, imgsz=640, project=f"/content/{client_id}/yolo_training")

    model_save_path = Path(f"/content/{client_id}/yolo_training/{client_id}.pt")
    model_save_path.parent.mkdir(parents=True, exist_ok=True)
    model.ckpt = {"model": model.model}
    model.save(model_save_path)

    print(f"✅ Training complete for {client_id}. Model saved to {model_save_path}")
    return model_save_path

# Run training in parallel for the 3 clients
threads = []
client_models = {}

for client in CLIENTS:
    thread = threading.Thread(target=lambda: client_models.update({client: train_client(client)}))
    threads.append(thread)
    thread.start()

for thread in threads:
    thread.join()

print("✅ All clients trained successfully!")

**Comment by Y-T-G** [comment]
The mismatch is because the model state dict is from a fused model. You need to avoid fusing the model.

**Comment by sanjaiiv04** [comment]
> The mismatch is because the model state dict is from a fused model. You need to avoid fusing the model.

@Y-T-G How do I prevent that? Also, I tried to create a deep copy of the global model for the clients to train and learn the weights. Once the weights are aggregated I tried to feed it back to the global model and still the error persists.

**Comment by Y-T-G** [comment]
https://github.com/ultralytics/ultralytics/issues/14826#issuecomment-2258727121

**Comment by sanjaiiv04** [comment]
@Y-T-G @pderrenger Let me share my code completely so you can understand where I am coming from. 

gmodel = YOLO("yolov8n.pt")

#Training the clients
import torch
import threading
from pathlib import Path

def train_client(client_id):
    print(f"🔄 Training YOLO model for {client_id}...")
    cmodel = copy.deepcopy(gmodel)
    cmodel.train(data=YAML_PATH, epochs=10, imgsz=640, project=f"/content/{client_id}/yolo_training")

    model_save_path = Path(f"/content/{client_id}/yolo_training/{client_id}.pt")
    model_save_path.parent.mkdir(parents=True, exist_ok=True)
    cmodel.ckpt = {"model": cmodel.model}
    cmodel.save(model_save_path)

    print(f"✅ Training complete for {client_id}. Model saved to {model_save_path}")
    return model_save_path

threads = []
trained_models = {}

for client in CLIENTS:
    thread = threading.Thread(target=lambda client=client: trained_models.update({client: train_client(client)}))
    threads.append(thread)
    thread.start()

for thread in threads:
    thread.join()

client_models = trained_models.copy()
print("✅ All clients trained successfully!")

# Averaging the weights
client_models = {}
num_clients = 3

for i in range(num_clients):
    client_id = i + 1
    model_path = f'/content/client_{client_id}/yolo_training/client_{client_id}.pt'
    client_models[f'{client_id}'] = YOLO(model_path)

state_dicts = [client_models[f'{i+1}'].model.state_dict() for i in range(num_clients)]

all_keys = set(state_dicts[0].keys())
for state_dict in state_dicts:
    all_keys.update(state_dict.keys())

print("🔄 Averaging model weights")
avg_state_dict = {}

for key in all_keys:
    if all(key in state_dict for state_dict in state_dicts):  # Ensure key exists in all models
        avg_state_dict[key] = torch.zeros_like(state_dicts[0][key], dtype=torch.float32)
    else:
        print(f"⚠️ Warning: Key {key} is missing in some state dictionaries. Skipping.")

for state_dict in state_dicts:
    for key in avg_state_dict.keys():
        avg_state_dict[key] += state_dict[key].float()

for key in avg_state_dict.keys():
    avg_state_dict[key] = avg_state_dict[key] / num_clients  # Element-wise division

for key in avg_state_dict.keys():
    avg_state_dict[key] = avg_state_dict[key].to(state_dicts[0][key].dtype)


gmodel.load_state_dict(avg_state_dict,strict=True)
gmodel.model.ckpt = dict(model=gmodel.model)  # Ensure checkpoint dict is correct
gmodel.save("/content/yoloAvg.pt")

print("✅ Federated model saved as yoloAvg.pt")

When I run this, I get a weird problem. It aggregates the weights but then when evaluating the average weights, it shows the classes from the COCO dataset and not my classes.

**Comment by aymuos15** [comment]
Just a quick update from me: In collaboration with a colleague from my department (https://github.com/Yang-Li86), we have now solved this. Please find it here: https://github.com/KCL-BMEIS/UltraFlwr . It was recently accepted to a MICCAI workshop!

**Comment by glenn-jocher** [comment]
@sanjaiiv04 the issue with seeing COCO classes instead of your custom classes after weight averaging is because the `state_dict` only contains model parameters, not metadata like class names. You need to also preserve the model's class information during aggregation.

Try this approach:

```python
# After loading your trained client models, preserve the class info
client_models = {}
for i in range(num_clients):
    client_id = i + 1
    model_path = f'/content/client_{client_id}/yolo_training/client_{client_id}.pt'
    client_models[f'{client_id}'] = YOLO(model_path)

# Use the first client's model as the base to preserve metadata
base_model = client_models['1']
gmodel.model.load_state_dict(avg_state_dict, strict=False)

# Preserve class information from your trained model
gmodel.model.names = base_model.model.names
gmodel.model.nc = base_model.model.nc

gmodel.ckpt = dict(model=gmodel.model)
gmodel.save("/content/yoloAvg.pt")
```

This should maintain your custom class information after averaging. Also, great work @aymuos15 on the UltraFlwr solution!
