### ISSUE TITLE
Codebase for running YoloV10 with ONNX

### ISSUE THREAD

**Issue by JijaProGamer** [ultralytics/ultralytics#14538]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Since YoloV10 is released and added to ultralytics package, and it has exports to ONNX, how would I use it? Is there any codebase I can inspire from? I cannot use any yolov8 codebase, as that had a NMS approach so the output would be very different.

I plan on using ONNX with NodeJS, but it's almost the same as vanilla ONNX so any code base works.

If there isn't any ONNX codebase yet, a pytorch codebase would be okay too

**Comment by Y-T-G** [comment]
It's the same as YOLOv8. You just skip the NMS part.

**Comment by JijaProGamer** [comment]
Thanks, I'll give that a try and give a response if I am successful

**Comment by JijaProGamer** [comment]
I've tried running it with the same codebase as YOLOv8, but confidence is always 0 for some reason:

`
const ort = require('onnxruntime-node');
const fs = require("fs");
const path = require("path")

const constants = JSON.parse(fs.readFileSync(path.join(__dirname, "constants.json")))

async function predict(image) {
    const output = await run_model(image.map(v => v / 255.0));

    return process_output(output);
}

async function run_model(input) {
    const model = await ort.InferenceSession.create(path.join(__dirname, "model.onnx"));
    input = new ort.Tensor(Float32Array.from(input), [1, 3, constants.model_size[1], constants.model_size[0]]);

    console.log(input)
    const outputs = await model.run({ images: input });
    return outputs["output0"].data;
}

function process_output(output) {
    let boxes = [];
    for (let index = 0; index < 8400; index++) {
        const [class_id, prob] = [...Array(80).keys()]
            .map(col => [col, output[8400 * (col + 4) + index]])
            .reduce((accum, item) => item[1] > accum[1] ? item : accum, [0, 0]);

        if (prob < constants.probabilities[class_id]) {
            continue;
        }

        const label = constants.labels[class_id];

        const xc = output[index];
        const yc = output[8400 + index];
        const w = output[2 * 8400 + index];
        const h = output[3 * 8400 + index];
        const x1 = (xc - w / 2);
        const y1 = (yc - h / 2);
        const x2 = (xc + w / 2);
        const y2 = (yc + h / 2);

        boxes.push([x1, y1, x2, y2, label, prob]);
    }

    return boxes;
}

module.exports = { predict };
`

**Comment by Y-T-G** [comment]
The model already outputs (1, 300, 6) boxes. 300 boxes. The first 4 of the 6 values are the coordinates (xyxy). 5th value is the confidence. And 6th value is the lable. You just need to apply the confidence threshold based on the 5th value.

**Comment by JijaProGamer** [comment]
Thanks, I'll take that into consideration and post a result soon

**Comment by pderrenger** [comment]
You're welcome! Looking forward to hearing about your results. If you encounter any issues or have further questions, feel free to reach out.

**Comment by JijaProGamer** [comment]
Yes, I got it working, and it's wonderfull. Recall is from 80% to 90%, precision from 90% to 95%, mAP from 80% to 90%, and switfching from tfjs-webgl to onnxruntime with dml got my frametime from 40ms per frame to 16ms per frame (RX  6750 XT, 350x250 frames, and of course from yolov8s to yolov10s)

This is the final code:

`
const ort = require('onnxruntime-node');
const fs = require("fs");
const path = require("path");

const constants = JSON.parse(fs.readFileSync(path.join(__dirname, "constants.json")))
let model;

async function predict(image) {
    const input = modifyInput(Float32Array.from(image, value => value / 255.0))
    const output = await run_model(input);

    return process_output(output);
}

function modifyInput(image){
    const reshapedArray = new Float32Array(3 * constants.model_size[1] * constants.model_size[0]);
    for (let i = 0; i < constants.model_size[1]; i++) {
      for (let j = 0; j < constants.model_size[0]; j++) {
        reshapedArray[i * constants.model_size[0] + j] = image[(i * constants.model_size[0] + j) * 3];
        reshapedArray[(constants.model_size[1] * constants.model_size[0]) + i * constants.model_size[0] + j] = image[(i * constants.model_size[0] + j) * 3 + 1];
        reshapedArray[(2 * constants.model_size[1] * constants.model_size[0]) + i * constants.model_size[0] + j] = image[(i * constants.model_size[0] + j) * 3 + 2];
      }
    }

    return reshapedArray;
}

async function run_model(input) {
    if(!model){
        model = await ort.InferenceSession.create(path.join(__dirname, "model.onnx"), { executionProviders: ['dml'] });
    }
    
    input = new ort.Tensor(input, [1, 3, constants.model_size[1], constants.model_size[0]]);

    const outputs = await model.run({ images: input });
    return outputs["output0"].data;
}

function process_output(output) {
    let boxes = [];
    for (let index = 0; index < 1800; index += 6) {
        const x1 = output[index]/constants.model_size[0];
        const y1 = output[index + 1]/constants.model_size[1];
        const x2 = output[index + 2]/constants.model_size[0];
        const y2 = output[index + 3]/constants.model_size[1];
        const score = output[index + 4];
        const label = constants.labels[output[index + 5]];

        if (score < constants.probabilities[label]) {
            continue;
        }

        boxes.push({x1, y1, x2, y2, class: label, score});
    }

    return boxes;
}

module.exports = { predict };
`

**Comment by pderrenger** [comment]
That's fantastic to hear! Your results are impressive, and it's great to see the significant performance improvements you've achieved. If you encounter any further questions or need additional assistance, feel free to reach out. Keep up the excellent work!
