### ISSUE TITLE
YOLO(model_yaml).load(model.pt) not work.

### ISSUE THREAD

**Issue by wanyne-yyds** [ultralytics/ultralytics#14546]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why, when I use model = YOLO("/home/ultralytics/ultralytics/cfg/models/v8/yolov8s-obb.yaml").load("/home/ultralytics/runs/obb/weights/last.pt") to load weights, can the model not detect objects, but when I initialize the model with model = YOLO("/home/ultralytics/runs/obb/weights/last.pt"), it can detect objects? Why is this the case?

**Comment by wanyne-yyds** [comment]
> @wanyne-yyds thank you for your question. The issue you're encountering likely stems from a mismatch between the model architecture defined in the YAML file and the weights in the `.pt` file. When you load the model directly from the `.pt` file, it includes both the architecture and the weights, ensuring compatibility. However, when you initialize the model from the YAML file and then load the weights, any discrepancies between the architecture defined in the YAML and the saved weights can lead to detection failures.谢谢你的提问。您遇到的问题可能源于 YAML 文件中定义的模型体系结构与 `.pt` 文件中的权重不匹配。当您直接从 `.pt` 文件加载模型时，它包括体系结构和权重，从而确保兼容性。但是，当您从 YAML 文件初始化模型，然后加载权重时，YAML 中定义的体系结构与保存的权重之间的任何差异都可能导致检测失败。
> 
> To resolve this, ensure that the YAML file accurately reflects the architecture of the model used to generate the weights. If the issue persists, please verify that you are using the latest version of the Ultralytics package, as updates often include bug fixes and improvements. If you continue to experience problems, feel free to provide more details, and we can further investigate.要解决此问题，请确保 YAML 文件准确反映用于生成权重的模型的体系结构。如果问题仍然存在，请确认您使用的是最新版本的 Ultralytics 软件包，因为更新通常包括错误修复和改进。如果您仍然遇到问题，请随时提供更多详细信息，我们可以进一步调查。

@pderrenger Thank you for your patient responses. I tried pulling the latest content from the official repository, but I still encounter this issue, which is very confusing to me. Here is how I write my code:
```model = YOLO('/home/ultralytics/ultralytics/cfg/models/v8/yolov8n-obb.yaml').load('/home/ultralytics/runs/obb/MEOBB_FRONT_BACK/weights/best.pt')```

**Comment by wanyne-yyds** [comment]
> @wanyne-yyds thank you for your question. The issue you're encountering likely stems from a mismatch between the model architecture defined in the YAML file and the weights in the `.pt` file. When you load the model directly from the `.pt` file, it includes both the architecture and the weights, ensuring compatibility. However, when you initialize the model from the YAML file and then load the weights, any discrepancies between the architecture defined in the YAML and the saved weights can lead to detection failures.
> 
> To resolve this, ensure that the YAML file accurately reflects the architecture of the model used to generate the weights. If the issue persists, please verify that you are using the latest version of the Ultralytics package, as updates often include bug fixes and improvements. If you continue to experience problems, feel free to provide more details, and we can further investigate.

@pderrenger Thank you for your patient responses. I tried pulling the latest content from the official repository, but I still encounter this issue, which is very confusing to me. Here is how I write my code:
```
        model = YOLO('/home/ultralytics/ultralytics/cfg/models/v8/yolov8n-obb.yaml').load(
            '/home/ultralytics/runs/obb/MEOBB_FRONT_BACK/weights/best.pt')
```

**Comment by Y-T-G** [comment]
Because not all the weights are loaded since the head of the yaml is different due to different `nc`. You have to edi the `nc` in the yaml to match your model's class number and then load like this.

**Comment by wanyne-yyds** [comment]
@Y-T-G Your solution solved my problem perfectly! Thank you very much!
