### ISSUE TITLE
Crops not saving after exporting to onnx and tensorrt format

### ISSUE THREAD

**Issue by Kash6** [ultralytics/ultralytics#1454]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

After exporting to both tensorrt and onnx formats, the .engine and .onnx files seem to have lost the label names as I'm not able to save the crops. I get the error when I switch save_crop=True:
AttributeError: 'tensorrt.tensorrt.ICudaEngine' object has no attribute 'names'   
![image](https://user-images.githubusercontent.com/62140058/225543767-8eb9e65d-7700-489d-8996-c9971aadacc9.png)

**Comment by Laughing-q** [comment]
@Kash6 Thanks for the reporting! We'll fix this soon. :)
@glenn-jocher tested and I can reproduce the issue.
```bash
yolo export model=weights/yolov8n.pt format=engine opset=12 half device='0'
yolo detect predict model=yolov8n.engine half=True save_crop
```
