### ISSUE TITLE
Yolov8 classifier training: impossible to disable some augmentation options

### ISSUE THREAD

**Issue by AlainPilon** [ultralytics/ultralytics#14549]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I run my training with the following: 

```
model.train(data=data_path, epochs=args.epochs, imgsz=640, batch=args.batch, dropout=args.dropout, lr0=args.lr0, hsv_h=0.0, hsv_s=0.0, hsv_v=0.0, degrees=10, translate=0.0, scale=args.scale, erasing=args.erasing, optimizer=args.optimizer)
```

notice the `hsv_h=0.0, hsv_s=0.0, hsv_v=0.0` values are all set to 0.0. Yet, when I look at the training artifact, I see this in the `train_batch0` file:

![image](https://github.com/user-attachments/assets/3d5f1f79-f3ff-46ec-b555-f7cff8a394fb)

How is this possible is all the `hsv` options are disabled? 

As a side question, all my images are rectangular (aspect ratio 2:1) why arent there any black bands on the images?

### Environment

```
ultralytics              8.0.238
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
Pass `auto_augment=None`.

Classification training uses RandomResizedCrop which is square.

**Comment by Y-T-G** [comment]
also `erasing=0`

**Comment by AlainPilon** [comment]
@Y-T-G Thanks! Why the added comment about `erasing=0`? I was currently sweeping values from 0.1 to 0.3.

**Comment by Y-T-G** [comment]
Because I think that augmentation in your image looks like erasing. Not any hue, saturation, brightness change. The erased portion is filled with pixels in a way that the overall RGB mean is unaffected.

**Comment by glenn-jocher** [comment]
I believe this is just a function of disabling all training augmentations. Most likely autoaugment is causing the HSV overflow as @Y-T-G said.
