### ISSUE TITLE
multi input video to YOLOv8 and using bytetrack.yaml  return same ID to different object and keep increasing

### ISSUE THREAD

**Issue by Jeong-m1n** [ultralytics/ultralytics#14543]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to split one captured frame(original) to multiple input video and run multi-thread to get result simultaneously because using only original frame as input miss many objects.
for example, original captured frame is 
![image](https://github.com/user-attachments/assets/691389a4-8c01-494b-b2e7-6434212f588e)
and I split it to 5 small size video by this code

    input_img_list = []     # element is [[x1,y1],[x2,y2], ... , [xn,yn]]
            
    for img_idx, img_ in enumerate(input_img_list):
        #polygon_points = [[2050,1454],[1954,1282],[2212,1160],[2484,1213],[2533,1548]]
        polygon = Polygon(img_)
        x_min , y_min, x_max, y_max = map(int, polygon.bounds)

        width = x_max - x_min
        height = y_max - y_min
        x_center = (x_min + width) /2
        y_center = (y_min + height) /2
        cropped_img = frame[y_min:y_max, x_min:x_max]
        #print(f'----{img_idx}th roi image shape: ', frame.shape)
        #print('++++shape: ', cropped_img.shape)
        model = YOLO('yolov8l.pt')
        results=model.track(source=cropped_img, persist=True, verbose=False, tracker = "bytetrack.yaml")
        results = list(results)
        #print(results[0])
        annotated_frame = results[0].plot()
        cv2.imshow(f"{img_idx} id", merged_img)
         if cv2.waitKey(1)&0xFF==27:
              break

Then I got 5 separate imshow window but here comes the problem.

At first, I used default tracker (Bot tracker) by using `results=model.track(source=frame, persist=True, verbose=False)` but I got error related with lkpyramid  : #https://github.com/ultralytics/ultralytics/issues/1429#issuecomment-1483746453 has same problem with me
![image](https://github.com/user-attachments/assets/299d0c41-49ef-49e6-ba7b-3f229bc123ff)

I don't know How to solve this, so I changed tracker to Bytetrack by `results=model.track(source=cropped_img, persist=True, verbose=False, tracker = "bytetrack.yaml")`. 
By using bytetrack.yaml, above problem doesn't appear but same ID is assigned to different object in seperate window. 
( for example, 80 is assigned to 3 different object in '2id', '3id', '4id' window) 
![image](https://github.com/user-attachments/assets/70c2b6af-2fc9-44d5-a841-10650451f844)

 Even worse, detected object is not moving (traffic light is red light) but ID keeps increasing for same object. For example, at first frame ID starts with 30 and increasing every frame for few seconds and maintained as 80 later)
https://github.com/ultralytics/ultralytics/issues/9197 
I think this issue is similar with my problem but changing parameter in yaml file didn't work for me.

Please help how to fix these issues..
Thanks in advance

**Comment by pderrenger** [comment]
@Jeong-m1n thank you for your detailed explanation. It seems like the issue you're encountering with ByteTrack assigning the same ID to different objects across multiple windows is due to the independent tracking processes not sharing state information. Each instance of the tracker is unaware of the others, leading to ID conflicts.

To address this, you should consider consolidating the tracking into a single process that handles all the cropped images together. This way, the tracker can maintain a consistent state and avoid ID conflicts. Additionally, ensure you are using the latest version of the Ultralytics package to benefit from any recent bug fixes or improvements.

If the problem persists, please provide more details or a minimal reproducible example, and we can investigate further. For more information on tracking configurations, you can refer to the [Ultralytics tracking documentation](https://docs.ultralytics.com/modes/track/).

**Comment by Y-T-G** [comment]
Well, that's expected. `model.train` expects sequence of frames. It won't work when you pass different slices of the same frame. It thinks those frames are one after another, not slices of the same frame. You will have to get all the detections first, merge them into one single set of detections, and then write a custom tracking function to do the tracking.

**Comment by Jeong-m1n** [comment]
@Y-T-G  thanks for you reply. I understand your comment as I am using for loop to split frame and feed it to YOLO and because of this model thinks scene is changing every frame (cropped img 1-2-3-4-5-1-2-3-4-5-,,,), right?

What if I run each model in different thread like [https://docs.ultralytics.com/guides/yolo-thread-safe-inference/#understanding-python-threading](url)?
Then each model will get sequenced image of only one cropped region or still useless?

Of course even if this expedient works I should manage global ID manager to avoid ID conflict in total frame, but maybe It would be much easier than writing custom tracking function..

**Comment by Jeong-m1n** [comment]
@pderrenger Is there any way to access tracker (list or dictionay, set or something) in yolo itself when tracking model is running? Or do I have to post-process IDs from yolo result of input frame?

> To address this, you should consider consolidating the tracking into a single process that handles all the cropped images together

As you mentioned, attaching cropped image to one frame and keep using this as input to yolo would work . I'll try it and update, thanks!

**Comment by pderrenger** [comment]
You can access the tracker state directly within the YOLO model by modifying the tracker configuration or by using custom post-processing. However, consolidating the tracking into a single process that handles all cropped images together is generally more efficient and avoids ID conflicts. If you encounter any issues, please ensure you are using the latest version of the Ultralytics package. Feel free to update us on your progress or if you need further assistance.

**Comment by Y-T-G** [comment]
Running it in a different model won't help. If the car moves from one slice to another, then it will be given new track id. It will only help track it inside the same slice or crop.

**Comment by Jeong-m1n** [comment]
@Y-T-G Oh, I attached example cropped image sliced from one lane of road. But actually I'll crop each area in different lane (to measure traffic count in each lane). So detected object don't move from one slice to another.
In this case, making thread and run it simultaneously will fit my requirement?
 - no ID conflict (need post-processing)
 - handle ID assigned to one object keep increasing problem ( due to for loop, video was getting discontinuous frame video)   

Thank you for your help! It was very helpful :)

**Comment by Y-T-G** [comment]
Then you can just use batch processing.

`model.track([crop_1, crop_2, crop_3])`

You have to make sure the order is always the same. First image should always be from the same slice, second from the same slice and so on. Each slice will be tracked independently.
