### ISSUE TITLE
Support distributed evaluation during training process

### ISSUE THREAD

**Issue by math-yyj** [ultralytics/ultralytics#14540]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Is there any plan to support distributed evaluation during training process?

Look like that only single gpu eval during training. Distributed valuation could make it more efficient.

Many thanks

### Use case

 distributed evaluation during training process to save time 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
Thank you for your suggestion regarding distributed evaluation during the training process. Currently, YOLOv8 supports single-GPU evaluation, but we recognize the potential benefits of distributed evaluation for efficiency. While this feature is not available at the moment, we are continuously working on improving our framework and will consider this for future updates. We appreciate your input and encourage you to stay tuned for upcoming enhancements. If you have any other questions or need further assistance, feel free to ask.
