### ISSUE TITLE
The engine model RTX3060 exported by RTX4070 cannot be inferred

### ISSUE THREAD

**Issue by tonycc521** [ultralytics/ultralytics#14545]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The engine model RTX3060 exported by RTX4070 cannot be inferred，How can I fix it?
![微信图片_20240719153010](https://github.com/user-attachments/assets/23ad77e8-0dba-48e5-9752-b959d0a089b6)

**Comment by pderrenger** [comment]
@sunmooncode it seems like the TensorRT engine model exported on an RTX4070 is not compatible with your RTX3060. TensorRT optimizations can be hardware-specific, and exporting the model on the same GPU architecture as the target device often resolves such issues. Please try exporting the model directly on the RTX3060 and see if that resolves the problem. If the issue persists, ensure you are using the latest versions of the Ultralytics package and TensorRT.

**Comment by Y-T-G** [comment]
TensorRT engine is specific to the GPU it was exported on.
