### ISSUE TITLE
Show the true label

### ISSUE THREAD

**Issue by wanyne-yyds** [ultralytics/ultralytics#14559]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When using OBB detection, some targets do not show a bounding box in the generated **val_batch{i}_labels.jpg** images, although they do exist in reality. After commenting out the following code in the plot_images function, the issue is resolved. Why is this happening?
```
                if len(boxes):
                    # if boxes[:, :4].max() <= 1.1:  # if normalized with tolerance 0.1
                    boxes[..., [0, 2]] *= w  # scale to pixels
                    boxes[..., [1, 3]] *= h
                    # elif scale < 1:  # absolute coords need scale if image scales
                    #     boxes[..., :4] *= scale
```

**Comment by pderrenger** [comment]
@wanyne-yyds thank you for bringing this to our attention. It seems the issue arises from the coordinate scaling logic within the `plot_images` function. The commented-out code is intended to handle different coordinate formats (normalized vs. absolute). When this logic is bypassed, the bounding boxes appear correctly, suggesting a potential mismatch in how the coordinates are being scaled.

To address this, please ensure you are using the latest version of the Ultralytics package, as updates may contain fixes for such issues. If the problem persists, it might be helpful to review the coordinate format of your dataset and ensure consistency with the expected input format for OBB detection.

If you continue to experience issues, please provide additional details or consider opening a new issue with a minimal reproducible example. This will help us investigate further and provide a more targeted solution.
