### ISSUE TITLE
About Detection Speed YOLOV8

### ISSUE THREAD

**Issue by diyaralma** [ultralytics/ultralytics#14561]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

https://github.com/user-attachments/assets/3c3502b8-6c61-469d-8ef5-91a8ec3e07e6

### Additional

My trained model command : 

```
yolo task=detect mode=train model=yolov8s.pt epochs=50 batch=16 amp=False
```

As you can see, the square that follows the fish follows behind the fish when it moves. Because of this, my application does not work as I want. What should I do for a better detection?
I also used cascade classifier as a detection algorithm, currently I am using yolov8, but the result is always the same for about 1 month.
Could it be due to the graphics card or RAM I use?

NOTE: I am using gtx 1650 and ddr4 16gb ram.

**Comment by Y-T-G** [comment]
Are you using tracker?

**Comment by diyaralma** [comment]
> Are you using tracker?


No, I don't use it. I tried to integrate the SAHI tracking algorithm into my project, but I failed


```
results = self.yolo.predict(self.screenshot, verbose=False)
                rectangles = []

                for result in results:
                    for box in result.boxes:
                        x1, y1, x2, y2 = map(int, box.xyxy[0].cpu().numpy())
                        rectangles.append((x1, y1, x2 - x1, y2 - y1))
```

I tried to update this piece of code by including SAHI, but I did not get any results.
It would be great if you could help me with this.

**Comment by Y-T-G** [comment]
Did you export to TensorRT?

**Comment by diyaralma** [comment]
> Did you export to TensorRT?

No.

**Comment by Y-T-G** [comment]
If you have NVIDIA GPU, you can do that. It will be 3-4 times faster.
