### ISSUE TITLE
hydra module

### ISSUE THREAD

**Issue by chiragubnare** [ultralytics/ultralytics#1456]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

ModuleNotFoundError: No module named 'hydra'
![2023-03-16](https://user-images.githubusercontent.com/65922679/225562326-fe80a414-5987-4d1b-b472-672fd5b3b7bf.png)

**Comment by glenn-jocher** [comment]
@chiragubnare your model or your ultralytics package are out of date. Update your package with `pip install -U ultralytics` and train a new model if necessary.

**Comment by chiragubnare** [comment]
@glenn-jocher Thanks for your reply, I will do the required changes as you mentioned.

**Comment by glenn-jocher** [comment]
@chiragubnare absolutely, happy to help! Don't hesitate to reach out if you have any further questions or concerns. Remember to follow the recommended best practices when using YOLOv8, and check out our documentation and community resources for more information. Keep up the great work!
