### ISSUE TITLE
YOLOV8 with SAHI Tracking

### ISSUE THREAD

**Issue by diyaralma** [ultralytics/ultralytics#14573]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am preparing a project in which I perform real-time object detection. I want to include the SAHI object tracking algorithm in my project, but I was unsuccessful in my attempts. I want to transfer the coordinates of the object tracked from SAHI's result value to a rectangles array.

This is my code without SAHI tracking. 
```
results = self.yolo.predict(self.screenshot, verbose=False)
                rectangles = []

                for result in results:
                    for box in result.boxes:
                        x1, y1, x2, y2 = map(int, box.xyxy[0].cpu().numpy())
                        rectangles.append((x1, y1, x2 - x1, y2 - y1))
```
As you can see, I am assigning the coordinates of the detected object to the array called rectangles. I want to do the same operation using SAHI, but I think the 'results' variable I obtained from SAHI contains different values. I can integrate the SAHI tracking algorithm into my project however I want.

**Comment by pderrenger** [comment]
Thank you for your question. To integrate SAHI with YOLOv8 for object tracking, you need to adapt your code to handle the different structure of the results returned by SAHI. The `results` object from SAHI contains a list of `ObjectPrediction` instances, which you can iterate over to extract the bounding box coordinates.

First, ensure you have the latest versions of both `ultralytics` and `sahi` installed. Then, modify your code to process the SAHI results accordingly. You can access the bounding box coordinates from each `ObjectPrediction` and append them to your `rectangles` array.

If you encounter any issues, please verify the reproducibility with the latest package versions. For further details on SAHI integration, you can refer to the [SAHI documentation](https://docs.ultralytics.com/guides/sahi-tiled-inference/).

**Comment by diyaralma** [comment]
> Thank you for your question. To integrate SAHI with YOLOv8 for object tracking, you need to adapt your code to handle the different structure of the results returned by SAHI. The `results` object from SAHI contains a list of `ObjectPrediction` instances, which you can iterate over to extract the bounding box coordinates.
> 
> First, ensure you have the latest versions of both `ultralytics` and `sahi` installed. Then, modify your code to process the SAHI results accordingly. You can access the bounding box coordinates from each `ObjectPrediction` and append them to your `rectangles` array.
> 
> If you encounter any issues, please verify the reproducibility with the latest package versions. For further details on SAHI integration, you can refer to the [SAHI documentation](https://docs.ultralytics.com/guides/sahi-tiled-inference/).

Thank you for your interest and suggestion. I will integrate it into my project as soon as possible as you mentioned.

**Comment by pderrenger** [comment]
@diyaralma you're welcome! If you encounter any issues or need further assistance while integrating SAHI with YOLOv8, feel free to ask. Make sure to check the latest documentation and updates for both `ultralytics` and `sahi` to ensure compatibility. Good luck with your project!
