### ISSUE TITLE
WARNING  TensorBoard not initialized correctly, not logging this run. 'NoneType' object is not callable

### ISSUE THREAD

**Issue by sandelush** [ultralytics/ultralytics#1459]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

WARNING  TensorBoard not initialized correctly, not logging this run. 'NoneType' object is not callable

### Environment

Ultralytics YOLOv8.0.53  Python-3.9.12 torch-2.1.0.dev20230315+cu118 CUDA:0 (NVIDIA GeForce RTX 2060 SUPER, 8192MiB)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sandelush you can `pip install tensorboard` if you'd like to log to TensorBoard.

**Comment by sandelush** [comment]
thx, worked.

**Comment by sandelush** [comment]
@glenn-jocher Thanks for your effort
