### ISSUE TITLE
NMS and Confusion Matrix

### ISSUE THREAD

**Issue by rhalder2023** [ultralytics/ultralytics#14600]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, so during inferencing, yolo predicts 2 classes with different confidence scores, for the same object in the location, can we handle this using an argument in the predict method, or do i need to handle it in post processing seperatly?

Also, i have like 70 classes and hence the plotted confusion matrix post training is very cluttered, is there a way to fix it, or can i get the raw values so that i can plot it seperately, i could fork your repo and try and help in making that better if i could find where the plotting actually takes place
![confusion_matrix](https://github.com/user-attachments/assets/b2b25aae-9547-4463-818a-73e2bd39e7e5)

**Comment by Burhan-Q** [comment]
If you're running validation using the Python interface, you can access the confusion matrix raw values like this:

```py
from ultralytics import YOLO

model = YOLO("yolov8n.pt")
results = model.val(data="coco8.yaml")

results.confusion_matrix.matrix  # returns Numpy array
>>> array([[          4,           0,           0, ...,           0,           0,           0],
           [          0,           0,           0, ...,           0,           0,           0],
           [          0,           0,           0, ...,           0,           0,           0],
           ...,
           [          0,           0,           0, ...,           0,           0,           0],
           [          0,           0,           0, ...,           0,           0,           0],
           [          6,           0,           0, ...,           0,           0,           0]])
```

**Comment by Y-T-G** [comment]
> Hi, so during inferencing, yolo predicts 2 classes with different confidence scores, for the same object in the location, can we handle this using an argument in the predict method, or do i need to handle it in post processing seperatly?

You can use `agnostic=True` to remove overlapping but different classes.

**Comment by rhalder2023** [comment]
> > Hi, so during inferencing, yolo predicts 2 classes with different confidence scores, for the same object in the location, can we handle this using an argument in the predict method, or do i need to handle it in post processing seperatly?
> 
> You can use `agnostic=True` to remove overlapping but different classes.

Thank you, i havent tested it out yet, but im assuming you are right

**Comment by pderrenger** [comment]
You're welcome! If you encounter any issues or need further assistance while testing, feel free to reach out. For your second question, you can access the raw values of the confusion matrix from the validation results and plot them separately to avoid clutter. If you need more details on this, let me know.

**Comment by rhalder2023** [comment]
> If you're running validation using the Python interface, you can access the confusion matrix raw values like this:
> 
> ```python
> from ultralytics import YOLO
> 
> model = YOLO("yolov8n.pt")
> results = model.val(data="coco8.yaml")
> 
> results.confusion_matrix.matrix  # returns Numpy array
> >>> array([[          4,           0,           0, ...,           0,           0,           0],
>            [          0,           0,           0, ...,           0,           0,           0],
>            [          0,           0,           0, ...,           0,           0,           0],
>            ...,
>            [          0,           0,           0, ...,           0,           0,           0],
>            [          0,           0,           0, ...,           0,           0,           0],
>            [          6,           0,           0, ...,           0,           0,           0]])
> ```

Thank You Sir

**Comment by pderrenger** [comment]
You're welcome! If you need further assistance or have more questions, feel free to ask. We're here to help!

**Comment by rhalder2023** [comment]
> > > Hi, so during inferencing, yolo predicts 2 classes with different confidence scores, for the same object in the location, can we handle this using an argument in the predict method, or do i need to handle it in post processing seperatly?
> > 
> > 
> > You can use `agnostic=True` to remove overlapping but different classes.
> 
> Thank you, i havent tested it out yet, but im assuming you are right

the argument's called agnostic_nms now. but other than that it worked.

**Comment by pderrenger** [comment]
@rhalder2023 thank you for the update. Yes, the correct argument is `agnostic_nms=True`. I'm glad to hear it worked for you. If you have any more questions or need further assistance, feel free to ask.
