### ISSUE TITLE
Trying to make a package using YOLO but can not load up the .pt model

### ISSUE THREAD

**Issue by zshar7** [ultralytics/ultralytics#14604]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

So I am currently working on my research project and wanted to package some of my code for streamlined use throughout my project. However, while packaging my code, part of my code needs to load my .pt model and use it for inferencing. This is the following code:

```python
from importlib import resources
import io
from ultralytics import YOLO

# Some code in between

with resources.open_binary('ct_to_catheter_stl', 'best.pt') as fp:
      pt = fp.read()
model = YOLO(str(io.BytesIO(pt)))
files = request(str(Path.cwd())+'/'+folder+'/'+'*.'+format, format)

# Some code in between 

result = model(IMAGE_FILE, verbose=False)
```

Now I want to include my best.pt file in my package but YOLO accepts only strings for the path to load up a model. What should I do?

**Comment by Burhan-Q** [comment]
@zshar7 you should probably just use a string. Not sure what you mean by "package" your code or how it would "streamline" anything. This sounds like an [XY problem](https://xyproblem.info/) and I highly recommend learning what that means, and then you can try re-asking your problem (if needed, but honestly you should just use a string). As of now, the information you've provided is too vague to offer any type of support.
