### ISSUE TITLE
How to extract multiple XYZ data for multiple object detection using YOLO V8 OBB  

### ISSUE THREAD

**Issue by KennethEladistu** [ultralytics/ultralytics#14612]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Currently I trained my data set on "parcel" images. My model is currently detecting parcel using my AI depth camera. Currently even if it detects 2 parcel it can only extract 1 XYZ data on only 1 parcel. How can i make it so that everytime it detects parcel/parcels regardless of how many, it can extract the XYZ of all those parcels. Thank you

this is my code `import cv2
import depthai as dai
from submodule.calc import HostSpatialsCalc
from submodule.utility import *
import numpy as np
import math
from ultralytics import YOLO  # Assuming you have YOLOv8 with OBB support

# Load a pretrained YOLOv8 OBB model (ensure it's trained for OBB)
model = YOLO("C:/Users/KennethAaronEladistu/oak_d/oak_d/best(3).pt")  # Replace with your model path

# Create pipeline
pipeline = dai.Pipeline()

# Define source and output (RGB camera)
camRgb = pipeline.create(dai.node.ColorCamera)
xoutRgb = pipeline.create(dai.node.XLinkOut)
xoutRgb.setStreamName("rgb")

# Properties
camRgb.setPreviewSize(640, 640)
camRgb.setResolution(dai.ColorCameraProperties.SensorResolution.THE_1080_P)
camRgb.setInterleaved(False)
camRgb.setColorOrder(dai.ColorCameraProperties.ColorOrder.RGB)

# Linking (RGB camera)
camRgb.preview.link(xoutRgb.input)

# Define sources and outputs (Stereo Depth)
monoLeft = pipeline.create(dai.node.MonoCamera)
monoRight = pipeline.create(dai.node.MonoCamera)
stereo = pipeline.create(dai.node.StereoDepth)

# Properties (Stereo Depth)
monoLeft.setResolution(dai.MonoCameraProperties.SensorResolution.THE_400_P)
monoLeft.setBoardSocket(dai.CameraBoardSocket.LEFT)
monoRight.setResolution(dai.MonoCameraProperties.SensorResolution.THE_400_P)
monoRight.setBoardSocket(dai.CameraBoardSocket.RIGHT)

stereo.initialConfig.setConfidenceThreshold(255)
stereo.setDefaultProfilePreset(dai.node.StereoDepth.PresetMode.HIGH_DENSITY)
stereo.setDepthAlign(camera=dai.CameraBoardSocket.CAM_A)
stereo.setLeftRightCheck(True)
stereo.setOutputSize(monoLeft.getResolutionWidth(), monoLeft.getResolutionHeight())
stereo.setSubpixel(False)
stereo.setExtendedDisparity(True)

# Linking (Stereo Depth)
monoLeft.out.link(stereo.left)
monoRight.out.link(stereo.right)

xoutDepth = pipeline.create(dai.node.XLinkOut)
xoutDepth.setStreamName("depth")
stereo.depth.link(xoutDepth.input)

xoutDepth = pipeline.create(dai.node.XLinkOut)
xoutDepth.setStreamName("disp")
stereo.disparity.link(xoutDepth.input)

# Connect to device and start pipeline
with dai.Device(pipeline) as device:
    depthQueue = device.getOutputQueue(name="depth", maxSize=10, blocking=False)
    dispQ = device.getOutputQueue(name="disp", maxSize=10, blocking=False)
    qRgb = device.getOutputQueue(name="rgb", maxSize=4, blocking=False)

    text = TextHelper()
    rgbtext = TextHelper()
    hostSpatials = HostSpatialsCalc(device)
    delta = 5

    hostSpatials.setDeltaRoi(delta)

    print("Use 'r' and 'f' to change ROI size.")

    while True:
        inRgb = qRgb.get()  # Blocking call for new RGB frame
        depthData = depthQueue.get()
        frame = inRgb.getCvFrame()
      
        results = model.predict(source=frame, classes=[1])  # Filter to only detect class 1 (parcels)

        try:
            for result in results:
                if hasattr(result, 'obb'):
                    xmin = int(result.obb.xyxy[0][0])
                    ymin = int(result.obb.xyxy[0][1])
                    xmax = int(result.obb.xyxy[0][2])
                    ymax = int(result.obb.xyxy[0][3])
                    rgbtext.rectangle(frame, (xmin, ymin), (xmax, ymax))
                    print(f"OBB Coordinates: {xmin}, {ymin}, {xmax}, {ymax}")

                    # Calculate spatial coordinates
                    center_x = (xmin + xmax) // 2
                    center_y = (ymin + ymax) // 2
                    spatials, centroid = hostSpatials.calc_spatials(depthData, (center_x, center_y))
                    text.putText(frame, f"X: {spatials['x']:.1f}mm", (xmin, ymin - 20))
                    text.putText(frame, f"Y: {spatials['y']:.1f}mm", (xmin, ymin - 10))
                    text.putText(frame, f"Z: {spatials['z']:.1f}mm", (xmin, ymin))
            
        # except Exception as e:
        #     print(f"Error: {e}")

        except:
            print("No Objects Detected")

        # # Get disparity frame for nicer depth visualization
        # disp = dispQ.get().getFrame()
        # disp = (disp * (255 / stereo.initialConfig.getMaxDisparity())).astype(np.uint8)
        # disp = cv2.applyColorMap(disp, cv2.COLORMAP_JET)

        # text.putText(disp, f"X: {spatials['x']:.1f}mm", (center_x + 10, center_y + 20))
        # text.putText(disp, f"Y: {spatials['y']:.1f}mm", (center_x + 10, center_y + 35))
        # text.putText(disp, f"Z: {spatials['z']:.1f}mm", (center_x + 10, center_y + 50))

        # Show the frame
        # cv2.imshow("depth", disp)
        cv2.imshow("rgb", frame)
        
        key = cv2.waitKey(1)
        if key == ord('q'):
            break

        elif key == ord('r'):  # Increase Delta
            if delta < 50:
                delta += 1
                hostSpatials.setDeltaRoi(delta)

        elif key == ord('f'):  # Decrease Delta
            if 3 < delta:
                delta -= 1
                hostSpatials.setDeltaRoi(delta)`

**Comment by Y-T-G** [comment]
You're just indexing one box `xyxy[0`. You're supposed to loop through all the obbb boxes:

``
for result in results:
            if hasattr(result, 'obb'):
                xmin = int(result.obb.xyxy[0][0])
                ymin = int(result.obb.xyxy[0][1])
                xmax = int(result.obb.xyxy[0][2])
                ymax = int(result.obb.xyxy[0][3])
                rgbtext.rectangle(frame, (xmin, ymin), (xmax, ymax))
                print(f"OBB Coordinates: {xmin}, {ymin}, {xmax}, {ymax}")
```

**Comment by KennethEladistu** [comment]
> You're just indexing one box `xyxy[0]`. You're supposed to loop through all the obbb boxes:
> 
> ```
> for result in results:
>             if hasattr(result, 'obb'):
>                 xmin = int(result.obb.xyxy[0][0])
>                 ymin = int(result.obb.xyxy[0][1])
>                 xmax = int(result.obb.xyxy[0][2])
>                 ymax = int(result.obb.xyxy[0][3])
>                 rgbtext.rectangle(frame, (xmin, ymin), (xmax, ymax))
>                 print(f"OBB Coordinates: {xmin}, {ymin}, {xmax}, {ymax}")
> ```

do you have a sample for this? do I just remove my "try catch" code?

**Comment by Y-T-G** [comment]
You loop through each result in `result.obb.xyxy`
