### ISSUE TITLE
Request for Assistance in Predicting Future Positions of Moving Objects with YOLO

### ISSUE THREAD

**Issue by fusang1337** [ultralytics/ultralytics#14615]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

**Objective:** 
Thank you for your support and assistance！I am currently using YOLO for object tracking in a video stream. I would like to extend its functionality to predict the positions of moving objects approximately 3 seconds into the future.Before this, I have researched possible methods, including using Kalman filtering for predicting motion trajectories. I noticed that YOLO's tracking algorithm also incorporates enhanced Kalman filtering. Therefore, I would like to consult the YOLO development and maintenance team and express gratitude for the team's efforts.
**Current Implementation:**
```
import cv2

from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO(r"weights\best.pt")

# Open the video file
video_path = "25Min_1X_2M_1080P_15FPS.mp4"
cap = cv2.VideoCapture(video_path)

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 tracking on the frame, persisting tracks between frames
        results = model.track(frame, persist=True)

        # Visualize the results on the frame
        annotated_frame = results[0].plot()
        annotated_frame = cv2.resize(annotated_frame,(int(1920/2),int(1080/2)))

        # Display the annotated frame
        cv2.imshow("YOLOv8 Tracking", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()
```

**Request:**
I am seeking guidance or a demo on how to predict the future positions of tracked objects approximately 3 seconds ahead using the YOLO framework. Any insights, methodologies, or sample code demonstrating this predictive capability would be greatly appreciated.

**Comment by pderrenger** [comment]
@fusang1337 thank you for your detailed query and for sharing your current implementation. Predicting future positions of moving objects is indeed a complex task that typically involves motion prediction algorithms such as Kalman filters or more advanced techniques like deep learning-based trajectory prediction.

Given that YOLO's tracking algorithm already incorporates Kalman filtering, you are on the right track. To predict future positions, you can extend the Kalman filter to project the object's state into the future. This involves using the filter's prediction step multiple times to estimate the object's position at future time steps.

While YOLO itself does not provide built-in functionality for future position prediction, you can integrate a Kalman filter or another predictive model into your tracking loop. You would need to extract the current state (position and velocity) of each tracked object and then use the Kalman filter to predict its future state.

For detailed guidance on implementing this, I recommend looking into resources on Kalman filters and motion prediction. If you encounter specific issues or need further assistance with integrating these methods into your YOLO-based tracking system, feel free to ask.

For more information on YOLO's tracking capabilities, you can refer to the [Ultralytics documentation](https://docs.ultralytics.com/modes/predict/).

**Comment by fusang1337** [comment]
> @fusang1337 thank you for your detailed query and for sharing your current implementation. Predicting future positions of moving objects is indeed a complex task that typically involves motion prediction algorithms such as Kalman filters or more advanced techniques like deep learning-based trajectory prediction.
> 
> Given that YOLO's tracking algorithm already incorporates Kalman filtering, you are on the right track. To predict future positions, you can extend the Kalman filter to project the object's state into the future. This involves using the filter's prediction step multiple times to estimate the object's position at future time steps.
> 
> While YOLO itself does not provide built-in functionality for future position prediction, you can integrate a Kalman filter or another predictive model into your tracking loop. You would need to extract the current state (position and velocity) of each tracked object and then use the Kalman filter to predict its future state.
> 
> For detailed guidance on implementing this, I recommend looking into resources on Kalman filters and motion prediction. If you encounter specific issues or need further assistance with integrating these methods into your YOLO-based tracking system, feel free to ask.
> 
> For more information on YOLO's tracking capabilities, you can refer to the [Ultralytics documentation](https://docs.ultralytics.com/modes/predict/).

Thank you for your reply,When I attempted to independently call the target tracking in YOLO:
```
from ultralytics import YOLO
from ultralytics.trackers.bot_sort import BOTSORT
import cv2
import numpy as np

model = YOLO(r'weights\best.pt')

class Args:
    def __init__(self):
        self.with_reid = False
        self.cmc_method = 'none'
        self.gmc_method = 'none'
        self.name = 'none'
        self.ablation = 'none'
        self.mot20 = 'none'
        self.proximity_thresh = 0.6
        self.appearance_thresh = 0.25
        self.match_thresh = 0.8
        self.track_buffer = 30
        self.track_high_thresh = 0.7
        self.track_low_thresh = 0.2
        self.new_track_thresh = 0.7

args = Args()
tracker = BOTSORT(args, frame_rate=30)

cap = cv2.VideoCapture(r'25Min_1X_2M_1080P_15FPS.mp4')
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = int(cap.get(cv2.CAP_PROP_FPS))
out = cv2.VideoWriter('output_video.mp4', cv2.VideoWriter_fourcc(*'XVID'), fps, (width, height))

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    results = model(frame)

    dets = []
    for result in results:
        for box in result.boxes:
            x1, y1, x2, y2 = box.xyxy[0]
            score = box.conf
            dets.append([x1.item(), y1.item(), x2.item(), y2.item(), score.item()])

    dets = np.array(dets)

    online_targets = tracker.update(results[0].boxes.cpu())
    pass

    for target in online_targets:
        # tlwh = target.tlwh
        # tid = target.track_id
        # x1, y1, w, h = target[:4]
        # x2, y2 = x1 + w, y1 + h
        x1, y1, x2, y2 = target[:4]
        cv2.rectangle(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0, 0, 255), 2)
        cv2.putText(frame, str(target[7]), (int(x1), int(y1) - 10), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
        cv2.imshow('img',frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    # Write the frame to the video file
    out.write(frame)

cap.release()
out.release()
cv2.destroyAllWindows()
```
`online_targets = tracker.update(results[0].boxes.cpu())`
The variable `online_targets` stores the results of the target tracking from `tracker.update(results[0].boxes.cpu())`Through debugging, I found the values to be:
`[[     459.43           0      1388.1      541.92           1     0.97274           4           0], [     1014.9      177.72        1200      320.19           2     0.89824           7           5], [     802.92      119.57       975.9      241.65           3     0.87844           7           6], [-5.1346e-05      571.81      280.38      1079.4          15     0.95343           0           2], [     79.931      564.25      362.15      849.72          16     0.92567           5           4], [      141.7      548.97      1845.2      1079.9          17     0.96165           0           1], [     1678.5      555.66      1919.8      1049.9          18     0.94386           2           3]]`
What do each of the columns in `online_targets` represent? It seems the first seven are `x1, y1, x2, y2, track_id, conf, cls` What does the last one represent?

**Comment by pderrenger** [comment]
@fusang1337 thank you for sharing your detailed implementation and observations. The `online_targets` array returned by the `tracker.update()` method indeed contains multiple columns representing different attributes of the tracked objects. Based on your description, the columns are as follows:

1. `x1`: Top-left x-coordinate of the bounding box.
2. `y1`: Top-left y-coordinate of the bounding box.
3. `x2`: Bottom-right x-coordinate of the bounding box.
4. `y2`: Bottom-right y-coordinate of the bounding box.
5. `track_id`: Unique identifier for the tracked object.
6. `conf`: Confidence score of the detection.
7. `cls`: Class label of the detected object.
8. `frame_id`: Frame identifier indicating the frame number in which the object was detected.

The last column, `frame_id`, is used to keep track of the frame number in which the object was detected, which can be useful for analyzing the movement of objects over time.

If you need further assistance with integrating future position prediction or have additional questions, feel free to ask. For more detailed information on tracking and prediction, you can refer to the [Ultralytics documentation](https://docs.ultralytics.com/modes/track/).

**Comment by matheusvvb-19** [comment]
Hello, @fusang1337.
Were you able to predict the future positions of moving objects? I'm facing a similar (or even the same) issue.
