### ISSUE TITLE
Facing error while training yolov8 with pre trained = False

### ISSUE THREAD

**Issue by Aniketiitk21** [ultralytics/ultralytics#14617]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I wanted to train the yolov8n model for the object detection task. I used the following code snippet for this purpose and got the error 
![image](https://github.com/user-attachments/assets/a63f258a-2d8e-4b6c-85f1-36a87063b327)

Please tell me how to solve this issue. I tried to search for it but could not find the same problem. But I trust you people will answer it asap. Thanking in advance!!

**Comment by Y-T-G** [comment]
That's an argument for `train()`

**Comment by ambitious-octopus** [comment]
Hey @Aniketiitk21, as @Y-T-G as suggested, `pretrained` is an argument for the `train` method. The correct code is as follows:

```python
from ultralytics import YOLO

model = YOLO('yolov8n.yaml')
model.train(data='YOUR-YAML, epochs=220, imgsz=640, pretrained=False)
```

Please refer to the [official documentation](https://docs.ultralytics.com/modes/train/).

@Aniketiitk21 Where did you find the snippet you used? Somewhere in the documentation?

**Comment by pderrenger** [comment]
@Aniketiitk21 thank you for the clarification. To resolve the issue, ensure you use the `pretrained` argument within the `train` method, not during model initialization. If you encounter further issues, please verify that you're using the latest version of the Ultralytics package. If the problem persists, feel free to provide additional details.
