### ISSUE TITLE
Segmentation Fault on Running Yolo Model using coral edgetpu

### ISSUE THREAD

**Issue by ARusDian** [ultralytics/ultralytics#14618]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

the console says 

```
python3 stream_predict.py 
Loading yolov8n_integer_quant_edgetpu.tflite for TensorFlow Lite Edge TPU inference...
Segmentation fault
```

### Environment

Ultralytics YOLOv8.2.63 ð Python-3.11.2 torch-2.3.1 CPU (Cortex-A72)
Setup complete â (4 CPUs, 7.6 GB RAM, 20.8/58.0 GB disk)

OS                  Linux-6.6.31+rpt-rpi-v8-aarch64-with-glibc2.36
Environment         Linux
Python              3.11.2
Install             pip
RAM                 7.63 GB
CPU                 Cortex-A72
CUDA                None

numpy               â 1.24.2<2.0.0,>=1.23.0
matplotlib          â 3.9.1>=3.3.0
opencv-python       â 4.10.0.84>=4.6.0
pillow              â 10.4.0>=7.1.2
pyyaml              â 6.0.1>=5.3.1
requests            â 2.28.1>=2.23.0
scipy               â 1.14.0>=1.4.1
torch               â 2.3.1>=1.8.0
torchvision         â 0.18.1>=0.9.0
tqdm                â 4.66.4>=4.64.0
psutil              â 5.9.4
py-cpuinfo          â 9.0.0
pandas              â 2.2.2>=1.1.4
seaborn             â 0.13.2>=0.11.0
ultralytics-thop    â 2.0.0>=2.0.0

### Minimal Reproducible Example

```

from ultralytics import YOLO


# Load the exported TFLite Edge TPU model
edgetpu_model = YOLO("yolov8n_integer_quant_edgetpu.tflite", task="detect")

# Run inference
results = edgetpu_model("https://ultralytics.com/images/bus.jpg")

```

### Additional

I've convert from yolov8 to edgetpu tflite and compile it using this gcollab link : [https://colab.research.google.com/github/google-coral/tutorials/blob/master/compile_for_edgetpu.ipynb](url).  and it says it's good 
![image](https://github.com/user-attachments/assets/90e5e771-481b-4a10-9890-bb000d94c700)

also i'm able to run example code from the https://coral.ai/docs/accelerator/get-started/#3-run-a-model-on-the-edge-tpu so i think it's not libedgetpu issue :/
![image](https://github.com/user-attachments/assets/a84dc733-7cd7-4e9a-97d7-16caa8507203)
![image](https://github.com/user-attachments/assets/3c17224b-020c-4934-a8fa-8a87bc0cffe8)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@ARusDian thank you for providing detailed information. The segmentation fault you're encountering could be due to compatibility issues between the TensorFlow Lite runtime and the Coral Edge TPU runtime. Please ensure you are using the latest versions of both. Additionally, verify that you have uninstalled any previous versions of TensorFlow and installed `tflite-runtime` as recommended. If the issue persists, try running the model on a different non-ARM platform to rule out hardware-specific issues. For further guidance, please refer to our detailed guide at https://docs.ultralytics.com/guides/coral-edge-tpu-on-raspberry-pi/.

**Comment by ARusDian** [comment]
Fix this issue by install legacy RPI4 OS so the default python ver is 3.9.2

**Comment by glenn-jocher** [comment]
@ARusDian thank you for your report. Please ensure you are using the latest version of the `ultralytics` package and the appropriate `tflite-runtime` version. If the issue persists, consider using a legacy Raspberry Pi OS with Python 3.9.2 as a workaround. For more details, visit our [Coral Edge TPU guide](https://docs.ultralytics.com/guides/coral-edge-tpu-on-raspberry-pi/).
