### ISSUE TITLE
the detection box is that passable to output over 640 height value ?

### ISSUE THREAD

**Issue by einsitang** [ultralytics/ultralytics#14610]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

hello,

I just use yolov8 model export tensorflow savedmodel , and run on kaggle , but I found that during the prediction process, it was predicted that the box would exceed 640 height (I not change the imgsz to train model)

<img width="665" alt="image" src="https://github.com/user-attachments/assets/7334fbf8-4f93-4fbb-8ece-e6b13b8088b1">

kaggle : https://www.kaggle.com/code/jianbintangelement/tensorflow-with-yolov8/

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@einsitang yes this is normal, raw YOLO model outputs may exceed image size. PyTorch postprocessing will clip these to image size as a natural prior, but for other export formats you may need to mature your postprocess pipeline yourself with these capabilities provided you are not running TF inference with the ultralytics package but instead with some other custom prediction workflow.

**Comment by einsitang** [comment]
thank you

**Comment by pderrenger** [comment]
@einsitang you're welcome! To address the issue of detection boxes exceeding the image size, this behavior can occur with raw YOLO model outputs. In PyTorch, post-processing typically clips these boxes to the image size. If you're using TensorFlow or another framework, ensure your post-processing pipeline includes this clipping step. Please also verify if the issue persists with the latest version of the Ultralytics package. If you need further assistance, feel free to ask!
