### ISSUE TITLE
Unexpected keyword argument ERROR using YOLO-NAS

### ISSUE THREAD

**Issue by matteocacioppo** [ultralytics/ultralytics#14620]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Hi, I'm trying to use YOLO-NAS exactly as specified here: https://docs.ultralytics.com/models/yolo-nas/#inference-and-validation-examples but I get the error: 

CustomizableDetector.forward() got an unexpected keyword argument 'augment'.

I've seen on github that someone else was having the same problem but a solution was not given; I've also seen on discord that someone was having similar issues with 'unexpected keyword argument' but not the same class and function as me. As far as you know, is there a known solution of this problem?

I've found that the class CustomizableDetector is within the super-gradients library and I had to install, using pip, super-gradients separately from ultralytics, I don't know if this can be the problem.

I've also tried to use super-gradients==3.1.2 as suggested in another issue regarding YOLOv8 but it doesn't work.

### Environment

Ultralytics YOLOv8.2.63 🚀 Python-3.10.12 torch-2.3.1+cu121 CPU (Intel Xeon 2.20GHz)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@matteocacioppo thank you for bringing this to our attention. The error you're encountering with the `CustomizableDetector.forward()` method is likely due to an incompatibility between the versions of the Ultralytics and Super-Gradients libraries. 

Please ensure you are using the latest versions of both libraries. You can update them using:
```
pip install --upgrade ultralytics super-gradients
```

If the issue persists after updating, it might be due to a recent change in the Super-Gradients library. In that case, please try downgrading to a version known to work well with Ultralytics YOLOv8, such as `super-gradients==3.1.2`.

Feel free to report back if the problem continues, and we can further investigate. Thank you for your patience and understanding.

**Comment by matteocacioppo** [comment]
@pderrenger Hi, I've tried both options but none of them worked, I have tried various versions of super-gradients but this also did not work, the error I get is always the same.

**Comment by glenn-jocher** [comment]
@Laughing-q I can reproduce this, can you look into this?

Autodownload was missing and I've added this in https://github.com/ultralytics/ultralytics/pull/14627 for NAS models now, but the OP's original error remains.

**Comment by glenn-jocher** [comment]
Screenshot from colab

<img width="924" alt="Screenshot 2024-07-23 at 16 16 16" src="https://github.com/user-attachments/assets/7b60cc16-3565-4fad-9d45-16a6c3f6ee1b">

**Comment by Laughing-q** [comment]
@glenn-jocher I'm on it

**Comment by Laughing-q** [comment]
@glenn-jocher @matteocacioppo I opened a PR to fix the issue, however this is not fully working
- Even within the PR, creating model with the pt files by `model=NAS('yolo_nas_s.pt')` won't work with the latest `super_gradients` because of some updates the super_gradients team made. showing following error from the `super_gradients` package:
```bash
  File "/home/laughing/codes/ultralytics/ultralytics/nn/autobackend.py", line 457, in forward
    self.model(im)
  File "/home/laughing/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laughing/codes/super-gradients/src/super_gradients/training/models/detection_models/customizable_detector.py", line 93, in forward
    x = self.backbone(x)
        ^^^^^^^^^^^^^^^^
  File "/home/laughing/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laughing/codes/super-gradients/src/super_gradients/modules/detection_modules.py", line 85, in forward
    for layer in self._all_layers:
                 ^^^^^^^^^^^^^^^^
  File "/home/laughing/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'NStageBackbone' object has no attribute '_all_layers'. Did you mean: 'out_layers'?
```
- Creating model with the pre-trained files from super_gradients by `model=NAS('yolo_nas_s')` won't work as well because the we are using `torch.inference_mode` for inference and the mode seems to needs `torch.no_grad()`, see this issue from pytorch: https://github.com/pytorch/pytorch/issues/90882. However I think rolling back to `torch.no_grad()` is not the update we want so I left the PR for now.

**Comment by Laughing-q** [comment]
@matteocacioppo Anyway if you want to make the NAS models running correctly at current stage, you need to switch the `nas` branch and manually replace the `torch.inference_mode` her https://github.com/ultralytics/ultralytics/blob/82956dc77b78b898559077eaf0d5311f749f9605/ultralytics/utils/torch_utils.py#L66
to `torch.no_grad`
and using `model=NAS('yolo_nas_s')` to create model.

**Comment by matteocacioppo** [comment]
@Laughing-q Just for information, even following the steps you have written in your last comment I still get the exact same error.

**Comment by glenn-jocher** [comment]
@matteocacioppo @Laughing-q Great news 😃! Your original issue may now be resolved ✅ in PR #14630. 

<img width="1123" alt="Screenshot 2024-07-23 at 21 40 38" src="https://github.com/user-attachments/assets/8c708566-7085-484a-aade-693b17bd8018">

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by glenn-jocher** [comment]
@matteocacioppo in any case I would stay away from the NAS models. YOLOv8 is better: faster, simpler, more accurate and more deployable.

**Comment by matteocacioppo** [comment]
Thank you for your help, in my colab I'm still facing the same problem although I have followed the latest instructions, but I am probably doing something wrong. However now I'm using the Yolov8 notebook and everything works fine so I will keep working with Yolov8.

**Comment by pderrenger** [comment]
Thank you for the update. I'm glad to hear that YOLOv8 is working well for you. If you encounter any further issues or have additional questions, feel free to reach out. Happy coding!
