### ISSUE TITLE
wrong location project yolov8

### ISSUE THREAD

**Issue by kyoko9000** [ultralytics/ultralytics#14629]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

my project is 81:
![image](https://github.com/user-attachments/assets/5a882a72-0898-4074-8997-eccee73073bf)

but it save to project 75:
![image](https://github.com/user-attachments/assets/b04e3c1c-c378-4c3b-a343-769e29df5d1e)

it auto download data and save to outside old project:
![image](https://github.com/user-attachments/assets/afc91b3a-851a-4b25-af28-093ba874a013)

i have to use project='OBB' to save it to current project:
![image](https://github.com/user-attachments/assets/4173b407-f964-461e-9144-8a38578768ff)

so how can i reset to make it auto download data and save result to current project
i use window 11
pycharm last version
yolov8 ver 8.2.63
python 3.10.11

**Comment by glenn-jocher** [comment]
@kyoko9000 dataset directories are defined in your YOLO settings. Run `yolo settings` for more info and see https://docs.ultralytics.com/quickstart/#ultralytics-settings

**Comment by pderrenger** [comment]
@kyoko9000 i'm glad to hear it's working now! For the issue with the auto-downloaded data being saved outside your project directory, please ensure your YOLO settings are correctly configured. You can adjust the dataset path in your settings to ensure it downloads to the desired location. If the issue persists, try updating to the latest version of YOLOv8 to see if it resolves the problem. Thank you for your patience!
