### ISSUE TITLE
Please allow to modify worker number during resuming an interrupted training

### ISSUE THREAD

**Issue by Helicopt** [ultralytics/ultralytics#1462]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Please allow to modify worker number during resuming an interrupted training

why the worker number is recorded in ckpt? it's weird.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Helicopt changing settings in between runs is not recommended. The idea behind resuming is that the exact same settings are applied to resume the run seamlessly. Any change in settings might lead to a change in behavior.
