### ISSUE TITLE
Question about mAP when training from scratch of RT-DETR

### ISSUE THREAD

**Issue by Rbrq03** [ultralytics/ultralytics#14631]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey there, congrats to the great work.
Have you ever tried to train any version of RT-DETR from scratch? Will it drop some mAP comparing with paper report? I will be appreciate if you can share any train log.

**Comment by pderrenger** [comment]
@Rbrq03 thank you for your kind words and interest in RT-DETR. Training RT-DETR from scratch can indeed result in variations in mAP compared to the reported values in the paper. These differences can be attributed to various factors such as training settings, dataset variations, and hardware configurations. While we don't have specific training logs to share, we recommend ensuring that you are using the latest version of the Ultralytics package and following the recommended training procedures closely. If you encounter any specific issues or discrepancies, please feel free to share more details, and we can assist you further.
