### ISSUE TITLE
How to call the detected object as image in yolo v8?

### ISSUE THREAD

**Issue by HarshkumarDegamadiya** [ultralytics/ultralytics#1465]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am using yolo v8 custom trained model for Passport Field detection purpose. Now i am facing the problem that i dont know to call the detected object for OCR purpose.

### Additional

My main reason for this is to build a model which can detect Fields in Passports and read it through OCR

**Comment by pderrenger** [comment]
@HarshkumarDegamadiya to call the detected object as an image in YOLOv8 for OCR purposes, you can use the "Predict" mode to make predictions using a trained YOLOv8 model on new images. This will provide you with the bounding boxes around the detected objects, which you can then extract from the original image. Once you have the bounding boxes, you can crop the original image using these coordinates to obtain the individual objects as separate images. These extracted images can then be used for OCR to read the content of the detected fields in passports.

Additionally, to achieve your goal of building a model that can detect and read fields in passports through OCR, you may want to consider using the YOLOv8 model to detect the fields and then pass the extracted images to an OCR engine for text recognition.

Feel free to let us know if you need further assistance with implementing this approach!
