### ISSUE TITLE
getting error using YOLOv10n.onnx with OpenCV DNN

### ISSUE THREAD

**Issue by 0xSynapse** [ultralytics/ultralytics#14657]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

``` bash
[ERROR:0@395.786] global onnx_importer.cpp:1035 handleNode DNN[/ONNX](http://localhost:8888/ONNX): ERROR during processing node with 2 inputs and 2 outputs: [TopK]:(onnx_node![/model.23/TopK](http://localhost:8888/model.23/TopK)) from domain='ai.onnx'
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
Cell In[17], line 3
      1 # Load the network.
      2 model = "yolov10n.onnx"
----> 3 net = cv2.dnn.readNetFromONNX(model)
      5 # Process image.
      6 detections = preprocess(frame, net)

error: OpenCV(4.10.0) [/io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1057](http://localhost:8888/io/opencv/modules/dnn/src/onnx/onnx_importer.cpp#line=1056): error: (-2:Unspecified error) in function 'handleNode'
> Node [TopK@ai.onnx]:(onnx_node![/model.23/TopK](http://localhost:8888/model.23/TopK)) parse error: OpenCV(4.10.0) [/io/opencv/modules/dnn/src/net_impl.hpp:108](http://localhost:8888/io/opencv/modules/dnn/src/net_impl.hpp#line=107): error: (-2:Unspecified error) Can't create layer "onnx_node![/model.23/TopK](http://localhost:8888/model.23/TopK)" of type "TopK" in function 'getLayerInstance'
>
```

### Environment

Ultralytics YOLOv8.2.64 🚀 Python-3.10.0 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3070 Ti Laptop GPU, 7974MiB)
Setup complete ✅ (16 CPUs, 15.3 GB RAM, 222.2/596.0 GB disk)

### Minimal Reproducible Example

code colab link - https://colab.research.google.com/drive/1hWaYbufFrsDPwjAUh406eQitt1klfOCo?usp=sharing

### Additional

I am trying to do object detection with opencv dnn module. I have the latest opencv-python = 4.10.0; it's working fine with yolov8 and v9, but the problem occurs with v10. 

Can anyone have any idea, please help!

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@0xSynapse thank you for reporting this issue. The error you're encountering with the `TopK` layer in YOLOv10n.onnx appears to be related to compatibility between the ONNX model and the OpenCV DNN module. YOLOv10 introduces new operations that may not yet be fully supported by OpenCV's ONNX importer.

To address this, please ensure you are using the latest versions of both the Ultralytics package and OpenCV. If the issue persists, consider using an alternative inference framework such as ONNX Runtime or TensorRT, which may offer better support for the new operations in YOLOv10.

If you continue to experience issues, please let us know, and we can further investigate. Thank you for your understanding and willingness to contribute!

**Comment by knoppmyth** [comment]
@0xSynapse This isn't an issue w/ Ultralytics but a limit of OpenCV. This should be resolved with OpenCV 5.0. I ran into this bug myself and ended up just using Onnxruntime. Using Onnxruntime also gave me a boost in inference speed versus OpenCV. This was with YOLOv6/8.

**Comment by 0xSynapse** [comment]
@pderrenger @knoppmyth, thanks for the help!

Yeah,  it's an OpenCV Dnn issue, we are working on that.

**Comment by pderrenger** [comment]
Thank you for the insights, @0xSynapse and @knoppmyth. Indeed, this is a limitation with OpenCV's current support for certain ONNX operations. We recommend using ONNX Runtime for now, as it provides better compatibility and performance. Please ensure you're using the latest versions of all packages to avoid any other potential issues. If you have further questions, feel free to ask here.
