### ISSUE TITLE
Pose Keypoints Visibility score

### ISSUE THREAD

**Issue by priyamw** [ultralytics/ultralytics#14665]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey, Yolo pose gives visibility score between [0,1] and in COCO format or even when I need to train the Yolo I have to give validity score 0 1 or 2. Is there any relation between these? What I mean to ask can I assign 
0 to 0.5 as 0
0.5 to 0.7 as 1
0.7 to 1 as 2( do not mind these exact values just want to ask if there is any such relation or can be made) 
I need to to train the YOLO pose model from the it's results adding few extra keypoints which I will annotate.

**Comment by Y-T-G** [comment]
The model will try to learn the score, so it should have some reason for the score, otherwise the model might have trouble learning.
