### ISSUE TITLE
How to Apply Agnostic NMS for Validation while Obtaining Class-Specific Metrics?

### ISSUE THREAD

**Issue by Guan9Wu** [ultralytics/ultralytics#14666]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

After training and evaluating, I observed that one target has multiple bounding boxes with different categories. To address this, I used the prediction parameter `agnostic_nms=True` to eliminate the duplicates.

However, I found that NMS is also applied during the validation phase before calculating the metrics, which raises concerns about the impact of overlapping bounding boxes on the model's accuracy. If I set the training parameter `single_cls=True`, it enables agnostic NMS during validation, but this results in the inability to obtain metrics for each class, as it combines them into a single class. This is not my intended outcome.

I want to apply agnostic NMS to mitigate the effects of overlapping targets while still being able to retrieve metrics for each individual class. What would be the best approach to achieve this?

Thank you!

**Comment by pderrenger** [comment]
@Guan9Wu to apply agnostic NMS during validation while still obtaining class-specific metrics, you can modify the validation script to include agnostic NMS without setting `single_cls=True`. This way, you can eliminate overlapping bounding boxes across different classes and still retain class-specific metrics. 

Ensure you are using the latest version of the Ultralytics package, as updates often include fixes and new features that might address your issue. If the problem persists, consider customizing the validation process by directly modifying the source code to apply agnostic NMS before calculating the metrics.

If you need further assistance, feel free to ask here.

**Comment by Laughing-q** [comment]
@Guan9Wu Hi, I've submitted a PR to allow `agnostic_nms` for validation so you could train your model on your data with `single_cls=False` and `agnostic_nms=True` to get class-specific metrics from agnostic nms. https://github.com/ultralytics/ultralytics/pull/14675
Note the PR has not merged to main yet so please use `val-nms` branch if you want to test it out now. :)

**Comment by glenn-jocher** [comment]
Great news 😃! Your original issue may now be resolved ✅ in PR #14675 by @Laughing-q. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!
