### ISSUE TITLE
Error when trying to train yolov8 model

### ISSUE THREAD

**Issue by vrathi101** [ultralytics/ultralytics#14664]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I followed the Ultralytics documentation online for using YoloV8 for training an object detection model but keep experiencing the following issue. This is the code I ran:

os.chdir('/kaggle/working')
!pip uninstall -y ultralytics
!pip cache purge
!pip install -U ultralytics
from ultralytics import YOLO
model = YOLO("yolov8s.pt")
results = model.train(
    data="/kaggle/working/data.yaml", epochs=20,
    imgsz=640, batch=-1, save=True
)

I previously installed ultralytics so here I just uninstalled and reinstalled it. the model loads properly but whenever I try training it I get the following error:

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[27], line 1
----> 1 results = model.train(
      2     data="/kaggle/working/data.yaml", epochs=20,
      3     imgsz=640, batch=-1, save=True
      4 )

File /opt/conda/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py:189, in YOLO.train(self, **kwargs)
    186 if overrides.get("resume"):
    187     overrides["resume"] = self.ckpt_path
--> 189 self.trainer = self.TrainerClass(overrides=overrides)
    190 if not overrides.get("resume"):  # manually set model only if not resuming
    191     self.trainer.model = self.trainer.get_model(weights=self.model if self.ckpt else None, cfg=self.model.yaml)

File /opt/conda/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py:86, in __init__(self, config, overrides)

File /opt/conda/lib/python3.10/site-packages/ultralytics/yolo/configs/__init__.py:25, in get_config(config, overrides)

File /opt/conda/lib/python3.10/site-packages/omegaconf/omegaconf.py:189, in OmegaConf.load(file_)
    186 from ._utils import get_yaml_loader
    188 if isinstance(file_, (str, pathlib.Path)):
--> 189     with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
    190         obj = yaml.load(f, Loader=get_yaml_loader())
    191 elif getattr(file_, "read", None):

FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/configs/default.yaml'

**Comment by Y-T-G** [comment]
Just restart the notebook kernel

**Comment by vrathi101** [comment]
I tried that but now am getting this error:
`AttributeError: module 'torch.amp' has no attribute 'GradScaler'`

**Comment by pderrenger** [comment]
@vrathi101 it looks like you're encountering an issue with the `GradScaler` attribute. This error typically arises from an incompatible or outdated version of PyTorch. Please ensure you have PyTorch 1.8 or later installed. You can update PyTorch using the following command:

```bash
pip install torch --upgrade
```

After updating, restart your kernel and try running your training script again. If the issue persists, please let us know.

**Comment by vrathi101** [comment]
yes that worked, thank you!

**Comment by pderrenger** [comment]
@vrathi101 glad to hear that it worked! If you encounter any further issues or have additional questions, feel free to reach out. We're here to help.

**Comment by Laughing-q** [comment]
@vrathi101 closing the issue as it's resolved, please feel free to reopen it if you encounter any related issues. :)
