### ISSUE TITLE
yolov8 stops detecting occasionally

### ISSUE THREAD

**Issue by lonnylundsten** [ultralytics/ultralytics#14667]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

When running detections with tracking on many videos we have drop-outs in detections, essentially the model occasionally stops making any detections or will only detect one object for some period of time. This would happen with the old yolov5 code base as well, although now we're using the ultralytics package. This happens probably 2-3 times per 15 minute file and we have run 500+ files through yolo/ultralytics. Any ideas about what causes this? I've attached a low-res video so you can understand what I mean, but I can provide high-res video if you need to see more clearly. You'll see right away all but one detection stop a just a few frames before 2s.

https://github.com/user-attachments/assets/578056e6-6337-46cd-9262-11ff9abcfa0f

### Environment

Ultralytics YOLOv8.2.53 🚀 Python-3.10.12 torch-2.3.0+cu121 CUDA:0 (NVIDIA A100-SXM4-40GB, 40514MiB)
Setup complete ✅ (12 CPUs, 83.5 GB RAM, 30.2/201.2 GB disk)

### Minimal Reproducible Example

# Track with the model
!yolo task=detect mode=track model="/content/drive/MyDrive/weights_configs/models/mbari_452k_yolov8.pt" half='True' save='True' save_txt='False' tracker="botsort.yaml" agnostic_nms='True' max_det=2000 augment='True' save_conf='False' imgsz=1280 device='0' conf=0.02 iou=.40 line_width=2 source='/content/drive/MyDrive/temp_files/V4430_20220908T162336Z_prores_trimmed.mov'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@lonnylundsten thank you for providing detailed information about the issue. It appears that the detection drop-outs you're experiencing might be related to the tracking algorithm or specific settings used during inference. Here are a few steps you can take to troubleshoot and potentially resolve the issue:

1. Ensure you are using the latest version of the Ultralytics package and YOLOv8 model. Updates often include bug fixes and performance improvements.
2. Try running the model without the `augment` argument to see if the issue persists, as augmentation during inference can sometimes cause inconsistencies.
3. Verify that the `tracker` configuration is optimal for your use case. You might experiment with different trackers or adjust the settings in `botsort.yaml`.
4. Check if the issue occurs with different confidence (`conf`) and IoU (`iou`) thresholds to see if adjusting these parameters improves detection consistency.

If the problem continues, please provide additional details or a high-resolution video for further analysis. This will help us better understand the context and provide more specific guidance.

**Comment by Burhan-Q** [comment]
The confidence values for most (possibly all) of the "dropped" detections are $<0.09$ with some as low as $0.01$ which means the confidence threshold is set quite low for these to show up at all.

**Comment by lonnylundsten** [comment]
@Burhan-Q That's correct, confidence threshold was set at 0.02. I updated the code above to reflect that. This is another peculiarity with utrlaytics vs. yolov5, I now have to set conf very low to get about the same results. 

@pderrenger I changed augment to 'False' and that did improve detections. Its not perfect yet, but certainly better.

**Comment by lonnylundsten** [comment]
Here is a new example with augmentation = False and conf = 0.01. We still get dropped detections. I have also tried with tracking off and got similar, dropped detections.

Here's the updated command:
`!yolo task=detect mode=track model="/content/drive/MyDrive/weights_configs/models/mbari_452k_yolov8.pt" half='False' save='True' save_txt='False' tracker="botsort.yaml" agnostic_nms='True' max_det=2000 augment='False' save_conf='False' imgsz=1280 device='0' conf=0.01 iou=.40 line_width=2`

https://github.com/user-attachments/assets/d9b19ad7-4565-4f7a-94bb-160c7ed978e6

**Comment by Y-T-G** [comment]
Does it always stop at the same point in the video?

**Comment by lonnylundsten** [comment]
Yes.

**Comment by pderrenger** [comment]
@lonnylundsten thank you for confirming. To further investigate, please ensure you're using the latest version of the Ultralytics package and YOLOv8 model. If the issue persists, try adjusting the `conf` and `iou` thresholds incrementally to see if it improves detection consistency. Additionally, you might want to experiment with different tracker configurations or even disable tracking to isolate the problem. If you continue to experience issues, providing more details or a high-resolution video could help us diagnose the problem more effectively.

**Comment by Burhan-Q** [comment]
@lonnylundsten have you modified any parameter(s) in `botsort.yaml`? If so, could you please post the contents of your `botsort.yaml`?

Given your system specs `12 CPUs, 83.5 GB RAM` I think we can rule out memory but wondering if there's anything on the CPU that could be causing this...Maybe it starts to throttle and that could lead to the issue occurring at the same time. Have you tried setting a `conf` value lower than $0.02$? Maybe try something like `conf=1e-3`? It might not be useful for your application, but it could help to understand the cause better.

@Laughing-q any ideas why the detections would drop at the same time in every run?

**Comment by lonnylundsten** [comment]
Note that the original video file is 00:15:14 (15m, 14s) long. I first noticed this issue with the full length clip. Then I trimmed the clip so it's just 28s long and the drop in detections occurs at the same point in the video even though the elapsed time is different. So I don't believe it has anything to do with the length of the file, size of the file, available GPU memory, etc. 

I have used no tracking, changed tracking parameters, used the default tracking parameters, I have changed the image size, conf threshold, etc. and none of these change the fact that the detections drop out at that point.

**Comment by lonnylundsten** [comment]
Is it possible that when the box size of a single detection becomes large enough, it suppresses all other detections? This is a pattern that I have started to notice. I've often noticed that once a somewhat large detection leaves the frame, all of a sudden we get many more detections of other objects. Notice that at 33s in this video, when the _Eptatretus_ (hagfish) observation becomes small again, all the other detections come back.

**Comment by Y-T-G** [comment]
Can you try passing only the classes that get dropped at that point using the `classes` argument?

I mean don't include the class of that one object that doesn't get dropped.

**Comment by lonnylundsten** [comment]
Yep. That worked.

**Comment by lonnylundsten** [comment]
Here's the example, with the class label for that larger detection excluded.
https://github.com/user-attachments/assets/4aa9aea9-8938-494c-8cb7-6ebbf85bbe1f

**Comment by lonnylundsten** [comment]
If the box size is the source of the problem, is that a threshold that can be changed?

**Comment by Y-T-G** [comment]
It seems more like the confidence is getting softmaxxed.

How did you train the model? Do you have the code?

**Comment by lonnylundsten** [comment]
I've attached the args.yaml. Does that give you the info you want? I can open the notebook and get the actual command in just a bit, if needed.
[args.txt](https://github.com/user-attachments/files/16382371/args.txt)

**Comment by Y-T-G** [comment]
Is this a custom architecture?

**Comment by lonnylundsten** [comment]
No. I just used the standard yolo training.

**Comment by pderrenger** [comment]
Thank you for providing the training command and data YAML file. Given that you used the standard YOLO training setup, it might be beneficial to check if the issue persists with the latest version of the Ultralytics package. Sometimes, updates include bug fixes and improvements that can resolve such issues.

If the problem continues, you might want to experiment with adjusting the Non-Maximum Suppression (NMS) settings or the confidence threshold to see if it helps mitigate the suppression of other detections when a large box is present. Additionally, reviewing the training data for any anomalies or imbalances could also provide insights.

If you have further questions or need additional assistance, feel free to ask!

**Comment by lonnylundsten** [comment]
I've checked to be certain that the ultralytics package is up-to-date:

Ultralytics YOLOv8.2.65 🚀 Python-3.10.12 torch-2.3.1+cu121 CUDA:0 (NVIDIA A100-SXM4-40GB, 40514MiB)
Setup complete ✅ (12 CPUs, 83.5 GB RAM, 30.1/201.2 GB disk)

**Comment by Y-T-G** [comment]
> No. I just used the standard yolo training.
> 
> This is the command I used for training: `yolo task=detect cache=True mode=train data="mbari_450k_yolov8.yaml" model="runs/detect/train27/weights/last.pt" epochs=60 batch=16 device=0,1,2,3,4,5,6,7 imgsz=1280 resume=True`
> 
> The data yaml is attached.
> 
> [mbari_450k_yolov8.yaml.txt](https://github.com/user-attachments/files/16382715/mbari_450k_yolov8.yaml.txt)

What model was it originally? Like which variant?

**Comment by lonnylundsten** [comment]
I used yolov8x.pt for the initial training.

**Comment by pderrenger** [comment]
Thank you for confirming that you used `yolov8x.pt` for the initial training. Given that you're experiencing intermittent detection dropouts, it might be beneficial to experiment with adjusting the Non-Maximum Suppression (NMS) settings or the confidence threshold. Additionally, ensure your training data is balanced and accurately annotated. If the issue persists, please verify reproducibility with the latest Ultralytics package version.

**Comment by Y-T-G** [comment]
> I used yolov8x.pt for the initial training.

Do you have the results image from the runs directory and also the validation batch preds plots?

**Comment by lonnylundsten** [comment]
![PR_curve](https://github.com/user-attachments/assets/83a157a1-7ba8-419d-b16e-00b15787b238)
![R_curve](https://github.com/user-attachments/assets/548f407c-3d6c-43b7-b051-fea03277fdea)
![confusion_matrix_normalized](https://github.com/user-attachments/assets/63bb12af-5728-4128-bb11-b3a0add012d3)
![confusion_matrix](https://github.com/user-attachments/assets/ef5e6da1-f4ef-4e4c-aae4-5334cde1f2fd)
![F1_curve](https://github.com/user-attachments/assets/873e2a88-f9f0-4ccf-b106-be2e187fc8fc)
![labels_correlogram](https://github.com/user-attachments/assets/7885cf6a-1ba7-463b-a3fa-7cb54e4dccda)
![labels](https://github.com/user-attachments/assets/5f97fc40-532b-4102-b370-f759e0870318)
![P_curve](https://github.com/user-attachments/assets/dd7a841a-f13a-405d-8e7e-2f81416d4e07)

**Comment by lonnylundsten** [comment]
![results](https://github.com/user-attachments/assets/9d98fd27-5733-438f-a8c6-1d3cf137102e)

**Comment by Y-T-G** [comment]
What about the validation plots? The plots with predictions on images from validation set.

I want to see if the confidences are low for them too.

**Comment by lonnylundsten** [comment]
Here is the contents of the runs directory, excluding the model. [metadata.zip](https://github.com/user-attachments/files/16395053/metadata.zip)

**Comment by pderrenger** [comment]
Thank you for providing the metadata. To address the detection dropouts, please ensure you are using the latest version of the Ultralytics package. If the issue persists, consider adjusting the Non-Maximum Suppression (NMS) settings and confidence thresholds. Additionally, reviewing the training data for any anomalies or imbalances might help. If you need further assistance, feel free to ask.

**Comment by Y-T-G** [comment]
I think the problem is there are too many detections (each object being detected as multiple classes) to the point that it hits the NMS limit:
https://github.com/ultralytics/ultralytics/blob/673e76b86282859ead5517bd04dee896a647db93/ultralytics/utils/ops.py#L173

which triggers a cutoff based on confidence:
https://github.com/ultralytics/ultralytics/blob/673e76b86282859ead5517bd04dee896a647db93/ultralytics/utils/ops.py#L280-281

You can try increasing the max_nms. Otherwise, the only solution is a better model.

**Comment by lonnylundsten** [comment]
OK. I'll give that a shot and retrain in yolov10 if that doesn't work. Thank you!

**Comment by lonnylundsten** [comment]
Adjusting max_nms did not solve the problem. I'll plan on retraining in yolov10.

**Comment by pderrenger** [comment]
Thank you for the update. If adjusting `max_nms` didn't resolve the issue, retraining with YOLOv10 could indeed be a beneficial next step. YOLOv10's architecture improvements might help mitigate the detection dropouts you're experiencing. Please ensure you're using the latest version of the Ultralytics package during your retraining process. If the issue persists, feel free to share any additional observations or results.

**Comment by lauravchrobak** [comment]
> @lonnylundsten have you modified any parameter(s) in `botsort.yaml`? If so, could you please post the contents of your `botsort.yaml`?
> 
> Given your system specs `12 CPUs, 83.5 GB RAM` I think we can rule out memory but wondering if there's anything on the CPU that could be causing this...Maybe it starts to throttle and that could lead to the issue occurring at the same time. Have you tried setting a `conf` value lower than 0.02? Maybe try something like `conf=1e-3`? It might not be useful for your application, but it could help to understand the cause better.
> 
> @Laughing-q any ideas why the detections would drop at the same time in every run?

If you look at the top video the detections drop out sooner (~4 s and in the second one they drop out at 8s) just to clarify- this would rule out anything in particular about the scene at a specific time for example.

**Comment by Y-T-G** [comment]
To debug this, it would be nice if you could provide the saved `output.pkl` file:

```python
import pickle
import cv2
from ultralytics import YOLO

# Load your own model. This is an example.
model = YOLO("yolov8n.pt")
# Run it at least once to create the predictor.
model(save=False, show=False)

# Load the problematic frame
frame = cv2.imread("frame_with_drop.jpg")
preprocessed = model.predictor.preprocess([frame])
output = model.predictor.inference(preprocessed)
with open("output.pkl", "wb") as f: pickle.dump([output, preprocessed, frame], f)
results = model.predictor.postprocess(output, preprocessed, [frame])

# Display the frame to verify it actually dropped the detections
cv2.imshow("frame", result.plot())
```

The frame should be the exact frame where the drop occurs. You can try capturing that frame [using VLC](https://digitalmediacookbook.com/capture-a-still-frame-from-a-video-using-vlc/) from the original video.

**Comment by lonnylundsten** [comment]
@Y-T-G I'm on vacation this week, but will get back on this early next week.

**Comment by lonnylundsten** [comment]
When I change the mode from track to predict on the frame that the detections 'drop out' the model detects the other objects in the frame.

![V4430_20220908T162336Z_trimmed_0537_predict](https://github.com/user-attachments/assets/1289cce3-4b24-410d-9089-6a33cb39d6dd)
![V4430_20220908T162336Z_trimmed_0537_track](https://github.com/user-attachments/assets/c3627466-2f89-4eeb-acc8-88cf26c71139)

**Comment by lauravchrobak** [comment]
@lonnylundsten I think it would be worth running with agnostic_nms=False. I imagine that the reason that this is happening is that when a proposal with a high score comes in, like the eel, the class agnostic nms is removing all of these non overlapping low confidence detections.

**Comment by Y-T-G** [comment]
Tracking has a minimum threshold that needs to be reached before they are considered valid.

https://github.com/ultralytics/ultralytics/blob/8648572809fa2e58967862f9a4748abddd0f60a7/ultralytics/cfg/trackers/botsort.yaml#L7

**Comment by lonnylundsten** [comment]
```
# Track with the model
!yolo task=detect mode=track model="/content/drive/MyDrive/weights_configs/models/mbari_452k_yolov8.pt" save='True' save_txt='False' agnostic_nms='False' max_det=5000 augment='False' save_conf='False' imgsz=1280 device='0' conf=1e-3 iou=0.4 line_width=2 source='/content/drive/MyDrive/temp_files/V4430_20220908T162336Z_trimmed/V4430_20220908T162336Z_trimmed_0537.jpg'
```
![V4430_20220908T162336Z_trimmed_0537](https://github.com/user-attachments/assets/38a6f706-d318-457d-9df9-1dd0290fa3be)

**Comment by lonnylundsten** [comment]
```
# predict with the model
!yolo task=detect mode=predict model="/content/drive/MyDrive/weights_configs/models/mbari_452k_yolov8.pt" save='True' save_txt='False' agnostic_nms='False' max_det=5000 augment='False' save_conf='False' imgsz=1280 device='0' conf=1e-3 iou=0.4 line_width=2 source='/content/drive/MyDrive/temp_files/V4430_20220908T162336Z_trimmed/V4430_20220908T162336Z_trimmed_0537.jpg'
```
![V4430_20220908T162336Z_trimmed_0537](https://github.com/user-attachments/assets/10300062-a869-4664-8418-6277fe977522)

**Comment by lonnylundsten** [comment]
@lauravchrobak @Y-T-G Both of the above images have agnostic_nms=False. One parameter is changed between the two runs, mode=predict vs mode=track. This is the frame where the gap in detections begins.

**Comment by Y-T-G** [comment]
It's normal behavior. Tracking's default minimum threshold is 0.6. So anything below that will be discarded. Only one object in your frame is above that.

But I thought you already tested the videos without tracking and it showed similar drop in detection before.

> I have also tried with tracking off and got similar, dropped detections.

**Comment by lonnylundsten** [comment]
@Y-T-G Yes, I did. That's correct.

**Comment by Y-T-G** [comment]
Without tracking as in setting `mode=predict` on the videos right?

**Comment by lonnylundsten** [comment]
@Y-T-G I don't think I did change the mode to predict when running the video through. I'll try that.

Also, I tried running the following code:

```
import pickle
import cv2
from ultralytics import YOLO

# Load your own model. This is an example.
model = YOLO("/Users/lonny/Desktop/recent_ml_work/models/mbari_452k_yolov8.pt")
# Run it at least once to create the predictor.
model(save=False, show=False, conf=0.01) # Add other parameters that you use

# Load the problematic frame
frame = cv2.imread("/Users/lonny/Desktop/V4430_20220908T162336Z_trimmed/V4430_20220908T162336Z_trimmed_0537.jpg")
preprocessed = model.predictor.preprocess([frame])
output = model.predictor.inference(preprocessed)
with open("/Users/lonny/Desktop/output.pkl", "wb") as f: pickle.dump([output, preprocessed, frame], f)
results = model.predictor.postprocess(output, preprocessed, [frame])

# Display the frame to verify it actually dropped the detections
cv2.imshow("frame", results[0].plot())
```

and got the following warning:
```
WARNING ⚠️ 'source' is missing. Using 'source=/Users/lonny/.pyenv/versions/3.12.4/lib/python3.12/site-packages/ultralytics/assets'.

image 1/2 /Users/lonny/.pyenv/versions/3.12.4/lib/python3.12/site-packages/ultralytics/assets/bus.jpg: 1280x960 1 Actiniaria, 3 Chionoecetes tanneris, 1 Gastropoda, 2 equipments, 1005.5ms
image 2/2 /Users/lonny/.pyenv/versions/3.12.4/lib/python3.12/site-packages/ultralytics/assets/zidane.jpg: 736x1280 1 Doryteuthis (Amerigo) opalescens, 2 Gonatuss, 1 Histioteuthis heteropsis, 2 equipments, 719.7ms
Speed: 3.5ms preprocess, 862.6ms inference, 1.5ms postprocess per image at shape (1, 3, 736, 1280)
```

Did I run that correctly?

**Comment by Y-T-G** [comment]
Okay, I think that's the issue. I thought you had run without tracking, as in set `mode=predict`. If you have `mode=track`, it's still using tracking. And due to that your detections get dropped when there's an object with confidence over 0.6 in the frame since that's the default minimum confidence.

Although, it should be dropping all of them and the code probably needs to be updated to drop all detections when nothing gets tracked to avoid this scenario:
https://github.com/ultralytics/ultralytics/blob/8648572809fa2e58967862f9a4748abddd0f60a7/ultralytics/trackers/track.py#L71-L72 @glenn-jocher

**Comment by lonnylundsten** [comment]
@Y-T-G I ran the updated code in 14831, but that changed it so only the Eptatretus was detected and no other classes were detected throughout the entire video. However, when I change the track.py code so that len(det) and len(tracks) !=0 then the code works as expected, no dropped ml proposals.

`for i in range(len(im0s)):
        tracker = predictor.trackers[i if is_stream else 0]
        vid_path = predictor.save_dir / Path(path[i]).name
        if not persist and predictor.vid_path[i if is_stream else 0] != vid_path:
            tracker.reset()
            predictor.vid_path[i if is_stream else 0] = vid_path

        det = (predictor.results[i].obb if is_obb else predictor.results[i].boxes).cpu().numpy()
        if len(det) != 0:
            continue
        tracks = tracker.update(det, im0s[i])
        if len(tracks) != 0:
            continue
        idx = tracks[:, -1].astype(int)
        predictor.results[i] = predictor.results[i][idx]

        update_args = {"obb" if is_obb else "boxes": torch.as_tensor(tracks[:, :-1])}
        predictor.results[i].update(**update_args)`

**Comment by lonnylundsten** [comment]
Here's the example with the track.py changed as above:
https://github.com/user-attachments/assets/502b422c-0706-4a0b-9c46-e68f9a864827

**Comment by lonnylundsten** [comment]
Here's the example with the track.py changed as above:

Uploading V4430_20220908T162336Z_trimmed_modified_track.py.mov…

**Comment by lonnylundsten** [comment]
https://github.com/user-attachments/assets/4bf0598c-8484-438f-b229-b49acad7ce54

**Comment by Y-T-G** [comment]
That's how it should be. If you want to track the low confidence detections, you will have to lower your `new_track_threshold` to a value that's below the confidence value of most of your detections. Like `0.001`

https://github.com/ultralytics/ultralytics/blob/8648572809fa2e58967862f9a4748abddd0f60a7/ultralytics/cfg/trackers/botsort.yaml#L7

**Comment by Y-T-G** [comment]
If you're not using tracking (making use of the assigned unique track ids to each object), then there's no need to use `mode=track`. Up until this point, most of your objects weren't being tracked anyway due to their confidence value being below the `new_track_thresh`.

**Comment by lonnylundsten** [comment]
@Y-T-G I tested your suggestion with your updated track code and changing the new_track_thresh in the botsort.yaml. That did not work. 

Changing the  track.py code so that len(det) and len(tracks) !=0 works as expected.

**Comment by Y-T-G** [comment]
> Changing the track.py code so that len(det) and len(tracks) !=0 works as expected.

That works because it breaks tracking, essentially making it same as `mode=predict`.

Did you pass the edited botsort.yaml using the `tracker=botsort.yaml` argument?

**Comment by lonnylundsten** [comment]
I did, but that again gave me only the one class (Eptatretus) detected.

**Comment by Y-T-G** [comment]
And when does it appear? When the confidence goes over 0.6?

**Comment by lonnylundsten** [comment]
Back to the original track.py code. Changed the botsort.yaml so that new_track_thresh: 0.001. Detections are better, but still doing that single class for ~90s.

**Comment by Y-T-G** [comment]
Create a new yaml file with a different filename and copy the tracker parameters from the updated `botsort.yaml` and pass that new file in the `tracker` argument.

**Comment by Y-T-G** [comment]
Also try reducing `track_low_thresh` to 0.001

**Comment by Laughing-q** [comment]
@lonnylundsten @Y-T-G Hey guys! That's how the trackers work, objects dropped because their confidence scores are too low to pass the tracker. And yes I would recommend to lower the `track_low_thresh` and `new_track_thresh` if you want to make it work with lower scores objects. :) 
BTW I wanted to respond the issue last week but I don't know why at that time I couldn't play the video @lonnylundsten posted. The video is ok to me now so I get to what's happening here. :)

**Comment by lonnylundsten** [comment]
@Y-T-G @Laughing-q It just dawned on me -- maybe you noticed this earlier -- for the most part tracking is not working on this video. Tracking does work occasionally on the single species of hagfish (Eptatretus) identified. And when tracking works for that one class, detections drop for all others. 

Questions that I have are, 1) why does tracking work so poorly for those other classes in this video and 2) why do the detections stop when one object is tracked?

I have tried to alter the parameters in the botsort.yaml but I can't get tracking to improve for any of the other classes in this video. Do you have any suggestions to improve tracking for this video over all the classes?

**Comment by Laughing-q** [comment]
> why does tracking work so poorly for those other classes in this video

because the confidence scores are too low.

> why do the detections stop when one object is tracked?

because once there's object being tracked successfully, it'd update all the ordinary predictions to the updated tracks, and since there's only one object being tracked hence only one tracked object left.

**Comment by lonnylundsten** [comment]
@Laughing-q OK. Thanks for the info. When I set the hyperparameters in the botsort.yaml really low (like 0.001), shouldn't that induce tracking for other classes? It seems like it would but that's not what's happening.

**Comment by Laughing-q** [comment]
@lonnylundsten ah interesting, maybe you could send me a minimal video and your model to reproduce if you don't mind. :) laughingq@163.com

**Comment by lonnylundsten** [comment]
@Laughing-q OK. I sent you an email with ftp urls that provide you with our yolov8 model and the short video clip that I’ve been using for testing purposes. Thanks for looking into this for us.

**Comment by Laughing-q** [comment]
@lonnylundsten Hey, I reproduced the issue even lower all the tracker-related threshold arguments and found it's related to the `fuse_score` function which fuses the low confidence scores you got with the calculated iou distance so no matches and no tracks. 
I've submitted a PR to add a new argument `fuse_score` to determine whether to fuse scores.
In you case, to track the objects currently you could use the `tracker` branch for now(before merging) and the following `custom_botsort.yaml`:
```yaml
# Ultralytics YOLO 🚀, AGPL-3.0 license
# Default YOLO tracker settings for BoT-SORT tracker https://github.com/NirAharon/BoT-SORT

tracker_type: botsort # tracker type, ['botsort', 'bytetrack']
track_high_thresh: 0.01 # threshold for the first association
track_low_thresh: 0.01 # threshold for the second association
new_track_thresh: 0.01 # threshold for init new track if the detection does not match any tracks
track_buffer: 30 # buffer to calculate the time when to remove tracks
match_thresh: 0.8 # threshold for matching tracks
fuse_score: False  # Whether to fuse confidence scores with the iou distances before matching
# min_box_area: 10  # threshold for min box areas(for tracker evaluation, not used for now)

# BoT-SORT settings
gmc_method: sparseOptFlow # method of global motion compensation
# ReID model related thresh (not supported yet)
proximity_thresh: 0.5
appearance_thresh: 0.25
with_reid: False
```

**Comment by lonnylundsten** [comment]
@Laughing-q Awesome! Thanks for working so hard to figure this out. I really appreciate it. I'll test this out shortly!

**Comment by lonnylundsten** [comment]
@Laughing-q @glenn-jocher That fixed it. We now have good tracking. Great work! Thanks again for looking into this.
https://github.com/user-attachments/assets/e08cf5d6-0cca-4df8-addd-ae0d40ca8a52

**Comment by glenn-jocher** [comment]
Glad to hear that the fix worked and you're now getting good tracking results! If you encounter any further issues or have additional questions, feel free to reach out. Thank you for your patience and for providing the necessary details to resolve this.

**Comment by glenn-jocher** [comment]
Great, thanks for confirming the update. If the issue persists, consider adjusting the Non-Maximum Suppression (NMS) settings or confidence thresholds to see if that helps. If you need further assistance, feel free to ask!

**Comment by glenn-jocher** [comment]
Thank you for confirming the update. If the issue persists, consider adjusting the Non-Maximum Suppression (NMS) settings or reviewing your training data for any imbalances. Let me know if you need further assistance!

**Comment by glenn-jocher** [comment]
Thank you for confirming the update. If the issue persists, consider adjusting the Non-Maximum Suppression (NMS) settings or the confidence threshold to see if it improves detection consistency. If you need further assistance, feel free to ask!

**Comment by glenn-jocher** [comment]
Thank you for confirming your setup. If the issue persists, consider experimenting with the Non-Maximum Suppression (NMS) settings or adjusting the confidence threshold to see if it improves detection consistency. If you have further questions, feel free to ask!
