### ISSUE TITLE
AttributeError: Can't get attribute 'v10DetectLoss' on module 'ultralytics.utils.loss' from 'path_to_ultralytics/utils/loss.py'

### ISSUE THREAD

**Issue by mrortach** [ultralytics/ultralytics#14676]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I am encountering an issue while trying to run a script with YOLOv10 using UltraLytics. The error traceback is as follows:

The script fails with an AttributeError related to v10DetectLoss in ultralytics.utils.loss.

I have tried multiple versions of torch and torchvision to resolve this issue, but it persists. Any guidance or suggestions to fix this issue would be greatly appreciated.

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS D:\***\***_tespit\yolov10\***_modelx> & C:/ProgramData/anaconda3/python.exe d:/***/***_tespit/yolov10/***_modelx/yolov10x_tek_camera.py
Traceback (most recent call last):
  File "d:\***\***_tespit\yolov10\***_modelx\yolov10x_tek_camera.py", line 4, in <module>
    model = YOLO("yolov10x.pt")
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***\AppData\Roaming\Python\Python312\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Users\***\AppData\Roaming\Python\Python312\site-packages\ultralytics\engine\model.py", line 141, in __init__
    self._load(model, task=task)
  File "C:\Users\***\AppData\Roaming\Python\Python312\site-packages\ultralytics\engine\model.py", line 293, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***\AppData\Roaming\Python\Python312\site-packages\ultralytics\nn\tasks.py", line 855, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***\AppData\Roaming\Python\Python312\site-packages\ultralytics\nn\tasks.py", line 781, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***\AppData\Roaming\Python\Python312\site-packages\ultralytics\utils\patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***\AppData\Roaming\Python\Python312\site-packages\torch\serialization.py", line 1026, in load
    return _load(opened_zipfile,
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***\AppData\Roaming\Python\Python312\site-packages\torch\serialization.py", line 1438, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "C:\Users\***\AppData\Roaming\Python\Python312\site-packages\torch\serialization.py", line 1431, in find_class
    return super().find_class(mod_name, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'v10DetectLoss' on <module 'ultralytics.utils.loss' from 'C:\\Users\\***\\AppData\\Roaming\\Python\\Python312\\site-packages\\ultralytics\\utils\\loss.py'>

### Environment
Windows 11 Visual Studi Code

### Minimal Reproducible Example

```Python
from ultralytics import YOLO

# Load a pre-trained YOLOv10x model
model = YOLO("yolov10x.pt")

# Perform object detection on an image or video (0 for webcam)
results = model.track(0, save=True, show=True, conf=0.2)

# Display the results
results[0].show()

**Comment by Y-T-G** [comment]
Seems like you're using the ultralytics from YOLOv10 repo, not the official one.

**Comment by Y-T-G** [comment]
Either that or the model checkpoint you're using is from that repo.

**Comment by mrortach** [comment]
Training by watching this video. https://youtu.be/3zp5LQr1VQM?si=Z3wP_Gyx7EySgGQz

**Comment by pderrenger** [comment]
Thank you for sharing the video link. If you encounter any issues or have specific questions while following the tutorial, please let us know. We're here to help!

**Comment by mrortach** [comment]
Even though it doesn't work, I get the same error. Use this method when training. https://youtu.be/3zp5LQr1VQM?si=Z3wP_Gyx7EySgGQz

**Comment by Y-T-G** [comment]
Did you manually download the yolov10x.pt?

**Comment by mrortach** [comment]
Once downloaded, it works without any problems, but its own training model does not work. 
How to train my model.
https://youtu.be/3zp5LQr1VQM?si=Z3wP_Gyx7EySgGQz

**Comment by Y-T-G** [comment]
Delete the yolov10x.pt file. It should download automatically.

**Comment by Y-T-G** [comment]
> Once downloaded, it works without any problems, but its own training model does not work. How to train my model. https://youtu.be/3zp5LQr1VQM?si=Z3wP_Gyx7EySgGQz

If you trained it like that, there shouldn't be an issue. But if you trained using this, then you would have an issue:
https://github.com/THU-MIG/yolov10

**Comment by mrortach** [comment]
No I didn't use this. https://github.com/THU-MIG/yolov10

**Comment by mrortach** [comment]
I still haven't tried it with 3 epochs, but I think something is stuck. I wonder if I chose instance segmentation with roboflow and marked them all as such, and instance segmentation is not yet available in Yolov10. Could this be the problem? If so, how can I choose from the beginning again?

**Comment by Y-T-G** [comment]
Instance segmentation will automatically be converted to box

**Comment by mrortach** [comment]
I don't need to do anything for this, right?

**Comment by mrortach** [comment]
There was no problem in 3 epochs.

**Comment by pderrenger** [comment]
Great to hear that the 3-epoch test ran without issues. For the 70-epoch run, ensure you're using the latest version of the Ultralytics package to avoid any potential bugs. If you encounter any issues, please let us know. Happy training!

**Comment by mrortach** [comment]
I probably confirmed it while making changes with the old file. No problem this time. Thank you everyone.

**Comment by pderrenger** [comment]
Glad to hear it's working now! If you encounter any other issues or have further questions, feel free to reach out. Happy training!
