### ISSUE TITLE
How to import custom activation function in SimAM

### ISSUE THREAD

**Issue by JustinGYF** [ultralytics/ultralytics#14678]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I imported the AconC module into the conv.py file of yolov8
```python
class AconC(nn.Module):
    # ACON activation (activate or not).
    # AconC: (p1*x-p2*x) * sigmoid(beta*(p1*x-p2*x)) + p2*x, beta is a learnable parameter
    # according to "Activate or Not: Learning Customized Activation" <https://arxiv.org/pdf/2009.04759.pdf>.

    def __init__(self, width):
        super().__init__()
        self.p1 = nn.Parameter(torch.randn(1, width, 1, 1))
        self.p2 = nn.Parameter(torch.randn(1, width, 1, 1))
        self.beta = nn.Parameter(torch.ones(1, width, 1, 1))

    def forward(self, x):
        return (self.p1 * x - self.p2 * x) * torch.sigmoid(self.beta * (self.p1 * x - self.p2 * x)) + self.p2 * x`
```

 hoping to use the activation function of AconC in SimAm,
```python
class SimAM(torch.nn.Module):
    def __init__(self, channels = None, e_lambda = 1e-4):
        super(SimAM, self).__init__()
 
        self.activaton = nn.AconC()  
        self.e_lambda = e_lambda
 
    def __repr__(self):
        s = self.__class__.__name__ + '('
        s += ('lambda=%f)' % self.e_lambda)
        return s`
```

but the following error occurred
```
   self.activaton = nn.AconC()
                     ^^^^^^^^
AttributeError: module 'torch.nn' has no attribute 'AconC'`
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by ambitious-octopus** [comment]
Hey @JustinGYF,  from the code you are providing it looks like you are mis-importing the `AconC` module, try this:

```python
class SimAM(torch.nn.Module):
    def __init__(self, channels = None, e_lambda = 1e-4):
        super(SimAM, self).__init__()
 
        self.activaton = AconC()  
        self.e_lambda = e_lambda
 
    def __repr__(self):
        s = self.__class__.__name__ + '('
        s += ('lambda=%f)' % self.e_lambda)
        return s
   ```

**Comment by JustinGYF** [comment]
> Hey @JustinGYF, from the code you are providing it looks like you are mis-importing the `AconC` module, try this:
> 
> ```python
> class SimAM(torch.nn.Module):
>     def __init__(self, channels = None, e_lambda = 1e-4):
>         super(SimAM, self).__init__()
>  
>         self.activaton = AconC()  
>         self.e_lambda = e_lambda
>  
>     def __repr__(self):
>         s = self.__class__.__name__ + '('
>         s += ('lambda=%f)' % self.e_lambda)
>         return s
> ```

thank you,but there is a problem, an error message ：name 'AconC' is not defined

**Comment by ambitious-octopus** [comment]
@JustinGYF because you have to define the class, here is the complete code!


```python
import torch
from torch import nn

class AconC(nn.Module):
    r""" ACON activation (activate or not).
    # AconC: (p1*x-p2*x) * sigmoid(beta*(p1*x-p2*x)) + p2*x, beta is a learnable parameter
    # according to "Activate or Not: Learning Customized Activation" <https://arxiv.org/pdf/2009.04759.pdf>.
    """

    def __init__(self, width):
        super().__init__()
        self.p1 = nn.Parameter(torch.randn(1, width, 1, 1))
        self.p2 = nn.Parameter(torch.randn(1, width, 1, 1))
        self.beta = nn.Parameter(torch.ones(1, width, 1, 1))

    def forward(self, x):
        return (self.p1 * x - self.p2 * x) * torch.sigmoid(self.beta * (self.p1 * x - self.p2 * x)) + self.p2 * x

class SimAM(torch.nn.Module):
    def __init__(self, channels = None, e_lambda = 1e-4):
        super(SimAM, self).__init__()
 
        self.activaton = AconC()  
        self.e_lambda = e_lambda
 
    def __repr__(self):
        s = self.__class__.__name__ + '('
        s += ('lambda=%f)' % self.e_lambda)
        return s
```

**Comment by JustinGYF** [comment]
> @JustinGYF because you have to define the class, here is the complete code!
> 
> ```python
> import torch
> from torch import nn
> 
> class AconC(nn.Module):
>     r""" ACON activation (activate or not).
>     # AconC: (p1*x-p2*x) * sigmoid(beta*(p1*x-p2*x)) + p2*x, beta is a learnable parameter
>     # according to "Activate or Not: Learning Customized Activation" <https://arxiv.org/pdf/2009.04759.pdf>.
>     """
> 
>     def __init__(self, width):
>         super().__init__()
>         self.p1 = nn.Parameter(torch.randn(1, width, 1, 1))
>         self.p2 = nn.Parameter(torch.randn(1, width, 1, 1))
>         self.beta = nn.Parameter(torch.ones(1, width, 1, 1))
> 
>     def forward(self, x):
>         return (self.p1 * x - self.p2 * x) * torch.sigmoid(self.beta * (self.p1 * x - self.p2 * x)) + self.p2 * x
> 
> class SimAM(torch.nn.Module):
>     def __init__(self, channels = None, e_lambda = 1e-4):
>         super(SimAM, self).__init__()
>  
>         self.activaton = AconC()  
>         self.e_lambda = e_lambda
>  
>     def __repr__(self):
>         s = self.__class__.__name__ + '('
>         s += ('lambda=%f)' % self.e_lambda)
>         return s
> ```

Sorry, I followed your code and still encountered a problem.`TypeError: AconC.__init__() missing 1 required positional argument: 'width'`

**Comment by pderrenger** [comment]
It looks like the `AconC` class requires a `width` argument during initialization. When you instantiate `AconC` in the `SimAM` class, make sure to pass the appropriate `width` value. For example, you can pass the `channels` parameter to `AconC`. Adjust your `SimAM` class initialization accordingly. If you encounter further issues, please ensure you are using the latest version of the package.
