### ISSUE TITLE
Whether 3D result prediction is supported?

### ISSUE THREAD

**Issue by lushikai** [ultralytics/ultralytics#14688]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

@glenn-jocher Hello, contributors! I trained with the MMDetection3D model to get a `.pth` weight file, and I want to use this weight file to make predictions, whether ultralytics supports 3D predictions?

**Comment by Burhan-Q** [comment]
@lushikai the only model weights that are supported by `ultralytics` are those generated using the `ultralytics` library. Currently we have no support for a 3D prediction task. All available tasks are listed in the [docs](https://docs.ultralytics.com/tasks).
