### ISSUE TITLE
YOLOv10 OMP Error #15: libiomp5md.dll Already Initialized

### ISSUE THREAD

**Issue by mrortach** [ultralytics/ultralytics#14681]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug
```
1/1: 0... Success ✅ (inf frames of shape 640x480 at 30.00 FPS)


WARNING ⚠️ inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memmory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:

    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

0: 480x640 1 person, 123.2ms
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
```

### Minimal Reproducible Example

```Python 
from ultralytics import YOLO

# Load a pre-trained YOLOv10x model
model = YOLO("yolov10s.pt")

# Perform object detection on an image or video (0 for webcam)
results = model.track(0, save=True, show=True, conf=0.2)

# Display the results
results[0].show()

**Comment by ambitious-octopus** [comment]
Hey @mrortach, I am unable to reproduce this error. Can you please provide the output of the `yolo check` command?

**Comment by mrortach** [comment]
I don't know exactly how to do this.

**Comment by ambitious-octopus** [comment]
Hey @mrortach, just run the command: `yolo check` and post the output. 
To do this simply open a terminal, activate the correct environment (if you are using a python virtual environment), type `yolo check` and post the results.

**Comment by mrortach** [comment]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\***\.conda\envs\yolov10x_derin\Scripts\yolo.exe\__main__.py", line 4, in <module>
  File "C:\Users\***\.conda\envs\yolov10x_derin\Lib\site-packages\ultralytics\__init__.py", line 10, in <module>
    from ultralytics.data.explorer.explorer import Explorer
  File "C:\Users\***\.conda\envs\yolov10x_derin\Lib\site-packages\ultralytics\data\__init__.py", line 3, in <module>
    from .base import BaseDataset
  File "C:\Users\***\.conda\envs\yolov10x_derin\Lib\site-packages\ultralytics\data\base.py", line 15, in <module>
    from torch.utils.data import Dataset
  File "C:\Users\***\.conda\envs\yolov10x_derin\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] Belirtilen modül bulunamadı. Error loading "C:\Users\***\.conda\envs\yolov10x_derin\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by pderrenger** [comment]
It looks like you're encountering an issue with a missing or improperly loaded DLL file in your environment. Please ensure that you have the latest versions of all packages, including PyTorch and Ultralytics. You can update your packages using `pip install --upgrade ultralytics torch`. If the issue persists, try reinstalling your environment. Let me know if you need further assistance!

**Comment by mrortach** [comment]
The problems have been solved, but I am having problems with my own model. Topic link: https://github.com/ultralytics/ultralytics/issues/14676

**Comment by pderrenger** [comment]
@mrortach thank you for the update. For issues with your custom model, please ensure you're using the latest versions of all relevant packages. If the problem persists, could you provide more details on the specific issue you're encountering? This will help us assist you more effectively.

**Comment by glenn-jocher** [comment]
Thank you for the update. For issues with your own model, please ensure you're using the latest versions of Ultralytics and PyTorch. If the problem persists, kindly provide more details on the linked topic so we can assist you further.

**Comment by MZaid101** [comment]
Hello, I am having the same issue:

```
>python test_track.py 

0: 384x640 2 Bootss, 2 Persons, 77.6ms
Speed: 5.0ms preprocess, 77.6ms inference, 109.6ms postprocess per image at shape (1, 3, 384, 640)

OMP: Error #15: Initializing libiomp5md.dll, but found libomp140.x86_64.dll already initialized.
```

here is the code:

```
import cv2

from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('e_ppe_e.pt')

# Open the video file
video_path = "AI/FD45.mp4"
cap = cv2.VideoCapture(video_path)

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 tracking on the frame, persisting tracks between frames
        results = model.track(frame, persist=True)

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Display the annotated frame
        cv2.imshow("YOLOv8 Tracking", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()
```

```
> python test_track.py 

0: 384x640 2 Bootss, 2 Persons, 77.6ms
Speed: 5.0ms preprocess, 77.6ms inference, 109.6ms postprocess per image at shape (1, 3, 384, 640)

OMP: Error #15: Initializing libiomp5md.dll, but found libomp140.x86_64.dll already initialized.
```

I am using my custom trained model:
[We Transfer Link for the Model file](https://we.tl/t-vSEZEvJWYF)

for further information:
```
> yolo check
Ultralytics YOLOv8.2.78 🚀 Python-3.12.4 torch-2.4.0+cu124 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 8188MiB)
Setup complete ✅ (24 CPUs, 31.8 GB RAM, 126.2/520.0 GB disk)

OS                  Windows-11-10.0.22631-SP0
Environment         Windows
Python              3.12.4
Install             pip
RAM                 31.81 GB
CPU                 13th Gen Intel Core(TM) i7-13700HX
CUDA                12.4

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.2>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.4.0+cu124>=1.8.0
torchvision         ✅ 0.19.0+cu124>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0
```

**Comment by glenn-jocher** [comment]
Please ensure you're using the latest versions of Ultralytics and PyTorch. If the issue persists, try setting the environment variable `KMP_DUPLICATE_LIB_OK=TRUE` before running your script. This can be done in your Python script with `import os; os.environ['KMP_DUPLICATE_LIB_OK']='TRUE'`. If the problem continues, please update the GitHub issue with any new findings.
