### ISSUE TITLE
when resuming rtdetr-l,The map value stays at 0

### ISSUE THREAD

**Issue by super-song-sir** [ultralytics/ultralytics#14682]
The break occurs when I train the rtdetr-l model with 300 epoches going to 90, but when I use resume, the epoches start at 91 but the map,R and P value become 0 and stay at 0 。the training code as follow:
`model = RTDETR(r'D:\project\ultralytics-main\tools\runs\detect\train\weights\last.pt')`
`results = model.train( resume=True)`
Also, when I train rtdetr-l, there are only last.pt and no best.pt in the weights file.And, after the training is completed, the folder contains only the training set GT box images. There is no val set GT box and predicted box images.But when I training yolov8，there is no problem as described above.could you tell me why?

**Comment by pderrenger** [comment]
@super-song-sir thank you for bringing this to our attention. It sounds like there might be an issue with the resuming functionality for the RTDETR model. First, please ensure you are using the latest version of the Ultralytics package, as updates often include important bug fixes. If the issue persists, it could be related to how the RTDETR model handles checkpoints and resuming training. Unlike YOLOv8, RTDETR might have different mechanisms for saving and resuming states. The absence of `best.pt` and the missing validation set images suggest that the checkpointing process might not be functioning as expected. We recommend checking the latest documentation for any model-specific instructions or updates. If the problem continues, please open an issue on GitHub with detailed logs and steps to reproduce the error, so our team can investigate further.

**Comment by super-song-sir** [comment]
> thank you for bringing this to our attention. It sounds like there might be an issue with the resuming functionality for the RTDETR model. First, please ensure you are using the latest version of the Ultralytics package, as updates often include important bug fixes. If the issue persists, it could be related to how the RTDETR model handles checkpoints and resuming training. Unlike YOLOv8, RTDETR might have different mechanisms for saving and resuming states. The absence of `best.pt` and the missing validation set images suggest that the checkpointing process might not be functioning as expected. We recommend checking the latest documentation for any model-specific instructions or updates. If the problem continues, please open an issue on GitHub with detailed logs and steps to reproduce the error, so our team can investigate further.

It seems the 'rtdetr-l' gets this problems. In addition to yolov8 ,I have tested 'rtdetr-resnet50' . And there is no problems,it can resume effectively.I will update and test again.Could you please test  'rtdetr-l''s resuming function with any dataset too?

**Comment by pderrenger** [comment]
@super-song-sir thank you for the additional information. It's helpful to know that the issue is specific to the 'rtdetr-l' model and not present in 'rtdetr-resnet50'. We will look into the resuming functionality for 'rtdetr-l' to identify any potential issues. In the meantime, please ensure you are using the latest version of the Ultralytics package and try updating and testing again. If the problem persists, please open an issue on GitHub with detailed logs and steps to reproduce the error, and our team will investigate further. Your patience and cooperation are appreciated.

**Comment by RDjarbeng** [comment]
There is no rtdetr-resnet50 from ultralytics apparently
FileNotFoundError: [Errno 2] No such file or directory: 'rtdetr-resnet50.pt'

Not sure if this was intended as a solution.

The issue never concluded before being closed, I have a similar problem with the model not resuming training and this isn't helping

**Comment by glenn-jocher** [comment]
Thank you for your comment. You're correct that Ultralytics does not provide an `rtdetr-resnet50.pt` model by default. If you're experiencing issues resuming training with RT-DETR models, I recommend ensuring you're using the proper checkpoint file (`last.pt`) from a previous training run and the latest version of the Ultralytics package. If the issue persists, please open a new GitHub issue with detailed logs and reproduction steps so we can investigate further.

**Comment by RDjarbeng** [comment]
Unfortunately I'm not going to open a new issue. I've spent too much time on this already.

The current issue has all the steps you mentioned and it still wasn't solved after so many months. Hopefully it gets fixed/clarified, but I made this comment just to clarify that it's still an issue.

Thanks for your reply

**Comment by glenn-jocher** [comment]
Thank you for the clarification. I understand your frustration, and I apologize for any inconvenience caused. We'll revisit the issue to ensure it gets the attention it needs. If you change your mind or have additional details, updating the original issue or sharing feedback is always welcome.
