### ISSUE TITLE
mAP_small,mAP_medium,mAP_large

### ISSUE THREAD

**Issue by Enryuwashere** [ultralytics/ultralytics#14685]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hello I have searched some of issues about showing the results of mAP_small,mAP_medium,mAP_large but you said that it will shows on the log of the output. But in my case, I didnt find anything about that value and the log results only show like this:

![Screenshot 2024-07-25 204439](https://github.com/user-attachments/assets/d9f3de40-2176-4897-8139-b3361629815d)

is that because of the newest version of yolov8 or not? is there any way to show up the mAP_small,mAP_medium,mAP_large values again? thank you

**Comment by Y-T-G** [comment]
You can run model.val() with `save_json` and it will return the COCO results.

**Comment by Enryuwashere** [comment]
How to run the model.val() with save.json ? because I cant find it in ultralytics website.

**Comment by Y-T-G** [comment]
```
results= model.val(data="data.yaml", save_json=True)
dir(results)
```

**Comment by Enryuwashere** [comment]
when I print the dir(results) this is the output

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'ap_class_index',
 'box',
 'class_result',
 'confusion_matrix',
 'curves',
 'curves_results',
 'fitness',
 'keys',
 'maps',
 'mean_results',
 'names',
 'on_plot',
 'plot',
 'process',
 'results_dict',
 'save_dir',
 'speed',
 'task']
 
 and I try to print all of the output I didn't find AP_small,AP_medium,and AP_large. Even the results = model.val still same with my previous photos only showing the results of class, image,instances,box p, r, mAP50 and mAP50-95 with the speed

**Comment by Y-T-G** [comment]
It should be in results.keys

**Comment by Y-T-G** [comment]
Yeah, it won't work. It only works for the COCO dataset.

You can use the COCOAPI to calculate it manually from the saved `predictions.json`, but you will need to convert your annotations to COCO JSON format first.

**Comment by Y-T-G** [comment]
```python
from pycocotools.coco import COCO 
from pycocotools.cocoeval import COCOeval

anno = COCO(str(anno_json)) # Load your JSON annotations
pred = anno.loadRes(str(pred_json))   # Load predictions.json
val = COCOeval(anno, pred, "bbox")
val.evaluate()
val.accumulate()
val.summarize()
val.print_results()
```
