### ISSUE TITLE
Yolo v8.0 & v8.2 - save_period parameter not working as expected

### ISSUE THREAD

**Issue by custom-build-robots** [ultralytics/ultralytics#14694]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

When I train a model with for example EPOCH 20 and the parameter save_period=1 I am missing the very first EPOCH 0 in the weights folder.

Below you see the saved *.pt files with their corresponding timestamp. 
This is repeadable on my ubuntu system with yolo v8.2 installed and on a windows machine with yolo v8.0 installed.

Model Path										Timestamp
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/epoch1.pt		24.07.2024 19:20
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/epoch2.pt		24.07.2024 19:57
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/epoch3.pt		24.07.2024 20:34
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/epoch4.pt		24.07.2024 21:12
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/epoch5.pt		24.07.2024 21:49
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/epoch6.pt		24.07.2024 22:27
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/epoch7.pt		24.07.2024 23:04
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/epoch8.pt		24.07.2024 23:41
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/epoch9.pt		25.07.2024 00:17
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/epoch10.pt	25.07.2024 00:53
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/epoch11.pt	25.07.2024 01:29
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/epoch12.pt	25.07.2024 02:05
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/epoch13.pt	25.07.2024 02:40
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/epoch14.pt	25.07.2024 03:16
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/epoch15.pt	25.07.2024 03:52
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/epoch16.pt	25.07.2024 04:27
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/epoch17.pt	25.07.2024 05:03
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/epoch18.pt	25.07.2024 05:39
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/last.pt		25.07.2024 06:15
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/epoch19.pt	25.07.2024 06:15
/mnt/data_2/05_mushroom/mushroom_training/20240724_mushroomm2/weights/best.pt		25.07.2024 06:15

Any idea if I have a missunderstanding here or maybe it is a bug?

### Environment

Ultralytics YOLOv8.2.10 🚀 Python-3.10.12 torch-2.0.1+cu117 CUDA:0 (NVIDIA RTX A6000, 48682MiB)
Setup complete ✅ (32 CPUs, 62.7 GB RAM, 694.6/915.3 GB disk)

OS                  Linux-6.2.0-39-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 62.71 GB
CPU                 AMD Ryzen 9 3950X 16-Core Processor
CUDA                11.7

matplotlib          ✅ 3.8.2>=3.3.0
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 2.0.1>=1.8.0
torchvision         ✅ 0.15.2>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.1.3>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0

### Minimal Reproducible Example

from ultralytics import YOLO
 
import os
os.environ['WANDB_MODE'] = 'disabled'
 
if __name__ == '__main__':
    model = YOLO('yolov8m.pt')

    results = model.train(

# Ingmar Hyperparameters
        data = '/mnt/data_2/05_mushroom/mushroom_yolov8_20240724.yaml',
        save_dir = '/mnt/data_2/05_mushroom/',
        epochs=20,
        batch=16,
        imgsz=1280,
        lr0=0.01,
        lrf=0.01,
        momentum=0.937,
        weight_decay=0.0005,
        warmup_epochs=3,
        warmup_momentum=0.8,
        box=7.5,
        save_period=1,
        cls=0.5,
        dfl=1.5,
        hsv_h=0.015,
        hsv_s=0.7,
        hsv_v=0.4,
        degrees=0.0,
        translate=0.1,
        scale=0.5,
        shear=0.0,
        perspective=0.0,
        flipud=0.0,
        fliplr=0.5,
        bgr=0,
        mosaic=1,
        mixup=0.0,
        copy_paste=0.0,
        project='mushroom_training',
        name='20240724_mushroom_m'

    )

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Burhan-Q** [comment]
From the [docs](https://docs.ultralytics.com/modes/train/#train-settings):

> `save_period` Frequency of saving model checkpoints, specified in epochs. A value of -1 disables this feature. Useful for saving interim models during long training sessions.

In the code https://github.com/ultralytics/ultralytics/blob/7a48b62cbc4a2fa709ee4bb86e8c95a693c08e1f/ultralytics/engine/trainer.py#L510-L511

**Comment by Burhan-Q** [comment]
Guessing your request is for this change?

```diff
- if (self.save_period > 0) and (self.epoch > 0) and (self.epoch % self.save_period == 0): 
+ if (self.save_period > 0) and (self.epoch >= 0) and (self.epoch % self.save_period == 0): 
```

**Comment by Burhan-Q** [comment]
@custom-build-robots I've opened PR #14700 to include this change. When I tested, it does now save a checkpoint for `epoch==0`
![image](https://github.com/user-attachments/assets/9cc5e954-f37e-498c-b26c-352216330f9c)

**Comment by custom-build-robots** [comment]
Thank you @Burhan-Q for explaining the cause in the code and already fixing it!
