### ISSUE TITLE
Panoptic Segmentation?

### ISSUE THREAD

**Issue by kevinconka** [ultralytics/ultralytics#1470]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello!

I have been experimenting with yolov5 and now I want to try yolov8. 

I am aware that yolov8 supports instance segmentation but can it also be purposed for panoptic segmentation? In the [ultralytics' website](https://docs.ultralytics.com/#a-brief-history-of-yolo) it is stated that yolov5 already supports panoptic segmentation.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/35779409/225923191-d4b0f88a-0884-43a2-b4a6-e04bf117c6cf.png">

By panoptic segmentation I mean classifying every pixel in the image.

![image](https://user-images.githubusercontent.com/35779409/225922881-ceddb6b2-a407-4b02-831e-fc5708886cf2.png)

Thanks and looking forward to your reply!
Kevin Serrano

**Comment by glenn-jocher** [comment]
@kevinconka presently we support instance segmentation, and instance segmentation with tracking, but not the other two examples shown above since they are not as commonly requested. We are adding tasks this year though, starting with Pose.

@AyushExel

**Comment by AyushExel** [comment]
@glenn-jocher @kevinconka Great feature request! I think panoptic segmentation is a great task to support. It's been getting popular due to self-driving examples.
The road to panoptic segmentation should involve getting semantic segmentation support first. I think once we're done with pose, we can start to take a look at it

**Comment by achbogga** [comment]
@AyushExel , I would like this support as well as pose with instance masks if possible!

**Comment by glenn-jocher** [comment]
@achbogga thank you for your interest in our YOLOv8 project! We appreciate your feedback and suggestions. We acknowledge there is a growing demand for panoptic segmentation support and we will consider it for future development. Additionally, we are happy to hear that you are also interested in Pose estimation with instance segmentation, we are continually striving to improve and expand upon YOLOv8's capabilities. If you have feedback or suggestions for future developments in our project, please do not hesitate to reach out to us.

**Comment by AyushExel** [comment]
> @AyushExel , I would like this support as well as pose with instance masks if possible!

Thanks. I think we'll need semantic segmentation first right? Would you like to conribute?

**Comment by achbogga** [comment]
> > @AyushExel , I would like this support as well as pose with instance masks if possible!
> 
> Thanks. I think we'll need semantic segmentation first right? Would you like to conribute?

I would like to contribute. But I might need some guidance. Please let me know if we can quickly hop on a call to discuss the high level design components.

**Comment by 3DMM-ICME2024** [comment]
@kevinconka kevinconka hello, could you please share the link that yolo is purposed for panoptic segmentation? Thank you very much!
