### ISSUE TITLE
Saving failing cases in YOLO val

### ISSUE THREAD

**Issue by tjasmin111** [ultralytics/ultralytics#14727]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am running `yolo val` on a test set to obtain the detection mAP and recall metrics and how my model performs. Now, I need to save the failing cases for further analysis. How can I do this in yolo?

`yolo detect val model=model.pt data=test.yaml`

**Comment by pderrenger** [comment]
@tjasmin111 to save failing cases during validation, you can use the `save_txt` argument in the `yolo val` command. This will save the detection results, including the failing cases, in a text file for further analysis. You can run the following command:

```bash
yolo detect val model=model.pt data=test.yaml save_txt=True
```

This will generate text files with the detection results, which you can then review to identify and analyze the failing cases. If you need more detailed information, please refer to our documentation at https://docs.ultralytics.com/reference/models/yolo/detect/val/.

**Comment by tjasmin111** [comment]
Thanks. I know the save_txt option but is there a way to only filter the failed cases?

I need to check them visually to see what fails.

**Comment by pderrenger** [comment]
To filter and save only the failed cases during validation, you can use the `save_conf` argument along with `save_txt`. This will include confidence scores in the saved text files, allowing you to identify and focus on low-confidence detections. Unfortunately, there isn't a built-in feature to automatically filter and save only failed cases, so you may need to implement a custom post-processing step to achieve this. For more detailed guidance, you can refer to our documentation or explore custom scripts to parse and filter the results based on your criteria.
