### ISSUE TITLE
Instability and Frame Loss during YOLOv8 Inference with RTSP Video Streams

### ISSUE THREAD

**Issue by Rasantis** [ultralytics/ultralytics#14720]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

We are experiencing significant instability and frame loss during the inference process when using YOLOv8 with video streams coming via RTSP. This issue is critical as it affects the accuracy and reliability of our application.

Steps to Reproduce:

Set up an RTSP video stream.
Configure YOLOv8 for inference on the incoming RTSP stream.
Monitor the inference process.
Expected Behavior:
Stable inference with minimal frame loss.

Observed Behavior:

Significant instability during inference.
Frequent frame loss.
Performance degradation over time.
Additional Information:

Network stability has been thoroughly tested and confirmed to not be the issue.
The problem is isolated to the inference process of YOLOv8.
We have tried multiple configurations and hardware setups, but the issue persists.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
What's your stream and inference FPS like?

**Comment by Rasantis** [comment]
> What's your stream and inference FPS like?

fps around 25, im using the rtsp with tcp...

**Comment by Y-T-G** [comment]
Inference reaches the full stream FPS?

**Comment by glenn-jocher** [comment]
@Rasantis you can use `stream_buffer=True` to back up frames rather than process them in realtime. Note this may crash your system eventually if the buffer becomes too long.

**Comment by glenn-jocher** [comment]
See https://docs.ultralytics.com/modes/predict/#inference-arguments

**Comment by Rasantis** [comment]
hi @glenn-jocher even using the stream_buffer parameter it work for a few minutes, but then he stop working and loss like more than 30 seconds of frames in a row...... Do you have any solutions or ideas to solve the issue ?

**Comment by Y-T-G** [comment]
I would suggest to write a frame grabber using OpenCV and using the GStreamer backend. GStreamer supports `drop=true` argument that drops old frames in the buffer.
