### ISSUE TITLE
The recognition results of tflite model exported by yolov8 are different

### ISSUE THREAD

**Issue by einsitang** [ultralytics/ultralytics#14722]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I wanted to use yolo's model on the tensorflow platform, so I could only use tflite via export.

I have looked at the code related to preprocessing and post-processing and have found nothing unusual.

same intput image with same model but different platform(YOLO/pytorch and tensorflow lite)

the detect result is not satisfactory

**yolo model** :

![image](https://github.com/user-attachments/assets/cf2e155b-eca2-4b41-80ea-8989b3f3d63f)

**tensorflow lite** :
![image](https://github.com/user-attachments/assets/66d1af4d-971d-4e50-80d5-1179580b520a)

I would appreciate it if you would review or modify my code problems for me

here is the kaggle notebook : https://www.kaggle.com/code/jianbintangelement/sudoku-detect-predict-use-platform-between-tflite

**Comment by glenn-jocher** [comment]
@einsitang run your TFLite model directly with Ultralytics. Outputs are identical to PyTorch:

```python
from ultralytics import YOLO

# Load an Ultralytics YOLO TFLite model
model = YOLO("path/to/model.tflite")

# Run inference with TFLite model
results = model("path/to/image.jpg")
```

**Comment by einsitang** [comment]
> @einsitang run your TFLite model directly with Ultralytics. Outputs are identical to PyTorch:
> 
> ```python
> from ultralytics import YOLO
> 
> # Load an Ultralytics YOLO TFLite model
> model = YOLO("path/to/model.tflite")
> 
> # Run inference with TFLite model
> results = model("path/to/image.jpg")
> ```

I need use tflite model without yolo/pytorch, because I want the model deploy on mobile device , that is way I need ensure tensorflow lite and yolo with same output

**Comment by Y-T-G** [comment]
Something wrong with your postprocessing.

You will have to replicate the post-processing here:

https://github.com/ultralytics/ultralytics/blob/673e76b86282859ead5517bd04dee896a647db93/examples/YOLOv8-OpenCV-int8-tflite-Python/main.py#L185

**Comment by einsitang** [comment]
> Something wrong with your postprocessing.
> 
> 
> 
> You will have to replicate the post-processing here:
> 
> 
> 
> https://github.com/ultralytics/ultralytics/blob/673e76b86282859ead5517bd04dee896a647db93/examples/YOLOv8-OpenCV-int8-tflite-Python/main.py#L185

thanks, I’am solved with this link

**Comment by pderrenger** [comment]
@einsitang great to hear that the link helped resolve your issue! If you have any more questions or run into other problems, feel free to ask. Happy coding!
