### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'model'

### ISSUE THREAD

**Issue by hariouat** [ultralytics/ultralytics#14737]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, 
i don't know why when i try to run this code i gave this error. 

AttributeError: 'NoneType' object has no attribute 'model'

<img width="1066" alt="image" src="https://github.com/user-attachments/assets/70a7b76f-2e2d-40c0-9c1a-208999dc7352">

**Comment by pderrenger** [comment]
@hariouat hello,

The error "AttributeError: 'NoneType' object has no attribute 'model'" typically indicates that an object you're trying to access has not been properly initialized. Please ensure that your model is correctly loaded before invoking any methods on it. 

Additionally, make sure you are using the latest version of the Ultralytics package, as updates often include important bug fixes. You can update the package using `pip install --upgrade ultralytics`.

If the issue persists, please provide more context or a minimal code snippet to help diagnose the problem further.
