### ISSUE TITLE
Evaluation metrics for OBB on custom dataset

### ISSUE THREAD

**Issue by Petros626** [ultralytics/ultralytics#14749]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

On the docs site https://docs.ultralytics.com/modes/val/ and here: https://github.com/ultralytics/ultralytics/blob/f8454f1ab71b860371deb03591342f6d6c87efac/ultralytics/utils/metrics.py#L633 I found the evaluation metrics for YOLOv8 OBB and would like to know, if these are the only evaluation metrics? 

Will be in the future metrics like: FLOPS, latency, model size, FPS

Thank you.

**Comment by Y-T-G** [comment]
You can find FLOPs and nom of parameters using `model.info()`.

FPS and latency depends on your system. You can run model benchmark:

https://docs.ultralytics.com/modes/benchmark/#supported-export-formats

**Comment by Petros626** [comment]
Thank you for this hint.

Does this `model.info()` mean during evaluation I'll get the live FLOPS?

**Comment by Y-T-G** [comment]
No, that's separate. It also shows it during `model.val()` if you look at the logs. I don't why you want it live. The FLOPs doesn't change during training.

**Comment by Petros626** [comment]
I thought during a evaluation process of e.g. 1000 images the model outputs his FLOPS for every single image until finishing the task. I need this metric not for the training process. 

Which of them you mean:
`FLOPS = Floating point operations per second`
`FLOPs = Floating point operations `

**Comment by Y-T-G** [comment]
> I thought during a evaluation process of e.g. 1000 images the model outputs his FLOPS for every single image until finishing the task. 

It doesn't show that. It would be difficult to calculate that. I don't know any library that calculates FLOPS live.

I was referring to FLOPs (Floating point operations ).

**Comment by Petros626** [comment]
Okay so this parameter is available during training and in the finished model file? I thought the term was referred to the operations during inference.

**Comment by Y-T-G** [comment]
FLOPs is based on the model. It doesn't change for a model. Just like number of parameters.

FLOPS is based on your system. It is usually used in the context of GPU performance. It doesn't directly relate to the model.

**Comment by Petros626** [comment]
Thank you for the clarification, I'll reopen this issue if needed.

**Comment by pderrenger** [comment]
You're welcome! Feel free to reopen the issue if you encounter any further problems or have additional questions. We're here to help.
