### ISSUE TITLE
Slow startup on yolov8 with internet access

### ISSUE THREAD

**Issue by renzo76** [ultralytics/ultralytics#1474]
It takes about 16 seconds to execute on anaconda with the yolo command without internet.
It's only 4 seconds when connected to the internet.

How can I resolve this issue?

**Comment by glenn-jocher** [comment]
@renzo76 on my 2022 Macbook M2 with WiFi disabled:

```python
import time
t = time.time()
from ultralytics import YOLO
model = YOLO('yolov8n.pt')
results = model()
print(time.time() - t)
Backend MacOSX is interactive backend. Turning interactive mode on.
WARNING ⚠️ 'source' is missing. Using 'source=/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets'.
image 1/4 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus.jpg: 640x480 4 persons, 1 bus, 1 stop sign, 50.7ms
image 2/4 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus_4ch.png: 640x480 4 persons, 1 bus, 1 stop sign, 50.2ms
image 3/4 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus_greyscale.jpg: 640x480 3 persons, 1 bus, 48.2ms
image 4/4 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/zidane.jpg: 384x640 2 persons, 1 tie, 41.1ms
Speed: 0.3ms preprocess, 47.6ms inference, 0.5ms postprocess per image at shape (1, 3, 640, 640)
1.1556432247161865
```

**Comment by q465414859** [comment]
有可能是 中国内网站 和 国外网站的区别

**Comment by glenn-jocher** [comment]
@q465414859 @renzo76 yes maybe there's a difference in China. 

We have a maintainer there actually. @Laughing-q if you run the below code with/without internet access do you see a speed difference? For me I see the same speed, about 1.2s in a new environment the first time I run the command or 0.3s additional times I run the code in the same environment.

```python
import time
t = time.time()

from ultralytics import YOLO
model = YOLO('yolov8n.pt')
results = model()

print(time.time() - t)
```

**Comment by Laughing-q** [comment]
@glenn-jocher @renzo76 @q465414859 tested with internet and without internet, it shows 5.5s vs 5s on my notebook.

**Comment by renzo76** [comment]
Here are my results:

No internet

(yolov8) C:\Users\admin>python predict.py

image 1/1 \\x.x.x.x\image.jpg: 384x640 1 truck, 101.7ms
Speed: 0.0ms preprocess, 101.7ms inference, 6.0ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs\detect\predict3
16.469942569732666

(yolov8) C:\Users\admin>

Here is the python file with commands:

import time
t=time.time()
from ultralytics import YOLO
model=YOLO("yolov8x.pt")
model.predict(source="\\\\x.x.x.x\\image.jpg",save=True)
print(time.time()-t)

**Comment by glenn-jocher** [comment]
@renzo76 your command seems fine. Since it's not reproducible by myself or @Laughing-q it's up to you to try to find the source of any possible slowdowns. If you identify which function(s) are causing the problems please let us know.
