### ISSUE TITLE
How do I change the serial number of the GPU I'm training on during training, from GPU1 to GPU2

### ISSUE THREAD

**Issue by Sparklexa** [ultralytics/ultralytics#14759]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How do I change the serial number of the GPU I'm training on during training, from GPU1 to GPU2.At the check point

**Comment by sunmooncode** [comment]
You can change it with the [**device**](https://docs.ultralytics.com/modes/train/#train-settings:~:text=increased%20memory%20usage.-,device,-None) parameter.

**Comment by sunmooncode** [comment]
It cannot be changed during training.

**Comment by pderrenger** [comment]
You are correct; changing the GPU during an ongoing training session is not supported. To switch GPUs, you would need to stop the current training, modify the `device` parameter to specify the new GPU, and then resume training from the last checkpoint. If you encounter any issues with this process, please ensure you are using the latest version of the Ultralytics package.

**Comment by Sparklexa** [comment]
I'm sorry, that doesn't seem to be working. I first stop the training, then enter parameters results = model.train(data="coco.yaml", epochs=500, imgsz=640, batch=32, resume=True, device=1), But GPU0 is still used instead of GPU1 @pderrenger

**Comment by pderrenger** [comment]
@Sparklexa it sounds like the device parameter might not be correctly recognized. Please ensure you are using the latest version of the Ultralytics package. If the issue persists, try setting the CUDA_VISIBLE_DEVICES environment variable before running your script to specify the GPU. This can help enforce the use of the desired GPU. If you continue to experience issues, please provide more details about your environment and setup.
