### ISSUE TITLE
How to train the YOLOv8-Pose model for keypoint detection as a standalone task.

### ISSUE THREAD

**Issue by Charlie-crl** [ultralytics/ultralytics#14769]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I configure YOLOv8-Pose to solely focus on keypoint detection, excluding object detection, as it is not required in my application? Is it possible for YOLOv8-Pose to perform keypoint detection as a standalone task?

Thanks for the great work you’ve done, and I appreciate any help you can provide in advance.

**Comment by Y-T-G** [comment]
Most keypoint estimation models require object detection.

You can adjust the loss weights to make it focus more on keypoints, but you can't entirely skip object detection.

https://github.com/ultralytics/ultralytics/blob/f8454f1ab71b860371deb03591342f6d6c87efac/ultralytics/cfg/default.yaml#L97-L101

**Comment by Charlie-crl** [comment]
@Y-T-G Got it, thanks a bunch!
