### ISSUE TITLE
Total people count

### ISSUE THREAD

**Issue by memoriesbytalha** [ultralytics/ultralytics#14766]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

```
class CustomObjectCounter(solutions.ObjectCounter):
    def __init__(self, classes_names):
        super().__init__(
            view_img=False,
            reg_pts=line_points,
            classes_names=classes_names,
            draw_tracks=True,
            line_thickness=2,
        )

def initialize_yolo_model(model_path):
    return YOLO(model_path)

def process_image(yolo_model, counter, image):
    model = yolo_model
    # Example classes to count
    classes_to_count = [0]  # Example classes: 0 for person
    
    # Track objects in the image
    tracks = model.track(image, persist=False, show=False, classes=classes_to_count)
    image = counter.start_counting(image, tracks)
\
    return image
    
```

I want to access the total number of people inside the picture/video and print of screen , but I am just able to access the total people in and going out.
NEED HELPP??

**Comment by Y-T-G** [comment]
Counter tracks `in_counts` and `out_counts`. 
```python
print(counter.in_counts)
```

https://github.com/ultralytics/ultralytics/blob/2ebd01faa8a709a97e08e54a6b6c8ba31fece1d0/ultralytics/solutions/object_counter.py#L80-L83

**Comment by RizwanMunawar** [comment]
@Y-T-G Thanks for sharing this! :)

@memoriesbytalha, if you want to count all objects instead of just the `in` and `out` counts, you can use the code provided below to accomplish that.

```
from ultralytics import YOLO

model = YOLO('yolov8n.pt')

results = model.predict(source="https://ultralytics.com/images/bus.jpg")
print(len(results[0]))
```

Thanks and Regards
Ultralytics Team!

**Comment by RizwanMunawar** [comment]
@memoriesbytalha I'm closing this as there hasn't been any update on this topic for the past few months.

Feel free to reopen the issue if you encounter any further problems.

Thank you!
