### ISSUE TITLE
Can tracking increase mAP50 of detection models?

### ISSUE THREAD

**Issue by optimisticabouthumanity** [ultralytics/ultralytics#14760]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi everyone, I was wondering whether mAP50 will increase for detection models when tracking is added? Is it possible that we compare the bbox and class with ground_truth after tracking is incorporated? What can be the change in mAP50?

If you have already experimented in such way, would you please share your findings?

**Comment by Y-T-G** [comment]
You can add a minimum hit threshold to reduce false positives. You can also adding voting or confidence averaging to reduce flickering and class switches.
