### ISSUE TITLE
INT8 calibration cache for TensoRT Engine

### ISSUE THREAD

**Issue by Egorundel** [ultralytics/ultralytics#14764]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

## Description

Hello, I have a YOLOv8 ONNX model with dynamic batch_size and an NMS module. 

I want to use it to turn it into a TensorRT Engine with INT8. To do this, I need to create a calibration cache. How can I do this? Is there any guide or a python script that runs? Please help me. 

Thank you in advance for your help.

## Environment

**TensorRT Version**: 8.6.1
**GPU Type**: RTX3060
**Nvidia Driver Version**: nvidia-driver-555
**CUDA Version**: 11.1
**CUDNN Version**: 8.0.4
**Operating System + Version**: Ubuntu 20.04
**Python Version (if applicable)**: 3.8.10
**PyTorch Version (if applicable)**: 1.10.1+cu111

## Relevant Files

YOLOv8_m_night.onnx
https://drive.google.com/drive/folders/1D19xWLW5mtTB6IRbmu8g87Y0vFQPZ3C6?usp=drive_link

**Comment by Egorundel** [comment]
@Y-T-G Thanks, but I need a dynamic batch size and a NMS module at the output.

**Comment by Y-T-G** [comment]
You can check the ultralytics code to find out bow calibration is done then.

**Comment by Egorundel** [comment]
@Y-T-G I would like to understand how `calibration_file.cache` is formed. And then use `trtexec` to make **TensorRT Engine**.

**Comment by Y-T-G** [comment]
https://github.com/ultralytics/ultralytics/blob/2ebd01faa8a709a97e08e54a6b6c8ba31fece1d0/ultralytics/engine/exporter.py#L745

**Comment by Petros626** [comment]
@Y-T-G what is the required `batch` when using `dynamic=True`?

TensorRT: WARNING ⚠️ 'dynamic=True' model requires max batch size, i.e. 'batch=16'

**Comment by Petros626** [comment]
validate image after image so I would say `batch=1`. In which cases a batch size of 8 or 16 makes sense?

**Comment by Y-T-G** [comment]
If you want to make inference with batch 8, you use batch 8.
