### ISSUE TITLE
Unreasonable Object Detection Counts with YOLOv8n Model

### ISSUE THREAD

**Issue by ZiYuCai1984** [ultralytics/ultralytics#14768]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Install, Predict

### Bug

I am encountering an issue with the YOLOv8n model where the detection results are not as expected. The model appears to be detecting an unusually high number of objects in a single image, which seems incorrect.

```
from ultralytics import YOLO

yolo = YOLO("yolov8n.pt",task="detect")
result = yolo(source="./ultralytics/assets/bus.jpg",save=True,conf=0.9)
```
![image](https://github.com/user-attachments/assets/b8042762-f1eb-41a4-99e1-a7b48c59b90e)

![bus](https://github.com/user-attachments/assets/aa4b00a0-0d9e-4d8c-8f4a-183686abdd25)

### Environment

OS                  Windows-10-10.0.20348-SP0
Environment         Windows
Python              3.11.9
Install             git
RAM                 15.90 GB
CPU                 Intel Core(TM) i7-9750H 2.60GHz
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.4.0>=1.8.0
torchvision         ✅ 0.19.0>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
https://www.reddit.com/r/Ultralytics/comments/1ecqmwb/psa_issues_observed_with_pytorch_240_windows_cpu/

**Comment by ZiYuCai1984** [comment]
> https://www.reddit.com/r/Ultralytics/comments/1ecqmwb/psa_issues_observed_with_pytorch_240_windows_cpu/

Thanks for your advice, it's working now.

**Comment by pderrenger** [comment]
@ZiYuCai1984 i'm glad to hear that the advice helped resolve your issue. If you encounter any further problems or have additional questions, feel free to reach out. Happy coding!

**Comment by Y-T-G** [comment]
Linking for reference https://github.com/pytorch/pytorch/issues/131958
