### ISSUE TITLE
result.tojson() returns a string, not dict

### ISSUE THREAD

**Issue by robmarkcole** [ultralytics/ultralytics#14775]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

As title. 

### Environment

Ultralytics YOLOv8.2.58 🚀 Python-3.10.10 torch-2.2.1+cu121 CUDA:0 (NVIDIA A10G, 22724MiB)
Setup complete ✅ (32 CPUs, 124.5 GB RAM, 54.5/824.0 GB disk)

### Minimal Reproducible Example

```python
results = model(image)
result = results[0]
json_result = result.tojson()
assert type(json_result) == str
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
What are you expecting instead?

**Comment by robmarkcole** [comment]
A dict I can pass to json.dumps

**Comment by Y-T-G** [comment]
It's already returning the output from `json.dumps()`

https://github.com/ultralytics/ultralytics/blob/2ebd01faa8a709a97e08e54a6b6c8ba31fece1d0/ultralytics/engine/results.py#L823

You can also see what it is dumping (`result.summary()`)

**Comment by glenn-jocher** [comment]
@Y-T-G yes that's right!

You can print this string directly and see your JSON structure.

**Comment by glenn-jocher** [comment]
@robmarkcole if you just want a dict the .summary() method is probably what you're looking for, i.e. `results[0].summary()`

**Comment by robmarkcole** [comment]
Yes I would expect a dict, rather than a string. Can confirm `results[0].summary()` returns this

**Comment by pderrenger** [comment]
Thank you for confirming. The `results[0].summary()` method indeed returns a dictionary, which you can use directly with `json.dumps()` if needed. If you encounter any further issues, please ensure you are using the latest version of the package.
