### ISSUE TITLE
result.save('/tmp/result.png') saves BGR not RGB

### ISSUE THREAD

**Issue by robmarkcole** [ultralytics/ultralytics#14777]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

As title:
Input:
<img width="423" alt="image" src="https://github.com/user-attachments/assets/21e3ba57-2937-42a0-80c9-423c9fd7106c">
Saved with prediction:
<img width="421" alt="image" src="https://github.com/user-attachments/assets/4444ddec-1e75-41d2-910c-f217b10c1582">

### Environment

Ultralytics YOLOv8.2.58 🚀 Python-3.10.10 torch-2.2.1+cu121 CUDA:0 (NVIDIA A10G, 22724MiB)
Setup complete ✅ (32 CPUs, 124.5 GB RAM, 54.5/824.0 GB disk)

### Minimal Reproducible Example

```
            if len(result.obb) > 0:
                tmp_result = '/tmp/result.png'
                result.save(tmp_result, labels=False) # hide the labels
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
The input to the model is expected to be BGR. So when it's saved, it will also be saved as such. It would only flip if you manually converted the input to RGB, but in that case, you're using the wrong input format.

**Comment by robmarkcole** [comment]
Reviewing the predict docs, it states that if a pillow Image is passed, it is expected in RGB. Other formats are expected in BGR. This is the convention used by those libraries so is the predict code switching the channel order depending on what is passed? https://docs.ultralytics.com/modes/predict/

**Comment by Y-T-G** [comment]
If you use pillow image, it will work in both RGB or BGR format. If it's BGR, it's converted to RGB

https://github.com/ultralytics/ultralytics/blob/2ebd01faa8a709a97e08e54a6b6c8ba31fece1d0/ultralytics/data/loaders.py#L422-L423

**Comment by glenn-jocher** [comment]
See https://docs.ultralytics.com/modes/predict/#inference-sources

<img width="902" alt="Screenshot 2024-07-30 at 02 12 04" src="https://github.com/user-attachments/assets/c7e2910c-60ae-4ebf-b698-22ee09d31708">

**Comment by robmarkcole** [comment]
OK I discovered this is therefore a bug in my code - I am loading a PIL Image, but converting to numpy for chipping - I was then not converting to BGR.
```python
def process_image(image: Image.Image, image_id: str, model: ultralytics.YOLO, patch_size: int, output_location: str) -> None:
    """Process an image in configurable patches and make predictions."""
    img_width, img_height = image.size
    for y in range(0, img_height, patch_size):
        for x in range(0, img_width, patch_size):
            patch = image.crop((x, y, x + patch_size, y + patch_size))
            patch_np = np.array(patch) # RGB
            patch_np = patch_np[..., ::-1] # Convert to BGR as required, this was missing
            result = model(patch_np)[0]
```
Many thanks!

**Comment by pderrenger** [comment]
Thank you for the update. It looks like you've identified the issue with the color conversion. Ensuring that the image is in BGR format before passing it to the model is crucial. If you encounter any further issues, please make sure you're using the latest version of the Ultralytics package, as updates often include important fixes and improvements. If the problem persists, feel free to reach out again. Happy coding!
