### ISSUE TITLE
YOLO OpenVINO with SAHI

### ISSUE THREAD

**Issue by ME1313** [ultralytics/ultralytics#14797]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hi. I wanna use OpenVINO for faster inference on large scale images by help of sahi slicing. i searched for how to use OpenVINO beside of sahi but i didnt find a solution or how it works? or even is it possible? if you can help me with that or there is a snip code, then please let me know. appreciations 🙏

**Comment by pderrenger** [comment]
@ME1313 hi,

Yes, you can use OpenVINO with SAHI for faster inference on large-scale images. To achieve this, you need to first export your YOLO model to the OpenVINO format and then integrate it with SAHI for sliced inference. Ensure you have the latest versions of both the Ultralytics and SAHI packages installed. 

For detailed steps on exporting your model to OpenVINO and integrating it with SAHI, please refer to our [SAHI Tiled Inference Guide](https://docs.ultralytics.com/guides/sahi-tiled-inference/). This guide provides comprehensive instructions on setting up and running sliced inference with OpenVINO.

If you encounter any issues, please verify that you are using the latest versions of the packages and try again. If the problem persists, feel free to provide more details, and we can assist further.

**Comment by ME1313** [comment]
I saw that link. It's just about SAHI. I don't know how to pass the openvino version of yolo to SAHI. I searching for combination of SAHI and openvino.

**Comment by pderrenger** [comment]
@ME1313 to use the OpenVINO version of YOLO with SAHI, you need to first export your YOLO model to the OpenVINO format using the `yolo export` command. Once exported, you can load the OpenVINO model in SAHI by specifying the model path and type. Ensure you have the latest versions of both Ultralytics and SAHI installed. For detailed steps, refer to the [SAHI Tiled Inference Guide](https://docs.ultralytics.com/guides/sahi-tiled-inference/). If you encounter issues, please verify reproducibility with the latest package versions.

**Comment by ME1313** [comment]
It's good when you don't know about something, then say nothing. Easy!!! @Burhan-Q fuck you by the way.

**Comment by Skillnoob** [comment]
@ME1313 Why are you so upset? We told you to go to the [SAHI](https://github.com/obss/sahi) github issues since this is not a ultralytics issue. Insulting someone is not the solution to your problem.

**Comment by ME1313** [comment]
@Skillnoob go fuck yourself
