### ISSUE TITLE
YOLOv8 OBB export to OpenVino error

### ISSUE THREAD

**Issue by KomodoCrypto** [ultralytics/ultralytics#14801]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to export a custom dataset model .pt to openVino. The export is done ok but I get an error in the inference. 

```
`from pathlib import Path
from PIL import Image

from ultralytics import YOLO

models_dir = Path("./Models")

model = YOLO("yolov8m-obb.pt")

# Load the exported OpenVINO model
OV_MODEL_NAME = "yolov8m-obb"

OV_MODEL_PATH = Path(f"{OV_MODEL_NAME}_openvino_model/{OV_MODEL_NAME}.xml")

if not OV_MODEL_PATH.exists():
    model.export(format="openvino", dynamic=True, half=True)

ov_model = YOLO("D:\\Models\\yolov8m-obb_openvino_model/")

# Run inference
image_path = "D:\\Deep\\test_low.png"

results = ov_model(image_path, device="cpu")`
```

The above code is working fine if I use yolov8m-obb model as the example. However, when I execute it with my obb model trained on custom dataset (working fine as .pt), I get this error: 

`Exception has occurred: KeyError
2
  File "D:\Deep\openVino_export.py", line 36, in <module>
    results = ov_model(image, device="cpu")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 2`

**Comment by Y-T-G** [comment]
You should specify the `task="obb"` while loading the model

**Comment by KomodoCrypto** [comment]
oh, that was the key :) It works now. Thank you for your fast reply!

**Comment by pderrenger** [comment]
@KomodoCrypto glad to hear that it works now! If you encounter any more issues or have further questions, feel free to ask. Happy coding!
