### ISSUE TITLE
still embedding projector

### ISSUE THREAD

**Issue by yu123596** [ultralytics/ultralytics#14806]
@glenn-jocher I had try your example code to get tensorboard embedding projector but it didn't work.
Sorry, the last question could not reopen so I open a new same question.
Could you check my code please?  I was expect to see the result like this to check my train data and val data rationality.
(MNIST with embedding projector) 
![messageImage_1722321084988](https://github.com/user-attachments/assets/416369df-68b3-48cb-a760-9d773a70bc99)

My custom classification have two classes. I use get_filelist function to get all image path in train file. Then turn image to tensor and input to model. 

```
from ultralytics import YOLO
import torch
import os
import cv2
def get_filelist(dir, Filelist):
    newDir = dir
    if os.path.isfile(dir):
        Filelist.append(dir)
    elif os.path.isdir(dir):
        for s in os.listdir(dir):
            newDir=os.path.join(dir,s)
            get_filelist(newDir, Filelist)
    return Filelist

if __name__ == '__main__':
    model = YOLO("./runs/classify/NXPD_train/train6/weights/best.pt")
    img_dir = "./datasets/NX-DP_ver2/train/"
    img_list = get_filelist(img_dir,[])
    for img_path in img_list:
        images = torch.tensor((cv2.imread(img_path)))
        with torch.no_grad():
            model.eval()
            embeddings = model.predict(images, embed=True)
```

Final I get this error message after the "Starting training for 100 epochs...". It should not be start training right?

> File ".....\lib\site-packages\torch\autograd\graph.py", line 744, in _engine_run_backward
>     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
> RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn)

Also if I want to get a result like the MNIST with embedding projector, the best model must to go through training process again? Thank you!

_Originally posted by @yu123596 in https://github.com/ultralytics/ultralytics/issues/11198#issuecomment-2257596932_

**Comment by Y-T-G** [comment]
You don't need this.

```
with torch.no_grad():
            model.eval()
```

And it should be `model.embed(image)`

**Comment by yu123596** [comment]
@Y-T-G It's work. I can transform image to image embedding. After that I will try to input tensorflow projector. Thanks a lot.
