### ISSUE TITLE
Calibration data for quantization int8

### ISSUE THREAD

**Issue by Egorundel** [ultralytics/ultralytics#14809]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

What is this calibration data? What kind of data is this exactly? What should they look like? What should the YAML file look like, in which the calibration data set should be written.

```cmd
yolo export format="engine" int8=True data="coco.yaml"
```

**Comment by Y-T-G** [comment]
Just like a normal dataset for YOLO. There's no special requirement for calibration data.

https://github.com/ultralytics/ultralytics/blob/f955fedb7f7dbf92bd062a89577d692eea53e9ce/docs/en/integrations/tensorrt.md

**Comment by Egorundel** [comment]
@Y-T-G And I have an ONNX model with a dynamic batch size and an NMS module at the output, can you tell me how to create calibration_data.cache correctly, taking into account the characteristics of my model?

input:
![Screenshot from 2024-07-30 13-22-57](https://github.com/user-attachments/assets/82bdda82-b9f6-47ba-8412-b1df925d1959)

output:
![Screenshot from 2024-07-30 13-23-07](https://github.com/user-attachments/assets/e9a09441-4bac-4ddf-b55f-f1a8128bde89)

**Comment by Y-T-G** [comment]
I think the calibration process would be the same. I already provided you the code for calibration that's used in ultralytics.

**Comment by Egorundel** [comment]
@Y-T-G Does this affect the calibration in any way?

![2024_07_30_0p0_Kleki](https://github.com/user-attachments/assets/6bda5336-d8ba-4d14-9c71-c7511ef462c5)

**Comment by Y-T-G** [comment]
No

**Comment by Y-T-G** [comment]
How are you running the export? You will have to use your own custom model which can't be used directly. You will have to manually write the code.

**Comment by Egorundel** [comment]
@Y-T-G O, thanks, I will try

**Comment by Y-T-G** [comment]
https://github.com/ultralytics/ultralytics/blob/7ecab94b291856da88d710d9939277e5b0775178/ultralytics/engine/exporter.py#L733-L734

Also change this to your image dimensions of ONNX

**Comment by Egorundel** [comment]
@Y-T-G Thanks, it works for me!
