### ISSUE TITLE
Can not run multiple models with multi processing

### ISSUE THREAD

**Issue by VM8198** [ultralytics/ultralytics#14808]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug
can not initialize model in multiprocessing. but it works with threading.

### Environment

OS                  Linux-5.15.0-117-generic-x86_64-with-glibc2.29
Environment         Linux
Python              3.8.2
Install             git
RAM                 31.25 GB
CPU                 Intel Core(TM) i7-7700 3.60GHz
CUDA                None

matplotlib          ✅ 3.7.4>=3.3.0
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.29.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.1.2>=1.8.0
torchvision         ✅ 0.16.2>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.7
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0

### Minimal Reproducible Example

```
from ultralytics import YOLO
import multiprocessing
import threading
        
class Test:
    def function1(self):
        print("calling function2 now")
        model1 = YOLO("yolov8n.pt")
        p = multiprocessing.Process(target=Test2().function2, args=(1,))
        p.start()
        
        # threading.Thread(target=Test2().function2, args=(1,)).start()
        

class Test2:
    def function2(self, arg1):
        print("initializing model now", arg1)
        model = YOLO("yolov8n.pt")
        print("model initialized", arg1)
        return 2

if __name__ == "__main__":
    t = Test()
    t.function1()
    
```

### Additional

In my project, I have two classes where I want to use multiprocessing to initialize models in both classes for inference. However, I'm encountering an issue: when I use multiprocessing, I can't initialize the model in the second class. On the other hand, it works when I use threading. After doing some research, I found that YOLO models aren't pickleable, which might be why they aren't initializing in the second class. @glenn-jocher Could you confirm if this is the issue or if something else is causing the problem? I need to use multiprocessing due to project requirements, so please let me know how I can achieve this using multiprocessing.

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
Add `p.join()`

**Comment by VM8198** [comment]
no @Y-T-G adding `p.join()` did not work.

**Comment by VM8198** [comment]
Got it, @Y-T-G but using `p.join()` will wait for it's child process to complete. I want both processes running simultaneously without waiting for other processes.

**Comment by Y-T-G** [comment]
I guess you don't need `join()` for it to work. But you need to wait some time to see the output.

**Comment by VM8198** [comment]
@Y-T-G  the above code snipped I've provided is just an example for better understanding. I've used it in my current project and I've already tried the solutions you provided but none of them working. That's why I've posted the question here. 
thanks for your time.

**Comment by Y-T-G** [comment]
How are you checking whether it's working besides printing? Can you save the prediction output in the second process and see if it saves when you launch the second one?

**Comment by VM8198** [comment]
Yes, that's how I checked. Inference is not working anyhow.

**Comment by Y-T-G** [comment]
It works fine for me. The exact same code as your post.

**Comment by rebelmachina** [comment]
@VM8198 to me it looks like a CPU bound task, in that case using threads won't help much, but you'll have to use processes.

I tried your minimal example and it works. Can you describe more how you use it? maybe try updating `ultralytics` package too (`pip install -U ultralytics`)
