### ISSUE TITLE
Visualize feature not yet supported

### ISSUE THREAD

**Issue by gjgjos** [ultralytics/ultralytics#1481]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello.

I am trying to visualize features during predict, but it failed with error message 'visualize feature not yet supported'

yolo detect predict model=./best.pt source="3.jpg" visualize=True

YOLOv5 supported visualize feature function, but does YOLOv8 not support? Then, how to visualize features?

**Comment by compVisual** [comment]
It works with show = True when the source is a video. If your source is an image, show only allows you to visualice it during a second or so. You could try save = True an you can see the path where is saved on the terminal. Usually it is inside a folder called runs.

**Comment by gjgjos** [comment]
Thank you for quick response! I will try right now

**Comment by pderrenger** [comment]
@gjgjos you're welcome! Feel free to reach out if you have further questions or need assistance. Good luck with your visualization, and happy coding!

**Comment by glenn-jocher** [comment]
@pderrenger you're welcome! If you need more help or have additional questions, don't hesitate to ask. Best of luck with your work! 🚀
