### ISSUE TITLE
yolov8n-pose doesn't detect pose keypoints

### ISSUE THREAD

**Issue by Mielpops05** [ultralytics/ultralytics#14811]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Other

### Bug

When using the yolov8n-pose model to detect poses, an implausibly large number of people are detected in the image. Instead of one person, the model detects many objects, and their key points do not coincide with the real ones. 
This is an output:
Downloading https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8n-pose.pt to 'yolov8n-pose.pt'...
100%|██████████| 6.52M/6.52M [00:02<00:00, 3.05MB/s]

0: 640x448 55 persons, 398.7ms
Speed: 4.0ms preprocess, 398.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 448)
Сохранено изображение с результатами: C:/Users/piurk/PycharmProjects/yolo/im_pose_detected.jpg

Process finished with exit code 0

And images before and after running my code:
![im](https://github.com/user-attachments/assets/c8bcbe99-82ec-4b30-b4b1-02feb9fec9ad)
![im_pose_detected](https://github.com/user-attachments/assets/b4c30ec3-7e69-4bf8-84b5-d625afa064c2)

### Environment

Ultralytics YOLOv8.2.69 🚀 Python-3.12.4 torch-2.4.0+cpu CPU (13th Gen Intel Core(TM) i5-13500H)
Setup complete ✅ (16 CPUs, 15.7 GB RAM, 72.1/120.0 GB disk)

System Information:
OS: Windows 11
Python version: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]

Installed Library Versions:
Ultralytics: 8.2.68
PyTorch: 2.4.0+cpu
NumPy: 1.26.4
OpenCV: 4.10.0
Pillow: 10.4.0

### Minimal Reproducible Example

from ultralytics import YOLO
import cv2
import numpy as np
import os

model = YOLO('yolov8n-pose.pt')

colors = {
    'white': (255, 255, 255),
    'red': (0, 0, 255),
    'blue': (255, 0, 0)
}

def draw_skeleton(image, keypoints, confs, pairs, color):
    for (start, end) in pairs:
        if confs[start] > 0.5 and confs[end] > 0.5:
            x1, y1 = int(keypoints[start][0]), int(keypoints[start][1])
            x2, y2 = int(keypoints[end][0]), int(keypoints[end][1])
            if (x1, y1) != (0, 0) and (x2, y2) != (0, 0):  
                cv2.line(image, (x1, y1), (x2, y2), color, 2)

def process_image(image_path):
    image = cv2.imread(image_path)
    if image is None:
        print("Ошибка: не удалось загрузить изображение")
        
    results = model(image)[0]

    
    if hasattr(results, 'boxes') and hasattr(results.boxes, 'cls') and len(results.boxes.cls) > 0:
        classes_names = results.names
        classes = results.boxes.cls.cpu().numpy()
        boxes = results.boxes.xyxy.cpu().numpy().astype(np.int32)

        if results.keypoints:
            keypoints = results.keypoints.data.cpu().numpy()
            confs = results.keypoints.conf.cpu().numpy()

            for i, (class_id, box, kp, conf) in enumerate(zip(classes, boxes, keypoints, confs)):
                draw_box = False
                if draw_box:
                    class_name = classes_names[int(class_id)]
                    color = colors['white']
                    x1, y1, x2, y2 = box
                    cv2.rectangle(image, (x1, y1), (x2, y2), color, 2)
                    cv2.putText(image, class_name, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

                
                for j, (point, point_conf) in enumerate(zip(kp, conf)):
                    if point_conf > 0.5: 
                        x, y = int(point[0]), int(point[1])
                        if (x, y) != (0, 0):  
                            cv2.circle(image, (x, y), 5, colors['blue'], -1)
                            cv2.putText(image, str(j), (x + 5, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, colors['blue'], 2)

                draw_skeleton(image, kp, conf, [(5, 7), (7, 9), (6, 8), (8, 10)], colors['white']) 
                draw_skeleton(image, kp, conf, [(11, 13), (13, 15), (12, 14), (14, 16)], colors['red'])  
                draw_skeleton(image, kp, conf, [(5, 11), (6, 12)], colors['blue'])  

   
    output_path = os.path.splitext(image_path)[0] + "_pose_detected.jpg"
    cv2.imwrite(output_path, image)
    print(f"Сохранено изображение с результатами: {output_path}")

    cv2.imshow('YOLOv8-Pose Detection', image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

image_path = 'C:/Users/piurk/PycharmProjects/yolo/im.jpg'
process_image(image_path)

### Additional

I also tried using other versions of the model (yolov8s-pose, yolov8m-pose, yolov8l-pose), but they gave the same error, and the yolov8x-pose and yolov8x-pose-p6 versions did not find anything on the image at all

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Mielpops05** [comment]
#MRE

from ultralytics import YOLO
import cv2
import numpy as np
import os

model = YOLO('yolov8n-pose.pt')

colors = {
    'white': (255, 255, 255),
    'red': (0, 0, 255),
    'blue': (255, 0, 0)
}

def draw_skeleton(image, keypoints, confs, pairs, color):
    for (start, end) in pairs:
        if confs[start] > 0.5 and confs[end] > 0.5:
            x1, y1 = int(keypoints[start][0]), int(keypoints[start][1])
            x2, y2 = int(keypoints[end][0]), int(keypoints[end][1])
            if (x1, y1) != (0, 0) and (x2, y2) != (0, 0):  
                cv2.line(image, (x1, y1), (x2, y2), color, 2)

def process_image(image_path):
    image = cv2.imread(image_path)
    if image is None:
        print("Ошибка: не удалось загрузить изображение")
        return

    results = model(image)[0]

    if hasattr(results, 'boxes') and hasattr(results.boxes, 'cls') and len(results.boxes.cls) > 0:
        classes_names = results.names
        classes = results.boxes.cls.cpu().numpy()
        boxes = results.boxes.xyxy.cpu().numpy().astype(np.int32)

        if results.keypoints:
            keypoints = results.keypoints.data.cpu().numpy()
            confs = results.keypoints.conf.cpu().numpy()

            for i, (class_id, box, kp, conf) in enumerate(zip(classes, boxes, keypoints, confs)):
                draw_box = False
                if draw_box:
                    class_name = classes_names[int(class_id)]
                    color = colors['white']
                    x1, y1, x2, y2 = box
                    cv2.rectangle(image, (x1, y1), (x2, y2), color, 2)
                    cv2.putText(image, class_name, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

                for j, (point, point_conf) in enumerate(zip(kp, conf)):
                    if point_conf > 0.5:  
                        x, y = int(point[0]), int(point[1])
                        if (x, y) != (0, 0): 
                            cv2.circle(image, (x, y), 5, colors['blue'], -1)
                            cv2.putText(image, str(j), (x + 5, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, colors['blue'], 2)

                draw_skeleton(image, kp, conf, [(5, 7), (7, 9), (6, 8), (8, 10)], colors['white'])  
                draw_skeleton(image, kp, conf, [(11, 13), (13, 15), (12, 14), (14, 16)], colors['red'])  
                draw_skeleton(image, kp, conf, [(5, 11), (6, 12)], colors['blue'])  # Тело

    output_path = os.path.splitext(image_path)[0] + "_pose_detected.jpg"
    cv2.imwrite(output_path, image)
    print(f"Сохранено изображение с результатами: {output_path}")

    cv2.imshow('YOLOv8-Pose Detection', image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

image_path = 'C:/Users/piurk/PycharmProjects/yolo/im.jpg'
process_image(image_path)

**Comment by Y-T-G** [comment]
PyTorch bug https://github.com/ultralytics/ultralytics/issues/14776
