### ISSUE TITLE
Adding attention module

### ISSUE THREAD

**Issue by gjgjos** [ultralytics/ultralytics#1482]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello~

I try to add attention module (CBAM) to existing current yolov8.
So I changed .yaml file like this.
`# YOLOv8.0s backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2 #ch_out,kernel,stride
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, CBAM, [128]]  
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, CBAM, [256]]  
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, CBAM, [512]]  
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, CBAM, [1024]]  
  - [-1, 1, SPPF, [1024, 5]]  # 9`
  
Also, I add CBAM class in modules.py and tasks.py within C:\Users\Desktop\yolov8 folder.

But error message says I have to add CBAM class in C:\ProgramData\Anaconda3\envs\tfgpu\lib\site-packages\ultralytics\nn\modules.py and C:\ProgramData\Anaconda3\envs\tfgpu\lib\site-packages\ultralytics\nn\tasks.py

When I use YOLOv5, I just changed function in Desktop path and run successfully directly even when I use same Anaconda. 
Is it right to change function in Anaconda folder instead of desktop folder?

When I changed function in Anaconda path, it runs succesfully!

**Comment by glenn-jocher** [comment]
@gjgjos you can git clone and pip install in debug mode to modify git files, i.e. see Colab example in Appendix:

https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb
```
# Git clone install (for development)
!git clone https://github.com/ultralytics/ultralytics -b main
%pip install -qe ultralytics
```
