### ISSUE TITLE
Changing YOLOv8 Weights and Validating 

### ISSUE THREAD

**Issue by ri2658** [ultralytics/ultralytics#14826]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm trying to validate a model after changing some parameters of interest. I'm using the following code structure to do so. This code should compile and run. 

```python 
model = YOLO('/path/to/best.pt')

with torch.no_grad():
    for i, weight in enumerate(suggested_weights):
        model.model.model[-2].cv2.conv.weight[channel, i, 0, 0] = weight # FYI: Optuna's trial.suggest_float() is used to suggest weights

print(model.model.model[-2].cv2.conv.weight[channel, :, 0, 0]) # Point A

metrics = model.val(data='/path/to/data.yaml',  
                    save_json=True,
                    conf=0.10,
                    max_det=1)

print(model.model.model[-2].cv2.conv.weight[channel, :, 0, 0]) # Point B
```

As expected, the weight change can be verified at Point A. 

However, after validating (Point B), the model seemingly reverts to its original weights. I think that while validating, it used a previous cache that loaded in the unchanged weights (is that correct?)

A solution that I am thinking is to export the model immediately after Point A, I export the model's weights and use those new weights to define the model variable, then validate the model with that.
I feel like there is a more efficient solution to this problem since exporting the model each time feels excessive.

Any solutions, code, or resources would be appreciated!

### Additional

I admit that I am quite new to using to YOLOv8, I ask of you to bear with me.

**Comment by Y-T-G** [comment]
Try this before the val:
```python
del model.ckpt["ema"]
model.ckpt.update(dict(model=model.model))
```

**Comment by ri2658** [comment]
Unfortunately, the issue still persists. For reference, here's my updated code.
```python
model = YOLO('/path/to/best.pt')

with torch.no_grad():
    for i, weight in enumerate(suggested_weights):
        model.model.model[-2].cv2.conv.weight[channel, i, 0, 0] = weight # FYI: Optuna's trial.suggest_float() is used to suggest weights

print(model.model.model[-2].cv2.conv.weight[channel, :, 0, 0]) # Point A

# Added lines
del model.ckpt["ema"] 
model.ckpt.update(dict(model=model.model))

metrics = model.val(data='/path/to/data.yaml',  
                    save_json=True,
                    conf=0.10,
                    max_det=1)

print(model.model.model[-2].cv2.conv.weight[channel, :, 0, 0]) # Point B
```

Point A shows the updated weights, whereas Point B shows reverted weights.

**Comment by Y-T-G** [comment]
It could be related to fusing that's done before val.

You could override the method to not perform fusing:
```python
def fuse(self, *args, **kwargs):
    return self

model.model.fuse = fuse.__get__(model.model, type(model.model))
```

**Comment by ri2658** [comment]
Can you please clarify where to override the method? I'm assuming it's somewhere inside the Ultralytics repository, which file is the fuse function located?

**Comment by Y-T-G** [comment]
> Can you please clarify where to override the method? I'm assuming it's somewhere inside the Ultralytics repository, which file is the fuse function located?

You just paste that code before you do the val

**Comment by ri2658** [comment]
Oh, ok. Sorry for the misunderstanding. It worked perfectly.

```python
model = YOLO('/path/to/best.pt')

with torch.no_grad():
    for i, weight in enumerate(suggested_weights):
        model.model.model[-2].cv2.conv.weight[channel, i, 0, 0] = weight # FYI: Optuna's trial.suggest_float() is used to suggest weights

print(model.model.model[-2].cv2.conv.weight[channel, :, 0, 0])

# Added lines
def fuse(self, *args, **kwargs):
            return self
model.model.fuse = fuse.__get__(model.model, type(model.model))

metrics = model.val(data='/path/to/data.yaml',  
                    save_json=True,
                    conf=0.10,
                    max_det=1)

print(model.model.model[-2].cv2.conv.weight[channel, :, 0, 0])
```
I will be closing the issue for now.

**Comment by pderrenger** [comment]
@ri2658 great to hear that it worked for you! If you encounter any further issues or have more questions, feel free to reach out. Happy coding!
