### ISSUE TITLE
track error

### ISSUE THREAD

**Issue by peanutpaste** [ultralytics/ultralytics#14821]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In a video with dense small objects, I can predict the objects normally using model.predict. But when I use model.track, only the first frame of multiple objects are correctly identified, and only a few objects in subsequent frames are identified. Please help, thx

results = model.track(file_path, show=True)
results = model.predict(file_path, show=True)

**Comment by Y-T-G** [comment]
Lower the threshold:

https://github.com/ultralytics/ultralytics/blob/80f699ae218f08d7f7846a7991c014456a81ae96/ultralytics/cfg/trackers/botsort.yaml#L7
