### ISSUE TITLE
How to recreate precision curves from raw metrics?

### ISSUE THREAD

**Issue by buzzysin** [ultralytics/ultralytics#1483]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How do I retreive the metrics that produced this and similar graphs? Is it possible, or do I need to set up a logger (or add a hook into the Comet logger) to capture the data while training? See below:

![F1_curve](https://user-images.githubusercontent.com/41271986/226110642-3e9684ba-2f98-4f37-8d4f-e46ced65b3ee.png)

I'm unsatisfied with the way the graphs look in my project poster, and would like to recreate them,using the raw data, but I can't seem to find it.

**Comment by glenn-jocher** [comment]
@buzzysin these are created after training is complete or when validating. See https://docs.ultralytics.com/modes/val

Val results may contain this data.

**Comment by buzzysin** [comment]
Thanks, I *think* I got what I wanted using `model.val(save_json=True)` in `predictions.json` and the data returned by this method.

**Comment by glenn-jocher** [comment]
I think you want val Results:

<img width="1603" alt="Screenshot 2023-03-18 at 16 58 17" src="https://user-images.githubusercontent.com/26833433/226116979-a7695039-6a84-4654-8dbe-4dc3be590fd8.png">

**Comment by buzzysin** [comment]
In essence, I'm looking for the data produced in `ultralytics.yolo.utils.metrics` by the `ap_per_class` method.

**Comment by pderrenger** [comment]
@buzzysin understood! If you need the full range, the table produced by `val` should contain the detailed metrics you're looking for, and that can be a helpful output for your project. If you need anything else, feel free to ask! 😊
