### ISSUE TITLE
track: Unable to specify the GPU used

### ISSUE THREAD

**Issue by JustChenk** [ultralytics/ultralytics#14833]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Whether the trajectory tracking algorithm can specify the GPU to use

The parameter device=gpu（defined 1） has been set, but the model is still loaded at GPU：0

![image](https://github.com/user-attachments/assets/7e79c81d-4b64-4999-800d-8b9077956777)

![image](https://github.com/user-attachments/assets/be19ac2f-2805-435a-a8f0-75338bce44ab)

![image](https://github.com/user-attachments/assets/02f86aa5-c336-44af-a4be-6f9370ea5194)

### Environment

ultralytics 8.2.36

### Minimal Reproducible Example

"""
        res = self.model.track(im, tracker="bytetrack.yaml", persist=True, imgsz=self.img_size, conf=self.conf,
                               iou=self.iou, device=self.device, verbose=False)
"""

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@JustChenk thank you for reporting this issue. It appears that specifying the GPU using the `device` parameter is not functioning as expected. Please ensure you are using the latest version of the Ultralytics package, as updates often include bug fixes and improvements. If the issue persists in the latest version, we would appreciate it if you could submit a PR with your proposed fix. This will help us address the problem more efficiently. Thank you for your contribution to improving Ultralytics YOLO.

**Comment by Y-T-G** [comment]
This ought to be supported but it seems like`select_device` forces GPU 0.

@glenn-jocher @Laughing-q

**Comment by JustChenk** [comment]
`from ultralytics import YOLO
import logging
from myutils.public_logger import logger


def tracker_infer(weight_path):
    model = YOLO(weight_path)

    def process(frame):
        res = model.track(frame, tracker="bytetrack.yaml", device=1, verbose=False)
        # logger.info(f"testInfer.py_tracker_infer(weight_path) 29: os.environ: {os.environ['gpu']}")

        detected_boxes = res[0].boxes
        pred_boxes = []

        for box in detected_boxes:
            xyxy = box.xyxy.cpu()
            confidence = box.conf.cpu().item()
            class_id = box.cls  # get the class id
            class_id_cpu = class_id.cpu()  # move the value to CPU
            class_id_int = int(class_id_cpu.item())  # convert to integer
            if class_id_int != 0:
                continue
            x1, y1, x2, y2 = xyxy[0].numpy()
            import logging
            # 增加NoneType情况处理步骤
            if box.id is None:
                logging.info(f"test.testInfer tracker_infer(weight_path): box.id: {box.id}")
                continue
            else:
                track_id = int(box.id.cpu().item())

            pred_boxes.append(
                (x1, y1, x2, y2,, confidence, track_id))

        return pred_boxes

    return process


v8Tracker = tracker_infer("weights/yolov8n.pt")
`

**Comment by JustChenk** [comment]
```
from ultralytics import YOLO
import logging
from myutils.public_logger import logger


def tracker_infer(weight_path):
    model = YOLO(weight_path)

    def process(frame):
        res = model.track(frame, tracker="bytetrack.yaml", device=1, verbose=False)
        # logger.info(f"testInfer.py_tracker_infer(weight_path) 29: os.environ: {os.environ['gpu']}")

        detected_boxes = res[0].boxes
        pred_boxes = []

        for box in detected_boxes:
            xyxy = box.xyxy.cpu()
            confidence = box.conf.cpu().item()
            class_id = box.cls  # get the class id
            class_id_cpu = class_id.cpu()  # move the value to CPU
            class_id_int = int(class_id_cpu.item())  # convert to integer
            if class_id_int != 0:
                continue
            x1, y1, x2, y2 = xyxy[0].numpy()
            import logging
            if box.id is None:
                logging.info(f"test.testInfer tracker_infer(weight_path): box.id: {box.id}")
                continue
            else:
                track_id = int(box.id.cpu().item())

            pred_boxes.append(
                (x1, y1, x2, y2, class_id_int, confidence, track_id))

        return pred_boxes

    return process


v8Tracker = tracker_infer("weights/yolov8n.pt")
```
Even if you specify device=1 directly, the model will be loaded to the GPU during the subsequent call

**Comment by JustChenk** [comment]
If you do not import the object from the object, you can specify the GPU to be used. Just like the code below
```
import cv2
from ultralytics import YOLO

DETECTOR_PATH = 'weights/yolov8n.pt'

# Load the YOLOv8 model
model = YOLO(DETECTOR_PATH)
# Open the video file
video_path = "videos/run01.mp4"


def tracker_infer(weight_path):
    model = YOLO(weight_path)

    def process(frame):
        res = model.track(frame, tracker="bytetrack.yaml", device=1, verbose=False)
        # return res
        detected_boxes = res[0].boxes
        pred_boxes = []

        for box in detected_boxes:
            xyxy = box.xyxy.cpu()
            confidence = box.conf.cpu().item()
            class_id = box.cls  # get the class id
            class_id_cpu = class_id.cpu()  # move the value to CPU
            class_id_int = int(class_id_cpu.item())  # convert to integer
            if class_id_int != 0:
                continue
            x1, y1, x2, y2 = xyxy[0].numpy()

            import logging
            if box.id is None:
                logging.info(f"box.id: {box.id}")
                continue
            else:
                track_id = int(box.id.cpu().item())

            pred_boxes.append(
                (x1, y1, x2, y2, class_id_int, confidence, track_id))

        # return pred_boxes
        return res, pred_boxes
    return process

v8Tracker = tracker_infer(DETECTOR_PATH)


cap = cv2.VideoCapture(video_path)

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 tracking on the frame, persisting tracks between frames
        results, _ = v8Tracker(frame)

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Display the annotated frame
        cv2.imshow("YOLOv8 Tracking", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()
```

**Comment by Y-T-G** [comment]
What does this print?

```python
from ultralytics.utils.torch_utils import select_device
print(select_device(device="1"))
```

**Comment by JustChenk** [comment]
Some of the code has been modified, and the result is shown in the following figure.
This seems a little strange
···
def tracker_infer(weight_path):
    model = YOLO(weight_path)

    def process(frame):
        res = model.track(frame, tracker="bytetrack.yaml", device=1, verbose=False)
        # logger.info(f"testInfer.py_tracker_infer(weight_path) 29: os.environ: {os.environ['gpu']}")
        from ultralytics.utils.torch_utils import select_device
        print(select_device(device="1"))
···
![image](https://github.com/user-attachments/assets/84586c02-b0b9-4a7a-bc01-1171723b1567)

**Comment by JustChenk** [comment]
And the CUDA_VISIBLE_DEVICE has been set up with the following code
···
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3,4,5,6,7"
···

**Comment by Y-T-G** [comment]
You can use this. But add this before you load the model. Not inside the function.

```python
import ultralytics.utils.torch_utils import torch_utils
def select_device(*args, **kwargs): return torch.device(device)
torch_utils.select_device = select_device
```

**Comment by Y-T-G** [comment]
You can use this. But add this before you load the model. Not inside the function. And use `device="cuda:1"` in your model.track.

```python
import ultralytics.utils.torch_utils import torch_utils
import torch
def select_device(device, *args, **kwargs): return torch.device(device)
torch_utils.select_device = select_device
```

**Comment by JustChenk** [comment]
> You can use this. But add this before you load the model. Not inside the function. And use `device="cuda:1"` in your model.track.
> 
> ```python
> import ultralytics.utils.torch_utils import torch_utils
> import torch
> def select_device(device, *args, **kwargs): return torch.device(device)
> torch_utils.select_device = select_device
> ```

Thank you ,but this didn't solve the problem.
After modifying the code, GPU0 is still loaded
![image](https://github.com/user-attachments/assets/bdd0b060-f7d3-48fd-9b2e-f6d05b7163ad)

**Comment by Y-T-G** [comment]
`import ultralytics.utils.torch_utils as torch_utils`

**Comment by Burhan-Q** [comment]
What about trying `device = torch.device("cuda:1")` mentioned on https://github.com/ultralytics/ultralytics/issues/3953#issuecomment-1821246928

**Comment by JustChenk** [comment]
@Burhan-Q  Thanks bro,I modified the code as follows and successfully loaded the model to the specified GPU.

"""
def tracker_infer(weight_path):
    model = YOLO(weight_path)

    def process(frame):
        res = model.track(frame, tracker="bytetrack.yaml", device=torch.device(f"cuda:{gpu}"), verbose=False)
"""

@Y-T-G Thanks for the suggestion too, bro, the problem has been solved, and it looks like  need to specify which GPU to use in a more secure standard way

**Comment by Burhan-Q** [comment]
Glad it helped @JustChenk Funny enough, I just _happened_ to have seen that someone else had run into this before
