### ISSUE TITLE
Error data path for YOLO.train()

### ISSUE THREAD

**Issue by wjcper2008** [ultralytics/ultralytics#1484]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

![image](https://user-images.githubusercontent.com/14107030/226115777-22ab4f6a-29bc-4f53-a029-b62bda5a209d.png)

### Environment

- Ultralytics YOLOv8.0.54 🚀 Python-3.8.13 torch-1.12.1
- OS: Ubuntu 20.04
- Python: 3.8

### Minimal Reproducible Example

There is missing path for the train. It isn't the current path but the root (home) path .... How can I address this issue. Thanks!

```
from ultralytics import YOLO
model = YOLO('yolov8n-cls.pt')
model.train(data='../datasets/mnist160/mnist160.yaml', epochs=100, imgsz=64)
```
If I use the following code, the 'mnist160.zip' is downloading in my home/datasets/mnist160.zip. NOT the current project path. 

```
from ultralytics import YOLO
model = YOLO('yolov8n-cls.pt')
model.train(data='mnist160', epochs=100, imgsz=64)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wjcper2008 dataset paths is an Ultralytics setting. You can see your settings with `yolo settings` and modify the settings YAML accordingly if you want.

**Comment by cheesent** [comment]
#### I have the same problem as @wjcper2008 while using `yolov8n-cls.pt`

![Captura desde 2023-03-23 11-36-50](https://user-images.githubusercontent.com/101491319/227291985-3423aa93-dfa5-4e9d-b761-8e70b9e811ee.png)


I did change the settings with `yolo settings` and I still got the error.

![Captura desde 2023-03-23 11-18-36](https://user-images.githubusercontent.com/101491319/227286251-bd334137-6251-461e-a55d-9cb8bd023944.png)

My `config.yaml` looks like this:
![Captura desde 2023-03-23 11-25-31](https://user-images.githubusercontent.com/101491319/227287542-87efd076-6139-4804-9681-c3b1bc4f7b41.png)


But the problem doesn't appear when I change the model to yolov8n.pt, seems to be for classification, 

Perhaps It works different with classification and I don't know how to use it, or it's not working 100%? I'm happy to receive any corrections or clarifications I'm kind of a noob.

##### Everything fine using `detect`
![Captura desde 2023-03-23 11-27-16](https://user-images.githubusercontent.com/101491319/227288501-ff9fdbde-f964-48a0-b414-f546c0501c21.png)
![Captura desde 2023-03-23 11-29-13](https://user-images.githubusercontent.com/101491319/227288725-31fc1492-5ea4-4e55-a126-892ac2577988.png)

### Setup
I'm using google colab with a custom dataset
`Ultralytics YOLOv8.0.55 🚀 Python-3.9.16 torch-1.13.1+cu116 CUDA:0 (Tesla T4, 15102MiB)`

**Comment by glenn-jocher** [comment]
@cheesent classification datasets do not require YAML files, just point to your dataset directory, i.e. `data=path/to/dir`

For Classification training examples see https://docs.ultralytics.com/tasks/classify
