### ISSUE TITLE
How to specify device in Python?

### ISSUE THREAD

**Issue by tjasmin111** [ultralytics/ultralytics#14859]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

We can define devices in CLI like this:
`yolo val detect data=coco.yaml device=0,1`

But how to specify the devices when using python?

`model = YOLO("yolov8n.pt")`

**Comment by pderrenger** [comment]
@tjasmin111 to specify the device in Python, you can pass the `device` argument directly to the `train` method or other relevant methods. For example:

```python
model = YOLO("yolov8n.pt")
results = model.train(data="coco.yaml", device="0,1")
```

This will ensure that the model uses the specified GPUs for training. If you encounter any issues, please ensure you are using the latest version of the Ultralytics package. For more details, you can refer to the [Ultralytics documentation](https://docs.ultralytics.com/modes/train/).

**Comment by Skillnoob** [comment]
https://docs.ultralytics.com/modes/train/#multi-gpu-training
