### ISSUE TITLE
Yolov8 Export inference results 

### ISSUE THREAD

**Issue by adriengoleb** [ultralytics/ultralytics#14854]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

After obtaining my inference results from my YoloV8 for a folder containing a hundred images, I want to export the results like displayed in the terminal as  a csv file.

<img width="436" alt="terminal" src="https://github.com/user-attachments/assets/e1935db2-e89b-477b-bb75-da5c8049365b">

can you help me define how to iterate on the "results" list variable to obtain the same result as in the terminal ? I want a csv file in which each line correpond to an image.

**Comment by pderrenger** [comment]
@adriengoleb hello,

To export your YOLOv8 inference results to a CSV file, you can iterate over the `results` list and extract the relevant information for each image. Each result object contains attributes like bounding boxes, class labels, and confidence scores that you can write to a CSV file. 

Ensure you are using the latest version of the Ultralytics package to avoid any potential issues. If you encounter any problems, please let us know.

For more detailed guidance, you can refer to our documentation: https://docs.ultralytics.com/guides/view-results-in-terminal/
