### ISSUE TITLE
Facing issue to understand time difference 

### ISSUE THREAD

**Issue by sourabCV** [ultralytics/ultralytics#14855]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

simple code :
```
import time
import sys
import cv2
from ultralytics import YOLO
pos_model = YOLO('models/yolov8n-pose.onnx', task='pose')

cap = cv2.VideoCapture(
    'rtsp://xxx:xxxx!@0xxxx:1xx77/stream1')

ret, frame = cap.read()

st = time.time()

results = pos_model.predict(
    frame, conf=0.5, iou=0.6 )#, imgsz=640, verbose=False)
print(time.time()-st)
```

Issue :
output showing 
Ultralytics YOLOv8.1.34 🚀 Python-3.11.9 torch-2.0.1+cpu CPU (Intel Xeon Platinum 8370C 2.80GHz)
Setup complete ✅ (64 CPUs, 256.0 GB RAM, 92.6/126.4 GB disk)
Loading models\yolov8n-pose.onnx for ONNX Runtime inference...

0: 640x640 (no detections), 46.5ms
Speed: 60.5ms preprocess, 46.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)
1.9199035167694092

what issue is there 
as per 60.5ms +46.5ms +1.0ms =0.108 sec 
but next line printing 1.91 sec 

### Additional

I am running this code in azure windows vm in cpu

**Comment by Y-T-G** [comment]
First prediction is slower

**Comment by sourabCV** [comment]
No its not for first 
0: 640x640 28 xxxx, 1 xxxx, 1 xxxx, 286.1ms
Speed: 3.0ms preprocess, 286.1ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)
25.154328107833862

0: 640x640 28 xxxx, 1 xxxx, 1 xxxx, 279.5ms
Speed: 5.2ms preprocess, 279.5ms inference, 0.6ms postprocess per image at shape (1, 3, 640, 640)
25.094976663589478

**Comment by sourabCV** [comment]
this work when i used 1 model 
but again facing same issue when I used another model with previous 

I used threading for that 
on every thread its calculating prediction 

code view :
```
#thread function 
def frameInf(frame):
    preprocessed = cust_model.predictor.preprocess([frame])
    output = cust_model.predictor.inference(preprocessed)
    results = cust_model.predictor.postprocess(output, preprocessed, [frame])
    frame = results[0].plot()
    preprocessed = pretrain_model.predictor.preprocess([frame])
    output = pretrain_model.predictor.inference(preprocessed)
    results = pretrain_model.predictor.postprocess(output, preprocessed, [frame])
    frame = results[0].plot()

```

if I hide one model then its working with proper speed 
but with 2 model its taking average 4 sec to complete 1 frame

**Comment by Y-T-G** [comment]
What's the reason foe threading? YOLO already uses threading internally.

**Comment by Y-T-G** [comment]
PyTorch already uses multi-threading.

https://github.com/ultralytics/ultralytics/blob/9ff33d67b6aba970cb675ba9e219ae75907d109f/ultralytics/utils/torch_utils.py#L211

If you want to use the full CPU, you should modify this:
https://github.com/ultralytics/ultralytics/blob/9ff33d67b6aba970cb675ba9e219ae75907d109f/ultralytics/utils/__init__.py#L39

By default it's limited to 8 threads.
