### ISSUE TITLE
Comment description wrong

### ISSUE THREAD

**Issue by dearMOMO** [ultralytics/ultralytics#14863]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

version：ultralytics 8.2.70

The wrong comment caused me to display the color incorrectly when I customized it

File path is: ultralytics/utils/plotting py

283 line comments

> color (tuple, optional): The background color of the rectangle (R, G, B).

Maybe it's (B, G,R).

```

    def box_label(self, box, label="", color=(128, 128, 128), txt_color=(255, 255, 255), rotated=False):
        """
        Draws a bounding box to image with label.

        Args:
            box (tuple): The bounding box coordinates (x1, y1, x2, y2).
            label (str): The text label to be displayed.
            color (tuple, optional): The background color of the rectangle (R, G, B).
            txt_color (tuple, optional): The color of the text (R, G, B).
            rotated (bool, optional): Variable used to check if task is OBB
        """

```
![image](https://github.com/user-attachments/assets/ee33d45d-04ca-481e-a220-21b69dc4b474)

### Environment

version：ultralytics 8.2.70

### Minimal Reproducible Example

code  `ann.box_label(box, label, color=colors(c_idx, bgr=True))`

```
import cv2 as cv
import numpy as np

from ultralytics.utils.plotting import Annotator, colors

names = {  # (1)!
    0: "person",
    5: "bus",
    11: "stop sign",
}

image = cv.imread("ultralytics/assets/bus.jpg")
ann = Annotator(
    image,
    line_width=None,  # default auto-size
    font_size=None,  # default auto-size
    font="Arial.ttf",  # must be ImageFont compatible
    pil=False,  # use PIL, otherwise uses OpenCV
)

xyxy_boxes = np.array(
    [
        [5, 22.878, 231.27, 804.98, 756.83],  # class-idx x1 y1 x2 y2
        [0, 48.552, 398.56, 245.35, 902.71],
        [0, 669.47, 392.19, 809.72, 877.04],
        [0, 221.52, 405.8, 344.98, 857.54],
        [0, 0, 550.53, 63.01, 873.44],
        [11, 0.0584, 254.46, 32.561, 324.87],
    ]
)

for nb, box in enumerate(xyxy_boxes):
    c_idx, *box = box
    label = f"{str(nb).zfill(2)}:{names.get(int(c_idx))}"
    ann.box_label(box, label, color=colors(c_idx, bgr=True))

image_with_bboxes = ann.result()
```

![image](https://github.com/user-attachments/assets/fcf2e02a-8c08-45be-b02f-9f73b8699b0e)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ambitious-octopus** [comment]
Hey @dearMOMO, thanks for noticing this documentation error. I just created a PR and made you a co-author!
