### ISSUE TITLE
RT-DETR validation - ValueError: x1 must be greater than or equal to x0

### ISSUE THREAD

**Issue by Ayazzia01** [ultralytics/ultralytics#14875]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Val

### Bug

```
thread Thread-5 (plot_images):
Traceback (most recent call last):
  File "/home/ayaz_ubuntu/anaconda3/envs/roboflow/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ayaz_ubuntu/anaconda3/envs/roboflow/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ayaz_ubuntu/anaconda3/envs/roboflow/lib/python3.10/site-packages/ultralytics/utils/plotting.py", line 1028, in plot_images
    annotator.box_label(box, label, color=color, rotated=is_obb)
  File "/home/ayaz_ubuntu/anaconda3/envs/roboflow/lib/python3.10/site-packages/ultralytics/utils/plotting.py", line 297, in box_label
    self.draw.rectangle(box, width=self.lw, outline=color)  # box
  File "/home/ayaz_ubuntu/anaconda3/envs/roboflow/lib/python3.10/site-packages/PIL/ImageDraw.py", line 413, in rectangle
    self.draw.draw_rectangle(xy, ink, 0, width)
ValueError: x1 must be greater than or equal to x0
```

### Environment

Ultralytics YOLOv8.2.70 🚀 Python-3.10.12 torch-2.3.1 CUDA:0 (NVIDIA GeForce RTX 2050, 4096MiB)
Setup complete ✅ (12 CPUs, 7.5 GB RAM, 157.0/1006.9 GB disk)

OS                  Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 7.46 GB
CPU                 AMD Ryzen 5 5600H with Radeon Graphics
CUDA                12.1

numpy               ✅ 1.23.0<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.3.1>=1.8.0
torchvision         ✅ 0.18.1>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

CLI: ```yolo detect val model=runs/detect/rtdetr-l_1024/weights/best.pt data=OCR-5/data.yaml name
=rtdetr-l_1024-val```

### Additional

RT-DETR was trained on same data: OCR-5/data.yaml. The data.yaml file is fine. When training is complete, RT-DETR does provide validation on images in the valid directory. But I cannot run ```yolo detect val``` on the same validation images using the detect command.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@Ayazzia01 Hi! Since RTDETR is a third-party model we integrated, our cli mode recognizes the model weights by the model name, which for RTDETR we need there's `rtdetr` in it.
https://github.com/ultralytics/ultralytics/blob/db4c43bafbed1e1298c4436b8c7e7c6e5b9f3eec/ultralytics/cfg/__init__.py#L788-L791
I'd recommend you to use our python interface to run the model you trained:
```python
from ultralytics import RTDETR

model = RTDETR("runs/detect/rtdetr-l_1024/weights/best.pt")
model.val(data="data.yaml")
```

**Comment by Ayazzia01** [comment]
@Laughing-q This worked thanks

> @Ayazzia01 Hi! Since RTDETR is a series of third-party model we integrated, our cli mode recognizes the model weights by the model name, which for RTDETR we need there's `rtdetr` in it.
> 
> https://github.com/ultralytics/ultralytics/blob/db4c43bafbed1e1298c4436b8c7e7c6e5b9f3eec/ultralytics/cfg/__init__.py#L788-L791
> 
> 
> I'd recommend you to use our python interface to run the model you trained:
> ```python
> from ultralytics import RTDETR
> 
> model = RTDETR("runs/detect/rtdetr-l_1024/weights/best.pt")
> model.val(data="data.yaml")
> ```
