### ISSUE TITLE
About close_mosaic

### ISSUE THREAD

**Issue by super-song-sir** [ultralytics/ultralytics#14886]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I found during training that every time when closing dataloader mosaic in the last ten epochs, the map value significantly increases. why this situation happen? Is it because I haven't trained enough epochs?Or is this considered a normal phenomenon？

**Comment by Skillnoob** [comment]
The training stops training with mosaic images in the last 10 epochs. That is to finalize the training on the actual images the model will see. If you want to disable it you can add the argument `close_mosaic=0` to the train method. See the [train settings](https://docs.ultralytics.com/modes/train/#train-settings).
