### ISSUE TITLE
Mean & std for yolov8 detector and classifier

### ISSUE THREAD

**Issue by raushani2v** [ultralytics/ultralytics#14880]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi @glenn-jocher,

What does the default mean and std used by yolov8 **detector** and **classifier** during training? Does it use mean=(0,0,0), std=(1,1,1) **or** it uses ImageNet mean and std?

**Comment by raushani2v** [comment]
For both classifier as well as detector?

**Comment by Laughing-q** [comment]
@raushani2v exactly!
