### ISSUE TITLE
How to save the train or predict answer in the current folder?

### ISSUE THREAD

**Issue by shenvinci** [ultralytics/ultralytics#1489]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My environment is Mac with miniconda, I use ultralytics in the python. But every time when I run script to train or predict, the answer will save in the `/opt/homebrew/runs/detect/predict` rather than the current folder with my `py` file.
I have saw the API document, but I didn't find any parameter to change the save folder. What should I do?

**Comment by glenn-jocher** [comment]
@shenvinci results are saved to PROJECT/NAME directory. You can use these arguments to control where results are saved. If nothing is passed they are created for you.

https://github.com/ultralytics/ultralytics/blob/701fba47700dee7a6bd8ff4d219eca91adc9d3be/ultralytics/yolo/cfg/default.yaml#L19-L21

**Comment by shenvinci** [comment]
I am sorry to bother you again, but the mode I use is python API like given in the document, where can I load this `yaml` file? Should I use the DetectionPredictor or other things? Or I can use like `YOLO(my_cfg.ymal)`?

**Comment by Laughing-q** [comment]
@shenvinci You can directly pass the args you want to modify. i.e
```python
model = YOLO(yolov8.pt)
model.train(project=..., name=...)
```

**Comment by shenvinci** [comment]
Thanks a lot! That 's work in my project.

**Comment by pderrenger** [comment]
@ChengAoShen you're welcome! Glad to hear it's working for you in your project. If you have any more questions or need further assistance, feel free to ask. Good luck with your project!
