### ISSUE TITLE
i am getting false detections when i am running localy on my virtual env

### ISSUE THREAD

**Issue by Mehdi-Ben-Souda** [ultralytics/ultralytics#14890]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In this picture i get a lot of detections that does not exist . I've used the pip command to download the ultralytics in the python environment . I am using only the CPU and not have cuda installed. 
The code i wrote is simple : 

from ultralytics import YOLO
import ultralytics
ultralytics.checks()

model = YOLO('yolov8n.pt')

results = model(source='https://ultralytics.com/images/zidane.jpg',show=True,conf=0.4,save=True)

![zidane](https://github.com/user-attachments/assets/7e6dcbbc-0511-4755-8253-7ae915c71e23)

### Additional

i get this error with diffrent formats, in the video , the stream from webcam , images .
i saw on youtube videos that once they get the package using pip , they have no issues with the prediction.

**Comment by Y-T-G** [comment]
If you're using PyTorch 2.4.0, it's a bug. You can downgrade.

https://github.com/pytorch/pytorch/issues/131958

**Comment by Mehdi-Ben-Souda** [comment]
@Y-T-G thank you man. it worked i donwgraded to pytorch 2.3.
