### ISSUE TITLE
Yolo Models bug, multiple wrong detections

### ISSUE THREAD

**Issue by MarkoYaacoub** [ultralytics/ultralytics#14908]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hello, 

I'm new in thhis and so I try to use Yolo for objecct detection with this simple code which works on Ubuntu with same photo. 
<img width="461" alt="Screenshot 2024-08-02 103826" src="https://github.com/user-attachments/assets/5a6ea442-22b9-44a6-ae7c-602cce98ebaf">
Can you help me please ? 

### Environment

Ultralytics YOLOv8.2.71 🚀 Python-3.12.2 torch-2.4.0+cpu CPU (13th Gen Intel Core(TM) i9-13900H)
Setup complete ✅ (20 CPUs, 15.6 GB RAM, 264.6/828.7 GB disk)
Windows 11

### Minimal Reproducible Example

from ultralytics import YOLO

import cv2

model = YOLO('../YoloWeights/yolov10n.pt')

results = model("DJITelloPy\photo.jpg", conf = 0.9, show = True)

cv2.waitKey(0)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MarkoYaacoub** [comment]
Solved, needed Pytorch & Cuda install

**Comment by pderrenger** [comment]
@MarkoYaacoub great to hear that you resolved the issue by installing PyTorch and CUDA. If you encounter any further problems or have additional questions, feel free to reach out. For the best performance and latest features, always ensure you're using the latest versions of Ultralytics YOLO and its dependencies. Happy coding!
