### ISSUE TITLE
Analysis for Number of Images used in Training and Drop in RKNN quantization performance

### ISSUE THREAD

**Issue by aayushb-95** [ultralytics/ultralytics#14913]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello Everybody,
I was curious about how many images are required to train the YOLO-V8 Small model. Hence, I did an experiment based on that. Below is the table where I have trained the models on different dataset sizes. I then performed the analysis on my test data and calculated the **Mean IoU** of the test data for both the exported **TFLite-FP32** model and the converted **Quantized INT8 RKNN** model. 
The table below shows the respective values. As expected, the Mean IoU drops for the quantized models. However, after **60K** Images, the quantization performance suffers dramatically. Is there a valid explanation for such a drop in performance?
**Note: All the models are trained with the same hyperparameters.**
<img width="277" alt="Screenshot 2024-08-02 at 14 20 31" src="https://github.com/user-attachments/assets/edd53692-ab0a-4ef5-bf26-89abbf2cff3f">
Any answer on this will be very helpful.
Thanks

**Comment by Y-T-G** [comment]
It seems to be more like the IoU drops dramatically after your original IoU reaches over 0.90

**Comment by aayushb-95** [comment]
Hi @Y-T-G,
That is a good observation. However, it does not explain such a big drop-off in performance.

**Comment by Y-T-G** [comment]
Can you train with 100k images but stop the training when it's close to 90 and before it reaches 90+ and convert and see?

**Comment by aayushb-95** [comment]
Hi @Y-T-G,
Thanks for your message. Can you guide me on how to do that?

**Comment by Y-T-G** [comment]
How are you getting the mean IoU? Does it match the ultralytics metrics?

**Comment by aayushb-95** [comment]
Hi @Y-T-G ,
No. It is a custom program that I use to get the Mean IoU value.

**Comment by Y-T-G** [comment]
Well, then it's going to be difficult to judge that. Is it a segmentation model?

**Comment by aayushb-95** [comment]
Hi @Y-T-G,
It is an Object Detection model.

**Comment by aayushb-95** [comment]
Hi @Y-T-G, @glenn-jocher,
Is there any update on this?

**Comment by Y-T-G** [comment]
This is something custom and since you're not using any ultralytics functionality here to get the results or the converted engine, it's hard to say what's wrong.

**Comment by Y-T-G** [comment]
There's no clear answer for this. It would depend on how "easy" the task is.

**Comment by aayushb-95** [comment]
Hi @Y-T-G,
I am experimenting with detecting cars. So only 1 class.

**Comment by aayushb-95** [comment]
Hi @Y-T-G,
Do you have any insights on this?

**Comment by Y-T-G** [comment]
Like I said, there's no minimum. If you have a variety of cars, it's less likely to overfit. But if you have similar cars, it's more likely to overfit.

**Comment by aayushb-95** [comment]
Hi @Y-T-G,
Thanks for your valuable input.

**Comment by glenn-jocher** [comment]
Closing the loop here: RKNN INT8 export is now supported in Ultralytics starting with `ultralytics>=8.4.59`.

Implementation PR: https://github.com/ultralytics/ultralytics/pull/24656
Platform export UI: https://platform.ultralytics.com/ultralytics/yolo26/yolo26n?tab=export

Python usage now follows the same INT8 calibration-data flow as other export formats, for example:

```python
from ultralytics import YOLO

YOLO("yolo26n.pt").export(format="rknn", name="rk3588", int8=True, data="coco8.yaml")
```

Platform also exposes the RKNN FP16/INT8 export controls directly:

<img width="1306" height="1036" alt="Screenshot 2026-06-01 at 17 31 16" src="https://github.com/user-attachments/assets/553404ae-3048-48f9-9fde-02b200991be2" />
