### ISSUE TITLE
visualize feature not yet supported

### ISSUE THREAD

**Issue by gjgjos** [ultralytics/ultralytics#1491]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

`yolo detect predict model=./runs/detect/weights/best.pt source="3.jpg" visualize=True`
But there is log message _"visualize feature not yet supported"_

I found that in yolov8/ultralytics/nn/tasks.py 
![image](https://user-images.githubusercontent.com/76835329/226153326-78c7378f-1c3c-46db-9128-9b34fa958ac1.png)
TODO: Feature visualization

Then, when will feature visualization function be updated? I want to use feature visualization.

Thank you!

**Comment by glenn-jocher** [comment]
@gjgjos there's no timeframe for this feature currently, but if you'd like to help by submitting a PR that would be great. We simply need to migrate the functionality from YOLOv5, where it already works well.
