### ISSUE TITLE
Can't use yolov10 openvino.

### ISSUE THREAD

**Issue by dhrhkddns** [ultralytics/ultralytics#14927]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I tried to predict the image by using yolov10 openvino.

so when I run this code,

from ultralytics import YOLO

# Load a model
model = YOLO("yolov10_golf_best_openvino_model")  # load a custom trained model

# Run inference on 'golf.jpg' with arguments
model.predict("golf.jpg", save=True, imgsz=640)

It causes this kind of error.

Ultralytics YOLOv8.2.71 � Python-3.9.10 torch-2.4.0+cpu CPU (Intel Xeon E31270 3.40GHz)
Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\segment_detection_combine\memo.py", line 7, in <module>
    model.export(format='openvino', imgsz=640, batch=-1)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\ultraly
tics\engine\model.py", line 743, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\u
tils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\ultraly
tics\engine\exporter.py", line 232, in __call__
    im = torch.zeros(self.args.batch, 3, *self.imgsz).to(self.device)
RuntimeError: Trying to create tensor with negative dimension -1: [-1, 3, 640, 640]
PS C:\Users\Administrator\Desktop\segment_detection_combine> & C:/Users/Administrator/AppData/L
ocal/Programs/Python/Python39/python.exe c:/Users/Administrator/Desktop/segment_detection_combi
ne/memo.py
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define
 task for your model, i.e. 'task=detect', 'segment', 'classify','pose' or 'obb'.
Loading yolov10_golf_best_openvino_model for OpenVINO inference...
Using OpenVINO LATENCY mode for batch=1 inference...
Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\segment_detection_combine\memo.py", line 7, in <module>
    model.predict("golf.jpg", save=True, imgsz=640)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\ultraly
tics\engine\model.py", line 556, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\ultraly
tics\engine\predictor.py", line 303, in setup_model
    self.model = AutoBackend(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\u
tils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\ultraly
tics\nn\autobackend.py", line 213, in __init__
    ov_compiled_model = core.compile_model(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\openvin
o\runtime\ie_api.py", line 543, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Exception from src\inference\src\cpp\core.cpp:107:
Exception from src\inference\src\dev\plugin.cpp:53:
Exception from src\plugins\auto\src\auto_schedule.cpp:441:
[AUTO] compile model failed, CPU:Exception from src\inference\src\dev\plugin.cpp:53:
Check '(std::find(in_idxs.begin(), in_idxs.end(), idx) == in_idxs.end())' failed at src\plugins
\intel_cpu\src\emitters\plugin\x64\jit_emitter.cpp:76:
ov::intel_cpu::jit_emitter: Xmm(0) cannot be input register in SSE41

;

The interesting thing is when I used yolov10.pt, it worked well. so I think the problem exists in the OPENVINO model.

(but Converting .pt -> .openvino worked well! so it makes me more confused)

so How can I infer images by openvino without errors? :(

### Environment

certifi==2024.7.4
charset-normalizer==3.3.2
colorama==0.4.6
contourpy==1.2.1
cycler==0.12.1
filelock==3.15.4
fonttools==4.53.1
fsspec==2024.6.1
idna==3.7
importlib_resources==6.4.0
Jinja2==3.1.4
kiwisolver==1.4.5
lapx==0.5.9.post1
MarkupSafe==2.1.5
matplotlib==3.9.1
mpmath==1.3.0
networkx==3.2.1
numpy==1.26.4
opencv-python==4.10.0.84
openvino==2024.3.0
openvino-telemetry==2024.1.0
packaging==24.1
pandas==2.2.2
pillow==10.4.0
psutil==6.0.0
py-cpuinfo==9.0.0
pygame==2.6.0
pyparsing==3.1.2
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
requests==2.32.3
scipy==1.13.1
seaborn==0.13.2
six==1.16.0
sympy==1.13.1
torch==2.4.0
torchvision==0.19.0
tqdm==4.66.4
typing_extensions==4.12.2
tzdata==2024.1
ultralytics==8.2.71
ultralytics-thop==2.0.0
urllib3==2.2.2
zipp==3.19.2

### Minimal Reproducible Example

from ultralytics import YOLO

# Load a model
model = YOLO("yolov10_golf_best_openvino_model")  # load a custom trained model

# Run inference on 'golf.jpg' with arguments
model.predict("golf.jpg", save=True, imgsz=640)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
Thank you for reporting this issue. It appears that the problem arises when using the OpenVINO model for inference. To help resolve this, please ensure you are using the latest versions of the Ultralytics and OpenVINO packages. You can update them using:

```bash
pip install --upgrade ultralytics openvino
```

If the issue persists, it might be related to the specific configuration of the OpenVINO model. Please verify that the model was exported correctly and that the input dimensions match the expected format. Additionally, try running the inference with a smaller batch size, as the error suggests a problem with batch dimension handling.

For further assistance, you can refer to the detailed OpenVINO integration guide at https://docs.ultralytics.com/integrations/openvino/. If the problem continues, please provide any additional error logs or details that might help in diagnosing the issue.

**Comment by Skillnoob** [comment]
@dhrhkddns This code works fine on my machine:
```python
from ultralytics import YOLO

model = YOLO('yolov10n.pt')

model.export(format='openvino')

model = YOLO('yolov10n_openvino_model/')

model.predict()```

Can you try reinstalling ultralytics in a `venv` or `miniconda` environment.
If you used a different task than `detect` you need to specify it when initializing the model with `YOLO`.

**Comment by akash-harijan** [comment]
I am also facing same issue, I was trying to run yolov10 on a edge device and it is giving me this error. Btw I tested same code on my laptop machine it was working fine.

```python
RuntimeError: Exception from src/inference/src/cpp/core.cpp:104:
Exception from src/inference/src/dev/plugin.cpp:53:
Exception from src/plugins/auto/src/auto_schedule.cpp:441:
[AUTO] compile model failed, CPU:Exception from src/inference/src/dev/plugin.cpp:53:
Check '(std::find(in_idxs.begin(), in_idxs.end(), idx) == in_idxs.end())' failed at src/plugins/intel_cpu/src/emitters/plugin/x64/jit_emitter.cpp:76:
ov::intel_cpu::jit_emitter: Xmm(0) cannot be input register in SSE41

```

**Comment by glenn-jocher** [comment]
It seems like the issue might be related to the specific configuration of your edge device. Please ensure that your device supports the required OpenVINO operations and that you have the latest drivers and updates installed. If the problem persists, consider checking the compatibility of your device with OpenVINO.
