### ISSUE TITLE
Pretrain YOLO backbone with self-supervised learning

### ISSUE THREAD

**Issue by Glaadiss** [ultralytics/ultralytics#1493]
### Objective:
My objective is to enhance the detection accuracy of my computer vision models for segmentation and detection tasks by incorporating a larger pool of unlabeled data. I hope, this will provide more contextual information to the network and potentially improve its performance.

### Context:
I am currently working on computer vision tasks that involve YOLO architecture. Although I have access to a vast amount of video data, most of it is unannotated. The camera that captures the footage remains fixed, and only a few elements in the scene change over time. While I am annotating some of the data, the process is quite tedious. I am interested in exploring self-supervised learning as a means of leveraging unannotated material. My plan is to train a self-supervised model and use the resulting weights as a backbone in YOLO. However, I am unsure of where to begin.

### Question:
Could you please suggest any tutorials or insights that could guide me in pretraining the YOLO backbone with SSL techniques?

**Comment by glenn-jocher** [comment]
@Glaadiss yes you can use active learning to start from a smaller set of labelled data and then progressively train on larger unlabelled data. 

You would start by training a model on a small set of labeled data. Use this trained model to predict object locations on a larger set of unlabeled data. You can set a threshold for the confidence score of the predictions to filter out false positives. Then manually review a sample of the predicted labels and adjust them as necessary.

Use the adjusted labels to train a new model on the combined set of labeled and adjusted unlabeled data.

Repeat the above steps on progressively larger portions of the unlabeled data until you have labeled and trained on as much data as you desire.

Optionally, you can fine-tune the final model on a smaller set of manually labeled validation data to improve its performance.

This iterative approach is known as active learning and can be used to gradually increase the amount of labeled data without requiring significant manual annotation effort. By using a model to generate initial labels and iteratively improving them, you can efficiently train a model on a much larger dataset than would be possible through manual annotation alone.

**Comment by Glaadiss** [comment]
Thank you for your reply. I've already implemented the process of active learning (similar to what you described). I was thinking though if we can go even further and pre-train the backbone in a fully automated way. For example, using contrastive learning, pretext tasks or other techniques from self-supervised learning.

**Comment by Zephyr69** [comment]
It will depend on how accurate your model needs to be for your tasks. What you are describing is a semi-supervised method, but theoretically and practically the training pipelines incorporating this kind of method will never be as accurate as fully supervised ones, and by a relatively large margin. 

Of course, this is when given the same amount of training data, which will not be the case for these two schemes. What I want to say is this may not "enhance the detection accuracy" the way you expected; the metrics will surely fall. The accuracy is "enhanced" only when you compare it to a scenario where you feed unlabeled data into a fully supervised pipeline.

The current main usage of semi-surpervised learning here is to adapt the model to a more general domain, at an acceptable cost of accuracy.

**Comment by Glaadiss** [comment]
@Zephyr69 Thanks for replying to my question. That makes sense. I thought I can somehow leverage the fact that I have a lot of similar frames because the scene is fixed. If semi-supervised learning is mostly used for generalization I probably won't gain much here.

**Comment by akashAD98** [comment]
@Glaadiss its possible for you to share how you implemented active learninig?

**Comment by glenn-jocher** [comment]
@akashAD98, Yes, YOLOv8 has an option `save_txt=True` to save the detection results for each frame to a text file. Here's an example of how you can use it:

```python
from yolov8 import detect

# set the parameters for detection
config = 'yolov8.yaml'  # path to .yaml model config file
weights = 'yolov8.pt'   # path to .pt model parameters file
img_dir = 'images'      # path to directory containing images to detect objects in

# run detection and save results to a text file
detect(source=img_dir, weights=weights, config=config, save_txt=True)
```

When `save_txt=True`, YOLOv8 will save the detection results for each input image to a file in the same directory as the input image. The file name will be the same as the input image name, but with a `.txt` extension. Each line of the text file corresponds to a detected object and has the format:

```
<class> <confidence> <x_center> <y_center> <width> <height>
```

where `<class>` is the name of the detected object class, `<confidence>` is the detection confidence score, and `<x_center>`, `<y_center>`, `<width>`, and `<height>` are the coordinates and dimensions of the bounding box around the object.

I hope this helps! Please let me

**Comment by glenn-jocher** [comment]
@akashAD98 i apologize for the confusion, `yolov8.detect` was a typo. In YOLOv8, the detection function is called `detect.py` and can be run from the command line or from a Python script as follows:

```python
from detector import detect

# set the parameters for detection
config = 'path/to/config.yaml'  # path to .yaml model config file
weights = 'path/to/weights.pt'   # path to .pt model parameters file
source = 'path/to/images'      # path to directory containing images to detect objects in

# run detection and save results to a text file
detect(source=source, weights=weights, config=config, save_txt=True)
```

This will save the detection results to a text file in the same directory as the input image.

**Comment by akashAD98** [comment]
@glenn-jocher im not getting this also ,what i found is

```
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.predict(source="/content/inputvideo.mp4",save=True,save_txt=True,conf=0.50)
```

i cheecked predict documents, & im not getting what are the different arugments we can pass there, need to modify some documents,

i was checking for Confidenc thres,nms tres,--classes, aruments but this arguments are not mentioned & im not getting it

**Comment by IgorSusmelj** [comment]
@akashAD98 and @Glaadiss, you might want to have a look at this example here using YOLOv8 and active learning: https://docs.lightly.ai/docs/active-learning-yolov8-video

Regarding self-supervised pre-training. It's something I'm looking into, but so far, the results with YOLO models were not very good.

**Comment by Rayen023** [comment]
Hello, I'm currently working on a task similar to what @Glaadiss described, which involves a system of deep neural networks that perform object detection with self-learning capabilities for anomaly detection. 
I'm looking for tutorials or insights on extracting the YOLO backbone and pretraining it with SSL methods such as SimCLR or SWAV. 
I've found a solution using the library Lightly with Detectron2, but I'm looking for a similar solution tailored for YOLO. I've been conducting some research, and I could use some suggestions or guidance on the best approaches or resources to follow. 
If anyone has any recommendations or experiences to share, I would greatly appreciate it.

**Comment by glenn-jocher** [comment]
@Rayen023 certainly, pretraining the YOLO backbone with SSL methods such as SimCLR or SWAV can be an effective way to improve model performance and generalization. However, it's important to note that pretraining with SSL methods requires a careful selection of hyperparameters and design choices to achieve the best results. 

To start, you can look into pre-existing implementations of YOLOv8 or other YOLO models pretrained with SSL methods, such as those published in research papers or available on GitHub. These pre-existing implementations can give you insights into how to translate the SSL pretraining pipeline to YOLO. Furthermore, you can experiment with different data augmentation strategies, network design choices, and hyperparameters to see how they impact performance. 

It's also important to consider the trade-offs between SSL pretraining and fully-supervised training in terms of the amount of labeled data required, computing resources, and time constraints. Depending on the specifics of your task and available resources, SSL pretraining may be an effective way to enhance performance, or it may not be worth the additional complexity beyond traditional supervised training.

**Comment by kalikhademi** [comment]
> Hello, I'm currently working on a task similar to what @Glaadiss described, which involves a system of deep neural networks that perform object detection with self-learning capabilities for anomaly detection.
> I'm looking for tutorials or insights on extracting the YOLO backbone and pretraining it with SSL methods such as SimCLR or SWAV.
> I've found a solution using the library Lightly with Detectron2, but I'm looking for a similar solution tailored for YOLO. I've been conducting some research, and I could use some suggestions or guidance on the best approaches or resources to follow.
> If anyone has any recommendations or experiences to share, I would greatly appreciate it.



> Hello, I'm currently working on a task similar to what @Glaadiss described, which involves a system of deep neural networks that perform object detection with self-learning capabilities for anomaly detection.
> I'm looking for tutorials or insights on extracting the YOLO backbone and pretraining it with SSL methods such as SimCLR or SWAV.
> I've found a solution using the library Lightly with Detectron2, but I'm looking for a similar solution tailored for YOLO. I've been conducting some research, and I could use some suggestions or guidance on the best approaches or resources to follow.
> If anyone has any recommendations or experiences to share, I would greatly appreciate it.

Hi Ryan, 

I am also looking for the same thing. Did you found any tutorial to pretrain yolo with unlabeled data and self-supervised learning models?

**Comment by glenn-jocher** [comment]
@kalikhademi hi there, 

Pretraining YOLOv8 with self-supervised learning methods can be an effective way to improve model performance and generalization, but requires some expertise and careful experimentation with hyperparameters and design choices. Unfortunately, we do not have a tailored solution to pretrain YOLOv8 with self-supervised learning models such as SimCLR or SWAV at this time. However, there are some pre-existing implementations of pre-trained YOLOv8 models with self-supervised learning that you can find by conducting literature review and on Github repositories. These pre-existing implementations could serve as a starting point for conducting your own experimentation. 

In addition, there are tutorials and example code on YOLOv8 models, learning frameworks, and computer vision concepts that could be useful for building your own solution tailored to your specific problem statement. I would recommend conducting research and experimentation with different design choices, datasets, and hyperparameters. 

Best of luck!

**Comment by sergiev** [comment]
@glenn-jocher hi, 
could you please provide some links to such works? I'm currently looking for something really relevant, i.e. not about active learning on video, but about improving performance by learning domain features on augmented images or some other method, given that all accessible related images are already tagged.

P.S. Thank you for your hard work and willingness to help, I can't express how much I appreciate your efforts to keep YOLO the best :)

**Comment by glenn-jocher** [comment]
@sergiev hello,

Thank you for your interest in YOLOv8. While we do not have specific links to works using self-supervised learning to enhance the performance of YOLOv8 on augmented images, we recommend conducting a literature review on the topic and reviewing existing GitHub repositories. Research studies and GitHub repositories can provide useful insights into how to apply self-supervised learning techniques to improve the performance of YOLOv8 on an augmented dataset. It's important to ensure that your experiments are reproducible, and that you carefully tune hyperparameters and network architecture to ensure optimal performance. 

Thank you for your support and interest in the YOLOv8 project. If you have any additional questions, please do not hesitate to ask.

**Comment by skywalker-ai** [comment]
Hello, Did anyone manage to perform self supervision (not active learning)? I would like to train the backbone alone using contrastive learning or any other SSL methods, can anyone help me with how to extract the backbone alone in yolov8-seg architecture for SSL?

**Comment by skywalker-ai** [comment]
I have done the following to extract the backbone and train it separately, can anyone verify whatever I am doing is right?
`model = YOLO('PATH-TO-MODEL/yolov8l-seg.pt') `
`model_children_list = list(model.model.children())`
`backbone = model_children_list[0][:10]`

when I print the **backbone** this is what I get.

```
Sequential(
  (0): Conv(
    (conv): Conv2d(3, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
    (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
    (act): SiLU(inplace=True)
  )
  (1): Conv(
    (conv): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
    (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
    (act): SiLU(inplace=True)
  )
  (2): C2f(
    (cv1): Conv(
      (conv): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (cv2): Conv(
      (conv): Conv2d(320, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (m): ModuleList(
      (0-2): 3 x Bottleneck(
        (cv1): Conv(
          (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(64, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
      )
    )
  )
  (3): Conv(
    (conv): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
    (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
    (act): SiLU(inplace=True)
  )
  (4): C2f(
    (cv1): Conv(
      (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (cv2): Conv(
      (conv): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (m): ModuleList(
      (0-5): 6 x Bottleneck(
        (cv1): Conv(
          (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(128, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
      )
    )
  )
  (5): Conv(
    (conv): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
    (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
    (act): SiLU(inplace=True)
  )
  (6): C2f(
    (cv1): Conv(
      (conv): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (cv2): Conv(
      (conv): Conv2d(2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (m): ModuleList(
      (0-5): 6 x Bottleneck(
        (cv1): Conv(
          (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
      )
    )
  )
  (7): Conv(
    (conv): Conv2d(512, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
    (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
    (act): SiLU(inplace=True)
  )
  (8): C2f(
    (cv1): Conv(
      (conv): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (cv2): Conv(
      (conv): Conv2d(1280, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (m): ModuleList(
      (0-2): 3 x Bottleneck(
        (cv1): Conv(
          (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (cv2): Conv(
          (conv): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
      )
    )
  )
  (9): SPPF(
    (cv1): Conv(
      (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(256, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (cv2): Conv(
      (conv): Conv2d(1024, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(512, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): SiLU(inplace=True)
    )
    (m): MaxPool2d(kernel_size=5, stride=1, padding=2, dilation=1, ceil_mode=False)
  )
)
```

**Comment by glenn-jocher** [comment]
@skywalker-ai hello there,

The steps you're following to extract the backbone seem correct. You're correctly loading the pretrained model and then slicing the Sequential component of the model to get the backbone. 

The output you get is essentially the feature extraction component of the YOLOv8 model, which is also known as the backbone of the network. Comparing it to the architecture diagram, it appears to match indeed, giving indications that your approach is correct.

Keep in mind, however, that when it comes to training this backbone with self-supervised learning, you will need to consider the output layer and adjust it accordingly based on your specific use-case. You may have to add additional layers or modify the existing ones to fit with the self-supervised learning task at hand. 

Good luck! If you have any more questions, feel free to ask.

**Comment by skywalker-ai** [comment]
@glenn-jocher Thank you for confirming!

**Comment by glenn-jocher** [comment]
@skywalker-ai you're welcome! If you have any further questions or need more assistance, feel free to ask. We're always here to help. Good luck with your work on YOLOv8!

**Comment by andresinsitu** [comment]
> @akashAD98, Yes, YOLOv8 has an option `save_txt=True` to save the detection results for each frame to a text file. Here's an example of how you can use it:
> 
> ```python
> from yolov8 import detect
> 
> # set the parameters for detection
> config = 'yolov8.yaml'  # path to .yaml model config file
> weights = 'yolov8.pt'   # path to .pt model parameters file
> img_dir = 'images'      # path to directory containing images to detect objects in
> 
> # run detection and save results to a text file
> detect(source=img_dir, weights=weights, config=config, save_txt=True)
> ```
> 
> When `save_txt=True`, YOLOv8 will save the detection results for each input image to a file in the same directory as the input image. The file name will be the same as the input image name, but with a `.txt` extension. Each line of the text file corresponds to a detected object and has the format:
> 
> ```
> <class> <confidence> <x_center> <y_center> <width> <height>
> ```
> 
> where `<class>` is the name of the detected object class, `<confidence>` is the detection confidence score, and `<x_center>`, `<y_center>`, `<width>`, and `<height>` are the coordinates and dimensions of the bounding box around the object.
> 
> I hope this helps! Please let me


Hi @glenn-jocher, here you say that saved txt are in the format:  
`<class> <confidence> <x_center> <y_center> <width> <height>`

But checking the code 
https://github.com/ultralytics/ultralytics/blob/c7ceb84fb6085e767ed664460cd6abec9ced86d8/ultralytics/engine/results.py#L290

it seems they are instead in the format:

`<class> <x_center> <y_center> <width> <height> <confidence>`

Is that right?

**Comment by CrapbagMo** [comment]
Hi, I tried to pretrain the yolo backbone with self-supervised learning method. I got the state_dict file, and loaded it like this:
```
backbone = torch.load('pretrain/your_exp_dir/yolov8backbone_1kpretrained_timm_style.pth')
model = YOLO('yolov8l-p2.yaml')
model.model.load_state_dict(backbone['module'], strict=False)
model.train(data='delft500.yaml', epochs=100, close_mosaic=10, name='yolol-p2-mae')  # tr
```
I tried to train it with two different pretrained weights but got exactly the same results twice. Would you tell me what went wrong? How do I load the backbone weights correctly?

**Comment by glenn-jocher** [comment]
@CrapbagMo hello,

Your approach to load pre-trained weights into the YOLOv8 backbone seems to be correct. You are loading the state dictionary of the pre-trained backbone and then applying it to your model using the `load_state_dict` function with `strict=False`, which allows the program to proceed even if the keys in the state dictionary don't perfectly match the keys in your model.

The fact that you are getting the same results twice could be attributed to several reasons. It could be due to the nature of the dataset you are training on, the number of epochs you're training for, or due to the learning rate not being fine-tuned for the task at hand.

To debug, I recommend checking your training process:

1. Verify that your backbone weights file ('yolov8backbone_1kpretrained_timm_style.pth') is different for the two pre-trained weights you are loading. 
2. Inspect your training dataset to make sure it contains the variety needed for training, and that the classes are balanced.
3. Experiment with different training parameters such as the learning rate, batch size, and number of epochs.
4. Ensure that your training process updates the weights of the backbone correctly after loading the pre-trained weights.

Remember that the effectiveness of pretraining largely depends on how similar your new task is to the task the network was originally pretrained on. If the tasks are very similar, pretraining can be beneficial. If they are very different, pretraining may not provide any benefit. 

I hope this helps! Please let us know if you have any other questions or need further clarification.

**Comment by Estellasy** [comment]
> Hi, I tried to pretrain the yolo backbone with self-supervised learning method. I got the state_dict file, and loaded it like this:
> 
> ```
> backbone = torch.load('pretrain/your_exp_dir/yolov8backbone_1kpretrained_timm_style.pth')
> model = YOLO('yolov8l-p2.yaml')
> model.model.load_state_dict(backbone['module'], strict=False)
> model.train(data='delft500.yaml', epochs=100, close_mosaic=10, name='yolol-p2-mae')  # tr
> ```
> 
> I tried to train it with two different pretrained weights but got exactly the same results twice. Would you tell me what went wrong? How do I load the backbone weights correctly?

I got the same problem as you, have you solved it?

**Comment by glenn-jocher** [comment]
@Estellasy hey there! 😊 It looks like you're on the right track with loading your pre-trained backbone weights. If you're seeing identical results with two different sets of weights, it might be worth double-checking a few things:

- Ensure the two sets of pre-trained weights are indeed different and relevant to your task.
- Verify that the weights are being correctly applied to the model. Sometimes, a quick print statement after loading weights can help confirm changes.
- Consider experimenting with different hyperparameters or training settings, as the issue might not be with how you're loading the weights but rather with how the model is learning from your specific dataset.

Here's a quick snippet to help you confirm the weights have been loaded:

```python
for name, param in model.named_parameters():
    if param.requires_grad:
        print(name)
```

This will print out the names of the parameters that are being updated during training. You should see the names of the backbone layers if the weights have been successfully loaded.

Hope this helps! Let us know how it goes. 🚀

**Comment by Lightmannnn** [comment]
> > 嗨,我试着用自我监督的学习方法来预先训练约洛的脊梁。我拿到了国家档案,然后像这样加载:
> > ```
> > backbone = torch.load('pretrain/your_exp_dir/yolov8backbone_1kpretrained_timm_style.pth')
> > model = YOLO('yolov8l-p2.yaml')
> > model.model.load_state_dict(backbone['module'], strict=False)
> > model.train(data='delft500.yaml', epochs=100, close_mosaic=10, name='yolol-p2-mae')  # tr
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我试着用两种不同的预先训练的重物训练它,但两次得到了完全相同的结果。你能告诉我怎么了吗?如何正确地装载脊骨重量?
> 
> 我和你有同样的问题,你解决了吗?

Same here, I get the same results regardless of loading any pre-trained model

**Comment by glenn-jocher** [comment]
It sounds like the pre-trained weights might not be applying as expected. Double-check that the weights are correctly loaded and consider verifying the differences between the pre-trained models. Adjusting hyperparameters or training settings might also help.

**Comment by Y-T-G** [comment]
I created a guide on how to pretrain the backbone using Lightly and load it in Ultralytics 

https://y-t-g.github.io/tutorials/yolo-pretrain-ssl/

**Comment by yutong-xiang-97** [comment]
Hi, there! We are [Lightly](https://www.lightly.ai/) and we recently launched LightlyTrain which enables pretraining Ultralytics' YOLO models with distillation and self-supervised learning! This might be interesting for users who would like to pretrain domain-specific YOLO backbones.

[LightlyTrain](https://github.com/lightly-ai/lightly-train) is a novel pretraining framework built with PyTorch. It lets you pretrain any computer vision model on your unlabeled data, by leveraging distillation from foundation models and using self-supervised learning. With only a few lines of code, the community can pretrain domain-specific backbones for any downstream task that YOLO supports, such as classification, object detection, and more.

You can simply start pretraining e.g. a YOLO11 model by:

import lightly_train

if __name__ == "__main__":
    lightly_train.train(
        out="out/my_experiment",                # Output directory.
        data="my_data_dir",                     # Directory with images.
        model="ultralytics/yolo11s.yaml",       # Pass the YOLO11 model.
    )

and fine-tune using the checkpoint by:

from pathlib import Path

from ultralytics import YOLO

if __name__ == "__main__":
    # Load the exported model.
    model = YOLO("out/my_experiment/exported_models/exported_last.pt")

    # Fine-tune with ultralytics.
    data = Path("my_data_dir/config.yaml").absolute()
    model.train(data=data)

You can check our [docs](https://docs.lightly.ai/train/stable/index.html) and [product page](https://www.lightly.ai/lightlytrain) for more details.

**Comment by glenn-jocher** [comment]
@yutong-xiang-97 Thank you for sharing LightlyTrain with our community! This looks like an excellent solution for users wanting to leverage self-supervised learning with YOLO models. The ability to pretrain domain-specific backbones using unlabeled data addresses exactly what was asked in this issue.

I appreciate that you've provided a straightforward implementation example that works with our YOLO11 models. This kind of integration between different ML tools helps the entire computer vision community advance.

For users following this thread who were experiencing issues with loading pretrained weights, this framework might offer a more streamlined approach. The combination of Y-T-G's guide and this LightlyTrain solution provides good options for tackling self-supervised pretraining.

**Comment by lucatersisve** [comment]
@yutong-xiang-97 Thank you for sharing LightlyTrain, I've tested the tutorial and the fine tuning of yolo **detection** works out of the box. However I'm getting problems to fine tune **segmentation** task after pre-training. Here the stack trace:

>   File "/opt/conda/lib/python3.11/site-packages/ultralytics/nn/tasks.py", line 301, in loss
    return self.criterion(preds, batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ultralytics/utils/loss.py", line 218, in __call__
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ultralytics/utils/loss.py", line 218, in <listcomp>
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[32, 74, -1]' is invalid for input of size 172032


Do you have any suggestion? Thank you very much

**Comment by guarin** [comment]
The above error seems to be related to Ultralytics model saving, see https://github.com/ultralytics/ultralytics/issues/20570

**Comment by glenn-jocher** [comment]
@guarin thanks for the helpful reference! @lucatersisve that's a good catch - the shape mismatch error you're seeing during segmentation fine-tuning is likely related to how the model head is being reconstructed after loading the pretrained backbone. You might want to check if the exported model from LightlyTrain maintains the correct head architecture for segmentation tasks, or consider manually ensuring the segmentation head is properly initialized before fine-tuning.
