### ISSUE TITLE
[ultralytics[explorer]] When I execute "yolo explorer", an error is reported

### ISSUE THREAD

**Issue by ws1065** [ultralytics/ultralytics#14935]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/user-attachments/assets/a3f65eb5-90db-423c-b987-f440520d8783)
我看到是端口监听失败了，但是我不知道怎么排查这个问题，也没有找到这个相关的文档。
1.它监听的是什么端口？
2.如果我想traces yolo explores 命令，在win下应该怎么操作？换句话说yolo命令替代了python的什么命令？

**Comment by ws1065** [comment]
我重启电脑才发现他监听的端口是8501  ，我建议应该优化报错输出

**Comment by pderrenger** [comment]
@ws1065 thank you for the feedback. It's helpful to know that the port in question is 8501. We appreciate your suggestion to improve the error messaging, and we'll consider it for future updates. If you encounter any further issues, please ensure you're using the latest version of the Ultralytics package.

**Comment by ws1065** [comment]
Thank you

**Comment by pderrenger** [comment]
You're welcome! If you encounter any further issues or have additional questions, feel free to ask. We're here to help!
