### ISSUE TITLE
residual connection is redundant in c2f module

### ISSUE THREAD

**Issue by ohmydroid** [ultralytics/ultralytics#14931]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

As C2f module for yolov8n includes concat operation and residual connection from the same input of bottleneck. Concat and residual connection share similar function to introduce short paths for network. It is not necessary to adopt both operations.

We can remove residual connection by fusing partial weights of the last 1x1 convolution after training, or directly abandon residual connection before the first training.
I prefer the latter scheme.

If c2f has multiple bottleneck blocks for other size of yolov8, only the residual connection in last bottleneck can be removed.

### Use case

Removing redundant residual connection can accelerate model training or inference

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@ohmydroid thank you for your detailed observation regarding the C2f module in YOLOv8. Your suggestion to remove the redundant residual connection is insightful. We will consider this for future updates to optimize the model's performance. If you have further insights or would like to contribute, feel free to submit a PR. Meanwhile, please ensure you are using the latest version of the package to benefit from recent improvements and fixes.
