### ISSUE TITLE
Scaling models to higher resolutions

### ISSUE THREAD

**Issue by ganessh22** [ultralytics/ultralytics#14936]
I am trying to improve performance of YOLOv8 on my object detection task. The objects are often small. For v7-v6 I used to use the 1280 models. I want to train a v8 1280 or higher model. Is there some way to scale up the config with more parameters and/or depth when increasing resolution?

I remember that v5 had higher resolution released models. I just want to understand how the scaling up is done as I can't notice a proper pattern from the v5 config files.

I had previously asked on discord but since I didn't get a response I thought I'd try here.

**Comment by Y-T-G** [comment]
For more parameters, you can use the `p2` config or a larger model. Resolution doesn't increase parameters.

**Comment by ganessh22** [comment]
Do you mean p6? The p2 looks to be a smaller backbone model. 
`p2`
```yaml
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9
```

`p6`
```yaml
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [768, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [768, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 9-P6/64
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 11
```
Hmm I think I can see some pattern from looking at p2 vs p6. I will try adding a 11-p7/128 kind of line and onwards when trying to train a larger resolution model.

**Comment by Y-T-G** [comment]
p6 or more is for very large objects. It's not going to be useful for small objects.

**Comment by ganessh22** [comment]
@Y-T-G was a model which combines P2-P6 combined with more width tried? I think that should perform the best right for large and small objects mixed?

**Comment by Y-T-G** [comment]
P2 is for extra small objects while P6 is for extra large objects. Usually you have one or the other. You can combine both, but it would be pretty slow.
