### ISSUE TITLE
Save_frames from predict function on instance segmentation task does not work. 

### ISSUE THREAD

**Issue by MaxRondelli** [ultralytics/ultralytics#14943]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

I am trying to save all the frame from predict inference on instance segmentation task but the arg does not work. 
As you can see from the following figure, this is a line of my stack trace during the inference (the predicted class are covered for NDA since it is a custom project). There is no info about where the image has been saved. This result is with `save_frames = True` as arg.

![bug](https://github.com/user-attachments/assets/969e458e-c52f-49bc-9349-cbcd79980b24)

Viceversa, when I set `save = True` as arg, this is the stacktrace and the frame is saved in the correct path. 

![bug1](https://github.com/user-attachments/assets/7956dc9b-b875-4aee-a16b-6597823fdd0f)

I provide you also the environment that I working on and the function to where I make the prediction for the frames in the video.

### Environment

Ultralytics YOLOv8.2.70 🚀 Python-3.12.4 torch-2.4.0 CUDA:0 (NVIDIA GeForce RTX 3060, 11947MiB)
Setup complete ✅ (12 CPUs, 15.6 GB RAM, 413.1/907.0 GB disk)

OS                  Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.12.4
Install             pip
RAM                 15.57 GB
CPU                 AMD Ryzen 5 3600 6-Core Processor
CUDA                12.4

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.4.0>=1.8.0
torchvision         ✅ 0.19.0>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

```python 
def get_video(FPS, OUTPUT_VIDEO_NAME, VIDEO_PATH, MODEL_PATH_YOLO):
    model = YOLO(MODEL_PATH_YOLO)

    # Start capturing the feed and converting video into frames
    cap = cv2.VideoCapture(VIDEO_PATH)
    video_length = int(cap.get(cv2.CAP_PROP_FRAME_COUNT)) - 1
    print ("Number of frames: ", video_length)
    print ("Converting video..\n")

    progress_bar = tqdm(total=min(video_length, 1500))  # Set progress bar for 1500 frames
    inferenced_frames = []
    frame_counter = 0

    while cap.isOpened() and frame_counter < 1500:
        # Extract the frame
        ret, frame = cap.read()
        if not ret:
            break

        # Make the inference on the current frame
        result = model.predict(source = frame,
                            save_frames = True,
                            show_labels = False,
                            show_conf = False,
                            line_width = 2,
                            project="inferenced_frames", 
                            name="inference", 
                            exist_ok=True
                            )
        
        frame_counter += 1
        progress_bar.update(1) # Continue with next frame
    
    progress_bar.close()

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
`save_frames` works when you start the inference using `model(video_path)` or if you add `stream=True` to your `model.predict()`

**Comment by MaxRondelli** [comment]
This is the solution that I found with `stream=True` but not with `save_frames`. 
```python
from ultralytics import YOLO

def get_video(VIDEO_PATH, MODEL_PATH_YOLO):
    model = YOLO(MODEL_PATH_YOLO)
    source = VIDEO_PATH
    results = model(source, stream=True)
    
    # Process results generator
    count = 0
    for result in results:
        boxes = result.boxes  # Boxes object for bounding box outputs
        masks = result.masks  # Masks object for segmentation masks outputs
        keypoints = result.keypoints  # Keypoints object for pose outputs
        probs = result.probs  # Probs object for classification outputs
        obb = result.obb  # Oriented boxes object for OBB outputs
        result.save(filename=f"inferenced/frame_{count}.jpg")  # save to disk
        count += 1
```

The arg `save_frames` still does not work. I'm probably doing something wrong but with the following code no frames are saved in the folder.
```python
from ultralytics import YOLO

def get_video(VIDEO_PATH, MODEL_PATH_YOLO):
    model = YOLO(MODEL_PATH_YOLO)
    source = VIDEO_PATH
    results = model(source, stream=True, save_frames=True)
```

**Comment by Y-T-G** [comment]
You have to use both `save` and `save_frames` together.

**Comment by MaxRondelli** [comment]
Still. No frames are saved into the folder, in both ways.
```python
from ultralytics import YOLO

def get_video(VIDEO_PATH, MODEL_PATH_YOLO):
    model = YOLO(MODEL_PATH_YOLO)
    source = VIDEO_PATH

    # First way
    results = model.predict(source, stream=True, save=True, save_frames=True)

    # Second way
    results = model(source, stream=True, save=True, save_frames=True)

if __name__ == "__main__":
    MODEL_PATH_YOLO = '/my_project_path/runs/segment/train/weights/best.pt'
    VIDEO_PATH = '/my_project_path/video.mp4'

    # Run inference for a video 
    get_video(VIDEO_PATH, MODEL_PATH_YOLO) 
```

**Comment by Y-T-G** [comment]
After you add `stream=True`, you have to iterate through the results.

Your old code was fine. Just `add save=True`

**Comment by MaxRondelli** [comment]
Dope. Found the solution.

```python
from ultralytics import YOLO

def get_video(VIDEO_PATH, MODEL_PATH_YOLO):
    model = YOLO(MODEL_PATH_YOLO)
    source = VIDEO_PATH
    results = model(source, 
                    stream=True, 
                    save=True, 
                    save_frames=True,
                    show_labels=False,
                    show_conf=False
                    )

    # Process results generator
    for result in results:
        boxes = result.boxes  # Boxes object for bounding box outputs
        masks = result.masks  # Masks object for segmentation masks outputs
        keypoints = result.keypoints  # Keypoints object for pose outputs
        probs = result.probs  # Probs object for classification outputs
        obb = result.obb  # Oriented boxes object for OBB outputs
```

Now all frames are saved in predict folder. 

Thank you for the support.

**Comment by pderrenger** [comment]
Great to hear you found the solution! If you encounter any further issues or have additional questions, feel free to reach out. Always ensure you're using the latest version of the package to benefit from the latest fixes and features. Thank you for your engagement!
