### ISSUE TITLE
NMS is not applied in detection task at inference time

### ISSUE THREAD

**Issue by muzunpostalci** [ultralytics/ultralytics#14942]
When I get inferences on my model I get a lot of boxes overlapping each other, either with same classes or different classes. Almost exactly same coordinates. When I debugged the code to track nms function I saw the following code lines.

https://github.com/ultralytics/ultralytics/blob/bea4c932783f6ab80cce91e00abe38d45c575531/ultralytics/utils/ops.py#L219-L223

My prediction shape is indeed (1,300,6) and it just filters confidence scores and returns two boxes that almost have exactly same coordinates and class but different confidence.

When I modify the code like this, I get my expected result (only one box)
```
if prediction.shape[-1] == 6:  # end-to-end model (BNC, i.e. 1,300,6)
    output = [pred[pred[:, 4] > conf_thres] for pred in prediction]
    if classes is not None:
        output = [pred[(pred[:, 5:6] == classes).any(1)] for pred in output]
    for i, pred in enumerate(output):
        if len(pred) > 0:
            boxes = pred[:, :4]
            scores = pred[:, 4]
            idxs = torchvision.ops.nms(boxes, scores, iou_thres)
            output[i] = pred[idxs]
    return output
```

I wonder why is it the case that when prediction results are boxes no nms is applied. Am I missing an argument to do this or something else?

**Comment by Y-T-G** [comment]
Which model?

`RTDETR` and `YOLOv10` do not use NMS.

**Comment by muzunpostalci** [comment]
I am indeed using YOLOv10, we switched from v8 at some point, but I guess missed out the NMS part. Thanks for pointing it out.

**Comment by pderrenger** [comment]
@muzunpostalci thank you for confirming. YOLOv10 indeed does not use NMS as part of its architecture. If you need NMS, you might consider switching back to YOLOv8 or implementing a custom post-processing step. If you encounter any other issues, please ensure you're using the latest version of the package.
