### ISSUE TITLE
yolov8 classification in aws sagemaker.

### ISSUE THREAD

**Issue by sard0r** [ultralytics/ultralytics#14945]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have successfully trained the yolov8 classification model on aws. But when it comes to the validation I am failing to specify the validation folder. According to the Ultralytics the model should remember all the path and values. But it is not finding the validation folder and throwing error over and over again. 

So can we include data dir to the model.val function. I saw cli function as yolo task=classify mode=val model={HOME}/runs/classify/train/weights/best.pt data='{DATA_DIR}'.

Can we run model.val(data=data_dir) or anything possible thank you very much!

**Comment by Y-T-G** [comment]
> Can we run model.val(data=data_dir) or anything possible thank you very much!

Yes
