### ISSUE TITLE
使用图片文件夹运行predict时 内存管理BUG

### ISSUE THREAD

**Issue by q465414859** [ultralytics/ultralytics#1494]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

用predict文件夹图片时，内存管理没之前版本的好。会导致内存上升。虽然不会溢出，但在执行其他程序时会导致降低时间。
降低时间的情况很普遍但我只截取到一个。如果在运行其他程序时时间大多会是80+ms
![QQ浏览器截图20230319194259](https://user-images.githubusercontent.com/26251132/226175464-9e0f9217-f5cb-4c3b-bf86-c4a079f0fcca.png)
![QQ浏览器截图20230319203102](https://user-images.githubusercontent.com/26251132/226175467-947a1fe9-55f9-4a29-ac71-728914545113.png)

### Environment

Ultralytics YOLOv8.0.54  Python-3.8.16 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce GTX 1060 5GB, 5120MiB)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@q465414859 inference is very compute intensive and will slow down if you are running other programs at the same time. 

If you think there's been a change in speed please point us to a a diff in versions that you believe experienced performance changes and a minimum reproducible example that shows the change in speeds between the versions. Thank you!

**Comment by q465414859** [comment]
> @q465414859推理是非常计算密集型的，如果同时运行其他程序，推理速度会变慢。
> 
> 如果您认为速度有所变化，请指出您认为经历性能变化的版本差异，以及显示版本之间速度变化的最小可再现示例。谢谢大家！

 是内存爆满后速度会变慢，运行其他软件在内存没爆满时不会有速度的变化。但在内存爆满后就会有速度的变化。
其实内存爆满的问题严重，之前不是这个情况。我是17号换成8.0.54版本的。具体版本我忘记了
