### ISSUE TITLE
Can't seem to asign second GPU to yolov8 training.

### ISSUE THREAD

**Issue by uorufu** [ultralytics/ultralytics#14949]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My script:

```
from ultralytics import YOLO
import torch

def main():
    device = torch.device("cuda")
    torch.cuda.set_device(1)
    print(torch.cuda.get_device_name())         #This properly shows my second GPU

    model = YOLO("yolov8m-seg.pt")

    results = model.train(
        data = "D:/Dataset/data.yaml",
        name='train_yolo8m-seg',
        imgsz=640,
        epochs=500,
        patience=200,
        device=1                                              #Does nothing, my device in 0 is used instead.
        )

    metrics = model.val()

if __name__ == "__main__":
    main()
```

So I want to use my second GPU, but the training keeps using my first GPU. What is wrong?

Versions information:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:28:36_Pacific_Standard_Time_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0
```

```
Name: torch
Version: 2.4.0+cu124
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: d:\dataset\venv\lib\site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: thop, torchaudio, torchvision, ultralytics
```

```
Name: ultralytics
Version: 8.0.23
Summary: Ultralytics YOLOv8
Home-page: https://github.com/ultralytics/ultralytics
Author: Ultralytics
Author-email: hello@ultralytics.com
License: GPL-3.0
Location: d:\dataset\venv\lib\site-packages
Requires: ipython, matplotlib, numpy, opencv-python, pandas, Pillow, psutil, PyYAML, requests, scipy, seaborn, sentry-sdk, tensorboard, thop, torch, torchvision, tqdm
Required-by:
```

**Comment by pderrenger** [comment]
@uorufu it looks like you're having trouble assigning the second GPU for your YOLOv8 training. The issue might be related to how the `device` argument is being handled. Instead of setting the device within the `train` method, try setting the device directly when loading the model. Here's a quick adjustment:

```python
from ultralytics import YOLO
import torch

def main():
    device = torch.device("cuda:1")  # Specify the second GPU
    print(torch.cuda.get_device_name(device))  # Confirm the second GPU

    model = YOLO("yolov8m-seg.pt").to(device)  # Load model to the specified device

    results = model.train(
        data="D:/Dataset/data.yaml",
        name='train_yolo8m-seg',
        imgsz=640,
        epochs=500,
        patience=200,
        device=device  # Ensure the device is correctly passed
    )

    metrics = model.val()

if __name__ == "__main__":
    main()
```

This should ensure that the model and training process use the second GPU. If the issue persists, please verify that your environment correctly recognizes multiple GPUs and that there are no other processes occupying the second GPU. Also, ensure you are using the latest versions of the Ultralytics and PyTorch packages.

**Comment by uorufu** [comment]
> @uorufu it looks like you're having trouble assigning the second GPU for your YOLOv8 training. The issue might be related to how the `device` argument is being handled. Instead of setting the device within the `train` method, try setting the device directly when loading the model. Here's a quick adjustment:
> 
> ```python
> from ultralytics import YOLO
> import torch
> 
> def main():
>     device = torch.device("cuda:1")  # Specify the second GPU
>     print(torch.cuda.get_device_name(device))  # Confirm the second GPU
> 
>     model = YOLO("yolov8m-seg.pt").to(device)  # Load model to the specified device
> 
>     results = model.train(
>         data="D:/Dataset/data.yaml",
>         name='train_yolo8m-seg',
>         imgsz=640,
>         epochs=500,
>         patience=200,
>         device=device  # Ensure the device is correctly passed
>     )
> 
>     metrics = model.val()
> 
> if __name__ == "__main__":
>     main()
> ```
> 
> This should ensure that the model and training process use the second GPU. If the issue persists, please verify that your environment correctly recognizes multiple GPUs and that there are no other processes occupying the second GPU. Also, ensure you are using the latest versions of the Ultralytics and PyTorch packages.

I get this then

```
results = model.train(
AttributeError: 'NoneType' object has no attribute 'train'
```

remove just the .to(device) give me this:

```
raise RepresenterError("cannot represent an object", data)
yaml.representer.RepresenterError: ('cannot represent an object', device(type='cuda', index=1))
```

My first gpu is a RTX 4090 and my second an A6000. Could there be a driver issue here? It seems it doesn't like my RTX A6000?

**Comment by Y-T-G** [comment]
Try
```python
import torch
model.train(..., device=torch.device((1))
```

**Comment by uorufu** [comment]
Ok, not 100% sure what did it, but it suddenly works. I restarted my pc and tried what @Y-T-G suggested, and my A6000 is blasting away suddenly.
