### ISSUE TITLE
using torch GPU

### ISSUE THREAD

**Issue by 576667737** [ultralytics/ultralytics#1495]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Ultralytics YOLOv8.0.53 Python-3.9.1 torch-1.8.1+cu111 CUDA:0 (NVIDIA GeForce RTX 3070, 8192MiB)
Ultralytics YOLOv8.0.54 Python-3.10.6 torch-2.0.0+cpu CPU
in window10,same environment,latest YOLOv8 can't use GPU for training

**Comment by 576667737** [comment]
using this command  
yolo detect train data=road.yaml model=yolov8n.pt epochs=100 imgsz=640 
the training begins,but it's too slow ,
![7a1e062ff46809ed3f398adaf288e38](https://user-images.githubusercontent.com/46989779/226182279-040426ae-1dfb-4ddc-abb9-6d3624c1e3ff.png)
![79d8bf1c20ed104c840aa02f666953d](https://user-images.githubusercontent.com/46989779/226182297-069106af-6525-4c2f-8d2f-1c8f66b6115d.png)

**Comment by glenn-jocher** [comment]
@576667737 if `yolo train device=0` doesn't work then your environment doesn't support GPU, or you only have torch CPU installed.

**Comment by seblful** [comment]
after installing ```ultralytics``` try to install torch with gpu using next command ```pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117```. Probably you should delete first torch, torchvision, torchaudio

**Comment by lakyfarky** [comment]
Install torch GPU first, then ultralytics

**Comment by nadinator** [comment]
> Install torch GPU first, then ultralytics

That didn't work for me.

**Comment by pderrenger** [comment]
@nadinator it's unfortunate that the approach didn't yield the expected results for you. Have you considered checking if your CUDA version is compatible with the torch GPU version you installed? Additionally, you may want to ensure the correct GPU drivers are installed and accessible in your environment.
