### ISSUE TITLE
multi-threading or list.streams

### ISSUE THREAD

**Issue by shengyu27** [ultralytics/ultralytics#14953]
@Rasantis hey!

Absolutely, YOLOv8 is designed with efficiency in mind and supports processing multiple video streams in real-time, including RTSP streams. For handling +20 cameras, implementation may hinge on factors like hardware capabilities, network bandwidth, and desired inference speed.

A simple way to approach this is to employ multithreading in Python, where each thread processes a separate video stream. Here's a basic example of how you might set this up:

```python
import threading
from ultralytics import YOLO

def process_stream(source):
    model = YOLO('yolov8n.pt')
    results = model.track(source=source, stream=True)
    for result in results:
        # Your code to handle each result here
        print(result)

# List of your RTSP camera sources
camera_sources = ['rtsp://camera1_stream', 'rtsp://camera2_stream', '...', 'rtsp://camera20_stream']

# Create threads for each camera stream
for source in camera_sources:
    t = threading.Thread(target=process_stream, args=(source,))
    t.start()
```

Keep in mind that processing a large number of streams simultaneously is resource-intensive. Optimization and testing on the target hardware is crucial to achieve the best performance. Also, you might want to explore distributed computing solutions if scalability is a core requirement. 🚀

Hope this helps! Feel free to reach out if you have more questions.

_Originally posted by @glenn-jocher in https://github.com/ultralytics/ultralytics/issues/9823#issuecomment-2041206514_

----------------------------------------------------------------------------------------------------------------------------

I found that YOLO can input multiple streams simultaneously, batch process them, and then return the results.
```
import threading
from ultralytics import YOLO

# List of your RTSP camera sources
# camera_sources = ['rtsp://camera1_stream', 'rtsp://camera2_stream', '...', 'rtsp://camera20_stream']
camera_sources = '/list.streams'
model = YOLO('yolov8n.pt')
results = model.track(source=camera_sources, stream=True)
for result in results:
      # Your code to handle each result here
      print(result)

```

Will this batch processing method involve multiple threads?
Which of the two ways is better?

**Comment by Y-T-G** [comment]
Batch is better

**Comment by Y-T-G** [comment]
torch uses multi-threading

multi-threading in Python isn't useful due to GIL because it doesn't use all the CPUs

You should use multiprocessing + Triton Inference Server for multiple streams.

**Comment by shengyu27** [comment]
> torch uses multi-threading
> 
> multi-threading in Python isn't useful due to GIL because it doesn't use all the CPUs
> 
> You should use multiprocessing + Triton Inference Server for multiple streams.

If I were to run 2000 real-time streams now and use multiple processes, wouldn't it require 2000 processes? Doesn't that require a lot of CPU resources? This is definitely not very practical, what if I use multithreading?
Or is there any more reasonable plan?

**Comment by Y-T-G** [comment]
> If I were to run 2000 real-time streams now and use multiple processes, wouldn't it require 2000 processes? Doesn't that require a lot of CPU resources? This is definitely not very practical, what if I use multithreading?

If you use multi-threading, you will be limited to 1 CPU.

For cases like these, you should DeepStream with Triton Inference Server launching a batch of streams in each process.

**Comment by shengyu27** [comment]
If there is no Triton Inference Server, can I use TensorRT instead?
That is to say, using multiple processes, each with multiple streams using a YOLO model, and using batch processing (i.e. list. streams?)

**Comment by pderrenger** [comment]
@shengyu27 yes, you can use TensorRT for efficient inference. Running multiple processes with each handling multiple streams using batch processing is a viable approach. This setup can help manage resources effectively while maintaining performance. Ensure you test and optimize based on your specific hardware and workload.

**Comment by shengyu27** [comment]
Thank you for your guidance and suggestions.
I have set up multiple processes, each using a YOLO model for batch processing (list. streams), and the following issues occur:
![image](https://github.com/user-attachments/assets/debd0194-3b6f-498e-858b-bb885a81ba37)
I think this is due to the CPU's processing not keeping up with the transfer speed of RTSP, resulting in a mismatch of serial numbers?
But my server CPU supports a maximum of 48 threads, and I have run a total of 25 streams. Theoretically, each process processes 5 and each thread processes 1, which does not exceed the processing performance of the CPU. If my understanding is correct, then what is the reason for this?

**Comment by Y-T-G** [comment]
@shengyu27 TensorRT and Triton server different purpose. With Triton, you don't need to load multiple models. All the processes will use the same model. TensorRT is a backend for acceleration. Triton supports multiple backends including TensorRT, ONNX, Torchscript etc.

**Comment by shengyu27** [comment]
> @shengyu27 TensorRT and Triton server different purpose. With Triton, you don't need to load multiple models. All the processes will use the same model. TensorRT is a backend for acceleration. Triton supports multiple backends including TensorRT, ONNX, Torchscript etc.

My requirement is to load different models for different bitstreams and customize them.

Furthermore, regarding the issues mentioned above, may I ask if you can provide any assistance?

**Comment by pderrenger** [comment]
For your requirement to load different models for different bitstreams, using multiple processes with TensorRT should work. Ensure each process handles a manageable number of streams to balance the load. Regarding the RTSP issue, it seems like a CPU bottleneck. Verify that your CPU utilization is within limits and consider optimizing the RTSP stream handling or using hardware acceleration if available. Also, ensure you are using the latest versions of the Ultralytics package and dependencies to rule out any bugs. If the issue persists, please provide more details for further assistance.

**Comment by shengyu27** [comment]
Thank you for your suggestion. I have one more question.
When using `yolo.predist ('list. streams', stream=True)`, all streams in the file are batched.
If I allocate 5 processes and load 10 streams using the above method in each process, then a total of 50 streams have been run.
Does YOLO create threads on its own during batch processing in each process? Or is it just one thread to complete this batch processing process? 
I found that my CPU supports up to 48 threads in parallel, and when running 50 streams, the CPU utilization rate has already reached 99%. So, does YOLO's internal batch processing automatically use multiple-threads to complete it?

**Comment by Y-T-G** [comment]
`torch` uses multiple threads.

**Comment by shengyu27** [comment]
Thank you, I think I understand now.

**Comment by pderrenger** [comment]
You're welcome! If you encounter any further issues or have additional questions, feel free to ask. We're here to help!

**Comment by tofulim** [comment]
@shengyu27 check my issue #14257 i asked similar question about this.
i think the difference between using multi-thread and list.streams is control
if u choose multi-thread and capture rtsp stream's frame individually, u could control FPS, capture buffer or pre/post processing but if u choose list.streams it's hard to control.

using list.streams mean that using only below code lines
```python
yolo.predict('list.streams', stream=True)
```
so, this makes u inference with less code lines but in other words that means you get less permission to control

**Comment by shengyu27** [comment]
> 检查我的问题 #14257 我问了类似的问题。我认为使用多线程和 list.streams 之间的区别在于控制，如果您选择多线程并单独捕获 RTSP 流的帧，您可以控制 FPS、捕获缓冲区或前/后处理或其他东西。但是如果你选择 List.streams，就很难控制细节，因为你有 Ultralytics 的依赖项
> 
> 使用 List.streams 意味着仅使用以下代码行
> 
> ```python
> yolo.predict('list.streams', stream=True)
> ```
> 
> 因此，这使得 U 使用更少的代码行进行推理，但换句话说，这意味着您获得的控制权限更少

Your idea is correct. Not using `list.streams` can indeed achieve more refined control. It would be more convenient to directly use YOLO's already integrated codes.
Of course, if there are specific requirements, such as me needing to simultaneously detect 2000 RTSP streams, I can use multiprocessing and multithreading to handle each RTSP separately and customize specific tasks. Currently, YOLO's batch processing is good enough for me to use directly, so I prefer to use `list.streams`.

**Comment by shengyu27** [comment]
> @shengyu27 check my issue #14257 i asked similar question about this. i think the difference between using multi-thread and list.streams is at control if u choose multi-thread and capture rtsp stream's frame individually, u could control FPS, capture buffer or pre/post processing or something. but if u choose list.streams it's hard to control details because u got dependencies of ultralytics
> 
> using list.streams mean that using only below code lines
> 
> ```python
> yolo.predict('list.streams', stream=True)
> ```
> 
> so, this makes u inference with less code lines but in other words that means you get less permission to control


Your idea is correct. Not using `list.streams` can indeed achieve more refined control. It would be more convenient to directly use YOLO's already integrated codes.
Of course, if there are specific requirements, such as me needing to simultaneously detect 2000 RTSP streams, I can use multiprocessing and multithreading to handle each RTSP separately and customize specific tasks. Currently, YOLO's batch processing is good enough for me to use directly, so I prefer to use `list.streams`.

**Comment by tofulim** [comment]
if using `list.streams` could manage 2000 RTSP streams then it would be the best for you.
as my task need to inference based on real-time with no-delay. when i used `yolo.track('list.streams')` with over than 10 rtsp channels i got delayed capture frames and losing connection from cv capture.

so if there are no delay it would be good for you

**Comment by shengyu27** [comment]
I suggest you check the maximum number of processing threads on the CPU. 
```
import multiprocessing
print(multiprocessing.cpu_count())
````If the set multithreading exceeds this value, there may be some threading waiting issues, which is also one of the reasons for the delay. You can try to confirm whether the CPU meets the specific resource consumption needs.

**Comment by pderrenger** [comment]
Thank you for your suggestion. Checking the maximum number of processing threads on the CPU is indeed a good starting point. If the number of threads exceeds the CPU's capacity, it can lead to delays and resource contention. Ensuring that your CPU can handle the specific resource demands of your task is crucial. If you continue to experience issues, please verify that you are using the latest version of the Ultralytics package, as updates may include performance improvements and bug fixes.
