### ISSUE TITLE
get option to save the best  model depend to not only mAP50-95, but option to choose mAP50  only 

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/ultralytics#14952]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

@glenn-jocher please give us option to save the best model despond on the mAP50 also .
as you see here the last model give us higher mAP50 than the best saved model (sorry i have to hid some information )
![11](https://github.com/user-attachments/assets/bff28b47-4188-426f-96a4-994f78a9aa65)

 

we in studies  mAP50 is the imponent to use , 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@VYRION-Ai thank you for your suggestion. Currently, the model saving criteria are based on mAP50-95, but we understand the importance of flexibility in evaluation metrics. We will consider adding an option to save the best model based on mAP50 in future updates. In the meantime, you can manually monitor the mAP50 during training and save the model checkpoints accordingly. Please ensure you are using the latest version of the package to benefit from the most recent features and improvements.
