### ISSUE TITLE
combine YOLO dataset with a custom dataset

### ISSUE THREAD

**Issue by mazik1496** [ultralytics/ultralytics#1496]
`###` Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I posted a question a few days ago, but since I uploaded it(#1477 ) on Saturday, I think I missed it, so I'm posting the question once again. I am currently combining the dataset from coco128.yaml with my custom dataset. I put the images and labels from the coco128.yaml dataset into the train, val, and test folders of the custom dataset, and added the path and class from the custom dataset's yaml file. As a result, it was confirmed that only the classes of the coco128 dataset were trained and the training of the custom dataset was omitted. Can you tell me how can I solve it? The yaml file code is:

`train: /home/user/vrx_ws/src/vrx/vrx_gazebo/nodes/train/images
val: /home/user/vrx_ws/src/vrx/vrx_gazebo/nodes/valid/images
test: /home/user/vrx_ws/src/vrx/vrx_gazebo/nodes/test/images

nc: 83
names: ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck',
        'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse',
        'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase',
        'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard',
        'tennis racket', 'bottle', wine glass', 'cup', 'fork', 'knite', 'spoon', 'bowl', 'banana', 'apple', 'sandwich',
        'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed',
        'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'ceil phone', 'microwave', 'oven',
        'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush','Bicon', 'dock', 'light_buoy']

roboflow:
  workspace: project
  project: vrx-detection
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/project/vrx-detection/dataset/1`

**Comment by AyushExel** [comment]
How do you confirm that the model was not trained on the custom dataset? Can you check if the trainer is reading all the images? You should see that in the training log before epochs start. 
If the dataset is being read, then the problem might be in the quality of the data

**Comment by mazik1496** [comment]
@AyushExel 
![image](https://user-images.githubusercontent.com/80936392/226260122-01c7601b-8f0e-4165-a342-5b290fbd5c57.png)
Looking at the pre-epoch log when training was done, I could see the following results: If there was a problem with the data quality, I think that the problem would have occurred even when the custom data was trained separately.

**Comment by AyushExel** [comment]
@mazik1496 the number of instances/images and labels are not visible in the above screenshot. You might want to capture the part that's above it. It'll list the number of images

**Comment by mazik1496** [comment]
@AyushExel Where is the number of instances / number of instances and labels marked? None of that appears.

**Comment by AyushExel** [comment]
<img width="1054" alt="Screenshot 2023-03-20 at 11 59 05 AM" src="https://user-images.githubusercontent.com/15766192/226263578-a9174290-da20-4dc9-b6ed-f16b59e64513.png">

**Comment by mazik1496** [comment]
@AyushExel 
![image](https://user-images.githubusercontent.com/80936392/226265601-962fc6d9-72cf-4c84-8661-6e443ca25cda.png)

I looked down and confirmed it. thank you the result is like this

**Comment by Laughing-q** [comment]
@mazik1496 ok then your images should be added correctly since coco128 only got 128 images but you already have 2543 images.

**Comment by mazik1496** [comment]
@AyushExel  How can I add it?? I wanted to combine the coco128 dataset and custom data, so I tried to do something similar to the method in this question(#1420), but it didn't work. can you help? I'll also give you my work files if you need them.

**Comment by AyushExel** [comment]
As @Laughing-q mentioned, based on your logs, the datasets are correctly merged. So I'm not sure why you're seeing different Results.

**Comment by mazik1496** [comment]
@AyushExel The correct merging means that the way I was doing it was correct. thank you If you need it, can I send you the files I'm working on?! You might find it helpful to look at my work files.

**Comment by Laughing-q** [comment]
@mazik1496 please tell me what's the number of your custom images.

**Comment by mazik1496** [comment]
@Laughing-q The number of custom images is 2417.

**Comment by Laughing-q** [comment]
> @AyushExel ![image](https://user-images.githubusercontent.com/80936392/226260122-01c7601b-8f0e-4165-a342-5b290fbd5c57.png) Looking at the pre-epoch log when training was done, I could see the following results: If there was a problem with the data quality, I think that the problem would have occurred even when the custom data was trained separately.

@mazik1496 there're many reasons that you get poorer results compared to the model trained with your custom dataset only. like there're too many classes introduced by coco128 but your dataset only got 3 classes which probably introduced a serious category imbalance.

**Comment by mazik1496** [comment]
@Laughing-q 
Thank you for the correct method. So, I have a question here. If you are combining correctly, you need to combine the classes together, but when you learn, only the classes of the custom data are missing. You said that the cause of this is an imbalance in the number of categories. Can you tell me what to do about this?

**Comment by Laughing-q** [comment]
@mazik1496 well that depends, and the category imbalance also is just a example, it might not be the really issue in your case. Probably add more data samples to do some experiments.
BTW have you updated the class index in the labels of your custom datasets?

**Comment by mazik1496** [comment]
@Laughing-q 
![image](https://user-images.githubusercontent.com/80936392/226274991-1b633054-7c16-46a5-acd7-bbf888f418c5.png)

yes yes. I moved the image and label files and updated the custom data's yaml file as follows.
At this time, the classes corresponding to the custom data are 'Bicon', 'dock', and 'light_buoy'.
