### ISSUE TITLE
How can I plot the segmentation masks on the original using the label.txt file

### ISSUE THREAD

**Issue by rhalder2023** [ultralytics/ultralytics#14972]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, so i have been trying to plot the mask data over an original image from the label.txt file, its a segmentation model so the txt file has mask data like class id x1 y1 x2 y2 x3 y3 .... 
and the values are normalized.

I saw in one of your issues #13900 that you guys provided a snippet of code that can do it, but when im making the mask points variable and setting the dtype to npint8 all the values are becoming 0, because the values are below 1 due the fact that they are normalized, so i was thinking that maybe that snippet wont work in this case.

And you guys do have a annotater class from utils.plotting but i didnt see any option to use it for segmentation mask plotting.

so my question would be does ultralytics have a utility that allows for plotting masks over original image using the annotation txt files or do i need to make the code myself, or if i can un-normalize these values then can i use the code mentioned in the issue #13900 ??

Thank you

**Comment by Y-T-G** [comment]
You can convert the segments to mask

https://github.com/ultralytics/ultralytics/blob/5d9046abda3d1070bc2c4bf234a1ab81f50e43e5/ultralytics/data/utils.py#L209

And then use Annotator or write a simple function with `cv2` to overlay the mask.

**Comment by rhalder2023** [comment]
> You can convert the segments to mask
> 
> https://github.com/ultralytics/ultralytics/blob/5d9046abda3d1070bc2c4bf234a1ab81f50e43e5/ultralytics/data/utils.py#L209
> 
> And then use Annotator or write a simple function with `cv2` to overlay the mask.

but doesnt the Annotator not have support for segments or masks. I mean i guess i just have to make the function right

**Comment by rhalder2023** [comment]
Well I got it to work. Thank You

**Comment by pderrenger** [comment]
Glad to hear you got it working! If you have any more questions or need further assistance, feel free to ask. Happy coding!
