### ISSUE TITLE
SAM2 negative point

### ISSUE THREAD

**Issue by quocnhat** [ultralytics/ultralytics#14982]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Sam2 negative click has not been affected yet, Do you have any plan to integrate their great feature to Ultralytics?

**Comment by pderrenger** [comment]
@quocnhat thank you for your question. Currently, SAM2's negative click feature is not integrated into Ultralytics. While we recognize its potential benefits, there are no immediate plans to add this functionality. However, we continuously evaluate new features and improvements, so stay tuned for future updates. If you have any other questions or need further assistance, feel free to ask.

**Comment by quocnhat** [comment]
Thank you for your quick response, 
Looking forward to seeing it.

**Comment by pderrenger** [comment]
@quocnhat you're welcome! We appreciate your understanding and interest. We'll keep the community updated with any new features or improvements. If you have any other questions or need further assistance, feel free to reach out.
