### ISSUE TITLE
Selecting the optimal hyperparameters

### ISSUE THREAD

**Issue by qingchengleiqing** [ultralytics/ultralytics#14986]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I select the best hyperparameters for training based on my customized YOLOv8 model and dataset? If possible, could you provide the code?

**Comment by pderrenger** [comment]
@qingchengleiqing to select the best hyperparameters for your customized YOLOv8 model and dataset, you can use the `model.tune()` method, which leverages genetic algorithms for optimization. This method iteratively adjusts hyperparameters to improve model performance. For detailed guidance, you can refer to our hyperparameter tuning documentation at https://docs.ultralytics.com/guides/hyperparameter-tuning/. If you need further assistance, feel free to ask!
