### ISSUE TITLE
Yolov8 Training - UTF-8 error

### ISSUE THREAD

**Issue by adriengoleb** [ultralytics/ultralytics#14988]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

When I run a training of a Yolov8n during 100 epochs, I have this following error which appears at the end of the 80th epoch or at the last epochs at each time.

The error message :  " 'utf-8' codec can't decode byte 0xe9 in position 139: invalid continuation byte".

I don't understand the origin of this error in this context.

**Comment by Y-T-G** [comment]
Post the full traceback.
