### ISSUE TITLE
About confusion matrix of detection validation

### ISSUE THREAD

**Issue by Tsai-chia-hsiang** [ultralytics/ultralytics#14998]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! I've tracked the code of ```my_yolo_model.val()``` for the detection task, and there is a thing about the confusion matrix that confuses me : 

About [```update_metrics(self, preds, batch)```](https://github.com/ultralytics/ultralytics/blob/9f593318542e9fc38de6b30b070673104a3c6f28/ultralytics/models/yolo/detect/val.py#L125) in  ```DetectionValidator``` at ```ultralytics/models/yolo/detect/val.py```  

https://github.com/ultralytics/ultralytics/blob/9f593318542e9fc38de6b30b070673104a3c6f28/ultralytics/models/yolo/detect/val.py#L159

And the [```process_batch(self, detections, gt_bboxes, gt_cls)```](https://github.com/ultralytics/ultralytics/blob/9f593318542e9fc38de6b30b070673104a3c6f28/ultralytics/utils/metrics.py#L317) of  ```ConfusionMatrix``` at ```ultralytics/utils/metrics.py``` 

It seems like it doesn't consider wether the classification of the predicted box is correct and just using iou matching to calculate TP :

https://github.com/ultralytics/ultralytics/blob/9f593318542e9fc38de6b30b070673104a3c6f28/ultralytics/utils/metrics.py#L367

Why doesn't it check the classification result ?

Thanks.

**Comment by Y-T-G** [comment]
It doesn't have to. If the predicted class is wrong, then it would be incrementing the corresponding gt class in that row, indicating both a false positive and false negative. If the predicted class is correct, then it will increment the correct class in the row indicating true positive.

**Comment by Tsai-chia-hsiang** [comment]
Oh I see, since it uses ```detection_classes[m1[j]]``` as the row index.
Thank you for your reply

**Comment by pderrenger** [comment]
@Tsai-chia-hsiang you're welcome! If you have any more questions or need further clarification, feel free to ask. Happy coding!
