### ISSUE TITLE
How can I change the yolov8 prediction path to an AWS S3 bucket? I want to save results directly on cloud rather than on my local system?

### ISSUE THREAD

**Issue by divyvijay** [ultralytics/ultralytics#15005]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I change the yolov8 prediction path to an AWS S3 bucket? I want to save results directly on cloud rather than on my local system?

### Additional

How can I change the yolov8 prediction path to an AWS S3 bucket? I want to save results directly on cloud rather than on my local system.

**Comment by pderrenger** [comment]
@divyvijay to save YOLOv8 prediction results directly to an AWS S3 bucket, you can modify the code to upload the results to S3 after generating them. This involves using the AWS SDK for Python (boto3) to handle the S3 interactions. Ensure you have the latest version of the Ultralytics package and boto3 installed. For detailed steps, you can refer to the [Ultralytics documentation](https://docs.ultralytics.com/integrations/amazon-sagemaker/). If you encounter any issues, please let us know.

**Comment by divyvijay** [comment]
Hey, thank you for the response. So, the results anyway will be saved to the local directory, and then we could upload the same to the S3 bucket. Right? There is no other way to directly push the results into the S3 bucket.

**Comment by pderrenger** [comment]
@divyvijay yes, that's correct. The results are initially saved to the local directory, and you can then upload them to the S3 bucket using boto3 or similar tools. Directly saving to S3 isn't supported out-of-the-box, but this two-step process is a common approach. If you need further assistance with the upload process, feel free to ask!

**Comment by RogerioLS** [comment]
Hey guys, @divyvijay I also ran into this problem recently, here is the code I used that records the artifacts in s3. It is important to remember that while the model is being trained it will have the local record but at the end of the execution it will be stored in s3.
Here is the code.
```python
import mlflow
import mlflow.pytorch
from ultralytics import YOLO
import os
import time

os.environ['WANDB_DISABLED'] = 'true'

# Configurações do AWS
os.environ['AWS_ACCESS_KEY_ID'] = ""
os.environ['AWS_SECRET_ACCESS_KEY'] = ""
os.environ['AWS_DEFAULT_REGION'] = ''

EXPERIMENT_NAME = "YOLOv8 Full Parameter Tracking"
os.environ["MLFLOW_TRACKING_URI"] = "http://ec2-"
mlflow.set_experiment(EXPERIMENT_NAME)

experiment = mlflow.get_experiment_by_name(EXPERIMENT_NAME)
print("experiment_id:", experiment.experiment_id)
print("artifact_location:", experiment.artifact_location)
print("lifecycle_stage:", experiment.lifecycle_stage)

try:
    with mlflow.start_run(experiment_id=experiment.experiment_id, run_name="detect_place_yolo") as run:
        model = YOLO('yolov8x.pt')

        # Define as tags para o experimento
        tags = {"Model": "Yolov8", "User": "",
                "TCC": "", "Approach": "best_model"}
        mlflow.set_tags(tags)

        # Loga o modelo treinado
        mlflow.pytorch.log_model(model, "model")

        # Treina o modelo YOLOv8
        results = model.train(
            data='',  # Caminho do arquivo YAML do dataset
            epochs=100,
            batch=16,
            imgsz=640
        )

        # Valida o modelo
        val_results = model.val('')

except mlflow.exceptions.MlflowException as e:
    print(f"Erro no MLflow: {str(e)}")
except Exception as e:
    print(f"Erro inesperado: {str(e)}")

print("Training completed and fully tracked with MLflow.")
``` 
Another detail is that for my architecture I am using EC2 for tracking.
I hope this helps.
