### ISSUE TITLE
Error when running fine-tuned segmentation model on Triton Inference server : Trying to create tensor with negative dimension -23: [0, -23]

### ISSUE THREAD

**Issue by atheer174** [ultralytics/ultralytics#15003]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hi, I'm facing the same issue that @songjiahao-wq had in #13548 , however, it happened to me when running my custom model using Triton Inference server. I managed to solve it by changing the DEFAULT_CFG_PATH at init.py manually to be directed to my config file DEFAULT_CFG_PATH = ROOT / "/Users/atheer/Desktop/repos/AI/runs/segment/train5/args.yaml" 

this is the error I got:
File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/utils/ops.py", line 244, in non_max_suppression output = [torch.zeros((0, 6 + nm), device=prediction.device)] * bs RuntimeError: Trying to create tensor with negative dimension -23: [0, -23]

BTW I am only facing this issue with Triton, regular usage of my custom model is fine, please help me with this because I'm planning to use more than one segmentation model, so it's not efficient to change the default config path to a static one.

thanks

### Environment

Ultralytics YOLOv8.2.67 🚀 Python-3.10.10 torch-2.0.1 CPU (Apple M2 Pro)
Setup complete ✅ (10 CPUs, 16.0 GB RAM, 378.0/460.4 GB disk)

OS                  macOS-13.2.1-arm64-arm-64bit
Environment         Darwin
Python              3.10.10
Install             pip
RAM                 16.00 GB
CPU                 Apple M2 Pro
CUDA                None

numpy               ✅ 1.23.5<2.0.0,>=1.23.0
matplotlib          ✅ 3.7.2>=3.3.0
opencv-python       ✅ 4.7.0.72>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.2>=1.4.1
torch               ✅ 2.0.1>=1.8.0
torchvision         ✅ 0.15.2>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

This is my Trition client script:
<img width="707" alt="Screenshot 2024-08-01 at 12 09 04 AM" src="https://github.com/user-attachments/assets/73eefa25-d15c-44bf-9f83-33f75ab48493">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
Which model is this?

**Comment by Misbah-AI** [comment]
> Which model is this?

I fine-tuned yolov8n-seg.pt

**Comment by atheer174** [comment]
> Which model is this?

I fine-tuned yolov8n-seg.pt

**Comment by pderrenger** [comment]
@atheer174 thank you for the information. Please ensure you're using the latest version of the Ultralytics YOLO package. If the issue persists, it might be related to Triton's handling of the model. You could try exporting the model to a different format, such as ONNX, and see if that resolves the issue. If you continue to face problems, please provide more details about your Triton configuration and any additional error logs.

**Comment by atheer174** [comment]
> @atheer174 thank you for the information. Please ensure you're using the latest version of the Ultralytics YOLO package. If the issue persists, it might be related to Triton's handling of the model. You could try exporting the model to a different format, such as ONNX, and see if that resolves the issue. If you continue to face problems, please provide more details about your Triton configuration and any additional error logs.

Thank you for your reply, I upgraded to the latest version and still facing the same issue even tho I'm using ONNX format. 

BTW as I mentioned in the issue, using a segmentation model without fine-tuning works fine, the problem is when using a custom model. 

this is the error I'm getting now:

```
Traceback (most recent call last):
  File "/Users/atheer/Desktop/repos/AI-client/yolo_client.py", line 20, in <module>
    results = model(["./image/0cd8f14b-7f12-451a-b07c-8abd00c0afde.jpeg"])  
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 173, in __call__
    return self.predict(source, stream, **kwargs)
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 563, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 261, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/models/yolo/segment/predict.py", line 30, in postprocess
    p = ops.non_max_suppression(
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/utils/ops.py", line 244, in non_max_suppression
    output = [torch.zeros((0, 6 + nm), device=prediction.device)] * bs
RuntimeError: Trying to create tensor with negative dimension -942: [0, -942]
```

**Comment by pderrenger** [comment]
Thank you for the update. Since you're experiencing this issue with a fine-tuned segmentation model on Triton, even after upgrading to the latest version and using the ONNX format, it suggests there might be a specific compatibility issue with the custom model.

Given that the problem does not occur with the base segmentation model, it could be related to the fine-tuning process or the specific configurations used. Please ensure that the model's configuration file and all dependencies are correctly set up in Triton. Additionally, check if the issue persists when using a different export format like TensorRT.

If the problem continues, please share more details about your Triton setup and any additional error logs. This information will help in diagnosing the issue more effectively.

**Comment by atheer174** [comment]
The fine-tuned segmentation model is fine when I use it directly without Triton, it produces the expected output,  I'm only facing that error when trying to infer with Triton.

I explained in the issue how I changed the config file in the Ultralytics package and that solved the problem temporarily, however, it's not practical to hard code the config file path in the package scripts. 

+ I can't use TensorRT on macOS

**Comment by Y-T-G** [comment]
Can you post the full traceback of the error?

**Comment by atheer174** [comment]
> Can you post the full traceback of the error?

(base) atheer@Atheers-MacBook-Pro-3 AI-client % python yolo_client.py           

Traceback (most recent call last):
  File "/Users/atheer/Desktop/repos/AI-client/yolo_client.py", line 20, in <module>
    results = model(["./image/0cd8f14b-7f12-451a-b07c-8abd00c0afde.jpeg"])  
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 173, in __call__
    return self.predict(source, stream, **kwargs)
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 563, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 261, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/models/yolo/segment/predict.py", line 30, in postprocess
    p = ops.non_max_suppression(
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/utils/ops.py", line 244, in non_max_suppression
    output = [torch.zeros((0, 6 + nm), device=prediction.device)] * bs
RuntimeError: Trying to create tensor with negative dimension -942: [0, -942]

**Comment by Y-T-G** [comment]
What model is this? YOLOv10?

**Comment by atheer174** [comment]
> What model is this? YOLOv10?

YOLOv8

**Comment by pderrenger** [comment]
Thank you for confirming it's YOLOv8. Given that the issue occurs only with Triton and not during direct usage, it suggests a potential compatibility issue with Triton's handling of the fine-tuned model. Please ensure you're using the latest versions of both the Ultralytics package and Triton. If the issue persists, consider sharing more details about your Triton configuration and any additional logs. This will help in diagnosing the problem more effectively.

**Comment by Y-T-G** [comment]
You can try this:
```python
# Define number of classes in your model
NUM_CLASSES = 80
model.model.names = dict(zip(range(NUM_CLASSES), range(NUM_CLASSES)))
results = model(...)
```

**Comment by atheer174** [comment]
thank you @Y-T-G for the PR, after updating the package to the latest version, I got this:

```(base) atheer@Atheers-MacBook-Pro-3 AI-client % python yolo_client.py      

Traceback (most recent call last):
  File "/Users/atheer/Desktop/repos/AI-client/yolo_client.py", line 20, in <module>
    results = model(["./image/0cd8f14b-7f12-451a-b07c-8abd00c0afde.jpeg"])  
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 173, in __call__
    return self.predict(source, stream, **kwargs)
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 563, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 234, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 639, in warmup
    self.forward(im)  # warmup
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 606, in forward
    if len(self.names) == 999 and (self.task == "segment" or len(y) == 2):  # segments and names not defined
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'AutoBackend' object has no attribute 'task'```

**Comment by Y-T-G** [comment]
@atheer174 Can you try removing the `self.task == segment`?

**Comment by Y-T-G** [comment]
Can you also try setting `task` manually after loading the model
```
model.task = "segment"
```

**Comment by atheer174** [comment]
I removed `self.task == segment` from autobackend.py here:
<img width="780" alt="Screenshot 2024-08-14 at 4 52 16 PM" src="https://github.com/user-attachments/assets/c386655c-e6c8-4dbb-8b5a-95f61bc2a24e">

and set `task` in tasks.py here:
<img width="849" alt="Screenshot 2024-08-14 at 4 52 06 PM" src="https://github.com/user-attachments/assets/01f9d213-9ab8-4d74-8474-6e48d79f81c8">

and got this:
`
Traceback (most recent call last):
  File "/Users/atheer/Desktop/repos/AI-client/yolo_client.py", line 20, in <module>
    results = model(["./image/0cd8f14b-7f12-451a-b07c-8abd00c0afde.jpeg"])  
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 173, in __call__
    return self.predict(source, stream, **kwargs)
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 563, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 261, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/models/yolo/segment/predict.py", line 52, in postprocess
    masks = ops.process_mask(proto[i], pred[:, 6:], pred[:, :4], img.shape[2:], upsample=True)  # HWC
  File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/utils/ops.py", line 673, in process_mask
    masks = (masks_in @ protos.float().view(c, -1)).view(-1, mh, mw)  # CHW
RuntimeError: mat1 and mat2 shapes cannot be multiplied (300x0 and 32x25600)`

**Comment by chuan298** [comment]
> I removed `self.task == segment` from autobackend.py here: <img alt="Screenshot 2024-08-14 at 4 52 16 PM" width="780" src="https://private-user-images.githubusercontent.com/61187989/357842972-c386655c-e6c8-4dbb-8b5a-95f61bc2a24e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMzc0NTIsIm5iZiI6MTcyNDAzNzE1MiwicGF0aCI6Ii82MTE4Nzk4OS8zNTc4NDI5NzItYzM4NjY1NWMtZTZjOC00ZGJiLThiNWEtOTVmNjFiYzJhMjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAzMTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MzY1ZjdhY2ZmNjIyOTQxMjVhMGVlMDI5ZjVjZWJjNzM1NmMxMzJjYTdmNjk0NTVhMDk0ODNjMmIxNmU2NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a5L2j8_Hsxq6U1gcUPEw90MGrZtNe1bqmrhxHW8mEps">
> 
> and set `task` in tasks.py here: <img alt="Screenshot 2024-08-14 at 4 52 27 PM" width="733" src="https://private-user-images.githubusercontent.com/61187989/357843820-a5cbb09d-e1ad-4639-842d-ebc1db3c84cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMzc0NTIsIm5iZiI6MTcyNDAzNzE1MiwicGF0aCI6Ii82MTE4Nzk4OS8zNTc4NDM4MjAtYTVjYmIwOWQtZTFhZC00NjM5LTg0MmQtZWJjMWRiM2M4NGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAzMTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZGNmOTBjYTUxMzJhOTQ1YzkyMDk2MzUwNDE3ZGUwNDM5YzI2MzA4YTNkNDQyN2JlZGUyMGFiZTA3YzNkOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hzCwxIvKj6pgkP1obl4pCNP1hnUznUup3-QPAbkzyUM">
> 
> and got this:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/atheer/Desktop/repos/AI-client/yolo_client.py", line 20, in <module>
>     results = model(["./image/0cd8f14b-7f12-451a-b07c-8abd00c0afde.jpeg"])  
>   File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 173, in __call__
>     return self.predict(source, stream, **kwargs)
>   File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 563, in predict
>     return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
>   File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
>     return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
>   File "/Users/atheer/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
>     response = gen.send(None)
>   File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 261, in stream_inference
>     self.results = self.postprocess(preds, im, im0s)
>   File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/models/yolo/segment/predict.py", line 52, in postprocess
>     masks = ops.process_mask(proto[i], pred[:, 6:], pred[:, :4], img.shape[2:], upsample=True)  # HWC
>   File "/Users/atheer/miniconda3/lib/python3.10/site-packages/ultralytics/utils/ops.py", line 673, in process_mask
>     masks = (masks_in @ protos.float().view(c, -1)).view(-1, mh, mw)  # CHW
> RuntimeError: mat1 and mat2 shapes cannot be multiplied (300x0 and 32x25600)
> ```

Hi @atheer174 , I also get same error. Have you fixed it yet?

**Comment by chuan298** [comment]
Hi @atheer174 , I just fixed the error by passing the `data="your_config.yaml"`when predicting the model. The config contains `names` key representing your custom classes.
For example my yaml config:
```
names:
  0: A
  1: B
  2: C
  3: D
```

**Comment by atheer174** [comment]
> Hi @atheer174 , I just fixed the error by passing the `data="your_config.yaml"`when predicting the model. The config contains `names` key representing your custom classes. For example my yaml config:
> 
> ```
> names:
>   0: A
>   1: B
>   2: C
>   3: D
> ```

@chuan298 Thank you! That worked 👍
