### ISSUE TITLE
Error processing character 1: OpenCV(4.10.0) /io/opencv/modules/core/src/copy.cpp:1026

### ISSUE THREAD

**Issue by yaredoguta** [ultralytics/ultralytics#15017]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

I have developed yolov8 custom model and when I test the model with some image I received below error 

Error processing character 0: OpenCV(4.10.0) /io/opencv/modules/core/src/copy.cpp:1026: error: (-215:Assertion failed) top >= 0 && bottom >= 0 && left >= 0 && right >= 0 && _src.dims() <= 2 in function 'copyMakeBorder'

Shape of input image: (1, 640, 640, 3)

Error processing character 1: OpenCV(4.10.0) /io/opencv/modules/core/src/copy.cpp:1026: error: (-215:Assertion failed) top >= 0 && bottom >= 0 && left >= 0 && right >= 0 && _src.dims() <= 2 in function 'copyMakeBorder'

Shape of input image: (1, 640, 640, 3)

Error processing character 2: OpenCV(4.10.0) /io/opencv/modules/core/src/copy.cpp:1026: error: (-215:Assertion failed) top >= 0 && bottom >= 0 && left >= 0 && right >= 0 && _src.dims() <= 2 in function 'copyMakeBorder'

Shape of input image: (1, 640, 640, 3)

Error processing character 3: OpenCV(4.10.0) /io/opencv/modules/core/src/copy.cpp:1026: error: (-215:Assertion failed) top >= 0 && bottom >= 0 && left >= 0 && right >= 0 && _src.dims() <= 2 in function 'copyMakeBorder'

Shape of input image: (1, 640, 640, 3)

Error processing character 4: OpenCV(4.10.0) /io/opencv/modules/core/src/copy.cpp:1026: error: (-215:Assertion failed) top >= 0 && bottom >= 0 && left >= 0 && right >= 0 && _src.dims() <= 2 in function 'copyMakeBorder'

Shape of input image: (1, 640, 640, 3)

Error processing character 5: OpenCV(4.10.0) /io/opencv/modules/core/src/copy.cpp:1026: error: (-215:Assertion failed) top >= 0 && bottom >= 0 && left >= 0 && right >= 0 && _src.dims() <= 2 in function 'copyMakeBorder'
a 

### Environment

Ultralytics YOLOv8.2.74 🚀 Python-3.10.12 torch-2.3.1+cu121 CPU (AMD EPYC 7B12)
Setup complete ✅ (8 CPUs, 51.0 GB RAM, 34.6/225.8 GB disk)

### Minimal Reproducible Example

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from ultralytics import YOLO
from PIL import Image, ImageDraw, ImageFont

# Define your custom class mapping
class_mapping = {0: 'ሀ', 1: 'ሁ', 2: 'ሂ', 3: 'ሃ', 4: 'ሄ', 5: 'ህ', 6: 'ሆ'}

# Load YOLOv8 model (assuming you have a trained model at 'best.pt')
model = YOLO('best.pt')

# Define the path to your images
img_path = "Addis.png"  # Update this path to your image directory
output_dir = "/content/character_images"    # Directory to save character images
os.makedirs(output_dir, exist_ok=True)

# Function to resize and pad image to 640x640
def resize_with_padding(image, target_size=640):
    h, w = image.shape[:2]
    scale = min(target_size / h, target_size / w)
    new_h, new_w = int(h * scale), int(w * scale)
    resized_image = cv2.resize(image, (new_w, new_h), interpolation=cv2.INTER_AREA)
    pad_top = (target_size - new_h) // 2
    pad_bottom = target_size - new_h - pad_top
    pad_left = (target_size - new_w) // 2
    pad_right = target_size - new_w - pad_left

    # Ensure non-negative padding values
    pad_top = max(0, pad_top)
    pad_bottom = max(0, pad_bottom)
    pad_left = max(0, pad_left)
    pad_right = max(0, pad_right)

    padded_image = cv2.copyMakeBorder(resized_image, pad_top, pad_bottom, pad_left, pad_right, cv2.BORDER_CONSTANT, value=[114, 114, 114])
    return padded_image

# Process the image
image = cv2.imread(img_path)
if image is None:
    print(f"Failed to load image: {img_path}")
else:
    print(f"Processing image: {img_path}")

    # Convert to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Apply binary thresholding
    _, binary = cv2.threshold(gray, 128, 255, cv2.THRESH_BINARY_INV)

    # Apply dilation to merge fragmented parts of characters
    kernel = np.ones((10, 6), np.uint8)
    dilated = cv2.dilate(binary, kernel, iterations=1)

    # Find contours
    contours, _ = cv2.findContours(dilated, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    # Sort contours from left to right
    contours = sorted(contours, key=lambda ctr: cv2.boundingRect(ctr)[0])

    # Loop through each contour and extract characters
    character_images = []
    for i, ctr in enumerate(contours):
        # Get bounding box for the contour
        x, y, w, h = cv2.boundingRect(ctr)

        # Filter out unwanted contours based on size and aspect ratio
        aspect_ratio = w / float(h)
        if 1500 < cv2.contourArea(ctr) < 30000 and 0.1 < aspect_ratio < 2.0:  # Adjusted thresholds
            # Extract the character
            char_img = binary[y:y+h, x:x+w]

            # Resize the character image to a fixed size (240x240 pixels) and then pad to 640x640 pixels
            char_img_resized = cv2.resize(char_img, (240, 240), interpolation=cv2.INTER_AREA)
            char_img_padded = resize_with_padding(char_img_resized, 640)

            # Save the character image
            character_images.append(char_img_padded)
            cv2.imwrite(os.path.join(output_dir, f'char_{i}.png'), char_img_padded)

    # Display the extracted characters if any characters are found
    if character_images:
        fig, axs = plt.subplots(1, len(character_images), figsize=(10, 5))
        for ax, char_img in zip(axs, character_images):
            ax.imshow(char_img, cmap='gray')
            ax.axis('off')
        plt.show()
        print(f"Collected Character Images: {len(character_images)}")

        # Predict and display the recognized characters
        for i, char_img in enumerate(character_images):
            try:
                char_img_rgb = cv2.cvtColor(char_img, cv2.COLOR_GRAY2RGB)
                char_img_rgb = np.expand_dims(char_img_rgb, axis=0)  # Add batch dimension

                # Debugging: Check the shape of the input image
                print("Shape of input image:", char_img_rgb.shape)

                # Make prediction using YOLOv8 model
                results = model(char_img_rgb)

                # Debugging: Check the results
                print("Results:", results)

                # Get the recognized character (assuming model outputs class indices)
                recognized_char_index = int(results[0].boxes.data[0, 5])  # Adjust according to your model's output format
                recognized_char = class_mapping.get(recognized_char_index, "Unknown")  # Use the class mapping

                # Create an image with the recognized character using the custom font
                char_img_pil = Image.fromarray(np.uint8(char_img)).convert('RGB')
                draw = ImageDraw.Draw(char_img_pil)
                font = ImageFont.truetype('/content/All05/AbyssinicaSIL-2.201/AbyssinicaSIL-Regular.ttf', 40)  # Adjust font size as needed
                draw.text((10, 10), recognized_char, font=font, fill=(255, 255, 255))  # Position the text and set color

                # Convert back to numpy array for displaying with matplotlib
                char_img_with_text = np.array(char_img_pil)

                # Display the recognized character with the custom font
                plt.imshow(char_img_with_text)
                plt.title(f'Recognized Character {i}')
                plt.axis('off')
                plt.show()
            except Exception as e:
                print(f"Error processing character {i}: {e}")
                continue
    else:
        print("No character images were collected.")

### Additional

![image](https://github.com/user-attachments/assets/b20943fc-776b-417d-9659-78109ff2c309)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
You can use the preprocessing from the examples:

https://github.com/ultralytics/ultralytics/blob/12bf3bf64b060c0b3acccf5dc0729e373ff174fe/examples/YOLOv8-OpenCV-ONNX-Python/main.py

https://github.com/ultralytics/ultralytics/blob/12bf3bf64b060c0b3acccf5dc0729e373ff174fe/examples/YOLOv8-OpenCV-int8-tflite-Python/main.py
