### ISSUE TITLE
OBB Yolo Model misbehaves on windows for ultralytics > 8.2.60

### ISSUE THREAD

**Issue by Skgland** [ultralytics/ultralytics#15022]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

When running the same model on ultralytics <= 8.2.60 or when running on linux my program produces the following annotated image 

![bottom annotated](https://github.com/user-attachments/assets/3f7f4b9a-8582-497d-aa07-e7f4ba6f4f4f)

only changing the ultralytics version to >= 8.2.61 (including 8.2.74) leaving everything else the same results in 

![bottom annotated](https://github.com/user-attachments/assets/df3520c8-7e35-43d6-8189-9dafef238d8f)

### Environment

Working

```
 yolo check
Ultralytics YOLOv8.2.60 🚀 Python-3.11.9 torch-2.4.0+cpu CPU (Intel Core(TM) i5-10400 2.90GHz)
Setup complete ✅ (12 CPUs, 15.8 GB RAM, 345.1/476.2 GB disk)

OS                  Windows-10-10.0.22631-SP0
Environment         Windows
Python              3.11.9
Install             pip
RAM                 15.83 GB
CPU                 Intel Core(TM) i5-10400 2.90GHz
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1.post1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.0.1>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.4.0>=1.8.0
torchvision         ✅ 0.19.0>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0
```

Broken 

```
Ultralytics YOLOv8.2.61 🚀 Python-3.11.9 torch-2.4.0+cpu CPU (Intel Core(TM) i5-10400 2.90GHz)
Setup complete ✅ (12 CPUs, 15.8 GB RAM, 345.1/476.2 GB disk)

OS                  Windows-10-10.0.22631-SP0
Environment         Windows
Python              3.11.9
Install             pip
RAM                 15.83 GB
CPU                 Intel Core(TM) i5-10400 2.90GHz
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1.post1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.0.1>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.4.0>=1.8.0
torchvision         ✅ 0.19.0>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0
```

Also broken

```
Ultralytics YOLOv8.2.74 🚀 Python-3.11.9 torch-2.4.0+cpu CPU (Intel Core(TM) i5-10400 2.90GHz)
Setup complete ✅ (12 CPUs, 15.8 GB RAM, 344.3/476.2 GB disk)

OS                  Windows-10-10.0.22631-SP0
Environment         Windows
Python              3.11.9
Install             pip
RAM                 15.83 GB
CPU                 Intel Core(TM) i5-10400 2.90GHz
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1.post1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.0.1>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.4.0>=1.8.0
torchvision         ✅ 0.19.0>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0
```

### Minimal Reproducible Example

Image/Model/Python: [reproducer.zip](https://github.com/user-attachments/files/16532056/reproducer.zip)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@Skgland thank you for the detailed report. To help us investigate this issue further, could you please confirm if the problem persists with the latest version of the Ultralytics package? Additionally, ensure that all dependencies are up-to-date. If the issue still occurs, please provide any relevant logs or error messages. This will assist us in diagnosing the problem more effectively.

**Comment by Skgland** [comment]
> @Skgland thank you for the detailed report. To help us investigate this issue further, could you please confirm if the problem persists with the latest version of the Ultralytics package? 

Yes, as stated in the Issue description this Issue persists with ultralytics 8.2.74 which is the latest version as far as I am aware.

> Additionally, ensure that all dependencies are up-to-date. 

I am pretty sure I made sure to update everything, but I will check again once I am able to tomorrow.

> If the issue still occurs, please provide any relevant logs or error messages. 

There are no relevant logs/error message the result is just completely off as shown in the sample images in the issue description and as reproducible with the MRE linked in the issue description.

**Comment by pderrenger** [comment]
@Skgland thank you for confirming that the issue persists with the latest version, 8.2.74. Since there are no relevant logs or error messages, the provided sample images and MRE are very helpful. We will investigate this discrepancy further. Please make sure all dependencies are up-to-date and let us know if you find any changes after rechecking. Your detailed report is invaluable, and we appreciate your patience as we work to resolve this.

**Comment by Y-T-G** [comment]
It's a PyTorch bug. You have to downgrade to 2.3.1/

**Comment by Skgland** [comment]
> It's a PyTorch bug. You have to downgrade to 2.3.1/

I can confirm that ultralytics 8.2.74 with torch 2.3.1 does not reproduce the problem and works as expected.

**Comment by Skgland** [comment]
> Please make sure all dependencies are up-to-date and let us know if you find any changes after rechecking. Your detailed report is invaluable, and we appreciate your patience as we work to resolve this.

After upgrading all dependencies the problem is still reproducible

<details>
<summary>yolo check</summary>

```
 yolo check                                                                                                                                                       
Ultralytics YOLOv8.2.74 🚀 Python-3.11.9 torch-2.4.0+cpu CPU (Intel Core(TM) i5-10400 2.90GHz)
Setup complete ✅ (12 CPUs, 15.8 GB RAM, 1221.0/1863.0 GB disk)

OS                  Windows-10-10.0.22631-SP0
Environment         Windows
Python              3.11.9
Install             pip
RAM                 15.83 GB
CPU                 Intel Core(TM) i5-10400 2.90GHz
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1.post1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.4.0>=1.8.0
torchvision         ✅ 0.19.0>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0
```


</details>

downgrading torch to 2.3.1 make the problem go away

<details>
<summary>yolo check</summary>

```
yolo check
Ultralytics YOLOv8.2.74 🚀 Python-3.11.9 torch-2.3.1+cpu CPU (Intel Core(TM) i5-10400 2.90GHz)
Setup complete ✅ (12 CPUs, 15.8 GB RAM, 1220.9/1863.0 GB disk)

OS                  Windows-10-10.0.22631-SP0
Environment         Windows
Python              3.11.9
Install             pip
RAM                 15.83 GB
CPU                 Intel Core(TM) i5-10400 2.90GHz
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1.post1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.3.1>=1.8.0
torchvision         ✅ 0.18.1>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0
```

</details>

alternatively downgrading ultralytics to 8.2.60 also makes the problem disappear

<details>
<summary>yolo check</summary>

```
yolo check                                                                                                                                                       
Ultralytics YOLOv8.2.60 🚀 Python-3.11.9 torch-2.4.0+cpu CPU (Intel Core(TM) i5-10400 2.90GHz)
Setup complete ✅ (12 CPUs, 15.8 GB RAM, 1221.0/1863.0 GB disk)

OS                  Windows-10-10.0.22631-SP0
Environment         Windows
Python              3.11.9
Install             pip
RAM                 15.83 GB
CPU                 Intel Core(TM) i5-10400 2.90GHz
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1.post1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.4.0>=1.8.0
torchvision         ✅ 0.19.0>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0
```

</details>

**Comment by pderrenger** [comment]
Thank you for the detailed follow-up. It appears the issue is related to the compatibility between PyTorch 2.4.0 and the latest versions of Ultralytics. Downgrading to PyTorch 2.3.1 or Ultralytics 8.2.60 resolves the problem. We will investigate this further to identify the root cause. For now, please continue using PyTorch 2.3.1 or Ultralytics 8.2.60 as a workaround. Your patience and detailed reports are greatly appreciated.
