### ISSUE TITLE
yolo export model=yolov8n.pt format=tflite int8=true dynamic=true fails

### ISSUE THREAD

**Issue by harufumigithub** [ultralytics/ultralytics#15024]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

yolo export model=yolov8n.pt format=tflite int8=true dynamic=true fails

### Environment

Ultralytics YOLOv8.2.74 🚀 Python-3.9.12 torch-1.13.1 CUDA:0 (NVIDIA GeForce RTX 3070 Laptop GPU, 7967MiB)
Setup complete ✅ (16 CPUs, 62.4 GB RAM, 209.5/245.0 GB disk)

OS                  Linux-6.5.0-45-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.9.12
Install             git
RAM                 62.44 GB
CPU                 11th Gen Intel Core(TM) i7-11800H 2.30GHz
CUDA                11.7

numpy               ✅ 1.26.3<2.0.0,>=1.23.0
matplotlib          ✅ 3.8.2>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.27.1>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 1.13.1>=1.8.0
torchvision         ✅ 0.14.1>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.7
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.1.4>=1.1.4
seaborn             ✅ 0.13.1>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

Download yolov8n.pt and run yolo export model=yolov8n.pt format=tflite int8=true dynamic=true fails

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@harufumigithub thank you for reporting this issue. To help us diagnose the problem, could you please ensure you are using the latest version of the Ultralytics package? You can update it using `pip install --upgrade ultralytics`. If the issue persists, please provide any error messages or logs generated during the export process. This information will be invaluable for us to investigate further.
