### ISSUE TITLE
Tuning the v8 model

### ISSUE THREAD

**Issue by rhalder2023** [ultralytics/ultralytics#15023]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, So ive been training a model, and i also tuned it using your model.tune() function, but I was going over your tuning docs, and in the steps there was mention of a _mutate() method that basically takes in an old set of hyperparameters to generate a new set. So is that used by the tuner function internally, or is that something we can use to tune also writing our own tuner code, And also can we make the tuner choose the optimizer also, or does it use the AdamW if we dont mention an optimizer in the function arguments? i know the other hyperparameters kinda depend on the optimizer, but like if the tuner also tuned the optimizer that would be great. so is it possible?

**Comment by rhalder2023** [comment]
And also the three arguments for augmentation, h, s and v, we provide a float as the input, so does it change the hsv space similarly for all images, or does it randomly chooses images to change the hsv values for, so im asking what it does, if its explained somewhere then a link to that also works

**Comment by rhalder2023** [comment]
Hi, so I tried to implement the randomHSV method from your augmenter class to see whats happening, Im attaching the lines of code in here, but after viewing the augmented image it looked the same as the original image, so i was wondering what am i doing wrong

![Screenshot from 2024-08-07 16-56-10](https://github.com/user-attachments/assets/b8e0cfe3-c655-41f0-9879-91b727c7fd46)

**Comment by pderrenger** [comment]
@rhalder2023 it sounds like the `randomHSV` method might not be applying the expected changes to your images. Ensure that the input parameters for hue, saturation, and value are set correctly and that the method is being called appropriately within your augmentation pipeline. If the issue persists, please check if you are using the latest version of the Ultralytics package, as updates may resolve such issues. For more detailed guidance, you can refer to the [Ultralytics documentation on augmentation](https://docs.ultralytics.com/guides/hyperparameter-tuning/).

**Comment by rhalder2023** [comment]
> @rhalder2023 it sounds like the `randomHSV` method might not be applying the expected changes to your images. Ensure that the input parameters for hue, saturation, and value are set correctly and that the method is being called appropriately within your augmentation pipeline. If the issue persists, please check if you are using the latest version of the Ultralytics package, as updates may resolve such issues. For more detailed guidance, you can refer to the [Ultralytics documentation on augmentation](https://docs.ultralytics.com/guides/hyperparameter-tuning/).

but is the code correct, like should it have applied the augmentations on the original image with just these lines, i can tweak the hsv parameter values, and i choose these values because it was the output of the tuner in the best hyperparameter file?

**Comment by rhalder2023** [comment]
> @rhalder2023 it sounds like the `randomHSV` method might not be applying the expected changes to your images. Ensure that the input parameters for hue, saturation, and value are set correctly and that the method is being called appropriately within your augmentation pipeline. If the issue persists, please check if you are using the latest version of the Ultralytics package, as updates may resolve such issues. For more detailed guidance, you can refer to the [Ultralytics documentation on augmentation](https://docs.ultralytics.com/guides/hyperparameter-tuning/).

oh yeah its working, and does ultralytics have a function that can do the exact hsv modification instead of a random one that the function chooses internally based on the input range

**Comment by pderrenger** [comment]
Glad to hear it's working! Ultralytics does not have a built-in function for exact HSV modifications; the `randomHSV` method applies changes within a specified range to introduce variability. For precise adjustments, you might need to implement a custom augmentation function. If you have further questions, feel free to ask!
