### ISSUE TITLE
engine file has metadata that makes it not work with many toolchains

### ISSUE THREAD

**Issue by rlewkowicz** [ultralytics/ultralytics#15025]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

https://github.com/NVIDIA/TensorRT/issues/2915#issuecomment-1700007024

This thread outlines it pretty well. I ran into this too with a custom c++ implementation. Ultralytics is probably one of the most popular ML toolchains on the planet now. This is maybe half bug/half request. You don't owe anyone to kinda standardize I suppose. 

It would be convenient to be able to take the engine into other ecosystems. I'm still screwing around trying to get trtexec to work on an image so I can just verify the darn engine it produces. But for better or worse it does work with my implementation (at least it compiles and runs) but I'm getting odd behavior etc.

### Environment

Windows

### Minimal Reproducible Example

Just export an engine file and try to use it with native trt tooling. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@rlewkowicz thank you for bringing this to our attention. The issue you're encountering with the metadata in the engine file is known and has been discussed in various forums, including the one you linked. To address this, please ensure you are using the latest version of the Ultralytics package, as updates often include fixes and improvements.

If the issue persists, it might be beneficial to explore different export configurations or tools that can strip or modify the metadata to improve compatibility with other toolchains. Unfortunately, we cannot provide private support, but we encourage you to continue the discussion in the community forums or submit a detailed issue if you identify a specific bug.

We appreciate your understanding and patience as we strive to improve the compatibility and functionality of our tools.
