### ISSUE TITLE
Validation dataset

### ISSUE THREAD

**Issue by Jessica-hub** [ultralytics/ultralytics#15045]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi. Can I use a different validation dataset from the one I used during training? I want to retrieve the validation results with a smaller dataset and faster.

**Comment by Y-T-G** [comment]
Yes. The results will be different of course.
