### ISSUE TITLE
Incorrect objects detected.

### ISSUE THREAD

**Issue by dcimkarthik** [ultralytics/ultralytics#15042]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

![image](https://github.com/user-attachments/assets/1ce4f73f-739c-467e-bec5-19d08b5810fb)

### Environment

Ultralytics YOLOv8.2.74 🚀 Python-3.12.2 torch-2.4.0+cpu CPU (11th Gen Intel Core(TM) i5-1145G7 2.60GHz)
Setup complete ✅ (8 CPUs, 15.7 GB RAM, 182.8/930.9 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.12.2
Install             pip
RAM                 15.69 GB
CPU                 11th Gen Intel Core(TM) i5-1145G7 2.60GHz
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1.post1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.4.0>=1.8.0
torchvision         ✅ 0.19.0>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

import cv2
import numpy as np
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('yolov8n.pt') 

# Capture video from webcam
cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print("Error: Could not open webcam.")
    exit()

while True:
    ret, frame = cap.read()
    if not ret:
        print("Error: Could not read frame.")
        break
    
    # Run the detection
    results = model.predict(frame)
    
    # Process the results
    for result in results:
        boxes = result.boxes
        for box in boxes:
            # Extract bounding box coordinates
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            
            # Extract the confidence score and class id
            confidence = box.conf.item()
            class_id = box.cls.item()
            
            # Draw the bounding box
            cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
            
            # Draw the label
            label = f'{model.names[class_id]}: {confidence:.2f}'
            cv2.putText(frame, label, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
    
    # Display the frame
    cv2.imshow('YOLOv8 Detection', frame)
    
    # Exit on 'q' key press
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the webcam and close windows
cap.release()
cv2.destroyAllWindows()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
PyTorch bug. Downgrade to 2.3.1

**Comment by Y-T-G** [comment]
Linking for reference https://github.com/pytorch/pytorch/issues/131958
