### ISSUE TITLE
How do I download an older version of ultralytics 8.1.34 and install it in editable mode. 

### ISSUE THREAD

**Issue by Jessica-hub** [ultralytics/ultralytics#15047]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How do I download an older version of ultralytics 8.1.34 and install it in editable mode.

**Comment by Y-T-G** [comment]
```
git clone https://github.com/ultralytics/ultralytics
cd ultralytics 
git checkout v8.1.31
pip install -e.
```

**Comment by Jessica-hub** [comment]
> ```
> git clone https://github.com/ultralytics/ultralytics
> cd ultralytics 
> git checkout v8.1.31
> pip install -e .
> ```
Thank you for your help! It works perfectly. Is there a way, by any chance, to check all the available previous versions of YOLOv8 for installation?

**Comment by Y-T-G** [comment]
Run  `git tag` inside the ultralytics folder.
