### ISSUE TITLE
Triton reasoning onnx model takes category names

### ISSUE THREAD

**Issue by wangyang581** [ultralytics/ultralytics#15056]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My Environment：
torch                          2.4.0
ultralytics                    8.2.75
tritonclient                   2.48.0
When I use Triton to
load my trained YOLOV8 ONNX model for inference,There is no problem with the inference of the onnx model but I cannot get the name of the detection category in the results field. 
<img width="359" alt="Snipaste_2024-08-09_16-20-47" src="https://github.com/user-attachments/assets/41b4df0c-2a0d-4644-859f-d4faffb8e11f">
<img width="795" alt="Snipaste_2024-08-09_16-14-30" src="https://github.com/user-attachments/assets/acf65185-bc97-4ef0-9370-1897c1717151">
As shown in the figure, results[0].names is not the name of the model detection category，When I use ultralytics to load the pt model locally, the code can achieve the expected results.
Of course, I can use a dictionary to map my own class names, but that isnot elegant enough. Is there any good way?

**Comment by pderrenger** [comment]
@wangyang581 thank you for reaching out. It appears that when using Triton to load your YOLOv8 ONNX model, the category names are not included in the results. This is a known limitation when exporting models to ONNX, as the class names are not embedded within the ONNX model itself.

To address this, you can manually map the class indices to their respective names using a dictionary, as you mentioned. While this might seem less elegant, it is currently the most straightforward solution. Ensure that your dictionary aligns with the class indices used during training.

If you haven't already, please verify that you are using the latest versions of the Ultralytics and Triton packages, as updates may include improvements or fixes related to this issue.

For further details on model export and handling class names, you can refer to the [Ultralytics documentation](https://docs.ultralytics.com/reference/models/yolo/classify/val/). If you encounter any other issues, feel free to ask.
