### ISSUE TITLE
Rtsp connection error robustness handling

### ISSUE THREAD

**Issue by leon2014dresden** [ultralytics/ultralytics#15057]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am using the yolo for my tracking task and rtsp connection to get data from the camera. However, when the rtsp connection breaks due to the internet connection, the tracking task breaks, too. Is there any robust handling to rtsp connection error?

The following is my code.
```
    yolo = YOLO(
        args.yolo_model if 'yolov8' in str(args.yolo_model) else 'yolov8n.pt',
    )

    results = yolo.track(
        source=args.source,
        conf=args.conf,
        iou=args.iou,
        agnostic_nms=args.agnostic_nms,
        show=args.show,
        stream=True,
        device=args.device,
        show_conf=args.show_conf,
        save_txt=args.save_txt,
        show_labels=args.show_labels,
        save=args.save,
        verbose=args.verbose,
        exist_ok=args.exist_ok,
        project=args.project,
        name=args.name,
        classes=args.classes,
        imgsz=args.imgsz,
        vid_stride=args.vid_stride,
        line_width=args.line_width
    )

    yolo.add_callback('on_predict_start', partial(on_predict_start, persist=True))

    if 'yolov8' not in str(args.yolo_model):
        # replace yolov8 model
        m = get_yolo_inferer(args.yolo_model)
        model = m(
            model=args.yolo_model,
            device=yolo.predictor.device,
            args=yolo.predictor.args
        )
        yolo.predictor.model = model

    # store custom args in predictor
    yolo.predictor.custom_args = args

    start_time = time.time()
    for frame_idx, r in enumerate(results):
        current_time = time.time()
        boxes = r.boxes.xyxy
        print(boxes)
```

**Comment by Y-T-G** [comment]
You should write your own frame grabber using cv2 and handle it.

**Comment by leon2014dresden** [comment]
> You should write your own frame grabber using cv2 and handle it.

It would be better, if you can tell me where I can edit the frame grabber inside yolov8 so that I can still keep the current code framework?

**Comment by leon2014dresden** [comment]
> Your current code will be almost the same. You will just use `source=frame` instead of `source=args.source`.

I tried with your method.
`from collections import defaultdict

import cv2
import numpy as np

from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO("yolov8n.pt")

# Open the video file
video_path = "rtsp://10.0.220.210/VideoInput/"
cap = cv2.VideoCapture(video_path)

# Store the track history
track_history = defaultdict(lambda: [])

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 tracking on the frame, persisting tracks between frames
        results = model.track(frame, persist=True)

        # Get the boxes and track IDs
        boxes = results[0].boxes.xywh.cpu()
        track_ids = results[0].boxes.id.int().cpu().tolist()

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Plot the tracks
        for box, track_id in zip(boxes, track_ids):
            x, y, w, h = box
            track = track_history[track_id]
            track.append((float(x), float(y)))  # x, y center point
            if len(track) > 30:  # retain 90 tracks for 90 frames
                track.pop(0)

            # Draw the tracking lines
            points = np.hstack(track).astype(np.int32).reshape((-1, 1, 2))
            cv2.polylines(annotated_frame, [points], isClosed=False, color=(230, 230, 230), thickness=10)

        # Display the annotated frame
        cv2.imshow("YOLOv8 Tracking", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()`

However, I got the following error:

> [rtsp @ 000002360cc92ec0] method OPTIONS failed: 404 Stream Not Found

**Comment by Y-T-G** [comment]
Seems like an issue with your network or stream link

**Comment by leon2014dresden** [comment]
> Seems like an issue with your network or stream link

However, with the previous method, given the same rtsp connection url, it worked.

    yolo = YOLO(
        args.yolo_model if 'yolov8' in str(args.yolo_model) else 'yolov8n.pt',
    )

    results = yolo.track(
        source=args.source,
        conf=args.conf,
        iou=args.iou,
        agnostic_nms=args.agnostic_nms,
        show=args.show,
        stream=True,
        device=args.device,
        show_conf=args.show_conf,
        save_txt=args.save_txt,
        show_labels=args.show_labels,
        save=args.save,
        verbose=args.verbose,
        exist_ok=args.exist_ok,
        project=args.project,
        name=args.name,
        classes=args.classes,
        imgsz=args.imgsz,
        vid_stride=args.vid_stride,
        line_width=args.line_width
    )

**Comment by Y-T-G** [comment]
Are you sure? Try removing the last `/` and is there a username and password for it? If so, add that.

**Comment by Y-T-G** [comment]
Or it should be:

`rtsp://10.0.22.21/VideoInput/1/h264/1`

That makes more sense as an RTSP link.

**Comment by leon2014dresden** [comment]
> Are you sure? Try removing the last `/` and is there a username and password for it? If so, add that.

Forgot username and passwort. I have deleted part of the link for security so that it does not look like proper one.

Part of the ultralytics code was modified and add some features. However, the original one does not have such feature. With my current version, I got the following error:
AttributeError: 'numpy.ndarray' object has no attribute 'conf'. Did you mean: 'conj'?

With the original one from ultralytics, it ran properly.

So again back to the original point, is there any way for me to increase the robustness facing the connection error with the former framework?

```
yolo = YOLO(
    args.yolo_model if 'yolov8' in str(args.yolo_model) else 'yolov8n.pt',
)

results = yolo.track(
    source=args.source,
    conf=args.conf,
    iou=args.iou,
    agnostic_nms=args.agnostic_nms,
    show=args.show,
    stream=True,
    device=args.device,
    show_conf=args.show_conf,
    save_txt=args.save_txt,
    show_labels=args.show_labels,
    save=args.save,
    verbose=args.verbose,
    exist_ok=args.exist_ok,
    project=args.project,
    name=args.name,
    classes=args.classes,
    imgsz=args.imgsz,
    vid_stride=args.vid_stride,
    line_width=args.line_width
)
```

**Comment by Y-T-G** [comment]
> However, when the rtsp connection breaks due to the internet connection, the tracking task breaks, too

When you say breaks, what do you mean?

**Comment by Y-T-G** [comment]
You could probably put this in a while loop that keeps trying to reconnect:

https://github.com/ultralytics/ultralytics/blob/d7d3449ec60081b728330749cae47e224e912813/ultralytics/data/loaders.py#L128

**Comment by Y-T-G** [comment]
I still don't understand. You mean it doesn't resume after the connection comes back?

Do you get this warning?

https://github.com/ultralytics/ultralytics/blob/d7d3449ec60081b728330749cae47e224e912813/ultralytics/data/loaders.py#L127

**Comment by leon2014dresden** [comment]
> I still don't understand. You mean it doesn't resume after the connection comes back?
> 
> Do you get this warning?
> 
> https://github.com/ultralytics/ultralytics/blob/d7d3449ec60081b728330749cae47e224e912813/ultralytics/data/loaders.py#L127

You are right. It is actually nothing to do with the tracking, because the connection can't be resumed.

I got different warning.

"[ WARN:0@30.095] global cap_ffmpeg_impl.hpp:453 _opencv_ffmpeg_interrupt_callback Stream timeout triggered after 30089.379000 ms"

And error:
"ConnectionError: 1/1: rtsp://10.0.22... Failed to open rtsp://10.0.22..."

**Comment by Y-T-G** [comment]
But that error would occur when you're trying to start the inference. Not in between the inference.

https://github.com/ultralytics/ultralytics/blob/d7d3449ec60081b728330749cae47e224e912813/ultralytics/data/loaders.py#L97

**Comment by Y-T-G** [comment]
You can change this to enter the loop even when the `cap` is not opened and then inside the loop keep trying to open it:

https://github.com/ultralytics/ultralytics/blob/d7d3449ec60081b728330749cae47e224e912813/ultralytics/data/loaders.py#L119

**Comment by leon2014dresden** [comment]
> But that error would occur when you're trying to start the inference. Not in between the inference.
> 
> https://github.com/ultralytics/ultralytics/blob/d7d3449ec60081b728330749cae47e224e912813/ultralytics/data/loaders.py#L97

You are right. I tried to reproduce the error. I got it when I started the inference.

Now i got the warning when the connection was broken during the streaming.

[ WARN:0@42.334] global cap_ffmpeg_impl.hpp:453 _opencv_ffmpeg_interrupt_callback Stream timeout triggered after 30084.995000 ms

And I got no error. The whole tracking program did not run any more after one or two minutes without receiving any error.

**Comment by leon2014dresden** [comment]
> You can change this to enter the loop even when the `cap` is not opened and then inside the loop keep trying to open it:
> 
> https://github.com/ultralytics/ultralytics/blob/d7d3449ec60081b728330749cae47e224e912813/ultralytics/data/loaders.py#L119

Have you found a way to deal with long time disconnection? I just could not resume the stream after long time disconnection.

**Comment by leon2014dresden** [comment]
> You can change this to enter the loop even when the `cap` is not opened and then inside the loop keep trying to open it:
> 
> https://github.com/ultralytics/ultralytics/blob/d7d3449ec60081b728330749cae47e224e912813/ultralytics/data/loaders.py#L119

When you try to open the cap after the disconnection, you are facing the same situation like starting the inference when the connection is not opened. After one minute, you will receive the error message

[ WARN:0@42.334] global cap_ffmpeg_impl.hpp:453 _opencv_ffmpeg_interrupt_callback Stream timeout triggered after 30084.995000 ms

**Comment by Y-T-G** [comment]
That's the timeout from FFMPEG backend used by OpenCV. If you're trying to restart, it should still work. Or you can close `cap` and recreate a new one.

**Comment by leon2014dresden** [comment]
> That's the timeout from FFMPEG backend used by OpenCV. If you're trying to restart, it should still work. Or you can close `cap` and recreate a new one.

I have just tried to build robust rtsp connection with OpenCV.

cap = cv2.VideoCapture(url3)
shape = (int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)), int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)))

#while cap.isOpened():
while 1:
    ret, frame = cap.read()
    if not ret:
        print("waiting for stream")
        #frame = np.zeros(shape, dtype=np.uint8)
        cap.release()
        cap = cv2.VideoCapture(url3)
        continue
    shape = (int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)), int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)))
    print(shape)
    cv2.imshow('VIDEO', frame)
    cv2.waitKey(1)

This time, it worked. However, after the disconnection and resuming connection, the frame size have changed. Correct one was (640, 512) before the disconnection. After resuming the connection, I got the frame size (4500, 3000).

Do you have any solution for this issue?

**Comment by Y-T-G** [comment]
You should add some `sleep` before `continue`. Like 10ms.

**Comment by leon2014dresden** [comment]
> You should add some `sleep` before `continue`. Like 10ms.

I tried.

```
cap = cv2.VideoCapture(url3)
shape = (int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)), int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)))

#while cap.isOpened():
while 1:
    ret, frame = cap.read()
    if not ret:
        print("waiting for stream")
        #frame = np.zeros(shape, dtype=np.uint8)
        cap.release()
        cap = cv2.VideoCapture(url3)
        time.sleep(0.01)
        continue
    
    shape = (int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)), int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)))
    print(shape)
    cv2.imshow('VIDEO', frame)
    cv2.waitKey(1)
```

However, it did not work. I still got different frame shape (4500, 3000) after resuming the connection.

**Comment by Y-T-G** [comment]
I am not sure why you need to get the shape? Is the actual frame also that shape after reconnection?

**Comment by leon2014dresden** [comment]
> I am not sure why you need to get the shape? Is the actual frame also that shape after reconnection?
> 
> Can you `print(frame.shape)`?

I followed your suggestion.

```
cap = cv2.VideoCapture(url3)

#while cap.isOpened():
while 1:
    ret, frame = cap.read()
    if not ret:
        print("waiting for stream")
        #frame = np.zeros(shape, dtype=np.uint8)
        cap.release()
        cap = cv2.VideoCapture(url3)
        time.sleep(0.01)
        continue
    
    print('frame shape: ', frame.shape)
    cv2.imshow('VIDEO', frame)
    cv2.waitKey(1)
```

Result:

> frame shape:  (512, 640, 3)
> frame shape:  (512, 640, 3)
> frame shape:  (512, 640, 3)
> frame shape:  (512, 640, 3)
> waiting for stream
> [ WARN:0@49.046] global cap_ffmpeg_impl.hpp:453 _opencv_ffmpeg_interrupt_callback Stream timeout triggered after 30032.839000 ms
> frame shape:  (3000, 4500, 3)
> frame shape:  (3000, 4500, 3)
> frame shape:  (3000, 4500, 3)
> frame shape:  (3000, 4500, 3)
> frame shape:  (3000, 4500, 3)

The actual frame shape has changed after the reconnection.

**Comment by Y-T-G** [comment]
I am not sure why it would change, unless it's changed from the source. Because the aspect ratio is also different. Can you test it in VLC whether it does the same thing?

Also try using 
```
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
cap set(cv2.CAP_PROP_FRAME_HEIGHT, 512)
```

**Comment by leon2014dresden** [comment]
> I am not sure why it would change, unless it's changed from the source. Because the aspect ratio is also different. Can you test it in VLC whether it does the same thing?
> 
> Also try using
> 
> ```
> cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
> cap set(cv2.CAP_PROP_FRAME_HEIGHT, 512)
> ```

VLC did not try to resume the connection. After the disconnection, it just stopped further streaming even after the connection was resumed.

For my program,
```

cap = cv2.VideoCapture(url3)

#while cap.isOpened():
while 1:
    ret, frame = cap.read()
    if not ret:
        print("waiting for stream")
        #frame = np.zeros(shape, dtype=np.uint8)
        cap.release()
        cap = cv2.VideoCapture(url3)
        cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
        cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 512)    
        time.sleep(0.01)
        continue
    

    print('frame shape: ', frame.shape)
    cv2.imshow('VIDEO', frame)
    cv2.waitKey(1)
```

However, the setting step does not have any effect on the stream after the reconnection. 

```
frame shape:  (512, 640, 3)
frame shape:  (512, 640, 3)
frame shape:  (512, 640, 3)
waiting for stream
[ WARN:0@38.957] global cap_ffmpeg_impl.hpp:453 _opencv_ffmpeg_interrupt_callback Stream timeout triggered after 30078.337000 ms
frame shape:  (3000, 4500, 3)
frame shape:  (3000, 4500, 3)
frame shape:  (3000, 4500, 3)
frame shape:  (3000, 4500, 3)
```

**Comment by leon2014dresden** [comment]
> I am not sure why it would change, unless it's changed from the source. Because the aspect ratio is also different. Can you test it in VLC whether it does the same thing?
> 
> Also try using
> 
> ```
> cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
> cap set(cv2.CAP_PROP_FRAME_HEIGHT, 512)
> ```

I solve the issue with cv2.resize

```
cap = cv2.VideoCapture(url3)
shape = (int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)), int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)))

#while cap.isOpened():
while 1:
    ret, frame = cap.read()
    if not ret:
        print("waiting for stream")
        #frame = np.zeros(shape, dtype=np.uint8)
        #cap.release()
        #cap = cv2.VideoCapture(url3)
        cap.open(url3)
        continue
    
    start = time.time()
    frame = cv2.resize(frame, dsize=shape, interpolation=cv2.INTER_CUBIC)
    end = time.time()
    print("processing time: ", end - start)
    print('frame shape: ', frame.shape)
    cv2.imshow('VIDEO', frame)
    cv2.waitKey(1)
```

**Comment by Y-T-G** [comment]
What if you restart 1 second later?

**Comment by Y-T-G** [comment]
I don't think resize is a good approach since that consumes CPU.

**Comment by leon2014dresden** [comment]
> What if you restart 1 second later?

It does not have any effect. 

The cv2.resize method is quite time-consuming, causing a latency about average 4 ms. It transfomred the image size from (3000, 4500, 3) to (512, 640, 3).

**Comment by leon2014dresden** [comment]
@Y-T-G 

Bakc to the track program. I received the warning:

> WARNING ⚠️ Waiting for stream 0
> WARNING ⚠️ Waiting for stream 0
> [ WARN:0@42.334] global cap_ffmpeg_impl.hpp:453 _opencv_ffmpeg_interrupt_callback Stream timeout triggered after 30084.995000 ms
> WARNING ⚠️ Waiting for stream 0
> WARNING ⚠️ Waiting for stream 0

I think it is not coming from the update funtion but the __next__ function https://github.com/ultralytics/ultralytics/blob/d7d3449ec60081b728330749cae47e224e912813/ultralytics/data/loaders.py#L168

How can I implement the reconnection handling in this function?

**Comment by Y-T-G** [comment]
If you correctly restarted the stream, it should resume automatically and starting appending frames to `self.imgs`

https://github.com/ultralytics/ultralytics/blob/d7d3449ec60081b728330749cae47e224e912813/ultralytics/data/loaders.py#L130

**Comment by leon2014dresden** [comment]
> If you correctly restarted the stream, it should resume automatically and starting appending frames to `self.imgs`
> 
> https://github.com/ultralytics/ultralytics/blob/d7d3449ec60081b728330749cae47e224e912813/ultralytics/data/loaders.py#L130

But I have never received the warning ""WARNING ⚠️ Video stream unresponsive, please check your IP camera connection."", which is in the update function. I doubt whether the tracking program have ever used the update function?

**Comment by Y-T-G** [comment]
If it doesn't use it, then there will be no frames in `self.imgs` ever.

**Comment by glenn-jocher** [comment]
To handle long disconnections, consider implementing a reconnection loop that attempts to reopen the stream until successful. This way, the stream can resume once the connection is restored.

**Comment by glenn-jocher** [comment]
@leon2014dresden to handle long disconnections, consider implementing a reconnection loop that attempts to reopen the stream until successful. This can help maintain the connection when interruptions occur.

**Comment by glenn-jocher** [comment]
To handle long disconnections, consider implementing a retry mechanism within the loop to continuously attempt reconnection until successful.

**Comment by glenn-jocher** [comment]
To handle long disconnections, consider implementing a retry mechanism within the loop to continuously attempt reconnection until the stream resumes.
