### ISSUE TITLE
Pytorch 2.X

### ISSUE THREAD

**Issue by N-Friederich** [ultralytics/ultralytics#1505]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi,

I think [pytorch 2 ](https://pytorch.org/get-started/pytorch-2.0/)support would be a big step from a performance technical perspective and should be implementable without much effort.

Especially the new possibility to [compile the model](https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html) would be helpful.

Thx and best regards,
Nils

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Hey, can you please start a PR if you're willing? Thanks!

**Comment by dankernel** [comment]
@AyushExel @N-Friederich 

To my knowledge, the compile feature provided in PyTorch 2.x version effectively shortens the training and inference time.
Keeping up with rapidly evolving frameworks can be very significant. 
Do you have any plans to develop or support the compile feature of PyTorch 2.x officially in the discussion?
