### ISSUE TITLE
How to decode the keypoints output by YOLO-pose？

### ISSUE THREAD

**Issue by Mauerrr** [ultralytics/ultralytics#15059]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

#13226 
I looked up the previous answer and there was a similar question. But there was no clear code level response.

I am developing a C++ depolyment that uses the YoloPose model for keypoint detection in images. The model predicts 9 keypoints for each of 5 different object categories and processes images of size 3x320x320. The output from the model is a 1x2100x36 tensor, which includes data for 4 bounding box coordinates, classification scores for 5 categories, and 3 values (x, y, visibility) for each of the 9 keypoints. 4+5+3*9=36

The problem I am facing is accurately mapping these predicted keypoints onto the corresponding positions in the original images. The bounding boxes are correct, indicating that the model and its preprocessing steps are functioning properly. Additionally, since the image dimensions are identical to the model's input size, no resizing is necessary. My model predictions are perfect in the python environment, but in the c++ deployment the detection of the box plot is correct, but the detection of the keypoints is wrong.

Here is my processing function. I just added the model output corresponding to keypoint_x and keypoint_y to the center of the block diagram. But the final result shows that this is clearly not correct. I looked through the yolo source code, and there is nothing special about the **postprocess** for the points here in _ultralytics\models\yolo\pose\predict.py_. I'm not sure if I'm processing the points correctly or if there's some other postprocessing for key points there?

```
void generate_proposals(const ncnn::Mat& out, float prob_threshold, std::vector<Object>& objects, int stride = 32, int input_width = 320, int input_height = 320) {
    int num_anchors = out.w; // Total number of anchors, each representing a candidate detection box
    int num_classes = 5; // Total number of classes
    int num_keypoints = 9; // Number of keypoints detected per object

    // Dimensions of the input image
    int img_w = input_width;
    int img_h = input_height;

    // Create a new vector to hold rearranged output data, size 2100 x 36
    std::vector<float> new_out(2100 * 36);
    // Rearrange data from the model output for easier access
    for (int i = 0; i < 36; i++) {
        for (int j = 0; j < 2100; j++) {
            new_out[j * 36 + i] = out.row(i)[j];
        }
    }

    // Extend the output vector to include an additional column for the maximum class score
    std::vector<float> extended_out(2100 * 37);
    for (int i = 0; i < num_anchors; i++) {
        float softmax_input[5];
        float softmax_output[5];

        // Extract softmax inputs for class score calculations
        for (int j = 0; j < 5; j++) {
            softmax_input[j] = new_out[i * 36 + 4 + j];
        }

        // Compute softmax to determine the most probable class
        float max_softmax_score = softmax(softmax_input, softmax_output, 5);

        // Insert the maximum softmax score into the extended output vector
        for (int j = 0; j < 4; j++) {
            extended_out[i * 37 + j] = new_out[i * 36 + j]; // Copy bounding box coordinates
        }
        extended_out[i * 37 + 4] = max_softmax_score; // Insert the max class score

        // Copy the remaining data to the extended output vector
        for (int j = 5; j < 37; j++) {
            extended_out[i * 37 + j] = new_out[i * 36 + j - 1];
        }
    }

    // Process the extended vector to generate object proposals
    for (int i = 0; i < num_anchors; i++) {
        const float* pitem = &extended_out[i * 37];

        // Retrieve bounding box coordinates and confidence score
        float cx = pitem[0];
        float cy = pitem[1];
        float width = pitem[2];
        float height = pitem[3];
        float confidence = pitem[4];

        // Filter out low-confidence boxes
        if (confidence < prob_threshold)
            continue;

        // Calculate exact bounding box coordinates
        float left = cx - width * 0.5f;
        float top = cy - height * 0.5f;
        float right = cx + width * 0.5f;
        float bottom = cy + height * 0.5f;

        // Ensure coordinates are within image bounds
        left = std::max(std::min(left, static_cast<float>(img_w - 1)), 0.f);
        top = std::max(std::min(top, static_cast<float>(img_h - 1)), 0.f);
        right = std::max(std::min(right, static_cast<float>(img_w - 1)), 0.f);
        bottom = std::max(std::min(bottom, static_cast<float>(img_h - 1)), 0.f);

        // Determine the label with the highest score
        float max_class_score = 0.0f;
        int label = -1;
        for (int j = 5; j <= 9; j++) {
            float class_score = pitem[j];
            if (class_score > max_class_score) {
                max_class_score = class_score;
                label = j - 5; // Adjust index to get the label
            }
        }

        // Create object instance
        Object obj;
        obj.rect.x = left;
        obj.rect.y = top;
        obj.rect.width = right - left;
        obj.rect.height = bottom - top;
        obj.prob = confidence;
        obj.label = label;

        // Decode keypoints based on anchor grid
        int feature_map_size = 10; // Feature map size is 10x10
        int k = 21; // Number of anchors per feature map location

        int feature_y = (i / k) / feature_map_size;
        int feature_x = (i / k) % feature_map_size;

        // Add keypoints to object
        for (int j = 0; j < num_keypoints; j++) {
            float keypoint_x = pitem[10 + j * 3]; // Updated index for new structure
            float keypoint_y = pitem[10 + j * 3 + 1];
            float keypoint_confidence = pitem[10 + j * 3 + 2];

            // Adjust keypoint coordinates based on the anchor position
            keypoint_x = (feature_x * stride + 16) + (keypoint_x * 2) - 0.5f;
            keypoint_y = (feature_y * stride + 16) + (keypoint_y * 2) - 0.5f;

            // Ensure keypoints are within bounding box bounds
            keypoint_x = std::max(std::min(keypoint_x, right), left);
            keypoint_y = std::max(std::min(keypoint_y, bottom), top);

            // Store keypoint information
            KeyPoint kp;
            kp.pt = cv::Point2f(keypoint_x, keypoint_y);
            kp.confidence = keypoint_confidence;

            obj.keypoints.push_back(kp);
        }

        objects.push_back(obj);
    }
}
```

**Comment by pderrenger** [comment]
@Mauerrr to decode the keypoints output by YOLO-pose, you need to ensure that the keypoints are correctly mapped from the model's output tensor to the original image coordinates. Given your description, it seems you are on the right track but may need to refine the post-processing steps.

First, ensure that the keypoints are correctly scaled and positioned relative to the bounding box and the original image dimensions. The keypoints' coordinates are typically normalized, so you need to scale them back to the original image size.

In your C++ code, make sure you correctly interpret the keypoints' x and y coordinates and adjust them based on the bounding box and the stride of the feature map. Also, verify that the keypoint coordinates are within the bounds of the image.

If you continue to face issues, I recommend checking the latest version of the Ultralytics repository to ensure there have been no updates or changes to the keypoint decoding process. If the problem persists, please provide more details or specific issues you encounter during the decoding process.

**Comment by Y-T-G** [comment]
Not sure what you're doing here:
```
        int feature_map_size = 10; // Feature map size is 10x10
        int k = 21; // Number of anchors per feature map location

        int feature_y = (i / k) / feature_map_size;
        int feature_x = (i / k) % feature_map_size;
```

**Comment by Mauerrr** [comment]
I've solved the problem. Normally the model export needs to be decoded, but in ultralytics the post-processing is blended into the model when the model is exported.

**Comment by pderrenger** [comment]
@Mauerrr great to hear you've resolved the issue! Yes, Ultralytics integrates post-processing into the model during export, simplifying deployment. If you have any further questions or run into other issues, feel free to ask.

**Comment by guoqi1217** [comment]
now,i want deploy yolov8 pose in android ，use ncnn format，but i cant get answer. i use yolov8 ncnn export drectly.

**Comment by glenn-jocher** [comment]
For deploying YOLOv8 pose in Android using the NCNN format, ensure you export the model with `yolo export format=ncnn`. If you encounter issues, please verify you're using the latest version of the Ultralytics package. For further guidance, refer to the NCNN documentation and Ultralytics export documentation.
