### ISSUE TITLE
IterableSimpleNamespace' object has no attribute 'fuse_score'

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/ultralytics#15053]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train, Predict

### Bug

```

Traceback (most recent call last):
  File "/home/test/lib/python3.10/site-packages/joblib/_utils.py", line 72, in __call__
    return self.func(**kwargs)
  File "/home/test/lib/python3.10/site-packages/joblib/parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
  File "/home/test/lib/python3.10/site-packages/joblib/parallel.py", line 598, in <listcomp>
    return [func(*args, **kwargs)
  File "/sshfs/tr01/d096/to/06a/wf/03_inference/acv_inference_filesystem.py", line 154, in inference
    inference_results = modeli.track(img, verbose=False, device=gpu, stream=False, classes=ipd['classes'], persist=True, tracker=ipd['tracker'], conf=ipd['conf'])
  File "/home/test/lib/python3.10/site-packages/ultralytics/engine/model.py", line 610, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "/home/test/lib/python3.10/site-packages/ultralytics/engine/model.py", line 563, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/test/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/test/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
    response = gen.send(None)
  File "/home/test/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 262, in stream_inference
    self.run_callbacks("on_predict_postprocess_end")
  File "/home/test/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 399, in run_callbacks
    callback(self)
  File "/home/test/lib/python3.10/site-packages/ultralytics/trackers/track.py", line 70, in on_predict_postprocess_end
    tracks = tracker.update(det, im0s[i])
  File "/home/test/lib/python3.10/site-packages/ultralytics/trackers/byte_tracker.py", line 297, in update
    dists = self.get_dists(strack_pool, detections)
  File "/home/test/lib/python3.10/site-packages/ultralytics/trackers/byte_tracker.py", line 378, in get_dists
    if self.args.fuse_score:
  File "/home/test/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 182, in __getattr__
    raise AttributeError(
AttributeError:
            'IterableSimpleNamespace' object has no attribute 'fuse_score'. This may be caused by a modified or out of date ultralytics
            'default.yaml' file.
Please update your code with 'pip install -U ultralytics' and if necessary replace
            /home/test/lib/python3.10/site-packages/ultralytics/cfg/default.yaml with the latest version from
            https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/default.yaml

```

### Environment

Setup complete ✅ (64 CPUs, 176.9 GB RAM, 107.6/1035.4 GB disk)

OS                  Linux-5.15.0-117-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 176.87 GB
CPU                 Intel Xeon Gold 5218R 2.10GHz
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1.post1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.4.0>=1.8.0
torchvision         ✅ 0.19.0>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

standard predict

### Additional

started with version .50?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@apiszcz it looks like you're encountering an issue with the `fuse_score` attribute in the `IterableSimpleNamespace` object. This might be due to an outdated or modified `default.yaml` file. Please ensure you are using the latest version of the Ultralytics package by running `pip install -U ultralytics`. Additionally, update your `default.yaml` file with the latest version from the [Ultralytics GitHub repository](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/default.yaml). This should resolve the attribute error you're experiencing. If the issue persists, please let us know.

**Comment by apiszcz** [comment]
update to .75 and manually replaced the default.yaml file,
I am not finding fuse_score  in any of the files including https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/default.yaml
I must be looking in the wrong location.


$ grep fuse_score ./lib/python3.10/site-packages/ultralytics/cfg/default.yaml
$


$ wget https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/default.yaml
$ grep fuse_score default.yaml
$

**Comment by arnoluken** [comment]
Hi, 
I had the same problem with the Ultralytics update. I was using my custom bytetrack.yaml and botsort.yaml files for tracking, and the new option was missing in those files. Adding this line: fuse_score: True # Whether to fuse confidence scores with the iou distances before matching to both files solved my problem. See also: [this pull request](https://github.com/ultralytics/ultralytics/pull/14965). Hope that helps!

**Comment by apiszcz** [comment]
[arnoluken](https://github.com/arnoluken) thank you, that change works, the error message leading me to other default.yaml configuration not the tracking yaml files. Now it all makes sense.

**Comment by pderrenger** [comment]
Great to hear that the solution worked for you! If you encounter any further issues or have additional questions, feel free to reach out. We're here to help.

**Comment by NatalyHofkamp** [comment]
> Hi, I had the same problem with the Ultralytics update. I was using my custom bytetrack.yaml and botsort.yaml files for tracking, and the new option was missing in those files. Adding this line: fuse_score: True # Whether to fuse confidence scores with the iou distances before matching to both files solved my problem. See also: [this pull request](https://github.com/ultralytics/ultralytics/pull/14965). Hope that helps!


You are my hero!

**Comment by glenn-jocher** [comment]
@NatalyHofkamp thank you for sharing your solution! You're correct that the `fuse_score` parameter belongs in the tracker configuration files (like `bytetrack.yaml`/`botsort.yaml`) rather than `default.yaml`. This aligns with our [tracking documentation](https://docs.ultralytics.com/modes/track/) which allows custom tracker configurations. Your proactive approach to updating custom tracker files is exactly the right way to handle such cases. 🚀
