### ISSUE TITLE
Hyperparameter Tuning using Raytune

### ISSUE THREAD

**Issue by N-Friederich** [ultralytics/ultralytics#1506]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi,

YOLov5 had a good generic algorithm. But think it would be interesting to add support for [Raytune](https://docs.ray.io/en/latest/tune/index.html). This library offers a whole range of possibilities.

I am happy to help with the development!

Greetings,
Nils

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Hey, thanks for the feature request. I've used the ray tune before and I love it. 
Can you please start a PR and we can discuss the details there? Thanks!

**Comment by sarpx** [comment]
@N-Friederich  It's a great idea to integrate, congratulations.
