### ISSUE TITLE
Pixel wise segmentation labels

### ISSUE THREAD

**Issue by N-Friederich** [ultralytics/ultralytics#1507]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi,

maybe a new way of entering segmentation labels would be interesting. Many formats have pixel wise segmentation. To bring this into the polygon format of YOLO(v5/v8 or COCO) is quite complex, reduces accuracy and is actually unnecessary (because in the end it is converted back internally).

Best regards,
Nils

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by N-Friederich** [comment]
@glenn-jocher Got it. But with a pixel by pixel segmentation you can also simply resize the mask.

**Comment by glenn-jocher** [comment]
@N-Friederich yes, true! 

I think the real problem is just dataset size. COCO is 20GB with 120k 3ch compressed jpgs, but there are 1M+ instances in the dataset, so if we used segment masks in datasets then the dataset size itself would grow unacceptably. Indeed most of the dataset size would no longer be images but labels.

**Comment by N-Friederich** [comment]
@glenn-jocher That's a good point. Maybe a possibility would be to make an internal YOLOv8 format and support different label types. My problem is: I have very small objects (sometimes only a few pixels) and a resolution of 256^2. One pixel deviation destroys everything :D

**Comment by glenn-jocher** [comment]
@N-Friederich for training there's nothing else to do unless you want to train at a higher imgsz, but for segment predict you can use retina_masks for improved resolution.

**Comment by N-Friederich** [comment]
> @N-Friederich for training there's nothing else to do unless you want to train at a higher imgsz, but for segment predict you can use retina_masks for improved resolution.

@glenn-jocher Good point, I will try this, thx!
