### ISSUE TITLE
YOLOV8 segmentation similar objects close together

### ISSUE THREAD

**Issue by qq996235826** [ultralytics/ultralytics#1508]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I use YOLOV8 to split snack boxes that are put together, and I am currently training roboflow with a data set of over 1000 images. However, when I did the split, I found that YOLOV8 seemed to split adjacent objects in a BBOX together, which caused me a lot of trouble (I also had this happen in YOLOV7). Is this a characteristic of YOLO or is there a mistake in my training?
This is result：
![result](https://user-images.githubusercontent.com/51869146/226341997-816f8cdd-cb36-49ae-9efc-99d08b1b895e.png)

This is one of the masks：
![0-LFQ-1-0 9360216](https://user-images.githubusercontent.com/51869146/226342165-a6664824-86f8-4f10-8055-d0bf977a2511.png)

I want to get a mask that only has one object, and doesn't include anything next to it, like this:
![3-LFQ-1-0 91280794](https://user-images.githubusercontent.com/51869146/226342453-73753d43-7756-4d8b-83dd-8df1b3b19112.png)

**Comment by qq996235826** [comment]
> @qq996235826 hi, With only one object in the pic the boundaries of the snack are very clear and obvious right? this could be treated as easy samples. ![image](https://user-images.githubusercontent.com/61612323/226345420-c02c33ae-f9d0-462c-ad92-53eb99af0053.png) With multiple snacks in one pic then the boundaries of the center one become impure which includes some parts of other snacks. And the center snack is a hard sample compared to other one. ![image](https://user-images.githubusercontent.com/61612323/226345466-5372d1ba-288d-4655-b7f6-a69cfb644dee.png) So I might say this could happen with only 1000 training images. You can add more samples to make the model learn better. :) Or probably modify some args of augmentations since this is boundary-related and some augmentation would cut some parts of objects.

Both masks are from one image, and I don't understand why one of them works well, but the other doesn't. Objects that seem to be in the middle of their class are more prone to this error.
But you're right, when I was training with only 200 images it was even worse than it is now.
Thanks for your suggestion, I will try to increase the number of training pictures to 5000 or even 10000, it should be able to achieve better results.
Thanks again

**Comment by jrdalenberg** [comment]
For anyone ending up here like me:

I am pretty sure that this is a Non-Maximum Suppression (NMS) problem; overlapping bounding boxes start to compete with each other since NMS regards them as multiple detections of the same object. And this problem becomes bigger when objects are diagonally placed in the image as it increases bounding box overlap. 

To overcome this problem, you could try Oriented Bounding Boxes (OBB): https://docs.ultralytics.com/datasets/obb/

**Comment by glenn-jocher** [comment]
Thank you for sharing this insight! You're correct that Non-Maximum Suppression (NMS) can cause issues with overlapping bounding boxes, and Oriented Bounding Boxes (OBB) can indeed help in scenarios with diagonal or densely packed objects. For more details, users can explore OBB implementation here: https://docs.ultralytics.com/datasets/obb/.
