### ISSUE TITLE
In yolov8, whether all models use copy paste？

### ISSUE THREAD

**Issue by yang-0201** [ultralytics/ultralytics#1509]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I found in the mmyolo project that I did not use the mask tag of the coco dataset to do copy paste data augmentation, the accuracy was lower than the official one, and only after I used it did I align the accuracy, please ask yolov8, n, s, m, l, x models all use this data augmentation method by default.

**Comment by Laughing-q** [comment]
@yang-0201 for m,l,x models we used copy-paste but for n,s models we didn't.

**Comment by yang-0201** [comment]
Thank you very much for your answer. There are still two questions: first, what is the probability of using copy paste, and second, whether all models use mask information to optimize detection boxes

**Comment by Laughing-q** [comment]
@yang-0201 0.1 for M and 0.3 for L and X if I remember this correctly. And yes all the models were trained with segment labels.
