### ISSUE TITLE
Tracking in Colab not working

### ISSUE THREAD

**Issue by mikearney** [ultralytics/ultralytics#1510]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

I assume that in order to show unique ID's in the bounding box, I need to add "show=true" to the !yolo command. But in doing this in Google Colab I receive the following error. 

---

!yolo track tracker="botsort.yaml" task=detect mode=predict model=yolov8n.pt conf=0.25 source='/content/drive/Shareddrives/Public-Drive/PB/batchvideos/goldstandard-35sec.mp4' save=True show=True

```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/usr/local/lib/python3.9/dist-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
```

### Environment

YOLO V 8.0.54

### Minimal Reproducible Example

In Google Colab run:

!yolo track tracker="botsort.yaml" task=detect mode=predict model=yolov8n.pt conf=0.25 source=pathtovideo.mp4' save=True show=True

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@mikearney try without task=detect. 
cc @Laughing-q @glenn-jocher

**Comment by mikearney** [comment]
It worked after I removed both `task=detect` and `mode=predict`

**Comment by mikearney** [comment]
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/4148169/226480976-91043e06-43a6-4596-9371-b22fcae27827.png">

**Comment by pderrenger** [comment]
@mikearney glad to hear that it worked! If you have any more questions or need further assistance, feel free to ask. 😊
