### ISSUE TITLE
Tracker State Clearing

### ISSUE THREAD

**Issue by parthapn98** [ultralytics/ultralytics#1518]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi I have a question on clearing the tracker states during repeated calling of model.track

my code straucture is roughly

```
def funcA(folder):
    rgb_file_path = get_mp4(folder)
    model = YOLO()
    results = model.track(source=rgb_file_path,
                          project=raw_data_dir_.as_posix(),
                          name="YOLOv8_Tracking_bytetrack",
                          show=show,
                          exist_ok=True,
                          save=True,
                          save_txt=True, save_conf=True,
                          verbose=False, tracker='bytetrack.yaml',
                          classes = [0,1],
                          conf=0.3, iou=0.5)

def funcB(dir):
    for sub_folders in dir:
        funcA(subfolders)

```

i have an issue when subfolders are iterated, the tracker still holds id from the prior inferences and uses new track-ids

Is there any way i can disable this?

**Comment by parthapn98** [comment]
HI @Laughing-q  I had assumed a similar behaviour and thus structured the code in this manner. However then I should report this as a bug.

Is there possibly something in the model.track parameters I'm setting that could cause this?
Can you try a similar set of code on your end to see if it is replicable?

**Comment by Laughing-q** [comment]
@parthapn98 wait, you mean the `sub_folders` in your case are iterated, so I suppose you probably have multiple videos in `sub_folders`?

**Comment by parthapn98** [comment]
@Laughing-q no each subfolder has 1 video only, i replaced the names for the directory and variables for privacy reason and code conciseness

get_mp4() returns the path to the single mp4 file in the subfolder and model.track is run once with a single path

when executed we get sth like

video 1: person_id 1 and 2
video 2: person_id 3 and 4
video 3: person_id 5 and 6


the ids are not always consequential, however I think the skips can be attributed to when people are moving out of frame, it misses some detections and instead of reacquiring it inits a new track(this is not a problem for us)

However we would like to know if something might have gone wrong in our implementation st, the tracks are not always 1/2/3 and keep increasing for subsequent videos

**Comment by parthapn98** [comment]
@Laughing-q 

Thank you for the quick fix, 
Query, given i was using the pip installation to work with yolo, 
How long for this patch to be released there and should i instead switch to the source installation?

**Comment by glenn-jocher** [comment]
@parthapn98 8.0.56 will be released this week.
