### ISSUE TITLE
Inference failed running Yolov8CPPInference failed

### ISSUE THREAD

**Issue by Zhaonb** [ultralytics/ultralytics#1522]
obt@ubuntu:~/workspace/NNF/yolov8_CPP_Inference_OpenCV_ONNX/build$ ./Yolov8CPPInference 
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.6.0) /home/obt/workspace/opencv-4.6.0/modules/dnn/src/onnx/onnx_importer.cpp:255: error: (-5:Bad argument) Can't read ONNX file: /home/.../yolov8_CPP_Inference_OpenCV_ONNX/source/models/yolov8s.onnx in function 'ONNXImporter'

Aborted (core dumped)

**Comment by AyushExel** [comment]
@JustasBart might know the answer to this

**Comment by Zhaonb** [comment]
Thanks, ask JustasBart later.

**Comment by Zhaonb** [comment]
Thanks, ask JustasBart later.

**Comment by JustasBart** [comment]
@Zhaonb This seems like a duplicate? Have you changed the path in the **main.cpp**? Is this resolved?
