### ISSUE TITLE
Parameter`model` is not working

### ISSUE THREAD

**Issue by ToddGuo** [ultralytics/ultralytics#1523]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I downloaded the weight file (path: "./weights/yolov8m.pt") and assigned its path to parameter `model` during training, but it is still trained with "yolov8n. pt". Did I enter the wrong command? Here is the screenshot.
![1](https://user-images.githubusercontent.com/49402628/226507633-391da45f-a381-4d5c-b054-00e3510530e6.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@ToddGuo well I think that's because we are checking the availability of amp with `yolov8n.pt` by default, so it downloaded yolov8n.pt automatically. :)

**Comment by Laughing-q** [comment]
@ToddGuo I'm closing the issue. Please feel free to reopen it if you still have related issues. :)
