### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by FXNE** [ultralytics/ultralytics#15246]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

As a starter in YOLO, I'm having some issues during running this program.
In some particular tasks such as detecting, the VS code will report "NotImplementedError",  however, some tasks  such as classification will not report this error, how can I fix it?

![image](https://github.com/user-attachments/assets/4ab092bd-6405-40c2-8c06-2a144c2df840)

**Comment by Y-T-G** [comment]
You have to reinstall PyTorch. First uninstall torch and torchvision.

`pip uninstall torch torchvision`

Then follow the command it gives here:

https://pytorch.org/get-started/locally/

**Comment by FXNE** [comment]
> You have to reinstall PyTorch. First uninstall torch and torchvision.
> 
> `pip uninstall torch torchvision -y`
> 
> Then follow the command it gives here:
> 
> https://pytorch.org/get-started/locally/

THANK YOU!!!

The problem was solved immediately! This is real magic!

**Comment by pderrenger** [comment]
@FXNE i'm glad to hear that resolved your issue! If you have any more questions or run into any other problems, feel free to ask. Happy coding!
