### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by Rua-Zi** [ultralytics/ultralytics#15248]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Val

### Bug

This is my first time raising an issue on GitHub, please let me know if I'm not thoughtful enough.

I am working on a segmentation model for fabric defect detection for a university. For privacy reasons, I have erased the name of the university. Please forgive me for any inconvenience.

This bug first appeared when I used my fabric dataset for segmentation training. At that time, I thought it was a bug caused by labeling issues. After that, I upgraded ultralystics to the latest version and tested it with the COCO dataset, and found that the bug still exists.

You can see that there are always NaN values ​​in val/box_loss, val/cls_loss, and val/dfl_loss. I would like to ask if these three values ​​are NaN, will it affect the other results of model evaluations? If so, I think I need to export the model and use other methods to evaluate my model.

Bug screenshot:

![bug3](https://github.com/user-attachments/assets/7397cde5-9357-435c-a787-67707e423cd1)

Here is one of the results on fabric segmentation:

![results](https://github.com/user-attachments/assets/b18399ca-f6a7-4f75-920b-7044b65d1eff)

Here is the test result of the COCO dataset:

![results](https://github.com/user-attachments/assets/fe61393f-3bcf-4789-ae3f-688e5ffad301)

### Environment

Ultralytics YOLOv8.2.75 🚀 Python-3.10.11 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1660 Ti, 6144MiB)
Setup complete ✅ (12 CPUs, 31.8 GB RAM, 1180.5/1386.1 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.10.11
Install             pip
RAM                 31.77 GB
CPU                 Intel Core(TM) i7-10750H 2.60GHz
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.0>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.3.1+cu121>=1.8.0
torchvision         ✅ 0.18.1+cu121>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

from ultralytics import YOLO

if __name__ == '__main__':

    model = YOLO("yolov8n-seg.yaml")
    model = YOLO("yolov8n-seg.pt")
    model = YOLO("yolov8n-seg.yaml").load("yolov8n.pt")

    model.train(data="coco8-seg.yaml", epochs=10, imgsz=640,amp =False)

    results  = model.val()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
It's a from with your GPU. Add `amp=False` and `half=False` to your training command.

**Comment by Rua-Zi** [comment]
> It's a problem with your GPU. Add `amp=False` and `half=False` to your training command.

Thanks for your help, the error does not occur now.

I would like to ask if I just do the segmentation task, do I need to concern about the val/box_loss, val/cls_loss, and val/dfl_loss? In that case, is it reasonable for them to have NaN values? The values of train/box_loss, train/cls_loss, and train/dfl_loss exist and the values of validation are NaN makes me confuse.

**Comment by Rua-Zi** [comment]
Here is the screenshot of the results in the COCO dataset which I apply amp=False and half=False:

![results](https://github.com/user-attachments/assets/63ce170d-e0b9-4ca9-9e6d-2a39d99f0ef4)

**Comment by Y-T-G** [comment]
It could be because validation uses FP16 which your GPU has problems with.

https://github.com/ultralytics/ultralytics/blob/63e26e1fc8a2f96199c9ae6ecb26c13ba880a072/ultralytics/engine/validator.py#L115

You could try using this to override `half()` method:
```python
def override_half(trainer):
    trainer.model.half = lambda x: trainer.model

model.add_callbacks("on_train_start", override_half)
```

Add these after you load the model before you start training.

**Comment by Rua-Zi** [comment]
> It could be because validation uses FP16 which your GPU has problems with.
> 
> https://github.com/ultralytics/ultralytics/blob/63e26e1fc8a2f96199c9ae6ecb26c13ba880a072/ultralytics/engine/validator.py#L115
> 
> You could try using this to override `half()` method:
> 
> ```python
> def override_half(trainer):
>     trainer.model.half = lambda x: trainer.model
> 
> def override_args(validator):
>     validator.args.half = False
> 
> model.add_callback("on_train_start", override_half)
> model.add_callback("on_val_start", override_args)
> ```
> 
> Add these after you load the model before you start training.

Hi, thanks for your reply.

Here is my code now:

```
if __name__ == '__main__':
    model = YOLO("yolov8n-seg.yaml").load("yolov8n-seg.pt")


    def override_half(trainer):
        trainer.model.half = lambda x: trainer.model


    def override_args(validator):
        validator.args.half = False


    model.add_callback("on_train_start", override_half)
    model.add_callback("on_val_start", override_args)

    model.train(data="coco8-seg.yaml", epochs=5, imgsz=640, amp=False, half=False)

    results = model.val()
```
Looks like a new error occurred:

![bug4](https://github.com/user-attachments/assets/5e597ee0-7cad-4dcc-86e7-c85a4823029a)
![bug5](https://github.com/user-attachments/assets/1ccf88d5-01b5-4513-b641-ab86fa8ca6cb)


I tried reinstalling ultralytics, not overriding half(), and only applying amp=False and half=False, and the old error reappeared.

Here is my yolo check now:

Ultralytics YOLOv8.2.76 🚀 Python-3.10.11 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1660 Ti, 6144MiB)
Setup complete ✅ (12 CPUs, 31.8 GB RAM, 1180.7/1386.1 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.10.11
Install             pip
RAM                 31.77 GB
CPU                 Intel Core(TM) i7-10750H 2.60GHz
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.0>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.3.1+cu121>=1.8.0
torchvision         ✅ 0.18.1+cu121>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

I am new to AI and less experienced in using GPU acceleration, and these errors confuse me.

**Comment by Y-T-G** [comment]
Try
```python
def override_half(trainer):
    trainer.model.half = trainer.model.float

def override_args(validator):
    validator.args.half = False

model.add_callback("on_train_start", override_half)
model.add_callback("on_val_start", override_args)
```

**Comment by Rua-Zi** [comment]
> Try
> 
> ```python
> def override_half(trainer):
>     trainer.model.half = trainer.model.float
> 
> def override_args(validator):
>     validator.args.half = False
> 
> model.add_callback("on_train_start", override_half)
> model.add_callback("on_val_start", override_args)
> ```

The error still occur:

RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same

And here is my code now:

```
if __name__ == '__main__':
    model = YOLO("yolov8n-seg.yaml").load("yolov8n-seg.pt")


    def override_half(trainer):
        trainer.model.half = trainer.model.float


    def override_args(validator):
        validator.args.half = False


    model.add_callback("on_train_start", override_half)
    model.add_callback("on_val_start", override_args)

    model.train(data="coco8-seg.yaml", epochs=5, imgsz=640, amp=False, half=False)

    results = model.val()
```

**Comment by Y-T-G** [comment]
I edited the code. Test it again.

**Comment by Rua-Zi** [comment]
> I edited the code. Test it again.

Here is the result now:
![results](https://github.com/user-attachments/assets/2d2b4045-f79c-414a-aacb-ed50d2385b52)

This seems to work well in the COCO dataset now, I will test it on my dataset. 

Thanks for your help, I hope you have a good day.

**Comment by Y-T-G** [comment]
@glenn-jocher I think this is a bug. If `amp=False`, it shouldn't force validation with `half` during training.

**Comment by Y-T-G** [comment]
It's also related to thsi:
https://github.com/ultralytics/ultralytics/issues/14929#issuecomment-2268398319

**Comment by Y-T-G** [comment]
It's also related to this:
https://github.com/ultralytics/ultralytics/issues/14929

**Comment by Y-T-G** [comment]
@Gnoot01 Is your loss nan?

**Comment by Gnoot01** [comment]
> @Gnoot01 Is your loss nan?

Yep

```
Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size       
      50/50      8.85G        nan        nan        nan        nan        nan         20        640: 100%
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P      
                   all         20         75          0          0          0          0          0          0          0          0
```

**Comment by Y-T-G** [comment]
@Gnoot01 Try training with `amp=False`

**Comment by Gnoot01** [comment]
Thanks it worked! The "preds".jpg also didn't show because of this issue, as it had trouble "drawing". 

For education purposes, may I ask what this amp does? and would simply changing my GPU help?

**Comment by Y-T-G** [comment]
@Gnoot01 AMP is used to speed up training speeds.

You have a problematic GPU that doesn't support it:

https://www.reddit.com/r/Ultralytics/comments/1eqfl7t/psa_gpus_that_have_issues_with_amp_training/

Using a GPU that's not one of the ones mentioned above, it should work fine.

You can also try using `batch=3` and `amp=True`. It reportedly works fine at that batch size.
