### ISSUE TITLE
MLFlow Integration

### ISSUE THREAD

**Issue by yoloyash** [ultralytics/ultralytics#1525]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hello, I see that yolov8 does an amazing job at logging. I would like to contribute by adding the support of MLFlow into it. Please let me know if this can be done or not. @AyushExel @glenn-jocher 
Similar issue: #199

### Use case

Better logging

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by N-Friederich** [comment]
@yoloyash Sounds interesting, but why not ClearML and Comet (they are already implemented)? :)

**Comment by yoloyash** [comment]
> @yoloyash Sounds interesting, but why not ClearML and Comet (they are already implemented)? :)

Hello, both ClearML and Comet are solid options and offer many features. However, many teams use MLFlow for logging in their local databases as mentioned in #199. I had to code it for for my team and there aren't any resources out there for doing it. So that's why I offered :)

**Comment by N-Friederich** [comment]
@yoloyash Ah ok, good point :) So, you can take a look at the examples in https://github.com/ultralytics/ultralytics/tree/main/ultralytics/yolo/utils/callbacks and develop something similar for MLFLow following the example of Comet and clearml

**Comment by yoloyash** [comment]
> @yoloyash Ah ok, good point :) So, you can take a look at the examples in https://github.com/ultralytics/ultralytics/tree/main/ultralytics/yolo/utils/callbacks and develop something similar for MLFLow following the example of Comet and clearml

I'm new to contributing to open source. Seems like you are new too! Can you help me out to get started? :)

**Comment by N-Friederich** [comment]
@yoloyash I don't know in how far this is interesting for the whole project (@glenn-jocher  @yoloyash). Otherwise, implement it and create a PR. My advice is to follow (as said above) the structure of the existing logging tools and follow the [MLFlow tutorials](https://mlflow.org/docs/latest/tutorials-and-examples/tutorial.html).

**Comment by glenn-jocher** [comment]
@N-Friederich yes this would be a great integration! You could use Comet and ClearML and examples for how to implement here:
https://github.com/ultralytics/ultralytics/tree/main/ultralytics/yolo/utils/callbacks

**Comment by glenn-jocher** [comment]
Thank you for creating a Pull Request! I would be happy to discuss merging it into the main branch. Could you please provide some details about what changes are included in the PR and what issues it addresses? Once I have a better understanding of the changes, I can share my feedback and we can proceed from there.

**Comment by Bartosz-Lewandowski** [comment]
Does anyone know how to later use the registered YOLO model? I can't see any custom function for mlflow. I don't know if I do something wrong, but when I call PyFuncModel on img data it returns nothing.
