### ISSUE TITLE
Questions regarding 'batch' and 'workers' arguments.

### ISSUE THREAD

**Issue by Stefanus1235** [ultralytics/ultralytics#15264]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

1. According to an answer by @glenn-jocher in [Batch Size per GPU options](https://github.com/ultralytics/ultralytics/issues/13328#issuecomment-2145646381), all GPUs involved in training uses batch size equal to value provided by 'batch' argument, but when I try to train with `batch=16` and two GPUs (`devices=[0,1]`), the given train_batchX only contain eight images as shown below. Doesn't this mean the batch size used by each gpu is 8 instead of 16, and I have to multiply the intended 'batch' value with my number of GPUs for training?
![train batch](https://github.com/user-attachments/assets/8f53a62b-d545-4858-9919-fdee41d77e8d)
2. Is it correct to say that 'workers' argument only influence number of workers for data loading, hence only affect training speed instead of training result? Does it have to match my CPU count? What happen if my CPU count is lower than 'workers' value -- say, 4 cores to default `workers = 8`?

Thank you.

**Comment by Y-T-G** [comment]
1. Yes, you have to multiply and it has to be divisible by the number of GPUs.
2. There's no point in doing that since you are not gaining any performance (or even losing some). You will probably see a warning too. It doesn't affect results.
