### ISSUE TITLE
manipulate window when show=True

### ISSUE THREAD

**Issue by ratishbambang** [ultralytics/ultralytics#1528]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

`results = model.predict(source="0", show=True)`

when inferencing on webcam/video, i cannot close the window(show=true) and stop unless ctrl c is given to terminal. 
how close and stop?

if inference image, i use

```
cv2.waitKey(0)
cv2.destroyAllWindows()
```

**Comment by AyushExel** [comment]
Pressing `Q` key stops the process for me
