### ISSUE TITLE
Switching between projects using a relative dataset directory fails.

### ISSUE THREAD

**Issue by netbrain** [ultralytics/ultralytics#1530]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

```
    if not path.is_absolute():
        path = (DATASETS_DIR / path).resolve()
```
Will resolve to the incorrect dir in `ultralytics/yolo/data/utils.py:220` if you have multiple ultralytics projects where datasets are specified in terms of relative directories.

This happens because ultralytics apparently has a configuration file in (path dependent on os) and in said file there is a datasets_dir value that is being used when the abovementioned code is hit.

It will work fine for project A which has the correct datasets_dir, but for project B it will resolve to an incorrect dir, resulting in something along the lines of:

```
Dataset 'x.yaml' images not found ⚠️, missing paths ['/home/user/dev/project1/datasets/x/valid.txt']
.....
OSError: [Errno 39] Directory not empty: '/home/user/dev/project2/datasets/x'
```

I believe the code should be changed to:

```
    if not path.is_absolute():
        path = (os.getcwd() / path).resolve()
```

This may only be an issue if you your data.yaml file has a download section

### Additional

Would be good if the solution would have a means to support multiple projects instead of relying on what is effectively a singleton outside of the project. One solution could be to use environment variables that define the current configuration file to be used.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@netbrain you can view your global settings and adjust as you see fit with `yolo settings`
