### ISSUE TITLE
Non-Ascii Characters

### ISSUE THREAD

**Issue by Rockntt** [ultralytics/ultralytics#15312]
@Papuszkin I can reproduce with the non-ascii characters in a class name. I'll try to debug the issue and push a fix.

_Originally posted by @glenn-jocher in https://github.com/ultralytics/ultralytics/issues/1979#issuecomment-1505913227_

Hi, Glenn!

I trained a yolov8 for finding symbols from armenian language on pictures (my task for computer vision contest) and it is GREAT! But I'm bumping into problem with annotating letters on my images.

How I am doing it:
```python
annotator.box_label(b, "Ա")``` (this exact letter was put here for example)
```
I'm getting error exactly like in the issue i've replied to earlier.
```    self.draw.rectangle(box, width=self.lw, outline=color)  # box
    ^^^^^^^^^
AttributeError: 'Annotator' object has no attribute 'draw'```

Looking for some help!

**Comment by glenn-jocher** [comment]
@Rockntt non-ascii characters in class names should work correctly. If not please provide a minimal reproducible example. 

For Annotator usage documentation see https://docs.ultralytics.com/reference/utils/plotting/#ultralytics.utils.plotting.Annotator

**Comment by Rockntt** [comment]
Thanks for your answers. Now I don't have any need to use ascii-symbols in my project so I stale this issue. 
If I will have any time in future I'll try to reproduce this problem again and extend this/new issue about non-ascii characters.

**Comment by glenn-jocher** [comment]
You're welcome! If you encounter the issue again in the future, please feel free to reopen or create a new issue with additional details.
