### ISSUE TITLE
Is API call of model.predict slower than cli command?

### ISSUE THREAD

**Issue by gabriel-joy** [ultralytics/ultralytics#1536]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I have a folder of images that needs to be adjusted first with openCV, after that I'm using detection.

API calling of model.predict is slower that using cli command

#CLI:
yolo task=detect mode=predict model=data/small1004.onnx  source=output/sb9/* conf=0.7 iou=0.8 save=True

#API:

    img0 = cv2.imread(file)  # BGR

 #Run inference

    t0 = time.time()

    results = model.predict(source=img0, save=False, save_txt=False, imgsz=imgsz, conf=oconf_thres, iou=oiou_thres, verbose=False)
   
    t = (time.time() - t0)*1000

# t is around 3x-4x bigger than inference time reported by the CLI command. what is wrong with my code?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@gabriel-joy time package is not a reliable profiling method with cuda inference. See https://discuss.pytorch.org/t/how-to-measure-execution-time-in-pytorch/111458

**Comment by gabriel-joy** [comment]
@glenn-jocher 

I confirm that I use CPU.

I measured the batch processing (passing the folder location as source) in the same way and the time is similar with sequence detection, nevertheless 3x-4x bigger than what is shown in the cli command. why is that? 

test code:
import cv2 
import numpy as np 
import time 
import pprint
import configparser
import argparse
import os


from ultralytics import YOLO
from ultralytics.yolo.utils.plotting import Annotator

#init arguments
parser = argparse.ArgumentParser()
parser.add_argument ('-s','--studio', help='input studio')
parser.add_argument ('-t','--type', help='batch/sequence')
parser.add_argument ('-m','--model', help='model.pt')

args = vars(parser.parse_args())
checkDir = args['studio']
type = args['type']
modelFile = args['model']

pp = pprint.PrettyPrinter(indent=4)

model = YOLO(modelFile)
numFiles = 0;
 
t0 = time.time()

if type == 'batch':
    results = model.predict(source=checkDir, device='cpu', save=False, save_txt=False, imgsz=160, conf=0.7, iou=0.8, verbose=False, max_det=3)  # save predictions as labels
    numFiles = len(results)
else:
    for file in os.listdir(checkDir):
        if file.endswith("jpg"):
            img0 = cv2.imread(os.path.join(checkDir, file))  # BGR
            results = model.predict(source=img0, device='cpu', save=False, save_txt=False, imgsz=160, conf=0.7, iou=0.8, verbose=False, max_det=3)  # save predictions as labels
            numFiles +=1
            
#pp.pprint(results)

if numFiles>0:
    print('%d Files, AVG Prediction Time:%.2f ms' % (numFiles, (time.time() - t0)*1000/numFiles))

**Comment by Laughing-q** [comment]
@gabriel-joy well there are some reasons that you got slower speed with `model.predict`.
- the first time you run `model.predict` it need to initialize the predictor which could cost some time.
- also it needs time to set up source
- if you set `save=True`  or `show=True` then it needs to plot images that also could cost time.
- speed from cli logs are pure speed of `preprocess`, `inference` and `postprocess` without any other time like above two.

BTW the cli mode is actually using `model.predict` inside, so basically there's no difference between cli mode and python interface.

**Comment by gabriel-joy** [comment]
@Laughing-q 

Sorry, I think I missed that. I had a look on def stream_inference in https://docs.ultralytics.com/reference/base_pred/#ultralytics.yolo.engine.predictor.BasePredictor and is clear now.

Thank you.
