### ISSUE TITLE
Is it possible to obtain the coordinates of occluded keypoints?

### ISSUE THREAD

**Issue by Javacr** [ultralytics/ultralytics#15379]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/user-attachments/assets/07f06730-4b9e-4358-afa9-b94978762deb)

When using YOLO-Pose, in many cases, when certain keypoints of a person are occluded, their values are (0, 0, 0). This, of course, relates to the original training dataset, as the COCO dataset does not include keypoint coordinates for occluded parts of the person. How can we use the current pre-trained weights（your official weights） to obtain the coordinates of these types of keypoints?"
I have searched similar questions, but those issues dosen't solve my problem. https://github.com/ultralytics/ultralytics/issues/7153, https://github.com/ultralytics/ultralytics/issues/13582

**Comment by Y-T-G** [comment]
You will have to retrain with a dataset that includes occluded keypoints.
