### ISSUE TITLE
Cannot change device ID after load last-trained checkpoints

### ISSUE THREAD

**Issue by yang-fei** [ultralytics/ultralytics#15378]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

problem: 
When load last-trained checkpoints, I want to start a new training. Thus, I set the device=1 while the last-training was done on device=0. This training will be still on device 0. 

I do some checks: 
1. when start a new training without pre-loading any weights, it is OK to set the device ID. 
2. Loading the official pretrained weights (e.g yolov8s-seg) provided by ultralytics is OK to set the device ID
3. I located the code:  nn/tasks.py/torch_safe_load
<img width="743" alt="image" src="https://github.com/user-attachments/assets/21d0424d-d72f-464c-99c2-1008d4daea07">

if we set os.environ['CUDA_VISIBLE_DEVICES'] = 1 before the 'torch.load(file, map_location="cpu")', it is OK to set the gpu id. If we set the gpu id after that torch loading code, the gpu id setting is ineffective. 

So we compare the weights of that official previded and the weights ultralytics saved. We found that: the weights ultralytics saved (e.g. best.pt) contains the "updates: " values with the 'devices: cuda:0'. 

So I think the reason is that: 
When loading the last-trained weights, pytorch will do the gpu initialization, thus the last-trained weights contains the values that indicate the device on gpu. Even the torch loading code contains the map_location='cpu‘， pytorch will still initialize the gpu and load the model on cpu. Once the gpu is initialized, the scripts will see all the gpus. The gpu id setting after that is ineffective. 

The solution I think: 
1. Do not load last-trained weights, you can set the device id. 
2. Remove the device:cuda:0 from your weights, thus you can load the pre-trained weights just like that as the official previded. 
3. Set os.environ['CUDA_VISIBAL_DEVICES'] = '1' (you set gpu id) before loading your pre-trained weights.
4. Could the ultralytics team solve this little bug? 
    1) try to remove the device:cuda:0 from the saved weights?  Will this affect the resume process? 
    2) use other methods to set cuda devices? Will this affect multi-gpu training?

Currenly, I just found this, I don't have an idea to modify the code neatly. 

### Environment

.

### Minimal Reproducible Example

.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
What if you train with `model.train(..., device=torch.device("cuda:1"))`? 

Does it work?

**Comment by yang-fei** [comment]
> What if you train with `model.train(..., device=torch.device("cuda:1"))`?
> 
> Does it work?

Yes it can work. In this way, pytorch has initialized all gpus before. And we just forced the training on the second gpu.  Because when write the format: "cuda:1", the function select_device will just return device. 
<img width="669" alt="image" src="https://github.com/user-attachments/assets/3578d418-c4e4-493c-823e-335999535dcf">

But in this way, how to set multi-gpu training from the beginning?

**Comment by pderrenger** [comment]
@yang-fei thank you for the detailed explanation. To address your concern about multi-GPU training from the beginning, you can specify multiple GPU IDs directly in the `device` argument, such as `device=[0, 1]`. This should ensure that the training process utilizes both GPUs right from the start. Please try this approach and let us know if it resolves the issue. If the problem persists, ensure you are using the latest version of the Ultralytics package.

**Comment by Y-T-G** [comment]
@yang-fei So the model is initially loaded on the trained GPU?
