### ISSUE TITLE
YOLOv9 Model Fails to Detect 2 Classes: Only Detects 1 Class

### ISSUE THREAD

**Issue by janelyd** [ultralytics/ultralytics#15382]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i have been working on MR images with yolov9. i have 2 classes and theyre named as "1" , "2".  
* i'm doing an intanstance segmentation with yolov9
* i have 2 classes named "1" and "2". 

![image](https://github.com/user-attachments/assets/1193b0b0-1e02-47fa-a8eb-ff41f50df1b4)

according to my model's result, the confusion matrix seems so well. but when it comes to implement the segment/predict .py  i am facing with this issue: guessing the "1" class as "1" class(which is true). But also guessing the "2" class as "1" class. 

i've checked my train,val,test dataset and labels checked. 

why could am i detecting only 1 class?

**Comment by Y-T-G** [comment]
What's your predict code?

**Comment by janelyd** [comment]
> What's your predict code?

!python segment/predict.py  --weights /content/drive/MyDrive/staj_hafta3.2/yolov9/runs/train-seg/gelan-c-seg/weights/best.pt \
  --source /content/drive/MyDrive/staj_hafta3/data/YOLODataset/YOLODataset/images/test \
  --save-txt

**Comment by Y-T-G** [comment]
That is not ultralytics code.
