### ISSUE TITLE
Quantization of PyTorch model for Torch Mobile

### ISSUE THREAD

**Issue by NazaRik555** [ultralytics/ultralytics#15388]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hi everyone!
I'm trying to quantize default yolov8n with `torch.quantization.quantize_dynamic`

But I have an error 
"RuntimeError: Dataset "path/to/coco8.yaml" error "path/to/coco8.yaml" does not exists

### Environment

Ultralytics YOLOv8.2.76 🚀 Python-3.11.9 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3080 Ti, 12288MiB)
Setup complete ✅ (20 CPUs, 31.9 GB RAM, 71.6/785.0 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.11.9
Install             pip
RAM                 31.86 GB
CPU                 12th Gen Intel Core(TM) i7-12700KF
CUDA                11.7

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.0>=3.3.0
opencv-python       ✅ 4.7.0.72>=4.6.0
pillow              ✅ 9.3.0>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.28.1>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.0.1+cu117>=1.8.0
torchvision         ✅ 0.15.2+cu117>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.1>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

from ultralytics import YOLO
import torch 

model = YOLO("path/to/pretrained/model.pt")
quantized_detector = torch.quantization.quantize_dynamic(model, {torch.nn.Linear, torch.nn.Conv2d}, dtype = torch.qint8)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@NazaRik555 thank you for your detailed report. The error you're encountering suggests that the dataset path specified in your YAML file does not exist. Please ensure that the path to your dataset is correctly specified in the `coco8.yaml` file. Additionally, verify that the dataset is properly structured and accessible.

If the issue persists, please try updating to the latest version of the Ultralytics YOLO package to ensure compatibility. If you have any further questions or need additional assistance, feel free to ask.

**Comment by NazaRik555** [comment]
> @NazaRik555 thank you for your detailed report. The error you're encountering suggests that the dataset path specified in your YAML file does not exist. Please ensure that the path to your dataset is correctly specified in the `coco8.yaml` file. Additionally, verify that the dataset is properly structured and accessible.
> 
> If the issue persists, please try updating to the latest version of the Ultralytics YOLO package to ensure compatibility. If you have any further questions or need additional assistance, feel free to ask.

I think that's because I've learned it at another computer and the path to the dataset is mentioned in .pt file during training. But I don't understand why I need dataset when I'm trying to apply post-training quantization

**Comment by pderrenger** [comment]
@NazaRik555 the dataset path is likely embedded in the model's metadata, which is why you're encountering this issue. For post-training quantization, the dataset isn't needed. Ensure you're using the latest version of the Ultralytics YOLO package and try loading the model without specifying the dataset path. If the problem persists, consider re-saving the model on your current machine to update the paths. If you need further assistance, feel free to ask.

**Comment by NazaRik555** [comment]
> @NazaRik555 the dataset path is likely embedded in the model's metadata, which is why you're encountering this issue. For post-training quantization, the dataset isn't needed. Ensure you're using the latest version of the Ultralytics YOLO package and try loading the model without specifying the dataset path. If the problem persists, consider re-saving the model on your current machine to update the paths. If you need further assistance, feel free to ask.

How can I load model without specifying dataset path?

**Comment by pderrenger** [comment]
@NazaRik555 you can load the model without specifying the dataset path by simply using the model's `.pt` file. Ensure you're using the latest version of the Ultralytics YOLO package. If you still encounter issues, try re-saving the model on your current machine to update any embedded paths. If you need further assistance, feel free to ask.
