### ISSUE TITLE
yolov8-obb model evaluation ，why is input size is asymmetrical？

### ISSUE THREAD

**Issue by DWendou** [ultralytics/ultralytics#15385]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In model inferring, my input size is 416*416, and my original image size is 1280*720, but when I evaluated my model, 
https://github.com/ultralytics/ultralytics/blob/63e26e1fc8a2f96199c9ae6ecb26c13ba880a072/ultralytics/engine/validator.py#L178                
the input batch['img'].shape=16, 3, 256, 448, why are the following two dimensions not 416*416? Looking forward to your reply, thank you！

**Comment by DWendou** [comment]
in addition, batch['ratio_pad'][0] = [[0.325, 0.325], [16, 11]], After scaling the original drawing at a ratio of 0.325, the input size becomes 416*234, and then add a width of 16 to the left and right sides of the input, and add a width of 11 to the upper and lower sides of the input, and finally the input size becomes 448*256? I don't know if I can understand that?

**Comment by DWendou** [comment]
in addition, batch['ratio_pad'][0] = [[0.325, 0.325], [16, 11]], After scaling the original drawing at a ratio of 0.325, the input size becomes 416*234, and then add a width of 16 to the left and right sides of the input, and add a width of 11 to the upper and lower sides of the input, and finally the input size becomes 448*256? I don't know if I can understand that?

**Comment by DWendou** [comment]
in addition, batch['ratio_pad'][0] = [[0.325, 0.325], [16, 11]], After scaling the original drawing at a ratio of 0.325, the input size becomes 416x234, and then add a width of 16 to the left and right sides of the input, and add a width of 11 to the upper and lower sides of the input, and finally the input size becomes 448x256? I don't know if I can understand that?

**Comment by Y-T-G** [comment]
It's based on how the padding is done for PyTorch model:

https://github.com/ultralytics/ultralytics/blob/63e26e1fc8a2f96199c9ae6ecb26c13ba880a072/ultralytics/data/augment.py#L1476

PyTorch uses minimum rectangle.

**Comment by DWendou** [comment]
> LetterBox

Thank you for your reply. I understand the LetterBox function. I just don't quite understand why the image size of the input model for inference is not symmetrical during model evaluation. In my case, it should be 416x416 in theory. I retrained my model, but there was an asymmetry in the evaluation, that is, the size of batch['img'].

**Comment by DWendou** [comment]
> It's based on how the padding is done for PyTorch model:
> 
> https://github.com/ultralytics/ultralytics/blob/63e26e1fc8a2f96199c9ae6ecb26c13ba880a072/ultralytics/data/augment.py#L1476
> 
> PyTorch uses minimum rectangle.

Thank you for your reply. I am familiar with the LetterBox function, but I just don't quite understand why the size of the input image for inference is not symmetrical during model evaluation. In my example, theoretically it should be 416x416. I checked the 'rect' parameter in the training parameter list, set it to True, and retrained my model. However, during evaluation, there was still an asymmetric result, which is the size asymmetry of batch ['img '].

**Comment by Y-T-G** [comment]
It would depend on whether all the images in `val` batch have same original size or not. If they have save size, then they will use minimum rectangle like you can see in the `Letterbox` function.

**Comment by DWendou** [comment]
> It would depend on whether all the images in `val` batch have same original size or not. If they have save size, then they will use minimum rectangle like you can see in the `Letterbox` function.

Thank you for your reply. I understand now

**Comment by pderrenger** [comment]
You're welcome! If you encounter any further issues or have additional questions, feel free to ask.
