### ISSUE TITLE
Mismatch between bounding boxes and images when using albumentations

### ISSUE THREAD

**Issue by azizche** [ultralytics/ultralytics#15394]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I was using albumentation random crop augmentation on my dataset, when looking at some of the images after augmentation I realized that there are images having bboxes when they should not have. I realized the problem was that the random crop sometimes crops the images on parts where there are no bboxes and the result images labels (bboxes) don't get updated. You can see that this type of behavior is expected when looking at this code found in data/augment.py:
```Python
if len(new["class_labels"]) > 0:  # skip update if no bbox in new im
                    labels["img"] = new["image"]
                    labels["cls"] = np.array(new["class_labels"])
                    bboxes = np.array(new["bboxes"], dtype=np.float32)
                labels["instances"].update(bboxes=bboxes)
```
what happens is the new image indeed does not have bboxes due to random cropping but the original image does. So it is essential to update the bboxes at this case.

### Environment

The problem is not related to enviroment

### Minimal Reproducible Example

I can't show a reproducible code because the bug depends on the image and at a special case of random cropping

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@azizche thank you for bringing this to our attention. It appears that the issue arises from the random crop operation not updating the bounding boxes correctly when no objects are present in the cropped area. This behavior can indeed lead to mismatched bounding boxes and images.

To address this, please ensure you are using the latest version of the Ultralytics package, as updates may contain fixes for such issues. If the problem persists, we would appreciate it if you could submit a PR with your proposed solution. Your contribution would be valuable to the community.

If you need further assistance or have additional questions, feel free to ask here. Thank you for your willingness to contribute!

**Comment by azizche** [comment]
I just finished removing the if statement so that bboxes get updated even if there are no bboxes in the new image and also I changed labels.['instances'].update function so that it accepts empty bboxes. But, I run into another issue, when using random cropping with a probability >0 and <1 there is a mismatch between sizes of the images who got copped and the images that didin't. I thought about addind a fixed albumentations resizing function so all the images get resized to only one size. Should I add that in the PR?

**Comment by glenn-jocher** [comment]
@azizche thank you for your initiative in addressing the bounding box update issue. Adding a fixed albumentations resizing function to ensure all images are resized to a consistent size sounds like a practical solution. Please proceed with including this in your PR.

**Comment by azizche** [comment]
@glenn-jocher #15619 I submitted this PR Request and I addressed everything mentioned in this issue. 
One issue is that in the PR, I agreed and signed the CLA but the bot said I did not.

**Comment by glenn-jocher** [comment]
Thank you for your PR submission and for addressing the issue. Please try re-signing the CLA to ensure it's properly recorded. If the problem persists, let us know so we can assist further.
