### ISSUE TITLE
Collecting the false positive and negative images

### ISSUE THREAD

**Issue by Overste** [ultralytics/ultralytics#15393]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I'm working on improving a binary classification model that determines whether an image is correctly taken of water. My current model has an accuracy of around 86%, but I aim to achieve at least 90%. I have a dataset of 13,000 images of water. WHich both class have around 6k each of images.

During validation, I observe a significant number of false positives and false negatives, with the confusion matrix looking like this:
[[405, 51] [134, 784]] 

I want to identify the specific images that are being misclassified (i.e., the false positives and false negatives). I tried following the steps in the GitHub issue Find all false positive and false negative images of test dataset (https://github.com/ultralytics/ultralytics/issues/5367), which involve writing to a file within the `process_batch `or `update_metrics `functions.

However, I’m facing issues where nothing is written to a file when I attempt to do this within those functions. The file is only created and written to when I place the write function outside of these functions, leading me to suspect that these functions are not being called as expected when I run validation.

How can I successfully log the false positives and false negatives to a file? Alternatively, would it be better to run predictions and set aside images that fall below a certain confidence threshold? Other suggestions would also be appreciated.

**Comment by Y-T-G** [comment]
You can add your saving code after this:
https://github.com/ultralytics/ultralytics/blob/63e26e1fc8a2f96199c9ae6ecb26c13ba880a072/ultralytics/utils/metrics.py#L315

```python
if p != t:
    if p == 0 and t == 1: # False Negative
    elif p == 1 and t == 0: # False positive
```
