### ISSUE TITLE
Strange predictions for some classes after merging datasets.

### ISSUE THREAD

**Issue by mazik1496** [ultralytics/ultralytics#1542]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/80936392/226619122-1f3bc218-b66a-4618-88f1-fa3660ff9306.png)
![image](https://user-images.githubusercontent.com/80936392/226619238-df6aae4c-8664-4968-908c-fabdf8d29c69.png)

I asked a question about merging datasets last time, but the merging of datasets moved the images and labels to the corresponding folder and modified the contents of the txt corresponding to the label to match the class, so I succeeded in merging the classes.

![image](https://user-images.githubusercontent.com/80936392/226619337-5f48f09e-a0c9-4401-ac5e-0e28917cc889.png)
However, we found a phenomenon that made object detection strange for some data classes. I trained with epoch set to 100, but I don't know where the problem is. Can you tell what could be the cause for this? This is my first time using Yolo, so there are many things I don't know.

**Comment by mazik1496** [comment]
@glenn-jocher 
![image](https://user-images.githubusercontent.com/80936392/227070791-2f5d7a8c-81db-4dca-bf20-19b103291400.png)


thanks for the nice answer But I have a question here. When the data was merged from the link above, the existing data was 0-79, so the data to be added began with number 80. However, on the contrary, I did the custom 0-2 and the existing data from 3-82. May I ask if doing it this way is wrong? I thought that simply labeling it didn't matter.

**Comment by mazik1496** [comment]
@glenn-jocher 

![image](https://user-images.githubusercontent.com/80936392/227831389-ea8c582d-e9de-4618-8d9e-2c3f072190ac.png)
So, here's one thing I'm curious about. I set the epoch to 300 for the integrated data and got the following result. So, when I went into the val13 folder and compared batch and label, I confirmed that it worked pretty well.

![image](https://user-images.githubusercontent.com/80936392/227831737-2833d15f-0c38-4a82-9b9e-1e6ce83a9c9d.png)
However, if you check bus.jpg or dog.jpeg, which are used as basic examples of yolov8 here, unlike the previous examples, some objects are not recognized or even if they are recognized, the bounding box size is displayed strangely. Can you tell me if the cause of this is because I used the example picture from the existing data only in the integrated data or if there is another cause?

**Comment by glenn-jocher** [comment]
@mazik1496 COCO128 should not be used other than for sanity checks.
