### ISSUE TITLE
Installing Ultralytics with system installed matplotlib - cannot import name 'rcParams' ifrom matplotlib,axes(in python_path.)

### ISSUE THREAD

**Issue by programmeddeath1** [ultralytics/ultralytics#15439]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to create a pyinstaller executable for a pyqt application which uses YOLO model to send detections, and ros1 for the robot simulation. ROS 1 uses the system installed matplotlib installed in the /usr/lib/python3/dist-packages path.

When I install ultralytics, it installs maptlotlib to the user python directory at .local/lib/python3.8/site-packages.

When i  build the pyinstaller executable, it finds matplotlib in two paths and thus does not install the matplotlib libraries properly in the executable. The app then fails during run with " cannot import name 'rcParams' ifrom matplotlib,axes(in python_path.) " when it runs 
```
from ultralytics import YOLO
```

Is it possible to install ultalytics by making it use the system installed matplotlib? In this case then the user installation of matplotlib can be removed and the pyinstaller can add the system dependencies of maplotlib.

**Comment by pderrenger** [comment]
@programmeddeath1 it sounds like you're encountering a conflict between the system-installed and user-installed versions of matplotlib. To resolve this, you can try creating a virtual environment and installing all dependencies within it. This way, you can control the versions and paths of the installed packages, avoiding conflicts with system-wide installations. Ensure you have the latest versions of Ultralytics and matplotlib to avoid any compatibility issues. If the problem persists, please let us know if there are any specific error messages or logs that could help us diagnose further.
