### ISSUE TITLE
Regarding the Problem of Rectangle Rotation

### ISSUE THREAD

**Issue by lhj5426** [ultralytics/ultralytics#15434]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/user-attachments/assets/362262ae-a158-47ce-81c8-acaa5ae7f4b2)

![image](https://github.com/user-attachments/assets/4b4fb0ee-602f-40b7-9cdd-fcccd24fb64c)

Hello, I’m using YOLOv8 to train a model for text localization and recognition in comics. However, I’ve encountered an issue. 

As you can see in the image, I’m using a rotatable, tilted rectangle to completely enclose the text area in the comics. But during training and prediction, the model is using regular, non-tilted rectangles to select the text areas.

Could you please tell me why this is happening?

I used the annotation tool [X-AnyLabeling](https://github.com/CVHub520/X-AnyLabeling) for annotating the rotated rectangles. After completing the annotations, I exported them using the "Export YOLO-Obb Annotations" option.
![image](https://github.com/user-attachments/assets/834ce3a3-f12e-40ed-bcc8-434b301a8d1c)

As shown in the image, these are the exported annotations for the tilted rectangles, which I then used for training. However, during prediction, the rectangles appear in a regular, non-tilted orientation rather than the tilted one.
![image](https://github.com/user-attachments/assets/baf3af34-39a8-4455-960e-74c98767e105)

Why is this happening? Did I make a mistake somewhere? Is it an annotation error, or did I use the wrong annotation tool? Could you please help me?

**Comment by Kayzwer** [comment]
maybe you need to access the result like this:
```
obb_data = model(img)[0].obb
obb_data.xyxyxyxy # coordinates info
obb_data.cls # class
obb_data.conf # confidence level
```

**Comment by pderrenger** [comment]
@Kayzwer thank you for your detailed explanation and the images provided. It appears that the issue might be related to how the model is interpreting the annotations. Please ensure you are using the latest version of the Ultralytics YOLO package, as updates often include important fixes and improvements.

If the problem persists, verify that your model configuration is set up to handle Oriented Bounding Boxes (OBB). The annotations should be in the correct YOLO OBB format, which specifies bounding boxes by their four corner points. If your annotations are correct and the issue continues, it might be worth checking the training script to ensure it properly processes OBB data.

Feel free to share any additional details if the issue remains unresolved.

**Comment by lhj5426** [comment]
> @Kayzwer* thank you for your detailed explanation and the images provided. It appears that the issue might be related to how the model is interpreting the annotations. Please ensure you are using the latest version of the Ultralytics YOLO package, as updates often include important fixes and improvements.
> 
> If the problem persists, verify that your model configuration is set up to handle Oriented Bounding Boxes (OBB). The annotations should be in the correct YOLO OBB format, which specifies bounding boxes by their four corner points. If your annotations are correct and the issue continues, it might be worth checking the training script to ensure it properly processes OBB data.
> 
> Feel free to share any additional details if the issue remains unresolved.
Thanks for your help. I found the root cause of the issue. I was using `yolov8s.pt` when I should have been using `yolov8s-obb.pt`. After retraining with the correct model, I was able to recognize rotated rectangles. Thanks again for your assistance!

**Comment by lhj5426** [comment]
> > > @Kayzwer* * thank you for your detailed explanation and the images provided. It appears that the issue might be related to how the model is interpreting the annotations. Please ensure you are using the latest version of the Ultralytics YOLO package, as updates often include important fixes and improvements.
> > > If the problem persists, verify that your model configuration is set up to handle Oriented Bounding Boxes (OBB). The annotations should be in the correct YOLO OBB format, which specifies bounding boxes by their four corner points. If your annotations are correct and the issue continues, it might be worth checking the training script to ensure it properly processes OBB data.
> > > Feel free to share any additional details if the issue remains unresolved.
> > > Thanks for your help. I found the root cause of the issue. I was using `yolov8s.pt` when I should have been using `yolov8s-obb.pt`. After retraining with the correct model, I was able to recognize rotated rectangles. Thanks again for your assistance!
> 
> 你要用YOLO来帮助翻译本本😏？

是啊已经训练了2还行的 的模型了 不过 还在训练
https://github.com/xulihang/ImageTrans-docs/issues/711

**Comment by yxl23** [comment]
你好，你咋解决了这个倾斜框不倾斜的问题的，我现在也遇到了这个问题我使用了yolov8s-obb.pt进行的训练

**Comment by lhj5426** [comment]
> 你好，你咋解决了这个倾斜框不倾斜的问题的，我现在也遇到了这个问题我使用了yolov8s-obb.pt进行的训练

我的问题就是因为我用错模型了  我现在是有obb是会正常倾斜的。。。

**Comment by glenn-jocher** [comment]
@lhj5426 确保你使用的是正确的模型配置，并检查你的数据格式是否符合YOLO OBB要求。如果问题仍然存在，请查看训练脚本和配置文件以确保它们正确处理OBB数据。
