### ISSUE TITLE
close to zero recall and precision

### ISSUE THREAD

**Issue by abdullahbzr** [ultralytics/ultralytics#1543]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I've trained a custom dataset using YOLOv5 multiple times and achieved good results. However, when I tried the same dataset on YOLOv8, I got close to 0 recall and precision for some classes. Interestingly, training the same data on YOLOv5 with the same parameters yielded acceptable results. What could be causing this discrepancy between the two models?
**YOLOv8**
![all-class_pr](https://user-images.githubusercontent.com/66210642/226627759-c90ee4dd-ee71-4641-9ebf-76638b30b940.png)
![all_class_curves](https://user-images.githubusercontent.com/66210642/227171504-06f8f0b4-0b39-423b-8274-53cd8c96f3fd.png)

**YOLOv5** (The below curve was generated using the largest model whereas the above curve was generated using the light model, but I trained my model using the largest model as well in YOLOv8, and despite that, I still obtained terrible results.
![F1_curve](https://user-images.githubusercontent.com/66210642/227175884-7881e611-59bf-4cfd-aadb-396111a6ea8a.png)
![results](https://user-images.githubusercontent.com/66210642/227172032-96356253-c353-4fba-8499-264d9f779fd8.png)

**Dataset**
![Labels_0_24100c836099724bf8aa-2](https://user-images.githubusercontent.com/66210642/227172523-14ac2a8c-edcf-4121-9784-d465140c3d7e.jpg)

**Comment by ExtReMLapin** [comment]
Sound like an unbalanced dataset, could also annotation quality issue, mind sharing a dataset sample with us ?

**Comment by abdullahbzr** [comment]
> Sound like an unbalanced dataset, could also annotation quality issue, mind sharing a dataset sample with us ?

If it was the case, would not it be a problem for v5 as well?

**Comment by abdullahbzr** [comment]
@glenn-jocher What info am I supposed to attach to issue in this case. Could you specify?

**Comment by abdullahbzr** [comment]
@glenn-jocher What info am I supposed to attach to issue in this case. Could you specify?

**Comment by pderrenger** [comment]
You are absolutely right, @bezir! The potential issues of an unbalanced dataset or annotation quality should indeed affect both YOLOv5 and YOLOv8 similarly. If the dataset and annotations are the same for both models, we would expect comparable performance.

In this case, it may be worth investigating other factors such as differences in default hyperparameters or model architectures between YOLOv5 and YOLOv8 that could lead to the observed performance variation.

If you would still like to share a dataset sample for further investigation, that would be much appreciated. Thank you for your understanding and cooperation!

**Comment by glenn-jocher** [comment]
You're correct, @pderrenger. If the dataset and annotations are consistent, the issue likely isn't with data quality or balance, as this would impact both YOLOv5 and YOLOv8. The discrepancy might stem from differences in model architecture or hyperparameters. It's worth reviewing the training configuration and comparing the setups between the two versions. If you're open to sharing a sample of your dataset, we could take a closer look. Thanks for your collaboration! 🤝
