### ISSUE TITLE
The bounding box remains

### ISSUE THREAD

**Issue by jy-98** [ultralytics/ultralytics#15436]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/user-attachments/assets/ecfd3d42-5260-42aa-9495-9256294437e9)
![image](https://github.com/user-attachments/assets/fada8daa-1d1e-493c-ab4a-6070fccb70b4)
![image](https://github.com/user-attachments/assets/be2906cf-67de-41f0-8d87-1a967489fe1b)

**Comment by Y-T-G** [comment]
You should save `im_bgr`

**Comment by jy-98** [comment]
thankes. It was my carelessness

**Comment by jy-98** [comment]
> 你应该保存`im_bgr`

![image](https://github.com/user-attachments/assets/8d8dfcf1-a614-411f-86e7-680714626037)
Is it possible to tell if there is an intersection between the mask of the bus and the mask of the person?

**Comment by jy-98** [comment]
![1723539992697](https://github.com/user-attachments/assets/fb355941-cbb8-499a-b562-2af8ff95c423)
Isn't there a model for instance segmentation?

**Comment by pderrenger** [comment]
Yes, Ultralytics YOLOv8 supports instance segmentation. You can use the YOLOv8 segmentation models, such as `yolov8n-seg.pt`, for this purpose. If you need to check for intersections between masks, you can use the mask coordinates provided in the prediction results. For more detailed guidance, please refer to the [Ultralytics documentation on isolating segmentation objects](https://docs.ultralytics.com/guides/isolating-segmentation-objects/).

**Comment by jy-98** [comment]
> 是的，Ultralytics YOLOv8 支持实例分割。为此，您可以使用 YOLOv8 分割模型（例如 ）。如果需要检查掩码之间的交叉点，可以使用预测结果中提供的掩码坐标。有关更详细的指导，请参阅[有关隔离分割对象的 Ultralytics 文档](https://docs.ultralytics.com/guides/isolating-segmentation-objects/)。`yolov8n-seg.pt`
![image](https://github.com/user-attachments/assets/36ccbb2a-2766-44f4-bd61-1a4fb7ca6270)
I want to do a vehicle crimping thing, but this should be image segmentation, and I want a complete image of the car, so I can solve the vehicle crimping problem by whether there is a duplicate area between the masks.

**Comment by pderrenger** [comment]
Yes, you can use YOLOv8 segmentation models like `yolov8n-seg.pt` for instance segmentation. To check for overlapping areas between masks, you can analyze the mask coordinates provided in the prediction results. This will help you determine if there are duplicate areas between the masks, which can be useful for your vehicle crimping task. For more details, refer to the [Ultralytics documentation on isolating segmentation objects](https://docs.ultralytics.com/guides/isolating-segmentation-objects/).
