### ISSUE TITLE
Bounding boxes/image detection are inaccurate when using yolov8x-obb

### ISSUE THREAD

**Issue by steven-nguyen22** [ultralytics/ultralytics#15432]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When using yolov8x-obb the bounding boxes and image detection are inaccurate. How do I fix this issue?

This is my code 
```
from ultralytics import YOLO

model = YOLO('yolov8x-obb')

results = model("boat.jpg", save=True, show=True)
```

This is my result
![boat](https://github.com/user-attachments/assets/4b38afd9-93d0-4cb4-bf7c-b1237bc01473)

**Comment by quangdungluong** [comment]
Hi, you can check your downloaded model again. I used the pretrained model, and it works well.
![image](https://github.com/user-attachments/assets/1d6e31b1-7c7f-4336-a8a5-b31ef7ca217b)

**Comment by steven-nguyen22** [comment]
@quangdungluong wait that's so weird because I have the yolo8x-obb.pt file in my directory. How should I fix this issue? Should I try uninstalling Ultralytics and reinstalling it? I feel like you have the correct result I should be expecting when I run it using the pretrained model.

**Comment by quangdungluong** [comment]
You can try deleting the yolov8x-obb.pt file and running the code again. It will automatically download the model.

**Comment by Y-T-G** [comment]
https://github.com/ultralytics/ultralytics/issues/15049
