### ISSUE TITLE
Different predictions when use batch of images with different sizes

### ISSUE THREAD

**Issue by bobokvsky** [ultralytics/ultralytics#15430]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

Hello!

We have trained the `yolov8l-seg.pt` model at 640x640 resolution and encountered an unexpected issue.

When we load the model and make a prediction on a single image size of 640x480, the results are as follows:
```python
image_path = "image.jpg"
image = np.array(Image.open(image_path))
res = model.predict([image], conf=0.01)
res[-1].boxes.xyxy
```

It returns a tensor of 10 bounding boxes:

```python
tensor([[ 46.9212,  55.8923, 309.6488, 339.7917],
        [158.1116, 237.3364, 271.6354, 313.3171],
        [146.0500, 199.1800, 263.5758, 269.2297],
        [256.5987, 160.1060, 292.5726, 226.1018],
        [ 82.8419, 194.4707, 152.0749, 239.3202],
        [ 82.5174,  55.4958, 181.1967,  86.0534],
        [ 46.7865,  83.2617, 143.2966, 163.7049],
        [ 98.6274, 222.9462, 170.5394, 279.4631],
        [ 83.3294, 194.6769, 151.9173, 239.2567],
        [105.7473,  59.2709, 284.3904, 238.4791]])
```

However, when we use the same image as part of a batch of images with different sizes, the results are completely different:

```python
images_paths = ["cat.jpg", "dog.jpg", "image.jpg"]
images = [np.array(Image.open(image_path)) for image_path in images_paths]
res = model.predict(images, conf=0.01)
res[-1].boxes.xyxy
```
It returns a tensor of 14 bounding boxes:

```python
tensor([[ 47.0130,  55.7368, 309.0879, 339.2734],
        [157.8179, 237.2233, 272.8201, 313.5610],
        [145.5466, 199.0240, 264.0729, 269.3022],
        [256.6822, 159.8955, 292.5418, 226.1201],
        [ 82.3141,  55.4002, 182.1868,  86.1910],
        [ 46.5939,  83.2031, 143.3913, 163.8268],
        [ 83.0141, 194.4045, 152.0511, 239.2537],
        [ 83.2650, 194.3647, 151.8856, 239.3702],
        [ 98.8002, 222.9816, 170.6800, 279.3308],
        [265.0975, 195.6075, 308.2141, 276.2281],
        [105.8460,  91.2694, 254.0211, 215.2254],
        [150.2464,  57.6225, 282.3745, 141.7567],
        [105.3105,  60.0917, 284.4826, 238.3464],
        [105.3196,  91.1018, 240.9588, 182.9443]])
```
After investigating, we found that when processing a batch of images with different shapes, the `auto` parameter for `LetterBox` [is disabled](https://github.com/ultralytics/ultralytics/blob/03e0b1033cdd097651188321a16a33b315feb908/ultralytics/engine/predictor.py#L154), resulting in a image resized to 640x640 being fed to the model. In the single image case, the image size is same as it was, 640x480:
```python
model.predictor.preprocess([image])  # torch.Size([1, 3, 480, 640])
model.predictor.preprocess(images)  # torch.Size([3, 3, 640, 640])
```
This discrepancy leads to inconsistent prediction results. We kindly request that this behavior be adjusted so that the predictions for the same image are consistent, regardless of whether it is processed alone or as part of a batch. Alternatively, please consider adding an option in `predict` to control this behavior.

Thank you!

### Environment

Ultralytics YOLOv8.2.76 🚀 Python-3.11.4 torch-2.4.0+cu121 CUDA:0 (NVIDIA GeForce RTX 4060 Ti, 16076MiB)
Setup complete ✅ (12 CPUs, 125.6 GB RAM, 202.4/491.6 GB disk)

OS                  Linux-5.15.0-101-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.11.4
Install             pip
RAM                 125.64 GB
CPU                 12th Gen Intel Core(TM) i5-12400F
CUDA                12.1

numpy               ✅ 1.24.3<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.4.0>=1.8.0
torchvision         ✅ 0.19.0>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.1.4>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

Look above

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
Thank you for the detailed report. The discrepancy you're observing is due to the different preprocessing steps applied when handling single images versus batches of images. Specifically, the `auto` parameter for `LetterBox` is disabled for batches, leading to all images being resized to 640x640, which affects the predictions.

To address this, you can manually resize your images to a consistent size before passing them to the model. Alternatively, you can modify the preprocessing behavior in the source code to maintain the original aspect ratio for batch processing.

If you believe this should be a configurable option in the `predict` method, please consider submitting a feature request on our GitHub issues page. This will help us prioritize and address it in future updates.

For now, ensure you are using the latest version of the Ultralytics package to benefit from any recent fixes or improvements. If the issue persists, feel free to reach out again.
