### ISSUE TITLE
About pretrained YOLO models

### ISSUE THREAD

**Issue by TatianaGayda** [ultralytics/ultralytics#15451]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Could you tell me, please, with what hyperparameter values a pretrained YOLOv8 model was pretrained on COCO dataset?

**Comment by Y-T-G** [comment]
You can see it:

```python
model = YOLO("yolov8n.pt")
print(model.ckpt["train_args"])
```

**Comment by TatianaGayda** [comment]
Thank you very much for your answer!

**Comment by pderrenger** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to ask. The YOLO community and the Ultralytics team are always here to help.
