### ISSUE TITLE
Custom Checkpoints not working with SAM

### ISSUE THREAD

**Issue by volks73** [ultralytics/ultralytics#15466]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict, Integrations

### Bug

Thank you for adding SAM2 support to the `ultralytics` package, #14867 and #14795. We are trying to use a path to the checkpoint files instead of a key name, but we are obtaining a `FileNotFoundError` when using a checkpoint file, a.k.a. weights file, with a file name different from the checkpoint names added in the refactoring (#14867). We are using v8.2.74.

This appears to be caused by the following code in the `build_sam` function of the `models/sam/build.py` module:

```python
model_builder = None
ckpt = str(ckpt)  # to allow Path ckpt types
for k in sam_model_map.keys():
    if ckpt.endswith(k):
        model_builder = sam_model_map.get(k)

if not model_builder:
    raise FileNotFoundError(f"{ckpt} is not a supported SAM model. Available models are: \n {sam_model_map.keys()}")
```

According to the docstring for the `build_sam` function:

```python
def build_sam(ckpt="sam_b.pt"):
    """
    Builds and returns a Segment Anything Model (SAM) based on the provided checkpoint.

    Args:
        ckpt (str | Path): Path to the checkpoint file or name of a pre-defined SAM model.

    Returns:
        (SAMModel | SAM2Model): A configured and initialized SAM or SAM2 model instance.

    Raises:
        FileNotFoundError: If the provided checkpoint is not a supported SAM model.

    Examples:
        >>> sam_model = build_sam("sam_b.pt")
        >>> sam_model = build_sam("path/to/custom_checkpoint.pt")

    Notes:
        Supported pre-defined models include:
        - SAM: 'sam_h.pt', 'sam_l.pt', 'sam_b.pt', 'mobile_sam.pt'
        - SAM2: 'sam2_t.pt', 'sam2_s.pt', 'sam2_b.pt', 'sam2_l.pt'
    """
```

A custom checkout file should be possible. Note, everything works if the file name matches the supported pre-defined models in the Notes section, but if the file name is something different, it fails. For example, if on-disk I download the sam2_t.pt file and rename it to `/home/user/models/sam/2/t.pt`, the `FileNotFoundError` will be raised.

I believe the issue caused because the `ckpt` argument of the `build_sam` function cast to a string without checking if it is a `Path` first, https://github.com/ultralytics/ultralytics/blob/da2797a182f56748391c55a1b0bb133f7f0c8fb4/ultralytics/models/sam/build.py#L344 If `ckpt` is a Path, then I believe checking the `sam_model_map` should be skipped. 

However, there still needs to be way to indicate the variant/type of SAM associated with the checkpoint file. The various model builder functions have a `checkpoint` argument but are all defaulted to `None`. The functionality is partially there. I understand SAM2 support is still a work-in-progress (WIP) with #14795 still open.

### Environment

Ultralytics YOLOv8.2.76 🚀 Python-3.11.9 torch-2.4.0+cu121 CUDA:0 (NVIDIA RTX A4000, 16109MiB)
Setup complete ✅ (32 CPUs, 125.6 GB RAM, 487.4/1832.2 GB disk)

OS                  Linux-5.15.0-117-generic-x86_64-with-glibc2.31
Environment         Linux
Python              3.11.9
Install             git
RAM                 125.61 GB
CPU                 AMD Ryzen Threadripper PRO 3955WX 16-Cores
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.4.0>=1.8.0
torchvision         ✅ 0.19.0>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

```sh
wget https://github.com/ultralytics/assets/releases/download/v8.2.0/sam2_t.pt
```

```sh
mv sam2_t.pt custom_checkpoint.pt
```

```python
import torch

from ultralytics import SAM

model = SAM("/absolute/path/to/checkpoint/file/custom_checkpoint.pt")  # But not really a custom checkpoint file, just a different file name
```

#### Error Message

```sh
/absolute/path/to/checkpoint/file/custom_checkpoint.pt is not a supported SAM model. Available models are: dict_keys(['sam_h.pt', 'sam_l.pt', 'sam_b.pt', 'mobile_sam.pt', 'sam2_t.pt', 'sam2_s.pt', 'sam2_l.pt'])
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@volks73 thank you for your detailed report and for identifying the issue with custom checkpoint filenames. The current implementation indeed checks the filename against predefined model names, which causes the `FileNotFoundError` when using custom filenames.

To address this, we recommend ensuring the checkpoint filename matches one of the predefined model names. However, we understand this is not ideal for all use cases. We are actively working on improving SAM2 support and will consider your feedback for future updates.

In the meantime, please try renaming your checkpoint file to match one of the supported names (e.g., `sam2_t.pt`). If the issue persists, ensure you are using the latest version of the package, as updates may include fixes and improvements.

Feel free to submit a PR if you have a solution in mind. Your contributions are always welcome. For further details, you can refer to the [documentation](https://docs.ultralytics.com/reference/models/sam/build/). Thank you for your understanding and patience.

**Comment by glenn-jocher** [comment]
@Laughing-q seems like a filename bug here is only allowing official SAM2 models to be loaded, but if a user changes the name, or maybe even moves the official model to a different directly loading fails. Can you take a look?

**Comment by volks73** [comment]
Thank you all for the quick reply. I do believe this is a bug, and I think the variant of the SAM needs to be "decoupled" from the checkpoint file name. A new argument needs to be added and supported for the `build_sam` function and then within the `SAM()` class constructor.

Something along the lines of:

```python
def build_sam(ckpt="sam_b.pt", variant=None):
    ...
```

where `variant` is one of the valid values from dict. If `variant` is `None`, then the filename is checked for variant of SAM to build. This way, if `ckpt` is a Path to a renamed weights file or a custom weights file, the `variant` argument should be used to indicate which variant of SAM. For example,

```python
model = SAM("/path/to/checkpoint/custom.pt", variant="sam2_t.pt")
```

or

```python
model = SAM("sam2_t.pt")
```

or

```python
model = SAM()  # Starts the `sam_b.pt`
```

should work and maintain compatibility with the current behavior.

**Comment by pderrenger** [comment]
Thank you for your suggestion. We appreciate your input on improving the flexibility of the `build_sam` function. To address the issue, we recommend checking if the problem persists with the latest package version. If it does, we will consider adding a `variant` argument to decouple the model variant from the checkpoint filename in future updates. Your proposed solution aligns well with our goal of enhancing usability. For now, please ensure your checkpoint filenames match the supported model names. Thank you for your understanding.

**Comment by Laughing-q** [comment]
@volks73 Hi, thanks for the reporting!
The `SAM` series is a bit different than other our other yolo models in loading side, the former needs to create the model first then load the weight but our yolo models we could directly load the model by `torch.load()`. So current logic for `SAM` models(both SAM and SAM2) is to recognize the model by its name and create the model before actual loading it, I don't know if this is a bug to us since this seems to be the easiest way to support a third-party model series.
We also distinguish `SAM` and `SAM2` by the weight's name, and we also do the same for cli mode of other third-party models.
https://github.com/ultralytics/ultralytics/blob/d7d3449ec60081b728330749cae47e224e912813/ultralytics/models/sam/model.py#L66
https://github.com/ultralytics/ultralytics/blob/d7d3449ec60081b728330749cae47e224e912813/ultralytics/cfg/__init__.py#L788-L803
which is not the best solution but seems to be the easiest way to maintain other models.
It might confuse users more if we try to implement another argument to allow the use case, and introduce more chances for users to make mistakes and ask questions. :) 
@volks73 One question though, is there a specific use case for you that has to load a model by a modified weight name? why not directly use `model="sam2_t.pt"` but introduce another argument `variant="sam2_t.pt"`?

**Comment by volks73** [comment]
>why not directly use model="sam2_t.pt" but introduce another argument variant="sam2_t.pt"?

Absolutely! My suggestion was just my initial thought. The following seems reasonable to me as well.

```python
def build_sam(ckpt="sam_b.pt", weights=None):
    ...
    return model_builder(checkpoint=weights)
```

Then

```python
model = SAM("sam2_t.pt", weights=Path("/path/to/checkpoint/custom.pt"))  # weights should probably be of type, Path.
```

or

```python
model = SAM("sam2_t.pt")
```

The CLI can be:

```sh
$ yolo predict model="sam2_t.pt" weights="/path/to/checkpoint/custom.pt"
```

or

```sh
$ yolo predict model="sam2_t.pt"
```

But, YOLO models would be different:

```sh
$ yolo predict model="/path/to/checkpoint/custom.pt"
```

automatically defaults to YOLO model. This CLI example highlights a potential source of confusion for users, or least to me.

A user downloads the weights file linked in the documentation. The user potentially renames the weights file to fit into his or her own organization and workflow patterns, i.e., the user is like me and overly organized to a fault. Then, the user uses the CLI:

```sh
$ yolo predict model="/sam/v2/t.pt"
```

In this case, a SAM2 weights file will be used with a YOLO model based on <https://github.com/ultralytics/ultralytics/blob/d7d3449ec60081b728330749cae47e224e912813/ultralytics/cfg/__init__.py#L788-L803> with the `else` clause. A potentially confusing error is reported. Note, I have not tried this yet to get the exact error, maybe the error is not all confusing. Then, I am sorry for all of this.

I agree and admit, it is unusual to have custom checkpoint files for the SAM family of models given the pre-trained weights are supposed to be good for everything, but the above CLI example is a potentially common usage pattern.

I think this would be a problem with all non-YOLO supported models. I am not as familiar with the DETR family of models. Are custom checkpoints common for the RT-DETR family of models? A similar error would occur if I rename a RT-DETR weights file I downloaded, correct? 

It looks like for RT-DETR, the following is possible in Python examples:

```python
model = RETR("/detr/rt/b.pt")
```

because the family is already specified by using the `RETR` class. I do not use the CLI as much as Python examples.

**Comment by Laughing-q** [comment]
@volks73 Thanks for your detailed suggestions! However for third-party models I prefer not to introduce more logic for the case which might make the logic complicated i.e. users would get confused by two similar arguments(both accept a `.pt` name/filename)
```python
model = SAM("sam2_t.pt", weights=Path("/path/to/checkpoint/custom.pt"))  # weights should probably be of type, Path.
```
And for your cases that you want to customize the filename for SAM models, I could give you a customized `SAM` class that works for you:

**Comment by Laughing-q** [comment]
@volks73 Thanks for your detailed suggestions! However for third-party models I prefer not to introduce more logic for the case which might make the logic complicated i.e. users would get confused by two similar arguments(both accept a `.pt` name/filename)
```python
model = SAM("sam2_t.pt", weights=Path("/path/to/checkpoint/custom.pt"))  # weights should probably be of type, Path.
```
And for your cases that you want to customize the filename for SAM models, I could give you a customized `SAM` class that works for you:
```python
from ultralytics.models.sam.build import sam_model_map
from ultralytics import SAM

class CustomSAM(SAM):
    def __init__(self, model="sam_b.pt", model_type="sam_b.pt") -> None:
        self.model_type = model_type
        self.is_sam2 = "sam2" in model_type
        super().__init__(model)

    def _load(self, weights: str, task=None):
        model_builder = sam_model_map[self.model_type]
        self.model = model_builder(weights)

model = CustomSAM("custom.pt", model_type="sam2_b.pt")
results = model(save=True)
```
