### ISSUE TITLE
May I ask if the model can still eliminate NMS if I change the v10Detect detection head to another detection head？

### ISSUE THREAD

**Issue by Earnest522** [ultralytics/ultralytics#15467]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

May I ask if the model can still eliminate NMS if I change the v10Detect detection head to another detection head？

### Additional

May I ask if the model can still eliminate NMS if I change the v10Detect detection head to another detection head？

**Comment by Y-T-G** [comment]
No
