### ISSUE TITLE
Segment object has no attribute detect

### ISSUE THREAD

**Issue by rajaram6052150** [ultralytics/ultralytics#15480]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

C:\Users\Rajaram>yolo version
8.2.5

C:\Users\Rajaram>ultralytics version
8.2.5

Many said that different versions causing this issue . But even though the version is same the issue persists.

### Environment

C:\Users\Rajaram>yolo version
8.2.5

C:\Users\Rajaram>ultralytics version
8.2.5

### Minimal Reproducible Example

   model = YOLO(model_path)

    # Perform prediction on the input image
    results = model.predict(image_path)

    # Display the results
    results.show()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
Post the full traceback.

Did you try the latest version?
