### ISSUE TITLE
Mask out area of image ignoring objects in that area

### ISSUE THREAD

**Issue by Rich2020** [ultralytics/ultralytics#1549]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Apologies in advance if this has been answered somewhere, but the word "mask" brings up 8 pages of questions, so I could not search them all.

I know with YOLOv8 we can supply masks, but they are for segmentation tasks. 
I want to supply an image mask to an inference task in an object detection and classification context. For example, imagine I have an image and half of the image is a wall. I don't want to perform inference on that part of the image as it may produce false positives, so I'd like to mask out that part of the image so that inference is only performed on the other half. Of course, this is a crude example and the mask, in reality could be any shape.

Is this possible with YOLv8?

**Comment by Laughing-q** [comment]
@Rich2020 well we don't support that internally. But the `model.predict` api is also able to accept a cv2 image as source so basically you can mask any areas of the image first as you want and pass the masked image to `model.predict`.
```python
img = cv2.imread("img_path")
# mask the image areas
masked_img = ...
results = model.predict(source=masked_img)
```
