### ISSUE TITLE
can i Continue Train on Trained Model ?

### ISSUE THREAD

**Issue by 7assanx7** [ultralytics/ultralytics#1550]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm working on a sign language project using yolo v8
I have trained a model that can detect 3 signs 
And signs are define as classes [hello, email, stop]
If I want to keep training and add more signs  while keeping the old signs 
So what can I do to get the model can detect new signs and old signs ?
if i load the pre trained model and define the new signs with old signs like this [hello , email , stop , love , trade , friend] but i will train the new model with data of 3 new signs, is this steps is right to continue training on pre trained model ?

**Comment by Laughing-q** [comment]
@7assanx7 you should always train a model with the whole datasets including your old ones and the new ones. And yeah you can use the previous trained model as pretrained weights, but I'm sure if it would show better results than pretrained from our official weights. I guess you can try them both with the whole datasets.

**Comment by brianlmerritt** [comment]
Are there any examples of "transfer learning" with YOLOv8 that might help @7assanx7 and myself?

**Comment by Gertje79** [comment]
> @7assanx7 you should always train a model with the whole datasets including your old ones and the new ones. And yeah you can use the previous trained model as pretrained weights, but I'm sure if it would show better results than pretrained from our official weights. I guess you can try them both with the whole datasets.

is this correct? so i train a model with 100 images, then I use the best.pt to train another 100 images... You say that I should train it with all the 200 images?

**Comment by glenn-jocher** [comment]
@Gertje79 if you train a model on new images it will forget any older images. If you don't want it to forget older images you must train on all images.

**Comment by brianlmerritt** [comment]
In this video https://www.youtube.com/watch?v=QGeP-Y6KMLM Glenn Jocker says YoloV8 can remember previous learnings so long as we do not write over previous indexes they will be retained.

**Comment by pderrenger** [comment]
@brianlmerritt i appreciate the reference! While YOLOv8 can indeed remember previous learnings, it's crucial to train the model with the entire dataset, including both the old and new images, to retain previous knowledge and effectively incorporate new learnings. This approach ensures that the model comprehensively learns from the complete dataset, safeguarding the retention of past knowledge.

**Comment by dynamic612** [comment]
Hello, is it okay to continue training an already trained model? Which is better, retraining or continuous training?

**Comment by glenn-jocher** [comment]
@dynamic612 continuing training (fine-tuning) from your trained model is often better than retraining from scratch, especially when you have limited new data. You can load your trained model as pretrained weights using `model = YOLO("your_best.pt")` and continue training - this leverages the features already learned and typically requires fewer epochs to converge.
