### ISSUE TITLE
the classification fine tuning doesn't learn

### ISSUE THREAD

**Issue by WikiGenius** [ultralytics/ultralytics#1552]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I tried to fine-tune the model for the binary classification problem which is gender.
But the model doesn't learn.
It fluctuates between 0.4 and 0.6.

what I tried is:
1. updating the model pip install -U 
2. Tring different models like nano and X
3. changing lr from 0.1 to 0 0.001
The model doesn't learn
The data is not high quality but the model also can't overfit the model
So I am asking if is Yolo suitable for finetuning the classification problem or not.
Thanks so much
![bin_cls](https://user-images.githubusercontent.com/33193541/226741649-d045957d-cead-4a4d-bd14-59ce4cd53c02.png)

**Comment by WikiGenius** [comment]
I think you are right.
The dataset is almost 200 for 2 classes.

What is the recommended size?
Can I control the elements like the width and depth of the arch and change some elements or add multi-tasks for the classification like age and gender?
and what do you think about Yolo in the classification?
Because I am thinking of arch-like CoAtNet because it is the state of the art

@glenn-jocher

**Comment by WikiGenius** [comment]
![11](https://user-images.githubusercontent.com/33193541/227727982-004a44ca-d234-4efb-a4e3-59f0ee7d38fb.png)
![22](https://user-images.githubusercontent.com/33193541/227727983-f8e290b8-abe2-4926-8c30-e77812ed3804.png)
![33](https://user-images.githubusercontent.com/33193541/227727986-980b6aa3-059c-4d38-b551-883c5345dd1c.png)
![44](https://user-images.githubusercontent.com/33193541/227727989-cd84b3bc-0bf2-4f5e-81d3-e4f98ade8947.png)
![111](https://user-images.githubusercontent.com/33193541/227727991-bc49b00c-20fc-4dc5-b108-4ae806f93621.png)

It is good in the classification.
It will be a good idea in the new version added multi-classification or multi tasks

**Comment by glenn-jocher** [comment]
@WikiGenius very cool!

**Comment by wynshiter** [comment]
> ![11](https://user-images.githubusercontent.com/33193541/227727982-004a44ca-d234-4efb-a4e3-59f0ee7d38fb.png) ![22](https://user-images.githubusercontent.com/33193541/227727983-f8e290b8-abe2-4926-8c30-e77812ed3804.png) ![33](https://user-images.githubusercontent.com/33193541/227727986-980b6aa3-059c-4d38-b551-883c5345dd1c.png) ![44](https://user-images.githubusercontent.com/33193541/227727989-cd84b3bc-0bf2-4f5e-81d3-e4f98ade8947.png) ![111](https://user-images.githubusercontent.com/33193541/227727991-bc49b00c-20fc-4dc5-b108-4ae806f93621.png)
> 
> It is good in the classification. It will be a good idea in the new version added multi-classification or multi tasks

can i know how many images for each class at last for your dataset？

**Comment by WikiGenius** [comment]
Hi @wynshiter 

They are 2k for each class
