### ISSUE TITLE
Callbacks on_fit_epoch_end in final_eval creates error

### ISSUE THREAD

**Issue by silvanro** [ultralytics/ultralytics#1553]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Speed: 1.9ms preprocess, 161.5ms inference, 0.0ms loss, 5.8ms postprocess per image
Results saved to runs\detect\train23
Traceback (most recent call last):
  File "C:\Users\u230546\Desktop\yolov8\scratch2.py", line 9, in <module>
    model.train(data='coco128.yaml', epochs=3)
  File "C:\Users\u230546\Anaconda3\envs\YOLOv8\lib\site-packages\ultralytics\yolo\engine\model.py", line 317, in train
    self.trainer.train()
  File "C:\Users\u230546\Anaconda3\envs\YOLOv8\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 188, in train
    self._do_train(RANK, world_size)
  File "C:\Users\u230546\Anaconda3\envs\YOLOv8\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 376, in _do_train
    self.final_eval()
  File "C:\Users\u230546\Anaconda3\envs\YOLOv8\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 513, in final_eval
    self.run_callbacks('on_fit_epoch_end')
  File "C:\Users\u230546\Anaconda3\envs\YOLOv8\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 166, in run_callbacks
    callback(self)
  File "C:\Users\u230546\Desktop\yolov8\scratch2.py", line 6, in on_fit_epoch_end
    print(f"val/box_loss: {trainer.metrics['val/box_loss']}")
KeyError: 'val/box_loss'

### Environment

-YOLO: Ultralytics 8.0.47
-OS: Win10

### Minimal Reproducible Example

```
from ultralytics import YOLO

model = YOLO('yolov8n.pt')

def on_fit_epoch_end(trainer):
    print(f"val/box_loss: {trainer.metrics['val/box_loss']}")


model.add_callback("on_fit_epoch_end", on_fit_epoch_end)
model.train(data='coco128.yaml', epochs=2)
```

### Additional

Why is the callback on_fit_epoch_end two times in the training pipeline? The second time in final_eval are not the same metrics available.

Thanks for your help and your amazing work!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@glenn-jocher @AyushExel I think this is a good question. We do call `on_fit_epoch_end` in `final_eval`, I know this callback is reporting the final metrics there but `final_eval` is not in the epoch level which seems a little odd that we call `on_fit_epoch_end` in it. 
Probably add a new callback like `on_final_eval` to report the final metrics?

**Comment by glenn-jocher** [comment]
@silvanro yes I'm able to reproduce this now. Yes we should not be calling on_fit_epoch_end on final eval, it's really a standalone evaluation. I'll add a TODO to investigate.

**Comment by silvanro** [comment]
@glenn-jocher Perfect, thank you! :)

**Comment by glenn-jocher** [comment]
@silvanro @Laughing-q it's being called manually here. I think this is because if we don't run this callback then loggers won't record these validation results. 

The keyerror appears to be caused because we've popped the metrics before the callback is run. I think if I just reverse the order here this might fix the problem:

https://github.com/ultralytics/ultralytics/blob/8c8c43922c8a01f70ef462a3213c270648275bb3/ultralytics/yolo/engine/trainer.py#L513-L522

**Comment by glenn-jocher** [comment]
@silvanro ok looked into it. We need to keep the callback for logging final val results to ClearML, Comet, TensorBoard, etc.

Don't know why your usage example is erroring though.

**Comment by glenn-jocher** [comment]
Everything is working normally, so I've removed TODO and added a wontfix tag here.

Alternatively we could always populate val results with losses and define them as None.

**Comment by silvanro** [comment]
@glenn-jocher Thanks Glenn! So I am using this callback to log metrics each epoch. One of the metrics I log is "val/box_loss", which I get from "trainer.metrics['val/box_loss']" in the callback. It seems like those metrics are available in the normal training loop but not in the final_eval section and therefore I get the error at the end of training. 
Would it be possible to consider making an additional callback with another name as @Laughing-q proposed in his answer?

**Comment by silvanro** [comment]
It seems a bit odd to me to have the same callback in different locations where different metrics are available

**Comment by silvanro** [comment]
> Everything is working normally, so I've removed TODO and added a wontfix tag here.
> 
> Alternatively we could always populate val results with losses and define them as None.

This alternative would actually already be enough :)

**Comment by silvanro** [comment]
@Thank you very much for your support! I'll look into it.
