### ISSUE TITLE
original image path is ignored when multiple images are fed to predict function

### ISSUE THREAD

**Issue by inqlee0704** [ultralytics/ultralytics#1554]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

When multiple image paths are given to the predict function, original image paths are ignored and assigned a different name like 'image.jpg'. 
![image](https://user-images.githubusercontent.com/73238273/226773542-a93db537-b5bd-43fa-8d1e-5e1ed97803d7.png)

### Minimal Reproducible Example

```
result = model.predict([test_img_path1,test_img_path2])
print(result[0].path)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@inqlee0704 hi, currently that's how it works when `source` is a list, since we support any formats in one list, i.e:
```python
model.predict(source=[file_name, PIL, numpy,...])
```
But PIL and numpy do not include the info of filename so we are generating new name i.e `image.jpg` for all the cases including when the elements in the list are filename.

**Comment by Laughing-q** [comment]
@inqlee0704 But yeah it makes more sense if we can keep its original path if the source is filename.
@AyushExel do you think we can treat `filename` as a special case and return its original path when source is a list?

**Comment by AyushExel** [comment]
I think result.path would mean "the path of the result" anf not the path of the input.. So I'm not too sure about this

**Comment by inqlee0704** [comment]
@AyushExel But then it is not consistent with the case when only one image path is given. 
For example,
`result1 = model.predict([test_img_path1,test_img_path2]` and 
`result2 = model.predict(test_img_path1)`
`result1[0].path` and `result2[0].path` would be different.

I think at least they should be consistent.

**Comment by glenn-jocher** [comment]
@inqlee0704 yes, this is a bug, we'll work on a fix.

**Comment by glenn-jocher** [comment]
@inqlee0704 oh I see, this is affecting both the results[0].path attribute but also the name assigned to the new file when `save=True`, which was my original concern. I'll try to fix both.

**Comment by glenn-jocher** [comment]
@AyushExel I'm looking around at this, it looks like we need to apply the fixes in the dataloaders. Do you want to handle this since I think you're more familiar? Maybe we are losing the paths here:

https://github.com/ultralytics/ultralytics/blob/8c8c43922c8a01f70ef462a3213c270648275bb3/ultralytics/yolo/data/dataloaders/stream_loaders.py#L350-L364

**Comment by glenn-jocher** [comment]
@AyushExel @inqlee0704 maybe this isn't too difficult. I've tried a fix in https://github.com/ultralytics/ultralytics/pull/1584

**Comment by glenn-jocher** [comment]
@inqlee0704 its fixed in #1584! Can you try this PR and see if it fixes your problem please?

**Comment by glenn-jocher** [comment]
@inqlee0704 @AyushExel fix merged into updates branch for deployment with 8.0.56.

**Comment by inqlee0704** [comment]
Thank you for the fix :)

**Comment by pderrenger** [comment]
@inqlee0704 you're welcome! If you have any more questions or need further assistance, feel free to ask. We're here to help!

**Comment by glenn-jocher** [comment]
You're welcome, @pderrenger! Happy to help. 😊 If anything else comes up, just let us know!
