### ISSUE TITLE
How to use a freezed pretrained backone and train head from scratch? Am I doing right?

### ISSUE THREAD

**Issue by Farenweh** [ultralytics/ultralytics#15571]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thanks before,
I made a toy model which uses DINOv2 as its backbone and YOLOv8L'head as its head, just for helping myself understand how to DIY a new model and modify this framework.
Now, I'm trying to transfer pretrained DINOv2 weight to newed toy model and freezing it before training model's head from scratch.
But I'm not sure is this the right way to do so, is the Trainer really gets the pretrained DINOv2 and works right or still remains scratch? That's my question. Thanks again.

```
import torch
from ultralytics import YOLO

model = YOLO("yolov8-dinov2.yaml", task="detect")

dinov2_state_dict = torch.load("/home/me/.cache/torch/hub/checkpoints/dinov2_vitl14_reg4_pretrain.pth")
renamed_state_dict = {}

for key, value in dinov2_state_dict.items():
    new_key = "model.model.0." + key
    renamed_state_dict[new_key] = value

model.load_state_dict(renamed_state_dict, strict=False)

model.train(
    data="coco8.yaml",
    imgsz=518,
    batch=5,
    epochs=1000,
    device="0,1,2,3,4",
    freeze=1,
    name="dinov2_try",
    patience=100,
)
```

**Comment by Y-T-G** [comment]
It should work

**Comment by Farenweh** [comment]
Beholden and grateful~

**Comment by pderrenger** [comment]
@Farenweh thank you for your kind words! Your approach to freezing the pretrained DINOv2 backbone and training the YOLOv8 head looks correct. Ensure that the `freeze=1` argument is properly set to freeze the backbone layers. If you encounter any issues, please verify with the latest version of the Ultralytics package.

**Comment by Farenweh** [comment]
Actually it's NOT working well (at least in multi-gpu training), it seems subprocess would rebuild model from cfg and generate weight from scratch.
Luckily I've found a workaround

**Comment by glenn-jocher** [comment]
Thank you for the update. If you encounter further issues, please ensure you're using the latest version of the package. Feel free to share your workaround for the benefit of the community.

**Comment by Lightmannnn** [comment]
> Actually it's NOT working well (at least in multi-gpu training), it seems subprocess would rebuild model from cfg and generate weight from scratch. Luckily I've found a workaround

Hi, I'm experiencing the same issue, loading the pre-training weights doesn't seem to have an effect, can you please tell me how you solved it further.

**Comment by glenn-jocher** [comment]
I recommend checking the model loading and freezing process to ensure it's correctly implemented. If you've found a workaround, sharing it here could benefit others facing similar issues.

**Comment by Farenweh** [comment]
> > Actually it's NOT working well (at least in multi-gpu training), it seems subprocess would rebuild model from cfg and generate weight from scratch. Luckily I've found a workaround
> 
> Hi, I'm experiencing the same issue, loading the pre-training weights doesn't seem to have an effect, can you please tell me how you solved it further.

step 0: train your arch from scratch by using 'x.cfg' on 'coco8' for 1 epoch, for a checkpoint with your arch inside;
step 1: load your pretrained weights to checkpoint by using 'torch.load', keys of weight dict may need being renamed due to module name diff, then save it as a pretrained checkpoint;
step 2: start your training from pretrained(weight loaded) checkpoint instead of 'x.cfg', thus subprocesses will load weight from checkpoint instead of regen their model from scratch using 'x.cfg'.

**Comment by glenn-jocher** [comment]
Thank you for sharing your solution. It seems like a practical approach to ensure the pretrained weights are effectively utilized in multi-GPU training. If you have any further questions or need assistance, feel free to ask.

**Comment by Lightmannnn** [comment]
> > > Actually it's NOT working well (at least in multi-gpu training), it seems subprocess would rebuild model from cfg and generate weight from scratch. Luckily I've found a workaround
> > 
> > 
> > Hi, I'm experiencing the same issue, loading the pre-training weights doesn't seem to have an effect, can you please tell me how you solved it further.
> 
> step 0: train your arch from scratch by using 'x.cfg' on 'coco8' for 1 epoch, for a checkpoint with your arch inside; step 1: load your pretrained weights to checkpoint by using 'torch.load', keys of weight dict may need being renamed due to module name diff, then save it as a pretrained checkpoint; step 2: start your training from pretrained(weight loaded) checkpoint instead of 'x.cfg', thus subprocesses will load weight from checkpoint instead of regen their model from scratch using 'x.cfg'.

That was very kind of you, it works. I appreciate it.
