### ISSUE TITLE
change the map50-95 criteria to map50-75

### ISSUE THREAD

**Issue by oribarak90** [ultralytics/ultralytics#15577]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

is there a way to change the map50-95 criteria, to run through different thresholds ? lets say, map50-75 ?

**Comment by Y-T-G** [comment]
You can get the mAP value for each threshold using `model.val()`:
```
results = model.val(data="coco8.yaml")
print(results.box.all_ap)
```
It will give you all the 10 thresholds `(0.5, 0.55, 0.6, ..., 0.95)`

You can use it to average your own range.

**Comment by oribarak90** [comment]
> You can get the mAP value for each threshold using `model.val()`:
> 
> ```
> results = model.val(data="coco8.yaml")
> print(results.box.all_ap)
> ```
> 
> It will give you all the 10 thresholds `(0.5, 0.55, 0.6, ..., 0.95)`
> 
> You can use it to average your own range.

the YOLOv8 saves the results to an image, and it saves the map50-95 as a plot
is there a way to change the default values so it would print the plot as map50-75?

**Comment by Y-T-G** [comment]
No
