### ISSUE TITLE
Issue with Custom Training for Subset of Classes

### ISSUE THREAD

**Issue by PraveenKumar-Rajendran** [ultralytics/ultralytics#1558]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I used the CoCo-128 dataset, but I want to train only a few of the classes. To do this, I used the 'classes' argument to pass in a list of the classes I want to train. 

However, after training and validation, I noticed that the confusion matrix contains false negatives(FN) for classes that are not included in my list. How can I exclude these other classes completely and only train for the classes I specified in the list?

![confusion_matrix](https://user-images.githubusercontent.com/53290706/226807705-ce1f2867-a224-43a9-9196-f1dfdc0788d6.png)

For example) Please check the column of the cat class that contains a false negative (being predicted as a dog) for the class that I did not include in the list.

**Comment by Laughing-q** [comment]
@PraveenKumar-Rajendran the `classes` arg is working well while training, so you were training these classes you wanted. But yes there might be a problem with the confusion matrix which should not include other classes.

**Comment by glenn-jocher** [comment]
@PraveenKumar-Rajendran maybe we should go a step further and force the cls biases for non classes lower, but for now your result is expected and correct, as classes argument simply strips away labels in your dataset but does NOT modify model architecture, so you trained an 80 class model that's only capable of detecting a few classes that you defined with the classes arg.

**Comment by glenn-jocher** [comment]
The cls output biases should already be initialized very low, i.e. -10 maybe in logit-space, so there is no action to take here. I think you just need to train longer, i.e. try training 2x or 10x longer.

**Comment by PraveenKumar-Rajendran** [comment]
@glenn-jocher @Laughing-q  Got it. Thank you. So is there a way to change the model architecture only for the selected classes? or are there any plans to do this in the future? :)

**Comment by glenn-jocher** [comment]
@PraveenKumar-Rajendran you do that yourself by passing a dataset with just the classes you want.

`classes` arg is lightweight and simply ignore classes that are not included in the classes list, it has no effect on model architecture.

**Comment by PraveenKumar-Rajendran** [comment]
Thank you! I will preprocess the data to remove other classes.
