### ISSUE TITLE
eval cost much more time in multi gpu training than single gpu training

### ISSUE THREAD

**Issue by GuoQuanhao** [ultralytics/ultralytics#15598]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train, Val, Multi-GPU

### Bug

I use single GPU to train the model, I get less eval time
device=0
![image](https://github.com/user-attachments/assets/68a4ae4b-4476-47f3-9d57-6722b4385c81)
device=1
![image](https://github.com/user-attachments/assets/d56a466d-c1fd-40d0-9489-696e53fc123b)
device=0,1
![image](https://github.com/user-attachments/assets/8c62a156-1c2c-4dfb-a0ce-6d75c3253500)
I found torch.nonzeros cost much more eval time in multi gpu training, what should I do.
![image](https://github.com/user-attachments/assets/55c9f168-4775-4abc-a2f9-5050cb835bba)

### Environment

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

torch                     2.4.0
torchaudio                2.4.0
torchvision               0.19.0

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0

cuDNN v8.9.7
```

### Minimal Reproducible Example

None

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by GuoQuanhao** [comment]
tqdm told me evaluation would take 5 minutes when multi gpu, bu 1.5 minutes when single gpu

**Comment by Y-T-G** [comment]
If you're using `multi-GPU` you should multiply the batch size with no. of GPUs.

In your screenshots, single-GPU val involves 106 iterations, while multi-GPU involves 211 iterations.

**Comment by Y-T-G** [comment]
You should be using `batch=256` for 2 GPUs as you used `batch=128` in your single-GPU training.

**Comment by glenn-jocher** [comment]
It sounds like the issue may have resolved itself. If you encounter any further problems, please ensure you're using the latest version of the package and feel free to reach out with specific details.
