### ISSUE TITLE
How to get 44.9map with yolov8s

### ISSUE THREAD

**Issue by adamqian111** [ultralytics/ultralytics#1559]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to get 44.9map with yolov8s?

I trained yolov8s with:  yolo detect train model=ultralytics/models/v8/yolov8s.yaml data=ultralytics/datasets/coco.yaml
But only got 42.3MAP

**Comment by AyushExel** [comment]
How many epochs have you trained for ? The official models have been trained for 500 epochs

**Comment by adamqian111** [comment]
@AyushExel Thanks for your reply. I traind for 300 epochs. I will try 500 epochs.
