### ISSUE TITLE
YOLOv8 : pose(person) + object detection or classification(other object)

### ISSUE THREAD

**Issue by jjlee93** [ultralytics/ultralytics#15595]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi

In order to analyze human behavior in the video, I am using the YOLO-pose (v8) model and the YOLO object detection (v5) model. However, since I was using the two models at the same time, there was a big disadvantage in terms of inference speed, and to solve this problem, I would like to use the YOLO-pose model as a single model, including the task of detecting or classifying objects.
(1) In other words, what I want is to add a function to the pose model to classify objects that people can interact with indoors, such as whether the refrigerator door is open or closed.
→ When I tried it, I confirmed that when I mixed the pose labeling data (bbox coordinates + keypoint coordinates) and the labeling data for object detection (bbox coordinates) and ran the model training, an error message was output telling me not to mix the data. So when I set all the keypoint coordinates to 0 and trained the object detection data, I could see that while the bbox for the object (ex. door) was inferred well, the inference accuracy of the bbox coordinates and keypoint coordinates for the person was very low. I would like some advice on whether this problem is simply caused by insufficient data or whether the method I chose itself is problematic.

(2) If the above method is incorrect, I wonder if it is possible to perform classification for each object (person, door) first before inferring the keypoint of a person in terms of the structure of the model and output the result.
→ It is known that the yolo-pose model is a top-down method that classifies the class of an object and uses class information to infer keypoints, but from what I searched, it was told that it is not a top-down method because it infers both the bbox and keypoint at the same time. I need help on what work is needed to obtain the result I want.

Thank you.

**Comment by jjlee93** [comment]
Yes,
For humans, I used the specified format as is.
4 bbox coordinates + 17 keypoint coordinates joints (x, y, visibility)
I also adjusted it to the same format for other objects. However, just one different thing is I changed all x, y, and visibility values ​​to 0.

**Comment by Y-T-G** [comment]
It should work.

**Comment by jjlee93** [comment]
I used 200 images with three classes(person, opened door, closed door) and labeling those objects (person : bbox+keypoints/opened door : bbox+keypoints with all zero value/closed door : sames as opened door) to train model. and it detected door classes but it didn't work well on person.
Would you please give me some advice?
Were there too few images to detect bbox and keypoints of person?

**Comment by glenn-jocher** [comment]
It sounds like the issue might be due to the limited number of images. For accurate detection and keypoint estimation, especially for complex tasks like pose estimation, a larger and more diverse dataset is typically required. Consider increasing your dataset size and ensuring a balanced representation of all classes.

**Comment by jjlee93** [comment]
There was a minor issue. I corrected it and it worked well. 
Thank you guys.

**Comment by glenn-jocher** [comment]
Glad to hear you resolved the issue! If you have any more questions, feel free to ask.
