### ISSUE TITLE
How to use 2 detections model for 1 video?

### ISSUE THREAD

**Issue by andhikafeha** [ultralytics/ultralytics#15601]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to use my person detection then after it detects the person, we detect if the person using helmet, boots, and vest or not. How can I combine that for realtime detection?

**Comment by chuang091** [comment]
Since your goal is realtime detection, you can try just use one model that can fullfill the task your mentioned above and maybe will more accurate either.

**Comment by glenn-jocher** [comment]
@chuang091 for real-time detection, you can use two models sequentially: first, detect the person, then crop the detected area and pass it to the second model to check for helmet, boots, and vest. This approach ensures accurate detection for each specific task.
