### ISSUE TITLE
How to use yolov8 to find erased parts of an image?

### ISSUE THREAD

**Issue by jindameias** [ultralytics/ultralytics#15607]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a task now to find an erased part of a picture. 
I want to use yolov8-seg, but it doesn't seem to work. 
The image I obtained is similar to the one below with generative adversarial network processing, which wiped out the house:
![123_erase](https://github.com/user-attachments/assets/93c52004-a12d-4707-8d46-cd9548b54eca)

This is the original image below:
![123](https://github.com/user-attachments/assets/99af43fc-3e4d-4ac4-80a7-c7670e29af68)

The images obtained were of various objects being erased, such as necklaces, bottles, balloon, chairs, and so on.
So, how can I find the pixels that have been modified without original image, and get the mask.
Thanks!

**Comment by Y-T-G** [comment]
This is not a task for YOLO.

You can use OpenCV and find the difference.
