### ISSUE TITLE
The result of optimizing Ultralytics with OpenVINO was incorrect

### ISSUE THREAD

**Issue by qinqinqin648** [ultralytics/ultralytics#15605]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Val

### Bug

When the prediction result is printed, the result is wrong, and all the prediction boxes are at the top and all wrong
![预测结果（错误）](https://github.com/user-attachments/assets/38b6fd29-6da9-4a5d-ada5-9322e68dd91f)

### Environment

Ultralytics YOLOv8.2.77 🚀 Python-3.10.14 torch-2.4.0+cpu CPU (Intel Core(TM) i7-8700K 3.70GHz)
Setup complete ✅ (12 CPUs, 15.9 GB RAM, 408.1/446.5 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.10.14
Install             pip
RAM                 15.94 GB
CPU                 Intel Core(TM) i7-8700K 3.70GHz
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.4.0>=1.8.0
torchvision         ✅ 0.19.0>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

from ultralytics.utils import DEFAULT_CFG
from ultralytics.cfg import get_cfg
from ultralytics.data.converter import coco80_to_coco91_class
from ultralytics.data.utils import check_det_dataset
import yolov8ModelDownload
import openvino as ov
from Define_validation_function import test
from Define_validation_function import print_stats
import nncf  # noqa: F811
from typing import Dict
import Define_validation_function
import ipywidgets as widgets
import requests
import torch

if __name__ == '__main__':
    core = ov.Core()

    args = get_cfg(cfg=DEFAULT_CFG)
    args.data = str(yolov8ModelDownload.CFG_PATH)
    det_validator = yolov8ModelDownload.model.task_map[yolov8ModelDownload.model.task]["validator"](args=args)
    det_validator.data = check_det_dataset(args.data)
    det_validator.stride = 32
    det_data_loader = det_validator.get_dataloader(yolov8ModelDownload.OUT_DIR / "coco", 1)
    det_validator.is_coco = True
    det_validator.class_map = coco80_to_coco91_class()
    det_validator.names = yolov8ModelDownload.model.model.names
    det_validator.metrics.names = det_validator.names
    det_validator.nc = yolov8ModelDownload.model.model.model[-1].nc
    NUM_TEST_SAMPLES = 300

    fp_det_stats = test(yolov8ModelDownload.ov_model, core, det_data_loader, det_validator, num_samples=NUM_TEST_SAMPLES)

    int8_model_det_path = yolov8ModelDownload.models_dir / f"{yolov8ModelDownload.MODEL_NAME}_openvino_int8_model/{yolov8ModelDownload.MODEL_NAME}.xml"

    to_quantize = widgets.Checkbox(
        value=True,
        description="Quantization",
        disabled=False,
    )
    # Fetch skip_kernel_extension module
    r = requests.get(
        url="https://raw.githubusercontent.com/openvinotoolkit/openvino_notebooks/latest/utils/skip_kernel_extension.py",
    )
    open("skip_kernel_extension.py", "w").write(r.text)

    def transform_fn(data_item: Dict):
        """
        Quantization transform function. Extracts and preprocess input data from dataloader item for quantization.
        Parameters:
           data_item: Dict with data item produced by DataLoader during iteration
        Returns:
            input_tensor: Input data for quantization
        """
        input_tensor = det_validator.preprocess(data_item)['img'].numpy()
        return input_tensor

    quantization_dataset = nncf.Dataset(det_data_loader, transform_fn)

    ignored_scope = nncf.IgnoredScope(
        names=[
            "__module.model.22.cv3.0.0.conv/aten::_convolution/Convolution",  # in the post-processing subgraph
            "__module.model.16.conv/aten::_convolution/Convolution",
            "__module.model.22.cv2.0.0.conv/aten::_convolution/Convolution",
            "__module.model.6.cv1.conv/aten::_convolution/Convolution",
            "__module.model.22.cv3.1.1.conv/aten::_convolution/Convolution",
            "__module.model.21.cv2.conv/aten::_convolution/Convolution",
            "__module.model.21.m.0.cv1.conv/aten::_convolution/Convolution",
            "__module.model.22/aten::add/Add_6",
            "__module.model.22/aten::sub/Subtract",
            "__module.model.7.conv/aten::_convolution/Convolution",
            "__module.model.12.cv1.conv/aten::_convolution/Convolution",
            "__module.model.4.cv1.conv/aten::_convolution/Convolution",
            "__module.model.22.cv2.2.1.conv/aten::_convolution/Convolution",
            "__module.model.22.cv2.0.1.conv/aten::_convolution/Convolution",
            "__module.model.22.dfl.conv/aten::_convolution/Convolution",
            "__module.model.22.cv3.2.2/aten::_convolution/Convolution",
            "__module.model.22.cv3.0.2/aten::_convolution/Convolution",
            "__module.model.15.cv1.conv/aten::_convolution/Convolution",
            "__module.model.5.conv/aten::_convolution/Convolution",
            "__module.model.0.conv/aten::_convolution/Convolution"
        ]
    )

    # Detection model
    quantized_det_model = nncf.quantize(
        yolov8ModelDownload.ov_model,
        quantization_dataset,
        preset=nncf.QuantizationPreset.MIXED,
        ignored_scope=ignored_scope
    )
    print(f"Quantized detection model will be saved to {int8_model_det_path}")
    ov.save_model(quantized_det_model, str(int8_model_det_path))

    device = widgets.Dropdown(
        options=core.available_devices + ["AUTO"],
        value="AUTO",
        description="Device:",
        disabled=False, )

    ov_config = {}
    if device.value != "CPU":
        quantized_det_model.reshape({0: [1, 3, 640, 640]})
    if "GPU" in device.value or ("AUTO" in device.value and "GPU" in core.available_devices):
        ov_config = {"GPU_DISABLE_WINOGRAD_CONVOLUTION": "YES"}
    quantized_det_compiled_model = core.compile_model(quantized_det_model, device.value, ov_config)

    def infer(*args):
        result = quantized_det_compiled_model(args)
        return torch.from_numpy(result[0])

    yolov8ModelDownload.model.predictor.inference = infer

    res = yolov8ModelDownload.model(yolov8ModelDownload.IMAGE_PATH)
    display(yolov8ModelDownload.Image.fromarray(res[0].plot()[:, :, ::-1]))

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
https://github.com/ultralytics/ultralytics/issues/15049

**Comment by Y-T-G** [comment]
Downgrade PyTorch and export again

**Comment by qinqinqin648** [comment]
> Downgrade PyTorch and export again

Yes，thank you very much

**Comment by glenn-jocher** [comment]
You're welcome! Please let us know if the issue persists after downgrading PyTorch.
