### ISSUE TITLE
Ultra-high resolution object detection

### ISSUE THREAD

**Issue by llmgpt** [ultralytics/ultralytics#15618]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

If the cuda memory is large enough, can you directly use yolov8 for ultra-high resolution image detection?For example, 10000x8000 pixel object detection,Because I set imgsz=4160, in 24G Nvidia 3090.

**Comment by Y-T-G** [comment]
Yes

**Comment by Skillnoob** [comment]
Yes, though I'd rather recommend [SAHI](https://docs.ultralytics.com/guides/sahi-tiled-inference/) for very large images.

**Comment by llmgpt** [comment]
Thank you for your answers. I will try two ways to solve my problem

**Comment by glenn-jocher** [comment]
You're welcome! If you encounter any further issues or have additional questions, feel free to ask.

**Comment by llmgpt** [comment]
Can I use eight graphics cards (P40,24G) to train ultra-high resolution pictures (10000x8000), that is, set the imgsz to 8192? If not, I might lose my job.

**Comment by llmgpt** [comment]
Because when training,8 graphics cards must specify batch=8, not batch=1,How to solve?

**Comment by Y-T-G** [comment]
`batch=8` for 8 GPUs would be 1 batch for each GPU.

**Comment by Skillnoob** [comment]
It divides the batch size up between the gpu's. If you specify batch=1 you would give each gpu less than one image, which is not possible.

**Comment by Skillnoob** [comment]
Additionally, if the imgz doesn't fit within the VRAM i would strongly reccomend to try SAHI, which I have linked earlier and slice your training images to something more managable like a resolution of 1280 and then train with `imgsz=1280`.

**Comment by llmgpt** [comment]
Can't I stack the memory of eight graphics cards together?

**Comment by glenn-jocher** [comment]
Unfortunately, you cannot stack the memory of multiple GPUs together. Each GPU operates independently with its own memory. For ultra-high resolution images, consider using techniques like SAHI to manage memory usage effectively.

**Comment by llmgpt** [comment]
yolo detect train data=tiles2.yaml model=yolov8s.pt epochs=500 patience=250 name=tiles2 batch=1 imgsz=8192 device=0,1,2,3
Is there a way to implement this command?

**Comment by llmgpt** [comment]
I tried the SAHI+YOLOv8 solution, but the boss said no.

**Comment by Y-T-G** [comment]
No. Batch size has to be divisible by no. of GPUs

**Comment by llmgpt** [comment]
Ok, I see. Thank you for your reply

**Comment by llmgpt** [comment]
Is it possible to implement imgsz set to 8192 using a model parallel approach? I have eight p40(24G).

**Comment by glenn-jocher** [comment]
Implementing `imgsz=8192` using a model parallel approach is not feasible as GPU memory cannot be stacked. Consider reducing the image size or using techniques like SAHI for ultra-high resolution images.

**Comment by Skillnoob** [comment]
@llmgpt If a single gpu cannot handle that a batch of 1 at that imgsz, no. Again, you should be using SAHI for these kinds of images. It has no downsides and will give you much faster train rates at much better accuracy. I don't know why your boss would not want to use SAHI.

**Comment by llmgpt** [comment]
Thank you very much for your reply.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any further questions or need additional assistance, feel free to ask.
