### ISSUE TITLE
any limitation on size of object that can yolo be able to detect?

### ISSUE THREAD

**Issue by sourabCV** [ultralytics/ultralytics#15612]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a 1920x1080 image where I want to detect a screw whole that is 18x18 px in size 
yolo can detect that if I train a model on 640 image size ?

**Comment by Y-T-G** [comment]
Maybe. You can try the `yolov8n-p2.yaml` model.

**Comment by AliBYetiser** [comment]
With 640px your target bbox will be 6px by 6px. I think that's way too small but it could in an highly controlled environment. Depending on your resources I would suggest training with imgsz 1920 or use Slicing Aided Hyper Inference SAHI and train a model with crops of 1920px images where targets are then 18px by 18px and so training size is 640.

**Comment by glenn-jocher** [comment]
@AliBYetiser using a 640px image size might make your target bounding box too small (6px by 6px). For better results, consider training with `imgsz=1920` or using Slicing Aided Hyper Inference (SAHI) to train on 1920px image crops, which will maintain the target size at 18px by 18px while keeping the training size at 640px.
