### ISSUE TITLE
About parameter dropout

### ISSUE THREAD

**Issue by YycYoung** [ultralytics/ultralytics#1561]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The parameter dropout in default.ymal shows (classify train only).
Is that means only useful on classification model like yolov8-cls? Or it's also useful when tuning it on detection models?

**Comment by AyushExel** [comment]
Yes, the config `dropout` only controls classification training. The architecture for detection and segmentation models are not configurable via cmd-line configs.
