### ISSUE TITLE
YOLOV8 with SAM2

### ISSUE THREAD

**Issue by XtraspotsSimpson** [ultralytics/ultralytics#15627]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there any way to use yolov8 and Sam2 at the same time? Use yolov8 to add object functions and use SAM2 to segmentation my objects

I want to be able to use yolov8 to identify the object frame when a new object appears in the video, and then give this object frame to SAM2 for subsequent recognition and tracking.

**Comment by chuang091** [comment]
Seems possible, do you have any further information or code?

**Comment by Burhan-Q** [comment]
You can use the `auto_annotate` function with an object detection model to feed box-prompts to SAM or SAM2. See the [docs here](https://docs.ultralytics.com/usage/simple-utilities/#auto-labeling-annotations) for reference

**Comment by XtraspotsSimpson** [comment]
@Burhan-Q I think `auto_annotate`  is a great way to annotate, but I want to know if I can first get the object detection bounding box from the image through yolov8, and treat this as the BOX prompt of SAM2 MASK, and then use SAM2 tracking to help me track the object target.

**Comment by Burhan-Q** [comment]
Yes, you can access the bounding boxes from the detection model results, then pass those to a SAM model (any kind) using the `bboxes` argument. This is exactly what the `auto_annotate` function does.

https://github.com/ultralytics/ultralytics/blob/62094bd03fc6d14726a8362ccb7e2872fe6b7909/ultralytics/data/annotator.py#L39-L46

**Comment by ousaghro** [comment]
Hello
I use YOLOv11 ans SAM2 i get the segmentation result but i need please how i can get the mask of object segmented in the image 
this the code of segmentataion after detection by yolov11.
from ultralytics import YOLO
import cv2
from ultralytics import SAM

# Load the YOLO model
yolo_model = YOLO("/content/runs/detect/train/weights/best.pt")  # pretrained YOLO model

# Run batched inference on a list of images

# Load the SAM model
import matplotlib.pyplot as plt
sam_model = SAM("sam2_b.pt")
results = yolo_model("/content/e.jpg")  # return a list of Results objects
for result in results:
     class_ids = result.boxes.cls.int().tolist()  # noqa
     if len(class_ids):
         boxes = result.boxes.xyxy  # Boxes object for bbox outputs
         sam_results = sam_model(result.orig_img, bboxes=boxes, verbose=False, save=False, device=0)
thank you very much

**Comment by glenn-jocher** [comment]
To retrieve segmentation masks from SAM2 results, access the `masks` attribute in your `sam_results` object. Here's a concise implementation:

```python
# After obtaining sam_results
masks = sam_results[0].masks.data.cpu().numpy()  # Convert masks tensor to numpy array

# Visualize first mask
import matplotlib.pyplot as plt
plt.imshow(masks[0])
plt.show()
```

For detailed mask processing guidance, see the [Segmentation Masks documentation](https://docs.ultralytics.com/tasks/segment/#masks) covering mask manipulation and visualization techniques.

**Comment by ousaghro** [comment]
Tanak you very much #19572 to you response 
please an other question how i can extract tha part on image using this mask and image.

**Comment by glenn-jocher** [comment]
To extract image regions using SAM2 masks, you can apply boolean masking with numpy. Here's a concise implementation:

```python
import cv2
import numpy as np

# After obtaining masks from sam_results
mask = masks[0].astype(np.uint8)  # First mask
segmented_region = cv2.bitwise_and(result.orig_img, result.orig_img, mask=mask)

# Extract bounding coordinates from mask
y, x = np.where(mask)
cropped = segmented_region[y.min():y.max(), x.min():x.max()]
```

For detailed guidance on mask operations, see the [Segmentation Masks documentation](https://docs.ultralytics.com/tasks/segment/#masks). This approach preserves only the masked object region while maintaining original image quality.
