### ISSUE TITLE
Filtering YOLOv8 NCNN output

### ISSUE THREAD

**Issue by Rockntt** [ultralytics/ultralytics#15623]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi!

I've tried exporting my pre-trained YOLOv8 model in NCNN format and now wondering how to filter my output. Here's the thing:

```
image 1/1 C:\my\path\20240625_182103.jpg: 640x640 5 1s, 3 11s, 5 12s, 5 13s, 12 14s, 16 15s, 21 16s, 5 18s, 7 20s, 22 22s, 10 23s, 15 24s, 2 25s, 5 26s, 1 27, 17 29s, 17 3s, 6 31s, 27 32s, 4 34s, 31 35s, 37 5s, 25 8s, 2 9s, 55.5ms
Speed: 3.0ms preprocess, 55.5ms inference, 632.5ms postprocess per image at shape (1, 3, 640, 640)
```

How can I get the predicted class name from this?

**Comment by glenn-jocher** [comment]
@Rockntt to filter the output and get the predicted class names from your YOLOv8 NCNN model, you will need to map the class indices to their corresponding names using your dataset's class list. Ensure you have the latest version of the Ultralytics package, and refer to the [NCNN integration guide](https://docs.ultralytics.com/integrations/ncnn) for detailed instructions.

**Comment by Rockntt** [comment]
> @Rockntt to filter the output and get the predicted class names from your YOLOv8 NCNN model, you will need to map the class indices to their corresponding names using your dataset's class list. Ensure you have the latest version of the Ultralytics package, and refer to the [NCNN integration guide](https://docs.ultralytics.com/integrations/ncnn) for detailed instructions.

But what means 's' in prediction result? For example in "5 1s".

**Comment by Y-T-G** [comment]
Plural 's'

persons, cars, trucks, buses.

It adds 's' to the end.

**Comment by Rockntt** [comment]
> Plural 's'
> 
> persons, cars, trucks, buses.
> 
> It adds 's' to the end.

Thanks!
So all my classes are in my output cause of something wrong with my model...
There's an [[Link text](https://github.com/ultralytics/ultralytics/issues/15624)](issue) about that.

**Comment by glenn-jocher** [comment]
@Rockntt it seems like your model might be misconfigured. Please check the linked issue for potential solutions and ensure your class labels are correctly set up in your dataset. If the problem persists, verify with the latest package version.

**Comment by Rockntt** [comment]
> @Rockntt it seems like your model might be misconfigured. Please check the linked issue for potential solutions and ensure your class labels are correctly set up in your dataset. If the problem persists, verify with the latest package version.

My package seems to be latest and my .pt YOLO model works fine. All I did was exporting it into NCNN format and something went wrong. I will try to reexport it again so maybe the problem will be gone. If it will - I'll close linked issue.

**Comment by glenn-jocher** [comment]
Thank you for the update. Re-exporting the model is a good step. If the issue persists after re-exporting, please let us know, and we can further investigate.

**Comment by Rockntt** [comment]
> Thank you for the update. Re-exporting the model is a good step. If the issue persists after re-exporting, please let us know, and we can further investigate.

Re-exporting didn't help. As my question about filtering output is done, We can move to the exporting related issue (https://github.com/ultralytics/ultralytics/issues/15624), which contains my export logs and code I've used for exporting

**Comment by glenn-jocher** [comment]
Thank you for the update. Let's continue the discussion on the exporting issue in the linked GitHub issue. We'll review your export logs and code there to assist further.
