### ISSUE TITLE
model.track(name="VIDEO")

### ISSUE THREAD

**Issue by JorMartins** [ultralytics/ultralytics#15620]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Variabel NAME not work with track ??    Window show with name: video_path_contador and no "VIDEO"

results = model.track(
            video_path_contador,
            name="VIDEO",
            stream=False,
            conf=0.5,
            iou=0.5,
            persist= True,
            show=True,
            show_labels=True, 
            show_conf=True

**Comment by glenn-jocher** [comment]
@JorMartins the `name` parameter in `model.track` is not used to set the window title. To set the window title, you can use OpenCV directly. Here's an example:

```python
import cv2
from ultralytics import YOLO

model = YOLO("yolov8n.pt")
results = model.track(video_path_contador, stream=False, conf=0.5, iou=0.5, persist=True, show=False)

for result in results:
    frame = result.plot()
    cv2.imshow("VIDEO", frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cv2.destroyAllWindows()
```

This will display the window with the title "VIDEO".

**Comment by JorMartins** [comment]
> @JorMartins the `name` parameter in `model.track` is not used to set the window title. To set the window title, you can use OpenCV directly. Here's an example:
> 
> ```python
> import cv2
> from ultralytics import YOLO
> 
> model = YOLO("yolov8n.pt")
> results = model.track(video_path_contador, stream=False, conf=0.5, iou=0.5, persist=True, show=False)
> 
> for result in results:
>     frame = result.plot()
>     cv2.imshow("VIDEO", frame)
>     if cv2.waitKey(1) & 0xFF == ord('q'):
>         break
> 
> cv2.destroyAllWindows()
> ```
> 
> This will display the window with the title "VIDEO".

I´m not using cv2 in this project.

**Comment by Skillnoob** [comment]
The `name` argument is not a thing. See the [predict arguments](https://docs.ultralytics.com/modes/predict/#inference-arguments). Additionally, `show=True` uses OpenCV to display the image, so glenn's solution would work. See the show function:
https://github.com/ultralytics/ultralytics/blob/a6f4a9f2d480caa2cd199a53926e897c1a739a50/ultralytics/engine/predictor.py#L386-L394
