### ISSUE TITLE
How to analyzed runs/detects folder

### ISSUE THREAD

**Issue by ngocnh22** [ultralytics/ultralytics#15622]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, 
I have a question about the runs/detect folder after training is completed.

1- How to analyzed it to improve the architecture or parameters with my custom dataset?
2: I trained with a single object, and after I completed it, I have the train_batch{*}.jpg. As following https://docs.ultralytics.com/yolov5/tutorials/tips_for_best_training_results/#dataset observe it to verify my labels appear correct. I revived some images with "0" label and 'my label' in data.yaml file. What does it mean? Is it true that for objects labeled 0 the model cannot learn? I make sure my dataset was labeled in correctly.

**Comment by Skillnoob** [comment]
Here's a docs page about the performance metrics: https://docs.ultralytics.com/guides/yolo-performance-metrics/
