### ISSUE TITLE
Segmentation mask artefact

### ISSUE THREAD

**Issue by StitchUA** [ultralytics/ultralytics#15636]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi all, i have a question.

I train a model with segmentation task. After trainig I made a prediction of image 
```
results = model.predict(image_path, classes=[0], show_boxes=False, retina_masks=True, verbose=False)
```
and have been confiused when saw a segmentation masks.

![image](https://github.com/user-attachments/assets/2bdc4112-d18d-470f-92fa-13fcd6e70560)

After prediction every mask of every label have this artefact, one per mask.  

I used  a `yolov8m-seg` model for trainig.

Can anyone help me with this?

Sorry for my english.

**Comment by glenn-jocher** [comment]
@StitchUA thank you for your question. Please ensure you are using the latest version of the Ultralytics package. If the issue persists, try adjusting the `retina_masks` parameter or retraining the model with different augmentation settings. If you need further assistance, feel free to provide more details.

**Comment by StitchUA** [comment]
Hi @glenn-jocher , thanks for your answer.

I have updated to the last version of  Ultralytics package it is 8.2.78 and try make prediction, the artifact still persist.
I tried to change `retina_masks` parametr to it default value (False) but it doesn't make difference too.
Could you please advise which augmentation params I need to change before retraining the model.
I attached `args.yaml` I used for last model trainig.
Thank you in advance.
 
[args .txt](https://github.com/user-attachments/files/16639229/args.txt)

**Comment by StitchUA** [comment]
I forgot to mention about augmentation for creating a dataset for trainig model. I have used Albumentation librery
with this configuration:
```
transform = A.Compose([
        A.HorizontalFlip(p=0.5),
        A.VerticalFlip(p=0.5),
        A.RandomBrightnessContrast(p=0.2),
        A.Rotate(limit=45),
        A.Blur(blur_limit=3, p=0.1),
        A.GaussNoise(var_limit=(10.0, 50.0), p=0.2),
        A.HueSaturationValue(hue_shift_limit=20, sat_shift_limit=30, val_shift_limit=20, p=0.3),
        A.CLAHE(clip_limit=2.0, tile_grid_size=(8, 8), p=0.2)
    ], is_check_shapes=False)
    ```

**Comment by Y-T-G** [comment]
Provide output of `yolo checks `

**Comment by StitchUA** [comment]
```

Ultralytics YOLOv8.2.78 🚀 Python-3.12.3 torch-2.3.1+cu121 CPU (Intel Core(TM) i5-4570 3.20GHz)
Setup complete ✅ (4 CPUs, 31.3 GB RAM, 61.5/233.7 GB disk)

OS                  Linux-6.8.0-40-generic-x86_64-with-glibc2.39
Environment         Linux
Python              3.12.3
Install             git
RAM                 31.25 GB
CPU                 Intel Core(TM) i5-4570 3.20GHz
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.3.1>=1.8.0
torchvision         ✅ 0.18.1>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

```

**Comment by StitchUA** [comment]
As I see, pytorch is not installed in project. Sorry I'm newbee yet with Python and AI

![image](https://github.com/user-attachments/assets/3bfd3d58-96bd-4371-98c2-f2a8f97e1314)

**Comment by Y-T-G** [comment]
Is the image from `train_batch.png`?

> 
> ![image](https://private-user-images.githubusercontent.com/3766841/358555056-2bdc4112-d18d-470f-92fa-13fcd6e70560.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MjgzNTQsIm5iZiI6MTcyMzgyODA1NCwicGF0aCI6Ii8zNzY2ODQxLzM1ODU1NTA1Ni0yYmRjNDExMi1kMThkLTQ3MGYtOTJmYS0xM2ZjZDZlNzA1NjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMTcwNzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjFjNDc2ZTU2NjNiOTNjMDBkZTJhMTQ1N2RmZjk3MzA4YzJlMjVkOWEwMjA5ZDE4Y2U2YWI4ZWE1YWYyNzM3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Xg2qndkUbkVZOXRHIpRL5C-Bq5gecVXKADXP3ff0zBs)
>

**Comment by StitchUA** [comment]
On the right side image - yes, it is only added to show that in bboxes, from train_batch and val_batch too, have the same places. I understend, that they needed for only visualization purposes, to tied mask with its bbox.

On the left side imge - no, it is result of the prediction.

This `artifact` are present in every bbox+mask for every label.

**Comment by glenn-jocher** [comment]
Thank you for the clarification. It seems the artifact issue persists in your predictions. Could you try retraining the model with different augmentation settings or without any augmentations to see if the issue resolves? Additionally, ensure your dataset annotations are correct and consistent. If the problem continues, please share more details about your training configuration and dataset.

**Comment by Y-T-G** [comment]
If it appears in train batch, then you have an issue with your labels

**Comment by StitchUA** [comment]
Hi @Y-T-G ,

I have cheked the labels, and you was right. The source of the issue the method which recalculating mask coordinates to normalize them to yolo requirements.
I've changed this method and the issue was solved.

Thanks everybody who helped. :)

**Comment by StitchUA** [comment]
I think it need to close the ticket

**Comment by glenn-jocher** [comment]
@StitchUA thank you for the update. I'll go ahead and close the ticket. If you encounter any further issues, feel free to open a new one.
