### ISSUE TITLE
Face YOLOs , v8 or V9 consistently disregard sizes of eyes, or sizes of faces. Making it impossible to be used for face Loras. its like a lottery game ...

### ISSUE THREAD

**Issue by akos111** [ultralytics/ultralytics#15638]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Face YOLOs , v8 or V9 consistently disregard and wrongly "proportionalize" the sizes of eyes, or sizes of faces. Making it impossible to be used for face Loras. its like a lottery game ... 2 in 10 work, 8 out of 10 are unusable. i tested with xyz plots , using different face loras, different noise, different prompts, in order to end up finding identical errors each time in sizes and placement of eyes, and jawlines, which consequently point to the single one common denominator, the YOLOs that place these regions in the first place. Question is, can a face YOLO be fixed, since this is not  small tiny optimization anymore ... ? ..

### Environment

kunhjbhjbnkj

### Minimal Reproducible Example

no idea what a code here would be

### Additional

Yolos are used on a mac mini M2 Pro , Pinokio and auto1111 with Adetailer ..... and in conjunction with Face-loras to create faceswaps.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@akos111 thank you for your feedback. Please ensure you are using the latest version of the Ultralytics YOLO package. If the issue persists, consider providing a more detailed example or dataset so we can better understand and address the problem.

**Comment by Skillnoob** [comment]
1. Please provide information about your enviroment. Run `yolo checks` in a terminal for that.
2. Provide the code you are running. You did not give us anything to work of.
3. Provide examples where it wrongly "proportionalized" the things you are trying to detect
