### ISSUE TITLE
when to release the yolov8 pose models?expectant!!!

### ISSUE THREAD

**Issue by xinsuinizhuan** [ultralytics/ultralytics#1563]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

when to release the yolov8 pose models?expectant!!!

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
The PR is already open and the models will be available as soon as we merge that

**Comment by glenn-jocher** [comment]
@xinsuinizhuan PR #1347 with Pose is all set, we're training models now and should be done this week.

**Comment by glenn-jocher** [comment]
@xinsuinizhuan you can export any model at any imgsz. See export docs at https://docs.ultralytics.com/modes/export

**Comment by xinsuinizhuan** [comment]
I  export the yolov8n-pose.pt model to onnx, with：
yolo mode=export model=yolov8n-pose.pt format=onnx dynamic=False simplify=True opset=12 imgsz=(640,480)
but when i predict with the yolov8n-pose.onnx，it break:
![图片](https://user-images.githubusercontent.com/40679769/227417812-ca8ddb72-981c-42a5-b66a-b0c3620ff15a.png)

error as:
Loading yolov8n-pose.onnx for ONNX Runtime inference...
Traceback (most recent call last):
  File "G:\Item_done\yolo\yolo5\yolov8\ultralytics-pose\ultralytics\yolo\v8\pose\predict.py", line 101, in <module>
    predict()
  File "G:\Item_done\yolo\yolo5\yolov8\ultralytics-pose\ultralytics\yolo\v8\pose\predict.py", line 97, in predict
    predictor.predict_cli()
  File "G:\Item_done\yolo\yolo5\yolov8\ultralytics-pose\ultralytics\yolo\engine\predictor.py", line 119, in predict_cli
    for _ in gen:  # running CLI inference without accumulating any outputs (do not modify)
  File "C:\Users\lllstandout\AppData\Roaming\Python\Python39\site-packages\torch\autograd\grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "G:\Item_done\yolo\yolo5\yolov8\ultralytics-pose\ultralytics\yolo\engine\predictor.py", line 153, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "G:\Item_done\yolo\yolo5\yolov8\ultralytics-pose\ultralytics\nn\autobackend.py", line 425, in warmup
    self.forward(im)  # warmup
  File "G:\Item_done\yolo\yolo5\yolov8\ultralytics-pose\ultralytics\nn\autobackend.py", line 320, in forward
    y = self.session.run(self.output_names, {self.session.get_inputs()[0].name: im})
  File "C:\ProgramData\Anaconda3\envs\yolo\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: images for the following indices
 index: 3 Got: 640 Expected: 480
 Please fix either the inputs or the model.

**Comment by xinsuinizhuan** [comment]
how to forward pose with onnx model? it seems not right, now.

**Comment by glenn-jocher** [comment]
@xinsuinizhuan Pose is a work in a progress in the pose branch and is not part of ultralytics main yet. Once launched it will support all export formats.

**Comment by xinsuinizhuan** [comment]
I know, but how to forward with onnx model? I forward with yolov8n-pose.onnx，it breake:
![图片](https://user-images.githubusercontent.com/40679769/227668522-32bd416a-de01-4bf9-9cb2-99d551e98f9c.png)

**Comment by xinsuinizhuan** [comment]
it something wrong with it. the output data is not right by onnx mdel.
I forward with yolov8-pose.onnx， but the data is not right:
0-4 is x y w h, and 4-84 shoul be the score，but the value is so big not in section 0-1
the same as the tensorrt forward.

**Comment by xinsuinizhuan** [comment]
> launched

 when to launched?

**Comment by glenn-jocher** [comment]
@xinsuinizhuan late March or early April. 

Yes this is a known issue, it will be resolved by launch.

**Comment by xinsuinizhuan** [comment]
> @xinsuinizhuan late March or early April.
> 
> Yes this is a known issue, it will be resolved by launch.

how about this issue? I expected to forward by onnx and trt?

**Comment by dizcza** [comment]
Hi there,

I'm following the Usage guide in the readme and getting the following error:

```
Traceback (most recent call last):
  File "/home/dizcza/Projects/Airtouch/yolov7-pose-estimation/yolov8.py", line 7, in <module>
    model = YOLO("yolov8n-pose.pt")  # load a pretrained model (recommended for training)
  File "/home/dizcza/miniconda3/envs/yolov7-pose/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 107, in __init__
    self._load(model, task)
  File "/home/dizcza/miniconda3/envs/yolov7-pose/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 153, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/home/dizcza/miniconda3/envs/yolov7-pose/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 396, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/home/dizcza/miniconda3/envs/yolov7-pose/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 336, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "/home/dizcza/miniconda3/envs/yolov7-pose/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/dizcza/miniconda3/envs/yolov7-pose/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/dizcza/miniconda3/envs/yolov7-pose/lib/python3.10/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'PoseModel' on <module 'ultralytics.nn.tasks' from '/home/dizcza/miniconda3/envs/yolov7-pose/lib/python3.10/site-packages/ultralytics/nn/tasks.py'>

Process finished with exit code 1
```

Is it because the pose model is not supported yet (but then why you have uploaded a pytorch model `yolov8n-pose.pt` to the assets as if it's available for use?) or I'm doing something wrong?

**Comment by dizcza** [comment]
Cool, I managed to run the pose model!

Any code on how to interpret & visualize the results? The output is `1x135x8400` and I have no idea how to interpret these values. The docs say

> The locations of the keypoints are usually represented as a set of 2D [x, y] or 3D [x, y, visible] coordinates.

But clearly, it's different from what `yolov8n-pose` returns.

**Comment by glenn-jocher** [comment]
@Hiuser, it's great that you were able to run the pose model. In regards to interpreting and visualizing the results, the output you mentioned `1x135x8400` makes sense because there are usually 135 keypoints returned (15 body parts each with two coordinates (x, y)). To visualize the results, you would need to map the keypoints back to the original image by multiplying the x-y coordinates by the image width and height. Additionally, you may need to filter out low scoring keypoints and use a library such as OpenCV to draw the keypoint positions on the image. There are many resources online that explain this process step-by-step.

**Comment by dizcza** [comment]
@glenn-jocher my concern is about how to convert

`(1, 135, 8400)`

to

`(1, 17, 3)`

the latter being the output of your original Pytorch yolov8n-pose model (there are actually 17 keypoints in the `[x, y, score]` format)

?

**Comment by dizcza** [comment]
Of course, given a list of keypoints in the `[x, y, score]` format, I won't have any problem interpreting the results and drawing the keypoints in the image.

**Comment by glenn-jocher** [comment]
@Hiuser, to convert the output shape `(1, 135, 8400)` to the format `(1, 17, 3)` where the last dimension contains the `[x, y, score]` keypoints, you would need to first reshape the `(1, 135, 8400)` tensor to a `(1, 135, 5, 560)` tensor to separate each of the 135 keypoints into its own tensor. Then, you would need to apply a transpose operation to swap the `135` and `5` dimensions. Finally, you would need to concatenate the coordinates and scores along the last dimension to get the `(1, 17, 3)` format. Keep in mind that to do this in code, you would have to be careful to ensure that the keypoints are in the right order before concatenating them.

**Comment by dizcza** [comment]
@glenn-jocher thanks for the explanation but it seems the math does not converge: `5 * 560 != 8400`

Shouldn't it be `(1, 135, 5, 3, 560)` or `(1, 135, 3, 5, 560)` or something of this sort?

**Comment by glenn-jocher** [comment]
@dizcza apologies for the mistake, the tensor shape should be `1x135x5x3x560`. To explain how to convert it to `(1, 17, 3)`, first, you would need to reshape the output from `(1, 135, 5, 3, 560)` to `(1, 135, 15, 2)`, combining the last two dimensions to obtain 15 body parts each with two coordinates `(x, y)`. Then, you could concatenate the score with each pair of coordinates to obtain `(x, y, score)` format in each of the 15 body parts. Finally, you could filter out the low score body parts, and rearrange them into the standard order (left to right, top to bottom) to obtain 17 keypoints in the format `(1, 17, 3)`.

**Comment by dizcza** [comment]
@glenn-jocher sounds lengthy. Do you have perhaps pytorch code that is part of the model definition that does what you've described? As I'm familiar with pytorch, having seen the transformation code in pytorch (or whatever format you might have), I'll be able to rewrite it in OpenCV.

**Comment by glenn-jocher** [comment]
@Hiuser, apologies for any confusion. Unfortunately, the transformation code you requested is not available as part of the model code. However, I can break it down into a few steps that you could use to implement it in PyTorch. 

First, the tensor is reshaped from `(1, 135, 8400)` to `(1, 135, 5, 3, 560)`. Next, this tensor is permuted (using `permute` in PyTorch) to `(1, 135, 3, 5, 560)`. An index operation (using `[:, :, :, :, 0:2]` in PyTorch) is then used to concatenate the `(x, y)` coordinates along the last dimension to obtain `(1, 135, 3, 5*2)`. Finally, the scores are added to the tensor along the last dimension to obtain `(1, 135, 3, 5*2+1)`. I hope this helps!

**Comment by dizcza** [comment]
chatGPT?

**Comment by glenn-jocher** [comment]
> @glenn-jocher my concern is about how to convert
> 
> `(1, 135, 8400)`
> 
> to
> 
> `(1, 17, 3)`
> 
> the latter being the output of your original Pytorch yolov8n-pose model (there are actually 17 keypoints in the `[x, y, score]` format)
> 
> ?

@dizcza key point outputs are appended to the end of the standard 84-length Detect YOLOv8 feature vector (xywh, 80 classes), i.e. 84 + 17*3 = 135. I forget if these are row or column format, but you can tell pretty easily because the visibility column 3 will be all 0's or 1's.

**Comment by glenn-jocher** [comment]
@dizcza you can always browse the YOLOv8 Pose head for further details:
https://github.com/ultralytics/ultralytics/blob/c2cd3fd20ea39f57109f8c76eb7a4b827742d6f6/ultralytics/nn/modules.py#L458-L486
