### ISSUE TITLE
ONNX Yolov8 infinite loading

### ISSUE THREAD

**Issue by Rockntt** [ultralytics/ultralytics#15641]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi!

```
model = YOLO("nano.onnx")
```
just prints
```
Loading nano.onnx for ONNX Runtime inference...
```

and program freezes...any Ideas?
I use python + opencv with trained yolov8 exported in onnx

**Comment by glenn-jocher** [comment]
@Rockntt hi! Please ensure you have the latest version of the Ultralytics package installed. If the issue persists, try updating your ONNX Runtime library. For more details, visit our [ONNX integration guide](https://docs.ultralytics.com/integrations/onnx/).

**Comment by Rockntt** [comment]
> @Rockntt hi! Please ensure you have the latest version of the Ultralytics package installed. If the issue persists, try updating your ONNX Runtime library. For more details, visit our [ONNX integration guide](https://docs.ultralytics.com/integrations/onnx/).

Hi, Glenn!

My packages have the latest versions (as they represented over python pip). Also here's how I export my model:

```
yolo export model=nano.pt format=ncnn simplify=True int8=True data=data.yaml dynamic=True
```

Maybe It will help us to find out what's wrong.

**Comment by glenn-jocher** [comment]
@Rockntt thanks for the details. It looks like your export command is correct. Please try running the ONNX model with a simpler configuration (e.g., without `optimize`, `simplify`, `int8`, and `dynamic` flags) to isolate the issue. If the problem persists, consider testing the ONNX model with a basic ONNX Runtime script to ensure it's not an environment-specific issue.

**Comment by Rockntt** [comment]
As NCNN is much better for my Raspberry Pi project than ONNX, I'm not re-training or re-exporting ONNX now. If I will have enough time, soon I'll try to fix ONNX problem on Pi and extend this issue.

Now I'm closing this as "stale", but if you have the same problem like me, you can try this:

- training and exporting without any additional parameters as Glenn adviced
- exporting your model on the same device you will be using it at

thanks!

**Comment by glenn-jocher** [comment]
Thank you for the update. If you encounter further issues with ONNX on your Raspberry Pi, feel free to reopen the issue or start a new thread. Best of luck with your project!
