### ISSUE TITLE
about predict parameters and

### ISSUE THREAD

**Issue by yeonhyochoi** [ultralytics/ultralytics#15647]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, thank you always for your hard work.

I'm applying the yolov8 detection model to my personal data set, and looking at the results.png picture, it looks like it's learning really well, but there are too many FPs. I am learning this way.

![results](https://github.com/user-attachments/assets/52f50450-b6b3-4d36-a7f0-dcf1bcf4c8c7)

1. The learning data set is 300,000 images with lesions, 30,000 images without lesions (10%), and the lesion is a single class!

2. Training from scratch with pretrained =False

3. 300epoch training

And the actual test is measuring TP and FP accuracy for each frame in the video.

This is my actual test code. Here's what I'm curious about:
![image](https://github.com/user-attachments/assets/594858b4-8e97-4ada-8d50-8244ad015f50)
![image](https://github.com/user-attachments/assets/33422b1d-a859-4333-9034-22268c152293)

1. Is there a need to change to RGB using cv2.cvtColor?
2. Is it necessary to apply normalization to changed frames?

I've seen this question a lot in your documents, but I'm asking it again. It seems that your documents automatically pre-process the frames even if they are loaded that way.
The reason I ask this question is because I am curious about whether there is a difference between the data being trained and the data being tested during the preprocessing process.

This problem hasn't been resolved for a month. I would really appreciate your help!

**Comment by Y-T-G** [comment]
To avoid default preprocessing, you can pass the preprocessed frames as tensors.
