### ISSUE TITLE
YoloV8 Detect all pretrained class and have confidence = 1.0

### ISSUE THREAD

**Issue by Shiina-kawaeee** [ultralytics/ultralytics#15642]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

I try to detect object in garbage.mp4 but it detect all class it have and each one it detect it have confidence = 1.
I've try to reinstall torch torchvision torchaudio and ultralytics but it don't work,
I also clean reinstall python and python launcher too,

and i use this command from pytorch page to set up torch:
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

*I'm not use python environment*

I also try to use model.predict() too but same problem occur

Can you help me I think it's a bug or something because I didn't see any this kind of bug report,
So if you want more details about my computer please fell free to contact me.

Thanks for all replies.

![Screenshot 2024-08-17 114939](https://github.com/user-attachments/assets/5374c9ae-ee78-423e-aa96-d49bf346c475)
![Screenshot 2024-08-17 idajiod](https://github.com/user-attachments/assets/afcfc7b2-d9dd-407d-a677-0a817a5d90a4)

### Environment

Ultralytics YOLOv8.2.78 🚀 Python-3.12.5 torch-2.4.0+cu118 CPU (AMD Ryzen 7 7730U with Radeon Graphics)
Setup complete ✅ (16 CPUs, 15.4 GB RAM, 119.1/241.1 GB disk)

OS                  Windows-11-10.0.22631-SP0
Environment         Windows
Python              3.12.5
Install             pip
RAM                 15.40 GB
CPU                 AMD Ryzen 7 7730U with Radeon Graphics
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.4.0+cu118>=1.8.0
torchvision         ✅ 0.19.0+cu118>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

from ultralytics import YOLO

model = YOLO('yolov8m.pt')

results = model.track('./garbage.mp4', show=True, persist= True)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
https://github.com/ultralytics/ultralytics/issues/15049

**Comment by Shiina-kawaeee** [comment]
> #15049

Thank you for the answer.  I finally fixed it.

**Comment by glenn-jocher** [comment]
@Shiina-kawaeee great to hear that you resolved the issue! If you have any more questions or run into any other problems, feel free to reach out.

**Comment by Shiina-kawaeee** [comment]
> @Shiina-kawaeee great to hear that you resolved the issue! If you have any more questions or run into any other problems, feel free to reach out.

You can respond with:

Thank you so much! If I have any more questions or run into any other issues, I'll definitely reach out.

**Comment by glenn-jocher** [comment]
Thank you! Feel free to reach out if you have any more questions or issues.
