### ISSUE TITLE
albumentations with yolov8

### ISSUE THREAD

**Issue by yeonhyochoi** [ultralytics/ultralytics#15646]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, i really appreciate your hard works.

I am trying to train the yolov8 model, but albumentations augmentation is not applied well.
For example, I want to adjust the p value that exists in the 'albumentations' class in 'augment.py', and I think 0.01 is too small, but even if I change the value, the existing default value continues to appear in the terminal.

![yolov8_augmentations](https://github.com/user-attachments/assets/1c1fc8ee-3257-4aa2-85fa-a85c4fc28f31)

The photo above is what is output to the terminal and I modified it as shown in the photo below.

![image](https://github.com/user-attachments/assets/07f880c0-6ed9-4785-8358-85b3c76f1f81)

I would appreciate it if you could let me know what the problem is!

**Comment by Y-T-G** [comment]
It works for me:

> albumentations: Blur(p=0.5, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))

Something wrong with your modifications or installation.

**Comment by yeonhyochoi** [comment]
Oh thanks,
I tried to run 
pip install - e.
After this code, i can modify augment.py!!

**Comment by glenn-jocher** [comment]
@yeonhyochoi great to hear that it worked! If you encounter any further issues, feel free to reach out. Happy training!
