### ISSUE TITLE
YOLOv9e-seg giving empty (0 pixel value) segmentation masks

### ISSUE THREAD

**Issue by PythoneerSamurai** [ultralytics/ultralytics#15643]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

Greetings.
Throughout my journey as a computer vision engineer I have trained many YOLO models. However, the last model I trained, namely YOLOv9e-seg, for segmenting the HAM10000 skin cancer dataset, doesn't quite work correctly. The training process went excellent with the model segmenting the images with good precision and recall, however as soon as I used the model to predict on the same images used for training, it seems to be giving masks that are empty (have only one unique value = 0).
I have never faced this issue before.
Following is the link to my model:
https://www.kaggle.com/models/pythonistasamurai/yolov9e-ham1000-segmentation
Following is the link to the HAM10000 dataset:
https://www.kaggle.com/datasets/surajghuwalewala/ham1000-segmentation-and-classification
Following is my notebook:
[yolov9e-supervision-ham1000-skin-cancer-seg.ipynb.zip](https://github.com/user-attachments/files/16643869/yolov9e-supervision-ham1000-skin-cancer-seg.ipynb.zip)

Even if you set save=True in the .predict() function, it can be seen that images with no segmentation are saved.
Kindly fix this issue.
Meanwhile, I'll try to train a yolov8x-seg model to see if it works correctly.

### Environment

Ultralytics YOLOv8.2.78 🚀 Python-3.10.13 torch-2.1.2 CUDA:0 (Tesla T4, 15095MiB)
Setup complete ✅ (4 CPUs, 31.4 GB RAM, 5771.7/8062.4 GB disk)

### Minimal Reproducible Example

Check the ipynb I attached above.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
Post the code for training and prediction. Nobody is going to download a zip file, open IPYNB viewer just to check your code.

**Comment by PythoneerSamurai** [comment]
> Post the code for training and prediction. Nobody is going to download a zip file, open IPYNB viewer just to check your code.

Code for training:
```
!pip install --upgrade ultralytics wandb
!wandb login --cloud "api key"
from ultralytics import YOLO
MODEL = YOLO("yolov9e-seg.yaml")
MODEL.train(
    data="config.yaml",
    epochs=600,
    device=[0, 1],
    pretrained=False,
    patience=50,
)
```

Code for predictions:
``` 
inference=MODEL.predict(
    "Image path",
     imgsz=IMAGE_SIZE,
     conf=0.1,
     save=True
)[0]
numpy_seg = inference.masks.data.cpu().numpy()
print(numpy.unique(numpy_seg))
Output:
[    0]
``

**Comment by Y-T-G** [comment]
Did you try loading the `best.pt`?

**Comment by PythoneerSamurai** [comment]
> Did you try loading the `best.pt`?

No, however the point to be noted is that for many cases the difference between last.pt and best.pt is minimal, still I'll try the best.pt .

**Comment by glenn-jocher** [comment]
Please try using `

**Comment by PythoneerSamurai** [comment]
> Did you try loading the `best.pt`?

Greetings.
Your solution worked, it seems that best.pt seems to be predicting fine.

**Comment by glenn-jocher** [comment]
Great to hear that loading `
