### ISSUE TITLE
The number of images and labels after segmentation with split_dota does not match？

### ISSUE THREAD

**Issue by Cyeden** [ultralytics/ultralytics#15649]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

After I split DOTAv1.0 using split_dota.py, I found that the number of images and the number of labels do not match. Is this normal? How can I fix it?
For example, the train set has 15749 images, but the corresponding labels are only 9734. The following is a screenshot of my split code：
![image](https://github.com/user-attachments/assets/c2e2fcb3-eca1-4476-85b2-0d49f6453dcf)
And this problem will occur regardless of single-scale segmentation or multi-scale segmentation.
I would be very grateful if someone can help me:D

**Comment by Y-T-G** [comment]
If they don't have any labels, there won't be any file.

**Comment by Cyeden** [comment]
@Y-T-G Oh！I got it！Thanks;-)
