### ISSUE TITLE
How to fix the situation like on image?

### ISSUE THREAD

**Issue by AleksandrMarkin** [ultralytics/ultralytics#15653]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to fix the situation like on image? First one, when 2 bounding box have intersections and one of them catchs piace of second one item. The second quaction is iou=8, but some times I have a lot of bounding boxes on 1 item.
![photo_2024-08-17_15-48-07 (2)](https://github.com/user-attachments/assets/34515eb1-391e-4174-9d44-6073e7e53de4)
![photo_2024-08-17_15-48-07](https://github.com/user-attachments/assets/aa5c6053-7575-4dc3-8a32-0d1df7a33233)

**Comment by glenn-jocher** [comment]
@AleksandrMarkin to address overlapping bounding boxes, consider adjusting the Non-Maximum Suppression (NMS) threshold to reduce multiple detections of the same object. For the issue with excessive bounding boxes, ensure your confidence threshold is set appropriately. If the problem persists, please verify with the latest package version.

**Comment by Y-T-G** [comment]
Lower the `iou`
