### ISSUE TITLE
How to use multiple GPU acceleration when using detection models or pose models

### ISSUE THREAD

**Issue by Lanson426** [ultralytics/ultralytics#15650]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,how to use multiple GPU acceleration when using detection models or pose models?

I tried to handle it this way but failed.
![微信截图_20240817185727](https://github.com/user-attachments/assets/4433296c-63cd-4c53-a7a1-b148d4118355)

**Comment by Y-T-G** [comment]
You can't use multiple GPU for inference.
