### ISSUE TITLE
Difference between model(img) and model.model(img) final results after NMS

### ISSUE THREAD

**Issue by w013nad** [ultralytics/ultralytics#1565]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

We have existing code built for syolov4/yolov5 and we wish to adapt yolov8 to match the same outputs as previous models. However, yolov8 does not appear to have a detection confidence (and the 2nd/3rd columns are transposed) on the prediction output. To fix this, I have attempted to write a wrapper to have an encapsulated model which replicates the inputs.

To do this, I simply add a ones column to emulate a detection confidence which goes away in the non_max_suppression.

My dependencies are the ultralytics library, the yolov5 non_max_suppression, torch, and opencv
ultralytics 8.0.14
torch 1.13.1+cu117

```
from ultralytics import YOLO
from utils.general import non_max_suppression
import cv2
import torch

model_file = 'yolov8n.pt'

class v8Wrapper:
    def __init__(self, weights, device=torch.device('cuda'), half=True):
        # Use model.model to get base model
        self.model = YOLO(weights).model.to(device)
        self.model = self.model.half() if half else self.model
        self.device = device
        self.dtype = torch.half if half else torch.float32

    def __call__(self, images, augment=False):
        pred = list(self.model(images, augment))
        bboxes = pred[0][:, :4, :]
        class_conf = pred[0][:, 4:, :]
        detect_filler = torch.ones([1, 1, bboxes.shape[2]], dtype=self.dtype, device=self.device)
        pred[0] = torch.cat([bboxes, detect_filler, class_conf], 1).permute([0, 2, 1])
        return tuple(pred)

# Create callable model
model_wrapped = v8Wrapper(model_file, half=False)
```

This appears to work for the most part. However, the results between my wrapper and the model call appear to be different.

```
file = 'data/images/bus.jpg'
img = cv2.resize(cv2.imread(file), [1024, 1024]) # Resize for demo purposes
imgt = torch.tensor(img).permute([2, 0, 1])[None].cuda().float() / 255 # Reshape into 1x3xXxY shape model expects

res = model_wrapped(imgt)
print(non_max_suppression(res, conf_thres=0.25, iou_thres=0.7)[0])
```

```
tensor([[ 2.80651e+02,  3.81159e+02,  4.35110e+02,  8.16043e+02,  8.76951e-01,  0.00000e+00],
        [ 8.48024e+02,  3.55027e+02,  1.02355e+03,  8.32518e+02,  7.99848e-01,  0.00000e+00],
        [ 6.92207e+01,  3.78802e+02,  2.76434e+02,  8.64346e+02,  7.74455e-01,  0.00000e+00],
        [ 8.44465e+02,  7.81517e+02,  1.02376e+03,  8.38665e+02,  5.81543e-01,  3.60000e+01],
        [-1.04660e-01,  5.10759e+02,  8.72034e+01,  8.29812e+02,  4.49486e-01,  0.00000e+00],
        [ 3.28068e+02,  2.15444e+02,  1.02706e+03,  7.43833e+02,  2.68477e-01,  5.00000e+00],
        [ 2.89601e+01,  1.75114e+02,  9.07108e+02,  7.19062e+02,  2.57056e-01,  7.00000e+00]], device='cuda:0')
```
Whereas 
```
print(YOLO(model_file)(img, imgsz=1024, conf=0.25, iou=0.7)[0])
```

```
tensor([[2.81000e+02, 3.82000e+02, 4.35000e+02, 8.17000e+02, 8.58237e-01, 0.00000e+00],
        [8.47000e+02, 3.63000e+02, 1.02400e+03, 8.34000e+02, 8.41805e-01, 0.00000e+00],
        [6.90000e+01, 3.79000e+02, 2.67000e+02, 8.65000e+02, 8.18468e-01, 0.00000e+00],
        [6.00000e+01, 2.15000e+02, 9.49000e+02, 7.17000e+02, 6.05203e-01, 5.00000e+00],
        [0.00000e+00, 5.19000e+02, 8.90000e+01, 8.31000e+02, 4.24263e-01, 0.00000e+00],
        [2.56000e+02, 2.24000e+02, 1.02300e+03, 6.86000e+02, 3.74312e-01, 5.00000e+00],
        [8.44000e+02, 7.81000e+02, 1.02200e+03, 8.38000e+02, 3.39005e-01, 3.60000e+01]], device='cuda:0')
```

The answers are fairly close. If we look at the first prediction for both methods. The bounding boxes are very slightly off. However, this does vary for other images and can be quite different. Am I misunderstanding something about the model.model call?

I would like to use the model the way it is intended. However, this needs to go into higher level code which must be adaptable for different yolo models.

**Comment by w013nad** [comment]
> @w013nad AMP is applied automatically during predict calls. Accessing the lower level model may not invoke this.

The results remain the same even if I change the image and model to half.

**Comment by glenn-jocher** [comment]
@w013nad then you've likely introduced new steps or are missing steps from the default usage in your custom code.

**Comment by w013nad** [comment]
This is before I'm putting this into my custom code. I'm just trying to verify that it works. To clarify, the only difference between yolov5 and yolov8 outputs of the model.model class are that yolov8 does not have detection confidences?

**Comment by glenn-jocher** [comment]
@w013nad yes that's correct, YOLOv8 outputs are the same as YOLOv5 outputs except they are not transposed and they lack objectness output as it's already built into cls outputs.

**Comment by glenn-jocher** [comment]
@w013nad yes, makes sense. The predict dataloader by default expects BGR if arrays are numpy, to facilitate cv2 usage, i.e. `model(cv2.imread('im.jpg'))`

**Comment by valentin-fngr** [comment]
> @w013nad yes, makes sense. The predict dataloader by default expects BGR if arrays are numpy, to facilitate cv2 usage, i.e. `model(cv2.imread('im.jpg'))`

Hi, Is there any documentation about it ? 
That would be very nice to have it written next to the different type of input you can give to the model during inference.

**Comment by glenn-jocher** [comment]
@valentin-fngr hello! Thank you for your question. At the moment, there is no specific documentation on the dataloader behavior with numpy arrays. However, it is good feedback and we will consider adding this information in the future. If you have any further questions or concerns, please let us know.
