### ISSUE TITLE
How can I get all the pixel coordinates inside contours?

### ISSUE THREAD

**Issue by HamsterPunch** [ultralytics/ultralytics#15662]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello Ultralytics!
I'm using yolov8 segmentation trained with custom data.
My goal to is to get all the pixel coordinates inside the mask.
I've succeeded in getting the mask and the contour, but I'm having difficulties in figuring out how to get the pixel locations which comprise the mask. How can I get the pixel locations inside the mask?
I've been searching the internet for a few days now and I started to feel like it's more of an cv-related issue rather than yolo_related, but still I'm asking you for help just in case.
Followings are snippets from my code

`results = model.predict(source='./human_face.jpg', save=True)`
`result = results[0]`
`for i, box in enumerate(result.boxes):`
        `    detected_class = int(box.cls.cpu())`
        `    if detected_class == 4:`
        `        face_mask = result.masks[i]`
        `    elif detected_class == 8:`
        `        nose_mask = result.masks[i]`
`# How can I get the pixel locations of face mask and nose mask?`

I'd appreciate a little hint.
Thanks

**Comment by Y-T-G** [comment]
The mask has multiple pixels. So I am not sure which pixel locations you want to get.

Wherever the value is not 0 inside the `nose_mask`, it is a mask pixel.

**Comment by Y-T-G** [comment]
`nose_mask.nonzero()` will return all the coordinates/indices where the value is not zero, i.e. all the coordinates of the pixels of the mask.

**Comment by HamsterPunch** [comment]
sorry about not being specific.
I meant the pixels which make up the mask, not the contour.

**Comment by glenn-jocher** [comment]
You can get the pixel coordinates inside the mask using the `numpy` function `nonzero()`. For example, `mask_pixels = np.nonzero(face_mask)` will give you the coordinates of all non-zero pixels in the mask.

**Comment by HamsterPunch** [comment]
Your code works!
Thank you for your help :)

**Comment by glenn-jocher** [comment]
You're welcome! I'm glad to hear that you found the solution helpful. If you have any more questions, feel free to ask.
