### ISSUE TITLE
Segmentation model cannot directly use in IOS device

### ISSUE THREAD

**Issue by Tungway1990** [ultralytics/ultralytics#1566]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

 I notice that the CoreML pipeline is not yet ready for segmentation model.

```python
elif self.model.task == 'segment':
            # TODO CoreML Segmentation model pipelining
            model = self.model
```

May I know if anyone is working on it otherwise or I will try to submit a PR on it.

### Use case

Adding the remaining pipeline so that the polygon prediction can be shown directly on IOS device.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @filipwojtasik, the CoreML pipeline for segmentation is still under development. We appreciate your interest and willingness to contribute through a PR. At this time, our team is focused on other priorities, such as Pose models and HUB integration for YOLOv8. Please keep checking the repository for any updates or changes regarding CoreML segmentation. In the meantime, feel free to continue exploring YOLOv8 and let us know if you have any further questions or concerns.
