### ISSUE TITLE
RuntimeError: Encountered unresolved custom op: edgetpu-custom-op.Node number 0 (edgetpu-custom-op) failed to prepare. but work using tflite interpreter

### ISSUE THREAD

**Issue by ARusDian** [ultralytics/ultralytics#15664]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

So I got Error when try inference with coral USB Accelerator using EDGETPU model by ```YOLO()``` from ultralytics library 

```RuntimeError: Encountered unresolved custom op: edgetpu-custom-op.Node number 0 (edgetpu-custom-op) failed to prepare.```

It Went normal using ```tflite.Interpreter``` but the result is hard to post-process to get the inference result and cause some delays, so tried to use from ultralytics instead to determine which method perform better (tflite interpreter or using ultralytics library).

### Environment

Ultralytics YOLOv8.2.78 🚀 Python-3.9.2 torch-2.0.1 CPU (Cortex-A72)
Setup complete ✅ (4 CPUs, 7.6 GB RAM, 7.2/28.9 GB disk)

OS                  Linux-6.1.21-v8+-aarch64-with-glibc2.31
Environment         Linux
Python              3.9.2
Install             pip
RAM                 7.63 GB
CPU                 Cortex-A72
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 8.1.2>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.25.1>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.0.1>=1.8.0
torchvision         ✅ 0.15.2>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 5.8.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.2>=2.0.0

### Minimal Reproducible Example

```import cv2
import pandas as pd
import numpy as np
from ultralytics import YOLO
import time
from picamera2 import Picamera2

model = YOLO('yolov8n_full_integer_quant_edgetpu_480.tflite',task="detect")


picam = Picamera2()
picam.configure(picam.create_preview_configuration(main={"format": 'XRGB8888', "size": (480, 480)}))
picam.start()
my_file = open("coco.txt", "r")
data = my_file.read()
class_list = data.split("\n")

frame_count = 0
start_time = time.time()

while True:
    frame = picam.capture_array()
    frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    frame_count += 1
    if frame_count % 3 != 0:
        continue

    results = model.predict(frame, imgsz=480)
    a = results[0].boxes.data
    px = pd.DataFrame(a).astype("float")

    for index, row in px.iterrows():
        x1 = int(row[0])
        y1 = int(row[1])
        x2 = int(row[2])
        y2 = int(row[3])
        d = int(row[5])
        c = class_list[d]

        cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)

        cv2.putText(frame, c, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2, cv2.LINE_AA)

    # Calculate FPS
    end_time = time.time()
    elapsed_time = end_time - start_time
    fps = frame_count / elapsed_time

    # Display FPS on frame
    cv2.putText(frame, f"FPS: {fps:.2f}", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2, cv2.LINE_AA)

    cv2.imshow("FRAME", frame)

    if cv2.waitKey(1) & 0xFF == 27:
        break

picam.stop()
cv2.destroyAllWindows()
```

### Additional

Anyway, using latest torch version caused ```Illegal Instruction``` Error, and the running using ```tflite.Interpreter(
            model_path=self.tflite_model, 
            experimental_delegates=[tflite.load_delegate('libedgetpu.so.1')]
            )      ```
works perfectly so i don't think it is coral USB Accelerator Issue

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ARusDian please ensure you are using the latest version of the Ultralytics package. If the issue persists, it may be related to the custom operations required by the Edge TPU. For now, using the `tflite.Interpreter` with the Edge TPU delegate is the recommended approach. For further details, please refer to our guide at https://docs.ultralytics.com/guides/coral-edge-tpu-on-raspberry-pi/.

**Comment by Skillnoob** [comment]
Remove the _480 from your model file name. Its supposed to end in _edgetpu, otherwise ultralytics cannot detect if its a edgetpu model

**Comment by ARusDian** [comment]
> Remove the _480 from your model file name. Its supposed to end in _edgetpu, otherwise ultralytics cannot detect if its a edgetpu model

oh yeah thank you it works now but i got new error, it says

`_interpreter_wrapper.CreateWrapperFromFile( ValueError`

**Comment by glenn-jocher** [comment]
@ARusDian please ensure you are using the latest version of the Ultralytics package. If the issue persists, try converting the model again using the recommended export methods. If you continue to encounter problems, please provide more details about the error message.
