### ISSUE TITLE
yolov8 tflite c++ api not giving correct range of values for the bounding boxes

### ISSUE THREAD

**Issue by AD-lite24** [ultralytics/ultralytics#15660]
I have found the reason why the NMS is not working correct. Getting the output tensor after performing the relevant reshaping and transposing gets us a shape of (8400, 84) which is consistent with the outputs. Now among the 84 the first four are box coordinates (x, y, w, h) while the rest are class scores. The class scores seem _fine_ though not very good when compared to the onnx runtime. The real issue is the box coordinates. 

In tflite my box coordinates take up the values

```
data idx 0: 0.00505153
data idx 1: 0.0262354
data idx 2: 0.0120835
data idx 3: 0.0546932
```

while in onnx they take up the values
```
data idx 0: 3.401
data idx 1: 6.82366
data idx 2: 7.008
data idx 3: 13.7652
```
Granted these are not the same boxes but the range of values it can take up is wildly different which is potentially messing up with the NMS.  Moreover I get a lot more bboxes that I have to process through NMS in tflite vs that in onnx (133 vs 30). I have no idea why this is happening though and how it can be fixed.

_Originally posted by @AD-lite24 in https://github.com/ultralytics/ultralytics/issues/2260#issuecomment-2295166300_

**Comment by glenn-jocher** [comment]
@AD-lite24 thank you for your detailed report. Please ensure you are using the latest version of the Ultralytics package. If the issue persists, consider checking the preprocessing and postprocessing steps for both TFLite and ONNX to ensure consistency. For further assistance, refer to our documentation at https://docs.ultralytics.com/guides/yolo-common-issues/.

**Comment by AD-lite24** [comment]
@glenn-jocher There is no 'ultralytics package', this is c++. The only thing I am using is a yolov8n.pt file I downloaded off the repository and exported it to tflite using the latest ultralytics package if that is what you are referring to. The issue is the results are simply wrong.

**Comment by AD-lite24** [comment]
Issue was fixed, a single reshape was missing. Thanks for the assistance

**Comment by glenn-jocher** [comment]
@AD-lite24 glad to hear the issue was resolved! If you have any more questions or need further assistance, feel free to reach out.
