### ISSUE TITLE
Plot ground truth annotations (object detection)?

### ISSUE THREAD

**Issue by ri2658** [ultralytics/ultralytics#15676]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

This may seem like a basic question, but is there a way to plot the ground truth bounding boxes in addition to the prediction bounding boxes? 

I read the YOLOv8 predict mode documentation, and as far as my tests go, all of the visualization arguments/methods seem to correspond to prediction bounding boxes, not ground truth bounding boxes.

**Comment by glenn-jocher** [comment]
@ri2658 to plot ground truth bounding boxes, you can use the `val` mode with the `save_json` argument set to `True`. This will save the ground truth annotations, which you can then visualize using your preferred plotting library. For more details, please refer to the [validation documentation](https://docs.ultralytics.com/modes/val).

**Comment by Y-T-G** [comment]
`predict` doesn't load the ground-truth annotation.

It's not something that's expected to be present.

**Comment by ri2658** [comment]
I apologize, I should've been more clear in describing the task I am doing.
I was using the `predict` mode on a testing dataset for which I had ground truth annotations. Since `train` and `val` both make caches for ground truth annotations, I thought `predict` would make caches too, but based on your insight this is not the case.

I've tried using the `save_json` argument for `val`, but I've noticed that it only saves detection bounding box coordinates. Even without this argument, I can already extract bounding boxes using `results.boxes.xywh` in the `predict` mode so this would not be very helpful.

I've also tried `save_hybrid`, but this seems to create combinations of ground truth and predictions. It also seems to save only select validation batches, and not specific images I want to feed. 

**Is there any way to plot both ground truth bounding boxes and prediction bounding boxes separately for specific images I feed?**

**Comment by glenn-jocher** [comment]
To plot both ground truth and prediction bounding boxes for specific images, you can manually load the ground truth annotations and overlay them on the images along with the predictions. Unfortunately, `predict` mode does not cache ground truth annotations. You can use a custom script to achieve this by loading the annotations and using a plotting library like Matplotlib to visualize both sets of boxes.

**Comment by ri2658** [comment]
I see; thank you for the insight. Closing issue.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to reach out. Happy coding!

**Comment by ri2658** [comment]
I've created a custom script that plots YOLOv8 bounding boxes to original images. It worked very well for my purposes, so I will put it here for reference. 

```python 
!pip install opencv-python matplotlib pillow

import os
import cv2
import numpy as np

# Define paths
images_path = 'path/to/images'  # Path to your images
annotations_path = 'path/to/annotations'  # Path to your annotations
output_path = 'path/to/output_images'  # Path to save annotated images

# Create output directory if it doesn't exist
os.makedirs(output_path, exist_ok=True)

# Function to draw bounding boxes
def draw_bbox(image, annotation):
    height, width, _ = image.shape
    with open(annotation, 'r') as file:
        for line in file:
            class_id, center_x, center_y, bbox_width, bbox_height = map(float, line.strip().split())
            
            # Convert YOLO format to OpenCV format
            x1 = int((center_x - bbox_width / 2) * width)
            y1 = int((center_y - bbox_height / 2) * height)
            x2 = int((center_x + bbox_width / 2) * width)
            y2 = int((center_y + bbox_height / 2) * height)
            
            # Draw the bounding box
            color = (0, 255, 0)  # Green color for bbox
            cv2.rectangle(image, (x1, y1), (x2, y2), color, 2)
            cv2.putText(image, str(class_id), (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, color, 2)

    return image

# Process each image and its corresponding annotation
for image_file in os.listdir(images_path):
    image_path = os.path.join(images_path, image_file)
    annotation_file = os.path.splitext(image_file)[0] + '.txt'
    annotation_path = os.path.join(annotations_path, annotation_file)
    
    # Check if annotation file exists
    if os.path.exists(annotation_path):
        # Load image
        image = cv2.imread(image_path)
        
        # Draw bounding boxes
        annotated_image = draw_bbox(image, annotation_path)
        
        # Save the annotated image
        output_image_path = os.path.join(output_path, image_file)
        cv2.imwrite(output_image_path, annotated_image)

        print(f"Saved annotated image: {output_image_path}")

print("All images processed.")

```

**Comment by glenn-jocher** [comment]
Thank you for sharing your custom script! It's great to hear that it worked well for your purposes. If you have any further questions or need additional assistance, feel free to ask.
