### ISSUE TITLE
How to output the feature maps of certain layers?

### ISSUE THREAD

**Issue by AaspiralMoon** [ultralytics/ultralytics#15678]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi ultralytics teams,

I'm using detector model with yolov8n, and i'm wondering how to output the feature maps of certain layers? For example, i want to output the feature maps of P4. How should i modify the corresponding code? Could you please give me some instructions? 

Thanks!

**Comment by glenn-jocher** [comment]
@AaspiralMoon to output feature maps of certain layers, you can register forward hooks on the desired layers. Here's a minimal example:

```python
from ultralytics import YOLO

model = YOLO('yolov8n.pt')
layer_name = 'model.14.cv2'  # Replace with your target layer name

def hook_fn(module, input, output):
    print(output.shape)  # Or save the output as needed

layer = dict(model.named_modules())[layer_name]
layer.register_forward_hook(hook_fn)

# Run inference to trigger the hook
model('path/to/image.jpg')
```

Replace `'model.14.cv2'` with the specific layer name you want to inspect.

**Comment by Y-T-G** [comment]
You use the `embeds` argument to specify which layers to return the output from:

`model.predict(..., embed=[4, 5])` returns the output of 4th and 5th layer.

**Comment by AaspiralMoon** [comment]
@glenn-jocher @Y-T-G Thanks for the reply. I just want to double check the number on each layer in the following figure corresponds to the options of embed argument, right? For example, if I want to output the features of C2F after P4, i just have to set embed=[6].

![yolov8](https://github.com/user-attachments/assets/b39db9eb-43b0-4577-95e6-63e1405b2e85)

**Comment by Y-T-G** [comment]
You could just check the `yaml` file for the model. Or even browse it in Python:

```
model = YOLO("yolov8n.pt")
print(model.model.model[0]) # Layer 0
print(model.model.model[1]) # Layer 1
```
