### ISSUE TITLE
Increasing Memory Usage During Continuous Video Processing with YOLOv8

### ISSUE THREAD

**Issue by dimasalifta** [ultralytics/ultralytics#15682]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am working on a real-time video processing application using YOLOv8 for object detection. I’ve encountered an issue where memory usage gradually increases with each iteration of the processing loop, even though I am using gc.collect() and deleting intermediate variables.

Here is the code snippet I’m using:

### Additional

import cv2
import gc
import tracemalloc
from ultralytics import YOLO
from memory_profiler import profile

# Start tracing memory allocations
tracemalloc.start()

@profile
def run_inference():
    model = YOLO("yolov9t.pt")

    cap = cv2.VideoCapture(0)

    while cap.isOpened():
        success, frame = cap.read()

        if success:
            frame = cv2.resize(frame, (640, 480))

            results = model.predict(frame, 
                                    verbose=False, 
                                    imgsz=320,
                                    max_det=1,
                                    vid_stride=10
                                   )
            
            results = results.cpu() if results.is_cuda else results
            
            annotated_frame = results[0].plot()

            cv2.imshow("YOLOv8 Inference", annotated_frame)

            del results
            del annotated_frame
            del frame

            gc.collect()

            current, peak = tracemalloc.get_traced_memory()
            print(f"Current memory usage: {current / 10**6:.2f}MB; Peak: {peak / 10**6:.2f}MB")

            if cv2.waitKey(1) & 0xFF == ord("q"):
                break
        else:
            break

    cap.release()
    cv2.destroyAllWindows()

    tracemalloc.stop()
    gc.collect()

if __name__ == "__main__":
    run_inference()

**Comment by ou525** [comment]
My problem is also like this, and I have updated the latest code as much as possible.

**Comment by glenn-jocher** [comment]
It sounds like a memory leak issue. Ensure you're using the latest YOLOv8 version and consider checking for any lingering references in your loop. If the problem persists, reviewing the Ultralytics documentation on common issues might help.
