### ISSUE TITLE
Overlap mask when inference

### ISSUE THREAD

**Issue by binhaicycle** [ultralytics/ultralytics#15684]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained a YOLOv8 model for instance segmentation. During inference, some objects have masks with missing middle parts, which overlap with other objects. For example, as shown in the figures below, Figure 1 represents the mask of a car's hood, while Figure 2 shows the mask of a specific component located on that hood. I would like the first mask to include the second mask. How can I achieve this?

First mask:
![image](https://github.com/user-attachments/assets/9f099da4-900f-4d70-b536-94b79e55c35f)

Second mask:
![image](https://github.com/user-attachments/assets/b6d1e502-9f9c-4b34-99ce-ce57e7aeb3a0)

**Comment by Y-T-G** [comment]
You will have to retrain with `overlap_mask=False`

**Comment by binhaicycle** [comment]
Thank you, @Y-T-G . I'm currently retraining my model. This argument is a bit confusing. I initially thought that setting overlap_mask would allow the masks to overlap.

**Comment by Y-T-G** [comment]
It can be confusing at first. It's `True` by default. If it's true, it merges the masks of all the classes into a single mask, so overlapping is discarded, i.e. it means "overlap all the masks to create a single mask".

So to keep each of mask separate as their own mask, you have to set it to `False`.
