### ISSUE TITLE
CUDA out of memory with backbone p4

### ISSUE THREAD

**Issue by Spratumn** [ultralytics/ultralytics#15685]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I added "backbone P4" to fpn and head, and it runs ok at the ealy batches, but i get "RuntimeError: CUDA out of memory" after hundreds of batches

**Comment by glenn-jocher** [comment]
@Spratumn it sounds like your model is running out of GPU memory during training. Please try reducing the batch size or image size, and ensure you are using the latest version of the Ultralytics package. If the issue persists, consider using gradient accumulation to manage memory usage more effectively.

**Comment by Spratumn** [comment]
I tried setting the batch size to 2, but the same situation still occurs. Why doesn't the error happen at the beginning of the training, but instead there's a sudden memory explosion after some time?

**Comment by Spratumn** [comment]
@glenn-jocher I tried setting the batch size to 2, but the same situation still occurs. Why doesn't the error happen at the beginning of the training, but instead there's a sudden memory explosion after some time?

**Comment by glenn-jocher** [comment]
@Spratumn it sounds like there might be a memory leak or accumulation issue. Ensure you're using the latest Ultralytics package and try monitoring memory usage over time to identify any patterns or specific operations causing the spike.
