### ISSUE TITLE
train from scratch, freeze parameter not working

### ISSUE THREAD

**Issue by dhruvinvadgama** [ultralytics/ultralytics#15688]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How do I train the YOLO model from scratch? I do not want to freeze any layers and train all from scratch.

I would like to know the following things, which I didn't clearly understand from the website and github issues.

I would like to train the model from scratch. As per your suggestions from this github issue: [Github Issue](https://github.com/ultralytics/ultralytics/issues/13781), I tried setting the `freeze` parameter in the `model.train()` to `0` and/or `None`, but I still see this line when I start the training: `Freezing layer 'model.22.dfl.conv.weight`
Should I ignore it? 
additionally, I have also tried updating the ultralytics library, removing and reinstalling again, but I still see the same line.

Here is the code

```
...imports...

model =  YOLO('yolo8n.yaml')
results = model.train(data= 'data_custom.yaml', epochs = 10, imgsz = 640, freeze = None)
```

## alternate try

```
results = model.train(data= 'data_custom.yaml', epochs = 10, imgsz = 640, freeze = 0, pretrained = False)´
```

I'd be glad if you could provide me with a clear answer to train my model from scratch.

**Comment by Y-T-G** [comment]
That layer always freezes and it's normal
