### ISSUE TITLE
Use Custom Transformations and custom Dataloader

### ISSUE THREAD

**Issue by dhruvinvadgama** [ultralytics/ultralytics#15694]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would like to use custom transformations and custom dataloader for training the model. I saw a few Github issues which talk about this and also on the ultralytics website Q&A ([Similar issue](https://docs.ultralytics.com/modes/train/)), but I did not get a clear answer about how to use it.

I have custom transformations which I want to use, not the default ones which are available like resize, horizontalflip etc, but I have custom functions which do transfomation on images like `Erosion`, `dilation`, `Erosion&Dilation` etc. How do I integrate these in my training?

The model only accepts `data.yaml` file, and not dataloaders. 
What do I do to make the model accept the dataloader? I read in one of the issues that the training loop of YOLO can be modified, but how? Could anyone please guide me on this?

I have custom transformations defined with `pytorch` like this:

```
transform = v2.Compose(
       [ 
              Erosion(),
              Dilation(),
              customfunction_1(),
              customfunction_2(),
              .....,
              .....,
              .....,
              T.resize((640,640)),
              v2.Dtype(torch.float32, scale = True),
              v2.Normalize(mean=[0.485, 0.456, 0.406], std = [0.299, 0.224, 0.225])
       ]
)
```

This is how my custom dataloader looks like:

```
class CustomDataPipeline(Dataset): 
     def __init__(self, image_paths, annotation_paths, transform = None):
           self.image_paths = image_paths
           self.annotation_paths = annotation_paths
           self.transform = transform 
     
     def __getitem__(self, idx):
            img = cv2.imread(str(self.image_paths[idx]))
            img = self.transform(img)
            .....
            .....
            .....

            return img, target 

      def __len__(self): 
            return len(self.image_paths)
```

1) How do I use this dataloader for training the model? 
2) To make it simple, is it possible to use custom transformations directly in the `data.yaml` file?

**Comment by Y-T-G** [comment]
You will have to first create a new custom dataset class inheriting from `YOLODataset` class and override the `build_transforms` function to return your own transforms:
https://github.com/ultralytics/ultralytics/blob/7a79680dcc1d9c8d8da1c3910fa1775110c41255/ultralytics/data/dataset.py#L46

Then you have inherit the `DetectionTrainer` to create a new custom trainer class and override the `build_dataset` function to use your custom dataset class that you used above. Here's how it's done for `YOLOWorld`:
https://github.com/ultralytics/ultralytics/blob/7a79680dcc1d9c8d8da1c3910fa1775110c41255/ultralytics/models/yolo/world/train.py#L68

Then you have to pass that trainer class as argument to `model.train(..., trainer=CustomTrainer)` like how it's done for YOLO World training:

https://docs.ultralytics.com/models/yolo-world/#launch-training-from-scratch
