### ISSUE TITLE
Determining the detection head and anchor scale of a bounding box's corresponding feature maps in YOLOv8

### ISSUE THREAD

**Issue by leethologica** [ultralytics/ultralytics#15695]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello! I am currently working on an implementation that analyzes intermediary feature maps of YOLO models. I had implemented a working solution for YOLOv3 which involved extracting the intermediary feature maps of the input features to each detection head. For example, I would have a set of three extracted features in a dictionary:
```
features = {
    0: array of shape [n, 256, 80, 80],
    1: array of shape [n, 512, 40, 40],
    2: array of shape [n, 1024, 20, 20],
}
```
where `n` is the batch size. Given a ground truth bounding box annotation, I could translate the location of the bounding box from `cls, x, y, w, h`  to `cls, x1, y1, x2, y2`, obtain the `x1, y1, x2, y2` of the static anchor-boxes, determine the best IoU anchor box, and from there obtain exactly which detection head, anchor scale, and grid cell that feature map corresponds to. If the anchor box of a particular bounding box `i` corresponded to head 1, grid cell (12, 15), then I could take `features[1][i, :, 12, 15]`. 

I am wondering how I can translate this approach to YOLOv8, with its anchor-free architecture. I understand that while it is anchor free in the sense that it does not produce offsets to a static set of anchor boxes and instead predicts directly the center of a bounding box, it still uses anchor boxes during training. There are still three prediction heads, and there are still grid cells — I should be able to use the same theoretical approach, but it is unclear to me how to determine which head and anchor scale to use since my previous transformations relied on determining which static anchor box a detection corresponded to.

I have the following snippet of the YOLOv8 architecture that shows the layers I believe are relevant. Unlike YOLOv3 which handled the object classification and bounding box regression together, YOLOv8 has them in separate branches which I have labeled and color-coded (hopefully correctly):

![Screenshot 2024-08-19 at 9 43 56 AM](https://github.com/user-attachments/assets/04a3a078-5c00-4c90-b613-0530979cee45)

Specifically, I am taking the input features to each of the colored branches (there are only three since the input features to the class and bounding box branches are the same for each head). My new dictionary is of form:
```
features = {
    0: [n, 576, 20, 20],
    1: [n, 384, 40, 40],
    2: [n, 192, 80, 80],
}
```
I still have the COCO ground truth annotations of form `cls, x, y, w, h` which can still be translated to `cls, x1, y1, x2, y2`. I can also still obtain grid cell indexes by dividing the image width and height by each head's window divisor `(32, 16, 8)` to obtain cell dimensions and figuring out which cell contains the center point of the bounding box.

How do I then determine from the ground truth annotation which head, 0, 1, or 2, the feature map would have come from? Additionally, in YOLOv3, there was a concept of three anchor scales for each head which represented the static anchor aspect ratios — is there an equivalent in YOLOv8, and could I obtain those too somehow?

Thanks!

**Comment by leethologica** [comment]
Thank you! Reading through the `TaskAlignedAssigner` and `v8DetectionLoss` helped clarify how the offsets to anchor centers are found from features. A few more specific questions:
* The `make_anchors` method is called repeatedly, but it appears to me that it yields the same anchor points every time, as it is only dependent on feature shape and stride, both of which are the same for a particular YOLO model. Why are the anchor points not simply generated once as a class attribute? Just wondering if I am misunderstanding something, and if the anchor points do indeed change depending on input.
* I am still a bit unclear about how I could go in the reverse direction — given a ground truth box of form `x, y, w, h` or a transformation to the top-left, bottom-right corner `x, y, x, y` representation, I don't understand how I would determine which of the 8400 anchor positions to use. I could obtain the center of the ground truth box and find the anchor point closest to that center, but is that actually guaranteed to be the feature from which the predicted bounding box would come from? What would happen if the ground truth center fell in the exact middle of two or four anchor points?

**Comment by Y-T-G** [comment]
1. It's probably done to support `multi-scale` training.
2. The anchor points are determined here:
https://github.com/ultralytics/ultralytics/blob/7a79680dcc1d9c8d8da1c3910fa1775110c41255/ultralytics/utils/tal.py#L213
So in case of edge cases, it would just behave how `torch.amin()` behaves when there are multiple equal minimum values.
