### ISSUE TITLE
resume=True argument

### ISSUE THREAD

**Issue by rhalder2023** [ultralytics/ultralytics#15700]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, So I wanted to continue training a model from where it was stopped, so I was playing around with the resume=true parameter in the train() function. 
I was going over the issue #14073 where they were encountering the same issue when resuming training. 
![image](https://github.com/user-attachments/assets/89c76e41-16af-459e-9862-8d0649a4b0fc)
This is the error.

I tried multiple things, including upgrading pip and ultralytics. 

Im noticing, whenever resume=true, its creating another folder called YOLOV8 and inside that it there is a folder called yolo8m-seg and inside that is a args.yaml that has those 3 parameters

![image](https://github.com/user-attachments/assets/9b5df55d-243c-4a4b-86ce-7f37e59b0bd0)

I dont understand why its doing that, because in the train func im already specifying everything,
![image](https://github.com/user-attachments/assets/d7c3b2e5-1b88-4d53-ab35-d9fc283acfae)
this is the function call

Can I get some help? or do i need to let resuming training go as a viable option? :(

**Comment by rhalder2023** [comment]
> ### Search before asking
> * [x]  I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> ### Question
> Hi, So I wanted to continue training a model from where it was stopped, so I was playing around with the resume=true parameter in the train() function. I was going over the issue #14073 where they were encountering the same issue when resuming training. ![image](https://private-user-images.githubusercontent.com/126802941/359209520-89c76e41-16af-459e-9862-8d0649a4b0fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTM4OTYsIm5iZiI6MTcyNDA5MzU5NiwicGF0aCI6Ii8xMjY4MDI5NDEvMzU5MjA5NTIwLTg5Yzc2ZTQxLTE2YWYtNDU5ZS05ODYyLThkMDY0OWE0YjBmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQxODUzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODBjNjAzN2M4ODIwYjJkNmU4ZTMyNDNhMDRkNTkyNzVhODA3MmViNWY0ZmU3NWNiNzhkZTc2NjE4YzAzN2UxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tbba1W0moYQFV9i7bXf9ekB6Ni8uPDC8-2qLOLzCiP8) This is the error.
> 
> I tried multiple things, including upgrading pip and ultralytics.
> 
> Im noticing, whenever resume=true, its creating another folder called YOLOV8 and inside that it there is a folder called yolo8m-seg and inside that is a args.yaml that has those 3 parameters
> 
> ![image](https://private-user-images.githubusercontent.com/126802941/359210066-9b5df55d-243c-4a4b-86ce-7f37e59b0bd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTM4OTYsIm5iZiI6MTcyNDA5MzU5NiwicGF0aCI6Ii8xMjY4MDI5NDEvMzU5MjEwMDY2LTliNWRmNTVkLTI0M2MtNGE0Yi04NmNlLTdmMzdlNTliMGJkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQxODUzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTRiODk4ODM4Zjg0N2JmYWZjOTMzNGQ5OGE1MmU0MmQ4MWI4ZjVmYzdiYjM3MDdiMmVkNDA4ZmQ0NmE3MGE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dkCp0DPfc-TnilLw0ERP8FLacMPg63cpp5RLH9tERcA)
> 
> I dont understand why its doing that, because in the train func im already specifying everything, ![image](https://private-user-images.githubusercontent.com/126802941/359210274-d7c3b2e5-1b88-4d53-ab35-d9fc283acfae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTM4OTYsIm5iZiI6MTcyNDA5MzU5NiwicGF0aCI6Ii8xMjY4MDI5NDEvMzU5MjEwMjc0LWQ3YzNiMmU1LTFiODgtNGQ1My1hYjM1LWQ5ZmMyODNhY2ZhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQxODUzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMGUyODkyMzM2NDU1ZDZjMGQyMWVmOTJmOTU1NDkwNDUwZDg0NGZiZWY4MTBjZWJkMjI4OTU0MTgwM2RlYjUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WKBTyc14ya9UoYKb8bH77qUPXTZJDeeZHzIZEb0Ros8) this is the function call
> 
> Can I get some help? or do i need to let resuming training go as a viable option? :(
> 
> ### Additional
> _No response_

Okay, I am using python 3.10 if thats a problem

**Comment by rhalder2023** [comment]
![image](https://github.com/user-attachments/assets/710e406b-4168-4183-a4cd-c7dea990599c)

These are my version details

**Comment by rhalder2023** [comment]
I am on ultra

> To resume, you don't need to add any argument besides `data`

But if i dont add anything else it just creates another folder in the project directory and starts training from scratch

**Comment by glenn-jocher** [comment]
It sounds like there might be an issue with how the resume functionality is being handled. Please ensure you're using the latest version of the Ultralytics package. If the problem persists, could you share the exact command or code snippet you're using?

**Comment by Y-T-G** [comment]
Load the `last.pt` and then use `resume=True`

**Comment by rhalder2023** [comment]
> It sounds like there might be an issue with how the resume functionality is being handled. Please ensure you're using the latest version of the Ultralytics package. If the problem persists, could you share the exact command or code snippet you're using?

I shared all of that above, like im using ultralytics 8.2.79, and the commands also above, im just loading the model and then using the .train() funciton.

Once i ran it without resume=True, and set up a training for 50 epochs, i stopped it in the middle using "ctrl+c", then i used the same code, just changed the resume argument and ran the code again

**Comment by rhalder2023** [comment]
> Load the `last.pt` and then use `resume=True`

woah, this worked, i mean i thought i should try this but. Thankkk yooouuuu

**Comment by glenn-jocher** [comment]
@rhalder2023 glad to hear it worked! If you have any more questions or run into any other issues, feel free to ask. Happy training!
