### ISSUE TITLE
Docker + Deepstream in a Jetson Orin Nano

### ISSUE THREAD

**Issue by jvd-monteiro** [ultralytics/ultralytics#15705]
Hello!

I've just started using a Jetson Orin Nano and was running the example in https://docs.ultralytics.com/guides/deepstream-nvidia-jetson/#deepstream-configuration-for-yolov8. 

When running locally it all works fine, but when trying to run a container I'm getting errors and still don't know what the best approach would be. Should I install deepstream inside the container (if so could you please give me some light on how to) or simply mount the Deepstream library I already have in the Jetson to the container?

Thanks for any kind of help!

**Comment by isratjerinruba2** [comment]
https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

https://skylivetvgo.com/viral/?yy

**Comment by Y-T-G** [comment]
What container? DeepStream has its own comtainer.
