### ISSUE TITLE
Using onnx yolov8n-cls custom classification model. CLI right but python code has error!

### ISSUE THREAD

**Issue by erfansafaie** [ultralytics/ultralytics#15706]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict, Export

## A problem in running python code
I have trained yolov8-cls model to classification car color models with 7 class. Run in .pt mode has right answer but when export ONNX model using python code has error but when using CLI run correctly.

## Export code:
modelColorPt = YOLO('/carColorV2.pt', 'task = classify')
modelColorPt.export(format="onnx") 

## CLI:
yolo predict task=classify model='/carColorV2.onnx' source='/225.jpg'
## Output:
white 0.71, blue 0.10, gray 0.09, black 0.04, yellow 0.04, 785.0ms
## Using in python:
modelColorOnnx = YOLO('/carColorV2.onnx', 'task = classify')
results = modelColorOnnx.predict(carCrop, task='classify', imgsz=640)[0]
probs = results.probs.data.tolist()
print(probs)
maxProb = max(probs)
## Error:
AssertionError: input shape last dimension expected 4 but input shape is torch.Size([7, 1])

### Environment

Ultralytics YOLOv8.2.79 🚀 Python-3.10.12 torch-2.3.1+cu121 CPU (Intel Xeon 2.20GHz)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 33.8/107.7 GB disk)

OS                  Linux-6.1.85+-x86_64-with-glibc2.35
Environment         Colab
Python              3.10.12
Install             pip
RAM                 12.67 GB
CPU                 Intel Xeon 2.20GHz
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.7.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.3.1+cu121>=1.8.0
torchvision         ✅ 0.18.1+cu121>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.1.4>=1.1.4
seaborn             ✅ 0.13.1>=0.11.0
ultralytics-thop    ✅ 2.0.5>=2.0.0

### Minimal Reproducible Example

modelColorPt = YOLO('/carColorV2.pt', 'task = classify')
modelColorPt.export(format="onnx") 

## python:
modelColorOnnx = YOLO('/carColorV2.onnx')
results = modelColorOnnx.predict(carCrop, task='classify', imgsz=640)[0]
probs = results.probs.data.tolist()
print(probs)
maxProb = max(probs)

## CLI:
yolo predict task=classify model='/carColorV2.onnx' source='/225.jpg'

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
You're supposed to use `task="classify"` while loading the model inside `YOLO()` not in `predict()`

**Comment by erfansafaie** [comment]
### I change the
>modelColorOnnx = YOLO('/carColorV2.onnx')
>results = modelColorOnnx.predict(carCrop, task='classify', imgsz=640)[0]
### to 
>modelColorOnnx = YOLO('/carColorV2.onnx', 'task = classify')
>results = modelColorOnnx.predict(carCrop, imgsz=640)[0]
>results = modelColorOnnx(carCrop, imgsz=640)[0]
#### and test again
### I face new error in both cases:
KeyError: 'task = classify'
The above exception was the direct cause of the following exception:
NotImplementedError                       Traceback (most recent call last)
NotImplementedError: WARNING ⚠️ 'YOLO' model does not support 'predict' mode for 'task = classify' task yet.

**Comment by erfansafaie** [comment]
> You're supposed to use `task="classify"` while loading the model inside `YOLO()` not in `predict()`

I change the
modelColorOnnx = YOLO('/carColorV2.onnx')
results = modelColorOnnx.predict(carCrop, task='classify', imgsz=640)[0]

to
modelColorOnnx = YOLO('/carColorV2.onnx', 'task = classify')
results = modelColorOnnx.predict(carCrop, imgsz=640)[0]
results = modelColorOnnx(carCrop, imgsz=640)[0]

and test again
I face new error in both cases:
KeyError: 'task = classify'
The above exception was the direct cause of the following exception:
NotImplementedError Traceback (most recent call last)
NotImplementedError: WARNING ⚠️ 'YOLO' model does not support 'predict' mode for 'task = classify' task yet

**Comment by erfansafaie** [comment]
> You're supposed to use `task="classify"` while loading the model inside `YOLO()` not in `predict()`

### I change the
modelColorOnnx = YOLO('/carColorV2.onnx')
results = modelColorOnnx.predict(carCrop, task='classify', imgsz=640)[0]

### to
modelColorOnnx = YOLO('/carColorV2.onnx', 'task = classify')
results = modelColorOnnx.predict(carCrop, imgsz=640)[0]
results = modelColorOnnx(carCrop, imgsz=640)[0]

#### and test again
### I face new error in both cases:
KeyError: 'task = classify'
The above exception was the direct cause of the following exception:
NotImplementedError Traceback (most recent call last)
NotImplementedError: WARNING ⚠️ 'YOLO' model does not support 'predict' mode for 'task = classify' task yet

**Comment by Y-T-G** [comment]
It's not `'task = classify'`. It's `task="classify"`

**Comment by erfansafaie** [comment]
it's worked! thanks

**Comment by glenn-jocher** [comment]
Great to hear that it worked! If you have any more questions or run into further issues, feel free to ask.
