### ISSUE TITLE
YOLOv8 Segmentation Fault when using GPU

### ISSUE THREAD

**Issue by andreaeusebi** [ultralytics/ultralytics#15702]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

Hi I've recently installed ultralytics package via:
`pip install ultralytics`

and during installation everything seemed to be fine.

I have a laptop with a Nvidia GPU model: Quadro T550.
I have CUDA 11.8, cudNN 8.9.7 and pythorch 2.0.1 installed.

If I run `torch.__version__` command I get: `'2.0.1+cu118'`.

I'm trying to run a simple inference test script to check that everything is fine.

This is the script that I'm running:

```
from ultralytics import YOLO, checks
import torch

checks()

print(f"Cuda available: {torch.cuda.is_available()}")

model = YOLO("yolov8m.pt").to("cuda")

print(model.device)

print("Succesfully loaded YOLOv8 model!")

results = model.predict("cat_dog.jpg")
```

But I got a segmentation fault error, as can be seen from the terminal output below:

_Ultralytics YOLOv8.2.78 🚀 Python-3.8.10 torch-2.0.1+cu118 CUDA:0 (NVIDIA T550 Laptop GPU, 3914MiB)
Setup complete ✅ (12 CPUs, 31.0 GB RAM, 400.1/737.2 GB disk)
Cuda available: True
cuda:0
Succesfully loaded YOLOv8 model!
Segmentation fault (core dumped)_

The strange thing is that if I switch from "cuda" to "cpu" when instantiating the YOLO model, everything is fine and it can run inference normally. THis is the output in this second case:

_Ultralytics YOLOv8.2.78 🚀 Python-3.8.10 torch-2.0.1+cu118 CUDA:0 (NVIDIA T550 Laptop GPU, 3914MiB)
Setup complete ✅ (12 CPUs, 31.0 GB RAM, 400.1/737.2 GB disk)
Cuda available: True
cpu
Succesfully loaded YOLOv8 model!
image 1/1 /home/andrea/raymond/yolov8/cat_dog.jpg: 448x640 1 cat, 1 dog, 563.1ms
Speed: 1.5ms preprocess, 563.1ms inference, 0.6ms postprocess per image at shape (1, 3, 448, 640)_

I don't think is a problem of too few GPU memory because if I look at memory usage using "nvtop" command this is what I see:

![image](https://github.com/user-attachments/assets/b915ee7d-d1ea-4ca6-95ff-6c69fe0ba3ec)

As you can see memory usage is quite limited (right plot refers to discrete GPU, while left plot to integrated GPU).

What do you think could be the problem for this??

### Environment

Ultralytics YOLOv8.2.78 🚀 Python-3.8.10 torch-2.0.1+cu118 CUDA:0 (NVIDIA T550 Laptop GPU, 3914MiB)
Setup complete ✅ (12 CPUs, 31.0 GB RAM, 400.1/737.2 GB disk)

### Minimal Reproducible Example

from ultralytics import YOLO, checks
import torch

checks()

print(f"Cuda available: {torch.cuda.is_available()}")

model = YOLO("yolov8m.pt").to("cuda")

print(model.device)

print("Succesfully loaded YOLOv8 model!")

results = model.predict("cat_dog.jpg")

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@andreaeusebi thank you for reporting this issue. Please ensure you are using the latest version of the Ultralytics package by running `pip install --upgrade ultralytics`. If the problem persists, try updating your GPU drivers and CUDA toolkit. If the issue continues, please provide additional details or logs for further investigation.

**Comment by Y-T-G** [comment]
Remove this:

`.to("cuda")`

You're supposed to pass the device using the `device` argument to predict.

**Comment by dearMOMO** [comment]
Excuse me, what is the command of the following graphical interface
![image](https://github.com/user-attachments/assets/d608931b-0120-46b1-a2b2-e13a380f65ae)

**Comment by glenn-jocher** [comment]
Thank you for your suggestion. However, the issue seems to be related to GPU usage rather than CPU cache. We'll focus on GPU-related troubleshooting steps.

**Comment by andreaeusebi** [comment]
Hi all and thanks for your suggestions.
After some further trials I've been able to make the script work by simply switching the importing order.
If I import torch before ultralytics everything works fine! This is very strange and I can not give an answer, but maybe could be worth investigating a little more...
Anyway, thanks again to you all for your support!

**Comment by glenn-jocher** [comment]
Thank you for the update! We're glad to hear that switching the import order resolved the issue. We'll look into this further. If you encounter any more problems, please let us know.
