### ISSUE TITLE
Docker + Deepstream on Jetson Orin Nano

### ISSUE THREAD

**Issue by jvd-monteiro** [ultralytics/ultralytics#15707]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I'm using a Jetson Orin Nano and wanted to try different set ups to run a YOLO model with Deepstream.
When setting things locally I can make it work, but when setting up a Docker with:
```
t=ultralytics/ultralytics:latest-jetson-jetpack6
sudo docker pull $t && sudo docker run -it --ipc=host --runtime=nvidia $t
```
I can make regular inference work, but was still not able to do it with Deepstream. So my main question is on how to set up a Container with Deepstream appropriately, since the one created above is not working... Should I create the NVIDIA Deepstream container itself and then set up Ultralytics libraries inside it? Please shed some light on the best approach for it.

Thanks in advance!

**Comment by glenn-jocher** [comment]
@jvd-monteiro hello,

For running YOLO with DeepStream in a Docker container on Jetson Orin Nano, it's best to start with the NVIDIA DeepStream container and then install the Ultralytics libraries within it. This ensures compatibility with DeepStream's dependencies. You can follow the detailed guide at https://docs.ultralytics.com/guides/deepstream-nvidia-jetson/ for step-by-step instructions.

Thanks!
