### ISSUE TITLE
How to run multiple yolo models in parallel within one GPU?

### ISSUE THREAD

**Issue by webzhao9125** [ultralytics/ultralytics#15712]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I now have multiple yolo models which have the same input image. I have only one GPU, during inference, if I use the sequential execution method, the time complexity increases with the number of models, is there any way I can run multiple models in parallel on one GPU to reduce the inference time?

Meanwhile, I try to freeze the backbone part to train the yolo model, and then inside task.py I try to speed up the inference by using the common backbone output and then connecting Neck and Head. But I found that as the model increases, this approach takes more time than the linear increase, may I ask why, is it because of the multiple conversion of cpu and gpu or something else? Here is my code.

![image](https://github.com/user-attachments/assets/ab68933b-ee64-4a85-8336-11372b3afe65)

**Comment by Y-T-G** [comment]
You can use Triton Inference Server and create multiple instance of the model.

https://docs.ultralytics.com/guides/triton-inference-server/

**Comment by webzhao9125** [comment]
> You can use Triton Inference Server and create multiple instance of the model using `config.pbtxt`
> 
> https://docs.ultralytics.com/guides/triton-inference-server/

It seems like Triton Inference Server needs to connect to Nvidia's servers for inference, but I want to implement the parallelism on the local GPU. Is there any other solution for this?

**Comment by Y-T-G** [comment]
Triton Inference Server can run locally. The tutorial is showing how to run it locally too.
