### ISSUE TITLE
Even if I add metrics.box.map75, I still don't get the value of AP75. Now I am training coco data set. How can aps apm a appear in the evaluation

### ISSUE THREAD

**Issue by tangruinenu** [ultralytics/ultralytics#1571]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Even if I add metrics.box.map75, I still don't get the value of AP75. Now I am training coco data set. How can aps apm a appear in the evaluation。

>

**Comment by pderrenger** [comment]
@tangruinenu hi there! 😊

To display the AP75 metric in the evaluation, you can use `-verbose` flag that will show AP for all IoU thresholds (AP50, AP75, and AP90). This will allow you to see the values for APs, APm, and APl in the evaluation results.

You can find more details on the evaluation process in the [YOLOv8 Val Mode documentation](https://docs.ultralytics.com/modes/val).

Feel free to reach out if you have any more questions or need further assistance!
