### ISSUE TITLE
YOLO v8n GPU consumption with two running model inference on 1080p camera feed 

### ISSUE THREAD

**Issue by sajedulalamSajid** [ultralytics/ultralytics#15714]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How much YOLO v8n GPU VRAM will be consumed with two running model inference on 1080p camera feed. on each inference two YOLO model will be running. I will run this on rtx 3060ti and rtx 3080ti. And what will be the maximum number of inference I will be able to run on each one of these GPUs where each inference will use two models at least?

**Comment by sajedulalamSajid** [comment]
Thank you so much for your prompt reply. I will look on to it.

**Comment by glenn-jocher** [comment]
@sajedulalamSajid you're welcome! If you have any further questions or need additional assistance, feel free to ask.
