### ISSUE TITLE
Multiple points in SAM?

### ISSUE THREAD

**Issue by chuang091** [ultralytics/ultralytics#15716]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi Ultralytics!
It seems that the SAM now cannot accept points prompt that more than one, as the original meta sam can do so.
Personally, I struggled with the points prompt for a long time until I change to the libary of meta's.
Now I think I have time to help these enhencements and PR.
```python
from ultralytics import SAM

# Load a model
model = SAM("sam_b.pt")

# Segment with bounding box prompt
model("ultralytics/assets/zidane.jpg", bboxes=[439, 437, 524, 709])

# Segment with points prompt
model("ultralytics/assets/zidane.jpg", points=[900, 370], labels=[1])
```
change to
```python
from ultralytics import SAM

# Load a model
model = SAM("sam_b.pt")

# Segment with bounding box prompt
model("ultralytics/assets/zidane.jpg", bboxes=[439, 437, 524, 709])

# Segment with points prompt
model("ultralytics/assets/zidane.jpg", points=[[900, 370],[100,200],[450,400]], labels=[1,0,1])
```
Ref: [Ultralytics Doc](https://docs.ultralytics.com/models/sam/#how-can-i-use-the-segment-anything-model-sam-for-image-segmentation)
Expect behavior:
<img width="359" alt="image" src="https://github.com/user-attachments/assets/8a1fa01f-c150-41d2-b2d0-a050591856c1">

### Use case

People can use the SAM more easily and have more moethod to get the mask.

### Additional

Yes I'd like to help by submitting a PR!
But I am not sure if these enhencements were done or I am loss with the doc.
Feel free to tell me the details of it.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@chuang091 thank you for your interest in contributing! The current implementation of SAM does support multiple points prompts. If you encounter any issues, please ensure you are using the latest version of the package. We welcome your PR to enhance the documentation or functionality further. Feel free to submit your enhancements, and we'll review them promptly. For more details, you can refer to our [documentation](https://docs.ultralytics.com/models/sam/).

**Comment by laogonggong847** [comment]
Hello @glenn-jocher :

Am I doing this correctly and can I export SAM2 from YOLO V8 to onnx format?
![img](https://github.com/user-attachments/assets/b7fa145a-cc43-4c31-aa12-c6539a0d827e)

**Comment by glenn-jocher** [comment]
Hello @laogonggong847,

Yes, you can export SAM2 from YOLOv8 to ONNX format. Use the following command:

```bash
yolo export model=sam2.pt format=onnx
```

If you encounter any issues, please ensure you are using the latest version of the package.

**Comment by laogonggong847** [comment]
Hello @glenn-jocher :
I'm sorry to ask for your help again.

I have pulled the latest code from Ultralytics and ```pip install -U ultralytics```
![d5d7d2c533f05804ac0138e3fc16c7c5](https://github.com/user-attachments/assets/5ac4424d-848b-40dc-8bf6-e193c0ce193f)



But when I execute the code shown in the image above, I get the following error:
```
Traceback (most recent call last):
  File "/Users/cc/Downloads/ultralytics-main/MyExport.py", line 6, in <module>
    model.export(format="onnx", imgsz=640)
  File "/Users/cc/Downloads/ultralytics-main/ultralytics/engine/model.py", line 737, in export
    "imgsz": self.model.args["imgsz"],
  File "/opt/anaconda3/envs/cc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'SAM2Model' object has no attribute 'args'
```

If I run your command line below I get the following error:
```
(Env) cc@cc-2 ultralytics-main % yolo export model=sam2_t.pt format=onnx
Traceback (most recent call last):
  File "/opt/anaconda3/envs/cc/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/anaconda3/envs/cc/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 797, in entrypoint
    from ultralytics import SAM2
ImportError: cannot import name 'SAM2' from 'ultralytics' (/opt/anaconda3/envs/cc/lib/python3.10/site-packages/ultralytics/__init__.py)
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit

```

**Comment by glenn-jocher** [comment]
Hello @laogonggong847,

It looks like there might be an issue with the SAM2 model export functionality. Please ensure you have the latest version of the package installed. If the issue persists, it may be a bug. You can report it on the GitHub issues page for further assistance. Thank you for your understanding.
