### ISSUE TITLE
yolo mode=export model=yolov8n.yaml format=onnx how to export half format onnx

### ISSUE THREAD

**Issue by zhu709654396** [ultralytics/ultralytics#1572]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

use command 'yolo mode=export model=yolov8n.yaml format=onnx' how to export half format onnx file

**Comment by glenn-jocher** [comment]
`yolo export half` 

See https://docs.ultralytics.com/modes/export

**Comment by leemengwei** [comment]
Neither can half the model, cli yolo command nor python script
python script:
success = model.export(format="onnx", half=True)  
![image](https://github.com/ultralytics/ultralytics/assets/17986725/a25c1083-5fe9-4fee-b2b6-a4ea9f260c8e)

cli command:
yolo export model=yolov8n.pt format=onnx half
Ultralytics YOLOv8.0.106 🚀 Python-3.9.2 torch-1.8.1+cu102 CPU
WARNING ⚠️ half=True only compatible with GPU export, i.e. use device=0
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients

PyTorch: starting from yolov8n.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

ONNX: starting export with onnx 1.12.0 opset 12...
ONNX: export success ✅ 1.8s, saved as yolov8n.onnx (12.2 MB)

Export complete (2.2s)
Results saved to /home/lmw/leemengwei/ultralytics
Predict:         yolo predict task=detect model=yolov8n.onnx imgsz=640 
Validate:        yolo val task=detect model=yolov8n.onnx imgsz=640 data=coco.yaml 
Visualize:       https://netron.app
![image](https://github.com/ultralytics/ultralytics/assets/17986725/290e52fe-a5bb-42ac-9f4f-0e1fac7c0bcd)

**Comment by glenn-jocher** [comment]
@leemengwei thank you for bringing this issue to our attention. Regarding exporting the model in half-precision format using the `yolo export` command or Python script, it's important to note that this option is only compatible with GPU export, not CPU. As you are likely exporting using your CPU, the `half=True` option will not work and will result in an error.

If possible, I recommend giving a GPU a try or contacting your cloud service provider to see if they offer one with your machine. If that's not possible, you may have to resort to the default full-precision model format instead.

Thank you for using YOLOv8!

**Comment by leemengwei** [comment]
Hmm something's wrong?
![image](https://github.com/ultralytics/ultralytics/assets/17986725/2ce0b24c-4a67-4548-ad34-3cc407a66074)

**Comment by glenn-jocher** [comment]
Hi @leemengwei, thank you for posting the issue. The error message suggests that the predict command is unable to find a valid model file. In order for `yolo predict` command to work, you need to provide it with the correct path to your model file. Please double-check that:

1. You have correctly specified the location of the model file.

2. The name of the model file you've provided matches the actual name of your saved YOLOv8 model file. 

If you continue to experience issues, please provide more information in the issue such as the file structure of your project, and the specific command you are using to run the predict command. Thank you for using YOLOv8!

**Comment by leemengwei** [comment]
@glenn-jocher No. I'm not encountering any error. I just can't get half precision fp16 onnx model by yolo export command or py convert script. I've double check my gpu driver, cuda, onnxruntime(gpu) and command. But the ONNX model I got is still float32 mode

**Comment by glenn-jocher** [comment]
@leemengwei hi there! If you are having trouble exporting your YOLOv8 model in half precision (FP16) format using the `yolo export` command or the Python script, please note that this option only works with GPU export and is not compatible with CPU export. Based on the information you provided, it seems like you may be using a CPU instead of a GPU to export the model, which is why you are not seeing half precision output.

If you have access to a GPU, I recommend trying the `yolo export` command again with the `device` argument set to the GPU you want to use. Additionally, you can try the Python script with a CUDA-enabled PyTorch installation to ensure that the model is exported in half precision format.

Thank you for using YOLOv8!

**Comment by leemengwei** [comment]
According to  https://docs.ultralytics.com/usage/cfg/#export, I don't see arguments 'device' is avalibale.
Meanwhile I'm sure GPU is accessable and I tried Python script with CUDA-enabled PyTorch, but the model exported is still not half precision.
Can you share your scrennshot of output of `yolo export model=yolov8n.pt format=onnx half`
@glenn-jocher

**Comment by glenn-jocher** [comment]
@leemengwei hi there! I apologize for any confusion regarding the `device` argument in the `yolo export` command. Upon further inspection, it appears that the `device` argument is not listed in the documentation for the command. However, if you have access to a GPU and are using the correct CUDA-enabled PyTorch installation, the `half=True` option should result in an FP16 model export by default.

If you are still not seeing an FP16 output, it's possible that the model architecture or model weights are not supporting half-precision export. One way to verify this is to check the summary of your model using the `--info` option in the `yolo export` command and verify that all layers and parameters support FP16.

Regarding your request for a screenshot, I'm afraid I cannot provide one at this time. However, I recommend double-checking your command arguments and ensuring that your PyTorch installation has the correct CUDA support.

Thank you for using YOLOv8!

**Comment by elb3k** [comment]
is there a way to export it with fp16 without GPU?

**Comment by glenn-jocher** [comment]
@elb3k exporting to FP16 without a GPU is not supported, as half-precision operations require GPU capabilities.
