### ISSUE TITLE
Help understand the function ap_per_class in utils/metrics.py

### ISSUE THREAD

**Issue by melinnediniz** [ultralytics/ultralytics#15729]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I have a question about the source code of YOLO, specifically about how the metrics for object detection. 

I'm really sorry if it's a dumb question. 

But I want to know how is the shape of ``tp``, ``conf`` and ``pred_cls`` defined in the ``ap_per_class`` in ``ultralytics/utils/metrics.py``?

 I know it changes based on the number of images, but why is always a large number? It is all the predictions without Non Max Supression?

**Comment by glenn-jocher** [comment]
The `tp`, `conf`, and `pred_cls` arrays in the `ap_per_class` function represent true positives, confidence scores, and predicted classes, respectively. Their shapes depend on the number of detections across all images. These arrays include all predictions, both before and after Non-Maximum Suppression (NMS). For more detailed information, you can refer to the [Ultralytics documentation on metrics](https://docs.ultralytics.com/reference/utils/metrics/).

**Comment by melinnediniz** [comment]
So, debugging the source code, in 33 images, it generated a ``tp``, ``conf`` and ``pred_cls`` with shape (1002,n). The 1002 predictions are all the predictions before Non-Maximum Suppression(NMS)?

So, when calculating the metrics in the validation mode, it considers all predictions, including the ones before Non-Maximum Suppression?

**Comment by glenn-jocher** [comment]
@melinnediniz the shapes of `tp`, `conf`, and `pred_cls` arrays include all predictions after Non-Maximum Suppression (NMS). The metrics calculation in validation mode only considers predictions that pass through NMS. If you have further questions, please refer to the [Ultralytics documentation on metrics](https://docs.ultralytics.com/reference/utils/metrics/).
