### ISSUE TITLE
Support for Switching CLIP Models (e.g., ViT-G/14) in YOLO-World Inference

### ISSUE THREAD

**Issue by WangQvQ** [ultralytics/ultralytics#15723]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

When using YOLO-world for inference, can I switch to other versions of the CLIP model, such as ViT-G/14?

![image](https://github.com/user-attachments/assets/df766323-f9a8-484c-86c8-a51ced1b9f60)

**Comment by glenn-jocher** [comment]
@WangQvQ hello,

Currently, YOLO-World does not support switching to other versions of the CLIP model, such as ViT-G/14, for inference. For updates and potential future support, please keep an eye on the repository.

**Comment by WangQvQ** [comment]
Thank you very much for your answer.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions, feel free to ask.
