### ISSUE TITLE
.track detecting way less objects than .predict

### ISSUE THREAD

**Issue by charlielito** [ultralytics/ultralytics#15738]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

Using the .predict and .track on the same input result in different # of objects detected, returning the .track much less objects

.predict
![predict_plot](https://github.com/user-attachments/assets/96460bfa-e006-423c-865b-35a7288410e3)

.track
![track_plot](https://github.com/user-attachments/assets/aa5d5133-77c8-40f1-a607-bf9ed44f879f)

### Environment

Ultralytics YOLOv8.1.47 🚀 Python-3.10.12 torch-1.13.0+cu117 CUDA:0 (NVIDIA GeForce RTX 3070 Laptop GPU, 7967MiB)
Setup complete ✅ (8 CPUs, 15.3 GB RAM, 628.1/777.4 GB disk)

OS                  Linux-6.8.0-76060800daily20240311-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 15.31 GB
CPU                 11th Gen Intel Core(TM) i7-11370H 3.30GHz
CUDA                11.7

matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 1.13.0>=1.8.0
torchvision         ✅ 0.14.0>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Minimal Reproducible Example

Test image:
![frame](https://github.com/user-attachments/assets/5c967ed5-315e-4b48-98a2-1fd12796c638)

Code:
```python
from ultralytics import YOLO

image_path = "image.jpg"
model = YOLO(model_path)

predict_result = model.predict(image_path,show=True,conf=0.1)[0]
print(f"# objects found with .predict: {len(predict_result)}")
result = model.track(image_path,show=True,conf=0.1)[0]
print(f"# objects found with .track: {len(result)}")
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by charlielito** [comment]
Just found that it was due to the confidences defined here: https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/trackers/botsort.yaml
By tunning the `new_track_thresh` you can get more detections

**Comment by glenn-jocher** [comment]
@charlielito thank you for sharing your findings. Adjusting the `new_track_thresh` in the `botsort.yaml` configuration is indeed a valid approach to increase the number of detections. If you have any further questions or need additional assistance, feel free to ask.

**Comment by BlackiePiggy** [comment]
> Just found that it was due to the confidences defined here: https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/trackers/botsort.yaml
> By tunning the `new_track_thresh` you can get more detections

hi Charlie, I encountered the same problem.

I tried tune the new_track_thresh. So should the detected items become more when I tune it up? I tried tune it to 0.9, but it still cannot have the same detect result as the "predict" output. I also tried tune it down, still not working.

How exactly did you adjust this parameter? if you could help me, I would be grateful.

**Comment by Y-T-G** [comment]
@BlackiePiggy You will have to reduce it. Try 0.25. And pass the modified `yaml` as `tracker=modified.yaml` in `model.track()`
