### ISSUE TITLE
How are false negatives counted in YOLOv8?

### ISSUE THREAD

**Issue by melinnediniz** [ultralytics/ultralytics#15730]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello again, I have another question. This time, about how is the confusion matrix calculated. 

## Example:
If I have an image with a ground truth class B and my model predicted this ground truth class B as A, it is a false positive for A. 

But does YOLO also counts it as a false negative for B?

**Comment by Y-T-G** [comment]
The code for the confusion matrix is here: 
https://github.com/ultralytics/ultralytics/blob/98a39f594cb98e9a761503c36df300e13701df6e/ultralytics/utils/metrics.py#L362

It doesn't seem like it would do that. It would only count it as false positive.

It would count as both FP and FN only when the detected box didn't match any ground truth box based on IoU and the ground truth box didn't match any other detected boxes bases on IoU.
