### ISSUE TITLE
I selected yolov8s model for training, why did I download yolov8n.pt before the training started

### ISSUE THREAD

**Issue by tangruinenu** [ultralytics/ultralytics#1573]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I selected yolov8s model for training, why did I download yolov8n.pt before the training started

### Additional

<img width="1190" alt="截屏2023-03-23 上午10 45 50" src="https://user-images.githubusercontent.com/100890412/227087112-dac9a527-e5e8-477e-91bb-19d853442e66.png">

**Comment by JustasBart** [comment]
@tangruinenu I think this might be a duplicate of what I saw yesterday with [1570](https://github.com/ultralytics/ultralytics/issues/1570). I think there is something going on with this...

**Comment by tangruinenu** [comment]
> @tangruinenu I think this might be a duplicate of what I saw yesterday with [1570](https://github.com/ultralytics/ultralytics/issues/1570). I think there is something going on with this...

However, this does not seem to affect training. Have you used yolov8? Why can't the weight given in github reach 44.9 on cocoval

**Comment by JustasBart** [comment]
@tangruinenu I'm not sure about that one...

**Comment by tangruinenu** [comment]
> @tangruinenu I'm not sure about that one...

Thank you. This thing still needs to be updated. I've only been working on it for a day and I've had several problems.
