### ISSUE TITLE
onnx infer result error

### ISSUE THREAD

**Issue by zhu709654396** [ultralytics/ultralytics#1575]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

code :
  import onnxruntime
import cv2
import numpy as np
model='./best.onnx'
session = onnxruntime.InferenceSession(model, None,providers=[ 'CPUExecutionProvider'])
# print(len(session.get_outputs()))
# print(len(session.get_inputs()))
output_name = session.get_outputs()[0].name
input_imgs = session.get_inputs()[0].name
IMG_PATH = '../yolov7/bus.jpg'
img = cv2.imread(IMG_PATH)
img = cv2.resize(img, (640, 640))
img = img[:,:,::-1].transpose((2,0,1))
img = img/255
prediction = session.run([output_name], {input_imgs: img[None].astype(np.float16)})[0]
print(prediction)
xc = prediction[:,4:16,prediction[:, 4:16, :].argmax(1)[0]] > 0.25
ind=xc[xc==True]
print(ind)

result is wrong,cls number all is 0

**Comment by glenn-jocher** [comment]
@zhu709654396 

```
yolo export model=yolov8n.pt format=onnx
yolo predict model=yolov8n.onnx
```
