### ISSUE TITLE
Failed while searching for ".npy" file in train

### ISSUE THREAD

**Issue by alem-memic-mathforml** [ultralytics/ultralytics#15768]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

After 47 epochs of training YOLOv8 on Vertex AI everything suddenly started to train again, from scratch. So, I looked in logs and realized that there was that error: f"OSError: [Errno 107] Transport endpoint is not connected: '/gcs/{bucket_name}/data/images/train/{name}.npy'". 

I know that there was already similar issue here, but that was related to Google Drive mounting, while here I used Vertex AI, so I thought how can this happen. Then I realized how ".npy" file is the problem. For some reason, it failed because it couldn't find that ".npy" file. I really don't have any npy files in my dataset at all. They are all jpg images.

Why would it fail because of that? I checked again that train part of the bucket and searched for that image name. I realized that there is one, but only jpg. No npy files are present. So, why does it search for npy file in the first place?

### Environment

I didn't specify version of ultralytics, so it is probably the latest one. 

### Minimal Reproducible Example

I am not legally authorized to share my code.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
The `.npy` files are created when disk caching is enabled `cache="disk"`.

**Comment by alem-memic-mathforml** [comment]
results = model.train(data=f'/gcs/{bucket_name}/data.yaml',
                          epochs=100,
                          imgsz=1024,
                          batch=16,
                          project=output_dir,
                          device=[0,1,2,3,4,5,6,7],#8,9,10,11,12,13,14,15],
                          cache=False)
That is how it looks in my script...

**Comment by Y-T-G** [comment]
Do you have full traceback of the error?

**Comment by alem-memic-mathforml** [comment]
![logs](https://github.com/user-attachments/assets/2489cb86-0b9b-4ad3-80b5-f155fb3c78f1)

**Comment by alem-memic-mathforml** [comment]
That was exactly before that error... As I can see, it goes to part "if fn.exists(): # load npy", but I don't have any npy files in my dataset...

**Comment by Y-T-G** [comment]
I don't think it failed due to not having `.npy`. But it failed because the `exists()` check failed probably due to some sort of disk mounting error. The code was checking whether `.npy` file existed, but it couldn't check it correctly because the disk or the path became inaccessible.

**Comment by Y-T-G** [comment]
The type of exception that was raised is `OSError` which is different from `FileNotFoundError`. It seems like an issue caused by Vertex AI.

**Comment by alem-memic-mathforml** [comment]
But why did he try to find npy image in the first place. Imagine you have "a.jpg" image in your dataset and then everything fails because he couldn't find "a.npy". It just doesn't make any sense.

**Comment by Y-T-G** [comment]
Because that's how you would check whether the `.npy` file exists. The `exists()` function tries to check whether that file exists.

It didn't fail because of some ultralytics related issue. It was an issue with Vertex AI and their disk. If the disk suddenly becomes inaccessible, then it would have failed even if the `.npy` check was not there because it won't be able to access the `.jpg` file either for the same reason. So it would have failed either way.

**Comment by alem-memic-mathforml** [comment]
I understand...Makes sense...Thank you very much

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to ask.
