### ISSUE TITLE
Referring Expression Comprehension(REC) in yolo-world ?

### ISSUE THREAD

**Issue by wuji3** [ultralytics/ultralytics#15780]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In yolo-world paper and codes in Ultralytics YOLO, I do not find REC ability of model. 
For example, 
Input-prompt: "a boy is flying a kite"
Input-image: <image> containing boy and kite

output: a bbox with boy and a bbox with kite.

I want to check whether my understanding is right. 
By the way, GroundingDINO supports this function.

Looking forward to your reply.

**Comment by glenn-jocher** [comment]
@wuji3 thank you for your question. You are correct; the current YOLO-World implementation does not support Referring Expression Comprehension (REC). For REC capabilities, you might want to explore models like GroundingDINO. If you have further questions or need assistance with other features, feel free to ask.
