### ISSUE TITLE
Unknown problem with ncnn yolo

### ISSUE THREAD

**Issue by Rockntt** [ultralytics/ultralytics#15787]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

```Loading nano32_ncnn_model for NCNN inference...
Traceback (most recent call last):
  File "/media/kloch/A86B-5F74/main.py", line 138, in <module>
    results = model.predict(frame, verbose=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kloch/miniconda3/envs/cv_venv/lib/python3.11/site-packages/ultralytics/engine/model.py", line 557, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/home/kloch/miniconda3/envs/cv_venv/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 303, in setup_model
    self.model = AutoBackend(
                 ^^^^^^^^^^^^
  File "/home/kloch/.local/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kloch/miniconda3/envs/cv_venv/lib/python3.11/site-packages/ultralytics/nn/autobackend.py", line 384, in __init__
    w = next(w.glob("*.param"))  # get *.param file from *_ncnn_model dir
        ^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
```

Other NCNN model works fine and was exported the same way.

### Environment

Ultralytics YOLOv8.2.78 🚀 Python-3.11.9 torch-2.4.0 CPU (Cortex-A76)
Setup complete ✅ (4 CPUs, 7.9 GB RAM, 9.8/28.0 GB disk)

OS                  Linux-6.6.31+rpt-rpi-2712-aarch64-with-glibc2.36
Environment         Linux
Python              3.11.9
Install             pip
RAM                 7.86 GB
CPU                 Cortex-A76
CUDA                None

numpy               ✅ 1.23.5<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.4.0>=1.8.0
torchvision         ✅ 0.19.0>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

```python
model = YOLO("nano32_ncnn_model")
model.predict(frame, verbose=False)
```

### Additional

My deadline is burning and i might let my competition team down, pls help me asap!!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
Seems like a path error. Try using full path to the model.

**Comment by Rockntt** [comment]
> Seems like a path error. Try using full path to the model.

yeah it was
making really dumb mistakes at midnight...
thanks for the patience

**Comment by glenn-jocher** [comment]
@Rockntt glad to hear that resolved it! If you encounter any more issues, feel free to reach out.
