### ISSUE TITLE
prediction_labelling_problem

### ISSUE THREAD

**Issue by ilhansevval** [ultralytics/ultralytics#1582]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am using segmentation task for yolov8. In the prediction part, I'm reloading my model and I want to predict as a single image.

When i visualize it, I see two prediction for one class.

Let's think that one prediction is bus, one prediction is car and the actual class is car.

Car prediction result is 0.34, and bus prediction result is 0.78. When i give a threshold, such as confidence, iou, the actual class prediction is disappear. Because this prediction result is so low.

I want to keep in actual class prediction even the result is so low, and I want to disappear of  wrong prediction.

Is there a solution, or an argument for this problem in Yolov8 ?

**Comment by aurelm95** [comment]
I guess your model just needs more trainning

**Comment by ilhansevval** [comment]
In the dataset, the number of the images is low. So, even the more training won't be enough. I want keep the actual prediction result after training. This is the problem

**Comment by pderrenger** [comment]
@ilhansevval got it! 🤔 To retain the actual class prediction while filtering out the wrong predictions, you can adjust the confidence threshold for visualization only, without affecting the actual predictions. This can be achieved by visualizing the predictions with a lower threshold for visualization purposes, while keeping the higher threshold for filtering out unwanted predictions during inference. This way, you can maintain the actual class prediction and visually inspect all predictions.
