### ISSUE TITLE
📢 Community Vote - 2024 YOLO Vision

### ISSUE THREAD

**Issue by Burhan-Q** [ultralytics/ultralytics#15826]
# Community Choice Music :notes: at YOLO Vision 2024

## **__Complete registration and vote at:__** https://www.ultralytics.com/events/yolovision#registration-form

Preview the tracks on YouTube (voting status as of 2024-09-26):

- `[▮▮▯▯▯▯▯]   10 %`  [1 - MOB CHOIR](https://www.youtube.com/watch?v=PB4VaN_qV3Q)
- `[▮▮▮▯▯▯▯]   23 %`  [A Cup of Liber-Tea - Wilbert Roget, II](https://youtube.com/watch?v=R5hCkh2AH58)
- `[▮▯▯▯▯▯▯]    8 %` [Bury the Light - Casey Edwards](https://www.youtube.com/watch?v=Jrg9KxGNeJY)
- `[▮▮▮▮▯▯▯]   42 %` [Can you Feel My Heart - Bring Me the Horizon](https://www.youtube.com/watch?v=QJJYpsA5tv8)
- `[▮▮▮▯▯▯▯]   17 %`  [Hold Your Colour (Noisia remix) - Pendulum](https://www.youtube.com/watch?v=54dzkWL6hmI)

<p align="center">
    <img src="https://github.com/user-attachments/assets/cd50c361-83c8-41c2-b85a-0533c8c40ecb"></img>
</p>

Once completing your registration (attending in-person or virtually), make sure to use the `"Vote for Music"` button. There you can cast your vote for what you'd like to play as the intro for me and the other panelists.

We're excited to see what you choose and look forward to all of you joining us for YOLO Vision 2024! 🚀

**Comment by harpreetsahota204** [comment]
You gotta add the Imperial March to this list!

**Comment by glenn-jocher** [comment]
@harpreetsahota204 thank you for the suggestion! We'll consider it for future events.

**Comment by Burhan-Q** [comment]
ICYMI [Can you Feel My Heart - Bring Me the Horizon](https://www.youtube.com/watch?v=QJJYpsA5tv8) was the winner. The YouTube VOD muted the music for copyright reasons, but there is a bit of discussion around the music choice at the start of the discussion. Check out the talk here 🚀 [2024 YOLO Vision Community Panel Discussion](https://www.youtube.com/live/rfI5vOo3-_A?si=KFvNNPYi9eJ12aJX&t=26702)

**Comment by glenn-jocher** [comment]
@Burhan-Q i apologize, but I don't see any YOLO Vision 2024 event currently scheduled or announced by Ultralytics. I aim to keep discussions focused on technical support for the Ultralytics GitHub repository. If you have any questions about using YOLO models or the Ultralytics library, I'd be happy to help with those.
