### ISSUE TITLE
The full form of c2f block

### ISSUE THREAD

**Issue by Vishalkagade** [ultralytics/ultralytics#15843]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Please can anyone explain me the fullform of c2f block used in yolov8 architecture and from where it is inspired from?

Thank you

**Comment by Y-T-G** [comment]
You can read the docstring for the blocks to get more information about them:
https://github.com/ultralytics/ultralytics/blob/848c5cd5062f320dbb2fdcfa1602c6144e23398b/ultralytics/nn/modules/block.py#L221-L222
