### ISSUE TITLE
GPU Memory Consumption keeps Increasing while running YOLO for object tracking

### ISSUE THREAD

**Issue by klentabistado** [ultralytics/ultralytics#15849]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My GPU usage starts at less than a GB and gradually increases over time until it reaches the maximum GPU memory. What changes should be made to the code below with Ultralytics to keep the usage constant? Is there a memory leak in the sample code?

Here's the code:

model = YOLO('yolov8n-seg.pt').to('cuda')

    box_annotator = sv.MaskAnnotator()
    label_annotator = sv.LabelAnnotator()

    for result in model.track(source=0, show=True, stream=False, conf=0.6):
        frame = result.orig_img
        detections = sv.Detections.from_ultralytics(result)

        if result.boxes.id is not None:
            detections.tracker_id = result.boxes.id.cpu().numpy().astype(int)
        else:
            continue

        labels = [
            f"id: {tracker_id} {model.model.names[class_id]} {confidence:0.2f}"
            for class_id, confidence, tracker_id
            in zip(detections.class_id, detections.confidence, detections.tracker_id)
        ]

        frame = box_annotator.annotate(
            scene=frame,
            detections=detections)
        frame = label_annotator.annotate(
            scene=frame, detections=detections, labels=labels)

        cv2.imshow('realtime', frame)

**Comment by glenn-jocher** [comment]
@klentabistado it appears that the GPU memory consumption issue might be due to accumulating results in memory. Try adding `torch.cuda.empty_cache()` within your loop to clear unused memory. If the issue persists, please ensure you are using the latest version of the Ultralytics package.

**Comment by Y-T-G** [comment]
Try using `stream=True`.

**Comment by klentabistado** [comment]
> Try using `stream=True` and `show=False`.
> 
> https://docs.ultralytics.com/modes/predict/#__tabbed_1_2

thanks @Y-T-G , i also tried this configuration, including both having false:
stream=False and show=False
but to no success.

**Comment by Y-T-G** [comment]
You can try running with supervision.

Just use `cv2.imshow("frame", result.plot())` inside the loop.

**Comment by Y-T-G** [comment]
Or you can even remove that because if you use `show=True`, it should show the detections without `imshow`. So you can simply set `stream=True` and `show=True` and use `pass` inside the for loop to run the loop.
