### ISSUE TITLE
'solutions' module in YOLOv8

### ISSUE THREAD

**Issue by isura3147** [ultralytics/ultralytics#15859]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I saw there was a discussion talking about the 'solutions' module not being avalaible in the YOLOv8 public release. This discussion was closed in may. I want to know if there any updates. Is the solutions module available for the public yet or not. How can we check this ourselves ? 

thank you .

**Comment by isura3147** [comment]
Hey guys, after some research I found the solutions folder. If anyone has this issue you can find the folder here:
https://github.com/ultralytics/ultralytics/tree/main/ultralytics/solutions

**Comment by glenn-jocher** [comment]
The 'solutions' module is not currently available in the public release of YOLOv8. For the latest updates, please refer to the official Ultralytics GitHub repository.
