### ISSUE TITLE
Setting reg_max parameter during validation/inference.

### ISSUE THREAD

**Issue by gx-lighthaus** [ultralytics/ultralytics#15852]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is the ```reg_max``` parameter used in ```ultralytics/nn/modules/head.py```  during validation (```model.val```) and prediction ```model.predict```). I have changed ```reg_max=64``` for an image size of ```2048```. 

How can i change the ```reg_max``` parameter during inference? Thanks

**Comment by Y-T-G** [comment]
Did you train it with that `reg_max`?

**Comment by gx-lighthaus** [comment]
@Y-T-G  yeap, if I were to use model.val() and model.predict() would the same ```reg_max``` be used?

**Comment by Y-T-G** [comment]
It should use the same.

You can check by doing
`print(model.model.model[-1].reg_max)`

**Comment by Y-T-G** [comment]
Did you see any benefit of higher `reg_max`?

Can you mention your findings here:
https://github.com/ultralytics/ultralytics/issues/11634

**Comment by gx-lighthaus** [comment]
@Y-T-G Will do so promptly, thank you for the help!
