### ISSUE TITLE
The heatmaps.ipynb parameter is incorrect

### ISSUE THREAD

**Issue by dearMOMO** [ultralytics/ultralytics#15851]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

path: ultralytics/examples/heatmaps.ipynb

```
# Initialize heatmap object
heatmap_obj = solutions.Heatmap(
    colormap=cv2.COLORMAP_PARULA,
    view_img=True,
    shape="circle",
    classes_names=model.names,
)

```
The `classes_names` argument is incorrect. It should be `name`

![image](https://github.com/user-attachments/assets/7c9e382e-644f-4978-834d-8c3b5fc834f7)

### Environment

Ultralytics YOLOvmain
![image](https://github.com/user-attachments/assets/0bf8d29b-bc5d-48fa-a66c-a6bafde68170)

### Minimal Reproducible Example

path: ultralytics/examples/heatmaps.ipynb

```
# Initialize heatmap object
heatmap_obj = solutions.Heatmap(
    colormap=cv2.COLORMAP_PARULA,
    view_img=True,
    shape="circle",
    classes_names=model.names,
)

```
The `classes_names` argument is incorrect. It should be `name`

![image](https://github.com/user-attachments/assets/7c9e382e-644f-4978-834d-8c3b5fc834f7)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@dearMOMO thank you for pointing that out. You are correct; the argument should be `names` instead of `classes_names`. We appreciate your willingness to submit a PR to correct this.
