### ISSUE TITLE
Exporting engine int8 quantization model, setting dynamic=False, batch=1 does not take effect?

### ISSUE THREAD

**Issue by ZJDATY** [ultralytics/ultralytics#15856]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

yolo export model=yolov8n.pt format=engine imgsz=640,640 batch=1 int8=True dynamic=False

> **log**
```
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics YOLOv8.2.82 🚀 Python-3.8.16 torch-2.0.0 CUDA:0 (NVIDIA TITAN V, 12050MiB)
WARNING ⚠️ INT8 export requires a missing 'data' arg for calibration. Using default 'data=coco8.yaml'.
YOLOv8n summary (fused): 168 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs

PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

ONNX: starting export with onnx 1.16.1 opset 17...
================ Diagnostic Run torch.onnx.export version 2.0.0 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ONNX: export success ✅ 0.6s, saved as 'yolov8n.onnx' (12.1 MB)

TensorRT: starting export with TensorRT 8.6.0...
[08/28/2024-16:11:40] [TRT] [I] [MemUsageChange] Init CUDA: CPU +2, GPU +0, now: CPU 2447, GPU 619 (MiB)
[08/28/2024-16:11:44] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +430, GPU +72, now: CPU 2953, GPU 691 (MiB)
[08/28/2024-16:11:44] [TRT] [I] ----------------------------------------------------------------
[08/28/2024-16:11:44] [TRT] [I] Input filename:   yolov8n.onnx
[08/28/2024-16:11:44] [TRT] [I] ONNX IR version:  0.0.8
[08/28/2024-16:11:44] [TRT] [I] Opset version:    17
[08/28/2024-16:11:44] [TRT] [I] Producer name:    pytorch
[08/28/2024-16:11:44] [TRT] [I] Producer version: 2.0.0
[08/28/2024-16:11:44] [TRT] [I] Domain:           
[08/28/2024-16:11:44] [TRT] [I] Model version:    0
[08/28/2024-16:11:44] [TRT] [I] Doc string:       
[08/28/2024-16:11:44] [TRT] [I] ----------------------------------------------------------------
[08/28/2024-16:11:44] [TRT] [W] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
TensorRT: input "images" with shape(-1, 3, -1, -1) DataType.FLOAT
TensorRT: output "output0" with shape(-1, 84, -1) DataType.FLOAT
TensorRT: WARNING ⚠️ 'dynamic=True' model requires max batch size, i.e. 'batch=16'
TensorRT: building INT8 engine as yolov8n.engine
TensorRT: collecting INT8 calibration images from 'data=coco8.yaml'
Scanning /home/zhang/pythonworkspace/deeplabv3-plus-pytorch/datasets/coco8/label
TensorRT: WARNING ⚠️ >300 images recommended for INT8 calibration, found 4 images.
```

> I don't quite understand the TensorRT part in the log information. I have already set the static size and set 'dynamic=False'. The model is from the official YOLOV8n.

```
TensorRT: input "images" with shape(-1, 3, -1, -1) DataType.FLOAT
TensorRT: output "output0" with shape(-1, 84, -1) DataType.FLOAT
TensorRT: WARNING ⚠️ 'dynamic=True' model requires max batch size, i.e. 'batch=16'

```

### Environment

Ultralytics YOLOv8.2.82 🚀 Python-3.8.16 torch-2.0.0 CUDA:0 (NVIDIA TITAN V, 12050MiB)
Setup complete ✅ (8 CPUs, 31.3 GB RAM, 34.8/93.3 GB disk)

OS                  Linux-6.8.0-40-generic-x86_64-with-glibc2.17
Environment         Linux
Python              3.8.16
Install             git
RAM                 31.27 GB
CPU                 Intel Core(TM) i7-9700 3.00GHz
CUDA                11.7

numpy               ✅ 1.23.5<2.0.0,>=1.23.0
matplotlib          ✅ 3.4.3>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.28.1>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.0.0>=1.8.0
torchvision         ✅ 0.15.0>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

yolo export model=yolov8n.pt format=engine imgsz=640,640 batch=1 int8=True dynamic=False

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
`dynamic=True` is enforced for `int8` TensorRT exports:
https://github.com/ultralytics/ultralytics/blob/4fe046e2d59c0377fcc4ab01634a2e71aa02069b/ultralytics/engine/exporter.py#L208

@Burhan-Q Probably should have a warning.

**Comment by Burhan-Q** [comment]
@ZJDATY if you're curious why this is enabled you can review the following:
- https://github.com/ultralytics/ultralytics/pull/10165#pullrequestreview-2039720084
- https://github.com/ultralytics/ultralytics/pull/10423#issuecomment-2094758129
- https://github.com/ultralytics/ultralytics/pull/11788

I've added a logging message about enforcing `dynamic=True` for this condition in #15874 to at least provide notice about this behavior.

**Comment by ZJDATY** [comment]
> @ZJDATY if you're curious why this is enabled you can review the following:
> 
> * [`ultralytics 8.2.11` new TensorRT INT8 export feature #10165 (review)](https://github.com/ultralytics/ultralytics/pull/10165#pullrequestreview-2039720084)
> * [`ultralytics 8.2.9` OpenVINO INT8 fixes and tests #10423 (comment)](https://github.com/ultralytics/ultralytics/pull/10423#issuecomment-2094758129)
> * [Enforce `dynamic=True` for TensorRT and OpenVINO INT8 #11788](https://github.com/ultralytics/ultralytics/pull/11788)
> 
> I've added a logging message about enforcing `dynamic=True` for this condition in #15874 to at least provide notice about this behavior.

ok,thinks.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any further questions or need additional assistance, feel free to ask.

**Comment by Petros626** [comment]
@glenn-jocher which `batch` is recommended for exporting to `TensorRT FP16` and how to calculate the best `batch`? You used by default 8

**Comment by Y-T-G** [comment]
There's no recommended batch. You just set it based on your requirements. If you don't need dynamic batch, then you can ignore the warning. It will use max as 1.

**Comment by Petros626** [comment]
Is it recommended for performance to use `dynamic=True`? Otherwise I could do without dynamic and leave the batch at 1?

**Comment by Y-T-G** [comment]
If you don't need dynamic, you shouldn't use it

**Comment by Petros626** [comment]
Yes I think for validating an image series instead so several frame, it makes more sense.

**Comment by glenn-jocher** [comment]
@Petros626 for image series validation with YOLO11, you can use `model.val(batch=N)` where `N` is your desired batch size. The validation batch size is independent of export settings, but exported models will have a maximum inference batch size equal to their export `batch` value. See the [Predict Mode documentation](https://docs.ultralytics.com/modes/predict/) for batch processing details and [Configuration docs](https://docs.ultralytics.com/usage/cfg/) for batch size optimization guidance.

**Comment by Petros626** [comment]
The problem is that I choose N according to these two criteria:

Real-time applications: Smaller batch sizes (e.g. 1 or 2) to minimise latency.
Batch processing: Larger batch sizes (e.g. 8, 16, 32) to maximise throughput.

**Comment by glenn-jocher** [comment]
Your understanding is correct! For real-time applications, smaller batch sizes (1-2) optimize latency, while larger batches (8+) maximize throughput. The exported model's `batch` value sets the maximum allowed during inference, but you can use smaller batches as needed. For implementation details, see the TensorRT Export documentation and TensorRT Benchmarks showing performance characteristics at different batch sizes.
