### ISSUE TITLE
 Ram memory usage problems with track mode

### ISSUE THREAD

**Issue by walter2482** [ultralytics/ultralytics#1586]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Along with saying hello, I comment that I am tracking with my weights YOLOv8x.pt. The model was trained on a set of construction objects with an input resolution of 1280x1280, I am researching the production of construction machinery via CLI using the command:

I have tried to vary the resolution, the type of model to "m", the frame rate, the track video. The configuration via streaming on youtube works fine, but loading the video from the route is when the use of ram memory increases. I have also tried on A100 80 GB gpu.

The installation module method is pip install -U ultralytics.

The modules installed are these

Package                           Version
--------------------------------- --------------------

- absl-py                           1.4.0
- agate                             1.6.0
- agate-dbf                         0.2.0
- agate-excel                       0.2.3
- agate-sql                         0.5.2
- aiohttp                           3.8.3
- aiosignal                         1.3.1
- anyio                             3.6.2
- argon2-cffi                       21.3.0
- argon2-cffi-bindings              21.2.0
- asttokens                         2.2.1
- astunparse                        1.6.3
- async-timeout                     4.0.2
- attrs                             18.2.0
- awscli                            1.25.91
- Babel                             2.11.0
- backcall                          0.2.0
- beautifulsoup4                    4.11.1
- bleach                            6.0.0
- blis                              0.7.9
- boto3                             1.24.90
- botocore                          1.27.90
- cached-property                   1.5.2
- cachetools                        5.3.0
- catalogue                         2.0.8
- certifi                           2019.11.28
- cffi                              1.15.1
- chardet                           3.0.4
- charset-normalizer                2.1.1
- chex                              0.1.5
- click                             8.1.3
- click-completion                  0.5.2
- click-didyoumean                  0.3.0
- click-help-colors                 0.9.1
- cloudpickle                       2.2.0
- colorama                          0.4.3
- comm                              0.1.2
- confection                        0.0.4
- contourpy                         1.0.7
- csvkit                            1.0.2
- cycler                            0.11.0
- cymem                             2.0.7
- Cython                            0.29.32
- datasets                          2.4.0
- dbfread                           2.0.7
- dbus-python                       1.2.16
- debugpy                           1.6.6
- decorator                         5.1.1
- defusedxml                        0.7.1
- dill                              0.3.5.1
- dm-tree                           0.1.8
- docker-pycreds                    0.4.0
- docutils                          0.16
- entrypoints                       0.4
- et-xmlfile                        1.0.1
- etils                             1.0.0
- exceptiongroup                    1.1.0
- executing                         1.2.0
- fastjsonschema                    2.16.2
- filelock                          3.9.0
- flatbuffers                       1.12
- flax                              0.6.3
- fonttools                         4.38.0
- frozenlist                        1.3.3
- fsspec                            2023.1.0
- future                            0.18.2
- gast                              0.4.0
- gdown                             4.5.1
- gitdb                             4.0.10
- GitPython                         3.1.30
- google-auth                       2.16.0
- google-auth-oauthlib              0.4.6
- google-pasta                      0.2.0
- gql                               3.0.0a6
- gradient                          2.0.6
- gradient-utils                    0.5.0
- graphql-core                      3.1.7
- greenlet                          2.0.1
- grpcio                            1.51.1
- h5py                              3.8.0
- halo                              0.0.31
- huggingface-hub                   0.12.0
- idna                              2.8
- imageio                           2.25.0
- importlib-metadata                6.0.0
- importlib-resources               5.10.2
- iniconfig                         2.0.0
- ipykernel                         6.16.0
- ipython                           8.5.0
- ipython-genutils                  0.2.0
- ipywidgets                        8.0.2
- isodate                           0.6.0
- jax                               0.4.1
- jaxlib                            0.4.1+cuda11.cudnn82
- jdcal                             1.0
- jedi                              0.18.2
- Jinja2                            3.1.2
- jmespath                          1.0.1
- joblib                            1.2.0
- json5                             0.9.11
- jsonify                           0.5
- jsonschema                        4.17.3
- jupyter-client                    7.3.4
- jupyter-contrib-core              0.4.2
- jupyter-contrib-nbextensions      0.7.0
- jupyter_core                      5.1.5
- jupyter-highlight-selected-word   0.2.0
- jupyter-nbextensions-configurator 0.6.1
- jupyter-server                    1.23.5
- jupyter-server-mathjax            0.2.6
- jupyterlab                        3.4.6
- jupyterlab-git                    0.41.0
- jupyterlab-pygments               0.2.2
- jupyterlab_server                 2.19.0
- jupyterlab-snippets               0.4.1
- jupyterlab-widgets                3.0.5
- keras                             2.9.0
- Keras-Preprocessing               1.1.2
- kiwisolver                        1.4.4
- langcodes                         3.3.0
- lap                               0.4.0
- leather                           0.3.3
- libclang                          15.0.6.1
- log-symbols                       0.0.14
- lxml                              4.5.0
- Markdown                          3.4.1
- markdown-it-py                    2.1.0
- MarkupSafe                        2.1.2
- marshmallow                       2.21.0
- matplotlib                        3.6.1
- matplotlib-inline                 0.1.6
- mdurl                             0.1.2
- mistune                           2.0.4
- msgpack                           1.0.4
- multidict                         6.0.4
- multiprocess                      0.70.13
- murmurhash                        1.0.9
- nbclassic                         0.4.8
- nbclient                          0.7.2
- nbconvert                         7.2.9
- nbdime                            3.1.1
- nbformat                          5.7.3
- nest-asyncio                      1.5.6
- networkx                          3.0
- nltk                              3.7
- notebook                          6.5.2
- notebook_shim                     0.2.2
- numpy                             1.23.4
- oauthlib                          3.2.2
- opencv-python                     4.6.0.66
- openpyxl                          3.0.3
- opt-einsum                        3.3.0
- optax                             0.1.4
- orbax                             0.1.0
- packaging                         23.0
- pandas                            1.5.0
- pandocfilters                     1.5.0
- parsedatetime                     2.4
- parso                             0.8.3
- pathtools                         0.1.2
- pathy                             0.10.1
- pexpect                           4.8.0
- pickleshare                       0.7.5
- Pillow                            9.2.0
- pip                               22.3.1
- platformdirs                      2.6.2
- pluggy                            1.0.0
- preshed                           3.0.8
- progressbar2                      4.2.0
- prometheus-client                 0.9.0
- promise                           2.3
- prompt-toolkit                    3.0.36
- protobuf                          3.19.6
- psutil                            5.9.4
- ptyprocess                        0.7.0
- pure-eval                         0.2.2
- pyarrow                           10.0.1
- pyasn1                            0.4.8
- pyasn1-modules                    0.2.8
- pycparser                         2.21
- pydantic                          1.9.2
- Pygments                          2.14.0
- PyGObject                         3.36.0
- pymongo                           3.13.0
- pyparsing                         3.0.9
- pyrsistent                        0.19.3
- PySocks                           1.7.1
- pytest                            7.2.1
- python-apt                        2.0.1
- python-dateutil                   2.8.2
- python-distutils-extra            2.39
- python-slugify                    4.0.0
- python-utils                      3.4.5
- pytimeparse                       1.1.5
- pytz                              2022.7.1
- PyWavelets                        1.4.1
- PyYAML                            5.4.1
- pyzmq                             25.0.0
- regex                             2022.10.31
- requests                          2.28.2
- requests-oauthlib                 1.3.1
- requests-toolbelt                 0.10.1
- requests-unixsocket               0.2.0
- responses                         0.18.0
- rich                              13.2.0
- rsa                               4.7.2
- s3transfer                        0.6.0
- scikit-image                      0.19.3
- scikit-learn                      1.1.2
- scipy                             1.9.2
- seaborn                           0.12.0
- Send2Trash                        1.8.0
- sentence-transformers             2.2.2
- sentencepiece                     0.1.97
- sentry-sdk                        1.14.0
- setproctitle                      1.3.2
- setuptools                        66.1.1
- shellingham                       1.5.0.post1
- shortuuid                         1.0.11
- six                               1.14.0
- smart-open                        6.3.0
- smmap                             5.0.0
- sniffio                           1.3.0
- soupsieve                         2.3.2.post1
- spacy                             3.4.1
- spacy-legacy                      3.0.12
- spacy-loggers                     1.0.4
- spinners                          0.0.24
- SQLAlchemy                        1.4.41
- srsly                             2.4.5
- stack-data                        0.6.2
- tabulate                          0.9.0
- tensorboard                       2.9.1
- tensorboard-data-server           0.6.1
- tensorboard-plugin-wit            1.8.1
- tensorflow                        2.9.2
- tensorflow-estimator              2.9.0
- tensorflow-io-gcs-filesystem      0.30.0
- tensorstore                       0.1.30
- termcolor                         2.2.0
- terminado                         0.17.1
- terminaltables                    3.1.10
- thinc                             8.1.7
- thop                              0.1.1.post2209072238
- threadpoolctl                     3.1.0
- tifffile                          2023.1.23.1
- tinycss2                          1.2.1
- tokenizers                        0.12.1
- tomli                             2.0.1
- toolz                             0.12.0
- torch                             1.12.1+cu116
- torchaudio                        0.12.1+cu116
- torchvision                       0.13.1+cu116
- tornado                           6.1
- tqdm                              4.64.1
- traitlets                         5.8.1
- transformers                      4.21.3
- typer                             0.4.2
- typing_extensions                 4.4.0
- ultralytics                       8.0.55
- Unidecode                         1.1.1
- urllib3                           1.26.14
- wandb                             0.13.4
- wasabi                            0.10.1
- wcwidth                           0.2.6
- webencodings                      0.5.1
- websocket-client                  0.57.0
- Werkzeug                          2.2.2
- wheel                             0.35.1
- widgetsnbextension                4.0.5
- wrapt                             1.14.1
- xgboost                           1.6.2
- xlrd                              1.1.0
- xxhash                            3.2.0
- yarl                              1.8.2
- zipp                              3.11.0

![image](https://user-images.githubusercontent.com/93685420/227333062-f8bb3f14-93d9-490c-b5ac-50e69bd71aea.png)

### Environment

Python version: Python 3.9.16 (main, Dec  7 2022, 01:11:51) 
OS: Ubuntu 20.04.5 LTS (Focal Fossa)
Specifications: Ultralytics YOLOv8.0.55 🚀 Python-3.9.16 torch-1.12.1+cu116 CUDA:0 (NVIDIA RTX A6000, 48685MiB)
Setup complete ✅ (8 CPUs, 44.1 GB RAM, 131.8/246.0 GB disk)

### Minimal Reproducible Example

yolo track model=/notebooks/runs/detect/train19/weights/best.pt  tracker="botsort.yaml" source="/notebooks/vid4/CraneVistas TowerCrane TimeLapse Diary July 10th 2020 [Ambient Background Whitenoise Music Included.mp4" conf=0.25 iou=0.5 imgsz=1280 save_txt=True save=True save_conf=True half=True

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by walter2482** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.
> 
> ### YOLOv8 Component
> Other
> 
> ### Bug
> Along with saying hello, I comment that I am tracking with my weights YOLOv8x.pt. The model was trained on a set of construction objects with an input resolution of 1280x1280, I am researching the production of construction machinery via CLI using the command:
> 
> I have tried to vary the resolution, the type of model to "m", the frame rate, the track video. The configuration via streaming on youtube works fine, but loading the video from the route is when the use of ram memory increases. I have also tried on A100 80 GB gpu.
> 
> The installation module method is pip install -U ultralytics.
> 
> The modules installed are these
> 
> Package Version
> 
> * absl-py                           1.4.0
> * agate                             1.6.0
> * agate-dbf                         0.2.0
> * agate-excel                       0.2.3
> * agate-sql                         0.5.2
> * aiohttp                           3.8.3
> * aiosignal                         1.3.1
> * anyio                             3.6.2
> * argon2-cffi                       21.3.0
> * argon2-cffi-bindings              21.2.0
> * asttokens                         2.2.1
> * astunparse                        1.6.3
> * async-timeout                     4.0.2
> * attrs                             18.2.0
> * awscli                            1.25.91
> * Babel                             2.11.0
> * backcall                          0.2.0
> * beautifulsoup4                    4.11.1
> * bleach                            6.0.0
> * blis                              0.7.9
> * boto3                             1.24.90
> * botocore                          1.27.90
> * cached-property                   1.5.2
> * cachetools                        5.3.0
> * catalogue                         2.0.8
> * certifi                           2019.11.28
> * cffi                              1.15.1
> * chardet                           3.0.4
> * charset-normalizer                2.1.1
> * chex                              0.1.5
> * click                             8.1.3
> * click-completion                  0.5.2
> * click-didyoumean                  0.3.0
> * click-help-colors                 0.9.1
> * cloudpickle                       2.2.0
> * colorama                          0.4.3
> * comm                              0.1.2
> * confection                        0.0.4
> * contourpy                         1.0.7
> * csvkit                            1.0.2
> * cycler                            0.11.0
> * cymem                             2.0.7
> * Cython                            0.29.32
> * datasets                          2.4.0
> * dbfread                           2.0.7
> * dbus-python                       1.2.16
> * debugpy                           1.6.6
> * decorator                         5.1.1
> * defusedxml                        0.7.1
> * dill                              0.3.5.1
> * dm-tree                           0.1.8
> * docker-pycreds                    0.4.0
> * docutils                          0.16
> * entrypoints                       0.4
> * et-xmlfile                        1.0.1
> * etils                             1.0.0
> * exceptiongroup                    1.1.0
> * executing                         1.2.0
> * fastjsonschema                    2.16.2
> * filelock                          3.9.0
> * flatbuffers                       1.12
> * flax                              0.6.3
> * fonttools                         4.38.0
> * frozenlist                        1.3.3
> * fsspec                            2023.1.0
> * future                            0.18.2
> * gast                              0.4.0
> * gdown                             4.5.1
> * gitdb                             4.0.10
> * GitPython                         3.1.30
> * google-auth                       2.16.0
> * google-auth-oauthlib              0.4.6
> * google-pasta                      0.2.0
> * gql                               3.0.0a6
> * gradient                          2.0.6
> * gradient-utils                    0.5.0
> * graphql-core                      3.1.7
> * greenlet                          2.0.1
> * grpcio                            1.51.1
> * h5py                              3.8.0
> * halo                              0.0.31
> * huggingface-hub                   0.12.0
> * idna                              2.8
> * imageio                           2.25.0
> * importlib-metadata                6.0.0
> * importlib-resources               5.10.2
> * iniconfig                         2.0.0
> * ipykernel                         6.16.0
> * ipython                           8.5.0
> * ipython-genutils                  0.2.0
> * ipywidgets                        8.0.2
> * isodate                           0.6.0
> * jax                               0.4.1
> * jaxlib                            0.4.1+cuda11.cudnn82
> * jdcal                             1.0
> * jedi                              0.18.2
> * Jinja2                            3.1.2
> * jmespath                          1.0.1
> * joblib                            1.2.0
> * json5                             0.9.11
> * jsonify                           0.5
> * jsonschema                        4.17.3
> * jupyter-client                    7.3.4
> * jupyter-contrib-core              0.4.2
> * jupyter-contrib-nbextensions      0.7.0
> * jupyter_core                      5.1.5
> * jupyter-highlight-selected-word   0.2.0
> * jupyter-nbextensions-configurator 0.6.1
> * jupyter-server                    1.23.5
> * jupyter-server-mathjax            0.2.6
> * jupyterlab                        3.4.6
> * jupyterlab-git                    0.41.0
> * jupyterlab-pygments               0.2.2
> * jupyterlab_server                 2.19.0
> * jupyterlab-snippets               0.4.1
> * jupyterlab-widgets                3.0.5
> * keras                             2.9.0
> * Keras-Preprocessing               1.1.2
> * kiwisolver                        1.4.4
> * langcodes                         3.3.0
> * lap                               0.4.0
> * leather                           0.3.3
> * libclang                          15.0.6.1
> * log-symbols                       0.0.14
> * lxml                              4.5.0
> * Markdown                          3.4.1
> * markdown-it-py                    2.1.0
> * MarkupSafe                        2.1.2
> * marshmallow                       2.21.0
> * matplotlib                        3.6.1
> * matplotlib-inline                 0.1.6
> * mdurl                             0.1.2
> * mistune                           2.0.4
> * msgpack                           1.0.4
> * multidict                         6.0.4
> * multiprocess                      0.70.13
> * murmurhash                        1.0.9
> * nbclassic                         0.4.8
> * nbclient                          0.7.2
> * nbconvert                         7.2.9
> * nbdime                            3.1.1
> * nbformat                          5.7.3
> * nest-asyncio                      1.5.6
> * networkx                          3.0
> * nltk                              3.7
> * notebook                          6.5.2
> * notebook_shim                     0.2.2
> * numpy                             1.23.4
> * oauthlib                          3.2.2
> * opencv-python                     4.6.0.66
> * openpyxl                          3.0.3
> * opt-einsum                        3.3.0
> * optax                             0.1.4
> * orbax                             0.1.0
> * packaging                         23.0
> * pandas                            1.5.0
> * pandocfilters                     1.5.0
> * parsedatetime                     2.4
> * parso                             0.8.3
> * pathtools                         0.1.2
> * pathy                             0.10.1
> * pexpect                           4.8.0
> * pickleshare                       0.7.5
> * Pillow                            9.2.0
> * pip                               22.3.1
> * platformdirs                      2.6.2
> * pluggy                            1.0.0
> * preshed                           3.0.8
> * progressbar2                      4.2.0
> * prometheus-client                 0.9.0
> * promise                           2.3
> * prompt-toolkit                    3.0.36
> * protobuf                          3.19.6
> * psutil                            5.9.4
> * ptyprocess                        0.7.0
> * pure-eval                         0.2.2
> * pyarrow                           10.0.1
> * pyasn1                            0.4.8
> * pyasn1-modules                    0.2.8
> * pycparser                         2.21
> * pydantic                          1.9.2
> * Pygments                          2.14.0
> * PyGObject                         3.36.0
> * pymongo                           3.13.0
> * pyparsing                         3.0.9
> * pyrsistent                        0.19.3
> * PySocks                           1.7.1
> * pytest                            7.2.1
> * python-apt                        2.0.1
> * python-dateutil                   2.8.2
> * python-distutils-extra            2.39
> * python-slugify                    4.0.0
> * python-utils                      3.4.5
> * pytimeparse                       1.1.5
> * pytz                              2022.7.1
> * PyWavelets                        1.4.1
> * PyYAML                            5.4.1
> * pyzmq                             25.0.0
> * regex                             2022.10.31
> * requests                          2.28.2
> * requests-oauthlib                 1.3.1
> * requests-toolbelt                 0.10.1
> * requests-unixsocket               0.2.0
> * responses                         0.18.0
> * rich                              13.2.0
> * rsa                               4.7.2
> * s3transfer                        0.6.0
> * scikit-image                      0.19.3
> * scikit-learn                      1.1.2
> * scipy                             1.9.2
> * seaborn                           0.12.0
> * Send2Trash                        1.8.0
> * sentence-transformers             2.2.2
> * sentencepiece                     0.1.97
> * sentry-sdk                        1.14.0
> * setproctitle                      1.3.2
> * setuptools                        66.1.1
> * shellingham                       1.5.0.post1
> * shortuuid                         1.0.11
> * six                               1.14.0
> * smart-open                        6.3.0
> * smmap                             5.0.0
> * sniffio                           1.3.0
> * soupsieve                         2.3.2.post1
> * spacy                             3.4.1
> * spacy-legacy                      3.0.12
> * spacy-loggers                     1.0.4
> * spinners                          0.0.24
> * SQLAlchemy                        1.4.41
> * srsly                             2.4.5
> * stack-data                        0.6.2
> * tabulate                          0.9.0
> * tensorboard                       2.9.1
> * tensorboard-data-server           0.6.1
> * tensorboard-plugin-wit            1.8.1
> * tensorflow                        2.9.2
> * tensorflow-estimator              2.9.0
> * tensorflow-io-gcs-filesystem      0.30.0
> * tensorstore                       0.1.30
> * termcolor                         2.2.0
> * terminado                         0.17.1
> * terminaltables                    3.1.10
> * thinc                             8.1.7
> * thop                              0.1.1.post2209072238
> * threadpoolctl                     3.1.0
> * tifffile                          2023.1.23.1
> * tinycss2                          1.2.1
> * tokenizers                        0.12.1
> * tomli                             2.0.1
> * toolz                             0.12.0
> * torch                             1.12.1+cu116
> * torchaudio                        0.12.1+cu116
> * torchvision                       0.13.1+cu116
> * tornado                           6.1
> * tqdm                              4.64.1
> * traitlets                         5.8.1
> * transformers                      4.21.3
> * typer                             0.4.2
> * typing_extensions                 4.4.0
> * ultralytics                       8.0.55
> * Unidecode                         1.1.1
> * urllib3                           1.26.14
> * wandb                             0.13.4
> * wasabi                            0.10.1
> * wcwidth                           0.2.6
> * webencodings                      0.5.1
> * websocket-client                  0.57.0
> * Werkzeug                          2.2.2
> * wheel                             0.35.1
> * widgetsnbextension                4.0.5
> * wrapt                             1.14.1
> * xgboost                           1.6.2
> * xlrd                              1.1.0
> * xxhash                            3.2.0
> * yarl                              1.8.2
> * zipp                              3.11.0
> 
> ![image](https://user-images.githubusercontent.com/93685420/227333062-f8bb3f14-93d9-490c-b5ac-50e69bd71aea.png)
> 
> ### Environment
> Python version: Python 3.9.16 (main, Dec 7 2022, 01:11:51) OS: Ubuntu 20.04.5 LTS (Focal Fossa) Specifications: Ultralytics YOLOv8.0.55 🚀 Python-3.9.16 torch-1.12.1+cu116 CUDA:0 (NVIDIA RTX A6000, 48685MiB) Setup complete ✅ (8 CPUs, 44.1 GB RAM, 131.8/246.0 GB disk)
> 
> ### Minimal Reproducible Example
> yolo track model=/notebooks/runs/detect/train19/weights/best.pt tracker="botsort.yaml" source="/notebooks/vid4/CraneVistas TowerCrane TimeLapse Diary July 10th 2020 [Ambient Background Whitenoise Music Included.mp4" conf=0.25 iou=0.5 imgsz=1280 save_txt=True save=True save_conf=True half=True
> 
> ### Additional
> _No response_
> 
> ### Are you willing to submit a PR?
> * [ ]  Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@walter2482 use stream=True to return results in an iterator, otherwise your results will continue to accumulate over time, increasing RAM as expected. See https://docs.ultralytics.com/modes/predict

**Comment by walter2482** [comment]
@glenn-jocher Thank!!! 

Now i use:

from ultralytics import YOLO
model = YOLO('/notebooks/runs/detect/train19/weights/best.pt')
results = model.track(source="/notebooks/vid10/cranevistas.mp4",tracker="botsort.yaml",stream=True,half=True,imgsz=1920,save_txt=True,save_conf=True,save=True,conf=0.25,iou=0.5)

for r in results:
    boxes = r.boxes  # Boxes object for bbox outputs
    probs = r.probs  # Class probabilities for classification outputs

ram memory usage is constant!!!!

**Comment by ArthurHakobyann** [comment]
@glenn-jocher how can I do this "stream  = True "  on the images so that results  don't accumulate over time, increasing RAM as expected?

**Comment by glenn-jocher** [comment]
If you want to process images in a stream instead of loading them all into memory at once while avoiding memory buildup, you can use the `cv2.VideoCapture` function from the openCV library. You can pass the path to your video file or camera id to this function, which returns a `VideoCapture` object that can be used to read one frame at a time. You can then apply YOLOv8 object detection to each frame and show the results.

Here is an example of how to use `cv2.VideoCapture` and YOLOv8 to process a video file:

```python
import cv2
from yolov8 import detect

# Path to video file
video_file = 'path/to/video.mp4'

# Open the video file
cap = cv2.VideoCapture(video_file)

# Loop over frames
while True:
    # Read frame from video
    ret, frame = cap.read()

    # Break loop if end of video file reached
    if not ret:
        break

    # Perform object detection on frame
    detections = detect(frame)

    # Display the results
    cv2.imshow('Frame', detections)

    # Exit if 'q' is pressed
    if cv2.waitKey(1) == ord('q'):
        break

# Release the video capture object and destroy windows
cap.release()
cv2.destroyAllWindows()
```

You can modify this code to take input from a camera instead of a video file by passing the camera id

**Comment by ArthurHakobyann** [comment]
if I have a folder with pictures and not videos. just read each file in turn?

**Comment by glenn-jocher** [comment]
Yes, if you have a folder with pictures and not videos, you can read each file in turn using any programming language that supports image processing. 

For example, in Python, you can use the OpenCV library to read each image in the folder and process it using YOLOv8. Here is some example code:

```
import cv2
import os

# Set the path to the folder containing the images
path = "path/to/folder"

# Get a list of all the files in the folder
files = os.listdir(path)

# Iterate over each file in the folder
for file in files:
    # Check if the file is an image
    if file.endswith(".jpg") or file.endswith(".png"):
        # Read the image using OpenCV
        img = cv2.imread(os.path.join(path, file))

        # Process the image using YOLOv8
        # ...
```

Note that you will need to modify the YOLOv8 implementation to work with single images instead of video frames. You can refer to the YOLOv8 documentation for more information on how to do this.

**Comment by pbugneac** [comment]
> @walter2482 great, glad to hear it.
> 
> @AyushExel @Laughing-q I don't know how to address this issue, it seems like lots of users are running out of RAM (maybe CUDA also) when predicting on videos/webcams.

Hey @glenn-jocher , there seems to be a memory leak in ByteTrack. The `self.removed_stracks` variable increases without limit and can eventually deplete the RAM memory when running on video streams. This also leads to slower tracking inference as a result. See [here ](https://github.com/ifzhang/ByteTrack/pull/249) a proposed solution in the ByteTrack repo. If you want I can submit a pr here.

**Comment by glenn-jocher** [comment]
@pbugneac thank you for bringing this to my attention. It seems that there is a memory leak issue in the ByteTrack algorithm, where the `removed_stracks` variable is accumulating indefinitely and can eventually lead to memory depletion. This can cause slow tracking inference as well. 

A possible solution was proposed in the ByteTrack repository to address this issue. If needed, you could either implement the proposed solution or submit a pull request to the ByteTrack repository to help improve the algorithm.

**Comment by glenn-jocher** [comment]
@walter2482 see PR #1890 for a proposed solution. Please leave a comment there on the PR approach.

**Comment by glenn-jocher** [comment]
@walter2482 sure, I completely understand. It's great to hear that you're excited about the potential improvements and I look forward to hearing about the results of your experiments. In the meantime, it's important to remember to carefully preprocess your video content to maximize the accuracy and efficiency of your detection algorithms. Additionally, sharing quantitative information and metrics with others is a great way to advance the state of the art in computer vision and contribute to the broader research community.
