### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by Xuezha333** [ultralytics/ultralytics#15878]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

WARNING ⚠️ Metadata not found for 'model=/home/intern/jingjie/weights/yolov8n-pose_saved_model/yolov8n-pose_float32.tflite'

Hi!, ive finetuned a V8 pose model and tried to run inference with the official yolo inferencing script, and i got this error.
![image](https://github.com/user-attachments/assets/550559e6-4572-4532-a213-1917491fce29)

upon further investigation, ive found out that no classes and metadata are available, causing this issue. Based on my understanding, yolo.export dosent incorporate the metadadata.yaml in the yolov8n-pose_float32.tflite weights, causing this issue:
![image](https://github.com/user-attachments/assets/e70d754f-9218-415f-989d-000f716724b9)

can anyone please guide me on how to use this metadata with yolo? Thanks!

**Comment by Y-T-G** [comment]
You can try passing your `data.yaml` file during prediction:

https://github.com/ultralytics/ultralytics/issues/15003#issuecomment-2295822993

**Comment by Xuezha333** [comment]
![image](https://github.com/user-attachments/assets/419d9b5c-e17d-4345-b93a-c75195dd441a)
i've tried by still getting this issue

**Comment by Y-T-G** [comment]
What's your ultralytics version?

Can you post the output from running `yolo checks` in terminal?

**Comment by Y-T-G** [comment]
Try using `model.predict(img, data="data.yaml")`

**Comment by Xuezha333** [comment]
tried this, still yields WARNING ⚠️ Metadata not found for 'model=/home/intern/jingjie/weights/v8face_100epochs_wiseai/yolov8n-pose_saved_model/yolov8n-pose_float32.tflite'

![image](https://github.com/user-attachments/assets/7cd38837-61c3-45e9-a014-d2f34f61369c)

**Comment by Xuezha333** [comment]
![image](https://github.com/user-attachments/assets/8a4d77ed-0a5c-4ece-be8d-287789b53907)
this is the output from my yolo checks command, can you please try exporting and inferencing with tflite to validate that the issue dosent only presist on my end

**Comment by Xuezha333** [comment]
Again, thanks for your help :)

**Comment by Y-T-G** [comment]
Did you load it with `task="pose"`?

**Comment by Y-T-G** [comment]
Can you upgrade your ultralytics? It's really old.

**Comment by Xuezha333** [comment]
results = model.predict(file_path,device='cpu',data='/home/intern/jingjie/weights/v8face_100epochs_wiseai/yolov8n-pose_saved_model/metadata.yaml', task='pose') 
I did pass in the "pose" param ^

+ upgraded ultralytics and ran my inference code again, the same issue still presists
![image](https://github.com/user-attachments/assets/513ceb63-a828-4514-ba74-bb77bb576f6a)

**Comment by Y-T-G** [comment]
Use `task="pose"` while loading the model inside `YOLO()` function, not in `model.predict()`.

**Comment by Xuezha333** [comment]
model = YOLO(weight, task='pose')    was previously done also

**Comment by Y-T-G** [comment]
Can you export it again with the upgraded ultralytics and try again?

**Comment by Xuezha333** [comment]
![image](https://github.com/user-attachments/assets/123a45a2-870c-4cd3-bd38-2573e03aa922)
After exporting with the newest package, ive gotten the same results. 

However i think its worth to clear up that this "failure" is not the cause of the misfunction right? Since the tflite's weights are all present

**Comment by Y-T-G** [comment]
It works for me with latest ultralytics. No warning.

**Comment by Y-T-G** [comment]
Try using this version:

https://github.com/ultralytics/ultralytics/issues/14235#issuecomment-2211489301

**Comment by Xuezha333** [comment]
Thanks alot ! After clonning the newest ultralytics repo and using your versions for the packages, i got it to work

**Comment by glenn-jocher** [comment]
@Xuezha333 great to hear that it's working now! If you encounter any further issues, feel free to reach out.
