### ISSUE TITLE
ValueError: batch_size should be a positive integer value, but got batch_size=-1

### ISSUE THREAD

**Issue by animikhaich** [ultralytics/ultralytics#15872]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train, Hyperparameter Tuning

### Bug

```
ValueError: batch_size should be a positive integer value, but got batch_size=-1
File /Workspace/Users/ultralytics/ultralytics/engine/model.py:813, in Model.train(self, trainer, **kwargs)
    810     self.model = self.trainer.model
    812 self.trainer.hub_session = self.session  # attach optional HUB session
--> 813 self.trainer.train()
    814 # Update model and cfg after training
    815 if RANK in {-1, 0}:
File /Workspace/Users/ultralytics/ultralytics/engine/trainer.py:208, in BaseTrainer.train(self)
    205         ddp_cleanup(self, str(file))
    207 else:
--> 208     self._do_train(world_size)
File /Workspace/Users/ultralytics/ultralytics/engine/trainer.py:327, in BaseTrainer._do_train(self, world_size)
    325 if world_size > 1:
    326     self._setup_ddp(world_size)
--> 327 self._setup_train(world_size)
    329 nb = len(self.train_loader)  # number of batches
    330 nw = max(round(self.args.warmup_epochs * nb), 100) if self.args.warmup_epochs > 0 else -1  # warmup iterations
File /Workspace/Users/ultralytics/ultralytics/engine/trainer.py:291, in BaseTrainer._setup_train(self, world_size)
    289 # Dataloaders
    290 batch_size = self.batch_size // max(world_size, 1)
--> 291 self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=LOCAL_RANK, mode="train")
    292 if RANK in {-1, 0}:
    293     # Note: When training DOTA dataset, double batch size could get OOM on images with >2000 objects.
    294     self.test_loader = self.get_dataloader(
    295         self.testset, batch_size=batch_size if self.args.task == "obb" else batch_size * 2, rank=-1, mode="val"
    296     )
File /Workspace/Users/ultralytics/ultralytics/models/yolo/detect/train.py:55, in DetectionTrainer.get_dataloader(self, dataset_path, batch_size, rank, mode)
     53     shuffle = False
     54 workers = self.args.workers if mode == "train" else self.args.workers * 2
---> 55 return build_dataloader(dataset, batch_size, workers, shuffle, rank)
File /Workspace/Users/ultralytics/ultralytics/data/build.py:135, in build_dataloader(dataset, batch, workers, shuffle, rank)
    133 generator = torch.Generator()
    134 generator.manual_seed(6148914691236517205 + RANK)
--> 135 return InfiniteDataLoader(
    136     dataset=dataset,
    137     batch_size=batch,
    138     shuffle=shuffle and sampler is None,
    139     num_workers=nw,
    140     sampler=sampler,
    141     pin_memory=PIN_MEMORY,
    142     collate_fn=getattr(dataset, "collate_fn", None),
    143     worker_init_fn=seed_worker,
    144     generator=generator,
    145 )
File /Workspace/Users/ultralytics/ultralytics/data/build.py:37, in InfiniteDataLoader.__init__(self, *args, **kwargs)
     35 def __init__(self, *args, **kwargs):
     36     """Dataloader that infinitely recycles workers, inherits from DataLoader."""
---> 37     super().__init__(*args, **kwargs)
     38     object.__setattr__(self, "batch_sampler", _RepeatSampler(self.batch_sampler))
     39     self.iterator = super().__iter__()
File /databricks/python/lib/python3.10/site-packages/torch/utils/data/dataloader.py:357, in DataLoader.__init__(self, dataset, batch_size, shuffle, sampler, batch_sampler, num_workers, collate_fn, pin_memory, drop_last, timeout, worker_init_fn, multiprocessing_context, generator, prefetch_factor, persistent_workers, pin_memory_device)
    353             sampler = SequentialSampler(dataset)  # type: ignore[arg-type]
    355 if batch_size is not None and batch_sampler is None:
    356     # auto_collation without custom batch_sampler
--> 357     batch_sampler = BatchSampler(sampler, batch_size, drop_last)
    359 self.batch_size = batch_size
    360 self.drop_last = drop_last
File /databricks/python/lib/python3.10/site-packages/torch/utils/data/sampler.py:232, in BatchSampler.__init__(self, sampler, batch_size, drop_last)
    226 def __init__(self, sampler: Union[Sampler[int], Iterable[int]], batch_size: int, drop_last: bool) -> None:
    227     # Since collections.abc.Iterable does not check for `__getitem__`, which
    228     # is one way for an object to be an iterable, we don't do an `isinstance`
    229     # check here.
    230     if not isinstance(batch_size, int) or isinstance(batch_size, bool) or \
    231             batch_size <= 0:
--> 232         raise ValueError("batch_size should be a positive integer value, "
    233                          "but got batch_size={}".format(batch_size))
    234     if not isinstance(drop_last, bool):
    235         raise ValueError("drop_last should be a boolean value, but got "
    236                          "drop_last={}".format(drop_last))
```

### Environment

New https://pypi.org/project/ultralytics/8.2.82 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.2.81 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla V100-PCIE-16GB, 16151MiB)
TensorBoard: Start with 'tensorboard --logdir runs/detect/train6', view at http://localhost:6006/
Transferred 355/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅

### Minimal Reproducible Example

model = YOLO('weights/last.pt')
results = model.train(
    data='cfg/datasets/data.yaml',
    epochs=500, 
    imgsz=640, 
    cache=False, 
    patience=10,
    save_period=25,
    workers=os.cpu_count(),
    cos_lr=True, 
    lr0=0.03, 
    lrf=0.0001,
    weight_decay=0.001, 
    dropout=0.25, 
    plots=True,
    batch=-1,
    verbose=False,
    device=0,
    resume=True,
)

### Additional

The training environment is Databricks with Azure backend. Standard_NC6s_v3 Instance, with V100 GPU and 6 vCPUs and 112 GB RAM. 

I faced the same issue when I provide batch=0.6 or batch=-1 as mentioned in the Ultralytics documentation: https://docs.ultralytics.com/modes/train/#train-settings

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
If you're resuming the training from an unfinished checkpoint, you just provide the `data` and the `resume=True` argument in `model.train()`.

But if `last.pt` has finished training, then you can't resume anymore so it should be `False`.

**Comment by animikhaich** [comment]
Thanks for your response. 

However that is not the error that I faced. 

The error is regarding setting the batch size and not resuming training.

More specifically, if I set the "batch" to be a positive integer like 16, 32, 64, etc, it trains as expected. 

However based on the YOLO documentation (linked above) the "batch" argument also accepts the values: -1 (for auto batch size) or fractions like 0.5 to indicate setting a batch size such that it occupies 50% of the GPU VRAM. In this case, it throws the error mentioned above.

**Comment by Y-T-G** [comment]
Can you try removing all the arguments except `data` and `resume`?

`resume` should automatically run with the initial arguments used to train it including batch size. So you don't need to provide any other arguments.

`batch=-1` works when you're not resuming a training.

**Comment by Y-T-G** [comment]
Can you also post the output of `yolo checks`?

**Comment by Y-T-G** [comment]
It could also be because your environment has a `RANK` variable set to 0. You can try running.
```python
import os
del os.environ["RANK"]
```
before `model.train()`

**Comment by animikhaich** [comment]
@Y-T-G, 

Thanks for your suggestions. 

I retried with the exact changes which you suggested and that did not resolve the error. 

Code I tried: 

```
del os.environ["RANK"]

settings.update({'mlflow': False})
settings.reset()

try:
    torch.distributed.init_process_group(backend="nccl")
except:
    pass

model = YOLO('yolov8n.pt')
results = model.train(
    data='/Workspace/Users/ultralytics/ultralytics/cfg/datasets/data.yaml',
    epochs=10, 
    imgsz=640, 
    batch=-1,
)
```

Output for YOLO Checks is as follows:
```
WARNING ⚠️ Ultralytics settings reset to default values. This may be due to a possible problem with your settings or a recent ultralytics package update. 
View settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.yaml'
Update settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Ultralytics YOLOv8.2.83 🚀 Python-3.11.0rc1 torch-2.3.1+cu121 CUDA:0 (Tesla V100-PCIE-16GB, 16151MiB)
Setup complete ✅ (6 CPUs, 104.0 GB RAM, 41.6/250.9 GB disk)

OS                  Linux-5.15.0-1067-azure-x86_64-with-glibc2.35
Environment         Linux
Python              3.11.0rc1
Install             pip
RAM                 103.95 GB
CPU                 Intel Xeon E5-2690 v4 2.60GHz
CUDA                12.1

numpy               ✅ 1.23.5<2.0.0,>=1.23.0
matplotlib          ✅ 3.7.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.1>=1.4.1
torch               ✅ 2.3.1+cu121>=1.8.0
torchvision         ✅ 0.18.1+cu121>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 8.0.0
pandas              ✅ 1.5.3>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
ultralytics-thop    ✅ 2.0.5>=2.0.0
```

**Comment by Y-T-G** [comment]
What's the `torch.distributed.init_process_group(backend="nccl")` for?

**Comment by animikhaich** [comment]
On Azure Databricks Notebook, it is necessary to set that flag, otherwise the it throws an error with device allocation (different error form what this issue is about). That is platform specific. 


To reiterate, this issue is regarding the fact that setting `batch=-1` or `batch=0.70` as given as an option on [YOLO Documentation](https://docs.ultralytics.com/modes/train/#train-settings) (Screenshot below) throws a `ValueError: batch_size should be a positive integer value, but got batch_size=-1` while any integer batch size like `batch=16` or `batch=32` works perfectly fine. 

![image](https://github.com/user-attachments/assets/28f689df-efdc-4d53-abe1-c860508055a7)

**Comment by Y-T-G** [comment]
I guess that sets the `RANK` variable which messes up the environment.

Move the delete code to right before `model.train()`

**Comment by Y-T-G** [comment]
If that doesn't work, then instead of delete, add:
`os.environ["RANK"] = -1`
right before `model.train()`

**Comment by Y-T-G** [comment]
The automatic batch calculation works only if the `RANK` environment variable it -1 or 0:
https://github.com/ultralytics/ultralytics/blob/0f9f7b806c709f762483bc7ab6c56a72b357c58b/ultralytics/engine/trainer.py#L278-L285

So if your environment is somehow being set to a `RANK` other than that, then it will fail. This is expected behavior because the `RANK` variable is only changed when running distributed training. So a training run using a single GPU shouldn't be having a `RANK` other than `-1`.

**Comment by animikhaich** [comment]
@Y-T-G , thank you. This issue was resolved when I ran it directly in a bare-metal VM instead of through Databricks.

**Comment by Petros626** [comment]
@Y-T-G for me a problem during validation task appeared:
`ValueError: batch_size should be a positive integer value, but got batch_size=-1`

Validation code:
```python
from ultralytics import YOLO
model = YOLO('/home/heizung1/ultralytics_yolov8-obb_ob_kitti/ultralytics/kitti_bev_yolo/run_94_Adam_88.8_87.2/weights/best.pt') # val. Pytorch model FP32
metrics = model.val(data='/home/heizung1/ultralytics_yolov8-obb_ob_kitti/ultralytics/cfg/datasets/kitti_bev.yaml', imgsz=640, 
                    batch=-1, save_json=False, save_hybrid=False, conf=0.001, iou=0.5, max_det=300, half=False,
                    device='0', dnn=False, plots=False, rect=False, split='val', project='kitti_bev_yolo', name='val')
```
RANK variable with output:
```python
import os
rank = os.environ.get("RANK")
print(f"RANK: {rank}")
```
`RANK: None`

**Comment by Y-T-G** [comment]
@Petros626 You can't use -1 or fraction batch outside of `model.train()`

**Comment by Petros626** [comment]
But the documentation for validation mode describes this as a valid option. Other batch sizes work fine, would setting `RANK` to - 1 before validating work or should I avoid it?

**Comment by Y-T-G** [comment]
Updated https://github.com/ultralytics/ultralytics/pull/19504

**Comment by Y-T-G** [comment]
`RANK` issue is only applicable if you're training.

**Comment by Petros626** [comment]
Thanks for your service! 

> Updated [#19504](https://github.com/ultralytics/ultralytics/pull/19504)

Thanks for your service!
