### ISSUE TITLE
No detection 

### ISSUE THREAD

**Issue by ashunrt** [ultralytics/ultralytics#15885]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Other

### Bug

I have trained yolov10l.pt model on custom dataset on google colab and tested the model performance on colab, it is working.
But when i tried to use it locally there is no detection. The code is same that i have used on colab.

This is how i trained the model 
![Screenshot 2024-08-29 142149](https://github.com/user-attachments/assets/6ff72c08-5bd0-4bbf-af30-109c6fd73d62)

and testing/prediction code
![Screenshot 2024-08-29 142019](https://github.com/user-attachments/assets/6980425f-c8d7-4f87-9ccb-1204001046b1)

I am using same code locally with paths changed. Why is this hapeening and how can i resolve this issue?
Output when ran locally 
![Screenshot 2024-08-29 142307](https://github.com/user-attachments/assets/a5a93620-65d9-45cf-9dcd-e88507aa5f15)

### Environment

Python-3.10.14

### Minimal Reproducible Example

**Code used locally**

```python
import cv2
import os
from ultralytics import YOLO
model2 = YOLO('D:\\yolo_custom\\best.pt')

def predict(chosen_model, img, classes=[], conf=0.15):
    if classes:
        results = chosen_model.predict(img, classes=classes, conf=conf)
    else:
        results = chosen_model.predict(img, conf=conf)
    return results

def predict_and_detect(chosen_model, img, classes=[], conf=0.15, rectangle_thickness=2, text_thickness=1):
    results = predict(chosen_model, img, classes, conf=conf)
    for result in results:
        for box in result.boxes:
            cv2.rectangle(img, (int(box.xyxy[0][0]), int(box.xyxy[0][1])),
                          (int(box.xyxy[0][2]), int(box.xyxy[0][3])), (255, 0, 0), rectangle_thickness)
            cv2.putText(img, f"{result.names[int(box.cls[0])]}",
                        (int(box.xyxy[0][0]), int(box.xyxy[0][1]) - 10),
                        cv2.FONT_HERSHEY_PLAIN, 1, (255, 0, 0), text_thickness)
    return img, results

for i in os.listdir('D:\\yolo_custom\\test'):
  image_path = os.path.join('D:\\yolo_custom\\test', i)
  image = cv2.imread(image_path)
  image = cv2.resize(image, (480,640))

  if image is not None:
    result_img, _ = predict_and_detect(model2, image, classes=[])
    cv2.imwrite(f"D:\\yolo_custom\\processed_images\\{i}", result_img)
  else:
    print(f"Failed to load image: {image_path}")
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
Can you post the output of the `yolo checks` command in terminal?

**Comment by ashunrt** [comment]
Hi @Y-T-G, Thank you for helping me out, here is the output of yolo checks. It is working thorugh command line and i have checked the same command line code in jupyter notebook locally and it is working but i can't use this command line code for my use case.
![Screenshot 2024-08-30 103148](https://github.com/user-attachments/assets/710e72df-ab45-4b53-95a9-f7ffffd3e6d0)

**Comment by Y-T-G** [comment]
Try downgrading to torch 2.3.1

**Comment by Y-T-G** [comment]
`yolo checks` is a command that you need to run in a terminal. Then post the output of running that.

**Comment by ashunrt** [comment]
The problem is i have different environment with different python versions in my vscode,when i ran it in terminal it showed Python 3.8.0, so i tried to run the code on 3.8 and it is working and detecting.

But i still wonders, why it was not running on 3.10.14 , like there was no error thrown when i ran the code, it ran successfully with no detection.

**Comment by Y-T-G** [comment]
You will have to run `yolo checks` with both environments and  see if they're the same.

**Comment by ashunrt** [comment]
Yes, they were different. Thanks for the help @Y-T-G
