### ISSUE TITLE
How can i stop when yolov8 predict is runing?

### ISSUE THREAD

**Issue by kyoko9000** [ultralytics/ultralytics#1588]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When i start predict yolov8 webcam and i dont know how to stop it with code. I need to make a program with yolov8.

**Comment by AyushExel** [comment]
Pressing key 'Q' works for me.
To force stop the process you can use ctrl+c or z

**Comment by kyoko9000** [comment]
Thank to answer but if i need to make it stop by code how can i do?

**Comment by pderrenger** [comment]
@kyoko9000 to stop YOLOv8 prediction using code, you can implement a signal handler in your program to catch a specific interrupt signal such as SIGINT (Ctrl+C). Upon catching the signal, you can add code to gracefully stop the YOLOv8 prediction process. This approach allows you to handle the process termination programmatically.
