### ISSUE TITLE
How to apply YOLOv8 in a multi-task scenario that requires both bounding boxes and keypoint annotations?

### ISSUE THREAD

**Issue by Guan9Wu** [ultralytics/ultralytics#15894]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a dataset with 3 categories, where all categories have been annotated with bounding boxes, and two of the categories require additional keypoint annotations. How should I structure the dataset? How can I apply YOLOv8 to this case?

**Comment by Guan9Wu** [comment]
Thanks for your response. I appreciate your help. Closing this issue now.

**Comment by glenn-jocher** [comment]
@Guan9Wu you're welcome! If you have any more questions in the future, feel free to ask. Have a great day!
