### ISSUE TITLE
When exporting onnx, how to export the feature map of a certain layer in backbone?

### ISSUE THREAD

**Issue by DWendou** [ultralytics/ultralytics#15905]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I trained my yolov8obb model, and when I exported onnx, I want to use the feature map output by the first C2f module in backbone as the output "output1", and then the feature map output by the last C2f module as the output "output2". Finally, the yolov8obb.onnx model has the original output 'output0' and two additional outputs' output1 'and' output2 '. What should I do with the output of an onnx structure like the one shown below in the middle of the model
![微信图片_20240830101451](https://github.com/user-attachments/assets/564e4d94-145e-4a09-aefd-32f50ad395b7)
? Look forward to your reply very much, thank you!

**Comment by Y-T-G** [comment]
You can try this:

https://github.com/microsoft/onnxruntime/issues/1455#issuecomment-979901463

**Comment by DWendou** [comment]
> You can try this:
> 
> [microsoft/onnxruntime#1455 (comment)](https://github.com/microsoft/onnxruntime/issues/1455#issuecomment-979901463)

Great, successfully solved my problem, thank you very much!!
