### ISSUE TITLE
yolov8 obb opencv dnn onnx cpp demo

### ISSUE THREAD

**Issue by CF-chen-feng-CF** [ultralytics/ultralytics#15907]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

For yolov8 obb, there is not a single case of opencv+dnn inference using c++ language, can you add

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
The `OBB` inference would work similar to the normal `Detect` except you have `angle` as the last value after the class confidences. So you have a total of `4 + nc + 1` output for each anchor.

**Comment by CF-chen-feng-CF** [comment]
> The `OBB` inference would work similar to the normal `Detect` except you have `angle` as the last value after the class confidences. So you have a total of `4 + nc + 1` output for each anchor.

Thank you, I have succeeded.

**Comment by glenn-jocher** [comment]
@CF-chen-feng-CF great to hear that you succeeded! If you have any more questions, feel free to ask.

**Comment by JinYuannn** [comment]
I've seen some similar issues. If needed, I can submit a PR to add an OBB MODEL_TYPE to the ONNXRuntime C++ demo. @glenn-jocher

**Comment by glenn-jocher** [comment]
Thank you for offering to contribute! Please feel free to submit a PR with your proposed changes. We appreciate your support.
