### ISSUE TITLE
How to cancel console log printing

### ISSUE THREAD

**Issue by linxingchao** [ultralytics/ultralytics#1590]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/18258911/227412646-9a7430bb-a356-4be9-99a8-dcc45e441644.png)

**Comment by AyushExel** [comment]
pass `verbose=False`

**Comment by glenn-jocher** [comment]
@linxingchao also you can set environment variable `YOLO_VERBOSE=False` to disable ALL YOLO console logging.
