### ISSUE TITLE
License for sale

### ISSUE THREAD

**Issue by Egorundel** [ultralytics/ultralytics#15911]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Greetings, I am writing to find out what license is used by ultralytics? 
Can I use your detector and then sell this solution to someone without any problems?

**Comment by glenn-jocher** [comment]
@Egorundel greetings, Ultralytics YOLO is available under the AGPL-3.0 license, which requires you to open-source your entire project if you use our models. For commercial use without open-source requirements, you need an Enterprise License. Please visit https://ultralytics.com/license for more details.

**Comment by RizwanMunawar** [comment]
@Egorundel Thanks for your query! It looks like @glenn-jocher has already addressed your question.

_Ultralytics YOLO is available under the AGPL-3.0 license, which requires you to open-source your entire project if you use our models. For commercial use without open-source requirements, you need an Enterprise License. Please visit https://ultralytics.com/license for more details._

I'll go ahead and close this issue for now. If you encounter any further issues, feel free to open a new one!

Thanks and Regards
The Ultralytics Team!
