### ISSUE TITLE
yolov8.2.83 predict not right

### ISSUE THREAD

**Issue by sxzzl55** [ultralytics/ultralytics#15910]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

yolo predict model=yolov8n.pt source='bus.jpg' show=True save=True device='cpu'

YOLOv8n summary (fused): 168 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs

image 1/1 C:\deep\tool\bus.jpg: 640x480 31 cars, 66 airplanes, 5 buss, 165 trains, 30 boats, 3 stop signs, 428.6ms
Speed: 7.0ms preprocess, 428.6ms inference, 45.8ms postprocess per image at shape (1, 3, 640, 480)

### Environment

Ultralytics YOLOv8.2.83 🚀 Python-3.12.5 torch-2.4.0+cpu CPU (Intel Xeon Platinum 8163 2.50GHz)

### Minimal Reproducible Example

yolo predict model=yolov8n.pt source='bus.jpg' show=True save=True device='cpu'

YOLOv8n summary (fused): 168 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs

image 1/1 C:\deep\tool\bus.jpg: 640x480 31 cars, 66 airplanes, 5 buss, 165 trains, 30 boats, 3 stop signs, 428.6ms
Speed: 7.0ms preprocess, 428.6ms inference, 45.8ms postprocess per image at shape (1, 3, 640, 480)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Alarmod** [comment]
https://github.com/ultralytics/ultralytics/issues/15049

**Comment by glenn-jocher** [comment]
Thank you for reporting this issue. Please ensure you are using the latest version of the Ultralytics package. If the problem persists, let us know so we can further investigate.

**Comment by glenn-jocher** [comment]
@Alarmod @ambitious-octopus @Y-T-G @Skillnoob @Burhan-Q guys please mark duplicate issues as duplicate when you spot them to help organize these better, thank you!

If anyone is missing permissions let @Burhan-Q know and I can add you.
