### ISSUE TITLE
Is the background picture involved in training

### ISSUE THREAD

**Issue by bj5546** [ultralytics/ultralytics#1591]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In my sample, there are 1000 images, 20 of which are unlabeled files, so does it participate in training? Do I have to generate an empty label file if I want him to participate in the training

**Comment by glenn-jocher** [comment]
@bj5546 yes, all images in your train or val directories are used regardless of whether they have associated label files.
