### ISSUE TITLE
Get More Out of My GPU

### ISSUE THREAD

**Issue by jitaxis** [ultralytics/ultralytics#1592]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I am getting inference times of about 50ms or so, which is good but I feel like my GPU is being under utilized. The GPU being used is a A5000 RTX and I have attached an image of my GPU usage (not all is due to YOLOv8). 
![GPU usage](https://user-images.githubusercontent.com/99373584/227420966-f177717e-5bb8-44a6-a11d-9efa06bcc4ac.png)
I was wondering if there is a way to make YOLOv8 use my GPU better? 
The main reason I ask this is because I am getting pretty much the same results as I did from using my Quadro 3000 RTX on my laptop.
Any help is appreciated,
Thanks.

**Comment by glenn-jocher** [comment]
@jitaxis use a larger image size, larger model, larger batch size, etc, you get the idea.

**Comment by jitaxis** [comment]
Thanks for the response. Is that mainly for the training side? The main area im looking to increase for is inference. 
Or by applying the tips, does that increase the speed, Or accuracy or both of inference?

**Comment by glenn-jocher** [comment]
@jitaxis the above steps will naturally increase GPU utilization, which was the intention of your original request. Other outcomes may vary.

**Comment by jitaxis** [comment]
My naive assumption was that better GPU utilization would come with better inference times. From the graphs on the main readme, my follow-up question is how those speeds were achieved. 
Sorry if these questions are potentially basic, it's just a gap in my knowledge that would improve my understanding of object detection and how to improve my work.
Thank you for taking the time so far to answer my questions.

**Comment by glenn-jocher** [comment]
@jitaxis README speeds are on ONNX or TensoRT A100 FP16 at batch-size 1 for 640 images.

<img width="799" alt="Screenshot 2023-03-27 at 02 58 40" src="https://user-images.githubusercontent.com/26833433/227816906-dcf51423-fcda-46b2-bd96-d437e3045e20.png">
