### ISSUE TITLE
speed estimation always results in 0

### ISSUE THREAD

**Issue by Wangxinyu-qlz** [ultralytics/ultralytics#15928]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

speed_estimation

### Bug

Thanks to your contributions, I was able to get the features I needed done quickly!
But I encountered this bug when using the `speed_estmation` module: 
the estimated speed is always 0
`notes: Since my code is a bit different from the official documentation, I haven't found any other cases where this bug occurs, so if it's because of my wrong call, I kindly ask you to point it out!`

### Environment

 - Ultralytics YOLOv8.2.7
 - Python-3.11.7

### Minimal Reproducible Example

I read the documentation https://docs.ultralytics.com/guides/speed-estimation/?h=speedestimator#real-world-applications
and found that the handling is a bit different, here is my code:
The whole system is complex and I've only extracted the key parts, so please let me know if I've missed anything!
```python
line_pts = [(20, 360), (1260, 360)]

# Init speed-estimation obj
speed_obj = speed_estimation.SpeedEstimator()
speed_obj.set_args(reg_pts=line_pts,
                   names=model.model.names,
                   view_img=True,
                   spdl_dist_thresh=300)

# Get data source
iter_model = iter(
            model.track(source=self.source, show=False, stream=True, iou=0.45, conf=0.25))

# Get the image information of a frame
result = next(iter_model)  
speed_obj.estimate_speed(result.orig_img, result)

# draw label on the image
labels_write, img_box, speed_obj.dist_data = self.creat_labels(detections, img_box, model, speed_obj)
```

### Additional

I made my system work by changing the code in the speed_estimation.SpeedEstimator.extract_tracks() method
```python
def extract_tracks(self, tracks):
    """
    Extracts results from the provided data.

    Args:
        tracks (list): List of tracks obtained from the object tracking process.
    """
    # self.boxes = tracks[0].boxes.xyxy.cpu()
    # self.clss = tracks[0].boxes.cls.cpu().tolist()
    # self.trk_ids = tracks[0].boxes.id.int().cpu().tolist()

    # return all objects' message
    self.boxes = tracks.boxes.xyxy.cpu()
    self.clss = tracks.boxes.cls.cpu().tolist()
    self.trk_ids = tracks.boxes.id.int().cpu().tolist()
```
The reason for doing so: I found out through repeated dubug that the parameter tracks received by extract_tracks(self, tracks) is the result returned by model.tracks(), which contains information about all detected objects in the current frame, as shown in the figure, 
![PixPin_2024-08-31_16-06-22](https://github.com/user-attachments/assets/ca6644be-1092-4be4-aa6a-1fbae95e6a0a)
The result (i.e. tracks) contains the information of 4 objects in the current frame, but the extract_tracks() method only returns the first one, i.e. track[0].
test1: `self.boxes = tracks.boxes.xyxy.cpu()...`
![image](https://github.com/user-attachments/assets/e5cd8fcb-5957-4c03-ac7d-e02554d7ca2a)
test2: `self.boxes = tracks[0].boxes.xyxy.cpu()...`
![image](https://github.com/user-attachments/assets/19ec36f1-3bb0-4d7b-88de-51e6510bd5cf)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Wangxinyu-qlz thank you for the detailed report. It seems like the issue might be related to how the tracks are being processed. Please ensure you are using the latest version of the Ultralytics package. If the issue persists, feel free to submit a PR with your proposed changes for further review.

**Comment by Wangxinyu-qlz** [comment]
> @Wangxinyu-qlz thank you for the detailed report. It seems like the issue might be related to how the tracks are being processed. Please ensure you are using the latest version of the Ultralytics package. If the issue persists, feel free to submit a PR with your proposed changes for further review.

thanks your advice, I got to the root of the problem.
I tested both the [official examples]( https://docs.ultralytics.com/guides/speed-estimation/?h=speedestimator#real-world-applications) and my code, using both Ultralytics YOLO v8.2.7 and v8.2.85 for each test.
### Conclusion: the method in speed_estimation.SpeedEstimator is fine
I compared the differences between the official example and my code with debug, and finally, 
the problem is in the `result(tracks)` passed to `estimate_speed(self, im0, tracks, region_color=(255, 0, 0))`, as shown:
![difference](https://github.com/user-attachments/assets/17f0c7c3-12f2-4dae-9ceb-a64040468732)
`I should have tested the official example first,` I'm sorry for the trouble I caused, please accept my sincere apologies!

**Comment by glenn-jocher** [comment]
@Wangxinyu-qlz thank you for the update and for thoroughly testing the issue. I'm glad you identified the root cause. If you have any further questions or need additional assistance, feel free to ask.
