### ISSUE TITLE
YOLOv8 Object Detection: Parsing the metrics for generating Precision/Recall/F1-Confidence curve

### ISSUE THREAD

**Issue by neelsen1994** [ultralytics/ultralytics#15938]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

First of all, thanks for the great work!

I want to generate a plot for the Precision-Confidence, Recall-Confidence, F1-Confidence and Precicion-Recall curve, just like the one which is generated after the validation script. When I run the model.val() with my trained model and dataset, I get an object (Metrics and DetMetrics) having a couple of attributes and methods. After going through all the attributes, I can't find anything that returns me the list of precision/recall/f1 values based on the confidence threshold. 

Any help in this would be greatly appreciated.

Thanks in advance.

Best regards
Neel

**Comment by Y-T-G** [comment]
They are in `results.curve_results`

**Comment by neelsen1994** [comment]
> They are in `results.curve_results`

Thanks! I got that.

**Comment by glenn-jocher** [comment]
@neelsen1994 you're welcome! If you have any more questions, feel free to ask.

**Comment by Petros626** [comment]
@neelsen1994 does that mean, that the visual outputs aren't limited to COCO Metrics Evaluation "https://docs.ultralytics.com/guides/yolo-performance-metrics/#class-wise-metrics" ? 

I thought you can only evaluate "What metrics can I get from YOLOv8 model validation?" from https://docs.ultralytics.com/modes/val/#how-do-i-validate-my-yolov8-model-with-ultralytics

Thanks in advance

**Comment by neelsen1994** [comment]
> @neelsen1994 does that mean, that the visual outputs aren't limited to COCO Metrics Evaluation "https://docs.ultralytics.com/guides/yolo-performance-metrics/#class-wise-metrics" ?
> 
> I thought you can only evaluate "What metrics can I get from YOLOv8 model validation?" from https://docs.ultralytics.com/modes/val/#how-do-i-validate-my-yolov8-model-with-ultralytics
> 
> Thanks in advance

The visual outputs (Precision-Recall, F1-Confidence, Precision-Confidence, Recall-Confidence curves) are generated from 'curves_results' property of the DetMetrics class. It gives a list of conf threshold and corresponding recall, precision and f1 values.

**Comment by glenn-jocher** [comment]
The visual outputs (Precision-Recall, F1-Confidence, Precision-Confidence, Recall-Confidence curves) are generated from the `curve_results` property of the `DetMetrics` class, providing a list of confidence thresholds and corresponding recall, precision, and F1 values.
