### ISSUE TITLE
lazy inference of detection result while set stream=True

### ISSUE THREAD

**Issue by sinopec** [ultralytics/ultralytics#15939]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I process a large video file use model prediction while set stream=True， It seems I cant iterrator the results use "for in", but I can only wait all video frames is processed to use the results. 
No lazy inference  works as expected.
How can I do it ?

**Comment by Skillnoob** [comment]
@sinopec Can you share the code you used?
Simple example on how to use stream:
```python
from ultralytics import YOLO

model = YOLO("yolov8n.pt") 

results = model(source="video.mp4", stream=True) 

for result in results:
    pass
```

**Comment by sinopec** [comment]
sorry , i got a mistake, the inference is lazy executed,but  the fastapi i used  is not returned instantly , until all is processed.

**Comment by glenn-jocher** [comment]
@sinopec it sounds like the issue might be with FastAPI's handling of the streaming results. You may need to adjust your FastAPI implementation to handle streaming responses properly. If the problem persists, please ensure you're using the latest version of the Ultralytics package.
