### ISSUE TITLE
results path

### ISSUE THREAD

**Issue by Pandaliaojing** [ultralytics/ultralytics#15935]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to add a method in the results class to get the path to save the image and txt after the model prediction. How do I modify the script

**Comment by Y-T-G** [comment]
Do you mean the path of the image?
