### ISSUE TITLE
How do I auto-mask using the Segment Anything 2 model?

### ISSUE THREAD

**Issue by kadirnar** [ultralytics/ultralytics#15951]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to make auto-mask using SAM2 model. I reviewed the documentation. I found this code.

```python
from ultralytics.data.annotator import auto_annotate

auto_annotate(data="path/to/images", det_model="yolov8x.pt", sam_model="sam2_b.pt")
```
But I don't want that. I just want to make an auto mask using the sam model.

Example Notebook: https://github.com/facebookresearch/segment-anything-2/blob/main/notebooks/automatic_mask_generator_example.ipynb

**Comment by glenn-jocher** [comment]
@kadirnar to auto-mask using the SAM 2 model directly, you can use the following code snippet:

```python
from ultralytics import SAM

# Load the SAM 2 model
model = SAM("sam2_b.pt")

# Run inference to auto-mask
results = model("path/to/image.jpg")
```

This will generate masks for the entire image without needing additional prompts. For more details, please refer to the [SAM 2 documentation](https://docs.ultralytics.com/models/sam-2/).
