### ISSUE TITLE
Prediction with certain GPU，but it is not specified

### ISSUE THREAD

**Issue by s907461903** [ultralytics/ultralytics#1595]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection, Multi-GPU

### Bug

Prediction with certain GPU，but it is not specified.
results = model.predict(source="/data1/home/images/predict/",save=True, save_txt=True, device="1,2")  
while the result show 
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 564.00 MiB (**GPU 0;** 31.75 GiB total capacity; 29.32 GiB already allocated; 455.69 MiB free; 30.10 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

By the way，the trainng can specify the GPU 
correctly.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@s907461903 predict supports CPU, MPS, single CUDA device

**Comment by s907461903** [comment]
> @s907461903 predict supports CPU, MPS, single CUDA device
Thank you for your reply. But When I predict like results = model.predict(source="/data1/home/sunchen/Data/SAM/images/train/", save_txt=True, **device="2"**)  ,with sigle Cuda device  and device2, the results say  like
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 72.00 MiB (**GPU 0**; 31.75 GiB total capacity; 29.91 GiB already allocated; 7.69 MiB free; 30.53 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF.
I donot know why I spicify device2, it shows GPU0 out of memory.  The GPU0  as follows
0  Tesla V100-PCIE...  Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   34C    P0    24W / 250W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A

**Comment by Laughing-q** [comment]
@s907461903 please set `stream=True` which is the memory efficient way to use predict, more details please refer to our docs. [https://docs.ultralytics.com/modes/predict/](https://docs.ultralytics.com/modes/predict/)
