### ISSUE TITLE
Export but in 'head' self.export=false

### ISSUE THREAD

**Issue by djdll** [ultralytics/ultralytics#15952]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

A new Detect was designed, but when exporting the onnx model, export=false, which was strange. As a result, the output format of the model was not exported in the way I designed, but when I switched detect to ultralytic, it printed true

### Environment

Ultralytics 8.2.18

### Minimal Reproducible Example

```
from ultralytics import YOLO
import numpy as np
ptpath = 'runs/obb/train_c3_du_ch_le_e500_ciou/weights/best.pt'
onnxpath = 'runs/obb/train_c3_du_ch_le_e500_ciou/weights/best.onnx'
model = YOLO(ptpath)
model.export(format="onnx",imgsz=(192,288))  # creates 'yolov8n.onnx'
```
2.
```
class myDetect(nn.Module):
    """YOLOv8 Detect head for detection models."""

    dynamic = False  # force grid reconstruction
    export = False  # export mode
    shape = None
    anchors = torch.empty(0)  # init
    strides = torch.empty(0)  # init

    def __init__(self, nc=80, ch=()):
        """Initializes the YOLOv8 detection layer with specified number of classes and channels."""
        super().__init__()
        self.nc = nc  # number of classes                                                               
        self.nl = len(ch)  # number of detection layers       ........        
``` 
3.
```
class myOBB(myDetect):
    def __init__(self, nc=80, ne=1, ch=()):
        """Initialize OBB with number of classes `nc` and layer channels `ch`."""
        super().__init__(nc, ch)
        self.ne = ne  # number of extra parameters
        .....  
        print("exportobb--------------------------------------------",self.export)
        if self.export:
            return x[0], x[1], angle_return
        else:
            return (torch.cat([x[0], angle], 1), (x[1], angle))   
```   
4.
output:
```
exportobb-------------------------------------------- False
exportobb-------------------------------------------- False

PyTorch: starting from 'runs/obb/train_c3_du_ch_le_e500_ciou_reg=8/weights/best.pt' with input shape (1, 1, 192, 288) BCHW and output shape(s) ((1, 6, 1134), ()) (1.5 MB)

ONNX: starting export with onnx 1.16.2 opset 19...
exportobb-------------------------------------------- False
```
                

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
It's set here. Maybe something is wrong with your modification.

https://github.com/ultralytics/ultralytics/blob/1a497f174c21993e2464725d96482e2a4a52758b/ultralytics/utils/callbacks/tensorboard.py#L60-L61

**Comment by djdll** [comment]
@Y-T-G Both training and testing worked fine, and exporting the model worked, but recently I wanted to change the output format and found this problem. Indeed, when I ran one of the detection tasks I had trained earlier, export=true, but I was wondering what was the problem

**Comment by Y-T-G** [comment]
The code checks if it is an instance of `Detect` or `RTDETR`:

https://github.com/ultralytics/ultralytics/blob/5b3e60b4525f1b757bf4b1b8d78a273f7133e358/ultralytics/engine/exporter.py#L247-L250

Your model is not using `Detect` but creating a new class `myDetect`.

**Comment by djdll** [comment]
@Y-T-G yes，you are right. Thanks, it is indeed effective to add 'MyDetect' where you said above. I found that the following paragraph also contains 'Detect' through searching. Do you know that 'MyDetect' needs to be added here or 489 line what is the use of it.
[ultralytics/ultralytics/engine/exporter.py](https://github.com/ultralytics/ultralytics/blob/5b3e60b4525f1b757bf4b1b8d78a273f7133e358/ultralytics/engine/exporter.py#L247-L250)
```
489            if isinstance(self.model.model[-1], Detect):
490                # Includes all Detect subclasses like Segment, Pose, OBB, WorldDetect
491                head_module_name = ".".join(list(self.model.named_modules())[-1][0].split(".")[:2])
```

**Comment by Y-T-G** [comment]
You can just make your `myDetect` class inherit from `Detect`

`class myDetect(Detect)`

instead of adding `myDetect` to all these places.
