### ISSUE TITLE
Should I choose weight from augmentation epochs?

### ISSUE THREAD

**Issue by optimisticabouthumanity** [ultralytics/ultralytics#15969]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Dear Ultralytics, first of all thanks to you for always being supportive towards the community.

I have a conceptual question about choosing weights:
I am training my model on first few epochs with MOSAIC augmentation turned on and on later epochs it is trained without MOSASIC.

During mosaic epochs, it's mAP50 is best. Later score decreases.

Should I choose the model with best score from all epochs? Can there be any problem if I choose weight from mosaic augmentation epochs? Or should I only take the weights from epochs where data is not mosaic-ed.

**Comment by Y-T-G** [comment]
You can select the best. `mosaic` is automatically turned off by default in the last 10 epochs.
