### ISSUE TITLE
Improvement regarding queue_management.py

### ISSUE THREAD

**Issue by TechWolf21** [ultralytics/ultralytics#15970]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

For Queue Management solution I need the queue counts outside the program and populate it in another visualization. Already there is a method called 'counts' you created but it returns '0' every time. Since I checked queue_management.py while displaying queue counts you refreshing it to 0 for some idle reason. So, by keeping your code as it is, I added some changes by creating a function to get queue counts outside to print in local system code. It is hard to add change in local system every time I install ultralytics library. Can I contribute it? Will you add as a contribution for me?

### Additional
I created a pull request by add changes
url : https://github.com/ultralytics/ultralytics/pull/15971

_No response_

**Comment by glenn-jocher** [comment]
@TechWolf21 thank you for your contribution! We appreciate your initiative in improving the queue management functionality. We'll review your pull request and provide feedback or merge it if it aligns with our project goals. Please ensure your changes are well-documented and tested.

**Comment by TechWolf21** [comment]
Thank you for your response, resolving the issue and merging my pull request.

**Comment by glenn-jocher** [comment]
@TechWolf21 you're welcome! We're glad we could resolve the issue and merge your pull request. Thank you for your contribution!
