### ISSUE TITLE
About the hyper-parameter of train:  overlap_mask

### ISSUE THREAD

**Issue by Zhiquan98** [ultralytics/ultralytics#15977]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How does YOLO handle overlapping masks? I expect that in the JSON file, the annotations labeled later would overwrite the earlier ones. Specifically, when a pixel belongs to two categories simultaneously, it should be assigned to the annotations labeled later. This is also how Labelme handles the conversion of JSON files to PNG files. I'm not sure how YOLO deals with this.

**Comment by Y-T-G** [comment]
It's based on the size of the polygons. They're sorted in descending order and laid on top of another.

This is if `overlap_masks=True` other it uses multi-label training where the pixels can belong to multiple classes.

**Comment by Zhiquan98** [comment]
> It's based on the size of the polygons. They're sorted in descending order and laid on top of another.
> 
> This is if `overlap_masks=True` other it uses multi-label training where the pixels can belong to multiple classes.

Does this mean that smaller masks will cover larger masks? Is there any way to set the overlay order to what I expect?

**Comment by Zhiquan98** [comment]
> It's based on the size of the polygons. They're sorted in descending order and laid on top of another.
> 
> This is if `overlap_masks=True` other it uses multi-label training where the pixels can belong to multiple classes.

Does this mean that smaller masks will cover larger masks? Is there any way to set the overlay order to what I expect? Because I always start by precisely annotating the large areas first, followed by the smaller adjacent areas. When annotating the boundary between the small and large areas, I often extend the boundary of the small area into the large area, and finally adjust the order of layers to let the large area cover the small area as shown in figure.
![屏幕截图 2024-09-04 092045](https://github.com/user-attachments/assets/5c47938a-4344-474f-8ac3-f5030a2a3919)

**Comment by Y-T-G** [comment]
There's no way to set the order. Segments with smaller areas will be above segments with larger areas.

You can only disable `overlap_mask`, which will treat each mask independently, so the order won't matter.

**Comment by Zhiquan98** [comment]
Thanks for the reply. It seems I’ll have to re-annotate my data.

**Comment by glenn-jocher** [comment]
You're welcome. If you need further assistance with re-annotation or have any other questions, feel free to ask.
