### ISSUE TITLE
iOS and TFLite deployment error

### ISSUE THREAD

**Issue by AndreaBrg** [ultralytics/ultralytics#1597]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I don't know if this is the best place to ask; I apologize if it is not.

I exported a yolov8 model as a .tflite, and I'm trying to use it in an iOS app, but it gives me this error `ERROR: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.` right after the TensorFlow Lite runtime initialization. This did **not** occur with YOLOv5.

Does anyone have any experience using TFLite on iOS and knows how to resolve this issue?

Thanks.

**Comment by glenn-jocher** [comment]
@AndreaBrg Flex ops were present in TFLite models untill recently, I think we removed them maybe in 8.0.53. Try to update to the latest package and then export a new TFLite model, and this error should go away I'm assuming as this new model will not have any Flex ops.
```
pip install -U ultralytics
```
