### ISSUE TITLE
AttributeError: 'Sequential' object has no attribute 'append' when loading SAM2

### ISSUE THREAD

**Issue by felipe-parodi** [ultralytics/ultralytics#15995]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Integrations

### Bug

I encountered an error when trying to load the SAM2 model as described in the documentation. Below is the code snippet I used and the corresponding error message:

```python
from supervision.annotators.core import BackgroundOverlayAnnotator
import supervision as sv
import cv2
from ultralytics import ASSETS, SAM, YOLO
model = SAM("sam2_b.pt")
```

Error:

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Cell In[9], line 1
> ----> 1 model = SAM("sam2_b.pt")
> 
> File ~\AppData\Roaming\Python\Python38\site-packages\ultralytics\models\sam\model.py:67, in SAM.__init__(self, model)
>      65     raise NotImplementedError("SAM prediction requires pre-trained *.pt or *.pth model.")
>      66 self.is_sam2 = "sam2" in Path(model).stem
> ---> 67 super().__init__(model=model, task="segment")
> 
> File ~\AppData\Roaming\Python\Python38\site-packages\ultralytics\engine\model.py:145, in Model.__init__(self, model, task, verbose)
>     143     self._new(model, task=task, verbose=verbose)
>     144 else:
> --> 145     self._load(model, task=task)
> 
> File ~\AppData\Roaming\Python\Python38\site-packages\ultralytics\models\sam\model.py:84, in SAM._load(self, weights, task)
>      69 def _load(self, weights: str, task=None):
>      70     """
>      71     Loads the specified weights into the SAM model.
>      72 
>    (...)
>      82         >>> sam._load("path/to/custom_weights.pt")
>      83     """
> ---> 84     self.model = build_sam(weights)
> ...
>    1129         return modules[name]
> -> 1130 raise AttributeError("'{}' object has no attribute '{}'".format(
>    1131     type(self).__name__, name))
> 
> AttributeError: 'Sequential' object has no attribute 'append'

I would appreciate any guidance or suggestions on how to resolve this issue. Thank you!

### Environment

Ultralytics YOLOv8.2.87 🚀 Python-3.10.14 torch-2.2.0 CUDA:0 (NVIDIA GeForce RTX 4090, 24564MiB)
Setup complete ✅ (32 CPUs, 191.7 GB RAM, 519.0/1862.3 GB disk)

OS                  Windows-10-10.0.22631-SP0
Environment         Windows
Python              3.10.14
Install             pip
RAM                 191.71 GB
CPU                 Intel Core(TM) i9-14900K
CUDA                11.8

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.8.3>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.2.0>=1.8.0
torchvision         ✅ 0.17.0>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.6>=2.0.0
torch               ✅ 2.2.0<2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

```python
from supervision.annotators.core import BackgroundOverlayAnnotator
import supervision as sv
import cv2
from ultralytics import ASSETS, SAM, YOLO
model = SAM("sam2_b.pt") # other models yield the same error
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
I am not able to reproduce it in the same version.

**Comment by felipe-parodi** [comment]
Thanks- yeah I can't

**Comment by santlchogva** [comment]
I meet the same question，can you tell me how handle it ?
![image](https://github.com/user-attachments/assets/5f8e57e6-3d68-498d-89d9-e8daba8e7e8b)

**Comment by glenn-jocher** [comment]
@santlchogva please ensure you're using the latest version of the Ultralytics package and check that your model file is correctly specified. If the issue persists, consider reinstalling the dependencies.
