### ISSUE TITLE
AttributeError: 'RTDETRDecoder' object has no attribute 'stride'

### ISSUE THREAD

**Issue by f549263766** [ultralytics/ultralytics#16006]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

## Bug
When i use this official demo(https://docs.ultralytics.com/zh/models/rtdetr/#pre-trained-models) to train the custom data, and get the bugs `AttributeError: 'RTDETRDecoder' object has no attribute 'stride'`.

![image](https://github.com/user-attachments/assets/5b4450b3-75fb-4ac1-8e2b-874db0a976d0)

### Environment

Ultralytics YOLOv8.2.87 🚀 Python-3.10.14 torch-2.3.1 CUDA:0 (NVIDIA GeForce RTX 3090, 24260MiB)
Setup complete ✅ (64 CPUs, 503.3 GB RAM, 1341.8/1832.7 GB disk)

OS                  Linux-5.15.0-100-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.14
Install             pip
RAM                 503.26 GB
CPU                 Intel Xeon Gold 6130 2.10GHz
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.3.1>=1.8.0
torchvision         ✅ 0.18.1>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0
torch               ✅ 2.3.1<2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

```python
from ultralytics import RTDETR

# Load a COCO-pretrained RT-DETR-l model
model = RTDETR("rtdetr-l.pt")

# Display model information (optional)
model.info()

devices = [0, 1, 2]

# Train the model on the custom dataset for 300 epochs
results = model.train(
                data="custom_data.yaml", 
                epochs=300,
                imgsz=640,
                patience=50, 
                batch=128, 
                cache=True,
                save=True, 
                save_period=-1,
                project="runs/train",
                name='rtdetr'
                device=devices
)

# Run inference with the RT-DETR-l model on the 'bus.jpg' image
results = model("path/to/bus.jpg")
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by f549263766** [comment]
Find the solution

**Comment by f549263766** [comment]
Find the solution

**Comment by chenqi142** [comment]
@f549263766 how do you solve?
