### ISSUE TITLE
Cache, augmentations and model name bugs

### ISSUE THREAD

**Issue by vladyskai** [ultralytics/ultralytics#16010]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

The bugs are the following:
- The name of the model created is "yolov8n.pt" instead of "yolov8s.pt", as indicated in the code.
- The model seems to be augmenting the data when I specifically set all parameters of data augmention to zero.
- The cache seems to require "195.5GB RAM", but the data is less than 4GB. This does not make any sense.

Here is the code I use for training:
```
from ultralytics import YOLO

if __name__ == '__main__':
    # Load a model
    model = YOLO("yolov8s.yaml", task="detect")

    # Use the model
    model.train(data="config.yaml", 
                task = "detect", 
                epochs= 2, 
                batch = 4, # for a 12 GB memory card
                imgsz = 2048,
                device = "cuda", 
                cache = True, 
                verbose = True,
                hsv_h=0.0,         # Disable hue augmentation
                hsv_s=0.0,         # Disable saturation augmentation
                hsv_v=0.0,         # Disable value (brightness) augmentation
                degrees=0.0,       # Disable rotation augmentation
                translate=0.0,     # Disable translation augmentation
                scale=0.0,         # Disable scale augmentation
                shear=0.0,         # Disable shear augmentation
                perspective=0.0,   # Disable perspective augmentation
                flipud=0.0,        # Disable vertical flip
                fliplr=0.0,        # Disable horizontal flip
                bgr=0.0,           # Disable RGB to BGR channel flip
                mosaic=0.0,        # Disable mosaic augmentation
                mixup=0.0,         # Disable mixup augmentation
                copy_paste=0.0,    # Disable copy-paste augmentation
                auto_augment=None, # Disable auto augment policy
                erasing=0.0,       # Disable random erasing augmentation
                crop_fraction=1.0  # Disable cropping by setting fraction to 1 (no cropping)
            )
```

Here is my log when starting a training session:

```
YOLOv8s summary: 225 layers, 11,137,148 parameters, 11,137,132 gradients, 28.7 GFLOPs

Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning C:\Users\vkk\Desktop\Data_yolo\augmentedTrainingSet2\labels.cache... 14052 images, 9174 backgrounds, 0 corrupt: 100%|██████████| 14052/14052 [00:00
train: 195.5GB RAM required to cache images with 50% safety margin but only 33.3/47.9GB available, not caching images ⚠️
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
```

### Environment

Ultralytics YOLOv8.2.87 🚀 Python-3.11.9 torch-2.5.0.dev20240903+cu124 CUDA:0 (NVIDIA GeForce RTX 3060, 12287MiB)
Setup complete ✅ (12 CPUs, 47.9 GB RAM, 1203.7/1861.9 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.11.9
Install             pip
RAM                 47.92 GB
CPU                 AMD Ryzen 5 5600 6-Core Processor
CUDA                12.4

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.5.0.dev20240903+cu124>=1.8.0
torchvision         ✅ 0.20.0.dev20240903+cu124>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.6>=2.0.0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\vkk\Desktop\Data_yolo\.venv\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "c:\Users\vkk\Desktop\Data_yolo\.venv\Lib\site-packages\ultralytics\cfg\__init__.py", line 750, in entrypoint
    special[a.lower()]()
  File "c:\Users\vkk\Desktop\Data_yolo\.venv\Lib\site-packages\ultralytics\utils\checks.py", line 614, in collect_system_info
    is_met = "✅ " if check_version(current, str(r.specifier), hard=True) else "❌ "
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\vkk\Desktop\Data_yolo\.venv\Lib\site-packages\ultralytics\utils\checks.py", line 259, in check_version
    raise ModuleNotFoundError(emojis(warning))  # assert version requirements met
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: WARNING  version>=1.8.0 is required, but version==2.5.0.dev20240903+cu124 is currently installed

### Minimal Reproducible Example

```
from ultralytics import YOLO

if __name__ == '__main__':
    # Load a model
    model = YOLO("yolov8s.yaml", task="detect")

    # Use the model
    model.train(data="config.yaml", 
                task = "detect", 
                epochs= 2, 
                batch = 4, # for a 12 GB memory card
                imgsz = 2048,
                device = "cuda", 
                cache = True, 
                verbose = True,
                hsv_h=0.0,         # Disable hue augmentation
                hsv_s=0.0,         # Disable saturation augmentation
                hsv_v=0.0,         # Disable value (brightness) augmentation
                degrees=0.0,       # Disable rotation augmentation
                translate=0.0,     # Disable translation augmentation
                scale=0.0,         # Disable scale augmentation
                shear=0.0,         # Disable shear augmentation
                perspective=0.0,   # Disable perspective augmentation
                flipud=0.0,        # Disable vertical flip
                fliplr=0.0,        # Disable horizontal flip
                bgr=0.0,           # Disable RGB to BGR channel flip
                mosaic=0.0,        # Disable mosaic augmentation
                mixup=0.0,         # Disable mixup augmentation
                copy_paste=0.0,    # Disable copy-paste augmentation
                auto_augment=None, # Disable auto augment policy
                erasing=0.0,       # Disable random erasing augmentation
                crop_fraction=1.0  # Disable cropping by setting fraction to 1 (no cropping)
            )
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AmrElabbasy** [comment]
try this
https://gofile.io/d/Lji8KD
select the desired compiler in the installer

**Comment by glenn-jocher** [comment]
@vladyskai please ensure you're using the latest version of the Ultralytics package. For the model name issue, verify that the correct model file is being loaded. For augmentation, double-check that all augmentation parameters are correctly set to zero. Regarding the cache issue, ensure sufficient RAM is available and consider reducing the cache size. If the problems persist, please provide additional logs or details.

**Comment by Y-T-G** [comment]
1. The `yolov8n.pt` is used for AMP checks, and not the model being trained.
2. What augmentations have you observed? Do you have images?
3. This is normal. Decoded images take a lot more memory than actual images.

**Comment by vladyskai** [comment]
1. I see, and it seems the model created has 11M parameters as it should for the yolov8s. However, the model that appears in my working folder when I start the training has the name yolov8n. I guess this is the downloaded model for the AMP checks. Thank you for pointing that out.
![image](https://github.com/user-attachments/assets/c594078e-dc5b-48b8-816d-9017c60c4c42)

2. I do not observe the augmentations, but this line:
`albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8)))`

appears when I start a training session and I believe it should not. I do not want to apply any blur nor any of those modifications. I put all the augmentation options that appear in the documentation to zero, so I'm not sure why this line still appears.

3. I understand, thank you. I thought that you could still store the images in RAM without decoding and that would reduce the I/O related slowdown, and I didn't know raw images would take so much memory.

**Comment by Y-T-G** [comment]
You can uninstall albumentations to disable it.
