### ISSUE TITLE
How does TFLite export work?

### ISSUE THREAD

**Issue by ShubhamAtPhilips** [ultralytics/ultralytics#1603]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I am trying to figure out how does TFLite export work. Seems like the export code for tflite is commented [here](https://github.com/ultralytics/ultralytics/blob/28e48be5b68f11a7a71029b7b7bccf6a3ac26a66/ultralytics/yolo/engine/exporter.py#L566 ). So I am not sure how does it work? Can someone point me to the code where conversion happens?

Thank you.

**Comment by glenn-jocher** [comment]
@ShubhamAtPhilips exporter.py contains all export code. See https://docs.ultralytics.com/modes/export for Usage examples.
