### ISSUE TITLE
model weights

### ISSUE THREAD

**Issue by rhalder2023** [ultralytics/ultralytics#16042]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, there were 2 questions I had. 

1. So ultralytics has a hidden settings.yaml file in .config for linux systems that has the data download dir. okay lets say for example that in my yaml file the data download dir is home/documents/ML/yolo
so when i pass the path in the train() since im assuming itll join the path in the settings.yaml i just give data_dir/data.yaml, where im assuming it will make the path home/documents/ML/yolo/data_dir/data.yaml, and then try to read, but it doesnt do that it considers data_dir.data.yaml as the absolute path and hence doesnt find it.
but if pass .train(data=../data_dir/data/yaml) then it considers the path in the settings.yaml and says home/documents/ML/data_dir/data.yaml doesnt exist, well because it doesnt.
only when i provide the full path to the data.yaml file only then it runs properly.
Can explain this behavior to me pleaseee..

2. So im loading the medium model 
![image](https://github.com/user-attachments/assets/ba7d693b-52d2-40a8-af8d-813a48db800c)
but it downloads and uses the 8n.pt also 
![image](https://github.com/user-attachments/assets/c68d77ac-8afd-4747-8e04-eb7a6591d805)

is it because all the increasingly sized models uses the n version as their base model and hence we need the n.pt also??

and why is a weight from a convolution layer frozen, im assuming its related to the distribution focal loss? is there a reason for it?

**Comment by rhalder2023** [comment]
Also is there any sort of regularization implemented in the codebase for v8?

**Comment by rhalder2023** [comment]
> @rhalder2023 1. The `train()` function requires the full path to the `data.yaml` file. It doesn't automatically join paths from the settings file, so you'll need to specify the complete path manually.
> 
> 2. The `8n.pt` model is not used as a base for other models. If it's downloading unexpectedly, please ensure you're specifying the correct model path. The frozen convolution layer is unrelated to distribution focal loss; it might be part of the model's architecture.

the training summary does show me this though
![image](https://github.com/user-attachments/assets/8d79a94c-701f-4841-a2fc-ce1a3566c56b)

even then it downloaded the nano model

**Comment by rhalder2023** [comment]
> > @rhalder2023 1. The `train()` function requires the full path to the `data.yaml` file. It doesn't automatically join paths from the settings file, so you'll need to specify the complete path manually.
> > 
> > 2. The `8n.pt` model is not used as a base for other models. If it's downloading unexpectedly, please ensure you're specifying the correct model path. The frozen convolution layer is unrelated to distribution focal loss; it might be part of the model's architecture.
> 
> the training summary does show me this though ![image](https://private-user-images.githubusercontent.com/126802941/364898782-8d79a94c-701f-4841-a2fc-ce1a3566c56b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NjA2MTQsIm5iZiI6MTcyNTU2MDMxNCwicGF0aCI6Ii8xMjY4MDI5NDEvMzY0ODk4NzgyLThkNzlhOTRjLTcwMWYtNDg0MS1hMmZjLWNlMWEzNTY2YzU2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxODE4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGIxODgyYzQwZTc5MDhkMTU1ODIxOGU3MzUwZjgwZjNkZDg4MmE2OTZlNjQ4ZjQwMDA3NTUxNGQ2MTJiNTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NMR8MFPnDUIjqDLqG58ZpEeQNQozflI8JlSrst_Pg7c)
> 
> even then it downloaded the nano model

the head does say its a segment head so, im training the right model right? like i was trying to organize my repo so i moved folders around and i was trying giving relative paths in my code so it looks cleaner, but i inadvertently made yolo somehow download the 8n model.

but based on my screenshot, im training the 8m-seg model right???

**Comment by Y-T-G** [comment]
The n model is used for AMP checks. It will always be downloaded.

The DFL layer is always frozen. It's not meant to be learnt.

**Comment by rhalder2023** [comment]
> The n model is used for AMP checks. It will always be downloaded.
> 
> The DFL layer is always frozen. It's not meant to be learnt.

Thank you very much for clearing that up

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions, feel free to ask.
