### ISSUE TITLE
WARNING for custom YAML file COCO dataset

### ISSUE THREAD

**Issue by CQHofsns** [ultralytics/ultralytics#16043]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I am new to Ultralytics, I have a large COCO format dataset, which is structured as below:

> ├── COCO
> │   ├── test.json
> │   ├── train.json
> │   └── val.json
> ├── PNG
> │   ├── <hash>.png
> │   ├── ...

I tried to modify the yaml file you have said in this issue: https://github.com/ultralytics/ultralytics/issues/9161
```
# dataset.yaml
train: ./PNG/  # directory to train images
val: ./PNG/  # directory to val images

# COCO json annotation files
train_ann: ./COCO/train.json
val_ann: ./COCO/val.json

nc: 11  # number of classes
names: [ 
...
]  # class names
```

My training code:
```
from ultralytics import YOLO

def train_model(weight_path, data_yaml_path):
    model= YOLO(weight_path)

    model.train(
        data= data_yaml_path,
        epochs= 500,
        batch= 4,
        imgsz= 640,
        device= 0
    )

train_model(weight_path= "./yolov8_weights/yolov8m.pt", data_yaml_path= "./data.yaml")
```

After the model loaded I noticed there were some warning messages as below:
```
AMP: checks passed ✅
/<path>/miniconda3/lib/python3.12/site-packages/ultralytics/engine/trainer.py:276: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(enabled=self.amp)
train: Scanning /<path>/dataset/PNG.cache... 0 images, 81471 backgrounds, 0 corrupt: 100%|██████████| 81471/81471 [00:00<?, ?it/s]
WARNING ⚠️ No labels found in /<path>/dataset/PNG.cache, training may not work correctly. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
val: Scanning /<path>/dataset/PNG.cache... 0 images, 81471 backgrounds, 0 corrupt: 100%|██████████| 81471/81471 [00:00<?, ?it/s]
WARNING ⚠️ No labels found in /<path>/dataset/PNG.cache, training may not work correctly. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
Plotting labels to /<path>/yolo/runs/detect/train/labels.jpg... 
zero-size array to reduction operation maximum which has no identity
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: SGD(lr=0.01, momentum=0.9) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.0005), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
```

Training still happened but I am afraid that the data.yaml file was not configured properly hence I got this warning. Do you have any idea about this?
Note that the train validation and test images are in the same folder. This is the predefined structure of the dataset author.

Thank you very much.

**Comment by Y-T-G** [comment]
That format is not supported. You should convert it to YOLO format.

**Comment by CQHofsns** [comment]
@Y-T-G Thanks for replying.
But as I read this issue I believe that Yolov8 can handle COCO dataset?

https://github.com/ultralytics/ultralytics/issues/9161#issuecomment-2010371643

**Comment by CQHofsns** [comment]
So I did some research and found this [GitHub](https://github.com/ppaanngggg/yolo-doclaynet/blob/main/convert_dataset.py), he wrote the code to convert the COCO JSON format to YOLO txt format. I hope this helps.

**Comment by Y-T-G** [comment]
There's also a converter that's part of ultralytics.

.https://docs.ultralytics.com/usage/simple-utilities/#convert-coco-into-yolo-format

**Comment by WoLogi** [comment]
Sorry but why coco dont work im so confused and spent 1 day to Figure out what im ding wrong because in docs tehy say coco works but now All of you say it dont works so ether they need to fix it or Update the docs that coco dont work.

**Comment by Y-T-G** [comment]
Which docs said that?

Ultralytics only works with the format described under:

https://docs.ultralytics.com/datasets/

**Comment by Gnoot01** [comment]
@Y-T-G he might be referring to: https://github.com/ultralytics/ultralytics/issues/9161#issuecomment-2014906389
