### ISSUE TITLE
use hyperparamater optimization 

### ISSUE THREAD

**Issue by MohamedKHALILRouissi** [ultralytics/ultralytics#16041]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

from ultralytics import YOLO
from pathlib import Path

# Initialize the YOLO model
model = YOLO("yolov8n.pt")

# Tune hyperparameters on COCO8 for 30 epochs
model.tune(data=f"{str(Path().absolute())}/data.yaml", epochs=30, iterations=300, optimizer="AdamW", plots=False, save=False, val=False)

when i run this code i get this issue 

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x759c06756350>: Failed to establish a new connection: [Errno 111] Connection refused

**Comment by Y-T-G** [comment]
Something wrong with your connection
