### ISSUE TITLE
Yolov8 segmentation instance

### ISSUE THREAD

**Issue by shamstuqa** [ultralytics/ultralytics#1605]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello
I want to use yolov8 to do the segmentation ,,, and I have a dataset,, but some of the images in the dataset do not contain an object that yolo can segment for, so it returns the value "None",, how to make yolo skip images that do not contain an object that yolo can You detect it and move to the other image without error??
I tried more than one condition, but it didn't work for me.

this is the line code
for filename in os.listdir(input_folder):
    if filename.endswith(('.jpg', '.png')):
        img = cv2.imread(os.path.join(input_folder, filename))

        # detect objects using YOLO
        result = ys.detect(img)
        if result is None:
            continue  # skip this image if YOLO fails to detect any objects

        bboxes, classes, segmentations, scores = result

        for bbox, class_id, seg, score in zip(bboxes, classes, segmentations, scores):
                (x, y, x2, y2) = bbox
                cv2.polylines(img, [seg], True, (0, 255, 0), 2)
                mask = np.zeros_like(img[:,:,0])
                cv2.fillPoly(mask, [seg], 1)
                object = img * np.expand_dims(mask, axis=2)

and the error after one houres

AttributeError                            Traceback (most recent call last)
<ipython-input-6-cc2c91353129> in <module>
     21 
     22         # detect objects using YOLO
---> 23         result = ys.detect(img)
     24         if result is None:
     25             continue  # skip this image if YOLO fails to detect any objects

/content/drive/MyDrive/yolov8_segmentation-pysource.com/yolo_segmentation.py in detect(self, img)
     16         result = results[0]
     17         segmentation_contours_idx = []
---> 18         for seg in result.masks.segments:
     19             # contours
     20             seg[:, 0] *= width

AttributeError: 'NoneType' object has no attribute 'segments'

**Comment by glenn-jocher** [comment]
@shamstuqa datasets must either be of type segment or detect, mixed datasets won't work well.

**Comment by shamstuqa** [comment]
[glenn-jocher](https://github.com/glenn-jocher) yes i used mixed dataset ,,and i used yolov8 to make a new dataset from this one
so how can solve this error ,, i tried a lot but no one is benefit with me
