### ISSUE TITLE
Is that possible to move YOLOModel initialize predicting to GPU?

### ISSUE THREAD

**Issue by Farenweh** [ultralytics/ultralytics#16062]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

When creating a new YOLO family model which uses `nn.tasks.DetectionModel`, a predict is required, like calling

```python
class DetectionModel(BaseModel):
    """YOLOv8 detection model."""

    def __init__(self, cfg="yolov8n.yaml", ch=3, nc=None, verbose=True):  # model, input channels, number of classes
        """Initialize the YOLOv8 detection model with the given config and parameters."""
        super().__init__()
        …………
        # Build strides
        m = self.model[-1]  # Detect()
        if isinstance(m, Detect):  # includes all Detect subclasses like Segment, Pose, OBB, WorldDetect
            s = 256 
            m.inplace = self.inplace

            def _forward(x):
                """Performs a forward pass through the model, handling different Detect subclass types accordingly."""
                if self.end2end:
                    return self.forward(x)["one2many"]
                return self.forward(x)[0] if isinstance(m, (Segment, Pose, OBB)) else self.forward(x)
        …………
```

And this inference is running on CPU anyway, which conflicts some device choosy module like `MemEfficientAttention`.
Thus, I wonder is that possible to move this part to GPU to make ultralytics capable with them?
Thanks a lot.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Farenweh thank you for your question. You can move the model to GPU by using `.to('cuda')` on the model instance. This should enable GPU usage for inference. If you encounter any issues, please ensure you're using the latest version of the package.

**Comment by Skillnoob** [comment]
If you want to run inference on the GPU you need to install a PyTorch cuda version and add `device="cuda"` to the prediction call.
