### ISSUE TITLE
using tracker slows down the process time

### ISSUE THREAD

**Issue by parniahf** [ultralytics/ultralytics#16075]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I'm using model.track on a video sequence, but I see significantly lower processing times than the predict mode. the infrence time is almost the same but when I time the process I see it takes much longer for the tracking to be completed rather than the prediction. 
Here is the result of prediction without tracking
`  
                start = time.time() 
                results = model([front_frame, back_frame], conf=0.65,device=0)
                end = time.time() 
                print(end - start)
`

![Screenshot from 2024-09-06 15-04-38](https://github.com/user-attachments/assets/ce747e2c-1e4a-4896-ab3b-077c00f08f7a)

and here is the result of tracking:
`
                start = time.time()
                results = model.track([front_frame, back_frame], conf=0.65,device=0,tracker="tracker.yaml")
                end = time.time()
                print(end - start)
`

![Screenshot from 2024-09-06 15-05-07](https://github.com/user-attachments/assets/2c005a03-91a1-4e33-9abd-2b06692baa7d)

is there any way to lower the process time for tracking?

**Comment by Y-T-G** [comment]
You can use `bytetrack.yaml` instead of `botsort.yaml`.

**Comment by JONA415457** [comment]
Kindly solve your issue here and claim your rewards

**Comment by RizwanMunawar** [comment]
@parniahf Thanks for your query! It looks like @Y-T-G has already addressed your question. You can directly use the object tracking algorithm supported by Ultralytics with the command `yolo track source="path/to/video/file.mp4"`.

I'll go ahead and close this issue for now. If you encounter any further issues, feel free to open a new one!

Thanks and Regards
The Ultralytics Team!
