### ISSUE TITLE
How to add your class to an already loaded pre-trained model.

### ISSUE THREAD

**Issue by Zaskilovan** [ultralytics/ultralytics#1607]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a class A, how can I add my own class to a pre-trained model so that I have 81 classes in recognition output, 80 pre-trained classes and 1 new class of mine?

**Comment by glenn-jocher** [comment]
@Zaskilovan short answer is you have to train on both datasets combined. See https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets for details.

**Comment by Zaskilovan** [comment]
Thanks. Maybe I didn't quite understand, but is it possible to add only my own class without retraining the model from scratch? And will this method work on YOLOv8?

**Comment by pderrenger** [comment]
@Zaskilovan yes, it is possible to add your own class without retraining the model from scratch in YOLOv8. You can achieve this by fine-tuning the pre-trained model with your additional class using transfer learning techniques. This allows you to leverage the knowledge already present in the pre-trained model and adapt it to recognize the new class. Fine-tuning involves updating the weights of the pre-trained model during training to specialize in recognizing the new class. You can refer to the YOLOv8 documentation for details on fine-tuning a model with additional classes.

**Comment by glenn-jocher** [comment]
是的，您的理解是正确的！👍 为了让模型能同时识别新的类别和原有的类别，最好的做法是将新的数据集和原始数据集合并，然后一起进行训练。这样，模型就可以学习到全部类别的特征。祝您训练成功！如果有更多问题，欢迎随时提问。

**Comment by Y-T-G** [comment]
You can in a hacky way with caveats.

https://y-t-g.github.io/tutorials/yolov8n-add-classes/

**Comment by glenn-jocher** [comment]
@Y-T-G, indeed, there's a more experimental approach you could try as suggested in the link 😊. However, always keep in mind that integrating a new class this way might introduce discrepancies in performance for your original classes. It's a neat workaround but involves careful balancing. Here's a quick snippet on how you can start this process, assuming you have your dataset ready:

```python
# Assuming you're using YOLOv8 Python package
from ultralytics import YOLO

# Load your pre-trained model
model = YOLO('yolov8n.pt') 

# Start fine-tuning with your dataset (new + original classes)
model.train(data='your_data.yaml', epochs=30, imgsz=640)
```
Always consider the trade-offs and test thoroughly. Happy coding! 🚀
