### ISSUE TITLE
ONNX outputs are not identical to PyTorch output

### ISSUE THREAD

**Issue by ShubhamAtPhilips** [ultralytics/ultralytics#1608]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

The output of the converted ONNX model is not identical to the PyTorch model. Have a look at diff between PyTorch and ONNX values.

YOLOv5 had TFModel class which copied weights from PyTorch by skipping ONNX conversion, which produced identical outputs.

![Screen Shot 2023-03-24 at 2 26 23 PM](https://user-images.githubusercontent.com/72627736/227609475-5761d945-53ae-48c5-983d-090b46d52ea2.png)
[pt.log](https://github.com/ultralytics/ultralytics/files/11065345/pt.log)
[onnx.log](https://github.com/ultralytics/ultralytics/files/11065346/onnx.log)

### Minimal Reproducible Example

`yolo val detect model=yolov8n.pt data=coco128.yaml`

`yolo export model=yolov8n.pt format=onnx`

`yolo val detect model=yolov8n.pt data=coco128.yaml`

### Additional

- not really sure what to change exactly because it's a single-line function(torch.onnx.export). So not many parameters to experiment with. 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ShubhamAtPhilips we already validate all export formats for accuracy and speed, every 24 hours and on every commit as part of our ongoing benchmarks, and ONNX is exporting and validating correctly with no accuracy loss. See https://docs.ultralytics.com/modes/benchmark for details

See https://github.com/ultralytics/ultralytics/actions/runs/4506420261/jobs/7933175225 for most recent benchmarks
<img width="1262" alt="Screenshot 2023-03-24 at 20 13 48" src="https://user-images.githubusercontent.com/26833433/227618839-2080b2c1-d433-4679-86bb-55ba10b908bf.png">
