### ISSUE TITLE
Why does yolov8 create multiple runs directories

### ISSUE THREAD

**Issue by AD-lite24** [ultralytics/ultralytics#16080]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I trained yolov8 detection for 5 epochs. In my runs->detect-> directory I found 3 directories yolov8n_e, yolov8n_e2, yolov8n_e3, where yolov8n_e is my experiment name. I don't understand the difference between these

**Comment by Y-T-G** [comment]
Each time you train, it will create a new directory to store the results.

**Comment by AD-lite24** [comment]
Ah one of my lab mates might have run it multiple times then. Sorry for the mixup

**Comment by glenn-jocher** [comment]
@AD-lite24 no worries! If you have any more questions or need further assistance, feel free to ask.
