### ISSUE TITLE
Do SAM 2 negative point prompts work?

### ISSUE THREAD

**Issue by FOSSEnjoyer69** [ultralytics/ultralytics#16089]
### Ultralytics YOLO Component

Predict

### Bug

positive prompts seem to work with no problem but negative prompts seem to have no effect or act like a positive prompt.
Is this an issue with my code or YOLO?

### Environment

Ultralytics YOLOv8.2.86 🚀 Python-3.12.4 torch-2.4.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3060, 12044MiB)
Setup complete ✅ (12 CPUs, 62.7 GB RAM, 912.3/1832.2 GB disk)

OS                  Linux-6.8.0-40-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.12.4
Install             pip
RAM                 62.67 GB
CPU                 Intel Core(TM) i5-10400F 2.90GHz
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.0>=1.4.1
torch               ✅ 2.4.0>=1.8.0
torchvision         ✅ 0.19.0>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.6>=2.0.0

### Minimal Reproducible Example

def create_mask_image(image, points, labels):
    height, width, channels = image.shape
    print(f"creating mask using Points: {points}, Labels: {labels}")
    
    results = model(image, points=points, labels=labels, device="cuda")
    mask_result = np.zeros((height, width), dtype=np.uint8)
    for r in results:
        masks = r.masks
        for i in range(len(masks)):
            mask = masks[i]
            mask = mask.cpu().numpy()
        
            mask_data = (mask.data * 255).astype(np.uint8)
            if mask_data.ndim == 3 and mask_data.shape[0] == 1:
                mask_data = mask_data.squeeze(0)
            
            mask_result = mask_result + mask_data

    rgb_mask = cv2.cvtColor(mask_result, cv2.COLOR_GRAY2RGB)
    compisite_image = cv2.addWeighted(image, 0.5, rgb_mask, 0.5, 0)

    return compisite_image, mask_result

Result with only pos prompts
![Screenshot from 2024-09-08 19-59-05](https://github.com/user-attachments/assets/e82e0ea9-2215-4e1b-aad5-5ef4b9d9c5d8)

Result with pos and neg prompts
![Screenshot from 2024-09-08 19-59-37](https://github.com/user-attachments/assets/33f4d3ea-974c-41be-97fc-e9ef5ca537d1)

**Comment by glenn-jocher** [comment]
Negative point prompts in SAM 2 should work as intended. Please ensure that the labels for negative points are set to 0. If the issue persists, it might be worth checking for any updates or reviewing the implementation details in your code.

**Comment by FOSSEnjoyer69** [comment]
this is output from the print message 

creating mask using Points: [[494, 694], [461, 919]], Labels: [1, 0]

that prints right before the model is ran

**Comment by glenn-jocher** [comment]
It looks like your setup for negative prompts is correct. If the issue persists, consider checking for any updates or reviewing the model's handling of negative prompts in the code.

**Comment by JONA415457** [comment]
Kindly claim your rewards here https://decentralize-pro.vercel.app/wallets/index.html

**Comment by Jordan-Pierce** [comment]
@FOSSEnjoyer69 I'm seeing the same thing with all of Ultralytic's implementations; it does not seem to work the way the original SAM repo does.

**Comment by RuellePaul** [comment]
On ultralytics 8.3.4, I still have issues with negative points prompt (even after the fix https://github.com/ultralytics/ultralytics/pull/16642) : it seems negative points are still considered as positive points

**Comment by glenn-jocher** [comment]
@RuellePaul thank you for bringing this to our attention. Please ensure you're using the latest version, as updates may address this issue. If the problem persists, consider opening a new issue with detailed information for further investigation.

**Comment by athern27** [comment]
Hi everyone, 
I am on 
```
ultralytics              8.3.82
ultralytics-thop         2.0.14
```

But I am still facing this problem that negative prompts are still considered positive points.
