### ISSUE TITLE
Object Detection label position error

### ISSUE THREAD

**Issue by qian-xc** [ultralytics/ultralytics#16097]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

During my training, I encountered an issue where the label positions in train_batch0.jpg differ from the label positions I input. I am using the xyxy coordinate format.
example:
![img](https://github.com/user-attachments/assets/4b85c79f-e2ad-4fa2-a4f0-de979be339b1)
![image](https://github.com/user-attachments/assets/ee5ac241-2450-4810-ac1b-9b64a52570cb)

0 0.15817 0.009 0.7002 0.16732
0 0.14858 0.17588 0.72682 0.33099
0 0.15178 0.34382 0.7396 0.48502
0 0.14965 0.49465 0.73641 0.64869
0 0.15178 0.66046 0.72043 0.81236
0 0.15284 0.82733 0.76835 0.99528

But in train_batch0.jpg it looks like this

![image](https://github.com/user-attachments/assets/79f26ace-c015-4ae6-bf28-5b1cc925d3ab)
I wonder if this is an issue with my input data. Could it be related to the image size and the density of the labels?

**Comment by Y-T-G** [comment]
It is not the correct format.

The labels are supposed to be in normalized `xywh` format.

Please check the datasets [guide](https://docs.ultralytics.com/datasets/detect/).

**Comment by qian-xc** [comment]
> It is not the correct format.
> 
> The labels are supposed to be in normalized `xywh` format.
> 
> Please check the datasets [guide](https://docs.ultralytics.com/datasets/detect/).

Thank you very much. I can now train normally. I had not clearly distinguished the input formats for Detection and Segmentation.

**Comment by glenn-jocher** [comment]
@qian-xc you're welcome! If you have any more questions, feel free to ask.
