### ISSUE TITLE
Trigger webhook on object detection

### ISSUE THREAD

**Issue by PacketTrace** [ultralytics/ultralytics#1610]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I'm working on a script that will send a webhook if an object is detected. Below is the example running code that is triggered every minute via a cronjob. The model I'm using works and successfully detects a deer, but I'm having trouble parsing the output so I can trigger an if condition. Is there an easier way to output the results of what was detected to a variable? The code doesn't work right now because the word "doe" or "buck" is in the results regardless of whether one was detected.

Example code of what I'm trying to do: 
```
from ultralytics import YOLO
import requests

URL = 'example.com'

model = YOLO('best.pt')
results = model.predict(source='deerTest.jpg',conf=0.50)
if "doe," or "buck," in results:
    testRequest = requests.get(url)

```

**Comment by glenn-jocher** [comment]
@PacketTrace use the class index, i.e. `0 in results[0].boxes.cls`

**Comment by PacketTrace** [comment]
> @PacketTrace use the class index, i.e. `0 in results[0].boxes.cls`

I'm not sure what you mean. Do you mind providing an example of where/what I'd put in my code? I'm somewhat new to coding so I apologize.
