### ISSUE TITLE
Counting is only in one direction in object_counter.py

### ISSUE THREAD

**Issue by CharanPrasadK** [ultralytics/ultralytics#16115]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

while using object_counter.py its counting on in one direction. When I use different video i need mirror them. I submitted a PR regarding this 
PR: https://github.com/ultralytics/ultralytics/pull/16104

### Additional
PR: https://github.com/ultralytics/ultralytics/pull/16163
_No response_

**Comment by glenn-jocher** [comment]
@CharanPrasadK thank you for your PR! We'll review it soon. For now, you can modify the script to handle bidirectional counting by adjusting the logic in the code.

**Comment by CharanPrasadK** [comment]
@glenn-jocher Ok, I modified the script in local system. I raised PR so it adds another functionality and some accuracy to object  counting solution.

**Comment by glenn-jocher** [comment]
Thank you for your contribution! We'll review your PR and get back to you soon.

**Comment by CharanPrasadK** [comment]
Another update PR to solve this issue.
PR:
https://github.com/ultralytics/ultralytics/pull/16163

**Comment by CharanPrasadK** [comment]
@glenn-jocher Review the new PR, and suggest me about any changes

**Comment by glenn-jocher** [comment]
Thank you for your PR! We'll review it and provide feedback soon.

**Comment by CharanPrasadK** [comment]
@glenn-jocher can you review and merge it or give some suggestions

**Comment by glenn-jocher** [comment]
Thank you for your contribution! We'll review your PR and provide feedback shortly.
