### ISSUE TITLE
Error occurred in yolov8 switching to savemodel

### ISSUE THREAD

**Issue by tangruinenu** [ultralytics/ultralytics#1612]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Error occurred in yolov8 switching to savemodel

code：
from ultralytics import YOLO

model =("/home/rui.tang/runs/detect/train2/weights/best.pt")
model.fuse()  
model.info(verbose=True)  # Print model information
model.export(format='saved_model',opset=11)  # TODO:

### Additional

<img width="1101" alt="截屏2023-03-25 下午12 20 30" src="https://user-images.githubusercontent.com/100890412/227695674-f3440648-62fe-424e-872b-efd174529a54.png">

**Comment by glenn-jocher** [comment]
@tangruinenu TF SavedModel exports work correctly, they are part of our CI, so our entire CI stack would fail if SavedModel exports failed. I'd recommend running in a verified environment below if you are having issues locally.
See https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule

## Environments

YOLOv8 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/GCP-Quickstart)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/AWS-Quickstart)
- **Docker Image**. See [Docker Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

**Comment by glenn-jocher** [comment]
@tangruinenu I just wanted to follow up and see if you were able to solve your issue. Please let me know if you need any further assistance. Also, keep in mind that you can check our documentation at https://docs.ultralytics.com for more information on YOLOv8.
