### ISSUE TITLE
The x y width height of the yolov10 model output looks like a pixel value. What is the size of the model output?

### ISSUE THREAD

**Issue by lizhiwen19900709** [ultralytics/ultralytics#16136]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The x y width height of the yolov10 model output looks like a pixel value. What is the size of the model output? I tried to normalize by 640*640 and the result was incorrect!

**Comment by lizhiwen19900709** [comment]
Model used is the model in https://github.com/Oil3/yolov10-coreML/releases/tag/yolov10-coreml-pretrained-models download

**Comment by glenn-jocher** [comment]
@lizhiwen19900709 the YOLOv10 model outputs coordinates in pixel values relative to the input image size. Ensure your input image size matches the model's expected size for accurate results. If you're using a different size, adjust the normalization accordingly.
