### ISSUE TITLE
AttributeError: Can't get attribute 'v10DetectLoss' on <module 'ultralytics.utils.loss' from '/usr/local/lib/python3.10/dist-packages/ultralytics/utils/loss.py'>

### ISSUE THREAD

**Issue by roscoekerby** [ultralytics/ultralytics#16146]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

I have trained a YOLO v10 model [best(1).pt] on custom data. I need to convert it to TFLite. 

### Environment

Ultralytics YOLOv8.2.90 🚀 Python-3.10.12 torch-2.4.0+cu121 CPU (Intel Xeon 2.20GHz)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 32.9/107.7 GB disk)

OS                  Linux-6.1.85+-x86_64-with-glibc2.35
Environment         Colab
Python              3.10.12
Install             pip
RAM                 12.67 GB
CPU                 Intel Xeon 2.20GHz
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.7.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.4.0+cu121>=1.8.0
torchvision         ✅ 0.19.0+cu121>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.1.4>=1.1.4
seaborn             ✅ 0.13.1>=0.11.0
ultralytics-thop    ✅ 2.0.6>=2.0.0
torch               ✅ 2.4.0+cu121!=2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

from ultralytics import YOLO
# Load a model
model = YOLO('/content/best (1).pt')

# Export the model
model.export(format='tflite')

### Additional

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-4-6e6c55dcf94b>](https://localhost:8080/#) in <cell line: 3>()
      1 from ultralytics import YOLO
      2 # Load a model
----> 3 model = YOLO('/content/best (1).pt')
      4 
      5 # Export the model

8 frames
[/usr/local/lib/python3.10/dist-packages/torch/serialization.py](https://localhost:8080/#) in find_class(self, mod_name, name)
   1513                     pass
   1514             mod_name = load_module_mapping.get(mod_name, mod_name)
-> 1515             return super().find_class(mod_name, name)
   1516 
   1517     # Load the data (which may in turn use `persistent_load` to load tensors)

AttributeError: Can't get attribute 'v10DetectLoss' on <module 'ultralytics.utils.loss' from '/usr/local/lib/python3.10/dist-packages/ultralytics/utils/loss.py'>

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
Ultralytics has added support for YOLOv10. But the model you trained with the YOLOv10 repo will not work with it. You will have to retrain a new model.

https://docs.ultralytics.com/models/yolov10/
