### ISSUE TITLE
Parameters in C2f and issues with logging output

### ISSUE THREAD

**Issue by YQ0Sun** [ultralytics/ultralytics#16142]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In the C2f module, the number of Bottleneck layers is defined by the parameter n=1 in the module's initialization, which can be adjusted in the YAML file. During training, the logs indicate that there are two Bottleneck layers present in the fourth and sixth layers.
![image](https://github.com/user-attachments/assets/ff31f0ea-1345-4fa4-af99-f895a34eb299)
If you need to change the number of Bottleneck layers, you should modify the YAML file and change the value from 6 to 3. Why is that?
![image](https://github.com/user-attachments/assets/88c9a75b-14f1-435d-8927-bd12b9813d40)

**Comment by Y-T-G** [comment]
It's derived based on `depth` and `repeats`:

https://github.com/ultralytics/ultralytics/blob/main/ultralytics%2Fnn%2Ftasks.py#L909
