### ISSUE TITLE
update read.me file to detail VisualStudio imports for /examples/YOLOv8-ONNXRuntime-CPP project

### ISSUE THREAD

**Issue by harryhancock** [ultralytics/ultralytics#16145]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi, The project at https://github.com/ultralytics/ultralytics/blob/main/examples/YOLOv8-ONNXRuntime-CPP/main.cpp does not have all the Visual Studio includes required to build the project detailed in the read.me file to guide a complete beginner using visual studio.

To be added:
- reference for "onnxruntime_cxx_api.h" in inference.h needs include path: ...\onnxruntime-main\include\onnxruntime\core\session
- reference for opencv in main.cpp needs #include <opencv2/opencv.hpp> at top of file, plus include path of ...\OpenCv
plus the additional library directories and list oif .lib files under the linker project properties settings

### Use case

used by those building the project in visual studio

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@harryhancock thank you for the suggestion. We appreciate your input and encourage you to submit a pull request with these updates to help improve the documentation for Visual Studio users.
