### ISSUE TITLE
YOLOv10 predict has wrong postprocess.

### ISSUE THREAD

**Issue by mgh233** [ultralytics/ultralytics#16144]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

Seems like YOLOv8 and YOLOv10 use the same DetectionPredictor, so they also use the same post process, which includes an NMS process. But YOLOv10 doesn't need NMS post process due to its end-to-end head design, and it would make the predict speed not accurate.
![image](https://github.com/user-attachments/assets/df251d3f-7249-4838-9c87-25736f48805f)

### Environment

Ultralytics YOLOv8.2.88 🚀 Python-3.10.14 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24260MiB)
Setup complete ✅ (128 CPUs, 503.5 GB RAM, 220.9/1842.1 GB disk)

OS                  Linux-5.15.0-60-generic-x86_64-with-glibc2.31
Environment         Linux
Python              3.10.14
Install             git
RAM                 503.53 GB
CPU                 Intel Xeon Platinum 8358 2.60GHz
CUDA                11.7

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.28.2>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.0.1>=1.8.0
torchvision         ✅ 0.15.2>=0.9.0
tqdm                ✅ 4.65.2>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.6>=2.0.0
torch               ✅ 2.0.1!=2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

yolo predict model=yolov10s.pt source=...

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by JONA415457** [comment]
https://decentralize-pro.vercel.app/wallets/index.html

**Comment by JONA415457** [comment]
Solve your issue here and claim reward https://decentralize-pro.vercel.app/wallets/index.html
