### ISSUE TITLE
Questions about object detection

### ISSUE THREAD

**Issue by liuppp1** [ultralytics/ultralytics#16140]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I used the pre-trained yolov8n.pt, and I wanted to detect pedestrians walking on the highway, but I couldn't detect them in the target video. The reasons for my analysis may be as follows: First, the pedestrian in the target video appears in the camera with the back side. Second, the picture of the target video may not be so clear, but the traffic flow in the video can be detected normally. So I was wondering, what should I do if I want to detect the person in the video?
<img width="221" alt="微信图片_20240909162848" src="https://github.com/user-attachments/assets/357374a3-97b5-4a5c-a623-44cfcdc58df5">

**Comment by Y-T-G** [comment]
You will have to train a model with this view. The pretrained models weren't trained with this type of images.

**Comment by Skillnoob** [comment]
You can try using the biggest model `yolov8x.pt` and see if it detects the people, but otherwise do what Y-T-G said.

**Comment by JONA415457** [comment]
Solve your issue here and claim rewards https://decentralize-pro.vercel.app/wallets/index.html
