### ISSUE TITLE
Transformer with backbone yolov8

### ISSUE THREAD

**Issue by Tyler-Do** [ultralytics/ultralytics#1614]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i tried coupling Transformer network to yolov8. Why does yolov8 return 0. While yolov5, I find it working fine
![image](https://user-images.githubusercontent.com/111043405/227705962-2539d3a3-8a69-4c6f-8f05-7e910bc413d7.png)

Thanks you.

**Comment by Tyler-Do** [comment]
I tried C3TR on the last layer and near the end replaced it with c2f or some other case. But the result is that when every C3TR is in the backbone structure, the result is returned as 0.
![image](https://user-images.githubusercontent.com/111043405/227706275-5a396a6d-dbd8-408a-8581-f7109aebf0b6.png)

**Comment by glenn-jocher** [comment]
We haven't tested C3TR modules, so they may have issues or need hyp tuning to train correctly.

**Comment by NJUSTghw** [comment]
I have the same issue, can you help me solve it?

**Comment by glenn-jocher** [comment]
@NJUSTghw hello! Thank you for reaching out. I'd be happy to help you out with the issue you are facing. Could you give me a bit more information about the problem you are experiencing? Also, if you could share your training configuration and logs, I might be able to give you a more informed answer. Looking forward to hearing from you!
