### ISSUE TITLE
Proper CoreML Conversion for YOLOv10

### ISSUE THREAD

**Issue by nicspect** [ultralytics/ultralytics#16157]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

This feature request is an ease of use request. In the older YOLOv8, when you did the conversion, in my case with NMS, the input and output data are way better defined, allowing for better use in xcode. 
![Screenshot 2024-09-09 at 15 20 00](https://github.com/user-attachments/assets/4db32fcb-f2b1-40fb-accd-41514fbf9a7d)

The newer YOLOv10 outputs a MultiArray (Float32 1 × 300 × 6) which is tough for me to use. I have attached images with each example. I also don't have the ability to set the confidence threshold
![Screenshot 2024-09-09 at 15 24 28](https://github.com/user-attachments/assets/e3e5eb87-b6b7-418e-beda-2a466591e756)

Thank you!

### Use case

This feature would be used by anyone looking to use YOLOv10 on iOS through Xcode

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Skillnoob** [comment]
YoloV10 doesn't use NMS, thats why the output is different.

**Comment by JONA415457** [comment]
Kindly solve your issue here and claim your reward https://decentralize-pro.vercel.app/wallets/index.html

**Comment by nicspect** [comment]
@Skillnoob, I understand the output is different. I'm trying to find a way to understand better the MultiArray (Float32 1 × 300 × 6) output. The results in that format are very confusing compared to the coordinates and confidence outputs.
