### ISSUE TITLE
How to make Yolov8-segmatation model convert to tensor-RT INT8 model?

### ISSUE THREAD

**Issue by numidun** [ultralytics/ultralytics#16154]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello!

I want to Yolov8-segmatation model convert to tensor-RT INT8 model.

Before convert, I prepared the dataset by creating a dataset in the form of COCO-seg in roboflow and converting it to the form of yolov8 seg.

I know how to convert to tensor-RT INT 8 model using below code.
out = model.export(format="engine", imgsz=640, dynamic=True, verbose=False, batch=8, workspace=2, int8=True, data="coco8.yaml")

However, I don't know what image to create the data set for calibration as and what .yaml to create.

Do you have any information on this?

**Comment by JONA415457** [comment]
Claim your reward here https://decentralize-pro.vercel.app/wallets/index.html
