### ISSUE TITLE
Fast computation methods in yolov8 tracking

### ISSUE THREAD

**Issue by abhi0928** [ultralytics/ultralytics#16164]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,
I am running some videos to track humans inside the camera and also checking if there is some movement in the tracked object or not, I can do it successfully with accurate results. but I want to reduce the computation time currently I am using it on the thread with 10 videos at a time and it is only using 4-5% of my GPU power, is there a way I can reduce the computation time even if it uses more power of my GPU because it will not be an issue for me?

I really appreciate any help you can provide.

**Comment by Y-T-G** [comment]
Tracking is mostly a CPU bound process. You can try using `tracker=bytetrack.yaml` instead as it would be faster than the default.

**Comment by CharanPrasadK** [comment]
@abhi0928 Try check what are the devices compatible for YOLO models and after initializing the model use 'model.to('cuda')'  to use your gpu if your system is NVIDIA CUDA supportable. Try to check what else keywords are usable other than 'cuda'

**Comment by abhi0928** [comment]
@Y-T-G thanks for your response,
Is there a way I can make tracking algorithm to work with GPU? Where do i need to make changes. Also I will try with bytetrack.

Thanks for your response

**Comment by abhi0928** [comment]
@CharanPrasadK thanks for your response.

I have a Nvidia RTX 3060 12 GB, and I am using model.to('cuda') already. I guess the issue lies in tracking computation as @Y-T-G suggested

**Comment by Y-T-G** [comment]
@abhi0928 Not everything can be run on a GPU. You can try compiling OpenCV with CUDA and see if it improves the speed.
