### ISSUE TITLE
How to use YOLOV8-OBB on deepstream

### ISSUE THREAD

**Issue by kunal-bits-123** [ultralytics/ultralytics#16167]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am able to run yolov8 on deepstream but now I want to do for oriented areal images, I tried my keeping everything same and just using yolov8-obb model but that gave multiple bounding boxes and it could not correctly identify the objects, also the bounding boxes were not oriented. 
For reference I used https://wiki.seeedstudio.com/YOLOv8-DeepStream-TRT-Jetson/

**Comment by glenn-jocher** [comment]
To use YOLOv8-OBB with DeepStream, ensure your model is correctly exported to TensorRT format with `yolo export model=yolov8n-obb.pt format=engine`. Verify that your DeepStream pipeline supports oriented bounding boxes and adjust any post-processing steps accordingly. For detailed guidance, refer to the DeepStream documentation.

**Comment by kunal-bits-123** [comment]
Thanks @glenn-jocher , I am using deepstream 6.3 and had looked in its documentation but I couldn't find required changes to do in my pipeline. Also there is also issue for not taking NMS as its producing many overlapping bounding boxes which are not oriented as well. For the model, I have used yolov8x-obb.onnx . If you can suggest me some resources or help it would be really helpful.

**Comment by glenn-jocher** [comment]
@kunal-bits-123 for DeepStream integration with YOLOv8-OBB, ensure your pipeline supports custom NMS for oriented bounding boxes. You might need to implement a custom plugin for this. Check NVIDIA forums or DeepStream community resources for guidance on handling OBB models.

**Comment by kunal-bits-123** [comment]
Thank you very much for your assistance. I will consult the NVIDIA forums and DeepStream community resources for further guidance. Should I have any additional questions or need further clarification, I will reach out as necessary

**Comment by glenn-jocher** [comment]
You're welcome! Feel free to reach out if you have more questions. Good luck with your project!
