### ISSUE TITLE
Make Enough FPS with Multiple Models for Multiple Stream 

### ISSUE THREAD

**Issue by john09282922** [ultralytics/ultralytics#16160]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Dear All,

I need your help to make real-time processing with yolo models.
My custom models have 6 model and all models go through each CCTV camera.
Do you have an idea? I am considering to use Thread and Batch inference method for object detection.
If you have an idea, can you give me an example code.

Thanks,
John

### Additional

![화면 캡처 2024-09-07 231610](https://github.com/user-attachments/assets/f3ec4864-f3cb-4822-b034-c016f73083bc)
This is my code, but only one model run by one stream.

**Comment by glenn-jocher** [comment]
@john09282922 for real-time processing with multiple YOLO models, consider using Python's `threading` module to instantiate a separate model within each thread. This ensures thread safety and allows each model to process a different stream concurrently. For more details, you can refer to our guide on thread-safe inference at https://docs.ultralytics.com/guides/yolo-thread-safe-inference/.

**Comment by Y-T-G** [comment]
You can try using Triton Inference Server.

https://docs.ultralytics.com/guides/triton-inference-server/

But if your GPU has reached maximum utilization, then threading won't help much. You will have to drop some frames to keep up.

**Comment by Y-T-G** [comment]
Use Triton Inference Server

**Comment by glenn-jocher** [comment]
@john09282922 @Y-T-G no, **you do not need 3rd party tools to run multi-stream inference**. We offer this directly via the `ultralytics` package using our own custom asynchronous StreamLoader:
https://docs.ultralytics.com/modes/predict/#inference-sources

<img width="2031" alt="Screenshot 2024-09-18 at 09 15 03" src="https://github.com/user-attachments/assets/a8d20df3-bad2-4199-8454-177cc01b141a">
