### ISSUE TITLE
Train custom Dataset with fixed H:480 but different Width: 600 - 850 

### ISSUE THREAD

**Issue by Nadayz** [ultralytics/ultralytics#16166]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I have a custom dataset to be trained using Yolov8.
All images in the dataset have a fixed height of 480.
and different widths from 600 to 850.

The problem here is that Yolov8 resizes the longer side to 640 and considers it as image height (**but the longer side of the image is width in my case**)
So, it is like I'm training a rotated image, right?

My question is:
What are the preferred training settings to handle this situation ?

**Comment by Y-T-G** [comment]
What do you mean it considers it as height and what difference does it make?

The images will always be resized to fit the defined `imgsz`. The longer side is resized because that's how you preserve the aspect ratio.
