### ISSUE TITLE
Save detected person's image if source is camera stream

### ISSUE THREAD

**Issue by mriamnobody** [ultralytics/ultralytics#1617]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there a way to capture and save an image of a scene when a person is detected in case a camera stream is used as a source? I used `save = True` which resulted in an unplayable video file.

I used the following code:

```
from ultralytics import YOLO

model = YOLO("yolov8n.yaml") 
model = YOLO("yolov8n.pt")  

model.train(data="coco128.yaml", epochs=3) 

metrics = model.val() 
results = model("rtsp://username:password@IP:PORT/cam/realmonitor?channel=1&subtype=0", save = True)  
success = model.export(format="onnx") 
```

**Comment by glenn-jocher** [comment]
@mriamnobody yes, you can use `stream=True` to produce a generator and then handle Results frame by frame. See https://docs.ultralytics.com/modes/predict/

**Comment by mriamnobody** [comment]
> @mriamnobody yes, you can use `stream=True` to produce a generator and then handle Results frame by frame. See https://docs.ultralytics.com/modes/predict/

Thank you, @glenn-jocher. However, I've encountered an issue. My camera is pointed at a small garden within my compound, and when I run yolo prediction, plants are continuously detected. Saving each detected plant image is not useful. Is there a specific argument or parameter that would save images only when a human is detected? I've read the documentation available at the URL you provided, but I couldn't find it (please forgive me, as I am a beginner).

**Comment by glenn-jocher** [comment]
@mriamnobody the default commands are meant as demos to show you what's possible. You can infinitely customize your own workflows by running YOLO models in your own custom Python code, i.e.:

```
results = model(source=..., stream=True)

for r in results:
    if r[0].class == 0:  # person
        # do anything here
```

See https://docs.ultralytics.com/modes/predict/ for details

**Comment by mriamnobody** [comment]
Hello @glenn-jocher. I have tried to implement to save image if a human is detected, the script is working fine but the images are not being saved if a human is detected 

```
import cv2
from ultralytics import YOLO

img_dir = "C:\\Users\\rosha\\Downloads\\Compressed\\ultralytics-main\\humandetections"

model = YOLO("yolov8n.yaml") 
model = YOLO("yolov8n.pt") 


model.train(data="coco128.yaml", epochs=3) 
metrics = model.val() 
results = model("rtsp://username:password@IP:PORT/cam/realmonitor?channel=1&subtype=0", stream = True, save = True) 
success = model.export(format="onnx") 

for r in results:
    if 0 in r[0].boxes.cls: 
        img_rgb = cv2.cvtColor(r['img'], cv2.COLOR_BGR2RGB)
        output_file = f"{img_dir}/human_detected_{r['frame']}.png"
        cv2.imwrite(output_file, img_rgb)
```

**Comment by mriamnobody** [comment]
@glenn-jocher @AyushExel @plashchynski @onuralpszr @Laughing-q

**Comment by mriamnobody** [comment]
@bogdan-galileo @developer0hye @alexstoken @kalenmike @hedrergudene

**Comment by alexstoken** [comment]
There is no 'img' property in the results object. See https://docs.ultralytics.com/modes/predict/#video-formats .

Im mobile and can't test this now, but you probably need something like 

`img = r.orig_im`

And you probably don't need to do the colorspace conversion.

**Comment by mriamnobody** [comment]
Thank you @alexstoken for your response. I tried reading the officiL documentation but as a beginner it isn't making much sense to me. Thank you for pointing out the colorspace conversion.

**Comment by mriamnobody** [comment]
The source is a IP cmaera stream.

**Comment by pderrenger** [comment]
Understood! When working with an IP camera stream, you can iterate through the results to save the images when a person is detected. Here's an adapted version of your code with the necessary corrections for saving images:

```python
import cv2
from ultralytics import YOLO

img_dir = "C:\\Users\\rosha\\Downloads\\Compressed\\ultralytics-main\\humandetections"

model = YOLO("yolov8n.pt")

results = model("rtsp://USERNAME:Password @mriamnobody:PORT/cam/realmonitor?channel=1&subtype=0", stream=True)

for r in results.imgs:
    if 0 in r['pred']: 
        output_file = f"{img_dir}/human_detected_{r['frame']}.png"
        cv2.imwrite(output_file, r['img'])
```

In the above code:
- We use `YOLO("yolov8n.pt")` to load the YOLOv8 model.
- Setting `stream=True` in `results = model(..., stream=True)` generates a generator, which we iterate through to access individual frames and their predictions.
- For each frame, we check if a person is detected (`if 0 in r['pred']` where 0 represents the class index for a person).
- Using `cv2.imwrite(output_file, r['img'])`, we save the frame as an image if a person is detected.

Please give this code a try and let me know if it works for you!

**Comment by mriamnobody** [comment]
> Understood! When working with an IP camera stream, you can iterate through the results to save the images when a person is detected. Here's an adapted version of your code with the necessary corrections for saving images:
> 
> ```python
> import cv2
> from ultralytics import YOLO
> 
> img_dir = "C:\\Users\\rosha\\Downloads\\Compressed\\ultralytics-main\\humandetections"
> 
> model = YOLO("yolov8n.pt")
> 
> results = model("rtsp://USERNAME:Password @mriamnobody:PORT/cam/realmonitor?channel=1&subtype=0", stream=True)
> 
> for r in results.imgs:
>     if 0 in r['pred']: 
>         output_file = f"{img_dir}/human_detected_{r['frame']}.png"
>         cv2.imwrite(output_file, r['img'])
> ```
> 
> In the above code:
> 
> * We use `YOLO("yolov8n.pt")` to load the YOLOv8 model.
> * Setting `stream=True` in `results = model(..., stream=True)` generates a generator, which we iterate through to access individual frames and their predictions.
> * For each frame, we check if a person is detected (`if 0 in r['pred']` where 0 represents the class index for a person).
> * Using `cv2.imwrite(output_file, r['img'])`, we save the frame as an image if a person is detected.
> 
> Please give this code a try and let me know if it works for you!

Thank you @pderrenger for helping me with my issue. I tried your code but got an error:
```
WARNING  Ultralytics settings reset to default values. This may be due to a possible problem with your settings or a recent ultralytics package update.
View settings with 'yolo settings' or at 'C:\Users\rosha\AppData\Roaming\Ultralytics\settings.yaml'
Update settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'.
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8l.pt to 'yolov8l.pt'...
100%|█████████████████████████████████████████████████████████████████████████████| 83.7M/83.7M [00:24<00:00, 3.52MB/s]
Traceback (most recent call last):
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\script.py", line 10, in <module>
    for r in results.imgs:
AttributeError: 'generator' object has no attribute 'imgs'
```

**Comment by mriamnobody** [comment]
@pderrenger I removed `imgs` from the line:

`for r in results.imgs:`

and got the following error:

```
1/1: rtsp://USERNAME:Password @mriamnobody:PORT/cam/realmonitor?channel=1&subtype=0... Success  (inf frames of shape 2688x1520 at 20.00 FPS)

Traceback (most recent call last):
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\script.py", line 11, in <module>
    if 0 in r['pred']:
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\engine\results.py", line 108, in __getitem__
    return self._apply('__getitem__', idx)
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\engine\results.py", line 144, in _apply
    setattr(r, k, getattr(v, fn)(*args, **kwargs))
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\ultralytics\engine\results.py", line 63, in __getitem__
    return self.__class__(self.data[idx], self.orig_shape)
IndexError: too many indices for tensor of dimension 2
Exception ignored in: <generator object BasePredictor.stream_inference at 0x00000213B2E7B1B0>
Traceback (most recent call last):
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\vt\lib\site-packages\torch\utils\_contextlib.py", line 44, in generator_context
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\vt\lib\site-packages\torch\autograd\grad_mode.py", line 270, in clone
  File "C:\Users\rosha\Downloads\Compressed\ultralytics-main\vt\lib\site-packages\torch\autograd\grad_mode.py", line 251, in __init__
AttributeError: 'NoneType' object has no attribute '_jit_internal'
```
