### ISSUE TITLE
In the segmentation task, the self-made data labels have accurate true value contours, but the contours are not accurate during training

### ISSUE THREAD

**Issue by litengfeigithub** [ultralytics/ultralytics#16178]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I created my own dataset in the coco-seg8 format. The ground truth bounding boxes are very accurate, but during training, the contours shown in train0 and train1 images are not accurate, with some boundaries being offset. What could be the reason for this? Additionally, where can I find code to draw and fill polygons from labels onto images? I couldn't find this code in the repository.

**Comment by Y-T-G** [comment]
Can you show examples?

The `polygon2mask` code is here:

https://github.com/ultralytics/ultralytics/blob/e97782943b7b707ea2c9ddd65e1e80654ee77823/ultralytics/data/utils.py#L169

**Comment by litengfeigithub** [comment]
Thank you for your response. The logo in Image 1 is one I created myself. The mask and polygon outlines are accurate, but during training, there was some shift in image effects between train0 and the inference results. I would like to know the reason for this. Could it be due to resizing the images, which might have affected the accuracy of the mask? I hope you can help. Thank you!
![111](https://github.com/user-attachments/assets/1ef471d7-963a-4a48-879a-240e9454f283)
![222](https://github.com/user-attachments/assets/54a63473-88e6-4219-bd32-b759b5f119fe)
![333](https://github.com/user-attachments/assets/5f3933f5-5593-44ba-9318-ef0fe036bad1)
![444](https://github.com/user-attachments/assets/15e8ceea-3304-48ab-b003-58c5fdd599dd)

**Comment by litengfeigithub** [comment]
Thank you for your response. The logo in Image 1 is one I created myself. The mask and polygon outlines are accurate, but during training, there was some shift in image effects between train0 and the inference results. I would like to know the reason for this. Could it be due to resizing the images, which might have affected the accuracy of the mask? I hope you can help. Thank you!
![111](https://github.com/user-attachments/assets/1955bb82-4445-4bd2-93a9-2a34a667f44d)
![222](https://github.com/user-attachments/assets/ebb3852d-06cd-429f-93b2-fc3e301ca3dc)
![333](https://github.com/user-attachments/assets/68353b14-1d46-4343-9c04-deacd3b55a52)
![555](https://github.com/user-attachments/assets/5fd41a57-b804-42dd-aab1-6ba91ec7baf4)

**Comment by litengfeigithub** [comment]
During the training process, the boundary of H shifted.
![666](https://github.com/user-attachments/assets/b9e1d820-b60f-4deb-936b-e3e26827886a)
![777](https://github.com/user-attachments/assets/e75aacf9-27db-4a04-8dab-b81ab74c30b7)

**Comment by litengfeigithub** [comment]
我试过了，但是多边形轮廓框还是有一些会偏移。我现在看train0，train1里面的有一些真值会发生偏移，box框不是很准确，所以我怀疑是不是训练的过程中在哪里对真值进行了处理，导致没有原本那样准确。请问您知道在训练过程中在图片中将box在图片中画出来的代码在哪里么？
![Uploading 888.png…]()

**Comment by litengfeigithub** [comment]
I have tried, but there are still some polygonal bounding boxes that may be offset. I am currently looking at train0 and train1, and some of the truth values in them may be offset. The box boxes are not very accurate, so I suspect that the truth values may have been processed somewhere during the training process, which may have caused them to be less accurate than before. Do you know where the code for drawing the box in the image during the training process is located?
![888](https://github.com/user-attachments/assets/78486325-e906-4a30-83e2-096cd5838145)

**Comment by Y-T-G** [comment]
https://github.com/ultralytics/ultralytics/blob/17477066ec2fd61d08652a22897e23d2040ff3e6/ultralytics/models/yolo/segment/train.py#L47

**Comment by litengfeigithub** [comment]
Thank you very much

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions, feel free to ask.

**Comment by litengfeigithub** [comment]
I would like to ask if the model training will select image size and resize images, such as imgsz=640. I would like to know how this resizing is done and where the code is. Thank you for helping me

**Comment by glenn-jocher** [comment]
Yes, the model resizes images to the specified `imgsz` during training. You can find the resizing code in the data loading and preprocessing sections of the repository.
