### ISSUE TITLE
Deploying the YOLOv10 model on Android using the TFLite library gives inaccurate results?

### ISSUE THREAD

**Issue by anhquyetnguyen** [ultralytics/ultralytics#16179]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/user-attachments/assets/7b451fe9-412b-4698-8ccb-f56ee3c163c0)
After a successful conversion, I tested the TFLite model and it produced good results. However, when deploying the TFLite model on Android, the results were very different and it couldn’t detect any objects with the input I used for testing on the PC.

**Comment by anhquyetnguyen** [comment]
But when I download the yolov10n.pt model trained on the coco dataset from the website https://docs.ultralytics.com/models/yolov10/#performance, and then follow the steps to convert it to tflite, the results on PC and mobile are the same. Can you explain why?

**Comment by Y-T-G** [comment]
Can you provide the output after running this command in terminal: `yolo checks`?

**Comment by anhquyetnguyen** [comment]
@Y-T-G here
![image](https://github.com/user-attachments/assets/49ef72fb-a694-4d64-a228-877fc092a004)
I don't know why running my model on mobile gives results that differ significantly from those on PC. The model I downloaded from [this link](https://docs.ultralytics.com/models/yolov10/#performance) and exported to tflite gives the same results on both PC and Android mobile

**Comment by Y-T-G** [comment]
@anhquyetnguyen So your `tflite` model works with Ultralytics, but not on Android?

**Comment by Y-T-G** [comment]
@anhquyetnguyen It could be something wrong with your Android code. Because if it works with Ultralytics, then there's no issue in the model.

**Comment by anhquyetnguyen** [comment]
@Y-T-G 
However, I downloaded your yolov10n.pt file, exported it to TFLite format, and performed predictions in Android code, and the results were the same as when using Ultralytics on PC.

**Comment by iamxiaojuan** [comment]
@Y-T-G I encountered the same problem with good results in the Ultralytics project and unsatisfactory results in android after exporting tflite format. In fact, I wonder if the number of training sets is not enough. Two categories. I've only labeled a hundred or so training sets.

**Comment by Y-T-G** [comment]
@iamxiaojuan Are you talking about the performance on the same images as you have in val set, or different images?

100 images isn't enough for generalization

**Comment by iamxiaojuan** [comment]
The image detected in android is one of the ones that belongs to the training set.
I will try to annotate more images in the future and give feedback after that. Thank you for your reply.

**Comment by Y-T-G** [comment]
The postprocessing of YOLOv10 is different from other YOLOs. So you should make sure you do it differently.
