### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'box' when trying to train YOLOv8 on pytorch lightning using v8DetectionLoss.

### ISSUE THREAD

**Issue by Vicks0712** [ultralytics/ultralytics#16189]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello @ultralytics team,

I am trying to train the Yolov8 model with a more customized trainer, instead of using the one provided by the default library. I'm trying to reproduce the loss calculation for this model using the v8DetectionLoss class, but it always gives this same error:

```
Cell In[21], line 28, in YOLOv8LightningModule.training_step(self, batch, batch_idx)
     25 targets['bboxes'] = targets['bboxes'].to(self.device)
     27 predictions = self.forward(images)
---> 28 loss = self.compute_loss(predictions, targets)
     30 self.train_loss.append(loss.item())
     32 self.log('train_loss', loss, on_step=True, on_epoch=True, prog_bar=True)

Cell In[21], line 16, in YOLOv8LightningModule.compute_loss(self, predictions, targets)
     12 def compute_loss(self, predictions, targets):
     13     """
     14     Calculates the loss across multiple scales from both 'one2many' and 'one2one'.
     15     """
---> 16     loss = loss_fn(predictions, targets)
     17     return loss

File ~\AppData\Local\pypoetry\Cache\virtualenvs\hermes-video--0vDOw8A-py3.11\Lib\site-packages\ultralytics\utils\loss.py:243, in v8DetectionLoss.__call__(self, preds, batch)
    238     target_bboxes /= stride_tensor
    239     loss[0], loss[2] = self.bbox_loss(
    240         pred_distri, pred_bboxes, anchor_points, target_bboxes, target_scores, target_scores_sum, fg_mask
    241     )
--> 243 loss[0] *= self.hyp.box  # box gain
    244 loss[1] *= self.hyp.cls  # cls gain
    245 loss[2] *= self.hyp.dfl  # dfl gain

AttributeError: 'dict' object has no attribute 'box'
```

And I think it comes from this part of the code in v8DetectionLoss class, in utils/loss.py:

```
self.hyp = model.args
```

The code that I'm using is this one, including a custom dataloader and a custom Trainer using pytorch lightining:

dataloader:
```
class YOLOv8Dataset(Dataset):
    def __init__(self, images_dir, labels_dir, transform=None):
        self.images_dir = images_dir
        self.labels_dir = labels_dir
        self.image_paths = list(Path(images_dir).glob("*.png"))
        self.transform = transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = str(self.image_paths[idx])
        label_path = str(Path(self.labels_dir) / (Path(img_path).stem + ".txt"))

        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        # Resize and normalize the image
        resized_image = cv2.resize(image, (640, 640))
        normalized_image = resized_image / 255.0
        image_tensor = torch.from_numpy(normalized_image).permute(2, 0, 1).float()

        # Read the labels from the text file
        with open(label_path, 'r') as f:
            labels = np.array([list(map(float, line.strip().split())) for line in f])

        # Extract classes and bounding boxes from the labels
        if len(labels) > 0:
            cls = labels[:, 0]  # First column is the class
            bboxes = labels[:, 1:]  # The other columns are the bounding box coordinates
        else:
            cls = np.array([])  # If there are no labels
            bboxes = np.array([])

        target = {
            'batch_idx': idx,  # Add the batch index
            'cls': torch.tensor(cls, dtype=torch.float32),  # Classes
            'bboxes': torch.tensor(bboxes, dtype=torch.float32)  # Bounding boxes
        }

        return image_tensor, target

train_dataset = YOLOv8Dataset(images_dir="./test/data/images/", labels_dir=Path("./test/data/labels/"))

def collate_fn(batch):
    images = []
    batch_targets = {'batch_idx': [], 'cls': [], 'bboxes': []}

    for i, (image, target) in enumerate(batch):
        images.append(image)

        # Add the data from each image to the corresponding batches
        batch_targets['batch_idx'].append(torch.full((len(target['cls']),), i))  # Batch indices
        batch_targets['cls'].append(target['cls'])
        batch_targets['bboxes'].append(target['bboxes'])

    # Concatenate the data so PyTorch can handle it
    batch_targets['batch_idx'] = torch.cat(batch_targets['batch_idx'])
    batch_targets['cls'] = torch.cat(batch_targets['cls'])
    batch_targets['bboxes'] = torch.cat(batch_targets['bboxes'])

    return torch.stack(images, dim=0), batch_targets


train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, collate_fn=collate_fn)
```

Loss function (v8DetectionLoss):
```
model = YOLO("yolov8n.pt").to(device)
pytorch_model = model.model.train()
loss_fn = v8DetectionLoss(pytorch_model)
```

Custom Trainer:

```
class YOLOv8LightningModule(pl.LightningModule):
    def __init__(self, model, lr=1e-3):
        super(YOLOv8LightningModule, self).__init__()
        self.model = model
        self.lr = lr
        self.train_loss = []  #
        self.val_loss = []

    def forward(self, x):
        return self.model(x)

    def compute_loss(self, predictions, targets):
        loss = loss_fn(predictions, targets)
        return loss

    def training_step(self, batch, batch_idx):
        images, targets = batch

        images = images.to(self.device)
        targets['batch_idx'] = targets['batch_idx'].to(self.device)
        targets['cls'] = targets['cls'].to(self.device)
        targets['bboxes'] = targets['bboxes'].to(self.device)

        predictions = self.forward(images)
        loss = self.compute_loss(predictions, targets)

        self.train_loss.append(loss.item())

        self.log('train_loss', loss, on_step=True, on_epoch=True, prog_bar=True)
        return loss

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=self.lr)
        return optimizer
```

Here are the relevant versions of my dependencies:

```
PyTorch: 2.4.0
torchvision: 0.19.0
ultralytics: 8.1.34
numpy: 1.26.4
```

Thank you very much in advance for any kind of help!

**Comment by Y-T-G** [comment]
You should ask it on the YOLOv10 repo because that's the code you're using.

**Comment by Y-T-G** [comment]
Ultralytics `8.1.34` had no official support for YOLOv10.

So it seems like you're using the code from the YOLOv10 repo. So you should probably ask over there.

**Comment by Vicks0712** [comment]
S

> Ultralytics `8.1.34` had no official support for YOLOv10.
> 
> So it seems like you're using the code from the YOLOv10 repo. So you should probably ask over there.

What a mistake, I'll do it now!! Thanks

**Comment by Vicks0712** [comment]
> Because the code you're using is not from the official ultralytics. It's from https://github.com/THU-MIG/yolov10
> 
> So any issues with the code should be directed to the repo where you got the code from.

Hello again, I have replicated the code again but using the yolov8 model, and it seems to give the same error.

**Comment by Y-T-G** [comment]
You need to set the weights for the box losses.

```
model.model.args["box"] = 7.5
```

https://github.com/ultralytics/ultralytics/blob/2a17462367f59307cc4dd5477bfac68c7bb3352c/ultralytics/cfg/default.yaml#L97-L101

**Comment by LingjieBao1998** [comment]
`from ultralytics.utils.tal import make_anchors

# ref:https://github.com/cfotache/pytorch_custom_yolo_training/tree/master


class v8DetectionLoss_v2(v8DetectionLoss):
    """Criterion class for computing training losses."""
    def __init__(self, model, tal_topk=10, box_weight=7.5, cls_wight=0.5, dfl_weight=1.5):
        # Ensure the model is de-paralleled if needed
        super().__init__(model, tal_topk=tal_topk)  # Call the parent class' __init__ method
        self.box_weight = box_weight
        self.cls_wight = cls_wight
        self.dfl_weight = dfl_weight


    def __call__(self, preds, batch):
        """Calculate the sum of the loss for box, cls and dfl multiplied by batch size."""
        loss = torch.zeros(3, device=self.device)  # box, cls, dfl
        feats = preds[1] if isinstance(preds, tuple) else preds
        pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
            (self.reg_max * 4, self.nc), 1
        )

        pred_scores = pred_scores.permute(0, 2, 1).contiguous()
        pred_distri = pred_distri.permute(0, 2, 1).contiguous()

        dtype = pred_scores.dtype
        batch_size = pred_scores.shape[0]
        imgsz = torch.tensor(feats[0].shape[2:], device=self.device, dtype=dtype) * self.stride[0]  # image size (h,w)
        anchor_points, stride_tensor = make_anchors(feats, self.stride, 0.5)

        # Targets
        targets = torch.cat((batch["batch_idx"].view(-1, 1), batch["cls"].view(-1, 1), batch["bboxes"]), 1)
        targets = self.preprocess(targets.to(self.device), batch_size, scale_tensor=imgsz[[1, 0, 1, 0]])
        gt_labels, gt_bboxes = targets.split((1, 4), 2)  # cls, xyxy
        mask_gt = gt_bboxes.sum(2, keepdim=True).gt_(0.0)

        # Pboxes
        pred_bboxes = self.bbox_decode(anchor_points, pred_distri)  # xyxy, (b, h*w, 4)
        # dfl_conf = pred_distri.view(batch_size, -1, 4, self.reg_max).detach().softmax(-1)
        # dfl_conf = (dfl_conf.amax(-1).mean(-1) + dfl_conf.amax(-1).amin(-1)) / 2

        _, target_bboxes, target_scores, fg_mask, _ = self.assigner(
            # pred_scores.detach().sigmoid() * 0.8 + dfl_conf.unsqueeze(-1) * 0.2,
            pred_scores.detach().sigmoid(),
            (pred_bboxes.detach() * stride_tensor).type(gt_bboxes.dtype),
            anchor_points * stride_tensor,
            gt_labels,
            gt_bboxes,
            mask_gt,
        )

        target_scores_sum = max(target_scores.sum(), 1)

        # Cls loss
        # loss[1] = self.varifocal_loss(pred_scores, target_scores, target_labels) / target_scores_sum  # VFL way
        loss[1] = self.bce(pred_scores, target_scores.to(dtype)).sum() / target_scores_sum  # BCE

        # Bbox loss
        if fg_mask.sum():
            target_bboxes /= stride_tensor
            loss[0], loss[2] = self.bbox_loss(
                pred_distri, pred_bboxes, anchor_points, target_bboxes, target_scores, target_scores_sum, fg_mask
            )
        
        try:
            loss[0] *= self.hyp.box  # box gain
        except:
            loss[0] *= self.box_weight
        try:
            loss[1] *= self.hyp.cls  # cls gain
        except:
            loss[1] *= self.cls_wight
        
        try:
            loss[2] *= self.hyp.dfl  # dfl gain
        except:
            loss[2] *= self.dfl_weight

        return loss.sum(), loss.detach()  # loss(box, cls, dfl)`

**Comment by glenn-jocher** [comment]
The issue you're experiencing is that the `v8DetectionLoss` class expects certain hyperparameters in the model's `args` attribute, but they aren't present in your setup. The error occurs because `self.hyp` (which references `model.args`) doesn't have a 'box' attribute needed for the loss calculation.

You have two options to solve this:

1. Add the required hyperparameters to your model before initializing the loss function:
```python
model.model.args = {}  # If args doesn't exist yet
model.model.args["box"] = 7.5
model.model.args["cls"] = 0.5
model.model.args["dfl"] = 1.5
loss_fn = v8DetectionLoss(pytorch_model)
```

2. Use the custom `v8DetectionLoss_v2` class provided by @LingjieBao1998, which handles missing hyperparameters with default values.

The first approach is simpler and works fine if you just need to use the loss function as-is. The second approach gives you more flexibility for customization in your PyTorch Lightning implementation.

**Comment by glenn-jocher** [comment]
Looking at your implementation, I see the issue. The `v8DetectionLoss` expects `model.args` to be an object with attributes (accessed with dot notation), not a dictionary (accessed with bracket notation). 

Your approach with the custom `V8DetectionLossArgs` class is correct. However, for a cleaner solution that maintains compatibility with the existing Ultralytics structure, you can use `SimpleNamespace`:

```python
from types import SimpleNamespace
from ultralytics.utils.loss import v8DetectionLoss

model = YOLO("yolov8n.pt").model.train()
model.args = SimpleNamespace(box=7.5, cls=0.5, dfl=1.5)
loss_fn = v8DetectionLoss(model)
```

This creates an object where `model.args.box`, `model.args.cls`, and `model.args.dfl` are accessible as attributes, which is exactly what the [v8DetectionLoss implementation](https://docs.ultralytics.com/reference/utils/loss/#ultralytics.utils.loss.v8DetectionLoss.__call__) expects when it accesses `self.hyp.box`, `self.hyp.cls`, and `self.hyp.dfl`.
