### ISSUE TITLE
Filtering on classes

### ISSUE THREAD

**Issue by jobjansweijer** [ultralytics/ultralytics#16198]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Based on the classes argument mentioned here: https://docs.ultralytics.com/modes/predict/#inference-arguments

I'm trying to use my yolo predict model (based on yolov8n) to predict on a limited number of the classes it is trained on. I've tried the variations below, but in each case, the model returns a prediction based on all classes.

**How do I correctly get the model to only return predictions for a subset of specified classes?**

Off course, I could get the model to return all predictions, and then filter the results myself afterwards, but I'm wondering if there is a more direct way to do it. I'm hoping the model might be faster if it is possible to limit the number of outcomes on forehand?

**The code:**
```
from ultralytics import YOLO

model = YOLO('static/yolo_model.pt')
image_path = 'static/dataset/240711-130908-001_crop_cam0.jpg'

def print_prediction_result(prediction):
   for pred in prediction:
    print(f'conf: {pred.probs.top5conf}')
    print(f'ids: {pred.probs.top5}\n')

#Option 1: No filtering
prediction = model.predict(image_path, verbose=False) 

classes = 32

#Option 2: Filtering only int
prediction = model.predict(image_path, classes=classes, verbose=False) 
print_prediction_result(prediction)

#Option 3: Filtering only int, with list, like in documentation
prediction = model.predict(image_path, classes=list[classes], verbose=False) 
print_prediction_result(prediction)

classes = [0,1,2,3,4]

#Option 4: Filtering on array, 
prediction = model.predict(image_path, classes=classes, verbose=False) 
print_prediction_result(prediction)

#Option 5: Filtering on array, with list, like in documentation
prediction = model.predict(image_path, classes=list[classes], verbose=False)
print_prediction_result(prediction)
```

### Additional

**The result**
(identical for each)

```
conf: tensor([0.5759, 0.3816, 0.0183, 0.0067, 0.0036])
ids: [515, 533, 501, 470, 710]

conf: tensor([0.5759, 0.3816, 0.0183, 0.0067, 0.0036])
ids: [515, 533, 501, 470, 710]

conf: tensor([0.5759, 0.3816, 0.0183, 0.0067, 0.0036])
ids: [515, 533, 501, 470, 710]

conf: tensor([0.5759, 0.3816, 0.0183, 0.0067, 0.0036])
ids: [515, 533, 501, 470, 710]
```

**Comment by Skillnoob** [comment]
The correct and simplest way to do it is to filter the classes by adding `classes=[class_id_1, class_id_2, ...]` to the prediction function.
It will not make the model run faster since they are filtered out during postprocessing, well maybe NMS will speed up a little.

This example code filters for just people:
```python
from ultralytics import YOLO, ASSETS

model = YOLO("yolov8n.pt")
image = ASSETS / 'bus.jpg'

result = model.predict(image, classes=[0], save=True)
```

Result:
![bus](https://github.com/user-attachments/assets/80b41145-9e68-4afc-8c60-c1a626f1e008)

**Comment by Skillnoob** [comment]
I don't think its supported for classification since the classify predictor doesn't take in the classes argument.
