### ISSUE TITLE
Using ultralytics library with custom model(PeopleNet.onnx) 

### ISSUE THREAD

**Issue by HuseyinSaidKoca** [ultralytics/ultralytics#16197]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can we use this model with ultralytics for inference or can we make it ultralytics compatible (like in scikit-learn implement fit and traind method and voila you can use your custom model with scikit learn features)

**Comment by HuseyinSaidKoca** [comment]
@Y-T-G

**Comment by Y-T-G** [comment]
You can't do that. Ultralytics library is designed to work with models trained with Ultralytics.
