### ISSUE TITLE
How to use Ultralytics to calculate the parameters and FLOPs of YOLOv10？

### ISSUE THREAD

**Issue by Tissum** [ultralytics/ultralytics#16207]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, as stated by THU-MIG, the one-to-many head in YOLOv10 is not needed during inference, so this part of params and FLOPs can be ignored. [https://github.com/THU-MIG/yolov10/issues/178](url)
They provide a script that can correctly calculate the parameters and FLOPs of YOLOv10, as shown below:
![{H43H%MOAJPWSAHVESMKMO](https://github.com/user-attachments/assets/eed8a217-53b4-46c8-96a9-dc2067c09a09)
This is effective in YOLOv10 of THU-MIG, and I can obtain the following results:
![image](https://github.com/user-attachments/assets/0a6d6d67-de4b-4b4e-9ca6-e183fb41584a)
However, when I used the script in Ultralytics, I was unable to obtain FLOPs for YOLOv10.
As shown below:
![image](https://github.com/user-attachments/assets/b3c37ee7-c29e-4602-8af4-2e4dca0f37c5)
![image](https://github.com/user-attachments/assets/a567ad1f-e6a9-4f1a-aff4-e061ae46a900)

**Comment by Y-T-G** [comment]
```python
from ultralytics import YOLO
from torch.nn import ModuleList, Identity

model = YOLO("yolov10n.pt")

model.model.model[-1].cv2 = ModuleList([Identity() for i in model.model.model[-1].cv2])
model.model.model[-1].cv3 = ModuleList([Identity() for i in model.model.model[-1].cv3])

model.fuse()

print(model.info())
````

**Comment by Tissum** [comment]
Hi! @Y-T-G 
Thank you very much, it has been very helpful to me. I can now correctly calculate the parameters and FLOPs of YOLOv10.
