### ISSUE TITLE
Why was the input set in the test was 640, but the picture was resize to 576x640, and the picture was not resize to 640x640 during the training?

### ISSUE THREAD

**Issue by tangruinenu** [ultralytics/ultralytics#1620]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why was the input set in the test was 640, but the picture was resize to 576x640, and the picture was not resize to 640x640 during the training? This is critical because I want to deploy YOLOV8.
<img width="633" alt="截屏2023-03-25 下午8 36 05" src="https://user-images.githubusercontent.com/100890412/227717643-829e9308-1622-44f5-b12f-60bc5c8b2a2e.png">

**Comment by glenn-jocher** [comment]
@tangruinenu rectangular inference for reduced FLOPs. 

If you have a rectangle why would you want to waste FLOPs running YOLO on extra pixels that aren't part of your image?
