### ISSUE TITLE
deafult.yaml Issues

### ISSUE THREAD

**Issue by duhyeonlee** [ultralytics/ultralytics#16202]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

It was working perfectly fine before I changed my laptop. Even after I setup the same environment in Jupyter Notebook at the new laptop, it started to show an error like this:

Exception in thread Thread-42:
Traceback (most recent call last):
  File "C:\Users\alee\AppData\Local\anaconda3\envs\yolo_env\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\alee\AppData\Local\anaconda3\envs\yolo_env\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\alee\AppData\Local\Temp\ipykernel_21288\520561643.py", line 37, in track_video
  File "C:\Users\alee\AppData\Local\anaconda3\envs\yolo_env\lib\site-packages\ultralytics\engine\model.py", line 614, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "C:\Users\alee\AppData\Local\anaconda3\envs\yolo_env\lib\site-packages\ultralytics\engine\model.py", line 567, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "C:\Users\alee\AppData\Local\anaconda3\envs\yolo_env\lib\site-packages\ultralytics\engine\predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "C:\Users\alee\AppData\Local\anaconda3\envs\yolo_env\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\alee\AppData\Local\anaconda3\envs\yolo_env\lib\site-packages\ultralytics\engine\predictor.py", line 262, in stream_inference
    self.run_callbacks("on_predict_postprocess_end")
  File "C:\Users\alee\AppData\Local\anaconda3\envs\yolo_env\lib\site-packages\ultralytics\engine\predictor.py", line 399, in run_callbacks
    callback(self)
  File "C:\Users\alee\AppData\Local\anaconda3\envs\yolo_env\lib\site-packages\ultralytics\trackers\track.py", line 80, in on_predict_postprocess_end
    tracks = tracker.update(det, im0s[i])
  File "C:\Users\alee\AppData\Local\anaconda3\envs\yolo_env\lib\site-packages\ultralytics\trackers\byte_tracker.py", line 337, in update
    dists = self.get_dists(strack_pool, detections)
  File "C:\Users\alee\AppData\Local\anaconda3\envs\yolo_env\lib\site-packages\ultralytics\trackers\byte_tracker.py", line 418, in get_dists
    if self.args.fuse_score:
  File "C:\Users\alee\AppData\Local\anaconda3\envs\yolo_env\lib\site-packages\ultralytics\utils\__init__.py", line 266, in __getattr__
    raise AttributeError(
AttributeError: 
            'IterableSimpleNamespace' object has no attribute 'fuse_score'. This may be caused by a modified or out of date ultralytics
            'default.yaml' file.
Please update your code with 'pip install -U ultralytics' and if necessary replace
            C:\Users\alee\AppData\Local\anaconda3\envs\yolo_env\lib\site-packages\ultralytics\cfg\default.yaml with the latest version from
            https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/default.yaml

I followed error's suggestion but still shows the error.

This is my default.yaml file.

# Ultralytics YOLO 🚀, AGPL-3.0 license
# Default training settings and hyperparameters for medium-augmentation COCO training

task: detect # (str) YOLO task, i.e. detect, segment, classify, pose
mode: train # (str) YOLO mode, i.e. train, val, predict, export, track, benchmark

# Train settings -------------------------------------------------------------------------------------------------------
model: # (str, optional) path to model file, i.e. yolov8n.pt, yolov8n.yaml
data: # (str, optional) path to data file, i.e. coco8.yaml
epochs: 100 # (int) number of epochs to train for
time: # (float, optional) number of hours to train for, overrides epochs if supplied
patience: 100 # (int) epochs to wait for no observable improvement for early stopping of training
batch: 16 # (int) number of images per batch (-1 for AutoBatch)
imgsz: 640 # (int | list) input images size as int for train and val modes, or list[h,w] for predict and export modes
save: True # (bool) save train checkpoints and predict results
save_period: -1 # (int) Save checkpoint every x epochs (disabled if < 1)
cache: False # (bool) True/ram, disk or False. Use cache for data loading
device: # (int | str | list, optional) device to run on, i.e. cuda device=0 or device=0,1,2,3 or device=cpu
workers: 8 # (int) number of worker threads for data loading (per RANK if DDP)
project: # (str, optional) project name
name: # (str, optional) experiment name, results saved to 'project/name' directory
exist_ok: False # (bool) whether to overwrite existing experiment
pretrained: True # (bool | str) whether to use a pretrained model (bool) or a model to load weights from (str)
optimizer: auto # (str) optimizer to use, choices=[SGD, Adam, Adamax, AdamW, NAdam, RAdam, RMSProp, auto]
verbose: True # (bool) whether to print verbose output
seed: 0 # (int) random seed for reproducibility
deterministic: True # (bool) whether to enable deterministic mode
single_cls: False # (bool) train multi-class data as single-class
rect: False # (bool) rectangular training if mode='train' or rectangular validation if mode='val'
cos_lr: False # (bool) use cosine learning rate scheduler
close_mosaic: 10 # (int) disable mosaic augmentation for final epochs (0 to disable)
resume: False # (bool) resume training from last checkpoint
amp: True # (bool) Automatic Mixed Precision (AMP) training, choices=[True, False], True runs AMP check
fraction: 1.0 # (float) dataset fraction to train on (default is 1.0, all images in train set)
profile: False # (bool) profile ONNX and TensorRT speeds during training for loggers
freeze: None # (int | list, optional) freeze first n layers, or freeze list of layer indices during training
multi_scale: False # (bool) Whether to use multiscale during training
# Segmentation
overlap_mask: True # (bool) masks should overlap during training (segment train only)
mask_ratio: 4 # (int) mask downsample ratio (segment train only)
# Classification
dropout: 0.0 # (float) use dropout regularization (classify train only)

# Val/Test settings ----------------------------------------------------------------------------------------------------
val: True # (bool) validate/test during training
split: val # (str) dataset split to use for validation, i.e. 'val', 'test' or 'train'
save_json: False # (bool) save results to JSON file
save_hybrid: False # (bool) save hybrid version of labels (labels + additional predictions)
conf: # (float, optional) object confidence threshold for detection (default 0.25 predict, 0.001 val)
iou: 0.7 # (float) intersection over union (IoU) threshold for NMS
max_det: 300 # (int) maximum number of detections per image
half: False # (bool) use half precision (FP16)
dnn: False # (bool) use OpenCV DNN for ONNX inference
plots: True # (bool) save plots and images during train/val

# Predict settings -----------------------------------------------------------------------------------------------------
source: # (str, optional) source directory for images or videos
vid_stride: 1 # (int) video frame-rate stride
stream_buffer: False # (bool) buffer all streaming frames (True) or return the most recent frame (False)
visualize: False # (bool) visualize model features
augment: False # (bool) apply image augmentation to prediction sources
agnostic_nms: False # (bool) class-agnostic NMS
classes: # (int | list[int], optional) filter results by class, i.e. classes=0, or classes=[0,2,3]
retina_masks: False # (bool) use high-resolution segmentation masks
embed: # (list[int], optional) return feature vectors/embeddings from given layers

# Visualize settings ---------------------------------------------------------------------------------------------------
show: False # (bool) show predicted images and videos if environment allows
save_frames: False # (bool) save predicted individual video frames
save_txt: False # (bool) save results as .txt file
save_conf: False # (bool) save results with confidence scores
save_crop: False # (bool) save cropped images with results
show_labels: True # (bool) show prediction labels, i.e. 'person'
show_conf: True # (bool) show prediction confidence, i.e. '0.99'
show_boxes: True # (bool) show prediction boxes
line_width: # (int, optional) line width of the bounding boxes. Scaled to image size if None.

# Export settings ------------------------------------------------------------------------------------------------------
format: torchscript # (str) format to export to, choices at https://docs.ultralytics.com/modes/export/#export-formats
keras: False # (bool) use Kera=s
optimize: False # (bool) TorchScript: optimize for mobile
int8: False # (bool) CoreML/TF INT8 quantization
dynamic: False # (bool) ONNX/TF/TensorRT: dynamic axes
simplify: False # (bool) ONNX: simplify model using `onnxslim`
opset: # (int, optional) ONNX: opset version
workspace: 4 # (int) TensorRT: workspace size (GB)
nms: False # (bool) CoreML: add NMS

# Hyperparameters ------------------------------------------------------------------------------------------------------
lr0: 0.01 # (float) initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
lrf: 0.01 # (float) final learning rate (lr0 * lrf)
momentum: 0.937 # (float) SGD momentum/Adam beta1
weight_decay: 0.0005 # (float) optimizer weight decay 5e-4
warmup_epochs: 3.0 # (float) warmup epochs (fractions ok)
warmup_momentum: 0.8 # (float) warmup initial momentum
warmup_bias_lr: 0.1 # (float) warmup initial bias lr
box: 7.5 # (float) box loss gain
cls: 0.5 # (float) cls loss gain (scale with pixels)
dfl: 1.5 # (float) dfl loss gain
pose: 12.0 # (float) pose loss gain
kobj: 1.0 # (float) keypoint obj loss gain
label_smoothing: 0.0 # (float) label smoothing (fraction)
nbs: 64 # (int) nominal batch size
hsv_h: 0.015 # (float) image HSV-Hue augmentation (fraction)
hsv_s: 0.7 # (float) image HSV-Saturation augmentation (fraction)
hsv_v: 0.4 # (float) image HSV-Value augmentation (fraction)
degrees: 0.0 # (float) image rotation (+/- deg)
translate: 0.1 # (float) image translation (+/- fraction)
scale: 0.5 # (float) image scale (+/- gain)
shear: 0.0 # (float) image shear (+/- deg)
perspective: 0.0 # (float) image perspective (+/- fraction), range 0-0.001
flipud: 0.0 # (float) image flip up-down (probability)
fliplr: 0.5 # (float) image flip left-right (probability)
bgr: 0.0 # (float) image channel BGR (probability)
mosaic: 1.0 # (float) image mosaic (probability)
mixup: 0.0 # (float) image mixup (probability)
copy_paste: 0.0 # (float) segment copy-paste (probability)
auto_augment: randaugment # (str) auto augmentation policy for classification (randaugment, autoaugment, augmix)
erasing: 0.4 # (float) probability of random erasing during classification training (0-0.9), 0 means no erasing, must be less than 1.0.
crop_fraction: 1.0 # (float) image crop fraction for classification (0.1-1), 1.0 means no crop, must be greater than 0.

# Custom config.yaml ---------------------------------------------------------------------------------------------------
cfg: # (str, optional) for overriding defaults.yaml

# Tracker settings ------------------------------------------------------------------------------------------------------
tracker: botsort.yaml # (str) tracker type, choices=[botsort.yaml, bytetrack.yaml]

**Comment by Y-T-G** [comment]
Update your ultralytics.

`pip install -U ultralytics`

**Comment by duhyeonlee** [comment]
@Y-T-G 
Hi!

Yes, I did have updated ultralytics and re-installed default.yaml...
But it still shows the same issue.

**Comment by Y-T-G** [comment]
What's the code you're using for tracking?

Do you have a custom `botsort.yaml` that you're using? It's missing the `fuse_score` key.

https://github.com/ultralytics/ultralytics/blob/6b95967e080dcba832a7f505c7925d9137f51733/ultralytics/cfg/trackers/botsort.yaml#L10

**Comment by duhyeonlee** [comment]
@Y-T-G 
I am using custom trained YOLO.

This is the botsort.yaml

# Ultralytics YOLO 🚀, AGPL-3.0 license
# Default YOLO tracker settings for BoT-SORT tracker https://github.com/NirAharon/BoT-SORT

tracker_type: botsort # tracker type, ['botsort', 'bytetrack']
track_high_thresh: 0.5 # threshold for the first association
track_low_thresh: 0.1 # threshold for the second association
new_track_thresh: 0.6 # threshold for init new track if the detection does not match any tracks
track_buffer: 30 # buffer to calculate the time when to remove tracks
match_thresh: 0.8 # threshold for matching tracks
fuse_score: True # Whether to fuse confidence scores with the iou distances before matching
# min_box_area: 10  # threshold for min box areas(for tracker evaluation, not used for now)

# BoT-SORT settings
gmc_method: sparseOptFlow # method of global motion compensation
# ReID model related thresh (not supported yet)
proximity_thresh: 0.5
appearance_thresh: 0.25
with_reid: False

**Comment by Y-T-G** [comment]
What code are you using for tracking?

**Comment by Y-T-G** [comment]
Can you provide the output after running this command in terminal: `yolo checks`?

**Comment by duhyeonlee** [comment]
> What code are you using for tracking?

I am using Jupyter Notebook to run. However, it showed the same error when I ran it on Ubuntu as well.
Or is it because I have trained with custom dataset with YOLO v9?




> Can you provide the output after running this command in terminal: `yolo checks`?

Ultralytics YOLOv8.2.91 🚀 Python-3.9.18 torch-2.3.1 CUDA:0 (NVIDIA GeForce GTX 1050, 4096MiB)
Setup complete ✅ (8 CPUs, 15.9 GB RAM, 248.9/290.7 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.9.18
Install             pip
RAM                 15.86 GB
CPU                 Intel Core(TM) i7-7700HQ 2.80GHz
CUDA                11.8

numpy               ✅ 1.24.3<2.0.0,>=1.23.0
matplotlib          ✅ 3.8.4>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.2>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.3.1>=1.8.0
torchvision         ✅ 0.18.1>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.1>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.6>=2.0.0
torch               ✅ 2.3.1!=2.4.0,>=1.8.0; sys_platform == "win32"

**Comment by Y-T-G** [comment]
What's the command or code you're using?

**Comment by duhyeonlee** [comment]
# Load the models
model1 = YOLO(lights_path)
model2 = YOLO(docking_path)

# Create threads for each model
conf=0.3
show=True
save=False

# Initialize a list to store log data
log_data = []

thread1 = threading.Thread(target=track_video, args=(model1, video_path, conf, show, save, 'output_lights.avi', ["b_light", "w_light"], 8))
thread2 = threading.Thread(target=track_video, args=(model2, video_path, conf, show, save, 'output_docking.avi', ["docking_station"], 1))

# Start the threads
thread1.start()
thread2.start()

# Wait for both threads to finish
thread1.join()
thread2.join()

# Save log data to Excel filePixel_Height
df = pd.DataFrame(log_data)
df.to_excel('log_data.xlsx', index=False)

# Clean up and close windows
cv2.destroyAllWindows()

**Comment by Y-T-G** [comment]
Where's the code for `track_video`? I want to see the code for `model.track`.

**Comment by duhyeonlee** [comment]
# Function to run tracking
def track_video(model, source, conf, show, save, output_path, class_names, max_det):
    video = cv2.VideoCapture(source)  # Read the video file

    # Get video properties
    frame_width, frame_height, fps, fourcc = get_video_properties(video)

    print("FPS: ", fps)

    # Get the center of the image
    image_center_x = frame_width / 2
    image_center_y = frame_height / 2
    image_center = [image_center_x, image_center_y]
    print("Image Size: ", frame_width, frame_height)

    out = cv2.VideoWriter(output_path, fourcc, fps, (frame_width, frame_height))

    num_frame = 0 # initialize frame number
    start_time = time.time() # time count starts

    # Example extrinsic parameters (You need to provide actual values for R and t)
    R = np.eye(3)  # Identity matrix for simplicity, replace with actual rotation matrix
    t = np.array([0, 0, 0])  # No translation for simplicity, replace with actual translation vector

    while video.isOpened():
        ret, frame = video.read()  # Read the video frames

        # Exit the loop if no more frames in either video
        if not ret:
            break

        w_light_points_2d = []
        
        num_frame = num_frame + 1 # Show Frame Number
        elapsed_time = time.time() - start_time # current time
        
        results = model.track(frame, show=show, conf=conf, save=save, iou=0.4, persist=True, tracker=bytetrack_yaml_path, max_det=max_det)    
        res_plotted = results[0].plot()

        res_plotted, b_light_points_2d = process_results(results, class_names, dock_height, frame_height, image_center, res_plotted, elapsed_time, num_frame, R, t)

        if 'w_light' in class_names:
            res_plotted, w_light_points_2d = draw_circle(results, res_plotted, frame_width, frame_height, elapsed_time, num_frame, R, t)

        # Retrieve Rotation and Translation Matrix
        points_2d = [b_light_points_2d, w_light_points_2d]
        print("Points in 2D: \n", points_2d)
        if [] in points_2d:
            points_2d = [list(point) if isinstance(point, tuple) else point for sublist in points_2d for point in sublist] # Flatten and make it list.
            points_2d = np.array(points_2d) # Convert list to numpy array
            R, t = R, t
        else:
            points_2d = [list(point) if isinstance(point, tuple) else point for sublist in points_2d for point in sublist] # Flatten and make it list.
            points_2d = np.array(points_2d) # Convert list to numpy array
            R, t = get_Rt(points_2d)

        R_t = np.transpose(R)
        Cw = R_t @ (-t)
        print("Center of Camera: ", Cw)

        # Draw the circle at the camera center on the image
        cv2.circle(res_plotted, (int(cx), int(cy)), 10, (255, 255, 255), -1)  # Green color, filled circle
        # Camera Center 3D
        Cw = [np.round(x, 3) for x in Cw]
        txt_cc = f"Camera away from Doc at x: {Cw[0]} m, y: {Cw[1]} m, z: {Cw[2]} m"
        cv2.putText(res_plotted, txt_cc, ((50), int(cy-20)), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (100, 50, 250), 2)
        
        # Display Frame
        cv2.putText(res_plotted, f"Frame: {num_frame}", (frame_width - 100, 15), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 0), 2)
        
        # Write the frame to the output video
        out.write(res_plotted)
        cv2.imshow(f"Tracking_Stream_{output_path}", res_plotted)

        key = cv2.waitKey(1)
        if key == ord("q"):
            break

    # Release resources
    video.release()
    out.release()

**Comment by duhyeonlee** [comment]
I noticed that when there is nothing detected, code is still running and trying to detect something, but once something get detected then it shows the error like this.

**Comment by Y-T-G** [comment]
What's inside your `bytetrack_yaml_path`? Does it have `fuse_score`? If not, add `fuse_score`.

https://github.com/ultralytics/ultralytics/blob/ec9f4a7b1a3d3580bdea40107f54bb3a43e361f5/ultralytics/cfg/trackers/bytetrack.yaml#L10

**Comment by duhyeonlee** [comment]
# Ultralytics YOLO 🚀, AGPL-3.0 license
# Default YOLO tracker settings for ByteTrack tracker https://github.com/ifzhang/ByteTrack

tracker_type: bytetrack # tracker type, ['botsort', 'bytetrack']
track_high_thresh: 0.01 # threshold for the first association
track_low_thresh: 0.01 # threshold for the second association
new_track_thresh: 0.01 # threshold for init new track if the detection does not match any tracks
track_buffer: 60 # buffer to calculate the time when to remove tracks
match_thresh: 0.6 # threshold for matching tracks
# min_box_area: 10  # threshold for min box areas(for tracker evaluation, not used for now)
# mot20: False  # for tracker evaluation(not used for now)

**Comment by Y-T-G** [comment]
Add `fuse_score` like in the linked file

**Comment by duhyeonlee** [comment]
I need to do more things but it seems solved so far!

Thank you so much!

**Comment by glenn-jocher** [comment]
@duhyeonlee you're welcome! If you have more questions, feel free to ask.
