### ISSUE TITLE
How to Merge or use two weights at the same time

### ISSUE THREAD

**Issue by NicolasGonzalezF** [ultralytics/ultralytics#16200]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi i have a question about methods to use two trained pt files to have my custom object recognition of one single object and i want to use the yolo object recognition to also detect objects like type of cars, i know i can use RobotFlow to merge projects but theres not quite... a project that can help me with that task, ive read that you can use Torch.Hub.Load to load two different models but to my understanding it only works with yolo 5 and i have trained my pt with yolo 8 and newer

so i just want to know two things.

1- Is there a way for me to add my custom dataset to Yolo example mine is detection of kites or carwheels, and train it so i can have both of best worlds or.
2- Is there a method to have Yolo pt and my custom pt to work at the same time to detect objects on an img /video ?

currently i found also a broken link
https://community.ultralytics.com/t/how-to-combine-weights-to-detect-from-multiple-datasets
that i tought it would help but well its broken, any help would do...

### Additional

Im using python for my project and google collab to train my dataset i know how to load, track and extract info from the results =model.predict(img)  i just want to use both of my object detection capabilities and i dont think i can just load both models and ask it to draw on the same cv2 canvas

**Comment by Y-T-G** [comment]
>  i dont think i can just load both models and ask it to draw on the same cv2 canvas

You can do that.
```python
img_plotted = img.copy()

result = model1(img)[0]
img_plotted = result.plot(img=img_plotted)

result = model2(img)[0]
img_plotted = result.plot(img=img_plotted)

cv2.imshow("Results", img_plotted)
```

**Comment by NicolasGonzalezF** [comment]
> > i dont think i can just load both models and ask it to draw on the same cv2 canvas
> 
> You can do that.
> 
> ```python
> img_plotted = img.copy()
> 
> result = model1(img)[0]
> img_plotted = result.plot(img=img_plotted)
> 
> result = model2(img)[0]
> img_plotted = result.plot(img=img_plotted)
> 
> cv2.imshow("Results", img_plotted)
> ```

ok thats very very useful thanks 👌, now i just want to know if i can merge the two things together

**Comment by NicolasGonzalezF** [comment]
> It's not possible to merge weights.

but is it posible to get the dataset from yolo and merge in robot flow with my custom dataset then train it in google collab? or do i have to do the anotations manually?

**Comment by Y-T-G** [comment]
The COCO dataset (which the pretrained model uses) has over 117k images. You will hardly complete 1 epoch on Google Colab before it times out.

**Comment by NicolasGonzalezF** [comment]
> Works fine for me.

yeah but the logic there is kinda not understandable, yet since ultimetly it overwrites the img_plotted variable with the results of the second model ultimetly doing... notting that ive asked before where i wanted to have bot tracking boxes in the same window

**Comment by Y-T-G** [comment]
`img_plotted` is passed to the `plot()` method, so it writes onto it. The results of both models are written on the same image. So at the end `img_plotted` will have both.

**Comment by NicolasGonzalezF** [comment]
![image](https://github.com/user-attachments/assets/f4170d1f-f9c2-4989-ac12-cc982fb17a85)

for some reason it needs to load first the yolo method then the custom one... now i have to fiddle around with the tracker so i can count only the car-tires, thank you very much

**Comment by glenn-jocher** [comment]
You're welcome! If you need further assistance with tracking car tires, feel free to ask.
