### ISSUE TITLE
Early stopping model.tune() -- what happens?

### ISSUE THREAD

**Issue by wynne-chen** [ultralytics/ultralytics#16204]
//removed.

**Comment by wynne-chen** [comment]
At present when I look at the best_hyperparameters.yaml file, this is what the top comments say:

# 30/300 iterations complete ✅ (744464.61s)
# Results saved to results/yolov9c-seg/tune3
# Best fitness=0.0 observed at iteration 1
# Best fitness metrics are {}
# Best fitness model is results/yolov9c-seg/tune3-
# Best fitness hyperparameters are printed below.

followed by the default hyperparameter values. My question is whether there is a form of early stopping that would update the 'best fitness= _' and best fitness metrics and best fitness model to the actual best results amongst what has already run. Hope that's clearer.

**Comment by Y-T-G** [comment]
It doesn't seem like it found anything useful yet. And if you aren't intending to run hyperparameter tuning for a long time, then any difference is mostly placebo.

**Comment by wynne-chen** [comment]
On reading the tuner.py file I believe you're right, because it should be updating the file every run if the current fitness value excedes the best value. Correspondingly I checked the csv file and found that fitness for all iterations so far has been logged at 0, which confused me. So I dug into the trainer.py file to see how fitness metrics are evaluated, which pointed me to the validator.py file, where I've noticed that in the BaseValidator class these are simply empty:

 ```
   def init_metrics(self, model):
        """Initialize performance metrics for the YOLO model."""
        pass

    def update_metrics(self, preds, batch):
        """Updates metrics based on predictions and batch."""
        pass

    def finalize_metrics(self, *args, **kwargs):
        """Finalizes and returns all metrics."""
        pass

    def get_stats(self):
        """Returns statistics about the model's performance."""
        return {}

    def check_stats(self, stats):
        """Checks statistics."""
        pass

    def print_results(self):
        """Prints the results of the model's predictions."""
        pass

    def get_desc(self):
        """Get description of the YOLO model."""
        pass
      
@property
    def metric_keys(self):
        """Returns the metric keys used in YOLO training/validation."""
        return []

    def on_plot(self, name, data=None):
        """Registers plots (e.g. to be consumed in callbacks)."""
        self.plots[Path(name)] = {"data": data, "timestamp": time.time()}

    # TODO: may need to put these following functions into callback
    def plot_val_samples(self, batch, ni):
        """Plots validation samples during training."""
        pass

    def plot_predictions(self, batch, preds, ni):
        """Plots YOLO model predictions on batch images."""
        pass

    def pred_to_json(self, preds, batch):
        """Convert predictions to JSON format."""
        pass

    def eval_json(self, stats):
        """Evaluate and return JSON format of prediction statistics."""
        pass
```

Could one of the developers explain if I'm misreading this? Thank you!

**Comment by Y-T-G** [comment]
It's an abstract class. The methods are implemented in the classes that inherit from it. Like `DetectionValidator`.
