### ISSUE TITLE
A question about how to make the input of layer zero as the input of other layers

### ISSUE THREAD

**Issue by HoungJee** [ultralytics/ultralytics#16209]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to make changes to the fifth layer, I need to change its input to the input of the zero layer, which is the original image, the parameter -1 is the previous layer, the parameter 0 is the 0th layer, I want to know how much I should set the parameters, I don't want to add another layer because adding an extra layer according to the experiment will affect some of my experimental results
![mymodule](https://github.com/user-attachments/assets/756272b1-1b82-43db-9c12-baed6dbc7d3d)

**Comment by Y-T-G** [comment]
You can't do that without modifying the layers because the 5th layer expects 64 channel input, but the image is 3 channels

**Comment by Y-T-G** [comment]
You can delete the first 4 layers in the yaml and try.

**Comment by HoungJee** [comment]
> Collaborator



> You can delete the first 4 layers in the yaml and try.

I'm wrong, the purpose is to add a layer that can be used to generate a grayscale image, which requires the original image

**Comment by glenn-jocher** [comment]
To generate a grayscale image, you can modify the model's architecture to include a layer that processes the original image directly. Consider adding a custom layer for this purpose.
