### ISSUE TITLE
YOLOv8 OpenVINO C++ inference

### ISSUE THREAD

**Issue by lyC121** [ultralytics/ultralytics#16212]
### 平台：
window11

### 软件安装：
cmake version 3.29.8
opencv version 4.10.0
mingw version 13.2.0
python version 3.9.5

### 其中CMakeLists.txt内容如下：

cmake_minimum_required(VERSION 3.12)
project(yolov8_openvino_example)

set(CMAKE_CXX_STANDARD 14)

find_package(OpenVINO REQUIRED)

if(OpenVINO_FOUND)
message(STATUS "OpenVINO found: ${OpenVINO_LIBS}")
endif()

find_package(OpenCV REQUIRED)

if(OpenCV_FOUND)
message(STATUS "OpenCV found: ${OpenCV_LIBS}")
endif()

include_directories(
${OpenCV_INCLUDE_DIRS}
#${OpenVINO_INCLUDE_DIRS}
D:/software/openvino_windows_2024.0.0.1/runtime/include/
)

add_executable(detect
main.cc
inference.cc
)

target_link_libraries(detect
${OpenCV_LIBS}
#${OpenVINO_LIBS}
D:/software/openvino_windows_2024.0.0.1/runtime/lib/intel64/Release/openvino.lib

)

### 运行方式：
mkdir build && cd build
cmake -G "MinGW Makefiles" ..
mingw32-make

### 运行cmake 后结果如下：
F:\workspace\ultralytics\examples\YOLOv8-OpenVINO-CPP-Inference\build>cmake -G "MinGW Makefiles" ..
-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/software/mingw64/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/software/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- OpenVINO found:
-- Found OpenCV: D:/software/opencv/opencv/install (found version "4.10.0")
-- OpenCV found: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_gapi;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_stitching;opencv_video;opencv_videoio
-- Configuring done (2.1s)
-- Generating done (0.1s)
-- Build files have been written to: F:/workspace/ultralytics/examples/YOLOv8-OpenVINO-CPP-Inference/build

### 运行mingw32-make 后报错如下：

F:\workspace\ultralytics\examples\YOLOv8-OpenVINO-CPP-Inference\build>mingw32-make
[ 33%] Building CXX object CMakeFiles/detect.dir/main.cc.obj
[ 66%] Building CXX object CMakeFiles/detect.dir/inference.cc.obj
[100%] Linking CXX executable detect.exe
CMakeFiles\detect.dir/objects.a(main.cc.obj):main.cc:(.text$_ZN4yolo9InferenceD1Ev[_ZN4yolo9InferenceD1Ev]+0x2a): undefined reference to __imp__ZN2ov13CompiledModelD1Ev' CMakeFiles\detect.dir/objects.a(main.cc.obj):main.cc:(.text$_ZN4yolo9InferenceD1Ev[_ZN4yolo9InferenceD1Ev]+0x3e): undefined reference to __imp__ZN2ov12InferRequestD1Ev'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x1e00): undefined reference to __imp__ZN2ov13CompiledModelD1Ev' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x1e17): undefined reference to __imp__ZN2ov12InferRequestD1Ev'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3a80): undefined reference to __imp__ZN2ov13CompiledModelD1Ev' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3a97): undefined reference to __imp__ZN2ov12InferRequestD1Ev'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3af5): undefined reference to __imp__ZN2ov4CoreC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3b35): undefined reference to _imp__ZNK2ov4Core10read_modelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3b5c): undefined reference to __imp__ZNK2ov5Model10is_dynamicEv' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3b8b): undefined reference to __imp__ZN2ov9DimensionC1Ex'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3ba7): undefined reference to __imp__ZN2ov9DimensionC1Ex' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3bd0): undefined reference to __imp__ZN2ov9DimensionC1Ex'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3bf9): undefined reference to __imp__ZN2ov9DimensionC1Ex' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3c28): undefined reference to __imp__ZN2ov12PartialShapeC1ESt16initializer_listINS_9DimensionEE'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3c3e): undefined reference to __imp__ZN2ov5Model7reshapeERKNS_12PartialShapeE' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3c89): undefined reference to __imp__ZN2ov10preprocess16PrePostProcessorC1ERKSt10shared_ptrINS_5ModelEE'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3c99): undefined reference to __imp__ZN2ov10preprocess16PrePostProcessor5inputEv' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3ca5): undefined reference to __imp__ZN2ov10preprocess9InputInfo6tensorEv'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3cb8): undefined reference to __imp__ZN2ov10preprocess15InputTensorInfo16set_element_typeERKNS_7element4TypeE' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3ce7): undefined reference to __imp__ZN2ov10preprocess15InputTensorInfo10set_layoutERKNS_6LayoutE'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3d23): undefined reference to __imp__ZN2ov10preprocess15InputTensorInfo16set_color_formatERKNS0_11ColorFormatERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISB_EE' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3d51): undefined reference to __imp__ZN2ov10preprocess16PrePostProcessor5inputEv'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3d5d): undefined reference to __imp__ZN2ov10preprocess9InputInfo10preprocessEv' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3d70): undefined reference to __imp__ZN2ov10preprocess15PreProcessSteps20convert_element_typeERKNS_7element4TypeE'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3d90): undefined reference to __imp__ZN2ov10preprocess15PreProcessSteps13convert_colorERKNS0_11ColorFormatE' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3e1c): undefined reference to __imp__ZN2ov10preprocess15PreProcessSteps5scaleERKSt6vectorIfSaIfEE'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3e4a): undefined reference to __imp__ZN2ov10preprocess16PrePostProcessor5inputEv' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3e56): undefined reference to __imp__ZN2ov10preprocess9InputInfo5modelEv'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3e85): undefined reference to __imp__ZN2ov10preprocess14InputModelInfo10set_layoutERKNS_6LayoutE' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3ea4): undefined reference to __imp__ZN2ov10preprocess16PrePostProcessor6outputEv'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3eb0): undefined reference to __imp__ZN2ov10preprocess10OutputInfo6tensorEv' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3ec3): undefined reference to __imp__ZN2ov10preprocess16OutputTensorInfo16set_element_typeERKNS_7element4TypeE'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3eda): undefined reference to __imp__ZN2ov10preprocess16PrePostProcessor5buildEv' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3fb4): undefined reference to __imp__ZN2ov4Core13compile_modelERKSt10shared_ptrIKNS_5ModelEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3mapISC_NS_3AnyESt4lessISC_ESaISt4pairISD_SG_EEE'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x3fe1): undefined reference to __imp__ZN2ov13CompiledModelD1Ev' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x403b): undefined reference to __imp__ZN2ov13CompiledModel20create_infer_requestEv'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x4068): undefined reference to __imp__ZN2ov12InferRequestD1Ev' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x4087): undefined reference to __imp__ZN2ov5Model6inputsEv'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x40a4): undefined reference to __imp__ZNK2ov6OutputINS_4NodeEE9get_shapeEv' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x40b6): undefined reference to _imp__ZN2ov5ShapeC1ERKS0'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x40ca): undefined reference to __imp__ZNK2ov5ShapeixEx' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x40e8): undefined reference to __imp__ZNK2ov5ShapeixEx'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x414e): undefined reference to __imp__ZN2ov5Model7outputsEv' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x416b): undefined reference to __imp__ZNK2ov6OutputINS_4NodeEE9get_shapeEv'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x417e): undefined reference to __imp__ZN2ov5ShapeC1ERKS0_' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x4193): undefined reference to __imp__ZNK2ov5ShapeixEx'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x41b2): undefined reference to __imp__ZNK2ov5ShapeixEx' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x41fe): undefined reference to __imp__ZN2ov5ShapeD1Ev'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x4219): undefined reference to __imp__ZN2ov5ShapeD1Ev' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x4235): undefined reference to __imp__ZN2ov10preprocess16PrePostProcessorD1Ev'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x4393): undefined reference to __imp__ZN2ov5ShapeD1Ev' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x43b8): undefined reference to __imp__ZN2ov5ShapeD1Ev'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x43de): undefined reference to __imp__ZN2ov10preprocess16PrePostProcessorD1Ev' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x444c): undefined reference to __imp__ZN2ov12InferRequest5inferEv'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x4577): undefined reference to __imp__ZN2ov7StridesC1Ev' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x458e): undefined reference to __imp__ZNK2ov13CompiledModel5inputEv'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x459a): undefined reference to __imp__ZNK2ov6OutputIKNS_4NodeEE9get_shapeEv' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x45b4): undefined reference to __imp__ZNK2ov13CompiledModel5inputEv'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x45c0): undefined reference to __imp__ZNK2ov6OutputIKNS_4NodeEE16get_element_typeEv' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x45ec): undefined reference to __imp__ZN2ov6TensorC1ERKNS_7element4TypeERKNS_5ShapeEPvRKNS_7StridesE'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x4613): undefined reference to __imp__ZN2ov12InferRequest16set_input_tensorERKNS_6TensorE' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x4623): undefined reference to __imp__ZN2ov6TensorD1Ev'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x4672): undefined reference to __imp__ZN2ov6TensorD1Ev' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x4704): undefined reference to __imp__ZN2ov12InferRequest17get_output_tensorEv'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x472d): undefined reference to __imp__ZN2ov6TensorD1Ev' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text+0x4b61): undefined reference to __imp__ZN2ov6TensorD1Ev'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text$_ZN2ov6LayoutC1EPKc[_ZN2ov6LayoutC1EPKc]+0x47): undefined reference to __imp__ZN2ov6LayoutC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text$_ZNK2ov6Tensor4dataIKffEEPT_v[_ZNK2ov6Tensor4dataIKffEEPT_v]+0xf): undefined reference to __imp__ZN2ov7element4fromIfEENS0_4TypeEv'
CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text$_ZNK2ov6Tensor4dataIKffEEPT_v[_ZNK2ov6Tensor4dataIKffEEPT_v]+0x26): undefined reference to __imp__ZNK2ov6Tensor4dataERKNS_7element4TypeE' CMakeFiles\detect.dir/objects.a(inference.cc.obj):inference.cc:(.text$_ZNSt4pairIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN2ov3AnyEED1Ev[_ZNSt4pairIKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN2ov3AnyEED1Ev]+0x1a): undefined reference to __imp__ZN2ov3AnyD1Ev'
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [CMakeFiles\detect.dir\build.make:132: detect.exe] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:82: CMakeFiles/detect.dir/all] Error 2
mingw32-make: *** [Makefile:90: all] Error 2

### 能否帮忙看下什么原因，谢谢

**Comment by glenn-jocher** [comment]
@lyC121 it seems you're encountering linker errors related to OpenVINO. Please ensure that the OpenVINO libraries are correctly linked in your `CMakeLists.txt`. Double-check the paths and ensure all necessary OpenVINO libraries are included. You might also need to update the OpenVINO version or check compatibility with your current setup.

**Comment by HHeLiBeB-C** [comment]
同样的问题，有解决嘛？

**Comment by glenn-jocher** [comment]
请确保所有必需的OpenVINO库都已正确链接，并检查路径设置。如果问题仍然存在，建议查看OpenVINO版本的兼容性。
