### ISSUE TITLE
RuntimeError: The size of tensor a (8400) must match the size of tensor b (16800) at non-singleton dimension 2

### ISSUE THREAD

**Issue by SM2XWe1L** [ultralytics/ultralytics#16210]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When i want to quantize my yolov8 model ,i encounter this problem in the dist2bbox function (in Detect's forward function),could anyone help me?
Thirsty for your kind reply!!
![image](https://github.com/user-attachments/assets/a361fc12-f805-4477-beed-a87828e30e32)

**Comment by Skillnoob** [comment]
Can you share the code you ran
