### ISSUE TITLE
High class imbalance

### ISSUE THREAD

**Issue by S20-Raj** [ultralytics/ultralytics#16217]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am working on a project for detecting objects in hand which are put inside or taken outside the refrigerator. Yolov8 is unable to detect the objects accurately for the same background as well as when the background (person + new view of the refrigerator) is changed. 
In the image below  we can see that number of hand instances is too much. Even if I will apply augmentation, then also hand instances will be increased as hand class is almost in every image. 

![image](https://github.com/user-attachments/assets/ba2840b2-389d-4333-a965-c437442eb5ca)

**Comment by Y-T-G** [comment]
The low number of instances for the other classes is a bigger problem than the high number of instances of hand.

**Comment by S20-Raj** [comment]
> The low number of instances for the other classes is a bigger problem than the high number of instances of hand.

Yes, I know. But how to solve it?

**Comment by Y-T-G** [comment]
You can try [this](https://y-t-g.github.io/tutorials/yolo-class-balancing/) with `agg_func` set to `np.sum`, but it wouldn't help with the overfitting issue because of low number of instances.
