### ISSUE TITLE
Help Wanted 🙏 YOLOv8 Conda Distribution Implementation

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/ultralytics#1622]
### Call for Community Contributions

We're calling on the community to help us implement YOLOv8 on conda and create a github actions workflow for deployment on version increase. This will make it easier for users to install and use YOLOv8, as well as keep up to date with the latest releases. We have an existing pip deploy workflow that automatically publishes a new `ultralytics` package to pypi when a push to main increments a patch version by + 0.0.1. You can see this action here: 

https://github.com/ultralytics/ultralytics/blob/ef03e6732aecc91134275a3f5a62f2e0f82ab4bf/.github/workflows/publish.yml#L1-L69

**Requirements:**

- Experience with conda distribution and packaging
- Experience with Github Actions
- Familiarity with YOLOv8 and its dependencies
- Strong problem-solving skills

**Expected Deliverables:**

- YOLOv8 conda package that can be easily installed
- Github Actions workflow for deployment on version increase
- Documentation on how to install and use the conda package

We welcome contributions from anyone interested in helping us achieve this goal. Let's work together to make YOLOv8 more accessible to everyone!

Originally raised in https://github.com/ultralytics/ultralytics/issues/304

**Comment by abraha2d** [comment]
I've started the process to get `ultralytics` on conda-forge, see https://github.com/conda-forge/staged-recipes/pull/22721. I've added @glenn-jocher, @AyushExel, and @Laughing-q to the list of proposed maintainers (along with myself)... let me know if that list should be different.

Currently, the only thing blocking that PR is the fact that the `thop` dependency is not available on conda-forge yet. `thop` does not have an sdist published to PyPI either, so I'm not sure how to get it on conda-forge. I've submitted https://github.com/Lyken17/pytorch-OpCounter/pull/204 to change that, hoping that gets merged soon.

Alternatively, Is the dependency on `thop` necessary? Can `ultralytics` be updated to only use `thop` if available, and fall back to no profiling support if `thop` isn't available?

With the way conda-forge is set up, no changes should be necessary to this repo's GitHub Actions setup... once a new version of `ultralytics` is published to PyPI, the automation around conda-forge can handle publishing that version to conda-forge.

**Comment by glenn-jocher** [comment]
@abraha2d thank you for updating us on the progress you've made to get `ultralytics` on conda-forge. We appreciate your efforts in proposing the list of maintainers, which seems fine for now. That's great to hear that the only thing holding the PR back is the `thop` dependency, and we will have to wait until there is a published sdist on PyPI or a successful merge on https://github.com/Lyken17/pytorch-OpCounter/pull/204.

Regarding the dependency of `thop`, we will check if this is necessary for YOLOv8, and if not, we can consider updating it to only use `thop` when it's available and fallback when it's not.

Additionally, we appreciate your feedback on the GitHub Actions setup and how the process for conda-forge works. Please keep us posted on updates, and we're committed to making `ultralytics` more accessible to everyone.

**Comment by glenn-jocher** [comment]
@abraha2d ok I've looked into this some more. Unfortunately thop does not appear to be maintained. I've submitted a [PR](https://github.com/Lyken17/pytorch-OpCounter/pull/201) myself about 2 months ago for a warning that's started appearing and it's gone unanswered, so we may need to search for alternatives. 

I tried to create a native torch FLOPs profiler [here](https://github.com/ultralytics/ultralytics/pull/2369), but unfortunately it's very verbose, i.e.

```
STAGE:2023-05-02 21:50:04 33874:980425 ActivityProfilerController.cpp:311] Completed Stage: Warm Up
STAGE:2023-05-02 21:50:04 33874:980425 ActivityProfilerController.cpp:317] Completed Stage: Collection
STAGE:2023-05-02 21:50:04 33874:980425 ActivityProfilerController.cpp:321] Completed Stage: Post Processing
```

We could:

- Make thop optional, i.e. if it's not installed, FLOPs are not computed.
- Figure out how to silence the native FLOPs above
- Find an alternative
- Fork thop and submit a new package to pypi, i.e. `ultralytics-thop`

Can you take a look around at the options and see what the best route is?

**Comment by abraha2d** [comment]
Hi @glenn-jocher, gracefully falling back to no FLOPs computation if thop is not installed is probably the quickest way to get this PR through. If you agree, I can get a PR up for that, and we can get this up on conda-forge once that's merged.
I can also take a look at the native profiler as that might be the best option long-term, given that `thop` is unmaintained.

**Comment by glenn-jocher** [comment]
Hi @abraha2d, 

Yes, gracefully falling back to no FLOPs computation if thop is not installed would be a reasonable solution for this situation. Thank you for offering to create a PR for that.

Regarding the native profiler, that could be a potential long-term solution, and we appreciate your offer to take a look at it.

Please keep us posted on any updates, and let us know if there's anything else we can assist with.

Best regards,
Glenn Jocher

**Comment by glenn-jocher** [comment]
@abraha2d ok let's move forward with your idea. Can you submit a PR for thops profiling to return None if thop is not installed? Then we can comment it in requirements.txt. If it is installed users will see FLOPs, if not then no FLOPs will be show, nice and simple, and then we can start with the Conda distribution :)

**Comment by abraha2d** [comment]
Sounds good, opened https://github.com/ultralytics/ultralytics/pull/2664.

**Comment by abraha2d** [comment]
@glenn-jocher thanks for pushing that through... will push things through on the conda-forge side once a new version of ultralytics is published.

In the meantime, it would be great if @glenn-jocher, @AyushExel, and @Laughing-q could post a comment on https://github.com/conda-forge/staged-recipes/pull/22721 confirming that they are willing to be maintainers for the package. If anyone objects, I can go ahead and remove them from the list.

**Comment by abraha2d** [comment]
In addition, could you clarify whether ultralytics is licensed under `AGPL-3.0-only` or `AGPL-3.0-or-later`?
The conda-forge recipe is passing, license clarification and comments from maintainers mentioned above are the only things left before submitting it for review.

**Comment by glenn-jocher** [comment]
@abraha2d thank you for your inquiry regarding the licensing of ultralytics. To clarify, Ultralytics YOLOv8 is licensed under AGPL-3.0-only. In regards to the conda-forge recipe, it sounds like everything is in order except for some comments from maintainers mentioned above and clarification of the license. Once we have those, the recipe will be ready for submission.

**Comment by abraha2d** [comment]
Got it, updated the license specifier in the conda-forge recipe.

**Comment by glenn-jocher** [comment]
@abraha2d thanks for the update on the conda-forge recipe for YOLOv8! We appreciate your efforts in keeping everything in line with licensing requirements. Once the comments from the maintainers you mentioned above have been added, we should be ready for submission.

**Comment by glenn-jocher** [comment]
@abraha2d hi there! Is there anything left to make `ultralytics` available on conda? Let me know if you need anything. If we are all set then we can start updating the docs with the new installation option?

**Comment by abraha2d** [comment]
Hi @glenn-jocher, still waiting for comments from those on the list of maintainers for the recipe.

Currently, that list is @glenn-jocher, @AyushExel, and @Laughing-q. Please post a comment on conda-forge/staged-recipes#22721 confirming that you are willing to be a maintainer for that recipe, or let me know and I can remove you from the list.

That's the only thing left to do before I submit the recipe to the conda-forge review team.

**Comment by glenn-jocher** [comment]
@abraha2d hi! I've pinged the conda guys a few times but they don't seem to be taking any action on our Conda PR. Any ideas?

**Comment by glenn-jocher** [comment]
@fcakyon thanks! I'll give it a try over there.

**Comment by abraha2d** [comment]
Looks like we're good to go now: https://anaconda.org/conda-forge/ultralytics
It may be a while before I can test it on my project, but I think this can be closed now.

**Comment by glenn-jocher** [comment]
@abraha2d awesome!! So now we can point users to use `conda install ultralytics`?


What about maintenance updates? What's the workflow for updating conda forge when we release a new patch version?

**Comment by abraha2d** [comment]
Yes, that should work, although I'd advise briefly testing it locally first.

As far as updates go, conda-forge automation will pick up when a new release is published to PyPI and open a PR on the feedstock ([here](https://github.com/conda-forge/ultralytics-feedstock)). That PR can be merged by any of the maintainers listed in the recipe, and then the new version will be published to conda-forge.

**Comment by glenn-jocher** [comment]
@abraha2d also how can we update this description section? It won't let me even though I'm logged into Conda. Should we paste a copy of the README here?

<img width="1103" alt="Screenshot 2023-06-21 at 00 00 08" src="https://github.com/ultralytics/ultralytics/assets/26833433/abbd0dd8-3fb0-464f-92cd-e801126d84e5">

**Comment by abraha2d** [comment]
That's populated by the about/description field in the recipe, see for example https://github.com/conda-forge/django-environ-feedstock/blob/main/recipe/meta.yaml#L33

**Comment by glenn-jocher** [comment]
Ohhh got it. Ok so if we do another PR to the https://github.com/conda-forge/staged-recipes repo that should take care of it? Can the description field handle markdown images and text?

**Comment by abraha2d** [comment]
conda-forge has already picked up 2 version updates: https://github.com/conda-forge/ultralytics-feedstock/pulls
I'm not sure what it will do if you merge two version bumps in quick succession, so I would close the first one (8.0.119) and merge the second one (8.0.120).

**Comment by glenn-jocher** [comment]
@abraha2d oh wow, awesome. I don't have write access though to https://github.com/conda-forge/ultralytics-feedstock. Am I supposed to?

<img width="1016" alt="Screenshot 2023-06-21 at 21 20 24" src="https://github.com/ultralytics/ultralytics/assets/26833433/a5f1e716-ef8d-432f-9bf7-e2c26cd29988">

**Comment by abraha2d** [comment]
Yes, you should have write access since you're listed as a maintainer in the recipe. It may be taking some time for their automation to catch up.

**Comment by glenn-jocher** [comment]
@abraha2d still can't merge. I'm super confused. Opened up a help issue in https://github.com/regro/cf-scripts/issues/1720

**Comment by abraha2d** [comment]
See if you can merge now, I just got an email saying I was added to the team.

**Comment by glenn-jocher** [comment]
@abraha2d hi there! Thank you for letting us know about the access issue. It seems that the permission update has been initiated and you should have write access to the https://github.com/conda-forge/ultralytics-feedstock repository soon. Please allow some time for the changes to propagate.

Once you have the write access, you should be able to proceed with the merge process. However, please keep in mind that merging two version bumps in quick succession might have unpredictable results. To avoid any potential issues, we recommend closing the first version bump (8.0.119) and merging the second version bump (8.0.120) when the access is available.

If you encounter any further difficulties or have any other questions, please feel free to ask. We're here to assist you.

**Comment by glenn-jocher** [comment]
@abraha2d ok I think we are all set! I've opened up a PR to update the description in https://github.com/conda-forge/ultralytics-feedstock/pull/6 and also to remove one of the dependencies that is no longer in requirements.txt. 

Thanks for all the help! I'm closing this issue and removing the TODO!!

**Comment by glenn-jocher** [comment]
@abraha2d just wanted to say thank you again, Conda package is live and we have over a thousand downloads now, and I've added Conda install instructions to https://docs.ultralytics.com/quickstart/

Our description looks great and I've enabled fully automated autobuilds on pip updates, so this appears to be 100% on cruise control now.

@Laughing-q @AyushExel @fcakyon FYI

**Comment by abraha2d** [comment]
No problem, glad I could help!

**Comment by glenn-jocher** [comment]
@abraha2d hi there,

Thank you for reaching out. I'm glad I could assist you with the YOLOv8 conda distribution and Github Actions workflow. It's great to see the community coming together to make YOLOv8 more accessible to users.

Regarding your question about YOLOv8's performance on small objects, it's important to note that YOLOv8, like any other object detection model, may face challenges when detecting small objects. This is because small objects have less visual information and can be easily overshadowed or occluded by larger objects.

However, YOLOv8 can still perform reasonably well on small objects depending on various factors such as the size of the objects, image resolution, and the training data. By fine-tuning the model with a diverse dataset that includes small object instances and adjusting certain hyperparameters, you can potentially improve YOLOv8's performance in detecting small objects.

Additionally, using techniques like data augmentation, object scaling, and training with high-resolution images can also help enhance the detection of small objects with YOLOv8.

It's worth mentioning that YOLOv8 is a powerful and versatile object detection model, but it's not specifically optimized for small object detection. If your primary use case involves detecting predominantly small objects, you might want to explore other models or specialized architectures that excel in handling small objects, such as RetinaNet or EfficientDet.

I hope this clarifies the performance considerations of YOLOv8 on small objects. Let me know if you have any further questions or need additional assistance.

Best regards,
Glenn Jocher

**Comment by glenn-jocher** [comment]
@abraha2d I've got a question for you. I discovered a bug in our Anaconda builds that I fixed in https://github.com/conda-forge/ultralytics-feedstock/pull/59, but I also realized that this should have been failing the tests we placed in the `recipe/meta.yaml` and apparently it was building and deploying anyways. 

So it seems like either the tests are not running or conda is deploying with failing tests. I'd like to expand the **conda build tests to the full suite of tests** we have that we normally run with `pytest ultralytics/tests`. Can you help me make this update in https://github.com/conda-forge/ultralytics-feedstock?

**Comment by abraha2d** [comment]
Hi @glenn-jocher, started a PR to add the pytest suite to the feedstock build.
It looks like at least some of the tests require CUDA devices to be present?
See https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=777704&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=1569

**Comment by glenn-jocher** [comment]
Thanks buddy. There are tests in tests/test_cuda.py but these do not run in non-CUDA environments like the CI actions runners. 

I'll take a look at the azure results there to see what might be going wrong.
