### ISSUE TITLE
The conf composition during the inference process in YOLOV8

### ISSUE THREAD

**Issue by huaiguang233** [ultralytics/ultralytics#16222]
### Search before asking

- [ ] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello，
I have some questions about the conf in the inference process , mentioned in #4149, "the confidence score essentially becomes the product of the box confidence and the class confidence."  However, I found no trace of box confidence in the code.  In the non_max_suppression function of ops.py:  " box, cls, mask = x.split((4, nc, nm), 1)" and "conf, j = cls.max(1, keepdim=True)". There doesn't seem to be an operation on the product. If it is convenient for you, can you tell me where in the code the box confidence is located. Thanks.

**Comment by huaiguang233** [comment]
Thank you very much for your answer. This question has been bothering me all night.

**Comment by glenn-jocher** [comment]
@huaiguang233 you're welcome! If you have any more questions, feel free to ask.
