### ISSUE TITLE
How to use Tensorrt 10 in C++API  to action a segment task 

### ISSUE THREAD

**Issue by Zerocheng001** [ultralytics/ultralytics#16221]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I can use tensorrt to generate engine and infter the result ，but how can I get the  x,y,width,height,confidence,classid and mask

**Comment by glenn-jocher** [comment]
@Zerocheng001 to extract x, y, width, height, confidence, class ID, and mask from a TensorRT engine in C++, you'll need to parse the output tensors according to your model's output format. For detailed guidance, refer to the TensorRT documentation and ensure your model's output layers are correctly mapped.
