### ISSUE TITLE
Regarding confusion matrices and accuracy in test data

### ISSUE THREAD

**Issue by aakashthapa22** [ultralytics/ultralytics#16224]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I split the data into training, validation and testing. While using 

!yolo task=detect mode=val model={HOME}/runs/detect/train_mid_final/weights/best.pt data={HOME}/data.yaml 

the resulting folder has confusion matrices, f1,pr,r curves along with value of evaluation metrices for eg.

                   all        250      15740      0.998      0.996      0.995      0.991
                  Dead         38         48      0.997          1      0.995      0.991
               Healthy        247      13947      0.997      0.997      0.995      0.995
               
However, when i write code for prediction
!yolo task=detect mode=predict model={HOME}/runs/detect/train_mid_final/weights/best.pt source={HOME}/palm-tree-5/test/images save=True

ther code only gives resulting folder of test with predictions of boxes but not confusion matrices and curves and evaluation metrices values. how do i get such values and figures?

**Comment by Y-T-G** [comment]
You only get those with `mode=val` which runs validation, not `mode=predict` which is simply prediction. Why do you want to use `mode=predict` to get those?

**Comment by Y-T-G** [comment]
Are you trying run validation on the `test` set?

Then you just need to pass `split=test` to the first command.

**Comment by aakashthapa22** [comment]
I am doing an application-based work where I need to find accuracy (precision, recall, and map) on test dataset too.. 

I just checked using split=test at the end of the code line and it works.

**Comment by glenn-jocher** [comment]
@aakashthapa22 great to hear that using `split=test` worked for you! If you have any more questions, feel free to ask.
