### ISSUE TITLE
run "pip install ultralytics" on a cpu-only server still install cuda-related modules

### ISSUE THREAD

**Issue by itsrealkk** [ultralytics/ultralytics#16230]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Install

### Bug

I'm installing ultralytics module on my CPU-ONLY server, but i found that the pip also installed cuda-related modules.
why did pip still install cuda-related modules on a non-nvidia GPU device
![image](https://github.com/user-attachments/assets/3959882d-9fdf-4d1a-8d19-63f3e275bcd2)

### Environment

```
Ultralytics YOLOv8.2.92 🚀 Python-3.11.9 torch-2.4.1+cu121 CPU (Intel Xeon Gold 6133 2.50GHz)
Setup complete ✅ (2 CPUs, 1.7 GB RAM, 21.1/49.1 GB disk)

OS                  Linux-6.8.0-44-generic-x86_64-with-glibc2.39
Environment         Linux
Python              3.11.9
Install             pip
RAM                 1.67 GB
CPU                 Intel Xeon Gold 6133 2.50GHz
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.4.1>=1.8.0
torchvision         ✅ 0.19.1>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.6>=2.0.0
torch               ✅ 2.4.1!=2.4.0,>=1.8.0; sys_platform == "win32"
```

### Minimal Reproducible Example

```
pip install ultralytics
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by itsrealkk** [comment]
neofetch info
![image](https://github.com/user-attachments/assets/c19d03cd-9c95-4e10-9f51-faf7bc04006c)

**Comment by Y-T-G** [comment]
It's something done by `pip` while installing `torch`. `ultralytics` isn't specifying them to be installed.

**Comment by glenn-jocher** [comment]
@Y-T-G @itsrealkk if you want to force CPU-only torch versions run `pip install ultralytics --index-url https://download.pytorch.org/whl/cpu`

**Comment by tothadi** [comment]
> [@Y-T-G](https://github.com/Y-T-G) [@itsrealkk](https://github.com/itsrealkk) if you want to force CPU-only torch versions run `pip install ultralytics --index-url https://download.pytorch.org/whl/cpu`

There's no ultralytics package in this index.

**Comment by glenn-jocher** [comment]
You're right @tothadi - the solution needs to be different since ultralytics isn't in PyTorch's index. The correct approach is to install the CPU-only PyTorch first, then ultralytics:

```
# First install CPU-only PyTorch
pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu

# Then install ultralytics
pip install ultralytics
```

This way, pip will skip reinstalling PyTorch since a compatible version is already present, and you'll avoid the CUDA dependencies entirely.

**Comment by ocanevet** [comment]
With flag `--extra-index-url` instead of `--index-url` you can do it in one command:

```
pip install --extra-index-url https://download.pytorch.org/whl/cpu torch torchvision numpy ultralytics
```

**Comment by glenn-jocher** [comment]
@ocanevet excellent point! Using `--extra-index-url` is indeed more elegant than the two-step approach. This allows pip to check both PyPI for ultralytics and the PyTorch CPU index for torch/torchvision in a single command, ensuring CPU-only versions are installed.
