### ISSUE TITLE
YOLOv8-OBB angle convertion

### ISSUE THREAD

**Issue by JasonSloan** [ultralytics/ultralytics#16235]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Im confused about the angle convertion during the training process.
During the training process, the code converts the xyxyxyxy format label to xywhr format with opencv's minAreaRect API, which the angle ranges from [0, pi/2) according to the docs in opencv. However, the angle ranges in model prediction which is [-pi/4, pi3/4) is different from the label. Why keep this inconsistence?

the function that convert label from xyxyxyxy2xywhr:
![image](https://github.com/user-attachments/assets/45af1d60-0a13-43c6-bc03-05a1f9cb027a)

the forward function of OBB head:
![image](https://github.com/user-attachments/assets/5884788b-fab9-4d87-9f1f-4cec190c51b0)
        
  Thanks a lot!

**Comment by glenn-jocher** [comment]
@JasonSloan the angle inconsistency is due to different conventions used during label conversion and model prediction. This approach helps in handling various object orientations effectively. For more details, you can refer to the documentation on OBB datasets.

**Comment by Petros626** [comment]
@JasonSloan Hey
