### ISSUE TITLE
AttributeError: 'AutoBackend' object has no attribute 'task' & WARNING  Metadata not found for 'model=best.onnx' 

### ISSUE THREAD

**Issue by Haseeeb21** [ultralytics/ultralytics#16234]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained a yolov8n segmentation model and also exported it in onnx format using export function.

The following code is given when I run it first it prints `WARNING  Metadata not found for 'model=best.onnx' ` and then 
`AttributeError: 'AutoBackend' object has no attribute 'task'`

Code:

from ultralytics import YOLO

onnx_model = YOLO('best.onnx', task='segment')

results = onnx_model("image_0.jpg")

Output:

Loading best.onnx for ONNX Runtime inference...
WARNING  Metadata not found for 'model=best.onnx'

AttributeError                            Traceback (most recent call last)
Cell In[5], [line 7](vscode-notebook-cell:?execution_count=5&line=7)
      [4](vscode-notebook-cell:?execution_count=5&line=4) onnx_model = YOLO('best.onnx', task='segment')
      [6](vscode-notebook-cell:?execution_count=5&line=6) # Run inference
----> [7](vscode-notebook-cell:?execution_count=5&line=7) results = onnx_model("image_0.jpg")

Can we not use onnx models for inference? As I want to use it on an edge device

### Additional

Can we use onnx model (trained for segmentation) on edge devices like `andorid` and `ios`.

**Comment by Haseeeb21** [comment]
> Can you provide the output after running this command in terminal: `yolo checks`?
> 
> And also your export code.
YOLO checks output:
[2K
[2K
Ultralytics YOLOv8.2.92 🚀 Python-3.11.9 torch-2.4.1+cpu CPU (Intel Core(TM) i7-8750H 2.20GHz)
Setup complete ✅ (12 CPUs, 15.9 GB RAM, 214.5/232.0 GB disk)

OS                  Windows-10-10.0.22631-SP0
Environment         Windows
Python              3.11.9
Install             pip
RAM                 15.85 GB
CPU                 Intel Core(TM) i7-8750H 2.20GHz
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.4.1>=1.8.0
torchvision         ✅ 0.19.1>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.6>=2.0.0
torch               ✅ 2.4.1!=2.4.0,>=1.8.0; sys_platform == "win32"




export code:

from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO("best.pt")

# Export the model to ONNX format
model.export(format="onnx")  # creates 'yolov8n.onnx'

**Comment by Y-T-G** [comment]
Does it load if you export the pretrained model?

`model = YOLO("yolov8n.pt")`

**Comment by Haseeeb21** [comment]
@Y-T-G yes it downloaded.

**Comment by Y-T-G** [comment]
Did you export the pretrained model as ONNX and try to load it as ONNX? Does it work?

**Comment by Haseeeb21** [comment]
@Y-T-G As I have mentioned I have trained a segmentation model for that obviously I have loaded a pretrained [YOLOv8n-seg](https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8n-seg.pt) model and after training I obtained best.pt and loaded this model to predict on image first and then exported as in the above code.

**Comment by Y-T-G** [comment]
I want to know if the original pretrained model loads correctly as ONNX. Or both `best.onnx` and the original `yolov8n.onnx` fails to load.

**Comment by Haseeeb21** [comment]
> I want to know if the original pretrained model loads correctly as ONNX. Or both `best.onnx` and the original `yolov8n.onnx` fails to load.

This cell runs without any issue,

model = YOLO("best.onnx", task='segment')

**Comment by Y-T-G** [comment]
1. Export `yolov8n-seg.pt` as ONNX.
2. Load the exported `yolov8n-seg.onnx`.
3. Perform inference.

Does it show the same error?

**Comment by Y-T-G** [comment]
Does tour `last.pt` also show the same error on ONNX inference?


You can try inference by specifying `data=your_data.yaml`.

`model.predict(..., data=your_data.yaml)`

**Comment by Haseeeb21** [comment]
> Does your `last.pt` also show the same error on ONNX inference?
> 
> You can try inferencing by specifying `data=your_data.yaml`.
> 
> `model.predict(..., data=your_data.yaml)`


I replaced the model with last.onnx it worked but the results are not good.

Anyway why is it the best.onnx is not working (Metadata not found) and last.onnx is working without any error.

**Comment by Y-T-G** [comment]
It probably didn't save correctly

**Comment by Haseeeb21** [comment]
Yes its working now, 
correct code:

from ultralytics import YOLO

# Load the exported ONNX model
onnx_model = YOLO('best.onnx', task='segment')

# Run inference
results = onnx_model.predict(source='img_0.jpg', save=True, imgsz=640)

**Comment by glenn-jocher** [comment]
Great to hear it's working! If you have any more questions, feel free to ask.
