### ISSUE TITLE
Warning generated by RT-DETR training

### ISSUE THREAD

**Issue by 733ly** [ultralytics/ultralytics#16231]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![82cee482-eb9b-4ea7-8d11-36faf19f00d6](https://github.com/user-attachments/assets/39e29c03-2645-42e7-8242-3d4e36562f7e)
"I encountered this error while training RT-DETR: 'WARNING ⚠️ no model scale passed. Assuming scale='l'.' How can I resolve this?"

**Comment by Y-T-G** [comment]
You can load it using `model = RTDETR("rtdetr-l.pt")`
