### ISSUE TITLE
In a YOLOv8 segmentation task, does resizing images affect the accuracy of the ground truth mask, and can it cause the ground truth polygon to shift?

### ISSUE THREAD

**Issue by litengfeigithub** [ultralytics/ultralytics#16240]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In a YOLOv8 segmentation task, does resizing images affect the accuracy of the ground truth mask, and can it cause the ground truth polygon to shift?

**Comment by Y-T-G** [comment]
Not by a lot. The labels are normalized, so not bound the original image size
