### ISSUE TITLE
_reach_out_prediction_result

### ISSUE THREAD

**Issue by ilhansevval** [ultralytics/ultralytics#1624]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, In the #1483 issue @glenn-jocher shared validation results. Thanks to this I finally reach out the precision and recall results for validation. Could you please share this results for training and prediction. Thank you

**Comment by glenn-jocher** [comment]
@ilhansevval if you're asking about `predict` results, see https://docs.ultralytics.com/modes/predict/#working-with-results

train results are val results from final epoch.

**Comment by ilhansevval** [comment]
I searched the document. I want to reach out precision recall results and f1 score. 

`metrics.box.update(results)` 

I used this because you mention in metrics.py file but i got this error:

cannot unpack non-iterable NoneType object 

@glenn-jocher

**Comment by glenn-jocher** [comment]
```python
from ultralytics import YOLO

model = YOLO()
metrics=model.val(data='coco8.yaml')

print(vars(metrics.box))
```

**Comment by ilhansevval** [comment]
Also could you please tell me how can i use this method:

`result.boxes.conf.masked_scatter()`

I couldn't define arguments in right way 

@glenn-jocher

**Comment by glenn-jocher** [comment]
@ilhansevval result.boxes.conf is just a torch Tensor, and masked_scatter() is a torch Tensor method. For Usage with this method see torch docs:
https://pytorch.org/docs/stable/generated/torch.Tensor.masked_scatter.html

**Comment by glenn-jocher** [comment]
@ilhansevval I've implemented improved printing of results and metrics in https://github.com/ultralytics/ultralytics/pull/1616 for release with 8.0.57 in the next few days.
