### ISSUE TITLE
Is it possible to stratify metrics?

### ISSUE THREAD

**Issue by Dapid** [ultralytics/ultralytics#16268]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My data comes from different locations. Right now, the relevant bit of my `dataset.yaml` looks like:

```
train:
  [ obj_Train_A_data,
    obj_Train_B_data]
val:
  [ obj_Test_A_data,
    obj_Test_B_data ]
```

That loads the data from both sites, and reports the aggregated performance.

I'd like to see not just the average progress, but also the metrics for both A and B separately, in order to see if any site is harder than the other, or the imbalance between them is affecting us.

Is this possible?

**Comment by Y-T-G** [comment]
You can create a new `yaml` for each and run `model.val` on them.

**Comment by Dapid** [comment]
But that gives me just the final result, not the training curve.

**Comment by Y-T-G** [comment]
Validating on two different datasets during training isn't supported.
