### ISSUE TITLE
How to use yolov8 algorithm combined with botsort algorithm to obtain video tracking results and obtain detailed tracking result files for subsequent tracking algorithm evaluation？

### ISSUE THREAD

**Issue by lmaple24327** [ultralytics/ultralytics#16289]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

from ultralytics import YOLO

# 加载预训练模型
model = YOLO("runs/last.pt")

# 进行跟踪
model.track(
    source=r"C:\Users\admin\Desktop\datasets\VIS_Onshore\Videos\MVI_1622_VIS.avi",
    tracker="ultralytics/cfg/trackers/botsort.yaml",
    save=True
)

**Comment by UltralyticsAssistant** [comment]
👋 Hello @lmaple24327, thank you for reaching out to Ultralytics 🚀! An Ultralytics engineer will assist you soon.

In the meantime, we recommend checking out our [Docs](https://docs.ultralytics.com) where you can find many [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples that might help. 

If your query involves a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) so we can assist you more effectively.

If you are working on custom training and have ❓ Questions regarding this, it would be really helpful if you could provide as much information as possible, including dataset image examples and training logs. Make sure to follow our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

Feel free to join our community for more discussions or help:
- For real-time chat, head to [Discord](https://ultralytics.com/discord) 🎧.
- For in-depth conversations, visit our [Discourse](https://community.ultralytics.com).
- Join discussions and share knowledge on our [Subreddit](https://reddit.com/r/ultralytics).

## Install

You can pip install the `ultralytics` package along with all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/).

```bash
pip install ultralytics
```

## Environments

YOLOv8 can be run in these environments:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, our [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are passing, which verify the correct operation of all YOLOv8 [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) on macOS, Windows, and Ubuntu every 24 hours and on each commit.

**Comment by Skillnoob** [comment]
You can add `save_txt=True` or process the `results` object to get boxes + track id's etc. Check out the [predict docs](https://docs.ultralytics.com/modes/predict/) on how to process the results.

**Comment by lmaple24327** [comment]
> You can add `save_txt=True` or process the `results` object to get boxes + track id's etc. Check out the [predict docs](https://docs.ultralytics.com/modes/predict/) on how to process the results.

Thank you very much for your help. Through the way you mentioned, I now get the txt file of the tracking result, but the tracking result does not contain the confidence degree of the target detected in each frame, may I ask how to get the confidence degree at the same time?

**Comment by glenn-jocher** [comment]
To include confidence scores in the tracking results, ensure your tracking configuration or script is set to save confidence values. You can modify the code to extract and save these details from the `results` object.

**Comment by Skillnoob** [comment]
Add `save_conf=True` as well. The argument is listed in the "visualization arguments" in the documentation I linked earlier.

**Comment by lmaple24327** [comment]
> Add `save_conf=True` as well. The argument is listed in the "visualization arguments" in the documentation I linked earlier.

Thank you so much. You're amazing. Thank you for your help.

**Comment by Skillnoob** [comment]
No problem. You can close the issue if everything is resolved.
