### ISSUE TITLE
Region counter

### ISSUE THREAD

**Issue by MuhammedEnesGurkan** [ultralytics/ultralytics#16292]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi i use object counter and tracking for sheep counting but it cannot count the sheeps properly.For in and out. Can you suggest any idea for code below.

### Additional

import cv2
import geocoder
from ultralytics import YOLO
from ultralytics.solutions import object_counter

def location_send():
    # IP adresi kullanarak mevcut konumu al
    g = geocoder.ip('me')

    # Enlem ve boylam bilgilerini yazdır
    ll = g.latlng
    el = g.address
    return f"Konumunuzun enlem ve boylam bilgileri:{ll}\n Konumuzun adresi:{el}"

def count_objects_in_region(video_path, output_video_path, model_path):
    classes_to_count = [18]
    out_count = 0
    """Count objects in a specific region within a video."""
    model = YOLO(model_path)
    cap = cv2.VideoCapture(video_path)
    assert cap.isOpened(), "Error reading video file"
    w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))
    region_points = [(40, 150), (300, 150),(300,350),(40,350)]
    video_writer = cv2.VideoWriter(output_video_path, cv2.VideoWriter_fourcc(*"mp4v"), fps, (w, h))
    counter = object_counter.ObjectCounter()
    # sheep = model.names.get(18)
    counter.set_args(view_img=True, reg_pts=region_points, classes_names=model.names, draw_tracks=True, line_thickness=2,)

    while True:
        success, im0 = cap.read()
        if not success:
            print("Video frame is empty or video processing has been successfully completed.")
            break
        tracks = model.track(im0,persist=True,show=False,classes=classes_to_count,conf=0.2)
        im0 = counter.start_counting(im0, tracks)
        video_writer.write(im0)

        if counter.out_counts > out_count :
            out_count += 1
            location=location_send()
            print(location)
            print(out_count,counter.out_counts)
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break

    cap.release()
    video_writer.release()
    cv2.destroyAllWindows()

count_objects_in_region(0, "output_video.avi", "yolov8s.pt")

**Comment by Y-T-G** [comment]
What's the issue you're having?

**Comment by RizwanMunawar** [comment]
@MuhammedEnesGurkan Hi! Thank you for bringing up the issue you're experiencing and sharing the initial details. Could you please provide more specific information so we can better understand and reproduce the problem? Currently, with just the details on incorrect `in_counts` and `out_counts`, it's difficult to test accurately. For your reference, I tested it with a sample video, and everything appears to be functioning well on my end.

@Y-T-G Hey there! I've added the `solutions` label to help me track it more easily :)
