### ISSUE TITLE
Resume issue

### ISSUE THREAD

**Issue by Laughing-q** [ultralytics/ultralytics#163]
@AyushExel @glenn-jocher 
Got incorrect results after resuming, the mAP before resume was 36.2 but it went to wrong after I started a resuming training(DDP mode).
![image](https://user-images.githubusercontent.com/61612323/211308082-bd48d047-c4cc-4fa6-b99e-5a356701eeac.png)
command:
```bash
yolo task=detect mode=train model=last.pt data=coco.yaml resume=True device=\'0,1,2,3\'
```
We can fix this later sometime as we also need to update the usage of resume(passing `resume=last.pt` instead if `model=last.pt`).
Just open this issue in case we forget. :)

**Comment by dungviet112** [comment]
@Laughing-q Hi. I have an issue with the resume method. When I continue training it takes so much more time for each epoch than before (1.3s/it vs 30s/it). I'm using Colab with this command:
`!yolo task=detect \
mode=train \
model=yolov8n.pt \
data=data.yaml \
epochs=50 \
batch=32 \
imgsz=640 \
v5loader=True`
![Screenshot 2023-01-17 143441](https://user-images.githubusercontent.com/72445774/212836687-9a7a864c-7b9f-4f49-af38-7c892e98e62e.png)
`!yolo task=detect \
mode=train \
model=runs/detect/train/weights/last.pt\
data=data.yaml \
resume=True`
![image](https://user-images.githubusercontent.com/72445774/212837195-56baaa9a-abe8-4169-858d-ccc78e6e3b3b.png)

**Comment by Robotatron** [comment]
@dungviet112 is there any advantage of using `v5loader=True` ?
