### ISSUE TITLE
Why image size is changing when model.predict?

### ISSUE THREAD

**Issue by Haseeeb21** [ultralytics/ultralytics#16339]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained a YOLOv8n-seg model. My dataset images size was 750 (width) x 1000 (height), during training in `model.train` the imgsz is 640, this means the model is trained on images being resized to 640 x 640.
Now the model is trained and I am using the predict method on real time camera feed, this is output shape.
`1/1: 0... Success  (inf frames of shape 640x480 at 30.00 FPS)`
1. Why is it reshaped to 640 x 480? 
2. Is this 640 (width) x 480 (height)?
3. Does this effect the model performance on detecting the object?

Even after explicitly mentioning 640 it still shows output in `640x480`

**Code:**
results = model.predict(source="0", show=True, imgsz=(640, 640), conf=0.5)

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Haseeeb21, thank you for reaching out to Ultralytics 🚀! We suggest checking out the [Docs](https://docs.ultralytics.com) for comprehensive usage examples, which might help clarify common questions.

If this is a 🐛 Bug Report, we encourage you to provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to assist us in diagnosing the issue more effectively.

For custom training ❓ Questions, please include detailed information, such as dataset image samples and training logs, and ensure you follow our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

You can engage with the Ultralytics community in several ways:
- Join our [Discord](https://ultralytics.com/discord) 🎧 for real-time conversations.
- Participate in in-depth talks on [Discourse](https://community.ultralytics.com).
- Explore threads and share your experiences on the [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade

Please make sure to upgrade to the latest `ultralytics` package and verify your environment's requirements using:

```bash
pip install -U ultralytics
```

You'll need a [Python>=3.8](https://www.python.org/) environment with [PyTorch>=1.8](https://pytorch.org/get-started/locally/).

## Environments

You can run YOLOv8 in these verified environments with all dependencies preinstalled:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/).
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/).
- **Docker Image**. Guidance available in the [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

This indicates the status of our continuous integration tests to ensure everything operates smoothly across different platforms.

This response is automated, but rest assured, an Ultralytics engineer will assist you shortly. 😊

**Comment by Y-T-G** [comment]
The difference is due to how preprocessing is handled when you inference use the PyTorch model. You can read the explanation [here](https://github.com/ultralytics/ultralytics/issues/14733#issuecomment-2254102334).

Here the original image is of resolution 1280x720. Now to preserve the aspect ratio, you will first resize to 640x360:

![image0 (1).png](https://github.com/user-attachments/assets/d698e054-cb01-47ef-b423-07a98b06e8f2)


But YOLO requires both sides to be divisible by 32. So it will pad until it reaches 384.

In both cases, the original image was resized to 640x360. The only difference was in padding.
