### ISSUE TITLE
Pose mAP computation

### ISSUE THREAD

**Issue by Haozong-Zeng** [ultralytics/ultralytics#16351]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

YOLO pose model provides a metrics of pose mAP. From literatures, a common precision measure in human pose estimation is the mean average precision (mAP) which is the percentage of correctly estimated joints. Typically, a joint position is considered as correctly estimated, if it is within a certain range of the ground truth. I just want to check if mAP in YOLO pose model is also defined like that and if so, what is such "range"? Thanks.

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Haozong-Zeng, thank you for your question about the pose mAP in the YOLO model 🚀! While we can't delve into specifics here, I'll make sure an Ultralytics engineer will assist you soon.

In the meantime, you may find helpful information in our [Docs](https://docs.ultralytics.com), where there might be relevant details about the mAP computation for pose models.

If this is a ❓ question about custom metrics, you could also provide more context or examples to help us understand better.

For real-time discussions, join us on [Discord](https://ultralytics.com/discord) 🎧, or engage with our community on [Discourse](https://community.ultralytics.com) or [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade

Please ensure you're using the latest version of the `ultralytics` package, as improvements and fixes are continuously integrated:

```bash
pip install -U ultralytics
```

## Environments

Experiment with our verified environments:

- **Notebooks**: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all our tests are passing!

Thank you for your patience and contribution to the Ultralytics community 🌟!

**Comment by Y-T-G** [comment]
The metrics are processed here:
https://github.com/ultralytics/ultralytics/blob/6dcc4a0610bf445212253fb51b24e29429a2bcc3/ultralytics/models/yolo/pose/val.py#L159

The keypoint IOU is calculated here:
https://github.com/ultralytics/ultralytics/blob/6dcc4a0610bf445212253fb51b24e29429a2bcc3/ultralytics/utils/metrics.py#L151

There are no joint metrics being used.
