### ISSUE TITLE
When training Multiple Dataset that share same Class labels, How the Confidence Scores computed?

### ISSUE THREAD

**Issue by Nadayz** [ultralytics/ultralytics#16364]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I have the following data.yaml file 
![image](https://github.com/user-attachments/assets/e1f6c426-c5f9-40df-b72f-06548f5ae016)

using it to train YOLOv8 on these 3 datasets, but all share the same labeling.
How does the Confidence Scores computed in this scenario?
![val_batch2_pred](https://github.com/user-attachments/assets/a41487f3-cc05-4256-8839-1d703666322c)

And when It's Scanning the data it consider on Action1 labels but compute the total number of images over the 3 dataset
![image](https://github.com/user-attachments/assets/527da1eb-7ea9-4b3c-a4d5-ba18d7828d63)
Can someone explain to me, please?

Thanks

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Nadayz, thank you for reaching out to Ultralytics 🚀!

We suggest checking our [Docs](https://docs.ultralytics.com) for guidance on training with multiple datasets. There, you can find relevant [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) examples.

For custom training inquiries like yours, please include as much detail as possible. This can include dataset samples, training logs, and confirmation that you've followed our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/) 🏆.

An Ultralytics engineer will assist you soon. Meanwhile, you might also want to engage with our community on [Discord](https://ultralytics.com/discord) 🎧 or join discussions on [Discourse](https://community.ultralytics.com) or [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade

To ensure your issue isn't resolved in the latest version, please update to the latest `ultralytics` package including all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment:

```bash
pip install -U ultralytics
```

## Environments

Run YOLOv8 in these environments (with CUDA/CUDNN, Python, and PyTorch preset):

- **Notebooks** with free GPU support: [Gradient](https://console.paperspace.com/github/ultralytics/ultralytics), [Colab](https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb), [Kaggle](https://www.kaggle.com/ultralytics/yolov8)
- **Google Cloud**: [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon**: [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**: [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

This badge indicates if all [CI tests](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) are passing, confirming proper operation across modes and tasks on various platforms.
