### ISSUE TITLE
KeyError when try to convert COCO Dataset Format to YOLO Format

### ISSUE THREAD

**Issue by LittlePotatoChip** [ultralytics/ultralytics#16363]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I downloaded the annotions from coco website [https://cocodataset.org/#download](url)，whose file structure is：

annotions
|-----captions_train2017.json
|-----captions_val2017.json
|-----instances_train2017.json
|-----instances_val2017.json
|-----person_keypoints_train2017.json
|-----person_keypoints_val2017.json

I downloaded this files because I want to use 2017 train images and val images
![image](https://github.com/user-attachments/assets/882053e4-45d1-4444-87d4-6c364558fa16)

I tried to use this code to convert them as [websites](https://docs.ultralytics.com/datasets/detect/) :

`from ultralytics.data.converter import convert_coco
convert_coco(labels_dir="/home/potato/workplace/datasets/coco/labels/annotations/")`

but it returned an error:
`Annotations /home/potato/workplace/datasets/coco/labels/annotations/captions_train2017.jso
Traceback (most recent call last):
  File "/home/potato/workplace/datasets/coco/convert_coco_to_yolo.py", line 3, in <module>
    convert_coco(labels_dir="/home/potato/workplace/datasets/coco/labels/annotations/")
  File "/home/potato/workplace/yolov10/ultralytics/data/converter.py", line 275, in convert_coco
    if ann["iscrowd"]:
KeyError: 'iscrowd'
`
so I openned the above 6 documents and found that only the last two files contain 'iscrowd' while the first 4 files not.

Am I using the right data set？

**Comment by UltralyticsAssistant** [comment]
👋 Hello @LittlePotatoChip, thank you for reaching out to us at Ultralytics 🚀!

We see you're encountering a KeyError when converting COCO annotations to YOLO format. If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us diagnose the problem accurately. This will aid our engineers in assisting you effectively.

Here's a quick tip: It seems like your issue might be related to the specific JSON files you're using (e.g., `captions_train2017.json` does not contain the 'iscrowd' key, which might be causing the error). Make sure to use the correct annotation files intended for object detection.

For more interactive support or to chat in real-time, consider joining our [Discord](https://ultralytics.com/discord) 🎧. If in-depth conversation is your style, explore topics on [Discourse](https://community.ultralytics.com) or check out our [Subreddit](https://reddit.com/r/ultralytics) for community insights.

## Upgrade

Ensure you have the latest version of the `ultralytics` package along with all required dependencies by upgrading your installation. This is recommended to confirm that your issue isn't already resolved:

```bash
pip install -U ultralytics
```

Running YOLOv8 is possible in various verified environments. Explore platforms like Google Colab or Kaggle, which offer free GPU resources to test your workflows:

- **Notebooks**: <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

An Ultralytics engineer will review your issue soon. In the meantime, feel free to explore our [Docs](https://docs.ultralytics.com) for more information on using COCO datasets and converting formats.

Thanks for your patience and happy coding! 😊

**Comment by LittlePotatoChip** [comment]
> 👋 Hello @LittlePotatoChip, thank you for reaching out to us at Ultralytics 🚀!
> 
> We see you're encountering a KeyError when converting COCO annotations to YOLO format. If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us diagnose the problem accurately. This will aid our engineers in assisting you effectively.
> 
> Here's a quick tip: It seems like your issue might be related to the specific JSON files you're using (e.g., `captions_train2017.json` does not contain the 'iscrowd' key, which might be causing the error). Make sure to use the correct annotation files intended for object detection.
> 
> For more interactive support or to chat in real-time, consider joining our [Discord](https://ultralytics.com/discord) 🎧. If in-depth conversation is your style, explore topics on [Discourse](https://community.ultralytics.com) or check out our [Subreddit](https://reddit.com/r/ultralytics) for community insights.
> 
> ## Upgrade
> Ensure you have the latest version of the `ultralytics` package along with all required dependencies by upgrading your installation. This is recommended to confirm that your issue isn't already resolved:
> 
> ```shell
> pip install -U ultralytics
> ```
> 
> Running YOLOv8 is possible in various verified environments. Explore platforms like Google Colab or Kaggle, which offer free GPU resources to test your workflows:
> 
> * **Notebooks**: [![Open In Colab](https://camo.githubusercontent.com/96889048f8a9014fdeba2a891f97150c6aac6e723f5190236b10215a97ed41f3/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/c7135949c5c6882489e68f4af05a78a759460a4db256b86df3097e04419b4d9e/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/ultralytics/yolov8)
> 
> An Ultralytics engineer will review your issue soon. In the meantime, feel free to explore our [Docs](https://docs.ultralytics.com) for more information on using COCO datasets and converting formats.
> 
> Thanks for your patience and happy coding! 😊

I upgraded the ultralytics to the latest version，now the Dependencies is :
`torch == 2.0.1
ultralytics == 8.2.97`

and tried it again,
`
from ultralytics.data.converter import convert_coco

convert_coco(labels_dir="/home/potato/workplace/datasets/coco/labels/annotations/")
`

it returned a new error:
`
Annotations /home/potato/workplace/datasets/coco/labels/annotations/captions_train2017.jso
Traceback (most recent call last):
  File "/home/potato/workplace/datasets/coco/convert_coco_to_yolo.py", line 3, in <module>
    convert_coco(labels_dir="/home/potato/workplace/datasets/coco/labels/annotations/")
  File "/home/potato/anaconda3/envs/yolov10/lib/python3.9/site-packages/ultralytics/data/converter.py", line 290, in convert_coco
    box = np.array(ann["bbox"], dtype=np.float64)
KeyError: 'bbox'
`

**Comment by Y-T-G** [comment]
You could only be converting the `instances_*.json` file because that's the one with the relevant annotations.

Ultralytics already has the COCO dataset converted and ready to download. You just need to specify `data="coco.yaml"` in `model.train()` to download it automatically.

**Comment by LittlePotatoChip** [comment]
> You could only be converting the `instances_*.json` file because that's the one with the relevant annotations.

can it downloads the label.txt automaticly?

**Comment by Y-T-G** [comment]
Yes

**Comment by LittlePotatoChip** [comment]
> Yes

ths， I used the following coding to train:

`from ultralytics import YOLOv10

model = YOLOv10('yolov10n.pt')
model.train(data = 'coco.yaml',epochs = 500, batch = 256)`

It still printed the error:
`Dataset 'coco.yaml' images not found ⚠️, missing path '/home/potato/workplace/datasets/coco/val2017.txt'`

`FileNotFoundError: train: Error loading data from /home/potato/workplace/datasets/coco/train2017.txt
See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.`

**Comment by Y-T-G** [comment]
Did it download it?

**Comment by glenn-jocher** [comment]
It seems like the dataset didn't download completely. Please ensure you have a stable internet connection and try running the command again. If the issue persists, you might need to manually download the dataset and configure the paths in your `coco.yaml` file.

**Comment by LittlePotatoChip** [comment]
> It seems like the dataset didn't download completely. Please ensure you have a stable internet connection and try running the command again. If the issue persists, you might need to manually download the dataset and configure the paths in your `coco.yaml` file.

[https://cocodataset.org/](url) does''t provide the txt file，and I can't find the ulr to download those txt files in the ultralytics ‘coco.yaml’

**Comment by Y-T-G** [comment]
You can try downloading the zip from here.

https://github.com/ultralytics/assets/releases/tag/v0.0.0

**Comment by LittlePotatoChip** [comment]
> You can try downloading the zip from here.
> 
> https://github.com/ultralytics/assets/releases/tag/v0.0.0

ths,it works

**Comment by glenn-jocher** [comment]
@LittlePotatoChip great to hear it worked! If you have any more questions, feel free to ask.
