### ISSUE TITLE
No labels found error during training

### ISSUE THREAD

**Issue by aw-wenntech** [ultralytics/ultralytics#1640]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to train a segmentation model. I am seeing the following error 

```python
optimizer: SGD(lr=0.01) with parameter groups 86 weight(decay=0.0), 97 weight(decay=0.0005), 96 bias
train: Scanning /home/ec2-user/SageMaker/roads/tiff/train/labels... 0 images, 11
train: WARNING ⚠️ No labels found in /home/ec2-user/SageMaker/roads/tiff/train/labels.cache. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data
train: New cache created: /home/ec2-user/SageMaker/roads/tiff/train/labels.cache
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/python3.7/site-packages/ultralytics/yolo/cfg/__init__.py", line 318, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/python3.7/site-packages/ultralytics/yolo/engine/model.py", line 329, in train
    self.trainer.train()
  File "/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/python3.7/site-packages/ultralytics/yolo/engine/trainer.py", line 191, in train
    self._do_train(world_size)
  File "/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/python3.7/site-packages/ultralytics/yolo/engine/trainer.py", line 266, in _do_train
    self._setup_train(world_size)
  File "/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/python3.7/site-packages/ultralytics/yolo/engine/trainer.py", line 249, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
  File "/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/python3.7/site-packages/ultralytics/yolo/v8/detect/train.py", line 44, in get_dataloader
    rect=mode == 'val', names=self.data['names'])[0]
  File "/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/python3.7/site-packages/ultralytics/yolo/data/build.py", line 86, in build_dataloader
    classes=cfg.classes)
  File "/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/python3.7/site-packages/ultralytics/yolo/data/dataset.py", line 67, in __init__
    classes)
  File "/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/python3.7/site-packages/ultralytics/yolo/data/base.py", line 48, in __init__
    self.labels = self.get_labels()
  File "/home/ec2-user/anaconda3/envs/amazonei_pytorch_latest_p37/lib/python3.7/site-packages/ultralytics/yolo/data/dataset.py", line 145, in get_labels
    raise FileNotFoundError(f'{self.prefix}No labels found in {cache_path}, can not start training. {HELP_URL}')
FileNotFoundError: train: No labels found in <dir>, can not start training. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data
```

I will say I am not entirely sure I have to yaml file corret.

I have three directories: val, test, train.

In each directory the following exists:
```python
- images (.jpg images)
- labels (.jpg masks)
- text_labels (.txt pixel locations for respective class)
```

I have tried training with the following yaml file:
```yaml
train: 
    - "train/images"
    - "train/text_labels"
val: 
    - "val/images"
    - "val/text_labels"
test: 
    - "test/images"
    - "test/text_labels"
# number of classes
nc: 1
# class names
names: 
    0: class1
```

I have tried a combination of things in this yaml from specifying images & masks, images & labels, and only images with rgb values. I am having no luck, would anybody have any ideas? Thanks!

### Additional

- Following my error into this code, I am fully not understanding what is happening here  either so this could be a lack of knowledge on my part.
```python
def get_labels(self):
        """Users can custom their own format here.
        Make sure your output is a list with each element like below:
            dict(
                im_file=im_file,
                shape=shape,  # format: (height, width)
                cls=cls,
                bboxes=bboxes, # xywh
                segments=segments,  # xy
                keypoints=keypoints, # xy
                normalized=True, # or False
                bbox_format="xyxy",  # or xywh, ltwh
            )
        """
```
- Also tried  to follow this yaml and still same error 
   - https://github.com/ultralytics/yolov5/blob/master/data/coco128-seg.yaml

**Comment by glenn-jocher** [comment]
@aw-wenntech your dataset is likely not structured corretly. Train first on coco8-seg.yaml to see what your Segment dataset should look like, and then mimic this format for your custom data:

```
yolo train model=yolov8n-seg.pt data=coco8-seg.yaml
```

**Comment by aw-wenntech** [comment]
> @aw-wenntech your dataset is likely not structured corretly. Train first on coco8-seg.yaml to see what your Segment dataset should look like, and then mimic this format for your custom data:
> 
> ```
> yolo train model=yolov8n-seg.pt data=coco8-seg.yaml
> ```

I appreciate the swift response. I will give this ago and close assuming it fixes... thanks!

**Comment by shangdongfeng** [comment]
I also encountered the same problem, and found that because the number of images and txt must be the same, and they correspond one to one, it is not a path problem。
see: ultralytics\yolo\data\dataset.py  
line132: 
print(self.im_files, 'self.im_files')
print(img2label_paths(self.im_files), 'img2label_paths(self.im_files)')
self.label_files = img2label_paths(self.im_files)

**Comment by aw-wenntech** [comment]
I was able to resolve this - bad data.yaml

**Comment by glenn-jocher** [comment]
@aw-wenntech glad to hear that you were able to resolve the issue! In YOLOv8, make sure to double-check your `data.yaml` file before training. Any problems, such as incorrectly-specified paths, classes, or augmentation parameters, can cause issues during training. Updating `data.yaml` with the correct information should resolve the problem.

**Comment by karelseaat** [comment]
Now im sure no one else would have this problem ;).
If your image and or label files are not of a numeric format (0.png, 1.png, 2.png) and (0.txt, 1.txt, 2.txt) this will happen.
Hope it helps.

**Comment by glenn-jocher** [comment]
@karelseaat thank you for contributing to the discussion and for sharing your insights. It's a valuable observation that files named using non-numeric formats may lead to unexpected behaviors. While YOLOv8 does support various naming conventions, ensuring consistency between the paired image and label files is essential for the data loader to function correctly. It's always a good practice to follow a systematic naming pattern and verify that each image file has a corresponding annotation file with the same base name. Your tip could indeed be helpful for users facing similar issues. We appreciate your efforts to assist the YOLOv8 community!
