### ISSUE TITLE
IEEE Reference Format:month should be "January" or "1" is correct

### ISSUE THREAD

**Issue by fppccc** [ultralytics/ultralytics#1643]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,
in IEEE Reference Formatmonth ,I was wondering if month should be "January" or "1" is correct?
Thank you very much.
bibtex :
-------------
@software{Jocher_YOLO_by_Ultralytics_2023,
author = {Jocher, Glenn and Chaurasia, Ayush and Qiu, Jing},
license = {GPL-3.0},
month = {1},
title = {{YOLO by Ultralytics}},
url = {https://github.com/ultralytics/ultralytics},
version = {8.0.0},
year = {2023}
}

**Comment by glenn-jocher** [comment]
@fppccc if you've copied it from the citation info in the repo then it should be correct.
