### ISSUE TITLE
Preprocessing step ? 

### ISSUE THREAD

**Issue by NguyenHongSon1103** [ultralytics/ultralytics#1644]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I saw an official example using opencv  but for some reason I want to run it directly in onnx.
My preprocessing code: 
Letterbox function copy from yolov5
`def letterbox(im, new_shape=(640, 640), color=(114, 114, 114), auto=True, scaleup=True, stride=32):
      # Resize and pad image while meeting stride-multiple constraints
      shape = im.shape[:2]  # current shape [height, width]
      if isinstance(new_shape, int):
          new_shape = (new_shape, new_shape)
  
      # Scale ratio (new / old)
      r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])
      if not scaleup:  # only scale down, do not scale up (for better val mAP)
          r = min(r, 1.0)
  
      # Compute padding
      new_unpad = int(round(shape[1] * r)), int(round(shape[0] * r))
      dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]  # wh padding
  
      if auto:  # minimum rectangle
          dw, dh = np.mod(dw, stride), np.mod(dh, stride)  # wh padding
  
      dw /= 2  # divide padding into 2 sides
      dh /= 2
  
      if shape[::-1] != new_unpad:  # resize
          im = cv2.resize(im, new_unpad, interpolation=cv2.INTER_LINEAR)
      top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
      left, right = int(round(dw - 0.1)), int(round(dw + 0.1))
      im = cv2.copyMakeBorder(im, top, bottom, left, right, cv2.BORDER_CONSTANT, value=color)  # add border
      return im, r, (dw, dh)`
And all preprocessing step:

`image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
  image, ratio, dwdh = letterbox(image, new_shape=(640, 640), auto=False)
  image = image.transpose((2, 0, 1))
  image = image.astype(np.float32) / 255.0
  input = np.expand_dims(image, 0)`

Other part like fit into model, nms and postprocessing, I use the same code in the official example.
Result seem fine but it still different with 
`model = YOLO('trained/weights')
  input = np.expand_dims(image, 0)
  result = self.model.predict(source=input, verbose=False)[0].cpu().numpy()
  boxes, scores, class_ids = result.boxes.xyxy.astype('int32'), result.boxes.conf,  result.boxes.cls.astype('int32')`

I want to ask if my preprocessing code is correct or not, I try to read the code base but still not sure
If not, please show me the correct one. Thank for your help

**Comment by AyushExel** [comment]
We also have an ONNX python example here - https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-OpenCV-ONNX-Python

**Comment by NguyenHongSon1103** [comment]
@AyushExel as I said I already see the example, but I don't want to run it with opencv. I tried to use the preprocessing part in that example, something like: 

        height, width = image.shape[:2]

        length = max((height, width))

        im = np.zeros((length, length, 3), np.uint8)

        im[0:height, 0:width] = image

        scale = length / 640

        tensor_in = cv2.dnn.blobFromImage(im, scalefactor=1 / 255.0, size=(640, 640))

and fit into onnx session.run. But result is not as same as YOLO().predict()

**Comment by MagicCodess** [comment]
> 



> We also have an ONNX python example here - https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-OpenCV-ONNX-Python

this code results differently from the yolov8 code's results

**Comment by MagicCodess** [comment]
https://github.com/ultralytics/ultralytics/pull/1747

**Comment by glenn-jocher** [comment]
@MagicCodess thank you for the PR!

@NguyenHongSon1103 see PR #1747 to solve your problem!

**Comment by MagicCodess** [comment]
> @MagicCodess thank you for the PR!
> 
> @NguyenHongSon1103 see PR #1747 to solve your problem!
@glenn-jocher previous PR committed by wrong account, I changed to this one.
https://github.com/ultralytics/ultralytics/pull/1780
