### ISSUE TITLE
The pre-training model is trained

### ISSUE THREAD

**Issue by liuppp1** [ultralytics/ultralytics#16454]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Because I want to implement the function of detecting vehicle spills, but the current yolov8x.pt does not support this function, so I built a data set myself to train it. After training, the model did realize vehicle spill detection, but the function of the model before training was lost, and the basic pedestrian detection could not be done. I think the possible reason is the poor quality of the data set. So I would like to ask: how to train the model while retaining the function of the model before and after training?

### Additional

Looking forward to your reply very much

**Comment by Y-T-G** [comment]
You will have to add pedestrian images to your dataset. The model only keeps what's in the dataset.
