### ISSUE TITLE
RGB infrared multimodal input

### ISSUE THREAD

**Issue by csh313** [ultralytics/ultralytics#16474]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I am preparing a topic on multimodal rotating box input, and I mainly want to add the information of infrared image to the original RGB image, and I would like to ask if it is possible to load infrared image by loading RGB when loading_image?

**Comment by UltralyticsAssistant** [comment]
👋 Hello @csh313, thank you for your interest in Ultralytics 🚀!

For those diving into multimodal input like combining RGB and infrared images, we suggest checking out the [Docs](https://docs.ultralytics.com). You can explore various [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples there, which may provide insights into your project.

If this is a 🐛 Bug Report, we kindly ask for a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to assist in debugging.

For custom training or other ❓ Questions, please give us as much context as possible, such as dataset samples and logs, and ensure you're following our [Model Training Tips](https://docs.ultralytics.com/guides/model-training-tips/).

Engage with the Ultralytics community:
- Join [Discord](https://ultralytics.com/discord) 🎧 for live chats.
- Visit [Discourse](https://community.ultralytics.com) for in-depth discussions.
- Share on our [Subreddit](https://reddit.com/r/ultralytics) for broader community feedback.

## Upgrade

Ensure your environment is up-to-date with the latest `ultralytics` package:

```bash
pip install -U ultralytics
```

## Environments

YOLOv8 supports these verified environments:

- **Notebooks**: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud**, **Amazon**, **Docker**: Check respective guides for setup.

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

An Ultralytics engineer will review your question soon. Thanks for your patience and contribution! 😊

**Comment by glenn-jocher** [comment]
To incorporate infrared data with RGB images, you can preprocess both modalities to create a combined input before feeding it into the model. This typically involves aligning and stacking the images into a multi-channel format.

**Comment by Y-T-G** [comment]
Duplicate of https://github.com/ultralytics/ultralytics/issues/6929
