### ISSUE TITLE
No metrics, train, val graph in ClearML

### ISSUE THREAD

**Issue by darouwan** [ultralytics/ultralytics#1647]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

No metrics, train, val graph display in clearml SCALARS section when training. Only :monitor:gpu and :monitor: machine can be seen. The epoch is always 1 in the graph. 
![image](https://user-images.githubusercontent.com/2324213/227848100-2f051f73-3443-4f73-8ba0-efa3baebd05c.png)

### Environment

- YOLO: Ultralytics YOLOv8.0.58  Python-3.9.10 torch-2.0.0+cu118 CUDA:0 (NVIDIA RTX A4000, 16376MiB)
- OS: Windows-10-10.0.19044-SP0
- Python: 3.9.10

### Minimal Reproducible Example

```
from ultralytics import YOLO
if __name__ == '__main__':
    model = YOLO('yolov8n.yaml')
    model. Train(data=r"data.yaml", epochs=1000, batch=64,
                patience=200, project='yolov8_new', workers=0)
    # model.val()
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
<img width="1377" alt="Screenshot 2023-03-27 at 2 01 17 PM" src="https://user-images.githubusercontent.com/15766192/227886486-decbe697-27ac-4b93-872d-138e39564696.png">
I see the metrics.

**Comment by darouwan** [comment]
> <img alt="Screenshot 2023-03-27 at 2 01 17 PM" width="1377" src="https://user-images.githubusercontent.com/15766192/227886486-decbe697-27ac-4b93-872d-138e39564696.png">
> 
> I see the metrics.

That's the strange thing. When I run the same code with the same dataset with same version at home, everything is fine. But when I ran it in the office, some metrics info was absent. So, does it relate to the network?

**Comment by darouwan** [comment]
> <img alt="Screenshot 2023-03-27 at 2 01 17 PM" width="1377" src="https://user-images.githubusercontent.com/15766192/227886486-decbe697-27ac-4b93-872d-138e39564696.png">
> 
> I see the metrics.

That's the strange thing. When I run the same code with the same dataset with same version at home, everything is fine. But when I ran it in the office, some metrics info was absent. So, does it relates to the network?

**Comment by TTK95** [comment]
Hey there, I had a similar issue this weekend! Do you have tensorboard installed? 
After installing tensorboard alle the metrics are shown. 
I only had the CSV logger per default, but in the docs it says tensorboard logger is the default, so I checked for my tensorboard package and it was missing.
Good luck!

**Comment by feicccccccc** [comment]
> Hey there, I had a similar issue this weekend! Do you have tensorboard installed? After installing tensorboard all the metrics are shown. I only had the CSV logger per default, but in the docs it says tensorboard logger is the default, so I checked for my tensorboard package and it was missing. Good luck!

This works for me.

**Comment by glenn-jocher** [comment]
@feicccccccc glad to hear that installing Tensorboard worked for you! The Tensorboard logger is the default logger for YOLOv8, and it's responsible for showing the metrics during training. So, if Tensorboard was missing, the metrics couldn't be displayed, even though the CSV logger was working as expected. Installing Tensorboard is an easy fix for this problem. Good luck with your YOLOv8 training!

**Comment by darouwan** [comment]
wonderful！ I will try it later

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by glenn-jocher** [comment]
@darouwan sure, I'm happy to help! If you run into any other issues or have questions about YOLOv8 in the future, feel free to reach out. Don't forget to check out the YOLOv8 documentation, which contains plenty of helpful information and examples. Good luck with your project and happy training!

**Comment by darouwan** [comment]
@glenn-jocher  So is it possible to install the tensorboard by default in requirements and docker files? After all this function is so easy to forget and some people may miss it.  I am happy to create a PR for that.

**Comment by TTK95** [comment]
@darouwan you should maybe create the PR in ClearML, because they need to fix that, too.

**Comment by glenn-jocher** [comment]
@TTK95 That's a great idea! Including Tensorboard in the default requirements and docker files would make it much easier for users to get started with YOLOv8 and ensure that they have access to all the necessary features during training. Creating a PR with this update would be a valuable contribution to the project. However, it's always a good idea to check with the Ultralytics team first to ensure they agree with the change before submitting the PR. Thanks for your willingness to help!
