### ISSUE TITLE
'coco2017labels-pose.zip' does not exist or is a bad zip file

### ISSUE THREAD

**Issue by derronqi** [ultralytics/ultralytics#1648]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

![image](https://user-images.githubusercontent.com/34156011/227866939-539e0c1e-a9a3-4c18-b740-db115bf1e0f6.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Pose models haven't been released yet. All of this will work at launch very soon

**Comment by derronqi** [comment]
thanks!

**Comment by pderrenger** [comment]
@derronqi you're welcome! If you have any more questions or need further assistance, feel free to ask!

**Comment by glenn-jocher** [comment]
@pderrenger you're welcome! Don't hesitate to reach out if you need more help. Happy coding! 😊
