### ISSUE TITLE
predict classes

### ISSUE THREAD

**Issue by 1623021453** [ultralytics/ultralytics#16511]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can a multi class segmentation model trained by oneself detect only one class with parameter settings？

**Comment by UltralyticsAssistant** [comment]
👋 Hello @1623021453, thank you for your interest in Ultralytics 🚀!

For your ❓ question on custom multi-class segmentation, we suggest you explore our [Docs](https://docs.ultralytics.com) which include examples on handling class-specific detections in segmentation models.

If this involves a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to assist us in debugging.

For further queries, please provide additional information like dataset examples or logs if applicable. Also, ensure you are abiding by our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

Join the Ultralytics community in real time on [Discord](https://ultralytics.com/discord) 🎧, engage in detailed discussions on [Discourse](https://community.ultralytics.com), or find insights on our [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade

Ensure you're using the latest `ultralytics` package by upgrading, which may resolve your issue:

```bash
pip install -U ultralytics
```

## Environments

Try using YOLOv8 across verified environments:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

Rest assured, an Ultralytics engineer will assist you soon. If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing, ensuring reliable performance across all tasks and modes.

**Comment by Y-T-G** [comment]
You can use the `classes` argument to detect only specific classes.

https://docs.ultralytics.com/modes/predict/#inference-arguments

**Comment by 1623021453** [comment]
Thank you.

**Comment by 1623021453** [comment]
> 👋 Hello @1623021453, thank you for your interest in Ultralytics 🚀!
> 
> For your ❓ question on custom multi-class segmentation, we suggest you explore our [Docs](https://docs.ultralytics.com) which include examples on handling class-specific detections in segmentation models.
> 
> If this involves a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to assist us in debugging.
> 
> For further queries, please provide additional information like dataset examples or logs if applicable. Also, ensure you are abiding by our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).
> 
> Join the Ultralytics community in real time on [Discord](https://ultralytics.com/discord) 🎧, engage in detailed discussions on [Discourse](https://community.ultralytics.com), or find insights on our [Subreddit](https://reddit.com/r/ultralytics).
> 
> ## Upgrade
> Ensure you're using the latest `ultralytics` package by upgrading, which may resolve your issue:
> 
> ```shell
> pip install -U ultralytics
> ```
> 
> ## Environments
> Try using YOLOv8 across verified environments:
> 
> * **Notebooks** with free GPU: [![Run on Gradient](https://camo.githubusercontent.com/6df71b7d7e0b09a2e97776f416bcd40acf48fc87337f8bcce48e4235537daf1f/68747470733a2f2f6173736574732e706170657273706163652e696f2f696d672f6772616469656e742d62616467652e737667)](https://console.paperspace.com/github/ultralytics/ultralytics) [![Open In Colab](https://camo.githubusercontent.com/96889048f8a9014fdeba2a891f97150c6aac6e723f5190236b10215a97ed41f3/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/c7135949c5c6882489e68f4af05a78a759460a4db256b86df3097e04419b4d9e/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/ultralytics/yolov8)
> * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
> * **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) [![Docker Pulls](https://camo.githubusercontent.com/6dcbe0a245fadcfd5202d971a92467bd2fcab86efebb2228d73468152c680573/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f756c7472616c79746963733f6c6f676f3d646f636b6572)](https://hub.docker.com/r/ultralytics/ultralytics)
> 
> ## Status
> [![Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg)](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule)
> 
> Rest assured, an Ultralytics engineer will assist you soon. If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing, ensuring reliable performance across all tasks and modes.

**Comment by 1623021453** [comment]
Thank you.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions, feel free to ask.
