### ISSUE TITLE
CUDA out of memory issue

### ISSUE THREAD

**Issue by agupta582** [ultralytics/ultralytics#1654]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I landed up into the following Runtime Error several times whenever I pick any model from Ultralytics package. The error snippet, given below, I got for yolov5n.pt model. Interestingly, when I train the same model directly from Yolov5 github repository [https://github.com/ultralytics/yolov5], it works perfectly without any error. Even I was able to train the large model Yolov5l.pt also with no errors. So, essentially, it seems an issue with the memory management in Ultralytics package. Please look into it.

_RuntimeError: CUDA out of memory. Tried to allocate 572.00 MiB (GPU 0; 23.99 GiB total capacity; 21.62 GiB already allocated; 0 bytes free; 22.67 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF_

### Environment

-- Ultralytics YOLOv8.0.57  Python-3.9.12 torch-1.12.0 CUDA:0 (NVIDIA RTX A5000, 24564MiB)
-- OS Ubuntu 22.04

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ExtReMLapin** [comment]
While yolov5 seems to had a very stable memory usage, it seems that yolov8 doesn't have this benefit.

Even when runing ray optimization, I decided to go low enough on the batch size to only use 20Gb of vram out of my 40 available, yet it still managed to crash (OOM) when I let it ran for few hours.

**Comment by glenn-jocher** [comment]
@ExtReMLapin hello! We're sorry to hear that you're encountering memory-related issues while running YOLOv8 👎. If you encounter a CUDA Out Of Memory (OOM) Error, it is typically the result of a lack of available memory to perform a specific task. To help avoid this, we recommend lowering your batch size and/or reducing your training image size. If this does not work and you have a larger GPU, you could try increasing your GPU's memory to run your models.

Another option that you might want to consider is tuning the `max_split_size_mb` parameter to adjust the amount of reserved memory relative to allocated memory to avoid memory fragmentation. You can find information on how to do this on the official PyTorch website.

We hope that helps! Let us know if you have any additional questions or run into any other issues.

**Comment by DFoxinator** [comment]
I ran into this issue and it was because I tried out auto batch size selection (batch=-1). Too high of a batch size was chosen which caused out of memory issues. Setting the batch size lower fixed it.

**Comment by ExtReMLapin** [comment]
Sorry for the delayed answer, I guess the issue is the memory usage is unstable, hear me out, with yolov5 the memory usage was very stage, while internally, there are allocations that are invisible in nvidia-smi because pytorch has reserved memory, with yolov8 it seems that for some reasons, deep in the training it needs to reserve more memory.

Starting a training on 35gb used out of 40gb sounds safe, but crashing two hours later is frustrating.

please take a look at the following error : 


```
      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
   128/3500      34.4G       1.64     0.3032     0.5341        219       2048: 100%|██████████| 82/82 [00:53<00:00,  1.53it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 36/36 [00:09<00:00,  3.66it/s]
                   all        491      14399     0.0357       0.26     0.0251    0.00567

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
   129/3500      34.2G      1.697     0.2921     0.5755        134       2048:  80%|████████  | 66/82 [00:42<00:10,  1.55it/s]Traceback (most recent call last):
  File "/home/CENSORED/.config/Ultralytics/DDP/_temp_ajvj9jgl139928182858336.py", line 9, in <module>
    trainer.train()
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 332, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 44, in forward
    return self.loss(x, *args, **kwargs)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 434, in loss
    preds = self.predict(img, batch=targets) if preds is None else preds
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 478, in predict
    x = head([y[j] for j in head.f], batch)  # head inference
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/nn/modules/head.py", line 242, in forward
    dec_bboxes, dec_scores = self.decoder(embed,
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/nn/modules/transformer.py", line 359, in forward
    output = layer(output, refer_bbox, feats, shapes, padding_mask, attn_mask, pos_mlp(refer_bbox))
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/nn/modules/transformer.py", line 319, in forward
    tgt = self.cross_attn(self.with_pos_embed(embed, query_pos), refer_bbox.unsqueeze(2), feats, shapes,
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/nn/modules/transformer.py", line 268, in forward
    output = multi_scale_deformable_attn_pytorch(value, value_shapes, sampling_locations, attention_weights)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/nn/modules/utils.py", line 59, in multi_scale_deformable_attn_pytorch
    value_l_ = (value_list[level].flatten(2).transpose(1, 2).reshape(bs * num_heads, embed_dims, H_, W_))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 224.00 MiB (GPU 2; 40.00 GiB total capacity; 35.54 GiB already allocated; 211.38 MiB free; 35.62 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Each epoch + evaluation takes about one minute, and at epoch 120, the training ran for two hours straight.
The issue I have is the usage was at 35gb out of 40, which should be enough for small unpredicted allocations.
(3 A40 @ 40gb running the training)

There was nothing else running on the server.

Here are some metrics from wandb

![image](https://github.com/ultralytics/ultralytics/assets/3909752/eea5320b-74e9-4172-8184-550306dfe0ee)

At the very end there is peak, but I'm unsure what it is, or if it's caused by the crash itself.

**Comment by glenn-jocher** [comment]
@ExtReMLapin hi there,

Apologies for the delayed response. It appears that the memory usage of YOLOv8 is more unstable compared to YOLOv5. While YOLOv5 may have hidden memory allocations that are not visible in `nvidia-smi` due to PyTorch reserving memory, YOLOv8 seems to require additional memory reservations during deep training.

Starting the training with 35GB of VRAM out of 40GB may seem safe, but it eventually crashes after running for a couple of hours. The error message you shared indicates that there was a CUDA Out Of Memory (OOM) error at epoch 129 when allocating additional memory.

One potential solution is to reduce the batch size and/or image size during training to lower the memory requirements. Another option is to increase the available GPU memory if you have a larger GPU or consider adjusting the `max_split_size_mb` parameter to optimize memory allocation and avoid fragmentation.

From the Wandb metrics you shared, there is a peak at the very end, but it's unclear whether it caused the crash or is a result of the crash itself.

Please let us know if you have any further questions or if there's anything else we can assist you with.

**Comment by thurnbauermatthi** [comment]
I have a similar issue. I have access to two NVIDIA A5000 GPUs with 24GB each. I use the pretrained yolov8m model. I get an OOM for an image size of 640 and a batch size of 4(!!). I am using cached images on disk for the training, but the error message says:

`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 18.46 GiB (GPU 0; 23.69 GiB total capacity; 16.35 GiB already allocated; 4.53 GiB free; 18.77 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`

Why does PyTorch reserve 18GB? That does sound like it is too much.

**Comment by glenn-jocher** [comment]
@thurnbauermatthi hi there, 

The PyTorch CUDA out of memory error you're encountering generally indicates that your GPU does not have enough memory to store the computations needed for training your model. In your case, with the pretrained YOLOv8m model, image size of 640 and a batch size of 4 on NVIDIA A5000 GPUs, it seems like PyTorch is indeed trying to reserve more memory than what's available on your GPUs.

The memory reserved by PyTorch isn't just for the model parameters. It's also used to store intermediate variables for backpropagation, optimizer states, and more. Moreover, PyTorch tends to cache memory to avoid the cost of allocating and deallocating memory every time it’s needed.

The memory requirement can increase with the complexity of the model, the size of the input data, and the batch size. While batch size and input size are more direct factors because they affect how much data is loaded into memory at once, the model complexity indirectly affects the memory requirement through the computational graph used for backpropagation.

Here are a few solutions you could try:

1. **Reduce the batch size**: You've already mentioned your batch size is 4. You could try reducing it further, even though that could potentially affect your training dynamics.

2. **Gradual Freezing**: This involves freezing some layers of the model while training others, then alternating.

3. **Gradient Checkpointing**: This is a trade-off strategy where you decrease memory usage by saving some intermediate variables and re-computing them during backward passes.

4. **Adjusting max_split_size_mb**: PyTorch divides tensors into chunks to optimize memory usage, and this parameter tells PyTorch the maximum chunk size. You could try modifying it based on your requirements.

5. **Using PyTorch's memory utilities**: `torch.cuda.memory_summary()` could be particularly useful to understand how CUDA memory is being allocated and, possibly, is running out.

I hope this information will help you! Let us know if there's anything else we could do to assist you.

**Comment by dt140120** [comment]
@glenn-jocher 
same problem, with imgsz=640, batch=4, satellite images and trained by rtx 2080ti (12gb)

**Comment by glenn-jocher** [comment]
@dt140120 hello, 

Thanks for reaching out. It appears you're experiencing an Out of Memory (OOM) error when attempting to train with a batch size of 4 and image size of 640 using RTX 2080 Ti (12GB).

The GPU memory requirement for training a model is primarily affected by input data size and model complexity. In this case, your batch size, model, and input image size are likely demanding more GPU memory than the available 12GB during training.

To resolve this issue, you could try several approaches:

1. **Reduce the batch size**: While your current batch size is relatively small, reducing it further might help lessen the memory demand, though this could affect training dynamics.

2. **Decrease the image size**: Reducing the image size will lower the memory footprint per image. 

3. **Adjust `max_split_size_mb`**: This can help optimize memory allocation.

4. **Use gradient accumulation**: This allows you to virtually increase your batch size without increasing memory usage by accumulating gradients over multiple mini-batches and performing a model update afterwards.

Please note that these solutions come with trade-offs and can potentially impact the accuracy of the model. 

I hope this helps, and do let us know if you have further questions!

**Comment by Petros626** [comment]
for me the following things seem to work:
1. reduce the batch size
2. call `torch.cuda.empty_cache()` before training job, some frameworks do this automatically.
3. `os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"`

**Comment by glenn-jocher** [comment]
Thank you for sharing your insights! Reducing batch size and managing CUDA memory with `torch.cuda.empty_cache()` or `PYTORCH_CUDA_ALLOC_CONF` are indeed effective strategies to mitigate memory issues. These approaches can help users optimize their training processes.

**Comment by zjykzj** [comment]
> for me the following things seem to work:
> 
> 1. reduce the batch size
> 2. call `torch.cuda.empty_cache()` before training job, some frameworks do this automatically.
> 3. `os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"`

The same error occurred as this issue and it can be stably reproduced. I also found that yolov5 is less stable than ultralytics in terms of gpu memory usage during training. In my testing, `reducing batch size` was effective, while the remaining 2 and 3 did not have an effect.

```shell
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/300      16.1G      1.477     0.7796      1.028        120        800: 100%|██████████| 805/805 [01:39<00:00,  8.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 101/101 [00:13<00:00,  7.70it/s]
                   all       3225      39675       0.84      0.597      0.677      0.366

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/300      19.8G      1.468     0.7752      1.024        169        800: 100%|██████████| 805/805 [01:37<00:00,  8.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 101/101 [00:13<00:00,  7.69it/s]
                   all       3225      39675       0.85      0.595       0.68       0.37

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/300        18G      1.466     0.7727      1.024        103        800: 100%|██████████| 805/805 [01:35<00:00,  8.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 101/101 [00:13<00:00,  7.70it/s]
                   all       3225      39675       0.84        0.6      0.678      0.368

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/300      15.3G      1.462     0.7669      1.025        150        800: 100%|██████████| 805/805 [01:38<00:00,  8.21it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 101/101 [00:13<00:00,  7.58it/s]
                   all       3225      39675      0.842      0.594      0.677      0.366

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/300      14.3G      1.469     0.7728      1.024        222        800: 100%|██████████| 805/805 [01:39<00:00,  8.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 101/101 [00:13<00:00,  7.64it/s]
                   all       3225      39675      0.847      0.601      0.683       0.37

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/300      14.3G      1.459     0.7599      1.022        136        800: 100%|██████████| 805/805 [01:34<00:00,  8.51it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 101/101 [00:13<00:00,  7.60it/s]
                   all       3225      39675      0.851      0.603      0.686      0.374

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/300        17G      1.446     0.7567      1.023        212        800: 100%|██████████| 805/805 [01:38<00:00,  8.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 101/101 [00:13<00:00,  7.74it/s]
                   all       3225      39675       0.85      0.601      0.685      0.373

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/300      19.2G      1.452     0.7582       1.02        303        800:  68%|██████▊   | 549/805 [01:06<00:31,  8.22it/s]
Traceback (most recent call last):
  File "/root/anaconda3/envs/py38/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/ultralytics/cfg/__init__.py", line 831, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/ultralytics/engine/model.py", line 803, in train
    self.trainer.train()
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 385, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 107, in forward
    return self.loss(x, *args, **kwargs)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 289, in loss
    return self.criterion(preds, batch)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/ultralytics/utils/loss.py", line 232, in __call__
    _, target_bboxes, target_scores, fg_mask, _ = self.assigner(
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/ultralytics/utils/tal.py", line 72, in forward
    mask_pos, align_metric, overlaps = self.get_pos_mask(
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/ultralytics/utils/tal.py", line 92, in get_pos_mask
    mask_in_gts = self.select_candidates_in_gts(anc_points, gt_bboxes)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/ultralytics/utils/tal.py", line 230, in select_candidates_in_gts
    bbox_deltas = torch.cat((xy_centers[None] - lt, rb - xy_centers[None]), dim=2).view(bs, n_boxes, n_anchors, -1)
RuntimeError: CUDA out of memory. Tried to allocate 9.67 GiB (GPU 0; 23.70 GiB total capacity; 12.33 GiB already allocated; 9.27 GiB free; 12.71 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/root/anaconda3/envs/py38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/py38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/root/anaconda3/envs/py38/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 297, in rebuild_storage_fd
    fd = df.detach()
  File "/root/anaconda3/envs/py38/lib/python3.8/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/root/anaconda3/envs/py38/lib/python3.8/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/root/anaconda3/envs/py38/lib/python3.8/multiprocessing/connection.py", line 508, in Client
    answer_challenge(c, authkey)
  File "/root/anaconda3/envs/py38/lib/python3.8/multiprocessing/connection.py", line 752, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/root/anaconda3/envs/py38/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/root/anaconda3/envs/py38/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/root/anaconda3/envs/py38/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by glenn-jocher** [comment]
@zjykzj thank you for sharing your detailed observations and findings. It's clear that reducing the batch size remains the most effective solution for managing GPU memory issues in your scenario. The fluctuating memory usage in `ultralytics` compared to `yolov5` is noted and may be connected to differences in architecture or training implementation. We recommend monitoring GPU memory usage with tools like `nvidia-smi` during training and submitting a reproducible example to the [GitHub Issues](https://github.com/ultralytics/ultralytics/issues) if you believe this warrants further investigation. Let us know if you have additional insights or questions.
