### ISSUE TITLE
model = YOLO("yolo11s.pt") and im sure i download the pt then put it in root dir, when i run the code why still auto download yolov8n.pt

### ISSUE THREAD

**Issue by dingnasty** [ultralytics/ultralytics#16557]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

model = YOLO("yolo11s.pt") and im sure i download the pt then put it in root dir, when i run the code why still auto download yolov8n.pt

**Comment by dingnasty** [comment]
i found that use yolov8n.pt just for checking AMP. Did I understand it right?

**Comment by glenn-jocher** [comment]
@dingnasty during training yes that is correct. We will update this to YOLO11n but everything is fine and your training should not have any problems.

**Comment by glenn-jocher** [comment]
Opened https://github.com/ultralytics/ultralytics/pull/16560 to update this

**Comment by 258692011** [comment]
测试版，早期yolo10，也是需要yolov8环境

**Comment by glenn-jocher** [comment]
Thank you for your comment. Yes, YOLOv10 requires the YOLOv8 environment for compatibility. If you have further questions, feel free to ask!

**Comment by superhankqiao** [comment]
Now, I use yolo11l.pt, but at first it also shows Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt'..

Is this normal?

Thanks!

**Comment by glenn-jocher** [comment]
@superhankqiao yes, this is normal. The `yolo11n.pt` file is downloaded temporarily during training to check AMP (Automatic Mixed Precision) compatibility, which ensures your setup is optimized for performance. It does not affect your use of `yolo11l.pt`. Let me know if you have further questions!

**Comment by superhankqiao** [comment]
This is very useful to me. Thank you so much!

**Comment by glenn-jocher** [comment]
@superhankqiao you're very welcome! The credit goes to the Ultralytics team and the amazing YOLO community for making this possible. If you have further questions, feel free to ask!

**Comment by ahiyantra** [comment]
> [@superhankqiao](https://github.com/superhankqiao) yes, this is normal. The `yolo11n.pt` file is downloaded temporarily during training to check AMP (Automatic Mixed Precision) compatibility, which ensures your setup is optimized for performance. It does not affect your use of `yolo11l.pt`. Let me know if you have further questions!

I was wondering about why the yolo11n file was getting downloaded automatically during the model training step despite my jupyter code not having anything to do it. This explains things.

**Comment by glenn-jocher** [comment]
@ahiyantra thank you for confirming! This AMP check helps ensure your hardware configuration is optimized for training stability and performance. The Ultralytics team and YOLO community appreciate your engagement - feel free to reach out with any other questions! 🚀
