### ISSUE TITLE
Yolo10 - weights_only

### ISSUE THREAD

**Issue by applesun8799** [ultralytics/ultralytics#16569]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

FutureWarning: You are using `torch.load` with **`weights_only=False`** (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(file, map_location="cpu")

**Comment by applesun8799** [comment]
<img width="1033" alt="微信图片_20240930221129" src="https://github.com/user-attachments/assets/9013902c-f199-457e-8b01-0671ab2c52b6">

**Comment by Y-T-G** [comment]
Can you provide the output after running this command in terminal: `yolo checks`?

**Comment by applesun8799** [comment]
After uninstalling this package（albumentations）, it runs normally

**Comment by glenn-jocher** [comment]
It seems like the issue was related to the albumentations package. If you need further assistance, feel free to ask!
