### ISSUE TITLE
YOLO CLI object detection doesn't match Python example

### ISSUE THREAD

**Issue by MattAlanWright** [ultralytics/ultralytics#1656]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am finding that the output of either the YOLO CLI or YOLO Python class, when performing prediction/object detection, doesn't match the output when performing the same via the sample Python script that loads the ONNX model into OpenCV's DNN module and performs inference that way (https://github.com/ultralytics/ultralytics/blob/main/examples/YOLOv8-OpenCV-ONNX-Python/main.py). The discrepancies seem small on the sample "bus.jpg", but are significant on the images I'm working with (I'm unable to share these, unfortunately). 

Is there a step or part of the process that I am missing? I would like to use a YOLOv8 model in a custom program that is already using OpenCV and this is the preferred way of ingesting and using the model. The differences are small here but significant in images that I am working with, so much so that the custom script misses some boxes entirely.

### Procedure

First, I generate an ONNX version of YOLOv8n using exactly the steps from the README here: https://github.com/ultralytics/ultralytics/blob/main/examples/YOLOv8-OpenCV-ONNX-Python/README.md and then run the example script here: https://github.com/ultralytics/ultralytics/blob/main/examples/YOLOv8-OpenCV-ONNX-Python/main.py, with the change that NMSBoxes' IoU threshold is set to 0.7:

```
...
result_boxes = cv2.dnn.NMSBoxes(boxes, scores, 0.25, 0.70, 0.5)
...
```

From the Python script I get:

![opencv_bus](https://user-images.githubusercontent.com/46428602/228016706-0a6295d2-6fe7-4f6c-ac7d-1a75f5b776e1.jpg)

To compare with the CLI, I am running the following:

```
yolo detect predict model=.\yolov8n.onnx source=.\bus.jpg imgsz=640 conf=0.25 iou=0.7 device=cpu save=True save_txt=True save_conf=True
```

From the CLI I get

![cli_bus](https://user-images.githubusercontent.com/46428602/228016780-5da8d42b-f152-4c26-8da5-9e9820812835.jpg)

This is on a Windows 10 machine with Python 3.7.3. I am attaching the resulting images from both. You can see the confidence scores are different.

**Comment by glenn-jocher** [comment]
@MattAlanWright you might want to make sure that the dnn inference example is using all the same settings as in default.yaml and that you are passing the image in the correct RGB/BGR order.

**Comment by MattAlanWright** [comment]
I have reviewed all the entires in default.yaml and I believe my DNN example matches all of those values (except in cases where I pass something different to the CLI, in which case my DNN example mimics the value passed to the CLI). I experimented with converting the color channels from BGR to RGB but the results are even further off:

![opencv_bus_bgr2rgb](https://user-images.githubusercontent.com/46428602/228235144-52c57d71-554e-4832-9d5c-fd9c82e138a2.jpg)

This example is taken directly from the Ultralytics repo.

**Comment by glenn-jocher** [comment]
@MattAlanWright ah ok got it. Then there may be some issues in DNN. Note that DNN is different that ONNX Runtime, you can **run any exported YOLOv8 model directly with the ultralytics package**, you don't need DNN, i.e.

```
from ultralytics import YOLO

model = ('yolov8n.onnx')  # load an ONNX model
results = model(img)  # run inference
```

**Comment by glenn-jocher** [comment]
@MattAlanWright also note that we benchmark all exported formats for speed and accuracy, and ONNX does not lose any accuracy:

https://github.com/ultralytics/ultralytics/actions/runs/4537845907/jobs/7996127140

<img width="1207" alt="Screenshot 2023-03-28 at 17 29 01" src="https://user-images.githubusercontent.com/26833433/228289069-7a99c9d2-2cab-4276-ad8b-573254cc4fd3.png">


See https://docs.ultralytics.com/modes/benchmark

**Comment by stephenllh** [comment]
> Thanks @glenn-jocher. I found that If I replace these pre-processing steps:
> 
> ```
> [height, width, _] = original_image.shape
> length = max((height, width))
> scale = length / 640
> image = np.zeros((length, length, 3), np.uint8)
> image[0:height, 0:width] = original_image
> 
> blob = cv2.dnn.blobFromImage(image, scalefactor=1 / 255, size=(640, 640))
> model.setInput(blob)
> outputs = model.forward()
> ```
> 
> with this, taken from bits and pieces of the Ultralytics prediction code:
> 
> ```
> image = LetterBox([640,640], auto=False, stride=32)(image=original_image)
> image = image.transpose((2, 0, 1))[::-1]  # HWC to CHW, BGR to RGB
> image = np.ascontiguousarray(image)  # contiguous
> 
> image = torch.from_numpy(image).to("cpu")
> image = image.float()  # uint8 to fp16/32
> image /= 255  # 0 - 255 to 0.0 - 1.0
> image = image[None]
> 
> image = image.cpu().numpy()  # torch to numpy
> model.setInput(image)
> outputs = model.forward()
> ```
> 
> I get the expected output, so it must have been a pre-processing step. I'm not sure which particular step was missing.

This solves my problem of the ONNX Python example getting different results compared to using the CLI to call the ONNX model. Thanks a lot!

**Comment by glenn-jocher** [comment]
Great to hear you've resolved the discrepancy, @stephenllh! Pre-processing is indeed critical for consistent results. If you have any more questions or need further assistance, feel free to reach out. Happy coding! 🚀
