### ISSUE TITLE
About the Size parameter

### ISSUE THREAD

**Issue by boysj** [ultralytics/ultralytics#16579]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have always had a problem with the size parameter and I don’t understand it.

1.The document points out that the Size parameter 320 is not as accurate as 640 in identifying small targets. What is the specific size of this small target with or without image examples?

2.Does Size have to be in square format? If I use 640*320 for training, will there be any problems in recognizing 1920*1080 images?

3.Does the training size parameter need to be proportional to the size of the recognized image? Is it possible to train with a size of 640*320, and is it feasible to recognize an input parameter image of 700*600?

For questions 2 and 3, I have also conducted similar training and recognition, but the recognition was not successful. I don't know if I'm doing something wrong.I remember that 640*320 was used for training, and the image size was not fixed during inference.

**Comment by UltralyticsAssistant** [comment]
👋 Hello @boysj, thank you for your interest in Ultralytics 🚀! We recommend a visit to the [Docs](https://docs.ultralytics.com) for new users where you can find many [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples and where many of the most common questions may already be answered.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us debug it.

For your questions about the size parameter, understanding model resizing and its effects can be complex. If you've tried some setups that didn't succeed, providing specific details about your model configuration and results can help. An Ultralytics engineer will assist you shortly to address your specific questions.

Join the Ultralytics community where it suits you best:
- For real-time chat, head to [Discord](https://ultralytics.com/discord) 🎧.
- Prefer in-depth discussions? Check out [Discourse](https://community.ultralytics.com).
- Dive into threads on our [Subreddit](https://reddit.com/r/ultralytics) to share knowledge with the community.

## Upgrade

Upgrade to the latest `ultralytics` package, including all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml), in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

## Environments

YOLOv8 can be run in up-to-date environments:

- **Notebooks** with free GPU:
  - <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> 
  - <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> 
  - <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) 
  - <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all automated tests are passing. CI tests verify the correct operation on macOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by Y-T-G** [comment]
1. Smaller `imgsz` would result in coarse features, which may cause issues with small objects. Small object is usually regarded as any object below 32x32.
2. For training, you can only specify square size. For export, some formats support non-square sizes.
3. 640x640 is sufficient for most use cases. Unless your object is really small, you don't have to worry about it.

**Comment by boysj** [comment]
I use 640 for training to recognize pictures in 1920*1080 or other formats. The height-to-width ratio is not 1:1. Will it cause a decrease in accuracy?
