### ISSUE TITLE
Is there any benchmark available for the performances of YOLO models on edge devices (can be both android and iOS)?

### ISSUE THREAD

**Issue by Haseeeb21** [ultralytics/ultralytics#16591]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am searching for a benchmark with edge devices (android & iOS) and their performances on different models versions and formats (tflite, onnx, etc..) so that I can know which model and which format of that model works / gives the best results and performance.
One benchmark is as below but it just contains information of YOLOv4
https://ai-benchmark.com/ranking_detailed.html

**Comment by UltralyticsAssistant** [comment]
@Haseeeb21 you can benchmark on your own iOS devices with https://github.com/ultralytics/yolo-ios-app and for Android with https://github.com/ultralytics/yolo-flutter-app

**Comment by Haseeeb21** [comment]
@UltralyticsAssistant 
![image](https://github.com/user-attachments/assets/dff698ce-aa9b-4609-8f36-adabd3eb7b2f)

so YOLO models cannot be used for segmentation on edge devices?

**Comment by Haseeeb21** [comment]
what if we have onnx format models and using android studio can we make segmentation app?

**Comment by glenn-jocher** [comment]
Yes, you can use ONNX format models in Android Studio to create a segmentation app. You'll need to integrate an ONNX runtime compatible with Android to run the model.

**Comment by Haseeeb21** [comment]
Is there any application uploaded in ultralytics related to segmentation and detection?

**Comment by glenn-jocher** [comment]
Ultralytics provides models for segmentation and detection, but specific applications are not uploaded. You can use the models with the provided documentation to create your own applications.
