### ISSUE TITLE
[8.0.58] Autobatch being too conservative?

### ISSUE THREAD

**Issue by Denizzje** [ultralytics/ultralytics#1659]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi there,

With my quite large dataset (40k training images) and the YoloV8 L-seg model, I noticed that the autobatch seems to be quite conservative right now and just takes 66% of the GPU memory.

```
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
AutoBatch: Computing optimal batch size for imgsz=640
AutoBatch: CUDA:0 (NVIDIA A100-SXM4-80GB) 79.21G total, 0.37G reserved, 0.36G allocated, 78.48G free
      Params      GFLOPs  GPU_mem (GB)  forward (ms) backward (ms)                   input                  output
    45954552       220.9         1.726         28.87           nan        (1, 3, 640, 640)                    list
    45954552       441.8         2.991         27.27           nan        (2, 3, 640, 640)                    list
    45954552       883.6         5.352         27.89           nan        (4, 3, 640, 640)                    list
    45954552        1767        10.127         30.79           nan        (8, 3, 640, 640)                    list
    45954552        3534        19.623         50.07           nan       (16, 3, 640, 640)                    list
AutoBatch: Using batch-size 43 for CUDA:0 52.52G/79.21G (66%) ✅
```

It was a fresh start of the system and nothing else was running.  I would expect the autobatch to aim for something like 80% RAM usage. I know the autobatch has to be a bit conversative so smaller VRAM GPUs dont get knocked out by it during training. I am wondering if this is too conservative however, perhaps a bug, or actually intended.

Env:
PyTorch 2.0 (CUDA 11.7) from pip, YOLOv8 8.0.58 (freshly pulled before starting), Nvidia drivers 515.65.01, Ubuntu 20.04, Python 3.10.10.

### Additional

Checking nvitop the GPU usage is actually fairly decent:

![image](https://user-images.githubusercontent.com/25279882/228036171-28edf9b1-5b3f-4d66-bea3-6ec2a212d12c.png)

Though I am used from YoloV5 to the utilisation fairly constantly at 100% as well as the memory at 80-90%. So I feel there is some gains to be had here.

**Comment by glenn-jocher** [comment]
@Denizzje for YOLOv5 we've set this to 80%, for YOLOv8 since it's newer and less tested we initially set to 70%, and got a couple user errors at this level on smaller graphics cards, so we reduced to 67% based on their feedback. 

Note this usage will increase as EMA is created and val is run, so AutoBatch requires some buffer to account for these two events that is hard to estimate. The main issue is estimating CUDA usage on very small GPUs is difficult/unreliable, while larger cards like A100's are more reliable.

Maybe we could convert AutoBatch argument handling to accept floats and then use that as the target CUDA usage, i.e. 
```
yolo train batch=0.8  # AutoBatch target of 80% usage
```

**Comment by glenn-jocher** [comment]
@SaraDadjouy Yes, using a batch size of -1 with YOLOv8's AutoBatch feature can be a good practice when using Ray Tune for hyperparameter tuning. With a batch size of -1, AutoBatch will automatically compute the optimal batch size to use based on the available GPU memory. This can help prevent out-of-memory errors during training and can also help improve training performance by maximizing GPU usage. 

To use AutoBatch with Ray Tune, you can define a search space for the batch size as an integer range or a list of specific values, and then pass this search space to a Ray Tune trainable function. Within the trainable function, you can then set the batch size to -1 and let AutoBatch compute the optimal batch size for each trial.
