### ISSUE TITLE
post_process

### ISSUE THREAD

**Issue by ilhansevval** [ultralytics/ultralytics#1660]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there any way to implement post processing without using api in yolov8 ?

**Comment by glenn-jocher** [comment]
@ilhansevval I don't understand your question, can you explain what you're looking for in more detail?

**Comment by ilhansevval** [comment]
Such as, select boxes above a classification threshold,  clip boxes to the image shape, apply the Non-Maximum-Selection algorithm, resize bounding boxes to original image shape.

**Comment by pderrenger** [comment]
@ilhansevval got it! Yes, you can implement post-processing in YOLOv8 without using an API by directly manipulating the bounding box coordinates and implementing algorithms like Non-Maximum-Suppression (NMS) and thresholding in your own code. After obtaining the bounding box predictions from the model, you can select boxes above a classification threshold, clip boxes to the image shape, apply NMS, and resize bounding boxes to the original image shape using custom post-processing logic in your application. This allows for flexibility and customization according to your specific requirements.

**Comment by glenn-jocher** [comment]
Absolutely, @pderrenger! YOLOv8 outputs raw predictions that you can post-process manually. You can filter out detections below your desired confidence threshold, clip bounding boxes to the image boundaries, apply Non-Maximum Suppression to remove overlapping boxes, and scale them back to the original image size. All these steps can be implemented in your code following the model's predictions to tailor the output to your needs. Happy coding! 🚀
