### ISSUE TITLE
Yolov8 Multi-Object Tracking id  keeps incrementing

### ISSUE THREAD

**Issue by sunyw000** [ultralytics/ultralytics#1663]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I use the model.track() function to read and process images from the video frame by frame, the returned ID keeps incrementing. May I ask what could be the cause of this?

There is code:

def draw_rotated_bounding_box(mask):

    binary_mask = mask.cpu().numpy().astype(np.uint8)

    contours, _ = cv2.findContours(binary_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    contour = max(contours, key=cv2.contourArea)
    rotated_rect = cv2.minAreaRect(contour)
    box_points = cv2.boxPoints(rotated_rect)
    box_points = np.int0(box_points)
    return box_points

model = YOLO("best.pt")

def process_frame(frame):

    frame = cv2.resize(frame, dsize=(1280, 800), interpolation=cv2.INTER_AREA)
    results = model.track(source=frame,tracker='bytetrack.yaml')
    model.predictor.run_callbacks('on_predict_postprocess_end')
    model.predictor.run_callbacks('on_predict_end')
    label_to_name = {0: "car", 1: "truck", 2: "bus"}
    name_to_color = {
        "car": (0, 255, 0),  
        "truck": (255, 0, 0),  
        "bus": (0, 0, 255)  
    }
    masks = results[0].masks
    boxes = results[0].boxes.cls
    confs = results[0].boxes.conf
    ids=results[0].boxes.id
    for box, mask, conf, id in zip(boxes, masks, confs,ids):
        label = int(box)
        id=int(id)
        name = label_to_name[label]
        color = name_to_color[name]
        rotated_box_points = draw_rotated_bounding_box(mask.data)
        cv2.drawContours(frame, [rotated_box_points], 0, color, 2)
        text_position = (int(rotated_box_points[0][0]), int(rotated_box_points[0][1] - 10))
        conf_text = f"{name} {conf:.1f} {id}"
        cv2.putText(frame, conf_text, text_position, cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 1, cv2.LINE_AA)
    return frame

video_file = "../2.avi"

cap = cv2.VideoCapture(video_file)

if not cap.isOpened():

    print("Error: Could not open the video file.")
    exit()

fps = int(cap.get(cv2.CAP_PROP_FPS))
width = 1280
height = 800
fourcc = cv2.VideoWriter_fourcc(*"mp4v") 
output_video = cv2.VideoWriter("./output_video.mp4", fourcc, fps, (width, height))
while True:

    ret, frame = cap.read()
    if not ret:
        break
    processed_frame = process_frame(frame)
    # output_video.write(processed_frame)
    cv2.imshow("Processed Frame", processed_frame)
    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

cap.release()

cv2.destroyAllWindows()

**Comment by AyushExel** [comment]
Object tracking is not a 100% accurate solution. It really depends on the video, camera angle etc. 
If there are a lot of changing angles, occlusions, and movements, the tracker might assign a new ID to the same object. That's why in most tracking applications, the scene( or the camera angle) is fixed. 
We'll work on models with better re-id capabilities soon but the difference should not be night and day
