### ISSUE TITLE
Weird PermissionDenied behaivor (dataset) even after reboot

### ISSUE THREAD

**Issue by schelmi1** [ultralytics/ultralytics#1665]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Hi, i have a dataset 'data/' which i use to train models on.
Recently i trained a model and aborted the training process before reaching the desired amount of epochs.
(i killed the training process with ctrl+c and closing the terminal)

I can resume training of this model on this dataset without any problems.
However if i want to train a new model using this dataset i get a Permission Denied error **(even after rebooting the machine)**

![err](https://user-images.githubusercontent.com/90637575/228111775-2d0252b7-c15f-4381-82a2-e46f08a33bc3.png)

when using a different dataset 'data2', i also get this error
as for now the only thing that works is resume training

### Environment

Ultralytics YOLOv8.0.58  torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce GTX 1070, 8192MiB)
OS: Windows 10
Python: 3.10.0
venv: conda

### Minimal Reproducible Example

yolo task=detect mode=train model=yolov8n.pt epochs=20 imgsz=640 batch=48 data=data/ name=yolov8n_opt

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by schelmi1** [comment]
as you can see in the screenshot, i am already doing this

**Comment by SubhiH** [comment]
I am facing same issue. After few epochs (between 2 to 8), I get **Access denied** error. I tried in Admin mode still same. I have another machine with exact setup and it is working fine there.

@schelmi1 , could you please explain more on the work around you found?

<img width="943" alt="Screenshot 2023-04-06 at 10 03 47 PM" src="https://user-images.githubusercontent.com/2580270/230525798-9b3f62be-bd7e-4bdf-a46f-3eac2724ce01.png">

**Comment by glenn-jocher** [comment]
@hasmukh-jevani, it seems that the issue you are facing might be related to file/folder permissions. Sometimes, even when running in admin mode, Windows can restrict access to certain folders, causing the `access denied` error. 

@schelmi1 advised that specifying the folder path in the `data` argument might not be necessary and could cause issues. Additionally, try running the command from a different directory or check if there are any other processes that could be restricting access to the files/folders.

**Comment by SubhiH** [comment]
@glenn-jocher Thanks for the comment!
How can I point the model to the data set without using the data argument?

**Comment by schelmi1** [comment]
> 
> 
> @schelmi1 , could you please explain more on the work around you found?
> 

it looks like your issues is different.
my issues was getting a PermissionDenied error due to not specifying the data.yaml but just the data folder in the **data argument** (data=data/ instead of data=data/data.yaml)
this only happens with train, but not train resume

**Comment by glenn-jocher** [comment]
@schelmi1 @SubhiH another possibility is that your system is simply out of resources. If this error doesn't occur with smaller datasets and/or models then this is a likely cause.
