### ISSUE TITLE
Heatmap for classification

### ISSUE THREAD

**Issue by davy-blavette** [ultralytics/ultralytics#16687]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

During classification training I see that Yolov8 generates images with what looks like a heatmap, I'd like to be able to generate these images, but I can't see how to do it, or how to get this data to colorise my image with cv2 or matplolib, could you help me? 

![image](https://github.com/user-attachments/assets/a0a931fb-6b7f-4378-9788-763f817feb6f)

**Comment by Y-T-G** [comment]
It's not a heatmap. It's an augmentation applied during training.

**Comment by davy-blavette** [comment]
@Y-T-G OK, thanks, that's interesting, but what does it tell us about? If Yolo generates it, I'd like to be able to do it on all these images (once I've understood what it's for)... :)

**Comment by Y-T-G** [comment]
`ultralytics` shows samples from training batches in the plots. The augmentations are used to improve accuracy of the model and make the model learn on variations of the image.

If you want to get feature visualizations, you can pass `visulaize=True` to `model.predict()`

https://docs.ultralytics.com/modes/predict/#inference-arguments

**Comment by davy-blavette** [comment]
thanks I find https://github.com/z1069614715/objectdetection_script/blob/master/yolo-gradcam/yolov8_heatmap.py 
![image](https://github.com/user-attachments/assets/891da9d5-89cd-42fe-9a64-06207abfee30)

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions about using YOLO with heatmaps, feel free to ask.
