### ISSUE TITLE
Training yolov8-seg and yolo11-seg failed

### ISSUE THREAD

**Issue by PandaGab** [ultralytics/ultralytics#16693]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Everything was working until I upgraded the library. Now training yolov8-seg (and yolo11-seg) now leads to this error.

```shell
  File "/.venv/lib/python3.11/site-packages/ultralytics/data/augment.py", line 2126, in _format_segments
    masks, sorted_idx = polygons2masks_overlap((h, w), segments, downsample_ratio=self.mask_ratio)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/ultralytics/data/utils.py", line 225, in polygons2masks_overlap
    mask = ms[i] * (i + 1)
           ~~~~~~^~~~~~~~~
OverflowError: Python integer 256 out of bounds for uint8
```

### Environment

Ultralytics 8.3.4 🚀 Python-3.11.7 torch-2.4.1+cu121 CUDA:0 (NVIDIA RTX A5000, 24240MiB)
Setup complete ✅ (20 CPUs, 62.5 GB RAM, 271.7/937.3 GB disk)

OS                  Linux-5.14.0-1055-oem-x86_64-with-glibc2.35
Environment         Linux
Python              3.11.7
Install             git
RAM                 62.53 GB
CPU                 Intel Core(TM) i9-10900X 3.70GHz
CUDA                12.1

numpy               ✅ 2.1.1>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.4.1>=1.8.0
torchvision         ✅ 0.19.1>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.8>=2.0.0
torch               ✅ 2.4.1!=2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

No code to reproduce

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @PandaGab, thank you for bringing this to our attention and for your interest in Ultralytics 🚀! 

Please make sure to provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) so we can better assist you with this 🐛 bug report. This will help in debugging the issue effectively.

We recommend checking out our [Docs](https://docs.ultralytics.com) for insights, especially if you're new to using the library. You'll find useful [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples there.

Stay connected with the Ultralytics community:
- Join real-time discussions on [Discord](https://ultralytics.com/discord) 🎧.
- Participate in in-depth discussions on [Discourse](https://community.ultralytics.com).
- Engage with others on our [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade

Ensure you're using the latest version of Ultralytics with all dependencies up-to-date in a [**Python>=3.8**](https://www.python.org/) environment:

```bash
pip install -U ultralytics
```

## Environments

YOLO can run in numerous verified environments. Consider trying one of these for a smooth experience with all dependencies pre-installed:

- **Notebooks**: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud**: [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon**: [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker**: [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

The CI badge status indicates if all tests are passing. This includes verification of YOLO across platforms like macOS, Windows, and Ubuntu.

Rest assured, an Ultralytics engineer will review your issue soon to provide further assistance. 😊

**Comment by PandaGab** [comment]
Should be fixed by https://github.com/ultralytics/ultralytics/pull/16690

**Comment by glenn-jocher** [comment]
@PandaGab thank you for pointing that out. Please check the latest updates from the pull request to see if it resolves your issue.
