### ISSUE TITLE
Issue quantizing YOLO11 model to int8

### ISSUE THREAD

**Issue by lucalazzaroni** [ultralytics/ultralytics#16737]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

Hello everyone, I'm having an issue when trying to convert my `best.pt` model to int8 tflite. It seems that this issue only happens with `int8`, because I tried using `half=True` and the fp16 exporting works fine.

Here is the output that I get when I run `model.export(format="tflite", int8=True, data='data.yaml')`:

```
Ultralytics 8.3.2 🚀 Python-3.8.19 torch-2.4.1+cu124 CPU (Intel Core(TM) i9-14900K)
YOLO11n summary (fused): 238 layers, 2,583,127 parameters, 0 gradients, 6.3 GFLOPs

PyTorch: starting from 'C:\Users\elios\Documents\tld\runs\yolo11\train4\weights\best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 9, 8400) (5.3 MB)
```

After this I get no error and the command stops without producing anything.

### Environment

```
Ultralytics 8.3.2 🚀 Python-3.8.19 torch-2.4.1+cu124 CUDA:0 (NVIDIA GeForce RTX 4080, 16376MiB)
Setup complete ✅ (32 CPUs, 29.7 GB RAM, 436.7/453.7 GB disk)

OS                  Windows-10-10.0.22631-SP0
Environment         Windows
Python              3.8.19
Install             pip
RAM                 29.66 GB
CPU                 Intel Core(TM) i9-14900K
CUDA                12.4

numpy               ✅ 1.24.1<2.0.0,>=1.23.0
matplotlib          ✅ 3.7.5>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.4.1+cu124>=1.8.0
torchvision         ✅ 0.19.1+cu124>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.8>=2.0.0
torch               ✅ 2.4.1+cu124!=2.4.0,>=1.8.0; sys_platform == "win32"
```

### Minimal Reproducible Example

```
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO("./best.pt")
    # Export the model to TFLite format
    model.export(format="tflite", int8=True, data='data.yaml')
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ambitious-octopus** [comment]
Ciao @lucalazzaroni, known problem (#15873), we are working to fix it. Be careful though because the full int8 quantization works correctly the problem is only related to the int8 quantization with int16 activations.

```python
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO("yolo11n.pt")
    model.export(format="tflite", int8=True, data='coco8.yaml')
    model = YOLO("yolo11n_saved_model/yolo11n_full_integer_quant.tflite")
    res = model.predict()
    res[0].show()
```

**Comment by lucalazzaroni** [comment]
@ambitious-octopus thank you for the quick reply. Actually, I am using the same exact code but I am not able to generate any int8 model. On my Windows machine the process stops without any error and it does not generate anything.

I also tried on an Ubuntu machine and here is the result:

```
Ultralytics 8.3.6 🚀 Python-3.8.19 torch-2.4.1+cu121 CPU (11th Gen Intel Core(TM) i7-11800H 2.30GHz)
YOLO11n summary (fused): 238 layers, 2,583,127 parameters, 0 gradients, 6.3 GFLOPs

PyTorch: starting from 'best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 9, 8400) (5.3 MB)

TensorFlow SavedModel: starting export with tensorflow 2.13.1...

ONNX: starting export with onnx 1.17.0 opset 19...
ONNX: slimming with onnxslim 0.1.34...
ONNX: export success ✅ 1.1s, saved as 'best.onnx' (10.2 MB)
TensorFlow SavedModel: collecting INT8 calibration images from 'data=BoschDriveU.yaml'
Scanning /home/luca/yolo/datasets/tld/valid/labels.cache... 4536 images, 356 backgrounds, 17 corrupt: 100%|█
WARNING ⚠️ /home/luca/yolo/datasets/tld/valid/images/DE_BBBR667_2015-05-15_16-27-51-677305_k0.png: ignoring corrupt image/label: negative label values [ -0.0068359]
Killed
```

**Comment by ambitious-octopus** [comment]
@lucalazzaroni I think it's a data issue, try using `coco8.yaml`. Also, can you give me your yolo checks output?

**Comment by lucalazzaroni** [comment]
@ambitious-octopus thank you, it was indeed a data issue because with `coco8.yaml` it works. However, I don't know how can it be possible that it's a data problem because I trained my model with the same dataset. My yaml file is as follows:

```
train: ./tld/train/images
val: ./tld/valid/images
test: ./tld/test/images

nc: 5
names: [0,1,2,3,4]
```

And here is my `yolo checks` on the Windows machine:
```
Ultralytics 8.3.2 🚀 Python-3.8.19 torch-2.4.1+cu124 CUDA:0 (NVIDIA GeForce RTX 4080, 16376MiB)
Setup complete ✅ (32 CPUs, 29.7 GB RAM, 436.7/453.7 GB disk)

OS                  Windows-10-10.0.22631-SP0
Environment         Windows
Python              3.8.19
Install             pip
RAM                 29.66 GB
CPU                 Intel Core(TM) i9-14900K
CUDA                12.4

numpy               ✅ 1.24.1<2.0.0,>=1.23.0
matplotlib          ✅ 3.7.5>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.4.1+cu124>=1.8.0
torchvision         ✅ 0.19.1+cu124>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.8>=2.0.0
torch               ✅ 2.4.1+cu124!=2.4.0,>=1.8.0; sys_platform == "win32"
```

**Comment by yg-dickson** [comment]
RuntimeError: Quantized dimension for tensor property and quantization parameters do not match. Got 3 and 0 respectively.

WARNING: INT8 Quantization with int16 activations tflite output failed.
W0000 00:00:1728366998.180039  182160 tf_tfl_flatbuffer_helpers.cc:390] Ignored output_format.
W0000 00:00:1728366998.180061  182160 tf_tfl_flatbuffer_helpers.cc:393] Ignored drop_control_dependency.
Traceback (most recent call last):
  File "/opt/miniconda3/envs/ultralytics/lib/python3.10/site-packages/onnx2tf/onnx2tf.py", line 1597, in convert
    tflite_model = converter.convert()
  File "/opt/miniconda3/envs/ultralytics/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1175, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/opt/miniconda3/envs/ultralytics/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1129, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/opt/miniconda3/envs/ultralytics/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1500, in convert
    return self._convert_from_saved_model(graph_def)
  File "/opt/miniconda3/envs/ultralytics/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1368, in _convert_from_saved_model
    return self._optimize_tflite_model(
  File "/opt/miniconda3/envs/ultralytics/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py", line 215, in wrapper
    raise error from None  # Re-throws the exception.
  File "/opt/miniconda3/envs/ultralytics/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/opt/miniconda3/envs/ultralytics/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1074, in _optimize_tflite_model
    model = self._quantize(
  File "/opt/miniconda3/envs/ultralytics/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 753, in _quantize
    return calibrate_quantize.calibrate_and_quantize(
  File "/opt/miniconda3/envs/ultralytics/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py", line 215, in wrapper
    raise error from None  # Re-throws the exception.
  File "/opt/miniconda3/envs/ultralytics/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/opt/miniconda3/envs/ultralytics/lib/python3.10/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 194, in calibrate_and_quantize
    return self._calibrator.QuantizeModel(
RuntimeError: Quantized dimension for tensor property and quantization parameters do not match. Got 3 and 0 respectively.

WARNING: Full INT8 Quantization with int16 activations tflite output failed.

I keep getting this error, is there any solution? Thank you very much.

**Comment by ambitious-octopus** [comment]
@lucalazzaroni It could be an Out of Memory (OOM), can you check your memory usage, please?

**Comment by lucalazzaroni** [comment]
@ambitious-octopus it is indeed an OOM, when I have more than 400 images the process gets killed because the RAM is full (I have 32 GB RAM though)

**Comment by vjayd** [comment]
I am also observing the same issue while quantizing YOLO11 to int8, by the way  @ambitious-octopus why does it occupy 52GB of RAM for quantization?

**Comment by kuber-petlibro** [comment]
> Ciao @lucalazzaroni, known problem (#15873), we are working to fix it. Be careful though because the full int8 quantization works correctly the problem is only related to the int8 quantization with int16 activations.
> 
> ```python
> from ultralytics import YOLO
> 
> if __name__ == '__main__':
>     model = YOLO("yolo11n.pt")
>     model.export(format="tflite", int8=True, data='coco8.yaml')
>     model = YOLO("yolo11n_saved_model/yolo11n_full_integer_quant.tflite")
>     res = model.predict()
>     res[0].show()
> ```

If I use the above code and replace yolov11.pt with my own custom yolov8s model; It exports without errors, but it does still show the precision of weights stored in onnx version as "FLOAT" (fp32). Any idea what's happening? I am trying to export to ONNX int8 precision; with custom "data" file too! There is not much difference between coco8.yaml and coco_custom.yaml; expect the later contains only 2 classes from superset of COCO classes. PFA screenshot of weight precision, when I load the saved int8 onnx model.
<img width="660" alt="Screenshot 2024-10-10 at 8 05 55 PM" src="https://github.com/user-attachments/assets/3ac86f0b-fe18-4ed2-af8b-12070b53c108">

**Comment by CH-Echo** [comment]
Please tell me about yolo11pose. I feel that it is not reasonable to use int8 for pose. The principle of the model is top-down. What I want to know is whether it is possible to use int8 when detecting the human body and use fp16 when posing. I want to know the feasibility.

**Comment by WildTaras** [comment]
Hi. May I ask for a help. I did next 
    model = YOLO('yolo11n.pt')
    model.export(format="tflite", int8=True, data='coco8.yaml')
    model = YOLO("yolo11n_saved_model/yolo11n_full_integer_quant.tflite", task="detect")
    res = model('frame00002.png')
    res[0].show()

I have problem during running inference on image
predictor.py", line 216, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
torch/utils/_contextlib.py", line 36, in generator_context
    response = gen.send(None)
engine/predictor.py", line 332, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
yolo/detect/predict.py", line 54, in postprocess
    preds = ops.non_max_suppression(
/ops.py", line 265, in non_max_suppression
    output = [torch.zeros((0, 6 + nm), device=prediction.device)] * bs
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Trying to create tensor with negative dimension -913: [0, -913]

**Comment by glenn-jocher** [comment]
@lucalazzaroni Thanks for confirming it's an OOM issue. This is a known behavior with INT8 calibration - it loads multiple batches of calibration data into memory simultaneously during the process.

You can use the `fraction` parameter to reduce memory usage while maintaining good calibration quality. For example:

```python
model.export(format="tflite", int8=True, data='data.yaml', fraction=0.1)
```

This would use only 10% of your validation dataset for calibration, substantially reducing memory requirements.

@vjayd The high memory usage during quantization is because the calibration process loads all representative images into memory to analyze activation distributions across layers. For larger models like YOLO11M, this becomes especially memory-intensive. Using the `fraction` parameter as suggested above can help manage memory usage.

@kuby-dl When exporting to ONNX with INT8, note that the model weights stored in the ONNX file remain as FP32, but the runtime quantization happens during inference. This is expected behavior - the actual quantization is handled by the inference engine.

@CH-Echo Yes, it's possible to use mixed precision in model deployment, but it requires custom post-processing. You would need to export the detection portion with INT8 and the pose estimation with FP16, then create a custom pipeline that connects them.

@WildTaras That error indicates a shape mismatch in the post-processing. Try using a more recent version of Ultralytics, as this specific issue has been addressed in recent updates.

**Comment by manueldiaz96** [comment]
Hi @glenn-jocher, I am not sure if I undestood you correctly when you said:

> When exporting to ONNX with INT8, note that the model weights stored in the ONNX file remain as FP32, but the runtime quantization happens during inference. This is expected behavior - the actual quantization is handled by the inference engine.

Does the INT8 quantization happen after converting the model to an ONNX file? So basically it is done by the TensorRT engine? 

I have the following code, but I do not seem to get the models to quantize to INT8. Could you give me some hints on what might I be setting up wrong?

```python
from ultralytics import YOLO
import argparse
import os

if __name__ == "__main__":

    parser = argparse.ArgumentParser()

    # Adding optional argument
    parser.add_argument("-v", "--version", default='nano', type=str, help = "YOLOv11 version: ['large' , 'nano']")

    args = parser.parse_args()

    assert args.version in ["large", "nano"], "Invalid YOLO version, please use 'nano' or 'large'" 

    model_name = "yolo11"

    if args.version == "large":

        model_name += "l"
        
    elif args.version == "nano":

        model_name += "n"
        
    model = YOLO(model_name+".pt")

    model.export(format='engine', 
                    int8 = True, 
                    half = False, 
                    workspace=2, 
                    verbose=True, 
                    batch=1, 
                    nms=True,
                    data='coco8.yaml')

    print("\n")
    print("#"*60)
    print("Verification Test")
    print("#"*60)
    print("\n")

    image = 'bus.jpg' # Downloaded from:  https://ultralytics.com/images/bus.jpg

    for model_file in [model_name+".pt", model_name+".engine"]:

        print(f"Running Model File: {model_file}")

        model = YOLO(model_file, task='detect')

        for _ in range(10): model.predict(source=image, device=0, verbose=False)

        start = time.perf_counter()
        for _ in range(100): model.predict(source=image, device=0, verbose=False)
        print(f"Avg: {(time.perf_counter()-start)/100*1000:.2f} ms")
```

I say that the models are not being quantized to INT8 given that I get messages like `TensorRT: building FP16 engine as yolo11n.engine` that indicate the model is not being compiled as INT8:

```bash
ONNX: starting export with onnx 1.19.1 opset 17...
ONNX: slimming with onnxslim 0.1.71...
ONNX: export success ✅ 22.7s, saved as 'yolo11n.onnx' (10.2 MB)

TensorRT: starting export with TensorRT 10.7.0...
[10/17/2025-06:35:34] [TRT] [I] [MemUsageChange] Init CUDA: CPU -1, GPU +0, now: CPU 634, GPU 2534 (MiB)
[10/17/2025-06:35:34] [TRT] [V] Trying to load shared library libnvinfer_builder_resource.so.10.7.0
[10/17/2025-06:35:34] [TRT] [V] Loaded shared library libnvinfer_builder_resource.so.10.7.0
[10/17/2025-06:35:36] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +980, GPU +1161, now: CPU 1649, GPU 3736 (MiB)
[10/17/2025-06:35:36] [TRT] [V] CUDA lazy loading is enabled.
[10/17/2025-06:35:36] [TRT] [I] ----------------------------------------------------------------
[10/17/2025-06:35:36] [TRT] [I] Input filename:   yolo11n.onnx
[10/17/2025-06:35:36] [TRT] [I] ONNX IR version:  0.0.8
[10/17/2025-06:35:36] [TRT] [I] Opset version:    17
[10/17/2025-06:35:36] [TRT] [I] Producer name:    pytorch
[10/17/2025-06:35:36] [TRT] [I] Producer version: 2.5.0
[10/17/2025-06:35:36] [TRT] [I] Domain:           
[10/17/2025-06:35:36] [TRT] [I] Model version:    0
[10/17/2025-06:35:36] [TRT] [I] Doc string:       
[10/17/2025-06:35:36] [TRT] [I] ----------------------------------------------------------------
[10/17/2025-06:35:36] [TRT] [V] Adding network input: images with dtype: float32, dimensions: (1, 3, 640, 640)
[10/17/2025-06:35:36] [TRT] [V] Registering tensor: images for ONNX tensor: images
[10/17/2025-06:35:36] [TRT] [V] Importing initializer: model.0.conv.weight
...
[10/17/2025-06:35:37] [TRT] [V] /model.23/Concat_5 [Concat] outputs: [output0 -> (1, 84, 8400)[FLOAT]], 
[10/17/2025-06:35:37] [TRT] [V] Marking output0_110 as output: output0
TensorRT: input "images" with shape(1, 3, 640, 640) DataType.FLOAT
TensorRT: output "output0" with shape(1, 84, 8400) DataType.FLOAT
TensorRT: building FP16 engine as yolo11n.engine
...
Layer(Myelin): {ForeignNode[/model.23/Split_40.../model.23/Concat_5]}, Tactic: 0x0000000000000000, /model.23/Concat_3_output_0 (Half[1,144,8400]), /model.23/Mul_2_output_0 (Half[1,4,8400]) -> Reformatted Output Tensor 0 to {ForeignNode[/model.23/Split_40.../model.23/Concat_5]} (Half[1,84,8400])
Layer(Reformat): Reformatting CopyNode for Output Tensor 0 to {ForeignNode[/model.23/Split_40.../model.23/Concat_5]}, Tactic: 0x00000000000003e8, Reformatted Output Tensor 0 to {ForeignNode[/model.23/Split_40.../model.23/Concat_5]} (Half[1,84,8400]) -> output0 (Float[1,84,8400])
[10/17/2025-06:57:18] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 0 MiB, GPU 260 MiB
[10/17/2025-06:57:18] [TRT] [V] Adding 1 engine(s) to plan file.
[10/17/2025-06:57:18] [TRT] [V] Adding 1 engine weights(s) to plan file.
TensorRT: export success ✅ 553.9s, saved as 'yolo11n.engine' (7.9 MB)

Export complete (555.3s)
Results saved to /mydir/quantize_models
Predict:         yolo predict task=detect model=yolo11n.engine imgsz=640 half 
Validate:        yolo val task=detect model=yolo11n.engine imgsz=640 data=/usr/src/ultralytics/ultralytics/cfg/datasets/coco.yaml half 
Visualize:       https://netron.app

############################################################
Verification Test
############################################################

Running Model File: yolo11n.pt
Avg: 48.95 ms
Running Model File: yolo11n.engine
Loading yolo11n.engine for TensorRT inference...
[10/17/2025-07:31:39] [TRT] [I] Loaded engine size: 11 MiB
[10/17/2025-07:31:39] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +18, now: CPU 0, GPU 28 (MiB)
Avg: 42.14 ms

```
Also the timings are almost the same after the export, nor the download folders for the COCO8 samples that would be used for calibration. I have also tried using `data=coco128.yaml` but no downloads appear either. 

I am running all of these tests on a Jetson Orin NX 16GB with Jetpack 6.1, here is my system info:

```
Ultralytics 8.3.215 🚀 Python-3.10.12 torch-2.5.0a0+872d972e41.nv24.08 CUDA:0 (Orin, 15656MiB)
Setup complete ✅ (8 CPUs, 15.3 GB RAM, 88.3/115.4 GB disk)

OS                     Linux-5.15.148-tegra-aarch64-with-glibc2.35
Environment            Docker
Python                 3.10.12
Install                pip
Path                   /usr/local/lib/python3.10/dist-packages/ultralytics
RAM                    15.29 GB
Disk                   88.3/115.4 GB
CPU                    ARMv8 Processor rev 1 (v8l)
CPU count              8
GPU                    Orin, 15656MiB
GPU count              1
CUDA                   12.6

numpy                  ✅ 1.26.4>=1.23.0
matplotlib             ✅ 3.10.7>=3.3.0
opencv-python          ✅ 4.10.0.84>=4.6.0
pillow                 ✅ 12.0.0>=7.1.2
pyyaml                 ✅ 6.0.3>=5.3.1
requests               ✅ 2.32.5>=2.23.0
scipy                  ✅ 1.15.3>=1.4.1
torch                  ✅ 2.5.0a0+872d972e41.nv24.8>=1.8.0
torch                  ✅ 2.5.0a0+872d972e41.nv24.8!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision            ✅ 0.20.0a0+afc54f7>=0.9.0
psutil                 ✅ 5.9.0
polars                 ✅ 1.34.0
ultralytics-thop       ✅ 2.0.17>=2.0.0
{'OS': 'Linux-5.15.148-tegra-aarch64-with-glibc2.35', 'Environment': 'Docker', 'Python': '3.10.12', 'Install': 'pip', 'Path': '/usr/local/lib/python3.10/dist-packages/ultralytics', 'RAM': '15.29 GB', 'Disk': '88.3/115.4 GB', 'CPU': 'ARMv8 Processor rev 1 (v8l)', 'CPU count': 8, 'GPU': 'Orin, 15656MiB', 'GPU count': 1, 'CUDA': '12.6', 'Package Info': {'numpy': '✅ 1.26.4>=1.23.0', 'matplotlib': '✅ 3.10.7>=3.3.0', 'opencv-python': '✅ 4.10.0.84>=4.6.0', 'pillow': '✅ 12.0.0>=7.1.2', 'pyyaml': '✅ 6.0.3>=5.3.1', 'requests': '✅ 2.32.5>=2.23.0', 'scipy': '✅ 1.15.3>=1.4.1', 'torch': '✅ 2.5.0a0+872d972e41.nv24.8!=2.4.0,>=1.8.0; sys_platform == "win32"', 'torchvision': '✅ 0.20.0a0+afc54f7>=0.9.0', 'psutil': '✅ 5.9.0', 'polars': '✅ 1.34.0', 'ultralytics-thop': '✅ 2.0.17>=2.0.0'}}
```

Any help would be greatly appreciated. Thanks!

**Comment by glenn-jocher** [comment]
@manueldiaz96 Correct—ONNX stays FP32; INT8 is applied by TensorRT when it builds the engine using your calibration data. Your log shows a FP16 fallback, which usually means no INT8 calibration profile was attached (dataset not resolved, stale cache, or unsupported builder config). Please try:

```python
from ultralytics import YOLO

m = YOLO("yolo11n.pt")
m.export(
    format="engine",
    int8=True,
    dynamic=True,
    batch=8,           # helps calibration stability
    workspace=4,
    data="coco128.yaml",  # or your val set
    fraction=0.3,      # reduce RAM usage
    verbose=True
)
# Optional on Jetson DLA:
# m.export(format="engine", int8=True, device="dla:0", batch=8, data="coco128.yaml", fraction=0.3, verbose=True)
```

Before re-exporting, delete any existing calibration cache next to the ONNX (`*.cache`). On success you should see “building INT8 engine” and a new `.cache` file. Full guidance is in the TensorRT INT8 section of our docs: see the [TensorRT INT8 export guide](https://docs.ultralytics.com/integrations/tensorrt/) and the [export arguments reference](https://docs.ultralytics.com/modes/export/). If it still builds FP16, please share the full `verbose=True` export log from the same container so we can check why INT8 isn’t being enabled.

**Comment by manueldiaz96** [comment]
Thank you @ambitious-octopus ! 
I am not sure why it was not working, but with the set of args you gave, worked perfectly!
