### ISSUE TITLE
Plotting different track ids corresponding bounding boxes with different colors

### ISSUE THREAD

**Issue by sivaji123256** [ultralytics/ultralytics#1673]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi @glenn-jocher @Laughing-q @AyushExel ,I was trying to assign different colors to different track ids available in the frame for better visualization instead of a single color for all the instances (track ids).Any suggestions would help me .Thanks in advance.

**Comment by Laughing-q** [comment]
@sivaji123256 for now the colors depends on the predicted idx of category. I think you can assign colors to ids by replacing the `colors(c, True)` to `colors(id, True)`:
[https://github.com/ultralytics/ultralytics/blob/ec10002a4ade5a43abb9d5765f77eefddf98904b/ultralytics/yolo/v8/detect/predict.py#L74](https://github.com/ultralytics/ultralytics/blob/ec10002a4ade5a43abb9d5765f77eefddf98904b/ultralytics/yolo/v8/detect/predict.py#L74)
