### ISSUE TITLE
Error in Model Training when using the optuna for HYO:  ValueError 'object of too small depth for desired arrary

### ISSUE THREAD

**Issue by Badar-e-Alam** [ultralytics/ultralytics#16738]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Hyperparameter Tuning

### Bug

As you can see from the following error, it occurred on Trial 73. This indicates that the code successfully completed 72 trials without any errors. I suspect that the error might be related to a specific hyperparameter suggested by Optuna, but I’m not sure which one. The whole objective here to maximize the mAp50-95B value on validation dataset.

````shell
[W 2024-10-07 12:36:42,866] Trial 73 failed with parameters: {'epochs': 9, 'batch_size': 15, 'learning_rate': 8.423355336732259e-05, 'optimizer': 'SGD', 'model_type': 'yolov8s', 'imgsize': 857, 'patience': 16, 'cos_lr': True, 'close_mosaic': 2, 'determinstic': False, 'freeze': 3, 'weight_decay': 7.413698668293164e-05, 'mixup': 0.037920535047583595, 'label_smoothing': 0.18938126398552818} because of the following error: ValueError('object of too small depth for desired array').
Traceback (most recent call last):
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\optuna\study\_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "C:\Users\b.alam\Desktop\Yolo\Chisels_Detection\HYO\HYO_small.py", line 40, in objective
    model.train(
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\ultralytics\engine\model.py", line 802, in train
    self.trainer.train()
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\ultralytics\engine\trainer.py", line 207, in train
    self._do_train(world_size)
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\ultralytics\engine\trainer.py", line 479, in _do_train
    self.run_callbacks("on_train_end")
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\ultralytics\engine\trainer.py", line 168, in run_callbacks
    callback(self)
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\ultralytics\utils\callbacks\wb.py", line 142, in on_train_end
    _plot_curve(
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\ultralytics\utils\callbacks\wb.py", line 87, in _plot_curve
    y_log = np.interp(x_new, x, np.mean(y, axis=0)).round(3).tolist()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\numpy\lib\function_base.py", line 1599, in interp
    return interp_func(x, xp, fp, left, right)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: object of too small depth for desired array
[W 2024-10-07 12:36:42,918] Trial 73 failed with value None.
Traceback (most recent call last):
  File "C:\Users\b.alam\Desktop\Yolo\Chisels_Detection\HYO\HYO_small.py", line 88, in <module>
    # Run the optimization
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\optuna\study\study.py", line 475, in optimize
    _optimize(
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\optuna\study\_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\optuna\study\_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\optuna\study\_optimize.py", line 248, in _run_trial
    raise func_err
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\optuna\study\_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "C:\Users\b.alam\Desktop\Yolo\Chisels_Detection\HYO\HYO_small.py", line 40, in objective
    model.train(
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\ultralytics\engine\model.py", line 802, in train
    self.trainer.train()
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\ultralytics\engine\trainer.py", line 207, in train
    self._do_train(world_size)
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\ultralytics\engine\trainer.py", line 479, in _do_train
    self.run_callbacks("on_train_end")
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\ultralytics\engine\trainer.py", line 168, in run_callbacks
    callback(self)
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\ultralytics\utils\callbacks\wb.py", line 142, in on_train_end
    _plot_curve(
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\ultralytics\utils\callbacks\wb.py", line 87, in _plot_curve
    y_log = np.interp(x_new, x, np.mean(y, axis=0)).round(3).tolist()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\b.alam\.conda\envs\yolo\Lib\site-packages\numpy\lib\function_base.py", line 1599, in interp
    return interp_func(x, xp, fp, left, right)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: object of too small depth for desired array




### Environment

Ultralytics 8.3.5 🚀 Python-3.12.4 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4090, 24564MiB)
Setup complete ✅ (16 CPUs, 63.9 GB RAM, 198.2/1907.0 GB disk)

### Minimal Reproducible Example

````python
def objective(trial):
    # Suggest hyperparameters
    epochs = trial.suggest_int("epochs", 0, 10)

    batch_size = trial.suggest_int("batch_size", 4, 16)
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-5, 1e-2)
    optimizer = trial.suggest_categorical(
        "optimizer",
        ["Adam", "SGD", "AdamW", "NAdam", "RAdam", "RMSProp", "auto"],
    )
    model_type = trial.suggest_categorical(
        "model_type",
        [
            "yolov8n",
            # "yolov8s",
            # "yolov8m",
            # "yolov8l",
        ],
    )
    imgsize = trial.suggest_int("imgsize", 640, 1024)
    patience = trial.suggest_int("patience", 10, 100)
    cos_lr = trial.suggest_categorical("cos_lr", [True, False])
    close_mosaic = trial.suggest_int("close_mosaic", 0, 20)
    determinstic = trial.suggest_categorical("determinstic", [True, False])
    freeze = trial.suggest_int("freeze", 0, 5)
    weight_decay = trial.suggest_loguniform("weight_decay", 1e-5, 1e-2)
    mixup = trial.suggest_float("mixup", 0.0, 1.0)
    label_smoothing = trial.suggest_float("label_smoothing", 0.0, 0.8)
    # Load the model
    model = YOLO(
        f"C:/Users/b.alam/Desktop/Yolo/Chisels_Detection/pretrained_model/{model_type}.pt"
    )

    # Train the model
    model.train(
        data="C:/Users/b.alam/Desktop/Yolo/Chisels_Detection/Config/data_2.yaml",
        epochs=epochs,
        batch=batch_size,
        lr0=learning_rate,
        cache=True,
        save=False,
        save_period=-1,
        task="detect",
        imgsz=imgsize,
        cos_lr=cos_lr,
        close_mosaic=close_mosaic,
        optimizer=optimizer,
        verbose=False,
        workers=8,
        device=1,
        patience=patience,
        amp=True,
        freeze=freeze,
        weight_decay=weight_decay,
        mixup=mixup,
        label_smoothing=label_smoothing,
    )

    # Evaluate the model
    results = model.val(
        data="C:/Users/b.alam/Desktop/Yolo/Chisels_Detection/Config/data_2.yaml"
    )
    trial.report(results.maps[1], step=trial.number)
    if trial.should_prune():
        raise optuna.TrialPruned()

    print(f"mAP: {results.maps[1]}")
    # Return the evaluation metric (e.g., mAP)
    return results.maps[1]
````

### Additional

I have see you previous comment on similar issue but its different I cross check every point you mentioned could potential lead to this error.I have reviewed your previous comment on a similar issue, but this situation is different. I have cross-checked every point you mentioned that could potentially lead to this error

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Badar-e-Alam, thank you for reaching out and sharing your issue with us 🚀! We recommend checking the [Docs](https://docs.ultralytics.com) where you might find helpful examples and answers to common questions.

It seems like you've encountered a 🐛 bug while hyperparameter tuning with Optuna. To assist you better, please ensure that you provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) if not already provided.

Your willingness to submit a PR is greatly appreciated! An Ultralytics engineer will review your issue soon to help further.

Meanwhile, you can join our vibrant Ultralytics community:
- For real-time discussions, join us on [Discord](https://ultralytics.com/discord) 🎧.
- Engage in in-depth discussions on [Discourse](https://community.ultralytics.com).
- Share insights on our [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade

Please upgrade to the latest `ultralytics` package and all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment to see if the issue resolves with the latest updates:

```bash
pip install -U ultralytics
```

## Environments

Ensure YOLO runs in a verified environment:
- **Notebooks** with GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are passing across different platforms.

Stay tuned, and thank you for contributing to the Ultralytics community! ✨

**Comment by Y-T-G** [comment]
The error is in the W&B callback. You can try uninstalling it if you're not using it

**Comment by Y-T-G** [comment]
What are the particular hyperparameters that caused this error?

**Comment by Badar-e-Alam** [comment]
I have tried uninstalling and reinstalling W&B, but I don't think the issue is related to that. I suspect it might be related to `imgsize`, but as you can see, Optuna is set to recommend the `imgsize` value from a specific range (640-1024), which shouldn't be problematic.

**Comment by Y-T-G** [comment]
`ultralytics` has hyperparameter tuning built-in.

https://docs.ultralytics.com/guides/hyperparameter-tuning/

**Comment by Badar-e-Alam** [comment]
Yes, I looked into it, and Ray Tune as well, but you don’t have much freedom there to create the hyperparameter search space. For example, you can't try out different image sizes, batch sizes, etc.

**Comment by Y-T-G** [comment]
Ray tune supports tuning most parameters including batch size, optimizer, image size. You just need to pass `space` as an argument.

It doesn't support different models during tuning, but a model is not a hyperparameter. A larger model will obviously get better scores. At that point you can just perform multiple hyperparameter tuning using ray-tune, one for each model.

**Comment by glenn-jocher** [comment]
Great news 😃! Your original issue may now be resolved ✅ in PR #17088. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by Badar-e-Alam** [comment]
I also solved this issue by commenting out the __plot_curve function because it was happening because of W&B logging.

**Comment by glenn-jocher** [comment]
Thank you for sharing your solution. If you encounter further issues, feel free to reach out for assistance.
