### ISSUE TITLE
multiGPU fails with "returned non-zero exit status 1" for detection training

### ISSUE THREAD

**Issue by amor-volastra** [ultralytics/ultralytics#1675]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

numpy= 1.24.2
mkl-service= 2.4.0
Ultralytics YOLOv8.0.58 🚀 Python-3.9.5 torch-1.13.0+cu117 CUDA:0 (Tesla T4, 15110MiB)
                                                           CUDA:1 (Tesla T4, 15110MiB)
                                                           CUDA:2 (Tesla T4, 15110MiB)
                                                           CUDA:3 (Tesla T4, 15110MiB)
yolo/engine/trainer: task=detect, mode=train, model=yolov8s.pt, data=/dbfs/mnt/amortazi/TCGA OvCa 40x WSI diagnostic slides/train_valid_yolov8/fold_test2/data.yaml, epochs=12, patience=50, batch=4, imgsz=512, save=True, save_period=-1, cache=False, device=0,1,2,3, workers=8, project=/databricks/driver/, name=test_multigpu, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=/databricks/driver/test_multigpu
Overriding model.yaml nc=80 with nc=2

                   from  n    params  module                                       arguments                     
  0                  -1  1       928  ultralytics.nn.modules.Conv                  [3, 32, 3, 2]                 
  1                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]                
  2                  -1  1     29056  ultralytics.nn.modules.C2f                   [64, 64, 1, True]             
  3                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]               
  4                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]           
  5                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]              
  6                  -1  2    788480  ultralytics.nn.modules.C2f                   [256, 256, 2, True]           
  7                  -1  1   1180672  ultralytics.nn.modules.Conv                  [256, 512, 3, 2]              
  8                  -1  1   1838080  ultralytics.nn.modules.C2f                   [512, 512, 1, True]           
  9                  -1  1    656896  ultralytics.nn.modules.SPPF                  [512, 512, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]                           
 12                  -1  1    591360  ultralytics.nn.modules.C2f                   [768, 256, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]                           
 15                  -1  1    148224  ultralytics.nn.modules.C2f                   [384, 128, 1]                 
 16                  -1  1    147712  ultralytics.nn.modules.Conv                  [128, 128, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]                           
 18                  -1  1    493056  ultralytics.nn.modules.C2f                   [384, 256, 1]                 
 19                  -1  1    590336  ultralytics.nn.modules.Conv                  [256, 256, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]                           
 21                  -1  1   1969152  ultralytics.nn.modules.C2f                   [768, 512, 1]                 
 22        [15, 18, 21]  1   2116822  ultralytics.nn.modules.Detect                [2, [128, 256, 512]]          
Model summary: 225 layers, 11136374 parameters, 11136358 gradients, 28.6 GFLOPs

Transferred 349/355 items from pretrained weights
Running DDP command ['/local_disk0/.ephemeral_nfs/envs/pythonEnv-e01025ab-3f13-4188-9cba-8b0a7ef3fb2e/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '38909', '/databricks/python_shell/scripts/db_ipykernel_launcher.py', 'task=detect', 'mode=train', 'model=yolov8s.pt', 'data=/dbfs/mnt/amortazi/TCGA OvCa 40x WSI diagnostic slides/train_valid_yolov8/fold_test2/data.yaml', 'epochs=12', 'patience=50', 'batch=4', 'imgsz=512', 'save=True', 'save_period=-1', 'cache=False', 'device=0,1,2,3', 'workers=8', 'project=/databricks/driver/', 'name=test_multigpu', 'exist_ok=False', 'pretrained=False', 'optimizer=SGD', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'image_weights=False', 'rect=False', 'cos_lr=False', 'close_mosaic=10', 'resume=False', 'amp=True', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'save_hybrid=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'source=None', 'show=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'hide_labels=False', 'hide_conf=False', 'vid_stride=1', 'line_thickness=3', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'boxes=True', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=False', 'opset=None', 'workspace=4', 'nms=False', 'lr0=0.01', 'lrf=0.01', 'momentum=0.937', 'weight_decay=0.0005', 'warmup_epochs=3.0', 'warmup_momentum=0.8', 'warmup_bias_lr=0.1', 'box=7.5', 'cls=0.5', 'dfl=1.5', 'fl_gamma=0.0', 'label_smoothing=0.0', 'nbs=64', 'hsv_h=0.015', 'hsv_s=0.7', 'hsv_v=0.4', 'degrees=0.0', 'translate=0.1', 'scale=0.5', 'shear=0.0', 'perspective=0.0', 'flipud=0.0', 'fliplr=0.5', 'mosaic=1.0', 'mixup=0.0', 'copy_paste=0.0', 'cfg=None', 'v5loader=False', 'tracker=botsort.yaml']
CalledProcessError: Command '['/local_disk0/.ephemeral_nfs/envs/pythonEnv-e01025ab-3f13-4188-9cba-8b0a7ef3fb2e/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '38909', '/databricks/python_shell/scripts/db_ipykernel_launcher.py', 'task=detect', 'mode=train', 'model=yolov8s.pt', 'data=/dbfs/mnt/amortazi/TCGA OvCa 40x WSI diagnostic slides/train_valid_yolov8/fold_test2/data.yaml', 'epochs=12', 'patience=50', 'batch=4', 'imgsz=512', 'save=True', 'save_period=-1', 'cache=False', 'device=0,1,2,3', 'workers=8', 'project=/databricks/driver/', 'name=test_multigpu', 'exist_ok=False', 'pretrained=False', 'optimizer=SGD', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'image_weights=False', 'rect=False', 'cos_lr=False', 'close_mosaic=10', 'resume=False', 'amp=True', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'save_hybrid=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'source=None', 'show=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'hide_labels=False', 'hide_conf=False', 'vid_stride=1', 'line_thickness=3', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'boxes=True', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=False', 'opset=None', 'workspace=4', 'nms=False', 'lr0=0.01', 'lrf=0.01', 'momentum=0.937', 'weight_decay=0.0005', 'warmup_epochs=3.0', 'warmup_momentum=0.8', 'warmup_bias_lr=0.1', 'box=7.5', 'cls=0.5', 'dfl=1.5', 'fl_gamma=0.0', 'label_smoothing=0.0', 'nbs=64', 'hsv_h=0.015', 'hsv_s=0.7', 'hsv_v=0.4', 'degrees=0.0', 'translate=0.1', 'scale=0.5', 'shear=0.0', 'perspective=0.0', 'flipud=0.0', 'fliplr=0.5', 'mosaic=1.0', 'mixup=0.0', 'copy_paste=0.0', 'cfg=None', 'v5loader=False', 'tracker=botsort.yaml']' returned non-zero exit status 1.

### Environment

numpy= 1.24.2
mkl-service= 2.4.0
Ultralytics YOLOv8.0.58 
 Python-3.9.5 
torch-1.13.0+cu117 
CUDA:0 (Tesla T4, 15110MiB)
CUDA:1 (Tesla T4, 15110MiB)
CUDA:2 (Tesla T4, 15110MiB)
CUDA:3 (Tesla T4, 15110MiB)

### Minimal Reproducible Example

`from ultralytics import YOLO
import os

os.environ['MKL_SERVICE_FORCE_INTEL'] = '1'
model = YOLO('yolov8s.pt')
data = "/dbfs/mnt/train_valid_yolov8/fold_test2/data.yaml"
model.train(
data=data,
imgsz=512,
epochs=12,
batch=4,
project='/databricks/driver/',
name='test_multigpu',
device='0,1,2,3'
)`

### Additional

I updated numpy to latest version and also set MKL_SERVICE_FORCE_INTEL=1. But didn't help (tried this https://github.com/pytorch/pytorch/issues/37377 and https://github.com/ultralytics/ultralytics/issues/1499), but didn't work.
I can do training in single GPU without any any issue.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by LegendSun0** [comment]
I was using the official image and fixed the problem when I upgraded numpy to install numpy==1.23.4

**Comment by glenn-jocher** [comment]
I'm glad to hear that you were able to fix your problem! Upgrading numpy is often a good solution when encountering compatibility issues with Python packages. If you encounter any other issues or have any other questions, feel free to ask!
