### ISSUE TITLE
The YOLOv8s model in v8.3 has a different number of parameters compared to v8.2.

### ISSUE THREAD

**Issue by Fang-lolo** [ultralytics/ultralytics#16761]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

After the release of YOLO11, I downloaded the latest v8.3 code. I was able to train my dataset well using the YOLOv8s model in v8.2, but when training with the YOLOv8s model in v8.3, I encountered an "out of memory" issue.
I can confirm that when using both v8.2 and v8.3, my parameter settings were identical (data augmentation parameters, batch size, device, etc.). Upon comparison, I noticed a difference in the number of parameters in the head section (the first image is from v8.2, and the second image is from v8.3). Interestingly, the v8.3 version, which triggered the out-of-memory error, has fewer parameters and lower computational requirements.
![v8 2](https://github.com/user-attachments/assets/19c2e721-c781-4c33-8ed5-bc5a57ea469e)
![v8 3](https://github.com/user-attachments/assets/f6c976eb-86ba-438a-b4ba-f109794f2716)

Note: I originally intended to train my data using the YOLO11s model, but I encountered an out-of-memory issue. Since YOLO11s has fewer parameters and lower computational requirements compared to YOLOv8s, I was confused as to why I could train with YOLOv8s but not YOLO11s. Therefore, I compared the training of YOLOv8s in both versions. Surprisingly, the YOLOv8s model in v8.3 also encountered an out-of-memory issue. Even after switching machines, the same problem persisted.

### Additional
I noticed that some others have encountered a similar issue before, where YOLO11-seg training takes up more GPU memory than YOLOv8-seg.
_No response_

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Fang-lolo, thank you for reaching out to Ultralytics 🚀! We appreciate your interest and are here to help.

It seems like you've encountered an issue with the YOLOv8s model between versions v8.2 and v8.3. If this is a 🐛 Bug Report, could you please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/)? This would greatly assist us in understanding and resolving the issue more efficiently.

In the meantime, ensure you're using the latest version by upgrading your `ultralytics` package:

```bash
pip install -U ultralytics
```

Our [Docs](https://docs.ultralytics.com) are a great place to find more resources and examples. For further assistance and community support, feel free to join our [Discord](https://ultralytics.com/discord) 🎧, participate in discussions on [Discourse](https://community.ultralytics.com), or engage with others on our [Subreddit](https://reddit.com/r/ultralytics).

An Ultralytics engineer will review your issue soon to provide more targeted assistance. Thanks for your patience and support!

## Environments

YOLO models can be run seamlessly in any of these environments:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM: See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI: See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**: See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

Check out our CI tests to ensure that all functionalities are working as expected: <a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

Stay tuned for further updates, and thank you for your contribution! 😊

**Comment by Skillnoob** [comment]
The `Detect` head got changed with v11, so the previous v8 models inherited the new head. Its not the "true" yolov8 head anymore, but the current published yolov8 models still have the old head.

**Comment by Fang-lolo** [comment]
> The `Detect` head got changed with v11, so the previous v8 models inherited the new head. Its not the "true" yolov8 head anymore, but the current published yolov8 models still have the old head.

Thank you for your response. It seems that the new head has reduced the number of parameters, but the issue I've encountered is that with a smaller number of parameters, it occupies more memory than the old version of YOLOv8.

**Comment by Y-T-G** [comment]
Try updating to the latest version.

**Comment by Le0v1n** [comment]
I have the same question, you can check it?

Thanks for ur patience! 😊@ @glenn-jocher

**Comment by glenn-jocher** [comment]
Please provide more details about your question, and I'll be happy to assist you.
