### ISSUE TITLE
Yolo uses test to validate instead of validation for classification

### ISSUE THREAD

**Issue by lorenzomammana** [ultralytics/ultralytics#1677]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Hi, first of all thanks for the great work done in the repo, I'm currently experimenting with the classification scenario, I saw that we can pass to data_path the path to a folder containing what I would expect to be a train/val/test subdivision, but the validation is never used if test set is available.

This is because on line 296 of yolo/data/utils.py we find
`test_set = data_dir / 'test' if (data_dir / 'test').exists() else data_dir / 'val'  # data/test or data/val`

Is it intended? Why we should prioritize data/test over data/val during training?

I saw that the code is also called from the validator, maybe there's also some weird interaction here.

### Environment

    Ultralytics YOLOv8.0.58 🚀 Python-3.9.15 torch-1.13.1+cu117 CUDA:0 (Tesla V100-DGXS-32GB, 32505MiB)
    OS: Ubuntu 20.04
    Python: 3.9

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@lorenzomammana yes this is because some of datasets lacked a 'val' split but contain a 'test' split. If it makes more sense to swap this order then please submit a PR to main with this change, thank you!
