### ISSUE TITLE
export bbox

### ISSUE THREAD

**Issue by dungx48** [ultralytics/ultralytics#1679]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can i export boudingbox after using tensorrt model?

**Comment by glenn-jocher** [comment]
@dungx48 all exported models run inference just like pytorch models:

```python
from ultralytics import YOLO

model = YOLO('yolov8n.engine')
results = model(img)
```

For handling inference results see https://docs.ultralytics.com/modes/predict

**Comment by dungx48** [comment]
@glenn-jocher Thanks for your help :+1:
