### ISSUE TITLE
Can't train instance segmentation on custom dataset

### ISSUE THREAD

**Issue by aurelien-m** [ultralytics/ultralytics#1681]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

```
Traceback (most recent call last):
  File "/home/aurelien/Projects/Venvs/yolov8/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/aurelien/Projects/Venvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/cfg/__init__.py", line 318, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/aurelien/Projects/Venvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 326, in train
    self.trainer.train()
  File "/home/aurelien/Projects/Venvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 186, in train
    self._do_train(RANK, world_size)
  File "/home/aurelien/Projects/Venvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 317, in _do_train
    self.loss, self.loss_items = self.criterion(preds, batch)
  File "/home/aurelien/Projects/Venvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/v8/segment/train.py", line 40, in criterion
    return self.compute_loss(preds, batch)
  File "/home/aurelien/Projects/Venvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/v8/segment/train.py", line 87, in __call__
    raise TypeError('ERROR ❌ segment dataset incorrectly formatted or not a segment dataset.\n'
TypeError: ERROR ❌ segment dataset incorrectly formatted or not a segment dataset.
This error can occur when incorrectly training a 'segment' model on a 'detect' dataset, i.e. 'yolo train model=yolov8n-seg.pt data=coco128.yaml'.
Verify your dataset is a correctly formatted 'segment' dataset using 'data=coco128-seg.yaml' as an example.
See https://docs.ultralytics.com/tasks/segment/ for help.
```

### Environment

- YOLO v8 8.0.55
- Pop OS 22.04
- Python 3.10.6

### Minimal Reproducible Example

```
yolo segment train model=yolov8l-seg.pt imgsz=512 data=/.../dataset-seg.yaml epochs=400 batch=-1 project=... name=...
```

### Additional

I'm trying to train on a custom dataset, but unfortunately, I have not been able to find any clear documentation on how the dataset must be structured...

Here's what mine looks like:
```
mydataset/
    train/
        images/ ... x.png y.png z.png ...
        labels/ ... x.txt y.txt z.txt ...
    valid/
        images/ ... x.png y.png z.png ...
        labels/ ... x.txt y.txt z.txt ...
````

And in my label files contain:
```
class_id x1 y1 x2 y2 x3 y3 ... xn yn
class_id x1 y1 x2 y2 x3 y3 ... xn yn
class_id x1 y1 x2 y2 x3 y3 ... xn yn
```

Any ideas :smile: thanks!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by aurelien-m** [comment]
I tried `yolo train model=yolov8n-seg.pt data=coco128.yaml` that is recommended but I still have the same issue :eyes:

**Comment by glenn-jocher** [comment]
@aurelien-m if you can successfully train coco128-seg.yaml then your dataset is the problem as the message indicates.

See https://docs.ultralytics.com/tasks/segment for Usage example of training `coco128-seg.yaml`

**Comment by aurelien-m** [comment]
Damn, I'm an idiot, I found my issue. Thanks

**Comment by mahmoudtabikh** [comment]
@aurelien-m what was your issue?

**Comment by glenn-jocher** [comment]
Thanks for sharing the solution that worked for you @aurelien-m! Don't hesitate to let us know if you have any other questions or issues in the future.

**Comment by 523997931** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.
> 
> ### YOLOv8 Component
> Training
> 
> ### Bug
> ```
> Traceback (most recent call last):
>   File "/home/aurelien/Projects/Venvs/yolov8/bin/yolo", line 8, in <module>
>     sys.exit(entrypoint())
>   File "/home/aurelien/Projects/Venvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/cfg/__init__.py", line 318, in entrypoint
>     getattr(model, mode)(**overrides)  # default args from model
>   File "/home/aurelien/Projects/Venvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 326, in train
>     self.trainer.train()
>   File "/home/aurelien/Projects/Venvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 186, in train
>     self._do_train(RANK, world_size)
>   File "/home/aurelien/Projects/Venvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 317, in _do_train
>     self.loss, self.loss_items = self.criterion(preds, batch)
>   File "/home/aurelien/Projects/Venvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/v8/segment/train.py", line 40, in criterion
>     return self.compute_loss(preds, batch)
>   File "/home/aurelien/Projects/Venvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/v8/segment/train.py", line 87, in __call__
>     raise TypeError('ERROR ❌ segment dataset incorrectly formatted or not a segment dataset.\n'
> TypeError: ERROR ❌ segment dataset incorrectly formatted or not a segment dataset.
> This error can occur when incorrectly training a 'segment' model on a 'detect' dataset, i.e. 'yolo train model=yolov8n-seg.pt data=coco128.yaml'.
> Verify your dataset is a correctly formatted 'segment' dataset using 'data=coco128-seg.yaml' as an example.
> See https://docs.ultralytics.com/tasks/segment/ for help.
> ```
> 
> ### Environment
> * YOLO v8 8.0.55
> * Pop OS 22.04
> * Python 3.10.6
> 
> ### Minimal Reproducible Example
> ```
> yolo segment train model=yolov8l-seg.pt imgsz=512 data=/.../dataset-seg.yaml epochs=400 batch=-1 project=... name=...
> ```
> 
> ### Additional
> I'm trying to train on a custom dataset, but unfortunately, I have not been able to find any clear documentation on how the dataset must be structured...
> 
> Here's what mine looks like:
> 
> ```
> mydataset/
>     train/
>         images/ ... x.png y.png z.png ...
>         labels/ ... x.txt y.txt z.txt ...
>     valid/
>         images/ ... x.png y.png z.png ...
>         labels/ ... x.txt y.txt z.txt ...
> ```
> 
> And in my label files contain:
> 
> ```
> class_id x1 y1 x2 y2 x3 y3 ... xn yn
> class_id x1 y1 x2 y2 x3 y3 ... xn yn
> class_id x1 y1 x2 y2 x3 y3 ... xn yn
> ```
> 
> Any ideas 😄 thanks!
> 
> ### Are you willing to submit a PR?
> * [ ]  Yes I'd like to help by submitting a PR!

hi,

**Comment by aurelien-m** [comment]
Hello, it means each point of the polygon that represents the segmentation mask. A tool that I found very helpful was this one: https://github.com/cocodataset/cocoapi/issues/39#issuecomment-456641698

**Comment by glenn-jocher** [comment]
@aurelien-m that's correct. To clarify, each line in your label file should correspond to a polygon that encodes the mask of a particular object in the image. Each line should contain the class id followed by the x and y coordinates of the polygon vertices. The x and y values should be normalized to be between 0 and 1 and relative to the width and height of the image.

Also, as mentioned in the previous comment, the cocoapi provides a great visualization tool to check if your segment annotations are correct. You can follow the instructions provided at https://github.com/cocodataset/cocoapi/issues/39#issuecomment-456641698 to use the tool.

**Comment by Arshadoid** [comment]
Hi @glenn-jocher, 

Just want to clarify the normalization part of segmentation annotation.
I couldn't find detailed information about this beside [this](https://github.com/AlexeyAB/Yolo_mark/issues/60)
According to that x and y should be normalized with height and width via <x> = <absolute_x> / <image_width> and <height> = <absolute_height> / <image_height> respectively. 

Now let's say I have a point with coordinate os (639,31) where image size is (640,320). If I follow the normalization mentioned above I don't think it will be correct. For example:
<x>=639/640=0.9984375
as the coordinate ranges from 0 to 639, shouldn't we divide point coordinates by **<image_width>-1** and  **<image_height>-1** respectively?  
Above provided link doesn't say anything about segmentation so I'm not sure if it's related. 

@aurelien-m may I ask how you solved this conversion and did you have any performance issue with the model?

I know that this normalization conversion should too much impact the performance in general, but still.

**Comment by faisalhazry** [comment]
@glenn-jocher 
I have question about this data set that i have create using roboflow.

`https://universe.roboflow.com/universiti-teknologi-malaysia-h8ohj/corrosion-instance-segmentation/browse?queryText=&pageSize=50&startingIndex=0&browseQuery=true` 

Which is instance segmentation data set. Why  I cannot train using [YOLOv8n-seg] but when i train using [YOLOv8n] the model manage train it and give result using same the data set given 

here is the error appear when using model  [YOLOv8n-seg] 
![error yolo seg](https://github.com/ultralytics/ultralytics/assets/121289405/46f65d95-33f9-4ef1-ba2d-22b0ed6a23cd)

**Comment by glenn-jocher** [comment]
Hello @faisalhazry,
From the error message displayed in the image you attached, it seems that your segmentation dataset might be incorrectly formatted or not a segmentation dataset according to the `YOLov8` model. Make sure that your dataset is properly formatted according to the guidelines provided in the `YOLov8` documentation for training a segmentation model.

Regarding the normalization of coordinates in the segmentation dataset, the coordinates should be normalized with respect to the image size. The values of x and y should be in the range of [0, 1]. So, if you have a point with coordinates (639, 31) on an image with size (640, 320), you should normalize the coordinates as follows: x = 639 / 640 = 0.998 and y = 31 / 320 = 0.097. However, if you observe any performance issues, you may experiment with dividing the point coordinates by (image_width - 1) and (image_height - 1) respectively instead of (image_width) and (image_height).

I hope this helps you resolve your issue. Let me know if you have any other questions!

**Comment by egorovivannn** [comment]
Seems like if you have a polygon with 4 points then model thinks the dataset is for detection and raises the error

**Comment by glenn-jocher** [comment]
@egorovivannn hi there,

It appears that the error you encountered is related to a specific scenario where a polygon with only 2 points was present in your dataset. In YOLOv8, for segmentation tasks, each polygon should have a minimum of 3 pairs of x and y coordinates. This requirement is necessary for accurate segmentation. It seems that you inadvertently included a polygon with only 2 points in your dataset, leading to the error.

In the future, please ensure that all polygons in your segmentation dataset consist of at least 3 pairs of x and y coordinates. Following this guideline will help prevent this error from occurring again.

If you have any further questions or concerns, feel free to ask. We're here to assist you!

Best regards,

**Comment by HawkingRadiation42** [comment]
if my dataset labels contains 4 points creating a rectangle shape, then i cant use the segmentation model here? as it requires more atleast 3 pairs? is that right?  i couldn't use YOLOv8 object detection here as the images are rotated and the bounding boxes created by YOLOv8 are of axis=0.

**Comment by glenn-jocher** [comment]
@HawkingRadiation42 yes, you're correct. For segmentation tasks in YOLOv8, each object must be represented by a polygon with at least three distinct pairs of (x, y) coordinates. If your labels only contain rectangles, represented by 4 points, you won't be able to use the segmentation model here. The polygons in YOLOv8 segmentation tasks must have at least 3 pairs of coordinates because they need to be able to represent arbitrary shapes, not just rectangles.

As for the object detection, YOLOv8 indeed produces axis-aligned bounding boxes, which might not perfectly enclose rotated objects in the images. One way to handle this could be to preprocess your images so they're not rotated, but I understand that might not be feasible depending on your dataset.

I hope this provides some clarification. If you have any other questions, feel free to ask.

**Comment by HawkingRadiation42** [comment]
thank you for your response, in order to use yolov8 for segmentation can i just add some points to the lables file in the already 4 point labelled annotations, As i want to do rectangle shape segmentation can  i  just add the points which are already on the line of the rectangle box annotation created by the current 4 points annotations? or any other way for it, as i cant annotate the whole dataset again.

**Comment by glenn-jocher** [comment]
@HawkingRadiation42 hello,

Adding additional points on the line of the existing rectangular annotation should work, as long as there are at least three pairs of coordinates. The requirement for more than two pairs of coordinates is to avoid ambiguity in defining a polygon's shape. For example, with a three-point polygon, the model can define a triangle, while with two points, it could interpret it as a rectangle, line, or other shape.

In your case, since you have a rectangular object, you could add additional points to form a non-rectangular polygon with several points falling on the line of the rectangle. This polygon would still represent the rectangular target object, and the segmentation model should be able to work as expected.

Remember, though, that the coordinates of all points need to be labeled correctly in relation to their position on the image and need to be in the normalized format required by YOLOv8.

Please be aware that the above is a workaround and may still not provide the exact optimal results compared with having more organically created annotations. However, it can help you proceed without needing to re-annotate your entire dataset. 

If you encounter any further issues or have additional questions, please feel free to ask.

**Comment by ajanujaj** [comment]
Hi, 
Just a question to this 
I have label text in below format.

class x y x1 y1
`0 0.1296875 0.44296875 0.225 0.5421875` 

Is this correct for the image segmentation dataset ?

**Comment by glenn-jocher** [comment]
@ajanujaj hi there,

The label format you've provided is suitable for object detection tasks where objects are represented by bounding boxes. For image segmentation tasks in YOLOv8, labels must define the boundaries of objects with polygons, which requires a series of points (x,y coordinates). Each object should be labeled with at least 3 pairs of normalized coordinates to define a polygon.

For example:
`0 x1 y1 x2 y2 x3 y3 ... xn yn`

Each (x,y) pair should be normalized between [0, 1] relative to the image width and height.

Please review the [Segmentation](https://docs.ultralytics.com/tasks/segment/) documentation for detailed instructions on properly formatting your dataset for segmentation tasks.

Best wishes on your project!

**Comment by praveencloudangles** [comment]
Hi, can you provide me the yaml file structure that i need to follow for yolo v8

**Comment by glenn-jocher** [comment]
@praveencloudangles hey there! 👋

Sure, for YOLOv8, your YAML file for a custom dataset typically looks like this:

```yaml
# Training dataset
train: /path/to/train/images
val: /path/to/val/images

# Number of classes
nc: 80

# Class names
names: ['class1', 'class2', ..., 'classN']
```

Just replace `/path/to/train/images` and `/path/to/val/images` with the paths to your training and validation dataset directories, set `nc` to your number of classes, and list all your class names under `names`. 

Hope this helps! Let me know if you have more questions. 😊

**Comment by praveencloudangles** [comment]
> @praveencloudangles hey there! 👋
> 
> Sure, for YOLOv8, your YAML file for a custom dataset typically looks like this:
> 
> ```yaml
> # Training dataset
> train: /path/to/train/images
> val: /path/to/val/images
> 
> # Number of classes
> nc: 80
> 
> # Class names
> names: ['class1', 'class2', ..., 'classN']
> ```
> 
> Just replace `/path/to/train/images` and `/path/to/val/images` with the paths to your training and validation dataset directories, set `nc` to your number of classes, and list all your class names under `names`.
> 
> Hope this helps! Let me know if you have more questions. 😊
Thanks for your help..

**Comment by EnjoyingSerious** [comment]
> @HawkingRadiation42 hello, 你好，
> 
> Adding additional points on the line of the existing rectangular annotation should work, as long as there are at least three pairs of coordinates. The requirement for more than two pairs of coordinates is to avoid ambiguity in defining a polygon's shape. For example, with a three-point polygon, the model can define a triangle, while with two points, it could interpret it as a rectangle, line, or other shape.只要至少有三对坐标，就可以在现有矩形注释的线上添加其他点。要求多于两对坐标是为了避免定义多边形形状时出现歧义。例如，对于三点多边形，模型可以定义一个三角形，而对于两点，模型可以将其解释为矩形、直线或其他形状。
> 
> In your case, since you have a rectangular object, you could add additional points to form a non-rectangular polygon with several points falling on the line of the rectangle. This polygon would still represent the rectangular target object, and the segmentation model should be able to work as expected.在您的情况下，由于您有一个矩形对象，因此您可以添加其他点来形成一个非矩形多边形，其中几个点落在矩形的线上。该多边形仍代表矩形目标对象，并且分割模型应该能够按预期工作。
> 
> Remember, though, that the coordinates of all points need to be labeled correctly in relation to their position on the image and need to be in the normalized format required by YOLOv8.但请记住，所有点的坐标都需要根据它们在图像上的位置进行正确标记，并且需要采用 YOLOv8 所需的标准化格式。
> 
> Please be aware that the above is a workaround and may still not provide the exact optimal results compared with having more organically created annotations. However, it can help you proceed without needing to re-annotate your entire dataset.请注意，上述方法是一种解决方法，与更有机地创建的注释相比，可能仍然无法提供确切的最佳结果。但是，它可以帮助您继续操作，而无需重新注释整个数据集。
> 
> If you encounter any further issues or have additional questions, please feel free to ask.如果您遇到任何其他问题或有其他疑问，请随时询问。

Thank you for your answer, which solved the problem that puzzled me for a long time!
