### ISSUE TITLE
failed to export yolov11 onnx file 

### ISSUE THREAD

**Issue by zhangnju** [ultralytics/ultralytics#16848]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

run onnx export inside official docker, and met the below issue

code:
from ultralytics import YOLO

model = YOLO("yolo11n.pt")

path = model.export(format="onnx")

bug: 
Ultralytics 8.3.9 🚀 Python-3.11.6 torch-2.4.1+cpu CPU (AMD EPYC 9454 48-Core Processor)
YOLO11n summary (fused): 238 layers, 2,616,248 parameters, 0 gradients, 6.5 GFLOPs

PyTorch: starting from 'yolo11n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (5.4 MB)
Ultralytics 8.3.9 🚀 Python-3.11.6 torch-2.4.1+cpu CPU (AMD EPYC 9454 48-Core Processor)
YOLO11n summary (fused): 238 layers, 2,616,248 parameters, 0 gradients, 6.5 GFLOPs

PyTorch: starting from 'yolo11n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (5.4 MB)
ONNX: export failure ❌ 0.1s: partially initialized module 'onnx' has no attribute '__version__' (most likely due to a circular import)
ONNX: export failure ❌ 0.3s: partially initialized module 'onnx' has no attribute '__version__' (most likely due to a circular import)
Traceback (most recent call last):
  File "/ultralytics/onnx.py", line 5, in <module>
    path = model.export(format="onnx")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ultralytics/ultralytics/engine/model.py", line 734, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/ultralytics/ultralytics/engine/exporter.py", line 314, in __call__
    f[2], _ = self.export_onnx()
              ^^^^^^^^^^^^^^^^^^
  File "/ultralytics/ultralytics/engine/exporter.py", line 140, in outer_func
    raise e
  File "/ultralytics/ultralytics/engine/exporter.py", line 135, in outer_func
    f, model = inner_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ultralytics/ultralytics/engine/exporter.py", line 403, in export_onnx
    import onnx  # noqa
    ^^^^^^^^^^^
  File "/ultralytics/onnx.py", line 5, in <module>
    path = model.export(format="onnx")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ultralytics/ultralytics/engine/model.py", line 734, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/ultralytics/ultralytics/engine/exporter.py", line 314, in __call__
    f[2], _ = self.export_onnx()
              ^^^^^^^^^^^^^^^^^^
  File "/ultralytics/ultralytics/engine/exporter.py", line 140, in outer_func
    raise e
  File "/ultralytics/ultralytics/engine/exporter.py", line 135, in outer_func
    f, model = inner_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ultralytics/ultralytics/engine/exporter.py", line 406, in export_onnx
    LOGGER.info(f"\n{prefix} starting export with onnx {onnx.__version__} opset {opset_version}...")
                                                        ^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'onnx' has no attribute '__version__' (most likely due to a circular import)

### Environment

yolo checks
Ultralytics 8.3.9 🚀 Python-3.11.6 torch-2.4.1+cpu CPU (AMD EPYC 9454 48-Core Processor)
Setup complete ✅ (192 CPUs, 3023.5 GB RAM, 499.3/3519.8 GB disk)

OS                  Linux-5.15.0-117-generic-x86_64-with-glibc2.38
Environment         Linux
Python              3.11.6
Install             git
RAM                 3023.55 GB
Disk                499.3/3519.8 GB
CPU                 AMD EPYC 9454 48-Core Processor
CPU count           192
GPU                 None
GPU count           None
CUDA                None

numpy               ✅ 1.26.4>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.4.1+cpu>=1.8.0
torchvision         ✅ 0.19.1+cpu>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.9>=2.0.0
torch               ✅ 2.4.1+cpu!=2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

from ultralytics import YOLO

model = YOLO("yolo11n.pt")

path = model.export(format="onnx")

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
Try reinstalling onnx.

`pip uninstall onnx`

`pip install onnx`

**Comment by inisis** [comment]
see error here File "/ultralytics/onnx.py", line 5, in

maybe you have a local onnx.py, and it treated as a module, you just need to rename it to some name else.

**Comment by glenn-jocher** [comment]
It looks like there's a naming conflict with a local `onnx.py` file. Try renaming it to resolve the issue.

**Comment by zhangnju** [comment]
Thanks for your info. I could have a try. and I also exported onnx file successfully through yolo export command. let me close this issue

**Comment by glenn-jocher** [comment]
Great to hear you resolved it! If you have more questions, feel free to reach out.
