### ISSUE TITLE
How can I convert to tflite and make inputs image's type to uint8

### ISSUE THREAD

**Issue by fhqihgu** [ultralytics/ultralytics#16890]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I convert pt to the tflite but the inputs image is float32, how can I make it to uint8?

**Comment by UltralyticsAssistant** [comment]
👋 Hello @fhqihgu, thank you for reaching out to us at Ultralytics 🚀! 

For guidance on model conversion, especially to TFLite, we suggest checking our [Docs](https://docs.ultralytics.com) where you might find relevant tips for the conversion process. Also, verifying that you've followed appropriate steps can be helpful.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us understand and debug the issue.

For deeper technical discussions and help from the community, feel free to join the conversation over on [Discord](https://ultralytics.com/discord) 🎧, our [Discourse forum](https://community.ultralytics.com), or connect with us on our [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade

Ensure you're using the latest `ultralytics` package and dependencies in a [**Python>=3.8**](https://www.python.org/) setup with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

## Environments

You can run your model in any up-to-date environment:

- **Notebooks** with GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** VMs, [AWS](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/) AMIs, or [Docker](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/).

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

Rest assured, an Ultralytics engineer will look into your request soon and assist further.

**Comment by Y-T-G** [comment]
You can pass `int8=True` in `model.export()`.

https://docs.ultralytics.com/modes/export/#arguments
