### ISSUE TITLE
Why does this code remove the sigmoid function compared to the previous one?

### ISSUE THREAD

**Issue by jiaqizhang123-stack** [ultralytics/ultralytics#16893]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, when I test the instance segmentation with the code that removes the sigmoid function, the recognized boundaries of the object contours in the image are smoother, why is that? Thank you very much for your answer.

https://github.com/ultralytics/ultralytics/commit/b10e0f3fa8564e7a5402c544b8ae5a95aff1e491

**Comment by Y-T-G** [comment]
Is it better with `sigmoid()` or without `sigmoid()`?

**Comment by jiaqizhang123-stack** [comment]
with sigmoid() is better

**Comment by jiaqizhang123-stack** [comment]
without sigmoid() is better

**Comment by Y-T-G** [comment]
You can read https://github.com/ultralytics/ultralytics/pull/13939
