### ISSUE TITLE
Video model

### ISSUE THREAD

**Issue by timmermansjoy** [ultralytics/ultralytics#1690]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Since YOLO is used so much in videos, I was wondering if Ultralytics is ever gonna create a model that. takes advantage of multiple frames like models [here](https://paperswithcode.com/sota/video-object-detection-on-imagenet-vid) utilising the attention of transformers.

This would add some overhead, but think this would be great for fast moving images and I'm assuming pretty blurry objects

![Screenshot 2023-03-29 at 10 25 38](https://user-images.githubusercontent.com/61321383/228473306-2fc6ef4d-b34c-4c6d-9aa5-2ae3b6415e82.png)

### Use case

To have better detections when working with video

### Additional

These models exist but are not very accessible. Since Ultralytics wants to make ai accessible this seems like a very good idea

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
This is a great suggestion! Ultralytics is always looking for ways to improve their models and provide better solutions. Taking advantage of multiple frames could definitely improve object detection in videos, especially for fast-moving and blurry objects. However, this feature is not currently implemented in YOLOv8, and developing it would require significant time and resources. 

Ultralytics always welcomes contributions from the community, so if you have the skills and resources to implement this feature, you are more than welcome to submit a pull request. In the meantime, you can check out the documentation at https://docs.ultralytics.com/ for more information on how to use YOLOv8 for video object detection.
