### ISSUE TITLE
Change of units used to display speed to mph, rather than kmh?

### ISSUE THREAD

**Issue by benjaminfphillips** [ultralytics/ultralytics#16915]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Obviously I cannot just change the text because that would suggest the cars are going wayyy faster than they are. I'm likely going to save the data and make graphs etc from it to display to the local council and if the data was in MPH from the source that would be easier than me writing something to convert it after the fact.

Is there somewhere I can add a little division in to get the mph value and then change the kmh to mph text?

Appreciate any help with this as UA and machine learning etc is all pretty new to me!

**Comment by Y-T-G** [comment]
You can add the conversion here:

https://github.com/ultralytics/ultralytics/blob/15e6133534d82ec6845308f1e258d77c1b9bab36/ultralytics/solutions/speed_estimation.py#L69

**Comment by benjaminfphillips** [comment]
> You can add the conversion here:
> 
> https://github.com/ultralytics/ultralytics/blob/15e6133534d82ec6845308f1e258d77c1b9bab36/ultralytics/solutions/speed_estimation.py#L69

Hey, I ended up moding the code on line 50 to the below, and it seems to work, just need to tidy up the decimal places.

speed_label = f"{int(self.spd[track_id])/1.609} km/h" if track_id in self.spd else self.names[int(cls)]

#https://github.com/ultralytics/ultralytics/blob/15e6133534d82ec6845308f1e258d77c1b9bab36/ultralytics/solutions/speed_estimation.py#L50

**Comment by glenn-jocher** [comment]
That sounds like a practical solution. If you have any further questions or need assistance, feel free to ask.
