### ISSUE TITLE
When exporting to mlpackage (CoreML), nms should be True by default.

### ISSUE THREAD

**Issue by philipperemy** [ultralytics/ultralytics#16924]
### Search before asking

- [X] I have searched the Ultralytics [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

When we export a model to CoreML, `nms=True` should be default.

Otherwise, the model is unusable as it is.

```python
model = YOLO(weights)
model_dir = model.export(format='mlpackage', nms=True)
```

I feel like it's more intuitive to do that way.

### Use case

cf. description.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@philipperemy thank you for the suggestion. We'll consider this for future updates to improve usability. If you have more ideas, feel free to share them!
