### ISSUE TITLE
Training problems yolov8

### ISSUE THREAD

**Issue by Sylarik** [ultralytics/ultralytics#16935]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Good afternoon
I want to train the yolov8 model so that, apart from the classes it already detects, it can detect one more class.
The problem I have is that when I train yolov8n.pt with a dataset of this new class, it forgets the 80 previous classes of yolo.

Is there any way for it to preserve the knowledge about those classes?

PS: I have tried many things like reinforcement training but nothing works for me.

### Additional

[predict_video.txt](https://github.com/user-attachments/files/17378306/predict_video.txt)
[train.txt](https://github.com/user-attachments/files/17378307/train.txt)

**Comment by Y-T-G** [comment]
That's normal. You can try this. But it's not meant to be used to add classes perpetually.

https://y-t-g.github.io/tutorials/yolov8n-add-classes/

**Comment by Sylarik** [comment]
@Y-T-G  Thank you for your answer. However, I had already seen this article and it has not solved anything, any other option?

**Comment by 361754100** [comment]
亲爱的，邮件已收到，谢谢！

**Comment by Y-T-G** [comment]
No. Unless you want to download the whole COCO dataset and train on it along with your class.

**Comment by Sylarik** [comment]
okey thank you!

**Comment by Petros626** [comment]
@Sylarik can be closed?

**Comment by Sylarik** [comment]
@Petros626 what do you mean?

**Comment by Petros626** [comment]
when the issue is solved, for a better overview it should be closed or am I wrong?

**Comment by Sylarik** [comment]
I have not tested it yet, I am working on it. When I get a result I will write if it worked or not.

**Comment by glenn-jocher** [comment]
Great! Feel free to share your results or any questions you have along the way.

**Comment by Y-T-G** [comment]
@Sylarik Do what? Add a head? You can download the notebook from Colab and run it and change the dataset directories. It's going to work the same.

**Comment by Petros626** [comment]
> @Y-T-G I have managed to do it in google colab and it works, but now I need to do it in a linux machine through vs code. But I am having a lot of problems with the libraries and their versions. Does anyone have a requirement.txt?

@Sylarik you mean this?
Pip install the ultralytics package including all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [Python>=3.8](https://www.python.org/) environment with [PyTorch>=1.8](https://pytorch.org/get-started/locally/).

**Comment by Sylarik** [comment]
@Y-T-G @Petros626 finally the program works!
I would like to know if I can do it with other sizes of yolo8, like yolov8m, what should I do?

**Comment by Y-T-G** [comment]
@Sylarik I still don't know what you're referring to by "it".

**Comment by Sylarik** [comment]
@Y-T-G I mean if you can create a new model but using a bigger size of yolo, not just yolov8n as one of the heads.

**Comment by Petros626** [comment]
You want to switch the head of a bigger model to a tiny model for example? I mean the heads and it's architectures and typical for the model size.

**Comment by Y-T-G** [comment]
It's mentioned how to in the comments.

https://github.com/Y-T-G/Yasins-Keep/discussions/4#discussioncomment-9086157

**Comment by Sylarik** [comment]
@Y-T-G thank you very much! I had not seen it. Let's see if it works. ^^
