### ISSUE TITLE
How to load tensorrt yolov8l-worldv2.engine and predict images in Python?

### ISSUE THREAD

**Issue by AgentEXPL** [ultralytics/ultralytics#16934]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have already export the yolov8l-worldv2.pt to yolov8l-worldv2.engine;
I know that yolov8s-seg.engine can be loaded with `model = YOLO(cache_dir1+"/yolov8/yolov8s-seg.engine")`;
Is it possible to load yolov8l-worldv2.engine in the similar way? Please keep in mind that YOLOWorld() model can handle text prompts with `model.set_classes(text)`.

**Comment by Y-T-G** [comment]
The exported YOLOWorld model simply becomes a normal YOLO model that can be loaded using `YOLO()`. It's not possible to `set_classes` in the exported model. You can only set the classes before export, which would then become the classes used by the exported model.
