### ISSUE TITLE
How can I disable data scanning step when training yolov8?

### ISSUE THREAD

**Issue by hujunyao** [ultralytics/ultralytics#16949]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I generated image data over 2,000,000 images. It scan files for very long time.  Especially when I rerun training for test and the data is checked by first training , Is any method to disable scanning?  [ps parameter cache=false as default ]
train: Scanning /yolov8/data/test/manual ... 2270040 images, 0 backgrounds, 0 corrupt: 100%|██████████| 2270040/2270040 [1:28:06<00:00, 429.38it/s]
and I also found , when I use multi-gpu to train these data , it  failed and complained the time out for something.  I think it came from the long-time data checking?

**Comment by Y-T-G** [comment]
It will scan once and create `labels.cache` files in the `train` and `val` folder. If you run it next time, it will just use the cached labels without scanning.

**Comment by hujunyao** [comment]
> It will scan once and create `labels.cache` files in the `train` and `val` folder. If you run it next time, it will just use the cached labels without scanning.

do I need to set  cache=true when run next time?   I just rerun by nohup python3 train.py  2>&1 & ,  and every time it will scanning all the data .

**Comment by Y-T-G** [comment]
No. You don't need to set `cache=True`.

It will show as scanning, but it will finish almost immediately.
