### ISSUE TITLE
predict box left and top slight offset

### ISSUE THREAD

**Issue by HonestyBrave** [ultralytics/ultralytics#16951]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am using the latest YOLOX11 object detection model to train on a custom dataset. However, when i use the model to make predictions, i notice a strange situation: all the predicted boxes have a slight offset to the left and top of the objects. i have checked my custom dataset, but i not find label box have left and top offset. Could you give me some suggestions or help?

**Comment by Y-T-G** [comment]
Can you post examples? Does it have the same issue with YOLOv8?
