### ISSUE TITLE
How to set the parameters when exporting onnx so that the final export is onnx v7

### ISSUE THREAD

**Issue by zhoujun0715** [ultralytics/ultralytics#16959]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The same YOLOV8OBB PT weight model, setting different "opset" values cannot change the final exported "onnx" format. We tried exporting onnx with opset values equal to 10, 11, and 12, and obtained ONNX V10 format through Netron parsing. We would like to inquire about how to set parameters so that the final exported onnx format is ONNX V7?
![image](https://github.com/user-attachments/assets/b8d7a9fa-874f-42b2-a23b-414367e8589f)
![image](https://github.com/user-attachments/assets/2a2d71c3-544c-49b4-b3f3-7ae08b47e6ea)
![image](https://github.com/user-attachments/assets/907d0593-6b78-4b7c-93ee-00eba09b5a28)

**Comment by Y-T-G** [comment]
What opset does the log show while exporting?

**Comment by zhoujun0715** [comment]
![image](https://github.com/user-attachments/assets/98110355-8697-497c-a06d-6d9da79b5b3c)

**Comment by Y-T-G** [comment]
If you use opset=7, what does it show in logs?

**Comment by zhoujun0715** [comment]
![Uploading image.png…]()

**Comment by zhoujun0715** [comment]
![image](https://github.com/user-attachments/assets/94db45d2-16c1-4ea3-bf9b-1d326a2d88a1)

**Comment by zhoujun0715** [comment]
Only 10 and above can be set, and setting this value will not change the final onnx v10 result

**Comment by Y-T-G** [comment]
opset 7 is too old to work

**Comment by zhoujun0715** [comment]
opset=12, Before the YOLO11 update, all exports were onnx v7, but after the update, the export became onnx v10, and the value of this opset is not equal to the setting of onnx v7

**Comment by zhoujun0715** [comment]
![image](https://github.com/user-attachments/assets/a05703c0-63d7-4ac3-b7ae-652238ce1e23)

**Comment by zhoujun0715** [comment]
@Y-T-G @akx @plashchynski @rromanchuk

**Comment by Y-T-G** [comment]
@inisis Do you know about this?

> opset=12, Before the YOLO11 update, all exports were onnx v7, but after the update, the export became onnx v10, and the value of this opset is not equal to the setting of onnx v7

**Comment by inisis** [comment]
@zhoujun0715 Can you provide your onnx and onnxruntime version? And can you also try set simplify=False

**Comment by zhoujun0715** [comment]
![image](https://github.com/user-attachments/assets/c8d7e9b8-d71c-4e2a-90e6-10f6f881249a)

**Comment by zhoujun0715** [comment]
I just conducted the following experiment:
1. Use the latest version of ultralytics (after updating YOLO11) to export YOLOV8OBB.PT to onnx;
2. Use the old version of ultralytics (before updating YOLO11) to export onnx to YOLOV8OBB.PT;
3. Use the old version of ultralytics (before updating YOLO11) to export YOLOV11OBB.PT to onnx;
The exported code used is completely consistent, and the weights used are completely consistent;
result:
1. The results of program execution are exactly the same, both are opset 12
2. Use Netron to parse two generated onnx, with the old version being onnx v7 and the new version being onnx v10;
3. Exporting YOLO11 to the old version failed with the following error message:
![image](https://github.com/user-attachments/assets/aff91493-5452-4505-b90d-e6063a935411)
@inisis

**Comment by inisis** [comment]
opset=13
![image](https://github.com/user-attachments/assets/c4a6616a-c6c8-47f2-9d64-81417f419af8)

opset=12
![image](https://github.com/user-attachments/assets/4ab1508e-d4b5-4218-8bec-2f5fd2d758e6)

@zhoujun0715 is this what you want

**Comment by zhoujun0715** [comment]
No, the onnx format cannot be represented here. You can use it instead https://netron.app/ To analyze the onnx model you obtained, the format in its parameter table is their main difference:
![image](https://github.com/user-attachments/assets/80e9e39b-0242-42b2-bc07-1fb66f025dce)

**Comment by zhoujun0715** [comment]
The same opset=11, 12, 13, using the latest version of ultralytics to obtain onnx v10, using the old version of ultralytics to obtain onnx v7, and it is not possible to use the latest version of ultralytics to obtain onnx v7;

**Comment by zhoujun0715** [comment]
When deploying in C++, it was found that some onnx parsers were able to parse onnx v7, but would fail to parse onnx v10, which would result in the inability to use the new model in previous projects and serious format compatibility issues;

**Comment by inisis** [comment]
@zhoujun0715 you can try pip install onnx==1.12 onnxruntime==1.12

**Comment by zhoujun0715** [comment]
尝试过了。这个方法是不行的，你可以在你的环境中进行尝试，然后去使用“netron”去解析

**Comment by zhoujun0715** [comment]
Have you ever tried exporting onnx files for onnx v7 using the latest factory library

**Comment by inisis** [comment]
this is what I got
![image](https://github.com/user-attachments/assets/faead450-1ba2-4afa-a4e6-e7a26796a8dd)

**Comment by zhoujun0715** [comment]
Can you show me your environment? Installation failed on my end

![image](https://github.com/user-attachments/assets/69bda2d6-6dd6-426c-b0e3-2f2d961c466c)

**Comment by inisis** [comment]
> Can you show me your environment? Installation failed on my end
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/69bda2d6-6dd6-426c-b0e3-2f2d961c466c)
> 
> 
> 
> 

I will fix it soon！

**Comment by inisis** [comment]
@zhoujun0715 @Y-T-G The root cause is that onnxslim will discard raw ir_version to align with your currrently used onnx, and I think this is expected, if you want to change the ir version, you can use the following code.

```
import onnx

model_path = 'your_model.onnx'
model = onnx.load(model_path)
print(f"Current IR version: {model.ir_version}")

new_ir_version = 7
model.ir_version = new_ir_version

updated_model_path = 'updated_model.onnx'
onnx.save(model, updated_model_path)

print(f"IR version updated to: {new_ir_version}")
```

**Comment by glenn-jocher** [comment]
@zhoujun0715 please ensure you're using the latest versions of ONNX and ONNX Runtime. If the issue persists, consider checking compatibility with your deployment environment or consult the [ONNX documentation](https://docs.ultralytics.com/integrations/onnx/) for further guidance.

**Comment by zhoujun0715** [comment]
After conversion, the problem was perfectly solved. Thank you very much, the work was done very well!

**Comment by glenn-jocher** [comment]
Please ensure you're using compatible versions of ONNX and ONNX Runtime. If the issue persists, consider checking the Netron analysis for further insights.

**Comment by glenn-jocher** [comment]
I recommend checking the ONNX and onnxruntime versions and ensuring compatibility. If issues persist, consider using an older version of Ultralytics that worked for you. For further assistance, please visit our [ONNX documentation](https://docs.ultralytics.com/integrations/onnx/).

**Comment by glenn-jocher** [comment]
@zhoujun0715 it seems like the issue persists. I recommend checking the compatibility of your ONNX and ONNX Runtime versions, and ensure you're using the correct opset version. If the problem continues, consider reaching out to the ONNX community for further assistance.
