### ISSUE TITLE
YOLOV11 inference, with the save_drop = true, where can I set the save image format? I want to save in PNG format. The second question is about the results of YOLOV11 detection. boxes The boxes  do not have categories, how do we know which box belongs to which category?

### ISSUE THREAD

**Issue by litengfeigithub** [ultralytics/ultralytics#16952]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

YOLOV11 inference, with the save_drop = true, where can I set the save image format? I want to save in PNG format. The second question is about the results of YOLOV11 detection. boxes The boxes  do not have categories, how do we know which box belongs to which category?
![1](https://github.com/user-attachments/assets/af382b01-70af-4172-bb02-c690b556e61c)
![2](https://github.com/user-attachments/assets/d09b4d32-ed69-4aaa-809b-efbda563fa8e)

**Comment by litengfeigithub** [comment]
The second issue has been resolved

**Comment by Y-T-G** [comment]
You can save it manually by cropping it yourself.

https://docs.ultralytics.com/modes/predict/#working-with-results

**Comment by Y-T-G** [comment]
You can find the class of the boxes in `result.boxes.cls`. The order is the same as `result.boxes.xyxy`.
