### ISSUE TITLE
A strange question.

### ISSUE THREAD

**Issue by jiance1** [ultralytics/ultralytics#16977]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

 Why has the number of parameters for the same yolov8n decreased from version to version with the update of ultralystics, I remember that the computation was still 8.2GFLOPS in the previous v8 version How come it is now 6.9?

**Comment by glenn-jocher** [comment]
@jiance1 the reduction in parameters and GFLOPS for YOLOv8n is due to optimizations and improvements in the model architecture, enhancing efficiency without compromising performance. For more details, you can check the release notes or documentation updates.
