### ISSUE TITLE
Questions about box coordinates in yolov10 when using attempt_load_weights

### ISSUE THREAD

**Issue by JeanPhilippeMonteuuis** [ultralytics/ultralytics#16972]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, 

I was trying to figure out: how are defined the box coordinates of a yolov10 output when using `attempt_load_weights()`?

```
import torch

from PIL import Image
from torchvision import transforms
from ultralytics.nn.tasks import attempt_load_weights

DEVICE = torch.device("cuda")
MODEL_PATH = "yolov10s.pt"
IMAGE_PATH = "zidane.jpg"

transform = transforms.Compose(
    [
        transforms.Resize((640, 640), interpolation=Image.BICUBIC),
        transforms.ToTensor(),
    ]
)

model = attempt_load_weights(f"{MODEL_PATH}", DEVICE).eval()


PIL_img = Image.open(IMAGE_PATH).convert("RGB")
tensor_img = transform(PIL_img)
results = model(tensor_img.unsqueeze(0).to(DEVICE))
```
When running the code below, on the original zidane image (resized at 640x640), I get `results`. When looking at 'results[0]', it is a structure of the size [1:300:6]. looking at the box coordinates values (e.g., `results[0][:,:,1]`), I can see some values are above 640.

Can someone explain me why? 
Thank you

**Comment by Y-T-G** [comment]
If it's slightly higher than 640, then that's normal.

**Comment by JeanPhilippeMonteuuis** [comment]
Thank you for reassuring me on the normal behavior. However, I would like to understand why some values are above 640 in this precise case?

**Comment by glenn-jocher** [comment]
@JeanPhilippeMonteuuis the values can exceed 640 due to the model's predictions being in the original image scale, which might not perfectly align with the resized dimensions. For more details, you can refer to the YOLO documentation on bounding box scaling.
