### ISSUE TITLE
How to use ReID Bot-tracker

### ISSUE THREAD

**Issue by soseji01** [ultralytics/ultralytics#16982]
### Search before asking

- [ ] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, as part of a school project, I am developing an object tracking system. I am using YOLO.track() with the default tracker, BOT SORT. Is it correct that the REID feature is not yet supported by default?I was looking for a way to re-identify disappeared objects, and I came across an example code: BOTrack(tlwh, score, cls, feat=None, feat_history=50). I would like to use this, but how can I integrate it with the existing yolo.track(). Could you explain how to use this??

**Comment by rioisme** [comment]
@glenn-jocher Thank you for your work. When will the ReID capability be enabled in BOTrack?
