### ISSUE TITLE
How to tune yolov11cls hyperparameter with object function defined as the combination of accuracy and f1 score?

### ISSUE THREAD

**Issue by AnikiFan** [ultralytics/ultralytics#16989]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, the newly released yolov11cls is such a powerful classifier that I'm using it in my classification competition, where competitor's score is calculated as 0.6*accuracy + 0.4*f1 score. Therefore, I want to tune yolov11cls model's hyperparameter with 0.6*accuracy + 0.4*f1 score as object function. By searching the document, I've learned that I can define my own custom fitness function with P, R, mAP@0.5, mAP@0.5:0.95. However, I couldn't figure out how to use them to construct my object function. By the way, I also have no idea what to do after defining fitness function. orz

**Comment by Y-T-G** [comment]
Fitness for classification doesn't use F1-score. F1-score isn't calculated for classification.

https://github.com/ultralytics/ultralytics/blob/22ebd44f62791cfd4de2a24de15ce05a13c1447a/ultralytics/utils/metrics.py#L1200
