### ISSUE TITLE
Is it possible to train a yolo-seg model directly using mask images?

### ISSUE THREAD

**Issue by e8-ChenLe** [ultralytics/ultralytics#16987]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My goal is to train the model to divide the area with a ring, but it seems that the ring area cannot be marked by contour points.
The ring area can be represented directly by mask, but the data format of yolo-seg model does not support the input of mask image training. What should I do, please give me some help.Thank you in advance.

**Comment by glenn-jocher** [comment]
@e8-ChenLe to train a YOLO-seg model with mask images, you'll need to convert your masks into the format YOLO-seg supports, typically using annotations with bounding boxes and segmentation masks. For detailed guidance, please refer to our documentation on isolating segmentation objects: https://docs.ultralytics.com/guides/isolating-segmentation-objects/.

**Comment by Y-T-G** [comment]
You will have to edit this part so that it directly loads the masks instead of converting segment to polygon. You will also need to resize the mask to the required size. It should be of shape (N, H, W) where N is the number of classes. And then train with `mask_overlap=False`

https://github.com/ultralytics/ultralytics/blob/22ebd44f62791cfd4de2a24de15ce05a13c1447a/ultralytics/data/augment.py#L2131

**Comment by e8-ChenLe** [comment]
@glenn-jocher Thanks for the advice.Sorry I didn't describe it well, I need the YOLO-seg model to segment the ring region, as described in this [question](https://github.com/ultralytics/ultralytics/issues/12730#issue-2300369208).The ring region needs two polygon arcs to represent it, I found they can't form a closed region, and can't use `polygons2masks `to get a mask. so I wondered if I could train the YOLO-seg model directly using the mask annotation.How do I change the code to implement this idea？

**Comment by e8-ChenLe** [comment]
@Y-T-G Thanks for the reply, if I modify `polygons2masks` to load the mask directly, I still need to generate the `bbox ` through the mask right? Does the process of loading the labels need to be modified as well?

**Comment by Y-T-G** [comment]
Yes, you will have to change that too. There's a mask2boxes function in `ultralytics` which you can use
