### ISSUE TITLE
How to perform incremental learning with YOLOV8 model 

### ISSUE THREAD

**Issue by SubhadipMaji** [ultralytics/ultralytics#16980]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained a yolov8 model with 2078 images successfully. I want to add a feature of incremental learning in the model for future if new classes are coming . But the constraint is I can not use the previously trained dataset or store the previous data to retrain it , I have to train the model only with the new class data and the old weights . How to implement it with the existing weights while the model accuracies will not effect and also want a technique for auto annotation for the new images in offline mode . can you help me with it ?

**Comment by Y-T-G** [comment]
It's not possible. The model will lose the old performance.

**Comment by SubhadipMaji** [comment]
> It's not possible. The model will lose the old performance.

can you suggest a better way to make a incremental model with yolov8

**Comment by Y-T-G** [comment]
You can't without the old dataset.
