### ISSUE TITLE
How to export dynamic batch size onnx?

### ISSUE THREAD

**Issue by xfchangwei** [ultralytics/ultralytics#16999]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to export dynamic batch size onnx, [-1,3,640,640]? My batch inference is not fixed each time, sometimes 3 sheets, sometimes 5 sheets.

**Comment by xfchangwei** [comment]
batch=-1, report errors

**Comment by Y-T-G** [comment]
Use `dynamic=True`.

https://docs.ultralytics.com/modes/export/
