### ISSUE TITLE
Process is being killed after transferring weights from pretrained model

### ISSUE THREAD

**Issue by prichinatryaski** [ultralytics/ultralytics#17006]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

![image](https://github.com/user-attachments/assets/9b7fdc51-e04f-446a-9656-ddeb285f162e)
After an attempt to run train on any dataset, the process is being killed

### Environment

Ultralytics 8.3.15 🚀 Python-3.11.2 torch-2.5.0+cu124 CUDA:0 (GRID A100D-80C, 81916MiB)
Setup complete ✅ (30 CPUs, 1.2 GB RAM, 40.2/489.6 GB disk)

OS                  Linux-6.1.0-26-amd64-x86_64-with-glibc2.36
Environment         Linux
Python              3.11.2
Install             pip
RAM                 1.24 GB
Disk                40.2/489.6 GB
CPU                 Intel Xeon Gold 6336Y 2.40GHz
CPU count           30
GPU                 GRID A100D-80C, 81916MiB
GPU count           1
CUDA                12.4

numpy               ✅ 2.1.2>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 11.0.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.5.0>=1.8.0
torchvision         ✅ 0.20.0>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.1.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.9>=2.0.0
torch               ✅ 2.5.0!=2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

yolo detect train data=coco8.yaml model=yolo11n.pt epochs=10 imgsz=640

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
You don't have enough RAM.

**Comment by prichinatryaski** [comment]
> > RAM 1.24 GB
> 
> You don't have enough RAM.

I have 40 gbs allocated

**Comment by Y-T-G** [comment]
It's only seeing 1.24GB.

**Comment by glenn-jocher** [comment]
Glad you found the issue. If you need further assistance, feel free to ask!
