### ISSUE TITLE
Yolo-pose output

### ISSUE THREAD

**Issue by rabum** [ultralytics/ultralytics#17008]
I see those occluded keypoints are set to [0,0], is it a postprocess? If so can I get their original xy the model predicted?
![image](https://github.com/user-attachments/assets/ce7cd36b-e27c-48d0-8804-4e6dda5a69a4)

**Comment by Y-T-G** [comment]
You will have to update the code.

https://github.com/ultralytics/ultralytics/blob/ea326c0a4fd0f7dca46e317ef29cd2b8172dca88/ultralytics/engine/results.py#L1309-L1310
