### ISSUE TITLE
how to edit default cfg augmentation settings while training ? 

### ISSUE THREAD

**Issue by aaiguy** [ultralytics/ultralytics#1700]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm trying to do some more augmentation on training data  like rotation by passing cfg default.yaml flie   as below 
```
`# Ultralytics YOLO 🚀, GPL-3.0 license
# Default training settings and hyperparameters for medium-augmentation COCO training

task: detect  # inference task, i.e. detect, segment, classify
mode: train  # YOLO mode, i.e. train, val, predict, export

# Train settings -------------------------------------------------------------------------------------------------------
model:  # path to model file, i.e. yolov8n.pt, yolov8n.yaml
data: data.yaml # path to data file, i.e. i.e. coco128.yaml
epochs: 100000  # number of epochs to train for
patience: 50  # epochs to wait for no observable improvement for early stopping of training
batch: 16  # number of images per batch (-1 for AutoBatch)
imgsz: 786 # s786ize of input images as integer or w,h
save: True  # save train checkpoints and predict results
save_period: 50 # Save checkpoint every x epochs (disabled if < 1)
cache: False  # True/ram, disk or False. Use cache for data loading
device:  # device to run on, i.e. cuda device=0 or device=0,1,2,3 or device=cpu
workers: 8  # number of worker threads for data loading (per RANK if DDP)
project:  # project name
name:  # experiment name
exist_ok: False  # whether to overwrite existing experiment
pretrained: False  # whether to use a pretrained model
optimizer: SGD  # optimizer to use, choices=['SGD', 'Adam', 'AdamW', 'RMSProp']
verbose: True  # whether to print verbose output
seed: 0  # random seed for reproducibility
deterministic: True  # whether to enable deterministic mode
single_cls: False  # train multi-class data as single-class
image_weights: False  # use weighted image selection for training
rect: False  # support rectangular training if mode='train', support rectangular evaluation if mode='val'
cos_lr: False  # use cosine learning rate scheduler
close_mosaic: 10  # disable mosaic augmentation for final 10 epochs
resume: False  # resume training from last checkpoint
min_memory: False  # minimize memory footprint loss function, choices=[False, True, <roll_out_thr>]
# Segmentation
overlap_mask: True  # masks should overlap during training (segment train only)
mask_ratio: 4  # mask downsample ratio (segment train only)
# Classification
dropout: 0.0  # use dropout regularization (classify train only)

# Val/Test settings ----------------------------------------------------------------------------------------------------
val: True  # validate/test during training
split: val  # dataset split to use for validation, i.e. 'val', 'test' or 'train'
save_json: False  # save results to JSON file
save_hybrid: False  # save hybrid version of labels (labels + additional predictions)
conf:  # object confidence threshold for detection (default 0.25 predict, 0.001 val)
iou: 0.7  # intersection over union (IoU) threshold for NMS
max_det: 300  # maximum number of detections per image
half: False  # use half precision (FP16)
dnn: False  # use OpenCV DNN for ONNX inference
plots: True  # save plots during train/val

# Prediction settings --------------------------------------------------------------------------------------------------
source:  # source directory for images or videos
show: False  # show results if possible
save_txt: False  # save results as .txt file
save_conf: False  # save results with confidence scores
save_crop: False  # save cropped images with results
hide_labels: False  # hide labels
hide_conf: False  # hide confidence scores
vid_stride: 1  # video frame-rate stride
line_thickness: 3  # bounding box thickness (pixels)
visualize: False  # visualize model features
augment: False  # apply image augmentation to prediction sources
agnostic_nms: False  # class-agnostic NMS
classes:  # filter results by class, i.e. class=0, or class=[0,2,3]
retina_masks: False  # use high-resolution segmentation masks
boxes: True  # Show boxes in segmentation predictions

# Export settings ------------------------------------------------------------------------------------------------------
format: torchscript  # format to export to
keras: False  # use Keras
optimize: False  # TorchScript: optimize for mobile
int8: False  # CoreML/TF INT8 quantization
dynamic: False  # ONNX/TF/TensorRT: dynamic axes
simplify: False  # ONNX: simplify model
opset:  # ONNX: opset version (optional)
workspace: 4  # TensorRT: workspace size (GB)
nms: False  # CoreML: add NMS

# Hyperparameters ------------------------------------------------------------------------------------------------------
lr0: 0.01  # initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
lrf: 0.01  # final learning rate (lr0 * lrf)
momentum: 0.937  # SGD momentum/Adam beta1
weight_decay: 0.0005  # optimizer weight decay 5e-4
warmup_epochs: 3.0  # warmup epochs (fractions ok)
warmup_momentum: 0.8  # warmup initial momentum
warmup_bias_lr: 0.1  # warmup initial bias lr
box: 7.5  # box loss gain
cls: 0.5  # cls loss gain (scale with pixels)
dfl: 1.5  # dfl loss gain
fl_gamma: 0.0  # focal loss gamma (efficientDet default gamma=1.5)
label_smoothing: 0.0  # label smoothing (fraction)
nbs: 64  # nominal batch size
hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # image HSV-Value augmentation (fraction)
degrees: 180  # image rotation (+/- deg)
translate: 0.1  # image translation (+/- fraction)
scale: 0.5  # image scale (+/- gain)
shear: 0.0  # image shear (+/- deg)
perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
flipud: 0.0  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)
mosaic: 1.0  # image mosaic (probability)
mixup: 0.0  # image mixup (probability)
copy_paste: 0.0  # segment copy-paste (probability)

# Custom config.yaml ---------------------------------------------------------------------------------------------------
cfg:  # for overriding defaults.yaml

# Debug, do not modify -------------------------------------------------------------------------------------------------
v5loader: False  # use legacy YOLOv5 dataloader

# Tracker settings ------------------------------------------------------------------------------------------------------
tracker: botsort.yaml  # tracker type, ['botsort.yaml', 'bytetrack.yaml']`
```

when i try to give train with this as cfg default.yaml life as below 

```
from ultralytics.yolo.engine.model import YOLO
def main():
    # Instantiate YOLO model
    model = YOLO()
    model.train(cfg='default.yaml')
if __name__ == "__main__":
    main()
```

I get error as below 

> cfg file passed. Overriding default params with default.yaml.

> Traceback (most recent call last):
>   File "C:\Data\AI\XIPA\OD\YOLO_Impementation\train.py", line 18, in <module>
>     main()
>   File "C:\Data\AI\XIPA\OD\YOLO_Impementation\train.py", line 10, in main
>     model.train(cfg='default.yaml')
>   File "C:\Users\NLRH1411\Anaconda3\envs\invokeai\lib\site-packages\ultralytics-8.0.42-py3.9.egg\ultralytics\yolo\engine\model.py", line 279, in train
>     self.trainer = self.TrainerClass(overrides=overrides)
>   File "C:\Users\NLRH1411\Anaconda3\envs\invokeai\lib\site-packages\ultralytics-8.0.42-py3.9.egg\ultralytics\yolo\engine\trainer.py", line 84, in __init__
>     self.args = get_cfg(cfg, overrides)
>   File "C:\Users\NLRH1411\Anaconda3\envs\invokeai\lib\site-packages\ultralytics-8.0.42-py3.9.egg\ultralytics\yolo\cfg\__init__.py", line 98, in get_cfg
>     check_cfg_mismatch(cfg, overrides)
>   File "C:\Users\NLRH1411\Anaconda3\envs\invokeai\lib\site-packages\ultralytics-8.0.42-py3.9.egg\ultralytics\yolo\cfg\__init__.py", line 148, in check_cfg_mismatch
>     raise SyntaxError(string + CLI_HELP_MSG) from e
> SyntaxError: 'yaml_file' is not a valid YOLO argument.
> 
>     Arguments received: ['yolo']. Note that Ultralytics 'yolo' commands use the following syntax:
> 
>         yolo TASK MODE ARGS
> 
>         Where   TASK (optional) is one of [detect, segment, classify]
>                 MODE (required) is one of [train, val, predict, export]
>                 ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
>                     See all ARGS at https://docs.ultralytics.com/cfg or with 'yolo cfg'
> 
>     1. Train a detection model for 10 epochs with an initial learning_rate of 0.01
>         yolo train data=coco128.yaml model=yolov8n.pt epochs=10 lr0=0.01
> 
>     2. Predict a YouTube video using a pretrained segmentation model at image size 320:
>         yolo predict model=yolov8n-seg.pt source='https://youtu.be/Zgi9g1ksQHc' imgsz=320
> 
>     3. Val a pretrained detection model at batch-size 1 and image size 640:
>         yolo val model=yolov8n.pt data=coco128.yaml batch=1 imgsz=640
> 
>     4. Export a YOLOv8n classification model to ONNX format at image size 224 by 128 (no TASK required)
>         yolo export model=yolov8n-cls.pt format=onnx imgsz=224,128
> 
>     5. Run special commands:
>         yolo help
>         yolo checks
>         yolo version
>         yolo settings
>         yolo copy-cfg
>         yolo cfg
> 
>     Docs: https://docs.ultralytics.com/cli
>     Community: https://community.ultralytics.com
>     GitHub: https://github.com/ultralytics/ultralytics

Why am  i getting this error ? how to train properly ?

**Comment by glenn-jocher** [comment]
@aaiguy this might occur because you are using an out-of-date version of ultralytics. Is this happening if you update to the latest version of the package, 8.0.58? You can use this command to update:

```
pip install -U ultralytics
```

**Comment by glenn-jocher** [comment]
@aaiguy @aaiguy It looks like you are trying to call train() method with an argument 'cfg' that is not recognized. Instead of using 'cfg', follow the YOLO syntax and specify the 'TASK MODE ARGS' such as:

```
yolo detect train data=coco128.yaml cfg=default.yaml
```

In this example, 'detect' is the task, 'train' is the mode, and 'data=coco128.yaml' and 'cfg=default.yaml' are the arguments. 

Alternatively, if you want to use train method() with a dict object, you can pass configurations as a dictionary object like below:

```
from ultralytics.yolo.engine.model import YOLO
config = {'data': 'coco128.yaml', 'cfg': 'default.yaml'}
def main():
    # Instantiate YOLO model
    model = YOLO()
    model.train(**config)
if __name__ == "__main__":
    main()
```

I hope this helps!

**Comment by aaiguy** [comment]
THanks, this worked for me.

**Comment by glenn-jocher** [comment]
@aaiguy you're welcome! Don't hesitate to ask if you have any more questions in the future.

**Comment by aaiguy** [comment]
I have one more question related to augmentation, i did rotation augmentation , mentioning 45 as degree, when I see batch image i see only augmented rotation images, is it possible to train model on both normal image and rotation augmented image ? what changes I need to modify in default.yaml ?

**Comment by glenn-jocher** [comment]
@aaiguy yes, you can train your model on both normal images and rotation-augmented images (or any other type of augmentation). 

In `default.yaml`, the relevant parameter to modify is `degrees`, which controls the maximum amount of degrees of rotation applied during the augmentation. By default, it is set to 180, meaning that the images can be rotated by up to 180 degrees. If you only want to rotate your images some of the time, change `degrees` to a smaller value, such as:

```
degrees: 45  # Maximum rotation degrees
```

This will limit the rotation to at most 45 degrees. 

Then, to enable both normal and augmented images, you can set `mosaic` to a value between 0 and 1, which controls the probability that the image will be augmented with mosaic augmentation, which combines multiple images into one. When mosaic is 0, only the original images will be used; when mosaic is 1, only mosaic images will be used; and when mosaic is between 0 and 1, the model will use a mix of original and augmented images. For example:

```
mosaic: 0.5  # Probability of using mosaic augmentation. If 0, only original images are used; if 1, only augmented images are used.
```

I hope this helps!

**Comment by aaiguy** [comment]
I gave training with below config settings 

> `# Ultralytics YOLO 🚀, GPL-3.0 license
> # Default training settings and hyperparameters for medium-augmentation COCO training
> 
> task: detect  # inference task, i.e. detect, segment, classify
> mode: train  # YOLO mode, i.e. train, val, predict, export
> 
> # Train settings -------------------------------------------------------------------------------------------------------
> model:  # path to model file, i.e. yolov8n.pt, yolov8n.yaml
> data: data.yaml  # path to data file, i.e. coco128.yaml
> epochs: 100000  # number of epochs to train for
> patience: 50  # epochs to wait for no observable improvement for early stopping of training
> batch: 8  # number of images per batch (-1 for AutoBatch)
> imgsz: 786  # size of input images as integer or w,h
> save: True  # save train checkpoints and predict results
> save_period: 20 # Save checkpoint every x epochs (disabled if < 1)
> cache: False  # True/ram, disk or False. Use cache for data loading
> device:  # device to run on, i.e. cuda device=0 or device=0,1,2,3 or device=cpu
> workers: 8  # number of worker threads for data loading (per RANK if DDP)
> project:  # project name
> name:  # experiment name, results saved to 'project/name' directory
> exist_ok: False  # whether to overwrite existing experiment
> pretrained: False  # whether to use a pretrained model
> optimizer: SGD  # optimizer to use, choices=['SGD', 'Adam', 'AdamW', 'RMSProp']
> verbose: True  # whether to print verbose output
> seed: 0  # random seed for reproducibility
> deterministic: True  # whether to enable deterministic mode
> single_cls: False  # train multi-class data as single-class
> image_weights: False  # use weighted image selection for training
> rect: False  # support rectangular training if mode='train', support rectangular evaluation if mode='val'
> cos_lr: False  # use cosine learning rate scheduler
> close_mosaic: 10  # disable mosaic augmentation for final 10 epochs
> resume: False  # resume training from last checkpoint
> # Segmentation
> overlap_mask: True  # masks should overlap during training (segment train only)
> mask_ratio: 4  # mask downsample ratio (segment train only)
> # Classification
> dropout: 0.0  # use dropout regularization (classify train only)
> 
> # Val/Test settings ----------------------------------------------------------------------------------------------------
> val: True  # validate/test during training
> split: val  # dataset split to use for validation, i.e. 'val', 'test' or 'train'
> save_json: False  # save results to JSON file
> save_hybrid: False  # save hybrid version of labels (labels + additional predictions)
> conf:  # object confidence threshold for detection (default 0.25 predict, 0.001 val)
> iou: 0.7  # intersection over union (IoU) threshold for NMS
> max_det: 300  # maximum number of detections per image
> half: False  # use half precision (FP16)
> dnn: False  # use OpenCV DNN for ONNX inference
> plots: True  # save plots during train/val
> 
> # Prediction settings --------------------------------------------------------------------------------------------------
> source:  # source directory for images or videos
> show: False  # show results if possible
> save_txt: False  # save results as .txt file
> save_conf: False  # save results with confidence scores
> save_crop: False  # save cropped images with results
> hide_labels: False  # hide labels
> hide_conf: False  # hide confidence scores
> vid_stride: 1  # video frame-rate stride
> line_thickness: 3  # bounding box thickness (pixels)
> visualize: False  # visualize model features
> augment: False  # apply image augmentation to prediction sources
> agnostic_nms: False  # class-agnostic NMS
> classes:  # filter results by class, i.e. class=0, or class=[0,2,3]
> retina_masks: False  # use high-resolution segmentation masks
> boxes: True  # Show boxes in segmentation predictions
> 
> # Export settings ------------------------------------------------------------------------------------------------------
> format: torchscript  # format to export to
> keras: False  # use Keras
> optimize: False  # TorchScript: optimize for mobile
> int8: False  # CoreML/TF INT8 quantization
> dynamic: False  # ONNX/TF/TensorRT: dynamic axes
> simplify: False  # ONNX: simplify model
> opset:  # ONNX: opset version (optional)
> workspace: 4  # TensorRT: workspace size (GB)
> nms: False  # CoreML: add NMS
> 
> # Hyperparameters ------------------------------------------------------------------------------------------------------
> lr0: 0.01  # initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
> lrf: 0.01  # final learning rate (lr0 * lrf)
> momentum: 0.937  # SGD momentum/Adam beta1
> weight_decay: 0.0005  # optimizer weight decay 5e-4
> warmup_epochs: 3.0  # warmup epochs (fractions ok)
> warmup_momentum: 0.8  # warmup initial momentum
> warmup_bias_lr: 0.1  # warmup initial bias lr
> box: 7.5  # box loss gain
> cls: 0.5  # cls loss gain (scale with pixels)
> dfl: 1.5  # dfl loss gain
> fl_gamma: 0.0  # focal loss gamma (efficientDet default gamma=1.5)
> label_smoothing: 0.0  # label smoothing (fraction)
> nbs: 64  # nominal batch size
> hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
> hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
> hsv_v: 0.4  # image HSV-Value augmentation (fraction)
> degrees: 45  # image rotation (+/- deg)
> translate: 0.1  # image translation (+/- fraction)
> scale: 0.5  # image scale (+/- gain)
> shear: 0.0  # image shear (+/- deg)
> perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
> flipud: 0.5 # image flip up-down (probability)
> fliplr: 0.5  # image flip left-right (probability)
> mosaic: 0.5  # image mosaic (probability)
> mixup: 0  # image mixup (probability)
> copy_paste: 0.5  # segment copy-paste (probability)
> 
> # Custom config.yaml ---------------------------------------------------------------------------------------------------
> cfg:  # for overriding defaults.yaml
> 
> # Debug, do not modify -------------------------------------------------------------------------------------------------
> v5loader: False  # use legacy YOLOv5 dataloader
> 
> # Tracker settings ------------------------------------------------------------------------------------------------------
> tracker: botsort.yaml  # tracker type, ['botsort.yaml', 'bytetrack.yaml']`
> 


If i check training log tail it takes lot of time for validation epoch than training epochs, training epochs completes in few 2 seconds but validation epochs taking around 3min as shown below 

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
   2/100000      9.51G      2.932      7.785      2.232         36        800: 100%|██████████| 4/4 [00:03<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [02:45<00:00, 82.50s/it]
                   all         29        136          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
   3/100000        10G      2.997      7.916      2.277         39        800: 100%|██████████| 4/4 [00:03<00:00,  1.14it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [02:41<00:00, 80.91s/it]
                   all         29        136          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
   4/100000        10G      3.025      7.769      2.271         42        800: 100%|██████████| 4/4 [00:03<00:00,  1.16it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [02:44<00:00, 82.02s/it]
                   all         29        136          0          0          0          0



I've only around 60 images in training data, earlier when i used to train with default config training used to happen quickly both in training and validation epochs, how can I fix this?

**Comment by glenn-jocher** [comment]
@Elec4d0 to train using Python, ensure your `config` dictionary includes valid YOLO arguments. Replace `'cfg': 'nohsvo.yaml'` with specific parameters from your YAML file. For detailed guidance, refer to the [Ultralytics documentation](https://docs.ultralytics.com/usage/cfg/).
