### ISSUE TITLE
Why can't yolo11 achieve additional benefits at 1280 resolution?

### ISSUE THREAD

**Issue by tms2003** [ultralytics/ultralytics#17007]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I trained yolov8 1280 and yolo11 1280 at the same time, and found that the results of yolo11 1280 are basically equivalent to 640 (except that the training is slower and occupies more video memory), but yolov8 1280 will achieve better results than 640. What is the reason?

**Comment by Y-T-G** [comment]
Do you have the results?

**Comment by Skillnoob** [comment]
Are your training images at least 1280x1280? If they aren't, it will need to upscale the images which will give you no benefit.

**Comment by tms2003** [comment]
@Skillnoob 
> Are your training images at least 1280x1280? If they aren't, it will need to upscale the images which will give you no benefit.

of course,I trained my model like this:
yolo detect train data=data/coco11.yaml model=yolo11l.pt imgsz=1280 batch=16 patience=0 augment=true patience=0 device=0,1,2,3 workers=32 epochs = 300

**Comment by Skillnoob** [comment]
Can you share the results like @Y-T-G asked for.

**Comment by dantetemplar** [comment]
I note same behavior on task of detecting people on image from UAV (4k resolution). That's very strange. And also I lost 4 gpu days to train yolo11 with imgsz=1280px.

**Comment by glenn-jocher** [comment]
Thank you for sharing your experience. The lack of improvement at higher resolutions could be due to diminishing returns on larger image sizes or the model's architecture not fully leveraging the additional detail. You might consider experimenting with different augmentations or hyperparameters to see if they yield better results.

**Comment by dantetemplar** [comment]
@tms2003 did you find the real reason?

**Comment by Y-T-G** [comment]
Probably because it uses attention, so it has better receptive field even without large image size.

**Comment by MasIgor** [comment]
is there a maximum image size that can be used? for example would a 4096x4096 image be possible and bring some benefit in finding small objects on a big image?

**Comment by Skillnoob** [comment]
@MasIgor for those kinds of images I would reccomend [SAHI](https://docs.ultralytics.com/guides/sahi-tiled-inference/) and training with a lower imgsz like 640 or 1280, because training with a imgsz of 4000+ would take too long.

**Comment by dantetemplar** [comment]
> [@MasIgor](https://github.com/MasIgor) for those kinds of images I would reccomend [SAHI](https://docs.ultralytics.com/guides/sahi-tiled-inference/) and training with a lower imgsz like 640 or 1280, because training with a imgsz of 4000+ would take too long.

I would recommend to implement SAHI by hand because they have shitty code, same as in XXX.

**Comment by glenn-jocher** [comment]
Thank you for your feedback. While SAHI's implementation has proven effective for many users in our community ([citation](https://arxiv.org/abs/2202.06934)), we welcome contributions to improve integration. For custom implementations, our AGPL-3.0 license allows modifications when adhering to license terms.
