### ISSUE TITLE
Wrong bounding box in example YOLOv8 int8 tflite

### ISSUE THREAD

**Issue by hieuhhongdmprof** [ultralytics/ultralytics#17003]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Other

### Bug

When I run the tflite yolov8 using the following code, the bounding box is wrong. It's still correct a few days ago.
https://github.com/ultralytics/ultralytics/blob/main/examples/YOLOv8-OpenCV-int8-tflite-Python

![Output_screenshot_18 10 2024](https://github.com/user-attachments/assets/5ee17897-bc46-48f6-971f-bc061d598d86)

I realize the following source code was override the variables which store the size of model input.
https://github.com/ultralytics/ultralytics/commit/533774290c06f7d5750ccf4c9d8fc2778b4df85a#diff-1448dd3c06a52afef13e2663c9e51cac0da548614e8aec102b5444c64e6e0ca8R211 

### Environment

Ultralytics YOLOv8.2.79 🚀 Python-3.10.12 torch-2.3.1+cu118 CUDA:0 (NVIDIA GeForce GTX 1050, 4039MiB)
Setup complete ✅ (12 CPUs, 15.5 GB RAM, 380.2/456.9 GB disk)

OS                  Linux-6.8.0-47-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 15.49 GB
CPU                 Intel Core(TM) i7-8750H 2.20GHz
CUDA                11.8

numpy               ✅ 1.23.5<2.0.0,>=1.23.0
matplotlib          ✅ 3.5.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.25.1>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.3.1+cu118>=1.8.0
torchvision         ✅ 0.18.1+cu118>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.5>=2.0.0

### Minimal Reproducible Example

``` python
python yolov8_tflite_quant_int.py --model yolov8s_saved_model/yolov8s_full_integer_quant.tflite  --img bus.jpg
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
@franklinOliveira Can you check this?
