### ISSUE TITLE
smaller yolo network

### ISSUE THREAD

**Issue by qiuzhewei** [ultralytics/ultralytics#17000]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,
Thanks for your amazing work. Just out of curiosity, is there any smaller model(smaller than yolo11n) available?
The NCNN model I get from yolo11n.pt is 11M in fp32 mode, 5.2M in fp16, which is not friendly on a mobile device.

**Comment by Y-T-G** [comment]
It should be smaller with `int8` export but `ultralytics` doesn't support that for NCNN yet.

**Comment by qiuzhewei** [comment]
量化训练后保存的模型文件为什么大小还是和不量化得到的差不多？比如picodetxs，都是4M+的大小

**Comment by qiuzhewei** [comment]
Why the trained model size on disk is almost the same for quantized and non-quantized training procedure? Both sizes are about 4M on disk.

**Comment by Y-T-G** [comment]
The trainer model is saved as FP16. So quantizing to FP16 wouldn't reduce it. It's already FP16.

**Comment by qiuzhewei** [comment]
But in the configuration file, the specific quantization type is `int8` not `fp16`.
If it only supports to quantize to `fp16`, other tools, exporting to onnx for example, could also achieve that without loss of precision, then what the point of quantization?

**Comment by Y-T-G** [comment]
`int8` isn't supported for all export types since it's not straightforward and different formats require calibration techniques.

You can find the formats that support `int8` by checking the "Arguments" column here:

https://docs.ultralytics.com/modes/export/#export-formats
