### ISSUE TITLE
Why do the parameter count and FLOPs printed by model.info() differ from those printed during model.train()?

### ISSUE THREAD

**Issue by syz247179876** [ultralytics/ultralytics#17004]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a question regarding the YOLOv8n model. Why do the parameter count and FLOPs printed by model.info() differ from those printed during model.train()?

model.info():

![image](https://github.com/user-attachments/assets/a8be3daf-e436-4235-bc0e-13ac2973af75)

model.train():

![image](https://github.com/user-attachments/assets/f31e34d4-eff2-49be-8d07-6b2821fb9f18)

So, which calculation method should I use?

**Comment by Y-T-G** [comment]
If you're using 8.3.0+ for YOLOv8 training, then it uses a different head. 

https://github.com/ultralytics/ultralytics/issues/16678#issuecomment-2393099959

**Comment by syz247179876** [comment]
Yes, I know that after version 8.3.0+, the head changed from Conv to DWConv, but I'm using the same model and the same .yaml file here, so why do I get different parameter counts and computational costs when calling the two functions?

**Comment by syz247179876** [comment]
> If you're using 8.3.0+ for YOLOv8 training, then it uses a different head.
> 
> [#16678 (comment)](https://github.com/ultralytics/ultralytics/issues/16678#issuecomment-2393099959)

Yes, I know that after version 8.3.0+, the head changed from Conv to DWConv, but I'm using the same model and the same .yaml file here, so why do I get different parameter counts and computational costs when calling the two functions?

**Comment by Y-T-G** [comment]
It would be the same if you do this:

```python
from ultralytics import YOLO, ASSETS

model = YOLO("yolov8n.yaml")
model.info()
``` 

It won't be the same if you do this:

``python
from ultralytics import YOLO, ASSETS

model = YOLO("yolov8n.pt")
model.info()
``` 

The `.pt` model still has the original head and weights. But if you train with it, then the model is recreated based on the yaml `model.model.yaml` and the weights are transferred. While recreating it from yaml, it will use the new head.

**Comment by Laughing-q** [comment]
@Y-T-G You are right I forgot about that launching a training from pt model still need to create models from yamls first. @Y-T-G @syz247179876 I've created a PR to support the backward compatibility for our legacy models. https://github.com/ultralytics/ultralytics/pull/17010

**Comment by syz247179876** [comment]
> @Y-T-G You are right I forgot about that launching a training from pt model still need to create models from yamls first. @Y-T-G @syz247179876 I've created a PR to support the backward compatibility for our legacy models. #17010

@Y-T-G  Thank you for your help! I've resolved my issue, and the main reason is likely that the model I trained was from a version prior to 8.3.0. After updating to the new version, there was a discrepancy in the parameters and FLOPs between inference and training.
