### ISSUE TITLE
can yolov8 inference multi images as the same time?

### ISSUE THREAD

**Issue by xmj-7** [ultralytics/ultralytics#17014]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

can yolov8 inference multi images as the same time? i have 100 images, when i write a program predict one by one, it's slowly,can i set the batch same whit train or val?

**Comment by Y-T-G** [comment]
Yes. You can pass images as a list and all of them would be processed in a batch.

Or you can pass a folder and set `batch` and it will predict in batches.

https://docs.ultralytics.com/modes/predict/#inference-sources
