### ISSUE TITLE
I want to use V8 weights, why does the model automatically call 11 weight files？

### ISSUE THREAD

**Issue by Lucky-person** [ultralytics/ultralytics#17011]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to use V8 weights, why does the model automatically call 11 weight files
![屏幕截图 2024-10-18 173029](https://github.com/user-attachments/assets/230d5062-a66f-4da4-895e-fcbfac4e7c5c)

**Comment by Y-T-G** [comment]
It's for AMP checks. Not for training.

**Comment by Y-T-G** [comment]
@glenn-jocher Do we need to print the model name? It confuses a lot of people.

**Comment by Lucky-person** [comment]
> It's for AMP checks. Not for training.

thank you

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions, feel free to ask.

**Comment by monkeycc** [comment]
How to add AMP model path in code
This way, there is no need to download the PT model file

**Comment by glenn-jocher** [comment]
@monkeycc The AMP check is hardcoded to use YOLO11n.pt in the `check_amp()` function. If you want to avoid automatic downloads, you have two options:

1. Pre-download the model to your local Ultralytics assets folder (located in ~/.config/Ultralytics/assets/ on Linux/Mac or C:\Users\username\.config\Ultralytics\assets\ on Windows)

2. Disable AMP altogether by setting `amp=False` in your training command:
```python
model.train(data='coco.yaml', epochs=100, amp=False)
```

This way, the system won't attempt to perform AMP checks that trigger the download.

**Comment by monkeycc** [comment]
`model.train(data='coco.yaml', epochs=100, amp=True, amp_file="./yolov11n")`

`model.amp_file="./yolov11n"`

Suggest considering adding custom file paths
@glenn-jocher

**Comment by glenn-jocher** [comment]
@monkeycc That's a good suggestion. I like the idea of adding a custom file path option for AMP checks. This would give users more control and avoid unexpected downloads. I'll note this as a potential enhancement for future releases. 

Currently, as a workaround, you can either pre-download the model to your local assets directory or disable AMP completely, but having a configurable path would certainly be more flexible. Thanks for the feedback!

**Comment by Y-T-G** [comment]
> How to add AMP model path in code
> This way, there is no need to download the PT model file

If you already have `yolo11n.pt` in the working directory, it will not redownload.
