### ISSUE TITLE
Trying to use yolov8/v11 for detection speed of local cars. I notice when I run the script on the videos I've captured it passes in the following code & needing advice on real world distances and if they can or need to be set for 11x

### ISSUE THREAD

**Issue by benjaminfphillips** [ultralytics/ultralytics#17028]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

`Ultralytics Solutions: ✅ {'model': 'yolo11x.pt', 'region': [(375, 400), (775, 404), (775, 360), (375, 360)], 'line_width': 2, 'show': True, 'show_in': True, 'show_out': True, 'classes': None, 'up_angle': 145.0, 'down_angle': 90, 'kpts': [6, 8, 10], 'colormap': None, 'analytics_type': 'line'}`

This is the code that runs when I plug my file and minor changes into the example posts on collecting speed data (blog) the only reference to up and down angle I could see was inside gymAI.

I'm fairly new to any CV type stuff but I've defined a region, and the model picks up speeds that would be reasonable for the area when the car is inside the region, and I've added a conversion to make it mph rather than kmh. The region is defined in pixels, without any real world measurements.

Do I not need to be defining the size of the region, or something else on the screen for reference or is this something the model can roughly calculate some sort of distance per pixel? The footage I have taken was from a pedestrian bridge, over a road that has two lanes in opposite directions in the UK (dual carriageway). I do have a radar gun so I can capture footage and also compare with a radar gun when I next capture it. The height of the bridge is maybe 15 metres or so, so it gives a good vantage point.

Where I am more interested in is capturing data is on a single track road with likely only one car coming in either direction. The estimated height of my camera would be 8/10 feet in the air, so somewhere between 2.5 to 3 metres in height.

Obviously I can draw the region and tell the model the size of the region area but I'm wondering if there's something else I need to do in my situation or will the stock code give me 'reasonably' accurate data? As I say, I am new to this so I'm not 100% sure on how the speed is calculated without some sort of predetermined measurements.

I had used a python script before that needed to be at a 90 degree angle to the traffic and using cv it was able to roughly calculate the speed by tracking and taking images, BUT I did have to do some config by measuring the size of a known object/area before running it.

You'll have to excuse any ignorance on this, it's a bit of a learning process and before going any further I just wanted to understand the pixel vs real world calculation for distance without me inputting any values.

I'm using a 4090, along with a 13900k, with 64GB DDR 5600mhz ram to process the data - it's not being done in real time, it's being done from recorded videos as I cannot move my desktop to the areas I am trying to get an idea of car speeds from.

**Comment by glenn-jocher** [comment]
@benjaminfphillips to accurately estimate real-world distances from pixel measurements, you'll need to calibrate your setup using known measurements, such as the height of your camera or a reference object in the scene. This calibration allows the model to convert pixel distances to real-world units. For detailed guidance, you can refer to our speed estimation documentation at https://docs.ultralytics.com/guides/speed-estimation/.

**Comment by benjaminfphillips** [comment]
Hello Glenn,

Thanks for the reply. I had a little look around and couldn't see anything obvious in the arguments. It wouldn't be difficult for me to create a "region" using yolov11 of a known length and distance from my camera. My issue would be inputting that into the code. Is there a file/part of a file that has the predetermined settings for the model and code used in the blog posts for speed estimation in yolov11 to give me an idea of what I'm looking at/for/need to create.

I'm sure you've used your model in many situations to test it's accuracy. I don't need EXACT speeds, just a rough idea, enough to highlight a problem in the area, e.g the speed limit is 30, but people are still coming through at 50mph, which is exceedingly dangerous with the junction just 2/3 metres inside the 30 mph zone.

I'll try and illustrate my issue so it makes more sense. The speeds in the image below are in miles per hour. The small x set back in the image would be roughly where the camera would be at maybe 4m in height.

![30SignsEdit](https://github.com/user-attachments/assets/9c6589a2-a0f9-45f5-b143-0396b03515c9)

The issue we have is that in the UK any old lane is basically a 60mph for a road - it's an "unclassified road" if you tried driving these at 60 you'd be dead within minutes. Our new housing development is built at the end of one of these roads and unfortunately it provides a 500m straight for people to put their foot down and floor it. Essentially ignoring the 30mph sign, which goes to a 20 mph a little further down.

Pets are being killed on the monthly, there's been one child hit a bit further down, and cars sometimes park along the right hand side of the image which is a further issue, as children walking to get the bus have to walk around the cars (so they're now in the middle of the road) in order to get to the school bus that collects them further down the road.

So, my point being I don't need super accurate data, but it would be good to be able to take the overall volume of cars that are well in excess of the limit as they pass the 30 sign. E.g if I could go to them and say, here's some data, I've excluded any cars doing 35mph or less, as this is the margin of error.

The council are looking into it, but cold hard data is much harder to miss than a bunch of annoyed parents. It's a bit of a death trap and there's much more to it than the obvious issue from the image.

I hope this makes sense.

**Comment by benjaminfphillips** [comment]
Alt tabbed and closed accidently 🤦‍♂️

**Comment by glenn-jocher** [comment]
No worries! If you have any further questions or need assistance, feel free to ask.

**Comment by benjaminfphillips** [comment]
I did ask something in the comment above the accidental closure. I couldn't see anything obvious about mm per pixel or anything like that in the demo code. What does the code use by default/where is it stored please? Just so I can get some idea of how it makes it's estimates.

I also asked a question about how accurate the default snippet likely is, due to my use case not needing to be EXACT but within a few (maybe 5mph) mph would be fine

**Comment by glenn-jocher** [comment]
The code uses pixel measurements and requires calibration with known distances for accurate speed estimation. For your use case, setting a reference object or known distance in the scene will help achieve the accuracy you need. The default setup doesn't include real-world measurements, so calibration is essential.

**Comment by benjaminfphillips** [comment]
Hello again,

Appreciate the reply.

I hope this doesn't sound like a stupid question, I'm just looking to apply UA to a real world useful project, which others might also find some use in. I am just wondering which file/variables are responsible for this, or if there is a documentation page on creating such a configuration, or even any project you know of other people who've implemented their own real world data into the code.

I can go there and make markings on the road via spray paint or w/e and take images from the fixed position of the camera. Eg, I can go mark out a 10x5m area as the region area but I'm totally clueless at this point as to how I would put that into the code once I've measured the number of pixels that = 10m from my perspective.

**Comment by glenn-jocher** [comment]
@benjaminfphillips to incorporate real-world measurements, you'll need to calibrate your setup by mapping pixel distances to known real-world distances. This typically involves using a reference object or area with known dimensions. Unfortunately, there's no built-in feature for this in the default code, so you'll need to manually adjust your calculations based on your measurements. For further guidance, you might find community forums or discussions helpful.
