### ISSUE TITLE
Difference Between val And predict

### ISSUE THREAD

**Issue by ZYJIQVV** [ultralytics/ultralytics#17030]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Dear Ultralytics,
these days I found that the model predictions for the same image under predict mode differ from that under val mode. the predicted labels are the same as val but the confidences and bboxes are a little different from val.
could you please tell why there exists such a difference and how or what I should do to eliminate the difference

**Comment by hhaamm** [comment]
Have you checked if the parameters for inference are the same that for val? E.g. conf, imgsz, IoU, etc. I _think_ val uses conf=0.25 and IoU=0.45 for the plots.

**Comment by Y-T-G** [comment]
You can pass `rect=True` to `model.val()` to make it match predict.

https://github.com/ultralytics/ultralytics/issues/2783#issuecomment-2413530537

**Comment by ZYJIQVV** [comment]
> Have you checked if the parameters for inference are the same that for val? E.g. conf, imgsz, IoU, etc. I _think_ val uses conf=0.25 and IoU=0.45 for the plots.

yes they are the same. I found that the predicted bounding boxes of model.predict() are different from model.val(), the data augmentation seems to be the reason as when augmenting, the image is resized and padded and box is transformed with affinity transformation.

**Comment by ZYJIQVV** [comment]
> You can pass `rect=False` to `model.val()` to make it match predict.
> 
> [#2783 (comment)](https://github.com/ultralytics/ultralytics/issues/2783#issuecomment-2413530537)

thanks for your advice i'll try

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions, feel free to ask.

**Comment by myjc1** [comment]
你好，我遇到了相同的问题，对于同一张图像使用model.val()和model.predict()，检测的结果出现了偏差，请问是什么原因导致的呢

**Comment by glenn-jocher** [comment]
您好！`model.val()`和`model.predict()`结果差异通常源于验证和推理阶段的不同预处理参数。请确保：  
1. 参数对齐（`conf`/`iou`/`imgsz`）  
2. 验证时设置`rect=False`（默认True会启用矩形验证）  
3. 禁用预测的`augment`参数（默认False）  
完整参数设置参考[Val文档](https://docs.ultralytics.com/usage/cfg/)和[Predict文档](https://docs.ultralytics.com/guides/object-cropping/)。

**Comment by myjc1** [comment]
> 您好！`model.val()`和`model.predict()`结果差异通常源于验证和推理阶段的不同预处理参数。请确保：
> 
> 1. 参数对齐（`conf`/`iou`/`imgsz`）
> 2. 验证时设置`rect=False`（默认True会启用矩形验证）
> 3. 禁用预测的`augment`参数（默认False）
>    完整参数设置参考[Val文档](https://docs.ultralytics.com/usage/cfg/)和[Predict文档](https://docs.ultralytics.com/guides/object-cropping/)。

您好：感谢您给出的解答，我仍存在以下问题：
       在训练过程当中我将rect设置为False，但是在val的推理过程当中rect如果设置为False，map50相比rect设置为True的情况低15%左右，请问这是正常的吗？有什么比较好的解决办法吗

**Comment by cnjhh** [comment]
在val模式下，图像在送进模型检测时会进行预处理，rect=true意味着，图像会被缩放到640*640且，上下左右边框都会被填充16个灰度像素值，使得图像大小从640*640变为672*672，在predict时，则不会有缩放到640*640这一过程，而是640*未知数，且不会在图像四个边框填充16个像素，这样子会使得模型推理变快但是检测精度下降，误检率上升，主要是图像边缘误检会上升，可能原因是边缘没填充，导致误检。

**Comment by myjc1** [comment]
> 在val模式下，图像在送进模型检测时会进行预处理，rect=true意味着，图像会被缩放到640_640且，上下左右边框都会被填充16个灰度像素值，使得图像大小从640_640变为672_672，在predict时，则不会有缩放到640_640这一过程，而是640*未知数，且不会在图像四个边框填充16个像素，这样子会使得模型推理变快但是检测精度下降，误检率上升，主要是图像边缘误检会上升，可能原因是边缘没填充，导致误检。

如果是这样的话如何保证predict过程中的结果与val过程中较好的结果保持一致呢

**Comment by cnjhh** [comment]
> > 在val模式下，图像在送进模型检测时会进行预处理，rect=true意味着，图像会被缩放到640_640且，上下左右边框都会被填充16个灰度像素值，使得图像大小从640_640变为672_672，在predict时，则不会有缩放到640_640这一过程，而是640*未知数，且不会在图像四个边框填充16个像素，这样子会使得模型推理变快但是检测精度下降，误检率上升，主要是图像边缘误检会上升，可能原因是边缘没填充，导致误检。
> 
> 如果是这样的话如何保证predict过程中的结果与val过程中较好的结果保持一致呢？

predict时，rect设置为True，如果结果不一致，再试试修改源码：
①　Ultralytics.data.augment.LetterBox.__Call__
添加if条件：
if labels.pop('type_mode', True) != 'predict':
labels = self._update_labels(labels, ratio, dw, dh)
②　Ultralytics.engine.predictor.BasePredictor.pre_transform
函数体替换为：
h0, w0 = im[0].shape[:2]  # orig hw
r = self.imgsz[0] / max(h0, w0)  # ratio

mini = maxi = h0/float(w0)
if maxi < 1:
    shapes = [maxi, 1]
elif mini > 1:
    shapes = [1, 1 / mini]
else:
    shapes = [1, 1]
stride=32
pad=0.5
rect_shapes = np.ceil(np.array(shapes) * self.imgsz / stride + pad).astype(int) *stride

if r != 1:  # if sizes are not equal
    w, h = (min(math.ceil(w0 * r), self.imgsz[1]), min(math.ceil(h0 * r), self.imgsz[0]))
    im[0] = cv2.resize(im[0], (w, h), interpolation=cv2.INTER_LINEAR)

labels = {'img':im[0], 'rect_shape':rect_shapes, 'ratio_pad':(h/h0, w/w0), 'type_mode':'predict'}
letterbox = LetterBox(self.imgsz, auto=False, scaleup=False, stride=self.model.stride)
res = letterbox(labels=labels)
self.batch = (*self.batch[:2], res['ratio_pad'], self.batch[3])
return [res['img']]
③　Ultralytics.engine.predictor.BasePredictor.stream_inference
1)添加
path, im0s, vid_cap, s = batch
im0scopy = im0s.copy()
# Preprocess
with profilers[0]:
im = self.preprocess(im0s)
2)替换
with profilers[2]:
#self.results = self.postprocess(preds, im, im0s) #ori
self.results = self.postprocess(preds, im, im0scopy)
④　Ultralytics.models.yolo.detect.DetectionPredictor.postprocess
替换
#pred[:, :4] = ops.scale_boxes(img.shape[2:], pred[:, :4], orig_img.shape)  # ori
pred[:, :4] = ops.scale_boxes(img.shape[2:], pred[:, :4], orig_img.shape, ratio_pad=self.batch[2])   
⑤　Val验证模式batch=1，imgsz、conf、iou和Predict设置一致，即可得到一致预测结果。

**Comment by myjc1** [comment]
> > > 在val模式下，图像在送进模型检测时会进行预处理，rect=true意味着，图像会被缩放到640_640且，上下左右边框都会被填充16个灰度像素值，使得图像大小从640_640变为672_672，在predict时，则不会有缩放到640_640这一过程，而是640*未知数，且不会在图像四个边框填充16个像素，这样子会使得模型推理变快但是检测精度下降，误检率上升，主要是图像边缘误检会上升，可能原因是边缘没填充，导致误检。
> > 
> > 
> > 如果是这样的话如何保证predict过程中的结果与val过程中较好的结果保持一致呢？
> 
> predict时，rect设置为True，如果结果不一致，再试试修改源码： ①　Ultralytics.data.augment.LetterBox.**Call** 添加if条件： if labels.pop('type_mode', True) != 'predict': labels = self._update_labels(labels, ratio, dw, dh) ②　Ultralytics.engine.predictor.BasePredictor.pre_transform 函数体替换为： h0, w0 = im[0].shape[:2] # orig hw r = self.imgsz[0] / max(h0, w0) # ratio
> 
> mini = maxi = h0/float(w0) if maxi < 1: shapes = [maxi, 1] elif mini > 1: shapes = [1, 1 / mini] else: shapes = [1, 1] stride=32 pad=0.5 rect_shapes = np.ceil(np.array(shapes) * self.imgsz / stride + pad).astype(int) *stride
> 
> if r != 1: # if sizes are not equal w, h = (min(math.ceil(w0 * r), self.imgsz[1]), min(math.ceil(h0 * r), self.imgsz[0])) im[0] = cv2.resize(im[0], (w, h), interpolation=cv2.INTER_LINEAR)
> 
> labels = {'img':im[0], 'rect_shape':rect_shapes, 'ratio_pad':(h/h0, w/w0), 'type_mode':'predict'} letterbox = LetterBox(self.imgsz, auto=False, scaleup=False, stride=self.model.stride) res = letterbox(labels=labels) self.batch = (*self.batch[:2], res['ratio_pad'], self.batch[3]) return [res['img']] ③　Ultralytics.engine.predictor.BasePredictor.stream_inference 1)添加 path, im0s, vid_cap, s = batch im0scopy = im0s.copy()
> 
> # Preprocess
> with profilers[0]: im = self.preprocess(im0s) 2)替换 with profilers[2]: #self.results = self.postprocess(preds, im, im0s) #ori self.results = self.postprocess(preds, im, im0scopy) ④　Ultralytics.models.yolo.detect.DetectionPredictor.postprocess 替换 #pred[:, :4] = ops.scale_boxes(img.shape[2:], pred[:, :4], orig_img.shape) # ori pred[:, :4] = ops.scale_boxes(img.shape[2:], pred[:, :4], orig_img.shape, ratio_pad=self.batch[2]) ⑤　Val验证模式batch=1，imgsz、conf、iou和Predict设置一致，即可得到一致预测结果。

非常感谢您给出的建议，我已经按照您给出的建议对源代码进行了修改，但他似乎出现了一些问题导致修改后的代码无法运行，希望您能给出一定指导

**Comment by myjc1** [comment]
> > > > 在val模式下，图像在送进模型检测时会进行预处理，rect=true意味着，图像会被缩放到640_640且，上下左右边框都会被填充16个灰度像素值，使得图像大小从640_640变为672_672，在predict时，则不会有缩放到640_640这一过程，而是640*未知数，且不会在图像四个边框填充16个像素，这样子会使得模型推理变快但是检测精度下降，误检率上升，主要是图像边缘误检会上升，可能原因是边缘没填充，导致误检。
> > > 
> > > 
> > > 如果是这样的话如何保证predict过程中的结果与val过程中较好的结果保持一致呢？
> > 
> > 
> > predict时，rect设置为True，如果结果不一致，再试试修改源码： ①　Ultralytics.data.augment.LetterBox.**Call** 添加if条件： if labels.pop('type_mode', True) != 'predict': labels = self._update_labels(labels, ratio, dw, dh) ②　Ultralytics.engine.predictor.BasePredictor.pre_transform 函数体替换为： h0, w0 = im[0].shape[:2] # orig hw r = self.imgsz[0] / max(h0, w0) # ratio
> > mini = maxi = h0/float(w0) if maxi < 1: shapes = [maxi, 1] elif mini > 1: shapes = [1, 1 / mini] else: shapes = [1, 1] stride=32 pad=0.5 rect_shapes = np.ceil(np.array(shapes) * self.imgsz / stride + pad).astype(int) *stride
> > if r != 1: # if sizes are not equal w, h = (min(math.ceil(w0 * r), self.imgsz[1]), min(math.ceil(h0 * r), self.imgsz[0])) im[0] = cv2.resize(im[0], (w, h), interpolation=cv2.INTER_LINEAR)
> > labels = {'img':im[0], 'rect_shape':rect_shapes, 'ratio_pad':(h/h0, w/w0), 'type_mode':'predict'} letterbox = LetterBox(self.imgsz, auto=False, scaleup=False, stride=self.model.stride) res = letterbox(labels=labels) self.batch = (*self.batch[:2], res['ratio_pad'], self.batch[3]) return [res['img']] ③　Ultralytics.engine.predictor.BasePredictor.stream_inference 1)添加 path, im0s, vid_cap, s = batch im0scopy = im0s.copy()
> > # Preprocess
> > with profilers[0]: im = self.preprocess(im0s) 2)替换 with profilers[2]: #self.results = self.postprocess(preds, im, im0s) #ori self.results = self.postprocess(preds, im, im0scopy) ④　Ultralytics.models.yolo.detect.DetectionPredictor.postprocess 替换 #pred[:, :4] = ops.scale_boxes(img.shape[2:], pred[:, :4], orig_img.shape) # ori pred[:, :4] = ops.scale_boxes(img.shape[2:], pred[:, :4], orig_img.shape, ratio_pad=self.batch[2]) ⑤　Val验证模式batch=1，imgsz、conf、iou和Predict设置一致，即可得到一致预测结果。
> 
> 非常感谢您给出的建议，我已经按照您给出的建议对源代码进行了修改，但他似乎出现了一些问题导致修改后的代码无法运行，希望您能给出一定指导。
此外，在训练过程当中也会进行验证过程，在这一过程当中rect是保持开启还是关闭

**Comment by glenn-jocher** [comment]
您好！val模式与predict结果差异主要源于预处理流程的不同。若需保持训练中验证结果的一致性，建议：

1. **训练阶段**：保持`rect=True`（默认设置），这是标准评估方式
2. **预测阶段**：通过`model.predict(imgsz=val_imgsz, rect=True)`对齐参数，无需修改源码

验证指标差异15%属异常情况，通常应<2%。请确保：
- 验证/预测使用相同`imgsz`
- 禁用预测的`augment`参数
- 确认数据集标注一致性

具体参数配置请参考官方文档[Val设置](https://docs.ultralytics.com/usage/cfg/)和[Predict参数](https://docs.ultralytics.com/guides/object-cropping/)。若仍需代码级调试，建议在GitHub提交具体报错信息的Issue。
