### ISSUE TITLE
Confusion matrix label for multiple bounding boxes in one object

### ISSUE THREAD

**Issue by Azhar275** [ultralytics/ultralytics#17041]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I'm currently trying to recreate the confusion matrix for a YOLOv8 model. I have a case that keeps bothering me. For example, I have a model to detect a dog in an image. However, the model gives the dog two bounding boxes instead of one. So, do both of the bounding boxes count as TP in the confusion matrix, or does only one of them count as TP?

**Comment by glenn-jocher** [comment]
@Azhar275 in a confusion matrix, only one bounding box should count as a true positive (TP) if it matches the ground truth, while the other would typically be considered a false positive (FP). For more insights, you can refer to the [YOLO Common Issues Guide](https://docs.ultralytics.com/guides/yolo-common-issues/).
