### ISSUE TITLE
Question About imgsz Parameter When Using YOLOv8 on iOS for Tennis Ball Detection

### ISSUE THREAD

**Issue by keisan1231** [ultralytics/ultralytics#17043]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to use YOLOv8 on iOS to recognize tennis balls and have a question regarding the imgsz parameter.

The smartphone screen's pixel size is, for example, 1080 x 2340, which is not square. Should I generally export the input images to the YOLO model as squares (e.g., imgsz=[640, 640])?

Additionally, are there any advantages to exporting them as rectangles that maintain the same aspect ratio as the pixel size, such as imgsz=[360, 780]?

Regarding how YOLO operates, which is faster and more accurate: recognizing the entire image or recognizing a cropped portion of the image? (Assuming the area to be recognized is the same.)

Thank you for your assistance!

**Comment by Y-T-G** [comment]
The screen size doesn't have an effect. Perhaps you mean camera resolution.

> Additionally, are there any advantages to exporting them as rectangles that maintain the same aspect ratio as the pixel size, such as imgsz=[360, 780]?

If your camera is running at a certain aspect ratio, then you can export at that ratio and it should be somewhat faster.

> Regarding how YOLO operates, which is faster and more accurate: recognizing the entire image or recognizing a cropped portion of the image? (Assuming the area to be recognized is the same.)

It wouldn't have a much effect on speed if you're inferring at the same `imgsz`. The only effect would be how much faster the image can be resized to match `imgsz`. If the original resolution is 4K, while the cropped portion is 1280x720, going from the latter to 640x640 is faster than going from 4K to 640x640.

**Comment by keisan1231** [comment]
@Y-T-G Thank you so much
