### ISSUE TITLE
USER_CONFIG_DIR is not a PurePath object and does not support / operation.

### ISSUE THREAD

**Issue by sthemeow** [ultralytics/ultralytics#1704]
https://github.com/ultralytics/ultralytics/blob/ccb64198351b1121478ab4280589741c7988003f/ultralytics/yolo/utils/__init__.py#L589

`file=USER_CONFIG_DIR / 'settings.yaml'` is not possible.
USER_CONFIG_DIR is a string object, not a PurePath object, and hence does not support / operation.

When run with os env USER_CONFIG_DIR defined, the following error will occur:
`File "/***/ultralytics/yolo/utils/__init__.py", line 589, in <module>
    def get_settings(file=USER_CONFIG_DIR / 'settings.yaml', version='0.0.2'):
TypeError: unsupported operand type(s) for /: 'str' and 'str'`

**Comment by glenn-jocher** [comment]
@sthemeow thank you for the bug report and the PR fix!
