### ISSUE TITLE
How Can I calculate the number of each segment pixels in segmentation?

### ISSUE THREAD

**Issue by azadehashouri** [ultralytics/ultralytics#17045]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello everyone,
I train Yolo segmentation on my custom dataset including 17 classes.
I intend to calculate the number of each segment pixels. I want to find the exact and precise size of each segment in my test data.
However, I don't have any idea how can access the number of pixels in each segment which is related to specific category.

I really appreciate your help in advance.
Thanks.

**Comment by Y-T-G** [comment]
You can use this.

```python
from ultralytics import YOLO, ASSETS

model = YOLO("yolo11n-seg.pt")
results = model(ASSETS / "bus.jpg") 

for mask in results[0].masks.data:
	 num_pixels = mask.sum()
```

**Comment by azadehashouri** [comment]
> You can use this.
> 
> ```python
> from ultralytics import YOLO, ASSETS
> 
> model = YOLO("yolo11n-seg.pt")
> results = model(ASSETS / "bus.jpg") 
> 
> for mask in results[0].masks.data:
>     num_pixels = mask.sum()
> ```

So many thanks @Y-T-G :)

**Comment by azadehashouri** [comment]
@Y-T-G Excuse me,
How can I get label of each segment, too?
Thank you.

**Comment by Y-T-G** [comment]
You can read the docs: 

https://docs.ultralytics.com/modes/predict/#working-with-results


```python
from ultralytics import YOLO, ASSETS

model = YOLO("yolo11n-seg.pt")
result = model(ASSETS / "bus.jpg")[0]

for cls, mask in zip(result.boxes.cls, result.masks.data):
	 num_pixels = mask.sum()
```

**Comment by azadehashouri** [comment]
> You can read the docs:
> 
> https://docs.ultralytics.com/modes/predict/#working-with-results
> 
> ```python
> from ultralytics import YOLO, ASSETS
> 
> model = YOLO("yolo11n-seg.pt")
> result = model(ASSETS / "bus.jpg")[0]
> 
> for cls, mask in zip(result.boxes.cls, result.masks.data):
> 	 num_pixels = mask.sum()
> ```
I appreciate your help, and thank you so much.
@Y-T-G
