### ISSUE TITLE
How to turn off pre-trained weights?   About the YOLOv11 model

### ISSUE THREAD

**Issue by WCC0810** [ultralytics/ultralytics#17053]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to turn off pre-trained weights?   About the YOLOv11 model
I've tried several methods, but none of them seem to work, and the pre-trained weights are downloaded every time. How to solve it?
Thanks

**Comment by WCC0810** [comment]
![9ED95015C9F72D669220108C80985412](https://github.com/user-attachments/assets/7428da8d-0b3d-46f6-9b41-315fcbb54402)

**Comment by WCC0810** [comment]
![9ED95015C9F72D669220108C80985412](https://github.com/user-attachments/assets/212c3938-ec79-43d3-ace8-3b807e2238d6)
![3827E6133F4BC4092326073AD9842DA1](https://github.com/user-attachments/assets/df0e6f16-b9fb-4b6c-b5f7-047460866b0a)

**Comment by Y-T-G** [comment]
It's using `yolo11n.pt` for AMP checks.

**Comment by Y-T-G** [comment]
Not for training.
