### ISSUE TITLE
YOLOv10s trained on RHEL 8 with CUDA support crashes upon inference with device = 'mps'

### ISSUE THREAD

**Issue by gH2AX** [ultralytics/ultralytics#17054]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

```
WARNING ⚠️ imgsz=[2202] must be multiple of max stride 32, updating to [2208]
/AppleInternal/Library/BuildRoots/289ffcb4-455d-11ef-953d-e2437461156c/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSNDArray/Kernels/MPSNDArrayGatherND.mm:256: failed assertion `Rank of updates array (1) must be greater than or equal to inner-most dimension of indices array (300)'
zsh: abort      /opt/homebrew/Caskroom/miniforge/base/envs/ultralytics/bin/python 
```

Works on CPU. Same problem with YOLOv10m.
Yes, I have tried updating Ultralytics to the latest version. 

### Environment

Train environment:

Ultralytics YOLOv8.2.98 🚀 Python-3.11.10 torch-2.4.1+cu121 CUDA:0 (NVIDIA A100-PCIE-40GB, 40339MiB)
Setup complete ✅ (64 CPUs, 503.3 GB RAM, 7.6/40.0 GB disk)

OS                  Linux-4.18.0-372.16.1.el8_6.x86_64-x86_64-with-glibc2.28
Environment         Linux
Python              3.11.10
Install             pip
RAM                 503.35 GB
CPU                 Intel Core Processor (Haswell, IBRS)
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.4.1>=1.8.0
torchvision         ✅ 0.19.1>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.6>=2.0.0
torch               ✅ 2.4.1!=2.4.0,>=1.8.0; sys_platform == "win32"

Inference environment:

Ultralytics YOLOv8.2.98 🚀 Python-3.11.10 torch-2.4.1 CPU (Apple M1 Pro)
Setup complete ✅ (10 CPUs, 32.0 GB RAM, 691.1/926.4 GB disk)

OS                  macOS-14.7-arm64-arm-64bit
Environment         Darwin
Python              3.11.10
Install             git
RAM                 32.00 GB
CPU                 Apple M1 Pro
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0>=4.6.0
pillow              ✅ 11.0.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.4.1>=1.8.0
torchvision         ✅ 0.19.1>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.6>=2.0.0
torch               ✅ 2.4.1!=2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

```
model = YOLO(".YOLO/models/weights/best.pt")
predictions = model.predict(FOLDER, conf = 0.6, imgsz = 2202, max_det = 1, classes = [0], stream = True, device = 'mps')
next(predictions)
```
[best.pt.zip](https://github.com/user-attachments/files/17450319/best.pt.zip)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
Does the pretrained models work?

**Comment by gH2AX** [comment]
> Does the pretrained models work?

Yes.

**Comment by Y-T-G** [comment]
Does it fail immediately or after some images?

**Comment by gH2AX** [comment]
It fails right away.

**Comment by Y-T-G** [comment]
Does it work if you add this before your code:

```python
import torch

def mps_gather_workaround(input, dim, index):
    if input.shape[-1] == 1:
        return torch.gather(input.unsqueeze(-1), dim - 1 if dim < 0 else dim, index.unsqueeze(-1)).squeeze(-1)
    else:
        return torch.gather(input, dim, index) 

torch.Tensor.gather = mps_gather_workaround
```

**Comment by gH2AX** [comment]
Where did your last comment go? That little snippet worked perfectly! Now inference runs 5x faster than before.

```
import torch

def mps_gather_workaround(input, dim, index):
    if input.shape[-1] == 1:
        return torch.gather(input.unsqueeze(-1), dim - 1 if dim < 0 else dim, index.unsqueeze(-1)).squeeze(-1)
    else:
        return torch.gather(input, dim, index) 

torch.Tensor.gather = mps_gather_workaround
```

**Comment by Y-T-G** [comment]
I was testing it. Thought it was broken.

```python
import torch

def mps_gather_workaround(input, dim, index):
    if input.shape[-1] == 1:
        return torch.gather(input.unsqueeze(-1), dim - 1 if dim < 0 else dim, index.unsqueeze(-1)).squeeze(-1)
    else:
        return torch.gather(input, dim, index) 

torch.Tensor.gather = mps_gather_workaround
```

**Comment by Y-T-G** [comment]
@gH2AX Does the error occur with pretrained YOLOv10 models if you use `max_det=1`?

**Comment by Y-T-G** [comment]
and `imgsz=2202`

**Comment by gH2AX** [comment]
Yes and yes!

**Comment by glenn-jocher** [comment]
It seems like the issue might be related to the specific configuration on your MPS setup. If the pretrained models work, try adjusting the image size or other parameters to see if it resolves the issue.

**Comment by glenn-jocher** [comment]
Could you provide more details about the issue you're experiencing?

**Comment by gH2AX** [comment]
> Could you provide more details about the issue you're experiencing?

What do you want to know? I am not an experienced enough programmer to make changes to the MPS framework - if that is even possible. I suspect a bug in the MPS implementation of Pytorch, but since that one-line error report is all I got, I did not know here to look. My previous answer might have been misleading and has been rectified just now.
