### ISSUE TITLE
YOLOv11n and YOLOV11s

### ISSUE THREAD

**Issue by OmarKhater98** [ultralytics/ultralytics#17058]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is the architecture for yolov11n and yolov11s available? And if it is available, can you please give me the link?

**Comment by 2JAE22** [comment]
available. just use that from github..!

**Comment by OmarKhater98** [comment]
Can you please share the link with me. Because I did not see the full code for yolov11

**Comment by Y-T-G** [comment]
Are you asking about architecture diagram?

**Comment by 77xiaofa** [comment]
Same,my pycharm cannot download yolov11 models,aha!!!!

**Comment by OmarKhater98** [comment]
Yes @Y-T-G . I need the full implementation code or the diagram that can help in wrjtinh the code if it not available

**Comment by 2JAE22** [comment]
@OmarKhater98  you can download yolov11.pt any moder from ultralytic hub
login > model > selece model > deploy page
 it can download yolov11.pt
 but if you want to see the code which see all codes, you must git clone this gitpage then see ultralytic>models> yolo > v11 folder

**Comment by glenn-jocher** [comment]
The repository includes the implementation for YOLOv11 models. You can explore the code by cloning the repo and navigating to the `ultralytics/models/yolo` directory. For more details, visit the [YOLO11 documentation](https://docs.ultralytics.com/models/yolo11/).

**Comment by OmarKhater98** [comment]
@glenn-jocher, Can you please give me the repo for yolov11n and yolov11s for object detection?

**Comment by Y-T-G** [comment]
This repo has the YOLO11 implementation.

The yaml files define the architecture:
https://github.com/ultralytics/ultralytics/tree/main/ultralytics/cfg/models/11

The model layers are built using the yaml files.

**Comment by OmarKhater98** [comment]
@Y-T-G Thank you Mohammed. But this yaml file only includes the description of the layers, not the actual full code. So, how I can generate the full code from this file?

**Comment by Y-T-G** [comment]
The yaml files are parsed by `ultralytics` to generate the model. If you mean code with YOLO11 class and all the layers defined, then there's no such code. The model is generated dynamically based on the yaml files.

**Comment by OmarKhater98** [comment]
@Y-T-G Yeah, that's what I meant. The only way now to build the code is using the YAML file
