### ISSUE TITLE
Train fails with: cv2.error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'resize'

### ISSUE THREAD

**Issue by gcem-ph** [ultralytics/ultralytics#17067]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

Yolo fails with an error when cv2 try to resize the image. Tried with different datasets (ie. coco, coco8 etc). 

```
yolo detect train data=coco8.yaml model=yolov8n.pt epochs=100 imgsz=128 device=1
File "/opt/anaconda3/envs/pytorch/lib/python3.12/site-packages/ultralytics/data/augment.py", line 1584, in __call__
    img = cv2.resize(img, new_unpad, interpolation=cv2.INTER_LINEAR)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'

```
Image resize works fine with no errors when executed outside yolo:

```
import cv2
import os
import numpy as np

image_path = 'img.png'
image = cv2.imread(image_path)
shape = (image.shape[0], image.shape[1])
new_shape = (640, 640)
r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])
shape = image.shape[:2]
new_unpad = int(round(shape[1] * r)), int(round(shape[0] * r))
resized = cv2.resize(image, new_unpad,interpolation=cv2.INTER_LINEAR)

```

### Environment

```
$ yolo checks
Ultralytics 8.3.16 🚀 Python-3.12.7 torch-2.4.1+cu121 CUDA:0 (Tesla T4, 14931MiB)
Setup complete ✅ (224 CPUs, 3023.0 GB RAM, 34.7/70.0 GB disk)

OS                  Linux-4.18.0-513.18.1.el8_9.x86_64-x86_64-with-glibc2.28
Environment         Linux
Python              3.12.7
Install             pip
RAM                 3022.98 GB
Disk                34.7/70.0 GB
CPU                 Intel Xeon Platinum 8380H 2.90GHz
CPU count           224
GPU                 Tesla T4, 14931MiB
GPU count           2
CUDA                12.1

numpy               ✅ 1.26.4>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.4.1>=1.8.0
torchvision         ✅ 0.19.1>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.9>=2.0.0
torch               ✅ 2.4.1!=2.4.0,>=1.8.0; sys_platform == "win32"
```

### Minimal Reproducible Example

`yolo detect train data=coco8.yaml model=yolov8n.pt epochs=1 imgsz=128 device=1`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
Probably something wrong with your environment.

Does this work?

```python
from ultralytics import YOLO, ASSETS

model = YOLO("yolo11n.pt")
results = model(ASSETS / "bus.jpg") 
```

**Comment by gcem-ph** [comment]
same error:

```
cv2.error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'imdecode'
> Overload resolution failed:
>  - buf is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'buf'
```

**Comment by Y-T-G** [comment]
I guess recreate the environment and reinstall `ultralytics`

**Comment by gcem-ph** [comment]
reinstalling miniconda + env solved the issue.

**Comment by glenn-jocher** [comment]
Great to hear that reinstalling Miniconda and the environment resolved the issue! If you have any more questions, feel free to ask.

**Comment by DeeraDigiSpoc** [comment]
It's better to create a new envioronment for Ultralytics, or Steps to solve in the same environment:

1.  Uninstall OpenCV and torch. (also ultralytics if installed)
2. Install ultralytics
3. then, PyTorch

**Comment by glenn-jocher** [comment]
Creating a new environment for Ultralytics is a good approach. If issues persist, reinstalling OpenCV, PyTorch, and Ultralytics in that order can help resolve conflicts.

**Comment by Kidult29** [comment]
In my environment,  I uninstall Opencv and  reinstall again, then problem is solved.

**Comment by glenn-jocher** [comment]
Thanks for confirming—this is usually due to mixed pip/conda installs corrupting OpenCV; stick to one package manager and verify with yolo checks; we’ll close this out, but if it reappears please reopen with a minimal reproducible example.

**Comment by GhaouiYoussef** [comment]
check if you can import matplotlib.pyplot without error: if it raises an error:
!pip install --force-reinstall numpy matplotlib --upgrade
then restart the kernel the training/val would work.

**Comment by glenn-jocher** [comment]
Good tip—matplotlib import failures can signal a broken NumPy; after reinstalling, please verify the environment and share text outputs with:
```bash
yolo checks
```
If the OpenCV resize/imdecode error persists, open a new issue with the full traceback and an MRE per [Creating a Minimal Reproducible Example](https://docs.ultralytics.com/help/minimum-reproducible-example/); you can also reference guidance in [Troubleshooting Common YOLO Issues](https://docs.ultralytics.com/guides/yolo-common-issues/).
