### ISSUE TITLE
Why is the squeeze operation slower than the numpy translation?

### ISSUE THREAD

**Issue by sh1man999** [ultralytics/ultralytics#17069]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I compared the two methods and unzip is 2x faster. Why is that, can anyone    
   
   ```
 def unzip(self):
        boxes = self.result.boxes.xyxy.int().cpu().numpy()
        confidences = self.result.boxes.conf.cpu().numpy()
        for box, confidence in zip(boxes, confidences):
            yield NumberPlate(box=BoundingBox(*box), confidence=confidence)

    def unzip2(self):
        for d in self.result.boxes:
            conf, box = float(d.conf), d.xyxy.squeeze()
            if isinstance(box, torch.Tensor):
                box = box.tolist()
            yield NumberPlate(box=BoundingBox(*box), confidence=conf)
```

**Comment by Y-T-G** [comment]
Which one is faster?

**Comment by sh1man** [comment]
Is unzip first

**Comment by sh1man** [comment]
Which of the features do you think is the best in production?

**Comment by Y-T-G** [comment]
You should only move the results to the CPU and convert to numpy once.

`results = results.cpu().numpy()`

**Comment by sh1man999** [comment]
this will be the fastest

r = self.result.boxes.cpu().numpy()
for box, confidence in zip(r.xyxy.astype(int), r.conf.astype(int)):
	yield NumberPlate(box=BoundingBox(*box), confidence=confidence)

**Comment by glenn-jocher** [comment]
@sh1man999 thank you for sharing your approach. It looks efficient for converting and iterating over results. If you have further questions, feel free to ask!
