### ISSUE TITLE
Validation via SAHI

### ISSUE THREAD

**Issue by faxy1578** [ultralytics/ultralytics#17061]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi. I have a couple of questions.

1. I am trying to evaluate object detection on high-resolution images using a trained YOLO-v8 model.

I want to approach the high-resolution images in the similar way as SAHI, making inferences in the form of a sliding window and using it for model evaluation.
However, in ultralyics, it seems that SAHI is only provided with code for inference. Is it possible to evaluate the accuracy of the prediction based on the label information with SAHI?

2. I want to upsample the resolution of the evaluation data by applying super-resolution and use it to evaluate the yolo model. However, it seems that for upsampling, I need to convert the annotation given by gt to correspondingly. Does ultralyics support a similar pipeline that handles this approach?

3. I would like to plot GT bounding boxes on the original image like this code: 
 engine/validator.py > self.plot_val_samples(batch, batch_i) 
 The problem is that that validator code plots on resized data. I would like to draw a gt bounding box on the original image, is there any way to do that?

**Comment by faxy1578** [comment]
The solution to issue #1 was found at the following link:
@ https://github.com/ultralytics/ultralytics/issues/7768#issuecomment-1960746239

I don't think it's been integrated into the main project yet, but it would be great to have it!

**Comment by Y-T-G** [comment]
1. val with SAHI is not supported.

2. YOLO annotations are not affected if you resize the original image as long as you maintain aspect ratio.

3. You can run `model.predict()` on all the images with `save=True` to save them with plotted annotations.

**Comment by faxy1578** [comment]
> 1. val with SAHI is not supported.
> 2. YOLO annotations are not affected if you resize the original image as long as you maintain aspect ratio.
> 3. You can run `model.predict()` on all the images with `save=True` to save them with plotted annotations.

Thank you for your kind response.

Regarding answer #3, I want to draw only the bounding box for the label (gt) on the original image, not the bounding box for the prediction result, and not include the prediction result. How would you suggest me to do in this case?

**Comment by Y-T-G** [comment]
`ultralytics` doesn't provide a function to plot GT manually. But you can use Ultralytics HUB and upload your dataset to it to view the plotted ground truths.

**Comment by glenn-jocher** [comment]
@mmarei1 i'm glad you found a solution using the supervision package. For plotting ground truth boxes, adapting their examples is a great approach. If you have further questions, feel free to ask!
