### ISSUE TITLE
Question about a log message that appears to be an empty message

### ISSUE THREAD

**Issue by emily-bianchi** [ultralytics/ultralytics#17066]
Hi,
quick question: I was keep getting an empty line in my terminal when running something and I tracked it down to be a log message emitted by the ultralytics logger. Specifically, it seems to be this line. 
https://github.com/ultralytics/ultralytics/blob/0535db9885327d4ff2e7a7f41e6b8dad4a3a6abf/ultralytics/engine/predictor.py#L218
Was just curious to understand if there was a particular reason for it to be an empty string and to be there :smile: 

Thanks,
E

**Comment by Y-T-G** [comment]
I guess it's to add spacing between multiple predictions being run sequentially.

**Comment by emily-bianchi** [comment]
Ok, thanks. But does it really make sense to "add spacing" between logs? Also, the log message itself already contains info useful for the reader to easily tell apart messages from multiple predictions.

**Comment by Y-T-G** [comment]
I think whitespace is still required for it to appear not congested
