### ISSUE TITLE
 Difference in learning speed between yolov8n and yolov11n

### ISSUE THREAD

**Issue by kunsungwoo** [ultralytics/ultralytics#17068]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have mainly used yolov8n. To test it, I also tried learning with yolov11n, but the learning speed was 3 times slower. Why? All parameters are the same. The training data is 300,000 images of size 640. Per epoch, yolov8n takes 36 minutes, and yolov11n takes 1 hour and 35 minutes

results= model.train(data='/content/sample_data/test/data.yaml',epochs=18,imgsz=640,batch=64,patience=3,save_period=1,name='yolo8n',iou=0.95,lr0=0.001,lrf=0.001,exist_ok=True,pretrained=True ,deterministic=False,translate=0.00,scale=0.025,mosaic=0.00,mixup=0.0,cls=6,box=90,dfl=9.0,close_mosaic=18,shear=0.0,erasing=0,perspective=0.0,flipud=0,fliplr=0,copy_paste=0,optimizer='AdamW',cos_lr=True)

results= model.train(data='/content/sample_data/test/data.yaml',epochs=18,imgsz=640,batch=64,patience=3,save_period=1,name='yolo11n',iou=0.85,lr0=0.001,lrf=0.001,exist_ok=True,pretrained=True ,deterministic=False,translate=0.00,scale=0.025,mosaic=0.00,mixup=0.0,cls=6,box=90,dfl=9.0,close_mosaic=18,shear=0.0,erasing=0,perspective=0.0,flipud=0,fliplr=0,copy_paste=0,optimizer='AdamW',cos_lr=True)

**Comment by glenn-jocher** [comment]
@kunsungwoo yOLOv11n's architecture includes enhancements that may increase computational requirements, leading to slower training speeds compared to YOLOv8n. For more details, you can refer to the YOLOv11 documentation.

**Comment by kunsungwoo** [comment]
@glenn-jocher For yolov8 or yolov10, worker=8 is set, and during training, it is normally displayed as "Using 8 dataloader workers." However, in yolo11, the number of workers is set to 8, but when training starts, it displays "Using 2 dataloader workers."
Doesn’t this have a big impact on learning time? The difference in learning speed is too severe.

**Comment by kunsungwoo** [comment]
@glenn-jocher I tried with workers=8, but it still says Using 2 dataloader workers. Is there a bug?


results= model.train(data='/content/sample_data/test/data.yaml',epochs=18,imgsz=640,batch=64,patience=3,save_period=1,name='yolo11_3',workers=8,iou=0.85,lr0=0.001,lrf=0.001,exist_ok=True,pretrained=True ,deterministic=False,translate=0.00,scale=0.025,mosaic=0.00,mixup=0.0,cls=6,box=90,dfl=9.0,close_mosaic=18,shear=0.0,erasing=0,perspective=0.0,flipud=0,fliplr=0,copy_paste=0,optimizer='AdamW',cos_lr=True)

**Comment by glenn-jocher** [comment]
It seems like an issue with the worker setting. Please ensure your system supports the specified number of workers and check for any resource limitations. If the problem persists, consider opening an issue on GitHub for further investigation.
