### ISSUE TITLE
Yolo11n TFLite INT8 prediction inconsistent

### ISSUE THREAD

**Issue by afg-gatv** [ultralytics/ultralytics#17073]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict, Export

### Bug

Hello! I am trying to use Yolo11n in a light processing device which requires TFLite format and INT8 quantification to be accelerated. 

Following the  Ultralytics [Export](https://docs.ultralytics.com/modes/export/#how-do-i-enable-int8-quantization-when-exporting-my-yolo11-model) documentation, I exported the model from the original yolo11n weights, into TFLite format, with a fixed image size of 384x640 and quantizied to INT8 as follows in CLI: 

`yolo export model=yolo11n.pt format=tflite imgsz='384,640' int8=True`

No issues found here, logs are as follows: 

```
Ultralytics 8.3.15 🚀 Python-3.10.15 torch-2.4.1+cu121 CPU (Intel Core(TM) i9-10900 2.80GHz)
WARNING ⚠️ INT8 export requires a missing 'data' arg for calibration. Using default 'data=coco8.yaml'.
YOLO11n summary (fused): 238 layers, 2,616,248 parameters, 0 gradients, 6.5 GFLOPs

PyTorch: starting from 'yolo11n.pt' with input shape (1, 3, 384, 640) BCHW and output shape(s) (1, 84, 5040) (5.4 MB)

TensorFlow SavedModel: starting export with tensorflow 2.17.0...

ONNX: starting export with onnx 1.17.0 opset 19...
ONNX: slimming with onnxslim 0.1.35...
ONNX: export success ✅ 0.8s, saved as 'yolo11n.onnx' (10.2 MB)
TensorFlow SavedModel: collecting INT8 calibration images from 'data=coco8.yaml'
Scanning /media/gatv-geno/Data-disk/MULTISPECTRAL/Code/Ours/GitLab/datasets/coco8/labels/val.cache... 4 images, 0 backgrounds, 0 corrup
TensorFlow SavedModel: WARNING ⚠️ >300 images recommended for INT8 calibration, found 4 images.
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.22.3...
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1729175257.820388   30482 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1729175258.585400   30482 tf_tfl_flatbuffer_helpers.cc:392] Ignored output_format.
W0000 00:00:1729175258.585426   30482 tf_tfl_flatbuffer_helpers.cc:395] Ignored drop_control_dependency.
I0000 00:00:1729175259.193143   30482 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
W0000 00:00:1729175259.721816   30482 tf_tfl_flatbuffer_helpers.cc:392] Ignored output_format.
W0000 00:00:1729175259.721834   30482 tf_tfl_flatbuffer_helpers.cc:395] Ignored drop_control_dependency.
I0000 00:00:1729175260.464466   30482 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
W0000 00:00:1729175261.011011   30482 tf_tfl_flatbuffer_helpers.cc:392] Ignored output_format.
W0000 00:00:1729175261.011029   30482 tf_tfl_flatbuffer_helpers.cc:395] Ignored drop_control_dependency.
W0000 00:00:1729175263.431482   30482 tf_tfl_flatbuffer_helpers.cc:392] Ignored output_format.
W0000 00:00:1729175263.431497   30482 tf_tfl_flatbuffer_helpers.cc:395] Ignored drop_control_dependency.
W0000 00:00:1729175263.998332   30482 tf_tfl_flatbuffer_helpers.cc:392] Ignored output_format.
W0000 00:00:1729175263.998347   30482 tf_tfl_flatbuffer_helpers.cc:395] Ignored drop_control_dependency.
W0000 00:00:1729175264.527150   30482 tf_tfl_flatbuffer_helpers.cc:392] Ignored output_format.
W0000 00:00:1729175264.527166   30482 tf_tfl_flatbuffer_helpers.cc:395] Ignored drop_control_dependency.
TensorFlow SavedModel: export success ✅ 24.2s, saved as 'yolo11n_saved_model' (29.4 MB)

TensorFlow Lite: starting export with tensorflow 2.17.0...
TensorFlow Lite: export success ✅ 0.0s, saved as 'yolo11n_saved_model/yolo11n_int8.tflite' (2.8 MB)

Export complete (24.4s)
Results saved to /home/gatv-geno
Predict:         yolo predict task=detect model=yolo11n_saved_model/yolo11n_int8.tflite imgsz=384,640 int8 
Validate:        yolo val task=detect model=yolo11n_saved_model/yolo11n_int8.tflite imgsz=384,640 data=/usr/src/ultralytics/ultralytics/cfg/datasets/coco.yaml int8 WARNING ⚠️ non-PyTorch val requires square images, 'imgsz=[384, 640]' will not work. Use export 'imgsz=640' if val is required.
Visualize:       https://netron.app
💡 Learn more at https://docs.ultralytics.com/modes/export
```

Then, I am trying to use these weights to predicts over an existing image, but I find the same issue when running on the example images. The CLI command used is: 

`yolo detect predict model='yolo11n_saved_model/yolo11n_int8.tflite' imgsz=384,640 int8`

Every time I run exactly the same command line, I obtain different output images containing great number of false positive detections with confidence 1.0. Usually, the first time I run the CLI line I get the correct predictions, but I cannot reproduce it a second time. Some of the results are: 

![zidane](https://github.com/user-attachments/assets/e596d8e5-f704-4bbd-ab23-7eda8a0cec6f)
![bus](https://github.com/user-attachments/assets/361fbecb-1b85-4da3-b6df-62429f24eeb2)
![zidane](https://github.com/user-attachments/assets/0e826ed3-ffaf-4343-a57b-efd0b06f69c8)
![bus](https://github.com/user-attachments/assets/381034c6-ca58-4c47-95f4-e3dbaacdef5f)
![zidane](https://github.com/user-attachments/assets/35b5a53d-d01d-4d78-a411-18b7151b3d30)
![bus](https://github.com/user-attachments/assets/42a052aa-84dd-47b0-894c-5fc4274c56dd)

Logs obtained with no errors or issues as follows: 

```
WARNING ⚠️ 'source' argument is missing. Using default 'source=/home/gatv-geno/anaconda3/envs/ultralytics/lib/python3.10/site-packages/ultralytics/assets'.
Ultralytics 8.3.15 🚀 Python-3.10.15 torch-2.4.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11172MiB)
Loading yolo11n_saved_model/yolo11n_int8.tflite for TensorFlow Lite inference...
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

image 1/2 /home/gatv-geno/anaconda3/envs/ultralytics/lib/python3.10/site-packages/ultralytics/assets/bus.jpg: 384x640 9 persons, 1 car, 1 airplane, 2 trains, 1 traffic light, 9 stop signs, 3 sheeps, 1 elephant, 4 frisbees, 1 toilet, 52.6ms
image 2/2 /home/gatv-geno/anaconda3/envs/ultralytics/lib/python3.10/site-packages/ultralytics/assets/zidane.jpg: 384x640 15 persons, 5 cars, 3 trucks, 12 stop signs, 4 parking meters, 4 birds, 10 sheeps, 1 elephant, 7 frisbees, 1 mouse, 50.0ms
Speed: 11.5ms preprocess, 51.3ms inference, 0.9ms postprocess per image at shape (1, 3, 384, 640)
Results saved to runs/detect/predict17
💡 Learn more at https://docs.ultralytics.com/modes/predict
```

I reviewed the raw output of the model by doing my own prediction script, and I found the same issue, there are many false positive predictions with a confidence of 1.0. Any idea of what is going on and how to solve it? 

Thanks a lot!

### Environment

Ultralytics 8.3.15 🚀 Python-3.10.15 torch-2.4.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11172MiB)
Setup complete ✅ (20 CPUs, 31.2 GB RAM, 270.6/365.6 GB disk)

OS                  Linux-5.15.0-124-generic-x86_64-with-glibc2.31
Environment         Linux
Python              3.10.15
Install             pip
RAM                 31.19 GB
Disk                270.6/365.6 GB
CPU                 Intel Core(TM) i9-10900 2.80GHz
CPU count           20
GPU                 NVIDIA GeForce GTX 1080 Ti, 11172MiB
GPU count           1
CUDA                12.1

numpy               ✅ 1.26.4>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 11.0.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.4.1>=1.8.0
torchvision         ✅ 0.19.1>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.9>=2.0.0
torch               ✅ 2.4.1!=2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

yolo export model=yolo11n.pt format=tflite imgsz='384,640' int8=True
yolo detect predict model='yolo11n_saved_model/yolo11n_int8.tflite' imgsz=384,640 int8

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Skillnoob** [comment]
When using a exported int8 model you should use the `_full_integer_quant.tflite` version and you don't need to add int8 to your prediction call.

**Comment by afg-gatv** [comment]
I tried exporting as: 

`yolo export model=yolo11n.pt format=edgepu imgsz='384,640'`

to obtain the _yolo11n_full_integer_quant.tflite_ model, and predicting as: 

`yolo detect predict model='yolo11n_saved_model/yolo11n_full_integer_quant.tflite' imgsz=384,640`

The issue this way is that there is no prediction in any case, as claimed in this other issue: [https://github.com/ultralytics/ultralytics/issues/1185#issue-1601132801](url)

Any other ideas?

**Comment by Skillnoob** [comment]
You're supposed to export to tflite, not edgetpu

**Comment by afg-gatv** [comment]
If I export as I was doing before: 

` yolo export model=yolo11n.pt format=tflite imgsz='384,640' int8=True` 

I get the following output models: `saved_model.pb, yolo11n_float16.tflite, yolo11n_float32.tflite and yolo11n_int8.tflite`

Only by running `yolo export model=yolo11n.pt format=edgepu imgsz='384,640'` I got `_full_integer_quant.tflite`

Is there other way to export it to get the full integer quant not corrupted?

**Comment by Skillnoob** [comment]
Ah, I forgot regular tflite export doesn't generate that file, its the _int8 one you need sorry. You can try different tensorflow versions. From my experience some are broken.

**Comment by ambitious-octopus** [comment]
Hey guys, this seems a problem with non-squared image size. This works fine:
```python
from ultralytics import YOLO
model = YOLO('yolo11n.pt')
model.export(format='tflite', imgsz=384, int8=True)
model = YOLO('yolo11n_saved_model/yolo11n_full_integer_quant.tflite')
res = model.predict(imgsz=384)
res[0].plot(show=True)
```
I'm investigating.

**Comment by ambitious-octopus** [comment]
Hey @Skillnoob @afg-gatv created a PR with a possible fix.
