### ISSUE TITLE
When the YOLO11 model is converted to tflite and quantized to INT8, there is no result when running

### ISSUE THREAD

**Issue by fsamekl** [ultralytics/ultralytics#17070]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

The first question is that when the YOLO11 model is converted to tflite and INT8 is running, there are no errors, and it stops running directly.
The second issue is that when converting directly to tflite without using INT8, it takes several runs to successfully convert.
The main issue is that the first problem cannot be converted to INT8 now. I need to use INT8 on my Android platform. Thank you
<img width="1016" alt="1729514134818" src="https://github.com/user-attachments/assets/90bdca32-0378-49d2-b83c-d1ddb21495f5">

### Environment

Ultralytics 8.3.13 🚀 Python-3.10.0 torch-2.4.1+cu118 CUDA:0 (NVIDIA GeForce RTX 2070, 8192MiB)
Setup complete ✅ (48 CPUs, 31.9 GB RAM, 74.7/130.1 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.10.0
Install             pip
RAM                 31.88 GB
Disk                74.7/130.1 GB
CPU                 Intel Xeon E5-2678 v3 2.50GHz
CPU count           48
GPU                 NVIDIA GeForce RTX 2070, 8192MiB
GPU count           2
CUDA                11.8

numpy               ✅ 1.24.3>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.4.1+cu118>=1.8.0
torchvision         ✅ 0.19.1+cu118>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.9>=2.0.0
torch               ✅ 2.4.1+cu118!=2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

from ultralytics import YOLO

if __name__ == '__main__':

    model = YOLO(r"C:\Users\q\Desktop\ultralytics-main\runs\detect\train\weights\best.pt")
    model.export(format="tflite",data=r"C:\Users\q\Desktop\ultralytics-main\datasets\coco128-cx.yaml",int8=True)
    model = YOLO("yolo11n_saved_model/yolo11n_full_integer_quant.tflite")
    res = model.predict()
    res[0].show()

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@fsamekl it seems you're encountering issues with INT8 quantization for TFLite. Please ensure your dataset is representative for calibration during conversion. For detailed guidance, refer to the TFLite integration documentation: https://docs.ultralytics.com/integrations/tflite/. If the issue persists, consider testing with a smaller dataset to isolate the problem.
