### ISSUE TITLE
Counting using tracking 

### ISSUE THREAD

**Issue by sivaji123256** [ultralytics/ultralytics#1715]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi @glenn-jocher @Laughing-q @AyushExel ,I was trying to count based on the track ids.I tried to modify the predict.py to add a counter based on the track ids. But, counting seems like happening for every batch and it becomes zero again and starting again.
I have added counter in the following function :
def write_results(self, idx, results, batch) in  class SegmentationPredictor(DetectionPredictor) in predict.py 
Any suggestions will help me in developing this. Thanks in advance.

**Comment by glenn-jocher** [comment]
@sivaji123256 hi, based on your description, it sounds like the counter you implemented is being reset after each batch of predictions. One approach you could consider is creating a dictionary to store the count for each unique track id, and then incrementing the count for that track id each time it is detected in a new batch. 

You may also want to consider using a persistent storage method, such as a database or file, to store the counts if you need to retain the count data between runs of the script. 

I hope this helps! Let me know if you have any further questions or if there is anything else I can assist you with.

**Comment by Laughing-q** [comment]
@sivaji123256 how about counting ids outside? something like this:
```python
from collections import defaultdict
count = defaultdict(int)
results = model.track(source=0, stream=True)
for result in results:
    boxes = result.boxes
    frame = result.orig_img
    for box in boxes:
        id = box.id
        count[id] += 1
```

**Comment by Sasek-11** [comment]
Thanks for your great work and activate help alwasys! 
Could I know how to save the tacking results ? I added the save_txt= true, but the output txt.files don't have the ID infromation for each frame/image. Sorry, my question may be not elegent, since I am just new to yolov8. I would appreciate to your kind help.
