### ISSUE TITLE
Export Onnx int8, don't really export in int8

### ISSUE THREAD

**Issue by davy-blavette** [ultralytics/ultralytics#17158]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

I have a classification model trained with yolov8 that I want to export to ut8, I do : 

```
            model = YOLO(self.file_handler.model_path)
            params = self.get_params()
            model.export(**params)

    def get_params(self):
        return {
            format': “onnx”,
            ‘data’: self.data,
            dynamic': True,
            ‘imgsz’: self.imgsz,
            ‘task’: self.get_task(),
            ‘opset’: 8,
            ‘int8’: self.int8
        }
```

Exported model with parameters: 

`{ ‘format’: ‘onnx’, ‘data’: ‘/AI_Workspace/Projects/C46/datasets’, ‘dynamic’: True, ‘imgsz’: 352, ‘task’: ‘classify’, ‘opset’: 8, ‘int8’: True}`

The export seems to run smoothly and I have no errors:

```
YOLOv8n-cls summary (fused): 73 layers, 1,437,442 parameters, 0 gradients, 3.3 GFLOPs
PyTorch: starting from ‘/AI_Workspace/Projects/C46/datasets/run/weights/C46.pt’ with input shape (1, 3, 352, 352) BCHW and output shape(s) (1, 2) (2.8 MB)
ONNX: starting export with onnx 1.16.2 opset 8...
ONNX: export success ✅ 0.1s, saved as ‘/AI_Workspace/Projects/C46/datasets/run/weights/C46.onnx’ (5.5 MB)
Export complete (1.3s)
Results saved to /AI_Workspace/Projects/C46/datasets/run/weights
Predict:         yolo predict task=classify model=/AI_Workspace/Projects/C46/datasets/run/weights/C46.onnx imgsz=352 int8
Validate:        yolo val task=classify model=/AI_Workspace/Projects/C46/datasets/run/weights/C46.onnx imgsz=352 data=/AI_Workspace/Projects/C46/datasets int8
```

but then I check the signatures and quantization and nothing changes, everything remains in FP32....

```
            ‘Quantization": {
                ‘has_quantization_nodes": false,
                ‘has_int8_weights": false
            }
```

This doesn't work.

### Environment

Ultralytics YOLOv8.2.91 🚀 Python-3.12.5 torch-2.4.1+cu118 CPU (Intel Core(TM) i7-8700 3.20GHz)
YOLOv8n-cls summary (fused): 73 layers, 1,437,442 parameters, 0 gradients, 3.3 GFLOPs

### Minimal Reproducible Example

```
            model = YOLO(self.file_handler.model_path)
            params = self.get_params()
            model.export(**params)

    def get_params(self):
        return {
            format': “onnx”,
            ‘data’: self.data,
            dynamic': True,
            ‘imgsz’: self.imgsz,
            ‘task’: self.get_task(),
            ‘opset’: 8,
            ‘int8’: self.int8
        }
```

Exported model with parameters: 

`{ ‘format’: ‘onnx’, ‘data’: ‘/AI_Workspace/Projects/C46/datasets’, ‘dynamic’: True, ‘imgsz’: 352, ‘task’: ‘classify’, ‘opset’: 8, ‘int8’: True}`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
ONNX export doesn't support `int8`. You can find the list of supported args in the docs (the `Arguments` column)

https://docs.ultralytics.com/modes/export/#export-formats

**Comment by davy-blavette** [comment]
humm.....this link it's for YOLO11 but I use Yolov8 here https://github.com/ultralytics/ultralytics/issues/8980 they say it's possible with yolov8.

**Comment by glenn-jocher** [comment]
For YOLOv8, int8 quantization is supported with TensorRT. Please try exporting using TensorRT for int8 quantization. If you need further assistance, feel free to ask!

**Comment by davy-blavette** [comment]
Ok, no problem, I'll use tensorRT, but it's a bit confusing because yolo returns the int8 information with the onnyx export "model=/AI_Workspace/Projects/C46/datasets/run/weights/C46.onnx imgsz=352 int8" so it looks like it worked...

**Comment by glenn-jocher** [comment]
Thank you for pointing that out. The message might be misleading, but int8 quantization is supported with TensorRT, not ONNX. Let us know if you need further assistance with TensorRT!
