### ISSUE TITLE
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

### ISSUE THREAD

**Issue by matthewdwatkins** [ultralytics/ultralytics#17168]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

Training attempts on any dataset result in this error:

```
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to YOLO11x-seg-benchmark-mps/YOLO11x-seg-benchmark-mps7
Starting training for 3 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/2306 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/Users/mwatkins/Documents/Benchmarking/train.py", line 14, in <module>
    results = model.train(
              ^^^^^^^^^^^^
  File "/Users/mwatkins/Library/Caches/pypoetry/virtualenvs/benchmarking-cBuHTsDm-py3.12/lib/python3.12/site-packages/ultralytics/engine/model.py", line 803, in train
    self.trainer.train()
  File "/Users/mwatkins/Library/Caches/pypoetry/virtualenvs/benchmarking-cBuHTsDm-py3.12/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "/Users/mwatkins/Library/Caches/pypoetry/virtualenvs/benchmarking-cBuHTsDm-py3.12/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 393, in _do_train
    self.scaler.scale(self.loss).backward()
  File "/Users/mwatkins/Library/Caches/pypoetry/virtualenvs/benchmarking-cBuHTsDm-py3.12/lib/python3.12/site-packages/torch/_tensor.py", line 581, in backward
    torch.autograd.backward(
  File "/Users/mwatkins/Library/Caches/pypoetry/virtualenvs/benchmarking-cBuHTsDm-py3.12/lib/python3.12/site-packages/torch/autograd/__init__.py", line 347, in backward
    _engine_run_backward(
  File "/Users/mwatkins/Library/Caches/pypoetry/virtualenvs/benchmarking-cBuHTsDm-py3.12/lib/python3.12/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

### Environment

OS                  macOS-15.0.1-arm64-arm-64bit
Environment         Darwin
Python              3.12.7
Install             pip
RAM                 64.00 GB
Disk                453.4/926.4 GB
CPU                 Apple M2 Ultra
CPU count           24
GPU                 None
GPU count           None
CUDA                None

numpy               ✅ 2.1.2>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 11.0.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.5.0>=1.8.0
torchvision         ✅ 0.20.0>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 6.1.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.9>=2.0.0
torch               ✅ 2.5.0!=2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

```python
from ultralytics import YOLO

NAME = "YOLO11x-seg-benchmark-mps"
PROJECT = "YOLO11x-seg-benchmark-mps"
EPOCHS = 3
DATASET_PATH = "coco8-seg.yaml"
IMAGE_SIZE = 640
DEVICE = "mps"

model = YOLO("yolo11x-seg.pt").load("yolo11n.pt")
model.info()

results = model.train(
    name=NAME,
    project=PROJECT,
    data=DATASET_PATH,
    epochs=EPOCHS,
    imgsz=IMAGE_SIZE,
    device=DEVICE,
    workers=16,
    mask_ratio=1
)
```

### Additional

I'm using `pyenv` and `poetry` for env management. The code in question is run using `poetry run python train.py`

The contents of `pyproject.toml` are:
```toml
[tool.poetry]
name = "benchmarking"
version = "0.1.0"
description = "Benchmarking tool"
authors = ["Matthew Watkins"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ultralytics = "^8.3.23"
labelme2yolo = "^0.2.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by matthewdwatkins** [comment]
I was able to get it to run by turning off `device='mps'`, so I think this probably is a bug.

**Comment by Y-T-G** [comment]
Could be a PyTorch bug. Try downgrading PyTorch.

**Comment by matthewdwatkins** [comment]
Thank you. It was a PyTorch bug and downgrading from 2.5.0 to 2.3.0 resolved it.

**Comment by glenn-jocher** [comment]
Glad to hear that resolved the issue. If you have any more questions, feel free to ask!

**Comment by saserbest** [comment]
Same issue while training model on Apple Silicon. Isn't Ultralytics compatible with PyTorch >2.5.0 ?

**Comment by Y-T-G** [comment]
It seems more like a PyTorch bug, than Ultralytics. You can open an issue on PyTorch repo.
