### ISSUE TITLE
How can I use my predictions to generate new training data for my model?

### ISSUE THREAD

**Issue by Camerabiologist** [ultralytics/ultralytics#1718]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have built a model for detecting a particular plant species, based on a ~7.5k of hand-labeled pictures in different classes. The model works reasonably well for detecting the species, but has issues with false positives by detecting the wrong species, for instance. Due to the complexity and variation of plants as an object, I expect that I will need to grow my annotation dataset further, but if I can avoid annotating thousands of extra pictures, I would certainly prefer that. 

This leads me to my question. If I were to run prediction with my model on a dataset of let's say 10k images of my desired plant species, could I let the predictions be saved alongside the predicted bounding boxes, but as a YOLO-compatible .txt label? The goal would then be to add the new images and labels to my training data set and in that way iteratively improve my model. Of course I would need to check and see how accurate and useful the labels actually are, but even this would greatly reduce my workload. 

Is this possible and if so how can it be achieved?

Thank you very much!

**Comment by glenn-jocher** [comment]
Yes, you can definitely use your model's predictions as a starting point for generating YOLO-compatible annotations, which can then be added to your training dataset. This process is known as "pseudo-labeling" or "self-training" and can help improve your model iteratively with less manual annotation effort. However, you should be cautious about the quality of these automatically generated annotations and consider verifying them before adding them to your training dataset.

**Comment by Camerabiologist** [comment]
Great! Thanks for your response. I will try it out and see if the annotation quality is good enough for this purpose. If I'm correct, passing `save_txt=True` should do the trick in a prediction, is that right?

**Comment by Camerabiologist** [comment]
This thread can be closed. I figured out how to use my predictions as new labels.

**Comment by glenn-jocher** [comment]
@Camerabiologist glad to hear you figured it out! Feel free to reach out if you have any more questions or issues with YOLOv8.
