### ISSUE TITLE
Another format for segments results (list of xy coordinates)

### ISSUE THREAD

**Issue by dh031200** [ultralytics/ultralytics#1726]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Currently Masks.segments provide normalized coorinates.

```python
# ultralytics/yolo/engine/results.py:275
    @property
    @lru_cache(maxsize=1)
    def segments(self):
        return [
            ops.scale_segments(self.masks.shape[1:], x, self.orig_shape, normalize=True)
            for x in ops.masks2segments(self.masks)]
```

If I want to use result with opencv (ex. cv2.fillPoly, polylines) then I need demormalized xy format.

How about segments provide 2 formats like a bbox (xyxy, xywh)?

### Use case

We can use it more easily.
```python
for s in seg_results:
    # Before
    canv = np.full((h,w,3),(0,0,0),dtype=np.uint8)
    polyline = s.masks.segments[0]
    polyline[:,0] *= w
    polyline[:,1] *= h
    cv2.polylines(canv,[polyline.astype(np.int32)], True,(255,255,255))
    cv2.imwrite('polyline_n.png',canv)

    # After
    canv = np.full((h,w,3),(0,0,0),dtype=np.uint8)
    polyline = s.masks.segments_xy[0]
    cv2.polylines(canv,[polyline], True,(255,255,255))
    cv2.imwrite('polyline_xy.png',canv)
```

### Additional

Sorry for my bad naming sense. I think you should change the name.

```python
    @property
    @lru_cache(maxsize=1)
    def segments_xy(self):
        return [
            np.int32(ops.scale_segments(self.masks.shape[1:], x, self.orig_shape, normalize=False))
            for x in ops.masks2segments(self.masks)]
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@dh031200 PR merged! Thank you for your contributions!
