### ISSUE TITLE
a question about parameter loading

### ISSUE THREAD

**Issue by Christian-lyc** [ultralytics/ultralytics#17283]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I’m facing a weird problem. Here I use the yolov8n model to run object detection, it gives reasonable results with predicted bonding box. Later I rebuilt the model without reading that yaml file, because with random weights, it gives bonding box with 0 value inside. And then the weird thing happens, when I load parameters from the pretrained ultralytics model to the rebuilt model, it gives empty bounding box. And I randomly checked the maximum loaded parameters of the rebuilt model and the pretrained one, it’s same. I don’t know what happened, but I’m sure it the problem of parameter transfer problem. Here’s the loading code I used. Hope anyone can help me. Thank you so much, I really appreciate it.
rebuilt_model.conv1.load_state_dict(pretrain_model.model._modules[‘model’][0].state_dict())
rebuilt_model.conv2.load_state_dict(pretrain_model.model._modules[‘model’][1].state_dict())
rebuilt_model.c2f1.load_state_dict(pretrain_model.model._modules[‘model’][2].state_dict())
rebuilt_model.conv3.load_state_dict(pretrain_model.model._modules[‘model’][3].state_dict())
rebuilt_model.c2f2.load_state_dict(pretrain_model.model._modules[‘model’][4].state_dict())
rebuilt_model.conv4.load_state_dict(pretrain_model.model._modules[‘model’][5].state_dict())
rebuilt_model.c2f3.load_state_dict(pretrain_model.model._modules[‘model’][6].state_dict())
…
rebuilt_model.detect.load_state_dict(pretrain_model.model._modules['model'][22].state_dict())
rebuilt_model.detect.anchors=pretrain_model.model._modules['model'][22].anchors
rebuilt_model.detect.stride=pretrain_model.model._modules['model'][22].stride
rebuilt_model.detect.strides=pretrain_model.model._modules['model'][22].strides
rebuilt_model.detect.shape=pretrain_model.model._modules['model'][22].shape

**Comment by Y-T-G** [comment]
Did you try using `model.load()` to load weights?

**Comment by Y-T-G** [comment]
https://github.com/ultralytics/ultralytics/issues/16520#issuecomment-2380734866

**Comment by Christian-lyc** [comment]
Thank you so much. The problem is I rebuilt the model without loading yaml file, the names are different, besides I built it manually by simply stacking the blocks. So I can't use model.load directly I think. I think the problem lies in detection block, because without loading detection block, the model outputs bounding box with zero values.

**Comment by Christian-lyc** [comment]
I'm so sorry I made stupid mistake. I added shortcut to one c2f block, which should not be there. Sorry.

**Comment by glenn-jocher** [comment]
No worries, mistakes happen! Glad you identified the issue. If you have any more questions or need further assistance, feel free to ask.
