### ISSUE TITLE
Ubuntu system report MacOS Bug

### ISSUE THREAD

**Issue by sdreamforchen** [ultralytics/ultralytics#1728]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When I run "yolo val task=detect model=yolov8n.mlmodel imgsz=640 data=coco.yaml" I got this exception below,but my system is Ubuntu 18.04
Exception: Model prediction is only supported on macOS version 10.13 or later.

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sdreamforchen the message is correct. Inference is only supported on macOS and you are on Ubuntu, that's the entire point of the message.
