### ISSUE TITLE
CLI integration for bare metal engine on ultralytics hub

### ISSUE THREAD

**Issue by tilobormann** [ultralytics/ultralytics#17291]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I'm running my training on a couple of Jetson devices from a kubernetes cluster. 

Either on 
ultralytics/ultralytics:latest-jetson-jetpack4 (Jetson TX2 NX) or 
ultralytics/ultralytics:latest-jetson-jetpack5 (Jetson Xavier) 
depending on the device. 

When i use Ultralytics Hub I get the connection possible only for python3:

```
from ultralytics import YOLO, checks, hub
checks()

hub.login('<token>')

model = YOLO('https://hub.ultralytics.com/models/<modelID>')
results = model.train()
```
it works but only for CPU usage. when i try `model.train(device=gpu)` ot fails due to the missing support of GPU support of the pytorch package ind the container. As far as I know there is no official CUDA support from the pytorch wheels. 

But if i run a local model from the CLI then it works and the GPU (CUDA 11.4 or 10.2) will be utilized. 

**Question: Because I really want to use the HUB functionality, my question is: Is there a possibility to connect to the project in the HUB via CLI, that is adequate to the python code above or is only python possible to establish the connection?**

**Comment by UltralyticsAssistant** [comment]
👋 Hello @tilobormann, thank you for reaching out to Ultralytics 🚀! It seems you're interested in leveraging the Ultralytics Hub features with GPU support on Jetson devices. Your setup using Kubernetes and different Jetson configurations sounds intriguing!

To address your query about CLI integration with Ultralytics Hub: currently, the primary method for interfacing with the Hub is via Python, as you mentioned. If this is a 🐛 Bug Report regarding the `model.train(device=gpu)` issue, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us investigate further.

In the meantime, ensure your environment is up-to-date with the latest versions and that all dependencies are correctly installed. You can upgrade using the following command:

```bash
pip install -U ultralytics
```

Check our [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) as this might offer insights into resolving compatibility issues with CUDA and PyTorch within your Docker containers.

For more immediate assistance, feel free to join the vibrant Ultralytics community on [Discord](https://ultralytics.com/discord) 🎧, or engage in discussions on [Discourse](https://community.ultralytics.com).

An Ultralytics engineer will also review your issue and provide additional assistance. Thank you for your patience! 🌟

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are running successfully. These tests verify the correct operation of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) across various platforms including macOS, Windows, and Ubuntu.

**Comment by Y-T-G** [comment]
What's the exact error you're getting?

**Comment by tilobormann** [comment]
When I try to override the HUB-default parameter I get immediately 

```
>>> results = model.train(device=0)
WARNING ⚠️ using HUB training arguments, ignoring local training arguments.
``` 


And it starts training with the CPU. When when I setup GPU usage already in the HUB (advanced settings) then I get this error:

```
root@ultralytics-demo:/ultralytics# python3
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ultralytics import YOLO, checks, hub
>>> checks()
Ultralytics 8.3.23 🚀 Python-3.8.10 torch-2.4.1 CPU (ARMv8 Processor rev 0 (v8l))
Setup complete ✅ (6 CPUs, 6.7 GB RAM, 80.3/468.3 GB disk)
>>> 
>>> hub.login('6d39e24d34c784dff578423a65ae3d535ddfad9263')
Ultralytics HUB: New authentication successful ✅
True
>>> 
>>> model = YOLO('https://hub.ultralytics.com/models/9acRkGyGFiUpOxUo0dbz')
Ultralytics HUB: View model at https://hub.ultralytics.com/models/9acRkGyGFiUpOxUo0dbz 🚀
>>> results = model.train()
New https://pypi.org/project/ultralytics/8.3.25 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.23 🚀 Python-3.8.10 torch-2.4.1 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ultralytics/ultralytics/engine/model.py", line 796, in train
    self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
  File "/ultralytics/ultralytics/engine/trainer.py", line 103, in __init__
    self.device = select_device(self.args.device, self.args.batch)
  File "/ultralytics/ultralytics/utils/torch_utils.py", line 192, in select_device
    raise ValueError(
ValueError: Invalid CUDA 'device=0' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: all
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.
```

When i start a training with a local downloaded model from the CLI it works with `device=0`.

**Comment by Y-T-G** [comment]
> torch-2.4.1 CPU

It says torch CPU. What does it say when you train with CLI?

**Comment by tilobormann** [comment]
```
root@ultralytics-demo:/ultralytics# yolo export model=yolov8n.pt format=engine device=0
Ultralytics 8.3.23 🚀 Python-3.8.10 torch-2.1.0a0+41361538.nv23.06 CUDA:0 (Xavier, 6833MiB)
YOLOv8n summary (fused): 168 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs

PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

ONNX: starting export with onnx 1.17.0 opset 17...
====== Diagnostic Run torch.onnx.export version 2.1.0a0+41361538.nv23.06 =======
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ONNX: slimming with onnxslim 0.1.36...
ONNX: export success ✅ 5.9s, saved as 'yolov8n.onnx' (12.2 MB)

TensorRT: starting export with TensorRT 8.5.2.2...
```

and there we are. 



![image](https://github.com/user-attachments/assets/f1a1a145-0d3b-4faf-9fa6-2166f067ca46)

I tried to install the torch-2.1.0a0+41361538.nv23.06 wheel in the container for testing (for a modified Dockerfile later) but run into issues with torchvision.

**Comment by Y-T-G** [comment]
Can you run `which yolo` and `which python3` in the terminal?

**Comment by tilobormann** [comment]
```
root@ultralytics-demo:/ultralytics# which yolo
/usr/local/bin/yolo
root@ultralytics-demo:/ultralytics# which python3
/usr/bin/python3
```

**Comment by Y-T-G** [comment]
Run `/usr/local/bin/python3` and use `ultralytics` in that

**Comment by tilobormann** [comment]
good idea but there is no python3 in /usr/local/bin. I did not find any virtual environment as well. the yolo file in that folder redirects the call to IPython. 

```
root@ultralytics-demo:/usr/local/bin# cat yolo
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from ultralytics.cfg import entrypoint
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(entrypoint())
root@ultralytics-demo:/usr/local/bin# 
```

any other ideas?

**Comment by Y-T-G** [comment]
Are these the same environment?

> Ultralytics 8.3.23 🚀 Python-3.8.10 torch-2.4.1 CPU (ARMv8 Processor rev 0 (v8l))

> Ultralytics 8.3.23 🚀 Python-3.8.10 torch-2.1.0a0+41361538.nv23.06 CUDA:0 (Xavier, 6833MiB)

How do they have different PyTorch versions if they're the same env?

**Comment by tilobormann** [comment]
Honestly I have no idea, maybe someone from ultralytics can answer this.

**Comment by Y-T-G** [comment]
How many torch versions does `pip list` show?

**Comment by tilobormann** [comment]
thats even more confusing, it's only one: 
`torch                        2.0.0a0+ec3941ad.nv23.2`
but this is also different.

**Comment by glenn-jocher** [comment]
@tilobormann it seems like there might be a discrepancy between the environments or installations. I recommend ensuring that the same Python environment is used for both CLI and Python script executions. You might want to check your PATH settings and ensure that the correct Python and PyTorch installations are being referenced.

**Comment by Y-T-G** [comment]
What's the location of `torch` in `pip show torch`?

And what's the location when you `import torch; print(torch.__file___)`

**Comment by tilobormann** [comment]
first of all: @Y-T-G : thanks for your support and the effort to solve this 

> What's the location of torch in pip show torch?

```
root@ultralytics-demo:/ultralytics# pip show torch
Name: torch
Version: 2.0.0a0+ec3941ad.nv23.2
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /usr/local/lib/python3.8/dist-packages
Requires: networkx, sympy, typing-extensions
Required-by: torchaudio, torchvision, ultralytics, ultralytics-thop
```

> And what's the location when you import torch; print(torch.__file__)

```
root@ultralytics-demo:/ultralytics# python3
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch; print(torch.__file__)
/usr/local/lib/python3.8/dist-packages/torch/__init__.py
```

> pip3 show torch

```
root@ultralytics-demo:/ultralytics# pip3 show torch
Name: torch
Version: 2.0.0a0+ec3941ad.nv23.2
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /usr/local/lib/python3.8/dist-packages
Requires: networkx, sympy, typing-extensions
Required-by: torchaudio, torchvision, ultralytics, ultralytics-thop
root@ultralytics-demo:/ultralytics# 
```

**Comment by Y-T-G** [comment]
What foes `cat /usr/local/lib/python3.8/dist-packages/torch/version.py` show?

**Comment by tilobormann** [comment]
`What foes cat /usr/local/lib/python3.8/dist-packages/torch/version.py show?`
```
root@ultralytics-demo:/ultralytics# cat /usr/local/lib/python3.8/dist-packages/torch/version.py
__version__ = '2.0.0a0+ec3941ad.nv23.02'
debug = False
cuda = '11.4'
git_version = '0bd8be0232e78dc7b9c66c316ef39977c1c7c0ed'
hip = None
root@ultralytics-demo:/ultralytics# 
```

**Comment by tilobormann** [comment]
>What if you import torch; print(torch.__version__)?

```
root@ultralytics-demo:/ultralytics# python3
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch; print(torch.__version__)
2.0.0a0+ec3941ad.nv23.02
>>> torch.cuda.is_available()
False
```
it's the same version. but somehow CUDA is not available.

**Comment by Y-T-G** [comment]
Run the export command shown here:

https://docs.nvidia.com/deeplearning/frameworks/install-pytorch-jetson-platform/index.html#verify

**Comment by tilobormann** [comment]
other than in the post i had to change to path to `/usr/lib/llvm-10/lib` since llvm-8 is not existing. But I cannot see any errors

```
root@ultralytics-demo:/ultralytics# export LD_LIBRARY_PATH=/usr/lib/llvm-10/lib:$LD_LIBRARY_PATH
root@ultralytics-demo:/ultralytics# python3
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
False
>>> exit()
```

**Comment by Y-T-G** [comment]
You can try reinstalling PyTorch based on that guide.

**Comment by tilobormann** [comment]
Over the weekend I tried several reinstallations but without success, I even updated the CUDA drivers to 12.1 on the machine itself. But the python environment always returns false for the torch.cuda.is_available(). 
Since this is the default container from ultralytics I'm going to open a bug report on this.

**Comment by glenn-jocher** [comment]
Thank you for your efforts. Please proceed with opening a bug report on the Ultralytics GitHub repository, providing all relevant details for further investigation.

**Comment by tilobormann** [comment]
closing this issue and opening new bug report #17345

**Comment by glenn-jocher** [comment]
Thank you for updating us. We'll continue the discussion and address the issue in the new bug report #17345.
