### ISSUE TITLE
When will the 1280 size model be launched?

### ISSUE THREAD

**Issue by M15-3080** [ultralytics/ultralytics#1730]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When will the 1280 size model be launched?
such as：yolov8s6.pt,yolov8m6.pt,yolov8l6.pt,yolov8x6.pt
I am looking forward to your reply,thanks.

**Comment by Overtrued** [comment]
yes， when

**Comment by glenn-jocher** [comment]
@Overtrued we're working hard on new model trainings! Right now we are retraining improved Pose models, then our server is scheduled for Ray Tune experiments which may take up to a month, afterwich we should be able to train P6 models with improved hyperparameters.

**Comment by r8420** [comment]
@glenn-jocher Since it has been 2 months, could you possibly give an estimate on when the new models will be done?

**Comment by monkeycc** [comment]
+1

**Comment by glenn-jocher** [comment]
@monkeycc thank you for your interest in YOLOv8! We appreciate your support. The YOLOv8 team is working diligently to bring you the best models possible. While we don't have an exact timeline for when the new models will be released, we are actively working on it and will make an announcement as soon as they are ready. We appreciate your patience and thank you for your continued support.
