### ISSUE TITLE
Add more option for plot

### ISSUE THREAD

**Issue by dh031200** [ultralytics/ultralytics#1731]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I added 4 options to the Results.plot() function to give users a little more flexibility.
```python
"""
Args:
    img (numpy.ndarray): Plot to another image. if not, plot to original image.
    hide_labels (bool): Whether to show the label of bounding boxes.
    hide_boxes (bool): Whether to show the bounding boxes.
    hide_masks (bool): Whether to show the masks.
"""
```
### In my case:
I have 2 different models  (detect, segmentation). And I want plot both result to one image.
And I want hide label of segment masks like below image.
![image](https://user-images.githubusercontent.com/66017052/229039552-c40943fa-8027-4220-8e98-528fdf08c6ad.png)

### Use case

property seg.masks.segments_xy was created by #1727

```python
detect_model = YOLO("yolov8l-obstacles.pt")
seg_model = YOLO("yolov8l-road-seg.pt")
src = 'sample.mp4'
save_path = 'output.mp4'
w, h, fps = 1920, 1080, 60
writer = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc(*'mp4v'), fps, (w, h))
colors = Colors()

detect_results = detect_model.track(source=src, verbose=False, tracker="botsort.yaml", stream=True)
seg_results = seg_model.predict(source=src, verbose=True, retina_masks=True, agnostic_nms=True, stream=True)

# Before
for detect, seg in zip(detect_results, seg_results):
    img = detect.plot()
    canvas = np.full((h,w,3),(0,0,0),dtype=np.uint8)
    for c,s in zip(seg.boxes.cls, seg.masks.segments_xy):  
        cv2.fillPoly(canvas, [s], colors(c))
    output = cv2.addWeighted(img,1,canvas,0.7,0)
    writer.write(output)

# After
for detect, seg in zip(detect_results, seg_results):
    img = detect.plot()
    seg_img = seg.plot(img=img, hide_boxes=True)
    writer.write(seg_img)
```

### Additional

I don't know if the explanation in the docstring is easy to understand. Because my English writing skills are not good 😂
I think it will be useful when using yolov8 in combination with something else.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@dh031200 thanks for the PR. I'm work on integrating this into 8.0.60.
