### ISSUE TITLE
YOLOv10 TFLite Int8 quantization does not work

### ISSUE THREAD

**Issue by Hozzu** [ultralytics/ultralytics#17327]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

I exported YOLOv10 to TFLite using the following command.

```python
model = YOLO("yolo10n.pt")
model.export(format="tflite", int8=True, half=False, data="coco128.yaml")

```

The yolov10n_float32.tflite and yolov10n_float16.tflite work, but not yolov10n_full_integer_quant.tflite,  yolov10n_int8.tflite, and  yolov10n_integer_quant.tflite.

For example, yolo detect val model=yolov10n_int8.tflite data=coco128.yaml gives mAP 0.

### Environment

Ultralytics 8.3.27 🚀 Python-3.11.10 torch-2.5.0+cu124 CUDA:0 (NVIDIA GeForce RTX 4090, 24102MiB)

### Minimal Reproducible Example

```python
model = YOLO("yolo10n.pt")
model.export(format="tflite", int8=True, half=False, data="coco128.yaml")
```

cd yolov10n_saved_model/
yolo detect val model=yolov10n_int8.tflite data=coco128.yaml

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Hozzu, thank you for sharing your experience with Ultralytics 🚀! We're glad you're exploring the TFLite export functionalities. An Ultralytics engineer will review your issue and assist you soon. 

In the meantime, please ensure you're using the latest version of the `ultralytics` package as updates often contain valuable fixes and improvements:

```bash
pip install -U ultralytics
```

If you have not already done so, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) that can help us pinpoint the issue with your `tflite` export results showing `mAP 0`.

For more detailed guidance, including our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/), you might find visiting our [Docs](https://docs.ultralytics.com) helpful. For various examples and questions, you can check out our [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage sections.

Join our vibrant Ultralytics community where you can have real-time discussions on [Discord](https://ultralytics.com/discord) 🎧, engage in thoughtful exchanges on [Discourse](https://community.ultralytics.com), or join our [Subreddit](https://reddit.com/r/ultralytics) for broader community insights.

## Environments

Make sure your environment is set up correctly. YOLO can be run in any of these verified, up-to-date environments with all dependencies installed:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM ([GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/))
- **Amazon** Deep Learning AMI ([AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/))
- **Docker Image** ([Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/)) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

You can check the current status of all our tests on the [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule), which validates all YOLO modes and tasks on different platforms daily and with every code update.

Thank you for being part of the Ultralytics community!✨

**Comment by Y-T-G** [comment]
Something wrong with the bounding boxes.

![results_bus.jpg](https://github.com/user-attachments/assets/0c8ce62e-0954-4f67-aaf2-71f31d972d6b)

**Comment by ambitious-octopus** [comment]
@Y-T-G @Hozzu, investigating, looks like floating point models work correctly:

```python
from ultralytics import YOLO
model = YOLO("yolov10n.pt")
model.export(format="tflite", int8=True, data="coco8.yaml")
model = YOLO("yolov10n_saved_model/yolov10n_float32.tflite")
res = model.predict()
res[0].show()
```
