### ISSUE TITLE
The impact of image translation on YOLOv8 pose keypoints.

### ISSUE THREAD

**Issue by Ichiruchan** [ultralytics/ultralytics#17374]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello everyone, I am currently facing a situation. When I use my self-trained YOLO-Pose model to predict objects and keypoints on the same image, the results are identical after ten predictions. However, when I translate the image (the image size does not change) and then predict, I find that there is a 1-2 pixel deviation in the keypoints after restoring the results to the original coordinate system. I noticed that there is a default translation augmentation of 0.1 during training, and theoretically, my translation amount does not exceed this percentage. I want to know why this happens and whether this situation is unavoidable.

**Comment by Y-T-G** [comment]
Can you provide examples?

**Comment by Ichiruchan** [comment]
> Can you provide examples?

In my image, there are two objects, each with one key point. I need to calculate the distance between the key points of the two objects. As mentioned earlier, this distance changes when I move the image horizontally or vertically. 
```
for i in range(10):
    height, width = img.shape[:2]

    max_translation = 30
    tx = random.randint(-max_translation, max_translation)
    ty = random.randint(-max_translation, max_translation)
    translation_matrix = np.float32([[1, 0, tx], [0, 1, ty]])
    translated_image = cv2.warpAffine(img, translation_matrix, (width, height))

    imgsz = auto_cal_size(cur_img=translated_image)
    results = yolo_model.predict(translated_image, imgsz=imgsz, conf=0.2, iou=0.5)
    ... .... ...
```
The result:
![image](https://github.com/user-attachments/assets/c141ffe1-1a96-44c7-9293-2c3247237473)

**Comment by Y-T-G** [comment]
You mean inferring on the image after moving it? Then that's normal. The model wouldn't output the exact same point if you move it.

**Comment by Ichiruchan** [comment]
> You mean inferring on the image after moving it? Then that's normal. The model wouldn't output the exact same point if you move it.

I only performed translations on the images in the x and y directions, so their absolute coordinates change. I used to think that their relative positions (distances) would remain unchanged. Are you saying that their relative positions might still vary slightly due to different inputs?

**Comment by Y-T-G** [comment]
You can get different just by changing the interpolation mode you use for resizing. Deep learning models are sensitive to the input.

**Comment by Ichiruchan** [comment]
> You can get different results just by changing the interpolation mode you use for resizing. Deep learning models are sensitive to the input.

Actually, I didn't change my image size. I just translated image horizontally and vertically and added black border.  So I don't think there is any interpolation.

**Comment by Y-T-G** [comment]
What I mean is deep learning models are so sensitive to input that even changing the interpolation method affects the output. Translating is much more significant.

**Comment by Ichiruchan** [comment]
Thank you very much for your reply. I will close this issue. Wishing you a wonderful day!
