### ISSUE TITLE
object contour detection with yolov8-seg

### ISSUE THREAD

**Issue by Zijian-Wu** [ultralytics/ultralytics#1737]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to use yolov8-seg to do object contour detection as shown in the figure below, how can I achieve this?
<img width="176" alt="seg" src="https://user-images.githubusercontent.com/126188358/229141377-65b2d882-1eb1-44a2-b1fe-6357f616f382.png">

**Comment by glenn-jocher** [comment]
👋 Hello @RogerPeng, 

To implement object contour detection using YOLOv8, we recommend the following steps:

1. Train a YOLOv8 model on your dataset using `--device 'cpu'` and the `--resume` flag if you wish to continue training from a checkpoint
2. Extract image-level features from the final convolutional layer of the model
3. Use the extracted features to generate a contour image for each object using a suitable method such as the Canny edge detection in OpenCV [cv2.Canny()](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_canny/py_canny.html)

Please note that the exact implementation details will depend on your specific use case and dataset.

Let me know if you have any further questions!

**Comment by Zijian-Wu** [comment]
> 👋 Hello @Zijian-Wu, thanks for asking!
> 
> See our full Segmentation Guide at https://docs.ultralytics.com/tasks/segment/

I have thoroughly read the documentation. Well, what I meant is **not to apply a mask to the detected objects** like semantic segmentation or instance segmentation. Instead, I'm interested in simply **outlining the outer contours of the detected objects** while **keeping the colors within the contours unchanged**. Can yolov8-segment achieve this?

**Comment by glenn-jocher** [comment]
Thank you for clarifying, @Zijian-Wu. At present, YOLOv8-seg doesn't support object contour detection, but object segmentation. We recommend you check out the semantic segmentation methods mentioned in the documentation to achieve the outlined contour of the detected objects like the one you linked to. Many image processing libraries like OpenCV have edge detection that you can use in conjunction with the segmentation of objects detected by YOLOv8.  Let me know if this helps or if I can assist with anything else.

**Comment by Zijian-Wu** [comment]
> Thank you for clarifying, @Zijian-Wu. At present, YOLOv8-seg doesn't support object contour detection, but object segmentation. We recommend you check out the semantic segmentation methods mentioned in the documentation to achieve the outlined contour of the detected objects like the one you linked to. Many image processing libraries like OpenCV have edge detection that you can use in conjunction with the segmentation of objects detected by YOLOv8. Let me know if this helps or if I can assist with anything else.

Ok, I see. Thank you very much for your patient response!
