### ISSUE TITLE
Batch size issue in Benchmark function with Multi-GPU (AutoBatch with batch<1 not supported for Multi-GPU training)

### ISSUE THREAD

**Issue by fazrigading** [ultralytics/ultralytics#17370]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Val, Multi-GPU, Other

### Bug

Hi, this is the first time I opened an issue to a repo as dev student.
I encountered an error where batch size = 1 is an issue in benchmarks.py.

Here is the error information:
```
ValueError                                Traceback (most recent call last)
Cell In[6], line 4
      1 from ultralytics.utils.benchmarks import benchmark
      3 # Benchmark on GPU
----> 4 benchmark(model="my-trained-yolov8l-on-custom-dataset.pt", 
      5           data="dataset.yaml", imgsz=640, half=True, device="cuda:0,1")

File /opt/conda/lib/python3.10/site-packages/ultralytics/utils/benchmarks.py:86, in benchmark(model, data, imgsz, half, int8, device, verbose, eps)
     84 pd.options.display.max_columns = 10
     85 pd.options.display.width = 120
---> 86 device = select_device(device, verbose=False)
     87 if isinstance(model, (str, Path)):
     88     model = YOLO(model)

File /opt/conda/lib/python3.10/site-packages/ultralytics/utils/torch_utils.py:207, in select_device(device, batch, newline, verbose)
    205 if n > 1:  # multi-GPU
    206     if batch < 1:
--> 207         raise ValueError(
    208             "AutoBatch with batch<1 not supported for Multi-GPU training, "
    209             "please specify a valid batch size, i.e. batch=16."
    210         )
    211     if batch >= 0 and batch % n != 0:  # check batch_size is divisible by device_count
    212         raise ValueError(
    213             f"'batch={batch}' must be a multiple of GPU count {n}. Try 'batch={batch // n * n}' or "
    214             f"'batch={batch // n * n + n}', the nearest batch sizes evenly divisible by {n}."
    215         )

ValueError: AutoBatch with batch<1 not supported for Multi-GPU training, please specify a valid batch size, i.e. batch=16.
```

How to reproduce the problem:
```python
from ultralytics.utils.benchmarks import benchmark

benchmark(model="my-trained-yolov8l-on-custom-dataset.pt", data="dataset.yaml", imgsz=640, half=True, device="cuda:0,1")
```

According to this benchmarks.py in main version:
https://github.com/ultralytics/ultralytics/blob/d0abd95f95211851cb37004510f03191ac8d12be/ultralytics/utils/benchmarks.py#L86

Batch size is hardcoded to always equals 0 in line 86. Please fix this issue.
I also have some questions if you could answer:
1. Why the batch size value is 0 in the `benchmark` function?
2. What is the most fit value for batch size when using Multi-GPU if there are 2xT4 GPUs?
3. Will it be possible for user to modify the batch size from the `benchmark` function args?

### Environment

```
Ultralytics 8.3.27 🚀 Python-3.10.14 torch-2.4.0 CUDA:0 (Tesla T4, 15095MiB)
Setup complete ✅ (4 CPUs, 31.4 GB RAM, 5933.9/8062.4 GB disk)
```

### Minimal Reproducible Example

```python
from ultralytics.utils.benchmarks import benchmark

benchmark(model="yolov8l.pt", data="dataset.yaml", imgsz=640, half=True, device="cuda:0,1")
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
You can't use multi-GPU for benchmarking or inference. Only pass a single GPU.

**Comment by fazrigading** [comment]
> You can't use multi-GPU for benchmarking or inference. Only pass a single GPU.

Thank you for the information! I suggest the README on Benchmark should be updated where it mentions multi-GPU setup:
https://github.com/ultralytics/ultralytics/blob/4453ddab93c390c11c9f8bb8d90a761a4cec3342/docs/en/modes/benchmark.md?plain=1#L105

**Comment by glenn-jocher** [comment]
@fazrigading thank you for the helpful suggestion. I've created an issue to update the benchmark documentation to clarify that multi-GPU is not supported for benchmarking. Feel free to submit a PR to help improve the docs if you'd like to contribute directly. For benchmarking, please use a single GPU device like `device='cuda:0'`.
