### ISSUE TITLE
tracker_id=None 

### ISSUE THREAD

**Issue by Umar-Saeed-97** [ultralytics/ultralytics#1739]
- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I'm encountering an issue with the model.track() function where I am not receiving any tracking IDs for the detections that the model is making.

### Reproducible Example

        line_start = sv.Point(329, 406)
        line_end = sv.Point(925, 406)

        line_counter = sv.LineZone(start = line_start, end = line_end)

        line_annotator = sv.LineZoneAnnotator(thickness = 2,
                                      text_thickness = 1,
                                      text_scale = 0.5)
                                      
        box_annotator = sv.BoxAnnotator(thickness = 1,
                                text_thickness = 1,
                                text_scale = 0.5)

        model = YOLO('yolov8l.pt')

        out = cv2.VideoWriter('test1.mp4', cv2.VideoWriter_fourcc(*'mp4v'), 30, (1280, 720))

        for result in model.track(source='/content/drive/MyDrive/Vehicle Tracking/Data/test1.mp4', show=True, stream=True, 
                                                tracker="botsort.yaml", agnostic_nms=True):
        
            frame = result.orig_img

            detections = sv.Detections.from_yolov8(result)
   
            labels = [f"{tracker_id} {model.model.names[class_id]} {confidence:0.2f}"
                  for _, confidence, class_id, tracker_id 
                  in detections]
    
            line_counter.trigger(detections)
     
            line_annotator.annotate(frame, line_counter)

            frame = box_annotator.annotate(scene = frame,
                                       detections = detections,
                                       labels = labels)
        
            out.write(frame)

        out.release()

**Comment by glenn-jocher** [comment]
👋 Hello @Umar-Saeed-97. The `track()` function in YOLOv8 returns a `Detection` object which contains the detection boxes, class IDs, and confidence scores for each object detected in an input image or video frame. If you are not receiving any tracking IDs, it is most likely because you have not specified a tracker in the `track()` function. 

In your example code, you have specified the "botsort.yaml" tracker which should return tracking IDs for each detected object. Please verify that the "botsort.yaml" file is located in the correct directory and that the file contains valid YAML code for the desired tracker.

**Comment by Umar-Saeed-97** [comment]
> 

I'm not sure what you're referring to (I installed the libraries through pip command).
![image_2023-03-31_204112217](https://user-images.githubusercontent.com/87208133/229166916-36ae138e-c4d3-4718-acf0-f98bc3f3eeb1.png)

**Comment by glenn-jocher** [comment]
👋 Hello @Umar-Saeed-97. My apologies if my previous response was unclear. I wasn't referring to the installation of the `ultralytics` package, which can indeed be done via pip. Instead, I was suggesting that you verify that the "botsort.yaml" tracker exists in the directory where your code is located, and that the file contains the correct YAML code for the desired tracker.

In your example code, your `track()` function call includes the `tracker="botsort.yaml"` argument, which tells YOLOv8 to use the "`botsort.yaml`" file as a tracker. Please verify that the file exists in the directory where your Python script is located, and that the file contains valid YAML code for the tracker.

**Comment by Umar-Saeed-97** [comment]
The file doesn't exist in the main directory, where can I find it?

**Comment by Umar-Saeed-97** [comment]
@glenn-jocher The issue still persists. I also tried changing this part of the code but it didn't help

        for result in model.track(source='/content/drive/MyDrive/Vehicle Tracking/Data/test1.mp4', show=True, stream=True, 
                                               agnostic_nms=True):

**Comment by Umar-Saeed-97** [comment]
@glenn-jocher Hey! Problem solved, the following code fixed the issue:

        if result.boxes.id is not None:
           detections.tracker_id = result.boxes.id.cpu().numpy().astype(int)
