### ISSUE TITLE
saving results

### ISSUE THREAD

**Issue by Abshir4** [ultralytics/ultralytics#1740]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

    model = YOLO('yolov8x-seg.pt')
    results = model.predict(source="images", imgsz=1500, boxes=True, conf=0.55, classes=[0, 2])
  
I would like to save the image if conf=0.55. And is it possible to save the whole results to like a json file?

**Comment by AyushExel** [comment]
To save the results, you can pass `save=True` with model.predict. Currently save_json is available for validation. Prediction supports saving results in the txt file be passing `save_txt=True`. In your case, the command will be:
```
results = model.predict(source="images", imgsz=1500, boxes=True, conf=0.55, classes=[0, 2], save=True, save_txt=True)
```

**Comment by Abshir4** [comment]
> 

](https://github.com/ultralytics/ultralytics/issues/1740#issuecomment-1492822268)

> To save the results, you can pass `save=True` with model.predict. Currently save_json is available for validation. Prediction supports saving results in the txt file be passing `save_txt=True`. In your case, the command will be:
> 
> ```
> results = model.predict(source="images", imgsz=1500, boxes=True, conf=0.55, classes=[0, 2, 3], save=True, save_txt=True)
> ```
> 
> I've opened a PR that adds predict argument usage to docs - #1744

thank you for your time
 save=True saves all images i just want to save the images who got 55 in conf or more.


example:

when i run it i get

image 5/224 C:\python\yolov8\images\4362.jpg: 768x1504 3 cars, 1 truck, 5188.7ms

is it possible to get this result in 4362.txt?

now i get in label, 4362.txt :

2 0.644282 0.521277 0.643617~ and alot of more numbers.....

**Comment by pderrenger** [comment]
@Abshir4 understood! To save only the images with a confidence greater than or equal to 0.55, and their respective results in a JSON format, you can modify the `predict` function as follows:

```
results = model.predict(source="images", imgsz=1500, conf=0.55, save=True, save_txt=True, save_conf=True)
```

This will save the images with a confidence of 0.55 or higher and their corresponding results in a JSON file, while also saving the results in the default text format.

Let me know if there is anything else I can assist you with!

**Comment by theyurtman** [comment]
this code is working fine, saving pics and labels but not saving conf, what should ı do?

model = YOLO("./runs/detect/train6/weights/best.pt")
if __name__ == "__main__":
    results = model.predict(
        source="./dataset_for_yolo/test/",
        imgsz=640,
        conf=0.5,
        save=True,
        save_txt=True,
        save_conf=True,
    )

**Comment by glenn-jocher** [comment]
@theyurtman hi there! 😊 It looks like you're almost there. If you're aiming to save the confidence scores along with the labels, your current setup should technically work as intended with `save_conf=True`. However, if the confidence scores are not appearing in your saved text files, please ensure you're using the latest version of the Ultralytics YOLOv8 repository, as updates and bug fixes are regularly made.

If after updating, you're still facing the issue, it might be helpful to manually iterate over the `results` object and save the desired data in your preferred format. Here's a quick example of how you could extract and save the confidence scores along with the labels:

```python
for img in results.imgs:
    labels, confs = results.pred[img]
    with open(f"{img.stem}_conf.txt", "w") as f:
        for label, conf in zip(labels, confs):
            f.write(f"{label} {conf}\n")
```

This is a simplified example, so you might need to adjust it based on your exact requirements. If you're still stuck, feel free to share more details, and we'll be happy to help further!
