### ISSUE TITLE
Docs Feedback for Predict page at /modes/predict/

### ISSUE THREAD

**Issue by leodemachado** [ultralytics/ultralytics#1741]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hello, thanks for this amazing repo. We should be able to see/read the complete list of attributes of the predict() function. You gave extensive information on source attribute, but no idea on the rest.

### Use case

Every one could take the best from predict function like changing save directory, altering output configurations, etc.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Thanks for the feedback. Opened a PR to fix this

**Comment by glenn-jocher** [comment]
@leodemachado @AyushExel PR merged #1744 merged for 8.0.60 this weekend!
