### ISSUE TITLE
Exporting model as half precision torchscript doesn't reduce the model size by half

### ISSUE THREAD

**Issue by AnikiFan** [ultralytics/ultralytics#17454]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/user-attachments/assets/da22fb66-1b21-4984-be48-d789161642a0)
The models exported as full precision torchscript and half precision torchscripts respectively have almost the same model size.
However, when I export the model i written in pytorch into half precision torchscript format model, the model size was reduced by half compared with the model exported as full precision torchscript.
Is there any other way to reduce the yolo model size exported as torchscipt?

**Comment by UltralyticsAssistant** [comment]
👋 Hello @AnikiFan, thank you for bringing this to our attention 🚀! We understand you're experiencing an issue with model size when exporting as half precision torchscript.

If this is indeed a 🐛 Bug Report, we'd appreciate it if you could provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to aid our debugging efforts. This helps us understand the issue more clearly and offer a more precise solution.

In the meantime, please ensure your environment is up-to-date. To do this, upgrade to the latest `ultralytics` package with the necessary [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment and verify with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/), as the issue may have already been addressed in a newer version:

```bash
pip install -U ultralytics
```

For further assistance, explore our comprehensive [Docs](https://docs.ultralytics.com) where you'll find many [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) examples. You can also join our community for more interactive support. For real-time help, visit [Discord](https://ultralytics.com/discord) 🎧, or for deeper discussions, head over to [Discourse](https://community.ultralytics.com). Feel free to post questions and learn together with others on our [Subreddit](https://reddit.com/r/ultralytics).

An Ultralytics engineer will also review your issue soon and provide further assistance. Thanks for your patience and collaboration! 😊

**Comment by Y-T-G** [comment]
The original `.pt` model is already FP16. Exporting to half precision (FP16) will not decrease the size because it has the same precision as the original.

**Comment by AnikiFan** [comment]
thanks, but why it will become to two times larger when I export it to half precision torchscript format

**Comment by Y-T-G** [comment]
Torchscript export doesn't support `half` precision. So it's using FP32.

https://docs.ultralytics.com/modes/export/#export-formats

**Comment by UltralyticsAssistant** [comment]
A potential fix for this issue has been merged in [PR #18185](https://github.com/ultralytics/ultralytics/pull/18185) 🎉! Here's a summary of the key changes introduced in this PR:

### Key Updates:
- **Improved Argument Validation**: A new `validate_args` function has been added to ensure only supported arguments are passed during export, reducing the likelihood of errors.
- **Updated Export Format Configurations**: Specific configurations now support features like `half`, `int8`, and `batch`, improving clarity and usability.
- **Refined Workflows**: The export and benchmarking processes now leverage enhanced validations, making the process more robust and predictable.
- **Version Bump**: The library version has been updated from `8.3.52` to `8.3.53`.

These updates aim to enhance the export functionality, reduce errors, and improve overall usability. If this addresses the issue you were experiencing, we encourage you to test it out!

### How to Test:
1. Install the latest changes directly from the `main` branch:
   ```bash
   pip install git+https://github.com/ultralytics/ultralytics.git@main
   ```
2. OR wait until the next official PyPI release to test the updated version.

### Request for Feedback:
Please let us know if the changes in this PR resolve your issue. If the problem persists or you encounter any new challenges, feel free to provide additional feedback. 

Thank you for reporting this issue 🙏! Your input is invaluable in helping us improve. 🚀

**Comment by xx025** [comment]
This issue has been closed for a long time. In my opinion, this should be a bug, not "torchscript" not supporting FP16.

In production I use: https://github.com/ultralytics/ultralytics/blob/1117381474da745a28a539cad6b144aa2983919c/ultralytics/engine/exporter.py#L438

Change to (onnx or jit) , export the torchscript model to FP16 version
```python
if self.args.half and (onnx or jit ) and self.device.type != "cpu":
     im, model = im.half(), model.half()  # to FP16
````

**Comment by Y-T-G** [comment]
@xx025 You can open a PR for it.

I don't think it's a bug because Ultralytics doesn't claim to support FP16 export for TorchScript. It would only be a bug if Ultralytics claimed to support it. What you outlined is a feature request.

**Comment by Y-T-G** [comment]
@xx025 Can you open a PR for it?

[This PR](https://github.com/ultralytics/ultralytics/pull/20313) added `half` as supported, but they didn't make the change in the code to actually support `half`.

**Comment by UltralyticsAssistant** [comment]
Good news! A potential fix for this issue has been merged in the pull request Expand FP16 export support for ultralytics 8.3.208. Full details here: [PR #22316 on GitHub](https://github.com/ultralytics/ultralytics/pull/22316) by @glenn-jocher with contributions from @phillies.

Key updates that may resolve this issue:
- FP16 (half) export behavior is now safer and more predictable:
  - `half=True` is applied on GPU for ONNX and TorchScript (JIT).
  - CPU exports automatically disable FP16 and emit a clear warning.
- JIT now aligns with ONNX in FP16 handling.
- Expanded ONNX FP16 export test coverage to validate these cases.
- Clearer docs on where `half=True` is supported, plus friendlier download error messaging.
- Version bumped to 8.3.208.

How to test the fix:
- Upgrade to the latest version with:
  ```
  pip install -U ultralytics>=8.3.208
  ```
- Or install the latest from the main branch:
  ```
  pip install git+https://github.com/ultralytics/ultralytics.git@main
  ```
- Alternatively, wait for the next official PyPI release if not yet available in your environment.

Quick example to verify:
```python
from ultralytics import YOLO

model = YOLO("yolo11n.pt")

# GPU: FP16 ONNX export (supported)
model.export(format="onnx", half=True, device=0)

# CPU: FP16 will auto-disable with a warning (expected)
model.export(format="onnx", half=True, device="cpu")
```

Feedback on whether this resolves the issue would be greatly appreciated. Thanks for reporting this, and feel free to share more details if anything persists. 🙏
