### ISSUE TITLE
Yolo with mlflow

### ISSUE THREAD

**Issue by AJITKUMAR130012** [ultralytics/ultralytics#17467]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

from ultralytics import YOLO
import mlflow

# Load a model
model = YOLO("yolo11n.pt")

experiment_name = "yolo1"
mlflow.set_experiment(experiment_name)
# Train the model

from mlflow import set_tracking_uri, start_run, log_metric

# Ensure the tracking URI points to the correct backend
set_tracking_uri("/home/eflag2/Documents/Ajit/yolo_pipeline/src/components/mlruns")

with mlflow.start_run():
    mlflow.log_param("Start", 1)
    train_results = model.train(
        data="/home/eflag2/Documents/Ajit/yolo_pipeline/data/male-female/data.yaml",  # path to dataset YAML
        epochs=1,  # number of training epochs
        imgsz=640,  # training image size
        device=0,  # device to run on, i.e. device=0 or device=0,1,2,3 or device=cpu
    )
    #mlflow.log_param("Model info", model.info())
    print("="*50)
    print("Train Result")

    print(f"Fitness score: {train_results.fitness}")
    mlflow.log_param("Fitness score:", train_results.fitness)

### Additional

![image](https://github.com/user-attachments/assets/315e4dae-4b85-4557-85fa-ccef931dfb35)
MLflow: WARNING ⚠️ Failed to initialize: Run 'fe8ce4d65fba4eccb5d6e34e71246468' not found

![image](https://github.com/user-attachments/assets/d5f35cf5-ba69-4087-b192-9c3dd87145a6)
mlflow.exceptions.MlflowException: Run 'fe8ce4d65fba4eccb5d6e34e71246468' not found

MLFLOW version:

![image](https://github.com/user-attachments/assets/f4bd8185-d203-4cae-84e4-ffc9161ea5e9)

Python version:
![image](https://github.com/user-attachments/assets/07de95df-064b-473d-b795-fb5edee408a0)

yolo version:
yolo11

**Comment by Y-T-G** [comment]
MLFlow should initialize automatically. You don't need to manually initialize. Just run training as usual

**Comment by AJITKUMAR130012** [comment]
I want to store the result in the mlflow for each time training, that why i have initialized the MLFlow in our code

**Comment by AJITKUMAR130012** [comment]
@Y-T-G , Thanks got it

**Comment by AJITKUMAR130012** [comment]
Solved

**Comment by glenn-jocher** [comment]
Great to hear that you solved the issue! If you have any more questions or need further assistance, feel free to ask.
