### ISSUE TITLE
working with yolov11_obb with Deap learning accelerator support , getting error 

### ISSUE THREAD

**Issue by Adicontrol** [ultralytics/ultralytics#17470]
when i a converting custom yolov11l model to engine using DLA support it is working good.
but when it comes to custom_yolov11l_obb.pt to custom_yolov11l_obb.engine it showing follwoing error while inferencing.
can you help in this to resolve this error

![obb_with_dla_issue](https://github.com/user-attachments/assets/9397da09-c9f5-46de-bbe5-a3ff17b7e0bb)

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Adicontrol, thank you for your interest in Ultralytics 🚀! We understand you are encountering issues when converting a custom model with Deep Learning Accelerator (DLA) support, particularly with the custom_yolov11l_obb model. 

For bug-related issues like this 🐛, we'd appreciate it if you could provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to assist in diagnosing the problem. This will help our team understand the context and specifics of your error better.

In the meantime, please ensure your environment is up to date. Upgrade to the latest ultralytics package along with all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a **Python>=3.8** environment with **PyTorch>=1.8**:

```bash
pip install -U ultralytics
```

For further support, join the Ultralytics community on [Discord](https://ultralytics.com/discord) 🎧 for real-time assistance, or engage with other users on [Discourse](https://community.ultralytics.com) and [Subreddit](https://reddit.com/r/ultralytics).

Your issue will be reviewed by an Ultralytics engineer soon. In the meantime, updating your environment might fix the problem. If the badge below indicates green, our [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing, ensuring stable operations of all YOLO modes and tasks:

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

**Comment by Adicontrol** [comment]
import cv2
from ultralytics import YOLO


model = YOLO("custom_yolo11_obb_weights/yolo11_obb_best.pt")
model.export(format="engine", device="dla:0", half=True)  # Use DLA core 0, adjust if necessary
# model.export(format="engine") 

trt_model = YOLO("custom_yolo11_obb_weights/yolo11_obb_best.engine")

Its converting .pt to engine using DLA support but while inferencing i am getting error 
Loading custom_yolo11_obb_weights/yolo11_obb_best.engine for TensorRT inference...

following is my error 
 File "/home/jetson-isaac/Desktop/yolov11_project/realtime.py", line 33, in <module>
    results = trt_model(resized_frame)
  File "/home/jetson-isaac/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 176, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/jetson-isaac/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 554, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/jetson-isaac/.local/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 169, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/jetson-isaac/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/jetson-isaac/.local/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 275, in stream_inference
    s[i] += self.write_results(i, Path(paths[i]), im, s)
  File "/home/jetson-isaac/.local/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 335, in write_results
    string += f"{result.verbose()}{result.speed['inference']:.1f}ms"
  File "/home/jetson-isaac/.local/lib/python3.10/site-packages/ultralytics/engine/results.py", line 663, in verbose
    log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "
KeyError: 1
 can you help in this to resolve this

**Comment by Y-T-G** [comment]
The warning clearly says in your screenshot to specify the task while loading the model

**Comment by Y-T-G** [comment]
`trt_model = YOLO("custom_yolo11_obb_weights/yolo11_obb_best.engine", task="obb")`

**Comment by Adicontrol** [comment]
thank you resolved . i didn't noticed this warning

**Comment by glenn-jocher** [comment]
You're welcome! I'm glad to hear the issue is resolved. If you have any more questions, feel free to ask.
