### ISSUE TITLE
False positives disregarded in the evaluation in val() function

### ISSUE THREAD

**Issue by menna-ibrahim** [ultralytics/ultralytics#17478]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Val

### Bug

In ultralytics/models/yolo/segment/val.py
https://github.com/ultralytics/ultralytics/blob/0fa1d7d5a6bd78e4ac0814e071a470314d2bbe37/ultralytics/models/yolo/segment/val.py#L132-L139

This if-condition prevents the false positives from being counted in case the model detects objects in an image with no labels in its ground truth. This results in an incorrect confusion matrix.

### Environment

Ultralytics 8.3.27 🚀 Python-3.11.10 torch-2.4.1+cu121 CPU (Intel Xeon Gold 6248R 3.00GHz)
Setup complete ✅ (40 CPUs, 376.5 GB RAM, 4.1/188.3 GB disk)

### Minimal Reproducible Example

```            
            # Evaluate
            if nl:
                stat["tp"] = self._process_batch(predn, bbox, cls)
                stat["tp_m"] = self._process_batch(
                    predn, bbox, cls, pred_masks, gt_masks, self.args.overlap_mask, masks=True
                )
                if self.args.plots:
                    self.confusion_matrix.process_batch(predn, bbox, cls)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Thank you for pointing this out. We appreciate your feedback on the evaluation logic. If you have a proposed solution, feel free to submit a pull request for review.
