### ISSUE TITLE
Error while prediction in Python

### ISSUE THREAD

**Issue by shahnupur1901** [ultralytics/ultralytics#1748]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I pass an input image to my YOLO segmentation model and this was working till yesterday, with the labels and image stored in the folder. 
However, I started getting this error today.
![image](https://user-images.githubusercontent.com/67814929/229271335-4f39abf5-076a-4656-8447-4a3c08d90d6d.png)
I've made no changes to the code since yesterday and would like to know what should be changed.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@shahnupur1901 thanks for the bug report. I will take a look.

**Comment by glenn-jocher** [comment]
@shahnupur1901 fixed in https://github.com/ultralytics/ultralytics/pull/1753/commits/eeaf7266652950f9b4804ffd83d1c6897cc9a848 for publishing with 8.0.60 tomorrow. Let us know if this resolves your issue or if you have any other problems with YOLOv8!
