### ISSUE TITLE
MLflow Error: "NoneType has no attribute log.param"

### ISSUE THREAD

**Issue by rafaelvp-db** [ultralytics/ultralytics#1751]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Integrations

### Bug

When using `mlflow.autolog()`, `mlflow.autolog(disable=True) or `mlflow.start_run`, we get the following error when running the code on Databricks:

`MLflow Error: "NoneType has no attribute log.param"`

This is due to the fact that we set the `run` object to `None` in the `except` block. If you are running the experiment on Databricks, experiments will be automatically named `YOLOv8`, which will trigger an exception, since these names are invalid - consequently, `run` will be set to None and then the code tries to log params on top of an empty run object.

Code excerpt:

```python
try:
            run, active_run = mlflow, mlflow.start_run() if mlflow else None
            if active_run is not None:
                run_id = active_run.info.run_id
                LOGGER.info(f'{prefix}Using run_id({run_id}) at {mlflow_location}')
        except Exception as err:
            LOGGER.error(f'{prefix}Failing init - {repr(err)}')
            LOGGER.warning(f'{prefix}Continuing without Mlflow')
            run = None

        run.log_params(vars(trainer.model.args))
```

After the change I've done, we first check if there's already an active run; we create a new one if that's not the case. This solves the problem.

```python
try:
            active_run = mlflow.active_run()
            if not active_run:
                active_run = mlflow.start_run(experiment_id = experiment.experiment_id)
            run_id = active_run.info.run_id
            LOGGER.info(f'{prefix}Using run_id({run_id}) at {mlflow_location}')
            mlflow.log_params(vars(trainer.model.args))
        except Exception as err:
            LOGGER.error(f'{prefix}Failing init - {repr(err)}')
            LOGGER.warning(f'{prefix}Continuing without Mlflow')
```

### Additional

I have the fixed the bug and tested locally. Currently working, will submit a PR to solve this issue.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by rafaelvp-db** [comment]
Submitted PR https://github.com/ultralytics/ultralytics/pull/1752 to fix this

**Comment by glenn-jocher** [comment]
👍 Thanks for the contribution, @rafaelvp-db! Our team will review the pull request and merge it soon. In the meantime, if you have any other questions or suggestions, feel free to ask here or in the pull request.
