### ISSUE TITLE
 How we can plot the confusion matrix, F1 curve,pr curve, etc on classification models as of detection models its just saved result.csv and weights on yoloV8??? 

### ISSUE THREAD

**Issue by shumshersubashgautam** [ultralytics/ultralytics#1754]
@glenn-jocher  How we can plot the confusion matrix, F1 curve,pr curve, etc on classification models??? as of detection models default just saved weights and results.csv file. I need all these metrics plots on classification models by default how we can plot any code and tutorial please suggest for the classification model??

**Comment by glenn-jocher** [comment]
@shumshersubashgautam we don't have confusion matrices for classification models, but you can implement one yourself starting from the detection confusion model base. I can't do this because I don't have the time available, but if you do this yourself please submit a PR for other users!
