### ISSUE TITLE
What are the differences between Yolov5 and Yolov8 architecture?

### ISSUE THREAD

**Issue by shayandaneshvar** [ultralytics/ultralytics#1757]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I wanted to know about the architecture of Yolov8 and how it is different from Yolov5.
I have tested both on a custom dataset for detection, and Yolov5 is performing better than V8. I would like to know more about the loss function and other details to understand why V8 performs worse than V5.

I have also searched the issues and realized that Yolov8, unlike previous models, is an anchor-free model. Is it possible to elaborate a bit on this, i.e. what was removed from v5 in v8 and what was added to achieve an anchor-free model, and what kind of anchor-free model is v8 e.g. Dense Predict or Key-Point Based?

**Comment by glenn-jocher** [comment]
@shayandaneshvar hi buddy. Many differences in architecture (split head, anchor-free, no objectness output), loss (TAL and DFL), improved accuracy, speed and size, and general simplifications everywhere, not to mention vast improvements in UI/UX for improved usability in Python and CLI.

**Comment by glenn-jocher** [comment]
@shayandaneshvar hi buddy. Many differences in architecture (split head, anchor-free, no objectness output), loss (TAL and DFL), improved accuracy, speed and size, and general simplifications everywhere, not to mention vast improvements in UI/UX for improved usability in Python and CLI.

**Comment by glenn-jocher** [comment]
@shayandaneshvar hi buddy. Many differences in architecture (split head, anchor-free, no objectness output), loss (TAL and DFL), improved accuracy, speed and size, and general simplifications everywhere, not to mention vast improvements in UI/UX for improved usability in Python and CLI.

**Comment by shayandaneshvar** [comment]
> @shayandaneshvar hi buddy. Many differences in architecture (split head, anchor-free, no objectness output), loss (TAL and DFL), improved accuracy, speed and size, and general simplifications everywhere, not to mention vast improvements in UI/UX for improved usability in Python and CLI.

Thanks for the answers @glenn-jocher. 
So, if there is no objectness output, then how do we get the confidence at the end? I can't really understand.

Sorry if I an not fully familiar with the YOLO architectures.
