### ISSUE TITLE
examples/object_tracking.ipynb report an exception "Annotator.seg_bbox() got an unexpected keyword argument 'track_label'"

### ISSUE THREAD

**Issue by relaxtheo** [ultralytics/ultralytics#17603]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Other

### Bug

I am trying the examples/object_tracking.ipynb, and it reports an exception "Annotator.seg_bbox() got an unexpected keyword argument 'track_label'"

### Environment

Ultralytics 8.3.32 🚀 Python-3.10.15 torch-2.5.1+cu124 CUDA:0 (NVIDIA GeForce RTX 3090, 24152MiB)
Setup complete ✅ (24 CPUs, 62.5 GB RAM, 2533.8/3666.4 GB disk)

### Minimal Reproducible Example

running examples/object_tracking.ipynb

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
@relaxtheo Hi, thank you for raising the issue. I have tested the existing code available at: [https://github.com/ultralytics/ultralytics/blob/main/examples/object_tracking.ipynb](https://github.com/ultralytics/ultralytics/blob/main/examples/object_tracking.ipynb), and it is working as expected.

**Note:** Please ensure that you have upgraded the Ultralytics package to the latest version by running `pip install -U ultralytics`. This should resolve your issue.

Thanks,  
The Ultralytics Team

**Comment by RizwanMunawar** [comment]
I am closing this issue for now. However, if you encounter any problems with the Ultralytics package, please don't hesitate to open a new issue. Thank you! 👍🏻
