### ISSUE TITLE
AttributeError: 'float' object has no attribute 'mosaic'

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#17608]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

[def v8_transforms(dataset, imgsz, hyp, stretch=False):
](https://github.com/ultralytics/ultralytics/blob/2ccec61b5856614b3a230d16cf80c0af894b9ce1/ultralytics/data/augment.py#L2273)

```python
from ultralytics.data.dataset import YOLODataset
dataset = YOLODataset(img_path="path/to/images", imgsz=640)
hyp = {"mosaic": 1.0, "copy_paste": 0.5, "degrees": 10.0, "translate": 0.2, "scale": 0.9}
transforms = v8_transforms(dataset, imgsz=640, hyp=hyp)
augmented_data = transforms(dataset[0])
```

 mosaic = Mosaic(dataset, imgsz=imgsz, p=hyp.mosaic)
                                            ^^^^^^^^^^
AttributeError: 'float' object has no attribute 'mosaic'

**Comment by UltralyticsAssistant** [comment]
👋 Hello @monkeycc, thanks for reaching out and sharing your query with the Ultralytics community 🚀! 

It seems like you're encountering an `AttributeError` related to the `mosaic` key in your augmentation pipeline. If you believe this is a 🐛 Bug Report, could you please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) so our team can better assist you?

While you await further assistance, make sure to explore our [Docs](https://docs.ultralytics.com) where you might find useful information related to augmentation strategies in [Python](https://docs.ultralytics.com/usage/python/) or even tackle this directly through our [CLI](https://docs.ultralytics.com/usage/cli/).

If you have any customization ❓ Questions, please include more details like your dataset examples and training logs to offer a clearer picture of your workflow. Also, ensure you're following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/) for optimal performance.

Engage with the vibrant Ultralytics community through various platforms:
- For real-time discussions, hop onto [Discord](https://ultralytics.com/discord) 🎧.
- For detailed exchanges, visit [Discourse](https://community.ultralytics.com).
- Or join ongoing conversations on our [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade

Ensure your `ultralytics` package is up-to-date with all necessary [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml), running in a [**Python>=3.8**](https://www.python.org/) environment and leveraging [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

## Environments

Consider running YOLO in one of these supported environments where dependencies like [CUDA](https://developer.nvidia.com/cuda) and [CUDNN](https://developer.nvidia.com/cudnn) are pre-installed:

- **Notebooks** with free GPU access: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VMs, per the [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMIs, per the [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**, followed through the [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/): <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

This badge indicates the current status of all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests. When green, it signifies successful checks of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) across macOS, Windows, and Ubuntu systems, performed daily and upon each commit.

An Ultralytics engineer will be with you soon to offer further assistance. Thank you for your patience and collaboration! 🌟

**Comment by Y-T-G** [comment]
`hyp` supposed to be a Namespace, not dict.

**Comment by monkeycc** [comment]
https://github.com/ultralytics/ultralytics/blob/2ccec61b5856614b3a230d16cf80c0af894b9ce1/ultralytics/data/augment.py#L2290C1-L2294C52

```python
    Examples:
        >>> from ultralytics.data.dataset import YOLODataset
        >>> dataset = YOLODataset(img_path="path/to/images", imgsz=640)
        >>> hyp = {"mosaic": 1.0, "copy_paste": 0.5, "degrees": 10.0, "translate": 0.2, "scale": 0.9}
        >>> transforms = v8_transforms(dataset, imgsz=640, hyp=hyp)
        >>> augmented_data = transforms(dataset[0])
    """
```

We should follow the official example
Is there a problem with the example

**Comment by glenn-jocher** [comment]
@monkeycc the issue with the example is that `hyp` should be a Namespace object, not a dictionary, to access attributes like `hyp.mosaic`. You can fix this by converting `hyp` to a Namespace using `from argparse import Namespace; hyp = Namespace(**hyp_dict)`.
