### ISSUE TITLE
results[0].prob is None but there's boxes?

### ISSUE THREAD

**Issue by mxlei01** [ultralytics/ultralytics#1761]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

HI All,

I've been trying to upgrade from yolov5 to yolov8, and everything seems to be the same in terms of performance except the result now returns a little bit differently.

I'm getting bounding boxes, and I'm able to plot the image using `results[0].plot(pil=True)` for this classification task.

Here's some of my results:
```
results = model(frame, imgsz=(1920, 1080))

(Pdb) results[0].boxes
ultralytics.yolo.engine.results.Boxes object with attributes:

boxes: tensor([[856.33850, 384.92340, 885.75146, 415.35544,   0.91006,  10.00000]])
cls: tensor([10.])
conf: tensor([0.91006])
data: tensor([[856.33850, 384.92340, 885.75146, 415.35544,   0.91006,  10.00000]])
id: None
is_track: False
orig_shape: tensor([1080, 1920])
shape: torch.Size([1, 6])
xywh: tensor([[871.04498, 400.13940,  29.41296,  30.43204]])
xywhn: tensor([[0.45367, 0.37050, 0.01532, 0.02818]])
xyxy: tensor([[856.33850, 384.92340, 885.75146, 415.35544]])
xyxyn: tensor([[0.44601, 0.35641, 0.46133, 0.38459]])
(Pdb) results[0].probs
(Pdb) results[0].names
{0: 'audio', 1: 'audio_box', 2: 'audio_menu', 3: 'audio_player', 4: 'audio_player_download', 5: 'audio_player_open_options', 6: 'audio_player_when_options_opened', 7: 'download_audio_button', 8: 'enter_audio', 9: 'not_a_robot_box', 10: 'not_a_robot_button', 11: 'select_all_images', 12: 'verify_button'}
```

There's names and bounding boxes, but no probs, even though the probability of predicting a class was over 80%?

**Comment by glenn-jocher** [comment]
Hi @AnGiangIT97, thanks for reaching out to us. It looks like you're not seeing any probabilities in your results object. YOLOv8's `detect()` function returns detector output by default, which includes boxes, predictions, and features.  If you would like to see the probabilities associated with each bounding box in your results object, you can set `save_conf=True` when you call `model.detect()`. This will ensure that probabilities are included in the results object returned by detect(). Additionally, you can use the `.numpy()` method to print the results in the desired format. I hope this helps, please let me know if you have any additional questions!

**Comment by mxlei01** [comment]
@glenn-jocher I tried adding in `save_conf=True` via:
`model.predict(frame, imgsz=(1920, 1080), save_conf=True)`, but I'm still not seeing any probs. If it helps I loaded the model that I previously trained using `YOLO(./best.pt)`.

**Comment by lus105** [comment]
Hi, I am facing simmilar issue. My aim is to retrieve classes of detected objects which are associated with bounding boxes. I added `save_conf=True` parameter to `result = model(image, save_conf=True)`, however `results[0].probs` member is None even when there are some detections.

**Comment by glenn-jocher** [comment]
Hi @ktnguyenuw, thanks for reaching out. If you'd like to see the probabilities associated with each bounding box in your results object, you can set `save_conf=True` when calling `model.detect()`. This will include the probabilities in the results object returned by `detect()`. Additionally, make sure the model was trained with `--data coco.yaml --img 640 --rect --nosave --evolve --weights yolov5m.pt`. Let me know if that helps!

**Comment by mxlei01** [comment]
@happydracula @glenn-jocher 
I tried doing `save_conf=True`, but there wasn't anything. However this is what I did at the end though:

```
# Inference
results: Results = model(frame, imgsz=input_size)[0]

# Get all the classes
classes: Dict[int, str] = results.names

# From the boxes get the predictions
results_with_probs: List[Tuple[Results, str]] = [(result, classes[result.boxes.cls.numpy()[0]]) for result in results]
```

It seems that `model(frame, imgsz=input_size)` outputs a list. BUT even with multiple detection boxes, it's always one size list. So the way I did it was access the `result.boxes.cls` this is a pytorch tensor 1xN where N is number of detections for the index of `results.names`. So you would get the index from `result.boxes.cls` and then map it to `results.names`.

**Comment by egorovivannn** [comment]
res[0].boxes.conf does what you want

**Comment by nandish486** [comment]
guys in my case result[0].boxes is None and operating on it raises nonetype error, if anyone can help

**Comment by glenn-jocher** [comment]
@nandish486 hello! Thank you for your question. If `result[0].boxes` is returning `None` and you're seeing a `NoneType` error when you attempt to operate on it, this could indicate that YOLOv8 was not able to detect any objects in the input image. You might want to double-check that the input image is properly formatted and that object classes are present in the image. In addition, YOLOv8's `detect()` function returns the detector output by default which includes boxes, predictions, and features. If you are seeing only a `NoneType` error for `result[0].boxes`, you could try setting `save_txt=True` when calling `model.detect()`. This will save the `result.txt` file, including bounding box coordinates and object class predictions. Let me know if that helps!

**Comment by sakhij** [comment]
Hello @glenn-jocher 
i trained classification model with yolov8
i am getting the predictions like this j 0.99, 4 0.01, 3 0.00, 0 0.00, x 0.00
i only want j 0.99 (the one with the highest probabilty) to be printed,nothing else should be printed on the terminal.

**Comment by yuhe0925** [comment]
is detect function always return the result with size of 1? I see most of the examples using results = model.detect(), which got me thinking is there situration that detect() returns more than 1 results or none result?

**Comment by glenn-jocher** [comment]
@yuhe0925 hello and thank you for your question.

The `detect()` function in YOLOv8 will always return a results object, even if no objects are detected in the input image. This results object contains detection results as well as other attributes related to the detection process.

If YOLOv8 detects multiple objects in an image, these detections will be included in the same results object. Individual detections can be accessed through attributes of the results object like `boxes`, `confidences` and `classes`.

So, while the `detect()` function will always return a single results object per input image, this object can contain multiple detections, or no detections at all if no objects were found.

I hope this answers your question. Do let me know if you need further clarification.
