### ISSUE TITLE
w"FutureWarning: 'timm.models.layers' is deprecated, should I update my imports to 'timm.layers'?"

### ISSUE THREAD

**Issue by xw-wj** [ultralytics/ultralytics#17638]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", FutureWarning)
val: Scanning D:\BaiduNetdiskDownload\yolo11-main02\GRAZPEDWRI-DX\data\labels\valid.cache... 4092 images, 3 backgrounds, 0 corrupt: 100%|██████████| 4092/4092 [00:00<?, ?it/s]
D:\anaconda3\envs\yolo11\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
D:\anaconda3\envs\yolo11\lib\site-packages\timm\models\helpers.py:7: FutureWarning: Importing from timm.models.helpers is deprecated, please import via timm.models
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", FutureWarning)

### Environment

Ultralytics 8.3.26 🚀 Python-3.9.20 torch-2.5.0 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 8188MiB)

### Minimal Reproducible Example

D:\anaconda3\envs\yolo11\lib\site-packages\timm\models\helpers.py:7: FutureWarning: Importing from timm.models.helpers is deprecated, please import via timm.models
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", FutureWarning)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
This doesn't seem `ultralytics` related. `ultralytics` doesn't use timm.

**Comment by glenn-jocher** [comment]
Yes that's correct @Y-T-G
