### ISSUE TITLE
How to get correct class names with onnx model in triton inference server without specifiying data?

### ISSUE THREAD

**Issue by KiSchnelle** [ultralytics/ultralytics#17637]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

This Issue was kind of described but never really resolved in this issue:
https://github.com/ultralytics/ultralytics/issues/8763

When exporting as onnx and running with triton inference server the classes will be 0:class0 to 998:class998 unless you specify the data.yaml in the model.predict(data=data.yaml).

This obviously is quite troublesome if a use of the inference server is not having acess to the data.yaml file path.

I have so far not found a valid way to include or export the model correctly with the class name data.

Also for the segment task, the inference will even fail without data specified.

From all the issues i found here and posts i can not find a proper solution, LLM answers are apperently failing to provide a solution.

Anyone has one?

**Comment by KiSchnelle** [comment]
Ok thank you, then i dont have to try anymore:)

**Comment by glenn-jocher** [comment]
@KiSchnelle you're welcome! If you have any more questions or need further assistance, feel free to ask.

**Comment by Y-T-G** [comment]
@KiSchnelle Triton Inference now supports automatic metadata retrieval from the server in the latest release. You can check the guide on how to store the metadata in `config.pbtxt`.

https://docs.ultralytics.com/guides/triton-inference-server/#exporting-yolo11-to-onnx-format
