### ISSUE TITLE
how to forbidden val 

### ISSUE THREAD

**Issue by gcg0210** [ultralytics/ultralytics#1764]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i want to train myown model without val datasets .however when i set val :false in default.yaml ,code did not work and still searched val path.

**Comment by lakyfarky** [comment]
@gcg0210 val=False will validate only final epoch
