### ISSUE TITLE
yolov11 export engine fp16 bug

### ISSUE THREAD

**Issue by zerobest** [ultralytics/ultralytics#17654]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

During the conversion process of the YOLOv11 model, I chose to convert it to an FP16 precision engine model. According to the conversion results, it shows that the conversion was successful. However, during the inference phase, I found that the model's precision is still FP32. Could you please help me with this issue? The specific details are shown in the figure below.!
![6ae89d3bdbc387a84c1ea12f91b17c4](https://github.com/user-attachments/assets/00a114f3-c21d-4be5-af41-f35d5029cfec)
![e6497d04cf94891893de64640a0ade8](https://github.com/user-attachments/assets/ca70773a-0a31-4f1f-b40c-fa4f47c57b59)
![532e6ff15756a52267f1f60019042e5](https://github.com/user-attachments/assets/7fce9e5b-db45-41db-b7c8-34f4046fd1bf)

### Environment

Ultralytics 8.3.33 🚀 Python-3.9.0 torch-2.0.1+cu117 CUDA:0 (Tesla P40, 24452MiB)
Setup complete ✅ (36 CPUs, 125.7 GB RAM, 854.0/935.3 GB disk)

OS                  Linux-5.4.0-200-generic-x86_64-with-glibc2.31
Environment         Linux
Python              3.9.0
Install             pip
RAM                 125.70 GB
Disk                854.0/935.3 GB
CPU                 Intel Xeon E5-2696 v3 2.30GHz
CPU count           36
GPU                 Tesla P40, 24452MiB
GPU count           2
CUDA                11.7

numpy               ✅ 1.23.0>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 11.0.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.0.1>=1.8.0
torchvision         ✅ 0.15.2>=0.9.0
tqdm                ✅ 4.67.0>=4.64.0
psutil              ✅ 6.1.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.11>=2.0.0
numpy               ✅ 1.23.0<2.0.0; sys_platform == "darwin"
torch               ✅ 2.0.1!=2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

from ultralytics import YOLO
import cv2
import pdb
# Load a model
model = YOLO("/home/qxtech/tmh/yolov11/runs/detect/personBall/weights/best.pt")

path = model.export(format="engine",half=True,device=0)  # return path to exported model
from ultralytics import YOLO
import cv2
import pdb
# Load a model
model = YOLO("/home/qxtech/tmh/yolov11/runs/detect/personBall/weights/best_half.engine")

model.predict(source='/home/qxtech/tmh/yolov11/data',save=True,conf=0.35,save_txt=True,save_conf=True,save_crop=True,project='/home/qxtech/tmh/yolov11/runs/detect')

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
The input and output of TRT would still be FP32.

https://github.com/NVIDIA/TensorRT/issues/1792#issuecomment-1038372973

https://forums.developer.nvidia.com/t/want-to-know-more-about-int8-precision/273242/7

https://forums.developer.nvidia.com/t/tensorrt-int8-quantization-weights-activations-quantization/110404/2

**Comment by zerobest** [comment]
It might be because the P40 graphics card does not support half-precision computation.

**Comment by glenn-jocher** [comment]
@zerobest it's possible that the Tesla P40 GPU doesn't support FP16 precision, which could be causing the issue. You might want to verify the GPU's capabilities or test the model on a different GPU that supports FP16 to see if the problem persists. If the issue continues, feel free to share more details for further assistance.
