### ISSUE TITLE
ParkingPtsSelection bug on mac to select images

### ISSUE THREAD

**Issue by amiune** [ultralytics/ultralytics#17662]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Other

### Bug

The class [ParkingPtsSelection](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/solutions/parking_management.py) has a problem in mac.

The file selection wildcard patterns [seems must be](https://stackoverflow.com/questions/44403566/add-multiple-extensions-in-one-filetypes-mac-tkinter-filedialog-askopenfilenam) a space rather than ;

I think the line 92:
```python
self.image = Image.open(self.filedialog.askopenfilename(filetypes=[("Image Files", "*.png;*.jpg;*.jpeg")]))
```

should be changed to 
```python
self.image = Image.open(self.filedialog.askopenfilename(filetypes=[("Image Files", "*.png *.jpg *.jpeg")]))
```

### Environment

MacOS Sequoia version 15.1

### Minimal Reproducible Example

```python
from ultralytics import solutions
solutions.ParkingPtsSelection()
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @amiune, thank you for reaching out and reporting this issue with the Ultralytics repository 🚀! An Ultralytics engineer will be with you shortly to assist further.

In the meantime, feel free to explore our [Docs](https://docs.ultralytics.com) where you might find additional information that could be helpful. We provide a range of [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples that could also aid in navigating any other queries you might have.

If you're encountering a 🐛 bug as you've described, it's fantastic that you've already included a minimal reproducible example! This info is incredibly valuable for our team to diagnose and address the issue efficiently. 

While you're here, you might want to join our community for more interactive support or discussions:

- Join us on [Discord](https://ultralytics.com/discord) 🎧 for real-time chat with fellow users.
- Check out [Discourse](https://community.ultralytics.com) for more structured community discussions.
- Dive into our [Subreddit](https://reddit.com/r/ultralytics) to engage in broader conversations with our community.

## Upgrade

Ensure you are using the latest version of the `ultralytics` package as updates might already include necessary fixes:

```bash
pip install -U ultralytics
```

Make sure to check out the project’s [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) to verify your environment setup is correct, specifically with [**Python>=3.8**](https://www.python.org/) and [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/).

## Test in Verified Environments

Consider trying one of these verified environments to further test your scenario:

- **Notebooks** with free GPUs: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See our [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. Explore our [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

Current build and test statuses can be tracked through our [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) system. This aids in ensuring all features and fixes are working correctly across different platforms.

Thank you for your willingness to contribute with a PR! Your engagement helps improve Ultralytics for everyone 😊.

**Comment by glenn-jocher** [comment]
@amiune thank you for identifying the issue and proposing a solution! Your observation regarding the file selection wildcard patterns for macOS is valid. Feel free to submit a Pull Request (PR) with your suggested fix, as it will enhance cross-platform compatibility. Please ensure you follow the [Contributing Guide](https://docs.ultralytics.com/help/contributing/) and sign the Contributor License Agreement (CLA) when submitting your PR. Let us know if you have further questions!

**Comment by RizwanMunawar** [comment]
Hi @amiune, thank you for sharing the details about the issue you encountered. I’ve opened a PR to address this, and hopefully, it will resolve the problem. Thanks!

#17797
