### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by Starmixcraft** [ultralytics/ultralytics#1766]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Im Trying to train a YOLOv5 model on a custom dataset.
Single GPU Training runs without problems, tested on 1 and 2 separaty.

I have 3 GPUs in the System, GPU0 is a 1080TI and GPU1,2 are 1080.
Im only traing on 1 and 2.
Multi-GPU Training allways throws errors, full log: https://pastebin.com/TUFqBqSp

### Environment

Ultralytics YOLOv8.0.59 
Python-3.10.6 
torch-2.0.0+cu117 
CUDA:1 (NVIDIA GeForce GTX 1080, 8192MiB)                                                                                                                                                                                                    CUDA:2 (NVIDIA GeForce GTX 1080, 8192MiB)
WSL (Ubuntu22.04 LTS)

### Minimal Reproducible Example

`from ultralytics import YOLO
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
model = YOLO('?') #any model (YOLOv8 and YOLOv8)
results = model.train(data='?', epochs=500, batch=4, save_period=25, device=[1,2], v5loader=True)` #any dataset (coco128) also produces the above results

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Starmixcraft from the information provided, it appears that you are facing a problem when trying to train a YOLOv8 model using multi-GPU training on your custom dataset.

Given your setup, there are a few things you might want to consider:

Ensure that your environment is correctly set up to support multi-GPU training with PyTorch. You might need to install the appropriate version of torch and torchvision for your specific CUDA version.

Make sure that you have sufficient GPU memory available to accommodate multi-GPU training. Training with multiple GPUs may require additional memory, especially if you're using large batch sizes. You can try reducing the batch size to see if that resolves the issue.

Verify that your dataset is properly formatted and doesn't have any issues that might cause problems during training. This includes making sure that your labels are correct and that your images are accessible.

If you continue to face problems, I would recommend referring to the YOLOv8 documentation at https://docs.ultralytics.com for more information on setting up your environment and preparing your dataset for multi-GPU training.
