### ISSUE TITLE
multi-class yolov11-pose onnx output probelm

### ISSUE THREAD

**Issue by AyeGo** [ultralytics/ultralytics#17674]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello. I encountered some problems when i am trying to deploy multi-class yolov11-pose model using C++.I trained the model with 2 classes each have 3 keypoints and it inferences output correctly.But when I converted it to onnx and ran on  C++,I could only get output with 1 class and 3 keypoints .I noticed the output of both pt and onnx model are (1, 15, 8400).
Properties of model 
![Snipaste_2024-11-21_10-05-57](https://github.com/user-attachments/assets/5c0e133d-977d-4ee7-84ea-f53d20a80568)
and my export code
`model.export(format='onnx',simplify=True, device=0, opset=12,
             imgsz=640)`

is the model exported correctly?how can i use exported model? can you give me some example code?
Thanks for the help

**Comment by UltralyticsAssistant** [comment]
👋 Hello @AyeGo, thank you for reaching out and sharing your experience with Ultralytics 🚀! We're here to help. An Ultralytics engineer will assist you soon, but in the meantime, let's see how we can make progress.

If this is a 🐛 Bug Report related to your multi-class yolov11-pose ONNX output, could you please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/)? This helps us to understand the issue better and debug it efficiently.

For model export and usage questions, here are a few things to check:

1. Ensure you are using the latest version of the `ultralytics` package, as many issues are promptly resolved in newer releases. You can upgrade it using:

   ```bash
   pip install -U ultralytics
   ```

2. Check that your Python environment is [**Python>=3.8**](https://www.python.org/) with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/). 

If you're new to using our tools, consider visiting our [Docs](https://docs.ultralytics.com) where you can find detailed [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) examples.

For real-time support and to connect with other users, you might want to join our community on [Discord](https://ultralytics.com/discord) 🎧, or for more in-depth discussions, check out [Discourse](https://community.ultralytics.com). You can also explore threads and share insights on our [Subreddit](https://reddit.com/r/ultralytics).

## Environments

YOLO can be run in several up-to-date environments with pre-installed dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn):

- Use free GPU notebooks: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- For Google Cloud, refer to the [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/).
- Access Amazon services via the [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/).
- If Docker is your choice, see the [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>.

## Status

Check if all tests are passing on our [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule). If the badge is green, the tests for YOLO are passing across macOS, Windows, and Ubuntu, checking all [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/).

Feel free to add more details about your setup or any specific error messages you encounter. We're here to help! 😊

**Comment by glenn-jocher** [comment]
@AyeGo it seems like there might be an issue with the ONNX export or the way the model is being run in your C++ environment. Please ensure that your model is exported correctly by checking the ONNX export documentation: [Exporting YOLO11 to ONNX](https://docs.ultralytics.com/integrations/onnx/). Additionally, verify that your C++ environment supports the necessary operations and has the proper dependencies. If the issue persists, consider checking the ONNX Runtime documentation for guidance on handling multi-class outputs in C++. If you have further questions, please feel free to reach out on the GitHub issues page.

**Comment by AyeGo** [comment]
Hi @glenn-jocher  
Thank you for your reply!
I checked onnx inference followed steps below:
`from ultralytics import YOLO
model = YOLO("best.pt")
model.export(format="onnx")  
onnx_model = YOLO("best.pt")
results = onnx_model("test.jpg")`
The results is correct.The thing confusing me is the output shape of pt and onnx model are (1, 15, 8400).My understanding of output is 15 means: xywh(4) + ?(1) + confidence(1) + kpts(3*3),so I got 1 class outputs in C++.But how can i get the other class output?And what does ?(1)  mean?

**Comment by Y-T-G** [comment]
It's correct.

xywh + 2 class scores + 3*3 keypoints = 15

**Comment by Y-T-G** [comment]
There's no confidence output. You get that from the class scores.

**Comment by AyeGo** [comment]
Thanks for the help.
I didn't realize the output need to be extracted by class score.

**Comment by glenn-jocher** [comment]
@AyeGo you're welcome! I'm glad the clarification helped. If you have any more questions or need further assistance, feel free to ask.
