### ISSUE TITLE
How do I setup multi-GPU training?

### ISSUE THREAD

**Issue by Chase-Nolan** [ultralytics/ultralytics#1769]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey so I could only find the Yolov5 multi-gpu training command (https://docs.ultralytics.com/yolov5/multi_gpu_training/) but it doesn't work at all on Yolov8

Here is my code that I'm using.

`# Yolov8s training object detection model
from ultralytics import YOLO

# Load a model
model = YOLO("yolov8s.yaml")  # build a new model from scratch

# Use the model and train it on Nvidia GPU, use an image size of 1920x1080, and train for 1 epoch
if __name__ == '__main__':
    results = model.train(data="config.yaml", epochs=3, imgsz=1280, device='0,1', batch=32)
    results = model.val()`

Here is the entire output

> PS C:\Users\Chase\Desktop\YoloV8-Detection>  c:; cd 'c:\Users\Chase\Desktop\YoloV8-Detection'; & 'C:\Users\Chase\AppData\Local\Programs\Python\Python311\python.exe' 'c:\Users\Chase\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '52939' '--' 'C:\Users\Chase\Desktop\YoloV8-Detection/main.py' '-Xfrozen_modules=off' 

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.Conv                  [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.C2f                   [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.C2f                   [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.Conv                  [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.C2f                   [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.SPPF                  [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]
 12                  -1  1    591360  ultralytics.nn.modules.C2f                   [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]
 15                  -1  1    148224  ultralytics.nn.modules.C2f                   [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.Conv                  [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]
 18                  -1  1    493056  ultralytics.nn.modules.C2f                   [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.Conv                  [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]
 21                  -1  1   1969152  ultralytics.nn.modules.C2f                   [768, 512, 1]
 22        [15, 18, 21]  1   2147008  ultralytics.nn.modules.Detect                [80, [128, 256, 512]]
YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients, 28.8 GFLOPs

New https://pypi.org/project/ultralytics/8.0.59 available  Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.58  Python-3.11.2 torch-2.0.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3060 Ti, 8192MiB)
                                                           CUDA:1 (NVIDIA GeForce GTX 1070, 8192MiB)
yolo\engine\trainer: task=detect, mode=train, model=yolov8s.yaml, data=config.yaml, epochs=3, patience=50, batch=32, imgsz=1280, save=True, save_period=-1, cache=False, device=0,1, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs\detect\train9
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.Conv                  [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.C2f                   [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.C2f                   [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.Conv                  [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.C2f                   [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.SPPF                  [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]
 12                  -1  1    591360  ultralytics.nn.modules.C2f                   [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]
 15                  -1  1    148224  ultralytics.nn.modules.C2f                   [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.Conv                  [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]
 18                  -1  1    493056  ultralytics.nn.modules.C2f                   [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.Conv                  [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]
 21                  -1  1   1969152  ultralytics.nn.modules.C2f                   [768, 512, 1]
 22        [15, 18, 21]  1   2116435  ultralytics.nn.modules.Detect                [1, [128, 256, 512]]
YOLOv8s summary: 225 layers, 11135987 parameters, 11135971 gradients, 28.6 GFLOPs

Running DDP command ['C:\\Users\\Chase\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '52949', 'C:\\Users\\Chase\\AppData\\Roaming\\Ultralytics\\DDP\\_temp_a5z0srvc2392469293904.py', 'task=detect', 'mode=train', 'model=yolov8s.yaml', 'data=config.yaml', 'epochs=3', 'patience=50', 'batch=32', 'imgsz=1280', 'save=True', 'save_period=-1', 'cache=False', 'device=0,1', 'workers=8', 'project=None', 'name=None', 'exist_ok=False', 'pretrained=False', 'optimizer=SGD', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'image_weights=False', 'rect=False', 
'cos_lr=False', 'close_mosaic=10', 'resume=False', 'amp=True', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'save_hybrid=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'source=None', 'show=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'hide_labels=False', 'hide_conf=False', 'vid_stride=1', 'line_thickness=3', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'boxes=True', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=False', 'opset=None', 'workspace=4', 'nms=False', 'lr0=0.01', 'lrf=0.01', 'momentum=0.937', 'weight_decay=0.0005', 'warmup_epochs=3.0', 'warmup_momentum=0.8', 'warmup_bias_lr=0.1', 'box=7.5', 'cls=0.5', 'dfl=1.5', 'fl_gamma=0.0', 'label_smoothing=0.0', 'nbs=64', 'hsv_h=0.015', 'hsv_s=0.7', 'hsv_v=0.4', 'degrees=0.0', 'translate=0.1', 'scale=0.5', 'shear=0.0', 'perspective=0.0', 'flipud=0.0', 'fliplr=0.5', 'mosaic=1.0', 'mixup=0.0', 'copy_paste=0.0', 'cfg=None', 'v5loader=False', 'tracker=botsort.yaml']
NOTE: Redirects are currently not supported in Windows or MacOs.
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-921FQ8E]:52949 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-921FQ8E]:52949 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-921FQ8E]:52949 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-921FQ8E]:52949 (system error: 10049 - The requested address is not valid in its context.).
DDP settings: RANK 0, WORLD_SIZE 2, DEVICE cuda:0
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-921FQ8E]:52949 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-921FQ8E]:52949 (system error: 10049 - The requested address is not valid in its context.).
Overriding model.yaml nc=80 with nc=1
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed 
Traceback (most recent call last):
  File "c:\Users\Chase\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 3489, in <module>
    main()
  File "c:\Users\Chase\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 3482, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Chase\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2510, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Chase\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2517, in _exec
    globals = pydevd_runpy.run_path(file, globals, '__main__')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Chase\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Chase\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\Chase\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "C:\Users\Chase\AppData\Roaming\Ultralytics\DDP\_temp_a5z0srvc2392469293904.py", line 6, in <module>
    trainer.train()
  File "C:\Users\Chase\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\yolo\engine\trainer.py", line 191, in train
    self._do_train(world_size)
  File "C:\Users\Chase\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\yolo\engine\trainer.py", line 266, in _do_train
    self._setup_train(world_size)
  File "C:\Users\Chase\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\yolo\engine\trainer.py", line 215, in _setup_train
    dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chase\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\distributed\distributed_c10d.py", line 1436, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chase\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\distributed\distributed_c10d.py", line 1559, in broadcast
    work.wait()
RuntimeError: Invalid scalar type
Traceback (most recent call last):
  File "c:\Users\Chase\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 3489, in <module>
    main()
  File "c:\Users\Chase\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 3482, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Chase\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2510, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Chase\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2517, in _exec
    globals = pydevd_runpy.run_path(file, globals, '__main__')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Chase\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Chase\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\Chase\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "C:\Users\Chase\AppData\Roaming\Ultralytics\DDP\_temp_a5z0srvc2392469293904.py", line 6, in <module>
    trainer.train()
  File "C:\Users\Chase\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\yolo\engine\trainer.py", line 191, in train
    self._do_train(world_size)
  File "C:\Users\Chase\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\yolo\engine\trainer.py", line 266, in _do_train
    self._setup_train(world_size)
  File "C:\Users\Chase\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\yolo\engine\trainer.py", line 215, in _setup_train
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chase\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\distributed\distributed_c10d.py", line 1436, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chase\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\distributed\distributed_c10d.py", line 1559, in broadcast
    work.wait()
RuntimeError: Invalid scalar type 

>

**Comment by glenn-jocher** [comment]
@Chase-Nolan for local DDP issues I'd recommend training in our Docker image. Try that and see if it resolves your issue:

## Environments

YOLOv8 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/GCP-Quickstart)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/AWS-Quickstart)
- **Docker Image**. See [Docker Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

**Comment by Chase-Nolan** [comment]
Thanks for the reply, I have downloaded the docker image but I don't know what it does, nor where to find out?

**Comment by glenn-jocher** [comment]
@darouwan it seems that the issue you encountered with local DDP training in YOLOv8 is related to the Windows environment. It is recommended to test the training in other environments, such as Linux or WSL2. The Docker image is a platform-independent environment that can be used to run YOLOv8 in any supported environment. By using the Docker image, you can avoid compatibility issues between different operating systems and software.

**Comment by glenn-jocher** [comment]
@darouwan the YOLOv8 image is at ultralytics/ultralytics:latest. See https://hub.docker.com/r/ultralytics/ultralytics

**Comment by glenn-jocher** [comment]
<img width="1104" alt="Screenshot 2023-04-12 at 01 41 47" src="https://user-images.githubusercontent.com/26833433/231311631-22ba14cb-a8cb-4cb6-8924-993265418fff.png">

**Comment by darouwan** [comment]
Thank you very much! I will try it later

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by darouwan** [comment]
@glenn-jocher  I have tried docker on both single gpu training and multiple gpu training. It seems the docker has significant performance issue. For the same training param, the docker always takes more than 1 minutes for each epoch. However the local windows only takes about 40 seconds. Do you ever meet the similar issue?

**Comment by glenn-jocher** [comment]
@darouwan yes, it's possible that using Docker may introduce some performance overhead compared to running directly on the host system. This is because Docker containers add an additional layer of virtualization, which may introduce some latency and overhead. However, the extent of the performance impact may vary depending on factors such as the host system configuration, the container image size, the workload running inside the container, and other factors. 

If you're experiencing significant performance issues when running inside a Docker container, you may want to investigate further to see if there are any specific configuration or setup issues that could be causing the issue. For example, it's possible that the container image you're using may have some additional debugging or logging overhead that's slowing down the training, or there could be some other configuration issue that's causing the container to run slower than expected. 

One thing to investigate is whether you have the necessary GPU drivers and other dependencies installed properly within the Docker container. If these dependencies are not set up correctly or are not the same version as those on the host system, this could cause performance issues. It may also be worth comparing the container runtime environment to the host runtime environment, to see if there are any other differences that could be impacting performance.

**Comment by daiyicun** [comment]
I think wsl2 is not support muti GPU training. according to below Microsoft webpage. 
https://learn.microsoft.com/en-us/windows/wsl/tutorials/gpu-compute
I also have this problem training yolov8 on windows with 2 GPU.

**Comment by glenn-jocher** [comment]
@daiyicun you're correct. Currently, WSL2 does not officially support multi-GPU training. This limitation applies to several deep learning frameworks and is not unique to YOLOv8. The primary reason for this limitation is that the underlying infrastructure of WSL2 does not handle communication between multiple GPUs. 

While Windows is continuing to improve its support for machine learning and AI workloads, for now, multi-GPU training is typically more straightforward on a Linux system. If you have access to one, you might have an easier time running your multi-GPU training tasks there. 

It's worth keeping an eye on Microsoft's updates regarding enhancements to GPU support in WSL2. As they continue to invest in this area, it's likely we'll see improvements in the future.

**Comment by AIFlowML** [comment]
I'm gonna setup a dual GPU for training but the linux drivers for most of the hardware MB are not available. 
You think i should just make a Dual boot with Ubuntu and work mainly in Linux (now 1gpu on win11 wsl2) ?
Can docker solve the multi GPU on win ? 

Tnks

**Comment by glenn-jocher** [comment]
@AIFlowML dual-booting with Ubuntu could indeed provide a more seamless multi-GPU training experience, as Linux generally offers better native support for such setups. Docker on Windows won't circumvent the WSL2 limitation regarding multi-GPU support. If your workflow heavily relies on multi-GPU capabilities, transitioning to a Linux-based system could be beneficial. 🐧✨

**Comment by AIFlowML** [comment]
Tnks for the reply.
The only fear for me are the drivers for the mb.
I had to get an ASUS Z790 black hero with ZERO support for Linux. So that is the only issue.
And of course no documentation:(

>

**Comment by glenn-jocher** [comment]
@AIFlowML It's understandable to be concerned about hardware compatibility. While official support may be lacking, the Linux community is resourceful, and you may find that generic drivers or community-driven solutions can provide the functionality you need. Before committing to a dual-boot setup, you might consider testing your hardware with a live Linux USB to check for any major issues. Good luck! 🍀

**Comment by mountain111** [comment]
@AIFlowML  Hi, I encounter the same issue. Do you have any solution now? Look forward to your reply.
