### ISSUE TITLE
Keep geting "FileNotFoundError: val: No labels found in C:\[...]\lisa-dataset\valid\labels.cache, can not start training"

### ISSUE THREAD

**Issue by KuroiYoshiko** [ultralytics/ultralytics#1770]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I know someone had similar problem already but for me it seems a bit different, as it seems to be only about these labels.cache files. I converted LISA traffic dataset to, what I at least think is appropriate version, to be able to train yolov8 with it.
I'm getting this specific error:
FileNotFoundError: val: No labels found in C:\Users\rumpe\OneDrive\Desktop\lisa-test\datasets\lisa-dataset\valid\labels.cache, can not start training. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data

Picture of entire terminal:
![image](https://user-images.githubusercontent.com/46839601/229355597-af7cb3dd-d56f-473d-878b-0bce28c48ffc.png)

I converted LISA dataset to format as below, splitting folders for "train" and "valid", and in both there's "images" and "labels" folders. In main folder (lisa-dataset, consisting of train and valid folders) I have data.yaml file that looks like below:
![image](https://user-images.githubusercontent.com/46839601/229355472-84d3967c-04e6-4b6e-8386-6afa08bfb8aa.png)
![image](https://user-images.githubusercontent.com/46839601/229355903-903e4654-9366-44ac-b368-1201bb3ded46.png)

This format worked when I was training model in google colab. After splitting dataset into smaller sample I was able to both train model and use detection, so I'm convinced it's correct. I just didn't have labels.cache but seems not to be problem for colab. As you can see in colab training starts without problem, it just creates appropriate labels.cache files that seem to work: 
![image](https://user-images.githubusercontent.com/46839601/229356082-1648a759-ff2a-4d4b-8d29-825cf581de47.png)

But suddenly when I want to do the same thing on my desktop with windows 10, in virtual environment it doesn't seem to work, giving me error that I stated before. It also creates cache files but as I understand they are not correct?
![image](https://user-images.githubusercontent.com/46839601/229356460-05f4722d-eda4-4c83-b4dc-466230f633db.png)

I'm totally lost as what should I do and what could be the problem in this situation. Funny enough, on the second PC I own (just has worse specs so I wanted to switch to something better for training) I had the same problem, took me 3 hours to fix it and I don't even recall what could that be, as I literally tried everything before it finally worked (from changing hierarchy of folders multiple times, restarting pc, installing and uninstalling packages of cuda-python, torch and who knows what else...). Hierarchy of folders on both PC seem to be the same... Any idea what could I do to fix this?

**Comment by mausam-office** [comment]
I got same error while training yolov8-pose model 
"FileNotFoundError: val: No labels found in D:\Mausam\YOLOv8\PlateRecognition\datasets\projects\plateDetectionKeypoint\V1 data2\labels\val.cache,"

Were you able to solve the issue? @KuroiYoshiko  @glenn-jocher 

Following code is of data-config.yaml file
![image](https://github.com/ultralytics/ultralytics/assets/96226036/f07ffe83-220d-45fd-869f-673a985bef2c)

ERROR
![image](https://github.com/ultralytics/ultralytics/assets/96226036/6fa5c437-21e6-4cf9-ac8e-7c73b4496309)

Please let me know if there is any issue with yaml file

**Comment by mausam-office** [comment]
I was able to solve the above problem.
The problem existed with my data. The label file for image file was with different name which created no label file for image file

This problem will arise if no label file is available for any of the images in either of directories: train or val.

**Comment by glenn-jocher** [comment]
@mausam-office i'm glad to hear that you were able to solve the issue! It seems like the problem was with your data. Specifically, the label file for an image file had a different name, which caused the absence of a label file for that image file.

This issue can occur when there are no label files available for any of the images in either the "train" or "val" directories.

By ensuring that the label file names match the corresponding image file names, you can avoid this error and proceed with training your YOLOv8 model.

If you have any further questions or concerns, feel free to ask. Good luck with your training!

**Comment by Humaira-Sadia** [comment]
Facing issue labels not found for val folder...
![image](https://github.com/user-attachments/assets/abab754c-dac1-4038-8108-cbd51c47852b)
Labels are sharing same name as that of images but still facing this issue!!!
file structure :- 
![image](https://github.com/user-attachments/assets/f4341be0-78a9-40ff-a519-e2c8ca6f0c8e)

**Comment by glenn-jocher** [comment]
Ensure that your label files are in the correct format and located in the "labels" directory corresponding to your "images" directory. Double-check that the paths in your data.yaml file are accurate. If the issue persists, please refer to the YOLO documentation for further troubleshooting steps.

**Comment by Y-T-G** [comment]
@Humaira-Sadia Move the yaml file inside the dataset folder. And remove spaces and special characters from your label and image file names. Only have number, underscores and letters.

**Comment by Humaira-Sadia** [comment]
Still facing same issue
![image](https://github.com/user-attachments/assets/7f5674fe-8e66-40ee-bddb-9dd611ead57b)
changed file name - images name and labels name removed extra spaces and all 
![image](https://github.com/user-attachments/assets/80a4a797-2378-4364-baa9-dd842cd0208f)

**Comment by Y-T-G** [comment]
@Humaira-Sadia What does your yaml file look like?

**Comment by Y-T-G** [comment]
@Humaira-Sadia You should delete the label.cache inside the train and val folders. And rerun.
