### ISSUE TITLE
Mask size does not scale when using yolo11s-seg.engine or yolo11s-seg.onnx, while yolo11s-seg.pt still get the right scale

### ISSUE THREAD

**Issue by davidan208** [ultralytics/ultralytics#17743]
Hi,
I'm having issues when using yolo11s-seg.onnx and yolo11s-seg.engine after converting from the Ultralytics export method.
This is my result:
- Original:
![image](https://github.com/user-attachments/assets/4831d9f8-95d9-41f3-b659-7627804fd096)

- ONNX:
![image](https://github.com/user-attachments/assets/a4fb34bf-e684-468d-b596-2c488453c1b3)

- TensorRT:
![image](https://github.com/user-attachments/assets/669ebce6-f904-4b22-bd0c-7ac9a471194a)

This is my code:
```
import cv2
import numpy as np
from ultralytics import YOLO
from PIL import Image

model = YOLO("./models/yolo11n-seg.pt")
img = cv2.imread('../pose_data/1.jpg')
target_class = "person"
results = model(img, conf = 0.80)

for result in results:
    masks = result.masks.data.cpu().numpy()
    class_ids = result.boxes.cls.cpu().numpy()
    for mask, class_id in zip(masks, class_ids):
        if class_id != 0:
            continue

        mask = (mask > 0.5).astype(np.uint8) * 255
        before_mask = mask.copy()
        print(before_mask.sum())
        mask_resized = cv2.resize(mask, (img.shape[1], img.shape[0]), interpolation = cv2.INTER_NEAREST)
        print(mask_resized.sum())
        blurred_img  = cv2.GaussianBlur(img, (501, 501), 123)
        mask_3d      = cv2.merge([mask_resized] * 3)
        
        img          = np.where(mask_3d == 255, blurred_img, img)

final_result = Image.fromarray(cv2.cvtColor(img, cv2.COLOR_RGB2BGR))
final_result.show()
```

How can i get the right size for the mask when scaling ?
Thanks

**Comment by UltralyticsAssistant** [comment]
👋 Hello @davidan208, thank you for sharing your issue with Ultralytics 🚀! An Ultralytics engineer will be here to assist you soon. In the meantime, I can offer some guidance and resources to help address your concerns.

Based on your description, it seems like you are experiencing scaling issues with masks when using `yolo11s-seg.onnx` and `yolo11s-seg.engine`. Here are some initial steps:

- Please ensure you are using the latest version of the `ultralytics` package to eliminate any potential bugs that have been resolved in recent updates. You can update using:
  ```bash
  pip install -U ultralytics
  ```

- If this is a 🐛 Bug Report, providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) can greatly assist our team in troubleshooting the issue more effectively.

- For more insights on exporting your models and expected outcomes, you might want to visit our [Export Guide](https://docs.ultralytics.com/modes/export/).

To further explore your scenario or similar cases, consider joining the Ultralytics community:
- For real-time support, our [Discord](https://ultralytics.com/discord) channel 🎧 is available.
- Prefer threaded discussions? Check out [Discourse](https://community.ultralytics.com) or our [Subreddit](https://reddit.com/r/ultralytics).

If you're running your scripts in a specific environment, it may help to test your setup in a verified environment to rule out compatibility issues:
- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

We appreciate your patience and look forward to resolving this matter. Your screenshots and code are very helpful in understanding the issue, so thank you for including those!

**Comment by Y-T-G** [comment]
Use `retina_masks=True` in `model.predict`. You don't have to resize masks if you use that.
