### ISSUE TITLE
Request for Information on Postprocessing Utility for NMS on TFLite Model for Mobile Application

### ISSUE THREAD

**Issue by WikiGenius** [ultralytics/ultralytics#1777]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I want to perform post-processing for NMS on a TFLite model for mobile purposes. Is there any utility available for this? Also, if possible, I want it to require minimal imported libraries. I don't want to use PyTorch for this function.

Thank you so much.

### Additional

I tried to create a matrix of boxes X by boxes to filter out boxes with an IOU < thresh and the overlapping boxes, but it was not efficient due to its time complexity of 8600 X 8600 (n^2).

**Comment by glenn-jocher** [comment]
@WikiGenius yes it's possible to perform Non-Maximum Suppression (NMS) without using any deep learning frameworks like TensorFlow or PyTorch. We are working on an open-source framework for both iOS and Android to enable users to embed HUB trained YOLO models in their own 3rd party apps. 

This should be out soon! Our lead mobile developer on the effort is @sergiossm.

**Comment by WikiGenius** [comment]
@glenn-jocher  Good to hear this
Is there any GitHub repo for this?

**Comment by glenn-jocher** [comment]
@WikiGenius, we do not have a separate GitHub repo for this mobile-specific implementation, as it is still in development. However, we will update the main YOLOv8 repo with this implementation once it is ready. Please stay tuned for more updates by following our project on GitHub or our official website https://ultralytics.com/. In the meantime, if you have any other questions or concerns, feel free to reach out to us.
