### ISSUE TITLE
SyncBatchNorm for DDP training

### ISSUE THREAD

**Issue by developer0hye** [ultralytics/ultralytics#1779]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

We can train yolov5 with SyncBatchNorm when training a model with DDP. 

https://github.com/ultralytics/yolov5/blob/cca5e21995679c4fce32d67a69e2ec89fe131c0e/train.py#L182-L185

However, it seems that SyncBatchNorm is not used in the yolov8 project.

Is that an intended change?

**Comment by pderrenger** [comment]
@developer0hye hi there! 👋 YOLOv8 currently does not use SyncBatchNorm for DDP training. This decision is based on trade-offs between performance and complexity. However, the YOLOv8 repo is continuously evolving, and your feedback is valuable for future developments. If you have any further questions or suggestions, feel free to share them!
