### ISSUE TITLE
How are images in val_batchX selected?

### ISSUE THREAD

**Issue by kakann** [ultralytics/ultralytics#1784]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,
I am doing a project where I am using YOLOv8 for road damage detection on image data from 7 countries. I have a question regarding the generation of runs/detect/val folder which is generated when doing validation. Within the runs/detect/val folder there are 6 images, namely:
val_batch0_labels.jpg
val_batch0_pred.jpg
val_batch1_labels.jpg
val_batch1_pred.jpg
val_batch2_labels.jpg
val_batch2_pred.jpg

As I understand it those images should contain a random sample of images (and their labels) from the validation set as defined in the .yaml file. However, in the six images listed above, there is only a selection of images from one out of my 7 country images. All images are named according to the country where they were taken, so its easy to separate images by country. 

 
![val_batch0_pred](https://user-images.githubusercontent.com/43540525/229457020-1c9b1f97-cf6d-4edb-a177-12a3fe29a40f.jpg)

My question is if this behavior is as expected or is this a bug? I tried to remove all Swedish images from the dataset leaving the other 6 country images intact but then there were only images from Japan on the val_batchX images(with the exception for one Chinese image).

![val_batch1_labels](https://user-images.githubusercontent.com/43540525/229457733-4b938c98-7144-4cf5-a1ae-bcec7616a366.jpg)
Note that this image is from another validation where all Swedish images have been removed from the validation set.

I have also rerun validation on the 7 country data and got only Swedish images again. Those images were other Swedish images, but still only Swedish images.

![val_batch0_pred](https://user-images.githubusercontent.com/43540525/229459322-bfd744f6-b12f-46d1-ae24-a672f204d02a.jpg)

This last image is val_batch0_pred from another validation with the same 7 country validation set. We can see that only Swedish images are selected once again.

How are images that end up in val_batchX selected? Are YOLO trying to tell me something by only placing Swedish images in the val_batchX images?

**Comment by glenn-jocher** [comment]
@kakann hello, thank you for choosing YOLOv8 for your road damage detection project! 

Regarding your question about the behavior of the `val_batchX` images - this is actually expected behavior. The images in `val_batchX` are randomly sampled from the validation dataset according to the `val` percentage set in the `.yaml` file. Therefore, it is possible that there are only images from one specific country in the `val_batchX` images generated during validation.

If you would like to sample images from each country during validation, I would recommend splitting your validation dataset into separate folders by country and running validation on each folder individually. This would ensure that the `val_batchX` images contain a variety of images from different countries.

I hope this helps! Let us know if you have any further questions.

**Comment by glenn-jocher** [comment]
If you are using a txt file to define your split then YOLO will use every image in your txt file.

**Comment by kakann** [comment]
Thank you for the answer! :)

**Comment by glenn-jocher** [comment]
@kakann you're welcome! To answer your question about validation, if you have not defined a `val` percentage in your `.yaml` file, YOLOv8 will use all the images in your `val` dataset for validation. However, during validation, only the top X validation images are plotted for easier visual monitoring of the training progress. If you want to visualize all the validation images, you need to modify the source code. Specifically, you can remove ` and batch_i < 3` in line 171 of the `validator.py` file.

**Comment by glenn-jocher** [comment]
Currently, there isn't a built-in parameter to control the number of validation images visualized during validation without modifying the source code. The visualization logic is hardcoded to show a fixed number of batches for simplicity. For custom visualization needs, you'd need to adjust the `validator.py` code as previously suggested. We appreciate the feedback and will consider adding this as a configurable parameter in future updates!
