### ISSUE TITLE
How to ignore some class while training model ?

### ISSUE THREAD

**Issue by jayprajapati-inventyv** [ultralytics/ultralytics#17855]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have 14 class in my dataset. I want to ignore some class form this 14 class. How i can skip that classes while training new model.?

**Comment by Y-T-G** [comment]
You can specify the classes to train using the `classes` argument.

`model.train(classes=[0,3,5,8])`

**Comment by Tissum** [comment]
@Y-T-G Hi！
What should I do if I want to ignore certain classes in `val`？ Is `classes` valid in val?
My dataset contains three categories: [0,1,2], but I want to discard 0 and 1.

**Comment by Tissum** [comment]
@Y-T-G Hi！
What should I do if I want to ignore certain classes in `val`？ Is `classes` valid in val?
My dataset contains three categories: [0,1,2], but I want to discard 0 and 1.
