### ISSUE TITLE
Processing ONNX YOLOv11 Pose response

### ISSUE THREAD

**Issue by Umenokin** [ultralytics/ultralytics#17857]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am exporting yolo11n-pose.pt model into onnx format to read it in Unreal Engine.

**According to multiple sources, I can confirm:**
Input shape (1, 3, 640, 640)
Output shape (1, 56, 8400)

Again, according to multiple sources, I am iterating 8400 float elements, where each block is 56 floats. 
It seems I should expect the following format:
data pointer[0 - 3] - bounding box's x, y, w, and h values.
data pointer[4] - confidence.
data pointer[5 - 55] - keypoints(17x3).

If I iterate through each 56-sized block, below are the first few blocks. But I cannot understand how to process those data. For example:
batch[4] = 32.638496, which seems not to make sense as a confidence value.
batch[0-3] = 13.666249, 19.569092, 23.765324, 28.339148 which should be the bounding box which means keypoints should be within this bounding box;, thus keypoints with values like 380.933899, 387.889221, 402.532867, 408.798767, 416.330170, 422.008850, 432.839783, 435.251282, 444.962463 do not make sense either.

What am I missing?

```
Batch[13.666249, 19.569092, 23.765324, 28.339148, 32.638496, 43.249947, 54.544548, 64.417160, 72.106735, 75.926041, 83.592789, 89.712357, 100.039474, 106.587318, 113.482056, 122.601883, 129.788193, 135.521545, 146.121780, 159.803375, 168.036316, 176.245758, 187.029297, 196.902313, 198.584351, 204.631989, 207.647461, 212.405945, 223.582794, 239.484131, 249.426651, 256.036255, 260.329742, 270.528198, 276.157593, 285.805298, 296.446625, 305.705322, 312.737671, 316.779449, 321.034729, 326.352844, 335.634064, 347.428345, 352.754242, 357.367065, 372.193665, 380.933899, 387.889221, 402.532867, 408.798767, 416.330170, 422.008850, 432.839783, 435.251282, 444.962463]

Batch[451.427155, 455.969788, 462.540222, 470.130676, 483.506348, 493.187195, 500.511658, 509.326538, 515.935547, 525.338135, 530.741699, 539.375244, 548.000793, 556.369873, 562.470764, 572.062134, 584.310181, 591.288025, 595.769531, 601.747803, 604.767578, 613.637695, 621.265625, 628.164062, 11.044588, 19.977673, 25.107475, 32.258617, 35.793083, 44.676353, 55.411682, 65.967133, 73.806190, 78.170433, 86.499161, 90.578880, 99.772972, 105.784431, 113.494591, 124.430786, 129.565872, 135.332367, 146.117310, 157.356552, 165.624039, 174.495178, 186.204895, 195.177872, 196.752762, 204.146439, 208.744202, 215.616425, 226.404694, 237.547272, 244.938293, 254.136871]

Batch[259.614319, 271.633209, 277.555847, 284.367706, 292.145660, 302.302979, 309.837463, 315.843872, 322.720398, 330.118408, 339.021606, 346.933685, 353.458282, 359.330566, 373.332031, 380.817139, 385.544373, 401.416565, 411.681213, 420.437317, 420.949219, 429.743225, 435.748840, 444.041595, 451.256989, 457.253326, 462.617676, 470.911255, 485.649109, 493.368530, 499.191895, 508.018005, 516.686584, 528.384460, 529.934448, 538.547119, 549.609253, 557.836914, 565.217285, 575.609131, 584.906738, 589.563110, 594.925232, 600.208618, 600.478943, 610.356445, 622.494507, 632.665405, 8.074855, 18.791046, 22.573189, 29.402584, 32.516338, 43.208710, 55.237076, 65.399910]

Batch[73.601486, 76.318420, 83.412552, 88.345924, 96.995705, 101.817329, 112.620201, 126.393166, 132.838608, 136.432159, 146.821014, 158.293839, 165.348022, 174.470551, 186.894272, 194.077362, 195.539185, 203.696350, 208.096863, 213.792633, 225.849640, 238.599899, 244.951111, 253.849701, 259.861816, 271.611603, 280.361389, 288.891205, 293.614746, 302.207794, 311.875183, 317.684265, 323.715515, 330.048492, 339.277588, 348.017609, 353.737488, 361.741211, 376.077606, 381.994507, 385.274200, 399.038086, 407.567261, 418.147095, 423.189270, 429.974915, 435.841766, 443.459015, 449.617493, 453.699036, 459.955017, 468.097534, 485.674622, 495.039124, 498.418762, 510.310791]


LogTemp: Warning: Batch[518.753174, 527.636536, 528.095581, 536.828064, 548.262573, 559.661499, 565.093140, 577.377930, 587.795654, 588.493652, 595.090210, 599.931152, 603.042847, 615.447021, 625.675781, 633.887939, 9.293912, 19.325333, 24.948727, 31.756699, 33.348740, 44.023773, 54.177498, 64.441208, 73.314247, 77.112579, 84.918144, 91.033012, 98.510162, 101.183334, 111.867615, 124.343307, 131.785538, 137.032669, 146.186859, 157.631348, 165.219971, 174.573929, 185.380127, 191.121460, 195.318008, 203.862320, 209.543976, 216.680054, 226.071747, 237.800018, 245.103378, 253.095612, 260.290283, 270.692017, 279.523041, 287.691254, 293.183319, 301.093323, 310.364319, 316.711182]

Batch[323.965820, 330.190643, 338.641541, 347.829437, 354.673035, 363.914795, 374.298096, 381.583862, 387.535339, 395.376587, 407.238739, 416.315002, 421.756561, 428.249634, 436.649872, 443.262085, 450.144714, 455.788208, 463.079651, 471.935486, 486.899414, 495.649841, 498.230591, 510.851501, 519.741577, 527.192932, 526.026855, 534.236267, 546.710999, 557.143921, 565.095703, 576.919739, 587.545654, 589.648926, 596.962402, 600.523560, 602.104370, 608.642212, 625.559326, 632.057251, 11.996860, 19.353428, 23.373360, 28.357397, 31.014135, 41.864410, 54.609852, 65.399307, 73.717018, 77.272842, 84.840424, 90.625885, 98.195198, 101.417633, 112.318283, 125.812088]

Batch[133.661316, 140.076508, 147.231140, 157.724182, 165.477341, 174.811462, 184.595581, 191.817505, 195.668884, 203.454102, 209.396667, 215.673248, 223.203323, 238.151154, 246.078339, 251.727081, 260.949615, 267.578369, 277.938110, 287.618286, 295.027679, 301.215393, 310.381104, 317.544861, 323.458862, 328.333801, 336.423370, 348.333435, 355.647827, 363.320770, 374.637146, 382.438873, 387.546875, 394.511658, 401.194092, 414.162354, 423.023376, 428.524109, 437.683105, 441.377380, 448.257874, 453.627563, 463.780548, 473.719421, 485.562805, 494.740967, 497.263733, 510.686920, 518.320679, 524.543518, 526.356323, 535.493408, 543.930542, 555.273865, 562.675415, 576.797974]

Batch[585.578857, 589.245850, 596.922119, 599.825989, 604.100830, 611.901978, 626.677612, 633.183472, 12.804651, 18.379162, 23.718945, 28.732010, 32.303078, 42.825157, 53.233391, 63.437557, 71.551338, 76.385414, 84.229599, 90.568436, 98.577362, 101.448441, 111.660423, 123.858727, 133.094330, 140.126129, 147.265198, 157.068497, 164.376862, 173.563782, 183.753967, 191.815109, 196.415482, 203.941376, 209.856689, 217.224121, 223.963348, 238.201965, 246.003815, 250.922485, 261.013611, 267.051575, 277.346375, 285.962769, 294.967712, 301.679565, 309.253143, 318.045349, 323.322571, 328.759705, 337.237671, 349.377197, 356.827820, 363.307098, 373.975830, 382.699860]
```

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Umenokin, thank you for your interest in Ultralytics 🚀! We recommend checking out the [Ultralytics Documentation](https://docs.ultralytics.com) for a wealth of information on model export and usage, including helpful guides on [Exporting Models](https://docs.ultralytics.com/modes/export/) and [Post-Processing Outputs](https://docs.ultralytics.com/tasks/detect/#predictions).

If this is a 🐛 Bug Report, please provide us with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) (MRE) that clearly demonstrates how you're exporting the model, the assumptions you're making about the output, as well as any related code snippets. This will help us debug and better understand the issue.

If this is a custom ❓ Question, it would be great to get more details on:
- The exact command or code used for exporting the model to ONNX format.
- How you're parsing the exported ONNX model's output in Unreal Engine and the issues you're encountering.
- Any relevant logs or error messages to provide additional context.

### Debugging Steps

Here are some steps to verify and resolve potential issues:
1. **Export Verification**: Ensure the model is exported correctly with the following command:
   ```bash
   yolo export model=yolo11n-pose.pt format=onnx
   ```
2. **Output Check**: After exporting, inspect the resulting ONNX model with tools like [Netron](https://netron.app/) to confirm the input/output shapes and tensor structure.
3. **Post-Processing**: Make sure you're interpreting the ONNX output properly. The exported format should align with YOLO predictions, as detailed in the [YOLO Task Outputs](https://docs.ultralytics.com/tasks/detect/#predictions). Keypoints are relative coordinates normalized to bounding boxes.

### Community Support

For more interactive support, join the Ultralytics community where developers like you share insights:
- [Discord](https://discord.com/invite/ultralytics) 🎧 for real-time discussions.
- [Discourse](https://community.ultralytics.com) for in-depth Q&A.
- [Subreddit](https://reddit.com/r/Ultralytics) for broader discussions and troubleshooting.

## Upgrade

Ensure you're running the latest version of the `ultralytics` package in a compatible environment:
```bash
pip install -U ultralytics
```

## Environments

YOLO models, including the ONNX format, can be run effectively in any of these verified environments:
- **Notebooks**: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Cloud VMs**: See [GCP Quickstart](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) and [AWS Quickstart](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/).
- **Docker** deployments: See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>.

An Ultralytics engineer will respond soon to further assist you. Let us know if you have additional details in the meantime! 😊

**Comment by Y-T-G** [comment]
You're supposed to transpose it first to `(1, 8400, 56)` which basically means 8400 boxes with 56 values which are as you described.

**Comment by Y-T-G** [comment]
Or you can use this to export with NMS

https://github.com/ultralytics/ultralytics/issues/17149#issuecomment-2437362705

**Comment by Umenokin** [comment]
Thank you @Y-T-G for your help. Sorry for the newbie questions. I am really new in this ecosystem and AI in general.
I tried to export yolov8 to onnx using the link you suggested. Unfortunately, when I load it, it shows a (1, 1, 1) output shape. I think some of the issues can be caused by experimental Unreal Engine runtime, so to exclude it from the equation, I want to try out the transpose option.

I tried to set the shape during configuration manually, but I did not think it would work since I could extract those from the model, and runtime probably just ignored it, producing exactly the same result.

After running the model by Unreal Engine ONNX runtime, I am getting a flat array of 8400 float elements. However, I am skeptical about the results I am getting. For example, the butch below does not look like it makes any sense:

```
Batch[13.666249, 19.569092, 23.765324, 28.339148, 32.638496, 43.249947, 54.544548, 64.417160, 72.106735, 75.926041, 83.592789, 89.712357, 100.039474, 106.587318, 113.482056, 122.601883, 129.788193, 135.521545, 146.121780, 159.803375, 168.036316, 176.245758, 187.029297, 196.902313, 198.584351, 204.631989, 207.647461, 212.405945, 223.582794, 239.484131, 249.426651, 256.036255, 260.329742, 270.528198, 276.157593, 285.805298, 296.446625, 305.705322, 312.737671, 316.779449, 321.034729, 326.352844, 335.634064, 347.428345, 352.754242, 357.367065, 372.193665, 380.933899, 387.889221, 402.532867, 408.798767, 416.330170, 422.008850, 432.839783, 435.251282, 444.962463]
```

I also tried to read this array in a transposed fashion where first index is [i * 56], but did not made any difference:
```
Batch[13.666249, 451.427155, 259.614319, 73.601486, 518.753174, 323.965820, 133.661316, 585.578857, 387.651001, 197.267532, 7.356037, 449.392639, 262.033539, 68.454987, 515.597595, 326.027893, 131.841904, 584.882996, 387.645630, 195.618866, 7.852393, 450.517944, 262.252411, 68.348953, 514.945862, 324.266418, 130.690155, 579.215210, 386.499786, 193.010925, 6.265284, 446.884521, 259.693848, 67.544746, 513.113037, 323.805725, 129.963654, 574.137451, 387.580170, 196.066528, 4.766586, 450.282227, 262.106293, 65.667191, 520.421814, 325.639709, 133.820450, 573.824219, 385.365112, 193.947220, 8.699878, 450.328339, 260.990479, 65.293976, 518.641296, 324.290863]
```

**Comment by Y-T-G** [comment]
You would be getting those values unless you transpose the output. Because it's just showing the x coordinates of all the boxes.

In PyTorch, you transpose using `.transpose()`.
https://pytorch.org/docs/stable/generated/torch.transpose.html

**Comment by Y-T-G** [comment]
You can try exporting using this.


```
from ultralytics import YOLO
from torch import nn
import torch
import torchvision
from ultralytics.utils.ops import xywh2xyxy
import cv2

img = cv2.imread("ultralytics/assets/bus.jpg")

model = YOLO("yolov8n-pose.pt")

_ = model()

prep = model.predictor.preprocess([img, img.transpose(1,0,2)])
num_classes = 1
kpt_shape = 17 * 3

class Model(nn.Module):
    def __init__(self, model):
        super().__init__()
        self.model = model.model
    def forward(self, x):
        pred = self.model(x)[0]
        pred = pred.permute(0, 2, 1)
        return pred

onnxm = Model(model)

torch.onnx.export(
    onnxm,
    prep,
    "onnx_nms.onnx",
    export_params=True,                 # Store the trained parameter weights inside the model file
    opset_version=11,                   # ONNX opset version
    do_constant_folding=True,           # Simplify the model
    input_names=['input'],              # Input name in ONNX model
    output_names=['outputs'],  # Output names
    dynamic_axes={'input': {0: 'batch_size'},   # Dynamic batch size
                'outputs': {0: 'batch_size'},
}
     )
```

The output would be transposed by default.

**Comment by Y-T-G** [comment]
> I also tried to read this array in a transposed fashion where first index is [i * 56], but did not made any difference:
> ```

It should be `[i * 8400]` if it's not transposed.

**Comment by Umenokin** [comment]
Thank you very much for all your suggestions, @Y-T-G !
I found my issue. It is all was my silly mistake. I treated the output as a float[8400] array but not non transposed matrix of [56][8400] and essentially only iterated through one row.

I have not tested my values yet, but they all look promising.

**Comment by Umenokin** [comment]
@Y-T-G I am now getting a set of bounding boxes with values, which looks much nicer. Hover for bus sample all my confidence scores are in the range of 0.000001 to 0.083290. Is it because I am incorrectly processing source image or this value needs to be somehow normalized?

**Comment by Y-T-G** [comment]
You're supposed to filter the boxes by applying a confidence threshold like 0.25. Then you have to apply NMS.

**Comment by Umenokin** [comment]
> You're supposed to filter the boxes by applying a confidence threshold like 0.25. Then you have to apply NMS.

@Y-T-G Yeah, if I will filter them out based on confidence, I will zero them since the biggest confidence I get is 0.083290. I am currently making debug texture which I will use to make sure I read pixels correctly, and if I am, I am stuck😅

**Comment by Y-T-G** [comment]
There's an issue with your preprocessing then

**Comment by Umenokin** [comment]
@Y-T-G in which format do pixels need to be fed into the model? From this issue, it seems they need to be normalized, which I do. https://github.com/ultralytics/ultralytics/issues/12726
However, it seems the format needs to be BGR? I assume the main factor hear is how model was trained I am using the default coco one.

**Comment by Y-T-G** [comment]
The preprocessing is like in the code here.

https://github.com/ultralytics/ultralytics/issues/17423#issuecomment-2466139832

Except it has to N,C,H,W instead of C,H,W. One extra dimension.

**Comment by Umenokin** [comment]
Thank you @Y-T-G, Now things start getting clearer to me. I completely did not understand what the shape of inputs and outputs meant. To be honest, the term "transpose" made it even more confusing. It "clicked" once I looked at it from a different perspective - I have been writing RGBs one after another while I should've written all reds first, greens next, and then all blues, which is the same as transposing it. That did not click when I worked on Outputs, which follows the same logic.

Correct me if I am wrong, though 😅
Thanks a lot for your help!

**Comment by Y-T-G** [comment]
The output will still need to be transposed because that's how it is. The input will need to be preprocessed like in the example. N,C,H,W. Batch dimension first, channel dimension next, height and then width. This is the shape of the input. These are all deep learning related concepts.

**Comment by Umenokin** [comment]
@Y-T-G I am getting close. I think I saw an issue where you helped someone with exactly the same picture but could not find it again. I did not apply to NMS yet.
<img width="1037" alt="Screenshot 2024-12-01 at 17 34 11" src="https://github.com/user-attachments/assets/24156089-2db6-4790-80f0-7c078803e8a6">

**Comment by Y-T-G** [comment]
You will need to unpad and rescale like in the postprocess function in the same code I shared.

https://github.com/ultralytics/ultralytics/issues/17423#issuecomment-2466139832

**Comment by Umenokin** [comment]
I am going to close this issue with the summary for those who will need it:

1. Make sure input data match the input shape where (1, 3, 640, 640) means we process one image with 3 color channels ordered in the form [Rx640, Gx640, Bx640]
2. Colors must be normalized to 0 - 1
3. Image needs to maintain its aspect ration which means if it is wide like 1080 it should be scaled down to have width 640 with top and bottom paddings - top padding height + scaled down image height + bottom padding height = 640.
4. Output shape of (1, 56, 8400) means we have output for one image with 8400 bounding boxes 56 floats each so without transposing data would look like [bx_center x 8400, by_center x 8400, ....]
5. Format of the bounding box is:
0: bb x - center of the bb
1: bb y - center of the bb
2: bb width - total width
3: bb height -total height
4: bb confidence
5 - 55: 17 keypoints array where each keypoint has x, y position and its visibility score.

6. Apply NMS means that model will generate multiple boxes pointing the same person so we need to keep only one bounding box per person which we think is the most accurate.

<img width="643" alt="Screenshot 2024-12-02 at 14 15 16" src="https://github.com/user-attachments/assets/a19bb1f2-750c-4051-a994-816f525c9772">

**Comment by glenn-jocher** [comment]
Thank you for summarizing your findings! This will undoubtedly be very helpful for others tackling similar issues. If further clarification is needed, feel free to consult the [Ultralytics YOLO Docs](https://docs.ultralytics.com/) for detailed guidance.

**Comment by el-hult** [comment]
Thank you @Umenokin ! Ive spent 3 hours reading the YOLO docs, but this thread contained just about everything I needed to know. great summary!

**Comment by Umenokin** [comment]
You are welcome, @el-hult ! Glad it helped someone.

**Comment by OliverDolan** [comment]
any thoughts on what i might need to do here as I dont see why I am getting negative and positive values for the x+y and how to turn them back into co-ordinates in an image any help appreciated :)

<img width="305" alt="Image" src="https://github.com/user-attachments/assets/18bfefe2-e52c-4537-b923-b668a9311b13" />
<img width="255" alt="Image" src="https://github.com/user-attachments/assets/8180788e-f2ad-4c88-880b-8a652092a973" />
<img width="424" alt="Image" src="https://github.com/user-attachments/assets/c4ab285f-2731-4572-82dc-8d50843cb843" />

**Comment by Y-T-G** [comment]
@OliverDolan Is this TFLite?

**Comment by OliverDolan** [comment]
@Y-T-G you mean on the export correct?

**Comment by Y-T-G** [comment]
`nms=True` is an argument during export

**Comment by OliverDolan** [comment]
@Y-T-G now i just get 0's from the run.session in onnx

i exported with this command:
 yolo export model=yolo11n-pose.pt format=onnx nms=true

**Comment by Y-T-G** [comment]
That probably means your preprocessing is incorrect

**Comment by OliverDolan** [comment]
Looks like this

<img width="476" alt="Image" src="https://github.com/user-attachments/assets/1d10d28e-3511-43ed-b0cc-1c8076df0053" />

**Comment by Y-T-G** [comment]
Does the test image have predictions with Ultralytics?

**Comment by OliverDolan** [comment]
@Y-T-G  yes it detects a full pose via python but in code i send in the full sized image not scaled to 640*640 and its using YOLO directly not via onnx

tmp.jpg also appears correct as it has black letterboxes and the image inside them

**Comment by Y-T-G** [comment]
The input image should be in N, C, H, W format

**Comment by OliverDolan** [comment]
thanks i got it working

**Comment by glenn-jocher** [comment]
Great to hear you got it working! 🎉 For others facing similar ONNX pose estimation challenges, your solution summary and code example in [your comment](https://github.com/ultralytics/ultralytics/issues/17423#issuecomment-2466139832) should be very helpful. The Ultralytics team appreciates community contributions like this that help everyone succeed with YOLO models.

**Comment by glenn-jocher** [comment]
@sddaphal Thanks for sharing your experience with the TFLite conversion. Keypoint management in pose models can indeed be challenging, especially when handling NMS and original dimension restoration. For YOLO11-pose TFLite postprocessing, you can reference our [YOLO TFLite example](https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-TFLite-Python) and adapt the keypoint handling portion. 

The tricky parts are the keypoint mapping (each keypoint has [x, y, confidence]) and coordinate transformation back to original dimensions. Consider posting a more specific code sample of your current implementation in a new issue if you're still facing challenges, and our team can provide more targeted guidance.
