### ISSUE TITLE
how can I use the ultralytics folder in the project as the package, instead of pip install ultralytics?

### ISSUE THREAD

**Issue by hjq052070** [ultralytics/ultralytics#17894]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

To make code modification and debugging easier, I hope to use the ultralytics folder in the project code as a package. 
Because if I "pip install ultralytics", I must modify code in sitepackage when I want to make some changes to codes such as augmentation. That is  inconvenient. 
Can you give me some suggestions to me? Thank you !

If I dont install ultralytics, when training model in multi-gpus mode, it will generate a DDP temp file, and the training will failed as follows.

train: /home/hejiaqi18/data/image_url_mukao_vis/classify_data_new/train... found 48122 images in 5 classes ✅ 
val: /home/hejiaqi18/data/image_url_mukao_vis/classify_data_new/val... found 1948 images in 5 classes ✅ 
test: None...
DDP: debug command /home/hejiaqi18/anaconda3/envs/yolov7/bin/python -m torch.distributed.run --nproc_per_node 4 --master_port 59902 /home/hejiaqi18/.config/Ultralytics/DDP/_temp_2z60ejbv140349079716528.py
Traceback (most recent call last):
  File "/home/hejiaqi18/.config/Ultralytics/DDP/_temp_2z60ejbv140349079716528.py", line 6, in <module>
    from ultralytics.models.yolo.classify.train import ClassificationTrainerTraceback (most recent call last):

ModuleNotFoundError  File "/home/hejiaqi18/.config/Ultralytics/DDP/_temp_2z60ejbv140349079716528.py", line 6, in <module>
: No module named 'ultralytics'
    from ultralytics.models.yolo.classify.train import ClassificationTrainer
ModuleNotFoundError: No module named 'ultralytics'
Traceback (most recent call last):
  File "/home/hejiaqi18/.config/Ultralytics/DDP/_temp_2z60ejbv140349079716528.py", line 6, in <module>
    from ultralytics.models.yolo.classify.train import ClassificationTrainer
ModuleNotFoundError: No module named 'ultralytics'
Traceback (most recent call last):
  File "/home/hejiaqi18/.config/Ultralytics/DDP/_temp_2z60ejbv140349079716528.py", line 6, in <module>
    from ultralytics.models.yolo.classify.train import ClassificationTrainer
ModuleNotFoundError: No module named 'ultralytics'

**Comment by UltralyticsAssistant** [comment]
👋 Hello @hjq052070, thank you for your interest in Ultralytics 🚀! We recommend a visit to the [Docs](https://docs.ultralytics.com) for new and experienced users alike, where you can find many [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples and helpful guides to get started.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example (MRE)](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us reproduce and debug the issue.

Regarding your question, working on the source code directly (without installing via `pip`) for development purposes can certainly be done. Based on your description, the issue appears to stem from Distributed Data Parallel (DDP) processes failing to locate the `ultralytics` module when you haven't installed it via `pip`. It looks like you'll need to correctly set your Python environment to recognize the directory as a package.

An Ultralytics engineer will assist you shortly to provide more insights and specific guidance 💡.

While you wait, feel free to explore the following resources for additional help or to connect with the broader Ultralytics community:

- Join [Discord](https://discord.com/invite/ultralytics) 🎧 for real-time support and discussions.
- Visit our [Discourse](https://community.ultralytics.com) for in-depth discussions and solutions.
- Share insights and questions on our [Subreddit](https://reddit.com/r/Ultralytics).

## Upgrade

Ensure that you are working in a [**Python>=3.8**](https://www.python.org/) environment and that your dependencies like [PyTorch](https://pytorch.org/get-started/locally/) are up to date. If you're still using the latest pip-installed version alongside the source code, you can upgrade the package with:

```bash
pip install -U ultralytics
```

## Environments

Ultralytics supports a variety of environments for running YOLO workflows:

- **Notebooks** with ready-to-use GPUs: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Cloud Instances** like Google Cloud or AWS (See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) and [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/))
- **Docker** configurations available in our [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/): <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

You can also check our CI pipeline status for updates:  
<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

This badge indicates whether all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests—covering supported modes, tasks, and systems—are passing.

**Comment by hjq052070** [comment]
> You can install a local folder by running `pip install -e .` (dot at the end) inside the folder

thank you!
