### ISSUE TITLE
why this repo name not yolov8 but  ultralytics ?

### ISSUE THREAD

**Issue by wstchhwp** [ultralytics/ultralytics#179]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

why this repo name not yolov8 but  ultralytics ?

**Comment by AyushExel** [comment]
Because This repo is a framework. It can be used to train any model not just YOLOv8. We'll add support for more YOLO and non-YOLO models
See more details here https://github.com/ultralytics/ultralytics

**Comment by zhiqwang** [comment]
To put it another way, these names (yolov5, yolov6, yolov7, yolov8) have been taken by third parties on pypi.org, and I think ultralytics will most likely not adopt this name if they want to make this framework been installed through `pip install ...`
