### ISSUE TITLE
Should Instances objects be allowed to have self.segments set to None?

### ISSUE THREAD

**Issue by EchoLynx** [ultralytics/ultralytics#17923]
In ultralytics/data/augment.py, there's a "Format" transform whose [docstring](https://github.com/ultralytics/ultralytics/blob/dbdb451512ad4b3c636e6d61ad7af31e07301ece/ultralytics/data/augment.py#L2006) says its job is to format image annotations into a standard format for use with a PyTorch DataLoader 'collate_fn'.

One of the parameters of this transformation is, "An Instances object containing bounding boxes, segments, and keypoints."

It looks like the class definition for an Instances object is in ultralytics/utils/instance.py, and its [docstring](https://github.com/ultralytics/ultralytics/blob/dbdb451512ad4b3c636e6d61ad7af31e07301ece/ultralytics/utils/instance.py#L196) says that the segments and keypoints parameters are optional and will be None by default.

But if I create an Instances object with segments set to None, as they are by default, and then pass the Instances object as a parameter to the Format transform, I get the following error:

```
.../venv/lib/python3.10/site-packages/ultralytics/utils/instance.py", line 258, in denormalize
    self.segments[..., 0] *= w
TypeError: 'NoneType' object is not subscriptable
```
Upon further inspection, it looks like the Instances class' denormalize() method tries to operate on segments without first checking if it's None, like it is by default.

https://github.com/ultralytics/ultralytics/blob/dbdb451512ad4b3c636e6d61ad7af31e07301ece/ultralytics/utils/instance.py#L258

And the Format transform calls denormalize():

https://github.com/ultralytics/ultralytics/blob/dbdb451512ad4b3c636e6d61ad7af31e07301ece/ultralytics/data/augment.py#L2039

This seems like a bug to me. But how to fix it?  Should an Instances be allowed to have a None segments?

**Comment by UltralyticsAssistant** [comment]
👋 Hello @EchoLynx, thank you for bringing this up and for your detailed explanation 🚀! We'll look into this issue.

To help us debug, could you please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) demonstrating how you are encountering this error? This will assist us in isolating the issue further and understanding the specific conditions leading to the bug 🐛.

In the meantime, if you haven’t already, ensure that you upgrade to the latest version of the `ultralytics` package and verify if the issue persists. To upgrade:

```bash
pip install -U ultralytics
```

You can also explore our [Docs](https://docs.ultralytics.com) for additional guidelines, and feel free to reach out for real-time community support on our [Discord](https://discord.com/invite/ultralytics) 🎧 or join discussions on our [Discourse](https://community.ultralytics.com) and [Subreddit](https://reddit.com/r/Ultralytics).

## Relevant Environments

If you'd like to test in a verified environment, Ultralytics supports several out-of-the-box setups with all dependencies preinstalled, including free GPU-powered notebooks:
- **Paperspace Gradient**: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a>
- **Google Colab**: <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle**: <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Alternatively, our [Docker Image](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) is also available for containerized setups: <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing. CI tests verify correct operation of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) on macOS, Windows, and Ubuntu every 24 hours and on every commit.

Our team will investigate this further, and an Ultralytics engineer will follow up with you soon. Thank you for contributing to the improvement of the Ultralytics repository! 🚀

**Comment by Y-T-G** [comment]
I guess it's supposed to be empty array.

https://github.com/ultralytics/ultralytics/blob/dbdb451512ad4b3c636e6d61ad7af31e07301ece/ultralytics/data/dataset.py#L225

**Comment by EchoLynx** [comment]
> It's probably easier to use an empty array because then you can perform any numpy operation on it and it will return nothing instead of throwing an error. It will remove the need to check if it's None every time.

Agreed, and that's exactly what I did. Thank you.

**Comment by glenn-jocher** [comment]
You're welcome! Glad to hear it worked for you. If you have any further questions, feel free to ask.
