### ISSUE TITLE
HOW CAN I SAVE THE NUMBER OF DETECTION DATA THAT GENERATES ON CMD AFTER DETECTION.

### ISSUE THREAD

**Issue by doomslayer1434** [ultralytics/ultralytics#1792]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

image 1/1 D:\virtualenv\yolov8_custom\50.jpg: 448x640 **_31 persons_**, 1558.2ms
Speed: 2.0ms preprocess, 1558.2ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)   

Iam using the yoloV8l algorithm trained on my custom dataset to detect the heads of people and  
I get the number of predictions on my image in the cmd  when I run the python script just like I've shown above , but my question is how do I extract this data that says number of detections and use it in some other calculations that I want to do in other python scripts .Please help me my project deadline is near

### Additional

![image](https://user-images.githubusercontent.com/117589442/229565041-0fccfcf7-a2ee-4dcf-88fa-17765f3a5d45.png)

**Comment by Marco-Nguyen** [comment]
Hope this is not late for you. You can extract the number of detections per image/frame [here](https://github.com/ultralytics/ultralytics/blob/37274c9845e5626f4a2b419a50cb8e8e889052c2/ultralytics/yolo/v8/detect/predict.py#L60)

```
        for c in det.cls.unique():
            n = (det.cls == c).sum()  # detections per class
            log_string += f"{n} {self.model.names[int(c)]}{'s' * (n > 1)}, "
```

**Comment by doomslayer1434** [comment]
> 

Thankyou so much for your response. It really helped me a lot.

**Comment by glenn-jocher** [comment]
@doomslayer1434 i'm glad to hear that you found the information useful! It's always rewarding to see our efforts make a difference. If you have any additional questions or need further clarification on any aspects of YOLOv8, please don't hesitate to ask. The Ultralytics team and the wider YOLO community are here to assist. Stay connected and keep exploring the wonderful world of YOLOv8!
