### ISSUE TITLE
Inference YOLOv8s model with TensorRT(C++)

### ISSUE THREAD

**Issue by Stoooner** [ultralytics/ultralytics#1799]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

## 1. Datasets
- **Training Datasets**: [Singapore Maritime Dataset (SMD) 数据集;](https://sites.google.com/site/dilipprasad/home/singapore-maritime-dataset)
- **Testing Dataset**: SMD_Test_Videos/MVI_1471_VIS.avi
- **Testing Video Dims**: $1920 \times 1080$;
- **Testing Video Frame Rate**: $30\ FPS$;
- **Sample picture**:
![SMD_data](https://user-images.githubusercontent.com/31228436/229659129-14bb56a2-2e59-4199-8799-61b1ed3bca3a.png)

### 2.1 x86_84 Platform

- **Model_Version**: YOLOv8s
- **System_Version**: Ubuntu20.04;
- **GPU_Version**: Quadro RTX 5000(16G RAM);
- **GCC_Version**: 9.4.0;
- **CMake_Version**: 3.16.3;
- **CUDA_Version**: 11.5;
- **CUDNN_Version**: 8.3.2;
- **OpenCV_Version**: 4.5.4;
- **TensorRT_Version**: 8.4.3.1;
- **Avg_FPS_1**: ~200 FPS(CPU Preprocess+PostProcess+FP16)
- **Avg_FPS_2**: ~290 FPS(CUDA Preprocess+PostProcess+FP16)
- **NewResult_Avg_FPS_1**: ~233 FPS(CPU Preprocess+PostProcess+int8)
- **NewResult_Avg_FPS_2**: ~347 FPS(CUDA Preprocess+PostProcess+int8)

### 2.2 Jetson Agx Xavier

- **Model_Version**: YOLOv8s
- **System_Version**: Ubuntu20.04(aarch64);
- **Jetpack_Version**: Jetpack5.1
- **GCC_Version**: 9.4.0;
- **CMake_Version**: 3.16.3;
- **CUDA_Version**: 11.4.315;
- **CUDNN_Version**: 8.6.0.166;
- **OpenCV_Version**: 4.5.4 with CUDA YES;
- **TensorRT_Version**: 8.5.2.2;
- **Avg_FPS_1**: ~75 FPS(CPU Preprocess+PostProcess)
- **Avg_FPS_2**: ~100 FPS(CUDA Preprocess+PostProcess)
- **NewResult_Avg_FPS_1**: ~90 FPS(CPU Preprocess+PostProcess+int8)
- **NewResult_Avg_FPS_2**: ~138 FPS(CUDA Preprocess+PostProcess+int8)

**Comment by glenn-jocher** [comment]
Thank you for providing such detailed information about your datasets and test platform configuration, @lzmcty. Regarding your question, could you please provide more context or clarify your question so that we can better understand what you need help with? Any additional details would be much appreciated.

**Comment by Stoooner** [comment]
> Thank you for providing such detailed information about your datasets and test platform configuration, @lzmcty. Regarding your question, could you please provide more context or clarify your question so that we can better understand what you need help with? Any additional details would be much appreciated.

Thank you so much， I have no no any question. It's just for my practices info record. Thank you so much again.

**Comment by CasparQuast** [comment]
Hello Stoooner,

it seems like you tried out int8 quantization on with your yolov8 model with TensorRT in c++.
Would you mind sharing the code for the calibration of the model? I am currently using yolov8 .engine with fp16 quantization but didnt find good examples and clear instructions on how to set up the calibration for int8. Im happy about any tips & references.

Regards,
Caspar

**Comment by glenn-jocher** [comment]
@CasparQuast hello Caspar, 

Thank you for your interest in using YOLOv8 with TensorRT and for reaching out to the community for support. Regarding int8 quantization with TensorRT and YOLOv8, I can only suggest the following general guidelines:
 
1. First, you should generate the float .engine and .uff files of your YOLOv8 model with TensorRT, and ensure that it works correctly.
2. Then, you should use the provided TensorRT calibration tool to generate a calibration table by running inference on a set of representative images. During the calibration, images are passed through the network using TensorRT, with the values collected being used to determine the optimal scale factors that minimize the difference between the actual output ranges and the target dynamic range.
3. Finally, you should use the calibration table to generate an int8 TensorRT engine from the .uff file using TensorRT.

While we cannot provide code examples, you can find more detailed instructions on how to set up the calibration process in the TensorRT documentation. TensorRT is a powerful library and has excellent online documentation with including examples, samples, and frequently asked questions that can help you customize and refine your calibration process.

I hope this helps. Good luck with your YOLOv8 project with TensorRT. If you have any additional questions, feel free to ask the YOLOv8 community.
