### ISSUE TITLE
 ModuleNotFoundError: No module named 'ultralytics.yolo.v8.detect.some_module'

### ISSUE THREAD

**Issue by yeongnamtan** [ultralytics/ultralytics#1800]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

%pip install ultralytics

import ultralytics
ultralytics.checks()

Name: ultralytics
Version: 8.0.3

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-8-f3c6b5ebba3f> in <module>
      1 get_ipython().run_line_magic('pip', 'install ultralytics')
      2 
----> 3 import ultralytics
      4 ultralytics.checks()

~/ultralytics-main/ultralytics/__init__.py in <module>
      3 __version__ = "8.0.3"
      4 
----> 5 from ultralytics.hub import checks
      6 from ultralytics.yolo.engine.model import YOLO
      7 from ultralytics.yolo.utils import ops

~/ultralytics-main/ultralytics/hub/__init__.py in <module>
     13 from ultralytics.yolo.utils import LOGGER, emojis, is_colab
     14 from ultralytics.yolo.utils.torch_utils import select_device
---> 15 from ultralytics.yolo.v8.detect import DetectionTrainer
     16 
     17 

~/ultralytics-main/ultralytics/yolo/__init__.py in <module>
      1 # Ultralytics YOLO 🚀, GPL-3.0 license
      2 
----> 3 from . import v8

~/ultralytics-main/ultralytics/yolo/v8/__init__.py in <module>
      3 from pathlib import Path
      4 
----> 5 from ultralytics.yolo.v8 import classify, detect, segment
      6 
      7 ROOT = Path(__file__).parents[0]  # yolov8 ROOT

~/ultralytics-main/ultralytics/yolo/v8/detect/__init__.py in <module>
      5 from .val import DetectionValidator, val
      6 
----> 7 from .some_module import SomeClass, some_function
      8 
      9 #__all__ = ['SomeClass', 'some_function', 'DEFAULT_CONFIG']

**ModuleNotFoundError: No module named 'ultralytics.yolo.v8.detect.some_module'**

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@antonioaguado, thank you for your question. The error message suggests that a `ModuleNotFoundError` has occurred because some module is missing at `ultralytics.yolo.v8.detect.some_module`. To resolve this issue, please make sure that you have installed YOLOv8 correctly following the installation instructions provided in the [YOLOv8 Docs](https://docs.ultralytics.com). If the error still persists, please try re-installing YOLOv8 and updating the `ultralytics` package to the latest version available. If you're still experiencing issues, please provide more information about your environment, operating system, and Python version.

**Comment by yeongnamtan** [comment]
i have tried re-installing YOLOV8 and updating the ultralytics package.
I am running this on AWS sagemaker.

The funny thing is that when I use the previous trained weights, I had no
issue.  But after doing further training, I get stuck here.   I did the
training twice to be sure it is not due to training.

[2023-04-04 04:26:34,567][root.tracker][INFO] - Loading weights from
deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7... Done!
Ultralytics YOLOv8.0.3 🚀 Python-3.8.16 torch-1.12.1+cu113 CUDA:0
(Tesla T4, 15110MiB)
Error executing job with overrides:
['model=/root/ultralytics-main_old/ultralytics/yolo/v8/detect/runs/detect/train3/weights/best.pt',
'source=/root/Yolov5_DeepSort_Pytorch/VideosForTracking/video_2023-04-03_09-26-37_reducedspeed_Part2.mp4']
Traceback (most recent call last):
  File "tracking_fish_counting.py", line 322, in predict
    predictor()
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py",
line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/ultralytics-main/ultralytics/yolo/engine/predictor.py",
line 164, in __call__
    model = self.model if self.done_setup else self.setup(source, model)
  File "/root/ultralytics-main/ultralytics/yolo/engine/predictor.py",
line 121, in setup
    model = AutoBackend(model, device=device, dnn=self.args.dnn,
fp16=self.args.half)
  File "/root/ultralytics-main/ultralytics/nn/autobackend.py", line
73, in __init__
    model = attempt_load_weights(weights if isinstance(weights, list) else w,
  File "/root/ultralytics-main/ultralytics/nn/tasks.py", line 303, in
attempt_load_weights
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py",
line 712, in load
    return _load(opened_zipfile, map_location, pickle_module,
**pickle_load_args)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py",
line 1049, in _load
    result = unpickler.load()
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py",
line 1042, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'IterableSimpleNamespace' on
<module 'ultralytics.yolo.utils' from
'/root/ultralytics-main/ultralytics/yolo/utils/__init__.py'>

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by AyushExel** [comment]
You're using 8.0.3 release which is very outdated. Please upgrade to the latest version using `pip install --upgrade ultralytics` and let us know if the problem still exists

**Comment by glenn-jocher** [comment]
@yeongnamtan it seems that even after upgrading to the latest version of Ultralytics, you are still facing issues with `import` statements. Specifically, the error `ImportError: cannot import name 'DEFAULT_CONFIG' from 'ultralytics.yolo.utils'` indicates that there is an issue with importing a specific module from the `ultralytics.yolo.utils` package.

One possible solution is to ensure that all dependencies are up to date and that you have installed YOLOv8 correctly as described in the installation guide provided in the YOLOv8 Docs. Another possibility is to check if the module you are trying to import is present in the package path, and if it is not, try adding the path to the package to the system path using the `sys.path.append()` method.

**Comment by yeongnamtan** [comment]
i discovered something interesting:

when I use below CLI format with my own weights, it works okay.
*yolo track model=yolov8n.pt <http://yolov8n.pt> source=pathtomymp4
conf=0.3, iou=0.5 save=True*

But when I use below, I get the attributerror.  I don't have this issue
before.
*!python tracking.py model=yolov8n.pt <http://yolov8n.pt>
source=pathtomymp4 conf=0.3, iou=0.5 save=True*

Traceback (most recent call last):
  File "/root/ultralytics-main/ultralytics/yolo/v8/detect/tracking_fish_counting.py",
line 317, in <module>
    @hydra.main(version_base=None,
config_path=str(DEFAULT_CFG.parent), config_name=DEFAULT_CFG.name)
AttributeError: 'IterableSimpleNamespace' object has no attribute 'parent'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

**Comment by glenn-jocher** [comment]
@yeongnamtan it seems that you are able to use your own weights with the `yolo track` command-line interface (CLI), but face an attribute error when running the tracking script using `!python tracking.py` command. 

One possible explanation for this could be the difference in how the commands are executed. The `yolo track` command may be using a different set of configurations, while the tracking script may be expecting certain arguments passed in a specific format.

To address the attribute error, you can try updating your code to use the correct attribute name instead of `parent`. Additionally, you can try printing out the arguments that are received by the script to check if they are in the expected format.

**Comment by yeongnamtan** [comment]
I just want a line across to count the number of fish swimming across.
This is for a fish farm project

**Comment by glenn-jocher** [comment]
@yeongnamtan thank you for clarifying the intended use of YOLOv8 for your project. 

To add a counting functionality, you can retrieve the number of detections from each frame using the YOLOv8 detect function, and then increment a counter for each detection. To track the number of fish crossing a line, you can draw a line across the screen and use object tracking to determine when a detected object (fish) intersects or crosses the line. Whenever a fish is detected crossing the line, you can increment a separate counter to keep track of the count. 

Additionally, you can consider using OpenCV or other image processing libraries to help with drawing the line and tracking objects.

**Comment by yeongnamtan** [comment]
i have the OpenCV code with the line and counter  inside the tracking.py
file but it can't run because of the below error.  It was running okay
until I did a new training on custom dataset this week.

can I somehow incorporate those OpenCV code into YOLO track CLI command? if
so, how ?

Traceback (most recent call last):
  File "/root/ultralytics-main/ultralytics/yolo/v8/detect/tracking_fish_counting.py",
line 19, in <module>
    from yolo.utils import DEFAULT_CONFIG
ImportError: cannot import name 'DEFAULT_CONFIG' from 'yolo.utils'
(/opt/conda/lib/python3.9/site-packages/ultralytics/yolo/utils/__init__.py)
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

**Comment by glenn-jocher** [comment]
@yeongnamtan it seems that you are getting an error in the YOLOv8 tracking script when trying to import the `DEFAULT_CONFIG` attribute from the `yolo.utils` module. This error could be due to a change in the YOLOv8 implementation or a compatibility issue with the dependencies. It may be helpful to check the version of YOLOv8 you are using and ensure it is compatible with your current dependencies.

Regarding incorporating OpenCV code into the YOLO track CLI command, you can add the OpenCV code to the tracking script and use it in conjunction with the YOLOv8 detect function. The OpenCV code can be used to draw a line on the screen and track the objects detected by YOLOv8 to determine if they cross the line. This will require making changes to the tracking script, possibly by adding code to the `tracking.py` file or creating a new python script that integrates YOLOv8 and OpenCV.

**Comment by yeongnamtan** [comment]
Thank you.  I added the OpenCV code into tracking.py and use the YOLO CLI
command as follows:

!yolo task=tracking_fish_counting  mode=predict  model=
pathtomybestweights  conf=0.25 source=video.mp4 save=True

The tracking of the fish is there but somehow the line and counter is not
shown in the output.

**Comment by yeongnamtan** [comment]
How do I add the OpenCV code to the tracking script ?
[image: image.png]

**Comment by glenn-jocher** [comment]
@yeongnamtan to add the OpenCV code to the tracking script, you need to modify the `tracking.py` file. In particular, you would want to integrate the code that draws the line on the screen and tracks objects with the YOLOv8 object tracking functionality. These changes could involve adding code to define the line and drawing it on the screen, implementing object tracking to detect when a fish crosses the line, and incrementing a counter each time a fish is detected passing the line. The specific changes needed will depend on the details of your OpenCV code and how you want to incorporate it with YOLOv8.

**Comment by yeongnamtan** [comment]
I did add the OpenCV code into tracking.py (i called it
'tracking_fish-counting.py'), and use the YOLO CLI command as follows:

*!yolo task=tracking_fish_counting  mode=predict  model=
pathtomybestweights  conf=0.25 source=video.mp4 save=True*

Somehow the line and counter is still not shown in the output.

**Comment by glenn-jocher** [comment]
@yeongnamtan it looks like the changes you made to `tracking_fish-counting.py` to add the OpenCV code are not resulting in the expected output. It's possible that there may be an issue with the integration between the YOLOv8 object tracking functionality and the OpenCV code, or that there may be a mistake in the implementation of the OpenCV code. It may be helpful to further troubleshoot the code to identify the root cause of the issue and make necessary modifications.

**Comment by yeongnamtan** [comment]
Can you advise if this command line is correct for doing tracking?
*!yolo track model=pathtomyweights.pt <http://pathtomyweights.pt>
 conf=0.25 source=pathtovideomp4 save=True*

If so, which python file should I use to add the OpenCV code?

Thank you for your patience.

**Comment by glenn-jocher** [comment]
@yeongnamtan yes, the command line you provided is correct for running YOLOv8 object tracking on a video and saving the output. To add OpenCV code to the YOLOv8 object tracking, you can modify the `tracking.py` file in the YOLOv8 repository located in the `yolo/scripts/` directory. More specifically, you can add the necessary OpenCV code to the `draw_tracking_frame` function in the `tracking.py` file, which is responsible for drawing bounding boxes and other tracking-related visualizations on each frame of the video.

**Comment by Dacrikka** [comment]
*** Error running postprocess_image: G:\Edo\Programmi_Installati\Stable\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "G:\Edo\Programmi_Installati\Stable\stable-diffusion-webui\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "G:\Edo\Programmi_Installati\Stable\stable-diffusion-webui\extensions\adetailer\adetailer\traceback.py", line 159, in wrapper
        raise error from None
    ModuleNotFoundError:
    ╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
    │                                                        System info                                                         │
    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃             ┃ Value                                                                                                    ┃ │
    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │    Platform │ Windows-10-10.0.19045-SP0                                                                                │ │
    │ │      Python │ 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]                         │ │
    │ │     Version │ v1.6.0                                                                                                   │ │
    │ │      Commit │ 5ef669de080814067961f28357256e8fe27544f4                                                                 │ │
    │ │ Commandline │ ['launch.py', '--autolaunch', '--xformers']                                                              │ │
    │ │   Libraries │ {'torch': '2.0.1+cu118', 'torchvision': '0.15.2+cu118', 'ultralytics': 'Unknown', 'mediapipe': '0.10.7'} │ │
    │ └─────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                                                           Inputs                                                           │
    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃                 ┃ Value                                                                                                ┃ │
    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │          prompt │ Zaida Zainab, 28 year old arabic amazing woman, long brown hair, working at a medical lab            │ │
    │ │                 │ <lora:breastsizeslideroffset:0.4> <lora:epiCRealLife:0.5> <lora:epiCRealismHelper:0.5>               │ │
    │ │                 │ <lora:more_details:0.5>                                                                              │ │
    │ │ negative_prompt │                                                                                                      │ │
    │ │          n_iter │ 1                                                                                                    │ │
    │ │      batch_size │ 1                                                                                                    │ │
    │ │           width │ 350                                                                                                  │ │
    │ │          height │ 512                                                                                                  │ │
    │ │    sampler_name │ DPM++ 2M SDE Karras                                                                                  │ │
    │ │       enable_hr │ True                                                                                                 │ │
    │ │     hr_upscaler │ R-ESRGAN 4x+                                                                                         │ │
    │ │      checkpoint │ epicphotogasm_xPlusPlus.safetensors [00debdee15]                                                     │ │
    │ │             vae │ Automatic                                                                                            │ │
    │ │            unet │ Automatic                                                                                            │ │
    │ └─────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                                         ADetailer                                                                          │
    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                  │
    │ ┃                     ┃ Value                                                           ┃                                  │
    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩                                  │
    │ │             version │ 23.10.1                                                         │                                  │
    │ │            ad_model │ face_yolov8n.pt                                                 │                                  │
    │ │           ad_prompt │ Zaida Zainab, 28 year old arabic amazing woman, long brown hair │                                  │
    │ │  ad_negative_prompt │                                                                 │                                  │
    │ │ ad_controlnet_model │ None                                                            │                                  │
    │ │              is_api │ False                                                           │                                  │
    │ └─────────────────────┴─────────────────────────────────────────────────────────────────┘                                  │
    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮                       │
    │ │ G:\Edo\Programmi_Installati\Stable\stable-diffusion-webui\extensions\adetailer\adetailer\traceba │                       │
    │ │ ck.py:139 in wrapper                                                                             │                       │
    │ │                                                                                                  │                       │
    │ │   136 │   │   width = width - 4 if width > 4 else None                                           │                       │
    │ │   137 │   │   console = Console(file=string, width=width)                                        │                       │
    │ │   138 │   │   try:                                                                               │                       │
    │ │ ❱ 139 │   │   │   return func(*args, **kwargs)                                                   │                       │
    │ │   140 │   │   except Exception as e:                                                             │                       │
    │ │   141 │   │   │   tables = [                                                                     │                       │
    │ │   142 │   │   │   │   get_table(title, data)                                                     │                       │
    │ │                                                                                                  │                       │
    │ │ G:\Edo\Programmi_Installati\Stable\stable-diffusion-webui\extensions\adetailer\scripts\!adetaile │                       │
    │ │ r.py:732 in postprocess_image                                                                    │                       │
    │ │                                                                                                  │                       │
    │ │   729 │   │   │   for n, args in enumerate(arg_list):                                            │                       │
    │ │   730 │   │   │   │   if args.ad_model == "None":                                                │                       │
    │ │   731 │   │   │   │   │   continue                                                               │                       │
    │ │ ❱ 732 │   │   │   │   is_processed |= self._postprocess_image_inner(p, pp, args, n=n)            │                       │
    │ │   733 │   │                                                                                      │                       │
    │ │   734 │   │   if is_processed and not getattr(p, "_ad_skip_img2img", False):                     │                       │
    │ │   735 │   │   │   self.save_image(                                                               │                       │
    │ │                                                                                                  │                       │
    │ │ G:\Edo\Programmi_Installati\Stable\stable-diffusion-webui\extensions\adetailer\scripts\!adetaile │                       │
    │ │ r.py:657 in _postprocess_image_inner                                                             │                       │
    │ │                                                                                                  │                       │
    │ │   654 │   │   │   kwargs["device"] = self.ultralytics_device                                     │                       │
    │ │   655 │   │                                                                                      │                       │
    │ │   656 │   │   with change_torch_load():                                                          │                       │
    │ │ ❱ 657 │   │   │   pred = predictor(ad_model, pp.image, args.ad_confidence, **kwargs)             │                       │
    │ │   658 │   │                                                                                      │                       │
    │ │   659 │   │   masks = self.pred_preprocessing(pred, args)                                        │                       │
    │ │   660 │   │   shared.state.assign_current_image(pred.preview)                                    │                       │
    │ │                                                                                                  │                       │
    │ │ G:\Edo\Programmi_Installati\Stable\stable-diffusion-webui\extensions\adetailer\adetailer\ultraly │                       │
    │ │ tics.py:19 in ultralytics_predict                                                                │                       │
    │ │                                                                                                  │                       │
    │ │   16 │   confidence: float = 0.3,                                                                │                       │
    │ │   17 │   device: str = "",                                                                       │                       │
    │ │   18 ) -> PredictOutput:                                                                         │                       │
    │ │ ❱ 19 │   from ultralytics import YOLO                                                            │                       │
    │ │   20 │                                                                                           │                       │
    │ │   21 │   model = YOLO(model_path)                                                                │                       │
    │ │   22 │   pred = model(image, conf=confidence, device=device)                                     │                       │
    │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯                       │
    │ ModuleNotFoundError: No module named 'ultralytics'                                                                         │

**Comment by Dacrikka** [comment]
I got this message... but i can't figured out the problem...some help?

**Comment by glenn-jocher** [comment]
@Dacrikka hello,

First of all, thank you for reaching out to us. It sounds like you're having trouble, but in order for us to provide the best assistance, we'll need some additional details about the issue you're experiencing. Please could you provide more information about the exact error message you're seeing, as well as some context about what you're trying to do when the problem occurs? Particularly, if you could specify what steps you've taken that led to the issue, we'll be in a better position to help. Please also let us know about any specific elements of YOLOv8 you're working with.

Looking forward to your response and we'll do our best to help you resolve the issue.

Best regards.

**Comment by Dacrikka** [comment]
Hi! Thank u for the kind reply! I'm just having some troubles with Adetailer for Stable Diffusion. 
I think I have everything installed, including Ultralytics model (pip install ultralytics) ... but something is wrong and the message you see above appears when I try to use Adetalier in SD. In addition I attach a check

Ultralytics YOLOv8.0.200 Python-3.10.6 torch-2.1.0+cpu CPU (AMD Ryzen 9 3900X 12-Core Processor)
Setup complete (24 CPUs, 63.9 GB RAM, 290.4/475.6 GB disk)

OS Windows-10-10.0.19045-SP0
Environment Windows
Python 3.10.6
Install pip
RAM 63.94 GB
CPU AMD Ryzen 9 3900X 12-Core Processor
CUDA None
GPU 4060ti 16gb

matplotlib 3.8.0>=3.3.0
numpy 1.26.0>=1.22.2
opencv-python 4.8.1.78>=4.6.0
pillow 10.0.1>=7.1.2
pyyaml 6.0.1>=5.3.1
requests 2.31.0>=2.23.0
scipy 1.11.3>=1.4.1
torch 2.1.0>=1.8.0
torchvision 0.16.0>=0.9.0
tqdm 4.66.1>=4.64.0
pandas 2.1.1>=1.1.4
seaborn 0.13.0>=0.11.0
psutil 5.9.6
py-cpuinfo 9.0.0
thop 0.1.1-2209072238>=0.1.1

**Comment by glenn-jocher** [comment]
@Dacrikka hello,

Thank you for taking the time to provide in-depth information about your issue and your system setup.

Based on the details you've shared, it seems like the problem could be derived from mismatched library versions, specifically, your PyTorch version (torch 2.1.0) seems a bit off. As of my current knowledge, PyTorch's latest version is 1.10.2 and not 2.1.0. So, please start by ensuring you have the correct PyTorch installed.

Additionally, there could be a compatibility issue with Python 3.10.6. Keep in mind, not all libraries have been updated to fully support this version yet.

Lastly, make sure CUDA is properly installed and correctly configured with PyTorch if you're looking to use your GPU. I notice you've listed "CUDA None," which suggests that it possibly isn't recognized.

Try rectifying these and let us know if the problem persists. We're here to help!

Best,
