### ISSUE TITLE
Multiple columns classification ?

### ISSUE THREAD

**Issue by ExtReMLapin** [ultralytics/ultralytics#1807]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,
Is there any plan to do multiple columns classification for YoloV8 ?

Example : 

instead of having only the classes : "dog", "cat", "racoon".

You would instead have ["dog" "cat" "racoon"], and ["dirty", "clean", "wet"]

Or another example : ["car", "truck", "bike"] and ["factory new", "used", "rusty"]

Thanks.

**Comment by ExtReMLapin** [comment]
Already supported according to this https://github.com/ultralytics/yolov5/issues/1811

**Comment by glenn-jocher** [comment]
@ExtReMLapin, glad to hear that you found the answer to your question in the YOLOv5 Issues section! It looks like there has been a discussion about implementing multiple column classification in YOLOv5, and according to that thread it is possible with some modifications. However, I would like to clarify that Ultralytics YOLOv8 is an independent fork of YOLOv5 and does not have that feature out of the box. Nonetheless, it is open source, so if this feature is important to your use case, you can extend the code to include it. Feel free to ask more questions if you need further assistance!
