### ISSUE TITLE
How to ignore settings.yaml file?

### ISSUE THREAD

**Issue by haimat** [ultralytics/ultralytics#1809]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have seen that recently a system-wide `settings.yaml` file in the user's home directory has been introduced in YOLOv8. That file configures the global path to the training datasets. However, we don't have such a system-wide dataset folder. Instead different projects use different root folders. When using the `ultralytics` Python API, how can I completely ignore that global `settings.yaml` file and use the `model.train(data=local-config.yaml)` option only?

**Comment by glenn-jocher** [comment]
@haimat you can completely ignore the global `settings.yaml` file and use local training datasets by specifying the `data` parameter followed by the path of a local configuration YAML file when running `model.train()`. This will allow you to use different root folders for different projects. Make sure to reference the correct path in your local configuration YAML file for your training dataset. Also, please note that the global `settings.yaml` file is a convenient way for setting up a common dataset path across different scripts and projects.

**Comment by haimat** [comment]
@glenn-jocher Thanks, but it seems there is a bug then - I do have specified the `data=local.yaml` parameter at the call to `train()`, but the YOLOv8 trainer still concatenates the `dataset` value from the global `settings.yaml` file and the value from the `local.yaml` file into one long directory path. Do you need a separete bug report?

**Comment by glenn-jocher** [comment]
@haimat, if you have specified the `data` parameter for `model.train()` method call with a local YAML file, it should override the dataset path specified in the global `settings.yaml` file. However, if you are still experiencing issues where the code appends the paths together, it would be best to create a separate bug report with details of the error, the code used, and any other relevant information to help us understand the issue better.

**Comment by katrinmisel** [comment]
If you want to override the `settings.yaml` file, you can do this by adding a `path:` line in your `data.yaml` file to precise the folder containing your datasets. If your directory tree is as such:

project_dir
> dataset_dir
> > test
> > train
> > valid

Then add the "path: " line to your data.yaml: 

```
[...]
path: D:/project_dir
test: ../test/images
train: dataset_dir/train/images
val: dataset_dir/valid/images
[...]
```

Then train with: 

`model.train(data='dataset_dir/data.yaml', [...])`

**Comment by glenn-jocher** [comment]
@katrinmisel that's correct, you can certainly specify the `path` field in your `data.yaml` file to tell YOLOv8 the location of your dataset, overriding the global `settings.yaml` file. Just ensure that the `path` field points to the correct directory where your dataset is located. In your case, it would be `D:/project_dir`.

With regards to your `test`, `train` and `val` fields in `data.yaml`, these paths should be relative to where the `data.yaml` file resides. Your command for starting the training process seems to be correct: `model.train(data='dataset_dir/data.yaml', [...])`. Just ensure that 'dataset_dir/data.yaml' is the correct path from your current working directory to your `data.yaml` file.

This configuration should help YOLOv8 correctly identify and access your project's unique dataset, ignoring the global `settings.yaml` file.

**Comment by pizixie** [comment]
I think that is a bug.
Because
`path:./datasets/test`
is a path that relative to project
Not relative to path in '~/.config/Ultralytics/settings.yaml'

**Comment by glenn-jocher** [comment]
@pizixie thank you for reaching out to report this behavior.

The `path` field in a `data.yaml` file should indeed be relative to the project directory by default. If you are observing that the `path` is resolving relative to the `settings.yaml` file in the Ultralytics configuration directory, then this could be an unintended behavior, and we appreciate your diligence in bringing this to our attention.

While the global `settings.yaml` is designed to streamline dataset paths across different projects, it should not interfere when a local `path` is explicitly defined in your project's `data.yaml` file.

It's important then, to ensure that when specifying the `path`, it is intended to be from the project root or working directory, and not the home directory `.config/Ultralytics/`.

We will look into this, and if confirmed as a bug, we'll work towards a fix in an upcoming release. Meanwhile, check your `data.yaml` and the project's working directory to ensure they align correctly. Also, ensure the global `settings.yaml` does not have conflicting settings that could affect your project.

I would recommend opening an issue on the Ultralytics YOLOv8 repository, providing details like your project directory structure, your `data.yaml` contents, and the exact behavior you're experiencing. This will help us reproduce the issue.

We value your contribution to the community and your patience as we investigate this matter. We aim to maintain robust and precise functionality in our frameworks, and user reports are a vital part of that process.

**Comment by RundownMouse** [comment]
It's been a while, but this information might still be useful to someone:

1) On a Windows 10 system, using a local `dataset.yaml` file with the `path:` element works as expected for me.

2) On Ubuntu (WSL2), this is not the case. However, by commenting out lines in the global `.config/Ultralytics/settings.yaml` file, like this:

```
#datasets_dir: /mnt/.../datasets
#weights_dir: /mnt/.../weights
#runs_dir: /mnt/.../runs
```

the system operates as expected, using relative paths from `dataset.yaml`.

**Comment by glenn-jocher** [comment]
@RundownMouse thank you for sharing your experience with different operating systems. It's good to hear that on Windows 10, specifying the `path:` in your `dataset.yaml` works without issues. For Ubuntu (WSL2), your solution to comment out the respective lines in the global `.config/Ultralytics/settings.yaml` file to ensure the system respects the local `dataset.yaml` paths is a practical workaround. Your insights are valuable to the community, and it's indeed helpful information for anyone who might encounter similar issues. If consistent behavior across platforms is not observed, we would encourage users to raise an issue on the repository so it can be investigated further. 👍🏼

**Comment by DimIsaev** [comment]
there must be a solution that can override variables from a file `.config/Ultralytics/settings.yaml`

**Comment by glenn-jocher** [comment]
@DimIsaev certainly! A straightforward solution to override variables from the `.config/Ultralytics/settings.yaml` file is to set them explicitly in your script or via environment variables. For example, in your Python script, you can set the paths directly like so:

```python
import os
from ultralytics import YOLO

# Override settings by directly setting them in the environment
os.environ["YOLO_DATASETS_DIR"] = "/path/to/your/datasets"
os.environ["YOLO_WEIGHTS_DIR"] = "/path/to/your/weights"
os.environ["YOLO_RUNS_DIR"] = "/path/to/your/runs"

# Now, initialize your YOLO model
model = YOLO('path/to/model.pt')
```

This way, you ensure that your specified directories are used for that script's execution, overriding the global settings! 🚀

**Comment by kaikcoder** [comment]
> @DimIsaev当然！覆盖`.config/Ultralytics/settings.yaml`文件中变量的一个简单解决方案是在脚本中或通过环境变量显式设置它们。例如，在 Python 脚本中，您可以直接设置路径，如下所示：
> 
> ```python
> import os
> from ultralytics import YOLO
> 
> # Override settings by directly setting them in the environment
> os.environ["YOLO_DATASETS_DIR"] = "/path/to/your/datasets"
> os.environ["YOLO_WEIGHTS_DIR"] = "/path/to/your/weights"
> os.environ["YOLO_RUNS_DIR"] = "/path/to/your/runs"
> 
> # Now, initialize your YOLO model
> model = YOLO('path/to/model.pt')
> ```
> 
> 这样，您可以确保指定的目录用于该脚本的执行，从而覆盖全局设置！ 🚀
这个设置还是没用

**Comment by glenn-jocher** [comment]
@kaikcoder 抱歉听到您遇到了问题！尝试直接在环境变量中设置路径应该会覆盖全局的`settings.yaml`配置。如果这个方法没有奏效，可能存在其他问题。为了帮助您更快地解决这个问题，我们建议您在初始化YOLO模型**之前**确保设置了环境变量。这是非常关键的一步。如果问题仍然存在，请确保您的`ultralytics`库是最新版本的，或者考虑提交一个issue到GitHub仓库以便我们进一步帮助您！🌟

**Comment by MarkhamLee** [comment]
Instead of having all of these work arounds to override the input data directory of the system wide settings file, can it just be removed all together in favor of just following whatever we have in our data.yaml file? Many of us are working on a wide variety of projects for multiple stakeholders, customers or research projects, and it wouldn't make much sense for us to have a single directory full of datasets and training results that have nothing to do with each other. As it stands now it's very easy for someone to accidentally train a model with the wrong data, forget to change the setting as they start a new project etc., going back to just using what's in the data.yaml file would be a lot more user friendly.

**Comment by DimIsaev** [comment]
> Many of us are working on a wide variety of projects for multiple stakeholders, customers or research projects, and it wouldn't make much sense for us to have a single directory full of datasets and training results that have nothing to do with each other. As it stands now it's very easy for someone to accidentally train a model with the wrong data, forget to change the setting as they start a new project etc., going back to just using what's in the data.yaml file would be a lot more user friendly.

Yes this very important

**Comment by glenn-jocher** [comment]
@DimIsaev thank you for your feedback! We understand the challenges of managing multiple projects with diverse datasets and the potential for confusion with a single global settings file. Your suggestion to rely solely on the `data.yaml` file for dataset paths is valid and could indeed simplify project management.

To address this, we recommend the following steps to ensure your local `data.yaml` settings are prioritized:

1. **Local Configuration Override**: Ensure your `data.yaml` file is correctly configured with relative paths specific to each project. This should take precedence over global settings.
   
2. **Environment Variables**: As a temporary measure, you can set environment variables at the start of your script to override global settings:
   ```python
   import os
   from ultralytics import YOLO

   os.environ["YOLO_CONFIG_DIR"] = "./local_config"
   model = YOLO('path/to/model.pt')
   ```

3. **Custom Configuration Directory**: Create a custom configuration directory for each project and set the `YOLO_CONFIG_DIR` environment variable to point to it. This ensures each project uses its own settings.

We are continuously working to improve the usability of our tools, and your input is invaluable. If you encounter any issues or have further suggestions, please let us know. For now, please verify that you are using the latest version of the `ultralytics` package to ensure all recent updates and fixes are applied.

For a more detailed discussion or to report specific issues, feel free to open an issue on our GitHub repository with a reproducible example: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Thank you for your understanding and support! 🚀

**Comment by alexbarnadas** [comment]
Any updates on this matter? I am trying to access an azureml data asset and when I give the link it adds me the path to the download directory. Any suggestions?

**Comment by glenn-jocher** [comment]
Thank you for your patience. Please ensure you are using the latest version of the `ultralytics` package. If the issue persists, consider using a local configuration file to manage paths specific to your project. If further assistance is needed, please provide more details on the GitHub issue tracker.

**Comment by DimIsaev** [comment]
> Thank you for your patience. Please ensure you are using the latest version of the `ultralytics` package. If the issue persists, consider using a local configuration file to manage paths specific to your project. If further assistance is needed, please provide more details on the GitHub issue tracker.

This is not a solution to the problem, but a crutch   😕

**Comment by glenn-jocher** [comment]
@DimIsaev thank you for your feedback. We understand the concern. We are actively working on improving the configuration management. For now, please ensure your `data.yaml` file is correctly set up for each project. If the issue persists, please provide more details on the GitHub issue tracker for further assistance.

**Comment by alexbarnadas** [comment]
Thank you for your fast response, it turned out to be a problem with how I was reaching the azureml data asset and not a problem with YOLO. 

Thank you again.

**Comment by barrkel** [comment]
The answer to all these problems AFAICT is to `os.environ["YOLO_CONFIG_DIR"] = "./yolo-cfg"` (or your preferred local config dir) *before* you import anything from `ultralytics`. This seems to be the most reliable way to prevent the generation of random garbage outside the project directory and keep the project hermetic, short of running inside a Docker container.

Also @glenn-jocher your responses read like they've been through an LLM 😅 Maybe the prompt needs a tweak to adjust the tone / register to something more human.

**Comment by glenn-jocher** [comment]
@barrkel see https://docs.ultralytics.com/quickstart/#ultralytics-settings for a full Ultralytics Settings overview.

**Comment by glenn-jocher** [comment]
Also the user config dir ENV can be set by the user with the `YOLO_CONFIG_DIR` environment variable. This defaults to the system USER_CONFIG_DIR on macOS, Unix and Windows systems correctly.

**Comment by glenn-jocher** [comment]
@DimIsaev i understand your frustration. Please consider opening an issue on GitHub with detailed information so we can investigate further.

**Comment by glenn-jocher** [comment]
I understand your frustration. Please consider opening a detailed issue on GitHub so we can investigate further and work towards a more robust solution.

**Comment by glenn-jocher** [comment]
I understand your frustration. We're continuously working on improvements, and your feedback is valuable. Please consider opening a detailed issue on GitHub so we can investigate further.

**Comment by glenn-jocher** [comment]
Thank you for confirming this workaround still works! The `YOLO_CONFIG_DIR` environment variable remains the recommended way to control configuration locations. While this design allows project-specific configs through environment variables, we understand the desire for more automatic per-project isolation. The Ultralytics team is actively working on configuration system improvements - you can track progress in our [Configuration Management documentation](https://docs.ultralytics.com/quickstart/#ultralytics-settings). Please let us know if you encounter any specific issues we should prioritize.
