### ISSUE TITLE
MLFlow invalid parameter value

### ISSUE THREAD

**Issue by sebos123** [ultralytics/ultralytics#1810]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hi,

I am trying to run Yolov8 training with mlflow integration.
Unfortunately, I do get an error, when I try to set the project path to something containing a forward slash:
`RestException: INVALID_PARAMETER_VALUE: Invalid name '/test/yolov8_train'. A registered model name must be a non-empty UTF-8 string and cannot contain forward slashes(/), periods(.), or colons(:).`
It happens in ultralytics/yolo/utils/callbacks/mlflow.py:63:
`run.register_model(model_uri, experiment_name)`

### Environment

- Ultralytics YOLOv8.0.61 🚀 Python-3.9.5 torch-1.13.1+cu117
- MLFlow Version: 2.1.1

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi @k0m0d0,

Thank you for reaching out. I suggest changing the project path to something that does not contain a forward slash to avoid the error you encountered. YOLOv8 requires a valid model name without forward slashes, periods, or colons. If you encounter further issues, we recommend visiting the YOLOv8 [Docs](https://docs.ultralytics.com/)  for more information or opening a new issue.

Regarding your interest in submitting a PR, we appreciate your willingness to contribute to the project. Please make sure to review our [Contributing Guidelines](https://github.com/ultralytics/ultralytics/blob/main/.github/CONTRIBUTING.md) before submitting a PR to ensure the best collaborative experience.

Let us know if you have any other questions.

Best regards!
