### ISSUE TITLE
COCO dataset for Pose estimation?

### ISSUE THREAD

**Issue by LaCandela** [ultralytics/ultralytics#1811]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

What kind of dataset can I use for evaluation to reproduce the results reported on the pose branch? Is there a separate dataset like there is for segmentation?

I tried:

from ultralytics import YOLO
model = YOLO("/ultralytics/log/weights/yolov8n-pose.pt") 
results = model.val(data='ultralytics/datasets/coco.yaml')

Can I use the same data that is used for the detection task? If I try that then the code tries do download the dataset from
https://github.com/ultralytics/yolov5/releases/download/v1.0/coco2017labels-segments.zip
However, if I download it and set the path in coco-pose.yaml the dataset seems to be empty after cashing.
I also tried downloading 
https://github.com/ultralytics/yolov5/releases/download/v1.0/coco2017labels-pose.zip
but it fails.
Can you help me with this?
Thanks!

**Comment by glenn-jocher** [comment]
Hello @szymonb, thank you for reaching out and asking about how to reproduce pose results with YOLOv8. The same datasets used for detection tasks on YOLOv8 should suffice for reproducing pose results. Specifically, the COCO dataset should be appropriate for this task.
It's interesting that you're having issues downloading the dataset from our GitHub releases. Are you experiencing a download error? Please confirm that you're unzipping the dataset after you've downloaded it. Your current issue may be due to the fact that the dataset is not being fully extracted from the zip file. 
If you continue to have issues, let us know and we'll be happy to help you further.

**Comment by glenn-jocher** [comment]
@LaCandela after reviewing your question closer, you just have to wait for pose branch to merge into main later this week. The dataset used is coco-pose.yaml in the pose branch.

**Comment by LaCandela** [comment]
@glenn-jocher so is there something wrong with the pose branch right now?
For some reason I still cannot download
https://github.com/ultralytics/yolov5/releases/download/v1.0/coco2017labels-pose.zip
I only get a github error message that says "Not Found" and it won't start the download so I cannot get any zip file at all. Will it be available?

**Comment by glenn-jocher** [comment]
@szymonb, you're welcome! The pose branch is still active and we're working to make it part of the main branch in the upcoming days. As for the download issue, it seems like there could be a temporary issue on GitHub's end. I suggest that you try again in a few hours or tomorrow. Also, ensure that you have permission to access the file as there are certain limitations that apply. If the issue persists, let us know and we'll assist you with alternative download approaches.

**Comment by LaCandela** [comment]
@glenn-jocher uhm, I am not sure if it is really a github issue since I have no problem accessing
https://github.com/ultralytics/yolov5/releases/download/v1.0/coco2017labels-segments.zip
I can wait till tomorrow, although I don't believe it will help too much...
If I get it right, I will still need
https://github.com/ultralytics/yolov5/releases/download/v1.0/coco2017labels-pose.zip
anyway even after you merged pose into the main branch.

**Comment by glenn-jocher** [comment]
@szymonb, thanks for clarifying that you were able to download the segmentation labels file without a problem. Regarding the pose dataset, it will likely still be needed even after the pose branch is merged into the main branch as it contains specific training annotations tailored for the pose task. Once you download the pose dataset, you should be able to follow the instructions in `coco-pose.yaml` to utilize it in your training, validation, and testing tasks. Let me know if you have any further questions or run into any other issues.

**Comment by triple-Mu** [comment]
URL : https://github.com/ultralytics/yolov5/releases/download/v1.0/coco2017labels-pose.zip
Not available!

**Comment by glenn-jocher** [comment]
@szymonb, I'm sorry to hear that the pose dataset is currently not available to download from the provided URL. There could be various reasons why this is the case, ranging from a temporary issue with the server that hosts the file to a change in the location of the file. One suggestion would be to reach out to the author/maintainer of the repo responsible for the pose branch to inquire about the availability of the dataset or to ask them for an alternative download source. You could also try looking for the dataset elsewhere online or consider creating your own annotated dataset for the pose task if you have the means to do so.

**Comment by glenn-jocher** [comment]
@triple-Mu @LaCandela Pose release is out! You can start training on COCO Pose with this command. Dataset is automatically downloaded. See https://docs.ultralytics.com/tasks/pose for details.

```
yolo train data=coco-pose.yaml
```

**Comment by glenn-jocher** [comment]
Here are some example results:

![20180908_WeWork_Hibiya_Park_Front_-_Common_Areas_-_Wide-3](https://user-images.githubusercontent.com/26833433/230657924-7c47bb75-932f-473d-b658-5a872c806d15.jpeg)
![gettyimages-881484382-612x612](https://user-images.githubusercontent.com/26833433/230657927-585a81f7-ac8b-4d87-a9e4-29fb07648c1a.jpeg)
![image-asset](https://user-images.githubusercontent.com/26833433/230657928-b3abaaeb-aba2-4376-aac9-b0b0c618c23a.jpeg)
![IMG_0698](https://user-images.githubusercontent.com/26833433/230657930-9aa3bfe3-a028-4a7e-b290-c10469ba9065.jpg)
![img](https://user-images.githubusercontent.com/26833433/230657933-1323f128-4e7c-4e90-8650-f28a13e8b1a8.jpg)
![zidane](https://user-images.githubusercontent.com/26833433/230657934-98ce6ddc-350b-4f4c-8eba-3aea6bc4c2ba.jpg)

**Comment by YinYanfang** [comment]
> 
but in  coco-pose.yaml, the download path of  coco2017labels-pose.zip  is 
 still "https://github.com/ultralytics/yolov5/releases/download/v1.0/coco2017labels-pose.zip" , so it doesn't work.

**Comment by glenn-jocher** [comment]
@YinYanfang, the issue with the `coco2017labels-pose.zip` file download may be because the URL has been updated to reflect the new release, but the YAML file has not. To resolve this issue, it is best to contact the author/maintainer of the repository for further assistance. It is possible that the new download URL can be found elsewhere in the documentation or accompanying release notes. Additionally, there may be alternative sources or mirror sites where the file may be downloaded from.

**Comment by YinYanfang** [comment]
@glenn-jocher  thanks.

**Comment by glenn-jocher** [comment]
@YinYanfang, you're welcome. In order to resolve the issue with the `coco2017labels-pose.zip` file download, it would be best to contact the author/maintainer of the repository for further guidance. There may be changes to the download URL that are not reflected in the YAML file, but which have been updated in the accompanying release notes or documentation. Additionally, the author/maintainer may be aware of alternative sources or mirror sites from which the file may be obtained. It is important to ensure that all instructions are followed and that the correct data is obtained for successful training, validation, and testing of the pose model.

**Comment by glenn-jocher** [comment]
@YinYanfang I just checked the download URL and you are right, it was broken as it was using our old naming of coco-kpt. I've updated the labels to the correct coco-pose URL now and tested that everything works:

<img width="979" alt="Screenshot 2023-04-13 at 12 47 25" src="https://user-images.githubusercontent.com/26833433/231736365-04f565de-4064-4348-b7f8-0e4e93b3138f.png">

Please try your training again and let us know if this resolves your issue!

```
yolo train model=yolov8n-pose.pt data=coco-pose.yaml
```

**Comment by YinYanfang** [comment]
@glenn-jocher  It works now. Thank you very much.

**Comment by LeBron-Jian** [comment]
@glenn-jocher  hi ，sorry to bother you , I alse plan to reproduce the performance of yolo-pose on the coco dataset.  I downloaded the coco2017labels-pose.zip annotation file according to https://docs.ultralytics.com/datasets/pose/coco

Beacuse I already have the coco dataset. I noticed that the original COCO dataset train_images has 118287 images and val_images has 5000 images. Then in the annotation of coco2017labels-pose.zip, train_labels has 56599 annotation files and val_labels has 2346 annotation files.
![coco_show2](https://github.com/user-attachments/assets/9661057f-dd3e-409d-9659-db87c126b27b)


I saw that the document said that the file with some data annotations are the annotations of pose estimation, as follows:
![coco_show](https://github.com/user-attachments/assets/68c5d466-01f3-4791-b1a7-20b25398847e)

but I am not sure whether the zip file I parsed is complete. If possible, whether the content of coco2017labels-pose.zip is written in more detail in the Dataset Structure of the https://docs.ultralytics.com/datasets/pose/coco/ document. This way, subsequent reproducers don't have to worry about whether the zip file is downloaded completely.

**Comment by glenn-jocher** [comment]
Hi, no problem at all. The `coco2017labels-pose.zip` file should contain the necessary annotations for pose estimation. If you've followed the instructions and extracted the files, you should be set. For detailed dataset structure, please refer to the documentation link you mentioned. If you encounter any issues, feel free to ask here.
