### ISSUE TITLE
Multi-Channel and Metadata Integration

### ISSUE THREAD

**Issue by Carlson-J** [ultralytics/ultralytics#1813]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I think we should add the ability to add metadata or additional feature layers into the framework. This could be done by appending channels to the input image or adding channels at the start of the different detection heads. This would allow for the model to use that information either in the backbone or the head.

I've already implemented a way of appending additional channels to an image in [Carlson-J:multi_channel](https://github.com/Carlson-J/ultralytics/tree/multi_channel). In this implementation, the data augmentation only happens on the first 3 channels, excluding the resizing and mosaic, which still keep the inputs associated with their respective pixels. 

I'm not aware of examples of people adding in additional feature maps at different layers in a YOLO architecture, but for my application, it would be extremely useful to add additional information to help classify different objects.

### Use case

The use case would be adding the ability to add additional information from the images, e.g., location. When similar objects are easily differentiated based on these features, e.g., location and species of animal, these additional features can allow for improved classification and detection.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Carlson-J thank you for your suggestion! Your idea sounds interesting and I can definitely see its potential for use cases like yours. Adding metadata or additional feature layers could certainly enhance the detection and classification capabilities of the model. While adding channels to the input image is something that has been implemented in a branch of the YOLOv8 repository, adding feature maps at different layers is a more complex idea that would require careful consideration and experimentation to determine the best approach. I encourage you to submit a Pull Request with your implementation for appending channels to the input image as a starting point. Thank you for your willingness to contribute to the project!

**Comment by Y-T-G** [comment]
Duplicate of https://github.com/ultralytics/ultralytics/issues/6929
