### ISSUE TITLE
When running segment/val.py file, an incorrect predictions.json file is generated

### ISSUE THREAD

**Issue by timecollision** [ultralytics/ultralytics#18136]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

After I ran the /yolo/segment/val.py file, the "counts" in the output preditions.json file are all garbled,how can I solve this? 
I have only one "ship" category in my coco dataset and the category_id is 1,and I found that the "category_id": 1 in the original instances_val2017.json file, but predictions.json file changed to "category_id": 0

[{"image_id": 499, "category_id": 0, "bbox": [202.953, 116.714, 84.71, 50.938], "score": 0.72763, "segmentation": {"size": [192, 500], "counts": "c\\V1b0^50O2O00000O1O1O10000O1000000N11000OO200O10O1000000N101000N20O011MXOlJg0T5300000000O10O10N02000O0100O10OO2OO20000O01N2000O0100000M300000O01N20O100O10000O1N200O1O1N200O1L4N202M[^W1"}}, {"image_id": 499, "category_id": 0, "bbox": [191.89, 125.712, 77.472, 39.747], "score": 0.00518, "segmentation": {"size": [192, 500], "counts": "jTT14l50O4K20000O101O00001N3L20000O1000000O1N2000000O10000N20N20O10O100000O10O10O1O01O10O01000O1N2O100000O1000O01OO11000O01O1O10O01000O01N2O11OO100000000O100000SP[1"}}, 
[predictions.json](https://github.com/user-attachments/files/18064248/predictions.json)
[instances_val2017.json](https://github.com/user-attachments/files/18064251/instances_val2017.json)

**Comment by UltralyticsAssistant** [comment]
👋 Hello @timecollision, thank you for bringing this to our attention 🚀!

We recommend exploring the [Ultralytics Docs](https://docs.ultralytics.com) for a wealth of resources and examples that may help address your issue. For example, you can find detailed explanations of [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage or take a look at our [segmentation documentation](https://docs.ultralytics.com/tasks/segment/) for more task-specific guidance.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example (MRE)](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us debug it. This would include:
1. A clear description of the issue you've observed.
2. Steps to reproduce the issue, including code snippets.
3. Your environment details (e.g., Ultralytics version, Python version, operating system, and any changes made to the code).

Additionally, ensure that your setup is running on the latest version of the `ultralytics` package, as the issue may have already been resolved. You can upgrade with the following command:

```bash
pip install -U ultralytics
```

### Insights for Your Specific Case
In your description, it seems there might be a mismatch or encoding issue with the `category_id` in your output `predictions.json` file. Please provide:
- A sample from your dataset (e.g., specific images or annotations causing this issue).
- Any modifications you've made to the `val.py` file or other configuration settings.
- Logs or prints from your validation/testing script for further investigation.

If relevant, you can also link us to your dataset or specific segments of your `predictions.json` and `instances_val2017.json` files to help us understand the discrepancies 🔍.

### Community Resources
Join the vibrant Ultralytics community 🎉:
- Chat with the team and peers in real-time on [Discord](https://discord.com/invite/ultralytics) 🎧.
- Engage in extended discussions on our [Discourse forums](https://community.ultralytics.com).
- Visit our [Subreddit](https://reddit.com/r/Ultralytics) to connect with others working on similar projects.

### Verified Environments
For best results, we recommend running YOLO within one of these verified environments:
- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud**: Refer to our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/).
- **AWS AMI**: Use the [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/).
- **Docker Image**: See the full [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>.

---

An Ultralytics engineer will look into this and assist you shortly. Thank you for your patience and for using Ultralytics 🙌!

**Comment by Y-T-G** [comment]
Remove everything and just run `model.val(save_json=True)`

**Comment by timecollision** [comment]
> Remove everything and just run `model.val(save_json=True)`
I ran this code:

from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO(r'D:\JetBrains 2023\Yolov8seg\ultralytics-main\runs\train\SAPS_SCSA\exp\weights\best.pt')
    model.val(save_json=True)

but also got the incorrect predictions.json

[{"image_id": 499, "category_id": 0, "bbox": [202.978, 116.867, 84.689, 50.684], "score": 0.71775, "segmentation": {"size": [192, 500], "counts": "c\\V1b0^50O2O00000O1O1O10000O1000000N11000OO2O1000O1000000O0O2000N20O011OON3000000000O0100N0200O01000O1O1O00O20000ON300000O0100000M30000O010N20O100O10000O1N200O1O1N200O1L4N202M[^W1"}}, {"image_id": 499, "category_id": 0, "bbox": [193.067, 120.94, 79.545, 45.957], "score": 0.16951, "segmentation": {"size": [192, 500], "counts": "i`T161Ke590000O101O00001N3L200O2O00000O1O1O1000000O10000N11N20O10O1000O100000O01O10O1O001000O1N2O10000000O10O01OO11000O01O100O00OYOkJg0U5YOkJg0U510O20000O10O10000O10O10000O1000W^Z1"}}
[predictions.json](https://github.com/user-attachments/files/18066412/predictions.json)

**Comment by Y-T-G** [comment]
Can you provide the output after running this command in terminal: `yolo checks`?

**Comment by Y-T-G** [comment]
The `counts` is RLE encoded mask, so it looks like that.

https://github.com/ultralytics/ultralytics/blob/d170f1ab6ad740369e5508788ab267a6639fc851/ultralytics/models/yolo/segment/val.py#L270

**Comment by timecollision** [comment]
> Can you provide the output after running this command in terminal: `yolo checks`?
Ultralytics 8.3.27 🚀 Python-3.9.13 torch-2.5.1+cpu CPU (12th Gen Intel Core(TM) i9-12900HX)
Setup complete ✅ (24 CPUs, 15.7 GB RAM, 691.1/752.9 GB disk)

OS                  Windows-10-10.0.22631-SP0
Environment         Windows
Python              3.9.13
Install             pip
RAM                 15.74 GB
Disk                691.1/752.9 GB
CPU                 12th Gen Intel Core(TM) i9-12900HX
CPU count           24
GPU                 None
GPU count           None
CUDA                None

numpy               ✅ 2.0.2>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 11.0.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.5.1>=1.8.0
torchvision         ✅ 0.20.1>=0.9.0
tqdm                ✅ 4.66.6>=4.64.0
psutil              ✅ 6.1.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.10>=2.0.0
numpy               ✅ 2.0.2<2.0.0; sys_platform == "darwin"
torch               ✅ 2.5.1!=2.4.0,>=1.8.0; sys_platform == "win32"

**Comment by timecollision** [comment]
> The `counts` is RLE encoded mask, so it looks like that.
> 
> https://github.com/ultralytics/ultralytics/blob/d170f1ab6ad740369e5508788ab267a6639fc851/ultralytics/models/yolo/segment/val.py#L270

I also thought that the amount would make this happen, but after I tried to change the code to :
rle["counts"] = rle["counts"].decode("utf-8", errors="ignore"), the output didn't change

**Comment by glenn-jocher** [comment]
The issue with `counts` in the `predictions.json` is not related to decoding. The `counts` field uses RLE (Run Length Encoding), a standard COCO format for mask representation. Your output format is correct and adheres to COCO standards. If you're experiencing specific downstream issues, please ensure the consuming tool or script supports RLE encoding as defined by COCO.

**Comment by timecollision** [comment]
> The issue with in the is not related to decoding. The field uses RLE (Run Length Encoding), a standard COCO format for mask representation. Your output format is correct and adheres to COCO standards. If you're experiencing specific downstream issues, please ensure the consuming tool or script supports RLE encoding as defined by COCO.`counts``predictions.json``counts`

Thanks for your answer, because I want to use predictions.json file to output mAPs, mAPm, mAPl evaluation indicators, originally I directly ran model.val() and found that the above three indicators were not output, I thought it was a problem with the JSON file generation error, and now I use code:

from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval


# accumulate predictions from all images
# load instances_val2017.json
coco_true = COCO(annotation_file="D:\JetBrains 2023\Yolov8seg/ultralytics-main\datasets\coco/annotations\instances_val2017.json")
# load predictions.json
coco_pre = coco_true.loadRes(r'D:\JetBrains 2023\Yolov8seg\ultralytics-main/runs\segment/val5\predictions.json')

coco_evaluator = COCOeval(cocoGt=coco_true, cocoDt=coco_pre, iouType="segm")
coco_evaluator.evaluate()
coco_evaluator.accumulate()
coco_evaluator.summarize()

This code can display the following information in the terminal:
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000

I found that the reason why the values are all 0 is that the "category_id" in the predictions.json is 0, but the "category_id" in the single-category coco dataset I made myself is 1.I changed 
cls = coco80[ann["category_id"] - 1] if cls91to80 else ann["category_id"] - 1  # class
to
cls = coco80[ann["category_id"]] if cls91to80 else ann["category_id"]  # class
but it did not work.

**Comment by glenn-jocher** [comment]
The issue arises because your custom dataset uses `category_id` as 1, while `predictions.json` is defaulting to 0. This mismatch causes the COCO evaluation to fail. To resolve this, ensure your dataset configuration and model are aligned:

1. Verify your dataset's `category_id` in your `coco.yaml` file matches the correct label mapping (e.g., setting `names: {0: "ship"}` if your single class is "ship").
2. Use `cls = ann["category_id"]` directly to ensure `category_id` matches your dataset's ground truth.
3. Regenerate the `predictions.json` after making these adjustments.

If the problem persists, please double-check your dataset annotations and ensure consistent `category_id` usage across all files.

**Comment by Petros626** [comment]
@glenn-jocher will I also have problems with obb/val.py if the class indexes start like this in kitti_bev.yaml? What can I do if I want to keep exactly this order?

```yaml
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/kitti # dataset root dir
train: images/train/ # train images (relative to 'path') 18560 images (3712 training images extended with data augmentation)
val: images/val/ # val images (relative to 'path') 3769 images
test: # test images (optional)

# Classes
names:
  0: None? # Is the `category_id` necessary starting at 0?
  1: Car
  2: Ped
  3: Cyc
```

**Comment by glenn-jocher** [comment]
Yes, you may encounter issues since COCO-style evaluation expects `category_id` to start from `0`. To retain your current class order (1-Car, 2-Ped, 3-Cyc), ensure you adjust your dataset's `category_id` mapping during both annotation creation and model inference outputs to align with COCO conventions. Specifically, map your dataset's `category_id` (1, 2, 3) to COCO's 0-based index (0, 1, 2) during pre-processing and reverse it post-processing if needed.

**Comment by Petros626** [comment]
Would setting the first `category_id` to None help? Or what change in code `obb/val.py` would be necessary? https://github.com/ultralytics/ultralytics/blob/d170f1ab6ad740369e5508788ab267a6639fc851/ultralytics/models/yolo/obb/val.py#L114

**Comment by Y-T-G** [comment]
@Petros626 `save_json` is used to save COCO predictions.json which can be used in COCOAPI. The index starts from 1 for COCO format. In YOLO labels format, the index starts from 0. So when you use `save_json=True` it will automatically map, the 0th class in yaml to 1 in JSON and so on. This is with latest version.

**Comment by Petros626** [comment]
"COCO's 0-based index" as Glenn said? Is my code solution incorrect?

**Comment by Y-T-G** [comment]
COCO is 1-based. YOLO is 0-based. I'm not sure why you want to convert OBB to COCO JSON. AFAIK, COCOAPI doesn't support OBB evaluation.

**Comment by Petros626** [comment]
I wanted to know whether it is problematic to have a class index from 1 with the parameter `save_json=True` as already described here: https://github.com/ultralytics/ultralytics/issues/18136#issuecomment-2561941077. Because internally it works with COCO format, the OBBValidator inherits from DetectionValidator and this uses COCO indexing for the classes https://github.com/ultralytics/ultralytics/blob/c9a48b281e590f8bd0869ffc38a0bfdbf634ee3b/ultralytics/models/yolo/detect/val.py#L77.

**Comment by Petros626** [comment]
> @Petros626 `save_json` is used to save COCO predictions.json which can be used in COCOAPI. The index starts from 1 for COCO format. In YOLO labels format, the index starts from 0. So when you use `save_json=True` it will automatically map, the 0th class in yaml to 1 in JSON and so on. This is with latest version.

Then my problem was not understood correctly. I would have liked to use my fixed order (1-Car, 2-Pedestrian, 3-Cyclist) with the YOLO format, but apparently this is not possible without changing the code, because I would like to start at 1 instead of 0. Hence my question what to do. By the way, the description of the `save_json` is not the best either "If True, saves the results to a JSON file for further analysis or integration with other tools". Nowhere does it say anything about the `COCOAPI`.

**Comment by Petros626** [comment]
> @Petros626 `save_json` is used to save COCO predictions.json which can be used in COCOAPI. The index starts from 1 for COCO format. In YOLO labels format, the index starts from 0. So when you use `save_json=True` it will automatically map, the 0th class in yaml to 1 in JSON and so on. This is with latest version.

Then my problem was not understood correctly. I would have liked to use my fixed order (1-Car, 2-Pedestrian, 3-Cyclist) with the YOLO format, but apparently this is not possible without changing the code, because I would like to start at 1 instead of 0. Hence my question what to do. 

By the way, the description of the `save_json` is not the best either `COCOAPI`.

**Comment by Y-T-G** [comment]
> Then my problem was not understood correctly. I would have liked to use my fixed order (1-Car, 2-Pedestrian, 3-Cyclist) with the YOLO format

If your classes start with 0 in YOLO format and data yaml, then they would start with 1 in COCO formatted JSON.

> but apparently this is not possible without changing the code, because I would like to start at 1 instead of 0. Hence my question what to do.

Why? Can you actually mention what exactly is it that you're trying to achieve by changing the starting index to avoid the XY problem? What will you be doing with the JSON exactly and why is it required for it to break the COCO convention and start with index 0?

**Comment by Petros626** [comment]
can I simply assign None to the first index for names or is this then included in the .json file??
```yaml
names:
  0: None
  1: Car
  2: Ped
  3: Cyc
  ```
  Originally I just wanted a consistent category_id without mapping later. Since I read that it is necessary to save the correct .json file https://github.com/ultralytics/ultralytics/issues/18136#issuecomment-2536425338

**Comment by glenn-jocher** [comment]
If you assign `0: none` in your dataset YAML, it will appear in the JSON as `category_id: 1`, since COCO's format requires a 1-based indexing. If you want to exclude it entirely, remove `0: none` from your YAML.
