### ISSUE TITLE
how to get the result str content from Result？

### ISSUE THREAD

**Issue by wynshiter** [ultralytics/ultralytics#1816]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

e.g : in yolov5 and v8 we  have  result str 
> 0: 480x640 1 person, 70.4ms

means camera id:0 ，Resolution, detection result statistics, runtime

seems ultralytics.yolo.engine.results.Results object  attributes dont have this result str

can we add this or we already api？

**Comment by glenn-jocher** [comment]
@wynshiter hello! The `Results` object in Ultralytics YOLOv8 does not currently contain the result string you mentioned, but it is possible to create a custom string by accessing the relevant attributes and formatting them appropriately. We suggest taking a look at the source code in the `ultralytics.yolo.engine.torch_utils` module for examples of how to do this. Additionally, please note that YOLOv5 is not supported by Ultralytics YOLOv8, so we cannot provide support for it. If you have any further questions, feel free to ask!
