### ISSUE TITLE
Unable to see probs or masks in Result object

### ISSUE THREAD

**Issue by happydracula** [ultralytics/ultralytics#1817]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

`from ultralytics import YOLO`
`model = YOLO('yolov8x.pt') `
`results = model.predict("https://ultralytics.com/images/bus.jpg",save_conf=True)`
On running this code I am able to get the bounding boxes, but not the probs or the masks. The Result object contains 'None' for those fields.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@deepakkumria, it looks like you're able to get bounding boxes, but not probabilities or masks from your `YOLOv8` model when using `predict()` method. Please make sure the `save_conf` parameter is set to `True` for confidence scores and that the `save_mask` parameter is set to `True` for segmentation masks. You can also try checking the logs to make sure that you are seeing detections with matching labels. Additionally, ensure that your model is trained with confidence scores and masks. If you're still encountering issues, please do not hesitate to provide more information or check out the YOLOv8 docs for more information.

**Comment by solwarsop** [comment]
@glenn-jocher I have the same issue, even with save_conf=True set. I can access the confidences through `results[0].boxes.data`, but `results[0].probs` is `None`.

Using macOS 13.2.1 with Python 3.10.0 and Ultralytics 8.0.81.

**Comment by glenn-jocher** [comment]
@solwarsop, thank you for your feedback regarding the access to probabilities using the `predict()` method in YOLOv8. While it is possible to obtain bounding box data from the `results[0].boxes.data` property, please note that `results[0].probs` will not work for YOLOv8. Instead, use `results[0].pred[:, 4]` to obtain class probabilities. Please let us know if this responds to your problem.

**Comment by Laughing-q** [comment]
@solwarsop hey, `results[0].probs` is for classify task, if you want to access the cls of detection task, please use `results[0].boxes.cls`. :)
more examples please refer to our docs. [https://docs.ultralytics.com/usage/python/#predict](https://docs.ultralytics.com/usage/python/#predict)

**Comment by solwarsop** [comment]
> @solwarsop, thank you for your feedback regarding the access to probabilities using the `predict()` method in YOLOv8. While it is possible to obtain bounding box data from the `results[0].boxes.data` property, please note that `results[0].probs` will not work for YOLOv8. Instead, use `results[0].pred[:, 4]` to obtain class probabilities. Please let us know if this responds to your problem.

Thank you, `but results[0].pred` actually raises an attribute error. I've ended up implementing a solution based on @Laughing-q 's using the bounding box data to generate a results dictionary.

` {cls: conf for cls, conf in zip(results[0].boxes.cls.tolist(), results[0].boxes.conf.tolist())}`

**Comment by solwarsop** [comment]
Is this the intended behaviour? If so, the documentation should be updated. A very simple example based upon the first part of https://docs.ultralytics.com/usage/python/#val just outputs `None, None`.

`from ultralytics import YOLO

model = YOLO('yolov8n.pt')

inputs = ['img1.jpg', 'img2.jpg']  # list of image paths
results = model(inputs)  # list of Results objects

for result in results:
    boxes = result.boxes  # Boxes object for bbox outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    probs = result.probs  # Class probabilities for classification outputs
    
    print(probs)`

**Comment by rexblack** [comment]
I've been wondering as well why results are lacking masks and eventually I came across [this](https://docs.ultralytics.com/tasks/segment/#predict).
Looks like there's another model which is specialized on segmentation and does indeed actually return masks.

**Comment by glenn-jocher** [comment]
@rexblack, thank you for raising this issue. We apologize for the confusion and appreciate the feedback. `YOLOv8` does indeed have a dedicated segmentation model, which is intended for tasks such as [instance and semantic segmentation](https://docs.ultralytics.com/tasks/segment/). This is a separate model from the object detection model used in the code example in our current documentation. 

To clarify, with our YOLOv8 object detection models, bounding box and class probability information is provided through `results[0].boxes` and `results[0].pred[:, 4]`, respectively. Our segmentation models provide instance and semantic segmentation masks through `results[0].pred` and `results[0].labels`. 

Thank you for bringing this to our attention, and we apologize for any inconvenience this may have caused. Please don't hesitate to reach out if you have any further questions or feedback!

**Comment by rockdrigoma** [comment]
Same issue and above recommendation won't work.

I am using right model for detection:
`model = YOLO("yolov8x.pt")`

But when trying:
```
results = model.predict(source=image, conf=0.05, save_conf=True)
print(results[0].probs)
```
I get _None_ as a result.

When trying the _results[0].pred[:, 4]_ it won't work either:

`AttributeError: 'Results' object has no attribute 'pred'. See valid attributes below.`

When checking, runs directory is created and image results of detection as well, so prediction is working.
So I tried:

`res_json = json.loads(results[0].tojson())`

And this is giving me what I was looking for:

```
[{
	'name': 'person',
	'class': 0,
	'confidence': 0.8508743643760681,
	'box': {
		'x1': 55.31374740600586,
		'y1': 115.3524169921875,
		'x2': 246.815185546875,
		'y2': 298.05712890625
	}
}, {
	'name': 'car',
	'class': 2,
	'confidence': 0.37475401163101196,
	'box': {
		'x1': 91.22966003417969,
		'y1': 93.53160095214844,
		'x2': 445.1508483886719,
		'y2': 456.1500549316406
	}
}]
```

**Comment by glenn-jocher** [comment]
@rockdrigoma thank you for reaching out regarding the `probs` attribute and `results[0].pred[:, 4]` not working as expected in YOLOv8. While the `probs` attribute is not working in YOLOv8, your approach of using `json.loads(results[0].tojson())` should work fine. To address the `results[0].pred[:, 4]` issue, `pred` was a property used in some previous versions of YOLOv5, and is not implemented in YOLOv8. Instead, please use `results[0].boxes.conf`, which returns the confidence scores of each detection. 

We apologize for any confusion this may have caused and hope this helps you to continue working with YOLOv8 without any issues. Please let us know if we can provide any further assistance!

**Comment by hamzagorgulu** [comment]
I wonder how to see the prediction probabilities of every class in instance segmentation. I understand that it only gives the argmaxed result at the end. But I need n number of masks that corresponds the probabilities for every classes. So this is the step before the yolo argmaxes it.

**Comment by glenn-jocher** [comment]
@hamzagorgulu the current implementation of YOLOv8 in instance segmentation mode only provides masks for the highest-probability class for each detected object. In other words, the model applies an argmax operation on the class probabilities to determine the class of an object, and this operation cannot be reversed or bypassed to retrieve the individual class probabilities directly.

I understand you're interested in accessing probabilities for each class prior to the argmax operation. However, currently, this kind of functionality isn't supported due to a design decision aimed at computational and memory efficiency.

Modifying the model to provide each class's mask would significantly increase the complexity of the model's output and the necessary computation, negatively affecting performance and usability. 

 If such feature is essential to your project, you might consider modifying the source code or training a dedicated model per class according to your requirements. Do note that these workarounds would still require considerable computational resources and expertise in neural network programming.

**Comment by hamzagorgulu** [comment]
@glenn-jocher thank you for the great answer. I wonder if this is possible in the previous yolo versions. If not, I guide where would I need to change the source code would be also helpful. I tried the same thing in detectron2 myself but I was lost in the source code.

**Comment by glenn-jocher** [comment]
@hamzagorgulu, thank you for your response. Making the change you proposed in earlier YOLO versions or in YOLOv8 would still present a significant challenge. This is due to the high-level nature of the core design and the way the output format is tightly integrated into the models.

These models, including YOLOv8, are designed to carry out high-performance object detection and segmentation with a highly optimized format for output results. They make a prediction for a discrete class rather than a distribution over all classes primarily to conserve memory and computation resources.

Altering this design to include class probabilities for each object in the instance segmentation would involve significant changes in both the model architecture and post-processing steps.

If you're still keen on making these modifications, I would recommend you to start by reviewing the prediction and loss computation methods in the model implementation. But be prepared that this process could likely involve extensive adjustments and a good understanding of deep learning development. I wish you all the best in your endeavor.

**Comment by Promootheus** [comment]
replacing results[0].pred[:, 4] with results[0].boxes.conf results in

Speed: 6.1ms preprocess, 85.3ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 448)
Traceback (most recent call last):
  File "test.py", line 53, in <module>
    detect_and_crop(model, SOURCE_FOLDER, CONF_THRESHOLD, ASPECT_RATIO)
  File "test.py", line 35, in detect_and_crop
    for label, x, y, w, h in zip(results[0].boxes.conf[:, -1], results[0].boxes.conf[:, 0], results[0].boxes.conf[:, 1], results[0].boxes.conf[:, 2], results[0].boxes.conf[:, 3]):
IndexError: too many indices for tensor of dimension 1


```
def detect_and_crop(model, source_folder, conf_threshold=0.25, aspect_ratio="1:1"):
    for img_name in os.listdir(source_folder):
        img_path = os.path.join(source_folder, img_name)
        results = model.predict(img_path)

        # Assuming results are in the same format as YOLOv5's results
        for label, x, y, w, h in zip(results[0].boxes.conf[:, -1], results[0].boxes.conf[:, 0], results[0].boxes.conf[:, 1], results[0].boxes.conf[:, 2], results[0].boxes.conf[:, 3]):
            if label == 0 and results[0].boxes.conf[:, 4] >= conf_threshold:  # Assuming label 0 is 'person'
                img = cv2.imread(img_path)
                img_height, img_width = img.shape[:2]

                new_x, new_y, new_w, new_h = adjust_bbox(x, y, w, h, aspect_ratio, img_width, img_height)
                cropped_img = img[new_y:new_y+new_h, new_x:new_x+new_w]

                output_path = os.path.join(source_folder, f"cropped_{img_name}")
                cv2.imwrite(output_path, cropped_img)

if __name__ == "__main__":
    MODEL_PATH = 'yolov8n.pt'
    SOURCE_FOLDER = '/home/mypath/'
    CONF_THRESHOLD = 0.25
    ASPECT_RATIO = "1:1"  # or "1:1.5"

    model = YOLO(MODEL_PATH)
    detect_and_crop(model, SOURCE_FOLDER, CONF_THRESHOLD, ASPECT_RATIO)
```
