### ISSUE TITLE
YOLOV8 model deployment(TensorRT + CUDA  C)

### ISSUE THREAD

**Issue by FeiYull** [ultralytics/ultralytics#182]
### Description

yolov8  andyolov5 are very powerful  object detection algorithm in my  heart.     Here I give the model deployment  of yolov5 and yolov8. The method is: cuda c and tensorrt, model pre-processing, post-processing, infer 
 support cuda acceleration.  **TensorRT-Alpha:**          https://github.com/FeiYull/tensorrt-alpha     

the following is yolov8n running speed：

![8473e71b98e84cd45ff4d64e8bafb439](https://user-images.githubusercontent.com/113091091/211528956-24173c05-13b8-4ad9-8287-314b4fb746ca.jpg)

**Comment by triple-Mu** [comment]
I also do the same things in https://github.com/triple-Mu/YOLOv8-TensorRT.
It seems great to accelerate model inference with gpu.

**Comment by Linaom1214** [comment]
hhhhhh @triple-Mu  
I also do some works on this projects  https://github.com/Linaom1214/TensorRT-For-YOLO-Series that use TensorRT to accelerate YOLO. This repository now supports multiple versions of YOLO, including YOLOv8, YOLOv7, YOLOv6, YOLOX, YOLOV5, and YOLOv3. The most important feature is that it supports post-processing acceleration using the TensorRT NMS plugin, making the process much more streamlined.

**Comment by AyushExel** [comment]
@Linaom1214 thanks for your kind words. This seems like an interesting idea. It'd be great it you can start a PR. Thanks!

**Comment by Linaom1214** [comment]
> 

thanks， I will do it.
