### ISSUE TITLE
external data augmentatio impact 

### ISSUE THREAD

**Issue by aiakash** [ultralytics/ultralytics#1825]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i have done external data augmentation,this are the results , so adding this type of data in outr train data is helpful? should i add different version or data augmented images to dataset? 

if im adding 3 different effect data to my dataset will model not baised? my approch is correct or should i need to add only 1 image insted of 3 different augmented images?

<img width="731" alt="image" src="https://user-images.githubusercontent.com/126226282/229981799-ecd479a3-70c5-454d-ad2d-aec440c7d235.png">

<img width="757" alt="image" src="https://user-images.githubusercontent.com/126226282/229982446-807c56e6-94ac-4934-915f-e98511ec9227.png">

**Comment by glenn-jocher** [comment]
Great question, @HackerBuddy12! Data augmentation is a powerful tool that can improve your training data and help your model generalize better by increasing the variety of examples it sees. Adding different versions of the same image with different augmentations is a good strategy to diversify your dataset. However, you need to be careful not to overfit your model to the augmented images, so you should include both the original and augmented images together in your training set. This will prevent your model from learning the specific details of each augmented image and instead learn the underlying patterns that generalize well to new examples. Keep up the good work!
