### ISSUE TITLE
FileNotFoundError: 'yolov8n-p6.yaml' does not exist

### ISSUE THREAD

**Issue by zhangshoulong** [ultralytics/ultralytics#1830]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

FileNotFoundError: 'yolov8n-p6.yaml' does not exist

**Comment by glenn-jocher** [comment]
Hi @baobaozhuzhi, it looks like you're receiving a FileNotFoundError when running YOLOv8. This error indicates that the specified file, 'yolov8n-p6.yaml', could not be found.

If you're using a custom .yaml file for YOLOv8, please ensure that the file exists in the specified directory and has the correct name. Double-checking the file path and name will often resolve FileNotFoundError issues.

If you're still having trouble, feel free to provide more information about your setup and steps leading up to the error, and we'll try our best to help you troubleshoot the issue further.
