### ISSUE TITLE
Score is too small with onnx

### ISSUE THREAD

**Issue by Kohirus** [ultralytics/ultralytics#18313]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I trained a yolo-obb model. Everything worked fine when I used the following code to predict:

```python
model = YOLO("./obb/train3/weights/best.pt")
result = model(
    source="./data_obb/images/test/test_0001.jpg",
    device=0,
    save=True,
    project="obb",
)
for r in result:
    print(r.obb)
```

This is the result, confidences are normal:

```
image 1/1 E:\Code\VS Code\KeyPoints\data_obb\images\test\test_0001.jpg: 224x320 58.8ms
Speed: 6.3ms preprocess, 58.8ms inference, 138.7ms postprocess per image at shape (1, 3, 224, 320)
Results saved to obb\predict4
ultralytics.engine.results.OBB object with attributes:

cls: tensor([1., 0.], device='cuda:0')
conf: tensor([0.9206, 0.8919], device='cuda:0')
data: tensor([[1.1136e+03, 5.4824e+02, 8.4011e+02, 6.9993e+01, 1.5628e+00, 9.2063e-01, 1.0000e+00],
        [1.1288e+03, 4.8233e+02, 7.9915e+02, 7.2716e+01, 3.1284e+00, 8.9193e-01, 0.0000e+00]], device='cuda:0')
id: None
is_track: False
orig_shape: (1024, 1536)
shape: torch.Size([2, 7])
xywhr: tensor([[1113.5511,  548.2414,  840.1144,   69.9928,    1.5628],
        [1128.8273,  482.3346,  799.1498,   72.7162,    3.1284]], device='cuda:0')
xyxy: tensor([[1075.2024,  127.9182, 1151.8999,  968.5646],
        [ 728.8072,  440.7049, 1528.8474,  523.9644]], device='cuda:0')
xyxyxyxy: tensor([[[1081.9094,  968.5646],
         [1151.8999,  968.0058],
         [1145.1929,  127.9182],
         [1075.2024,  128.4770]],

        [[ 728.8072,  451.2545],
         [ 729.7672,  523.9644],
         [1528.8474,  513.4148],
         [1527.8875,  440.7049]]], device='cuda:0')
xyxyxyxyn: tensor([[[0.7044, 0.9459],
         [0.7499, 0.9453],
         [0.7456, 0.1249],
         [0.7000, 0.1255]],

        [[0.4745, 0.4407],
         [0.4751, 0.5117],
         [0.9953, 0.5014],
         [0.9947, 0.4304]]], device='cuda:0')
```

Then I exported it as an onnx file using code like below:

```python
model = YOLO("./obb/train3/weights/best.pt")
model.export(format="onnx", imgsz=320)
```

I use the DNN module of OpeCV to load this onnx file for interfacing in the following code:

```c++
// Load image and ONNX model file
cv::Mat src = cv::imread("test.png");
cv::dnn::Net model = cv::dnn::readNet("best.onnx");
model->setPreferableBackend(cv::dnn::DNN_BACKEND_OPENCV);
model->setPreferableTarget(cv::dnn::DNN_TARGET_CPU);

// Set parameters
cv::dnn::Image2BlobParams params;
params.scalefactor = 1.0 / 255.0;
params.size        = cv::Size(320, 320);
params.mean        = cv::Scalar(0.0, 0.0, 0.0);
params.swapRB      = true;
params.ddepth      = CV_32F;
params.datalayout  = cv::dnn::DNN_LAYOUT_NCHW;
params.paddingmode = cv::dnn::ImagePaddingMode::DNN_PMODE_LETTERBOX;
cv::Mat input_blob = cv::dnn::blobFromImageWithParams(src, params);

// Forward interfacing
model->setInput(input_blob);
std::vector<cv::Mat> output_blobs;
model->forward(output_blobs, model->getUnconnectedOutLayersNames());

// Post processing
std::vector<cv::RotatedRect> boxes;
std::vector<int>             class_ids;
std::vector<float>           confidences;

for (auto preds : outputs) {
    preds = preds.reshape(1, preds.size[1]);
    cv::transpose(preds, preds);

    for (int i = 0; i < preds.rows; ++i) {
        cv::Mat   scores = preds.row(i).colRange(4, preds.cols - 1);
        double    score;
        cv::Point class_idx;
        cv::minMaxLoc(scores, nullptr, &score, nullptr, &class_idx);

        std::cout << score << std::endl;
        if (score < conf_threshold_)
            continue;

        float* box      = preds.ptr<float>(i);
        float  center_x = box[0], center_y = box[1];
        float  width = box[2], height = box[3];
        float  angle = box[preds.cols - 1];
        boxes.emplace_back(cv::RotatedRect(cv::Point2f(center_x, center_y), cv::Size2f(width, height), angle));
        class_ids.emplace_back(class_idx.x);
        confidences.emplace_back(static_cast<float>(score));
    }
}

// NMS ...
```

The confidences I got for each class is very small, almost all less than e-5:

![image](https://github.com/user-attachments/assets/22f32065-ab2b-445e-a58b-e6ce5a763f18)

In the meantime, I tried the following methods, but none of them worked:

- Add `half` param when export onnx file.
- Change ONNX version with `opset` param.
- Change *.pt file to export, such as `last.pt`.
- Change test image.
- Update version of ultralytics.

This is my environment:

- ultralytics: 8.3.51
- torch: 2.5.1+cu118
- Python: 3.0.11
- OpenCV: 4.8.0
- OS: Windows 11

Who can help me solve this problem, Thanks.

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Kohirus, thank you for raising this issue and for your detailed explanation! 🚀

We recommend visiting the [Ultralytics Docs](https://docs.ultralytics.com) for detailed guidance, including [YOLO export options](https://docs.ultralytics.com/modes/export/) and [ONNX usage examples](https://docs.ultralytics.com/tasks/detect/#export-to-onnx), which might provide additional insights.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example (MRE)](https://docs.ultralytics.com/help/minimum_reproducible_example/) that we can use to investigate the issue further. An MRE helps us replicate the scenario more effectively.

If this is related to ❓ Custom Training or ONNX exports, please describe with as much detail as possible (as you've already done 🙌) and ensure you're following our [Training Tips](https://docs.ultralytics.com/guides/model-training-tips/) for best practices.

To help address your issue:

## Debugging Steps

1. **Upgrade**  
   Ensure you're using the latest release of Ultralytics and all required dependencies. Upgrade with:
   ```bash
   pip install -U ultralytics
   ```
   
2. **Testing in Verified Environments**  
   YOLO and ONNX should perform consistently across environments verified by Ultralytics:
   - **Notebooks** with free GPU:<br>
     <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
   - **Google Cloud** Deep Learning VM (see [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/))
   - **Amazon** Deep Learning AMI (see [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/))
   - **Docker Image**. Detailed [Docker guide here](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/):  
     <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>  

3. **ONNX Debugging**  
   - Check that the exported ONNX model works correctly in Python using `onnxruntime` or another framework as a sanity check.
   - Verify the input preprocessing settings (e.g., scaling factor, padding, normalization) used in your OpenCV code are consistent with those in the `.pt` model.
   - Test with different `opset` versions during export to see if the issue persists (e.g., `model.export(format="onnx", opset=14)`).

## Community Support

Join the thriving Ultralytics community:  
- For real-time discussions, connect on [Discord](https://discord.com/invite/ultralytics) 🎧.  
- Explore deeper conversations on [Discourse](https://community.ultralytics.com).  
- Share and gain insights on our [Subreddit](https://reddit.com/r/Ultralytics).

## Status

If this badge is green, Ultralytics CI tests are passing across environments:  
<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>.

An Ultralytics engineer will review your issue shortly to provide additional assistance 😊. Thank you for your patience and for being a part of the Ultralytics community 🚀!

**Comment by Y-T-G** [comment]
What's the value of `preds.rows`?

**Comment by Kohirus** [comment]
This is the size of model:

![image](https://github.com/user-attachments/assets/227757bd-4a05-4492-89c4-d095f377f533)

So `pred.rows` is 2100, `pred.cols` is 7.

**Comment by Y-T-G** [comment]
Are you sure? Did you print `preds.rows`?

Because you need to transpose the output from `1, 7, 2100` to `1, 2100, 7` before you loop.

**Comment by Y-T-G** [comment]
The confidence of most of the output will be very small. Only the output with the valid object will have high confidence.

**Comment by Kohirus** [comment]
> The confidence of most of the output will be very small. Only the output with the valid object will have high confidence, which is why use the threshold to filter them to get the valid outputs.大多数输出​​的置信度会很小。只有具有有效对象的输出才会具有高置信度，这就是为什么使用阈值来过滤它们以获得有效输出。

I used the same image in Python and C++.

**Comment by Y-T-G** [comment]
The preprocessing is probably incorrect then

**Comment by glenn-jocher** [comment]
@Kohirus great to hear you resolved the issue! Thank you for sharing the solution—it could be helpful to others encountering a similar problem. If you have any further questions, feel free to ask.
