### ISSUE TITLE
How to Remove Class Names and Confidence Threshold from Detection Output

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [ultralytics/ultralytics#18347]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I'm new to Ultralytics YOLOv11 and I'm working on detecting very small objects. The bounding box size, class name, and confidence threshold are not properly matching the object size, making it difficult to visualize the detected objects clearly. I'm running detections using the CLI command. I have the Ultralytics repo already cloned, I would like to know where I can modify the code to reduce or remove the class names and confidence threshold from the output. Additionally, how can I run detect.py directly without using the CLI command?

### Additional

Also, I'd like to add the FPS display in the top-right corner of the inference window. Any guidance on how to achieve this would be greatly appreciated. 🙏🙏

**Comment by UltralyticsAssistant** [comment]
👋 Hello @abuelgasimsaadeldin, thank you for your interest in Ultralytics 🚀! We recommend a visit to the [Docs](https://docs.ultralytics.com) for new users where you can find many [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples and where many of the most common questions may already be answered.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us debug it.

If this is a custom training or usage ❓ Question, please provide as much information as possible, including dataset image examples, code snippets, and detailed logs. For achieving the best model performance or visualizations, ensure you follow our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

Regarding your question about modifying detection output (e.g., removing class names and confidence thresholds, or displaying FPS), customizations can often be made by editing specific sections of the code. Additionally, running the `detect.py` script or modifying the CLI behavior can involve key adjustments. Stay tuned—an Ultralytics engineer will assist you further with this soon!

Join the Ultralytics community where it suits you best:
- 💬 For real-time discussions, connect on [Discord](https://discord.com/invite/ultralytics) 🎧
- 🗣️ For forum-style Q&A, join [Discourse](https://community.ultralytics.com)
- 📢 Explore and participate in [Subreddit discussions](https://reddit.com/r/Ultralytics)

## Upgrade

Make sure you’re using the latest version of Ultralytics for the best experience. Update the `ultralytics` package and dependencies in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

## Environments

Run YOLO in any of the following verified environments, seamlessly preconfigured:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing. CI tests verify proper functioning of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) across macOS, Windows, and Ubuntu systems every 24 hours and on every new repo commit.

We hope this helps for now—an engineer will be here to further assist you soon! 😊

**Comment by glenn-jocher** [comment]
@abuelgasimsaadeldin thank you for your question. To remove the class names and confidence scores from the detection output, you can modify the visualization arguments in the code. Specifically, set `show_labels=False` and `show_conf=False` when using the `model.predict()` method. In the CLI, you can add these flags by modifying the `detect.py` script.

To run `detect.py` directly, navigate to the cloned Ultralytics repository and execute it using Python, e.g., `python detect.py --source <source>`. Ensure you provide the necessary arguments for your use case.

For displaying FPS in the inference window, you can add a custom code snippet to `detect.py` that calculates and overlays the FPS on the video feed. If you need help with that snippet, let me know.

For further details, please refer to [the Predict documentation](https://docs.ultralytics.com/modes/predict/).
