### ISSUE TITLE
ClearML shows a mAP peak on the last epoch

### ISSUE THREAD

**Issue by ppantoniom** [ultralytics/ultralytics#1835]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I found that ClearML shows a peak in the mAP on the last epoch.
As is shown in the picture below, this happens only when the train reaches the final epoch (without being interrupted by the early stopping).

![image](https://user-images.githubusercontent.com/123379349/230035580-abd8a2a3-48b2-413c-b030-1757e86bb761.png)

I hint that the final mAP report was done after loading the `best.pt`. Is that true? If so, is there a way of reporting the actual performance (not overwriting the model performance on the last epoch)?

### Environment

- commit 4198570
- Python 3.8
- ubuntu 22.04

### Minimal Reproducible Example

```
# Choose model
model_name = "yolov8n"

# ClearML init
task = Task.init(project_name="YOLOv8", task_name=model_name)

# Load pre-trained model
detection_model = YOLO(f"{model_name}.pt")

# Train the model
detection_model.train(data="/datasets/coco128/dataset.yaml", epochs=50, patience=50, classes=80)

# Save used hyperparameters
task.connect(detection_model.overrides)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Thank you for reporting this issue, @Chrom2961. The `mAP` reported by `ClearML` comes from the evaluation of the model with the `best.pt` weights, which might not be the final epoch if early stopping is triggered. However, the model is trained until the last epoch consistently. If you would like to know the actual performance, you can run a final evaluation of the trained model using the `pycocotools` COCO evaluation metrics, or use the `test` method in the `detect` module to test the model on a specific dataset to observe the mAP or other detection metrics.

**Comment by pderrenger** [comment]
You're welcome, @ppantoniom! If you have any further questions or need additional assistance, feel free to ask. Happy to help!

**Comment by glenn-jocher** [comment]
@pderrenger you're welcome! If you need more help, just let me know. 😊👍
