### ISSUE TITLE
Prediction on Youtube video slows down massively

### ISSUE THREAD

**Issue by initdebugs** [ultralytics/ultralytics#1837]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I tried doing prediction on a Youtube video for the first time. The video on youtube is 3 minutes long:
[https://www.youtube.com/watch?v=_xhycdLcrt4](ttps://www.youtube.com/watch?v=_xhycdLcrt4)

I tried doing the prediction and the video that came out is 15:38 minutes long. It is also very laggy (because of slowdown).
This is the ouput video: https://drive.google.com/file/d/1U6w2seUb9_jMHKS9C3HMsNfsSKqca53X/view?usp=sharing

### Environment

Ultralytics YOLOv8.0.58  Python-3.9.7 torch-2.1.0.dev20230403+cu118 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
Windows 11

### Minimal Reproducible Example

```yolo task=detect mode=predict source="https://youtu.be/_xhycdLcrt4" model="G:/My Drive/Projects/TrafficDetection/Models/YoloV8/Github Models/TrafficDetection_8S.pt" save=True device=0 hide_labels=false hide_conf=true line_thickness="1"```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@initdebugs hello, 

It seems like you are experiencing issues with the prediction on a YouTube video using YOLOv8.  The resulting video is longer and laggier than expected. One thing to note is that processing longer videos with YOLOv8 may take some time depending on the configuration of your hardware. You can try adjusting the batch size or video resolution to see if it improves the performance. Additionally, you can refer to the documentation at https://docs.ultralytics.com for more information on optimizing the YOLOv8 performance.

**Comment by initdebugs** [comment]
@glenn-jocher This is not the issue. The processed video is 13 minutes longer than the original video. I don't really care about processing time.

**Comment by glenn-jocher** [comment]
@initdebugs, apologies for the confusion. It appears that the output video generated by YOLOv8 is much longer than the original video. This may be related to the FPS settings of the input video. You might try to adjust the FPS of the input video to see if that resolves the issue. You can also try using a different video player to view the output video to see if it's a playback issue. Additionally, please refer to the documentation and other issues on the Ultralytics YOLOv8 GitHub page to see if there are similar issues and solutions that might be helpful to you.

**Comment by initdebugs** [comment]
@glenn-jocher The input video is 30fps. Different video player does not work, the video itself is made longer than the original. 3 minutes to 16 minutes

**Comment by glenn-jocher** [comment]
@initdebugs, thank you for the clarification. It appears that the output video generated by YOLOv8 is significantly longer than the original input video despite having the same FPS. This may be a potential bug in the YOLOv8 algorithm. I suggest submitting an issue on the Ultralytics YOLOv8 GitHub page with details on the steps to reproduce the issue and include any additional information that may be helpful in identifying the source of the problem. The Ultralytics team will review the issue and provide feedback on potential solutions or workarounds.

**Comment by initdebugs** [comment]
This is the GitHub page and this is me submitting the issue.

**Comment by glenn-jocher** [comment]
@initdebugs apologies for misunderstanding your previous message. Thank you for submitting the issue on the Ultralytics YOLOv8 GitHub page. Our team will review it and provide assistance as needed. In the meantime, please feel free to explore the documentation https://docs.ultralytics.com for more information on working with YOLOv8 and optimizing its performance.

**Comment by tekert** [comment]
The problem is still there, any prediction on a youtube video takes ~2 seconds per frame and doesn't skip frames to account for the time lost, so the video takes way longer to play, in slow motion, does not happen on other stream sources like rtmp etc. 
Speed: 1.0ms preprocess, 28.6ms inference, 2.3ms postprocess per image at shape (1, 3, 640, 640)

It seems there is a problem on the youtube decoder.

**Comment by pderrenger** [comment]
@tekert i'm glad to hear that the issue has been resolved! If you have any more questions or need further assistance in the future, feel free to reach out. Happy coding!
