### ISSUE TITLE
Print or log operations not working in loop with stream=True

### ISSUE THREAD

**Issue by Pawan-Valluri** [ultralytics/ultralytics#1840]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I'm trying to some operations and printing the results inside the loop while settng the option stream=True
But results are being printed outside the loop and the results are aggregared

I'm running the model(TensorRT) on 6 streams
I'm trying to print people count per iteration, but the results are after the loop and the results are aggregated

I'm running the following script
```python
from ultralytics import YOLO
import cv2

model = YOLO("yolov8_proj/models/yolov8x_6batch.engine")
results = model("streams.streams", stream=True, show=True, classes=[0], task="detect")  # setting streams=True

while True:
    result = next(results)
    people_count = list(map(lambda x:x.boxes.cls.tolist().count(0), results)) # 0 is label for person class
    print("people Count", people_count)    

    if cv2.waitKey(1) == "q":
        break
```
Output:
```error
Loading yolov8_proj/models/yolov8l_6st.engine for TensorRT inference...
[04/05/2023-09:27:18] [TRT] [I] Loaded engine size: 85 MiB
[04/05/2023-09:27:18] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +7, GPU +34, now: CPU 291, GPU 1376 (MiB)
[04/05/2023-09:27:18] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +84, now: CPU 0, GPU 84 (MiB)
[04/05/2023-09:27:18] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +32, now: CPU 206, GPU 1376 (MiB)
[04/05/2023-09:27:18] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +278, now: CPU 0, GPU 362 (MiB)

1/6: rtsp:<some ip>... Success ✅ (inf frames of shape 1280x720 at 30.00 FPS)
2/6: rtsp:<some ip>... Success ✅ (inf frames of shape 704x576 at 30.00 FPS)
3/6: rtsp:<some ip>... Success ✅ (inf frames of shape 1280x720 at 30.00 FPS)
4/6: rtsp:<some ip>... Success ✅ (inf frames of shape 1280x720 at 30.00 FPS)
5/6: rtsp:<some ip>... Success ✅ (inf frames of shape 1280x720 at 30.00 FPS)
6/6: rtsp:<some ip>... Success ✅ (inf frames of shape 1280x720 at 30.00 FPS)

0: 640x640 (no detections), 1: 640x640 (no detections), 2: 640x640 4 persons, 3: 640x640 (no detections), 4: 640x640 1 person, 5: 640x640 2 persons, 118.6ms
0: 640x640 (no detections), 1: 640x640 (no detections), 2: 640x640 4 persons, 3: 640x640 (no detections), 4: 640x640 1 person, 5: 640x640 3 persons, 165.4ms
0: 640x640 (no detections), 1: 640x640 (no detections), 2: 640x640 4 persons, 3: 640x640 (no detections), 4: 640x640 1 person, 5: 640x640 4 persons, 13.5ms
0: 640x640 (no detections), 1: 640x640 (no detections), 2: 640x640 4 persons, 3: 640x640 (no detections), 4: 640x640 1 person, 5: 640x640 4 persons, 12.6ms
0: 640x640 (no detections), 1: 640x640 (no detections), 2: 640x640 4 persons, 3: 640x640 (no detections), 4: 640x640 1 person, 5: 640x640 3 persons, 12.6ms
0: 640x640 (no detections), 1: 640x640 (no detections), 2: 640x640 4 persons, 3: 640x640 (no detections), 4: 640x640 1 person, 5: 640x640 3 persons, 15.0ms
0: 640x640 (no detections), 1: 640x640 (no detections), 2: 640x640 4 persons, 3: 640x640 (no detections), 4: 640x640 1 person, 5: 640x640 3 persons, 13.4ms
Speed: 0.6ms preprocess, 4.5ms inference, 4.6ms postprocess per image at shape (1, 3, 640, 640)

people Count [4, 0, 1, 2, 0, 0, 4, 0, 1, 3, 0, 0, 4, 0, 1, 4, 0, 0, 4, 0, 1, 4, 0, 0, 4, 0, 1, 3, 0, 0, 4, 0, 1, 3, 0, 0, 4, 0, 1, 3, 0, 0, 4, 0, 1, 4, 0, 0, 4, 0,]

Traceback (most recent call last):
  File "yolov8test.py", line 9, in <module>
    result = next(results)
StopIteration
terminate called without an active exception
terminate called recursively
terminate called recursively
Aborted
```
### Environment

I'm running the script on a docker container (from nvidia pytorch image) with some installations

### Minimal Reproducible Example

```python
from ultralytics import YOLO
import cv2

model = YOLO("yolov8_proj/models/yolov8x_6batch.engine")
results = model("streams.streams", stream=True, show=True, classes=[0], task="detect")  # setting streams=True

while True:
    result = next(results)
    people_count = list(map(lambda x:x.boxes.cls.tolist().count(0), results)) # 0 is label for person class
    print("people Count", people_count)    

    if cv2.waitKey(1) == "q":
        break

```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Pawan-Valluri** [comment]
I've tried writing results in a txt file(inside the loop) too, but same problem persists
results are after the loop and results are aggregated

**Comment by glenn-jocher** [comment]
@Pawan-Valluri it looks like results are being aggregated for multiple runs of the loop and printed outside the loop. This is likely happening because the code is keeping the previous data stored and is not resetting for each new iteration of the loop. One possible solution could be to initialize/reset the values before each iteration of the loop to avoid aggregated results. Also, you can try to further debug and isolate the issue by checking the variables for each iteration using print statements or by writing to a log file.

**Comment by glenn-jocher** [comment]
@Pawan-Valluri thank you for clarifying your question. It seems that the problem might not be related to keeping the previous data stored. Instead, it may be related to the way the print statements are working in the loop. 

By default, the `print()` function buffers the output, which means the output is not immediately printed to the console. Instead, it is stored in a buffer and then printed when the buffer is flushed. This can cause the delay you are seeing between the actual people count and the printed output. 

To make the results print in real-time, you can either flush the buffer manually using `sys.stdout.flush()` after each `print()` statement in the loop or you can turn off the buffer by using the `-u` flag when running the script (e.g. `python -u my_script.py`). This will cause the output to be immediately printed to the console without buffering.

**Comment by Pawan-Valluri** [comment]
I've tried `sys.stdout.flush()` and `print(flush=True)`.
I've also tried the `-u` too

but the results are the same

**Comment by glenn-jocher** [comment]
@Pawan-Valluri sure! One possible reason for the results not being printed in real-time could be due to buffering of the output. By default, the `print()` function buffers the output which causes a delay between the actual people count and the printed output. To make the results print in real-time, we need to flush the buffer manually after each `print()` statement in the loop using `sys.stdout.flush()` or by using `-u` flag when running the script. However, if the problem still persists, we may need to look for other possible causes such as issues with the loop or the way data is being stored or accessed in the script.

**Comment by glenn-jocher** [comment]
@Pawan-Valluri it seems like you have explored multiple possible solutions for resolving the issue of not getting real-time results, including flushing the output buffer with `sys.stdout.flush()`, using `print()` with `flush=True`, and using the `-u` flag when running the script.

In general, it is always best practice to try to avoid buffering any output when working with real-time data streams. When using the `print()` function in Python, buffering of the output can cause a delay between the actual data and the printed output. As a workaround, we can try to flush the buffer manually by calling `sys.stdout.flush()` after each `print()` statement, or by using `-u` flag when running the script. 

If buffering is not the cause of the issue, other possible reasons may include issues with the loop, such as how data is being stored or accessed. Working with generators can sometimes cause issues when used within a loop, especially with regards to lazy evaluation of the generator. Thus it may be worth looking into how the generator is being used within the loop and checking that it is working as intended.

**Comment by Pawan-Valluri** [comment]
I've tried all options regardinng flushing and others, but still nothing works. Any solution to this?

**Comment by pderrenger** [comment]
@Pawan-Valluri It seems like you've thoroughly explored various potential solutions for addressing the real-time print issue, without success. Given this, I recommend reaching out to the Ultralytics YOLOv8 community or opening an issue on the YOLOv8 GitHub repository to seek further assistance. The developers and other community members may have insights or alternative approaches to resolve the issue. Feel free to provide your code and a detailed explanation of the problem when seeking help from the community.
