### ISSUE TITLE
Yolov8 Segmentation Validation Error

### ISSUE THREAD

**Issue by abdulaMLE** [ultralytics/ultralytics#1841]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

![image](https://user-images.githubusercontent.com/128579607/230071728-8ef5d471-c843-4d91-b3a5-6125392f569f.png)

### Minimal Reproducible Example

!yolo val segment data=coco128.yaml batch=1 device=0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Tobi_MLE, thank you for sharing this bug 🐛 you found with us. However, we need more information to help you. 

Could you please provide more details about the error you are encountering? It would be helpful to see the full error traceback that is being produced, as well as any other relevant information about your setup and what you are trying to accomplish.

Also, it seems like you are trying to run some code that is specific to YOLOv5, not YOLOv8. If you are interested in YOLOv8, we recommend using the correct commands and scripts for YOLOv8. You may refer to the [YOLOv8 documentation](https://docs.ultralytics.com/) and try the examples given there.

We appreciate your interest in submitting a PR! If you have a fix for the bug you found, please feel free to open a pull request with your changes. Thank you!
