### ISSUE TITLE
Key point detection to yolov8?

### ISSUE THREAD

**Issue by June1124** [ultralytics/ultralytics#185]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Have you considered adding key point detection to yolov8?

**Comment by AyushExel** [comment]
@June1124 yes we have considered it and we plan to support it soon

**Comment by mobotyx** [comment]
We're also interested in key-point detection. Looking forward to it.

**Comment by achbogga** [comment]
Also interested, Please let me know if I can help speed up the process. Thanks!

**Comment by AyushExel** [comment]
Sure. If you'd like to take a stab at it, I'd be happy to work on the PR with you

**Comment by AyushExel** [comment]
I'll start working on it next week. Meanwhile for dataset we can use coco key point dataset

**Comment by AyushExel** [comment]
I'll start working on it next week. Meanwhile for dataset we can use coco key point dataset

**Comment by salikramkhanal** [comment]
I am also looking for the same.

**Comment by AyushExel** [comment]
The PR is open. We aim to get this done by the end of month

**Comment by AyushExel** [comment]
yes you can set nc

**Comment by glenn-jocher** [comment]
@dferrarigrowtech @AyushExel actually our dataset YAMLs don't use `nc` anymore, they read the class count directly from the `names` dict, i.e.:

https://github.com/ultralytics/ultralytics/blob/8c8c43922c8a01f70ef462a3213c270648275bb3/ultralytics/datasets/coco.yaml#L1-L98
