### ISSUE TITLE
Is there a C++ example available for YOLOv8 segmentation with OpenCV ONNX?

### ISSUE THREAD

**Issue by milan0092** [ultralytics/ultralytics#1852]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I found a Python implementation here: https://github.com/ibaiGorordo/ONNX-YOLOv8-Instance-Segmentation
and a v5 implementation for C++ here: https://github.com/UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp

So I may be able to figure it out based on that, but it would be great if there is already an example available somewhere...

Edit: I wasn't seeing the latest updates on the v5 c++ implementation, which is a lot more clear now.

**Comment by glenn-jocher** [comment]
@hightower87, glad you found the resources you needed to help you out! While we do not currently have an official YOLOv8 implementation for C++, you might find our YOLOv5 C++ implementation a valuable reference. The YOLOv8 algorithm is very similar to YOLOv5, so with some minor tweaks you should be able to adapt it to work with YOLOv8 as well. Good luck with your project!

**Comment by madinwei** [comment]
> Edit: I wasn't seeing the latest updates on the v5 c++ implementation, which is a lot more clear now.
Hello @milan0092 , is it possible to share the v8 c++ implementation or give me some tips on how to use my v8 model with v5 c++ code? and thank you in advance.

**Comment by glenn-jocher** [comment]
Hello @madinwei, unfortunately there is no official YOLOv8 implementation for C++ provided by Ultralytics at this time. However, you may find helpful information in our YOLOv5 C++ implementation or in the other resources you mentioned, such as the Python and v5 C++ implementations you previously found. In general, the YOLOv8 algorithm is very similar to YOLOv5, so you should be able to make minor modifications to v5 code in order to use the YOLOv8 model. If you require further assistance, please provide more details on your specific use case and what exactly you are trying to accomplish.

**Comment by milan0092** [comment]
@madinwei Sure, the main thing is that you need to reshape the output before looping through the data and change the step size from 5 to 4. The rest is very similar as mentioned before.

// Reshape YOLOv8 output
auto rows = output[0].size[2];
auto dims = output[0].size[1];
output[0] = output[0].reshape(1, dims);
transpose(output[0], output[0]);

// Process output
auto *data = (float *) output[0].data;
for (int r = 0; r < rows; r++)
{
    float *scores = data + 4;
    ...
   data += dims;
}

Hope that helps.

**Comment by glenn-jocher** [comment]
Thank you for sharing that code snippet, @milan0092. It seems that the major difference between the YOLOv5 and YOLOv8 C++ implementations is in the output data shape of the model, and some adjustments need to be made when looping through the data. Overall, the process is quite similar, so with some minor modifications, the v5 C++ code can be adjusted to work with v8 models. It is worth noting that Ultralytics does not provide an official YOLOv8 C++ implementation at this time.

**Comment by glenn-jocher** [comment]
@milan0092 BTW we do have an official C++ Detect inference example here:
https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-CPP-Inference

**Comment by madinwei** [comment]
@milan0092 @glenn-jocher ,
thank you for your help and response, I really appreciate it. I see, so I need to change the output shape.
BTW I also found this implementation for v8 in c++:  [v8](https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp) 
it might help,

**Comment by cvetaevvitaliy** [comment]
c++ implementation yolov8 segmentation 

https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp

**Comment by glenn-jocher** [comment]
Hello @cvetaevvitaliy, thank you for sharing the YOLOv8 C++ implementation with us. We appreciate the contributions from the community. As a reminder, however, we would like to clarify that the official Ultralytics YOLOv8 repository at https://github.com/ultralytics/ultralytics does not currently provide an official YOLOv8 C++ implementation. That being said, we welcome the sharing of resources and code from the community that can help others work with YOLOv8. If you have any questions or issues related to YOLOv8, please don't hesitate to let us know.

**Comment by cyrusbehr** [comment]
I've created an easy-to-follow sample project which demonstrates how to run YoloV8 GPU inference using the TensorRT C++ API. Check it out [here](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP).

**Comment by glenn-jocher** [comment]
Hello @cyrusbehr, thank you for sharing your sample project demonstrating how to run YOLOv8 GPU inference using the TensorRT C++ API. We appreciate your contribution to the YOLOv8 community. It's always great to see different approaches and implementations to working with YOLOv8. Please feel free to share any further insights or suggestions you may have.

**Comment by cyrusbehr** [comment]
Hi there folks. In the latest release of my project, I demonstrate how to use the TensorRT C++ API to run YoloV8 inference with support for Semantic Segmentation! Check out the project [here](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP).

**Comment by glenn-jocher** [comment]
@cyrusbehr hello! Thank you for sharing your project with us. It's great to see different implementations and approaches to running YOLOv8 inference using the TensorRT C++ API. We appreciate your contribution to the YOLOv8 community. If you have any further insights or suggestions related to YOLOv8, feel free to let us know. We're here to help.

**Comment by FourierMourier** [comment]
Hello there! This is yet another C++ ONNX inference implementation that produces identical results to the Python version, regardless of the image size.
https://github.com/FourierMourier/yolov8-onnx-cpp

**Comment by glenn-jocher** [comment]
Hello @FourierMourier, thank you for sharing your implementation of YOLOv8 in C++ with ONNX inference. We appreciate how the YOLOv8 community continues to create diverse solutions and shares them for the benefit of others. Keep in mind that the official Ultralytics YOLOv8 repo does not currently provide a YOLOv8 C++ implementation, so we love to see independent implementations like this from community members. We're always here to help with any questions or issues related to YOLOv8, so don't hesitate to reach out. Thank you for being a part of our community!

**Comment by DavidFord1** [comment]
> c++ implementation yolov8 segmentation
> 
> https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp

Hello
Please put the executable file
I failed to compile because of the onnxruntime library and...
It is a difficult and very time-consuming work and there are many errors

**Comment by DavidFord1** [comment]
> Hello @FourierMourier, thank you for sharing your implementation of YOLOv8 in C++ with ONNX inference. We appreciate how the YOLOv8 community continues to create diverse solutions and shares them for the benefit of others. Keep in mind that the official Ultralytics YOLOv8 repo does not currently provide a YOLOv8 C++ implementation, so we love to see independent implementations like this from community members. We're always here to help with any questions or issues related to YOLOv8, so don't hesitate to reach out. Thank you for being a part of our community!

Hello
Please put the executable file
I failed to compile because of the onnxruntime library and...
It is a difficult and very time-consuming work and there are many errors

**Comment by eliahilse** [comment]
> > Hello @FourierMourier, thank you for sharing your implementation of YOLOv8 in C++ with ONNX inference. We appreciate how the YOLOv8 community continues to create diverse solutions and shares them for the benefit of others. Keep in mind that the official Ultralytics YOLOv8 repo does not currently provide a YOLOv8 C++ implementation, so we love to see independent implementations like this from community members. We're always here to help with any questions or issues related to YOLOv8, so don't hesitate to reach out. Thank you for being a part of our community!
> 
> Hello Please put the executable file I failed to compile because of the onnxruntime library and... It is a difficult and very time-consuming work and there are many errors

Here's an example of Yolo v8 in C++ with pure OpenCV (using it's dnn module).
https://github.com/eliahilse/visionary (cpp/prototypes/v1/VisionaryProto1)
Instructions on how to get a suitable .onnx model are in the readme ^^
