### ISSUE TITLE
Any examples on pose estimation with latest Yolov8 pose model released?

### ISSUE THREAD

**Issue by joansc** [ultralytics/ultralytics#1853]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have seen Yolov8 pose estimation model got released. Are out there any examples available using this new model?

Thanks,

Joan

**Comment by glenn-jocher** [comment]
@joansc hi Joan! Thank you for your interest in YOLOv8. Yes, we have recently released YOLOv8-P (Pose Estimation) and you can find examples using it in our official documentation at https://docs.ultralytics.com/tasks/pose_estimation/. If you have any questions or need further assistance, please let us know!

**Comment by cyalla** [comment]
link not working  https://docs.ultralytics.com/tasks/pose_estimation/. 
404 - Not found

**Comment by glenn-jocher** [comment]
Here are a few examples. You can create your own by following the usage examples in https://docs.ultralytics.com/tasks/pose


![img](https://user-images.githubusercontent.com/26833433/230653210-e4ff3653-c189-4ce8-bf3d-0816638436bb.jpg)


![image-asset](https://user-images.githubusercontent.com/26833433/230653208-d3880da7-396f-4242-9068-96955cd1115c.jpeg)
![gettyimages-881484382-612x612](https://user-images.githubusercontent.com/26833433/230653203-4e1e6447-51fd-4d56-8b5e-152e24d02f8a.jpeg)

**Comment by glenn-jocher** [comment]
Here are a few examples. You can create your own by following the usage examples in https://docs.ultralytics.com/tasks/pose


![20180908_WeWork_Hibiya_Park_Front_-_Common_Areas_-_Wide-3](https://user-images.githubusercontent.com/26833433/230657504-daeeb982-55af-44da-a7dc-2afbe51df7b9.jpeg)
![gettyimages-881484382-612x612](https://user-images.githubusercontent.com/26833433/230657509-611a2a3a-a12c-4128-95c0-5982398ac189.jpeg)
![image-asset](https://user-images.githubusercontent.com/26833433/230657510-f5d447a5-e0c1-4ee9-96bd-dac2050c2ba7.jpeg)
![IMG_0698](https://user-images.githubusercontent.com/26833433/230657511-f024c9fa-d728-4e5c-ac26-0fa794304d46.jpg)
![img](https://user-images.githubusercontent.com/26833433/230657513-3067168c-bf08-44a1-b5a9-644f57132050.jpg)
![zidane](https://user-images.githubusercontent.com/26833433/230657515-8edc0da2-b31f-40e7-9b57-5dd2d967f7d3.jpg)

**Comment by ben-spiteri** [comment]
Hello! I followed the steps in the documentation at https://docs.ultralytics.com/tasks/pose, however the error message AttributeError: Can't get attribute 'PoseModel' on <module 'ultralytics.nn.tasks' is appearing

**Comment by stefp** [comment]
@joansc FYI I also found some more documentation on the Ultralytics YOLO format here: https://docs.ultralytics.com/datasets/pose/

**Comment by glenn-jocher** [comment]
@stefp thank you for sharing this link. We are always updating the Ultralytics documentation to make it more comprehensive and user-friendly. If you have any further questions or suggestions, please let us know. We're glad to help!
