### ISSUE TITLE
how to export the yolov8-pose model to onnx？

### ISSUE THREAD

**Issue by xinsuinizhuan** [ultralytics/ultralytics#1856]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I export the yolov8n-pose.pt to onnx with command:
yolo mode=export model=yolov8n-pose.pt format=onnx simplify=True
get the the onnx model, but the ouput is error: 1x56x8400
But the forth num is should be score, as [0,1], but now is so big:
![图片](https://user-images.githubusercontent.com/40679769/230254218-4b423f1d-e333-4fe5-b340-72c6552c1a3c.png)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@glenn-jocher is hard at work on exports will provide an update when he's done. Stay tuned!

**Comment by dizcza** [comment]
Same for me.

In my case, the output is `1x135x8400`. I used python backed to export the trained model to ONNX:

```python
from ultralytics import YOLO
import cv2
import time

cap = cv2.VideoCapture(0)

model = YOLO("yolov8n-pose.pt")  # load a pretrained model (recommended for training)
success = model.export(format="onnx")  # export the model to ONNX format
```

Once again, OpenCV DNN backed has trouble loading this file: https://github.com/opencv/opencv/issues/23464. Don't know on which side the error happens. In either case, something fishy is going on with the yolov8 pose exporter.

**Comment by glenn-jocher** [comment]
@dizcza thank you for bringing this to our attention. Our team is aware of this issue and is actively working on fixing it. We apologize for any inconvenience this has caused and appreciate your patience. In the meantime, please refer to our documentation at https://docs.ultralytics.com/ for more information on working with YOLOv8.

**Comment by BecayeSoft** [comment]
Hi,
I have the same issue like @dizcza.

### ONNX
`
session = ort.InferenceSession(path_or_bytes= 'model/best.onnx')
`

Using ONNX to load the model returns an ouput tensor of shape: `[1, 5, 8400]`.
The inputs seem correct to me though.

### cv2
Also when reading the ONNX with cv2
`
onnx_model = 'model/best.onnx'
model = cv2.dnn.readNetFromONNX(onnx_model)
`

I get the following error:

`cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1040: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20220524::ONNXImporter::handleNode'
> Node [Reshape@ai.onnx]:(onnx_node!/model.22/dfl/Reshape) parse error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layers\reshape_layer.cpp:108: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'cv::dnn::computeShapeByReshapeMask'
> `

**Comment by BecayeSoft** [comment]
Hi,
I have the same issue like @dizcza.

### ONNX
`
session = ort.InferenceSession(path_or_bytes= 'model/best.onnx')
`

Using ONNX to load the model returns an ouput tensor of shape: `[1, 5, 8400]`.
The inputs seem correct to me though.
<img width="314" alt="image" src="https://user-images.githubusercontent.com/87549214/231055987-dac785e0-e691-4387-abf9-522e4c5c00e9.png">


### cv2
Also when reading the ONNX with cv2
`
onnx_model = 'model/best.onnx'
model = cv2.dnn.readNetFromONNX(onnx_model)
`

I get the following error:

`cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1040: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20220524::ONNXImporter::handleNode'
> Node [Reshape@ai.onnx]:(onnx_node!/model.22/dfl/Reshape) parse error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layers\reshape_layer.cpp:108: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'cv::dnn::computeShapeByReshapeMask'
> `

**Comment by glenn-jocher** [comment]
@BecayeSoft we apologize for the inconvenience this has caused you. We are aware of these issues and are actively working on a fix. As a temporary workaround, we recommend that you try using third-party libraries, such as TensorFlow or PyTorch, to load the exported model file. Additionally, please check our documentation available at https://docs.ultralytics.com for further information on working with YOLOv8. Thank you for your patience and understanding.

**Comment by glenn-jocher** [comment]
@dizcza @BecayeSoft you can run YOLOv8 Pose ONNX inference directly with ultralytics, i.e.
```commandline
yolo predict model=yolov8n-pose.onnx
```

or 
```python
from ultralytics import YOLO

model = YOLO('yolov8n-pose.onnx')
results = model(image)
```

**Comment by BecayeSoft** [comment]
@glenn-jocher thank you, that’s the solution I used. I used Ultralytics in my API directly

**Comment by BecayeSoft** [comment]
> @BecayeSoft I've posted the problem you mentioned to the OpenCV issue tracker: #1856
> 
> It seems to be resolved, I haven't tried yet - I was getting some python import cv2 errors with opencv built from master branch. Let me know if you manage to import the yolovn-pose.onnx model in OpenCV. Thanks.
@dizcza I will let you know when I try it

**Comment by glenn-jocher** [comment]
@BecayeSoft Thank you for keeping us informed. We appreciate your contribution to the YOLOv8 community. If you have any further questions or concerns, please don't hesitate to reach out.

**Comment by mattcattb** [comment]
2 weeks ago I was experiencing the same issue. I upgraded to Ultralytics 8.0.90 today and ran the model.export(format='onnx') API, getting another 1x56x8400 onnx model. 

This issue seems to effect other exporting functions, such as the TF-lite [https://github.com/ultralytics/ultralytics/issues/2317] model conversion, the irregular being the 8400 insteal of 1 shape. I could be completely wrong however.

Thank you for your dedication into this bug! I would love to be updated on the progress. Thank you. 

Usage specifics:
-Utralytics: 8.0.90
-Python: 3.10.10
-Pytorch: 2.0.0 CPU
-OS: Ubuntu 22.04.2 LTS

**Comment by glenn-jocher** [comment]
@mattcattb thank you for reaching out to us and providing the details of your usage. We appreciate your patience and understanding as our team works to resolve this issue with ONNX model exports. Our developers are currently investigating and testing a solution. In the meantime, please stay tuned to our GitHub repository for further updates. If you have any other questions or concerns, please don't hesitate to let us know. Thanks again for your support of YOLOv8.

**Comment by yuliya3000** [comment]
@glenn-jocher Hello!
Could you please help? I have yolov8-seg.pt (pretrained model on my custom dataset) and I want to fasten its inference speed. For this purpose i'm converting to onnx format but get error:

```
WARNING  Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', or 'pose'.
Loading C:\Users\... \yolov8l_seg.onnx for ONNX Runtime inference...
requirements: Ultralytics requirement "onnxruntime-gpu" not found, attempting AutoUpdate...
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\RedmiBook\\anaconda3\\Lib\\site-packages\\~umpy\\core\\_multiarray_tests.cp39-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

requirements:  Command 'pip install --no-cache "onnxruntime-gpu"  ' returned non-zero exit status 1.
C:\Users\RedmiBook\anaconda3\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:53: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'CPUExecutionProvider'
  warnings.warn("Specified provider '{}' is not in available provider names."
```
I'm applying onnx model to basic code:

```

 model = YOLO(model_weights)
    
    labels =[]
  
    while True:
        status, frame = cap.read()
        if status:
            results = model(frame , stream =True)    
...
```

**Comment by glenn-jocher** [comment]
Hello @yuliya3000,
Based on the error message you provided, it seems that you need to specify the "model task" for your segmentation model during the export process. It looks like the model is currently defaulting to task 'detect' and not recognizing the segmentation task you are trying to perform. You can explicitly define this task by setting the "task=segment" parameter when calling the `export` function. 

Regarding the second error message you received, "KeyError: 16", this seems to be a result of the model not recognizing a class label in your segmentation output. You may want to double-check your label names and ensure that they match with the expected outputs of your model. 

Finally, make sure you have the `onnxruntime` package installed. As for the warning message about `onnxruntime-gpu`, it is not required for exporting the model to ONNX but will help you to run the exported ONNX model with GPU support. 

I hope this helps! Let us know if you have any further questions or concerns.

**Comment by yuliya3000** [comment]
@glenn-jocher Thanks for reply. I tried:
```
model = YOLO("./yolov8l_seg.pt")  
success = model.export(imgsz = 320, format="onnx", task='segment')
```
but is still gives the warning and error about input size (Got: 640 Expected: 320)
Seems it does not see this param 'task'

**Comment by yuliya3000** [comment]
@glenn-jocher Ok, thanks) what i found out when `dynamic = True` it is possible to change the `imgsz` for e.g. to 320  (with no error) But there is another error occurs (just like in this discussion https://github.com/ultralytics/yolov5/issues/10277) and seems it is connected to `task` param  which should be `segment` just as in my case and which is unseen now

**Comment by glenn-jocher** [comment]
@yuliya3000 thank you for sharing your findings and experience with us. We appreciate your efforts in finding the workaround. As for the `task` parameter issue, we apologize for the inconvenience caused by this known issue. Currently, when exporting to ONNX format, YOLOv8 ignores the `task` parameter, resulting in the error you encountered. Our development team is aware of this issue and is actively working on a solution. In the meantime, you can try manually editing the exported ONNX model to modify the input shape to match your desired size, using a tool like `onnx-tf` or `onnx-editor`. Again, we appreciate your patience and contributions to YOLOv8.

**Comment by richardverheyen** [comment]
Hi @glenn-jocher 
I'm attempting to export the yolov8l-pose model to CoreML format, and I'm aware that NMS isn't currently working for exporting Pose models.
I expected that the (1, 56, 8400) output tensor would have 8400 * Dim = 3 formatted pose outputs I could then do NMS with OpenCV on, but the output data seems to not fit into the dim3 yolo pose format. Is it possible to pull useful pose keypoints from the exported (1, 56, 8400) model output? 
And/or: has anyone got Yolov8Pose working in CoreML or ONNX in another format which I can then convert from ONNX to CoreML?
<img width="1096" alt="Screenshot 2023-09-15 at 1 35 34 pm" src="https://github.com/ultralytics/ultralytics/assets/18094975/d2ea9fd2-4ebc-4dfe-b47e-b9812a3c9cfc">

**Comment by glenn-jocher** [comment]
@richardverheyen hi there!

The dimensions of the output tensor from the model, specifically (1, 56, 8400), are derived from the model architecture and the specific implementation details of the Pose Prediction task in YOLOv8. 

The tensor does indeed represent pose predictions - however, these are encoded in a manner specific to YOLOv8, and wouldn't necessarily be meaningful if interpreted directly as 3D coordinates. 

The process of extracting meaningful pose keypoints from these predictions involves further steps such as applying certain transformations and decoding operations to the raw output.

Your CoreML or ONNX model is simply replicating the forward pass computation of the original YOLOv8 model, which does not include the decoding of these predictions into meaningful keypoints. This is done separately in the YOLOv8 codebase.

Unfortunately, exporting the full pose prediction functionality, including this decoding step and non-maxima suppression, to ONNX or CoreML is currently not supported. We are aware that our users are interested in such a feature, and we are exploring ways to support this in the future.

I would recommend running the NMS and decoding steps in PyTorch based on the PyTorch model, and then applying the transformations and encoding in your CoreML or ONNX application as a separate post-processing step after you run your model. 

Please feel free to continue sharing any doubts or concerns you have. Thank you for using YOLOv8!

**Comment by richardverheyen** [comment]
Thanks so much for your help with this!
Based on the Yolo pose data format: 
`<class-index> <x> <y> <width> <height> <px1> <py1> <p1-visibility> <px2> <py2> <p2-visibility> <pxn> <pyn> <p2-visibility>`

I think you're saying that I can run the pytorch logic found in `head.py/Detect.forward()` on the first 5 of 56 channels from the (1 × 56 × 8400) shaped tensor I'm getting out of the pose.mlpackage:
```
x_cat = torch.cat([xi.view(shape[0], self.no, -1) for xi in x], 2)
# ...
box, cls = x_cat.split((self.reg_max * 4, self.nc), 1)
dbox = dist2bbox(self.dfl(box), self.anchors.unsqueeze(0), xywh=True, dim=1) * self.strides
# ...
y = torch.cat((dbox, cls.sigmoid()), 1)
return y if self.export else (y, x)
```

and then also that I can run the `head.py/Pose.kpts_decode()` logic on the last 51 of 56 channels from the same array. 
```
y = kpts.clone()
if ndim == 3:
    y[:, 2::3].sigmoid_()  # inplace sigmoid
y[:, 0::ndim] = (y[:, 0::ndim] * 2.0 + (self.anchors[0] - 0.5)) * self.strides
y[:, 1::ndim] = (y[:, 1::ndim] * 2.0 + (self.anchors[1] - 0.5)) * self.strides
return y
```
Then I should have valid output data which I can run NMS on?

**Comment by glenn-jocher** [comment]
Hello @richardverheyen,

You're on the right path with the approach you've described. Running the PyTorch logic found in head.py/Detect.forward() on the first 5 of 56 channels will derive the bounding box and class predictions, while applying head.py/Pose.kpts_decode() logic on the last 51 of 56 channels will return keypoint locations and visibility scores.

Once you have that data, you would perform NMS on the bounding box predictions along with their class scores. This will provide you with a final set of detections. For each of these detections, you can then associate the corresponding keypoints.

Please keep in mind that this process will give raw keypoints, meaning that they are relative to each detection box and the visibility scores are between 0 and 1. To get keypoints in the image space or on the original image scale, you would translate and scale them according to the detection box coordinates and size.

Finally, remember that this part of the pipeline is typically termed 'post-processing', and it's quite common that this stage isn't fully exported with the model to ONNX or CoreML. Therefore, these steps need to be replicated in whichever deployment environment you are using.

I hope this clarifies the process. Please feel free to ask if you have more questions!
