### ISSUE TITLE
coco8-pose

### ISSUE THREAD

**Issue by derronqi** [ultralytics/ultralytics#1858]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n-pose.yaml")  # build a new model from scratch
# Use the model
model.train(data="coco8-pose.yaml", epochs=3)  # train the model

train: Scanning /ssd2t/derron/datasets/coco8-pose/labels/train.cache... 4 images, 0 backgrounds, 5 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
train: WARNING ⚠️ /ssd2t/derron/datasets/coco8-pose/images/train/000000000036.jpg: ignoring corrupt image/label: cannot reshape array of size 55 into shape (2)
train: WARNING ⚠️ /ssd2t/derron/datasets/coco8-pose/images/train/000000000049.jpg: ignoring corrupt image/label: cannot reshape array of size 55 into shape (2)
train: WARNING ⚠️ /ssd2t/derron/datasets/coco8-pose/images/train/000000000077.jpg: ignoring corrupt image/label: cannot reshape array of size 55 into shape (2)
train: WARNING ⚠️ /ssd2t/derron/datasets/coco8-pose/images/train/000000000086.jpg: ignoring corrupt image/label: cannot reshape array of size 55 into shape (2)

ValueError: not enough values to unpack (expected 3, got 0)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
We'll check the coco-pose assets today. are you seeing the same error in coco128-pose.yaml?

**Comment by derronqi** [comment]
Thank you for your reply. I didn't see  coco128-pose.yaml

**Comment by AyushExel** [comment]
Oh I see sorry I got confused with coco128-seg.yaml. I'll verify the coco8-pose issue today then

**Comment by derronqi** [comment]
thanks a lot!

**Comment by glenn-jocher** [comment]
@derronqi sure, I'll do my best to explain things conceptually without writing code. Just let me know if you have any questions or need further explanation.

**Comment by derronqi** [comment]
![image](https://user-images.githubusercontent.com/34156011/230278801-7f058081-606e-4acc-8520-4eb4076b1ad6.png)

It is mentioned in the yolov8 docs that coco128-pose.yaml.

**Comment by glenn-jocher** [comment]
@derronqi in the image above, the architecture of YOLOv8 for human pose estimation is shown. The image shows how the body parts are represented as smaller pickled circles and connected by lines that indicate the skeletal structure. The final output from this architecture would be the accuracy of the different body part detection and the connection of these parts to from the human pose estimation. This architecture is built with a Vision Transformer that essentially learns from the images to detect these body parts and provide the outputs by considering the complete image using attention mechanisms. The final layer of the model is the Predict module, which would provide the final output including the location and class of each detected object.

**Comment by derronqi** [comment]
thanks!

**Comment by glenn-jocher** [comment]
@derronqi certainly! The picture above represents how the YOLOv8 architecture works for human pose estimation. The architecture consists of a Vision Transformer that can learn to detect the different body parts and make accurate pose estimations. The body parts are represented by smaller pickled circles that are connected by lines that indicate the skeletal structure. The final output from the architecture is the accuracy of the different body part detections and the seamless connection of these parts to form the actual human pose. The Predict module is the final layer of the architecture that processes the detected body parts and provides the final output which includes the location and class of each detected object in the image.

**Comment by teraoka-hiroshi** [comment]
@derronqi 
Hi
This problem is happening to me too.
how do you solve it?

**Comment by teraoka-hiroshi** [comment]
that the yaml path was wrong and
It worked when I cleared the cache.

**Comment by glenn-jocher** [comment]
@teraoka-hiroshi thank you for sharing your solution. It is great to hear that you were able to resolve the issue. Invalid YAML path can cause errors in loading the data, and clearing the cache can help remove any corrupted files in your dataset. If you encounter any other issues in the future, feel free to ask for help.

**Comment by teraoka-hiroshi** [comment]
thanks!

**Comment by glenn-jocher** [comment]
@teraoka-hiroshi hi,
It looks like you are encountering an issue with YOLOv8's training process on the coco8-pose dataset, where the program is ignoring corrupt image/label files and causing a `ValueError` due to an empty list. One possible solution is to check that your YAML path is correct and make sure that you have downloaded the dataset as instructed in the documentation. Additionally, you can try clearing the cache to remove any corrupted files in the dataset. These steps should help you resolve the issue. If you are still experiencing problems, please let us know, and we would be glad to help you further.
