### ISSUE TITLE
Will the segment task of YOLOV8 generate instance IDs？

### ISSUE THREAD

**Issue by PiBigStar5712** [ultralytics/ultralytics#1860]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I hope to assign a mask with a certain color to each instance by using the segment function of YOLOV8. Now I have several questions that I need help with.

`Q1:  Will the segment function of YOLOV8 assign IDs to each instance? If so, will this ID be reassigned after it is first assigned to the corresponding instance and disappears from the screen?`

`Q2:  When I use ultralytics/yolo/v8/segment/predict.py, how can I only visualize the mask without displaying the original image?`

`Q3:  Is the principle of the boxes generated in the segment task the same as the boxes generated in the detect task? What is the mechanism for generating boxes in a segment? Is it generated by detecting the target or by generating a minimum bounding rectangle box based on the mask data?`

Is there anyone here who can help me？Any help will be appreciated!

### Additional

I have currently completed the assignment of mask colors for different instances, but there are some problem with it.
I modified the code in `ultralytics/yolo/v8/segment/predict.py` as follows, starting at line 65.
```
        ################
        ## Init color_dict ##
        ################
        color_dict = {}

        # Print results
        for c in det.cls.unique():
            n = (det.cls == c).sum()  # detections per class
            ########## change ###########
            color_dict.update({c: n})
            ##########################
            log_string += f"{n} {self.model.names[int(c)]}{'s' * (n > 1)}, "

        ##################### change #######################
        color_keys = list(color_dict.keys())
        my_color = []
        count_iter = -1
        for x in det.cls:
            if x == color_keys[2]:
                count_iter += 1
                if count_iter > 0:
                    my_color.append(x + count_iter)
                else:
                    my_color.append(x)
            else:
                my_color.append(x)
        ##################################################

        # Mask plotting
        if self.args.save or self.args.show:
            im_gpu = torch.as_tensor(im0, dtype=torch.float16, device=mask.masks.device).permute(
                2, 0, 1).flip(0).contiguous() / 255 if self.args.retina_masks else im[idx]
            # self.annotator.masks(masks=mask.masks, colors=[colors(x, False) for x in det.cls], im_gpu=im_gpu)
            self.annotator.masks(masks=mask.masks, colors=[colors(x, True) for x in my_color], im_gpu=im_gpu)
```
Currently, there is an issue with this code where the colors of the same instance may appear differently in different images or videos. This is inconsistent with the idea of binding a color mask to the same instance I described.

**Comment by glenn-jocher** [comment]
@PiBigStar5712 thank you for reaching out with your questions. 

Regarding your first question, YOLOv8's segment function does assign separate IDs to each instance it detects. However, these IDs are not reassigned if the instance disappears from the screen and reappears later. 

To answer your second question, if you want to only visualize the mask without displaying the original image in `ultralytics/yolo/v8/segment/predict.py`, you can comment out or remove the line `self.annotator.show()` in the `def show_results` function.

Regarding your third question, the principle of the boxes generated in the segment task and detect task are different. In segment, the box is generated using the minimum bounding rectangle based on the mask data, while in detect, it is generated by detecting the target object. 

I hope this helps! If you need additional information or assistance, don't hesitate to ask or check out the documentation at https://docs.ultralytics.com.

**Comment by PiBigStar5712** [comment]
> @PiBigStar5712 thank you for reaching out with your questions.
> 
> Regarding your first question, YOLOv8's segment function does assign separate IDs to each instance it detects. However, these IDs are not reassigned if the instance disappears from the screen and reappears later.
> 
> To answer your second question, if you want to only visualize the mask without displaying the original image in `ultralytics/yolo/v8/segment/predict.py`, you can comment out or remove the line `self.annotator.show()` in the `def show_results` function.
> 
> Regarding your third question, the principle of the boxes generated in the segment task and detect task are different. In segment, the box is generated using the minimum bounding rectangle based on the mask data, while in detect, it is generated by detecting the target object.
> 
> I hope this helps! If you need additional information or assistance, don't hesitate to ask or check out the documentation at https://docs.ultralytics.com.

Thank you for your reply! Regarding the content of your reply 
`To answer your second question, if you want to only visualize the mask without displaying the original image in ultralytics/yolo/v8/segment/predict.py, you can comment out or remove the line self.annotator.show() in the def show_results function.`
I haven't found any information about `def show_results` or `self.annotator.show()` in `ultralytics/yolo/v8/segment/predict.py`. And I also used the search function provided by PyCharm to search the total project, but it still failed. Is your description incorrect?
Also, regarding the issue of instance ID, I hope you can tell me which line of code I can obtain the instance ID value from.
Work successfully！

**Comment by glenn-jocher** [comment]
@PiBigStar5712 i apologize for any confusion caused by my previous response. The `def show_results` function and `self.annotator.show()` line are not present in the `ultralytics/yolo/v8/segment/predict.py` file. I apologize for any inaccuracies in my previous response.

Regarding your question about obtaining instance ID values, the instance IDs are not explicitly calculated or returned by YOLOv8's segment function. However, they can be inferred from the ordering of the boxes and masks output by the function. Each box and mask corresponds to a different instance, and the order in which they are output corresponds to their respective instance IDs. 

Please let me know if you have any further questions or need additional clarification.

**Comment by PiBigStar5712** [comment]
> @PiBigStar5712 i apologize for any confusion caused by my previous response. The `def show_results` function and `self.annotator.show()` line are not present in the `ultralytics/yolo/v8/segment/predict.py` file. I apologize for any inaccuracies in my previous response.
> 
> Regarding your question about obtaining instance ID values, the instance IDs are not explicitly calculated or returned by YOLOv8's segment function. However, they can be inferred from the ordering of the boxes and masks output by the function. Each box and mask corresponds to a different instance, and the order in which they are output corresponds to their respective instance IDs.
> 
> Please let me know if you have any further questions or need additional clarification.

Thank you for your reply. According to your statement, I seem to have found the relevant code in `ultralytics/yolo/v8/segment/predict.py`. 

```
        # Print results
        for c in det.cls.unique():
            n = (det.cls == c).sum()  # detections per class
            log_string += f"{n} {self.model.names[int(c)]}{'s' * (n > 1)}, "
```
Can `n` in the above code be understood as `the order` you mentioned?

**Comment by PiBigStar5712** [comment]
> @PiBigStar5712 i apologize for any confusion caused by my previous response. The `def show_results` function and `self.annotator.show()` line are not present in the `ultralytics/yolo/v8/segment/predict.py` file. I apologize for any inaccuracies in my previous response.
> 
> Regarding your question about obtaining instance ID values, the instance IDs are not explicitly calculated or returned by YOLOv8's segment function. However, they can be inferred from the ordering of the boxes and masks output by the function. Each box and mask corresponds to a different instance, and the order in which they are output corresponds to their respective instance IDs.
> 
> Please let me know if you have any further questions or need additional clarification.

I hope to obtain a feasible solution to the problem of removing the original image output while only retaining the mask.
