### ISSUE TITLE
Annotations with holes?

### ISSUE THREAD

**Issue by stphtan94117** [ultralytics/ultralytics#1862]
Is it possible to make annotations of shapes with holes on it? e.g. donuts
i have segmentation data json, but it is s hard to convert yolo txt, because those shapes are all with holes.
do you have any good idea?

for example, I want to label donuts, but need to erase holes.
i do not know yolo txt format how to delete this hole.
thanks.

**Comment by glenn-jocher** [comment]
@stphtan94117 yes, it is possible to annotate shapes with holes using YOLOv8. However, the YOLOv8 text format doesn't have a specific method for deleting holes in shapes. As a workaround, you could try creating a separate bounding box annotation for the hole within the larger bounding box of the donut. Another option would be to use a different annotation tool that supports more complex shapes, such as polygons or masks. Overall, it's important to choose an approach that works well with your segmentation data and meets the requirements of your specific use case. We recommend checking out the Ultralytics YOLOv8 documentation for additional resources and guidance.

**Comment by stphtan94117** [comment]
> @stphtan94117 yes, it is possible to annotate shapes with holes using YOLOv8. However, the YOLOv8 text format doesn't have a specific method for deleting holes in shapes. As a workaround, you could try creating a separate bounding box annotation for the hole within the larger bounding box of the donut. Another option would be to use a different annotation tool that supports more complex shapes, such as polygons or masks. Overall, it's important to choose an approach that works well with your segmentation data and meets the requirements of your specific use case. We recommend checking out the Ultralytics YOLOv8 documentation for additional resources and guidance.

I'm sorry, I don't quite understand what you mean.

Taking this image as an example, I want to label the roadmarks using segmentation.
![image](https://user-images.githubusercontent.com/110151053/230299761-fe953c77-b401-40a8-989b-cf4c105269a1.png)

So, do I need to create two labels? One for roadmarks and another for holes?

If I train the model and use the predict.py command with the "classes" option set to "roadmark", what will happen?

**Comment by JustasBart** [comment]
Hi @stphtan94117 unfortunately at the minute there doesn't seem to be any straight and non-hacky ways of doing what you're describing. As @glenn-jocher is saying this will very likely be supported in the near enough future but for now you'll have to pick a work-around.

All the best! :rocket:

**Comment by glenn-jocher** [comment]
@JustasBart in response to your question, currently there is no easy way to annotate shapes with holes in YOLOv8. As an alternative, one possibility is to create a separate annotation for the hole inside the larger bounding box of the donut or roadmark. Another option is to use a different annotation tool that supports shapes with holes, such as polygons or masks. However, YOLOv8 is being actively developed, and it is possible that support for shapes with holes will be added in the future. In the meantime, it's important to choose an approach that works best for your specific use case and data.

**Comment by stphtan94117** [comment]
> @JustasBart in response to your question, currently there is no easy way to annotate shapes with holes in YOLOv8. As an alternative, one possibility is to create a separate annotation for the hole inside the larger bounding box of the donut or roadmark. Another option is to use a different annotation tool that supports shapes with holes, such as polygons or masks. However, YOLOv8 is being actively developed, and it is possible that support for shapes with holes will be added in the future. In the meantime, it's important to choose an approach that works best for your specific use case and data.

I think the real issue here is the training files, which are in TXT format. 
Currently, it is possible to draw patterns with holes using the free software QGIS and export them as GeoJSON. 
GeoJSON is a format that belongs to JSON and can exclude the range of the holes. 
In the future, if we want to train these patterns, we may have to abandon the labels TXT file and use the GeoJSON method instead.

[map.txt](https://github.com/ultralytics/ultralytics/files/11188329/map.txt)
The following is a test file. Please rename the file extension to .json and upload it to the website https://geojson.tools/. You can then display the pattern.

**Comment by glenn-jocher** [comment]
@stphtan94117 yes @AyushExel is planning for future dataloaders that may read directly from other formats like COCO JSON, which may allow for multi-part object. Not sure if COCO JSON is hole capable but I'd imagine so.

**Comment by stphtan94117** [comment]
> @stphtan94117 yes @AyushExel is planning for future dataloaders that may read directly from other formats like COCO JSON, which may allow for multi-part object. Not sure if COCO JSON is hole capable but I'd imagine so.

It seems that Coco JSON cannot solve the issue of hole capability. The rules for erasing holes must still follow GeoJSON standards.

**Comment by glenn-jocher** [comment]
@stphtan94117 GeoJSON is a specialized format used by specialized (and expensive) software like ArcGIS, and is intended solely for geographical use cases, like mapping and satellite imagery. 

If we were to introduce another dataloader it would ideally be on a more general format that doesn't need specialized software to generate. I think there are definitely Segmentation examples in the COCO dataset of object with holes, i.e. a person with a hand on their hip and a gap between the arm and the body.

**Comment by glenn-jocher** [comment]
@stphtan94117 examples below of objects with holes and split in parts in COCO JSON annotations:

<img width="1022" alt="Screenshot 2023-04-10 at 12 05 53" src="https://user-images.githubusercontent.com/26833433/230881144-d9e08afb-4a0f-4787-b168-235eaf141387.png">
<img width="1082" alt="Screenshot 2023-04-10 at 12 05 12" src="https://user-images.githubusercontent.com/26833433/230881153-a1468dc6-e69d-4644-98a7-3af81623cf27.png">

**Comment by stphtan94117** [comment]
> examples below of objects with holes and split in parts in COCO JSON annotations:

Thank you for your response. It seems that COCO can support objects with holes and split in parts. I'm not sure which free software can achieve this type of annotation.

**Comment by glenn-jocher** [comment]
@stphtan94117 oh yeah that's a good question, I don't know the answer.

**Comment by ryouchinsa** [comment]
Using the script [general_json2yolo.py](https://github.com/ryouchinsa/Rectlabel-support/blob/master/general_json2yolo.py), you can convert the RLE mask with holes to the YOLO segmentation format.

The RLE mask is converted to a parent polygon and a child polygon using `cv2.findContours()`.
The parent polygon points are sorted in clockwise order. 
The child polygon points are sorted in counterclockwise order.
Detect the nearest point in the parent polygon and in the child polygon.
Connect those 2 points with narrow 2 lines.
So that the polygon with a hole is saved in the YOLO segmentation format.

```
def is_clockwise(contour):
    value = 0
    num = len(contour)
    for i, point in enumerate(contour):
        p1 = contour[i]
        if i < num - 1:
            p2 = contour[i + 1]
        else:
            p2 = contour[0]
        value += (p2[0][0] - p1[0][0]) * (p2[0][1] + p1[0][1]);
    return value < 0

def get_merge_point_idx(contour1, contour2):
    idx1 = 0
    idx2 = 0
    distance_min = -1
    for i, p1 in enumerate(contour1):
        for j, p2 in enumerate(contour2):
            distance = pow(p2[0][0] - p1[0][0], 2) + pow(p2[0][1] - p1[0][1], 2);
            if distance_min < 0:
                distance_min = distance
                idx1 = i
                idx2 = j
            elif distance < distance_min:
                distance_min = distance
                idx1 = i
                idx2 = j
    return idx1, idx2

def merge_contours(contour1, contour2, idx1, idx2):
    contour = []
    for i in list(range(0, idx1 + 1)):
        contour.append(contour1[i])
    for i in list(range(idx2, len(contour2))):
        contour.append(contour2[i])
    for i in list(range(0, idx2 + 1)):
        contour.append(contour2[i])
    for i in list(range(idx1, len(contour1))):
        contour.append(contour1[i])
    contour = np.array(contour)
    return contour

def merge_with_parent(contour_parent, contour):
    if not is_clockwise(contour_parent):
        contour_parent = contour_parent[::-1]
    if is_clockwise(contour):
        contour = contour[::-1]
    idx1, idx2 = get_merge_point_idx(contour_parent, contour)
    return merge_contours(contour_parent, contour, idx1, idx2)

def mask2polygon(image):
    contours, hierarchies = cv2.findContours(image, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_TC89_KCOS)
    contours_approx = []
    polygons = []
    for contour in contours:
        epsilon = 0.001 * cv2.arcLength(contour, True)
        contour_approx = cv2.approxPolyDP(contour, epsilon, True)
        contours_approx.append(contour_approx)

    contours_parent = []
    for i, contour in enumerate(contours_approx):
        parent_idx = hierarchies[0][i][3]
        if parent_idx < 0 and len(contour) >= 3:
            contours_parent.append(contour)
        else:
            contours_parent.append([])

    for i, contour in enumerate(contours_approx):
        parent_idx = hierarchies[0][i][3]
        if parent_idx >= 0 and len(contour) >= 3:
            contour_parent = contours_parent[parent_idx]
            if len(contour_parent) == 0:
                continue
            contours_parent[parent_idx] = merge_with_parent(contour_parent, contour)

    contours_parent_tmp = []
    for contour in contours_parent:
        if len(contour) == 0:
            continue
        contours_parent_tmp.append(contour)

    polygons = []
    for contour in contours_parent_tmp:
        polygon = contour.flatten().tolist()
        polygons.append(polygon)
    return polygons 

def rle2polygon(segmentation):
    if isinstance(segmentation["counts"], list):
        segmentation = mask.frPyObjects(segmentation, *segmentation["size"])
    m = mask.decode(segmentation) 
    m[m > 0] = 255
    polygons = mask2polygon(m)
    return polygons
```

The RLE mask.

![スクリーンショット 2023-11-22 1 57 52](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/df2dfad5-a13f-49c6-818a-8aba1d3ce83c)

The converted YOLO segmentation format.

![スクリーンショット 2023-11-22 2 11 14](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/cc34027a-075f-4b67-8de7-bd2dddddac59)

To run the script, put the COCO JSON file coco_train.json into `datasets/coco/annotations`.
Run the script. `python general_json2yolo.py  `
The converted YOLO txt files are saved in `new_dir/labels/coco_train`.

![スクリーンショット 2023-11-23 16 39 21](https://github.com/ultralytics/JSON2YOLO/assets/1954306/c3d98120-66f5-4cb8-b74d-a500f0bd811d)

Edit use_segments and use_keypoints in the script.

```
if __name__ == '__main__':
    source = 'COCO'

    if source == 'COCO':
        convert_coco_json('../datasets/coco/annotations',  # directory with *.json
                          use_segments=True,
                          use_keypoints=False,
                          cls91to80=False)
```

To convert the COCO bbox format to YOLO bbox format.
```
use_segments=False,
use_keypoints=False,
```

To convert the COCO segmentation format to YOLO segmentation format.
```
use_segments=True,
use_keypoints=False,
```

To convert the COCO keypoints format to YOLO keypoints format.
```
use_segments=False,
use_keypoints=True,
```

This script originates from Ultralytics [JSON2YOLO](https://github.com/ultralytics/JSON2YOLO) repository.
We hope this script would help your business.

**Comment by glenn-jocher** [comment]
@ryouchinsa thank you for sharing this information, it's insightful. Indeed, converting annotations from one format to another, like RLE mask to YOLO segmentation format, can be challenging, especially for complex shapes with holes.

The approach you've detailed using `cv2.findContours` and careful management of polygon winding orders to distinguish between parent and child polygons is a creative solution. It ensures that the converted YOLO segmentation representation correctly reflects the original object, including any interior holes.

It's great to see the community developing and sharing tools to expand the capabilities of YOLOv8 and other YOLO versions. Your script could be very useful to others who might be facing similar challenges with their segmentation data.

As an additional note for others reading this thread: The script you've referenced performs a specific conversion process. Users who wish to apply it will need familiarity with Python and OpenCV, and they should modify the script according to their data format and directory structure.

This sharing of resources and collaboration is an excellent example of how our community innovates and helps make these models more accessible and capable across different types of data and use cases. Thank you for your contribution! 🤝
