### ISSUE TITLE
Extensibility of ultralytics framework

### ISSUE THREAD

**Issue by zhiqwang** [ultralytics/ultralytics#187]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

> One key feature of YOLOv8 is its extensibility. It is designed as a framework that supports all previous versions of YOLO, making it easy to switch between different versions and compare their performance. This makes YOLOv8 an ideal choice for users who want to take advantage of the latest YOLO technology while still being able to use their existing YOLO models.

Is there more detail on the scope of expandability here, such as support for yolov3, yolov6, yolov7 or paddleyolo series? And do you plan to do compatibility support for the previous series of yolov5 versions (version 1.0 to 6.0)?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@zhiqwang yes. All both yolo and non-yolo models for any type of task.

**Comment by p0wned17** [comment]
and which non-yolo ones can be used?

**Comment by AyushExel** [comment]
@p0wned17 depends on how you customize it..See the tutorial here - https://docs.ultralytics.com/engine/
We'll add more soon

**Comment by AyushExel** [comment]
Closing this. Please reopen if you have any other questions
