### ISSUE TITLE
Pose Estimation inference 

### ISSUE THREAD

**Issue by sivaji123256** [ultralytics/ultralytics#1870]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi @glenn-jocher @Laughing-q @AyushExel ,Thanks for great work and it's nice to see the expansion of tasks of Yolov8. I would like to test it on animal key point detection. But, will the pretrained pose estimation models works only for humans ?If yes, is there any custom training process available?
Thanks in advance.

**Comment by Laughing-q** [comment]
@sivaji123256 The modes works only for human pose. and yes you can train your custom model by:
```bash
yolo pose train ...
```
just prepare your dataset just like our [coco8-pose](https://ultralytics.com/assets/coco8-pose.zip).
```bash
cls cx cy w h x1 x2 ... xn yn
```
