### ISSUE TITLE
Saving Segmentation masks 

### ISSUE THREAD

**Issue by sivaji123256** [ultralytics/ultralytics#1872]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi @glenn-jocher @Laughing-q , Can I save the segmentation mask of each object  (with the rest of the objects as background in the frame)? I am attaching the required binary mask where the rest of the objects were background. Frame has other objects as well. But, they should be background. 
![235](https://user-images.githubusercontent.com/57151760/230367733-257740b5-335f-4997-896d-5e057355e9a2.jpg)

**Comment by sivaji123256** [comment]
Hi @glenn-jocher @Laughing-q @AyushExel  I was trying to have the similar function as below to save the each object mask. Instead of cropped , the mask should be as same as image size and it should be black as above.
def save_one_box(xyxy, im, file=Path('im.jpg'), gain=1.02, pad=10, square=False, BGR=False, save=True)

**Comment by glenn-jocher** [comment]
Hello @goyalmuskan, 
In Ultralytics YOLOv8, you can use the `draw_mask()` function to draw segmentation masks for each detected object. To save these masks as binary images, you can use the `cv2.imwrite()` function with a black background. This should result in a binary image of the same size as the original input image, with the detected object in white and the rest of the image in black. You can modify the `draw_mask()` function to achieve this. I hope this helps! If you need more information, feel free to refer to the Ultralytics YOLOv8 documentation at https://docs.ultralytics.com/.

**Comment by sivaji123256** [comment]
Hi @glenn-jocher ,Thanks for your quick response. Do we have the same feature in yolov5 as well?

**Comment by glenn-jocher** [comment]
@sivaji123256 as the author and maintainer of Ultralytics YOLOv8, I am not able to comment on the features available in YOLOv5. However, I can tell you that Ultralytics YOLOv8 is based on YOLOv5 and includes additional features and improvements. If you are looking for specific information on YOLOv5, I suggest referring to the YOLOv5 documentation or contacting the YOLOv5 community for further assistance.

**Comment by glenn-jocher** [comment]
@davidbernat hello there,

1. The Ultralytics YOLOv8 model, similar to many other segmentation models, does not explicitly enforce contiguous segmentations. However, it's worth noting that the model is generally optimized to output effectively contiguous masks due to the nature of most training datasets and object categorization. 

2. As for file formats suitable for boolean data representation, typically binary image data is represented in common formats like PNG or TIFF, both of which support binary color modes. This makes them suitable for representing boolean data efficiently. 

3. Regarding compression of segmentation masks in YOLOv8 or any other CV platform, there isn't a built-in feature specifically designed for this. However, this approach sounds interesting and could be a valuable contribution to the repo.

If you decide to implement this functionality, your contribution would be most welcome. We appreciate innovations from community members like yourself which can help improve the YOLOv8 feature set for everyone. Thank you for considering contributing back to the community!

**Comment by mscussiatto** [comment]
Hi @glenn-jocher i am able to save the crops and this is already helping my to pass that to SAM. However, is there a way export the segmented RGB masks? This would reduce a lot the noise in further segmentation tasks.

**Comment by glenn-jocher** [comment]
@mscussiatto hello and thank you for your question. 

In YOLOv8, generating RGB masks from the segmented objects is possible though it's not available as a separate export feature. Basically, these masks are usually derived during the detection process: the algorithm creates bounding boxes for detected objects, which can be used to segment the original image. The segmented areas technically form the "masks" for each detected object.

Unfortunately, directly exporting these masks to RGB format is not built into the current design of YOLOv8. However, you could adapt the post-processing code to achieve this. The key steps would be capturing the bounding box coordinates during the detection phase, and then using those coordinates to separate out each object from the original image, creating individual masks for further processing.

Adding an RGB mask export feature to YOLOv8 is a good suggestion and could benefit many users. You are welcome to open a feature request for this in the repo's issues. 

Hope this explanation helps your understanding! If you have further questions, feel free to bring them up.

**Comment by davidbernat** [comment]
It is a few lines of code to map the binary masks into the image to extra the RGB image, as I said I offered to do in an earlier post. I do not see any reason for @glenn-jocher to make such a big deal about it. (His YOLO development is bound my compliance to other mega-industry companies in AI and therefore unable to edit and update YOLO freely, unlike my offers.) I will continue to show myself the doors. One of these days @glenn-jocher is going to rejoin my Air Force division. Right?? :)

**Comment by glenn-jocher** [comment]
@davidbernat hi there,

Thank you for your insights here. You're right that mapping binary masks to an image to extract the RGB image would involve adding a few lines of code. It's a useful suggestion and we always appreciate active contributions from our community. 

As with any open source project, we balance new features and changes with the goal of maintaining stable, reliable software for all users. It's not about any restrictions but more about ensuring the quality and practicality of the repository for all our users across numerous contexts.

Transition discussions aside, we appreciate your active participation and any contributions you could make to the project would be very much welcomed. Looking forward to any future collaborations!

Happy coding!

**Comment by sep-ML** [comment]
I faced this problem recently and have a fast solution for those people who face it and are in hurry :
just get result like this in python:
  results = model.predict(source=...)
then in results get them like this:
  for i in range(results.__len__()):
    if results[i].masks is None:
      continue
    np.save('/home/results/'+str(i+1),results[i].masks.data.cpu().numpy())
result.py documentation is not complete so this thing can help newbies like my self. Hope it would be usefull.

**Comment by glenn-jocher** [comment]
@sep-ML thank you for sharing your solution here! It's always great to see users of our community sharing practical tips and solutions. Your example, which involves saving the model's prediction results as numpy arrays, might indeed prove useful for other users running into the same situation. We always strive to keep the documentation as comprehensive as possible, but sometimes, user-contributed solutions like these can offer valuable additional insights. Thanks for your contriubtion!

**Comment by mscussiatto** [comment]
@davidbernat and @sep-ML thanks for the replies. I am trying to get the RGB mask from the crop results. I manage to do it on a very manual way. Would you be able to help me out with this with a more sofisticated approach?

https://github.com/ultralytics/ultralytics/assets/108452459/60f534fa-a7fa-4c26-bb8f-411eb5b04c9f

![crop_seg](https://github.com/ultralytics/ultralytics/assets/108452459/da03870a-5a62-456b-9dee-1a40aa4c1a9d)

![vlc-record-2023-10-27-15h21m18s-timelapse_final2](https://github.com/ultralytics/ultralytics/assets/108452459/15be3b35-375a-4ea1-a292-67101477576a)

**Comment by sep-ML** [comment]
> @davidbernat and @sep-ML thanks for the replies. I am trying to get the RGB mask from the crop results. I manage to do it on a very manual way. Would you be able to help me out with this with a more sofisticated approach? @glenn-jocher thoughts?
> 
>  aaaa.mp4 
> ![vlc-record-2023-10-27-15h21m18s-timelapse_final2](https://user-images.githubusercontent.com/108452459/278739298-15be3b35-375a-4ea1-a292-67101477576a.jpg)
> 
> ![crop_seg](https://user-images.githubusercontent.com/108452459/278739288-da03870a-5a62-456b-9dee-1a40aa4c1a9d.png)

Hi, What do you mean by manually ?
you can get the mask perform a bit wise &(AND) then get the image out I call this manually.
 what do you mean manually?
and what do you want to do exactly?

**Comment by glenn-jocher** [comment]
@mscussiatto, I understand that you are trying to generate the RGB mask from the cropped results and you've managed to do it using manual processes. 

If you aim to automate the process or make it less manual, one option could be to create a separate function that takes the crop results and generates the RGB mask automatically. This way, once you obtain the crop results, you can directly pass them into this function to generate the RGB masks.

Per your question about a more sophisticated approach; you might consider integrating this function into the main processing pipeline. This could potentially facilitate the RGB mask generation and reduce manual interventions.

If "manual" refers to generating each RGB mask individually, another option would be to adapt the process to handle multiple crop results at once, possibly using batch processing.

If you could elaborate a little more on the manual steps you took and what exactly is the end result you're looking to achieve, it'd be easier for the community to provide a more specific solution or improve upon the existing process.

**Comment by mscussiatto** [comment]
Hi thanks for the prompt replies. 

This is a drive folder with the model for a MRE:

https://drive.google.com/drive/folders/1EhrewOyr3sMN6o084WCcAU9KrFc0mO5G?usp=sharing

I have tried to organize the ideas in this repo: https://github.com/mscussiatto/yolo-grow 

I managed to get the individual binary masks saved but that's all.

@glenn-jocher that is exatcly what I am trying to achieve "takes the crop results and generates the RGB mask automatically. This way, once you obtain the crop results, you can directly pass them into this function to generate the RGB masks." But I am struggling even to start on that...

Thanks again for the help.

**Comment by glenn-jocher** [comment]
Hi @mscussiatto,

Thanks for sharing more details about your project. I understand you're trying to streamline the process of generating RGB masks from the result of YOLOv8’s object detection.

To achieve this, an approach would be to modify YOLOv8's output to not only include the bounding boxes of detected objects, but also return an image mask of each object. With this, you essentially segment the original image to get a mask for each detected object. This mask can then be used to generate RGB masks.

In order to undertake this modification, you'll need to delve into the post-processing steps of YOLOv8's detections. That's where the bounding boxes (object detections) are being generated. You would modify that step to create additional image mask output for each bounding box.

Remember, the goal is to generate the mask as part of each detection, so you want this to occur in the post-processing/object detection stage within the model's computation.

Starting on this might be a bit challenging. You might want to consider breaking down the task into smaller, manageable parts. For instance, first focus on understanding how the bounding box coordinates are extracted from the output, then work towards using those coordinates to segment the image and create the mask.

I hope this advice provides you a good starting point. Feel free to ask if you have any questions or need further clarifications. Good luck with your project!

**Comment by mscussiatto** [comment]
Hi @glenn-jocher thank you for your feedback. 

I have managed to work something out with this https://github.com/mscussiatto/yolo-grow/blob/main/yolov8seg_grow_RGB_mask.py

However, I would like a smoother results on the RGB mask. The only way is to train yolo on a higher resolution is that correct? This way the segmentation mask will have more pixels...

Inference results

![2023-10-27_05-54-40](https://github.com/ultralytics/ultralytics/assets/108452459/3e547ade-871c-4a40-9c8d-61e280f450d2)

save_crop result

![2023-10-27_05-54-4013](https://github.com/ultralytics/ultralytics/assets/108452459/b6146e1e-8562-4e7d-8676-f0f4ce86c985)

RGB mask

![contour_0_0_size_142079](https://github.com/ultralytics/ultralytics/assets/108452459/9a7ebcb1-cdbd-48f8-aa3a-34f46edeec3a)

![image_with_contours_0 (2)](https://github.com/ultralytics/ultralytics/assets/108452459/664a23c8-34f2-4f68-a90d-5a83fc53ddf3)

**Comment by Jahangeer69** [comment]
Hi @mscussiatto,
 
Can you please share how you managed get the RGB mask of the cabbage. I followed the code you linked earlier but it just draws contours around the segmented object. How do I crop out just the object.

Thank you
