### ISSUE TITLE
`Pose Estimation` for multi-classes

### ISSUE THREAD

**Issue by uyolo1314** [ultralytics/ultralytics#1874]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Currently, `Pose Estimation` only supports one class. https://github.com/ultralytics/ultralytics/blob/1cb92d7f42a3725a0114dd60df12c059c495c5eb/ultralytics/yolo/v8/pose/val.py#L77

**It's wonderful that `Pose Estimation` only supports multi-classes.**

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@xlong67, thank you for your feedback! We're glad that you find YOLOv8 useful. For `Pose Estimation`, we currently only support multi-class support.
If you have any more questions or suggestions, please feel free to ask, and we'll do our best to help.  If you'd like to contribute a PR, please make sure your submission follows our PR guidelines and license agreement.

**Comment by glenn-jocher** [comment]
@fanyigao thank you for your kind words! For a scenario with five classes, each having four keypoints, once you've set your dataset correctly in the `coco128-pose.yaml`, you'll also need to adjust the model's configuration for the number of classes and keypoint attributes. Make sure your annotations are correctly formatted aligning with the model's expectations for multi-class pose estimation. For any modifications in the code, look into areas handling the parsing of keypoints and the model's head definition designed for keypoint detection. Keep the annotations consistent with the model's output structure. Good luck! 🚀

**Comment by fanyigao** [comment]
> 谢谢你的客气话！对于具有五个类的方案，每个类有四个关键点，在 中正确设置数据集后，还需要针对类数和关键点属性调整模型的配置。确保您的注释格式正确，符合模型对多类姿态估计的期望。对于代码中的任何修改，请查看处理关键点解析的区域以及为关键点检测而设计的模型头部定义。使注释与模型的输出结构保持一致。祝你好运！🚀`coco128-pose.yaml`

Thank you!

**Comment by glenn-jocher** [comment]
@fanyigao for a five-class and four-keypoints setup, after updating your dataset in `coco128-pose.yaml`, adjust the model configuration for class count and keypoint attributes. Ensure that your annotations match the required format for multi-class keypoint detection. Changes in the code should focus on keypoint parsing and the model's keypoint head configuration. Keep annotations and model outputs consistent. Good luck! 🚀

**Comment by fanyigao** [comment]
> 对于 5 类和 4 个关键点设置，在 中更新数据集后，调整类计数和关键点属性的模型配置。确保您的批注与多类关键点检测所需的格式匹配。代码中的更改应侧重于关键点解析和模型的关键点头配置。保持注释和模型输出的一致性。祝你好运！🚀`coco128-pose.yaml`

Do you have some annotation tools recommended? labelme and labelimg are not user-friendly I think

**Comment by fanyigao** [comment]
> 对于在多类设置中注释关键点，工具的选择取决于您的具体要求。虽然我们不正式推荐一种工具而不是另一种工具，但请考虑探索支持多个类的关键点注释的工具，并确保它们可以导出为与 YOLOv8 兼容的格式。许多用户发现带有 GUI 的工具有助于简化视觉注释。祝你的项目好运！🌟
thank you! I'm using labelme to annotate my images, and I found a interesting thing,that is the shape of the dots must be a closed figure, which means body cannnot be annotated with labelme, although it seems normal in my dataset.

**Comment by glenn-jocher** [comment]
@fanyigao When annotating keypoints with labelme, ensure that your chosen shapes align with YOLOv8 requirements. If labelme's constraints limit annotation options for specific body parts, considering alternative tools or customizing labelme for your needs might be necessary. Coordination between the annotation format and the model's input is crucial for successful training. 🎯
