### ISSUE TITLE
Setting `data` parameter don't allow to ignore `datasets_dir` property in settings.yaml

### ISSUE THREAD

**Issue by mrekin** [ultralytics/ultralytics#1879]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I found question about such trouble (#1809 ) but not bug.

I have a settings.yaml file in user home folder with
`datasets_dir: /home/vardas/yolo`
File auto created by first run yolo train in same directory

I create directory
`/home/vardas/cleartest`
and place into dataset (downloaded from roboflow)
```
vardas@yoloTrain:~/cleartest$ ls 
README.dataset.txt  README.roboflow.txt  data.yaml  test  train  valid
```
Start train with command in directory `cleartest`
`vardas@yoloTrain:~/cleartest$  yolo train data=data.yaml model=yolov8n.pt epochs=1 imgsz=640 batch=4`

and yolo loads dataset from directory configured in settings file
```
optimizer: SGD(lr=0.01) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias
train: Scanning /home/vardas/yolo/train/labels.cache... 538 images, 0 backgrounds, 0 corrupt: 100%|██████████| 538/538 [00:00<?, ?it/s]
val: Scanning /home/vardas/yolo/valid/labels.cache... 153 images, 0 backgrounds, 0 corrupt: 100%|██████████| 153/153 [00:00<?, ?it/s]
```

Yolo searches provided file data.yaml in `datasets_dir`.

### Environment

- ultralytics-8.0.68
- Ubuntu 22.04
- Python 3.10.7

Train with cpu or gpu -doesn't matter

### Minimal Reproducible Example

```
yolo train data=data.yaml model=yolov8n.pt epochs=1 imgsz=640 batch=4
```

### Additional

-

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mrekin thank you for reaching out and providing detailed information about your issue with YOLOv8. From your description, it seems that YOLOv8 is reading the `settings.yaml` file from your home folder and searching for the `data.yaml` file in the `datasets_dir` folder specified in the `settings.yaml` file. This behavior is expected as per YOLOv8's configuration. However, if you want YOLOv8 to use a different dataset directory, you can modify the `datasets_dir` parameter in the `settings.yaml` file accordingly. Additionally, if you encounter any other issues, please feel free to reach out to us for further assistance or refer to the documentation at `https://docs.ultralytics.com` for more information.

**Comment by mrekin** [comment]
@glenn-jocher Hi Glenn!
Can you  explain how I need organize datasets storage and right `data` value to use it?
I tried to put my data set to `datasets_dir` subdirectory, like 
`/home/vardas/yolo/dataset1`
and run with data  property
`dataset1/data.yaml` or `/dataset1/data.yaml`
with no success

May by I can set `datasets_dir` to empty value and provide full path every run? I think there will be problems with relative paths for train/ valid/  directories...

Current logic with global path without way to redefine it for project looks not very usefull.

**Comment by mrekin** [comment]
Don't reply right now :)
Let me read, understand and accept  #1881  ;)
I'll reject a bug or ask new question little bit later.

**Comment by glenn-jocher** [comment]
@mrekin sure, no problem! Take your time to read and understand the documentation in issue #1881. If you have any questions or concerns, please feel free to reach out to us for further assistance. Generally, to utilize datasets in YOLOv8, you would need to organize your data in a specific YAML format and follow the instructions described in the documentation. In addition, you should modify the `datasets_dir` parameter in the `settings.yaml` file to correspond to the directory containing your dataset. If you encounter any challenges or issues, you can always refer to the documentation or reach out to us for further assistance.

**Comment by mrekin** [comment]
I find (by yolo code investigating, not in docs) that simplest way to train with roboflow dataset is to download zip with dataset and pass in in `data` parameter (`data=roboflow.zip`)
Yolo will unzip in in dataset dir and use for training. And it will done every start and user may forgot to rename zip and get strange results (mixed datasets (not sure) but latest data.yaml with latest classes)

But roboflow for yolov8 provide commands with unzip to current dir and this is not very clear :)

The second way I found is addind path variable  in data,yaml file with absolute path to directory with dataset
`path: /home/vardas/cleartest`
This also works and much better for my case.
Anyway, I don't fount this in docs or code examples.

Maybe need to have possibility to provide path by yolo params?

I find usefull way for me, but still  think that a parameter is needed to specify a custom path to the dataset.
Fill free to reject a bug or change it to feature requst :)

Thanks for your support.

**Comment by hmoghimifam** [comment]
I find this annoying too to manually set the `path: absolute current directory path` especially when moving files between different computers. Previously in yolov5, you could provide the relative path as `./` which meant the same `yaml` file worked between multiple computers without a need to change. I think this can be a positive change if the default is set to current work directory instead.

**Comment by glenn-jocher** [comment]
@hmoghimifam thank you for bringing this to our attention. We understand that the current behavior of YOLOv8 can be frustrating, especially when moving files between different computers. While we do not currently provide the capability to define a custom path via YOLOv8 parameters, we appreciate your feedback and suggestion. We will certainly consider this feature request in our future updates. Additionally, we are constantly looking for ways to improve and simplify our product. Thank you for your continued support and contributions to YOLOv8.
