### ISSUE TITLE
Precision, recall and F1 curve generation

### ISSUE THREAD

**Issue by muttahirul** [ultralytics/ultralytics#1880]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello @glenn-jocher, after training my custom dataset, I only get the image of plotted curve of precision, recall and F1. 
If I would like to generate the curve all by myself, is there any raw data that are saved after training I can use? 
I can plot the result.png file using result.csv file. I would like to do the same for other accuracy metric. Could you please help in this regard?

**Comment by glenn-jocher** [comment]
Hello @muttahirul, glad to see your interest in YOLOv8 🚀! After training, YOLOv8 saves the training metrics data in the TensorBoard format. You can easily fetch the raw data by loading that data in TensorBoard or use a Python library like TensorBoard into Pandas DataFrame and plot the metrics as you like. You can also find the `results.txt` file in the training folder that contains the loss and accuracy data for each epoch. Please note that if you are running YOLOv8 on a cloud platform, you may need to download the data to your local machine for plotting. Hope this helps!

**Comment by muttahirul** [comment]
Thank you for your quick response. Actually I was talking about generating the plot given in the pictures below. I could not understand how could I generate such plot with result.txt file? 
![image](https://user-images.githubusercontent.com/121252824/230544956-5fd94f7d-9fa6-4409-a8b8-e2f8bb31a67b.png)
![image](https://user-images.githubusercontent.com/121252824/230545017-0803c6cc-5ab8-49f6-9932-7a64415a1719.png)
![image](https://user-images.githubusercontent.com/121252824/230545057-863ab982-18a0-4be5-b6d0-d95846041e88.png)
![image](https://user-images.githubusercontent.com/121252824/230545111-b6c67d21-56bf-4c5c-9c59-cb2cf3278a8c.png)

**Comment by glenn-jocher** [comment]
@muttahirul, to generate the curves like the ones shown in the images you provided, you can use metrics from the `result.txt` file that gets generated during training. The `result.txt` file contains training metrics like loss, precision, recall, F1, and mAP. You can plot these metrics using a plot library like Matplotlib or Seaborn after parsing the data from the `result.txt` file. Hope this helps!

**Comment by muttahirul** [comment]
Sorry to disturb you again. I am new to this field so may be I am little bit confused.

Did you mean the snapshot of csv file I attached below when you referred to the result.txt file? But in this file there is no class wise data, only the precision, recall etc. of every epoch. How could I parse classwise data and plot them? 
![image](https://user-images.githubusercontent.com/121252824/230574201-0604deee-c8f2-4f2f-9860-de6106258a8e.png)

**Comment by Coolzyh** [comment]
I have the same question. Does anyone know how to fetch the raw data of Precision and Recall during validation?

**Comment by glenn-jocher** [comment]
@Coolzyh of course, I'd be happy to help! 

After training, YOLOv8 saves the training metrics data in the TensorBoard format. You can use the `tensorboard --logdir=<path>` command to launch TensorBoard and then view the training/validation metrics. Alternatively, you can load the data in TensorBoard into Pandas DataFrame and plot the metrics as you like. You can also find the `result.txt` file in the training folder that contains the loss and accuracy data for each epoch. You can parse the Precision and Recall data from the `result.txt` file. 

However, please be advised that as of now YOLOv8 does not provide class-wise Precision and Recall data during validation. So you cannot plot class-wise Precision and Recall curves with YOLOv8. Hopefully this clarifies things for you. Let me know if you have any other questions!
