### ISSUE TITLE
Can't change the default dir where YOLOV8 downloads example datasets

### ISSUE THREAD

**Issue by nikolaydyankov** [ultralytics/ultralytics#1881]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm running the example python script:

```
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.yaml')  # build a new model from YAML
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)
model = YOLO('yolov8n.yaml').load('yolov8n.pt')  # build from YAML and transfer weights

# Train the model
model.train(data='coco128.yaml', epochs=100, imgsz=640)
```

It runs without errors, but it creates the `datasets` dir two levels up?

```
datasets/
dir1/
    dir2/
        train.py
```

```
cd dir1/dir2
python3 train.py
```

Am I missing some config to specify the datasets dir? I can't find anything in the docs, or in other issues.

**Comment by glenn-jocher** [comment]
@nikolaydyankov datasets dir is defined in settings. You can see settings with `yolo settings`. If you redefine datasets_dir in settings to be relative or absolute then YOLO will download and look for datasets there.

**Comment by nikolaydyankov** [comment]
@glenn-jocher Thank you, I can see the dir there. How do I change it?

**Comment by glenn-jocher** [comment]
You can open the settings YAML file in any editor and modify the directory.

**Comment by nikolaydyankov** [comment]
I found this issue: https://github.com/ultralytics/ultralytics/issues/1809

You say that when you specify `data` argument to `model.train()` it's supposed to override the global datasets_dir from the settings.yaml file. However it's not behaving like this. Is it possibly a bug?

**Comment by glenn-jocher** [comment]
@nikolaydyankov I'm not sure what you mean by override. datasets directory is where datasets go.

I also don't understand what you mean by you can't find your settings file anywhere, if you run `yolo settings` as I indicated above it displays the file location.

**Comment by nikolaydyankov** [comment]
> I also don't understand what you mean by you can't find your settings file anywhere, if you run yolo settings as I indicated above it displays the file location.

Ignore that, I can't read. I found the file.

I figured the datasets and data.yaml locations, but the final thing that I want to change on a per-project basis is where to put the "runs" folder. Currently it's specified in the global settings.yaml, but I don't see a way to change that when calling model.train().

**Comment by glenn-jocher** [comment]
@nikolaydyankov oh, runs is a default directory that is used if you don't define your own PROJECT/NAME to store a run:

```
yolo train project=PROJECT name=NAME
```

with save results to the PROJECT/NAME dir.

**Comment by nikolaydyankov** [comment]
Thank you!

**Comment by glenn-jocher** [comment]
@nikolaydyankov in response to your question about directing "runs" folder in Ultralytics YOLOv8, you can define your own PROJECT/NAME when you train your model, and it will store the run in the specified directory. "runs" is the default directory if you haven't defined a PROJECT/NAME folder.
