### ISSUE TITLE
Will wait after each training round

### ISSUE THREAD

**Issue by songjiahao-wq** [ultralytics/ultralytics#1883]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

What is the problem that I have to wait for a period of time to train the next round after each training of an epoch? I'm confused.

**Comment by songjiahao-wq** [comment]
![image](https://user-images.githubusercontent.com/75210061/230548336-2d58482a-4ca2-428e-8d16-7ef76f6919f1.png)
yi
Always gets stuck before each round of training and has to wait longer

**Comment by Lollykonkon** [comment]
Have similar issue. 
After first epoch of training terminal turns itself off (same with VSCode, not only terminal but whole app). 

![Снимок экрана от 2023-04-07 15-15-28](https://user-images.githubusercontent.com/52105849/230552671-030c1b31-348d-4bab-94ff-10a66ae485f2.png)

It happens regardless of version: I tried both 8.0.20 and 8.0.61

**Comment by glenn-jocher** [comment]
@EmilKas, thank you for reaching out. 

Without more information it is difficult to provide a concrete answer. However, it is possible that your system resources are running out of memory during the training process or that there is some other issue related to your system or environment. We recommend reviewing your hardware capabilities and monitoring your system resources during training. I also suggest visiting the YOLOv8 Docs (https://docs.ultralytics.com/) for more information on best practices for training and troubleshooting.

**Comment by songjiahao-wq** [comment]
After observing the training process, I found that on Windows platform, the normal training speed can be maintained only when workers are lowered to 0 or 1. But this problem is not in YOLOv5

**Comment by glenn-jocher** [comment]
@songjiahao-wq, thank you for this observation. YOLOv8 and YOLOv5 are separate projects with different design choices and configurations. It is possible that the differences you observed are due to different defaults or settings used in each project. We recommend configuring your training environment based on the specific needs of your dataset, hardware, and available system resources, and consulting the respective project's documentation for guidance on optimal configurations. Additionally, it's important to note that while YOLOv8 and YOLOv5 share some similarities, they are separate projects and may exhibit different behaviors.

**Comment by CaptainMai** [comment]
I have a similar situation.  I use windows.  After downloading the latest yolov8 code unchanged and executing ultralytics\yolo\v8\detect\train.py, there was a long wait for the reverification set and the next turn.  Therefore, I downloaded the yolov5 code and found no similar problem.  Only when I modify workers to 1 can normal training problems be maintained

**Comment by CaptainMai** [comment]
I have a similar situation. I use windows and 3090 . After downloading the latest yolov8 code unchanged and executing ultralytics\yolo\v8\detect\train.py, there was a long wait for the reverification set and the next turn. Therefore, I downloaded the yolov5 code and found no similar problem. Only when I modify workers to 1 can normal training problems be maintained

**Comment by glenn-jocher** [comment]
@songjiahao-wq @Lollykonkon @CaptainMai I looked into this some more. 

What you're seeing is normal for PyTorch dataloaders on Windows. For YOLOv5 I created a dataloader wrapper class called InfiniteDataloader that attempts to recycle workers each epoch, speeding up the process and hiding the slow defaylt PyTorch dataloader behavior, apparently particularly in Windows.

The InfiniteDataloader is only applied when dataloader properties do not require modification during training. Setting close_mosaic=10, as is the default, changes properties in the dataloader, so the YOLOv8 code falls back to the default PyTorch dataloader, which you feel is slow, but in reality is simply the default PyTorch dataloader speed.

You can set close_mosaic=0 to disable this feature, which will allow YOLOv8 to use the InfiniteDataloader. This will result in slightly lower final mAP (like YOLOv5, which lacks this feature) but should improve training speed (also like YOLOv5).

**Comment by glenn-jocher** [comment]
See https://github.com/ultralytics/ultralytics/blob/c38b17a0d80958788d7fbf6b5159b756b7d56e07/ultralytics/yolo/data/build.py#L23-L105 for details

**Comment by glenn-jocher** [comment]
@songjiahao-wq @Lollykonkon @CaptainMai I've tried an experiment in https://github.com/ultralytics/ultralytics/pull/1907/commits/e00dab0f93b4988cb313aa159441d4b07f0339ea which will persist workers for default PyTorch dataloader usage. This may help as well. This will be released in 8.0.71 soon. 

Please try this out and let me know if this improves speed on Windows, and also try the close_mosaic=0 solution.

**Comment by songjiahao-wq** [comment]
@glenn-jocher Thank you very much! This problem is solved

**Comment by glenn-jocher** [comment]
@songjiahao-wq you're welcome! I'm glad that the solution worked out for you. If you have any further questions, please don't hesitate to ask. Remember that YOLOv8 is a separate project with different design choices and configurations than YOLOv5. It is important to configure your training environment based on the specific needs of your dataset, hardware, and available system resources, and to consult the respective project's documentation for guidance on optimal configurations.

**Comment by glenn-jocher** [comment]
@songjiahao-wq @Lollykonkon @CaptainMai I've set close_mosaic=0 as the default starting in 8.0.72. I think this will benefit the most users, as even on Linux for small datasets the InfiniteDataloader is much faster. 

Note this means your models may train to slightly lower mAP, but this difference is quite small, i.e. mayb 0.0-0.5% mAP, and you can always opt-in to close_mosaic by passing any non-zero value for it like the previous default of `close_mosaic=10` at the expense of slower training.
