### ISSUE TITLE
save_crop - add a delimiter

### ISSUE THREAD

**Issue by erwanlenagard** [ultralytics/ultralytics#1885]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

When you save multiple crops from the same image, you add an index at the end of the file name. Would id be possible to add a delimiter to easily split the original filename from the crop index ? 

![image](https://user-images.githubusercontent.com/6311190/230560006-77d4a939-44e4-4a86-8baf-7a4dae49d2eb.png)

### Minimal Reproducible Example

model(source=url, 
                save=True,
                save_txt=True, 
                save_conf=True, 
                save_crop=True,
                show_labels=True, 
                show_conf=True,  
                line_thickness=1, 
                conf=0.5,
                name="name",
                stream=True
                )

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@erwanlenagard thank you for reaching out and bringing this to our attention. This is a great suggestion, and we understand how this can improve the user experience. Adding a delimiter to the file name for easier file management is a great idea and we will consider this feature in future updates. In the meantime, if you have any additional questions or concerns, please don't hesitate to ask, or refer to our documentation at https://docs.ultralytics.com for more information.

**Comment by glenn-jocher** [comment]
@erwanlenagard I've removed the bug label as this is not a bug. No error is produced and output is as expected.
