### ISSUE TITLE
Result plotting returns ndarray despite the parameter pil

### ISSUE THREAD

**Issue by mrekin** [ultralytics/ultralytics#1886]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

HI!

Triyng to plot retection results to image.
Method `.plot()` for ultralytics/yolo/engine/results.py returns ndarray if argument pil=True or not.
Expected that method will return PIL image in case `pil=True`.

Looks like there are bug in
`return np.asarray(annotator.im) if annotator.pil else annotator.im`
and need to change
`return np.asarray(annotator.im) if not annotator.pil else annotator.im`

Then pil=False, annotator.im is an ndarray too, then pil=True, annotator.im is PIL image, but not returns.

### Environment

- yolo 8.0.68
- Ubuntu 22.04
- Python 3.10.4

### Minimal Reproducible Example

```
from ultralytics import YOLO

model = YOLO('yolov8n.pt')
results = model('images/', line_thickness =1)

for result in results:
    res =result.plot(pil=True)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mrekin hello, thank you for bringing this to our attention. We are sorry for the inconvenience caused. Based on your description, it appears that there might be a bug in the `.plot()` method implementation for YOLOv8. We will look into this further and make the necessary changes if required. In the meantime, if you need further assistance, you can refer to our documentation at https://docs.ultralytics.com for more information. Thank you for using YOLOv8.

**Comment by AyushExel** [comment]
@glenn-jocher @CNH5 it looks like this line was introduced in this PR by you guys https://github.com/ultralytics/ultralytics/pull/1316
Can you please verify if the suggested approach the user here will resolve the problem? Thanks!

**Comment by glenn-jocher** [comment]
@mrekin @AyushExel there is no bug. I've removed the label. 

.plot() will always return a numpy array regardless of the plotting method (cv2 or PIL). PIL simply plots annotations using the PIL library.

![abc](https://user-images.githubusercontent.com/26833433/230634917-e429529b-810f-4902-853a-3795b99d21ff.jpg)

**Comment by mrekin** [comment]
@glenn-jocher 
Docs says
<html>
<body>


pil | bool | Whether to return the image as a PIL Image. | False
-- | -- | -- | --



</body>
</html>

and

<html>
<body>
<p style="box-sizing: inherit; color: rgba(0, 0, 0, 0.87); font-family: Roboto, -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif; font-size: 17.6px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: inherit;">Returns:</strong></p><div class="md-typeset__scrollwrap" style="box-sizing: inherit; margin: 1em -0.8rem; overflow-x: auto; touch-action: auto; color: rgba(0, 0, 0, 0.87); font-family: Roboto, -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif; font-size: 17.6px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="md-typeset__table" style="box-sizing: inherit; display: table !important; margin-bottom: 0.5em; padding: 0px 0.8rem; line-height: 1; width: 792.031px;">

Type | Description
-- | --
None) or (PIL.Image | If pil is True, a PIL Image is returned. Otherwise, nothing is returned.

</div></div>
</body>
</html>

May be this is docs bug then?

**Comment by glenn-jocher** [comment]
@mrekin ah, yes this is a docs bug then, thank you for pointing this out. I'll update the docs to clarify this.

**Comment by glenn-jocher** [comment]
@mrekin fixed in https://github.com/ultralytics/ultralytics/pull/1892/commits/ff62da0db13d47b06309a976470483c285cfd1f9! Thank you for letting us know about this and let us know if you find any other problem :)

**Comment by mrekin** [comment]
@glenn-jocher 
already close issue, but not forget to fix connects in code :)
results.py
`pil (bool): Whether to return the image as a PIL Image.`

**Comment by glenn-jocher** [comment]
@mrekin thank you for your feedback. We have taken steps to ensure that the documentation accurately reflects the functionality of the `.plot()` method in YOLOv8. The `pil` flag tells the method whether to return the annotated image as a `numpy` array, or as a `PIL Image` object. We have updated the documentation accordingly to clarify this. We appreciate your help in improving the documentation and hope that this resolves any confusion.

**Comment by glenn-jocher** [comment]
@mrekin all done, thank you!
