### ISSUE TITLE
MLflow callback fails when experiment is not pre created.

### ISSUE THREAD

**Issue by rafaelolg** [ultralytics/ultralytics#1891]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

When trying to start training with MLFLOW_TRACKING_URI with a valid value to a new experiment, the experiment  is never assigned.

https://github.com/ultralytics/ultralytics/blob/c2cd3fd20ea39f57109f8c76eb7a4b827742d6f6/ultralytics/yolo/utils/callbacks/mlflow.py#L29-L31

This results in a error here:

https://github.com/ultralytics/ultralytics/blob/c2cd3fd20ea39f57109f8c76eb7a4b827742d6f6/ultralytics/yolo/utils/callbacks/mlflow.py#L38

### Environment

- YOLO: ultralytics==8.0.67 mlflow==2.2.2
- Python 3.10.6
-  Ubuntu 22.04.2 LTS

### Minimal Reproducible Example

`export MLFLOW_TRACKING_URI="http://<MLFLOW_URI>:5000";yolo train`

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by rafaelolg** [comment]
Tried this fix and it worked:


````
 29         experiment = mlflow.get_experiment_by_name(experiment_name)
 30         if experiment is None:
 31             mlflow.create_experiment(experiment_name)
                  experiment =  mlflow.get_experiment_by_name(experiment_name)
 32         mlflow.set_experiment(experiment_name)
 ````

**Comment by glenn-jocher** [comment]
@rafaelolg thank you! Pleases submit a PR with your fix.

**Comment by glenn-jocher** [comment]
@robmarkcole, thank you for the update. I appreciate your feedback on this issue. As per the discussion on GitHub pull request #1752, we have updated the `mlflow` callbacks to correctly handle missing experiment names. We are glad that the suggested fix worked in your case. Thank you for using YOLOv8 and if you have any further questions, feel free to reach out to us.

**Comment by syedRumman** [comment]
@rafaelolg hey man, i am trying to get mlflow callback to run. But it's not hitting the callbacks at all and I am not logging anything on the mlflow server. Would you be able to share your setup? Thanks!

**Comment by rafaelolg** [comment]
Not sure if this is the right place for this discussion. But be sure you
have the mlflow environmental variables with valid values.

Em ter., 22 de ago. de 2023 21:09, syedRumman ***@***.***>
escreveu:

**Comment by glenn-jocher** [comment]
@syedRumman sure, to run the MLFlow callback, make sure you have set the MLFLOW_TRACKING_URI environmental variable to the correct MLFlow server URI value. Also, check if other dependent environmental variables are properly configured. This should enable your MLFlow callback to log to the MLFlow server. If you still face issues, please share more details about your setup and the problem.
