### ISSUE TITLE
How to save the full image with bounding boxes from the result of detected video in yolov8?

### ISSUE THREAD

**Issue by nitin29121** [ultralytics/ultralytics#1893]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

While doing the prediction on a video, yolov8 saves the prediction inference in video only. How to save images with bounding boxes corresponding to the saved labels for the predicted video

Thanks in advance

**Comment by glenn-jocher** [comment]
@nitin29121 see https://docs.ultralytics.com/modes/predict/#streaming-source-for-loop for custom handling of video frame predict results.
