### ISSUE TITLE
using ONNX for Inference without installing Pytorch?

### ISSUE THREAD

**Issue by muhammadAgfian96** [ultralytics/ultralytics#1894]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi there,

I want to use the ONNX format for prediction with the Ultralitics library. However, Ultralitics requires the installation of PyTorch, which I would prefer not to install due to its large size and because I will not be using it for the ONNX format. Is it possible to achieve this without installing PyTorch?

**Comment by glenn-jocher** [comment]
Hello @muhammadAgfian96, thanks for reaching out! Unfortunately, YOLOv8 uses PyTorch as its deep learning framework and requires it to be installed. PyTorch is used not only for training the YOLOv8 model, but also for prediction and inference. Therefore, we can not use YOLOv8 without installing PyTorch. 

If the size of the package is a concern, one alternative to consider could be using PyTorch's [torchscript](https://pytorch.org/docs/stable/jit.html) to run YOLOv8's inference in a more efficient way. However, this would still require the installation of PyTorch.

**Comment by PrinceB7** [comment]
@muhammadAgfian96 not sure if you already solved this issue, but this repo helps you infer your segmentation model without pytorch: https://github.com/PrinceB7/yolov8-seg-onnx

**Comment by glenn-jocher** [comment]
@PrinceB7, while it's great to see community contributions, the official stance is that the Ultralytics YOLOv8 repository is designed to work with PyTorch. For any modifications or alternative implementations like the one you've mentioned, we cannot guarantee support or compatibility. If you choose to use such repositories, please be aware that it's outside the scope of the official Ultralytics documentation and support. 🛠️
