### ISSUE TITLE
Seeking clarity on how to parse openvino model output in C++

### ISSUE THREAD

**Issue by derek-knox** [ultralytics/ultralytics#1895]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How exactly should I be parsing my openvino 1x8x1344 output Tensor in C++?

### Context

I've perused the Python source code `Result` and `Boxes` to try to understand the mapping to the `xywh` and class probabilities, but I don't have clarity on this yet. The xywh and class probabilities are ultimately what I'm after, but I don't get these in C++ without manually parsing (afaik) the output data.

My openvino model outputs a 1x8x1344 as seen here:

```xml
<layer id="424" name="output0/sink_port_0" type="Result" version="opset1">
	<input>
		<port id="0" precision="FP32">
			<dim>1</dim>
			<dim>8</dim>
			<dim>1344</dim>
		</port>
	</input>
</layer>
```

And here is some sample output data which has helped me _guess_ how to parse the output, but I'm not 100% sure if my interpretation is correct. I have 4 classes in my detector and thus I'm under the impression the first four are either xywh or x0y0x1y1 where the next four are the respective class probabilities. I'd like to know with 100% certainty hence the original question. Does anyone have insight here or a link to source that will help me properly understand the mapping?

```
tensor[0][0][0] = 4.39267
tensor[0][1][0] = 5.63971
tensor[0][2][0] = 9.43832
tensor[0][3][0] = 11.3698
tensor[0][4][0] = 2.39304e-06
tensor[0][5][0] = 1.79337e-06
tensor[0][6][0] = 8.64966e-08
tensor[0][7][0] = 5.47415e-08

tensor[0][0][1] = 11.9316
tensor[0][1][1] = 4.75945
tensor[0][2][1] = 24.5353
tensor[0][3][1] = 9.92516
tensor[0][4][1] = 6.30788e-07
tensor[0][5][1] = 5.70787e-07
tensor[0][6][1] = 4.15295e-08
tensor[0][7][1] = 2.55529e-08

tensor[0][0][2] = 18.8224
tensor[0][1][2] = 5.84231
tensor[0][2][2] = 32.4648
tensor[0][3][2] = 11.9807
tensor[0][4][2] = 3.14367e-07
tensor[0][5][2] = 4.26914e-07
tensor[0][6][2] = 4.60934e-08
tensor[0][7][2] = 2.85369e-08

tensor[0][0][3] = 24.8427
tensor[0][1][3] = 5.89207
tensor[0][2][3] = 36.0952
tensor[0][3][3] = 12.1171
tensor[0][4][3] = 3.92996e-07
tensor[0][5][3] = 3.6497e-07
tensor[0][6][3] = 5.92016e-08
tensor[0][7][3] = 3.85484e-08

tensor[0][0][4] = 34.0272
tensor[0][1][4] = 5.97404
tensor[0][2][4] = 32.3866
tensor[0][3][4] = 12.3104
tensor[0][4][4] = 4.89454e-07
tensor[0][5][4] = 4.78933e-07
tensor[0][6][4] = 5.69483e-08
tensor[0][7][4] = 3.65805e-08

...
```

**Comment by glenn-jocher** [comment]
@derek-knox it appears that you have already made some progress and have correctly guessed the interpretation of the output. Based on the sample output data you provided, it appears that the first four values are indeed `x0y0x1y1` values, while the next four values are class probabilities. If you have not done so already, you can try to confirm your interpretation by comparing the results of your C++ code with those obtained from the Python `Result` and `Boxes` classes, as you mentioned you've already reviewed their source code. I understand that you would like to have a definitive source for the mapping, however it is indeed dependent on the specific model architecture and inference setup. I hope this helps!
