### ISSUE TITLE
How do I stop Yolo output?

### ISSUE THREAD

**Issue by Chase-Nolan** [ultralytics/ultralytics#1896]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I really don't like this loop of out put seen in the screenshot, how can I remove it?

![Screenshot 2023-04-07 203044](https://user-images.githubusercontent.com/99596659/230659617-045d67a4-922a-446a-90c6-c8dd3d507b7d.png)

**Comment by glenn-jocher** [comment]
Hello @mrekin, to remove the loop of output, you can try using the `verbose=False` option. This should turn off verbose output and reduce the amount of output on the console. Additionally, you may want to check the documentation at https://docs.ultralytics.com for more information on how to configure and customize the output of YOLOv8. Thank you.

**Comment by glenn-jocher** [comment]
You might also use the env variable `YOLO_VERBOSE=False`

**Comment by Chase-Nolan** [comment]
Thanks that works perfectly!

**Comment by pderrenger** [comment]
@Chase-Nolan you're welcome! I'm glad to hear that it worked perfectly for you. If you have any more questions or need further assistance with YOLOv8 or anything else, feel free to ask. Happy coding!

**Comment by Lawrence27R** [comment]
hello it is still there for me using YOLOv8 after using YOLO_VERBOSE = False

**Comment by revtheundead** [comment]
Hi, I was wondering why inferencing is done on the webcam by default. I don't capture anything from my webcam, my code only runs for a couple of IP cams but I can't figure out why the model keeps the webcam on, it seems like extra processing for me and I would like to prevent this behaviour if possible. If it helps here is how I initialize my model:

```python
def initialize_model():
    global model, CLASS_NAMES_DICT

    MODEL = "yolov8l-oiv7.pt"
    model = YOLO(MODEL)
    model.fuse()

    if torch.cuda.is_available():
        device = torch.device("cuda")
        print("Using CUDA")
    else:
        device = torch.device("cpu")
        print("Using CPU")
    model.to(device)

    CLASS_NAMES_DICT = model.model.names

    return model, CLASS_NAMES_DICT
```

**Comment by glenn-jocher** [comment]
Hello! It looks like your model initialization doesn't specify the source for the inference, which might be why it defaults to the webcam. You can explicitly set the source to your IP cams in your prediction call. Here’s how you can modify your prediction function:

```python
results = model.predict(source='rtsp://ip_cam_address')
```

Replace `'rtsp://ip_cam_address'` with the actual stream address of your IP cams. This should direct the model to use your IP cams instead of the default webcam. Hope this helps! 😊

**Comment by revtheundead** [comment]
The thing is I need to use `cv2.VideoCapture` to get the frames since I want to serve both raw and fully annotated frames. So here is how I use the model `results = next(self.model(frame, stream=True, verbose=False))`. Is there another way to simply say that I don't want to use the default behaviour?

**Comment by glenn-jocher** [comment]
Hello! If you're using `cv2.VideoCapture` and want to avoid the default webcam usage, you can directly pass the frame to the model without specifying `stream=True` since you're handling the frame capture externally. Here's a simplified way to do it:

```python
results = self.model(frame, verbose=False)
```

This should work seamlessly with your setup, ensuring that only the frames you capture are processed. Let me know if this helps or if you have any more questions! 😊

**Comment by revtheundead** [comment]
Thank you, but I used to do this without `stream=True` and inference happened all the same so I don't think thats the issue. It's weird that the official documentation doesn't mention why this happens and how I can prevent it.

**Comment by glenn-jocher** [comment]
@revtheundead hello! It sounds like you're looking for a way to ensure that your model doesn't default to using the webcam. If you're handling frame capture externally and want to prevent any default behavior, you might consider explicitly setting the device for your model when initializing it, and ensure you're not passing any default source when calling the model for predictions.

Here’s a quick example to ensure the model uses only the frames you provide:

```python
# Assuming 'frame' is obtained from your cv2.VideoCapture
results = self.model(frame)
```

Make sure that when you initialize and use the model, there are no implicit defaults affecting your setup. If this doesn't resolve the issue, it might be helpful to check if any other part of your code or a specific library version could be influencing this behavior. Let me know how it goes! 😊

**Comment by revtheundead** [comment]
Hi Glenn, thanks for reaching out. Unfortunately I tried this as well but it seems that inferencing using the webcam still happens. It feels like a bug at this point or someone unintentionally left this in the code and we can't turn it off from the provided interface.

**Comment by glenn-jocher** [comment]
Hello! It sounds frustrating to deal with this unexpected behavior. If you've ensured that no default source is being passed and the issue persists, it might indeed be a bug or an unintended default setting in the codebase. I recommend opening an issue on the [Ultralytics YOLOv8 GitHub repository](https://github.com/ultralytics/ultralytics/issues) to report this behavior. The development team can provide more specific guidance or address it in future updates. Thanks for your patience and for bringing this to our attention! 😊

**Comment by revtheundead** [comment]
I'll be sure to do that when I get the time to do so :) Thanks for your help and patience.

**Comment by glenn-jocher** [comment]
You're welcome! 😊 If you need any more help in the future, feel free to reach out. Good luck with your project!
