### ISSUE TITLE
Training questions

### ISSUE THREAD

**Issue by sxl845414442** [ultralytics/ultralytics#1903]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello author, I am a novice in this field and I am not sure if a pre trained model has been introduced. May I ask if the yaml file needs to have the same name as the pt file? Below are two pictures of my operation. Is the operation correct
![QQ截图20230408145356](https://user-images.githubusercontent.com/127416177/230707934-4b4ca4c0-0ef3-42c9-b81e-c95c6dd3737c.png)
![QQ截图20230408145425](https://user-images.githubusercontent.com/127416177/230707938-108e277a-5ebf-4f3f-9c69-da44497b3e09.png)

**Comment by sxl845414442** [comment]
I just created a py file and wrote instructions, and then annotated the n, m, l, and x of the file xiaomubiao.yaml. Can I use the pre trained model yolov8s.pt?

**Comment by glenn-jocher** [comment]
@sxl845414442 yes, you can use the pre-trained model yolov8s.pt with your configuration file xiaomubiao.yaml. You can simply specify the path to `yolov8s.pt` in your command or configuration file. However, keep in mind that the pre-trained weights are trained on a different dataset and may need to be fine-tuned on your specific task to achieve best results. I recommend referring to the documentation for instructions on how to use pre-trained models with YOLOv8 and for guidance on fine-tuning pre-trained weights.
