### ISSUE TITLE
Result image is not saved in cli mode

### ISSUE THREAD

**Issue by youngjae-avikus** [ultralytics/ultralytics#1904]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I am using the latest version of Ultralytics YOLOv8 (8.0.70) with Anaconda on Windows.
 When I entered the command yolo predict model=yolov8n.pt source=image1.jpg` in the CLI mode, the inference was made successfully but the resulting image was not saved.

<img width="902" alt="image" src="https://user-images.githubusercontent.com/99321359/230710204-d8ea0c7c-0528-4509-a662-8eb6f77876af.png">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by youngjae-avikus** [comment]
yolo cfg says save=true, so I didn't give a separate option, but I have to give the save option myself to save it. is this a bug?

**Comment by glenn-jocher** [comment]
@youngjae-avikus this is not a bug, as the `save` option is not implied by default in Ultralytics YOLOv8. If you want to save the resulting image, you have to explicitly provide the `save` option along with the desired image format and file name. You can refer to the Ultralytics YOLOv8 documentation for more information on how to use the `save` option.

**Comment by glenn-jocher** [comment]
@AyushExel @Laughing-q user points out correctly that default save=True is not being applied to predict mode (only for saving checkpoints in train mode). This seems like a bug. Do you we want to default to saving all CLI predict images? This may reduce performance but may be friendlier for new users.

**Comment by Laughing-q** [comment]
@glenn-jocher yeah I noticed that long time ago but I thought you guys designed it for some reasons.😂 Personally I would expect cli mode to save images or videos automatically.

**Comment by glenn-jocher** [comment]
@Laughing-q yeah that's probably best. Then they also get the extra line showing the save directory which avoid confusion.

**Comment by glenn-jocher** [comment]
@youngjae-avikus predict will now respect the save value in the default.yaml, which is True by default as you pointed out. This has been fixed in https://github.com/ultralytics/ultralytics/pull/1907/commits/183ec47db92a4ae3a9ade67fc47c67589d90b478 and will be published soon in 8.0.71.

**Comment by Laughing-q** [comment]
@glenn-jocher wait, does this update also mean that the images/videos would be saved automatically in python interface?

**Comment by glenn-jocher** [comment]
@Laughing-q oh good question. Yes I think so. Maybe this is why we changed it.

**Comment by glenn-jocher** [comment]
Ok I'll work on a fix.

**Comment by Laughing-q** [comment]
@glenn-jocher yeah, I prefer keeping python interface without saving anything by default.🤔 but that means cli and python will not have the same behavior on predict save.

**Comment by glenn-jocher** [comment]
@Laughing-q yeah it's a bit strange, but I think the users are expecting some sort of result after running CLI inference. I've updated it now for the different default behaviors. 

Next week we'll see a user pointing out that Python predict isn't saving as the default.yaml indicates it should 😂

**Comment by AyushExel** [comment]
@glenn-jocher @Laughing-q yeah this was intentionally designed this way after initial discussion.
Our thought process was this - the 2 interfaces are different and so they should behave differently.
* **CLI** - This interface should be used when you have to use yolo without any modifications, ie, the existing solution is what you want, so we treat every operation as complete in itself and save/log outputs.
*  **python** - When you need to modify something, or extend yolo as a part of existing pipeline. In this case the yolo operations might not be complete in itself and can be a part of a bigger pipeline,  so saving outputs by default might be pre-mature if there are many operations after it.

**Comment by glenn-jocher** [comment]
@AyushExel yup sounds good. So after this PR:

- CLI saves by default (changed)
- Python does not save (same as now)

**Comment by robot-jr** [comment]
I have noticed somthing weird when i try predicting with yolov8 on my images.
if the model makes a prediction on an image it saves it in the folder, but when there is no prediction
i noticed that it saves the pictures with the prediction instead of just the unpredicted image,
so my predicted folder has the same number of my source images and the same names
but the unpredicted images are not there and instead is one of the predicted pictures

**Comment by Laughing-q** [comment]
@robot-jr I think I probably know what's happening here, I'll try to reproduce and fix it later today.

**Comment by glenn-jocher** [comment]
@Laughing-q that's strange. If you have any small PRs for today I'm merging 8.0.72 later with some other small fixes.

**Comment by Laughing-q** [comment]
@glenn-jocher I realized that I have to add one line in each `predict.py` of all tasks, so I think it's better I fix it with just one line code after I implement result.save_crop/save_txt function and eliminate these duplication. But I don't have enough time for the implementation yesterday so I scheduled it today. :)

**Comment by glenn-jocher** [comment]
@Laughing-q ok sounds good!
