### ISSUE TITLE
Accessing individual prediction speeds

### ISSUE THREAD

**Issue by ChickenKorma** [ultralytics/ultralytics#1905]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

In a python notebook I have trained the YOLOv8 model on a custom dataset and then made predictions on the testing portion:
```results = model.predict(source="Data/RoboFlow/test/images")```

This cell gives an output of:
```
image 1/5 Data\RoboFlow\test\images\image_1_png.rf.4e558f7e01ff1908bddc1e12bd6a48d5.jpg: 640x640 1 blimp, 119.0ms
image 2/5 Data\RoboFlow\test\images\image_30_png.rf.f4f53fd8e40972e1b59a389240e5cfee.jpg: 640x640 1 blimp, 94.0ms
image 3/5 Data\RoboFlow\test\images\image_40_png.rf.b74e9f148960822e0bce231d2f535c38.jpg: 640x640 1 blimp, 91.0ms
image 4/5 Data\RoboFlow\test\images\image_46_png.rf.9add4c8ee053a80f7f8df159b66e9646.jpg: 640x640 1 blimp, 92.0ms
image 5/5 Data\RoboFlow\test\images\image_5_png.rf.cd8c0cf03243b0f678de9cd7948acff3.jpg: 640x640 1 blimp, 90.0ms
Speed: 0.8ms preprocess, 97.2ms inference, 0.6ms postprocess per image at shape (1, 3, 640, 640)
```

I can access the bounding box, class and confidence data directly from `results` but I am wondering if there is a way to also access the prediction speed as printed in the output (119.0ms, 94.0ms etc)?

If that is not possible, is there a way to capture the cell output as text and try to extract the speeds from that? I have tried using `%%capture` but this does not work.

Thank you in advance

**Comment by glenn-jocher** [comment]
@ChickenKorma speeds are in results, i.e. `results[0].speed`

<img width="755" alt="Screenshot 2023-04-08 at 14 49 35" src="https://user-images.githubusercontent.com/26833433/230722056-fc205512-7c11-4f20-a4c9-4318080582eb.png">


You can see all these details in https://docs.ultralytics.com/reference/results/

**Comment by ChickenKorma** [comment]
@glenn-jocher Thank you very much that's perfect, I did look through that docs page but the speed attribute does not seem to appear there?
Also to anyone else having issues with `results[0].speed` make sure your python version is updated.

**Comment by glenn-jocher** [comment]
@ChickenKorma yes thanks for the Docs feedback! I checked and it's missing as it's added later, so I initialized the speed attribute now and it should show correctly in the Docs in the next release.
