### ISSUE TITLE
How to run yolov8 on OpenVino? 

### ISSUE THREAD

**Issue by dhaval-zala-aivid** [ultralytics/ultralytics#191]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am using the same [script of yolov5 ](https://github.com/bethusaisampath/YOLOs_OpenVINO)to run yolov8 on openvino but its not working. So, how to run yolov8 on OpenVino

**Comment by adrianboguszewski** [comment]
Hey @dhaval-zala-aivid, please try this notebook: https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/230-yolov8-optimization/230-yolov8-optimization.ipynb

**Comment by dhaval-zala** [comment]
Thanks

I run yolov8n int8 IR converted model using this notebook it consume 40% of my CPU on 10 FPS live stream. But if I bound thread using taskset command it consume only 8-10% CPU on the same stream. So, why it is required to restrict CPU and how I can fix this?

**Comment by adrianboguszewski** [comment]
@yury-gorbachev, any idea who can help with that?

**Comment by yury-gorbachev** [comment]
@dmitry-gorokhov or @wangleis can you guys look at this question?

**Comment by wangleis** [comment]
@dhaval-zala Could you please share the full command which restrict thread using taskset command?

**Comment by wangleis** [comment]
@dhaval-zala Could you please share log of `lscpu` and `lscpu -e` as well?

**Comment by dhaval-zala** [comment]
Im using `taskset -c 0 python scripy.py `to restrict CPU

lscpu and lscpu -e

![Screenshot from 2023-02-03 17-43-07](https://user-images.githubusercontent.com/68200424/216601282-6200d0c9-ef51-4592-a3de-8adf7180234e.png)
![Screenshot from 2023-02-03 17-43-50](https://user-images.githubusercontent.com/68200424/216601290-22e56529-45ee-4c86-b753-4bd4bbc5b816.png)

**Comment by wangleis** [comment]
@dhaval-zala OpenVINO uses all CPU resources provided for application for inference. But when there is not enough input, the CPU will idle.

[yolo_openvino_demo.py]( https://github.com/bethusaisampath/YOLOs_OpenVINO/blob/main/YOLOv5/yolo_openvino_demo.py) you used loaded network to OpenVINO with 2 infer request. The following benchmark app command also loads network to OpenVINO with 2 infer request. Run this command with yolov8n int8 IR converted by [230-yolov8-optimization.ipynb](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/230-yolov8-optimization/230-yolov8-optimization.ipynb) on 4 cores 8 CPUs platform, the throughput performance is 20.31 FPS.
-_benchmark_app -d CPU -m openvino_notebooks/notebooks/230-yolov8-optimization/yolov8n_openvino_model/yolov8n.xml -shape [1,3,640,640] -nireq 2_

If run benchmark app in throughput mode as below comments, the throughput performance can achieve 30.04 FPS.
-_benchmark_app -d CPU -m openvino_notebooks/notebooks/230-yolov8-optimization/yolov8n_openvino_model/yolov8n.xml -shape [1,3,640,640] -hint throughput_

So 10 FPS live stream cannot provide enough inputs in you case. Please try the two benchmark app commands, all CPU resource on you platform will be used.

**Comment by HENNESSYxie** [comment]
> Hey @dhaval-zala-aivid, please try this notebook: https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/230-yolov8-optimization/230-yolov8-optimization.ipynb

I have tried this notebook for inference my model, but I'm recieving error:
`RuntimeError                              Traceback (most recent call last)
[<ipython-input-13-c16351ad52de>](https://localhost:8080/#) in <module>
     32 
     33 input_image = np.array(Image.open(IMAGE_PATH))
---> 34 detections = detect(input_image, det_compiled_model)[0]
     35 image_with_boxes = draw_results(detections, input_image, label_map)
     36 

2 frames
[/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/ops.py](https://localhost:8080/#) in non_max_suppression(prediction, conf_thres, iou_thres, classes, agnostic, multi_label, labels, max_det, nc, max_time_img, max_nms, max_wh)
    198 
    199     t = time.time()
--> 200     output = [torch.zeros((0, 6 + nm), device=prediction.device)] * bs
    201     for xi, x in enumerate(prediction):  # image index, image inference
    202         # Apply constraints`

**Comment by eaidova** [comment]
@HENNESSYxie  if I correctly understand, does your model trained on a different dataset? there is a parameter inside detect function, when  calling non_maximum_suppression, nc - it is responsible for a number of classes known by the model, please try to modify it according to your model supported a number of classes

**Comment by HENNESSYxie** [comment]
> @HENNESSYxie if I correctly understand, does your model trained on a different dataset? there is a parameter inside detect function, when calling non_maximum_suppression, nc - it is responsible for a number of classes known by the model, please try to modify it according to your model supported a number of classes

Its worked for me. Thanks!

**Comment by akashAD98** [comment]
@wangleis @adrianboguszewski is there any simple script to run yolov8 openvino model?
the notebook which you mentioned is very big & in order to run file need to run all notebook.

```
model = YOLO("yolov8n.pt")
start_time = time.time()
src='/content/inputvideo.mp4'
results = model.track(source=src, tracker="botsort.yaml", verbose=False, save=True)
```

i just want to use openvino weights insted of yolov8.pt , its possible to get that script ?


something like 

```
from openvino.runtime import Core
import collections

core = Core()
# read converted model
#pat of object detector
model = core.read_model("object_detector/best_weapons22_int8_IRnew.xml")
# load model on CPU device
model = core.compile_model(model, 'CPU')

```

**Comment by akashAD98** [comment]
i tested with tracker & this is the speed im getting, ill try yolov8s_int format for getting more fps.
@glenn-jocher thanks a lot , you're always supporting & helping. 
```
yolov8n.xml --> Speed: 0.8ms preprocess, 130.6ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 640)
yolov8.pt --> Speed: 0.6ms preprocess, 130.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)
yolov8s.xml. --> Speed: 1.0ms preprocess, 396.0ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640
yolov8s.pt -->Speed: 0.5ms preprocess, 416.1ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 640)


```

**Comment by akashAD98** [comment]
https://github.com/ultralytics/ultralytics/issues/1735

**Comment by glenn-jocher** [comment]
@akashAD98 OpenVINO should show speedups on Intel CPUs, i.e. if you look at the CI benchmarks here. On other CPUs ONNX may be faster:

<img width="1324" alt="Screenshot 2023-03-31 at 17 18 26" src="https://user-images.githubusercontent.com/26833433/229161488-5a64af4e-4e07-41d3-9ca4-ca91d4f1b976.png">

**Comment by akashAD98** [comment]
@glenn-jocher its fp32 openvino model or int8.xml model?

**Comment by akashAD98** [comment]
@glenn-jocher  when i didi the fps check this is how im getting, i tried it on 16 core macine &  yolov8s.pt has higher fps than openvino yolov8s.xml file, may i know why its like this?  
also yolov8.pt models using 384*640 size during predictions -may i know why its like this?
```
<img width="166" alt="image" src="https://user-images.githubusercontent.com/62583018/229732694-a76d076e-1c85-41dd-a45a-721825d4c404.png">


```

**Comment by glenn-jocher** [comment]
@akashAD98 It's curious that you are getting better results with `yolov8s.pt` than with `openvino yolov8s.xml` on an Intel CPU, because the OpenVINO tools are optimized specifically for Intel hardware. However, there may be other factors that affect the results, such as the size of the model, the preprocessing, or the batch size. 

Regarding your second question, most YOLO models do not require input images that are multiples of 32, but instead accept any image size that is divisible by two. `384x640` is probably used here as an arbitrary image size that gives good results.

**Comment by akashAD98** [comment]
@adrianboguszewski is there any way to improve fps using yolo code & openvino weights? like passing the number of threads , asynchronous queue or any other methods which we can integrate with current Yolo code?

**Comment by adrianboguszewski** [comment]
Yes. We created a new notebook showing how to improve the performance in OpenVINO. It hasn't been merged yet, but you can see some tricks [here](https://github.com/openvinotoolkit/openvino_notebooks/pull/790)

**Comment by glenn-jocher** [comment]
@akashAD98 Yes, there are several ways to improve the performance of OpenVINO models. One of them is to use number of threads, i.e. you can try to set the `num_threads` parameter to optimize your hardware. Another way is to use asynchronous inference, which allows GPU to work overlap with CPU. Yet another method is to use OpenVINO's own performance testing tools, such as the benchmark_app tool, in order to optimize your models.

**Comment by akashAD98** [comment]
@glenn-jocher i want to add this code , is there nay way to customise yolo code?
im directlyy loading openvino modelmbut i want to add few parameters to it,
```
from ultraltyics import YOLO
model = YOLO('yolov8n_openvino_model/')
results = model(img)
```

below are the some improvment things i want to try
```
num_cores = os.cpu_count()
ov_cpu_config_model = core.compile_model(ov_model, device_name="CPU", config={"INFERENCE_NUM_THREADS": num_cores})
```

```
core = Core()
model = core.read_model("object_detector/yolv8.xml)
setting = {"INFERENCE_NUM_THREADS":"16", "AFFINITY":"NUMA"}
model = core.compile_model(model=model, device_name="CPU", config=setting)

```

**Comment by glenn-jocher** [comment]
@akashAD98 Yes, you can customize the YOLO code to add features such as setting the number of threads or tuning other parameters. One way to do this is to modify the YOLO code directly and add functions that allow you to do this customization, or you could create a new class that inherits from the YOLO class and add the new features there. Just be careful when you modify the code, because it might affect other parts of the YOLO codebase. The safer way to add these features is by creating a wrapper function that loads the OpenVINO model and then sets the desired parameters before calling the YOLO function with the loaded model.

**Comment by akashAD98** [comment]
@glenn-jocher i was using int8_format of openvino weight . i compaired  fps it with yolov8_openvino weight & im exactly getting same  fps,  is``` export='openvino' ``` bydefault converting .pt weights into int8 format?

<img width="757" alt="image" src="https://user-images.githubusercontent.com/62583018/229846629-cac332aa-00d3-46fb-98d7-24d385a678a6.png">

also in the export of openvino model there is metadate.yaml file is generating
even if i pass batch=10,its not reflect any changes ,getting exactly same fps

<img width="430" alt="image" src="https://user-images.githubusercontent.com/62583018/229848511-b03bcec5-8dc4-4108-a23d-a10295969e00.png">

**Comment by glenn-jocher** [comment]
@akashAD98 The `export` parameter in the YOLO class specifies how the model should be exported. If you set it to `openvino`, the YOLO class will convert the model to OpenVINO format, and by default, it will use the int8 data format. However, you can change this behavior by specifying the `precision` parameter when exporting the model. The `metadata.yaml` file is used to store information about the exported model, such as its input and output shapes, batch size, and precision. If you're not seeing any changes in FPS when changing the batch size, it could be because the model is being executed with the same set of inputs. You may need to modify the input data to reflect the new batch size.

**Comment by achuntelolan** [comment]
i need to create a separate inference pipeline for object prediction using the model i trained using yolov8 in open vino so  how i import the architecture and how i load the yaml file extra can anyone share me some example blogs or tell me how

**Comment by glenn-jocher** [comment]
@achuntelolan hi there! 😊 To create an inference pipeline using your YOLOv8 model trained and exported for OpenVINO, you'll first need to ensure you have OpenVINO installed and set up. Then, you can use the OpenVINO `Core` API to load your model and the `InferRequest` API for inference. Here's a quick example to get you started:

```python
from openvino.runtime import Core

# Initialize OpenVINO Core
core = Core()

# Read the network and weights from the model file
model_path = 'path/to/your/yolov8_openvino_model.xml'  # Path to .xml file
model = core.read_model(model_path)

# Compile the model for a specific device
compiled_model = core.compile_model(model=model, device_name="CPU")

# Create an infer request
infer_request = compiled_model.create_infer_request()

# Prepare your input data (adjust the shape according to your model's needs)
input_data = ...  # Your input data here

# Perform inference
results = infer_request.infer(inputs={0: input_data})

# Process results
...
```

Regarding loading the YAML file, it's typically used for configuration during training with YOLOv8. For inference with OpenVINO, you usually don't need it since the model architecture and weights are already encapsulated in the exported `.xml` and `.bin` files.

For more detailed examples and guides, the [OpenVINO documentation](https://docs.openvino.ai/latest/index.html) is a fantastic resource. Also, keep an eye on the [Ultralytics GitHub](https://github.com/ultralytics/ultralytics) for any updates or example projects. Happy coding! 🚀

**Comment by achuntelolan** [comment]
Ok thank you @glenn-jocher

**Comment by glenn-jocher** [comment]
@achuntelolan you're welcome! If you have any more questions or need further assistance, feel free to ask. Happy coding! 😊

**Comment by achuntelolan** [comment]
Hii i converted to openvino by changing the size of images but that time I lost my accuracy

**Comment by achuntelolan** [comment]
Hi is Yolo v8 openvino model will work with openvio version 2022 and below and Python 3.6? because my current project is running on this configuration that's why, can anyone please help me?

**Comment by glenn-jocher** [comment]
@achuntelolan hello! 👋 YOLOv8 models exported for OpenVINO should be compatible with OpenVINO 2022 versions and work fine with Python 3.6. However, it's always good to test with your specific setup. If you encounter any issues, make sure to have the latest version of the YOLOv8 repository and consider updating OpenVINO if possible. Here's a quick snippet on how to load and use the model:

```python
from openvino.runtime import Core

core = Core()
model = core.read_model(model="path/to/your/model.xml")
compiled_model = core.compile_model(model=model, device_name="CPU")
# Now you're ready to make predictions with `compiled_model`!
```

If you run into any specific errors, feel free to share them here! 😊

**Comment by achuntelolan** [comment]
hii @glenn-jocher  while i trying to load the openvino model of yolov8 I am getting error like this I am using open vino 2021 version:
Traceback (most recent call last):
  File "yolo-old-v8.py", line 199, in <module>
    start_function()
  File "/home/anoop/AnoopAJ/ML/new_code_workshop/YOLOV8/yolov4/lib/python3.8/site-packages/memory_profiler.py", line 1188, in wrapper
    val = prof(func)(*args, **kwargs)
  File "/home/anoop/AnoopAJ/ML/new_code_workshop/YOLOV8/yolov4/lib/python3.8/site-packages/memory_profiler.py", line 761, in f
    return func(*args, **kwds)
  File "yolo-old-v8.py", line 132, in start_function
    yolo = predict(input_image_size,batch_size,thresh, common_path)
  File "yolo-old-v8.py", line 16, in __init__
    self.yolo = YOLO(inp_size=inp_size,\
  File "/home/anoop/AnoopAJ/ML/new_code_workshop/YOLOV8/yolov8.py", line 71, in __init__
    net = ie.read_network(model=model_xml,weights=model_bin)
  File "ie_api.pyx", line 368, in openvino.inference_engine.ie_api.IECore.read_network
  File "ie_api.pyx", line 411, in openvino.inference_engine.ie_api.IECore.read_network
RuntimeError: Check 'false' failed at src/frontends/common/src/frontend.cpp:53:
Converting input model
Cannot create Interpolate layer /model.10/Resize id:164 from unsupported opset: opset11

**Comment by adrianboguszewski** [comment]
@achuntelolan OV 2021 is a very old version. Any chance to update it to something newer? I think it may resolve your issue.

**Comment by achuntelolan** [comment]
Hii @adrianboguszewski updating to a newer version is a little difficult because I am running this project individually in 88 systems that are in different locations in India so updating the version is the last way before we try to resolve using the older version

**Comment by adrianboguszewski** [comment]
Could you report your bug here: https://github.com/openvinotoolkit/openvino/issues? I think our developers will be able to help :)

**Comment by achuntelolan** [comment]
Hii when i trying to run yolo v8 on openvino version 2022.2.0 with python 3.6 getting this error:
Check 'false' failed at frontends/common/src/frontend.cpp:54:
Converting input model

**Comment by adrianboguszewski** [comment]
Did you convert the model to OV with 2022.2 as well? The best way is to convert the model with the version you want to use for inference

**Comment by achuntelolan** [comment]
how i can ?

**Comment by adrianboguszewski** [comment]
Have you tried this?
``` 
from ultralytics import YOLO

# Load a YOLOv8n PyTorch model
model = YOLO('yolov8n.pt')

# Export the model
model.export(format='openvino')  # creates 'yolov8n_openvino_model/'

# Load the exported OpenVINO model
ov_model = YOLO('yolov8n_openvino_model/')

# Run inference
results = ov_model('https://ultralytics.com/images/bus.jpg')
```

**Comment by achuntelolan** [comment]
This is just exporting the pytorch model to the openvino model right, this I have done I need how to convert to the openvino 2022 version supported model

**Comment by adrianboguszewski** [comment]
You just need to run the code above, when you have OpenVINO 2022 installed.

**Comment by glenn-jocher** [comment]
Absolutely! Once you have OpenVINO 2022 installed, running the code provided will export your YOLOv8 model in a format compatible with OpenVINO 2022. This ensures that the model utilizes the latest optimizations and features available in the newer version of OpenVINO. If you encounter any issues during the process, feel free to reach out! 😊

**Comment by achuntelolan** [comment]
ya ok, but I am using python3.6 with openvino 2022.2.0 version, here while I trying to install Ultralytics lib it gives the following error :

while I'm trying to install the ultralytics package using pip in the python3.6 version it's not getting installed its showing this error:
 pip3 install ultralytics
ERROR: Could not find a version that satisfies the requirement ultralytics (from versions: none)
ERROR: No matching distribution found for ultralytics

**Comment by adrianboguszewski** [comment]
I believe you need to use a newer version of Ultralytics as well. Then newer OpenVINO will be installed.

**Comment by glenn-jocher** [comment]
You're right! Upgrading to a newer version of Ultralytics can help ensure compatibility with the latest OpenVINO. You can update the Ultralytics package using pip:

```bash
pip install ultralytics --upgrade
```

This should also handle any necessary updates to OpenVINO. Let me know if this resolves the issue or if there's anything else I can assist you with! 😊

**Comment by achuntelolan** [comment]
@glenn-jocher Yaa but i want to work with old version of openvino

**Comment by glenn-jocher** [comment]
Hi there! To work with an older version of OpenVINO, you can manually specify the version when installing OpenVINO. For example, if you want to install OpenVINO 2022.2.0, you can use:

```bash
pip install openvino==2022.2.0
```

Make sure your environment is compatible with the version you're installing. If you have any more questions or need further assistance, feel free to ask! 😊

**Comment by achuntelolan** [comment]
Hi I manually installed this version but after running the Python code to convert the Yolo v8 pytorch model to the openvino model, Ultralitics automatically updated the openvino version to the latest one

**Comment by adrianboguszewski** [comment]
@achuntelolan what version of ultralytics do you use?

**Comment by adrianboguszewski** [comment]
That's the problem. The Ultralytics package version is linked to the OpenVINO version. If you want to use older OpenVINO, you need to use older Ultralytics as well e.g. 8.0.128 which is linked to OV 2022.3 or higher. So:
1. Downgrade Ultralytics to 8.0.128
2. Downgrade OpenVINO to 2022.3
3. Use the export function

**Comment by glenn-jocher** [comment]
@adrianboguszewski absolutely! Downgrading both Ultralytics and OpenVINO to versions that are compatible with each other is a good approach. Here's a quick way to do it:

```bash
pip install ultralytics==8.0.128
pip install openvino==2022.3
```

Then, you can proceed with the export function as usual. Let me know if this helps or if you run into any other issues! 😊

**Comment by achuntelolan** [comment]
after this changes why iam getting this error :
  File "/home/atai/Anoop/yolov8/lib/python3.8/site-packages/torch/serialization.py", line 1439, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'ultralytics.utils'

**Comment by glenn-jocher** [comment]
Hi @achuntelolan,

It looks like the error is due to a missing module, likely because of version mismatches. Here’s a step-by-step to resolve it:

1. **Ensure Compatibility**: Make sure you have compatible versions of Ultralytics and OpenVINO. For instance, Ultralytics 8.0.128 works well with OpenVINO 2022.3.
   ```bash
   pip install ultralytics==8.0.128
   pip install openvino==2022.3
   ```

2. **Reinstall Dependencies**: Sometimes, a fresh installation can resolve unexpected issues.
   ```bash
   pip uninstall ultralytics openvino
   pip install ultralytics==8.0.128 openvino==2022.3
   ```

3. **Check Imports**: Ensure your script imports the correct modules and paths.

If the issue persists, please share more details about your setup. Happy coding! 😊

**Comment by achuntelolan** [comment]
Yes, I'm using the same version that you gave and this is my script for exporting :

from ultralytics import YOLO


model = YOLO('best.pt')

# Export the model
model.export(format='openvino',imgsz=(640,384))
ov_model = YOLO('yolov8n_openvino_model/')

# Run inference
results = ov_model('https://ultralytics.com/images/bus.jpg')

**Comment by glenn-jocher** [comment]
Hi @achuntelolan,

Thanks for sharing your script! It looks mostly correct, but there might be a small issue with the model path after export. Here’s a refined version:

```python
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('best.pt')

# Export the model to OpenVINO format
model.export(format='openvino', imgsz=(640, 384))

# Load the exported OpenVINO model
ov_model = YOLO('best_openvino_model/')  # Ensure this matches the export directory

# Run inference
results = ov_model('https://ultralytics.com/images/bus.jpg')
```

Make sure the directory name (`best_openvino_model/`) matches the one created during export. If you still encounter issues, please let us know! 😊

**Comment by achuntelolan** [comment]
actually I am getting the error while exporting so I have a doubt I trained the model in ultralytics latest version and converting with the older version so I just retraining my model with  Ultralytics 8.0.128 version and after trying to convert to know if that is any issues will be there, but anyway I am really happy to say that you guys giving a huge support for resolving the issues I didn't got this much support from even from my seniors also thanks @glenn-jocher for your valuable support

**Comment by glenn-jocher** [comment]
Hi @achuntelolan,

Thank you for your kind words! 😊

Yes, training your model with Ultralytics 8.0.128 and then exporting it should resolve the compatibility issues. It's always best to keep the training and exporting environments consistent.

If you encounter any further issues or need additional assistance, feel free to reach out. We're here to help!

Best of luck with your retraining and exporting!

Warm
