### ISSUE TITLE
Export .pb file has empty SignatureMap

### ISSUE THREAD

**Issue by AkashSCIENTIST** [ultralytics/ultralytics#1911]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When printing the signature map I get this error: `_SignatureMap({})`
I could be able to export the model as pb file, but could not convert pb to tflite, because : `ValueError: Only support at least one signature key.`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AkashSCIENTIST thank you for your bug report. Perhaps you might be able to contribute a fix here. The relevant *.pb export code is here, you can correct or update it as required, and then please submit a PR to help other users with this issue. Thank you!

https://github.com/ultralytics/ultralytics/blob/48f1d269fb26ed135e7b3319f74483937d245c15/ultralytics/yolo/engine/exporter.py#L553-L567

**Comment by SohailSayed** [comment]
@glenn-jocher Has this been fixed? I'm encountering the same error

**Comment by glenn-jocher** [comment]
@SohailSayed hey there! 👋

Not yet, but we're looking into the issue. If you're savvy with code, we'd absolutely welcome any contributions or ideas on how to tackle this. Basically, it's about making sure the export process includes a signature for the model, so TensorFlow Lite conversion doesn't hit a snag. 

For a quick starter, ensuring the export operation has something like this might help:

```python
builder.add_meta_graph_and_variables(sess,
                                     [tf.saved_model.tag_constants.SERVING],
                                     signature_def_map={ "serving_default": signature })
```

Stay tuned for updates!
