### ISSUE TITLE
YOLOv8 Pose Model Export Error

### ISSUE THREAD

**Issue by irmuun20** [ultralytics/ultralytics#1920]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

When I try to export the pose detection model, I got the following error:
```
ONNX: starting export with onnx 1.10.1 opset 10...
ONNX: export failure  2.4s: Unsupported: ONNX export of index_put in opset 9. Please try opset version 11.
Traceback (most recent call last):
  File "export-pose.py", line 6, in <module>
    assert success
AssertionError
```

### Environment

- YOLO: ultralytics YOLOv8 8.0.72
- OS: Windows 10
- Python 3.7.13

### Minimal Reproducible Example

```
from ultralytics import YOLO

model = YOLO("yolov8s-pose.pt")  # load a pretrained model (recommended for training)
success = model.export(format="onnx")  # export the model to onnx format
assert success
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@irmuun20 try `opset=11` or higher
![image](https://user-images.githubusercontent.com/61612323/230814407-73dccf3c-afd1-40b3-a7a8-683993cc7355.png)

**Comment by irmuun20** [comment]
fixed the issue by upgrading python version and onnx

**Comment by glenn-jocher** [comment]
@irmuun20 thank you for sharing your solution! It's great to hear that upgrading to Python 3.8 and using ONNX v1.12.0 resolved the issue you were experiencing. In general, issues like this can often be resolved by upgrading to the latest versions of dependencies or libraries, and checking compatibility between different components. If you encounter any further issues, feel free to share more details and we'll do our best to help.
