### ISSUE TITLE
No Detection on Output Image

### ISSUE THREAD

**Issue by irmuun20** [ultralytics/ultralytics#1922]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Tested yolov8 model. It produces detection results as follows but there are no detection drawings on output image:
```
Found [https:\ultralytics.com\images\bus.jpg](https://ultralytics.com/images/bus.jpg) locally at bus.jpg
image 1/1 E:\Test_yolov8\bus.jpg: 640x480 4 persons, 1 bus, 1 stop sign, 144.0ms
Speed: 1.0ms preprocess, 144.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)
```

### Environment

- YOLO: ultralytics YOLOv8 8.0.72
- OS: Windows 10
- Python 3.7.13

### Minimal Reproducible Example

```
from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

# Use the model
results = model("https://ultralytics.com/images/bus.jpg")  # predict on an image
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@irmuun20 it draws only when you pass `save=True` or `show=True`.

**Comment by irmuun20** [comment]
Thanks

**Comment by glenn-jocher** [comment]
@irmuun20 you're welcome! Glad I could help. In general, if no detections are showing up in the output image, you can set the `save` or `show` parameter to `True` to display the detections on the image. This will help you to visualize the detected objects. Let me know if you have any other questions or if there's anything else I can help you with.
