### ISSUE TITLE
Top-down or Bottom-up

### ISSUE THREAD

**Issue by irmuun20** [ultralytics/ultralytics#1924]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thank you for your wonderful implementation. I would like to know whether yolov8-pose model is top-down or bottom-up. Thanks

**Comment by glenn-jocher** [comment]
@irmuun20 in general, top-down approaches first detect humans in the image using an object detection model (like YOLO) and then estimate the pose for each person individually. Bottom-up approaches, on the other hand, detect body parts (joints) in the image and then group them together to form human poses.

YOLOv8 Pose works like all YOLO models in that it performs a single pass through the image, and in the case of Pose estimates bounding boxes, classes and keypoints simultaneously.

**Comment by irmuun20** [comment]
I see. So, yolov8-pose is a top-down method. And, simultaneously meaning that if there are N number of people on the image, its runtime will be the same(or close to) as that of 1 person on the image, (N > 1, for example 100 people). Am I correct? As far as I know, top-down approaches slow down as the number of people on the image increases. Thank you for your reply.

**Comment by glenn-jocher** [comment]
@irmuun20, YOLOv8 Pose is indeed a top-down method. And when detecting multiple people in an image, the runtime of the model is approximately proportional to the number of people present in the image. However, the exact runtime is dependent on a variety of factors such as image size, GPU hardware, and batch size. Nonetheless, overall YOLOv8 Pose has been optimized to achieve high performance while maintaining real-time inference speeds. If you have any further questions or concerns, feel free to let me know.

**Comment by irmuun20** [comment]
thanks for your reply

**Comment by irmuun20** [comment]
Same reply as previous one, are you using chatgpt or auto-reply algorithm :) ?

**Comment by blackCmd** [comment]
> Certainly, @irmuun20. YOLOv8 Pose is indeed a top-down approach for estimating human pose. As for runtime, the model's speed when detecting multiple people is approximately proportional to the number of individuals present in the image. However, there are other factors that may influence the model's runtime, such as image size, GPU hardware, and batch size. Nevertheless, YOLOv8 Pose has been optimized to achieve high performance while maintaining real-time inference speeds. If you have any further questions or concerns, please don't hesitate to let me know.

@glenn-jocher 
I want to train keypoints for cars instead of human keypoints.
Is it possible to achieve this with yolov8-pose?

**Comment by pderrenger** [comment]
Apologies for the repeated message, @irmuun20. I strive to provide consistent and accurate information for your queries. If there's anything else you'd like to know or if you have any other questions, feel free to ask, and I'll be more than happy to assist!
