### ISSUE TITLE
label shallow copy

### ISSUE THREAD

**Issue by regainOWO** [ultralytics/ultralytics#1926]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Detection

### Bug

i increased the list plot_idx in trainer.py. it will save 20 train_batch_x.jpg, but i found there are some error label plot in this images. I found it caused by label shallow copy. self.labels[index] return type is a dict, invoke the .copy function is a shallow copy.

### Environment

- YOLO: Ultralytics YOLOv8.0.21 Python-3.8.10 torch 1.11.0+cu113 CUDA:0 (Quadro P6000, 24576MiB)
- OS: Windows10
- Python:3.8.10

### Minimal Reproducible Example

``` python
label = deepcopy(self.labels[index])
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by regainOWO** [comment]
label shallow copy is down here
https://github.com/ultralytics/ultralytics/blob/95f96dc5bc1ad6fc22fa9ede1c9fe36d4c6abb56/ultralytics/yolo/data/base.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L180

**Comment by glenn-jocher** [comment]
@regainOWO yes I see the .copy() operation. I have a small test script to verify that changes to a copied dict don't affect the base dict:

```python
# Create a dict
a = {'a': 1, 'b': 2, 'c': 3}

# Copy it
b = a.copy()

# Modify the copy
b.pop('b')

# Print two dictionaries
print(a)  # {'a': 1, 'b': 2, 'c': 3}
print(b)  # {'a': 1, 'c': 3}
```

**Comment by Laughing-q** [comment]
@regainOWO Thanks for the reporting! 
are you trying to train a pose model? I'm able to reproduce this issue with pose since `keypoints` in labels is pure numpy which `labels.copy()` is shallow copy and do not work on numpy type. 

But since we have class `Bboxes` for `boxes` labels and `resample_segments` function for segments labels so detection and segmentation work properly in my case.

**Comment by Laughing-q** [comment]
@glenn-jocher @regainOWO 
```python
import numpy as np
from copy import deepcopy

kpt = np.random.rand(17, 2)

a = dict(keypoints=kpt)
b = a.copy()
a["keypoints"] += 1
print((a["keypoints"] == b["keypoints"]).all())
b = deepcopy(a)
a["keypoints"] += 1
print((a["keypoints"] == b["keypoints"]).all())
```
output:
```bash
True
False
```
