### ISSUE TITLE
i want to export my bounding box result to csv ,

### ISSUE THREAD

**Issue by HarshkumarDegamadiya** [ultralytics/ultralytics#1927]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i want to export my bounding box result to csv ,when i run this command mode.predict(source="image1.jpg) , i want bounding box coordinate as csv file .

**Comment by Mohit-robo** [comment]
There is an argument `save_txt`, does that work or only `csv`

**Comment by HarshkumarDegamadiya** [comment]
@Mohit-robo it is working but when i put video as output it is converting each frame as txt file ,which is hard to combine,

**Comment by Mohit-robo** [comment]
So what is the exact format ypu are expecting it to be in

**Comment by HarshkumarDegamadiya** [comment]
Frame name , class , x_min() , ymin(),x_max(),y_max()

**Comment by HarshkumarDegamadiya** [comment]
Frame name , class , x_min() , ymin(),x_max(),y_max()

**Comment by Mohit-robo** [comment]
Got it thanks

**Comment by glenn-jocher** [comment]
@HarshkumarDegamadiya there is no CSV output, but you can exports/save/handle results in any way you'd like, they are infinitely customizable. For details see https://docs.ultralytics.com/reference/results/
