### ISSUE TITLE
Mosaic in pose model

### ISSUE THREAD

**Issue by enhany** [ultralytics/ultralytics#1930]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

When augmentation is enabled in pose model with 3D keypoints (x,y,visible) and any keypoint is out of image (not visible because of augmentation), will "visible" value change to "invisible" ?
I can't find it in the code.

**Comment by Laughing-q** [comment]
@enhany sure it'll be turned to visible=0 from visible=1
[https://github.com/ultralytics/ultralytics/blob/95f96dc5bc1ad6fc22fa9ede1c9fe36d4c6abb56/ultralytics/yolo/data/augment.py#L327-L328](https://github.com/ultralytics/ultralytics/blob/95f96dc5bc1ad6fc22fa9ede1c9fe36d4c6abb56/ultralytics/yolo/data/augment.py#L327-L328)
