### ISSUE TITLE
TypeError: ultralytics.yolo.engine.model.YOLO.train() got multiple values for keyword argument 'verbose'

### ISSUE THREAD

**Issue by enheng-de** [ultralytics/ultralytics#1931]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

TypeError: ultralytics.yolo.engine.model.YOLO.train() got multiple values for keyword argument 'verbose'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@enheng-de, this error occurs when passing too many arguments to the `train()` method. 

One possible cause is the use of a custom training script or modified command line arguments. Review your code, and verify the number of arguments being passed to the `train()` method, making sure that only one value is being passed to each named parameter, including the `verbose` parameter.

We hope this helps, but feel free to ask more questions if you need further assistance. Good luck with your training!
