### ISSUE TITLE
How can I get seg mask in yolo v8 seg

### ISSUE THREAD

**Issue by 44825762** [ultralytics/ultralytics#1932]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I get seg mask in prediction of yolo v8 seg

**Comment by glenn-jocher** [comment]
@44825762, thanks for reaching out. YOLOv8 is not a segmentation model, but instead, it is a state-of-the-art object detection system. However, if you want to perform semantic segmentation, you might want to check out the [Deep Learning Toolkit for Images](https://docs.nvidia.com/deeplearning/frameworks/dl-image-library/index.html) by NVIDIA, which has segmentation models that you can use. 

If you have any more questions related to YOLOv8, please do not hesitate to ask.

**Comment by glenn-jocher** [comment]
@44825762, thanks for reaching out. You can get segmentation masks via the Results. See https://docs.ultralytics.com/modes/predict/ for details

**Comment by lvjihui** [comment]
when i use yolov8 to get the mask, I find the masks.xy just  represent  the contour point? how can i get all the point of an object?
`results=self.model.predict(source=image,device=self.device,conf=0.6)
   masks=results[0].masks.xy
img=cv2.imread(rgb_file)
    for i in range(len(masks)):
        (u, v) = (int(masks[i][0]), int(masks[i][1]))
        # print((u,v))
        cv2.circle(img, (u,v), 1, (0, 0, 255), -1)
    cv2.imshow('Marked Image', img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()`

the result is 
![Marked Image_screenshot_11 04 2023](https://user-images.githubusercontent.com/95521166/231047582-3c3a11ee-70e6-4940-9357-22cf83f67f22.png)

**Comment by manasrda** [comment]
@Laughing-q  
```results[0].masks.masks``` and ```results[0].masks.data```  returns masks of shape (n, 128, 640). Is there a way to get a mask that has the same shape of the original image?

**Comment by Laughing-q** [comment]
@manasrda set `retina_masks=True`, but might occupy more cpu and gpu memory if your original resolution is pretty high.

**Comment by adit-0503** [comment]
Hi @Laughing-q can you explain what the `retina_masks` flag does in detail. In the documentation we get the following documentation:


> Uses high-resolution segmentation masks if available in the model. This can enhance mask quality for segmentation tasks, providing finer detail.


But from your comment it seems it helps to obtain masks for the same resolution as the original input image
