### ISSUE TITLE
Save multiple predicted results to one output folder(custom path).

### ISSUE THREAD

**Issue by mathur01** [ultralytics/ultralytics#1935]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to save multiple image prediction into one folder, in yolov5 we was able to edit detect.py. In yolov8 how we can do so. i tried following code but not sucess.
```
import os
import cv2
import torch
from models.experimental import attempt_load
from utils.general import non_max_suppression, scale_coords, plot_one_box
from utils.dataloaders import LoadImages, letterbox
device = 'cpu'
model = attempt_load('C:/Users/nirbhay.matur/Desktop/EmptySpaceProject/EmptySpaceYolov8/train19/weights/best.pt', map_location=device)
imgsz = 640
img_folder = 'C:/Users/nirbhay.matur/Desktop/EmptySpaceProject/EmptySpaceYolov8/TestData'
img_paths = [os.path.join(img_folder, f) for f in os.listdir(img_folder) if f.endswith('.jpg')]
for img_path in img_paths:
    # Load input image
    img = cv2.imread(img_path)

    # Resize and pad image
    img, _, _, _ = letterbox(img, new_shape=imgsz)

    # Convert image to tensor
    img = img[:, :, ::-1].transpose(2, 0, 1)
    img = img[np.newaxis, :, :, :] / 255.0
    img = torch.from_numpy(img).to(device)

    # Make predictions on image
    pred = model(img)[0]

    # Apply non-maximum suppression to filter detections
    pred = non_max_suppression(pred, conf_thres=0.5, iou_thres=0.5)

    # Get detection results
    det = pred[0]

    # Iterate over detections and draw bounding boxes on image
    for *xyxy, conf, cls in det:
        # Scale bounding box coordinates back to original image size
        xyxy = scale_coords(img.shape[2:], xyxy, img.shape[2:]).round()

        # Draw bounding box on image
        plot_one_box(xyxy, img, label=f'{cls} {conf:.2f}')

    # Save image with bounding boxes
    output_path = os.path.join('path/to/output/folder', os.path.basename(img_path))
    cv2.imwrite(output_path, img[0, :, :, :].cpu().numpy() * 255)
```
error:
`ImportError: cannot import name 'scale_coords' from 'utils.general'`
I have kept all required files from yolov5 such as : models, utils

**Comment by glenn-jocher** [comment]
@mathur01 you are using a YOLOv5 utility function `scale_coords` in your YOLOv8 code snippet, which is why you are getting an import error. In YOLOv8, you should instead use `model.scale_coords()` or `model.autoscale()`. In order to save multiple predicted images in one folder, you should provide a constant output folder path `'path/to/output/folder'`, instead of rejoining with each image path with `os.path.basename(img_path)`.

**Comment by glenn-jocher** [comment]
@mathur01 you can define a custom save directory combining `project` and `name` arguments just like in YOLOv5:

```
yolo predict project=PROJECT name=NAME exist_ok=True
```
