### ISSUE TITLE
save information displayed on screen to custom log file 

### ISSUE THREAD

**Issue by bobyfisch** [ultralytics/ultralytics#1937]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to create custom logs for training/inference with some of the information displayed on screen:
 
- Is there any option to save the information displayed on screen while training to a custom file? Is  this information already saved some place I can't find?

- This is also interesting when I'm predicting on a video (with `yolo.predict(source= video_path)`) -  as I would like to save inference times for each frame in a log, not just the output video file.

I have tried redirecting stdout but to no avail, for example, for model train:

![image](https://user-images.githubusercontent.com/84570376/230944132-c5d18d4c-7574-43fa-a555-4d1b249e4272.png)

I suppose this is due to the use of the logging module in the code, but I can't think of a solution apart from forking and editing the logging functions locally.

**Comment by glenn-jocher** [comment]
@bobyfisch this is a great question! There should be a way to update the python logger to also output to a file in addition to the console. We experimented with this in YOLOv5 but never fully implemented it.

**Comment by mehran66** [comment]
I have been using nohup and redirect the outputs to a log file:

    nohup python train.py  > ./runs/log_ex0.out

In YoloV8, my training was intersuppted after closing terminal even with nohup.... setsid and  disown fixed it for me:

    setsid nohup python train.py --config ./configs/config_training.yaml > ./runs/log_ex0.out & disown
    
the only minor issue with this approach is the use of coloring logs used in Yolo code to change the color of logs when printing into the screen....so those color codes prints out before and after text.

**Comment by bobyfisch** [comment]
Thank you for the pointer @mehran66, however, I wanted to automate log saving in python to be able to experiment and compare runs easily, for example by saving them with standard names that match run params, date-time, etc. I suppose I could write bash to execute python automatically and save logs with nohup but this seems like a very un-clean work around.

@glenn-jocher thank you very much for the feedback and quick response! Should I turn this into a  feature request?
