### ISSUE TITLE
Confusion Matrix for classification

### ISSUE THREAD

**Issue by Ercalvez** [ultralytics/ultralytics#1938]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Confusion Matrix is only available for detection. The goal is to implement confusion matrix for classification task.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Ercalvez thank you for your interest in contributing to YOLOv8! We appreciate your initiative.

Regarding your feature request for confusion matrix for classification task, we understand that it would be a useful addition to YOLOv8. We encourage you to continue your contributions to this project by submitting a pull request with your implementation. 

Please make sure to follow our [contributing guidelines](https://github.com/ultralytics/ultralytics/blob/main/.github/CONTRIBUTING.md) to ensure your code meets our standards and can be easily reviewed. If you have any questions or concerns, please do not hesitate to ask on our [community forum](https://forums.ultralytics.com/) or open a new issue.
