### ISSUE TITLE
Main Difference versus YOLOv5 v7.0?

### ISSUE THREAD

**Issue by sarmientoj24** [ultralytics/ultralytics#194]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

What would be the main difference versus YOLOv5 v7.0?

**Comment by AyushExel** [comment]
@sarmientoj24 There are many changes. The models are much more accurate. The architecture is different and the entire framework is written from scratch. We'll release more details along with the paper soon

**Comment by Nil-Andreu** [comment]
There is this related [issue](https://github.com/ultralytics/ultralytics/issues/189), that could help solve your question.

**Comment by RangeKing** [comment]
@sarmientoj24 I've briefly summarize the main difference of YOLOv8 model structure versus YOLOv5 v7.0 in https://github.com/ultralytics/ultralytics/issues/189.
