### ISSUE TITLE
Offline training may report an error

### ISSUE THREAD

**Issue by wynshiter** [ultralytics/ultralytics#1941]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

 File "C:\Users\WYANING\.conda\envs\tracking\lib\site-packages\ultralytics\yolo\utils\checks.py", line 131, in check_latest_pypi_version
    response = requests.get(f'https://pypi.org/pypi/{package_name}/json')
  File "C:\Users\WYANING\.conda\envs\tracking\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\WYANING\.conda\envs\tracking\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\WYANING\.conda\envs\tracking\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\WYANING\.conda\envs\tracking\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\WYANING\.conda\envs\tracking\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/ultralytics/json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

### Additional

shall we add verify=False here？ or we have other solution？
response = requests.get(f'https://pypi.org/pypi/{package_name}/json',verify=False)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wynshiter hello, 

Thank you for reporting this issue. The error message suggests that there is a SSL certificate verification problem when the code attempts to connect to the official PyPi API to check for the latest package version. While adding "verify=False" might help bypass this error, this approach may introduce security risks. Instead, we recommend checking your SSL/TLS libraries, system time and CA certificates configuration. You can refer to the Python Requests documentation for more information. Please let us know if you have any further questions or concerns.

**Comment by wynshiter** [comment]
> @wynshiter I've decided to add your recommended change here as this should reduce issues in the future for other users. Change implemented in [cef04cf](https://github.com/ultralytics/ultralytics/commit/cef04cf0f7c9fa3b32436638cb7de84688bc275d)

Thank you for taking the suggestion
