### ISSUE TITLE
When I use 'stream = True' the code is stopping and out!! How can I solve this issue?

### ISSUE THREAD

**Issue by mohammed3120** [ultralytics/ultralytics#1951]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection, Other

### Bug

![Screenshot (7)](https://user-images.githubusercontent.com/36825089/231084328-20f4b90d-3409-46c9-9511-392f34b02846.png)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@mohammed3120 see the usage in docs [https://docs.ultralytics.com/modes/predict/](https://docs.ultralytics.com/modes/predict/), it'll return a generator when you set `stream=True`, you have to use a for loop to launch this generator.
