### ISSUE TITLE
YOLOv8n-pose model export issue

### ISSUE THREAD

**Issue by wzf19947** [ultralytics/ultralytics#1952]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I exported the YOLOv8n-pose.pt successfully，and it got out with shape of [1,56,8400]，I know the 8400 equals 80*80+40*40+20*20, so how can I do to export the model with 3 branches outputs as [1,56,6400],[1,56,1600],[1,56,400]? 
Thank you for your any reply.

**Comment by glenn-jocher** [comment]
@wzf19947 YOLOv8 Pose model usage is displayed directly after export, you can follow these guidelines to predict or val with your Pose model in any of the supported export formats. 

Outputs for any number of detect/pose layers are concatenated into a single output in all YOLOv8 models. You can visualize YOLOv8 architecture using Netron viewer on exported formats like ONNX.

**Comment by wzf19947** [comment]
> 
Thank you for your help. I wonder if there any ways to modify "Outputs for any number of detect/pose layers are concatenated into a single output in all YOLOv8 models."  since I don't want to merge the outputs into a single output.

**Comment by Laughing-q** [comment]
@wzf19947 you can modify the inference code of `Detect` and `Pose` modules in ultralytics/nn/modules.py
