### ISSUE TITLE
Detecting small objects in crowded images

### ISSUE THREAD

**Issue by aurelm95** [ultralytics/ultralytics#1957]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would like to train a model in a custom dataset that consists of crowded images with small objects.

- Some of these objects might be really close to each other (so I guess the NMS algorithm should be modified)
- There might be a lot  (+300) objects in the same image.

How should I set up the configuration for the best performance?

Thanks!

**Comment by aurelm95** [comment]
> @aurelm95 thank you for your question! That sounds like an interesting and challenging dataset to work with. Since YOLOv8 uses a post-processing Non-Maximum Suppression (NMS) algorithm, you can adjust the IoU (Intersection over Union) threshold to control the degree of overlapping objects that will be kept or removed. YOLOv8 also has an anchor-free model (ATSS) that can help detect small objects. Additionally, the batch size and image size can be adjusted based on the available GPU memory to optimize training. Please refer to our documentation at https://docs.ultralytics.com/ for further details on these topics. Hopefully this helps you get started!

Thanks for the suggestions!

**Comment by glenn-jocher** [comment]
@aurelm95 you're welcome! To optimize your YOLOv8 training on the crowded custom dataset with small objects, you can adjust the IoU threshold in the post-processing Non-Maximum Suppression (NMS) to control the overlap calculation. YOLOv8's anchor-free model (ATSS) can also help improve small object detection. Lastly, adjusting the batch size and image size based on your GPU memory can optimize your training. We have additional documentation available at https://docs.ultralytics.com/ that can further guide you in implementing these techniques. Good luck with your training!

**Comment by CPFelix** [comment]
What do you mean "ATSS"?Is it the label assign method? @glenn-jocher

**Comment by glenn-jocher** [comment]
Hi @CPFelix, thank you for your question! In YOLOv8, "ATSS" stands for "Adaptive Training Sample Selection". It is a method for selecting training samples for object detection, specifically designed to work well with anchor-free models. The idea is to select samples with high potential for informative training, where the measure of informativeness is based on the quality of the sample's positive and negative anchors. ATSS helps ensure that the model pays attention to difficult examples during training, which can lead to better performance on challenging datasets. Please let me know if you have further questions on this or other aspects of YOLOv8!

**Comment by hankhhy** [comment]
> @aurelm95 thank you for your question! That sounds like an interesting and challenging dataset to work with. Since YOLOv8 uses a post-processing Non-Maximum Suppression (NMS) algorithm, you can adjust the IoU (Intersection over Union) threshold to control the degree of overlapping objects that will be kept or removed. YOLOv8 also has an anchor-free model (ATSS) that can help detect small objects. Additionally, the batch size and image size can be adjusted based on the available GPU memory to optimize training. Please refer to our documentation at https://docs.ultralytics.com/ for further details on these topics. Hopefully this helps you get started!

**Comment by whittenator** [comment]
@glenn-jocher How does one enable ATSS? Is this a simply configuration change that I am missing?

Also, I have read a couple discussions where people have recommended the P2 adaptation to YoloV8 for small object detection. Is this the anchor-free model you are referring to?

Also, are there any other tips/tricks that you have for training a YoloV8 model on a custom dataset that involves mainly small objects?

Thanks

**Comment by glenn-jocher** [comment]
Hello @whittenator, thank you for your questions!

1. "ATSS" or Adaptive Training Sample Selection, is enabled by default on the YOLOv8 model. It does not require any additional configuration on your end.

2. The P2 adaptation is not explicitly what we refer to as the anchor-free model. However, this model does use strategies that help with small object detection. ATSS, as mentioned earlier, is a part of our anchor-free approach.

3. As for training a YOLOv8 model on a custom dataset with small objects, you might find it helpful to adjust your input image sizes. Increasing the size can effectively "enlarge" the small objects, which can be beneficial for detection. Moreover, remember to set a lower IoU threshold for NMS to accommodate tightly spaced objects.

Remember, the training process is empirical, and results can vary wildly depending on the specifics of the dataset. The best advice I can give is to try different configurations, review the results, and iterate.

Thank you for your interest in the YOLOv8 model, and I wish you the best in your object detection endeavors.

**Comment by tongchangD** [comment]
@glenn-jocher  from this  [article](https://zhuanlan.zhihu.com/p/632343063)，he said use `ATSS` to change `TAL`,but i can't find TAL in ultralytics,and you said  ATSS is enabled by default on the YOLOv8 model.
this mean ,I only need add P2 in the last layer
like this,
```
- [[18, 21, 24, 27], 1, Segment, [nc, 32, 256]]  # Segment(P2, P3, P4, P5) # change  - [[15, 18, 21], 1, Segment, [nc, 32, 256]]  # Segment(P3, P4, P5)
```
and he said can change the default size of the anchor box from 5 to 3，
but where to change it，i could't find it 
best,
tongchangD

**Comment by glenn-jocher** [comment]
Hello @tongchangD, thank you for bringing up these points!

In YOLOv8, 'ATSS' stands for 'Adaptive Training Sample Selection'. It is a mechanism used by the model by default and does not require additional code changes. It adapts the training process to better detect a wide range of object scales by selecting informative samples based on their potential during training. As for 'TAL', it appears there may be a misunderstanding, as this term is not used in the YOLOv8 model.

As for adding P2 in the last layer, you're thinking along the right lines. Adding P2 as an additional segmentation layer does indeed increase the feature resolution and is beneficial for detecting small objects.

When it comes to the default anchor box sizes, they are preset in YOLOv8 model according to the standard object scales found in most generic datasets. Changing them might not be straightforward as it requires modifying the architecture of the model and its training process. However, YOLOv8 has been designed in a robust way in terms of handling different sizes and aspect ratios of objects.

I hope this clears up your doubts. If you have further questions or need more clarification, please feel free to ask. Happy coding!
