### ISSUE TITLE
Documentation for how this library communicates with Ultralytics and Sentry?

### ISSUE THREAD

**Issue by akx** [ultralytics/ultralytics#1961]
The original issue #791 was closed without this being addressed by @ultralytics, so bringing this up again: I don't think it's clearly documented that this library implicitly, by default, communicates with

* https://api.ultralytics.com/v1/usage/anonymous (which I don't think is quite anonymous)
* [Sentry](https://sentry.io/)

As I mentioned before, this could have implications (GDPR sub-processors, etc.) for any user of the library.

---

> I think the whole `sync` option should be very prominently documented (not just in a docstring introduced in #125), because it's pretty surprising that a library would quietly send pseudonymous (not anonymous, since the `settings['uuid']` value is deterministic) data to an arbitrary location.
>
> `sync` also seems to enable posting error reports to [Sentry](https://sentry.io/); this seems to have been added in #449 (and #568, etc.). IANAL, but this could have some GDPR consequences since Sentry is a third party.

_Originally posted by @akx in https://github.com/ultralytics/ultralytics/issues/791#issuecomment-1427927465_

**Comment by glenn-jocher** [comment]
@akx, thank you for bringing this up. We take privacy concerns very seriously at Ultralytics and are committed to ensuring that our users understand how their data is collected and used. 

Please note that the `https://api.ultralytics.com/v1/usage/anonymous` endpoint is used solely for the purpose of anonymously tracking software usage for statistical purposes, whereas the Sentry integration is used for crash reporting when an error is encountered while running YOLOv8. 

However, we understand that users may have GDPR compliance concerns and will look into making these details more prominent in our documentation. 

In the meantime, users can set the `--device` flag to `cpu` to ensure that no data is sent to our servers during runtime.
