### ISSUE TITLE
How to install ultralites in docker? 

### ISSUE THREAD

**Issue by AverinaMasha** [ultralytics/ultralytics#1963]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to install ultralites in docker? Swears when installing via pip. In the available dockers, he does not see Tesla video cards.

**Comment by glenn-jocher** [comment]
@AverinaMasha you can use the official YOLOv8 Docker image:
```
t=ultralytics/ultralytics:latest && sudo docker pull $t && sudo docker run -it --ipc=host --gpus all $t
```
