### ISSUE TITLE
YOLOv8-Pose annotations format

### ISSUE THREAD

**Issue by Yusepp** [ultralytics/ultralytics#1970]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am currently working on a pose detection task using YOLOv8 and I am facing an issue with the annotations format. I have referred to the documentation and searched for answered questions, but I couldn't find any information on the proper format for annotations specific to pose detection tasks.

I understand that the general format for annotations in YOLOv8 is (class Id, bbox, bbox, bbox, bbox, keypoints), but I am unsure if this format is suitable for pose detection tasks or if there is a specific format that I should follow.

I also wanted to know if the parser in YOLOv8 reads any kind of keypoints or only COCO pose format.

Could you please provide me with the proper format for annotations in YOLOv8 for pose detection tasks and clarify if the parser reads any kind of keypoints or only COCO pose format?

Thank you for your time and assistance

**Comment by AyushExel** [comment]
Yes, your assumption about the format is correct. it is (class Id, bbox, bbox, bbox, bbox, keypoints) for coco-pose dataset it is - (class id, box, box, box, box, 17x3 keypoints) - here each keypoint is 3 dimensional - x,y, visibility. You can also have a keypoint dataset with 2 dimensions - x, y co-ordinates. 
We'll work on a dedicated dataset format converter to make it easy for users to convert dataset formats.

**Comment by Yusepp** [comment]
> Yes, your assumption about the format is correct. it is (class Id, bbox, bbox, bbox, bbox, keypoints) for coco-pose dataset it is - (class id, box, box, box, box, 17x3 keypoints) - here each keypoint is 3 dimensional - x,y, visibility. You can also have a keypoint dataset with 2 dimensions - x, y co-ordinates. We'll work on a dedicated dataset format converter to make it easy for users to convert dataset formats.

If use coordinates x,y, will the model automatically infer also the visibility?

**Comment by computervisioneng** [comment]
> > Yes, your assumption about the format is correct. it is (class Id, bbox, bbox, bbox, bbox, keypoints) for coco-pose dataset it is - (class id, box, box, box, box, 17x3 keypoints) - here each keypoint is 3 dimensional - x,y, visibility. You can also have a keypoint dataset with 2 dimensions - x, y co-ordinates. We'll work on a dedicated dataset format converter to make it easy for users to convert dataset formats.
> 
> If use coordinates x,y, will the model automatically infer also the visibility?

I am curious to know this too. In the case of [x, y] annotations, how to specify the keypoint visibility? Maybe we should use a special code like [0, 0] or [-1, -1] for non visible keypoints?

**Comment by ryouchinsa** [comment]
We improved the JSON2YOLO script so that it converts the COCO keypoints format to YOLOv8 format.
https://github.com/ultralytics/JSON2YOLO/issues/45

[RectLabel](https://rectlabel.com) is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel, you can label polygons and keypoints in the YOLO format.
```
class_index center_x center_y width height x1 y1 v1 x2 v2 y2 x3 y3 v3 ...
0 0.545230 0.616880 0.298794 0.766239 0.522073 0.309332 2 0.540170 0.293193 2 0.499589 0.296503 2 ...
```

A visibility flag v defined as v=0: not labeled, v=1: labeled but not visible, and v=2: labeled and visible.
https://cocodataset.org/#format-data

![yolo_polygon](https://user-images.githubusercontent.com/1954306/209942647-fa9565e0-d4cf-42c2-a382-a8043465765b.jpg)

**Comment by glenn-jocher** [comment]
@ryouchinsa great to hear that the JSON2YOLO script has been improved to convert the COCO keypoints format to the YOLOv8 format. This improvement means that you can use the COCO format for your annotations and the script will automatically convert them to the YOLOv8 format. 

Regarding your question about how to specify keypoint visibility if you're using [x, y] annotations, one approach is to use a visibility flag like COCO does, where 0 means not labeled, 1 means labeled but not visible, and 2 means labeled and visible. In the case of the YOLOv8 format, you can use a special code like [0,0] or [-1,-1] for non-visible keypoints, so the model can easily differentiate between visible and non-visible keypoints. 

It's also worth noting that the RectLabel tool can be used to label polygons and keypoints in the YOLO format, including the visibility flags.

**Comment by AyushExel** [comment]
@ryouchinsa Hey, it's great news. I have been procrastinating on pose support. Would you like to make a PR to include this change in josn2yolo? I can also do it if you want. Thanks :)

**Comment by ryouchinsa** [comment]
Thanks for reviewing the script.
We created a pull request.
https://github.com/ultralytics/JSON2YOLO/pull/46

**Comment by glenn-jocher** [comment]
@ryouchinsa thank you for the update and for creating a pull request for the JSON2YOLO script improvement. We appreciate your effort and contribution to the YOLOv8 community! Our team will review the pull request and merge it as soon as possible. Please let us know if there is anything else that we can help you with regarding YOLOv8. Thank you.

**Comment by Yusepp** [comment]
Should the coordinates of the keypoints be relative to the cropped image or the global image? In other words, should I adjust the coordinates to take into account the cropping, or should I keep them as they are in the original image?

I've tried to search for an answer to this question, but I couldn't find a clear answer.

**Comment by glenn-jocher** [comment]
@Yusepp thanks for reaching out. The coordinates of the keypoints should be relative to the global image and not the cropped image. This means that if you are working with a cropped image, you should adjust the keypoints' coordinates to take into account the cropping. For instance, if a person is cropped out from the original image and the keypoints are set to the original position then the model will not be able to correctly predict the keypoints for the person in the cropped image.

So, to ensure that keypoint predictions are correct, it's important to adjust the coordinates of the keypoints to be relative to the global image.

I hope this helps. Let us know if you have any further questions.

**Comment by josh-001** [comment]
> @ryouchinsa thank you for the update and for creating a pull request for the JSON2YOLO script improvement. We appreciate your effort and contribution to the YOLOv8 community! Our team will review the pull request and merge it as soon as possible. Please let us know if there is anything else that we can help you with regarding YOLOv8. Thank you.

[bboxpose-1.json](https://github.com/ultralytics/ultralytics/files/13256821/bboxpose-1.json)
this is my son file I am trying to convert json file to coco file but its throwing an error

kpt_shape: [4, 3]
flip_idx: [0, 2, 1, 3]
Annotations /home/bhanu/JSON2YOLO/bboxpose-1.json:   0%|  | 0/9 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "j2y.py", line 439, in <module>
    convert_coco_json('/home/bhanu/JSON2YOLO',  # directory with *.json
  File "j2y.py", line 289, in convert_coco_json
    box[[0, 2]] /= w  # normalize x
IndexError: index 0 is out of bounds for axis 0 with size 0


What changes I have to do?
is that json file is correct?if not from where I should do the annotations?
Thanks.

**Comment by glenn-jocher** [comment]
@josh-001 hello, thank you for reaching out about your problem. The error message you are seeing, "index 0 is out of bounds for axis 0 with size 0", suggests that your annotations data may not be loaded correctly or the content is empty. If there are no annotations loaded, there won't be any axis for the index to access, thereby causing the index out of bounds error. 

As for the JSON file, it's hard to determine if it's correct without examining it. However, the standard JSON annotation file structure for YOLOv8 looks something like this:

```
[
  {
    "image_path": "image1.jpg",
    "annotations": [
      {
        "class": 0,
        "bbox": [x, y, width, height],
        "keypoints": [x1, y1, v1, x2, y2, v2, ..., xn, yn, vn]
      },
      ...
    ]
  },
  ...
]
```

Each image has an "annotations" list, and within this list, each annotated object has a "class", "bbox", and "keypoints". "class" is the class index you want to detect, "bbox" is the bounding box represented by x, y, width, and height, and "keypoints" are the x, y coordinates and visibility of each keypoint you want to detect. 

Make sure your JSON file follows this structure and that your annotations are correct. If the issue persists, it's possibly a code issue and we recommend you to carefully follow the script execution and where the data loading happens.

**Comment by ryouchinsa** [comment]
Hi @josh-001, I fixed your problem in this comment.
https://github.com/ultralytics/JSON2YOLO/issues/49#issuecomment-1831384098

**Comment by glenn-jocher** [comment]
Hi @ryouchinsa, glad to hear the issue has been addressed. If you have any more questions or need further assistance with YOLOv8, feel free to reach out. Happy detecting! 🚀

**Comment by palmcorp** [comment]
Follow on from  #1970
Follow up Question on why labels are being rejected.
We have images annotated with CVAT key points.  They were exported as COCO 1.0 annotations and converted to YOLOv8 annotations with the Yolo script (JSON2YOLO).  Alter loading yolov8n-pose and initializing the pose model the labels are being rejected with the following error:
train: WARNING ⚠️ /content/datasets/echo-pose/images/train2017/frame_000000.PNG: ignoring corrupt image/label: labels require 13 columns each
Images are PNG as exported by CVAT.
Here are a couple of sample labels:
frame_000000.txt
0 0.680863 0.595223 0.20369 0.0726488 0.579017 0.631547 2 0.687827 0.609047 2 0.748973 0.590758 2 0.782708 0.558898 2 0.6325 0.624151 2

frame_000001.txt
0 0.659062 0.613906 0.23378 0.0539435 0.542172 0.640877 2 0.645104 0.61308 2 0.714791 0.617574 2 0.775952 0.586934 2 0.589449 0.637366 2

frame_000002.txt
0 0.683393 0.603251 0.211935 0.0538542 0.577425 0.630178 2 0.70613 0.604702 2 0.762752 0.590238 2 0.78936 0.576324 2 0.655357 0.617142 2

As near as I can tell, these annotations do contain 13 columns as follows:
It seems that we  have 13:
Classes: cls = 5
Keypoints = 4 
Box:              4 
Total = 13

Anyone else encountering similar situation?
PS here is the data.yaml file:
#keypoint data sets

# Data
#path: D:POSE/data
path: /content/datasets/echo-pose
train: images/train2017   # subsets to D
val:   images/val2017 # relative to path

# Keypoints
kpt_shape: [4,2]  # number of keypoints, number of dim
flip_indx: [0,1,2,3]  # no flipping

#backbone:  using standard backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9
#using standard head

head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 8], 1, Concat, [1]] # cat backbone P5
  - [-1, 3, C2, [768, False]] # 14

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2, [512, False]] # 17

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2, [256, False]] # 20 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 17], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2, [512, False]] # 23 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 14], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2, [768, False]] # 26 (P5/32-large)

  - [-1, 1, Conv, [768, 3, 2]]
  - [[-1, 11], 1, Concat, [1]] # cat head P6
  - [-1, 3, C2, [1024, False]] # 29 (P6/64-xlarge)

  - [[20, 23, 26, 29], 1, Pose, [nc, kpt_shape]] # Pose(P3, P4, P5, P6)

# Classes
names:
  0: Class0
  1: Class1
  2: Clsss2
  3: Class3
  4: Class4

**Comment by ryouchinsa** [comment]
Hi @palmcorp, looking at your text file, there are 5 keypoints. 
The first integer is the class id, following 4 float values are the bounding box [x, y, w, h], and the rest values are keypoint [x, y, v] values.

0
0.680863 0.595223 0.20369 0.0726488 
0.579017 0.631547 2 
0.687827 0.609047 2
0.748973 0.590758 2 
0.782708 0.558898 2 
0.6325 0.624151 2

**Comment by palmcorp** [comment]
Agreed.  But the format still looks OK to me.  Do you see a problem that would cause the label to be rejected?  And where does the message “13 columns” apply to?

Thanks in advance.

 

-- 

==============================

Paul L Petronelli

CEO

PALM Associates, Inc.

***@***.***

 

paul.petronelli [skype]

(408) 582-8056 [cell]

http://www.palmcorp.com

**Comment by glenn-jocher** [comment]
@palmcorp hi Paul,

The format you've provided does indeed look correct for YOLOv8-Pose with keypoints. The "13 columns" message typically refers to the expected data points per line in the label files, which should include the class id, bounding box coordinates, and keypoint coordinates. Each keypoint should have three values (x, y, visibility), which seems to be correctly formatted in your example.

If the labels are still being rejected, it might be worth double-checking for any invisible characters or formatting issues in the text files that might not be immediately visible. Sometimes, issues like these can cause parsing errors.

Hope this helps! Let me know if there's anything else you need. 😊

**Comment by ryouchinsa** [comment]
Hi @palmcorp, I noticed another thing about the kpt_shape in your yaml file.

If your label file is correct.

frame_000000.txt
0 0.680863 0.595223 0.20369 0.0726488 0.579017 0.631547 2 0.687827 0.609047 2 0.748973 0.590758 2 0.782708 0.558898 2 0.6325 0.624151 2

Then the yaml file should be like this. Because your label file includes 5 keypoints and (x, y, v) values.

kpt_shape: [5,3] # number of keypoints, number of dim
flip_indx: [0,1,2,3, 4] # no flipping

If your yaml file is correct.

kpt_shape: [4,2] # number of keypoints, number of dim
flip_indx: [0,1,2,3] # no flipping

The label file should be like this. There should be 4 keypoints and all keypoints are visible so that the value 2 is ignored.

frame_000000.txt
0 0.680863 0.595223 0.20369 0.0726488 0.579017 0.631547 0.687827 0.609047 0.748973 0.590758 0.782708 0.558898

Hope this helps.

**Comment by palmcorp** [comment]
Hi Ryo,

Thanks for the insight. Very helpful. 

 

Since there is only one yaml file that covers all labels, would it make sense to make sure all of the labels are in the same format  [5,3] or [4,2] by adding null keypoints  to the shorter labels?  Note, a similar approach was evident in the coco example (https://docs.ultralytics.com/datasets/pose/.  Because there is one overriding yaml file, should there be an instruction on the web site that ALL labels must be the same size??

 

 

Yes, very helpful.

Best,

Paul

**Comment by palmcorp** [comment]
Hi Glenn,

Your advice appreciated.  Will go over the label files and make sure there are no Unicode characters hidden in the text.

Best,

Paul

**Comment by glenn-jocher** [comment]
@palmcorp hi Glenn,

Thanks for the advice. I'll review the label files to ensure there are no hidden Unicode characters or formatting issues.

**Comment by ryouchinsa** [comment]
Hi @palmcorp, 

If some keypoints are not visible, you have to label those keypoints as invisible.
So that the number of keypoints can be the same.

Each keypoint has a visibility flag v defined as
v=0: not labeled, 
v=1: labeled but not visible, and 
v=2: labeled and visible. 

Keypoint Detection
https://cocodataset.org/#format-data

**Comment by palmcorp** [comment]
Hi Glen,

Thanks for your excellent advice, but the problem is still there. Not sure where to look now.  

1.      Wrote program to scan for non- ASCII characters in the label files and none detected.

2.      Attached is a short report of the labels used for training.  They all look fine to me.  All have the same format.

3.      Attached is also the data.yml  file.

Any ideas where to look?

Best,

Paul

**Comment by palmcorp** [comment]
Hi Ryo,

Thanks for looking into this problem.  Attached is a list of all of the labels used for training and the data.yml file.  The labels look pretty consistent – all were generated by CVAT as COCO 1.0 labels and converted to Yolo labels using COCO2YOLO.  LMK if you see any issues.

Best,

Paul

***@***.***

**Comment by ryouchinsa** [comment]
Hi @palmcorp, 

Thanks for showing label files. 
To be honest, just looking at those label files, I cannot find the exact problem in your label files.
If the number of keypoints and the dimension is consistent with [5, 3], I think you can train those label files with YOLOv8.
