### ISSUE TITLE
for custom data training, how to specify the model scale 

### ISSUE THREAD

**Issue by madinwei** [ultralytics/ultralytics#1975]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have modified the class number to two classes only from the 80 classes. and every time I train the training is always with model scale= 'n', I don't know from where I should pass the model scale information. 

### Additional

I tried to use the model scale in the name of the .ymal file, however, it always rases a file not found Error.

**Comment by Laughing-q** [comment]
@madinwei can you share you training command?

**Comment by madinwei** [comment]
@Laughing-q , Thank you for your response, here it is:
```python
from ultralytics import YOLO

# Load a model
model = YOLO('custom-seg.yaml').load('y8best4-12.pt')  # build from YAML and transfer weights

# Train the model
model.train(data='custom.yaml', epochs=500, imgsz=640, batch=-1, optimizer='AdamW')

```

**Comment by Laughing-q** [comment]
@madinwei fro current logic, you have to include `yolov8` and `scale` in your custom model name.
like `yolov8n-seg-custom.yaml`
[https://github.com/ultralytics/ultralytics/blob/e5cb35edfc3bbc9d7d7db8a6042778a751f0e39e/ultralytics/nn/tasks.py#L528-L531](https://github.com/ultralytics/ultralytics/blob/e5cb35edfc3bbc9d7d7db8a6042778a751f0e39e/ultralytics/nn/tasks.py#L528-L531)

**Comment by madinwei** [comment]
@Laughing-q , I am very grateful for your help. now it works ^_^. I will close this issue then.

**Comment by glenn-jocher** [comment]
You're welcome @madinwei :) I'm glad to hear that the solution I provided has helped you. If you have any further questions or issues, feel free to ask, or you can also visit the Ultralytics YOLOv8 Docs for more information.
