### ISSUE TITLE
Tensorflow module path

### ISSUE THREAD

**Issue by hardikdava** [ultralytics/ultralytics#198]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello @glenn-jocher  @AyushExel, I can help with tensorflow export. Can you tell me where should I create python file for it?

**Comment by AyushExel** [comment]
You can start working in nn.modules.tf ..we can change it later if we need to

**Comment by glenn-jocher** [comment]
@hardikdava we've been trying to use onnx2tf for TensorFlow export with mixed success. I think it's enabled for SavedModel  but it requires additional dependencies and may not always work correctly. See:
https://github.com/ultralytics/ultralytics/blob/dba3f178849692a13f3c43e81572255b1ece7da9/ultralytics/yolo/engine/exporter.py#L453-L485

**Comment by hardikdava** [comment]
@glenn-jocher I was able to use onnx2tf for tensorflow saved_model, tflite and keras model successfully. But I will test it with every models and submit PR soon.
