### ISSUE TITLE
Running ultralyticis with docker container in Jetson with GPU

### ISSUE THREAD

**Issue by aurelm95** [ultralytics/ultralytics#1981]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I want to run yolov8 with docker in my jetson device to see its performance. The problem is that when I run the image `ultralytics/ultralytics:latest-arm64` and I run the following python code

```py
import torch
torch.cuda.is_available()
```
shows `False`.

### Additional

I have tried to run the docker image with the flag `--gpus all`but did not succeed.

According to [this post](https://forums.developer.nvidia.com/t/how-to-enable-gpu-in-custom-docker-image/192881), in order to use the jetson GPU in a container, it must be created on top of [this base image](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-base)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by aurelm95** [comment]
@glenn-jocher Thanks for the info. I ended up using this image: nvcr.io/nvidia/l4t-pytorch:r35.2.1-pth2.0-py3 and then cloning there this repo and worked as expected so far. 

Thank you!

**Comment by glenn-jocher** [comment]
@aurelm95 great to hear that you found a solution that works for you using the `nvcr.io/nvidia/l4t-pytorch` container. That container is based on Nvidia’s Linux for Tegra (L4T) which is the underlying OS for Jetson devices. It is preloaded with CUDA, cuDNN, PyTorch and other tools. You can then install YOLOv8 or other models you would like to use on top of this container to leverage the GPU for improved performance. Don't hesitate to reach out if you have any other questions in the future.

**Comment by blackCmd** [comment]
@aurelm95 
Hi, 
What is your Jetson model ?

**Comment by glenn-jocher** [comment]
Hi @blackCmd,
Regarding the error you're encountering with the `ultralytics/ultralytics:latest-arm64` Docker image, it seems that this image is intended for ARM inference rather than GPU inference. To use the Jetson GPU in a container, you can try using the `nvcr.io/nvidia/l4t-pytorch:r35.2.1-pth2.0-py3` container which is based on Nvidia's Linux for Tegra (L4T) and comes preloaded with CUDA, cuDNN, PyTorch, and other tools.

You mentioned that installing this container and cloning the YOLOv8 repo worked well for you on your Jetson device. That's great to hear! Jetson Nano with Jetpack 4.6.x is known to be incompatible with PyTorch 1.11, so it's important to make sure you're using a compatible version.

If you have any further questions or need any assistance, feel free to ask. We're here to help!

**Comment by aurelm95** [comment]
@blackCmd Yep, sadly jetpack 4.6 is not compatible with the ultralytics docker image. Some how, nvidia has deprecated the jetson nano because you cant even reflash the nano with a newer jetpack. :(

**Comment by glenn-jocher** [comment]
Hi @aurelm95,

I understand your frustration, and thank you for bringing this to our attention. Unfortunately, compatibility issues can occur as software evolves over time. As you've found, JetPack 4.6 indeed has some conflicts with the current version of the Ultralytics Docker image for YOLOv8.

In terms of the Jetson Nano not being able to be reflashed with a newer JetPack, it's something that lies outside the control of the development team of YOLOv8 and Ultralytics. The changing requirements and dependencies of computing environments including hardware, operating systems, drivers and development frameworks need to be managed by the device manufacturers, in this case, NVIDIA.

We appreciate your patience and understanding in this matter, and we definitely empathize with your situation dealing with these software compatibility challenges.

We will continue to do our best in developing, maintaining, and improving YOLOv8 such that it works with as many environments and configurations as possible. If there are any changes or updates that might help in your situation, we'll try to keep the community informed.

Stay tuned and thank you for your support of YOLOv8.

Best,
Glenn Jocher

**Comment by Ahelsamahy** [comment]
Hi @aurelm95, I had the same problem with jetson nano. I managed to create this [docker image](https://hub.docker.com/layers/mwlvdev/jetson-nano-ubuntu/bionic-torch1.11-cp38-cuda10.2/images/sha256-21fb42c51a98ca251e24169dbb53ebc011d96364a10dbe8b615c957f2472ceca?context=explore) and yolov8 is working fine on it.

I attached a screenshot for the speed test on it 
![image](https://github.com/ultralytics/ultralytics/assets/10195309/f47dc77e-c64f-4e99-ac57-a2b894c040b2)

**Comment by jasonlytehouse** [comment]
You can use this [repo](https://github.com/jayfalls/jetson_nano_ubuntu20_docker/tree/main) I created which provides a docker image with python3.11 to run any ultralytics yolo models on Jetson Nano with torch gpu or tensorrt

You can expect about 60-70ms average end-to-end with yolov8n and yolov10n on the Jetson with Python3.11

**Comment by Ahelsamahy** [comment]
Hi @jasonlytehouse, I checked your repo, and it is quite impressive. However, I have made a PR that runs Yolov8 on python 3.8 and it have been accepted. You can see it here https://github.com/ultralytics/ultralytics/pull/13100#event-13108826788. In includes the tests that I have made

**Comment by jasonlytehouse** [comment]
That's awesome, I'm not trying to downplay any other work and more native support is always great

Just want to bring awareness so others don't have to struggle the same way I did as python3.11 is a hard requirement for my needs and I'm sure others need something other than 3.8

I think all contributions are great and love that the community is keeping the Jetson Nano alive

**Comment by glenn-jocher** [comment]
Hi @jasonlytehouse,

Thank you for your thoughtful comment and for sharing your solution. It's fantastic to see the community actively contributing and supporting each other, especially when it comes to keeping the Jetson Nano relevant and functional.

Your work with Python 3.11 is indeed valuable, and it's great to have options for different Python versions to cater to various needs. We appreciate your effort in making these resources available to others who might face similar challenges.

If anyone else has specific requirements or faces issues, please feel free to share your experiences and solutions. The collaborative spirit here is what makes our community strong and resourceful.

Keep up the great work, everyone! 🚀
