### ISSUE TITLE
Object detection in image and whole image classification using single yolo model

### ISSUE THREAD

**Issue by kumarneeraj2005** [ultralytics/ultralytics#1984]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to detect 5 objects inside an image and also need to classify the whole image into 2 classes for example  - detect persons inside a picture and classify an entire image as a day or night.

How do you annotate images for the above use case, please guide.

currently, I am using the following and getting error.
the last column represents two classes of images -
100.png 0.0123 0.373 0.488 0.0837 0.0300 1
31.png 0.0234 0.467 0.423 0.1860 0.0686 0

**Comment by glenn-jocher** [comment]
@kumarneeraj2005 these are two different tasks, so you would define Classify and Detect versions of your dataset and then train one model on each. See:

https://docs.ultralytics.com/tasks/classify
https://docs.ultralytics.com/tasks/detect
