### ISSUE TITLE
Questions about train imgz and export imgz

### ISSUE THREAD

**Issue by Monday-Leo** [ultralytics/ultralytics#1986]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thanks for your great work!
1. I train the model by setting the imgs 640*640. Then i export the onnx model by setting the imgs 320*320.
2. I train the model by setting the imgs 320*320. Then i export the onnx model whose size is the same as training.
My question is whether the Map of the two exported models is same? Do models with different input sizes need to be retrained?

**Comment by glenn-jocher** [comment]
@Monday-Leo thanks for your question! YOLOv8 should be able to handle multiple image resolutions up to a certain point. However, expect  performance drop if the testing resolution is different from the training resolution. In this case, you have reduced the image resolution from 640x640 to 320x320 for inference. If the new input size is too small, smaller targets may become too difficult to detect, leading to a reduction in performance or Map loss. It's best to keep the testing resolution consistent with your training resolution to get consistent Map results.
