### ISSUE TITLE
MLflow Integration

### ISSUE THREAD

**Issue by mmortazavi** [ultralytics/ultralytics#199]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Is integrating MLflow integration is part of near-future roadmap? I recall there was a major PR in Yolov5 that was to be merged, but never did, I hope MLflow can also be integrated into Yolov8 soon. Great work and many thanks!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by luigisaetta** [comment]
well, I think it is an important feature, it would add a lot of value to Yolo since many teams prefer to use MLFlow in their environment to track experiments.

**Comment by mucozcan** [comment]
I believe it can be integrated using [callbacks](https://github.com/ultralytics/ultralytics/tree/main/ultralytics/yolo/utils/callbacks). I`d like to help with it @glenn-jocher @AyushExel
