### ISSUE TITLE
Custom yaml file does not exist

### ISSUE THREAD

**Issue by edehino** [ultralytics/ultralytics#1992]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

My folder structure is:

```
yolov8
  |  
   ultralytics
     |
      {some files}
      ultralytics
         |
         assets
         .
         .
         .
         datasets
            |
            custom.yaml
```

I am trying to run `yolo detect train data=custom.yaml epochs=2` but error occurred that the yaml file does not exist.
`raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
RuntimeError: Dataset 'custom.yaml' error  'custom.yaml' does not exist`.

I invoke the yolo command on .../yolov8/ultralytics path but above error occurred which implies that the dataset path is not pointing on the ../ultralytics/ultralytics/datasets path.

I already ran the same yolo command before and training process was successful. I also updated the ultralytics package using `pip install -U ultralytics` 

Anyone who can help me with this?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@edehino it works fine to me and here's my folder structure:
```
ultralytics              # there is also where I run the command
├── ultralytics
│   ├── datasets
│   │   ├── custom.yaml
```
```bash
yolo detect train data=custom.yaml epochs=2
```

**Comment by AyushExel** [comment]
One more thing to note - you don't have to have the custom.yaml inside the ultralytics folder. It can be anywhere and you can simple pass its relative path - `yolo data=path/to/data`

**Comment by Laughing-q** [comment]
@aiakash simply passing the absolute path of your data.yaml should also work.
