### ISSUE TITLE
How to deploy yolov8 model for object detection in openwrt  environment ?

### ISSUE THREAD

**Issue by xingyuezhiyun** [ultralytics/ultralytics#1993]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to deploy yolov8 model for object detection in openwrt  environment ?
i try to package yolov8 project as whl file, but it cannot run in openwrt env, the error is loss gcc or gfortran compile
so, there is good way for deploy this model in flushbonading env ? wait for your help, thanks~

**Comment by glenn-jocher** [comment]
@xingyuezhiyun you are welcome, and I'm glad to hear that you found MNN to be a viable solution for your use case. Cross-compiling Python code can be a complex task, especially on embedded devices such as OpenWrt. It's great to see that you have found an alternative solution that meets your requirements. If you come across any further issues or questions related to Ultralytics YOLOv8, please don't hesitate to reach out.

**Comment by xingyuezhiyun** [comment]
thanks a lot, i am glad to use yolov8 series, it's the best. and i try to improve my program skill and konwledge so that i can jion the cv domain one day. if you interest me, send me email and be a friend , there is my email ywb10.8@qq.com

**Comment by glenn-jocher** [comment]
@xingyuezhiyun I'm glad to hear that you find YOLOv8 to be a valuable resource for your computer vision project. It's great that you are also working on improving your programming skills and knowledge in this domain. Collaborating and expanding your network can certainly help you grow in these areas. However, as a Github support representative, my primary focus is to provide assistance related to Ultralytics YOLOv8 issues and queries. If you have any such questions, please don't hesitate to open a Github issue or discussion thread, and I'll do my best to help you out.
