### ISSUE TITLE
cfg=default or custom_cfg.yaml not working ,not able to train custom model

### ISSUE THREAD

**Issue by aiakash** [ultralytics/ultralytics#2000]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

```
 yolo detect train data=coco128.yaml cfg=default.yaml

```

if i remove cfg=default.yaml its working, but i want to pass my default cfg parametrs to train model

im getting error, also this

```

        Where   TASK (optional) is one of ('detect', 'segment', 'classify', 'pose')
                MODE (required) is one of ('train', 'val', 'predict', 'export', 'track', 'benchmark')
                ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
                    See all ARGS at https://docs.ultralytics.com/usage/cfg or with 'yolo cfg'

    1. Train a detection model for 10 epochs with an initial learning_rate of 0.01
        yolo train data=coco128.yaml model=yolov8n.pt epochs=10 lr0=0.01

    2. Predict a YouTube video using a pretrained segmentation model at image size 320:
        yolo predict model=yolov8n-seg.pt source='https://youtu.be/Zgi9g1ksQHc' imgsz=320

    3. Val a pretrained detection model at batch-size 1 and image size 640:
        yolo val model=yolov8n.pt data=coco128.yaml batch=1 imgsz=640

    4. Export a YOLOv8n classification model to ONNX format at image size 224 by 128 (no TASK required)
        yolo export model=yolov8n-cls.pt format=onnx imgsz=224,128

    5. Run special commands:
        yolo help
        yolo checks
        yolo version
        yolo settings
        yolo copy-cfg
        yolo cfg

    Docs: https://docs.ultralytics.com
    Community: https://community.ultralytics.com
    GitHub: https://github.com/ultralytics/ultralytics



```

### Environment

OS-Ubantu 
ultralytics-8.0.74

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@aiakash it seems that you are encountering an error when passing your own default cfg parameters to train the model using YOLOv8. You mentioned that the command works when you remove the `cfg=default.yaml` parameter but you want to use your own default cfg parameters. Have you tried specifying the path to your config file instead of passing `default.yaml` as an argument? Additionally, you can refer to the Ultralytics YOLOv8 documentation at https://docs.ultralytics.com for more information on how to properly pass arguments when training, validating, or predicting with YOLOv8.

**Comment by Laughing-q** [comment]
@aiakash can you provide your full error log? I can't see what error you encountered from you msg.

**Comment by chirag-adagrad** [comment]
@aiakash is there a resolution to this issue, I'm still facing this bug

**Comment by sjy0322** [comment]
@chirag-adagrad If you use it as a package command, it doesn't seem to be applied by loading the code from the package. Are you not using train.py by any chance?

**Comment by chirag-adagrad** [comment]
@sjy0322 no, I'm using the CLI command. @aiakash I've changed the deafult.yaml, but it still doesn't work

**Comment by glenn-jocher** [comment]
Hello @aiakash, 

Thank you for your patience and I apologize for the inconvenience caused. Based on what you've described, it sounds like you're experiencing an issue with your particular setup.

When using the CLI command, the configuration file is crucial. If you have correctly edited the `default.yaml` but still encounter issues, it might be worthwhile to double-check the modifications made in this file. Ensure all parameters in this file match the ones you want to use for your model to avoid conflict.

Additionally, ensure that you're specifying the correct path to your `default.yaml` file in your CLI command, and that the values provided in the .yaml are in the correct format for each specific parameter field.

Lastly, ensure that your Ultralytics version is up to date. If the issue persists after these checks, it may be helpful to monitor the output logs for any errors or warnings that might shed light on potential issues with your setup.

I appreciate your understanding and commitment towards resolving this issue. Thank you for your continued support of the Ultralytics YOLOv8 project.

**Comment by mczhao1977** [comment]
Recently I encountered same problem using Ultralytics 8.3.161 with yolov11s model. 
Symptom
yolo detect train data=coco128.yaml cfg=default.yaml prints warnings like
WARNING ⚠️ 'mode' argument is missing or ignores data.

The reson is in the CLI source (ultralytics/cfg/__init__.py::entrypoint()), the parser replaces all previously collected overrides as soon as it meets cfg=….
Anything specified before cfg= is therefore wiped out.
Corrected command (cfg first):
yolo cfg=default.yaml detect train data=coco128.yaml
—or, if you prefer explicit key=value syntax—
yolo cfg=default.yaml task=detect mode=train data=coco128.yaml
Placing cfg= first preserves every other argument and eliminates the “missing mode/model/data” warnings. Hope this saves the next person some time!

**Comment by glenn-jocher** [comment]
@mczhao1977 excellent analysis! You've identified the root cause perfectly. The CLI parser does indeed replace all previously collected overrides when it encounters `cfg=`, so the argument order matters.

For anyone else encountering this issue, the solution is to place `cfg=` first in your command:

```bash
yolo cfg=default.yaml detect train data=coco128.yaml epochs=10 lr0=0.01
```

This ensures your custom configuration file is loaded first, then any additional arguments override those defaults as expected. Thank you for sharing this insight with the community!

**Comment by hibikiyoyo** [comment]
@glenn-jocher I tried but wasn’t successful when placing the cfg parameter at the front. I realized that this cfg conflicts with both the CLI command and the parameter that can be passed in through default.yaml. This might be a mistake from the developer for using the same name.

<img width="1307" height="1391" alt="Image" src="https://github.com/user-attachments/assets/47f46766-fd7e-4e58-9445-7d6f2b9bc2a7" />


I used yolo copy-cfg and then ended up overriding it directly in the default_copy.yaml file

<img width="1909" height="769" alt="Image" src="https://github.com/user-attachments/assets/691c0d9b-9906-4ed4-a735-51a65cb6a5ec" />

**Comment by glenn-jocher** [comment]
Thanks for the details—there isn’t a naming conflict here: the CLI treats `cfg=...` as a special loader and ignores any `cfg:` key inside the YAML, so please remove that line from your `default_copy.yaml` and keep `cfg=` first, e.g.:

```bash
yolo cfg=default_copy.yaml detect train data=coco128.yaml
```

This flow is documented under [Overriding Default Config File](https://docs.ultralytics.com/usage/cli/#overriding-default-config-file); if it still fails, open a new issue (this one is closed/stale) and include your full command, the YAML, and the output of `yolo checks`.
