### ISSUE TITLE
Why i load a model , still download from github?

### ISSUE THREAD

**Issue by lyj0309** [ultralytics/ultralytics#2001]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/50474995/231722340-450fe2fa-a062-46eb-8295-5205d550594c.png)

**Comment by glenn-jocher** [comment]
@lyj0309, that warning appears to be an indicative message that simply reminds the user that unused parameters may have been passed to the `detect` method of `yolo` object. It should not impact the inference results.

Feel free to submit a pull request with a fix, but it is not required for YOLOv8 to function properly. Hope this clears up any confusion!

**Comment by Laughing-q** [comment]
@lyj0309 hi, internally we use a yolov8n model to check the feasibility of amp so it'll download yolov8n.pt if you don't have one locally.

**Comment by lyj0309** [comment]
> @lyj0309 hi, internally we use a yolov8n model to check the feasibility of amp so it'll download yolov8n.pt if you don't have one locally.

Get it ,thanks.

**Comment by glenn-jocher** [comment]
@lyj0309, the response explains that internally the YOLOv8 model uses a particular model named YOLOv8n to check the feasibility of Automatic Mixed Precision (AMP). If the YOLOv8n pre-trained model is not available on your local system then the code will download it automatically. This process helps to ensure that the AMP feature is working as expected. Please feel free to reach out to us if you have any further questions or support requests.
