### ISSUE TITLE
Normalized boxes not between [0, 1]

### ISSUE THREAD

**Issue by Yusepp** [ultralytics/ultralytics#2005]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I'm using 1280x640 images. Using xyxyn format gives me bounding boxes that are not normalized (between 0 and 1).

For instance i obtain:
```
array([[     129.33,      20.531,      203.67,      25.531]
```

Is this suposed to be the expected behavior of xyxyn? or am i missing something?

Thank you.

### Minimal Reproducible Example

```
# Define a function to detect faces using YOLO
def detect_faces_fast(model, batch):
    # Use YOLO to predict bounding boxes and confidences for each image in the batch
    results = model.predict(batch, stream=False, verbose=False, device=0, half=True) #half=True
    
    # Extract bounding boxes and confidences from the YOLO results
    boxes, confidences = [result.boxes.xyxyn.cpu().numpy() for result in results], [result.boxes.conf.cpu().numpy() for result in results]
    
    return boxes, confidences
`
``

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@Yusepp I'm not able to reproduce the issue. boxes.xyxyn looks good to me.
![image](https://user-images.githubusercontent.com/61612323/231927873-00d799c3-6f18-4d0d-aa8d-4e28eb6a01ce.png)
