### ISSUE TITLE
Image preprocessing and results postprocessing

### ISSUE THREAD

**Issue by mazatov** [ultralytics/ultralytics#2009]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey guys, I was wondering about different preprocessing and postprocessing steps that must be happening behind the scenes. 

I trained my model on my own dataset and afterward tried predicting using the trained model using the code snippet in your docs. It all worked like a charm but I did wonder what happens behind the scenes and if I need to do something specifically for my task. 

1) Pre-processing. Does the model handle all the preprocessing steps by itself. Like resizing the image, padding it to appropriate size, etc. Does it save resized/padded image somewhere so I can take a look at it? 

2) Post-processing. In previous Yolo models I used to play with detection probability threshold as well NMS IOU threshold for optimal results. Where can I see where those thresholds are set up? Or are they optimized per task? I have no idea what they are set to right now. 

```
inputs = [img, img]  # list of numpy arrays
results = model(inputs)  # list of Results objects

for result in results:
    boxes = result.boxes  # Boxes object for bbox outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    probs = result.probs  # Class probabilities for classification outputs

```

**Comment by glenn-jocher** [comment]
@mazatov thanks for reaching out! YOLOv8 handles most of the preprocessing steps internally, such as resizing the image and padding it to the appropriate size. However, you can specify custom preprocessing steps using the `preprocess` argument in the `Detector` class. As for post-processing, the detection probability and NMS IOU thresholds are set internally and optimized per task, but you can adjust them using the `conf` and `iou` arguments respectively in the `Detector` class. You can also set these thresholds manually using the `detect` function in the `models/ensemble.py` module. You can take a look at the source code for more information, and feel free to reach out if you have any more questions!

**Comment by Laughing-q** [comment]
@mazatov
> 1. Pre-processing. Does the model handle all the preprocessing steps by itself. Like resizing the image, padding it to appropriate size, etc. Does it save resized/padded image somewhere so I can take a look at it?

yes images are resized and padded automatically inside the code, but we do not save it.

> 2. Post-processing. In previous Yolo models I used to play with detection probability threshold as well NMS IOU threshold for optimal results. Where can I see where those thresholds are set up? Or are they optimized per task? I have no idea what they are set to right now.

you can pass `conf` and `iou` to control the confidence score threshold and nms iou threshold. More args please refer to our docs. [https://docs.ultralytics.com/usage/cfg/#predict](https://docs.ultralytics.com/usage/cfg/#predict)
