### ISSUE TITLE
Problems with multi GPU usage

### ISSUE THREAD

**Issue by m-mehdi-git** [ultralytics/ultralytics#2023]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Multi-GPU

### Bug

Ultralytics YOLOv8.0.75 🚀 Python-3.11.2 torch-2.0.0+cu117 CUDA:0 (Tesla V100-PCIE-16GB, 16160MiB)
                                                           CUDA:1 (Tesla V100-PCIE-16GB, 16160MiB)
                                                           CUDA:2 (Tesla V100-PCIE-16GB, 16160MiB)
                                                           CUDA:3 (Tesla V100-PCIE-16GB, 16160MiB)
yolo/engine/trainer: task=detect, mode=train, model=last.pt, data=./data/custom_product_empty_data.yaml, epochs=200, patience=50, batch=32, imgsz=640, save=True, save_period=-1, cache=False, device=(0, 1, 2, 3), workers=8, project=yolov8_product_empty_detection, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=yolov8_product_empty_detection/train13
Running DDP command ['/anaconda/envs/yolov8/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '47163', '/home/azureuser/.config/Ultralytics/DDP/_temp_121evcaj139957781718992.py', 'task=detect', 'mode=train', 'model=last.pt', 'data=./data/custom_product_empty_data.yaml', 'epochs=200', 'patience=50', 'batch=32', 'imgsz=640', 'save=True', 'save_period=-1', 'cache=False', 'device=(0, 1, 2, 3)', 'workers=8', 'project=yolov8_product_empty_detection', 'name=None', 'exist_ok=False', 'pretrained=False', 'optimizer=SGD', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'image_weights=False', 'rect=False', 'cos_lr=False', 'close_mosaic=0', 'resume=False', 'amp=True', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'save_hybrid=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'source=None', 'show=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'show_labels=True', 'show_conf=True', 'vid_stride=1', 'line_thickness=3', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'boxes=True', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=False', 'opset=None', 'workspace=4', 'nms=False', 'lr0=0.01', 'lrf=0.01', 'momentum=0.937', 'weight_decay=0.0005', 'warmup_epochs=3.0', 'warmup_momentum=0.8', 'warmup_bias_lr=0.1', 'box=7.5', 'cls=0.5', 'dfl=1.5', 'pose=12.0', 'kobj=1.0', 'label_smoothing=0.0', 'nbs=64', 'hsv_h=0.015', 'hsv_s=0.7', 'hsv_v=0.4', 'degrees=0.0', 'translate=0.1', 'scale=0.5', 'shear=0.0', 'perspective=0.0', 'flipud=0.0', 'fliplr=0.5', 'mosaic=1.0', 'mixup=0.0', 'copy_paste=0.0', 'cfg=None', 'v5loader=False', 'tracker=botsort.yaml']
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
DDP settings: RANK 0, WORLD_SIZE 4, DEVICE cuda:0
Transferred 595/595 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
WARNING ⚠️ 'Boxes.boxes' is deprecated. Use 'Boxes.data' instead.
WARNING ⚠️ 'Boxes.boxes' is deprecated. Use 'Boxes.data' instead.
AMP: checks passed ✅
optimizer: SGD(lr=0.01) with parameter groups 97 weight(decay=0.0), 104 weight(decay=0.0005), 103 bias
train: Scanning /mnt/batch/tasks/shared/LS_root/mounts/clusters/weryou-4v100-16g/code/Users/m.mejdoub/ultralytics/data/product-empty/train/labels.cache... 3160 images, 2 backgrounds, 0
val: Scanning /mnt/batch/tasks/shared/LS_root/mounts/clusters/weryou-4v100-16g/code/Users/m.mejdoub/ultralytics/data/product-empty/val/labels.cache... 498 images, 0 backgrounds, 0 corr
Plotting labels to yolov8_product_empty_detection/train13/labels.jpg... 
Image sizes 640 train, 640 val
Using 24 dataloader workers
Logging results to yolov8_product_empty_detection/train13
Starting training for 200 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    150/200      10.9G     0.4559     0.2307     0.8026       1393        640: 100%|██████████| 99/99 [01:57<00:00,  1.19s/it]F
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 32/32 [00:16<00:00,  1.99it/s]
                   all        498      70099      0.935      0.907      0.941       0.82

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    151/200      10.4G     0.4635     0.2344      0.805       1578        640: 100%|██████████| 99/99 [01:52<00:00,  1.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 32/32 [00:16<00:00,  1.93it/s]
                   all        498      70099      0.937      0.905      0.941       0.82

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    152/200      12.1G      0.463      0.234     0.8059       1762        640: 100%|██████████| 99/99 [01:54<00:00,  1.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 32/32 [00:15<00:00,  2.01it/s]
                   all        498      70099      0.934      0.905      0.941       0.82

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    153/200      9.87G     0.4639     0.2342     0.8053       1469        640: 100%|██████████| 99/99 [01:53<00:00,  1.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 32/32 [00:16<00:00,  1.94it/s]
                   all        498      70099      0.937      0.904      0.941      0.821

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    154/200      12.1G     0.4608     0.2329     0.8041       1240        640: 100%|██████████| 99/99 [01:53<00:00,  1.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 32/32 [00:16<00:00,  1.97it/s]
                   all        498      70099      0.942      0.898      0.941       0.82

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    155/200      9.48G     0.4542     0.2311     0.8053       1180        640: 100%|██████████| 99/99 [01:55<00:00,  1.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 32/32 [00:15<00:00,  2.07it/s]
                   all        498      70099      0.944      0.898      0.942       0.82

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    156/200      11.4G     0.4623     0.2327      0.804       1125        640: 100%|██████████| 99/99 [01:53<00:00,  1.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 32/32 [00:16<00:00,  1.96it/s]
                   all        498      70099       0.94        0.9      0.941      0.819

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    157/200      10.8G     0.4653     0.2329     0.8042        884        640: 100%|██████████| 99/99 [01:53<00:00,  1.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 32/32 [00:17<00:00,  1.86it/s]
                   all        498      70099      0.946      0.895      0.942      0.821

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    158/200       9.9G     0.4658     0.2352     0.8046       1491        640: 100%|██████████| 99/99 [01:52<00:00,  1.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 32/32 [00:16<00:00,  1.89it/s]
                   all        498      70099      0.944      0.896      0.942      0.821

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    159/200      9.13G     0.4589      0.231     0.8039        604        640: 100%|██████████| 99/99 [01:52<00:00,  1.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 32/32 [00:16<00:00,  1.93it/s]
                   all        498      70099       0.95      0.893      0.943      0.821

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    160/200      12.5G     0.4557     0.2302     0.8037       2354        640:  88%|████████▊ | 87/99 [01:37<00:15,  1.32s/it]

[E ProcessGroupNCCL.cpp:828] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=10792, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1800764 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:828] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=10792, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1800802 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:828] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=10792, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1800804 milliseconds before timing out.
Traceback (most recent call last):
  File "/home/azureuser/.config/Ultralytics/DDP/_temp_121evcaj139957781718992.py", line 6, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/azureuser/.config/Ultralytics/DDP/_temp_121evcaj139957781718992.py", line 6, in <module>
  File "/home/azureuser/.config/Ultralytics/DDP/_temp_121evcaj139957781718992.py", line 6, in <module>
    trainer.train()
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/ultralytics/yolo/engine/trainer.py", line 190, in train
    trainer.train()
    trainer.train()
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/ultralytics/yolo/engine/trainer.py", line 190, in train
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/ultralytics/yolo/engine/trainer.py", line 190, in train
    self._do_train(world_size)
    self._do_train(world_size)
    self._do_train(world_size)
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/ultralytics/yolo/engine/trainer.py", line 326, in _do_train
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/ultralytics/yolo/engine/trainer.py", line 326, in _do_train
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/ultralytics/yolo/engine/trainer.py", line 326, in _do_train
    self.scaler.scale(self.loss).backward()
      File "/anaconda/envs/yolov8/lib/python3.11/site-packages/torch/_tensor.py", line 487, in backward
self.scaler.scale(self.loss).backward()
    self.scaler.scale(self.loss).backward()
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/torch/_tensor.py", line 487, in backward
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(    
torch.autograd.backward(    
torch.autograd.backward(
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/torch/autograd/__init__.py", line 200, in backward
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/torch/autograd/__init__.py", line 200, in backward
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/torch/autograd/__init__.py", line 200, in backward

============================================================

Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

RuntimeErrorRuntimeError: : NCCL communicator was aborted on rank 1.  Original reason for failure was: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=10792, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1800764 milliseconds before timing out.RuntimeErrorNCCL communicator was aborted on rank 2.  Original reason for failure was: [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=10792, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1800804 milliseconds before timing out.
NCCL communicator was aborted on rank 3.  Original reason for failure was: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=10792, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1800802 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:455] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:455] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:455] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 15270 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 1 (pid: 15271) of binary: /anaconda/envs/yolov8/bin/python

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

/home/azureuser/.config/Ultralytics/DDP/_temp_121evcaj139957781718992.py FAILED
----------------
Failures:
[1]:
  time      : 2023-04-14_09:57:32
  host      : localhost
  rank      : 2 (local_rank: 2)
  exitcode  : -6 (pid: 15272)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 15272
[2]:
  time      : 2023-04-14_09:57:32
  host      : localhost
  rank      : 3 (local_rank: 3)
  exitcode  : -6 (pid: 15273)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 15273
----------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-14_09:57:32
  host      : localhost
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 15271)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 15271
-------------------

Traceback (most recent call last):
  File "/anaconda/envs/yolov8/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/ultralytics/yolo/cfg/__init__.py", line 391, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/ultralytics/yolo/engine/model.py", line 367, in train
    self.trainer.train()
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/ultralytics/yolo/engine/trainer.py", line 186, in train
    raise e
  File "/anaconda/envs/yolov8/lib/python3.11/site-packages/ultralytics/yolo/engine/trainer.py", line 184, in train
    subprocess.run(cmd, check=True)
  File "/anaconda/envs/yolov8/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/anaconda/envs/yolov8/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '47163', '/home/azureuser/.config/Ultralytics/DDP/_temp_121evcaj139957781718992.py', 'task=detect', 'mode=train', 'model=last.pt', 'data=./data/custom_product_empty_data.yaml', 'epochs=200', 'patience=50', 'batch=32', 'imgsz=640', 'save=True', 'save_period=-1', 'cache=False', 'device=(0, 1, 2, 3)', 'workers=8', 'project=yolov8_product_empty_detection', 'name=None', 'exist_ok=False', 'pretrained=False', 'optimizer=SGD', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'image_weights=False', 'rect=False', 'cos_lr=False', 'close_mosaic=0', 'resume=False', 'amp=True', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'save_hybrid=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'source=None', 'show=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'show_labels=True', 'show_conf=True', 'vid_stride=1', 'line_thickness=3', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'boxes=True', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=False', 'opset=None', 'workspace=4', 'nms=False', 'lr0=0.01', 'lrf=0.01', 'momentum=0.937', 'weight_decay=0.0005', 'warmup_epochs=3.0', 'warmup_momentum=0.8', 'warmup_bias_lr=0.1', 'box=7.5', 'cls=0.5', 'dfl=1.5', 'pose=12.0', 'kobj=1.0', 'label_smoothing=0.0', 'nbs=64', 'hsv_h=0.015', 'hsv_s=0.7', 'hsv_v=0.4', 'degrees=0.0', 'translate=0.1', 'scale=0.5', 'shear=0.0', 'perspective=0.0', 'flipud=0.0', 'fliplr=0.5', 'mosaic=1.0', 'mixup=0.0', 'copy_paste=0.0', 'cfg=None', 'v5loader=False', 'tracker=botsort.yaml']' returned non-zero exit status 1.

### Environment

Ultralytics YOLOv8.0.75 🚀 Python-3.11.2 torch-2.0.0+cu117 CUDA:0 (Tesla V100-PCIE-16GB, 16160MiB)

### Minimal Reproducible Example

yolo task=detect mode=train data=./data/mycustom_data.yaml model=yolov8l.pt epochs=200 imgsz=640 batch=32 save=true device=0,1,2,3
or when resuming
yolo task=detect mode=train data=./data/mycustom_data.yaml model=last.pt resume epochs=200 imgsz=640 batch=32 save=true device=0,1,2,3

### Additional

on multi GPU after some epochs of training it crashes. i'm obliged to resume multiple times

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@m-mehdi-git 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃
