### ISSUE TITLE
i

### ISSUE THREAD

**Issue by anbriel** [ultralytics/ultralytics#2027]

**Comment by pderrenger** [comment]
@anbriel it seems like there is a TypeError occurring during the training process. This issue might be related to the recent changes in the PyTorch library.

To resolve this, I recommend updating `torch` and `torchvision` to the latest version. You can achieve this by running the following commands in your Python environment:

```bash
pip install torch torchvision --upgrade
```

After updating the packages, attempt to train the YOLOv8 model again and check if the issue has been resolved. If the problem persists, please let me know, and we can explore other potential solutions.
