### ISSUE TITLE
Will YOLO provide the rotation angle for bounding box? Now rotation angle is not provided by YOLO. 

### ISSUE THREAD

**Issue by frabob2017** [ultralytics/ultralytics#2033]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Will YOLO provide the rotation angle for bounding box? Now rotation angle is not provided by YOLO.  If I want to label a oblique and long lesion, if the bound box can rotate to accommodate it, it will be great.  Otherwise, I will rotate the images to make this oblique and long lesion to be horizontal or vertical, it increase label work a lot.

**Comment by frabob2017** [comment]
I also feel confused. during the data augmentation, YOLO allow images to rotate. I believe that bounding box will also rotate. How does YOLO handle this rotated situation?

**Comment by glenn-jocher** [comment]
@frabob2017 yes, YOLOv8 supports data augmentation, including rotation, which allows the images to be rotated to a certain degree to increase diversity and improve the model's performance. During training, the object's annotation also shifts according to the same degree of rotation applied to the input image. Thus, the model will learn to detect objects at different angles. However, YOLO can only handle axis-aligned bounding boxes during detection. The rotated bounding box cannot be supported without any prior pre-processing or post-processing techniques.

**Comment by frabob2017** [comment]
Thank you Jocher, I also think it should be like this way.  I will rotate my image to make the oblique, long lesion to align to vertical or horizontal direction. I believe that minimizing unnecessary information into the bounding box, it will increase YOLO detection accuracy if using the same amount of training dataset.

**Comment by glenn-jocher** [comment]
You're welcome @frabob2017. Yes, it is always better to minimize the unnecessary information into the bounding box to avoid confusion or false detection. For this instance, it is advisable to preprocess the images by rotating them to align the oblique and long lesion to a vertical or horizontal direction before applying the bounding box. With this, the model can better understand and learn the images that properly align the objects. Additionally, using more training data can help improve the model's accuracy. You can refer to our Ultralytics documentation or raise any questions here if needed.
