### ISSUE TITLE
bitmap to jpg

### ISSUE THREAD

**Issue by q465414859** [ultralytics/ultralytics#2034]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

截图win10的桌面窗口，将图片通过tcp传输到局域网内的服务器进行yolo检测。但在 bitmap 到 jpg 比特的过程中。原本保存150kb的数据在 .tobytes() 后变成了 1920600 比特。这非常影响传输效率，想知道有没有更优秀的转换方式 使数据量变小，并保持完整性.
![f017488e93d12b46f2258d123d8acdf](https://user-images.githubusercontent.com/26251132/232087672-f6bfa601-1c30-4d7b-affb-728aaec18fcb.png)
![d109eec6480c7cbff6f70f9e6a7a805](https://user-images.githubusercontent.com/26251132/232087686-dc92c0d5-ed59-4e46-a0da-561aaf2f3c00.png)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@q465414859 it seems that the conversion from bitmap to jpg format is resulting in a larger file size than expected, leading to decreased transmission efficiency. One possible solution would be to explore different compression algorithms, such as PNG or WEBP, which may result in a smaller file size without compromising the integrity of the image. Additionally, there may be factors within the transmission process that could be optimized to further increase efficiency, such as using a more lightweight protocol or compressing the transmission itself. For more information on image compression and transmission, you may find resources on our documentation website helpful.
