### ISSUE TITLE
pytorch 2.0 hide_conf and hide_labels

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/ultralytics#2037]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

FYSA:
```
WARNING  'hide_conf' is deprecated and will be removed in 'ultralytics 8.2' in the future. Please use 'show_conf' instead.
WARNING  'hide_labels' is deprecated and will be removed in 'ultralytics 8.2' in the future. Please use 'show_labels' instead.
```

**Comment by glenn-jocher** [comment]
@apiszcz thank you for bringing this to our attention. The warnings you see mean that 'hide_conf' and 'hide_labels' functions are no longer available in Ultralytics YOLOv8 and have been replaced with 'show_conf' and 'show_labels', respectively. These new functions offer improved performance and functionality over the old functions. Please update your code accordingly to avoid any issues when upgrading to future versions of Ultralytics YOLOv8. If you need help with implementation, please refer to our documentation at https://docs.ultralytics.com for more information.
