### ISSUE TITLE
Yolo look for incorrect dataset path

### ISSUE THREAD

**Issue by luhgit** [ultralytics/ultralytics#2039]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have encountered this issue again. This time I am running a classification model.

Here is my config.yaml file:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/8448270/232139332-f14ea891-44d8-4d56-85b2-93e1004e4779.png">

The dataset directory structure under datasets/:

<img width="213" alt="image" src="https://user-images.githubusercontent.com/8448270/232141185-e43c8f4e-aeea-4bb3-9d96-27d52b63d6b2.png">

Each of these folders (train/val/test) contains class folders (A/B/C/D) which contain images.

I do not understand why does it always look for incorrect path i.e. /Users/aamit/datasets/dataset_config.yaml/train. Why is it appending yaml file in the path?

This is the error message that I get:
```
Ultralytics YOLOv8.0.77 🚀 Python-3.9.16 torch-2.0.0 CPU
yolo/engine/trainer: task=classify, mode=train, model=yolov8s-cls.pt, data=dataset_config.yaml, epochs=15, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs/classify/train3

Dataset not found ⚠️, missing path /Users/aamit/datasets/dataset_config.yaml, attempting download...
Downloading https://github.com/ultralytics/yolov5/releases/download/v1.0/dataset_config.yaml.zip to /Users/aamit/datasets/dataset_config.yaml.zip...
⚠️ Download failure, retrying 1/3 https://github.com/ultralytics/yolov5/releases/download/v1.0/dataset_config.yaml.zip...
######################################################################## 100.0%
Unzipping /Users/aamit/datasets/dataset_config.yaml.zip to /Users/aamit/datasets...
Dataset download success ✅ (0.6s), saved to /Users/aamit/datasets/dataset_config.yaml

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
File /usr/local/Caskroom/miniconda/base/envs/common_x86/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py:120, in BaseTrainer.__init__(self, cfg, overrides, _callbacks)
    119 if self.args.task == 'classify':
--> 120     self.data = check_cls_dataset(self.args.data)
    121 elif self.args.data.endswith('.yaml') or self.args.task in ('detect', 'segment'):

File /usr/local/Caskroom/miniconda/base/envs/common_x86/lib/python3.9/site-packages/ultralytics/yolo/data/utils.py:303, in check_cls_dataset(dataset)
    302 nc = len([x for x in (data_dir / 'train').glob('*') if x.is_dir()])  # number of classes
--> 303 names = [x.name for x in (data_dir / 'train').iterdir() if x.is_dir()]  # class names list
    304 names = dict(enumerate(sorted(names)))

File /usr/local/Caskroom/miniconda/base/envs/common_x86/lib/python3.9/site-packages/ultralytics/yolo/data/utils.py:303, in <listcomp>(.0)
    302 nc = len([x for x in (data_dir / 'train').glob('*') if x.is_dir()])  # number of classes
--> 303 names = [x.name for x in (data_dir / 'train').iterdir() if x.is_dir()]  # class names list
    304 names = dict(enumerate(sorted(names)))

File /usr/local/Caskroom/miniconda/base/envs/common_x86/lib/python3.9/pathlib.py:1160, in Path.iterdir(self)
   1157 """Iterate over the files in this directory.  Does not yield any
   1158 result for the special paths '.' and '..'.
   1159 """
-> 1160 for name in self._accessor.listdir(self):
   1161     if name in {'.', '..'}:
   1162         # Yielding a path object for these makes little sense

FileNotFoundError: [Errno 2] No such file or directory: '/Users/aamit/datasets/dataset_config.yaml/train'

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
Cell In[10], line 2
      1 model = YOLO('yolov8s-cls.pt')
----> 2 model.train(data='dataset_config.yaml', epochs=15, imgsz=640)

File /usr/local/Caskroom/miniconda/base/envs/common_x86/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py:362, in YOLO.train(self, **kwargs)
    360     overrides['resume'] = self.ckpt_path
    361 self.task = overrides.get('task') or self.task
--> 362 self.trainer = TASK_MAP[self.task][1](overrides=overrides, _callbacks=self.callbacks)
    363 if not overrides.get('resume'):  # manually set model only if not resuming
    364     self.trainer.model = self.trainer.get_model(weights=self.model if self.ckpt else None, cfg=self.model.yaml)

File /usr/local/Caskroom/miniconda/base/envs/common_x86/lib/python3.9/site-packages/ultralytics/yolo/v8/classify/train.py:20, in ClassificationTrainer.__init__(self, cfg, overrides, _callbacks)
     18     overrides = {}
     19 overrides['task'] = 'classify'
---> 20 super().__init__(cfg, overrides, _callbacks)

File /usr/local/Caskroom/miniconda/base/envs/common_x86/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py:126, in BaseTrainer.__init__(self, cfg, overrides, _callbacks)
    124             self.args.data = self.data['yaml_file']  # for validating 'yolo train data=url.zip' usage
    125 except Exception as e:
--> 126     raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
    128 self.trainset, self.testset = self.get_dataset(self.data)
    129 self.ema = None

RuntimeError: Dataset 'dataset_config.yaml' error ❌ [Errno 2] No such file or directory: '/Users/aamit/datasets/dataset_config.yaml/train'
```

**Comment by ekiefl** [comment]
The python API for managing the data.yaml and the paths it specifies is buggy.

I have some insight into the issue. Essentially, I'm noticing that when you call `YOLO.train` and pass the path of a YAML file to the `data` parameter, there are two major issues.

The first is probably related or equivalent to the behavior described above. I can't pass a path that is relative to my working directory. The YAML file is properly read, but the paths it points to don't exist. If I instead pass a full path, the error disappears and the paths specified in the YAML are properly read.

Here is the code I'm running:

```python
from ultralytics import YOLO
from pathlib import Path

model = YOLO("yolov8n.pt")

# This is the path to my YAML relative to my CWD
rel_path = "ml/datasets/dump/ml/data.yaml"

# This file _does_ exist
assert Path(rel_path).exists(), "File doesn't exist"

try:
    model.train(data=rel_path, epochs=2, imgsz=640)
except RuntimeError as e:
    print(
        f"Using a relative path to the YAML loads the YAML correctly, but "
        f"garbage gets prepended to the directories specified within the YAML, "
        f"leading to the following runtime error: \n {e}"
    )

# This is fixed by using the _full_ path

full_path = Path(rel_path).resolve()

try:
    model.train(data=str(full_path), epochs=1, imgsz=640)
except RuntimeError:
    print("This doesn't print")
```

Grabbing the relevant bits from the stdout, we see a `RuntimeError` when using the relative path:

```
Using a relative path to the YAML loads the YAML correctly, but garbage gets prepended to the directories specified within the YAML, leading to the following runtime error:
 Dataset 'ml/datasets/dump/ml/data.yaml' error ❌
Dataset 'ml/datasets/dump/ml/data.yaml' images not found ⚠️, missing paths ['/Users/evan/Software/poolml/poolml/ml/datasets/ml/datasets/dump/ml/val/images']
Note dataset download directory is '/Users/evan/Software/poolml/poolml/ml/datasets'. You can update this in '/Users/evan/Library/Application Support/Ultralytics/settings.yaml'
```

Below is where it's looking for the images (first) versus where the images are (second):

```
/Users/evan/Software/poolml/poolml/ml/datasets/ml/datasets/dump/ml/val/images
/Users/evan/Software/poolml/poolml/ml/datasets            /dump/ml/val/images
```

I don't think it's a coincidence that the added bit, `ml/datasets`, is the prefix of my relative path.

After passing a full path it finds the images and training commences. Here is my YAML:

```yaml
names:
- cue
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
nc: 10
test: ./test/images
train: ./train/images
val: ./val/images
```

Not only must you pass a full path, but it cannot be a `Path` object, otherwise an `AttributeError` is raised because `Path` objects don't have `endswith(...)`:

```
Dataset '/Users/evan/Software/poolml/poolml/ml/datasets/dump/ml/data.yaml' error ❌ 'PosixPath' object has no attribute 'endswith'
```

**Comment by glenn-jocher** [comment]
@luhgit the issue with the Python API for managing the data.yaml and the paths it specifies is that it is currently buggy. When using the `YOLO.train` function and passing a YAML file to the `data` parameter, there are two major issues. First, it is not possible to pass a path that is relative to the working directory, as this causes errors when the paths in the YAML file are read. To fix this, a full path must be used instead. Second, it is important to note that a `Path` object cannot be used as the path, as it will raise an error due to `Path` objects not having the required `endswith(...)` attribute. These issues must be taken into consideration when using the Python API for managing the data.yaml and its associated paths.

**Comment by ekiefl** [comment]
... Did you just use a bot to synthesize my reply and post it as your own?

**Comment by glenn-jocher** [comment]
@ekiefl passing data as a Path would be a beneficial improvement, if you could submit a PR for this that would help other users I think.

Regarding the dataset paths, `yolo settings` will indicate your dataset path, which is where `ultralytics` will look for datasets. You can redefine your datasets path to a local or absolute directory, or simply reset your settings with `yolo settings reset`, which may resolve path issues.

**Comment by ekiefl** [comment]
@glenn-jocher What I've described is a bug, not incorrect usage. Whether I pass the YAML file as a relative path or an absolute path should have **zero** bearing on where the image files are looked for. It's the same YAML file in both cases.

**Comment by glenn-jocher** [comment]
For a simple demo dataset you can use to get started you can run 'yolo train', which will auto download and indicate the correct usage.

If you feel there is a bug then please submit a PR with a fix and the team will review your proposal there, thank you!

**Comment by luhgit** [comment]
@ekiefl : Thanks for providing insights on this issue. So you don't keep the path attribute in your .yaml file? How does it know in that case where your train/val directory is located? Perhaps based on your "yolo settings" file config? I am assuming your cwd is /Users/evan/Software/poolml/poolml/ml/datasets?

I tried to pass full path as you explained but then it still does not find dataset/dataset.yaml even though the path to it exists which I already verified from my current working directory but it attempts to download it?

```
Dataset not found ⚠️, missing path /Users/aamit/dataset_config.yaml, attempting download...
Downloading https://github.com/ultralytics/yolov5/releases/download/v1.0/Users/aamit/dataset_config.yaml.zip to /Users/aamit/dataset_config.yaml.zip...
⚠️ Download failure, retrying 1/3 https://github.com/ultralytics/yolov5/releases/download/v1.0//Users/aamit/dataset_config.yaml.zip...
curl: (3) U⚠️ Download failure, retrying 2/3 https://github.com/ultralytics/yolov5/releases/download/v1.0//Users/aamit/dataset_config.yaml.zip...
RL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
⚠️ Download failure, retrying 3/3 https://github.com/ultralytics/yolov5/releases/download/v1.0//Users/aamit/dataset_config.yaml.zip...
curl: (3) URL using bad/illegal format or missing URL
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
File /usr/local/Caskroom/miniconda/base/envs/common_x86/lib/python3.9/site-packages/ultralytics/yolo/utils/downloads.py:99, in safe_download(url, file, dir, unzip, delete, curl, retry, min_bytes, progress)
     98     r = subprocess.run(['curl', '-#', f'-{s}L', url, '-o', f, '--retry', '3', '-C', '-']).returncode
---> 99     assert r == 0, f'Curl return value {r}'
    100 else:  # urllib download

AssertionError: Curl return value 3

The above exception was the direct cause of the following exception:

ConnectionError                           Traceback (most recent call last)
File /usr/local/Caskroom/miniconda/base/envs/common_x86/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py:120, in BaseTrainer.__init__(self, cfg, overrides, _callbacks)
    119 if self.args.task == 'classify':
--> 120     self.data = check_cls_dataset(self.args.data)
    121 elif self.args.data.endswith('.yaml') or self.args.task in ('detect', 'segment'):

File /usr/local/Caskroom/miniconda/base/envs/common_x86/lib/python3.9/site-packages/ultralytics/yolo/data/utils.py:296, in check_cls_dataset(dataset)
    295     url = f'[https://github.com/ultralytics/yolov5/releases/download/v1.0/{dataset}.zip](https://github.com/ultralytics/yolov5/releases/download/v1.0/%7Bdataset%7D.zip)'
--> 296     download(url, dir=data_dir.parent)
    297 s = f"Dataset download success ✅ ({time.time() - t:.1f}s), saved to {colorstr('bold', data_dir)}\n"

File /usr/local/Caskroom/miniconda/base/envs/common_x86/lib/python3.9/site-packages/ultralytics/yolo/utils/downloads.py:208, in download(url, dir, unzip, delete, curl, threads, retry)
    207 for u in [url] if isinstance(url, (str, Path)) else url:
--> 208     safe_download(url=u, dir=dir, unzip=unzip, delete=delete, curl=curl, retry=retry)

File /usr/local/Caskroom/miniconda/base/envs/common_x86/lib/python3.9/site-packages/ultralytics/yolo/utils/downloads.py:126, in safe_download(url, file, dir, unzip, delete, curl, retry, min_bytes, progress)
    125 elif i >= retry:
--> 126     raise ConnectionError(emojis(f'❌  Download failure for {url}. Retry limit reached.')) from e
    127 LOGGER.warning(f'⚠️ Download failure, retrying {i + 1}/{retry} {url}...')

ConnectionError: ❌  Download failure for https://github.com/ultralytics/yolov5/releases/download/v1.0//Users/aamit/dataset_config.yaml.zip. Retry limit reached.

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
Cell In[23], line 3
      1 # This is fixed by using the _full_ path
      2 full_path = Path(rel_path).resolve()
----> 3 model.train(data=str(full_path), epochs=1, imgsz=640)

File /usr/local/Caskroom/miniconda/base/envs/common_x86/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py:362, in YOLO.train(self, **kwargs)
    360     overrides['resume'] = self.ckpt_path
    361 self.task = overrides.get('task') or self.task
--> 362 self.trainer = TASK_MAP[self.task][1](overrides=overrides, _callbacks=self.callbacks)
    363 if not overrides.get('resume'):  # manually set model only if not resuming
    364     self.trainer.model = self.trainer.get_model(weights=self.model if self.ckpt else None, cfg=self.model.yaml)

File /usr/local/Caskroom/miniconda/base/envs/common_x86/lib/python3.9/site-packages/ultralytics/yolo/v8/classify/train.py:20, in ClassificationTrainer.__init__(self, cfg, overrides, _callbacks)
     18     overrides = {}
     19 overrides['task'] = 'classify'
---> 20 super().__init__(cfg, overrides, _callbacks)

File /usr/local/Caskroom/miniconda/base/envs/common_x86/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py:126, in BaseTrainer.__init__(self, cfg, overrides, _callbacks)
    124             self.args.data = self.data['yaml_file']  # for validating 'yolo train data=url.zip' usage
    125 except Exception as e:
--> 126     raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
    128 self.trainset, self.testset = self.get_dataset(self.data)
    129 self.ema = None

RuntimeError: Dataset '/Users/aamit/dataset_config.yaml' error ❌ ❌  Download failure for https://github.com/ultralytics/yolov5/releases/download/v1.0//Users/aamit/Documents/dataset_config.yaml.zip. Retry limit reached.
```

**Comment by luhgit** [comment]
@glenn-jocher It might be that my data directory does not have proper arrangements of images in the class directories. But unfortunately, there is no proper documentation on how to arrange data and corresponding .yaml file for all types of training modes (detect/classify/segment/pose). It would be nice to have a chapter in the docs on this.

Also, this behavior of the Python API that it does not easily locate datasets doesn't motivate me to use it in production scenarios as to me it is a bug. Perhaps we could fix it?

**Comment by luhgit** [comment]
@ekiefl @glenn-jocher Is there any documentation to use the v8 by cloning it and manually calling classify/train.py and passing the dataset configuration?

**Comment by asizk** [comment]
Did you solve it? I have the same problem

**Comment by a-gucciardi** [comment]
@luhgit I know there is this [colab](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/classify/tutorial.ipynb#scrollTo=1NcFxRcFdJ_O) on training where your custom dataset configuration can be passed for training. Maybe this can help ? It worked for me but it's Yolov5 not Yolov8.  

I have the same current general issue when trying to write relative paths in my dataset.yaml with yolov8 API, using full path works although it requires some work around with `os.path` if you want to share your code.

**Comment by glenn-jocher** [comment]
@asizk the user has pointed out the lack of documentation on how to arrange data and corresponding .yaml files for all types of training tasks in the YOLOv8 API. They also mention that the behavior of the Python API in not being able to locate datasets easily is problematic for production scenarios. The user suggests adding a chapter in the documentation on data arrangement and fixing the API's dataset location issue. According to the user, the current path resolution strategy connecting the current working directory, paths in the data.yaml, and the datasets_dir path defined in settings.yaml is shoddy, and this complexity stems from the API strategy of shoehorning all CLI artifacts into Python. The user suggests alternative solutions for passing image paths and data configuration to the API.

**Comment by Laughing-q** [comment]
@luhgit @ekiefl hey guys, the designed logic here of data.yaml is to concatenate the `datasets_dir` from `yolo settings` and the relative directory if the path is relative. Please pass absolute path for data.yaml if you don't use `datasets_dir` in your workflow. :)
[https://github.com/ultralytics/ultralytics/blob/a38f22767254f2c2ee241490bd027987780d83ca/ultralytics/yolo/data/utils.py#L225-L229](https://github.com/ultralytics/ultralytics/blob/a38f22767254f2c2ee241490bd027987780d83ca/ultralytics/yolo/data/utils.py#L225-L229)

**Comment by AyushExel** [comment]
@luhgit the classification task doesn't need any .yaml file you can simply pass the dataset folder path.
Please try this:
```
yolo classify train data="path/to/folder"
```
This should work out of the box

**Comment by luhgit** [comment]
@AyushExel : You are a lifesaver man! Your suggestion worked just out of the box.

It's just so frustrating to see the setup of yolov8 API being so confusing and lack of documentation. I mean the `data-config.yaml` file didn't play any role finally and neither did the path in `yolo settings`.

**Key take aways:**
- It might be true for object detection or segment tasks that `config.yaml` file plays a role but
- For classify tasks the key is to arrange data in a way that config.yaml is unnecessary and does not provide any additional information that train.py cant get from the directory structure i.e.
- So if we organize the data in the following way:

```
path/to/data
├── train/
│   ├── class_1/
│   ├── class_2/
│   ├── ...../
│   └── class_n/
├── val/
│   ├── class_1/
│   ├── class_2/
│   ├── ...../
│   └── class_n/
└── test/
    ├── class_1/
    ├── class_2/
    ├── ...../
    └── class_n/
```
Given the above directory structure, `config.yaml` is simply redundant from my perspective as we can infer all the information that we were trying to specify in the `config.yaml` file.

Another thing to keep in mind is to pass the full path (absolute) and not relative path. `yolo settings` becomes relvant when a relative path is passed. But `yolo settings` does not play a role when absolute path is passed.

So for me the following worked:

`yolo classify train model='yolov8n-cls.pt' data='absolute_path_to_data_directory_containing_train_test_val' `

OR

`model.train(data='absolute_path_to_data_directory_containing_train_test_val', epochs=20)`

Thanks @AyushExel and @ekiefl for helping me figure out the issue. 

@glenn-jocher : Perhaps we should consider this information to be added to the documentation?

**Comment by glenn-jocher** [comment]
Yes, Ayush and I were talking yesterday about the need for dataset docs and expanded instructions there like we have in our yolov5 tutorial. 

Could you submit a PR to docs if you have time in docs/modes/train?

**Comment by AyushExel** [comment]
@glenn-jocher I have made a PR for this yesterday

**Comment by Teut2711** [comment]
Sharing my config  which fixed it for me:

```python
results = model.train(data="D:/newspapergames_com/data/sudoku.yaml", epochs=100)
```


![image](https://github.com/user-attachments/assets/f2f9f45a-0301-46a1-ba6e-16a5fe77b61b)


```yaml
path: ../datasets/sudoku
train: train/images
val: val/images

names:
  - 0: sudoku
nc: 1
```

**Comment by glenn-jocher** [comment]
Thanks for sharing your solution! If you have any more questions or need further assistance, feel free to ask.

**Comment by glenn-jocher** [comment]
Thank you for sharing your solution. If you have any further questions or need assistance, feel free to ask!

**Comment by glenn-jocher** [comment]
Thank you for sharing your solution. If you have any further questions or need assistance, feel free to ask!

**Comment by ekiefl** [comment]
@glenn-jocher please turn your autocommenter off. It is unhelpful and in my opinion signals huge amounts of distrust that you're willing to offload the responsibility of maintaining a repo to a pretend version of yourself.

**Comment by glenn-jocher** [comment]
Thanks for sharing your solution! If you have any more questions or need further assistance, feel free to ask.

**Comment by glenn-jocher** [comment]
Thanks for sharing your solution! If you have any more questions or need further assistance, feel free to ask.

**Comment by glenn-jocher** [comment]
Thank you for sharing your configuration. It's great to hear that it resolved your issue. If you have any further questions or need additional assistance, feel free to ask.

**Comment by sirineHD** [comment]
Hello,
I encountered the same issue but after dubugging it seems that the yaml file structure is wrong so you need to nc which is the number of classes and the path should be absolute path this is an example of how it should be:

path: "absolute path to your dataset"

train: images/train # Train images directory
val: images/test # Validation images directory
nc: 1
names:
0: class_name# If you have multiple classes, add them here

**Comment by glenn-jocher** [comment]
Thanks for sharing your experience! For classification tasks, Ultralytics YOLO doesn't require a YAML file - you can simply point to your dataset directory structured with `train`/`val`/`test` subfolders containing class folders. The `nc` and `names` are auto-detected from this structure. For details, see our classification dataset docs: [Image Classification Datasets Overview](https://docs.ultralytics.com/datasets/classify/).
