### ISSUE TITLE
Where can I find coco128.yaml and coco8-pose.yaml?

### ISSUE THREAD

**Issue by OpenMMLab-Assistant-007** [ultralytics/ultralytics#2044]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Where can I find coco128.yaml and coco8-pose.yaml?

**Comment by Laughing-q** [comment]
@OpenMMLab-Assistant-007 it's in `ultralytics/datasets/`.
