### ISSUE TITLE
How to not display labels and conf ?

### ISSUE THREAD

**Issue by qiujianchen** [ultralytics/ultralytics#2046]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would not to display labels and conf when predict images, but I failed. Can someone solve this problem ?
```python
import torch
from ultralytics import YOLO

# 加载模型
model = YOLO("runs/detect/train4/weights/best.pt")

# 预测结果
with torch.no_grad():
    results = model.predict(task="detect", source="/mnt/datasets/rebar_bale_detection/images/val", max_det=1000, conf=0.55, show_labels=False, show_conf=False, save=True, device="0")  # predict on a Image，最大检测数修改为1000，不显示标签和置信度，保存检测结果图像
```

result:
![下载 (4)](https://user-images.githubusercontent.com/71818703/232190055-660a8551-662f-4e7d-91fa-648a1e80e2d7.jpg)

**Comment by glenn-jocher** [comment]
@qiujianchen, you can accomplish this by specifying the `augment` argument as `False` when calling the `predict()` function. Here is an example:

```python
import torch
from ultralytics import YOLO

# 加载模型
model = YOLO("runs/detect/train4/weights/best.pt")

# 预测结果
with torch.no_grad():
    results = model.predict(task="detect", source="/mnt/datasets/rebar_bale_detection/images/val", max_det=1000, conf=0.55, show_labels=False, show_conf=False, save=True, device="0", augment=False)  # predict on a Image，最大检测数修改为1000，不显示标签和置信度，保存检测结果图像，不进行数据扩充
```

This runs the detection on the original image without any data augmentations and output will not include the labels or confidences.

**Comment by qiujianchen** [comment]
I added the  the `augment` argument as `False`, but **it still displayed the labels and conf**.
before I trained the model and predict images, I've installed `ultralytics` by `pip install ultralytics`. Tthe version of `ultralytics` is `8.0.78`.
![下载](https://user-images.githubusercontent.com/71818703/232199236-4e6ebc1b-e65b-4e0c-9978-bb6839372d3b.jpg)

**Comment by glenn-jocher** [comment]
@qiujianchen, thank you for providing the additional information. I apologize for any confusion from my previous response. 

To address your issue, it seems that the `show_labels` and `show_conf` arguments may not be disabling the display of labels and confidences as expected. Please try specifying `box_args=dict(labels=False)` when calling `predict()`. This should disable the display of labels while still allowing for the display of the bounding boxes. 

If the issue still persists, please share some additional details on your training and prediction setup. Specifically, what dataset are you using, how was the model trained, and what modifications were made to the model or the `predict()` function.

**Comment by qiujianchen** [comment]
So how to use `box_args=dict(labels=False)` ？ I add it in `predict()`, but it seems not the configuration of `predict()`.
```python
import torch
from ultralytics import YOLO

# 加载模型
model = YOLO("runs/detect/train5/weights/best.pt")

# 预测结果
with torch.no_grad():
    results = model.predict(task="detect", source="IMG_20230327_144942.jpg", max_det=1000, conf=0.55, show_labels=False, show_conf=False, box_args=dict(labels=False), save=True, device="0", augment=False)  # predict on a Image
```
It can not run.  The error message is `SyntaxError: 'box_args' is not a valid YOLO argument.`.

I just use `train()` to train my custom model, and do not modify the model.
```python
from ultralytics import YOLO

# Load a pretrained model
model = YOLO("yolov8s.pt")

# Train the model
model.train(task="detect", model="train", data="rebar_dataset.yaml", epochs=120, imgsz=640, batch=8, device="0", workers=0)
```

**Comment by AyushExel** [comment]
@glenn-jocher @qiujianchen thanks for the bug report. I was able to reproduce this. I'll add a TODO and work on a fix.

**Comment by AyushExel** [comment]
I think show_label=False should hide everything once this fixed so you won't need to pass both show_label=false and show_conf=False. Right @glenn-jocher ?

**Comment by glenn-jocher** [comment]
@AyushExel i.e. for Detect models show_label=False should hide the "person 0.90" string and show only the box. show_conf=False would show the box and "person"

**Comment by qiujianchen** [comment]
@glenn-jocher  @AyushExel  **Thank you for solving this problem!** The latest version can hide the labels and confidences, and only show the detection boxes.

**Comment by glenn-jocher** [comment]
@qiujianchen, you're very welcome! We're glad to hear that the latest version of YOLOv8 addresses your issue with hiding labels and confidences during predictions. 

To provide a bit more context, showing the bounding box only is useful in some cases where there is no need to show class information on the image. By hiding the label and the confidence score, the user can keep the focus on the image without any extra information. Additionally, having the ability to customize the visualization of the prediction results can greatly improve the user experience and tailor the predictions to specific applications or requirements.

**Comment by Justinfungi** [comment]
Is it fixed. when i use show_label == False, it still show the label

**Comment by sitifatim** [comment]
hello, is this argument just work for custom dataset only? because i've tried to hiding the confidence score with show_conf = False with pre-trained model, but the result is still showing the confidence label. 

> @AyushExel i.e. for Detect models show_label=False should hide the "person 0.90" string and show only the box. show_conf=False would show the box and "person"

**Comment by glenn-jocher** [comment]
@sitifatim hello, The `show_conf` and `show_labels` arguments are available for both pre-trained and custom models in YOLOv8. However, `show_conf=False` should be used to hide the confidence label and `show_labels=False` should be used to hide the object label. Thus, if you want to hide both confidence and object labels, you should set `show_conf=False` and `show_labels=False` together. It's worth noting that the `show_labels` parameter applies only during visualization, and not during model inference or export.

**Comment by leosv123** [comment]
hide_labels and hide_conf is not working

**Comment by glenn-jocher** [comment]
@leosv123 hello,

Thank you for reporting this issue. The `show_labels=False` and `show_conf=False` arguments should be used to hide the object labels and confidence scores, respectively, in the visualized output of the model prediction. However, these parameters only apply to the visualization and do not affect the result returned by the `predict()` function, which still includes the labels and confidence scores for each detected object.

So, when you set `show_labels=False` and `show_conf=False`, it should not display the labels and confidence scores in the visual output (such as when saving the result as an image file), but the result returned by the `predict()` function remains unchanged.

If these parameters do not behave as expected, please let me know, as this could be a potential bug that needs to be addressed.

Thank you for your support and engagement in improving YOLOv8.

**Comment by prerakmody** [comment]
Hi,
Is there a way to hide a particular label? I need to show all labels except the first one.

**Comment by glenn-jocher** [comment]
@prerakmody hello,

Absolutely, hiding specific labels in the visualization of your model's predictions can be accomplished by post-processing the "labels" array of your prediction results. The labels are represented as integers, and you can remove detections of certain classes by discarding the results for the corresponding labels. 

For example, if you wish to hide the first label (which is usually represented as "0"), you could do so by ignoring or deleting detections with the label "0" in your results. This would hide the predictions of that class in your visual output.

Please note that this modification wouldn't affect the model's ability to detect all classes during the inference, it only changes what detections are included in the final displayed results. 

I hope this helps, and please let us know if you have more questions!

**Comment by srangg** [comment]
I have a question:
I already have cropped 14 classes, and I want to save all of them to each folder 1 class, for example crop of class 1 will save to folder class 1, I don't know how to figure out that problem even I was trying to find any solution. Any advice to solve that?

![302591808_2395645330584298_955148377692769140](https://github.com/ultralytics/ultralytics/assets/81784975/e4b3bd0a-31d1-4059-80d5-f7a3b7fc94ed)

**Comment by glenn-jocher** [comment]
@srangg hello,

From your question, it sounds like you've already successfully separated and cropped your dataset into 14 different classes. Now, you want to save the individual class crops to their respective directories. 

In order to accomplish this, you would need to loop over your list of detected objects after running the detector. For each object detected, you would extract the class label and then use this label to determine the folder where the cropped image should be saved.

Remember to ensure that your directories for each class are already created before you attempt to save the cropped images to them. If they're not created beforehand, you will need to include a step in your code to create the directory when needed.

In effect, the solution involves combining YOLOv8 object detection classes with some file and directory handling operations in Python. This approach should result in a directory for each class, each containing the cropped images for that class.

I hope this helps and results in the organization you're looking for in your dataset. Let us know if you have more questions.

**Comment by saikrishna0203** [comment]
@glenn-jocher  please say me how to remove conf scores,i need just labels only not scores ,pls did you solve that bug?

**Comment by glenn-jocher** [comment]
@saikrishna0203 hello,

The functionality to hide confidence scores (`show_conf=False`) while displaying only the labels during the visualization step is intended to work as described. If the confidence scores are still appearing despite setting `show_conf=False`, then there might be an issue that needs to be investigated.

There are a couple of things to check:

1. Ensure you are using the latest version of YOLOv8, as updates and bug fixes are continuously made.
2. Confirm that you have correctly set `show_conf=False` during the visualization step.

If you have checked these points and the issue persists, it could indeed be a potential bug. I would recommend reporting it in detail on the Ultralytics YOLOv8 GitHub issue tracker. This would include your current environment setup, model version, and a snippet of code that reproduces the problem. The development team can then investigate and work on a solution.

Thanks for your patience and collaboration in improving the YOLOv8 project.

**Comment by hellowqc** [comment]
> @leosv123 hello,
> 
> Thank you for reporting this issue. The `show_labels=False` and `show_conf=False` arguments should be used to hide the object labels and confidence scores, respectively, in the visualized output of the model prediction. However, these parameters only apply to the visualization and do not affect the result returned by the `predict()` function, which still includes the labels and confidence scores for each detected object.
> 
> So, when you set `show_labels=False` and `show_conf=False`, it should not display the labels and confidence scores in the visual output (such as when saving the result as an image file), but the result returned by the `predict()` function remains unchanged.
> 
> If these parameters do not behave as expected, please let me know, as this could be a potential bug that needs to be addressed.
> 
> Thank you for your support and engagement in improving YOLOv8.

Hello, I am visualizing the results returned by the Predict() function. I want to hide labels and confidence in visualized photos. Is there a solution?

**Comment by MZaid101** [comment]
Hey, I need to hide bboxes but get the conf and labels:
I am using following code:

```
parts_seg_res = model1.predict(vehicle_img, classes=names, conf=0.05, show_conf=False, augment=False)
damge_seg_res = model2.predict(vehicle_img, show_boxes=False, augment=False)
```


but it doesn't work
![image](https://github.com/ultralytics/ultralytics/assets/53510596/82a9f6bf-6216-48e1-8e1e-f55f9ec9adcf)

ultralytics version 8.0.227

**Comment by glenn-jocher** [comment]
@MZaid101 hello,

For hiding bounding boxes while retaining the confidence and labels in the visual output, the argument you've used (`show_boxes=False`) should be correct. If this isn't working as intended, it's possible you've encountered a bug.

Please ensure you're using the latest version of YOLOv8 from the repository, as this can often resolve issues due to recent bug fixes and improvements. If after updating the issue persists, we encourage you to submit a bug report on the GitHub repository with the details of the behavior you're experiencing, along with your environment details.

Thank you for bringing this to our attention, and we appreciate your assistance in enhancing YOLOv8.

**Comment by benito-gonzalez** [comment]
Hi @glenn-jocher 
I'm using the latest ultralytics 8.1.0 and when passing show_labels=False, show_conf=False to the track() method, both labels and conf still appear. 
This is my call:
```python
results = model.track(interest_region, persist=True, classes=[0], show_labels=False, show_conf=False)
annotated_region = results[0].plot()
cv2.imshow("YOLOv8 Tracking", annotated_region)
```
and the image shows:

![Captura desde 2024-01-11 12-26-55](https://github.com/ultralytics/ultralytics/assets/44648757/5fce28b4-5337-4941-a04b-2936d260f26d)

is there any workaround to get rid of that information in the output? Thanks.

**Comment by a2082761** [comment]
I also used mode.track function  and I used show_boxes = False, show_labels = False, show_conf=False 
but still it all appear.
Is there another way to solve this problem?

**Comment by glenn-jocher** [comment]
@a2082761 hello,

If `show_labels=False` and `show_conf=False` are not hiding labels and confidence scores in the visual output when using the `track()` method, this might be an unintended behavior that needs to be addressed.

As a workaround, you can manually edit the visualization code to not render the labels and confidence scores on the output frames. However, since this involves altering the source code, it's not the most user-friendly solution.

Please report this issue on the GitHub repository with the details of your environment and the unexpected behavior. The development team will look into it and work on a fix.

Thank you for your patience and for helping us improve YOLOv8.

**Comment by glenn-jocher** [comment]
@HolintCasazr hey there! 👋 It looks like the `show_labels=False` and `show_conf=False` options should be applied when calling the `.plot()` method, not directly in the `track()` method. Try adjusting your code like this:

```python
results = model.track(interest_region, persist=True, classes=[0])
annotated_region = results[0].plot(show_labels=False, show_conf=False)
cv2.imshow("YOLOv8 Tracking", annotated_region)
```

This should ensure that labels and confidence scores are not displayed in your output. Hope this helps! Let us know if you have any more questions. 😊

**Comment by jvmolu** [comment]
For anyone else stuck in the same issue when using result.plot() function:

The arguments to be passed are:

conf = False [NOT show_conf = False or probs = False]

So the code should be like:

```
results = model.track(interest_region, persist=True, classes=[0])
annotated_region = results[0].plot(labels=False, conf=False)
cv2.imshow("YOLOv8 Tracking", annotated_region)
```

**Comment by glenn-jocher** [comment]
Hey there! Thank you for providing clarity on the correct usage of the arguments for the `plot()` function. 🌟 Your example is spot-on and it's important to use `conf=False` to hide the confidence scores effectively. Here's the succinct version of your contribution:

```python
results = model.track(interest_region, persist=True, classes=[0])
annotated_region = results[0].plot(labels=False, conf=False)
cv2.imshow("YOLOv8 Tracking", annotated_region)
```

This should help anyone looking to customize their tracking output display. Keep up the great work with your contributions to the community! 😊
