### ISSUE TITLE
Why repo name is "ultralytics"  instead of "yolov8" ?

### ISSUE THREAD

**Issue by awsaf49** [ultralytics/ultralytics#205]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I was wondering why the repo name is "ultralytics"  instead of "yolov8" ? Previously YOLOv5 and v3 repos are named after their actual name but for YOLOv8 repo is named quite differently. I'm wondering if it means this is the final version of YOLO from ultralytics team.

### Additional

I just noticed there is no discussion section for yolov8 hence [discussion link](https://github.com/ultralytics/ultralytics/discussions) doesn't work.

**Comment by NBStephens** [comment]
Already been asked and answered in #179

**Comment by awsaf49** [comment]
Thanks I'm closing it.
