### ISSUE TITLE
setting device=1 won't work, uses device o instead

### ISSUE THREAD

**Issue by bit-scientist** [ultralytics/ultralytics#2055]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Detection

### Bug

I got two GPUs on my windows 10 PC, 8GB and 24GB. According to Task manager, GPU 0 is 8GB GPU, GPU 1 is 24GB. 

![image](https://user-images.githubusercontent.com/26497571/232234521-47ef9982-abd6-4ce7-8e40-2ad12d7be774.png)

For training with 24 GB, I used `device=1` hoping that it will access GPU 1. However, it keeps allocating memory from GPU 0 and throws an error due to large batch size (because I'm using larger batch-size). 

`RuntimeError: CUDA out of memory. Tried to allocate 600.00 MiB (GPU 0; 8.00 GiB total capacity; 6.82 GiB already allocated; 0 bytes free; 7.12 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`.

`print(torch.cuda.device_count())` returns 2 as expected.
It goes on as a  usual training on device 0 with smaller batch-size. 
I tried with both CLI and python.

### Environment

Ultralytics YOLOv8.0.77  Python-3.8.16 torch-1.12.1 CUDA:1 (NVIDIA GeForce RTX 2060 SUPER, 8192MiB)

### Minimal Reproducible Example

Any training command (`device=1`) that runs on a PC which has at least 2 GPUs.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@bit-scientist it seems that the issue might be related to PyTorch's GPU memory allocation strategy. When `device=1` is passed, the program is trying to allocate the memory on GPU1, but it seems that PyTorch is still allocating memory on GPU0. One possible solution is to manually set the environment variable "CUDA_VISIBLE_DEVICES" to "1" before running the training command. This should ensure that the training process is only able to access the specified GPU. Additionally, reducing the batch size might help to reduce the GPU memory usage. You can find more information on GPU memory management and allocation in PyTorch documentation.

**Comment by bit-scientist** [comment]
Thanks, @glenn-jocher . I set the following at the top of my python training file: 
```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
```
I should also note that, after doing that, the device has to be set to 0 (`device=0`). I guess it's only logical because `os.environ["CUDA_VISIBLE_DEVICES"] = "1"` makes it see only one GPU and assigns an ID of 0. Appreciate your timely response.

**Comment by glenn-jocher** [comment]
You're welcome @bit-scientist. I'm glad that setting the "CUDA_VISIBLE_DEVICES" environment variable resolved your issue. As you mentioned, setting the variable to "1" makes sure that the training process only accesses the specified GPU. It's important to note that after setting the environment variable, the device should be set to "0" so that the training process is assigned to the only accessible GPU. Additionally, reducing the batch size might help if you still see high memory usage. In case you need more information on GPU memory management and allocation, you can refer to the official PyTorch documentation. If you have any further questions or issues, feel free to ask.
