### ISSUE TITLE
Prediction settings

### ISSUE THREAD

**Issue by HornGate** [ultralytics/ultralytics#2057]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Does the augment parameter in the prediction settings in default.yaml mean TTA(Test Time Augmentation)？

**Comment by glenn-jocher** [comment]
@HornGate yes, the "augment" parameter in default.yaml refers to Test Time Augmentation (TTA) in YOLOv8. TTA is an ensemble technique where multiple predictions are made on augmented versions of the same image and the results are aggregated to create a final prediction. By default, YOLOv8 uses horizontal flip and simple scaling as augmentation techniques during TTA. You can modify this setting in the default.yaml file as per your requirements. For more details, you can refer to the Ultralytics YOLOv8 documentation at https://docs.ultralytics.com/.

**Comment by HornGate** [comment]
@glenn-jocher Sorry, why I can't find it in predictor.py code？

**Comment by glenn-jocher** [comment]
@HornGate The `predictor.py` file is a class file and contains methods related to model prediction. The parameter `"augment"` in the `default.yaml` file is used by the `test` method of `model.py`, which calls `predictor.py` to perform model predictions. The `augment` parameter controls whether TTA is applied to the model predictions or not. If the argument is set to `True`, the model predictions are made on augmented versions of the input image, whereas if the argument is set to `False`, the model predictions are made on the input image without any augmentation. The `predictor.py` file does not directly use the `"augment"` parameter. Let me know if you have any other questions or concerns.

**Comment by HornGate** [comment]
@glenn-jocher Thanks. But I found that the model.py didn't have test method, why?

**Comment by HornGate** [comment]
> @HornGate The `predictor.py` file is a class file and contains methods related to model prediction. The parameter `"augment"` in the `default.yaml` file is used by the `test` method of `model.py`, which calls `predictor.py` to perform model predictions. The `augment` parameter controls whether TTA is applied to the model predictions or not. If the argument is set to `True`, the model predictions are made on augmented versions of the input image, whereas if the argument is set to `False`, the model predictions are made on the input image without any augmentation. The `predictor.py` file does not directly use the `"augment"` parameter. Let me know if you have any other questions or concerns.

Or could you tell me in which method it's used?

**Comment by Laughing-q** [comment]
@HornGate just pass `augment=True` when you predicting if you want to use TTA, it'll work but noted that we only support detection model for TTA for now.
