### ISSUE TITLE
data augmentation in training

### ISSUE THREAD

**Issue by jet-c-21** [ultralytics/ultralytics#2058]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

If I use the following example code in doc, will it perform data augmentation in training?

```python3
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.yaml')  # build a new model from YAML
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)
model = YOLO('yolov8n.yaml').load('yolov8n.pt')  # build from YAML and transfer weights

# Train the model
model.train(data='coco128.yaml', epochs=100, imgsz=640)
```

Or I have to do data augmentation by myself? If so, hope you can provide some example for adding data aug in training phase. Thank You!

**Comment by glenn-jocher** [comment]
Hi @jet-c-21-Chen! Yes, the example code you provided will perform data augmentation during training. We use the Albumentations library to perform data augmentation. By default, we use random flipping, scaling, translating, and color jittering. You can customize the image augmentations by adjusting the parameters in the data YAML file, as shown in the [COCO128 config file](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml). If you wish to write your own image augmentations, you can modify the [`transforms` function](https://github.com/ultralytics/yolov5/blob/master/models/yolo.py#L61) in the `yolo.py` file. I hope this helps!

**Comment by Abecadarian** [comment]
The COCO128 config file doesn't seem to have parameters relating to image augmentation.

**Comment by mwyborski** [comment]
In v8 the Albumentation transformations are in https://github.com/ultralytics/ultralytics/blob/0a36b83e7addd5e21438d32a614bbdf3f330e6d9/ultralytics/yolo/data/augment.py#L589
and not in yolo.py. Then passing 'augment=True' to the train parameters solved it for me.

**Comment by glenn-jocher** [comment]
@mwyborski hello! In YOLOv8, the Albumentations transformations are located in the `augment.py` file and not the `yolo.py` file. When running the training script, you can enable data augmentation by setting the `augment` parameter to `True`. This will apply the default set of image augmentations to the training data before passing it to the YOLOv8 model. You can also customize the set of image augmentations by modifying the transformation functions in the `augment.py` file or by creating your own set of transformation functions. I hope this helps!

**Comment by glenn-jocher** [comment]
Hi @Arshadoid-21-Chen, thanks for your question! In YOLOv8, data augmentation is applied during training by default. Specifically, we use the Albumentations library to perform random flipping, scaling, translating, and color jittering. You can customize the set of image augmentations by modifying the transformation functions in the `augment.py` file or by creating your own set of transformation functions. 

Regarding the `augment` flag, setting it to `True` will enable data augmentation during training. If you don't pass the `augment` flag, data augmentation will still be applied by default during training. However, if you want to disable data augmentation altogether, you can pass `augment=False`. You are correct that the `augment` flag is not currently documented in the YOLOv8 documentation, and we appreciate your feedback regarding this. 

Thanks for your interest in YOLOv8, and please let us know if you have any additional questions!

**Comment by muellevin** [comment]
I think the the `augment` argument does not have any effect right now. I tested it with the Ultralytics YOLOv8.0.92 version. During Training the mAP with augment `True/False` are exactly the same.
After that i modified the the still undocumented augmentation values to be 0. Then i got a different mAP. It seems that currently you can not disable the augmentation.

You can get the configuration with `yolo cfg`. It will show you all options and avaiable augmentations.

**Comment by glenn-jocher** [comment]
@muellevin thank you for bringing this to our attention! We apologize for any confusion caused. It appears that the `augment` flag in YOLOv8 currently has no effect on whether the default data augmentation is being applied during training. Instead, data augmentation is always applied by default during training, and you can modify the set of transformations by modifying the code in the `augment.py` file or creating your own set of transformation functions. We appreciate your suggestion to include all options and available augmentations in the `yolo cfg` command, and we will take this into consideration for future updates to YOLOv8.
