### ISSUE TITLE
high to('cpu') operation time

### ISSUE THREAD

**Issue by mohsenp20** [ultralytics/ultralytics#2059]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

On rtx3070 gpu, the processing time of each frame with the 'yolov8m-pose.engine' model is only 3.2ms, while the 'result.to('cpu')' operation takes 60ms, which extremely drops the fps in real-time processing. Is there any suggestion or correction in this regard?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mohsenp20 thank you for reaching out with your bug report on YOLOv8 🔍! The `to('cpu')` operation can cause a noticeable delay when transferring data between the GPU and CPU. A couple of suggestions to improve processing time include upgrading to higher performing hardware or reviewing the `batch_size` configs to optimize performance for real-time processing. I hope this helps! If you have any further questions, don't hesitate to let us know.
