### ISSUE TITLE
Add docker manifest

### ISSUE THREAD

**Issue by grzegorzb1990** [ultralytics/ultralytics#2063]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Adding the docker manifest
https://docs.docker.com/engine/reference/commandline/manifest/

### Use case

An attempt to create an azure container from an ultralytics/ultralytics image fails. 
![image](https://user-images.githubusercontent.com/19983241/232344663-d99fba1a-d534-4423-9a2c-000def3a55c7.png)

This is because azure requires a published manifest.
https://learn.microsoft.com/en-us/answers/questions/1179992/(inaccessibleimage)-the-image-docker-io-presearch

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@grzegorzb1990 thank you for your contribution to YOLOv8! We appreciate your suggestion for adding a docker manifest to the docker image. While we understand the use case and will consider this feature request, we currently do not have plans to add a docker manifest to our public Docker image. However, we welcome pull requests from our community and future collaborations. In the meantime, please let us know if there's anything else we can help with or any further questions you may have.
