### ISSUE TITLE
Segment in YOLOV8 is Semantic-Segmentation or Instance Segmentation？

### ISSUE THREAD

**Issue by TommyZihao** [ultralytics/ultralytics#2064]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Segment in YOLOV8 is Semantic-Segmentation or Instance Segmentation？
What does it mean in txt label file?

**Comment by glenn-jocher** [comment]
Thank you for reaching out, @TommyZihao. YOLOv8 is an object detection model that performs instance segmentation, meaning it localizes and identifies each object instance in an image. The ground-truth `txt` label file for YOLOv8 contains a list of annotations for each object instance in the image, including its class, bounding box coordinates, and objectness score. It does not include segmentation masks. I hope this helps clarify your question. If you have any further questions, don't hesitate to ask.

**Comment by TommyZihao** [comment]
I check out coco128-seg sample dataset,
for example,  `000000000081.txt` only contains class_id and poly points, but no object instance bbox.
I think it is semantic segmentation, but no object instance.

![WX20230417-151258@2x](https://user-images.githubusercontent.com/36354458/232411984-58f5e994-2bbb-4b83-9759-b4bd6f3b1d88.png)

**Comment by Laughing-q** [comment]
@TommyZihao hi, we have a function inside to automatically calculate object boxes by segmentation points.
[https://github.com/ultralytics/ultralytics/blob/a38f22767254f2c2ee241490bd027987780d83ca/ultralytics/yolo/data/utils.py#L91](https://github.com/ultralytics/ultralytics/blob/a38f22767254f2c2ee241490bd027987780d83ca/ultralytics/yolo/data/utils.py#L91)
[https://github.com/ultralytics/ultralytics/blob/a38f22767254f2c2ee241490bd027987780d83ca/ultralytics/yolo/utils/ops.py#L501-L515](https://github.com/ultralytics/ultralytics/blob/a38f22767254f2c2ee241490bd027987780d83ca/ultralytics/yolo/utils/ops.py#L501-L515)

**Comment by TommyZihao** [comment]
In coco128-seg sample dataset, `000000000081.txt`, there are no bbox coordinates, but only poly points coordinates.

(4 means aeroplane)

```
4 0.596297 0.426306 0.716766 0.433106 0.850781 0.249435 0.912516 0.244894 0.868859 0.403624 0.912516 0.362824 0.97275 0.3492 0.886922 0.478447 0.900469 0.496588 0.900469 0.521553 0.861328 0.535153 0.876375 0.625859 0.816156 0.605435 0.783016 0.562353 0.659547 0.594094 0.611359 0.587294 0.501437 0.612235 0.511969 0.696141 0.525531 0.702941 0.513484 0.707482 0.533062 0.732424 0.518 0.739224 0.536062 0.748306 0.524016 0.768706 0.543594 0.804988 0.560156 0.802729 0.551125 0.814071 0.549625 0.843529 0.530047 0.825388 0.490891 0.820871 0.436688 0.766447 0.412594 0.795929 0.352359 0.795929 0.344828 0.777788 0.344828 0.743765 0.362906 0.725624 0.391516 0.723365 0.400547 0.725624 0.376453 0.696141 0.358391 0.712024 0.334297 0.721082 0.319234 0.725624 0.298156 0.721082 0.292125 0.705224 0.280078 0.678 0.289109 0.641718 0.316219 0.644 0.340313 0.639459 0.302672 0.598635 0.289109 0.580494 0.237922 0.553294 0.111437 0.551012 0.0677656 0.532871 0.0602344 0.498871 0.0798125 0.460306 0.134016 0.421765 0.189734 0.412706 0.236406 0.412706 0.370422 0.408165 0.370422 0.387765 0.382469 0.371882 0.409578 0.367341 0.435172 0.362824 0.45325 0.362824 0.505953 0.312918 0.505953 0.258494 0.585766 0.226753 0.734828 0.0952471 0.7785 0.0952471 0.780016 0.104306 0.674609 0.260776 0.695688 0.287976 0.6475 0.290259 0.659547 0.306118 0.664062 0.333341 0.644484 0.326541 0.620391 0.360541 0.644484 0.376424 0.605328 0.380941 0.585766 0.424047 0.602328 0.433106
```
![WX20230417-151258@2x](https://user-images.githubusercontent.com/36354458/232419232-5cf219a6-60d2-4bfe-b6c4-6602bb3ee659.png)

**Comment by glenn-jocher** [comment]
@TommyZihao yes that's correct. The boxes are computed from the maximum extents of the points, i.e. just [min(x), min(y), max(x), max(y)] for an xyxy box.

**Comment by TommyZihao** [comment]
get it, so there indeed is a implicit box, and it is truly instance segmentation, Thanks!

**Comment by 748811693aB** [comment]
> @TommyZihao yes that's correct. The boxes are computed from the maximum extents of the points, i.e. just [min(x), min(y), max(x), max(y)] for an xyxy box.

by the way ,Is there a function in the yolov8 project to output the vertex coordinates of the edges of an object based on the example segmentation result?

**Comment by glenn-jocher** [comment]
Certainly, @748811693aB. While YOLOv8 does not have a specific function for outputting the vertex coordinates of object edges, you can easily compute these points from the segmentation mask by finding the contours using OpenCV. To accomplish this, you can first convert the segmentation mask to a binary image, and then find the contours using the `cv2.findContours()` function. This will return a list of contours, where each contour is a list of points that form a closed polygon around the object. You can then iterate over the list of points for each contour and output its vertex coordinates.
