### ISSUE TITLE
What's in txt label file?

### ISSUE THREAD

**Issue by TommyZihao** [ultralytics/ultralytics#2066]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there any official doc of YOLO Darknet format txt label file?
For detection, segment and pose?

**Comment by TommyZihao** [comment]
Link 404 Not Find

**Comment by Laughing-q** [comment]
@TommyZihao Thanks for the reminding! we're working on the data format part in docs.:) Before that I'd like to share you the formats:
detection:
```
cls cx cy w h
```
segmentation
```
cls x1 y1 x2 y2...xn yn
```
pose
```
cls cx cy w h x1 y1 x2 y2...x17 y17
```
where the `cls` is the category of object, `cx` and `cy` are the center coordinates, `w` and `h` are the width and height of the objects, and all the coordinates are normalized by image size.
you can check the datasets folder for more examples. [https://github.com/ultralytics/ultralytics/tree/main/ultralytics/datasets](https://github.com/ultralytics/ultralytics/tree/main/ultralytics/datasets)

**Comment by TommyZihao** [comment]
Get it, Thanks!

**Comment by TommyZihao** [comment]
> @TommyZihao Thanks for the reminding! we're working on the data format part in docs.:) Before that I'd like to share you the formats: detection:
> 
> ```
> cls cx cy w h
> ```
> 
> segmentation
> 
> ```
> cls x1 y1 x2 y2...xn yn
> ```
> 
> pose
> 
> ```
> cls cx cy w h x1 y1 x2 y2...x17 y17
> ```
> 
> where the `cls` is the category of object, `cx` and `cy` are the center coordinates, `w` and `h` are the width and height of the objects, and all the coordinates are normalized by image size. you can check the datasets folder for more examples. https://github.com/ultralytics/ultralytics/tree/main/ultralytics/datasets

pose annotation is not right, you miss keypoint visibility, it should be:
`cls_id cx cy w h x1 y1 v1 x2 y2 v2 x3 y3 v3 ……`

**Comment by TommyZihao** [comment]
> @TommyZihao Thanks for the reminding! we're working on the data format part in docs.:) Before that I'd like to share you the formats: detection:
> 
> ```
> cls cx cy w h
> ```
> 
> segmentation
> 
> ```
> cls x1 y1 x2 y2...xn yn
> ```
> 
> pose
> 
> ```
> cls cx cy w h x1 y1 x2 y2...x17 y17
> ```
> 
> where the `cls` is the category of object, `cx` and `cy` are the center coordinates, `w` and `h` are the width and height of the objects, and all the coordinates are normalized by image size. you can check the datasets folder for more examples. https://github.com/ultralytics/ultralytics/tree/main/ultralytics/datasets

@Laughing-q pose annotation is not right, you miss keypoint visibility, it should be:
cls_id cx cy w h x1 y1 v1 x2 y2 v2 x3 y3 v3 ……
keypoint visibility: 0 means no point, 1 means occulision, 2 means ok

**Comment by glenn-jocher** [comment]
@TommyZihao you are correct! I apologize for the mistake. The correct format for pose is:

```
cls_id cx cy w h x1 y1 v1 x2 y2 v2 x3 y3 v3 …
``` 

where `v` represents the visibility of the keypoints. `0` means the point is not visible, `1` means the point is partially visible (occluded) and `2` means the point is fully visible. Thank you for pointing it out!

**Comment by Laughing-q** [comment]
> > @TommyZihao Thanks for the reminding! we're working on the data format part in docs.:) Before that I'd like to share you the formats: detection:
> > ```
> > cls cx cy w h
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > segmentation
> > ```
> > cls x1 y1 x2 y2...xn yn
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > pose
> > ```
> > cls cx cy w h x1 y1 x2 y2...x17 y17
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > where the `cls` is the category of object, `cx` and `cy` are the center coordinates, `w` and `h` are the width and height of the objects, and all the coordinates are normalized by image size. you can check the datasets folder for more examples. https://github.com/ultralytics/ultralytics/tree/main/ultralytics/datasets
> 
> @Laughing-q pose annotation is not right, you miss keypoint visibility, it should be: cls_id cx cy w h x1 y1 v1 x2 y2 v2 x3 y3 v3 …… keypoint visibility: 0 means no point, 1 means occulision, 2 means ok

Thanks for reminding! We actually support both the formats (with or without visible):
```bash
cls cx cy w h x1 y1 x2 y2...x17 y17
```
```bash
cls cx cy w h x1 y1 v1 x2 y2 v2 x3 y3 v3 …
```
you just need to modify the `kpt_shape` in your data.yaml:
```yaml
kpt_shape: [17, 3]     # 3 for the one includes visible, 2 for the one does not include visible
```
In this case you're able to train keypoints task with other number of keypoints, like facial landmark which usually includes 5 points and without an extra dimension `visible`.

BTW for generality we're saving txt files without visible dimension while predicting with `save_txt=True`.
```bash
yolo pose predict save_txt
```
