### ISSUE TITLE
Which part should i modify for recording the Learning rate on Tensorboard??

### ISSUE THREAD

**Issue by yellowjs0304** [ultralytics/ultralytics#2070]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I want to record learning rate score during training.
Which part should i modify to put the lr value on tensorboard?'

+) It looks like related with [yolo/utils/callbacks/tensorboard.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/utils/callbacks/tensorboard.py#L14), [yolo/entgine/trainer](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/engine/trainer.py#L353) maybe.

Also there's lr/pg0, lr/pg1 in csv(result.csv) file, but not in tensorboard.

**Comment by glenn-jocher** [comment]
@yellowjs0304 hi there! To record the learning rate score during training, you can modify the "tensorboard.py" file located at "yolo/utils/callbacks/". Specifically, you can add a line to log the learning rate using the "add_scalar" function from TensorBoard. Additionally, you can also check the "trainer.py" file located at "yolo/engine/" as it is responsible for the training process and can give you insights to where the learning rate value can be accessed. Keep in mind that the learning rate values are already recorded in the resulting "results.csv" file, so you can check that as well for reference. Hope this helps!
