### ISSUE TITLE
TypeError: build_dataloader() got an unexpected keyword argument 'names'

### ISSUE THREAD

**Issue by figurative666** [ultralytics/ultralytics#2071]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Traceback (most recent call last):
  File "ultralytics/yolo/v8/detect/train.py", line 274, in <module>
    train()
  File "ultralytics/yolo/v8/detect/train.py", line 216, in train
    trainer.train()
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/trainer.py", line 191, in train
    self._do_train(world_size)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/trainer.py", line 268, in _do_train
    self._setup_train(world_size)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/trainer.py", line 250, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
  File "ultralytics/yolo/v8/detect/train.py", line 49, in get_dataloader
    build_dataloader(cfg = self.args, batch = batch_size, img_path=dataset_path, stride=gs, rect = 'val', names=self.data['names'], rank=rank, mode=mode)[0]
TypeError: build_dataloader() got an unexpected keyword argument 'names'

How can we solve this problem？

**Comment by Laughing-q** [comment]
@figurative666 we have deprecated the arg `names` and use `data_info` instead, please upgrade the package and try again. :)
```bash
pip install -U ultralytics
```

**Comment by figurative666** [comment]
> @figurative666 we have deprecated the arg and use instead, please upgrade the package and try again. :)`names``data_info`
> 
> ```shell
> pip install -U ultralytics
> ```

It still doesn't work. Same error

**Comment by Laughing-q** [comment]
@figurative666 could you share me the command you used? I'd like to try and reproduce the issue.

**Comment by figurative666** [comment]
> 你能告诉我你使用的命令吗？我想尝试重现该问题。

python ultralytics/yolo/v8/detect/train.py

**Comment by figurative666** [comment]
> > 你能告诉我你使用的命令吗？我想尝试重现该问题。
> 
> python ultralytics/yolo/v8/detect/train.py

This command works fine on windows, but on Ubuntu, the above error occurs

**Comment by figurative666** [comment]
> @figurative666 it seems like the error is occurring because you're using the old argument instead of . Please use instead and let us know if the error persists. You can update the Ultralytics package via 。`names``data_info``data_info``pip install -U ultralytics`

I've tried running “pip install -U ultralytics”, but the problem hasn't been solved yet.

**Comment by Laughing-q** [comment]
@figurative666 still can't reproduce the issue.
![pic-full-230417-1915-53](https://user-images.githubusercontent.com/61612323/232468943-02e33bac-5e82-4c91-a80d-7cb6d2f8a91a.png)
probably there's something wrong of your package. I suggest you uninstall the package and reinstall it.

**Comment by figurative666** [comment]
> @figurative666 still can't reproduce the issue. ![pic-full-230417-1915-53](https://user-images.githubusercontent.com/61612323/232468943-02e33bac-5e82-4c91-a80d-7cb6d2f8a91a.png) probably there's something wrong of your package. I suggest you uninstall the package and reinstall it.

Thank you. The problem has been fixed. It is indeed a problem with the package.

**Comment by glenn-jocher** [comment]
@figurative666 you're welcome, glad to hear the issue has been resolved! If you have any other questions, feel free to ask. Remember to always keep your Ultralytics package updated to the latest version to avoid issues caused by deprecated arguments/imports etc.

**Comment by Huang-06** [comment]
> > @figurative666 still can't reproduce the issue. ![pic-full-230417-1915-53](https://user-images.githubusercontent.com/61612323/232468943-02e33bac-5e82-4c91-a80d-7cb6d2f8a91a.png) probably there's something wrong of your package. I suggest you uninstall the package and reinstall it.
> 
> Thank you. The problem has been fixed. It is indeed a problem with the package.

Could you please describe in detail how you solved this problem? I also encountered this problem.

**Comment by figurative666** [comment]
> 
Execute the following command:
cd ultralytics
pip install -e .        (Windows system)
pip install .            (Ubuntu system)

**Comment by figurative666** [comment]
> > > @figurative666 still can't reproduce the issue. ![pic-full-230417-1915-53](https://user-images.githubusercontent.com/61612323/232468943-02e33bac-5e82-4c91-a80d-7cb6d2f8a91a.png) probably there's something wrong of your package. I suggest you uninstall the package and reinstall it.
> > 
> > 
> > Thank you. The problem has been fixed. It is indeed a problem with the package.
> 
> Could you please describe in detail how you solved this problem? I also encountered this problem.

Execute the following command:
cd ultralytics
pip install -e . (Windows system)
pip install . (Ubuntu system)

**Comment by glenn-jocher** [comment]
@Huang-06 to resolve the issue, the user uninstalled and reinstalled the Ultralytics package using the appropriate commands for their operating system, i.e., "pip install -e ." for Windows and "pip install ." for Ubuntu. This helped fix any issues caused by deprecated arguments or imports. It is always a good practice to keep the package updated to the latest version to avoid such issues.
