### ISSUE TITLE
Can't train model without setting up WandB API connection

### ISSUE THREAD

**Issue by Abecadarian** [ultralytics/ultralytics#2073]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When I try to train my model on Kaggle, I can't continue the training until I enter an API key for wandb. Cntrl + c doesn't work to let me skip it.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Abecadarian thank you for reaching out. It seems like the issue you're experiencing is related to wandb, a tool we use for YOLOv8 training. To skip entering your wandb API key in Kaggle, you should be able to set the environment variable `WANDB_MODE` to `dryrun`. This will allow you to continue the training without authenticating with your API key. You can refer to the wandb documentation for more information on this. Let me know if you have any further questions or if this resolves your issue.

**Comment by turtlepile** [comment]
Hello,
We are having this problem, still. Will there be an update soon? thanks

**Comment by glenn-jocher** [comment]
@turtlepile hello! Thank you for reaching out and bringing up this issue. We are constantly working on improving YOLOv8, and we appreciate your input. However, it would be helpful if you could provide more details about the specific problem you're experiencing. This will enable us to better understand and address the issue. Feel free to provide any more background information or specific error messages you've encountered, and we'll do our best to help you find a solution. Thanks again for using YOLOv8!

**Comment by AlicanAKCA** [comment]
Has anyone solved that 'issue' ?

**Comment by glenn-jocher** [comment]
Hello @AlicanAKCA, thank you for reaching out. Without more specific information about the issue you are referring to, it is difficult to provide a direct answer. If you could provide additional context or error messages, we may be able to better understand and help resolve the issue. However, we encourage you to search our YOLOv8 repo issues and documentation for any solutions that may already exist. It is possible that others have experienced similar issues and have found solutions that may be helpful to you. Thanks for using YOLOv8, and we hope to hear back from you soon!

**Comment by devic1** [comment]
> Has anyone solved that 'issue' ?

Uninstall wandb Module before running the Training Cell

`!pip3 uninstall wandb`
 
it works for me

**Comment by glenn-jocher** [comment]
Hello @devic1, thank you for your solution suggestion. Uninstalling the wandb module is indeed one way of getting around the issue if you don't intend to use Weights & Biases for logging your training progress. Once wandb is uninstalled, the training should proceed without requiring an API key. Thank you for sharing this workaround, and we hope this helps others who encounter the same situation. We also encourage everyone to keep sharing their solutions and insights for the benefit of the entire YOLOv8 community.

**Comment by xzkeee** [comment]
> > Has anyone solved that 'issue' ?
> 
> Uninstall wandb Module before running the Training Cell
> 
> `!pip3 uninstall wandb`
> 
> it works for me

it works, thanks
