### ISSUE TITLE
strange issue on resuming Pose detection with custom dataset.

### ISSUE THREAD

**Issue by yellowjs0304** [ultralytics/ultralytics#2074]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I can't get it why there's strange dataset is loaded when using "resume" command.(Please see below image)

![image](https://user-images.githubusercontent.com/30281608/232432826-8025f8a7-4ad3-4303-9c32-9fdd4bf26454.png)

There's no error message without resume command.(it is running well)

**Comment by glenn-jocher** [comment]
@yellowjs0304 hello! When you use the "resume" command, YOLOv8 will load the most recent checkpoint for your specific training run. The dataset that you see in the image is likely a result of that checkpoint being trained on a different dataset than the one you intended to use in your current training run. To avoid this, make sure that you're training with the same dataset and settings that were used to create the checkpoint. Additionally, please review our documentation at https://docs.ultralytics.com/ for more information about how to correctly use the "resume" command. Let me know if you have any further questions.

**Comment by Laughing-q** [comment]
@yellowjs0304 please refer to the following example of resume:
```bash
yolo pose train model=last.pt data=keypoint.yaml resume
```
also refer to our docs: [https://docs.ultralytics.com/usage/cli/#train](https://docs.ultralytics.com/usage/cli/#train)
