### ISSUE TITLE
Multi-GPU DDP error

### ISSUE THREAD

**Issue by kbratsy** [ultralytics/ultralytics#2076]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Multi-GPU

### Bug

Running DDP command ['.../envs/yolov8/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '36503', '.../demo_debug.py', 'task=detect', 'mode=train', 'model=yolov8x.pt', 'data=.../data.yaml', 'epochs=2', 'patience=50', 'batch=32', 'imgsz=640', 'save=True', 'save_period=-1', 'cache=False', 'device=0,1', 'workers=8', 'project=None', 'name=None', 'exist_ok=False', 'pretrained=True', 'optimizer=SGD', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'image_weights=False', 'rect=False', 'cos_lr=False', 'close_mosaic=10', 'resume=False', 'amp=True', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'save_hybrid=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'source=None', 'show=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'hide_labels=False', 'hide_conf=False', 'vid_stride=1', 'line_thickness=3', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'boxes=True', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=False', 'opset=None', 'workspace=4', 'nms=False', 'lr0=0.01', 'lrf=0.01', 'momentum=0.937', 'weight_decay=0.0005', 'warmup_epochs=3.0', 'warmup_momentum=0.8', 'warmup_bias_lr=0.1', 'box=7.5', 'cls=0.5', 'dfl=1.5', 'fl_gamma=0.0', 'label_smoothing=0.0', 'nbs=64', 'hsv_h=0.015', 'hsv_s=0.7', 'hsv_v=0.4', 'degrees=0.0', 'translate=0.1', 'scale=0.2', 'shear=0.0', 'perspective=0.0', 'flipud=0.0', 'fliplr=0.5', 'mosaic=1.0', 'mixup=0.0', 'copy_paste=0.0', 'cfg=None', 'v5loader=False', 'tracker=botsort.yaml']
WARNING:main:

Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.

TypeError: 'IterableSimpleNamespace' object is not subscriptable

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 95015) of binary: .../envs/yolov8/bin/python

### Environment

- YOLO: Ultralytics YOLOv8.0.55 🚀 Python-3.8.10 torch-2.0.0 versions CUDA:0 (Tesla P100-16GB, 16281MiB) CUDA:1 (Tesla P100-16GB, 16281MiB)
- OS: CentOS7.3
- Python: 3.8.10

### Minimal Reproducible Example

from ultralytics import YOLO

model = YOLO("yolov8x.pt") 

results = model.train(data="../data.yaml", epochs=25, imgsz=640,device='0,1', batch=32) 
results = model.val() 
model.export()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by kbratsy** [comment]
> @kbratsy hi, I tested your script and it works fine in my case, also I noticed your package version is outdated, please upgrade the package and try again. :)
> 
> ```shell
> pip install -U ultralytics
> ```

Thank you for your answer.
After doing the update, I'm running into the following errors. How can I solve it? Is there any way you would suggest for a solution?

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 283881 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 283882) of binary: ..miniconda3/envs/yolov8/bin/python
Traceback (most recent call last):
  File "..miniconda3/envs/yolov8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "..miniconda3/envs/yolov8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "..miniconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "..miniconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "..miniconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "..miniconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "..miniconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "..miniconda3/envs/yolov8/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
Traceback (most recent call last):
  File "demo_debug.py", line 20, in <module>
    results = model.train(data="..demo/mersin-demo/data.yaml", epochs=25,workers=0,device=[0,1],batch=8, imgsz=640)  # train the model
  File "..miniconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 371, in train
    self.trainer.train()
  File "..miniconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 187, in train
    raise e
  File "..miniconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 185, in train
    subprocess.run(cmd, check=True)
  File "..miniconda3/envs/yolov8/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['..miniconda3/envs/yolov8/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '59756', '..demo/demo_debug.py', 'task=detect', 'mode=train', 'model=yolov8n.pt', 'data=..demo/mersin-demo/data.yaml', 'epochs=25', 'patience=50', 'batch=8', 'imgsz=640', 'save=True', 'save_period=-1', 'cache=False', 'device=[0, 1]', 'workers=0', 'project=None', 'name=None', 'exist_ok=False', 'pretrained=False', 'optimizer=SGD', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'image_weights=False', 'rect=False', 'cos_lr=False', 'close_mosaic=0', 'resume=False', 'amp=True', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'save_hybrid=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'source=None', 'show=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'show_labels=True', 'show_conf=True', 'vid_stride=1', 'line_thickness=3', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'boxes=True', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=False', 'opset=None', 'workspace=4', 'nms=False', 'lr0=0.01', 'lrf=0.01', 'momentum=0.937', 'weight_decay=0.0005', 'warmup_epochs=3.0', 'warmup_momentum=0.8', 'warmup_bias_lr=0.1', 'box=7.5', 'cls=0.5', 'dfl=1.5', 'pose=12.0', 'kobj=1.0', 'label_smoothing=0.0', 'nbs=64', 'hsv_h=0.015', 'hsv_s=0.7', 'hsv_v=0.4', 'degrees=0.0', 'translate=0.1', 'scale=0.5', 'shear=0.0', 'perspective=0.0', 'flipud=0.0', 'fliplr=0.5', 'mosaic=1.0', 'mixup=0.0', 'copy_paste=0.0', 'cfg=None', 'v5loader=False', 'tracker=botsort.yaml']' returned non-zero exit status 1.

**Comment by Laughing-q** [comment]
@kbratsy hey I'm not able to reproduce the issue.
```python
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model.train(data="coco128.yaml", epochs=25, imgsz=640,device='0,1', batch=32)
results = model.val()
```
![pic-full-230417-1822-52](https://user-images.githubusercontent.com/61612323/232457892-a8215fcf-f73c-4bb1-a000-5e75ab61e32e.png)

BTW can you share the full error log?

**Comment by kbratsy** [comment]
> @kbratsy hey I'm not able to reproduce the issue.
> 
> ```python
> from ultralytics import YOLO
> 
> model = YOLO("yolov8n.pt")
> 
> results = model.train(data="coco128.yaml", epochs=25, imgsz=640,device='0,1', batch=32)
> results = model.val()
> ```
> 
> ![pic-full-230417-1822-52](https://user-images.githubusercontent.com/61612323/232457892-a8215fcf-f73c-4bb1-a000-5e75ab61e32e.png)
> 
> BTW can you share the full error log?

I have attached the full error log "Error_log.txt".
[Error_log.txt](https://github.com/ultralytics/ultralytics/files/11249158/Error_log.txt)

**Comment by Laughing-q** [comment]
@kbratsy hi, this is because the code will automatically launch the script in the DDP way if you point multi devices. so in your case, the `model.val()` is also running in two threads which is not expected. This might take some time to come up a solution to fix it, before that I recommend you the following usage for now:
```python
from ultralytics import YOLO
from ultralytics.yolo.utils import RANK

model = YOLO("yolov8n.pt")

results = model.train(data="coco128.yaml", epochs=1, imgsz=640,device='0,1', batch=32)
if RANK in (0, -1):
    results = model.val()
```
Thanks!

**Comment by kbratsy** [comment]
Hello,
I can use it now with the usage you suggested, thanks. :)

**Comment by glenn-jocher** [comment]
@kbratsy glad to hear that! The issue previously reported was due to using multiple devices during training, which triggers the DDP mode of launching the code, leading to unexpected behavior when calling `model.val()`. By wrapping the validation code under an if statement checking the rank of the process, the validation script is only run once, which solves the problem for now.

**Comment by kbratsy** [comment]
Yes, I got the error and this is a workaround for now. Then when I added model.export() to the code, I got the same error again. I applied the solution you mentioned in this error and it worked.
If RANK==0:
      model.export()

Thanks. :))

**Comment by glenn-jocher** [comment]
@kbratsy sure, I'm glad my solution worked for you. The issue you faced when running `model.export()` was similar to the previous issue with `model.val()` in that using multiple devices during training triggers the DDP mode, which leads to unexpected behavior when calling `model.export()`. The solution is to wrap the export code under an if statement checking the rank of the process (`if RANK==0:`). This ensures that the export code is only run once, by the process with rank 0, and eliminates any possible issues caused by running it on multiple threads.

**Comment by ignaciohrdz** [comment]
Hi, I'm facing a similar issue. I've done `pip install -U ultralytics`  already but it did not solve the issue.

The training script is [here](https://github.com/ignaciohrdz/yolo-face-parts-detector/blob/main/train.py). The line in my code that does the training is almost identical to the example by @Laughing-q:

```
for m in ['n', 's', 'm', 'l', 'x']:
    model = YOLO("weights/yolov8{}.pt".format(m))

    # Train the model
    results = model.train(data=path_yaml, task="detect", name="train_{}".format(m),
                          epochs=args.epochs, batch=args.batch_size,
                          device=",".join(args.device),
                          scale=0.25,
```

My error log is [here](https://github.com/ultralytics/ultralytics/files/11303381/error_log.txt). The code is working fine when I use one GPU only.

Thanks!

**Comment by Laughing-q** [comment]
@ignaciohrdz hi, yeah technically the for loop in your script probably will not work as expect, we're trying to optimize this case. For now I recommend you to launch each training in each python file instead of including 5 training in one file. or launch training with a bash script, something like this:
```bash
for i in "n" "s" "m" "l" "x";
  do yolo train data=... name="train_$i";
done
```

**Comment by vgarg11** [comment]
I am getting the following error when I try to train 

CalledProcessError: Command '['/home/ec2-user/anaconda3/envs/tensorflow2_p310/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '36195', '/home/ec2-user/.config/Ultralytics/DDP/_temp_vx81sjah140128352409424.py']' returned non-zero exit status 1.

Here is my code

from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.yaml')  # build a new model from YAML
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)
model = YOLO('yolov8n.yaml').load('yolov8n.pt')  # build from YAML and transfer weights

training_data = '/home/ec2-user/SageMaker/machine-learning-data-intellicheck/image-cropping/data.yaml'

# Train the model
results = model.train(data=training_data, epochs=1, imgsz=640, device='0,1,2,3')

**Comment by glenn-jocher** [comment]
@vgarg11 hey there! 😊 It looks like you're encountering an issue when trying to train on GPU. This error typically occurs due to a setup issue with distributed training or a mismatch in the environment setup. Here are a couple of things you might want to check:

1. Ensure that your environment is correctly set up for GPU usage. This includes having the correct version of PyTorch installed that supports CUDA, and that your CUDA drivers are up to date.
2. When specifying `device='0,1,2,3'`, make sure that your system actually has 4 GPUs available. You can check this by running `nvidia-smi` in your terminal.
3. Try running the training with a single GPU first to isolate the issue. You can do this by setting `device='0'`.

If you're still facing issues, it might be helpful to provide more details about your environment, such as the PyTorch and CUDA versions you're using. This will help in diagnosing the problem more accurately. 

Hope this helps! Let us know how it goes.

**Comment by vgarg11** [comment]
Thank you for your reply. I was getting this error on Sagemaker when I was running Tensorflow kernel. Once I switched to Torch kernel, it worked.

**Comment by glenn-jocher** [comment]
@vgarg11 great to hear switching to the Torch kernel resolved the issue for you! 😊 If you encounter any more challenges or have questions while working with YOLOv8, feel free to reach out. Happy coding!

**Comment by HonestyBrave** [comment]
> > @kbratsy hey I'm not able to reproduce the issue.
> > ```python
> > from ultralytics import YOLO
> > 
> > model = YOLO("yolov8n.pt")
> > 
> > results = model.train(data="coco128.yaml", epochs=25, imgsz=640,device='0,1', batch=32)
> > results = model.val()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![pic-full-230417-1822-52](https://user-images.githubusercontent.com/61612323/232457892-a8215fcf-f73c-4bb1-a000-5e75ab61e32e.png)
> > BTW can you share the full error log?
> 
> I have attached the full error log "Error_log.txt". [Error_log.txt](https://github.com/ultralytics/ultralytics/files/11249158/Error_log.txt)

@Laughing-q hi，我训练的时候遇到了和你图片中一样的内容，就是：
UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later ...

这个对训练出来的模型有没有影响，该怎么解决呀，多谢，还请帮忙看看
