### ISSUE TITLE
how can i change the label font size : beginner's question

### ISSUE THREAD

**Issue by BoscoShin** [ultralytics/ultralytics#2077]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i used the predict method(results = model(my source(mp4)....), and i got a prediction result. 

but i I want a small font, label box  in result img or video.

so, how can i change the label font size?

thanks.

**Comment by Laughing-q** [comment]
@BoscoShin here's an example of changing the font size.
```python
from ultralytics import YOLO
import cv2

model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)
frame = cv2.imread("ultralytics/assets/bus.jpg")
results = model.predict(frame, save=False)
img = results[0].plot(font_size=20, pil=True)
cv2.imwrite("1.jpg", img)
```
BTW `font_size` only works with pil so you need to set `pil=True`.

**Comment by BoscoShin** [comment]
> @BoscoShin here's an example of changing the font size.
> 
> ```python
> from ultralytics import YOLO
> import cv2
> 
> model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)
> frame = cv2.imread("ultralytics/assets/bus.jpg")
> results = model.predict(frame, save=False)
> img = results[0].plot(font_size=20, pil=True)
> cv2.imwrite("1.jpg", img)
> ```
> 
> BTW `font_size` only works with pil so you need to set `pil=True`.

Thanks you!!!

**Comment by Laughing-q** [comment]
@BoscoShin Then I'm closing the issue, please feel free to reopen it if you have related issues. :)

**Comment by BoscoShin** [comment]
> @BoscoShin Then I'm closing the issue, please feel free to reopen it if you have related issues. :)

sorry. i have a problem.

i tried plot method, it doesn't work(There's no label output. Only the source video came out.). 
Labels were printed when nothing was included in the plot method.

here's my code
---------------------------------
def predict_video():
    import cv2
    from ultralytics import YOLO
    import time
    
    prev_frame_time = 0
    
    new_frame_time = 0
    
# Load the YOLOv8 model
    model = YOLO('runs/detect/train30/weights/best.pt')

# Open the video file
    video_path = "assets/mask5.mp4"
    cap = cv2.VideoCapture(video_path)

# Loop through the video frames
    while cap.isOpened():
    # Read a frame from the video
        success, frame = cap.read()

        if success:
        # Run YOLOv8 inference on the frame
            results = model(frame, save=True, conf=0.4)
            
            frame = results[0].plot(line_width=5, font_size=10, pil=True)

        # Visualize the results on the frame
            frame = cv2.resize(frame, (720, 480))
            font = cv2.FONT_HERSHEY_SIMPLEX
            
            new_frame_time = time.time()
            
            fps = 1/(new_frame_time-prev_frame_time)
            prev_frame_time = new_frame_time
            
            fps = int(fps)
            fps = str(fps)
            
            cv2.putText(frame, fps, (7, 70), font, 3, (100, 255, 0), 3, cv2.LINE_AA)

        # Display the annotated frame
            cv2.imshow("Detection", frame)
            
        # Break the loop if 'q' is pressed
            if cv2.waitKey(1) & 0xFF == ord("q"):
                break
        else:
        # Break the loop if the end of the video is reached
            break

# Release the video capture object and close the display window
    cap.release()
    cv2.destroyAllWindows()
    
if __name__=='__main__':
    predict_video()

**Comment by Laughing-q** [comment]
@BoscoShin if the image is not plotted, probably because the model does not detect anything.
the plotting works well to me if the model detects objects.
![pic-full-230417-1829-57](https://user-images.githubusercontent.com/61612323/232459117-4c98b63f-150b-4a72-8aff-5da0152d73be.png)

**Comment by BoscoShin** [comment]
> @BoscoShin if the image is not plotted, probably because the model does not detect anything. the plotting works well to me if the model detects objects. ![pic-full-230417-1829-57](https://user-images.githubusercontent.com/61612323/232459117-4c98b63f-150b-4a72-8aff-5da0152d73be.png)

i tried example code.

but i have same problem.

so. i will update the v8 lib. then i re-try the code

can u wait for me?

![p](https://user-images.githubusercontent.com/75238411/232466974-0102e4a9-522d-4d49-a37c-6c9415e401e1.png)
![p1](https://user-images.githubusercontent.com/75238411/232466997-16a4610e-25dc-4a8e-86c8-55973a0639f6.png)

**Comment by BoscoShin** [comment]
i fixed it.

the version was problem!

thanks you

**Comment by glenn-jocher** [comment]
@BoscoShin i'm glad to hear you solved the issue. It sounds like you were using an outdated version of Ultralytics YOLOv8. It's always a good idea to make sure your dependencies are up to date to avoid any possible version-related issues. If you encounter any more problems or have any other questions in the future, feel free to open a new issue.

**Comment by MoAbbasid** [comment]
hi @Laughing-q , If I want to set font_size while using ndarray, PIL=False, what to do?

**Comment by Y-T-G** [comment]
@MoAbbasid It's not supported. You can change the ndarray to PIL image before inference

```python
from PIL import Image

img = Image.fromarray(array)
```

**Comment by MoAbbasid** [comment]
I found that line_width param shrinks the size instead of font size for ndarrays to get the desired effect.
```
result.plot(line_width=_)
```

**Comment by glenn-jocher** [comment]
The `line_width` parameter adjusts the thickness of bounding boxes, not font size. For font adjustments, consider using PIL with `font_size`.
