### ISSUE TITLE
Support for Jetson deployment

### ISSUE THREAD

**Issue by Alberto1404** [ultralytics/ultralytics#208]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi! Can't wait to read your paper soon!
It would be awesome to deploy this new member of the Yolo family in Nvidia Jetson. Looking forward to getting the docs updated with this info. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Linaom1214** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.
> 
> ### Description
> Hi! Can't wait to read your paper soon! It would be awesome to deploy this new member of the Yolo family in Nvidia Jetson. Looking forward to getting the docs updated with this info.
> 
> ### Use case
> _No response_
> 
> ### Additional
> _No response_
> 
> ### Are you willing to submit a PR?
> * [ ]  Yes I'd like to help by submitting a PR!

@Alberto1404  you can see my project. https://github.com/Linaom1214/TensorRT-For-YOLO-Series

**Comment by FeiYull** [comment]
@Alberto1404 Hi, If you want to make full use of GPU to run yolo family(yolov8 v7 v6 v5 v4 v3 yolox yolox), you can try this repository: https://github.com/FeiYull/tensorrt-alpha      We use cuda to accelerate image processing, inference, decode and NMS.☺️☺️☺️☺️

**Comment by Alberto1404** [comment]
> 

@FeiYull Do you use Deepstream in your repo?

**Comment by Linaom1214** [comment]
> > 
> 
> @FeiYull Do you use Deepstream in your repo?

@Alberto1404  ,this project maybe can help you. 

https://github.com/triple-Mu/YOLOv8-TensorRT

@triple-Mu

**Comment by FeiYull** [comment]
@Alberto1404 Although we does not support DeepStream, but we supports CUDA C END2END infer and supports multi-batch infer.

**Comment by Alberto1404** [comment]
> > > 
> > 
> > 
> > @FeiYull Do you use Deepstream in your repo?
> 
> @Alberto1404 ,this project maybe can help you.
> 
> https://github.com/triple-Mu/YOLOv8-TensorRT
> 
> @triple-Mu

Thank you so much @Linaom1214!

**Comment by triple-Mu** [comment]
@Linaom1214  @Alberto1404  Thank you all for your attention!
