### ISSUE TITLE
labels graphs - what do they correspond to and clearer graph titles

### ISSUE THREAD

**Issue by bobyfisch** [ultralytics/ultralytics#2086]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, 

I have seen the labels.jpg and labels_correologram.jpg that YOLOv8 outputs after training. 

**I think the data in these graphs corresponds to the labels in the train set and after image augmentation. Is this correct?** 

I think this could be indicated in the graph titles inside the images (ex: title: label data for train data set after image augmentation) or in the docs some place. Also: including the total number of images/labels could be very useful. 

Furthermore, Indicating that the confusion matrix corresponds to the validation set couldn't hurt. As all (trian/val) graphs are saved in the same "train" folder (when doing a train run with a .yaml that points to train and validation folders) it can get confusing as to which graph corresponds to which data set.

Thank you,

Alex

**Comment by Laughing-q** [comment]
@bobyfisch thanks for the suggestions! one thing I need to correct is that the data in these graphs does correspond to the labels in the train set **without** image augmentation.

**Comment by bobyfisch** [comment]
@glenn-jocher @Laughing-q thank you very much for both answers! I proceed to closing the issue.

**Comment by glenn-jocher** [comment]
@bobyfisch You're welcome! If you have any further questions or suggestions, feel free to open a new issue. We'll be happy to help you.
