### ISSUE TITLE
Train yolov8n-cls on a custom dataset

### ISSUE THREAD

**Issue by martin0496** [ultralytics/ultralytics#2087]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi all,

I am Training yolov8n-cls on a custom dataset for binary classification.
I am facing some issues with the input data format. 
in detection tasks, we have txt file for each image with the coordinates and class of each bounding box.
Here we are not using bounding boxes , how should I create the labelled dataset for training ? 

Thank you

**Comment by AyushExel** [comment]
No. For classification, you can use the existing torch-vision folder structure where each class is represented as its own folder.
To train, you can simply pass the path of that folder as `data=path/to/dataset_folder`
