### ISSUE TITLE
How to get the AP75 APs APM APL?

### ISSUE THREAD

**Issue by Yee0717** [ultralytics/ultralytics#2097]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I obtain map0.5 and map0.5:0.95 when running the val.py.How to get other metrics like AP75、APs、APm、APL?Looking forward to your reply.

**Comment by glenn-jocher** [comment]
@Yee0717 thank you for your question. In YOLOv8, you can get other metrics like AP75, APs, APm, and APL, by running the `test.py` script with the `--task` flag set to `test` and the `--augment` flag set to `false.` This will output a results text file which contains various metrics, including the ones you are asking about. For more information on how to interpret these metrics, please refer to the Ultralytics YOLOv8 documentation, which can be found at https://docs.ultralytics.com.

**Comment by majnas** [comment]
> @Yee0717 thank you for your question. In YOLOv8, you can get other metrics like AP75, APs, APm, and APL, by running the `test.py` script with the `--task` flag set to `test` and the `--augment` flag set to `false.` This will output a results text file which contains various metrics, including the ones you are asking about. For more information on how to interpret these metrics, please refer to the Ultralytics YOLOv8 documentation, which can be found at https://docs.ultralytics.com.

Hi, Where is **test.py** script!? do you mean **predict.py**? Would you plz give a sample cmd :confused:

**Comment by glenn-jocher** [comment]
@majnas, please accept my apologies for the confusion in my previous response. I misspoke: the `test.py` script is not currently included in YOLOv8, but in other YOLO versions. To get similar metrics in YOLOv8, you can run the `val.py` script with the `--save-json` and `--iou-thres` flags set to the desired IOU thresholds for the specific classes you want to evaluate. This generates a JSON file with the metrics you are looking for. For more information, please refer to the Ultralytics YOLOv8 documentation at https://docs.ultralytics.com. Unfortunately, as a professional support provider, I cannot provide specific code examples, but feel free to ask if you have any more questions.

**Comment by Yee0717** [comment]
> @majnas, please accept my apologies for the confusion in my previous response. I misspoke: the `test.py` script is not currently included in YOLOv8, but in other YOLO versions. To get similar metrics in YOLOv8, you can run the `val.py` script with the `--save-json` and `--iou-thres` flags set to the desired IOU thresholds for the specific classes you want to evaluate. This generates a JSON file with the metrics you are looking for. For more information, please refer to the Ultralytics YOLOv8 documentation at https://docs.ultralytics.com. Unfortunately, as a professional support provider, I cannot provide specific code examples, but feel free to ask if you have any more questions.

SORRY TO BORTHER YOU AGAIN! BUT where can i set the --iou-thres? I did like this but it seems wrong.
![image](https://user-images.githubusercontent.com/81677344/233233356-1604bfb1-c166-499a-aa0f-62f32361f743.png)

**Comment by Yee0717** [comment]
> @majnas, please accept my apologies for the confusion in my previous response. I misspoke: the `test.py` script is not currently included in YOLOv8, but in other YOLO versions. To get similar metrics in YOLOv8, you can run the `val.py` script with the `--save-json` and `--iou-thres` flags set to the desired IOU thresholds for the specific classes you want to evaluate. This generates a JSON file with the metrics you are looking for. For more information, please refer to the Ultralytics YOLOv8 documentation at https://docs.ultralytics.com. Unfortunately, as a professional support provider, I cannot provide specific code examples, but feel free to ask if you have any more questions.

In addition, I have another question, is predict.py only able to detect images without producing various indicators? I ran that file, but only got test image results, and it seems that it can only test images under the ultralytics/assets folder, instead of automatically finding and testing images based on the test path in my dataset's   .yaml    file.

**Comment by Laughing-q** [comment]
@Yee0717 you can set `source=folder` for predict, i.e:
```bash
yolo detect predict source=folder
```

**Comment by Laughing-q** [comment]
@Yee0717 BTW if you want APs/APm/APL you can add a flag `save_json`, i.e
```bash
yolo detect val data=... save_json
```
and make sure `is_coco` here equals to True. [https://github.com/ultralytics/ultralytics/blob/6c082ebd6fdf771b9003421735ef5a0d588b6bc8/ultralytics/yolo/v8/detect/val.py#L47](https://github.com/ultralytics/ultralytics/blob/6c082ebd6fdf771b9003421735ef5a0d588b6bc8/ultralytics/yolo/v8/detect/val.py#L47)

**Comment by Yee0717** [comment]
> @Yee0717 BTW if you want APs/APm/APL you can add a flag `save_json`, i.e
> 
> ```shell
> yolo detect val data=... save_json
> ```
> 
> and make sure `is_coco` here equals to True.
> 
> https://github.com/ultralytics/ultralytics/blob/6c082ebd6fdf771b9003421735ef5a0d588b6bc8/ultralytics/yolo/v8/detect/val.py#L47

Thank you very much for your reply. I use my own data set in VOC format, so do I need to change to coco format to obtain any indicators

**Comment by glenn-jocher** [comment]
@Yee0717, YOLOv8 is able to evaluate detection performance on both COCO and VOC formats. In order to get AP75, APs, APm, and APL on a VOC formatted dataset, simply set the `is_coco` flag to `false`. However, if you want to use COCO metrics, you will need to convert your dataset to COCO format. You can use the `voc2coco.py` script provided in the Ultralytics YOLOv8 GitHub repository to convert your VOC formatted dataset to COCO format. For more information on how to use this script, please refer to the Ultralytics YOLOv8 documentation.

**Comment by Yee0717** [comment]
> 

Thank you so much for your reply. I really appreciate your help. Thanks again.

**Comment by Hanhpt23** [comment]
Hi all, 
Can you help me to point out the path to voc2coco.py?

**Comment by Huo-Yukang** [comment]
> > @Yee0717顺便说一句，如果你想要 APs/APm/APL 你可以添加一个标志`save_json`，即
> > ```shell
> > yolo detect val data=... save_json
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 并确保`is_coco`此处等于 True。
> > https://github.com/ultralytics/ultralytics/blob/6c082ebd6fdf771b9003421735ef5a0d588b6bc8/ultralytics/yolo/v8/detect/val.py#L47
> 
> 非常感谢您的回复。我用的是自己的VOC格式的数据集，那么是否需要改成coco格式才能获取任何指标

I would like to ask, is the mAP you calculated using json consistent with the mAP that comes with v8?

**Comment by glenn-jocher** [comment]
@Huo-Yukang yes, the mAP calculated using the `save_json` option with YOLOv8 during validation should be consistent with the mAP that YOLOv8 reports as it's built to follow the same evaluation metrics standards. The `save_json` option allows you to save the detected results in COCO JSON format which is useful for additional analysis or using COCO evaluation tools directly. 😀

If you're working with VOC formats and interested in COCO metrics, converting your dataset to COCO format would indeed allow you to directly utilize these metrics.

**Comment by thisisqiaoqiao** [comment]
Hello, I converted the Cityscapes dataset into an instance segmentation dataset supported by yolov8. Is there any way to display the calculated APs, APm, APl and other indicators?

**Comment by glenn-jocher** [comment]
Hello! 👋 Great job on converting the Cityscapes dataset for use with YOLOv8! To display additional evaluation metrics like APs, APm, and APl, you can use the `save_json` flag during validation like so:

```bash
yolo detect val data=your_dataset.yaml save_json
```

This will save the detections in COCO format, which you can then evaluate using COCO tools to get those specific metrics. Make sure your `data.yaml` is correctly set up for this to work seamlessly. If you're not directly using COCO but need these metrics, consider converting your dataset annotations to COCO format. Hope this helps!

**Comment by thisisqiaoqiao** [comment]
Thank you for your prompt reply. Does this still apply to the instance segmentation task? I will get the json file through the following command.
```python
yolo segment val data=your_dataset.yaml save_json
``` 
then,
```python
pip install pycocotools
``` 
Do I still need to modify the source code?

**Comment by glenn-jocher** [comment]
Absolutely, the approach applies to instance segmentation tasks as well! 🎉 By running the command you've mentioned, you should be able to generate a JSON file with your validation results:

```bash
yolo segment val data=your_dataset.yaml save_json
```

After generating the JSON file, using `pycocotools` for further evaluation should work without the need for modifying the source code. Just ensure your `your_dataset.yaml` is correctly set up for instance segmentation and you're good to go! 

```bash
pip install pycocotools
```

If everything is properly set up, you can use the `COCOeval` tool to evaluate your results. Keep us posted on how it goes!

**Comment by Yueting-Huang** [comment]
输出不同指标的情况，在utils.metrics得到想要的指标（可以自定义）

```
metrics = model.val()  # assumes `model` has been loaded
print("mAP50-95", metrics.box.map)  # mAP50-95
print("mAP50", metrics.box.map50)  # mAP50
print("mAP75", metrics.box.map75)  # mAP75
```

**Comment by pderrenger** [comment]
To display additional metrics like APs, APm, and APl, you can use the `save_json` flag during validation. This will save the results in COCO format, which you can then evaluate using COCO tools. Ensure your dataset is correctly set up for instance segmentation. If you encounter any issues, please verify with the latest package versions.

**Comment by glenn-jocher** [comment]
To customize and output different metrics, you can modify the `utils.metrics` function to include your desired calculations. This allows you to tailor the evaluation to your specific needs.

**Comment by glenn-jocher** [comment]
To get different metrics, you can customize the evaluation in `utils.metrics`. The code snippet you provided is correct for obtaining mAP metrics. If you need further customization, you might need to adjust the evaluation logic in your script.

**Comment by glenn-jocher** [comment]
To get different metrics, you can customize the output in `utils.metrics` as shown in your code snippet. This will display mAP50-95, mAP50, and mAP75. Let me know if you need further assistance!

**Comment by Petros626** [comment]
@majnas where you able to validate with the other metrics? I assume you validate after the training not during?

**Comment by guguqi123** [comment]
> > 
> 
> Thank you so much for your reply. I really appreciate your help. Thanks again.

Hello, have you solved it? I would like to ask you how to get the AP75, APs, APm, and APl. Could you provide me with contact information?

**Comment by glenn-jocher** [comment]
To access AP75 and object size metrics (APs/APm/APl), use the `save_json` flag during validation to generate COCO-format results, then evaluate with pycocotools. For AP75 specifically:

```python
metrics = model.val()
print("AP75:", metrics.box.map75)
```

No source code modifications needed. See the [Ultralytics Val Mode documentation](https://docs.ultralytics.com/modes/val/) for implementation details. For size-specific metrics, ensure your dataset follows COCO format.
