### ISSUE TITLE
YOLOv8 model metrics plot and so on

### ISSUE THREAD

**Issue by isLinXu** [ultralytics/ultralytics#210]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I would like to ask why the accuracy of the YOLOV8 model is different from my own verification, and whether the model weight and the network have been updated. In addition, here I draw a comparison chart of multiple model indicators. 
I want to ask if there are any errors or places that need to be modified. I can improve it in time.
By the way, whether the Chinese version of the readme is already written, if not, I can submit PR.
Github：https://github.com/isLinXu/YOLOv8_Efficient

![plot_metrics](https://user-images.githubusercontent.com/59380685/211603372-d8a8efe0-d5c6-449a-bbc0-cff042f975f1.jpg)

**Comment by AyushExel** [comment]
Ohh that is because you're comparing p6 models(1280pixel size) with base models 640. That is not right.. We'll provide official trt benchmarks soon.

**Comment by isLinXu** [comment]
okay,I got it,thanks.

**Comment by isLinXu** [comment]
> Ohh that is because you're comparing p6 models(1280pixel size) with base models 640. That is not right.. We'll provide official trt benchmarks soon.

By the way, whether the Chinese version of the readme is already written, if not, I can submit PR.

**Comment by AyushExel** [comment]
Yes its written here https://github.com/ultralytics/ultralytics/blob/main/README.zh-CN.md

**Comment by isLinXu** [comment]
Okay,I see it,good job👍🏻

**Comment by AyushExel** [comment]
Please see the readme for plots. We'll add more plots soon
