### ISSUE TITLE
'rect=True' is incompatible with DataLoader shuffle

### ISSUE THREAD

**Issue by HornGate** [ultralytics/ultralytics#2102]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

WARNING ⚠️ 'rect=True' is incompatible with DataLoader shuffle, setting shuffle=False.

Does it affect training efficience?

**Comment by glenn-jocher** [comment]
@HornGate the warning message indicates that the 'rect' parameter is incompatible with the 'shuffle' parameter in DataLoader, and thus 'shuffle' has been set to False. This only affects the shuffling of data during training and should not significantly impact the efficiency of training. In general, it is advisable to avoid using rect=True with DataLoader shuffle, as it may lead to incorrect data being fed to the model. For more information about DataLoader parameters and usage, please refer to https://docs.ultralytics.com/.
