### ISSUE TITLE
show not working. `BasePredictor` has both a `show` variable and `show` method which conflict

### ISSUE THREAD

**Issue by RobMulla** [ultralytics/ultralytics#212]
I am trying to run yolov8 and have it show the live predictions but am getting this error. Both in the CLI and python API version of yolov8.

```
$ yolo task=detect mode=predict model=yolov8n.pt source=5 show=True
Ultralytics YOLOv8.0.2 🚀 Python-3.8.15 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11178MiB)
Fusing layers... 
YOLOv8n summary: 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
VIDEOIO ERROR: V4L2: property frame_count is not supported
1/1: 5...  Success (inf frames 640x480 at 30.00 FPS)

Error executing job with overrides: ['task=detect', 'mode=predict', 'model=yolov8n.pt', 'source=5', 'show=True']
Traceback (most recent call last):
  File "/home/robmulla/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/cli.py", line 52, in cli
    func(cfg)
  File "/home/robmulla/anaconda3/envs/yolov8/lib/python3.8/site-packages/hydra/main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "/home/robmulla/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/v8/detect/predict.py", line 92, in predict
    predictor()
  File "/home/robmulla/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/robmulla/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 180, in __call__
    self.show(p)
TypeError: 'bool' object is not callable

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
terminate called without an active exception
Aborted (core dumped)
```

I believe the issue is caused because the `BasePredictor` class has both a `show` variable and `show` method which conflict and it attempts to call the variable to display, which obviously fails.

variable: https://github.com/ultralytics/ultralytics/blob/dba3f178849692a13f3c43e81572255b1ece7da9/ultralytics/yolo/engine/predictor.py#L91
method: 
https://github.com/ultralytics/ultralytics/blob/dba3f178849692a13f3c43e81572255b1ece7da9/ultralytics/yolo/engine/predictor.py#L202
where it fails:
https://github.com/ultralytics/ultralytics/blob/dba3f178849692a13f3c43e81572255b1ece7da9/ultralytics/yolo/engine/predictor.py#L180

**Comment by AyushExel** [comment]
Thanks for reporting.
@glenn-jocher it was introduced in the patch release PR https://github.com/ultralytics/ultralytics/pull/169/files#diff-bd2831d027341da2474db760605211ea00b347396b0d708a4343a2b709eb3675

**Comment by kadirnar** [comment]
Hi @AyushExel ,

I am writing demo code(Hugging Face) for yolov8. I am using the save parameter. I need the save_path variable. How can I do that?
Code:
```
model = YOLO(model_path)
model.conf = conf_threshold
model.iou = iou_threshold
prediction = model.predict(source=image, imgsz=image_size, save=True)
```
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/v8/detect/predict.py#L71 ?

**Comment by glenn-jocher** [comment]
@kadirnar save_path = PROJECT/NAME together, i.e. model.predict(pass project=PROJECT, name=NAME)

**Comment by glenn-jocher** [comment]
@RobMulla I've pushed a fix for this in #218 and a previous PR and will deploy 8.0.3 that includes this shortly.

**Comment by glenn-jocher** [comment]
@RobMulla done. Please upgrade to 8.0.3 and let us know if the issue persists:
```
pip install -U ultralytics
```

**Comment by kadirnar** [comment]
> @kadirnar save_path = PROJECT/NAME together, i.e. model.predict(pass project=PROJECT, name=NAME)

This isn't it. I want the path information of my saved image. So you need to add return code.
Demo: https://huggingface.co/spaces/kadirnar/yolov8/blob/main/app.py
I just want to do it using ultralytics functions.
