### ISSUE TITLE
yolov8 classify model .pt convert to .onnx, result not right

### ISSUE THREAD

**Issue by HonestyBrave** [ultralytics/ultralytics#2134]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

hi, @glenn-jocher, @Laughing-q
    i have training yolov8-cls.pt in my custom data, when i use .pt model to test, the result look is normal:
 NG total 67 images, predict 60 NG, 7 OK
 OK total 19 images, predict 16 OK, 3 NG

when i use the command:
 yolo export model=/home/weights/round.pt format=onnx, imgsz=224,224 opset=12
to convert onnx
**when i test the same image, the result is always NG**,  like:

 NG total 67 images, predict 67 NG,
 OK total 19 images, predict 19 NG

could you give me some suggest? i have find same question, but not any answer in the: https://github.com/ultralytics/ultralytics/issues/1163

### Environment

github branch is : 8.0.81

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by HonestyBrave** [comment]
.pt model test look like normal

![image](https://user-images.githubusercontent.com/16200506/233241876-b0e8ecca-a8b1-4fb0-9fee-9fa55e9ab194.png)

.onnx model test look like abnormal

![image](https://user-images.githubusercontent.com/16200506/233241943-f1b1ce6b-f874-4bd5-a114-f59e3a084ff6.png)

**Comment by Laughing-q** [comment]
@HonestyBrave hey, could you test the following commands to see if the results are consistent?
```python
from ultralytics import YOLO
model = YOLO("yolov8n-cls.pt")
model.predict(imgsz=224)
model.export(format="onnx")
model = YOLO("yolov8n-cls.onnx")
model.predict(imgsz=224)
```

**Comment by HonestyBrave** [comment]
> @HonestyBrave hey, could you test the following commands to see if the results are consistent?
> 
> ```python
> from ultralytics import YOLO
> model = YOLO("yolov8n-cls.pt")
> model.predict(imgsz=224)
> model.export(format="onnx")
> model = YOLO("yolov8n-cls.onnx")
> model.predict(imgsz=224)
> ```

yes, i test the method, but get the same result, see more detail in the result.txt
![image](https://user-images.githubusercontent.com/16200506/233355556-767d5dd9-971c-4621-9f21-18d6093e4adc.png)

[result.txt](https://github.com/ultralytics/ultralytics/files/11285752/result.txt)

**Comment by Laughing-q** [comment]
@HonestyBrave oh I mean just test with official model. I want to know if this issue is related to custom trained model or probably there's a bug in your case.
could you test with exactly the same script to see the result?
```python
from ultralytics import YOLO
model = YOLO("yolov8n-cls.pt")
model.predict(imgsz=224)
model.export(format="onnx")
model = YOLO("yolov8n-cls.onnx")
model.predict(imgsz=224)
```

**Comment by HonestyBrave** [comment]
@Laughing-q ok, I test official model, is correct. i find is my reason, I trained long image but test round image, so, the result not right. but i curious about is test same image, .pt and .onnx is result not same. but not matter, if next occur, i ask again.

today afternoon, i retry training again with long image and test long image of .pt and .onnx, the result is same and right.

thank you for your patience in answer my question.

**Comment by glenn-jocher** [comment]
@HonestyBrave, glad to hear that your issue has been resolved. Generally, it is important to ensure that the test images are similar to the images that the model was trained on in order to obtain accurate and consistent results. It is also common for the results of the .pt and .onnx models to be different due to differences in the implementation under the hood. In general, it is recommended that you keep the input shapes consistent between the tests with different models to obtain consistent results. If you have any other questions in the future, feel free to ask. Thank you for your patience!

**Comment by HonestyBrave** [comment]
yeah, very thank you for yours!


| |
沈建华
|
|
***@***.***
|
---- Replied Message ----
| From | Glenn ***@***.***> |
| Date | 4/22/2023 01:26 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [ultralytics/ultralytics] yolov8 classify model .pt convert to .onnx, result not right (Issue #2134) |

@HonestyBrave, glad to hear that your issue has been resolved. Generally, it is important to ensure that the test images are similar to the images that the model was trained on in order to obtain accurate and consistent results. It is also common for the results of the .pt and .onnx models to be different due to differences in the implementation under the hood. In general, it is recommended that you keep the input shapes consistent between the tests with different models to obtain consistent results. If you have any other questions in the future, feel free to ask. Thank you for your patience!

**Comment by Captain1986** [comment]
> @Laughing-q ok, I test official model, is correct. i find is my reason, I trained long image but test round image, so, the result not right. but i curious about is test same image, .pt and .onnx is result not same. but not matter, if next occur, i ask again.
> 
> today afternoon, i retry training again with long image and test long image of .pt and .onnx, the result is same and right.
> 
> thank you for your patience in answer my question.

Hi, HonestyBrave:
