### ISSUE TITLE
on windows + anaconda

### ISSUE THREAD

**Issue by carlosjulioph** [ultralytics/ultralytics#214]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i have followed install quick start, but on window i got this error:
  hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

**Comment by JosecarlosRamirezB** [comment]
Hi I'm also have the same problem

**Comment by sijie-Xu** [comment]
嘿，兄弟，不需要进行这样操作，

有两种可能一种是环境变量的问题，你可以打开你的subprocess.py文件

位置在你的python环境中，比如 C:\User\...\Python\Python39\lib\subprocess.py

找到报错的位置，去打印args变量,查看哪些环境变量出了问题
`print(args)
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,`

另一种方式是，找到subprocess.py中的class Popen
然后将shell=False 改为 shell=True

如图所示：
![image](https://user-images.githubusercontent.com/122505422/211971729-2c5eb174-cc63-4520-851a-32408e12ae76.png)

**Comment by pderrenger** [comment]
@sijie-Xu 嘿，感谢你的建议！

我建议你先尝试查看环境变量是否设置正确，然后看看是否有包含问题的地方。将`print(args)`添加到相应的位置，会有助于找到具体出错的地方。

如果这个方法不起作用，你可以尝试将`shell=False`改为`shell=True`，这可能会解决问题。

希望有所帮助！
