### ISSUE TITLE
Yolov8-pose onnxruntime c++ example

### ISSUE THREAD

**Issue by duymanh-111** [ultralytics/ultralytics#2145]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello
Thanks for your great excellent job.
I am going to  develop engine to detect four corners of license plate car with yolov8-pose by c++.
But I don't know to inference with yolov8-pose in onnxruntime c++ lib.
I would appreciate that somebody upload yolov8-pose onnxruntime inference moudle.
Again thanks for yolov8 developers.
Best regards.

**Comment by glenn-jocher** [comment]
Hello @duymanh-111, glad to hear that you are interested in using YOLOv8 for license plate corner detection! We do not provide any official onnxruntime inference modules for YOLOv8. You can export an ONNX model from YOLOv8 and use it for inference in a separate application running the onnxruntime C++ library. You can find an overview of how to export an ONNX model in this [YOLOv8 tutorial](https://github.com/ultralytics/yolov5/issues/1918#issuecomment-789718468). For onnxruntime C++ usage examples, please refer to the [official onnxruntime documentation](https://www.onnxruntime.ai/docs/cxxapi.html). Good luck with your project!

**Comment by triple-Mu** [comment]
Here is a tensorrt demo https://github.com/triple-Mu/YOLOv8-TensorRT/tree/main/csrc/pose/normal

**Comment by glenn-jocher** [comment]
@triple-Mu thank you for sharing the TensorRT demo for YOLOv8 pose detection! It's great to see the YOLOv8 community contributing to the development and application of YOLOv8. We appreciate your involvement and invite you to continue participating in the community. If there's anything else we can help you with, please don't hesitate to ask.
