### ISSUE TITLE
Is multi-label detection supported in this version of YOLO?

### ISSUE THREAD

**Issue by WadRex** [ultralytics/ultralytics#2147]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I have a question about multi-label detection in YOLOv8. I want to know if it is supported and if yes, how can I use it. The closest issue I found was related to classification, not detection. As far as I understood, multi-label detection is supported in the original YOLO and also in YOLOv5, but I am not sure about the support in YOLOv8. Can anyone please help me with this? Thank you in advance!

**Comment by pderrenger** [comment]
@WadRex hello! Yes, YOLOv8 supports multi-label detection. You can achieve this by annotating your dataset with multiple labels for each object and then training the model using the standard YOLOv8 training process. During inference, the model will be able to detect and label multiple objects within the same image. This functionality allows for flexible and comprehensive object detection capabilities. If you need further assistance, feel free to ask. Good luck with your project!
