### ISSUE TITLE
Extracting masks and confidence values from Onnx output

### ISSUE THREAD

**Issue by Tyler-Dickinson** [ultralytics/ultralytics#2149]
### Search before asking
I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained a yolov8m-seg.pt (segmentation) model on a custom dataset with 2 classes and converted to ONNX.  
The ONNX model has two outputs: 

- output0 : **float32[batch,anchors,Concatoutput0_dim_2]** 
- output1 : **float32[batch,32,mask_height,mask_width]**

I would like to extract mask and confidence values, but I have not been able to determine how.  I am feeding the model an image **float32[1,3,640,640]** and it returns output1 as **float32[1,32,160,160]**. The mask output shape and values don't resemble **torch.Size([1, 640, 640])** from the original torch model's mask.  The pytorch model works correctly, I'm just wanting to get the faster inference speeds to accomodate higher framerates.  Any information or code examples on how to extract this data would be appreciated.

**Comment by glenn-jocher** [comment]
@Tyler-Dickinson it sounds like the ONNX output may have undergone some resizing during the conversion process, resulting in a different mask shape and values in the ONNX output compared to the original PyTorch model's mask. To extract the mask and confidence values, you can use the following code example:

```python
import onnxruntime
import numpy as np

# load the ONNX model
sess = onnxruntime.InferenceSession("model.onnx")

# Run prediction on input data and get the output tensor(s)
input_data = np.random.random_sample((1, 3, 640, 640)).astype(np.float32)
output = sess.run(None, {'input': input_data})

# Extract the mask and confidence values
mask = output[1]
confidence = np.squeeze(output[0], axis=(0, 1)).flatten()
```

In the code above, we first load the ONNX model using the `onnxruntime.InferenceSession()` function. We then pass the input image data to the model and obtain the output tensors using `sess.run()`. Finally, we extract the mask and confidence values from the outputs. The `np.squeeze()` function is used to remove any single-dimensional entries in the shape of an array, and the `flatten()` function is used to convert the multi-dimensional confidence tensor into a 1D array. 

Note that you should replace the `'model.onnx'` string in `InferenceSession()` with the actual path to your ONNX model file.

**Comment by Tyler-Dickinson** [comment]
I tried the above code with my model and got the following: 
**ValueError: cannot select an axis to squeeze out which has size not equal to one**. 
I noticed the input name of my onnx model is 'images' not 'input'.  
This is the code I used :

```
import numpy as np
import onnxruntime as rt

sess_options = rt.SessionOptions()
cache_path = r'E:\onnx_cache'

providers = [
    ('TensorrtExecutionProvider', {
        'device_id': 0,
        'trt_max_workspace_size': 2147483648,
        'trt_fp16_enable': True,
        'trt_engine_cache_enable':True,
        'trt_engine_cache_path':cache_path,
    }),
    ('CUDAExecutionProvider', {
        'device_id': 0,
        'arena_extend_strategy': 'kNextPowerOfTwo',
        'gpu_mem_limit': 2 * 1024 * 1024 * 1024,
        'cudnn_conv_algo_search': 'EXHAUSTIVE',
        'do_copy_in_default_stream': True,
    })
    ]
model_path =r'E:\best.onnx'
sess = rt.InferenceSession(model_path,sess_options=sess_options,providers=providers)

input_data = np.random.random_sample((1, 3, 640, 640)).astype(np.float32)
output = sess.run(None, {'images': input_data})

mask = output[1]
confidence = np.squeeze(output[0], axis=(0, 1)).flatten()
```
Before it hits the error, it does copy to the mask variable with shape **(1, 32, 160, 160)** and vals(-0.27856445 to 2.59375):
```
array([[[[-1.24328613e-01,  1.41357422e-01,  2.00805664e-01, ...,
          -3.46755981e-03,  3.81469727e-02,  5.78002930e-02],
         [-8.44116211e-02,  3.79150391e-01,  5.56640625e-01, ...,
           2.46337891e-01,  3.21777344e-01,  2.19360352e-01],
         [-7.64770508e-02,  3.70849609e-01,  5.99609375e-01, ...,
           2.23266602e-01,  3.22753906e-01,  2.74658203e-01],
         ...,
         [-1.56005859e-01,  2.86132812e-01,  3.84033203e-01, ...,
```
compared to mask tensor from pytorch with shape **torch.Size([1, 640, 640])** and vals (0 to 1 ):

```
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0')
```

**Comment by glenn-jocher** [comment]
@Tyler-Dickinson, it seems that the `np.squeeze()` call used in the original code example may not work in your particular use case because the confidence dimension has size `32` and not `1`, as we had originally assumed. In this case, you may want to use `np.reshape()` instead of `np.squeeze()` to convert the confidence tensor into a 1D array. That being said, before using `np.reshape()` or any other reshaping function, make sure that the structure of your outputs conforms to the expected format. 

Regarding the mask values, the different ranges of the values in your PyTorch and ONNX outputs suggest that there may be some scaling or normalization that was performed on the mask values during model training or inference. We recommend investigating the training and inference procedures used to generate the model, as well as any post-processing steps applied to the output. 

As a next step, you may also want to visualize the mask output values from the PyTorch and ONNX models to better understand the differences between them. This should help give you a better idea about what might be causing the discrepancy in values between the two outputs.

**Comment by DoDucNhan** [comment]
I also got the output shape [1,32,160,150] when inferencing with onnx. I am still seeking a way to convert it to the [1,640,640] shape. Do you have any solutions for this? A code example would be a great help as well.

**Comment by Laughing-q** [comment]
@DoDucNhan hi, you can refer to our `process_mask_upsample` function:
[https://github.com/ultralytics/ultralytics/blob/d1107ca4cb5ef2a94a583e0a0247172f7f972f9a/ultralytics/yolo/utils/ops.py#L557-L575](https://github.com/ultralytics/ultralytics/blob/d1107ca4cb5ef2a94a583e0a0247172f7f972f9a/ultralytics/yolo/utils/ops.py#L557-L575)
which takes `32,160,160` and `n,32` as input and generate final `n,640,640` outputs.

**Comment by davidvct** [comment]
> @DoDucNhan hi, you can refer to our `process_mask_upsample` function:
> 
> https://github.com/ultralytics/ultralytics/blob/d1107ca4cb5ef2a94a583e0a0247172f7f972f9a/ultralytics/yolo/utils/ops.py#L557-L575
> 
> which takes `32,160,160` and `n,32` as input and generate final `n,640,640` outputs.

Hi, how do I find n? 

I am using cv2 dnn to load the onnx model:
`result = model.forward()`
the shape of the `result` is:
`1, 32, 160, 160`

**Comment by glenn-jocher** [comment]
Hi @davidvct, 

The variable `n` in the `process_mask_upsample` function refers to the number of instances to be segmented in an image. It is inferred from the model itself, which indicates how many instances have been detected. 

In your case, when using cv2.dnn, the output shape `1, 32, 160, 160` is describing a 4D tensor. The second dimension, which is `32` in your case, could possibly be the number of instances that the model detected. Hence this can be your `n`.

I hope this helps!

**Comment by glenn-jocher** [comment]
Hi @davidvct,

Your observation is quite correct. The output differences between cv2.dnn and onnxruntime could be due to how they handle and interpret the model's architecture.

As you've found, onnxruntime provides both the `output0` and `output1` outputs, giving you comprehensive details about the segmented instances and other information like bounding box coordinates or class predictions.

Yes, switching to onnxruntime is a good move if it gives you all the information you need. It's a versatile and efficient tool for inference with ONNX models.

If you have any other questions or concerns, feel free to ask. We're here to help!

**Comment by KhadimHussain55** [comment]
Hello @davidvct  could you  explain how you were able to make it work with onnxruntime. I am trying to get masks, bboxes, confidences and class ids from model output however output looks strange to me. in my case I also have `output0 ` and `output1` . Possibly I am missing something in post processing.  `output1 = (1, 32, 320, 320)`   `output0 = (1, 41, 33600)`

**Comment by glenn-jocher** [comment]
Hi @KhadimHussain55,

Without including a code or links, the general process involves the following steps:

1. Load the ONNX model with onnxruntime. The model should be provided as an input to `onnxruntime.InferenceSession()`.
2. Use the `run` function to generate model outputs. The output should be a list of numpy arrays.
3. The two outputs `output0` and `output1` can be referenced by their indices in the output list.
4. `output0` typically contains information about the bounding boxes, confidences, and class ids. The size `33600` is likely `105x320`, where `105` is the number of anchors and `320` is the number of grid cells. You will need to reshape this output into a shape that matches `(batch size, number of anchors, grid cells, properties per anchor)`. The properties per anchor typically consist of 5 properties for the bounding box (x,y,width,height, confidence) and additional properties for the class probabilities.
5. The bounding boxes will need to be scaled according to the input image size and the confidences should be passed through a sigmoid function to restrict their values between 0 and 1.
6. `output1` usually contains the instance masks. The size `32` is likely the number of instances detected. This output is of the shape `(batch size, number of instances, height of grid cells, width of grid cells)`.
7. The instance masks will likely need to be resized to match the original image size. This can be done with any image resizing function, ensuring that the masks are resized using a method suitable for binary masks, such as nearest-neighbor interpolation.

I hope this guidance helps. Happy coding!

**Comment by davidvct** [comment]
> Hello @davidvct could you explain how you were able to make it work with onnxruntime. I am trying to get masks, bboxes, confidences and class ids from model output however output looks strange to me. in my case I also have `output0 ` and `output1` . Possibly I am missing something in post processing. `output1 = (1, 32, 320, 320)` `output0 = (1, 41, 33600)`

@KhadimHussain55 Maybe you can try this:

```
from yoloseg import YOLOSeg

yoloseg = YOLOSeg("model.onnx", conf_thres=0.5, iou_thres=0.5)

img = cv2.imread("./test.jpg")

# Detect Objects
boxes, scores, class_ids, masks = yoloseg(img)
```

**Comment by KhadimHussain55** [comment]
thank you guys. shared info and resources are very useful. I appreciate it.

**Comment by glenn-jocher** [comment]
@davidvct you're very welcome! I'm glad to hear that you found the information and resources we provided useful for your project. If you have any further questions or if there's anything else you need assistance with in regards to YOLOv8, please feel free to ask. We're here to help. Happy coding!

**Comment by rosemolthomas30** [comment]
> thank you guys. shared info and resources are very useful. I appreciate it.

Hi how you predict masks using output0 and output1. If you have any code could you share it to me

**Comment by khadimhussain0** [comment]
hello @rosemolthomas30 for my usecase bboxes were enough so I did not bother to get masks. However here is an approach which contains code for masks support although when I tested it it had some bugs. feel free to check if it works for your use case https://github.com/ibaiGorordo/ONNX-YOLOv8-Instance-Segmentation/blob/main/yoloseg/YOLOSeg.py
