### ISSUE TITLE
SOTA

### ISSUE THREAD

**Issue by bakeryproducts** [ultralytics/ultralytics#215]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

> “Ultralytics YOLOv8 is the highest performing YOLO model ever released, setting new standards in SOTA real-time detection and segmentation, ...

> [Ultralytics YOLOv8](https://github.com/ultralytics/ultralytics), developed by [Ultralytics](https://ultralytics.com/), is a cutting-edge, state-of-the-art (SOTA) model ...

> Ultralytics YOLOv8: The State-of-the-Art YOLO Model

SOTA results have been announced multiple times in the repository and on the website. What are these SOTA results you managed to beat and is there a comparison with current SOTA?

**Comment by HarishGuragol** [comment]
@bakeryproducts  you can go through this medium blog for understanding of the SOTA comparison and results

**Comment by AyushExel** [comment]
@bakeryproducts @HarishGuragol we'll release comparison plots soon with exact commands to reproduce. There are multiple tasks so it takes comparatively more time. Please be patient.

**Comment by glenn-jocher** [comment]
@bakeryproducts SOTA comparisons added in #260

**Comment by bakeryproducts** [comment]
No way professionals like Ultralytics claiming 'new standards in SOTA real-time detection and segmentation' without proper comparison on different resolutions, datasets, batch-sizes, GPU-archs.

Surely Ultralytics got better SOTA comparisons then two .png files of accuracy plots vs other YOLO models.
Here some reference that you brought up by yourself in plots from #230 : https://arxiv.org/pdf/2207.02696.pdf 

> YOLOv7 <...> has the highest accuracy 56.8% AP among all known real-time object detectors with 30 FPS or higher on GPU V100

Whats YOLOv8 highest AP on COCO val with 30 FPS or higher (on A100 GPU as you did in #230)?

**Comment by AyushExel** [comment]
@bakeryproducts yes, that's the standard to compare mAP vs speed on coco test set. Every repository does that and thats the main plot. We've provided size comparison too. And more plots are coming in the future. And all these plots will be available in the paper too. FPS too can be calculated using the latency. We need to prioritize bug reports too.

Regarding 56.8 map, those are p6 models. That's a different family of models. Base models (trainer at 640 pixel) and larger p6 models( trained at 1280 pixels). 53.9 is the highest-ever map achieved by the base model still being faster and smaller than the next model in the line.
We cannot compare the different classes of models with very different sizes. v6 had 5 base models and v7 has 2. Both are included in our charts. Our p6 models will be available soon if you're interested in that. We will keep following the release on a rolling basis. hope I answered your questions. If not, please check back in a few days.

**Comment by Laughing-q** [comment]
@bakeryproducts hi actually the highest model we got is 56.9 with resolution 1280. But we noticed that the settings we used for the model is suboptimal after the training finished, so the 56.9 is suboptimal. We think it's not ready to release if it's suboptimal. And we don't have enough time to train another before release the code. Thanks for the attention. :) We'll release the highest model soon.

**Comment by wesboyt** [comment]
has there been a followup here @bakeryproducts ?

**Comment by bakeryproducts** [comment]
Hey @wesboyt, no, but when the Ultralytics team says "soon," it could take years. No need to worry though! It's been only a year since SOTA claims, and we've been waiting for YOLO papers from them for about three years i think. fingers crossed!
