### ISSUE TITLE
save_period not working in yolov8 during model training

### ISSUE THREAD

**Issue by AzwadFawadHasan** [ultralytics/ultralytics#2150]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

![image](https://user-images.githubusercontent.com/106096161/233416383-189f211a-ceaa-402c-9271-f2a7b8d95f4c.png)

### Environment

using yolov8 using CLI along with rtx 3050ti notebook gpu (windows 10)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi @AzwadFawadHasan, thank you for reaching out to us. The error message that you're seeing suggests that you may have an issue with your environment or dependencies that were installed for YOLOv8 CLI to function properly. We would recommend double-checking the requirements listed in our [GitHub repository](https://github.com/ultralytics/ultralytics/blob/main/requirements.txt) are properly installed in your environment. Also, please let us know if you have changed settings or network architectures from the default YOLOv8 setup.

Regarding your willingness to contribute, contributions to Ultralytics YOLOv8 are always welcome! Please feel free to open a pull request with any proposed changes or bug fixes. If you're not sure where to start, we suggest identifying any issues you may have encountered and submitting proposed changes to fix them. Thanks!

**Comment by AzwadFawadHasan** [comment]
Yes, re-installing ultralytics using pip fixed it.

**Comment by glenn-jocher** [comment]
@AzwadFawadHasan glad to hear that you were able to fix the issue by re-installing Ultralytics using `pip`! Sometimes issues with the environment, dependencies or installation can cause unexpected behavior, and it's always a good idea to double check that everything is installed and updated correctly, especially when encountering errors or bugs. If you encounter any other issues, don't hesitate to reach out to us again or open an issue on our GitHub repository.
