### ISSUE TITLE
Save YOLO.val() results into a custom path?

### ISSUE THREAD

**Issue by 01bui** [ultralytics/ultralytics#2151]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

How do I save YOLO.val() results into a custom path? There is no argument such as "save_dir".

Thanks for looking into this!

**Comment by wojtek11530** [comment]
Currently one workaround is to pass `project` and `name` arguments from which inside of `BaseValidator` class `savedir` is constructed: 
https://github.com/ultralytics/ultralytics/blob/243fc4b1fe214ff6c27759dad51c37809db8f7f8/ultralytics/yolo/engine/validator.py#L80

Example:
```
metrics = model.val(
    data=dataset_config,
    split="test",
    project=save_dir,
    name=name
)
```
and results will be saved under `save_dir/name`.

**Comment by glenn-jocher** [comment]
@wojtek11530 hi,

To save YOLO.val() results into a custom path, you can use the `project` and `name` arguments. The `savedir` is constructed by combining these two arguments in the `BaseValidator` class. For example, if you set `project` to be the directory you want to save the results in and `name` to be the name of the file, the results will be saved under `project/name`.

Here's an example:

```
metrics = model.val(
    data=dataset_config,
    split="test",
    project='custom/path',
    name='results'
)
```

This will save the results in the directory `custom/path` under the file name `results`. Let me know if you have any further questions!
