### ISSUE TITLE
Running YOLOv8 CLI/Running YOLOv8 in general

### ISSUE THREAD

**Issue by frankvp11** [ultralytics/ultralytics#2156]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

![image](https://user-images.githubusercontent.com/90110502/233484769-a161edef-2e3a-4a6a-84fa-4b9c8734e569.png)
![image](https://user-images.githubusercontent.com/90110502/233484920-e367c2b6-a79b-435d-959d-55804ef15261.png)

(there is some overlap in the photos but nonetheless). Basically, it (claims to) install ultralytics properly, however then when I run it (or atleast try to) it doesn't work. I've shown both attemps at running Yolo and both fail. 

### Environment

-YOLO (from git clone)
-Ubuntu 16.04
-Python 3.8 (from source)
- Jetson TX1 (relatively old flash aswell if relevant)

### Minimal Reproducible Example

Can be seen in images

### Additional

It could just be that it's an old flash, however It's not my device so I don't have many option as far as reflashing goes. As for the errors, I've looked into the dockerfiles aswell, however I don't have the storage space for those. These are the two only ways (as far as i know) to run Yolo, feel free to comment more if there are, or to give me advice on fixing the error

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi @frankvp11, thank you for your question! From the error messages, it seems there might be some compatibility issues between your Jetson TX1 device and the installed software. Since Jetson TX1 is an older device, it might be worth checking if `ultralytics` is compatible with it at all. You can also try running YOLOv8 on a newer device or even using one of the [provided cloud-based environments](https://github.com/ultralytics/yolov5#environments) to see if the error persists. Finally, we recommend double-checking that you have installed `ultralytics` properly and that all dependencies are met. You can refer to the [installation instructions](https://github.com/ultralytics/yolov5#install) and see if there are any missing steps on your end. I hope this helps!

**Comment by frankvp11** [comment]
Hi Glenn,
With your response, I have a couple questions. How might I be able to check/find out if ultralytics is compatible with the TX1? Also, I don't have a newer device that I can use to test it. As for cloud-based environments, I've run many version of YOLO before on colab, however that's hard to integrate into actual environments. As for the installation instructions, I will be sure to check that. One last thing though, if all else fails, could you potentially suggest me some other potential computer vision options that run at roughly the same fps as YOLO? I chose yolo due to it's speed, but fear running something like detectron2 (which i am well versed in) because of it's size. 
Thanks and greetings,
Frank

**Comment by glenn-jocher** [comment]
Hi @frankvp11, thank you for your follow-up questions. To check compatibility between `ultralytics` and your Jetson TX1 device, you can try installing `ultralytics` on a similar device and see if you encounter the same issues. Alternatively, you can reach out to the Jetson TX1 community and inquire about its compatibility with the latest versions of `PyTorch` and `CUDA`, which are the main dependencies required by `ultralytics`.

As for other computer vision options that run at roughly the same fps as YOLO, you might want to consider OpenCV's DNN module or MobileNet, which are both optimized for speed and commonly used for object detection tasks. However, depending on your specific requirements and use case, there might be other options available that could better suit your needs.

**Comment by frankvp11** [comment]
Ok thanks for the advice. I will be sure to try all these things.

**Comment by glenn-jocher** [comment]
You're welcome @frankvp11. I'm glad I could offer some advice. Feel free to let us know if you run into any other issues or have any questions. We're always happy to help. Remember to check the documentation and installation instructions on the project page to ensure that your environment is set up correctly. Lastly, you might want to consider other options like OpenCV's DNN module or MobileNet for object detection, as these are also optimized for speed and commonly used in computer vision tasks. Good luck with your project!
