### ISSUE TITLE
Is "classes" option doesn't support in keypoint detection??

### ISSUE THREAD

**Issue by yellowjs0304** [ultralytics/ultralytics#2158]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi
As i told you [before ](https://github.com/ultralytics/ultralytics/issues/1236)there's 5 classes in my dataset. And i want to train the part of classes(only 0, 1).

I used the "classes" option, before in segment task. 
But there's an error in pose task training. I wondered why this makes an error.

![image](https://user-images.githubusercontent.com/30281608/233522497-21e0bbc4-f922-481c-a7a7-edcb7fa347dd.png)

And here's my command.
```
yolo task=pose mode=train model=yolov8x-pose-p6.pt data=custom_data.yaml imsz=1280 batch=8 epochs=1000 image_weights=True workers=2 device=\'1,2\' classes=[0,1]
```

**Comment by Laughing-q** [comment]
@yellowjs0304 Thanks for the reporting! I'm able to reproduce the issue, I'll fix it later. :)
