### ISSUE TITLE
为什么我服务器运行yolov8后，会卡两分钟才开始训练或者测试？很奇怪

### ISSUE THREAD

**Issue by xiamangfu** [ultralytics/ultralytics#2159]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Validation

### Bug

为什么我服务器运行yolov8后，会卡两分钟才开始训练或者测试？很奇怪。windows就正常

### Environment

ltralytics YOLOv8.0.77 🚀 Python-3.9.16 torch-1.13.1 CUDA:0 (NVIDIA GeForce RTX 3090, 24260MiB)

### Additional

为什么我服务器运行yolov8后，会卡两分钟才开始训练或者测试？很奇怪

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@xiamangfu 你可以提供一个复现的命令吗

**Comment by xiamangfu** [comment]
> 
这个是训练脚本
from ultralytics import YOLO

if __name__ == '__main__':
    model=YOLO('/home/xr/xmf/ultralytics-main/ultralytics/yolo/v8/pose/yolov8s-pose.pt')
    model.train(data='carplate-pose.yaml')
下面是验证脚本
from ultralytics import YOLO


if __name__ == '__main__':
    model = YOLO(r'/home/xr/xmf/ultralytics-main/carplate/ccpd_base3/weights/best.pt')#这里写入要测试的模型文件
    metrics=model.val()#不需要参数，数据集和测试已经被记忆
    print(metrics.box.map70)

**Comment by Laughing-q** [comment]
@xiamangfu 我测试了一下，我们这边无法复现这个卡顿问题，或许和你的服务器配置或者环境有关

**Comment by leonwujy** [comment]
可能是网络连接问题，导致check_pip_update_available()函数卡住

**Comment by jayphone17** [comment]
Same problem! Have you solved it ?
I use
`python main.py`
for training, as follows:
```
from ultralytics import YOLO
if __name__ == '__main__':
    model = YOLO('ultralytics/cfg/models/v8/yolov8n.yaml')
    model.load('yolov8n.pt')
    model.train(**{'cfg':'ultralytics/cfg/my.yaml', 'data':'dataset/rr/rr.yaml'})
```
and I stucked in this:
```
                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]           
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
YOLOv8 summary: 225 layers, 3011043 parameters, 3011027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Ultralytics YOLOv8.0.207 🚀 Python-3.8.18 torch-1.12.1+cu113 CUDA:0 (Tesla V100-SXM2-32GB, 32510MiB)
WARNING ⚠️ Upgrade to torch>=2.0.0 for deterministic training.
engine/trainer: task=detect, mode=train, model=None, data=dataset/rr/rr.yaml, epochs=300, patience=50, batch=128, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=ultralytics/cfg/my.yaml, tracker=botsort.yaml, save_dir=runs/detect/train
```
withour further ongoing.....just stucked....

**Comment by glenn-jocher** [comment]
@jayphone17 it appears that you are experiencing a delay before training begins and you suspect the `check_pip_update_available()` function might be causing a network-related blockage.

In situations where network access might block or delay certain startup operations, it's often advantageous to look into what is specifically causing the connection issue. This could be due to multiple reasons such as server configuration, firewall settings, or other network-related restrictions.

One temporary workaround to test if the `check_pip_update_available()` function is causing the delay is to manually disable any code that checks for updates or requires internet access during startup. Carefully comment out the relevant lines of code in your local copy of the repository and see if the delay persists. Remember, this is just for debugging purposes and should not be a permanent change.

In case disabling the update check resolves the delay issue, you may want to consider a more permanent solution that allows you to bypass the update check in environments with limited network access. If the problem is indeed confirmed to be caused by the update check, a feature request could be submitted to provide an option to disable network checks for environments with restricted access.

Please also feel free to share your findings or continue the conversation in the GitHub issues so that if it's a common problem, it can be addressed in future updates of the repository.

For your second issue regarding the training stucking without further progress, it might be related to a separate issue. Ensure that you are using the latest version of the repository, and all requirements are installed correctly. Additionally, make sure that your dataset paths and configurations are correct and accessible.

You can also run additional debugging or verbose logging if available to get further insight into where exactly the code is getting stuck. Sometimes, waiting for a longer period may also reveal if there's a very time-consuming process that's just taking longer than expected.

If none of the above helps and you are certain that the issue is not related to environment or configuration, you might want to consider creating a detailed bug report on the GitHub issues page. Include as much detail as possible, including stack traces, error messages, and your environment setup, so that contributors can help diagnose the problem you're facing.

**Comment by xmccl** [comment]
I also encountered such a problem, I was stuck in that place, and then the error that appeared after I ctrl+c was as follows:
^CTraceback (most recent call last):
  File "train.py", line 8, in <module>
    model.train(data='/home/coop/coop_data/8kbak/mingchao2/yolov8-main/dataset/mydata/mydata.yaml',
  File "/home/adlab2/ssd1/coop_data/8kbak/mingchao2/yolov8-main/ultralytics/engine/model.py", line 337, in train
    self.trainer = (trainer or self._smart_load('trainer'))(overrides=args, _callbacks=self.callbacks)
  File "/home/adlab2/ssd1/coop_data/8kbak/mingchao2/yolov8-main/ultralytics/engine/trainer.py", line 119, in __init__
    self.data = check_det_dataset(self.args.data)
  File "/home/adlab2/ssd1/coop_data/8kbak/mingchao2/yolov8-main/ultralytics/data/utils.py", line 326, in check_det_dataset
    check_font('Arial.ttf' if is_ascii(data['names']) else 'Arial.Unicode.ttf')  # download fonts
  File "/home/adlab2/ssd1/coop_data/8kbak/mingchao2/yolov8-main/ultralytics/utils/__init__.py", line 307, in decorated
    return f(*args, **kwargs)
  File "/home/adlab2/ssd1/coop_data/8kbak/mingchao2/yolov8-main/ultralytics/utils/checks.py", line 283, in check_font
    if downloads.is_url(url):
  File "/home/adlab2/ssd1/coop_data/8kbak/mingchao2/yolov8-main/ultralytics/utils/downloads.py", line 37, in is_url
    with request.urlopen(url) as response:
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/home/coop/anaconda3/envs/v8/lib/python3.8/socket.py", line 797, in create_connection
    sock.connect(sa)
KeyboardInterrupt

**Comment by soo-s** [comment]
我也遇到了相同的问题在服务器上训练的时候，很奇怪。在加载模型之前会卡一次，在加载模型之后也会卡顿一次

**Comment by glenn-jocher** [comment]
您提到的卡顿问题通常与服务器网络连接或资源检查有关。根据您提供的日志，卡顿可能发生在`check_font()`尝试下载字体文件时。建议：

1. 手动下载[Arial.ttf字体文件](https://github.com/ultralytics/assets/releases/download/v0.0.0/Arial.ttf)并放置到`~/.config/Ultralytics/`目录
2. 检查服务器网络连接是否允许访问GitHub资源
3. 确认CUDA和PyTorch版本匹配

若问题仍存在，请提供完整的DEBUG日志输出：`yolo cfg=settings.yaml`，我们会进一步分析具体卡顿环节。最新版本已优化部分网络检查逻辑，建议先尝试升级到YOLOv8最新版本。

**Comment by Udischarge** [comment]
ultralytics/ultralytics/utils/checks.py中的第316行，读取本地的Arial.tff字体文件即可

**Comment by glenn-jocher** [comment]
@Udischarge 谢谢您分享这个解决方案！这确实是一个有效的方法。对于遇到类似问题的用户，您可以修改 `ultralytics/utils/checks.py` 文件中的字体检查逻辑，让它直接读取本地的Arial.ttf文件而不是尝试下载。

除此之外，用户还可以考虑以下操作：

1. 如我之前建议的，预先下载所需字体文件并放置在合适目录中
2. 在网络受限环境中，考虑设置环境变量阻止更新检查：`export ULTRALYTICS_SKIP_CHECKS=1`
3. 确保服务器网络连接设置合理，特别是代理配置和GitHub资源访问

这个问题在最新版本中已有一些优化，所以升级到最新版本也可能有所帮助。如果您仍然遇到问题，欢迎提供更多细节，我们可以进一步分析。
