### ISSUE TITLE
How to get only keypoints

### ISSUE THREAD

**Issue by shox21512** [ultralytics/ultralytics#2165]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I take only keypoints without bounding box?

**Comment by Laughing-q** [comment]
@shox21512 
```python
from ultralytics import YOLO
model = YOLO(yolov8n-pose.pt")
model.predict(source=.., boxes=False)
```

**Comment by shox21512** [comment]
> @shox21512
> 
> ```python
> from ultralytics import YOLO
> model = YOLO(yolov8n-pose.pt")
> model.predict(source=.., boxes=False)
> ```

Thanks for the quick reply.
I need the x and y coordinates of the 17 joint points. In the labels folder, it stores 38 coordinates in a txt files. I think 4 of them for bounding box coordinates. How can I extract only 34 coordinate points?

**Comment by Laughing-q** [comment]
@shox21512 well probably you need to modify it by your own. 
modify this line:
[https://github.com/ultralytics/ultralytics/blob/6c082ebd6fdf771b9003421735ef5a0d588b6bc8/ultralytics/yolo/engine/results.py#L289](https://github.com/ultralytics/ultralytics/blob/6c082ebd6fdf771b9003421735ef5a0d588b6bc8/ultralytics/yolo/engine/results.py#L289)
to:
```python
line = (*kpt, )
```

**Comment by shox21512** [comment]
Thank you!

**Comment by glenn-jocher** [comment]
@shox21512 you're welcome! Please keep in mind that modifying code is not officially supported and any modifications made by the user are done at their own risk. Additionally, as always we recommend users to thoroughly test their changes to ensure they match their desired behavior. If you encounter any issues or bugs, feel free to report them on our [Issues](https://github.com/ultralytics/ultralytics/issues) page on GitHub.

**Comment by dvskabangira** [comment]
i would like to combine yolov8 with lstm for human action recognition, is there any way to do it... Thank you???

**Comment by glenn-jocher** [comment]
@dvskabangira absolutely, combining YOLOv8 with an LSTM for human action recognition sounds like an exciting project! 🚀 You can use YOLOv8 to extract features or keypoints from video frames, and then feed these into an LSTM to model temporal dependencies for action recognition.

Here's a very basic outline of how you might set it up:

1. Use YOLOv8 to detect humans and/or keypoints in each frame.
2. Collect these detections/keypoints over a sequence of frames.
3. Feed the sequence into an LSTM network to classify the action.

```python
# Pseudo-code outline
for frame in video_frames:
    detections = yolov8.predict(frame)
    features = extract_features(detections)
    sequence.append(features)

action = lstm_model.predict(sequence)
```

Remember to preprocess your data to match the LSTM input requirements and consider how to handle videos of varying lengths. Good luck, and feel free to reach out if you have more questions!
