### ISSUE TITLE
show_conf=False in plot

### ISSUE THREAD

**Issue by BoscoShin** [ultralytics/ultralytics#2166]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello!!

I checked the document to make sure that the conf score was not printed.

.predict(show_conf=False) <- This code does not output conf scores.

So I tried the show_confarg in predict method. And then I used the plot method for printing.

But it doesn't seem to work in the plot method.

How can I make it invisible? (I also checked the plot document.).

Is it possible only in the prediction method?

Thanks.
Wseop.

![2023-04-21 181515](https://user-images.githubusercontent.com/75238411/233597528-dd2c4f53-a0ee-436b-aa6b-8d52c2ed7a4c.png)

**Comment by BoscoShin** [comment]
oh thanks you.

it works!

**Comment by Laughing-q** [comment]
@BoscoShin Glad to help! Then I'd like to close the issue. :) Please feel free to reopen it whenever you have related issues. :)
