### ISSUE TITLE
Yolov8 segmentation having low FPS

### ISSUE THREAD

**Issue by s4ifbn** [ultralytics/ultralytics#2174]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Applying Yolov8 large segmentation model using MPS on a Macbook pro m1 2021 machine
I'm experiencing a low fps around 8 and 10
what can I do to improve that?

thanks...

**Comment by glenn-jocher** [comment]
@s4ifbn, thanks for reaching out. The Macbook pro m1 2021 is an ARM-based machine and YOLOv8 large segmentation model may not be optimized for this architecture. You could try enabling the CUDNN MIPs flag in NVIDIA GPU-based systems to increase model evaluation speed, but for ARM-based machines, there may not be a direct solution. However, you could try optimizing the environment in which the model runs, for example, closing unnecessary programs and clearing memory. You could also try choosing a lightweight version of YOLOv8 or another model that was explicitly optimized for your machine. Additionally, you should verify that your hardware acceleration is properly configured and all dependencies are up-to-date.
