### ISSUE TITLE
Onnx inference into mobile Android app

### ISSUE THREAD

**Issue by flexbeats** [ultralytics/ultralytics#2177]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi all,

First, many thanks for your work on Yolov8.

I ran a successful training based on volov8n-cls.pt using [this data set](https://www.kaggle.com/datasets/gpiosenka/100-bird-species).
I converted my .pt file to .onnx using yolo CLI onnx export.
I used [microsoft onnx runtime demo android application ](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/image_classification/android)to build an android app based on my custom classification model.

I change the code to call my model instead of mobilenetv2_fp32.onnx and changed the imagenet_classes.txt to my labels.txt.

When I do predictions through the app, I barely have a result greater than 0.30% for my top 1 prediction and predictions aren't really accurate, on this kind of image I get 85% BLUE TIT.

![image](https://user-images.githubusercontent.com/66123389/233671181-9ce1c14d-18bb-45ac-bbce-d7a30f79e64e.png)

The problem is that when I use default MobileNetv2*.onnx, I got good results.

I think there is something related to Yolo architecture but I don't know what, if somebody can help me please.

Many thanks,

FleX

**Comment by glenn-jocher** [comment]
@flexbeats hi Flex, thank you for using YOLOv8 and congrats on your successful training! Regarding your question, we would recommend checking the input shapes and scales for your custom classification model, as well as verifying your class labels and that they match the format of the imagenet_classes.txt file. If your model is working well with MobileNetV2 but not with YOLOv8, it might be related to differences in the input format, image preprocessing, and/or post-processing. Reviewing the documentation for the onnx export function from YOLOv8 might also be helpful in troubleshooting any differences in the custom model versus the MobileNetV2 model that could affect its accuracy. I hope this helps!

**Comment by flexbeats** [comment]
The pre-process function is the same when I compare it to a [GitHub repo that normally works](https://github.com/luizhss/Android-Image-Classifier-App/). The problem is that it isn't compilable because of strange "<<<<<HEAD" markers into the code. Am I the only one trying to build a classifier android app using Yolov8?

**Comment by rucayun** [comment]
@flexbeats Hi, were you able to successfully implement your yolov8.onnx model on android? I'm trying to do it too, but I couldn't get it to work.

**Comment by glenn-jocher** [comment]
@rucayun hi there! If implementing your yolov8.onnx model on Android is causing a few challenges, there are a few steps you could take to potentially solve the issue. 

First, make sure that your model is correctly converted to .onnx format. Errors during the conversion can lead to problems downstream.

Next, ensure that the input tensor formats and shapes match what your model is expecting. This often involves proper preprocessing of input data - in this case, your images may need resizing or normalization.

Additionally, verify that the output from your model is correctly interpreted. Android's ONNX runtime may require additional processing or mapping to correctly assign output values to your classes.

Remember that ONNX models may have different operational requirements than the original model, so you may need to adjust your app’s logic or resources to accommodate the difference. 

I hope this helps! Let me know if there's anything else you need.

**Comment by flexbeats** [comment]
@rucayun, no I didn't solve this issue. I think it is mainly linked to
pre-processing as I can't have a proper match (only few % of confidence)
even on training images. I tried to change RGB-RBG but it didn't work.

Le mar. 1 août 2023, 12:54, Glenn Jocher ***@***.***> a
écrit :

**Comment by mablue** [comment]
Try sherpa onnx from k2-fsa
https://github.com/k2-fsa/sherpa-onnx

**Comment by pderrenger** [comment]
Thank you for the suggestion! Using Sherpa ONNX from k2-fsa could indeed be a valuable approach for some use cases. If you encounter any specific issues or need further assistance with YOLOv8, feel free to ask.

**Comment by jelychow** [comment]
@flexbeats Hi, I've recently been working on yolov8 integration on Android apps and used the same git repository as you to test it I ran into the same problem as you, but luckily I solved it. The root cause of this problem is that the official example of yolo8 doesn't normalize the images as default, the easiest way to solve this problem is to add the parameter augment = True to the train method, I hope this helps!
