### ISSUE TITLE
Error while inferencing with DNN module using CLI and ONNX export

### ISSUE THREAD

**Issue by hdnh2006** [ultralytics/ultralytics#2178]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection, Other

### Bug

Hello,

I am running yolov8 segmentation with a model exported to onnx using dnn module from OpenCV.

This is how I exported the model:
```
yolo export model=yolov8x-seg.pt opset=12 format=onnx
```

And this is what I get when I run yolo using CLI:
```
yolo task=segment mode=predict model=yolov8x-seg.onnx dnn
```

Error
```
WARNING ⚠️ 'source' is missing. Using default 'source=/home/henry/.local/bin/.virtualenvs/yolov8/lib/python3.8/site-packages/ultralytics/assets'.
Ultralytics YOLOv8.0.84 🚀 Python-3.8.10 torch-1.12.0+cu113 CUDA:0 (NVIDIA GeForce GTX 1650, 3912MiB)
Loading yolov8x-seg.onnx for ONNX OpenCV DNN inference...
WARNING ⚠️ Metadata not found for 'model=yolov8x-seg.onnx'

Traceback (most recent call last):
  File "/home/henry/.local/bin/.virtualenvs/yolov8/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/henry/.local/bin/.virtualenvs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 391, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/henry/.local/bin/.virtualenvs/yolov8/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/henry/.local/bin/.virtualenvs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 252, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/henry/.local/bin/.virtualenvs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 162, in predict_cli
    for _ in gen:  # running CLI inference without accumulating any outputs (do not modify)
  File "/home/henry/.local/bin/.virtualenvs/yolov8/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "/home/henry/.local/bin/.virtualenvs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 225, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "/home/henry/.local/bin/.virtualenvs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/v8/segment/predict.py", line 14, in postprocess
    p = ops.non_max_suppression(preds[0],
  File "/home/henry/.local/bin/.virtualenvs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/utils/ops.py", line 201, in non_max_suppression
    output = [torch.zeros((0, 6 + nm), device=prediction.device)] * bs
RuntimeError: Trying to create tensor with negative dimension -837: [0, -837]
```

It happens just with segmentation models, since in detection models I can correctly run yolo using CLI:
```
 yolo task=detect mode=predict model=yolov8x.onnx dnn
WARNING ⚠️ 'source' is missing. Using default 'source=/home/henry/.local/bin/.virtualenvs/yolov8/lib/python3.8/site-packages/ultralytics/assets'.
Ultralytics YOLOv8.0.84 🚀 Python-3.8.10 torch-1.12.0+cu113 CUDA:0 (NVIDIA GeForce GTX 1650, 3912MiB)
Loading yolov8x.onnx for ONNX OpenCV DNN inference...
WARNING ⚠️ Metadata not found for 'model=yolov8x.onnx'

image 1/2 /home/henry/.local/bin/.virtualenvs/yolov8/lib/python3.8/site-packages/ultralytics/assets/bus.jpg: 640x640 4 class0s, 1 class5, 3223.8ms
image 2/2 /home/henry/.local/bin/.virtualenvs/yolov8/lib/python3.8/site-packages/ultralytics/assets/zidane.jpg: 640x640 2 class0s, 1 class27, 3171.7ms
Speed: 0.9ms preprocess, 3197.7ms inference, 10.1ms postprocess per image at shape (1, 3, 640, 640)
```

Same error happens with `torch==2.0.0`

is somebody getting the same error?

### Environment

Ultralytics YOLOv8.0.84 🚀 Python-3.8.10 torch-1.12.0+cu113 CUDA:0 (NVIDIA GeForce GTX 1650, 3912MiB)
Ubuntu
Python3.8

### Minimal Reproducible Example

``` 
yolo export model=yolov8x-seg.pt opset=12 format=onnx
yolo task=segment mode=predict model=yolov8x-seg.onnx dnn
``` 

### Additional

It seems other user had the same problem here:
https://github.com/ultralytics/ultralytics/issues/1680#issue-1644302036

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@hdnh2006 thank you for your question. Based on the error message and the similar issue you found, it seems like this error might be related to the dimensions of the tensor for segmentation models. One potential solution could be to check the input data to make sure they have appropriate dimensions before running the model. It might also be helpful to refer to the documentation for Ultralytics YOLOv8 at https://docs.ultralytics.com for more information and guidance on troubleshooting this issue. I hope this helps!

**Comment by glenn-jocher** [comment]
@FengJunJian hello,

Thank you for raising this issue. 

If the `yolov8n-seg.onnx` model is running correctly, but the `yolov8s-seg.onnx` model is not, it seems like the problem could be related specifically to the `yolov8s-seg.onnx` model. 

There are a few things you might want to inspect, especially the dimensions and datatypes of the inputs and outputs. The error might be caused because the `yolov8s-seg.onnx` model expects different dimensions or datatypes than your current setup.

Also, double-check that you've correctly followed all steps in the pipeline for preparing, training, and exporting the model.

If all else fails, you may need to further investigate the differences between the `yolov8n-seg.onnx` and `yolov8s-seg.onnx` models, including configuration details and any differences in training between the two models.

Without specific error messages or more detail on the problem, this is the best advice I can give at the moment. If you could provide more information, we might be able to give more specific guidance.

Thanks for your contribution to YOLOv8. Your feedback is valuable in improving the overall performance and user experience of the system.
