### ISSUE TITLE
'NoneType' object has no attribute 'shape'  train

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#2181]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

classify train
```
Ultralytics YOLOv8.0.84  Python-3.8.16 torch-1.10.1 CUDA:0 (NVIDIA GeForce RTX 3080 Ti Laptop GPU, 16384MiB)
yolo\engine\trainer: task=classify, mode=train, model=D:\YOLOv8\ultralytics\MX\Classification\yolov8s-cls.pt, data=E:/FL/, epochs=100, patience=50, batch=100, imgsz=224, save=True, save_period=-1, cache=False, device=None, workers=8, project=kuanshi, name=kuanshi_FL_0422, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=kuanshi\kuanshi_FL_04225
Overriding model.yaml nc=1000 with nc=24

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.Conv                  [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.C2f                   [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.C2f                   [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.Conv                  [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.C2f                   [512, 512, 1, True]
  9                  -1  1    688664  ultralytics.nn.modules.Classify              [512, 24]
YOLOv8s-cls summary: 99 layers, 5111480 parameters, 5111480 gradients, 12.6 GFLOPs
Transferred 156/158 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed
optimizer: SGD(lr=0.01) with parameter groups 26 weight(decay=0.0), 27 weight(decay=0.00078125), 27 bias
libpng warning: iCCP: known incorrect sRGB profile
Image sizes 224 train, 224 val
Using 8 dataloader workers
Logging results to FL\FL
Starting training for 100 epochs...

      Epoch    GPU_mem       loss  Instances       Size
      1/100       1.8G      4.983        100        224:  10%|▉         | 8/81 [00:02<00:15,  4.76it/s]libpng warning: iCCP: known incorrect sRGB profile
      1/100       1.8G      4.487        100        224:  53%|█████▎    | 43/81 [00:05<00:02, 13.13it/s]libpng warning: iCCP: known incorrect sRGB profile
      1/100       1.8G      3.913        100        224:  89%|████████▉ | 72/81 [00:07<00:00,  9.08it/s]
Traceback (most recent call last):
  File "KS_fl.py", line 21, in <module>
    results = model.train(data=  "E:/kuanshi_MB_0422_dir/FLOK_ZQ_OKOK/", imgsz=224 , epochs=100, batch = 100 , project="kuanshi",name="kuanshi_FL_0422")
  File "D:\YOLOv8\ultralytics\ultralytics\yolo\engine\model.py", line 370, in train
    self.trainer.train()
  File "D:\YOLOv8\ultralytics\ultralytics\yolo\engine\trainer.py", line 191, in train
    self._do_train(world_size)
  File "D:\YOLOv8\ultralytics\ultralytics\yolo\engine\trainer.py", line 304, in _do_train
    for i, batch in pbar:
  File "D:\anaconda3\envs\yolov8\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "D:\YOLOv8\ultralytics\ultralytics\yolo\data\build.py", line 39, in __iter__
    yield next(self.iterator)
  File "D:\anaconda3\envs\yolov8\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "D:\anaconda3\envs\yolov8\lib\site-packages\torch\utils\data\dataloader.py", line 1183, in _next_data
    return self._process_data(data)
  File "D:\anaconda3\envs\yolov8\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "D:\anaconda3\envs\yolov8\lib\site-packages\torch\_utils.py", line 434, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\anaconda3\envs\yolov8\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\anaconda3\envs\yolov8\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda3\envs\yolov8\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\YOLOv8\ultralytics\ultralytics\yolo\data\dataset.py", line 263, in __getitem__
    sample = self.torch_transforms(im)
  File "D:\anaconda3\envs\yolov8\lib\site-packages\torchvision\transforms\transforms.py", line 61, in __call__
    img = t(img)
  File "D:\YOLOv8\ultralytics\ultralytics\yolo\data\augment.py", line 803, in __call__
    imh, imw = im.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

```

### Environment

```
win11
python 3.8
------------------- --------------------
certifi             2022.12.7
charset-normalizer  3.1.0
colorama            0.4.6
contourpy           1.0.7
cycler              0.11.0
fonttools           4.39.3
idna                3.4
importlib-resources 5.12.0
kiwisolver          1.4.4
matplotlib          3.7.1
numpy               1.23.2
opencv-python       4.7.0.72
packaging           23.1
pandas              2.0.0
Pillow              9.2.0
pip                 23.0.1
psutil              5.9.5
pyparsing           3.0.9
python-dateutil     2.8.2
pytz                2023.3
PyYAML              6.0
requests            2.28.2
scipy               1.10.1
seaborn             0.12.2
sentry-sdk          1.20.0
setuptools          66.0.0
six                 1.16.0
thop                0.1.1.post2209072238
torch               1.10.1
torchaudio          0.10.1
torchvision         0.11.2
tqdm                4.65.0
typing_extensions   4.5.0
tzdata              2023.3
ultralytics         8.0.84
urllib3             1.26.15
wheel               0.38.4
zipp                3.15.0
```

### Minimal Reproducible Example

```python
    model = YOLO(r"D:\YOLOv8\ultralytics\MX\Classification\yolov8s-cls.pt")              # load a pretrained model (recommended for training)

    results = model.train(data=  "E:/FL/", imgsz=224 , epochs=100, batch = 100 )  
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@monkeycc it looks like the issue is in the `augment.py` file where the `__call__` method is trying to access the shape attribute of a `NoneType` object. This is causing an `AttributeError` to be raised. The traceback suggests that the error is occurring during data loading in the `dataset.py` file. One possible solution could be to check for `None` types before trying to access the shape attribute to avoid the error. Additionally, as a best practice, it is recommended to check the data being loaded for any inconsistencies or missing values before loading to ensure smooth execution of the script. It may also be helpful to refer to the documentation at https://docs.ultralytics.com for more information on data loading and augmentation techniques.

**Comment by almak75** [comment]
There was a similar problem during training. The training started, several batches passed, and then ended with an error. The problem turned out to be in a single dataset file with non-Latin characters in its name. I fixed it, and the error disappeared. Maybe my decision will help someone.

**Comment by glenn-jocher** [comment]
@almak75 thank you for sharing your experience and solution to the issue. It is possible that non-Latin characters in dataset file names can cause errors during training, as the system may not be able to read or parse the file correctly. Therefore, it is recommended to avoid using non-Latin characters in the dataset file names. Your solution may be helpful for others who face similar issues during training.

**Comment by guilherme-butzke** [comment]
Hi there. I have the same problem even using the coco8set dataset.
```

from ultralytics import YOLO

model = YOLO('yolov8m.pt') 
model.train(
    data='coco8-seg.yaml',
    epochs= 2 ,
    imgsz=640 ,
    batch=32 ,
    patience = 10,
    project='runs_coco8' ,
    name='train_augmentation' ,
    augment= True,
    hsv_h = 0.015,
    hsv_s = 0.7,
    hsv_v = 0.4,
    degrees = 90.0,
    translate = 0.1,
    scale = 0.5,
    shear = 30.0,
    perspective = 0.0001,
    flipud = 0.1,
    fliplr = 0.5,
    mosaic = 0.5,
    mixup = 0.5,
)

```

And I have the same error:

```

New https://pypi.org/project/ultralytics/8.0.121 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.120 🚀 Python-3.10.10 torch-2.0.0 CUDA:0 (Tesla T4, 15102MiB)
yolo/engine/trainer: task=detect, mode=train, model=yolov8m.pt, data=coco8-seg.yaml, epochs=2, patience=10, batch=32, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=runs_coco8, name=train_augmentation, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=True, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=90.0, translate=0.1, scale=0.5, shear=30.0, perspective=0.0001, flipud=0.1, fliplr=0.5, mosaic=0.5, mixup=0.5, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs_coco8/train_augmentation3

                   from  n    params  module                                       arguments                     
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]                 
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]                
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]             
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]               
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]           
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]              
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]           
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]              
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]           
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]                 
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]                 
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]                 
 22        [15, 18, 21]  1   3822016  ultralytics.nn.modules.head.Detect           [80, [192, 384, 576]]         
Model summary: 295 layers, 25902640 parameters, 25902624 gradients

Transferred 475/475 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning /home/ec2-user/datasets/coco8-seg/labels/train.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
val: Scanning /home/ec2-user/datasets/coco8-seg/labels/val.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
Plotting labels to runs_coco8/train_augmentation3/labels.jpg... 
optimizer: AdamW(lr=0.000119, momentum=0.9) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.0005), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs_coco8/train_augmentation3
Starting training for 2 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        1/2      2.17G      1.667      4.099       1.96         37        640: 100%|██████████| 1/1 [00:00<00:00,  7.20it/s]
/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:139: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/1 [00:00<?, ?it/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[4], line 4
      1 from ultralytics import YOLO
      3 model = YOLO('yolov8m.pt') 
----> 4 model.train(
      5     data='coco8-seg.yaml',
      6     epochs= 2 ,
      7     imgsz=640 ,
      8     batch=32 ,
      9     patience = 10,
     10     project='runs_coco8' ,
     11     name='train_augmentation' ,
     12     
     13     augment= True,
     14     hsv_h = 0.015,
     15     hsv_s = 0.7,
     16     hsv_v = 0.4,
     17     degrees = 90.0,
     18     translate = 0.1,
     19     scale = 0.5,
     20     shear = 30.0,
     21     perspective = 0.0001,
     22     flipud = 0.1,
     23     fliplr = 0.5,
     24     mosaic = 0.5,
     25     mixup = 0.5,
     26 )

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py:373, in YOLO.train(self, **kwargs)
    371     self.model = self.trainer.model
    372 self.trainer.hub_session = self.session  # attach optional HUB session
--> 373 self.trainer.train()
    374 # Update model and cfg after training
    375 if RANK in (-1, 0):

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py:192, in BaseTrainer.train(self)
    190         ddp_cleanup(self, str(file))
    191 else:
--> 192     self._do_train(world_size)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py:371, in BaseTrainer._do_train(self, world_size)
    368 final_epoch = (epoch + 1 == self.epochs) or self.stopper.possible_stop
    370 if self.args.val or final_epoch:
--> 371     self.metrics, self.fitness = self.validate()
    372 self.save_metrics(metrics={**self.label_loss_items(self.tloss), **self.metrics, **self.lr})
    373 self.stop = self.stopper(epoch + 1, self.fitness)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py:477, in BaseTrainer.validate(self)
    473 def validate(self):
    474     """
    475     Runs validation on test set using self.validator. The returned dict is expected to contain "fitness" key.
    476     """
--> 477     metrics = self.validator(self)
    478     fitness = metrics.pop('fitness', -self.loss.detach().cpu().numpy())  # use loss as fitness measure if not found
    479     if not self.best_fitness or self.best_fitness < fitness:

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ultralytics/yolo/engine/validator.py:165, in BaseValidator.__call__(self, trainer, model)
    163 with dt[2]:
    164     if self.training:
--> 165         self.loss += model.loss(batch, preds)[1]
    167 # Postprocess
    168 with dt[3]:

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ultralytics/nn/tasks.py:215, in BaseModel.loss(self, batch, preds)
    212     self.criterion = self.init_criterion()
    214 preds = self.forward(batch['img']) if preds is None else preds
--> 215 return self.criterion(preds, batch)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ultralytics/yolo/utils/loss.py:159, in v8DetectionLoss.__call__(self, preds, batch)
    157 loss = torch.zeros(3, device=self.device)  # box, cls, dfl
    158 feats = preds[1] if isinstance(preds, tuple) else preds
--> 159 pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
    160     (self.reg_max * 4, self.nc), 1)
    162 pred_scores = pred_scores.permute(0, 2, 1).contiguous()
    163 pred_distri = pred_distri.permute(0, 2, 1).contiguous()

TypeError: 'NoneType' object is not iterable
```

Any idea about the problem?

**Comment by keaneflynn** [comment]
Getting the same error although none of my images files have any non-latin characters. I'm sure there is a faulty image somewhere but they can't expect us to got through 100k images to find the one erroneous one? I was thinking adding a bad.list like available in PJ Reddies YOLOv4 would be good to identify the problematic images would be a great feature. I'd make a pull request but if I was good enough at coding to do that I probably wouldn't be coming here for help. Cheers

`
Starting training for 50 epochs...

      Epoch    GPU_mem       loss  Instances       Size
       1/50     0.709G     0.4237         16        416:   2%|▏         | 52/2144 [00:02<01:18, 26.77it/s]Premature end of JPEG file
       1/50     0.709G     0.3666         16        416:  30%|███       | 647/2144 [00:24<00:57, 26.16it/s]
Traceback (most recent call last):
  File "c:\users\windows\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\windows\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Windows\AppData\Local\Programs\Python\Python37\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "c:\users\windows\appdata\local\programs\python\python37\lib\site-packages\ultralytics\yolo\cfg\__init__.py", line 411, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "c:\users\windows\appdata\local\programs\python\python37\lib\site-packages\ultralytics\yolo\engine\model.py", line 373, in train
    self.trainer.train()
  File "c:\users\windows\appdata\local\programs\python\python37\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 192, in train
    self._do_train(world_size)
  File "c:\users\windows\appdata\local\programs\python\python37\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 315, in _do_train
    for i, batch in pbar:
  File "c:\users\windows\appdata\local\programs\python\python37\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "c:\users\windows\appdata\local\programs\python\python37\lib\site-packages\ultralytics\yolo\data\build.py", line 38, in __iter__
    yield next(self.iterator)
  File "c:\users\windows\appdata\local\programs\python\python37\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "c:\users\windows\appdata\local\programs\python\python37\lib\site-packages\torch\utils\data\dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "c:\users\windows\appdata\local\programs\python\python37\lib\site-packages\torch\utils\data\dataloader.py", line 1225, in _process_data
    data.reraise()
  File "c:\users\windows\appdata\local\programs\python\python37\lib\site-packages\torch\_utils.py", line 429, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 7.
Original Traceback (most recent call last):
  File "c:\users\windows\appdata\local\programs\python\python37\lib\site-packages\torch\utils\data\_utils\worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "c:\users\windows\appdata\local\programs\python\python37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "c:\users\windows\appdata\local\programs\python\python37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "c:\users\windows\appdata\local\programs\python\python37\lib\site-packages\ultralytics\yolo\data\dataset.py", line 262, in __getitem__
    sample = self.torch_transforms(im)
  File "c:\users\windows\appdata\local\programs\python\python37\lib\site-packages\torchvision\transforms\transforms.py", line 60, in __call__
    img = t(img)
  File "c:\users\windows\appdata\local\programs\python\python37\lib\site-packages\ultralytics\yolo\data\augment.py", line 881, in __call__
    imh, imw = im.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
`

**Comment by glenn-jocher** [comment]
@keaneflynn hi there,

I understand that you are encountering an error during training and you suspect there might be a faulty image causing the issue. Adding a "bad.list" feature similar to what is available in PJ Reddies YOLOv4 to identify problematic images would be a useful addition. 

In this particular case, the error seems to be related to a "Premature end of JPEG file" and subsequently a 'NoneType' object having no attribute 'shape'. This suggests that there might indeed be an issue with one of the image files, causing the error during data loading.

To help identify the problematic image file, one approach you can take is to isolate smaller batches of your image dataset and gradually narrow down the scope of images that are being processed. This way, you can identify the specific image(s) causing the error more efficiently and reduce the effort required to sift through all 100k images.

I hope this explanation helps you address the issue with YOLOv8. If you have any further questions, feel free to ask. Cheers!

**Comment by monkeycc** [comment]
I have discovered the problem

1. Rectangle annotation, not labeled in order from left to right, from right to left
2. Picture frame, coordinates exceeding the maximum or minimum value of the image, such as 800 * 800, coordinates -1 or 809
3. Labels may have special symbols, spaces, etc

-------------------------------------------------------------------------

The official solution should be:

1. Yolov8 should output the problematic annotation file path
The path for outputting errors is convenient for us to troubleshoot problems
We can delete this file or manually adjust it

2. Provide a script for dataset checking and output problematic paths

@glenn-jocher

**Comment by keaneflynn** [comment]
@monkeycc 
I was encountering this error on a classification task so it seems like the problem might be a bit larger than just annotations. Regardless definitely sounds like this could benefit from an output list pointing to faulty images/annotation files. I will post a feature request when I get a chance.

**Comment by glenn-jocher** [comment]
@keaneflynn 

Thank you for bringing this issue to our attention. Based on your findings, it appears that the error might not be limited to annotations alone, but also related to other factors such as incorrect labeling order, coordinates exceeding image boundaries, and non-standard labels.

To better assist with troubleshooting, we understand the need for YOLOv8 to output the specific paths of problematic annotation files or images. This would allow users to easily identify and address the issues by either manually adjusting the files or removing them from the dataset.

Additionally, providing a script for dataset checking that can highlight problematic paths would be a valuable tool for users. This way, users can efficiently identify and resolve any errors in their dataset.

We appreciate your feedback, and we encourage you to submit a formal feature request outlining these suggestions. This will ensure that our development team considers and implements these improvements in future updates of YOLOv8.

Thank you once again for your contribution to the YOLOv8 community. If you have any further questions or need assistance, please feel free to reach out.

**Comment by glenn-jocher** [comment]
@AlainPilon i appreciate the challenge you're facing with the large dataset, and I understand how crucial it is to streamline the debugging process, especially when such errors occur. Identifying problematic files in large datasets can be a significant hurdle and a time-consuming process without the right tools or error outputs.

The suggestion to have YOLOv8 output the path to the problematic file upon encountering an error is indeed a valid and helpful feature. It would allow for faster identification and resolution of issues that halt the training process. Noting the commonality of this request, taking this feedback to the development team would be a logical step. Meanwhile, you can follow any current best practices for dataset validation and error handling, although I recognize that with your dataset's size, that's not a trivial task.

While I can't commit to immediate changes or feature implementations, I am committed to ensuring your voice is heard. If you have any more insights or questions, please feel free to share them. Your feedback is invaluable in improving YOLOv8. Thank you for your contribution to making YOLOv8 a more robust and user-friendly tool.
