### ISSUE TITLE
MPS device returning incorrect keypoints for YOLOv8 pose estimation model

### ISSUE THREAD

**Issue by xalil8** [ultralytics/ultralytics#2184]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I'm encountering an issue with the YOLOv8 pose estimation model inference using the MPS model. The model is returning incorrect key points. However, when I use the same method and code on the CPU, the key points are correct. I believe the issue may be related to the Apple Metal library. From my research, it seems to be causing the error. The bounding boxes detection seems to be working fine, but there's an issue with calculating the key points. Could you please help me solve this problem?
Here are the test results 

With Mps 
<img width="1168" alt="Screenshot 2023-04-19 at 15 54 42" src="https://user-images.githubusercontent.com/46287166/233778053-94b7af38-43a9-4fa1-8a4d-c9a96510fdc6.png">

With Cpu 
<img width="1212" alt="Screenshot 2023-04-19 at 16 18 57" src="https://user-images.githubusercontent.com/46287166/233778040-cee612bb-b963-483e-b4cb-777a7f0c1129.png">

### Environment

ultralytics Version: 8.0.81
Python Version: 3.10.8
Torch Version: 2.1.0.dev20230417
Opencv Version: 4.7.0.72

### Minimal Reproducible Example

`
import cv2
import numpy as np
from ultralytics import YOLO

cv2.namedWindow("mps_test",cv2.WINDOW_NORMAL)
image = cv2.imread("pose_test.jpeg")
model = YOLO('yolov8s-pose.pt')  # load an official model

results = model(source=image,device="cpu",conf=0.6)
#results = model(source=image,device="mps",conf=0.6)

result_image = results[0].plot()

cv2.imshow("cpu_test", result_image)
cv2.waitKey(0)
cv2.destroyAllWindows()`

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @xalil8, thank you for reaching out with your issue. As you already know, YOLOv8 uses the Metal Performance Shaders framework to accelerate neural network training and inference on MacOS and iOS systems. It's possible that you're experiencing issues with the Metal library causing incorrect key points calculation. We recommend confirming that Metal is properly installed and set up. You could try disabling MPS acceleration and running the model on the GPU instead, as this may help further isolate the issue. Additionally, you may find it helpful to reach out to the Metal support team for further assistance in troubleshooting this issue. Good luck with your debugging!

**Comment by xalil8** [comment]
Hi @glenn-jocher, thanks for your response. I wanted to share the issue here because after looking into it a bit more, I found that there doesn't seem to be a problem with tensor conversion for bounding boxes. However, Model having trouble converting key points, which might be related to the conversion process in the yolov8 code.

**Comment by glenn-jocher** [comment]
Hello @xalil8, thanks for your update. It is possible that the issue you're facing with key point conversion may be related to a conversion process in the YOLOv8 code, as you mentioned. However, without seeing more information about the error message or logs, it's difficult to say for sure what the root cause is. If you have verified that Metal is properly installed and set up, it may be helpful to reach out to the YOLOv8 support team or open a bug report issue with as much detail as possible, including the test results, to facilitate further troubleshooting. The YOLOv8 documentation may also provide additional insights or tips on this topic. Best of luck with further debugging!

**Comment by gsnoh** [comment]
Hi all,
I have faced the same issue with @xalil8.
The bounding box is correct but key points are incorrect.
I have verified Metal is installed well based on (https://developer.apple.com/metal/pytorch/)
