### ISSUE TITLE
Can someone tell me how to release the thread after the training is finished？

### ISSUE THREAD

**Issue by CaptainMai** [ultralytics/ultralytics#2193]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am training in gui, after the training is finished but the thread and memory usage seem to be unable to end, I have to restart to train, I want to ask how to free the memory? I've tried a lot of things. They don't seem to work。

**Comment by glenn-jocher** [comment]
@CaptainMai it sounds like you are experiencing issues with thread and memory usage in YOLOv8 after finishing training in the gui. There could be a few potential solutions to try to free up the memory, such as optimizing your data loading procedures or reducing the batch size during training. You may want to refer to the documentation at https://docs.ultralytics.com for further insights on how to reduce memory usage in YOLOv8. I hope this helps!
