### ISSUE TITLE
How to push a stream to display the predicted results of model processing again

### ISSUE THREAD

**Issue by xiaohangguo** [ultralytics/ultralytics#2195]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I use the local YOLOv8 environment as a server to infer the video stream obtained by the network camera. How can I push the results with detection boxes out for real-time display after processing them

**Comment by glenn-jocher** [comment]
@xiaohangguo to achieve real-time display after processing the video stream with detection boxes, you can consider using an output module such as OpenCV's `cv2.imshow()` function to display the frames with boxes overlaid. Alternatively, you can save the frames with boxes overlaid to a video file and display it using a video player application. For more information and implementation details, you can refer to the Ultralytics YOLOv8 documentation at https://docs.ultralytics.com/.
