### ISSUE TITLE
Can you share the training log of sementation?

### ISSUE THREAD

**Issue by CangHaiQingYue** [ultralytics/ultralytics#2197]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello， I am trying to replicate the segmentation results, can you share the training log?
Thanks!

**Comment by glenn-jocher** [comment]
Hello @CangHaiQingYue, glad to assist you. The YOLOv8 segmentation architecture is based on YOLOv5, but with a modified head architecture. You can find the training logs and more details on the YOLOv8 Segmentation overview in the [Docs](https://docs.ultralytics.com/v8/segmentation/). 

The Segmentation training logs are available in the `runs/train/exp*/labels.png` and `runs/train/exp*/pred.png` for pixel-level visualizations of ground truth labels and predicted masks, respectively. You can also explore the [GitHub Issues](https://github.com/ultralytics/ultralytics/issues?q=is%3Aissue+is%3Aclosed+label%3Asegmentation+) and [Discussions](https://github.com/ultralytics/ultralytics/discussions?discussions_q=segmentation) to see how other users approached their Segmentation training tasks.

I hope this helps!
