### ISSUE TITLE
YOLOv8 Python SDK issues

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/ultralytics#220]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

@glenn-jocher 
I installed ultralytics via pip, I executed this line of code `results = model("https://media.roboflow.com/notebooks/examples/dog.jpeg", save=True)`, I found that the exported result is Tensor type, I want to detect the coordinate data and category data of the bounding box, how should I get it?

**Comment by Laughing-q** [comment]
@Zengyf-CVer hey the outputs are:
detection - List[nxTensor[]] - one 1x6 tensor for each of the n images
segmentation - List[nx[Tensor, Tensor]] - Here output of each image itself is a list of 2 tensors, 1st is the detection part and 2nd is the segmentation mask
