### ISSUE TITLE
Why model inference result shape is 1 84 8400?

### ISSUE THREAD

**Issue by dongqianzhuan** [ultralytics/ultralytics#221]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

1 84 8400 is (batch,xywh+80class_score,boxes_num )

yolov5 is (batch, boxes_num, xywh+80class_score )

why use this?it is more efficient?

**Comment by AyushExel** [comment]
@dongqianzhuan where are you seeing this shape? Can you please provide a minimal reproducible code? Thanks!

**Comment by dongqianzhuan** [comment]
> @dongqianzhuan where are you seeing this shape? Can you please provide a minimal reproducible code? Thanks!
i run this code

`from ultralytics import YOLO
model = YOLO('yolov8s.pt')  
model.export(format="onnx")`

i export onnx ,and watch it in netron,it`s dim different with yolov5
if i want run it with my yolov5_onnx_inference project,i need transpose yolov8_res(0,2,1)
i want to know why use this new shape ,it is more efficient?

**Comment by Laughing-q** [comment]
@dongqianzhuan if I remember this correctly, we removed some unnecessary torch.permute operation. Then it's (1, 84, 8400).

**Comment by dongqianzhuan** [comment]
> 
OK i understand,thank u
