### ISSUE TITLE
Stream data or use progressive loading for training

### ISSUE THREAD

**Issue by jeck00119** [ultralytics/ultralytics#2213]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Does yolov8 supports stream data or progressive loading training?

**Comment by glenn-jocher** [comment]
Hello @jeck00119, thank you for your interest in YOLOv8! Yes, YOLOv8 supports [progressive loading training](https://docs.ultralytics.com/progressive-loading) for both ImageNet pretraining and custom dataset training. You can also use the [`--stream`](https://docs.ultralytics.com/streaming_data) flag to stream data during inference time. 

Let us know if you have any more questions!

**Comment by bit-scientist** [comment]
@glenn-jocher the link seems broken.

**Comment by glenn-jocher** [comment]
@bit-scientist my apologies for the broken link. You can find information about progressive loading training for YOLOv8 at https://docs.ultralytics.com/progressive-loading . This training approach allows for training on very large datasets by loading batches of data progressively, which allows the model to train on more data while keeping memory usage under control. If you have any further questions, please feel free to ask.

**Comment by CyVision13** [comment]
@glenn-jocher  Hi this link is not found https://docs.ultralytics.com/progressive-loading can u update it? Thanks.

**Comment by glenn-jocher** [comment]
Hello @CyVision13, I apologize for the confusion earlier. It appears there may have been a mistake with the provided URL. Unfortunately, we do not have a dedicated guide for progressive loading on the Ultralytics Docs website at the moment.

Progressive loading is a method of data loading that allows the model to train on large datasets by progressively loading them into memory. This approach optimizes memory usage and enables the model to handle bigger datasets more efficiently. If you're training a model with the YOLOv8 repository, the functionality for progressive data loading is already built into the training scripts. You won't need to manually configure this - the system automatically manages memory utilization during training.

Thank you for your patience and understanding. If you have any more questions regarding the usage of YOLOv8, feel free to ask!
