### ISSUE TITLE
Add the actual count in confusion matrix

### ISSUE THREAD

**Issue by darouwan** [ultralytics/ultralytics#2214]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I notice there is only the percentage number in the current confusion matrix. However, in practice, the data count in each class is imbalanced and the general percentage cannot represent the actual result well. 
For example, for the validation result:
|     | | Predict |Predict |
|  ----  | ----  | ----|----|
|    |  | A| B|
| True  | A | 990| 10
| True    | B | 5| 5|

the current confusion matrix will be : 

|     | | Predict |Predict |
|  ----  | ----  | ----|----|
|    |  | A| B|
| True  | A | 0.99| 0.01
| True    | B | 0.5| 0.5|

But the data amount for class B is relatively small and it will not impact the general result too much. 
So I suggest adding a confusion matrix including the actual amount of data for each class. 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by darouwan** [comment]
@glenn-jocher I have submitted the PR for this feature: #2444 
The new confusion matrix will be like this:
[![iadnvy.png](https://i.328888.xyz/2023/05/07/iadnvy.png)](https://imgloc.com/i/iadnvy)

**Comment by glenn-jocher** [comment]
@darouwan You did a great job creating the PR #2444 for YOLOv8's confusion matrix feature request. Thank you for your contribution to the project. We will review and test the code changes and provide feedback as needed. We appreciate your effort and look forward to merging your PR into the main branch.

**Comment by darouwan** [comment]
New PR for remaining issue #2472

**Comment by glenn-jocher** [comment]
@darouwan, thank you for your contribution to the YOLOv8 project. We appreciate your effort in creating a new PR for issue #2472. We will review and test the changes and get back to you as soon as possible. If we have any additional feedback, we will provide it in the PR comments section. Thank you again for your contribution and support for YOLOv8.
