### ISSUE TITLE
When I run the Track demo, I get the following error:   TypeError: 'float' object cannot be interpreted as an integer.

### ISSUE THREAD

**Issue by peiyun1982** [ultralytics/ultralytics#2216]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

![e01](https://user-images.githubusercontent.com/16250376/233981935-180eab24-a08f-460c-a012-12c6f81e8e0e.jpg)
![e02](https://user-images.githubusercontent.com/16250376/233981951-6b96248e-beaf-4047-8914-b6ef5e044c11.jpg)
![e03](https://user-images.githubusercontent.com/16250376/233981962-955d242b-6644-4a5b-b040-af46af853540.jpg)

### Environment

YOLO：ultralytics 8.0.86
Python 3.10.11
windows 11
NVIDIA RTX 3080 v31.0.15.3141 10G
CUDA 11.6
pytorch==1.12.1
torchvision==0.13.1
torchaudio==0.12.1
cudatoolkit=11.6

### Minimal Reproducible Example

```
from ultralytics import YOLO

# Load a model
#model = YOLO('yolov8n.pt')  # load an official detection model
model = YOLO('yolov8n-seg.pt')  # load an official segmentation model
#model = YOLO('path/to/best.pt')  # load a custom model

# Track with the model
results = model.track(source="https://youtu.be/Zgi9g1ksQHc", show=True) 
#results = model.track(source="https://youtu.be/Zgi9g1ksQHc", show=True, tracker="bytetrack.yaml") 
```

### Additional

When I run the Track demo, I get the following error: 
`TypeError: 'float' object cannot be interpreted as an integer.`

The video loading process is normal, but the error message appears later.

PS: The CLI command is:

`yolo track [model=yolov8n.pt](http://model/%3Dyolov8n.pt/) source="https://youtu.be/Zgi9g1ksQHc" conf=0.3, iou=0.5 show`

It can work normally.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@peiyun1982, thank you for your interest in YOLOv8! In order to help you with this issue, we would need additional information. Can you please provide more context as to where in the YOLOv8 codebase this error is occurring? Additionally, please confirm whether the issue occurs exclusively with the track() function, or if it occurs in other areas of the codebase as well. We look forward to your response! Also, remember that you can always check out the YOLOv8 [Docs](https://docs.ultralytics.com/) for helpful guides and examples.

**Comment by peiyun1982** [comment]
> 
@glenn-jocher 
Thank you for your response.

First, I followed the examples in YOLOv8 Docs and obtained the code with the following command:
```
git clone https://github.com/ultralytics/ultralytics
cd ultralytics
pip install -e .
```
Then, open the ultralytics folder using vscode and create a new file named `testrun.ipynb`.
Copy the following code from YOLOv8 Dcos:
```
from ultralytics import YOLO
model = YOLO('yolov8n-seg.pt')
results = model.track(source="https://youtu.be/Zgi9g1ksQHc", show=True)
```
After running, the following results are obtained:
```
1/1: https://youtu.be/Zgi9g1ksQHc... Success  (6557 frames of shape 1280x676 at 24.00 FPS)


    WARNING  stream/video/webcam/dir predict source will accumulate results in RAM unless `stream=True` is passed,
    causing potential out-of-memory errors for large sources or long-running streams/videos.

    Usage:
        results = model(source=..., stream=True)  # generator of Results objects
        for r in results:
            boxes = r.boxes  # Boxes object for bbox outputs
            masks = r.masks  # Masks object for segment masks outputs
            probs = r.probs  # Class probabilities for classification outputs

0: 352x640 1 car, 641.8ms
0: 352x640 6 persons, 1 cup, 1 bowl, 1 tv, 1 laptop, 1 mouse, 12.5ms
Output exceeds the size limit. Open the full output data in a text editor---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[7], line 9
      5 model = YOLO('yolov8n-seg.pt')  # load an official segmentation model
      6 #model = YOLO('path/to/best.pt')  # load a custom model
      7 
      8 # Track with the model
----> 9 results = model.track(source="https://youtu.be/Zgi9g1ksQHc", show=True)

File c:\Users\zwill\ultralytics\ultralytics\yolo\engine\model.py:275, in YOLO.track(self, source, stream, persist, **kwargs)
    273 kwargs['conf'] = conf
    274 kwargs['mode'] = 'track'
--> 275 return self.predict(source=source, stream=stream, **kwargs)

File c:\Users\zwill\.conda\envs\YoloV8\lib\site-packages\torch\autograd\grad_mode.py:27, in _DecoratorContextManager.__call__..decorate_context(*args, **kwargs)
     24 @functools.wraps(func)
     25 def decorate_context(*args, **kwargs):
     26     with self.clone():
---> 27         return func(*args, **kwargs)

File c:\Users\zwill\ultralytics\ultralytics\yolo\engine\model.py:252, in YOLO.predict(self, source, stream, **kwargs)
    250 else:  # only update args if predictor is already setup
    251     self.predictor.args = get_cfg(self.predictor.args, overrides)
--> 252 return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
...
     55 def __getitem__(self, idx):
     56     """Return a BaseTensor with the specified index of the data tensor."""
---> 57     return self.__class__(self.data[idx], self.orig_shape)

TypeError: 'float' object cannot be interpreted as an integer
```
This is all
![e002](https://user-images.githubusercontent.com/16250376/234153451-36f5b695-f21e-4ddd-8035-16fae2e9ae44.jpg)
![e003](https://user-images.githubusercontent.com/16250376/234153457-f78daac5-5cd0-45c5-8be4-29c7a79b5d83.jpg)
![e001](https://user-images.githubusercontent.com/16250376/234153445-de41e40a-e898-4a18-83b4-8261d2f2298d.jpg)

**Comment by Souviksaha1998** [comment]
Hi @peiyun1982 , if you clone the repo from github then please go to this path "ultralytics\yolo\engine\results.py " 
 and change this function from `def __getitem__(self, idx):
        """Return a BaseTensor with the specified index of the data tensor."""
        return self.__class__(self.data[idx], self.orig_shape`
to this -->
`def __getitem__(self, idx):
        """Return a BaseTensor with the specified index of the data tensor."""
        if type(idx) == int:
            return self.__class__(self.data[idx], self.orig_shape)`
hope this will solve your problem. Thank you

**Comment by glenn-jocher** [comment]
Hello @Souviksaha1998, thank you for reaching out to us. It seems like you are encountering a traceback error when implementing the track() function on the YOLOv8 repository. 

After looking into the issue, it appears that the error occurs due to a 'float' object which is incorrectly interpreted as an integer. We recommend that you update the function by modifying the `results.py` file so that the `__getitem__` function returns output that is expected by your code. Specifically, in the `__getitem__` function, include a type check on the input index `idx` such that if `idx` is an integer, then the function will return the `BaseTensor` class with the specified index of the data tensor.

Please let us know if this resolves your issue. Thank you.
