### ISSUE TITLE
Example of ONNX interface of pose estimation with C++

### ISSUE THREAD

**Issue by mallumoSK** [ultralytics/ultralytics#2222]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Please add similiar example as this
[YOLO ONNX Detection Inference with C++](https://github.com/ultralytics/ultralytics/blob/main/examples/YOLOv8-CPP-Inference)
**BUT** for **pose estimation**.
Thanx.

### Use case

I have Firefly embedded boards with **NNAPI** (**RK3588**), **Os Android**. 
My knowledge of Python is ZERO. 
Currently i am using multi-pose detection by movenet. 
But YOLOv8-pose gave mutch better results. I try by [CLI](https://docs.ultralytics.com/usage/cli/)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mallumoSK, thank you for reaching out to us and for your interest in contributing to YOLOv8! Currently, we do not have a pose estimation implementation available for YOLOv8 like the one you have described for detection in C++. 
 
However, we appreciate your enthusiasm and welcome contributions from the community. With regard to contributing a pose estimation implementation for YOLOv8, you may find the following resources helpful:

- [YOLOv8 Docs](https://docs.ultralytics.com/docs/yolov8/), particularly the sections on [Pose Estimation Tasks](https://docs.ultralytics.com/tasks/pose/) and [Building Custom Models](https://docs.ultralytics.com/models/custom/)
- The [PyTorch documentation](https://pytorch.org/docs/stable/index.html) and [PyTorch tutorials](https://pytorch.org/tutorials/) may also prove useful in implementing custom models and training them

I hope that helps! Best of luck with your implementation, please let us know if you have any further questions or if there is anything we can do to help.

**Comment by triple-Mu** [comment]
Here is a tensorrt demo https://github.com/triple-Mu/YOLOv8-TensorRT/tree/main/csrc/pose/normal

**Comment by glenn-jocher** [comment]
@triple-Mu thank you for sharing this with us! While this is not an official implementation from the Ultralytics team, we appreciate community contributions like this to the YOLOv8 ecosystem. TensorRT can provide advantages over native PyTorch models, such as faster inference speeds and reduced memory usage. Additionally, as YOLOv8 is designed to be flexible, there are many potential use cases for the model beyond object detection and we welcome innovations like this for pose estimation. 

Thanks again for sharing, and please let us know if you have any further questions or feedback!

**Comment by mallumoSK** [comment]
thanx @triple-Mu
helps a lot
P.S.: i rewrite  whole to opencv ...
https://github.com/mallumoSK/yolov8
Me C++ is not the best, but works  :)

**Comment by glenn-jocher** [comment]
@mallumoSK it's great to hear that @triple-Mu's TensorRT demo was helpful to you! We appreciate contributions like these from the community. It's also impressive that you were able to rewrite the codebase to OpenCV - while C++ may not be your strongest language, it's important to remember that practice makes perfect! 

Please let us know if you have any further questions or if there is anything we can do to help. Best of luck with your implementation!
