### ISSUE TITLE
Metrics to report mIoU of all classes or a certain class in Semantic Segmentation task in validate.

### ISSUE THREAD

**Issue by Arshadoid** [ultralytics/ultralytics#2227]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

It would be great to have an option of reporting mIoU of all classes or a certain class in a Semantic Segmentation task. 

### Use case

Most of the papers report mIoU for semantic segmentation tasks. Although mAP metrics are already reported for instance segmentation, it would be great to have reporting of mIoU for semantic segmentation (combined instances) so the model performance can be compared with the existing methods.  

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Arshadoid thank you for your feature request! Reporting mIoU for semantic segmentation seems like a valuable addition to YOLOv8's features. Have you tried calculating mIoU manually using the available predictions and ground truths? If you encounter any difficulties, please feel free to ask for help. Additionally, the Ultralytics YOLOv8 documentation provides information on the available metrics and how to use them.

**Comment by Arshadoid** [comment]
Hi @glenn-jocher, thanks for the feedback. I will continue the conversation on this topic [here](https://github.com/ultralytics/ultralytics/issues/2191#issuecomment-1519316959).
