### ISSUE TITLE
Setup should detect MPS

### ISSUE THREAD

**Issue by robmarkcole** [ultralytics/ultralytics#2233]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

torch-2 is used and will detect MPS but this is not indicated by `ultralytics.checks()`

This should be updated to show MPS detected and will be used:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/11855322/234237499-7690652e-7a89-4bfc-8f80-75a1bdc30273.png">

Then on training, it is used:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/11855322/234237814-d650a274-0631-483c-8293-01b931db097a.png">

### Use case

Devs on MPS machine

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@robmarkcole thank you for bringing this to our attention. We appreciate your suggestion to update `ultralytics.checks()` to reflect the detection of MPS in torch-2. We have taken note of this and will consider it for a future update. In the meantime, please refer to the documentation at https://docs.ultralytics.com for additional information on MPS detection in YOLOv8.
