### ISSUE TITLE
detection, crops, filename suffix

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/ultralytics#2234]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Current behavior appears to append an integer to the crop object filename.
Has anyone requested an option to allow a configuration file parameter for the suffix?

cropdetectionsuffix = '_%09d'{existingsuffix}

**Comment by glenn-jocher** [comment]
@apiszcz in python you can also return the crops without saving and handle saving with a custom script.
