### ISSUE TITLE
“Resume training” yields different metrics compared to a full run without resume

### ISSUE THREAD

**Issue by veskatsenkova** [ultralytics/ultralytics#2235]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I run a full training session on the coco dataset using:
yolo detect train data=coco128.yaml model=yolov8n.pt epochs=10 imgsz=128

Then I run the exact same training using
yolo detect train data=coco128.yaml model=yolov8n.pt epochs=10 imgsz=128

and interrupt it(CTRL-C) after epoch 5 is finished.

Then I resume the training with
yolo task=detect mode=train resume model=c:\users\veska\documents\ultralytics\runs\detect\train\weights\last.pt
The training is resumed successfully and I get another results.csv file with metrics.

The metrics from the full experiment and the ones from the resumed experiment are supposed to be similar. However, the metrics in the two results.csv files are identical only up to the epoch at which the train was interrupted. After that the resumed training starts to produce different precision, recall, etc. and overall the results(comparing the csv files)
of the 2 experiments significantly differ. 

results.csv from the full, uninterrupted experiment:

<img width="960" alt="results_full_exp_1" src="https://user-images.githubusercontent.com/110890926/234254893-16d8c328-fa75-4e35-bb77-463ac1b9eee7.png">

results.csv from the resumed experiment

<img width="960" alt="results_resumed_exp" src="https://user-images.githubusercontent.com/110890926/234255470-f7f85209-61fa-4fa8-8b0c-88d6138b9e8c.png">

### Environment

YOLOv8.0.87  Python-3.10.6 torch-2.0.0+cpu CPU
Windows 10.0.19045
Python: 3.10.6

### Minimal Reproducible Example

"""for training"""
yolo detect train data=coco128.yaml model=yolov8n.pt epochs=10 imgsz=128

"""for resuming"""
yolo task=detect mode=train resume model=c:\users\veska\documents\ultralytics\runs\detect\train\weights\last.pt

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@veskatsenkova there's no bug. What happens is that random number generates are initialized in both trainings and the RNG will be at a different place in generating cycle in both of your experiments, producing different augmentations (and any other effect based on RNG like shuffling etc.)
