### ISSUE TITLE
Feed images/boxes during training manually?

### ISSUE THREAD

**Issue by XPbIM3** [ultralytics/ultralytics#2237]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi!
Any chance to feed images/boxes during training mannually from memory?   NOT pointing to disk folder as it supposed by data= argument.

**Comment by AyushExel** [comment]
When you set `cache=True`(ram) or `cache=disk` it stores the dataset cache in memory(ram or HDD depending on how you set it)
