### ISSUE TITLE
automaticlly download weights

### ISSUE THREAD

**Issue by isOreo** [ultralytics/ultralytics#2239]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I use the "model.train(**{'cfg': 'ultraltics/yolo/cfg/default.yaml'})" in python SDK,  It will train using yolov8n, and automaticlly downloading yolov8n.pt, rather than my.yaml. And I don't choose yolov8n.yaml and yolov8.pt in default.yaml

**Comment by AyushExel** [comment]
`cfg` is used to override the default configuration using a .yaml file (https://docs.ultralytics.com/usage/cfg/#train).
If you want to pass a model just pass `model="model.yaml"` or `"model.pt"` as mentioned in the link above
