### ISSUE TITLE
yolov8-pose

### ISSUE THREAD

**Issue by zcunyi** [ultralytics/ultralytics#224]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Whether yolov8-pose will be provided?

**Comment by Laughing-q** [comment]
@zcunyi yeah that's on our TODO list.

**Comment by AyushExel** [comment]
@zcunyi yes this is just a start.. We're working towards making this is a platform to support any task/model/interface users would want, which would also allow us to accept user contributions more often

**Comment by AyushExel** [comment]
We added this to the roadmap. I'm closing this issue. Please reopen is there are any other questions

**Comment by xinsuinizhuan** [comment]
looking forward to yolov8-pose

**Comment by priyankinfinnov** [comment]
looking forward to yolov8-pose, any estimate timelines? (like is it weeks or months?)

**Comment by AyushExel** [comment]
most likely 2 months

**Comment by tctco** [comment]
looking forward to yolov8-pose

**Comment by zcunyi** [comment]
> most likely 2 months

too long , crying

**Comment by pderrenger** [comment]
@tctco we appreciate your enthusiasm! Keep an eye on our updates for the latest developments.

**Comment by glenn-jocher** [comment]
@pderrenger Thanks for your interest! We're excited too and will share news as soon as it's ready. Stay tuned! 🚀

**Comment by glenn-jocher** [comment]
Pose is out!! Let us know if you need any help using it :)

See https://docs.ultralytics.com/tasks/pose
