### ISSUE TITLE
Custom YOLOv8 detection training issue

### ISSUE THREAD

**Issue by terbed** [ultralytics/ultralytics#2240]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

> Starting training for 100 epochs...
> 
>       Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
>   0%|          | 0/106 [00:00<?, ?it/s]zero-size array to reduction operation maximum which has no identity
>       1/100     0.472G          0      4.703          0          0        128: 100%|██████████| 106/106 [00:07<00:00, 14.73it/s]
>                  Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:00<00:00, 22.39it/s]
> Traceback (most recent call last):
>   File "/home/terbed/PROJECTS/DHM/RCH/HoloReckoning/yolo/train_yolo.py", line 8, in <module>
>     model.train(data="data.yaml", imgsz=128, classes=1, device="cuda:0", hsv_h=0., hsv_s=0., hsv_v=0.)
>   File "/home/terbed/anaconda3/envs/DL/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 370, in train
>     self.trainer.train()
>   File "/home/terbed/anaconda3/envs/DL/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 191, in train
>     self._do_train(world_size)
>   File "/home/terbed/anaconda3/envs/DL/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 364, in _do_train
>     self.metrics, self.fitness = self.validate()
>   File "/home/terbed/anaconda3/envs/DL/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 464, in validate
>     metrics = self.validator(self)
>   File "/home/terbed/anaconda3/envs/DL/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/terbed/anaconda3/envs/DL/lib/python3.10/site-packages/ultralytics/yolo/engine/validator.py", line 175, in __call__
>     stats = self.get_stats()
>   File "/home/terbed/anaconda3/envs/DL/lib/python3.10/site-packages/ultralytics/yolo/v8/detect/val.py", line 130, in get_stats
>     self.nt_per_class = np.bincount(stats[-1].astype(int), minlength=self.nc)  # number of targets per class
> IndexError: list index out of range
> 
> Process finished with exit code 1

### Environment

Ultralytics YOLOv8.0.87 🚀 Python-3.10.9 torch-2.0.0 CUDA:0 (NVIDIA GeForce GTX 1060 6GB, 6073MiB)

### Minimal Reproducible Example

```
from ultralytics import YOLO

# Load a model
# model = YOLO('yolov8n.yaml')  # build a new model from YAML
model = YOLO('yolov8s.pt')  # load a pretrained model (recommended for training)

# Train
model.train(data="data.yaml", imgsz=128, classes=1, device="cuda:0", hsv_h=0., hsv_s=0., hsv_v=0.)
```

data.yaml:
```
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: /home/terbed/PROJECTS/DHM/DATA/SGDM/sco_yolo_splits  # dataset root dir
train: train  # train images (relative to 'path') 128 images
val: val  # val images (relative to 'path') 128 images
test: test  # test images (optional)

names:
  0: object
```

### Additional

I only have 1 class in this task. 1 epoch successfully ends and the issue comes after it.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
The problem seems to generate from `get_stats()` after the 1st validation is done. If the dataset is small enough and can be shared, it'd be helpful for us if you could share it.

**Comment by Laughing-q** [comment]
@terbed noticed you only have one class but use `classes=1` in your training command. `classes=1` means you only train with your second category which you don't have. this is incorrect.
please remove the `classes=1` in you training command and try again.

**Comment by terbed** [comment]
Dear @Laughing-q,
Thank you for your fast response! You are right, removing `classes=1` solves the issue! I thought this property overrides the default `nc=80` value to `nc=1`, so it is a little bit misleading.
