### ISSUE TITLE
Add way to disable integration callbacks

### ISSUE THREAD

**Issue by Toutatis64** [ultralytics/ultralytics#2241]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Today there is no way to disable a specific callback. 
If we want to custom some specific integrations (like mlflow), there is no way to disable it :(

An interesting feature would be at least to have a workaround to disable them. Today, the callbacks are loaded when calling train() method, so no way to bypass them. At least a workaround should be implemented for that...

### Use case

I want to custom the callback or no need to run the integration callbacks (mlflow for example), I cannot easily disable them. 

### Additional

I'm able to push a PR soon to disable callbacks by key (but won't be able to segregate between type of integrations)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Toutatis64** [comment]
For specific callbacks, maybe some workaround could be to switch environment variables like MLFLOW_TRACKING_URI just between some functions, but not convenient at all as we must keep old value to restore after specific calls, and need to know internal implementation of the callback :(

**Comment by glenn-jocher** [comment]
@Toutatis64 yes it's true callbacks are added by default if the corresponding package is installed. If you have mlflow installed then the callbacks will run by default. 

A hack to disable MLflow would be to `pip uninstall -y mlflow` but yes I agree there should be an alternative, perhaps in the settings, i.e. `yolo settings set mlflow False`

Run `yolo settings` to see current settings.

**Comment by edublanco** [comment]
@glenn-jocher  in the meantime, could you provide the version where this wasn't done in automatic o could you deactivate this feature? Any other workaround suggestion is appreciated

**Comment by glenn-jocher** [comment]
@edublanco unfortunately, we do not have previous versions of YOLOv5 that do not automatically generate callbacks upon installation. However, a possible workaround would be to uninstall the mlflow package temporarily or permanently. Alternatively, we could add a setting to disable or enable the automatic callback feature. You can view the current settings by running `yolo settings`. We apologize for any inconvenience this may have caused.

**Comment by edublanco** [comment]
In case anybody finds this useful, what I did was to locate where the packages where install by using `pip show ultralytics`, after that I navigate through the folders until I found mlflow.py where I commented the part where the model was being logged. The path for the script is: your_path/ultralytics/yolo/utils/callbacks

**Comment by Toutatis64** [comment]
OK I'll update settings to be able to bypass them. 
The way the settings version are used is that if I update the settings 'version number', it will overwrite all users settings configurations ...  :(
Do we need to update settings version only when we have incompatible updates ? So I don't have to update settings version in order to keep compatibility ? 
Or does this system should be updated to ease the update from a version to another ?

**Comment by glenn-jocher** [comment]
@Toutatis64 @edublanco great news 😃! Your original issue may now be resolved ✅ in PR #3790 and published in a new `ultralytics 8.0.141` release. This PR adds a SettingsManager class that allows for direct viewing and modifying of Ultralytics settings:

<img width="955" alt="Screenshot 2023-07-23 at 16 11 23" src="https://github.com/ultralytics/ultralytics/assets/26833433/1427f5bd-52b6-445a-ab5b-e4c0eeccc10b">

For details see https://docs.ultralytics.com/quickstart

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by edublanco** [comment]
Hello @glenn-jocher  thank so much for the update!

**Comment by Toutatis64** [comment]
Hi, good news, thanks a lot !

**Comment by glenn-jocher** [comment]
@edublanco you're welcome! We're glad to hear that you found the update helpful. If you have any further questions or issues, feel free to let us know. We're here to help! Happy training with YOLOv8.
