### ISSUE TITLE
Train with RGBD images

### ISSUE THREAD

**Issue by adarshvjois** [ultralytics/ultralytics#2242]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I would like to be able to train a yolov8 model on 4 channel images where the 4th channel is depth.

### Use case

This feature would be used for any of the following use cases:
- Classification
- Segmentation
- Object Detection
The goal of this would be to enhance the CLI interface. This would mean supporting a channels argument either in a model.yaml or any other means deemed valid by the project leads. The effect of this would be to initializing a model where the first conv layer accepts an input with the requested number of channels.

If finetuning weights are passed in, trained on images with a different number of channels, then the first layer should be initialized from scratch.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@adarshvjois - [X] No, I am not able to submit a PR at the moment.

**Comment by achbogga** [comment]
I am interested in this feature request as well!

**Comment by glenn-jocher** [comment]
@achbogga thank you for your interest in this feature request. Our team is always looking for ways to improve the user experience and we appreciate your feedback. We will add this to our list of potential features for future updates. Feel free to reach out if you have any further suggestions or questions.

**Comment by maciej-szulc-robotics** [comment]
This could be interesting feature...

**Comment by Pedro-Jobs** [comment]
Me too, i would like to perform segmentation tasks adding the fourth channel (depth).

**Comment by glenn-jocher** [comment]
@Pedro-Jobs absolutely, adding a depth channel for segmentation tasks sounds like a promising enhancement to improve model performance, especially in understanding spatial relationships in images. 🚀 While YOLOv8 currently doesn't natively support 4-channel inputs, you can experiment by modifying the first convolutional layer to accept an additional channel. Here's a quick example on how you might approach this in PyTorch:

```python
import torch.nn as nn

# Assuming 'model' is your YOLOv8 model
# Change the first conv layer to accept 4 channels
model.model[0].conv = nn.Conv2d(4, model.model[0].conv.out_channels, 
                                kernel_size=model.model[0].conv.kernel_size, 
                                stride=model.model[0].conv.stride, 
                                padding=model.model[0].conv.padding, 
                                bias=model.model[0].conv.bias)

# Note: You'll need to adjust the weights for this layer or initialize it as needed.
```

Keep in mind, this is a simplified example and integrating depth information effectively might require more adjustments. We're excited about exploring such features in future versions! 🌟

**Comment by Y-T-G** [comment]
Duplicate of https://github.com/ultralytics/ultralytics/issues/6929
