### ISSUE TITLE
How to get rid of verbose prompt print outputs like this?

### ISSUE THREAD

**Issue by TommyZihao** [ultralytics/ultralytics#2243]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I don't like this output print.

<img width="851" alt="image" src="https://user-images.githubusercontent.com/36354458/234466319-6bb4b288-7d79-4b0c-a286-692964cafc06.png">

**Comment by Laughing-q** [comment]
@TommyZihao add `verbose=False`

**Comment by glenn-jocher** [comment]
Also environment variable `YOLO_VERBOSE=False` works

**Comment by TommyZihao** [comment]
> verbose=False

How to do it in Python API

like this?

model = YOLO('yolov5n.pt', verbose=False)

**Comment by Laughing-q** [comment]
@TommyZihao yes!

**Comment by Laughing-q** [comment]
@TommyZihao oh sorry my mistake, it should be:
model= YOLO('yolov8n.pt')
model.predict(verbose=False)
