### ISSUE TITLE
How to handle background images without targets in the dataset?

### ISSUE THREAD

**Issue by ZhangLe-fighting** [ultralytics/ultralytics#2246]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would like to add some images without targets in the training dataset for training, with the aim of removing false positives caused by the background. Does YOLOV8 support this operation? If so, when using the COCO data format, does the image field in the JSON file include the image, but does not include the annotation information of the image in the annotations field? Is there a detailed explanation in this regard?

**Comment by pderrenger** [comment]
@ZhangLe-fighting absolutely! YOLOv8 supports the inclusion of images without any annotated targets in the training dataset. When using the COCO data format, the JSON file's "images" field will include these images, while the "annotations" field will not contain any annotation information for these background-only images. This allows you to train the model to distinguish between background and actual targets, helping reduce false positives. If you need further details on this, you can refer to the [Training](https://docs.ultralytics.com/modes/train) section in the Ultralytics Docs for a more comprehensive explanation.
