### ISSUE TITLE
Use different input size for training and validation

### ISSUE THREAD

**Issue by rusvagzur** [ultralytics/ultralytics#2249]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi Ultralytics team/community,

I would like to set different imgsz for training and validation, e.g. 640 for training and 320 for validation. I have been trying to get this done modifying the self.args.imgsz in various places of the trainer.py and validator.py within the engine directory but still haven't found a solution. Could you please give some hints on how to do that?

Many thanks

**Comment by glenn-jocher** [comment]
@rusvagzur good question! This feature is not available by default, but you could customize the training and validation code to achieve this in our own local branch or fork.

**Comment by rusvagzur** [comment]
@glenn-jocher Thanks. Could you please point to the scripts where that should be done? I'll be happy to submit a PR if this works out and is of interest for you.
