### ISSUE TITLE
CHANGING NAME OF PREDICTED LABEL ON PREDICTED IMAGE

### ISSUE THREAD

**Issue by edanurkamaci** [ultralytics/ultralytics#2255]
### Discussed in https://github.com/orgs/ultralytics/discussions/2254

<div type='discussions-op-text'>

<sup>Originally posted by **edanurkamaci** April 26, 2023</sup>
Hello i have an urgent question. I do not have time to train a model again so i wanted to change the name of labels after test result, but i want new labels on predicted result image. How can i do that?</div>

**Comment by edanurkamaci** [comment]
Yeah it is a custom training but i can not any infos bcs of the privicy

**Comment by glenn-jocher** [comment]
I understand, @edanurkamaci. If I understand your question correctly, you would like to change the label names of your test dataset without retraining the YOLOv8 model. If that's the case, the easiest way to do this is to manually modify the label files of your test dataset using a text editor or running a script that renames the labels.

Once you have your modified test dataset, you can use YOLOv8 to predict new bounding boxes using the `-save-txt` flag which will output the predicted bounding boxes with the modified label names specified in your modified test dataset. 

Please keep in mind that changing the label names without changing the training set can reduce the accuracy of your model predictions; thus, it is generally best to retrain your model with updated label names for optimal performance.
