### ISSUE TITLE
Exported ONNX cannot be opened in OpenCV

### ISSUE THREAD

**Issue by knoppmyth** [ultralytics/ultralytics#226]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

I created a custom object detector and export to ONNX. Attempting to load it in OpenCV results in the following error:
`[ERROR:0@0.816] global /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp (1018) handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 2 outputs: [Split]:(onnx_node!/model.22/Split) from domain='ai.onnx'
2023-01-10 19:55:38.062 Uncaught app exception
Traceback (most recent call last):
  File "/home/user/Development/Python/VENV/nfx/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/home/user/Development/foo/odmc.py", line 576, in <module>
    main()
  File "/home/user/Development/foo/odmc.py", line 568, in main
    directory_mode("browse")
  File "/home/user/Development/foo/odmc.py", line 503, in directory_mode
    detection_processing(image, confidence)
  File "/home/user/Development/foo/odmc.py", line 543, in detection_processing
    detect_yolov567(confidence, model_image, class_list=["foo"],
  File "/home/user/Development/foo/odmc.py", line 289, in detect_yolov567
    net = cv2.dnn.readNet(model_path)
cv2.error: OpenCV(4.6.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1040: error: (-2:Unspecified error) in function 'handleNode'
> Node [Split@ai.onnx]:(onnx_node!/model.22/Split) parse error: OpenCV(4.6.0) /io/opencv/modules/dnn/src/layers/slice_layer.cpp:235: error: (-215:Assertion failed) splits > 0 && inpShape[axis_rw] % splits == 0 in function 'getMemoryShapes'
> `

### Environment

- YOLO YOLOV8
- Arch Linux
- Python 3.10
- OpenCV 4.6.0.66

### Minimal Reproducible Example

Built a model and exported with:
`yolo mode=export model=runs/detect/train/weights/best.pt format=onnx`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by knoppmyth** [comment]
The same error is present w/ OpenCV 4.5 and 4.7. If I export with dynamic=True, this is the error I get:

`cv2.error: OpenCV(4.5.5) /io/opencv/modules/dnn/src/graph_simplifier.cpp:76: error: (-212:Parsing error) Input node with name /model.22/Gather_2_output_0 not found in function 'getInputNodeId'`

**Comment by knoppmyth** [comment]
I'm able to export with:
`yolo mode=export model=runs/detect/train/weights/best.pt imgsz=[640,640] format=onnx opset=11`
OpenCV 4.7 can read the resulting ONNX file. However since the format has changed, I need to adjust my code to properly parse the returned array.

**Comment by qtran2021** [comment]
@knoppmyth  Were you able to pass the blob into net.forward()? For some reason, it fails here.

**Comment by knoppmyth** [comment]
@qtran2021 Yes, see my code at #457.

**Comment by LACHENNG** [comment]
> yolo mode=export model=runs/detect/train/weights/best.pt imgsz=[640,640] format=onnx opset=11

works for me，thank you

**Comment by pderrenger** [comment]
@LACHENNG glad to hear that it worked for you! If you encounter any other issues or have further questions, feel free to ask. Good luck with your project!
