### ISSUE TITLE
Problem exporting into tensorflow "saved_model"

### ISSUE THREAD

**Issue by edublanco** [ultralytics/ultralytics#2264]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to export my modelo to tensorflow but I got this error:

TensorFlow SavedModel: export failure ❌ 12.5s: SavedModel file does not exist at: runs/detect/train21/weights/best_saved_model/{saved_model.pbtxt|saved_model.pb}
============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

I don't understand how to generate does files, if they generate automatically or what I am doing wrong. The path does exist, the files don't

**Comment by glenn-jocher** [comment]
@edublanco if you are having issues in your local environment I'd recommend trying your exports in one of the environments below:


## Environments

YOLOv8 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/GCP-Quickstart)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/AWS-Quickstart)
- **Docker Image**. See [Docker Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

**Comment by edublanco** [comment]
@glenn-jocher so when i am exporting to tensorflow, i got this error:
TensorFlow SavedModel: running 'onnx2tf -i runs/detect/train18/weights/best.onnx -o runs/detect/train18/weights/best_saved_model -nuo --non_verbose'
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/bin//onnx2tf", line 5, in <module>
    from onnx2tf import main
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/onnx2tf/__init__.py", line 1, in <module>
    from onnx2tf.onnx2tf import convert, main
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/onnx2tf/onnx2tf.py", line 28, in <module>
    tf.keras.utils.set_random_seed(0)

what version of tensorflow do i need?
