### ISSUE TITLE
AttributeError: 'NoneType' when using Ray Tune without wandb

### ISSUE THREAD

**Issue by Sylus1000** [ultralytics/ultralytics#2268]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Evolution

### Bug

When using:
```
model = YOLO("yolov8n.pt")
result = model.tune(
    data="coco128.yaml",
    space={"lr0": tune.uniform(1e-5, 1e-1)},
    train_args={"epochs": 50}
)
```
Without having wandb installed you get the following error message:
```
AttributeError: 'NoneType' object has no attribute 'setup'
```
Setting the tuner_callbacks parameter to None causes this error message https://github.com/ultralytics/ultralytics/blob/0a36b83e7addd5e21438d32a614bbdf3f330e6d9/ultralytics/yolo/engine/model.py#L456
After installing wandb it was solved. It would be nice tho to use raytune without having to install wandb. Maybe somone has the same issue and this helps ;)

### Environment

- OS : Windows 10 64bit
- Python 3.8.8

### Minimal Reproducible Example

```
model = YOLO("yolov8n.pt")
result = model.tune(
    data="coco128.yaml",
    space={"lr0": tune.uniform(1e-5, 1e-1)},
    train_args={"epochs": 50}
)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@Sylus1000 BTW yes the intention is for RayTune to work no matter what other packages are installed, so this is definitely a bug.
