### ISSUE TITLE
Difference between COCO and YOLO evaluation results

### ISSUE THREAD

**Issue by salwaalkhatib** [ultralytics/ultralytics#2269]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello!

I ran the evaluation using the COCO evaluation available in the YOLO repo itself by modifying the saved JSON to the relevant format (i.e. setting the image id accordingly). However, the results given by the coco evaluator were widely different than those given by the YOLO evaluator (20% difference in mAP 50-95). What is the reason behind this?

Would appreciate your help on this, thanks!

**Comment by glenn-jocher** [comment]
@salwaalkhatib hello! Thank you for reaching out. The reason for the difference in mAP 50-95 between the COCO and YOLO evaluators can be due to various factors such as differences in the parameter settings, annotations, or evaluation method. To help provide a more specific answer, could you please provide more details about the evaluation method you used, including parameter settings and evaluation metrics? Additionally, it could be helpful to provide some sample images and annotations for further investigation. Thank you.

**Comment by salwaalkhatib** [comment]
I am training an object detection model on the iSAID dataset. 

During evaluation, I ran with the `save_json=True` setting. In the val.py file, I made the following changes:

I hardcoded `self.is_coco=True`, and set the `anno_json ` path to the relevant path in the `eval_json ` function. 

I also modified the JSON before initializing the COCO evaluator so that the image_ids of the created JSON match the ground truth image_ids. 

Below is the modified `eval_json ` function

```
def fix_predjson_image_id(self,pred_json, anno_json):

        import json

        with open(pred_json, 'r') as f:

            pred = json.load(f)

        with open(anno_json, 'r') as f:

            anno = json.load(f)




        for p in pred:

            for im in anno['images']:

                if im['file_name'] == p['image_id'] + '.png':

                    p['image_id'] = im['id']

                    break

        with open(str(pred_json)[:-5] + '_new.json', 'w') as f:

            json.dump(pred, f)

        print('Saved altered predictions.json to ', str(pred_json)[:-5] + '_new.json')

    

    def eval_json(self, stats):

        if self.args.save_json and self.is_coco and len(self.jdict):

            anno_json = self.data['path'] / 'val/instancesonly_filtered_val.json' #'annotations/instances_val2017.json'  # annotations

            pred_json = self.save_dir / 'predictions.json'  # predictions

            # pred_json = Path('runs/detect/valsApr23/contr_momen_MultiStage_BS10Calib_0.2queue50_emaIters200_70epochs_mosaic1.0_closemosaic5ap_SML9/predictions.json')




            self.logger.info(f'\nEvaluating pycocotools mAP using {pred_json} and {anno_json}...')

            try:  # https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocoEvalDemo.ipynb

                check_requirements('pycocotools>=2.0.6')

                from pycocotools.coco import COCO  # noqa

                from pycocotools.cocoeval import COCOeval  # noqa




                self.fix_predjson_image_id(pred_json, anno_json)

                pred_json = self.save_dir / 'predictions_new.json'




                for x in anno_json, pred_json:

                    assert x.is_file(), f'{x} file not found'

                anno = COCO(str(anno_json))  # init annotations api

                pred = anno.loadRes(str(pred_json))  # init predictions api (must pass string, not Path)

                eval = COCOeval(anno, pred, 'bbox')

                print('After COCOeval')

                # print(len(eval.params.imgIds))

                # if self.is_coco:

                #     eval.params.imgIds = [int(Path(x).stem) for x in self.dataloader.dataset.im_files]  # images to eval

                eval.evaluate()

                print('After eval.evaluate()')

                eval.accumulate()

                eval.summarize()

                stats[self.metrics.keys[-1]], stats[self.metrics.keys[-2]] = eval.stats[:2]  # update mAP50-95 and mAP50

            except Exception as e:

                self.logger.warning(f'pycocotools unable to run: {e}')

        return stats
```

The rest of the evaluation is kept the same. So the usual evaluation using COCO is completed and the JSON is loaded to perform evaluation using the COCO evaluator. As for YOLO evaluation, I changed nothing and used the default settings i.e. confidence threshold of 0.001 and iou threshold of 0.7.

Below is an example results of the evaluations:

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/42833490/234709615-e95d6701-ac74-46ce-ace3-15c75c780a90.png)

**Comment by glenn-jocher** [comment]
Hello @salwaalkhatib, thank you for training with YOLOv8!

Based on the information you provided, the difference in mAP50-95 between the COCO and YOLOv8 evaluators could be due to several reasons. The COCO evaluator is performed using external evaluation metrics and the `pycocotools` library, while the YOLOv8 evaluation is performed using internal evaluation metrics. Moreover, different evaluation scripts have different parameter settings that could affect the evaluation performance in different ways.

To further investigate the evaluation results, it could be helpful to provide more information such as the evaluation metrics used, the parameters set in the evaluation scripts, and example images and annotations.

Please let me know if there is anything else I can assist you with.

**Comment by Laughing-q** [comment]
@salwaalkhatib hi, I think probably your case is related to `class_map`, this `class_map` is hardcoded for COCOdataset which map your class id to another index.
[https://github.com/ultralytics/ultralytics/blob/243fc4b1fe214ff6c27759dad51c37809db8f7f8/ultralytics/yolo/v8/detect/val.py#L48](https://github.com/ultralytics/ultralytics/blob/243fc4b1fe214ff6c27759dad51c37809db8f7f8/ultralytics/yolo/v8/detect/val.py#L48)
[https://github.com/ultralytics/ultralytics/blob/243fc4b1fe214ff6c27759dad51c37809db8f7f8/ultralytics/yolo/utils/ops.py#L56-L65](https://github.com/ultralytics/ultralytics/blob/243fc4b1fe214ff6c27759dad51c37809db8f7f8/ultralytics/yolo/utils/ops.py#L56-L65)
modify this line to:
```python
self.class_map = list(range(1000))
```
probably would solve your issue. :)

**Comment by uobinxiao** [comment]
same question, any solutions?
