### ISSUE TITLE
kpt_shape

### ISSUE THREAD

**Issue by Abecadarian** [ultralytics/ultralytics#2275]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I've been trying to train a model for pose detection on a custom dataset and run into the error:

 model = PoseModel(cfg, ch=3, nc=self.data['nc'], data_kpt_shape=self.data['kpt_shape'], verbose=verbose)
KeyError: 'kpt_shape'

I can't find anything in the documentation about this. What is 'kpt_shape'?

**Comment by pderrenger** [comment]
@Abecadarian your dataset needs a kpt_shape field describing the number and dimensions of your keypoints. See coco8-pose.yaml as an example:
https://github.com/ultralytics/ultralytics/blob/0a36b83e7addd5e21438d32a614bbdf3f330e6d9/ultralytics/datasets/coco8-pose.yaml#L1-L25

**Comment by TekayaNidham** [comment]
@pderrenger Hi, currently getting this error.

my yaml: 
```python
kpt_shape: [2, 2]  # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)
flip_idx: [1, 2]

# Classes
names:
  0: cotation
```
an annotation sample:
```
0 0.131077 0.896214 2.25169e-05 0.164858 0.131088 0.813785 2 0.131066 0.978642 2
```
Skeleton template:

![image](https://github.com/ultralytics/ultralytics/assets/62834628/b5c9eec8-ee30-4c36-bd8c-658a19fadf5b)

**Comment by glenn-jocher** [comment]
@TekayaNidham your annotations are incorrect. If you have 2 dims then your kpts are xy, xy but you have xy 2, xy 2, with is 3 dimensions. See https://docs.ultralytics.com/datasets/pose/

**Comment by glenn-jocher** [comment]
@TekayaNidham, I recommend that you label manually or use a tool such as labelme to export your annotations as coco keypoints format as this avoids the complications that CVAT introduced to your annotations. Also, be sure to verify your annotations before running the converter script to avoid possible issues during training.

**Comment by ryouchinsa** [comment]
Using the JSON2YOLO script, you can convert the COCO keypoints format to YOLOv8 pose format.
https://github.com/ultralytics/JSON2YOLO/issues/45

**Comment by glenn-jocher** [comment]
@ryouchinsa hi there, 
Yes, the JSON2YOLO script can be used to convert your annotations from COCO keypoints format to YOLOv8 pose format. You will need to modify the  `pose.py` and `config.yaml` files to match your custom dataset. `pose.py` is the model definition file that describes your model architecture. `config.yaml` specifies the dataset, model, and training hyperparameters. Once you have specified these correctly, you can then run the `train.py` script to train your model. 

Hope this helps.

**Comment by YSA-github** [comment]
@glenn-jocher 
Hello! If I don't have a keypoint and just use a rectangular box, how do I assign a value to my kpt_shape？
