### ISSUE TITLE
How to cashe image on traning

### ISSUE THREAD

**Issue by totoadel** [ultralytics/ultralytics#228]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to cashe image on traning ?

**Comment by Laughing-q** [comment]
@totoadel try `cache=True` is you want to cache images in memory, or you can try `cache=disk` and it'll cache images in disk.

**Comment by totoadel** [comment]
@Laughing-q thank you
