### ISSUE TITLE
What's the difference between B and P?

### ISSUE THREAD

**Issue by TommyZihao** [ultralytics/ultralytics#2281]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

<img width="745" alt="image" src="https://user-images.githubusercontent.com/36354458/234778087-b2be19e4-7a53-4ed2-a0b0-dbc595987836.png">

What's the difference between B and P?
And how to calculate them?

**Comment by pderrenger** [comment]
@TommyZihao B is for Box mAP and P is for Pose mAP.

**Comment by glenn-jocher** [comment]
@TommyZihao in YOLOv8, B refers to Box mAP and P refers to Pose mAP. Box mAP represents how well the model can detect and locate objects in an image. Pose mAP represents how accurately the model can detect and determine the pose or orientation of an object in an image. The calculation for both metrics follows the same general approach as other mAP metrics, where precision and recall are calculated based on a set of ground truth and predicted labels, and then averaged across multiple thresholds to obtain an overall score.
