### ISSUE TITLE
dataset annotation

### ISSUE THREAD

**Issue by vasundharalahankar** [ultralytics/ultralytics#2282]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

suggest any annotation tool for custom human keypoint annotation which return annotation points location in txt format and each point returns three values what are these three values if any annotation tool is not oresent then please provide some alternativate way for data annotation

**Comment by glenn-jocher** [comment]
@vasundharalahankar there are a variety of dataset annotation tools available. Roboflow make things pretty easy, you could start there.

**Comment by ryouchinsa** [comment]
As an open source tool, you can label keypoints using [COCO Annotator](https://github.com/jsbroks/coco-annotator) and export in the COCO keypoints format.

Using the JSON2YOLO script, you can convert the COCO keypoints format to YOLOv8 pose format.
https://github.com/ultralytics/JSON2YOLO/issues/45

**Comment by glenn-jocher** [comment]
@ryouchinsa thank you for your question! As an option for annotating your keypoints in YOLOv8, I recommend using the open-source COCO Annotator and exporting your annotations in COCO keypoints format. From there, you can use the JSON2YOLO script to convert your annotations to the YOLOv8 pose format. Please refer to the official YOLOv8 documentation and the JSON2YOLO repo for more details on this process. I hope this helps, and please let me know if you have any further questions!
