### ISSUE TITLE
GPU_mem shows 0G while training using coco128 []

### ISSUE THREAD

**Issue by A1exan10er** [ultralytics/ultralytics#2285]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello ultralytics,
thank you for providing the quick start tutorial, it helps implement the project. 
But after I finished every installation step and started training, using the demo CLI command 

- yolo detect train data=coco128.yaml model=yolov8n.yaml epochs=100 imgsz=640

The outputs in terminal are a little weird.
![GPU](https://user-images.githubusercontent.com/49768349/234831656-bb3819b1-fc61-4732-b98c-6ba52b8626d7.png)
In the screenshot GPU_mem keeps showing 0 while using nvidia-smi I can see there's a little usage of GPU, showing in this screenshot.
![nvidia](https://user-images.githubusercontent.com/49768349/234832174-96102030-9ab2-4816-b7b7-a77e5c706750.png)

Could you please tell me is this normal? I thought using GPU training means using more memory than the current 0G. 
If not, could you please tell me where the problem could be? I followed the installation guide of CUDA 11.8, cuDNN 8.9.0, PyTorch 2.0.0 and its relatives and verified them all as well, so the installation should not be the cause. 

Look forward to your response.
Thanks in advance!

**Comment by AyushExel** [comment]
You might want to check if torch can access cuda.
```
import torch
print(torch.cuda.is_available())
```
this snippet should print true.
You can try to pass device=0 manually, although if available device 0 GPU should automatically be used for training.

**Comment by A1exan10er** [comment]
> You might want to check if torch can access cuda.
> 
> ```
> import torch
> print(torch.cuda.is_available())
> ```
> 
> this snippet should print true. You can try to pass device=0 manually, although if available device 0 GPU should automatically be used for training.

No, the output is FALSE.
I guess this means GPU was not used by PyTorch.

I checked the environment variable $PATH, and it didn't show the path of CUDA. I guess this could be the reason of not using GPU. 
It's weird that the CUDA path disappeared because directly after CUDA installation I added it and checked it was in $PATH. After reboot it's gone.

I'll try to re-do the CUDA and cuDNN installation and fix this problem.

Thank you for your response. :)

**Comment by A1exan10er** [comment]
Problem solved, thank you very much! :) @AyushExel 
![True](https://user-images.githubusercontent.com/49768349/234877227-552ad08d-13d8-4262-bff1-880c450814e9.png)
![GPU_true](https://user-images.githubusercontent.com/49768349/234877249-2a12a481-6c85-4311-9c0d-3d0758e80744.png)
