### ISSUE TITLE
Run YOLOv8 inference on the frame, how to take out the result?

### ISSUE THREAD

**Issue by kyoko9000** [ultralytics/ultralytics#2288]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

# when i run code like this:

import cv2
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('yolov8n.pt')

# Open the video file
cap = cv2.VideoCapture("video1.mp4")

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 inference on the frame
        results = model(frame)

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Display the annotated frame
        cv2.imshow("YOLOv8 Inference", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break

        for result in results:
            boxes = result[0].boxes.numpy()  # Boxes object for bbox outputs
            for box in boxes:  # there could be more than one detection
                print("class", box.cls)
                print("xyxy", box.xyxy)
                print("conf", box.conf)

    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()

#it run in the short time and show error like this:

0: 384x640 1 car, 200.9ms
Speed: 1.0ms preprocess, 200.9ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)
class [          2]
xyxy [[      655.3      2.1034      707.62      34.452]]
conf [    0.32724]

0: 384x640 (no detections), 160.9ms
Speed: 2.0ms preprocess, 160.9ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)
Traceback (most recent call last):
  File "D:\9. python project\75. yolov8 pyqt5\direct_yolov8.py", line 30, in <module>
    boxes = result[0].boxes.numpy()  # Boxes object for bbox outputs
  File "D:\9. python project\75. yolov8 pyqt5\venv\lib\site-packages\ultralytics\yolo\engine\results.py", line 104, in __getitem__
    setattr(r, k, getattr(self, k)[idx])
  File "D:\9. python project\75. yolov8 pyqt5\venv\lib\site-packages\ultralytics\yolo\engine\results.py", line 57, in __getitem__
    return self.__class__(self.data[idx], self.orig_shape)
IndexError: index 0 is out of bounds for dimension 0 with size 0

Process finished with exit code 1

# if i don't use this code:
for result in results:
            boxes = result[0].boxes.numpy()  # Boxes object for bbox outputs
            for box in boxes:  # there could be more than one detection
                print("class", box.cls)
                print("xyxy", box.xyxy)
                print("conf", box.conf)
# it run normal
=> so how can i take out of result in this case if i want to use this code or some things like that?

**Comment by glenn-jocher** [comment]
@kyoko9000 it looks like the issue occurs when you try to access `result[0]` in the for loop. This error is likely due to no detection being made by YOLOv8 in the current frame. To avoid this error, you can add a simple conditional statement before the for loop to check if a detection has been made by YOLOv8 in the current frame. If no detections are found, you can skip the loop using the `continue` statement. This will allow you to continue processing the next frame without encountering the index error.

**Comment by waleedZaghloul** [comment]
use this instead u forgot to add the if statement to check if the list is empty(nothing is detected):
`
results = model(frame)
boxes = results[0].boxes.xyxy.tolist()
if results[0].boxes.id is None:
    for i, box in enumerate(boxes):
        x_min, y_min, x_max, y_max = box
        car_width = x_max - x_min
        car_hight = y_max - y_min
        conf = results[0].boxes.conf[i]
`
