### ISSUE TITLE
Disable callbacks

### ISSUE THREAD

**Issue by edublanco** [ultralytics/ultralytics#2290]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I saw that you have recently added a way to disable callbacks (thank you very much), can you provide an example of how to do it in python i.e. disable mlflow callbacks.

**Comment by AyushExel** [comment]
@glenn-jocher there's a PR for something similar. I've tagged you there
