### ISSUE TITLE
segmentation model look so blurry?

### ISSUE THREAD

**Issue by GalSang17** [ultralytics/ultralytics#2299]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Why does the segmentation model look so blurry? This is the case whether using video streams or .mp4 files. The command I use is as follows: 
model = YOLO('ultralytics/yolo/v8/weights/yolov8l-seg.pt')
results = model.predict('ultralytics/assets/p1.mp4', save=True, show=True, imgsz=640, conf=0.5)

![image](https://user-images.githubusercontent.com/49866330/235033005-c7a8b409-fa9d-47cf-9440-df1027aab6f7.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@GalSang17 try adding `retina_masks=True` option.
hi, we designed to ways to draw masks, by default(without retina_masks) it draws faster but less accurate if the original resolution of image is high, and with `retain_masks=True` it'll draw masks that are more accurate and high quality but spend more plotting time.

**Comment by GalSang17** [comment]
> 

yeah, I try it! but an error display:
![image](https://user-images.githubusercontent.com/49866330/235040742-4eaf5a99-2abe-49ce-99c1-a568bf3da5b6.png)
command line like this:
model = YOLO('ultralytics/yolo/v8/weights/yolov8l-seg.pt')
results = model.predict('ultralytics/assets/p1.mp4', save=True, show=True, retain_masks=True, imgsz=640, conf=0.5)

**Comment by Laughing-q** [comment]
@GalSang17 oh I mistyped😂, it's `retina_masks` not `retain_masks`. :)

**Comment by GalSang17** [comment]
> @GalSang17 oh I mistyped😂, it's `retina_masks` not `retain_masks`. :)



> @GalSang17 oh I mistyped😂, it's `retina_masks` not `retain_masks`. :)

Yes, it works, but it seems that the graphics card usage will continue to increase until the graphics card is not enough and then report an error, my graphics card is 3090 24G，error like this:

![image](https://user-images.githubusercontent.com/49866330/235044749-4d84b5d9-20f0-4f6e-a6b5-e5b347c576e6.png)

**Comment by Laughing-q** [comment]
@GalSang17 recommend you to use `stream=True` to save memory when source is video or steam.
```python
for result in model.predict('ultralytics/assets/p1.mp4', save=True, show=True, retina_masks=True, imgsz=640, conf=0.5):
    pass
```
more details please refer to our docs.

**Comment by GalSang17** [comment]
> @GalSang17 recommend you to use `stream=True` to save memory when source is video or steam.
> 
> ```python
> for result in model.predict('ultralytics/assets/p1.mp4', save=True, show=True, retina_masks=True, imgsz=640, conf=0.5):
>     pass
> ```
> 
> more details please refer to our docs.

thank you, I will try it later!

**Comment by glenn-jocher** [comment]
@GalSang17 you're welcome! Feel free to let us know if you have any further questions. We're here to help.

**Comment by glenn-jocher** [comment]
You're welcome, @GalSang17! Using the `stream=True` option when the source is a video or stream, can help to save memory by reducing the number of frames loaded into memory at once. This can prevent GPU memory errors that may occur when the available memory is fully utilized, as you have experienced. 
In your case, you may consider refactoring your code to use a `for loop` to iterate through the individual frames of the video and process them one at a time using the `model.predict()` method. This approach can allow you to process videos of any length without running out of GPU memory. Please refer to our documentation for more details on how to use this feature.
