### ISSUE TITLE
How to Use CLI to export dynamic onnx model?

### ISSUE THREAD

**Issue by wjj19950828** [ultralytics/ultralytics#230]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to Use CLI to export dynamic onnx model?

export static onnx model by

```shell
yolo task=detect mode=export model=yolov8s.pt format=onnx
```

How to export dynamic shape?

**Comment by wjj19950828** [comment]
export dynamic model by

```shell
yolo task=detect mode=export model=yolov8s.pt format=onnx dynamic=True
```

but name may have some question, [batch, Concatoutput0_dim_2, anchors]should be more appropriate？
![image](https://user-images.githubusercontent.com/19977378/211737484-164d50a1-e5c0-4051-8b43-d0930565007e.png)

**Comment by pderrenger** [comment]
@wjj19950828 to export a dynamic ONNX model using the CLI, you can run the following command:

```shell
yolo task=detect mode=export model=yolov8s.pt format=onnx dynamic=True
```

Regarding the naming of the dynamic output dimensions, you mentioned that [batch, Concatoutput0_dim_2, anchors] may be more appropriate. This is a customization that is often done based on the specific requirements of your project or framework. You can adjust these names as needed for your use case.

If you need further assistance with the dynamic model export or have any other questions, feel free to ask!
