### ISSUE TITLE
Can we add cpu_per_trial to model.tune()

### ISSUE THREAD

**Issue by saad-palapa** [ultralytics/ultralytics#2301]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I'm running a hypertuning job and it is hanging because there are two trials that are running in parallel.

This is because my cpu count is 16 and [model.tune is hard-coded to 8](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/engine/model.py#L445) which is causing two jobs to run at once. Check out [raytune's documentation](https://docs.ray.io/en/latest/tune/tutorials/tune-resources.html) to find out why.

For `model.tune()`, can we add `cpu_per_trial` as an argument to fix my issue.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @saad-palapa, 

Thank you for bringing this to our attention. We appreciate your suggestion and understand your issue.

We will review your feedback and assess the potential impact and implications of adding `cpu_per_trial` as a new argument to `model.tune()`. 

In the meantime, to work around the issue, we suggest you reduce the `n_calls` argument in `model.hypertune()` to match the value of `cpu_per_trial`, which will limit the number of parallel jobs to one.

Thank you for your understanding and continued usage of YOLOv8.

**Comment by mattiasmar** [comment]
@glenn-jocher  What is recommended way to limit HW resources when calling `model.tune`?
Could I send a dictionary like 
`resources_per_trial = {"cpu": 6, "gpu": 0.15}`
to the tuner?

**Comment by glenn-jocher** [comment]
Hi @mattiasmar,

When using `model.tune()`, the recommended way to limit hardware resources depends on whether you're using Ray Tune integration:

If using Ray Tune (`use_ray=True`), you can control GPU allocation with the `gpu_per_trial` parameter:

```python
model.tune(
    data="coco8.yaml", 
    use_ray=True,
    gpu_per_trial=0.15,  # Allocate 15% of a GPU per trial
    iterations=10
)
```

For CPU control, as @saad-palapa pointed out, there's currently no direct `cpu_per_trial` parameter - this would be a useful addition to implement. The current implementation uses a fixed value for CPU allocation per trial.

As a potential workaround, you could modify the system environment to limit available resources before running Ray Tune, but directly passing resources like your suggested dictionary isn't currently supported in the API.
