### ISSUE TITLE
my data.yaml is not a valid yolo argument

### ISSUE THREAD

**Issue by LonewolfASIF** [ultralytics/ultralytics#2302]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

!yolo task=detect mode=train model=yolov8s.pt data={dataset.location}/data.yaml epochs=25 imgsz=800 plots=True
![obj](https://user-images.githubusercontent.com/103584439/235056082-30d188e6-eabc-4f96-af20-c6f0d3575f04.png)

**Comment by Laughing-q** [comment]
@LonewolfASIF looks like you are using window system, I don't really use window but probably using `data={dataset.location}\data.yaml` instead of `data={dataset.location}/data.yaml`?

**Comment by Janaud14** [comment]
same problem for me

**Comment by glenn-jocher** [comment]
Hi @Janaud14, thank you for reporting this issue. Could you please elaborate on the problem you are encountering in more detail? This will help us better understand the issue and provide you with the appropriate solution.
