### ISSUE TITLE
Multimodal feature for document intelligence

### ISSUE THREAD

**Issue by shameem198** [ultralytics/ultralytics#2305]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Is it possible to combine text features in yolov8 object detection? any thoughts?

### Use case

This feature can improve document intelligence to another level.

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Not right now but with the addition of transformer-based models, this should be possible.
