### ISSUE TITLE
how to use yolov8-seg.yaml as yolov8x-seg.yaml?

### ISSUE THREAD

**Issue by hujunyao** [ultralytics/ultralytics#2307]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to train image in big size  (1280), I read doc that it will use yolov8x-seg.yaml . I search the site , only fond https://github.com/ultralytics/ultralytics/blob/main/ultralytics/models/v8/yolov8-seg.yaml file.   
in the yolov8-seg.yaml file, it writes:
scales: # model compound scaling constants, i.e. 'model=yolov8n-seg.yaml' will call yolov8-seg.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]
  s: [0.33, 0.50, 1024]
  m: [0.67, 0.75, 768]
  l: [1.00, 1.00, 512]
  x: [1.00, 1.25, 512]

does this mean model=yolov8x-seg.yaml can use it? 
but How can I change default nc=80 to my own nc=5?
any examples will appreciate。

**Comment by Laughing-q** [comment]
@hujunyao sure you can use `model=yolov8x-seg.yaml` and also you don't have to manually modify `nc`, it'll be updated automatically according to your data.yaml. you can see our example data yaml like [coco128.yaml](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/datasets/coco128.yaml).
