### ISSUE TITLE
How to use visualize argument to show feature map when do prediction

### ISSUE THREAD

**Issue by TommyZihao** [ultralytics/ultralytics#2309]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/36354458/235124322-7fd6e345-acfa-4267-9c29-694e9137177a.png">

**Comment by TommyZihao** [comment]
@Laughing-q @glenn-jocher

**Comment by Laughing-q** [comment]
@TommyZihao I think we missed this while we migrate features from v5 repo to here. I've added it in #2306 and also fixed the error. It'll be merged later today. Thanks for your reporting! 
After the PR merged, it should work as expect.
```bash
yolo detect predict visualize
```
