### ISSUE TITLE
Save the detected annotations file to the runs file

### ISSUE THREAD

**Issue by HarishGuragol** [ultralytics/ultralytics#231]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to save the detected annotations to the file, can u please let me know what changes should be done to the  command?

`!yolo task=detect mode=val model={HOME}/runs/detect/train/weights/best.pt data={dataset.location}/data.yaml`

**Comment by Laughing-q** [comment]
@HarishGuragol add `save_txt=True` then it should work.

**Comment by HarishGuragol** [comment]
Thanks for the update
