### ISSUE TITLE
Statisque of processing 

### ISSUE THREAD

**Issue by storm12t48** [ultralytics/ultralytics#2312]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello 
I just have a question how to retrieve the processing times per image that are displayed in the terminal when running a program use yolov8?

**Comment by jpl-c** [comment]
Hi @storm12t48 

I think you are looking to access the `speed` attribute of the `Results`.
See the code to the `Results` object [here](https://github.com/ultralytics/ultralytics/blob/243fc4b1fe214ff6c27759dad51c37809db8f7f8/ultralytics/yolo/engine/results.py#L60)
You can use a code like this to access it : 
```python
model = YOLO('weights/best.pt')
predictions = model(image_path, save_txt=None)
speed = predictions[0].speed
print(f"speed is {speed}")
```

**Comment by glenn-jocher** [comment]
Hello @storm12t48,

To access the processing times per image, you can retrieve the `speed` attribute of the `Results` object. The `speed` attribute is part of the `Results` class, which is returned by the `YOLO` model's `predict` method. Here is an example of how to access and print the speed attribute:

```python
from ultralytics.yolo import YOLO

model = YOLO('weights/best.pt')
image_path = 'path/to/image.jpg'
results = model(image_path)

speed = results.speed
print(f"Image processing time: {speed} seconds")
```

Please let me know if you have any further questions or require additional information.

Best regards.

**Comment by storm12t48** [comment]
thank you for such a quick response
Now I have another can we embed its speed fps information etc. on the FINAL video not the streaming one (ex: cv2.putText: s) but the one that comes out with the save=True option

**Comment by glenn-jocher** [comment]
Hello @storm12t48,

Yes, you can embed the processing metrics such as speed and FPS into the final video output that is saved using the `save` option in YOLOv8. 

To do this, you can use OpenCV's `cv2.putText()` function to annotate the video with the processing metrics. The `cv2.putText()` function takes in several parameters, including the frame to draw the text on, the text string to display, the position of the text on the frame, and other options such as the font face and size. 

You can extract the processing metrics directly from the YOLOv8 `Results` object that is returned by the `predict` method, and then use these values to display the metrics on each frame of the video. Once you have added the text annotations, you can use OpenCV's `cv2.VideoWriter` object to save the annotated video to disk.

I hope this information helps. Please let me know if you have any further questions or require additional information.

Best regards.

**Comment by storm12t48** [comment]
> Yes, you can embed the processing metrics such as speed and FPS into the final video output that is saved using the `save` option in YOLOv8.

Hello

Thank you for your answer but I did not see any option in the doc which allows to insert the information on the video directly

for the other method i will try it
I'll get back to you

**Comment by glenn-jocher** [comment]
@storm12t48 hello,

Thank you for your reply.

To embed the processing metrics such as speed and FPS into the final video output using the `save` option in YOLOv8, you can use OpenCV's `cv2.putText()` function to overlay the information on each frame of the video. 

First, extract the processing metrics such as speed and FPS directly from the YOLOv8 `Results` object returned by the `predict` method. Then, use these values to create text strings that can be passed to `cv2.putText()` to overlay the text onto each frame of the output video. 

Finally, once the text has been added to each frame, use OpenCV's `cv2.VideoWriter` object to save the annotated video to disk.

Please feel free to ask any additional questions you may have.

Best regards.

**Comment by storm12t48** [comment]
I think everything is clear thank you very much

**Comment by glenn-jocher** [comment]
Hello @storm12t48,

You're welcome, glad to be of help. If you have any further questions or require additional information, please don't hesitate to reach out.

Best regards.
