### ISSUE TITLE
Errors in tutorial.ipynb when using in Colab

### ISSUE THREAD

**Issue by HoLue** [ultralytics/ultralytics#232]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

I tried the tutorial.ipynb and got errors.

I started just with the colab link on the main page (https://github.com/ultralytics/ultralytics)
![grafik](https://user-images.githubusercontent.com/55573836/211741137-6fa77e08-22c4-4424-948f-766c240633f1.png)
(BTW, at least essentially the same (I had some different special characters in output))

The tutorial works until "4. Export" but from "5. Python Usage" there are errors. (I tried to correct path of yaml but I couldn't make it work.)

The tutorial.ipynb with the errors can be seen at the YOLOv8_Tutorial_Errors.ipynb in detail
[YOLOv8_Tutorial_Errors.zip](https://github.com/ultralytics/ultralytics/files/10389655/YOLOv8_Tutorial_Errors.zip)

Here a screenshots for fast "look at".

"5. Python Usage"
![grafik](https://user-images.githubusercontent.com/55573836/211742188-bf8fffcf-e7ae-48d2-95d5-29653f993db3.png)

"6. Tasks" - Detection
![grafik](https://user-images.githubusercontent.com/55573836/211742489-65727e00-63ac-426c-ab54-3e0e198401dd.png)

"6. Tasks" - ## 2. Segmentation
![grafik](https://user-images.githubusercontent.com/55573836/211742682-850ee80c-9bc0-490c-b5fa-2ba2a4b2a136.png)

"6. Tasks" - Classification
![grafik](https://user-images.githubusercontent.com/55573836/211742725-37728251-e9fa-4ed8-8190-8287079618ae.png)

To mention once more, all can be seen in YOLOv8_Tutorial_Errors.ipynb  (in the zip).

It would be great when you could correct the tutorial that it runs in colab.

### Environment

colab default

### Minimal Reproducible Example

https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@HoLue thanks! we'll look into this. After installing the package, have you tried restarting the runtime before running the python usage?

**Comment by HoLue** [comment]
@

> @HoLue thanks! we'll look into this. After installing the package, have you tried restarting the runtime before running the python usage?

No, I didn't - actually I don't know, how. When I restart runtime everything is gone and I have to reinstall everything which is the same once more... Maybe I'm doing something wrong there....

**Comment by AyushExel** [comment]
@HoLue no no..You don't have to reset.Just restart.
But I just checked again and it works without restarting.. There might be some other issue. Is it still happening? Can you try again? Just run the first setup cell and the detection python code. Thanks!
<img width="1073" alt="Screenshot 2023-01-11 at 2 26 21 PM" src="https://user-images.githubusercontent.com/15766192/211761810-1173ded9-528b-4027-a288-c5b26860ec1a.png">

**Comment by HoLue** [comment]
> @HoLue no no..You don't have to reset.Just restart. But I just checked again and it works without restarting.. There might be some other issue. Is it still happening? Can you try again? Just run the first setup cell and the detection python code. Thanks! <img alt="Screenshot 2023-01-11 at 2 26 21 PM" width="1073" src="https://user-images.githubusercontent.com/15766192/211761810-1173ded9-528b-4027-a288-c5b26860ec1a.png">

Ok, this works!
I did

1. Setup (cell with # Pip install method (recommended) ...)
2. 6. Tasks -> 1. Detection (cell with # Load a pretraind YOLOv8n detection model, train it on COCO128 for 3 epochs and predict an image with it ...)
The next ones (segmentation and classification) work, too.

So somewhere are path settings wrong on the way? I think it would be good to repair it - when the tutorial does not work it' not good....

**Comment by AyushExel** [comment]
@HoLue okay thanks for the feedback!
I didn't quite get which part is broken. Are you still seeing a cell that is throwing errors?

**Comment by HoLue** [comment]
> @HoLue okay thanks for the feedback! I didn't quite get which part is broken. Are you still seeing a cell that is throwing errors?

When I run the tutorial.ipynb from the beginning, the first error occurs in "5. Python Usage" as in my first description:
![grafik](https://user-images.githubusercontent.com/55573836/211780918-6e788856-fbc8-4a5e-88a1-2cfaf7f5a964.png)

**Comment by AyushExel** [comment]
@HoLue okay I'll take a look today

**Comment by puneetjindal** [comment]
@AyushExel Even i am facing the same issue while running the colab tutorial!

**Comment by AyushExel** [comment]
@puneetjindal can you try only running the first cell for setup? the one that sys "recommended" and then skip the next cell that clones the repo. I'm not sure if that's causing problems but it seemed like that from what @HoLue described. 
Of course factory reset the colab first :)

**Comment by puneetjindal** [comment]
Agreed with you @AyushExel 

Following cell is culprit. All i need to do is comment it and everything else ran smoothly for me!

![image](https://user-images.githubusercontent.com/2950341/211807284-588567cd-ef96-4668-9234-076ac36479fd.png)

**Comment by AyushExel** [comment]
Okay thanks this might be colab specific problem or  a bug in main branch @glenn-jocher
