### ISSUE TITLE
Can we train ImageNet dataset for Object detection and how?

### ISSUE THREAD

**Issue by TapendraBaduwal** [ultralytics/ultralytics#2320]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

If we set ImageNet.yaml results = model.train(data='ImageNet.yaml', epochs=3) and give path of dataset in ImageNet.yaml then its work ? Do we need to download ImageNet dataset in locally or ImageNet.yaml file automatically download the dataset?

**Comment by glenn-jocher** [comment]
@TapendraBaduwal hi there,

Setting `results = model.train(data='ImageNet.yaml', epochs=3)` in YOLOv8 will train the model using the dataset specified in the ImageNet.yaml file. However, you would need to download the dataset manually and provide the path to its directory in the ImageNet.yaml file for the training to work.

The ImageNet.yaml file does not automatically download the dataset.

Let me know if you have any further questions.

Best regards,
Glenn Jocher
