### ISSUE TITLE
Error: "metadata generation failed", can't install Ultralytics Module

### ISSUE THREAD

**Issue by ErfanSharifi** [ultralytics/ultralytics#2322]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to install Utralytics on raspberrypi model 4 with 4G RAM and with bullseye raspberryOS. when i want to install with below comand:

pip install ultralytics

i take below error. i tried this command too:

pyhton3 -m pip install ultralytics

but i take same error. i update pip,setuptools,wheel. how can i fix it.

`      ../../meson.build:63:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'],   ['g95']]
  The following exception(s) were encountered:
  Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
  Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
  Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
  Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
  Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
  Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
  Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
  Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
  Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
  Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
  Running `ifx --version` gave "[Errno 2] No such file or directory: 'ifx'"
  Running `ifx -V` gave "[Errno 2] No such file or directory: 'ifx'"
  Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
  Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"
  
  A full log can be found at /tmp/pip-install-vpm4le6w/scipy_fa8642477d2a4052aa580a87c2367cda/.mesonpy-wae33bni/build/meson-logs/meson-log.txt
  + meson setup --prefix=/usr /tmp/pip-install-vpm4le6w/scipy_fa8642477d2a4052aa580a87c2367cda /tmp/pip-install-vpm4le6w/scipy_fa8642477d2a4052aa580a87c2367cda/.mesonpy-wae33bni/build --native-file=/tmp/pip-install-vpm4le6w/scipy_fa8642477d2a4052aa580a87c2367cda/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
  [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by glenn-jocher** [comment]
@ErfanSharifi it seems that you are encountering a compilation error during the installation of the Scipy package, which is required by Ultralytics. Specifically, the compilation process could not find several Fortran compilers on your system. 

You could try installing these compilers in order to solve this error. However, please note that YOLOv8 has not been officially tested or optimized for Raspberry Pi, and so we cannot guarantee that it will work as expected on your system.

**Comment by ErfanSharifi** [comment]
Hi @glenn-jocher. 
This is true. Ultra lyrics does not work on raspberry pi. 🙏

**Comment by glenn-jocher** [comment]
Hello @ErfanSharifi, thank you for reaching out and bringing this to our attention. While YOLOv8 has not been officially tested or optimized for Raspberry Pi, some users have reported success in running Ultralytics on the Raspberry Pi platform. Unfortunately, as you indicated, others have had trouble with it. It's difficult to provide a definitive solution without further diagnostic information about the specific issue that you are encountering. Please note that YOLOv8 requires a Python environment with PyTorch>=1.7 installed, and that the installation of PyTorch can be challenging on certain systems. Additionally, Raspberry Pi systems may have resource constraints that can affect performance and memory usage. Nonetheless, we appreciate your interest in Ultralytics and will continue to evaluate the feasibility of supporting diverse hardware platforms in the future. Let us know if you have any further questions, and we'll do our best to assist you.
