### ISSUE TITLE
I did not found yolov8n.yaml file how can i get this file ? I got only  yolov8.yaml file but i need yolov8n.yaml file to set path on model = YOLO('path/yolov8n.yaml')

### ISSUE THREAD

**Issue by TapendraBaduwal** [ultralytics/ultralytics#2328]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to give path of yolov8n.yaml' file in below code... i need to  modify some training parameters such as learning rate (lr), batch size (batch-size), number of epochs (epochs), etc.

How to get yolov8n.yaml file ?

model = YOLO('path/yolov8n.yaml')  # build a new model from scratch

**Comment by glenn-jocher** [comment]
@TapendraBaduwal hello,

You can find the 'yolov8n.yaml' file in the 'models' folder of this repository. You can modify the training parameters by editing the values in the corresponding section of the YAML file.

Once the changes are made, save the file and provide the path of the modified 'yolov8n.yaml' file in the 'model' parameter of the YOLO constructor.

I hope this helps. Let me know if you have any further questions or issues.

Best, 
Glenn Jocher

**Comment by 0fine0** [comment]
Hi,

I also met this question. And after I read the yolov8.yaml, I found the yolov8n.yaml has been merged to yolov8.yaml.

and their comments said: 
# model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'

So, I think you just need to revise yolov8.yaml.

**Comment by glenn-jocher** [comment]
@0fine0 hello,

Thank you for reaching out. Regarding the 'yolov8n.yaml' file, it has been merged with 'yolov8.yaml' and you can find the scaling constants in the latter file. The comment in the YAML file explains that using 'model=yolov8n.yaml' will call 'yolov8.yaml' with the corresponding scaling factor 'n'.

Therefore, to modify the parameters for 'yolov8n', you can edit the corresponding values in 'yolov8.yaml' and call it using 'model=yolov8n.yaml'.

I hope this answers your question. Let me know if you have any further concerns or inquiries.

Best regards,
Glenn Jocher

**Comment by ovidedecroly** [comment]
> @TapendraBaduwal hello,
> 
> You can find the 'yolov8n.yaml' file in the 'models' folder of this repository. You can modify the training parameters by editing the values in the corresponding section of the YAML file.
> 
> Once the changes are made, save the file and provide the path of the modified 'yolov8n.yaml' file in the 'model' parameter of the YOLO constructor.
> 
> I hope this helps. Let me know if you have any further questions or issues.
> 
> Best, Glenn Jocher

How do I change the yolov8 model/architecture in yolov8 yaml like in yolov5? Thank You

**Comment by ovidedecroly** [comment]
> @0fine0 hello,
> 
> Thank you for reaching out. Regarding the 'yolov8n.yaml' file, it has been merged with 'yolov8.yaml' and you can find the scaling constants in the latter file. The comment in the YAML file explains that using 'model=yolov8n.yaml' will call 'yolov8.yaml' with the corresponding scaling factor 'n'.
> 
> Therefore, to modify the parameters for 'yolov8n', you can edit the corresponding values in 'yolov8.yaml' and call it using 'model=yolov8n.yaml'.
> 
> I hope this answers your question. Let me know if you have any further concerns or inquiries.
> 
> Best regards, Glenn Jocher

@glenn-jocher 
How do I change the yolov8 model/architecture in yolov8 yaml like in yolov5? Thank You

**Comment by glenn-jocher** [comment]
@ovidedecroly hello,

Thank you for your query.

To change the YOLOv8 model architecture using the 'yolov8.yaml' file, you can follow a similar process to what you used with yolov5. Edit the 'yolov8.yaml' file by changing the parameters defined there. The yaml file contains sections for backbone, head and neck with various predefined architecture settings. You can adjust these settings according to your needs, for example, you can change the number of layers, layer types and layer parameters, etc.

Remember to save your changes before running your model. Use the 'model=yolov8.yaml' to call the model with your custom settings.

Let me know if you need more clarification or have any further questions.

Best Regards,
Glenn Jocher

**Comment by SamedSen** [comment]
@glenn-jocher  Hi, 

How can i configure yolov8n.yaml in colab. I dont want to do it from repos. Can i edit the file in colab? Is there a way to do it? 

Thank you already.

**Comment by glenn-jocher** [comment]
@SamedSen hello,

Yes, you can configure the 'yolov8n.yaml' in Colab. Once you import the YOLOv8 repository into your Colab environment, you'll find the .yaml file under the 'models' directory. You can directly open and edit this file in Colab using its built-in text editor.

Simply find the 'yolov8n.yaml' (or 'yolov8.yaml' if 'n' is a compound scaling constant) file in the file explorer on the left side of your Colab notebook, right-click the file, and select "Open in a new tab" to edit it. Remember to save your changes before running your model.

This will allow you to adjust the training parameters locally in your Colab environment without having to make any changes to the repository itself. 

Let me know if you have any other questions! 

Best,
Glenn Jocher

**Comment by ovidedecroly** [comment]
@glenn-jocher <https://github.com/glenn-jocher> Hi,

Glenn, Hello

I've changed some convolution and block types in conv.py and block.py. For
example, I change the Conv type to Convmodified and C2f to C2fmodified. I
have also set the yaml. I also changed C2f by adding an attention mechanism
block to it and changing the bottleneck. My question is where should I
adjust the shape of the input and output size tensors? Thanks you
my error is like this:


                    from n params module arguments
   0 -1 1 1856 ultralytics.nn.modules.conv.MConv [3, 64, 3, 2]
   1 -1 1 73984 ultralytics.nn.modules.conv.MConv[64, 128, 3, 2]
   2 -1 1 159808 ultralytics.nn.modules.block.MC2f [128]
   3 -1 1 295424 ultralytics.nn.modules.conv.MConv[128, 256, 3, 2]
   4 -1 1 635008 ultralytics.nn.modules.block.MC2f [256]
   5 -1 1 1180672 ultralytics.nn.modules.conv.MConv [256, 512, 3, 2]
   6 -1 1 2531584 ultralytics.nn.modules.block.MC2f [512]
   7 -1 1 4720640 ultralytics.nn.modules.conv.MConv [512, 1024, 3, 2]
   8 -1 1 10109440 ultralytics.nn.modules.block.MC2f [1024]
   9 -1 1 1050624 ultralytics.nn.modules.block.MSPPF [1024]
  10 -1 1 0 torch.nn.modules.upsampling.Upsample [None, 2, 'nearest']
  11 [-1, 6] 1 0 ultralytics.nn.modules.conv.Concat [1]
  12 -1 1 525312 ultralytics.nn.modules.conv.MConv[1024, 512, 1, 1]
  13 -1 1 2531584 ultralytics.nn.modules.block.MC2f [512]
  14 -1 1 0 torch.nn.modules.upsampling.Upsample [None, 2, 'nearest']
  15 [-1, 4] 1 0 ultralytics.nn.modules.conv.Concat [1]
  16 -1 1 131584 ultralytics.nn.modules.conv.MConv[512, 256, 1, 1]
  17 -1 1 635008 ultralytics.nn.modules.block.MC2f [256]
  18 -1 1 1180672 ultralytics.nn.modules.conv.MConv[256, 512, 3, 2]
  19 [-1, 12] 1 0 ultralytics.nn.modules.conv.Concat [1]
  20 -1 1 394240 ultralytics.nn.modules.conv.MConv[768, 512, 1, 1]
  21 -1 1 2531584 ultralytics.nn.modules.block.MC2f [512]
  22 -1 1 4720640 ultralytics.nn.modules.conv.MConv [512, 1024, 3, 2]
  23 [-1, 9] 1 0 ultralytics.nn.modules.conv.Concat [1]
  24 -1 1 2099200 ultralytics.nn.modules.conv.MConv[2048, 1024, 1, 1]
  25 -1 1 10109440 ultralytics.nn.modules.block.MC2f [1024]
  26 [15, 18, 21] 1 161104 ultralytics.nn.modules.head.Detect [20, [9, 9,
15]]
-------------------------------------------------- -------------------------
RuntimeError Traceback (most recent call last)
<ipython-input-4-2558d6878823> in <cell line: 4>()
       2 from ultralytics import YOLO
       3
----> 4 models = YOLO('yolov8s-seg.yaml')

11 frames
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py in
_conv_forward(self, input, weight, bias)
     457 weight, bias, self.stride,
     458 _pair(0), self.dilation, self.groups)
--> 459 return F.conv2d(input, weight, bias, self.stride,
     460 self.padding, self.dilation, self.groups)
     461

RuntimeError: Given groups=1, weight of size [512, 1024, 1, 1], expected
input[1, 5632, 16, 16] to have 1024 channels, but got 5632 channels instead

وَ السَّلاَمُ عَلَيْكُمْ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ
Best regards,

*Ovide Decroly Wisnu Ardhi, S.T., M.Eng*
Universitas Sebelas Maret
Jl. Ir. Sutami 36 A Kentingan Surakarta, 57126 Indonesia
Phone: +62-271-663450

Mobile: +6282220301004
Whatapps: +6282220301004
Website: http://ovide.id/

**Comment by glenn-jocher** [comment]
@ovidedecroly hello Ovide,

Considering the modifications you made to the convolution types in conv.py and block.py, you've encountered a RuntimeError indicating a mismatch between the number of channels expected and the number you actually have. 

The error message reads: "RuntimeError: Given groups=1, weight of size [512, 1024, 1, 1], expected input[1, 5632, 16, 16] to have 1024 channels, but got 5632 channels instead". 

The channel size in the error message comes from your modified convolutional block: 'ultralytics.nn.modules.conv.MConv[1024, 512, 1, 1]'. You might need to ensure that the output channel size of your attention mechanism block and the input channel size of the convolutional layer which follows, are compatible.

You should adjust the input and output tensor sizes in the forward method of your custom Conv classes and the attention mechanism block to ensure compatible dimensionality across all inputs and outputs. You might need to make changes to adopt the correct tensor shape based on your modified Convs and the attention mechanism block you introduced.

Hope this information helps guide you towards the resolution of your problem.

Best Regards,

Glenn Jocher

**Comment by jahid-coder** [comment]
I did find yolov8s.yaml file. Anyone gives me the link from where i can download this file.

**Comment by glenn-jocher** [comment]
@jahid-coder hello,

You can find the 'yolov8s.yaml' file inside the 'models' directory within the YOLOv8 GitHub repository. It should be available in the repository once you clone or download it in your local system. If it isn't present, it may be possible that it was renamed or merged with another file. Verify if a similar file is accessible in the 'models' directory.

Best regards,
Glenn Jocher

**Comment by ZhaoChunjiang** [comment]
I can't find the yolov8s.yaml file either. In fact, I didn't find any yaml file in the 'models' directory.

**Comment by jahid-coder** [comment]
I can't find the yolov8s.yaml file yet. where do i get this file . 
![image](https://github.com/ultralytics/ultralytics/assets/73584067/82161a6d-9102-4143-ac41-ca309b97a1d5)

**Comment by glenn-jocher** [comment]
@ZhaoChunjiang hello,

I apologize for the confusion. It seems like there may have been a change or renaming in the repository. The 'yolov8s.yaml' file typically resides in the 'models' directory within the YOLOv8 GitHub repository. If it's not there, it's possible that its name has been changed or the file might have been moved to another directory. Please go through the repository once again thoroughly.  If you're still unable to locate the file, it would be best to raise an issue on the GitHub repository to bring this to the attention of the contributors. They might provide the next course of action or clarify if this file has been renamed or replaced.

Best Regards,
Glenn Jocher

**Comment by jahid-coder** [comment]
@glenn-jocher
I can't find the yolov8s.yaml file yet. where do i get this file .
![image](https://github.com/ultralytics/ultralytics/assets/73584067/06672036-7767-46c3-a72f-a0ce7699e44f)

**Comment by glenn-jocher** [comment]
Hello @jahid-coder,
Apologies for the confusion. There might have been a change or renaming in the repository. The 'yolov8s.yaml' file you are looking for traditionally resides in the 'models' directory within the YOLOv8 GitHub repository. If it's not there currently, it's possible that the file name has been changed or moved to a different directory.

By properly inspecting the repository, you should be able to find the configuration file or its equivalent under a new name. If you're still unable to locate the file, please feel free to raise a new issue detailing your problem. The developers and contributors of the repository can provide you with the most accurate information.

Thank you for your understanding,
Glenn Jocher

**Comment by glenn-jocher** [comment]
Hello @JeromePTI,

Yes, adapting the 'nc' (number of classes) parameter in the model's YAML file to match your specific use case is not only good practice, it's necessary for training a model on your dataset. When you have a dataset with 6 classes, you should set the 'nc' value to 6 to align the model's final layer outputs with the number of classes you wish to detect.

This change tailors the model configuration to your data and is one of the fundamental steps for training a custom model with YOLOv8. No other structural changes in the architecture are required for this adjustment, just ensure that your dataset is properly labeled and that the rest of the configurations are appropriate for your training setup.

**Comment by ccachard** [comment]
Hi @glenn-jocher ,
I see your answer to @JeromePTI and I was wondering if in the case of pretrained models for custom dataset we can only set the nc in the my_custom_data.yaml (in my case it would be like 10 classes) ? Because with `yolo detect train data=my_custom_data.yaml model=yolov8n.pt epochs=100 imgsz=640`, we do not have access to the nc variable of yolov8n.pt.

Thank you in advance for your reply

**Comment by glenn-jocher** [comment]
@ccachard hello,

When using a pretrained model like 'yolov8n.pt' for custom training with your dataset, setting the `nc` parameter in your custom dataset YAML file (e.g., 'my_custom_data.yaml') is indeed the correct approach. The model will adjust the final layer automatically to match the number of classes (`nc`) specified in your dataset configuration file when you initiate training.

For training from scratch or when fine-tuning a pretrained model, the process is similar. The `nc` value in your dataset YAML file is used to update the number of classes the model should expect. There's no need to manually modify the `nc` value within the model's YAML configuration since the model dynamically adapts to your dataset based on the dataset configuration provided during training.

In other words, the `nc` variable in your 'my_custom_data.yaml' effectively overwrites the `nc` variable in 'yolov8.yaml' or in the '.pt' checkpoint file during training. The training script takes care of this adaptation, so you only need to specify the correct number of classes once in your dataset YAML file.

**Comment by natbutter** [comment]
For simple people like me who also could not find this file:
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/models/v8/yolov8.yaml

**Comment by glenn-jocher** [comment]
@natbutter the file 'yolov8.yaml' should be available in the 'models' directory of the YOLOv8 GitHub repository. If the file is missing or you cannot locate it, please check for any updates in the file structure of the repository via the GitHub interface or clone the repository to search locally. If the issue persists, don't hesitate to raise it on GitHub, where the Ultralytics team can help you further.

**Comment by PozitronikTech** [comment]
If it weren't for you, I'd still be searching. Thank you. @natbutter 
Their documentation is terrible.
They wrote the same things over and over again.
If even the employee in the company **cannot** answer correctly...  And they repeat the same things like bots.

**Comment by alsozatch** [comment]
> If it weren't for you, I'd still be searching. Thank you. @natbutter Their documentation is terrible. They wrote the same things over and over again. If even the employee in the company **cannot** answer correctly... And they repeat the same things like bots.

It's cause most of glenn's comments in 2023 are chatgpt responses. There are multiple threads that make this painfully clear

**Comment by BNislam** [comment]
hello, I want to use the weights classes to balance my dataset to train a yolov8 model out of 12 I calculated the weights [0.02019275 0.09361391 0.11182256 0.09952436 0.01905868 0.06931413
 0.05859288 0.10397119 0.05381769 0.11471 0.06815406 0.18722781] my question is how can I use it???

thanks in advance
