### ISSUE TITLE
yolo: error: argument --cfg/-c: invalid choice: 'default.yaml' (choose from 'job', 'hydra', 'all')

### ISSUE THREAD

**Issue by jiyuwangbupt** [ultralytics/ultralytics#233]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

![image](https://user-images.githubusercontent.com/37127150/211743035-db661704-e3ef-46ee-92ca-581116f45035.png)
cfg error

### Environment

Ultralytics YOLOv8.0.3 🚀 Python-3.8.5 torch-1.11.0+cu102 CUDA:0 (Tesla P40, 8192MiB)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@jiyuwangbupt is you default.yaml file in the same working dir? If it is, can you try running `--config-name default.yaml` instead? Thanks!
