### ISSUE TITLE
WARNING Environment does not support cv2.imshow() or PIL Image.show()

### ISSUE THREAD

**Issue by yongjer** [ultralytics/ultralytics#2335]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

as title 

### Environment

docker env ultralytics/ultralytics:latest

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@yongjer hi! Thank you for your interest in YOLOv8. We are sorry but we couldn't understand the issue you are facing, could you please provide us with more details? Some helpful information would be the steps you have taken before the bug occurred or any error messages that you've received.  Additionally, if you can provide us with more context regarding the issue, we will be better able to help you. Please feel free to let us know if you have further questions or if you need any help. Thank you!

**Comment by yongjer** [comment]
![Screenshot from 2023-05-01 10-07-35](https://user-images.githubusercontent.com/54315206/235391480-e3ba602e-5b1e-428f-8cbd-668b118f8b7d.png)
so it can show the result correctly, but not able to show the image that my webcam is taking.
should I install opencv or PIL  on my host computer to make it works?

**Comment by pderrenger** [comment]
@yongjer It seems like you are encountering an issue with displaying images from your webcam. The error message you mentioned typically occurs when the environment does not support displaying images using `cv2.imshow()` or `PIL Image.show()`. 

To resolve this issue, you may need to install OpenCV (`opencv-python`) and/or PIL (`Pillow`) on your host computer, as these libraries are often used for displaying images. Once installed, you should be able to show the images captured by your webcam.

If you have any further questions or need assistance with the installation process, feel free to ask!
