### ISSUE TITLE
Issue trying to modify C2f layer

### ISSUE THREAD

**Issue by pinheiromelobruno** [ultralytics/ultralytics#2337]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm doing research on top of YOLOv8 and I need to create a modification on top of the C2f layer (which I'm provisionally calling C2f_new). For that I'm modifying yolov8.yaml changing the C2f variables for my new ones C2f_new. Also, I update the /content/ultralytics/ultralytics/nn/modules.py file to include my new C2f_new. Until yesterday it was working, but today when I try to run train, If I try to bruteforce the path, I get:

                    from n params module arguments
   0 -1 1 464 ultralytics.nn.modules.Conv [3, 16, 3, 2]
   1 -1 1 4672 ultralytics.nn.modules.Conv [16, 32, 3, 2]
Traceback (most recent call last):
   File "/usr/local/bin/yolo", line 8, in <module>
     sys.exit(entrypoint())
   File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/cfg/init.py", line 364, in entrypoint
     model = YOLO(model, task=task)
   File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/model.py", line 105, in init
     self._new(model, task)
   File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/model.py", line 138, in _new
     self.model = TASK_MAP[self.task][0](cfg_dict, verbose=verbose and RANK == -1) # build model
   File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 181, in init
     self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose) # model, savelist
   File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 467, in parse_model
     m = getattr(torch.nn, m[3:]) if 'nn.' in m else globals()[m] # get module
KeyError: 'C2f_new'

If I only indicate model=yolov8n.yaml during train it downloads yolov8.pt and ignore the yaml.

Does anyone know what can it be?

**Comment by pinheiromelobruno** [comment]
Apparently the training routine is ignoring any (models).yaml file, because in all attempts it displays the following message:

Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to yolov8n.pt...
100% 6.23M/6.23M [00:00<00:00, 365MB/s]

**Comment by glenn-jocher** [comment]
@pinheiromelobruno hello!

It appears that the training routine is ignoring your .yaml file because it is defaulting to downloading the YOLOv8 pretrained model (yolov8n.pt) instead. This can happen if there is any error or misconfiguration in your .yaml file.

Have you checked the syntax and correctness of your .yaml file? Also, make sure that you are providing the correct path for your modified /content/ultralytics/ultralytics/nn/modules.py file that includes your new C2f_new layer.

If the issue persists, feel free to ask for further assistance.

**Comment by pinheiromelobruno** [comment]
@glenn-jocher firstly thanks for your assistance.

I am still with problems and I think it's all ok with my modules.py archive.

Even when I try to call the yolov8n.yaml:
![image](https://user-images.githubusercontent.com/68548768/235387913-c8c5645e-45cd-461e-a2f8-6521b871d8de.png)

during the training it default to yolov8n.pt:
![image](https://user-images.githubusercontent.com/68548768/235388006-c415a8d0-37bf-408f-9c61-ea283a3c1a3f.png)

On the other hand, when I try to call model=yolov8-new1.yaml I get:
![image](https://user-images.githubusercontent.com/68548768/235388264-425e5955-cf8d-4fdf-b8b2-95419d1ee67b.png)

If I use the path (model=/content/ultralytics/ultralytics/models/v8/yolov8-new1.yaml) I get:
![image](https://user-images.githubusercontent.com/68548768/235388342-60f899d3-d7b2-4e41-8b7a-d5781e1a9123.png)

About the new modules.py I am just adding my new C2f classes to the archive:
![image](https://user-images.githubusercontent.com/68548768/235388527-976f590e-617f-4f11-bd29-dddadc564be9.png)

**Comment by glenn-jocher** [comment]
@pinheiromelobruno hello! Based on the error messages you provided, it seems that the training routine is defaulting to downloading the pretrained YOLOv8 model (yolov8n.pt) instead of using your modified .yaml file. This could be happening if there is any error or misconfiguration in your .yaml file.

It appears that you have checked your modules.py file and have successfully added your new C2f class. However, the error messages suggest that the issue may be related to your .yaml file. Please double-check the syntax and correctness of your .yaml file, and ensure that you are providing the correct path to it during training.

If you are still having problems, please let us know and we will do our best to assist you further.

**Comment by pinheiromelobruno** [comment]
@glenn-jocher I thoroughly checked the .yaml model file and its path. It seems to me that there is a problem when the network tries to use it. In terms of syntax the only thing I'm doing is replacing "C2f" with the new layer "C2f_new" in the backbone, so it doesn't seen that's this is the problem. Even if I don't create a new .yaml (using an previous existing), rewriting the C2f layers when the training routing loads the layers it does with C2f, not with C2f_new.

Another question, is it necessary to modify the tasks.py file as well (to include my C2f_new in the dictionaries)?

**Comment by glenn-jocher** [comment]
@pinheiromelobruno It's possible that the issue may be with the implementation of your new layer "C2f_new". Have you checked that this new layer is correctly implemented in your modules.py file and that it is compatible with YOLOv8? 

Regarding your question, it is not necessary to modify the tasks.py file to include your new layer "C2f_new" in the dictionaries. However, if you have modified the modules.py file and added your new layer, you will need to ensure that it is correctly referenced in your .yaml file. 

If the issue persists after verifying that the implementation of your new layer is correct and that your .yaml file references it correctly, feel free to ask for further assistance.

**Comment by glenn-jocher** [comment]
@pinheiromelobruno 

To modify the C2f layer in YOLOv8, you will need to update the modules.py file to implement your changes. It appears that you have already done this based on the screenshots you provided.

However, when you run the training routine using the default yolov8.yaml file, it appears that the changes you made to the C2f layer parameters are not being reflected in the network structure during training.

To ensure that your modifications to the C2f layer are reflected during training, you will need to make sure that your .yaml file references the updated parameters correctly. Specifically, you will need to ensure that the "filters" and "n" parameters in the C2f layer are updated to reflect your modifications.

If you have already updated the .yaml file and are still not seeing the changes reflected during training, please ensure that you are providing the correct path to your modified .yaml file during training. You may also want to check that your modifications to the C2f layer are in fact compatible with the YOLOv8 architecture.

I hope this helps, and please feel free to ask if you have any further questions.

**Comment by pinheiromelobruno** [comment]
Resolved. It worked when I included the new "C2f2" in /content/ultralytics/ultralytics/nn/tasks.py in all instances where C2f appears.

**Comment by glenn-jocher** [comment]
@pinheiromelobruno i'm glad to hear that you have resolved the issue with your modified C2f layer in YOLOv8. It appears that you needed to include the new "C2f2" layer in the tasks.py file in all instances where C2f appears, which allowed the training routine to properly recognize and use your modified layer.

In addition to modifying the modules.py file to implement your new layer, it is important to ensure that any references to the old layer are updated throughout the YOLOv8 codebase. In your case, updating the tasks.py file was necessary to properly utilize your modified C2f layer during training.

If you have any further questions or issues, please don't hesitate to ask.

**Comment by pinheiromelobruno** [comment]
> qual commit do yolov8 possui esse arquivo? reparei que não tem mais na versão atual

Aqui: ultralytics/models/v8

**Comment by glenn-jocher** [comment]
@Dieguinho5 the file you are looking for, modules.py, can be found in the ultralytics/models/v8 directory. Please note that this is based on the current version of YOLOv8 at the time of writing, and the location of files may vary in future releases.

**Comment by muhammadtaimoor145** [comment]
Can anyone plz tell me what is an argument when we are training the YOLO V8 model? Talking about the highlighted area in red.
![YOLO V8](https://github.com/ultralytics/ultralytics/assets/78852870/f39fb499-0d98-42e8-b3df-cb366b8fc347)

**Comment by glenn-jocher** [comment]
@muhammadtaimoor145 certainly! In YOLOv8, there are a number of arguments that can be passed during training to customize the training process. However, without seeing the specific command being executed, it is difficult to say for sure which argument you are referring to in the red box.

Based on the screenshot you provided, it appears that the red box is highlighting an argument of the form "--img-size XX", where XX is a numerical value. This argument specifies the size of the input images used during training. 

During training, images are often preprocessed to a fixed size to ensure consistency in the input size across the dataset. The "--img-size" argument allows you to specify the size to which images will be resized during preprocessing.

I hope this helps clarify the argument you are inquiring about. If you have any further questions, please don't hesitate to ask!

**Comment by muhammadtaimoor145** [comment]
> @muhammadtaimoor145 certainly! In YOLOv8, there are a number of arguments that can be passed during training to customize the training process. However, without seeing the specific command being executed, it is difficult to say for sure which argument you are referring to in the red box.
> 
> Based on the screenshot you provided, it appears that the red box is highlighting an argument of the form "--img-size XX", where XX is a numerical value. This argument specifies the size of the input images used during training.
> 
> During training, images are often preprocessed to a fixed size to ensure consistency in the input size across the dataset. The "--img-size" argument allows you to specify the size to which images will be resized during preprocessing.
> 
> I hope this helps clarify the argument you are inquiring about. If you have any further questions, please don't hesitate to ask!

Here is code am passing. What is meaning of [3, 16, 3, 2] and son on. This by default arguments I guess. I am attaching code. Plz check 
![YOLO 2](https://github.com/ultralytics/ultralytics/assets/78852870/26d12a08-8431-4d4d-9136-dfac68a404a7)

**Comment by glenn-jocher** [comment]
@muhammadtaimoor145, in the highlighted code, the arguments [3, 16, 3, 2] and [16, 32, 3, 2] correspond to the filter sizes for the first and second convolutional layers of the YOLOv8 network, respectively. Specifically, the numbers represent the number of filters used in each layer, the size of the filters, and the stride of the convolution operation. 

During training, the filter sizes and other architectural parameters can be adjusted to customize the YOLOv8 network to your specific use case. The filter sizes in particular can impact the size and complexity of the network, and may need to be adjusted depending on the dataset and classes being detected.

I hope this answers your question! If you have any further questions, please don't hesitate to ask.

**Comment by bijuangalees** [comment]
How to edit the filer size in each  convoution layer?Which file need to be updated?
![Screenshot 2023-08-27 233005](https://github.com/ultralytics/ultralytics/assets/43088119/8d9b3a7d-29a8-4590-95ae-b164730adf3d)

**Comment by glenn-jocher** [comment]
@bijuangalees you can modify the filter size for each convolutional layer by editing the .yaml configuration file for the YOLOv8 network. In each configuration line for a convolutional layer, the arguments correspond to the layer's parameters, including the filter size.

For example, consider a line in the form `x y Conv [a, b, c, d]`. Here `a` is the input number of channels for this layer, `b` is the number of filters (or output channels), `c` is the filter size, and `d` is the stride size.

By changing the value of `c` in the relevant lines, you can adjust the filter size of each convolutional layer.

Remember to make sure the changes are compatible with the structure of your model, as some modifications can cause issues due to incompatibility in the dimensions of the layers.

**Comment by bijuangalees** [comment]
Is there any way to know the output size of an image in each layer after changing and stride and padding ?
What is mean by n=1, 2 etc?
I read that from -1 is taking inpute from previous layer, in the architecture every layer has -1. So what is the first layer
![Screenshot 2023-08-28 144656](https://github.com/ultralytics/ultralytics/assets/43088119/a4d9a94c-584f-4ea1-981c-f1a62d6fab6a)
?

**Comment by bijuangalees** [comment]
I want to change the stride padding size of yolov8n. What files need to be made changes?  making changes on yolo8.yamal file itself effect on architecture?![Screenshot 2023-08-28 145422](https://github.com/ultralytics/ultralytics/assets/43088119/9a86bc39-456d-45e9-8088-51bc00e6afb5)
