### ISSUE TITLE
Getting error when trying to train on GPU

### ISSUE THREAD

**Issue by initdebugs** [ultralytics/ultralytics#234]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

`Error executing job with overrides: ['task=detect', 'mode=train', 'model=yolov8s.pt', 'data=/content/Traffic-Detection-5/data.yaml', 'epochs=200', 'imgsz=800']
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/cli.py", line 52, in cli
    func(cfg)
  File "/usr/local/lib/python3.8/dist-packages/hydra/main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/v8/detect/train.py", line 206, in train
    model.train(**cfg)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/model.py", line 193, in train
    self.trainer.train()
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/trainer.py", line 177, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/trainer.py", line 275, in _do_train
    for i, batch in pbar:
  File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.8/dist-packages/torch/_utils.py", line 543, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/data/base.py", line 179, in __getitem__
    return self.transforms(self.get_label_info(index))
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/data/augment.py", line 48, in __call__
    data = t(data)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/data/augment.py", line 48, in __call__
    data = t(data)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/data/augment.py", line 361, in __call__
    i = self.box_candidates(box1=instances.bboxes.T,
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/data/augment.py", line 375, in box_candidates
    return (w2 > wh_thr) & (h2 > wh_thr) & (w2 * h2 / (w1 * h1 + eps) > area_thr) & (ar < ar_thr)  # candidates
ValueError: operands could not be broadcast together with shapes (5,) (9,) `

### Environment

Ultralytics YOLOv8.0.3 🚀 Python-3.8.16 torch-1.13.0+cu116 CUDA:0 (Tesla T4, 15110MiB)

### Minimal Reproducible Example

!yolo task=detect mode=train model=yolov8s.pt data={dataset.location}/data.yaml epochs=200 imgsz=800

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@initdebugs looks like a dataloader issue, please try it again with `v5loader=True`.

**Comment by Laughing-q** [comment]
@initdebugs could you please tell me more about this issue? like is there negative labels or empty labels in you custom dataset? I'd like to reproduce your issue and solve it. :)

**Comment by initdebugs** [comment]
@Laughing-q I'm not sure what you mean with 'negative labels'. There are no empty labels in the dataset.

Adding v5loader=True to the query worked, it's now training

**Comment by initdebugs** [comment]
@Laughing-q I made my dataset with Roboflow and exported it in YoloV8 format. 
https://universe.roboflow.com/lesley-natrop-zgywz/traffic-detection-e3og7/dataset/6
This is the dataset. Hope this helps

**Comment by Laughing-q** [comment]
@initdebugs thanks!

**Comment by Laughing-q** [comment]
@initdebugs hi, I reproduced your error and checked your dataset. Most of your labels are detection labels which include only five columns but some of your labels are segmentation labels like `20221224131640_016701_MP4-0_jpg.rf.b916383333413a5c7ac6a41806dffd27.txt`.
**Actually we only support either all of the labels are segments or all of them are detections.**
The new dataloader treat this situation different from V5 loader so that's why you don't get error when you set `v5loader=True`. But as you're v5loader, I think there might be something incorrect in your training. 

It could be the mosaic+random_perspective progress.
part of random_perspective code in v5loader:
![image](https://user-images.githubusercontent.com/61612323/211771979-8dfa3b62-a597-4627-b2b6-6c69fc5e94fd.png)
this might make some of your bboxes value become 0 when there's a segment label.

Anyway the best solution here is clean up your labels and make it all detection labels.

**Comment by initdebugs** [comment]
Thank you for the quick help! That makes sense, I will fix those labels and will try again.

**Comment by vodanhbk95** [comment]
> `v5loader`



> @initdebugs looks like a dataloader issue, please try it again with `v5loader=True`.

Did u mean edit arg `v5loader=True` in default.yaml

**Comment by initdebugs** [comment]
No pass v5loader=True as argument when training.

**Comment by vodanhbk95** [comment]
> 

still not working.

>   File "/home/cybercore/miniconda3/envs/haimd_yolov5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cybercore/miniconda3/envs/haimd_yolov5/lib/python3.7/site-packages/ultralytics/nn/modules.py", line 145, in forward
    return x + self.cv2(self.cv1(x)) if self.add else self.cv2(self.cv1(x))
  File "/home/cybercore/miniconda3/envs/haimd_yolov5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cybercore/miniconda3/envs/haimd_yolov5/lib/python3.7/site-packages/ultralytics/nn/modules.py", line 52, in forward
    return self.act(self.bn(self.conv(x)))
  File "/home/cybercore/miniconda3/envs/haimd_yolov5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cybercore/miniconda3/envs/haimd_yolov5/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/cybercore/miniconda3/envs/haimd_yolov5/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 460, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by vodanhbk95** [comment]
I think its the problem of batchsize, I dont really understand why but when i descrease the number of batchsize , this error is disappeared.

**Comment by vodanhbk95** [comment]
I dont really understand why but when i decrease the number of batchsize, the error disappears. Maybe the problem is about VRAM.

**Comment by initdebugs** [comment]
I'm absolutely no expert in this. When there's not enough vram, the error would be something like: Cuda out of memory

**Comment by ichsan2895** [comment]
I also have this problem. The problem solved after I cleaned the yolo annotations.
If yolo annot has Bbox format, then use task=detect, if yolo annot has segmentation format, then use task=segment. You can not mix it both.

Just a reminder
BBOX format = _class Xcenter Ycenter Width Height_
Segmentation format = _class X1 Y1 X2 Y2 .... Xn Yn_

**Comment by AyanPaul2210** [comment]
Same error I am facing while training even after v5loader=True

Ultralytics YOLOv8.0.6 🚀 Python-3.8.16 torch-1.13.0+cu116 CUDA:0 (Tesla T4, 15110MiB)
yolo/engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=/content/drive/MyDrive/yolo/yolov8/obj_det/Field-Capsicum-1/data.yaml, epochs=1, patience=50, batch=16, imgsz=800, save=True, cache=False, device=, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=False, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, retina_masks=False, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, hydra={'output_subdir': None, 'run': {'dir': '.'}}, v5loader=True, save_dir=runs/detect/train6

Dataset not found ⚠️, missing paths ['/content/drive/MyDrive/yolo/yolov8/obj_det/datasets/Field-Capsicum-1/valid/images']
Error executing job with overrides: ['task=detect', 'mode=train', 'model=yolov8n.pt', 'data=/content/drive/MyDrive/yolo/yolov8/obj_det/Field-Capsicum-1/data.yaml', 'epochs=1', 'imgsz=800', 'v5loader=True']
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/cli.py", line 56, in cli
    func(cfg)
  File "/usr/local/lib/python3.8/dist-packages/hydra/main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/v8/detect/train.py", line 207, in train
    model.train(**cfg)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/model.py", line 189, in train
    self.trainer = self.TrainerClass(overrides=overrides)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/trainer.py", line 126, in __init__
    self.data = check_dataset_yaml(self.data)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/data/utils.py", line 232, in check_dataset_yaml
    raise FileNotFoundError('Dataset not found ❌')
FileNotFoundError: Dataset not found ❌

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by Laughing-q** [comment]
@AyanPaul2210 

> Dataset not found warning, missing paths ['/content/drive/MyDrive/yolo/yolov8/obj_det/datasets/Field-Capsicum-1/valid/images']

hi it seems you didn't give the correct dataset path.

**Comment by CodexData** [comment]
@Laughing-q referring back to your comment regarding detection and segment labels, please can you clarify on the criteria for this? Its just odd as each label was done identically, so im at a loss as to why this error occurred but with v5loader its training ok

**Comment by FrancescoSaverioZuppichini** [comment]
I have a similar error

**Comment by Edohvin** [comment]
I am facing the same error.
All my labels seem object detection clean.
v5loader = True while training also does not help.

Do you think empty labels might be an issue? 
My data was also exported to yolov8 format using Roboflow. Seems like the issue might be with Roboflow export?

**Comment by Laughing-q** [comment]
@Edohvin what version of ultralytics are you using? please use the latest package version. :)

**Comment by Edohvin** [comment]
@Laughing-q 
I was using 8.0.31
Now I updated to 8.0.32, but still have same issue

`yolo detect train data=data.yaml model=yolov8l.pt epochs=300` Gives the error
`yolo detect train data=data.yaml model=yolov8l.pt epochs=300 batch=4` Gives no error. Running smaller models such as yolov8s.pt also gives no errors.

I'll keep looking into it, maybe it really is a cudnn installation issue. It is not too big of an issue for me. But finding the solution might help others or solve a bug :)

**Comment by Kjellmd** [comment]
@Edohvin Did you figure out how to fix the limitations of batch sizes? Having the same problems myself.

**Comment by Edohvin** [comment]
@Kjellmd No I haven't sorry! Haven't trained a model in a while

**Comment by Kjellmd** [comment]
@Edohvin I found out how to fix it! Need to update to the newest version of the library. 8.0.51 is what i'm using. And run the line "YOLO.amp = False" before training. Hope this helps

**Comment by andophine** [comment]
export dataset from roboflow with yolo5 PyTorch format, and add v5loader = True flag did solve my problem.

**Comment by glenn-jocher** [comment]
@andophine i'm glad to hear that you were able to resolve your issue! Just as a clarification for others who might come across this thread, while exporting a dataset from roboflow, select the YOLO PyTorch format. Afterward, when initiating the training with your dataset, remember to enable the 'v5loader' flag.

Remember, usage of the 'v5loader' flag helps to configure the loader for specific dataset formats and might solve issues related to incompatible or unexpected data formats. It's great to hear that it helped in your case!

Please feel free to report any other issues you encounter, or new features that you think could be beneficial. Contributions to YOLOv8 are always welcome! Thank you for being a part of the YOLO community.

**Comment by Shreya72Dubey** [comment]
/content
Ultralytics YOLOv8.0.20 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla T4, 15102MiB)
yolo/engine/trainer: task=detect, mode=train, model=yolov8s.yaml, data=/content/datasets/freedomtech/data.yaml, epochs=100, patience=50, batch=16, imgsz=800, save=True, cache=False, device=, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=False, val=True, save_json=False, save_hybrid=False, conf=0.001, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=ultralytics/assets/, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.001, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, save_dir=runs/detect/train15
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/cfg/__init__.py", line 249, in entrypoint
    getattr(model, mode)(verbose=True, **overrides)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/model.py", line 203, in train
    self.trainer = self.TrainerClass(overrides=overrides)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py", line 122, in __init__
    self.data = check_det_dataset(self.data)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/utils.py", line 237, in check_det_dataset
    raise FileNotFoundError(msg)
FileNotFoundError: 
Dataset '/content/datasets/freedomtech/data.yaml' not found ⚠️, missing paths ['/content/datasets/freedomtech/labels/validation']
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit   I have found this error even my path is correct what i do now

**Comment by glenn-jocher** [comment]
Hey there! It looks like there’s a bit of trouble finding your dataset. 😕 This issue usually crops up when the paths specified in your `data.yaml` file might not be correctly pointing to where your dataset actually lives.

Could you double-check the paths in your `data.yaml` file? Here's a quick example of what it should look like:

```yaml
train: /path/to/your/train/images
val: /path/to/your/val/images
...
```

Make sure that the paths to `train`, `val`, and if you have them, `test` directories are absolutely correct and accessible from where you're running your YOLO command. Also, ensure that the `/content/datasets/freedomtech/labels/validation` directory exists and is not empty. Sometimes, a simple typo can be the culprit!

One more thing, since you're working in an environment that looks a lot like Google Colab (`/content` is a giveaway 😉), ensure that your drive is properly mounted and the paths in the `data.yaml` file are correctly prefixed with `/content/drive/MyDrive/` if your dataset is in your Google Drive.

If you’ve double-checked everything and it still doesn’t work, try printing out the full path in a notebook cell or the command line to confirm you can access it:

```python
import os
print(os.listdir('/content/datasets/freedomtech/labels/validation'))
```

This should list the content of the folder if it’s accessible.

Hope this helps! Keep us updated. 🚀

**Comment by Krystex** [comment]
This issue persists, I still get the `ValueError: operands could not be broadcast together with shapes` error. Also, apparently the `v5loader`-flag was deprecated ([see here](https://github.com/ultralytics/ultralytics/pull/3744)), so that doesn't work.

**Comment by glenn-jocher** [comment]
It seems like the issue might be related to data augmentation or the dataset format. Please ensure your dataset annotations are consistent and correctly formatted for the task you're performing. If the problem persists, consider checking for any updates or fixes in the latest version of the repository.
