### ISSUE TITLE
Model tracker does not work with the version 8.0.90

### ISSUE THREAD

**Issue by ppiiesle3y1** [ultralytics/ultralytics#2341]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Hi I recently updated the ultralytics to the latest version and the model tracker does not work. When I switch to an older version of Yolov8, the problem is solved. I've pasted the simple line of code I run and the error message.

I'm not sure if this is a sagemaker environment issue or yolo issue, if that's not a bug from the update, please kindly ignore. Thank you

### Environment

-Yolov8 8.0.90
-Python 3.8 and Python 3.9
-Sagemaker Pytorch 1.12

### Minimal Reproducible Example

#this is the code
results= model_best.track(source="video.mp4",classes=[6])

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-5fa6b98f0c42> in <module>
     48     print(f"Received arguments: {args}")
     49 
---> 50     box, track_id = get_data_from_model(model_best,"edg-sample1_cropped_10fps.mp4")
     51 

<ipython-input-8-5fa6b98f0c42> in get_data_from_model(model, vid)
     24     track_id=[]
     25     results=model.track(source=vid, classes=[6],device=0,stream=True)
---> 26     for result in results:
     27         boxes = result.boxes.xywh  # Boxes object for bbox outputs
     28         trackid=result.boxes.id

/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py in generator_context(*args, **kwargs)
     62                         # Pass the last request to the generator and get its response
     63                         with self.clone():
---> 64                             response = gen.send(request)
     65 
     66             # We let the exceptions raised above by the generator's `.throw` or

/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py in stream_inference(self, source, model)
    235             with self.dt[2]:
    236                 self.results = self.postprocess(preds, im, im0s)
--> 237             self.run_callbacks('on_predict_postprocess_end')
    238 
    239             # Visualize, save, write results

/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py in run_callbacks(self, event)
    329         """Runs all registered callbacks for a specific event."""
    330         for callback in self.callbacks.get(event, []):
--> 331             callback(self)
    332 
    333     def add_callback(self, event: str, func):

/opt/conda/lib/python3.8/site-packages/ultralytics/tracker/track.py in on_predict_postprocess_end(predictor)
     46         if len(det) == 0:
     47             continue
---> 48         tracks = predictor.trackers[i].update(det, im0s[i])
     49         if len(tracks) == 0:
     50             continue

/opt/conda/lib/python3.8/site-packages/ultralytics/tracker/trackers/byte_tracker.py in update(self, results, img)
    219         self.multi_predict(strack_pool)
    220         if hasattr(self, 'gmc') and img is not None:
--> 221             warp = self.gmc.apply(img, dets)
    222             STrack.multi_gmc(strack_pool, warp)
    223             STrack.multi_gmc(unconfirmed, warp)

/opt/conda/lib/python3.8/site-packages/ultralytics/tracker/utils/gmc.py in apply(self, raw_frame, detections)
     77             return self.applyEcc(raw_frame, detections)
     78         elif self.method == 'sparseOptFlow':
---> 79             return self.applySparseOptFlow(raw_frame, detections)
     80         elif self.method == 'file':
     81             return self.applyFile(raw_frame, detections)

/opt/conda/lib/python3.8/site-packages/ultralytics/tracker/utils/gmc.py in applySparseOptFlow(self, raw_frame, detections)
    246         """Initialize."""
    247         # t0 = time.time()
--> 248         height, width, _ = raw_frame.shape
    249         frame = cv2.cvtColor(raw_frame, cv2.COLOR_BGR2GRAY)
    250         H = np.eye(2, 3)

AttributeError: 'cv2.VideoCapture' object has no attribute 'shape'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by wangzexi** [comment]
https://github.com/ultralytics/ultralytics/pull/2336#pullrequestreview-1407121259

**Comment by glenn-jocher** [comment]
@ppiiesle3y1 thank you for your contribution to YOLOv8! We really appreciate it. The Ultralytics team has reviewed your pull request and provided some feedback on how to implement the requested changes more effectively. Please take the suggestions into consideration and make the necessary revisions in your pull request. Once the changes have been implemented, we will review the pull request again for final approval.
