### ISSUE TITLE
Export key point data of YOLOv8 pose detection

### ISSUE THREAD

**Issue by 7288Fzq** [ultralytics/ultralytics#2342]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can I export key point data when using the pose model, for example: key point coordinates of human body movement in each frame of a video

**Comment by glenn-jocher** [comment]
@7288Fzq yes, you can export key point data when using the pose model in YOLOv8. The pose model outputs a set of keypoints representing the human body movement in each frame of a video. You can extract these keypoints and save them as a JSON or CSV file for further analysis or visualization.

**Comment by 7288Fzq** [comment]
> @7288Fzq是的，在YOLOv8中使用pose模型时可以导出关键点数据。姿态模型输出一组关键点，代表视频每一把中的人体运动。你可以提这个一些关键点并将它们保存为 JSON 或 CSV 文件，以提供一步分析或可视化。

How can I realize this function, is there a code example! Whether to read from the video stream or export from adding code before detection begins. thank you

**Comment by 7288Fzq** [comment]
> @7288Fzq yes, you can export key point data when using the pose model in YOLOv8. The pose model outputs a set of keypoints representing the human body movement in each frame of a video. You can extract these keypoints and save them as a JSON or CSV file for further analysis or visualization.

I checked the documentation of pose and found the function kpts_decode. Is it possible to use this function to derive key points? Looking forward to your reply!

**Comment by glenn-jocher** [comment]
@7288Fzq, yes, you are correct. The `kpts_decode` function can be used to derive key points from the pose model output. This function takes as input the pose model output tensor and outputs the key point coordinates. You can then use these coordinates to save the key points as a JSON or CSV file for further analysis or visualization. Let me know if there's anything else I can assist you with.

**Comment by Zengyf-CVer** [comment]
@7288Fzq 
May I ask the specific usage of this kpts_decode function, can you give a sample code?

**Comment by 7288Fzq** [comment]
> 

我本来是想做摔倒识别，通过对关键点的计算，判断是否摔倒，我感觉这样比图像识别来的更加准确。现在我想用来做篮球的投篮等动作的检测。

**Comment by 7288Fzq** [comment]
> @7288Fzq May I ask the specific usage of this kpts_decode function, can you give a sample code?


我本来是想做摔倒识别，通过对关键点的计算，判断是否摔倒，我感觉这样比图像识别来的更加准确。现在我想用来做篮球的投篮等动作的检测。
