### ISSUE TITLE
Unable to import ultralytics module on RaspberryPi 4

### ISSUE THREAD

**Issue by fahiar10** [ultralytics/ultralytics#2345]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

I installed Ultralytics on a Raspberry Pi 4 Model B 4GB using 'pip install ultralytics'. However, when I tried running the script, I encountered the 'Illegal instruction' error. What could be causing this issue?

### Environment

-OS: Debian GNU/Linux 11 (bullseye)
-Python: 3.10.9

### Minimal Reproducible Example

```
from ultralytics import YOLO
```

results in the error: 
`Illegal instruction`

### Additional

I'm currently performing live inference from my webcam by API calls by having my model deployed on Roboflow but it's very slow. I want to perform this locally on RPi but can only do so if the above error is solved. Is there any other way?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@fahiar10 please paste a full error output here so we can see what might be causing the problem.

**Comment by fahiar10** [comment]
![1](https://user-images.githubusercontent.com/78529205/235488596-9b79dd24-0ea1-4e21-ad0b-37d0d6a79b52.jpg)
That IS the only error that I'm receiving.


And pretty sure it occurs while importing ultralytics because I tried line by line debugging in thonny IDE.
 
![3](https://user-images.githubusercontent.com/78529205/235488974-c63d9ed9-3893-4f45-9bf3-478e6073575a.jpg)
No issue when executing `import cv2, os`

![4](https://user-images.githubusercontent.com/78529205/235489168-9e32e3df-979a-4449-8015-9f7801122601.jpg)
But as soon as I execute the next line.. the program exits.

![2](https://user-images.githubusercontent.com/78529205/235489292-0d7792f4-58de-4330-8ee9-cbf3a451ab76.jpg)
Tried executing it directly from the terminal too.

Is there a way I can find out what the illegal instruction is?

**Comment by MERYX-bh** [comment]
I am having the same error

**Comment by glenn-jocher** [comment]
Dear @fahiar10, thank you for reaching out about the "Illegal instruction" error. This error can occur when executing code that includes an instruction that the CPU does not support. Given that you are running your code on a Raspberry Pi 4 with Debian GNU/Linux 11 and Python 3.10.9, it is possible that the ultralytics package is not compatible with your specific CPU architecture.

One possible solution is to try running your code on an x86/x64 CPU architecture instead of ARM architecture. Alternatively, you could try using YOLOv8 in another environment such as a virtual machine (e.g. using VirtualBox) or Docker container to eliminate any potential compatibility issues with your system hardware architecture.

Please let us know if you have any additional questions or if you find a solution that resolves the "Illegal instruction" error you are experiencing.

Best regards,
Glenn Jocher, Ultralytics YOLOv8 Maintainer.

**Comment by SliverAward** [comment]
> Dear @fahiar10, thank you for reaching out about the "Illegal instruction" error. This error can occur when executing code that includes an instruction that the CPU does not support. Given that you are running your code on a Raspberry Pi 4 with Debian GNU/Linux 11 and Python 3.10.9, it is possible that the ultralytics package is not compatible with your specific CPU architecture.
> 
> One possible solution is to try running your code on an x86/x64 CPU architecture instead of ARM architecture. Alternatively, you could try using YOLOv8 in another environment such as a virtual machine (e.g. using VirtualBox) or Docker container to eliminate any potential compatibility issues with your system hardware architecture.
> 
> Please let us know if you have any additional questions or if you find a solution that resolves the "Illegal instruction" error you are experiencing.

Nice to meet you. Are you saying that it is impossible to run it on Raspberry Pi 4 64-bit?

**Comment by glenn-jocher** [comment]
Dear @SliverAward, thank you for your question. While it is possible to run YOLOv8 on a Raspberry Pi 4 with a 64-bit operating system, it is also dependent on hardware architecture and specific system configurations. 

The "Illegal instruction" error can occur when certain instructions are not supported by the CPU on which the code is being executed. This potential issue may be encountered on some ARM-based systems like the Raspberry Pi 4.

To eliminate any potential compatibility issues with your system's specific hardware architecture, you may wish to try running YOLOv8 in another environment such as a virtual machine or Docker container.

If you have any further questions or concerns, please do not hesitate to reach out.

**Comment by SliverAward** [comment]
> Dear @SliverAward, thank you for your question. While it is possible to run YOLOv8 on a Raspberry Pi 4 with a 64-bit operating system, it is also dependent on hardware architecture and specific system configurations.
> 
> The "Illegal instruction" error can occur when certain instructions are not supported by the CPU on which the code is being executed. This potential issue may be encountered on some ARM-based systems like the Raspberry Pi 4.
> 
> To eliminate any potential compatibility issues with your system's specific hardware architecture, you may wish to try running YOLOv8 in another environment such as a virtual machine or Docker container.
> 
> If you have any further questions or concerns, please do not hesitate to reach out.

 Thanks to YOLOv8, I have been consistently interested in object detection. I'm sorry for constantly asking questions.

After training with YOLOv8 nano version, I tried running it on a Raspberry Pi 4 4GB, and I did feel a slight improvement.

Stubbornly, I want to run it to the fullest extent possible with the limited hardware of the Raspberry Pi!

Please give me some keywords to work with! Also, I want to use the quantization method. What code should I write with the trained pt file?

I also want to display the FPS, but I can't find the related code even though I searched for it.

**Comment by goodevile** [comment]
I will be direct: Use docker.

Yes, it will consume a little bit of processing power, but you can check everything that docker is using and then install it yourself without docker.

https://docs.ultralytics.com/quickstart/#install-ultralytics

![image](https://github.com/ultralytics/ultralytics/assets/46387951/4dddf87c-cdeb-490f-bb3e-ba6499e0d0ad)

**Comment by glenn-jocher** [comment]
@goodevile absolutely, Docker is a great way to ensure compatibility and streamline the setup process! 🐳 It does use a bit of extra processing power, but the trade-off for ease of use and environment consistency is often worth it. Plus, as you mentioned, you can always peek into what Docker is doing and replicate that setup natively if needed.

For those interested, here's a quick snippet on how to pull and run our Docker image:

```bash
docker pull ultralytics/yolov8:latest  # Pull the latest YOLOv8 image
docker run -it ultralytics/yolov8:latest  # Run the container
```

And here's the link to our [installation guide](https://docs.ultralytics.com/quickstart/#install-ultralytics) for more detailed instructions. Happy detecting! 🚀

**Comment by aliyilma** [comment]
I tried both docker and without docker solutions, still having that error.

With docker: "Illegal Instruction (core dump)"
Without docker: "Illegal Instruction"

AlsonI saw that those are related with importing torch and torchvision. Importing Cv2 and other libs are fine. Tried almost every RPiOS's pretty much the error was same.

**Comment by pderrenger** [comment]
@aliyilma thank you for the detailed feedback. The "Illegal Instruction" error typically indicates an incompatibility with the CPU architecture. Please ensure you are using the latest versions of the Ultralytics package, PyTorch, and TorchVision, as updates may resolve this issue. Additionally, you might want to try using the NCNN export format, which is optimized for ARM architectures like the Raspberry Pi. If the issue persists, consider using a virtual environment to isolate dependencies.

**Comment by aliyilma** [comment]
@goodevile 

Raspberry Pi 4B
The docker line command directly from [Ultralytics Docs](https://docs.ultralytics.com/guides/raspberry-pi/#set-up-ultralytics)
`t=ultralytics/ultralytics:latest-arm64 && sudo docker pull $t && sudo docker run -it --ipc=host $t`

@pderrenger 
Again, as I said especially importing torch and torchvision (also ultralytics) causing this. 
- Yes I've updated all the packages.
- Yes I've tried different version combinations.
- Yes, I am sure that pip installs the correct package wheels, also I tried installing manually.
- No, NCNN or any other format is not the issue, I cannot even import torch and torchvision at the beginning.
- Yes, I am always using virtual environment

**Comment by pderrenger** [comment]
Thank you for the detailed information. Given that the issue persists with both Docker and non-Docker setups, and considering the "Illegal Instruction" error specifically with `torch` and `torchvision`, it seems to be a compatibility issue with the ARM architecture of the Raspberry Pi 4B.

Please ensure you are using the latest versions of PyTorch and TorchVision compatible with ARM. You might want to try the following steps:
1. Use the official PyTorch ARM builds from the [PyTorch website](https://pytorch.org).
2. Verify that your Raspberry Pi OS is up-to-date and running a 64-bit version.
3. Consider using a lightweight OS like Raspberry Pi OS Lite to minimize resource usage.

If the issue persists, it might be worth trying a different ARM-compatible deep learning framework or reaching out to the PyTorch community for more specific guidance on ARM compatibility.

**Comment by aliyilma** [comment]
Thank you for quick and detailed responses. 1. Check, 2. Check and 3. Check (with lite/normal & Bookworm and Bullseye). From now on it seems the only problem caused by PyTorch, but I wonder why Docker solution did not work either. I could not find reliable solutions for the Pytorch & Illegal Instruction error online. Maybe my RasPi has hardware problem itself. 

If anybody else faced similar error and perhaps with a solution, I would love to discuss it.

**Comment by aliyilma** [comment]
Update: I've managed to install torch and torchvision via `sudo apt install python3-torch python3-torchvision`. And for other packages like ultralytics, `sudo pip pkg_name --break-system-packages` was mandatory because I had to use `sudo apt install`. So I cannot use virtual environment, but I am only using Raspberry Pi for small automations so I am good with "breaking system packages". Maybe there ara better ways but my capabilities are limited. So if it works, it works for me.

I don't understand why linux is that hard...

**Comment by pderrenger** [comment]
Thank you for the update. It's great to hear you've managed to install `torch` and `torchvision`. Using `sudo pip` with `--break-system-packages` can indeed resolve some installation issues, but it does come with risks, as you mentioned. For future reference, using a virtual environment is generally recommended to avoid such conflicts. If you encounter any other issues or have further questions, feel free to ask. Linux can have a learning curve, but it offers great flexibility once you get the hang of it.

**Comment by pderrenger** [comment]
Thank you for sharing your experience. Linux can indeed be challenging at times, especially on ARM devices like the Raspberry Pi. If you continue to face issues, you might consider using Ubuntu Server, which is also supported on Raspberry Pi and may offer a different set of precompiled packages that could simplify your setup. If you encounter further difficulties, please ensure you are using the latest versions of all packages.

**Comment by GateraGael** [comment]
I am having similar issues importing YOLO through docker with my Raspberrypi 4B, the operating system is bookworm.

cat /etc/os-release

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm

The simple python script also produces the same error Illegal instruction (core dumped)

```python
from ultralytics import YOLO
print("it actually runs!")
```

output is Illegal instruction (core dumped) for all three of the following images: 
- ultralytics/ultralytics:latest-arm64
- ultralytics/ultralytics:8.2.74-arm64
- ultralytics/ultralytics:8.2.77-arm64

All pulled from [Ultralytics DockerHub](https://hub.docker.com/r/ultralytics/ultralytics/tags?page=1&page_size=&name=&ordering=).

I also tried to build the docker image using the ARM docker file provided by the ultralytics repo.

[Dockerfile-arm64](https://github.com/ultralytics/ultralytics/blob/main/docker/Dockerfile-arm64)

Changed the base image three times to see if anything changes original base image: arm64v8/debian:bookworm-slim
Attempts:
- arm64v8/debian:bookworm
- arm64v8/debian:bullseye
- arm64v8/debian:bullseye-slim

Still the same error Illegal instruction (core dumped)

**Comment by pderrenger** [comment]
Thank you for the detailed information. The "Illegal instruction" error typically indicates an incompatibility with the ARM architecture. Please ensure you are using the latest versions of all packages. Additionally, you might want to try using the official PyTorch ARM builds from the PyTorch website, as they are optimized for ARM architecture. If the issue persists, consider reaching out to the PyTorch community for more specific guidance on ARM compatibility.

**Comment by dnghosh08** [comment]
> Update: I've managed to install torch and torchvision via `sudo apt install python3-torch python3-torchvision`. And for other packages like ultralytics, `sudo pip pkg_name --break-system-packages` was mandatory because I had to use `sudo apt install`. So I cannot use virtual environment, but I am only using Raspberry Pi for small automations so I am good with "breaking system packages". Maybe there ara better ways but my capabilities are limited. So if it works, it works for me.
> 
> I don't understand why linux is that hard...

while in my virtual environment (on RPI4, bookworm), downgrading torch to 2.3.1 & torchvision to 0.18.1 packages helped me get past the "illegal instruction" issue:
pip3 install torch==2.3.1 torchvision==0.18.1

**Comment by glenn-jocher** [comment]
Thank you for sharing your solution. If you encounter further issues, please ensure you're using the latest versions of all packages. For any additional assistance, feel free to reach out.

**Comment by glenn-jocher** [comment]
@aliyilma i'm glad you found a solution that works for you. Linux can be challenging at times, but it's great for customization and flexibility. If you have any more questions or need further assistance, feel free to ask!

**Comment by glenn-jocher** [comment]
Thank you for sharing your solution. Linux can be challenging, but your approach is practical for your needs. If you have further questions, feel free to ask!

**Comment by glenn-jocher** [comment]
I'm glad you found a solution that works for you. Linux can be challenging, especially with package management, but it offers flexibility once you get the hang of it. If you have any more questions, feel free to ask!

**Comment by glenn-jocher** [comment]
Thank you for sharing your solution. Linux can be challenging at times, but your approach is practical for your needs. If you have further questions or need assistance, feel free to ask here.

**Comment by glenn-jocher** [comment]
Thank you for sharing your solution. Linux can indeed be challenging, especially with package management, but your approach is valid for your use case. If you have any further questions or need assistance, feel free to ask here.

**Comment by bartoszxkozlowski** [comment]
> > Update: I've managed to install torch and torchvision via `sudo apt install python3-torch python3-torchvision`. And for other packages like ultralytics, `sudo pip pkg_name --break-system-packages` was mandatory because I had to use `sudo apt install`. So I cannot use virtual environment, but I am only using Raspberry Pi for small automations so I am good with "breaking system packages". Maybe there ara better ways but my capabilities are limited. So if it works, it works for me.
> > I don't understand why linux is that hard...
> 
> while in my virtual environment (on RPI4, bookworm), downgrading torch to 2.3.1 & torchvision to 0.18.1 packages helped me get past the "illegal instruction" issue: pip3 install torch==2.3.1 torchvision==0.18.1

Just as a possible similar solution for anybody that might have the same problem when trying to run ultralytics or any other package that has it as a dependency on a Raspberry Pi 4 as of today - for the same problem with "Illegal instruction" all I needed was to downgrade from torchvision==0.25.0 to torchvision==0.24.1. Thank you @dnghosh08 for sharing your original solution - saved me a couple of hours!
