### ISSUE TITLE
Train at YoloV8 with rectangular training

### ISSUE THREAD

**Issue by bzisl** [ultralytics/ultralytics#235]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I know that it is quite soon and doc must have more development. If I want to train with images of 512x380, which are the parameters for train?
`imgsz=[512,380], rect=True`
???

Thanks in advance.

**Comment by AyushExel** [comment]
Yes correct. You need to use `rect=True`. See this for more details https://docs.ultralytics.com/config/#training

**Comment by AyushExel** [comment]
Closing this. Please open if the issue persisits

**Comment by CySlider** [comment]
I tried this with 832x480, but I get this warning:

> WARNING ⚠️ updating to 'imgsz=832'. 'train' and 'val' imgsz must be an integer, while 'predict' and 'export' imgsz may be a [h, w] list or an integer, i.e. 'yolo export imgsz=640,480' or 'yolo export imgsz=640' 

directly followed by

> WARNING ⚠️ 'rect=True' is incompatible with DataLoader shuffle, setting shuffle=False

Another weird thing is, while an epoch is being processed, the output line says:

 ```
    Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size                                                 
   10/3000      20.1G      1.563      1.425      1.123         72        832:  93%|█████████▎| 42/45 [00:18<00:01,  2.05it/s]

```

So size is 832 (not 832x380)

But after the epoch finishes it says size=640:

```
  Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size                                                          
10/3000      20.1G      1.546      1.429      1.131         58        640: 100%|██████████| 45/45 [00:20<00:00,  2.25it/s]         
             Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 3/3 [00:01<00:00,  1.67it/s]
               all         95        272      0.742      0.313      0.369       0.21       
```                                        

So what am I missing? Seems to me he is training in 832x832 after all

**Comment by CySlider** [comment]
Update: 

When I check train_batch0.jpg, then I see a clear difference when I do 832x832 training, vs 832x480 training. 

In first case there is a lot of paddign showing and the image grid consists of square images, in the latter the grid has no padding and the images are rectangular. So It seems this warning is just a bug, that has no effect. at least I hope so. Would like to get a confirmation on this.

I am using ultralytics-8.0.57-py3-none-any

**Comment by glenn-jocher** [comment]
@CySlider warning is not a bug. As the message states training only accepts an integer imgsz. You can optionally use rect=True. Everything is working correctly.

**Comment by CySlider** [comment]
But the warning states, that my input of 832x480 was changed to 832 which is equivalent to 832x832

If Rect=True still leads to the model training with 832x480 then the first warning is misleading, as the parameter wasn't changed obviously, else how does he know the resolution to train with?

**Comment by glenn-jocher** [comment]
As the message states training only accepts an integer imgsz, so your argument is redefined as imgsz=832. 

Since you passed rect=True YOLOv8 will resolve the short side of your image automatically to meet stride constraints of 32 or 64 depending on your model architecture.

**Comment by CySlider** [comment]
My images have different aspect ration, only most of them are in that given aspect ratio.
So do you say, the first image the trainer gets, defines the aspect ratio for all other images? Or is this per image?

train_batch0.jpg seems to suggest that they all get fit into the same aspect ratio, but might be luck, as most images have the same.

**Comment by glenn-jocher** [comment]
@CySlider there's no luck here. Unique aspect ratios for minimum image sizes are computed for every batch in your dataset and then collated accordingly during train val.

**Comment by CySlider** [comment]
Looking at all train_batch images again, I indeed see that each batch has a different aspect ratio (but same for all images in that batch) so it seems like really one image of a batch does determine the aspect ratio for all images in that batch. Ok, not what I expected to happen... But now I think I understand the warning. 

I would still argue, that it was quite natural to get to my conclusion and I'd recommend updating the documentation or change the warning, to not lead to this. 

> imgsz 	640 	size of input images as integer or w,h
> rect 	False 	support rectangular training

Maybe better:

> imgsz 	640 	size of input images as integer or w,h. Training always only accepts single integer, even if rect=True
> rect 	False 	support rectangular training by automatically adjusting each batch to the aspect ratio of that batches images. imgsz still is a single integer in this case

**Comment by glenn-jocher** [comment]
@CySlider please submit a PR to code or docs with any proposed changes and we can review there, thank you.

**Comment by CySlider** [comment]
Done: https://github.com/ultralytics/ultralytics/pull/1638

**Comment by jwee1369** [comment]
Is there a way (aside from guessing by looking at the rectangular images of train_batch*.jpg) to determine the exact rectangular image size used during training after reducing the padding when rect=True?

**Comment by uraltaf** [comment]
What I see the correct format to mention is imgsz = [h, w] .
<img width="946" alt="Screenshot_12" src="https://github.com/ultralytics/ultralytics/assets/145838006/33bca88b-138e-45bc-a5a3-a7cfbc86b0ea">

**Comment by glenn-jocher** [comment]
@uraltaf hi there! 🚀

The correct format for specifying image size with height and width is indeed `imgsz=[height, width]` when working programmatically. However, kindly note that when using the command line for YOLOv8 operations, `imgsz` currently only supports a single integer that applies to both dimensions for square training, or calculates the shorter dimension automatically when `rect=True` is set, optimizing for the aspect ratios in each batch dynamically.

So for example, in Python, it would look something like:
```python
model.train(imgsz=[512, 384], ...)
```

But for CLI, you would do:
```bash
yolo train ... imgsz=512
```
And with `rect=True`, YOLOv8 handles the aspect ratio optimally for you. 

Hope this helps clear things up! If you have any more questions or need further assistance, feel free to ask.

**Comment by Ayush23062025** [comment]
when i set rect = True , i get this error :

  File "/data/WORKSPACE_AYUSH/IRIS_DET_N_SEG/TinyissimoYOLO/ultralytics/nn/modules/conv.py", line 333, in forward
    return torch.cat(x, self.d)

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 16 but got size 15 for tensor number 1 in the list.

**Comment by glenn-jocher** [comment]
@Ayush23062025 this error typically occurs when using `rect=True` with models that have architectural constraints around input dimensions. The tensor size mismatch in the concatenation operation suggests the model is receiving inputs that don't align properly with the expected stride requirements.

Try setting `rect=False` to confirm this is the issue, and if you need rectangular training, ensure your model architecture supports variable input dimensions or consider using a different model variant that's more flexible with input sizes.

**Comment by Zoofly85** [comment]
is there a way to have rect= true but keep shuffle=true  ?

**Comment by glenn-jocher** [comment]
No—by design `rect=True` relies on sorting/grouping samples by aspect ratio to compute per-batch `batch_shapes`, so the DataLoader disables `shuffle` to keep those batches consistent (see how `set_rectangle()` reorders files/labels in the [BaseDataset.set_rectangle reference](https://docs.ultralytics.com/reference/data/base/)); if you need true shuffling, use `rect=False` (square letterbox) or implement a custom “bucketed shuffle” dataloader.

**Comment by architjaiswal** [comment]
> [@uraltaf](https://github.com/uraltaf) hi there! 🚀
> 
> The correct format for specifying image size with height and width is indeed `imgsz=[height, width]` when working programmatically. However, kindly note that when using the command line for YOLOv8 operations, `imgsz` currently only supports a single integer that applies to both dimensions for square training, or calculates the shorter dimension automatically when `rect=True` is set, optimizing for the aspect ratios in each batch dynamically.
> 
> So for example, in Python, it would look something like:
> 
> model.train(imgsz=[512, 384], ...)
> But for CLI, you would do:
> 
> yolo train ... imgsz=512
> And with `rect=True`, YOLOv8 handles the aspect ratio optimally for you.
> 
> Hope this helps clear things up! If you have any more questions or need further assistance, feel free to ask.

@glenn-jocher hello,

I tried passing model.train(data='dataset.yaml', imgsz=[512, 640], rect=True) in Ultralytics 8.4.62 🚀 Python-3.10.12 torch-2.7.1+cu118 CUDA:0 (NVIDIA GeForce RTX 4090 Laptop GPU, 15946MiB) and the rectangular training did not work for yolov8. I still get the warning imgsz must be an integer and not a tuple. 

<img width="3362" height="1440" alt="Image" src="https://github.com/user-attachments/assets/8c05acbf-0ff0-46c8-ac90-34bbdb00894d" />

**Comment by glenn-jocher** [comment]
You’re right to flag that; my 2024 comment was outdated. In current Ultralytics YOLO training, `imgsz` must be a single integer, and `[h, w]` is only supported for `predict` and `export`, while `rect=True` still enables rectangular batching by grouping similar aspect ratios and computing per-batch `batch_shapes` from that integer target rather than enforcing a fixed `512x640` train size; see [`check_imgsz()`](https://docs.ultralytics.com/reference/utils/checks) and [`BaseDataset.set_rectangle()`](https://docs.ultralytics.com/reference/data/base).
