### ISSUE TITLE
Yolov8 training custom dataset utility or Error using this mode?

### ISSUE THREAD

**Issue by storm12t48** [ultralytics/ultralytics#2358]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello everyone
I tried to understand by training a yolov8s.pt model on a custom dataset de  1500 images like this : 

> https://universe.roboflow.com/paradox-hsze6/shipandbuoy/dataset/1

Gives a best.pt which detects much less well than the basic yolo model even on targets classes  more I have the impression that the other classes have completely disappeared from the model

My question I will have forgotten a step in the training which makes me keep the same precision for the other classes and improve the target classes?

**Comment by storm12t48** [comment]
> @storm12t48 hello, thank you for reaching out. It's possible that during training, the model is overfitting on the target classes and not generalizing well to the other classes. One approach you can try is to adjust the weighting of the loss function to give more emphasis to the other classes during training. This can potentially improve the detection performance on those classes. You can also try increasing the amount of training data for the other classes. It's also important to evaluate the model's performance on a validation set to ensure that it's not overfitting. Feel free to let us know if you have any further questions or concerns.

sorry do you have example for loss function weighting?

**Comment by glenn-jocher** [comment]
@storm12t48, adjusting the loss function weighting involves assigning different weights to the different classes. Usually, this is addressed by giving the underrepresented classes a higher weight in the loss function, proportional to the inverse of the class frequency. This will lead the model to pay more attention to the underrepresented classes during training. 
For example, let's say you have two classes with 10 and 90 samples respectively. You could assign the first class a weight of 9 and the second class a weight of 1. 
Just a reminder that adjusting the loss function weighting is just one approach and may not necessarily be the best solution for all cases. It's important to experiment with different settings and evaluate the model's performance to find the best approach for your specific case.

**Comment by storm12t48** [comment]
thx for help 
 need time to learn the concepts

**Comment by storm12t48** [comment]
Hello@Glen
I come back to you I understood the principle by adjusting the weighting of the loss function on the unlisted classes but frankly I don't even know which parameters in the yolo train function can do this and how to know the id_class of all the datasets yolo?

**Comment by glenn-jocher** [comment]
Hello @storm12t48, I'm glad to hear that adjusting the loss function weighting makes sense to you. In YOLOv8, the class weighting can be adjusted through the `--cls_weights` argument, which accepts a list of weights for each class ID. The class ID can be determined by the order of the names in your dataset `.names` file, with the first name corresponding to class ID 0, the second name corresponding to class ID 1, etc. You can also find the class IDs by inspecting the generated `.txt` files for each training image, where the class ID is the integer in the first column. 

For example, if you have 3 classes named "cat", "dog" and "bird" in your .names file, where "cat" and "bird" have fewer samples, you can set the weights to be something like [1.0, 2.0, 5.0] (where 'cat' has a weight of 1.0, 'dog' has a weight  of 2.0 and 'bird' has a weight of 5.0). 

I hope this helps. If you have any further questions or concerns, please don't hesitate to let me know.

**Comment by storm12t48** [comment]
> Hello @storm12t48, I'm glad to hear that adjusting the loss function weighting makes sense to you. In YOLOv8, the class weighting can be adjusted through the `--cls_weights` argument, which accepts a list of weights for each class ID. The class ID can be determined by the order of the names in your dataset `.names` file, with the first name corresponding to class ID 0, the second name corresponding to class ID 1, etc. You can also find the class IDs by inspecting the generated `.txt` files for each training image, where the class ID is the integer in the first column.
> 
> For example, if you have 3 classes named "cat", "dog" and "bird" in your .names file, where "cat" and "bird" have fewer samples, you can set the weights to be something like [1.0, 2.0, 5.0] (where 'cat' has a weight of 1.0, 'dog' has a weight of 2.0 and 'bird' has a weight of 5.0).
> 
> I hope this helps. If you have any further questions or concerns, please don't hesitate to let me know.

But how to put a weight even on untrained classes that will not be listed in the data_custom.yaml?
Cordially

**Comment by glenn-jocher** [comment]
@storm12t48 hello,

Thank you for your question. If you have classes that are unlisted in your `data_custom.yaml` file, but you still want to apply class weighting to them, one way you can do this is by creating a new row for each unlisted class in your `.names` file and assigning a weight to it in your `--cls_weights` argument during training. 

For example, let's say your `data_custom.yaml` has 3 classes named "cat", "dog", and "bird", and you have 2 unlisted classes "turtle" and "frog" that you want to apply weighting to. You can create a new row for each unlisted class in your `.names` file, with "turtle" being assigned to class ID 3 and "frog" being assigned to class ID 4. Then, during training, you can use the `--cls_weights` argument to specify the weighting of each class, including the unlisted "turtle" and "frog" classes by providing an extended list of class weights for all classes. 

I hope this answers your question. If you have any further questions or concerns, please don't hesitate to let me know.

**Comment by Wang-Yu-Qing** [comment]
@glenn-jocher Is there a way to assign classes weights in the code rather than command line args `--cls_weight`?

**Comment by glenn-jocher** [comment]
@Wang-Yu-Qing hello there! 👋

Absolutely, you can assign class weights directly in the code. If you're using a Python script to train your model, you can set the class weights in the `hyp` (hyperparameters) dictionary under the key `cls_pw` (class positive weights). Here's a quick example:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('yolov8n.pt')

# Define your class weights
class_weights = [1.0, 2.0, 1.5]  # Example weights for three classes

# Set class weights in hyperparameters
model.hyp['cls_pw'] = class_weights

# Train your model
model.train()
```

This will apply the specified weights to your classes during training. Hope this helps, and happy training! 😊

**Comment by glenn-jocher** [comment]
Hello @Wang-Yu-Qing-Qing! 😊

I'm sorry to hear you're encountering issues. In YOLOv8, you can set class weights by modifying the `hyp` (hyperparameters) YAML file used during training. Here's a quick example of how you can do this:

```yaml
# hyp.yaml
cls_pw: [1.0, 2.0, 1.5]  # Example class weights
```

Then, pass this file to the training command:

```bash
yolo train data=your_dataset.yaml model=yolov8n.pt hyp=hyp.yaml
```

This should apply your class weights correctly. Let me know if this helps or if you need further assistance!

**Comment by Wang-Yu-Qing** [comment]
@glenn-jocher Not working:
```
> yolo train data=data.yaml model=yolov8n.pt hyp=hyp.yaml device=cpu
Traceback (most recent call last):
  File "/Users/wangyq/opt/miniconda3/envs/football/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/Users/wangyq/opt/miniconda3/envs/football/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 501, in entrypoint
    check_dict_alignment(full_args_dict, overrides)
  File "/Users/wangyq/opt/miniconda3/envs/football/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 308, in check_dict_alignment
    raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'hyp' is not a valid YOLO argument. 
```

**Comment by glenn-jocher** [comment]
Hey @Wang-Yu-Qing-Qing-Qing! 👋

It looks like there's a bit of confusion with the command syntax. In YOLOv8, the hyperparameters should be included directly in your `data.yaml` file, rather than as a separate `hyp.yaml`. Here's how you can specify them:

```yaml
# data.yaml
train: /path/to/train/images
val: /path/to/val/images

# Hyperparameters
lr0: 0.01  # initial learning rate
lrf: 0.1   # final learning rate
momentum: 0.937  # SGD momentum
weight_decay: 0.0005  # optimizer weight decay
warmup_epochs: 3.0  # warmup epochs
warmup_momentum: 0.8  # warmup momentum
warmup_bias_lr: 0.1  # warmup bias lr
box: 0.05  # box loss gain
cls: 0.5  # cls loss gain
cls_pw: 1.0  # cls positive weight
obj: 1.0  # obj loss gain (scale with pixels)
obj_pw: 1.0  # obj positive weight
iou_t: 0.20  # IoU training threshold
anchor_t: 4.0  # anchor-multiple threshold
# ... other hyperparameters
```

Then, run your training command without the `hyp` argument:

```bash
yolo train data=data.yaml model=yolov8n.pt device=cpu
```

Give this a try, and you should be good to go! If you run into any more issues, just let me know. Happy training! 😊

**Comment by Wang-Yu-Qing** [comment]
@glenn-jocher I'm able to launch the training task successfully. But from the output of the trainer, I don't see any parameters named `cls_pw`, even though I set it as `cls_pw = [1.0, 2.0, 1.0, 1.0]` in the `data.yaml`. Is it actually working?: 
```
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=data.yaml, epochs=100, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=mps, workers=8, project=None, name=train13, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train13
Overriding model.yaml nc=80 with nc=4
```

**Comment by satyrmipt** [comment]
@Wang-Yu-Qing 
> And in the `utils/loss.py` I didn't find any code using `cls_pw` so I think this parameter may not working. I think I need to hack the loss function by myself. Hope your develop team could provide a standard way to set classes weights.

1) looks like cls_pw was not implemented in yolo8, look here https://github.com/ultralytics/ultralytics/pull/8557
2) do you know how to hack the loss function if working in google colab? I have no access to yolo source code in colab.

**Comment by Najamulhassan3383** [comment]
@Wang-Yu-Qing did you find any solution for assigning weights to classes or how to handle imbalance in data for object detection. I am new to object detection, you help will be much appreciated.
