### ISSUE TITLE
Unable to see predictions on test data.

### ISSUE THREAD

**Issue by Mayuresh999** [ultralytics/ultralytics#236]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I have tried to train on a custom dataset where training is completed successfully. The detection/prediction script works correctly as well but cannot see the images after detection has completed. There are bunch of empty folders created after  running the script with the name of images. Same issue with videos.

Here is a screenshot of the issue ..
![Untitled](https://user-images.githubusercontent.com/95702726/211754192-e60cbfa3-d255-4cba-9dbb-d4477db309cb.png)

### Environment

Environment : Google Colab

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@Mayuresh999 to view the opencv frame of predictions, you need to pass `show=True` in both cli or python interface..
To save the predictions you need to pass `save=True`. Btw colab doesn't support imshow() so you probably won't be able to see the opencv outputs. For that you'll need to run on your local system

**Comment by glenn-jocher** [comment]
@Mayuresh999 your issue may be resolved now in PR #256 that I just merged. Please update your code and let us know if this resolves the issue for you, thank you!
