### ISSUE TITLE
Capturing Yolo8 Terminal Messages

### ISSUE THREAD

**Issue by ocnuybear** [ultralytics/ultralytics#2360]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have this code:
`import cv2
import time
import sys
import logging
from pathlib import Path
from ultralytics import YOLO

def main():
  
    model = YOLO('yolov8n-face.pt')

    # Set video source (0 for default camera, or path to a video file)
    video_path = 0
    # Create a VideoCapture object
    cap = cv2.VideoCapture(video_path)

    # Initialize the time variable
    prev_inference_time = 0

    # Loop through video frames
    while cap.isOpened():
        # Read a frame
        success, frame = cap.read()
        # Resize the frame
        frame = resize_frame(frame, width=400, height=300)
        # Break the loop if the end of the video is reached
        if not success:
            break

        # Get the current time
        current_time = time.time()

        # Check if at least 0.5 seconds have passed since the last inference
        if current_time - prev_inference_time >= 0.5:
            # Run YOLOv8 inference
            results = model(frame)

            # Visualize results on the frame
            for result in results:
                annotated_frame = result.plot()
                # Display the annotated frame using cv2.imshow
                cv2.imshow("YOLOv8 Inference", annotated_frame)

            # Update the previous inference time
            prev_inference_time = current_time
        else:
            # Display the unannotated frame
            cv2.imshow("YOLOv8 Inference", frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break

    # Release the video capture object and close the display window
    cap.release()
    cv2.destroyAllWindows()

def resize_frame(frame, width, height):
    # Resize the frame to the specified dimensions
    return cv2.resize(frame, (width, height))

if __name__ == "__main__":
    main()
`

And it outputs this in the terminal:
`0: 480x640 1 face, 148.8ms
Speed: 5.3ms preprocess, 148.8ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)`
How can I capture this messages using python, I have tried debug logging, stdout, but nothing works, please advise?

**Comment by glenn-jocher** [comment]
Hello @ocnuybear, 

To capture the messages that are printed to the terminal while running inference with YOLOv8, you can redirect the standard output to a file or to a variable using the `sys` module. You can use the `sys.stdout` attribute to redirect the standard output to a variable, and then print that variable at the end of the script.

Here is an example:

```python
import cv2
import time
import sys
from pathlib import Path
from ultralytics import YOLO

# Redirect standard output to a variable
sys.stdout = open('output.txt', 'w')

# Initialize YOLOv8 model
model = YOLO('yolov8n-face.pt')

# Define video source
video_path = 0
cap = cv2.VideoCapture(video_path)

# Loop through video frames
while True:
    success, frame = cap.read()
    if not success:
        break

    # Run inference
    results = model(frame)

    # Print results
    print(results)

# Close the standard output file
sys.stdout.close()

# Print the captured messages
with open('output.txt', 'r') as f:
    print(f.read())
```

In this example, the standard output is redirected to a file called `output.txt`. After running the script, you can open the file and see all messages that were printed to the terminal during inference.

I hope this helps! Let me know if you have any other questions.

**Comment by ocnuybear** [comment]
I also took a different approach and traced back these terminal messages to predictor.py in the code `LOGGER.info(f'{s}{self.dt[1].dt * 1E3:.1f}ms')` where s is the amount of faces detected using this code: 

`            # Run YOLOv8 inference
            results = model(frame)

            # Call write_results() to get the s value
            p = Path('dummy_path')  # Create a dummy path object
            im = frame  # The preprocessed image is the same as the original frame in this case
            im0 = frame.copy()  # Create a copy of the frame for visualization
            s = model.predictor.write_results(0, results, (p, im, im0))

            # Print the s value
            print(s)`

**Comment by glenn-jocher** [comment]
@ocnuybear hello!

The messages you see in the terminal during YOLOv8 inference are logged by the `LOGGER` object in the `predictor.py` module. These messages can be captured and saved to a file or printed in the console using the `logging` module available in Python.

To capture the amount of faces detected, you can call `write_results()` method of the predictor to obtain a tensor of detections and then extract the length of that tensor. In the following code snippet, `s` represents the number of faces detected:

```python
# Run YOLOv8 inference
results = model(frame)

# Call write_results() to get the s value
p = Path('dummy_path')  # Create a dummy path object
im = frame  # The preprocessed image is the same as the original frame in this case
im0 = frame.copy()  # Create a copy of the frame for visualization
s = model.predictor.write_results(0, results, (p, im, im0))

# Print the s value
print(s)
```

Please note that `write_results()` method expects a specific input format. Please refer to documentation for more details.

I hope this helps! Let me know if you have any other questions.

**Comment by najwabelarbi2** [comment]
> image_path



> Hello @ocnuybear,
> 
> To capture the messages that are printed to the terminal while running inference with YOLOv8, you can redirect the standard output to a file or to a variable using the `sys` module. You can use the `sys.stdout` attribute to redirect the standard output to a variable, and then print that variable at the end of the script.
> 
> Here is an example:
> 
> ```python
> import cv2
> import time
> import sys
> from pathlib import Path
> from ultralytics import YOLO
> 
> # Redirect standard output to a variable
> sys.stdout = open('output.txt', 'w')
> 
> # Initialize YOLOv8 model
> model = YOLO('yolov8n-face.pt')
> 
> # Define video source
> video_path = 0
> cap = cv2.VideoCapture(video_path)
> 
> # Loop through video frames
> while True:
>     success, frame = cap.read()
>     if not success:
>         break
> 
>     # Run inference
>     results = model(frame)
> 
>     # Print results
>     print(results)
> 
> # Close the standard output file
> sys.stdout.close()
> 
> # Print the captured messages
> with open('output.txt', 'r') as f:
>     print(f.read())
> ```
> 
> In this example, the standard output is redirected to a file called `output.txt`. After running the script, you can open the file and see all messages that were printed to the terminal during inference.
> 
> I hope this helps! Let me know if you have any other questions.

Hello, how can I only capture the inference time and write it in another file? thank you in advance

**Comment by glenn-jocher** [comment]
Hello @najwabelarbi2,

To save only the inference time to a separate file, you can modify the model to store the elapsed time for each inference instead of sending it to standard output. The elapsed inference time is typically calculated within the inference method of the model. After each inference, instead of logging or printing this time, you can append it to a list or similar data structure.

At the end of your script, you can then write the contents of this list to a file. This will provide you with a file containing the inference times for each frame processed by your model. Please ensure these modifications follow the guidelines and licensing of the YOLOv8 repository. 

Let me know if you have any other questions!

**Comment by Phantasiie** [comment]
> Hello @najwabelarbi2,
> 
> To save only the inference time to a separate file, you can modify the model to store the elapsed time for each inference instead of sending it to standard output. The elapsed inference time is typically calculated within the inference method of the model. After each inference, instead of logging or printing this time, you can append it to a list or similar data structure.
> 
> At the end of your script, you can then write the contents of this list to a file. This will provide you with a file containing the inference times for each frame processed by your model. Please ensure these modifications follow the guidelines and licensing of the YOLOv8 repository.
> 
> Let me know if you have any other questions!

Hey, I am looking to use the inference time as reference to add a simple FPS counter by dividing 1000 by it. I have tried to implement using cv2, but am having trouble adding it on top of the YOLO live video output. I guess I am new to this and any help would be greatly appreciated! Thanks

**Comment by glenn-jocher** [comment]
@Phantasiie hello,

In order to add a FPS (frames-per-second) counter, you would need to modify the live video output in your script. This can be achieved by utilizing the inference time that you've already calculated. 

First, calculate the frames-per-second by dividing 1000 by the inference time for a single frame. This gives you the number of frames that can be processed in one second.

Then, you could use the OpenCV function `cv2.putText()` to overlay this FPS value onto your video. This function allows you to display text on an image or a frame of a video. You would call this function once for each frame after it has been processed but before it is displayed.

Please reach out if you have any additional questions. I'm here to assist you!

**Comment by Phantasiie** [comment]
@glenn-jocher 
How would one call the inference time to be able to use it in the FPS calculation?

**Comment by glenn-jocher** [comment]
@Phantasiie hello, 

To incorporate the inference time in your FPS calculation, you can access it directly from the `results` object returned by the model inference in YOLOv8. This object encapsulates all results from running the model on an image, including inference time.

The inference time is located under the `results.speed['inference']` attribute. This attribute stores the amount of time in seconds it took for the model to perform inference on the image. 

You can use this time to calculate FPS. For instance, if you extract the inference time and find that it's 0.05 seconds (or 50 milliseconds), then you can calculate FPS as `1 / 0.05 = 20 FPS`.

Keep in mind that this FPS value represents the theoretical maximum FPS based solely on the model's inference time. In a real-world application, additional factors such as image pre-processing, post-processing and rendering time would further reduce the actual FPS. 

If you aim to display the FPS on the video output, this value should be calculated and updated for each frame. 

Please feel free to reply if you have any further questions.

**Comment by Phantasiie** [comment]
@glenn-jocher 
Thanks a lot for the help! I enjoy that you reply and help people, even when they ask simple questions. 
I ended up finding somewhere online that you can `import time`, and then inside the video loop you can set current time as `time.time()`, use FPS as 1/(current time-previous time) and then set previous time as current time. You can then draw it using `cv2.putText` like you previously showed.
Even though you answered my previous question and I didn't use your answer, I do appreciate the response. It helped me learn something :)

**Comment by glenn-jocher** [comment]
Hello @Phantasiie,

Thank you for your kind words! I'm glad to hear that you found a solution that works for you. Your approach with using the `time` module to track the time before and after inference is indeed a common and practical way to calculate and display FPS.

Remember, the learning process often involves exploring various approaches, so there's a lot of value in the journey itself. Always feel free to share your experiences and your learnings here, it may help other community members who are looking for similar answers.

Keep up the great work, and never hesitate to reach out if you have more questions. Happy coding!
