### ISSUE TITLE
issue in running inference with onnx and opencv

### ISSUE THREAD

**Issue by kmlrohin1** [ultralytics/ultralytics#2363]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

![image](https://user-images.githubusercontent.com/131166922/235671035-abfe7c0b-2dcf-4229-8f7a-5e72904763e2.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @kmlrohin1, thank you for reaching out regarding the YOLOv8 Export component. From the provided image, it seems that there is an issue with the exported model. To properly diagnose this issue, we would need more information on the environment and the minimal reproducible examples.

For the environment information, could you provide details on the version of PyTorch used in the original training and the version of PyTorch used during the export?

For the minimal reproducible examples, could you provide more information on the dataset used along with the script used for exporting the model?

Once we have more information, we will be better equipped to help identify and resolve the issue you are experiencing. Thank you for your willingness to help submit a PR, and we look forward to assisting you further.
