### ISSUE TITLE
Why not directly use the 'batched_nms' function from torchvision?

### ISSUE THREAD

**Issue by calmisential** [ultralytics/ultralytics#2365]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thanks for your great work! In the 'non_max_suppression' function, there are codes:
```       
c = x[:, 5:6] * (0 if agnostic else max_wh)  # classes
boxes, scores = x[:, :4] + c, x[:, 4]  # boxes (offset by class), scores
i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
```
which means doing batched nms on the boxes. However,  I think these codes can be simplified by using the 'batched_nms' function from torchvision.
If you think my idea works, I can submit a PR.

**Comment by glenn-jocher** [comment]
@calmisential this is a great question! In the past when I've profiled the batched_nms speeds vs the current implementation the batched_nms speeds were actually slower (yes I know it sounds strange), so I wasn't able to use it without inference times increasing. 

Please do an independent assessment of this yourself, as much time has past since my tests (about a year). If you find that batched_nms improves speeds please submit a PR, thank you!

**Comment by stastatun** [comment]
@glenn-jocher  Doesn't sound strange at all! Looking at the torchvision implementation of [batched_nms](https://github.com/pytorch/vision/blob/main/torchvision/ops/boxes.py#L78), it does the same thing, but with extra casting, conditionals, and a `torch.max` call.
```python
def _batched_nms_coordinate_trick(
    boxes: Tensor,
    scores: Tensor,
    idxs: Tensor,
    iou_threshold: float,
) -> Tensor:
    if boxes.numel() == 0:
        return torch.empty((0,), dtype=torch.int64, device=boxes.device)
    max_coordinate = boxes.max()
    offsets = idxs.to(boxes) * (max_coordinate + torch.tensor(1).to(boxes))
    boxes_for_nms = boxes + offsets[:, None]
    keep = nms(boxes_for_nms, scores, iou_threshold)
    return keep
```
Torchvisions version has the benefit of being more robust to image size, and performing better with a large amount (>20k) of bounding boxes. But seeing as running inference on images larger than 7680x7680 is pretty unlikely, and number of bounding boxes passed to `nms` is capped at 30k by default, it makes sense to drop the extra operations to boost performance.

**Comment by glenn-jocher** [comment]
Thank you for following up, @stastatun. That's a fair point you bring up, and given the assumptions around image size and number of bounding boxes, it does seem like removing the extra operations makes sense and could boost performance. If you think there's a significant improvement to be had using `batched_nms`, please feel free to submit a PR. Thanks again for your contribution to the YOLOv8 community!
