### ISSUE TITLE
Batch tracking with persist parameter gives wrong detections and tracking

### ISSUE THREAD

**Issue by KerolosAtef** [ultralytics/ultralytics#2367]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why when using model.track(batch_frames,persist=True) the model can't detect or track the objects correctly, but when batch_size=1 the results are valid? 

Snapshot of the code is :
![image](https://user-images.githubusercontent.com/26412108/235741780-10cbfd5c-6cbb-4ff8-a341-7c353f644d04.png)

**Comment by glenn-jocher** [comment]
Thank you for sharing your question with the YOLOv8 community, @KerolosAtef-1994! When you're using a batch size greater than one and set the `persist` parameter to `True`, the YOLOv8 tracker will preserve the ID of previously detected objects and re-use them in subsequent frames. If the model detects a different object than before, it will assign the new object a new ID. This may cause inaccuracies in tracking if multiple similar objects are present in the batch, or if objects are occluded or overlap between frames.

When using a batch size of one, the model only needs to track a single object at a time, so it can more accurately assign unique IDs and track them over time.

To improve tracking accuracy with a batch size greater than one, you may want to try changing the tracking threshold (`conf_thres`) or the tracking IOU threshold (`iou_thres`) to adjust the sensitivity of the tracker. You could also try adjusting the object detection parameters to increase the confidence level or decrease the NMS threshold to help prevent over-tracking. Additionally, you may want to experiment with using a different tracker type, such as Deep SORT, or consider post-processing the tracked objects to filter out inaccuracies.

I hope this information helps you with your tracking tasks!

**Comment by KerolosAtef** [comment]
Thank you for your reply ,but changing the parameters doesn't solve the
problem with me.
Could you look into my pull request i fixed this bug.

**Comment by glenn-jocher** [comment]
@KerolosAtef, thank you for addressing the tracking issue you were experiencing and submitting a pull request to fix it! We appreciate your contribution to the YOLOv8 community. We will review your pull request as soon as possible and provide feedback. 

Please let us know if you have any other questions or issues in the meantime. We are always here to help!
