### ISSUE TITLE
Classify training doesn't work out-of-the-box

### ISSUE THREAD

**Issue by TomDeBacker** [ultralytics/ultralytics#237]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

[user@laptop ultralytics]$ yolo task=classify mode=train model=yolov8m-cls.pt device=cpu

```
yolo/engine/trainer: task=classify, mode=train, model=yolov8m-cls.pt, data=mnist160, epochs=100, patience=50, batch=16, imgsz=640, save=True, cache=False, device=cpu, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=False, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, retina_masks=False, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.1, lrf=0.01, momentum=0.937, weight_decay=5e-05, warmup_epochs=0.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.1, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, v5loader=False, save_dir=runs/classify/train
Ultralytics YOLOv8.0.2 🚀 Python-3.8.13 torch-1.13.1+cu117 CPU
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8m-cls.pt to yolov8m-cls.pt...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32.7M/32.7M [00:03<00:00, 8.62MB/s]
optimizer: SGD(lr=0.1) with parameter groups 38 weight(decay=0.0), 39 weight(decay=5e-05), 39 bias
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to runs/classify/train
Starting training for 100 epochs...

      Epoch    GPU_mem       loss  Instances       Size
  0%|          | 0/5 [00:03<?, ?it/s]
Error executing job with overrides: ['task=classify', 'mode=train', 'model=yolov8m-cls.pt', 'device=cpu']
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/cli.py", line 52, in cli
    func(cfg)
  File "/home/user/.local/lib/python3.8/site-packages/hydra/main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/v8/classify/train.py", line 145, in train
    trainer.train()
  File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 177, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/home/user/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 300, in _do_train
    self.scaler.scale(self.loss).backward()
  File "/home/user/.local/lib/python3.8/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/user/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

Am I missing something? 

### Environment

- RHEL 8
- Python 3.8

### Minimal Reproducible Example

yolo task=classify mode=train model=yolov8m-cls.pt device=cpu

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@TomDeBacker we'll look into this today and get back to you.. Thanks for your pateince!
@glenn-jocher did something change yesterday? I don't think you saw this error in your testing

**Comment by TomDeBacker** [comment]
> @TomDeBacker we'll look into this today and get back to you.. Thanks for your pateince! @glenn-jocher did something change yesterday? I don't think you saw this error in your testing

Sidenote

`releases/download/v0.0.0 `

v0.0.0 strikes me as odd

**Comment by AyushExel** [comment]
@TomDeBacker yes those are github assets version.. We haven't generated a release yet. We'll soon set them up to match our framework version. Good catch!

**Comment by TomDeBacker** [comment]
@AyushExel Any update?

**Comment by aus10powell** [comment]
Hi,

I've come across the above issues several times. Is there anything that solves this?

```python
  File "temp_training.py", line 116, in <module>
    main()
  File "temp_training.py", line 91, in main
    results = model.train(
  File "/Users/aus10powell/Documents/Projects/MIT-Fishery-Counter/code/notebooks/venv/lib/python3.8/site-packages/ultralytics/engine/model.py", line 377, in train
    self.trainer.train()
  File "/Users/aus10powell/Documents/Projects/MIT-Fishery-Counter/code/notebooks/venv/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/Users/aus10powell/Documents/Projects/MIT-Fishery-Counter/code/notebooks/venv/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 339, in _do_train
    self.scaler.scale(self.loss).backward()
  File "/Users/aus10powell/Documents/Projects/MIT-Fishery-Counter/code/notebooks/venv/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/Users/aus10powell/Documents/Projects/MIT-Fishery-Counter/code/notebooks/venv/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
```

**Comment by glenn-jocher** [comment]
@aus10powell hi there,

The error `'element 0 of tensors does not require grad and does not have a grad_fn'` usually occurs when you are trying to backpropagate through a tensor that doesn't have `requires_grad=True`. 

In the context of YOLOv8, it appears that the loss function is trying to perform a backward operation on a tensor that does not have its gradients computed. 

With YOLOv8's PyTorch implementation, the `requires_grad` attribute should be automatically set to `True` for all learnable parameters of the model during training. If this is not happening, it might warrant a closer examination of the model configuration or the data inputs. 

Make sure that the input data and the model are compatible and there are no inconsistencies. 

Hope this helps in resolving the issue.

**Comment by aus10powell** [comment]
@glenn-jocher thanks for the response. I'm using outputs from the roboflow for yolov8 which has worked for many models in the past. I haven't changed the configurations since the model ran correctly last time. But it does seem to work if I change virtual environment. Does the match your expectations?

**Comment by aus10powell** [comment]
@glenn-jocher I just noticed that the error occurs consistently if I set epochs > 100. It immediately stops if epochs <= 100

**Comment by glenn-jocher** [comment]
Hi @aus10powell, thank you for sharing your observations.

It could be that you're running out of resources when setting epochs > 100. Training deep learning models over numerous epochs will require more computational power, hence it might be checking your available resources such as GPU memory or RAM.

However, this is quite peculiar because the number of workers in the dataloader and the batch size, which directly influence the resource consumption, are kept constant across epochs. Maybe there's a memory leak somewhere or some resources are not being freed properly.

I would suggest monitoring your system's resources whilst training the model to see if you are indeed running out of memory when setting epochs > 100. This would provide a clearer understanding of what's causing the error you're encountering.

I hope this helps, let us know if you have any other questions or updates!
