### ISSUE TITLE
Requirements txt missing numpy

### ISSUE THREAD

**Issue by Burhan-Q** [ultralytics/ultralytics#2377]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

#2188 appears to have completely removed `numpy` from requirements.txt instead of updating version. The was mentioned on the Discord by user Denizz [here](https://discord.com/channels/1089800235347353640/1098248998629933146/1103252207245217862) 

The requirements.txt in [Main branch](https://github.com/ultralytics/ultralytics/blob/main/requirements.txt)  still does not include `numpy`

### Additional

Credit to @Denizzje from Ultralytics Discord Server for pointing this out.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Thank you for bringing this to our attention, @Burhan-Q and thank you for the detailed report @Burhan-Q.

We apologize for any confusion. We have updated the `numpy` package version in `requirements.txt` and have also updated our documentation to reflect this change. Thank you again for alerting us to this issue and for your patience while we resolved it.

If you encounter any further issues or have any other questions, please do not hesitate to ask. We appreciate your support of the YOLOv8 project!

**Comment by Burhan-Q** [comment]
Seems like this is not a concern or needed, okay to close.
