### ISSUE TITLE
single class training

### ISSUE THREAD

**Issue by AryaAftab** [ultralytics/ultralytics#238]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I get some error when training yolov8 with single class flagg.

![image](https://user-images.githubusercontent.com/30603302/211758250-2ee71ae1-1270-4d10-a368-1b1076fd3aa5.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@AryaAftab can you try using `v5Loader=True` flag and see if the problem still exists? Thanks!

**Comment by AryaAftab** [comment]
Thanks for your fast response,
v5Loader flag doesn't exist, but v5loader is ok :)))

**Comment by AyushExel** [comment]
@AryaAftab okay perfect! we'll fix this issue soon so you don't have to use v5loader flag

**Comment by Laughing-q** [comment]
@AryaAftab BTW do you have empty labels in your datasets? I'm working on this and it seems there's something wrong with dealing with empty labels.

**Comment by AryaAftab** [comment]
@AyushExel Thanks,
@Laughing-q yeah, some images in my dataset haven't box.

**Comment by Laughing-q** [comment]
@AryaAftab hi this issue has fixed by this [https://github.com/ultralytics/ultralytics/pull/249](https://github.com/ultralytics/ultralytics/pull/249). :)
