### ISSUE TITLE
Request for YOLOv8 Code for Generating Separate Text Files for Object Detection/Prediction on Multiple Images in a Folder

### ISSUE THREAD

**Issue by shubham001official** [ultralytics/ultralytics#2384]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am writing to request with regards to obtaining Python code for object detection/prediction on multiple images in a folder using YOLOv8. I am currently searching for some related articles/tutorials, but I cannot seem to find a solution for my problem.

Specifically, I am looking for YOLOv8 code that will generate a separate text file for each image in the folder. The text file should contain the name of the class that is found in that particular image and its count. For instance, if the images are of vehicles, each text file should contain data for the corresponding image, such as,

{"car":10, "bike":15}

I want to clarify that my requirement is to have individual text files generated for each image in the folder, and not a single file that contains the data of all images.

If it is possible, could you please provide me with the necessary YOLOv8 code to accomplish this task? I appreciate any help you can offer and thank you in advance for your time.

### Additional

i have received this answer prior. but i can't code it !!

hi, to save the count of classes found in a particular image in a text file, you can use the yolo.run(img) method to detect objects in the image, then access the returned Tensor objects that report the predicted class_id, class_name, and the coordinates of the bounding box of each object. In order to output the counts to a txt file, you could create a dictionary to store the counts for each class and then iterate over the detected objects, incrementing the count for each class in the dictionary, before writing the counts to a file. Let us know if you need further assistance!

**Comment by glenn-jocher** [comment]
@shubham001official hello! I'm glad that you've reached out to us for help with your task. To save the count of classes found in each image to a separate text file, you can use the yolo.run(img) method to detect objects in each image, and then you would create a dictionary to store the counts for each class in that image. Next, you would iterate over the detected objects, incrementing the count for each class in the dictionary. Finally, you can write the counts to a separate text file for each image. This can be done using Python's file IO functions, where you would open a new file for each image and write the dictionary data to it. 

I hope that helps! If you need any further help or clarification, please let me know and I'd be happy to assist you.
