### ISSUE TITLE
where to put conf(confidence) value in Python script?

### ISSUE THREAD

**Issue by rgund26** [ultralytics/ultralytics#2397]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Could you please tell where to put "conf" value in python script while using webcam on local machine in realtime condition?

**Comment by Laughing-q** [comment]
@rgund26 `model.predict(conf=0.4)`.
