### ISSUE TITLE
Confidence score is >1 while predicting with Int8 TFlite model

### ISSUE THREAD

**Issue by Prakash-Reddy-6** [ultralytics/ultralytics#2401]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

Hi, I exported yolov8n model to int8 tflite model using the below script. While I am predicting with _yolov8n_full_integer_quant.tflite_ I am getting a confidence score >1. Which it should not be.  Please find the snippets which I used for exporting and predicting.
Thanks

![bus](https://user-images.githubusercontent.com/99396741/236147085-51ae804a-5735-4c9b-9ddb-cea605556bb9.jpg)

### Minimal Reproducible Example

```python
from ultralytics import YOLO

model = YOLO("yolov8n.pt")  
model.export(format="tflite", imgsz = 320, int8 = True)
``` 
```python
from ultralytics import YOLO

model = YOLO("yolov8n_saved_model/yolov8n_full_integer_quant.tflite")
model.predict(source="ultralytics/assets/bus.jpg", imgsz = 320, save=True,  show_conf = True)
``` 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi @Prakash-Reddy-6, thank you for reporting this issue. It appears that your exported tflite model is producing confidence scores greater than 1, which is unexpected behavior. There could be several reasons for this issue, including data preprocessing, model architecture, or other factors. 

To better assist you, can you provide us with more information about your environment setup? Specifically, can you let us know what version of TensorFlow you are using, and what device you are running the model on? 

Additionally, have you tried running the same model with integer quantization disabled to see if the confidence levels are being calculated correctly? 

We appreciate your help in providing any additional information you can so we can better diagnose this issue. Thank you!

**Comment by Prakash-Reddy-6** [comment]
Hi @glenn-jocher ,

I tried the YOLOv8 tutorial on a Colab instance with the following specifications: Python-3.10.11, torch-2.0.0+cu118, CUDA:0 (Tesla T4, 15102MiB), and TensorFlow version 2.12.0.

I used the YOLOv8 Nano model from the hub for exporting to TFLite. I disabled int8 and checked with a float32 model. It worked, and the output tensor matched the PyTorch model.

I also conducted another experiment where I used a 640 image size during the export. However, with the int8 models, I did not get any predictions, while the float32 model worked fine.

I hope this helps you understand the issue.

```shell
yolo export model=yolov8n.pt format=tflite int8=True imgsz=320
```  
```shell
yolo predict model=/content/yolov8n_saved_model/yolov8n_integer_quant.tflite source='https://ultralytics.com/images/bus.jpg'  imgsz=320
```

**Comment by glenn-jocher** [comment]
Hi @Prakash-Reddy-6, 

Thanks for your message and experimentation on YOLOv8. 

It seems like you have exported a YOLOv8 model to TFLite format with integer quantization enabled and int8=True over an image size of 320 and checked the model with a float32 model, which worked fine.

Regarding your second experiment, you used an image size of 640 during the export and int8 quantization was not working correctly. This behavior could be due to the memory capacity limitations of the int8 quantization format, which might have caused the model not to work with 640 image sizes.

Could you try to export the model using the float32 data format instead of int8 to see if this resolves the issue? Additionally, you can reduce the image size to a lower value to see if the quantization works correctly in this scenario.

Please let us know if you have further questions, and we'll be happy to assist you.

**Comment by Prakash-Reddy-6** [comment]
HI @glenn-jocher,

For both 320 and 640 image sizes float32 is working fine.

But with int8 model with 320 size, I am getting confidence score >1. Whereas with 640 int8 there are no detections even till 0.01 conf.

**Comment by glenn-jocher** [comment]
Hi @Prakash-Reddy-6-6,

Thanks for getting back to us with the results of your experiments. Based on your observations, it appears that the cause of this issue could be the capacity limitations of the int8 quantization format for image sizes greater than 320.

Our recommendation would be to avoid using int8 quantization when working with larger image sizes, as this might cause the model to provide suboptimal performance. Instead, you can use the float32 data format to achieve more accurate and reliable results when working with larger image sizes.

We hope this information helps, and let us know if you have any further questions.
