### ISSUE TITLE
how to deal with object detection in high resolution images with small objects

### ISSUE THREAD

**Issue by IAGirl-dev** [ultralytics/ultralytics#2402]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hello, I am using yolov8 to realise an object detection on helmet, however my images have a high resolution (2664x1998).
When I run the object detection on all the image no object is detected, but when I slice my image into small images I detection objects on each sub image.
is there a way to realise this automatically or a way to improuve the model so that even on a high resolution image very small objects as a helmet be detected please ?

**Comment by chenzx2** [comment]
you need to cut the srcImg,and train it. predict like this
                    img_reized_temp = []
                    boxes_temp = []
                    classes_temp = []
                    scores_temp = []
                    cutHight = 2
                    cutWidth = 3
                    h = int(height / cutHight)
                    w = int(width / cutWidth)
                    for i in range(cutHight):
                        for j in range(cutWidth):
                            resultImg = frame[i * h:(i + 1) * h, j * w:(j + 1) * w]
                            if (self.isRK3588):
                                img_reized_temp, boxes_temp, classes_temp, scores_temp = rknnLite.infer(resultImg)
                            else:
                                img_reized_temp, boxes_temp, classes_temp, scores_temp = intelOpenVino.infer(resultImg)
                            # ----------增强模式数据拼接----------
                            if( scores_temp is not None and len(scores_temp) >= 0):
                                boxes_temp = np.array(boxes_temp)

                                y = np.copy(boxes_temp)
                                y[:, 0] = ( boxes_temp[:, 0]  + 640*j ) / cutWidth #x1
                                y[:, 1] = ( boxes_temp[:, 1]  + 640*i ) / cutHight #y1
                                y[:, 2] = ( boxes_temp[:, 2]  + 640*j ) / cutWidth #x2
                                y[:, 3] = ( boxes_temp[:, 3]  + 640*i ) / cutHight #y2
                                boxes_temp1 = y

                                boxes.extend(boxes_temp1)
                                classes.extend(classes_temp)
                                scores.extend(scores_temp)

**Comment by chenzx2** [comment]
you can cut the srcImg,and train it. predict like this

**Comment by glenn-jocher** [comment]
Hi @chenzx2. Thank you for your question. It is possible to break down a high-resolution image into several small images and perform detection on each. However, this is not automatic and requires some additional coding effort to implement. 

In the code that you shared, the image is divided into small rectangular parts, and object detection is performed on each. The output boxes and scores of each of the results are then concatenated as the final result. 

Another way to improve object detection on high-resolution images is to adjust the hyperparameters of the YOLOv8 model. You can try increasing the input resolution, decreasing the image augmentation or using a smaller grid size. All these options help the model perceive small objects more effectively. 

Please let me know if you have any more questions.

**Comment by chenzx2** [comment]
Maybe both is a good choice. Small GPU memery can train yolov8 by cutting the srcImgs

**Comment by chenzx2** [comment]
> Hi @chenzx2. Thank you for your question. It is possible to break down a high-resolution image into several small images and perform detection on each. However, this is not automatic and requires some additional coding effort to implement.
> 
> In the code that you shared, the image is divided into small rectangular parts, and object detection is performed on each. The output boxes and scores of each of the results are then concatenated as the final result.
> 
> Another way to improve object detection on high-resolution images is to adjust the hyperparameters of the YOLOv8 model. You can try increasing the input resolution, decreasing the image augmentation or using a smaller grid size. All these options help the model perceive small objects more effectively.
> 
> Please let me know if you have any more questions.

Thank you for the suggestion, I'm going to try it

**Comment by glenn-jocher** [comment]
You're welcome, @chenzx2! I'm glad I could help. Don't hesitate to reach out if you have any more questions or need further assistance. Good luck with your project!

**Comment by glenn-jocher** [comment]
Hi @IAGirl-dev, thank you for your question. 

Yes, it is possible to use tiled inference with YOLOv8 to perform segmentation on high-resolution images. Tiled inference involves breaking up the input image into smaller pieces and processing them separately. After processing these smaller images, the resulting segmented outputs are combined to obtain the final output for the full-size image. This approach helps to reduce memory limitations when dealing with high-resolution images.

To use tiled inference with YOLOv8, you need to modify the `inference` function in `yolov8.py` to accept tiled input images and perform segmentation on each tile. You can also implement a function to stitch the resulting tiles of segmentation back into a single output image. 

You would also need to ensure that your data pipeline splits your high-resolution images into tiles before passing them to YOLOv8 for inference.

I hope this helps. If you have any more questions, feel free to ask. Good luck with your project!

**Comment by jehan88** [comment]
@glenn-jocher how can i use   tiled inference could you please provide me the code or the link?

**Comment by glenn-jocher** [comment]
@jehan88 hello! Thank you for your question. To implement tiled inference in YOLOv8, you'll need to modify the `inference` function in the `yolov8.py` file. This involves:
- Breaking the input image into smaller tiles.
- Running the inference process on each tile individually.
- Combining the results from each tile to obtain the final output for the full-sized image.

You'll also want to implement a stitching function to combine the segmented outputs from each tile into a single output image. This way, you can maintain the quality of the segmentation across the entire high-resolution image.

Unfortunately, I cannot provide the specific code or a direct link to implement tiled inference. However, you can find code examples and tutorials for tiled inference in YOLOv8 by searching online or referring to relevant papers and articles. This will help you understand the necessary modifications and the stitching process.

I hope this guidance helps! If you have any further questions, please feel free to ask. Good luck with your project!

**Comment by iraadit** [comment]
FYI, SAHI can be used now: https://docs.ultralytics.com/guides/sahi-tiled-inference/

**Comment by glenn-jocher** [comment]
@iraadit hello there! Thank you for sharing the information about SAHI. It is always great to have different tools and resources available for various use cases.

For the YOLOv8 model, implementing tiled inference would involve breaking the larger input image into smaller "tiles" or sections, performing prediction on these smaller sections individually, and then aggregating the results back to obtain the final prediction for the complete image.

This can be particularly beneficial when dealing with high-resolution images with small objects, as it can help manage memory constraints and potentially improve object detection performance.

However, please note that adding this functionality would require modifying the inference process within the YOLOv8 model's code. If you are considering integrating SAHI with YOLOv8, consider the steps I mentioned and how it aligns with your current workflow.

Once again, thank you for your contribution to the discussion, and feel free to share any more suggestions or inquiries you may have. Your input is greatly appreciated!

**Comment by iraadit** [comment]
I understand the use of chatgpt to improve your answering speed, but you should at least read these answers before posting them.

SAHI is doing exactly that, ready to use and using yolov8 (or other networks), without any change required on yolov8, as advertised on your own (Ultralytics's) website, from where the link I posted is coming from.

Here is a Google Colab using it with yolov5: https://colab.research.google.com/github/obss/sahi/blob/main/demo/inference_for_yolov5.ipynb

From SAHI's GitHub: https://github.com/obss/sahi

For yolov8, it suffices to follow the guide on your website (https://docs.ultralytics.com/guides/sahi-tiled-inference/). It would be easy to update the previously linked Google Colab from the content of the guide.

Thanks for the great work on yolo.

**Comment by glenn-jocher** [comment]
@iraadit hello, thank you for your gracious information and response! You're correct, SAHI can be used to implement tiled inference, even for high-resolution images, alongside YOLOv8 without the need to modify the YOLOv8 code base.

Essentially, SAHI provides an out-of-the-box solution to deal with tiling and stitched predictions, making it smoother to handle large images and small object detections. And you're right, there is ample material available in the Ultralytics documentation guide to help users leverage SAHI with YOLOv8.

I deeply apologize if my previous responses weren't specific enough or misleading. I really appreciate your input and am always here to assist the YOLOv8 community. It is contributions like yours that help us to extend and enhance the overall usability and user experience of YOLOv8. Once again, thank you for your valuable feedback and support for the project!

**Comment by NawoyaSarah** [comment]
> Hi @IAGirl-dev, thank you for your question.
> 
> Yes, it is possible to use tiled inference with YOLOv8 to perform segmentation on high-resolution images. Tiled inference involves breaking up the input image into smaller pieces and processing them separately. After processing these smaller images, the resulting segmented outputs are combined to obtain the final output for the full-size image. This approach helps to reduce memory limitations when dealing with high-resolution images.
> 
> To use tiled inference with YOLOv8, you need to modify the `inference` function in `yolov8.py` to accept tiled input images and perform segmentation on each tile. You can also implement a function to stitch the resulting tiles of segmentation back into a single output image.
> 
> You would also need to ensure that your data pipeline splits your high-resolution images into tiles before passing them to YOLOv8 for inference.
> 
> I hope this helps. If you have any more questions, feel free to ask. Good luck with your project!

@glenn-jocher Hello. where do i find the yolov8.py? its the same as the train.py?

**Comment by glenn-jocher** [comment]
Hello @NawoyaSarah! Apologies for the confusion earlier. There's no need to modify any files like `yolov8.py` or `train.py`. For tiled inference with YOLOv8, you can use the SAHI tool, which is designed to handle high-resolution images and small objects detection without any code changes to YOLOv8.

Please refer to the Ultralytics documentation guide on SAHI tiled inference for detailed instructions on how to set it up with YOLOv8. This will guide you through the process and help you get started with tiled inference right away.

If you have any further questions or need more assistance, feel free to reach out. Happy to help!

**Comment by jasonpp** [comment]
Nice,got it.

**Comment by namnh194** [comment]
Sahi and Ultralytics, grateful both of you :)

**Comment by glenn-jocher** [comment]
@namnh194 thank you for your kind words! The success is all thanks to the YOLO community and the Ultralytics team. If you have any questions, feel free to ask!

**Comment by berda-ak** [comment]
Hello, ı have a same problem but when ı want to use SAHI: WARNING - sahi.utils.coco -   Segmentation annotation for id 310 is skipped since RLE segmentation format is not supported.
is there any other tool that support RLE?
my project is in Cvat and my  model run with Ultralytics format.

**Comment by glenn-jocher** [comment]
Thank you for your kind words! The success of these tools is thanks to the dedicated YOLO community and the Ultralytics team. If you have any questions, feel free to ask!

**Comment by glenn-jocher** [comment]
Thank you for your kind words! We're glad to hear you're finding both SAHI and Ultralytics helpful. If you have any questions, feel free to ask!

**Comment by glenn-jocher** [comment]
Thank you for your kind words! We're glad to hear you're finding SAHI and Ultralytics helpful. If you have any questions or need further assistance, feel free to ask.
