### ISSUE TITLE
raise FileNotFoundError(f'{p} does not exist'

### ISSUE THREAD

**Issue by ZealandNew2023** [ultralytics/ultralytics#2403]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I passed the binary read out by cv2. imread() into the source parameter of the predict function and reported 'raise FileNotFoundError (f' {p} does not exist '). I have reviewed the official documentation（ https://docs.ultralytics.com/modes/predict/#image -And video formats), which shows support for passing binaries, I don't understand why we need to determine whether the path exists.The following is the error code:

Traceback (most recent call last):
  File "/home/miniconda/brain/GTUtility/ai_control/pipeline/predict_pipe.py", line 186, in detect_img
    bboxes = self.detect_sub_img(box=box, img=img, WIDTH=WIDTH, HEIGHT=HEIGHT)
  File "/home/miniconda/brain/GTUtility/ai_control/pipeline/predict_pipe.py", line 73, in detect_sub_img
    results = self.model.detect(img)
  File "/home/miniconda/brain/GTAI/yolo/yolov8_pipe.py", line 28, in detect
    conf=self.model_config.thresh.thresh_model)
  File "/home/miniconda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/miniconda/lib/python3.7/site-packages/ultralytics/yolo/engine/model.py", line 130, in predict
    predictor.setup(model=self.model, source=source, return_outputs=return_outputs)
  File "/home/miniconda/lib/python3.7/site-packages/ultralytics/yolo/engine/predictor.py", line 149, in setup
    vid_stride=self.args.vid_stride)
  File "/home/miniconda/lib/python3.7/site-packages/ultralytics/yolo/data/dataloaders/stream_loaders.py", line 171, in __init__
    raise FileNotFoundError(f'{p} does not exist')
FileNotFoundError: /home/miniconda/brain/test/ai_client_test/[[[122 148 172]

### Environment

Ultralytics YOLOv8.0.6  
Python-3.7.9 
torch-1.10.1
torchvision0.11.2
cuda10.1   
NVIDIA TITAN Xp 12288MiB 
OS: Centos7.9

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by stastatun** [comment]
Hi,
The predictor accepts inputs of type `numpy.ndarray` - which is what the python version of `cv2.imread` returns. 
```python
# This works
array = cv2.imread("image.jpg")
output = model(source=array)
```
It looks like your error stems from the array being passed as string, so most likely you're converting the `numpy.ndarray` to a string at some point in your pipeline?

**Comment by TIBREWA** [comment]
Hey @ZealandNew2023 did you fix the file not found error in ultralytics if yes please tell me how to fix it

**Comment by glenn-jocher** [comment]
Hi @TIBREWA,

The "FileNotFoundError" you encountered in YOLOv8 could be due to passing a string (interpreted as a filename) instead of a numpy array as the "source" parameter in the predict function.

To resolve this issue, make sure you are passing a numpy array (the output of `cv2.imread`) as the source parameter when calling the predict function, rather than a string representing a file path.

If you have further questions or need additional assistance, please let me know.

**Comment by chandumatrix004** [comment]
@glenn-jocher I don't think anybody here is able to understand the problem even. The yolov8 model is considering the frame as a numpy array but then it prints that that specific array (file) does not exist. I'm totally frustrated of this and nobody in the whole world is able to tell a resolution to this problem. I have checked each and every forum for this issue. 
**Below is the code snippet:**
`import numpy as np
import datetime
import cv2

from ultralytics import YOLO

from helper import create_video_writer
from collections import deque

from deep_sort.deep_sort.tracker import Tracker
from deep_sort.deep_sort import nn_matching
from deep_sort.deep_sort.detection import Detection
from deep_sort.tools import generate_detections as gdet

# define some parameters
conf_threshold = 0.5
max_cosine_distance = 0.4
nn_budget = None
points = [deque(maxlen=32) for _ in range(1000)] # list of deques to store the points
counter_A = 0
counter_B = 0
counter_C = 0

# Initialize the video capture and the video writer objects
video_cap = cv2.VideoCapture("1.mp4")

writer = create_video_writer(video_cap, "output.mp4")
# Initialize the YOLOv8 model using the default weights
model = YOLO("yolov8n.pt")
#print(model)
#print(video_cap.read())
#model.predict(source="1.mp4", show=True)
# loop over the frames

# Initialize the deep sort tracker
model_filename = "config/mars-small128.pb"
encoder = gdet.create_box_encoder(model_filename, batch_size=1)
metric = nn_matching.NearestNeighborDistanceMetric(
    "cosine", max_cosine_distance, nn_budget)
tracker = Tracker(metric)

# load the COCO class labels the YOLO model was trained on
classes_path = "config/coco.names"
with open(classes_path, "r") as f:
    class_names = f.read().strip().split("\n")

# create a list of random colors to represent each class
np.random.seed(42)  # to get the same colors
colors = np.random.randint(0, 255, size=(len(class_names), 3))  # (80, 3)

counter = 0
while True:
    # starter time to computer the fps
    start = datetime.datetime.now()
    ret, frame = video_cap.read()
    # if there is no frame, we have reached the end of the video
    if not ret:
        print("End of the video file...")
        break
    ############################################################
    ### Detect the objects in the frame using the YOLO model ###
    ############################################################
   
    counter = counter + 1
    count = str(counter)
   # framesRead = cv2.imread("imgFrames/imgFrame" + count + ".jpg")
   #results = model("imgFrames/imgFrame" + count + ".jpg")
    results = model(source=frame)
    #print(results)`



**Below is the error snippet:**
2023-09-27 01:24:12.564464: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Ultralytics YOLOv8.0.3  Python-3.11.0 torch-2.0.1+cpu CPU
Fusing layers... 
YOLOv8n summary: 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
Traceback (most recent call last):
  File "C:\Users\Priti\PycharmProjects\RealTimeObjectDetect\main.py", line 77, in <module>
    results = model(source=frame)
              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Priti\PycharmProjects\RealTimeObjectDetect\ultralytics\yolo\engine\model.py", line 58, in __call__
    return self.predict(source, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Priti\PycharmProjects\RealTimeObjectDetect\venv\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Priti\PycharmProjects\RealTimeObjectDetect\ultralytics\yolo\engine\model.py", line 130, in predict
    predictor.setup(model=self.model, source=source)
  File "C:\Users\Priti\PycharmProjects\RealTimeObjectDetect\ultralytics\yolo\engine\predictor.py", line 143, in setup
    self.dataset = LoadImages(source,
                   ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Priti\PycharmProjects\RealTimeObjectDetect\ultralytics\yolo\data\dataloaders\stream_loaders.py", line 171, in __init__
    raise FileNotFoundError(f'{p} does not exist')
FileNotFoundError: C:\Users\Priti\PycharmProjects\RealTimeObjectDetect\[[[ 95 161 160]
  [ 92 158 157]
  [104 170 169]
  ...
  [ 33  34  29]
  [ 32  33  28]
  [ 32  33  28]]

 [[ 85 151 150]
  [ 76 142 141]
  [ 76 142 141]
  ...
  [ 33  34  29]
  [ 32  33  28]
  [ 32  33  28]]

 [[ 57 135 132]
  [ 48 126 123]
  [ 48 126 123]
  ...
  [ 33  34  29]
  [ 32  33  28]
  [ 32  33  28]]

 ...

 [[157 136 122]
  [159 138 124]
  [161 140 126]
  ...
  [127 119 114]
  [125 117 112]
  [124 116 111]]

 [[155 134 120]
  [158 137 123]
  [161 140 126]
  ...
  [127 119 114]
  [125 117 112]
  [124 116 111]]

 [[155 134 120]
  [158 137 123]
  [161 140 126]
  ...
  [127 119 114]
  [125 117 112]
  [124 116 111]]] does not exist

**Comment by glenn-jocher** [comment]
@chandumatrix004 i'm sorry to know that you're having a long-standing frustrating issue. From the traceback you've provided, it looks like the YOLOv8 model interpret the frame as a path to a file, which could be the root of the issue.

In the Ultralytics YOLOv8 implementation, when you are passing an image data into the model in the form of a numpy array, it is still mistakenly treating it as a path to a file. Consequently, it attempts to locate a file at the location described by the numpy array and results in a FileNotFoundError because such a file does not exist.

As you have suggested, the problem appears to be within the YOLOv8 model's handling of inputs, specifically in treating numpy arrays as file paths. This is likely a quirk of the specific version of the YOLOv8 model's implementation that is in use. 

I recommend reporting this specific issue to the authors or maintainers of the Ultralytics YOLOv8 implementation. This information would be beneficial as it would help address this issue and possibly prevent others from encountering a similar problem.

Thanks for your understanding and patience.

**Comment by chandumatrix004** [comment]
@glenn-jocher could you please suggest which version of Yolov8 I can use for this requirement. It would be of great help!!

**Comment by glenn-jocher** [comment]
Hello @chandumatrix004,

Thank you for your inquiry. As per your requirement, identifying the right version of YOLOv8 largely depends upon your specific needs and constraints. Each version has differing implementations, features, and may have varying requirements for libraries, operating systems, and hardware.

However, the Ultralytics YOLOv8 version you're using is widely recognized for its versatility and performance, thus it is generally a safe bet for a wide range of tasks. If you're experiencing issues, it may be less about needing a different version and more to do with troubleshooting the specific issue. 

We highly recommend that you share more details about your specific use-case requirements, errors you are encountering, or any constraints you might have. The more context you provide, the better we can assist you.

I hope this helps, and I'm here for any further questions or if you need additional clarification. Thank you for reaching out about YOLOv8!

**Comment by chandumatrix004** [comment]
Hello @glenn-jocher I'm using Yolov8 for a simulation of Real-time Object detection for autonomous cars with tracking of objects within frames. For this objective which version of Yolov8 would be best to use here. Please suggest the way forward. Thank you.

**Comment by chandumatrix004** [comment]
Hello @glenn-jocher,

I used a new Yolov8 version and it solved my above problem. 
I am now getting problem with the DeepSORT method gdet.create_box_encoder(model_filename, batch_size=1). 

# Below is the whole code snipped:

`import numpy as np
import datetime
import cv2

from ultralytics import YOLO

from helper import create_video_writer
from collections import deque

from deep_sort.deep_sort.tracker import Tracker
from deep_sort.deep_sort import nn_matching
from deep_sort.deep_sort.detection import Detection
from deep_sort.tools import generate_detections as gdet

# define some parameters
conf_threshold = 0.5
max_cosine_distance = 0.4
nn_budget = None
points = [deque(maxlen=32) for _ in range(1000)] # list of deques to store the points
counter_A = 0
counter_B = 0
counter_C = 0

# Initialize the video capture and the video writer objects
video_cap = cv2.VideoCapture("1.mp4")

writer = create_video_writer(video_cap, "output.mp4")
# Initialize the YOLOv8 model using the default weights
model = YOLO("yolov8n.pt")

# Initialize the deep sort tracker
model_filename = "config/mars-small128.pb"
encoder = gdet.create_box_encoder(model_filename, batch_size=1)
metric = nn_matching.NearestNeighborDistanceMetric(
    "cosine", max_cosine_distance, nn_budget)
tracker = Tracker(metric)

# load the COCO class labels the YOLO model was trained on
classes_path = "config/coco.names"
with open(classes_path, "r") as f:
    class_names = f.read().strip().split("\n")

# create a list of random colors to represent each class
np.random.seed(42)  # to get the same colors
colors = np.random.randint(0, 255, size=(len(class_names), 3))  # (80, 3)

counter = 0
while True:
    # starter time to computer the fps
    start = datetime.datetime.now()
    ret, frame = video_cap.read()
    # if there is no frame, we have reached the end of the video
    if not ret:
        print("End of the video file...")
        break
    ############################################################
    ### Detect the objects in the frame using the YOLO model ###
    ############################################################
    results = model(frame)

    # loop over the results
    for result in results:
        # initialize the list of bounding boxes, confidences, and class IDs
        bboxes = []
        confidences = []
        class_ids = []

        # loop over the detections
        for data in result.boxes.data.tolist():
            x1, y1, x2, y2, confidence, class_id = data
            x = int(x1)
            y = int(y1)
            w = int(x2) - int(x1)
            h = int(y2) - int(y1)
            class_id = int(class_id)

            # filter out weak predictions by ensuring the confidence is
            # greater than the minimum confidence
            if confidence > conf_threshold:
                bboxes.append([x, y, w, h])
                confidences.append(confidence)
                class_ids.append(class_id)
                # cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)

    ############################################################
    ### Track the objects in the frame using DeepSort        ###
    ############################################################

    # get the names of the detected objects
    names = [class_names[class_id] for class_id in class_ids]

    # get the features of the detected objects
    features = encoder(frame, bboxes)
    # convert the detections to deep sort format
    dets = []
    for bbox, conf, class_name, feature in zip(bboxes, confidences, names, features):
        dets.append(Detection(bbox, conf, class_name, feature))

    # run the tracker on the detections
    tracker.predict()
    tracker.update(dets)

    # loop over the tracked objects
    for track in tracker.tracks:
        if not track.is_confirmed() or track.time_since_update > 1:
            continue

        # get the bounding box of the object, the name
        # of the object, and the track id
        bbox = track.to_tlbr()
        track_id = track.track_id
        class_name = track.get_class()
        # convert the bounding box to integers
        x1, y1, x2, y2 = int(bbox[0]), int(bbox[1]), int(bbox[2]), int(bbox[3])

        # get the color associated with the class name
        class_id = class_names.index(class_name)
        color = colors[class_id]
        B, G, R = int(color[0]), int(color[1]), int(color[2])

        # draw the bounding box of the object, the name
        # of the predicted object, and the track id
        text = str(track_id) + " - " + class_name
        cv2.rectangle(frame, (x1, y1), (x2, y2), (B, G, R), 3)
        cv2.rectangle(frame, (x1 - 1, y1 - 20),
                      (x1 + len(text) * 12, y1), (B, G, R), -1)
        cv2.putText(frame, text, (x1 + 5, y1 - 8),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)


    ############################################################
    ### Some post-processing to display the results          ###
    ############################################################

    # end time to compute the fps
    end = datetime.datetime.now()
    # calculate the frame per second and draw it on the frame
    fps = f"FPS: {1 / (end - start).total_seconds():.2f}"
    cv2.putText(frame, fps, (50, 50),
                cv2.FONT_HERSHEY_SIMPLEX, 2, (0, 0, 255), 8)

    # draw the total number of vehicles passing the lines
    cv2.putText(frame, "A", (10, 483), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)
    cv2.putText(frame, "B", (530, 483), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)
    cv2.putText(frame, "C", (910, 483), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)


    # show the output frame
    cv2.imshow("Output", frame)
    # write the frame to disk
    writer.write(frame)
    if cv2.waitKey(1) == ord("q"):
        break

# release the video capture, video writer, and close all windows
video_cap.release()
writer.release()
cv2.destroyAllWindows()`


# Below is the error snippet:

C:\Users\Priti\PycharmProjects\RealTimeObjectDetect\venv\Scripts\python.exe C:\Users\Priti\PycharmProjects\RealTimeObjectDetect\main.py 

0: 384x640 5 cars, 1 bus, 1 umbrella, 839.5ms
Speed: 14.4ms preprocess, 839.5ms inference, 30.1ms postprocess per image at shape (1, 3, 384, 640)
Traceback (most recent call last):
  File "C:\Users\Priti\PycharmProjects\RealTimeObjectDetect\main.py", line 112, in <module>
    features = encoder(frame, bboxes)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Priti\PycharmProjects\RealTimeObjectDetect\deep_sort\tools\generate_detections.py", line 110, in encoder
    patch = extract_image_patch(image, box, image_shape[:2])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Priti\PycharmProjects\RealTimeObjectDetect\deep_sort\tools\generate_detections.py", line 62, in extract_image_patch
    bbox = bbox.astype(np.int)
                       ^^^^^^
  File "C:\Users\Priti\PycharmProjects\RealTimeObjectDetect\venv\Lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?

Process finished with exit code 1



# Please help me resolve this numpy error. Shall I use some other version of numpy??

**Comment by chandumatrix004** [comment]
Hello @glenn-jocher,

I Installed numpy version 1.23.5 and the whole code is working flawlessly. Thanks a lot for your help & support. Cheers mate!!

**Comment by glenn-jocher** [comment]
@chandumatrix004 hello,

I'm glad to hear that updating your numpy version to 1.23.5 has resolved the issue with your code. It's great to hear that everything is now working flawlessly.

You're welcome! It's always a pleasure to be able to help. Great job on finding the solution. Cheers, and best of luck with the continuation of your project using YOLOv8. Don't hesitate to reach back out if you encounter any other issues or challenges!

Best,
Glenn

**Comment by Misael777** [comment]
hi friend I resolove the problem, the issue is for versions. you need to install the last version of ultralytics. I think that older version doesn't have the arrays as an input parameter from source.

**Comment by glenn-jocher** [comment]
@Misael777 hi there,

I'm glad to hear that you managed to resolve the problem. It's great that you found the solution. You're absolutely right, having the most recent version of Ultralytics will likely ensure compatibility and remove potential issues. It is indeed possible that older versions may not have the flexibility to accept arrays as an input parameter from source.

Good job on diagnosing the versioning issue and thank you for sharing your solution. This will surely be helpful for other users who might encounter the same issue.

Best regards,
Glenn
