### ISSUE TITLE
Hardcoded channel number 

### ISSUE THREAD

**Issue by pbonazzi** [ultralytics/ultralytics#2413]
Why is this parameter hardcoded ? 

https://github.com/ultralytics/ultralytics/blob/243fc4b1fe214ff6c27759dad51c37809db8f7f8/ultralytics/nn/modules.py#L458

**Comment by glenn-jocher** [comment]
@pbonazzi thank you for bringing this to our attention. 

Regarding the hardcoded parameter you are referring to, it is related to the implementation of the YOLOv8 Neural Network and its associated configuration (number of anchor boxes, classes, etc.). Therefore, this parameter can be considered a default configuration of the YOLOv8 network, and changing it may affect the other components of the network, such as the number and size of the filters.

However, we understand that some users may want to experiment with different configurations, in which case they can modify this (and other) parameters accordingly, making sure to take into consideration any other necessary changes to the network as a whole.

Let us know if you have any further questions.

**Comment by pbonazzi** [comment]
Thanks, pietro out.
