### ISSUE TITLE
Any plan to implement with_reid?

### ISSUE THREAD

**Issue by liamsun2019** [ultralytics/ultralytics#2418]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Based on the codes, the with_reid in botsort.yaml has not actually been supported. Do you have any plan to implement the feature? Thanks for your time.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@liamsun2019 thank you for reaching out and for your interest in YOLOv8! We appreciate your feedback and suggestions for additional features. 

Regarding the `with_reid` option in `botsort.yaml`, at this time we have not implemented support for this feature in YOLOv8. However, we are always looking for ways to improve the codebase and provide new functionalities, so we will consider this as a potential feature to add in the future.

Please feel free to reach out with any other questions or suggestions you may have. Thank you for your time and contribution to the YOLOv8 community!

**Comment by liamsun2019** [comment]
Thanks for your quick feedback and look forward to your updates in the future.

**Comment by glenn-jocher** [comment]
@liamsun2019 thank you for your message and interest in YOLOv8! We appreciate your feedback and suggestions as we continue to develop and improve the codebase. We will keep in mind your request for feature support and consider implementing it in future releases.

Please let us know if you have any further questions or feedback. We are always happy to help and appreciate your contributions to the YOLOv8 community!

**Comment by jbdebelle** [comment]
Hello, I was wondering if since May there have been any advancement on the topic, I would be interested in having with_reid implemented. Is this planned ? 
Best Regards

**Comment by glenn-jocher** [comment]
@jbdebelle hello again! We continuously work on improving YOLOv8 and adding new features. However, as of now, there has not been an update regarding the direct implementation of `with_reid` within the YOLOv8 repository. Feature updates are carefully planned and prioritized based on a range of factors, including community demand and resource availability.

Rest assured that we take such requests into consideration as we plan the roadmap for future updates. We value your patience and continued interest and recommend staying tuned for any announcements related to new capabilities and improvements. If this feature becomes a part of our repository, it will be documented in our release notes and the official documentation.
