### ISSUE TITLE
segmentation model do not support augment inference

### ISSUE THREAD

**Issue by zhang-qiang-github** [ultralytics/ultralytics#2419]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I want the test-time augmentation for segmentation model.

### Use case

Just like the docment descript:

```
results = model(img, augment=True)
```

### Additional

Currently, the test-time augment is not supported:

```
class SegmentationModel(DetectionModel):
    """YOLOv8 segmentation model."""

    def __init__(self, cfg='yolov8n-seg.yaml', ch=3, nc=None, verbose=True):
        """Initialize YOLOv8 segmentation model with given config and parameters."""
        super().__init__(cfg=cfg, ch=ch, nc=nc, verbose=verbose)

    def _forward_augment(self, x):
        """Undocumented function."""
        raise NotImplementedError(emojis('WARNING ⚠️ SegmentationModel has not supported augment inference yet!'))
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@zhang-qiang-github hello, 

Thank you for reaching out. At the moment, test-time augmentation is not supported in YOLOv8 segmentation models. However, we appreciate your input and willingness to contribute to the project. If you would like to submit a PR with this feature, we encourage you to do so. 

Thank you for using YOLOv8! Let us know if you have any further questions or concerns.
