### ISSUE TITLE
Numpy Cholesky decomposition LinAlgError (in bot_sort)

### ISSUE THREAD

**Issue by chrah123** [ultralytics/ultralytics#2420]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I'm running model.track() with bot_sort and it works fine most of the time. However, occasionally, I get the following error message:

File "....\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 237, in stream_inference
    self.run_callbacks('on_predict_postprocess_end')
  File "....\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 331, in run_callbacks
    callback(self)
  File "....\lib\site-packages\ultralytics\tracker\track.py", line 47, in on_predict_postprocess_end
    tracks = predictor.trackers[i].update(det, im0s[i])
  File "....\lib\site-packages\ultralytics\tracker\trackers\byte_tracker.py", line 232, in update
    track.update(det, self.frame_id)
  File "....\lib\site-packages\ultralytics\tracker\trackers\bot_sort.py", line 58, in update
    super().update(new_track, frame_id)
  File "....\lib\site-packages\ultralytics\tracker\trackers\byte_tracker.py", line 104, in update
    self.mean, self.covariance = self.kalman_filter.update(self.mean, self.covariance,
  File "....\lib\site-packages\ultralytics\tracker\utils\kalman_filter.py", line 414, in update
    chol_factor, lower = scipy.linalg.cho_factor(projected_cov, lower=True, check_finite=False)
  File "....\lib\site-packages\scipy\linalg\_decomp_cholesky.py", line 154, in cho_factor
    c, lower = _cholesky(a, lower=lower, overwrite_a=overwrite_a, clean=False,
  File "....\lib\site-packages\scipy\linalg\_decomp_cholesky.py", line 37, in _cholesky
    raise LinAlgError("%d-th leading minor of the array is not positive "
numpy.linalg.LinAlgError: 2-th leading minor of the array is not positive definite

The matrix a1 in
c, info = potrf(a1, lower=lower, overwrite_a=overwrite_a, clean=clean)
in _decomp_cholesky.py
is not positive definite, so the linalg function works as it should: 
(array([[     6.2323,      5.7667,           0,           0],
       [     5.7667,     -1.1936,           0,           0],
       [          0,           0,      6.2323,      5.7667],
       [          0,           0,      5.7667,     -1.1936]]))

Perhaps this error can be caught somewhere upstream, rather than just crashing halfway through a video? Sorry for not suggesting a solution, this is unfortunately out of my comfort zone.

### Environment

- YOLO: Ultralytics YOLOv8.0.91  Python-3.10.11 torch-2.0.0 CUDA:0 (NVIDIA TITAN V, 12288MiB)
- OS: Windows 11
- python 3.10.11

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@chrah123 thank you for bringing this issue to our attention. This error occurs when the projected covariance matrix passed to scipy.linalg.cho_factor contains negative eigenvalues. While we are constantly improving our codebase, we do not currently catch this error but it is definitely something that we could consider adding upstream. 

As this is a relatively low frequency error, one workaround is to rerun the video after this error occurs; however we understand that this is not always practical. We are sorry that we are not able to offer a more immediate solution to this problem, but we truly appreciate your patience and understanding.

If you have any more questions or need further assistance, please do not hesitate to ask.

**Comment by shubhendu-ranadive** [comment]
@glenn-jocher

I have encountered the same bug.
But similar to @chrah123 , I don’t know how to solve this yet. 

My environment:
OS: Ubuntu 20.04
Python: 3.8.10
YOLO: Ultralytics YOLOv8.0.114 torch-2.0.1 CUDA:0 (NVIDIA Geforce GTX 1080 Ti 11264MiB)

**Comment by mzh1993** [comment]
I have encountered the same bug.

**Comment by glenn-jocher** [comment]
@mzh1993 understood. We've taken note of this issue affecting multiple users. We will look into handling non-positive definite matrices within our Kalman filter implementation to prevent such crashes in future releases. Thank you for your feedback. Keep an eye on our GitHub repository for updates concerning this matter.

**Comment by CourchesneA** [comment]
Still running into this issue once in a while and it's crashing the whole application for now, the try/catch solution is annoying to implement. It would be great if it could be fixed in the codebase

```
  File "/usr/local/lib/python3.8/dist-packages/scipy/linalg/_decomp_cholesky.py", line 37, in _cholesky
    raise LinAlgError("%d-th leading minor of the array is not positive "
numpy.linalg.LinAlgError: 2-th leading minor of the array is not positive definite
```

ultralytics version 8.3.3

**Comment by glenn-jocher** [comment]
Thank you for the follow-up. This issue is on our radar, and we are exploring ways to improve the handling of non-positive definite matrices in the codebase to avoid application crashes. For now, using a try/catch block is a viable interim solution, though we understand it is not ideal. Your patience is appreciated, and we encourage you to stay updated on future releases for potential fixes. If you'd like, you can also check our [Minimum Reproducible Example guide](https://docs.ultralytics.com/help/minimum_reproducible_example/) to assist us in replicating edge cases.

**Comment by PanJinquan** [comment]
hi, you can reset the tracking ID to fix this bug

```python
 try:
            tracks = model.track(im0, persist=True, show=False)
 except:  # TODO Bug: LinAlgError: 1-th leading minor of the array is not positive definite
            model.predictor.trackers[0].reset()  # reset the tracking ID
            tracks = model.track(im0, persist=True, show=False)
```

**Comment by glenn-jocher** [comment]
Thanks @PanJinquan—resetting the tracker state is a sensible mitigation. If you want to avoid catching exceptions altogether, try switching to ByteTrack (often more numerically stable) and persist the tracker:

```python
results = model.track(source=..., tracker="bytetrack.yaml", persist=True)
```

If this still occurs on the latest release, please open a new issue with the `yolo checks` output and a short clip so we can reproduce. We’re also happy to review a small PR that adds a diagonal-jitter fallback around `cho_factor` in `KalmanFilterXYWH.update()` (see the [KalmanFilter reference](https://docs.ultralytics.com/reference/trackers/utils/kalman_filter/) and [BOTSORT tracker reference](https://docs.ultralytics.com/reference/trackers/bot_sort/)); general usage is covered in the [Track mode docs](https://docs.ultralytics.com/modes/track/).
