### ISSUE TITLE
yolov8n-pose.pt export yolov8n-pose.onnx, yolov8n-pose.onnx works error

### ISSUE THREAD

**Issue by sunbozhang** [ultralytics/ultralytics#2422]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

yolov8n-pose.pt export yolov8n-pose.onnx, then i run yolo predict task=pose model=yolov8n-pose.onnx imgsz=640  source=./w4.jpg is bad
![w41](https://user-images.githubusercontent.com/16524657/236403497-666bd7b2-1b86-4df1-910d-3465d750b3e3.jpg)
but  i run yolo predict task=pose model=yolov8n-pose.pt imgsz=640  source=./w4.jpg is good 
![w4](https://user-images.githubusercontent.com/16524657/236403665-159200cd-d848-4247-8e5f-b6b0c06d8316.jpg)

### Environment

Ultralytics YOLOv8.0.92 � Python-3.8.0 torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce GTX 1650, 3910MiB)

### Minimal Reproducible Example

yolo predict task=pose model=yolov8n-pose.onnx imgsz=640  source=./w4.jpg

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @sunbozhang, thank you for bringing this to our attention. We're sorry to hear you're encountering issues with the onnx model exported from `yolov8n-pose.pt`. To help us debug this, could you provide us with the `Traceback` you are receiving when running yolo predict task=pose model=yolov8n-pose.onnx imgsz=640  source=./w4.jpg? Furthermore, could you provide us with the script you are using to convert `yolov8n-pose.pt` to `yolov8n-pose.onnx`, as well as the version of `onnx` you have installed? We're here to assist you in resolving this issue and if necessary, we will take any necessary steps to address it within the YOLOv8 codebase.

**Comment by sunbozhang** [comment]
@glenn-jocher Thank you for your reply, this is the script convert yolov8n-pose.pt to yolov8n-pose.onnx.
pt2onnx.py and onnx 1.12.0 opset 17
```
from ultralytics import YOLO
# Load a model
model = YOLO('yolov8n-pose.pt')  # load an official model
# Export the model
model.export(format='onnx', dynamic=False, simplify=True)
```
run python pt2onnx.py
output
```
Ultralytics YOLOv8.0.92 � Python-3.8.0 torch-2.0.0+cu117 CPU
YOLOv8n-pose summary (fused): 187 layers, 3289964 parameters, 0 gradients, 9.2 GFLOPs

PyTorch: starting from yolov8n-pose.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 56, 8400) (6.5 MB)

ONNX: starting export with onnx 1.12.0 opset 17...
============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ONNX: simplifying with onnxsim 0.4.17...
ONNX: export success ✅ 0.9s, saved as yolov8n-pose.onnx (12.8 MB)

Export complete (1.4s)
Results saved to /home/mnt/pytorch/yolo
Predict:         yolo predict task=pose model=yolov8n-pose.onnx imgsz=640 
Validate:        yolo val task=pose model=yolov8n-pose.onnx imgsz=640 data=/usr/src/app/ultralytics/datasets/coco-pose.yaml 
Visualize:       https://netron.app
```

run yolo predict task=pose model=yolov8n-pose.onnx imgsz=640 source=./w4.jpg
output
```
Ultralytics YOLOv8.0.92 � Python-3.8.0 torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce GTX 1650, 3910MiB)
Loading yolov8n-pose.onnx for ONNX Runtime inference...

image 1/1 /home/mnt/pytorch/yolo/w4.jpg: 640x640 8 persons, 10.9ms
Speed: 2.0ms preprocess, 10.9ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/pose/predict21
```

**Comment by glenn-jocher** [comment]
@sunbozhang, thank you for providing this additional information regarding your issue. It seems that you are correctly using the `ultralytics` script to convert `yolov8n-pose.pt` to `yolov8n-pose.onnx` and the conversion process is successful. However, when you run `yolo predict task=pose model=yolov8n-pose.onnx imgsz=640 source=./w4.jpg` with the converted `onnx` model, you encounter an issue. Since we cannot replicate the issue without seeing the actual error traceback, could you please provide us with this information? We would also recommend verifying that the version of the `onnx` dependencies installed is correct and compatible with the version of the model you are exporting. Thank you for your cooperation on this matter, and we look forward to hearing from you.

**Comment by sunbozhang** [comment]
@glenn-jocher hi，thanks for your patience。“However, when you run yolo predict task=pose model=yolov8n-pose.onnx imgsz=640 source=./w4.jpg with the converted onnx model, you encounter an issue. ”，this is output “ Ultralytics YOLOv8.0.92 � Python-3.8.0 torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce GTX 1650, 3910MiB)
Loading yolov8n-pose.onnx for ONNX Runtime inference...

image 1/1 /home/mnt/pytorch/yolo/w4.jpg: 640x640 8 persons, 10.9ms
Speed: 2.0ms preprocess, 10.9ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/pose/predict21”
it seems correct。

**Comment by glenn-jocher** [comment]
@sunbozhang, thank you for providing this information. It appears that the converted `onnx` model is working correctly and is producing the expected output. If you have any further questions or issues regarding YOLOv8, please don't hesitate to ask. Thank you for using YOLOv8.

**Comment by ZhouJiaHuan** [comment]
I met the same problem when trying to inference the exported onnx pose model, and the details are as follows:

**Environment:**
- ultralytics: 8.0.92
- torch: 1.12.1+cu116
- onnx; 1.12.0
- onnxruntime: 1.14.1
- numpy: 1.24.2

**Model:**
- yolov8n-pose.pt,
- md5: f02847dfc62af48e2e01848e06a2e03f

onnx model was exported with the follow command:
```
yolo export model= checkpoints/yolov8n-pose.pt format=onnx

# output:
Ultralytics YOLOv8.0.92 🚀 Python-3.8.10 torch-1.12.1+cu116 CPU
YOLOv8n-pose summary (fused): 187 layers, 3289964 parameters, 0 gradients, 9.2 GFLOPs

PyTorch: starting from checkpoints/yolov8n-pose.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 56, 8400) (6.5 MB)

ONNX: starting export with onnx 1.12.0 opset 10...
ONNX: export success ✅ 1.5s, saved as checkpoints/yolov8n-pose.onnx (12.8 MB)

Export complete (1.9s)
Results saved to /home/meringue/Project/ultralytics/checkpoints
Predict:         yolo predict task=pose model=checkpoints/yolov8n-pose.onnx imgsz=640 
Validate:        yolo val task=pose model=checkpoints/yolov8n-pose.onnx imgsz=640 data=/usr/src/app/ultralytics/datasets/coco-pose.yaml 
Visualize:       https://netron.app
```

ps: I tried to using different opset version but the results are same in the predict phase.

**Predict**:

torch model:
```
yolo predict model=checkpoints/yolov8n-pose.pt source=ultralytics/assets/bus.jpg

# output
Ultralytics YOLOv8.0.92 🚀 Python-3.8.10 torch-1.12.1+cu116 CUDA:0 (NVIDIA GeForce RTX 3090, 24260MiB)
YOLOv8n-pose summary (fused): 187 layers, 3289964 parameters, 0 gradients, 9.2 GFLOPs

image 1/1 /home/meringue/Project/ultralytics/ultralytics/assets/bus.jpg: 640x480 4 persons, 13.9ms
Speed: 2.1ms preprocess, 13.9ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 640)
Results saved to /home/meringue/Project/ultralytics/runs/pose/predict9
```

onnx model
```
yolo predict model=checkpoints/yolov8n-pose.onnx source=ultralytics/assets/bus.jpg

# output
Ultralytics YOLOv8.0.92 🚀 Python-3.8.10 torch-1.12.1+cu116 CUDA:0 (NVIDIA GeForce RTX 3090, 24260MiB)
Loading checkpoints/yolov8n-pose.onnx for ONNX Runtime inference...

image 1/1 /home/meringue/Project/ultralytics/ultralytics/assets/bus.jpg: 640x640 4 persons, 21.7ms
Speed: 4.5ms preprocess, 21.7ms inference, 2.5ms postprocess per image at shape (1, 3, 640, 640)
Results saved to /home/meringue/Project/ultralytics/runs/pose/predict10
```

results (pt && onnx)
![bus](https://user-images.githubusercontent.com/37075120/236718342-74d84675-285b-453d-af17-8fbc16ea8802.jpg)


![bus](https://user-images.githubusercontent.com/37075120/236718423-6e71756d-2cfb-4d44-9c52-6fc216e89309.jpg)


and I found the problem may caused by the keypoints score when I try the onnxruntime inference with different keypoints score threshold, which was as follows:
``` Python
'''
yolov8-pose onnxruntime inference
github: https://github.com/ultralytics/ultralytics
'''

import os
import numpy as np
import cv2
import argparse
import json
import onnxruntime
from tqdm import tqdm
from typing import List, Tuple, Dict

COLOR_LIST = list([[128, 255, 0], [255, 128, 50], [128, 0, 255], [255, 255, 0],
                   [255, 102, 255], [255, 51, 255], [51, 153, 255], [255, 153, 153],
                   [255, 51, 51], [153, 255, 153], [51, 255, 51], [0, 255, 0],
                   [255, 0, 51], [153, 0, 153], [51, 0, 51], [0, 0, 0],
                   [0, 102, 255], [0, 51, 255], [0, 153, 255], [0, 153, 153]])

def xywh2xyxy(box: np.ndarray) -> np.ndarray:
    box_xyxy = box.copy()
    box_xyxy[..., 0] = box[..., 0] - box[..., 2] / 2
    box_xyxy[..., 1] = box[..., 1] - box[..., 3] / 2
    box_xyxy[..., 2] = box[..., 0] + box[..., 2] / 2
    box_xyxy[..., 3] = box[..., 1] + box[..., 3] / 2
    return box_xyxy

def compute_iou(box: np.ndarray, boxes: np.ndarray) -> np.ndarray:
    '''
    box and boxes are format as [x1, y1, x2, y2]
    '''
    # inter area
    xmin = np.maximum(box[0], boxes[:, 0])
    ymin = np.maximum(box[1], boxes[:, 1])
    xmax = np.minimum(box[2], boxes[:, 2])
    ymax = np.minimum(box[3], boxes[:, 3])
    inter_area = np.maximum(0, xmax-xmin) * np.maximum(0, ymax-ymin)

    # union area
    box_area = (box[2] - box[0]) * (box[3] - box[1])
    boxes_area = (boxes[:, 2] - boxes[:, 0]) * (boxes[:, 3] - boxes[:, 1])
    union_area = box_area + boxes_area - inter_area

    return inter_area / union_area

def nms_process(boxes: np.ndarray, scores: np.ndarray, iou_thr: float) -> List[int]:
    sorted_idx = np.argsort(scores)[::-1]
    keep_idx = []
    while sorted_idx.size > 0:
        idx = sorted_idx[0]
        keep_idx.append(idx)
        ious = compute_iou(boxes[idx, :], boxes[sorted_idx[1:], :])
        rest_idx = np.where(ious < iou_thr)[0]
        sorted_idx = sorted_idx[rest_idx+1]
    return keep_idx

class Yolov8KeypointsInference(object):
    ''' yolov8-keypoints onnxruntime inference
    '''

    def __init__(self,
                 onnx_path: str,
                 input_size: Tuple[int],
                 box_score=0.25,
                 kpt_score=0.5,
                 nms_thr=0.2
                 ) -> None:
        assert onnx_path.endswith('.onnx'), f"invalid onnx model: {onnx_path}"
        assert os.path.exists(onnx_path), f"model not found: {onnx_path}"
        self.sess = onnxruntime.InferenceSession(onnx_path)
        print("input info: ", self.sess.get_inputs()[0])
        print("output info: ", self.sess.get_outputs()[0])
        self.input_size = input_size
        self.box_score = box_score
        self.kpt_score = kpt_score
        self.nms_thr = nms_thr

    def _preprocess(self, img: np.ndarray):
        ''' preprocess image for model inference
        '''
        input_w, input_h = self.input_size
        if len(img.shape) == 3:
            padded_img = np.ones((input_w, input_h, 3), dtype=np.uint8) * 114
        else:
            padded_img = np.ones(self.input_size, dtype=np.uint8) * 114
        r = min(input_w / img.shape[0], input_h / img.shape[1])
        resized_img = cv2.resize(
            img,
            (int(img.shape[1] * r), int(img.shape[0] * r)),
            interpolation=cv2.INTER_LINEAR,
        ).astype(np.uint8)
        padded_img[: int(img.shape[0] * r), : int(img.shape[1] * r)] = resized_img
        # (H, W, C) BGR -> (C, H, W) RGB
        padded_img = padded_img.transpose((2, 0, 1))[::-1, ]
        padded_img = np.ascontiguousarray(padded_img, dtype=np.float32)
        return padded_img, r
    
    def _postprocess(self, output: List[np.ndarray], ratio) -> Dict:
        predict = output[0].squeeze(0).T
        predict = predict[predict[:, 4] > self.box_score, :]
        scores = predict[:, 4]
        boxes = predict[:, 0:4] / ratio
        boxes = xywh2xyxy(boxes)
        kpts = predict[:, 5:]
        print(kpts)
        for i in range(kpts.shape[0]):
            for j in range(kpts.shape[1] // 3):
                if kpts[i, 3*j+2] < self.kpt_score:
                    kpts[i, 3*j: 3*(j+1)] = [-1, -1, -1]
                else:
                    kpts[i, 3*j] /= ratio
                    kpts[i, 3*j+1] /= ratio 
        idxes = nms_process(boxes, scores, self.nms_thr)
        result = {'boxes': boxes[idxes,: ].astype(int).tolist(),
                  'kpts': kpts[idxes,: ].astype(float).tolist(),
                  'scores': scores[idxes].tolist()}
        return result

    def detect(self, img: np.ndarray) -> Dict:
        img, ratio = self._preprocess(img)
        ort_input = {self.sess.get_inputs()[0].name: img[None, :]/255}
        output = self.sess.run(None, ort_input)
        result = self._postprocess(output, ratio)
        return result
    
    def draw_result(self, img: np.ndarray, result: Dict, with_label=False) -> np.ndarray:
        boxes, kpts, scores = result['boxes'], result['kpts'], result['scores']
        for box, kpt, score in zip(boxes, kpts, scores):
            x1, y1, x2, y2 = box
            label_str = "{:.0f}%".format(score*100)
            label_size, baseline = cv2.getTextSize(label_str, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 2)
            cv2.rectangle(img, (x1, y1), (x2, y2), (0, 0, 255), 2)
            if with_label:
                cv2.rectangle(img, (x1, y1), (x1+label_size[0], y1+label_size[1]+baseline),
                    (0, 0, 255), -1)
                cv2.putText(img, label_str, (x1, y1+label_size[1]), cv2.FONT_HERSHEY_SIMPLEX,
                    0.5, (255, 255, 255), 2)
            for idx in range(len(kpt) // 3):
                x, y, score = kpt[3*idx: 3*(idx+1)]
                if score > 0:
                    cv2.circle(img, (int(x), int(y)), 2, COLOR_LIST[idx], -1)
        return img

def parse_args():
    parser = argparse.ArgumentParser("yolov8 keypoints onnx inference demo")
    parser.add_argument("demo", type=str,
        help="demo type, image | stream")
    parser.add_argument("model", type=str,
        help="onnx model path")
    parser.add_argument("input", type=str, default="0",
        help="camera id | video path | image path | image dir")
    parser.add_argument("--box_score", type=float, default=0.25,
        help="box score threshold")
    parser.add_argument("--kpt_score", type=float, default=0.5,
        help="keypoint score threshold")
    parser.add_argument("--nms_thr", type=float, default=0.5,
        help="nms threshold")
    parser.add_argument("--input_size", type=int, default=640,
        help="input size")
    parser.add_argument("--show", action="store_true")
    return parser.parse_args()

def demo_image(args):
    input_size = (args.input_size, args.input_size)
    yolo = Yolov8KeypointsInference(args.model, input_size, args.box_score, args.kpt_score, args.nms_thr)
    img = cv2.imread(args.input)
    if img is None:
        print(f"read image failed: {args.input}")
        return
    result = yolo.detect(img)
    img = yolo.draw_result(img, result)
    boxes = result['boxes']
    kpts = result['kpts']
    scores = result['scores']
    for box, kpt, score in zip(boxes, kpts, scores):
        kpt = list(map(lambda k: round(k, 3), kpt))
        print(f"{score:.3}\t{box}\t{kpt}")
      
    if args.show:
        cv2.imshow("detect", img)
        cv2.waitKey(0)

def demo_image_dir(args):
    input_size = (args.input_size, args.input_size)
    yolo = Yolov8KeypointsInference(args.model, input_size, args.box_score, args.kpt_score, args.nms_thr)

    assert os.path.isdir(args.input), f"invalid image directory: {args.input}"
    img_list = [os.path.basename(img_name) for img_name in os.listdir(args.input) 
                if img_name.split('.')[-1] in ('jpg', 'png')]
    save_dir = 'result_' + os.path.abspath(args.input).replace('/', '_')
    os.makedirs(save_dir, exist_ok=True)
    for img_name in tqdm(img_list):
        img_path = os.path.join(args.input, img_name)
        img = cv2.imread(img_path)
        if img is None:
            print(f'read image failed: {img_path}')
            continue
        result = yolo.detect(img)
        img_result = yolo.draw_result(img, result)
        cv2.imwrite(os.path.join(save_dir, img_name), img_result)
        with open(os.path.join(save_dir, img_name.split('.')[0]+'.json'), 'w') as f:
            result['img_name'] = img_name
            result['img_size'] = img.shape[:2][::-1]
            json.dump(result, f)
        if args.show:
            cv2.imshow('detect', img_result)
            cv2.waitKey(100)

def demo_stream(args):
    input_size = (args.input_size, args.input_size)
    yolo = Yolov8KeypointsInference(args.model, input_size, args.box_score, args.kpt_score, args.nms_thr)

    if (len(args.input)) == 1:
        cap = cv2.VideoCapture(int(args.input))
    else:
        cap = cv2.VideoCapture(args.input)

    while True:
        ret, frame = cap.read()
        if not ret:
            break
        result = yolo.detect(frame)
        frame = yolo.draw_result(frame, result)
        if args.show:
            cv2.imshow("detect", frame)
            if cv2.waitKey(1) == ord('q'):  # Esc
                break
        else:
            num = len(result['boxes'])
            print(f"detect {num} objects")

def main():
    args = parse_args()
    if args.demo == 'image':
        if os.path.isfile(args.input):
            return demo_image(args)
        elif os.path.isdir(args.input):
            return demo_image_dir(args)
        else:
            print(f"invalid input: {args.input}")
            return
    elif args.demo == 'stream':
        return demo_stream(args)

if __name__ == "__main__":
    main()

```

**Comment by akkolyth** [comment]
@ZhouJiaHuan

have you fixed that?

**Comment by ZhouJiaHuan** [comment]
@akkolyth 
Not yet. I tried to install ultralytics with pip in a virtual environment and got the same problem, it seems a bug. However, the pose onnx model works before I pulling the latest code...

**Comment by akkolyth** [comment]
@ZhouJiaHuan 
I figured it out. There is must be some kind of export bug between ultralytics<=8.0.87 and ultralytics>=8.0.88. Exported models are completely different (netron / polygraphy). If you downgrade to 8.0.87 it should work (only for export). All weights are from here: https://docs.ultralytics.com/tasks/pose/#models

Other libs versions that I used:
- ultralytics 8.0.87 
- onnx 1.14.0 (newest)
- onnxruntime 1.14.1 (newest)

![image](https://github.com/ultralytics/ultralytics/assets/87362667/e9132887-5585-4332-a97b-19646952da9a)

btw, you can run those exported models on newest ultralytics==8.0.98

**Comment by glenn-jocher** [comment]
@akkolyth thank you for sharing your solution! It seems like there is a bug in the export function between versions 8.0.87 and 8.0.88 of Ultralytics. Downgrading to version 8.0.87 and using the weights from the Ultralytics documentation should resolve the issue. Additionally, you mentioned that the exported models can be run on version 8.0.98 of Ultralytics.

**Comment by ZhouJiaHuan** [comment]
@akkolyth thank you for your solution @glenn-jocher I test the exported onnx model prediction wih yolo8n-pose on version 8.0.87 and 8.0.92, and the results are as follows:

- onnx model exported with ultralytic 8.0.87
1. predict on version 8.0.87: OK
2. predict on version 8.0.92: OK

- onnx model exported with ultralytic 8.0.92
1. predict on version 8.0.87: WRONG
2. predict on version 8.0.92: WRONG

by the way, the lower version seems to have a BUG when traing pose model with custom dataset. Concretely the pose Presion and Recall are very small during the traing phase. But when training with latest version, it's OK.

**Comment by glenn-jocher** [comment]
Hello @ZhouJiaHuan, thank you for your update on the situation. It seems like the exported onnx model prediction with YOLOv8 depends on the version of Ultralytics used to export the model. Based on your results, the onnx model exported with Ultralytics 8.0.87 works with both versions 8.0.87 and 8.0.92 of YOLOv8, while the onnx model exported with Ultralytics 8.0.92 doesn't work with either version. 

You also mentioned that there seems to be a bug in the lower version (8.0.87) when training pose models with custom datasets, resulting in small pose precision and recall during training. However, when using the latest version of Ultralytics, this issue is resolved.

**Comment by zhxingye** [comment]
> 



> Hello @ZhouJiaHuan, thank you for your update on the situation. It seems like the exported onnx model prediction with YOLOv8 depends on the version of Ultralytics used to export the model. Based on your results, the onnx model exported with Ultralytics 8.0.87 works with both versions 8.0.87 and 8.0.92 of YOLOv8, while the onnx model exported with Ultralytics 8.0.92 doesn't work with either version.
> 
> You also mentioned that there seems to be a bug in the lower version (8.0.87) when training pose models with custom datasets, resulting in small pose precision and recall during training. However, when using the latest version of Ultralytics, this issue is resolved.

@glenn-jocher Although Ultralytics 8.0.87 seems works，some of the keypoint scores of yolov8n-pose.onnx are greater than 1.0（can be negative, too ），which is different from the pytorch output (0 - 1.0).  The predict keypoints number of the two model may not same (only a little bit different ), althought the predict locations are same.

**Comment by glenn-jocher** [comment]
Hello @zhxingye, thank you for bringing this to our attention. It seems that there might be some issues with the exported ONNX model from YOLOv8 specifically with keypoint scores. We will investigate this further to determine the root cause of this behavior. We appreciate your patience and understanding as we work to resolve this issue.

**Comment by BHUVAN-RJ** [comment]
I am still facing the same issue, has anyone found any solution to this? I tried to get this environment to export my own pose model but it gives me some errors(will further elaborate if needed). So cannot even get this to work. Any suggestions or work around??

> @akkolyth thank you for your solution @glenn-jocher I test the exported onnx model prediction wih yolo8n-pose on version 8.0.87 and 8.0.92, and the results are as follows:
> 
> * onnx model exported with ultralytic 8.0.87
> 
> 1. predict on version 8.0.87: OK
> 2. predict on version 8.0.92: OK
> 
> * onnx model exported with ultralytic 8.0.92
> 
> 1. predict on version 8.0.87: WRONG
> 2. predict on version 8.0.92: WRONG
> 
> by the way, the lower version seems to have a BUG when traing pose model with custom dataset. Concretely the pose Presion and Recall are very small during the traing phase. But when training with latest version, it's OK.

**Comment by glenn-jocher** [comment]
Hey there! 😊 It seems like you're encountering some tricky issues with exporting your pose model. Based on the testing done by @BHUVAN-RJ and the discrepancies between versions 8.0.87 and 8.0.92 you've noted, it does look like there's a specific matter with the export function across different Ultralytics versions.

For a possible workaround, considering exporting the model using version 8.0.87 (since it seems to produce usable outputs for both 8.0.87 and 8.0.92 during predictions) may be a solid temporary fix. However, if you're hitting errors even in this setup, I'd definitely like to hear more about those so we can work together toward a solution. 🛠

On another note, the issue you mentioned regarding pose Precision and Recall in 8.0.87 during training—this has been noted, and it's great to hear the latest version has improvements there.

It might also be beneficial to see if using `dynamic_axes` during the export may help with compatibility. Here's a rough example of what the export command might look like:

```bash
yolo export model=path/to/your/yolov8n-pose.pt format=onnx imgsz=640 dynamic=True
```

Remember, each project's setup can be unique, so we may need to adjust some parameters. Let us know if you can share more details about the errors you're facing, and we'll do our best to help you out!

**Comment by BHUVAN-RJ** [comment]
Hi @glenn-jocher, I did try to get that done. I am getting dependency conflict. I just this -- pip install ultralytics==8.0.87.
And here is the traceback of the same:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/yolo", line 5, in <module>
    from ultralytics.cfg import entrypoint
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.data.explorer.explorer import Explorer
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/data/__init__.py", line 3, in <module>
    from .base import BaseDataset
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/data/base.py", line 17, in <module>
    from ultralytics.utils import DEFAULT_CFG, LOCAL_RANK, LOGGER, NUM_THREADS, TQDM
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/utils/__init__.py", line 1030, in <module>
    set_sentry()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ultralytics/utils/__init__.py", line 893, in set_sentry
    sentry_sdk.init(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sentry_sdk/hub.py", line 131, in _init
    client = Client(*args, **kwargs)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sentry_sdk/client.py", line 162, in __init__
    self._init_impl()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sentry_sdk/client.py", line 268, in _init_impl
    self.integrations = setup_integrations(
                        ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sentry_sdk/integrations/__init__.py", line 119, in setup_integrations
    for integration_cls in iter_default_integrations(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sentry_sdk/integrations/__init__.py", line 46, in iter_default_integrations
    yield getattr(import_module(module), cls)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sentry_sdk/integrations/flask.py", line 30, in <module>
    from flask import Flask, Request  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/flask/__init__.py", line 1, in <module>
    from . import json as json
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/flask/json/__init__.py", line 6, in <module>
    from ..globals import current_app
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/flask/globals.py", line 45, in <module>
    app_ctx: AppContext = LocalProxy(  # type: ignore[assignment]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LocalProxy.__init__() got an unexpected keyword argument 'unbound_message'

**Comment by BHUVAN-RJ** [comment]
Does anyone know how to build ultralytics from source? I tried pip install but I have encountered the above error, dependencies versions aren't matching apparently. Any ideas to solve this??

**Comment by glenn-jocher** [comment]
@BHUVAN-RJ hi there! Sorry to hear you're running into issues with installing Ultralytics from source. It looks like you're facing a dependency conflict, which is fairly common. To install from source, you can follow these steps:

1. Clone the repository:
```bash
git clone https://github.com/ultralytics/ultralytics.git
```

2. Navigate into the cloned directory:
```bash
cd ultralytics
```

3. Install the package using pip with the `-e` (editable) flag. This way, your installation updates as you pull changes from Git:
```bash
pip install -e .
```

This approach should help in resolving any potential versioning conflicts with dependencies. Make sure your Python environment matches the prerequisites mentioned in the Ultralytics README for a smooth experience. 😊

If you continue facing the same issue, consider setting up a new virtual environment specifically for this project to isolate and manage dependencies more effectively:

```bash
python -m venv ultralytics-env
source ultralytics-env/bin/activate
pip install -e .
```

Hope this helps! Let us know if you run into any more bumps along the way.

**Comment by BHUVAN-RJ** [comment]
hi @glenn-jocher, I wanted to install the ultralytics version 8.0.87 from source as pip install ultralytics==8.0.87 gives me the dependency error. I want to export my pytorch model to onnx and have found that exporting using the current version of ultralytics is buggy and output has an issue.

**Comment by glenn-jocher** [comment]
@BHUVAN-RJ hi there! 😊 To install Ultralytics version 8.0.87 from source, you can follow these simple steps:

1. Clone the repository and navigate to it:
```bash
git clone https://github.com/ultralytics/ultralytics.git
cd ultralytics
```

2. Checkout to the specific commit or tag that matches version 8.0.87 (assuming `tag_v8.0.87` is the tag):
```bash
git checkout tags/tag_v8.0.87
```

3. Install the package using pip in editable mode:
```bash
pip install -e .
```

This should help you avoid dependency conflicts and allow you to export your PyTorch model to ONNX using the specific version. If you still encounter issues after this, please let us know! Happy coding! 🚀

**Comment by glenn-jocher** [comment]
Hey @BHUVAN-RJ! 😊 It looks like there's an issue with loading a custom model due to a missing module 'ultralytics.nn.modules.conv'. This particular issue might be related to the version compatibility or an unexpected alteration in your model's architecture during training with a different version of Ultralytics.

A quick potential fix would be to ensure that your Ultralytics installation and the model are perfectly matched in terms of the version. If the model was trained on an older or different version of Ultralytics than what you're currently running, you might encounter such issues.

As the error suggests, training your model again with the latest `ultralytics` package could resolve the issue, ensuring all required modules are present. Alternatively, testing with an official model like `yolov8n.pt` can help verify if the environment setup works correctly without the custom model complexities.

```bash
yolo predict model=yolov8n.pt source=./your_image.jpg
```

If you're deeply reliant on your current model and retraining isn't immediately feasible, revisiting the exact Ultralytics version used during the model's training and aligning your current environment accordingly might be necessary. Unfortunately, the direct installation for a missing internal module like `'ultralytics.nn.modules.conv'` won't be straightforward since it's specific to the Ultralytics framework structure.

Feel free to share more details if you continue to face issues; we're here to help!
