### ISSUE TITLE
CHANGE DEFAULT AUGMENTATION VALUES VIA YOLO PACKAGE

### ISSUE THREAD

**Issue by edanurkamaci** [ultralytics/ultralytics#2428]
### Discussed in https://github.com/orgs/ultralytics/discussions/2427

<div type='discussions-op-text'>

<sup>Originally posted by **edanurkamaci** May  5, 2023</sup>
Hi I wanted to augment my dataset using augment class which has albumentation operations with yolo package. I did it but I do not know how to integrate it to my model created by YOLO(..) function. Can you help me with that. I do not wanna clone github code, I am just trying to figure out to how to deal with it by using package</div>

**Comment by glenn-jocher** [comment]
@edanurkamaci hello edanurkamaci, 

Thank you for your interest in using augmentations with YOLOv8. To integrate augmentations to your existing model, you can make use of the DataPipeline class provided by Ultralytics.

First, you need to define the augmentations you want to use in your pipeline using Albumentations. Then, you can create an instance of a DataPipeline with the defined augmentations. Finally, use the DataPipeline object in your YOLOv8 model initialization to load your augmented data.

If you have any difficulties, the Ultralytics team is always here to help. Feel free to reach out to us with more questions.

Best regards,

Glenn Jocher

**Comment by edanurkamaci** [comment]
@glenn-jocher  hi glenn,

I tried to implement what you said but, i could not find DataPipeline class in Ultralytics. I created new transform values using albumentation class and created a new instance of Compose with the transform values, but i could not figure out how to initialize my model with the compose or use it in train function
