### ISSUE TITLE
Save Track detected object ID image with biggest box size

### ISSUE THREAD

**Issue by SuperMaximus1984** [ultralytics/ultralytics#2430]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I need to attain the best object image and want to overwrite the image of a detected object with the same tracked ID (e.g. same person in frame) with same file name instead of `save_crop` producing multiple images like "videoXX.jpg"  in `\runs\detect\track\crops\person\`.
How to realize it in Python? Thanks!

My current code:

```
from ultralytics import YOLO
model = YOLO('yolov8x.pt')

results = model.track(source="http://192.168.0.207:8080/video", conf=0.65, classes=[0], save_crop=True, device=0, show=True)
```

**Comment by glenn-jocher** [comment]
Hello @SuperMaximus1984, 

It sounds like you want to overwrite the saved cropped image with the same filename for a given tracked object ID instead of having multiple cropped images saved per frame. While this is not currently a feature in YOLOv8, one way to accomplish your goal is to use Python's built-in file-handling functions to check if a file with the same filename already exists and overwrite it.

To do this, you can extract the object ID and filename of each cropped image and then use Python functions such as `os.path.isfile()` and `os.remove()` to check if the file already exists and overwrite it. You will need to implement your own solution to maintain tracking ID between frames or use the already available tracking ID in the file's name.

I hope this helps. If you have any further questions or need additional assistance, please let me know.

**Comment by SuperMaximus1984** [comment]
@glenn-jocher If you have any idea about the unique object ID extraction, please share.
That's the primary obstacle I face.
Thanks!

**Comment by glenn-jocher** [comment]
Hello @SuperMaximus1984,

To extract unique object IDs, you can take advantage of the tracking feature in YOLOv8. Once a track is assigned to an object, each unique object in the frame should have a unique track ID assigned to it. You can then retrieve the track ID and use it as a part of the filename when saving the cropped image.

To access the track ID, you can modify the `save_crop` function in the `detector.py` file in the YOLOv8 repository to return the track ID for each cropped image. You can then use the track ID as part of the filename when saving the cropped image to ensure each unique object has a unique filename.

I hope this helps. Let me know if you have any additional questions or need further assistance.

**Comment by SuperMaximus1984** [comment]
@glenn-jocher Hello!
I can't use `save_crop` due to the impossibility of implementing the conditional saving of cropped images (I only save if detection matches my conditions). Below I wrote a code that does the job well (only if `show=True, stream=True` and GUI windows are shown), but now I need to run it "silently" in the console, and when `show=False, stream=False` the algorithm does not work at all. I have detections in the console, though, and need to save JPGs using the logic in this code, but scratching my head how to accomplish it...

```
import cv2

from ultralytics import YOLO
from datetime import datetime
import supervision as sv
import numpy as np


LINE_START = sv.Point(640, 0)
LINE_END = sv.Point(640, 720)
last_detected = {}
max_size = {}

def main():
    line_counter = sv.LineZone(start=LINE_START, end=LINE_END)
    line_annotator = sv.LineZoneAnnotator(thickness=2, text_thickness=1, text_scale=0.5)
    box_annotator = sv.BoxAnnotator(
        thickness=2,
        text_thickness=1,
        text_scale=0.5
    )

    model = YOLO("yolov8l.pt")
    for result in model.track(source=0, conf=0.65, show=False, stream=False, agnostic_nms=True):
        
        frame = result.orig_img
        detections = sv.Detections.from_yolov8(result)

        if result.boxes.id is not None:
            detections.tracker_id = result.boxes.id.cpu().numpy().astype(int)
        
        detections = detections[detections.class_id == 0]

        if detections.tracker_id is not None:
            for i, detection in enumerate(detections):
                x1, y1, x2, y2 = detections.xyxy[i]
                tracker_id = detections.tracker_id[i]
                now = datetime.now()
                size = (x2 - x1) * (y2 - y1)
                              
                if tracker_id not in last_detected or (now - last_detected[tracker_id]).total_seconds() > 30:
                    last_detected[tracker_id] = now
                    max_size[tracker_id] = size
                    timestamp = now.strftime('%y%m%d_%H%M')
                    filename = f"{timestamp}_person_{tracker_id}.jpg"
                    if frame[int(y1):int(y2), int(x1):int(x2)].size != 0:
                        print("Saving image normal")
                        cv2.imwrite(filename, frame[int(y1):int(y2), int(x1):int(x2)])       
                
                elif size > max_size[tracker_id]:
                    max_size[tracker_id] = size
                    timestamp = now.strftime('%y%m%d_%H%M')
                    filename = f"{timestamp}_person_{tracker_id}.jpg"
                    if frame[int(y1):int(y2), int(x1):int(x2)].size != 0:
                        print("Saving image overwrite")
                        cv2.imwrite(filename, frame[int(y1):int(y2), int(x1):int(x2)])

        labels = [
            f"{tracker_id} {model.model.names[class_id]} {confidence:0.2f}"
            for _, confidence, class_id, tracker_id
            in detections
        ]

        frame = box_annotator.annotate(
            scene=frame,
            detections=detections,
            labels=labels
        )

        line_counter.trigger(detections=detections)
        line_annotator.annotate(frame=frame, line_counter=line_counter)

        cv2.imshow("yolov8", frame)

        if (cv2.waitKey(30) == 27):
            break


if __name__ == "__main__":
    main()
```

**Comment by glenn-jocher** [comment]
Hello @SuperMaximus1984,

I am glad to hear that the supervision feature in YOLOv8 helped in your use case and thank you for considering the `save_crop` function for future reference. To extract the object ID, you can take advantage of YOLOv8's tracking feature, which assigns a unique track ID to each object. You can retrieve the track ID using the `save_crop` function and use it to generate a unique filename for each object.

Regarding the reference to the `detector.py` file, it is the main YOLOv8 detector file located in the `models` directory of the repository. You can modify this file to customize YOLOv8's behavior to meet your needs. 

I hope this helps. Let me know if you have any further questions or need more clarification.

**Comment by Ariega14** [comment]
@glenn-jocher I have a problem retrieving the ID assigned to an object, I am also having a hard time understanding the save_crop as I do not know how to access detector.py. I am currently using:

results1 = model.track(img, persist=True)
annotated_frame = results1[0].plot()

I get the ID along with the frame and confidence for the object, but how can I modify the plot where I have my own modified frame, how to retrieve the ID assigned to an object. Sorry for my newb question as I am very new to Image Processing. I hope you can help me thank you.
