### ISSUE TITLE
Training command

### ISSUE THREAD

**Issue by wzf19947** [ultralytics/ultralytics#2434]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm really confused about the training commands in YOLOv8, I'm using the way of
"yolo cfg=default_copy.yaml".
1. if my epochs=100, I interrupt it at epoch 60, how do I continue the training without from scratch?
2. if I finish my training with 100epochs, I want to train longer with 150 epoch, how do I use the command?
3. if I use my custom model yaml, is it useful to use a pretrained model like yolov8n.pt?

**Comment by glenn-jocher** [comment]
@wzf19947 hello and thank you for reaching out. 

1. If you interrupt training at epoch 60 and want to continue training without starting from scratch, you can simply resume the training by running the same training command with the `--resume` flag followed by the path to the last saved checkpoint of your model. This way, the model will load the weights from this checkpoint, and it will continue from where it left off. 

2. If you want to train the model longer with 150 epochs, you can just run the same training command again, but change the `--epochs` flag to 150. The model will start training from the last checkpoint of your model.

3. Using a pretrained model like yolov8n.pt can be helpful for improving the performance of your custom model, especially when you have a limited amount of data. In this case, you can use the pretrained model to initialize the weights of your custom model and further finetune them during training. However, it depends on your specific use case and the available resources. 

Please let me know if you have any further questions or concerns.
