### ISSUE TITLE
not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by NooraldeenBarqawi** [ultralytics/ultralytics#2439]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Ultralytics YOLOv8.0.93 🚀 Python-3.10.11 torch-2.0.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
yolo/engine/trainer: task=detect, mode=train, model=yolov8l.pt, data=../content/drive/MyDrive/yoloD/plates/data.yaml, epochs=10, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs/detect/train4
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments                     
  0                  -1  1      1856  ultralytics.nn.modules.Conv                  [3, 64, 3, 2]                 
  1                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]               
  2                  -1  3    279808  ultralytics.nn.modules.C2f                   [128, 128, 3, True]           
  3                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]              
  4                  -1  6   2101248  ultralytics.nn.modules.C2f                   [256, 256, 6, True]           
  5                  -1  1   1180672  ultralytics.nn.modules.Conv                  [256, 512, 3, 2]              
  6                  -1  6   8396800  ultralytics.nn.modules.C2f                   [512, 512, 6, True]           
  7                  -1  1   2360320  ultralytics.nn.modules.Conv                  [512, 512, 3, 2]              
  8                  -1  3   4461568  ultralytics.nn.modules.C2f                   [512, 512, 3, True]           
  9                  -1  1    656896  ultralytics.nn.modules.SPPF                  [512, 512, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]                           
 12                  -1  3   4723712  ultralytics.nn.modules.C2f                   [1024, 512, 3]                
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]                           
 15                  -1  3   1247744  ultralytics.nn.modules.C2f                   [768, 256, 3]                 
 16                  -1  1    590336  ultralytics.nn.modules.Conv                  [256, 256, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]                           
 18                  -1  3   4592640  ultralytics.nn.modules.C2f                   [768, 512, 3]                 
 19                  -1  1   2360320  ultralytics.nn.modules.Conv                  [512, 512, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]                           
 21                  -1  3   4723712  ultralytics.nn.modules.C2f                   [1024, 512, 3]                
 22        [15, 18, 21]  1   5583571  ultralytics.nn.modules.Detect                [1, [256, 512, 512]]          
Model summary: 365 layers, 43630611 parameters, 43630595 gradients, 165.4 GFLOPs

Transferred 589/595 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs/detect/train4', view at http://localhost:6006/
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
optimizer: SGD(lr=0.01) with parameter groups 97 weight(decay=0.0), 104 weight(decay=0.0005), 103 bias
train: Scanning /content/drive/MyDrive/yoloD/plates/train/labels.cache... 10 images, 0 backgrounds, 10 corrupt: 100% 10/10 [00:00<?, ?it/s]
train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/1.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/10.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/2.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/3.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/4.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/5.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/6.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/7.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/8.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/9.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/cfg/__init__.py", line 394, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/model.py", line 370, in train
    self.trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py", line 191, in train
    self._do_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py", line 268, in _do_train
    self._setup_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py", line 250, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/v8/detect/train.py", line 59, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode, batch_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/v8/detect/train.py", line 33, in build_dataset
    return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == 'val', stride=gs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/build.py", line 74, in build_yolo_dataset
    dataset = YOLODataset(
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/dataset.py", line 39, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/base.py", line 69, in __init__
    self.labels = self.get_labels()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/dataset.py", line 132, in get_labels
    len_cls, len_boxes, len_segments = (sum(x) for x in zip(*lengths))
ValueError: not enough values to unpack (expected 3, got 0)

### Environment

Ultralytics YOLOv8.0.93 🚀 Python-3.10.11 torch-2.0.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
google colab

### Minimal Reproducible Example

! yolo task=detect mode=train model=yolov8l.pt data=../content/drive/MyDrive/yoloD/plates/data.yaml epochs=50 imgsz=640

### Additional

my labeling format is correct and none of the values is negative (object-class,x ,y,width,height)
for example: 15 0.516357 0.877279 0.260254 0.077474

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by hecheng000** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.
> 
> ### YOLOv8 Component
> Training
> 
> ### Bug
> Ultralytics YOLOv8.0.93 🚀 Python-3.10.11 torch-2.0.0+cu118 CUDA:0 (Tesla T4, 15102MiB) yolo/engine/trainer: task=detect, mode=train, model=yolov8l.pt, data=../content/drive/MyDrive/yoloD/plates/data.yaml, epochs=10, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs/detect/train4 Overriding model.yaml nc=80 with nc=1
> 
> ```
>                from  n    params  module                                       arguments                     
> ```
> 
> 0 -1 1 1856 ultralytics.nn.modules.Conv [3, 64, 3, 2] 1 -1 1 73984 ultralytics.nn.modules.Conv [64, 128, 3, 2] 2 -1 3 279808 ultralytics.nn.modules.C2f [128, 128, 3, True] 3 -1 1 295424 ultralytics.nn.modules.Conv [128, 256, 3, 2] 4 -1 6 2101248 ultralytics.nn.modules.C2f [256, 256, 6, True] 5 -1 1 1180672 ultralytics.nn.modules.Conv [256, 512, 3, 2] 6 -1 6 8396800 ultralytics.nn.modules.C2f [512, 512, 6, True] 7 -1 1 2360320 ultralytics.nn.modules.Conv [512, 512, 3, 2] 8 -1 3 4461568 ultralytics.nn.modules.C2f [512, 512, 3, True] 9 -1 1 656896 ultralytics.nn.modules.SPPF [512, 512, 5] 10 -1 1 0 torch.nn.modules.upsampling.Upsample [None, 2, 'nearest'] 11 [-1, 6] 1 0 ultralytics.nn.modules.Concat [1] 12 -1 3 4723712 ultralytics.nn.modules.C2f [1024, 512, 3] 13 -1 1 0 torch.nn.modules.upsampling.Upsample [None, 2, 'nearest'] 14 [-1, 4] 1 0 ultralytics.nn.modules.Concat [1] 15 -1 3 1247744 ultralytics.nn.modules.C2f [768, 256, 3] 16 -1 1 590336 ultralytics.nn.modules.Conv [256, 256, 3, 2] 17 [-1, 12] 1 0 ultralytics.nn.modules.Concat [1] 18 -1 3 4592640 ultralytics.nn.modules.C2f [768, 512, 3] 19 -1 1 2360320 ultralytics.nn.modules.Conv [512, 512, 3, 2] 20 [-1, 9] 1 0 ultralytics.nn.modules.Concat [1] 21 -1 3 4723712 ultralytics.nn.modules.C2f [1024, 512, 3] 22 [15, 18, 21] 1 5583571 ultralytics.nn.modules.Detect [1, [256, 512, 512]] Model summary: 365 layers, 43630611 parameters, 43630595 gradients, 165.4 GFLOPs
> 
> Transferred 589/595 items from pretrained weights TensorBoard: Start with 'tensorboard --logdir runs/detect/train4', view at http://localhost:6006/ AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n... AMP: checks passed ✅ optimizer: SGD(lr=0.01) with parameter groups 97 weight(decay=0.0), 104 weight(decay=0.0005), 103 bias train: Scanning /content/drive/MyDrive/yoloD/plates/train/labels.cache... 10 images, 0 backgrounds, 10 corrupt: 100% 10/10 [00:00<?, ?it/s] train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/1.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0 train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/10.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0 train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/2.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0 train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/3.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0 train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/4.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0 train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/5.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0 train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/6.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0 train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/7.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0 train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/8.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0 train: WARNING ⚠️ /content/drive/MyDrive/yoloD/plates/train/images/9.jpg: ignoring corrupt image/label: Label class 15 exceeds dataset class count 1. Possible class labels are 0-0 Traceback (most recent call last): File "/usr/local/bin/yolo", line 8, in sys.exit(entrypoint()) File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/cfg/**init**.py", line 394, in entrypoint getattr(model, mode)(**overrides) # default args from model File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/model.py", line 370, in train self.trainer.train() File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py", line 191, in train self._do_train(world_size) File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py", line 268, in _do_train self._setup_train(world_size) File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py", line 250, in _setup_train self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train') File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/v8/detect/train.py", line 59, in get_dataloader dataset = self.build_dataset(dataset_path, mode, batch_size) File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/v8/detect/train.py", line 33, in build_dataset return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == 'val', stride=gs) File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/build.py", line 74, in build_yolo_dataset dataset = YOLODataset( File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/dataset.py", line 39, in **init** super().**init**(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/base.py", line 69, in **init** self.labels = self.get_labels() File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/data/dataset.py", line 132, in get_labels len_cls, len_boxes, len_segments = (sum(x) for x in zip(*lengths)) ValueError: not enough values to unpack (expected 3, got 0)
> 
> ### Environment
> Ultralytics YOLOv8.0.93 🚀 Python-3.10.11 torch-2.0.0+cu118 CUDA:0 (Tesla T4, 15102MiB) google colab
> 
> ### Minimal Reproducible Example
> ! yolo task=detect mode=train model=yolov8l.pt data=../content/drive/MyDrive/yoloD/plates/data.yaml epochs=50 imgsz=640
> 
> ### Additional
> my labeling format is correct and none of the values is negative (object-class,x ,y,width,height) for example: 15 0.516357 0.877279 0.260254 0.077474
> 
> ### Are you willing to submit a PR?
> * [x]  Yes I'd like to help by submitting a PR!

How did you solve the same problem?

**Comment by glenn-jocher** [comment]
@hecheng000 hey there! 😊 It looks like the issue you're encountering is due to the class labels in your dataset. Your labels are marked as "15", but since your dataset is configured for a single class (nc=1), the valid class label should be "0". 

To fix this, you'll need to adjust your label files so that all instances of "15" are replaced with "0". Here's a quick example of how you can do this for one of your label files:

```python
# Example to change class label from 15 to 0 in a label file
with open('path/to/your/label/file.txt', 'r') as file:
    lines = file.readlines()
    lines = [line.replace('15', '0', 1) for line in lines]

with open('path/to/your/label/file.txt', 'w') as file:
    file.writelines(lines)
```

Make sure to apply this change to all your label files. This should resolve the error and allow your training to proceed without issues. If you have any more questions or run into further issues, feel free to ask. Good luck with your training! 🚀
