### ISSUE TITLE
Non-Moving Objects

### ISSUE THREAD

**Issue by dong-uk-kim97** [ultralytics/ultralytics#2440]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Please consider that I am using a translator because I am not good at English. I want to display the bounding box only for moving objects without processing the bounding box for non-moving objects. What should I do? Please tell me where to fix the code. Thank you

### Additional

my code is same as tutorial
```
import cv2
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('yolov8n.pt')

# Open the video file
cap = cv2.VideoCapture(0)

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 inference on the frame
        results = model(frame)

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Display the annotated frame
        cv2.imshow("YOLOv8 Inference", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()
```

**Comment by glenn-jocher** [comment]
@dong-uk-kim97 hello! To display bounding boxes only for moving objects, you can use a motion detection algorithm to determine which objects are moving and then pass only those objects to YOLOv8 for inference. One simple approach could be to use background subtraction, which involves taking the difference between the current frame and a background frame that does not contain any objects. Pixels that have changed significantly in the current frame are considered to be part of a moving object. You can then pass these moving objects to YOLOv8 for inference and display the resulting bounding boxes. To implement this, you can use OpenCV's background subtraction functions such as `cv2.createBackgroundSubtractorMOG2()` or `cv2.createBackgroundSubtractorKNN()`. 

Feel free to let us know if you have any other questions!

**Comment by dong-uk-kim97** [comment]
Thank you so much for your advice. I followed your advice but couldn't get better results. I was still on the webcam, but they drew a bounding box on me when I was still. Because I was lacking in code, I asked chatgpt to fix it. I made it recognize the object as the fps changes, but I don't know how to fix it. Below is the code written by chatgpt.

### my code
```
import cv2
import time
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('yolov8n.pt')

# Create the background subtractor object
back_sub = cv2.createBackgroundSubtractorMOG2()

# Open the video file
cap = cv2.VideoCapture(0)

# Get the video FPS and frame size
fps = cap.get(cv2.CAP_PROP_FPS)
frame_size = (int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)), int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)))

# Create a VideoWriter object to save the output video
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter('output.mp4', fourcc, fps, frame_size)

# Initialize variables for FPS calculation
frame_count = 0
start_time = time.time()

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Apply the background subtractor to the frame
        fg_mask = back_sub.apply(frame)

        # Run YOLOv8 inference on the frame
        results = model(frame)

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Combine the foreground mask and annotated frame
        fg_mask = cv2.cvtColor(fg_mask, cv2.COLOR_GRAY2BGR)
        combined_frame = cv2.addWeighted(annotated_frame, 0.5, fg_mask, 0.5, 0)

        # Write the combined frame to the output video
        out.write(combined_frame)

        # Display the combined frame
        cv2.imshow("YOLOv8 Inference", combined_frame)

        # Update the FPS calculation variables
        frame_count += 1
        elapsed_time = time.time() - start_time

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break

        # Delay the output to match the video FPS
        if elapsed_time < (frame_count / fps):
            time.sleep((frame_count / fps) - elapsed_time)
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture and output objects, and close the display window
cap.release()
out.release()
cv2.destroyAllWindows()
```

**Comment by glenn-jocher** [comment]
Dear @dong-uk-kim97, thank you for trying out YOLOv8 and sharing your code with us.

From your code, it seems like you have incorporated a background subtractor to detect moving objects and passed only those objects to YOLOv8 for inference. However, you have mentioned that a bounding box is drawn on still objects as well. This might happen if there is still noise in the foreground mask or if the background model is not stable enough. You can try tuning some of the background subtractor parameters such as number of components, history, learning rate, and shadow detection to improve the accuracy of the foreground mask.

You have also mentioned that the object recognition changes with fps. This could happen if the frame rate synchronization between the background subtractor and YOLOv8 is not handled properly. One solution could be to adjust the delay in between each frame such that it matches the frame rate of the input video. You can try setting the delay to `(1/fps) - elapsed_time` to achieve this, where `elapsed_time` is the time taken to process the current frame.

I hope these suggestions help improve your results. Feel free to let us know if you have any other questions or need further assistance.

**Comment by dong-uk-kim97** [comment]
Thanks for the advice I used yolov5 for my project last year, but yolov8! It's amazing. If there is a model from ultralytics in the future, I will use it often! Thank you.

**Comment by glenn-jocher** [comment]
@dong-uk-kim97 thank you for your kind words and for trying out YOLOv8! We are glad to hear that you found it amazing and we appreciate your support. Please feel free to share any feedback or suggestions you may have as we are always looking for ways to improve our models and user experience.

**Comment by Shubham77saini** [comment]
@glenn-jocher Hi, Shubham Saini this side. I want to know how I can detect moving vehicles in green bbox and the vehicles that stop suddenly in red bbox. For moving vehicles we can apply a motion detector algorithm but what about suddenly stopping the vehicle (eg. A car is moving but when a red light happens it will stop slowly slowly. ).

**Comment by glenn-jocher** [comment]
@Shubham77saini hello Shubham Saini! To detect moving vehicles with a green bounding box, you can indeed apply a motion detection algorithm. For detecting vehicles that stop suddenly and marking them with a red bounding box, you will need to analyze the change in the vehicle's position over successive frames. You could track the vehicles' centroids and calculate the difference in their positions over time. Sudden drops in speed (a quick reduction in the change of position) could be an indicator of a stopping vehicle. You would need to establish a threshold for what constitutes "suddenly stopping" based on the frame rate and expected vehicle speeds in your application. Then, based on this analysis, you can overlay the corresponding colored bounding boxes onto your video frames using OpenCV. Keep up the great work on your projects! 👍

**Comment by Shubham77saini** [comment]
@glenn-jocher Thankyou
