### ISSUE TITLE
Show the label info on images. 

### ISSUE THREAD

**Issue by darouwan** [ultralytics/ultralytics#2443]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In the doc https://docs.ultralytics.com/yolov5/tutorials/train_custom_data/#12-create-labels, I noticed roboflow is recommended to used to label the images and this file ([ultralytics/yolo/data/converter.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/data/converter.py#LL13C28-L13C28)) can also convert the COCO format to YOLOv8 compatible format.

So if I already had a YOLOv8 labelling dataset, how to check if the annotation box is right? Any tools can convert the YOLO dataset back to COCO format or show the labelling info on images directly?

**Comment by glenn-jocher** [comment]
@darouwan thank you for your question! 

If you have a YOLOv8 labeling dataset, you can use the popular image annotation tool, LabelImg (https://github.com/tzutalin/labelImg), to visualize your annotation box and check if they are correct by loading and viewing your images with annotations. However, there does not appear to be a tool to directly convert YOLOv8 format to COCO format, but, the `ultralytics/yolo/data/converter.py` file, as you mentioned, can convert COCO format to YOLOv8 format. 

I hope this helps! Please feel free to let us know if you have any additional questions or concerns.

**Comment by Avv22** [comment]
Is there a step by step guide please how to split data intro training and testing and building configuration file? I have labelled data for one-class using labelimg where I have only one class:
