### ISSUE TITLE
Yolo detection error help me

### ISSUE THREAD

**Issue by SliverAward** [ultralytics/ultralytics#2445]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

**train.py**
`
from ultralytics import YOLO

## Load the model.
model = YOLO('C:\\yolov8\\yolov8n.pt')

## Training.
if __name__ == '__main__':
    results = model.train(
        data='C:\\yolov8\\dataset\\data.yaml',
        imgsz=416,
        patience=50,
        epochs=100,
        batch=10,
        name='yolov8n_custom')`
        
**detect.py**
`from ultralytics import YOLO
from ultralytics.yolo.v8.detect.predict import DetectionPredictor
import cv2

model = YOLO("C:\\yolov8\\runs\\detect\\train5\\weights\\best.pt")
#model = YOLO(/home/esp/yolov8/best.pt)

results = model.predict(source="1", show=True)

print(*results)
`

**detection result**
![image](https://user-images.githubusercontent.com/115061522/236654384-6e18af1f-0805-48b0-8e5c-e61f2d446fde.png)
![image](https://user-images.githubusercontent.com/115061522/236654392-9763ce84-c6a5-4194-bf8d-c72187e3637c.png)

After training, I moved the 'best.pt' file to my Raspberry Pi 4 and ran detection. However, too many bounding boxes are displayed. Could this be a problem during training?

**Comment by AyushExel** [comment]
try increasing the conf value with `model.predict(..., conf=0.5)`. THe default value is 0.25 which works for most cases but it seems it requires some tuning in your case.

**Comment by SliverAward** [comment]
> try increasing the conf value with `model.predict(..., conf=0.5)`. THe default value is 0.25 which works for most cases but it seems it requires some tuning in your case.

재학습하고 나와 다시 디텍션해보니 바운딩박스가 줄었습니다!

추후 문제가 다시 발생한다면 참고하겠습니다! 감사해요!

**Comment by glenn-jocher** [comment]
@SliverAward you're welcome! We're glad to hear that increasing the conf value helped reduce the number of bounding boxes in your detection results. Please don't hesitate to reach out to us if you have any further questions or issues with YOLOv8 in the future. Thank you for using our repo.
