### ISSUE TITLE
Testing the exported checkpoints (torchscript, onnx...) with detect.DetectionPredictor class

### ISSUE THREAD

**Issue by kangyeolk** [ultralytics/ultralytics#2446]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to test the exported checkpoints (torchscript, onnx...) with `detect.DetectionPredictor` class. However, I got error when calling `setup_model`.

```
predictor.setup_model(ckpt_path)
outputs = predictor(source=dummy_image)
```
Does YOLOv8 not support this workflow yet?
Thank you in advance 😀.

**Comment by kangyeolk** [comment]
I solved this problem by upgrading PyTorch version to 2.0

**Comment by glenn-jocher** [comment]
@kangyeolk, 

Thank you for sharing the solution that worked for you! However, YOLOv8 requires PyTorch >= 1.7, which is currently the latest version of PyTorch. Therefore, upgrading to PyTorch 2.0 may not be necessary and may even cause compatibility issues with YOLOv8. 

If you encounter any further issues, feel free to submit a new issue on the YOLOv8 GitHub repository. Our team will be happy to help you.
