### ISSUE TITLE
Training memory leak

### ISSUE THREAD

**Issue by fortminors** [ultralytics/ultralytics#2449]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I have found out that if you run `model.train(...)` in the same process several times, each run leaks memory after its done. This eventually leads to OOM errors.

### Environment

```
- ultralytics 8.0.89
- ubuntu 22.04
- python 3.8.10
- torch 2.0.0+cu118
```

### Minimal Reproducible Example
```
from ultralytics import YOLO

model = YOLO("yolov8m-seg.pt")
for _ in range(10):
    model.train(data="coco128.yaml", epochs=3)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @fortminors, thank you for bringing this issue to our attention. We appreciate you taking the time to share your experience with YOLOv8. 

Unfortunately, there seems to be a memory leak issue when running `model.train(...)` multiple times in the same process. We apologize for the inconvenience this may have caused you.

To help resolve this issue, we suggest running each instance of `model.train(...)` in a separate process or to restart the process after each run to free up memory. We will make sure to document this in the future to prevent other users from running into this issue. 

If you have any additional questions or concerns, please don't hesitate to let us know.

**Comment by joshniemela** [comment]
Is there a reason this cannot be fixed by deleting `model.trainer.train_loader` and `model.trainer_test_loader`?

**Comment by glenn-jocher** [comment]
@joshniemela thank you for the follow-up question.

While manually deleting objects such as `model.trainer.train_loader` and `model.trainer_test_loader` might seem like a potential workaround, this may not address all potential sources of memory leaks. In Python, memory leaks can occur for various reasons, including but not limited to, circular references or native resources not being released properly.

Properly identifying and fixing memory leaks can be complex and generally requires a thorough analysis of object life cycles and references. The issue might lie within our codebase or could be associated with external libraries and frameworks we rely on, such as PyTorch. Hence, it is not always guaranteed that manually deleting certain objects will resolve the issue.

Our team is committed to continuously improving our models, and we appreciate your input on possible solutions. We will investigate the issue further and look for any objects that may not be getting cleaned up correctly between training runs. In the meantime, we do recommend isolating each training run in its own process as a temporary measure to avoid the accumulation of memory usage.

If you have any more insights or specific suggestions on where memory might not be freeing up, feel free to share those details as they could be helpful for us in diagnosing and solving the problem. Your cooperation and patience are much appreciated as we work on ensuring the reliability and performance of YOLOv8.

**Comment by willshw** [comment]
> Hello @fortminors, thank you for bringing this issue to our attention. We appreciate you taking the time to share your experience with YOLOv8.
> 
> Unfortunately, there seems to be a memory leak issue when running `model.train(...)` multiple times in the same process. We apologize for the inconvenience this may have caused you.
> 
> To help resolve this issue, we suggest running each instance of `model.train(...)` in a separate process or to restart the process after each run to free up memory. We will make sure to document this in the future to prevent other users from running into this issue.
> 
> If you have any additional questions or concerns, please don't hesitate to let us know.

@glenn-jocher Is this documented somewhere that I can refer to? I had the same issue and just found out this post buried deep in the closed issues.

**Comment by glenn-jocher** [comment]
@willshw thank you for your feedback. We're working on documenting this issue more clearly. Please ensure you're using the latest version of the package, as updates may address this. If the problem persists, feel free to reach out here.
