### ISSUE TITLE
Core dumps when training new model

### ISSUE THREAD

**Issue by wvalcke** [ultralytics/ultralytics#245]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Training goes fine for a moment (about 100 epochs), then all of a sudden it stops, much more errors then happen, to finally dumping a core.
It seems there are threading issues in the code.

Exception ignored in: <function Image.__del__ at 0x7fa1307a3b80>
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 4017, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Thanks for reporting. Can you tell us the exact command you ran?
@glenn-jocher @Laughing-q it's strange to see tkinter in the crash log?

**Comment by wvalcke** [comment]
Hi Ayush,

When i'm back tomorrow i'll let you know, one thing i tested was running again with the added option plot=false. Then it trained for 1200 epochs.
Before leaving i started again the training with the original options, let's see if it went ok or not. i'll keep you informed.

**Comment by ganghyunnnn** [comment]
I also faced with the same issue.

After running 185 epochs, training suddenly stopped.

Here is my running command

yolo task=detect model=yolov8x.pt data=data/data.yaml epochs=300 imgsz=1280 batch=8 patience=0 device=0 overlap_mask=False name=v8x

**Comment by jayer95** [comment]
I also got the same issue.

❯ yolo task=detect mode=train model=yolov8n-hagrid4k_se_half_add_snape4k_half_rechecked_aug_add_snape4k_half_aug_640.yaml d
ata=hagrid4k_se_half_add_snape4k_half_rechecked_aug_add_snape4k_half_aug.yaml device=0 epochs=150 batch=32 imgsz=640 rect=true workers=8 translate=0 scale=0 fliplr=0 mosaic=0
                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.Conv                  [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.Conv                  [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.C2f                   [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.C2f                   [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.C2f                   [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.SPPF                  [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]
 12                  -1  1    148224  ultralytics.nn.modules.C2f                   [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]
 15                  -1  1     37248  ultralytics.nn.modules.C2f                   [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.Conv                  [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]
 18                  -1  1    123648  ultralytics.nn.modules.C2f                   [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.Conv                  [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]
 21                  -1  1    493056  ultralytics.nn.modules.C2f                   [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.Detect                [1, [64, 128, 256]]
YOLOv8n-hagrid4k_se_half_add_snape4k_half_rechecked_aug_add_snape4k_half_aug_640 summary: 225 layers, 3011043 parameters, 3011027 gradients, 8.2 GFLOPs

Ultralytics YOLOv8.0.4 🚀 Python-3.9.15 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24252MiB)
yolo/engine/trainer: task=detect, mode=train, model=yolov8n-hagrid4k_se_half_add_snape4k_half_rechecked_aug_add_snape4k_half_aug_640.yaml, data=hagrid4k_se_half_add_snape4k_half_rechecked_aug_add_snape4k_half_aug.yaml, epochs=150, patience=50, batch=32, imgsz=640, save=True, cache=False, device=0, workers=8, project=None, name=None, exist_ok=False, pretrained=False,optimizer=SGD, verbose=False, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=True, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, retina_masks=False, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0, scale=0, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0, mosaic=0, mixup=0.0, copy_paste=0.0, cfg=None, hydra={'output_subdir': None, 'run': {'dir': '.'}}, v5loader=False, save_dir=runs/detect/train2

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.Conv                  [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.Conv                  [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.C2f                   [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.C2f                   [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.C2f                   [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.SPPF                  [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]
 12                  -1  1    148224  ultralytics.nn.modules.C2f                   [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]
 15                  -1  1     37248  ultralytics.nn.modules.C2f                   [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.Conv                  [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]
 18                  -1  1    123648  ultralytics.nn.modules.C2f                   [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.Conv                  [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]
 21                  -1  1    493056  ultralytics.nn.modules.C2f                   [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.Detect                [1, [64, 128, 256]]
YOLOv8n-hagrid4k_se_half_add_snape4k_half_rechecked_aug_add_snape4k_half_aug_640 summary: 225 layers, 3011043 parameters, 3011027 gradients, 8.2 GFLOPs

optimizer: SGD(lr=0.01) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias
WARNING ⚠️ --rect is incompatible with DataLoader shuffle, setting shuffle=False
train: Scanning /home/gvsai/datasets/us/hagrid4k_se_half_add_snape4k_half_rechecked_aug_add_snape4k_half_aug/raw_pos/labels
val: Scanning /home/gvsai/datasets/us/hagrid4k_se_half_add_snape4k_half_rechecked_aug_add_snape4k_half_aug/raw_pos/labels/v
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs/detect/train2
Starting training for 150 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/150      1.56G      1.967      26.75      1.121         31        640: 100%|██████████| 5777/5777 [14:31<00:00,  6.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 35/35 [00:17<00:
                   all       2202       4171      0.922      0.832      0.933      0.775

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/150      1.56G     0.7706      0.408     0.8043         31        640: 100%|██████████| 5777/5777 [14:24<00:00,  6.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 35/35 [00:14<00:
                   all       2202       4171      0.916      0.888      0.956      0.851

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/150      1.56G     0.6976     0.3682     0.7942         31        640: 100%|██████████| 5777/5777 [14:13<00:00,  6.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 35/35 [00:14<00:
                   all       2202       4171      0.912       0.91      0.961      0.867

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/150      1.56G     0.6422     0.3401     0.7883         31        640: 100%|██████████| 5777/5777 [14:16<00:00,  6.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 35/35 [00:14<00:
                   all       2202       4171      0.928       0.92      0.966      0.878

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/150      1.56G     0.6001      0.316     0.7837         31        640: 100%|██████████| 5777/5777 [14:23<00:00,  6.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 35/35 [00:16<00:
                   all       2202       4171      0.933      0.918      0.967      0.878

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/150      1.56G     0.5793     0.3035     0.7816         31        640: 100%|██████████| 5777/5777 [14:21<00:00,  6.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 35/35 [00:14<00:
                   all       2202       4171      0.936      0.916      0.967      0.878

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/150      1.56G     0.5659     0.2964     0.7804         31        640: 100%|██████████| 5777/5777 [14:39<00:00,  6.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 35/35 [00:15<00:
                   all       2202       4171      0.938      0.915      0.968       0.88

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/150      1.56G     0.5552     0.2907     0.7793         31        640: 100%|██████████| 5777/5777 [14:41<00:00,  6.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 35/35 [00:15<00:
                   all       2202       4171      0.938      0.917      0.969      0.881

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/150      1.56G      0.549     0.2867     0.7788         31        640: 100%|██████████| 5777/5777 [14:35<00:00,  6.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 35/35 [00:15<00:
                   all       2202       4171      0.938      0.917      0.968      0.882

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/150      1.56G     0.5419     0.2829     0.7782         31        640: 100%|██████████| 5777/5777 [14:45<00:00,  6.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 35/35 [00:19<00:
                   all       2202       4171      0.939      0.916      0.968      0.885

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/150      1.56G     0.5379     0.2801     0.7778         31        640: 100%|██████████| 5777/5777 [14:53<00:00,  6.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 35/35 [00:15<00:
                   all       2202       4171      0.938      0.913      0.968      0.885

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/150      1.56G     0.5334     0.2778     0.7775         31        640: 100%|██████████| 5777/5777 [14:24<00:00,  6.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 35/35 [00:15<00:
                   all       2202       4171      0.939      0.911      0.967      0.886

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/150      1.56G      0.536     0.2778     0.7775         47        640:  10%|▉         | 573/5777 [01:27<09:01,  9.6Exception ignored in: <function Image.__del__ at 0x7fbd8249c550>
Traceback (most recent call last):
  File "/home/gvsai/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 4017, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
     13/150      1.56G      0.536     0.2778     0.7775         47        640:  10%|▉         | 573/5777 [01:38<09:01,  9.6Exception ignored in: <function Variable.__del__ at 0x7fbd82502c10>
Traceback (most recent call last):
  File "/home/gvsai/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x7fbd82502c10>
Traceback (most recent call last):
  File "/home/gvsai/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x7fbd82502c10>
Traceback (most recent call last):
  File "/home/gvsai/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x7fbd82502c10>
Traceback (most recent call last):
  File "/home/gvsai/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7fbd8249c550>
Traceback (most recent call last):
  File "/home/gvsai/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 4017, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x7fbd82502c10>
Traceback (most recent call last):
  File "/home/gvsai/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x7fbd82502c10>
Traceback (most recent call last):
  File "/home/gvsai/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x7fbd82502c10>
Traceback (most recent call last):
  File "/home/gvsai/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x7fbd82502c10>
Traceback (most recent call last):
  File "/home/gvsai/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread
[1]    3276305 abort (core dumped)  yolo task=detect mode=train   device=0 epochs=150 batch=32 imgsz=640 rect=tru

**Comment by wvalcke** [comment]
I can confirm that adding the plots=false makes it working, i tested again with plots=true (which is the default), and it crashed again. 
So at least i can reproduce this problem. The problem must have something to do with the plots being generated each epoch. In yolov5 this was only done at the end. There is probably some threading issue.

Exception ignored in: <function Image.__del__ at 0x7fd9546493a0>
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 4017, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    35/1200      8.39G     0.3894     0.3237     0.8818         64        640: 100%|██████████| 11/11 [00:02<00:00,  3.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):  33%|███▎      | 2/6 [00:01<00:02,  1.56it/s]Exception ignored in: <function Variable.__del__ at 0x7fd95474fa60>
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 6/6 [00:03<00:00,  1.69it/s]
                   all        343        486      0.967      0.924       0.96      0.899

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    36/1200      8.39G     0.3814     0.3229     0.8799         58        640: 100%|██████████| 11/11 [00:02<00:00,  3.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 6/6 [00:03<00:00,  1.74it/s]
Exception ignored in: <function Variable.__del__ at 0x7fd95474fa60>
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x7fd95474fa60>
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
                   all        343        486      0.954      0.889      0.956      0.888
Exception ignored in: <function Variable.__del__ at 0x7fd95474fa60>
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread
Aborted (core dumped)

**Comment by Laughing-q** [comment]
@wvalcke hi can you use the latest version? I think `plot=True` should only work when it's the final epoch.
[https://github.com/ultralytics/ultralytics/blob/d0b616e41e827e1ac65ee99da1339e707a984989/ultralytics/yolo/engine/validator.py#L90](https://github.com/ultralytics/ultralytics/blob/d0b616e41e827e1ac65ee99da1339e707a984989/ultralytics/yolo/engine/validator.py#L90)
and yes it looks like a threading issue, we plot these images with multi threads. But actually it works well in our tests.

**Comment by wvalcke** [comment]
@Laughing-q 

No, it's not that code that's responsible for the problems. Indeed the plots for validation are only created at the end of the training. But that's the creation of images of max 3 batches of the validation set which indicate the real annotations and what the best trained weights predicted. This code is only executed at the end of the training.
The problem is related to the f1, pr, recall, precision,  etc... curves created after each epoch. 
In the older yolov5 code, those curves were only created at the end of the training. Now they seem to be created/updated during training. It looks to me that there we have a problem...

**Comment by glenn-jocher** [comment]
@wvalcke we should have a solution by @Laughing-q merged in https://github.com/ultralytics/ultralytics/pull/292 and scheduled to merge to main and deploy to 8.0.5 later today.

**Comment by wvalcke** [comment]
Ok fine, thanks for the speedy responses!
I will test it once more to see what it gives. I'll let you know.

**Comment by pderrenger** [comment]
@wvalcke glad to hear that the issue seems to be resolved! Feel free to reach out if you encounter any further issues or have additional feedback. Thanks for your collaboration!
