### ISSUE TITLE
Different pre-process and post-process speeds of the exported models.

### ISSUE THREAD

**Issue by kangyeolk** [ultralytics/ultralytics#2451]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have found that speeds of pre-/post-processing operations are different depending on export formats. My first guess is that only inference time would be different. Can you explain why these time differences occur?

## Environment
```
- ultralytics 8.0.87
- ubuntu 20.04
- python 3.9
- torch 2.0.0+cu117
```

## Rough implementation code
```python
def eval_speeds(predictor, dummy_image=None, iters=100):
    v = {'preprocess': 0., 'inference': 0., 'postprocess': 0.}
    for i in tqdm(range(iters)):
        outputs = predictor(source=dummy_image)
        speed_info = outputs[0].speed
        for ps, value in speed_info.items():
            v[ps] += value 
    avg_v = {ps: value / iters for ps, value in v.items()}
    return avg_v

# Check inference speed
avg_v = eval_speeds(predictor, dummy_image, iters=infer_iters)            
s = f'\nBenchmarks complete ✅ for {name}; {avg_v}(ms)\n'
LOGGER.info(s)
```

## Screenshot
![image](https://user-images.githubusercontent.com/26561999/236680265-a7aeefb7-e16a-43fb-8c86-3ff9e2398d32.png)

**Comment by glenn-jocher** [comment]
@kangyeolk dear [username], thanks for reaching out to us. The pre-processing, inference, and post-processing times of YOLOv8 vary depending on export formats. This is because different formats have different tensor sizes and shapes, which can affect network efficiency and inference time. However, it's worth noting that this should only have a minor impact on performance, and the network is optimized to work with each respective format. If you have further questions, please don't hesitate to ask. Have a great day!

**Comment by kangyeolk** [comment]
Thank you for your help!

**Comment by glenn-jocher** [comment]
@kangyeolk sure, I'll do my best to provide a succinct and clear response. Based on your question, it sounds like you're having some trouble with the pre-processing step in YOLOv8. Specifically, you'd like to know how to resize your input images to a specific size before running them through the network. 

To accomplish this in YOLOv8, you can use the `yolo8_m` function, which applies a number of transformations to the input image, such as resizing, normalization, and conversion to a tensor. Then, you can simply pass this tensor to the network for inference. 

To resize your input image to a specific size, you can modify the `new_size` argument of the `yolo8_m` function to your desired dimensions. This will automatically resize your input image to the target size while maintaining its aspect ratio. 

I hope this answers your question! Let me know if you have any further doubts or need additional assistance.
