### ISSUE TITLE
Modifications to plot do not have any effects

### ISSUE THREAD

**Issue by michelebechini** [ultralytics/ultralytics#2453]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Hi everyone!

I am using the yolov8-pose to detect BBoxes and Keypoints in some custom images. For my research I need to generate more plots and to modify some of the existing ones, in particular the ones related to the Precision-Recall curves.

I tried doing simple modifications (e.g. changing the title or the color of the line) in the plots defined in `/ultralytics/yolo/utils/metrics.py` in the function `plot_pr_curve`, but unfortunately all the modifications that I apply here are not reflected in the output plots at the end of the training phase nor for the boxes nor for the pose.
I put below the simple modification that I made to the `plot_pr_curve`.

Maybe the final plotting phase use other functions and algorithms that I am not aware of...

Can you please provide me some help? 

Thanks in advance and great work!!! 

### Environment

- YOLO: Ultralytics YOLOv8.0.93 🚀 Python-3.11.3 torch-2.0.0+cu117 CUDA:0 (NVIDIA RTX A6000, 48677MiB)
- OS: Ubuntu 20.04.5 LTS (Focal Fossa)
- Python: Python-3.11.3

### Minimal Reproducible Example

```
def plot_pr_curve(px, py, ap, save_dir=Path('pr_curve.png'), names=()):
    """Plots a precision-recall curve."""
    fig, ax = plt.subplots(1, 1, figsize=(9, 6), tight_layout=True)
    py = np.stack(py, axis=1)

    if 0 < len(names) < 21:  # display per-class legend if < 21 classes
        for i, y in enumerate(py.T):
            ax.plot(px, y, linewidth=1, label=f'{names[i]} {ap[i, 0]:.3f}')  # plot(recall, precision)
    else:
        ax.plot(px, py, linewidth=1, color='grey')  # plot(recall, precision)

    ax.plot(px, py.mean(1), linewidth=3, color='blue', label='all classes %.3f mAP@0.5' % ap[:, 0].mean())
    ax.set_xlabel('Recall')
    ax.set_ylabel('Precision')
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.legend(bbox_to_anchor=(1.04, 1), loc='upper left')
    ax.set_title('Precision-Recall Curve - TEST TITLE')
    fig.savefig(save_dir, dpi=250)
    plt.close(fig)
```

By modifying the default function with the one reported here, the title of the image should be "Precision-Recall Curve **- TEST TITLE**", but the plotted title is still "Precision-Recall Curve".

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by michelebechini** [comment]
Mmmh I am a bit lost. The `plot_pr_curve()` function from `/ultralytics/yolo/utils/metrics.py` is called inside the function `ap_per_class` inside `/ultralytics/yolo/utils/metrics.py`. If I modify directly the `plot_pr_curve()` as in the example reported [above](https://github.com/ultralytics/ultralytics/issues/2453#issue-1699168785), the modifications do not affect the results. 

For my understanding the `plot_results()` function plots the values inside the file `results.csv`. My intention is to modify the plot that are saved under the name `PosePR_curve.png` and `BoxPR_curve.png`.

Concerning the `test.py`, I am not able to lacate it, did you mean the `val.py`?

Can you please provide me a little more help please? Thanks in advance

**Comment by michelebechini** [comment]
I solved this issue. The problem is that I correctly modified the scripts in the cloned repo, but I was still using the package installed via `pip install ultralytics` instead of using `pip install -e .`, hence all my modifications do not have any effects. Now everything works perfectly.

@glenn-jocher  thanks for the support!!!

I close this issue.

**Comment by glenn-jocher** [comment]
Great to hear that you were able to solve the issue, @michelebechini! Thank you for sharing your solution with us, which is helpful for other users who may encounter the same problem.

It is important to note that If one modifies the scripts in the cloned repo, it is necessary to use `pip install -e .` to install the current developmental version of the package. This command installs the local directory in "editable" mode, meaning that any changes made in the scripts while the package is installed, will be applied immediately without the need to reinstall.
 
If you have further questions, don't hesitate to ask. Thank you for your interest in YOLOv8 and have a great day!
