### ISSUE TITLE
Segment dataset format

### ISSUE THREAD

**Issue by velastin** [ultralytics/ultralytics#2454]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

What is the format of the label files for segmentation? Are they polygons?

### Additional

Enjoying the repository. I would like to train for a custom segmentation dataset
I would like to double check what is the format of the labels files (the groundtruth).
I found this:
https://docs.ultralytics.com/tasks/segment/#dataset-format

cls x1 y1 x2 y2 p1 p2 ... pn
What is the meaning of each one? Are the segmentation masks represented by a (closed) polygon (segments)?
I also assume that they are given relative to image width and height (as per conventional bbox-based data).

My data would be based in the form of image masks (let's say binary masks). Any suggestions on converting these to polygons?
Thanks

**Comment by SuperGentry** [comment]
I use labelme to label the image, and then convert the Json format to Txt format for training. You can search for the python code from Labelme to YOLO. I hope it can help you.

**Comment by velastin** [comment]
Thanks. My images are pixel masks not polygons (I think labelme creates polygons). So I assume I have to find a way to change the mask in the images to polygons. So in the YOLO documentation, what is "x1 y1 x2 y2" and what is "p1 p2 ... pn"?. Perhaps x1 y1 x2 y2 is a bounding box and then p1 p2 ... the polygon coordinates? It is not clear.

**Comment by glenn-jocher** [comment]
@velastin thanks for reaching out! 

In the YOLOv8 documentation, the "x1 y1 x2 y2" refers to the coordinates of the bounding box around an object. Specifically, "x1 y1" represent the coordinates of the top-left corner of the bounding box, and "x2 y2" represent the coordinates of the bottom-right corner of the bounding box.

The "p1 p2 ... pn" section of the label file refers to the coordinates of the polygon that represents the segmentation mask. Each coordinate "pi" is represented by its x and y value in the format "x,y". 

As you mentioned, if you have pixel masks as opposed to polygons, you will need to convert these masks to polygons in order to use them with YOLOv8. One potential approach could be to use a library like OpenCV to find the contour of the mask and then represent that contour as a polygon. 

I hope this helps! Let me know if you have any further questions.

**Comment by velastin** [comment]
Many thanks Glenn. That is very useful.
I assume that all the x,y coordinates are given relative to width,height
I found this package to compute the polygon from a mask: 
https://github.com/jsbroks/imantics
import numpy as np
from imantics import Polygons, Mask

# This can be any array
array = np.ones((100, 100))

polygons = Mask(array).polygons()

print(polygons.points)
print(polygons.segmentation)

**Comment by glenn-jocher** [comment]
@velastin you're welcome, and yes, that is correct - all the x, y coordinates are given relative to the width and height of the image.

Regarding the conversion of pixel masks to polygons, the package you found looks like a good option. The code you provided seems straightforward as well. You can use the `np.ones()` function to create a binary mask (where all foreground pixels have a value of 1, and all background pixels have a value of 0) representing the segmentation of your object. You can then use this binary mask to create a `Mask` object from the `imantics` package and extract the `Polygons` object corresponding to the object's segmentation.

Hope this helps! Let me know if you have any further questions.

**Comment by SV1367** [comment]
Thanks again Glenn. It turns out that imantics has some problems computing polygons in a number of cases, especially if the masks have been generated by segmentation methods! Will have a look at opencv instead

**Comment by glenn-jocher** [comment]
Thanks for the update, @SV1367. That's a good point - when the segmentation is done by machine, there may be multiple contours corresponding to a single object. In these cases, additional processing may be necessary to merge the contours into a single polygon representation for use with YOLOv8. 

OpenCV's `findContours` function is a good option for extracting the contours from a binary mask, and can provide additional parameters to control things like retrieval mode and contour approximation. Once you've extracted the contours, you'll need to process them to merge any overlapping or adjacent contours into a single polygon representation.

Let me know if you have any further questions on this topic!

**Comment by ge1mina023** [comment]
> @velastin thanks for reaching out!
> 
> In the YOLOv8 documentation, the "x1 y1 x2 y2" refers to the coordinates of the bounding box around an object. Specifically, "x1 y1" represent the coordinates of the top-left corner of the bounding box, and "x2 y2" represent the coordinates of the bottom-right corner of the bounding box.
> 
> The "p1 p2 ... pn" section of the label file refers to the coordinates of the polygon that represents the segmentation mask. Each coordinate "pi" is represented by its x and y value in the format "x,y".
> 
> As you mentioned, if you have pixel masks as opposed to polygons, you will need to convert these masks to polygons in order to use them with YOLOv8. One potential approach could be to use a library like OpenCV to find the contour of the mask and then represent that contour as a polygon.
> 
> I hope this helps! Let me know if you have any further questions.

@glenn-jocher According to the [https://docs.ultralytics.com/datasets/segment/](url), the correct format is <class-index> <x1> <y1> <x2> <y2> ... <xn> <yn>. Where are special x1 y1 and x2 y2 ? BTW, according to the [https://docs.ultralytics.com/datasets/segment/](url), segmentation result don't have bounding box? OR, it supports two format(<class-index> <x1> <y1> <x2> <y2> ... <xn> <yn>
 and <class-index> cls cx cy w h <y1> <x2> <y2> <x1> <y1> <x2> <y2> ... <xn> <yn>
)?
