### ISSUE TITLE
Yolo Pose points labelling

### ISSUE THREAD

**Issue by Ykrowa** [ultralytics/ultralytics#2458]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How does yolo pose work? can i mark points outside the bbox area? Or points must be located inside bbox?

**Comment by glenn-jocher** [comment]
Hi @Ykrowa, 

In YOLOv8 pose estimation, you can mark points outside the bounding box area. The objective is to detect and label keypoints for an object within the image, regardless of their position in relation to the bounding box. 

You can mark keypoints for the head, shoulders, hip, etc. that are outside the current detected bounding box of the object/person. 

Hope that helps! Let us know if you have any further questions.
