### ISSUE TITLE
Pytorch 1.8.0 supprt

### ISSUE THREAD

**Issue by Goldenshluger** [ultralytics/ultralytics#2459]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello I am running on Jetson Nano platform with CUDA10.2
I manually built PyTorch 1.8 on Python 3.7. I thought this version would suffice, because your requirements file says PyTorch>=1.7.0

But now, when i try to import ultralytics, I get: ModuleNotFoundError: No module named 'torch.ao'. Building pytorch on a portable robot platform takes around 8 hours, so I can not really do to many experiments. I tried pytorch 1.7 and 1.8, both with no luck.

Is there a way to run ultralytics on Python 3.7 and CUDA10.2? What version of PyTorch should i build next?

**Comment by Goldenshluger** [comment]
**Here is a list of all satisfied requirements:**

Requirement already satisfied: matplotlib>=3.2.2 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from ultralytics==8.0.94) (3.5.3)
Requirement already satisfied: opencv-python>=4.6.0 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from ultralytics==8.0.94) (4.7.0.72)
Requirement already satisfied: Pillow>=7.1.2 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from ultralytics==8.0.94) (9.5.0)
Requirement already satisfied: PyYAML>=5.3.1 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from ultralytics==8.0.94) (6.0)
Requirement already satisfied: requests>=2.23.0 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from ultralytics==8.0.94) (2.30.0)
Requirement already satisfied: scipy>=1.4.1 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from ultralytics==8.0.94) (1.7.3)
Requirement already satisfied: torch>=1.7.0 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from ultralytics==8.0.94) (1.8.0a0+37c1f4a)
Requirement already satisfied: torchvision>=0.8.1 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from ultralytics==8.0.94) (0.14.1)
Requirement already satisfied: tqdm>=4.64.0 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from ultralytics==8.0.94) (4.65.0)
Requirement already satisfied: pandas>=1.1.4 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from ultralytics==8.0.94) (1.3.5)
Requirement already satisfied: seaborn>=0.11.0 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from ultralytics==8.0.94) (0.12.2)
Requirement already satisfied: psutil in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from ultralytics==8.0.94) (5.4.7)
Requirement already satisfied: thop>=0.1.1 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from ultralytics==8.0.94) (0.1.1.post2209072238)
Requirement already satisfied: sentry-sdk in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from ultralytics==8.0.94) (1.22.1)
Requirement already satisfied: cycler>=0.10 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from matplotlib>=3.2.2->ultralytics==8.0.94) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from matplotlib>=3.2.2->ultralytics==8.0.94) (4.38.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from matplotlib>=3.2.2->ultralytics==8.0.94) (1.4.4)
Requirement already satisfied: numpy>=1.17 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from matplotlib>=3.2.2->ultralytics==8.0.94) (1.21.6)
Requirement already satisfied: packaging>=20.0 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from matplotlib>=3.2.2->ultralytics==8.0.94) (21.3)
Requirement already satisfied: pyparsing>=2.2.1 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from matplotlib>=3.2.2->ultralytics==8.0.94) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from matplotlib>=3.2.2->ultralytics==8.0.94) (2.7.3)
Requirement already satisfied: pytz>=2017.3 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from pandas>=1.1.4->ultralytics==8.0.94) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from requests>=2.23.0->ultralytics==8.0.94) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from requests>=2.23.0->ultralytics==8.0.94) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from requests>=2.23.0->ultralytics==8.0.94) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from requests>=2.23.0->ultralytics==8.0.94) (2018.10.15)
Requirement already satisfied: typing_extensions in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from seaborn>=0.11.0->ultralytics==8.0.94) (4.5.0)
Requirement already satisfied: six>=1.5 in /mnt/dataprt/archiconda3/envs/Py37/lib/python3.7/site-packages (from python-dateutil>=2.7->matplotlib>=3.2.2->ultralytics==8.0.94) (1.11.0)

**Comment by glenn-jocher** [comment]
@Goldenshluger hello! It seems like all the requirements for YOLOv8 have already been satisfied in your environment, so that's great! As for your specific issue, it's actually related to PyTorch. The error message is indicating that it can't find the module `torch.ao`, which was only added in PyTorch 1.9.0, so it makes sense that you're getting the error with PyTorch 1.8.0.

Therefore, to run YOLOv8, you would need PyTorch 1.9.0 or higher. If building PyTorch on your platform takes such a long time, then an alternative might be to use pre-built PyTorch binaries, which are available for certain platforms and configurations. You can find more information on the PyTorch website: https://pytorch.org/get-started/locally/

I hope this helps, let us know if you have any other questions!

**Comment by KLiFF2606** [comment]
Hi @glenn-jocher  the pom file says YoloV8 support pytorch 1.8.0 https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml 

In my case, I only have pyTorch 1.8.0 because I need to run it with cuda 11.4. Pytorch 1.9 means a diffenrent hardware fro me.

Is there anything I can do to make YoloV8 work with pyTorch 1.8.0?

**Comment by glenn-jocher** [comment]
Thank you for your question! While the `pyproject.toml` specifies PyTorch>=1.7.0, YOLOv8 relies on features introduced in PyTorch 1.9.0, such as `torch.ao`. Unfortunately, this means PyTorch 1.8.0 is not supported. To use YOLOv8, you would need to upgrade to PyTorch 1.9.0 or higher, which might require different hardware or CUDA versions. If upgrading is not feasible, alternative options like using an older YOLO version (e.g., YOLOv5) compatible with your setup might be worth considering. Let us know if you have further questions.
