### ISSUE TITLE
Resume training failed

### ISSUE THREAD

**Issue by PhilCuriosity** [ultralytics/ultralytics#2460]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I tried the method mentioned in https://github.com/ultralytics/ultralytics/issues/2329  , but it didn't work.

### Environment

CUDA 10.2
Python 3.10
torch 1.12
ultralytics  8.0.94

### Minimal Reproducible Example

I tried the following
`model = YOLO(“yolov8l-seg.yaml”).load(r”runs/segment/train/weights/last.pt”) 
model.train(data=“ultralytics/datasets/coco128-seg-2M.yaml”, epochs=600, patience=100,
            batch=12, workers=3, imgsz=640, device=“2,7”, cos_lr=True, max_det=64, mosaic=0.1,
            fliplr=0.0, resume=True)`
or
`model = YOLO(“yolov8l-seg.yaml”).load(r”runs/segment/train/weights/last.pt”) 
model.train(data=“ultralytics/datasets/coco128-seg-2M.yaml”, epochs=600, patience=100,
            batch=12, workers=3, imgsz=640, device=“2,7”, cos_lr=True, max_det=64, mosaic=0.1,
            fliplr=0.0, resume=r“runs/segment/train/weights/last.pt”)`
or
`model = YOLO(“yolov8l-seg.yaml”)
model.train(data=“ultralytics/datasets/coco128-seg-2M.yaml”, epochs=600, patience=100,
            batch=12, workers=3, imgsz=640, device=“2,7”, cos_lr=True, max_det=64, mosaic=0.1,
            fliplr=0.0, resume=r“runs/segment/train/weights/last.pt”)`
 and none of them worked. The value of resume is always None.

> yolo/engine/trainer: task=segment, mode=train, model=yolov8l-seg.yaml, data=ultralytics/datasets/coco128-seg-2M.yaml, epochs=600, patience=100, batch=12, imgsz=640, resume=None, ...... ,save_dir=runs/segment/train2
 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ChenJian7578** [comment]
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by glenn-jocher** [comment]
@ChenJian7578 hi there! It looks like you're encountering a `RuntimeError` with YOLOv8. This error typically occurs when a new process is being started before the current process has finished its bootstrapping phase.

To resolve this issue, make sure you are following the proper idiom in the main module of your code if you are using multiprocessing. The idiom involves checking if `__name__ == '__main__'` and calling `freeze_support()` to properly start the child processes.

If you're not using multiprocessing or your code is not going to be frozen into an executable, you can safely omit the `freeze_support()` line.

By following this idiom, you should be able to resolve the `RuntimeError` and continue with your YOLOv8 implementation.

If you have any further questions or encounter any other issues, please let me know and I'll be happy to help!

**Comment by DaniSTexe** [comment]
This worked for me:

from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO('last.pt') # I copied last.pt to the principal folder
    results = model.train(resume=True)

**Comment by glenn-jocher** [comment]
@DaniSTexe that's great to hear!

Your solution involves creating the YOLO model initially with the 'last.pt' weights, which you've copied to the main directory. Then, you're calling the `train` method with `resume=True` to continue training from where it last left off.

Using the `if __name__ == '__main__':` idiom is a good practice in Python and it's especially important when working with multiprocessing. This bit of code makes sure that the multiprocessing code is not accidentally run multiple times, for example when your module is being imported.

I hope this helps others who might be facing the same issue!
