### ISSUE TITLE
> @zhu709654396我们的目标之前没有内部支持rknn格式，这个问题可能与rknn那个块有关，我不太明白

### ISSUE THREAD

**Issue by wandaoyi** [ultralytics/ultralytics#2462]
> @zhu709654396我们的目标之前没有内部支持rknn格式，这个问题可能与rknn那个块有关，我不太明白

好的感谢回答

_Originally posted by @zhu709654396 in https://github.com/ultralytics/ultralytics/issues/1555#issuecomment-1478858660_

**Comment by wandaoyi** [comment]
可否分享一下v8.onnx 转 rknn 的方案给我呢？谢谢。wandaoyi_dxq@qq.com

**Comment by wandaoyi** [comment]
谢谢&nbsp;


求道
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Glenn ***@***.***&gt;; 
发送时间: 2023年5月8日(星期一) 晚上11:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ultralytics/ultralytics] &gt; @zhu709654396我们的目标之前没有内部支持rknn格式，这个问题可能与rknn那个块有关，我不太明白 (Issue #2462)





 
@wandaoyi 你好，感谢您对YOLOv8的关注。我们很抱歉，目前我们的团队还没有内部支持rknn格式的方案。我们建议您可以通过了解rknn的官方文档和工具来尝试将v8.onnx转换为rknn格式。如果您有更多的问题或疑虑，我们将竭诚为您服务。

**Comment by glenn-jocher** [comment]
Hi @wandaoyi, thank you for your interest in YOLOv8 and for reaching out to us. We apologize that our team currently doesn't have an internal solution to support rknn format. However, we suggest that you refer to rknn's official documentation and tools to attempt to convert v8.onnx to rknn format. If you have any more questions or concerns, please don't hesitate to let us know. We're here to help!
