### ISSUE TITLE
An error occurred while executing the ONNX file.

### ISSUE THREAD

**Issue by SliverAward** [ultralytics/ultralytics#2464]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question
```
from ultralytics import YOLO

# Load the model.
model = YOLO('C:\\yolov8\\yolov8n.pt')

# Training.
if __name__ == '__main__':
    results = model.train(
        data='C:\\yolov8\\dataset\\data.yaml',
        imgsz=320,
        patience=50,
        epochs=100,
        batch=10,
        name='yolov8n_custom')

    model.export(format='onnx', opset=12, imgsz=[320, 320], int8=True)
```

**This is my train.py code.**

```
from ultralytics import YOLO
from ultralytics.yolo.v8.detect.predict import DetectionPredictor
import cv2
import time
import torch


# model.load
model = YOLO("C:\\yolov8\\runs\\detect\\yolov8n_custom5\\weights\\best.onnx")
result = model.predict(source="0", show=True)
print(result)

```
**And this is my detect.py code.**

![image](https://user-images.githubusercontent.com/115061522/236733819-f517bffc-25d7-479e-aa2b-16629ada234b.png)

**After training, I tried to convert it to ONNX and run it, but it seems like there is an image size error.

I set the size to 320 during training. Do you know why this is happening?

The current environment is Windows, and if it runs successfully, I plan to transfer it to Raspberry Pi 4 for object detection.**

**Comment by NguyenVuHoaBinh** [comment]
By default, the image size in detect is set 640. You should try to set imgsz=320 in your predict line to solve this problem. Hope this help.

**Comment by glenn-jocher** [comment]
@NguyenVuHoaBinh hello! Thank you for reaching out. From what I understand, the image size error is because the image size in detect is set to 640 by default, while you trained with 320. You can solve this by setting `imgsz=320` in your predict line, which should match with the size you used during training. I hope this explanation helps! Let us know if you have any further questions.
