### ISSUE TITLE
Cannot find primary config 

### ISSUE THREAD

**Issue by jiyuwangbupt** [ultralytics/ultralytics#247]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I want to replace the default yaml with my own hyp_yaml, but the following error occurs.
![Uploading image.png…]()

### Environment

Ultralytics YOLOv8.0.3 🚀 Python-3.8.5 torch-1.11.0+cu102 CUDA:0 (Tesla P40, 8192MiB)

### Minimal Reproducible Example

pass

### Additional

pass

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@jiyuwangbupt if you run `yolo task=init` you should get the deafult.yaml in your working directory.. You can then edit it however you like and use it:
```
yolo --config-name=defaults.yaml
```

**Comment by jiyuwangbupt** [comment]
> @jiyuwangbupt if you run `yolo task=init` you should get the deafult.yaml in your working directory.. You can then edit it however you like and use it:
> 
> ```
> yolo --config-name=defaults.yaml
> ```
yolo task=detect mode=train model=yolov8n.pt data=/nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/helmet640.yaml device=0 --config-name /nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/helmethyp.yaml
Error Message:
Cannot find primary config 'nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/helmethyp.yaml'. Check that it's in your config search path.

**Comment by jiyuwangbupt** [comment]
> yolo task=detect mode=train model=yolov8n.pt data=/nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/helmet640.yaml device=0 --config-name /nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/helmethyp.yaml



> @jiyuwangbupt if you run `yolo task=init` you should get the deafult.yaml in your working directory.. You can then edit it however you like and use it:
> 
> ```
> yolo --config-name=defaults.yaml
> ```

yolo task=init

        YOLO: configuration saved to /nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/default.yaml.
        To run experiments using custom configuration:
        yolo task='task' mode='mode' --config-name config_file.yaml

yolo task=detect mode=train model=yolov8n.pt data=/nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/helmet640.yaml device=0 --config-name /nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/default.yaml

      Cannot find primary config 'nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/default.yaml'. Check that it's in your config search path.
      
      Config search path:
              provider=hydra, path=pkg://hydra.conf
              provider=main, path=pkg://ultralytics.yolo.configs
              provider=schema, path=structured://
      
      Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by AyushExel** [comment]
@jiyuwangbupt the .yaml file needs to be in your current working dir.. Otherwise, you'll need to pass --config-path.. We'll work on making the process easier but meanwhile can you just move the file in your working directory..`yolo task=init` will do that for you

**Comment by jiyuwangbupt** [comment]
> --config-path




> @jiyuwangbupt the .yaml file needs to be in your current working dir.. Otherwise, you'll need to pass --config-path.. We'll work on making the process easier but meanwhile can you just move the file in your working directory..`yolo task=init` will do that for you

Due to data security and other reasons, the online server code is inconsistent with the environment path in Anaconda (the ultralytics environment is installed in the Anaconda virtual environment) and the working directory is in another path.

You mean the following command?
yolo task=init --config-name helmethyp.yaml --config-path /nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/

**Comment by AyushExel** [comment]
Yes I think that might work..Let me know if it doesn't ..today I'll push I fix to make this process simpler

**Comment by jiyuwangbupt** [comment]
> Yes I think that might work..Let me know if it doesn't ..today I'll push I fix to make this process simpler

EMMM, I'm sorry to say, failed. . . Tried the following commands. "helmethyp.yaml" is in this parent path "/nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/".  (The command is also executed under this parent path)
yolo task=init --config-name helmethyp.yaml --config-path /nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/                                                                                             
        YOLO: configuration saved to /nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/default.yaml.
        To run experiments using custom configuration:
        yolo task='task' mode='mode' --config-name config_file.yaml

yolo task=detect mode=train model=yolov8n.pt data=/nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/helmet640.yaml device=0 --config-name /nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/helmethyp.yaml
Cannot find primary config 'nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/helmethyp.yaml'. Check that it's in your config search path.

Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=pkg://ultralytics.yolo.configs
        provider=schema, path=structured://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by AyushExel** [comment]
```
yolo task=detect mode=train model=yolov8n.pt data=/nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/helmet640.yaml device=0 --config-name=helmethyp.yaml --config-path=/nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8
```
try this..If this also doesn't work..Just wait for a few hours and we'll push a fix

**Comment by jiyuwangbupt** [comment]
> Yes I think that might work..Let me know if it doesn't ..today I'll push I fix to make this process simpler

Tha

> ```
> yolo task=detect mode=train model=yolov8n.pt data=/nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/helmet640.yaml device=0 --config-name=helmethyp.yaml --config-path=/nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8
> ```
> 
> try this..If this also doesn't work..Just wait for a few hours and we'll push a fix

Wow, its work. Thanks a lot for your help.

**Comment by AyushExel** [comment]
Closing this issue. Feel free to reopen is something is broken

**Comment by jiyuwangbupt** [comment]
> Closing this issue. Feel free to reopen is something is broken

Hello, when I reconfigured a new environment, the command “ yolo task=init --config-name helmethyp.yaml --config-path /nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/                   
yolo task=detect mode=train model=yolov8n.yaml data=/nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/helmet640.yaml device=0 batch=20 workers=0 --config-name=helmethyp.yaml --config-path=/nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8”reported an error. 





Similar to datafile——coco128.yaml, is it possible to pass the hyperparameter yaml file directly to the command. for example, yolo task=detect mode=train model=yolov8n.yaml data=/nfs/volume-622-1/ lanzhixiong/project/smoking/code/yolov8/helmet640.yaml hyp=yolo task=detect mode=train model=yolov8n.yaml hyp=/nfs/volume-622-1/lanzhixiong/project/smoking/code/yolov8/helmet_hyp. yaml

**Comment by AyushExel** [comment]
@jiyuwangbupt you can pass custom config like this:
```
yolo cfg=file.yaml
```
Please keep checking docs for the latest usage. We're updating them rapidly

**Comment by rmbayer** [comment]
What would the configuration look like if you weren't using the CLI? 

`model = YOLO("yolov8n.pt")
model.train(data="testing_yaml.yaml")
results = model.val()  
success = model.export(format="onnx")  `

Compared to my current code, can I pass a cfg=my_custom_cfg.yaml somewhere?

**Comment by glenn-jocher** [comment]
@rmbayer yes, you can pass the custom configuration by simply passing the path to the configuration file as a variable. Before the train step, the configuration file path can be specified in the ```configs.yaml``` file. You can simply create a file which contains your custom configuration parameters and pass it to the ```YOLO()``` object by specifying the path to the YAML file such as: ```model = YOLO(config_path="my_custom_cfg.yaml")``` you can also specify the configuration paths using command line arguments too by passing ```--config-path```

**Comment by Nikitaa15** [comment]
I have read the above comments on this issue, but couldn't understood with my code.
I have the same error in my code. i.e.,

Primary config directory not found.
Check that the config directory 'C:\Users\Atom-2\PycharmProjects\pythonProject6 - YOLO V8\YOLOv8-DeepSORT-Object-Tracking\ultralytics\yolo\v8\detect\configs' exists and readable

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

![hydra error](https://github.com/ultralytics/ultralytics/assets/110290218/a04c909f-1ac5-4ba5-9c69-975aa5398702)

Please help me through this.
![hydra error](https://github.com/ultralytics/ultralytics/assets/110290218/1ab9096e-45d7-4d32-bc85-e37f8234c951)

**Comment by glenn-jocher** [comment]
@Nikitaa15 it seems there may be an issue with the path to the configuration file. Ensure the path to your config file is correct and that the directory is accessible. Double-check that your custom configuration file is placed in the right location and is named properly. Also, verify that your working directory is set appropriately in your IDE or when executing the script. If you continue to have issues, please refer to our documentation on configuring the model with custom paths and ensure that you're following the required format and file structure. If the issue persists, please provide more information on your directory structure and how you are setting up the model in your code.
