### ISSUE TITLE
Pose model taking more inference time

### ISSUE THREAD

**Issue by karunakr** [ultralytics/ultralytics#2476]
I am using yolov8x-pose-p6.pt for inference using 1280 sized. Though the results are good, it's taking around 300 ms when running inference in AWS g4dn instance. 

Could someone please guide me on the options available to improve performance?

**Comment by karunakr** [comment]
Thanks for your prompt response. I could able to export yolov8x-pose-p6 model to tensorrt, and when running inference, i am getting below error.  Could you please help
results = model.predict(source=sharpened_frame,imgsz=1280, save=False,boxes=True,conf=0.01,device=0,iou=0.85)[0]
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/Source/yolov8/ultralytics/ultralytics/yolo/engine/model.py", line 249, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/home/ubuntu/Source/yolov8/ultralytics/ultralytics/yolo/engine/predictor.py", line 285, in setup_model
    self.model = AutoBackend(model,
  File "/home/ubuntu/Source/yolov8/ultralytics/ultralytics/nn/autobackend.py", line 173, in __init__
    dtype = trt.nptype(model.get_binding_dtype(i))
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/tensorrt/__init__.py", line 166, in nptype
    bool: np.bool,
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecation

**Comment by glenn-jocher** [comment]
Hi @karunakr, it looks like you are trying to use the TensorRT backend in YOLOv8. The error you are seeing is related to how NumPy handles boolean data types, and is not specific to YOLOv8 or TensorRT.

To avoid this error, you can modify your code to use `bool` instead of `np.bool`. For example, you can change `np.bool` to `bool` in the `numpy.__init__` file where the error is occurring.

Regarding your requirement to obtain all keypoints along with boxes, you can use the `boxes` argument with a value of `True` when calling `predict`. This will return bounding boxes as well as other information such as confidence scores and class labels. For keypoints, you can use the `pose` function to get the pose keypoint locations.

Let me know if this helps, or if you have any other questions.

**Comment by karunakr** [comment]
Thanks, @glenn-jocher 
We are using AWS g4dn( 1 gpu vm) for running inference. I tried running tensorrt model in colab, but performance is getting worse. Could you please suggest what format would more ideal for aws g4dn instance

**Comment by glenn-jocher** [comment]
You're welcome, @karunakr!

To optimize performance on AWS g4dn instances, we recommend using the TensorRT backend for YOLOv8. You can export your YOLOv8 model to TensorRT using the `export()` function, and then use the `from_path()` function to load the TensorRT optimized engine. This should result in faster inference times compared to using the PyTorch backend.

Alternatively, you might consider using the ONNX format for your YOLOv8 model. This format is platform-independent and can be executed on various devices. In particular, AWS provides support for ONNX models using Amazon SageMaker Neo.

I hope this helps! Let me know if you have any further questions.

**Comment by karunakr** [comment]
Thanks @glenn-jocher again.

I could able to export() using colab, can i use the generated engine model in g4dn? Also, could you please share an example on how to use from_path(). I tried checking documentation, not able to locate any snippet

**Comment by glenn-jocher** [comment]
You're welcome, @karunakr! 

Yes, you can use the generated TensorRT engine model (`.plan` file) on your g4dn instance for faster inference times. To load the optimized engine into YOLOv8, you can use the `from_path()` function and provide the path to your `.plan` file as an argument. Here is an example:

```
from ultralytics.yolo import Model

# Load TensorRT engine from path
trt_model = Model.from_path(engine_path='path/to/trt/engine')

# Run inference
results = trt_model(source=image_path, imgsz=img_size, device=device)
```

In this example, `trt_model` is an instance of the `Model` class that has been optimized for execution on the g4dn instance using the TensorRT backend. You can then use this model to run inference on your input data.

I hope this helps! Let me know if you have any further questions.

**Comment by karunakr** [comment]
Thanks again @glenn-jocher 
I am getting an error as Model not found under yolo
             ImportError: cannot import name 'model' from 'ultralytics.yolo' (
I also tried with below import, but is giving below error
            from ultralytics.yolo.engine import model
            trt_model = model.from_path(engine_path='../yolov8x-pose-p6.engine'

However, i can able to generate trt model in the same machine using the below statement, and is 513 MB.
model.export(format='TensorRT',device=0)

Can you please suggest how to run inference using trt model.

**Comment by glenn-jocher** [comment]
Hi @karunakr,

The error you are seeing can occur when you are trying to import the `model` module from `ultralytics.yolo` when it is actually located under `ultralytics.yolo.engine`. You should update your import statement to:

```
from ultralytics.yolo.engine import model
```

Regarding how to run inference using your generated TensorRT model, you can use the `from_path()` function to load the TensorRT engine from the `.engine` file that you have generated using the `export()` function. This will create a new instance of the `Model` class that you can use to run inference on your input data. Here is an example:

```
from ultralytics.yolo.engine import model

# Load TensorRT engine from path
trt_model = model.from_path(engine_path='../yolov8x-pose-p6.engine')

# Run inference
results = trt_model(source=image_path, imgsz=img_size, device=device)
```

In this example, `trt_model` is an instance of the `Model` class that has been optimized for execution on the g4dn instance using the TensorRT backend. You can then use this model to run inference on your input data.

I hope this helps! Let me know if you have any further questions.

**Comment by karunakr** [comment]
Hi @glenn-jocher,
Though export is working well, i don't see an instance of the model getting generated post-export. I used below code snippet for export 
from ultralytics import YOLO
model = YOLO("yolov8x-pose-p6.pt") 
success = model.export(format="TensorRT",device=0) 

I tried installing the module using pip as well by using a clone of ultralytics module. In both cases, the model files not getting generated.  As from_path is not available, it's giving an error. If the model file is the same with no dependency on the system, could you please share the model file which I will copy under the engine folder and test the same?

**Comment by karunakr** [comment]
Hi @glenn-jocher,

The problem i am facing is, there's no method available from_path in the model class. Could you please share model class so that i can replace it under the engine folder?

**Comment by karunakr** [comment]
Hi @glenn-jocher 
It worked by changing model name. Thanks a lot for all your help.

**Comment by glenn-jocher** [comment]
@karunakr you're welcome! I'm glad to hear that changing the model name worked for you. If you have any further questions or issues with YOLOv8, feel free to reach out and we'll do our best to help you out. 

We appreciate your feedback and support for YOLOv8. If you find it useful, we encourage you to contribute to the project or spread the word to others who might benefit from it. Thank you for being a part of the YOLO community!
