### ISSUE TITLE
Couldn't find Yolov8 mAP 0,5 metric.

### ISSUE THREAD

**Issue by Raduas** [ultralytics/ultralytics#2477]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, looking for the YOLOv8 mAP 0.5 value, like on here [https://github.com/ultralytics/yolov5#pretrained-checkpoints](url) I could't find it. Can anyone tell me the mAP 0,5 value for pretrained v8m and v8n?

**Comment by Raduas** [comment]
Thank you

**Comment by Raduas** [comment]
I am sorry for bad formulation of my question, i wanted to ask for COCO dataset mAP 0,5, to compare it with my trained YOLOv8.

**Comment by Laughing-q** [comment]
@Raduas I don't remember the exact number but about 68 for M and 53 for N model.

**Comment by Raduas** [comment]
ok, thank you
