### ISSUE TITLE
Axis labels flipped on confusion matrix

### ISSUE THREAD

**Issue by JeremyMahieu** [ultralytics/ultralytics#2491]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I believe the X and Y axis labels are flipped on the confusion matrix. In the case below I have a rather bad model. The validation data has images for every class. However the model does not predict every class. I would expect the "True" columns to be filled at least on one square but there are entire classes that are empty.

Imagine the following question: How many images that are class 16 are actually labeled as class 4? In this case the matrix says there are 0 images labeled as class 16, which is incorrect.

When you add all the values of a row you can get more than 100%, meaning there are more predictions than there are labeled images. This agan means the rows are "true" and the columns are predictions. 

![image](https://user-images.githubusercontent.com/23409814/237020652-b5bbedd9-df5a-4162-9561-f307b6c4383f.png)
![image](https://user-images.githubusercontent.com/23409814/237022207-b1533914-aacf-49d0-9dca-73fcb7d8bb19.png)

If you agree this is a bug I can look into making a PR.

### Environment

Ultralytics YOLOv8.0.92 🚀 Python-3.8.10 torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24243MiB)
Python v3.8.10

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by JeremyMahieu** [comment]
Apparently this is normal.

> Regarding your question about the confusion matrix, yes, the "True" axis represents the predicted values of the model and the "Predicted" axis represents the labeled validation data. This may seem counterintuitive at first, but it is how the matrix is typically defined in machine learning.

**Comment by glenn-jocher** [comment]
@JeremyMahieu thank you for bringing this up. As stated, the axis labels on the confusion matrix for YOLOv8 are indeed flipped, as this is how the matrix is typically defined in machine learning. However, we appreciate your feedback and understand that it may seem counterintuitive at first. We'll keep this in mind for future updates and improvements to the repo. Thank you for your willingness to help by submitting a PR!
