### ISSUE TITLE
TFLite model not loading in Flutter app

### ISSUE THREAD

**Issue by kamilkk852** [ultralytics/ultralytics#2494]

**Comment by pderrenger** [comment]
@kamilkk852 hi there! It seems like you're encountering an issue with loading the TFLite model in your Flutter app. While the YOLOv8 repo focuses on the YOLOv8 model specifically, I'd be happy to help you troubleshoot this. 

Could you provide more details about the specific error or behavior you're experiencing when trying to load the TFLite model in your Flutter app? This will help me better understand the issue and provide you with the most accurate assistance. Thank you!
