### ISSUE TITLE
Why doesn't the setting of "batch" work when using tensorRT's engine for validation

### ISSUE THREAD

**Issue by 1224wxwx** [ultralytics/ultralytics#2500]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

`yolo detect val model="runs/detect/yolov8l_sku_0505/weights/last.engine" data="datasets/sku_d.yaml" imgsz="800" batch="32" iou="0.45" device="0,1" half`

The above is the command I used. However, during actual execution, the batch size was still 1.
Could you please tell me how can I make the setting of "batch" take effect?

### Additional

`yolo export model="runs/detect/yolov8l_sku_0505/weights/last.pt" format=engine imgsz="800" half device="0"`
The above is the command I used to export tensorRT model.

**Comment by glenn-jocher** [comment]
@1224wxwx thank you for reaching out with your question about the `batch` argument in the `yolo detect` command. The `batch` argument is used to set the batch size to be used during inference. 

If you set `batch=32` for example, the `yolo detect` command will attempt to perform object detection on 32 images at a time. However, it is possible that your system memory settings could override this argument and cause the batch size to default to 1. 

One potential solution would be to adjust the `batch` size setting to a lower number that your system can accommodate. Alternatively, you could try running the command on a machine with more memory. 

Regarding your additional question about exporting a TensorRT model, the `yolo export` command you provided should work for exporting a TensorRT model. If you encounter any issues, please let us know and we will do our best to help you troubleshoot the problem. 

I hope this helps! Let us know if you have any further questions.

**Comment by 1224wxwx** [comment]
@glenn-jocher Thank you for your response. It turns out that I forgot to include the 'batch' parameter when exporting the TensorRT engine. I would like to suggest that you consider adding the 'batch' parameter to the documentation on exporting models.

**Comment by glenn-jocher** [comment]
@1224wxwx you're welcome! Thank you for bringing this to our attention. We appreciate your suggestion and will take it into consideration as we continue to update and improve the YOLOv8 documentation. If you run into any other issues or have further suggestions, please don't hesitate to reach out. We're here to help!
