### ISSUE TITLE
Conf score vs visibility in pose output

### ISSUE THREAD

**Issue by karunakr** [ultralytics/ultralytics#2501]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I can conf score is of lessor than 0.3 %, but all key points of the person's visibility is more than 90% . Whereas, if I keep the conf score to 0.001, I can see a lot of false positives. Please find below data

Box data
[689.0, 264.0, 726.0, 365.0, 0.0037506408989429474, 0.0]

keypoints data
[[704.922607421875, 276.3669128417969, 0.7788121700286865], [706.4358520507812, 274.2142028808594, 0.6991372108459473], [703.0493774414062, 274.5367126464844, 0.6751337647438049], [709.1527709960938, 274.80316162109375, 0.44369012117385864], [700.712890625, 275.69573974609375, 0.38544175028800964], [713.4746704101562, 285.19451904296875, 0.9654200077056885], [698.437744140625, 286.2544860839844, 0.9615482091903687], [713.6337280273438, 298.810546875, 0.80079185962677], [697.2332153320312, 298.92657470703125, 0.799811601638794], [707.3626098632812, 304.2832946777344, 0.7244277596473694], [697.4207153320312, 301.8868408203125, 0.7334906458854675], [711.9510498046875, 311.60052490234375, 0.9811325669288635], [701.9801025390625, 312.03924560546875, 0.9805691242218018], [713.3037109375, 332.1739196777344, 0.9703779816627502], [702.391357421875, 332.61517333984375, 0.9709629416465759], [713.25439453125, 351.246337890625, 0.947269856929779], [703.159423828125, 351.7218017578125, 0.9474020004272461]]

Please suggest.

**Comment by glenn-jocher** [comment]
@karunakr based on your description of the issue and the data you've provided, it sounds like reducing the confidence score threshold has resulted in more false positive detections. One possible explanation for this is that the confidence scores returned by the YOLOv8 model are not directly related to the accuracy of the keypoints estimation. Another possible explanation is that the keypoints estimation and the object detection may have different thresholds and parameters affecting them. I would suggest keeping the confidence score threshold at a level that gives you accurate detections whilst minimizing false positives. I hope this helps. Let me know if you have any more questions or comments.

**Comment by karunakr** [comment]
Thanks @glenn-jocher for your prompt response. My question is, how come the keypoint conf score is above 90% for all key points, whereas the overall box conf score is 0.003? 

Is it a good idea to ignore the conf score and consider the keypoint score alone to get rid of false positives?

**Comment by glenn-jocher** [comment]
@karunakr, the confidence score is determined based on the detection of an object in the image, as well as the precision of the bounding box and the confidence of the keypoint location estimation. However, the confidence score may not always reflect the accuracy of the keypoint estimation. Therefore, if you are detecting an object with keypoints and the keypoint confidence score is high but the box confidence score is low, it may be an accurate detection worth keeping. However, if you set the confidence threshold too low, there will be a higher risk of false positives. I would recommend using your best judgement to determine a threshold that gives you accurate detections while minimizing false positives.

**Comment by karunakr** [comment]
Thanks @glenn-jocher
