### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by zhy007a** [ultralytics/ultralytics#2502]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I ran yolov8 in miniconda environment. When I run the command line `yolo train data=coco128.yaml model=yolov8n.pt epochs=10 lr0=0.01` to test it, it reported errors:
`AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Traceback (most recent call last):
  File "/home/username/miniconda3/envs/hzpy39/bin/yolo", line 33, in <module>
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())
  File "/home/username/ultralytics/ultralytics/yolo/cfg/__init__.py", line 394, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/username/ultralytics/ultralytics/yolo/engine/model.py", line 370, in train
    self.trainer.train()
  File "/home/username/ultralytics/ultralytics/yolo/engine/trainer.py", line 191, in train
    self._do_train(world_size)
  File "/home/username/ultralytics/ultralytics/yolo/engine/trainer.py", line 268, in _do_train
    self._setup_train(world_size)
  File "/home/username/ultralytics/ultralytics/yolo/engine/trainer.py", line 213, in _setup_train
    self.amp = torch.tensor(check_amp(self.model), device=self.device)
  File "/home/username/ultralytics/ultralytics/yolo/engine/trainer.py", line 669, in check_amp
    assert amp_allclose(YOLO('yolov8n.pt'), im)
  File "/home/username/ultralytics/ultralytics/yolo/engine/trainer.py", line 657, in amp_allclose
    a = m(im, device=device, verbose=False)[0].boxes.data  # FP32 inference
  File "/home/username/ultralytics/ultralytics/yolo/engine/model.py", line 111, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/username/miniconda3/envs/hzpy39/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/username/ultralytics/ultralytics/yolo/engine/model.py", line 252, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/username/ultralytics/ultralytics/yolo/engine/predictor.py", line 174, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
  File "/home/username/miniconda3/envs/hzpy39/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "/home/username/ultralytics/ultralytics/yolo/engine/predictor.py", line 212, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "/home/username/ultralytics/ultralytics/nn/autobackend.py", line 427, in warmup
    self.forward(im)  # warmup
  File "/home/username/ultralytics/ultralytics/nn/autobackend.py", line 313, in forward
    y = self.model(im, augment=augment, visualize=visualize) if augment or visualize else self.model(im)
  File "/home/username/miniconda3/envs/hzpy39/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/username/ultralytics/ultralytics/nn/tasks.py", line 205, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/username/ultralytics/ultralytics/nn/tasks.py", line 59, in _forward_once
    x = m(x)  # run
  File "/home/username/miniconda3/envs/hzpy39/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/username/ultralytics/ultralytics/nn/modules.py", line 40, in forward_fuse
    return self.act(self.conv(x))
  File "/home/username/miniconda3/envs/hzpy39/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/username/miniconda3/envs/hzpy39/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/username/miniconda3/envs/hzpy39/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
`
Anyone knows how to figure it out? Thanks very much.

### Additional

The conda list outputs are: 
# packages in environment at /home/username/miniconda3/envs/hzpy39:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   1.3.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
asttokens                 2.2.1                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2022.12.7            ha878542_0    conda-forge
cachetools                5.2.0                    pypi_0    pypi
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
contourpy                 1.0.6                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
deepen                    0.0.0                     dev_0    <develop>
docker-pycreds            0.4.0                    pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
flatbuffers               23.3.3                   pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.29                   pypi_0    pypi
google-auth               2.15.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.51.1                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imagehash                 4.3.1                    pypi_0    pypi
ipython                   8.7.0                    pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libblas                   3.9.0           15_linux64_openblas    conda-forge
libcblas                  3.9.0           15_linux64_openblas    conda-forge
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   11.2.0               h1234567_1  
liblapack                 3.9.0           15_linux64_openblas    conda-forge
libopenblas               0.3.20          pthreads_h78a6416_0    conda-forge
libprotobuf               3.20.3               he621ea3_0  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
markdown                  3.4.1                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.6.2                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
mypy                      0.991                    pypi_0    pypi
mypy-extensions           0.4.3                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3  
numpy                     1.23.5                   pypi_0    pypi
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cublas-cu12        12.1.0.26                pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.55                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cudnn-cu12         8.8.1.3                  pypi_0    pypi
nvidia-pyindex            1.0.9                    pypi_0    pypi
nvidia-tensorrt           99.0.0                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
onnx                      1.13.1                   pypi_0    pypi
onnx-simplifier           0.4.19                   pypi_0    pypi
onnxruntime-gpu           1.14.1                   pypi_0    pypi
onnxsim                   0.4.19                   pypi_0    pypi
opencv-python             4.6.0.66                 pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0  
packaging                 22.0                     pypi_0    pypi
pandas                    1.5.2                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.3.0                    pypi_0    pypi
pip                       22.2.2          py310h06a4308_0  
prompt-toolkit            3.0.36                   pypi_0    pypi
protobuf                  3.20.3                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pybktree                  1.1                      pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.10.8               h7a1cb2a_1  
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.6                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.28.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rich                      13.3.3                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-learn              1.2.0                    pypi_0    pypi
scipy                     1.9.3                    pypi_0    pypi
seaborn                   0.12.1                   pypi_0    pypi
sentry-sdk                1.13.0                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                65.5.0          py310h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sklearn                   0.0.post1                pypi_0    pypi
smmap                     5.0.0                    pypi_0    pypi
sqlite                    3.40.0               h5082296_0  
stack-data                0.6.2                    pypi_0    pypi
sympy                     1.11.1                   pypi_0    pypi
tensorboard               2.11.0                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorrt                  8.6.0                    pypi_0    pypi
thop                      0.1.1-2209072238          pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tomli                     2.0.1                    pypi_0    pypi
torch                     1.13.0                   pypi_0    pypi
torchvision               0.14.0                   pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.7.1                    pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2022g                h04d1e81_0  
ultralytics               8.0.96                    dev_0    <develop>
urllib3                   1.26.13                  pypi_0    pypi
wandb                     0.13.9                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.8                h5eee18b_0  
zlib                      1.2.13               h5eee18b_0

**Comment by SkalskiP** [comment]
I face the same issue.

**Comment by glenn-jocher** [comment]
@SkalskiP thank you for reporting this issue. Can you please provide more details on what the issue is and what steps you are taking when you encounter it? Also, please confirm that you have installed YOLOv8 correctly and are using a Python>=3.7 environment with PyTorch>=1.7. Once we have more information, we will be better able to assist you in resolving this issue.

**Comment by lonngxiang** [comment]
> @SkalskiP thank you for reporting this issue. Can you please provide more details on what the issue is and what steps you are taking when you encounter it? Also, please confirm that you have installed YOLOv8 correctly and are using a Python>=3.7 environment with PyTorch>=1.7. Once we have more information, we will be better able to assist you in resolving this issue.
same error

python 3.10
torch 2.1.0
cuda 11.7 

run：
```
yolo task=detect mode=val  model=/mnt/d****/runs/detect/train4/weights/last.pt conf=0.4 data=/mnt/***ety/data.yaml

```
![image](https://github.com/ultralytics/ultralytics/assets/40717349/457aedd8-141d-401e-b0c7-5cb9637d6d91)
