### ISSUE TITLE
How to pass Opencv/Pillow Image to model.predict()

### ISSUE THREAD

**Issue by dhunjoshi** [ultralytics/ultralytics#251]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to pass Opencv/Pillow Image to model.predict()

### Additional

How to pass Opencv/Pillow Image to model.predict()

**Comment by AyushExel** [comment]
@dhunjoshi Currently you can only pass file(img, videos, stream links, 0 for webcam) but this is a good idea.. We'll add support for passing tensors/np/PIL images

**Comment by Priler** [comment]
There's exactly undocumented way of passing a screenshot via [mss](https://python-mss.readthedocs.io/) with `python detect.py --source "screen 0 100 100 512 256"` CLI command or respective SDK code (the `source` must start with `screenshot` keyword as well).

Then, in the [source code](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/data/dataloaders/stream_loaders.py#L143) you can actually see how the `np` image is being loaded.
Currently, I have no time to come up with a convenient way of passing an `np` image externally, without changing the source code of `ultralytics/yolo`.

But as a temporary fix, you could do it with a custom monkey patch or by changing the source code to allow loading of `np` image directly.
