### ISSUE TITLE
Cannot find the common.py file, I want to change activation layer.

### ISSUE THREAD

**Issue by FONG1234** [ultralytics/ultralytics#2514]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to find out the location of common.py file in order to change the activation layer as stated in #2417 . This is the repo file I downloaded using through cloning.
![YOLOv8 Repo](https://github.com/ultralytics/ultralytics/assets/132126352/ec3159e0-c8b9-49ae-806c-29cecf66acda)

But I still cannot find the location of common.py file. Thanks for help~
![Location of File](https://github.com/ultralytics/ultralytics/assets/132126352/7b4ae175-c699-479a-bc09-bc23934d004f)

**Comment by Laughing-q** [comment]
@FONG1234 yeah there's no `common.py` now in this repo, we have all the modules in `ultralytics/nn/modules.py`

**Comment by FONG1234** [comment]
@Laughing-q Oh I see, so I can modify the activation layer by changing the modules.py file?

**Comment by Laughing-q** [comment]
@FONG1234 yeah and also this way [https://github.com/ultralytics/ultralytics/issues/2417#issuecomment-1541249134](https://github.com/ultralytics/ultralytics/issues/2417#issuecomment-1541249134).

**Comment by FONG1234** [comment]
@Laughing-q Thank You So Much! Appreciated it

**Comment by glenn-jocher** [comment]
@FONG1234 You're welcome! If you need further assistance, don't hesitate to ask.
