### ISSUE TITLE
Train error. Scatter_add cuda kernel does not have a deterministic implementation.

### ISSUE THREAD

**Issue by VivizSun** [ultralytics/ultralytics#2515]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Thank for your hard work.
When I used myself data to train detect of task, I got an error that scatter_add cuda kernel does not have a deterministic implementation.
However, when using segmentation or classification tasks in same environment, it is successfully to train.

Error as shown below :
![01](https://github.com/ultralytics/ultralytics/assets/98437625/60d10ac3-d012-4d1c-b8a3-d5b18df1869e)

### Environment

- ultralytics  8.0.96
- windows  11
- python  3.10.4
- torch  1.12.1

### Minimal Reproducible Example

args = dict(model='yolov8n.pt', data='coco.yaml', device=0)
trainer = DetectionTrainer(overrides=args)
trainer.train()

Train log as shown below :
![02](https://github.com/ultralytics/ultralytics/assets/98437625/64d940b4-ab40-4462-a06a-536f3b25b8a1)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@VivizSun It would be very helpful if you can provide a reproducible command with a copy-paste snippet. Thanks!

**Comment by VivizSun** [comment]
> @VivizSun如果您可以提供帶有復制粘貼片段的可重現命令，那將非常有幫助。謝謝！
I used train.py, and revise parameters of model, data and device.

args = dict(model='yolov8n.pt', data='coco.yaml', device=0)
trainer = DetectionTrainer(overrides=args)
trainer.train()

**Comment by Laughing-q** [comment]
@VivizSun I'm not able to reproduce the issue, this probably is related to the version of your pytorch, cuda, cudnn.

**Comment by VivizSun** [comment]
@Laughing-q 
Thank for your help. I solve it by update pytorch version from torch 1.12.1 to 2.0.1+cu118.
By the way, My CUDA version is 11.2, but nvidia-smi show 12.1

CUDA version as shown below :
![05](https://github.com/ultralytics/ultralytics/assets/98437625/112b8794-3b33-4766-a6b6-979e2f7fb276)

**Comment by glenn-jocher** [comment]
@Denizzje @sdimantsd @wooAo @Laughing-q @VivizSun I've fixed this in https://github.com/ultralytics/ultralytics/pull/2527/commits/14f9b893c187a38c86805434c4d98782995affa3

Now torch<2.0 training will not be deterministic and a warning will be displayed. For deterministic training please upgrade to torch 2.0 :)

**Comment by Hommoner** [comment]
a workaround solution is disable deterministic algorithms

in ultralytics\yolo\utils\tal.py

line line 189:

```
        torch.use_deterministic_algorithms(False) # <--- add this
        for k in range(self.topk):
            # Expand topk_idxs for each value of k and add 1 at the specified positions
            count_tensor.scatter_add_(-1, topk_idxs[:, :, k:k + 1], ones)
        torch.use_deterministic_algorithms(True) # <--- (optional) add this 
```

**Comment by glenn-jocher** [comment]
@Hommoner thank you for sharing the workaround solution. Disabling deterministic algorithms can resolve this issue. When using YOLOv8, deterministic algorithms are turned on by default to ensure reproducibility. However, in some cases like this, deterministic algorithms may not be supported for certain operations, leading to an error. Adding the `torch.use_deterministic_algorithms(False)` statement before the relevant operations, and re-enabling it using `torch.use_deterministic_algorithms(True)` afterwards, as described in the workaround can provide a temporary fix. However, upgrading to PyTorch 2.0 will provide proper support for deterministic algorithms and is recommended for best results.
