### ISSUE TITLE
How to log metadata of predictions made using YOLOv8?

### ISSUE THREAD

**Issue by Camerabiologist** [ultralytics/ultralytics#2519]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I am in the process of predicting objects based on video, linked with GPS using a pretrained model. Right now the only information I get out of the predictions are the console output telling me on which video frame the predictions are being made, file location, resolution, detections and the prediction time. Crops of the detections are saved in the Predict folder, for every class in my model. I would like to have access to for instance a csv file, containing all the detections made by the model, its class and the file name and location of the detection crops. 

As of yet I have not been able to find this available within YOLOv8, so I am asking here: is it possible to retrieve more complete information from the whole model.predict function?

**Comment by Camerabiologist** [comment]
One of the things that could really help me is if I could add the number of the frame being detected on to the saved crop image, because I would like to use the detections for further analysis. Is there a simple way to do that? Thank you!

**Comment by glenn-jocher** [comment]
@Camerabiologist thank you for using YOLOv8. 

To add the number of the frame to the saved crop image, you can modify the `general.py` file and include the frame number in the filename of the detection crop image before it is saved in the Predict folder. This way, you will have the frame number associated with every saved image. 

You can use the `frame_i` variable in the `detector function` located in the `yolo.py` file to get the current frame number. You can then incorporate this variable as part of the filename when the image is saved. For example, you can concatenate the frame number with the detection class name to create a unique filename for every detection crop that includes the frame number and class name.

Please let us know if you need any further assistance.

**Comment by Camerabiologist** [comment]
Perhaps a bit of a beginner question, but where can I find the general.py file to edit it? I can't seem to locate it in the ultralytics folder.

**Comment by Camerabiologist** [comment]
I can find these files in YOLOv5, is that what you meant? I am actually using YOLOv8, but can't find the same files in that repository. Are there analogous files available for YOLOv8?
