### ISSUE TITLE
Models not present as download

### ISSUE THREAD

**Issue by thhart** [ultralytics/ultralytics#252]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Your links are not working, the downloads for the example models in your top page are leadings to a 404 page. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Thanks. I can reproduce it. We'll fix it now

**Comment by glenn-jocher** [comment]
@thhart links fixed in PR #256 that's queued to deploy soon (i.e. an hour or two). Let us know if you are still seeing issues after that, thank you!
