### ISSUE TITLE
VSCode Debugger crashes

### ISSUE THREAD

**Issue by tomole444** [ultralytics/ultralytics#2521]
Hi there,
I am running yolov8 in a conda environment. If I try to add breakpoints in my code and run the Python Debugger that comes with the Python extension in vscode it crashes with the following message: 

QObject::moveToThread: Current thread (0xaa7c6d0) is not the object's thread (0xd60f8b0).
Cannot move to target thread (0xaa7c6d0)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/fhws_robotik/anaconda3/envs/leyh-env-dev/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

here is the output of pip list: 
Package                  Version
------------------------ --------------------
addict                   2.4.0
asttokens                2.2.1
attrs                    23.1.0
backcall                 0.2.0
blinker                  1.6.2
certifi                  2023.5.7
charset-normalizer       3.1.0
click                    8.1.3
cmake                    3.26.3
comm                     0.1.3
ConfigArgParse           1.5.3
contourpy                1.0.7
cycler                   0.11.0
dash                     2.9.3
dash-core-components     2.0.0
dash-html-components     2.0.0
dash-table               5.0.0
debugpy                  1.6.7
decorator                5.1.1
executing                1.2.0
fastjsonschema           2.16.3
filelock                 3.12.0
Flask                    2.3.2
fonttools                4.39.3
idna                     3.4
importlib-metadata       6.6.0
importlib-resources      5.12.0
imutils                  0.5.4
ipykernel                6.23.0
ipython                  8.13.2
ipywidgets               8.0.6
itsdangerous             2.1.2
jedi                     0.18.2
Jinja2                   3.1.2
joblib                   1.2.0
jsonschema               4.17.3
jupyter_client           8.2.0
jupyter_core             5.3.0
jupyterlab-widgets       3.0.7
kiwisolver               1.4.4
labelImg                 1.8.6
lit                      16.0.3
lxml                     4.9.2
MarkupSafe               2.1.2
matplotlib               3.7.1
matplotlib-inline        0.1.6
mpmath                   1.3.0
nbformat                 5.7.0
nest-asyncio             1.5.6
networkx                 3.1
numpy                    1.24.3
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
open3d                   0.17.0
opencv-python            4.7.0.72
packaging                23.1
pandas                   2.0.1
parso                    0.8.3
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.5.0
pip                      23.1.2
platformdirs             3.5.0
plotly                   5.14.1
prompt-toolkit           3.0.38
psutil                   5.9.5
ptyprocess               0.7.0
pure-eval                0.2.2
Pygments                 2.15.1
pykinect-azure           0.0.3
pyparsing                3.0.9
PyQt5                    5.15.9
PyQt5-Qt5                5.15.2
PyQt5-sip                12.12.1
pyquaternion             0.9.9
pyrsistent               0.19.3
python-dateutil          2.8.2
pytz                     2023.3
PyYAML                   6.0
pyzmq                    25.0.2
requests                 2.30.0
scikit-learn             1.2.2
scipy                    1.10.1
seaborn                  0.12.2
sentry-sdk               1.22.2
setuptools               67.7.2
six                      1.16.0
stack-data               0.6.2
sympy                    1.11.1
tenacity                 8.2.2
thop                     0.1.1.post2209072238
threadpoolctl            3.1.0
torch                    2.0.1
torchvision              0.15.2
tornado                  6.3.1
tqdm                     4.65.0
traitlets                5.9.0
triton                   2.0.0
typing_extensions        4.5.0
tzdata                   2023.3
ultralytics              8.0.97
urllib3                  1.26.15
wcwidth                  0.2.6
Werkzeug                 2.3.4
wheel                    0.40.0
widgetsnbextension       4.0.7
zipp                     3.15.0

Can you help me with this issue?

**Comment by glenn-jocher** [comment]
@tomole444 hello there,

Thank you for reaching out to us about this issue. Based on the error message you provided, it seems that the Qt platform plugin could not be initialized, which is causing the debugger to crash.

One possible solution to this issue is to try setting the environment variable `QT_QPA_PLATFORM` to `offscreen`. You can do this by running `export QT_QPA_PLATFORM=offscreen` in your terminal or by setting it as an environment variable in your conda environment.

Another solution would be to install the missing Qt platform plugin in your conda environment. You can do this by running the following command in your terminal: `sudo apt-get install -y libxcb-xinerama0`.

I hope this information helps you resolve your issue. Please let us know if you have any further questions or if this solution does not work for you.

Best regards.

**Comment by tomole444** [comment]
Thank you for your help so far.

I tried both of your proposed solutions but none worked for me :(
With the evironment variable set I get this issue:

> qt.qpa.plugin: Could not find the Qt platform plugin "offscreen" in "/home/fhws_robotik/anaconda3/envs/yolov8/lib/python3.9/site-packages/cv2/qt/plugins"
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: xcb.

The package libxcb-xinerama0 also is already installed.

Also if I use opencv natively in a python script, the error still appears but debugging with the vscode debugger works flawlessly.
Therefore I think that the issue lies in the ultralytics library.

**Comment by glenn-jocher** [comment]
@tomole444 thank you for trying the proposed solutions. It's unfortunate that neither of them worked for you.

Regarding the error message you received when setting the environment variable `QT_QPA_PLATFORM`, it seems that the offscreen plugin is not available in the path specified. In this case, you may want to try setting the environment variable to `xcb` instead, which is listed in the available platform plugins.

It's also good to hear that debugging with the VSCode debugger works without any issues. This suggests that the issue may be related to the Ultralytics library itself. In this case, our recommendation would be to raise this issue directly with the Ultralytics team. They will have more expertise with their library and may be able to provide more targeted support for this issue.

Best regards.
