### ISSUE TITLE
Is it possible to use model.predict() in multi-threading?

### ISSUE THREAD

**Issue by rathaROG** [ultralytics/ultralytics#2522]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, is it possible to use `model.predict()` in multithreading application? I can't run 2 parallel threads, and the threads just hang at `predict()`. Hint: There is no such issue with `opencv` `dnn` `YOLO` v2/3/4.

### Additional

Edit; I'm on Windows 11, using Python 3.10 & cuda 11.8, cudnn 8.9 (RTX 4090).

**Comment by glenn-jocher** [comment]
Hi @rathaROG, thank you for your question. Yes, you can use `model.predict()` in a multithreading application with YOLOv8. The most common cause for hanging threads is usually related to GPU memory contention. Please make sure you are sharing GPU memory efficiently between threads and batches, and consider using PyTorch's DataLoader utility to allow concurrent data loading without GPU memory conflict. You may also find it helpful to adjust the batch size in conjunction with your available GPU memory. If you continue to experience issues, please provide more details such as error messages and a more complete code example, and we'll be happy to assist you.

**Comment by rathaROG** [comment]
> Hi @rathaROG, thank you for your question. Yes, you can use `model.predict()` in a multithreading application with YOLOv8. The most common cause for hanging threads is usually related to GPU memory contention. Please make sure you are sharing GPU memory efficiently between threads and batches, and consider using PyTorch's DataLoader utility to allow concurrent data loading without GPU memory conflict. You may also find it helpful to adjust the batch size in conjunction with your available GPU memory. If you continue to experience issues, please provide more details such as error messages and a more complete code example, and we'll be happy to assist you.

Hi @glenn-jocher, thanks for the hint! I haven't tried Dataloader yet as I have no idea where to implement it in my code, but my multithread application works well after I unset the line 102 `# cv2.setNumThreads(0)` in [`ultralytics/yolo/utils/__init__.py`](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/utils/__init__.py). As the comment written in line 102 `# prevent OpenCV from multithreading (incompatible with PyTorch DataLoader)`, I now see `RuntimeError: CUDA error: an illegal memory access was encountered` when my application runs more than 1 thread using `ultralytics` model. I'm lost at this point.

**Comment by MosesChuka** [comment]
> Hi @rathaROG, thank you for your question. Yes, you can use `model.predict()` in a multithreading application with YOLOv8. The most common cause for hanging threads is usually related to GPU memory contention. Please make sure you are sharing GPU memory efficiently between threads and batches, and consider using PyTorch's DataLoader utility to allow concurrent data loading without GPU memory conflict. You may also find it helpful to adjust the batch size in conjunction with your available GPU memory. If you continue to experience issues, please provide more details such as error messages and a more complete code example, and we'll be happy to assist you.

Please, any illustration on how to use pytorch's dataloader to avoid GPU memory conflict? 
In my case, the model hangs will trying to perform inferences. I just gets stock at the `fuse_conv_and_bn` function of `/ultralytics/utils//torch_utils.py`. Find in the attached screenshot. I am using yolov8 as a submodule to perform object segmentation in a larger framework that runs multiple threads using OpenCV.
![Screenshot from 2023-08-14 23-53-53](https://github.com/ultralytics/ultralytics/assets/77914891/4d9123a7-dcf1-4af2-80ef-706bf63ef52e)

**Comment by HouseWei** [comment]
> > Hi [@rathaROG](https://github.com/rathaROG), thank you for your question. Yes, you can use `model.predict()` in a multithreading application with YOLOv8. The most common cause for hanging threads is usually related to GPU memory contention. Please make sure you are sharing GPU memory efficiently between threads and batches, and consider using PyTorch's DataLoader utility to allow concurrent data loading without GPU memory conflict. You may also find it helpful to adjust the batch size in conjunction with your available GPU memory. If you continue to experience issues, please provide more details such as error messages and a more complete code example, and we'll be happy to assist you.
> 
> Hi [@glenn-jocher](https://github.com/glenn-jocher), thanks for the hint! I haven't tried Dataloader yet as I have no idea where to implement it in my code, but my multithread application works well after I unset the line 102 `# cv2.setNumThreads(0)` in [`ultralytics/yolo/utils/__init__.py`](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/utils/__init__.py). As the comment written in line 102 `# prevent OpenCV from multithreading (incompatible with PyTorch DataLoader)`, I now see `RuntimeError: CUDA error: an illegal memory access was encountered` when my application runs more than 1 thread using `ultralytics` model. I'm lost at this point.

Hi, may I have your code for multi thread? I want to inference it.Thanks

**Comment by glenn-jocher** [comment]
Hi, I recommend following the thread-safe approach as outlined in the [YOLO Thread-Safe Inference Guide](https://docs.ultralytics.com/guides/yolo-thread-safe-inference/). Ensure each thread instantiates its own YOLO model to avoid race conditions and potential conflicts. If you encounter further issues, feel free to share specific details, and I’ll assist you!

**Comment by narugo1992** [comment]
For anyone landing here in 2026 from a search like "yolo predict multi-threading hangs" — yes, threaded `predict()` is possible, but the [thread-safe inference guide](https://docs.ultralytics.com/guides/yolo-thread-safe-inference/) recipe of "instantiate the model inside each thread" has a measurable throughput cost most people only discover after deploying. Each per-thread `InferenceSession` allocates its own cuDNN handles + CUDA workspace, and they contend with each other past ~4 threads. On an H200 with yolov8n we measured ~97 imgs/s at 32 workers with the per-thread recipe, vs ~278 imgs/s for shared-session + Python `threading.Lock` (which serialises Run() but at least keeps cuDNN happy).

The actual obstacle to "shared session, no lock" is a race in ORT's CUDA-EP `Softmax` kernel — `Detect._inference()` always emits a `Softmax(axis=...)` node for DFL decode, and ORT dispatches it to a cuDNN softmax whose handle is shared across the session's threads. If you patch every `Softmax` node in the exported ONNX with the math-equivalent 5-op subgraph (`ReduceMax → Sub → Exp → ReduceSum → Div`), shared-session-no-lock becomes safe and reaches ~428 imgs/s on the same setup — that's 1.5× the locked variant and 4.4× the per-thread variant. One-file patcher: https://github.com/deepghs/yolo-onnx-thread-safe . Drop in the patched ONNX, no other code change needed.

**Comment by glenn-jocher** [comment]
Thanks for sharing this; a shared `InferenceSession` without synchronization is not a supported Ultralytics inference pattern, so for a shared model please guard calls with `ThreadingLocked` as shown in the [API reference](https://docs.ultralytics.com/reference/utils/__init__), and since this is a closed stale issue plus an ONNX Runtime/CUDA-specific finding, please open a new issue with a minimal repro on the latest `ultralytics`, exact `onnxruntime-gpu`/CUDA versions, export command, full text logs, and `yolo checks` output so we can investigate it properly.
