### ISSUE TITLE
Vit 

### ISSUE THREAD

**Issue by maheshs11** [ultralytics/ultralytics#2526]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The output of Sam vit does not include everything which the model gives like "area" and other parameters and onnx model of Sam is released would you support it too?

**Comment by AyushExel** [comment]
Yeah currently they don't but it's a good feature request. I'll work on it this week
