### ISSUE TITLE
Problems with multiple gpu training

### ISSUE THREAD

**Issue by Tsardoz** [ultralytics/ultralytics#253]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Traceback (most recent call last):
  File "/opt/conda/bin/yolo", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.8/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 222, in run_and_report
    raise ex
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 219, in run_and_report
    return func()
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 105, in run
    cfg = self.compose_config(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 594, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 142, in load_configuration
    return self._load_configuration_impl(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 249, in _load_configuration_impl
    self.validate_sweep_overrides_legal(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 79, in validate_sweep_overrides_legal
    raise ConfigCompositionException(msg)
hydra.errors.ConfigCompositionException: Ambiguous value for argument 'device=0,1,2,3'
1. To use it as a list, use key=[value1,value2]
2. To use it as string, quote the value: key=\'value1,value2\'
3. To sweep over it, add --multirun to your command line

### Minimal Reproducible Example

yolo task=detect mode=train model=yolov8m.pt data=fallset.yaml device=0,1,2,3 epochs=40 batch=240 lr0=0.001 v5loader=True

using [0,1,2,3] does not work either
4 GPUS RTX3090

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@Tsardoz can you try device='0,1,2,3'?

**Comment by AyushExel** [comment]
@Tsardoz @Laughing-q oh you need to add backslashes in cli
```
yolo task=detect mode=train model=yolov8n.pt data=coco128.yaml device=\'0,1,2,3\'
```
You can find the syntax in the docs https://docs.ultralytics.com/quickstart/

**Comment by Laughing-q** [comment]
@AyushExel ah I thought the advice below the error log is from hydra. is there any chance that they've supported this?

**Comment by Tsardoz** [comment]
Thanks this worked. device=\'0,1,2,3\'
I also needed v5loader=True as reported elsewhere

**Comment by Laughing-q** [comment]
@Tsardoz did you get any issues with `v5loader=False`?

**Comment by Laughing-q** [comment]
@AyushExel probably we can remove the backslashes in our docs.

**Comment by Tsardoz** [comment]
> @Tsardoz did you get any issues with `v5loader=False`?

I omitted v5loader at first and was getting an error related to dimensions. Sorry I do not recall exactly what it was. Once the training run finishes I will try again and report.

**Comment by Tsardoz** [comment]
This is the error I get if I leave off v5loader=True.
If I put v5loader=True in it runs but the validation loss is always NaN


root@C.5722467:/usr/src/app/ultralytics$ yolo task=detect mode=train model=yolov8m.pt data=fallset.yaml device=\'0,1,2,3\' epochs=20 batch=200 lr0=0.001
yolo/engine/trainer: task=detect, mode=train, model=yolov8m.pt, data=fallset.yaml, epochs=20, patience=50, batch=200, imgsz=640, save=True, cache=False, device=0,1,2,3, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=False, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, retina_masks=False, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.001, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, hydra={'output_subdir': None, 'run': {'dir': '.'}}, v5loader=False, save_dir=runs/detect/train16
Ultralytics YOLOv8.0.3 🚀 Python-3.8.12 torch-1.10.2+cu113 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)
                                                           CUDA:1 (NVIDIA GeForce RTX 3090, 24268MiB)
                                                           CUDA:2 (NVIDIA GeForce RTX 3090, 24268MiB)
                                                           CUDA:3 (NVIDIA GeForce RTX 3090, 24268MiB)
Overriding model.yaml nc=80 with nc=5

                   from  n    params  module                                       arguments                     
  0                  -1  1      1392  ultralytics.nn.modules.Conv                  [3, 48, 3, 2]                 
  1                  -1  1     41664  ultralytics.nn.modules.Conv                  [48, 96, 3, 2]                
  2                  -1  2    111360  ultralytics.nn.modules.C2f                   [96, 96, 2, True]             
  3                  -1  1    166272  ultralytics.nn.modules.Conv                  [96, 192, 3, 2]               
  4                  -1  4    813312  ultralytics.nn.modules.C2f                   [192, 192, 4, True]           
  5                  -1  1    664320  ultralytics.nn.modules.Conv                  [192, 384, 3, 2]              
  6                  -1  4   3248640  ultralytics.nn.modules.C2f                   [384, 384, 4, True]           
  7                  -1  1   1991808  ultralytics.nn.modules.Conv                  [384, 576, 3, 2]              
  8                  -1  2   3985920  ultralytics.nn.modules.C2f                   [576, 576, 2, True]           
  9                  -1  1    831168  ultralytics.nn.modules.SPPF                  [576, 576, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]                           
 12                  -1  2   1993728  ultralytics.nn.modules.C2f                   [960, 384, 2]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]                           
 15                  -1  2    517632  ultralytics.nn.modules.C2f                   [576, 192, 2]                 
 16                  -1  1    332160  ultralytics.nn.modules.Conv                  [192, 192, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]                           
 18                  -1  2   1846272  ultralytics.nn.modules.C2f                   [576, 384, 2]                 
 19                  -1  1   1327872  ultralytics.nn.modules.Conv                  [384, 384, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]                           
 21                  -1  2   4207104  ultralytics.nn.modules.C2f                   [960, 576, 2]                 
 22        [15, 18, 21]  1   3778591  ultralytics.nn.modules.Detect                [5, [192, 384, 576]]          
Model summary: 295 layers, 25859215 parameters, 25859199 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
DDP settings: RANK 0, WORLD_SIZE 4, DEVICE cuda:0
ClearML Task: created new task id=8aa4bc77fc784072b46cec459c17ed1b
2023-01-11 13:38:14,186 - clearml.Task - INFO - No repository found, storing script code instead
ClearML results page: https://app.clear.ml/projects/82fb00c3af104521af5dd8718a255f9d/experiments/8aa4bc77fc784072b46cec459c17ed1b/output/log
2023-01-11 13:38:20,151 - clearml.Task - WARNING - Parameters must be of builtin type (General/hydra[DictConfig])
Overriding model.yaml nc=80 with nc=5

                   from  n    params  module                                       arguments                     
  0                  -1  1      1392  ultralytics.nn.modules.Conv                  [3, 48, 3, 2]                 
  1                  -1  1     41664  ultralytics.nn.modules.Conv                  [48, 96, 3, 2]                
  2                  -1  2    111360  ultralytics.nn.modules.C2f                   [96, 96, 2, True]             
  3                  -1  1    166272  ultralytics.nn.modules.Conv                  [96, 192, 3, 2]               
  4                  -1  4    813312  ultralytics.nn.modules.C2f                   [192, 192, 4, True]           
  5                  -1  1    664320  ultralytics.nn.modules.Conv                  [192, 384, 3, 2]              
  6                  -1  4   3248640  ultralytics.nn.modules.C2f                   [384, 384, 4, True]           
  7                  -1  1   1991808  ultralytics.nn.modules.Conv                  [384, 576, 3, 2]              
  8                  -1  2   3985920  ultralytics.nn.modules.C2f                   [576, 576, 2, True]           
  9                  -1  1    831168  ultralytics.nn.modules.SPPF                  [576, 576, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]                           
 12                  -1  2   1993728  ultralytics.nn.modules.C2f                   [960, 384, 2]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]                           
 15                  -1  2    517632  ultralytics.nn.modules.C2f                   [576, 192, 2]                 
 16                  -1  1    332160  ultralytics.nn.modules.Conv                  [192, 192, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]                           
 18                  -1  2   1846272  ultralytics.nn.modules.C2f                   [576, 384, 2]                 
 19                  -1  1   1327872  ultralytics.nn.modules.Conv                  [384, 384, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]                           
 21                  -1  2   4207104  ultralytics.nn.modules.C2f                   [960, 576, 2]                 
 22        [15, 18, 21]  1   3778591  ultralytics.nn.modules.Detect                [5, [192, 384, 576]]          
Model summary: 295 layers, 25859215 parameters, 25859199 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
optimizer: SGD(lr=0.001) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.0015625), 83 bias
train: Scanning /usr/src/app/ultralytics/datasets/combine/labels/train... 8906 images, 44 backgrounds, 0 corrupt: 100%|██████████| 8906/8906 [00:00<00:00, 10586.23it/s]
Signal received. 15 <frame at 0x7f56ac1d0b80, file '/opt/conda/lib/python3.8/site-packages/clearml/task.py', line 3924, code signal_handler>
Signal received. 15 <frame at 0x7f56ac1d0b80, file '/opt/conda/lib/python3.8/site-packages/clearml/task.py', line 3924, code signal_handler>
Signal received. 15 <frame at 0x7f56ac1d07c0, file '/opt/conda/lib/python3.8/site-packages/clearml/task.py', line 3924, code signal_handler>
Signal received. 15 <frame at 0x7f56ac1d0b80, file '/opt/conda/lib/python3.8/site-packages/clearml/task.py', line 3924, code signal_handler>
Signal received. 15 <frame at 0x7f56ac1d0b80, file '/opt/conda/lib/python3.8/site-packages/clearml/task.py', line 3924, code signal_handler>
Signal received. 15 <frame at 0x7f56ac1d0b80, file '/opt/conda/lib/python3.8/site-packages/clearml/task.py', line 3924, code signal_handler>
Signal received. 15 <frame at 0x7f56ac1d0b80, file '/opt/conda/lib/python3.8/site-packages/clearml/task.py', line 3924, code signal_handler>
Signal received. 15 <frame at 0x7f56ac1d0b80, file '/opt/conda/lib/python3.8/site-packages/clearml/task.py', line 3924, code signal_handler>
train: New cache created: /usr/src/app/ultralytics/datasets/combine/labels/train.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
val: Scanning /usr/src/app/ultralytics/datasets/combine/labels/valid... 4426 images, 10 backgrounds, 0 corrupt: 100%|██████████| 4426/4426 [00:00<00:00, 6132.49it/s]
Signal received. 15 <frame at 0x7f55d58af040, file '/opt/conda/lib/python3.8/site-packages/clearml/task.py', line 3924, code signal_handler>
Signal received. 15 <frame at 0x7f55d58c3400, file '/opt/conda/lib/python3.8/site-packages/clearml/task.py', line 3924, code signal_handler>
Signal received. 15 <frame at 0x7f55d573cd60, file '/opt/conda/lib/python3.8/site-packages/clearml/task.py', line 3924, code signal_handler>
Signal received. 15 <frame at 0x7f55d5898040, file '/opt/conda/lib/python3.8/site-packages/clearml/task.py', line 3924, code signal_handler>
Signal received. 15 <frame at 0x7f55d58af040, file '/opt/conda/lib/python3.8/site-packages/clearml/task.py', line 3924, code signal_handler>
Signal received. 15 <frame at 0x7f55d58af040, file '/opt/conda/lib/python3.8/site-packages/clearml/task.py', line 3924, code signal_handler>
Signal received. 15 <frame at 0x7f55d58af040, file '/opt/conda/lib/python3.8/site-packages/clearml/task.py', line 3924, code signal_handler>
Signal received. 15 <frame at 0x7f55d5737d60, file '/opt/conda/lib/python3.8/site-packages/clearml/task.py', line 3924, code signal_handler>
Traceback (most recent call last):
  File "/root/.config/Ultralytics/DDP/_temp_pae5uoea140206444466816.py", line 6, in <module>
    trainer.train()
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 177, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 275, in _do_train
    for i, batch in pbar:
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/data/base.py", line 179, in __getitem__
    return self.transforms(self.get_label_info(index))
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/data/augment.py", line 48, in __call__
    data = t(data)
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/data/augment.py", line 48, in __call__
    data = t(data)
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/data/augment.py", line 364, in __call__
    labels["instances"] = new_instances[i]
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/utils/instance.py", line 246, in __getitem__
    segments = self.segments[index] if len(self.segments) else self.segments
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 6

val: New cache created: /usr/src/app/ultralytics/datasets/combine/labels/valid.cache
Image sizes 640 train, 640 val
Using 32 dataloader workers
Logging results to runs/detect/train16
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/45 [00:00<?, ?it/s]WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 16178 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 16179 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 16181 closing signal SIGTERM
Signal received. 15 <frame at 0x7f56b00d6780, file '/opt/conda/lib/python3.8/site-packages/clearml/task.py', line 3924, code signal_handler>
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f56f00c93a0>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1301, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/opt/conda/lib/python3.8/multiprocessing/popen_fork.py", line 44, in wait
    if not wait([self.sentinel], timeout):
  File "/opt/conda/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/opt/conda/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/opt/conda/lib/python3.8/site-packages/clearml/task.py", line 3924, in signal_handler
    os.kill(os.getpid(), sig)
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/hub/session.py", line 26, in signal_handler
    sys.exit(signum)
  File "/opt/conda/lib/python3.8/site-packages/clearml/task.py", line 3850, in exit
    self._orig_exit(code)
SystemExit: 15
WARNING:torch.distributed.elastic.multiprocessing.api:Unable to shutdown process 16178 via 15, forcefully exitting via 9
WARNING:torch.distributed.elastic.multiprocessing.api:Unable to shutdown process 16181 via 15, forcefully exitting via 9
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 2 (pid: 16180) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 723, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/root/.config/Ultralytics/DDP/_temp_pae5uoea140206444466816.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-01-11_13:38:37
  host      : 5f17aea84b52
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 16180)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by Laughing-q** [comment]
@Tsardoz looks like it's segment issue, but you're training detection right?
logically if you're training detection, the code won't do any index operation to segment. But the error raised from this line:
[https://github.com/ultralytics/ultralytics/blob/f5dfd5be8b169935266ff602b8004a34d94feec5/ultralytics/yolo/utils/instance.py#L246](https://github.com/ultralytics/ultralytics/blob/f5dfd5be8b169935266ff602b8004a34d94feec5/ultralytics/yolo/utils/instance.py#L246)
I think your labels probably include segment labels. Can you check your dataset?
Also please refer to issue. [https://github.com/ultralytics/ultralytics/issues/234](https://github.com/ultralytics/ultralytics/issues/234)

**Comment by Tsardoz** [comment]
Thanks for your quick response.
Yes I am training detections and there are no segments. Some of the bounding box coordinates are very long though.
(many digits after decimal point)
Could that be it?
I have been training the same data with yolov5 without any issues before so I am not sure what the problem could be.

**Comment by Laughing-q** [comment]
@Tsardoz long coordinates won't affect if you make sure there're only five columns in each rows.
I noticed you're using clearml? the guy in issue #234 is also using clearml, so I suppose you might also got the same issue as him.
BTW yes v5 loader won't raise error if a part of your labels are segment, but it'll eliminate some of your labels while training. So this could be why you're getting nan loss while doing val.
Or if you don't mind, can you public your dataset then I can check it for you? if the datasets are all right, I also can reproduce your error then fix it. :)

**Comment by Tsardoz** [comment]
Thanks again @Laughing-q. I uninstalled clearml and ran again. I get the same issue. There is a validation nan in the csv file from the run so I dont think it is due to clearml. I tried again without v5loader=True and the training still crashes with the same error. I am pretty sure there are no segmentations present. I will double check tomorrow. Unfortunately I cannot supply the dataset images at all but could supply labels if that helps. I have attached some which are representative.
[set1.zip](https://github.com/ultralytics/ultralytics/files/10394210/set1.zip)

**Comment by Tsardoz** [comment]
@Laughing-q I have not tested this yet but I suspect the problem might be empty lines in the label files. Some just have a newline character. I will fix and report back when I get the chance

**Comment by Laughing-q** [comment]
@Tsardoz ok I've reproduced your issue by using your labels. Thanks! I'll let you know once I fix it.

**Comment by Laughing-q** [comment]
@Tsardoz actually there are several segment labels in you labels...so that's the problem..
like the `20221110033443.txt` one:
```
3 0.341016 0.668056 0.0601562 0.3944443 0.423438 0.657639 0.053125 0.2763893 0.382031 0.647917 0.0640625 0.3097220 0.776563 0.894444 0.203125 0.177778
```

**Comment by Tsardoz** [comment]
Thanks, sorry I should have replied earlier.
I found those labels and removed them.
I can now train without the v5loader=True (no error and crash) except it is still returning nan loss on valid set.
I will update once I find the issue.

**Comment by Laughing-q** [comment]
@Tsardoz did it happen at the first epoch? or all the epochs you trained.

**Comment by Tsardoz** [comment]
OK @Laughing-q I have finally got it running and removed all suspicious labels/images.
It still gives nan in val loss for all epochs not just the first.
This is the command I am using to train

!yolo task=detect mode=train model=yolov8s.pt data=fallset.yaml device=\'0,1,2,3,4,5\' epochs=20 batch=480 lr0=0.001 save=True

![image](https://user-images.githubusercontent.com/10258316/212021236-52d147dd-e0d6-4c6a-b59a-877f7ad7e275.png)

Set1 is the validation label file I am using.
[set1.zip](https://github.com/ultralytics/ultralytics/files/10399792/set1.zip)

**Comment by Laughing-q** [comment]
@Tsardoz ok I'll check it.

**Comment by AyushExel** [comment]
This issue might've been solved in the latest release. Please upgrade and let us know if you face any problems
