### ISSUE TITLE
Validation of pretrained model on custom dataset - how to match the classes ?

### ISSUE THREAD

**Issue by dmddmd** [ultralytics/ultralytics#2532]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My custom dataset has less classes than Coco (let's say 20). 4 classes of my custom dataset match 2 classes of coco.
It would be enough if it matches the classes with the same names.

But when I do validation, the metrics show the names of the first 20 coco classes.
I first thought that the values are ok but just the names should be changed to the 20 custom dataset class names.
But the values make no sense. It seems like it only shows values from the first 20 coco classes instead of showing the 20 custom dataset classes .

Maybe a modification of the yaml file is necessary? 

(The confusion matrix makes sense. There, I see the values for the 20 custom dataset classes (even if writes the first 20 coco classes names , I see that for example the 5th class value make sense as the custom dataset 5th class )

**Comment by glenn-jocher** [comment]
@dmddmd dear [username], thank you for reaching out to us. In your custom dataset, if the class names are the same as the corresponding classes in the COCO dataset, the model should automatically use those classes during validation. However, it's possible that the class names are not matching, and in that case, you would need to modify the yaml file to map those classes correctly. The metric values in the output file are based on the corresponding class IDs. So, even if the names are not matching, the values should be correct for the corresponding classes. If the confusion matrix is showing the correct values for your custom dataset, then the model is properly detecting and classifying the objects. Please feel free to ask any further questions or concerns.
