### ISSUE TITLE
RuntimeError scatter_add_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'

### ISSUE THREAD

**Issue by XDUbeginner** [ultralytics/ultralytics#2534]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

RuntimeError: scatter_add_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_determ
inistic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=Tr
ue' option, if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.
![image](https://github.com/ultralytics/ultralytics/assets/108787994/d600c0ff-d798-4fad-89ca-bdf439ca78ef)

### Environment

python = 3.9 ,
torch                     1.12.1+cu113 
torchaudio                0.12.1+cu113
torchvision               0.13.1+cu113
windows 11 

### Minimal Reproducible Example

    def select_topk_candidates(self, metrics, largest=True, topk_mask=None):
        """
        Select the top-k candidates based on the given metrics.

        Args:
            metrics (Tensor): A tensor of shape (b, max_num_obj, h*w), where b is the batch size,
                              max_num_obj is the maximum number of objects, and h*w represents the
                              total number of anchor points.
            largest (bool): If True, select the largest values; otherwise, select the smallest values.
            topk_mask (Tensor): An optional boolean tensor of shape (b, max_num_obj, topk), where
                                topk is the number of top candidates to consider. If not provided,
                                the top-k values are automatically computed based on the given metrics.

        Returns:
            (Tensor): A tensor of shape (b, max_num_obj, h*w) containing the selected top-k candidates.
        """

        # (b, max_num_obj, topk)
        topk_metrics, topk_idxs = torch.topk(metrics, self.topk, dim=-1, largest=largest)
        if topk_mask is None:
            topk_mask = (topk_metrics.max(-1, keepdim=True)[0] > self.eps).expand_as(topk_idxs)
        # (b, max_num_obj, topk)
        topk_idxs.masked_fill_(~topk_mask, 0)

        # (b, max_num_obj, topk, h*w) -> (b, max_num_obj, h*w)
        count_tensor = torch.zeros(metrics.shape, dtype=torch.int8, device=topk_idxs.device)
        ones = torch.ones_like(topk_idxs[:, :, :1], dtype=torch.int8, device=topk_idxs.device)
        for k in range(self.topk):
            # Expand topk_idxs for each value of k and add 1 at the specified positions
            count_tensor.scatter_add_(-1, topk_idxs[:, :, k:k + 1], ones)
        # filter invalid bboxes
        count_tensor.masked_fill_(count_tensor > 1, 0)

        return count_tensor.to(metrics.dtype)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by giter915** [comment]
修改cfg文件 改为False就ok

**Comment by glenn-jocher** [comment]
@XDUbeginner 谢谢您的反馈! 

根据报错信息，看起来是与 PyTorch 的 deterministic 算法相关的问题。您可以尝试在相关操作上，使用 `warn_only=True` 或将全局设置 `torch.use_deterministic_algorithms(False)`，以解决这个问题。此外，您也可以将您的 `cfg` 文件中的选项改为 `False`。 

如果您在对 `cfg` 文件进行更改后，仍然遇到问题，请随时在本仓库中提出 Issue，我们会尽快回复您的问题。

**Comment by DRRNO** [comment]
> 修改cfg文件 改为False就ok

请问，这个cfg文件路径是什么，还有修改哪处代码为False呢

**Comment by glenn-jocher** [comment]
@DRRNO 感谢您对 YOLOv8 的关注与使用。可以尝试使用简单的异常处理代码，比如封装try和except语句，捕获到这个 RuntimeError 后，使用 `torch.use_deterministic_algorithms(False)` 函数将其关闭再次执行即可。在CFG文件上，这与所提报错的具体场景有关，您需要进一步进行定位、分析与修改。在修改后可以尝试重新调整参数来检查报错是否已经被解决。希望以上信息能对您有所帮助。如果您有更多问题，请不要犹豫在此提出，我们会尽快回复您。

**Comment by Gavin-Evans** [comment]
> > 修改cfg文件 改为False就ok
> 
> 请问，这个cfg文件路径是什么，还有修改哪处代码为False呢

loacation: ultralytics\yolo\cfg\default.yaml,  then, deterministic: False

**Comment by glenn-jocher** [comment]
@Gavin-Evans thank you for your question! To modify the `cfg` file and set the deterministic flag to `False`, you can locate the `default.yaml` file in the `ultralytics/yolo/cfg` directory. Open the file and find the `deterministic` option. Change its value to `False`. This change should resolve the issue you are facing.

If you have any further questions or need assistance, please feel free to ask. We are here to help!

**Comment by Gavin-Evans** [comment]
> @Gavin-Evans thank you for your question! To modify the `cfg` file and set the deterministic flag to `False`, you can locate the `default.yaml` file in the `ultralytics/yolo/cfg` directory. Open the file and find the `deterministic` option. Change its value to `False`. This change should resolve the issue you are facing.
> 
> If you have any further questions or need assistance, please feel free to ask. We are here to help!

if need to use deterministic mode, upgrade torch >=2.0.0 for deterministic training please.

**Comment by glenn-jocher** [comment]
@Gavin-Evans Thank you for your feedback! However, if you need to use the deterministic mode, we recommend upgrading your Torch version to `>=2.0.0` for deterministic training. This will allow you to use the deterministic algorithm without experiencing the mentioned issue. If you have any further questions or need assistance, please don't hesitate to ask. We're here to help!

**Comment by chenjie04** [comment]
> > 修改cfg文件 改为False就ok
> 
> 请问，这个cfg文件路径是什么，还有修改哪处代码为False呢

在ultralytics/cfg/default.yaml里

**Comment by glenn-jocher** [comment]
感谢您的提问！在 `ultralytics/cfg/default.yaml` 文件中进行检查和更改，应该能帮助您解决问题。如果还有其他问题，请随时告知。
