### ISSUE TITLE
How to overrides runs/detect/train path and function related  to this ?

### ISSUE THREAD

**Issue by TapendraBaduwal** [ultralytics/ultralytics#2535]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to apply Multiprocessing so want to know the which user train output save in respective folders of runs?

**Comment by glenn-jocher** [comment]
@TapendraBaduwal hello, thank you for reaching out to us. By default, YOLOv8 saves training outputs into the `runs/train` directory. The output of each training run is saved in a separate folder named with the date and time stamp of the run. Each training run is unique, so you won't have to worry about the results of one run being mixed up with the result of another. 
If you plan to use multiprocessing for your training, YOLOv8 provides multi-GPU training right out of the box. This means that your training updates will be synced across all the GPUs you are using, and the training output will be saved in the same manner as when using a single GPU. Let us know if you have any other questions or concerns.
