### ISSUE TITLE
Missing Arguments on Prediction Documentation

### ISSUE THREAD

**Issue by MLEI-AERO** [ultralytics/ultralytics#2536]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection, Other

### Bug

To setup an equal yolov5 and yolov8 environment I focused on the prediction functionality only. As I wanted to control the result path of the result text document, I couldn't find the field "project=" like in yolov5 in the doc. But fortunately it works on yolov8 too. Further the example in the doc shows a field "imgz=", however the supported argument list doesn't contain it.

### Environment

[https://docs.ultralytics.com/modes/predict/#arguments](https://docs.ultralytics.com/modes/predict/#arguments)

### Minimal Reproducible Example

![grafik](https://github.com/ultralytics/ultralytics/assets/61831930/7a54a987-9a20-472f-9c84-38b1ef37d986)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @MLEI-AERO, 

Thank you for reaching out to us. We appreciate your interest in YOLOv8. We apologize for the confusion in the documentation and the missing supported argument list. 

As you have rightly observed, the "project" field is not documented in YOLOv8. However, it does work in YOLOv8, like in YOLOv5. We will update the documentation accordingly to reflect this.

Regarding the "imgz" field, please note that it is not one of the supported arguments in YOLOv8. We apologize for any confusion this may have caused. Please refer to our [YOLOv8 Docs](https://docs.ultralytics.com) for a complete list of supported arguments.

Thank you for bringing this to our attention! If you have any additional questions or if there is anything more we can do to assist you, please do not hesitate to let us know.
