### ISSUE TITLE
yolov8-pose custom model, onnxruntime error

### ISSUE THREAD

**Issue by TommyZihao** [ultralytics/ultralytics#2537]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I try to export my custom yolov8-pose model to onnx, and use onnxruntime to inference
I got the onnx file, but predict result in `runs/pose/predict` is empty
and ort_session.run get died
I wonder why and how to fix this

> model
> https://zihao-download.obs.cn-east-3.myhuaweicloud.com/yolov8/datasets/Triangle_215_Dataset/checkpoint/Triangle_215_yolov8n_pretrain.pt

> image
> https://zihao-openmmlab.obs.myhuaweicloud.com/20220610-mmpose/triangle_dataset/test_img/triangle_4.jpg

```python
from ultralytics import YOLO

# Load a model
model = YOLO('checkpoint/Triangle_215_yolov8n_pretrain.pt')

# Export the model
model.export(format='onnx')

!yolo predict pose model=checkpoint/Triangle_215_yolov8n_pretrain.onnx source=images/triangle_4.jpg

import onnxruntime

ort_session = onnxruntime.InferenceSession('checkpoint/Triangle_215_yolov8m_pretrain.onnx', providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'])

x = torch.randn(1, 3, 640, 640).numpy()
ort_inputs = {'images': x}
ort_output = ort_session.run(['output0'], ort_inputs)[0]
```

<img width="1252" alt="image" src="https://github.com/ultralytics/ultralytics/assets/36354458/a8dc8567-b9f7-4906-bbd8-d8107119abaf">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@TommyZihao I'm not able to reproduce the issue and I actually got predictions from your model and your image.
```python
model = YOLO('/home/laughing/Downloads/Triangle_215_yolov8n_pretrain.pt')
model.export(format="onnx")
```
```python
model = YOLO('/home/laughing/Downloads/Triangle_215_yolov8n_pretrain.onnx')
model.predict("/home/laughing/Downloads/triangle_4.jpg", task="pose", save=True)

import torch
import onnxruntime

ort_session = onnxruntime.InferenceSession('/home/laughing/Downloads/Triangle_215_yolov8n_pretrain.onnx', providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'])

x = torch.randn(1, 3, 640, 640).numpy()
ort_inputs = {'images': x}
ort_output = ort_session.run(['output0'], ort_inputs)[0]
```
![triangle_4](https://github.com/ultralytics/ultralytics/assets/61612323/9ffcdcad-75d1-4bf8-84b7-b315ea2bddbd)

But I did noticed a strange error when I put `model.export` and `onnxruntime.InferenceSession` together in the same code block. So I run export first then predict and onnx.inference, and everything looks good to me.

**Comment by TommyZihao** [comment]
Thanks, you are right and I'm fine now.

**Comment by glenn-jocher** [comment]
@TommyZihao you're welcome! I'm glad to hear that it's working now. If you have any other issues or questions, don't hesitate to ask. We're always here to help.
