### ISSUE TITLE
sometimes model.track doesnot assign track id in initial detection

### ISSUE THREAD

**Issue by parthapn98** [ultralytics/ultralytics#2544]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

when running 

```python
results = self.model.track(
            source=file,
            tracker="botsort.yaml",
            verbose=False,
            conf=self.conf,
            iou=self.iou,
            show=True,
            stream=True,
            classes=self.classes_lst,
        )
```
the track id is not assigned in the first detection

Note: This bug was detected repeatably for one video only so far,
we implement a workaround by checking is_track before accessing track ids,

Model used: yolo-pose-n

Same Video: yolo-det-n has no issue

**Comment by glenn-jocher** [comment]
@parthapn98 thank you for bringing this to our attention. We appreciate you taking the time to search for similar issues before reporting this bug. 

Based on the information you provided, it looks like the track id is not assigned in the first detection when running the track function with the given parameters. However, we are glad to know that you were able to find a workaround by checking is_track before accessing track ids. 

We will investigate this issue further to see if we can find a permanent solution. In the meantime, if you encounter any further similar issues, please don't hesitate to let us know and we'll do our best to assist you.
