### ISSUE TITLE
How to get results like `model(img_path)` of my custom onnx yolov8-pose model?

### ISSUE THREAD

**Issue by TommyZihao** [ultralytics/ultralytics#2548]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to use onnxruntime to deploy this model.
The output of my custom yolov8-pose onnx model is (1, 14, 8400)
Is there an easy way to get results like `results = model(img_path)` from this (1, 14, 8400) array?
So I can visualize more easily.
Thanks!

**Comment by TommyZihao** [comment]
I want results like this to do visualization

<img width="612" alt="image" src="https://github.com/ultralytics/ultralytics/assets/36354458/079fd30f-deb9-40b6-a2ee-b8cc9e5e96d7">

**Comment by TommyZihao** [comment]
@Laughing-q @glenn-jocher

**Comment by TommyZihao** [comment]
Anyone can help me?

**Comment by glenn-jocher** [comment]
@TommyZihao hi there! I'd be happy to help. From what I understand, you have an Onnx model based on our YOLOv8-pose model, and you have the output shape as (1, 14, 8400). If you want to get results like the `results = model(img_path)` format for visualization, you can first reshape the output to your desired shape. Then, you can loop through each detection and extract the class ID, coordinates, and confidence value. With these values, you can create a bounding box and add the class label and confidence value to it. Alternatively, you can use a visualization library like OpenCV to display the bounding boxes on the input image. If you need more help with the implementation, feel free to ask.

**Comment by TommyZihao** [comment]
Is there a off-the-shelf built-in function to do this in yolov8?

**Comment by glenn-jocher** [comment]
@TommyZihao hi there! As far as I know, there is no built-in function in YOLOv8 to directly extract and visualize detection results from an Onnx model output. However, you can reshape the output to your desired shape and then loop through each detection to extract the class ID, bounding box coordinates, and confidence value. With these values, you can create bounding boxes and add the class label and confidence value to them. Alternatively, you can use a visualization library like OpenCV to display the bounding boxes on the input image. If you need more help with the implementation, feel free to ask.

**Comment by TommyZihao** [comment]
How to extract bbox and keypoint prediction results in (1, 14, 8400) tensor, including coordinates and confidence.
What's in (1, 14, 8400)? Is there any doc?

**Comment by glenn-jocher** [comment]
@TommyZihao hi there! The (1, 14, 8400) output tensor from YOLOv8-pose Onnx model contains 14 detections (keypoint predictions) for a single input image. To extract the detection results, you need to first reshape the tensor to a shape of (14, 6), where each row contains the class ID, confidence score, and (x, y) coordinates of the keypoint. Once you have the detection results in this format, you can create bounding boxes and add the class label and confidence value to them. Alternatively, you can use a visualization library like OpenCV to display the bounding boxes on the input image. Please let me know if you have further questions or need more clarification.

**Comment by Laughing-q** [comment]
@TommyZihao we parse the outputs internally in our predictor.postprocess for all the tasks, here's how we parse the output for pose model, which you can refer:
[https://github.com/ultralytics/ultralytics/blob/229119c376070d3c7bc0170646e3651155024d38/ultralytics/yolo/v8/pose/predict.py#L24-L39](https://github.com/ultralytics/ultralytics/blob/229119c376070d3c7bc0170646e3651155024d38/ultralytics/yolo/v8/pose/predict.py#L24-L39)

**Comment by TommyZihao** [comment]
> ultralytics/ultralytics/yolo/v8/pose/predict.py

Thanks, but `preds` in this code fragment is not (1, N, 8400), I wonder how to deal with it.

**Comment by Laughing-q** [comment]
@TommyZihao oh yes you're right, we process the preds with `1,N,8400` in our nms fucntion `non_max_suppression` function and output a list and then goes to `predictor.postprocess`.
[https://github.com/ultralytics/ultralytics/blob/229119c376070d3c7bc0170646e3651155024d38/ultralytics/yolo/utils/ops.py#L133](https://github.com/ultralytics/ultralytics/blob/229119c376070d3c7bc0170646e3651155024d38/ultralytics/yolo/utils/ops.py#L133)

**Comment by glenn-jocher** [comment]
@TommyZihao hi there! The `img` variable used in the code snippet you mentioned is the resized version of your input image with the longer side scaled to 640 pixels while preserving the aspect ratio. 

The shape of `img` is determined by the reshape operation on `pred` tensor, which applies the scaling to the box coordinates returned by the neural network to be relative to the `img` size. The `round()` method rounds the floating-point values to the nearest integer, which are then used to define the coordinates of the bounding boxes. 

If you are observing a reduction in the accuracy of your detection results due to the re-scaling of your image, you may want to try a different combination of scalling parameters. Please let me know if you have further questions or need more clarification.

**Comment by Laughing-q** [comment]
@TommyZihao `img` is the resized image that produced after preprocessing and `orig_img` is the original image.
