### ISSUE TITLE
[RFC] Use `classmethod` to construct `YOLO`

### ISSUE THREAD

**Issue by zhiqwang** [ultralytics/ultralytics#255]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

[`classmethod`](https://docs.python.org/3/library/functions.html#classmethod) can be used as an alternative "constructor" in python, it's more pythonic and cleaner to implement multiple constructors.

Specifically, we can modify `YOLO` as follows,

Through `__int__`:
```python
from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.yaml")  # build a new model from scratch
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)
```
vs `@classmethod`:
```python
from ultralytics import YOLO

# Load a model
model = YOLO.from_config("yolov8n.yaml")  # build a new model from scratch
model = YOLO.from_pretrained("yolov8n.pt")  # load a pretrained model (recommended for training)
```

### Use case

It is widely used in other repos, such as [`from_pretrained`](https://github.com/huggingface/transformers/blob/8f796960f6bb6e68c673a2f682d5ac911f671ed8/src/transformers/modeling_utils.py#L1770) in 🤗 Transformers.

### Additional

- See https://stackoverflow.com/a/682545/7109845 for more details.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@zhiqwang thanks for the feedback. Yeah, it might make sense to add these explicit function names as alias/optional to the existing method. We chose one method here to avoid confusion but I think some users might like the explicit usage. We'll discuss this internally.

**Comment by zhiqwang** [comment]
@AyushExel 

Very glad to hear that, it is also simpler and cleaner regarding the programming style and future maintenance compare with the following writing style.

https://github.com/ultralytics/ultralytics/blob/55b313b167d2e65910058ca5710483c90a8208c4/ultralytics/yolo/engine/model.py#L55
