### ISSUE TITLE
integer vs floating bounding box coordinates

### ISSUE THREAD

**Issue by erkara** [ultralytics/ultralytics#2550]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am not sure how relevant/important is this but I want to bring it up. I trained a model and want to get the bounding box coordinates as usual

detection = model("datasets/test/images/9000.jpg")
print(detection[0].boxes.xyxy)
tensor([[311.00000, 236.00000, 318.00000, 243.00000,   0.79837,   0.00000]], device='cuda:0')

The coordinates has integer values. This is probably floating-point coordinates would not make sense in the context of pixel-based image manipulation. However, I want to get the actual floating-point coordinates to get a precise estimate about the location of my particles. Thus, I removed round() operation from "postprocess" function located at
"yolov8/ultralytics/yolo/v8/detect/predict.py". Then I got the following

detection = model("datasets/test/images/9000.jpg")
print(detection[0].boxes.xyxy)
tensor([[311.00192, 235.50635, 318.44250, 243.42377,   0.79837,   0.00000]], device='cuda:0')

This is what I needed but my question is does this practice break any other code piece somewhere? If not, do you think this can be an option that be provided to the users? Thank you!

**Comment by glenn-jocher** [comment]
@erkara hello! Thank you for bringing up your concern. We understand that you want to get the precise estimate about the location of your particles, and we appreciate your effort to modify the code to achieve this. The practice of removing the `round()` function from the `postprocess()` function and outputting floating-point coordinates should not cause any functional issues with the rest of the code. However, we must note that the output of `detect()` is intended to be used with YOLOv8 training, and the expected output of detections is integer values. Therefore, outputting floating-point values could potentially cause issues with the model's performance if used in other contexts. As for the option to output floating-point values, this is not currently supported as it is not the intended use case. Nevertheless, thank you for your feedback, and we will keep your suggestion in mind for any future improvements. Let us know if you have any other questions or concerns.
