### ISSUE TITLE
How to sum the weights of two Yolov8 models?

### ISSUE THREAD

**Issue by vtanwar-iitr** [ultralytics/ultralytics#2554]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to aggregate the weights of two different versions of the Yolov8 models (of the same type like yolov8n) to get the third aggregated model.

For example:

model = YOLO(yolov8n.yaml).load(yolov8n.pt) 

result_1 = model.train(data='coco128.yaml', **epochs=2**, imgsz=640, **batch=16**, project='Results_1')

result_2 = model.train(data='coco128.yaml', **epochs=3**, imgsz=640, **batch=32**, project='Results_2')

Then how to get/compute
result_3 = (result_1 + result_2)/2 ??   # this will be a new yolov8n model with aggregated weights of result_1 and result_2.

I know if I can find the weights obtained in result_1 and result_2, then I can take their mean. But I am unable to extract/find their weights.

Thanks in advance.

**Comment by glenn-jocher** [comment]
Hello @vtanwar-iitr,

Thank you for reaching out to us with your question. To aggregate the weights of two different versions of the YOLOv8 model, first, you will need to save the weights of each version. The `.train()` method does not return the model weights as it only saves the trained model. 

After saving the weights, you can load the weights of both models, calculate the mean of all the weights and save them as the new weights. The saved new weights can then be used to create the new model with aggregated weights.

Please refer to the PyTorch's documentation on how to [save and load model weights](https://pytorch.org/tutorials/beginner/saving_loading_models.html) for more information.

I hope this helps you. Let me know if you need further assistance.

Best regards.

**Comment by jaylongnwnr** [comment]
Hello @glenn-jocher ,

I have tried many ways to solve this problem, but I found that there is no key concept in the yolov8 model, so I can't get the model parameters by searching each key. I would like to ask if there is any better suggestion

**AttributeError: 'YOLO' object has no attribute 'keys'. See valid attributes below.** The error make me not to complete the project

Thanks in advance.

**Comment by vtanwar-iitr** [comment]
> Hello @vtanwar-iitr,
> 
> Thank you for reaching out to us with your question. To aggregate the weights of two different versions of the YOLOv8 model, first, you will need to save the weights of each version. The `.train()` method does not return the model weights as it only saves the trained model.
> 
> After saving the weights, you can load the weights of both models, calculate the mean of all the weights and save them as the new weights. The saved new weights can then be used to create the new model with aggregated weights.
> 
> Please refer to the PyTorch's documentation on how to [save and load model weights](https://pytorch.org/tutorials/beginner/saving_loading_models.html) for more information.
> 
> I hope this helps you. Let me know if you need further assistance.
> 
> Best regards.

Thank you, @glenn-jocher, for your help. I am able to aggregate two versions of Yolov8 as follows:

G_model = YOLO('yolov8n.pt')

path_v1 = './train1/weights/best.pt'
model_v1 = attempt_load_weights(path_v1)
mod_v1 = model_v1.state_dict()

path_v2 = './train2/weights/best.pt'
model_v2 = attempt_load_weights(path_v2)
mod_v2 = model_v2.state_dict()

avg_weights = copy.deepcopy(mod_v2)
for key in avg_weights.keys():
    avg_weights[key] = mean(mod_v1[key], mod_v2[key])

Now, the type(avg_weights) == <class 'collections.OrderedDict'>

I am trying to save these weights as a ".pt" file as follows:

G_model .attempt_load_weights(avg_weights)
    
modelDic = {'epoch':-1, 'best_fitness':None, 'model': global_model, 'ema':None, 'updates':None, 'optimizer':None, 'wandb_id':None, 'date':None}

torch.save(modelDic, 'yoloAvg.pt')

But it is showing errors:

AttributeError: 'YOLO' object has no attribute 'attempt_load_weights'. See valid attributes below.

    YOLO (You Only Look Once) object detection model.

    Args:
        model (str, Path): Path to the model file to load or create.
        task (Any, optional): Task type for the YOLO model. Defaults to None.

    Attributes:
        predictor (Any): The predictor object.
        model (Any): The model object.
        trainer (Any): The trainer object.
        task (str): The type of model task.
        ckpt (Any): The checkpoint object if the model loaded from *.pt file.
        cfg (str): The model configuration if loaded from *.yaml file.
        ckpt_path (str): The checkpoint file path.
        overrides (dict): Overrides for the trainer object.
        metrics (Any): The data for metrics.

    Methods:
        __call__(source=None, stream=False, **kwargs):
            Alias for the predict method.
        _new(cfg:str, verbose:bool=True) -> None:
            Initializes a new model and infers the task type from the model definitions.
        _load(weights:str, task:str='') -> None:
            Initializes a new model and infers the task type from the model head.
        _check_is_pytorch_model() -> None:
            Raises TypeError if the model is not a PyTorch model.
        reset() -> None:
            Resets the model modules.
        info(verbose:bool=False) -> None:
            Logs the model info.
        fuse() -> None:
            Fuses the model for faster inference.
        predict(source=None, stream=False, **kwargs) -> List[ultralytics.yolo.engine.results.Results]:
            Performs prediction using the YOLO model.

    Returns:
        list(ultralytics.yolo.engine.results.Results): The prediction results.

I have also tried "load_state_dict" instead of "attempt_load_weights," but I got the same error.

How can I save the model in ".pt"?

Thanks

**Comment by glenn-jocher** [comment]
Hello @jaylongnwnr,

Thank you for the update. I apologize for the confusion, the method `attempt_load_weights` is used to load the weights into the model, not to save them.

To save the model with the aggregated weights, you can create a new `state_dict` using the `avg_weights` dictionary from your example and load it into the model using the `load_state_dict()` method. Then you can save the model state dictionary to a file using `torch.save()`. Here is an example code snippet to save the modified state dictionary:

```
G_model = YOLO('yolov8n.pt')

path_v1 = './train1/weights/best.pt'
model_v1 = attempt_load_weights(path_v1)
mod_v1 = model_v1.state_dict()

path_v2 = './train2/weights/best.pt'
model_v2 = attempt_load_weights(path_v2)
mod_v2 = model_v2.state_dict()

avg_weights = copy.deepcopy(mod_v2)
for key in avg_weights.keys():
    avg_weights[key] = mean(mod_v1[key], mod_v2[key])

# Load the state dict with the aggregated weights into the model
G_model.load_state_dict(avg_weights)

# Save the model state dictionary to a file
torch.save(G_model.state_dict(), 'yoloAvg.pt')
```

This should save the modified weights to a file in the PyTorch `.pt` format.

I hope this helps! Let me know if you have any further questions.

Best regards.

**Comment by jaylongnwnr** [comment]
Hello @glenn-jocher ,

Thank you very much for taking the time to reply. It has helped me solve some of the problems, but a new problem has arisen.

I used the method you provided to modify it, but when the aggregated_weights.pt was finally output, the file size doubled, which meant that they were not adding parameters but adding files. This is not the result I want. Is there any better suggestion to assist me to solve it

G_model = YOLO('yolov8m.pt')

avg_weights = copy.deepcopy(mod_v2[0])  # Initialize avg_weights with the first model's state_dict
for key in avg_weights.keys():
    tensors_v1 = [mod[key] for mod in mod_v1]  # Gather the corresponding tensors for the key from mod_v1
    tensors_v2 = [mod[key] for mod in mod_v2]  # Gather the corresponding tensors for the key from mod_v2
    avg_tensor = torch.mean(torch.stack(tensors_v1 + tensors_v2), dim=0)  # Compute the average tensor
    avg_weights[key] = avg_tensor

# Save the aggregated weights to a file
torch.save(avg_weights, 'aggregated_weights.pt')

# Assign the aggregated weights to the model's state dictionary
G_model.model.load_state_dict(torch.load('aggregated_weights.pt'), strict=False)


# Save the model to a file
torch.save(G_model.model, 'yoloAvg.pt')
