### ISSUE TITLE
verbose output

### ISSUE THREAD

**Issue by enheng-de** [ultralytics/ultralytics#2555]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In the latest version, using multi-object detection, how to print verbose output of all categories？

**Comment by glenn-jocher** [comment]
@enheng-de hello,

To print verbose output of all categories during multi-object detection in YOLOv8, you need to set the `--verbose` flag when running detection. This will output detailed information for each detected object including class, confidence, bbox coordinates, and all other associated information. 

I hope this helps! Let us know if you have any further questions or concerns. 

Best regards,
Glenn Jocher
