### ISSUE TITLE
How to fix the non-normalized or out of bounds coordinates problem on YOLOv8?

### ISSUE THREAD

**Issue by SaraDadjouy** [ultralytics/ultralytics#2557]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,
I'm training my dataset on YOLOv8. I've created the YOLO's format .yaml file. Here's my code for doing this where df is a dictionary including the images ground-truth boxes with format [xmin ymin xmax ymax]. Since these boxes contain the coordinates in pixels, I've followed the [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data/#13-organize-directories) guides:
`for img in df:
  gold_box = df[img]['Gold']

  x_min, y_min, x_max, y_max = gold_box[0], gold_box[1], gold_box[2], gold_box[3]
  
  img_dir = os.path.join(images_dir, img)
  loaded_img = cv2.imread(img_dir)
  img_width, img_height = loaded_img.shape[0], loaded_img.shape[1]

  x_center = (x_min + x_max)/2
  y_center = (y_min + y_max)/2
  width = x_max - x_min
  height = y_max - y_min

  x_center /= img_width
  y_center /= img_height
  width /= img_width
  height /= img_height

  img_filename = img[:-4] + '.txt'

  img_label_dir = os.path.join(labels_dir, img_filename)
  with open(img_label_dir, "w") as f:
    f.write('0 {} {} {} {}'.format(x_center, y_center, width, height)) `

But when I want to train the model, I get these warnings for 10 of the images:

![Capture](https://github.com/ultralytics/ultralytics/assets/89508482/467316e6-60ff-4f62-8e1f-18198544616f)

Why is this happening? Do you know how I can fix it?

**Comment by glenn-jocher** [comment]
@SaraDadjouy hello! These warning messages often indicate that the ground truth boxes for some of your images may not be correctly formatted or labeled, resulting in negative coordinates or widths/heights that are zero or negative. 

Make sure to double-check your ground truth boxes and confirm that they have been correctly labeled with the [correct YOLOv8 format](https://docs.ultralytics.com/tutorials/yolov8/#labeling-tool). You can also check the size and aspect ratio of the images to make sure they match your expectations.

If the issue persists, you may want to try cropping or resizing problematic images or removing them from the dataset altogether.
