### ISSUE TITLE
Accuracy of each class of bounding boxes

### ISSUE THREAD

**Issue by ue17** [ultralytics/ultralytics#2559]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In yolov8 detection, I would like to know the establishment of all classes, including the class that appears in the bounding box during inference.

### Additional

In ultralytics/yolo/v8/detect/predict.py, you will find the following code
def postprocess(self, preds, img, orig_imgs):.
        """Postprocesses predictions and returns a list of Results objects."""
        preds = ops.non_max_suppression(preds,
                                        self.args.conf, self.args.iou,
                                        self.args.iou,.
                                        agnostic=self.args.agnostic_nms,.
                                        max_det=self.args.max_det, self.args.classes=self.args.classes
                                        classes=self.args.classes)

Additionally, in ultralytics/yolo/utils/ops.py you will find the following code
def non_max_suppression(
        prediction,
        conf_thres=0.25,.
        iou_thres=0.45,
        classes=None, agnostic=False, and
        agnostic=False,
        multi_label=False, labels=(),
        labels=(),
        max_det=300, nc=0, # number of classes (optional)
        nc=0, # number of classes (optional)
        max_time_img=0.05,
        max_time_img=0.05, max_nms=30000,
        max_wh=7680,
):

I think I can call multiple results in one bouding box when predicting, perhaps by setting multi_label=True, but what command can I hit to set multi_label=True?

**Comment by AyushExel** [comment]
You can get the mAP of each class when you run validation on the trained dataset.
