### ISSUE TITLE
deal with weird rect stuff

### ISSUE THREAD

**Issue by sipie800** [ultralytics/ultralytics#2564]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

There is a rect training from yolov5. IMO it makes little sense to make rect training a special one. A model should be agnostic to any image sizes in a single batch rather than uses the similar size images in a batch. Or can we just make the rect trainning common, there are too many weird stuff in the code to support rect.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sipie800 thank you for reaching out with your feedback about the rect training in YOLOv8. We appreciate your input and suggestions. The goal of YOLOv8 is to provide a strong and flexible object detection model that can perform well across a variety of image sizes and configurations. We prioritize simplicity and ease of use, while still maintaining performance. However, we understand that there is always room for improvement, and we will take your suggestions into consideration as we continue to develop and evolve the YOLOv8 repository. If you are interested in contributing to the project, we welcome your contributions and invite you to submit a PR.
