### ISSUE TITLE
How does YOLOv8 calculate the tp, conf, pred_cls, target_cls arrays for the ap_per_class method?

### ISSUE THREAD

**Issue by MathewsJosh** [ultralytics/ultralytics#2565]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to replicate the code from the [ap_per_class()](https://docs.ultralytics.com/reference/yolo/utils/metrics/?h=recall#ultralytics.yolo.utils.metrics.FocalLoss.forward:~:text=ap_per_class,-Computes%20the%20average) method to generate the same validation graphs (Precision x Confidence, Recall x Confidence, Precision x Recall, F1-score x Confidence) from YOLOv8 for any object detection model. My goal is to make clear comparisons between the performance of detection models from different networks (such as the SSD MobileNet V2 FPNLite 640x640) with YOLO. However, I am having trouble understanding how the metric of true positives (``tp``) should be calculated and what the final size of this array should be. 

In the source code snippet below (``ap_per_class()``), ``tp`` (true positives) and ``conf`` (confidence) are treated as one-dimensional arrays but also two-dimensional a few lines down. This is evident in the line ``tp, conf, pred_cls = tp[i], conf[i], pred_cls[i]``, where each array is indexed by the same variable i. This only works correctly if all arrays are one-dimensional. Also, the ``cumsum(0)`` methods are called on ``tpc = tp[i].cumsum(0)`` and ``fpc = (1 - tp[i]).cumsum(0)``, which calculate the cumulative sum along the 0 axis. This would make sense if ``tp`` were a one-dimensional array, since the ``cumsum(0)`` operation on a one-dimensional array returns the cumulative sum of the elements.

However, notice that in the line ``for j in range(tp.shape[1]):``, ``tp.shape[1]`` suggests that ``tp`` is a two-dimensional array, where the second axis (index 1) is iterated. This happened even before, when ``r[ci]`` and ``p[ci]`` were calculated (notice in the ``recall[:, 0]``, ``precision[:, 0]``).

So I might be misunderstanding how these arrays and their dimensionality are calculated/defined or there might be some inconsistency in the code.

```python
def ap_per_class(tp, conf, pred_cls, target_cls, plot=False, save_dir=Path(), names=(), eps=1e-16, prefix=''):
    """
    Computes the average precision per class for object detection evaluation.

    Args:
        tp (np.ndarray): Binary array indicating whether the detection is correct (True) or not (False).
        conf (np.ndarray): Array of confidence scores of the detections.
        pred_cls (np.ndarray): Array of predicted classes of the detections.
        target_cls (np.ndarray): Array of true classes of the detections.
        plot (bool, optional): Whether to plot PR curves or not. Defaults to False.
        save_dir (Path, optional): Directory to save the PR curves. Defaults to an empty path.
        names (tuple, optional): Tuple of class names to plot PR curves. Defaults to an empty tuple.
        eps (float, optional): A small value to avoid division by zero. Defaults to 1e-16.
        prefix (str, optional): A prefix string for saving the plot files. Defaults to an empty string.

    Returns:
        (tuple): A tuple of six arrays and one array of unique classes, where:
            tp (np.ndarray): True positive counts for each class.
            fp (np.ndarray): False positive counts for each class.
            p (np.ndarray): Precision values at each confidence threshold.
            r (np.ndarray): Recall values at each confidence threshold.
            f1 (np.ndarray): F1-score values at each confidence threshold.
            ap (np.ndarray): Average precision for each class at different IoU thresholds.
            unique_classes (np.ndarray): An array of unique classes that have data.

    """

    # Sort by objectness
    i = np.argsort(-conf)
    tp, conf, pred_cls = tp[i], conf[i], pred_cls[i]

    # Find unique classes
    unique_classes, nt = np.unique(target_cls, return_counts=True)
    nc = unique_classes.shape[0]  # number of classes, number of detections

    # Create Precision-Recall curve and compute AP for each class
    px, py = np.linspace(0, 1, 1000), []  # for plotting
    ap, p, r = np.zeros((nc, tp.shape[1])), np.zeros((nc, 1000)), np.zeros((nc, 1000))
    for ci, c in enumerate(unique_classes):
        i = pred_cls == c
        n_l = nt[ci]  # number of labels
        n_p = i.sum()  # number of predictions
        if n_p == 0 or n_l == 0:
            continue

        # Accumulate FPs and TPs
        fpc = (1 - tp[i]).cumsum(0)
        tpc = tp[i].cumsum(0)

        # Recall
        recall = tpc / (n_l + eps)  # recall curve
        r[ci] = np.interp(-px, -conf[i], recall[:, 0], left=0)  # negative x, xp because xp decreases

        # Precision
        precision = tpc / (tpc + fpc)  # precision curve
        p[ci] = np.interp(-px, -conf[i], precision[:, 0], left=1)  # p at pr_score

        # AP from recall-precision curve
        for j in range(tp.shape[1]):
            ap[ci, j], mpre, mrec = compute_ap(recall[:, j], precision[:, j])
            if plot and j == 0:
                py.append(np.interp(px, mrec, mpre))  # precision at mAP@0.5

    # Compute F1 (harmonic mean of precision and recall)
    f1 = 2 * p * r / (p + r + eps)
    names = [v for k, v in names.items() if k in unique_classes]  # list: only classes that have data
    names = dict(enumerate(names))  # to dict
    if plot:
        plot_pr_curve(px, py, ap, save_dir / f'{prefix}PR_curve.png', names)
        plot_mc_curve(px, f1, save_dir / f'{prefix}F1_curve.png', names, ylabel='F1')
        plot_mc_curve(px, p, save_dir / f'{prefix}P_curve.png', names, ylabel='Precision')
        plot_mc_curve(px, r, save_dir / f'{prefix}R_curve.png', names, ylabel='Recall')

    i = smooth(f1.mean(0), 0.1).argmax()  # max F1 index
    p, r, f1 = p[:, i], r[:, i], f1[:, i]
    tp = (r * nt).round()  # true positives
    fp = (tp / (p + eps) - tp).round()  # false positives
    return tp, fp, p, r, f1, ap, unique_classes.astype(int)
```

Thank you in advance for your time and attention!

### Additional

Also, I provide below the function I created to calculate tp, conf, pred_cls, target_cls. Please let me know if I am doing something wrong in these calculations. Thanks!

```python
def calculate_detection_metrics(ground_truths_lists_for_every_image, detections_lists_for_every_image, iou_threshold=0.5):
	tp, conf, pred_cls, target_cls = [], [], [], []

	for idx in range(len(ground_truths_lists_for_every_image)):
		ground_truths = ground_truths_lists_for_every_image[idx]['objects']
		preds = detections_lists_for_every_image[idx]

		for pred in preds:
			best_iou = 0.0
			best_gt_idx = None
			pred_class = pred['label']
			conf.append(pred['score'])
			pred_cls.append(pred_class)

			for gt_idx in range(len(ground_truths)):
				if ground_truths[gt_idx]['name'] != pred_class:
					continue

				iou = calculate_iou(ground_truths[gt_idx]['bbox'], pred['bbox'])
				if iou > best_iou:
					best_iou = iou
					best_gt_idx = gt_idx

			if best_iou >= iou_threshold and best_gt_idx is not None:
				tp.append(1)
				target_cls.append(pred_class)
				del ground_truths[best_gt_idx]
			else:
				tp.append(0)
				
	tp = np.array(tp)
        conf = np.array(conf)
        pred_cls = np.array(pred_cls)
        target_cls = np.array(target_cls)

	return tp, conf, pred_cls, target_cls
```

**Comment by glenn-jocher** [comment]
@MathewsJosh thank you for your question! 

In the `ap_per_class()` method, `tp, conf, pred_cls` are sorted according to `conf`, then unique classes are found. Within the loop iterating through the unique classes, `tp` and `conf` are indexed by `i`, which represent the indices for the current class in `pred_cls`. Thus, `tp`, `conf`, and `pred_cls` are effectively filtered to only include detections for the current class within the loop.

`tp` is initialized as an empty list and appended with 0 or 1 depending on whether a detection is a false positive or true positive, respectively. `tp` is a 2D array where the first dimension corresponds to the number of unique classes, and the second dimension corresponds to the number of detections. The `cumsum(0)` method calculates the cumulative sum along the 0th axis (number of detections) of `tp`, so it returns an array of the same size as `tp`.

Please note that unless `tp`, `conf`, `pred_cls`, and `target_cls` are all one-dimensional arrays, the `ap_per_class()` method would result in an error. 

Regarding your `calculate_detection_metrics()` method, it seems like the implementation is correct and should generate appropriate arrays for `tp`, `conf`, `pred_cls`, and `target_cls`. However, please make sure that the format of the bounding box coordinates and labels in your `ground_truths_lists_for_every_image` and `detections_lists_for_every_image` match the expected format.

**Comment by Monett1** [comment]
@glenn-jocher 

Hi, I know this thread has been closed for a while but I had a question about how false negatives are accounted for in the tp, conf, pred_cls and target cls lists.  What should happen in the @MathewsJosh's calculate_detection_metrics function when a prediction for an image is empty but ground truth is not? How is this reflected in the variables returned by the function?

**Comment by glenn-jocher** [comment]
@Monett1 hi there! 👋

Great question! In the scenario where predictions for an image are empty but ground truth is not, this would result in false negatives. In the `calculate_detection_metrics` function, these cases should be accounted for by appending zeros to `tp` (true positives) for each ground truth object, indicating that the model failed to detect them. Since there are no prediction confidences or classes to append to `conf` and `pred_cls`, you would skip these. However, you should still append the ground truth classes to `target_cls` to reflect the missed detections.

Here's a snippet to illustrate handling false negatives:

```python
if len(preds) == 0:  # No predictions for this image
    for gt in ground_truths:
        tp.append(0)  # False negative
        target_cls.append(gt['class_label'])  # Append the ground truth class
```

This way, `target_cls` will have the class labels of the missed objects, and `tp` will have a corresponding zero for each false negative. `conf` and `pred_cls` remain unchanged for that image since there were no detections.

Hope this helps! If you have any more questions, feel free to ask. 😊

**Comment by Monett1** [comment]
Hello @glenn-jocher,
Thank you for your quick response, it has helped me but another question has arisen. By adding a value to tp but keeping conf unchanged, wouldn't the values of tp and conf be misaligned? As far as I understood each value of tp corresponds to a value of conf, but if we add a value of tp and not of conf, the next value we add of conf will coincide with the previous non-detection. Am I misunderstanding something?

**Comment by glenn-jocher** [comment]
@Monett1 hi there!

You're absolutely right, and I apologize for any confusion. For false negatives, we should not append to `tp` since there are no corresponding confidence scores. Instead, we only need to account for them when calculating metrics like recall, where the number of ground truths is relevant. The `tp`, `conf`, `pred_cls`, and `target_cls` arrays should indeed align, with each element in `tp` and `pred_cls` corresponding to an element in `conf`. 

For false negatives, you might consider updating the recall calculation directly, or keeping a separate count of false negatives if needed for your specific metric calculations. Thanks for catching that, and I hope this clarification helps! 😊

**Comment by glenn-jocher** [comment]
@Monett1 hi there!

Great observation! In the `ap_per_class` function, recall is indeed calculated considering false negatives. The number of true positives (`tp`) and the length of ground truths (`nt`) are used to calculate recall. Here's the key: `nt` includes all ground truths (positives), and `tp` only includes detections that are true positives. So, false negatives are implicitly included in the recall calculation as the difference between all ground truths and the true positives.

Here's a simplified example of how recall is calculated:

```python
recall = tpc / (n_l + eps)  # n_l is the number of labels (ground truths)
```

In this line, `tpc` is the cumulative sum of true positives, and `n_l` is the total number of ground truths for a class. The recall at each detection threshold is then interpolated to create the recall curve.

Hope this helps clear things up! 😊
