### ISSUE TITLE
How to use albumentations?

### ISSUE THREAD

**Issue by Tsardoz** [ultralytics/ultralytics#257]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

OK I found albumentations in yolo/data/augment.py.
It says # YOLOv5 Albumentations class (optional, only used if package is installed)
so I did pip install albumentations.
I edited T=[A.ImageCompression(quality_lower=75, p=0.5),]

but when I run it I get no sign of added augmentation
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))

Is there some other way of turning this on? This is all I had to do with v5 ...

**Comment by Laughing-q** [comment]
@Tsardoz so you edited the source code? which file did you edit ?
actually there're two dataloaders v8 loader and v5 loader(v5loader is for debug for now), I think you probably didn't edit the right file.

**Comment by Tsardoz** [comment]
Of course the comment even says # YOLO**v5** Albumentations class (optional, only used if package is installed).
It would help if I read stuff!

There is nothing in the path that suggests v5 though. It was in the file yolo/data/augment.py
Since I cannot find any other references to albumentations I presume it is not yet implemented for v8.

**Comment by Laughing-q** [comment]
@Tsardoz oh sorry I didn't see you've mentioned the file. yes the `yolo/data/augment.py` is the correct path for v8loader.
And I just did what you tried, edited `T=[A.ImageCompression(quality_lower=75, p=0.5),]`
before edit:
![pic-selected-230111-2132-47](https://user-images.githubusercontent.com/61612323/211819913-34ef898e-2007-41a0-9b66-ffa899907d8c.png)
after edit:
![pic-selected-230111-2133-17](https://user-images.githubusercontent.com/61612323/211819928-ed46e358-3e9c-47f3-9d98-3737af9a9edd.png)
I suppose it's working as you expect.

**Comment by Tsardoz** [comment]
Sorry @Laughing-q I still cannot get this to work.
With this command for training

!yolo task=detect mode=train model=yolov8s.pt data=fallset.yaml device=\'0,1,2,3,4,5\' epochs=20 batch=480 lr0=0.001 save=True

and this in the augment.py file
![image](https://user-images.githubusercontent.com/10258316/212022734-09586e0a-78c7-459a-befe-2d44ea983431.png)

I get this output (still no albumentations)
![image](https://user-images.githubusercontent.com/10258316/212022867-822faf98-31f8-495d-979e-a6ceec43077d.png)

**Comment by Laughing-q** [comment]
@Tsardoz it works well to me...
![image](https://user-images.githubusercontent.com/61612323/212024632-ad562999-853f-4072-9631-c9646a128ff8.png)
output:
![VphapZGql2](https://user-images.githubusercontent.com/61612323/212024571-bbb46da8-a4f7-44bf-86d5-03b835d1d985.jpg)

**Comment by Laughing-q** [comment]
@Tsardoz yes, maybe you can also install the latest version and try again. :)

**Comment by Tsardoz** [comment]
@Laughing-q OK I have reinstalled and tried again. Still nothing. I added this last line and nothing is printed

![image](https://user-images.githubusercontent.com/10258316/212031838-65019142-0487-4dbc-8667-c80b087ee963.png)

**Comment by Tsardoz** [comment]
I will try debugging this

**Comment by Tsardoz** [comment]
No I have not looked at YOLOv8 for a while.
We are using YOLOv5 for now until v8 becomes more stable.
Maybe it is related to albumentations I was using if you are having same
error.

**Comment by anniebrapheal** [comment]
I had the same issue, I was also using the yolo command for training, I added the augmentation in the file in this location "\anaconda3\envs\yolo-v8\lib\site-packages\ultralytics\yolo\data\augment.py". Basically inside the ultralytics package in my environment and it shows up in the list of augmentations. There might be a better way to add the augmentations.

**Comment by glenn-jocher** [comment]
@anniebrapheal thank you for sharing your experience and solution to the issue. As you mentioned, adding the augmentation in the "augment.py" file located in the Ultralytics package is a viable solution. However, it is important to note that modifying package files directly may lead to issues in the future, such as conflicts when updating the package. A better approach may be to create a custom script or module that imports and modifies the necessary functions from the Ultralytics package. Overall, it is always recommended to use best coding practices and avoid modifying package files directly whenever possible.

**Comment by sunman91** [comment]
I monkeypatched the constructor of Albumentations class in the augment.py file in my training file.
This way you do not have to edit the `augment.py` file directly in the library

Hope this helps :smiley: 

```
from ultralytics.data.augment import Albumentations
from ultralytics.utils import LOGGER, colorstr

def __init__(self, p=1.0):
        """Initialize the transform object for YOLO bbox formatted params."""
        self.p = p
        self.transform = None
        prefix = colorstr("albumentations: ")
        try:
            import albumentations as A

            # check_version(A.__version__, "1.0.3", hard=True)  # version requirement

            # Transforms
            T = [
                A.Rotate(limit = 10, p=0.5),
                A.Blur(p=0.01),
                A.MedianBlur(p=0.01),
                A.ToGray(p=0.01),
                A.CLAHE(p=0.01),
                A.RandomBrightnessContrast(p=0.0),
                A.RandomGamma(p=0.0),
                A.ImageCompression(quality_lower=75, p=0.0),
            ]
            self.transform = A.Compose(T, bbox_params=A.BboxParams(format="yolo", label_fields=["class_labels"]))

            LOGGER.info(prefix + ", ".join(f"{x}".replace("always_apply=False, ", "") for x in T if x.p))
        except ImportError:  # package not installed, skip
            pass
        except Exception as e:
            LOGGER.info(f"{prefix}{e}")

Albumentations.__init__ = __init__

model = YOLO('yolov8n.yaml').load('yolov8n.pt')

results = model.train(data='coco128.yaml', epochs=100, imgsz=640)

```
I added the Rotate augmentation and it showed up in the terminal
![image](https://github.com/ultralytics/yolov5/assets/51843952/a97903ab-f91c-4f4b-8618-0f464478a655)

**Comment by glenn-jocher** [comment]
@sunman91, that's a clever workaround using monkey patching to customize the Albumentations class without altering the library files directly. It's great to hear that your solution is working and you're seeing the Rotate augmentation in the terminal output. Your approach maintains the integrity of the original package while allowing for the flexibility needed for your specific use case. Thanks for sharing this with the community! 😊 Keep in mind that while monkey patching can be useful, it should be used judiciously as it can make the code harder to understand and maintain. Happy training!

**Comment by camachoandres88** [comment]
are there any updates on this? It would be nice to have this as an ultralytics feature

**Comment by glenn-jocher** [comment]
Thank you for your interest! Currently, there are no updates on this feature, but we appreciate your feedback and will consider it for future releases.

**Comment by glenn-jocher** [comment]
Thanks for sharing your experience. For Albumentations integration, we recommend using the official implementation details in our [Albumentations Integration Guide](https://docs.ultralytics.com/integrations/albumentations/) which handles spatial transforms and label fields automatically. Ensure you have `albumentations>=1.0.3` installed and the `label_fields` parameter matches your dataset's annotation format. For direct support, please provide a minimum reproducible example using our [Bug Report Template](https://github.com/ultralytics/ultralytics/issues/new/choose).
