### ISSUE TITLE
Issue with training a pretrained model

### ISSUE THREAD

**Issue by halqadasi** [ultralytics/ultralytics#2571]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I run this command in my terminal to train again Yolov8 best model from last training and I got this error. Last note, the last training was in laptop1 and I used the best model to train again on another laptop, but both have the latest package of ultralytics.

Error: 
WARNING ⚠️ best.pt appears to require 'ultralytics.nn.modules.conv', which is not in ultralytics requirements.
AutoInstall will run now for 'ultralytics.nn.modules.conv' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
requirements: YOLOv8 requirement "ultralytics.nn.modules.conv" not found, attempting AutoUpdate...
requirements: ❌ AutoUpdate skipped (offline)

### Environment

- YOLO: Ultralytics YOLOv8.0.97 🚀 Python-3.9.16 torch-2.0.0+cu117 CUDA:0 (Tesla T4, 15110MiB)
Setup complete ✅ (4 CPUs, 15.4 GB RAM, 0.0/27.0 GB disk)
- Python: 3.9.16
- OS: Ubuntu 22.04

### Minimal Reproducible Example

!yolo task=detect mode=train model=best.pt data=data.yaml epochs=20 plots=True iou=0.90 optimizer=Adam lr0=0.001 lrf=0.001

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by halqadasi** [comment]
Firstly, ultralytics==8.0.98 has been released yesterday on 11/05/2023. I discovered now I installed ultralytics==8.0.98 in the first laptop last night, but in the second laptop I installed ultralytics==8.0.97 two days ago. Now I updated the second laptop with the latest verion 8.0.98, the problem has been resolved.

**Comment by glenn-jocher** [comment]
@halqadasi thank you for the update, we're glad to hear that updating to the latest version of Ultralytics has resolved your issue. It's always good practice to ensure that all of the machines you are using for training have the same dependencies and software versions. If you encounter any other difficulties, please don't hesitate to reach out to us. We're here to help!
