### ISSUE TITLE
Paper of YOLOv8

### ISSUE THREAD

**Issue by hussein-MA** [ultralytics/ultralytics#2572]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In my thesis, I need the paper of YOLOv8 to discuss its specifications and architecture.

**Comment by glenn-jocher** [comment]
@hussein-MA hello! YOLOv8 is not a published paper, but rather a series of improvements and extensions made by Ultralytics to the YOLOv5 architecture. Most of the changes made in YOLOv8 relate to model scaling and architecture tweaks, which can be found in the code and the documentation in the Ultralytics YOLOv8 repo at https://github.com/ultralytics/ultralytics.

**Comment by hussein-MA** [comment]
Thank you @glenn-jocher  for answering my question, and 
thanks for the great efforts made by Ultralytics.

**Comment by glenn-jocher** [comment]
You're very welcome, @hussein-MA! We're glad to help and we appreciate your kind words. If you have any more questions about YOLOv8, feel free to ask!

**Comment by Coolzyh** [comment]
@glenn-jocher Do we have the whole model architecture figure of YOLOv8? I am working on a paper using YOLOv8, and I hope to cite the figure to illustrate the model structure briefly. 
YOLOv8 is a really good detection model and is easy to use. Thanks for your guys' great work!

**Comment by glenn-jocher** [comment]
@Coolzyh thank you for your interest in YOLOv8! We do not have a standalone figure of the model architecture specifically for YOLOv8. However, the architecture of YOLOv8 is based on YOLOv5, with various modifications in terms of model scaling and architecture tweaks. Therefore, you could use the architecture figure of YOLOv5 and mention the specific changes made in YOLOv8 in your paper. We're glad that you find YOLOv8 easy to use and we appreciate your kind words!

**Comment by d-kleine** [comment]
Would it be possible to publish a paper on yolov8, or at least providing a written overview of the changes to yolov5, including architecture diagrams, etc.? 

This would make understanding easier why components have been used, changed and why.

**Comment by Petros626** [comment]
you could also refer to this:
`Real-Time Flying Object Detection with YOLOv8`
`A COMPREHENSIVE REVIEW OF YOLO ARCHITECTURES IN COMPUTER VISION: FROM YOLOV1 TO YOLOV8 AND YOLO-NAS`
`An Improved YOLOv8 OBB Model for Ship Detection through
Stable Diffusion Data Augmentation`

**Comment by glenn-jocher** [comment]
@d-kleine @Petros626 thanks for the suggestions and references! While we initially considered publishing a formal paper, we've opted to focus on comprehensive documentation instead due to YOLOv8's rapidly evolving nature. Our [YOLOv8 documentation](https://docs.ultralytics.com/models/yolov8/) provides detailed technical information, and users can cite YOLOv8 using the BibTeX format provided in the docs. @Petros626, those references you shared are great examples of how researchers are successfully incorporating YOLOv8 into their work!
