### ISSUE TITLE
can i use classification to classify human activity, and my dataset contains video

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/ultralytics#2574]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to  classify human activity, and my dataset contains video, can yolov8 do the job ?if yes , how ?

**Comment by glenn-jocher** [comment]
@totoadel hello! YOLOv8 can be used for object detection in video, but it may not be the best option for activity classification specifically. YOLOv8 can identify and locate objects in each frame of a video, which could potentially be used as features for activity classification, but the classification task itself would require a separate algorithm. I would recommend looking into other approaches for activity classification, such as using recurrent neural networks (RNNs) or 3D convolutions. Let me know if you have any more questions!
