### ISSUE TITLE
can i make model for label images automatically ?

### ISSUE THREAD

**Issue by 7assanx7** [ultralytics/ultralytics#2576]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i use annotation tool to label images for yolo model but if i want make model to label images automatically how can i do that ?

**Comment by AyushExel** [comment]
yes you can! Here's the PR that adds the functionality to the docs for easier access
https://github.com/ultralytics/ultralytics/pull/2577
