### ISSUE TITLE
Attribute Error : module numpy has no attribute 'object'

### ISSUE THREAD

**Issue by BhooshanDeshpande** [ultralytics/ultralytics#2578]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I am trying to run yolo prediction on a frame obtained by realsense for detection/classification. The error that i recieved is 
```
/home/beast/.local/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:572: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  (np.object, string),
Traceback (most recent call last):
  File "/home/beast/machine_learning/yolo_v8/yolo_v8.py", line 20, in <module>
    results = model(color_image)
  File "/home/beast/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 111, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/beast/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/beast/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 248, in predict
    self.predictor = TASK_MAP[self.task][3](overrides=overrides, _callbacks=self.callbacks)
  File "/home/beast/.local/lib/python3.8/site-packages/ultralytics/yolo/v8/segment/predict.py", line 13, in __init__
    super().__init__(cfg, overrides, _callbacks)
  File "/home/beast/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 109, in __init__
    callbacks.add_integration_callbacks(self)
  File "/home/beast/.local/lib/python3.8/site-packages/ultralytics/yolo/utils/callbacks/base.py", line 205, in add_integration_callbacks
    from .tensorboard import callbacks as tensorboard_cb
  File "/home/beast/.local/lib/python3.8/site-packages/ultralytics/yolo/utils/callbacks/tensorboard.py", line 5, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/beast/.local/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 13, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/home/beast/.local/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 13, in <module>
    from tensorboard.summary.writer.event_file_writer import EventFileWriter
  File "/home/beast/.local/lib/python3.8/site-packages/tensorboard/summary/__init__.py", line 25, in <module>
    from tensorboard.summary import v1  # noqa: F401
  File "/home/beast/.local/lib/python3.8/site-packages/tensorboard/summary/v1.py", line 26, in <module>
    from tensorboard.plugins.histogram import summary as _histogram_summary
  File "/home/beast/.local/lib/python3.8/site-packages/tensorboard/plugins/histogram/summary.py", line 38, in <module>
    from tensorboard.plugins.histogram import summary_v2
  File "/home/beast/.local/lib/python3.8/site-packages/tensorboard/plugins/histogram/summary_v2.py", line 38, in <module>
    from tensorboard.util import tensor_util
  File "/home/beast/.local/lib/python3.8/site-packages/tensorboard/util/tensor_util.py", line 24, in <module>
    from tensorboard.compat.tensorflow_stub import dtypes, compat, tensor_shape
  File "/home/beast/.local/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/__init__.py", line 25, in <module>
    from .dtypes import as_dtype  # noqa
  File "/home/beast/.local/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py", line 572, in <module>
    (np.object, string),
  File "/home/beast/.local/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

Please let me know what should I do to fix this bug/error. 

### Environment

my environment looks like this 
```
python 3.8.10
torch 1.9.0.dev20210518+cu111
numpy 1.24.3
```

### Minimal Reproducible Example

My code is short and simple 
```
import cv2
from ultralytics import YOLO
import pyrealsense2 as rs
import numpy as np 

pipe = rs.pipeline()
profile = pipe.start()
model = YOLO('yolov8n-seg.pt')

try:
  while True:
    frames = pipe.wait_for_frames()
    color_frame = frames.get_color_frame()

    if not color_frame:
        print("Did not receive color frame")
        continue

    color_image = cv2.cvtColor(np.asanyarray(color_frame.get_data()), cv2.COLOR_BGR2RGB)
    results = model(color_image)

    print(type(color_image))
    print(color_image.shape)

    annotated_image = results[0].plot()
    
    cv2.namedWindow('Segmentation', cv2.WINDOW_AUTOSIZE)
    cv2.imshow('egmentation', annotated_image)
    if cv2.waitKSey(1) & 0xFF == ord('q'):
        break

finally:
    pipe.stop()
```

### Additional

Might need to have realsense hardware and pyrealsense installed, in case you want to exactly reproduce, but i don't think that is an issue here. 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by BhooshanDeshpande** [comment]
I think I figured the issue,   needed to upgrade my tensor-board version from 2.4.0 to the latest 2.13.0. This should have been taken care by the requirements, in my opinion, but had to do it manually for some reason. Is this an improvement in the `requirements.txt` ? Opening it for further discussion.

**Comment by glenn-jocher** [comment]
@BhooshanDeshpande glad to hear that you were able to resolve your issue by manually upgrading the tensor-board version! While the requirements.txt file should include compatible dependencies for YOLOv8, there can still be instances where manual upgrades or installations are necessary due to changes or updates in the dependencies. This is not an issue specific to YOLOv8 and can happen with any software that has dependencies. Nonetheless, we appreciate your feedback and are always looking for ways to improve our documentation and processes.

**Comment by Vinodkumar96188** [comment]
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by Vinodkumar96188** [comment]
No use of these commands , I updated:
pip install numpy==1.23.4
!pip install -r requirements.txt
!pip install ultralytics

**Comment by glenn-jocher** [comment]
@Vinodkumar96188 based on your command, you seem to want to train the yolov8n.pt model on your Mixeddata.yaml dataset for 300 epochs. 

Normally, to start training, you'd use `mode=train` and specify your data configuration, model configuration, the number of epochs, and whether you want plots with `plots=True`. The data configuration file (like Mixeddata.yaml) should be a YAML file that specifies your train, validation, and test datasets, number of classes, and class names.

The YOLO model specified (`yolov8n.pt`) should be a pretrained model if you want to do transfer learning, or it could be a model configuration file if you want to train from scratch.

It seems like you've included `task=detect` in your command, but this should only be used if you want to perform object detection on a set of images or videos, not for training.

So your command should look more like this: `!yolo mode=train model=yolov8n.pt data=Mixeddata.yaml epochs=300 plots=True`

Also, ensure that your Mixeddata.yaml file is correctly configured and that your environment meets all requirements for YOLOv8 training.

**Comment by Vinodkumar96188** [comment]
Respected sir

As you said I train but
Yolov8 and yolov6 not showing in the trained results and confusion matrix
and trained and valid images

After completion of trained process it only shows the Avg precision and
recal and mAP only

And also I tired evaluation camnad also but it only shows Avg precision and
recal and mAP only

How to see results image and result csv and confusion matrix like yolov5

As earlier I used to yolov8 with another dataset that time I seen as I
asked like confusion matrix that time also yolov6 not shows , now yolov8
same as yolov6 at stage of after training

Can you please provide information after training process, I want to see
confusion matrix for accuracy and results and p curve and recal curve and
pr curve

I hope you understand my problem

Please help
Thank you sir

**Comment by glenn-jocher** [comment]
@Vinodkumar96188 hi there,

It seems like you are having some trouble getting some expected results from your training process. In YOLOv8, the results that you see after completing your training, such as average precision, recall and mAP to name a few, are the standard results that the training process outputs.

A confusion matrix, on the other hand, is generally used in supervised learning algorithms to visualize the performance of the algorithm. As such, it is not a common part of the output for models in the YOLO family (which includes YOLOv8) after training, as they are object-detection models. 

As for the other curves like PR curve, recall curve etc, YOLOv8 currently may not support direct generation of these curves. The training process in YOLO mainly focuses on improving the model accuracy and other parameters using given data.

If you have worked with YOLOv8 on another dataset and seen these output before, could there be a chance that there might be custom scripts or modifications implemented to produce those outputs? 

I hope this response clarifies things a little. We are always here to provide more support if needed!
