### ISSUE TITLE
YOLOV8(8.0.99) didn't load the model trained at 8.0.53, even I upgraded to the latest version 

### ISSUE THREAD

**Issue by AI-Passionner** [ultralytics/ultralytics#2587]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Thanks to the Ultralytics team. YOLOV8 is great!!!

However, I got an issue. 
1. I trained the yolov8 on my data in MAC M1 and it worked. I checked the version (8.0.53). 
2. Later on, I trained a new model at AWS SageMaker (Linux) with the latest version (I believe it is 8.0.99). It worked. 
3. The latest version can load the model trained with the version 8.0.53. But it didn't work via verse. 
4. I did research on this issue. It seems a version issue. However, I created a new virtual environment and install the requirements.txt and the latest ultralytics. It still doesn't work. I checked the version, it shows some sort of inconsistency 

<img width="408" alt="image" src="https://github.com/ultralytics/ultralytics/assets/65562616/b0bef368-1e46-46d9-b2c5-4461b2d055b0">

5. I guess it would be the virtual environment issue. but I am not sure if it is right. 

=========================
WARNING ⚠️ /Users/xxx/Downloads/xxx.pt appears to require 'ultralytics.nn.modules.conv', which is not in ultralytics requirements.
AutoInstall will run now for 'ultralytics.nn.modules.conv' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
requirements: YOLOv8 requirement "ultralytics.nn.modules.conv" not found, attempting AutoUpdate...
ERROR: Could not find a version that satisfies the requirement ultralytics.nn.modules.conv (from versions: none)
ERROR: No matching distribution found for ultralytics.nn.modules.conv
requirements: ❌ Command 'pip install "ultralytics.nn.modules.conv"  ' returned non-zero exit status 1.

ModuleNotFoundError: No module named 'ultralytics.nn.modules.conv'; 'ultralytics.nn.modules' is not a package

### Environment

-python 3.9
-ultralytics, 8.0.53 and 8.0.99

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AI-Passionner** [comment]
Figure out. It is my bad. I used the repository code to train the model and load model. It works for API. thanks.

**Comment by glenn-jocher** [comment]
@AI-Passionner glad to hear that your issue has been resolved! If you have any other queries or issues, feel free to ask. Thank you for using YOLOv8!
