### ISSUE TITLE
Poor Segmentation - Label Generation based off Masks.

### ISSUE THREAD

**Issue by aw-wenntech** [ultralytics/ultralytics#2592]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! I am attempting to tune a segmentation model and having weird results. I think this is coming from the generation of my labels.txt files... I have referenced some other issues in the repo related but was unable to come up with anything. 

Moreover, I have RGB images and Binary mask images. Provided below is the code I am using to generate my labels files. Also, the train batch jpegs. It just looks like there is some weirdness and I am betting that it is the way I am labelling this segmentation task. New to segmentation so any thoughts or feedback would be appreciated. Thanks!

**Label Generation based off masks:**
```python
import os
import cv2
import numpy as np
from imantics import Image as ImanticsImage
import matplotlib.pyplot as plt

# Set the directory paths for the images and labels
image_directory = 'yolo/valid/images/'
label_directory = 'yolo/labels_images_train/'

# Get the list of image and label filenames
image_filenames = os.listdir(image_directory)
label_filenames = os.listdir(label_directory)

# Define a threshold (assuming white pixels have a value of 255 in your binary image)
threshold = 254

# Set the class index for the "road" class
class_index = 0

# Iterate over the image files
for image_filename in image_filenames:
    try:
        # Check if the corresponding label file exists
        if image_filename in label_filenames:
            # Load the color image
            color_img = cv2.imread(os.path.join(image_directory, image_filename))

            # Load the binary image
            binary_img = cv2.imread(os.path.join(label_directory, image_filename))

            # Convert binary image to grayscale
            binary_img = cv2.cvtColor(binary_img, cv2.COLOR_BGR2GRAY)

            # Get the indices of the white pixels
            white_pixels = np.where(binary_img > threshold)

            # Check if both images have the same size
            if binary_img.shape != color_img.shape[:2]:
                print("Images do not have the same dimensions.")
                continue

            # Overlay the white pixels on the original image in lime green
            color_img[white_pixels] = [0, 255, 0]

            fig, ax2 = plt.subplots()
            ax2.imshow(color_img)
            plt.show()

            # Normalize the coordinates to the range [0, 1]
            normalized_coordinates = []
            for point in zip(*white_pixels):
                x = point[1] / color_img.shape[1]
                y = point[0] / color_img.shape[0]
                normalized_coordinates.append((x, y))

            # Create a new label file for each image
            label_file_path = os.path.join('yolo/valid/labels', f'{os.path.splitext(image_filename)[0]}.txt')

            with open(label_file_path, 'w') as label_file:
                # Write the class index to the label file
                label_file.write(str(class_index))
                label_file.write(' ')
                # Write the normalized coordinates to the label file
                for point in normalized_coordinates:
                    label_file.write(' '.join(map(str, point)))
                    label_file.write(' ')
                label_file.write('\n')
        else:
            print(f"No label found for image {image_filename}.")
    except:
        print(f"{image_filename} skipped.")
```
**Example byproduct of script:**
![download](https://github.com/ultralytics/ultralytics/assets/122185103/9f8e81dd-a5f3-4d05-8a9d-b1b58aa8a072)

**Example batch jpgs**
![download](https://github.com/ultralytics/ultralytics/assets/122185103/14ae32a1-3f44-49bf-8efb-caa2fe341f0b)

I am yet to finish a training job but a little skeptical that anything worth value is going to get produced... any thoughts welcome. Thanks!

**Comment by aw-wenntech** [comment]
I will add - my images are (1500,1500). I have specified this in the training params but I guess not positive if this is supported. Thanks!

**Comment by glenn-jocher** [comment]
@aw-wenntech hi! Thank you for reaching out. It's great to see that you're working on a segmentation task with YOLOv8. Regarding the size of your images, YOLOv8 technically doesn't have a specific limit for the input image size, but very large images may not fit into memory on your specific hardware and may cause issues. However, you mentioned that your images have a size of (1500, 1500), which should be manageable for most modern hardware. 

As for your label generation script, it looks like you're processing your binary mask image correctly and generating the corresponding label files with normalized coordinates. However, if you have any doubts about the correctness of your labels, I would suggest verifying them manually, e.g. by overlaying them on your original image and visually checking if they correspond to the location of the object you want to segment.

Good luck with your training, and let us know if you have any other questions or issues!

**Comment by aw-wenntech** [comment]
@glenn-jocher thanks for the reply!

Good to know about image sizes. So that is not my issue.

Also glad to hear these labels appear to be in the correct format! 

Let me ask this, does the train batch jpg provided look weird to you? When I was doing the training jobs I was doing them with only a few epochs just to ensure the labels were in the correct format. I guess I'm not sure _what_ to expect necessarily. Maybe it's worth upping the epochs and just letting it train and see what happens? Thanks!

**Comment by aw-wenntech** [comment]
After overlaying my labels on top of my RGB images, it does look funky. Almost seems this is occurring because of normalization and denormalization. I am not sure what to do about this to be honest.  Any thoughts would be appreciated: 

Labels overlaid on RGB
![download](https://github.com/ultralytics/ultralytics/assets/122185103/2543907b-9f4f-4c9a-801d-652283852eda)

Actual Mask overlaid on RGB
![download](https://github.com/ultralytics/ultralytics/assets/122185103/cc1e97b6-d2bf-4467-906c-937f23e5492d)

**Comment by glenn-jocher** [comment]
@aw-wenntech Hello! Based on the two images you provided -- the labels overlay and the actual mask overlay -- it seems that there may be some discrepancy between the normalized label coordinates and the original image coordinates. This could be due to a few factors, such as using the wrong height and width values for normalization, or a mismatch in aspect ratio.

To resolve this, I recommend double-checking the normalization code you're using to ensure that you are correctly taking into account the image dimensions when normalizing your coordinates. Additionally, it's worth verifying that your label images have the same aspect ratio as your RGB images. If not, you may need to resize your label images to match.

Another thing to consider is that YOLOv8 uses a grid-based approach, where each cell in a grid corresponds to a potential object detection or segmentation bounding box. It's possible that the grid setup may not be ideal for your specific task, and you may need to adjust the grid size or use a different approach entirely.

I hope that helps! Let us know if you have any other questions or concerns.
