### ISSUE TITLE
Yolov8 Dataset configuration for multilabel classification

### ISSUE THREAD

**Issue by developer-119** [ultralytics/ultralytics#2595]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

prepare a dataset for multi label classification in yolov8 like this:
```
dataset:
       train:
            A:
             a-1.jpg
             a-1.xml
            B:
             b-1.jpg
             b-2.xml
       valid:
            A:
             a-2.jpg
             a-2.xml
            B:
             b-2.jpg
             b-2.xml
       test:
            A:
             a-3.jpg
             a-3.xml
            B:
             b-3.jpg
             b-3.xml
```

and custom.yaml like this:
```
path:  dataset
train: /dataset/train
test: /dataset/test
valid: /dataset/valid

#Classes
nc: 28

#classes names
names: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', ...]
```

but i got error when run train command(for multi-label i cant find a documentation for prepare custom dataset)
SyntaxError: /dataset/custom.yaml 'val:' key missing ❌.
'train', 'val' and 'names' are required in data.yaml files.

**Comment by Burhan-Q** [comment]
The YAML file isn't needed if you're only doing classification (not object detection). Just pass the top-level directory of your classification dataset with train and valid directories and images for each class in sub-directories with class names.

If you're performing object detection, then you need to restructure your directory. See the Ultralytics Docs on specifics, but it should follow
data
   train/labels/*.txt
   train/images/*.png (or whatever image format you're using)
   valid/labels/*.txt
   valid/images/*.png

**Comment by glenn-jocher** [comment]
@Burhan-Q hello! If you are only doing classification, you don't need the `custom.yaml` file in your dataset. Instead, you can pass the top-level directory of your classification dataset with train and validation directories containing images for each class in sub-directories with the class name. 

On the other hand, if you are performing object detection, the directory structure should follow this format:
```/data
    /train/labels/*.txt
    /train/images/*.jpg
    /valid/labels/*.txt
    /valid/images/*.jpg
```
For more specific details, please check [Ultralytics Docs](https://docs.ultralytics.com). Let me know if this helps!
