### ISSUE TITLE
Data Augmentation - Rain

### ISSUE THREAD

**Issue by Vikram12301** [ultralytics/ultralytics#2596]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would like to include the [rain augmentation](class albumentations.augmentations.transforms.RandomRain) from albumentation

**Comment by Hommoner** [comment]
@Vikram12301 

you can add/modify albumentations in

ultralytics\ultralytics\yolo\data\augment.py

```
class Albumentations:
    # YOLOv8 Albumentations class (optional, only used if package is installed)
    def __init__(self, p=1.0):
        """Initialize the transform object for YOLO bbox formatted params."""
        self.p = p
        self.transform = None
        prefix = colorstr('albumentations: ')
        try:
            import albumentations as A

            check_version(A.__version__, '1.0.3', hard=True)  # version requirement

            T = [
                A.Blur(p=0.01),
                A.MedianBlur(p=0.01),
                A.ToGray(p=0.01),
                A.CLAHE(p=0.01),
                A.RandomBrightnessContrast(p=0.05),
                A.RandomGamma(p=0.0),
                A.ImageCompression(quality_lower=75, p=0.0)]  # transforms
            self.transform = A.Compose(T, bbox_params=A.BboxParams(format='yolo', label_fields=['class_labels']))
            LOGGER.info(prefix + ', '.join(f'{x}'.replace('always_apply=False, ', '') for x in T if x.p))
        except ImportError:  # package not installed, skip
            pass
        except Exception as e:
            LOGGER.info(f'{prefix}{e}')
```

**Comment by glenn-jocher** [comment]
Dear @Hommoner, to add the `rain` augmentation from Albumentations you could modify the `Albumentations` class in `ultralytics\ultralytics\yolo\data\augment.py` file. Inside the class, you can add the `class albumentations.augmentations.transforms.RandomRain` and adjust its probability accordingly to your needs using the `p` parameter. Don't forget to import this class from the `albumentations` package at the beginning of the file.

Please note that the Albumentations package is optional and needs to be installed separately. You can install it using `pip install albumentations`. 

I hope this helps! Let me know if you have any further questions.
