### ISSUE TITLE
How can I display the probability of each class in one bounding box when I predict?

### ISSUE THREAD

**Issue by ue17** [ultralytics/ultralytics#2600]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

During the forecast, one bounding box displays the determined class and confidence level.
The results are displayed as follows (for 5 classes).

"""
ultralytics.yolo.engine.results.Boxes object with attributes:

boxes: tensor([[2.2937e+02, 7.2819e+01, 6.9486e+02, 5.7075e+02, 3.2637e-01, 3.0000e+00]])
cls: tensor([3.])
conf: tensor([0.3264])
data: tensor([[2.2937e+02, 7.2819e+01, 6.9486e+02, 5.7075e+02, 3.2637e-01, 3.0000e+00]])
id: None
is_track: False
orig_shape: tensor([651, 861])
shape: torch.Size([1, 6])
xywh: tensor([[462.1165, 321.7848, 465.4899, 497.9325]])
xywhn: tensor([[0.5367, 0.4943, 0.5406, 0.7649]])
xyxy: tensor([[229.3716,  72.8185, 694.8615, 570.7510]])
xyxyn: tensor([[0.2664, 0.1119, 0.8070, 0.8767]])
"""

However, we would like to display not only one class and its confidence level, but also undetermined classes and their confidence levels. For example
Cat in: 50%.
Dogs: 20%.
Cars: 30%.

What kind of program should I make to get this kind of output?

**Comment by eiyike123** [comment]
I am also interested in the probability but when i use result.probs the result is always displaying none

**Comment by glenn-jocher** [comment]
@eiyike123 hello! To access the class probabilities for each bounding box, you can use the `result.xyxyn` tensor that contains the coordinates of each detection along with the class probability scores, ordered by the class index. Then, you can use indexing to select the desired class probability value from the tensor. For example, to get the probability value for the class with index 3 (assuming 0-based indexing), you can use `result.xyxyn[..., 5]`. Note that the `result.probs` attribute is not used in YOLOv8, so it will always return `None`.

**Comment by eiyike123** [comment]
Is the tensor going to display class id, x1, y1, x2, y2, confidence and class probability

**Comment by eiyike123** [comment]
> @eiyike123 hello! To access the class probabilities for each bounding box, you can use the `result.xyxyn` tensor that contains the coordinates of each detection along with the class probability scores, ordered by the class index. Then, you can use indexing to select the desired class probability value from the tensor. For example, to get the probability value for the class with index 3 (assuming 0-based indexing), you can use `result.xyxyn[..., 5]`. Note that the `result.probs` attribute is not used in YOLOv8, so it will always return `None`.

What if I have multiple images. Is there a way to do it.

**Comment by glenn-jocher** [comment]
@eiyike123 Yes, you can loop through the `result` object for each image and access the `result.xyxyn` tensor to get the class probabilities for each bounding box. For example, suppose you have a list of `result` objects for multiple images named `results`. Then, you can loop through the list and for each `result` object, you can access the `result.xyxyn[..., 5]` tensor to get the probability value for the desired class. You can store these probability values in a list or a dictionary for further processing. Let me know if you have any other questions!

**Comment by Dharmendra04** [comment]
is there any way to create a pixel wise probability map for the predicted image. or is there any way to get the pixel wise probability?

**Comment by ue17** [comment]
@glenn-jocher 
I can't execute result.xyxyn[..., 5]. How can I make it work?

Also, in result.boxes, there are only four tensors in xyxyn. Could you enlighten me on this?

**Comment by eiyike123** [comment]
> @glenn-jocher I can't execute result.xyxyn[..., 5]. How can I make it work?
> 
> Also, in result.boxes, there are only four tensors in xyxyn. Could you enlighten me on this?

X1,y1,x2,y2. Which is the bounding box top-left and bottom-right

**Comment by ue17** [comment]
> @eiyike123 Yes, you can loop through the `result` object for each image and access the `result.xyxyn` tensor to get the class probabilities for each bounding box. For example, suppose you have a list of `result` objects for multiple images named `results`. Then, you can loop through the list and for each `result` object, you can access the `result.xyxyn[..., 5]` tensor to get the probability value for the desired class. You can store these probability values in a list or a dictionary for further processing. Let me know if you have any other questions!

sorry. 
How can the above class establishment be implemented?
result.xyxyn[..., 5] cannot be executed.

**Comment by glenn-jocher** [comment]
@Dharmendra04 I'm sorry if my previous answer was unclear. To access the class probabilities for each bounding box, you need to first access the `result.xyxyn` tensor, which contains the coordinates of each detection along with the class probability scores, ordered by the class index. The `[..., 5]` notation is used to index the tensor along the last dimension (the class probability scores) to select the desired value. However, this notation can only be used in combination with a tensor object in Python.

To access the `result.xyxyn` tensor, you need to use a `for` loop over the `result` object for each image, as I mentioned earlier. Here is an example code snippet that demonstrates how to get the class probability values for each bounding box in each image:

```
# Suppose you have a list of `result` objects for multiple images named `results`.
# Then, you can loop through the list and for each `result` object, 
# you can access the `result.xyxyn` tensor to get the class probabilities for each bounding box. 

for result in results:
    class_probs = result.xyxyn[:, 5]  # get the class probability values for all bounding boxes in the image
    # do something with the class probability values, such as store them in a list or a dictionary
```

In this code snippet, `result.xyxyn[:, 5]` is used to extract the class probability values along the last dimension (dimension index 5) for all bounding boxes in the image represented by the `result` object. Note that `result.xyxyn` is a tensor object, which is why the `[..., 5]` notation cannot be used directly with it in Python.

**Comment by Dharmendra04** [comment]
from ultralytics import YOLO
from ultralytics.yolo.v8.detect.predict import DetectionPredictor

import cv2

model = YOLO('best_140.pt')

prediction = model.predict(source ='/home/dharmendra/Desktop/Ash_dieback' ,show=True)

from ultralytics.yolo.engine import results as results
for result in results:
	class_prob = result.xyxyn[:,5]  # cls prob, (num_class, )

print(class_prob)

I am trying this code , but i couldnt get the probability map, the error message saying a error message like this

  for result in results:
TypeError: 'module' object is not iterable

**Comment by Dharmendra04** [comment]
I have tried a different code 

from ultralytics import YOLO
from ultralytics.yolo.v8.detect.predict import DetectionPredictor

import cv2

model = YOLO('best_140.pt')

results = model.predict(source ='/home/dharmendra/Desktop/Ash_dieback' ,show=True)

for r in results:
	boxes = r.boxes
	
	for box in boxes:
		class_prob = box.xyxyn[:]
		print(class_prob)
		print(class_prob.shape)

But here I only getting the coordinates of the bounding boxes, which means class_prob.shape is [1,4] it doesnt have 5 dimension, in your earlier message you mentioned something like [: ,5] , what that means. and hence this xyxyn is only giving a bounding box not the probability class. please clarify this

**Comment by glenn-jocher** [comment]
@ue17 hello! I apologize for the confusion earlier. To access the class probabilities for each bounding box, you can use the `result.xyxyn` tensor that contains the coordinates of each detection along with the class probability scores. The `[..., 5]` notation is used to index the tensor along the last dimension (the class probability scores) to select the desired value. 

In your code example, you are accessing `box.xyxyn`, which only contains the coordinates of the bounding boxes and not the class probabilities. To get the class probabilities for each bounding box, you can access `r.xyxyn`. The `r.xyxyn` tensor has the dimensions `(num_boxes, num_params)`, where each row represents a bounding box and the last dimension contains the class probability scores. Hence, you can use indexing as `r.xyxyn[:, 5]` to get the class probability values for all bounding boxes in the image represented by the `result` object.

I hope this helps clarify how to access the class probabilities for each bounding box. Let me know if you have any other questions!

**Comment by ue17** [comment]
@glenn-jocher Thank you for your response.
I am very sorry that my understanding has not caught up with you.
For example, if I predict one image and run result.xyxyn, I get the following error

```
model = YOLO('best.pt')
result = model(source='image.jpg')
result.xyxyn[:, 5]
```

```
AttributeError: 'Results' object has no attribute 'xyxyn'. See valid attributes below.
```

The same error occurs when multiple images are used.
I am using a model trained with the latest version (8.0.112) to perform inference.

**Comment by glenn-jocher** [comment]
@ue17 Hello! I apologize for the confusion in my previous message. It looks like the `result.xyxyn` attribute is not available in the `Results` object for YOLOv8. Instead, you can access the class probability values in the `result.conf` attribute. The `result.conf` attribute is a tensor object that contains the confidence scores for each detection in the image, ordered by the detection index. To get the class probabilities for each bounding box, you need to multiply the confidence scores by the class probabilities. 

To do this, you can access the `result.pred` attribute, which is a tensor object that contains the predicted class scores and bounding box coordinates for each detection, ordered by the detection index. The `result.pred` tensor has the dimensions `(num_detections, num_params)` where `num_params` includes the class scores (indexed from 5 to the end) and the bounding box coordinates. You can use `result.pred[:, 5:]` to select the class scores for each detection in the image. 

Then, you can multiply the class scores by the confidence scores to get the class probability values. Note that the class scores are represented as logits, so you need to apply the softmax function to convert them to probability values. You can use the `torch.softmax` function to apply softmax to each row of the `result.pred[:, 5:]` tensor. Finally, you can multiply the softmax scores with the confidence scores to get the class probability values for each detection. 

I hope this helps! Let me know if you have any further questions.

**Comment by ue17** [comment]
@glenn-jocher Sorry for the repeated questions.
I ran .pred against the result.

```
model = YOLO('best.pt')
result = model(source='image.jpg')
result.pred[:, 5:]
```
Then I get the following error
```
AttributeError: 'Results' object has no attribute 'pred'. See valid attributes below.

    A class for storing and manipulating inference results.

    Args:
        orig_img (numpy.ndarray): The original image as a numpy array.
        path (str): The path to the image file.
        names (dict): A dictionary of class names.
        boxes (List[List[float]], optional): A list of bounding box coordinates for each detection.
        masks (numpy.ndarray, optional): A 3D numpy array of detection masks, where each mask is a binary image.
        probs (numpy.ndarray, optional): A 2D numpy array of detection probabilities for each class.
        keypoints (List[List[float]], optional): A list of detected keypoints for each object.


    Attributes:
        orig_img (numpy.ndarray): The original image as a numpy array.
        orig_shape (tuple): The original image shape in (height, width) format.
        boxes (Boxes, optional): A Boxes object containing the detection bounding boxes.
        masks (Masks, optional): A Masks object containing the detection masks.
        probs (numpy.ndarray, optional): A 2D numpy array of detection probabilities for each class.
        names (dict): A dictionary of class names.
        path (str): The path to the image file.
        keypoints (List[List[float]], optional): A list of detected keypoints for each object.
        speed (dict): A dictionary of preprocess, inference and postprocess speeds in milliseconds per image.
        _keys (tuple): A tuple of attribute names for non-empty attributes.
```

Is it not possible to get the establishment of each class out of one bounding box?

**Comment by glenn-jocher** [comment]
@Dharmendra04 hello! I apologize for the confusion in my previous message. It looks like the `result.pred` attribute is not available in the `Results` object for YOLOv8. Instead, you can access the bounding box coordinates and class probability values separately. 

To get the bounding box coordinates, you can access the `result.xyxy` attribute, which is a tensor object that contains the coordinates of each detection in the image, ordered by the detection index as (xmin, ymin, xmax, ymax).

To get the class probability values for each detection, you can access the `result.get_field('scores')` attribute, which is a tensor object that contains the class scores for each detection in the image, ordered by the detection index. Note that these are represented as logits, so you need to apply the softmax function to convert them to probability values.

To associate the class probability values with their respective bounding boxes, you need to loop through the detections and multiply the softmax scores with the confidence scores to get the class probability values for each detection. 

I hope this helps clarify how to access the bounding box coordinates and class probability values separately in YOLOv8. Let me know if you have any further questions.

**Comment by Daheer** [comment]
> @eiyike123 hello! To access the class probabilities for each bounding box, you can use the `result.xyxyn` tensor that contains the coordinates of each detection along with the class probability scores, ordered by the class index. Then, you can use indexing to select the desired class probability value from the tensor. For example, to get the probability value for the class with index 3 (assuming 0-based indexing), you can use `result.xyxyn[..., 5]`. Note that the `result.probs` attribute is not used in YOLOv8, so it will always return `None`.

result.xyxyn is still 4-dimensional. The 'n' at the end stands for normalized, so you're still going to get the bounding box co-ordinates but normalized to be between 0 and 1.

**Comment by glenn-jocher** [comment]
@Daheer hello! I apologize for the confusion in my previous message. The `result.xyxyn` attribute in YOLOv8 contains the`(x, y, w, h, objectness, class_prob)` values for each detection in the image, not just the normalized bounding box coordinates. To access the class probability values for each bounding box, you can use `result.xyxyn[..., 5]`, as you mentioned previously. 

I hope this helps to clarify how to access the class probability values in YOLOv8. Let me know if you have any further questions or concerns.

**Comment by ABeltramo** [comment]
No, `result.xyxyn` doesn't contain `(x, y, w, h, objectness, class_prob)` as even [your docs](https://docs.ultralytics.com/modes/predict/#boxes) correctly reports: 
> boxes.xyxyn  # box with xyxy format but normalized, (N, 4)

Please **stop blindly using ChatGPT** to generate messages and **verify the code before replying**.

**Comment by eiyike123** [comment]
> No, `result.xyxyn` doesn't contain `(x, y, w, h, objectness, class_prob)` as even [your docs](https://docs.ultralytics.com/modes/predict/#boxes) correctly reports:
> 
> > boxes.xyxyn  # box with xyxy format but normalized, (N, 4)
> 
> Please **stop blindly using ChatGPT** to generate messages and **verify the code before replying**.

Please can you clarify how class prob can be obtain. I just decided to use the normalized class confidence in place of prob

**Comment by eiyike123** [comment]
> > No, `result.xyxyn` doesn't contain `(x, y, w, h, objectness, class_prob)` as even [your docs](https://docs.ultralytics.com/modes/predict/#boxes) correctly reports:
> > > boxes.xyxyn  # box with xyxy format but normalized, (N, 4)
> > 
> > 
> > Please **stop blindly using ChatGPT** to generate messages and **verify the code before replying**.
> 
> Please can you clarify how class prob can be obtain. I just decided to use the normalized class confidence in place of prob

I don’t think yolo v8 have the attributes of prob as shown in the document

**Comment by glenn-jocher** [comment]
@ABeltramo i apologize for any confusion caused. In YOLOv8, the `Results` object doesn't have a specific attribute for class probabilities (`probs`). Instead, you can access the class confidence scores provided by the model. These scores represent the probability of each detection belonging to a specific class. Please note that these confidence scores are in a raw, unnormalized form (logits), and they are not directly converted to class probabilities. You can use these confidence scores to perform further analysis or apply appropriate post-processing techniques to obtain class probabilities if needed.

I hope this clarifies the situation. If you have any further questions, please let me know.

**Comment by tomer-grin** [comment]
> @ABeltramo i apologize for any confusion caused. In YOLOv8, the `Results` object doesn't have a specific attribute for class probabilities (`probs`). Instead, you can access the class confidence scores provided by the model. These scores represent the probability of each detection belonging to a specific class. Please note that these confidence scores are in a raw, unnormalized form (logits), and they are not directly converted to class probabilities. You can use these confidence scores to perform further analysis or apply appropriate post-processing techniques to obtain class probabilities if needed.
> 
> I hope this clarifies the situation. If you have any further questions, please let me know.

Thanks for the super helpful replies?
Do you have an answer dor @Dharmendra04 question regarding the per pixrl probability map?
Even a helpful resource to point out would be great.

**Comment by glenn-jocher** [comment]
@tomer-grin i understand you are looking for a per-pixel probability map for each class in your image. While YOLOv8 directly does not output such maps, they can be derived from the model's architecture and corresponding output layers. 

In YOLOv8, the detection process is performed at multiple scales, each corresponding to a different feature map with varying spatial resolution. These maps are used to predict the bounding boxes and associated class confidence scores, they however don't directly provide a per-pixel probability map for each class as you described.

The desired per-pixel class probabilities would require a pixel-wise classification which is often associated with tasks like semantic segmentation, rather than object detection which YOLOv8 is optimized for. So while it's theoretically possible to adapt the architecture to provide class probabilities at the pixel level, it would involve significant modifications to the model, and may not necessarily achieve the best results without careful design and training.

For tasks that require per-pixel class predictions, you might want to consider models specifically designed for semantic segmentation, as they naturally output a probability map for each class at every single pixel. These models can offer the output you're looking for but come with their own set of considerations and trade-offs.

**Comment by Z30G0D** [comment]
@glenn-jocher Thank you,
if not class probabilities at the pixel level, can I get it for the cell level?
Something like this:
![image](https://github.com/ultralytics/ultralytics/assets/33577556/b387942e-ca43-4ef2-b7b1-70ac534e4986)

**Comment by glenn-jocher** [comment]
@Z30G0D hello, thank you for your question. In short, the probability per cell behavior you described is a specific feature of how YOLO handles the detection process internally. 

YOLO splits the input image into a grid of cells, and each cell predicts `n` bounding boxes and class probabilities. However, these "cell level probabilities" are used within the model to define bounding boxes and make class predictions, and are not directly accessible in the output. 

The output of YOLOv8 provides predictions in the form of bounding boxes, each associated with a class and a confidence score. The confidence score gives the probability that a bounding box contains an object, multiplied by how accurate the model thinks the box is.

If you wanted to access the cell level probabilities or feature maps, you would need to modify the model to expose these intermediate values. Please keep in mind that it requires deep understanding of the model architecture and object detection mechanism to interpret these feature maps correctly. 

Remember also that these values are not comparable to the per-pixel or cell-level probabilities produced by a segmentation model, as they are part of a different mechanism within the YOLO model architecture to identify and localize objects within an image.

**Comment by TeenaJO** [comment]
Hey @glenn-jocher 
So yolov8 detection models gives the coordinates of the  bounding boxes right ..Now my images are captured from a camera on a multirotor and its giving me the xy coordinates of my bounding box,So i have to perform localisation (find the real coordinates of the targets) .Now my logic is we can find the pixel coordinates of the targets centre and measure the distance between the centre of the target and the centre of the image  captured by the UAV from the camera and multiply it with the GSD of the camera.So is the bounding box coordinates accurate with respect to the image

**Comment by glenn-jocher** [comment]
@TeenaJO hey there!

Yes, the YOLOv8 detection model provides the coordinates of the bounding boxes. These box coordinates are relative to the input image and represent the location of detected object in the frame. 

The coordinates provided by the model are designed to be as accurate as possible, but the exact precision can depend on many factors, such as the size of the object in the image, the image resolution, the quality of the training data, and the specific hyperparameters used to train the model.

Using the approach you described to estimate real world coordinates from pixel coordinates can be applicable, but remember that the accuracy of your localization highly depends on how precise the bounding box coordinates are and the exactness of your GSD (Ground Sample Distance) value.

Keep in mind, this kind of localization is subject to various types of errors. For example, the GSD assumes a flat Earth which might introduce errors if you're dealing with terrain undulation. Also, the pitch and roll of the UAV camera, the lens distortion, and the altitude variations can introduce more errors.

While the model tries to deliver the most accurate predictions, you have to take these considerations into account when using the bounding box coordinates for real-world localization.

**Comment by dbjorklund** [comment]
@ue17 Hi! Did you find a solution for your original question generating the class output probabilities for each class?

**Comment by HamidRezaHeidari** [comment]
you should use prob function:

conf =  [ ]

for box in boxes:
    prob = np.array(box.conf)
    conf.append(prob)

print(prob)

**Comment by glenn-jocher** [comment]
Thank you for your suggestion! While the `conf` attribute provides the confidence scores for each bounding box in YOLOv8, it doesn't directly give class probabilities for all classes. If class probabilities are needed, they can be accessed via the `probs` attribute if available, or derived from the model's raw outputs during custom implementation. Let me know if you need further clarification!
