### ISSUE TITLE
How many pictures should be used in the test?

### ISSUE THREAD

**Issue by 7assanx7** [ultralytics/ultralytics#2613]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i want to train model on 100 image so how many images should be used from 100 ?
i take 30% from train data for test do i have to make train data 100 and test data 30 or train data 70 and test 30 ?

**Comment by glenn-jocher** [comment]
@7assanx7 thanks for your question. As a rule of thumb, it is recommended to use at least 10-20% of your total dataset for testing and validation. This means that you should use around 10-20 images from your 100 images dataset as a test set. As for the split between train and test data, it's up to you to decide based on your specific use case and dataset characteristics. However, a common split for smaller datasets is 80% for training and 20% for testing. I hope that helps!

**Comment by 7assanx7** [comment]
ok,thanks for your help

**Comment by 7assanx7** [comment]
> @7assanx7 thanks for your question. As a rule of thumb, it is recommended to use at least 10-20% of your total dataset for testing and validation. This means that you should use around 10-20 images from your 100 images dataset as a test set. As for the split between train and test data, it's up to you to decide based on your specific use case and dataset characteristics. However, a common split for smaller datasets is 80% for training and 20% for testing. I hope that helps!


ok,thanks for your help

**Comment by glenn-jocher** [comment]
You're welcome @7assanx7! If you have any further questions or issues, feel free to ask. We're always here to help and support the YOLOv8 community.
