### ISSUE TITLE
[Question]Script to use multiple camera streams as source

### ISSUE THREAD

**Issue by mriamnobody** [ultralytics/ultralytics#2615]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I wrote a small script in Python with the help of a member in Discord and chatGPT to access multiple camera streams and perform detection. The issue with this script is that I have provided it with 5 camera streams but it displays and processes only 4 streams and over time the number of camera streams drops to 2.

```
import cv2
import time
import queue
import concurrent.futures
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('yolov8l.pt')

rtsp_urls = []

# Create a queue for each camera
frame_queues = [queue.Queue(maxsize=10) for _ in rtsp_urls]

# Function to connect to an IP camera and push frames to the queue
def capture_camera_frames(url, frame_queue):
    cap = cv2.VideoCapture()
    while True:
        cap.open(url)
        if cap.isOpened():
            print(f"Connection successful!")
            while True:
                ret, frame = cap.read()
                if ret:
                    if not frame_queue.full():
                        frame_queue.put(frame)
                else:
                    print("Failed to retrieve frame, reconnecting...")
                    break
            cap.release()
        else:
            print("Connection failed, retrying...")
            time.sleep(5)

# Function to display frames from the queue
def display_frames(frame_queue, i):
    while True:
        if not frame_queue.empty():
            frame = frame_queue.get()

            # Run YOLOv8 inference on the frame
            results = model.predict(frame,  conf=0.5, classes=0)

            # Visualize the results on the frame
            annotated_frame = results[0].plot()

            cv2.imshow(f'IP Camera Stream {i+1}', annotated_frame)
            if cv2.waitKey(1) & 0xFF == 27:
                break

# Start a thread pool executor
with concurrent.futures.ThreadPoolExecutor(max_workers=len(rtsp_urls)*2) as executor:
    # Start a thread for each camera to capture frames
    for i, url in enumerate(rtsp_urls):
        executor.submit(capture_camera_frames, url, frame_queues[i])
    # Start another thread for each camera to display frames
    for i, _ in enumerate(rtsp_urls):
        executor.submit(display_frames, frame_queues[i], i)

cv2.destroyAllWindows()
```

**Comment by glenn-jocher** [comment]
@mriamnobody hello! Thank you for reaching out. It sounds like you're trying to use multiple camera streams as a source for detection using YOLOv8. One issue you're experiencing is that only 4 out of the 5 streams are being displayed and processed, and over time the number of camera streams gets lower. 

I would suggest looking into the maximum number of connections that can be sustained by your system's hardware. There may be a limit to how many camera streams can be processed at once, causing a drop in the number of connected streams over time. Additionally, you may want to try increasing the number of threads handling the streams to see if that improves performance. 

Let me know if you have any further questions!
