### ISSUE TITLE
Change Color Space of image from RGB to YCbCr for object detection

### ISSUE THREAD

**Issue by Adi11cr7** [ultralytics/ultralytics#2619]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to detect fire in images, and wanted to change the color space of the input image from RGB to YCbCr. Would it be okay to feed YCbCr color model images as input since the model expects RGB.

**Comment by coolst3r** [comment]
> ### Search before asking
> 
>     * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> 
> ### Question
> 
> I am trying to detect fire in images, and wanted to change the color space of the input image from RGB to YCbCr. Would it be okay to feed YCbCr color model images as input since the model expects RGB.
> ### Additional
> 
> _No response_

test it wont hurt to try
