### ISSUE TITLE
Is yolov8 finetuning the full pretrained model or only the last layers?

### ISSUE THREAD

**Issue by ChrisRawstone** [ultralytics/ultralytics#2627]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi I am looking at the source code and I have a hard time figuring out if yolov8 is training all the layers of the pretrained model or only the last few layers?

Best regards
Christian

**Comment by ExtReMLapin** [comment]
You can use freeze param to freeze the backbone for example

**Comment by glenn-jocher** [comment]
@ChrisRawstone you are correct, there isn't a `freeze` parameter in YOLOv8. However, to freeze the backbone, you just need to set the `requires_grad` attribute of the backbone's parameters to `False`.

**Comment by kvnptl** [comment]
Is it going to be added as an argument? similar [YOLOv5 freeze argument](https://github.com/ultralytics/yolov5/blob/5eb7f7ddc034b9ad07578a6f954c58170579ebc6/train.py#LL469C8-L469C8)

**Comment by glenn-jocher** [comment]
@kvnptl thanks for your question regarding a potential `freeze` argument in YOLOv8. At the moment, there are no plans to add a `freeze` argument to YOLOv8. However, to freeze the backbone layers, you just need to set their `requires_grad` attribute to `False`. Hope this helps!

**Comment by SonwYang** [comment]
@kvnptl hello, bro!!!You can refer to this.Here is my implementation.
`from ultralytics import YOLO
import torch


class FinetuneYolo(YOLO):
    def load_backbone(self, ckptPath):
        """
        Transfers backbone parameters with matching names and shapes from 'weights' to model.
        """
        backboneWeights = torch.load(ckptPath)
        self.model.load_state_dict(backboneWeights, strict=False)
        return self
    
    def freeze_backbone(self, freeze):
        # Freeze backbone params
        freeze = [f'model.{x}.' for x in  range(freeze)]  # layers to freeze
        for k, v in self.model.named_parameters():
            v.requires_grad = True  # train all layers
            # v.register_hook(lambda x: torch.nan_to_num(x))  # NaN to 0 (commented for erratic training results)
            if any(x in k for x in freeze):
                v.requires_grad = False
        return self
    
    def unfreeze_backbone(self):
        # unfreeze backbone params
        for k, v in self.model.named_parameters():
            v.requires_grad = True  # train all layers
            # v.register_hook(lambda x: torch.nan_to_num(x))  # NaN to 0 (commented for erratic training results)
        return self`

**Comment by CharisWg** [comment]
Thank @SonwYang for your contribution

my code is:
class FinetuneYolo(YOLO):
    def load_backbone(self, ckptPath):
        """
        Transfers backbone parameters with matching names and shapes from 'weights' to model.
        """
        backboneWeights = torch.load(ckptPath)
        self.model.load_state_dict(backboneWeights, strict=False)
        return self
    
    def freeze_backbone(self, freeze):
        # Freeze backbone params
        freeze = [f'model.{x}.' for x in  range(freeze)]  # layers to freeze
        for k, v in self.model.named_parameters():
            v.requires_grad = True  # train all layers
            # v.register_hook(lambda x: torch.nan_to_num(x))  # NaN to 0 (commented for erratic training results)
            if any(x in k for x in freeze):
                v.requires_grad = False
        return self
    
    def unfreeze_backbone(self):
        # unfreeze backbone params
        for k, v in self.model.named_parameters():
            v.requires_grad = True  # train all layers
            # v.register_hook(lambda x: torch.nan_to_num(x))  # NaN to 0 (commented for erratic training results)
        return self

    model_cfg_path = opt.cfg.replace('yolov8.yaml', f'yolov8{opt.scale}.yaml')
    model = FinetuneYolo(model_cfg_path)# Initialize YOLO model from config
    print(f"Before loading: Model ckpt: {model.ckpt}")
    model.load_backbone(opt.ckptPath)# Load custom backbone
    print(f"After loading: Model ckpt: {model.ckpt}")
    print(f"Loaded ckpt_path: {opt.ckptPath}")

And the printout is:
Before loading: Model ckpt: None
After loading: Model ckpt: None
Loaded ckpt_path: /datashare3/charis/code2/SSL-yolo8/best_Backbone.pth

can you assist me to check why  Model ckpt is None?
