### ISSUE TITLE
Bug in yaml_save running train in docker

### ISSUE THREAD

**Issue by diramazioni** [ultralytics/ultralytics#2630]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hello, I was facing the below error, while running inside docker, 
```
  File "/whatever.py", line 51, in train_mode
    model.train(data='dataset/YOLO/dataset.yaml', project=project, imgsz=imgsz, augment=augment, batch=batch, epochs=epochs)
  File "/usr/local/lib/python3.11/site-packages/ultralytics/yolo/engine/model.py", line 365, in train
    self.trainer = TASK_MAP[self.task][1](overrides=overrides, _callbacks=self.callbacks)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ultralytics/yolo/engine/trainer.py", line 102, in init
    yaml_save(self.save_dir / 'args.yaml', vars(self.args))  # save run args
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ultralytics/yolo/utils/init.py", line 264, in yaml_save
    dict[k] = str(v)
    ~~~~^^^
TypeError: 'type' object does not support item assignment
```

I made a fix even if I'm not familiar with the codebase that made it pass that error.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
I think this PR should address this issue https://github.com/ultralytics/ultralytics/pull/2622

**Comment by diramazioni** [comment]
Funny we've submitted almost the same PR, at almost the same time, however as you can see in mine I've also modified the signature because I think data can't be Null (see my PR)

**Comment by glenn-jocher** [comment]
Hello @diramazioni! Thanks for the pull request and for the contribution to the YOLOv8 project! We will review and test your PR as soon as possible. 

Regarding your question about the data argument being null, could you please elaborate a bit more on the issue or scenario in which the data variable can be null? This would help us better understand the problem and evaluate your proposed solution. 

Thanks again for your time and contribution to the project!

**Comment by diramazioni** [comment]
Hello @glenn-jocher ,
I've just inferred from the code since if data is `Null` below on line 261 `for k, v in data.items():` would raise and exception iterating over Null.

**Comment by glenn-jocher** [comment]
Hello @diramazioni, thanks for your explanation. I understand your point now. In your PR, you modified the function signature for `yaml_save()` to make `data` a required argument, which should eliminate the possibility of `data` being null and raising an exception in line 261. 

Thanks for taking the time to contribute to YOLOv8! Don't hesitate to reach out if you have any other questions or suggestions.
