### ISSUE TITLE
Neither 'setup.py' nor 'pyproject.toml' found.

### ISSUE THREAD

**Issue by KhoiNghiem** [ultralytics/ultralytics#264]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I encountered this problem **"neither 'setup.py' nor 'pyproject.toml' found"** when installing from source.

### Environment

- Ubuntu 20.04 
- Pytorch 1.12.1+cu116
- Torchvision  0.13.1

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@KhoiNghiem can you please provide the command to reproduce?

**Comment by KhoiNghiem** [comment]
@AyushExel I already cd in the previous command
Exactly like this:
git clone https://github.com/ultralytics/ultralytics
cd ultralytics
pip install -e ultralytics
Obtaining file:///home/khoi/Documents/Yolov8/ultralytics/ultralytics
ERROR: file:///home/khoi/Documents/Yolov8/ultralytics/ultralytics does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

**Comment by Laughing-q** [comment]
can you try this one?
```python
cd ultralytics
pip install -e.
```

**Comment by glenn-jocher** [comment]
@KhoiNghiem to install from source:

```bash
!pip install git+https://github.com/ultralytics/ultralytics
```

Closing this issue but let us know if you have any other problems.

**Comment by moaazEl** [comment]
I am encountering  the same issue when running 
pip install -e. 
in a python environment.

**Comment by glenn-jocher** [comment]
Make sure you're running the `pip install -e .` command from within the root `ultralytics` directory where the `setup.cfg` file is located. If the issue persists, try updating `pip` with `pip install --upgrade pip`.

**Comment by furycurry** [comment]
@glenn-jocher hello. I am trying to install yolov5 and followed the steps mentioned above. Unfortunately facing this error.

> ```
> (john) john@ps:/lab_202/john/project/yolov5/yolov5-master/yolov5-master$ pip install -e .
> Defaulting to user installation because normal site-packages is not writeable
> WARNING: Ignoring invalid distribution -orch (/usr/local/anaconda3/envs/john/lib/python3.10/site-packages)
> Obtaining file:///lab_202/john/project/yolov5/yolov5-master/yolov5-master
>   Installing build dependencies ... done
>   Checking if build backend supports build_editable ... done
>   Getting requirements to build editable ... error
>   error: subprocess-exited-with-error
>   
>   × Getting requirements to build editable did not run successfully.
>   │ exit code: 1
>   ╰─> [14 lines of output]
>       error: Multiple top-level packages discovered in a flat-layout: ['data', 'models', 'segment', 'classify'].
>       
>       To avoid accidental inclusion of unwanted files or directories,
>       setuptools will not proceed with this build.
>       
>       If you are trying to create a single distribution with multiple packages
>       on purpose, you should not rely on automatic discovery.
>       Instead, consider the following options:
>       
>       1. set up custom discovery (`find` directive with `include` or `exclude`)
>       2. use a `src-layout`
>       3. explicitly set `py_modules` or `packages` with a list of names
>       
>       To find more information, look for "package discovery" on setuptools docs.
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build editable did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> ```

**Comment by Laughing-q** [comment]
@furycurry Hi for yolov5 we don't support `pip install -e.`. Recommend you directly use our `ultralytics` package by:
```bash
pip install ultralytics
```

**Comment by furycurry** [comment]
> @furycurry Hi for yolov5 we don't support `pip install -e.`. Recommend you directly use our `ultralytics` package by:
> 
> ```shell
> pip install ultralytics
> ```

Thanks @Laughing-q
