### ISSUE TITLE
duplicate logging folder spawn when DDP mode 

### ISSUE THREAD

**Issue by kboseong** [ultralytics/ultralytics#2642]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

duplicate folder spawn when train with DDP mode.
wandb projects are spawned duplicate too.
8.0.98 is okay, but 8.0.103 makes error.(8.0.101 makes error too)

### Environment

Using NGC 23.01 docker container

Hardware: NVDIA A100 Station(80G 4GPU)
Pytorch : 1.14.0a0+410ce96
Cuda : 12.01

### Minimal Reproducible Example

```
from ultralytics import YOLO

model = YOLO('yolov8x6.pt')  

model.train(
    data='config.yaml', 
    epochs=20, 
    patience=50,
    batch=64, 
    imgsz=1280,
    save=True,
    save_period=-1,
    cache=False, 
    device = '0,1,2,3',
    workers=16,
    project='my-project', 
    name='project100',
    exist_ok=False,
    pretrained=True, 
    optimizer='SGD',
    verbose=False,
    seed=0,
    deterministic=True,
    single_cls=False,
    rect=False,
    cos_lr=False,
    close_mosaic=0,
    resume=False,
    amp=True,
    lr0=0.01,
    lrf=0.01,
    momentum=0.937,
    weight_decay=0.0005,
    warmup_epochs=2,
    warmup_momentum=0.8,
    warmup_bias_lr=0.1,
    box=7.5,
    cls=0.5,
    dfl=1.5,
    pose=12.0,
    kobj=2.0,
    label_smoothing=0.0,
    nbs=64,
    overlap_mask=True,
    mask_ratio=4,
    dropout=0.0,
    val=True
)

```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kboseong thanks for the bug report! This is probably due to a recent PR by @developer0hye for delaying DDP timeouts. I'll revert the PR in the next release today. 

@developer0hye maybe it's just easier to extend the timeout period from 30 minutes to something higher?
