### ISSUE TITLE
Question about fixed output box

### ISSUE THREAD

**Issue by mingqiJ** [ultralytics/ultralytics#2647]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would like to ask if I can fix the prediction box of YOLOv8 to get the predicted score of the category I determined in this box I specified?

I don't want the model to predict the box, I specify the box and category.

**Comment by glenn-jocher** [comment]
@mingqiJ hello! Based on your question, it seems you are looking for a way to manually set the bounding box and category prediction output in YOLOv8. While YOLOv8 does allow for custom training on specific datasets, the model itself is not designed to take predetermined boxes or categories as input. The purpose of YOLOv8 is to predict bounding boxes and categories for objects in images on its own.

However, I would like to point out that the Ultralytics team welcomes community contributions and suggestions. If this is a feature that would benefit your use case, we encourage you to fork the repo and make any necessary changes you need. You can also submit a feature request as a Github issue on our repo and our team will review it. Thank you for your interest in YOLOv8 🚀!

**Comment by mingqiJ** [comment]
@glenn-jocher Hi! Thanks for you reply. I see. The YOLOv8 is to predict bounding boxes and categories for objects in images on its own.

I would like to ask **is it possible** to fix the prediction box of YOLOv8 to get the predicted score of the category I determined in this box I specified?

Or is this not feasible for YOLOv8.

**Comment by glenn-jocher** [comment]
Hello @mingqiJ, you're welcome. To answer your question, YOLOv8 is not designed to take predetermined or fixed boxes as input. The model's architecture is specifically designed to make real-time predictions of object detection bounding boxes and categories on its own based on the image fed into it. Therefore, it is not possible to fix the prediction box of YOLOv8 as described in your question. However, as I mentioned earlier, we welcome community contributions and suggestions, so if you have a specific use case where this functionality is necessary, you can fork the repository and make any necessary changes or submit a feature request as a GitHub issue on our repo. Thank you for your interest in YOLOv8 🚀!

**Comment by mingqiJ** [comment]
@glenn-jocher Hi! Thanks for your help! It is very useful.

**Comment by glenn-jocher** [comment]
@mingqiJ you're welcome, glad to hear that my help was useful to you! If you have any more questions or issues related to YOLOv8, feel free to ask. We're always here to help. Thank you for using YOLOv8 🚀!
