### ISSUE TITLE
How to set up image size and multi scale training for the API?

### ISSUE THREAD

**Issue by ch-hristov** [ultralytics/ultralytics#265]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

Altho it seems like a silly question, I can't really find the answer.

How do I set up multi scale training and/or other parameters when using the python API?

Thank you

**Comment by AyushExel** [comment]
@ch-hristov thanks for asking. `model.train()` accepts all training arguments mentioned here https://docs.ultralytics.com/config/#training 
for example:
``
mode.train(data=..., epochs=1, lr0=0.001..,..)
```

**Comment by ch-hristov** [comment]
@AyushExel Thank you!

**Comment by ch-hristov** [comment]
@AyushExel after looking into this a bit further I found this:

[[https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/configs/default.yaml#L10](url)](https://github.com/ultralytics/ultralytics/blob/f5dfd5be8b169935266ff602b8004a34d94feec5/ultralytics/yolo/configs/default.yaml#L10)


The parameter for multi scale training is not here. The most similar is this:

https://github.com/ultralytics/ultralytics/blob/f5dfd5be8b169935266ff602b8004a34d94feec5/ultralytics/yolo/configs/default.yaml#L94

But not 100% sure about that

**Comment by Laughing-q** [comment]
@ch-hristov the scale is a arg for affine augmentation, not the multi-scale training.
@AyushExel actually I think I haven't added the functionality of multi-scale yet.

**Comment by AyushExel** [comment]
Yes! mutli-scale training has not been added yet. I'll put it in our TODOs.

**Comment by ch-hristov** [comment]
Thank you for letting me know, please feel free to keep or close this issue if you want to keep track of this request. I will add "multi scale training" in the name to make it clearer.

**Comment by AyushExel** [comment]
Thanks!

**Comment by 25benjaminli** [comment]
@AyushExel has there been any progress on this?

**Comment by avril-wang1214** [comment]
@AyushExel Looking forward to your further work

**Comment by ZongXR** [comment]
> Looking forward to your further work

Is the multi_scale training available now?

**Comment by Laughing-q** [comment]
@ZongXR yes!
https://github.com/ultralytics/ultralytics/blob/d021524e850acfa393ec25d4ecb9c4c761cca688/ultralytics/cfg/default.yaml#L37

**Comment by ZongXR** [comment]
> @ZongXR yes!
> 
> https://github.com/ultralytics/ultralytics/blob/d021524e850acfa393ec25d4ecb9c4c761cca688/ultralytics/cfg/default.yaml#L37

This is only the configuration file. But I don't find any parameters in model.train related with multi_scale. When I set model.train(multi_scale=True), it raise an error for me.
