### ISSUE TITLE
Classify training ignores fliplr (and others)

### ISSUE THREAD

**Issue by HoLue** [ultralytics/ultralytics#2651]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Traing classify ignores parameters, e.g. fliplr.

My sample was training mnist160 in colab. YOLOv8_cls_bug01.ipynb with all included as zip:
[YOLOv8_cls_bug01.zip](https://github.com/ultralytics/ultralytics/files/11486016/YOLOv8_cls_bug01.zip)

Here are the images of first training batch image (default fliplr=0.5, ok);
![train_batch0_model_def](https://github.com/ultralytics/ultralytics/assets/55573836/cbf5e4cd-a24d-4ab6-a16e-9fbda10ea3ff)

And here for the traioning with fliplr=0 (flipping left right was done although fliplr=0 !):
![train_batch0_model_01](https://github.com/ultralytics/ultralytics/assets/55573836/77a65191-0ba7-4d7c-be46-a7741e5918e3)

The both args.yaml contain the correct fliplr - here the files as zip:
[args_yaml.zip](https://github.com/ultralytics/ultralytics/files/11486040/args_yaml.zip)

I tried several other parameters, too. Almost all concerning augmentation are ignored, too.

### Environment

Ultralytics YOLOv8.0.103 🚀 Python-3.10.11 torch-2.0.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 23.4/166.8 GB disk)
(Colab)

### Minimal Reproducible Example

# Pip install method (recommended)
%pip install ultralytics
import ultralytics
ultralytics.checks()

# Load YOLOv8n-cls, train it on mnist160
from ultralytics import YOLO

model_def = YOLO('yolov8n-cls.pt')  # load a pretrained YOLOv8n classification model
model_def.train(data='mnist160', imgsz=224, epochs=3)  # train the model

model_01 = YOLO('yolov8n-cls.pt')  # load a pretrained YOLOv8n classification model
model_01.train(data='mnist160', imgsz=224, epochs=3, fliplr=0.0)  # train the model

# Result
#Results are exactly equal, so everything must be same. In addition train_batch0.jpg images in both training settings and
#args.yaml where there is a difference

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@HoLue hello! Thank you for bringing this to our attention. We apologize for the inconvenience you've experienced. Our team is investigating this issue and will work to resolve it as soon as possible. It appears that parameters such as fliplr are not being properly applied during training. The issue appears to be reproducible with your given demo. We appreciate your patience and understanding as we work to address this issue. Please feel free to let us know if you have any further questions or concerns.

**Comment by HoLue** [comment]
Yes, seems to work, now! Thanks!!!

**Comment by pderrenger** [comment]
You're welcome, @HoLue! I'm glad to hear that the issue seems to be resolved now. If you encounter any further questions or concerns, feel free to reach out. Your feedback is extremely valuable to us as we continue to improve YOLOv8. Thank you for your support!
