### ISSUE TITLE
huge box_loss in new version

### ISSUE THREAD

**Issue by MikL9** [ultralytics/ultralytics#2655]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I was training a new model and noticed that I have a big loss. For the purity of the experiment, I took my last dataset (which was already successfully trained) and launched it following the loss.
Here are my results on the same data and the same versions of all libraries except ultralytics. Default configuration, except for batch = 8 and epoch = 50 (in both)
-yolo task=detect mode=train model=yolov8n.pt imgsz=1280 data=pothole_v8.yaml epochs=50 batch=8 name=yolov8n_v8_50e 
(Winows 11, gpu 1070ti, cpu i7-6700K)

1. ultralytics == 8.0.100 
 1/50      4.27G       1921      4.922       1494         34       1280: 100%|██████████| 46/46 [01:00<00:00,  1.31s/it]

2. ultralytics == 8.0.82
 1/50      4.16G      1.409       4.63      1.304         18       1280: 100%|██████████| 46/46 [00:30<00:00,  1.52it/s]

as you can see box_loss difference between 1921 and 1.409 as well as cls_loss.

I don’t know on which exact version between 82 and 100 the error occurred because it was updated from 8.0.82 to 8.0.100.
If you need any additional information, I can provide it based on the clearML logs.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MikL9 duplicate bug report, resolved in 8.0.101 yesterday.
