### ISSUE TITLE
The accuracy of RT-DETR cannot be aligned

### ISSUE THREAD

**Issue by Luo-Z13** [ultralytics/ultralytics#2659]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I use code in https://github.com/ultralytics/ultralytics/pull/2538/files, to inference RT-DETR in COCO2007 val set, but my AP is only 49.1 using "rtdetr-l.pt", cannot be aligned with the reported AP of 53.0% in the document .

### Environment

Ultralytics YOLOv8.0.103 🚀 Python-3.8.16 torch-2.0.1+cu117 CUDA:0 (NVIDIA TITAN RTX, 24220MiB)

### Minimal Reproducible Example
```
from ultralytics import RTDETR`

# model = RTDETR("rtdetr-l.pt")  # AP:49.1
model = RTDETR("rtdetr-x.pt")  # AP: 50.5
model.info()  # display model information
# model.predict("path/to/image.jpg")  # predict
# Validate the model
metrics = model.val()  # no arguments needed, dataset and settings remembered
metrics.box.map    # map50-95
print('metrics.box.map:',metrics.box.map )
metrics.box.map50  # map50
metrics.box.map75  # map75
metrics.box.maps 
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Luo-Z13** [comment]
I just create a new python file:
[demo.zip](https://github.com/ultralytics/ultralytics/files/11488142/demo.zip)

**Comment by glenn-jocher** [comment]
@Luo-Z13 it's possible you may need to update val default arguments.

@Laughing-q what val() settings did you use to get 53.0 on RTDETR-l?

**Comment by Laughing-q** [comment]
@Luo-Z13 @glenn-jocher please use cocoeval tools to reproduce. It seems there's a big gap between our internal map calculation and cocoeval for RT-DETR.
```python
from ultralytics.vit import RTDETR
model = RTDETR("rtdetr-l.pt")
model.val(data="coco.yaml")
```
our calculation: 49.3
![image](https://github.com/ultralytics/ultralytics/assets/61612323/606dfb7b-743e-43f6-8a8e-51cc7c591b3d)
cocoeval: 52.4
![image](https://github.com/ultralytics/ultralytics/assets/61612323/cf5af235-c911-4bcd-ad1a-8d52077e7cde)

BTW we got  52.4 mAP(slightly lower than official paddle weights, 53mAP) for rtdetr-l and 54 mAP(vs official 54.8) for rtdetr-x respectively. Still have gap with official ones but I think could be unavoidable since the weights are migrated from paddle to torch.
The gap can be eliminated once we implement the training and train the models ourselves I think.

**Comment by Luo-Z13** [comment]
> 

Thank you very much. I understand the reason now. Would it be possible for you to provide the script for validating using cocoeval? If it's convenient for you, I think it would be great if you could also update it in the [doc]https://github.com/ultralytics/ultralytics/pull/2538.

**Comment by Laughing-q** [comment]
@Luo-Z13 just the same as our yolo models. :) 
But the cocoeval trigger is hard-coded and assuming you structure coco dataset like this:
from our `ultralytics/datasets/coco.yaml`:
```yaml
path: ../datasets/coco  # dataset root dir
train: train2017.txt  # train images (relative to 'path') 118287 images
val: val2017.txt  # val images (relative to 'path') 5000 images
test: test-dev2017.txt  # 20288 of 40670 images, submit to https://competitions.codalab.org/competitions/20794
```
If you do not have such a structure then you need to modify two places:
1. [https://github.com/ultralytics/ultralytics/blob/b1119d512e738e90f2327b316216b069ed576a56/ultralytics/yolo/v8/detect/val.py#L47](https://github.com/ultralytics/ultralytics/blob/b1119d512e738e90f2327b316216b069ed576a56/ultralytics/yolo/v8/detect/val.py#L47), set `self.is_coco=True`.
2. [https://github.com/ultralytics/ultralytics/blob/b1119d512e738e90f2327b316216b069ed576a56/ultralytics/yolo/v8/detect/val.py#L253](https://github.com/ultralytics/ultralytics/blob/b1119d512e738e90f2327b316216b069ed576a56/ultralytics/yolo/v8/detect/val.py#L253), set your own annotation path `anno_json=Path("your annotation path")`

then run:
```python
from ultralytics.vit import RTDETR
model = RTDETR("rtdetr-l.pt")
model.val(data="coco.yaml")
```

**Comment by Luo-Z13** [comment]
> 



> @Luo-Z13 just the same as our yolo models. :) But the cocoeval trigger is hard-coded and assuming you structure coco dataset like this: from our :`ultralytics/datasets/coco.yaml`
> 
> ```yaml
> path: ../datasets/coco  # dataset root dir
> train: train2017.txt  # train images (relative to 'path') 118287 images
> val: val2017.txt  # val images (relative to 'path') 5000 images
> test: test-dev2017.txt  # 20288 of 40670 images, submit to https://competitions.codalab.org/competitions/20794
> ```
> 
> If you do not have such a structure then you need to modify two places:
> 
> 1. https://github.com/ultralytics/ultralytics/blob/b1119d512e738e90f2327b316216b069ed576a56/ultralytics/yolo/v8/detect/val.py#L47
>    , set .`self.is_coco=True`
> 2. https://github.com/ultralytics/ultralytics/blob/b1119d512e738e90f2327b316216b069ed576a56/ultralytics/yolo/v8/detect/val.py#L253
>    , set your own annotation path `anno_json=Path("your annotation path")`
> 
> then run:
> 
> ```python
> from ultralytics.vit import RTDETR
> model = RTDETR("rtdetr-l.pt")
> model.val(data="coco.yaml")
> ```

Thank you for your assistance. I am now able to achieve the desired accuracy (AP 52.4).

**Comment by glenn-jocher** [comment]
You're welcome, @Luo-Z13! We're glad to hear that your issue has been resolved and that you're able to achieve the desired accuracy of 52.4 AP using the above provided method. Don't hesitate to reach out to us if you have any further questions or concerns.
