### ISSUE TITLE
Directly predict with .onnx/.engine file

### ISSUE THREAD

**Issue by DaleBestOrbexLabs** [ultralytics/ultralytics#266]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Currently there is a runtime key error when doing YOLO("yolov8n.onnx") of "KeyError: '.onnx'". It appears that the YOLO wrapper only explicitly supports .pt files, however the AutoBackend appears to properly open .engine and .onnx files but doesn't have the same abstractions.

Is this a bug? If then I would like to request a feature to add support for being able to load .onnx/.engine files this way.

**Comment by AyushExel** [comment]
yes this might be a bug I'll try to reproduce and fix it today. Thanks for reporting
