### ISSUE TITLE
SAM - How to perform point or box selection refinement ?

### ISSUE THREAD

**Issue by Dhiaeddine-Oussayed** [ultralytics/ultralytics#2661]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Using the SAM demo online, you can use point selection or box selection for a better precision on an object. 
Is there anyway to implement or perform that ? (I think of using it with existing yolov5 annotations)
![example](https://github.com/ultralytics/ultralytics/assets/75687069/ec8cd95a-3528-470f-bcc8-3217cf47eff9)

**Comment by glenn-jocher** [comment]
@Dhiaeddine-Oussayed hi Sam,

Thank you for reaching out to us about refining point or box selection.

At this time, YOLOv8 does not have a built-in refinement feature for point or box selection. However, we recommend exploring third-party tools or libraries that may be compatible with YOLOv8 and suit your needs.

If you have any further questions or concerns, feel free to ask and we'll do our best to assist.

Best regards.

**Comment by glenn-jocher** [comment]
@Johan154, thank you for bringing this tool to our attention. We appreciate it when our users share their experiences and recommendations with the community.

It's great to hear that you found a tool that implements SAM for labeling, and that it can be used with custom YOLOv8 models. Keep in mind that while this tool may be suitable for your specific labeling needs, it is not an officially recommended or supported tool by the YOLOv8 team.

If you have any further questions or concerns about using YOLOv8, feel free to ask and we'll do our best to assist.

Best regards.
