### ISSUE TITLE
Can't pickle local object 'TorchHistory.add_log_hooks_to_pytorch_module.<locals>.<lambda>'

### ISSUE THREAD

**Issue by vyskocj** [ultralytics/ultralytics#2668]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

<code>
Starting training for 1 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        1/1      11.7G      1.564       4.64      1.419        333        640: 100%|██████████| 2862/2862 [25:21<00:00,  1.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 76/76 [00:27<00:00,  2.76it/s]
                   all       2410      31917      0.262     0.0499     0.0321     0.0189
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/tmp/pbs.15486198.meta-pbs.metacentrum.cz/ipykernel_195945/3018824876.py in <module>
      2 
      3 # Use the model
----> 4 model.train(data=f"datasets/custom.yaml", cache=True, epochs=1)  # train the model

~/.local-carnivore_id_v1.2.sif/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py in train(self, **kwargs)
    369             self.model = self.trainer.model
    370         self.trainer.hub_session = self.session  # attach optional HUB session
--> 371         self.trainer.train()
    372         # Update model and cfg after training
    373         if RANK in (-1, 0):

~/.local-carnivore_id_v1.2.sif/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py in train(self)
    191                 ddp_cleanup(self, str(file))
    192         else:
--> 193             self._do_train(world_size)
    194 
    195     def _setup_ddp(self, world_size):

~/.local-carnivore_id_v1.2.sif/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py in _do_train(self, world_size)
    370                 # Save model
    371                 if self.args.save or (epoch + 1 == self.epochs):
--> 372                     self.save_model()
    373                     self.run_callbacks('on_model_save')
    374 

~/.local-carnivore_id_v1.2.sif/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py in save_model(self)
    413 
    414         # Save last, best and delete
--> 415         torch.save(ckpt, self.last)
    416         if self.best_fitness == self.fitness:
    417             torch.save(ckpt, self.best)

/opt/conda/lib/python3.8/site-packages/torch/serialization.py in save(obj, f, pickle_module, pickle_protocol, _use_new_zipfile_serialization)
    378         if _use_new_zipfile_serialization:
    379             with _open_zipfile_writer(opened_file) as opened_zipfile:
--> 380                 _save(obj, opened_zipfile, pickle_module, pickle_protocol)
    381                 return
    382         _legacy_save(obj, opened_file, pickle_module, pickle_protocol)

/opt/conda/lib/python3.8/site-packages/torch/serialization.py in _save(obj, zip_file, pickle_module, pickle_protocol)
    546     pickler = pickle_module.Pickler(data_buf, protocol=pickle_protocol)
    547     pickler.persistent_id = persistent_id
--> 548     pickler.dump(obj)
    549     data_value = data_buf.getvalue()
    550     zip_file.write_record('data.pkl', data_value, len(data_value))

AttributeError: Can't pickle local object 'TorchHistory.add_log_hooks_to_pytorch_module.<locals>.<lambda>'
</code>

### Environment

ultralytics version: 8.0.103

nvidia-smi:
Wed May 17 08:36:49 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A40                      On | 00000000:61:00.0 Off |                    0 |
|  0%   43C    P0               79W / 300W|  14430MiB / 46068MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A    195945      C   /opt/conda/bin/python3.8                  14424MiB |
+---------------------------------------------------------------------------------------+

### Minimal Reproducible Example

```python
from ultralytics import YOLO
import wandb

def watch_model(trainer):
    wandb.watch(trainer.model, log="all", log_freq=100, log_graph=True)

# Load a model
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)
model.add_callback("on_train_start", watch_model)

# Use the model
model.train(data=f"datasets/custom.yaml", cache=True, epochs=1)  # train the model
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@vyskocj thanks for the bug report! This one is really strange, never seen that before. Does this happen without wandb? Are you using the latest version of `torch` and `ultralytics`?

**Comment by vyskocj** [comment]
Thank you very much for your fast response. Meanwhile, I tried to find the problem and solution (by using coco128.yaml data). The issue, that the `torch.save()` fails, is caused by the `wandb.watch()`.

Luckily, **I found an [easy solution](https://stackoverflow.com/questions/68679806/attributeerror-cant-pickle-local-object-pre-datasets-locals-lambda-when)** that you could implement (or I can via pull request). The only change is in trainer.py:
```python
def save_model(self):
     """Save model checkpoints based on various conditions."""
     ckpt = {
         'epoch': self.epoch,
         'best_fitness': self.best_fitness,
         'model': deepcopy(de_parallel(self.model)).half(),
         'ema': deepcopy(self.ema.ema).half(),
         'updates': self.ema.updates,
         'optimizer': self.optimizer.state_dict(),
         'train_args': vars(self.args),  # save as dict
         'date': datetime.now().isoformat(),
         'version': __version__}

     try:
         import dill as pickle
     except (ImportError, AssertionError):
         import pickle

     # Save last, best and delete
     torch.save(ckpt, self.last, pickle_module=pickle)
     if self.best_fitness == self.fitness:
         torch.save(ckpt, self.best, pickle_module=pickle)
     if (self.epoch > 0) and (self.save_period > 0) and (self.epoch % self.save_period == 0):
         torch.save(ckpt, self.wdir / f'epoch{self.epoch}.pt', pickle_module=pickle)
     del ckpt
```

Then, the following error raises only with "log_graph" (which practically does not matter, the result is only a graphic visualization of the network topology in wandb):

```
TypeError: cannot pickle 'CatBackward0' object
```

**Comment by glenn-jocher** [comment]
@vyskocj ok got it, thanks for the details. Since the error is not reproducible without wandb, then this is outside the scope of our support. You should raise a bug report directly with wandb for this issue, which is apparently caused by their package.

**Comment by djdll** [comment]
```
Starting training for 1000 epochs...

      Epoch    GPU_mem       loss  Instances       Size
     1/1000     0.178G     0.4144         15         96: 100%|██████████| 3277/3277 [02:05<00:00, 26.14it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 344/344 [00:03<00:00, 94.62it/s] 
                   all      0.659          1
Traceback (most recent call last):
  File "/home/dujiang/yolo/ultralytics-main/train_leyolo.py", line 6, in <module>
    model.train(project="cls_barcode", name="train_9_10_b32",
  File "/home/dujiang/yolo/ultralytics-main/ultralytics/engine/model.py", line 810, in train
    self.trainer.train()
  File "/home/dujiang/yolo/ultralytics-main/ultralytics/engine/trainer.py", line 206, in train
    self._do_train(world_size)
  File "/home/dujiang/yolo/ultralytics-main/ultralytics/engine/trainer.py", line 443, in _do_train
    self.save_model()
  File "/home/dujiang/yolo/ultralytics-main/ultralytics/engine/trainer.py", line 491, in save_model
    torch.save(
  File "/home/dujiang/yolo/ultralytics-main/ultralytics/utils/patches.py", line 110, in torch_save
    return _torch_save(*args, **kwargs)
  File "/home/dujiang/miniconda3/envs/yolo/lib/python3.10/site-packages/torch/serialization.py", line 652, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol, _disable_byteorder_record)
  File "/home/dujiang/miniconda3/envs/yolo/lib/python3.10/site-packages/torch/serialization.py", line 864, in _save
    pickler.dump(obj)
AttributeError: Can't pickle local object 'classify_transforms.<locals>.ResizeLongestSide'
```
I encountered a similar problem is I have modified the ultralytics/data/augment classify_transforms function under the py, error mentioned ResizeLongestSide is I modify the contents of the classify_transforms
Change：
```
tfl.extend(
        [
            T.CenterCrop(size),
            T.ToTensor(),
            T.Normalize(mean=torch.tensor(mean), std=torch.tensor(std)),
        ]
    )
```
TO:
```
tfl = [
        ResizeLongestSide(size, interpolation=getattr(T.InterpolationMode, interpolation)),  # 按长边缩放
        PadToSquare(size, fill=padding_color),  # 填充至正方形
        T.ToTensor(),
        T.Normalize(mean=torch.tensor(mean), std=torch.tensor(std)),
    ]
```
ResizeLongestSide like :
```
def classify_transforms(
    size=96,
    mean=DEFAULT_MEAN,
    std=DEFAULT_STD,
    interpolation="BILINEAR",
    crop_fraction: float = DEFAULT_CROP_FRACTION,
    padding_color=(127, 127, 127),  # 默认填充为灰色
):
   
    import torchvision.transforms as T
    import torch
    from torchvision.transforms import functional as F

    class ResizeLongestSide:
        def __init__(self, size, interpolation):
            self.size = size
            self.interpolation = interpolation

        def __call__(self, img):
            # 获取图像的当前尺寸
            width, height = img.size
            # 计算缩放比例
            if width > height:
                new_width = self.size
                new_height = int(self.size * height / width)
            else:
                new_height = self.size
                new_width = int(self.size * width / height)
            # 按长边缩放
            return img.resize((new_width, new_height), Image.BILINEAR)
```
In general, I would like to modify the preprocess for the classification task to change the scale after center clipping to equal scale and then fill to the specified size. Can you help me

**Comment by glenn-jocher** [comment]
It seems like the issue is related to pickling the `ResizeLongestSide` object. To resolve this, try moving the `ResizeLongestSide` class to the top level of your module, outside of the `classify_transforms` function. This should make it pickleable. Let me know if this helps!

**Comment by djdll** [comment]
@glenn-jocher yes，thanks very much! The training is normal, and the code runs normally in my test, but I hope it runs in line with my expectations in the training. I will wait for the end of the training for verification. I really appreciate your quick reply and solution to my doubts each time
