### ISSUE TITLE
Support for seamless numpy.ndarray and headless/silent operation

### ISSUE THREAD

**Issue by DaleBestOrbexLabs** [ultralytics/ultralytics#267]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Currently the recommend abstraction to interact with YoloV8 (from ultralytics import YOLO) does not support prediction on numpy.ndarray images which is quite common for open CV.

Furthermore, in the case in which it does work (using the URL link) the model will continuously print to console. I am not sure if there is a different class I should use for this case.

```
import cv2
from ultralytics import YOLO


test_image = cv2.imread("bus.jpg")

test_model = YOLO(model="yolov8n.pt")
detection_results = test_model.predict(test_image)

for _ in range(100):
    detection_results = test_model(test_image)`

```

### Use case

For applications/services that would run object detection continuously from a video feed and have coded logic based on the response with no need for the logs.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Thanks! we'll work to support this use case this week

**Comment by glenn-jocher** [comment]
Removing TODO as fully resolved now :)
