### ISSUE TITLE
what does the output of YOLOv8 mean?

### ISSUE THREAD

**Issue by eroist** [ultralytics/ultralytics#2670]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

as you know, the output of YOLOv8 model is `float32[1,84,8400]`
what does it actually mean?
thank you~

**Comment by DonkeySmall** [comment]
1 - bath size
84 - 0,1,2,3 is x,y,width,height,  4,5,6,7,8,9.... probability for each class 
8400 - number of possible detected objects

**Comment by glenn-jocher** [comment]
@eroist hi! Thank you for your question regarding the output of the YOLOv8 model. The output of the model has the shape `float32[1,84,8400]`. The first dimension represents the batch size, which is always equal to one. The second dimension consists of 84 values, where the first 4 values represent the bounding box coordinates (x, y, width and height) of the detected object, and the rest of the values represent the probabilities of the object belonging to each class. Finally, the third dimension represents the maximum number of possible detected objects, which is 8400 in this case. I hope this clears things up for you! Let me know if you have any more questions or concerns.

**Comment by Kayzwer** [comment]
@glenn-jocher can you explain the output of segmentation?

**Comment by glenn-jocher** [comment]
@DonkeySmall hi! Thanks for reaching out to us. If you are referring to the output of segmentation in YOLOv8, the model detects and segments objects of interest from an image, returning their bounding boxes coordinates (x, y, width, height) in one part of the output. In another part of the output, the probabilities of the object belonging to each class is returned. Both of these outputs are combined to give the final output. Is there something more specific that you would like to know about the segmentation output? I'm happy to help with any questions or clarifications you may have.

**Comment by eroist** [comment]
thank you @glenn-jocher 
that make sense

**Comment by Kayzwer** [comment]
@glenn-jocher  not quite understand

**Comment by DonkeySmall** [comment]
Here is an example output for a segmentation model with one class and an input size of 800 by 800 pixels
![BC00000000](https://github.com/ultralytics/ultralytics/assets/66531939/ca80ee6c-37dd-48e1-b9b1-5a83d1fdace3)

**[1,37,13125]**
1 - batch size
37 - the first 5 values "x, y, width, height and probability" of the detected object, next **32** values are the probability for the mask
13125 - the maximum number of possible detected objects

**[1,32,200,200] array of 32 masks measuring 200 by 200 pixels**
1 - batch size
**32** - index of the mask
200 - x point
200 - y point

so to get output mask for detected object you need first choose the best probability from first output and remember index of the object mask.

then get the object mask 200x200 pixels from second output **[1, index of the mask, x point, y point]** and interpolate x point and y point to input image multiplying by 4. 

800 / 200 = 4

**Comment by Nhat772001** [comment]
@glenn-jocher Hello, Output has the shape float32 [1,6,8400] "The first dimension represents the batch size, which is always equal to one" , can you please explain to me why it is always 1, thank you very much!

**Comment by complete-dope** [comment]
> @DonkeySmall hi! Thanks for reaching out to us. If you are referring to the output of segmentation in YOLOv8, the model detects and segments objects of interest from an image, returning their bounding boxes coordinates (x, y, width, height) in one part of the output. In another part of the output, the probabilities of the object belonging to each class is returned. Both of these outputs are combined to give the final output. Is there something more specific that you would like to know about the segmentation output? I'm happy to help with any questions or clarifications you may have.

How to extract the x,y,w,h values if each tensor is of size 8400 for ?
