### ISSUE TITLE
[8.0.104] ImportError: cannot import name 'auto_annotate' from 'ultralytics.yolo.data' 

### ISSUE THREAD

**Issue by Denizzje** [ultralytics/ultralytics#2673]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Trying to run the example from: https://docs.ultralytics.com/models/sam/

```
from ultralytics.yolo.data import auto_annotate

auto_annotate(data="path/to/images", det_model="yolov8x.pt", sam_model='sam_b.pt')
```

But with my own YoloV8-segmentation model (seg-l) and a folder of images, results in:

```
python sam_annotate.py 
Traceback (most recent call last):
  File "/home/<username>/ai_dev/datasets/species_i13/sam_annotate.py", line 1, in <module>
    from ultralytics.yolo.data import auto_annotate
ImportError: cannot import name 'auto_annotate' from 'ultralytics.yolo.data' (/home/<username>/.pyenv/versions/3.10.10/lib/python3.10/site-packages/ultralytics/yolo/data/__init__.py)
```

### Environment

- Ultralytics 8.0.104
- Fedora 38
- Torch 2.0 + Cuda 11.8
- Python 3.10 Pyenv, also tried on Python 3.11 system python.

It is a freshly installed enviornment.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Denizzje yes you are right! This should be `from ultralytics.yolo.data.annotator import auto_annotate`

I'll update Docs!

**Comment by AyushExel** [comment]
https://github.com/ultralytics/ultralytics/pull/2676
This should address it

**Comment by Denizzje** [comment]
Fixed ineed!

**Comment by glenn-jocher** [comment]
Hi @Denizzje, 

Thank you for reporting this issue and bringing it to our attention. We have found the problem and fixed it. 

You were correct in that the import should be modified to `from ultralytics.yolo.data.annotator import auto_annotate`. We have updated the Docs and merged the changes into the main branch. 

Thank you for your support of YOLOv8. If you encounter any further problems or have suggestions, please don't hesitate to reach out to us. 

Best regards,
Glenn Jocher

**Comment by adrianfernandeziturcemi** [comment]
Hi, im working from google colab to test this functionalities, however  it isnt able to find that import


![imagen](https://github.com/ultralytics/ultralytics/assets/118820735/78a6e404-ca4b-4066-a6c1-4443d60ecb22)

Same with the function auto_annotate

Could anyone tell me if i am missing something?, on the same notebook i have previously imported YOLO, train and even do some infereence in images.

**Comment by glenn-jocher** [comment]
Hello @adrianfernandeziturcemi, 

Thank you for reaching out to us. We're sorry to hear that you are experiencing import issues with `auto_annotate` and `convert_coco`.

From your screenshot, it appears that your notebook is unable to locate the `ultralytics` module. Please ensure that you have installed YOLOv8 correctly. You can do this by running `!pip install -U yolov8`.

After verifying that YOLOv8 is installed correctly, you can try importing again using `from ultralytics.yolo.data.annotator import auto_annotate` and `from ultralytics.yolo.utils.datasets import convert_coco`. 

Please let us know if this resolves the issue. If you encounter any further problems or have any additional questions, please don't hesitate to reach out to us.

Best regards,
Glenn Jocher
