### ISSUE TITLE
Resuming an existing track

### ISSUE THREAD

**Issue by MotsPassant** [ultralytics/ultralytics#2677]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I would love to see a new feature allowing us to resume a tracking of objects when new images are added to the timeseries. 

### Use case

My use case is this : 
I have multiple cameras that take pictures of fruits in a timelapse fashion (1 photo/hour). I go download the pictures every few days to add to my timeseries. I perform tracking with model.track() on these pictures with a YOLO model trained on a custom dataset, and it works wonderfully (thank you for your work !). But when I add new pictures every dew days, I don't want to have to start the tracking from scratch because I already made analysis on these pictures. I can easily write a script so that only the new images are considered for the new tracking, but then the IDs will be assigned differently. 

I have my own solution, which is : 
1. Compare images folder and labels folder to see until which image the tracking has been performed. Let's call this image N. 
2. Perform a new tracking from image N (included) and the rest of the new images. Labels will be saved in another folder, otherwise the label file for image N will be replaced. 
3. Now, we have two separate labels files for image N (because it has been tracked on two separate occasions).
4. Compare these two files to match the IDs. 
5. Update all the new labels files to rewrite the IDs to match those of the first tracking.
6. Move all the updated labels files to the original labels folder.

But obviously, if you could make a feature like that, I think it would be much better and useful in many use cases. Although I understand that you would have to know where the labels folder is located. 

Thank you for reading !

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MotsPassant thank you for your feature request, we appreciate your feedback! We understand the importance of being able to resume object tracking when new images are added to a timeseries, especially for use cases where analysis has already been performed on previous images. 

While we currently do not have this feature available, we will forward your request to our development team for consideration in future updates. In the meantime, we suggest using the solution you have written if it meets your needs. 

Thank you for using YOLOv8, and please feel free to contact us if you have any other questions or concerns.
