### ISSUE TITLE
Save Format when model.predict(save_txt=True)

### ISSUE THREAD

**Issue by Yusepp** [ultralytics/ultralytics#2679]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Given that the predictions saved from the .mp4 file are in the format of class index, bounding box, and confidence, and that the bounding box values appear to be normalized between 0 and 1, could you please provide clarity on the format used for these bounding box coordinates? Specifically, are they represented as top-left corner coordinates and width-height (xywh), top-left and bottom-right corner coordinates (xyxy), or center coordinates and width-height (center_x, center_y, w, h)?

**Comment by glenn-jocher** [comment]
@Yusepp thank you for your question. The bounding box coordinates saved via 'model.predict(save_txt=True)' are represented as center coordinates and width-height (center_x, center_y, w, h). Specifically, the first two values represent the x and y coordinates of the center of the bounding box, and the last two values represent the width and height of the bounding box respectively.
