### ISSUE TITLE
Detection with old code of yolov5

### ISSUE THREAD

**Issue by hdnh2006** [ultralytics/ultralytics#268]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi community, 

I just wanted to share with you this repo https://github.com/hdnh2006/yolov8asyolov5 which is able to use the new weights of yolov8 with the old code of yolov8 (just detection task by the moment).

The way to use it is similar as before, it just needs a flag `--is-yolov8`:

```
python detect.py --is-yolov8 --weights yolov8s.pt --source 0                               # webcam
                                                     img.jpg                         # image
                                                     vid.mp4                         # video
                                                     screen                          # screenshot
                                                     path/                           # directory
                                                     list.txt                        # list of images
                                                     list.streams                    # list of streams
                                                     'path/*.jpg'                    # glob
                                                     'https://youtu.be/Zgi9g1ksQHc'  # YouTube
                                                     'rtsp://example.com/media.mp4'  # RTSP, RTMP, HTTP stream
```

### Use case

Old code recycled

### Additional

Congratulations @glenn-jocher for this new version.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Great work! could please share what's the advantages/use-case of the v5 style usage? We'd like to improve ultralytics framework to better support maximum use cases

**Comment by hdnh2006** [comment]
It's an honor to get these words from you. You have done an awesome job and you have changed vision AI forever. Congratulations @AyushExel.

The performance is the same in all weights (detection), but there are many repos that still depend of the v5 style usage like [Yolov5_StrongSORT_OSNet](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet)) where I am contributor, and I think this could be helpful to those users. 

The new v8 code is fantastic but maybe there are some tools from v5 style that still can be helpful. 

Anyway, congratulations again for this fantastic tool.

**Comment by AyushExel** [comment]
Thanks for the kind words! the credit goes to the whole ultralytics team

**Comment by kadirnar** [comment]
Hi @hdnh2006 ,

I want to add tracker algorithms to Yolov8 model. But I get an error because this library does not support numpy. Did you solve this error?

**Comment by hdnh2006** [comment]
Hi @kadirnar,

You say "this library", what library are you refering to? ultralytics? Of course it supports numpy. I don't know what you mean, but actually ultralytics needs numpy as you can see in requirements:
https://github.com/ultralytics/ultralytics/blob/d0b616e41e827e1ac65ee99da1339e707a984989/requirements.txt#L7

**Comment by kadirnar** [comment]
> Hi @kadirnar,
> 
> You say "this library", what library are you refering to? ultralytics? Of course it supports numpy. I don't know what you mean, but actually ultralytics depends on numpy as you can see in requirements:
> 
> https://github.com/ultralytics/ultralytics/blob/d0b616e41e827e1ac65ee99da1339e707a984989/requirements.txt#L7

ultralytics library only supports str format(img/video). Numpy image has not been added yet. https://github.com/ultralytics/ultralytics/issues/271#issuecomment-1379479778

**Comment by hdnh2006** [comment]
It is something that along my career I have not needed, so maybe you should try it. Why would you need to label "images" converted to numpy (`*.npy` files)? I don't know, it is easier and less abstract to read the files and then label them. Try to modify the code yourself.

**Comment by hdnh2006** [comment]
Ok, whatever, you are not explaining yourself very well.

Good luck.

**Comment by hdnh2006** [comment]
hahaha @kadirnar you definitely are a kid 😂😂😂

**Comment by kadirnar** [comment]
Please follow github guidelines and only write technical articles.
