### ISSUE TITLE
Not able to perform hyperparameter tuning with ClearML

### ISSUE THREAD

**Issue by vignesh-Ag** [ultralytics/ultralytics#2688]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Integrations

### Bug

I am trying to run a hyperparameter tuning script for Yolov8n (object detection) with ClearML using Optuna.  I could see experiments are getting created. Also, I have successfully trained a model using the training script that is being used for optimization. However, I keep getting the below error for all the experiments.

YOLOv8n summary: 225 layers, 3012018 parameters, 3012002 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs/detect/train', view at http://localhost:6006/
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
optimizer: SGD(lr=0.01) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias
train: Scanning /data/labels/train.cache... 317 images, 19 backgrounds, 0 corrupt: 100%|██████████| 336/336 [00:00<?, ?it
/home/vignesh/miniconda3/envs/pytorch/lib/python3.9/site-packages/ultralytics/yolo/data/base.py:124: FutureWarning:

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

Traceback (most recent call last):
  File "/shared_data/AC/yolo/yolo_train.py", line 32, in <module>
    model.train(**args)  # train the model
  File "/home/vignesh/miniconda3/envs/pytorch/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py", line 371, in train
    self.trainer.train()
  File "/home/vignesh/miniconda3/envs/pytorch/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/vignesh/miniconda3/envs/pytorch/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 273, in _do_train
    self._setup_train(world_size)
  File "/home/vignesh/miniconda3/envs/pytorch/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 255, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
  File "/home/vignesh/miniconda3/envs/pytorch/lib/python3.9/site-packages/ultralytics/yolo/v8/detect/train.py", line 59, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode, batch_size)
  File "/home/vignesh/miniconda3/envs/pytorch/lib/python3.9/site-packages/ultralytics/yolo/v8/detect/train.py", line 33, in build_dataset
    return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == 'val', stride=gs)
  File "/home/vignesh/miniconda3/envs/pytorch/lib/python3.9/site-packages/ultralytics/yolo/data/build.py", line 74, in build_yolo_dataset
    return YOLODataset(
  File "/home/vignesh/miniconda3/envs/pytorch/lib/python3.9/site-packages/ultralytics/yolo/data/dataset.py", line 39, in __init__
    super().__init__(*args, **kwargs)
  File "/home/vignesh/miniconda3/envs/pytorch/lib/python3.9/site-packages/ultralytics/yolo/data/base.py", line 70, in __init__
    self.update_labels(include_class=classes)  # single_cls and include_class
  File "/home/vignesh/miniconda3/envs/pytorch/lib/python3.9/site-packages/ultralytics/yolo/data/base.py", line 124, in update_labels
    j = (cls == include_class_array).any(1)
AttributeError: 'bool' object has no attribute 'any'

### Environment
Ubuntu==22.04.2 LTS
clearml == 1.10.4
torch==2.0.1+cu117
optuna == 3.1.1
ultralytics == 8.0.105

## Optimization script
```
from clearml.automation import UniformParameterRange, UniformIntegerParameterRange, DiscreteParameterRange
from clearml.automation import HyperParameterOptimizer
from clearml.automation.optuna import OptimizerOptuna
from clearml.automation.hpbandster import OptimizerBOHB
from clearml.automation import RandomSearch
from clearml import Task

from ultralytics import YOLO

task = Task.init(project_name='Hyperparameter with Optuna',
                 task_name='Hyperparameter Search for ocg',
                 task_type=Task.TaskTypes.optimizer,
                 reuse_last_task_id=False)

TEMPLATE_TASK_ID = 'ad629417ec6419a3e64'


optimizer = HyperParameterOptimizer(
    base_task_id=TEMPLATE_TASK_ID,  # This is the experiment we want to optimize

    # here we define the hyper-parameters to optimize
    hyper_parameters=[
        UniformIntegerParameterRange('General/epochs', min_value=100, max_value= 1000, step_size=2),
        UniformIntegerParameterRange('General/batch', min_value=2, max_value=16, step_size=2),
        UniformIntegerParameterRange('General/imgsz', min_value=2, max_value=16, step_size=2),
        UniformParameterRange('General/dropout', min_value=0, max_value=0.5, step_size=0.05),
        UniformParameterRange('General/lrf', min_value=0.00025, max_value=0.01, step_size=0.00025),
        UniformParameterRange('General/lr0', min_value=0.00025, max_value=0.01, step_size=0.00025),
 
        
    ],
    # setting the objective metric we want to maximize/minimize
    objective_metric_title='metrics',
    objective_metric_series='mAP50-95(B)',
    objective_metric_sign='max',  # maximize or minimize the objective metric

    # setting optimizer - clearml supports GridSearch, RandomSearch, OptimizerBOHB and OptimizerOptuna

    optimizer_class=OptimizerOptuna,
    
    # Configuring optimization parameters
   
    max_number_of_concurrent_tasks=1,  # number of concurrent experiments
    optimization_time_limit=240.,  # set the time limit for the optimization process
    compute_time_limit=480,  # set the compute time limit (sum of execution time on all machines)
    total_max_jobs=100,  # set the maximum number of experiments for the optimization. 
     
    # min_iteration_per_job=15000,  # minimum number of iterations per experiment, till early stopping
    max_iteration_per_job=150000,  # maximum number of iterations per experiment
    save_top_k_tasks_only =5,
)


optimizer.set_report_period(1)  # setting the time gap between two consecutive reports
optimizer.start_locally()  
optimizer.wait()  # wait until process is done
optimizer.stop()

```

## Training Script
```
from ultralytics import YOLO
from clearml import Task
import tensorboard


task = Task.init(project_name="Proj", task_name="Proj_task-1")
model_variant ="yolov8n"
task.set_parameter("model_variant", model_variant)


model = YOLO('yolov8n.yaml').load(f'{model_variant}.pt')


yaml_config_path ='/data/yolo.yaml'
split=''
val =True
epochs=10
exist_ok= True
batch =16
resume = True
imgsz =640


args =dict(data=yaml_config_path,epochs=epochs,imgsz=imgsz, split =split, val=val,exist_ok=exist_ok,batch=batch, resume=resume)
task.connect(args)
print(f"\n  ********* Args: {args} **********\n")
# Use the model
model.train(**args)  # train the model
task.close()

```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Our friend from ClearML might know more about this. cc @thepycoder

**Comment by victormylle** [comment]
Did you find how to fix this? I am having the same error. When I pass an empty array of hyperparameters that need to be tuned, it works correctly (like the initial training run). When hyperparameters are added, it gives this error.

**Comment by glenn-jocher** [comment]
@victormylle yes, I was able to find a solution to this issue. It seems that when you pass an empty array of hyperparameters, the training run works correctly. However, when you add hyperparameters, it throws an error.

To fix this, you can manually copy the task and change the hyperparameter you want to modify. This workaround should allow you to run the training with the desired hyperparameters without encountering the error.

Please let me know if you have any further questions or need any additional assistance!

**Comment by vignesh-Ag** [comment]
> Did you find how to fix this? I am having the same error. When I pass an empty array of hyperparameters that need to be tuned, it works correctly (like the initial training run). When hyperparameters are added, it gives this error. Edit: Copying the task manually and changing a hyperparameter does work.

Nope, I am using what @glenn-jocher suggested. However, the workaround would involve searching the space manually instead of using optimization algorithm. So, for future purpose, if you could rectify the issue, that would be great.
