### ISSUE TITLE
Ray Tuning "shared" and "persistent" cache.

### ISSUE THREAD

**Issue by ExtReMLapin** [ultralytics/ultralytics#2689]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Persistent ram cache for concurrent/sequentials experiments when finetuning with Ray Tune would be great.

Requested here for yolov5 (for genetic evolve)

https://github.com/ultralytics/yolov5/issues/10796
https://github.com/ultralytics/yolov5/issues/10889

The idea would be to stop wasting time recaching the whole dataset in ram after each experiment.
What would be also even better is to let multiple concurrent experiments share the cache so running the tunning on 4 gpu would not take 4 time as much ram as one. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@ExtReMLapin that would be nice. Would you like to submit a PR for this?

**Comment by ExtReMLapin** [comment]
I might be able to give a try on the persistent cache in a week or two, next week's going to be busy.

As for the shared one between multiple Ray trials, I fear that's beyond my skills (didn't try yet tho)

**Comment by glenn-jocher** [comment]
@ExtReMLapin thank you for your willingness to contribute! Your idea for the persistent cache sounds interesting and could potentially save a lot of time during experiments. If you have any questions or need any assistance, please don't hesitate to ask. For the shared cache, we understand that it may require more advanced skills, but if anyone in the community is interested and capable of tackling this, we would certainly welcome a PR.

**Comment by ExtReMLapin** [comment]
As an update on this I do not have the time to work on it and I have no visibility on any "free time" in our planned workload in the next weeks at the office, if anyone want to contribute, feel free to do it

**Comment by pderrenger** [comment]
@ExtReMLapin thank you for the update, we appreciate your willingness to contribute. If anyone in the community is interested in taking on this feature, we would be grateful for their contribution. If you have any questions or ideas in the future, please feel free to reach out.
