### ISSUE TITLE
yolov8-p2 and yolov8 head using   "C2f",  why yolov8-p6 using "C2"

### ISSUE THREAD

**Issue by minwim** [ultralytics/ultralytics#2691]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

in yolov8.yamal,
head:

**# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, **C2f**, [512]]  # 12**

but in yolov8-p6

head
  _- [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 8], 1, Concat, [1]]  # cat backbone P5
  - [-1, 3, **C2**, [768, False]]  # 14_

**Comment by glenn-jocher** [comment]
@minwim that's a good question! I'm experimenting with both right now, but it appears we get better performance with C2f in the P6 head also...
