### ISSUE TITLE
bounding box inconsistent scaling issue found in images with different dimensions

### ISSUE THREAD

**Issue by WenjinFu** [ultralytics/ultralytics#2692]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Validation, Detection

### Bug

When I used my trained YOLOV8 model predict on the image resolution 1024 x 682 images I got the result images below: 
![image](https://github.com/ultralytics/ultralytics/assets/57229263/adbaca58-3c36-468d-93cc-721c326fac03)
<img src="https://github.com/ultralytics/ultralytics/assets/57229263/e9f93aa4-5058-4790-bfc7-e71cd1795322"  style="zoom:33%;" />
The classification are all correct, but the bounding box seems to scale in the prediction.
When I predict on the 2592 x 2048 images, the classification and bounding box seems to be correct as shown in the images below.
![image](https://github.com/ultralytics/ultralytics/assets/57229263/1bf46a76-0082-470f-8b66-554a408ab493)
![image](https://github.com/ultralytics/ultralytics/assets/57229263/dd4b27ea-e619-47a7-89b3-bb9756eb2ad5)

I don't know what I was doing wrong, since all of the higher resolution boxes are correct, the training process should be correct and the issue is the bbox scaling.
Really need help fixing this issue, have been stuck on this for whole day and had hard time fixing it. Thanks a lot! 
![0094EF71](https://github.com/ultralytics/ultralytics/assets/57229263/3a7c8eb8-e5af-4e1f-a9f9-c7bee9d469cb)
![00955F80](https://github.com/ultralytics/ultralytics/assets/57229263/e1b2225d-d2e2-4b77-886e-a66480bc0921)

### Minimal Reproducible Example

![image](https://github.com/ultralytics/ultralytics/assets/57229263/9144378d-db63-4b5e-ad46-88fcbe0be9c3)
Not sure if this part messing with bounding boxes

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by WenjinFu** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/57229263/31025573-cae2-40e0-96c8-e24ec26dfcbd)
![image](https://github.com/ultralytics/ultralytics/assets/57229263/dc500a08-21c6-4cab-9b33-6ead390962c3)
Here are the codes I used to plot those images. By the way, I don't think it's image resolution causing the problem. 
![image](https://github.com/ultralytics/ultralytics/assets/57229263/f759d6ee-984f-4ebc-9076-3ef2e708b838)
The images above in red circle has 1024x682 resolution and all have probelm of previous mentioned bounding box scaling issues. But the images above in blue circle has 2592x2048 resolutions doesn't have the bounding box scaling issue. They are all predicted together. Even if I resize the image in 1024x682 resolution, the bounding box is still problematic. Please help to see what's going on? Feeling it's so weird, lol

**Comment by WenjinFu** [comment]
Problem solved! Founding that my height and width in my COCO format label file are all incorrect... Someone must labeled them wrong, lol

**Comment by glenn-jocher** [comment]
@WenjinFu, thank you for your update! We're glad to hear that you were able to identify the issue causing the bounding box scaling. It's always rewarding to find a solution, and we're happy to have been a part of your journey with YOLOv8. Please feel free to reach out if you encounter any other issues or have any more questions.
