### ISSUE TITLE
Precision and Recall Value not matching the Confusion Matrix

### ISSUE THREAD

**Issue by Adi11cr7** [ultralytics/ultralytics#2693]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I ran validation on my test set and got the following results with **P=0.72 and R=0.594:** whereas if I calculate the precision and recall from the confusion matrix I am getting **P=0.976 and R=0.55**. **I used conf=0.1 and iou=0.1**. What is the reason for this.
<img width="684" alt="Screenshot 2023-05-18 161743" src="https://github.com/ultralytics/ultralytics/assets/71431299/81b8c934-31d8-4ef5-b8cd-7ac397eac708">

![confusion_matrix](https://github.com/ultralytics/ultralytics/assets/71431299/07c91201-0112-455b-9db4-872862ef8d0a)

**Comment by Adi11cr7** [comment]
@glenn-jocher You mentioned [here](https://github.com/ultralytics/yolov5/issues/8039#issuecomment-1145930854) that mAP is an absolute metric. But my mAP@.5 increases if I reduce the confidence threshold

**Comment by glenn-jocher** [comment]
@Adi11cr7 ah yes, this is because true mAP must be computed at conf=0.0.

We compute at conf=0.001 for faster speed and minimal difference, but technically any values higher than conf=0.0 are invalid.
