### ISSUE TITLE
Question about YOLOV8 model output after converted to TF (saved_model)

### ISSUE THREAD

**Issue by AI-Passionner** [ultralytics/ultralytics#2694]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Recently I used YOLOV8 for my object detection project. The number of classes is 14. 
The YOLOV8 Torch model works perfectly. However, I need to convert TF-saved_model for prediction. The tf model output is (1, 18,  5374). I know the first element is batch-size, the second one is 4 (x, y, w, h) + 14 (14 class probability) and the last one is the number of all detected boxes. But I remember that YOLO5 actually has (4 +1 + 14) for the second element, where the `1` here means the confidence that the box has an object in it. 
My first question is whether YOLOV8 removed this probability and combined it with the other 14 probabilities. 
My second question is that whether I need to run softmax on the 14 probabilities to get each class and its confidence score. Because those 14 class probability is very small, e-7~ e-9. 

Thanks.

**Comment by glenn-jocher** [comment]
@AI-Passionner hello! In YOLOv8, the confidence score is included in the 14 probabilities, so there is no separate confidence score. As for your second question, it depends on the post-processing method you are using. If you are using NMS (non-maximum suppression) to filter out overlapping boxes, then you do not need to run softmax on the class probabilities. However, if you are using a different post-processing method, you may need to run softmax to get each class and its confidence score.
