### ISSUE TITLE
How to Extract Mask Only Region in YOLOv8

### ISSUE THREAD

**Issue by ImSuMyatNoe** [ultralytics/ultralytics#2695]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would like to extract the mask only region in YOLOv8. How can I do this?

**Comment by AyushExel** [comment]
You can get the masks from results objects as mentioned here - https://docs.ultralytics.com/modes/predict/#masks .
Also, you can also get segment points and extract the masks.
