### ISSUE TITLE
face recognition

### ISSUE THREAD

**Issue by oussaifi-majdi** [ultralytics/ultralytics#2702]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i want to use yolov8 face to detect faces in image and after that i want to recognize the image in this face 
my code for detection is :
from ultralytics import YOLO
from ultralytics.yolo.v8.detect.predict import DetectionPredictor
import cv2
model = YOLO(r'C:\Users\Lenovo\Desktop\projtic\yoloface\face-detection-yolov8\yolov8n-face.pt')
results = model.predict(source=r'C:\Users\Lenovo\PycharmProjects\oussaifi.jpg', show=True)
print(results)

so my problem is how i can use the algorithme of recognition with yolov8

**Comment by oussaifi-majdi** [comment]
Thank you for answering quickly ,
I am very interested in the use of yolov8 with the yolov8 face model for the detection of faces but my problem is how to take the vectors from the result of yolov8 to compare with the vectors of the images in the database to know the face

**Comment by brianlmerritt** [comment]
> Thank you for answering quickly , I am very interested in the use of yolov8 with the yolov8 face model for the detection of faces but my problem is how to take the vectors from the result of yolov8 to compare with the vectors of the images in the database to know the face

In case this helps https://kean-chan.medium.com/real-time-facial-recognition-with-pytorch-facenet-ca3f6a510816 
I found your issue looking for the same thing, and I think this could be an answer

**Comment by glenn-jocher** [comment]
@brianlmerritt, glad to hear you're exploring YOLOv8 for face detection! 😊 For the face recognition part, after detecting faces with YOLOv8, you can use a model like FaceNet to extract embeddings. These embeddings are essentially the vectors you're interested in. You can then compare these embeddings with those of faces in your database using cosine similarity or Euclidean distance to identify the face.

Here's a quick example on how you might proceed after getting the face detections:

```python
from facenet_pytorch import MTCNN, InceptionResnetV1
import torch

# Initialize the models
mtcnn = MTCNN(image_size=160)
resnet = InceptionResnetV1(pretrained='vggface2').eval()

# Assuming `faces` is a list of cropped face images from YOLOv8 detections
face_tensors = [mtcnn(face) for face in faces]
embeddings = torch.stack([resnet(face_tensor.unsqueeze(0)) for face_tensor in face_tensors])

# `embeddings` now contains the vectors you can compare with your database
```

This is a simplified example, and you'll need to handle the database comparison logic based on your specific requirements. The link you shared is indeed a good resource for understanding the workflow in more detail. Keep experimenting, and feel free to reach out if you have more questions!
