### ISSUE TITLE
How to get multiple results in Python?

### ISSUE THREAD

**Issue by SexySteak** [ultralytics/ultralytics#2705]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

```
while True:
    ret, frame = cap.read()
    if not ret:
        break
    results = model.predict(source=frame, conf=0.8)
    for result in results:
        for bbox in result.boxes.xyxy:
            x1, y1, x2, y2 = bbox[0].item(), bbox[1].item(), bbox[2].item(), bbox[3].item()
            center_x, center_y = (x1 + x2) / 2, (y1 + y2) / 2
            centers.append((int(center_x), int(center_y)))
    for i in range(1, len(centers)):
        cv2.line(frame, centers[i - 1], centers[i], color, thickness)
    out.write(frame)
```

Here is my code. I use OpenCV to draw the track of the object. However, sometimes YOLOv8 would predict multiple results. How to draw the tracks of multiple results?

**Comment by glenn-jocher** [comment]
@SexySteak hello! Thank you for using YOLOv8. To draw multiple tracks for each prediction, you can modify the outer loop to loop through each prediction in `results`. Then, for each prediction, you can get the bounding box coordinates from `result.boxes.xyxy` and draw the corresponding track using the `cv2.line` function. I hope this helps! Let me know if you have any further questions.
