### ISSUE TITLE
Is there a way to specify the classes for detection for pre-trained RT-DETR?

### ISSUE THREAD

**Issue by JordanCahill** [ultralytics/ultralytics#2707]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

So for YOLOv8 I know that you can specify the classes you'd like to detect by setting the classes flag, like so:

`results = model.predict(source="sample.png", classes=[0,1,2])`

And with the torchvision models you can set:

`model.classes = [0, 1, 2]`

But neither of these work for RT-DETR, I'm just wondering if there's anything similar? Thanks!

**Comment by glenn-jocher** [comment]
@Laughing-q I thought class filtering was inherited from BasePredictor class, but it seems like no from the post above.

**Comment by Laughing-q** [comment]
@glenn-jocher @JordanCahill yeah our class filtering is inside nms but since RT-DETR does not need nms so this feature was not inherited from BasePredictor.

**Comment by Laughing-q** [comment]
@JordanCahill @glenn-jocher made a PR here to support this feature. #2748

**Comment by glenn-jocher** [comment]
@Laughing-q great! Merging PR now for 8.0.106

**Comment by Laughing-q** [comment]
@JordanCahill hi, now RT-DETR also supports `classes`, please update the package and test. :)
Closing the issue now, please feel free to reopen it if the latest package does not work to you. :)
