### ISSUE TITLE
size is not a valid key. Similar keys: ['visualize']

### ISSUE THREAD

**Issue by kadirnar** [ultralytics/ultralytics#271]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Detection codes are working. But when I want to add it to a different library it gives this error. Can you please fix this?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by kadirnar** [comment]
The reason for this error could be:
```
model(frame, size=640)
```
No video support?
```
  File "/home/kadir/miniconda3/envs/torchyolo/lib/python3.8/site-packages/ultralytics/yolo/data/dataloaders/stream_loaders.py", line 171, in __init__
    raise FileNotFoundError(f'{p} does not exist')
[[[174 126  91]
  [174 126  91]
  [174 126  91]
  ...

**Comment by AyushExel** [comment]
@kadirnar I think the error msg is accurate. `size` is not a key. please check docs for all available options https://docs.ultralytics.com/config/
probably you meant imgsz?

**Comment by kadirnar** [comment]
> @kadirnarHata mesajının doğru olduğunu düşünüyorum. `size`bir anahtar değildir. lütfen mevcut tüm seçenekler için belgelere bakın https://docs.ultralytics.com/config/ muhtemelen imgsz demek istediniz?

Yes I know. But the error messages are hard to understand. And no numpy image support. Does it only work for str?

**Comment by kadirnar** [comment]
And why is there no device parameter for detection? I couldn't find documentation either.

**Comment by AyushExel** [comment]
> > @kadirnarHata mesajının doğru olduğunu düşünüyorum. `size`bir anahtar değildir. lütfen mevcut tüm seçenekler için belgelere bakın https://docs.ultralytics.com/config/ muhtemelen imgsz demek istediniz?
> 
> Yes I know. But the error messages are hard to understand. And no numpy image support. Does it only work for str?

Thanks for the feedback. The error msg is not manually wirtten. It uses a string matching algorithm that suggests the valid config key that atleast 50% similar to the wrong key you enter. That algorithm found `visualize` to be most similar to `size`.
Please let me know if you have a better solution in mind..
As for numpy and PIL inference support, that'll be added later this week.

**Comment by AyushExel** [comment]
> And why is there no device parameter for detection? I couldn't find documentation either.

It should use the device on which the model is. If its not then there's a bug.

**Comment by kadirnar** [comment]
> > And why is there no device parameter for detection? I couldn't find documentation either.
> 
> It should use the device on which the model is. If its not then there's a bug.

Thank you. It is difficult to follow developments. Are you considering releasing Relases?

**Comment by AyushExel** [comment]
Yes a release with a few fixes have been just pushed. You can upgrade using `pip install --upgrade ultralytics `..
We expect to push rapid releases for a few days until this repo gets pretty stable. Then we'll move to weekly releases with better release notes

**Comment by kadirnar** [comment]
> Evet, birkaç düzeltme içeren bir sürüm yayınlandı. Kullanarak yükseltme yapabilirsiniz `pip install --upgrade ultralytics `.. Bu depo oldukça kararlı hale gelene kadar hızlı sürümleri birkaç gün zorlamayı umuyoruz. Ardından, daha iyi sürüm notları içeren haftalık sürümlere geçeceğiz

https://github.com/ultralytics/ultralytics/releases ?

**Comment by AyushExel** [comment]
Pip (pypi) releases not GitHub releases..

**Comment by jitaxis** [comment]
> > > @kadirnarHata mesajının doğru olduğunu düşünüyorum. `size`bir anahtar değildir. lütfen mevcut tüm seçenekler için belgelere bakın https://docs.ultralytics.com/config/ muhtemelen imgsz demek istediniz?
> > 
> > 
> > Yes I know. But the error messages are hard to understand. And no numpy image support. Does it only work for str?
> 
> Thanks for the feedback. The error msg is not manually wirtten. It uses a string matching algorithm that suggests the valid config key that atleast 50% similar to the wrong key you enter. That algorithm found `visualize` to be most similar to `size`. Please let me know if you have a better solution in mind.. As for numpy and PIL inference support, that'll be added later this week.

Are you able to let use know when the numpy/PIL support is added and if this requires a different way of providing it to the predict function.
