### ISSUE TITLE
The predicted image can be saved to desired location?

### ISSUE THREAD

**Issue by FONG1234** [ultralytics/ultralytics#2711]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Every time, after I done prediction, the image will be saved to a location in the ultralytics folder (ultralytics\runs\detect\predict1). Can I selected the desired location to save the predicted image?

![image](https://github.com/ultralytics/ultralytics/assets/132126352/8e642c85-7420-4688-abe0-2904354398e9)

Thank You.

**Comment by glenn-jocher** [comment]
@FONG1234 yes you can use `project` and `name` arguments to save to PROJECT/NAME directory.
