### ISSUE TITLE
training logs

### ISSUE THREAD

**Issue by miscedence12** [ultralytics/ultralytics#2713]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Will you release the training logs in the future? Thanks!

**Comment by glenn-jocher** [comment]
Hello @miscedence12! Thank you for your interest in YOLOv8. Currently, we do not have any plans to release the training logs publicly. However, if you are encountering any issues during training, please feel free to provide as much information as possible, including any error messages, and we will do our best to assist you in resolving the issue. Let us know if you have any other questions.
