### ISSUE TITLE
Output prediction result with error in validation or test

### ISSUE THREAD

**Issue by darouwan** [ultralytics/ultralytics#2715]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

In my industry practice, even the IOU is low sometimes, and the prediction result is regarded as FALSE, the prediction result is still reasonable because sometimes the labelled ground truth is not so accurate. It's important to show the actual bad sample images to users to analysis the root cause. Users may need to know the details of false negative or false positive cases. 

So, I suggest adding the option to show the wrong result of the images. 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@darouwan thank you for your suggestion to add an option to show the wrong prediction results of the test images. We appreciate your input and will consider this feature for future updates to YOLOv8. This could be a useful tool in the analysis of false negative or false positive cases. As always, contributions from the community are welcome and we appreciate your willingness to submit a PR. Thank you for using YOLOv8!

**Comment by darouwan** [comment]
I have create the PR in #2867

**Comment by glenn-jocher** [comment]
@darouwan, thank you for your contribution and for creating the PR in issue #2867. We appreciate your efforts to improve YOLOv8 and we will review your changes as soon as possible. Please note that we have a rigorous code review process to ensure the stability and reliability of the code, therefore it may take some time before we merge your PR. Once again, thank you for your contribution and for helping to make YOLOv8 better!
