### ISSUE TITLE
Trying different learning rate scheduler for YOLOv8

### ISSUE THREAD

**Issue by DerekHuynh98** [ultralytics/ultralytics#2721]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi everyone,

I am trying to incorporate different learning rate schedulers for yolov8 segmentation. As of now I have tried two default ones which are linear and cosinelr via default.yaml file. Cosine lr seems to work better and with lower learning rate I managed to get rid of overfitting, but now the validation loss seems to plateau really early, so I attempt to use other schedulers to see what happen. Can anyone show me how I can use steplr scheduler, or cycliclinglr scheduler? 

Thanks in advance!

**Comment by glenn-jocher** [comment]
@DerekHuynh98 hi there,

Thank you for reaching out and for using YOLOv8 for your project. 

To incorporate the StepLR and CyclicLR scheduler, you can modify the scheduler parameters in the `default.yaml` file. For the StepLR scheduler, you can set the `name` parameter to `StepLR` and adjust the `step_size` and `gamma` parameters as desired. For the CyclicLR scheduler, you can set the `name` parameter to `CyclicLR` and adjust the `base_lr`, `max_lr`, `step_size_up`, `step_size_down`, and `mode` parameters as desired.

Please keep in mind that different schedulers may require different hyperparameters to achieve the best performance for your specific use case, so don't hesitate to experiment with different settings.

I hope this helps. Let me know if you have any additional questions or concerns.

Best regards,
Glenn Jocher

**Comment by DerekHuynh98** [comment]
@glenn-jocher Hi Glenn, 

Thanks for your response. I've adjusted those parameters as you recommended, however I'm still not sure how I can set the starting learning rate for both StepLR and CyclicLR, is it the lr0? Futhermore, when I include the gamma = 0.1, does it override the lrf in the default.yaml file?

Kind regards,
Derek

**Comment by glenn-jocher** [comment]
@DerekHuynh98 hi Derek,

Thanks for following up. In StepLR, the starting learning rate is the initial value set in your `base_lr` parameter. The learning rate will then decrease by a factor of `gamma` every `step_size` epochs. For CyclicLR, the starting learning rate is defined by the `base_lr` parameter, while the maximum learning rate is defined by the `max_lr` parameter.

Regarding your question about `lr0`, unfortunately, there's no such parameter in StepLR or CyclicLR. The `lr0` parameter is specific to the learning rate scheduling implemented in YOLOv5 and not in YOLOv8.

Regarding the `gamma` parameter, it does not override the `lrf` in the default.yaml file. Instead, it multiplies the current learning rate by `gamma` every `step_size` epochs. 

Regarding the learning rate shape you observed, it seems that the learning rate did not decrease at `step_size` epochs as expected, as the shape should have been a smooth staircase. As for possible reasons why it did not happen, my first guess would be to check if the value of `step_size` is correct. 

Please let us know if you have any further questions or if there's anything else we can assist you with.

Best regards,
Glenn Jocher.

**Comment by yazansayed** [comment]
I don't seem to get this to work, I installed `ultralytics` using the source code, edited the file at `/myhome/ultralytics/ultralytics/cfg/default.yaml` to be:  
<details>
  <summary>default.yaml</summary>
  

  ```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# Default training settings and hyperparameters for medium-augmentation COCO training

task: detect  # (str) YOLO task, i.e. detect, segment, classify, pose
mode: train  # (str) YOLO mode, i.e. train, val, predict, export, track, benchmark

# Train settings -------------------------------------------------------------------------------------------------------
model:  # (str, optional) path to model file, i.e. yolov8n.pt, yolov8n.yaml
data:  # (str, optional) path to data file, i.e. coco128.yaml
epochs: 100  # (int) number of epochs to train for
patience: 50  # (int) epochs to wait for no observable improvement for early stopping of training
batch: 16  # (int) number of images per batch (-1 for AutoBatch)
imgsz: 640  # (int | list) input images size as int for train and val modes, or list[w,h] for predict and export modes
save: True  # (bool) save train checkpoints and predict results
save_period: -1 # (int) Save checkpoint every x epochs (disabled if < 1)
cache: False  # (bool) True/ram, disk or False. Use cache for data loading
device:  # (int | str | list, optional) device to run on, i.e. cuda device=0 or device=0,1,2,3 or device=cpu
workers: 8  # (int) number of worker threads for data loading (per RANK if DDP)
project:  # (str, optional) project name
name:  # (str, optional) experiment name, results saved to 'project/name' directory
exist_ok: False  # (bool) whether to overwrite existing experiment
pretrained: True  # (bool | str) whether to use a pretrained model (bool) or a model to load weights from (str)
optimizer: auto  # (str) optimizer to use, choices=[SGD, Adam, Adamax, AdamW, NAdam, RAdam, RMSProp, auto]
verbose: True  # (bool) whether to print verbose output
seed: 0  # (int) random seed for reproducibility
deterministic: True  # (bool) whether to enable deterministic mode
single_cls: False  # (bool) train multi-class data as single-class
rect: False  # (bool) rectangular training if mode='train' or rectangular validation if mode='val'
cos_lr: False  # (bool) use cosine learning rate scheduler
StepLR: True
close_mosaic: 10  # (int) disable mosaic augmentation for final epochs (0 to disable)
resume: False  # (bool) resume training from last checkpoint
amp: True  # (bool) Automatic Mixed Precision (AMP) training, choices=[True, False], True runs AMP check
fraction: 1.0  # (float) dataset fraction to train on (default is 1.0, all images in train set)
profile: False  # (bool) profile ONNX and TensorRT speeds during training for loggers
freeze: None  # (int | list, optional) freeze first n layers, or freeze list of layer indices during training
# Segmentation
overlap_mask: True  # (bool) masks should overlap during training (segment train only)
mask_ratio: 4  # (int) mask downsample ratio (segment train only)
# Classification
dropout: 0.0  # (float) use dropout regularization (classify train only)

# Val/Test settings ----------------------------------------------------------------------------------------------------
val: True  # (bool) validate/test during training
split: val  # (str) dataset split to use for validation, i.e. 'val', 'test' or 'train'
save_json: False  # (bool) save results to JSON file
save_hybrid: False  # (bool) save hybrid version of labels (labels + additional predictions)
conf:  # (float, optional) object confidence threshold for detection (default 0.25 predict, 0.001 val)
iou: 0.7  # (float) intersection over union (IoU) threshold for NMS
max_det: 300  # (int) maximum number of detections per image
half: False  # (bool) use half precision (FP16)
dnn: False  # (bool) use OpenCV DNN for ONNX inference
plots: True  # (bool) save plots during train/val

# Prediction settings --------------------------------------------------------------------------------------------------
source:  # (str, optional) source directory for images or videos
show: False  # (bool) show results if possible
save_txt: False  # (bool) save results as .txt file
save_conf: False  # (bool) save results with confidence scores
save_crop: False  # (bool) save cropped images with results
show_labels: True  # (bool) show object labels in plots
show_conf: True  # (bool) show object confidence scores in plots
vid_stride: 1  # (int) video frame-rate stride
stream_buffer: False  # (bool) buffer all streaming frames (True) or return the most recent frame (False)
line_width:   # (int, optional) line width of the bounding boxes, auto if missing
visualize: False  # (bool) visualize model features
augment: False  # (bool) apply image augmentation to prediction sources
agnostic_nms: False  # (bool) class-agnostic NMS
classes:  # (int | list[int], optional) filter results by class, i.e. classes=0, or classes=[0,2,3]
retina_masks: False  # (bool) use high-resolution segmentation masks
boxes: True  # (bool) Show boxes in segmentation predictions

# Export settings ------------------------------------------------------------------------------------------------------
format: torchscript  # (str) format to export to, choices at https://docs.ultralytics.com/modes/export/#export-formats
keras: False  # (bool) use Kera=s
optimize: False  # (bool) TorchScript: optimize for mobile
int8: False  # (bool) CoreML/TF INT8 quantization
dynamic: False  # (bool) ONNX/TF/TensorRT: dynamic axes
simplify: False  # (bool) ONNX: simplify model
opset:  # (int, optional) ONNX: opset version
workspace: 4  # (int) TensorRT: workspace size (GB)
nms: False  # (bool) CoreML: add NMS

# Hyperparameters ------------------------------------------------------------------------------------------------------
lr0: 0.01  # (float) initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
lrf: 0.01  # (float) final learning rate (lr0 * lrf)
base_lr: 0.0001
gamma: 0.1
step_size: 1
momentum: 0.937  # (float) SGD momentum/Adam beta1
weight_decay: 0.0005  # (float) optimizer weight decay 5e-4
warmup_epochs: 3.0  # (float) warmup epochs (fractions ok)
warmup_momentum: 0.8  # (float) warmup initial momentum
warmup_bias_lr: 0.1  # (float) warmup initial bias lr
box: 7.5  # (float) box loss gain
cls: 0.5  # (float) cls loss gain (scale with pixels)
dfl: 1.5  # (float) dfl loss gain
pose: 12.0  # (float) pose loss gain
kobj: 1.0  # (float) keypoint obj loss gain
label_smoothing: 0.0  # (float) label smoothing (fraction)
nbs: 64  # (int) nominal batch size
hsv_h: 0.015  # (float) image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # (float) image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # (float) image HSV-Value augmentation (fraction)
degrees: 0.0  # (float) image rotation (+/- deg)
translate: 0.1  # (float) image translation (+/- fraction)
scale: 0.5  # (float) image scale (+/- gain)
shear: 0.0  # (float) image shear (+/- deg)
perspective: 0.0  # (float) image perspective (+/- fraction), range 0-0.001
flipud: 0.0  # (float) image flip up-down (probability)
fliplr: 0.5  # (float) image flip left-right (probability)
mosaic: 1.0  # (float) image mosaic (probability)
mixup: 0.0  # (float) image mixup (probability)
copy_paste: 0.0  # (float) segment copy-paste (probability)

# Custom config.yaml ---------------------------------------------------------------------------------------------------
cfg:  # (str, optional) for overriding defaults.yaml

# Tracker settings ------------------------------------------------------------------------------------------------------
tracker: botsort.yaml  # (str) tracker type, choices=[botsort.yaml, bytetrack.yaml]

  ```
</details>  
and here's the learning rate csv from wandb  

```
"Step","pr11 - lr/pg1","pr11 - lr/pg1__MIN","pr11 - lr/pg1__MAX"
"1","0.0006540880503144654","0.0006540880503144654","0.0006540880503144654"
"2","0.0013142169811320753","0.0013142169811320753","0.0013142169811320753"
"3","0.0019677459119496854","0.0019677459119496854","0.0019677459119496854"
"4","0.0019703","0.0019703","0.0019703"
"5","0.0019703","0.0019703","0.0019703"
"6","0.0019604","0.0019604","0.0019604"
"7","0.0019505","0.0019505","0.0019505"
"8","0.0019406","0.0019406","0.0019406"
"9","0.0019306999999999998","0.0019306999999999998","0.0019306999999999998"
"10","0.0019207999999999999","0.0019207999999999999","0.0019207999999999999"
```

**Comment by glenn-jocher** [comment]
@yazansayed hello, 

From your description and the file, it looks like settings in your default.yaml file might be causing the problem. 

It is important to make sure that the various paths and settings in, e.g., the model, the data, project name, and source, are appropriately set for your specific use case. It looks like they might still contain the placeholders instead of the specific values needed for your training set and environment. 

Also, for the learning rate, make sure that it is set correctly and in a range suitable for your training. The 'lr0' field referring to the initial learning rate and 'lrf' referring to the final learning rate may need adjustment based on your model and data. 

I hope this points you in the right direction. Feel free to provide additional details if the issue persists. 

Best regards.

**Comment by yazansayed** [comment]
@glenn-jocher Thanks for your response, the model I'm using is `yolov8m-seg` , and the values I selected for base_lr, gamma and step_size are just for testing, as for lr0 and lrf I didn't change them because of [your answer](https://github.com/ultralytics/ultralytics/issues/2721#issuecomment-1556395258) 
>Regarding your question about lr0, unfortunately, there's no such parameter in StepLR or CyclicLR. The lr0 parameter is specific to the learning rate scheduling implemented in YOLOv5 and not in YOLOv8.


should i change `lr0` too ? if so then why set `base_lr` for StepLR in the first place ?

**Comment by ahmedfarouk99** [comment]
@DerekHuynh98 hey derek and sorry for bothering
did you managed to use Steplr or CyclicLR ?
because when i include any of them in the modified.yaml file it raise an error : no argument called steplr or cycliclr or gamma

**Comment by glenn-jocher** [comment]
Hi @ahmedfarouk99,

No worries at all, happy to help! 😊 It seems there might have been a misunderstanding regarding the implementation of learning rate schedulers in YOLOv8. Currently, YOLOv8 supports a default linear and cosine learning rate scheduler directly through the `default.yaml` configuration, but custom schedulers like StepLR or CyclicLR aren't directly supported through simple YAML configuration changes.

To use different schedulers like StepLR or CyclicLR, you would typically need to modify the training script itself, where the scheduler is defined and applied. This involves a bit more in-depth customization of the code.

For now, if you're looking to experiment with different learning rate schedules, I'd recommend sticking with the provided options or diving into the code to implement custom scheduler logic. 

Hope this clarifies things! Let me know if you have any more questions.

**Comment by ahmedfarouk99** [comment]
@glenn-jocher so it is not just adding "StepLR" &" gamma" & "step_size" as @yazansayed did above in the default.yaml file?
or i have to modify other things?
thanks in advance

**Comment by glenn-jocher** [comment]
@ahmedfarouk99 hi there! 😊

Indeed, adding "StepLR", "gamma", and "step_size" directly to the `default.yaml` won't automatically apply those schedulers in YOLOv8, as the training script itself needs to be modified to recognize and implement these changes.

For custom learning rate schedulers like StepLR or CyclicLR, you'd need to dive into the code where the optimizer and scheduler are set up, and manually integrate your desired scheduler.

Thanks for reaching out, and don't hesitate to ask if you have more questions!

**Comment by ahmedfarouk99** [comment]
@glenn-jocher thank you for your help and understanding 😄 
i found the definition of cosine learning rate and linear learning rate in "trainer.py" file, and i modified it to include cyclic LR, but i got stacked in how to use and include this modified "trainer.py" file in training my custom dataset.

**Comment by ahmedfarouk99** [comment]
@glenn-jocher can you help me in the previous question?

**Comment by glenn-jocher** [comment]
@ahmedfarouk99 hi there! 😊

Great job on customizing the `trainer.py` file for the cyclic LR! To use your modified `trainer.py` in training with your custom dataset, you just need to make sure your dataset is correctly set up in a YAML file (let's say `custom_dataset.yaml`), and you're running the Ultralytics training command from the directory containing your modified `trainer.py`. It should automatically pick up your changes during training.

If your custom dataset YAML and other configurations are all set, you'd typically start training like this:

```bash
python path/to/train.py --data custom_dataset.yaml --cfg yolov8_config.yaml --weights '' --name my_custom_training
```

Just replace `path/to/train.py` with the actual path to your modified `trainer.py`, and fill in the other arguments (`--data`, `--cfg`, etc.) according to your specific setup.

Hope this helps, and happy training! 🚀

**Comment by ahmedfarouk99** [comment]
@glenn-jocher hi glenn and sorry for too many questions
i did what you said above but nothing happened nor the training starts...it just give me a new command line as i will show in the below screenshot
<img width="1205" alt="1" src="https://github.com/ultralytics/ultralytics/assets/52285797/591f51ee-eab8-468e-a7da-6b37a4dd7b9c"
i tried it two times but nothing happened
do you know why that ?

**Comment by ahmedfarouk99** [comment]
@glenn-jocher can you answer my above question

**Comment by glenn-jocher** [comment]
@ahmedfarouk99 hi there! 😊

Sorry to hear you're encountering issues. Based on your description, it seems there might be a small hiccup in executing the training command.

A common reason the command line might not proceed with training is a typo or path issue in the command itself. Let’s ensure that the command is correct and all paths specified exist.

Here’s a quick checklist:
- Verify the path to `train.py` is correctly pointing to your modified `trainer.py` (the file name might need to match exactly).
- Ensure `custom_dataset.yaml` and `yolov8_config.yaml` paths are correctly specified.
- Double-check you are in the correct directory when executing the command.

If issues persist, a detailed look at your command or any console output/error messages would be really helpful in diagnosing the problem. 

Hope this nudges you in the right direction! 🚀

**Comment by ahmedfarouk99** [comment]
@glenn-jocher sorry for bothering and my too many questions but i got stacked here.....
how can i Verify the path to train.py is correctly pointing to your modified trainer.py (the file name might need to match exactly)?
i just wrote this in my command line:
<img width="1205" alt="1" src="https://github.com/ultralytics/ultralytics/assets/52285797/591f51ee-eab8-468e-a7da-6b37a4dd7b9c"
hint:
i modified the "trainer.py" file not "train.py" file, is that correct ?
thanks in advance.

**Comment by ahmedfarouk99** [comment]
@glenn-jocher can you help me in the above question?

**Comment by glenn-jocher** [comment]
@ahmedfarouk99 hi there! 😊

No worries at all; I'm here to help! If you've modified `trainer.py` instead of `train.py`, that's absolutely fine as long as your changes are intended for the training process handled by that script.

To ensure your modified `trainer.py` is used:
1. Make sure you're running the training command from within the Ultralytics YOLO directory where your modified `trainer.py` exists.
2. The usual command references `train.py`. If you've made changes to `trainer.py`, those changes should naturally be invoked during the training process, as `train.py` often utilizes functionality within `trainer.py`.

Just a quick note: if there's no direct command pointing to `trainer.py`, it likely means that it's internally used by another script (e.g., `train.py`), and thus, your modifications should be active during training.

Hope this clears things up! Let me know if you have any other questions.

**Comment by ahmedfarouk99** [comment]
@glenn-jocher sorry but i still counter a problem that i can't solve 
![1](https://github.com/ultralytics/ultralytics/assets/52285797/68f656b8-0941-40ed-91e1-e8c9fd753888)

**Comment by glenn-jocher** [comment]
@ahmedfarouk99 hi there! 😊

Sorry to hear you're encountering issues. Based on the message you've shared, it seems there might be a specific error occurring. Unfortunately, I can't view the screenshot directly here, but I'm here to help!

Could you briefly describe the error message or issue you're facing? This information will be super helpful in guiding you to a solution. 

Don't worry, we'll get you unstuck soon!

**Comment by ahmedfarouk99** [comment]
@glenn-jocher 
![IMG_7150](https://github.com/ultralytics/ultralytics/assets/52285797/1100d734-882e-4561-a63e-83d849bee7ec)

**Comment by Maddiesgithub** [comment]
> @DerekHuynh98 hi there,
> 
> Thank you for reaching out and for using YOLOv8 for your project.
> 
> To incorporate the StepLR and CyclicLR scheduler, you can modify the scheduler parameters in the `default.yaml` file. For the StepLR scheduler, you can set the `name` parameter to `StepLR` and adjust the `step_size` and `gamma` parameters as desired. For the CyclicLR scheduler, you can set the `name` parameter to `CyclicLR` and adjust the `base_lr`, `max_lr`, `step_size_up`, `step_size_down`, and `mode` parameters as desired.
> 
> Please keep in mind that different schedulers may require different hyperparameters to achieve the best performance for your specific use case, so don't hesitate to experiment with different settings.
> 
> I hope this helps. Let me know if you have any additional questions or concerns.
> 
> Best regards, Glenn Jocher

I'm using YOLOv8 for real-time small object detection, but I'm unsure of the optimal number of epochs because I haven't determined the appropriate learning rate. Could you guide me on how to adjust the learning rate effectively?
