### ISSUE TITLE
how can i use playsound library?

### ISSUE THREAD

**Issue by 7assanx7** [ultralytics/ultralytics#2722]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

                elif c == 1 :
                    import cv2
                    import threading
                    from playsound import playsound

                    def detect_object():
                        # perform object detection here
                        # ...
                        # play the sound notification only once
                        playsound('friend.mp3')

                    # start a new thread to perform object detection
                    detection_thread = threading.Thread(target=detect_object)
                    detection_thread.start()
                    
 i want to play audio file when detect class 1 but the audio file playing multiple times at the same moment which makes it sound like an echo I tried using  time.sleep() but same problem can fix that?

**Comment by glenn-jocher** [comment]
@7assanx7 hi there! 

In your code, you are creating a new thread every time a `class 1` object is detected. This means that when multiple objects are detected within a short period of time, multiple threads are created, and thus, multiple instances of the `playsound` function are called, resulting in the audio playing multiple times.

To fix this, you can try the following:
1. Create a global variable (e.g. `is_playing`) to keep track of whether the sound is currently playing or not. 
2. Before playing the sound, check if `is_playing` is `False`. If it is `True`, it means that the sound is already playing, so you can skip playing the sound again.
3. If the sound is not playing, set `is_playing` to `True`, play the sound, and then set `is_playing` back to `False` after the sound has finished playing.

Hope this helps!

**Comment by 7assanx7** [comment]
> @7assanx7 hi there!
> 
> In your code, you are creating a new thread every time a `class 1` object is detected. This means that when multiple objects are detected within a short period of time, multiple threads are created, and thus, multiple instances of the `playsound` function are called, resulting in the audio playing multiple times.
> 
> To fix this, you can try the following:
> 
> 1. Create a global variable (e.g. `is_playing`) to keep track of whether the sound is currently playing or not.
> 2. Before playing the sound, check if `is_playing` is `False`. If it is `True`, it means that the sound is already playing, so you can skip playing the sound again.
> 3. If the sound is not playing, set `is_playing` to `True`, play the sound, and then set `is_playing` back to `False` after the sound has finished playing.
> 
> Hope this helps!
` if c == 0 :
                    import threading
                    import pygame
                    pygame.init()
                    

                    def detect_object():
                        # play the sound notification only once
                         my_sound = pygame.mixer.Sound('friend.mp3')
                         my_sound.play()
    
                    # start a new thread to perform object detection
                    detection_thread = threading.Thread(target=detect_object)
                    detection_thread.start()`
if fix the problem by using pygame library but can I play the sound once and then play it again after 10 seconds i'm tried to use flag and counter but the audio file is still playing continuously 
maybe can use FPS to play audio file after 10 FPS or after 10 detections

**Comment by glenn-jocher** [comment]
Hi @7assanx7,

Glad to hear that you have fixed the issue by using the pygame library. 

To play the sound once and then play it again after 10 seconds, you can use the `time` module to track the time elapsed since the last time the sound was played. When a `class 0` object is detected, you can check if 10 seconds have passed since the last time the sound was played. If yes, play the sound and update the last-played time. If not, skip playing the sound. You can use a global variable (e.g. `last_played_time`) to keep track of the time.

Alternatively, you can use a counter to count the number of detections, and play the sound every 10 detections. You can also use a global variable (e.g. `detection_count`) to keep track of the count.

Keep in mind that playing the sound every 10 FPS or 10 detections might not be optimal depending on the framerate and the frequency of detections. You might want to experiment with different values to find the best balance between responsiveness and annoyance.

Hope this helps!

**Comment by 7assanx7** [comment]
> Hi @7assanx7,
> 
> Glad to hear that you have fixed the issue by using the pygame library.
> 
> To play the sound once and then play it again after 10 seconds, you can use the `time` module to track the time elapsed since the last time the sound was played. When a `class 0` object is detected, you can check if 10 seconds have passed since the last time the sound was played. If yes, play the sound and update the last-played time. If not, skip playing the sound. You can use a global variable (e.g. `last_played_time`) to keep track of the time.
> 
> Alternatively, you can use a counter to count the number of detections, and play the sound every 10 detections. You can also use a global variable (e.g. `detection_count`) to keep track of the count.
> 
> Keep in mind that playing the sound every 10 FPS or 10 detections might not be optimal depending on the framerate and the frequency of detections. You might want to experiment with different values to find the best balance between responsiveness and annoyance.
> 
> Hope this helps!

thanks bro it's work

**Comment by glenn-jocher** [comment]
@7assanx7 you're welcome! I'm glad to hear that the solution works for you. Don't hesitate to reach out if you have any more questions or issues regarding YOLOv8. The community here is always happy to help out.
