### ISSUE TITLE
CBAM integration

### ISSUE THREAD

**Issue by FatmaMazen2021** [ultralytics/ultralytics#273]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Dear sir,
Thank you for sharing this great work
I have a question regarding the integration of the CBAM module. Despite being defined in ultralytics/ultralytics/nn/modules.py, I got the following error when integrating it with the small model
ultralytics/ultralytics/nn/tasks.py", line 380, in parse_model
    m = eval(m) if isinstance(m, str) else m  # eval strings
  File "<string>", line 1, in <module>
NameError: name 'CBAM' is not defined

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by VicxCreine** [comment]
I have the same problem, would you mind to tell me if you have solved it？

**Comment by lzmlzm** [comment]
> I have the same problem, would you mind to tell me if you have solved it？

You need import this function in such  code :
`from ultralytics.nn.modules import (C1, C2, C3, C3TR, SPP, SPPF, Bottleneck, BottleneckCSP, C2f, C3Ghost, C3x, Classify,
                                    Concat, Conv, ConvTranspose, Detect, DWConv, DWConvTranspose2d, Ensemble, Focus,
                                    GhostBottleneck, GhostConv, Segment,CBAM)`

**Comment by pderrenger** [comment]
@linuxer-spec thank you for your interest in integrating the CBAM module with the YOLOv8 model. To address the error you encountered, you can import the CBAM function from the ultralytics.nn.modules module. 

Here's what you can do to resolve the issue:
```
from ultralytics.nn.modules import CBAM
```

By including this import statement in your code, you should be able to utilize the CBAM module without encountering the 'NameError' you mentioned.
