### ISSUE TITLE
Zero loss when training on GPU

### ISSUE THREAD

**Issue by Abecadarian** [ultralytics/ultralytics#2731]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When training models on my NVIDIA GeForce GTX 1650 GPU, all the losses are either NaN (if amp is set to True) or zero (if amp is set to false).

An example output for training pose detection with amp=False:

New https://pypi.org/project/ultralytics/8.0.105 available  Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.87  Python-3.11.3 torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce GTX 1650, 4096MiB)
yolo\engine\trainer: task=pose, mode=train, model=yolov8m-pose.pt, data=coco8-pose.yaml, epochs=10, patience=50, batch=2, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs\pose\train

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.Conv                  [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.Conv                  [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.C2f                   [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.Conv                  [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.C2f                   [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.Conv                  [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.C2f                   [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.Conv                  [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.C2f                   [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.SPPF                  [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]
 12                  -1  2   1993728  ultralytics.nn.modules.C2f                   [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]
 15                  -1  2    517632  ultralytics.nn.modules.C2f                   [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.Conv                  [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]
 18                  -1  2   1846272  ultralytics.nn.modules.C2f                   [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.Conv                  [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]
 21                  -1  2   4207104  ultralytics.nn.modules.C2f                   [960, 576, 2]
 22        [15, 18, 21]  1   4383838  ultralytics.nn.modules.Pose                  [1, [17, 3], [192, 384, 576]]
YOLOv8m-pose summary: 320 layers, 26464462 parameters, 26464446 gradients, 81.4 GFLOPs

Transferred 517/517 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs\pose\train', view at http://localhost:6006/
optimizer: SGD(lr=0.01) with parameter groups 83 weight(decay=0.0), 93 weight(decay=0.0005), 92 bias
train: Scanning datasets\coco8-pose\labels\train.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
val: Scanning datasets\coco8-pose\labels\val.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
Plotting labels to runs\pose\train\labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to runs\pose\train
Starting training for 10 epochs...

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
       1/10      1.98G      1.279      1.146     0.2934     0.7599      1.535          7        640: 100%|██████████| 2/2 [00:13<00:00,  6.74s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.03it/s]
                   all          4         14          0          0          0          0          0          0          0          0

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
       2/10      2.04G     0.8694      1.621      0.239     0.5622      1.293          9        640: 100%|██████████| 2/2 [00:00<00:00,  2.13it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.11it/s]
                   all          4         14          0          0          0          0          0          0          0          0

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
       3/10      2.04G      1.307      3.904     0.3478        1.3      1.622          7        640: 100%|██████████| 2/2 [00:00<00:00,  2.13it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.10it/s]
                   all          4         14          0          0          0          0          0          0          0          0

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
       4/10      2.03G      1.043      3.493     0.3701     0.8256      1.628          4        640: 100%|██████████| 2/2 [00:01<00:00,  1.94it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.08it/s]
                   all          4         14          0          0          0          0          0          0          0          0

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
       5/10      2.04G     0.8282      1.689     0.2586     0.4419      1.305          3        640: 100%|██████████| 2/2 [00:00<00:00,  2.17it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.08it/s]
                   all          4         14          0          0          0          0          0          0          0          0

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
       6/10      2.03G      1.102      1.877     0.3376     0.7233      1.196         10        640: 100%|██████████| 2/2 [00:00<00:00,  2.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.11it/s]
                   all          4         14          0          0          0          0          0          0          0          0

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
       7/10      2.03G     0.9643      2.597     0.2229     0.9163      1.405          6        640: 100%|██████████| 2/2 [00:01<00:00,  2.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.11it/s]
                   all          4         14          0          0          0          0          0          0          0          0

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
       8/10      2.02G      1.134      2.922     0.4428     0.9781      1.349          6        640: 100%|██████████| 2/2 [00:00<00:00,  2.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.11it/s]
                   all          4         14          0          0          0          0          0          0          0          0

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
       9/10      2.02G      1.273      1.292     0.3256     0.7482      1.629          5        640: 100%|██████████| 2/2 [00:00<00:00,  2.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.11it/s]
                   all          4         14          0          0          0          0          0          0          0          0

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
      10/10      2.07G      1.198       1.94     0.3589      1.079      1.643          2        640: 100%|██████████| 2/2 [00:00<00:00,  2.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.10it/s]
                   all          4         14          0          0          0          0          0          0          0          0

10 epochs completed in 0.022 hours.
Optimizer stripped from runs\pose\train\weights\last.pt, 53.3MB
Optimizer stripped from runs\pose\train\weights\best.pt, 53.3MB

Validating runs\pose\train\weights\best.pt...
Ultralytics YOLOv8.0.87  Python-3.11.3 torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce GTX 1650, 4096MiB)
YOLOv8m-pose summary (fused): 237 layers, 26447596 parameters, 0 gradients, 81.0 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.13it/s]
                   all          4         14          0          0          0          0          0          0          0          0
Speed: 0.5ms preprocess, 218.4ms inference, 0.0ms loss, 0.2ms postprocess per image

### Environment

YOLO: Ultralytics YOLOv8.0.87 Python-3.10 torch 2.0.0-cu117 

OS: Windows 11

Python: 3.10

CUDA: 11.8

### Minimal Reproducible Example

An example output for training pose detection with amp=False:

New https://pypi.org/project/ultralytics/8.0.105 available  Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.87  Python-3.11.3 torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce GTX 1650, 4096MiB)
yolo\engine\trainer: task=pose, mode=train, model=yolov8m-pose.pt, data=coco8-pose.yaml, epochs=10, patience=50, batch=2, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs\pose\train

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.Conv                  [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.Conv                  [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.C2f                   [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.Conv                  [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.C2f                   [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.Conv                  [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.C2f                   [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.Conv                  [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.C2f                   [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.SPPF                  [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]
 12                  -1  2   1993728  ultralytics.nn.modules.C2f                   [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]
 15                  -1  2    517632  ultralytics.nn.modules.C2f                   [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.Conv                  [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]
 18                  -1  2   1846272  ultralytics.nn.modules.C2f                   [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.Conv                  [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]
 21                  -1  2   4207104  ultralytics.nn.modules.C2f                   [960, 576, 2]
 22        [15, 18, 21]  1   4383838  ultralytics.nn.modules.Pose                  [1, [17, 3], [192, 384, 576]]
YOLOv8m-pose summary: 320 layers, 26464462 parameters, 26464446 gradients, 81.4 GFLOPs

Transferred 517/517 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs\pose\train', view at http://localhost:6006/
optimizer: SGD(lr=0.01) with parameter groups 83 weight(decay=0.0), 93 weight(decay=0.0005), 92 bias
train: Scanning datasets\coco8-pose\labels\train.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
val: Scanning datasets\coco8-pose\labels\val.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
Plotting labels to runs\pose\train\labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to runs\pose\train
Starting training for 10 epochs...

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
       1/10      1.98G      1.279      1.146     0.2934     0.7599      1.535          7        640: 100%|██████████| 2/2 [00:13<00:00,  6.74s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.03it/s]
                   all          4         14          0          0          0          0          0          0          0          0

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
       2/10      2.04G     0.8694      1.621      0.239     0.5622      1.293          9        640: 100%|██████████| 2/2 [00:00<00:00,  2.13it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.11it/s]
                   all          4         14          0          0          0          0          0          0          0          0

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
       3/10      2.04G      1.307      3.904     0.3478        1.3      1.622          7        640: 100%|██████████| 2/2 [00:00<00:00,  2.13it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.10it/s]
                   all          4         14          0          0          0          0          0          0          0          0

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
       4/10      2.03G      1.043      3.493     0.3701     0.8256      1.628          4        640: 100%|██████████| 2/2 [00:01<00:00,  1.94it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.08it/s]
                   all          4         14          0          0          0          0          0          0          0          0

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
       5/10      2.04G     0.8282      1.689     0.2586     0.4419      1.305          3        640: 100%|██████████| 2/2 [00:00<00:00,  2.17it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.08it/s]
                   all          4         14          0          0          0          0          0          0          0          0

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
       6/10      2.03G      1.102      1.877     0.3376     0.7233      1.196         10        640: 100%|██████████| 2/2 [00:00<00:00,  2.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.11it/s]
                   all          4         14          0          0          0          0          0          0          0          0

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
       7/10      2.03G     0.9643      2.597     0.2229     0.9163      1.405          6        640: 100%|██████████| 2/2 [00:01<00:00,  2.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.11it/s]
                   all          4         14          0          0          0          0          0          0          0          0

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
       8/10      2.02G      1.134      2.922     0.4428     0.9781      1.349          6        640: 100%|██████████| 2/2 [00:00<00:00,  2.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.11it/s]
                   all          4         14          0          0          0          0          0          0          0          0

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
       9/10      2.02G      1.273      1.292     0.3256     0.7482      1.629          5        640: 100%|██████████| 2/2 [00:00<00:00,  2.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.11it/s]
                   all          4         14          0          0          0          0          0          0          0          0

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
      10/10      2.07G      1.198       1.94     0.3589      1.079      1.643          2        640: 100%|██████████| 2/2 [00:00<00:00,  2.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.10it/s]
                   all          4         14          0          0          0          0          0          0          0          0

10 epochs completed in 0.022 hours.
Optimizer stripped from runs\pose\train\weights\last.pt, 53.3MB
Optimizer stripped from runs\pose\train\weights\best.pt, 53.3MB

Validating runs\pose\train\weights\best.pt...
Ultralytics YOLOv8.0.87  Python-3.11.3 torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce GTX 1650, 4096MiB)
YOLOv8m-pose summary (fused): 237 layers, 26447596 parameters, 0 gradients, 81.0 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.13it/s]
                   all          4         14          0          0          0          0          0          0          0          0
Speed: 0.5ms preprocess, 218.4ms inference, 0.0ms loss, 0.2ms postprocess per image

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by herofahad777** [comment]
I am having the same issue
`(yolov8_custom) D:\yolov8>yolo task=detect mode=train epochs=3 data=data_custom.yaml model=yolov8m.pt imgsz=640 batch=2
Ultralytics YOLOv8.0.203  Python-3.9.18 torch-2.1.0+cu118 CUDA:0 (NVIDIA GeForce GTX 1650 Ti, 4096MiB)
engine\trainer: task=detect, mode=train, model=yolov8m.pt, data=data_custom.yaml, epochs=3, patience=50, batch=2, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train2, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\train2
Overriding model.yaml nc=80 with nc=2

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3776854  ultralytics.nn.modules.head.Detect           [2, [192, 384, 576]]
Model summary: 295 layers, 25857478 parameters, 25857462 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs\detect\train2', view at http://localhost:6006/
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed
train: Scanning D:\yolov8\train\labels.cache... 15 images, 1 backgrounds, 0 corrupt: 100%|██████████| 16/16 [00:00<?, ?
val: Scanning D:\yolov8\val\labels.cache... 5 images, 1 backgrounds, 0 corrupt: 100%|██████████| 6/6 [00:00<?, ?it/s]
Plotting labels to runs\detect\train2\labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001667, momentum=0.9) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.0005), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to runs\detect\train2
Starting training for 3 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        1/3      1.24G        nan        nan        nan         10        640: 100%|██████████| 8/8 [00:08<00:00,  1.12
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<0
                   all          6         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        2/3      1.28G        nan        nan        nan         17        640: 100%|██████████| 8/8 [00:08<00:00,  1.10
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<0
                   all          6         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        3/3      1.28G        nan        nan        nan         14        640: 100%|██████████| 8/8 [00:08<00:00,  1.10
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<0
                   all          6         17          0          0          0          0

3 epochs completed in 0.010 hours.
Optimizer stripped from runs\detect\train2\weights\last.pt, 52.0MB
Optimizer stripped from runs\detect\train2\weights\best.pt, 52.0MB

Validating runs\detect\train2\weights\best.pt...
Ultralytics YOLOv8.0.203  Python-3.9.18 torch-2.1.0+cu118 CUDA:0 (NVIDIA GeForce GTX 1650 Ti, 4096MiB)
Model summary (fused): 218 layers, 25840918 parameters, 0 gradients, 78.7 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<0
                   all          6         17          0          0          0          0
Speed: 0.6ms preprocess, 135.5ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to runs\detect\train2
 Learn more at https://docs.ultralytics.com/modes/train`

**Comment by glenn-jocher** [comment]
@herofahad777 it appears that the loss values returned during your training run are 'nan'. This is usually due to errors in your training data or, sometimes, an error in learning rate. 

Here are a few things you should check:
1. Are your class labels properly aligned with the class names in your `data_custom.yaml` file? 
2. Check your dataset for potential issues like images without annotations/empty labels, or images where the bounding boxes are outside the image dimensions. 
3. Try reducing your learning rate. In some cases 'nan' loss could be a symptom of the learning rate being too high.
4. Be sure you're not feeding in any corrupt or unreadable image files into your dataset. 

Double-checking these factors should hopefully resolve your issue.

**Comment by umairsiddique3171** [comment]
I got the same problem with same GPU and toolkit specs. Increasing the batch size to 32 resolved the issue for me.

**Comment by glenn-jocher** [comment]
@umairsiddique3171 it appears that you're encountering an issue where the model is not learning during training, as indicated by the zero or NaN losses. This can be caused by several factors, including incorrect data preprocessing, model architecture issues, or problems with the training setup. Here are some steps you can take to troubleshoot and resolve the issue:

1. **Check Data Preprocessing:**
   - Ensure that your dataset is correctly labeled and formatted according to YOLOv8's requirements.
   - Verify that the images and annotations are being loaded correctly during training.

2. **Model Configuration:**
   - Review the model configuration file (`.yaml`) to ensure that the model architecture is defined correctly.
   - If you're using a custom model, double-check the layer definitions and connections.

3. **Training Hyperparameters:**
   - Experiment with different learning rates. Sometimes, if the learning rate is too high, it can cause the loss to explode to NaN.
   - Adjust other hyperparameters such as batch size, weight decay, and optimizer settings.

4. **Environment Check:**
   - Make sure you're using the correct versions of PyTorch and CUDA that are compatible with your GPU.
   - Update the Ultralytics YOLOv8 package to the latest version using `pip install -U ultralytics`.

5. **Hardware Check:**
   - Monitor the GPU usage during training to ensure it's being utilized properly.
   - Check for any hardware issues that might be causing the training to fail.

6. **AMP (Automatic Mixed Precision):**
   - Since you mentioned that setting `amp` to `True` results in NaN losses, it's possible that there's an issue with mixed precision training on your setup. Try training with `amp` set to `False` and see if the issue persists.

7. **Gradual Learning Rate Warmup:**
   - Implement a learning rate warmup strategy where the learning rate gradually increases over the first few epochs. This can help stabilize the training.

8. **Loss Function Check:**
   - Ensure that the loss functions are defined correctly and are suitable for the task at hand.

9. **Debugging:**
   - Add print statements or use a debugger to step through the training loop and inspect the values of the losses and gradients.

10. **Consult the Community:**
    - If the issue persists, consider opening an issue on the Ultralytics YOLOv8 GitHub repository with detailed information about your setup, model configuration, and the steps you've taken to resolve the issue.

By systematically going through these steps, you should be able to identify the root cause of the zero or NaN losses and take appropriate action to fix the problem.
