### ISSUE TITLE
Pre train dataset

### ISSUE THREAD

**Issue by AdnanEkici** [ultralytics/ultralytics#2734]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am new to deep learning so I am asking this question I want to pre train yolov8 detection and segmentation should I need to include my dataset(person detection so no new class) to coco dataset or can I only use my dataset.(2000 person data )

**Comment by glenn-jocher** [comment]
Hello @AdnanEkici, 

Yes, you can use your own dataset for pre-training YOLOv8 for person detection and segmentation. There is no need to combine your dataset with the COCO dataset. You can use any annotation tools like Roboflow, VGG Annotator, or labelImg to annotate your data and download the annotations. Once you have the annotations, you can start training your model with the YOLOv8 using your dataset. If you need any assistance during the training process, feel free to ask for help on the YOLOv8 issues or discussions page. 

Let us know if you have any other questions or concerns. We are always happy to help.
