### ISSUE TITLE
Are you sure the segmentation dataset format is correct?

### ISSUE THREAD

**Issue by zhangningboo** [ultralytics/ultralytics#2739]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The link of segmentation dataset format section is https://docs.ultralytics.com/tasks/segment/#train:
![image](https://github.com/ultralytics/ultralytics/assets/110680007/6892f546-808c-4d47-9736-654041e51ecd)
In my practice, the format would be ` cls p1 p2 ... pn`, not the` cls x1 y1 x2 y2 p1 p2 ... pn`. And the [coco-seg128](https://ultralytics.com/assets/coco128-seg.zip) dataset format is cls p1 p2 ... pn. I'm confused. The doc should be wrong. Please check it again; thanks!
[This issue](https://github.com/ultralytics/ultralytics/issues/2678#issue-1713873267) is similar with mine.

### Additional

The link of segmentation dataset format section is https://docs.ultralytics.com/tasks/segment/#train:
![image](https://github.com/ultralytics/ultralytics/assets/110680007/6892f546-808c-4d47-9736-654041e51ecd)
In my practice, the format would be ` cls p1 p2 ... pn`, not the` cls x1 y1 x2 y2 p1 p2 ... pn`. And the [coco-seg128](https://ultralytics.com/assets/coco128-seg.zip) dataset format is `cls p1 p2 ... pn`. I'm confused. The doc should be wrong. Please check it again; thanks!
[This issue](https://github.com/ultralytics/ultralytics/issues/2678#issue-1713873267) is similar to mine.

**Comment by Kayzwer** [comment]
https://github.com/ultralytics/JSON2YOLO
this is what you need, maybe.

**Comment by zhangningboo** [comment]
I know this repo, but the doc has some questions, right?

> https://github.com/ultralytics/JSON2YOLO this is what you need, maybe.

**Comment by Kayzwer** [comment]
@zhangningboo you can switch the branch to "gh-pages", and create a pull request.

**Comment by Laughing-q** [comment]
@zhangningboo yes you're right! Thanks for letting us know! BTW the data format in our dataset section is correct, please also refer to that page. :) [https://docs.ultralytics.com/datasets/segment/](https://docs.ultralytics.com/datasets/segment/)

**Comment by Laughing-q** [comment]
@zhangningboo fixed in #2748

**Comment by zhangningboo** [comment]
@Laughing-q  Dose include this page?: https://docs.ultralytics.com/tasks/segment/#train

**Comment by Laughing-q** [comment]
@zhangningboo I removed the incorrect format and point a link to the dataset page [https://docs.ultralytics.com/datasets/segment/](https://docs.ultralytics.com/datasets/segment/). It would look like this after the PR merged:
![image](https://github.com/ultralytics/ultralytics/assets/61612323/71eaf7d0-c9ff-49de-b1ce-598159b81a3a)

**Comment by zhangningboo** [comment]
Ok

**Comment by zhangningboo** [comment]
@glenn-jocher Thanks ^_^. Best wishes for your future work!

**Comment by glenn-jocher** [comment]
@Kayzwer thank you for the kind words and support! We're always glad to help and improve our repository. If you have any more questions or concerns regarding YOLOv8, feel free to ask. Thank you and have a great day!
