### ISSUE TITLE
Transferred 349 / 355 items from pretrained weights

### ISSUE THREAD

**Issue by junghyun-avikus** [ultralytics/ultralytics#2741]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,
when I finetune on the pretrained v8s,
I somehow get only 349 items transferred out of 355 items.

Are there any differences between the uploaded pretrained model and yaml implementation in the current master?

I just pulled the repository.

**Comment by Kayzwer** [comment]
if your number of classes of your data is different from the pre-trained weights, ofc it will not transfer all the param groups (different size)

**Comment by junghyun-avikus** [comment]
@Kayzwer Oh ok, that makes sense. Thanks!

**Comment by glenn-jocher** [comment]
@junghyun-avikus you're welcome, happy to help! If the number of classes in your data is different than the pre-trained weights, not all parameter groups may be transferred. This difference in size can cause some weights to be unused and not transferred. If you have any other questions or concerns, feel free to ask.

**Comment by marcofarrugia** [comment]
@glenn-jocher would I be correct to say that if the number of classes is different than the pre-trained weights, the weight belonging to the head would be discarded, hence the 349 items are the backbone and neck ones?

**Comment by glenn-jocher** [comment]
@marcofarrugia exactly right! When the number of classes differs from the pretrained weights, the classification head weights are discarded due to shape incompatibility, while the backbone and neck weights (the 349 items) are successfully transferred since their dimensions remain unchanged regardless of the number of output classes.
