### ISSUE TITLE
train using Ultralytics HUB, [ Multi gpu train, train use second gpu ] how to?

### ISSUE THREAD

**Issue by kincjf** [ultralytics/ultralytics#2744]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hello.
When train using Ultralytics HUB, [ Multi gpu train, train use second gpu ] how to? Please let me know how it is possible

I am currently using 3090 2 gpu's.
Does the Ultralytics HUB train run default, use the 1st gpu?

**Comment by Kayzwer** [comment]
https://docs.ultralytics.com/usage/cfg/#train

please refer to `device` row

**Comment by glenn-jocher** [comment]
@kincjf, to train YOLOv8 on multiple GPUs using Ultralytics HUB, you can set the `device` parameter in the `yaml` training configuration file to specify which GPU(s) to use for training and inference. By default, if `device` is not specified, YOLOv8 will use your first GPU (`device: 0`). 

To train using the second GPU, set `device` to `1`. If you would like to use both GPUs for training, set it to `0,1`. 

Once you have set `device` to the desired value(s) in your `yaml` file, Ultralytics HUB will automatically detect the number of available GPUs and utilize them for training according to your `device` parameter. 

I hope that helps!
