### ISSUE TITLE
generate bounding boxes coordinates

### ISSUE THREAD

**Issue by maziqueen79** [ultralytics/ultralytics#2747]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Helloo, how can i modify the predict function in detect task so i can get bounding boxes coordinates as an output ?

**Comment by glenn-jocher** [comment]
@maziqueen79 hello! Thank you for your question. To get bounding box coordinates as an output in YOLOv8, you can modify the `predict` function in the detect task. More specifically, you can access the `xywh` attribute of the detections and convert it to the format of your choice (for example, relative or absolute coordinates) using the `xyxy` method of the BoundingBox class. Then, you can return the desired format as the output of the `predict` function. Let us know if you need further assistance.
