### ISSUE TITLE
modified configs and modules to test and train yolov5, a error occurs here

### ISSUE THREAD

**Issue by isLinXu** [ultralytics/ultralytics#275]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I modified some configs and modules on the ultralytics repo to test and train yolov5, and the following errors occurred:
File "/home/linxu/PycharmProjects/ultralytics/ultralytics/nn/tasks.py", line 291, in attempt_load_weights
    args = {**DEFAULT_CONFIG_DICT, **ckpt['train_args']}  # combine model and default args, preferring model args
KeyError: 'train_args'
![截图_选择区域_20230112100223](https://user-images.githubusercontent.com/59380685/211958217-ff46707e-e4a7-4f78-a23a-5f88c6870fb8.png)

**Comment by Laughing-q** [comment]
@isLinXu oh that's because `train_args` is designed for yolov8 weights, yolov5 weights don't have this key.
Can you try again with `weights=''`? or just don't set weights, just use yaml file of model.

**Comment by isLinXu** [comment]
Um, I also found this problem, I will try the way you said
![截图_选择区域_20230112103054](https://user-images.githubusercontent.com/59380685/211964016-426a7ac3-76af-45c0-9d9d-8e728d5e73a1.png)

**Comment by Laughing-q** [comment]
@isLinXu We'll make other models i.e yolov5 compatible with this. Once we support it I'll let you know. :)

**Comment by isLinXu** [comment]
Okay,I got it.
And I tried what you said, and it didn't seem to work.
Look forward to your follow-up work,thanks

**Comment by Laughing-q** [comment]
@AyushExel

**Comment by AyushExel** [comment]
@Laughing-q @isLinXu I think we'll need to train YOLOv5 from scratch on this repo to fix this problem.. Or can we just transfer weights as a temporary solution?

**Comment by Laughing-q** [comment]
@AyushExel for now I think latter could be fine.

**Comment by pronoym99** [comment]
@Laughing-q How can weights transfer be implemented while creating an instance of YOLO? I have access to a weights file as well as it's equivalent `.pt` file.

**Comment by CTBULJ** [comment]
> @AyushExel can you take a look at this one?



> @isLinXu We'll make other models i.e yolov5 compatible with this. Once we support it I'll let you know. :)

Can't the weight files（best.pt） generated by YOLOv5 training be used as pre-training weights for YOLOv8?
