### ISSUE TITLE
@glenn-jocher. Keep training using the best.pt file

### ISSUE THREAD

**Issue by Minh-Tu-Cao** [ultralytics/ultralytics#2750]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi @glenn-jocher and YOLOv8 developers,
I have just tried YOLOv8 from to train on my dataset.
After completing training the model for 100 epoches, I got well the best.pt and last.pt.
I want to train the model one more time using the best.pt of the previous training time but the code does not take the best.pt as the initial weight, it seems to take yolov8n.pt (original weight) to start the second run.
I found down this issue because the mAP@50 of the best.pt for the first time is 0.458 but I got mAP@50 = 0.167 for the first epoch of the second trainning.
Could you please tell me how to resolve the problem. Please refer to the short code lines below:

def main():
    from ultralytics import YOLO
   model = YOLO('yolov8n.yaml').load('best.pt')  # build from YAML and transfer weights
    model.train(data='data_custom.yaml', epochs=10, imgsz=640, device = 0, workers = 0)
if __name__ == '__main__':
    main()

**Comment by Minh-Tu-Cao** [comment]
@Kayzwer Thank you. Problem is addressed.

**Comment by Kayzwer** [comment]
> @Kayzwer Thank you. Problem is addressed.

please close the issue if you dont have any other problem

**Comment by glenn-jocher** [comment]
You're welcome @Kayzwer-Cao! We're glad to hear that your problem has been addressed. If you don't have any other issues, please feel free to close this issue. If you have any further questions or run into any other issues in the future, please don't hesitate to reach out to us. We'll do our best to help you out. Thanks for using YOLOv8!
