### ISSUE TITLE
Nothing works, can't be installed and can't be run

### ISSUE THREAD

**Issue by easy-and-simple** [ultralytics/ultralytics#2756]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

pip install ultralytics shows warnings and then when I try to run export in 3 lines of python code it gives me error on first line of code - from ultralytica import YOLO
Also it installs over 1 gigabyte of nvidia archives, no matter that I dont have nvidia video card but just intel integrated

Installation warnings:
`WARNING: The script lit is installed in '/home/vvv/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts cmake, cpack and ctest are installed in '/home/vvv/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tqdm is installed in '/home/vvv/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts convert-caffe2-to-onnx, convert-onnx-to-caffe2 and torchrun are installed in '/home/vvv/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts ultralytics and yolo are installed in '/home/vvv/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
`
Run fail errors:
`Traceback (most recent call last):
  File "/home/vvv/yolov8/vvvexport.py", line 1, in <module>
    from ultralytics import YOLO
  File "/home/vvv/yolov8/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import start
  File "/home/vvv/yolov8/ultralytics/hub/__init__.py", line 5, in <module>
    from ultralytics.hub.auth import Auth
  File "/home/vvv/yolov8/ultralytics/hub/auth.py", line 5, in <module>
    from ultralytics.hub.utils import HUB_API_ROOT, PREFIX, request_with_credentials
  File "/home/vvv/yolov8/ultralytics/hub/utils.py", line 14, in <module>
    from ultralytics.yolo.utils import (ENVIRONMENT, LOGGER, ONLINE, RANK, SETTINGS, TESTS_RUNNING, TQDM_BAR_FORMAT,
  File "/home/vvv/yolov8/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/home/vvv/yolov8/ultralytics/yolo/v8/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8 import classify, detect, pose, segment
  File "/home/vvv/yolov8/ultralytics/yolo/v8/classify/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
  File "/home/vvv/yolov8/ultralytics/yolo/v8/classify/predict.py", line 5, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "/home/vvv/yolov8/ultralytics/yolo/engine/predictor.py", line 37, in <module>
    from ultralytics.nn.autobackend import AutoBackend
  File "/home/vvv/yolov8/ultralytics/nn/autobackend.py", line 18, in <module>
    from ultralytics.yolo.utils import LINUX, LOGGER, ROOT, yaml_load
  File "/home/vvv/yolov8/ultralytics/yolo/utils/__init__.py", line 750, in <module>
    SETTINGS = get_settings()
  File "/home/vvv/yolov8/ultralytics/yolo/utils/__init__.py", line 683, in get_settings
    from ultralytics.yolo.utils.torch_utils import torch_distributed_zero_first
  File "/home/vvv/yolov8/ultralytics/yolo/utils/torch_utils.py", line 14, in <module>
    import thop
ModuleNotFoundError: No module named 'thop'
`

### Environment

any version of python from 3.7-3.10
ubuntu 22.04 86x64

### Minimal Reproducible Example

pip install ultralytics

from ultralytics import YOLO

model = YOLO('yolov8n.pt')
model.export(format='edgetpu')

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by easy-and-simple** [comment]
I made new conda virtual env with python3.8
installed pytorch for CPU
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
installed ultralytics
pip install ultralytics

and nothing chages!!!!!!!!!!!!!!!!!!!!!!!!! Same error that there is no module named thop!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Maybe I am not pressing enter key with right finger?????????????????!!!!!!!!!!!!!!!!!!!!!!!!!
Nothing works, neither yolov8 nor yolov5

**Comment by easy-and-simple** [comment]
Python3 export still doesn't work and export is interruped with the same error: no module named thop

**Comment by easy-and-simple** [comment]
How model caould work after following?
:
WARNING: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: /onnxruntime_src/onnxruntime/core/graph/model.cc:146 onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&, const onnxruntime::ModelOptions&) Unsupported model IR version: 9, max supported IR version: 8

**Comment by easy-and-simple** [comment]
You export it in tflite format, and I need it to edgetpu dormat

**Comment by easy-and-simple** [comment]
What means if you need thop? What then installs ultralytics package if I need to install some unknown packages manually?
Also after "successful" export model can't be ran on edgetpu
If it works for you this doesn't means it works for everybody. If you want to reproduce mu case you should remove your nviade video card

**Comment by easy-and-simple** [comment]
There are 2 warnings that shows export is not successful, no matter that at the end it prints that export is successful

yolo export model=yolov8n.pt format=edgetpu
Ultralytics YOLOv8.0.106 🚀 Python-3.10.6 torch-2.0.1+cu117 CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients

PyTorch: starting from yolov8n.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

TensorFlow SavedModel: starting export with tensorflow 2.12.0...

ONNX: starting export with onnx 1.14.0 opset 17...
============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ONNX: simplifying with onnxsim 0.4.28...
ONNX: export success ✅ 1.3s, saved as yolov8n.onnx (12.2 MB)

TensorFlow SavedModel: running 'onnx2tf -i yolov8n.onnx -o yolov8n_saved_model -nuo --non_verbose -oiqt -qt per-tensor'
WARNING: The optimization process for shape estimation is skipped because it contains OPs that cannot be inferred by the standard onnxruntime.
WARNING: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: /onnxruntime_src/onnxruntime/core/graph/model.cc:146 onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&, const onnxruntime::ModelOptions&) Unsupported model IR version: 9, max supported IR version: 8

fully_quantize: 0, inference_type: 6, input_inference_type: FLOAT32, output_inference_type: FLOAT32
fully_quantize: 0, inference_type: 6, input_inference_type: INT8, output_inference_type: INT8
TensorFlow SavedModel: export success ✅ 104.5s, saved as yolov8n_saved_model (41.0 MB)
Edge TPU: WARNING ⚠️ Edge TPU known bug https://github.com/ultralytics/ultralytics/issues/1185

Edge TPU: starting export with Edge TPU compiler 16.0.384591198...
Edge TPU: running 'edgetpu_compiler -s -d -k 10 --out_dir yolov8n_saved_model yolov8n_saved_model/yolov8n_full_integer_quant.tflite'
Edge TPU Compiler version 16.0.384591198
Searching for valid delegate with step 10
Try to compile segment with 255 ops
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 1888 ms.

Input model: yolov8n_saved_model/yolov8n_full_integer_quant.tflite
Input size: 3.12MiB
Output model: yolov8n_saved_model/yolov8n_full_integer_quant_edgetpu.tflite
Output size: 3.87MiB
On-chip memory used for caching model parameters: 3.41MiB
On-chip memory remaining for caching model parameters: 3.17MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 255
Operation log: yolov8n_saved_model/yolov8n_full_integer_quant_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 230
Number of operations that will run on CPU: 25

Operator                       Count      Status

CONCATENATION                  16         Mapped to Edge TPU
CONCATENATION                  2          Operation is otherwise supported, but not mapped due to some unspecified limitation
CONCATENATION                  1          More than one subgraph is not supported
SUB                            2          More than one subgraph is not supported
MUL                            57         Mapped to Edge TPU
MUL                            2          More than one subgraph is not supported
STRIDED_SLICE                  2          Operation is otherwise supported, but not mapped due to some unspecified limitation
STRIDED_SLICE                  2          More than one subgraph is not supported
STRIDED_SLICE                  16         Mapped to Edge TPU
ADD                            6          Mapped to Edge TPU
ADD                            2          More than one subgraph is not supported
RESHAPE                        1          More than one subgraph is not supported
RESHAPE                        3          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESHAPE                        1          Mapped to Edge TPU
MAX_POOL_2D                    3          Mapped to Edge TPU
PAD                            7          Mapped to Edge TPU
TRANSPOSE                      1          Mapped to Edge TPU
TRANSPOSE                      4          Operation is otherwise supported, but not mapped due to some unspecified limitation
LOGISTIC                       57         Mapped to Edge TPU
LOGISTIC                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
QUANTIZE                       1          Mapped to Edge TPU
QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
CONV_2D                        63         Mapped to Edge TPU
CONV_2D                        1          More than one subgraph is not supported
SOFTMAX                        1          More than one subgraph is not supported
Compilation child process completed within timeout period.
Compilation succeeded! 
Edge TPU: export success ✅ 2.0s, saved as yolov8n_saved_model/yolov8n_full_integer_quant_edgetpu.tflite (3.9 MB)

Export complete (106.6s)
Results saved to /home/vvv/yolov8
Predict:         yolo predict task=detect model=yolov8n_saved_model/yolov8n_full_integer_quant_edgetpu.tflite imgsz=640 
Validate:        yolo val task=detect model=yolov8n_saved_model/yolov8n_full_integer_quant_edgetpu.tflite imgsz=640 data=coco.yaml 
Visualize:       https://netron.app

**Comment by easy-and-simple** [comment]
@glenn-jocher  could you export it to edgetpu format on your computer and to give it to me to test if model will work with edgetpu?

**Comment by easy-and-simple** [comment]
I installed thop as you suggested me and now export is not interrupted, but both warnings are there as if I run it by CLI

python3 vvvexport.py
Ultralytics YOLOv8.0.99 🚀 Python-3.10.6 torch-2.0.1+cu117 CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

PyTorch: starting from yolov8n.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

TensorFlow SavedModel: starting export with tensorflow 2.12.0...

ONNX: starting export with onnx 1.14.0 opset 17...
============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ONNX: simplifying with onnxsim 0.4.28...
ONNX: export success ✅ 1.2s, saved as yolov8n.onnx (12.2 MB)

TensorFlow SavedModel: running 'onnx2tf -i yolov8n.onnx -o yolov8n_saved_model -nuo --non_verbose -oiqt -qt per-tensor'
WARNING: The optimization process for shape estimation is skipped because it contains OPs that cannot be inferred by the standard onnxruntime.
WARNING: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: /onnxruntime_src/onnxruntime/core/graph/model.cc:146 onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&, const onnxruntime::ModelOptions&) Unsupported model IR version: 9, max supported IR version: 8

fully_quantize: 0, inference_type: 6, input_inference_type: FLOAT32, output_inference_type: FLOAT32
fully_quantize: 0, inference_type: 6, input_inference_type: INT8, output_inference_type: INT8
TensorFlow SavedModel: export success ✅ 105.6s, saved as yolov8n_saved_model (41.0 MB)
Edge TPU: WARNING ⚠️ Edge TPU known bug https://github.com/ultralytics/ultralytics/issues/1185

Edge TPU: starting export with Edge TPU compiler 16.0.384591198...
Edge TPU: running 'edgetpu_compiler -s -d -k 10 --out_dir yolov8n_saved_model yolov8n_saved_model/yolov8n_full_integer_quant.tflite'
Edge TPU Compiler version 16.0.384591198
Searching for valid delegate with step 10
Try to compile segment with 255 ops
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 1894 ms.

Input model: yolov8n_saved_model/yolov8n_full_integer_quant.tflite
Input size: 3.12MiB
Output model: yolov8n_saved_model/yolov8n_full_integer_quant_edgetpu.tflite
Output size: 3.87MiB
On-chip memory used for caching model parameters: 3.41MiB
On-chip memory remaining for caching model parameters: 3.17MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 255
Operation log: yolov8n_saved_model/yolov8n_full_integer_quant_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 230
Number of operations that will run on CPU: 25

Operator                       Count      Status

SOFTMAX                        1          More than one subgraph is not supported
MUL                            2          More than one subgraph is not supported
MUL                            57         Mapped to Edge TPU
TRANSPOSE                      4          Operation is otherwise supported, but not mapped due to some unspecified limitation
TRANSPOSE                      1          Mapped to Edge TPU
RESHAPE                        3          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESHAPE                        1          Mapped to Edge TPU
RESHAPE                        1          More than one subgraph is not supported
CONCATENATION                  1          More than one subgraph is not supported
CONCATENATION                  16         Mapped to Edge TPU
CONCATENATION                  2          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
CONV_2D                        63         Mapped to Edge TPU
CONV_2D                        1          More than one subgraph is not supported
QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
QUANTIZE                       1          Mapped to Edge TPU
MAX_POOL_2D                    3          Mapped to Edge TPU
ADD                            2          More than one subgraph is not supported
ADD                            6          Mapped to Edge TPU
PAD                            7          Mapped to Edge TPU
SUB                            2          More than one subgraph is not supported
LOGISTIC                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
LOGISTIC                       57         Mapped to Edge TPU
STRIDED_SLICE                  2          Operation is otherwise supported, but not mapped due to some unspecified limitation
STRIDED_SLICE                  2          More than one subgraph is not supported
STRIDED_SLICE                  16         Mapped to Edge TPU
Compilation child process completed within timeout period.
Compilation succeeded! 
Edge TPU: export success ✅ 2.0s, saved as yolov8n_saved_model/yolov8n_full_integer_quant_edgetpu.tflite (3.9 MB)

Export complete (107.7s)
Results saved to /home/vvv/yolov8
Predict:         yolo predict task=detect model=yolov8n_saved_model/yolov8n_full_integer_quant_edgetpu.tflite imgsz=640 
Validate:        yolo val task=detect model=yolov8n_saved_model/yolov8n_full_integer_quant_edgetpu.tflite imgsz=640 data=coco.yaml 
Visualize:       https://netron.app

**Comment by easy-and-simple** [comment]
@glenn-jocher 
In your case simplifying is right after onnx export and before diagnostic run, while in my case simplifying is after diagnostic tun, why?

**Comment by glenn-jocher** [comment]
@easy-and-simple hello! The difference in the order of the simplifying step between our cases is likely due to the version of the ONNX library being used. It is possible that different versions of the library handle the order of these steps differently. However, regardless of the order of these steps, the final exported ONNX model should still function correctly. Let me know if you have any further questions or concerns.

**Comment by easy-and-simple** [comment]
No this is not normal if I get 2 warnings that model is not processed. How you expect all is OK after that? According to error I get when I try to run model on edgetpu it is related to first warning because shape of model is not correct.
On top of all I need manually to install thop package in order to run python code and CLI code needs to be run 2 times in order to install all required packages

WARNING: The optimization process for shape **estimation is skipped because it contains OPs that cannot be inferred** by the standard onnxruntime.
WARNING: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : **Failed to load model with error:** /onnxruntime_src/onnxruntime/core/graph/model.cc:146 onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&, const onnxruntime::ModelOptions&) **Unsupported model IR version: 9, max supported IR version: 8**
I don't believe that after these warningd, that are pure errors model can be converted correctly and it will work
Would you fix your code to make it working

**Comment by easy-and-simple** [comment]
On second run on colab both warnings/errors are again here:

Ultralytics YOLOv8.0.106 🚀 Python-3.10.11 torch-2.0.1+cu118 CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients

PyTorch: starting from yolov8n.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

TensorFlow SavedModel: starting export with tensorflow 2.12.0...

ONNX: starting export with onnx 1.14.0 opset 17...
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ONNX: simplifying with onnxsim 0.4.28...
ONNX: export success ✅ 2.6s, saved as yolov8n.onnx (12.2 MB)

TensorFlow SavedModel: running 'onnx2tf -i yolov8n.onnx -o yolov8n_saved_model -nuo --non_verbose -oiqt -qt per-tensor'
WARNING: The optimization process for shape estimation is skipped because it contains OPs that cannot be inferred by the standard onnxruntime.
WARNING: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: /onnxruntime_src/onnxruntime/core/graph/model.cc:146 onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&, const onnxruntime::ModelOptions&) Unsupported model IR version: 9, max supported IR version: 8

fully_quantize: 0, inference_type: 6, input_inference_type: FLOAT32, output_inference_type: FLOAT32
fully_quantize: 0, inference_type: 6, input_inference_type: INT8, output_inference_type: INT8
2023-05-23 08:48:15.389312: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
TensorFlow SavedModel: export success ✅ 189.2s, saved as yolov8n_saved_model (41.0 MB)
Edge TPU: WARNING ⚠️ Edge TPU known bug https://github.com/ultralytics/ultralytics/issues/1185

Edge TPU: starting export with Edge TPU compiler 16.0.384591198...
Edge TPU: running 'edgetpu_compiler -s -d -k 10 --out_dir yolov8n_saved_model yolov8n_saved_model/yolov8n_full_integer_quant.tflite'
Edge TPU Compiler version 16.0.384591198
Searching for valid delegate with step 10
Try to compile segment with 255 ops
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 4679 ms.

Input model: yolov8n_saved_model/yolov8n_full_integer_quant.tflite
Input size: 3.12MiB
Output model: yolov8n_saved_model/yolov8n_full_integer_quant_edgetpu.tflite
Output size: 3.87MiB
On-chip memory used for caching model parameters: 3.41MiB
On-chip memory remaining for caching model parameters: 3.17MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 255
Operation log: yolov8n_saved_model/yolov8n_full_integer_quant_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 230
Number of operations that will run on CPU: 25

Operator                       Count      Status

CONCATENATION                  16         Mapped to Edge TPU
CONCATENATION                  2          Operation is otherwise supported, but not mapped due to some unspecified limitation
CONCATENATION                  1          More than one subgraph is not supported
SOFTMAX                        1          More than one subgraph is not supported
RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
CONV_2D                        1          More than one subgraph is not supported
CONV_2D                        63         Mapped to Edge TPU
QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
QUANTIZE                       1          Mapped to Edge TPU
MAX_POOL_2D                    3          Mapped to Edge TPU
ADD                            6          Mapped to Edge TPU
ADD                            2          More than one subgraph is not supported
LOGISTIC                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
LOGISTIC                       57         Mapped to Edge TPU
PAD                            7          Mapped to Edge TPU
TRANSPOSE                      1          Mapped to Edge TPU
TRANSPOSE                      4          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESHAPE                        1          Mapped to Edge TPU
RESHAPE                        3          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESHAPE                        1          More than one subgraph is not supported
STRIDED_SLICE                  2          More than one subgraph is not supported
STRIDED_SLICE                  2          Operation is otherwise supported, but not mapped due to some unspecified limitation
STRIDED_SLICE                  16         Mapped to Edge TPU
SUB                            2          More than one subgraph is not supported
MUL                            57         Mapped to Edge TPU
MUL                            2          More than one subgraph is not supported
Compilation child process completed within timeout period.
Compilation succeeded! 
Edge TPU: export success ✅ 4.9s, saved as yolov8n_saved_model/yolov8n_full_integer_quant_edgetpu.tflite (3.9 MB)

Export complete (194.5s)
Results saved to /content
Predict:         yolo predict task=detect model=yolov8n_saved_model/yolov8n_full_integer_quant_edgetpu.tflite imgsz=640 
Validate:        yolo val task=detect model=yolov8n_saved_model/yolov8n_full_integer_quant_edgetpu.tflite imgsz=640 data=coco.yaml 
Visualize:       https://netron.app/

**Comment by easy-and-simple** [comment]
The same errors appers and when I try to export it to tflite model.
@glenn-jocher congratulations ultralitics works only for you

**Comment by easy-and-simple** [comment]
This is result for tflite export on colab and as you see both errors are there too:

Ultralytics YOLOv8.0.106 🚀 Python-3.10.11 torch-2.0.1+cu118 CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients

PyTorch: starting from yolov8n.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

TensorFlow SavedModel: starting export with tensorflow 2.12.0...

ONNX: starting export with onnx 1.14.0 opset 17...
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ONNX: simplifying with onnxsim 0.4.28...
ONNX: export success ✅ 2.6s, saved as yolov8n.onnx (12.2 MB)

TensorFlow SavedModel: running 'onnx2tf -i yolov8n.onnx -o yolov8n_saved_model -nuo --non_verbose'
WARNING: The optimization process for shape estimation is skipped because it contains OPs that cannot be inferred by the standard onnxruntime.
WARNING: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: /onnxruntime_src/onnxruntime/core/graph/model.cc:146 onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&, const onnxruntime::ModelOptions&) Unsupported model IR version: 9, max supported IR version: 8

2023-05-23 09:00:20.060638: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
TensorFlow SavedModel: export success ✅ 15.6s, saved as yolov8n_saved_model (30.6 MB)

TensorFlow Lite: starting export with tensorflow 2.12.0...
TensorFlow Lite: export success ✅ 0.0s, saved as yolov8n_saved_model/yolov8n_float32.tflite (12.2 MB)

Export complete (16.1s)
Results saved to /content
Predict:         yolo predict task=detect model=yolov8n_saved_model/yolov8n_float32.tflite imgsz=640 
Validate:        yolo val task=detect model=yolov8n_saved_model/yolov8n_float32.tflite imgsz=640 data=coco.yaml 
Visualize:       https://netron.app/

**Comment by easy-and-simple** [comment]
@glenn-jocher 
Would you remove [non-reproducible] tag from my post, because if on colab result is the same as on my machine, then it is reproducible, right?!

**Comment by easy-and-simple** [comment]
@glenn-jocher Hi. There is no difference between results of my PC and colab. Results are the same. In both cases there are 2 warnings/errors issued by onnx2tf, Model exported in this way cant run on edgetpu device

**Comment by easy-and-simple** [comment]
There is difference only when ultralytics is installed, because on my PC thop module must be installed manually while on colab it is auto installed. My PC don't have discrete video card, so my setup require CPU packages to be installed

**Comment by easy-and-simple** [comment]
I replaced onnx 1.14.1 with 1.13.1 because on onnx2tf repository is written that there are problems with  1.14.1 and now there is not warnings/errors reported, but exported model doesn't run on edgetpu.

**Comment by glenn-jocher** [comment]
@easy-and-simple hello, thank you for reaching out with your issue. We're sorry to hear that you're experiencing problems with exporting your YOLOv8 model to run on edgetpu. It's possible that the error you're encountering is not related to the version of ONNX you are using, but rather a separate issue. We suggest checking that the input and output formats of your model are correct for the edgetpu device, as well as any other device-specific requirements. Additionally, you may want to consider checking the installation and dependencies of your edgetpu drivers. If the issue persists, please provide us with more details on the error and we'll do our best to assist you.

**Comment by easy-and-simple** [comment]
@glenn-jocher Hello. Its not mine yolov8 model, its yours. I just want to export is with default weights for edgetpu in order to check its accuracy and effectiveness on edgetpu. What is doing your export script if it cant export it in working condition?
I have no problems with edgetpu device because it is running fine with examples and models supplied by pycoral. I run detection with detect_image.py python script from examples directory of pycoral repository. It works fine with supplied mobilenet models, but when I point script to model exported in edgetpu format by yolov5 or yolov8 repository export functions I get error that index is out of range

**Comment by easy-and-simple** [comment]
I think export options used for different tools are not properly set. For example -nuo option of onnx2tf that according to description make the chance for errors very high. Also edgetpu_compiler is run in version 10 mode while version 14 i last and have more instructions supported. How YOLO exports model for edgetpu if is doesn't work? What options I need to pass to CLI export to export working model for edgetpu?

**Comment by glenn-jocher** [comment]
@easy-and-simple hello! Thank you for sharing your concerns.

The export options used in the YOLOv8 repository are optimized for exporting to TensorFlow Lite, TensorFlow.js, and Core ML. While the code may run in the edgetpu_compiler, we cannot guarantee that the inferred results will be correct. 

Regarding the issue of the "-nuo" option in onnx2tf, this flag is necessary for correct operation of TensorFlow 1.x versions that predate TensorFlow 2.0. However, YOLOv8 depends on TensorFlow 2.x, and so this flag should not make any difference in the efficacy or accuracy of the exported model.

Regarding the edgetpu_compiler version, thank you for bringing that to our attention. We will look into updating the repository to use the latest compiler version.

For exporting a YOLOv8 model to run on edgetpu, we suggest using the YOLOv8 origin repository's export_to_edgetpu() function which should handle most of the necessary settings and flags. We recommend reviewing the help function for edgetpu_compiler to better understand these flags.

Please let us know if you have any further concerns or questions!

**Comment by easy-and-simple** [comment]
@glenn-jocher  Hello. Now I am trying to install ultralytics on arm SBC and again have problems to install it
I installed torch and ultralytics but at first it is not added to path and at second I get some error that image libjps and libpng are not installed. Than after I run yolo exptarct is it not working and prints a lot of warnings/error messages that onnx cant be installed.
Does ultralytics run on arm CPUs?

**Comment by glenn-jocher** [comment]
@easy-and-simple hello! We apologize for the installation issues you're encountering with the Ultralytics package on your Arm SBC. Ultralytics should be compatible with Arm processors, so this may be an issue with conflicting dependencies. 

Regarding the missing image libraries, it may be necessary to install libjpeg and libpng manually. These packages can typically be installed using your distribution's package manager or via a command such as: "sudo apt-get install libjpeg-dev libpng-dev".

Regarding the warnings and errors you're seeing with the onnx and onnx tools installations, these may be related to conflicts with existing versions installed on your system. Try uninstalling possibly conflicting packages manually, then reinstalling Ultralytics.

Please let us know if this helps resolve the issue!

**Comment by easy-and-simple** [comment]
@glenn-jocher Hello. I think yolo docs and guides are really bead and useless. Issues with yolo installation on arm SBC was related to missing dependencies because in yolo docs there is no list of base requirements and also they are not installed automatically. On arm SBC installation problems was caused by missing or old versions of gcc, cmake, python3-dev and header files. Without these packages ultralitics cant be installed. These are obviously general issues with arm SBC boards so I can't understand why these requirements are not listed in yolo docs.

**Comment by easy-and-simple** [comment]
After I installed all packages I listed in my previous comment I installed yolov8 on my arm SBC, but now cant run detection because yolo issues error ValueError: Failed to load delegate from libedgetpu.so.1
Edgetpu runtime is installed. Do you have any idea what is causing this error?

**Comment by easy-and-simple** [comment]
Yolov8 model that is exported doesn't work and doesn't detect anything. Also if I export s model all instructions are mapped to CPU and 0 are mapped to edgetpu. I tried n and l model and both map 90% of instructions to edgetpu and 10% to CPU
If I export s model from yolo5 it is wotking with yolo5 detection script

**Comment by glenn-jocher** [comment]
@easy-and-simple hello! Thank you for reaching out with the issue you're encountering with the YOLOv8 model export. We're sorry to hear that the YOLOv8 model is not working as intended when exported to edgetpu. 

It's possible that the export options used for YOLOv8 are not optimal for running on edgetpu. In any case, it is an ongoing issue which we would love to investigate. For ensuring the compatibility of the model with edgetpu, you will need to make sure that the model's input and output formats are correct for this device, as well as any other device-specific requirements.

Regarding your observations about the instructions mapping, it's hard to tell without further information and details about the 's' model. However, it's possible that the optimization process is not taking advantage of all the capabilities of the edge tpu. You may want to explore different options for quantization and optimization when exporting the model, or consider fine-tuning the network architecture for better performance on your specific target device.

Please let us know if you have any further concerns or questions!
