### ISSUE TITLE
Tflite   issue java android 

### ISSUE THREAD

**Issue by mohamedyousef** [ultralytics/ultralytics#2758]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I converted the model to int8
This error is happening to me and I don't know why
                                                                                                    java.lang.IllegalArgumentException: Cannot copy to a TensorFlowLite tensor (serving_default_images:0) with 1228800 bytes from a Java Buffer with 307200 bytes.

### Additional

model: Yolov8n 
used this command to convert it   

```
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)
success = model.export(format="tflite",imgsz = 320, int8 = True)  # export the model to ONNX format

```

**Comment by glenn-jocher** [comment]
@mohamedyousef hello 👋,

Thank you for reaching out! It looks like you're running into an issue when converting the YOLOv8 model to an int8 TFLite model on Android. The error message you provided indicates that the dimensions of the input buffer you're passing to the `serving_default_images` tensor in TFLite don't match the tensor's expected size (1228800 bytes vs. 307200 bytes). Without additional information on how you're using the TFLite model on Android, it's difficult to pinpoint the exact cause of the issue, but the error message suggests that there may be a problem with the input image dimensions.

To help narrow down the issue and verify that it's related to YOLOv8, could you provide more information on the input data you're using (e.g., width, height, color format), how you're preparing the input data for the TFLite model, and any relevant code or logs that might be helpful for debugging? 

Looking forward to hearing back from you!

**Comment by mohamedyousef** [comment]
hello @glenn-jocher thanks for answering 
input data 

input size : 320   
color format :ARGB_8888

  ```
 protected void convertBitmapToByteBuffer(Bitmap bitmap) {

  bitmap.getPixels(intValues, 0, bitmap.getWidth(), 0, 0, bitmap.getWidth(), bitmap.getHeight());
        int pixel = 0;

        imgData.rewind();
        for (int i = 0; i < INPUT_SIZE; ++i) {
            for (int j = 0; j < INPUT_SIZE; ++j) {
                int pixelValue = intValues[i * INPUT_SIZE + j];
                if (isModelQuantized) {
                    // Quantized model
                    imgData.put((byte) ((((pixelValue >> 16) & 0xFF) - IMAGE_MEAN) / IMAGE_STD / inp_scale + inp_zero_point));
                    imgData.put((byte) ((((pixelValue >> 8) & 0xFF) - IMAGE_MEAN) / IMAGE_STD / inp_scale + inp_zero_point));
                    imgData.put((byte) (((pixelValue & 0xFF) - IMAGE_MEAN) / IMAGE_STD / inp_scale + inp_zero_point));
                } else { // Float model
                    imgData.putFloat((((pixelValue >> 16) & 0xFF) - IMAGE_MEAN) / IMAGE_STD);
                    imgData.putFloat((((pixelValue >> 8) & 0xFF) - IMAGE_MEAN) / IMAGE_STD);
                    imgData.putFloat(((pixelValue & 0xFF) - IMAGE_MEAN) / IMAGE_STD);
                }
            }
        }
       
}
```

 ```
   public ArrayList<Recognition> recognizeImage(Bitmap bitmap) {
        convertBitmapToByteBuffer(bitmap);

        Map<Integer, Object> outputMap = new HashMap<>();

        outData.rewind();
        outputMap.put(0, outData);
        Log.d("YoloV5Classifier", "mObjThresh: " + getObjThresh());

        Object[] inputArray = {imgData};
        tfLite.runForMultipleInputsOutputs(inputArray, outputMap); // crash happened here 

        ByteBuffer byteBuffer = (ByteBuffer) outputMap.get(0);
        byteBuffer.rewind();

        ArrayList<Recognition> detections = new ArrayList<Recognition>();

        float[][][] out = new float[1][output_box][numClass + 5];

        for (int i = 0; i < output_box; ++i) {
            for (int j = 0; j < numClass + 5; ++j) {
                if (isModelQuantized){
                    out[0][i][j] = oup_scale * (((int) byteBuffer.get() & 0xFF) - oup_zero_point);
                }
                else {
                    out[0][i][j] = byteBuffer.getFloat();
                }
            }
            // Denormalize xywh
            for (int j = 0; j < 4; ++j) {
                out[0][i][j] *= getInputSize();
            }
        }
        for (int i = 0; i < output_box; ++i){
            final int offset = 0;
            final float confidence = out[0][i][4];
            int detectedClass = -1;
            float maxClass = 0;

            final float[] classes = new float[labels.size()];
            for (int c = 0; c < labels.size(); ++c) {
                classes[c] = out[0][i][5 + c];
            }

            for (int c = 0; c < labels.size(); ++c) {
                if (classes[c] > maxClass) {
                    detectedClass = c;
                    maxClass = classes[c];
                }
            }

            final float confidenceInClass = maxClass * confidence;
            if (confidenceInClass > getObjThresh()) {
                final float xPos = out[0][i][0];
                final float yPos = out[0][i][1];

                final float w = out[0][i][2];
                final float h = out[0][i][3];

                final RectF rect =
                        new RectF(
                                Math.max(0, xPos - w / 2),
                                Math.max(0, yPos - h / 2),
                                Math.min(bitmap.getWidth() - 1, xPos + w / 2),
                                Math.min(bitmap.getHeight() - 1, yPos + h / 2));
                detections.add(new Recognition("" + offset, labels.get(detectedClass),
                        confidenceInClass, rect, detectedClass));
            }
        }

        final ArrayList<Recognition> recognitions = nms(detections);
        return recognitions;
    }

```

labels 
[coco.txt](https://github.com/ultralytics/ultralytics/files/11542330/coco.txt)

**Comment by mohamedyousef** [comment]
logs:

                                                                                                    java.lang.IllegalArgumentException: Cannot copy to a TensorFlowLite tensor (serving_default_images:0) with 1228800 bytes from a Java Buffer with 307200 bytes.

**Comment by mohamedyousef** [comment]
model :
[yolov8n_int8.tflite.zip](https://github.com/ultralytics/ultralytics/files/11542373/yolov8n_int8.tflite.zip)

**Comment by glenn-jocher** [comment]
Hello @mohamedyousef,

It looks like the error you're encountering is due to the input buffer you're passing to the "serving_default_images" tensor in TFLite not having the same size as the tensor expected by YOLOv8. The error message suggests that there may be an issue with the dimensions of the input image you're using.

Based on the code you've provided, you're preparing the input image data as an array of ARGB_8888 pixels with a size of 320 pixels. However, we cannot be sure if this is the exact size of the input image tensor expected by your YOLOv8 model. 

To troubleshoot and resolve the error, we would recommend double-checking the expected input dimensions of the YOLOv8 model, and ensure that your input image data matches those dimensions. Additionally, you may want to check if there are any preprocessing steps that need to be applied to the input image before passing it to the model.

Please let us know if you have any more questions or if the issue persists even after checking your input dimensions and preprocessing steps.

Best regards.
