### ISSUE TITLE
Question about converting yolov8 model to coreML model

### ISSUE THREAD

**Issue by 7288Fzq** [ultralytics/ultralytics#2764]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

`CoreML: starting export with coremltools 6.3.0...
Tuple detected at graph output. This will be flattened in the converted model.
Converting PyTorch Frontend ==> MIL Ops: 100%|█████████▉| 523/525 [00:00<00:00, 6736.19 ops/s]
Running MIL frontend_pytorch pipeline: 100%|██████████| 5/5 [00:00<00:00, 555.52 passes/s]
Running MIL default pipeline: 100%|██████████| 56/56 [00:00<00:00, 329.41 passes/s]
Running MIL backend_neuralnetwork pipeline: 100%|██████████| 8/8 [00:00<00:00, 1333.32 passes/s]
Translating MIL ==> NeuralNetwork Ops:  82%|████████▏ | 521/639 [00:00<00:00, 5178.04 ops/s]Const anchor_points was already added.
Translating MIL ==> NeuralNetwork Ops: 100%|██████████| 639/639 [00:00<00:00, 5007.09 ops/s]
CoreML Pipeline: starting pipeline with coremltools 6.3.0...
CoreML: export failure  2.0s: 'NoneType' object is not callable`

### Environment

Ultralytics YOLOv8.0.87  Python-3.10.9 torch-2.0.1+cu117 CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

### Minimal Reproducible Example

from ultralytics import YOLO

model=YOLO(r'D:\train\ballTest\yolov8n.pt')

model.export(format='coreml',nms=True)

### Additional

There is a problem when I try to export the official yolov8 model as a coreML model and set the NMS parameter to True.
The strange thing is that if the NMS parameter is set to False, which is the default value, it will not report an error but will export successfully. Looking forward to answer!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@corey-nm coremltools has been reducing support for *.mlmodel formats in recent releases. try version 6.0.0

**Comment by 7288Fzq** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/71710433/8c7e8df9-6a8c-4174-a95c-92c8bfeb5f4b)
![image](https://github.com/ultralytics/ultralytics/assets/71710433/2a67c676-e9cc-488a-9018-227be8057aa3)
I have installed the 6.0.0 version of coreML tools, a new problem appeared

**Comment by 7288Fzq** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/71710433/63f2e7fb-cd94-46e0-b2bd-e22fb7ec4f59)
using GoogleColab

**Comment by glenn-jocher** [comment]
Hi @7288Fzq, 

The error message "ImportError: cannot import name 'Darknet' from 'models', try installing yolo5" suggests that you are using an old version of the YOLOv8 repository. 

Please make sure that you have cloned the latest version of the repository from https://github.com/ultralytics/ultralytics, as YOLOv8 doesn't require YOLOv5 to be installed. Additionally, make sure that you are importing the correct model component from the YOLOv8 repository.

If you are still having trouble after ensuring that you have the correct version and importing the correct model component, please provide more details about your setup and the steps you have taken to reproduce the error.

Let me know if you have any further questions or concerns!

**Comment by simgt** [comment]
FYI this worked for me with coremltools `7.0b1` 🙂

**Comment by devvikas** [comment]
Ultralytics YOLOv8.0.199 🚀 Python-3.9.13 torch-1.9.0 CPU (Intel Core(TM) i7-9750H 2.60GHz)
/Users/vikaschoudhary/miniconda3/envs/py39_torch/lib/python3.9/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ../c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Model summary (fused): 168 layers, 3017348 parameters, 0 gradients, 8.1 GFLOPs

PyTorch: starting from 'best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 64, 8400) (6.0 MB)

CoreML: starting export with coremltools 7.0b1...
CoreML: export failure ❌ 8.9s: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.
Traceback (most recent call last):
  File "/Users/vikaschoudhary/Documents/work/Ludex/yolo8_conversion/conversion.py", line 5, in <module>
    model.export(format='coreml')
  File "/Users/vikaschoudhary/miniconda3/envs/py39_torch/lib/python3.9/site-packages/ultralytics/engine/model.py", line 313, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/Users/vikaschoudhary/miniconda3/envs/py39_torch/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/Users/vikaschoudhary/miniconda3/envs/py39_torch/lib/python3.9/site-packages/ultralytics/engine/exporter.py", line 258, in __call__
    f[4], _ = self.export_coreml()
  File "/Users/vikaschoudhary/miniconda3/envs/py39_torch/lib/python3.9/site-packages/ultralytics/engine/exporter.py", line 122, in outer_func
    raise e
  File "/Users/vikaschoudhary/miniconda3/envs/py39_torch/lib/python3.9/site-packages/ultralytics/engine/exporter.py", line 117, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/Users/vikaschoudhary/miniconda3/envs/py39_torch/lib/python3.9/site-packages/ultralytics/engine/exporter.py", line 532, in export_coreml
    ts = torch.jit.trace(model.eval(), self.im, strict=False)  # TorchScript model
  File "/Users/vikaschoudhary/miniconda3/envs/py39_torch/lib/python3.9/site-packages/torch/jit/_trace.py", line 735, in trace
    return trace_module(
  File "/Users/vikaschoudhary/miniconda3/envs/py39_torch/lib/python3.9/site-packages/torch/jit/_trace.py", line 977, in trace_module
    _check_trace(
  File "/Users/vikaschoudhary/miniconda3/envs/py39_torch/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/Users/vikaschoudhary/miniconda3/envs/py39_torch/lib/python3.9/site-packages/torch/jit/_trace.py", line 513, in _check_trace
    if compare_outputs(traced_outs, fn_outs, "Python function"):
  File "/Users/vikaschoudhary/miniconda3/envs/py39_torch/lib/python3.9/site-packages/torch/jit/_trace.py", line 488, in compare_outputs
    torch.testing.assert_allclose(
  File "/Users/vikaschoudhary/miniconda3/envs/py39_torch/lib/python3.9/site-packages/torch/testing/_core.py", line 260, in assert_allclose
    result, debug_msg = _compare_tensors_internal(actual, expected,
  File "/Users/vikaschoudhary/miniconda3/envs/py39_torch/lib/python3.9/site-packages/torch/testing/_core.py", line 164, in _compare_tensors_internal
    if torch.allclose(a, b, rtol=rtol, atol=atol, equal_nan=(equal_nan in {"relaxed", True})):
RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.

**Comment by glenn-jocher** [comment]
@devvikas this error may occur due to restrictions on inplace operations in the newer PyTorch versions after 1.9.0. When using inference mode, if you intended to make inplace modifications, you will need to clone the tensor first to get a normal tensor. This way, you will not be modifying the inference tensor directly which is currently not supported in inference mode.

As you are trying to export in CoreML format, you might be facing such issues if the tensor is modified in place during the `torch.jit.trace`.

Kindly note that any changes made on the tensor in-place during the trace operation can lead to discrepancies between the original and the traced model's outputs, which in turn can raise an error.

I'd recommend checking your model for any in-place operations and replacing them with out-of-place equivalents or cloning the tensor before modifications. Please ensure the results do not deviate while making these changes.
