### ISSUE TITLE
Loss masking for training a single YOLOv8 model on multiple datasets, each one with a different annotation standard?

### ISSUE THREAD

**Issue by PabloMessina** [ultralytics/ultralytics#2765]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I'm the  same guy from [this question](https://github.com/ultralytics/ultralytics/issues/1724). I have another question now.

I want to use two datasets. Each dataset uses the same kind of images, but dataset 1 uses convention 1 for annotating bounding boxes, and dataset 2 uses convention 2 for annotating bounding boxes.

I want my YOLOv8 model (**a single model**) to **benefit from both annotations**. A straightforward solution is to merge both annotations and configure YOLOv8 to predict the union of the bounding boxes and classes, and so when an image is sampled from dataset 1, only annotations from convention 1 will be present and the rest will be set to some default value that indicates "don't care" (and likewise for an image sampled from dataset 2).

The only thing I'm missing in this approach is how to apply masking to the loss function of YOLOv8 so that the "don't care" values are ignored.

How can this be done? Is this something already implemented in the library?

I'm also open to trying other approaches to the problem that don't require loss masking.

**Comment by glenn-jocher** [comment]
@PabloMessina hi there! Thanks for reaching out. Yes, you can certainly benefit from both annotations by merging them and configuring YOLOv8 to predict the union of the bounding boxes and classes. Regarding applying masking to the loss function, you can use the ignore index parameter in the loss function to ignore certain classes, which in your case could be the "don't care" values. This is not currently implemented in the library as each use case can vary, but you can find examples on how to do this in the PyTorch documentation. As for other approaches, you can also consider fine-tuning a YOLOv8 model pre-trained on one dataset with the annotations from the other dataset. Let me know if you have any other questions or concerns.

**Comment by PabloMessina** [comment]
Hi @glenn-jocher, sorry, I was a bit busy with other things, but now I'm ready to work on this. I'm looking at the source code of the loss function used by YOLOv8 for object detection, found here: https://github.com/ultralytics/ultralytics/blob/8940a27bdb26895f09a1554514a9a46312aa89c3/ultralytics/yolo/utils/loss.py#L82

```python
# Criterion class for computing Detection training losses
class v8DetectionLoss:

    def __init__(self, model):  # model must be de-paralleled

        device = next(model.parameters()).device  # get model device
        h = model.args  # hyperparameters

        m = model.model[-1]  # Detect() module
        self.bce = nn.BCEWithLogitsLoss(reduction='none')
        self.hyp = h
        self.stride = m.stride  # model strides
        self.nc = m.nc  # number of classes
        self.no = m.no
        self.reg_max = m.reg_max
        self.device = device

        self.use_dfl = m.reg_max > 1

        self.assigner = TaskAlignedAssigner(topk=10, num_classes=self.nc, alpha=0.5, beta=6.0)
        self.bbox_loss = BboxLoss(m.reg_max - 1, use_dfl=self.use_dfl).to(device)
        self.proj = torch.arange(m.reg_max, dtype=torch.float, device=device)

    def preprocess(self, targets, batch_size, scale_tensor):
        """Preprocesses the target counts and matches with the input batch size to output a tensor."""
        if targets.shape[0] == 0:
            out = torch.zeros(batch_size, 0, 5, device=self.device)
        else:
            i = targets[:, 0]  # image index
            _, counts = i.unique(return_counts=True)
            counts = counts.to(dtype=torch.int32)
            out = torch.zeros(batch_size, counts.max(), 5, device=self.device)
            for j in range(batch_size):
                matches = i == j
                n = matches.sum()
                if n:
                    out[j, :n] = targets[matches, 1:]
            out[..., 1:5] = xywh2xyxy(out[..., 1:5].mul_(scale_tensor))
        return out

    def bbox_decode(self, anchor_points, pred_dist):
        """Decode predicted object bounding box coordinates from anchor points and distribution."""
        if self.use_dfl:
            b, a, c = pred_dist.shape  # batch, anchors, channels
            pred_dist = pred_dist.view(b, a, 4, c // 4).softmax(3).matmul(self.proj.type(pred_dist.dtype))
            # pred_dist = pred_dist.view(b, a, c // 4, 4).transpose(2,3).softmax(3).matmul(self.proj.type(pred_dist.dtype))
            # pred_dist = (pred_dist.view(b, a, c // 4, 4).softmax(2) * self.proj.type(pred_dist.dtype).view(1, 1, -1, 1)).sum(2)
        return dist2bbox(pred_dist, anchor_points, xywh=False)

    def __call__(self, preds, batch):
        """Calculate the sum of the loss for box, cls and dfl multiplied by batch size."""
        loss = torch.zeros(3, device=self.device)  # box, cls, dfl
        feats = preds[1] if isinstance(preds, tuple) else preds
        pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
            (self.reg_max * 4, self.nc), 1)

        pred_scores = pred_scores.permute(0, 2, 1).contiguous()
        pred_distri = pred_distri.permute(0, 2, 1).contiguous()

        dtype = pred_scores.dtype
        batch_size = pred_scores.shape[0]
        imgsz = torch.tensor(feats[0].shape[2:], device=self.device, dtype=dtype) * self.stride[0]  # image size (h,w)
        anchor_points, stride_tensor = make_anchors(feats, self.stride, 0.5)

        # targets
        targets = torch.cat((batch['batch_idx'].view(-1, 1), batch['cls'].view(-1, 1), batch['bboxes']), 1)
        targets = self.preprocess(targets.to(self.device), batch_size, scale_tensor=imgsz[[1, 0, 1, 0]])
        gt_labels, gt_bboxes = targets.split((1, 4), 2)  # cls, xyxy
        mask_gt = gt_bboxes.sum(2, keepdim=True).gt_(0)

        # pboxes
        pred_bboxes = self.bbox_decode(anchor_points, pred_distri)  # xyxy, (b, h*w, 4)

        _, target_bboxes, target_scores, fg_mask, _ = self.assigner(
            pred_scores.detach().sigmoid(), (pred_bboxes.detach() * stride_tensor).type(gt_bboxes.dtype),
            anchor_points * stride_tensor, gt_labels, gt_bboxes, mask_gt)

        target_scores_sum = max(target_scores.sum(), 1)

        # cls loss
        # loss[1] = self.varifocal_loss(pred_scores, target_scores, target_labels) / target_scores_sum  # VFL way
        loss[1] = self.bce(pred_scores, target_scores.to(dtype)).sum() / target_scores_sum  # BCE

        # bbox loss
        if fg_mask.sum():
            target_bboxes /= stride_tensor
            loss[0], loss[2] = self.bbox_loss(pred_distri, pred_bboxes, anchor_points, target_bboxes, target_scores,
                                              target_scores_sum, fg_mask)

        loss[0] *= self.hyp.box  # box gain
        loss[1] *= self.hyp.cls  # cls gain
        loss[2] *= self.hyp.dfl  # dfl gain

        return loss.sum() * batch_size, loss.detach()  # loss(box, cls, dfl)
```

There are 3 losses: box loss, cls loss and dfl loss. Suppose I want to compute the 3 losses ignoring the model's predictions for some specific classes (the "don't care" classes). I'm not sure how I should modify the code to accomplish that. The self.assigner object seems to be key, because its output goes into the 3 losses. It is an instance of the class TaskAlignedAssigner. I haven't studied the code of that class in detail yet, but I would prefer to hear your input first. Is there a straightforward way to apply "don't cares" (masking) to the 3 losses consistently?

**Comment by PabloMessina** [comment]
@glenn-jocher I suspect that these lines are key:
```python
# targets
targets = torch.cat((batch['batch_idx'].view(-1, 1), batch['cls'].view(-1, 1), batch['bboxes']), 1)
targets = self.preprocess(targets.to(self.device), batch_size, scale_tensor=imgsz[[1, 0, 1, 0]])
gt_labels, gt_bboxes = targets.split((1, 4), 2)  # cls, xyxy
mask_gt = gt_bboxes.sum(2, keepdim=True).gt_(0)
```
What is the meaning of *mask_gt*? I suspect that *mask_gt* could be modified to also mask based on *gt_labels* and an additional variable *dont_care_labels* that could be provided as an additional argument. Would that make sense? I need to make sure that I understand that function of *mask_gt* first.

**Comment by PabloMessina** [comment]
@glenn-jocher I'm looking into the BboxLoss class, and I'm have a feeling that loss masking should be applied here as well:

```python
class BboxLoss(nn.Module):

    def __init__(self, reg_max, use_dfl=False):
        super().__init__()
        self.reg_max = reg_max
        self.use_dfl = use_dfl

    def forward(self, pred_dist, pred_bboxes, anchor_points, target_bboxes, target_scores, target_scores_sum, fg_mask):
        # IoU loss
        weight = torch.masked_select(target_scores.sum(-1), fg_mask).unsqueeze(-1)
        iou = bbox_iou(pred_bboxes[fg_mask], target_bboxes[fg_mask], xywh=False, CIoU=True)
        loss_iou = ((1.0 - iou) * weight).sum() / target_scores_sum

        # DFL loss
        if self.use_dfl:
            target_ltrb = bbox2dist(anchor_points, target_bboxes, self.reg_max)
            loss_dfl = self._df_loss(pred_dist[fg_mask].view(-1, self.reg_max + 1), target_ltrb[fg_mask]) * weight
            loss_dfl = loss_dfl.sum() / target_scores_sum
        else:
            loss_dfl = torch.tensor(0.0).to(pred_dist.device)

        return loss_iou, loss_dfl

    @staticmethod
    def _df_loss(pred_dist, target):
        # Return sum of left and right DFL losses
        # Distribution Focal Loss (DFL) proposed in Generalized Focal Loss https://ieeexplore.ieee.org/document/9792391
        tl = target.long()  # target left
        tr = tl + 1  # target right
        wl = tr - target  # weight left
        wr = 1 - wl  # weight right
        return (F.cross_entropy(pred_dist, tl.view(-1), reduction='none').view(tl.shape) * wl +
                F.cross_entropy(pred_dist, tr.view(-1), reduction='none').view(tl.shape) * wr).mean(-1, keepdim=True)
```

Do you know how I should mask the bounding box loss?

**Comment by glenn-jocher** [comment]
@PabloMessina hi there!

The *fg_mask* in the BboxLoss class stands for "foreground mask" and is used to mask out the background bounding boxes that are not present in an image. Therefore, it is used to ensure that only the relevant bounding boxes contribute to the loss calculation. 

As for using separate parameters to predict bounding boxes for different datasets, it is certainly possible to achieve this by having two separate sets of parameters for the bounding box prediction layer, and using them in the forward pass depending on which dataset is being sampled in the current batch. However, this approach would increase the number of parameters in the model and may also lead to overfitting. Instead, you may consider using multi-task learning, which can learn to predict both datasets' bounding boxes from the same set of parameters.

Regarding loss masking, you can modify the *fg_mask* to include information about the *dont_care_labels* and *gt_labels* so that the loss is not calculated for those bounding boxes. You can achieve this by creating a custom mask and applying it during the loss calculation.

I hope this helps!

**Comment by solyaH** [comment]
Hello, 

I'm tackling a challenge very similar to the one discussed in this issue. I'm merging two datasets (A and B), each with its own label sets (X and Y, respectively). I want to ensure that the training process is not misled by unlabeled instances of set X in dataset B or set Y in dataset A.

To address this, I'm applying an additional mask to the bce loss result (`bce *= labels_mask`; `labels_mask: (b, h*w, num_classes)`). This way, if a sample is from dataset A, I zero out the loss for the labels of set Y. Thus, the Y labels shouldn't contribute to the classification loss of the A samples (and vice versa for dataset B and label set X).

I also considered filtering out the `bboxes` that correspond to the "ignored" classes, but there is already another filtering mechanism applied. My understanding is that when calculating the bbox_loss the model takes into account only those outputs (anchors) which have the corresponding ground-truth bboxes (based on the IoU score). Thus, if the model detects an unlabeled instance, it won't contribute to the loss calculation.

I have two main questions:
1. I'm still curious how the model penalizes the wrong bounding boxes (I suspect the answer lies within the align_metric). Could you elaborate on this?
2. @glenn-jocher You mentioned that "you can modify the _fg_mask_ to include information about the _dont_care_labels_ and _gt_labels_ so that the loss is not calculated for those bounding boxes". Could you provide some guidance on achieving this?

I'd be significantly thankful for any help!

**Comment by glenn-jocher** [comment]
Hello @solyaH,

Thank you for your detailed question and for sharing your approach. It's great to see your proactive steps in addressing the challenge of merging datasets with different label sets.

### Addressing Your Questions

1. **Penalizing Wrong Bounding Boxes:**
   The model penalizes incorrect bounding boxes through the IoU (Intersection over Union) metric, which is used in the `bbox_loss` calculation. The `align_metric` you mentioned likely refers to how well the predicted bounding boxes align with the ground truth boxes. Specifically, the `TaskAlignedAssigner` class assigns targets based on the highest IoU scores. If a predicted bounding box does not align well with any ground truth box, it will have a low IoU score, resulting in a higher loss. This ensures that the model is penalized for incorrect bounding box predictions.

2. **Modifying the `fg_mask` for Loss Masking:**
   To incorporate the "don't care" labels into the `fg_mask`, you can modify the mask to exclude these labels from the loss calculation. Here's a conceptual approach to achieve this:

   ```python
   # Assuming `dont_care_labels` is a tensor of shape (num_classes,) indicating which classes to ignore
   dont_care_labels = torch.tensor([0, 1, 0, 1, ...], device=self.device)  # Example tensor

   # Create a mask for the ground truth labels
   gt_labels_mask = torch.ones_like(gt_labels, dtype=torch.bool)
   for label in dont_care_labels.nonzero(as_tuple=True)[0]:
       gt_labels_mask[gt_labels == label] = False

   # Combine with the existing mask_gt
   mask_gt = mask_gt & gt_labels_mask.unsqueeze(-1)
   ```

   This code snippet creates a mask that excludes the "don't care" labels from the ground truth labels, ensuring they do not contribute to the loss calculation.

### Additional Considerations

Your approach to applying an additional mask to the BCE loss is valid and should help in preventing the model from being misled by unlabeled instances. However, ensure that this masking is consistently applied across all relevant parts of the loss calculation to maintain the integrity of the training process.

If you have any further questions or need additional clarification, feel free to ask. We're here to help!

**Comment by solyaH** [comment]
@glenn-jocher Thanks for taking the time to look into this!

1. I'm still confused about how are the wrong bounding boxes incorporated in the `bbox_loss` calculations if fg_mask filters them out. According to my investigation, `fg_mask` is a simplified view of `mask_pos`, which in turn is calculated as `mask_pos = mask_topk * mask_in_gts * mask_gt`.
    - `mask_topk` - selects the best anchors per bbox based on how well the predicted bbox overlaps the target one;
    - `mask_in_gts` - selects the best anchors per bbox based on the target bboxes location;
    - `mask_gt` - simply masks the present-absent bboxes in the inputs. 

    Since we merge `mask_topk` and `mask_in_gts`, later on in the `bbox_loss` calculation we will only consider those anchors that are associated with targets. What about the other ones? What if most of the top_k best candidates are absolutely different from those that are selected in the `mask_in_gts`?

2. Great thanks for the code example! But my intention is not to filter out the ground truths, but rather to not pay attention to the predictions of the "don't care classes".I guess that it'll be easier to explain by example.
    
    My datasets A and B are concatenated and shuffled (I use `torch.utils.data.ConcatDataset` under the hood), which means that in the same batch there could be samples from both datasets.
    Then let the label sets be `X = [0, 1]` and `Y = [2, 3, 4]`, the overall `num_classes = 5`  and the `bs = 4`. As well, let's assume that the `n_max_boxes = 1`.
    A batch might consist of 2 samples from dataset A and 2 from dataset B. Thus, my `label_mask (bs, n_max_boxes, num_classes)` will look like
    ```
    tensor([[[1, 1, 0, 0, 0]],

            [[1, 1, 0, 0, 0]],

            [[0, 0, 1, 1, 1]],

            [[0, 0, 1, 1, 1]]])
    ```
    This mask is applied after the bce loss is calculated in the [v8DetectionLoss](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/loss.py#L244) (I use the same transformation that are applied to the `gt_labels`, `gt_bboxes` in the [get_targets()](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/tal.py#L163) to properly reshape the mask).
    ```
    # cls loss
    bce = self.bce(pred_scores, target_scores.to(dtype))
    bce *= target_mask # applying a mask here
    loss[1] = bce.sum() / target_scores_sum  # BCE
    ```
    The next step is to ensure that the predicted bboxes of the "don't care" labels don't contribute to the anchor selection and bbox loss. This means that if there are instances of the labels Y detected on dataset A, they shouldn't be counted as misdetections. And I'm struggling to undestand what is the right place to ignore such boxes.

**Comment by glenn-jocher** [comment]
Hi @solyaH,

Thank you for your detailed follow-up! Let's address your questions and concerns:

1. **Incorporation of Wrong Bounding Boxes in `bbox_loss`:**
   The `fg_mask` indeed filters out the background and irrelevant bounding boxes, focusing the loss calculation on the most relevant predictions. The `mask_pos` is a combination of `mask_topk`, `mask_in_gts`, and `mask_gt`, ensuring that only the best anchors and those within ground truth boxes are considered. However, the anchors that are not selected by `mask_pos` are implicitly penalized through the classification loss (`cls_loss`). If a predicted bounding box does not align well with any ground truth box, it will have a low IoU score, resulting in a higher classification loss. This ensures that the model is penalized for incorrect bounding box predictions.

2. **Ignoring Predictions of "Don't Care" Classes:**
   Your approach to applying a mask to the BCE loss is on the right track. To ensure that the predicted bounding boxes of the "don't care" labels do not contribute to the anchor selection and bbox loss, you can modify the `fg_mask` to exclude these classes. Here's a more detailed approach:

   ```python
   # Assuming `dont_care_labels` is a tensor of shape (num_classes,) indicating which classes to ignore
   dont_care_labels = torch.tensor([0, 1, 0, 1, ...], device=self.device)  # Example tensor

   # Create a mask for the ground truth labels
   gt_labels_mask = torch.ones_like(gt_labels, dtype=torch.bool)
   for label in dont_care_labels.nonzero(as_tuple=True)[0]:
       gt_labels_mask[gt_labels == label] = False

   # Combine with the existing mask_gt
   mask_gt = mask_gt & gt_labels_mask.unsqueeze(-1)
   ```

   Additionally, you can modify the `fg_mask` in the `BboxLoss` class to ensure that the "don't care" classes are ignored during the bbox loss calculation:

   ```python
   class BboxLoss(nn.Module):
       def __init__(self, reg_max, use_dfl=False):
           super().__init__()
           self.reg_max = reg_max
           self.use_dfl = use_dfl

       def forward(self, pred_dist, pred_bboxes, anchor_points, target_bboxes, target_scores, target_scores_sum, fg_mask):
           # Apply the mask to exclude "don't care" classes
           fg_mask = fg_mask & (target_scores.sum(-1) > 0).unsqueeze(-1)

           # IoU loss
           weight = torch.masked_select(target_scores.sum(-1), fg_mask).unsqueeze(-1)
           iou = bbox_iou(pred_bboxes[fg_mask], target_bboxes[fg_mask], xywh=False, CIoU=True)
           loss_iou = ((1.0 - iou) * weight).sum() / target_scores_sum

           # DFL loss
           if self.use_dfl:
               target_ltrb = bbox2dist(anchor_points, target_bboxes, self.reg_max)
               loss_dfl = self._df_loss(pred_dist[fg_mask].view(-1, self.reg_max + 1), target_ltrb[fg_mask]) * weight
               loss_dfl = loss_dfl.sum() / target_scores_sum
           else:
               loss_dfl = torch.tensor(0.0).to(pred_dist.device)

           return loss_iou, loss_dfl
   ```

This approach ensures that the "don't care" classes do not contribute to the classification or bounding box loss, maintaining the integrity of your training process.

I hope this helps! If you have any further questions or need additional clarification, feel free to ask. 😊
