### ISSUE TITLE
Yolov8 errors for Azure Multi GPU

### ISSUE THREAD

**Issue by rmbayer** [ultralytics/ultralytics#2766]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Multi-GPU

### Bug

I really tried to do my research, so I hope this isn't something obvious I overlooked.

We were previously using Yolov5 for our training in AzureML and had no issues. I've been stuck on this for Yolov8 for a bit now.

I have tried passing device =0, device=[0,1,2,3], device = '0,1,2,3' and have not had any luck.

### Environment

Docker File ( I need opencv-python-headless for the docker container)
```
FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest

ENV AZUREML_CONDA_ENVIRONMENT_PATH /azureml-envs/acuity_yolov8
# Create conda environment
RUN conda create -p $AZUREML_CONDA_ENVIRONMENT_PATH \
    python=3.8 \
    pip=22.1.2 \
    -c anaconda -c pytorch -c conda-forge

# Prepend path to AzureML conda environment
ENV PATH $AZUREML_CONDA_ENVIRONMENT_PATH/bin:$PATH

# Install Ultralytics dependenciies
RUN pip install 'matplotlib>=3.2.2' \
                'Pillow>=7.1.2' \
                'PyYAML>=5.3.1' \
                'requests>=2.23.0' \
                'scipy>=1.4.1' \
                'torch>=1.7.0' \
                'torchvision>=0.8.1' \
                'tqdm>=4.64.0' \
                'pandas>=1.1.4' \
                'seaborn>=0.11.0' \
                'onnx>=1.12.0 ' \
                'onnxsim>=0.4.1' \  
                'psutil' \ 
                'thop>=0.1.1

RUN pip install --extra-index-url https://download.pytorch.org/whl/cu113 torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0

RUN pip install 'azure-core<1.23.0' \
                'azureml-core==1.48.0' \
                'azureml-defaults==1.48.0' \
                'azureml-dataprep==4.8.6' \
                'onnxruntime-gpu>=1.7,<1.10' \
                'ipykernel~=6.0' \
                'opencv-python-headless==4.7.0.72'

# Ultralytics without dependencies so OpenCV is installed by user
RUN pip install ultralytics==8.0.87 --no-deps

# This is needed for mpi to locate libpython
ENV LD_LIBRARY_PATH $AZUREML_CONDA_ENVIRONMENT_PATH/lib:$LD_LIBRARY_PATH
```

### Minimal Reproducible Example

**yolov8_testing.py**
```
for name, value in os.environ.items():
    print(f"name {name}: {value}")

model = YOLO("yolov8n.pt")
model.train(data='coco128.yaml', epochs=3, device = 0)
results = model.val()  # evaluate model performance on the validation set
success = model.export(format="onnx")  # export the model to ONNX format

# Copy training artifacts to outputs folder
src_path = f"./runs/"
dst_path = f"./outputs/"
shutil.copytree(src_path, dst_path, dirs_exist_ok=True)
```

**Azure command to run the job. This should create my Environment variables for RANK, LOCAL-RANK, etc.**
```
job = command(
    compute=gpu_compute_target,
    environment=job_env,
    code="./",  # location of source code
    command=" python yolov8_testing.py",
    experiment_name=job_name,
    tags = {"purpose": "Debug", "process": "SDKv1"},
    # uncomment this part below for multigpu multinodes
    instance_count = 3,  # number of nodes (we don't have quota  for more than 2 nodes)
    distribution={
        "type": "PyTorch",
        # set process count to the number of gpus per node
        "process_count_per_instance": 4,
    },
)
```

**Error**
```
  0%|          | 0.00/755k [00:00<?, ?B/s]
100%|██████████| 755k/755k [00:00<00:00, 39.3MB/s]
Traceback (most recent call last):
  File "yolov8_testing.py", line 36, in <module>
    model.train(data='coco128.yaml', epochs=3, device = [0,1,2,3])
  File "/azureml-envs/acuity_yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 370, in train
    self.trainer.train()
  File "/azureml-envs/acuity_yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 191, in train
    self._do_train(world_size)
  File "/azureml-envs/acuity_yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 266, in _do_train
    self._setup_ddp(world_size)
  File "/azureml-envs/acuity_yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 195, in _setup_ddp
    torch.cuda.set_device(RANK)
  File "/azureml-envs/acuity_yolov8/lib/python3.8/site-packages/torch/cuda/__init__.py", line 314, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Environment Variables printed before the run with some private variables removed**

```
name NVIDIA_VISIBLE_DEVICES: all
name MLFLOW_EXPERIMENT_NAME: Acuity_yolov8_testing
name LOCAL_RANK: 0
name AZUREML_CR_CS_CAPABILITY_RUNNING: TRUE
name AZUREML_PROCESS_NAME: rank_4
name MASTER_PORT: 6105
name AZ_BATCHAI_GPU_COUNT: 4
name AZUREML_NODE_COUNT: 3
name AZUREML_CR_NODE_RANK: 1
name NCCL_SOCKET_IFNAME: eth0
name WORKER_TIMEOUT: 300
name NCCL_DEBUG: INFO
name AZUREML_COMPUTE_RESERVED_DISK_SPACE: 10400000000
name WORLD_SIZE: 12
name CONDA_PACKAGE: 22.11.1
name DATASET_RSLEX_UPLOAD: true
name AZ_BATCH_JOB_ID: keen_horse_cv2yr43z3n
name MLFLOW_DISABLE_ENV_MANAGER_CONDA_WARNING: True
name OPENMPI_VERSION: 4.1.0
name AZUREML_RUN_ID: keen_horse_cv2yr43z3n
name AZUREML_ROOT_RUN_ID: keen_horse_cv2yr43z3n
name NCCL_IB_TIMEOUT: 22
name SHLVL: 0
name NODE_RANK: 1
name MINICONDA_VERSION: py38_4.12.0
name NCCL_IB_DISABLE: 1
name RANK: 4
name MSI_ENDPOINT: http://localhost:46809/MSI/token
name DATASET_MOUNT_BLOCK_BASED_CACHE_ENABLED: false
name AZUREML_CR_CORRELATION_ID: keen_horse_cv2yr43z3n
name DEBIAN_FRONTEND: noninteractive
name NUMEXPR_MAX_THREADS: 8
name CUBLAS_WORKSPACE_CONFIG: :4096:8
name TF_CPP_MIN_LOG_LEVEL: 2
```

With Yolov5, I would run this and receive no errors
```
job = command(
    compute=gpu_compute_target,
    environment=job_env,
    code="./",  # location of source code
    command=python yolov5/train.py \
    --batch 192 \
    --data testing_yaml.yaml \
    --weights yolov5/yolov5s.pt \
    --cfg yolov5/models/yolov5s.yaml \
    --epochs 3 \
    --patience 50 \
    --hyp yolov5/data/hyps/hyp.scratch-low.yaml \
    --img-size 640,
    experiment_name=job_name,
    tags = {"purpose": "Debug", "process": "SDKv1"},
    # uncomment this part below for multigpu multinodes
    instance_count = 3,  # number of nodes (we don't have quota  for more than 2 nodes)
    distribution={
        "type": "PyTorch",
        # set process count to the number of gpus per node
        "process_count_per_instance": 4,
    },
)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@rmbayer also if you're having issues with an environment I'd recommend training in our Docker image:

## Environments

YOLOv8 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/GCP-Quickstart)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/AWS-Quickstart)
- **Docker Image**. See [Docker Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

**Comment by rmbayer** [comment]
I'm not entirely sure how I would use your docker container with Azure, but I will look into it.

```
  File "yolov8_testing.py", line 36, in <module>
    model.train(data='coco128.yaml', epochs=3, device = [0,1,2,3], batch=96)
  File "/azureml-envs/acuity_yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 370, in train
    self.trainer.train()
  File "/azureml-envs/acuity_yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 191, in train
    self._do_train(world_size)
  File "/azureml-envs/acuity_yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 266, in _do_train
    self._setup_ddp(world_size)
  File "/azureml-envs/acuity_yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 195, in _setup_ddp
    torch.cuda.set_device(RANK)
  File "/azureml-envs/acuity_yolov8/lib/python3.8/site-packages/torch/cuda/__init__.py", line 314, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

Is still what I am getting on my end. Not sure if anyone one else has experienced this or has advice.

**Comment by glenn-jocher** [comment]
@rmbayer thank you for bringing this issue to our attention. The error message you are seeing mentions an invalid device ordinal, which can happen when you are trying to access a GPU device that does not exist on your system. There could be several reasons for this, such as an incompatible CUDA version or an incorrectly installed driver. 
We recommend double-checking that your CUDA and PyTorch versions are compatible, and ensuring that your GPU driver is up-to-date. You may also try setting the `CUDA_LAUNCH_BLOCKING` environment variable to 1 to get a more detailed error message that can help identify the problem.

**Comment by adimux** [comment]
Currently, Yolov8 code is not compatible with multi-GPU training at all. It assumes that all GPUs are part of one machine, hence the error "CUDA wrong device ordinal" (the process rank for processes out of the main host is higher than the number of GPUs).

I dug deep into it and filed an issue [https://github.com/ultralytics/ultralytics/issues/2132](#2132). If you want, I can create a PR and submit a fix, because i was able to identify multiple parts in the code that are using RANK when they should be using LOCAL_RANK and are making wrong assumptions.

**Comment by rmbayer** [comment]
Yes, I came to the same conclusion. When using RANK rather than LOCAL_RANK. I get an index out of range error. I was able to print the os.environ variables and see that I am getting index out of range error. YOLOv5 uses LOCAL_RANK in it's call to the init torch distributed whereas YOLOv8 uses RANK. A PR for this issue would be great!

**Comment by glenn-jocher** [comment]
@rmbayer thank you for letting us know about this issue. It's great to hear that you have identified the problem and are willing to submit a fix. We appreciate your contribution to the YOLOv8 codebase. It looks like the code is currently using `RANK` instead of `LOCAL_RANK`, causing an index out of range error when running multi-GPU training. Updating these instances to use `LOCAL_RANK` instead should resolve this problem. If you would like to submit a PR to resolve the issue, please feel free to do so. We appreciate your help in improving the YOLOv8 codebase for everyone!

**Comment by ElianoMarques** [comment]
same issue here. @adimux thanks for your help with this. please if you could share when you fix it that would be great. back to v5 seems to be the only away around it for now?

**Comment by robtoth** [comment]
> @rmbayer thank you for letting us know about this issue. It's great to hear that you have identified the problem and are willing to submit a fix. We appreciate your contribution to the YOLOv8 codebase. It looks like the code is currently using `RANK` instead of `LOCAL_RANK`, causing an index out of range error when running multi-GPU training. Updating these instances to use `LOCAL_RANK` instead should resolve this problem. If you would like to submit a PR to resolve the issue, please feel free to do so. We appreciate your help in improving the YOLOv8 codebase for everyone!

Hello. Was this ever fixed? Looking to do some multi-node training on yolov8.

**Comment by glenn-jocher** [comment]
@robtoth hello! We are continuously working on improvements and fixes for YOLOv8. Unfortunately, I can't confirm the status of this specific issue at the moment. We do encourage you to update to the latest version of YOLOv8, if you haven't done so already, as this may resolve your problem. We appreciate your patience and interest in the YOLOv8 project, and all contributions towards making this tool better are welcome. If the problem persists after updating, please feel free to open a new issue thread on GitHub. Thank you!
