### ISSUE TITLE
Image_weights arg for yolov8

### ISSUE THREAD

**Issue by 3428232535** [ultralytics/ultralytics#2768]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I want to use image-weights strategy for my dataset in yolov8. But I could not find that arg in YOLO.train().
It seemed it was moved to v5loader and might be deprecated in the future.So is there any solution for that?

**Comment by glenn-jocher** [comment]
@3428232535 hello! Thank you for reaching out. The `image_weights` strategy is not currently supported in YOLOv8 directly with the `YOLO.train()` method. However, you can still use this strategy by writing a custom PyTorch data loader that loads images with different weightings based on an input list of weights. Alternatively, you can use the `weights` argument in the detection results to apply different weights to different detected objects.

I hope this helps! Let me know if you have any further questions or concerns.
