### ISSUE TITLE
Is "override custum config.yaml" in "default.yaml" an inoperative field?

### ISSUE THREAD

**Issue by ss-hyun** [ultralytics/ultralytics#2770]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

"default.yaml" has the following fields.
```
...
# Custom config.yaml ---------------------------------------------------------------------------------------------------
cfg:  # for overriding defaults.yaml
...
```
I thought it was to get the property "custom_config.yaml"and override it to default.
But it doesn't work, and I'm confused about what that field is used for.

**Comment by glenn-jocher** [comment]
Hello @ss-hyun! The `cfg` field in `default.yaml` allows you to override the default `config.yaml` file. You can specify a path to a custom `config.yaml` file that will be used instead of the default one. If you don't need to use a custom `config.yaml` file, you can leave this field blank or remove it altogether. Please ensure that the path to your custom file is correctly specified relative to the current working directory or using an absolute path. Let us know if you continue to have issues with this field and we will be happy to help!

**Comment by ss-hyun** [comment]
Thank you for your kind reply.

I've tried many things, but the problem persists.

What criteria should I set the path to the custom config.yaml file? I've used all the absolute paths, git source code top-level folder-based relative paths, and the relative paths under them, but the custom config file I wrote in the cfg field of default.yaml doesn't load. Is the name of the custom config file limited to config.yaml?

**Comment by glenn-jocher** [comment]
Hello @ss-hyun, glad to be of help! The path to the custom `config.yaml` file should be relative to the current working directory or using an absolute path. You can use either forward slashes (`/`) or backslashes (`\`) to separate directories on different platforms. However, note that some characters might need to be escaped if using backslashes on Windows. 

You can specify a custom `config.yaml` file name other than the default using the `cfg` field in `default.yaml`. Please make sure that the path you provide is valid and correctly references your custom `config.yaml` file. The specified file path should be relative to the current working directory or use an absolute path and the file name can be any valid file name, not just `config.yaml`. Additionally, ensure that the custom config file syntax is valid and that it is located in the specified path.

I hope this helps! Let me know if you have any further questions.
