### ISSUE TITLE
Use new jpg to improve pretrained model

### ISSUE THREAD

**Issue by biscowar** [ultralytics/ultralytics#2773]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained my model yolov8 for example with 100 jpg of a ferrari and 200 jpg of a porsche
now i want to improve my model and train with 2000 more jpg of the ferrari.
I have to train again the whole model or i can add to the previus one?
Thx

**Comment by glenn-jocher** [comment]
@biscowar you should combine all your data into one dataset and then start training from your pretrained model, i.e.:
```
yolo train model=path/to/best.pt data=new_combined_data.yaml
```
