### ISSUE TITLE
The "ultralytics 8.0.4" breaks prediction.

### ISSUE THREAD

**Issue by mzhen77** [ultralytics/ultralytics#278]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

` model("https://ultralytics.com/images/bus.jpg")`
gives
`<generator object BasePredictor.__call__ at 0x000001F8B8452500>`

The same line in version "8.0.3" gives the correct result.

### Environment

YOLOv8.0.4  Python-3.10.4 torch-1.12.0 CUDA:0 (Quadro RTX 6000, 24576MiB)
Windows 10 Enterprise, 21H2.

### Minimal Reproducible Example

Code from docs:

```Python
from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.yaml")  # build a new model from scratch
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

# Use the model
results = model.train(data="coco128.yaml", epochs=3)  # train the model
results = model("https://ultralytics.com/images/bus.jpg")  # predict on an image```

**Comment by Laughing-q** [comment]
hi @mzhen77, yeah we treat model.predict() as a generator now, we added a `return_outputs` arg to make sure users can get outputs and do whatever they want with it. Sorry the Docs haven't updated.
It's set to `True` as default in python interface, and you can set `return_outputs=False` then it should work as you expect.

Actually I'm considering making it `False` as default. Anyway if there's related updates, I'll let you know.:)
