### ISSUE TITLE
Validation on images of original size (no resizing)

### ISSUE THREAD

**Issue by ilia-chelak** [ultralytics/ultralytics#2781]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello all,

In my project I have found out that it is highly beneficial to use YOLO without resizing images on my custom dataset. So I was wondering if it is possible to run validation pipeline on batch size of 1 with images of original size? I have been struggling with this for quite a while and found no discussions on this topic. I am also new to YOLO and have been thinking that the only thing I can do is rewrite the source code but that would be a nightmare with how convoluted it is. So I would be really grateful if someone could point out an easier solution.

**Comment by Kayzwer** [comment]
yolo split image to n * n tile, https://arxiv.org/pdf/1506.02640.pdf

**Comment by ilia-chelak** [comment]
@Kayzwer Yes, I understand that. The thing is I can run YOLO in predict mode on images of various sizes with no problems by specifying imgsz of the original image. The difficult part is that I can not do that in validation mode as it requires imgsz parameter to rescale all the images in a batch. So the question is how to get around that limitation (I understand that all the images in a batch should be of the same size but processing images of various sizes should not be a problem with a batch size of 1)

**Comment by glenn-jocher** [comment]
Hello @ilia-chelak, 

In YOLOv8, the validate() method is designed to validate on batches of images, unlike the predict() method which can handle individual images. Batch processing ensures that the GPU can operate on multiple images at the same time, leading to a significant increase in inference speed. However, as you have pointed out, all images in a batch must be the same size.

To validate on images of various sizes, you would need to perform a series of independent validation runs, each with its own unique batch of similarly sized images. One workaround to achieve this would be to split the original image into a grid of tiles, and process each tile as an individual image. You can then combine the predictions from all tiles to produce a final prediction for the entire image. This approach is discussed in the YOLOv8 paper, Section 3.1.

I hope this helps. Let us know if you have any further questions.

**Comment by ilia-chelak** [comment]
Thanks, in the end, I have used custom dataloader and `model.predict()` to collect the statistics and plot confusion matrices by myself

**Comment by glenn-jocher** [comment]
Hello @ilia-chelak,

Thank you for sharing your solution! We are glad that you were able to resolve your issue by using a custom dataloader and the `model.predict()` method.

Custom dataloaders are a powerful feature in YOLOv8 that allow you to read your own dataset in a flexible and efficient manner. The predict() method is particularly useful as it can operate on individual images or on batches of images, making it easy to use in a wide range of applications.

We hope you continue to have a positive experience with YOLOv8 and please feel free to reach out if you have any further questions or issues.

Best regards,
Glenn Jocher and the Ultralytics team
