### ISSUE TITLE
Auto_annotate and Convert_json function not found

### ISSUE THREAD

**Issue by adrianfernandeziturcemi** [ultralytics/ultralytics#2782]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Hi, im working from google colab to test this functionalities, however it isnt able to find that import

![imagen](https://github.com/ultralytics/ultralytics/assets/118820735/0da5c818-f990-4eeb-8528-232430b5345f)

Same with the function convert_coco

Could anyone tell me if i am missing something?, on the same notebook i have previously imported YOLO, train and even do some infereence in images.

### Environment

- YOLO ultralytics v8
- Google Colab
- linux

### Minimal Reproducible Example

!pip install ultralytics==8.0.20
import ultralytics
from ultralytics.yolo.data.annotator import auto_annotate

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@adrianfernandeziturcemi hello! Thank you for reaching out to us with your question about the `auto_annotate()` and `convert_coco()` functions in YOLOv8.

It seems that prior to calling these functions you need to:

    - Import `from yolov5.utils import auto_annotate, convert_coco`
    
    - Do `!pip install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'`


After doing these steps, you should be able to use the `auto_annotate()` and `convert_coco()` functions.

Let us know if you encounter any other issues or if you have any further questions. We're glad to help!

**Comment by adrianfernandeziturcemi** [comment]
I have tried the solution you gave in another post https://github.com/ultralytics/ultralytics/issues/2673#issuecomment-1560468858 too but i have still a few questions.

1. The solution given in the comment i referenced lets me import auto_annotate but i still have the error not found with convert_coco
![imagen](https://github.com/ultralytics/ultralytics/assets/118820735/a892a3e1-2802-4edb-b39b-f25c0d4bc5b6)


3. The solution given in the comment i referenced force me to reinitialize the notebook because i am importing again yolo 
My code to import yolo is as follows:

first: 
# Pip install method (recommended)

!pip install ultralytics==8.0.20

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image


Then as you suggested i do:
!pip install -U yolov8

which gives me the following warning/error 
![imagen](https://github.com/ultralytics/ultralytics/assets/118820735/ccadcb79-f871-44a7-9e7f-f37ca4c56ed3)

Which way i should import YOLO? is there a difference between installing ultralytics and installing yolov8?

4. In :
> @adrianfernandeziturcemi hello! Thank you for reaching out to us with your question about the `auto_annotate()` and `convert_coco()` functions in YOLOv8.
> 
> It seems that prior to calling these functions you need to:
> 
> ```
> - Import `from yolov5.utils import auto_annotate, convert_coco`
> 
> - Do `!pip install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'`
> ```
> 
> After doing these steps, you should be able to use the `auto_annotate()` and `convert_coco()` functions.
> 
> Let us know if you encounter any other issues or if you have any further questions. We're glad to help!

You suggest that i import auto_annotate and convert_coco from yolov5 packages, would that result in a problem given that i am using yolov8 to train/test ?


Thank you for your time

**Comment by glenn-jocher** [comment]
Hi @adrianfernandeziturcemi,

We're sorry to hear that you're having trouble using the `convert_coco()` function. We're glad to help!

Regarding the installation, you should only need to install the `ultralytics` package with `!pip install ultralytics==8.0.20`. You shouldn't need to install `yolov8` separately. Please make sure to restart your notebook after running the installation command.

Regarding the `convert_coco()` function, this function is actually not implemented in YOLOv8. Instead, you can use the `Ultralytics` function `convert2coco()` to convert YOLO-formatted annotations to COCO format. Please refer to the [YOLOv8 documentation on annotation conversion](https://docs.ultralytics.com/tasks/convert/).

Regarding `auto_annotate()`, as you mentioned, there's an issue with importing this function. Please try:

```
from ultralytics.yolo.data.annotator import auto_annotate
```

instead of 

```
from yolov5.utils import auto_annotate
```

Please make sure to also install the COCO API as indicated in the documentation.

Let us know if you have any further questions or if you encounter any issues. We're here to help!

**Comment by glenn-jocher** [comment]
Hello @adrianfernandeziturcemi,

We apologize for any confusion caused by our previous response. We would like to clarify that the `convert_coco()` function is not implemented in YOLOv8 and is not available in the `ultralytics` package.

However, you can convert YOLO-formatted annotations to COCO format using the `convert2coco()` function, which is available in the `ultralytics` package. You can refer to the [YOLOv8 documentation on annotation conversion](https://docs.ultralytics.com/tasks/convert/) for more information on how to use this function.

Regarding the `auto_annotate()` function, the correct import statement in YOLOv8 is:

```
from ultralytics.yolo.data.annotator import auto_annotate
```

Regarding the broken documentation link, we apologize for the inconvenience. We will work to resolve the issue as soon as possible.

Please let us know if you have any further questions or encounter any issues. We are happy to help!

**Comment by adrianfernandeziturcemi** [comment]
@glenn-jocher  the import for the auto_annotate function as stated in this reply


> Hello @adrianfernandeziturcemi,
> 
> We apologize for any confusion caused by our previous response. We would like to clarify that the `convert_coco()` function is not implemented in YOLOv8 and is not available in the `ultralytics` package.
> 
> However, you can convert YOLO-formatted annotations to COCO format using the `convert2coco()` function, which is available in the `ultralytics` package. You can refer to the [YOLOv8 documentation on annotation conversion](https://docs.ultralytics.com/tasks/convert/) for more information on how to use this function.
> 
> Regarding the `auto_annotate()` function, the correct import statement in YOLOv8 is:
> 
> ```
> from ultralytics.yolo.data.annotator import auto_annotate
> ```
> 
> Regarding the broken documentation link, we apologize for the inconvenience. We will work to resolve the issue as soon as possible.
> 
> Please let us know if you have any further questions or encounter any issues. We are happy to help!

Doesn't work

**Comment by adrianfernandeziturcemi** [comment]
OK so after checking the packages and a quick review of the git repository i tried to change my import of yolo which was:

!pip install ultralytics==8.0.20

to

!pip install ultralytics==**8.0.112**

and after that the import for auto_annotate works :
from ultralytics.yolo.data.annotator import auto_annotate.

I m still trying to figure out the convert2coco function though

**Comment by glenn-jocher** [comment]
@adrianfernandeziturcemi hello!

We're glad to hear that you were able to import `auto_annotate()` successfully with the help of `ultralytics==8.0.112`. As for the `convert2coco()` function, this function is used to convert YOLO-formatted annotations to COCO format.

To use the `convert2coco()` function in YOLOv8, you first need to initialize a `YOLO` object with the `weights` parameter set to the path of your YOLOv8 model weights and the `conf` parameter set to the desired detection confidence threshold. Then, you can use the `convert2coco()` function to convert your YOLO-formatted annotations to COCO format.

For example:

```
from ultralytics import YOLO

yolo = YOLO(weights='path/to/weights', conf=0.5)
coco_dict = yolo.convert2coco('path/to/annotations')
```

The `convert2coco()` function returns a dictionary in COCO annotation format. You can save this dictionary to a JSON file using the `json.dump()` function from the `json` Python module.

Please let us know if you have any further questions or need any further assistance. We're here to help!

**Comment by mfkeles** [comment]
> @adrianfernandeziturcemi hello!
> 
> We're glad to hear that you were able to import `auto_annotate()` successfully with the help of `ultralytics==8.0.112`. As for the `convert2coco()` function, this function is used to convert YOLO-formatted annotations to COCO format.
> 
> To use the `convert2coco()` function in YOLOv8, you first need to initialize a `YOLO` object with the `weights` parameter set to the path of your YOLOv8 model weights and the `conf` parameter set to the desired detection confidence threshold. Then, you can use the `convert2coco()` function to convert your YOLO-formatted annotations to COCO format.
> 
> For example:
> 
> ```
> from ultralytics import YOLO
> 
> yolo = YOLO(weights='path/to/weights', conf=0.5)
> coco_dict = yolo.convert2coco('path/to/annotations')
> ```
> 
> The `convert2coco()` function returns a dictionary in COCO annotation format. You can save this dictionary to a JSON file using the `json.dump()` function from the `json` Python module.
> 
> Please let us know if you have any further questions or need any further assistance. We're here to help!

This no longer works! Is there a different way to convert to COCO or some other format to visualize the auto annotated data?
