### ISSUE TITLE
scan a jpg directory

### ISSUE THREAD

**Issue by biscowar** [ultralytics/ultralytics#2786]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

starting from this command line 

yolo task=detect mode=predict model=best.pt source=stelvio.jpg show=True

i need to detect all file in a directory instead off single file like in the above command

how can i do it?

**Comment by AyushExel** [comment]
You can just pass the dir as the source
```
yolo task=detect mode=predict model=best.pt source=path/to/dir show=True
```
