### ISSUE TITLE
RT-DETR inference run is giving strange error (datatype error)

### ISSUE THREAD

**Issue by Adeelbek** [ultralytics/ultralytics#2796]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I wanted to try use recent update of ultralytics with RT-DETR. 
I follow the documents and instructions in this link https://docs.ultralytics.com/models/rtdetr/#pre-trained-models
However, when I try to see the detection of RT-DETR using following lines of code:

```
from ultralytics import RTDETR

model = RTDETR("rtdetr-l.pt")
model.info()  # display model information
model.predict("bus.jpg")  # predict

 ```

This code is giving me following error:
```
RuntimeError: expected scalar type float but found double
```

I did not understand why model is asking me to change or modify the input data type since i am not doing any training. 
Am I doing something wrong in  here ?

### Additional

No attachment

**Comment by glenn-jocher** [comment]
Hello @Adeelbek, thanks for reaching out! 

The issue seems to be related to a data type mismatch in the input image. The error message "expected scalar type float but found double" indicates that the input image is in double data type format but the model is expecting a float data type format. 

To fix this issue, please convert your input data type to float32 using the following code:
```
from PIL import Image
import numpy as np

input_image = Image.open("bus.jpg")
input_image = np.array(input_image).astype(np.float32)
```

Then, you can call the model.predict function:
```
model.predict(input_image)
```

Please give this a try and let us know if this solves the issue.

**Comment by Adeelbek** [comment]
Hello Glenn 

Thanks for your quick feedback. 
I have tried the solution you mentioned above but it still gives the same error. 
I am not sure but I think it happens due to some data conversion within the pipeline or it can be due to another issue. 
Anyway, I am attaching my vs code snapshot below.  
If this happens with the images, then what would be the way around when we test with video data? 

Thanks ))

![image](https://github.com/ultralytics/ultralytics/assets/25815077/b6b31d8e-77b9-4910-9344-9691330caff0)

**Comment by glenn-jocher** [comment]
Hello @Adeelbek, thank you for trying the solution. 

Based on the VS code snapshot you provided, it appears that you are passing an image path as an argument to the `predict()` method. Please note that the `predict()` method expects a NumPy array or a list of NumPy arrays representing images. 

So, you could pass the input image into the `predict()` method in the following way:

```
input_image = Image.open("bus.jpg")
input_image = np.array(input_image).astype(np.float32)
model.predict([input_image])
```

Regarding your question about testing with video data, YOLOv8 has a `predict()` method for video, `predict_video()`, specifically designed for video inputs. This method takes a video file path as input and returns a generator that outputs one frame at a time. This generator can be iterated to get the detected objects in each video frame and work with them accordingly. 

Please give the above a try for the image input and let us know if it works for you. If you have any further questions please feel free to ask.

**Comment by Laughing-q** [comment]
@Adeelbek hi, I'm not able to reproduce your error.
![image](https://github.com/ultralytics/ultralytics/assets/61612323/d30d516a-7966-41cc-92de-62d9a81e1f34)
probably it's related to torch version, what's your torch version? I'm using torch-2.0

**Comment by Adeelbek** [comment]
![output_detr](https://github.com/ultralytics/ultralytics/assets/25815077/2a0c07b9-3135-4350-9e73-cd611573f4b0)

**Comment by Adeelbek** [comment]
![output_detr](https://github.com/ultralytics/ultralytics/assets/25815077/1975e86d-e4cd-4a5b-8a8d-8f814f430420)

**Comment by Adeelbek** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/25815077/f5ec38f1-6c80-4cb5-bfa3-5a27dcf566ad)

**Comment by glenn-jocher** [comment]
Hello @Adeelbek, thanks for reaching out to us! 

The error message you received indicates that the model was not able to find the path of the output directory. 

To fix this issue, please make sure that you have created the output directory and that the path you have specified in the `save_dir` parameter is correct and valid. 

Additionally, please make sure that you have the proper permissions to create and write to the specified directory. Sometimes permission issues may prevent the model from saving the outputs. 

If you continue to have issues with the `save()` method, feel free to provide us with more details about your setup and we will do our best to assist you.
