### ISSUE TITLE
How to make runs folder False during model.val() 

### ISSUE THREAD

**Issue by TapendraBaduwal** [ultralytics/ultralytics#2798]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

model = YOLO(best.pt)
metrics = model.val(data=data.yaml,
                            plots=False,
                            ) 
metrics.box.map50

I want only map50 score but script creat runs folder automatically...i make plots False then runs folder creat with plots false but i do not want runs folder ..just want map50 score only?

**Comment by glenn-jocher** [comment]
@TapendraBaduwal hello! If you don't want the "runs" folder to be created during `model.val()`, you can set the `opt.save_dir` parameter to `None`. This will prevent any output from being saved to disk. However, this will not affect the output metrics, which should still include the `metrics.box.map50` score that you are interested in. Let me know if you have any further questions!

**Comment by TapendraBaduwal** [comment]
@glenn-jocher In which location we have to set opt.save_dir parameter to None ....

**Comment by glenn-jocher** [comment]
Hello @TapendraBaduwal,

You can set the `opt.save_dir` parameter to `None` within the `val.yaml` configuration file in your `ultralytics/yolov8/data` directory. Specifically, you can set the `save_dir` parameter in the `[logging]` section of the YAML file to `null` or `~`, which represents a null or empty value.

Alternatively, you can modify the `yolo.py` file directly to change the behavior of the `model.val()` function. Specifically, you can modify the `val` function in `yolo.py` to include the `save_dir` parameter and set it to `None` directly, like so: `metrics = model(val=True, data=data, save_dir=None)`.

I hope this helps! Let me know if you have any further questions.
