### ISSUE TITLE
Unable to use "save_txt: True" in "pose track"

### ISSUE THREAD

**Issue by lhunout** [ultralytics/ultralytics#2803]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Traceback (most recent call last):
  File "/opt/conda/bin/yolo", line 33, in <module>
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())
  File "/usr/src/ultralytics/ultralytics/yolo/cfg/__init__.py", line 391, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/src/ultralytics/ultralytics/yolo/engine/model.py", line 275, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/src/ultralytics/ultralytics/yolo/engine/model.py", line 252, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/usr/src/ultralytics/ultralytics/yolo/engine/predictor.py", line 176, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/usr/src/ultralytics/ultralytics/yolo/engine/predictor.py", line 252, in stream_inference
    s += self.write_results(i, self.results, (p, im, im0))
  File "/usr/src/ultralytics/ultralytics/yolo/engine/predictor.py", line 160, in write_results
    result.save_txt(f'{self.txt_path}.txt', save_conf=self.args.save_conf)
  File "/usr/src/ultralytics/ultralytics/yolo/engine/results.py", line 284, in save_txt
    kpt = (kpts[j][:, :2] / d.orig_shape[[1, 0]]).reshape(-1).tolist()
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### Environment

- Ultralytics 8.0.91 
- Python 3.10.9
- CUDA 12.0 

### Additional

Hello everyone,

The main notable parameters for the problem are:
task: pose
mode: track
save_txt: True
It is important to note that the problem does not persist in mode: predict.

I managed to fix the problem by manually changing the following line:
kpt = (kpts[j][:, :2] / d.orig_shape[[1, 0]]).reshape(-1).tolist()
By this one:
kpt = (kpts[j][:, :2].to('cpu') / d.orig_shape[[1, 0]].to('cpu')).reshape(-1).tolist()

The general idea is to move all tensors to the same device.
I don't know if this method is the most optimal. I appreciate your feedback :)

Good day,
Lilian

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@lhunout hello Lilian, thank you for bringing this issue to our attention. 

You have correctly identified that the problem is caused by tensors being moved to different devices. The error message suggests that tensors are present on both CPU and GPU. It is advised to move your model to the same device as the tensors it is processing. You can force copying to a device with a `.to()` function.

Your suggested solution of moving the tensors to CPU with `.to('cpu')` is valid, but it will have a slight slowdown due to the CPU operations. An alternative solution is to enforce all tensors in your code to stay on a device by adding:

```
device = 'cpu' if not torch.cuda.is_available() else 'cuda'
torch.backends.cudnn.benchmark = True
```

This sets the device to use as cuda if you have it, otherwise cpu. cuiDNN will also enable some performance enhancements. 

Please let me know if this solution works for you or if you need any further assistance.

**Comment by glenn-jocher** [comment]
@lhunout great news 😃! Your original issue may now be resolved ✅ in PR #2898 which implements a fix similar to yours.

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by Laughing-q** [comment]
@lhunout hi, actually `save_txt` for pose works to me even without the fix. I suppose this probably is related to the version of pytorch, I'm using 2.0, could you tell me your torch version then I'm able to test it? :) Thanks!

**Comment by lhunout** [comment]
Hello everyone,

@glenn-jocher I confirm that I was using yolo in CLI and not from a script. That's why I had come up with this workaround, which is not unique. I'm glad the issue is fixed. Did you maintain the movement of the tensors towards the CPU?

@Laughing-q I can confirm that I am using version 2.0.0 of PyTorch.

Lilian

**Comment by glenn-jocher** [comment]
@Laughing-q yes you are right, the original code was operating correctly. I've reverted https://github.com/ultralytics/ultralytics/pull/2898 now back to the original code. 

@lhunout the current code should be working correctly. If not please provide a reproducible example showing an error. Thank you!

**Comment by lhunout** [comment]
@Laughing-q @glenn-jocher 

According to my initial post, the problem appeared in the "track" mode and not "predict".

"The main notable parameters for the problem are:
task: pose
mode: track
save_txt: True
It is important to note that the problem **does not persist in mode: predict**."

**Comment by Laughing-q** [comment]
@lhunout ok got it! then that makes sense, track mode would update bboxes to tracks which is in cpu. I'll fix it tomorrow. :)
cc@glenn-jocher

**Comment by Laughing-q** [comment]
@lhunout hi! sorry for the delay, I made a PR #2921  to fix this for track mode. `save_txt` with both `predict` and `track` mode should work properly after this PR.
Thanks for your reporting! :)
