### ISSUE TITLE
加速训练

### ISSUE THREAD

**Issue by q465414859** [ultralytics/ultralytics#2812]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

GPU利用率很低，怎样把利用率提升上去？
![1684970474636](https://github.com/ultralytics/ultralytics/assets/26251132/69a63210-9f3e-45cf-853c-67376b00140d)

**Comment by Kayzwer** [comment]
增加batch size, 可以看得出GPU內存沒有最大化利用，使用Adam，設workers=num of CPU cores，可以的話確保數據存在SSD，這樣的話大部分時間就不會花在讀取數據。

**Comment by q465414859** [comment]
> 增加批量大小，可以看得出国家政治保卫局。参见OGPU內存沒有最大化利用,使用亚当，設workers = CPU核心数，可以的話確保數據存在固态硬盘，這樣的話大部分時間就不會花在讀取數據。

看我现在的配置，而且在预加载时只有一个核心在跑。这很奇怪。CUDA指数也没有连续行的使用。
![image](https://github.com/ultralytics/ultralytics/assets/26251132/cd648b5e-fa51-4935-8f53-b5169cd976ea)

**Comment by q465414859** [comment]
> 增加批量大小，可以看得出国家政治保卫局。参见OGPU內存沒有最大化利用,使用亚当，設workers = CPU核心数，可以的話確保數據存在固态硬盘，這樣的話大部分時間就不會花在讀取數據。

预处理只用了单核，这使得处理时间非常久。导致cuda核心不能持续被使用
![image](https://github.com/ultralytics/ultralytics/assets/26251132/d322db76-9421-413c-bb91-a70809dfc1b6)

**Comment by Kayzwer** [comment]
@q465414859 試試看workers=36

**Comment by q465414859** [comment]
> 
我的就是这个

**Comment by Kayzwer** [comment]
@q465414859 那試試看CLI，如果CLI沒有問題的話，那就標記這個issue爲bug

**Comment by q465414859** [comment]
> issue

我去提个 issue

**Comment by glenn-jocher** [comment]
@q465414859 请问您有什么问题需要帮助解决吗？如果您有问题或疑问，可以您在我们的issue板块里提出具体问题和环境信息，我们的团队将竭诚为您提供技术帮助。

**Comment by glenn-jocher** [comment]
Hello @Kayzwer, thank you for reaching out to us regarding your issue of low GPU utilization and slow processing time when using YOLOv8. 

One way to increase GPU utilization is to increase batch size, although it is important to make sure that GPU memory is not being underutilized as well. Another approach is to use the Adam optimizer and set the number of workers equal to the number of CPU cores. Additionally, storing data in an SSD can help to reduce the time spent on reading data. 

If you have already tried these methods and are still experiencing issues with slow performance, we encourage you to provide us with more specific details about your environment and the issues you are facing by creating an issue in our board. Our team will do our best to help you with any technical issues you are experiencing.
