### ISSUE TITLE
the model memory size which trained by myself is larger than official pretrained, why?

### ISSUE THREAD

**Issue by xkangKK** [ultralytics/ultralytics#2816]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I trained yolov8n-seg model. The size of best.pt is 26.6MB, but the pretrained model is 7.1MB. Why are these two different?

**Comment by Kayzwer** [comment]
best.pt also contain information like epoch, best fitness, model, EMA, updates of EMA(not quite sure what it is), optimizer, training arguments, date, and version. Not sure is the official one removed all information and only keep model.

**Comment by glenn-jocher** [comment]
@xkangKK, good question! The reason why the size of your self-trained best.pt model is larger than the official pretrained model is that the best.pt contains additional information such as the model configuration, training settings `args`, optimizer state, the date and time of the training, and the number of epochs run, which the official pretrained model may not contain. 

The purpose of the official pretrained model is to provide a high-level starting point for users to fine-tune on their own datasets. As a result, the official pretrained model is typically smaller in size as it only contains the weights of a pre-trained model and doesn't contain information specific to any particular training. 

Keep in mind that the size of the weights file can vary depending on the targeted task, the size of the model, and the compression method used. I hope this explanation helps! Let us know if you have any further questions.

**Comment by xkangKK** [comment]
> 

Thanks for your answer. I have reviewed the ”strip_optimizer“ function. It removed several parameters.

**Comment by glenn-jocher** [comment]
@xkangKK thank you for your update. Yes, the `strip_optimizer` function removes optimizer-specific state from the checkpoint, as these values are not needed when performing inference. The remaining parameters that are saved in the checkpoint will be used for inference. Let us know if you have any other questions or if there is anything else we can do to help.
