### ISSUE TITLE
module separation

### ISSUE THREAD

**Issue by mhyeonsoo** [ultralytics/ultralytics#282]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,
Congrats for the release of Yolov8!
I've been having curiosity about the module separation in the yolo model architecture.
It seems like yolo supports classification only model, but I am wondering if it is also available for the localization only task.

What I initially thought were,
1. modifying .yaml file in **models/v8/**
2. modifying script in **nn/tasks.py**

Can I ask for your suggestions or tips for this?
Thanks!

**Comment by matanj83** [comment]
I'm also interested in this. Would be happy also for tips/suggestions of how to modify the training in case it's not easily possible currently. Can I e.g. zero the classification lr?
Many thank!

**Comment by matanj83** [comment]
Thanks for your rapid answer and the wonderful projects!

**Comment by mhyeonsoo** [comment]
Thanks!

**Comment by pderrenger** [comment]
@mhyeonsoo you're welcome! If you have any more questions or need further assistance, feel free to ask. Happy to help!
