### ISSUE TITLE
using on zero shot detection

### ISSUE THREAD

**Issue by saintour** [ultralytics/ultralytics#2822]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I was wondering how to use this in zero shot detection considering I have word embeddings for seen and unseen classes? Can anybody describe? Thanks in advance.

**Comment by glenn-jocher** [comment]
Hello @saintour,

Thank you for your interest in YOLOv8! Zero-shot detection may not be currently natively supported in YOLOv8. However, you may use a variant where you train on seen classes, while leveraging word embeddings directly or as part of your pipeline to recognize unseen classes via a nearest neighbor approach. Our [YOLOv8 Docs](https://docs.ultralytics.com) may serve as a starting point, especially regarding its [custom training and inference usage](https://docs.ultralytics.com/usage/). Good luck with your project!
