### ISSUE TITLE
GPU和CPU使用率过低

### ISSUE THREAD

**Issue by q465414859** [ultralytics/ultralytics#2828]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

尝试过改变workers 和 batch 对速度没有提升反而减低，在预处理中速度只有CPU的单核在工作。cuda核心没有持续的使用中。
![240866700-d322db76-9421-413c-bb91-a70809dfc1b6](https://github.com/ultralytics/ultralytics/assets/26251132/b7705d8d-ba6a-46f9-bb09-dd081a7461d9)
![240864730-cd648b5e-fa51-4935-8f53-b5169cd976ea](https://github.com/ultralytics/ultralytics/assets/26251132/905fb5a3-58a2-4161-9438-717edf4d49d8)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by q465414859** [comment]
> @q465414859 thank you for reporting this issue. We're sorry to hear that you're experiencing low usage of GPU and CPU. In some cases, tweaking the batch size and number of workers may not always increase training speed and can actually have a negative impact on performance. In terms of the usage of CUDA cores, it's important to note that YOLOv8 and other models rely heavily on the GPU's parallel processing capabilities, and not all operations can be parallelized or offloaded onto the GPU. Can you please provide us with more information on your environment, such as the version of PyTorch and CUDA, and the specifications of your GPU and CPU? Additionally, are there any specific errors or warnings that you're encountering? We'll do our best to help you troubleshoot this issue. Thank you for your offer to submit a PR, we greatly appreciate your support for the YOLOv8 community!

很高兴能得到您的回复。我觉得在GPU运算是的速度是可以的。但在预加载中我的CPU只用了1核，特别是把图片加载到内存中时，尤为明显，参考图2
![1685089169719](https://github.com/ultralytics/ultralytics/assets/26251132/8d965e74-7481-4002-bcc5-fee190bbc850)
https://user-images.githubusercontent.com/26251132/240897466-905fb5a3-58a2-4161-9438-717edf4d49d8.png

**Comment by glenn-jocher** [comment]
@q465414859 Thank you for your response and for providing us with more details. We're glad to hear that the GPU is performing well. As for the CPU usage, in the preloading step, it looks like only one core is being used, as shown in your second image. This is likely due to limitations in the codebase and dependencies, such as how the images are loaded into memory. This is an area where we're constantly working to optimize performance, however, some operations may be inherently serial and not easily parallelizable. Can you please provide us with more information on your environment, such as the version of PyTorch and CUDA, and the specifications of your GPU and CPU? If possible, sharing the relevant parts of your training script would also be helpful. We'll continue to investigate this issue and do our best to help you optimize your training workflow. Thanks again for your support and contributions to the YOLOv8 community!

**Comment by q465414859** [comment]
> @q465414859 Thank you for your response and for providing us with more details. We're glad to hear that the GPU is performing well. As for the CPU usage, in the preloading step, it looks like only one core is being used, as shown in your second image. This is likely due to limitations in the codebase and dependencies, such as how the images are loaded into memory. This is an area where we're constantly working to optimize performance, however, some operations may be inherently serial and not easily parallelizable. Can you please provide us with more information on your environment, such as the version of PyTorch and CUDA, and the specifications of your GPU and CPU? If possible, sharing the relevant parts of your training script would also be helpful. We'll continue to investigate this issue and do our best to help you optimize your training workflow. Thanks again for your support and contributions to the YOLOv8 community!

GPU 3060 CPU E5 2696v3  torch 1.13.1+cu117 ultralytics  8.0.54 win10 
[main.zip](https://github.com/ultralytics/ultralytics/files/11581875/main.zip)

**Comment by glenn-jocher** [comment]
@q465414859 Thank you for sharing your environment details and training script. Based on the information you provided, it looks like you're using PyTorch 1.13.1+cu117 and CUDA toolkit 11.7.101 on a Windows 10 machine with an NVIDIA GeForce RTX 3060 GPU and an Intel Xeon E5-2696 v3 CPU. 

Regarding the CPU usage during preloading, it does seem to be a limitation in the codebase and dependencies, as certain operations may not be easily parallelizable. The Ultralytics team is constantly working to optimize performance, but some operations may inherently require serial execution.

One potential solution to increase preloading speed is to use multi-threading, if your CPU has multiple cores available. You can try using Python's threading or multiprocessing libraries to concurrently load images into memory. 

Additionally, we noticed that the versions of PyTorch and CUDA you're using are relatively outdated compared to the latest available versions. Upgrading to the latest version of PyTorch can often bring performance improvements and bug fixes. We recommend updating to the latest PyTorch and CUDA versions and testing whether that resolves your issue.

Thank you for your support and contributions to the YOLOv8 community. We hope this information is helpful in optimizing your training workflow.

**Comment by q465414859** [comment]
> @q465414859 Thank you for sharing your environment details and training script. Based on the information you provided, it looks like you're using PyTorch 1.13.1+cu117 and CUDA toolkit 11.7.101 on a Windows 10 machine with an NVIDIA GeForce RTX 3060 GPU and an Intel Xeon E5-2696 v3 CPU.
> 
> Regarding the CPU usage during preloading, it does seem to be a limitation in the codebase and dependencies, as certain operations may not be easily parallelizable. The Ultralytics team is constantly working to optimize performance, but some operations may inherently require serial execution.
> 
> One potential solution to increase preloading speed is to use multi-threading, if your CPU has multiple cores available. You can try using Python's threading or multiprocessing libraries to concurrently load images into memory.
> 
> Additionally, we noticed that the versions of PyTorch and CUDA you're using are relatively outdated compared to the latest available versions. Upgrading to the latest version of PyTorch can often bring performance improvements and bug fixes. We recommend updating to the latest PyTorch and CUDA versions and testing whether that resolves your issue.
> 
> Thank you for your support and contributions to the YOLOv8 community. We hope this information is helpful in optimizing your training workflow.

多线程预加载的方案 官方有git分支吗？

**Comment by glenn-jocher** [comment]
@q465414859 Glad to hear that our suggestions were helpful! Regarding the use of multi-threading for pre-loading, the official YOLOv8 repo does not currently offer a specific implementation for it. However, you can use Python's built-in threading or multiprocessing libraries to achieve this. There are also several third-party libraries available that can help with multi-threading, such as joblib and concurrent.futures. We recommend reading up on Python multi-threading and experimenting with different techniques to find the best solution for your use case. Let us know if you have any further questions, and thank you for your contributions to the YOLOv8 community!

**Comment by q465414859** [comment]
> @q465414859 Glad to hear that our suggestions were helpful! Regarding the use of multi-threading for pre-loading, the official YOLOv8 repo does not currently offer a specific implementation for it. However, you can use Python's built-in threading or multiprocessing libraries to achieve this. There are also several third-party libraries available that can help with multi-threading, such as joblib and concurrent.futures. We recommend reading up on Python multi-threading and experimenting with different techniques to find the best solution for your use case. Let us know if you have any further questions, and thank you for your contributions to the YOLOv8 community!

我没有阅读过源码，不知道在哪里修改。

**Comment by glenn-jocher** [comment]
@q465414859 Thank you for your response. To implement multi-threading for pre-loading with YOLOv8, you will need to modify the relevant sections of the code that load images into memory. Specifically, you can use Python's built-in threading or multiprocessing libraries to concurrently load images into memory, rather than loading them one at a time in a serial manner. 

We recommend consulting the Python documentation and tutorials for threading and multiprocessing, as well as relevant third-party libraries such as joblib and concurrent.futures, to learn more about how to implement multi-threading in your training script. 

Furthermore, we suggest exploring existing implementations or code snippets online, or reaching out to the YOLOv8 community for guidance and insights. Please let us know if you have any further questions or concerns. Thank you for your support of the YOLOv8 project!
