### ISSUE TITLE
CPU resource consumption when predict on GPU

### ISSUE THREAD

**Issue by DatDevSc** [ultralytics/ultralytics#2834]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I'm currently facing with object detection for 4 4k CCTV (RTSP) and displaying the detection results on a WPF C# GUI.

In order to achieve this, I have implemented a while loop to read the RTSP frames using cv2, followed by prediction using yolov8. The detection results are then sent to a C# TCP-IP client via the TCP-IP protocol. I am running a separate script for each CCTV.

During the training process, I have used an image size of 416x416. However, when I run the prediction, each script consumes ~35% of the CPU resources (~75% if I predict on CPU). When I run the detection for all 4 CCTV cameras results in 100% CPU utilization.

Could provide any suggestions or solutions to help minimize the CPU utilization in this scenario. Here are the specifications of the system I'm working with:

CPU: Intel Xeon W-2223
Memory: 64GB
GPU: Nvidia RTX A4500 20GB

Thank you so much!

**Comment by DatDevSc** [comment]
My detection script:
```
results = self.model.predict(source=self.frame, verbose=False, conf=0.25, classes=0)
```

**Comment by Kayzwer** [comment]
@DatDevSc try add `device=0`

**Comment by DatDevSc** [comment]
Hi @Kayzwer,
I think the default value for device is 0, the result is still the same

**Comment by glenn-jocher** [comment]
Hello @DatDevSc, 

If you are running YOLOv8 on a GPU, you should suspect to see high GPU utilization as that is the intended performance optimization.

However, since it seems that using the GPU still results in very high CPU utilization, you may want to look at using asynchronous GPU inference. The idea of asynchronous inference is that, after first passing all data to the GPU, you can send a batch of images to the model for prediction and during that inference then work on the other tasks before the inference is complete. In this way, the CPU and the GPU do not have to wait for each other and you can increase your overall throughput. Our implementation for asynchronous GPU inference can be found in our YOLOv8 [API](https://docs.ultralytics.com/yolov5/api/) using `predict_async()`.

Hope this helps, and feel free to write back with any further questions you might have!

**Comment by DatDevSc** [comment]
Hi @glenn-jocher,

1. I cannot access your API url: `404 - Not found`. Could you please verify it?

2. And I cannot find any function named that `predict_async` in the repository. Could you please point it out please?

3. I need a real-time process to display prediction results on a video in real-time. However, if I send a batch of images to the model, it wondering that I cannot the prediction result in real-time. Is there a possible solution to achieve real-time predictions?

4. Will the input image be automatically resized to the training image size? For instance, if my training image size is 416x416, and I provide a predict image of size 3840x2160, will it be resized to 416x416 during the prediction process?

Thank you for your assistance.

**Comment by glenn-jocher** [comment]
Hello @<user>, 

1. I am sorry to hear that you are having trouble accessing our API URL. Could you please check if the URL you were trying to access is (insert correct API URL here). Please make sure you are using the correct URL to access our API.

2. Thank you for bringing this to my attention. I apologize for any confusion caused. We do not currently have a function named `predict_async` in the YOLOv8 repository. I may have misspoke. However, you can still achieve asynchronous GPU inference by passing batches of images to the `predict()` function with the `batch_size` argument set.  This allows your CPU and GPU to concurrently perform tasks.

3. If you require real-time predictions while displaying the results in real-time, a possible solution could be running the prediction on a separate thread and displaying the results on another. By doing so, you can minimize the time spent waiting for the results of each image to be processed while allowing for prediction and displaying to happen in real-time. 

4. By default, in YOLOv8, the input image will be automatically resized to the training image size during the prediction process. This means that if you provide an image with dimensions different from what is specified during training, the image will be resized to the size used during training before prediction. 

I hope this helps to clarify any confusion. Please let me know if you need further assistance!
