### ISSUE TITLE
Error: Only support 'predict' and 'val' modes

### ISSUE THREAD

**Issue by adrianosantospb** [ultralytics/ultralytics#2835]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I converted a pt segmentation model to trt. Using the CLI works well, but when I use Python I get this error message above: 

**... /best.engine' must be a *.pt PyTorch model, but is a different type. PyTorch models can be used to train, val, predict and export, i.e. 'yolo export model=yolov8n.pt', but exported formats like ONNX, TensorRT etc. only support 'predict' and 'val' modes, i.e. 'yolo predict model=yolov8n.onnx'.**

I'm using something like this:

`from ultralytics import YOLO
from ultralytics.yolo.utils.ops import scale_image
import cv2
import numpy as np
import matplotlib.pyplot as plt

def predict_on_image(model, img, conf):
    result = model(img, conf=conf)[0]
    cls = result.boxes.cls.cpu().numpy()    
    probs = result.boxes.conf.cpu().numpy() 
    boxes = result.boxes.xyxy.cpu().numpy()   

    masks = result.masks.masks.cpu().numpy()     
    masks = np.moveaxis(masks, 0, -1) 
    masks = scale_image(masks, result.masks.orig_shape)
    masks = np.moveaxis(masks, -1, 0) 

    return boxes, masks, cls, probs

def overlay(image, mask, color, alpha, resize=None):

    color = color[::-1]
    colored_mask = np.expand_dims(mask, 0).repeat(3, axis=0)
    colored_mask = np.moveaxis(colored_mask, 0, -1)
    masked = np.ma.MaskedArray(image, mask=colored_mask, fill_value=color)
    image_overlay = masked.filled()

    if resize is not None:
        image = cv2.resize(image.transpose(1, 2, 0), resize)
        image_overlay = cv2.resize(image_overlay.transpose(1, 2, 0), resize)

    image_combined = cv2.addWeighted(image, 1 - alpha, image_overlay, alpha, 0)

    return image_combined

model = YOLO("best.engine")
img = cv2.imread("myimage.jpg")
boxes, masks, cls, probs = predict_on_image(model, img, conf=0.55)

image_with_masks = np.copy(img)
for mask_i in masks:
    image_with_masks = overlay(image_with_masks, mask_i, color=(255,255,255), alpha=0.3)

plt.imshow(image_with_masks)

mask = img - image_with_masks

plt.imshow(mask)`

**Comment by adrianosantospb** [comment]
Even if I use the following code:

` result = model.predict(frame)[0]
  boxes = result.boxes.xyxy.cpu().numpy()
  masks = result.masks.data.cpu().numpy()    # masks, (N, H, W)  # noqa: E501
  masks = resize(masks, result.masks.orig_shape)`

**Comment by glenn-jocher** [comment]
@adrianosantospb thank you for reaching out. 

The error message you're seeing indicates that you're trying to use a TensorRT model in an unsupported mode. TensorRT models can only be used for prediction and validation, but not for training or exporting. 

The `predict` method you're using is the correct way to make predictions using a TensorRT model in YOLOv8. If you want to use your `predict_on_image` function instead, you'll need to make sure you're using a PyTorch model instead of a TensorRT model.

I hope that helps! Let us know if you have any more questions or issues.

**Comment by rusvagzur** [comment]
@adrianosantospb how did you fix this?

**Comment by glenn-jocher** [comment]
@rusvagzur it appears that the original poster has resolved the issue based on following the guidance for using TensorRT models correctly with YOLOv8 for 'predict' and 'val' modes only.

If you are facing a similar issue, ensure that you're using the `.predict()` method with a PyTorch `.pt` model for any operations outside of 'predict' and 'val', such as training or model exporting, and use the TensorRT `.engine` model exclusively for prediction or validation tasks.

For further information or if you need more detailed assistance, please consult the Ultralytics documentation or inquire within the GitHub repository discussions.

If there is an unresolved problem, don't hesitate to reach out with specific details, and the community will be glad to assist you!
