### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by Thecoder1012** [ultralytics/ultralytics#2848]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

The code was working pretty fine and suddenly I am facing the error RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED.

Checked with torch.cuda.is_available()
showing me True

Reinstalled all packages, (ultralytics, torch)

Same issue keeps coming! What to do?

Ultralytics == 8.0.75
torch == 2.0.1+cu117
cuda == 11.7

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Thecoder1012 hi there! Sorry to hear you're experiencing the CUDNN_STATUS_NOT_INITIALIZED error. This error commonly appears when there's an issue initializing cuDNN, such as a version mismatch or incorrect installation. 

If you've reinstalled all packages and are still having the issue, it might be helpful to double-check your cuDNN installation. You can also try clearing the CUDA cache by running `torch.cuda.empty_cache()` before running your code.

If the issue persists, please let us know, and we'll do our best to assist you further. Thanks for using YOLOv8!
