### ISSUE TITLE
Inquiry about distilling YOLOv8m model into YOLOv8n for edge detection tasks

### ISSUE THREAD

**Issue by JuanIsernGhosn** [ultralytics/ultralytics#2858]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Dear Community,

I trust you are all doing well. I have been engaging with this project and finding it immensely helpful and fascinating. The collective effort and commitment that have gone into this project are truly inspiring.

I am currently looking to enhance efficiency for edge detection tasks, specifically for resource-constrained devices such as the Jetson Nano. My approach is to apply model distillation techniques to create lighter, more resource-efficient Convolutional Neural Networks (CNN) models.

In this context, my plan is to use the YOLOv8m model as the teacher and distill its knowledge into a YOLOv8n model as the student. I believe this approach could provide a robust yet efficient model suitable for the edge computing scenario I'm dealing with.

My question to the community is: Is it feasible within the framework of this project to apply model distillation techniques to the YOLOv8m and YOLOv8n models? If so, could anyone provide guidance, pointers, or suggest any specific portion of the code that could be relevant for this endeavor?

I sincerely appreciate any assistance you may provide. I am excited about the prospect of learning more and potentially contributing to this remarkable project.

Best Regards,
Juan Isern

**Comment by glenn-jocher** [comment]
@JuanIsernGhosn hello Juan,

Thank you for your kind words and interest in YOLOv8! We are glad to hear that you find our project helpful and inspiring.

Regarding your question about distilling the YOLOv8m model into YOLOv8n for edge detection tasks, it should be feasible to apply model distillation techniques to the YOLOv8m and YOLOv8n models. We recommend reviewing the YOLOv8 [Custom Training](https://docs.ultralytics.com/custom) section in our documentation for guidance on how to perform custom training on the YOLOv8 architecture.

To implement model distillation, we suggest investigating the [Knowledge Distillation](https://arxiv.org/abs/1503.02531) technique. This technique involves training a smaller model to mimic the behavior of a larger model, using the larger model as a teacher to guide the training process of the smaller model.

When considering YOLOv8m and YOLOv8n models specifically, you may want to experiment with reducing the number of convolutional filters or removing certain layers from the YOLOv8m model to create a smaller model that can learn from the YOLOv8m teacher. There is no specific portion of the code that is more relevant for this endeavor as it depends on the specific distillation techniques being applied.

We hope that helps, and we wish you the best of luck with your project! Please feel free to ask any further questions you may have.

**Comment by OmarCHABCHOUB** [comment]
Hey, I have read this issue and it involves me.
Well, I did not understand the way it should be done. After train and export all I get is an onnx file that represents the teacher, isn't there a mode that deals with distillations so it reduces the number of layers?
Thanks

**Comment by OmarD-ctrl** [comment]
@glenn-jocher Thank you!

**Comment by minhhotboy9x** [comment]
I'm trying KD v8m into v8s. However, my results are much worse than the original model (around 44.4 of KD v8s compared to 44.9 original on Coco). I took the feature map output from 3 blocks P3, P4, and P5 of students [(yolov8 architecture)](https://github.com/ultralytics/ultralytics/issues/189) and calculated L2 loss with those of the teacher respectively. The problem may be either the loss function or the gap between the architecture of 2 models. Has anyone tried to KD this model successfully? If has, can you provide some tutorial codes or guidances, please?
Thank you so much!

**Comment by glenn-jocher** [comment]
@minhhotboy9x hello! 

It seems like you're on the right track with your approach of Knowledge Distillation (KD) from YOLOv8m (teacher model) to YOLOv8s (student model). Using the L2 loss for similarity between feature maps of the teacher and student models is a common practice.

The performance drop might be due to the reduced capacity of YOLOv8s compared to YOLOv8m, as you suggested. It's important to remember that the student model may not always reach the performance of the teacher due to its smaller size and less representational capacity.

Another potential pitfall could be related to how you are balancing the distillation loss with the original detection loss. It's crucial to strike a balance between them, as the model must also learn to predict accurate bounding boxes and object classes, not just mimic the teacher's feature maps.

Unfortunately, as YOLOv8 does not currently support a built-in mode for model distillation, we do not have specific code examples or tutorials available.

I recommend trying different types of loss functions or experiment with other distillation techniques, such as attention maps or hint learning. Tuning the balance between KD loss and fundamental detection loss might also help to improve the results.

Good luck with your model distillation, and we are eager to hear about any successful methods you discover!

**Comment by reza-shahriari** [comment]
can any one help me with distilling knowledge?

**Comment by glenn-jocher** [comment]
@reza-shahriari hello,

Knowledge distillation is a technique that involves training a smaller, student model to mimic a larger, teacher model. It's often used to reduce the computational complexity of larger models while retaining the bulk of their performance.

To perform knowledge distillation on YOLOv8, you would begin by training your larger YOLOv8 model with your dataset. This becomes your teacher model.

Next, you create a smaller student version of the YOLOv8 model. This can be done by reducing the number of layers, reducing the number of convolutional filters, or other simplifications.

You then train your student model using the same dataset, but in addition to the regular loss function, you add a term that represents the difference between the teacher model predictions and the student model predictions. This guides the student model to match the teacher model's performance as closely as possible.

One standard approach for calculating this additional term is using the L2 loss (also known as the Euclidean distance) between the teacher and the student model predictions.

Remember to maintain a balance between the distillation loss and the regular loss. Too much emphasis on the distillation loss can result in a student model that simply replicates the output of the teacher model, without learning the underlying patterns in the data. 

I hope this gives you a general understanding of how to perform knowledge distillation in YOLOv8. The specifics can vary based on your requirements and the nature of your data. Best of luck!

**Comment by melika-sce** [comment]
@minhhotboy9x Hi, I'm trying to use knowledge distillation for YOLOv8m to YOLOv8s, can you provide more information about the files you have modified and a sample code for distillation section?
Thanks

**Comment by glenn-jocher** [comment]
@melika-sce Hi there,

For knowledge distillation from YOLOv8m to YOLOv8s, you would typically need to modify the training script to include the distillation loss. This involves calculating the loss between the feature maps of the student and teacher models during training.

Unfortunately, we don't provide sample code for distillation as it's not a built-in feature of YOLOv8. You'll need to implement custom modifications to the training loop to integrate the distillation process.

For guidance on the architecture and training process, please refer to the Ultralytics Docs. Good luck with your distillation efforts! 🍀

**Comment by minhhotboy9x** [comment]
> @minhhotboy9x Hi, I'm trying to use knowledge distillation for YOLOv8m to YOLOv8s, can you provide more information about the files you have modified and a sample code for distillation section? Thanks

Hi @melika-sce, sorry for the very late reply. I'm using the old version of this repo so maybe my answer is incorrect for this version. 
In `ultralytics/nn/modules/task.py`, you can find the function `def _predict_once(self, x, profile=False, visualize=False, embed=None):`
```
def _predict_once(self, x, profile=False, visualize=False, embed=None):
        """
        Perform a forward pass through the network.

        Args:
            x (torch.Tensor): The input tensor to the model.
            profile (bool):  Print the computation time of each layer if True, defaults to False.
            visualize (bool): Save the feature maps of the model if True, defaults to False.
            embed (list, optional): A list of feature vectors/embeddings to return.

        Returns:
            (torch.Tensor): The last output of the model.
        """
        y, dt, embeddings = [], [], []  # outputs
        for m in self.model:
            if m.f != -1:  # if not from previous layer
                x = y[m.f] if isinstance(m.f, int) else [x if j == -1 else y[j] for j in m.f]  # from earlier layers
            if profile:
                self._profile_one_layer(m, x, dt)
            x = m(x)  # run
            y.append(x if m.i in self.save else None)  # save output
            if visualize:
                feature_visualization(x, m.type, m.i, save_dir=visualize)
            if embed and m.i in embed:
                embeddings.append(nn.functional.adaptive_avg_pool2d(x, (1, 1)).squeeze(-1).squeeze(-1))  # flatten
                if m.i == max(embed):
                    return torch.unbind(torch.cat(embeddings, 1), dim=0)
        return x
```
You can see that variable `m` in the `for` loop is a sub-module containing id `m.i` (you can look for the id of sub-modules here: [YOLOv8 structure](https://github.com/ultralytics/ultralytics/issues/189)). When you want to get the output feature maps from desired sub-module, you need to modify this code a little bit as I did in the old version.
```
def _forward_once(self, x, profile=False, visualize=False, mask_id = []):
        """
        Perform a forward pass through the network.

        Args:
            x (torch.Tensor): The input tensor to the model
            profile (bool):  Print the computation time of each layer if True, defaults to False.
            visualize (bool): Save the feature maps of the model if True, defaults to False

        Returns:
            (torch.Tensor): The last output of the model.
        """
        # print(mask_id)
        y, dt = [], []  # outputs
        feature_mask = [] # outputs of mask i_th
        for m in self.model:
            if m.f != -1:  # if not from previous layer
                x = y[m.f] if isinstance(m.f, int) else [x if j == -1 else y[j] for j in m.f]  # from earlier layers
            if profile:
                self._profile_one_layer(m, x, dt)
            x = m(x)  # run
            y.append(x if m.i in self.save else None)  # save output
            if visualize:
                LOGGER.info('visualize feature not yet supported')
                # TODO: feature_visualization(x, m.type, m.i, save_dir=visualize)
            if m.i in mask_id:
                feature_mask.append(x)
        if feature_mask:
            return x, feature_mask
        # print(f'------------{type(x)}------------{len(x)}----------------')
        return x
```

I inserted mask_id list, which contains the id of sub-modules to get their feature. You also have to modify the other method referring to this function and training code to calculate the loss distillation. You can find the training code in this version repo in `ultralytics/engine/trainer.py/_do_train`
```
def _do_train_v2(self: BaseTrainer, world_size=1):
    """Train completed, evaluate and plot if specified by arguments."""
    if world_size > 1:
        self._setup_ddp(world_size)

    self._setup_train(world_size)
    self.epoch_time = None
    self.epoch_time_start = time.time()
    self.train_time_start = time.time()
    nb = len(self.train_loader)  # number of batches
    nw = max(round(self.args.warmup_epochs * nb), 100)  # number of warmup iterations
    last_opt_step = -1
    # self.run_callbacks('on_train_start')
    LOGGER.info(f'Image sizes {self.args.imgsz} train, {self.args.imgsz} val\n'
                f'Using {self.train_loader.num_workers * (world_size or 1)} dataloader workers\n'
                f"Logging results to {colorstr('bold', self.save_dir)}\n"
                f'Starting training for {self.epochs} epochs...')
    if self.args.close_mosaic:
        base_idx = (self.epochs - self.args.close_mosaic) * nb
        self.plot_idx.extend([base_idx, base_idx + 1, base_idx + 2])


    # create imitation mask for knowledge distillation
    mask_id = self.args.kd_layer
    if hasattr(self, 'teacher'):
        self.type_kd_loss = self.args.type_kd_loss # -----------------get type kd loss-----------------
        self.teacher.train() 
        dump_image = torch.zeros((1, 3, self.args.imgsz, self.args.imgsz), device=self.device)

        _, features = self.model(dump_image, mask_id = mask_id)  # forward
        _, teacher_feature= self.teacher(dump_image, mask_id = mask_id) 
        
        stu_feature_adapts = [] # contain imitation

        for i in range(len(features)):
            _, student_channel, student_out_size, _ = features[i].shape
            _, teacher_channel, teacher_out_size, _ = teacher_feature[i].shape
            stu_feature_adapts.append(nn.Sequential(nn.Conv2d(student_channel, teacher_channel, 1,
                                                    padding=0, stride=1, bias=False),
                                                    nn.ReLU()).to(self.device))
        if self.args.train_adapter:
            self.add_params_kd(stu_feature_adapts)

    for epoch in range(self.start_epoch, self.epochs):
        self.epoch = epoch
        self.run_callbacks('on_train_epoch_start')
        self.model.train()

        if RANK != -1:
            self.train_loader.sampler.set_epoch(epoch)
        pbar = enumerate(self.train_loader)
        # Update dataloader attributes (optional)
        if epoch == (self.epochs - self.args.close_mosaic):
            LOGGER.info('Closing dataloader mosaic')
            if hasattr(self.train_loader.dataset, 'mosaic'):
                self.train_loader.dataset.mosaic = False
            if hasattr(self.train_loader.dataset, 'close_mosaic'):
                self.train_loader.dataset.close_mosaic(hyp=self.args)
        if RANK in (-1, 0):
            LOGGER.info(self.progress_string())
            pbar = tqdm(enumerate(self.train_loader), total=nb, bar_format=TQDM_BAR_FORMAT)
        self.tloss = None
        self.t_kdloss = 0 # mean of kd loss

        #----------------mean feat-----------------
        self.stu_mean = []
        self.tea_mean = []
        for id in mask_id:
            self.stu_mean.append({id: 0})
            self.tea_mean.append({id: 0})
        #------------------------------------------------

        self.optimizer.zero_grad()
        for i, batch in pbar:
            self.run_callbacks('on_train_batch_start')
            # Warmup
            ni = i + nb * epoch
            if ni <= nw:
                xi = [0, nw]  # x interp
                self.accumulate = max(1, np.interp(ni, xi, [1, self.args.nbs / self.batch_size]).round())
                for j, x in enumerate(self.optimizer.param_groups):
                    # Bias lr falls from 0.1 to lr0, all other lrs rise from 0.0 to lr0
                    x['lr'] = np.interp(
                        ni, xi, [self.args.warmup_bias_lr if j == 0 else 0.0, x['initial_lr'] * self.lf(epoch)])
                    if 'momentum' in x:
                        x['momentum'] = np.interp(ni, xi, [self.args.warmup_momentum, self.args.momentum])

            # Forward
            with torch.cuda.amp.autocast(self.amp):
                batch = self.preprocess_batch(batch)
                self.kd_loss = 0.0 # make a kd_loss

                if hasattr(self, 'teacher'):
                    preds, features =  self.model(batch['img'], mask_id = mask_id)
                    teacher_preds, teacher_features =  self.teacher(batch['img'], mask_id = mask_id)
                else:
                    preds = self.model(batch['img']) # predict

                self.loss, self.loss_items = self.criterion(preds, batch) # cal loss

                if hasattr(self, 'teacher'):
                    stu_feature_maps = []
                    for i in range(len(features)):
                        # print(f'-------------{stu_feature_adapts[i]}')
                        stu_feature_maps.append(stu_feature_adapts[i](features[i]))

                    self.kd_loss = cal_kd_loss(stu_feature_maps, 
                                            [f.detach() for f in teacher_features], batch, self.type_kd_loss)
                    
                    #--------------------------------------------------------
                    with torch.no_grad():
                        for j in range(len(mask_id)):
                            self.stu_mean[j][mask_id[j]] = (self.stu_mean[j][mask_id[j]] * i + torch.mean(stu_feature_maps[j])) / (i+1)
                            self.tea_mean[j][mask_id[j]] = (self.tea_mean[j][mask_id[j]] * i + torch.mean(teacher_features[j])) / (i+1)
                    
                    #-----------------------------------------------------------
                
                if RANK != -1:
                    self.loss *= world_size
                    if hasattr(self, 'teacher'):
                        self.kd_loss *= world_size

                #-------------------------------------------------------
                self.t_kdloss = (self.t_kdloss * i + self.kd_loss) / (i + 1)
                
                self.tloss = (self.tloss * i + self.loss_items) / (i + 1) if self.tloss is not None \
                    else self.loss_items

            # Backward
            self.alpha_kd = 0.05 # default 0.05
            self.scaler.scale(self.loss + self.alpha_kd * self.kd_loss).backward()

            # Optimize - https://pytorch.org/docs/master/notes/amp_examples.html
            if ni - last_opt_step >= self.accumulate:
                self.optimizer_step()
                last_opt_step = ni

            # Log
            mem = f'{torch.cuda.memory_reserved() / 1E9 if torch.cuda.is_available() else 0:.3g}G'  # (GB)
            loss_len = self.tloss.shape[0] if len(self.tloss.size()) else 1
            losses = self.tloss if loss_len > 1 else torch.unsqueeze(self.tloss, 0)
            if RANK in (-1, 0):
                # + '\n' + '%15.5g' * (1 + len(mask_id)*2)
                # , self.kd_loss
                pbar.set_description(
                    ('%11s' * 2 + '%11.4g' * (2 + loss_len) + '%11.4g') % 
                    (f'{epoch + 1}/{self.epochs}', mem, *losses, batch['cls'].shape[0], batch['img'].shape[-1], self.t_kdloss))
                self.run_callbacks('on_batch_end')
                if self.args.plots and ni in self.plot_idx:
                    self.plot_training_samples(batch, ni)

            self.run_callbacks('on_train_batch_end')

        self.lr = {f'lr/pg{ir}': x['lr'] for ir, x in enumerate(self.optimizer.param_groups)}  # for loggers

        self.scheduler.step()
        self.run_callbacks('on_train_epoch_end')

        if RANK in (-1, 0):

            # Validation
            self.ema.update_attr(self.model, include=['yaml', 'nc', 'args', 'names', 'stride', 'class_weights'])
            final_epoch = (epoch + 1 == self.epochs) or self.stopper.possible_stop

            if self.args.val or final_epoch:
                self.metrics, self.fitness = self.validate()
            self.save_metrics(metrics={**self.label_loss_items(self.tloss), **self.metrics, **self.lr})
            self.stop = self.stopper(epoch + 1, self.fitness)

            # Save model
            if self.args.save or (epoch + 1 == self.epochs):
                self.save_model()
                self.run_callbacks('on_model_save')

        tnow = time.time()
        self.epoch_time = tnow - self.epoch_time_start
        self.epoch_time_start = tnow
        self.run_callbacks('on_fit_epoch_end')
        torch.cuda.empty_cache()  # clears GPU vRAM at end of epoch, can help with out of memory errors

        # Early Stopping
        if RANK != -1:  # if DDP training
            broadcast_list = [self.stop if RANK == 0 else None]
            dist.broadcast_object_list(broadcast_list, 0)  # broadcast 'stop' to all ranks
            if RANK != 0:
                self.stop = broadcast_list[0]
        if self.stop:
            break  # must break all DDP ranks

    if RANK in (-1, 0):
        # Do final val with best.pt
        LOGGER.info(f'\n{epoch - self.start_epoch + 1} epochs completed in '
                    f'{(time.time() - self.train_time_start) / 3600:.3f} hours.')
        self.final_eval()
        if self.args.plots:
            self.plot_metrics()
        self.run_callbacks('on_train_end')
    torch.cuda.empty_cache()
    self.run_callbacks('teardown')
```
I've tried to test the distillation on coco with different loss but I get the worse results. I hope you can find a better way to do this.

**Comment by melika-sce** [comment]
Thank you so much @minhhotboy9x  for the complete explanation and the provided codes. I will give it a try in the newer version.
hope you the best in your projects

**Comment by Hemilibeatriz** [comment]
Hi @melika-sce 
Did you manage to develop that code for distilling?

**Comment by Priyanshu88** [comment]
Hi @melika-sce and @Hemilibeatriz, are you able to run the distillation with your code?

**Comment by Hemilibeatriz** [comment]
> Hi @melika-sce and @Hemilibeatriz, are you able to run the distillation with your code?

Hi @Priyanshu88, send me you e-mail... i share a Colab link with you :)

**Comment by Priyanshu88** [comment]
My email is 2040020@sliet.ac.in. Thank you very much!

**Comment by blue-q** [comment]
Hey @Hemilibeatriz, can you share it with me, my email is [1518751881@qq.com]. Thank you very much!

**Comment by Hemilibeatriz** [comment]
Hi @Priyanshu88, @blue-q, my code is about a classification model, so you should make some changes to apply it to other tasks. I've created a repo (it's easier 😊)

**Comment by El-amin** [comment]
> Hi [@Priyanshu88](https://github.com/Priyanshu88), [@blue-q](https://github.com/blue-q), my code is about a classification model, so you should make some changes to apply it to other tasks. I've created a repo (it's easier 😊)
> 
> Link: https://github.com/Hemilibeatriz/Destillation_ClassifyModel

How can I adopt this code for object detection using the same models? I tried adopting it, but I'm not going anywhere

**Comment by El-amin** [comment]
How can I adopt this code for object detection using the same models? I tried adopting it, but I'm not going anywhere @Hemilibeatriz
