### ISSUE TITLE
How to extract class(label) from webcam recognition results?

### ISSUE THREAD

**Issue by jhp21c-dev** [ultralytics/ultralytics#2868]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I successfully trained it using yolov5 thanks to ultralytics hub. I connected a webcam with the best.pt file and verified its operation. Now I want to send the class(label) variable to the Arduino to control the stepper motor. I would be grateful if you could tell me how to pull only the class(label) variable from the results. When I run the code, I get 
...
0: 384x512 1 General trash, 1 Paper pack, 619.3ms
Speed: 3.3ms preprocess, 619.3ms inference, 1.1ms postprocess per image at shape (1, 3, 512, 512)

0: 384x512 1 Clothing, 619.8ms
Speed: 1.0ms preprocess, 619.8ms inference, 1.0ms postprocess per image at shape (1, 3, 512, 512, 512)
...

Repeat this over and over to get the output to the console. 
The code looks like this
    `    
    
    import cv2
    import serial
    from ultralytics import YOLO

    # arduino connection
    arduino = serial.Serial('COM4', 9600)

    # load my YOLO v5 model
    model = YOLO("yolo/best.pt")
    model.conf = 0.5

    # using webcam
    cap = cv2.VideoCapture(0)

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # object detection
        results = model(frame)

        # Representing results in a frame
        annotated_frame = results[0].plot()

        # Visualizing annotated_frame
        cv2.imshow("YOLOv5 Inference", annotated_frame)

        # # Control stepmotors based on results
        # for *box, conf, cls in results[0]:
        #     if cls == 0:  # plastic
        #         arduino.write(b'H')
        #     elif cls == 1:  # paper
        #         arduino.write(b'2')
 
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()
    arduino.close()`

If I print the output with print(results), it looks like this
`
   
     ...
    0: 384x512 1 Clothing, 1 Metal, 657.9ms
    Speed: 3.0ms preprocess, 657.9ms inference, 1.6ms postprocess per image at shape (1, 3, 512, 512)
    [ultralytics.yolo.engine.results.Results object with attributes:

    boxes: ultralytics.yolo.engine.results.Boxes object      
    keypoints: None
    keys: ['boxes']
    masks: None
    names: {0: 'Battery', 1: 'Clothing', 2: 'General trash', 3: 'Glass', 4: 'Metal', 5: 'Paper pack', 6: 'Paper', 7: 'Plastic bag', 8: 'Plastic', 9: 
    'Styrofoam', 10: 'UNKNOWN'}
    orig_img: array([[[  1,  16,  12],
        [  6,  19,  16],
        [  9,  21,  18],
        ...,
        [254, 255, 254],
        [254, 255, 254],
        [254, 255, 254]],

       [[  7,  20,  14],
        [  8,  21,  15],
        [  9,  22,  16],
        ...,
        [252, 255, 252],
        [252, 255, 252],
        [252, 255, 252]],

       [[ 12,  18,  13],
        [ 13,  21,  16],
        [ 14,  24,  18],
        ...,
        [252, 255, 252],
        [252, 255, 252],
        [252, 255, 252]],

       ...,

       [[  8,  18,  15],
        [ 10,  16,  12],
        [  8,  12,   7],
        ...,
        [145, 148, 141],
        [148, 149, 144],
        [149, 150, 145]],

       [[  7,  17,  12],
        [  8,  16,  10],
        [  7,  13,   8],
        ...,
        [145, 149, 145],
        [151, 151, 151],
        [150, 150, 150]],

       [[  8,  14,  11],
        [ 10,  14,  11],
        [  9,  12,  10],
        ...,
        [148, 150, 146],
        [155, 155, 155],
        [150, 150, 150]]], dtype=uint8)
    orig_shape: (480, 640)
    path: 'image0.jpg'
    probs: None
    speed: {'preprocess': 3.0040740966796875, 'inference': 657.8564643859863, 'postprocess': 1.6436576843261719}]
    ...
`

**Comment by glenn-jocher** [comment]
@jhp21c-dev hello! To pull only the class(label) variable from the results, you can use indexing to loop over each detection and extract the class label. Here's a code snippet to get you started:

```
    for *box, conf, cls in results.xyxy[0]:
        class_label = model.names[int(cls)]
        print('Detected:', class_label)
        # Use class_label to control the stepper motor
```

Here, `results.xyxy` contains a tensor of all bounding box detections, with the first element corresponding to the first image in the batch (in this case, you are using one image at a time). The for loop goes over each detection, unpacking the variables `*box` (the coordinates of the box), `conf` (the confidence score), and `cls` (the predicted class index). `model.names` is a dictionary mapping class indices to their corresponding labels, so we index into it with `int(cls)` to get the label of the detected object.

I hope that helps! Let me know if you have any questions or run into any issues.

**Comment by jhp21c-dev** [comment]
When I added the above code and ran it, the webcam worked, but it only showed one image and threw an error. The error is AttributeError: 'list' object has no attribute 'xyxy'...

**Comment by jhp21c-dev** [comment]
@glenn-jocher Oh My God. It works. Love it!!

**Comment by glenn-jocher** [comment]
@jhp21c-dev, glad to hear that your issue has been resolved and that you are enjoying working with YOLOv8! If you have any further questions or run into any issues, feel free to open a new issue and we'll be happy to help. Have a great day!

**Comment by ahmedmuzammilAI** [comment]
> @jhp21c-dev "When I added the above code and ran it, the webcam worked, but it only showed one image and threw an error. The error is AttributeError: 'list' object has no attribute 'xyxy'...

hey, I get the same error can you please tell me how you had solved it

**Comment by jhp21c-dev** [comment]
@ahmedmuzammilAI 
I utilized the following code

for box in results[0].boxes:
# cls = box.cls # class
conf = box.conf # confidence score
if cls = 1: 
~~.
I hope this helps.

**Comment by glenn-jocher** [comment]
Hi @ahmedmuzammilAI,

To extract the class variable from detection results in YOLOv8, you can loop over the `results` list and access each detection's class index through the `cls` attribute. 

Here's an example of how you might do this:

```
for detection in results[0]: # Loop over each detection in the first image of the batch

    class_index = detection.cls # Get the class index of the detection

    # Do something with the class index, like print it or compare it to another value...
```

In this example, `results` is a list of all detections for the batch, with the first element corresponding to the first image. We access the `cls` attribute of each `Detection` object in the loop to extract the class index. You can then use this variable to control your stepper motor, check if the detection matches a certain class label, or perform further operations as needed.

I hope this helps! Let me know if you have any questions.

**Comment by glenn-jocher** [comment]
@marcospgp to extract the class labels from the webcam recognition results, you can access the `boxes` attribute of the `Results` object, which contains the detected bounding boxes along with their respective class IDs. You can then use the `names` dictionary to map the class IDs to their corresponding class names (labels).

Here's how you can modify your code to extract the class labels and send them to the Arduino:

```python
import cv2
import serial
from ultralytics import YOLO

# arduino connection
arduino = serial.Serial('COM4', 9600)

# load my YOLO model
model = YOLO("yolo/best.pt")
model.conf = 0.5

# using webcam
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # object detection
    results = model(frame)

    # Extract class labels
    for box in results[0].boxes:
        class_id = int(box.cls)  # Get class ID
        class_label = results[0].names[class_id]  # Get class label from class ID
        print(f'Detected class: {class_label}')  # Print class label

        # Control stepmotors based on class label
        if class_label == 'plastic':
            arduino.write(b'H')
        elif class_label == 'paper':
            arduino.write(b'2')

    # Representing results in a frame
    annotated_frame = results[0].plot()

    # Visualizing annotated_frame
    cv2.imshow("YOLO Inference", annotated_frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
arduino.close()
```

In this code snippet, we iterate over each detected `box` in the `results[0].boxes` list, retrieve the class ID using `box.cls`, and then use the `results[0].names` dictionary to get the corresponding class label. We then print the class label and send a command to the Arduino based on the detected class.

Make sure to replace `'plastic'` and `'paper'` with the actual class labels you have in your dataset. Also, ensure that the commands you send to the Arduino (`b'H'`, `b'2'`, etc.) match the expected input on the Arduino side for controlling the stepper motor.

**Comment by toula018** [comment]
hi @glenn-jocher 
i have a project working with yolov8 and i found difficulties ( i want extract center coord of bbox of class label 'weed' )  so if u can help me i will be grateful for u .
this is my attempt : 


import os
from PIL import Image, ImageDraw
from ultralytics import YOLO

# Load your custom trained YOLO model
model = YOLO("best.pt")

# Path to the folder containing images
folder_path = r"C:\Users\derra\OneDrive\Desktop\dataset0\test\weed"

# Create a directory to save processed images
output_folder = os.path.join(folder_path, "processed")
os.makedirs(output_folder, exist_ok=True)

# Iterate over the files in the folder
for filename in os.listdir(folder_path):
    if filename.endswith((".jpg", ".png", ".jpeg")):
        # Full path to the image file
        image_path = os.path.join(folder_path, filename)
        
        # Perform inference on the image
        results = model(source=image_path, conf=0.5, save=False)

        # Load the image using Pillow
        image = Image.open(image_path)

        # Get the bounding boxes from the YOLO results
        boxes = results[0].pred.xyxy.tolist()  # Access bounding boxes from results

        # Create a drawing object
        draw = ImageDraw.Draw(image)

        # Define the radius of the filled circle
        radius = 5

        # Loop over each detection in the first image of the batch
        for detection in results[0]:
            class_index = detection.cls  # Get the class index of the detection

            # Check if the class index corresponds to the class you want to visualize (e.g., "weed")
            if class_index == 1:  # Assuming "weed" class has index 1
                # Get the bounding box coordinates
                x1, y1, x2, y2 = detection.xyxy

                # Calculate the center coordinates of the bounding box
                x_center = (x1 + x2) / 2
                y_center = (y1 + y2) / 2

                # Draw a filled circle at the center coordinates
                draw.ellipse([(x_center - radius, y_center - radius), (x_center + radius, y_center + radius)], fill="red")

        # Save the image with filled circles drawn at the center coordinates
        processed_image_path = os.path.join(output_folder, filename)
        image.save(processed_image_path)

        print(f"Processed and saved: {processed_image_path}")

print("All images processed and saved.")

**Comment by toula018** [comment]
@glenn-jocher Same error here 
import os
import cv2
from ultralytics import YOLO
import serial
import time

# Load your custom trained YOLO model
model = YOLO("/media/der/AABE081FBE07E325/yolo raspberry pi/best.pt")

# Define the serial port and baud rate for communication with the Arduino
serial_port = '/dev/ttyACM0'  # Change this to match your serial port
baud_rate = 115200  # Match this to the baud rate configured in your Grbl firmware

# Open serial port
ser = serial.Serial(serial_port, baud_rate, timeout=1)
time.sleep(2)  # Wait for Grbl to initialize

# Define the video file path
video_path = "/path/to/your/video/file.mp4"

# Create a VideoCapture object
cap = cv2.VideoCapture(video_path)

# Define the codec and create VideoWriter object
fourcc = cv2.VideoWriter_fourcc(*'XVID')
output_video_path = "/path/to/save/processed_video.avi"
out = cv2.VideoWriter(output_video_path, fourcc, 20.0, (640, 480))

# Iterate over frames in the video
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break  # Break the loop if there are no more frames

    # Perform inference on the frame
    results = model(frame, conf=0.3, save=False)

    # Process the detected objects
    for result in results:
        boxes = result.boxes
        class_indices = boxes.cls

        for i, class_index in enumerate(class_indices):
            class_id = int(class_index)
            if class_id == 0:
                box_coordinates = boxes.xyxy[i]
                x_center = (box_coordinates[0] + box_coordinates[2]) / 2
                y_center = (box_coordinates[1] + box_coordinates[3]) / 2

                # Convert center coordinates to G-code format
                gcode_command = f"G1 X{x_center} Y{y_center} F200\n"  # Example G-code command

                # Send G-code command to Arduino
                ser.write(gcode_command.encode())

                # Wait for Grbl response
                response = ser.readline().decode('utf-8').strip()
                print("Response from Grbl:", response)

    # Write the frame into the processed video
    out.write(frame)

# Release everything when done
cap.release()
out.release()
cv2.destroyAllWindows()

# Close serial port
ser.close()
print("Video processing completed.")
