### ISSUE TITLE
model.predict(..., save=True) doesn't work as intended for batch prediction

### ISSUE THREAD

**Issue by afifaniks** [ultralytics/ultralytics#2875]
During batch prediction of pose estimation, if `save=True`, all of the predictions are incorrectly drawn on the first image of the batch. For example, if we have two images in a list that are passed to the model for prediction:

image1:
![img](https://github.com/ultralytics/ultralytics/assets/24480497/0b2b2f56-c1c5-49f4-a1d2-83a26e173e89)

image2:
![img_1](https://github.com/ultralytics/ultralytics/assets/24480497/e5c653cc-225c-44fb-803a-11054929a788)

The outputs are found in `runs/pose/predict` as given:

image1:
![img](https://github.com/ultralytics/ultralytics/assets/24480497/999eef76-4b0b-4842-9725-9eeeaa698b4c)

image2:
![img_1](https://github.com/ultralytics/ultralytics/assets/24480497/c7838c81-e1eb-402c-a79a-0dd53dc236e0)

**Comment by glenn-jocher** [comment]
@afifaniks, thank you for bringing this issue to our attention. This is indeed an unexpected behavior that we will need to investigate further.

In the meantime, a possible workaround could be to perform batch prediction without using the `save` parameter. Instead, the predicted outputs can be manually saved using Python code after the batch prediction has completed.

We apologize for any inconvenience this may have caused and we appreciate your patience as we work to resolve this issue. Please let us know if you have any further questions or concerns.
