### ISSUE TITLE
How to calculate bounding box

### ISSUE THREAD

**Issue by AjibolaPy** [ultralytics/ultralytics#2883]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Please if I want to do visualization with the yolov8 dataset. how do i make it useable with cv2 since yolo bbx is normalized( between 0-1). Is the calculation the same as yolov5 i.e xmin=(width*image_height)/2-x_center, ymin=(width*image_height)/2-y_center, xmax=(width*image_height)/2+x_center, ymax=(width*image_height)/2-y_center. I tried the above formulae but the bbx was not on the expected target

**Comment by glenn-jocher** [comment]
@AjibolaPy hello! Thank you for your question. To calculate the bounding box coordinates for YOLOv8, the same formula to convert normalized coordinates to pixel coordinates can be used - xmin=(image_width * x_center) - (bb_width * 0.5), ymin=(image_height * y_center) - (bb_height * 0.5), xmax=(image_width * x_center) + (bb_width * 0.5), ymax=(image_height * y_center) + (bb_height * 0.5). Here, x_center and y_center are the normalized x and y values of the bounding box center, and bb_width and bb_height are the width and height of the bounding box, also in normalized form. 

However, it seems that the above formula did not work for you. If you could provide further details such as your specific use case and any error messages that you encountered, we could better understand the issue and provide you with an accurate solution. Thanks!

**Comment by 123sameer456** [comment]
results = !yolo task=detect mode=predict model= best.pt show=True conf= 0.2 source=0 

boxes = results[0].boxes
for box in boxes:
    print(box.xyxy)
    
i want to print the Bbox values, i tried with this code, but it shows nothing just show me the camera and nothing.
basically i want to cut the detected part and when i press 's' it will save the detected part in the folder.

i did with cv and haarcascade_russian_plate_number.xml
here is the code that cuts the detected part and save in the folder when i click 's'
import cv2

harcascade = "haarcascade_russian_plate_number.xml"

cap = cv2.VideoCapture(0)

cap.set(3, 640) # width
cap.set(4, 480) #height

min_area = 500
count = 0

while True:
    success, img = cap.read()

    plate_cascade = cv2.CascadeClassifier(harcascade)
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    plates = plate_cascade.detectMultiScale(img_gray, 1.1, 4)

    for (x,y,w,h) in plates:
        area = w * h

        if area > min_area:
            cv2.rectangle(img, (x,y), (x+w, y+h), (0,255,0), 2)
            cv2.putText(img, "Number Plate", (x,y-5), cv2.FONT_HERSHEY_COMPLEX_SMALL, 1, (255, 0, 255), 2)

            img_roi = img[y: y+h, x:x+w]
            cv2.imshow("ROI", img_roi)


    
    cv2.imshow("Result", img)

    if cv2.waitKey(1) & 0xFF == ord('s'):
        cv2.imwrite("plates/scaned_img_" + str(count) + ".jpg", img_roi)
        cv2.rectangle(img, (0,200), (640,300), (0,255,0), cv2.FILLED)
        cv2.putText(img, "Plate Saved", (150, 265), cv2.FONT_HERSHEY_COMPLEX_SMALL, 2, (0, 0, 255), 2)
        cv2.imshow("Results",img)
        cv2.waitKey(500)
        count += 1

i want same thing but using yolov8n. my yolov8 model is saved as best.pt and it is a custom object detection model of person face and number plate.

please somebody help me

**Comment by glenn-jocher** [comment]
@123sameer456 hello there! You're right. YOLOv8 does return a list of box instances (objects) through which you can iterate. Each box object has attributes which represent the properties of a detected bounding box, such as the bounding box's top left and bottom right corner coordinates.

However, if you are not seeing any bounding boxes in your results, it could be due to a few reasons. One common issue often stems from the threshold value for the confidence score (the 'conf' parameter you're setting). If it is set too high, YOLOv8 might not be detecting any objects because none of the detections meet the confidence threshold. If you’re setting it at 0.2 and not encountering any results, try lowering it to a smaller value and see if you start detecting any objects.

Regarding saving the detected part of the image when 's' is pressed, this would require a variation of the codes you've shown. Instead of using haarcascades, you'll replace it with inference from the YOLO model, get the bounding boxes, and perform the same procedure of cropping the image according to the bounding box coordinates and saving the cropped section.

I hope this explanation is helpful!

**Comment by aleem75321** [comment]
HI is it possible to get the detected object width and height

**Comment by glenn-jocher** [comment]
@aleem75321 hello, yes it is possible to get the width and height of the detected object. The inference outputs from YOLOv8 include the bounding box coordinates for each detected object in an image. These bounding box coordinates are usually in the format of (xmin, ymin, xmax, ymax). With these coordinates, you can easily calculate the width and height of the detected object.

For instance:

- Width of the detected object = xmax - xmin
- Height of the detected object = ymax - ymin

You can access these bounding box coordinates and make these calculations to get the width and the height of a detected object. Hope this helps!

**Comment by tylerWorley3** [comment]
> @aleem75321 hello, yes it is possible to get the width and height of the detected object. The inference outputs from YOLOv8 include the bounding box coordinates for each detected object in an image. These bounding box coordinates are usually in the format of (xmin, ymin, xmax, ymax). With these coordinates, you can easily calculate the width and height of the detected object.
> 
> For instance:
> 
> * Width of the detected object = xmax - xmin
> * Height of the detected object = ymax - ymin
> 
> You can access these bounding box coordinates and make these calculations to get the width and the height of a detected object. Hope this helps!

What would be the measurement of the width and height?

**Comment by glenn-jocher** [comment]
@tylerWorley3 The width and height values obtained from the bounding box coordinates are in pixels, relative to the size of the image being processed. 📏✨
