### ISSUE TITLE
Low performance when assigning prediction results in loop for OpenCV

### ISSUE THREAD

**Issue by aric-volman** [ultralytics/ultralytics#2886]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When using/assigning predicted results in a loop for OpenCV usage, such as the example code below, the performance of the program (not YOLOv8n itself) is reduced significantly. The input image is a 224 by 224 RGB image.

Code (either reproduces the issue):
`results = model.predict(image, imgsz=224, conf=0.2, iou=0.1, stream=True, verbose=True, half=True)`
`for result in results:`
`	image = result.plot()`

Or

`results = model.predict(image, imgsz=224, conf=0.2, iou=0.1, stream=True, verbose=True, half=True)`
`image = results[0].plot()`

In my case, the performance of the program per each loop went from 20 ms (from just the YOLOv8n prediction on Intel Tiger Lake) to 80 ms (after assigning the result).

I suspect that the memory usage and overhead of returning the original image in the results might be the culprit (~3 MB for each image?) but I am not exactly sure why.

To test this assumption, I increased the image input size of the predict function, showing a ~50 ms addition to latency:

<table>
<tr>
 <td> Image Size (px)
 <td> Latency of OpenCV Program
<tr>
 <td>128 px
 <td> 60 ms total, 13 ms inference
<tr> 
 <td>224 px
 <td> 80 ms total, 20 ms inference
<tr>
 <td> 512 px
 <td> 130 ms total, 75 ms inference
</table>

### Additional

I am not sure if this counts as a bug or not, so I created the issue as a question.

**Comment by glenn-jocher** [comment]
Hi @aric-volman, thank you for bringing up this question. It does seem like the loop iteration through the prediction results may cause additional overhead, especially if the program has to assign each result to an output image. One recommendation would be to try loading the input image into the model using the batch size argument, to process multiple images simultaneously. This could potentially improve the throughput of the predictions and optimize the performance of your program.

In regards to the performance changing with image size, larger images require more processing power and can slow down the inference. Therefore, we generally recommend reducing image size to improve inference time, unless higher resolution images are necessary for your application.

Let us know if these recommendations alleviate the performance issues you are experiencing.
