### ISSUE TITLE
INT8 for Edge

### ISSUE THREAD

**Issue by sdreamforchen** [ultralytics/ultralytics#2887]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Can I suggest you program QAT（int8） in yolov8， for flexible deployment on edge devices

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sdreamforchen thanks for the feature request! Yes we want to do this also, implement native YOLOv8 pruning and quantization similar to Neural Magic :)

@ayushexel feature request

**Comment by AyushExel** [comment]
@sdreamforchen thanks for the feature request. This has been on our long-term roadmap for ultralytics. Although there is no fixed date on this, we'll try to start working on this as soon as we have some free time. Thanks!

**Comment by yoavhalevi** [comment]
joining in for the feature request

**Comment by glenn-jocher** [comment]
@yoavhalevi thank you for your feature request! We appreciate your suggestion to implement QAT (int8) in YOLOv8 for flexible deployment on edge devices. This is indeed a valuable feature that we are considering for future updates.

Quantization-Aware Training (QAT) is a technique that allows for the training of neural networks using lower precision (such as int8) without significant loss in accuracy. By implementing QAT in YOLOv8, we can enable more efficient and lightweight deployment on edge devices, while still maintaining high performance.

While we currently do not have an exact timeline for implementing this feature, we have added it to our roadmap and will start working on it as soon as we can.

Thank you for your contribution and for helping us make YOLOv8 even better! If you have any further questions or suggestions, please do not hesitate to let us know.

**Comment by anthony-icetana** [comment]
Also registering interest 😄

**Comment by glenn-jocher** [comment]
@anthony-icetana, thank you for expressing interest in this feature! Interest from users like you helps us prioritize our development roadmap. We understand that quantization can significantly improve the performance and efficiency of YOLOv8 on edge devices, making it much more flexible for a variety of applications. 

Rest assured, our team at Ultralytics will take this into consideration in our future updates. We look forward to continuously delivering improvements to YOLOv8. 

If there are any other features or improvements you're interested in, feel free to let us know. Your feedback is always appreciated and valuable in our ongoing development work. Thanks for your contribution to our project!

**Comment by DeeperNCheaper** [comment]
@AyushExel  Hi I want to contribute this feature (Int8 QAT on NVIDIA GPU devices).
I have already implemented this feature locally for detection and segmentation models and had a good result.
If you are ok, can I contribute this feature ?
Thanks,
@glenn-jocher

**Comment by glenn-jocher** [comment]
@DeeperNCheaper That's fantastic news! We'd be thrilled to have your contribution on Int8 QAT for NVIDIA GPU devices. 🚀 Please feel free to open a pull request with your implementation, and we'll review it together. Looking forward to seeing your great work integrated into YOLOv8!

Thanks for stepping up to contribute! 😄

**Comment by glenn-jocher** [comment]
Hello, the QAT (int8) feature is currently not available in the official codebase. However, we welcome contributions and encourage you to submit a pull request with your implementation for review. Thank you!
