### ISSUE TITLE
yolov8 pose for single person

### ISSUE THREAD

**Issue by Drake1601** [ultralytics/ultralytics#2890]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

can I set config for yolov8 pose for single person with an input image have many people

**Comment by pderrenger** [comment]
@Drake1601 yes, you can configure YOLOv8 for pose estimation on a single person within an image containing multiple individuals. This is achieved through the task mode and the model's internal architecture, which automatically identifies and estimates poses for each person in the image. Simply utilize the YOLOv8 model in the pose/kepoint estimation mode, and it will focus on detecting and estimating the pose for each individual within the input image.
