### ISSUE TITLE
Color selection 

### ISSUE THREAD

**Issue by martin0496** [ultralytics/ultralytics#2892]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi community, 

I want to do the prediction with some slight changes of results projection ( mainly the colors and sizes of bounding boxes ). 
How can I do that ? how should I install ultralytics in this case , because using pip does not allow me to change the code ? 

Thank you and best regards

**Comment by glenn-jocher** [comment]
@martin0496 hi there, 

To change the colors and sizes of bounding boxes, you can modify the visualization code in the `plotting.py` file located in the `utils` folder of the YOLOv8 repo. Specifically, you can change the values for `colors` and `widths` defined in the `plot_one_box` function to your desired color and size values. 

As for installation, you can install the YOLOv8 repo via pip and make your code changes locally. You can then use your modified version of the repo code in your project. 

I hope that helps! Let us know if you have any further questions. 

Best regards, 
Glenn Jocher

**Comment by martin0496** [comment]
Thank you very much.

**Comment by glenn-jocher** [comment]
Hi @martin0496,

Thank you for reaching out to us. To freeze the weights of the YOLOv8 model during training, you can set the `freeze` option to `"freeze"` in the `yolov5.yaml` configuration file. This option specifies which layers to freeze during training. 

You can also modify the `weights` option in the configuration file to use a pre-trained checkpoint for the frozen layers. This can help speed up convergence during training. 

Let us know if you have any further questions or concerns.

Best regards,
Glenn Jocher
