### ISSUE TITLE
INT8 Conversion Integration into Ultralytics

### ISSUE THREAD

**Issue by yoloyash** [ultralytics/ultralytics#2894]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

INT8 support for yolov8 for added by openvino quite some time ago [reference](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/230-yolov8-optimization/230-yolov8-optimization.ipynb). Currently, ultralytics only supports converting the model to openvino (fp32). Would you be interested in integrating the support for conversion to INT8 directly into ultralytics? I would love to make a PR for the same. 

### Use case

CPU based edge devices benefit a lot from faster inferences. 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@yoloyash this would be great! Yes please submit a PR for INT8 OpenVINO integration. I'd be interested to see what speed improvements that brings :)
