### ISSUE TITLE
Video processing FPS - slow tracking

### ISSUE THREAD

**Issue by antonmilev** [ultralytics/ultralytics#2899]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello.

I decided to test Yolov8 video-proceeding FPS on real Full HD traffic video (1920 x 1080). My purpose is to measure the FPS when I need to obtain the frames one by one for further processing.

Results I obtained are quite lower from what I see in the docs. Also with tracking I get twice as low FPS, maybe it would be interesting for you.

For example for a 10 sec Full HD video with 25 frames/sec I got the following results 

```
Yolo8 Average FPS: 23.4   track
Yolo8 Average FPS: 49.3   predict
Yolo4 Average FPS: 43.0   predict
```

My model is based on yolov8_s.pt and my GPU is RTX 3060.

Here is my test code:

```
model = YOLO('train-crossroad2/best_m.pt')
frame = 0
average_fps = 0.0
while True:
    ret, img = vid.read()
    if not ret:
        break
        
    start = time.time()
    # output = model.track(img)
    output = model.predict(img, conf=0.25)
    end = time.time()
    
    frame = frame + 1
    fps = 1.0/(end-start)
    print("%.1f" % fps)
    
    average_fps += fps

    out.write(img)
    
print("Average FPS: %.1f" % (average_fps / frame) )

```

During the test I am getting also the following prints:

```
track
0: 384x640 26 cars, 1 minibus, 25.0ms
Speed: 2.3ms preprocess, 25.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

predict
0: 384x640 26 cars, 1 minibus, 18.0ms
Speed: 2.0ms preprocess, 18.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)
```

So my question - are these results in the expected FPS range? Why tracking is so slow?

**Comment by glenn-jocher** [comment]
@antonmilev hi there! Thank you for reporting your FPS test results for YOLOv8! 

Based on your code example, it seems that you are using the predict and track functions, which each have different processing methods for obtaining FPS. 

YOLOv8 `predict` has higher FPS because it processes each frame individually. In contrast, `track` uses object tracking, where the model detects and tracks objects through consecutive frames, resulting in lower FPS due to more calculations required per frame.

The FPS range can vary based on multiple factors, such as video quality, hardware, and model complexity, so your results could be on the expected FPS range with your current setup. 

We recommend trying to optimize your code by using batch processing and modifying the `conf` (confidence) argument to decrease the number of bounding boxes while still ensuring detection of important objects if tracking is not needed. We also suggest using the latest [YOLOv8 updates](https://github.com/ultralytics/ultralytics/releases) to utilize the latest features and improvements. 

Let us know if you need further assistance optimizing your code or have any other questions!

**Comment by antonmilev** [comment]
Thanks for confirming this.

I am comparing the old legacy darknet Yolov4 (from 2017) with Yolov8. I will post my full test code if you can repeat it with other hardware. In my test t I am measuring only the **predict** and **track** not the video processing. Yolov8 predict is at least 15% faster, probably more. I expected however better performance from the default yolov8 tracking.

**Comment by glenn-jocher** [comment]
@antonmilev you're welcome! We appreciate your interest in YOLOv8 and your thorough testing. It's great to hear that YOLOv8 predict is at least 15% faster than YOLOv4. Regarding YOLOv8 tracking, it's true that different hardware setups can result in different performance results. We recommend optimizing parameters such as the `conf` (confidence) argument and using batch processing to improve FPS when using tracking. If you encounter any issues or need further help, feel free to reach out to us and we'll be happy to assist you!

**Comment by antonmilev** [comment]
Thanks! I was able to upload my traffic test with Yolov8 on my github:

https://github.com/antonmilev/TrafficDetection/releases/tag/v1.0

It is interesting for me the test FPS s on embedded devices like NVidia Xavier and Orion. This test measures only the Yolov8 detection FPS, times to obtain the video frames are not include (but are low anyway).

For the post-processing I need at least 30-40 FPS, otherwise some frames would be dropped which is not desirable for traffic or high-speed sport videos. My test also shows that Yolov8 ByteTrack tracker is very fast, with almost no FPS drop, but the more advanced BOT-Sort is still too slow with only 24 FPS (on RTX 3060).

![performance](https://github.com/ultralytics/ultralytics/assets/46096854/dd21809f-fa7d-42e8-9a42-ba147ae955ba)

It would be great if able to improve the BOT trackers performance, bounding-box trackers like ByteTrack are not always good.

It is interesting also if someone can run this FPS test on other GPUs and embedded devices like NVidia Xavier and Orion.

**Comment by glenn-jocher** [comment]
Hi @antonmilev! Thank you for sharing your test results on YOLOv8 detection FPS with the community. It's great to see that the YOLOv8 ByteTrack tracker is very fast with almost no FPS drop. We appreciate your feedback on the BOT-Sort tracker and we'll be sure to take it into consideration as we continuously improve our software. 

It would be interesting to see how YOLOv8 performs on other GPUs and embedded devices, such as NVidia Xavier and Orin. We recommend checking the YOLOv8 [documentation](https://docs.ultralytics.com) for more information on hardware requirements and optimization techniques. 

If you have any further questions or feedback, feel free to reach out to us and we'll be happy to assist you!

**Comment by antonmilev** [comment]
Ok, thanks. I will follow the BOT-Sort trackers development, I want to further test and employ these, Yolov8 makes this really easy.

**Comment by glenn-jocher** [comment]
@antonmilev thank you for your message and your interest in YOLOv8! We're glad to hear that our software is meeting your needs and making it easy for you to test and employ the BOT-Sort trackers. Our team is continuously working to improve and advance our software, so be sure to check out our latest updates and documentation for the latest features and best practices. If you have any further questions or feedback, feel free to reach out to us and we'll be happy to assist you!

**Comment by syariffortask** [comment]
i have problem with missing frame/lost frame when trying to tracking with, that make video frame not smooth

**Comment by glenn-jocher** [comment]
@syariffortask hi there! It sounds like you're experiencing issues with frame drops during tracking, which can indeed affect the smoothness of your video output. This could be related to the processing speed or the hardware capabilities.

Here are a few suggestions to potentially mitigate this issue:
- **Optimize your model**: Lower the resolution or simplify the model if possible.
- **Adjust the confidence threshold**: Higher thresholds may reduce the number of detections and thus the processing load.
- **Hardware check**: Ensure your hardware is capable of handling the processing demands, or consider upgrading if necessary.

If the problem persists, providing more details about your setup and the specific model configuration might help diagnose the issue further. Thanks for reaching out, and we're here to help you smooth out these bumps! 🚀

**Comment by rahuulbuttaan9** [comment]
I ma facing slow speed in inferencing the model approx. 380.ms. I have custom trained model for Cups on Yolov8l.pt with Sort tracker . 
I am running this on windows 10 CPU but have tried same on Colab GPU where inference speed was highly increased approx 25ms.
Now i want to try same on AWS and want to reduce 25ms to 5-10ms. please suggest what can be done for same as hardware for Windows10

Also sort sometimes drops the object and generates new id. please suggest a good tracker .

**Comment by glenn-jocher** [comment]
Hi @rahuulbuttaan9,

Thank you for reaching out! It sounds like you're experiencing slower inference speeds on your Windows 10 CPU compared to Colab's GPU, and you're looking to further optimize performance on AWS.

### Speed Optimization Tips:
1. **Hardware Upgrade**: For significant speed improvements, consider using a more powerful GPU on AWS, such as the NVIDIA V100 or A100.
2. **Model Optimization**: Use techniques like model quantization (e.g., FP16 or INT8) to reduce model size and inference time.
3. **Batch Processing**: If applicable, process multiple frames in batches to leverage parallel processing capabilities.
4. **Export to TensorRT**: Export your model to TensorRT for optimized inference on NVIDIA GPUs. You can do this using:
    ```python
    model.export(format='engine')
    ```

### Tracker Recommendation:
If SORT is dropping objects and generating new IDs, you might want to try **ByteTrack** or **BoT-SORT** for more robust tracking. You can switch trackers by specifying the tracker configuration file:
```python
results = model.track(source='path/to/video.mp4', tracker='bytetrack.yaml')
```

### Additional Resources:
For more detailed guidance, you can refer to our [Speed Estimation Guide](https://docs.ultralytics.com/guides/speed-estimation/).

Feel free to share a minimum reproducible example if the issue persists, and ensure you're using the latest versions of the packages. This helps us diagnose and assist you more effectively.

Best of luck with your optimizations! 🚀

**Comment by smrutiranjanmohapatra** [comment]
Hi @glenn-jocher . I am using yolov8x.pt in onnx format for detection in  my cpp code with deepsort cpp tracking algorithm included with fast reid feature extraction  onnx model. I am getting 7fps in gpu . Each frame detection taking time approximatly 0.1s while tracking taking 0.02s. How to improve the fps rate from 7 to almost 20+ in gpu

**Comment by glenn-jocher** [comment]
Hi @smrutiranjanmohapatra. To improve your FPS rate, consider optimizing your ONNX model with TensorRT for faster inference on NVIDIA GPUs. Additionally, ensure your GPU drivers and CUDA toolkit are up to date. If the issue persists, try reducing the input resolution or using a smaller model variant.

**Comment by Dkyouma** [comment]
I solved this problem, its not about yolo model , its true that yolo model cant handle lots of frames in 1 sec but its about the large data came from the frames i tried another method than frame processing and because of that normal home use devices cant handle this kind of data try another approach to process you yolo model results than frame processing, good luck.

**Comment by glenn-jocher** [comment]
Thank you for sharing your solution! If you have any other questions or need further assistance, feel free to ask.
