### ISSUE TITLE
GPU for Windows

### ISSUE THREAD

**Issue by fnoroozi** [ultralytics/ultralytics#290]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to use Yolov8 on windows with GPU.
It works for CPU, but not for GPU...

For having it on GPU I executed this command: 
yolo task=classify mode=train device=0

**Comment by mjan2021** [comment]
It supports GPU on windows. You need to verify if you Pytorch is installed correctly with GPU support. 
Try this:
`import torch
torch.cuda.is_available()
`

if this return false then try to reinstall as sometimes Pytorch installed from requirement file doesn't work properly
Here is the command to reinstall pytorch.

`pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu116`

**Comment by pderrenger** [comment]
@mjan2021 it sounds like you're experiencing issues with running YOLOv8 on GPU in a Windows environment. YOLOv8 does support GPU on Windows, and the issue might stem from the PyTorch installation on your system.

To troubleshoot, you can check if PyTorch is installed correctly with GPU support by running the following commands in a Python environment:
```python
import torch
print(torch.cuda.is_available())
```

If the above command returns `False`, it's possible that the PyTorch installation isn't properly configured for GPU support. In that case, you can consider reinstalling PyTorch with GPU support using the command:
```bash
pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu116
```
Reinstalling PyTorch with the specified version and the CUDA toolkit version may potentially resolve the issue you're encountering.
