### ISSUE TITLE
Small sample, needs to be generated with data augmentation

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#2902]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

<img width="518" alt="微信截图_20230530094148" src="https://github.com/ultralytics/ultralytics/assets/6490927/956fdd4b-d14f-4a24-b70d-e6ca617aca86">

https://docs.ultralytics.com/yolov5/tutorials/architecture_description/#2-data-augmentation

The official built-in data enhancement features require the use of these enhancements to generate a local enhanced dataset

For example, I only have 20 images and annotation files

These enhancement tools are needed to generate 2000 enhanced datasets

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@monkeycc hello! Thank you for opening the issue. 

To generate more augmented data, you can use the data augmentation scripts included in this repo. You can find them in this directory: yolo5/data/scripts. 

To use these scripts, you will need to specify the number of augmented images per original image you would like to generate and the augmentation techniques that you would like to apply. Once you have specified these settings, run the script and it will output the augmented images to the desired location. 

If you're interested in contributing to the repo, we welcome pull requests!

**Comment by sgiessl** [comment]
Hi @glenn-jocher, thanks a lot for the pointer. These mentioned scripts seem great for the mentioned purpose. I can't find `yolo5/data/scripts`, however.

Thus, to confirm: Did you mean `ultralytics/yolo/data/augment.py` or a more specific CLI tool?
