### ISSUE TITLE
What is that output meaning?

### ISSUE THREAD

**Issue by RosterMouch** [ultralytics/ultralytics#2903]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,i am trying to deploy my yolov8 model on NVIDIA Triton Inference Server,Yet i really don't understand the output meaning.
I got 18 class of objects,so my output size ofcourse is 22(plus 4 dim of x and y)xN,right?
But the value of output is really let me difficult to understand.
Here is the code:
```python
result = resp.get_result().as_numpy('output0')[0]
result = np.squeeze(result)
result = np.max(result, axis=0)
print(result[0:22])
``` 
By this code,the output look like that:
```bash
(triton) elin@ElinStation:~/modelTraining/triton/client$ python test.py 
[ 29.414284  23.126179  24.103891  22.758266  29.911556  49.36591
  52.804134  57.661083  62.714092  65.95106   75.47911   76.86234
  96.27799  107.696075 103.21292  111.21729  125.02727  126.521866
 138.86092  148.25026  157.74384  172.12064 ]
shape = (8400,)
```
But when i turn the `np.max()` function axis parameter to 1(for col),the output then looks like this:
```bash
(triton) elin@ElinStation:~/modelTraining/triton/client$ python test.py 
[6.3994720e+02 6.3980029e+02 2.2565619e+02 1.4506529e+02 6.2266648e-02
 1.8682373e-01 1.1130452e-02 8.2867295e-01 2.9208952e-01 2.2261560e-01
 4.5381045e-01 3.3943713e-02 1.8533468e-02 1.7693639e-03 5.5097103e-02
 4.7784865e-02 8.6811227e-01 7.9423904e-02 7.4019545e-01 4.8605204e-03
 1.1030436e-03 6.1564749e-01]
shape = (22,)
```
So which one is the correct result of detection?

**Comment by glenn-jocher** [comment]
@RosterMouch hello,

The output of the YOLOv8 model is a 1D array of length 22xN, where N is the number of detected objects. The first 4 values in the array represent the x, y, width, and height of the bounding box, followed by 18 values representing the confidence scores of each class. 

In your code example, the `np.max()` function is being used to find the class with the highest confidence score for each detected object. When `axis=0` is used, the highest confidence score across all classes is found for each detected object and the resulting array has shape (22,). When `axis=1` is used, the highest confidence score for each individual class is found across all detected objects, and the resulting array has shape (8400,).

The correct output to use depends on the specific use case. If you want to know the class with the highest confidence score for each detected object, use the output with shape (22,). If you want to know which classes have the highest confidence scores overall, use the output with shape (8400,) and then process it further. 

Let me know if you have any further questions.

**Comment by RosterMouch** [comment]
> @RosterMouch hello,
> 
> The output of the YOLOv8 model is a 1D array of length 22xN, where N is the number of detected objects. The first 4 values in the array represent the x, y, width, and height of the bounding box, followed by 18 values representing the confidence scores of each class. 
> 
> In your code example, the `np.max()` function is being used to find the class with the highest confidence score for each detected object. When `axis=0` is used, the highest confidence score across all classes is found for each detected object and the resulting array has shape (22,). When `axis=1` is used, the highest confidence score for each individual class is found across all detected objects, and the resulting array has shape (8400,).
> 
> The correct output to use depends on the specific use case. If you want to know the class with the highest confidence score for each detected object, use the output with shape (22,). If you want to know which classes have the highest confidence scores overall, use the output with shape (8400,) and then process it further. 
> 
> Let me know if you have any further questions.

Sorry I am still confused sir.I just wanna to extract all detections and it's bounding boxes to plot it on image frmae,how should i chose with those 22xN tensor and 8400xN tensor and how to processing them?

**Comment by RosterMouch** [comment]
> @RosterMouch hello,
> 
> The output of the YOLOv8 model is a 1D array of length 22xN, where N is the number of detected objects. The first 4 values in the array represent the x, y, width, and height of the bounding box, followed by 18 values representing the confidence scores of each class. 
> 
> In your code example, the `np.max()` function is being used to find the class with the highest confidence score for each detected object. When `axis=0` is used, the highest confidence score across all classes is found for each detected object and the resulting array has shape (22,). When `axis=1` is used, the highest confidence score for each individual class is found across all detected objects, and the resulting array has shape (8400,).
> 
> The correct output to use depends on the specific use case. If you want to know the class with the highest confidence score for each detected object, use the output with shape (22,). If you want to know which classes have the highest confidence scores overall, use the output with shape (8400,) and then process it further. 
> 
> Let me know if you have any further questions.

Or otherwise i just iterate all this output and extract the most higher confidence score class as an label?
But that's to weried,8400 object!My Image doesn't contains those too much for sure.😂

**Comment by RosterMouch** [comment]
> @RosterMouch hello,
> 
> The output of the YOLOv8 model is a 1D array of length 22xN, where N is the number of detected objects. The first 4 values in the array represent the x, y, width, and height of the bounding box, followed by 18 values representing the confidence scores of each class.
> 
> In your code example, the `np.max()` function is being used to find the class with the highest confidence score for each detected object. When `axis=0` is used, the highest confidence score across all classes is found for each detected object and the resulting array has shape (22,). When `axis=1` is used, the highest confidence score for each individual class is found across all detected objects, and the resulting array has shape (8400,).
> 
> The correct output to use depends on the specific use case. If you want to know the class with the highest confidence score for each detected object, use the output with shape (22,). If you want to know which classes have the highest confidence scores overall, use the output with shape (8400,) and then process it further.
> 
> Let me know if you have any further questions.

I finally made this,here is the code to extract the bounding boxes and most confidence class:
```python
@numba.jit
def extractFeature(inferenceResult:np.ndarray) -> np.ndarray:
    final = []
    for i in inferenceResult:
        temp = []
        box = i[:4]
        for j in box:
            temp.append(j)
        confidence = i[4:]
        classIndex = np.where(confidence == np.max(confidence))[0][0]
        temp.append(classIndex)
        final.append(temp)
    final = np.array(final)
    # drop duplicate boxes
    final = np.unique(final, axis=0)
    return final
result = resp.get_result().as_numpy('output0')[0].T
result = np.squeeze(result)
result = extractFeature(result)
print(result.shape)
```
But i really wanna ask that:is 8400 objects logical?(just curious lol😂)

**Comment by glenn-jocher** [comment]
Hi @RosterMouch,

I'm glad to hear that you were able to extract the bounding boxes and classes from the YOLOv8 output.

In regards to your question about the number of objects detected, It is possible for the YOLOv8 model to detect a large number of objects depending on the input image. However, it is unusual to detect 8400 objects in a single image. It's possible that there are duplicates in the detections or that the confidence score threshold is set too low, causing false positives to be detected as objects.

In your code example, you're dropping duplicate boxes by calling `np.unique(final, axis=0)`. This is a good way to remove any duplicate detections and possibly reduce the number of detected objects.

I hope this explanation helps. Let me know if you have any further questions or concerns.

**Comment by RosterMouch** [comment]
> Hi @RosterMouch,
> 
> I'm glad to hear that you were able to extract the bounding boxes and classes from the YOLOv8 output.
> 
> In regards to your question about the number of objects detected, It is possible for the YOLOv8 model to detect a large number of objects depending on the input image. However, it is unusual to detect 8400 objects in a single image. It's possible that there are duplicates in the detections or that the confidence score threshold is set too low, causing false positives to be detected as objects.
> 
> In your code example, you're dropping duplicate boxes by calling `np.unique(final, axis=0)`. This is a good way to remove any duplicate detections and possibly reduce the number of detected objects.
> 
> I hope this explanation helps. Let me know if you have any further questions or concerns.

Thanks a lot,close.

**Comment by glenn-jocher** [comment]
Hello @RosterMouch,

Thanks for reaching out! 

It is unusual for the YOLOv8 model to detect 8400 objects in a single image. This may be caused by duplicates in the detections, or the confidence score threshold might be set too low, resulting in false positives being detected as objects.

However, in your code example, you are dropping duplicate boxes with `np.unique(final, axis=0)`. This is a good way to remove any duplicate detections and possibly reduce the number of detected objects.

I hope this helps. Please let me know if you have any further questions or concerns.

Best regards.
