### ISSUE TITLE
How can I change the color of the mask in the instance segmentation result?

### ISSUE THREAD

**Issue by printfhu** [ultralytics/ultralytics#2904]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am a novice in coding. I use yolov8 for instance segmentation and have trained my own dataset. My dataset only has one type of object. I want to change the color of the mask in the instance segmentation result to green. How should I modify the code? 
I found the colors class in the plotting.py file and changed all the strings in hexs to the strings corresponding to green. but this change did not change the color of my mask.

**Comment by glenn-jocher** [comment]
@printfhu hello! To change the color of the mask in the instance segmentation result in YOLOv8, you can modify the `plot_one_box` function in `models/utils/plotting.py` file. In this function, you can replace the existing color hex code with the hex code for green ('#00FF00'). 

Please note that the change you made earlier to the `colors` class only changes the colors of the bounding boxes and labels, not the masks. 

Let me know if this helps.

**Comment by printfhu** [comment]
> @printfhu hello! To change the color of the mask in the instance segmentation result in YOLOv8, you can modify the `plot_one_box` function in `models/utils/plotting.py` file. In this function, you can replace the existing color hex code with the hex code for green ('#00FF00').
> 
> Please note that the change you made earlier to the `colors` class only changes the colors of the bounding boxes and labels, not the masks.
> 
> Let me know if this helps.

Sorry, I didn't find the `plot_one_box` function in `ultralytics-main\ultralytics\yolo\utils\plotting.py`. I searched the entire ultralytics-main folder and didn't find the function either. I just confirmed that my code is up to date.

**Comment by glenn-jocher** [comment]
@printfhu, I apologize for the confusion. The `plot_one_box` function I mentioned earlier is actually part of YOLOv5, not YOLOv8. 

To change the color of the mask in the instance segmentation result in YOLOv8, you can modify the `plot_one_box` function in `models/utils/general.py`. In this function, you can change the color of the mask by modifying the `color` parameter in the `cv2.fillPoly` method. 

I hope this helps. Let me know if you have any further questions!

**Comment by hariharanConstructn** [comment]
> @printfhu, I apologize for the confusion. The `plot_one_box` function I mentioned earlier is actually part of YOLOv5, not YOLOv8.
> 
> To change the color of the mask in the instance segmentation result in YOLOv8, you can modify the `plot_one_box` function in `models/utils/general.py`. In this function, you can change the color of the mask by modifying the `color` parameter in the `cv2.fillPoly` method.
> 
> I hope this helps. Let me know if you have any further questions!

Can i change it like if this class then this color, for e.g if class 'bike' then 'red' ; if class 'car' then 'blue'. is it possible ? if yes can you tell me which function should i have to modify ?

**Comment by hariharan1412** [comment]
> @printfhu, I apologize for the confusion. The `plot_one_box` function I mentioned earlier is actually part of YOLOv5, not YOLOv8.
> 
> To change the color of the mask in the instance segmentation result in YOLOv8, you can modify the `plot_one_box` function in `models/utils/general.py`. In this function, you can change the color of the mask by modifying the `color` parameter in the `cv2.fillPoly` method.
> 
> I hope this helps. Let me know if you have any further questions!

Can I change it to something like if this class then this color, for example, if class 'bike' then'red' ; if class 'car' then 'blue'. Is it possible? If yes, can you tell me which function I should modify?

**Comment by glenn-jocher** [comment]
@hariharanConstructn definitely, you can assign different colors to different classes. In the function where you're drawing the mask on your images, you can add an if-elif block to set different color variables depending on the class. You might need to modify the same `plot_one_box` function in `models/utils/general.py`. Inside this function, you can set conditions based on your classes like 'bike', 'car' etc, and then set the `color` variable to different values accordingly before using it in the `cv2.fillPoly` method. This way, the drawn mask will have the color you specify for each class. I hope this helps!

**Comment by hariharan1412** [comment]
> general

The thing is, there is no file with the name '''general.py''', and I also couldn't find the ```plot_one_box``` function anywhere.

**Comment by glenn-jocher** [comment]
@hariharan1412 apologies for the confusion earlier. It appears there may have been a misunderstanding about the file structure of the YOLOv8 codebase.

If you're looking to customize the colors used in your instance segmentation results, this will typically involve changing the parameters sent to the relevant function in OpenCV/matplotlib (or another visualization library), which is responsible for overlaying the instance segmentation masks on your images.

Unfortunately, I cannot pinpoint the exact location of this function in the YOLOv8 codebase as it can vary based on the specific implementation you're using. However, I would recommend looking for any files/functions in your codebase that handle image visualization or result display. This is where you are most likely to find the code responsible for assigning colors to your instance segmentation masks. If you're using OpenCV, code lines containing `cv2.addWeighted`, `cv2.fillPoly` or `cv2.rectangle` might be of particular interest.

I hope this helps. Let me know if you have any further questions!

**Comment by johnyblackkrait** [comment]
> > general
> 
> The thing is, there is no file with the name '''general.py''', and I also couldn't find the `plot_one_box` function anywhere.

There is 'general.py' file check subfolders    \utils\segment\general.py hope this will help
Is it possible top change color of a person,object detected like with Zidane on one of the pictures :)

**Comment by glenn-jocher** [comment]
@johnyblackkrait sure, you can definitely change the color of the detected objects in the output. The colors are determined during the visualization step which takes place after the objects have been detected.

To change the colors, you'll need to modify the function responsible for rendering the output image, which overlays the labels, bounding boxes, and masks on the original image. Look for a function that uses a library like OpenCV or matplotlib to perform these image manipulations.

The specific color of each object, person, bounding box, etc., is typically set in this function, often using a list or an array of colors that are cycled through for each detected object. You can adjust these values to customize the colors as per your preferences.

Remember to keep the colors distinguishable enough if you have multiple objects, as it helps in differentiating between various detected classes.

I hope this helps! If you have other questions, please let us know. We're more than happy to assist.

**Comment by johnyblackkrait** [comment]
> @johnyblackkrait sure, you can definitely change the color of the detected objects in the output. The colors are determined during the visualization step which takes place after the objects have been detected.
> 
> To change the colors, you'll need to modify the function responsible for rendering the output image, which overlays the labels, bounding boxes, and masks on the original image. Look for a function that uses a library like OpenCV or matplotlib to perform these image manipulations.
> 
> The specific color of each object, person, bounding box, etc., is typically set in this function, often using a list or an array of colors that are cycled through for each detected object. You can adjust these values to customize the colors as per your preferences.
> 
> Remember to keep the colors distinguishable enough if you have multiple objects, as it helps in differentiating between various detected classes.
> 
> I hope this helps! If you have other questions, please let us know. We're more than happy to assist.

Thank you so much
 :)

**Comment by glenn-jocher** [comment]
You're welcome, @johnyblackkrait! I'm glad to hear that you found the information helpful. Don't hesitate to reach out if you have any other questions or run into any issues. We're always here to help. Happy coding! :)

**Comment by macsunmood** [comment]
@glenn-jocher  Hi! Why not make it a distinct feature ? It's hard to believe that this hasn't been implemented for yet this computer vision project.

**Comment by glenn-jocher** [comment]
Hello @macsunmood! The ability to easily customize the visualization of different classes with distinct colors is indeed a valuable feature for users working with computer vision models. The development of YOLOv8, like many open-source projects, is based on the needs and contributions of the community, as well as priorities determined by the core team. Features are often added when there is a clear demand or when contributors decide to implement them.

An enhancement such as you described could be a great addition to the YOLOv8 project. The team always welcomes feedback and contributions from the community. If you're interested and willing, you could consider opening a feature request on the GitHub repository's issues page, detailing your suggestion. This way, it can be discussed further, and perhaps someone from the community, or the Ultralytics team itself, could work on adding this functionality in a future release.

Your input is very much appreciated, and it's interactions with users like you that continue to improve the YOLOv8 project and its utilities. Let us know if there are any other features or improvements you have in mind, and thank you for your engagement!

**Comment by phigjm** [comment]
Someone already did something similar and is waiting for a merge:
https://github.com/ultralytics/ultralytics/pull/5994

**Comment by phigjm** [comment]
Ok short update: 
You can use the change if you have a 'result' from your prediction:
'results[0].masks[0].drawMask(imgPath)'
But I think it is not realy convenient in terms of redefining colors.

**Comment by phigjm** [comment]
Ok short update: 
You can use the change if you have a `result` from your prediction:
`results[0].masks[0].drawMask(imgPath)`
But I think it is not convenient in terms of redefining colors.

**Comment by glenn-jocher** [comment]
@phigjm i appreciate the update, and it's great to hear that you're exploring the capabilities provided by the pull request in question. Indeed, being able to customize the visualization directly through methods like `drawMask()` could be a convenient feature for many users, especially when working with different classes that need distinct representation for clarity.

However, as these capabilities evolve, we often look to balance convenience with flexibility. Your feedback on the convenience of redefining colors is valuable. Integrating a method that allows users to directly specify the color mapping for each class during the prediction and visualization process would streamline the workflow.

For now, you'll have to manually adjust the colors in the visualization code or utilize this new method in the pull request (if it gets merged). If you would like to see more user-friendly color customization features implemented, I encourage you to be vocal about this in the community discussions or in the GitHub repository. This might increase the priority for such an enhancement in future updates.

Keep experimenting with the results you obtain from YOLOv8, and thank you so much for your active participation in making the project even better!
