### ISSUE TITLE
I would like to understand more about 2D and 3D coordinates.

### ISSUE THREAD

**Issue by mitesh741** [ultralytics/ultralytics#2905]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have read documentation of Pose model and found this line: 2D [x, y] or 3D [x, y, visible] coordinates.

But not able to understand what that 'visible' is for. 

Also, Do we have option to switch to 2D or 3D coordinates?

If yes, how?

Thanks.

### Additional

Nope. Thanks

**Comment by Johan154** [comment]
I have worked with pose estimation models in the past. You can not always see a keypoint, but you can still guess where it approximately should be. When you cannot see the keypoint, but you guess it,  you should also mark it as not visible. The keypoints that you can see should of course be labeled as visible. This is how I remember it.

**Comment by glenn-jocher** [comment]
@mitesh741 regarding your question about the 2D and 3D coordinates, the "visible" parameter is used to mark whether a keypoint is visible or not. In some scenarios when tracking human poses, certain keypoints may not always be visible but can be guessed based on the visible keypoints. For such cases, we can still label the keypoint with an approximate location but mark it as not visible. If a keypoint is visible, we simply mark it as visible.

Regarding your second question, YOLOv8 supports both 2D and 3D coordinates and you can switch between them based on your application needs. The type of the coordinates should be specified in the annotations file that you provide for training the model. If you want to switch from 2D to 3D coordinates, or vice versa, you would need to modify the data format of your annotations file accordingly.

**Comment by mitesh741** [comment]
Got it thank you very much @glenn-jocher

**Comment by glenn-jocher** [comment]
You're welcome, @mitesh741! If you have any further questions or if there's anything else I can help you with, feel free to ask. We are always happy to assist the YOLOv8 community!

**Comment by sheyteo** [comment]
@glenn-jocher  I would like to confirm if the YAML configuration file should include kpt_shape: [keypoint_number, 3] for 3D keypoints, and if the annotation file should list the coordinates as<class-index> <x> <y> <width> <height> <px1> <py1>  <pz1> <px2> <py2> <pz2> ..., with all values scaled between 0 and 1. Do i also scale the z values between 0 and 1, where 0 is the nearest a keypoint can be a 1 the furthest a keypoint can be ? Thank you

**Comment by glenn-jocher** [comment]
Yes, you are correct. For 3D keypoints, the `kpt_shape` in the YAML configuration file should be `[keypoint_number, 3]`. The annotation file should list the coordinates as `class-index x y width height px1 py1 pz1 px2 py2 pz2 ...`, with all values scaled between 0 and 1. This includes scaling the z values, where 0 represents the nearest a keypoint can be and 1 represents the furthest. If you encounter any issues, please ensure you are using the latest package versions. Thank you.

**Comment by sheyteo** [comment]
Thank you for your response @glenn-jocher. Do you perhaps have any suggestions what i could change and try to get 3d Keypoints working. I already opened an issue : [here](https://github.com/ultralytics/ultralytics/issues/14883.)

**Comment by HouraHashemi** [comment]
Umm... I am working on getting 3D pose estimation from a 2D image, and I can't find an open-source yolo repository for that. The only thing I found was VideoPose3D (https://github.com/facebookresearch/VideoPose3D/tree/main), which was pretty old and had outdated TensorFlow versions. :)
I wonder if there's any similar research in yolo?

**Comment by glenn-jocher** [comment]
Ultralytics' YOLO models, including YOLOv8 and YOLO11, support 2D pose estimation, but for 3D pose estimation directly from 2D images, you would need additional processing or integration with specialized methods like VideoPose3D. Currently, YOLO does not natively provide 3D pose estimation functionality. You can explore combining YOLO's 2D keypoint outputs with external 3D reconstruction techniques for your project.

**Comment by glenn-jocher** [comment]
@HouraHashemi you're welcome! I'm glad you found "mmpose" helpful. If you decide to revisit YOLO or need assistance integrating its 2D pose estimation outputs with external 3D solutions, feel free to reach out. The YOLO community is always here to support you.
