### ISSUE TITLE
BBoxes

### ISSUE THREAD

**Issue by AI-P-K** [ultralytics/ultralytics#291]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to extract BBOXES and classes from the predicted result in python?

**Comment by luigisaetta** [comment]
@AI-P-K I have also seen that, differently from Yolo v5, in the inference API this part is missing. I have written some custom code to extract BB. If you need I can provide an example. @glenn-jocher I think you're working on completing the inference API. Am I right?

**Comment by AI-P-K** [comment]
@luigisaetta, that would be fantastic. I need info such BB, classes, confidences if possible.. but anything would do to be honest.

**Comment by AyushExel** [comment]
@luigisaetta @AI-P-K we're working on something like that. interacting with outputs will be easy, fast and efficient very soon. Thanks for your patience!
