### ISSUE TITLE
Loading network share images on Windows 

### ISSUE THREAD

**Issue by maulakhan** [ultralytics/ultralytics#2912]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

In Line `159` of  `stream_loaders.py`, replacing `resolve()` by `absolute()` solves this problem

```

  File ~\Miniconda3\envs\yolo\lib\site-packages\ultralytics\yolo\data\dataloaders\stream_loaders.py:159 in __init__
    p = str(Path(p).resolve())
  File ~\Miniconda3\envs\yolo\lib\pathlib.py:1215 in resolve
    s = self._flavour.resolve(self, strict=strict)

  File ~\Miniconda3\envs\yolo\lib\pathlib.py:215 in resolve
    s = self._ext_to_normal(_getfinalpathname(s))

PermissionError: [WinError 5] Access is denied: '\\\\network\\share\\me\\'
```

### Environment

- OS: Windows 11
-  Python: 3.9.16
- Ultralytics: 8.0.111

### Minimal Reproducible Example

```
model.predict(source='\\network\\share\\me', save=True, imgsz=320, conf=0.5)

```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@maulakhan there are quite a few usages in the repo:

<img width="1112" alt="Screenshot 2023-05-30 at 21 32 04" src="https://github.com/ultralytics/ultralytics/assets/26833433/b3db5157-545f-48f8-859c-b85f99078be6">

**Comment by glenn-jocher** [comment]
@maulakhan see if https://github.com/ultralytics/ultralytics/pull/2915 works for you please.

**Comment by maulakhan** [comment]
> "Should we replace resolve with absolute everywhere throughout the repo though or just this one place?"

no the rest of the usages do not create any problem during training and prediction. So, only where I mentioned

**Comment by maulakhan** [comment]
> @maulakhan see if #2915 works for you please.
YES! Works now

**Comment by maulakhan** [comment]
> @maulakhan there are quite a few usages in the repo:
> 
> <img alt="Screenshot 2023-05-30 at 21 32 04" width="1112" src="https://user-images.githubusercontent.com/26833433/242077615-b3db5157-545f-48f8-859c-b85f99078be6.png">

Maybe I have to first test all these usages then to see if save directories usages also throw the same error

**Comment by glenn-jocher** [comment]
Hi @maulakhan!

Thank you for reporting the issue and for the PR!

Regarding the other usages in the repo, we certainly recommend testing them to verify if the same issue arises for save directories usage. 

Again, thank you for bringing this to our attention and your contribution to YOLOv8! Let us know if there's anything else we can help you with.

**Comment by maulakhan** [comment]
The saving of results on a network share address works well

**Comment by YuanKJing** [comment]
I want to know what the file path format is. I have tried many forms of file path formats, but they all say that my picture does not exist.

![AYC{XR%8V3ZQ_CXXOYGX3YR](https://github.com/ultralytics/ultralytics/assets/151496800/8e7e436a-e598-4a61-82d0-603b67a468e6)

**Comment by glenn-jocher** [comment]
@YuanKJing hi there! 🙌 It seems like you're having trouble with specifying the file path. Typically, a straightforward approach works best. If you're on Linux or macOS, your path might look like `/path/to/your/image.jpg`, and on Windows, it should be like `C:\\path\\to\\your\\image.jpg`. 

Make sure the path is correct and points exactly where your image is stored. For instance:

```python
from ultralytics import YOLO

model = YOLO('yolov8n.pt')
results = model.predict(source='/path/to/your/image.jpg')
```

If your image is in the same directory as your script, simply using `image.jpg` as the path should work. Let me know how it goes!

**Comment by YuanKJing** [comment]
Thank you for your answer，but unfortunatly i had made a stupid mistake that i use this code on colab but i forget to Upload my local dataset ，
I'm sorry that this kind of thing has taken up your time. wishing the YOLO team better and better

---Original---
From: "Glenn ***@***.***&gt;
Date: Wed, Mar 27, 2024 04:42 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ultralytics/ultralytics] Loading network share images on Windows (Issue #2912)




 
@YuanKJing hi there! 🙌 It seems like you're having trouble with specifying the file path. Typically, a straightforward approach works best. If you're on Linux or macOS, your path might look like /path/to/your/image.jpg, and on Windows, it should be like C:\\path\\to\\your\\image.jpg.
 
Make sure the path is correct and points exactly where your image is stored. For instance:
 from ultralytics import YOLO model = YOLO('yolov8n.pt') results = model.predict(source='/path/to/your/image.jpg')
 
If your image is in the same directory as your script, simply using image.jpg as the path should work. Let me know how it goes!

**Comment by glenn-jocher** [comment]
No worries at all, @YuanKJing! 😊 Mistakes happen to the best of us, especially when switching between local and cloud environments like Colab. I'm glad you figured it out! Remember, we're here to help, no matter how small the issue might seem. Wishing you success with your YOLOv8 projects, and if you ever run into any more hurdles or have questions, don't hesitate to reach out. Cheers to making awesome progress together! 🚀
