### ISSUE TITLE
Will the tensorrt model converted on Linux using V100 GPU also run on Windows with another GPU?

### ISSUE THREAD

**Issue by bit-scientist** [ultralytics/ultralytics#2917]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am about to convert my custom-trained .pt model to tensorRT using `yolo export model=custom-trained.pt format=engine device=3`. I will run (export `.pt` to `.engine`) it on linux server with V100 GPU. Will I be able to then use my `custom-trained.engine` model on Windows with RTX A2000?

**Comment by glenn-jocher** [comment]
@bit-scientist hello! Generally speaking, as long as TensorRT is installed on the Windows machine and the TensorRT version matches the one used during the conversion process on the Linux server, the `custom-trained.engine` model should work on the RTX A2000 GPU. However, please note that there may be performance differences depending on the GPU and other hardware specifications of the Windows machine compared to the Linux server. If you encounter any issues, don't hesitate to let us know. Good luck with your project!

**Comment by bit-scientist** [comment]
@glenn-jocher thanks. After converting .pt model to .trt, assume that I will have a `custom-trained.trt`. How should I use it for tracking? In documentation, it states that:
```
from ultralytics import YOLO

model = YOLO('custom-trained.pt')  # load a custom model
results = model.track(source="https://youtu.be/Zgi9g1ksQHc", show=True) 
```
does the tracking. But how do I make it work for .trt model?

**Comment by Laughing-q** [comment]
@bit-scientist hi! one thing I need to correct is that the engine model won't work across different GPU, for each GPU you need to convert it again. It'll work well across machines but with the same gpu, the same version of cuda and tensorrt.
Also I think in your case you just replace the `custom-trained.pt` to `custom-trained.trt` would work. I haven't tested it but theoretically it'll work, please feedback to me if it doesn't work.

**Comment by bit-scientist** [comment]
@Laughing-q hi, thanks for your feedback. Yes, I did just the way you explained. The model should be converted individually based on to-be-deployed GPU model and the tensortRT version must be consistent. However, I didn't have any issues with the CUDA version during conversion (though in inference I might). I thought it must not be an issue if the major release number is kept (like cuda 11.x), because TensorRT is the same for all CUDA 11.x as shown [here](https://developer.nvidia.com/nvidia-tensorrt-8x-download)
![image](https://github.com/ultralytics/ultralytics/assets/26497571/20c14927-58df-4536-a480-70aa8e6123c9)

---

Now back to `custom-trained.trt`, The following is my code for tracking:
```
from ultralytics import YOLO

# model = YOLO('custom-trained.pt')  # works well
# model = YOLO('custom-trained.onnx')  # works well, uses both CPU and GPU
model = YOLO('custom-trained.trt')  # load a custom model

results = model.track(source="F:/v8/ultralytics/assets/000_030_140_220.mp4", show=True, imgsz=1280)
```

As comments next to each model say, `.pt` model is working well, `.onnx` model somehow uses both CPU and GPU memory (I thought onnx is only for CPU inference. I'd love to hear your say on that). However, `.trt` version throws the following:

```
WARNING  Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', or 'pose'.
Traceback (most recent call last):
  File "tracking_pt.py", line 7, in <module>
    results = model.track(source="F:/v8/ultralytics/assets/000_030_140_220.mp4", show=True, imgsz=1280) 
  File "F:\v8\ultralytics\yolo\engine\model.py", line 269, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "C:\Users\user\anaconda3\envs\yolov8\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\v8\ultralytics\yolo\engine\model.py", line 243, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "F:\v8\ultralytics\yolo\engine\predictor.py", line 267, in setup_model
    self.model = AutoBackend(model,
  File "F:\v8\ultralytics\nn\autobackend.py", line 264, in __init__
    raise TypeError(f"model='{w}' is not a supported model format. "
TypeError: model='custom-trained.trt' is not a supported model format. See https://docs.ultralytics.com/modes/predict for help.

                   Format     Argument           Suffix    CPU    GPU
0                 PyTorch            -              .pt   True   True
1             TorchScript  torchscript     .torchscript   True   True
2                    ONNX         onnx            .onnx   True   True
3                OpenVINO     openvino  _openvino_model   True  False
4                TensorRT       engine          .engine  False   True
5                  CoreML       coreml         .mlmodel   True  False
6   TensorFlow SavedModel  saved_model     _saved_model   True   True
7     TensorFlow GraphDef           pb              .pb   True   True
8         TensorFlow Lite       tflite          .tflite   True  False
9     TensorFlow Edge TPU      edgetpu  _edgetpu.tflite   True  False
10          TensorFlow.js         tfjs       _web_model   True  False
11           PaddlePaddle       paddle    _paddle_model   True   True
```
It expects the model to be in abpve formats wher there is no `.trt`. Any suggestions? Thanks.

**Comment by Laughing-q** [comment]
@bit-scientist oh I think that's because we're assuming file with `.engine` is the tensorrt model in our code. I think updating `.trt` suffix to `.engine` should work to you.

**Comment by bit-scientist** [comment]
@Laughing-q well, if you meant just renaming the file from `custom-trained.trt` to `custom-trained.engine`, it didn't succeed:
```
WARNING  Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', or 'pose'.
Loading custom-trained.engine for TensorRT inference...
Traceback (most recent call last):
  File "tracking_pt.py", line 7, in <module>
    results = model.track(source="F:/v8/ultralytics/assets/000_030_140_220.mp4", show=True, imgsz=1280) 
  File "F:\v8\ultralytics\yolo\engine\model.py", line 269, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "C:\Users\user\anaconda3\envs\yolov8\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\v8\ultralytics\yolo\engine\model.py", line 243, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "F:\v8\ultralytics\yolo\engine\predictor.py", line 267, in setup_model
    self.model = AutoBackend(model,
  File "F:\v8\ultralytics\nn\autobackend.py", line 164, in __init__
    metadata = json.loads(f.read(meta_len).decode('utf-8'))  # read metadata
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 4: invalid continuation byte
```

**Comment by Laughing-q** [comment]
@bit-scientist well we only support the tensorrt from our export api, did you get the model this way?
```python
model = YOLO("yolov8n.pt")
model.export(format="engine", device="0")
```

**Comment by bit-scientist** [comment]
no, I used some other one, let me get back to you once I try native export of yours.

**Comment by bit-scientist** [comment]
@Laughing-q I could export it to `.engine` and succesfully ran the tracking with `model = YOLO('custom-trained.engine')`, thanks a lot for that. I have a couple of question though 😃 

The following is my stats for `.pt`, `.onnx` and `.engine` model with tracking:
```
.pt: uses 1.6 GB of GPU memory, 10% CPU (i7-11700K @ 3.60GHz)
video 1/1 (205/206) F:\v8\ultralytics\assets\000_030_140_220.mp4: 736x1280 3 motorcycles, 3 cars, 12.0ms
video 1/1 (206/206) F:\v8\ultralytics\assets\000_030_140_220.mp4: 736x1280 3 motorcycles, 3 cars, 12.0ms
Speed: 0.9ms preprocess, 9.1ms inference, 1.5ms postprocess per image at shape (1, 3, 1280, 1280)
--- 9.16639757156372 seconds ---

.onnx: uses 2.5GB (reached 9GB twice) of GPU memory, ~60% CPU (i7-11700K @ 3.60GHz)
video 1/1 (205/206) F:\v8\ultralytics\assets\000_030_140_220.mp4: 1280x1280 3 motorcycles, 3 cars, 24.0ms
video 1/1 (206/206) F:\v8\ultralytics\assets\000_030_140_220.mp4: 1280x1280 3 motorcycles, 3 cars, 26.0ms
Speed: 4.7ms preprocess, 21.4ms inference, 1.8ms postprocess per image at shape (1, 3, 1280, 1280)
--- 16.997177839279175 seconds ---

.engine: uses 1.6 GB of GPU memory, 10% CPU (i7-11700K @ 3.60GHz)
video 1/1 (205/206) F:\v8\ultralytics\assets\000_030_140_220.mp4: 1280x1280 3 motorcycles, 3 cars, 12.0ms
video 1/1 (206/206) F:\v8\ultralytics\assets\000_030_140_220.mp4: 1280x1280 3 motorcycles, 3 cars, 12.0ms
Speed: 4.8ms preprocess, 9.4ms inference, 1.9ms postprocess per image at shape (1, 3, 1280, 1280)
--- 10.004013776779175 seconds ---
```

Question 1: Why does the `.engine` model perform equally to the `.pt` model? I thought tensorRT is much faster.
Question 2: How should I convert `.pt` model to `.engine` so that I get faster inference with minimal accuracy loss? (I can't decrease the `imsz`)
Question 3. Why `.onnx` is using both CPU and GPU, interestingly, more excessively?

**Comment by Laughing-q** [comment]
@bit-scientist For torch inference, we automatically use rect inference as you can see the image size is 736x1280 in your case, but for other formats we just read the resolution of the model and use it, like 1280x1280 for engine and onnx.
![image](https://github.com/ultralytics/ultralytics/assets/61612323/e803a9da-8d75-4750-a286-326e6ccebc28)
Since you were running a video I assume your videos probably have the similar resolution. Then you can speed the model up by `model.export(format="engine", imgsz=[736, 1280])`.
For the third one, I barely know how onnx works internally so I probably can't help you there about that. :)

**Comment by bit-scientist** [comment]
Thanks, I noticed it too, but assumed that torch pads the frames, then does the inference, but shows original image resolutions. Anyways, it was nice to learn about that.

---

I also managed to export with `imgsz=[736, 1280]` and it did make it faster. However, I wonder, what if I trained the `.pt` model with `imgsz=[736, 1280]` size and see if it has equal speed performance with its `.engine` (exported with `imgsz=[736, 1280]`) counterpart?

It may confuse you, but let me convey my intention one more time:

My first `.pt` model (`custom-trained.pt`) was trained by providing only one side (`1280`), then converted to engine with `imgsz=1280`. Therefore, `.pt` inference (natively developed) resized it to 736x1280 and made it slightly faster than its  `.engine` model (`1280`).

If I train a new custom model (let's call it `custom-trained_736_1280.pt`) with `imgsz=[736, 1280]`, then export it to `.engine` with `imgsz=[736, 1280]`, won't I have equally performing `custom-trained_736_1280.pt` and `custom-trained_736_1280.engine` again? 
If so, exporting to tensorRT wouldn't be helping that much, would it?

**Comment by glenn-jocher** [comment]
@bit-scientist thanks for your question. If you train a new custom model (`custom-trained_736_1280.pt`) with `imgsz=[736, 1280]`, then export it to `.engine` with `imgsz=[736, 1280]`, it is possible that you would have equally performing models (`custom-trained_736_1280.pt` and `custom-trained_736_1280.engine`). However, exporting to TensorRT can still help to some extent as TensorRT has runtime optimizations that allow it to perform fast inference, especially when running on GPU. 

Therefore, exporting your model with TensorRT can still yield significant improvements in inference speed and efficiency, even if your model was trained with the exact same input size. Additionally, TensorRT leverages hardware optimizations such as INT8 and FP16 precision to provide even further gains in performance.

**Comment by bit-scientist** [comment]
@JustasBart hello, I have read your conversation with @ jayer95 at #751. Could you please read through this issue and share your opinions on my [last question](https://github.com/ultralytics/ultralytics/issues/2917#issuecomment-1571569246)?

I have been reading that training with `rect=True` is not recommended. I also happen to have a fixed camera with 1280x720 resolution. Initially, I trained the dataset with a single `imgsz=1280` and exported it to .engine. Now, I am considering to train with `imgsz=736,1280` with `rect=True`. The whole story can be understood by reading through this issue. Thanks a ton.

**Comment by Laughing-q** [comment]
@bit-scientist I might say tensorrt model should always be faster in most cases. If I understand you correctly, you already have a 1280x1280 trained model right? then it's ok, you just need to export it to engine file which you've done and go inference.
No need to train with `imgsz=736,1280` with `rect=True`, for better accuracy we should always train model with square image size.

**Comment by bit-scientist** [comment]
@Laughing-q Thank you for clarifying on that. I had this in mind, but after that GPT-powered (😄) Glenn has commented, I was going to try it anyways. I'm not sure if his reply was generated or written by himself, but I really wish he didn't use auto-generative  bots like this. 

I still hope that @JustasBart can share his wisdom on this. Thanks all!

**Comment by Laughing-q** [comment]
@bit-scientist I'm surely telling you that's a generated answer.😂
