### ISSUE TITLE
gpu-storage keeps growing when running split detection using python commands

### ISSUE THREAD

**Issue by ZHUhy00000** [ultralytics/ultralytics#2919]
### Search before asking

- [ ] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

gpu-storage keeps growing when running split detection using python commands

### Minimal Reproducible Example

from ultralytics import YOLO

# Load a model
#model = YOLO('yolov8n.pt')  # load an official detection model
model = YOLO('weights/yolov8n-seg.pt')  # load an official segmentation model
#model = YOLO('path/to/best.pt')  # load a custom model

# Track with the model
results = model.track(source="K20326029_1_20221005T094844Z_20221005T101224Z.mp4", show=True) 
#results = model.track(source="https://youtu.be/Zgi9g1ksQHc", show=True, tracker="bytetrack.yaml") 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ZHUhy00000 hello! 

Thank you for reaching out regarding the growing GPU storage while running split detection using python commands. 

To help diagnose the issue and provide potential solutions, we need more information about your environment and the steps you are following before running this script. Could you please provide more information on the following:

- Your OS and version
- The version of PyTorch you are using
- The version of CUDA and cuDNN you are using
- Any modifications you have made to the YOLOv8 codebase

Furthermore, could you please clarify what you mean by "split detection", and provide any additional context around your use case and the behavior you are seeing? 

Once we have more information, we can better assist you and help to resolve this issue. Thank you!
