### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by TapendraBaduwal** [ultralytics/ultralytics#2923]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Batch size = 2, image size=240
cuda True
1 device_count
0 current_device
NVIDIA GeForce RTX 3050 Laptop GPU  ..  get_device_name

Also while training on GPU for fine tune yolo8n.pt auto download even i have already  yolo8n.pt model....but working fine on CPU ?
Here is Transferred 319/355 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to yolov8n.pt...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.23M/6.23M [00:01<00:00, 6.53MB/s]
AMP: checks passed ✅

**Comment by TapendraBaduwal** [comment]
amp = False,
and  workspace =1 is good idea to solve the problem?

**Comment by glenn-jocher** [comment]
@TapendraBaduwal the error message you're seeing (`CUDA error: CUBLAS_STATUS_NOT_INITIALIZED`) can indicate that there are issues with CUBLAS, which is a CUDA library for performing basic linear algebra subroutines on GPUs. There could be many causes of this error, such as an incompatibility between your GPU and CUDA version or an issue with how you're initializing your CUDA context.

Regarding your question about `amp` and `workspace`, these are both settings that can affect the performance of your YOLOv8 training. By setting `amp` to `False`, you're disabling Automatic Mixed Precision (AMP), which is a feature that can help speed up your training by allowing your GPU to use half-precision floating-point numbers for some calculations. Setting `workspace` to `1` will cause the workspace memory to be allocated in a static buffer, which can save some time during training. 

However, changing these settings may not necessarily solve the `CUBLAS_STATUS_NOT_INITIALIZED` error, as this issue could have multiple causes. If you're still experiencing the error after making these changes, it may be helpful to check that your GPU driver and CUDA toolkit versions are compatible, check that your code is initializing the CUDA context correctly, or investigate other potential causes of the error.
