### ISSUE TITLE
长时间运行导致 inference 异常变慢

### ISSUE THREAD

**Issue by q465414859** [ultralytics/ultralytics#2926]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

长时间运行导致 inference 异常变慢
![1685454362739](https://github.com/ultralytics/ultralytics/assets/26251132/82cb36bd-58d9-4906-8b61-db4ea5302090)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@q465414859 thank you for bringing this issue to our attention. It sounds like you are experiencing inference slow down after prolonged runs. Based on your description, there might be several factors that could contribute to this behavior such as software or hardware limitations. To address this problem, we recommend you to check for possible memory leaks, optimize your code, and consider upgrading hardware if needed. We appreciate your willingness to contribute a PR and we look forward to working with you on this matter!
