### ISSUE TITLE
DDP yolov8-cls training bug

### ISSUE THREAD

**Issue by akkolyth** [ultralytics/ultralytics#2927]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

After running YoloV8 with args ```devices=[0, 1]```, DDP do not allocate GPU and freezes (the cell is running but there is no symptoms of started training). DDP looks strange: ```DDP command: ['/opt/conda/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '37607', '/opt/conda/lib/python3.11/site-packages/ipykernel_launcher.py']```. Below are yolo logs, and (gpu) nvidia-smi state while ```yolo.train(**args)``` cell is running.  

Yolov5 DDP training works completely fine on same environment. 

### Environment

* Ultralytics YOLOv8.0.111 rocket
* Python-3.11.3 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24260MiB)
                                                            CUDA:1 (NVIDIA GeForce RTX 3090, 24260MiB)

### Minimal Reproducible Example

Call yolo train 

```
COMMON_ARGS = {
    "data": "(...)/datasets/EXPERIMENT",
    "model": "(...)/weights/yolov8x-cls.pt",
    "plots": True,
    "verbose": True,
    "patience": 10,
    "imgsz": 1280,
    "batch": 12,
    "device": '0,1',
    "cache": 'disk'
}
```

```
model = YOLO('(...)/weights/yolov8x-cls.pt')
model.train(**model_args)
```

```
Ultralytics YOLOv8.0.111 🚀 Python-3.11.3 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24260MiB)
                                                            CUDA:1 (NVIDIA GeForce RTX 3090, 24260MiB)
yolo/engine/trainer: task=classify, mode=train, model=(...)/weights/yolov8x-cls.pt, data=(...)/datasets/EXPERIMENT, epochs=100, patience=10, batch=12, imgsz=1280, save=True, save_period=-1, cache=disk, device=0,1, workers=8, project=None, name=/home/jovyan/work/MDD/experiments/public_client_mid, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.5, perspective=0.5, flipud=0.0, fliplr=0.0, mosaic=1.0, mixup=0.5, copy_paste=0.3, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=/home/jovyan/work/MDD/experiments/public
Overriding model.yaml nc=1000 with nc=2

                   from  n    params  module                                       arguments                     
  0                  -1  1      2320  ultralytics.nn.modules.conv.Conv             [3, 80, 3, 2]                 
  1                  -1  1    115520  ultralytics.nn.modules.conv.Conv             [80, 160, 3, 2]               
  2                  -1  3    436800  ultralytics.nn.modules.block.C2f             [160, 160, 3, True]           
  3                  -1  1    461440  ultralytics.nn.modules.conv.Conv             [160, 320, 3, 2]              
  4                  -1  6   3281920  ultralytics.nn.modules.block.C2f             [320, 320, 6, True]           
  5                  -1  1   1844480  ultralytics.nn.modules.conv.Conv             [320, 640, 3, 2]              
  6                  -1  6  13117440  ultralytics.nn.modules.block.C2f             [640, 640, 6, True]           
  7                  -1  1   7375360  ultralytics.nn.modules.conv.Conv             [640, 1280, 3, 2]             
  8                  -1  3  27865600  ultralytics.nn.modules.block.C2f             [1280, 1280, 3, True]         
  9                  -1  1   1643522  ultralytics.nn.modules.head.Classify         [1280, 2]                     
YOLOv8x-cls summary: 183 layers, 56144402 parameters, 56144402 gradients, 154.3 GFLOPs
Transferred 300/302 items from pretrained weights
DDP command: ['/opt/conda/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '37607', '/opt/conda/lib/python3.11/site-packages/ipykernel_launcher.py']
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
```

```

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:81:00.0 Off |                  N/A |
| 49%   27C    P8    20W / 350W |      3MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:C1:00.0 Off |                  N/A |
| 30%   32C    P8    17W / 350W |      3MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@Laughing-q @glenn-jocher  did we make a change in DDP code recently?

**Comment by Laughing-q** [comment]
@AyushExel yeah but I don't think that update would affect something🤔. Also I'm not able to reproduce the issue. @akkolyth 
```bash
yolo classify train epochs=10 model=weights/yolov8n-cls.pt device='0,1' data=mnist160 imgsz=1280 batch=12 verbose plots patience=10 cache=disk
```
![pic-full-230531-1557-56](https://github.com/ultralytics/ultralytics/assets/61612323/5442da52-55bd-4bb7-bea0-75cf4375b08e)

**Comment by kvnptl** [comment]
The same thing working fine for me, without any errors.

**Comment by glenn-jocher** [comment]
@kvnptl thank you for reporting this issue. Based on your description, it seems that it occurs in some cases when using DDP with multiple GPUs. This may be due to various factors such as the network topology, GPU memory usage, or other configuration errors.

Could you provide us with more details about the environment you are using, such as the number and type of GPUs, and your DDP configuration settings? 

Also, please ensure that you have installed the latest version of YOLOv8. If the issue persists, please share additional information such as a full error log and reproduction steps so that we can investigate further.

**Comment by Laughing-q** [comment]
@akkolyth Hi, I think this could be related to the notebook way you are using, but I don't have a multi-gpu machine with gui interface, I'm not able to reproduce the issue since I don't have such a enviroment. I suggest you to use command line to launch the DDP training for now, and that works to me.

**Comment by kvnptl** [comment]
Yes, it works without Jupyter notebook. But, I was also facing issues with jupyter notebook multi-gpu training.

**Comment by glenn-jocher** [comment]
@kvnptl thank you for confirming that the multi-GPU training works without using the Jupyter notebook. We appreciate you bringing up potential issues with multi-GPU training in Jupyter notebooks. 

Running DDP training inside Jupyter notebooks can cause some conflicts due to the notebook server's parallel processing and GPU usage. Thus, we recommend running DDP training outside of Jupyter notebooks, utilizing command-line interfaces. 

If you have any further questions or concerns, feel free to reach out to us.

**Comment by lynxhawk** [comment]
I have the same problem too. It just freeze. I can run in Ultralytics 8.0.20, but when i update to lastest, it didn't work.
```
yolo detect train data=salmon.yaml model=yolov8x.yaml pretrained=yolov8x.pt epochs=300 imgsz=1280 patience=50 device='0,1,2' batch=18 save=True val=True

                   from  n    params  module                                       arguments
  0                  -1  1      2320  ultralytics.nn.modules.conv.Conv             [3, 80, 3, 2]
  1                  -1  1    115520  ultralytics.nn.modules.conv.Conv             [80, 160, 3, 2]
  2                  -1  3    436800  ultralytics.nn.modules.block.C2f             [160, 160, 3, True]
  3                  -1  1    461440  ultralytics.nn.modules.conv.Conv             [160, 320, 3, 2]
  4                  -1  6   3281920  ultralytics.nn.modules.block.C2f             [320, 320, 6, True]
  5                  -1  1   1844480  ultralytics.nn.modules.conv.Conv             [320, 640, 3, 2]
  6                  -1  6  13117440  ultralytics.nn.modules.block.C2f             [640, 640, 6, True]
  7                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]
  8                  -1  3   6969600  ultralytics.nn.modules.block.C2f             [640, 640, 3, True]
  9                  -1  1   1025920  ultralytics.nn.modules.block.SPPF            [640, 640, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  3   7379200  ultralytics.nn.modules.block.C2f             [1280, 640, 3]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  3   1948800  ultralytics.nn.modules.block.C2f             [960, 320, 3]
 16                  -1  1    922240  ultralytics.nn.modules.conv.Conv             [320, 320, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  3   7174400  ultralytics.nn.modules.block.C2f             [960, 640, 3]
 19                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   7379200  ultralytics.nn.modules.block.C2f             [1280, 640, 3]
 22        [15, 18, 21]  1   8795008  ultralytics.nn.modules.head.Detect           [80, [320, 640, 640]]
YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients

Transferred 595/595 items from pretrained weights
Ultralytics YOLOv8.0.116 🚀 Python-3.8.0 torch-2.0.1+cu117 CUDA:0 (NVIDIA A100-PCIE-40GB, 40338MiB)
                                                           CUDA:1 (NVIDIA A100-PCIE-40GB, 40338MiB)
                                                           CUDA:2 (NVIDIA A100-PCIE-40GB, 40338MiB)
yolo/engine/trainer: task=detect, mode=train, model=yolov8x.yaml, data=salmon.yaml, epochs=300, patience=50, batch=18, imgsz=1280, save=True, save_period=-1, cache=False, device=(0, 1, 2), workers=8, project=None, name=None, exist_ok=False, pretrained=yolov8x.pt, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs/detect/train3
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1      2320  ultralytics.nn.modules.conv.Conv             [3, 80, 3, 2]
  1                  -1  1    115520  ultralytics.nn.modules.conv.Conv             [80, 160, 3, 2]
  2                  -1  3    436800  ultralytics.nn.modules.block.C2f             [160, 160, 3, True]
  3                  -1  1    461440  ultralytics.nn.modules.conv.Conv             [160, 320, 3, 2]
  4                  -1  6   3281920  ultralytics.nn.modules.block.C2f             [320, 320, 6, True]
  5                  -1  1   1844480  ultralytics.nn.modules.conv.Conv             [320, 640, 3, 2]
  6                  -1  6  13117440  ultralytics.nn.modules.block.C2f             [640, 640, 6, True]
  7                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]
  8                  -1  3   6969600  ultralytics.nn.modules.block.C2f             [640, 640, 3, True]
  9                  -1  1   1025920  ultralytics.nn.modules.block.SPPF            [640, 640, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  3   7379200  ultralytics.nn.modules.block.C2f             [1280, 640, 3]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  3   1948800  ultralytics.nn.modules.block.C2f             [960, 320, 3]
 16                  -1  1    922240  ultralytics.nn.modules.conv.Conv             [320, 320, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  3   7174400  ultralytics.nn.modules.block.C2f             [960, 640, 3]
 19                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   7379200  ultralytics.nn.modules.block.C2f             [1280, 640, 3]
 22        [15, 18, 21]  1   8718931  ultralytics.nn.modules.head.Detect           [1, [320, 640, 640]]
YOLOv8x summary: 365 layers, 68153571 parameters, 68153555 gradients

Transferred 589/595 items from pretrained weights
DDP command: ['/data6/tx/anaconda3/envs/yolov8/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '3', '--master_port', '34437', '/data6/tx/.config/Ultralytics/DDP/_temp_5_0trqjj140136267932240.py']
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
DDP info: RANK 0, WORLD_SIZE 3, DEVICE cuda:0
Overriding model.yaml nc=80 with nc=1
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning /data6/tx/code/yolov8/ultralytics/datasets/salmon/labels/train.cache... 900 images, 0 backgrounds, 0 corrupt: 100%|██████████| 900/900 [00
val: Scanning /data6/tx/code/yolov8/ultralytics/datasets/salmon/labels/train.cache... 900 images, 0 backgrounds, 0 corrupt: 100%|██████████| 900/900 [00:0
Plotting labels to runs/detect/train3/labels.jpg...
optimizer: AdamW(lr=0.000714, momentum=0.9) with parameter groups 97 weight(decay=0.0), 104 weight(decay=0.0005625000000000001), 103 bias(decay=0.0)
Image sizes 1280 train, 1280 val
Using 18 dataloader workers
Logging results to runs/detect/train3
Starting training for 300 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/300      18.1G      4.295      3.804      4.178         82       1280:   2%|▏         | 1/50 [00:01<01:29,  1.82s/it]```

**Comment by spikyknox** [comment]
It look like I have the exact same problem with yolo detect train with multiple GPU. Here's my GPU setup.
![image](https://github.com/ultralytics/ultralytics/assets/24282214/3889d73c-e04c-4010-9751-a03b4af5215e)

**Comment by mcusgithub** [comment]
Same problem as reported by [lynxhawk](https://github.com/lynxhawk) and [spikyknox](https://github.com/spikyknox) **without** a jupyter notebook on 4 GPUs.  YoloV5 works fine.

**Comment by glenn-jocher** [comment]
@mcusgithub hello,

Thank you for bringing this issue to our attention. We understand that you are facing the same problem as other users when training YOLOv8 on multiple GPUs.

Based on the information you have provided, it seems that YOLOv8 freezes during the training process. It is important to note that YOLOv8 and YOLOv5 are separate repositories, and we are focused on addressing issues specific to YOLOv8.

From your description, it appears that communication between the GPUs is functioning correctly, as there is no NCCL error in the logs and the init_process_group has been successful for all world ranks.

To further investigate this issue, it would be helpful if you could provide more details such as the error logs or any additional information that may aid in diagnosing the problem. Additionally, please ensure that you are using the latest version of YOLOv8.

We are here to assist you, and we appreciate your patience as we work towards resolving this issue.

**Comment by ctycode** [comment]
I had the same problem no matter what way I used (jupyter||code)
It just runs to the following output and gets stuck without any response,I use two GPUs for training
`AMP: checks passed ✅`

**Comment by glenn-jocher** [comment]
@ctycode hello,

Thank you for reaching out and sharing the details of your issue. It seems that you are experiencing a similar problem as other users when training YOLOv8 on multiple GPUs.

Based on the information provided, the training process starts successfully but then gets stuck without any response after printing the AMP checks. The code you shared indicates that you are using two GPUs for training and that AMP is enabled.

To further investigate this issue, we would need more information such as the error logs or additional details that may help us diagnose the problem. Please ensure that you are using the latest version of YOLOv8 and that your environment is properly configured.

We apologize for any inconvenience this may have caused and are committed to resolving this issue. Thank you for your patience and understanding.

**Comment by dbparkJ** [comment]
@ctycode 
Hello, Ctycode
I'm having the same problem as you, have you solved this problem by any chance?
Then can you tell me the solution, too?
FYI I have an A40 GPU.

**Comment by glenn-jocher** [comment]
Hello @dbparkJ,

Thank you for sharing your issue with our community. It seems like you're experiencing a similar stopping issue that some users have experienced when training YOLOv8 on multiple GPUs, where the training process seems to hang after the AMP checks. 

While I don't have an immediate resolution for you at this moment, our team is diligently working on this matter to identify the root cause and devise a suitable solution. Your patience is appreciated in this regard.

In the meantime, do make sure you're using the most recent version of YOLOv8 and that your setup is correctly configured. 

Please do share any progress or findings of your own, as it may help us resolve this matter more efficiently. Thank you again for bringing this to our attention. Your contribution is much appreciated!

**Comment by manicmojo** [comment]
Hi, I have this same issue. 
Oddly though, I ran my training once, then stopped it as I wanted to change the batch size. When I started again (on either batch size) it froze after AMP: Checks passed. Now I cant get it to work. 

`yolo detect train data=/home/podqc/ultralytics/ultralytics/yolo/data/data.yaml model=/home/podqc/ultralytics/yolov8n.pt epochs=100 imgsz=3840 device=0 name=QC8.Y8nH3840R batch=6 dynamic=true amp=false
Ultralytics YOLOv8.1.42 🚀 Python-3.8.10 torch-2.0.0+nv23.05 CUDA:0 (Orin, 62795MiB)
engine/trainer: task=detect, mode=train, model=/home/podqc/ultralytics/yolov8n.pt, data=/home/podqc/ultralytics/ultralytics/yolo/data/data.yaml, epochs=100, time=None, patience=100, batch=6, imgsz=3840, save=True, save_period=-1, cache=False, device=0, workers=8, project=None, name=QC8.Y8nH3840R5, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=False, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=True, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=/home/podqc/ultralytics/runs/detect/QC8.Y8nH3840R5
Overriding model.yaml nc=80 with nc=33
`
I am running on NVIDIA JETSON ORIN, so multi-GPU.
Reading other posts, I have tried disabling AMP checks, but no luck.
I have also tried:
`import os
os.environ['NCCL_P2P_DISABLE'] = '1'`
But this didnt help either. 

I have just (after this error) updated to YOLO 8.1 (from 8), but this also changes nothing. 

Please help. Ill respond with anything you need. Thankyou

**Comment by dbparkJ** [comment]
@manicmojo I think your imgsz is to high

**Comment by manicmojo** [comment]
> @manicmojo I think your imgsz is to high

It's the test im doing at the moment, been incrementally moving up to full 4k. Has been doing great until now!

I've passed this issue now. 
The first time I ran it nano 4k, CLI passed AMP checks quickly. All the following times it seem to freeze as said before. 
I noticed that it was still processing CPU 100% on one core, then another, not the full 12 as normally during the process.
So given enough time it passed this stage, returning to 12 cores and continuing the training. 

Later the process was killed, likely the imgsz, but no reason given. This is why I'm testing though!

**Comment by yoonj1n** [comment]
hi, I have same error now.
does any solution here?

**Comment by glenn-jocher** [comment]
Hello! It seems like you're encountering stalls after the AMP checks when training with YOLOv8. This could be due to multiple reasons, including system resource limitations or issues with model configuration.

A couple of quick checks you might want to perform:
- Ensure that your system meets the hardware requirements for the size of the model and dataset you are using.
- Try reducing the image size (`imgsz`) and batch size to lower memory and processing requirements.

For example:
```bash
yolo detect train data=your_dataset.yaml model=yolov8n-cls.pt imgsz=640 batch=8
```

Make sure your CUDA and PyTorch installations are up to date as well. If you still face issues, sharing more details about your setup might help pinpoint the problem. Keep up the great work, and I hope this helps! 😊

**Comment by manicmojo** [comment]
> hi, I have same error now. when I try to train model(yolov8n-cls), it stuck after print "APP checks passed" does any solution here?

As for me nothing had changed, it ran first quickly, but seemed to freeze on later attempts, I left it alone for a long time, and it continued. 

I could see that the CPU was being utilised on one CPU core rather than the full 16 cores. So this is why it seemed to have froze.

 So, easy solution, give it time.

**Comment by glenn-jocher** [comment]
Hello! It sounds like you're experiencing a delay rather than a complete freeze during the training process. This can sometimes happen, especially with intensive computations or large models. Your observation about CPU utilization is insightful! It seems the process is still active but not fully utilizing all available cores.

If the training eventually continues after this apparent stall, it might indeed be a matter of giving it some time as you suggested. However, if you consistently find this delay to be too disruptive, you might consider adjusting the `num_workers` in your training configuration to better utilize your CPU resources:

```python
model.train(num_workers=8, ...)  # Adjust the number of workers as needed
```

This adjustment could help distribute the load more evenly across your CPU cores. Keep an eye on the system's performance, and thanks for sharing your solution! 😊

**Comment by fosteman** [comment]
CAN reproduce this specifically on **Nvidia A40**, Something due to the chip. 
Ultralytics 8.3.75 🚀 Python-3.10.12 torch-2.1.0+cu118 CUDA:1 (NVIDIA A40, 45515MiB)

Would just hang at AMP checks, not entering into file caching.

**Comment by glenn-jocher** [comment]
Thank you for reporting this issue with A40 GPUs. We'll investigate AMP compatibility for this architecture. For immediate resolution, you can try: 

1. Temporarily disable AMP with `amp=False` in your training command
2. Run a standalone AMP check using the script from our [checks documentation](https://docs.ultralytics.com/reference/utils/checks/#ultralytics.utils.checks.check_amp):

```python
from ultralytics import YOLO
from ultralytics.utils.checks import check_amp

model = YOLO("yolov8n.pt").model.cuda()
print("AMP works:" if check_amp(model) else "AMP disabled")
```

Please share your findings in a new GitHub issue if the problem persists.
