### ISSUE TITLE
Yolov8 with key points detection without object detection

### ISSUE THREAD

**Issue by halqadasi** [ultralytics/ultralytics#2929]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a project where the object is annotated with key points without any bounding boxes. Can I train Yolov8 with key points detection without object detection (bounding boxes)?

If the answer is yes, how the annotation file should look like, please give me an example.

**Comment by glenn-jocher** [comment]
@halqadasi thank you for your message and inquiry.

While YOLOv8 is primarily designed and optimized for object detection bounding boxes rather than key point detection, it is possible to modify the model to also detect keypoints. However, this requires a change to the model, training data, and evaluation metrics.
 
Regarding the annotation file, each line should represent a single image, beginning with the path of the image and followed by the keypoints coordinates. Please make sure that the format of the annotation file matches the input format required by YOLOv8.

We understand that the process can be complex, so we suggest consulting with experts in the field and related literature to ensure optimal results.

Please let us know if you have any further questions or concerns. We appreciate your interest in YOLOv8.

**Comment by Laughing-q** [comment]
@halqadasi hi, currently we train keypoint model only with the bounding boxes. I suppose the answer is no. :)

**Comment by bassam1993-c** [comment]
hello guys I have a problem I use the yolo8v for postestimation and I got the result with the 17 point but I can get to know with result for each point I mean I have 17 result pose and I have 17 point but I can't know witch result is for each point

**Comment by glenn-jocher** [comment]
@bassam1993-c hi there,

Thanks for reaching out with your usage question for YOLOv8 in pose estimation.

The issue you're facing seems to be related to a common challenge in pose estimation problems - identifying which detected keypoints relate to which parts of the body when using the standard 17 joints defined in many pose estimation models.

When YOLOv8 gives you results, it's returning an array of keypoints, probably in the order they were detected. However, without additional context or processing, it can be tough to know which keypoint corresponds to which joint.

A usual standard in pose estimation is to follow a predictable order when defining and detecting keypoints. For example, you might always list the keypoints in an order like: right ankle, right knee, right hip, left hip, left knee, left ankle, right wrist, right elbow, right shoulder, left shoulder, left elbow, left wrist, neck, head top, nose, left eye, and right eye. 

Please, check your model’s documentation to verify if it follows a standard order when listing keypoints. Also, it would be important to validate your labeling and processing pipeline to ensure the keypoints are being listed in the correct order.

Hope this information helps solving your issue. Let us know if you have any further questions!

**Comment by bassam1993-c** [comment]
> @bassam1993-c hi there,
> 
> Thanks for reaching out with your usage question for YOLOv8 in pose estimation.
> 
> The issue you're facing seems to be related to a common challenge in pose estimation problems - identifying which detected keypoints relate to which parts of the body when using the standard 17 joints defined in many pose estimation models.
> 
> When YOLOv8 gives you results, it's returning an array of keypoints, probably in the order they were detected. However, without additional context or processing, it can be tough to know which keypoint corresponds to which joint.
> 
> A usual standard in pose estimation is to follow a predictable order when defining and detecting keypoints. For example, you might always list the keypoints in an order like: right ankle, right knee, right hip, left hip, left knee, left ankle, right wrist, right elbow, right shoulder, left shoulder, left elbow, left wrist, neck, head top, nose, left eye, and right eye.
> 
> Please, check your model’s documentation to verify if it follows a standard order when listing keypoints. Also, it would be important to validate your labeling and processing pipeline to ensure the keypoints are being listed in the correct order.
> 
> Hope this information helps solving your issue. Let us know if you have any further questions!

thank you so much I will try to make a list of the 17 Keypoint and let you know

**Comment by glenn-jocher** [comment]
@bassam1993-c, you're welcome! Yes, creating a designated list for the keypoints might be the most feasible solution for the issue. Make sure to maintain the order in which the keypoints are trained in the model. This should allow you to understand and link each pose estimation result to its respective keypoint. 

Feel free to keep us updated on your progress. If you need further help or have any other questions, don't hesitate to reach out again! Remember, the YOLOv8 community is here to support you. Best of luck with your pose estimation project!

**Comment by chathurawimalasiri** [comment]
@glenn-jocher  Hello, I am planning to use YOLOv8 for keypoint detection in teeth, but there is a challenge. There are two types of teeth: single root and double root. We need to detect 5 keypoints in a single root and 6 keypoints in a double root. This means the number of detection points depends on the type of the object. We will be using dental X-rays as the input for the model, which consist of both single and double root teeth. Can YOLOv8 be effectively applied to address this problem?

**Comment by glenn-jocher** [comment]
@chathurawimalasiri Hi there! YOLOv8 can indeed be used for keypoint detection, and your use case with dental X-rays sounds quite interesting. While YOLOv8 typically expects a fixed number of keypoints, you could potentially approach this by training two separate models, one for single root (5 keypoints) and another for double root teeth (6 keypoints). Alternatively, you could train a single model with 6 keypoints, where the 6th keypoint for single root teeth could be a 'dummy' point that the model learns to ignore or place in a standard 'null' position.

Here's a rough idea of how your annotation might look for a single root tooth with a dummy 6th keypoint:

```
# x1,y1,...,x5,y5 are your real keypoints, x6,y6 is the dummy keypoint
path/to/image.jpg x1,y1,x2,y2,x3,y3,x4,y4,x5,y5,x6,y6
```

And for a double root tooth with all real keypoints:

```
path/to/image.jpg x1,y1,x2,y2,x3,y3,x4,y4,x5,y5,x6,y6
```

This way, your model always predicts 6 keypoints, but you interpret them according to the tooth type. Hope this helps, and best of luck with your project! 😄🦷

**Comment by Amiiney** [comment]
Hi @glenn-jocher, I would like to follow up on the order of detection of the keypoints, how can I follow a predictable order when defining and detecting keypoints? My ground truth is always in the same order and the list I pass to the yolov8 config is also in the same order, however the predictions are not, is there a way to post-process the predictions or to get the keypoint id for each keypoint?

Thank you,

**Comment by KingAsperin** [comment]
may i ask if making a custom dataset for keypoints detection is required to add a bounding box that enclosed all the keypoints when annotating?

**Comment by glenn-jocher** [comment]
@KingAsperin hi there! For keypoint detection in YOLOv8, it's not strictly necessary to include a bounding box that encloses all keypoints during annotation. YOLOv8 can be trained to detect keypoints directly. However, if your dataset includes bounding boxes, they can be helpful during training for better localization, but they're not a requirement for keypoint-only tasks. Happy annotating! 😊📊

**Comment by hariouat** [comment]
> @KingAsperin hi there! For keypoint detection in YOLOv8, it's not strictly necessary to include a bounding box that encloses all keypoints during annotation. YOLOv8 can be trained to detect keypoints directly. However, if your dataset includes bounding boxes, they can be helpful during training for better localization, but they're not a requirement for keypoint-only tasks. Happy annotating! 😊📊

IS there any paper about keypoint detection with yolov8?

**Comment by zyf-xtu** [comment]
> @KingAsperin大家好！对于 YOLOv8 中的关键点检测，在注释期间不一定非要包含一个包围所有关键点的边界框。YOLOv8 可以训练为直接检测关键点。但是，如果您的数据集包含边界框，它们在训练过程中有助于更好地定位，但它们不是仅关键点任务的必需品。祝您注释愉快！😊📊



> @KingAsperin hi there! For keypoint detection in YOLOv8, it's not strictly necessary to include a bounding box that encloses all keypoints during annotation. YOLOv8 can be trained to detect keypoints directly. However, if your dataset includes bounding boxes, they can be helpful during training for better localization, but they're not a requirement for keypoint-only tasks. Happy annotating! 😊📊
YOLOv8 can be trained to detect keypoints directly，What should I do if I only have keypoints without bounding boxes, and if I have bounding boxes, there is overlap, and keypoints are contained in multiple bounding boxes。

**Comment by zyf-xtu** [comment]
> @KingAsperin hi there! For keypoint detection in YOLOv8, it's not strictly necessary to include a bounding box that encloses all keypoints during annotation. YOLOv8 can be trained to detect keypoints directly. However, if your dataset includes bounding boxes, they can be helpful during training for better localization, but they're not a requirement for keypoint-only tasks. Happy annotating! 😊📊

YOLOv8 can be trained to detect keypoints directly，What should I do if I only have keypoints without bounding boxes, and if I have bounding boxes, there is overlap, and keypoints are contained in multiple bounding boxes。
