### ISSUE TITLE
Specify Comet project name through environment variable

### ISSUE THREAD

**Issue by lukasugar** [ultralytics/ultralytics#2932]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Support setting Comet project that's different from the YOLO's `project` value. This was possible in YOLOv5.

### Use case

`project` value is used both to describe the project with its name and to define the output path.

It's a valid case that someone doesn't want to have the project path as the name of the project inside Comet.

It seems that in YOLOv5 it was possible to set the project name ([link](https://docs.ultralytics.com/yolov5/tutorials/comet_logging_integration/?h=comet))
```
export COMET_API_KEY=<Your Comet API Key>
export COMET_PROJECT_NAME=<Your Comet Project Name> # This will default to 'yolov5'
```

As COMET_API_KEY is specified through environment variables, it makes most sense to support the COMET_PROJECT_NAME through them as well.

### Additional

I propose that this is fixed to support the logic from YOLOv5. E.g.:

Inside `comet.py` we could slightly modify the `_create_experiment` method:
```
def _create_experiment(args):
    """Ensures that the experiment object is only created in a single process during distributed training."""
    if RANK not in (-1, 0):
        return
    try:
        comet_mode = _get_comet_mode()
        
        # Existing implementation:
        # experiment = _get_experiment_type(comet_mode, args.project)

        # New implementation:
        _project_name = os.environ.get('COMET_PROJECT_NAME', args.project)
        experiment = _get_experiment_type(comet_mode, args.project)

        # The rest stays the same


```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by dsblank** [comment]
@lukasugar just one fix:

```python
        _project_name = os.environ.get('COMET_PROJECT_NAME', args.project)
        experiment = _get_experiment_type(comet_mode, _project_name)
```

But, yes this is the correct approach.

**Comment by lukasugar** [comment]
@dsblank yeah, that's an obvious error 😅 I've submitted the PR: https://github.com/ultralytics/ultralytics/pull/3013

**Comment by DN6** [comment]
Hi @lukasugar. Setting the project name via an environment variable works right out of the box with the current integration and without any changes to the current code. For example: 

```
import os

from ultralytics import YOLO

os.environ["COMET_PROJECT_NAME"] = "my-comet-env-project-name"

# Load a model
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

# train the model
results = model.train(
    data="coco128.yaml",
    batch=16,
    optimizer="AdamW",
    save_period=1,
    save_json=True,
    epochs=5,
)
```

Alternatively, if you export the project name environment variable and then run the script, you will log to the specified project. 

```
export COMET_PROJECT_NAME=my-project-name
```

```
python my_yolo_script.py
```

**Comment by lukasugar** [comment]
@dsblank I get different behavior than what you describe. I set environment variables both 'COMET_PROJECT_NAME' and 'COMET_API_KEY'. Since 'COMET_API_KEY' is successfully read, I'm sure that environment is properly configured.

In my case, I explicitly set model `name` and `project` in  `.train()`. The comet experiment name is set to `project` value.

**Comment by DN6** [comment]
Correct. Setting the project name via the `train` method will overwrite the one specified in the environment variable. If you remove the `project` argument from the `train` method, the Comet project will be set to the environment variable value.

**Comment by lukasugar** [comment]
I find that behavior problematic, as`project` is used both as the project name and the path/working dir/output dir of the training process.
Hope you find my arguments valid and approve the PR :)

**Comment by glenn-jocher** [comment]
@dsblank thank you for your feedback on YOLOv8's `train` method and default `project` value. The `project` parameter in the `train` method will override any environment variable values for the Comet project. We understand that this could cause confusion and appreciate your insight into the issue.

Your proposed changes have been submitted and will be reviewed by the Ultralytics team. We thank you for your valuable input and contributions to the YOLO community!

**Comment by DN6** [comment]
@lukasugar I see what you mean. In that case, your change makes sense. 

@glenn-jocher I wanted to make a small change to the Comet integration as well. I can create a new PR and include @lukasugar's changes in it as well if that's okay? That way you won't have to review two PRs.

**Comment by glenn-jocher** [comment]
Thank you for your interest in contributing to YOLOv8, @DN6. We appreciate your willingness to improve the Comet integration, and we believe it would be helpful to merge your changes along with the ones proposed by @lukasugar. Feel free to create a new PR including both sets of changes. We look forward to reviewing your contribution and thank you for your time and effort!

**Comment by lukasugar** [comment]
Resolved by @DN6, closing :)

**Comment by glenn-jocher** [comment]
Thank you, @lukasugar, for your contribution and for resolving this issue! Your changes have been reviewed and approved. We appreciate your efforts in improving the Comet integration in YOLOv8. Keep up the great work! The issue will be closed now. However, please don't hesitate to reach out if you have any further questions or if there are any other issues or feature requests you would like to address in the future. Your contributions are valuable to the YOLOv8 community.
