### ISSUE TITLE
Recognizing unknown class

### ISSUE THREAD

**Issue by RedPaladin** [ultralytics/ultralytics#2934]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

**Context**

I have used a pre-train model and fine-tuned it with my own dataset. 
My dataset are cans with different brands. I have created one class per brand of can.

The image I use for prediction are cans that the model is trained for and other brand that are unknown for the model.

I was expecting to get a "low" confidence for the unknown brand but YOLOv8 always returns me high confidence score (between 0.95 - 0.99) with a random class that it knows.

**Problem**

How can I do to "recognize" that it's a brand that the model it is not trained for ? My problem is I cannot create a separate class that contains all the unknown ones as I don't know in advance the brand I want to recognize.

I read some articles on Internet about this problem but it seems to be related to Out-of-Distribution Detection (OOD) but I don't have enough knowledge in deep-learning to understand such complexity.

**Comment by glenn-jocher** [comment]
@RedPaladin hello, 

It sounds like you're running into a common issue known as the Open Set Recognition problem, which is the ability of a model to recognize known classes while alerting the system or user when a new, previously unseen class is observed. Unfortunately, YOLOv8 doesn't currently have an OOD detection feature, but it does sound like the OOD problem is what you're encountering. 

While we recommend using an OOD detection approach, such as an anomaly detection algorithm (which could be combined with your trained model), as a workaround for your specific case, you could try creating an `unknown` class that encapsulates all the objects not recognized by your pre-trained YOLOv8 model. Such objects would receive a low confidence score, making it easier for you to distinguish them from the known classes. 

I hope that helps! Let us know if you have any further questions or concerns.

**Comment by Taimoor505** [comment]
@RedPaladin did you find a solution for this?
