### ISSUE TITLE
numbers in confusion matrix

### ISSUE THREAD

**Issue by bobyfisch** [ultralytics/ultralytics#2935]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Since last I updated the package the numbers that used to appear in the confusion matrix plot have disappeared: 

Before:
![image](https://github.com/ultralytics/ultralytics/assets/84570376/be1f417d-a202-42dc-b2f0-66b39b3a6970)
After:
![image](https://github.com/ultralytics/ultralytics/assets/84570376/116b63e9-0583-4888-90b5-b5b01468de32)

I found these numbers very useful and i can't find a way to reactivate them, could this be built into some argument for the train and val functions? Or is there another way to display them that I am missing?

Thanks!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by bobyfisch** [comment]
This was actually quite simple, it wasn't due to an update but to the fact that I had surpassed 30 class names.

I forked and edited the annot option https://github.com/ultralytics/ultralytics/blob/fd94d312da626f9557e43adb7b339afa459e497f/ultralytics/yolo/utils/metrics.py#LL327C34-L327C34 to `annot=nc < 30,` --> numbers are overlapping a little on graph but working fine. 

Not submitting pull request because I suppose this isn't useful for most people, and this does create a very small overlap between numbers in the confusion amtrix

**Comment by glenn-jocher** [comment]
@bobyfisch thank you for reaching out and sharing your experience with the confusion matrix. We're glad to hear that you were able to resolve the issue on your own. As you mentioned, when the number of class names in the confusion matrix exceeds 30, the numbers will overlap a little bit on the graph, but it doesn't affect the performance. Therefore, we haven't built this feature into the training or validation functions yet as it may not be useful for most users. However, we appreciate your feedback and we will keep this in mind for future updates. Let us know if you have any other questions or concerns.
