### ISSUE TITLE
Pixel wise probability

### ISSUE THREAD

**Issue by Dharmendra04** [ultralytics/ultralytics#2936]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there any way to identify the pixel wise probability of each class to create a probability map

**Comment by glenn-jocher** [comment]
Hello @Dharmendra04, thank you for your question! Yes, it is possible to identify the pixel-wise probability of each class using YOLOv8, and create a probability map. This can be achieved by parsing the output tensor of the model and extracting the corresponding class probabilities for each pixel position. These probabilities can then be visualized as a probability map using techniques such as heat-mapping or overlaying color-coded boxes on the input image.

Please note that this functionality is not included in the standard YOLOv8 implementation and may require custom code to extract and visualize the pixel-wise probabilities. Additionally, keep in mind that this may increase inference time and resource usage, depending on the size of the input images and number of classes to be detected. 

Let us know if you have any further questions or if there's any other way we can help!
