### ISSUE TITLE
YOLOv8 training in DDP mode using python interface on Amazon SageMaker

### ISSUE THREAD

**Issue by lukasugar** [ultralytics/ultralytics#2939]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to run YOLOv8 training in DDP mode using python interface on Amazon SageMaker? Has anyone managed to get this work?

### Additional

I'm trying to run YOLOv8 training in DDP mode, using python interface, on Amazon SageMaker.

My code so far is like this, and I get the error: ` Default process group has not been initialized, please make sure to call init_process_group`. Can someone share how these should be changed?

```
# train.py

model = YOLO(model_name)

model.train(
          data=yaml_path,
          epochs=max_epochs,
          batch=batch_size,
          imgsz=imgsz,
          project = working_dir,
          name = name, 
          # device=device,
      )

# Sagemaker script

    estimator = PyTorch(entry_point='train.py',
                    source_dir='./src/',
                    checkpoint_s3_uri=f's3://{bucket_name}/object_detection/training/sample/{job_name}/',
                    checkpoint_local_path=CHECKPOINT_LOCAL_PATH,
                    role=role,
                    image_uri = '763104351884.dkr.ecr.us-east-2.amazonaws.com/pytorch-training:2.0.0-gpu-py310-cu118-ubuntu20.04-sagemaker',
                    instance_count=2, #
                    instance_type='ml.g4dn.xlarge',
                    hyperparameters={
                        'model_name': model_name,
                        # 'max_epochs': 40,
                        'max_epochs': 2,
                        "batch_size": 16,
                        "imgsz": 640,
                        'working_dir': CHECKPOINT_LOCAL_PATH,
                        'name': job_name, # Needed for comet
                    },
                    distribution={"pytorchddp": {"enabled": True}} ,
    )


    res = estimator.fit(
    inputs={
        'dataset_path': 'SOME_PATH'  },
    job_name=job_name,
    )
```

**Comment by glenn-jocher** [comment]
@lukasugar hello! To run YOLOv8 training in DDP mode using the python interface on Amazon SageMaker, you would need to initialize the process group before calling the `train()` method. In your code, the error message suggests that the process group has not been initialized, so you would need to add the following code snippet before calling `model.train()`:

```
import torch.distributed as dist

dist.init_process_group(backend='nccl', 
                        init_method='env://', 
                        world_size=<number-of-processes>, 
                        rank=<process-rank>)
```

Here, `backend` should be set to `'nccl'`, which is the recommended backend for training on GPUs. `init_method` should be set to `'env://'`, which initializes the process group based on the environment variable `MASTER_ADDR` and `MASTER_PORT`. `world_size` should be set to the total number of processes you want to use for training, and `rank` should be set to the rank of the current process.

You would also need to make sure that your script is launched with the appropriate parameters for distributed training. For example, to launch two processes on a single machine, you would need to run:

```
python -m torch.distributed.launch --nproc_per_node=2 train.py
```

This will launch two processes and set the appropriate environment variables for distributed training.

I hope this helps! Let us know if you have any further questions!

**Comment by xzy0223** [comment]
> @lukasugar hello! To run YOLOv8 training in DDP mode using the python interface on Amazon SageMaker, you would need to initialize the process group before calling the `train()` method. In your code, the error message suggests that the process group has not been initialized, so you would need to add the following code snippet before calling `model.train()`:
> 
> ```
> import torch.distributed as dist
> 
> dist.init_process_group(backend='nccl', 
>                         init_method='env://', 
>                         world_size=<number-of-processes>, 
>                         rank=<process-rank>)
> ```
> 
> Here, `backend` should be set to `'nccl'`, which is the recommended backend for training on GPUs. `init_method` should be set to `'env://'`, which initializes the process group based on the environment variable `MASTER_ADDR` and `MASTER_PORT`. `world_size` should be set to the total number of processes you want to use for training, and `rank` should be set to the rank of the current process.
> 
> You would also need to make sure that your script is launched with the appropriate parameters for distributed training. For example, to launch two processes on a single machine, you would need to run:
> 
> ```
> python -m torch.distributed.launch --nproc_per_node=2 train.py
> ```
> 
> This will launch two processes and set the appropriate environment variables for distributed training.
> 
> I hope this helps! Let us know if you have any further questions!

@glenn-jocher hi, I have question related to this response. how can I specify the <process-rank> in the func dist.init_process_group() ?

**Comment by glenn-jocher** [comment]
@<user>, thanks for your question! The `rank` argument in `dist.init_process_group()` specifies the rank of the current process, which should be unique for each process involved in distributed training. Each process should have a unique rank between 0 and `world_size-1`. So, if you are using multiple instances for training, you would specify a `rank` value based on the number of processes on each instance. For example, if you have two instances with two processes on each, you would set the `rank` for the first process on the first instance to 0, the second to 1, the first process on the second instance to 2, and the second to 3. The `rank` argument should be specified accordingly in each instance. 

I hope this helps! Let us know if you have any further questions!

**Comment by xzy0223** [comment]
> 

@glenn-jocher hi, I have a new question. when I try yolov8 DDP training on sagemaker with the following sagemaker script:
`
hyperparameters = {'data': '/opt/ml/input/data/cfg/LogoDet-3K.yaml', 
                   'weight': 'yolov8s.pt', 
                   'project': '/opt/ml/model/',
                   'name': 'fw-logo-detection', 'imgsz': 640, 'batch': 16, 'epochs': 1, 'device': '0,1,2,3', 'workers':1}  

estimator = PyTorch(entry_point='train.py',
                            source_dir='./code/',
                            role=role,
                            hyperparameters=hyperparameters,
                            framework_version='1.13.1',
                            py_version='py39',
                            script_mode=True,
                            instance_count=1, 
                            metric_definitions=metric_definitions,
                            instance_type=instance_type,
                            distribution={
                                "torch_distributed": {
                                    "enabled": True
                                }
                            }
            )`

and the following training script without dist.init_process_group():
`def main(opt):
    # Load a model
    model = YOLO(opt.weights)  # load a pretrained model (recommended for training)

    # Use the model
    model.train(data=opt.data, epochs=opt.epochs, batch=opt.batch, imgsz=opt.imgsz, project=opt.project, name=opt.name, workers=opt.workers, device=opt.device)  # train the model


if __name__ == '__main__':
    
    print(os.listdir('/opt/ml/input/data/'))
    opt = parse_opt()
    main(opt)`

It seems to work, is this usage right?

**Comment by glenn-jocher** [comment]
@lukasugar hello! Thank you for your interest in YOLOv8. Indeed, the method you're using seems to be correct. You're employing Amazon SageMaker's distribution strategy, specifically enabled for PyTorch (`torch_distributed`), which should handle initializing the process group for distributed data parallel (DDP) training. This allows you to employ DDP without explicitly calling `dist.init_process_group()` in your training script. Your approach should generally work when training in a multi-GPU environment.

However, please note that the actual parallel execution and the resulting model performance might vary depending on the specifics of your setup, including the number of instances/GPUs used, the data distribution and sharding strategy among the multiple GPUs, and the specifics of how the model is parallelized in `YOLO` function.

As always, consider monitoring your training closely to ensure that the model is training as expected and that the GPUs are being utilized effectively.
