### ISSUE TITLE
Model exported in "edgetpu" format do not perform inferences

### ISSUE THREAD

**Issue by JordaoCassiano** [ultralytics/ultralytics#2942]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I have encountered a bug while using YOLOV8 predict and exporting the model to the Edge TPU format. After the export, the model is not generating detections correctly. Instead, for each processed frame, the output returns "no detections". The export process goes smoothly, but the model is unable to make inferences. The same version of the model in .pt format is capable of doing so.

### Environment

Python 3.9 

### Minimal Reproducible Example
model = YOLO("yolov5su.pt", )
model.export(format='edgeimpulse')
model.predict(yolov5su.edgetpu.tflite (..))

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by koush** [comment]
I can confirm this issue as well running the conversion and prediction from the docs:

```python
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')  # load an official model
# Export the model
model.export(format='edgetpu')
```


```
yolo predict task=detect model=yolov8n_saved_model/yolov8n_full_integer_quant_edgetpu.tflite imgsz=640

image 1/2 /.venv/lib/python3.9/site-packages/ultralytics/assets/bus.jpg: 640x640 (no detections), 57.0ms
image 2/2 /.venv/lib/python3.9/site-packages/ultralytics/assets/zidane.jpg: 640x640 (no detections), 50.6ms
Speed: 1.9ms preprocess, 53.8ms inference, 0.4ms postprocess per image at shape (1, 3, 640, 640)
```

**Comment by shashichilappagari** [comment]
@koush @JordaoCassiano 
Our team at DeGirum has successfully quantized and ported Ultralytics object detection models to Edge TPU. Specifically: YOLOv5nu, YOLOV5su, YOLOv8n, and YOLOv8s, with SiLU or ReLU6 activation functions. Each of these has been trained for a full COCO object detection task, as well as specialized models for face, hand, car, and license plate detection!

We are making these models available on our cloud platform at: https://degirum.com/#sign-up  

On the platform, you can try each model on: OpenVINO CPU (float), TFLite CPU (float), and TFLite EdgeTPU (quant), for a total of 120 possible combinations!

Once signed up, you can run the models in the browser or in this Google colab notebook: https://colab.research.google.com/github/DeGirum/PySDKExamples/blob/main/UltralyticsObjectDetectionImage.ipynb 

 For any questions or support, please open an issue on: https://github.com/DeGirum/PySDKExamples

If anyone’s interested, we will be doing a live demonstration of using these new models at: https://www.linkedin.com/events/theartofyolo-part1-unleashingth7092593180545540096/

**Comment by glenn-jocher** [comment]
Hello @shashichilappagari and @JordaoCassiano,

We are thrilled to let you know that our team at DeGirum has been successful in quantizing and porting various Ultralytics object detection models to the Edge TPU. This includes models such as YOLOv5nu, YOLOV5su, YOLOv8n, and YOLOv8s, with both SiLU or ReLU6 activation functions. We've trained these models for full COCO object detection tasks as well as specific models for detection of faces, hands, cars, and license plates.

We're offering access to these models on our cloud platform, DeGirum. Here, you can experiment with each model using OpenVINO CPU (float), TFLite CPU (float), and TFLite EdgeTPU (quant). That's a total of 120 possible combinations for you to explore!

Once signed up on our platform, you can run these models in the browser or in a provided Google colab notebook. For any questions or support, we recommend opening an issue on our PySDKExamples repository.

Additionally, we'll be giving a live demonstration of the use of these models. Stay tuned for more information on this soon. 

We hope this helps you, and we're excited to see what you can achieve using these models!

**Comment by Alan01252** [comment]
@shashichilappagari have you had any experience running your models on the coral USB accelerator?

**Comment by shashichilappagari** [comment]
@Alan01252 We did not run them coral USB accelerator but used the Coral M.2 Edge TPU (PCIe version). However, we are reasonably confident that if the USB accelerator is installed properly, our models and code work on the USB device too.

**Comment by glenn-jocher** [comment]
Hello @Alan01252, thank you for reaching out. We've primarily tested our models on the Coral M.2 Edge TPU (PCIe version). However, the underlying hardware technology is very similar to that of the Coral USB Accelerator. So, if the Coral USB Accelerator is correctly installed and set up in your environment, in all likelihood, our models and accompanying code should operate correctly on it as well. This is based on our understanding of the compatibility of these devices. Please feel free to let us know if you encounter any specific issues during your setup or testing.

**Comment by koush** [comment]
@shashichilappagari you mentioned that you have the edgetpu export skip the post process step? What command are you using to export?

**Comment by shashichilappagari** [comment]
@koush We maintain our own fork of the Ultralytics repo: https://github.com/DeGirum/ultralytics_degirum
In this repo, we made some changes to export function to make it more suitable for quantization and porting to different hardware such as Edge TPU.

**Comment by glenn-jocher** [comment]
Hello @shashichilappagari, 

We have a custom fork of the Ultralytics repository, wherein we've made some modifications to the export function, aligning it more towards quantization and hardware porting requirements, including Edge TPU. The modifications allow us to bypass the post-processing step during the model export, and we utilize this adjusted output for our deployment needs.

Please note that even slight changes to the model or the export process can significantly affect the ability of the model to be successfully deployed or even quantized. These changes were made to fit our requirements and may not suit all use-case scenarios.

If you have any questions, or if you need further clarification, feel free to ask.

**Comment by Alan01252** [comment]
Awesome thanks guys. I've actualy had some good results on the USB Coral TPU now with the export functionality from Yocto.

One of the biggest pain points I had was that at the standard imgsz size of 640 the model would not load on to the device ( something about transfer limits ) but at smaller imgsz sizes it works perfectly. 

Also, it didn't seem  to matter too much about the model size in terms of megabytes on disk ( as long as it fits in the coral ram ) for example a larger size model (small over nano) results in a larger model in i disk but that would happily get loaded onto the device.

**Comment by glenn-jocher** [comment]
@koush hello, we're glad to hear you had good results with the export functionality for the USB Coral TPU on YOLOv8!

About your observations:

1. Image Size (imgsz): Yes, Edge TPU has memory limits that extend to the size of tensors in your network. If imgsz is too large, the intermediate tensors during your network's forward pass could exceed Edge TPU's internal memory, causing the model loading to fail. Using smaller imgsz helps mitigate this issue.

2. Model Size: The model size in megabytes on disk relates to the number of parameters in your model, while the model's loading and running successfully on Edge TPU also depends on other factors. One key factor is the tensor sizes in your model (which could be smaller for smaller imgsz even for a larger model), as mentioned above. So, a model could be larger in terms of megabytes (more parameters/filters in the architecture) but still run fine if the maximum tensor size at any point in the network doesn't exceed Edge TPU's capacity.

It's fantastic that you are digging deep and making these observations, as this kind of nuanced understanding can be particularly helpful when adapting models to various ML accelerators. Keep up the good work!
