### ISSUE TITLE
is it possible to run 2 predictions?

### ISSUE THREAD

**Issue by Abshir4** [ultralytics/ultralytics#2943]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hello i want to find number plate but i dont get the results i want. so
im wondering if its possible to first find cars and then run a new prediction on the 
mask to find the number plate. how can i do it? can some1 point me in the right direction?

**Comment by glenn-jocher** [comment]
@Abshir4 hello! Yes, it's definitely possible to first detect cars and then run a new prediction on the mask to find the number plate. One way to do this is to simply crop the mask to the region where the car is located and then run YOLOv8 on that cropped region to detect the number plate. Alternatively, you can assign a unique class to the number plates and then run YOLOv8 on the output of the first detection to specifically detect number plates. Let me know if you need more help with this.
