### ISSUE TITLE
Training 8m model but 8n model is downloaded, why?

### ISSUE THREAD

**Issue by robmarkcole** [ultralytics/ultralytics#2952]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Training 8m but 8n is also downloaded, and a log `AMP: checks passed` what is this?

<img width="1141" alt="image" src="https://github.com/ultralytics/ultralytics/assets/11855322/15a861fe-da94-4534-a951-e485f2600650">

### Additional

```Ultralytics YOLOv8.0.112 🚀 Python-3.10.11 torch-2.0.1+cu118 CUDA:0 (NVIDIA A100-SXM4-40GB, 40514MiB)```

**Comment by glenn-jocher** [comment]
@robmarkcole hello,

The 8m model is actually a subset of the 8n model, as 8n contains all the parameters from 8m, along with additional layers for greater model accuracy. During the training process, the 8n model is saved along with the 8m model, as it contains all the information of the 8m model plus additional parameters.

Regarding your second question, `AMP: checks passed` refers to the Automatic Mixed Precision (AMP) feature of PyTorch, which allows faster and more memory-efficient model training by using half-precision floating-point operations. This message signals that the model successfully passed the checks for using AMP and is therefore using its benefits.

Please let me know if you have any further questions or concerns.

Best regards,
Glenn Jocher
