### ISSUE TITLE
How to Yolov8 .pt -> .tflite

### ISSUE THREAD

**Issue by rgund26** [ultralytics/ultralytics#2956]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can anyone please share the complete tutorial or any page on "how to convert yolov8 .pt file to tflite"

Thank you

### Additional

I have trained the custom model using yolov8 but while running real time I'm getting 10fps of 30fps video. Now I'm thinking to convert the model into .tflite so that it would increase the fps. Or is there any method or model to increase the fps up top 30 cause I'm using RTX 3060, 6  gb

**Comment by Kayzwer** [comment]
@rgund26 https://docs.ultralytics.com/modes/export/

**Comment by glenn-jocher** [comment]
Hello @rgund26, to convert the YOLOv8 .pt file to TFLite, you can use the export function in the Ultralytics YOLOv8 repo. Please visit the Ultralytics documentation to find the necessary steps on how to do this. Regarding the slow FPS issue, you can try optimizing your code or configuration settings to increase the frame rate. It is also possible to try using smaller image sizes or batch sizes which can increase the FPS. Hope this helps!
