### ISSUE TITLE
How to get the polygon vertex coordinates of the object edge of yolov8 segmentation

### ISSUE THREAD

**Issue by 748811693aB** [ultralytics/ultralytics#2961]

**Comment by Kayzwer** [comment]
@748811693aB 
```
from ultralytics import YOLO


if __name__ == "__main__":
    model = YOLO("path/to/model", "segment")
    output = model("path/to/image")[0]
    for vertex_coordinates in output.masks.xy:
        your code ...
        pass
```

**Comment by 748811693aB** [comment]
> @748811693aB
> 
> ```
> from ultralytics import YOLO
> 
> 
> if __name__ == "__main__":
>     model = YOLO("path/to/model", "segment")
>     output = model("path/to/image")[0]
>     for vertex_coordinates in output.masks.xy:
>         your code ...
>         pass
> ```

thanks alot. but is there any simple algorithm to get the boundary coordinates?like cv2.findcounters(...)?

**Comment by 748811693aB** [comment]
> @748811693aB
> 
> ```
> from ultralytics import YOLO
> 
> 
> if __name__ == "__main__":
>     model = YOLO("path/to/model", "segment")
>     output = model("path/to/image")[0]
>     for vertex_coordinates in output.masks.xy:
>         your code ...
>         pass
> ```

wow my fault, it just output the boundary. thanks

**Comment by glenn-jocher** [comment]
@748811693aB thank you for the update! Yes, the polygon vertex coordinates returned by `output.masks.xy` correspond to the boundary of the object segmented by YOLOv8. These coordinates represent a list of (x, y) positions that outline the object boundary. 

Please feel free to ask any further questions or concerns. We are always glad to help you!

**Comment by 748811693aB** [comment]
> @748811693aB thank you for the update! Yes, the polygon vertex coordinates returned by `output.masks.xy` correspond to the boundary of the object segmented by YOLOv8. These coordinates represent a list of (x, y) positions that outline the object boundary.
> 
> Please feel free to ask any further questions or concerns. We are always glad to help you!

great honor to be replied by you. Thanks alot.

**Comment by glenn-jocher** [comment]
@Kayzwer you're welcome! We're always here to help with any questions or concerns you might have. Don't hesitate to ask if you need further assistance or clarification. Thank you for your support of YOLOv8!
