### ISSUE TITLE
Add support for RAW and DICOM image formats

### ISSUE THREAD

**Issue by MattTheCuber** [ultralytics/ultralytics#2962]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

It would be really cool if you added support for RAW and DICOM image formats. As far as my understanding, RAW can have numerous different data formats within the file, so maybe just supporting the popular ones. But more importantly, DICOM (.dcm) images.

Currently supported types:
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/data/utils.py#L27

### Use case

We deal with DICOM images a lot and saving that conversion process would save time and effort. This is especially useful in the medical and industrial scanning fields.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MattTheCuber thank you for your feature request for YOLOv8, and your interest in adding support for the RAW and DICOM image formats. We understand the importance of these image formats, especially in the medical and industrial scanning fields. 

We appreciate your willingness to submit a PR to help with this feature. Adding support for new image formats requires updating the `dataloader.py` script. You can add your own custom dataloader functionality and specify the data location by modifying this file. We recommend checking out the source code for PyTorch's built-in `ImageFolder` method as well as the [Pillow-SIMD](https://github.com/uploadcare/pillow-simd) package, which provides support for a large number of image types. 

Please feel free to reach out if you have any questions or need further assistance. We look forward to seeing your contributions!

**Comment by MattTheCuber** [comment]
@glenn-jocher I can't find the dataloader.py file. I guess I'm confused how (and where in the code) images are normally loaded. According to this: https://github.com/ultralytics/ultralytics/blob/8940a27bdb26895f09a1554514a9a46312aa89c3/docs/modes/predict.md#sources , images are loaded in a lot of different ways. But, for example, I can't seem to find where TIFF images are loaded. DICOM images are usually 16-bit and so I wanted to check how TIFF images were loaded and see if YOLO allows for 16-bit grayscale TIFF images.
