### ISSUE TITLE
Question about the cuda usage

### ISSUE THREAD

**Issue by huyuaaaray** [ultralytics/ultralytics#2964]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,
How can i specifythe cuda to accelerate the prediction when i use the scripts like:
results = model.predict(device = ?)
Sincerely,
Yu Hu

**Comment by Kayzwer** [comment]
try run `print(torch.cuda.list_gpu_processes())` to check gpus in your device.
`results = model.predict("/path/to/image", device=0)` if you wish to use GPU: 0 to run the prediction.

**Comment by glenn-jocher** [comment]
Hello @huyuaaaray,

To specify the CUDA device to use in YOLOv8, you can simply pass the `device` parameter as an integer value corresponding to the index of the desired GPU, or pass the string `"cpu"` if you want to use only the CPU. For example, if you want to use GPU #0 to perform a prediction, you can specify the device parameter as `device=0` when calling the `model.predict()` method.

Before running YOLOv8 with CUDA, you may also want to check which GPUs are available in your device by running `print(torch.cuda.list_gpu_processes())`.

I hope this helps! Let us know if you have any further questions or issues.

**Comment by huyuaaaray** [comment]
Hi,
I really appreciate your answer. When i install cuda 12.2, the torch and YOLOv8 still cannot use the cuda to accelerate the model. Do you think it is the problem that the torch is incompatible with cuda 12.2?
Sincerely,
Yu Hu

**Comment by glenn-jocher** [comment]
Hello @Kayzwer,

Thank you for reaching out. It's possible that incompatibility between PyTorch and CUDA 12.2 may be the cause of the issue you are experiencing with YOLOv8.

One way to check if there is an issue with your installation is to run the `torch.version.cuda` command in Python after importing PyTorch to check which version of CUDA is currently being used. If the command returns the expected version (in your case, CUDA 12.2), then the installed version of PyTorch may not be able to utilize this version of CUDA.

A possible solution would be to upgrade to a version of PyTorch that is compatible with CUDA 12.2. You can check the PyTorch documentation for a list of compatible versions.

I hope this helps. Please let us know if you have any further questions or concerns.

**Comment by huyuaaaray** [comment]
Thanks, when I print the torch.version.cuda, it shows None, so it is the problem that i didn't install the cuda currently? But when i use `nvidia-smi` in the terminal, it can shows the detials of the gpu and cuda version. Do this represents I install it successfully?

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.98                 Driver Version: 535.98       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A1000 Laptop GPU  WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   46C    P0               8W /  38W |      0MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

**Comment by Denizzje** [comment]
That  CUDA Version: 12.2 is the maximum supported CUDA version of Driver Version: 535.98. Generally if you do:

```
pip install ultralytics 
```

it grabs the latest PyTorch with a precompiled CUDA binary (which is as of now 11.7, unless you already install the CUDA 11.8 version via pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118

Maybe you did get just a CPU version of torch somehow (happened to me randomly in the past), you could try to reinstall PyTorch and use the pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 command.

**Comment by huyuaaaray** [comment]
Thanks, @Denizzje . You are right, somehow when i install YOLOv8, it install the cpu version of torch. After your instructions. I can successfully use the cuda with YOLO, but it will throw a error:
```
Traceback (most recent call last):
  File "c:\Users\yu.hu\ultralytics\yolo_realsense.py", line 242, in <module>
    capture_frames()
  File "c:\Users\yu.hu\ultralytics\yolo_realsense.py", line 127, in capture_frames
    results = model.predict(color_image,conf = detection_confidence, classes = key, half = False,device = 0)
  File "C:\Users\yu.hu\AppData\Local\anaconda3\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "c:\Users\yu.hu\ultralytics\ultralytics\yolo\engine\model.py", line 253, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "c:\Users\yu.hu\ultralytics\ultralytics\yolo\engine\predictor.py", line 184, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
  File "C:\Users\yu.hu\AppData\Local\anaconda3\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "c:\Users\yu.hu\ultralytics\ultralytics\yolo\engine\predictor.py", line 244, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "c:\Users\yu.hu\ultralytics\ultralytics\yolo\v8\detect\predict.py", line 14, in postprocess
    preds = ops.non_max_suppression(preds,
  File "c:\Users\yu.hu\ultralytics\ultralytics\yolo\utils\ops.py", line 246, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
  File "C:\Users\yu.hu\AppData\Local\anaconda3\lib\site-packages\torchvision\ops\boxes.py", line 41, in nms
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
  File "C:\Users\yu.hu\AppData\Local\anaconda3\lib\site-packages\torch\_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})
NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].

CPU: registered at C:\Users\circleci\project\torchvision\csrc\ops\cpu\nms_kernel.cpp:112 [kernel]
QuantizedCPU: registered at C:\Users\circleci\project\torchvision\csrc\ops\quantized\cpu\qnms_kernel.cpp:124 [kernel]
BackendSelect: fallthrough registered at ..\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:144 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:491 [backend fallback]
Functionalize: registered at ..\aten\src\ATen\FunctionalizeFallbackKernel.cpp:280 [backend fallback]
Named: registered at ..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ..\aten\src\ATen\ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at ..\aten\src\ATen\native\NegateFallback.cpp:19 [backend fallback]
ZeroTensor: registered at ..\aten\src\ATen\ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:63 [backend fallback]
AutogradOther: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:30 [backend fallback]
AutogradCPU: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:34 [backend fallback]
AutogradCUDA: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:42 [backend fallback]
AutogradXLA: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:46 [backend fallback]
AutogradMPS: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:54 [backend fallback]
AutogradXPU: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:38 [backend fallback]
AutogradHPU: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:67 [backend fallback]
AutogradLazy: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:50 [backend fallback]
AutogradMeta: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:58 [backend fallback]
Tracer: registered at ..\torch\csrc\autograd\TraceTypeManual.cpp:294 [backend fallback]
AutocastCPU: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:487 [backend fallback]
AutocastCUDA: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:354 [backend fallback]
FuncTorchBatched: registered at ..\aten\src\ATen\functorch\LegacyBatchingRegistrations.cpp:815 [backend fallback]
FuncTorchVmapMode: fallthrough registered at ..\aten\src\ATen\functorch\VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at ..\aten\src\ATen\LegacyBatchingRegistrations.cpp:1073 [backend fallback]
VmapMode: fallthrough registered at ..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at ..\aten\src\ATen\functorch\TensorWrapper.cpp:210 [backend fallback]
PythonTLSSnapshot: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:152 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:487 [backend fallback]
PythonDispatcher: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:148 [backend fallback] 

```

**Comment by glenn-jocher** [comment]
@huyuaaaray glad to hear that you were able to successfully use CUDA with YOLOv8! However, it seems that you are encountering an error when running YOLOv8 with CUDA. The error message suggests that the 'torchvision::nms' operator is not available for the CUDA backend, and only available for a few other backends such as CPU and QuantizedCPU. This might be due to a missing or omitted build process. 

One possible solution to the problem is to manually install torchvision with CUDA support, as follows: 

```pip install torchvision -f https://download.pytorch.org/whl/cu111/torch_stable.html```

This will install torchvision with CUDA 11.1 support on your system. Then, modify your code to import these packages, and try running YOLOv8 again to see if the issue is resolved. If this solution does not work, please let us know and we can explore other options.

**Comment by huyuaaaray** [comment]
@glenn-jocher, thanks! I reinstall the ultralytics-8.0.112, and then i uninstall the cpu version of the torch that installed automatically with the ultralytics-8.0.112. Then I use the script to install the cuda torch:
`pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118`
When I use the command line you provide above, it shows all the requirements are satisfied. But I still come across the same problem above. Do you think is it the problem that the cuda toolkit version of 12.2 is incompatible with the YOLO?

**Comment by glenn-jocher** [comment]
Hi @huyuaaaray, it sounds like you have made some progress in resolving your YOLOv8 issue. It's good that you were able to reinstall Ultralytics-8.0.112 and uninstall the CPU version of torch that was installed with it. Additionally, installing the CUDA version of torch via the command you provided is a step in the right direction.

Regarding the issue you are still encountering, it's possible that the problem is due to a compatibility issue between the CUDA Toolkit version of 12.2 and YOLOv8. YOLOv8 may not be able to use the CUDA features of the Toolkit correctly, resulting in the error you're seeing. 

You may want to try downgrading your CUDA Toolkit version to 11.1, which is a version that YOLOv8 officially supports. This may help to resolve the issue you're experiencing. If this does not work, feel free to reach out to us with more details, and we'll do our best to help you out!

**Comment by huyuaaaray** [comment]
Hi @glenn-jocher , when i downgrade to 11.1, it still doesn't work：`Traceback (most recent call last):
  File "c:\Users\yu.hu\ultralytics\yolo_realsense.py", line 251, in <module>
    capture_frames(set_cpu=False)
  File "c:\Users\yu.hu\ultralytics\yolo_realsense.py", line 139, in capture_frames
    results = model.predict(color_image,conf = detection_confidence,classes = key, half = False, device = cuda)  
  File "C:\Users\yu.hu\AppData\Local\anaconda3\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "c:\Users\yu.hu\ultralytics\ultralytics\yolo\engine\model.py", line 253, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream) 
  File "c:\Users\yu.hu\ultralytics\ultralytics\yolo\engine\predictor.py", line 184, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
  File "C:\Users\yu.hu\AppData\Local\anaconda3\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "c:\Users\yu.hu\ultralytics\ultralytics\yolo\engine\predictor.py", line 244, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "c:\Users\yu.hu\ultralytics\ultralytics\yolo\v8\detect\predict.py", line 14, in postprocess
    preds = ops.non_max_suppression(preds,
  File "c:\Users\yu.hu\ultralytics\ultralytics\yolo\utils\ops.py", line 246, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
  File "C:\Users\yu.hu\AppData\Local\anaconda3\lib\site-packages\torchvision\ops\boxes.py", line 41, in nms      
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
  File "C:\Users\yu.hu\AppData\Local\anaconda3\lib\site-packages\torch\_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})
NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes 
for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].

CPU: registered at C:\Users\circleci\project\torchvision\csrc\ops\cpu\nms_kernel.cpp:112 [kernel]
QuantizedCPU: registered at C:\Users\circleci\project\torchvision\csrc\ops\quantized\cpu\qnms_kernel.cpp:124 [kernel]
BackendSelect: fallthrough registered at ..\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:144 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:491 [backend fallback]  
Functionalize: registered at ..\aten\src\ATen\FunctionalizeFallbackKernel.cpp:280 [backend fallback]
Named: registered at ..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ..\aten\src\ATen\ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at ..\aten\src\ATen\native\NegateFallback.cpp:19 [backend fallback]
ZeroTensor: registered at ..\aten\src\ATen\ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:63 [backend fallback]AutogradOther: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:30 [backend fallback]  
AutogradCPU: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:34 [backend fallback]    
AutogradCUDA: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:42 [backend fallback]   
AutogradXLA: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:46 [backend fallback]    
AutogradMPS: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:54 [backend fallback]    
AutogradXPU: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:38 [backend fallback]    
AutogradHPU: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:67 [backend fallback]    
AutogradLazy: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:50 [backend fallback]   
AutogradMeta: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:58 [backend fallback]   
Tracer: registered at ..\torch\csrc\autograd\TraceTypeManual.cpp:294 [backend fallback]
AutocastCPU: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:487 [backend fallback]
AutocastCUDA: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:354 [backend fallback]
FuncTorchBatched: registered at ..\aten\src\ATen\functorch\LegacyBatchingRegistrations.cpp:815 [backend fallback]FuncTorchVmapMode: fallthrough registered at ..\aten\src\ATen\functorch\VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at ..\aten\src\ATen\LegacyBatchingRegistrations.cpp:1073 [backend fallback]
VmapMode: fallthrough registered at ..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at ..\aten\src\ATen\functorch\TensorWrapper.cpp:210 [backend fallback]
PythonTLSSnapshot: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:152 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:487 [backend fallback] 
PythonDispatcher: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:148 [backend fallback]

PS C:\Users\yu.hu\ultralytics> `

**Comment by stonecorleone** [comment]
Hi,
I encountered the same issue.
**Yolov8 
CUDA Toolkit 12.2
Python 3.10.11
Windows 11**

**Torch**: First installation `torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121` returned the error, then changed to `torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121` run without errors but still run on CPU

**Comment by glenn-jocher** [comment]
@stonecorleone hi,

From your description, it seems like the issue might be related to CUDA Toolkit version compatibility, or with the torch bindings to CUDA not being correctly set up.

YOLOv8 typically requires a specific Python version (3.8) and a particular CUDA Toolkit version as well (commonly 10.x, 11.0, or 11.1). Using different versions might cause incompatibilities like the one you're experiencing.

It's possible that your PyTorch installation might not be correctly utilizing your GPU due to the Toolkit version you're using. It might be worth uninstalling your current CUDA Toolkit 12.2 and trying with an earlier version like 11.1.

Additionally, PyTorch sometimes has separate versions for GPU and CPU support. The command you used to install PyTorch might have installed the CPU version. When you're using the PyTorch command, ensure that you're installing the version compatible with CUDA.

Lastly, it might be helpful to verify that your system's environment variables are correctly set so that the Python packages can find your CUDA installation.

Hope this helps you resolve the problem. If you continue to have trouble, we're here to assist you.
