### ISSUE TITLE
Getting number of current epoch during training

### ISSUE THREAD

**Issue by MaxTeselkin** [ultralytics/ultralytics#2965]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! How can I get number of current epoch during model training using YOLO(model_name).train()?

**Comment by glenn-jocher** [comment]
@MaxTeselkin hello! To get the number of current epoch during training with YOLOv8, you can access the `epochs` variable from the `train` method and then use it in your code however you would like. For example:

```
yolo = YOLOv8(model_name='yolov5s')
yolo.train(...)
for epoch in range(yolo.epochs):
    # Do whatever you want with the epoch number
```

I hope this helps! Let me know if you have any other questions.

**Comment by KWiecko** [comment]
Just for the record, currently (ultralytics==8.0.194) this should also do the job (previous answer didn't work for me):

```{python}
yolo = YOLO("<path to weights>")
yolo.train(...)

for epoch in range(yolo.trainer.epochs):
    pass  # do something per epoch
```

**Comment by glenn-jocher** [comment]
@KWiecko hello! Yes, your approach is correct. You instantiated a YOLOv8 model with specific weights and moved on to training. To access the current epoch during training, you extracted the `epochs` variable from the `trainer` attribute of the instantiated YOLO object. By iterating over the range of total epochs, you can apply whatever operation you would like to perform on a per-epoch basis. Just ensure to replace the "pass" statement with the actual operation you are looking to complete. This effectively allows you to get the number of the current epoch and track the model's training progress across epochs. Let me know if you have any other questions!

**Comment by Asshok1** [comment]
After completion of training we are getting epoch number what I want when the training is going on I want to get the in which epoch my model training is going on. Is there any possible for this ?

**Comment by glenn-jocher** [comment]
@Asshok1 hi there! During training with YOLOv8, you can keep track of the current epoch by utilizing callback functions within the training loop. Although direct access to the epoch number isn't provided out-of-the-box as a simple attribute during training, here's a quick example of how you might implement a callback to print the epoch number:

```python
from ultralytics import YOLO, Callback

class PrintEpochCallback(Callback):
    def on_epoch_end(self, epoch, logs=None):
        print(f"Ending Epoch {epoch}")

# Initialize your model
model = YOLO('yolov8n.pt')  

# Attach the callback
callbacks = [PrintEpochCallback()]

# Start training with callbacks
model.train(callbacks=callbacks)
```

This setup will print the epoch number at the end of each epoch, keeping you updated as the training progresses. Hope this helps! 🚀

**Comment by Asshok1** [comment]
In yolov8 
ImportError: cannot import name 'Callback' from 'ultralytics' (/usr/local/lib/python3.10/dist-packages/ultralytics/__init__.py)
I cannot able to probide callback parameter during training

**Comment by Asshok1** [comment]
In yolov8
ImportError: cannot import name 'Callback' from 'ultralytics' (/usr/local/lib/python3.10/dist-packages/ultralytics/init.py)
I cannot able to provide callback parameter during training.

**Comment by Asshok1** [comment]
from ultralytics import YOLO
from ultralytics.utils import callbacks


class PrintEpochCallback(model):
    def on_epoch_end(self, epoch, logs=None):
        print(f"Ending Epoch {epoch}")


# Load the YOLO model (recommended for training)
model = YOLO('yolov8n.pt')

# Create the callback instance
print_epoch_callback = PrintEpochCallback()

# Register the callback with the model (ensure this line is included)
callbacks = [print_epoch_callback]

model.train(data=....yaml', epochs=25, imgsz=200, batch=4, workers=1,
            callbacks=callbacks)
            
            
  I have tried with this code as per knowledge in yolov8 training but i am not getting the current epoch number while training yolov8

Is there any possibility to get epoch number parallelly to store into a variable for another use case

**Comment by glenn-jocher** [comment]
Hey there! 😀

It seems there might have been a slight mix-up in your callback class definition. The `PrintEpochCallback` class needs to inherit from `Callback`, not `model`. Additionally, make sure your callback class methods match what YOLOv8 expects.

Also, callbacks are a part of the training process, but how they are implemented and utilized can vary between versions or custom implementations. If `callbacks` are not directly supported as an argument in the `train` function of the YOLOv8 version you're using, it might require a workaround or a custom modification to the training loop.

Here’s a corrected approach assuming YOLOv8 supports custom callbacks in the way you intended:

```python
from ultralytics import YOLO, Callback  # Correct import paths according to your YOLOv8 setup

class PrintEpochCallback(Callback):  # Ensure it inherits from Callback
    def on_epoch_end(self, epoch, logs=None):
        print(f"Ending Epoch {epoch}")

model = YOLO('yolov8n.pt')
print_epoch_callback = PrintEpochCallback()

# Assuming callbacks can be passed to train() directly. 
# If not, this feature might not be supported out of the box.
model.train(data='your_data.yaml', epochs=25, imgsz=200, batch=4, workers=1, callbacks=[print_epoch_callback])
```

If this doesn’t resolve the issue, it might suggest the current YOLOv8 version or your specific setup doesn’t straightforwardly support the callback functionality as shown. It’s worth checking the official documentation or reaching out in the discussions for insights on implementing custom behavior during the training loop.

Hope this helps! Keep experimenting 🚀
