### ISSUE TITLE
how to output kitti format predict results? 

### ISSUE THREAD

**Issue by HXB-1997** [ultralytics/ultralytics#2968]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

how to output kitti format predict results? could YOLOV8 output informations like below:
```
  1    truncated    Float from 0 (non-truncated) to 1 (truncated), where
                     truncated refers to the object leaving image boundaries
   1    occluded     Integer (0,1,2,3) indicating occlusion state:
                     0 = fully visible, 1 = partly occluded
                     2 = largely occluded, 3 = unknown
   1    alpha        Observation angle of object, ranging [-pi..pi]
   1    rotation_y   Rotation ry around Y-axis in camera coordinates [-pi..pi]
```

### Additional

NOTHING

**Comment by pderrenger** [comment]
@HXB-1997 to output predictions in the KITTI format using YOLOv8, you can utilize the export mode. Once the YOLOv8 model is trained and the desired weights are obtained, you can export the model to the KITTI format using the Export mode. This will convert the model into a deployment-ready format, allowing you to utilize it for KITTI format predictions as per your requirements.

**Comment by Petros626** [comment]
@HXB-1997 any progress with that?
