### ISSUE TITLE
Hyperparameters, min_width tweak recommendation?

### ISSUE THREAD

**Issue by TekayaNidham** [ultralytics/ultralytics#2970]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm working with large scale images 3200*2400, in pose estimation mode, the bboxes as displayed are thin and long, so far I haven't been able to achieve good results. Any suggestions? I have no hardware limitations, accuracy above all 😄

![image](https://github.com/ultralytics/ultralytics/assets/62834628/191d5f28-370d-4a83-8378-cff55a4d2983)

#### my args: 

```python
task: pose
mode: train
model: yolov8m-pose.yaml
data: /home/ntekay01/dataset_pose/cotation_pose/data_pose.yaml
epochs: 500
patience: 50
batch: 1
imgsz:
- 3200
- 2400
save: true
save_period: -1
cache: false
device: cpu
workers: 8
project: null
name: null
exist_ok: false
pretrained: false
optimizer: SGD
verbose: true
seed: 0
deterministic: true
single_cls: false
image_weights: false
rect: false
cos_lr: false
close_mosaic: 0
resume: false
amp: true
overlap_mask: true
mask_ratio: 4
dropout: 0.0
val: true
split: val
save_json: false
save_hybrid: false
conf: null
iou: 0.7
max_det: 300
half: false
dnn: false
plots: true
source: null
show: false
save_txt: false
save_conf: false
save_crop: false
show_labels: true
show_conf: true
vid_stride: 1
line_thickness: 3
visualize: false
augment: false
agnostic_nms: false
classes: null
retina_masks: false
boxes: true
format: torchscript
keras: false
optimize: false
int8: false
dynamic: false
simplify: false
opset: null
workspace: 4
nms: false
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 7.5
cls: 0.5
dfl: 1.5
pose: 12.0
kobj: 1.0
label_smoothing: 0.0
nbs: 64
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.0
copy_paste: 0.0
cfg: null
v5loader: false
tracker: botsort.yaml
save_dir: runs/pose/train4
```

**Comment by glenn-jocher** [comment]
@TekayaNidham thank you for reaching out with your question. Regarding your issue with thin and long bounding boxes while working with large-scale images of 3200x2400 in pose estimation mode, you may want to try tweaking the `min_width` hyperparameter in the `yolov8m-pose.yaml` configuration file. This hyperparameter controls the minimum allowed width of a bounding box. You can experiment with different values to see if it improves your results. Hope this helps! Let me know if you have any further questions.

**Comment by TekayaNidham** [comment]
@glenn-jocher thank you for the answer, are you referring to ```ultralytics/models/v8/yolov8-pose.yaml``` i see no ```min_width``` there can you be more precise please?

**Comment by glenn-jocher** [comment]
@TekayaNidham my apologies for the confusion. You are correct that the `min_width` hyperparameter is not present in the `yolov8-pose.yaml` configuration file. 

However, you can easily add this hyperparameter to the file. Simply add a new line after `max_objs: 128` and insert `min_width: 0`. Then you can experiment with different values for `min_width` to see if it improves your results.

I hope this helps! Let me know if you have any further questions or if there's anything else I can assist you with.

**Comment by TekayaNidham** [comment]
@glenn-jocher I see no ```max_objs: 128``` either, do I add that as well?

**Comment by glenn-jocher** [comment]
@TekayaNidham I apologize for the confusion. It seems that the `max_objs: 128` parameter is not present in the latest version of the `yolov8-pose.yaml` config file. So you can ignore that part of my previous response.

To add the `min_width` parameter to your config file, you will need to add a new line after the `mosaic: 1.0` parameter, and add `min_width: 0`. You can then experiment with different values for `min_width` to improve the results for your model.

I hope that clarifies things. Let me know if you have any further questions or concerns!

**Comment by TekayaNidham** [comment]
SyntaxError: 'min_width' is not a valid YOLO argument.

**Comment by glenn-jocher** [comment]
@TekayaNidham thank you for bringing this to our attention. I apologize for any confusion. The 'min_width' argument is not a valid YOLOv8 argument, despite previous mentions. We understand the importance of fine-tuning the model hyperparameters for specific use cases, but 'min_width' is not a parameter supported by YOLOv8. Please refer to the official YOLOv8 documentation or our repository's configuration files for the list of valid parameters that can be used to fine-tune your model. If you have any further questions or concerns, please feel free to ask.
