### ISSUE TITLE
how to disable wandb?

### ISSUE THREAD

**Issue by lucas-mior** [ultralytics/ultralytics#2973]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Formerly, I was able to disable wandb using:
```
import wandb
wandb.disabled = True
```
or
```
!wandb disabled
```
However, now it seems that yolo always asks for wandb login and won't start training if I don't enter it.

**Comment by glenn-jocher** [comment]
@lucas-mior thank you for your question. In order to disable wandb in YOLOv8, please modify the `wandb_logging.py` file in the `utils` folder by commenting out or deleting the line that initializes wandb. This will prevent the program from asking for wandb login and allow you to train without wandb logging. Let me know if you have any further questions or concerns.

**Comment by Hommoner** [comment]
try add this 
`os.environ['WANDB_DISABLED'] = 'true'`

**Comment by glenn-jocher** [comment]
Thank you for your suggestion @Hommoner. Setting the environment variable `WANDB_DISABLED` to `'true'` is another way to disable wandb in YOLOv8. Once the variable is set, wandb will not initialize and no wandb logging will occur during training. Please let us know if you have any further questions or if you encounter any issues.

**Comment by mpj1234** [comment]
I really don't need wandb login after adding this environment variable, but there will be bugs after the training.(AttributeError: 'DetMetrics' object has no attribute 'curves_results'. See valid attributes below.)， I modify the content `utils/callbacks/wb.py`。
```python
try:
	assert not TESTS_RUNNING  # do not log pytest
	assert SETTINGS['wandb'] is True  # verify integration is enabled
	import wandb as wb

	assert hasattr(wb, '__version__')  # verify package is not directory

	import numpy as np
	import pandas as pd

	_processed_plots = {}

except (ImportError, AssertionError):
	wb = None
# add this
wb = None
````

**Comment by glenn-jocher** [comment]
@mpj1234 it seems that the error `AttributeError: 'DetMetrics' object has no attribute 'curves_results'` indicates an issue beyond just disabling wandb. Setting `wb = None` in `utils/callbacks/wb.py` should indeed turn off wandb, but if there's a problem in the validation or training results handling, it may require a different approach. Please ensure that any changes in the code are consistent with the rest of the codebase, particularly in sections where validation metrics and results are processed. If issues persist, it might be best to carefully review changes to ensure they're not affecting other parts of the code unintentionally.

**Comment by tom-numberone** [comment]
os.environ['WANDB_MODE'] = 'disabled'

**Comment by glenn-jocher** [comment]
Great tip, @tom-numberone! 👍 Setting `os.environ['WANDB_MODE'] = 'disabled'` is indeed a handy way to disable wandb logging without modifying the codebase. 

For those who might need a quick guide on how to use it, simply insert the following line at the beginning of your script:

```python
import os
os.environ['WANDB_MODE'] = 'disabled'
```

This ensures wandb doesn't initialize, allowing you to run your training sessions without wandb login prompts. Thanks for sharing!

**Comment by Yuri-Njathi** [comment]
> Great tip, @tom-numberone! 👍 Setting `os.environ['WANDB_MODE'] = 'disabled'` is indeed a handy way to disable wandb logging without modifying the codebase.
> 
> For those who might need a quick guide on how to use it, simply insert the following line at the beginning of your script:
> 
> ```python
> import os
> os.environ['WANDB_MODE'] = 'disabled'
> ```
> 
> This ensures wandb doesn't initialize, allowing you to run your training sessions without wandb login prompts. Thanks for sharing!

Worked!

**Comment by BunnyNoBugs** [comment]
What worked for me is 

```python
from ultralytics import settings

settings.update({"wandb": False})
```

**Comment by BunnyNoBugs** [comment]
Actually, the fact that wandb and e.g. mlflow interactions are activated by default just because the packages are installed on the machine is confusing. This is kind of an unexpected behaviour.
Ultralytics team, please take a look at this

**Comment by glenn-jocher** [comment]
@BunnyNoBugs thank you for your feedback! We understand that having integrations like wandb and mlflow activated by default can be unexpected and potentially confusing. We appreciate your input and will consider it for future updates to improve user experience.

In the meantime, if you wish to disable wandb, you can use the following approach in your script:

```python
import os
os.environ['WANDB_MODE'] = 'disabled'
```

Alternatively, you can disable wandb within the Ultralytics settings:

```python
from ultralytics import settings
settings.update({"wandb": False})
```

These methods will prevent wandb from initializing, allowing you to proceed without any interruptions. If you encounter any further issues or have additional suggestions, please feel free to share them. Thank you for helping us improve! 😊

**Comment by BunnyNoBugs** [comment]
And also you could use some human-generated responses 😊

**Comment by glenn-jocher** [comment]
Hi @BunnyNoBugs,

Thank you for your feedback! We understand that having integrations like wandb and mlflow activated by default can be unexpected and potentially confusing. We appreciate your input and will consider it for future updates to improve user experience.

In the meantime, if you wish to disable wandb, you can use the following approach in your script:

```python
import os
os.environ['WANDB_MODE'] = 'disabled'
```

Alternatively, you can disable wandb within the Ultralytics settings:

```python
from ultralytics import settings
settings.update({"wandb": False})
```

These methods will prevent wandb from initializing, allowing you to proceed without any interruptions. If you encounter any further issues or have additional suggestions, please feel free to share them. Thank you for helping us improve! 😊

**Comment by stpic270** [comment]
From the all suggestions. For me worked only:
from ultralytics import settings
settings.update({"wandb": False})

**Comment by glenn-jocher** [comment]
@stpic270 thank you for sharing your solution. Disabling Weights & Biases through the `settings.update({"wandb": False})` method is indeed an effective approach. If you have further feedback or run into any issues, feel free to let us know!

**Comment by javierselva** [comment]
> What worked for me is
> 
> from ultralytics import settings
> 
> settings.update({"wandb": False})

That has worked for me when training a model. However, for some reason, if trying to find hyperparameters with model.tune this was not enough, and still I was getting logs in wandb.

Setting the environment variable like this did the trick for me when tunning hyperparameters.

> os.environ['WANDB_MODE'] = 'disabled'

Thanks!!

**Comment by glenn-jocher** [comment]
@javierselva thank you for sharing this important distinction! You're right that hyperparameter tuning with `model.tune()` can behave differently than regular training. Using `os.environ['WANDB_MODE'] = 'disabled'` is indeed the most reliable way to ensure wandb stays disabled across all modes including tuning. You can also disable it globally with `yolo settings wandb=False` which should persist across sessions.
