### ISSUE TITLE
AttributeError: 'Detect' object has no attribute 'nm'

### ISSUE THREAD

**Issue by zj1010** [ultralytics/ultralytics#2981]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hi,i'm a student using yolov8's segment mode,when i trying to train a yolov8 on a segment task,it shows this bug:AttributeError: 'Detect' object has no attribute 'nm',but i've chosen segment as the task in the model defining part,also the cfg file

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AbdesselamFerdi** [comment]
@zj1010 could you insert the command that you have used in order to reproduce the error?

**Comment by glenn-jocher** [comment]
Hello @zj1010, thank you for reporting this issue. Could you please provide us with more details on how you have attempted to use YOLOv8? Specifically, it would be helpful to know the exact command you used to run the model as well as the `yaml` configuration file you used for the model. Also, please let us know if you made any modifications to the code before running it. Thank you!

**Comment by zj1010** [comment]
sorry,I check again and find out its my fault to definite it by using 'yolov8.yaml' when i tried to use it on a segmentation task. Again,i'm so sorry to bother you guys,v8 is an excellent work.

**Comment by Laughing-q** [comment]
@zj1010 It's nice to hear you have solved the issue! Then closing the issue, please feel free to reopen it if you have any related issues. :)
