### ISSUE TITLE
Does YOLOv8-seg use SAM model to segment objects?

### ISSUE THREAD

**Issue by Hsien0802** [ultralytics/ultralytics#2987]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I have refer [https://github.com/ultralytics/ultralytics/issues/189#issuecomment-1489780341](url) to understand that the backbone of the YOLOv8-seg model is a CSPDarknet53 feature extractor.
Does YOLOv8-seg specifically use SAM model to segment objects?
Because I find the introduction about SAM here.
[https://docs.ultralytics.com/models/sam/](url)
Or it just used for auto-annotation in YOLOv8.

**Comment by Laughing-q** [comment]
@Hsien0802 the SAM model is only used for auto-annotation in YOLOv8.
