### ISSUE TITLE
Steam = False not working

### ISSUE THREAD

**Issue by dvdco** [ultralytics/ultralytics#2989]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

In my understanding the stream option is for turning on and off the console ourput, but when i set it to false, it still  outputs the logs.

`
...
0: 640x640 (no detections), 11.0ms
Speed: 2.0ms preprocess, 11.0ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)

0: 640x640 (no detections), 5.6ms
Speed: 2.0ms preprocess, 5.6ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)
...`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@dvdco actually `stream` is to save memory when predicting long or a large size image folder. I guess what you want is `verbose`. You can set `verbose=False` to turn off the console output.
