### ISSUE TITLE
The difference in TFLite output can be confusing when deploying it to Android.

### ISSUE THREAD

**Issue by Riandrp** [ultralytics/ultralytics#2990]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm having trouble deploying the best_float16.tflite model to Kotlin because it has a different data type compared to the code I'm following. Here are the differences I have identified.

here is my model (model 1):
<img width="522" alt="Screenshot 2023-06-03 234801" src="https://github.com/ultralytics/ultralytics/assets/98405455/ec191de7-4867-4a8b-8061-a8b8909c35c8">

and another model (model 2): 
<img width="578" alt="Screenshot 2023-06-03 234910" src="https://github.com/ultralytics/ultralytics/assets/98405455/ed5f936f-f7fa-4e3d-8644-ba0b1b7c4c7b">

My question: How can I obtain the same results as Model 2 because it is difficult to retrieve the locations, classes, and scores when using my model (Model 1)? Or do you have any suggestions on how to achieve a model similar to Model 2? Or could it be that I made a mistake in implementing the conversion to TFLite?

**Comment by glenn-jocher** [comment]
@Riandrp hello! 

If the output structure of the TFLite model is different from what you're expecting, the issue likely lies in the conversion process. The conversion of a PyTorch-trained YOLOv8 model to TFLite can be tricky, as the conversion script requires several manual modifications on the script to generate an output structure similar to Model 2. Therefore, it's important to double check the conversion script to ensure all steps were completed accurately.

Alternatively, you might consider the TF or Keras formats instead of TFLite. This is because not all YOLO models are guaranteed to work with TFLite as it has some limitations. However, these formats will require a separate conversion process and some adjustments to make sure you get the same output structure as Model 2, which seems like is what you are seeking.

Good luck with your project!

**Comment by Riandrp** [comment]
Thank you for your answer. Could you provide an example of the conversion you mentioned? I am still confused. Is the conversion you referred to when exporting the model to TFLite and then adding arguments?

**Comment by glenn-jocher** [comment]
@Riandrp, my apologies for not being clear enough in my previous response. The conversion process I mentioned refers to the conversion of your PyTorch-trained YOLOv8 model to the TFLite format. Ultralytics provides a conversion script to help convert PyTorch models to TFLite. The conversion script can be found in the `export_tflite.py` file in the Ultralytics YOLOv8 repo. 

To clarify, please follow the steps below to obtain a similar output structure as Model 2:
1. First, train your YOLOv8 model using PyTorch. 
2. Once your model is trained, export the model to TFLite using the `export_tflite.py` script.
3. However, Model 2 and Model 1 have different output structures. To obtain a similar output structure as Model 2, you'll have to modify the `export_tflite.py` script. You'll need to modify the `interpreter.allocate_tensors()` call and add the `np.copy()` function to retrieve the locations, classes, and scores as shown in Model 2.

I hope this clarifies the conversion process for you. If you have any further questions, please don't hesitate to ask.

**Comment by Riandrp** [comment]
Thank you for your answer.. Sorry, I would like to ask again, what do you mean in point 3 as mentioned in this link: https://github.com/ultralytics/yolov5/issues/1981#issuecomment-767685747, and how do I save it back to tflite?

**Comment by glenn-jocher** [comment]
@Riandrp, I apologize for any confusion. In step 3, after modifying the `export_tflite.py` script to include `np.copy()`, you will need to use this modified script to convert the PyTorch-trained YOLOv8 model to TFLite. The output of running the modified `export_tflite.py` script will be a new TFLite model file that has the desired output structure similar to Model 2.

Once you have this new TFLite file, there is no need to "save it back" to TFLite. This new TFLite file will now have the desired output structure when you run inference on it in your Android application. You can use this TFLite file directly in your code to perform object detection and retrieval of locations, classes, and scores as per Model 2.

I hope this clarifies your question. Please let me know if you have any further questions or concerns.

**Comment by Riandrp** [comment]
Thank you for your answer, I can't find export_tflite.py in the repo, can you show me the link?

**Comment by glenn-jocher** [comment]
@Riandrp hello! Thank you for your question. The `export_tflite.py` script for YOLOv8 can be found in the `models/tf.py` file in the Ultralytics YOLOv8 repo. This file contains the function `export_tf_lite()` that can be used to export your PyTorch-trained YOLOv8 model to TFLite.

To use this function, you will need to import it in your script and pass in the necessary arguments, including the path to your PyTorch-trained model, the path to the saved TFLite file, and any optional arguments such as an input shape.

I hope this helps! If you have any further questions or concerns, please don't hesitate to ask.

**Comment by Riandrp** [comment]
thank you for your answer. can you share link?. i dont get it in repo

**Comment by Riandrp** [comment]
do you mean this script:
`@try_export
def export_tflite(self, keras_model, nms, agnostic_nms, prefix=colorstr('TensorFlow Lite:')):
    """YOLOv8 TensorFlow Lite export."""
    import tensorflow as tf  # noqa

    LOGGER.info(f'\n{prefix} starting export with tensorflow {tf.__version__}...')
    saved_model = Path(str(self.file).replace(self.file.suffix, '_saved_model'))
    if self.args.int8:
        f = saved_model / f'{self.file.stem}_int8.tflite'  # fp32 in/out
    elif self.args.half:
        f = saved_model / f'{self.file.stem}_float16.tflite'  # fp32 in/out
    else:
        f = saved_model / f'{self.file.stem}_float32.tflite'
    return str(f), None`

**Comment by glenn-jocher** [comment]
@Riandrp hello! 

The script you shared is a snippet from the `tf.py` file in the Ultralytics YOLOv8 repo that defines the `export_tf_lite()` function. This function is used to export a PyTorch-trained YOLOv8 model to the TFLite format.

When using this function, you will need to pass in several arguments, such as the location of your PyTorch model file, whether to use fp32, fp16, or int8 precision, and the location to save the TFLite file, among others.

After running this function, you should have a TFLite file that can be loaded into your Android application and used for object detection with YOLOv8.

**Comment by mmmriyan** [comment]
@Riandrp hello, did the problem work? I have the same problem when I want to implement the Yolov8 model on Android

**Comment by mmmriyan** [comment]
@glenn-jocher hello sir

I run the program code like this:
!python export.py --weights myPath/best.pt --include tflite --float16 --img 640 --data myPath/data.yaml

and I get output like thist:
TorchScript: export success ✅ 18.0s, saved as yolov8n.torchscript (12.4 MB)
why the output is torchsript? i want to convert PyTorch to TFLITE
i hope u can help sir, thanks!

**Comment by gurushanthmurthy** [comment]
Hello @Riandrp, can you manage the export model to tflite format with metadata as required in Mode 2 format? 
@glenn-jocher I have exported my custom-trained model to tflite and used TF Lite to load model on Android, throwing following error,
`java.lang.RuntimeException: Error occurred when initializing ObjectDetector: Input tensor has type kTfLiteFloat32: it requires specifying NormalizationOptions metadata to preprocess input images.`

**Comment by glenn-jocher** [comment]
@gurushanthmurthy hello,

The error message you're encountering, `java.lang.RuntimeException: Error occurred when initializing ObjectDetector: Input tensor has type kTfLiteFloat32: it requires specifying NormalizationOptions metadata to preprocess input images.`, implies that the TensorFlow Lite Interpreter expects a specific format for preprocessing the input images, which are not being met in the current scenario.

When converting a model to TFLite, metadata about normalization (NormaliztionOptions) needs to be attached to the model if the input tensor is of type kTfLiteFloat32. This metadata usually describes how to convert the raw pixel values of the image to the scale of the input tensor.

This information is model specific and is typically defined during training. Make sure you have included the necessary normalization metadata in your model when exporting to TFLite.

Note: This assumes YOLOv8's typical normalization where pixel values are scaled to the range of [0, 1], but you should verify and adjust this if your training procedure was different.

I hope this helps to clarify the issue you're experiencing. Do feel free to reach out if you have any further questions.

**Comment by Thatsgaurav** [comment]
Any one have a working android sample using these exported models ?

**Comment by glenn-jocher** [comment]
@Thatsgaurav no, we currently do not provide an Android sample. However, after exporting the YOLOv8 model to TFLite, you can use the TensorFlow Lite Android Support Library to integrate the model into your application. Our models are designed to be compatible with standard TensorFlow Lite workflows. 😊📱

**Comment by devashpontay** [comment]
Hi @glenn-jocher. As per model 1 indicated in this post. Is there a way to interpret that output? I saw your explanation here:
https://github.com/ultralytics/ultralytics/issues/2670#issuecomment-1552199694

You explained there that the output has 3 dimensions:

`"The first dimension represents the batch size"`

` "The second dimension consists of 84 values, where the first 4 values represent the bounding box coordinates (x, y, width and height) of the detected object, and the rest of the values represent the probabilities of the object belonging to each class."`

`"Finally, the third dimension represents the maximum number of possible detected objects, which is 8400 in this case."`

How will the actual output look like in raw form? Will it look like an array [1, 0.XXX, 0.XXX, ....], where the '0' index equals the batch size, the '1st' to '4th' index equals the bounding box, and so on as per your explanation?

**Comment by glenn-jocher** [comment]
@devashpontay hello!

The raw output will resemble a 3-dimensional array with shape `[batch_size, number_of_detections, 84]`. For each detection, indexes `[0,1,2,3]` correspond to the bounding box `[x, y, width, height]`, and indexes `[4:84]` hold class probabilities. The output would be a nested array, with each inner array representing a single detection across all classes. 📦💡

**Comment by ArtashesH** [comment]
hello All
I am exporting the yolov8 based custom object detection model into tf-lite with this command

yolo mode=export  model=best.pt  format=tflite 

So it is exporting successfully, and when I am trying to use the exported model best_float32.tf in rasp pi5, ubuntu 22, it is giving this error


RuntimeError: Input tensor has type kTfLiteFloat32: it requires specifying NormalizationOptions metadata to preprocess input images.


PLease tell me, how to fix this issue.

**Comment by glenn-jocher** [comment]
@ArtashesH hello,

The error indicates that the TFLite model expects input preprocessing details in the form of NormalizationOptions metadata. To fix this, ensure that when exporting your model to TFLite, you include the necessary metadata that describes how to preprocess the input images for your model. This typically involves specifying how the raw input data should be normalized to match the input format expected by the model. Check the documentation on how to attach this metadata during the export process. 🛠️📊

**Comment by glenn-jocher** [comment]
@ArtashesH, to attach metadata to your TFLite model, you'll need to use additional tools or APIs provided by TensorFlow that allow you to define and include this information. Unfortunately, our export function does not currently handle the attachment of metadata directly. For detailed guidance on how to add metadata to a TFLite model, please refer to the TensorFlow Lite documentation on metadata. 📚🔧
