### ISSUE TITLE
Key point detection classified

### ISSUE THREAD

**Issue by Hasnain1997-ai** [ultralytics/ultralytics#2993]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi!

I wanted to train yolov8 key point detection for a custom dataset that is image of marker with head an tail as key point.

But I want the key point results classified as: AFter detection it should say that this key point is head and this is tail.

So I want to know what should be its data.yaml file and label file look like and what are the things that I need to change
Like the one below

![image](https://github.com/ultralytics/ultralytics/assets/84834010/88ecc915-3061-40ba-ab93-ad43c98c1d2a)

**Comment by glenn-jocher** [comment]
@Hasnain1997-ai hi, 

To train YOLOv8 for key point detection, you need to add two columns "keypoint1" and "keypoint2" to your label file. In "keypoint1" column, you can specify the coordinates of the head keypoint, and in "keypoint2" column, you can specify the coordinates of the tail keypoint. 

To classify the key point results, you can modify the data.yaml file to add the class names "head" and "tail" and specify them in the label file corresponding to each keypoint. 

Let us know if you have any further questions or concerns. 

Best, 
Glenn Jocher

**Comment by Hasnain1997-ai** [comment]
Thank you for the response @glenn-jocher 

but can you guide me if further if my
**data.yaml** file is :

```
train:./yolo_key_point_data/train/
val:./yolo_key_point_data/val/

names: 
   0: Marker

# Keypoints
kpt_shape: [2, 2]  # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)
```

and a **label file** img_1.txt is:
`0 0.56171875 0.67125 0.309375 0.175 0.440625 0.6975 0.540625 0.62625 0.55546875 0.7225 0.68671875 0.6375`

That how will these two file looks

**Comment by Laughing-q** [comment]
@Hasnain1997-ai hi, it seems you only have 2-pairs keypoints(head and tail), but I see 4-pairs keypoints in your label file which is the latest 8 points. I suppose in your case you might only need 2-pairs keypoints(4 points).

**Comment by Hasnain1997-ai** [comment]
@Laughing-q  you are right, it should be four, I pasted label file of another project, I am correcting it now

**Comment by Hasnain1997-ai** [comment]
@Laughing-q  I also understood from examples the same I am curious how can we add them to training the model and getting classified key points at output

**Comment by Laughing-q** [comment]
@Hasnain1997-ai Let's say you already have a trained model with the above format and do inference on a image with only one object in it, then in your case you'll get `prediction` with shape `[2, 2]`, the `prediction[0]` is the head point and `prediction[1]` is the tail point.
