### ISSUE TITLE
With ultralytics==8.0.112, bug retrieving pose keypoints

### ISSUE THREAD

**Issue by jimmybuffi** [ultralytics/ultralytics#2998]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Using `yolov8n-pose.pt`, with `ultralytics==8.0.112`, accessing key points after pose key point detection seems to result in an index error:

```
/yolo/.venv/lib/python3.10/site-packages/ultralytics/yolo/engine/results.py", line 555, in conf
    return self.data[..., 3] if self.has_visible else None

IndexError: index 3 is out of bounds for axis 2 with size 3
```

However, this same functionality returns a numpy array with `ultralytics==8.0.111`

### Environment

Ultralytics 8.0.112
MacOS
Python 3.10

### Minimal Reproducible Example

from ultralytics import YOLO

model = YOLO('yolov8n-pose.pt')

results = model.predict(img)

print(results[0].cpu().numpy().keypoints)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jimmybuffi Great news 😃! Your original issue may now be resolved ✅ in PR #2998. Can you please try the PR branch and let us know if this resolves your issue?

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by jimmybuffi** [comment]
So sorry for the delay here, looks like this issue is resolved! thank you!

**Comment by pderrenger** [comment]
@jimmybuffi you're very welcome! 😊 I'm glad to hear that the issue has been resolved. If you encounter any more issues or have any feature requests in the future, please don't hesitate to let us know. We're here to help! Happy coding with YOLOv8! 🎉
