### ISSUE TITLE
Where is the confidence info in onnx output?

### ISSUE THREAD

**Issue by hkncccn** [ultralytics/ultralytics#300]
### Search before asking

- [ ] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

in yolov5, 
when I write,
*
*
*
preds = yolo.forward() #predict
print(preds.shape)

for 20 classes , the output is (1, 25200, 25(classes + 5)). 
preds[0][x][4] is the confidence of each prediction.

But in yolov8 the output is (1, 24, 8400). 
How can I get the confidence info?

**Comment by phixerino** [comment]
there is no objectness like in yolov5, so just take the biggest confidence

**Comment by AyushExel** [comment]
See this official example for YOLOv8 ONNX opencv python and C++ inference https://github.com/ultralytics/ultralytics/tree/main/examples/

**Comment by unmakame** [comment]
nice

**Comment by glenn-jocher** [comment]
@hkncccn YOLOv8 removed the objectness score from the output format. In YOLOv8 ONNX output `(1, 84, 8400)`, the first 4 channels contain box coordinates (x, y, w, h) and the remaining 80 channels contain class probabilities. The confidence for each detection is simply the maximum class probability across those 80 channels - no separate objectness multiplication needed like in YOLOv5.
