### ISSUE TITLE
Pytorch Yolov8 pose Class File

### ISSUE THREAD

**Issue by mattcattb** [ultralytics/ultralytics#3001]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have some ideas for how I would be interested in changing the layers of the yolov8 pose model to be better adapted for mobile inference. Is there a file with a pytorch class, or would I have to look through the documentation and source code to find and stitch together all of its modules? I only have the .pt dict. This would be greatly appreciated if possible. Thank you.

**Comment by glenn-jocher** [comment]
@mattcattb the Pose head is here:
https://github.com/ultralytics/ultralytics/blob/2193ca1658007013c25cb427b1ddfbdfeb3c3829/ultralytics/nn/modules/head.py#L100-L139
