### ISSUE TITLE
Instance Segmentation with SAHI and YOLOv8

### ISSUE THREAD

**Issue by olivierdecitre** [ultralytics/ultralytics#3008]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello everyone, 

I'd need your help for a project I'm running, I have a few issues. My project aims to detect giant clams from drone imagery. I've trained an object detection algorithm well enough and have the weight "google2.pt" that I'm happy with. But now I can to use that detection on his large imagery, I'm using SAHI to help me but I'm encountering a few issues: 

1: the labels are way too big ! this seems like a stupid issue but I havent found a way to solve this yet. below is one of those drone images I tried running my algorithm on. 

![image](https://github.com/ultralytics/ultralytics/assets/135571869/39b551d7-7320-4510-85ae-d0cb3a379116)

2: how do I make it so I have my instance segmentation as well? The data was trained as an instance segmentation model and I only have the bounding boxes right now. 

3: more of a minor problem but I haven't been able to get a return for the total number of objects detected. 

Any help would be amazing thank you !! I'll paste the code below. 

import os
os.getcwd()
os.chdir(r"C:\Users\olivi\OneDrive\Desktop\Python\7_SAHI")

from sahi import AutoDetectionModel
from sahi.utils.cv import read_image
from sahi.utils.file import download_from_url
from sahi.predict import get_prediction, get_sliced_prediction, predict
from IPython.display import Image
from sahi.utils.cv import visualize_object_predictions

yolov8_model_path = "google2.pt"

detection_model = AutoDetectionModel.from_pretrained(
    model_type='yolov8',
    model_path=yolov8_model_path,
    confidence_threshold=0.8,
    device="cpu", # or 'cuda:0'
)

result = get_sliced_prediction(
    "dji.jpg",
    detection_model,
    slice_height = 640,
    slice_width = 640,
    overlap_height_ratio = 0.3,
    overlap_width_ratio = 0.3,
)

result.export_visuals(export_dir="demo_data/")

Image("demo_data/prediction_visual.png")

object_prediction_list = result.object_prediction_list
object_prediction_list[0]

**Comment by glenn-jocher** [comment]
@olivierdecitre in YOLOv8 you can use `hide_labels=True` to hide the labels, not sure about SAHI. See https://docs.ultralytics.com/modes/predict/#arguments for a full list of prediction arguments.

**Comment by monkeycc** [comment]
I also have a project to test minerals

It is also a target detection method with large image size and small image size

SAHI is also needed


There will be a problem here



1. Original drawing annotation

How to cut Labelme into small images in YOLO8 format


2. Yolov8+SAHI, simple inference code

**Comment by pderrenger** [comment]
@monkeycc for splitting Labelme annotations into small images in YOLOv8 format, you can use LabelmeSplitter (https://github.com/wkentaro/labelme/tree/master/examples/python). For YOLOv8+SAHI inference, you can use the provided inference code like this:

```python
from sahi import AutoDetectionModel
from sahi.utils.cv import read_image
from sahi.predict import get_prediction

yolov8_model_path = "your_yolov8_model_path"

detection_model = AutoDetectionModel.from_pretrained(
    model_type='yolov8',
    model_path=yolov8_model_path,
    confidence_threshold=0.8,
    device="cpu",  # or 'cuda:0'
)

# Read the image
image = read_image("your_image_path.jpg")

# Get the predictions
predictions = get_prediction(image, detection_model)

# Display the annotated image
annotated_image = detection_model.predict(image)
```

This code provides a simple inference using YOLOv8 and SAHI.

**Comment by Sarai256** [comment]
> @monkeycc for splitting Labelme annotations into small images in YOLOv8 format, you can use LabelmeSplitter (https://github.com/wkentaro/labelme/tree/master/examples/python). For YOLOv8+SAHI inference, you can use the provided inference code like this:
> 
> ```python
> from sahi import AutoDetectionModel
> from sahi.utils.cv import read_image
> from sahi.predict import get_prediction
> 
> yolov8_model_path = "your_yolov8_model_path"
> 
> detection_model = AutoDetectionModel.from_pretrained(
>     model_type='yolov8',
>     model_path=yolov8_model_path,
>     confidence_threshold=0.8,
>     device="cpu",  # or 'cuda:0'
> )
> 
> # Read the image
> image = read_image("your_image_path.jpg")
> 
> # Get the predictions
> predictions = get_prediction(image, detection_model)
> 
> # Display the annotated image
> annotated_image = detection_model.predict(image)
> ```
> 
> This code provides a simple inference using YOLOv8 and SAHI.

Thank you. So i this code, Dont i need to specify the slicing width and height, plus the overlap ration?

**Comment by Sarai256** [comment]
> @monkeycc for splitting Labelme annotations into small images in YOLOv8 format, you can use LabelmeSplitter (https://github.com/wkentaro/labelme/tree/master/examples/python). For YOLOv8+SAHI inference, you can use the provided inference code like this:
> 
> ```python
> from sahi import AutoDetectionModel
> from sahi.utils.cv import read_image
> from sahi.predict import get_prediction
> 
> yolov8_model_path = "your_yolov8_model_path"
> 
> detection_model = AutoDetectionModel.from_pretrained(
>     model_type='yolov8',
>     model_path=yolov8_model_path,
>     confidence_threshold=0.8,
>     device="cpu",  # or 'cuda:0'
> )
> 
> # Read the image
> image = read_image("your_image_path.jpg")
> 
> # Get the predictions
> predictions = get_prediction(image, detection_model)
> 
> # Display the annotated image
> annotated_image = detection_model.predict(image)
> ```
> 
> AM RUNNING INTO AN ERROR WITH THE CODE BELOW
from sahi import AutoDetectionModel
from sahi.utils.cv import read_image
from sahi.predict import get_prediction

yolov8_model_path = "D:\Codes\YOLOV8\YOLOv8\bestonsynthetic.pt"

detection_model = AutoDetectionModel.from_pretrained(
    model_type='yolov8',
    model = yolov8_model_path,
    confidence_threshold=0.5,
    device="cpu",  # or 'cuda:0'
)

# Read the image
image = read_image("2.jpg")

# Get the predictions
predictions = get_prediction(image, detection_model)

# Display the annotated image
annotated_image = detection_model.predict(image)

I get this error below when i use that code: 
Traceback (most recent call last):
  File "D:\Codes\YOLOV8\YOLOv8\SahiInference.py", line 7, in <module>
    detection_model = AutoDetectionModel.from_pretrained(
  File "C:\Users\user\anaconda3\envs\yolov8_custom\lib\site-packages\sahi\auto_model.py", line 66, in from_pretrained
    return DetectionModel(
  File "C:\Users\user\anaconda3\envs\yolov8_custom\lib\site-packages\sahi\models\base.py", line 65, in __init__
    self.set_model(model)
  File "C:\Users\user\anaconda3\envs\yolov8_custom\lib\site-packages\sahi\models\yolov8.py", line 47, in set_model
    category_mapping = {str(ind): category_name for ind, category_name in enumerate(self.category_names)}
  File "C:\Users\user\anaconda3\envs\yolov8_custom\lib\site-packages\sahi\models\yolov8.py", line 70, in category_names
    return self.model.names.values()
AttributeError: 'str' object has no attribute 'names'

**Comment by glenn-jocher** [comment]
Hello! It looks like there's a small mix-up in the function name. For predicting with a YOLOv8 model, you should use the `.predict` method on the model object directly. However, if you're using SAHI, the method to obtain predictions might differ.

Here's a quick example of how you can perform predictions directly with a YOLOv8 model:

```python
from ultralytics import YOLO

# Load your trained model
model = YOLO('path/to/your/model.pt')

# Perform predictions
results = model('path/to/your/image.jpg')
```

Make sure that the object 'model' is an instance of the model you're expecting to use. If you're working within SAHI, you might need to adjust the method according to their API. Thank you for reaching out, and happy coding! 🚀
