### ISSUE TITLE
When there is no bbox on some images, the model train that image?

### ISSUE THREAD

**Issue by studyfirston** [ultralytics/ultralytics#3009]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello. 

In the process of model training
I wonder when some images has no bbox,
then how does YoloV8 handle these no bbox data?

I saw similar question, but there's no specific answer. So I ask question.

https://stackoverflow.com/questions/75979297/yolov8-label-file-when-there-is-no-bounding-box
Like the question above, I wanna train the model using no-label data.
Because there's case when there is no object.

What I wanna know is
1) how does YoloV8 handle images without bbox on the traning process
2) If I can train the model with no-bbox data, 
how should the image label file be constructed? (Does image file need a label file?)

**Comment by Laughing-q** [comment]
@studyfirston We handle images without bbox as background images while training, and you just do not provide the label file if you want these images to be handled as background.

**Comment by studyfirston** [comment]
@Laughing-q Thank you for answering.
But, I confused that you mean images without bbox can be trained while training right?

**Comment by Laughing-q** [comment]
@studyfirston yeah it can be trained, as backgrounds.

**Comment by studyfirston** [comment]
@Laughing-q 
I understand. 
Thank you for helping me, have a nice day!

**Comment by studyfirston** [comment]
@Laughing-q 
Oh, I'm sorry. I have an one more question.
So if there's no bbox, then that images need a label file or no label file?
and if need label file.
In the label file, what text must be in?

**Comment by Laughing-q** [comment]
@studyfirston do not need a label file. Let me give you a example:
```
--images
----img1.jpg
----img2.jpg
--labels
----img1.txt
```
if the folder is like this, then `img1.jpg` will be trained as a normal labeled image, and `img2.jpg` will be trained as a background(a image without boxes).

**Comment by studyfirston** [comment]
@Laughing-q 
I really appreciated it.
Thank you!~
