### ISSUE TITLE
What is the post-processing (NMS) of yolov8-pose?

### ISSUE THREAD

**Issue by Charlie-crl** [ultralytics/ultralytics#3010]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello，

I am very interested in yolov8-pose. By looking at the code carefully, it is found that the pose and detect modules share an NMS function named "non_max_suppression" in yolo->utils->ops.py.

So I would like to ask, is the NMS strategy for key point detection the same as the NMS strategy for box detection? By selecting the appropriate box for the NMS of the box, the key points are screened. 

What should I do if I want to customize the NMS strategy of key points

### Additional

I want to better adapt to the characteristics of the data set by customizing the NMS of the key points. Thanks!

**Comment by Laughing-q** [comment]
@Charlie-crl 
> is the NMS strategy for key point detection the same as the NMS strategy for box detection?

yes we select bboxes first then filter keypoints in the same way. If you want to customize your own nms, my answer is just modifying the function `non_max_suppression` since I don't know how you want to modify it.

**Comment by tanishk27** [comment]
@Laughing-q so are you saying we just pick the keypoint coordinates of the nms selected bounding box?

**Comment by Laughing-q** [comment]
@tanishk27 yes

**Comment by Charlie-crl** [comment]
@Laughing-q I see, thank you！

**Comment by glenn-jocher** [comment]
You're welcome, @Charlie-crl! If you have any other questions or need further assistance, don't hesitate to ask. We are happy to help!
