### ISSUE TITLE
For Face emotion recognition task, what kind model do I have to use? 

### ISSUE THREAD

**Issue by dataliszt** [ultralytics/ultralytics#3011]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, ultralyrics! 

First, thanks for your open source code, it is really helpful to build application. 
I do have question that for face emotion recognition, what kind of task and model do I have to choose? 
- at first, I need to detect a face 
- and classify wether it is positive of neutral or negative  
- the dataset I have consists of image including emotional face with coordinate. 

Do I need classification model or deteciton model you are offering? I wonder classification model is 2 step model, like detecting 
 face and classifying it.

cheers,

**Comment by Laughing-q** [comment]
@dataliszt well if the emotions only contain two categories(positive and negative), I suggest to try one detection model to detect face and meanwhile classify emotions. Then go with detection model + a independent classify model if the performance is not as good as expect.

**Comment by dataliszt** [comment]
> @dataliszt well if the emotions only contain two categories(positive and negative), I suggest to try one detection model to detect face and meanwhile classify emotions. Then go with detection model + a independent classify model if the performance is not as good as expect.

Hi, Laughing-q, thanks for quick answer. Maybe I should try to classify emotion with detection model and your suggestion. 

I will share the results. 

Thanks,

**Comment by glenn-jocher** [comment]
@dataliszt you're welcome, happy to help! Do let us know how it goes with detecting faces and classifying emotions using the detection model. If you have any additional questions or run into any issues, feel free to ask. Good luck with your project!

**Comment by monkeycc** [comment]
1.Object Detection Cropping Face

2.Classification detection and emotion detection

**Comment by pderrenger** [comment]
@monkeycc it looks like you have a plan in place! Yes, you can start by implementing object detection to crop faces from images, and then move on to classifying the emotions detected on those cropped faces. Let me know if you need further assistance with any of these steps. Good luck!
