### ISSUE TITLE
YOLOv8 Is it suitable to be made into OCR ?

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#3012]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Letters+Numbers

1. Object detection or segmentation detection
Detected a line of text
Cropping

2.Object detection or segmentation detection
Detected individual text
Cropping

3. Classification detection

Result combination output

I'm not sure about the effect of what I did and the OCR effect

Which is better

**Comment by glenn-jocher** [comment]
@monkeycc hi there,

Thank you for your interest in YOLOv8! 

In general, YOLOv8 is a strong object detection framework and should be able to recognize individual characters and numbers. It is definitely possible to use it for OCR (Optical Character Recognition) by training on a dataset of characters and numbers. 

Based on the requirements you've mentioned, it seems like a combination of object detection and classification detection would work best for your OCR use case. For example, the first step could involve detecting a line of text and cropping it, followed by detection and classification of individual characters within the cropped image.

I hope this helps! If you have any further questions or concerns, don't hesitate to ask. 

Best regards,
Glenn Jocher

**Comment by FreedomLiX** [comment]
PaddleOCR repository: [https://github.com/PaddlePaddle/PaddleOCR](url)

**Comment by glenn-jocher** [comment]
@FreedomLiX hi there,

Thanks for bringing the PaddleOCR repo to our attention! Our team here at Ultralytics focuses on the development and maintenance of YOLOv8, an object detection framework based on YOLO, rather than OCR. As such, we don't have any direct experience with PaddleOCR.

That being said, we welcome and encourage collaboration and contributions from the open-source community. If PaddleOCR requires object detection capabilities, YOLOv8 could be a viable option for integration. However, I would recommend diving into specific details to determine if it's a good fit.

I hope this provides some insight, and please let me know if you have any further questions or concerns!

Best regards,
Glenn Jocher

**Comment by KetanB17395** [comment]
how can we manage the sequence of charecter

**Comment by glenn-jocher** [comment]
@KetanB17395 hi there,

To manage the sequence of characters detected by an object detection model like YOLOv8, one common strategy is to use the bounding box coordinates of the identified characters. By sorting these bounding boxes from left to right, you can infer the sequence of characters in a line. 

For example, if you have detected characters with bounding boxes, you can list them, then sort this list based on the x-axis coordinates of the bounding boxes. The character with the smallest x-coordinate is the first character, the one with the next smallest x-coordinate is the second character, and so on. 

However, please note that this method assumes that your text is in a straight line and read from left to right. If your text arranges vertically or in a different direction, you might need a different strategy or even a separate text recognition model.

Remember, while YOLOv8 is great for object detection tasks, handling the sequence of characters after detection typically requires additional processing or even different methodologies.

I hope this helps! If you have any further questions, feel free to ask.

Best regards,
Glenn Jocher

**Comment by monkeycc** [comment]
Need to reorder coordinates

X coordinate minimum value

Need to be processed as

Coordinate+label name

[[x1,y1,x2,y2,name],[x1,y1,x2,y2,name],[x1,y1,x2,y2,name]]

[name,name,name]

[1,2,3]

"123"

**Comment by glenn-jocher** [comment]
@monkeycc hi there,

It sounds like you're trying to ensure the textual elements in your image get detected and labeled in the correct order, based on their x-coordinates. 

You can extract the bounding box coordinates predicted by YOLOv8 and then sort them based on the x1 value (i.e., the x-coordinate of the top-left corner of each bounding box). This will arrange your detections from left to right.

Once your detections are sorted, you can append the name of each detected character to your final list, following the sorted order of characters as per their x-coordinates.

Following the above steps, you get two lists - one with sorted coordinates (including the character names) and the second one with only the names. These can be further processed as per your requirements.

I hope this guidance helps! Let us know if you have any additional questions.

Best regards,
Glenn Jocher

**Comment by fababaee** [comment]
How many samples are needed to train yolov8 for text detection on a specific dataset, like ID cards?
I appreciate your help in advance

**Comment by glenn-jocher** [comment]
@fababaee hi, 

The number of samples you need to accurately train YOLOv8 for text detection on a specific dataset like ID cards relies heavily on the complexity and diversity of the data you're dealing with.

In general, the more different examples of ID card text that the model can learn from, the better it is likely to perform. However, it's important to note that it isn't just about quantity – the quality and diversity of the samples matter as well. It's beneficial to have a significant range of variations in the text you're trying to detect (e.g., different fonts, sizes, colors, orientations, lighting conditions, etc.)

As for a specific number, it's challenging to say without knowing more about your specific application. However, as a starting point, you might consider gathering several thousand labeled examples and then continue to iteratively refine your model based on its performance.

Remember that appropriate validation and test sets that are representative of your deployment conditions are also crucial in training a robust model. 

I hope this provides some guidance! Let us know if you have more questions.

Best regards, 
Glenn Jocher

**Comment by TheGalaxyHunter** [comment]
> @FreedomLiX hi there,
> 
> Thanks for bringing the PaddleOCR repo to our attention! Our team here at Ultralytics focuses on the development and maintenance of YOLOv8, an object detection framework based on YOLO, rather than OCR. As such, we don't have any direct experience with PaddleOCR.
> 
> That being said, we welcome and encourage collaboration and contributions from the open-source community. If PaddleOCR requires object detection capabilities, YOLOv8 could be a viable option for integration. However, I would recommend diving into specific details to determine if it's a good fit.
> 
> I hope this provides some insight, and please let me know if you have any further questions or concerns!
> 
> Best regards, Glenn Jocher

The PaddleOCR has a detection model which detects text and then applies recognition using a separate model, I feel the detection model of PaddleOCR can be replaced with YOLOv8 model for a better text detection.

**Comment by BekzatAbdilamituulu** [comment]
Im tryin use easycor for reading licesnce plate. But plate like this easyocr cannot read left litle section character. How can i read this how can i annotate and train model. I trained model for lisence plate detection with yolo. Now i need read text on like this licence plate.
![p](https://github.com/ultralytics/ultralytics/assets/104716068/e50d5c08-82df-403e-ae2f-daca0c45348a)

**Comment by monkeycc** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/main/README_en.md
PaddleOCR

@BekzatAbdilamituulu

**Comment by monkeycc** [comment]
YOLOv8 OCR
Are you considering launching YOLOv8 OCR
@glenn-jocher

**Comment by glenn-jocher** [comment]
@monkeycc hi there,

Currently, we don't have plans to launch a YOLOv8 OCR-specific model. YOLOv8 is primarily designed for object detection tasks, including text or character detection within broader images, but not specifically for optical character recognition (OCR).

For OCR tasks, after detecting text regions with YOLOv8, you might consider coupling it with a dedicated OCR model like Tesseract or the newer deep learning-based models to handle character recognition.

We're always open to exploring new features based on community feedback, so thank you for your suggestion!
