### ISSUE TITLE
Extract the correct output

### ISSUE THREAD

**Issue by BruceUBC** [ultralytics/ultralytics#3015]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,
I am doing an object detection task using Yolov8. However, the output gives multiple predictions on a certain object in the image. How can I extract the prediction with only the highest confidence level from the output? I really appreciate any help you can provide.

**Comment by glenn-jocher** [comment]
@BruceUBC hello,

Thank you for reaching out. To extract the prediction with the highest confidence level from the output, you can sort the detections based on their confidence levels and then take the first detection. 

Assuming you are using the `detect()` method provided by the `models/YOLOv8.py` file in our GitHub repository, the output is a list of size `(batch_size, number_of_detections, 6)` where the last dimension represents `(x,y,w,h,conf,label)`. You can sort this list by the confidence levels by using the following Python code:

```python
detections = model.detect(images)  # images is a list of PIL images
for i, detection in enumerate(detections):
    detections[i] = detection[detection[:, 4].argsort(descending=True)] # sort detections by confidence
```

Here, we use the `argsort()` function with the `descending` parameter to sort the detections in descending order, based on the 5th index of the last dimension, which contains the confidence levels. Finally, we replace the original detection results with the sorted detection results.

After sorting the detections, you can take the first detection for each image in the batch, which will have the highest confidence level, by using the following Python code:

```python
best_detections = []
for detection in detections:
    best_detections.append(detection[0])
```

Here, we take the first element of each detection in the sorted list, which will contain the highest confidence level. The `best_detections` list will contain the best detection results for each input image.

Let me know if that answers your question.

**Comment by glenn-jocher** [comment]
Hello @BruceUBC, 

Thank you for your question. Yes, the proposed method of extracting the prediction with the highest confidence level can be used for images with multiple objects. Suppose there are two objects in an image and the model gives three predictions. In this case, you would have three detection results, each containing `(x,y,w,h,conf,label)` for a different object. 

By using the sorting method described earlier, you can sort each detection result by the confidence levels in descending order and then take the first detection result for each object. This will give you the two best detection results for the two objects in the image.

If you have any more questions or need further assistance, please don't hesitate to ask!

Best regards.
