### ISSUE TITLE
JSON of detections in video

### ISSUE THREAD

**Issue by varungupta31** [ultralytics/ultralytics#3017]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there an in-built way to create a JSON file containing detections in the video at frame level?

### Additional

If there is, please guide me through it.

Thanks.

**Comment by pderrenger** [comment]
@varungupta31 hi there!

Yes, YOLOv8 supports the generation of a JSON file containing detections in a video at the frame level. To achieve this, you can use the `--save-json` flag while running the `yolo` command in the Predict mode. This flag will prompt the model to save detections in a user-friendly JSON format.

You can find more information about this feature in the Predict mode documentation under the "Saving Detections" section.

Hope this helps! Let me know if you have any other questions. Cheers!
