### ISSUE TITLE
train pose with contour instead of rectangle

### ISSUE THREAD

**Issue by pax7** [ultralytics/ultralytics#3027]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Would it be possible to train pose with contours instead of rectangles?

### Use case

This should solve the situations when multiple objects are close to each other and a rectangle would eagerly encompass pixels from neighboring objects.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@pax7 well yes, that's the pose+segment idea we'd discussed, but even the segment models internally use box predictions for the mask matrix multiplication part of the segmentation (to develop segments only inside their predicted boxes), and then also for NMS.
