### ISSUE TITLE
Error in CreateMatrix when no detections are found

### ISSUE THREAD

**Issue by Mateo-EBA** [ultralytics/ultralytics#3028]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Validation

### Bug

In line 256 of file "ultralytics/yolo/utils/metrics.py", in case no detections where found, that "for loop" goes through each labels row.

I think the very next line should use "gc[0]" instead of only "gc".

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@Mateo-EBA can you provide a reproducible example? Thanks!

**Comment by glenn-jocher** [comment]
@Mateo-EBA I'm adding a non-reproducible tag to this bug report for now, but if you have a reproducible example please let us know.
