### ISSUE TITLE
Why is the module ultralytics not found?

### ISSUE THREAD

**Issue by dmddmd** [ultralytics/ultralytics#303]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In a conda environment with Python 3.8.15 I did `pip install ultralytics` and

    successfully installed ...,ultralytics-8.0.4

But when running `from ultralytics import YOLO` , it throws

    ModuleNotFoundError: No module named 'ultralytics'

**Comment by AyushExel** [comment]
@dmddmd are you on windows. This might be a windows env problem. Can you please confirm if you're seeing this issue with all libraries installed in your env or just ultralytics. Thanks!

**Comment by dmddmd** [comment]
@AyushExel yes, I am on Win11.  pip install and import matplotlib works.
pip install translate is successfull but importing it gives Module Not Found Error.

**Comment by glenn-jocher** [comment]
Windows CI is green, i.e. see https://github.com/ultralytics/ultralytics/actions/runs/3904409880/jobs/6670154566

**Comment by glenn-jocher** [comment]
CI uses Git clone method, then `pip install .` i.e.:

```python
# Git clone method (for development)
!git clone https://github.com/ultralytics/ultralytics
%cd ultralytics
%pip install -qe .
```

**Comment by dmddmd** [comment]
@glenn-jocher I tried that, but  pip install -e . gives
    ERROR: file:///.../ultralytics does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

Than I did
`%cd ..` and ran` pip install -e` again and it 
    Successfully installed ... ultralytics-8.0.5..

But I still get the ModuleNotFoundError
--------------------------------------------------------------------

I also tried 
`%pip install -qe ultralytics` like in the tutorial.ipynb
It throws:
    ERROR: ultralytics is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

**Comment by tfaehse** [comment]
Any chance your python/pip aliases are messed up? To verify:
- `where python` to check which python env is used (the first result)
- `where pip` to check which pip executable is used
If these two don't match, you're installing the package into another environment. An easy fix would be to specify which pip to use, e.g. by replacing pip with `python -m pip` or passing the full path.

**Comment by dmddmd** [comment]
@tfaehse  thanks for the suggestion, they match ...
