### ISSUE TITLE
Modifying the YOLO Prediction code to Blur region

### ISSUE THREAD

**Issue by varungupta31** [ultralytics/ultralytics#3034]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Where exactly in the code is the model creating the bounding boxes for a video?
and, How can I blur the region (say Guassian Blur) instead of the marking the box?

### Additional

I'm using the CLI interface

`yolo predict`

**Comment by Laughing-q** [comment]
@varungupta31 hi! here's where we plot bboxes.
https://github.com/ultralytics/ultralytics/blob/8940a27bdb26895f09a1554514a9a46312aa89c3/ultralytics/yolo/engine/results.py#L235
However I think in your case using python api might be more convenient without modifying source code, I assume you just need original image and the predicted bboxes then you can blur the region. Something like this:
```python
from ultralytics import YOLO
import torch

model = YOLO("yolov8n.pt")
for r in model.predict(stream=True):
    bboxes = r.boxes.xyxy.to(torch.int32).tolist()  # get predicted bboxes
    im = r.orig_img
    for b in bboxes:
        x1, y1, x2, y2 = b
        region = im[y1:y2, x1:x2]  # get region area
        # then you can blur the area here...
```
