### ISSUE TITLE
Why is there no confidence loss in yolov8 models

### ISSUE THREAD

**Issue by Gogh-123** [ultralytics/ultralytics#3039]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I think one of the essence of yolo object detection is objectness loss, but it was cancelled in yolov8, I wonder why?
 And without this loss calculation, how can bbox conf be obtained when predicting.

**Comment by glenn-jocher** [comment]
Hello @zcj7777, thank you for your interest in YOLOv8. YOLOv8 is based on the original YOLOv3 and shares many similarities. However, there are significant differences in their loss functions and training techniques. In YOLOv8, we have replaced the objectness loss with several different losses, including a focal loss, a class loss, and intensity loss. We found that this approach improved overall performance and reduced false positives in high-density scenarios. 

Regarding the bbox confidence, YOLOv8 uses several techniques, including non-maximum suppression and anchor-based scaling, to predict the confidence of candidate bounding boxes. These techniques help to improve localization accuracy and enhance the detection performance of bounding boxes.

I hope this answers your questions! Please let us know if you have any more.

**Comment by Gogh-123** [comment]
> Hello @zcj7777, thank you for your interest in YOLOv8. YOLOv8 is based on the original YOLOv3 and shares many similarities. However, there are significant differences in their loss functions and training techniques. In YOLOv8, we have replaced the objectness loss with several different losses, including a focal loss, a class loss, and intensity loss. We found that this approach improved overall performance and reduced false positives in high-density scenarios.
> 
> Regarding the bbox confidence, YOLOv8 uses several techniques, including non-maximum suppression and anchor-based scaling, to predict the confidence of candidate bounding boxes. These techniques help to improve localization accuracy and enhance the detection performance of bounding boxes.
> 
> I hope this answers your questions! Please let us know if you have any more.
I get it, thank you.

**Comment by Zephyr69** [comment]
Although this loss setup improved overall AP, it also led to much more false negatives in my experiments. In many practical scenarios, background false negatives are much more of a hard "no" than anything else.

Breaking the alignment in TAL assignment can alleviate this problem, but not to a significant degree, and it also decreases overall AP.

This is why I haven't switched to yolov8 for deployment.

**Comment by Laughing-q** [comment]
@Gogh-123 we currently use the predicted cls score in v8 as the `objectness` in v5.

**Comment by Gogh-123** [comment]
I get it, thank you.

**Comment by glenn-jocher** [comment]
@Zephyr69 you're welcome! If you have any further questions about YOLOv8 or anything related to object detection, feel free to ask. We are always happy to help and support the community.
