### ISSUE TITLE
Conda integration

### ISSUE THREAD

**Issue by dmddmd** [ultralytics/ultralytics#304]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

It would be nice to have the ability of ` conda install ultralytics`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@dmddmd thanks for the suggestion. If you have experience creating package for conda forge could please help us by starting a PR for what we need? Thanks!

**Comment by glenn-jocher** [comment]
@dmddmd I've opened up a call for community help in implementing this in #1622. If you can help that would be great!

**Comment by glenn-jocher** [comment]
@dmddmd conda support is now available!! See https://docs.ultralytics.com/quickstart :)

**Comment by nadinator** [comment]
Is ultralyticsplus also getting conda support?

**Comment by glenn-jocher** [comment]
@nadinator thank you for your inquiry. At the moment, conda support is only officially provided for the Ultralytics YOLOv8 repository. As for UltralyticsPlus, conda support is not officially available yet; however, we're always open to community contributions. If there are enough requests from users like yourself or if someone submits a pull request, this could certainly be considered for future implementation. We appreciate your input and your patience as we continue to make updates and improvements to our repositories!
