### ISSUE TITLE
Yolov8 detection and tracking with webRTC?

### ISSUE THREAD

**Issue by uzumakinaruto19** [ultralytics/ultralytics#3042]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Has anyone tried implementing yolov8 for both detection and tracking with webRTC, I have a few doubts, is there any repo that might help?

**Comment by glenn-jocher** [comment]
@uzumakinaruto19 hello! While we do not have any specific examples for implementing YOLOv8 for detection and tracking with webRTC, YOLOv8 should work well alongside webRTC. 

You can access the outputs of YOLOv8 detections as JSON or image annotations, which could easily be passed to the webRTC clients to visualize or send to other systems for tracking purposes.

If you have any more specific questions or doubts, feel free to ask and we'll do our best to help!

**Comment by uzumakinaruto19** [comment]
I was able to do that  --Thanks for the help

here is my code for detection and tracking

`import os
import torch
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="0"
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
import numpy as np
import json
from ultralytics import YOLO
model = YOLO('yolov8n.pt')
#@profile
def main_func(input_data,frame):

    global model, jpeg, ckpt_path_from_ultralytics

    if 'ignore' in input_data:
        return "ignore"
    else:

        input_data = json.loads(input_data)

        #results= model.predict(frame, imgsz=1080, conf_thres=0.5, iou_thres=0.5)
        results= model.track(frame, imgsz=1088, classes=0,tracker="bytetrack.yaml")
        tracker_id = results[0].t.cpu().numpy()
        print(tracker_id)
        boxes = results[0].boxes.cpu().numpy()

        if isinstance(boxes, list):
            boxes = np.array(boxes)
            boxes = boxes.astype("int")

        #store the boxes in a dictionary
        new_box = boxes.xyxy
        new_box = new_box.astype("int").tolist()
          
        # i=0
        # while i < len(new_box):
        #   new_box[i][3] = new_box[i][3] + new_box[i][1]
        #   new_box[i][2] = new_box[i][2] + new_box[i][0]
        #   i=i+1
        #cv2.rectangle(frame, new_box[:2], new_box[2:], (0,255,0), 2) 
        output = {
                  'frame_index':input_data['frame_index'],
                  'time_stamp':input_data['time_stamp'],
                  'detections':new_box,
                  'demo_run':input_data['demo_run']}

        return output

`
The issue I'm facing is the stream seems to have lesser quality compared to the RTSP stream I'm passing and the bounding box is drawn somewhere else, I think its an issue with resizing, the input stream is 1080p (24fps), any suggestions how to go with this? 

and how do I get the tracker id when using model.track here? when I print it doesn't have any ids, or  am I doing it correctly?

**Comment by glenn-jocher** [comment]
@uzumakinaruto19 congratulations on successfully implementing detection and tracking with YOLOv8! Regarding your two questions:

1. As for the lower quality of the stream and the misaligned bounding boxes, it is possible that these issues are related to the resizing of your frames. You might want to experiment with different image sizes (using the `imgsz` parameter) to find the optimal size for your frames. Additionally, double-check that your input frames are sized correctly and consistently. 

2. Regarding the tracker id, the `bytetrack`-based tracker used in `YOLOv8` is a deep SORT-like method that assigns and tracks detected objects across frames based on their similarities. The output of the tracker is a list of `Track` objects, one for each detected object that is being tracked. The `Track` object contains information such as the object's class, its current bounding box coordinates, and its track id. To access the track id of an object, you can use the `tracker_id` attribute of the `Track` object. In your code snippet, you can try uncommenting the `tracker_id` line (which currently is commented out) to print the track id for each detected object. 

I hope this helps! Let us know if you have any further questions or issues.

**Comment by glenn-jocher** [comment]
@uzumakinaruto19 hello! One possible solution to your issue is to keep track of the already assigned IDs and ensure that a new ID is only assigned to an object if it hasn't been assigned to any other object before. 

One way you could implement this is by storing all the assigned IDs in a list, and then checking if an ID is already in the list before assigning it to a new object. If the ID is already in the list, simply skip it and assign the next available ID to the object.

Here's some example code to illustrate this approach:

```
def process_frame(input_data, frame, line_counter_1, line_counter_2, line_counter_3, line_annotator, box_annotator):
    ...
    if results.boxes.id is not None:
        if not hasattr(process_frame, 'tracker_ids'):
            process_frame.tracker_ids = []
        new_tracker_ids = []
        for tracker_id in results.boxes.id.cpu().numpy().astype(int):
            if tracker_id in process_frame.tracker_ids:
                # ID already assigned, get next available ID
                new_id = max(process_frame.tracker_ids) + 1
            else:
                # Assign current ID to this object
                new_id = tracker_id
            # Add new ID to list of assigned IDs
            process_frame.tracker_ids.append(new_id)
            new_tracker_ids.append(new_id)
        ...
```

In this example, if an object's ID is already in the `process_frame.tracker_ids` list, the code gets the next available ID by taking the maximum assigned ID so far and adding 1 to it. If the ID is not already assigned, it is simply assigned to the object and added to the list of assigned IDs.

I hope this helps! Let me know if you have any further questions or issues.

**Comment by uzumakinaruto19** [comment]
hi

`import cv2
import numpy as np
from ultralytics import YOLO
import supervision as sv
from typing import Dict
from counter import LineZone

frame_index = 0
def main(input_data, frame, line_counter_1, line_counter_2, line_counter_3, zone):

    global model, frame_index
    

    input_data = {
            'frame_index': frame_index,
            'time_stamp': 0,  # You can replace 0 with an appropriate timestamp
            'demo_run': False
        }

    model = YOLO("yolov8n.pt")




    for result in model.track(frame, classes=0, imgsz= 1980, show=False, stream=True, persist=True,
                            agnostic_nms=True, tracker="bytetrack.yaml"):
        
        # frame = result.orig_img
        detections = sv.Detections.from_yolov8(result)

        if result.boxes.id is not None:
            detections.tracker_id = result.boxes.id.cpu().numpy().astype(int)
        else:
            detections.tracker_id = np.array([])
            detections.conf = np.array([])
            detections.xyxy = np.array([])
    


        new_ids = detections.tracker_id.astype(int).tolist()
        print(new_ids)
        new_box = detections.xyxy.astype(int).tolist()
        print(new_box)
        frame_index += 1`


so in this code, if i use any video or stream directly the id is getting generated is unique and appending, when I am using 'frame' which getting generated from another Python file which streams sends the frame to the detection file and gets back the output(ids, bbox coordinates etc) but the ids getting generated aren't unique but just [1,2,3] like it start from 1 always,  even if a new object enter the frame its gets the ID [1]only  but should have been [4]
