### ISSUE TITLE
CoreML vs Pytorch input size mismatch

### ISSUE THREAD

**Issue by lukasugar** [ultralytics/ultralytics#3048]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I've ran training of `yolov8` for object detection with `imgsz=640`. That should resize the input image's longer side to be 640, while keeping the aspect ratio (source: https://github.com/ultralytics/ultralytics/issues/1658). That means that the input images end up being e.g. 640 x 360, 640 x 640, 400 x 640...

When this model is converted to CoreML, it requires strict input size: 640 x 640:
<img width="499" alt="image" src="https://github.com/ultralytics/ultralytics/assets/22435018/c06ac689-7379-4950-800b-8ee37a4b6009">

What's the best way to resize/preprocess the image so that the 640x640 version has the best possible results?

Simply resizing the image to 640x640 worsens the predictions a lot. I'll try resizing the image while keeping the original aspect ratio, and padding the rest of the image. But I'd like to hear if someone has already tried any of this!

**Comment by lukasugar** [comment]
I found a workable solution:
- Use `LetterBox` transformation to preprocess the image: https://github.com/ultralytics/ultralytics/blob/8940a27bdb26895f09a1554514a9a46312aa89c3/ultralytics/yolo/data/augment.py#LL549C5-L549C49
- Feed the preprocessed image to the CoreML model
- The results are almost the same as in Pytorch!

Caveat:
- need to write transformations to convert results back to the original image.

**Comment by glenn-jocher** [comment]
@lukasugar thank you for sharing your solution! Using the `LetterBox` transformation to preprocess your image while keeping the original aspect ratio is a great way to resize the image to 640x640 as required by CoreML without worsening the predictions. Another important thing to consider when using this approach is to properly convert the results back to the original image. If you have any further questions or concerns, don't hesitate to ask!
