### ISSUE TITLE
about mosaic augment

### ISSUE THREAD

**Issue by 523997931** [ultralytics/ultralytics#3049]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hello,
recently i try to train a seg model for seg car, and i used the mosaic augment, but I found that in the save pic (train_batch0.jpg), 
<img width="185" alt="3B755A77-6E4D-4d1d-8364-96CF1497CBBA" src="https://github.com/ultralytics/ultralytics/assets/49772078/d161fb68-1463-436c-99af-fa57d852dcde">
and on the left side, there is a label that is too small to make sense, so i wonder if remove this label is better for trainning.

**Comment by Laughing-q** [comment]
@523997931 hi, the function `remove_zero_area` there is to remove zero areas after mosaic, but the image you see is after mosaic and `RandomPerspective`. And in `RandomPerspective` we filter bboxes by function `box_candidates`.
https://github.com/ultralytics/ultralytics/blob/8940a27bdb26895f09a1554514a9a46312aa89c3/ultralytics/yolo/data/augment.py#L471
you might want to update some args there manually, like `wh_thr`, `ar_thr`.

**Comment by 523997931** [comment]
> @523997931 hi, the function `remove_zero_area` there is to remove zero areas after mosaic, but the image you see is after mosaic and `RandomPerspective`. And in `RandomPerspective` we filter bboxes by function `box_candidates`.
> 
> https://github.com/ultralytics/ultralytics/blob/8940a27bdb26895f09a1554514a9a46312aa89c3/ultralytics/yolo/data/augment.py#L471
> 
> 
> you might want to update some args there manually, like `wh_thr`, `ar_thr`.

I try to set the wh_thr in my code ,and it work well, thank you for your reply!!

**Comment by glenn-jocher** [comment]
@523997931 you're welcome! I'm glad to hear that setting the `wh_thr` in your code helped. If you have any further questions or issues, feel free to ask. We're always here to help. Happy training with YOLOv8!

**Comment by aiakash** [comment]
@Laughing-q setting higer thresh it will remove this? smaller size image? im getting loys of false in segmention ,idk matbe this mosic augmention? bcz its taking images with very less size,not clear visible

**Comment by Laughing-q** [comment]
@aiakash yeah the `wh_thre` and `ar_thre` like I talked about above.https://github.com/ultralytics/ultralytics/issues/3049#issuecomment-1579739303

**Comment by aiakash** [comment]
@Laughing-q yes i understood,mt q is should i put higher values or lower values? do remove this lables

**Comment by Laughing-q** [comment]
@aiakash higher values.

**Comment by aiakash** [comment]
@Laughing-q 

```
git clone https://github.com/ultralytics/ultralytics
cd ultralytics
pip install -e .

```


i need to clone repo ,i was using pip install ultralytics,but in order to reflect this changes need to clone repo right,


after cloning should i run the same commands to train,test the code?

cd ultralytics/ 
```
yolo train data=coco128.yaml model=yolov8n.pt epochs=10 lr0=0.01

```

so it will reflect whatever changes i do in my code right?

**Comment by Laughing-q** [comment]
@aiakash yes, you can modify the code as you want in `ultralytics/` folder.

**Comment by aiakash** [comment]
@Laughing-q i tried different values for this,no any impact, images is as its for all values,

i cloned the repo ,now inside ultralytics/

tried to run below command
```
# Train YOLOv8n on COCO128 for 3 epochs
!yolo train model=yolov8n.pt data=coco128.yaml epochs=6 imgsz=640
```


<img width="504" alt="image" src="https://github.com/ultralytics/ultralytics/assets/126226282/1df8ef05-b336-4fe2-bf2c-e7eb38706a29">

**Comment by Laughing-q** [comment]
@aiakash I just tried to modify `wh_thr` from 2 to 20, and it does remove the objects with height or width less than `20`:
`wh_thr=2`:
![image](https://github.com/ultralytics/ultralytics/assets/61612323/b46706de-35b0-428a-a15a-9c32df1ded23)
`wh_thr=20`:
![image](https://github.com/ultralytics/ultralytics/assets/61612323/8eec41cc-f9da-41a5-97db-1208f17b0bd3)

**Comment by glenn-jocher** [comment]
@aiakash the `wh_thr` parameter is used to remove small objects from the mosaic images during augmentation. However, if your images have a lot of small objects, setting a high value for `wh_thr` can potentially remove important information that the model needs to learn from. In such cases, you can try adjusting the `wh_thr` parameter to a lower value, such as `35`, like you did, to keep more small objects in the mosaic image. 

If the small objects still pose a problem during training and inference, you can try resizing your original images to have larger dimensions, which can help the model better detect and classify smaller objects. Alternatively, you can also try other augmentation techniques such as random cropping and flipping, which can help introduce more diversity in your training data, and improve the model's ability to generalize to new unseen data with small objects.

I hope this helps! Let me know if you have any more questions.

**Comment by wcyjerry** [comment]
> @aiakash the `wh_thr` parameter is used to remove small objects from the mosaic images during augmentation. However, if your images have a lot of small objects, setting a high value for `wh_thr` can potentially remove important information that the model needs to learn from. In such cases, you can try adjusting the `wh_thr` parameter to a lower value, such as `35`, like you did, to keep more small objects in the mosaic image.
> 
> If the small objects still pose a problem during training and inference, you can try resizing your original images to have larger dimensions, which can help the model better detect and classify smaller objects. Alternatively, you can also try other augmentation techniques such as random cropping and flipping, which can help introduce more diversity in your training data, and improve the model's ability to generalize to new unseen data with small objects.
> 
> I hope this helps! Let me know if you have any more questions.

Hi, my understanding from codes. modify wh_thr won't ignore small object after mosaic, just small object after random perspective. But sometimes one object is big while it may get truncated after mosaic, maybe only 5% of it preserved, is there anything to avoid this?

**Comment by glenn-jocher** [comment]
@wcyjerry hello,

The `wh_thr` parameter indeed does not ignore small objects after mosaic, but as you correctly identified, it helps in dealing with small objects following the application of random perspective transformations.

As for your question about truncated objects following the mosaic augmentation - at this point, the code does not explicitly account for that. Sometimes, parts of objects may indeed get truncated in the mosaic environment - it's a possibility when randomly combining four images. While this can sometimes have a noticeable impact on performance, especially with larger objects, it's an inherent part of the mosaic augmentation technique. 

Decreasing the rate of truncation might be possible by tweaking the specific parameters of the mosaic augmentation, but it could also potentially reduce the randomness and diversity introduced by the augmentation, which is one of its main advantages.

I hope this explanation clarifies your question, and thank you for your interest in the YOLOv8 project.
