### ISSUE TITLE
Onnx prediction very slow compared with .pt

### ISSUE THREAD

**Issue by Fvegini** [ultralytics/ultralytics#3052]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I trained a yolov8 on a Amazon Sagemaker Notebook with GPU, then exported the model do .onnx and downloaded on my VM to test.
The VM only has CPU and is a Ubuntu one.

I created a new python env and installed the lastest ultralytics version.

I tried to run the onnx model with cv2 library but got some errors, after some research I could run in disabling the Winograd stuff.
But the speed was terrible slow (46.8s)
I did a test with yolo predict and the complete time was 20.8s - But the image processing time seems to be like 3~4s.

What I am doing wrong to get this awfull time with the onnx model?

![Yolov8 Speed](https://github.com/ultralytics/ultralytics/assets/32243959/170f0b43-9166-4a35-aa18-bc95127b5e2e)

### Additional

Edit:

I dug it a little and found a example with a library called onnxruntime.

Using it to run the model instead of the cv2 reduced the time to 6~7s, still kinda slow, but waay faster than cv2.

**Comment by glenn-jocher** [comment]
@Fvegini hello! 

Thank you for reaching out and providing detailed information regarding your inquiry!

It is not uncommon for `.onnx` models to perform slower than `.pt` models on CPU due to various optimizations made in the PyTorch inference. We do recommend using the `onnxruntime` package for running `.onnx` models for optimal performance instead of using OpenCV. This may reduce the time taken for inference as seen in your updated test.

Additionally, we recommend experimenting with the batch size to see if that improves performance. Also, it is important to note that the performance of the `.onnx` model is dependent on the hardware's compute capability and configuration. 

Please let us know if you have any further questions. We are happy to help!

**Comment by CedricLienhard** [comment]
Hello, 

Facing a similar issue here: when I perform inference with the .pt model on CPU, it runs at around 0.15s. However, when I perform inference with the .onnx model on CPU, it runs at around 0.4s, which is more than 2x slower and quite annoying for deployment. 

I tried the different optimizations proposed here: [https://docs.ultralytics.com/modes/export/#usage-examples](url) but none of them really helped decrease the inference time with the .onnx model.

The same page also mentions _Gain up to 5x GPU speedup with TensorRT and 3x CPU speedup with ONNX or OpenVINO._, which is quite the opposite of what I'm experiencing. 

Do you have any recommendation for improved performance on CPU with ONNX or any other library ?

**Comment by glenn-jocher** [comment]
Hello @CedricLienhard,

Thank you for reaching out and sharing your experience. I understand how frustrating it can be to encounter performance issues during deployment.

To address the slower inference times with the `.onnx` model on CPU, here are a few recommendations that might help improve performance:

1. **Use ONNX Runtime with Optimization**:
   Ensure you are using the `onnxruntime` package, which is optimized for running ONNX models. You can install it via pip:
   ```bash
   pip install onnxruntime
   ```
   Then, you can run your inference using ONNX Runtime as follows:
   ```python
   import onnxruntime as ort
   import numpy as np

   # Load the ONNX model
   ort_session = ort.InferenceSession("model.onnx")

   # Prepare input data
   input_data = np.random.randn(1, 3, 640, 640).astype(np.float32)

   # Run inference
   outputs = ort_session.run(None, {"input": input_data})
   ```

2. **Enable FP16 Precision**:
   If your hardware supports it, enabling FP16 precision can significantly speed up inference. You can export your model with FP16 precision:
   ```bash
   yolo export model=yolov8n.pt format=onnx half=True
   ```

3. **OpenVINO Optimization**:
   OpenVINO can provide substantial speedups on Intel hardware. You can export your model to OpenVINO format and use the OpenVINO runtime for inference:
   ```bash
   yolo export model=yolov8n.pt format=openvino
   ```
   For more details on using OpenVINO, please refer to our [OpenVINO Integration Guide](https://docs.ultralytics.com/integrations/openvino/).

4. **Batch Size Adjustment**:
   Experiment with different batch sizes to see if it improves performance. Sometimes, processing multiple images in a batch can be more efficient.

5. **Model Simplification**:
   Simplifying the model graph during export can sometimes help:
   ```bash
   yolo export model=yolov8n.pt format=onnx simplify=True
   ```

If the issue persists, please provide a minimum reproducible example as outlined [here](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us better understand the problem and provide more targeted assistance.

We appreciate your patience and are here to help you achieve the best performance for your deployment. 🚀

**Comment by CedricLienhard** [comment]
Hi @glenn-jocher, 

Thanks for the feedback. If I understand well, you recommend loading the model with ONNX directly:
`onnx_model = ort.InferenceSession("model.onnx")` 

rather than using YOLO's built-in method:
`onnx_model = YOLO("model.onnx")`

Is that correct? why not use the yolo built-in method which directly takes care of all the post-processing steps ?

**Comment by glenn-jocher** [comment]
Hello @CedricLienhard,

Thank you for your follow-up question! 😊

Yes, you are correct that using `onnxruntime` directly can sometimes offer more control and potentially better performance for specific use cases. However, the built-in YOLO method is designed to streamline the process by handling all the post-processing steps for you, making it more convenient and user-friendly.

Here's a quick comparison:

### Using ONNX Runtime Directly
```python
import onnxruntime as ort
import numpy as np

# Load the ONNX model
ort_session = ort.InferenceSession("model.onnx")

# Prepare input data
input_data = np.random.randn(1, 3, 640, 640).astype(np.float32)

# Run inference
outputs = ort_session.run(None, {"input": input_data})
```
This method gives you direct access to the ONNX runtime, allowing for more granular control over the inference process.

### Using YOLO's Built-in Method
```python
from ultralytics import YOLO

# Load the ONNX model
onnx_model = YOLO("model.onnx")

# Run inference
results = onnx_model("https://ultralytics.com/images/bus.jpg")
```
This approach simplifies the workflow by managing the preprocessing and post-processing steps, making it easier to integrate into your existing pipeline.

### Why Use YOLO's Built-in Method?
- **Convenience**: Automatically handles preprocessing and post-processing.
- **Consistency**: Ensures consistent results across different environments.
- **Ease of Use**: Reduces the amount of code you need to write and maintain.

If you are experiencing performance issues, it might be worth experimenting with both methods to see which one best suits your needs. Additionally, ensure you are using the latest versions of the packages to benefit from any recent optimizations and bug fixes.

For further optimization tips and detailed guidance, you can refer to our [OpenVINO Integration Guide](https://docs.ultralytics.com/integrations/openvino/).

Feel free to reach out if you have any more questions or need further assistance!

**Comment by trap-fish** [comment]
@CedricLienhard did you manage to get this working as expected? if so, what approach did you take? I'm also experiencing a slower onnx model

**Comment by CedricLienhard** [comment]
@trap-fish I got much better results with the openvino exporting format at the time, which were sufficient for my use case. So I didn't look much further into onnx ...
