### ISSUE TITLE
Multi-GPU Training Validation issue

### ISSUE THREAD

**Issue by Guruprasadhegde** [ultralytics/ultralytics#3057]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I am trying to train yolov8x with my custom dataset. The dataset is huge and it takes around 21 hr to complete one epoch of training which runs as expected. I am using two GPU's to train. After the first epoch validation is performed and this errors out after 1 hr (3600 secs).  
Error Message - 'RuntimeError: [Rank 1] Caught collective operation timeout: WorkNCCL(SeqNum=143, OpType=BROADCAST, TensorShape=[1], Timeout(ms)=3600000) ran for 3600089 milliseconds before timing out.'
During Training:
![grafik](https://github.com/ultralytics/ultralytics/assets/17193101/4f444beb-91c4-466e-b0f1-afd3b13710b2)

During Validation after the first epoch:
![grafik](https://github.com/ultralytics/ultralytics/assets/17193101/6e83da94-180e-4b67-acb6-035e410e153d)
Only GPU 0 seems to be used but the GPU 1 has utilization of 100% all the time (I checked with watch -n 1 nvidia-smi)
From this I am suspecting there is some DDP related issue during validation. Am I doing something wrong? Did anyone face similar issue?

### Environment

I am using the docker image (docker pull ultralytics/ultralytics)

### Minimal Reproducible Example

from ultralytics import YOLO
model = YOLO("yolov8x.yaml")
model.train(data="data/test.yaml", epochs=100,batch=4,imgsz=3288,device=[0,1],pretrained=True)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Guruprasadhegde hello! It seems that you are encountering a timeout issue during validation after the first epoch with your custom dataset while training with two GPUs. This could be related to a DDP issue during validation. 

To address this issue, you can try training with `--sync-bn` or disable NCCL timeout by setting `NCCL_DEBUG=VERSION`. Additionally, you can also try specifying `--local_rank` during the validation, which should ensure that data parallelism is properly established across the two GPUs. 

Please let us know if any of these suggestions address your issue. If they do not, please provide additional information such as logs or any further observations you may have. 

Thank you.

**Comment by Guruprasadhegde** [comment]
@glenn-jocher Sorry but I am a tad confused. As I am training using 
from ultralytics import YOLO
model = YOLO("yolov8x.yaml")
model.train(data="data/test.yaml", epochs=100,batch=4,imgsz=3288,device=[0,1],pretrained=True)

which will intern start the validation process where do you mean I should specify --local_rank during validation.
In your docs (https://docs.ultralytics.com/modes/val/#arguments) argument for device is 0 or 1 or 2 does this mean I cannot start validation using more than one device ? 
![image](https://github.com/ultralytics/ultralytics/assets/17193101/1ea48ce1-53bd-4926-af61-8354074df2ea)

**Comment by glenn-jocher** [comment]
@Guruprasadhegde, I apologize for any confusion. You can pass the `--local_rank` argument during validation by modifying the `val` script in YOLOv8. When running the `val` script, you can pass the argument `--local_rank 0` or `--local_rank 1`, depending on which GPU you want to use.

Regarding the validation process, you can run validation with more than one device by using the `--device` argument followed by a list of GPUs you want to use, such as `--device 0,1`. In your training script, since you have already specified `device=[0,1]`, both GPUs will be used during validation by default.

I hope this clears up any confusion. Please let me know if you have any further questions or concerns.

**Comment by Guruprasadhegde** [comment]
@glenn-jocher Thank you for your previous clarifications! 
I managed to resolve my issue by increasing the timeout value here: https://github.com/ultralytics/ultralytics/blob/29c954a1385815e522f0d94d7144814cc4e6da42/ultralytics/yolo/engine/trainer.py#L201. 
I've noticed that during inference, my training script continues to utilize only a single GPU.

I may be misunderstanding something, but based on these these lines of code:

https://github.com/ultralytics/ultralytics/blob/29c954a1385815e522f0d94d7144814cc4e6da42/ultralytics/yolo/engine/trainer.py#L363
https://github.com/ultralytics/ultralytics/blob/29c954a1385815e522f0d94d7144814cc4e6da42/ultralytics/yolo/engine/trainer.py#L240

It seems to me that regardless of the device argument passed, validation during training always occurs on a single device. Could you please let me know if I am missing something?

**Comment by kaunghtetsan275** [comment]
@Guruprasadhegde hi did you manage to solve validation not using multi GPU? Because I'm facing the same issue. I could train using multi gpu but validation only uses single gpu. please let me know if you found a way to handle this issue.

**Comment by steven1u** [comment]
Hey there! Any news on this issue?

@glenn-jocher Do you think we could run validation across multiple GPUs in the ultralytics code in the future? 

As @Guruprasadhegde mentioned, the `if RANK in {-1, 0}` condition still exists in the trainer.

**Comment by glenn-jocher** [comment]
@steven1u hello! Currently, validation is typically conducted on a single GPU due to the `if RANK in {-1, 0}` condition, which is intended to ensure synchronization and reduce complexity during this phase. While multi-GPU validation isn't supported out-of-the-box at the moment, it's a possibility for future updates. Keep an eye on the repository for any new developments. Thank you for your patience and understanding!
