### ISSUE TITLE
YOLOv8 Classsifier Fine Tuning

### ISSUE THREAD

**Issue by emigomez** [ultralytics/ultralytics#306]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to fine-tune the YOLOv8 classifier in my custom dataset.

I'm trying It with:
`!yolo mode=train task=classify model=yolov8n-cls.pt data=/content/dni_classifier.yaml epochs=3 imgsz=640`

But I'm getting the next error:
```
`Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n-cls.pt to yolov8n-cls.pt...
100% 5.28M/5.28M [00:00<00:00, 62.5MB/s]

Ultralytics YOLOv8.0.5 🚀 Python-3.8.16 torch-1.13.1+cu116 CUDA:0 (Tesla T4, 15110MiB)
yolo/engine/trainer: task=classify, mode=train, model=yolov8n-cls.pt, data=/content/dni_classifier.yaml, epochs=3, patience=50, batch=16, imgsz=640, save=True, cache=False, device=, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=False, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, retina_masks=False, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.1, lrf=0.01, momentum=0.937, weight_decay=5e-05, warmup_epochs=0.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.1, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, hydra={'output_subdir': None, 'run': {'dir': '.'}}, v5loader=False, save_dir=runs/classify/train
Downloading https://ultralytics.com/assets/Arial.ttf to /root/.config/Ultralytics/Arial.ttf...
100% 755k/755k [00:00<00:00, 49.4MB/s]
Overriding model.yaml nc=1000 with nc=3

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.Conv                  [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.Conv                  [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.C2f                   [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.C2f                   [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.C2f                   [256, 256, 1, True]           
  9                  -1  1    334083  ultralytics.nn.modules.Classify              [256, 3]                      
YOLOv8n-cls summary: 99 layers, 1442131 parameters, 1442131 gradients, 3.4 GFLOPs
optimizer: SGD(lr=0.1) with parameter groups 26 weight(decay=0.0), 27 weight(decay=5e-05), 27 bias
Error executing job with overrides: ['mode=train', 'task=classify', 'model=yolov8n-cls.pt', 'data=/content/dni_classifier.yaml', 'epochs=3', 'imgsz=640']
Traceback (most recent call last):
  File "/content/ultralytics/ultralytics/yolo/cli.py", line 56, in cli
    func(cfg)
  File "/usr/local/lib/python3.8/dist-packages/hydra/main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "/content/ultralytics/ultralytics/yolo/v8/classify/train.py", line 151, in train
    model.train(**cfg)
  File "/content/ultralytics/ultralytics/yolo/engine/model.py", line 193, in train
    self.trainer.train()
  File "/content/ultralytics/ultralytics/yolo/engine/trainer.py", line 185, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/content/ultralytics/ultralytics/yolo/engine/trainer.py", line 247, in _do_train
    self._setup_train(rank, world_size)
  File "/content/ultralytics/ultralytics/yolo/engine/trainer.py", line 233, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=rank, mode="train")
  File "/content/ultralytics/ultralytics/yolo/v8/classify/train.py", line 70, in get_dataloader
    loader = build_classification_dataloader(path=dataset_path,
  File "/content/ultralytics/ultralytics/yolo/data/build.py", line 111, in build_classification_dataloader
    dataset = ClassificationDataset(root=path, imgsz=imgsz, augment=augment, cache=cache)
  File "/content/ultralytics/ultralytics/yolo/data/dataset.py", line 194, in __init__
    super().__init__(root=root)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/datasets/folder.py", line 309, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/torchvision/datasets/folder.py", line 145, in __init__
    samples = self.make_dataset(self.root, class_to_idx, extensions, is_valid_file)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/datasets/folder.py", line 189, in make_dataset
    return make_dataset(directory, class_to_idx, extensions=extensions, is_valid_file=is_valid_file)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/datasets/folder.py", line 102, in make_dataset
    raise FileNotFoundError(msg)
FileNotFoundError: Found no valid file for the classes labels. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.`
```

My dni_classifier yaml is:
```
`# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: manipulation_classifier  # dataset root dir
train: train  # train images (relative to 'path') 128 images
val: val  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes
names:
  0: legitimate
  1: manipulate
  2: other`
```
  
And this is the structure of my dataset:
```
-   manipulation_classifier
- ---- train
- -------- images (jpg)
- -------- labels (txt files)
- ---- eval
- -------- images (jpg)
- -------- labels (txt files)
```

This is an example of label.txt: `0 0 0 1 1`

I don't understand this error: FileNotFoundError: Found no valid file for the class labels. `Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp`
Label should be a txt file, right? What I'm doing wrong?

**Comment by AyushExel** [comment]
@emigomez for classification you don't need to pass .yaml files. You can directly set data=dataset_folder. Please give it a try and let us know if the issue persisits

**Comment by s4ki3f** [comment]
it works fine when trying to run training for classification
`from ultralytics import YOLO

model = YOLO('yolov8n-cls.pt')  # load a pretrained YOLOv8n classification model
model.train(data='/content/Cow-Identification-1', epochs=3)  # train the model`

![image](https://user-images.githubusercontent.com/29111757/212220221-b2ce2905-28eb-4bb7-ad62-93f0921175cc.png)

but ,



when I try this, 
`!yolo task=classify mode=train model=yolov8n.pt data='/content/Cow-Identification-1' epochs=3`
it says no labels found

![image](https://user-images.githubusercontent.com/29111757/212220355-00cca0ac-4965-47d8-aa46-43df885172eb.png)

**Comment by Laughing-q** [comment]
@s4ki3f 
> when I try this,
!yolo task=classify mode=train model=yolov8n.pt data='/content/Cow-Identification-1' epochs=3
it says no labels found

hi the `yolov8n.pt` is detection model so it'll raise errors when you're trying to train a classify model but using detection model as pretrained.
you need to use `yolov8-cls.pt`.

**Comment by s4ki3f** [comment]
ow.. thank you.. that is silly of me.. I read the doc but forgot to change it.. Thank you @Laughing-q

**Comment by s4ki3f** [comment]
@Laughing-q , I have a silly question.  why the img_size are different in this two defaults run?

![image](https://user-images.githubusercontent.com/29111757/212227226-433b5844-c8b6-4ba4-93fe-75d812f87c8c.png)

**Comment by Laughing-q** [comment]
@s4ki3f oh that's a log issue I think. The training actually should be trained with `imgsz=224` in both cases you showed.
Thanks for the reporting, actually we're planning to perfect these stuffs of classify task.

**Comment by Laughing-q** [comment]
@AyushExel @glenn-jocher added this to TODO

**Comment by s4ki3f** [comment]
yeah, it is actually 224. It is shows 224 in epochs details

**Comment by emigomez** [comment]
Thank you for your responses!
But I still have an issue running with the python API:

Source code:
```
from ultralytics import YOLO
model = YOLO('yolov8n-cls.pt')  
model.train(data='content/manipulation_classifier', epochs=3)  
model.predict(source='https://ultralytics.com/images/bus.jpg') 
```
Error:
```
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n-cls.pt to yolov8n-cls.pt...
100%
5.28M/5.28M [00:00<00:00, 98.9MB/s]

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-4-2b88e9bf4ce1>](https://localhost:8080/#) in <module>
      6 
      7 # train the model
----> 8 model.train(data='content/manipulation_classifier', epochs=3)
      9 
     10 # evaluate model performance on the validation set

4 frames
/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/model.py in train(self, **kwargs)

/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/v8/classify/train.py in __init__(self, config, overrides)

/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/trainer.py in __init__(self, config, overrides)

/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/configs/__init__.py in get_config(config, overrides)

[/usr/local/lib/python3.8/dist-packages/omegaconf/omegaconf.py](https://localhost:8080/#) in load(file_)
    187 
    188         if isinstance(file_, (str, pathlib.Path)):
--> 189             with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
    190                 obj = yaml.load(f, Loader=get_yaml_loader())
    191         elif getattr(file_, "read", None):

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/configs/default.yaml'
```

While running without the API is not giving me any error:
`!yolo mode=train task=classify model=yolov8n-cls.pt data=/content/manipulation_classifier epochs=3 imgsz=640`

I don't know, but the error may be in the way I build the dataset. I tried different ways, bellow you see the structure dataset for the previous execution:
![image](https://user-images.githubusercontent.com/64838403/212288334-5ca2ac7e-586f-4243-8f30-0e9cec85cb93.png)

**Comment by rmorros** [comment]
I think your path is wrong, missing a '/' at the beginning.
You have model.train(data='content/manipulation_classifier', epochs=3) but in the working command line is
'/content/manipulation_classifier'

**Comment by NohaAhmad** [comment]
I have a problem with the fine-tuned classification model yolov8n-cls
The top probability logged doesn't match the top probability obtained from the results 

**which one is the correct one ? and why there's a conflict ?**
 
![yolo_issue](https://user-images.githubusercontent.com/45567574/224413631-222f5f09-81aa-4a97-8eab-9203fa74fac8.png)

**Comment by KarthikGogisetty07** [comment]
Exception in thread Thread-35:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/threading.py", line 69, in run
    reraise(*_capture_exception())
  File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/_compat.py", line 60, in reraise
    raise value
  File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/ultralytics/hub/utils.py", line 116, in func
    m = r.json().get('message', 'No JSON message.')
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)


getting this warning after the training is done

**Comment by glenn-jocher** [comment]
> I have a problem with the fine-tuned classification model yolov8n-cls The top probability logged doesn't match the top probability obtained from the results
> 
> **which one is the correct one ? and why there's a conflict ?**
> 
> ![yolo_issue](https://user-images.githubusercontent.com/45567574/224413631-222f5f09-81aa-4a97-8eab-9203fa74fac8.png)

@NohaAhmad this is because you have an older version of ultralytics that had a double-softmax bug. This has been fixed a while ago, so your package must be several weeks old at least. Please update with `pip install -U ultralytics` and the bug should be fixed. If not then please train a new model and the new model will work correctly.

**Comment by glenn-jocher** [comment]
> Exception in thread Thread-35: Traceback (most recent call last): File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner self.run() File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/threading.py", line 69, in run reraise(*_capture_exception()) File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/_compat.py", line 60, in reraise raise value File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/threading.py", line 67, in run return old_run_func(self, *a, **kw) File "/usr/lib/python3.9/threading.py", line 917, in run self._target(*self._args, **self._kwargs) File "/usr/local/lib/python3.9/dist-packages/ultralytics/hub/utils.py", line 116, in func m = r.json().get('message', 'No JSON message.') File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 900, in json return complexjson.loads(self.text, **kwargs) File "/usr/lib/python3.9/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/usr/lib/python3.9/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
> 
> getting this warning after the training is done

👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub, and if necessary `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
> Exception in thread Thread-35: Traceback (most recent call last): File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner self.run() File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/threading.py", line 69, in run reraise(*_capture_exception()) File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/_compat.py", line 60, in reraise raise value File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/threading.py", line 67, in run return old_run_func(self, *a, **kw) File "/usr/lib/python3.9/threading.py", line 917, in run self._target(*self._args, **self._kwargs) File "/usr/local/lib/python3.9/dist-packages/ultralytics/hub/utils.py", line 116, in func m = r.json().get('message', 'No JSON message.') File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 900, in json return complexjson.loads(self.text, **kwargs) File "/usr/lib/python3.9/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/usr/lib/python3.9/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
> 
> getting this warning after the training is done

@KarthikGogisetty07 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub, and if necessary `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
@s4ki3f @Laughing-q imgsz discrepancy issue is now resolved, removing TODO.
<img width="848" alt="Screenshot 2023-06-17 at 20 49 31" src="https://github.com/ultralytics/ultralytics/assets/26833433/84653884-cb24-49c3-ac47-b4c69696e679">

**Comment by jet-c-21** [comment]
@glenn-jocher I have a similiar question here, when I input my dataset dir like this

```python
results = model.train(
    data=ds_dir,
    # val=True,
    epochs=100,
    imgsz=640,
)
```

```
train: /train_data/AIBR/train-datasets/aibr_sc_dataset_yolov8/train... found 2021 images in 4 classes ✅ 
val: None...
test: None...
Overriding model.yaml nc=1000 with nc=4
```

it said that it cannot find the valid data, but i do have valid dir next to train dir, how to solve this?
