### ISSUE TITLE
Multi-card training error

### ISSUE THREAD

**Issue by 503092317** [ultralytics/ultralytics#3062]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Ultralytics\DDP\_temp_kobdm7j91461358308176.py", line 3, in <module>
    from __main__ import DetectionTrainer
ImportError: cannot import name 'DetectionTrainer' from '__main__' (C:\Users\Administrator\AppData\Roaming\Ultralytics\DDP\_temp_kobdm7j91461358308176.py)
Traceback (most recent call last):
  File "H:\Anaconda3\envs\xzksb\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "H:\Anaconda3\envs\xzksb\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "H:\Anaconda3\envs\xzksb\lib\site-packages\torch\distributed\launch.py", line 260, in <module>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Ultralytics\DDP\_temp_kobdm7j91461358308176.py", line 3, in <module>
    from __main__ import DetectionTrainer
ImportError: cannot import name 'DetectionTrainer' from '__main__' (C:\Users\Administrator\AppData\Roaming\Ultralytics\DDP\_temp_kobdm7j91461358308176.py)
    main()
  File "H:\Anaconda3\envs\xzksb\lib\site-packages\torch\distributed\launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['H:\\Anaconda3\\envs\\xzksb\\python.exe', '-u', 'C:\\Users\\Administrator\\AppData\\Roaming\\Ultralytics\\DDP\\_temp_kobdm7j91461358308176.py', '--local_rank=1', 'task=detect', 'mode=train', 'model=yolov8n.pt', 'data=D:\\LJL\\ultralytics-main\\ultralytics\\datasets\\VisDrone.yaml', 'epochs=100', 'patience=50', 'batch=16', 'imgsz=640', 'save=True', 'save_period=-1', 'cache=False', 'device=1,0', 'workers=8', 'project=None', 'name=None', 'exist_ok=False', 'pretrained=False', 'optimizer=SGD', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'rect=False', 'cos_lr=False', 'close_mosaic=0', 'resume=False', 'amp=True', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'save_hybrid=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'source=None', 'show=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'show_labels=True', 'show_conf=True', 'vid_stride=1', 'line_width=None', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'boxes=True', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=False', 'opset=None', 'workspace=4', 'nms=False', 'lr0=0.01', 'lrf=0.01', 'momentum=0.937', 'weight_decay=0.0005', 'warmup_epochs=3.0', 'warmup_momentum=0.8', 'warmup_bias_lr=0.1', 'box=7.5', 'cls=0.5', 'dfl=1.5', 'pose=12.0', 'kobj=1.0', 'label_smoothing=0.0', 'nbs=64', 'hsv_h=0.015', 'hsv_s=0.7', 'hsv_v=0.4', 'degrees=0.0', 'translate=0.1', 'scale=0.5', 'shear=0.0', 'perspective=0.0', 'flipud=0.0', 'fliplr=0.5', 'mosaic=1.0', 'mixup=0.0', 'copy_paste=0.0', 'cfg=None', 'v5loader=False', 'tracker=botsort.yaml']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "D:/LJL/ultralytics-main/ultralytics/yolo/v8/detect/train.py", line 257, in <module>
    train()
  File "D:/LJL/ultralytics-main/ultralytics/yolo/v8/detect/train.py", line 253, in train
    trainer.train()
  File "D:\LJL\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 187, in train
    raise e
  File "D:\LJL\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 185, in train
    subprocess.run(cmd, check=True)
  File "H:\Anaconda3\envs\xzksb\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['H:\\Anaconda3\\envs\\xzksb\\python.exe', '-m', 'torch.distributed.launch', '--nproc_per_node', '2', '--master_port', '51593', 'C:\\Users\\Administrator\\AppData\\Roaming\\Ultralytics\\DDP\\_temp_kobdm7j91461358308176.py', 'task=detect', 'mode=train', 'model=yolov8n.pt', 'data=D:\\LJL\\ultralytics-main\\ultralytics\\datasets\\VisDrone.yaml', 'epochs=100', 'patience=50', 'batch=16', 'imgsz=640', 'save=True', 'save_period=-1', 'cache=False', 'device=1,0', 'workers=8', 'project=None', 'name=None', 'exist_ok=False', 'pretrained=False', 'optimizer=SGD', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'rect=False', 'cos_lr=False', 'close_mosaic=0', 'resume=False', 'amp=True', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'save_hybrid=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'source=None', 'show=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'show_labels=True', 'show_conf=True', 'vid_stride=1', 'line_width=None', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'boxes=True', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=False', 'opset=None', 'workspace=4', 'nms=False', 'lr0=0.01', 'lrf=0.01', 'momentum=0.937', 'weight_decay=0.0005', 'warmup_epochs=3.0', 'warmup_momentum=0.8', 'warmup_bias_lr=0.1', 'box=7.5', 'cls=0.5', 'dfl=1.5', 'pose=12.0', 'kobj=1.0', 'label_smoothing=0.0', 'nbs=64', 'hsv_h=0.015', 'hsv_s=0.7', 'hsv_v=0.4', 'degrees=0.0', 'translate=0.1', 'scale=0.5', 'shear=0.0', 'perspective=0.0', 'flipud=0.0', 'fliplr=0.5', 'mosaic=1.0', 'mixup=0.0', 'copy_paste=0.0', 'cfg=None', 'v5loader=False', 'tracker=botsort.yaml']' returned non-zero exit status 1.

Process finished with exit code 1

No corresponding files are generated under the folder，like this
“C:\Users\Administrator\AppData\Roaming\Ultralytics\DDP\_temp_kobdm7j91461358308176.py”

### Environment

Ultralytics YOLOv8.0.97  Python-3.8.3 torch-1.7.1 CUDA:1 (NVIDIA GeForce RTX 2080 Ti, 11264MiB)
                                                    CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11264MiB)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by LiangYong1216** [comment]
i have the same question, 
my environments:
python 3.7.10
pytorch: 1.7.0
cuda: 11.0
cudnn: 8.0.3

**Comment by 503092317** [comment]
> 

At present, there is no problem with my single card training, but only with multi-card training will there be an error. Do you have a good solution?

**Comment by 503092317** [comment]
> i have the same question, my environments: python 3.7.10 pytorch: 1.7.0 cuda: 11.0 cudnn: 8.0.3



> i have the same question, my environments: python 3.7.10 pytorch: 1.7.0 cuda: 11.0 cudnn: 8.0.3

At present, there is no problem with my single card training, but only with multi-card training will there be an error. Do you have a good solution?

**Comment by LiangYong1216** [comment]
NO, one gpu training is OK,but mutil-gpu is failed,

**Comment by LiangYong1216** [comment]
i solved this issue by upgrade the python and pytorch:
python=3.8.0
pttorch=1.8.0
numpy=1.24.3
i hope this is useful for you !

**Comment by glenn-jocher** [comment]
@503092317 it seems that you are encountering an error when training YOLOv8 with multiple GPUs. The error message suggests that the subprocess is failing to import the `DetectionTrainer` from the main process. Although you have tried upgrading your Python and PyTorch to versions 3.8.0 and 1.8.0 respectively, this did not solve the problem.

One potential solution for this issue could be to set the `PYTHONPATH` environment variable to include the root directory of your YOLOv8 installation. This can ensure that your subprocess will be able to import the necessary modules. Another common fix is to make sure you're using the same version of PyTorch and Torchvision throughout your training script and your environment.

If neither of these solutions work for you, please share further details that could help us identify the root cause of your issue such as the exact steps to reproduce the problem, the training command, and the training logs.

**Comment by 503092317** [comment]
> @503092317 it seems that you are encountering an error when training YOLOv8 with multiple GPUs. The error message suggests that the subprocess is failing to import the `DetectionTrainer` from the main process. Although you have tried upgrading your Python and PyTorch to versions 3.8.0 and 1.8.0 respectively, this did not solve the problem.
> 
> One potential solution for this issue could be to set the `PYTHONPATH` environment variable to include the root directory of your YOLOv8 installation. This can ensure that your subprocess will be able to import the necessary modules. Another common fix is to make sure you're using the same version of PyTorch and Torchvision throughout your training script and your environment.
> 
> If neither of these solutions work for you, please share further details that could help us identify the root cause of your issue such as the exact steps to reproduce the problem, the training command, and the training logs.
thanks for your help!
i set the PYTHONPATH environment variable to include the root directory of  YOLOv8 installation.    but it
don‘t work.    how to make sure i'm using the same version of PyTorch and Torchvision throughout  training script and  environment?

Ultralytics YOLOv8.0.97  Python-3.8.0 torch-1.8.0+cu111 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11264MiB)
                                                          CUDA:1 (NVIDIA GeForce RTX 2080 Ti, 11264MiB)
yolo\engine\trainer: task=detect, mode=train, model=runs\detect\train0016\weights\last.pt, data=D:\LJL\ultralytics-main\ultralytics\datasets\coco.yaml, epochs=100, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=0, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs\detect\train0016
Running DDP command ['H:\\Anaconda3\\envs\\ljl\\python.exe', '-m', 'torch.distributed.launch', '--nproc_per_node', '2', '--master_port', '56737', 'C:\\Users\\Administrator\\AppData\\Roaming\\Ultralytics\\DDP\\_temp_v_j16u_j2072591437680.py', 'task=detect', 'mode=train', 'model=runs\\detect\\train0016\\weights\\last.pt', 'data=D:\\LJL\\ultralytics-main\\ultralytics\\datasets\\coco.yaml', 'epochs=100', 'patience=50', 'batch=16', 'imgsz=640', 'save=True', 'save_period=-1', 'cache=False', 'device=0', 'workers=8', 'project=None', 'name=None', 'exist_ok=False', 'pretrained=False', 'optimizer=SGD', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'rect=False', 'cos_lr=False', 'close_mosaic=0', 'resume=False', 'amp=True', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'save_hybrid=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'source=None', 'show=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'show_labels=True', 'show_conf=True', 'vid_stride=1', 'line_width=None', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'boxes=True', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=False', 'opset=None', 'workspace=4', 'nms=False', 'lr0=0.01', 'lrf=0.01', 'momentum=0.937', 'weight_decay=0.0005', 'warmup_epochs=3.0', 'warmup_momentum=0.8', 'warmup_bias_lr=0.1', 'box=7.5', 'cls=0.5', 'dfl=1.5', 'pose=12.0', 'kobj=1.0', 'label_smoothing=0.0', 'nbs=64', 'hsv_h=0.015', 'hsv_s=0.7', 'hsv_v=0.4', 'degrees=0.0', 'translate=0.1', 'scale=0.5', 'shear=0.0', 'perspective=0.0', 'flipud=0.0', 'fliplr=0.5', 'mosaic=1.0', 'mixup=0.0', 'copy_paste=0.0', 'cfg=None', 'v5loader=False', 'tracker=botsort.yaml']
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Ultralytics\DDP\_temp_v_j16u_j2072591437680.py", line 3, in <module>
    from __main__ import DetectionTrainer
ImportError: cannot import name 'DetectionTrainer' from '__main__' (C:\Users\Administrator\AppData\Roaming\Ultralytics\DDP\_temp_v_j16u_j2072591437680.py)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Ultralytics\DDP\_temp_v_j16u_j2072591437680.py", line 3, in <module>
    from __main__ import DetectionTrainer
ImportError: cannot import name 'DetectionTrainer' from '__main__' (C:\Users\Administrator\AppData\Roaming\Ultralytics\DDP\_temp_v_j16u_j2072591437680.py)
Killing subprocess 20092
Killing subprocess 17916
Traceback (most recent call last):
  File "H:\Anaconda3\envs\ljl\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "H:\Anaconda3\envs\ljl\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "H:\Anaconda3\envs\ljl\lib\site-packages\torch\distributed\launch.py", line 340, in <module>
    main()
  File "H:\Anaconda3\envs\ljl\lib\site-packages\torch\distributed\launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "H:\Anaconda3\envs\ljl\lib\site-packages\torch\distributed\launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['H:\\Anaconda3\\envs\\ljl\\python.exe', '-u', 'C:\\Users\\Administrator\\AppData\\Roaming\\Ultralytics\\DDP\\_temp_v_j16u_j2072591437680.py', '--local_rank=1', 'task=detect', 'mode=train', 'model=runs\\detect\\train0016\\weights\\last.pt', 'data=D:\\LJL\\ultralytics-main\\ultralytics\\datasets\\coco.yaml', 'epochs=100', 'patience=50', 'batch=16', 'imgsz=640', 'save=True', 'save_period=-1', 'cache=False', 'device=0', 'workers=8', 'project=None', 'name=None', 'exist_ok=False', 'pretrained=False', 'optimizer=SGD', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'rect=False', 'cos_lr=False', 'close_mosaic=0', 'resume=False', 'amp=True', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'save_hybrid=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'source=None', 'show=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'show_labels=True', 'show_conf=True', 'vid_stride=1', 'line_width=None', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'boxes=True', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=False', 'opset=None', 'workspace=4', 'nms=False', 'lr0=0.01', 'lrf=0.01', 'momentum=0.937', 'weight_decay=0.0005', 'warmup_epochs=3.0', 'warmup_momentum=0.8', 'warmup_bias_lr=0.1', 'box=7.5', 'cls=0.5', 'dfl=1.5', 'pose=12.0', 'kobj=1.0', 'label_smoothing=0.0', 'nbs=64', 'hsv_h=0.015', 'hsv_s=0.7', 'hsv_v=0.4', 'degrees=0.0', 'translate=0.1', 'scale=0.5', 'shear=0.0', 'perspective=0.0', 'flipud=0.0', 'fliplr=0.5', 'mosaic=1.0', 'mixup=0.0', 'copy_paste=0.0', 'cfg=None', 'v5loader=False', 'tracker=botsort.yaml']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "D:/LJL/ultralytics-main/ultralytics/yolo/v8/detect/train.py", line 257, in <module>
    train()
  File "D:/LJL/ultralytics-main/ultralytics/yolo/v8/detect/train.py", line 253, in train
    trainer.train()
  File "D:\LJL\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 187, in train
    raise e
  File "D:\LJL\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 185, in train
    subprocess.run(cmd, check=True)
  File "H:\Anaconda3\envs\ljl\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['H:\\Anaconda3\\envs\\ljl\\python.exe', '-m', 'torch.distributed.launch', '--nproc_per_node', '2', '--master_port', '56737', 'C:\\Users\\Administrator\\AppData\\Roaming\\Ultralytics\\DDP\\_temp_v_j16u_j2072591437680.py', 'task=detect', 'mode=train', 'model=runs\\detect\\train0016\\weights\\last.pt', 'data=D:\\LJL\\ultralytics-main\\ultralytics\\datasets\\coco.yaml', 'epochs=100', 'patience=50', 'batch=16', 'imgsz=640', 'save=True', 'save_period=-1', 'cache=False', 'device=0', 'workers=8', 'project=None', 'name=None', 'exist_ok=False', 'pretrained=False', 'optimizer=SGD', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'rect=False', 'cos_lr=False', 'close_mosaic=0', 'resume=False', 'amp=True', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'save_hybrid=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'source=None', 'show=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'show_labels=True', 'show_conf=True', 'vid_stride=1', 'line_width=None', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'boxes=True', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=False', 'opset=None', 'workspace=4', 'nms=False', 'lr0=0.01', 'lrf=0.01', 'momentum=0.937', 'weight_decay=0.0005', 'warmup_epochs=3.0', 'warmup_momentum=0.8', 'warmup_bias_lr=0.1', 'box=7.5', 'cls=0.5', 'dfl=1.5', 'pose=12.0', 'kobj=1.0', 'label_smoothing=0.0', 'nbs=64', 'hsv_h=0.015', 'hsv_s=0.7', 'hsv_v=0.4', 'degrees=0.0', 'translate=0.1', 'scale=0.5', 'shear=0.0', 'perspective=0.0', 'flipud=0.0', 'fliplr=0.5', 'mosaic=1.0', 'mixup=0.0', 'copy_paste=0.0', 'cfg=None', 'v5loader=False', 'tracker=botsort.yaml']' returned non-zero exit status 1.

Process finished with exit code 1
