### ISSUE TITLE
Is contribution feasible?

### ISSUE THREAD

**Issue by sipie800** [ultralytics/ultralytics#3064]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I'm reading the code of ultralytics to deicide if I'm going to make some new models there. However, I've got some obstacles here,

There are two different model code arch in ultralytics.models. One is the old yolov5 stuff, which has quite a complicated desigh IMO. And now the RTDETR is using that arch as well. The other is the code of SAM, which is in a comtemporary code arch for NN models.
The yaml model designing is convenient for an unprofessional user. But it's much more common to write a straight nn.module when build a new model. As a model desigher, I don't want to break a model into pieces and port them into a yaml because that's not necessary and the link between the modules just doesn't work just by writing that yaml.

And writing a model just in torch perspective is becoming more and more common thing for a AI worker as AI develops, it's just like a tool itself. I don't think wrapping a module and releasing it will last forever.

So my question is, are you plainning to use the yaml stuff in following updates ? Or can I make progress by using a torch style model?

**Comment by Zephyr69** [comment]
I don't get what you mean exactly. I think this configuration is compatible with the way you want it to work, isn't it? If there are some complex connections within networks that cannot be achieved in this way (idk if those exist tho), you can write the whole network into one big module, register how the instanitation parameters are passed in yolo,  and set it up in .yaml with just one line.

I've reimplemented/created many backbone/neck/heads from documents or my own over the years under this setup and I think it's great for users of all knowledge levels.

**Comment by glenn-jocher** [comment]
@sipie800 hello! Thank you for your interest in contributing to YOLOv8. Our team understands that different developers may have their own preferences and ways of designing models. While we do use YAML format in our model designing, it is certainly not the only way to contribute to the project. We are happy to review and consider contributions made using a torch-style model as well. In your case, if you prefer to write a model directly using the torch module, we suggest that you submit your contribution that way. Please note that if you choose this method, you will need to register how the instantiation parameters are passed in yolo (tasks.py) and set it up in .yaml with just one line as well. We understand that the process can be complex at times, but we have many users of all knowledge levels who have successfully implemented their own YOLO models, so it is certainly achievable. Thank you again for your interest in contributing to YOLOv8, and we look forward to reviewing your contributions.

**Comment by zhiqwang** [comment]
Just FYI @glenn-jocher @sipie800 , We have previously done similar work on the [yolort](https://zhiqwang.com/yolov5-rt-stack/notebooks/how-to-align-with-ultralytics-yolov5.html) project, where we refactored yolov5's yaml configuration mechanism into the [torchvision](https://github.com/zhiqwang/yolov5-rt-stack/blob/main/yolort/models/darknetv6.py) [style](https://github.com/zhiqwang/yolov5-rt-stack/blob/main/yolort/models/yolo.py), and the modified network was still able to load the checkpoints trained from yolov5.

**Comment by glenn-jocher** [comment]
Hello @oakaigh, thank you for sharing your project yolort with us. We appreciate your work and the effort you have put into it. We understand that you have refactored yolov5's YAML configuration builder into the torchvision nn.Module style and the modified model is still able to load the checkpoints trained from yolov5. However, YOLOv8's design and implementation may differ from that of yolov5 and may require a different approach for it to work together seamlessly. Specifically, YOLOv8's current trainers only accept paths as inputs, and passing a PyTorch dataloader to a `YOLO` object isn't supported. Having said that, we encourage you and the community to continue exploring and experimenting with different approaches to integrate YOLOv8's model functionality into other projects. Thank you again for sharing your work with us.
