### ISSUE TITLE
Confusion matrix : Not able to display labels

### ISSUE THREAD

**Issue by aj0218700** [ultralytics/ultralytics#3071]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

When we train the model, the confusion matrix is generated. 
However, there is no way to force the display of the labels. Even if the default behavior to hide them can be understandable, the fact that we cannot force it is a problem. 
This is due to metrics.py when calling sn.heatmap (around line 324), where the parameter is : "annot=nc < 30" => This is very strange to have this magic number : why 30 ? 
This should be great to solve that, and to be able to activate it if needed. (Eventually set to True by default and could deactivate it from params ?) 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@aj0218700 fontsize constraints prevent plotting of text within high occupancy confusion matrices. The text would either be illegible or overlap with neighboring text.

**Comment by glenn-jocher** [comment]
Removing bug label.
