### ISSUE TITLE
ConfusionMatrix mistake

### ISSUE THREAD

**Issue by mzb157** [ultralytics/ultralytics#3074]
after val , all objects has been detected ,but the ConfusionMatrix shows the P-value and R-value of all is 0.75 (just val one img for test)

![image](https://github.com/ultralytics/ultralytics/assets/54060753/3cef48f0-9b6d-4a83-bd08-56af6cb5f314)

<img width="386" alt="image" src="https://github.com/ultralytics/ultralytics/assets/54060753/d54ea4dd-0ac7-4417-8ed1-51492f4fdf03">

<img width="340" alt="image" src="https://github.com/ultralytics/ultralytics/assets/54060753/737cb7de-3073-4d13-83d6-9579e394841d">

<img width="870" alt="image" src="https://github.com/ultralytics/ultralytics/assets/54060753/982f1156-a6b5-4bf0-b4ab-11f74532d432">

**Comment by glenn-jocher** [comment]
@mzb157 normalization means all columns must sum to 1, so this is the correct behavior. 

We've added a second, non-normalized confusion matrix to the most recent versions, if you update your package to the latest this second confusion matrix will show the actual numeric values.
