### ISSUE TITLE
Geforce gtx1060 6gb

### ISSUE THREAD

**Issue by biscowar** [ultralytics/ultralytics#3075]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a cpu amd ryzen 7 3700x 8 and a gpu NVIDIA gtx1060 6g

This speed for training is good or is poor? 

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        1/8       2.8G     0.4452      1.629      1.087         18        704: 100%|██████████| 25848/25848 [5:32:46<00:00,  1.29it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 12924/12924 [1:45:40<00:00,  2.04it/s]
                   all     206780     411952      0.532      0.358      0.398      0.371

For training i use this python code

from ultralytics import YOLO
             
# Load the model.
model = YOLO('yolov8n.pt')
 
# Training.
if __name__ == "__main__":
	results = model.train(
   	data='test.yaml',
   	imgsz=704,
   	epochs=8,
   	batch=8,
   	name='test'
	)

Can i do something to speedup the training?
Regards

**Comment by bit-scientist** [comment]
@biscowar You could probably use 16 for your batch-size as it takes around 2.8Gb for your current 8. 
You posted this:
```
  Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    1/8       2.8G     0.4452      1.629      1.087         18        704: 100%|██████████| 25848/25848 [5:32:46<00:00,  1.29it/s]
             Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 12924/12924 [1:45:40<00:00,  2.04it/s]
               all     206780     411952      0.532      0.358      0.398      0.371
```
Are you sure this is a correct output of one training experiment? Because if you set the batch-size to be `8` and and you have 206780 images (which is extremely huge) as your test set, then the number `12924` must have been `25848` just like above. This leads me to think that you put two different outputs of batch-sizes of 8 and 16 😆 

Anyways, this is my recommendation:

1. Set batch-size to 16 (set it back to 8 if you get OOM error)
2. Split your whole dataset randomly but fairly (assuming you have 206780 images) as 90% training, 5% valid and 5% test. (or even 94%, 3%, 3%)
3. Consider reducing the image size to 640 (or even smaller) if your dataset has relatively larger objects (looks like you have around 2 instances per image)

**Comment by glenn-jocher** [comment]
Hello @biscowar, based on the output you provided you seem to have enough GPU memory to increase your batch size to 16. This may help you speed up your training time. However, if you experience out of memory errors, you should stay with batch size 8. Also, you can consider reducing the image size to 640 (or even smaller) to further increase training speed, depending on the size of your objects. Additionally, it is recommended to split your dataset into a training, validation, and test set, randomly but fairly, to assess how well your model is generalizing. I hope this helps!

**Comment by mithilnettyfy** [comment]
`Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      2.11G        nan        nan        nan         47        640:  100%|██████████|  1025/1025 [11:26<22:40,  2.00s/it]

Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 79/79 [01:10<00:00,  1.12it/s]
                   all        629       3947          0          0          0          0`

I train my model on NVIDIA GTX 1650 but not showing mAP50, mAP50-95, box_loss,   cls_loss,   dfl_loss,  value as see above output please give sume solution

Package            Version
------------------ --------------------
certifi            2023.5.7
charset-normalizer 3.1.0
colorama           0.4.6
contourpy          1.0.7
cycler             0.11.0
filelock           3.12.0
fonttools          4.39.4
idna               3.4
Jinja2             3.1.2
kiwisolver         1.4.4
MarkupSafe         2.1.3
matplotlib         3.7.1
mpmath             1.3.0
networkx           3.1
numpy              1.24.3
opencv-python      4.7.0.72
packaging          23.1
pandas             2.0.2
Pillow             9.5.0
pip                23.1.2
psutil             5.9.5
pyparsing          3.0.9
python-dateutil    2.8.2
pytz               2023.3
PyYAML             6.0
requests           2.31.0
scipy              1.10.1
seaborn            0.12.2
sentry-sdk         1.25.1
setuptools         65.5.0
six                1.16.0
sympy              1.12
thop               0.1.1.post2209072238
torch              2.0.0+cu117
torchvision        0.15.1+cu117
tqdm               4.65.0
typing_extensions  4.6.3
tzdata             2023.3
ultralytics        8.0.100
urllib3            2.0.3

this is my library is and it's version

**Comment by bit-scientist** [comment]
@mithilnettyfy, hi, please read the quickstart documentation and issues related to your questions throughly. Besides, you'd better create a new issue instead of posting it here. Best of luck!

**Comment by biscowar** [comment]
Sorry but i'm very new to Yolo.
If my jpg and my labet is made on 704x608 jpg size, can i train at 512 ?
The object is Car so it's big in the jpg for sure

**Comment by bit-scientist** [comment]
@biscowar, sure, you can run at whatever size you think is reasonable. Just use `imgsz=512` on the training command and the rest will be handled **automagically**. You may try different sizes eventually to match your best interest in terms of speed and accuracy tradeoff.

**Comment by glenn-jocher** [comment]
Hello @bit-scientist, yes you can train your model at a smaller image size, such as 512x436, if your objects are relatively big in the original image size of 704x608. To do this, you can adjust the `imgsz` parameter in your training command to 512. Additionally, training at a smaller image size may help speed up your training time, but it may also impact the accuracy of your model. Therefore, it's recommended to experiment with different image sizes to find the best balance between accuracy and speed. I hope this helps!

**Comment by biscowar** [comment]
ok now i have trained my model to detect make and model of a car.
Now i have best.pt file.  I have tested and work.
Now i wat to add a new make and model to my yolo. So i tranined startign from best.pt with this code
from ultralytics import YOLO

model = YOLO('best.pt')
results = model('c:/yolov4/nostro', save=True)

The problem is that now my best.pt detect all the car like the last one i give for training. How can i add new make and model or improove an esisting one in my best.pt?
Thx

**Comment by glenn-jocher** [comment]
@biscowar hello! To add a new make and model to your YOLOv8 model, you need to fine-tune the model with new training data containing the new make and model. You can achieve this by following a few steps:

1. Collect new images of the car make and model you want to add, and label them with a tool like LabelImg to create new annotations.

2. Add the new annotations to your original training data containing the previous make and models.

3. Train your model on this new combined dataset using the `train.py` script.

4. After training, you will get a new `best.pt` file that will contain the model weights for all the makes and models you trained on.

It's important to note that fine-tuning the existing model may cause some regression in detecting the original makes and models. Therefore, it's recommended to create a new model for each additional car make and model you want to detect. This way, you can have a more focused and accurate model for each car make and model.

**Comment by biscowar** [comment]
Thank you glenn-jocher for your support to a begginner like me.
So best way is add more labels and jpg to my dataset and train again whole data.
My jpg is composed by cropped car jpg. I notice that accuracy is better with 160 size than 320. Could be a problem of my trainig method?
Regards

**Comment by pderrenger** [comment]
@biscowar You're welcome! Adjusting the image size can indeed impact the training process. Training with smaller images (e.g., 160) may lead to better accuracy in your specific case, as it seems to provide more detailed information for the model to learn from. The choice of image size heavily depends on the characteristics of the objects you're detecting. In your case, since the images contain cropped car images, the smaller size might be providing ample information for accurate detection.

Therefore, it's advisable to continue with the image size that results in better accuracy for your specific dataset. Experimenting with different image sizes is common practice in deep learning, as it allows for optimizing performance based on the unique characteristics of the dataset.

Feel free to reach out if you have further questions!
