### ISSUE TITLE
Multi-scale training

### ISSUE THREAD

**Issue by tangruinenu** [ultralytics/ultralytics#3076]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

May I ask when yolov8 can add multi-scale training? Besides, does yolov8 use multi-scale training techniques in training

**Comment by glenn-jocher** [comment]
@tangruinenu hello! YOLOv8 does indeed use multi-scale training techniques during training, which are implemented in the training script. However, adding support for custom multi-scale training is not currently on our development roadmap. We appreciate your interest and support for YOLOv8!

**Comment by tangruinenu** [comment]
> @tangruinenu hello! YOLOv8 does indeed use multi-scale training techniques during training, which are implemented in the training script. However, adding support for custom multi-scale training is not currently on our development roadmap. We appreciate your interest and support for YOLOv8!

Multi-scale training to improve the performance of the model has a certain help, v5 support multi-scale, looking forward to v8 can also update the multi-scale training skills, which will help a lot of people. After all, v8 is the most advanced detector available, and many people want to use it as a basis for innovation.

**Comment by glenn-jocher** [comment]
@tangruinenu it's already on by default as I mentioned above. You can clearly see this in your training mosaics.

**Comment by dimidagd** [comment]
> @tangruinenu it's already on by default as I mentioned above. You can clearly see this in your training mosaics.

Turned off by defaul ton main https://github.com/ultralytics/ultralytics/blob/fbed8499da8e499248c401cc5c1648a0a35c5a73/ultralytics/cfg/default.yaml#L37

**Comment by rromanchuk** [comment]
@dimidagd @tangruinenu  did you ever figure this out? 

There is definite branching on this flag
https://github.com/ultralytics/ultralytics/blob/5dce4917e0ce01f18e25256c8082b7baac05120f/ultralytics/models/yolo/detect/train.py#L60

 A very curious and random usage here in what seems to be a totally unrelated FAQ

https://github.com/ultralytics/ultralytics/blob/5dce4917e0ce01f18e25256c8082b7baac05120f/docs/en/guides/yolo-common-issues.md?plain=1#L101

It's left out completely under train settings
https://docs.ultralytics.com/modes/train/#train-settings

There is the, what seems to be a related hyperparameter scale
https://github.com/ultralytics/ultralytics/blob/5dce4917e0ce01f18e25256c8082b7baac05120f/ultralytics/cfg/default.yaml#L109

Am I conflating the meaning of this param? 

> @tangruinenu it's already on by default as I mentioned above. You can clearly see this in your training mosaics.

This is true, but it's definitely not clear if that has anything to do with multi_scale, which stdout reports `multi_scale=False`
