### ISSUE TITLE
merge-NMS and require redundancy

### ISSUE THREAD

**Issue by gjgjos** [ultralytics/ultralytics#3077]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In ops.py, there is option for using merge-NMS and redundant (default setting is merge = False, redundant = True). 
![image](https://github.com/ultralytics/ultralytics/assets/76835329/3eeebe72-c06f-4917-a06e-f6ada67e9ac0)

I trained model on my custom dataset and then tried 3 cases 
1. merge=False (default), 
2. merge=True, redundant=True(default)
3. merge=True, redundant=False 

There is no difference of performance between case 1 and case 2. 
But, there is difference between case 2 and case 3. 
When redundant=True, mAP50 increases about 0.04% and mAP50-95 increases about 0.52%.
It means that merge-nms is not effective, but redundant (requiring redundancy) is effective.

I think when using redundancy, it can remove boxes that do not have IoU over threshold with other boxes resulting in less false alarm (=false positive). 

I wonder why you make redundant (=require redundancy) and is this feature not found in the original NMS?

**Comment by glenn-jocher** [comment]
Hi! These options are experimental and may benefit certain contexts and datasets, or may harm them.

I wasn't able to demonstrate improvement on COCO using these settings so I've defaulted them to False, but it's possible they may improve results on other datasets.
