### ISSUE TITLE
YOLOv8 TensorRT Engine: Engine deserialization failed

### ISSUE THREAD

**Issue by KevS272** [ultralytics/ultralytics#3080]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I encountered a weird issue when working with TensorRT engines of YOLOv8n.

As written in the YOLOv8 doc, I created the .onnx and .engine using the command:
`yolo export model=./best.pt format=tensorrt device=0`
I can then use this .engine file without any issues for inference with yolo using the `yolo predict` CLI command.

However, when I want to deserialized the engine using TensorRT directly in both Python and C++, I get the following error:
`[06/07/2023-14:30:53] [TRT] [E] 1: [stdArchiveReader.cpp::StdArchiveReader::30] Error Code 1: Serialization (Serialization assertion magicTagRead == magicTag failed.Magic tag does not match)
[06/07/2023-14:30:53] [TRT] [E] 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
Traceback (most recent call last):
  File "test_engine.py", line 12, in <module>
    context = engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'`
(similar error message for C++)

When I create the .engine using:
`trtexec --onnx=best.onnx --buildOnly --saveEngine=best.engine`
The deserialization works but then when I use it with the `yolo predict`, I get the error:
`[06/07/2023-15:40:30] [TRT] [I] [MemUsageChange] Init CUDA: CPU +357, GPU +0, now: CPU 479, GPU 994 (MiB)
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/cfg/__init__.py", line 397, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/model.py", line 250, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/predictor.py", line 295, in setup_model
    self.model = AutoBackend(model,
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/autobackend.py", line 165, in __init__
    metadata = json.loads(f.read(meta_len).decode('utf-8'))  # read metadata
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 4: invalid continuation byte
'`

I want to use it with TensorRT directly as I work mainly with C++. I want to ask: Is this a known issue and does the way I create the engine with `trtexec` influence the performance in any negative way compared to YOLOv8s export code?

Thx and BR
Kevin

**Comment by glenn-jocher** [comment]
Hello @KevS272, sorry to hear that you are having this issue when accessing TensorRT engines of YOLOv8 in both Python and C++. 

Regarding your first question, this error could be related to the version of TensorRT you are using to deserialize the engine. Please ensure that you are using a compatible version of TensorRT for the engine you have exported with YOLOv8. You may check the compatibility in the [official documentation](https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html).

Regarding your second question, we do not expect that the way you create the engine with trtexec will fundamentally affect the performance of YOLOv8 compared to our export code. The YOLOv8 export code uses the same underlying TensorRT API, and the model execution is the same.

Finally, Joao Medeiros (#7398) has also encountered this utf-8 deserialization error and has shared a possible solution on this [Seeed Studio Wiki](https://wiki.seeedstudio.com/YOLOv8-DeepStream-TRT-Jetson/). It could be helpful to have a look.

If you need further assistance, we invite you to join the Ultralytics Discord community where you can connect with Joao Medeiros and other experts to receive real-time help and support.

Best regards!
