### ISSUE TITLE
Class probabilites

### ISSUE THREAD

**Issue by baglanaitu** [ultralytics/ultralytics#3082]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! I have the same question as https://github.com/ultralytics/ultralytics/issues/2600#issuecomment-1571799089, https://github.com/ultralytics/ultralytics/issues/2863,  However, none of them worked for me. How to get class probabilities of predictions (between 0 and 1)?

**Comment by glenn-jocher** [comment]
@baglanaitu hi there,

Thank you for reaching out to us with your question on getting class probabilities for the predictions made using YOLOv8. To achieve this, you can use the sigmoid function to obtain the class probabilities between 0 and 1. The sigmoid function is applied to the output of the classification head and for each class, a probability score is obtained. 

Do let us know if you have any further questions or need more clarifications.

Best Regards,  
Glenn Jocher.

**Comment by baglanaitu** [comment]
Hi @glenn-jocher ! Thank you for your answer! However, I would like to ask for further clarification. My question is primitive. In the example below, I attempted simple cat detection. Given that yolo8n.pt has 80 classes, how can I display the probabilities of all classes ensuring that their sum equals 1? 

**from ultralytics import YOLO
model = YOLO('yolov8n.pt')
results = model.predict('/home/cat.jpg')
print(results)**

image 1/1 /home/cat.jpg: 480x640 1 cat, 11.2ms
Speed: 2.4ms preprocess, 11.2ms inference, 2.3ms postprocess per image at shape (1, 3, 640, 640)
[ultralytics.yolo.engine.results.Results object with attributes:
boxes: ultralytics.yolo.engine.results.Boxes object
keypoints: None
keys: ['boxes']
masks: None
names: {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted plant', 59: 'bed', 60: 'dining table', 61: 'toilet', 62: 'tv', 63: 'laptop', 64: 'mouse', 65: 'remote', 66: 'keyboard', 67: 'cell phone', 68: 'microwave', 69: 'oven', 70: 'toaster', 71: 'sink', 72: 'refrigerator', 73: 'book', 74: 'clock', 75: 'vase', 76: 'scissors', 77: 'teddy bear', 78: 'hair drier', 79: 'toothbrush'}
orig_img: array([[[ 49,  57,  26],
        [ 50,  58,  27],
        [ 47,  55,  25],
        ...,
        [ 30,  77,  45],
        [ 36,  87,  50],
        [ 45,  94,  56]],

       [[ 51,  57,  26],
        [ 52,  58,  27],
        [ 48,  56,  25],
        ...,
        [ 32,  82,  50],
        [ 37,  89,  52],
        [ 45,  96,  58]],

       [[ 51,  57,  26],
        [ 51,  57,  26],
        [ 49,  57,  26],
        ...,
        [ 27,  88,  52],
        [ 35,  95,  55],
        [ 42,  99,  60]],

       ...,

       [[ 15,  47,  36],
        [ 13,  46,  32],
        [ 13,  47,  36],
        ...,
        [156, 173, 182],
        [162, 179, 188],
        [164, 181, 190]],

       [[ 19,  53,  42],
        [ 20,  56,  42],
        [ 22,  58,  44],
        ...,
        [167, 184, 193],
        [158, 175, 184],
        [167, 184, 193]],

       [[ 25,  62,  46],
        [ 25,  64,  49],
        [ 27,  66,  51],
        ...,
        [188, 205, 214],
        [157, 174, 183],
        [158, 175, 184]]], dtype=uint8)
orig_shape: (360, 480)
path: '/home/cat.jpg'
probs: None
speed: {'preprocess': 2.4385452270507812, 'inference': 11.194229125976562, 'postprocess': 2.296924591064453}]

**Comment by glenn-jocher** [comment]
Hello @baglanaitu,

Thank you for your question! To display the class probabilities of the output of your YOLOv8 model, you can use the sigmoid function on the output of the classification head to obtain the probability of each class. For example, using your code, you could obtain the probabilities of each of the 80 classes by applying the sigmoid function on the outputs of the classification head and normalizing them such that their sum equals 1. This will give you a vector of probabilities for each class for a given image.

Do let us know if you have further questions or need additional clarification.

Best regards,
Glenn Jocher.

**Comment by baglanaitu** [comment]
Hi @glenn-jocher! Thank you for your answer! I was wondering, do I have to train a new model for that?
