### ISSUE TITLE
YOLOv8 custom model train with GPU

### ISSUE THREAD

**Issue by DrRazadyne** [ultralytics/ultralytics#3083]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, Im new to all this and Im trying to get YOLOv8 working with my GPU to train a custom model to no avail.

So after importing ultralytics and running this it took ages:

model = YOLO("yolov8x.yaml")

model.train(data="data.yaml", epochs=100)

So I researched on how to use the GPU and installed CUDA 12.1

<img width="593" alt="image" src="https://github.com/ultralytics/ultralytics/assets/91225547/2da8e26d-ad07-4bfa-bef7-6931691178c7">

Now running model.train(data="data.yaml", epochs=100, device=0) throws this error after some loading
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

Is there a way to fix this? I tried some thing from other posts with no results

Many thanks in advance.

-DSO.

**Comment by bit-scientist** [comment]
@DrRazadyne hi, pleasy try with lower CUDA (11.8) and do everything on conda environment. It's very convinient to work in conda envs for beginners.

**Comment by YoungLintao** [comment]
when i try _yolo train model=yolov8n.pt data=coco128.yaml epochs=3 imgsz=640_  it failed just like what you happened,
while  i changed into _yolo train model=yolov8n.pt data=coco128.yaml epochs=3 imgsz=640 **workers=0**_ it successed,so i think  may be the cause is the num_workers on win should be 0

**Comment by glenn-jocher** [comment]
@DrRazadyne hello! Thank you for reaching out to us. We are glad to hear that you were able to get your training to successfully run by setting the `workers` parameter to 0. 

You are correct that `num_workers` can cause issues with training on Windows, as it uses the `spawn` method of creating processes when `num_workers` is set to a non-zero value, which can cause problems. Setting `workers` to 0, which disables multi-processing, can help avoid these issues.

We hope this helps! If you have any other questions, please do not hesitate to ask.

**Comment by YoungLintao** [comment]
> 额，我用的11.8版本的pytorch，也出现这个报错
因为源码是在linux上的所以写的时候默认是多线程的，但是win上不能多线程，只要改设备数量就行了
