### ISSUE TITLE
Pretrained onnx model

### ISSUE THREAD

**Issue by hardikdava** [ultralytics/ultralytics#3086]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello @glenn-jocher @AyushExel , does ultralytics provide direct downloadable link for yolov8 onnx models? I am aware that onnx model can easily be exported using python API/ cli. But I want a URL where it is already stored. 

Thank you in advance.

**Comment by glenn-jocher** [comment]
@hardikdava no, we don't have ONNX downloads, but they are very simple to create. You can export one and store it yourself, i.e.

```
yolo export model=yolov8n.pt format=onnx
```
