### ISSUE TITLE
YOLOv8 inference

### ISSUE THREAD

**Issue by javiercolasbiddeo** [ultralytics/ultralytics#309]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to infer an image folder with a yolov8 model for object detection. The code I am using is as follows
`from ultralytics import YOLO`
`model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)`

`results = model.predict(source = "/Users/Javier/Desktop/fotos_test/makeup2_3.jpeg",
                       save_txt=True,
                       save_conf=True,
                       save_crop=True,
                       agnostic_nms=True,
                       retina_masks=True,
                       visualize=True,
                       project= '/Users/Javier/Downloads') # predict on an image`

And to see the results this one:

`for out in results:
    print(out)`

the error I get back is this:

_` No such file or directory: '/Users/Javier/Downloads/predict3/labels/makeup2_3.txt'`_

Any solutions?

**Comment by AyushExel** [comment]
I don't see any variable named `out`. If you want to see the output on the image, just pass `show=True`..
Alternatively, if you're more familiar with yolov5 like usage you can just run this command in your terminal:
```
yolo task=detect mode=predict show=True ...
```

**Comment by tank-o** [comment]
When using the python package for inference, the results is just empty, in yolov5 you would get results back and print it like so

`print(results.pandas().xyxy[0])`

is something similair not available for v8?

**Comment by AyushExel** [comment]
We're working on supporting it soon

**Comment by AyushExel** [comment]
@javiercolasbiddeo ohh I thought you just wanted to see the output. To save the txt files pass `save_txt=True`

**Comment by javiercolasbiddeo** [comment]
I already wrote that, the problem is that, when i use the library the parameter `project ` does not give an error, but it does not give me the output. When I use the terminal, using this `!yolo task=detect\
mode=predict \
model=yolov8n.pt \
source="https://ultralytics.com/images/bus.jpg" \
save_txt=True \
save_conf=True \
save_crop=True \
return_outputs=True \
name = 'motorcycle' 

`

I recive this error 
<img width="871" alt="image" src="https://user-images.githubusercontent.com/108056086/212295629-f397b0f1-e8fb-4e85-978a-f0874879dd82.png">

**Comment by JakobStadlhuber** [comment]
<img width="940" alt="Bildschirm­foto 2023-01-13 um 13 22 29" src="https://user-images.githubusercontent.com/20328243/212319382-51b05249-698e-49df-9002-35ac538d4c08.png">

**Comment by mrmarten** [comment]
> We're working on supporting it soon

Please ping us when its available this is what can make Yolo work in real life use cases not just for examples 💯

**Comment by AyushExel** [comment]
It is available in the current release but it's not perfect and you might experience slight slowdown. But working on much better support which'll be released soon. Meanwhile see how you can interact with predictions here:
https://docs.ultralytics.com/python/

**Comment by pjelar** [comment]
It's in the current release? I didn't see it when I recently ran it.

**Comment by pderrenger** [comment]
@pjelar apologies for the confusion. The feature you're looking for is not available in the current release. We are actively working on improving this to provide a seamless user experience. Thank you for your understanding.
