### ISSUE TITLE
How to upgrade ```ultralytics``` library (python) files

### ISSUE THREAD

**Issue by Adeelbek** [ultralytics/ultralytics#3090]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello there,

I have tried to upgrade ```ultralytics``` library files using ```pip install --upgrade ultralytics``` but I still see some difference between my ultralytics library python codes and online up-to-date github repo codes. For instance, I see a big difference between ```/opt/conda/lib/python3.8/site-packages/ultralytics/nn/tasks.py``` and ```https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/tasks.py```. Is there any way that I can try to make my environment completely identical with up-to-date github repo (I need updating method better than reinstalling).

Thanks!

**Comment by Mandeep-2407** [comment]
@Adeelbek 
you can do one thing 
run this command which might be helpful 

`pip uninstall ultralytics`
'pip install ultralytics'

**Comment by Kayzwer** [comment]
`pip install -U ultralytics`

**Comment by pderrenger** [comment]
@Kayzwer the implementation you mentioned is installed correctly. Remember that the GitHub repository may have the most recent changes but they might not be included in the current release yet. To be completely up-to-date with the repository, you can install the library directly from the main branch, but keep in mind that it might not be as stable as the stable releases.

**Comment by Petros626** [comment]
> `pip install -U ultralytics`

how can I update to the latest version, without losing my changed files, comments etc.? I used `git clone` for the installation with `pip install -e .`

**Comment by glenn-jocher** [comment]
To update your cloned repository while retaining your changes, use `git pull` to fetch the latest updates from the main branch. Resolve any merge conflicts locally to ensure your custom changes are preserved. For ongoing development, consider maintaining a separate branch for your modifications.
