### ISSUE TITLE
Does the file below mean that yolo-nas can be used with yolov8?

### ISSUE THREAD

**Issue by kimcheolhee80** [ultralytics/ultralytics#3091]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Does the file below mean that yolo-nas can be used with yolov8?

yolo_nas_l.pt
yolo_nas_m.pt
yolo_nas_s.pt

I found the above files at the url below.
https://github.com/ultralytics/assets/releases/

I'm still a newbie so the question may be stupid.
hope you understand.

**Comment by glenn-jocher** [comment]
@kimcheolhee80 yes, I made a PR for this in https://github.com/ultralytics/ultralytics/pull/2735, but there doesn't seem to be much demand for this so I've left it alone for now.
