### ISSUE TITLE
I ran into problem when training data with yolov8

### ISSUE THREAD

**Issue by dimaspratama08** [ultralytics/ultralytics#3096]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

When i tried to run the train model i got the following error:

`Traceback (most recent call last):
  File "c:\Dimas\11. Astra Agro Lestari\Probation\Tree Counting\model.py", line 7, in <module>
    results = model.train(data="config.yml", epochs=1)  # train the model
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\yolo\engine\model.py", line 371, in train
    self.trainer.train()
  File "C:\Users\dimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\yolo\engine\trainer.py", line 192, in train
    self._do_train(world_size)
  File "C:\Users\dimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\yolo\engine\trainer.py", line 398, in _do_train        
    self.final_eval()
  File "C:\Users\dimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\yolo\engine\trainer.py", line 553, in final_eval       
    self.metrics = self.validator(model=f)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dimas\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\yolo\engine\validator.py", line 131, in __call__       
    raise FileNotFoundError(emojis(f"Dataset '{self.args.data}' for task={self.args.task} not found ❌"))
FileNotFoundError: Dataset 'config.yml' for task=detect not found
PS C:\Dimas\11. Astra Agro Lestari\Probation\Tree Counting>`

### Environment

- i am using acer nitro 5 2022 (i5, rtx3050)
- YOLO v8
- python 3.11.3

### Minimal Reproducible Example

This is the code for my training model:

```
from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.yaml")  # build a new model from scratch

# Use the model
results = model.train(data="config.yml", epochs=1)  # train the model
```

### Additional

Here is the data that i used to train model

```path: C:\Dimas\11. Astra Agro Lestari\Probation\Tree Counting\Data  # dataset root dir
train: C:\Dimas\11. Astra Agro Lestari\Probation\Tree Counting\Data\train\images  # train images (relative to 'path')
val: C:\Dimas\11. Astra Agro Lestari\Probation\Tree Counting\Data\valid\images  # val images (relative to 'path')

# Classes
names:
  0: pohon sawit````

and by the way everytime i try to save the config file in .yaml it instantly changed to .yml

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by dimaspratama08** [comment]
@glenn-jocher please help

**Comment by Mandeep-2407** [comment]
@dimaspratama08 
model = YOLO("yolov8n.yaml")
Here you need to add .pt model file instead of adding the yaml file 



you can do the following thing


`from ultralytics import YOLO
# Load a model
model = YOLO("yolov8n.pt")  # load a custom model
model.train()
`
you can refer the train page and add whichever parameters you want to add
reference to the link:
<(https://docs.ultralytics.com/modes/train/>

**Comment by glenn-jocher** [comment]
@dimaspratama08 your dataset is incorrectly configured. See https://docs.ultralytics.com/datasets/detect/ for guidance.

**Comment by dimaspratama08** [comment]
@glenn-jocher i edited my config to this
![image](https://github.com/ultralytics/ultralytics/assets/86192369/184e0839-8f5a-40f7-bc22-4a5a6c266a77)

but i still got the file not found error for the config.yml
![image](https://github.com/ultralytics/ultralytics/assets/86192369/0e26e9c8-ad5d-41fe-b035-2748c2f93292)

**Comment by dimaspratama08** [comment]
the python code to run the model and the config is in the same dir
![image](https://github.com/ultralytics/ultralytics/assets/86192369/c449acda-0af1-4809-b889-0221e6321fc5)

**Comment by glenn-jocher** [comment]
@dimaspratama08, it seems like the YOLOv8 model is unable to locate your dataset in the location specified in the "config.yml" file when you are trying to train the model. Please ensure that you have specified the correct path to your dataset in the "config.yml" file.

For example, if you are using Windows, please ensure that you have used forward slashes (/) instead of backward slashes (\) in the path. Additionally, double-check that you have saved the "config.yml" file in the correct directory. 

If you are still encountering issues, try explicitly specifying the path to the "config.yml" file in your code:

```python
from ultralytics import YOLO

model = YOLO("yolov8n.pt")  # load a custom model
results = model.train(data="C:/path/to/config.yml", epochs=1)  # train the model
```

I hope this helps! Please let me know if you have any more questions.

**Comment by dimaspratama08** [comment]
@glenn-jocher i tried the suggestion, but it's still happening
![image](https://github.com/ultralytics/ultralytics/assets/86192369/c7c66d4b-d3c4-4659-9d63-f91ec2d8dcee)
![image](https://github.com/ultralytics/ultralytics/assets/86192369/bbf46084-ba76-4b34-9cde-c182bcf0e438)

**Comment by dimaspratama08** [comment]
@glenn-jocher i forgot to add that even though the 'FileNotFoundError' always occured everytime i tried to run the model. it gave me this result. i dont know if it supposed to happen or not :/
![image](https://github.com/ultralytics/ultralytics/assets/86192369/6b247b75-128c-4362-aaf2-5875109e31a6)

**Comment by glenn-jocher** [comment]
@dimaspratama08 The `FileNotFoundError` means that the YAML configuration file or the dataset could not be found in the specified location. However, the reason why you are seeing the model summary means that the model was loaded successfully and the file paths in the YAML file were correctly parsed. 

The faster_rcnn model takes in a tensor with Nx3xHxW dimensions and returns the predicted boxes as well as the associated scores, labels, and class probabilities. If the model was able to load and print its summary, then it should be ready for inference.

However, please note that the summary does not guarantee that the model will train well or perform well on your input data. You should still ensure that your YAML configuration and input data are properly set up before training and validating the model.

I hope this helps! Let me know if you have any other questions or concerns.

**Comment by dimaspratama08** [comment]
@glenn-jocher  so how to solve this? i am completely new to yolo

**Comment by dimaspratama08** [comment]
My directory:
![image](https://github.com/ultralytics/ultralytics/assets/86192369/0104afb9-803e-453b-abe7-bf67f6f35372)

The python code:
![image](https://github.com/ultralytics/ultralytics/assets/86192369/8876366c-6db1-4bea-8969-48a80e48e033)

config file:
![image](https://github.com/ultralytics/ultralytics/assets/86192369/a5b13690-c155-43f8-9cc2-1256f7fc3d3f)

**Comment by dimaspratama08** [comment]
Update
@glenn-jocher i solved the problem by changing my config.yml extension to yaml.
Thanks a lot for your help :) i really apreciate it
