### ISSUE TITLE
Generator from model prediction has confusing properties in 8.0.4 and 8.0.5

### ISSUE THREAD

**Issue by anderzzz** [ultralytics/ultralytics#310]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

This may be a feature and not a bug, but it took me a while to figure out how the context was managed for the generator that a model prediction creates. If intended, then I think documentation should be improved.

The prediction to illustrate the confusion:

```python
from ultralytics import YOLO
from copy import deepcopy

model = YOLO('yolov8n.pt')  # load a pretrained YOLOv8n detection model
tt = model.predict(source='https://ultralytics.com/images/bus.jpg', return_outputs=True, save=True)  # predict on an image
tmp1 = []
tmp2 = []
for x in tt:
    tmp1.append(x)
    tmp2.append(deepcopy(x))
print (tmp1)
print (tmp2)

tt = model.predict(source='https://ultralytics.com/images/bus.jpg', return_outputs=True, save=True)  # predict on an image
print ([*tt])
```

Of the three lists, only `tmp2` contains the prediction output, the other ones an empty dictionary.

From looking at the code, I understand this behaviour stems from a PyTorch generator context manager. If I revert to `8.0.3`, and remove the `return_outputs` argument, all three lists contain the results.

As was noted in #278 there was a change introduced, which changed behaviours. 

This was at least confusing to me, since the generator context was not immediately clear. I report it here so you can at least consider documentation clarification.

### Environment

YOLO: YOLOv8 8.0.4
OS: macOS Monterey 12.6
Python: 3.9.16 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@anderzzz hi! sorry for the inconvenience caused. We're currently working on improving out results along with the dedicated docs regarding their usage.
Currently we're using generators as its the best solution for managing memory with large outputs. Please stay tuned we'll provide a stable solution for this very soon!

**Comment by kadirnar** [comment]
> @anderzzz hi! sorry for the inconvenience caused. We're currently working on improving out results along with the dedicated docs regarding their usage. Currently we're using generators as its the best solution for managing memory with large outputs. Please stay tuned we'll provide a stable solution for this very soon!

@AyushExel 
Code:
```
model = YOLO("yolov8n.pt")
pred = model.predict(source=img_src)
print(pred)
```
Output:
```
[Ultralytics YOLO <class 'ultralytics.yolo.engine.results.Results'> instance
Ultralytics YOLO <class 'ultralytics.yolo.engine.results.Boxes'> masks
type: <class 'torch.Tensor'>
shape: torch.Size([3, 6])
dtype: torch.float32
original size: (464, 848)
]
```
How can I get all the outputs?

**Comment by AyushExel** [comment]
Pandas functionality is not implemented yet. We'll work on that soon

**Comment by kadirnar** [comment]
> Pandalar işlevi henüz uygulanmadı. Yakında bunun üzerinde çalışacağız

Thank you for the answer. I don't need pandas integration. I want this. 
```
tensor([[624.90729, 308.60022, 706.44482, 462.47269,   0.90652,   0.00000],
        [522.00854, 325.78876, 578.97314, 461.96042,   0.87011,   0.00000]], device='cuda:0')
```
I am able to do this in the Yolov5 repo. But should I wait for yolov8?

**Comment by AyushExel** [comment]
```
model = YOLO("yolov8n.pt")
pred = model.predict(source=img_src)
print(pred)

res = pred[0]
res.boxes # -> boxes of shape n,6... res.boxes.boxes to get raw tensors. res.boxes.xyhw to get list in xyhw format. boxes.xyhw[0] to get only one prediction in xyhw format
```

**Comment by AyushExel** [comment]
@glenn-jocher should we update the repr to print the matrices directly instead of only the shapes?

**Comment by kadirnar** [comment]
> ```
> model = YOLO("yolov8n.pt")
> pred = model.predict(source=img_src)
> print(pred)
> 
> res = pred[0]
> res.boxes # -> boxes of shape n,6... res.boxes.boxes to get raw tensors. res.boxes.xyhw to get list in xyhw format. boxes.xyhw[0] to get only one prediction in xyhw format
> ```
I solved it with the torch.cat function.
Code:
```
boxes = prediction[:].boxes.xyxy
score = prediction[:].boxes.conf
category_id = prediction[:].boxes.cls
dets = torch.cat((boxes, score.unsqueeze(1), category_id.unsqueeze(1)), dim=1)
print(dets)
```
Output:
```
tensor([[6.26000e+02, 3.10000e+02, 7.06000e+02, 4.64000e+02, 9.05056e-01, 0.00000e+00],
        [5.08000e+02, 3.01000e+02, 5.78000e+02, 4.64000e+02, 8.20299e-01, 0.00000e+00],
        [5.49000e+02, 3.24000e+02, 5.79000e+02, 4.56000e+02, 2.58571e-01, 0.00000e+00]], device='cuda:0')
```

**Comment by pderrenger** [comment]
@kadirnar great to hear that you were able to solve it using the torch.cat function! Your approach seems to be effective for combining the individual components of the prediction. If you have any more questions or need further assistance, feel free to ask!
