### ISSUE TITLE
Use semi-transparent label in image

### ISSUE THREAD

**Issue by darouwan** [ultralytics/ultralytics#3101]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

The box of the current prediction result often blocks other boxes, if the boxes have overlap. Suggest to use semi-transparent to show the box text. 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by darouwan** [comment]
@glenn-jocher Many thanks for your explanation. I will try to add the option to add the alpha channel to make it semi-transparent and avoid decreasing the performance as much as possible. After all certain validation scenarios with this requirement don't necessitate high performance.

**Comment by glenn-jocher** [comment]
You're welcome @darouwan, glad to help! It's great that you're planning on adding the option to make the bounding box text semi-transparent. As you mentioned, certain validation scenarios would benefit from this kind of display, and we appreciate any contributions that can improve the usability of YOLOv8 for our users. Just keep in mind that maintaining optimal performance is still crucial, so try to balance the two as much as you can. Good luck with your implementation, and don't hesitate to reach out if you have any questions!

**Comment by darouwan** [comment]
Solved in #3224

**Comment by pderrenger** [comment]
@darouwan great to hear that! If you need any further assistance or have any other suggestions, feel free to let us know. We're here to help!

**Comment by glenn-jocher** [comment]
@pderrenger Fantastic, thank you for the update! If there's anything else you need, we're always here to support. Happy coding! 🚀
