### ISSUE TITLE
Overlay output masks on the original image 

### ISSUE THREAD

**Issue by osamaalschame** [ultralytics/ultralytics#3104]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hello, 

how to overlay the output masks on the original image?

thank you

**Comment by glenn-jocher** [comment]
@osamaalschame hello,

Thank you for reaching out to us. To overlay the output masks on the original image, you can use the `cv2.addWeighted()` function in OpenCV. 

First, you need to convert the mask to a RGB image and resize it to match the size of the original image. Then, you can overlay the mask on the original image using the `cv2.addWeighted()` function, with a transparency value that suits your needs.

I hope this helps! Let us know if you have any further questions.
