### ISSUE TITLE
Loss types

### ISSUE THREAD

**Issue by MattAlanWright** [ultralytics/ultralytics#3105]
### Discussed in https://github.com/orgs/ultralytics/discussions/2712

<div type='discussions-op-text'>

<sup>Originally posted by **MattAlanWright** May 19, 2023</sup>
I see in the [training docs](https://docs.ultralytics.com/modes/train/#arguments) that there are tunable gains for three different loss types:
- Box loss
- Class loss
- DFL loss
Can anyone tell me more about how these are calculated? Which ones might be tuned to emphasize recall over precision or precision over recall?</div>

**Comment by glenn-jocher** [comment]
@MattAlanWright these are manually tuned for COCO mAP50-95. You can manually optimize or tune these for your particular scenario to maximize or minimize your particular criteria.

**Comment by aiakash** [comment]
@glenn-jocher any reference or guidance for tunning  this values
