### ISSUE TITLE
Export Yolov8 to TensorRT int8

### ISSUE THREAD

**Issue by hamedgorji** [ultralytics/ultralytics#3108]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi,

I've reviewed the documentation and discovered that I can export the model to TensorRT using three options: FP32, FP16, and Simplify. However, I specifically require my TensorRT model to be in INT8 precision.
Currently, I am able to export my model using the following code, but it poses an issue when working with Ultralytics:
`trtexec --onnx=best.onnx --int8 --saveEngine=resnet_engine.engine`
Could you please let me know if there is an existing method to export the YOLOv8 model to TensorRT with INT8 precision? Alternatively, I kindly request the addition of this feature to the export functionality.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@hamedgorji hello! Thank you for your interest in YOLOv8. Currently, we don't have an explicit method to export the YOLOv8 model to TensorRT with INT8 precision. However, you can still try to use the trtexec tool with the "--int8" flag to convert your ONNX model to an INT8 precision TensorRT engine. 

Please note that even though the model is exported with precision data, you will still need to find a way to calibrate the model to use it in the INT8 inference mode. TensorRT provides a calibration method that you can use, and you can find more information in the TensorRT documentation.

If you'd like to contribute to our project and add this feature to our export functionality, we'd be happy to review your pull request! Thank you for your support.

**Comment by Diaislam** [comment]
> @hamedgorji hello! Thank you for your interest in YOLOv8. Currently, we don't have an explicit method to export the YOLOv8 model to TensorRT with INT8 precision. However, you can still try to use the trtexec tool with the "--int8" flag to convert your ONNX model to an INT8 precision TensorRT engine.
> 
> Please note that even though the model is exported with precision data, you will still need to find a way to calibrate the model to use it in the INT8 inference mode. TensorRT provides a calibration method that you can use, and you can find more information in the TensorRT documentation.
> 
> If you'd like to contribute to our project and add this feature to our export functionality, we'd be happy to review your pull request! Thank you for your support.

Adding it would be a huge addition to the repository, thanks guys for the good work
