### ISSUE TITLE
Data Augmentation

### ISSUE THREAD

**Issue by China-pzy** [ultralytics/ultralytics#3109]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to do a gesture recognition project, does anyone know how to turn off the flipped data processing operation that comes with yolo v8? This operation caused me to have low recognition of both left and right hands

**Comment by Laughing-q** [comment]
@China-pzy pass `fliplr=0`.

**Comment by China-pzy** [comment]
it worked, thanks

> @China-pzy pass `fliplr=0`.

**Comment by glenn-jocher** [comment]
@China-pzy you're welcome! Remember that setting `fliplr=0` turns off the horizontal flipping augmentation of your input data, which can potentially help improve the recognition of left and right hand gestures. If you have any other questions or concerns, feel free to ask.

**Comment by Laughing-q** [comment]
@China-pzy nice to hear it's working to you! closing the issue since it's solved. :)
