### ISSUE TITLE
The confusing comment for true background and predicted background

### ISSUE THREAD

**Issue by darouwan** [ultralytics/ultralytics#3110]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I found in 
https://github.com/ultralytics/ultralytics/blob/29c954a1385815e522f0d94d7144814cc4e6da42/ultralytics/yolo/utils/metrics.py#L277-L288

Should the comment 'true background' and 'predicted background' be exchanged the position?
Based on my understanding, ` self.matrix[self.nc, gc] += 1` get the number of box which is labeled but not predicted, or we call it underkill or false negative. `self.matrix[dc, self.nc] += 1` get the number of box which is predicted but not labeled, or we call it overkill or false positive.

**Comment by glenn-jocher** [comment]
@darouwan hi there! Thank you for reaching out regarding the confusing comment for "true background" and "predicted background". To clarify, `self.matrix[self.nc, gc]` represents the number of boxes that are labeled as background and have been correctly predicted as background, which is why it is referred to as "true background". Similarly, `self.matrix[dc, self.nc]` represents the number of boxes that are predicted as background but are not actually background, which is why it is referred to as "predicted background". I hope this clears up any confusion! Let me know if you have any other questions or concerns.

**Comment by darouwan** [comment]
So take the below confusion matrix as sample:
The red part is calculated by self.matrix[self.nc, gc], and the green part is calculated by self.matrix[dc, self.nc], is it correct?
If yes,  `self.matrix[self.nc, gc]` should represent the box is labelled but predicted as background. `self.matrix[dc, self.nc]` represents the box is predicted, but actually it is background. The blue part means there is neither predicted box nor labelled box, so it should be always 0. 

Is my understanding correct? 

![image](https://github.com/ultralytics/ultralytics/assets/2324213/15e0591a-6d90-4acb-bb6e-b5e8cf81815f)

**Comment by glenn-jocher** [comment]
@darouwan Hi, thanks for providing the confusion matrix as an example. Your understanding is almost correct, but there is a slight confusion. `self.matrix[self.nc, gc]` actually represents the number of boxes that are labeled as "no object" (i.e., background) and have been correctly predicted as "no object", and `self.matrix[dc, self.nc]` represents the number of boxes that are predicted as "no object" but are not actually "no object". The blue part indeed represents the number of boxes that are neither predicted nor labeled, and therefore, it is always zero. I hope this clears up your confusion. Let me know if you have any other questions or concerns.

**Comment by darouwan** [comment]
@glenn-jocher  Hi, thanks for your detailed explanation. 
I want to confirm that does `self.matrix[self.nc, gc]` generate the red part?  If yes, what does the cell with the value 3 mean? The x-axis of this cell is True-chair and the y-axis is background-predicted. If the `self.matrix[self.nc, gc]` represents the number of boxes that are labeled as "no object" (i.e., background) and have been correctly predicted as "no object", what does the True-chair mean here?

**Comment by Evanurmalasari** [comment]
@glenn-jocher can you explain how to manually normalize the background value in the confusion matrix below. What number should this value be multiplied by? I don't understand manual normalization.
<img width="489" alt="confusion" src="https://github.com/ultralytics/ultralytics/assets/136422277/7b2f4b05-6528-489b-a271-dd7b8a5bf7d3">
