### ISSUE TITLE
Failed to enable GUI event loop integration for 'qt'

### ISSUE THREAD

**Issue by mcdonasd1212** [ultralytics/ultralytics#3113]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Here is the error

```
Failed to enable GUI event loop integration for 'qt'
Traceback (most recent call last):
  File "//.vscode/extensions/ms-python.python-2023.10.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydev_ipython/matplotlibtools.py", line 30, in do_enable_gui
    enable_gui(guiname)
  File "//.vscode/extensions/ms-python.python-2023.10.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydev_ipython/inputhook.py", line 540, in enable_gui
    return gui_hook(app)
           ^^^^^^^^^^^^^
  File "//.vscode/extensions/ms-python.python-2023.10.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydev_ipython/inputhook.py", line 176, in enable_qt
    from pydev_ipython.qt_for_kernel import QT_API, QT_API_PYQT5
  File "//.vscode/extensions/ms-python.python-2023.10.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydev_ipython/qt_for_kernel.py", line 116, in <module>
    QtCore, QtGui, QtSvg, QT_API = load_qt(api_opts)
                                   ^^^^^^^^^^^^^^^^^
  File "//.vscode/extensions/ms-python.python-2023.10.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydev_ipython/qt_loaders.py", line 285, in load_qt
    raise ImportError("""
ImportError: 
    Could not load requested Qt binding. Please ensure that
    PyQt4 >= 4.7 or PySide >= 1.0.3 is available,
    and only one is imported per session.

    Currently-imported Qt library:   None
    PyQt4 installed:                 False
    PyQt5 installed:                 False
    PySide >= 1.0.3 installed:       False
    PySide2 installed:               False
    Tried to load:                   ['pyqtdefault', 'pyside', 'pyside2', 'pyqt5']
    
Backend QtAgg is interactive backend. Turning interactive mode on.
```
I only get the error when the script loads
```
from ultralytics import YOLO
```
Here is the requirement.txt info

```
absl-py==1.4.0
adal==1.2.7
asttokens==2.2.1
attrs==23.1.0
azure-core==1.26.4
azure-storage-blob==12.16.0
backcall==0.2.0
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
cmake==3.26.3
comm==0.1.3
contourpy==1.0.7
cryptography==40.0.2
cycler==0.11.0
debugpy==1.6.7
decorator==5.1.1
evdev==1.6.1
executing==1.2.0
filelock==3.12.0
flatbuffers==23.5.9
fonttools==4.39.4
greenlet==2.0.2
idna==3.4
imbalanced-learn==0.10.1
ipykernel==6.23.1
ipython==8.13.2
isodate==0.6.1
jedi==0.18.2
Jinja2==3.1.2
joblib==1.2.0
jupyter_client==8.2.0
jupyter_core==5.3.0
kiwisolver==1.4.4
lit==16.0.3
MarkupSafe==2.1.2
matplotlib==3.7.1
matplotlib-inline==0.1.6
mediapipe==0.10.0
mpmath==1.3.0
msal==1.22.0
msrest==0.7.1
msrestazure==0.6.4
nest-asyncio==1.5.6
networkx==3.1
numpy==1.24.3
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
oauthlib==3.2.2
opencv-contrib-python==4.7.0.72
opencv-python==4.7.0.72
packaging==23.1
pandas==2.0.1
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.5.0
platformdirs==3.5.1
prompt-toolkit==3.0.38
protobuf==3.20.3
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.21
Pygments==2.15.1
PyJWT==2.7.0
pynput==1.7.6
pyparsing==3.0.9
PyQt6==6.5.1
PyQt6-Qt6==6.5.1
PyQt6-sip==13.5.1
PySide6==6.5.1.1
PySide6-Addons==6.5.1.1
PySide6-Essentials==6.5.1.1
python-dateutil==2.8.2
python-dotenv==1.0.0
python-xlib==0.33
pytz==2023.3
PyYAML==6.0
pyzmq==25.0.2
requests==2.30.0
requests-oauthlib==1.3.1
scikit-learn==1.2.2
scikit-plot==0.3.7
scipy==1.10.1
seaborn==0.12.2
sentry-sdk==1.23.0
shiboken6==6.5.1.1
six==1.16.0
sounddevice==0.4.6
SQLAlchemy==2.0.13
stack-data==0.6.2
sympy==1.12
thop==0.1.1.post2209072238
threadpoolctl==3.1.0
torch==2.0.1
torchaudio==2.0.2+cu118
torchvision==0.15.2
tornado==6.3.2
tqdm==4.65.0
traitlets==5.9.0
triton==2.0.0
typing_extensions==4.5.0
tzdata==2023.3
ultralytics==8.0.103
urllib3==1.26.15
wcwidth==0.2.6
xgboost==1.7.5
```

### Environment

- python 3.11
- Ubuntu 20.04
- Cuda 11.8

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mcdonasd1212 hello there! Thank you for reporting this issue. Based on your error message, it seems like there might be a problem with your Qt installation. YOLOv8 is not dependent on Qt and we don't use it in our code, so it's not an issue related to YOLOv8 itself. However, the error might be caused by a dependency or library installed on your machine that is required by Qt.

You could try reinstalling Qt and its dependencies to see if that resolves the issue. You can also try removing the line that imports YOLO from your script and check if the error persists. If the error does not persist, it means that YOLOv8 is not the problem here.

If you're still facing the problem after trying the above solutions, feel free to let us know and we'll try our best to help you.

Hope this helps!

**Comment by mcdonasd1212** [comment]
Thank you @glenn-jocher  the issue went away when I removed the  cv2.imshow and only used QT to display the video.

**Comment by glenn-jocher** [comment]
@mcdonasd1212 thank you for letting us know that the issue went away when you removed the `cv2.imshow` function and used QT to display the video instead. It's great to hear that you were able to find a solution to your problem. The issue with `cv2.imshow` is likely related to the fact that it uses a GUI backend (specifically, the HighGUI backend), which can sometimes cause issues when working with other GUI libraries, such as Qt. By using only Qt, you are avoiding potential conflicts between the two.

If you have any further questions or run into any other issues related to YOLOv8, please don't hesitate to ask. We're always here to help!

**Comment by Wandel-lon** [comment]
Hey there,

### Issue
I think the issue does not originate from [ultralytics](https://github.com/ultralytics/ultralytics) but from the vscode extension ms-python.python-2023.10.0 you are using. It has its own python environment and uses the matplotlibrc in `$HOME/.config/matplotlib/matplotlibrc` to determine matplotlib'S backend. If it is not set, it falls back to qt4. 
If you are interested , you could check out how the extensions chooses the backend for matplotlib. You just need to follow the path at the very stop of your traceback.

> Failed to enable GUI event loop integration for 'qt'
> Traceback (most recent call last):
>   File "//.vscode/extensions/ms-python.python-2023.10.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydev_ipython/matplotlibtools.py", line 30, in do_enable_gui
>     enable_gui(guiname)
> 

Further more you are using qt6 which is not supported (in my version of the extension at least, 2023.22.1)

> ```
> PyQt6==6.5.1
> PyQt6-Qt6==6.5.1
> PyQt6-sip==13.5.1
> ```

### Solution

I was not able to get it to run with qt6 yet, but qt5 worked for me. It should be possible to use `[qt6 though](https://www.pythonguis.com/tutorials/pyqt6-plotting-matplotlib/)`

```bash
echo "backend : Qt5Agg" > $HOME/.config/matplotlib/matplotlibrc
```

**Comment by glenn-jocher** [comment]
@Wandel-lon hello!

It appears that the issue is indeed related to the VSCode extension `ms-python.python-2023.10.0` and its interaction with matplotlib's backend configuration. As you've discovered, matplotlib defaults to Qt4 if not otherwise specified, which can cause compatibility issues, especially if you have Qt6 installed.

Reconfiguring the backend to use Qt5Agg by modifying the `matplotlibrc` file, as you've done, is a smart workaround, allowing you to use matplotlib effectively within VSCode.

Thanks for sharing your findings and solution with the community! If you encounter any issues directly related to YOLOv8 or other Ultralytics software, please reach out. Happy coding! 😊

**Comment by Wandel-lon** [comment]
@glenn-jocher hello!

No problem and happy coding to you as well  😊

**Comment by glenn-jocher** [comment]
@Wandel-lon Thank you! If you need any further assistance, feel free to reach out. Have a great day! 😊

**Comment by glenn-jocher** [comment]
Hey there! 🌟

Thanks for sharing your solution with the community! It's great to see you've found a workaround for the issue by setting `guiEventLoop` to `none` in your debug configuration. This can indeed help avoid conflicts with GUI event loops in certain environments. 

For anyone facing a similar issue, modifying your `.vscode/launch.json` like this can be a straightforward fix:

```json
"guiEventLoop": "none"
```

Happy coding, and keep those tips coming! 😊
