### ISSUE TITLE
pose/val.py fails when data set path is an absolute path

### ISSUE THREAD

**Issue by iperminov-mythic** [ultralytics/ultralytics#3119]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Validation

### Bug

```
Traceback (most recent call last):
  File "/python3.9/bin/yolo", line 33, in <module>
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())
  File "/ultralytics/ultralytics/yolo/cfg/__init__.py", line 398, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/python3.9/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/ultralytics/ultralytics/yolo/engine/model.py", line 302, in val
    validator(model=self.model)
  File "/python3.9/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/ultralytics/ultralytics/yolo/engine/validator.py", line 194, in __call__
    stats = self.eval_json(stats)  # update stats
  File "/ultralytics/ultralytics/yolo/v8/pose/val.py", line 183, in eval_json
    anno_json = self.data['path'] / 'annotations/person_keypoints_val2017.json'  # annotations
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```
This error happens when `path` in a dataset yaml is an absolute path, e.g.
coco-pose.yaml:
```
...
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: /some/path/starting/with/shash  # dataset root dir
train: train2017.txt  # train images (relative to 'path') 118287 images
...
```
The reason this error happens only for absolute paths is that `check_det_dataset` only converts `data['path']` from a string to a Path if the path is not absolute one: https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/data/utils.py#L229.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@iperminov-mythic thanks for the bug report! It's a little hard for me to reproduce this since I don't have the same dataset structure as you, but if you can please submit a PR for a solution that works for your use case I can take a look at your proposed changes there. Thanks!

**Comment by glenn-jocher** [comment]
@iperminov-mythic great news 😃! Your original issue may now be resolved ✅ in PR #3242. I've updated check_det_dataset() to always convert `path` to a Pathlib object, irrespective of whether it's an absolute or relative path.

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by iperminov-mythic** [comment]
The PR fixed the problem for me. Thanks a lot!

**Comment by pderrenger** [comment]
@iperminov-mythic you're welcome! I'm glad to hear that the PR fixed the problem for you. If you have any more questions or run into any other issues, feel free to ask. Happy to help!
