### ISSUE TITLE
change model. Clear GPU memory

### ISSUE THREAD

**Issue by Ykrowa** [ultralytics/ultralytics#3129]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello. I have a question. I want to change the model weights. 

1. load the first model yolov8n.pt. (It increase my gpu memory with ~600 mb)
```
self.model = YOLO('./yolov8n.pt') 
self.model.to(0)
```

2. After some time i want to change the model to yolov8x.pt. But i think first need to unload yolov8n.pt from gpu memory. How to do this correctly because i have no found such option in YOLO class?

### Additional
I have tried to cleary my gpu memory . Not works
```
import torch
from ultralytics import YOLO

print('used gpu mem', torch.cuda.memory_allocated()) #0
print('avaiable gpu mem', torch.cuda.memory_reserved()) #0

model = YOLO('yolov8n.pt')
model.predict()

print('used gpu mem with yolo', torch.cuda.memory_allocated()) #46253056
print('avaiable gpu mem', torch.cuda.memory_reserved()) #96468992
 
del model
torch.cuda.empty_cache()

print('used gpu mem after deleting yolo var', torch.cuda.memory_allocated()) #46252032
print('avaiable gpu mem', torch.cuda.memory_reserved()) #71303168
```

_No response_

**Comment by RobbStarkAustria** [comment]
I use a method from this source: [https://stackoverflow.com/questions/70508960/how-to-free-gpu-memory-in-pytorch](url)

**Comment by Ykrowa** [comment]
> https://stackoverflow.com/questions/70508960/how-to-free-gpu-memory-in-pytorch

i have tried both opinions. still same result (

**Comment by pderrenger** [comment]
@Ykrowa it's great to see you're actively exploring solutions! When changing model weights in YOLOv8, it's important to manage GPU memory effectively. To release the GPU memory occupied by the first model before loading the second one, you can use the `torch.cuda.empty_cache()` method after deleting the first model instance.

Here's the process in nutshell:
1. Load `yolov8n.pt` model and use it for your operations.
2. When you want to change to `yolov8x.pt`, delete the first model instance and then call `torch.cuda.empty_cache()` to clear the GPU memory.
3. After that, load the `yolov8x.pt` model for further operations.

It's essential to ensure that all references to the first model are deleted and that using `torch.cuda.empty_cache()` is the last step before loading the next model.

I'm confident that following these steps should help you effectively manage GPU memory when changing model weights. Let me know if you need further assistance! 😊
