### ISSUE TITLE
Returning `results` from SDK `.predict()`

### ISSUE THREAD

**Issue by SkalskiP** [ultralytics/ultralytics#313]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm confused. Just yesterday:

```python
model = YOLO(f'{HOME}/yolov8s-seg.pt')
results = model.predict(source='https://media.roboflow.com/notebooks/examples/dog.jpeg', conf=0.25)
```

Was returning results. Today it is `None`. What's the plan moving forward?

**Comment by AyushExel** [comment]
@SkalskiP can you try again? it should not return None. It should return a generator

**Comment by DCCCXIX** [comment]
@SkalskiP 
 In 8.0.5 return_outputs seems to default to False, so it returns None, add "return_outputs=True".

**Comment by AyushExel** [comment]
@SkalskiP @DCCCXIX Yeah there have been temp solutions to fix memory overloading issues. 
We are working on a better stable solution to provide an interface to outputs. You can follow the progress here. We're trying to put it out asap
https://github.com/ultralytics/ultralytics/pull/314

**Comment by SkalskiP** [comment]
@DCCCXIX and @AyushExel thanks for pro tips ;)

**Comment by SkalskiP** [comment]
@AyushExel I'm using `Ultralytics YOLOv8.0.6`. I tried to use `return_outputs=True` and the generator that it `.predict()` returns, but I behaved weirdly, to say the least. Take a look:

```python
model = YOLO(f'{HOME}/yolov8n.pt')
generator = model.predict(
    source='https://media.roboflow.com/notebooks/examples/dog.jpeg',
    conf=0.25, 
    return_outputs=True
)
```

Now:

```python
list(generator)
> [{}]
```

But:

```python
i = iter(generator)
x = next(I)
x
> {
    'det': array([
        [          0,         314,         625,        1278,     0.72656,           0],
        [         55,         250,         648,        1266,     0.28857,          16],
        [        633,         720,         701,         786,     0.28296,           2]], 
    dtype=float32)
}


```

Doing `list(generator)` is valid Python syntax, but it returns incorrect results. Or rather no results.

**Comment by Laughing-q** [comment]
@SkalskiP oh I think that's because there's a `clear()` operation:
[https://github.com/ultralytics/ultralytics/blob/0cb87f7dd340a2611148fbf2a0af59b544bd7b1b/ultralytics/yolo/engine/predictor.py#L200](https://github.com/ultralytics/ultralytics/blob/0cb87f7dd340a2611148fbf2a0af59b544bd7b1b/ultralytics/yolo/engine/predictor.py#L200)
BTW we're working on upgrading `Result`, we'll release it soon. :)

**Comment by SkalskiP** [comment]
Hahaha @Laughing-q not sure if I should be happy or scared 😱
