### ISSUE TITLE
Keypoints Size

### ISSUE THREAD

**Issue by Justinfungi** [ultralytics/ultralytics#3130]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can we change the keypoint size in CLI or python code. i read the code but cannot find the argument for changing the keypoints size

**Comment by swe-cognitica** [comment]
Changing the radius will do it. in plotting.py, function kpts() has radius=5 by default. Changing that will modify the keypoint size.

**Comment by glenn-jocher** [comment]
Hello! @swe-cognitica, 
To change the size of the keypoints in YOLOv8, you can modify the `radius` parameter in the `kpts()` function inside `plotting.py`. By default the `radius` is set to 5, but you can increase or decrease that value as you desire. Modifying this parameter will change the size of the keypoints in the output plots. 

I hope this helps!

**Comment by adkbbx** [comment]
@glenn-jocher Is it possible to do this using google colab.
