### ISSUE TITLE
Constantlt assignment label

### ISSUE THREAD

**Issue by Justinfungi** [ultralytics/ultralytics#3131]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Like i have 3 characters in the video, but the scenes are discontinuous. 

Let say we get keypoints by python
kpts1, kpts2, kpts3 = keypoints.xy[1].ravel(), keypoints.xy[2].ravel(), keypoints.xy[3].ravel()

How could i asset the kpt1 i get in scene 1 is for person 1 while in scene 2, i can also get the kpt1 which belongs to person 1

i have tried deepsort but it fail to do so for the discontinous scenesdeep sort

### Use case

Multi-object tracking

### Additional

NA

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@Justinfungi hi there! It seems like you're looking for a solution to effectively associate keypoints with specific individuals across discontinuous scenes in a video for multi-object tracking. One approach you can consider is using the YOLOv8's "Track" mode, which enables real-time object tracking. By leveraging the keypoint estimation capabilities of YOLOv8, you can track individuals across scenes based on their unique keypoints, allowing you to associate the correct keypoints with the respective persons. 

For a more detailed understanding of how to achieve this, you can refer to the Ultralytics documentation on the "Track" mode along with the keypoint estimation task for YOLOv8. This should provide you with the necessary insights to implement the solution for your use case.

Feel free to explore these features, and if you have any further questions or need additional assistance, please don't hesitate to ask! 🚀
