### ISSUE TITLE
Visualize Segmentation Mask from the Yolov8 Segmentation Dataset format

### ISSUE THREAD

**Issue by ahmadmustafaanis** [ultralytics/ultralytics#3137]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to understand the yolov8-segmentation dataset format, and working with coco1288-seg.yaml dataset. Here is an example label for coco128-seg/labels/train2017/000000000009.txt:
```txt
45 0.782016 0.986521 0.937078 0.874167 0.957297 0.782021 0.950562 0.739333 0.825844 0.561792 0.714609 0.420229 0.657297 0.391021 0.608422 0.4 0.0303438 0.750562 0.0016875 0.811229 0.003375 0.889896 0.0320156 0.986521
45 0.557859 0.143813 0.487078 0.0314583 0.859547 0.00897917 0.985953 0.130333 0.984266 0.184271 0.930344 0.386521 0.80225 0.480896 0.763484 0.485396 0.684266 0.39775 0.670781 0.3955 0.679219 0.310104 0.642141 0.253937 0.561234 0.155063 0.559547 0.137083
50 0.39 0.727063 0.418234 0.649417 0.455297 0.614125 0.476469 0.614125 0.51 0.590583 0.54 0.569417 0.575297 0.562354 0.601766 0.56 0.607062 0.536479 0.614125 0.522354 0.637063 0.501167 0.665297 0.48 0.69 0.477646 0.698828 0.494125 0.698828 0.534125 0.712938 0.529417 0.742938 0.548229 0.760594 0.564708 0.774703 0.550583 0.778234 0.536479 0.781766 0.531771 0.792359 0.541167 0.802937 0.555292 0.802937 0.569417 0.802937 0.576479 0.822359 0.576479 0.822359 0.597646 0.811766 0.607062 0.811766 0.618833 0.818828 0.637646 0.820594 0.656479 0.827641 0.687063 0.827641 0.703521 0.829406 0.727063 0.838234 0.708229 0.852359 0.729417 0.868234 0.750583 0.871766 0.792938 0.877063 0.821167 0.884125 0.861167 0.817062 0.92 0.734125 0.976479 0.711172 0.988229 0.48 0.988229 0.494125 0.967063 0.517062 0.912937 0.508234 0.832937 0.485297 0.788229 0.471172 0.774125 0.395297 0.729417
45 0.375219 0.0678333 0.375219 0.0590833 0.386828 0.0503542 0.424156 0.0315208 0.440797 0.0281458 0.464 0.0389167 0.525531 0.115583 0.611797 0.222521 0.676359 0.306583 0.678875 0.317354 0.677359 0.385271 0.66475 0.394687 0.588594 0.407458 0.417094 0.517771 0.280906 0.604521 0.0806562 0.722208 0.0256719 0.763917 0.00296875 0.809646 0 0.786104 0 0.745083 0 0.612583 0.03525 0.613271 0.0877187 0.626708 0.130594 0.626708 0.170437 0.6025 0.273844 0.548708 0.338906 0.507 0.509906 0.4115 0.604734 0.359042 0.596156 0.338188 0.595141 0.306583 0.595141 0.291792 0.579516 0.213104 0.516969 0.129042 0.498297 0.100792 0.466516 0.0987708 0.448875 0.0786042 0.405484 0.0705208 0.375219 0.0678333 0.28675 0.108375 0.282719 0.123167 0.267078 0.162854 0.266062 0.189083 0.245391 0.199833 0.203516 0.251625 0.187375 0.269771 0.159641 0.240188 0.101125 0.249604 0 0.287271 0 0.250271 0 0.245563 0.0975938 0.202521 0.203516 0.145354 0.251953 0.123167 0.28675 0.108375
49 0.587812 0.128229 0.612281 0.0965625 0.663391 0.0840833 0.690031 0.0908125 0.700109 0.10425 0.705859 0.133042 0.700109 0.143604 0.686422 0.146479 0.664828 0.153188 0.644672 0.157042 0.629563 0.175271 0.605797 0.181021 0.595 0.147437
49 0.7405 0.178417 0.733719 0.173896 0.727781 0.162583 0.729484 0.150167 0.738812 0.124146 0.747281 0.0981458 0.776109 0.0811875 0.804094 0.0845833 0.814266 0.102667 0.818516 0.115104 0.812578 0.133208 0.782906 0.151292 0.754063 0.172771
49 0.602656 0.178854 0.636125 0.167875 0.655172 0.165125 0.6665 0.162375 0.680391 0.155521 0.691719 0.153458 0.703047 0.154146 0.713859 0.162375 0.724156 0.174729 0.730844 0.193271 0.733422 0.217979 0.733938 0.244063 0.733422 0.281813 0.732391 0.295542 0.728266 0.300354 0.702016 0.294854 0.682969 0.28525 0.672156 0.270146
49 0.716891 0.0519583 0.683766 0.0103958 0.611688 0.0051875 0.568828 0.116875 0.590266 0.15325 0.590266 0.116875 0.613641 0.0857083 0.631172 0.0857083 0.6565 0.083125 0.679875 0.0883125 0.691563 0.0961042 0.711031 0.0649375
```
How should I visualize this on the actual image to understand the dataset correctly? Thanks.

**Comment by xovobobo** [comment]
its a polygon area.

```
import cv2
import numpy as np
from random import randint

with open('./000000000009.txt', 'r') as f:
    labels = f.read().splitlines()
img = cv2.imread('./000000000009.jpg')
h,w = img.shape[:2]

for label in labels:
    class_id, *poly = label.split(' ')
    
    poly = np.asarray(poly,dtype=np.float16).reshape(-1,2) # Read poly, reshape
    poly *= [w,h] # Unscale
    
    cv2.polylines(img, [poly.astype('int')], True, (randint(0,255),randint(0,255),randint(0,255)), 2) # Draw Poly Lines
    # cv2.fillPoly(img, [poly.astype('int')], (randint(0,255),randint(0,255),randint(0,255)), cv2.LINE_AA) # Draw area


    cv2.imshow('img with poly', img)
    cv2.waitKey(0)
```

**Comment by itstechaj** [comment]
# Just change the annotation path with path to your annotation text file of yolov8 segmentation 

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
from PIL import Image, ImageDraw,ImageFont
import random
from matplotlib import pyplot as plt
def maskVisualize(image,mask):
  fontsize = 18
  f, ax = plt.subplots(2, 1, figsize=(8, 8))
  ax[0].imshow(image)
  ax[1].imshow(mask)

#Define the boundary coordinates as a list of (x, y) tuples
'''
def draw_points_on_image(image, points):
  #resize image to 640*640
  resimg = cv2.resize(image, (640,640))
  #iterate for each mask
  for mask in points:
    #Draw each point on the image
    for point in mask:
        cv2.circle(resimg, tuple(point), 1, (0,0,255), -1,)
  #Display the image
  cv2_imshow(resimg)
'''
#convert the mask from the txt file(annotation_path is path of txt file) to array of points making that mask.
def generate_points(annotation_path=''):
  labels=[] # this will store labels
  #we are assuming that the image is of dimension (640,640). then you have annotated it.
  with open(annotation_path, "r") as file:
    points=[]
    for line in file:
      label,lis=line.split()[0],line.split()[1:]
      labels.append(label)
      lis=list(map(float,lis))
      for i in range(len(lis)):
        lis[i]=int(lis[i]*640)
      newlis=[]
      i=0
      while(i<len(lis)):
        #appendint the coordinates as a tuple (x,y)
        newlis.append((lis[i],lis[i+1]))
        i+=2
      points.append(newlis)
    return labels,points


#the below function convert the boundary coordinates to mask array (it shows mask if you pass 1 at show)
#the mask array is required when we want to augument the mask also using albumentation
def convert_boundary_to_mask_array(labels,points, show=0):
  #Create a new image with the same size as the desired mask
  mask = Image.new("L", (640, 640), 0)
  draw = ImageDraw.Draw(mask)
  for i,boundary_coords in enumerate(points):
    #boundary_coords represent boundary of one polygon
    #Draw the boundary on the mask image
    draw.polygon(boundary_coords,fill=1)
    #Also put the label as text 
    #Compute the centroid of the polygon
    centroid_x = sum(x for x, _ in boundary_coords) / len(boundary_coords)
    centroid_y = sum(y for _, y in boundary_coords) / len(boundary_coords)
    centroid = (int(centroid_x), int(centroid_y))
    #Write the name at the centroid
    text = str(labels[i])
    #Write the label at the centroid
    font = ImageFont.load_default()
    text_w, text_h = draw.textsize(text, font=font)
    text_pos = (centroid[0] - text_w/2, centroid[1] - text_h/2)
    draw.text(text_pos, text, font=font, fill='black')
  #Convert the mask image to a numpy array
  mask_array = np.array(mask)*255
  #Show the mask image
  if(show==1):
    #Image.fromarray(mask_array).show()
    cv2_imshow(mask_array)
  return mask_array

#function that takes mask path (yolov8 seg txt file) and return mask of an image (shape of mask == shape of image)
def generate_mask(annotation_path='',show=0):
  #pass show=1 for showing the generated mask
  #firstly we generate the points (coordinates) from the annotations
  labels,points=generate_points(annotation_path)
  #once we get the points we will now generate the mask image from these points (binary mask image (black/white))
  #mask is represented by white and ground is represented as black
  mask_array=convert_boundary_to_mask_array(labels,points,show)
  return mask_array
mask_array=generate_mask(annotation_path=**'/content/resized_image.txt'**,show=0)
maskVisualize(np.array(img),mask_array)

# _this code assumes that the image size is (640,640) . you can use these code to resize your image after reading._
from PIL import Image

#Open the image
img = Image.open('/content/img.jpg')

#Resize the image to 640 by 640
img = img.resize((640, 640))

#Save the resized image
img.save('resized_image.jpg')

**Comment by pderrenger** [comment]
@ahmadmustafaanis certainly! Here's the well-formatted code:

```python
import cv2
import numpy as np
from google.colab.patches import cv2_imshow
from PIL import Image, ImageDraw, ImageFont
from matplotlib import pyplot as plt

image_path = "/content/img.jpg"  # path of the image, change it
annotation_path = "/content/annotation.txt"  # path of the annotation text file, change it

# Helper functions below assume that the image size is (640,640). Hence resizing the image.
# Open the image
img = Image.open(image_path)
# Resize the image to 640 by 640
img = img.resize((640, 640))

# <--------- Helper functions starts here ----------------------------------->

def maskVisualize(image, mask):
    fontsize = 18
    f, ax = plt.subplots(2, 1, figsize=(8, 8))
    ax[0].imshow(image)
    ax[1].imshow(mask)


# Convert the mask from the txt file(annotation_path is path of txt file) to array of points making that mask.
def generate_points(annotation_path=''):
    labels = []  # this will store labels
    # assuming that the image is of dimension (640,640), then you have annotated it.
    with open(annotation_path, "r") as file:
        points = []
        for line in file:
            label, lis = line.split()[0], line.split()[1:]
            labels.append(label)
            lis = list(map(float, lis))
            for i in range(len(lis)):
                lis[i] = int(lis[i] * 640)
            newlis = []
            i = 0
            while(i < len(lis)):
                # appending the coordinates as a tuple (x,y)
                newlis.append((lis[i], lis[i+1]))
                i += 2
            points.append(newlis)
    return labels, points


# Convert the boundary coordinates to a mask array
def convert_boundary_to_mask_array(labels, points, show=0):
    # Create a new image with the same size as the desired mask
    mask = Image.new("L", (640, 640), 0)
    draw = ImageDraw.Draw(mask)
    for i, boundary_coords in enumerate(points):
        # Draw the boundary on the mask image
        draw.polygon(boundary_coords, fill=1)
        # Also put the label as text
        # Compute the centroid of the polygon
        centroid_x = sum(x for x, _ in boundary_coords) / len(boundary_coords)
        centroid_y = sum(y for _, y in boundary_coords) / len(boundary_coords)
        centroid = (int(centroid_x), int(centroid_y))
        # Write the name at the centroid
        text = str(labels[i])
        # Write the label at the centroid
        font = ImageFont.load_default()
        text_w, text_h = draw.textsize(text, font=font)
        text_pos = (centroid[0] - text_w/2, centroid[1] - text_h/2)
        draw.text(text_pos, text, font=font, fill='black')
    # Convert the mask image to a numpy array
    mask_array = np.array(mask) * 255
    # Show the mask image
    if show == 1:
        cv2_imshow(mask_array)
    return mask_array


# Function that takes mask path (yolov8 seg txt file) and return mask of an image (shape of mask == shape of image)
def generate_mask(annotation_path='', show=0):
    # pass show=1 for showing the generated mask
    # firstly we generate the points (coordinates) from the annotations
    labels, points = generate_points(annotation_path)
    # once we get the points we will now generate the mask image from these points (binary mask image (black/white))
    # mask is represented by white and ground is represented as black
    mask_array = convert_boundary_to_mask_array(labels, points, show)
    return mask_array

# <---------- Helper Functions Ends here ------------------------------------------------------------->

mask_array = generate_mask(annotation_path=annotation_path, show=0)
maskVisualize(np.array(img), mask_array)
```

I hope this makes it easier to understand the code!

**Comment by sasyed3** [comment]
Hello @pderrenger 

Sorry, I am late to the party. 
I used your code to generate the binary masks from my label files. Before 2025, my masks were coming out beautiful. However, I believe that the 'textsize' function has been deprecated. I replaced it with textlength but now my masks are coming out to be awkward. Is there any fix to that. 

![Image](https://github.com/user-attachments/assets/063e1a74-1aee-4542-b6c0-5afe9d4320f9)

<img width="402" alt="Image" src="https://github.com/user-attachments/assets/ede077d8-d5f4-42e7-96a5-1bd8dde57c85" />

I am attaching two pictures of the same masks: before and after textsize. Do you know if there is any fix to this?
