### ISSUE TITLE
yolo8 classification

### ISSUE THREAD

**Issue by Haibara-z** [ultralytics/ultralytics#3139]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to get the classes name in yolo8 image classification? The output seem to be sorted by score.

**Comment by Ykrowa** [comment]
results = model.predict(source=np_img_orig, conf=CONF, iou=IOU)
        classes = results[0].boxes.cls.int().tolist()
        boxes = results[0].boxes.xyxy.int().tolist()
        conf = results[0].boxes.conf.tolist()

**Comment by Haibara-z** [comment]
how to get the classes name when task is classify in cpp inference&nbsp;


&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月12日(星期一) 晚上7:00
收件人: ***@***.***&gt;; 
抄送: "zhu ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ultralytics/ultralytics] yolo8 classification (Issue #3139)





     results = model.predict(source=np_img_orig, conf=CONF, iou=IOU)     classes = results[0].boxes.cls.int().tolist()     boxes = results[0].boxes.xyxy.int().tolist()     conf = results[0].boxes.conf.tolist()
