### ISSUE TITLE
TTA Customization 

### ISSUE THREAD

**Issue by aloideao** [ultralytics/ultralytics#3142]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

https://github.com/ultralytics/yolov5/blob/8c6f9e15bfc0000d18b976a95b9d7c17d407ec91/models/yolo.py#L125-L137
how to customize TTA in yolov8 similar to this one ?

**Comment by aloideao** [comment]
@glenn-jocher

**Comment by mandal4** [comment]
Same question here. How did you solve it?
