### ISSUE TITLE
How to remove the background class from the confusion matrix?

### ISSUE THREAD

**Issue by Guillermo-Ingles** [ultralytics/ultralytics#3146]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I am training a set of images that has two classes: boat and airplane. However, when I do the training or validation, the background class appears in the confusion matrix, even though I do not have it and I am sure that all images are labeled.. I know it is recommended to use the background class to improve results in terms of FP, but I would like to see a bit of the performance without the background class. It seems that somehow, by default, YOLOv8 generates background images since true background labels can be seen in the confusion matrix. In addition, I am using cross-validation, and in each partition, I have a different number of true background labels in the confusion matrix. If anyone knows a way to prevent it from generating background images, I would be very grateful?

Here is an example of one of the confusion matrices I get:

![image](https://github.com/ultralytics/ultralytics/assets/99696352/de2041d6-05bc-47ce-b7fd-c1eede187b70)

And here my .yaml

![image](https://github.com/ultralytics/ultralytics/assets/99696352/69b11d6f-1164-4a5c-9e57-5d40239c79fd)

**Comment by DamnScallion** [comment]
> 
I got exactly the same issue. Can't find any solution from docs. May try another way to visualize the confusion matrix XD

**Comment by glenn-jocher** [comment]
@DamnScallion hello,

Thanks for reaching out with your concern. The confusion matrix visualization is built-in within YOLOv8 and the background class is included by default as it's an integral aspect of the algorithm. YOLOv8 considers any region where there's no object as a 'background' - it's a characteristic feature of how YOLOv8 operates.

However, if you're interested purely in the performance metrics of your specified classes (in your case, boats and airplanes) without the influence of the 'background' class, you might want to consider exploring that outside of the provided confusion matrix. 

You can extract the raw confusion data and use it to build a customized confusion matrix that suits your exact requirement using suitable data manipulation and visualization tools. The details should be available in your training or validation logs.

Remember, the 'background' class isn't an error or issue - it's inherent to how YOLOv8 operates and removing it entirely might lead to unexpected results or potentially inaccurate models.

We hope this helps clarify your concern! If you have more questions or need further help understanding any aspect of YOLOv8, please feel free to ask.

Best,
Glenn and the Ultralytics Team

**Comment by DamnScallion** [comment]
> @DamnScallion hello,
> 
> Thanks for reaching out with your concern. The confusion matrix visualization is built-in within YOLOv8 and the background class is included by default as it's an integral aspect of the algorithm. YOLOv8 considers any region where there's no object as a 'background' - it's a characteristic feature of how YOLOv8 operates.
> 
> However, if you're interested purely in the performance metrics of your specified classes (in your case, boats and airplanes) without the influence of the 'background' class, you might want to consider exploring that outside of the provided confusion matrix.
> 
> You can extract the raw confusion data and use it to build a customized confusion matrix that suits your exact requirement using suitable data manipulation and visualization tools. The details should be available in your training or validation logs.
> 
> Remember, the 'background' class isn't an error or issue - it's inherent to how YOLOv8 operates and removing it entirely might lead to unexpected results or potentially inaccurate models.
> 
> We hope this helps clarify your concern! If you have more questions or need further help understanding any aspect of YOLOv8, please feel free to ask.
> 
> Best, Glenn and the Ultralytics Team

That's what I gonna do with visualizing the confusion matrix. Will figure it out with other tools. Anyway, thanks for your time and suggestion 👍

**Comment by glenn-jocher** [comment]
You're welcome, @DamnScallion! I'm glad to hear that you found the information helpful. Just remember, the data and metrics that YOLOv8 outputs are very flexible, and can be manipulated to suit your custom visualization needs. Feel free to reach out if you have any other questions or clarifications about using YOLOv8. Happy coding!

**Comment by nardinameen** [comment]
> @DamnScallion hello,
> 
> Thanks for reaching out with your concern. The confusion matrix visualization is built-in within YOLOv8 and the background class is included by default as it's an integral aspect of the algorithm. YOLOv8 considers any region where there's no object as a 'background' - it's a characteristic feature of how YOLOv8 operates.
> 
> However, if you're interested purely in the performance metrics of your specified classes (in your case, boats and airplanes) without the influence of the 'background' class, you might want to consider exploring that outside of the provided confusion matrix.
> 
> You can extract the raw confusion data and use it to build a customized confusion matrix that suits your exact requirement using suitable data manipulation and visualization tools. The details should be available in your training or validation logs.
> 
> Remember, the 'background' class isn't an error or issue - it's inherent to how YOLOv8 operates and removing it entirely might lead to unexpected results or potentially inaccurate models.
> 
> We hope this helps clarify your concern! If you have more questions or need further help understanding any aspect of YOLOv8, please feel free to ask.
> 
> Best, Glenn and the Ultralytics Team

 how can i create a confusion matrix training or validation logs.
