### ISSUE TITLE
Tracker_id lost

### ISSUE THREAD

**Issue by litaldavar** [ultralytics/ultralytics#3148]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I was so happy to see there is a native tracker for YOLOv8
I started to use it with roboflow supervision and found a problem
whenever my object moves and the model can't detect it and then comes back it gets a new id
that wasn't the case when I was using ByteTrack (which is very not useable today)
Is there any way to prevent that from happening ?
I'm attaching a clip for you to see the problem
thanks

https://github.com/ultralytics/ultralytics/assets/4908360/7ec44a85-b5c5-45cf-be3e-45cdb0f2e3dc

**Comment by SuperMaximus1984** [comment]
Same here. But it seems to be a normal behavior of a tracker. Since your "old" object appears again, it's considered a new one for Yolo & the Tracker. I am using Deepsort, it subjectively gives an impression of better quality than other trackers. Need to test some more trackers as an alternative.

**Comment by litaldavar** [comment]
I used ByteTrack, and it worked very well. Unfortunately, ByteTrack is not maintained, many of its libraries are not in use, and it isn't easy to work with.

**Comment by bit-scientist** [comment]
@litaldavar hi, did you also annotate your prediction model's (used for tracking) data when the object disappears? Here's my suggestions:
- You may want to refine the annotation process a little more thoroughly, label the object even if it's occluded by the glass;
- Use heavy augmentation for training the dataset;
- increase 'track_buffer' from 30 to like 40 or more.

Let's see what you get. Good luck!

**Comment by ImSuMyatNoe** [comment]
hi @litaldavar may i know that how do you track with your custom weight model? When I track with my custom model, there is no detection occur. I am training on yolov8x-seg.pt file. Could someone please kindly suggest me? @bit-scientist @SuperMaximus1984 @plashchynski @akx

**Comment by bit-scientist** [comment]
@ImSuMyatNoe hi, I'd suggest you open a new issue and post your code examples and explain in more detail. You may cite that issue here and we can see what you got. Thanks

**Comment by litaldavar** [comment]
import os
import sys
import cv2
import numpy as np
import ultralytics
import supervision as sv
import json
from ultralytics import YOLO

class NativeTracking:
    def __init__(self, home_dir, out_dir):
        self.home_dir = home_dir
        self.out_dir = out_dir
        self.model = YOLO(r"/home/lital/NativeTrackingYOLOv8/runs/detect/train/weights/best.pt")

    def trackObjects(self):
        for f in os.listdir(self.home_dir):
            vFile = os.path.join(self.home_dir, f)

            fileType = vFile.split('.')[-1]

            if fileType != 'avi' and fileType != 'mp4':
                continue

            SOURCE_VIDEO_PATH = vFile
            # create target file for writing
            target_video_path = os.path.join(self.out_dir, ('tracked_' + f))
            
            vid = cv2.VideoCapture(vFile)
            self.fps = vid.get(cv2.CAP_PROP_FPS)
            self.height = int(vid.get(cv2.CAP_PROP_FRAME_HEIGHT))  # always 0 in Linux python3
            self.width = int(vid.get(cv2.CAP_PROP_FRAME_WIDTH))  # always 0 in Linux python3
            fourcc = cv2.VideoWriter_fourcc(*'mp4v')
            video = cv2.VideoWriter(target_video_path, fourcc, 20.0, (self.width, self.height))

            # process the video file
            self.ProcessVideo(vFile, video, outfile)


    def ProcessVideo(self,source_file_path,  video, outfile):
        box_annotator = sv.BoxAnnotator(
            thickness=2,
            text_thickness=1,
            text_scale=0.5
        )
        
        print(f"starting process of {source_file_path}")
        for result in self.model.track(source=source_file_path, stream=True):
            dict_one_frame = {}
            frame = result.orig_img
            detections = sv.Detections.from_yolov8(result)

            if result.boxes.id is not None:
                detections.tracker_id = result.boxes.id.cpu().numpy().astype(int)

            
            labels = [
                f"#{tracker_id} {self.model.model.names[class_id]} {confidence:0.2f}"
                for _, confidence, class_id, tracker_id
                in detections
            ]

           
            frame = box_annotator.annotate(scene=frame, detections=detections, labels=labels)
            video.write(frame)

       
        video.release()
        cv2.destroyAllWindows()
This is my code Where to change the track_buffer ?
Thanks

**Comment by pderrenger** [comment]
@litaldavar the `track_buffer` can be adjusted inside the YAML configuration file for the tracker. You can find the configuration file at `ultralytics/tracker/cfg/your-tracker.yaml`. Inside the YAML file, you can increase the value of `track_buffer` to your desired value, for example, from 30 to 40 or more. This adjustment may help improve the tracking behavior of the YOLOv8 model.

Remember to restart the tracking process after modifying the configuration to apply the changes. Good luck!
