### ISSUE TITLE
Confusion about different TFLite quantization methods and corresponding output files

### ISSUE THREAD

**Issue by MaikysuN** [ultralytics/ultralytics#3153]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am currently exporting my YOLOv8 model with the following export call to get all possible quantization outputs in one call:
` model.export(format="tflite",
                     imgsz=(128, 128),
                     half=False,
                     int8=True)`

The export call stores 5 different tflite files:

1. best_float32.tflite 
2. best_float16.tflite
3. best_int8.tflite
4. best_full_integer_quant.tflite
5. best_integer_quant.tflite

In the [TensorFlow Post-Training Quantization Documentation ](https://www.tensorflow.org/lite/performance/post_training_quantization) there are different methods showcased. I am confused which of these methods map to the yolo output files. The first two should be pretty clear, because they map to basically no quantization (float32) and float16 quantization through the half parameter.  Especially, I was wondering whether yolo utilizes the dynamic range quantization method.

But what is the difference between the last three integer quantizations? And how do they map to the methods described in the tf reference?

**Comment by pderrenger** [comment]
@MaikysuN hi there! Glad to hear you're exploring different quantization methods for your YOLOv8 model. 🧐 Let's break it down:

- The `best_int8.tflite` file is the result of 8-bit integer quantization, where weights and activations are quantized to int8.
  
- The `best_full_integer_quant.tflite` and `best_integer_quant.tflite` files both stem from integer quantization, but their specific mapping to TensorFlow's post-training quantization methods is not directly one-to-one. 

Both `best_full_integer_quant.tflite` and `best_integer_quant.tflite` files use integer quantization, with the difference likely residing in their quantization strategies and optimizations. 

I'd recommend referencing the YOLOv8's export code or documentation for more precise details on how these map to TensorFlow's quantization methods.

Hope this sheds some light on the different outputs you're getting! If you have further questions, feel free to ask. 😊

**Comment by glenn-jocher** [comment]
@pderrenger Hello! I understand the quantization options can be a bit confusing. Let's clarify:

- `best_float32.tflite` is the standard TensorFlow Lite model with no quantization.
- `best_float16.tflite` applies 16-bit floating-point quantization, reducing model size and potentially speeding up inference on compatible hardware.
- `best_int8.tflite` likely corresponds to TensorFlow's dynamic range quantization, where weights are quantized to int8, but activations are dynamically quantized at runtime.
- `best_full_integer_quant.tflite` is fully quantized with int8 weights and activations, requiring a representative dataset for calibration.
- `best_integer_quant.tflite` is also an int8 quantized model, but the exact difference from `best_full_integer_quant.tflite` would be in the specifics of the quantization approach, which can be found in our documentation or export code.

For the exact mapping to TensorFlow's methods, please refer to our documentation. If you need more help, we're here for you! 😄

**Comment by ivanstepanovftw** [comment]
> I'd recommend referencing the YOLOv8's export code or documentation for more precise details on how these map to TensorFlow's quantization methods.

Yes, please, do reference code or documentation when generating your hallucinations.
