### ISSUE TITLE
sum() instead of mean() in segmentation loss

### ISSUE THREAD

**Issue by LaCandela** [ultralytics/ultralytics#3159]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

In the segmentation loss there should be a sum() instead of a the first mean() here:
https://github.com/ultralytics/ultralytics/blob/c340f84ce9325de720fbd9ada6523a28fc432651/ultralytics/yolo/utils/loss.py#L270

(crop_mask(loss, xyxy).mean(dim=(1, 2)) / area).mean()
                                        ^
The output of crop_mask() is not really cropped but full of zeros outside of the instance bbox. Thus I think .mean(dim=(1, 2) is not appropriate here, there should be a sum(1,2) instead. What do you think?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@LaCandela current implementation is correct. If you can produce performance improvements with alternate loss implementations such as your suggestion above then please provide before and after training results. Thank you!

**Comment by gasharper** [comment]
@LaCandela I think `crop_mask(loss, xyxy).mean(dim=(1, 2)) / area` is equal to `really_crop_mask(loss, xyxy).mean(1,2)`, because
```python
crop_mask(loss, xyxy).mean(1,2)/area
=crop_mask(loss, xyxy).sum(1,2)/(160*160)/(norm_scale_w*norm_scale_h)
=crop_mask(loss, xyxy).sum(1,2)/((proto_scale_w/160)*(proto_scale_h/160))/(160*160)
=crop_mask(loss, xyxy).sum(1,2)/(proto_scale_w*proto_scale_h)
=really_crop_mask(loss, xyxy).mean(1,2)   
```

The implementation is based on not really `crop_mask()` because not all the masks are aligned at the same location.
