### ISSUE TITLE
Performance (mAP) drops in latest versions

### ISSUE THREAD

**Issue by bogdan-galileo** [ultralytics/ultralytics#3163]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

The performance of Yolov8x is significantly lower when using the latest version 8.0.117 (as compared to a version from a few months 8.0.80). I did not try versions in between to find what is the cause of this. 

I did multiple tests and evaluated the model in different ways, and reproduced the issue multiple times. It seems like the model is not training as well with the same parameters with newer versions.

![Screenshot 2023-06-13 at 2 37 08 PM](https://github.com/ultralytics/ultralytics/assets/112427971/c5110c8f-1ed1-4b1a-a30d-75a4ba1a9721)
![Screenshot 2023-06-13 at 2 58 42 PM](https://github.com/ultralytics/ultralytics/assets/112427971/45f38fdd-259d-4f59-b6be-e536e295a899)

### Environment

- Google Colab, various GPUs V100 or T4
- Python 3.10
- ultralytics v8.0.80 & v8.0.117 (latest at the momen)

### Minimal Reproducible Example

`yolo detect train model=yolov8x data=/content/datasets/data.yaml epochs=2`

for any data

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Kayzwer** [comment]
I dont think it is a bug, I think it is because of warmup epochs, where the first few epochs, the lr is very high, try set it to 0, and run the test again.

**Comment by bogdan-galileo** [comment]
> I dont think it is a bug, I think it is because of warmup epochs, where the first few epochs, the lr is very high, try set it to 0, and run the test again.

@Kayzwer thanks. Did the default lr change between these two versions ? If not, maybe I should specify that the tests are done in a new notebook/environment (to ensure that they do start from the same checkpoint).

**Comment by bogdan-galileo** [comment]
@Kayzwer Ha, I think you found it. In this commit https://github.com/ultralytics/ultralytics/commit/8940a27bdb26895f09a1554514a9a46312aa89c3 to version 8.0.114 the default optimizer was changed from SGD to auto, which in my particular case changed a lot on the lr.

Added a comment https://github.com/ultralytics/ultralytics/commit/8940a27bdb26895f09a1554514a9a46312aa89c3#commitcomment-117925911, I can close that bug though. Thanks!
