### ISSUE TITLE
Is save_json option implemented in YOLO.val() ?

### ISSUE THREAD

**Issue by cheezafizz** [ultralytics/ultralytics#3167]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I tried to use the save_json option by setting YOLO(model=MY_MODEL_PATH).val(save_json=True) but could not find any json file in my saving directory.

I discovered that this feature should be implemented in either BaseValidator or ClassificationValidator, since it seems that BaseValidator checks if save_json is True and dumps json file that has been recorded in self.jdict.

But I have never seen any code that adds dictionary items to jdict at all.

Is there something I am missing, or is it simply unimplemented to be implemented?

**Comment by Maya084** [comment]
I am wondering the same. I can't find any json files.

**Comment by glenn-jocher** [comment]
@Maya084 thanks for reaching out. The `save_json` option should indeed create a JSON file in your output directory, providing a record of the validation results. If you're not seeing this file, there are a few possibilities:

1. There may be an issue with your file paths. Please double-check that you're looking in the correct directory for the output file.

2. If the `jdict` dictionary is not being populated as expected, the `save_json` function wouldn't have anything to write to file. It could be that there are some conditions under which the dataset or model you're using doesn't populate `jdict`.

3. The feature could potentially be unimplemented or partially implemented, given its presence in the codebase.

To be sure, you may want to delve deeper into the code related to this feature or debug it to better understand what could be going wrong.

The Ultralytics team strives for ongoing improvement of the YOLOv8 repository, so we definitely appreciate your feedback and will take these questions into consideration in our future updates. Thanks for helping make YOLOv8 even better.

**Comment by sumitclearquote** [comment]
@glenn-jocher In what bbox format does predictions.json store results. Also, are the results after NMS being implemented?

**Comment by glenn-jocher** [comment]
@sumitclearquote hi there! The `predictions.json` file stores results in the `[x_center, y_center, width, height, confidence, class]` format, all normalized to the image size. Yes, the results included are after applying Non-Maximum Suppression (NMS) to ensure each detected object is represented by the most accurate bounding box. Hope this helps! 😊

**Comment by glenn-jocher** [comment]
The discrepancy occurs because the **confusion matrix** only includes **True Positives (TP)** and **False Positives (FP)** that meet the validation IoU threshold (default `iou=0.6`), while `predictions.json` contains **all post-NMS detections** regardless of IoU matching. For example, low-IoU predictions appear in the JSON but not in the matrix. Confirm your validation uses matching settings for `conf`/`iou` in both outputs. 

See [YOLO Validation Documentation](https://docs.ultralytics.com/modes/val/) for thresholds and metrics details.
