### ISSUE TITLE
About yolov8s-seg train custom dataset

### ISSUE THREAD

**Issue by arkerman** [ultralytics/ultralytics#317]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, buddy ! I am training my segmentation dataset by yolov8s-seg . But i got a problem with the value of P , R and mAP . I trained the seg model for 300 epochs , but i got very low value of P , R . And the P_R curve is very terrible . When i used the ```best.pt``` to predict my test dataset , i got nothing on the result pics , no masks and no bboxes . Even though i set the ```conf=0.01``` .   

This is my train command line : 
```yolo task=segment mode=train model=yolov8s-seg.pt data=dirty-seg.yaml epochs=10 imgsz=2048 batch=4 workers=0```

And this is predict command line : 
```yolo task=segment mode=predict model=best.pt conf=0.01 source=dirty_seg_test imgsz=2048```

How can i solve this problem ? Any suggestions will be appreciated .

**Comment by pepijnob** [comment]
Hi, I have the same issue. Also commented in issue #280 , maybe their suggestion works for you (it didn't for me though).

**Comment by arkerman** [comment]
@pepijnob  Hi , thanks for your reply ! I really appreciate it . I will read it and try to train seg again .
