### ISSUE TITLE
Yolv8 custom pose training error

### ISSUE THREAD

**Issue by karunakr** [ultralytics/ultralytics#3170]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, 

I want to train pose model using custom data. However, when i start trianing with limited data sets, i started seeing below error. The error persists, irrespective of if dimension is 2 or 3( visibility). 
usr/local/lib/python3.10/dist-packages/torch/optim/lr_scheduler.py:139: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  2.23it/s]
Exception in thread Thread-67 (plot_images):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/utils/plotting.py", line 388, in plot_images
    kpts_ = kpts[idx].copy()
IndexError: boolean index did not match indexed array along dimension 0; dimension is 60 but corresponding boolean dimension is 218

Data i used for training is https://ultralytics.com/assets/coco8-pose.zip 
I also tried with our own data, but giving same error by mentioning different value for dimension
YAML file content:

```
path: /content/drive/MyDrive/testimgs/cococ
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')


# Keypoints
kpt_shape: [17, 3]  # [number of keypoints, number of dim]
flip_idx: [0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15]

names:
  0: person
```

Training logic

```
from ultralytics import YOLO

model = YOLO('yolov8n-pose.pt')  

model.train(data='/content/drive/MyDrive/testimgs/config.yaml', epochs=1)


Please direct me where exactly am i making mistake?
```

**Comment by karunakr** [comment]
Hi, it's working now after updating with the library. When coming to annotation, we are annotating all 17 key points, and through the custom logic, i am converting JSON data into Yolo format. For this, based on min/max x,y values, i am coming up with bbox center as well width and height values. Could you confirm if the approach i took is correct or not?

Thanks
Karunakar

**Comment by karunakr** [comment]
With small adjustments in x, y values, i can see bbox is working well

**Comment by pderrenger** [comment]
@karunakr hey Karunakar! 👋

Glad to hear that it's working for you now! Regarding your approach for converting JSON data into YOLO format based on min/max x,y values for annotating all 17 key points, it sounds like you're on the right track. The bounding box calculation based on the center as well as the width and height values is a common and valid approach for representing annotated key points in YOLO format.

It's great to know that the adjustments in the x, y values are improving the performance of the bounding box. Keep up the good work, and feel free to reach out if you have any more questions or need further assistance! 😀

**Comment by glenn-jocher** [comment]
@pderrenger That's correct, Karunakar! Your method for converting JSON annotations to YOLO format by using the min/max coordinates to determine the bounding box center, width, and height is a standard approach. It's good to hear that fine-tuning the x, y values is yielding better bounding box accuracy. Keep it up, and don't hesitate to ask if you need more help! 😊
