### ISSUE TITLE
YOLO V8 failed to train using multiple Gpus on windows

### ISSUE THREAD

**Issue by laogonggong847** [ultralytics/ultralytics#3173]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

hello @glenn-jocher:
Thank you and your team for your tremendous contribution to advancing the exchange and advancement of technology. There is no doubt that YOLO V5 has achieved an extremely dazzling achievement. But when I saw YOLO V8, it was a real eye-opener for me. the prospect and potential of YOLO V8 is immeasurable, when I can't wait to use YOLO v8, I have some problems and need to ask you and your team for help.

__My problem is that an error occurred when I was training my model on Windows 10 using two Gpus (RTX 3090).__  I noticed that there are some people who have some of the same problems as me, such as #3122 and #3151, etc.  But I don't think they've made it clear in any of these issues, and therefore don't see a solution. Therefore, I will provide you list of all the details of my problems when using two Gpus, and hope that @glenn-jocher and your team can provide me with ideas or specific solutions to solve them.

The environment in which my computer is running is listed in detail in "Environment". The code used to prepare my own dataset is shown in the figure: However, it must be noted that this dataset was correctly trained by me using YOLO V5, so there is no problem with the dataset itself.

![09be0944e6c5d452d312d2f1527dbf2b](https://github.com/ultralytics/ultralytics/assets/81297486/19cc675f-faef-46fe-981f-1e7a63fce4f3)

For the above code, when I run it directly, it trains correctly and gets the result. Although I did not specify a GPU in the above code, it does run correctly and calls GPU-1 by default (and GPU-0 is not used during training). The use of GPU-1 is shown below (although there is some Chinese information in the figure below, I believe it does not affect your understanding).
![006ed8543bbe5a606ce8823a139e40e5](https://github.com/ultralytics/ultralytics/assets/81297486/5cf5cbfb-af36-4011-bce2-82adcb6f9665)

At this point, without specifying the device, and when the above code is run directly, the training does succeed as shown in the figure. ( There is no doubt that I can control which graphics card is used by ```device=0``` or ```device=1```, and there is no error in choosing either one).
![44749b2a1af076538472cf4f83a1f549](https://github.com/ultralytics/ultralytics/assets/81297486/a6e2bddd-5483-4bfd-b550-9d8f9265dd2f)
```
But I still have two questions about this:
1: There is a warning that I don't understand: user config directory is not writeable, defaulting to '\tmp\Ultralytics'.
2: Why does it show YOLOV8__n__, when I clearly specified YOLOV8__m__ in the code?
```
![b8a9e00a3dc9effb2c5e8da952e8fc1a](https://github.com/ultralytics/ultralytics/assets/81297486/94312878-4244-48d3-b5da-ad84ab0eb0c3)

![66570a4a4c043f23e19355a827aca770](https://github.com/ultralytics/ultralytics/assets/81297486/aab452c3-eccb-4990-8dd7-2dd65b1b2670)

----
However, when I modified the code to use two GPUs for training, I had an unexpected problem. The modified code is as follows, I just added one more line of code:

![53c435ad4f261f12b9d4134d7d620b9f](https://github.com/ultralytics/ultralytics/assets/81297486/0aac3461-0764-4640-ba39-c38274cedb26)

I put the details of running this code in __"Additional"__, please check it, thank you very much. I think the most valid information in this error message is 
```
subprocess.CalledProcessError: Command '['C:\\ProgramData\\anaconda3\\envs\\HCEnv\\python.exe', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '58889', 
```
I found this to be the distributed training related code for pytorch (again my pytorch version is 1.12.1+CU113).
__So I removed the added parameter ```device=[0, 1]```, and executed the following code__
```
 python -m torch.distributed.run --nproc_per_node 2 --master_port 55057 Mytrain.py --device 0,1
```

The specific content of ```Mytrain.py``` is actually the source program that I did not add device to as follows
![09be0944e6c5d452d312d2f1527dbf2b](https://github.com/ultralytics/ultralytics/assets/81297486/21fbc414-9042-4905-af47-48febe62a92a)

----

__It is important to emphasize that I have given two specific logs in "Additional" that I believe will better help you solve the problem. I am using pytorch1.12.1+CUDA11.3 on Win10.__

___Based on all this I will now summarize my 4 questions:___
* 1:  There is a warning that I don't understand: user config directory is not writeable, defaulting to '\tmp\Ultralytics'.
* 2: Why does it show YOLOV8__n__, when I clearly specified YOLOV8__m__ in the code?
* 3: I'm wondering if the problem that occurs with training using two GPUs is caused by the CUDA and pytorch versions, and if so what version should I replace it with.
* 4: If I did not set the correct parameters myself, how should I change them. If I need to change it, I hope you can tell me what to change in which line of the file, otherwise I am worried that I will misunderstand your meaning and change it wrongly.

__Thanks again to you and your team! @glenn-jocher__

### Environment

__-YOLO:__      Ultralytics YOLOv8.0.21
__-Python:__   3.8.16
__-torch:__       1.12.1+cu113
__-GPU:__      Nvidia GeForce RTX 3090（two）
__-OS:__           Win10

### Minimal Reproducible Example

```
from ultralytics import YOLO


if __name__ == "__main__":

    model = YOLO(r'D:\work\ultralytics-main\yolov8m.pt')

    model.train(data=r"D:\work\ultralytics-main\ultralytics\datasets\zhiguan.yaml",
                epochs=1,
                batch=36,
                imgsz=512,
                workers=0)   

```

### Additional

___The complete log information that results from running the code in the following figure directly is as follows___
![53c435ad4f261f12b9d4134d7d620b9f](https://github.com/ultralytics/ultralytics/assets/81297486/fd7d0b7c-d238-4666-9bb1-0144ccf8c356)

```
WARNING ⚠️ user config directory is not writeable, defaulting to '\tmp\Ultralytics'.
Ultralytics YOLOv8.0.116 🚀 Python-3.8.16 torch-1.12.1+cu113 CUDA:0 (NVIDIA GeForce RTX 3090, 24576MiB)
                                                             CUDA:1 (NVIDIA GeForce RTX 3090, 24575MiB)
WARNING ⚠️ Upgrade to torch>=2.0.0 for deterministic training.
yolo\engine\trainer: task=detect, mode=train, model=D:\work\ultralytics-main\yolov8m.pt, data=D:\work\ultralytics-main\ultralytics\datasets\zhiguan.yaml, epochs=1, patience=50, batch=36, imgsz=512, save=True, save_period=-1, cache=False, device=[0, 1], workers=0, project=None, name=None, exist_ok=False, pretrained=False, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs\detect\train76
Overriding model.yaml nc=80 with nc=9

                   from  n    params  module                                       arguments                     
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]                 
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]                
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]             
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]               
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]           
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]              
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]           
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]              
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]           
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]                 
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]                 
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]                 
 22        [15, 18, 21]  1   3780907  ultralytics.nn.modules.head.Detect           [9, [192, 384, 576]]          
Model summary: 295 layers, 25861531 parameters, 25861515 gradients

Transferred 469/475 items from pretrained weights
DDP command: ['C:\\ProgramData\\anaconda3\\envs\\HCEnv\\python.exe', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '58889', 'D:\\tmp\\Ultralytics\\DDP\\_temp_x7e7gzdc2197163767264.py']
NOTE: Redirects are currently not supported in Windows or MacOs.
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [WIN-ENORH68EHIP]:58889 (system error: 10049 - �����������У�������ĵ�ַ��Ч��).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [WIN-ENORH68EHIP]:58889 (system error: 10049 - �����������У�������ĵ�ַ��Ч��).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [WIN-ENORH68EHIP]:58889 (system error: 10049 - �����������У�������ĵ�ַ��Ч��).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [WIN-ENORH68EHIP]:58889 (system error: 10049 - �����������У�������ĵ�ַ��Ч��).
WARNING  Upgrade to torch>=2.0.0 for deterministic training.
DDP info: RANK 0, WORLD_SIZE 2, DEVICE cuda:0
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [WIN-ENORH68EHIP]:58889 (system error: 10049 - �����������У�������ĵ�ַ��Ч��).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [WIN-ENORH68EHIP]:58889 (system error: 10049 - �����������У�������ĵ�ַ��Ч��).
Overriding model.yaml nc=80 with nc=9
Transferred 469/475 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Traceback (most recent call last):
  File "D:\tmp\Ultralytics\DDP\_temp_x7e7gzdc2197163767264.py", line 9, in <module>
    trainer.train()
  File "D:\work\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 192, in train
    self._do_train(world_size)
  File "D:\work\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 275, in _do_train
    self._setup_train(world_size)
  File "D:\work\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 221, in _setup_train
    dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\site-packages\torch\distributed\distributed_c10d.py", line 1201, in broadcast
    work.wait()
RuntimeError: Invalid scalar type
AMP: checks passed 
Traceback (most recent call last):
  File "D:\tmp\Ultralytics\DDP\_temp_x7e7gzdc2197163767264.py", line 9, in <module>
    trainer.train()
  File "D:\work\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 192, in train
    self._do_train(world_size)
  File "D:\work\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 275, in _do_train
    self._setup_train(world_size)
  File "D:\work\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 221, in _setup_train
    dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\site-packages\torch\distributed\distributed_c10d.py", line 1201, in broadcast
    work.wait()
RuntimeError: Invalid scalar type
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 17572) of binary: C:\ProgramData\anaconda3\envs\HCEnv\python.exe
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\site-packages\torch\distributed\run.py", line 765, in <module>
    main()
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\site-packages\torch\distributed\run.py", line 761, in main
    run(args)
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\site-packages\torch\distributed\run.py", line 752, in run
    elastic_launch(
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\site-packages\torch\distributed\launcher\api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\site-packages\torch\distributed\launcher\api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
D:\tmp\Ultralytics\DDP\_temp_x7e7gzdc2197163767264.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-06-14_17:09:33
  host      : WIN-ENORH68EHIP.lan
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3924)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-14_17:09:33
  host      : WIN-ENORH68EHIP.lan
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 17572)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "D:\work\ultralytics-main\Mytrain.py", line 8, in <module>
    model.train(data=r"D:\work\ultralytics-main\ultralytics\datasets\zhiguan.yaml",
  File "D:\work\ultralytics-main\ultralytics\yolo\engine\model.py", line 371, in train
    self.trainer.train()
  File "D:\work\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 188, in train
    raise e
  File "D:\work\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 186, in train
    subprocess.run(cmd, check=True)
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\ProgramData\\anaconda3\\envs\\HCEnv\\python.exe', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '58889', 'D:\\tmp\\Ultralytics\\DDP\\_temp_x7e7gzdc2197163767264.py']' returned non-zero exit status 1.


```

----
----
----
The specific log when I run the command ```"python -m torch.distributed.run --nproc_per_node 2 --master_port 55057 Mytrain.py --device 0,1"```

```
(HCEnv) PS D:\work\ultralytics-main> python -m torch.distributed.run --nproc_per_node 2 --master_port 55057 Mytrain.py --device 0,1
NOTE: Redirects are currently not supported in Windows or MacOs.
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [WIN-ENORH68EHIP]:55057 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [WIN-ENORH68EHIP]:55057 (system error: 10049 - 在其上下文中，该请求的地址无效。).
WARNING ⚠️ user config directory is not writeable, defaulting to '\tmp\Ultralytics'.
WARNING ⚠️ Upgrade to torch>=2.0.0 for deterministic training.
Overriding model.yaml nc=80 with nc=9
Transferred 469/475 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Traceback (most recent call last):
  File "Mytrain.py", line 8, in <module>
    model.train(data=r"D:\work\ultralytics-main\ultralytics\datasets\zhiguan.yaml",
  File "D:\work\ultralytics-main\ultralytics\yolo\engine\model.py", line 371, in train
    self.trainer.train()
  File "D:\work\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 192, in train
    self._do_train(world_size)
  File "D:\work\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 275, in _do_train
    self._setup_train(world_size)
  File "D:\work\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 221, in _setup_train
    dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\site-packages\torch\distributed\distributed_c10d.py", line 1192, in broadcast
    default_pg = _get_default_group()
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\site-packages\torch\distributed\distributed_c10d.py", line 429, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
AMP: checks passed ✅
Traceback (most recent call last):
  File "Mytrain.py", line 8, in <module>
    model.train(data=r"D:\work\ultralytics-main\ultralytics\datasets\zhiguan.yaml",
  File "D:\work\ultralytics-main\ultralytics\yolo\engine\model.py", line 371, in train
    self.trainer.train()
  File "D:\work\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 192, in train
    self._do_train(world_size)
  File "D:\work\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 275, in _do_train
    self._setup_train(world_size)
  File "D:\work\ultralytics-main\ultralytics\yolo\engine\trainer.py", line 221, in _setup_train
    dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\site-packages\torch\distributed\distributed_c10d.py", line 1192, in broadcast
    default_pg = _get_default_group()
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\site-packages\torch\distributed\distributed_c10d.py", line 429, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 13788) of binary: C:\ProgramData\anaconda3\envs\HCEnv\python.exe
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\site-packages\torch\distributed\run.py", line 765, in <module>
    main()
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\site-packages\torch\distributed\run.py", line 761, in main
    run(args)
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\site-packages\torch\distributed\run.py", line 752, in run
    elastic_launch(
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\site-packages\torch\distributed\launcher\api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\ProgramData\anaconda3\envs\HCEnv\lib\site-packages\torch\distributed\launcher\api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
Mytrain.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-06-14_17:34:26
  host      : WIN-ENORH68EHIP.lan
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 12672)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-14_17:34:26
  host      : WIN-ENORH68EHIP.lan
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 13788)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@laogonggong847 if the default USER_CONFIG_DIR is not writeable then it will fall back to a tmp directory as in your case, but there is no problem here. 

YOLOv8n is used to verify correct operation of AMP irrespective of what model you are training.

I'm sorry but I don't have a windows machine myself to debug with, but if you come up with a solution please submit a PR.

In the meantime I'd highly recommend training all DDP models in our Docker image for maximum compatibility:

## Environments

YOLOv8 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/GCP-Quickstart)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/AWS-Quickstart)
- **Docker Image**. See [Docker Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

**Comment by glenn-jocher** [comment]
@laogonggong847 update on the tmp directory creation, I think we had a bug regarding determining user OS, which is now fixed in https://github.com/ultralytics/ultralytics/pull/3196. This may resolve at least one issue in this PR. Can you please update and try again?

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by glenn-jocher** [comment]
Great news 😃! Your original issue may now be resolved ✅ in PR #3197. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by 151707745** [comment]
Hello, I've encountered the same problem as you. How did you solve it?

**Comment by glenn-jocher** [comment]
@151707745 hello! If you're encountering the same issue, consider pulling the latest updates from the YOLOv8 GitHub repository, as we've implemented several fixes recently. If it's a particular error message that you're seeing, I would recommend searching for that specific error in the issues to see if it's been previously solved.

If you're still having trouble, please open a new issue. Be sure to include as much information as possible, including the error messages you're seeing, any relevant screenshots, and what steps you're taking when the problem occurs. This will help us give you the most accurate help possible. Thank you for your contribution to YOLOv8!
