### ISSUE TITLE
best.pth is not best model?

### ISSUE THREAD

**Issue by Darknesszlx** [ultralytics/ultralytics#3175]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/ultralytics/ultralytics/assets/7909474/fb4f8e8a-9210-4e23-a2db-2eb156fde6e0)

After training finshed, Validating best.pth summary did not show best_fitness, as you can see in epoch 99 which gives better mAP50 and mAP50-95.

**Comment by glenn-jocher** [comment]
@Darknesszlx best.pt is saved on every highest-mAP epoch, and then an independent validation is performed on best.pt after training is complete. There may be slight differences but everything is working correctly.

**Comment by Darknesszlx** [comment]
> 

Can you point out what's the differences?
