### ISSUE TITLE
How to change the loss function in yolov8?

### ISSUE THREAD

**Issue by remeberWei** [ultralytics/ultralytics#3177]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, brother. I recently used yolov8 to train my model, but I don't know how to modify the Loss function, such as how to modify it to GIOU, SIOU, etc. Can you help me? Thank you.

**Comment by glenn-jocher** [comment]
@remeberWei all loss functions are inside utils/loss.py here:
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/utils/loss.py

**Comment by remeberWei** [comment]
> @remeberWei all loss functions are inside utils/loss.py here: https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/utils/loss.py

oh，thanks you，gleen

**Comment by glenn-jocher** [comment]
Hello @remeberWei, thank you for reaching out! To modify the loss function in YOLOv8, you can locate the `utils/loss.py` file in this repository. Inside that file, you will find the implementation of different loss functions such as GIOU and SIOU.

You can modify the code in that file to replace the existing loss function with the one you desire. Make sure to understand the specific details of your chosen loss function and how it should be computed.

If you need any further assistance or have more questions, feel free to ask. We are here to help!

Best regards,
Glenn

**Comment by remeberWei** [comment]
I think I see what you mean，When I want to use GIOU, do I change CIOU=true to GIOU=true in the following links?        iou = bbox_iou(pred_bboxes[fg_mask], target_bboxes[fg_mask], xywh=False, CIoU=True)

**Comment by glenn-jocher** [comment]
@remeberWei hi there! To use the GIOU loss function in YOLOv8, you don't need to change the `CIOU=True` parameter to `GIOU=True` directly. Instead, you need to make a few modifications to the code.

In the mentioned line of code, `iou = bbox_iou(pred_bboxes[fg_mask], target_bboxes[fg_mask], xywh=False, CIoU=True)`, the `CIoU=True` parameter indicates the usage of the complete IoU loss, which includes GIoU and other components.

If you want to use GIOU specifically, you can replace the `bbox_iou` function with the `bbox_iou_giou` function, which is also available in the `loss.py` file. 

Please note that if you modify the loss function, you might need to make additional changes to ensure compatibility with the rest of the codebase and the network architecture.

Let me know if you have any further questions or need more clarification. I'm here to assist you!

Best regards,
Glenn

**Comment by pderrenger** [comment]
@remeberWei You're on the right track! When modifying the YOLOv8 loss function, it generally involves directly replacing the code for the specific loss function you want to use in the appropriate places.

As for the `seed=0` in the `default.yaml` file, this line sets the random seed used for reproducibility during training. When the seed is set to a specific value, such as 0, it means that a fixed random seed number is used. This can help in ensuring reproducibility of training runs, as using the same seed value will produce the same random numbers each time the code is run.

To check the specific random seed number, you can simply look in the `default.yaml` file at the specified line, where you will find the value assigned to the `seed` parameter, in this case, 0.

If you need any more help or have further questions, feel free to ask. I'm here to assist you!

**Comment by mickan30** [comment]
hello @pderrenger @glenn-jocher, can you please more elaborate on how to implement this? 
What I did were:

1. Clone the repository
2.  Modify the ultralytics\ultralytics\utils\loss.py
3. Then use the package
`from ultralytics.ultralytics.models.yolo.detect import DetectionTrainer

args = dict(model='yolov8n.pt', data='coco8.yaml', epochs=3)
trainer = DetectionTrainer(overrides=args)
trainer.train()`


But this throws error
.yolo.detect import DetectionTrainer
  File "c:\My Projects\AIProjects\YOLO\YOLOv8\ultralytics\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.data.explorer.explorer import Explorer
ModuleNotFoundError: No module named 'ultralytics.data'

Can you please help me with this.

**Comment by glenn-jocher** [comment]
Hello @mickan30, it seems like there might be an issue with your local setup or the way the repository is being used. Please ensure that you have installed all the required dependencies and that your Python environment is set up correctly.

If you've cloned the repository and made changes to `loss.py`, you should also make sure that you're working within the repository's root directory when trying to import and use the package. The error message suggests that there might be a problem with the Python path or missing modules.

Double-check your installation and the structure of the cloned repository. If the issue persists, consider opening an issue on the GitHub repository with detailed information about the steps you've taken and the full error message, so we can assist you more effectively.

**Comment by XiFromEY** [comment]
hi the github link is not working :(

**Comment by glenn-jocher** [comment]
@XiFromEY hi there! Sorry to hear you're having trouble with the link. 😕 Could you please provide more details or specify which link you're referring to? I'll be happy to help you out! Meanwhile, you can visit the [Ultralytics YOLOv8 main page](https://github.com/ultralytics/ultralytics) to see if you find what you're looking for. 🚀

**Comment by kanis777** [comment]
hi @glenn-jocher @pderrenger how do i use 
inner-mpdiou instead of ciou in yolov8 ? is there any functions of the implementation of mpdiou....where all should i update

**Comment by glenn-jocher** [comment]
Hello @kanis777! To switch from CIoU to MPD-IoU in YOLOv8, you'll need to modify the loss computation in the `loss.py` file. Currently, YOLOv8 does not include a predefined function for MPD-IoU, so you would need to implement this function based on its definition from the relevant research papers or sources.

Once you have your MPD-IoU function, replace the CIoU calls in `loss.py` with calls to your new function. Make sure to test the changes thoroughly to ensure that the new loss function integrates well with the rest of the model's training process.

If you're new to modifying loss functions, it might be helpful to start with smaller experiments or seek further guidance from the community or literature on implementing custom loss functions in neural networks. Good luck, and happy coding! 🚀

**Comment by kanis777** [comment]
@glenn-jocher . It would be helpful if you could be like more specific on where I should make the change. Bcz ciou is present in the form of ciou=true or false in utile/metrics.py and loss.py there are no functions . so where should I add and call and use the function ??

**Comment by glenn-jocher** [comment]
Hello @kanis777! To implement MPD-IoU in place of CIoU in YOLOv8, you'll need to focus on modifying the loss computation where CIoU is utilized. Here’s a brief guide:

1. **Create the MPD-IoU Function**: You'll need to write a new function for MPD-IoU. This function should compute the metric based on your specific requirements for bounding box regression.

2. **Integrate Your Function**: Once your function is ready, integrate it into the model's loss computation. Typically, this would be in `loss.py`, but since you mentioned it's not clear, you might need to look for where the CIoU loss is calculated within the model training loop or loss computation sections. It might not be explicitly named if it's toggled via a parameter.

3. **Replace CIoU Calls**: Replace any CIoU-related logic with calls to your new MPD-IoU function. Ensure that any references to CIoU in the configuration files or flags are appropriately adjusted to accommodate your new function.

4. **Test Changes**: Thoroughly test the new setup to ensure that the integration works as expected without introducing errors in the training process.

If you're still unsure, consider looking deeper into the model's documentation or the specific files where bounding box calculations are handled. This might give you a clearer idea of where to implement your changes. Good luck! 🚀

**Comment by glenn-jocher** [comment]
Hello @kanis777! Great to hear that you've implemented the changes. To test your new MPD-IoU function, you can follow these steps:

1. **Unit Testing**: Start by writing unit tests for your MPD-IoU function to ensure it calculates the metric correctly under various conditions.

2. **Integration Testing**: Incorporate the function into your model and run a smaller subset of your dataset to quickly verify that the model trains without errors and the loss decreases as expected.

3. **Full Training Run**: Once you're confident in the smaller tests, conduct a full training run to observe the overall impact on model performance and metrics.

4. **Evaluation**: Compare the performance, such as precision and recall, against the baseline model using the original CIoU to see if there are improvements or other effects.

Testing thoroughly will help ensure that your implementation not only works correctly but also enhances model performance. Good luck! 🚀

**Comment by kanis777** [comment]
Hi once again @glenn-jocher .So , we get 2 models best.pt and last.pt . wt is the difference btw both of them . can i know like y is that considered best - like maybe it stopped in some x epochs making it better than last.pt .Can you elaborate on that ?

**Comment by glenn-jocher** [comment]
Hello @kanis777,

Great question! The `best.pt` and `last.pt` models serve different purposes during the training process:

- **`best.pt`**: This model is saved when the validation performance is at its peak, typically based on metrics like mAP (mean Average Precision). It represents the model state that performed best on the validation set during training.

- **`last.pt`**: This model is saved at the end of the training process, regardless of its performance. It represents the final state of the model after all training epochs have completed.

The `best.pt` model is often considered more reliable for deployment as it has demonstrated the best performance on the validation set. The `last.pt` model might be useful for further fine-tuning or analysis.

If you have any more questions or need further clarification, feel free to ask! 😊

**Comment by kanis777** [comment]
Thanks @glenn-jocher for replying back . I want to know the epoch of the best.pt and last.pt ...so that i can become aware which epoch has peak performance. So can u tell me how can i check the epoch of the best and last ?

**Comment by glenn-jocher** [comment]
Hello @kanis777,

You're welcome! To determine the epoch at which `best.pt` and `last.pt` were saved, you can check the training logs generated during the training process. These logs typically contain detailed information about each epoch, including performance metrics.

Here’s a quick way to find the epoch information:

1. **Training Logs**: Review the training logs in the `runs` directory. The logs will indicate the epoch at which the `best.pt` model was saved based on the highest validation performance.

2. **Model Metadata**: If you saved the model with metadata, you can load the model and inspect its attributes. Here’s an example in Python:

    ```python
    import torch

    # Load the best model
    best_model = torch.load('path/to/best.pt')
    best_epoch = best_model['epoch'] if 'epoch' in best_model else 'Unknown'

    # Load the last model
    last_model = torch.load('path/to/last.pt')
    last_epoch = last_model['epoch'] if 'epoch' in last_model else 'Unknown'

    print(f"Best model saved at epoch: {best_epoch}")
    print(f"Last model saved at epoch: {last_epoch}")
    ```

This code snippet will help you identify the epochs at which the `best.pt` and `last.pt` models were saved. If you encounter any issues or need further assistance, feel free to ask! 😊

**Comment by tehseen123iqbal** [comment]
asslamoalikum:
i used yolov8n-obb model i want to used custom loss funtion which is rotate-iou and focel but when we train a model the model train  and  show  bydefault loss funtion .please tell me where is problem,

**Comment by glenn-jocher** [comment]
@tehseen123iqbal to use custom loss functions like Rotated-IoU and Focal Loss with YOLOv8n-obb, you'll need to modify the loss computation in the model's loss function. You can extend the `RotatedDetectionLoss` class in ultralytics/models/yolo/detect/loss.py and override the loss calculation methods to implement your desired loss functions. Let me know if you need help with the specific implementation.

**Comment by avishek-018** [comment]
hi, i made the following change in the ultralytics/models/yolo/detect/train.py line 95. I added "fl_loss"(assuming its focal loss) and removed "dfl_loss"
```
def get_validator(self):
        """Returns a DetectionValidator for YOLO model validation."""
        self.loss_names = "box_loss", "cls_loss", "fl_loss" # "dfl_loss"
        return yolo.detect.DetectionValidator(
            self.test_loader, save_dir=self.save_dir, args=copy(self.args), _callbacks=self.callbacks
        )
```

1) is it a correct way to use focal loss ? 
2) if YES, where do I get the names of the functions? (i.e., fl_loss for focal loss)

 I wanted to use the already made loss functions on loss.py rather than the typical 
 "box_loss", "cls_loss", "dfl_loss"

**Comment by glenn-jocher** [comment]
To use focal loss in your YOLO model, you'll need to ensure that `fl_loss` is correctly implemented in the loss computation logic. The mere addition of "fl_loss" in the `get_validator` method won't suffice unless the corresponding function is defined and integrated into the model's loss calculation process, typically found in `loss.py`. You should verify that `fl_loss` is implemented in the loss function file and that it replaces or complements the existing loss components. If `fl_loss` is not predefined, you'll need to implement it yourself based on the focal loss formula.

**Comment by Pidongg** [comment]
Hi @glenn-jocher ! I am trying to change the bce loss to use the ce loss instead, which make sense for my usecase since the boxes can only be single labled. However, the MAP after the change is really bad (~0.002, but 0.6 with bce loss), with the model predominantly predicting 1 class (minority class, with index 0). 

I was wondering if you could help me with detecting what went wrong?

I have only modified 3 places, in the loss.py file:
[1] __init__:
# original: self.bce = nn.BCEWithLogitsLoss(reduction="none")
self.ce = nn.CrossEntropyLoss(weight=class_weights.half().to(self.device),reduction="sum")

[2] __call__:
_, target_bboxes, target_scores, fg_mask, _ = self.assigner(
            # original: pred_scores.detach().sigmoid(),
            F.softmax(pred_scores.detach(), dim=-1),  # Mutually exclusive probabilities
            (pred_bboxes.detach() * stride_tensor).type(gt_bboxes.dtype),
            anchor_points * stride_tensor,
            gt_labels,
            gt_bboxes,
            mask_gt,
 )

[3] __call__:
# original: loss[1] = self.bce(pred_scores, target_scores.to(dtype)).sum() / target_scores_sum  # BCE
pred_scores_reshaped = pred_scores.view(-1, self.nc)
target_classes = target_scores.view(-1, self.nc).argmax(dim=1)
loss[1] = self.ce(pred_scores_reshaped, target_classes)/target_scores_sum

**Comment by glenn-jocher** [comment]
It seems like the main issue lies in the way you are handling `target_scores` and `pred_scores` during the loss computation. Specifically:

1. `CrossEntropyLoss` expects `target_classes` to be a single integer class index per sample, but you're deriving it from `target_scores`. If `target_scores` is sparse or imbalanced, it can lead to incorrect targets for `ce`.

2. Using `F.softmax` for `pred_scores` might not align well with how `target_scores` are assigned and scaled. Note that YOLO models naturally use sigmoid for multi-label outputs, and modifying this can misalign the loss function expectations.

To debug:
- Ensure `target_classes` is correctly derived from `target_scores` and represents valid class indices for your dataset.
- Verify that the weights used in `CrossEntropyLoss` (`class_weights`) are correctly computed and balanced for your dataset's class distribution.
- Check the assignment logic in `self.assigner` to ensure that it pairs predictions and targets appropriately after switching to `F.softmax`.

It might also help to monitor intermediate outputs (e.g., `pred_scores`, `target_classes`) to detect anomalies. Fine-tuning the loss weighting or re-evaluating the suitability of `CrossEntropyLoss` for your use case might also be necessary.

**Comment by Shivom23** [comment]
Hi @glenn-jocher I wanted to ask what should i do if i wanted to use contrastive loss in the yolov8 model. where should i edit the code ?

**Comment by glenn-jocher** [comment]
@Shivom23 hi, you'll need to implement your contrastive loss function and then integrate it into the loss computation—most likely by modifying or extending the classification loss module in ultralytics/utils/loss.py so it’s used during the model’s forward pass.

**Comment by Shivom23** [comment]
Thank you so much i ll try implementing it.....i ll trouble you further if
i face some difficulties....
Thank you,
Regards.

**Comment by glenn-jocher** [comment]
@Shivom23 you're welcome! We're glad to help. For future implementation questions, please share specific details about your contrastive loss approach and which model components you're modifying. The YOLO community and Ultralytics team will be happy to assist with technical questions about the existing loss framework in [loss.py](https://docs.ultralytics.com/reference/utils/loss/). Good luck with your experiments! 🚀

**Comment by Shivom23** [comment]
i am trying to modify the yolov8 model for the task of object detection.
Can you help me with which loss function i should modify in the loss.py so
it actually works well with the rest of the code without giving any error.
actually i am getting a lot of false positives so to reduce them i wanted
to add contrastive loss into the model can you help me with that?

**Comment by glenn-jocher** [comment]
Hi @Shivom23! For reducing false positives with contrastive loss in YOLOv8 detection, focus on modifying the classification loss component in the `v8DetectionLoss` class in `loss.py`. You'll need to integrate your contrastive loss logic alongside the existing `self.bce` loss while maintaining compatibility with the target assignment from `self.assigner`. The [loss.py reference](https://docs.ultralytics.com/reference/utils/loss/) shows where different loss components are initialized and applied. Ensure your new loss receives valid positive/negative pairs from the detection outputs to work effectively.
