### ISSUE TITLE
Yolov8 not working with ultralytics library on PC 

### ISSUE THREAD

**Issue by kyoko9000** [ultralytics/ultralytics#318]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When i used pip install ultralytics to install and use file.py to run results = model(..) or model.predict(...) It is not working on my PC. but it work well with code in terminal look like: yolo task=detect mode=predict model=yolov8n.pt source="https://ultralytics.com/images/bus.jpg". I have to download manual yolov8 on github and put it on my project. And it can work normal. 

### Environment

I use yolov8n.pt, python 3.9.13, pycharm

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@kyoko9000 hey can you try it again with the latest version 8.0.5? thanks!

**Comment by kyoko9000** [comment]
Thank you i will try it tonight. But that is version of yolov8 ?

**Comment by Laughing-q** [comment]
@kyoko9000 oh just `pip install --upgrade ultralytics` should work.

**Comment by kyoko9000** [comment]
Thank you!
