### ISSUE TITLE
Export Yolo v8n ONNX model without grid / concate

### ISSUE THREAD

**Issue by AatishLanghee** [ultralytics/ultralytics#3187]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to know how can I export the yolo v8n onnx model into the below format :

images
name: images
type: float32[1,3,640,640]

output0
name: output0
type: float32[1,80,80,144]
342
name: 342
type: float32[1,40,40,144]
358
name: 358
type: float32[1,20,20,144]

Currently the output shape is coming like this:

images
name: images
type: float32[1,3,640,640]

output0
name: output0
type: float32[1,84,8400]

**Comment by Kayzwer** [comment]
@AatishLanghee I think you need to modify the code in `ultralytics/nn/modules/head.py`.

**Comment by AatishLanghee** [comment]
@Kayzwer could you please help me with the modifications?
