### ISSUE TITLE
YOLOv8/OpenVINO input format

### ISSUE THREAD

**Issue by koush** [ultralytics/ultralytics#3188]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When trying to infer on a image using yolov8n converted to OpenVINO:

```python
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')  # load an official model

# Export the model
model.export(format='openvino')
```

Loading an image of shape (640,640,3) and running inference results in the following error

> Can't set input blob with name: images, because model input (shape=[1,3,640,640]) and blob (shape=(1.640.640.3)) are incompatible.

Typically the shape is w,h,d, but this seems to be expecting d,w,h? Is that RGB planar? I tried RGB planar but that did not yield any results.

What does (3,640,640) format mean for Yolov8 OpenVINO input?

Furthermore, I did not encounter this problem when testing CoreML.

**Comment by Kayzwer** [comment]
you need to permute your input before pass into the model

**Comment by koush** [comment]
> you need to permute your input before pass into the model

Could you elaborate?

**Comment by koush** [comment]
my solution:

```python
                im = np.stack([input])
                im = im.transpose((0, 3, 1, 2))  # BHWC to BCHW, (n, 3, h, w)
                im = im.astype(np.float32) / 255.0
                im = np.ascontiguousarray(im)  # contiguous
                im = ov.Tensor(array=im, shared_memory=True)
```

**Comment by pderrenger** [comment]
@koush the input format expected by YOLOv8 for OpenVINO is in the format (3, H, W), where 3 denotes the three color channels (RGB) and H, W represent the height and width of the image, respectively. To achieve this format, the input needs to be permuted before passing it into the model.

One way to achieve this is by using NumPy to stack the input into a new array, then transposing the dimensions to convert from BHWC to BCHW format, and finally normalizing the pixel values to the range [0, 1]. This can be followed by creating a contiguous array for efficient memory access. Lastly, you can wrap the data in an OpenVINO tensor for compatibility with the model.

This approach helps to align the input data with the expected format for YOLOv8 using OpenVINO.
