### ISSUE TITLE
YOLO models unable to update project & name parameters without reloading

### ISSUE THREAD

**Issue by nikhil-anand-95** [ultralytics/ultralytics#3189]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I have finetuned the YOLOv8 model on my dataset. I am loading the model in memory & running inference for multiple inputs. However, irrespective of the project & name parameters, the model is reusing the initial parameters and replacing the old output. How can I run inference with updated output directory without reloading the model.

<img width="1180" alt="Screenshot 2023-06-15 at 1 44 50 PM" src="https://github.com/ultralytics/ultralytics/assets/97036434/db5d6248-6ab2-4f8c-aea4-1424d2b7a7d4">

The above code generates output in specified folder & directory. However if I update the predict call with new locations, it replaces the existing output.

<img width="1181" alt="Screenshot 2023-06-15 at 1 45 06 PM" src="https://github.com/ultralytics/ultralytics/assets/97036434/21c16842-89f5-4c28-b6ea-3a6c779844f7">

The above code will save output in test_image1 project & directory instead of storing in new test_image2 locations. I can only resolve this by reloading the model by running `model = YOLO('weights/yolov8l_custom_v0.pt') ` but this is an inefficient way. 

How can I resolve this issue in an efficient manner. Thanks in advance.

### Environment

- YOLO: Ultralytics YOLOv8l finetuned on custom dataset
- OS: MacOS, Amazon EC2
- Python: 3.8

### Minimal Reproducible Example

`!pip install -q ultralytics
from ultralytics import YOLO

model = YOLO('weights/yolov8l_custom_v0.pt') 
results = model.predict(
    source='test_image1.jpg', 
    save=True,
    save_txt=True,
    save_conf=True,
    save_crop=True,
    project='test_image1',
    name='test_image1') 

results = model.predict(
    source='test_image2.jpg', 
    save=True,
    save_txt=True,
    save_conf=True,
    save_crop=True,
    project='test_image2',
    name='test_image2') 
`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@nikhil-anand-95 thanks for the bug report. I'm able to reproduce. Adding TODO tag to queue for a fix.


```
from ultralytics import YOLO

model = YOLO()
results = model.predict(
source='ultralytics/assets/bus.jpg',
save=True,
save_txt=True,
save_conf=True,
save_crop=True,
project='test_image1',
name='test_image1')

results = model.predict(
source='ultralytics/assets/bus.jpg',
save=True,
save_txt=True,
save_conf=True,
save_crop=True,
project='test_image2',
name='test_image2')

image 1/1 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus.jpg: 640x480 4 persons, 1 bus, 1 stop sign, 69.3ms
Speed: 3.2ms preprocess, 69.3ms inference, 9.1ms postprocess per image at shape (1, 3, 640, 640)
Results saved to test_image1/test_image1
1 label saved to test_image1/test_image1/labels

image 1/1 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus.jpg: 640x480 4 persons, 1 bus, 1 stop sign, 44.7ms
Speed: 1.4ms preprocess, 44.7ms inference, 0.4ms postprocess per image at shape (1, 3, 640, 640)
Results saved to test_image1/test_image1
1 label saved to test_image1/test_image1/labels
```

**Comment by glenn-jocher** [comment]
@nikhil-anand-95 Great news 😃! Your original issue may now be resolved ✅ in PR #3215. This will be part of 8.0.119 tomorrow.

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by nikhil-anand-95** [comment]
@glenn-jocher This is resolved in the said build. Thanks for the quick fix.

**Comment by glenn-jocher** [comment]
@nikhil-anand-95 great, thanks for the confirmation!
