### ISSUE TITLE
Support for Coreml Model Export

### ISSUE THREAD

**Issue by ryuFruit** [ultralytics/ultralytics#319]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi I wonder when will the support for exporting coreml model be available? and perhaps also inference pipeline using coreml model. Is there any timeline can be shared? thanks a lot.

**Comment by kmashal** [comment]
any answer, I can convert using export but it does not work so I am assuming the conversion is not correct

**Comment by pderrenger** [comment]
@kmashal hello! 🌟 You can currently export the YOLOv8 model using the export mode, but if you're experiencing issues with the CoreML conversion, it's possible that there may be a problem with the export format. Could you provide more details about the specific issues you're encountering with the CoreML conversion? This will help in identifying and resolving the problem. Thank you!
