### ISSUE TITLE
Are the YOLOv6 pretrained weights available for training?

### ISSUE THREAD

**Issue by syntherick** [ultralytics/ultralytics#3195]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I was looking through the yolov6 docs inside ultralytics and it has following pretrained weights table
![Screenshot from 2023-06-15 18-29-07](https://github.com/ultralytics/ultralytics/assets/59579709/7a2c1aea-2540-45ce-940b-c74e176ece87)

but when I do:
model = YOLO("yolov6-l6.pt")

I get error that "yolov6-l6.pt" not found
any idea about this?
I am using the latest ultralytics version.

**Comment by Kayzwer** [comment]
@syntherick https://github.com/meituan/YOLOv6#Benchmark try this

**Comment by syntherick** [comment]
@Kayzwer if I use pretrained model from Yolov6 repo. I get following error:

> WARNING ⚠️ ./yolov6l6.pt appears to require 'yolov6.models', which is not in ultralytics requirements.
AutoInstall will run now for 'yolov6.models' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
requirements: Ultralytics requirement "yolov6.models" not found, attempting AutoUpdate...
ERROR: Could not find a version that satisfies the requirement yolov6.models (from versions: none)
ERROR: No matching distribution found for yolov6.models
requirements: ❌ Command 'pip install --no-cache "yolov6.models"  ' returned non-zero exit status 1.

**Comment by Kayzwer** [comment]
@syntherick my bad I dont have solution

**Comment by syntherick** [comment]
@glenn-jocher any idea about this issue?

**Comment by Rusab** [comment]
@glenn-jocher I have tried this too, the pre-trained weights in the docs don't work, it is only possible to train from scratch.

**Comment by glenn-jocher** [comment]
@Rusab thank you for bringing this issue to our attention. I apologize for any confusion caused. 

At the moment, pretrained weights specifically for YOLOv6 are not available in the Ultralytics YOLOv8 repo. The pretrained weights mentioned in the YOLOv6 repo you mentioned are not compatible with the Ultralytics YOLOv8 implementation.

However, you can still train a YOLOv8 model from scratch using the Ultralytics YOLOv8 repo. We provide the necessary tools and documentation to train a YOLOv8 model on your custom dataset. Instructions on how to train a YOLOv8 model can be found in the YOLOv8 documentation.

If you have any further questions or need assistance with training a YOLOv8 model, please don't hesitate to ask. We are here to help!

**Comment by glenn-jocher** [comment]
You're welcome, @Rusab! I'm glad I could help clarify things for you. If you have any further questions or run into any other issues regarding YOLOv8, don't hesitate to reach out. We're here to assist. Happy coding!
