### ISSUE TITLE
How can i take frame for my project

### ISSUE THREAD

**Issue by kyoko9000** [ultralytics/ultralytics#320]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to take frame of video, webcam, pic because results = model(...) Give me only data. I need frame too show on my GUI.

**Comment by Laughing-q** [comment]
@kyoko9000 hi you can easily show plotted frames by set `show=True`.

**Comment by kyoko9000** [comment]
that's just show frame inside yolo. i need to take out frame at results = model(..) because if i want to show it on my gui like pyqt5 i can't.

**Comment by AyushExel** [comment]
@kyoko9000 We're working on improving this and will be available in the coming days very soon. Currently, you can get results using:
```
result = model(..., return_outputs=True)
```
