### ISSUE TITLE
Which papers/article does the YoloV8 instance segmentation function refer to?

### ISSUE THREAD

**Issue by HXB-1997** [ultralytics/ultralytics#3201]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question
Which papers/article does the YoloV8 instance segmentation function refer to? 

mask-RCNN ? PANet? YOLACT ?or anything else?

I am fresh for learning the instance segment, I wanna know how YOLOV8 made it. 

Thanks a lot.!!!!!!!!!!!!!!!

### Additional

:->

**Comment by glenn-jocher** [comment]
@HXB-1997 the YOLOv8-Pose implemenation is a mix of prior work like YOLO-ACT and the existing YOLOv8 detection updates, which are themselves a mix of in-house R&D and improvements from YOLOX, YOLOv5 and YOLOv6.

**Comment by HXB-1997** [comment]
Sorry for not replying in time due to jet lag. I probably got it, I'll check the relevant information. Thank you from the bottom of my heart

**Comment by pderrenger** [comment]
@HXB-1997 no worries at all! If you have any more questions as you explore the relevant information, feel free to ask. Happy to help!
