### ISSUE TITLE
Why the inference time is not same to the origin log

### ISSUE THREAD

**Issue by universea** [ultralytics/ultralytics#322]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The log is : image 1/1 C:\Users\MBL\Documents\Pengsong\bus.jpg: 640x480 4 persons, 1 bus, 1 stop sign, 33.0ms
Speed: 0.9ms pre-process, 33.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

However, I use the time.time() to calculation the speed, the time cost is more than 200ms.

<img width="596" alt="1673577672513" src="https://user-images.githubusercontent.com/13444641/212224904-47531239-4465-41ea-bef9-bd75584019b6.png">

**Comment by Wanghe1997** [comment]
因为你是将 time.time()放在循环内了吧？所以每一个循环的时间都累加统计了

**Comment by universea** [comment]
> 因为你是将 time.time()放在循环内了吧？所以每一个循环的时间都累加统计了

我放外面也是这样，可能是加载图片时间算进去了，但是他这个predict好像不支持输入numpy数组

**Comment by Wanghe1997** [comment]
> > 因为你是将 time.time()放在循环内了吧？所以每一个循环的时间都累加统计了
> 
> 我放外面也是这样，可能是加载图片时间算进去了，但是他这个predict好像不支持输入numpy数组

那不清楚了。想问下学长，您图片中detect阶段测速的控制台指令是什么？我现在还在训练，还没到您这步，想提前了解下测速指令

**Comment by Wanghe1997** [comment]
还有为什么这里没有像YOLOv5一样，显示NMS的用时呢？

**Comment by Laughing-q** [comment]
@universea @Wanghe1997 是的你计算了所有的时间，包括读取图片，前处理推理后处理，绘制的时间。
@Wanghe1997 log中的postprocess就是nms的时间
@universea 是的目前还不支持numpy作为输入，但这个在我们TODO列表里，我们会尽快支持的。:)

**Comment by Zzh-tju** [comment]
```python
yolo mode=val task=detect data=coco.yaml model=yolov8n.pt batch=1 device=0
Ultralytics YOLOv8.0.4 🚀 Python-3.8.15 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24265MiB)
Fusing layers...
YOLOv8n summary: 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
val: Scanning /home/ubuntu/data/coco/labels/val2017.cache... 4952 images, 48 backgrounds, 0 corrupt: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 5000/5000 [01:09<00:00, 71.52it/s]
Speed: 0.2ms pre-process, 2.5ms inference, 0.0ms loss, 0.4ms post-process per image
```

想问下各位，算FPS我该相信哪一个？按照时间的话，69s推理5k图片应该是72.5 FPS，而如果按照inference time，则应该是FPS=1000/3.1=322.6。这不科学啊

**Comment by Wanghe1997** [comment]
> ```python
> yolo mode=val task=detect data=coco.yaml model=yolov8n.pt batch=1 device=0
> Ultralytics YOLOv8.0.4 🚀 Python-3.8.15 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24265MiB)
> Fusing layers...
> YOLOv8n summary: 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
> val: Scanning /home/ubuntu/data/coco/labels/val2017.cache... 4952 images, 48 backgrounds, 0 corrupt: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
>                  Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 5000/5000 [01:09<00:00, 71.52it/s]
> Speed: 0.2ms pre-process, 2.5ms inference, 0.0ms loss, 0.4ms post-process per image
> ```
> 
> 想问下各位，算FPS我该相信哪一个？按照时间的话，69s推理5k图片应该是72.5 FPS，而如果按照inference time，则应该是FPS=1000/3.1=322.6。这不科学啊

你用predict.py检测一遍验证集（测试集），算平均时间，我感觉这样才准，我自己是算inference和nms时间的总和（忽略前处理时间）。我在yolov5就是这么做的。

**Comment by Zzh-tju** [comment]
@Wanghe1997 
按照你说的detect.py 我用秒表记录了一下。秒表得出的时间会比我上面列出的 `5000/5000 [01:09<00:00, 71.52it/s]`还要久一些。我发现detect.py使用了较大的分类得分阈值，以及把NMS的IoU阈值降低到了0.45。在对5k张图片推理时，每张图后面都会显示时间，就像这样

```python
image 4996/5000 /home/ubuntu/data/coco/val2017/000000581317.jpg: 384x640 1 person, 1 cow, 2 cell phones, 2.4ms
image 4997/5000 /home/ubuntu/data/coco/val2017/000000581357.jpg: 640x640 22 persons, 3 cars, 2 skateboards, 2.7ms
image 4998/5000 /home/ubuntu/data/coco/val2017/000000581482.jpg: 448x640 3 clocks, 2.4ms
image 4999/5000 /home/ubuntu/data/coco/val2017/000000581615.jpg: 640x480 1 toilet, 2.2ms
image 5000/5000 /home/ubuntu/data/coco/val2017/000000581781.jpg: 480x640 67 bananas, 1 apple, 18 oranges, 2.4ms
Speed: 0.1ms pre-process, 2.4ms inference, 0.3ms NMS per image at shape (1, 3, 640, 640)
```
实际上应该就是显示模型inference的时间。

目前来看，秒表记录的时间>进度条右侧的用时>(pre-process time + inference time + NMS time)*5000

秒表记录的时间包含了加载数据的时间，以及一些杂七杂八的时间。进度条右侧的用时可能只包含加载数据的时间，杂七杂八的用时没包括进来。而最终显示的pre-process time, inference time, NMS time就是字面意思。

我认为加载数据的用时是必不可少的，所以我准备以进度条右侧用时为准了

**Comment by universea** [comment]
> 



> > > 因为你是将 time.time()放在循环内了吧？所以每一个循环的时间都累加统计了
> > 
> > 
> > 我放外面也是这样，可能是加载图片时间算进去了，但是他这个predict好像不支持输入numpy数组
> 
> 那不清楚了。想问下学长，您图片中detect阶段测速的控制台指令是什么？我现在还在训练，还没到您这步，想提前了解下测速指令

预测的时候内部自带的，好像不需要其它指令

**Comment by Robotatron** [comment]
So what is the answer for this?
