### ISSUE TITLE
How to increase value of tracker_buffer 

### ISSUE THREAD

**Issue by litaldavar** [ultralytics/ultralytics#3225]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I set a higher value for tracker_buffer so my object's tracker_id won't get lost when it disappears for a short while
Thanks

**Comment by glenn-jocher** [comment]
@litaldavar tracker configuration YAMLs are here:
https://github.com/ultralytics/ultralytics/tree/main/ultralytics/tracker/cfg

**Comment by litaldavar** [comment]
There is one problem with that. The ulralytics is installed not cloned.

**Comment by glenn-jocher** [comment]
@litaldavar you can change the value of `tracker_buffer` in the tracker configuration file. The tracker configuration files can be found in the `ultralytics/tracker/cfg` directory of the YOLOv8 repository. Locate the specific YAML file you want to modify and open it. Look for the `tracker_buffer` parameter and update its value to your desired value. Saving the updated file will apply the new value for `tracker_buffer`. Keep in mind that a higher value for `tracker_buffer` will make the object's `tracker_id` less likely to get lost when it disappears temporarily.
