### ISSUE TITLE
why the P R and mAP50 always be 0?

### ISSUE THREAD

**Issue by BugOOM** [ultralytics/ultralytics#323]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/34702180/212230791-b89bfe8c-c9db-470a-a437-0fcd258043db.png)

**Comment by ichsan2895** [comment]
You have 2082 instances in just 79 images? Wow, I think thats the problem. **From my experience**, I suggest to use more images but has 10 - 20 instances/image. It more better than 50 intances/image but has lower images.

**Comment by sijie-Xu** [comment]
我认为是cuda和cudnn版本问题，16系列显卡没有半精度，但模型训练时候使用了半精度，导致无法计算

**Comment by BugOOM** [comment]
> You have 2082 instances in just 79 images? Wow, I think thats the problem. **From my experience**, I suggest to use more images but has 10 - 20 instances/image. It more better than 50 intances/image but has lower images.

signal detection，but this type of problem doesn't appear in yolov5

**Comment by BugOOM** [comment]
> 我认为是cuda和cudnn版本问题，16系列显卡没有半精度，但模型训练时候使用了半精度，导致无法计算

应该不是，跑v5就没问题

**Comment by Laughing-q** [comment]
> > 我认为是cuda和cudnn版本问题，16系列显卡没有半精度，但模型训练时候使用了半精度，导致无法计算
> 
> 应该不是，跑v5就没问题

我们这里复现不了这个问题，如果可以的话，你可以发我一部分数据复现一下么，十分感谢。邮箱：laughingq@163.com

**Comment by BugOOM** [comment]
> 

非常抱歉，数据集暂时无法共享，但可以看一下示例，训练的一个batch:
![image](https://user-images.githubusercontent.com/34702180/212532666-16bdff7e-305a-44a7-a072-c94fa6d89332.png)
因为很多信号都是很细长的，训练没有问题，但验证就出问题了
![image](https://user-images.githubusercontent.com/34702180/212532688-63e39ce1-e466-4f03-9e09-5b4e587abd28.png)

**Comment by BugOOM** [comment]
> > > 我认为是cuda和cudnn版本问题，16系列显卡没有半精度，但模型训练时候使用了半精度，导致无法计算
> > 
> > 
> > 应该不是，跑v5就没问题
> 
> 我们这里复现不了这个问题，如果可以的话，你可以发我一部分数据复现一下么，十分感谢。邮箱：[laughingq@163.com](mailto:laughingq@163.com)
非常抱歉，数据集暂时无法共享，但可以看一下示例，训练的一个batch:
![image](https://user-images.githubusercontent.com/34702180/212532666-16bdff7e-305a-44a7-a072-c94fa6d89332.png)
因为很多信号都是很细长的，训练没有问题，但验证就出问题了
![image](https://user-images.githubusercontent.com/34702180/212532688-63e39ce1-e466-4f03-9e09-5b4e587abd28.png)

**Comment by Laughing-q** [comment]
@BugOOM 有试过单独用val测试么

**Comment by BugOOM** [comment]
> @BugOOM 有试过单独用val测试么

好的，我试试

**Comment by BugOOM** [comment]
> @BugOOM 有试过单独用val测试么

我用test_python中的test_predict_dir进行检测，结果是这样的：
![image](https://user-images.githubusercontent.com/34702180/212533029-f8922889-8a77-41fa-b06d-212ebfa93293.png)
我在想代码在预测的时候针对形状特殊的物体做了什么处理吗

**Comment by Laughing-q** [comment]
@BugOOM 这个预测是正确的吗？
也麻烦请用下面的命令测试一下
```python
model = YOLO("your_model.pt")
model.val(data="your_data_yaml")
```

**Comment by BugOOM** [comment]
> @BugOOM 这个预测是正确的吗？ 也麻烦请用下面的命令测试一下
> 
> ```python
> model = YOLO("your_model.pt")
> model.val(data="your_data_yaml")
> ```

这个预测时有问题的，正确的预测是从左一直到右。
model.val结果是：
![image](https://user-images.githubusercontent.com/34702180/212533590-d7d999aa-76b2-4cbe-9275-b08b1fdfc238.png)

**Comment by Laughing-q** [comment]
@BugOOM 可能是因为你的目标检测太小，在训练的时候过滤掉了，过滤的代码在这：
[https://github.com/ultralytics/ultralytics/blob/ac628c0d3e4204236e370e399d45f6a15c2966dd/ultralytics/yolo/data/augment.py#L361](https://github.com/ultralytics/ultralytics/blob/ac628c0d3e4204236e370e399d45f6a15c2966dd/ultralytics/yolo/data/augment.py#L361)
你可以手动调整一下，或者说你关闭数据增强再试试

**Comment by BugOOM** [comment]
> @BugOOM 可能是因为你的目标检测太小，在训练的时候过滤掉了，过滤的代码在这：
> 
> https://github.com/ultralytics/ultralytics/blob/ac628c0d3e4204236e370e399d45f6a15c2966dd/ultralytics/yolo/data/augment.py#L361
> 
> 
> 你可以手动调整一下，或者说你关闭数据增强再试试

我考虑过这个，训练之前我就已经关闭了，训练阶段示例图如下：
![image](https://user-images.githubusercontent.com/34702180/212533753-90cdcbe5-fd94-4fc2-a99b-68fb5db627e6.png)
目前就是验证有问题（捂脸哭）

**Comment by BugOOM** [comment]
> 

这个我调过
![image](https://user-images.githubusercontent.com/34702180/212533905-241dfcfc-9c72-4e02-9b57-9bf2bc7c829f.png)
，我试试关闭数据增强，非常感谢

**Comment by BugOOM** [comment]
> @BugOOM 可能是因为你的目标检测太小，在训练的时候过滤掉了，过滤的代码在这：
> 
> https://github.com/ultralytics/ultralytics/blob/ac628c0d3e4204236e370e399d45f6a15c2966dd/ultralytics/yolo/data/augment.py#L361
> 
> 
> 你可以手动调整一下，或者说你关闭数据增强再试试

这个我调过
[image](https://user-images.githubusercontent.com/34702180/212533905-241dfcfc-9c72-4e02-9b57-9bf2bc7c829f.png)
，我试试关闭数据增强，非常感谢

**Comment by BugOOM** [comment]
> @BugOOM 可能是因为你的目标检测太小，在训练的时候过滤掉了，过滤的代码在这：
> 
> https://github.com/ultralytics/ultralytics/blob/ac628c0d3e4204236e370e399d45f6a15c2966dd/ultralytics/yolo/data/augment.py#L361
> 
> 
> 你可以手动调整一下，或者说你关闭数据增强再试试

有没有可能和样本匹配方式有关，对于比较细长的物体很难匹配正样本

**Comment by Laughing-q** [comment]
@BugOOM 额有可能，但是我觉得应该还是能匹配的。主要目前我们这无法复现。。如果之后你有任何发现请及时告诉我们。

**Comment by Laughing-q** [comment]
@BugOOM 
> 有没有可能和样本匹配方式有关，对于比较细长的物体很难匹配正样本

之后我会用一些这样的数据测试一下，有任何发现我会同步给你

**Comment by BugOOM** [comment]
> @BugOOM 额有可能，但是我觉得应该还是能匹配的。主要目前我们这无法复现。。如果之后你有任何发现请及时告诉我们。

OK，感谢您的回复

**Comment by Laughing-q** [comment]
@BugOOM hi,  may I ask if there're corrupt labels in your datasets?
![oRFtMgd2vI](https://user-images.githubusercontent.com/61612323/213076139-3ec3d352-42ca-4b8a-82ed-3834b40364c2.jpg)
actually I just found that we got a mismatch issue if there's corrupt label in datasets, so if you guys got corrupt labels then your issues could be solved by this PR. #460

**Comment by BugOOM** [comment]
> 

这个确实会有影响，但是我也发现了yolov8不足的地方，就是对于极端比例的物体来说没法检测
![image](https://user-images.githubusercontent.com/34702180/225023597-c508f8f8-f3f9-4942-a6d9-b0e517ba52ee.png)
就比如这张图，那种小的都可以检测，但是这种长的就适应不了了

**Comment by pderrenger** [comment]
@BugOOM 对于极端比例的物体，YOLOv8目前可能存在检测不足的情况。这是一个很好的观察，我们会持续改进模型以解决这个问题。感谢你的反馈，我们会关注这个问题并努力改进模型的性能。
