### ISSUE TITLE
Hyperparameter Tuning errors [Possible Bug?]

### ISSUE THREAD

**Issue by parthapn98** [ultralytics/ultralytics#3231]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

We get a ray tune error on invoking model.tune, 

```ValueError: The actor ImplicitFunc is too large (202 MiB > FUNCTION_SIZE_ERROR_THRESHOLD=95 MiB). Check that its definition is not implicitly capturing a large array or other object in scope. Tip: use ray.put() to put large objects in the Ray object store.
```

Since we donot actually deal with any ray tune parameters outside of model.tune space parameters, should we change something in our configuration or should it be handled inside yolo?

To note: 
- invoking model.train with same parameters works fine on our hardware,
- model.tune works fine with s and n models

Reproducable code
```python
def hyper_optim(data: str,
                model: str,
                optim: Dict[str,List],
                train_args: Dict):

    model = YOLO(model)

    for key, val in optim.items():
        optim[key] = tune.uniform(val[0],val[1])

    results = model.tune(
        data=data,
        space=optim,
        train_args=train_args
    )
    print(results)
```

config:
```
data: */coco/annotations.yaml
model: yolov8m-pose.pt
optim:
  lr0: [1e-5, 1e-1]
  lrf: [0.01, 1.0]
  momentum: [0.6, 0.98]
  weight_decay: [0.0, 0.001]
  warmup_epochs: [0.0, 5.0]
  warmup_momentum: [0.0, 0.95]
  box: [0.02, 0.2]
  cls: [0.2, 4.0]
  hsv_h: [0.0, 0.1]
  hsv_s:	    [0.0, 0.9]
  hsv_v:	    [0.0, 0.9]
  degrees:	    [0.0, 45.0]
  translate:	[0.0, 0.9]
  scale:	    [0.0, 0.9]
  shear:	    [0.0, 10.0]
  perspective:	[0.0, 0.001]
  flipud:	    [0.0, 1.0]
  fliplr:	    [0.0, 1.0]
  mosaic:	    [0.0, 1.0]
  mixup:	    [0.0, 1.0]
  copy_paste:	[0.0, 1.0]
train_args:
  epochs: 100
  imgsz: 1280
  batch: 1
  show: True
  seed: 123
  workers: 16
  cache: disk
  device: cuda

```

**Comment by glenn-jocher** [comment]
@AyushExel possible Ray Tune integration issue, can you take a look?

**Comment by AyushExel** [comment]
@parthapn98  What is the actual error ? the config seems fine. If its working for n and s model and only failing for larger ones then most probably its related to your system resources

**Comment by parthapn98** [comment]
The actual error is ValueError

Note: this is running on a 3090 24Gb. For the given model size there shouldnt really be a reaource bottleneck here and our data batch is kept at 1-3 rn for testing purposes, also on disk.

And also model m trains fine on this pc, without full utilisation of gpu. Irs just crashing in tuning, i raised the issue because of the following

```
ValueError: The actor ImplicitFunc is too large (202 MiB > 95....
```

Its thrown from inside the ray tune

for you its showing 101MB for me its 200+

**Comment by AyushExel** [comment]
yeah but what's the max run set to? that many runs should be running in parallel trying to utilize the resources. And it's not only the GPU, it's also memory and CPU workers, so I wouldn't discount the resource bottleneck.
set `gpu_per_trial` to 1 and stat with `max_trials` to 1. If that works then try increasing the max trials.

**Comment by parthapn98** [comment]
Okay ill try with these changes. Thanks

**Comment by glenn-jocher** [comment]
Hi @parthapn98,

It seems like you're encountering a `ValueError` when using `model.tune()` in YOLOv8. The error message indicates that the actor `ImplicitFunc` is too large, exceeding the threshold limit of 95 MiB.

This error can occur when there is insufficient memory to handle the large objects being used in the tuning process. While it's true that you have a powerful GPU (3090 24GB), it's important to consider other system resources such as memory and CPU workers as well.

To address this issue, you can try reducing the parallelization by setting `max_trials` to 1 and `gpu_per_trial` to 1. This will limit the number of parallel runs and help manage the resource usage.

If the error persists, you may need to further optimize your system resources to ensure sufficient memory capacity.

Hope this helps! Let me know if you have any further questions.

Best regards,
Glenn Jocher
