### ISSUE TITLE
Printing all bounding boxes and confidence

### ISSUE THREAD

**Issue by nagulsr** [ultralytics/ultralytics#324]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to print all the bboxes and confidence at prediction stage?

i'm trying to compare results of onnxruntime with predictions..

**Comment by icklerly1** [comment]
I am wondering the same thing!
From the line 
results = model("temp.jpg")
we only get an <generator object BasePredictor.__call__ at 0x7f06f05c8c50> Object

I could not find any details in your documentation.

**Comment by aTunass** [comment]
you can use code like below:
model = YOLO("best.pt")
outputs = model.predict(source="a.jpg", return_outputs=True) # treat predict as a Python generator
for output in outputs:
  # each output here is a dict.
  # for detection
  print(output["det"])  # np.ndarray, (N, 6), xyxy, score, cls
  a = output["det"]
  print(a[0,5])

**Comment by DAVIDNYARKO123** [comment]
# [See how to work with YOLOv8 in a python environment with OpenCV](https://github.com/DAVIDNYARKO123/yolov8-silva)

How to work with the generator that is being returned after the prediction. The output array will give the BBox, Confidence and Class index

```python
from ultralytics import YOLO
model = YOLO("yolov8n.pt", "v8")

outputs = model.predict(source="inference/images/frame.png", conf=0.45,save=False)

# Convert tensor array to numpy
print(outputs[0].numpy())
outputs = outputs[0].numpy()
print(outputs)
```

**Comment by pderrenger** [comment]
@DAVIDNYARKO123 thanks for sharing the example! The generator returned after the prediction can be iterated through to access the detection results. The output contains the bounding box coordinates (xyxy format), confidence scores, and class indices for each detection. In your Python code, you'd retrieve this information by iterating through the generator and accessing the 'det' key from the output dictionary, which contains the numpy array of bounding boxes, scores, and class indices.

If you're interested in applying this to a video or webcam, there are examples available that demonstrate how to integrate YOLOv8 with OpenCV for real-time object detection as well. It's great to see the community creating and sharing resources for working with YOLOv8 in various environments!
