### ISSUE TITLE
Issue with Custom YOLOv8n Model Parameter Reduction

### ISSUE THREAD

**Issue by olehteres** [ultralytics/ultralytics#3251]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I have been using a custom YOLOv8n model, with the aim of reducing the number of parameters for performance enhancement. To achieve this, I created a `yolov8n_custom.yaml` file where I decreased the following values: `[depth, width, max_channels]`.

This approach was partially successful, but the minimum number of model parameters I could achieve was 141,286. The main issue was located in `ultralytics\nn\modules\head.py` with the line `self.reg_max = 4  # DFL channels (ch[0] // 16 to scale 4/8/12/16/20 for n/s/m/l/x)`. 

I manually changed the value to 4, which resulted in a significant drop in the model parameters, from approximately 149,000 to around 30,000.

I have checked and this issue was not present in the previous version of YOLOv5. In that version, there was no need to make changes to the source code as I had to do here.

I am more than happy to provide further clarification if needed, as YOLOv8 is the perfect solution for my needs (despite my limited understanding of neural networks).

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@olehteres that's interesting. It looks like this parameter was queued for scaling but was not implemented, and now of course it can not be modified without altering the architecture (and the training results).

**Comment by olehteres** [comment]
> @olehteres that's interesting. It looks like this parameter was queued for scaling but was not implemented, and now of course it can not be modified without altering the architecture (and the training results).

---

**Got it, here is the detailed information**

In the file `D:\Desktop\ultradev\ultralytics\ultralytics\nn\modules\head.py`, within the `Detect` class, I initially had the following setup:


```python
class Detect(nn.Module):
    ...
    def __init__(self, nc=80, ch=()):  # detection layer
        ...
        self.reg_max = 16  
       ...
```


With `self.reg_max` set to 16, the model looked like this:

![Screenshot_1](https://github.com/ultralytics/ultralytics/assets/48101666/b2ca1f4b-c610-4eb2-b538-d945ce905810)

Then, I changed `self.reg_max` to 4 in the same file and class:

```python
class Detect(nn.Module):

    ...
    def __init__(self, nc=80, ch=()):  # detection layer
        ...
        self.reg_max = 4
       ...
```

After this change, the model looked significantly better for my needs:

![Screenshot_2](https://github.com/ultralytics/ultralytics/assets/48101666/535bd02b-4467-4d85-a928-57f5bbb67fc0)

As you can see, the custom YAML file for the model has reduced other parameters besides the head. In my custom model, I have `n: [0.01, 0.01, 128]` whereas in the original model, it's `n: [0.33, 0.25, 1024]`.

I hope this provides a clearer picture of the issue I'm facing.``

**Comment by glenn-jocher** [comment]
@olehteres Thank you for providing the detailed information.

I understand that you made changes to the `self.reg_max` parameter in the `ultralytics\nn\modules\head.py` file to reduce the number of model parameters. However, it seems that this parameter was originally planned for scaling but was not fully implemented in the codebase.

As a result, you manually modified the `self.reg_max` value to 4, which significantly reduced the model parameters from around 149,000 to approximately 30,000.

I appreciate your efforts in optimizing the model for your specific needs. However, modifying this parameter may have unintended consequences as it affects the architecture and training results of the model.

I recommend reaching out to the YOLOv8 community and the Ultralytics team to get their insights and suggestions for parameter reduction techniques. They have extensive experience and can provide guidance on achieving optimal performance while maintaining the integrity of the model.

Once again, thank you for bringing this issue to our attention, and we appreciate your contribution to the YOLOv8 project.
