### ISSUE TITLE
Import ultralytics error

### ISSUE THREAD

**Issue by qbKhanh** [ultralytics/ultralytics#3259]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My code:
import ultralytics
ultralytics.checks()

Error:
---------------------------------------------------------------------------
ScannerError                              Traceback (most recent call last)
[/home/billy/Candle_stick/Yolv8Training/yolov8.ipynb](https://file+.vscode-resource.vscode-cdn.net/home/billy/Candle_stick/Yolv8Training/yolov8.ipynb) Cell 3 in 1
----> [1](vscode-notebook-cell:/home/billy/Candle_stick/Yolv8Training/yolov8.ipynb#W2sZmlsZQ%3D%3D?line=0) import ultralytics
      [3](vscode-notebook-cell:/home/billy/Candle_stick/Yolv8Training/yolov8.ipynb#W2sZmlsZQ%3D%3D?line=2) ultralytics.checks()

File [~/anaconda3/envs/candle_detect/lib/python3.9/site-packages/ultralytics/__init__.py:5](https://file+.vscode-resource.vscode-cdn.net/home/billy/Candle_stick/Yolv8Training/~/anaconda3/envs/candle_detect/lib/python3.9/site-packages/ultralytics/__init__.py:5)
      1 # Ultralytics YOLO 🚀, AGPL-3.0 license
      3 __version__ = '8.0.119'
----> 5 from ultralytics.hub import start
      6 from ultralytics.vit.rtdetr import RTDETR
      7 from ultralytics.vit.sam import SAM

File [~/anaconda3/envs/candle_detect/lib/python3.9/site-packages/ultralytics/hub/__init__.py:5](https://file+.vscode-resource.vscode-cdn.net/home/billy/Candle_stick/Yolv8Training/~/anaconda3/envs/candle_detect/lib/python3.9/site-packages/ultralytics/hub/__init__.py:5)
      1 # Ultralytics YOLO 🚀, AGPL-3.0 license
      3 import requests
----> 5 from ultralytics.hub.auth import Auth
      6 from ultralytics.hub.utils import PREFIX
      7 from ultralytics.yolo.data.utils import HUBDatasetStats

File [~/anaconda3/envs/candle_detect/lib/python3.9/site-packages/ultralytics/hub/auth.py:5](https://file+.vscode-resource.vscode-cdn.net/home/billy/Candle_stick/Yolv8Training/~/anaconda3/envs/candle_detect/lib/python3.9/site-packages/ultralytics/hub/auth.py:5)
      1 # Ultralytics YOLO 🚀, AGPL-3.0 license
      3 import requests
----> 5 from ultralytics.hub.utils import HUB_API_ROOT, PREFIX, request_with_credentials
      6 from ultralytics.yolo.utils import LOGGER, SETTINGS, emojis, is_colab, set_settings
...
    ^
could not find expected ':'
  in "", line 4, column 1:
    uuid: 7a0bdf971b44bccdaeb35cbe47 ... 
    ^

**Comment by Kayzwer** [comment]
@qbKhanh can I know how you do the installation? it is less error prone if you clone directly from github.
Try
```
git clone https://github.com/ultralytics/ultralytics/
cd ultralytics/
pip install -e .
```
and run the code again.

**Comment by qbKhanh** [comment]
I tried it but this is my console:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/home/billy/Candle_stick/Yolv8Training/yolov8.ipynb](https://file+.vscode-resource.vscode-cdn.net/home/billy/Candle_stick/Yolv8Training/yolov8.ipynb) Cell 3 in 3
      [1](vscode-notebook-cell:/home/billy/Candle_stick/Yolv8Training/yolov8.ipynb#W2sZmlsZQ%3D%3D?line=0) import ultralytics
----> [3](vscode-notebook-cell:/home/billy/Candle_stick/Yolv8Training/yolov8.ipynb#W2sZmlsZQ%3D%3D?line=2) ultralytics.checks()

AttributeError: module 'ultralytics' has no attribute 'checks'

**Comment by Kayzwer** [comment]
@qbKhanh How about you try run the thing in code, cuz I tested your code dont have any problems
```
import ultralytics


if __name__ == "__main__":
    ultralytics.checks()
```

**Comment by qbKhanh** [comment]
@Kayzwer still the above error

**Comment by Kayzwer** [comment]
@qbKhanh Dont have problem in console also.
Python 3.11.3 (main, Apr 14 2023, 15:10:49) [GCC 12.2.1 20230201] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ultralytics
>>> ultralytics.checks()
Ultralytics YOLOv8.0.119 🚀 Python-3.11.3 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce GTX 1050, 4041MiB)
Setup complete ✅ (8 CPUs, 7.6 GB RAM, 125.9/914.9 GB disk)
>>>

**Comment by Kayzwer** [comment]
> @Kayzwer still the above error

you install by clone repo?

**Comment by qbKhanh** [comment]
I try both ways, if i use "pip install ultralytics" my first error occurs and if I clone repo the second one occurs

**Comment by Kayzwer** [comment]
@qbKhanh did you done `pip install -e .`?

**Comment by qbKhanh** [comment]
@Kayzwer  for sure, I did it

**Comment by Kayzwer** [comment]
@qbKhanh how about you try use venv by python instead of anaconda?

**Comment by glenn-jocher** [comment]
@Kayzwer

Thank you for reaching out to us. Regarding your issue, using a virtual environment (venv) instead of Anaconda may help resolve the error you are encountering. Anaconda can sometimes have compatibility issues with certain packages.

To create a virtual environment with Python, you can follow these steps:

1. Open a terminal or command prompt.
2. Navigate to your project directory.
3. Create a new virtual environment by running the command `python -m venv myenv` (replace `myenv` with your preferred environment name).
4. Activate the virtual environment by running the command `source myenv/bin/activate` on Mac/Linux or `myenv\Scripts\activate` on Windows.
5. Install the required packages by running `pip install -r requirements.txt` or `pip install ultralytics` within the virtual environment.
6. Run your code and see if the issue persists.

Using a virtual environment ensures that the dependencies are isolated and prevent conflicts with other packages in your system.

Please let me know if this solves your issue or if you need any further assistance.

**Comment by qbKhanh** [comment]
@Kayzwer @glenn-jocher thank you, I will try it and fb soon

**Comment by glenn-jocher** [comment]
@qbKhanh sure, here is a friendly and professional response to the GitHub issue:

"Thank you for your feedback! We appreciate your willingness to try the suggested solution using a virtual environment. This approach can help isolate dependencies and resolve compatibility issues. Please give it a try and let us know if it works for you. If you have any further questions or need assistance, feel free to ask. We're here to help! Thank you again for your support of YOLOv8."

**Comment by qbKhanh** [comment]
@glenn-jocher I tried with virtual env by pip but i still got this error:
ScannerError                              Traceback (most recent call last)
Cell In[2], line 1
----> 1 from ultralytics import YOLO
      3 # Load the model.
      4 model = YOLO('yolov8n.pt')

File /media/billy/DATA/KhanhDuong/khanhduong/lib/python3.9/site-packages/ultralytics/__init__.py:5
      1 # Ultralytics YOLO 🚀, AGPL-3.0 license
      3 __version__ = '8.0.119'
----> 5 from ultralytics.hub import start
      6 from ultralytics.vit.rtdetr import RTDETR
      7 from ultralytics.vit.sam import SAM

File /media/billy/DATA/KhanhDuong/khanhduong/lib/python3.9/site-packages/ultralytics/hub/__init__.py:5
      1 # Ultralytics YOLO 🚀, AGPL-3.0 license
      3 import requests
----> 5 from ultralytics.hub.auth import Auth
      6 from ultralytics.hub.utils import PREFIX
      7 from ultralytics.yolo.data.utils import HUBDatasetStats

File /media/billy/DATA/KhanhDuong/khanhduong/lib/python3.9/site-packages/ultralytics/hub/auth.py:5
      1 # Ultralytics YOLO 🚀, AGPL-3.0 license
      3 import requests
----> 5 from ultralytics.hub.utils import HUB_API_ROOT, PREFIX, request_with_credentials
...
    ^
could not find expected ':'
  in "", line 4, column 1:
    uuid: 7a0bdf971b44bccdaeb35cbe47 ... 
    ^

**Comment by glenn-jocher** [comment]
@qbKhanh hi there,

Thank you for reaching out with your issue. I apologize for the trouble you're experiencing.

The error you're encountering suggests a syntax error in the code. It seems that there might be an issue with the YAML file, specifically an unexpected colon (':').

To troubleshoot this, I would recommend checking the YAML file that is being imported. Make sure there are no syntax errors, such as missing or misplaced colons. If possible, you could also try using a different YAML file to see if the issue persists.

If the issue persists or you need further assistance, please don't hesitate to ask. We're here to help!

Thank you for your support of YOLOv8.

**Comment by Teut2711** [comment]
> @qbKhanh How about you try run the thing in code, cuz I tested your code dont have any problems
> 
> ```
> import ultralytics
> 
> 
> if __name__ == "__main__":
>     ultralytics.checks()
> ```

Does it uses multiprocessing inside or how does this fix it?
