### ISSUE TITLE
Regarding rectangular training and export to onnx

### ISSUE THREAD

**Issue by jayer95** [ultralytics/ultralytics#326]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi @glenn-jocher 

Thank you for your contribution to yolo, I believe yolov5/yolov8 are the best yolo, the best to use.

Our training data is all 3840x1080 (landscape), and we are conducting yolov5 rectangular training (--rect), so when converting to onnx, we use this parameter "--imgsz 96 320".

When we convert to onnx in yolov8,
how do I specify it as a rectangle?

Here is my conversion cmd:
`yolo task=detect mode=export model=runs/detect/train/weights/last.pt imgsz=192,640 simplify=true format=onnx opset=11
`

But the imgsz part is incorrect.

**Comment by knoppmyth** [comment]
`yolo mode=export model=runs/detect/train/weights/last.pt imgsz=[192,640] simplify=true format=onnx opset=11 `

**Comment by Laughing-q** [comment]
@knoppmyth hi yeah actually we're using hydra but it seems not to support list this way. But we'll work on it.
For now I recommend you to use python interface for any situation needs list:
```python
model = YOLO("your_model.pt")
model.export(imgsz=[192,640], simplify=true, format=onnx, opset=11 )
```
this should work.

**Comment by Laughing-q** [comment]
@knoppmyth hi now the following command is working as expect:
```bash
yolo task=detect mode=export model=runs/detect/train/weights/last.pt imgsz=192,640 simplify=true format=onnx opset=11
```
closing this issue, feel free to reopen it if you have related issues. :)
