### ISSUE TITLE
adding Yolo Hand + face to the pose model!

### ISSUE THREAD

**Issue by p0mad** [ultralytics/ultralytics#3265]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi,
Thanks for great project

I was wondering if it is possible to add hand + face keypoints (more than 30 on face) to the model to be able to detect the points?

thanks
best regards

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@p0mad yeah I think it's possible! please let me know if you have any experimental results on it!

**Comment by p0mad** [comment]
@Laughing-q 
Thanks for the reply!
Have you ever seen such a fork, ... on this subject? ( something like Mediapipe Holistic)

Thanks
Best regards

**Comment by blackCmd** [comment]
I am also curious. I want to detect keypoints of a car, not a human.
I have created a total of 8 keypoints of the car.
However, when I used `JsonToYolo` to convert the dataset I created, only empty files were generated.

Can I train with a custom dataset that has only 8 keypoints, not 17 keypoints?

**Comment by blackCmd** [comment]
Can't do it..
I am trying 8 keypoint of car. 
But can't train well..

**Comment by pderrenger** [comment]
@blackCmd i understand the challenge. Training a model to detect 8 keypoints of a car can be complex. It's essential to ensure that the dataset is diverse and representative of the scenarios you intend to use the model in. Additionally, model architecture, hyperparameters, and training strategies play crucial roles in achieving good results. Feel free to share more details, and I'd be glad to offer assistance.
