### ISSUE TITLE
nan values for all val_losses (box, cls, dfl) though precision, recall, mAP etc. seem to be fine

### ISSUE THREAD

**Issue by binit9** [ultralytics/ultralytics#3267]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello Ultralytics,

I have recently incrementally trained (fine-tuned) a already trained Yolov8 model (on a larger, but slightly varying dataset, same classes). While mAP and other metrics show improvement during the training, the val_losses - **box_loss, cls_loss, and dfl_loss** had **nan** values throughout the process. 

Best model attained at around 35 epochs, but since patience was set at 100, total number of epochs = 137. I changed LR values to: **lr0=0.0001, warmup_bias_lr=0.001** assuming LR should be low during fine-tuning.

Pls have a look at a screen shot from results.csv:

<img width="874" alt="TS+DOT_training_epochs" src="https://github.com/ultralytics/ultralytics/assets/25927344/0df9557f-86cd-4855-bd4d-6c423a19f8b8">

Also take a look at the results.png, which seems good except the val_losses:

![TS+DOT_results](https://github.com/ultralytics/ultralytics/assets/25927344/4cfada6d-30ff-4aa1-9697-16b15a6b6ae9)

About model performance: fine-tuned model performs really good on the new test data (new domain), but its performance degraded considerably on the previous, larger test data (older domain). I am bit curious whether this is a general trend or this performance degradation has a link with the nan values during training.

Pls let me know if you need any other info. Thanks a lot in advance.

**Comment by Laughing-q** [comment]
@binit9 what the ultralytics package version you are using? I remember the nan values issue existed in previous version, and should have been solved.

**Comment by binit9** [comment]
> @binit9 what the ultralytics package version you are using? I remember the nan values issue existed in previous version, and should have been solved.

@Laughing-q  Initially I trained with version 8.0.55 and later updated to 8.0.119 but no change in val_losses.

I went through issues having nan values for training losses, but in my case training losses are fine. Also those issues were fixed in version 8.0.50, I guess.

**Comment by Laughing-q** [comment]
@binit9 can you try to reproduce the issue with coco128.yaml? Thanks!
