### ISSUE TITLE
Change default save_dir path

### ISSUE THREAD

**Issue by icklerly1** [ultralytics/ultralytics#327]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, 
I was wondering how I can change the default save_dir variable.

Per Default everything gets saved in the ./runs/detect/train directory. But I want to change the location of that from command line or python code.

Do you have a tip for me?

Thanks in advance!

**Comment by icklerly1** [comment]
Thanks for your quick answer! That helps a lot!

Another question: Can I set the interval in which the model files are saved? 
save_period=1 Or something?

**Comment by AyushExel** [comment]
I think we do but its not documented.
@glenn-jocher implementing a env variable setting

**Comment by icklerly1** [comment]
Do you support a save-interval by now?
Or how would I force a weight-save after each epoch?

**Comment by ousaghro** [comment]
hello thank you
i change to save_dir parametre but the file don't save it to the directory, please how i  can do the save of the file after the detection and change the name defaulte .
