### ISSUE TITLE
RT-DETR's smaller model

### ISSUE THREAD

**Issue by sdreamforchen** [ultralytics/ultralytics#3279]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello，
If I want to design a N or Tiny model for RT-DERT, like YoloV8n YoloV8t, how should i design the config?
Thanks a lot

**Comment by Kayzwer** [comment]
you need to modify .yaml in `ultralytics/ultralytics/models/rt-detr/`

**Comment by glenn-jocher** [comment]
@sdreamforchen you could try `yolov8n-rtdetr.yaml`, this builds `yolov8-rtdetr.yaml` with an `n` scaling.

**Comment by Kayzwer** [comment]
> @sdreamforchen you could try `yolov8n-rtdetr.yaml`, this builds `yolov8-rtdetr.yaml` with an `n` scaling.

is it auto reply? cuz rtdetr only have x and l

**Comment by sdreamforchen** [comment]
> @sdreamforchen you could try `yolov8n-rtdetr.yaml`, this builds `yolov8-rtdetr.yaml` with an `n` scaling.

train  can't recognize the yolov8-rtdetr.yaml, No HybridEncoder module

**Comment by lyuwenyu** [comment]
For all scaled models, please check https://github.com/lyuwenyu/RT-DETR/tree/main

![image](https://github.com/ultralytics/ultralytics/assets/17582080/b9d560f7-c83a-4ae4-a7b1-30f1bdf0c8f0)

**Comment by glenn-jocher** [comment]
@lyuwenyu hi there,

Thank you for raising this issue. It seems that the `yolov8-rtdetr.yaml` file is missing the HybridEncoder module. This module is necessary for the configuration of the YOLOv8 model in RT-DETR.

To resolve this issue, you can visit the [lyuwenyu/RT-DETR](https://github.com/lyuwenyu/RT-DETR/tree/main) repository, which provides scaled models for RT-DETR. You can find the necessary configuration files and code there.

Please note that this repository is not affiliated with the Ultralytics YOLOv8 repository. It is always important to carefully review and verify the compatibility and integrity of external repositories before using them.

Let me know if you have any further questions or need additional assistance.
