### ISSUE TITLE
mAP increases extremely rapidly 

### ISSUE THREAD

**Issue by SjoerdBoonen** [ultralytics/ultralytics#3288]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello! I have been training a YOLOv8s-seg model on my custom dataset consisting of over 9000 images with identity documents placed on various backgrounds. I trained the model for 100 epochs with a image size of 1024(x1024), with single_cls set to True (as my only class is "ID").

When I look at the results.csv and the results.png I notice that my mAP50, mAP50-95 for both the mask and bounding box increase extremely rapidly, after the first epoch they are still low (around 0.1), but for the second epoch they are already above 0.9. After the second epoch it only slightly increases and then converges to 0.995.

Is this intended behaviour? Because it seems too good to be true =)

![results](https://github.com/ultralytics/ultralytics/assets/91719735/16f0e1f2-e3ed-4042-90d3-b1e26437216a)

[results.csv](https://github.com/ultralytics/ultralytics/files/11801082/results.csv)

Thank you in advance!

### Additional

Some example pictures of my dataset:
![YOLO_POLY_s0_81_polka-dotted_0137](https://github.com/ultralytics/ultralytics/assets/91719735/c1696cda-4731-410a-beaa-8caf0e0e9f56)

![YOLO_POLY_s0_203_banded_0002](https://github.com/ultralytics/ultralytics/assets/91719735/76e12c71-9048-4d51-b0a6-3c56b3f4b6b4)

![YOLO_POLY_s0_907_woven_0073](https://github.com/ultralytics/ultralytics/assets/91719735/394c084e-6ea2-423e-af97-770f0f49521e)

Some annotations visualized (I'm sure they are all correct)
![image](https://github.com/ultralytics/ultralytics/assets/91719735/025332da-4d5b-4bcc-804c-9826c1ec5818)

One of the training batch predictions:
![train_batch0](https://github.com/ultralytics/ultralytics/assets/91719735/0d3f7313-5db4-4c8f-a217-9938d71fdc88)

**Comment by glenn-jocher** [comment]
@SjoerdBoonen welcome to YOLOv8 😂

**Comment by SjoerdBoonen** [comment]
> @SjoerdBoonen welcome to YOLOv8 😂

🤣 In all seriousness though, is this normal? If so, wow... Amazing!

**Comment by glenn-jocher** [comment]
@SjoerdBoonen BTW your image of training batch is not predictions, these are labelled mosaics.
