### ISSUE TITLE
copy_paste parameter not affect training process

### ISSUE THREAD

**Issue by RomRoc** [ultralytics/ultralytics#3289]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Hello,
I trained yolov8x using copy_paste = 1, I obtain exactly same results in train valid and test using copy_paste = 0.
Even if I look to train_batch0.jpg images, I don't see the augmentation.
Is it correct?
Thanks a lot.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@RomRoc copy-paste augmentation is only applied when segmentation labels are available, otherwise for detection-only labels the entire box contents would have to be copied over.

**Comment by RomRoc** [comment]
Oh sorry, you are right, thanks a lot.

**Comment by pderrenger** [comment]
@RomRoc you're welcome! If you have any more questions or need further assistance, feel free to ask!
