### ISSUE TITLE
Collecting Data From YOLOv8 Bounding Boxes

### ISSUE THREAD

**Issue by colton1014** [ultralytics/ultralytics#3291]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm very new to coding and have just recently trained my first YOLOv8 model and tested it on a video.  Now I have a video with bounding boxes wherever the model sees the object I'm looking to detect as expected!  What I'd I like to do now is output the data in a .csv file or excel file (whatever is easiest).  All I need to know is the number of bounding boxes per frame of my video as I am only looking for a single object so the class is irrelevant.

I have used an Ubuntu 18.08 terminal for the entirety of this process and haven't really ventured into python.

Again, I am extremely new to all processes related to coding so my apologizes if this question is quite simple.  I am so close to reaching my goals, I just need to output data in a useful manor.

Thank you for any assistance that is provided.

**Comment by glenn-jocher** [comment]
@colton1014 you can output to *.txt with `save_txt=True` during predict, or you can handle `results` however you'd like in python. See https://docs.ultralytics.com/modes/predict/#working-with-results for details.

**Comment by colton1014** [comment]
@glenn-jocher Thanks so much for the reply!  It seems like save_txt doesn't accomplish what I need so I will look down the python path.  But follow up question:  If I have generated these prediction outputs (photos and videos) in a terminal how would I go about loading them into python so I can work with them?
