### ISSUE TITLE
Run pose model and detection model at the same time?

### ISSUE THREAD

**Issue by jimmybuffi** [ultralytics/ultralytics#3292]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm trying to capture both the joint key points for a person, and detect objects with bounding boxes, in the same image.

Is this possible to do using one function / class? Or would we have to create two different `YOLO` objects and run two different `predict` methods?

For example, to do both of these tasks on the same image, is the only solution to do something like this?

model_pose = YOLO('yolov8n-pose.pt')

results_pose = model_pose(img)

model_detect = YOLO('yolov8n.pt')

results_detect = model_detect(img)

**Comment by Kayzwer** [comment]
@jimmybuffi AFAIK there is no head provide such capability.
