### ISSUE TITLE
Resume checkpoint not found. Please pass a valid checkpoint to resume from, i.e. 'yolo train resume model=path/to/last.pt'

### ISSUE THREAD

**Issue by chelsea456** [ultralytics/ultralytics#3294]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

when i chose arg resume = 1 have this error

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@chelsea456 I think this is user error. Resume accepts a boolean or a path to a checkpoint to resume from. See https://docs.ultralytics.com/modes/train/#arguments

**Comment by glenn-jocher** [comment]
Actually I'm unsure about this. Adding a TODO to track.

**Comment by glenn-jocher** [comment]
@chelsea456 I've tested resume and everything works correctly. I've updated our Resume docs here to explain how it works better :)

https://docs.ultralytics.com/modes/train/#resuming-interrupted-trainings

<img width="1730" alt="Screenshot 2023-06-21 at 21 17 26" src="https://github.com/ultralytics/ultralytics/assets/26833433/5f8b7532-74c3-412f-b600-283207c23f56">
