### ISSUE TITLE
batch inference for images

### ISSUE THREAD

**Issue by zhanghang-official** [ultralytics/ultralytics#3297]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Since YOLOv8 currently does not support tensor inputs, how can batch inference for images be performed?

**Comment by Kayzwer** [comment]
@zhanghang-official you pass in directory to infer all images in it.

**Comment by zhanghang-official** [comment]
> @zhanghang-official you can pass in directory to infer all images in it.
directory input is also single infer not parallel bacth infer
