### ISSUE TITLE
CUDA out of memory while YOLOv8n-seg predicting

### ISSUE THREAD

**Issue by Accustomer** [ultralytics/ultralytics#3298]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

When I test yolov8n-seg model as example, the occupied CUDA memory increased with time. Finally, it raised "RuntimeError: CUDA out of memory". It seems that the variables on GPU have not been released while predicting.

![3dad440ba0f4b1269c6a543d0bdc894](https://github.com/ultralytics/ultralytics/assets/46698134/9c01ff73-a66d-4d35-a2c1-f84a4922a5a7)
![54c9d50388b1a08ff35d572fb454ff2](https://github.com/ultralytics/ultralytics/assets/46698134/cf211a7d-b428-45f0-ae14-7c5890884057)
![9657128c395679e33e8b36e17a867f2](https://github.com/ultralytics/ultralytics/assets/46698134/5e8f78e0-edac-4b7d-9739-99bade92622b)
![7da83a7dda5c9c22c956882d30e7b11](https://github.com/ultralytics/ultralytics/assets/46698134/184d8bd6-8841-4879-a29b-7dee895999e8)

### Minimal Reproducible Example

```
from ultralytics import YOLO
def inferDemo():
    model = YOLO("weights/yolov8n-seg.pt")
    model.predict(
        source='.../kaggle/ILSVRC/Data/CLS-LOC/test',
        save=False,
        save_txt=True,
        device='0'
    )    
if __name__ == '__main__':
    inferDemo()
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Accustomer user error. If you don't want results to accumulate then use streaming mode. See https://docs.ultralytics.com/modes/predict/
