### ISSUE TITLE
loss plot spikes when resume training

### ISSUE THREAD

**Issue by patraepl** [ultralytics/ultralytics#3299]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! 

I tried to do a small training of 250 epoch in Google Colab. 
While training, it got interrupted at epoch 152. Then, when I tried to resume the training, the loss trend didn't follow the previous training session, instead it went bigger. 

Plot result:

![results (1)](https://github.com/ultralytics/ultralytics/assets/137266570/8f1c1e5c-e4c5-49e9-ae2f-25c1ecc597f5)
loss spikes at epoch 153.

Initial command:
!yolo task=detect mode=train model=yolov8s.pt data={dataset.location}/data.yaml epochs=250 batch=48 imgsz=640 plots=True save=True patience=50

Resume command:
!yolo resume=True task=detect mode=train model=/mytest/runs/detect/train/weights/last.pt data={dataset.location}/data.yaml

The first initial training and the resume training were done in the same file location.

I also tried to test the resume training on different dataset and it still gives the same behavior.

What's wrong with my resume training?

**Comment by glenn-jocher** [comment]
@patraepl we've updated our resume docs here, please make sure you follow this usage. If this is reproducible on an official dataset like VOC please let us know, as we need a reproducible issue to start working on a fix.
https://docs.ultralytics.com/modes/train/#resuming-interrupted-trainings

**Comment by patraepl** [comment]
Sorry for the confusion. 
I ran the model again with the updated version and the resume went well. The problem might be because I was using the old version.

**Comment by pderrenger** [comment]
@patraepl glad to hear that the issue has been resolved with the updated version! If you encounter any further issues or have any questions, feel free to reach out. 😊

**Comment by glenn-jocher** [comment]
Great to hear the update resolved your issue, @pderrenger! Don't hesitate to get in touch if you need any more assistance. Happy training! 😊
