### ISSUE TITLE
Evolve for yolov8

### ISSUE THREAD

**Issue by p0wned17** [ultralytics/ultralytics#330]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, is there a --evolve method for yolov8, if so, can I get instructions on how to run it?

**Comment by AyushExel** [comment]
Evolve is not supported yet. We plan to work on it in the future

**Comment by UnglvKitDe** [comment]
I liked the genetic algorithm, but there are specialized libraries for hyperparameter tuning. e.g. raytune. There is also a guide from pytorch [here](https://pytorch.org/tutorials/beginner/hyperparameter_tuning_tutorial.html).

**Comment by PalTAJ** [comment]
any updates on evolve feature in yolov8 ?

**Comment by glenn-jocher** [comment]
@PalTAJ yes, we have a new PR open for integration of Ray Tune for hyperparameter optimization. See PR https://github.com/ultralytics/ultralytics/pull/1796 by @AyushExel
