### ISSUE TITLE
how to use different gpus in different threads 

### ISSUE THREAD

**Issue by lspze** [ultralytics/ultralytics#3300]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question
Hi!
I'm going to set their own predict models in different threads.
such as 
```
# thread0: 
result = model([image], save=False, conf=0.5, device=0)
# thread1:
result = model([image], save=False, conf=0.5, device=1)
# thread2:
result = model([image], save=False, conf=0.5, device=2)
```
but I find all result outputs is still " device = "cuda:0' "
then I find this file, I think "os.environ['CUDA_VISIBLE_DEVICES'] = device" doesn't take effect, it must be before "import torch"
![image](https://github.com/ultralytics/ultralytics/assets/46063990/1ecd6cec-4618-43c3-830a-d4d0ab265105)

how to solve this problem?

**Comment by pderrenger** [comment]
@lspze hi there! It seems like you're trying to run YOLOv8 with different GPUs in separate threads but encountering issues with the device assignment. 

To use different GPUs in different threads, you can set the CUDA_VISIBLE_DEVICES environment variable before initializing the PyTorch library. This can be done by running `os.environ['CUDA_VISIBLE_DEVICES'] = device` at the beginning of your script, before any import statements.

By setting this environment variable before the import of any GPU-related modules, you should be able to allocate different GPUs to different threads successfully.

Give this a try, and if you encounter any further issues, feel free to ask for more help 😊.
