### ISSUE TITLE
How to get the number of current iteration during YOLOv8 training?

### ISSUE THREAD

**Issue by MaxTeselkin** [ultralytics/ultralytics#3301]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! I want to get the number of current iteration (not number epoch, I mean iteration of an epoch) to set up a progress bar for my web application. Is it possible to get number of current iteration during YOLOv8 training? Or I will have to change the source code of YOLOv8 to add progress bar?

**Comment by glenn-jocher** [comment]
@MaxTeselkin YOLOv8 console output shows epoch and batch (in that epoch), you can solve for the iteration from those or develop a custom progress bar to show it.
