### ISSUE TITLE
Metrics during validation are always 0

### ISSUE THREAD

**Issue by wafflesdog** [ultralytics/ultralytics#3309]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I'm training a custom model on my own dataset and noticed that the validation results during training always give 0 like this:
```
Class     Images  Instances      Box(P          R      mAP50  mAP50-95):
all       120     482            0              0      0      0
```

What I tried to do is set training and validation on the same set and only use one image so it would start overfitting. 

My custom.yaml looks like this:
```
train: datasets/train  # train images 
val: datasets/train  # val images

nc: 2
names: [person, car]
```

Did not fix the validation results during training, but when i call the model.val() after the training is done it does give me results. 
Prediction also gives some results

### Environment

-YOLO: Ultralytics 8.0.51,  torch 1.8.2+cu11
-OS: Windows 
-Python 3.8.16

### Minimal Reproducible Example

model = YOLO('yolov8s.pt')
model.train(data="custom.yaml", epochs=10)
model.val()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
If val losses are reducing then all is good. Train longer.
