### ISSUE TITLE
how to modify yolov8 architecture to reduce depth

### ISSUE THREAD

**Issue by nikky4D** [ultralytics/ultralytics#3313]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would like to reduce Yolov8n depth but I'm not sure how to read the yaml file. 

would I need to modify this: ```n: [0.33, 0.25, 1024]``` or would I just modify the repeats in the layers in the backbone or the head of Yolov8n to reduce the total depth? would it be better to modify the head only or the backbone?

**Comment by glenn-jocher** [comment]
@nikky4D yes those are both valid ways to update the architecture. You can make changes to the YAML and see the immediate FLOPs/params result by running i.e. `yolo export model=model.yaml format=onnx simplify` and optionally view in Netron also.
