### ISSUE TITLE
Using ultralytics with torch 1.7 Jetson Xavier

### ISSUE THREAD

**Issue by Batselot** [ultralytics/ultralytics#3315]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi there. 

For my nvidia jetson xavier I am trying to use ultralytics. So far I have been able to use the cpu but for gpu I have some problems. 

It seems for me to use cuda on jetson xavier series I need to use this wheel that I found. I haven't found any other good solution for this. Docker images on jetpack 4.6 also comes with python3.6 installed so that's not what I want as well. 
Link:
[(https://drive.google.com/file/d/1lMSZu_hARJDpfZuJHc64Hb3OXntlRO--/view?pli=1)]

And that however doesn't fit into the requirements that ultralytics gives. Ultralytics requires torch>1.7.0 so I am in a pinch here. Can I change ultralytics so that I will specifically use 1.7 version.

By the way I don't specifically want to use TensorRT, I know that's a solution but using pytorch will be better in my case.

So what do you think is this possible? Do I have to resort to TensorRT?

Thanks!

**Comment by aurelm95** [comment]
Try to use the jetson docker image! You should be able to run your ultralytics scripts with jetson GPU

**Comment by Batselot** [comment]
@aurelm95 Are you sure that's supposed to work? I guess you are , but the base images I have worked with have python3.6 built in them which is not available for this repo as ultralytics requires for me to run on python3.8. Am I missing something here?

**Comment by aurelm95** [comment]
@Batselot The jetson ultralytics image has python3.8 so you don't have to worry about that!

**Comment by glenn-jocher** [comment]
Hi @aurelm95! You're right, the base images you've worked with may have Python 3.6 installed, but the jetson ultralytics image in particular includes Python 3.8, so you should be good to go! You don't need to worry about compatibility with the Python version required by Ultralytics. If you have any other questions or need further assistance, feel free to ask. Happy coding!

**Comment by TimotheeWrightFicha** [comment]
For all the people that will end up on this thread in the future, facing the same compatibility issues, I've tried to answer this in a stackoverflow thread:
[https://stackoverflow.com/q/78607175/13123667](https://stackoverflow.com/q/78607175/13123667)

**Comment by glenn-jocher** [comment]
Hi @TimotheeWrightFicha,

Thank you for sharing the StackOverflow link! For those encountering compatibility issues with Ultralytics on NVIDIA Jetson Xavier, here are some key points and solutions:

1. **Docker Image**: As mentioned earlier, using the pre-built Docker image for Jetson is a great way to get started. This image includes Python 3.8, which is compatible with Ultralytics. You can pull and run the Docker container with the following command:
    ```bash
    t=ultralytics/ultralytics:latest-jetson-jp5 && sudo docker pull $t && sudo docker run -it --ipc=host --runtime=nvidia $t
    ```

2. **Manual Installation**: If you prefer not to use Docker, you can manually install the necessary packages. Here’s a quick guide:
    - **Update Packages**:
        ```bash
        sudo apt update
        sudo apt install python3-pip -y
        pip install -U pip
        ```
    - **Install Ultralytics**:
        ```bash
        pip install ultralytics[export]
        ```
    - **Install PyTorch and Torchvision**:
        ```bash
        pip uninstall torch torchvision
        sudo apt-get install -y libopenblas-base libopenmpi-dev
        wget https://developer.download.nvidia.com/compute/redist/jp/v512/pytorch/torch-2.1.0a0+41361538.nv23.06-cp38-cp38-linux_aarch64.whl -O torch-2.1.0a0+41361538.nv23.06-cp38-cp38-linux_aarch64.whl
        pip install torch-2.1.0a0+41361538.nv23.06-cp38-cp38-linux_aarch64.whl
        sudo apt install -y libjpeg-dev zlib1g-dev
        git clone https://github.com/pytorch/vision torchvision
        cd torchvision
        git checkout v0.16.2
        python3 setup.py install --user
        ```

3. **Using TensorRT**: For optimal performance, consider exporting your model to TensorRT. Here’s how you can do it:
    ```python
    from ultralytics import YOLO

    # Load a YOLOv8n PyTorch model
    model = YOLO("yolov8n.pt")

    # Export the model to TensorRT format
    model.export(format="engine")  # creates 'yolov8n.engine'

    # Load the exported TensorRT model
    trt_model = YOLO("yolov8n.engine")

    # Run inference
    results = trt_model("https://ultralytics.com/images/bus.jpg")
    ```

For more detailed instructions, you can refer to our [NVIDIA Jetson Guide](https://docs.ultralytics.com/guides/nvidia-jetson/).

If you encounter any issues or have further questions, feel free to ask. We're here to help! 😊
