### ISSUE TITLE
traffic signal detection 

### ISSUE THREAD

**Issue by brijeshhr** [ultralytics/ultralytics#3322]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

data.yaml  file not found issue , even though there is  a file contained in it.[
![issue](https://github.com/ultralytics/ultralytics/assets/137390173/be704b09-96ea-41cb-a348-d395917b6f61)
](url)
model.train(data="/content/data.YAML",epochs=25)
while executing the above code!!!

**Comment by pderrenger** [comment]
@brijeshhr hi there! It looks like you're encountering an issue with the `data.yaml` file while using YOLOv8. When referencing the `data` parameter in the `model.train` function, make sure the file path is correctly specified. 

The error you're seeing could indicate that the file path is incorrect or that the file may not be in the expected format. Ensure that the file path points to the exact location where the `data.yaml` file is located, and double-check that the file itself follows the required format for YOLOv8 training.

If the issue persists, feel free to provide more details or code snippets for further assistance. We're here to help you out!
