### ISSUE TITLE
Learning rate finder

### ISSUE THREAD

**Issue by kaane8520** [ultralytics/ultralytics#3325]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Auto learning rate finder, something like here: https://pytorch-lightning.readthedocs.io/en/1.4.5/advanced/lr_finder.html  
to help find automatically the best initial learning rate for a training. 
I saw similar feature request here: https://github.com/ultralytics/ultralytics/issues/925 but unfortunately it has been closed and I think that this would be very helpful.

### Use case

This would help while training models, especially training from checkpoint/finetuning 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by aiakash** [comment]
@kaane8520 you can try raytune for finding best parameters, yolov8 has support for this

**Comment by glenn-jocher** [comment]
Hi @aiakash! Glad to see your interest in YOLOv8. To assist with finding the most appropriate initial learning rate for training from scratch, Ultralytics supports integrations with tools such as `raytune`. `raytune` is a powerful library used to perform hyperparameter tuning, including finding the best learning rate for training your model. You can consider using `raytune` with YOLOv8, as it helps automate and streamline the process of trying many different hyperparameters. Do let us know if you have any further questions!

**Comment by kaane8520** [comment]
Hi, thanks for your answers!
Finetuning models from scratch with raytune like this (I used docs: https://docs.ultralytics.com/usage/hyperparameter_tuning/):

```
model = YOLO("yolov8n.pt")
result = model.tune(
    data="my_data_config.yaml",
    space={"lr0": tune.uniform(1e-5, 1e-1)},
    train_args={"epochs": 50}
) 
```
seems to work fine, but I would like to finetune my own models (`model = YOLO("my_model.pt")`) and it doesn't work as I am getting this error:

> ValueError: Tracked actor is not managed by this event manager 

followed by:

> ValueError: The actor ImplicitFunc is too large (522 MiB > FUNCTION_SIZE_ERROR_THRESHOLD=95 MiB). Check that its definition is not implicitly capturing a large array or other object in scope. Tip: use ray.put() to put large objects in the Ray object store.

I run finetuning on 1 GPU (16 GB RTX), 8 CPUs and 32 Gi RAM. My model's weight is 131M

Did anyone coped with this error?

**Comment by glenn-jocher** [comment]
@kaane8520 hi there! Thank you for reaching out. It seems like you're encountering an error when attempting to finetune your own YOLOv8 model using `raytune`.

The error message "ValueError: Tracked actor is not managed by this event manager" suggests that there might be an issue with the management of the actor during the training process. This error can occur if the actor is not correctly set up or if there is an incompatibility between the actor and the event manager.

The additional error message "ValueError: The actor ImplicitFunc is too large (522 MiB > FUNCTION_SIZE_ERROR_THRESHOLD=95 MiB)" indicates that the size of the actor is exceeding the predefined threshold. This can happen when the size of the actor or the objects it captures in scope is too large.

To resolve these issues, you may need to make some adjustments. Here are a few suggestions:

1. Ensure that you have correctly set up and configured the actor for your specific use case. Check if there are any missing configurations or dependencies that may be causing the error.

2. Consider reducing the size of your model if possible. The error message mentions that your model's weight is 131M, which might be pushing the limits of the available memory. Reducing the size of your model could help avoid memory-related issues.

3. If you're passing large objects or arrays to the actor, you can use `ray.put()` to explicitly put these objects in the Ray object store. This can help manage memory usage more efficiently.

4. Consider adjusting the resource allocation for the Ray cluster. You mentioned using 1 GPU, 8 CPUs, and 32 GiB of RAM. You could try increasing the available memory or reducing the batch size to free up memory resources.

Keep in mind that these suggestions are general recommendations and may require further investigation based on your specific use case. If you continue to experience issues, please provide additional details about your setup and configurations, as this will help narrow down the problem and provide more targeted assistance.

**Comment by Won-JoonChoi** [comment]
Hello @glenn-jocher, can you show an example code how to use `ray.put()` to pass a large model to `tune()` method?
