### ISSUE TITLE
Best way to incorporate augmentations into YOLOv8 segmentation YAML file?

### ISSUE THREAD

**Issue by Karin2413** [ultralytics/ultralytics#3328]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm currently working on a project using YOLOv8 for segmentation tasks, and I would like to incorporate augmentations into my workflow. I have a YAML file that defines the configuration for my YOLOv8 model, and I'm wondering what is the best way to add augmentations to this file.

Specifically, I would like to apply augmentations such as random cropping, random flipping, mosaic and color jittering to my input images before they are fed into the YOLOv8 model for training. I'm not sure how to integrate them with the YAML configuration.

Could anyone provide guidance on the recommended approach to include augmentations in the YAML file for YOLOv8 segmentation? Are there any specific parameters or sections that need to be added or modified in order to incorporate these augmentations properly?

Any help or code examples would be greatly appreciated. Thank you in advance for your assistance!

### Additional

My ymal file is as follows:

`train: './datasets/train/'
val: './datasets/val/'
test: './datasets/test/'

nc: 5

# class names
names: ["dog", "cat", "rabbit", "mouse", "hamster"]
augmentations:
- Albumentations:
    blur_limit: 1
    translate: 0.1
    scale: 0.2
    shear: 0.2
    perspective: 0.1
    flipud: 0.7
    fliplr: 0.5
    mosaic: 0.3
    mixup: 0.1
    brightness_contrast: 
      brightness_limit: 0.1
      contrast_limit: 0.1
    gauss_noise:
      var_limit: (10.0, 20.0)
    horizontal_flip: true
    hue_saturation:
      hue_shift_limit: 20
      sat_shift_limit: 50
    rotate:
      limit: 45
      p: 0.5
    crop:
        width: 0.8
        height: 0.8
        p: 0.5`

**Comment by abelBEDOYA** [comment]
@Karin2413  As far as I know, you can launch a training from a cfg.yaml. It includes the typical arguments such as data, model, epoch, hyperparameters, ... Among them, you can find some of those augmentation hyperparameters (L81) that you are trying to set in your augmentation. This file is:

[cfg.yaml](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/cfg/default.yaml)

The CLI  would be:

`yolo segment train cfg=path/to/cfg.yaml`

Nevertheless, I'm still looking for some augmentations that you are listing in this post that don't show up in the cfg.yaml, such as brightness_contrast, brightness_limit, contrast_limit, gauss_noise, ... 

It would be great to find out how to carry out YOLOv8 training with these kinds of augmentation transforms facilitated by YOLOv8 itself without having to do it by ourselves.


Hope someone will answer us!

**Comment by glenn-jocher** [comment]
Hello @abelBEDOYA. Yes, you can use YAML files to configure YOLOv8 model for training along with augmentations. In your example YAML file, you have added `augmentations` section, which is the right approach as per your requirement.

In the `augmentations` section, you can add various augmentations like Albumentations, Mosaic, MixUp, etc., and set their hyperparameters accordingly. These augmentations will then be applied to the input images during the training process before they are fed to the model.

However, some augmentations like `brightness_contrast`, `brightness_limit`, `contrast_limit`, and `gauss_noise` are not currently supported in the YOLOv8 YAML file (version 19.11), as they were newly added in the YOLOv5 implementation. You can still use these augmentations, but you'll need to define them manually through code by using external libraries and then adding them to your transform pipeline before passing them to the YOLOv8 model.

I hope this explanation helps you. Please feel free to ask any further questions you may have.
