### ISSUE TITLE
Trackinig on custom weights outputs only detection results

### ISSUE THREAD

**Issue by lakyfarky** [ultralytics/ultralytics#3329]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Hi, I'm testing tracking performance with YOLOv8 and output from my custom weights contains no IDs while tracking with YOLOv8 pre-trained weights outputs ID with other tracks normally. Does .track support custom weights?

<img width="734" alt="image" src="https://github.com/ultralytics/ultralytics/assets/63816990/8e6536ac-3d5d-4345-b90a-afd206de0231">

<img width="716" alt="image" src="https://github.com/ultralytics/ultralytics/assets/63816990/7cdc4b15-840d-41f0-b042-80a2ca1e76e0">

### Environment

Yolo version 8.0.107
Python 3.9.13
CUDA: 11.8

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MrChains** [comment]
It does, I am tracking with custom weights with no issues at all. Is your model trained properly? you shold run 
```Python
from ultralytics import YOLO
model = YOLO("yourmodel.pt")
print(model.model.names)
```
in Python to see your model's class_id (you're missing a model)

**Comment by glenn-jocher** [comment]
@MrChains hi there,

It's great that you're exploring tracking performance with YOLOv8! Regarding your question, YOLOv8 does indeed support tracking with custom weights. To troubleshoot the issue you're facing, it's important to ensure that your model is trained correctly.

You can verify if your model is properly trained by running the following code in Python:

```Python
from ultralytics import YOLO

model = YOLO("yourmodel.pt")
print(model.model.names)
```

This code snippet will display the class IDs of your model. If you're not seeing any IDs, it suggests that there may be an issue with your model or the training process.

I hope this helps you in identifying the cause of the problem. Please feel free to provide more details or ask any further questions. We're here to assist you!

Best regards,
Glenn Jocher

**Comment by lakyfarky** [comment]
@MrChains , @glenn-jocher  Hi. 
I repeated the experiment and it works properly. Maybe runing model(frame) instead of model.predict(frame) cause problems with model.track() but Im not sure why I had problems yesterday. Thanks for your answer.

Br,
Luka Farkaš

**Comment by glenn-jocher** [comment]
@lakyfarky great, glad to hear it!
