### ISSUE TITLE
model.predict() not saving image when source is torch.Tensor

### ISSUE THREAD

**Issue by EricKeenan** [ultralytics/ultralytics#3332]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

No error message

### Minimal Reproducible Example

```python
import numpy as np
import torch
from ultralytics import YOLO

model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

image_tensor = torch.zeros(1, 3, 1024, 1024)    # torch tensor. This causes model.predict() to not save an image.
# image_tensor = np.zeros((1024, 1024, 3))    # numpy array. This causes model.predict() to save an image.

results = model.predict(source=image_tensor,
                        save=True,
                        save_txt=True,
                        project="test",
                        verbose=True)
```

### Additional

I would prefer to run `model.predict()` on torch tensors as opposed to numpy arrays. 

However, when setting the source to a torch tensor, no image is saved. Am I doing something wrong? Or is this a bug?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@EricKeenan thanks for the bug report! Yes I'm able to reproduce this, something seems wrong. I've added a TODO to queue for a fix.

**Comment by glenn-jocher** [comment]
@EricKeenan after investigating, this feature is disabled for torch inference:
https://github.com/ultralytics/ultralytics/blob/137552996a0aaeb90fa0c1d6da40f012f8801a00/ultralytics/yolo/engine/predictor.py#L258-L259

I've created a PR to add console output for torch inference and a warning explaining that save, save_txt and show features are not enabled for torch inference in https://github.com/ultralytics/ultralytics/pull/3361

If you'd like to help with a PR to introduce those that would be great. For now the warning should help explain to users that the features are missing.

**Comment by Neloy262** [comment]
@glenn-jocher  I would like to look into this issue

**Comment by glenn-jocher** [comment]
Hi @Neloy262, thanks for bringing this issue to our attention! 

After investigating, it seems that the `model.predict()` function in YOLOv8 does not save images when the source is a torch tensor. This feature is currently disabled for torch inference, but we have added a TODO to address this and provide a fix. 

In the meantime, a warning has been added to the code to inform users that the save, save_txt, and show features are not enabled for torch inference. 

If you would like to contribute to fixing this issue, feel free to submit a PR. We greatly appreciate your help!

Thanks again for reporting this and for your interest in YOLOv8!

**Comment by Neloy262** [comment]
@glenn-jocher does model.predict() have to support batched inputs?

**Comment by glenn-jocher** [comment]
@Neloy262 hi there! Thank you for your question about `model.predict()` in YOLOv8. I'm glad you reached out! 

Currently, the `model.predict()` function in YOLOv8 does not support batched inputs. It is designed to process one image or frame at a time. 

If you need to make predictions on multiple images or frames simultaneously, you can loop over your batch and call `model.predict()` for each input individually. This will allow you to process them one by one and get predictions for each input in the batch. 

I hope this clarifies things for you! Please let me know if you have any further questions or if there's anything else I can assist you with.
