### ISSUE TITLE
Validation speed in second or millisecond?

### ISSUE THREAD

**Issue by zhanglijun95** [ultralytics/ultralytics#3335]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I want to know the speed reported when calling val is in second or millisecond?
I found that in the code [here](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/engine/validator.py#L53C11-L53C11), it said in second. However, in the logging [here ](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/engine/validator.py#L188), it reports in millisecond. Which one is correct? Thank you!

**Comment by glenn-jocher** [comment]
@zhanglijun95 labelled as milliseconds indicates that the time is in milliseconds.
