### ISSUE TITLE
Is it possible to train a yolov8 or some other key-point detection model without bounding-boxes information

### ISSUE THREAD

**Issue by blackCmd** [ultralytics/ultralytics#3336]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

@glenn-jocher 
Hi, Is it possible to train a yolov8 or some other key-point detection model without bounding-boxes information, i.e. annotating only keypoints not the box-coordinates.

**Comment by glenn-jocher** [comment]
@blackCmd for Pose data format see https://docs.ultralytics.com/datasets/pose/
