### ISSUE TITLE
Error unable to find best.pt during training

### ISSUE THREAD

**Issue by Kang812** [ultralytics/ultralytics#334]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

yolo task=detect mode=train data=/workspace/apple_detection/dataset/coco128.yaml 

model=/workspace/apple_detection/model/yolov8n.pt epochs=20 imgsz=640 batch=8 device=\'0,1\'
Output exceeds the size limit. Open the full output data in a text editor
Ultralytics YOLOv8.0.5 🚀 Python-3.8.8 torch-1.8.2+cu111 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)
                                                         CUDA:1 (NVIDIA GeForce RTX 3090, 24268MiB)
yolo/engine/trainer: task=detect, mode=train, model=/workspace/apple_detection/model/yolov8n.pt, data=/workspace/apple_detection/dataset/coco128.yaml, epochs=20, patience=50, batch=8, imgsz=640, save=True, cache=False, device=0,1, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=False, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, retina_masks=False, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, hydra={'output_subdir': None, 'run': {'dir': '.'}}, v5loader=False, save_dir=runs/detect/train11
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.Conv                  [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.Conv                  [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.C2f                   [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.C2f                   [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.C2f                   [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.C2f                   [256, 256, 1, True]           
  9                  -1  1    164608  ultralytics.nn.modules.SPPF                  [256, 256, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]                           
 12                  -1  1    148224  ultralytics.nn.modules.C2f                   [384, 128, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]                           
 15                  -1  1     37248  ultralytics.nn.modules.C2f                   [192, 64, 1]                  
 16                  -1  1     36992  ultralytics.nn.modules.Conv                  [64, 64, 3, 2]                
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]                           
 18                  -1  1    123648  ultralytics.nn.modules.C2f                   [192, 128, 1]                 
...
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'runs/detect/train11/weights/best.pt'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace

### Environment

YOLO : YOLOv8 8.0.5 version
CUDA : 11.1 version
GPU : RTX 3090 
OS : ubuntu 18.04
python 3.8

### Minimal Reproducible Example

yolo task=detect mode=train data=/workspace/apple_detection/dataset/coco128.yaml 

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by ichsan2895** [comment]
How about this syntax?
```
yolo task=detect mode=train data=coco128.yaml model=yolov8m.pt
```

**Comment by Kang812** [comment]
The same error occurs for that syntax as well.

![image](https://user-images.githubusercontent.com/69283127/213060823-688afc65-3d47-478e-a374-cf95c95f5f1a.png)

When learning multi-gpu, I did the following.
![image](https://user-images.githubusercontent.com/69283127/213061203-82aa44de-bff1-4af9-b2d7-fd14c0877e75.png)

**Comment by Laughing-q** [comment]
@ichsan2895 @Kang812 guys, testing with the latest version, I don't see any errors:
```bash
yolo task=detect mode=train data=coco128.yaml model=weights/yolov8n.pt epochs=20 device=\'0,1\'
```
![image](https://user-images.githubusercontent.com/61612323/213065679-6aa7a2ac-77d4-42ac-b0d2-85012348fad7.png)

**Comment by kwbyun** [comment]
@Laughing-q thank you. However, in my case, the same problem occurs when using multi-gpu even after updating to the latest version. However, the error does not occur when using a single gpu.

**Comment by ichsan2895** [comment]
![image](https://user-images.githubusercontent.com/60387342/213092502-c85b9a78-e5f7-43db-99ac-14d0aab9964c.png)
Somehow I can't install newest yolov8 (v8.0.7) in colab (using `git clone` & `pip install -e .`)

But it ran successfull in previous yolov8 (v8.0.6)
![image](https://user-images.githubusercontent.com/60387342/213092768-a754b624-2f5e-4d32-9137-9f9f2d9ccd11.png)

Maybe new issue arise :(

**Comment by pderrenger** [comment]
@ichsan2895 i encountered a similar issue before, and it was resolved by reinstalling the 🐍 environment:
```bash
pip uninstall yolov8
pip install -U yolov8
```
Additionally, remember to restart the runtime to ensure the changes take effect.

**Comment by glenn-jocher** [comment]
@pderrenger it seems you're experiencing an issue with multi-GPU training where the `best.pt` file is not found. This could be due to a path resolution issue or a synchronization problem across GPUs. When using a single GPU, the error does not occur, which suggests the multi-GPU setup might be causing the problem.

Please ensure that your environment is set up correctly for multi-GPU training. You might want to verify that all necessary dependencies are up to date and that the GPUs are properly configured for parallel processing.

If the issue persists, consider submitting a detailed issue report on our GitHub page, including the full error log and the steps to reproduce the error. This will help us diagnose the problem more effectively. Meanwhile, you can continue using a single GPU if that setup is working without errors. Your contributions to improving YOLOv8 are appreciated! 🙌
