### ISSUE TITLE
How to use 'wandb' in yolov8?

### ISSUE THREAD

**Issue by anjaeju** [ultralytics/ultralytics#3340]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I try to use wandb to track several experiments based on yolov8; however, it is not well-written in the releses notes, codes, examples about using wandb.

How can it be possible to track the experiments with wandb with the following code snippet (which is official code for begineers from Ultralytics).
model = YOLO(args.model)
model.train(
    data=args.data,
    cfg=args.cfg,
    epochs=args.epochs,
    batch=args.batch,
    device=args.device,
    project=args.project,
    # WANDB ?? 
    )

**Comment by glenn-jocher** [comment]
@anjaeju hi there! If you want to use `wandb` to track your experiments with YOLOv8, you can do so by following these steps:

1. Install `wandb` by running `pip install wandb`.
2. Import the `wandb` library in your code.
3. Initialize `wandb` with your API key and project name. You can find your API key on the [wandb website](https://wandb.ai).
4. Add `wandb.init()` inside your `train()` function, before the training loop starts.
5. Inside the training loop, after each iteration, call `wandb.log()` to log any metrics or other relevant information.
6. Finally, call `wandb.finish()` after the training loop ends to finish the logging process.

Here's an example of how you can modify your code to incorporate `wandb`:

```python
import wandb

# Initialize wandb
wandb.init(project=args.project, api_key='YOUR_API_KEY')

# ...

model = YOLO(args.model)
model.train(
    data=args.data,
    cfg=args.cfg,
    epochs=args.epochs,
    batch=args.batch,
    device=args.device
)

# ...

def train():
    # wandb initialization
    wandb.init()
    
    # Training loop
    for epoch in range(args.epochs):
        # ...
        # Training code
        
        # Log metrics using wandb.log()
        wandb.log({"loss": loss})

    # Finish wandb logging
    wandb.finish()
```

Please note that you need to replace `'YOUR_API_KEY'` with your personal API key from the `wandb` website. This will allow `wandb` to keep track of your experiments and log the metrics associated with each run.

Let me know if you need further assistance!

**Comment by kalclark** [comment]
save_period=1 will track the metrics each epoch, default is -1 which is off until training is finished

https://docs.ultralytics.com/modes/train/#arguments

**Comment by anjaeju** [comment]
@kalclark  Super thanks. Now, errrthings are automatic

**Comment by glenn-jocher** [comment]
You're welcome, @anjaeju! I'm glad to hear that things are working smoothly for you. If you have any further questions or need assistance, feel free to reach out. Happy coding!
