### ISSUE TITLE
multiple class pose-estimation labeling format

### ISSUE THREAD

**Issue by bigsausage** [ultralytics/ultralytics#3356]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i was wondering how can i the train pose model when i have different object with different keypoints;
i have 2 class of object lets say **car** and **person**;
each **car** has 4 keypoints and **person** have 6 keypoints;
then i have 10 keypoints in total, so my **kpt_shape** param should be (10, 2) right?

and the question is the label file; **<px1> <py1> <px2> <py2> ... <pxn> <pyn>** is the **n** corresopond to the keypoints number 10?
so when i produce my **car** label row,  i have only 4 keypoints ,
do i need to set the other 6 keypoints with (0,0) to fullfill that each row have 1 + 4 + 10*2 
or i just set each row with 1+4 +4*2 is ok???

### Additional

i was wondering if it can handle the multiple class task...

also i want to know that if there is any paper i can refer to know better about the yolov8 pose-estimation 
or i  just have to go deep into the source code ?

**Comment by glenn-jocher** [comment]
@bigsausage hi there,

To train a YOLOv8 pose model with multiple classes and different keypoints per class, you need to consider a few things. First, for your case with 2 classes, "car" and "person," and a total of 10 keypoints, your `kpt_shape` parameter should indeed be (10, 2).

Regarding the label file format, the `<px1> <py1> <px2> <py2> ... <pxn> <pyn>` notation corresponds to the keypoints for a given object. In your case, when creating a label row for a "car," you only have 4 keypoints. You have two options:

1. Set the remaining 6 keypoints to (0, 0) to fulfill the requirement of each row having a total of 1 + 4 + 10 * 2 (objectness, bounding box, and keypoints).
2. Only set the keypoints that exist for the given object, resulting in a row with 1 + 4 + 4 * 2.

Both options are valid. The key is to ensure that the order of the keypoints is consistent across all objects and that the label format matches the model's expected input.

Regarding handling the multiple class task, YOLOv8 can handle multiple classes, including for pose estimation. You can train the model with different classes and keypoints by providing appropriate labels for each object in your dataset.

For a better understanding of YOLOv8 pose estimation, you can refer to the original YOLOv3 and YOLOv4 papers, as YOLOv8 builds upon their techniques. Additionally, going through the source code can help you gain a deep understanding of the YOLOv8 pose estimation implementation.

I hope this clarifies your questions. If you have any further inquiries, please don't hesitate to ask!

**Comment by bigsausage** [comment]
> @bigsausage hi there,
> 
> To train a YOLOv8 pose model with multiple classes and different keypoints per class, you need to consider a few things. First, for your case with 2 classes, "car" and "person," and a total of 10 keypoints, your `kpt_shape` parameter should indeed be (10, 2).
> 
> Regarding the label file format, the `<px1> <py1> <px2> <py2> ... <pxn> <pyn>` notation corresponds to the keypoints for a given object. In your case, when creating a label row for a "car," you only have 4 keypoints. You have two options:
> 
> 1. Set the remaining 6 keypoints to (0, 0) to fulfill the requirement of each row having a total of 1 + 4 + 10 * 2 (objectness, bounding box, and keypoints).
> 2. Only set the keypoints that exist for the given object, resulting in a row with 1 + 4 + 4 * 2.
> 
> Both options are valid. The key is to ensure that the order of the keypoints is consistent across all objects and that the label format matches the model's expected input.
> 
> Regarding handling the multiple class task, YOLOv8 can handle multiple classes, including for pose estimation. You can train the model with different classes and keypoints by providing appropriate labels for each object in your dataset.
> 
> For a better understanding of YOLOv8 pose estimation, you can refer to the original YOLOv3 and YOLOv4 papers, as YOLOv8 builds upon their techniques. Additionally, going through the source code can help you gain a deep understanding of the YOLOv8 pose estimation implementation.
> 
> I hope this clarifies your questions. If you have any further inquiries, please don't hesitate to ask!

thanks a lot !!

**Comment by glenn-jocher** [comment]
@bigsausage you're welcome! I'm glad I could help. Good luck with your YOLOv8 pose model training, and feel free to reach out if you have any further questions. Have a great day!

**Comment by blackCmd** [comment]
@glenn-jocher  Thank you for always providing the best answers, it has been helpful.
@bigsausage Also, I appreciate you addressing my concerns with clear questions.

Have a great day!

**Comment by glenn-jocher** [comment]
@blackCmd Thanks for reaching out! We're always here to help. If you have any further questions or concerns about YOLOv8, please don't hesitate to ask. We're committed to providing the best support possible to all our users. Have a great day!

**Comment by datpham270198** [comment]
I  have 3 class. But just  class1 has keypoints. I has annotated class1 with format cls1 x y w h kpt1x kpt1y kpt2x kpt2y and another class which dont have any keypoints with this format cls2 x y w h 0 0 0 0. The result i got with 2 keypoints for each class. Can you tell me method for training to get only keypoints for class i need. Many thanks!!!

**Comment by glenn-jocher** [comment]
@datpham270198 hi there! 👋

For training with keypoints only on specific classes, you can indeed follow the approach you've described. When a class doesn't have keypoints, setting those values to `0` (as you did with `cls2 x y w h 0 0 0 0`) is a common practice. However, ensure that your model and training configuration are correctly set up to interpret these zeros as "no keypoints" for those classes.

If you're still encountering issues, double-check your dataset and model configuration. It might also help to review the parsing logic in your dataset loader to ensure it correctly handles classes without keypoints.

Here's a quick snippet to illustrate handling keypoints in your dataset loader (assuming PyTorch):

```python
# Example for handling keypoints in dataset loader
if num_keypoints > 0:
    keypoints = [float(x) for x in line.split()[5:5+2*num_keypoints]]
else:
    keypoints = [0, 0] * expected_num_keypoints  # Adjust 'expected_num_keypoints' accordingly
```

This ensures that your model is trained with the correct understanding of which classes have keypoints and which do not. 

Hope this helps! Let us know if you have any more questions. 😊
