### ISSUE TITLE
Mss Screen grab not working says "does not exist"

### ISSUE THREAD

**Issue by LoveCoding-a** [ultralytics/ultralytics#336]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm wondering is this a bug or am missing some information from the documents.
I'm trying Yolov8 with screen capture but it doesn't seem to work.
Here my code
```
from ultralytics import YOLO
import mss
import numpy as np

screenshot = mss.mss()

model = YOLO('yolov8n.pt')  
monitor = {"top": 160, "left": 160, "width": 160, "height": 135}
frame = np.array(screenshot.grab(monitor))
results = model(frame)
```
I'm getting this error 

```
  ...
  [ 30  30  30 255]
  [ 30  30  30 255]
  [ 30  30  30 255]]] does not exist
```
Is there any way how to solve that?

**Comment by pderrenger** [comment]
@LoveCoding-a hey there! It looks like the issue might be related to the interactions between YOLOv8 and the mss screen capture library. 

Based on your code snippet, it seems you're attempting to pass a numpy array of a screenshot to the YOLOv8 `model` for inference. The error message "does not exist" could be indicating a problem with the input data or the format in which it's being passed to the model.

I'd recommend checking the input shape and data type of the `frame` before passing it to the YOLOv8 model. Also, ensure that the screen capture is functioning as expected outside of the YOLOv8 context.

If you have any more details about the error or any updates on your troubleshooting, feel free to share them. We'll do our best to help you out!
