### ISSUE TITLE
why is yolov8 always slower than yolov5 for inferencing ? 

### ISSUE THREAD

**Issue by HissaanAli** [ultralytics/ultralytics#3365]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I decided to shift to yolov8 after ultralytics mentioned that the new yolov8 model is better and faster than its successor yolov5 model but I found yolov8 inferencing speed slower than yolov5 (as opposed to the general view). I wanted to ask if I'm doing something wrong or is this just how it is supposed to be ?

I'm using yolov5s for both yolov5 and yolov8 and testing on the same image. 

## Yolov5
```python
from ultralytics import YOLO
import time, torch, cv2
# Load a model
yolov5_pt_model = torch.hub.load("ultralytics/yolov5", "yolov5s")

total_time = 0
img = cv2.imread('bus.jpg') # downloaded already from ultralytics github repo 
for i in range(100):
  
  start = time.time()
  results = yolov5_pt_model(img)  # yolov5 inferencing
  total_time += time.time()-start

print(total_time/100)
```
**Output: 0.36948140382766725**

## Yolov8
```python
from ultralytics import YOLO
import time, torch, cv2
# Load a model
model = YOLO("yolov8s.pt")

total_time = 0
img = cv2.imread('bus.jpg') # downloaded already from ultralytics github repo 
for i in range(100):
  
  start = time.time()
 
  results = model(img, verbose=False)  # yolov8 inferencing
  total_time += time.time()-start

print(total_time/100)
```
**Output: 0.5055585122108459**

**Device tested on: Colab CPU (without any hardware accelerator)**

### Note:
That's not just the case with `.pt` models, it is the same other formats as well (onnx, openvino), `yolov5` always outperforms `yolov8` in inferencing speed on cpu

@glenn-jocher could you please help me understand it. It is possible i may have the wrong impression or I must be doing something wrong.

**Comment by glenn-jocher** [comment]
@HissaanAli comparison speeds are available in our README for ONNX and TensorRT formats, i.e. see:

![image](https://github.com/ultralytics/ultralytics/assets/26833433/569149e1-c7e8-4db8-918e-3c62dcd44810)

**Comment by glenn-jocher** [comment]
For many sizes the v5 speeds may be slightly faster, though in general the v8 models are better placed to the top right of the speed vs mAP and params vs mAP charts.

**Comment by HissaanAli** [comment]
Could we reasonably infer that, in terms of processing speed, YOLOv8 generally does not surpass YOLOv5, but it does excel in achieving a superior accuracy-to-performance ratio?

**Comment by FrancescoSaverioZuppichini** [comment]
@glenn-jocher apologies in advance for the stupid question, is the benchmark code available?

**Comment by glenn-jocher** [comment]
```python
from ultralytics.yolo.utils.benchmarks import ProfileModels

ProfileModels(['yolov8n.pt', 'yolov8s.pt']).profile()
```
