### ISSUE TITLE
How to use augments in the inference stage of YOLOv8 segmentation?

### ISSUE THREAD

**Issue by bent1e** [ultralytics/ultralytics#3366]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to use augments in the inference stage of YOLOv8 segmentation?
I tried to modify augment=True during predict, but it didn't work.
WARNING ⚠️ SegmentationModel has not supported augment inference yet! Now using single-scale inference instead.

**Comment by pderrenger** [comment]
@bent1e you can't use augmentations during inference for YOLOv8 segmentation at the moment. When making predictions, the segmentation model does not support augmented inference, so it defaults to single-scale inference. This means that the model will only use the original, unaltered input during the inference process. If you need any further assistance, feel free to ask!
