### ISSUE TITLE
Getting "AttributeError: 'FreeTypeFont' object has no attribute 'getbbox'" while training in Google Colab

### ISSUE THREAD

**Issue by Balakishan77** [ultralytics/ultralytics#337]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

While training yolov8 with custom dataset, getting below error after running all epochs in the training process.

_Exception in thread Thread-101:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 250, in plot_images
    annotator.box_label(box, label, color=color)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 63, in box_label
    _, _, w, h = self.font.getbbox(label)  # text width, height
AttributeError: 'FreeTypeFont' object has no attribute 'getbbox'_

### Environment

Ultralytics YOLOv8.0.5 🚀 Python-3.8.16 torch-1.13.0+cu116 CUDA:0 (Tesla T4, 15110MiB)

### Minimal Reproducible Example

from ultralytics import YOLO

# Load a model
# model = YOLO("yolov8m.yaml")  # build a new model from scratch
model = YOLO("yolov8m.pt")  # load a pretrained model (recommended for training)

# Use the model
results = model.train(data="/content/drive/MyDrive/datasets/mask_dataset/face_mask_detection.yaml", epochs=25, imgsz=640)  # train the model

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ichsan2895** [comment]
Getting similar issue when I run a tutorial based from google colab
https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/train-yolov8-instance-segmentation-on-custom-dataset.ipynb

But, suprisingly, it works with my custom dataset in colab too
```
Ultralytics YOLOv8.0.4 🚀 Python-3.8.16 torch-1.13.0+cu116 CUDA:0 (Tesla T4, 15110MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 23.0/78.2 GB disk)
```

**Comment by Alimustoofaa** [comment]
I uninstall ultralytics and i try install from github solved
`!pip3 install git+https://github.com/ultralytics/ultralytics.git`

**Comment by pderrenger** [comment]
@Alimustoofaa it's great to hear that installing Ultralytics YOLOv8 from the GitHub repository solved the issue for you! The version from the GitHub repository may contain the fix for the error you encountered. It seems to be working well with your custom dataset in Google Colab now. If you have any further questions or need assistance with YOLOv8, feel free to ask!
