### ISSUE TITLE
ClearML item deletion issue

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/ultralytics#3370]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

@glenn-jocher @Laughing-q @AyushExel 
In ClearML, how to delete each experiment?
![image](https://github.com/ultralytics/ultralytics/assets/41098760/4cfb94d4-b678-46b8-a6fd-ddc455f978fa)

**Comment by glenn-jocher** [comment]
@thepycoder how can we delete each experiment as in the image above?
