### ISSUE TITLE
Training with imgsz=1280

### ISSUE THREAD

**Issue by Pedro-Leitek** [ultralytics/ultralytics#338]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

After reading the yolov8 documentation I realized that the img size of 1280 is not mentioned. I know that in yolov5 there are two groups of models, one for 640 and another for 1280 (the models end with 6). Is it possible to train the yolov8 models with img size of 1280?

Thanks

**Comment by Robotatron** [comment]
> we'll release the 1280 model soon

For detection only or segmentation as well? For the current segmentation models, would it make sense at all to train at higher resolution, e.g. 1280 or even 1600 or would it not have any benefits on the APs (even if trained from scratch?

**Comment by AyushExel** [comment]
1. Yes we might consider that
2. Yes you can try that but training time also increases with resolution so you need to be careful

**Comment by ahthserhsluk** [comment]
hey bro! just trying out things! 

if i have an image of size 1920*1080 in my dataset, what should be the imgsz?

**Comment by bit-scientist** [comment]
@AyushExel could you provide an approximate date for 1280 models release?

**Comment by bit-scientist** [comment]
> hey bro! just trying out things!
> 
> if i have an image of size 1920*1080 in my dataset, what should be the imgsz?

It should be `1920` and the rest will be handled automatically. Or if you do need to keep the sizes, use `rect` along with `imgsz`. Refer to [Docs](https://docs.ultralytics.com/tasks/detection/) for specific details

**Comment by 00ffcc** [comment]
> we'll release the 1280 model soon

When will yolov8n6.pt be released? 
By the way, I trained image of size 1280 with yolov8n.pt (imgsz=1280), it works but it runs very slow (about 600ms).
I want to search for a small design with stable size(16*16) and shape, could you please give me some suggestions about how to do it fast (maybe within 100ms)? I think this task is too simple to yolov8.

**Comment by glenn-jocher** [comment]
@carlos-leitek we appreciate your interest in the 1280 model of YOLOv8. While we're eager to bring this to you, we can't commit to an exact release date at this time. We understand how important this feature is for processing high-resolution images, and we want to ensure it meets Ultralytics' high standards of performance before releasing it. 

We frequently update our GitHub repo with the latest developments, so I would recommend you to keep an eye on repo updates for the most accurate information about the release. 

We sincerely appreciate your patience and understanding, and we're excited about the improvements YOLOv8 with the 1280 model will bring to your high-resolution image processing tasks.

**Comment by mikila85** [comment]
please 1280 is so needed since yolo5 you didnt release 1280, we need high accuracy which 1280 brings. 640 has alot of false positives.

**Comment by glenn-jocher** [comment]
We understand the need for high-resolution models and are working on it. Please stay tuned for updates on our GitHub repo. Thank you for your patience.

**Comment by mikila85** [comment]
I used yolov8x-pose-p6 it is 1280 and pose can extract box that I need and recognize person. For now it works. Same time 120ms as my yolov5 for same images

**Comment by glenn-jocher** [comment]
Glad to hear YOLOv8x-pose-p6 is working well for you! If you have any further questions or need assistance, feel free to ask.

**Comment by andwaal-esmart** [comment]
Great to see that this is being worked on, hopefully it will land soon!

A question you might help out with @glenn-jocher; 
How much does the size of the images used for training the original checkpoint 640 vs 1280, have to say for the performance of a custom model trained on it? 

We are currently using yolo5x6.pt as starting point for most of our models, training with imgsz=1280. 
In our tests it seem that YoloV5 (yolo5x6.pt) trained at 1280 outperforms Yolo11 (yolo11x.pt) trained at 1280 (_we are often looking for small, complex objects, and larger image size have shown to almost always give better result, so to train at 640 is most likely not an option_). 
This is currently our reason for not migrating from yolo5->11.

**Comment by glenn-jocher** [comment]
The image size used for training can significantly impact model performance, especially for detecting small, complex objects. Training at a higher resolution like 1280 often improves results for such tasks. If YOLOv5x6 is outperforming YOLO11 for your specific needs, it might be due to the model architecture or training specifics. Continuing with the model that best suits your requirements is a sound approach. Keep an eye on updates for potential improvements in YOLO11.
