### ISSUE TITLE
download weights

### ISSUE THREAD

**Issue by ChenJian7578** [ultralytics/ultralytics#3385]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

when i use yolov8s.yaml for train myself dataset,  it will download the yolov8n.pt weights,   why?    is there have any effect to my training?

### Additional

nothing

**Comment by glenn-jocher** [comment]
@ChenJian7578 we use YOLOv8n to verify that AMP is working correctly on a known model. YOLOv8n does not do anything with your training, it's only purpose in AMP verification.
