### ISSUE TITLE
 Automatic fix for "libpng warning: iCCP: known incorrect sRGB profile"

### ISSUE THREAD

**Issue by Robotatron** [ultralytics/ultralytics#339]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

During training the following warning is constantly shown: `libpng warning: iCCP: known incorrect sRGB profile`

Upon investigation the suggested answer on stackoverflow seems to be to use a third-party image editing tool such as imagemagick to fix the profile.

The feature request is for YOLO to automatically fixing such PNGs with incorrect sRGB profiles or to ignore the warning by default.

```
 8/99      38.9G    0.03909    0.04623    0.04188    0.01602        382        608:  45%|████▌     | 1323/2938 [19:44<23:34,  1.14it/s]
libpng warning: iCCP: known incorrect sRGB profile
       8/99      38.9G    0.03912     0.0463    0.04185    0.01607        359        608:  55%|█████▍    | 1609/2938 [23:59<19:36,  1.13it/s]
libpng warning: iCCP: known incorrect sRGB profile
       8/99      38.9G    0.03917    0.04634    0.04184    0.01611        403        608:  66%|██████▌   | 1926/2938 [28:41<15:06,  1.12it/s]
libpng warning: iCCP: known incorrect sRGB profile
       8/99      38.9G    0.03916    0.04634    0.04188    0.01609        409        608:  74%|███████▎  | 2165/2938 [32:15<11:33,  1.11it/s]libpng warning: iCCP: known incorrect sRGB profile
       8/99      38.9G    0.03915    0.04637    0.04191     0.0161        436        608:  85%|████████▍ | 2488/2938 [37:04<06:34,  1.14it/s]libpng warning: iCCP: known incorrect sRGB profile
       8/99      38.9G    0.03915    0.04635    0.04191    0.01609        353        608:  92%|█████████▏| 2695/2938 [40:07<03:34,  1.13it/s]
```

### Use case

Cleaner console log, better user experience

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@Robotatron thanks for reporting but this seems like a system-specific issue as its not reproducible for me

**Comment by Robotatron** [comment]
> @Robotatron thanks for reporting but this seems like a system-specific issue as its not reproducible for me

I will see if I can pinpoint the PNG files causing this and share it with you. For me it seems to be an image related issue and how it is read by `libpng` that YOLO code base is using.
Closing for now.

**Comment by sunmooncode** [comment]
@Robotatron Did you solve it? I have the same problem.

**Comment by glenn-jocher** [comment]
@sunmooncode hello! I'd recommend trying to isolate which PNG images are causing this issue on your system. It's possible that the problem comes from specific PNG files with incorrect sRGB profiles. In such cases, you could use a third-party image editing tool like ImageMagick to correct the sRGB profile. However, without knowing the exact files causing the error, it's hard to provide an accurate solution.

Please check your dataset and confirm if the issue arises due to specific image files. You might spot a pattern that can help in solving the problem. Searching for the specific warning message may help you narrow down which images are causing the problem.

If you can isolate the problematic files and resolve their issues, the warnings should stop. Remember, these warnings likely won't interrupt your training process, but cleaning them up may help clear any confusion they're causing. Let me know how it goes.

**Comment by sunmooncode** [comment]
@glenn-jocher 感谢您的回复。我正在训练一个大的数据集(25w左右)，但是数据中大部分的数据都会有这个问题并且我已经在训练了，我想着如何能暂时忽略这个警告。
![image](https://github.com/ultralytics/ultralytics/assets/86471590/a59a9856-e28f-4e76-b034-c18ecafe2d1c)

**Comment by sunmooncode** [comment]
@thanhnt-cf This is my way of handling it.
```
def detele_iccfile(image_path):
    img = Image.open(image_path)
    img.info.pop('icc_profile', None)
    img.save(image_path)
```

**Comment by glenn-jocher** [comment]
@sunmooncode Thank you for sharing your solution. By opening the image with Python's Imaging Library (PIL) and removing the 'icc_profile' information, you prevent the libpng warning. This is a good workaround for images with incorrect sRGB profiles.

However, please be aware that modifying the original images in your dataset by removing the ICC profile might affect the quality or appearance of these images, as the ICC profile is used to ensure the correct color representation of the images. Therefore, use this method cautiously, and make sure it doesn't have unintended effects on your dataset.

It's also worth noting that while this warning can be annoying, it doesn't directly impact the training of the YOLOv8 model.

Regardless, I'm glad you've found a solution that works for you, and appreciate you sharing it with the community.

**Comment by BaranBaygin2** [comment]
I don't know if it still helps, but I changed the format from PNG to JPG, and the warning went away. Guess YOLO has some issues with PNGs?

**Comment by l-33ter** [comment]
Same issue here - I DL some 'random' pictures from [Webb](https://webbtelescope.org/contents/news-releases/2024/news-2024-105#section-id-2) and basically every picture has this 'error' when I transform it to *.webp*.

I tried some few additional options but every time the same 'error':

`for b in *.png; do cwebp -q 100  $b -o `basename ${b%.png}`.webp; done` --> 

`
libpng warning: iCCP: known incorrect sRGB profile
Saving file 'ring-nebula_NIR_webb.webp'
File:      ring-nebula_NIR_webb.png
Dimension: 4097 x 4156
Output:    5904492 bytes Y-U-V-All-PSNR 51.61 51.85 51.62   51.65 dB
           (2.77 bpp)
block count:  intra4:      59927  (89.68%)
              intra16:      6893  (10.32%)
              skipped:         0  (0.00%)
bytes used:  header:           1031  (0.0%)
             mode-partition: 317026  (5.4%)
 Residuals bytes  |segment 1|segment 2|segment 3|segment 4|  total
    macroblocks:  |     100%|       0%|       0%|       0%|   66820
      quantizer:  |       0 |       0 |       0 |       0 |
   filter level:  |       0 |       0 |       0 |       0 |
   `
   But it's actually not bad, I can open/interact with the *.webp* like normal? :D

**Comment by glenn-jocher** [comment]
The warning is related to the PNG's sRGB profile and doesn't affect functionality. Converting to JPG before transforming to WEBP might help. If the images work fine otherwise, you can safely ignore the warning.

**Comment by cdrouin** [comment]
An option to suppress the warnings would be nice. It makes the diagnostics during the training process completely unreadable.

**Comment by glenn-jocher** [comment]
@cdrouin That's a fair point. These warnings can indeed clutter the console output during training. While they don't affect functionality, they can make it difficult to spot other important messages. I've noted your suggestion to add an option for suppressing these libpng warnings.

In the meantime, you can redirect stderr to filter out these specific warnings using Python. For example:

```python
import os
import sys
import subprocess

# Redirect stderr to a file and filter out libpng warnings
with open('stderr.txt', 'w') as stderr_file:
    original_stderr = sys.stderr
    sys.stderr = stderr_file
    
    # Run your YOLO training here
    
    # Restore stderr
    sys.stderr = original_stderr
```

You can find more troubleshooting tips in our [common issues guide](https://docs.ultralytics.com/guides/yolo-common-issues/). If you have any additional questions, feel free to ask.
