### ISSUE TITLE
palm and fingers keypoints - pose estimation

### ISSUE THREAD

**Issue by swe-cognitica** [ultralytics/ultralytics#3391]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The keypoint is till wrist only. I want to detect existing kepoints and additionally have fingers or end of arm as part of it. Will it be added in future? What are the possible ways to detect entire arm?

**Comment by glenn-jocher** [comment]
@swe-cognitica hello,

Currently, YOLOv8 supports pose estimation up to the wrist only. It doesn't specifically support detecting the fingers or the end of the arm as part of it. However, there are some possible options to detect the entire arm. One way would be to use a different model that specifically supports detecting the entire arm, like OpenPose or DensePose. Another option would be to train a custom model using a dataset that includes images with full arms visible, and then fine-tune it on that dataset. Please let me know if you have any further questions.

**Comment by swe-cognitica** [comment]
@glenn-jocher  Thank you. I will try that. 
Is there any plan on including fingers and palm as part of the model?

**Comment by glenn-jocher** [comment]
@swe-cognitica you're welcome! Currently, YOLOv8 doesn't specifically support detecting fingers and palm as part of the pose estimation model. However, there are some possible ways to detect them, such as using a different model or training a custom model on a dataset with images that include fingers and palm. At the moment, there are no specific plans to include fingers and palm in the model, but the model is open source, so anyone can contribute to it and add new features.

**Comment by swe-cognitica** [comment]
Okay Thank you!
