### ISSUE TITLE
Broken invitation link to Discord

### ISSUE THREAD

**Issue by pktiuk** [ultralytics/ultralytics#3394]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Discord Invitation link you use in your issue creation list is invalid
![image](https://github.com/ultralytics/ultralytics/assets/45544416/e420ca6a-87c4-47de-88cf-2906f0dab981)

I get: 

![image](https://github.com/ultralytics/ultralytics/assets/45544416/d0b1375c-aa27-40da-84e8-f46f9cba1f7c)

Discord docs: https://support.discord.com/hc/en-us/articles/360001556852-Invalid-Invite-Links

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@pktiuk thanks, yes you're right, the link appears broken! I will fix it. Please use this new link in the meantime: 

https://discord.gg/6Yy6tKnx
