### ISSUE TITLE
YOLO can't open/read file 

### ISSUE THREAD

**Issue by bibolil** [ultralytics/ultralytics#3398]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

train: Scanning /mnt/c/Users/bilel/help/object_detection_project/dataset/l
Traceback (most recent call last):
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/data/base.py", line 104, in get_img_files
    if p.is_dir():  # dir
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/pathlib.py", line 1305, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
OSError: [Errno 5] Input/output error: '/mnt/c/Users/bilel/helps/object_detection_project/dataset/images/validation'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bibolil/miniconda3/envs/tf/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/cfg/__init__.py", line 405, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 373, in train
    self.trainer.train()
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 276, in _do_train
    self._setup_train(world_size)
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 242, in _setup_train
    self.test_loader = self.get_dataloader(self.testset, batch_size=batch_size * 2, rank=-1, mode='val')
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/v8/detect/train.py", line 54, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode, batch_size)
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/v8/detect/train.py", line 28, in build_dataset
    return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == 'val', stride=gs)
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/data/build.py", line 74, in build_yolo_dataset
    return YOLODataset(
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/data/dataset.py", line 39, in __init__
[ WARN:0@11.727] global loadsave.cpp:244 findDecoder imread_('/mnt/c/Users/bilel/helps/object_detection_project/dataset/images/train/boat503.png'): can't open/read file: check file path/integrity
    super().__init__(*args, **kwargs)
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/data/base.py", line 71, in __init__
    self.im_files = self.get_img_files(self.img_path)
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/data/base.py", line 119, in get_img_files
    raise FileNotFoundError(f'{self.prefix}Error loading data from {img_path}\n{HELP_URL}') from e
FileNotFoundError: val: Error loading data from /mnt/c/Users/bilel/help/object_detection_project/dataset/images/validation
See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

### Environment

Ultralytics YOLOv8.0.123  Python-3.10.11 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
WSL2

### Minimal Reproducible Example

!yolo task=detect mode=train model=yolov8s.pt data=dataset.yaml epochs=100 imgsz=512

### Additional

trying to train yolo on local machine.

dataset.yaml 
path: dataset
train: images/train
val: images/validation
test: images/test

Classes
names:
    0: boat

import os
from pathlib import Path
print(os.path.exists('/mnt/c/Users/bilel/help/object_detection_project/dataset/images/train/boat503.png'))
True

when I run this code in a cell it finds the path, but while training YOLO it shows an error failing to read that path

Folders tree:
object_detection_project 
--------dataset
            -------------images ----(train,validation,test)
            -------------labels ----(train,validation,test)
--------yolo_v8.ipynb

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@bibolil there is probably an issue with your dataset paths. You can use coco8.yaml as an example for how to construct a dataset, i.e. run this example code to see:

`yolo train model=yolov8n.pt data=coco8.yaml`

**Comment by bibolil** [comment]
@glenn-jocher  trained yolo on the same dataset on colab and it didn't shows up with this isssue,
here's an example of the dataset imgs and labels:
![image_2023-06-26_203330353](https://github.com/ultralytics/ultralytics/assets/80677927/75bebd9a-faa4-4770-9b6d-98fb16dc10b8)
![image_2023-06-26_203414930](https://github.com/ultralytics/ultralytics/assets/80677927/f7a1fdab-f9fa-48e1-9dac-862dd7453b7c)
![image_2023-06-26_203543390](https://github.com/ultralytics/ultralytics/assets/80677927/0b182eb3-2f96-4450-9599-642bd5c84f36)

**Comment by bibolil** [comment]
I also get a similar issue with 
yolo task=detect mode=train model=yolov8s.pt data=coco8.yaml epochs=100 imgsz=640
dataset got downloaded and formatted in YOLO input format

cell output 

/bin/bash: /home/bibolil/miniconda3/envs/tf/lib/libtinfo.so.6: no version information available (required by /bin/bash)
Ultralytics YOLOv8.0.123 🚀 Python-3.10.11 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
yolo/engine/trainer: task=detect, mode=train, model=yolov8s.pt, data=coco8.yaml, epochs=100, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs/detect/train10

Dataset 'coco8.yaml' images not found ⚠️, missing paths ['/mnt/c/Users/bilel/Phelps2020/datasets/coco8/images/val']
Downloading https://ultralytics.com/assets/coco8.zip to /mnt/c/Users/bilel/Phelps2020/object_detection_project/coco8.zip...
100%|████████████████████████████████████████| 433k/433k [00:00<00:00, 1.08MB/s]
Unzipping /mnt/c/Users/bilel/Phelps2020/object_detection_project/coco8.zip to /mnt/c/Users/bilel/Phelps2020/object_detection_project...
Dataset download success ✅ (2.5s), saved to /mnt/c/Users/bilel/Phelps2020/object_detection_project


                   from  n    params  module                                       arguments                     
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]                 
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]             
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]           
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]              
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]           
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]                 
 22        [15, 18, 21]  1   2147008  ultralytics.nn.modules.head.Detect           [80, [128, 256, 512]]         
Model summary: 225 layers, 11166560 parameters, 11166544 gradients

Transferred 355/355 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs/detect/train10', view at http://localhost:6006/
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
Traceback (most recent call last):
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/data/base.py", line 114, in get_img_files
    raise FileNotFoundError(f'{self.prefix}{p} does not exist')
FileNotFoundError: train: /mnt/c/Users/bilel/Phelps2020/datasets/coco8/images/train does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bibolil/miniconda3/envs/tf/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/cfg/__init__.py", line 405, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 373, in train
    self.trainer.train()
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 276, in _do_train
    self._setup_train(world_size)
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 240, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/v8/detect/train.py", line 54, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode, batch_size)
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/v8/detect/train.py", line 28, in build_dataset
    return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == 'val', stride=gs)
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/data/build.py", line 74, in build_yolo_dataset
    return YOLODataset(
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/data/dataset.py", line 39, in __init__
    super().__init__(*args, **kwargs)
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/data/base.py", line 71, in __init__
    self.im_files = self.get_img_files(self.img_path)
  File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/ultralytics/yolo/data/base.py", line 119, in get_img_files
    raise FileNotFoundError(f'{self.prefix}Error loading data from {img_path}\n{HELP_URL}') from e
FileNotFoundError: train: Error loading data from /mnt/c/Users/bilel/Phelps2020/datasets/coco8/images/train
See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

**Comment by Burhan-Q** [comment]
Your screenshot shows you're using Windows OS, but the file path that's causing an error is not in a Windows path format

'/mnt/c/Users/bilel/helps/object_detection_project/dataset/images/validation'` 

which is where your issue is stemming from. If you ran this in Colab, I'm guessing (I don't use notebooks personally) that you can't run the exact notebook used locally, you'll have to rewrite the notebook locally. 

This error is where you should try to trace down your issue. Also it might be good to share your YAML file, as I suspect that the 'path' value is where the issue might stem from.

`File "/home/bibolil/miniconda3/envs/tf/lib/python3.10/pathlib.py", line 1097, in stat
return self._accessor.stat(self, follow_symlinks=follow_symlinks)

OSError: [Errno 5] Input/output error: '/mnt/c/Users/bilel/helps/object_detection_project/dataset/images/validation'`

**Comment by Burhan-Q** [comment]
Okay, that makes sense, I wasn't sure if WSL was being used or not since I didn't see mention of it (but I could've missed that).

What do you get if you run `os.environ` in your notebook?

**Comment by Burhan-Q** [comment]
Also wondering if there could be a permissioning issue between WSL Linux and the Windows directory. Haven't tried running training via WSL myself, so not sure what the access needs would be.

**Comment by bibolil** [comment]
@Burhan-Q  
This is what I get running os.environ
environ({'SHELL': '/bin/bash', 'WSL2_GUI_APPS_ENABLED': '1', 'CONDA_EXE': '/home/bibolil/miniconda3/bin/conda', '_CE_M': '', 'WSL_DISTRO_NAME': 'Ubuntu', 'NAME': 'BiboLap', 'PWD': '/mnt/c/Users/bilel/Phelps2020', 'LOGNAME': 'bibolil', 'CONDA_PREFIX': '/home/bibolil/miniconda3/envs/tf', 'MOTD_SHOWN': 'update-motd', 'HOME': '/home/bibolil', 'LANG': 'C.UTF-8', 'WSL_INTEROP': '/run/WSL/1799_interop', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'WAYLAND_DISPLAY': 'wayland-0', 'CONDA_PROMPT_MODIFIER': '(tf) ', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'TERM': 'xterm-color', '_CE_CONDA': '', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'USER': 'bibolil', 'CONDA_SHLVL': '2', 'DISPLAY': ':0', 'SHLVL': '1', 'CONDA_PYTHON_EXE': '/home/bibolil/miniconda3/bin/python', 'LD_LIBRARY_PATH': ':/home/bibolil/miniconda3/envs/tf/lib/:/home/bibolil/miniconda3/envs/tf/lib/python3.10/site-packages/nvidia/cudnn/lib', 'XDG_RUNTIME_DIR': '/run/user/1000/', 'CONDA_DEFAULT_ENV': 'tf', 'WSLENV': '', 'XDG_DATA_DIRS': '/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'PATH': '/home/bibolil/miniconda3/envs/tf/bin:/home/bibolil/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/System32/Wbem:/mnt/c/windows/System32/WindowsPowerShell/v1.0:/mnt/c/windows/System32/OpenSSH:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/System32/OpenSSH:/mnt/c/Users/bilel/AppData/Local/Microsoft/WindowsApps:/snap/bin', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'HOSTTYPE': 'x86_64', 'CONDA_PREFIX_1': '/home/bibolil/miniconda3', 'PULSE_SERVER': 'unix:/mnt/wslg/PulseServer', 'OLDPWD': '/mnt/c/Users/bilel', '_': '/home/bibolil/miniconda3/envs/tf/bin/jupyter', 'PYDEVD_USE_FRAME_EVAL': 'NO', 'JPY_PARENT_PID': '4014', 'CLICOLOR': '1', 'FORCE_COLOR': '1', 'CLICOLOR_FORCE': '1', 'PAGER': 'cat', 'GIT_PAGER': 'cat', 'MPLBACKEND': 'module://matplotlib_inline.backend_inline'})

**Comment by bibolil** [comment]
@Burhan-Q  Redownloading the dataset in the env and reprocessing it solved the issue about locating the dataset images and labels. But ended up facing a new issue the training start running epochs and it either kills the kernel or ends up the training without advancing .
![image_2023-06-27_133541027](https://github.com/ultralytics/ultralytics/assets/80677927/0a8a498f-355c-4cdb-9193-39d6de876670)

**Comment by glenn-jocher** [comment]
@bibolil hi there!

It's great to hear that you were able to solve the issue with locating your dataset images and labels. 

For the new issue you are encountering where training doesn't advance even though you're not receiving any visible errors, it sounds like the training process may be running out of memory resources and gets killed or stuck. 

One way to investigate this issue is to look into the hardware resources allocated to your environment while you're running the training process. This will help determine what might be causing the issue.

Another possible solution is to reduce the batch size or image size in your configuration file. You can also try splitting the dataset into smaller subsets and train on each subset separately. 

If this issue persists, please provide us with more information, such as your environment configuration and hardware specifications, so we can help you better.

**Comment by bibolil** [comment]
yolo v8 default batch size is set to 64, setting it to 32 made it work.
Thank you @glenn-jocher  @Burhan-Q

**Comment by glenn-jocher** [comment]
@bibolil you're welcome! Glad to hear the issue has been resolved. YOLOv8's default batch size is set to 64, but it is possible that lower-end systems can run into memory constraints with this batch size, resulting in the training process getting stuck. Reducing the batch size to 32 (or a lower value as needed) can free up memory resources and resolve the issue. If you encounter any further issues, don't hesitate to reach out.
