### ISSUE TITLE
Add documentation w.r.t. training regime for YOLO segmentation on COCO

### ISSUE THREAD

**Issue by Robotatron** [ultralytics/ultralytics#340]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

E.g. what augmentations did you use and all other relevant hyperpara (image size etc) for the models you are publishing such as 
[YOLOv8x](https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8x-seg.pt) etc.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Thanks for the feedback. Yes, we're rapidly making updates to code and docs and we'll continue to do so in coming days
