### ISSUE TITLE
Can we use torchvision's transforms with the existing albumentations transforms?

### ISSUE THREAD

**Issue by chokevin8** [ultralytics/ultralytics#3400]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, so I've been trying to customize the specific transforms in the yolov8 training, and I've successfully edited the transforms by editing the augment.py file with the albumentation transforms that I wanted. However, there is some more transforms that I want to do, and it is a combination of existing transformations in torchvision and a custom transformation that only seems to work in the torchvision transforms pipeline. When I test this torchvision transformation only separately, it works, but I don't know how to implement this with the albumentation transforms in the yolov8 pipeline. 

Do I need to specifically write a python class like Albumentations, RandomHSV and RandomFlip in the augment.py and then include it to the Compose pipeline, which is returned in the v8_transforms method in [here](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/data/augment.py#L762C11-L762C11)? Some detailed guidances would be appreciated, thanks!

**Comment by glenn-jocher** [comment]
@chokevin8 hi! Yes, you can use both torchvision and albumentations transforms together in the YOLOv8 pipeline. To implement this, you will need to create a custom transformation class that combines both the torchvision and albumentations transforms. You can then add this custom class to the Compose pipeline returned in the v8_transforms method. 

To create the custom class, you can use the torchvision.transforms.Lambda transform to apply a Python function that takes an input image and applies the necessary transforms using the albumentations library. You can then add other torchvision transforms to this class to further modify the input image. 

Once you have created the custom class, you can add it to the Compose pipeline by instantiating it and passing it to the transforms.Compose() function along with the other transforms. 

Hope this helps! Let us know if you have any further questions.

**Comment by chokevin8** [comment]
@glenn-jocher So, my custom torchvision transforms method is a bit more complicated to just use the lambda function, but I was successful in creating a class. However, I haven't been successful in training it, as it returns an error on the "labels" object, it expects it to be a dictionary, but somehow adding my custom torchvision transforms class ruins it- if I remove my custom class, it works fine again. It most likely is a mistake in my part, but could it be because of the differences of how dataloaders work in albumentations vs torchvisions? I've used both before and the method they work is slightly different. My v8_transforms method returns:
   return Compose([
        pre_transform,
        MixUp(dataset, pre_transform=pre_transform, p=hyp.mixup),
        Albumentations(p=1.0),
        MyCustomClass(
            std_hyper=-0.3,
            probability=0.8,
            distribution="normal",
            is_train=True,
            yaml_file= "\randstainnayaml"),
        RandomHSV(hgain=hyp.hsv_h, sgain=hyp.hsv_s, vgain=hyp.hsv_v), 
        RandomFlip(direction='vertical', p=hyp.flipud),
        RandomFlip(direction='horizontal', p=hyp.fliplr, flip_idx=flip_idx)])

MyCustomClass is my class, and no matter how I change the order (before albumentations, after albumentations, etc) I can't get it to work yet. Any suggestions?

**Comment by chokevin8** [comment]
@glenn-jocher for more information, below is the full error traceback (happens when starting the training for the first epoch):
Starting training for 300 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/344 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\hubmap\yolov8\train_yolov8.py", line 66, in <module>
    model_seg.train(data=r'C:\Users\Kevin\PycharmProjects\hubmap\yolov8\yolov8_v4_data.yaml'
  File "C:\Users\Kevin\.conda\envs\hubmap\lib\site-packages\ultralytics\yolo\engine\model.py", line 371, in train
    self.trainer.train()
  File "C:\Users\Kevin\.conda\envs\hubmap\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 192, in train
    self._do_train(world_size)
  File "C:\Users\Kevin\.conda\envs\hubmap\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 313, in _do_train
    for i, batch in pbar:
  File "C:\Users\Kevin\.conda\envs\hubmap\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\Users\Kevin\.conda\envs\hubmap\lib\site-packages\ultralytics\yolo\data\build.py", line 38, in __iter__
    yield next(self.iterator)
  File "C:\Users\Kevin\.conda\envs\hubmap\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "C:\Users\Kevin\.conda\envs\hubmap\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "C:\Users\Kevin\.conda\envs\hubmap\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "C:\Users\Kevin\.conda\envs\hubmap\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\Kevin\.conda\envs\hubmap\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\Kevin\.conda\envs\hubmap\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Kevin\.conda\envs\hubmap\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Kevin\.conda\envs\hubmap\lib\site-packages\ultralytics\yolo\data\base.py", line 239, in __getitem__
    return self.transforms(self.get_image_and_label(index))
  File "C:\Users\Kevin\.conda\envs\hubmap\lib\site-packages\ultralytics\yolo\data\augment.py", line 57, in __call__
    data = t(data)
  File "C:\Users\Kevin\.conda\envs\hubmap\lib\site-packages\ultralytics\yolo\data\augment.py", line 517, in __call__
    img = labels['img']
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by glenn-jocher** [comment]
@chokevin8 It seems that the error is caused by the line `img = labels['img']` in your custom torchvision transforms class. The error message indicates that `labels` is expected to be a dictionary, and indexing it with the key `'img'` is causing an `IndexError`.

To resolve this issue, you need to ensure that the `labels` object passed to your custom class is indeed a dictionary and contains the key `'img'`. It's possible that the `labels` object is not formatted as expected, causing the error.

I would recommend checking the structure and format of your `labels` object before passing it to the custom class. Ensure that it is a dictionary and contains the necessary key-value pairs that your custom class expects. You can use print statements or debugging tools to inspect the `labels` object and verify its structure.

If the issue persists, please provide more information about the structure and contents of your `labels` object, as well as the code for your custom class, so that we can further assist you in resolving the error.

Let me know if you have any further questions or need additional clarification.
