### ISSUE TITLE
Can augmented images used in test and validation dataset

### ISSUE THREAD

**Issue by cheeyin9394** [ultralytics/ultralytics#3402]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

1. Can augmented images used in test and validation dataset?
2. How to retrieve graph output with all classes labelled? Ultralytics version is 8.0.123. Currently all classes are in grey color and classes are not labelled.
<img width="521" alt="image" src="https://github.com/ultralytics/ultralytics/assets/133017595/7074c38d-740c-4669-9095-6760c4fb87c4">

**Comment by glenn-jocher** [comment]
@cheeyin9394 hello,

Yes, augmented images can be used in both the test and validation datasets. They can help improve the accuracy of the model as well as increase the diversity of the data.

To retrieve the graph output with all classes labeled, you can use the visualize command with the `--labels` flag set to true. This will display the class labels next to the bounding boxes in the output image. If the labels are still not showing up, please make sure that your class labels input file is in the correct format and is being loaded correctly.

Let me know if you have any further questions or issues.

Best, 
Glenn

**Comment by cheeyin9394** [comment]
Thanks @glenn-jocher 
I can see the class labelled next to the bounding boxes in the output image.
But I could not see the class labelled on output graph.

Besides that, may I know what are the key differences between YOLOv8n vs YOLOv8m?

**Comment by glenn-jocher** [comment]
Hi @cheeyin9394,

Glad to hear that you were able to show the class labels on the output graph by modifying the `metrics.py` file.

Regarding the key differences between YOLOv8n and YOLOv8m, I'm assuming you are referring to different variations of the YOLOv8 architecture.

In the context of the Ultralytics YOLOv8 repository, there is no specific YOLOv8n or YOLOv8m. The repository focuses on the implementation and maintenance of the YOLOv8 architecture, which is a single unified version.

If you have seen references to YOLOv8n and YOLOv8m in other contexts or repositories, they may be specific variations or modifications of the YOLOv8 architecture made by other authors or contributors. It would be best to refer to the specific documentation or discussions related to those variations for more detailed information about their differences.

Let me know if there's anything else I can help with.

Best,
Glenn

**Comment by cheeyin9394** [comment]
Hi @glenn-jocher,

I mean YOLOv8n and YOLOv8m in picture below that taken from https://github.com/ultralytics/ultralytics

![image](https://github.com/ultralytics/ultralytics/assets/133017595/876f2bd4-d13f-4b69-99e1-02e43b0b3f16)

**Comment by glenn-jocher** [comment]
Hi @cheeyin9394,

Thank you for reaching out. I apologize for any confusion caused earlier.

In the picture you provided from the Ultralytics YOLOv8 repository, the labels "YOLOv8n" and "YOLOv8m" refer to different model sizes or variations of the YOLOv8 architecture.

- YOLOv8n: This refers to a lightweight version of the YOLOv8 model, designed for faster inference with reduced computational requirements. It may have fewer parameters and a smaller model size compared to the standard YOLOv8 model.

- YOLOv8m: This refers to a medium-sized version of the YOLOv8 model, designed to strike a balance between model size and performance. It may have a moderate number of parameters and a reasonable model size compared to other variations.

These variations allow users to choose a model size that suits their specific requirements in terms of performance, inference speed, and resource constraints.

Please note that these variations are specific to the Ultralytics YOLOv8 repository and may not be standard across other implementations or versions of YOLO.

Let me know if you have any further questions or require additional clarification.

Best regards,
Glenn
