### ISSUE TITLE
RT-DETR : onnx conversion with dynamic batch size problem

### ISSUE THREAD

**Issue by younesslanda** [ultralytics/ultralytics#3403]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

```
from ultralytics import RTDETR
import torch
import numpy as np
import onnxruntime

def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

model = RTDETR("rtdetr-x.pt")
model.export(format='onnx', dynamic=True)

ort_session = onnxruntime.InferenceSession("rtdetr-x.onnx")
batch_size = 2
x = torch.randn(batch_size, 3, 640, 640, requires_grad=True)

# compute ONNX Runtime output prediction
ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(x)}
ort_outs = ort_session.run(None, ort_inputs)
```

With batch size = 2, it raises an error about the shape

```
[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'/model.32/Add_4' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:503 void onnxruntime::BroadcastIterator::Init(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 300 by 600
```

**Comment by glenn-jocher** [comment]
@younesslanda hello! The error you're seeing likely indicates a problem with axis broadcasting when trying to run the `ORT` model with a dynamic batch size. To fix this, we suggest modifying your code to respect the input_batch_size provided through the `ort_inputs` dictionary and passing it to the `to_numpy` function while exporting the ONNX model. 

Here is what your modified code snippet would look like:

```python
from ultralytics import RTDETR
import torch
import numpy as np
import onnxruntime


def to_numpy(tensor):
    return tensor.detach().cpu().numpy().astype('float32') if tensor.requires_grad else tensor.cpu().numpy().astype('float32')


model = RTDETR("rtdetr-x.pt")
model.export(format='onnx', dynamic=True, input_batch_size=2)

ort_session = onnxruntime.InferenceSession("rtdetr-x.onnx")
batch_size = 2
x = torch.randn(batch_size, 3, 640, 640, requires_grad=True)

# compute ONNX Runtime output prediction
ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(x)}
ort_outs = ort_session.run(None, ort_inputs)
```

We have added the input_batch_size parameter to the `model.export` method, which ensures that the input expected shape is updated to respect the input batch size.

Let us know if this solves your problem.

**Comment by younesslanda** [comment]
Hello @glenn-jocher, thank you for your answer.
My problem is I want a varying dynamic batch size. Setting the `dynamic=True` in `model.export` seems not to be working in this case.

**Comment by glenn-jocher** [comment]
Hi @younesslanda! Thank you for the clarification. 

In the case of YOLOv8, setting `dynamic=True` in the `model.export` function allows for the dynamic batch size during inference. However, it's worth noting that the dynamic batch size needs to be specified when exporting the model.

To achieve a varying dynamic batch size, you can modify your code as follows:

1. Set `dynamic=True` in the `model.export` function.
2. Specify the input batch size when exporting the model using the `input_batch_size` parameter.

By providing the desired input batch size during export, you should be able to achieve the varying dynamic batch size behavior.

Let me know if this helps and if you have any further questions!

**Comment by younesslanda** [comment]
Hello @glenn-jocher, thank you for the response.

By running this code :
```
from ultralytics import RTDETR
model = RTDETR("rtdetr-l.pt")
model.export(format='onnx', dynamic=True, input_batch_size=2)
```
I get : 
```
SyntaxError: 'input_batch_size' is not a valid YOLO argument.
```
So I changed `input_batch_size` into `batch` :
```
from ultralytics import RTDETR
model = RTDETR("rtdetr-l.pt")
model.export(format='onnx', dynamic=True, batch=2)
```
Now the model only accepts an input with `batch size == 2` : 
```
import onnxruntime
import numpy as np

ort_session = onnxruntime.InferenceSession("rtdetr-l.onnx", providers=['CPUExecutionProvider'])

batch_size=2
ort_inputs = {
    'images': np.random.randn(batch_size, 3, 640, 640).astype(np.float32)
}
ort_outs = ort_session.run(None, ort_inputs)

# this works fine
```
But in the case of `batch size != 2` : 
```
import onnxruntime
import numpy as np

ort_session = onnxruntime.InferenceSession("rtdetr-l.onnx", providers=['CPUExecutionProvider'])

batch_size=4
ort_inputs = {
    'images': np.random.randn(batch_size, 3, 640, 640).astype(np.float32)
}
ort_outs = ort_session.run(None, ort_inputs)
```
It raises : 
```
RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'/model.28/Add_4' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:540 void onnxruntime::BroadcastIterator::Init(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 600 by 900
```

Thank you for the help !

**Comment by gitzhou2006go** [comment]
@younesslanda 

> Hello @glenn-jocher, thank you for the response.
> 
> By running this code :
> 
> ```
> from ultralytics import RTDETR
> model = RTDETR("rtdetr-l.pt")
> model.export(format='onnx', dynamic=True, input_batch_size=2)
> ```
> 
> I get :
> 
> ```
> SyntaxError: 'input_batch_size' is not a valid YOLO argument.
> ```
> 
> So I changed `input_batch_size` into `batch` :
> 
> ```
> from ultralytics import RTDETR
> model = RTDETR("rtdetr-l.pt")
> model.export(format='onnx', dynamic=True, batch=2)
> ```
> 
> Now the model only accepts an input with `batch size == 2` :
> 
> ```
> import onnxruntime
> import numpy as np
> 
> ort_session = onnxruntime.InferenceSession("rtdetr-l.onnx", providers=['CPUExecutionProvider'])
> 
> batch_size=2
> ort_inputs = {
>     'images': np.random.randn(batch_size, 3, 640, 640).astype(np.float32)
> }
> ort_outs = ort_session.run(None, ort_inputs)
> 
> # this works fine
> ```
> 
> But in the case of `batch size != 2` :
> 
> ```
> import onnxruntime
> import numpy as np
> 
> ort_session = onnxruntime.InferenceSession("rtdetr-l.onnx", providers=['CPUExecutionProvider'])
> 
> batch_size=4
> ort_inputs = {
>     'images': np.random.randn(batch_size, 3, 640, 640).astype(np.float32)
> }
> ort_outs = ort_session.run(None, ort_inputs)
> ```
> 
> It raises :
> 
> ```
> RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'/model.28/Add_4' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:540 void onnxruntime::BroadcastIterator::Init(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 600 by 900
> ```
> 
> Thank you for the help !

I encountered the same problem, did you solve it?

**Comment by yellowjs0304** [comment]
same with yolo. if i set the command like this
```
yolo export model=./trained_weight/numr/numr_best_0811.pt format=onnx dynamic=True
```

But when i check the onnx file with netron, it only support batch 1.
<img width="222" alt="image" src="https://github.com/ultralytics/ultralytics/assets/30281608/e99dd52f-e094-42c6-a812-1c0cebdce13b">

what should i do for Onnx gpu runtime, with batch
@gitzhou2006go @younesslanda @glenn-jocher

**Comment by glenn-jocher** [comment]
@yellowjs0304 hello, thank you for reaching out. The command you provided will indeed export your trained YOLOv8 model to ONNX format with dynamic input/output shapes enabled.

The option `dynamic=True` allows the exported model to process inputs of different batch sizes and resolution at runtime. It means the model can be flexible in dealing with various input sizes.

However, please note that not all ONNX runtimes and optimization tools support models with dynamic shapes. For example, older versions of TensorRT may not fully support these dynamic models.

Therefore, make sure that your ONNX runtime or any other tools you plan to use are compatible with dynamic shapes before exporting the model in this way.

I hope this helps! If you encounter any problems or have any further questions, feel free to reach out.

**Comment by AnweshCR7** [comment]
@younesslanda @gitzhou2006go Facing the same issue. I would like to export an ONNX model capable of working with a variable batch-size based on the input. This was possible for Yolo models earlier but doesn't work for RT-DETR. Did you manage to resolve it somehow?

**Comment by dccho** [comment]
onnx-simplifier breaks dynamic property. I remove simplify option then model works file with dynamic batch

**Comment by glenn-jocher** [comment]
@dccho i'm glad to hear that your model is now working fine with dynamic batch sizes after removing the simplify option during ONNX export. It's important to note that certain ONNX post-processing steps, like simplification, can sometimes interfere with dynamic properties. It's always a good practice to verify the end-to-end behavior of your model after any modifications. If you run into any other issues, feel free to ask. Happy coding! 😊👍

**Comment by sdurmustalipoglu** [comment]
How can I  use rt-detr after onnx output?
ort_outs = ort_session.run(None, ort_inputs)

In ort_outs in below. It should be box sizes at  4 columns. But the data it does not make any sense.
[array([[[0.95845395, 0.5067266 , 0.03859097, 0.0099203 , 0.1055311 ],
         [0.9714186 , 0.7349827 , 0.04337773, 0.00955239, 0.03577971],
         [0.948589  , 0.8236258 , 0.05849624, 0.00824615, 0.05054411],
         ...,
         [0.30325168, 0.39236677, 0.08148962, 0.00897163, 0.03895688],
         [0.52754325, 0.0294382 , 0.04904827, 0.00935864, 0.0522306 ],
         [0.8139978 , 0.19884908, 0.05695143, 0.00868419, 0.03222087]]],
       dtype=float32)]

I will be appreciated your help

**Comment by pderrenger** [comment]
It looks like the output from your ONNX model isn't in the expected format. The `ort_outs` array should indeed contain bounding box coordinates, typically in a format with 4 columns representing [x, y, width, height] or similar. 

First, ensure that you are using the latest version of the Ultralytics package and ONNX runtime. If the issue persists, it might be related to the model's export configuration or the way the output is being interpreted. 

Check the model's documentation for the expected output format and verify that the ONNX export process was completed without errors. If you continue to face issues, please provide more details about the steps you followed for exporting the model and any modifications made. This will help in diagnosing the problem more effectively.

**Comment by sdurmustalipoglu** [comment]
I try every kind of solution after your comment. It does not work

I export the model in the below code.
`model5.export(format="onnx", opset=16) `


After that

`
onnx_model = 'C:/Users/stalipoglu/onnx/rtdet_100e_16op.onnx' 
onnx.checker.check_model(onnx_model)

sess_options = ort.SessionOptions()

# Below is for optimizing performance
sess_options.intra_op_num_threads = 24
sess_options.execution_mode = ort.ExecutionMode.ORT_PARALLEL
sess_options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL
ort_session = ort.InferenceSession("rtdet_100e_16op.onnx", sess_options=sess_options,providers = ['CUDAExecutionProvider'])


def to_numpy(tensor):
    #return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

`

`all_outs = []
process_time = []

print("\n \n                      RTDET                                ")
for images, targets in tqdm(test_loader):
    false = False
    for target in targets:
            
        for key, value in target.items():
            if value == None:
                false = True
                continue
        if false == True:
            continue
        targets = [{k: v.to(device) for k, v in t.items()} for t in targets]
        images = list(image.to(device) for image in images)
            
    for i, image in enumerate(images):
        print(f"\n Image {i} shape: {image.shape}")
        image1 = image.unsqueeze(0)
        print(f"\n Image1 {i} shape: {image1.shape}")

        start_time = time.time()
        ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(image1)}
        ort_outs = ort_session.run(None, ort_inputs)
        end_time = time.time()
        
        print(f"İşlem süresi: {end_time - start_time:.4f} sn \n")
        
        process_time.append(end_time - start_time)
        
        print(ort_outs)
        all_outs.append(ort_outs)
        print("-------------------------------------------------------------------")


    print("Mean Process Time : ", round(np.mean(process_time),2), "sn")
`

**Comment by pderrenger** [comment]
Thank you for sharing the detailed steps you've taken. It appears that the model export and ONNX runtime setup are correct. However, the output format might not be as expected. 

Please ensure you are using the latest versions of the Ultralytics package and ONNX runtime. If the issue persists, it might be helpful to check the model's documentation for the expected output format and verify that the export process completed without errors.

If you continue to face issues, please provide more details about the specific problem you're encountering with the output. This will help us diagnose the problem more effectively.

**Comment by sdurmustalipoglu** [comment]
I also tried that but it doesn't work by the way the last version of the program does not supported by GPU. That's way,  I can only try to convert from pre-trained model to onnx format at the last version. It takes too much time maybe 8-10 hours  to train a model in cpu

**Comment by pderrenger** [comment]
Thank you for your feedback. To address the GPU support issue, please ensure you are using the latest versions of the Ultralytics package and ONNX runtime, as updates often include important fixes and improvements. If the problem persists, consider using a pre-trained model to expedite the process. If you encounter any specific errors or issues during the ONNX export or inference, please provide those details so we can assist you further.
