### ISSUE TITLE
Anyone successfully installed Ultralytics on a closed network with no Internet connection?

### ISSUE THREAD

**Issue by whnam87** [ultralytics/ultralytics#3405]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have an Ubuntu container environment provided by my company, but this is a closed network with no Internet connection.

The container environment is running Python 3.8 with tf 2.4.0, torch 1.9.0, cuda 11.1 on Ubuntu 20.04 on AMD64 and has high-end hardware installed: Nvidia A100 80GB x 3 without internet connection.  So I cannot use the 'apt-get' or 'pip install' command with the Internet connection.

The Ultralytics requires many dependencies, but anyone who has successfully installed Ultralytics on a closed network can share the way?

**Comment by glenn-jocher** [comment]
@whnam87 for installation instructions see https://docs.ultralytics.com/quickstart

For enterprise licensing for commercial use at your company see https://ultralytics.com/license

**Comment by whnam87** [comment]
Not solved

**Comment by glenn-jocher** [comment]
@whnam87 hi there,

Thank you for reaching out! I understand that you're facing an issue with YOLOv8. I'd be happy to help you with it.

To better assist you, could you please provide more details about the specific problem you're encountering? This will help me understand the issue and provide you with the most accurate solution.

Looking forward to your response.

Best regards,
Glenn Jocher
