### ISSUE TITLE
Add end2end ONNX export

### ISSUE THREAD

**Issue by DennisJcy** [ultralytics/ultralytics#3408]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thank you for your excellent work!
I find the opencv dnn inference example in the code.However, the dnn is slower than onnxruntime both cpu and cuda.While export the onnx without the nms operator.Which The end2end onnx is useful for inference without transfer data between cpu and gpu which cost some time especially the pose model.Or there maybe a way to do that with my mistake

**Comment by glenn-jocher** [comment]
@DennisJcy hello! Thank you for your kind words and for using YOLOv8. We appreciate your support!

Regarding your question, currently, YOLOv8 supports exporting models in the ONNX format but the exported ONNX model does not include the NMS (Non-Maximum Suppression) operator. This means that the ONNX model cannot be used for end-to-end inference directly without additional post-processing.

However, you can use the exported ONNX model as a starting point and integrate it into a workflow where you perform the NMS step separately. One option is to use a library like ONNX Runtime to load the model and perform NMS using its post-processing capabilities. This way, you can avoid transferring data between the CPU and GPU and potentially improve the inference speed.

I hope this clarifies your question. Please let me know if you have any further inquiries or if there's anything else I can assist you with.

**Comment by DennisJcy** [comment]
Thank you for your reply!
I have Implement the Inference with ORT+dnn::NMSBoxes in CPP follow your example. The YOLOV8n is 10ms faster than YOLOV7-TINY with my i5-11400H CPU.
v5-nano
![image](https://github.com/ultralytics/ultralytics/assets/106725464/a79beec0-03d6-4602-8904-8b35a81a7ea1)
v8-nano
![image](https://github.com/ultralytics/ultralytics/assets/106725464/115b43d0-385a-444b-a558-cebd8bb93174)
v7-tiny
![image](https://github.com/ultralytics/ultralytics/assets/106725464/0972f977-9325-4bac-b5fe-d3fde4f1dfab)

**Comment by glenn-jocher** [comment]
@DennisJcy thank you for sharing your results and comparing the performance of YOLOv8-nano and YOLOv7-tiny on your i5-11400H CPU. It's great to hear that YOLOv8-nano is 10ms faster than YOLOv7-tiny in your setup! 

Your images provide a helpful visual representation of the performance improvement. The increased speed of YOLOv8-nano can be attributed to the improvements and optimizations made in the YOLOv8 architecture compared to YOLOv7-tiny. 

We appreciate your contribution and feedback. If you have any more questions or need further assistance, please feel free to ask. Keep up the great work!

**Comment by DennisJcy** [comment]
I'm trying to contribute my deploy cpp code to this repository, thank you for your kind reply

**Comment by glenn-jocher** [comment]
@DennisJcy thank you for your interest in contributing your C++ deploy code to the YOLOv8 repository! We appreciate your willingness to contribute and support the project.

To submit your code, please follow the steps outlined in our contribution guidelines. First, ensure that your code adheres to our code style and conventions. Next, create a new branch in the repository and commit your changes there.

Once your code is ready, you can create a pull request (PR) to propose your changes. In the PR, provide a clear description of the changes you have made, including any relevant details or considerations. Our team will review your code and provide feedback or suggestions if necessary.

We value the contributions of our community members and appreciate your effort in making YOLOv8 even better. If you have any further questions or need any assistance during the contribution process, feel free to ask. We look forward to reviewing your code and working with you to integrate it into the repository.

**Comment by braindotai** [comment]
Hi @DennisJcy , I am also looking for implementing post processing exported into onnx runtime, any updates on your progress :))

**Comment by glenn-jocher** [comment]
Hi @braindotai, thank you for your interest in implementing post-processing into the ONNX runtime for YOLOv8. Our team is working on this, and while we don't have a concrete update at this time, we want to assure you it's on our radar. We appreciate your patience and please stay tuned for future updates. Your contributions and interest in this project are greatly valued!

**Comment by DennisJcy** [comment]
@braindotai   You can write a class like yolov7 that inherits nn.module to implement the end-to-end export like under:
``` python
class End2End(nn.Module):
    def __init__(self, model, task, max_obj=100, iou_thres=0.45, score_thres=0.25, max_wh=None, device=None, n_classes=80):

    def forward(self, x):
        x = self.model(x)
        x = self.end2end(x)
        return x
```

**Comment by glenn-jocher** [comment]
Hi @DennisJcy, thanks for your question.

You are on the right track. Instead of exporting the model directly as an ONNX file using torch.onnx.export(), you can create a subclass of torch.nn.module, like you've suggested, to encapsulate the model and the post-processing steps. You can define an `End2End` class in which the `forward` method applies the model to the input and then performs any necessary post-processing.

You would then pass an instance of this `End2End` class, instead of the raw model, to torch.onnx.export() to export your ONNX file. This will ensure that the post-processing steps your model requires are included in the exported ONNX file.

Please note that this method may not work for all post-processing steps as it depends on whether the exact operations used in post-processing are supported by ONNX and the target inference engine.

This approach should also be taken care to properly handle the ONNX dynamic input shape while exporting as post-processing steps might have some dependencies on the input shape.

I hope this helps! If you have further questions, feel free to ask.
