### ISSUE TITLE
Why is export to ncnn not supported out of the box?

### ISSUE THREAD

**Issue by yrik** [ultralytics/ultralytics#3412]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I see that everyone is following some magic woodu steps when exporting to ncnnn. It basically includes some obscure ultralitics code modification in a couple of places. 
It is described here 
- https://medium.com/@gary.tsai.advantest/top-tutorials-for-deploying-custom-yolov8-on-android-%EF%B8%8F-dd6746afc1e6. #3379 
- https://github.com/FeiGeChuanShu/ncnn-android-yolov8/issues/8
- https://github.com/ultralytics/ultralytics/issues/726

Wouldn't it be better to have it integrated and what would result in an option to have truly performant deployment of an awesome yolov8 model?

### Use case

Deployment on mobile and embedded systems where ncnn works way faster.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@yrik hello, thank you for writing to us. 
YOLOv8 currently does not have built-in support for exporting to ncnn format. However, we appreciate your feedback and will consider adding the feature in the future.

Currently, the suggested method for exporting to ncnn format involves a series of Ultralytics code modifications. These modifications are performed outside the scope of the YOLOv8 repository and may be specific to certain hardware or software environments. 

We encourage you to monitor the relevant GitHub issues and contribute to the discussion with any knowledge or experience you may have. Please note that we cannot commit to a timeline for adding support for exporting to ncnn format at this time.

Thank you for using YOLOv8 and for your valuable feedback.

**Comment by yrik** [comment]
Hi @glenn-jocher,  I'm not sure I understood your answer. 

What is the state exactly? You don't want to support it? Or there is not enough manpower for that? Does it make sense to try to make PR? Or would it be not accepted even if someone has created it? Or was it not yet considered? I see that you have support for many other export formats but not this one, so there is probably some reason for that.

**Comment by kalenmike** [comment]
@yrik The previous reply was an automated bot. We are currently working on migrating it to another user to prevent confusion.

We are looking to add support for ncnn in the near future provided we do not face any severe complications.

@glenn-jocher Any updates on the ncnn exports?

FYI @sergiossm

**Comment by glenn-jocher** [comment]
@yrik hey there! Yes I think NCNN is the last major format we are missing. In the past for YOLOv5 I skipped it because the installation was not fully supported by pip, but that was about a year ago so I'll take another look. 

If you know your way around NCNN export then a PR would be a great help to us as I don't have NCNN experience myself. It looks like the module changes can be made using `self.export` flags that get set to True or set to 'ncnn' if export is ncnn. We already have examples of this when switching from .split() or .chunk() during certain export formats here:

https://github.com/ultralytics/ultralytics/blob/25159c93761736d811d350c7e9352d3fc28d2756/ultralytics/nn/modules/head.py#L55-L57

**Comment by glenn-jocher** [comment]
@yrik @kalenmike great news 😃! Your original issue may now be resolved ✅ in Ultraltyics PR https://github.com/ultralytics/ultralytics/pull/3529 which is part of `ultralytics==8.0.129`. This release adds official support for Ultralytics YOLOv8 NCNN export! You can export with CLI:
```
yolo export model=yolov8n.pt format=ncnn
```

or Python:
```python
from ultralytics import YOLO

# Create a model
model = YOLO('yolov8n.pt')

# Export the model to NCNN with arguments
model.export(format='ncnn', half=True, imgsz=640)
```

Output is a `yolov8n_ncnn_model/` directory containing `model.bin`, `model.param` and `metadata.yaml`, along with extra PNNX files. For details see https://github.com/pnnx/pnnx


To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!
