### ISSUE TITLE
Format bug with `%g` for keys in `images` dict in `convert_coco`

### ISSUE THREAD

**Issue by GreatGameDota** [ultralytics/ultralytics#3419]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

https://github.com/ultralytics/ultralytics/blob/05760b04c41d35b75c19a6a4620affbf7385bd6a/ultralytics/yolo/data/converter.py#L58
This line of code will round-off integers that are too big (up to 6 digits precision).
https://github.com/ultralytics/ultralytics/blob/05760b04c41d35b75c19a6a4620affbf7385bd6a/ultralytics/yolo/data/converter.py#L66
Normally this mapping would be fine and the id can be retrieved here. However, if two numbers are very close, they can be rounded-off to the same number resulting in the key being overridden.

### Minimal Reproducible Example

```
images = {'%g' % x['id']: x for x in [{'id': 1616047265003116043}, {'id': 1616047197720010576}]}
```
Results in:
```
{'1.61605e+18': {'id': 1616047197720010576}}
```
So the first id was completely overwritten and the key is `1616050000000000000` if it is converted back to an integer.

### Additional

This would normally be fine if numbers are unlikely to reach that size, like coordinates on an image e.g.:
https://github.com/ultralytics/ultralytics/blob/05760b04c41d35b75c19a6a4620affbf7385bd6a/ultralytics/yolo/data/converter.py#L115
I am not sure why `%g` is used for image ids as those can be any arbitrary number depending on the dataset. This is also a utility script so memory/speed does not matter very much.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@GreatGameDota great news 😃! Your original issue may now be resolved ✅ in PR #3420. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!
