### ISSUE TITLE
download rtdetr pretrain weight

### ISSUE THREAD

**Issue by shudct** [ultralytics/ultralytics#3425]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I notice that the pretrain weights rtdetr-l.pt in rtdetr.md, but there is no links. how can i download these weights?

**Comment by glenn-jocher** [comment]
@shudct thank you for reaching out! To load the pre-trained weights for RTDETR in YOLOv8, you can use the `RTDETR` class and pass the path to the weights file as an argument, like this: `model = RTDETR("rtdetr-l.pt")`. This will load the pre-trained weights and initialize the RTDETR model for you to use. Let me know if you have any further questions!
