### ISSUE TITLE
Cannot train RT-DETR on multi-gpu from checkpoint (works fine from scratch)

### ISSUE THREAD

**Issue by ExtReMLapin** [ultralytics/ultralytics#3439]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Single GPU training works fine with RT-DETR when :
* Loading from checkpoint (`rtdetr-l.pt`)
* Training from scratch (`rtdetr-l.yaml`)

It works on multi gpu only when training from scratch as when it try to run on multi GPU it errors with :  

```
DDP info: RANK 0, WORLD_SIZE 3, DEVICE cuda:0
wandb: Currently logged in as: lpn64. Use `wandb login --relogin` to force relogin
wandb: wandb version 0.15.4 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.15.2
wandb: Run data is saved locally in /opt/ultralytics/wandb/run-20230628_161623-5xhen8k2
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run large 2.5 boost RT-DETR
wandb: ⭐️ View project at CENSORED
wandb: 🚀 View run at CENSORED
Overriding model.yaml nc=80 with nc=1
WARNING ⚠️ no model scale passed. Assuming scale='l'.
Transferred 926/941 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning /home/CENSORED/CENSORED/labels/train.cache... 1719 images, 9 backgrounds, 0 corrupt: 100%|██████████| 1719/1719 [00:00<?, ?it/s]
val: Scanning /home/CENSORED/CENSORED/labels/val.cache... 491 images, 1 backgrounds, 0 corrupt: 100%|██████████| 491/491 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/CENSORED/.config/Ultralytics/DDP/_temp_r_5xaqei139646217166880.py", line 9, in <module>
    trainer.train()
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
Traceback (most recent call last):
  File "/home/CENSORED/.config/Ultralytics/DDP/_temp_r_5xaqei139646217166880.py", line 9, in <module>
    self._do_train(world_size)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 276, in _do_train
    self._setup_train(world_size)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 267, in _setup_train
        trainer.train()self.resume_training(ckpt)

  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 584, in resume_training
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 276, in _do_train
    start_epoch = ckpt['epoch'] + 1
KeyError: 'epoch'
    self._setup_train(world_size)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 267, in _setup_train
    self.resume_training(ckpt)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 584, in resume_training
    start_epoch = ckpt['epoch'] + 1
KeyError: 'epoch'
Plotting labels to /opt/ultralytics/runs/detect/large 2.5 boost RT-DETR12/labels.jpg...
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3074218 closing signal SIGTERM
15
optimizer: SGD(lr=0.01, momentum=0.9) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.000515625), 226 bias(decay=0.0)
Traceback (most recent call last):
  File "/home/CENSORED/.config/Ultralytics/DDP/_temp_r_5xaqei139646217166880.py", line 9, in <module>
    trainer.train()
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 276, in _do_train
    self._setup_train(world_size)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 267, in _setup_train
    self.resume_training(ckpt)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 584, in resume_training
    start_epoch = ckpt['epoch'] + 1
KeyError: 'epoch'
```

### Environment

4 A40 4GB Ubuntu Torch stable on GPU

### Minimal Reproducible Example

Command :

```
yolo detect train data=./your_dataset.yaml epochs=1250 imgsz=2048 patience=0 batch=6 model="rtdetr-l.pt" device=0,1,2  name="large 2.5 boost RT-DETR"

```

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ExtReMLapin got it! Could you submit a PR for a fix if you've patched it locally?

@Laughing-q it looks like maybe the RTDETR trainer is not using the same model save code as the base class since at least 'epoch' is missing from the checkpoint dict.

**Comment by ExtReMLapin** [comment]
> @ExtReMLapin got it! Could you submit a PR for a fix if you've patched it locally?
> 
> @Laughing-q it looks like maybe the RTDETR trainer is not using the same model save code as the base class since at least 'epoch' is missing from the checkpoint dict.

It's already up  ! https://github.com/ultralytics/ultralytics/pull/3440

So far there is a warning after the first epoch, but it ran fine for 12 epoch after the infamous `matrix contains invalid numeric entries` that can be fixed with `amp=false`

**Comment by glenn-jocher** [comment]
@ExtReMLapin hi,

Thank you for bringing this issue to our attention. I noticed that you have already submitted a pull request (#3440) for the fix. That's great!

Regarding the difference in behavior between single GPU and multi-GPU training, it can be attributed to the implementation of the RT-DETR trainer. It seems that the model saving code used in the training process may not be consistent across different scenarios, causing the issue you encountered. This inconsistency can result in missing keys like 'epoch' in the checkpoint dictionary.

While the fix in the pull request should address the problem, it's important to note that there might be a warning after the first epoch. Additionally, if you encounter the "matrix contains invalid numeric entries" error, setting `amp=false` should resolve it.

Thank you for your contribution and for helping us improve the Ultralytics YOLOv8 repository. If you have any further questions or need assistance, please feel free to ask.

Best regards,
Glenn Jocher

**Comment by glenn-jocher** [comment]
@ExtReMLapin @Laughing-q I see that when we train the models from YAML the ckpt structure is correct, so we are just going to train new RTDETR models and replace the existing assets with those. This should take a few days.

**Comment by ExtReMLapin** [comment]
Fixed !

**Comment by glenn-jocher** [comment]
@ExtReMLapin great news! The issue has been fixed. Please make sure to delete any existing RT-DETR models that you have locally and try running your command again. The fix involves running `strip_optimizer` on the checkpoints, returning them to the default checkpoint status. This should resolve the problem and allow you to train RT-DETR models on multiple GPUs without any errors. Thank you for your patience, and please let us know if you have any further questions or concerns.

**Comment by Misael777** [comment]
Hello I have a similar problem I can train with multi-GPUs. I attach the issue lines down. This is the cli comand that I running.

yolo train model=rtdetr-l.pt data=data.yaml epochs=2 imgsz=500 batch=16 device=0,1


#ERROR
      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
  0%|          | 0/658 [00:00<?, ?it/s]C:\Users\PracIngInd3\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\autograd\graph.py:744: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:87.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
        1/2      4.59G          0       1825          0          0        512:   0%|          | 1/658 [00:01<13:07,  1.20s/it]
[rank0]: Traceback (most recent call last):
[rank0]:   File "C:\Users\PracIngInd3\AppData\Roaming\Ultralytics\DDP\_temp_gxg1v5zy2245759170640.py", line 9, in <module>
[rank0]:     trainer.train()
[rank0]:   File "C:\Users\PracIngInd3\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\engine\trainer.py", line 195, in train
[rank0]:     self._do_train(world_size)
[rank0]:   File "C:\Users\PracIngInd3\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\engine\trainer.py", line 348, in _do_train
[rank0]:     self.loss, self.loss_items = self.model(batch)
[rank0]:   File "C:\Users\PracIngInd3\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "C:\Users\PracIngInd3\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "C:\Users\PracIngInd3\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\parallel\distributed.py", line 1589, in forward
[rank0]:     inputs, kwargs = self._pre_forward(*inputs, **kwargs)
[rank0]:   File "C:\Users\PracIngInd3\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\parallel\distributed.py", line 1480, in _pre_forward
[rank0]:     if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
[rank0]: RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`,

**Comment by glenn-jocher** [comment]
@Misael777 hello! It looks like you're encountering an issue with unused parameters during distributed training with RT-DETR. This is often resolved by enabling the detection of unused parameters in your DistributedDataParallel configuration. Try adjusting your setup to include the `find_unused_parameters=True` argument.

Here’s how you can modify your training script to incorporate this change:

```python
from torch.nn.parallel import DistributedDataParallel as DDP

# Assuming 'model' is your model instance and 'device' is your designated device
model = model.to(device)
model = DDP(model, device_ids=[device], find_unused_parameters=True)
```

This should help sidestep the reduction error you're seeing by ensuring all parameters are accounted for in the backward pass, regardless of whether they're actively used in the forward pass. Give it a try and let us know how it goes! 😊

**Comment by Misael777** [comment]
from ultralytics import RTDETR
import torch
from torch.nn.parallel import DistributedDataParallel as DDP
print(torch.version.cuda)
torch.cuda.is_available()
print(torch.cuda.is_available())

yaml_path = 'data.yaml' 
epochs = 1
patience = 100 
img_size = 512
device_ids = [0, 1] if torch.cuda.is_available() else 'cpu' 
#device = 0 if torch.cuda.is_available() else 'cpu' 
plots = True 
save_period = 10 #Checkpoint
batch = 8
workers = 30 
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

if _name_ == '_main_':
    # Load a COCO-pretrained RT-DETR-l model
    model = RTDETR('rtdetr-l.pt')
    
    
    if torch.cuda.is_available() and len(device_ids) > 1:
        # Initialize the model on the first device
        model = model.to(device=device)
        # Wrap the model with DDP
        model = DDP(model, device_ids=device_ids, find_unused_parameters=True)
        
        
    else:
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        model = model.to(device=device)
        
        
    model.info()

    results = model.train(
        data=yaml_path,
        epochs=epochs,
        patience=patience,
        imgsz=img_size,
        device=device,
        plots=plots,
        save_period=save_period,
        batch=batch,
        workers=workers
    )
    
    ###################################################################
    ###################################################################
    this is my code with the changes that you suggest me, but I have this error :( ....
    
    
    Traceback (most recent call last):
  File "c:/Users/PracIngInd3/Desktop/RTDETR/train.py", line 30, in <module>
    model = DDP(model, device_ids=device_ids, find_unused_parameters=True)
  File "c:\Users\PracIngInd3\Desktop\RTDETR\.venv\lib\site-packages\torch\nn\parallel\distributed.py", line 671, in _init_
    self._log_and_throw(
  File "c:\Users\PracIngInd3\Desktop\RTDETR\.venv\lib\site-packages\torch\nn\parallel\distributed.py", line 1089, in _log_and_throw
    raise err_type(err_msg)
RuntimeError: DistributedDataParallel is not needed when a module doesn't have any parameter that requires a gradient.
    
    
    Please, cloud you help me @glenn-jocher

**Comment by glenn-jocher** [comment]
Hey there! It looks like the error you're encountering suggests that your model doesn't have any parameters that require gradients, which is unusual if you're expecting to train the model. This could happen if your model is in `.eval()` mode or if all parameters are frozen.

To ensure your model is ready for training, you can add a check to make sure it's set to training mode and that there are trainable parameters:

```python
model.train()  # Set the model to training mode

# Check if there are any trainable parameters
if not any(p.requires_grad for p in model.parameters()):
    print("No trainable parameters found. Check your model configuration.")
else:
    model = DDP(model, device_ids=device_ids, find_unused_parameters=True)
```

This snippet will help you identify if the model is indeed ready for training or if there might be an issue with the model configuration. Let me know how it goes! 😊
