### ISSUE TITLE
How to control output directory?

### ISSUE THREAD

**Issue by jalexhurt** [ultralytics/ultralytics#344]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to use YOLOv8 in an environment in which I mount an output directory to a container. Following the documentation allows all the data and model paths to work perfectly, however I am unable to route model outputs to the mounted output directory. 

I have tried setting the `save_dir` parameter both from CLI and from a `cfg.yaml`, but in both cases, I receive an error of Invalid Key. 
```
Overriding default config with /output/args.yaml
save_dir is not a valid key. Similar keys: ['save_crop', 'save', 'save_hybrid']
```

How should I go about routing output to a custom directory?

**Comment by knoppmyth** [comment]
I too use a container, I mount my output directory under the "app" directory:
`docker run --ipc=host -it --gpus all -v ~/Development/YOLO/datasets:/usr/src/datasets -v ~/Development/YOLO/yolov8_runs/:/usr/src/yolov8/runs -v ~/Development/YOLO/yolov8_data/:/usr/src/yolov8/data knoppmyth/yolov8:latest`

**Comment by Laughing-q** [comment]
@jalexhurt  the save_dir is composed of project and name, which means save_dir = project/name, so just modify these two if you want to change save_dir.

**Comment by jalexhurt** [comment]
Both of your solutions fix the issue. Thank you very much!
