### ISSUE TITLE
Quantized Tensorflow Lite models don't output any detections

### ISSUE THREAD

**Issue by Rubengb16** [ultralytics/ultralytics#3443]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

Quantized Tensorflow Lite models don't infer any object. I've exported the pretrained yolov8n model to Tensorflow Lite and, if I use any of the quantized models (e.g. yolov8n_full_integer_quant.tflite) I'm unable to get any detections. If I use other exported models, like yolov8n_int8.tflite, the output seems correct. 

### Environment

- Ultralytics YOLOv8.0.124 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB) (2 CPUs, 12.7 GB RAM, 24.2/78.2 GB disk)
- Ubuntu: 20.04
- Python: 3.10.12
- Tensorflow: 2.12.0

### Minimal Reproducible Example

`yolo export model=yolov8n.pt format=tflite int8=True`
`yolo predict task=detect model=yolov8n_saved_model/yolov8n_full_integer_quant.tflite imgsz=640`

WARNING ⚠️ 'source' is missing. Using default 'source=/usr/local/lib/python3.10/dist-packages/ultralytics/assets'.
Ultralytics YOLOv8.0.124 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB)
Loading yolov8n_saved_model/yolov8n_full_integer_quant.tflite for TensorFlow Lite inference...
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

image 1/2 /usr/local/lib/python3.10/dist-packages/ultralytics/assets/bus.jpg: 640x640 (no detections), 281.5ms
image 2/2 /usr/local/lib/python3.10/dist-packages/ultralytics/assets/zidane.jpg: 640x640 (no detections), 238.6ms
Speed: 27.4ms preprocess, 260.1ms inference, 17.9ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict2

`yolo predict task=detect model=yolov8n_saved_model/yolov8n_int8.tflite imgsz=640`

WARNING ⚠️ 'source' is missing. Using default 'source=/usr/local/lib/python3.10/dist-packages/ultralytics/assets'.
Ultralytics YOLOv8.0.124 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB)
Loading yolov8n_saved_model/yolov8n_int8.tflite for TensorFlow Lite inference...
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

image 1/2 /usr/local/lib/python3.10/dist-packages/ultralytics/assets/bus.jpg: 640x640 4 persons, 1 bus, 367.9ms
image 2/2 /usr/local/lib/python3.10/dist-packages/ultralytics/assets/zidane.jpg: 640x640 2 persons, 1 tie, 446.1ms
Speed: 19.2ms preprocess, 407.0ms inference, 61.3ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict3

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Rubengb16 hi there! Thank you for bringing this issue to our attention.

It seems that there is an issue with the quantized Tensorflow Lite models in YOLOv8. When using the quantized models, such as `yolov8n_full_integer_quant.tflite`, no detections are being made. However, if you use other exported models like `yolov8n_int8.tflite`, the output appears to be correct.

To reproduce the issue, you exported the `yolov8n.pt` model to TFLite format with quantization using the command `yolo export model=yolov8n.pt format=tflite int8=True`. Then, when running the detection task with the exported `yolov8n_full_integer_quant.tflite` model using the command `yolo predict task=detect model=yolov8n_saved_model/yolov8n_full_integer_quant.tflite imgsz=640`, no detections are found. However, if you use `yolov8n_int8.tflite` instead, detections are made.

We apologize for the inconvenience caused by this bug. We appreciate your help in identifying this issue, and we will work on resolving it as soon as possible.

If you have any further questions or need assistance with anything else, please feel free to ask.

**Comment by Rubengb16** [comment]
> @Rubengb16 If you are still looking for fully quantized YOLO models, please see below:
> 
> 
> 
> Our team at DeGirum has successfully quantized and ported Ultralytics object detection models to Edge TPU. Specifically: YOLOv5nu, YOLOV5su, YOLOv8n, and YOLOv8s, with SiLU or ReLU6 activation functions. Each of these has been trained for a full COCO object detection task, as well as specialized models for face, hand, car, and license plate detection!
> 
> 
> 
> We are making these models available on our cloud platform at: https://degirum.com/#sign-up
> 
> 
> 
> On the platform, you can try each model on: OpenVINO CPU (float), TFLite CPU (float), and TFLite EdgeTPU (quant), for a total of 120 possible combinations!
> 
> 
> 
> Once signed up, you can run the models in the browser or in this Google colab notebook: https://colab.research.google.com/github/DeGirum/PySDKExamples/blob/main/UltralyticsObjectDetectionImage.ipynb
> 
> 
> 
> For any questions or support, please open an issue on: https://github.com/DeGirum/PySDKExamples
> 
> 
> 
> If anyone’s interested, we will be doing a live demonstration of using these new models at: https://www.linkedin.com/events/theartofyolo-part1-unleashingth7092593180545540096/

Thank you! I will see if it serves to me.

**Comment by glenn-jocher** [comment]
@shashichilappagari, we're glad to hear you found the offerings from the team at DeGirum potentially useful. Their work to successfully quantize and port Ultralytics object detection models such as YOLOv8 to Edge TPU is truly commendable. 

Having access to a full range of pre-trained models optimized for different tasks, such as a full COCO object detection task and specialized models for face, hand, car, and license plate detection, can indeed be beneficial. 

It's also great that you can experiment with these models in different environments, like OpenVINO and TFLite, on their cloud platform.

If you encounter any issues or have questions regarding their models, they have suggested reaching out by opening an issue on their PySDKExamples GitHub repository. They also mentioned a live demonstration of their new models, which could be an exciting opportunity to see these models in action.

Let us know if there is anything else we can assist you with. Happy coding!

**Comment by hlreicha** [comment]
Any updates or fixes on this?

**Comment by glenn-jocher** [comment]
Hello @hlreicha, thank you for checking in on this issue. We understand the importance of this issue and want to assure you that our team is actively working on it. Please bear with us as we try to iron out the issues. We are always striving to improve YOLOv8 and your patience is much appreciated. We will be sure to report back here as soon as we have any significant updates or a potential fix. Your understanding is greatly appreciated!

**Comment by hlreicha** [comment]
I suspect it outputs 0 detections because the int8 tflite model outputs tensor is int8 and the NMS does not expect these values. When you output raw detection's confidence value like this:
`print(np.unique(raw_detection[0, 4:, :]))`
The values are: [-108 -107]. The NMS confidence threshold expects values between 0.0 and 1.0, since the raw detection's output confidences are so low, none of the detections passes the threshold. I did tried to convert the output tensor back to floating point values like this:
```
output_details = interpreter.get_output_details()  
scale, zero_point = output_details[0]['quantization']  
converted_detection =  (raw_detection - zero_point) / scale  
print(np.unique(converted_detection[0, 4:, :]))  
```
This yields [0.       0.571223] and I managed to get detections again but the bounding boxes are off (unless I am doing something wrong with the conversion). I think this could be fixed if we keep the output tensor as FP32/64 (whichever the original output tensor datatype is) and preferably keep the input tensor the same as well. Let me know what you think!

**Comment by glenn-jocher** [comment]
@hlreicha hi there, thank you for this detailed analysis about the issue you've encountered with the int8 tflite model in YOLOv8. It's greatly appreciated!

As you've noted, it's likely the NMS is indeed not handling the int8 outputs correctly, as it is expecting values between 0.0 and 1.0. Your observation that the raw detection's output confidences are significantly outside this range may be a key indicator as to why no detections are being made.

Your attempt to convert the output tensor back to floating point values is an interesting approach. It's possible that the bounding box correctness issue might be due to inaccuracies in the conversion process.

Overall, your suggestion to keep the output tensor as FP32/64, ideally aligning it with the input tensor type to ensure consistency, might indeed aid in resolving this issue. We appreciate your effort in investigating this matter and your suggestions. These points will certainly inform our ongoing work on resolving this bug. 

Thank you once again for your valuable input!

**Comment by tpsvoets** [comment]
@hlreicha Could you elaborate a bit please? I'm currently running into a comparable problem I think. I have one model (that I converted some time ago) that seems to work, but another model (converted today) gives no outputs, even though the .pt file works fine. Help is greatly appreciated!

**Comment by hlreicha** [comment]
@tpsvoets I believe it is from the NMS function failing to handle the Int8 values from the Tflite model. In my own testing, the confidence values are [-128,-127], whereas the NMS function expects values between 0 and 1. I tried to do some conversions to bring the values back to the normal range but the bounding boxes were way off. I am not sure if the Tflite Int8 conversion is faulty (if you look in the code, it converts the Input and Output tensors to Int8) or something changed with the NMS function that  fails to handle Int8 output tensor. I tried other Tflite Int8 conversions but none of them worked, I ended up using YoloV4.

**Comment by tpsvoets** [comment]
@hlreicha Thanks for the quick response! I find it super weird that I have one model that seems to work, while another does not. Do you have any idea how that could be? And may I ask, why v4 instead of v5?

**Comment by tpsvoets** [comment]
@hlreicha ah right, makes sense. I'm doubting whether I should switch back v5 for the same reason. I double checked with the two networks I had (one working, the other not) and I retrained both networks with the exact same code. One gives output, while the other doesn't. So I guess it indeed has to do with the confidence score, since the network that doesn't give an output is trained on a far smaller dataset, so I presume the confidence scores are lower? Still a bit of a mystery to me though, so if you or anyone knows more, that would be of great help.

**Comment by shashichilappagari** [comment]
@hlreicha and @tpsvoets Quantized tflite models need to be exported properly so as not to lose accuracy. We have a fork of ultralytics repo where we fixed these issues. We made a simple colab notebook that you can try your checkpoints on: https://colab.research.google.com/drive/1yjCEwwFuMKvFJceSDfyWrUWOSfvLlPjl?usp=sharing
Please let us know if it helps or if you have any trouble running the notebook.

**Comment by glenn-jocher** [comment]
Hi @tpsvoets and @tpsvoets, are you utilizing the latest version of the Ultralytics YOLOv8 repository? Ensure you are using the most up-to-date version as we frequently release bug fixes and improvements.

As you've noted, the Non-Max Suppression (NMS) implementation assumes confidence scores between 0 and 1, which may potentially be incompatible with quantized int8 values. Let's look into a solution for this. We suggest that you normalize the int8 output values back to the 0-1 range before applying NMS. You could possibly adjust your confidence threshold to match the int8 range if changing the output isn't enough.

On the other hand, if you're particular just about quantization and don't necessarily require int8 precision, exporting your model as a FP16 quantized model may be a feasible workaround in your case. 

It really seems like a conversion inaccuracy might be causing the problem in such instances, and we'll look into this further. The export and the NMS implementation processes may very well need to evolve further to ensure consistent results across various input and output tensor datatypes, and to better accommodate for changes during conversion.

Your feedback and investigation into this matter are significantly appreciated, and will certainly guide our progression in enhancing the relevant processes. Your patience and understanding are equally appreciated as we work towards these improvements!

**Comment by tpsvoets** [comment]
@shashichilappagari Thanks a lot for your response! Your code works for my project and I'm very happy about it. Big kudos to you. @glenn-jocher Great to hear you plan to implement changes to improve YOLOv8 further. Perhaps the code of @shashichilappagari can help more people.

**Comment by shashichilappagari** [comment]
@tpsvoets We are so glad to hear that you found our code helpful. It makes all our efforts worthwhile.

**Comment by DivyeshJayswal** [comment]
Hello @glenn-jocher 
I had the same issue. I trained YOLOv8 custom object detection model, and exported it for edge tpu. It doesn't provide proper results(detections) while the same model in pt format give proper results as i expected. I retrained model with larger dataset but couldn't resolve the issue. The same model with .pt works fine. For more info. i trained nano model for custom object detection and im using the lastest version of ulralytics on google colab.

**Comment by Ghezzo98** [comment]
> @hlreicha and @tpsvoets Quantized tflite models need to be exported properly so as not to lose accuracy. We have a fork of ultralytics repo where we fixed these issues. We made a simple colab notebook that you can try your checkpoints on: https://colab.research.google.com/drive/1yjCEwwFuMKvFJceSDfyWrUWOSfvLlPjl?usp=sharing Please let us know if it helps or if you have any trouble running the notebook.

Amazing notebook! you saved my day.
But I'm facing a problem rn:
I can make predictions without any problems but I'm not able to do any type of evaluation (like confusion matrix, ecc...)
When I try do to model.val(...) I get
"
IndexError: list index out of range
"
in the val.py file. (line error:    "category_id": self.class_map[int(p[5])]   )

Do you have any hint on how to resolve this?

**Comment by Ghezzo98** [comment]
> @Ghezzo98 Glad to know that our notebook helped. Can you please let us know how you ran the eval? Also, is it the standard model or a custom model?

Thank you for your quick response!
I trained a Custom model on yoloV8m, then I quantized it with your colab repository and I did inference with 
"
!python dg_predict.py --weights 'best_saved_model/best_integer_quant.tflite'  --source datasets/test/images/00001.jpg --device cpu --imgsz 640
"
and it works just fine!

Then I want to try doing the evaluation with:
"
model = YOLO('best_saved_model/best_int8.tflite', task = 'detect')
model.val(data = 'data.yaml', conf=0.2, iou=0.5,  split = 'val')
"
but i got the error I wrote before... 

I tried also:
"
!python dg_val.py --weights 'best_saved_model/best_integer_quant.tflite' --data 'test_prova/' --device cpu --imgsz 640
"

But I got:
"
WARNING ⚠️ Metadata not found for 'model=/content/drive/MyDrive/quant_degirum/best_saved_model/best_int8.tflite'
.
.
.
FileNotFoundError: Dataset 'test_prova/' for task=detect not found ❌

**Comment by Ghezzo98** [comment]
Another thing to be mentioned is that when I do inference (with dg_predict.py) I lose the names of all my classes, i got like "class_1", "class_2", ecc... as output. I checked and they're right, but they don't have the original names...

**Comment by shashichilappagari** [comment]
> > @Ghezzo98 Glad to know that our notebook helped. Can you please let us know how you ran the eval? Also, is it the standard model or a custom model?
> 
> Thank you for your quick response! I trained a Custom model on yoloV8m, then I quantized it with your colab repository and I did inference with " !python dg_predict.py --weights 'best_saved_model/best_integer_quant.tflite' --source datasets/test/images/00001.jpg --device cpu --imgsz 640 " and it works just fine!
> 
> Then I want to try doing the evaluation with: " model = YOLO('best_saved_model/best_int8.tflite', task = 'detect') model.val(data = 'data.yaml', conf=0.2, iou=0.5, split = 'val') " but i got the error I wrote before...
> 
> I tried also: " !python dg_val.py --weights 'best_saved_model/best_integer_quant.tflite' --data 'test_prova/' --device cpu --imgsz 640 "
> 
> But I got: " WARNING ⚠️ Metadata not found for 'model=/content/drive/MyDrive/quant_degirum/best_saved_model/best_int8.tflite' . . . FileNotFoundError: Dataset 'test_prova/' for task=detect not found ❌ "

@Ghezzo98 evaluating using dg_val is the right approach as you need to pass extra parameters to evaluate when exported using our method. The error you are getting looks like it is unable to find the val data in the folder you mentioned.

**Comment by Ghezzo98** [comment]
> > > @Ghezzo98 Glad to know that our notebook helped. Can you please let us know how you ran the eval? Also, is it the standard model or a custom model?
> > 
> > 
> > Thank you for your quick response! I trained a Custom model on yoloV8m, then I quantized it with your colab repository and I did inference with " !python dg_predict.py --weights 'best_saved_model/best_integer_quant.tflite' --source datasets/test/images/00001.jpg --device cpu --imgsz 640 " and it works just fine!
> > Then I want to try doing the evaluation with: " model = YOLO('best_saved_model/best_int8.tflite', task = 'detect') model.val(data = 'data.yaml', conf=0.2, iou=0.5, split = 'val') " but i got the error I wrote before...
> > I tried also: " !python dg_val.py --weights 'best_saved_model/best_integer_quant.tflite' --data 'test_prova/' --device cpu --imgsz 640 "
> > But I got: " WARNING ⚠️ Metadata not found for 'model=/content/drive/MyDrive/quant_degirum/best_saved_model/best_int8.tflite' . . . FileNotFoundError: Dataset 'test_prova/' for task=detect not found ❌ "
> 
> @Ghezzo98 evaluating using dg_val is the right approach as you need to pass extra parameters to evaluate when exported using our method. The error you are getting looks like it is unable to find the val data in the folder you mentioned.

I just checked and now it works! I just did a typo in the yaml file... 
Do you have any clues why the output use different label names?

**Comment by shashichilappagari** [comment]
> Another thing to be mentioned is that when I do inference (with dg_predict.py) I lose the names of all my classes, i got like "class_1", "class_2", ecc... as output. I checked and they're right, but they don't have the original names... ![00001](https://private-user-images.githubusercontent.com/94114114/333228674-99a579f9-224b-42a5-aa25-7d5ae45da769.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzY3NTAsIm5iZiI6MTcxNjQ3NjQ1MCwicGF0aCI6Ii85NDExNDExNC8zMzMyMjg2NzQtOTlhNTc5ZjktMjI0Yi00MmE1LWFhMjUtN2Q1YWU0NWRhNzY5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE1MDA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MzZmYmE2NmNjNzFiZmM2ZmQ2NGE3OTM0YTQzNzE0ZDFmMjRkNDk5YWQ1ZWU2MDc2N2E4ZGEwMjkzM2EzMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UgX58B8vBjE6csWkLeCgaYZDrBvCEq9-J5LujRUa020)

@Ghezzo98 This is a known issue on our side as we export without the metadata. We have our own way of adding metadata when running inference using our pysdk. If this is a crucial feature for you, I can ask someone from my team to see if it can be added.

**Comment by Ghezzo98** [comment]
> > Another thing to be mentioned is that when I do inference (with dg_predict.py) I lose the names of all my classes, i got like "class_1", "class_2", ecc... as output. I checked and they're right, but they don't have the original names... ![00001](https://private-user-images.githubusercontent.com/94114114/333228674-99a579f9-224b-42a5-aa25-7d5ae45da769.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzY3NTAsIm5iZiI6MTcxNjQ3NjQ1MCwicGF0aCI6Ii85NDExNDExNC8zMzMyMjg2NzQtOTlhNTc5ZjktMjI0Yi00MmE1LWFhMjUtN2Q1YWU0NWRhNzY5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE1MDA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MzZmYmE2NmNjNzFiZmM2ZmQ2NGE3OTM0YTQzNzE0ZDFmMjRkNDk5YWQ1ZWU2MDc2N2E4ZGEwMjkzM2EzMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UgX58B8vBjE6csWkLeCgaYZDrBvCEq9-J5LujRUa020)
> 
> @Ghezzo98 This is a known issue on our side as we export without the metadata. We have our own way of adding metadata when running inference using our pysdk. If this is a crucial feature for you, I can ask someone from my team to see if it can be added.

It is for a university project, so it's not crucial :) 
But if you will include this feature in the future, just let me know please.
Thank you for everything!

Best <3

**Comment by shashichilappagari** [comment]
@Ghezzo98 Sure, if we add the feature we will let you know. You can also take a look at our PySDK at https://github.com/DeGirum/PySDKExamples. It is focused on ease of use and deployment and you may find it useful for your projects.
