### ISSUE TITLE
Ultralytics for Jetson jetpack 4.5?

### ISSUE THREAD

**Issue by M1ke002** [ultralytics/ultralytics#3444]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, i want to use yolov8 for my Jetson Xavier which has python 3.6.9 and Jetpack 4.5.1 installed. I checked the dockerfile-jetson and saw that it uses: FROM nvcr.io/nvidia/l4t-pytorch:r35.2.1-pth2.0-py3 which is the pytorch docker image for Jetpack 5.1. So I wonder if it also works for Jetpack 4.5.1? I see that NVIDIA L4T PyTorch has an image for JetPack 4.5, but the pytorch and torchvision version is older (PyTorch v1.7.0 and torchvision v0.8.0).
Thanks

**Comment by glenn-jocher** [comment]
@M1ke002 hi! Thank you for your interest in using YOLOv8 with your Jetson Xavier. While the official `dockerfile-jetson` uses an image for JetPack 5.1, it may still work with JetPack 4.5.1. 

Please note that the PyTorch and torchvision versions in the JetPack 4.5 image are older (PyTorch v1.7.0 and torchvision v0.8.0) compared to the versions used in the JetPack 5.1 image. 

You can try using the JetPack 4.5 image and see if it works for your specific setup. If you encounter any issues, please let us know and we'll be happy to assist you further.

Best of luck with your project!
