### ISSUE TITLE
Automatic validation after training although val: False in default.yaml

### ISSUE THREAD

**Issue by noel077** [ultralytics/ultralytics#3446]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Validation

### Bug

As described in the title, while training, after completing all epochs, the validation is automatically introduced. Although, in the default.yaml file I have set "val: False". If I understand it right, this should be the option to exactly deactivate this validation, right?

I am running the code this way:

```
model = YOLO()
training = model.train(cfg=DIR_cfg)
```

This is my default.yaml file
```
task: detect  # (str) YOLO task, i.e. detect, segment, classify, pose
mode: train  # (str) YOLO mode, i.e. train, val, predict, export, track, benchmark

# Train settings -------------------------------------------------------------------------------------------------------
model: yolov8n.pt # (str, optional) path to model file, i.e. yolov8n.pt, yolov8n.yaml
data: ...\data.yaml # (str, optional) path to data file, i.e. coco128.yaml
epochs: 3  # (int) number of epochs to train for
patience: 50  # (int) epochs to wait for no observable improvement for early stopping of training
batch: 16  # (int) number of images per batch (-1 for AutoBatch)
imgsz: 640  # (int) size of input images as integer or w,h
save: True  # (bool) save train checkpoints and predict results
save_period: 1 # (int) Save checkpoint every x epochs (disabled if < 1)
cache: False  # (bool) True/ram, disk or False. Use cache for data loading
device:  # (int | str | list, optional) device to run on, i.e. cuda device=0 or device=0,1,2,3 or device=cpu
workers: 8  # (int) number of worker threads for data loading (per RANK if DDP)
project:  # (str, optional) project name
name:  # (str, optional) experiment name, results saved to 'project/name' directory
exist_ok: False  # (bool) whether to overwrite existing experiment
pretrained: True  # (bool | str) whether to use a pretrained model (bool) or a model to load weights from (str)
optimizer: auto  # (str) optimizer to use, choices=[SGD, Adam, Adamax, AdamW, NAdam, RAdam, RMSProp, auto]
verbose: True  # (bool) whether to print verbose output
seed: 0  # (int) random seed for reproducibility
deterministic: True  # (bool) whether to enable deterministic mode
single_cls: False  # (bool) train multi-class data as single-class
rect: False  # (bool) rectangular training if mode='train' or rectangular validation if mode='val'
cos_lr: False  # (bool) use cosine learning rate scheduler
close_mosaic: 0  # (int) disable mosaic augmentation for final epochs
resume: False  # (bool) resume training from last checkpoint
amp: True  # (bool) Automatic Mixed Precision (AMP) training, choices=[True, False], True runs AMP check
fraction: 1.0  # (float) dataset fraction to train on (default is 1.0, all images in train set)
profile: False  # (bool) profile ONNX and TensorRT speeds during training for loggers
# Segmentation
overlap_mask: True  # (bool) masks should overlap during training (segment train only)
mask_ratio: 4  # (int) mask downsample ratio (segment train only)
# Classification
dropout: 0.0  # (float) use dropout regularization (classify train only)

# Val/Test settings ----------------------------------------------------------------------------------------------------
val: False  # (bool) validate/test during training
split:   # (str) dataset split to use for validation, i.e. 'val', 'test' or 'train'
save_json: False  # (bool) save results to JSON file
save_hybrid: False  # (bool) save hybrid version of labels (labels + additional predictions)
conf:  # (float, optional) object confidence threshold for detection (default 0.25 predict, 0.001 val)
iou: 0.7  # (float) intersection over union (IoU) threshold for NMS
max_det: 300  # (int) maximum number of detections per image
half: False  # (bool) use half precision (FP16)
dnn: False  # (bool) use OpenCV DNN for ONNX inference
plots: True  # (bool) save plots during train/val
```

I was thinking about omitting the path for the validation in the data.yaml file. But this leads to an error since train and val paths both always needs to be specified in a data.yaml file.

Moreover, I think this is a problem since the results of the automatic validation are not returned. Meaning that even if I want to perform a validation after the training, I have to perform the validation twice because the validation results of the automatic validation are not saved.

Thank you in advance!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@noel077 hi there,

Thank you for bringing this to our attention. In YOLOv8, the `val` parameter in the `default.yaml` file is indeed used to control whether validation is performed during training. However, it seems that there is a bug where validation is still being conducted even if `val: False` is set.

To mitigate this issue, you can explicitly set the `val` parameter to `True` and provide a valid validation dataset path in the `data.yaml` file. This way, the automatic validation will be performed, and the validation results will be saved.

Regarding the duplication of validation, I apologize for the inconvenience. The automatic validation results are not currently returned, so you will need to perform an additional validation after the training to obtain the validation results.

I want to assure you that our team takes user feedback seriously, and we'll work towards addressing this issue in a future update. In the meantime, I appreciate your understanding and patience.

If you have any further questions or need assistance, please feel free to ask.

Best regards,
Glenn Jocher

**Comment by glenn-jocher** [comment]
@noel077 final validation is always performed. `val=False` will disable validation after every training epoch.

**Comment by bavo96** [comment]
Hi @glenn-jocher, Is there any way to configure the final validation configuration when finish training? Because for my `model.val()` for example I have a configuration of `batch=64`, but the validation in the `model.train()` has `batch=128` (I think it automatically consumes all of my GPU memory).

**Comment by glenn-jocher** [comment]
Hi there! 👋

Great question! The final validation follows the `batch` value specified under the training settings by default. However, if you need a different setting for the final validation, you might consider manually setting your desired validation configuration right after training. Here's an example:

After training:
```python
model = YOLO('yolov8n.pt').train(...)  # your training config
model.val(batch=64)  # Manually set batch size for validation as needed
```

Currently, directly configuring the final validation batch size within `model.train()` isn't supported. The workaround is to explicitly specify your validation settings and call `model.val()` with your preferences after the training completes.

Hope this helps! Let us know if you have more questions. 😊

**Comment by bavo96** [comment]
Hi @glenn-jocher, thanks for the suggestion but this doesn't help in my situation. After the model ends training, it performs the final validation and causes my computer to crash (the validation process got killed) as in the image below (because the validation consumes all of the GPU memory).
![image](https://github.com/ultralytics/ultralytics/assets/27908949/ab575640-e6ca-4be5-9693-5be5d832ddb4)
Should we consider a way to configure the validation process (per N epochs or the final one) in the training process?

**Comment by glenn-jocher** [comment]
Hi there! 👋

I'm sorry to hear about the trouble you're experiencing with the final validation step. It sounds like a feature to configure validation settings directly during the training process would indeed be beneficial in cases like yours, where resource management is crucial.

While we currently don't have an out-of-the-box feature to configure the final validation batch size or disable it within `model.train()`, your feedback is valuable and could lead to improvements in future versions of Ultralytics YOLO. ☺️

As a temporary solution, if modifying the source code is an option for you, you could adjust the validation parameters within the training script or function where the final validation call is made. This might help prevent such crashes due to out-of-memory errors.

Meanwhile, please keep an eye on our updates, and thank you for bringing this to our attention!

```python
# Example: Adjusting validation parameters within the training script
# Model training:
model.train()

# Modify the script/function where the final validation is called to manage GPU usage effectively
```

Thank you for your patience and understanding. 🙏
