### ISSUE TITLE
No information on which keypoint/segmentation belong to which class

### ISSUE THREAD

**Issue by SujithChristopher** [ultralytics/ultralytics#3449]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

During inference the results from the model do not have information regarding which key-point/segmentation belongs to which class

I have also discussed it in #1906 , and thanking @glenn-jocher for valuable inputs.

But recently I have tried both Pose (Yolov8n-pose) and Segmentation (Yolov8n-seg) models.

Both of them are detecting the segments/pose-estimation and giving out key-points/masks (for multi-class), but there is no information on which box/key-points/segmentation belongs to which class.

![image](https://github.com/ultralytics/ultralytics/assets/50609700/e1192fba-cc60-4d30-84ba-4dd6e2e0d8e0)

As in the website in the picture it shows, that it also detect the class, but I do not find that information during inference.

I tried running the inference for the example-bus image

![image](https://github.com/ultralytics/ultralytics/assets/50609700/3bcc0bd2-248e-4783-8efa-284e53ade7c3)

This only shows all the names it has been trained., there is no corresponding ID for the mask/boxes

![image](https://github.com/ultralytics/ultralytics/assets/50609700/70a074b5-3810-4776-b66a-ad62d5d8a94c)

If this feature is not available, I kindly request and I strongly believe, this feature should be included, which makes YOLO network more useful.

Thanks.

If I'm missing anything, please let me know, I will correct my code.

### Environment

Ultralytics YOLOv8.0.123  Python-3.10.11 torch-2.0.0+cpu CPU

### Minimal Reproducible Example

```

model = YOLO('yolov8n-seg.pt')  # load a pretrained model (recommended for training)
results = model('https://ultralytics.com/images/bus.jpg')  # predict on an image
results[0].boxes
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SujithChristopher** [comment]
I missed the information on `results[0].boxes.cls` this solves my issue, thanks

**Comment by glenn-jocher** [comment]
Hi @SujithChristopher! Thank you for bringing up this issue and discussing it in #1906. I'm glad to hear that you found the solution to your problem with `results[0].boxes.cls`.

In YOLOv8, the information regarding which key-point/segmentation belongs to which class is available through the `results[0].boxes.cls` attribute. This attribute provides the class labels associated with the predicted bounding boxes, key-points, or segmentations.

I'm sorry if this information was not initially clear. We appreciate your feedback, and we continuously strive to improve the YOLOv8 documentation and user experience.

If you have any further questions or need assistance with anything else related to YOLOv8, please feel free to ask. We're here to help!

Best regards,

Glenn Jocher
