### ISSUE TITLE
The detection result is None

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/ultralytics#345]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

When I execute `pip install ultralytics==8.0.5`, the detection result is None.

```python
from ultralytics import YOLO

model = YOLO('yolov8n.pt')
results = model("https://ultralytics.com/images/bus.jpg")
print(results)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Kang812** [comment]
![image](https://user-images.githubusercontent.com/69283127/212450195-b1589e2d-5003-4ef8-8ac8-d84f91aef6f9.png)

Let's do it like this ~!!

**Comment by Zengyf-CVer** [comment]
@Kang812 Thank you very much.
