### ISSUE TITLE
[PR] Update YOLOv8-ONNXRuntime-CPP

### ISSUE THREAD

**Issue by DennisJcy** [ultralytics/ultralytics#3454]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hello
I push my deploy code to this repo,add the yolov8-onnxruntime-cpp project which i have tested OK.

![Snipaste_2023-06-29_09-20-48](https://github.com/ultralytics/ultralytics/assets/106725464/4358c599-46b6-4b6d-861b-a83181ff469a)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by DennisJcy** [comment]
https://github.com/ultralytics/ultralytics/pull/3455

**Comment by glenn-jocher** [comment]
@DennisJcy hi there,

Thank you for your contribution and for sharing your work on the YOLOv8-ONNXRuntime-CPP project. We appreciate your effort in expanding the capabilities of YOLOv8.

I just wanted to clarify that this PR is submitted to the Ultralytics YOLOv8 repository, not the YOLOv5 repository. Our focus here is solely on YOLOv8.

I've reviewed your description and the screenshot you provided. It seems that you have added the yolov8-onnxruntime-cpp project, which you have successfully tested.

If I understand correctly, you have integrated the ONNX Runtime library with the YOLOv8 model, which allows for faster inference and deployment in C++. This is a valuable addition, as it enables YOLOv8 to be used in CPP-based projects efficiently.

Regarding your request to update the YOLOv8-ONNXRuntime-CPP project, could you please provide more details about the specific updates you are suggesting? It would be helpful to know the scope and purpose of these changes.

Once we have a clear understanding of your proposed updates, we can analyze them further and discuss the best way to integrate them into the YOLOv8 project.

Thank you once again for your contribution, and we look forward to your response.

Best regards,
Glenn Jocher

**Comment by DennisJcy** [comment]
Good morning!
I add the following updates.The repo/main/examples have realize the ort inference in python and opencv's dnn inference + opencv's postprocess.But there is a fatser and  more frequently-used way to depoly,that is my specific updates:using onnxruntime inference and opencv's postprocess all in cpp.
1. more faster
2. support for cuda
3. use templeate function which is frendly for fp16 supporting

**Comment by DennisJcy** [comment]
I have add more descriptions in the PR readme.md,hope for your correction

**Comment by glenn-jocher** [comment]
Dear @DennisJcy,

Thank you for your contribution and the additional descriptions you have provided in the PR's readme.md file. We appreciate your effort in improving the documentation and ensuring its accuracy.

After reviewing your PR, it seems that you have made updates to optimize the deployment of the YOLOv8 model. These updates include the following:

1. Improved Performance: By integrating the ONNX Runtime library with the YOLOv8 model, you have achieved faster inference, enabling efficient deployment of the model.

2. CUDA Support: Your updates also include support for CUDA, which allows for GPU acceleration and further enhances the performance of YOLOv8.

3. Template Function: You have implemented a template function, which facilitates support for floating-point 16 (FP16) data types. This ensures compatibility with hardware that supports half-precision computations.

These updates provide a faster and more commonly used way to deploy YOLOv8, leveraging the benefits of ONNX Runtime and OpenCV's post-processing capabilities, all within a C++ environment.

Once again, we appreciate your efforts and the clear explanations provided in the readme.md file. We will carefully review your updates and work towards incorporating them into the YOLOv8 project.

Thank you for your patience, and please let us know if you have any further questions or suggestions.

Best regards,
Glenn Jocher

**Comment by DennisJcy** [comment]
Yes,that's what I mean.
Waiting for your correction!

**Comment by DennisJcy** [comment]
Hello, I add more description on the readme.md, and fix a few bugs.

**Comment by glenn-jocher** [comment]
@DennisJcy hello,

Thank you for providing additional descriptions in the readme.md file and for fixing some bugs. We appreciate your efforts to improve the documentation and ensure the stability of the YOLOv8 project.

It would be helpful if you could provide specific details about the descriptions you have added and the bugs you have fixed. This will allow us to review your changes more effectively and provide appropriate feedback.

Once we have reviewed your updates and confirmed that they align with the goals of the YOLOv8 project, we will work towards merging them into the repository.

Thank you for your contribution, and we look forward to your response.

Best regards,
Glenn Jocher

**Comment by DennisJcy** [comment]
# 1.descriptions add: Added special dependencies needed to build the c++ project like a requirement
## Dependency

| Dependency              | version  |
| ----------------------- | -------- |
| Onnxruntime-win-x64-gpu | >=1.14.1 |
| Opencv                  | >=4.0.0  |
| C++                     | >=17     |

Version dependency of c++ is not necessary,the version requirement here is due to the use of c++17's advanced feature filesystem.

# 2.fix bugs
That's my mistake.Thr PR code is cutted from my project.So the  inference.h file  missing a item `#include 
"onnxruntime_cxx_api.h" ` and main.cpp included wrong item ` #include "inference.h" `  instead of ` #include "DCSP_ONNX.h" `
![image](https://github.com/ultralytics/ultralytics/assets/106725464/f4e7573b-631c-4518-b0c7-fe0fa2669dcd)

![image](https://github.com/ultralytics/ultralytics/assets/106725464/6fee4016-105d-43b2-b56a-5848e430cb3b)
I changed the data structure without changing the initial way
![image](https://github.com/ultralytics/ultralytics/assets/106725464/d65e8c71-5958-408c-8fce-684c6e190ea3)

**Comment by glenn-jocher** [comment]
@DennisJcy hi there,

Thank you for your contribution and for providing the descriptions and bug fixes in your PR for YOLOv8. Here is the summary of the changes:

1. Descriptions:
   - Added special dependencies required to build the C++ project, including Onnxruntime-win-x64-gpu (version >=1.14.1), OpenCV (version >=4.0.0), and C++ (version >=17).
   - The version requirement for C++ is due to the use of advanced features from C++17, specifically the filesystem component.

2. Bug Fixes:
   - It was discovered that some code was missing from the PR. The `inference.h` file was missing the line `#include "onnxruntime_cxx_api.h"`, and in `main.cpp`, the incorrect line `#include "inference.h"` was included instead of `#include "DCSP_ONNX.h"`.
   - You made changes to the data structure without modifying the initial method.

Regarding the bug fixes, we appreciate your attention to detail in correcting these issues and ensuring the code is properly included and structured for successful compilation and execution.

Again, thank you for your contribution to YOLOv8, and we will review your changes and work towards merging them into the repository. If you have any further questions or suggestions, please let us know.

Best regards,
Glenn Jocher
