### ISSUE TITLE
May I ask  how to convert the tracking into tensorrt, so that the engine model can be called?

### ISSUE THREAD

**Issue by orderer0001** [ultralytics/ultralytics#3468]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

May I ask the author, how to convert the tracking into tensorrt, so that the engine model can be called?Is there an example of adding tensorrt code

**Comment by glenn-jocher** [comment]
Hi @orderer0001,

Converting the YOLOv8 tracking model into TensorRT to create an engine model that can be called is not currently supported in the Ultralytics YOLOv8 repository.

However, you can explore using the [torch2trt](https://github.com/NVIDIA-AI-IOT/torch2trt) library to convert your YOLOv8 model (including the tracking functionality) into a TensorRT engine. Torch2trt provides functions to convert PyTorch models to TensorRT engines, leveraging the benefits of both frameworks.

To use torch2trt, you would need to install the library and follow their documentation for converting YOLOv8 models. Note that this process may require some additional code modifications to ensure compatibility with torch2trt.

Please keep in mind that the Ultralytics YOLOv8 repository primarily focuses on providing training, validation, prediction, export, tracking, and benchmarking functionalities using PyTorch. The conversion to TensorRT is outside the scope of this repository, but torch2trt is an excellent resource to explore for this purpose.

Let me know if you have any further questions. I'm here to help!

Best regards,
Glenn Jocher

**Comment by bit-scientist** [comment]
@orderer0001 hi, you may find this issue #2917 (opened by me) useful to have an idea on how to approach your problem. In short, you just use the `export` by ultralytics on your detection `.pt` model and directly replace it in the tracking code.

**Comment by glenn-jocher** [comment]
Hi @bit-scientist,

Thank you for reaching out! If you want to integrate the tracking functionality of YOLOv8 into your project, you can follow these steps:

1. Ensure that you have a trained YOLOv8 detection model (`.pt` file) that performs object detection accurately.

2. Use the `export` command provided by Ultralytics to convert your YOLOv8 detection model into a deployment-ready format.

3. Obtain the exported model file (e.g., `yolov8.pt`) and replace the existing detection model in your tracking code with this exported model.

By doing this, you can leverage the tracking capability of YOLOv8 using the exported model. It allows you to detect and track objects in real-time.

If you encounter any issues or have further questions, feel free to ask. I'm here to assist you!

Best regards,
Glenn Jocher

**Comment by orderer0001** [comment]
> 你好@bit-scientist,
> 
> 感谢您伸出援手！如果您想将YOLOv8的跟踪功能集成到您的项目中，可以按照以下步骤操作：
> 
> 1. 确保您拥有经过训练的 YOLOv8 检测模型（`.pt`文件），可以准确执行对象检测。
> 2. 使用`export`Ultralytics 提供的命令将 YOLOv8 检测模型转换为可部署的格式。
> 3. 获取导出的模型文件（例如`yolov8.pt`）并用此导出的模型替换跟踪代码中的现有检测模型。
> 
> 通过这样做，您可以使用导出的模型来利用 YOLOv8 的跟踪功能。它允许您实时检测和跟踪对象。
> 
> 如果您遇到任何问题或有其他疑问，请随时提问。我是来帮助你的！
> 
> 最好的问候， 格伦·乔彻

thank you for your reply. I can already use the onnx file to load into the model, and then call the tracker through the model to get the result I want (model.track(frame,persist=Ture)). But now I want to load the engine file to the model and call the model's tracker like using onnx. Always get an error: 'utf-8' codec can't decode.....

**Comment by orderer0001** [comment]
> @orderer0001你好，你可能会发现这个问题#2917（由我打开）对于了解如何解决你的问题很有用。简而言之，您只需`export`在检测`.pt`模型上使用 by ultralytics 并直接在跟踪代码中替换它即可。

thank you for your reply. I can already use the onnx file to load into the model, and then call the tracker through the model to get the result I want (model.track(frame,persist=Ture)). But now I want to load the engine file to the model and call the model's tracker like using onnx. Always get an error: 'utf-8' codec can't decode.....

**Comment by orderer0001** [comment]
model = YOLO('xxx.oonx') ，Can it be changed  model=YOLO('xxxx.engine')

**Comment by bit-scientist** [comment]
Hi @orderer0001, I once again suggest you reading #2917, you can surely find what you need there. Review [export](https://docs.ultralytics.com/modes/export/#usage-examples) and all you need to do:
```
model = YOLO("yolov8n.pt") # replace with your .pt model
model.export(format="engine", device="0") # see other args in export above
```
Then, go ahead and use it right away just like you always do with .pt or .onnx file. Good luck!

**Comment by orderer0001** [comment]
I already have an engine model, but after I load it, the model can't use the tracker. I use the python version of yolov8.

---- Replied Message ----
| From | ***@***.***> |
| Date | 07/13/2023 15:08 |
| To | ultralytics/ultralytics ***@***.***> |
| Cc | orderer0001 ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [ultralytics/ultralytics] May I ask how to convert the tracking into tensorrt, so that the engine model can be called? (Issue #3468) |

Hi @orderer0001, I once again suggest you reading #2917, you can surely find what you need there. Review export and all you need to do:

model = YOLO("yolov8n.pt") # replace with your .pt model
model.export(format="engine", device="0") # see other args in export above


Then, go ahead and use it right away just like you always do with .pt or .onnx file. Good luck!

**Comment by bit-scientist** [comment]
Then leave the whole code and the traceback for us to debug.

**Comment by orderer0001** [comment]
> 你用什么命令将pt模型导出到.engine？
> 
> 此外，留下整个代码和回溯给我们调试。

I used the tensorrt tool trtexec to export the engine, and the model has no problem. After using the engine to load the model :`model = YOLO("xxx.engine") `, when running `mode.track(img,...)` an error will be reported utf-8 codec can't decode........But using this it works fine：`model = YOLO("xxx.onnx").       mode.track(img,...)`,

**Comment by bit-scientist** [comment]
you are supposed to use yolo's in-house export function for that which is stated in the comment #2917. Try using it and see if the error persists.

**Comment by orderer0001** [comment]
> 您应该将yolo的内部导出功能用于评论#2917中所述的功能。尝试使用它，看看错误是否仍然存在。

If I use the export function inside yolo, report an error and need to install onnxsim, but onnxsim cannot be installed on my jetson, and always report an error. I use pip install onnx-simplifier, but it cannot be installed,

**Comment by bit-scientist** [comment]
Well, that's what you should've come first with. Open another issue detailing this situation and hopefully someone will help you.

**Comment by glenn-jocher** [comment]
Hi @orderer0001,

I apologize for the confusion. If you are encountering issues with the export function of YOLOv8 and are unable to install the required package onnxsim, I recommend opening a new issue on the YOLOv8 GitHub repository to seek assistance from the community and the developers.

Please provide the details of the error you are facing when installing onnxsim and any relevant information about your environment (e.g., Jetson). This will help the community and developers provide targeted solutions to your problem.

Thank you for your patience, and I hope the issue gets resolved soon.

Best regards,
Glenn Jocher
