### ISSUE TITLE
 YOLOv8 segmentation results: 'Masks' object has no attribute 'xy'

### ISSUE THREAD

**Issue by louisfacun** [ultralytics/ultralytics#3469]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I'm using Ultralytics YOLOv8.0.28 and I have this code for prediction:

```
model = YOLO("_weights/yolov8-best3.pt")
results = model.predict(source=image_path,
                        imgsz=640,
                        iou=0.6,
                        conf=0.6,
                        retina_masks=True,
                        )

masks = results[0].masks
print(masks.xy)
```

However it says:

```
AttributeError: 
            'Masks' object has no attribute 'xy'. Valid 'Masks' object attributes and properties are:

            Attributes:
                masks (torch.Tensor): A tensor containing the detection masks, with shape (num_masks, height, width).
                orig_shape (tuple): Original image size, in the format (height, width).

            Properties:
                segments (list): A list of segments which includes x,y,w,h,label,confidence, and mask of each detection masks.
```

But according to the docs it says:

```
results = model(inputs)
masks = results[0].masks  # Masks object
masks.xy  # x, y segments (pixels), List[segment] * N
masks.xyn  # x, y segments (normalized), List[segment] * N
masks.data  # raw masks tensor, (N, H, W) or masks.masks 
```

So I had to use this, and pixelized it myself:
```
results[0].masks.segments[0]
```
Why I can't use xy or xyn?

### Environment

Ultralytics YOLOv8.0.28 🚀 Python-3.10.11 torch-2.0.1+cu117 CPU

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@louisfacun I noticed your ultralytics package version is `8.0.28` which is outdated, please use the latest version and try again. :)
BTW here's my result with the latest version and it works to me.
![pic-selected-230630-1542-32](https://github.com/ultralytics/ultralytics/assets/61612323/8cbcd67d-2f10-4076-b766-918b7876c672)

**Comment by louisfacun** [comment]
Outdated installation, thank you ^_^

**Comment by glenn-jocher** [comment]
Hi @louisfacun, it seems that you are using an outdated version of the Ultralytics YOLOv8 package. I recommend updating to the latest version to resolve the issue you are facing. Once you have the latest version installed, you should be able to use the `xy` and `xyn` attributes of the `Masks` object as mentioned in the documentation. If you need any further assistance, please let me know. Thanks!

**Comment by pythonworkspy** [comment]
> Hi @louisfacun, it seems that you are using an outdated version of the Ultralytics YOLOv8 package. I recommend updating to the latest version to resolve the issue you are facing. Once you have the latest version installed, you should be able to use the `xy` and `xyn` attributes of the `Masks` object as mentioned in the documentation. If you need any further assistance, please let me know. Thanks!

Hi Glenn, i need to get  polygone coordinates for draw polylines.  lastest version of ultralytics there is not parameters of  'result.masks.segments'.  I need to use result.masks.xy and result.masks.xyn for the get coordinates of polygone. is there a any example code ?

`        segmentation_contours_idx = []
        for seg in result.masks.segments:
            # contours
            seg[:, 0] *= width
            seg[:, 1] *= height
            segment = np.array(seg, dtype=np.int32)
            segmentation_contours_idx.append(segment)`

the code which i want to change for segments.


very thanks for your reply.

**Comment by pythonworkspy** [comment]
>         segmentation_contours_idx = []
        for seg in result.masks.segments:
            # contours
            seg[:, 0] *= width
            seg[:, 1] *= height
            segment = np.array(seg, dtype=np.int32)
            segmentation_contours_idx.append(segment)
