### ISSUE TITLE
YOLOv8-1.0

### ISSUE THREAD

**Issue by lagomff** [ultralytics/ultralytics#3470]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Dear developer, I would like to know when version 1.0 of yolov8 will be released

**Comment by glenn-jocher** [comment]
@lagomff dear user,

Thank you for your interest in YOLOv8! We appreciate your inquiry about the release date for version 1.0 of YOLOv8. 

At the moment, the Ultralytics team is actively maintaining and updating the YOLOv8 repository. However, we do not have a specific release date for version 1.0. We continuously strive to improve and enhance our models, and the development of new features and improvements is an ongoing process.

Please stay tuned to the YOLOv8 repository for updates and announcements regarding new releases. We encourage you to regularly check the repository and our documentation for the latest information on YOLOv8.

If you have any further questions or need assistance with YOLOv8, please do not hesitate to ask. We are here to help!

Thank you again for your support and interest in YOLOv8.

Best regards,
Glenn Jocher
