### ISSUE TITLE
 May I ask yolov8 how to set up a target tracking system for tracking people or car

### ISSUE THREAD

**Issue by kola515** [ultralytics/ultralytics#3471]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

yolov8 how to set up a target tracking system for tracking people or car?

**Comment by skyprince999** [comment]
Yolov8 has a native object-tracking system - BOT-Sort and ByteTrack. Both can be enabled by using model.track

**Comment by glenn-jocher** [comment]
@kola515 thank you for your interest in YOLOv8! YOLOv8 indeed provides native object tracking capabilities through the use of two tracking algorithms: BOT-Sort and ByteTrack. To enable object tracking using YOLOv8, you can simply set the `--model.track` flag when running the model in the Command Line Interface (CLI). This allows you to utilize the built-in tracking algorithms to track objects in real-time. Please note that YOLOv8 does not support YOLOv5's tracking algorithm, so using `--model.track` is the recommended approach in this repository. If you have any further questions or need additional assistance, please feel free to ask.
