### ISSUE TITLE
how to get the segments of a specific class?

### ISSUE THREAD

**Issue by Rokessovsky** [ultralytics/ultralytics#3476]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

For example, I have pictures containing a person, a car and a cat. How can I only get the image of the cat(everything else in the image is set to black)? Does the masks object contains the class label of each segment?

**Comment by glenn-jocher** [comment]
@Rokessovsky hi there,

To get the segments of a specific class using YOLOv8, you can utilize the segmentation functionality of the model. YOLOv8 is capable of performing both object detection and segmentation tasks.

In your case, if you have a picture containing a person, a car, and a cat, and you want to extract the segment of the cat while setting everything else in the image to black, you can use the segmentation output of the model. The `mask` attribute of the detected objects contains the pixel-level segmentation masks.

To extract the segment of the cat, you can iterate through the detected objects and filter for the ones that belong to the "cat" class. You can then use the corresponding mask to segment the image and set the pixels outside the cat region to black.

Please note that the `mask` object does not directly contain the class label of each segment. It represents a binary mask where pixels belonging to the detected object are represented by non-zero values.

I hope this helps! Let me know if you have any further questions.

**Comment by Rokessovsky** [comment]
how to filter the mask that belongs to the class without an extra call to Yolo if the mask object does not contain the class label?

**Comment by glenn-jocher** [comment]
@Rokessovsky hi there,

If you want to filter the mask that belongs to a specific class without making an extra call to YOLO, you can achieve this by following these steps:

1. Iterate through the detected objects and examine the class label of each object.
2. Determine if the class label matches the desired class you want to filter (e.g., "cat").
3. If the class label matches, you can consider that object as belonging to the desired class.
4. Use the corresponding mask of the object to extract the segment for that specific class.

The `mask` attribute of the detected objects represents a binary mask where the pixels belonging to each detected object are represented by non-zero values. By filtering for the desired class based on the class label, you can isolate the object of interest and utilize its mask to extract the corresponding segment.

Please note that although the mask object itself does not directly include the class label, you can still filter for the desired class based on the class label associated with each detected object.

I hope this clarifies your question. Feel free to reach out if you have any further inquiries.

**Comment by Rokessovsky** [comment]
I've noticed that there's only class label in the boxes attribute, but the idx of each class there doesn't seem to align with the idx of the masks?
