### ISSUE TITLE
Invalid configuration of MLFlow in Azure ML

### ISSUE THREAD

**Issue by Diegoigerencia** [ultralytics/ultralytics#3477]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I try to run a model of YOLOv8 in azure machine learning and use mlflow, but I have the error:
    
    File "/azureml-envs/azureml_669e3f5d3a028adacb2c7717adab167c/lib/python3.11/site-packages/mlflow/utils/rest_utils.py", line 133, in verify_rest_response raise RestException(json.loads(response.text)) mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'Error': {'Code': 'ValidationError', 'Severity': None, 'Message': 'The request is invalid.', 'MessageFormat': None, 'MessageParameters': None, 'ReferenceCode': None, 'DetailsUri': None, 'Target': None, 'Details': [], 'InnerError': None, 'DebugInfo': None, 'AdditionalInfo': None}, 'Correlation': {'operation': '239feefe1355854189950d9897ad6d5b', 'request': '1d6715de9ed76595'}, 'Environment': 'eastus', 'Location': 'eastus', 'Time': 0', 'ComponentName': 'mlflow', 'error_code': 'INVALID_PARAMETER_VALUE'}
    
  I don't understand what parameter is the problem, below I write the code.

### Environment

- YOLO: Yolov8 ultralytics==8.0.82
- UBUNTU: ubuntu18.04
- Python>=3.7

### Minimal Reproducible Example

import mlflow
import subprocess
import argparse
from pathlib import Path

subprocess.run(["apt-get", "update"])
subprocess.run(["apt-get", "install", "-y", "libgl1-mesa-glx"])

from ultralytics import YOLO

def main(args):
 
    
    pre_model = load_pretrain_model(Path(args.input_data)/'best_28_06_2023.pt')

    model = train_model(pre_model, Path(args.input_data)/'project_001/synthetic_dataset/data.yaml', 
                                                                                   Path(args.output_datastore)/'Train/model_results')
    
  

def load_pretrain_model(input_path):

   
    pre_model = YOLO('yolov8s-p2.yaml').load(input_path)

    return pre_model

def train_model(pre_model, data_train, data_save):

    model = pre_model.train(
            data=str(data_train),
            epochs=1,
            imgsz=640,
            batch=2,
            project=str(data_save)
            )

    return model

def parse_args():
    
    parser = argparse.ArgumentParser()

    parser.add_argument('--input_data', dest='input_data', type=str)

    parser.add_argument('--output_datastore', dest='output_datastore', type=str)

    args = parser.parse_args()

    return args 

if __name__ == "__main__":

    print("\n\n")
    print("Inicializando el entrenamiento...")
    print("*" * 60)

    run = mlflow.start_run()

    run = mlflow.get_run(run.info.run_id)

    # mlflow.set_experiment(experiment_name='dragon-3')
    mlflow.set_experiment(experiment_name=run.info.run_id)

    mlflow.autolog()

    args = parse_args()

    main(args)

    mlflow.end_run()
    print('Finalizando RUN mlflow')

    print("*" * 60)
    print("Entrenamiento finalizado.")
    print("\n\n")

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Diegoigerencia hello,

Thank you for reaching out regarding the invalid configuration of MLFlow in Azure ML when running YOLOv8. 

The error message you provided indicates an issue with a parameter in the MLFlow request. Specifically, it states that the request is invalid and refers to the error code 'INVALID_PARAMETER_VALUE'. Unfortunately, without further information or the specific MLFlow configuration, it is difficult to pinpoint the exact parameter that is causing the problem.

To debug this issue, we recommend checking your MLFlow configuration in Azure ML and ensuring that all parameters are correctly set. Double-check the values of the parameters being used in the MLFlow request, as any incorrect or invalid parameter value could trigger this error.

If you continue to experience difficulties, it may be helpful to consult the Azure ML documentation or seek assistance from the Azure ML support team, as they will have more expertise and familiarity with this specific integration between YOLOv8 and MLFlow in Azure ML.

Thank you for using YOLOv8, and we wish you success in resolving this issue with MLFlow in Azure ML.

Best regards,
The YOLOv8 Team
