### ISSUE TITLE
I can't training the model porperly in windows.

### ISSUE THREAD

**Issue by jkgjhfghdgfscv** [ultralytics/ultralytics#348]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

There is an error when I train a new model like this?This error seems from multiprocessing.But I can train properly using yolov5,I 'm confused why is it.
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

### Environment

Windows11 py3.9 torch==1.2.0

### Minimal Reproducible Example

 def cache_labels(self, path=Path("./labels.cache")):
        # Cache dataset labels, check images and read shapes
        x = {"labels": []}
        nm, nf, ne, nc, msgs = 0, 0, 0, 0, []  # number missing, found, empty, corrupt, messages
        desc = f"{self.prefix}Scanning {path.parent / path.stem}..."
        with Pool(NUM_THREADS) as pool:
            pbar = tqdm(
                pool.imap(verify_image_label,
                          zip(self.im_files, self.label_files, repeat(self.prefix), repeat(self.use_keypoints))),
                desc=desc,
                total=len(self.im_files),
                bar_format=TQDM_BAR_FORMAT,
            )
            for im_file, lb, shape, segments, keypoint, nm_f, nf_f, ne_f, nc_f, msg in pbar:
                nm += nm_f
                nf += nf_f
                ne += ne_f
                nc += nc_f
                if im_file:
                    x["labels"].append(
                        dict(
                            im_file=im_file,
                            shape=shape,
                            cls=lb[:, 0:1],  # n, 1
                            bboxes=lb[:, 1:],  # n, 4
                            segments=segments,
                            keypoints=keypoint,
                            normalized=True,
                            bbox_format="xywh",
                        ))
                if msg:
                    msgs.append(msg)
                pbar.desc = f"{desc} {nf} images, {nm + ne} backgrounds, {nc} corrupt"

        pbar.close()
        if msgs:
            LOGGER.info("\n".join(msgs))
        if nf == 0:
            LOGGER.warning(f"{self.prefix}WARNING ⚠️ No labels found in {path}. {HELP_URL}")
        x["hash"] = get_hash(self.label_files + self.im_files)
        x["results"] = nf, nm, ne, nc, len(self.im_files)
        x["msgs"] = msgs  # warnings
        x["version"] = self.cache_version  # cache version
        try:
            np.save(path, x)  # save cache for next time
            path.with_suffix(".cache.npy").rename(path)  # remove .npy suffix
            LOGGER.info(f"{self.prefix}New cache created: {path}")
        except Exception as e:
            LOGGER.warning(
                f"{self.prefix}WARNING ⚠️ Cache directory {path.parent} is not writeable: {e}")  # not writeable
        return x

### Additional

Nothing

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@jkgjhfghdgfscv hi, can you provide more info? like your training command, and the version of ultralytics package.

**Comment by ichsan2895** [comment]
If you run yolov5, do you give args `--cache disk` ? The args created `*.npy` file in your training dataset.

Maybe delete it will solve the problem hopefully.

**Comment by Dragos-Stan** [comment]
Hi, I'm having the same error, on both W10 and W11. ultralytics 8.05, training on either object detection or segmentation.
Training commands:

import ultralytics
from ultralytics import YOLO
model = YOLO("yolov8m-seg.pt")
model.train(data="data.yaml", epochs=200, imgsz=640, batch=8, name='TrafficDrone_seg_v8m')

Recently (after switching to 8.05) started to loop infinitely over that "freeze_support()" error..
Not related to labels.cache
Thanks for help

**Comment by Laughing-q** [comment]
> import ultralytics
from ultralytics import YOLO
model = YOLO("yolov8m-seg.pt")
model.train(data="data.yaml", epochs=200, imgsz=640, batch=8, name='Train')

Recently (after switching to 8.05) started to loop infinitely over that "freeze_support()" error..
Not related to labels.cache

@Dragos-Stan probably you can try:
```python
import ultralytics
from ultralytics import YOLO
if __name__ == "__main__":
    model = YOLO("yolov8m-seg.pt")
    model.train(data="data.yaml", epochs=200, imgsz=640, batch=8, name='Train')
```

**Comment by Dragos-Stan** [comment]
Thanks :) !

**Comment by asanaa8** [comment]
@jkgjhfghdgfscv same error when using the python sdk on windows 1O but works when using the CLI command
