### ISSUE TITLE
error while doing custom training on data 

### ISSUE THREAD

**Issue by priyatoshanand** [ultralytics/ultralytics#3481]
#AttributeError: 'NoneType' object has no attribute 'keys'
ran this code and got the above error

!cd yolov5 && python train.py --img 320 --batch 16 --epochs 5 --data dataset.yaml --weights yolov5s.pt --workers 2

![Screenshot (3)](https://github.com/ultralytics/ultralytics/assets/56202962/f57e767a-2826-42af-ab79-9ef75c439020)

!cd yolov5 && python train.py --img 320 --batch 16 --epochs 5 --data dataset.yaml --weights yolov5s.pt --workers 2

**Comment by glenn-jocher** [comment]
@priyatoshanand hello! Thank you for reaching out about this error. The `'NoneType' object has no attribute 'keys'` error usually occurs when there is an issue with the dataset configuration.

To resolve this error, please check the following:

1. Make sure that you have provided the correct path to your dataset.yaml file in the `--data` argument. 
2. Ensure that the dataset.yaml file is properly formatted and contains the necessary information for training, such as the path to your training and validation image sets, the number of classes, and the names of the classes. 
3. Double-check that your dataset folder structure matches the paths specified in dataset.yaml.

If the error persists, please provide additional details such as the contents of your dataset.yaml file and any relevant error logs. This will help the community and the Ultralytics team assist you more effectively.

Thank you, and I hope this helps resolve the issue!
