### ISSUE TITLE
how to use ultralytics8.0.0

### ISSUE THREAD

**Issue by simba404** [ultralytics/ultralytics#3483]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

(yolov8) PS E:\Bristol\YOLOV8\ultralytics-main> yolo detect train model=./yolov8n.yaml data=./mydata.yaml epochs=50 workers=1 cos_lr=True
Error parsing override 'detect'
missing EQUAL at '<EOF>'
See https://hydra.cc/docs/1.2/advanced/override_grammar/basic for details

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

this is the error I got when I want to train my own dataset with ultralytics8.0.0.
I know I can train it with ultralytics8.0.115 and it is successful, but I am trying to do yolov8+deepsort with https://github.com/MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking opensource code.
I need to use the old version of Ultralytics to train to get the .pt file. otherwise, I would have some problems with that project.
thanks for any help.

**Comment by glenn-jocher** [comment]
@simba404 hi there,

Thank you for reaching out regarding your question on how to use YOLOv8.

The error you encountered is related to the configuration of the training command. It seems that there is a missing equal symbol (=) in the `model=./yolov8n.yaml` part of your command. 

To resolve this issue, ensure that you include the equal symbol between the argument and its corresponding value, like this: `model=./yolov8n.yaml`. This should help you execute the command successfully.

It's worth mentioning that you mentioned using version 8.0.0 of Ultralytics. However, you noted that you were able to successfully train your own dataset using version 8.0.115. If possible, we recommend using the latest version of Ultralytics for the best experience and to take advantage of any new features or bug fixes.

Please let me know if you have any further questions or if there's anything else I can assist you with.

**Comment by simba404** [comment]
> 

thank you, you are right, the old version needs to show task=detect and mode=train, (yolo task=detect mode=train model=./yolov8n.yaml data=./mydata.yaml epochs=50 workers=1 cos_lr=True batch=8). it works for me, also need to change version of numpy and delete libiomp5md.dll in env

**Comment by glenn-jocher** [comment]
@simba404 thank you for your feedback and sharing the solution that worked for you!

For the old version of YOLOv8, it is necessary to specify the task as "detect" and the mode as "train" in the command. In your case, the command would be `yolo task=detect mode=train model=./yolov8n.yaml data=./mydata.yaml epochs=50 workers=1 cos_lr=True batch=8`.

Additionally, you mentioned that you needed to change the version of numpy and delete the `libiomp5md.dll` file in your environment. Updating the numpy version and removing `libiomp5md.dll` can help resolve certain compatibility issues.

If you have any further questions or need assistance with anything else, please feel free to ask.

**Comment by rajeevy397** [comment]
@glenn-jocher can you help me to get out of this problem.
i am using this command to train my custom dataset:
!yolo task=detect mode=train model=yolov8s.pt data= data.yaml epochs=25 imgsz=1080 plots=True

error i am getting is:
Error parsing override 'data.yaml'
missing EQUAL at '<EOF>'
See https://hydra.cc/docs/1.2/advanced/override_grammar/basic for details

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

i am using ultralytics==8.0.20 version
