### ISSUE TITLE
changing Yolov8 hyperparameters

### ISSUE THREAD

**Issue by moahaimen** [ultralytics/ultralytics#3491]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

@glenn-jocher Dear Sir  i made these changes in the Hyperparameters in the default.yaml"
# Ultralytics YOLO 🚀, AGPL-3.0 license
# Default training settings and hyperparameters for medium-augmentation COCO training

task: detect  # (str) YOLO task, i.e. detect, segment, classify, pose
mode: train  # (str) YOLO mode, i.e. train, val, predict, export, track, benchmark

# Train settings -------------------------------------------------------------------------------------------------------
model:  /content/yolov8s.pt# (str, optional) path to model file, i.e. yolov8n.pt, yolov8n.yaml
data: /content/datasets/WDdata/data.yaml # (str, optional) path to data file, i.e. coco128.yaml
epochs: 100  # (int) number of epochs to train 
optimizer: Adamax  
lr0: 0.0001 
"

but when i ran the code of training 
"
!yolo task=detect mode=train model=yolov8s.pt data=/content/WDdata/data.yaml epochs=75 
but the r

"

itried also using this "!yolo task=detect mode=train model=yolov8s.pt data=/content/WDdata/data.yaml epochs=75 cfg=/content/yolov8/ultralytics/yolo/cfg/default.yaml""
this error appears"File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/utils/checks.py", line 307, in check_yaml
    return check_file(file, suffix, hard=hard)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/utils/checks.py", line 299, in check_file
    raise FileNotFoundError(f"'{file}' does not exist")
FileNotFoundError: '/content/yolov8s.pt# (str, optional) path to model file, i.e. yolov8n.pt, yolov8n.yaml' does not exist"

i wish to make these changes  for my study
thank you

**Comment by glenn-jocher** [comment]
@moahaimen hi there! Thank you for reaching out. I understand that you are trying to modify the hyperparameters in the YOLOv8 repository. 

Regarding the error you encountered, it seems that there is an issue with the path to the model file (`yolov8s.pt`). Make sure that the path is correct and that the model file exists in that location.

To modify the hyperparameters, you need to make the changes in the `default.yaml` file. However, please note that your current modification includes extra text (`# (str, optional) path to model file, i.e. yolov8n.pt, yolov8n.yaml`) on the model path line. Please remove this extra text and ensure that the `model` path is pointing to the correct location of the model file.

Additionally, when running the training code, you should specify the hyperparameters using the `--` flag before each parameter. For example:

`!yolo task=detect mode=train model=yolov8s.pt data=/content/WDdata/data.yaml epochs=75`

Lastly, please note that YOLOv8 is not a part of the YOLOv5 repository. If you have any further questions or issues related to YOLOv8, please feel free to ask and I'll be happy to assist you.

**Comment by moahaimen** [comment]
@glenn-jocher  thank you i did this code 
!yolo task=detect mode=train model=yolov8s.pt data=/content/datasets/Weapon-Detection_merged-5/data.yaml epochs=100 lr0=0.0001  optimizer=RMSProp
 it working now
but please from where i can change the loss function

**Comment by moahaimen** [comment]
@glenn-jocher Thank you that worked, but now i went to https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/utils/loss.py
i need to change the loss function , or update another,

**Comment by glenn-jocher** [comment]
@moahaimen hi there! I'm glad to hear that the previous solution worked for you. Regarding your question about changing the loss function in YOLOv8, you can find the loss function implementation in the `loss.py` file within the YOLOv8 repository. However, please keep in mind that modifying the loss function might require a deep understanding of the YOLOv8 architecture and the impact it can have on the training process.

To update the loss function, you can make changes directly in the `loss.py` file. However, before making any modifications, I would recommend thoroughly understanding the existing loss function and its purpose. You might also want to refer to relevant research papers or the YOLOv8 documentation to gain a better understanding of the available options for customizing the loss function.

It's important to note that altering the loss function can significantly impact the performance and convergence of the model. Therefore, it's a good practice to experiment with small changes and thoroughly evaluate the results.

If you have any more specific questions or need further assistance with modifying the loss function in YOLOv8, feel free to ask. I'm here to help you!

**Comment by moahaimen** [comment]
@glenn-jocher Thank you for responding sir, i am facing a problem  that i am using Colab and whatever changes i made it seem doesn't have any effect on the Yolov8, i use this

"!yolo task=detect mode=train model=/content/yolov8/ultralytics/models/v8/yolov8.yaml data=/content/datasets/WDS/data.yaml epochs=100"

I make changes on the block.py and loss.py  but no changes 
"
also, i has another issue in here please help me in it 

https://github.com/ultralytics/ultralytics/issues/3246#issuecomment-1596319839

thank you very much

**Comment by glenn-jocher** [comment]
@moahaimen hi there,

I understand that you're facing some issues when making changes to YOLOv8 in Colab. Firstly, regarding the changes you made in the `block.py` and `loss.py` files, it's important to note that these changes will only take effect if you rebuild the YOLOv8 model after modifying those files. To rebuild the model, you can simply restart the runtime and rerun the training script.

As for the second issue you mentioned in the GitHub issue, I apologize for the inconvenience you're experiencing with the conflicting requirements of YOLOv8 and YOLOv5. To clarify, this repository is focused solely on YOLOv8, and any references or requirements related to YOLOv5 should not be applicable to this repo. I understand that the current state of the repository might be confusing due to shared code and structure between YOLOv8 and YOLOv5, but rest assured that YOLOv8 is the primary focus here.

Please let me know if there's anything else I can assist you with. Thank you for your patience and cooperation!

Best regards,
Glenn Jocher

**Comment by moahaimen** [comment]
@glenn-jocher I am very thankful and I am very sorry for bothering you, but I need your help because I may not have my PH.D. degree if I cant make any small contribution to Yolov8, I am not a professional developer, I am doing my best, so please I wish to get your help in at least adding a single layer to any model of yolo when I add or remove a layer in Yolov8. Yaml which I think works only on Yolov8n? I need just to delete a layer in Yolov8s, but when I make the training, error must about the tensor size issue, I tried to find how to fix it, in block.py, conv.py, train.py, but I couldn't find where is the source of the error and where the code to fix it, so please if you can tell how to fix it I would be grateful to you, @glenn-jocher

**Comment by glenn-jocher** [comment]
@moahaimen hi there,

I completely understand your situation and the importance of making contributions to YOLOv8 for your research. I'm here to help you.

To add or remove a layer in YOLOv8, you will need to make changes in the YOLOv8 configuration file (usually a YAML file). These changes should be done in the model architecture section of the configuration file.

If you want to delete a layer in YOLOv8s, you will need to carefully modify the configuration file to remove the corresponding layer definition. However, please note that removing a layer can affect the tensor sizes and cause errors during training. You mentioned that you encountered an error related to tensor size during training, and it's possible that this error is due to the changes you made in the layer configuration.

To fix this error, you need to ensure that the tensor sizes throughout the model architecture are consistent. It would help if you carefully examine the layer definitions, specifically its input and output sizes, in the configuration file (`yolov8s.yaml`). Cross-reference this with the size requirements of the YOLOv8 architecture and make the necessary adjustments to ensure the sizes remain compatible.

Please be aware that modifying the architecture of YOLOv8 without a deep understanding of its intricacies can be challenging. It is recommended to refer to the original YOLOv8 papers or consult with experienced researchers or developers who have expertise in YOLOv8 for guidance.

I hope this explanation helps you in making the necessary modifications to YOLOv8. If you have any further questions or need additional assistance, please feel free to ask. Good luck with your research!

Best regards,
Glenn Jocher

**Comment by moahaimen** [comment]
@glenn-jocher  
![image](https://github.com/ultralytics/ultralytics/assets/30658799/8f9906a0-4d53-4b16-9b3e-27f93fe7f564)
which on is Yolov8s, Yolov8l, Yolov8x

**Comment by moahaimen** [comment]
@glenn-jocher dear sir, i need to now to delete some layers of Yolov8l, but i dont know witch of Yaml file is the one 
thank you

**Comment by glenn-jocher** [comment]
@moahaimen

Hello, 

If you want to delete some layers in the YOLOv8l model, you can make the necessary changes in the `yolov8l.yaml` file. This file contains the configuration for YOLOv8l, which stands for YOLOv8 Large. 

Please open the `yolov8l.yaml` file, and you will find the model architecture definition within it. Look for the section that describes the layers and their parameters. You can remove the desired layers from this section. 

However, please remember that modifying the model architecture can have implications for the tensor sizes and may require other adjustments to maintain compatibility. Be sure to carefully consider the implications of removing a particular layer and ensure that the model can still function properly.

Feel free to ask if you have any further questions or need more assistance. Good luck with your project!

Best regards,
Glenn Jocher

**Comment by moahaimen** [comment]
@glenn-jocher   but sir there is no file named Yolov8l.yaml, if please check the attached image it from 

"/content/yolov8/ultralytics/models/v8"
![image](https://github.com/ultralytics/ultralytics/assets/30658799/d253576e-24ac-4f00-bfe0-d45a0f46f7d6)

@glenn-jocher

**Comment by glenn-jocher** [comment]
@moahaimen hi there,

I apologize for the confusion. It seems that the screenshot you provided does not include a `yolov8l.yaml` file in the specified directory. In that case, it's possible that the YOLOv8 repository does not provide a pre-defined configuration file for the YOLOv8l model.

To modify the YOLOv8l model, you can create a new YAML file and specify the architecture and parameters according to your requirements. You can use the existing YAML files (such as `yolov8.yaml` or `yolov8s.yaml`) as a reference to understand the structure and format.

Make sure to define the layers, their parameters, and any other necessary configuration options in the new YAML file. You can then use this new YAML file as the model configuration when training or using the YOLOv8l model.

If you have further questions or need additional assistance, please feel free to ask.

Best regards,
Glenn Jocher

**Comment by moahaimen** [comment]
@glenn-jocher  that will be hard, sir at least can you give me guides to build the Yolov8s.yaml? I need the exact number of layers and parameters for the backbone and head please.
this the  models/yolov5s.yaml from https://github.com/ultralytics/yolov5/blob/master/models/yolov5s.yaml

# YOLOv5 🚀 by Ultralytics, AGPL-3.0 license

# Parameters
nc: 80  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

   [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]


is it the same if i use it?
and please, could you explain to me then what is the  "Yolov8-P2.Yaml and Yolov8-P6.Yaml" what are they and what are they used for ?

**Comment by glenn-jocher** [comment]
@moahaimen hi,

Regarding the `yolov5s.yaml` file, it is not the same as the `yolov8s.yaml` in the YOLOv8 repository. The `yolov5s.yaml` file is specific to the YOLOv5 repository and cannot be directly used for YOLOv8.

To build the `yolov8s.yaml` for YOLOv8, it's important to understand the structure and key components of the YOLOv8 model. The backbone of YOLOv8s typically consists of convolutional layers followed by C3 blocks. The head includes upsampling layers, concatenation operations, and C3 blocks as well.

To create the `yolov8s.yaml` file, you can follow the general structure mentioned above and make adjustments as necessary. You'll need to specify the number of layers and their parameters for both the backbone and head sections based on your requirements.

Regarding the `yolov8-p2.yaml` and `yolov8-p6.yaml`, it seems that they are variants or different configurations of YOLOv8. Without further context, it's challenging to determine their exact purpose. They might represent variations of YOLOv8 with different layer sizes or structures to cater to specific use cases. It's best to consult the original YOLOv8 documentation or developers for more information about these specific configurations.

I hope this explanation helps. If you have any further questions or need additional assistance, feel free to ask.

Best regards,
Glenn Jocher

**Comment by moahaimen** [comment]
@glenn-jocher  thank you sir, i solved the issue and built the Yolov8s.Yaml
but having big issues in importing a new block from blocks.py

**Comment by glenn-jocher** [comment]
@moahaimen hi there,

I'm glad to hear that you were able to solve the issue and build the `Yolov8s.yaml` file for YOLOv8. Regarding the import of a new block from `blocks.py`, I can help you with that.

To import a new block from `blocks.py` into your YOLOv8 implementation, you need to follow these steps:

1. Open the `blocks.py` file and locate the block you want to import.
2. Copy the entire block definition, including its parameters and functionality.
3. In your code, at the location where you want to use the new block, import the block from `blocks.py`.
4. To import the block, use the following syntax: `from .blocks import YourBlockName`.
   Make sure to replace `YourBlockName` with the actual name of the block you want to import.
5. Once the block is imported, you can use it in your code by creating an instance of the block and passing in the necessary parameters.

Remember to understand the purpose and functionality of the block you're importing to ensure that it aligns with your specific use case in YOLOv8.

If you're facing any specific issues or error messages while importing the block, please provide more details, and I'll be happy to assist you further.

Best regards,
Glenn Jocher

**Comment by AAAlvi** [comment]
@moahaimen Could you help me add or remove layers from YOLOv8? I saw your message saying that you were able to do so. Could you give me the complete process to do so, or maybe share your code with me? I am a complete beginner in ML.

**Comment by moahaimen** [comment]
> @moahaimen Could you help me add or remove layers from YOLOv8? I saw your message saying that you were able to do so. Could you give me the complete process to do so, or maybe share your code with me? I am a complete beginner in ML.

yes, from Yaml file check the  model types s,m,n,l,x  see the default setting and play with parameters and layers

**Comment by AAAlvi** [comment]
@moahaimen The only things I can change are depth, width, and max_channels. if I try to change anything else it doesn't work.

**Comment by moahaimen** [comment]
> 

you add blocks to the Backbone and add layers but you need to take care of the tensor size 
also you can add layer blocks in the head

**Comment by AAAlvi** [comment]
@moahaimen How exactly how do I take care of the tensor size?

**Comment by glenn-jocher** [comment]
@AAAlvi hi there,

Taking care of tensor sizes means ensuring the output shape of one layer matches the expected input shape of the next layer. The tensor size or shape is often described by the dimensions of the tensor in terms of rows, columns, channels, etc.

When you add or remove layers, the shape of your tensors can change. If the output tensor of one layer doesn't correspond to the input shape needed for the next, an error will occur when you try to run your model.

To ensure tensor size compatibility:

1. Keep track of your tensor shapes: Keep in mind the expected shape of your tensors as they pass through each layer of your model. This can often be found in the documentation for the individual layers.

2. Use shape inference libraries or functions: Some machine learning libraries like TensorFlow and PyTorch provide functions to automatically determine the output shape of a layer given its input shape(s).

3. Adjust layers as needed: Sometimes you may need to add in additional layers like a Flatten layer or Reshape layer to modify your tensor shapes to be compatible.

Remember, designing and modifying machine learning architectures can be complex, so take your time, don't hesitate to recheck your model and adjustments, and ask for help when needed.

Best regards,
Glenn Jocher
