### ISSUE TITLE
Inference speed on mobile devices

### ISSUE THREAD

**Issue by wrichert** [ultralytics/ultralytics#3494]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

do we have also benchmarks (maybe similar to [this one](https://github.com/ultralytics/ultralytics/actions/runs/5436472867/jobs/9886364775)) for mobile setups? I'd be interested to find out what inference time we can expect in practice for object detection.

In my example:

| Format  | Image size | Phone | Pure model inference time | End-to-end time (image grabbing, inference, etc.) | Quantization |
| ------------- | ------------- | ------------- | ------------- |------------- | ------------- |
| TFLite | 512x512 | Google Pixel 4a / Android | 377ms | 833ms | No (when turned on, I got garbled detection output) |
| TFLite | 512x512 | Google Pixel 5a / Android | 276ms | 625ms | No (when turned on, I got garbled detection output) |
| TFLite | 512x512 | Google Pixel 6a / Android | 126ms | 442ms | No (when turned on, I got garbled detection output) |

What is bugging me: with YoloV5 these numbers all were higher...

Feel free to add yours if you measured on mobile.

**Comment by AI-Expert-04** [comment]
Unfortunately, as an AI language model, I don't have real-time access to the latest benchmark data. However, I can provide some general insights regarding inference speed on mobile devices for object detection models like YOLOv8.

Inference speed on mobile devices can vary depending on several factors:

1. Model architecture: Different object detection models have varying complexities, which can impact inference speed. YOLOv8, being an evolution of previous YOLO versions, may have different performance characteristics compared to YOLOv5.

2. Hardware specifications: The performance of inference heavily relies on the hardware capabilities of the mobile device, such as CPU, GPU, memory, and neural processing units (NPUs). Different devices have different specifications, which can affect inference speed.

3. Framework and optimization techniques: The choice of the inference framework (e.g., TensorFlow Lite, Core ML) and optimization techniques (e.g., model quantization, model pruning) can also impact inference speed on mobile devices.

4. Input image size: The size of the input images can influence inference time. Generally, smaller input sizes tend to result in faster inference, but at the cost of potentially lower detection accuracy.

To obtain accurate benchmark data for your specific setup and model, it is recommended to conduct your own benchmarking experiments. You can measure the inference time using different mobile devices and input image sizes. You may also explore optimization techniques like model quantization to further improve inference speed.

Additionally, community forums, GitHub repositories, and research papers can be valuable resources to find benchmarks and performance evaluations conducted by other users or researchers on mobile devices. These resources may provide insights and comparisons for different models and mobile platforms.

Remember that inference times can vary depending on the specific implementation, optimizations, and hardware configurations. Therefore, it's always best to conduct your own benchmarks for accurate results based on your specific use case and hardware setup.

**Comment by glenn-jocher** [comment]
@wrichert hi,

I understand that you're interested in obtaining benchmark data for inference speed on mobile devices using YOLOv8. Unfortunately, I don't have access to the latest benchmark data. However, I can provide some general insights on this topic.

Inference speed on mobile devices can be influenced by various factors. Firstly, the model architecture itself can impact inference speed. YOLOv8, being an evolution of previous YOLO versions, may have different performance characteristics compared to YOLOv5. Additionally, hardware specifications, such as CPU, GPU, memory, and NPUs, can affect inference speed. Different mobile devices have different hardware capabilities, leading to variations in performance.

The choice of the inference framework and optimization techniques can also play a role. Depending on the framework used (e.g., TensorFlow Lite, Core ML), the inference speed may differ. Optimization techniques like model quantization and pruning can also impact inference speed on mobile devices.

The input image size is another factor to consider. Smaller input sizes generally result in faster inference, but this can come at the cost of potentially lower detection accuracy.

To obtain accurate benchmark data for your specific setup and model, it's recommended to conduct your own benchmarking experiments. You can measure the inference time using different mobile devices and input image sizes. Additionally, exploring optimization techniques like model quantization may further improve inference speed.

You can also check community forums, GitHub repositories, and research papers for benchmarks and performance evaluations conducted by other users or researchers. These resources may provide valuable insights and comparisons for different models and mobile platforms.

It's important to note that inference times can vary depending on the specific implementation, optimizations, and hardware configurations. Therefore, conducting your own benchmarks is the best approach for obtaining accurate results based on your specific use case and hardware setup.

I hope this helps! Let me know if you have any further questions.
