### ISSUE TITLE
Standardize Onnx output format

### ISSUE THREAD

**Issue by thhart** [ultralytics/ultralytics#350]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Unfortunately the output layer in Onnx is different than YoloV5 and others. It is a small difference but leads to confusion and needs adaption in any code using the models. I am not an expert but obviously there are no standards for this which is a pity. Also documentation about input/output layers is very rare and not very common spread among Yolo scientists. At least it would be helpful to have some documentation here about the output format since often inference is done in different frameworks.

Here are some sample issues with obvious confusion:

https://github.com/ultralytics/ultralytics/issues/300
https://github.com/ultralytics/ultralytics/issues/221

### Use case

It would help to spread the use of models and avoid adaption work.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by DavidBerschauer** [comment]
Totally agree. Currently I am trying to get the instance segmentation to work, but I can't find any documentation about the output format. Guessing and looking at float arrays shouldn't be the solution.

**Comment by sstainba** [comment]
ABSOLUTELY AGREE.  Even if the formats between the two cannot be standardized, it would be immensely helpful to have a details explanation of what the output format mean and how to parse it.  I am a NET developer, not Python.  So my ability to look at the python scripts and see what it's doing is limited.  It's been difficult for me to implement these models in a c#/Windows app because there is no good documentation.

**Comment by knoppmyth** [comment]
I've closed #457 with code (Python) I've used that works w/ both v5 and 8 ONNX exports. Hopefully this is helpful. Look at the two
`if model == "yolov8":`
to see what needs to be changed for reading the ONNX for object detection. I've not done segmentation so I cannot say if it will work for it as well. If not, hopefully it gets you closer to a solution.

**Comment by umanniyaz** [comment]
Output coming ot of YOLOv8 custom trained is something like of shape : outputs.shape : (1, 9, 1029)

Not sure array of arrays ,no conf score nothing and its for one object how can I determine which is what  @knoppmyth

**Comment by sstainba** [comment]
> Output coming ot of YOLOv8 custom trained is something like of shape : outputs.shape : (1, 9, 1029)
> 
> Not sure array of arrays ,no conf score nothing and its for one object how can I determine which is what @knoppmyth

the output is the [batch size, x1, y1, x2, y2, class1, class2, ... ,classN, total elements].  so it looks like your model has 5 classes, right?  the second number will be 4 values for the x/y of the box and then one score for each class.  but i'm pretty sure the last value (1029) should be evenly divisible by the dimensions (second number 9).  so i'm not sure what's up with your model output.

**Comment by umanniyaz** [comment]
I only have one class and it's array of arrays It's confusing which is what

**Comment by sstainba** [comment]
> I only have one class and it's array of arrays It's confusing which is what

What do you mean "it's an array of arrays" ?  You mean the output?  Then yes... that's correct.  It's a multi-dimensional array... AKA a Tensor.  But if you only have 1 class, then the dimensions (second number) should be a 5.  I have two custom models, both of which are a single class and both are [1, 5, xxxxx] in output shape.

**Comment by umanniyaz** [comment]
@sstainba  Can you respond to updated comment

**Comment by JustasBart** [comment]
I totally agree with you guys, every time there's something new and exciting to test out it takes an absolute journey to try and pull together the pieces and fragments of information surrounding what is actually meant to happen and how and then how to wrap it within C++ and it's just painful...

**Comment by pderrenger** [comment]
@JustasBart i understand the frustration. Dealing with different output formats and lack of documentation can be quite challenging, especially when working with different programming languages like Python and C++. While I don't have the exact C++ code for parsing the output, I can share a general idea about the structure of the output array.

First off, the output shape (1, 9, 1029) indicates that your model expects a batch size of 1, has 9 anchors per grid cell, and produces an array of 1029 elements. Since you trained your model for 5 classes, the first 5 elements within each anchor's classification scores correspond to the confidence scores for those classes. Then, the subsequent 4 elements describe the bounding box coordinates (x1, y1, x2, y2) for each anchor.

To parse this output array, you'd extract the confidence scores for each class, choose the highest one as the predicted class for each anchor, and use the bounding box coordinates to draw the predicted boxes.

I hope this provides an initial insight into how to interpret the model's output. If you need further assistance or a more detailed explanation, feel free to ask!

**Comment by mrdoguoz** [comment]
Hi @pderrenger and @umanniyaz,

I trained the best.pt model with 5 segments with the yolo v8 model. Then I converted the best.pt model to best.onnx format with python:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
from ultralytics import YOLO

# Load a model
model_path = r'C:\Users\user\Desktop\Dogukan\best.pt'
official_model_path = r'C:\Users\user\Desktop\Dogukan\yolov8m-seg.pt'

model = YOLO(official_model_path)  # load an official model
model = YOLO(model_path)  # load a custom trained model

# Export the model
model.export(format='onnx')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Then I ran the best.onnx model on the PNG file in Android Java and output the results to the "result" object. I give my codes below:

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
public void onn() throws OrtException { OrtEnvironment env = OrtEnvironment.getEnvironment(); OrtSession.SessionOptions opts = new OrtSession.SessionOptions(); OrtSession session = env.createSession("/storage/emulated/0/Android/data/com.bantas.debug/files/best.onnx", opts); try { Bitmap bitmap = BitmapFactory.decodeFile("/storage/emulated/0/Android/data/com.bantas.debug/files/BlickerImage_37712.png");
float[][][][] input = preprocessImage(bitmap);

OnnxTensor inputTensor = OnnxTensor.createTensor(env, input);
OrtSession.Result result = session.run(Collections.singletonMap("images", inputTensor));
OnnxTensor outputTensor = (OnnxTensor) result.get(0);

float[][][] threeDimensionalArray = (float[][][]) result.get(0).getValue();

float[][] scores = threeDimensionalArray[0];
//    Map<String, Float> scoreMap = (Map<String, Float>) result.get(1).getValue();

Gson gson = new Gson();
String scoresJson = gson.toJson(scores);
//   String scoreMapJson = gson.toJson(scoreMap);

//    String deneme = processResult1(result);
Object out = outputTensor.getValue();

//  Gson gson = new Gson();
String json = gson.toJson(out);
String a = json;

} catch (Exception e) {
e.printStackTrace();
}

}
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
As the model output above, the json object is formed as follows:

json=[[[4.510956,17.391268,22.62502,27.104994 ... ...,0.6338775,0.54058886,0.36109298,0.062129557,0.043105423,0.3687974]]]

Using the JSON output from the ONNX model, what steps do I need to follow in Android to draw an image with certain bounding boxes and their class and confidence scores? How do we parse the JSON data representing the output of the model to get the coordinates, class information and confidence scores of the bounding boxes?

**Comment by Ayeshaaaaaaaaa** [comment]
i was using best.onnx model(pretrained the model on yolov8) for inference to detect objects but encountered unknown classids and bounding boxes , whereas my model worked fine with .pt.

**Comment by glenn-jocher** [comment]
It sounds like there might be an issue with the ONNX export. Please ensure you're using the latest version of the Ultralytics package and try exporting the model again. If the problem persists, you can refer to the [YOLOv8 ONNX export documentation](https://docs.ultralytics.com/integrations/onnx) for detailed guidance.
