### ISSUE TITLE
Unable to extract all polygon coordinates from predictions

### ISSUE THREAD

**Issue by Teamalpha-runcode** [ultralytics/ultralytics#3505]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

![binary](https://github.com/ultralytics/ultralytics/assets/136482741/3d10aca4-0f68-4fb5-94f4-922bae9c27a2)

above image is results[0].masks.data, while extracting polygon coordinates using results[0].masks.xy, I am just getting  polygon coordinates of first contour and I am unable to access polygon coordinates of second contour.

Can any one  help to extract both polygon coordinates.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Teamalpha-runcode hi there! Thank you for bringing this issue with extracting polygon coordinates from predictions to our attention. It seems that you are trying to extract polygon coordinates using `results[0].masks.xy`, but you are only able to access the polygon coordinates of the first contour and not the second one.

To extract the coordinates of both contours, you can try using the `find_contours` function from the `skimage.measure` module. This function will return a list of coordinates for each contour. You can then access the coordinates of each contour individually.

I hope this helps! If you have any further questions or need additional assistance, please let us know.

**Comment by Teamalpha-runcode** [comment]
> @Teamalpha-runcode hi there! Thank you for bringing this issue with extracting polygon coordinates from predictions to our attention. It seems that you are trying to extract polygon coordinates using `results[0].masks.xy`, but you are only able to access the polygon coordinates of the first contour and not the second one.
> 
> To extract the coordinates of both contours, you can try using the `find_contours` function from the `skimage.measure` module. This function will return a list of coordinates for each contour. You can then access the coordinates of each contour individually.
> 
> I hope this helps! If you have any further questions or need additional assistance, please let us know.

Thank you.

**Comment by glenn-jocher** [comment]
Hi @Teamalpha-runcode! Thank you for raising this issue with extracting polygon coordinates from predictions. In YOLOv8, when using `results[0].masks.xy`, you may encounter a limitation where only the polygon coordinates of the first contour are accessible, and not the second one.

To overcome this, you can utilize the `find_contours` function from the `skimage.measure` module. This function allows you to find and retrieve a list of coordinates for each contour detected in the image. By using this function, you will be able to access the coordinates of both contours individually.

I hope this explanation helps you to extract the needed polygon coordinates. If you have any further questions or require additional assistance, please don't hesitate to let us know. We're here to help!
