### ISSUE TITLE
How to prune YoloV8 model and save it for finetuning ?

### ISSUE THREAD

**Issue by ajithkumarmcw** [ultralytics/ultralytics#3507]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I like to prune yolov8 model but it seems that prune() in torch_utils is not implemented in yolov8 whereas yolov5 has it. i tried to take similar code of yolov5 . below is the yolov8 code to prune

```
import torch, torch.nn as nn
from torch.nn.utils import prune
from ultralytics import YOLO

model = YOLO("../weights/last.pt")


def sparsity(model):
    # Return global model sparsity
    a, b = 0, 0
    for p in model.parameters():
        a += p.numel()
        b += (p == 0).sum()
    return b / a

pruning_param = 0.3

for name, m in model.model.named_modules():
    if isinstance(m, nn.Conv2d) or isinstance(m, torch.nn.Linear):
        prune.l1_unstructured(m, name='weight', amount=pruning_param)  # prune
        prune.remove(m, 'weight')  # make permanent
print(f'Model pruned to {sparsity(model.model):.3g} global sparsity')

ckpt = {

            'model': model.model,
            'train_args': {},  # save as dict
}

torch.save(ckpt, '../model_pruned_3.pt')

model = YOLO(".../model_pruned_3.pt")

results = model.val(...)
```
After pruning i found that the models inference time has increased(3.5 times) rather than decreasing . Is my approach in pruning yolov8 model correct ? Kindly advise

**Comment by glenn-jocher** [comment]
@ajithkumarmcw hi,

Thank you for reaching out regarding pruning YOLOv8 model. Although pruning functionality is not directly implemented in the `torch_utils` module of YOLOv8, you can still apply pruning to YOLOv8 in a similar manner as you would with YOLOv5.

Based on the code you provided, it seems like you have used the `prune.l1_unstructured` method and `prune.remove` method from the `torch.nn.utils.prune` module to prune the convolutional and linear layers of the YOLOv8 model. This is a correct approach for pruning, so well done.

However, it is important to note that pruning a model might not always significantly reduce inference time. In some cases, pruning can introduce sparsity patterns that are not favorable for efficient computation, leading to slower inference times. The effectiveness and impact of pruning on the model's inference time depend on various factors such as the pruning ratio, architecture, and specific use case.

If your aim is to reduce inference time, I would recommend trying different pruning ratios and experimenting with different combinations of layers to prune. Additionally, you can consider other optimization techniques like quantization, layer fusion, or model distillation to further improve the efficiency of your pruned YOLOv8 model.

I hope this advice helps. If you have any further questions or need clarification, please feel free to ask.

Best regards,
Glenn Jocher

**Comment by ajithkumarmcw** [comment]
thanks for the explanation

**Comment by glenn-jocher** [comment]
@ajithkumarmcw you're welcome! I'm glad the explanation was helpful. If you have any further questions or need more assistance with pruning the YOLOv8 model, please don't hesitate to ask. I'm here to help!

**Comment by Hemilibeatriz** [comment]
I ran the example code from the issue to see how it works, and after I saved and tried to use it normally (loading the pruned model), I got this error: ` AssertionError: input shape last dimension expected 4 but input shape is torch.Size([15, 1])`. What could be the problem? Because the image is the same as I used in the model before pruning and it worked fine.

**Comment by glenn-jocher** [comment]
Hi there!

It seems like there could be an issue with how the model's state was restored after pruning, particularly in handling the input or output layers. When saving and reloading the model, ensure that the model architecture aligns explicitly with the expected input and output formats.

Here’s a quick fix to consider when loading your pruned YOLOv8 model:

```python
import torch
from ultralytics import YOLO

# Load your pruned model
model = YOLO('path_to_pruned_model.pt')

# Ensure model is in evaluation mode
model.model.eval()

# Optionally, if using custom preprocessing or need to confirm input size:
dummy_input = torch.randn(1, 3, 640, 640)  # Adjust the size (1, 3, height, width)
with torch.no_grad():
    output = model(dummy_input)
```

Make sure the size of the dummy input matches what your model expects. If the issue persists, double-check the modifications made during the pruning process, particularly around the reshaping or operations affecting dimensions.

If you need more help, feel free to ask! 😄

**Comment by Hemilibeatriz** [comment]
I made


```
model = YOLO("/content/drive/MyDrive/Marques/detector/medium_batch_32/weights/last.pt")


def sparsity(model):
    # Return global model sparsity
    a, b = 0, 0
    for p in model.parameters():
        a += p.numel()
        b += (p == 0).sum()
    return b / a

pruning_param = 0.3

for name, m in model.model.named_modules():
    if isinstance(m, nn.Conv2d) or isinstance(m, torch.nn.Linear):
        prune.l1_unstructured(m, name='weight', amount=pruning_param)  # prune
        prune.remove(m, 'weight')  # make permanent
print(f'Model pruned to {sparsity(model.model):.3g} global sparsity')

ckpt = {

            'model': model.model,
            'train_args': {},  # save as dict
}

torch.save(ckpt,"/content/drive/MyDrive/Marques/detector/medium_batch_32/weights/pruned.pt")
# Load your pruned model
model = YOLO('/content/drive/MyDrive/Marques/detector/medium_batch_32/weights/pruned.pt')

# Ensure model is in evaluation mode
model.model.eval()

# Optionally, if using custom preprocessing or need to confirm input size:
dummy_input = torch.randn(1, 3, 640, 640)  # Adjust the size (1, 3, height, width)
with torch.no_grad():
    output = model(dummy_input)
```
    
and i got:

![Captura de tela 2024-05-06 202024](https://github.com/ultralytics/ultralytics/assets/62450495/78515049-e089-4bfa-99dc-dfea8e6f29ca)

Can you help me with this?

**Comment by ajithvcoder** [comment]
@Hemilibeatriz could u share your model also ? 
then this type of pruning doesn't help for yolov8 you can use this it helped me https://github.com/VainF/Torch-Pruning/blob/master/examples/yolov8/yolov8_pruning.py

**Comment by Hemilibeatriz** [comment]
@ajithvcoder I'm using YOLOv8m to perform some performance tests with different hyperparameters and tactics. Now, I want to prune the model to see how it will impact my model. I'm starting to get worried because nothing I try seems to work #help LOL. Do you want the model itself? It's being developed on this dataset: https://www.kaggle.com/datasets/samuelcortinhas/sports-balls-multiclass-image-classification. Give me your email, and I'll share it with you. Regarding the repository you shared, I'm trying to use the Ultralytics YOLOv8.2.2 version, and it didn't work. If possible, please let me know which version you're using.

**Comment by ajithvcoder** [comment]
my email is inocajith21.5@gmail.com . 
This code https://github.com/VainF/Torch-Pruning/blob/master/examples/yolov8/yolov8_pruning.py worked for some version that was released in June 2023 and it was the proper method to prune and it was giving decent results. What is the error you are facing in using [this script](https://github.com/VainF/Torch-Pruning/blob/master/examples/yolov8/yolov8_pruning.py) ?

**Comment by ajithvcoder** [comment]
@Hemilibeatriz  you can refer this https://github.com/VainF/Torch-Pruning/tree/master/examples/yolov8 readme for the git commit id which worked while releasing the pruning code.

**Comment by Hemilibeatriz** [comment]
It wasn't exactly an error, I expressed myself poorly... What I want to do is to prune an already trained model, you know... And the script does the training of this model, which now doesn't make sense to me... Because I've already trained about 30 models with different hyperparameters and now I want to apply pruning to all these models, meaning I don't want to have to retrain all of them again... I'm searching for solutions but it's proving to be a huge challenge.

**Comment by ajithvcoder** [comment]
@Hemilibeatriz I believe you need to finetune the model anyway after pruning. You can see the explanation here https://stackoverflow.com/questions/64686187/is-re-training-required-on-a-model-pruned-using-tfmot  .

**Comment by ajithvcoder** [comment]
there are some open issues in pruning yolov8 because of their custom models https://github.com/ultralytics/ultralytics/issues/9374 . Only the VainF repo worked for me if u want u can use it , it gave good results.

**Comment by ajithvcoder** [comment]
its enough if u train for 5 or 10 epochs i think for finetuning and it will also show how much it has pruned for every epoch and the map results.

**Comment by glenn-jocher** [comment]
Absolutely! For finetuning, a short training period of about 5-10 epochs should be sufficient to recalibrate the parameters of your pruned model. 🌟 This is especially true if the initial training was thorough. During these additional training epochs, keep an eye on the printed metrics to monitor the effectiveness of the pruning process in terms of both sparsity and mAP performance. If you need further guidance or any issues arise, feel free to reach out!

**Comment by Hemilibeatriz** [comment]
Got it, thank you very much for the clarifications... but here we go...

I'm using this example:  https://github.com/VainF/Torch-Pruning/blob/master/examples/yolov8/yolov8_pruning.py as suggested by @ajithvcoder. I'm using the Ultralytics YOLOv8.2.2 (because it's the version my model was trained on). However, when I run it, I get this error: Import "ultralytics.yolo..." could not be resolved

![Captura de tela 2024-05-09 064626](https://github.com/ultralytics/ultralytics/assets/62450495/44266803-91e2-4fa1-ad5b-6dcc29cca191)


What should I do?I need to use it in Colab since my notebook's GPU doesn't train YOLO. I need help

**Comment by ajithvcoder** [comment]
!pip install ultralytics==8.2.2 , Even after installing that if it shows just run the cell. Some times IDE's show wrong info.

**Comment by Hemilibeatriz** [comment]
Yes, I did that.. but it didn't work. It generates
```
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-25-a22e5f0b378b>](https://localhost:8080/#) in <cell line: 17>()
     15 from ultralytics.nn.modules import Detect, C2f, Conv, Bottleneck
     16 from ultralytics.nn.tasks import attempt_load_one_weight
---> 17 from ultralytics.yolo.engine.model import TASK_MAP
     18 from ultralytics.yolo.engine.trainer import BaseTrainer
     19 from ultralytics.yolo.utils import yaml_load, LOGGER, RANK, DEFAULT_CFG_DICT, DEFAULT_CFG_KEYS

ModuleNotFoundError: No module named 'ultralytics.yolo'
```

**Comment by glenn-jocher** [comment]
@ajithvcoder hi there! It looks like you might be encountering issues even after installing the correct Ultralytics package. If you're still seeing the error after running `!pip install ultralytics==8.2.2`, it's often helpful to restart your runtime or kernel. This refresh can help resolve any cached or path issues especially in environments like Google Colab or Jupyter notebooks. Here’s how you can restart the runtime in Google Colab:

```python
import os
os.kill(os.getpid(), 9)
```

This will restart the session and clear out any issues. Give it a try and let me know if it helps!

**Comment by Hemilibeatriz** [comment]
> @ajithvcoderolá! Parece que você pode encontrar problemas mesmo depois de instalar o pacote Ultralytics correto. Se você ainda estiver vendo o erro após a execução `!pip install ultralytics==8.2.2`, geralmente é útil reiniciar o tempo de execução ou o kernel. Essa atualização pode ajudar a resolver quaisquer problemas de cache ou de caminho, especialmente em ambientes como Google Colab ou notebooks Jupyter. Veja como você pode reiniciar o tempo de execução no Google Colab:
> 
> ```python
> import os
> os.kill(os.getpid(), 9)
> ```
> 
> Isso reiniciará a sessão e eliminará quaisquer problemas. Experimente e deixe-me saber se isso ajuda!

Hi @glenn-jocher I did this but I keep getting the last error I mentioned:

```
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-25-a22e5f0b378b>](https://localhost:8080/#) in <cell line: 17>()
     15 from ultralytics.nn.modules import Detect, C2f, Conv, Bottleneck
     16 from ultralytics.nn.tasks import attempt_load_one_weight
---> 17 from ultralytics.yolo.engine.model import TASK_MAP
     18 from ultralytics.yolo.engine.trainer import BaseTrainer
     19 from ultralytics.yolo.utils import yaml_load, LOGGER, RANK, DEFAULT_CFG_DICT, DEFAULT_CFG_KEYS

ModuleNotFoundError: No module named 'ultralytics.yolo'
```

**Comment by Hemilibeatriz** [comment]
@ajithvcoder @glenn-jocher I'm trying another approach to see if I can solve the problem. But I'm not sure if I'm going down the right paths, can you please assist me? As mentioned earlier in #9374 , I am pruning my model using PyTorch with the following code:

![image](https://github.com/ultralytics/ultralytics/assets/62450495/456a28e5-2802-45f4-94c1-dada9e8fb004)

Then I try to use it with the code and i´m receiving:
![image](https://github.com/ultralytics/ultralytics/assets/62450495/cdeeecf5-8add-4b64-a7f2-3bc854009854)

What am I missing? What could the error be?

**Comment by glenn-jocher** [comment]
Hey there! It looks like you're really diving deep into model pruning with PyTorch, which is great! From the images you posted (though I can’t see them directly here), it seems like there might be an issue with how the pruned model is being loaded or used afterward.

If the error you're encountering is a `ModuleNotFoundError` or a misconfiguration error when loading the pruned model, it's important to make sure that the model's architecture in your script exactly matches the one you used during training and pruning. If there are discrepancies, PyTorch won't be able to correctly map all model parameters.

A common practice is to ensure that the model class definition and state dictionary match up. Here’s a small snippet to check if the state dictionary of your pruned model aligns with your model class:

```python
# Assuming 'pruned_model' is your loaded model and 'model' is the fresh instance of the same model architecture
model = TheModelClass(*args, **kwargs)  # replace with your actual model class and parameters
model.load_state_dict(pruned_model.state_dict())
```

This code initializes a new instance of your model and tries to load the pruned state dictionary into it. Any errors here would suggest discrepancies in the architecture.

If everything seems correct but you still face issues, ensure that your environment has all necessary dependencies correctly installed and up to date. Sometimes, a simple environment misconfiguration can cause such headaches.

Keep pushing through, you're on the right track! If there's anything more specific or another error message, feel free to share! 🚀

**Comment by Hemilibeatriz** [comment]
I didn't understand, can you help me with a more detailed example?

**Comment by glenn-jocher** [comment]
Absolutely, I'd be happy to help with a more streamlined example! Let's say you want to load a pre-trained YOLOv8 model and run a prediction on a single image. Here’s a brief example:

```python
from ultralytics import YOLO

# Load the pre-trained YOLOv8 model
model = YOLO('yolov8n.pt')

# Run prediction on an image
results = model.predict('path/to/your/image.jpg')

# Display results
results.show()
```

This snippet loads a model, performs inference on an image, and displays the results. Feel free to replace `'yolov8n.pt'` and `'path/to/your/image.jpg'` with your model and image path respectively. Let me know if you need more clarity on any part! 😊

**Comment by ramsiyer1** [comment]
Is there any way to do knowledge distillation between yolo models, similar to pruning??

**Comment by glenn-jocher** [comment]
Hi @ramsiyer1,

Thank you for your question! Knowledge distillation is indeed a powerful technique to transfer knowledge from a larger "teacher" model to a smaller "student" model, and it can be applied to YOLO models as well.

While YOLOv8 does not have built-in support for knowledge distillation like it does for pruning, you can implement it using PyTorch. Here’s a high-level approach to get you started:

1. **Define Teacher and Student Models**: Load your pre-trained teacher model and define your student model.
2. **Distillation Loss**: Implement a distillation loss function that combines the standard loss (e.g., cross-entropy) with a distillation loss (e.g., Kullback-Leibler divergence) to match the student’s output with the teacher’s softened output.
3. **Training Loop**: Train the student model using the combined loss.

Here’s a simplified example:

```python
import torch
import torch.nn as nn
import torch.optim as optim
from ultralytics import YOLO

# Load teacher and student models
teacher_model = YOLO('yolov8n.pt')
student_model = YOLO('yolov8s.pt')

# Define distillation loss
class DistillationLoss(nn.Module):
    def __init__(self, temperature=3.0, alpha=0.5):
        super(DistillationLoss, self).__init__()
        self.temperature = temperature
        self.alpha = alpha
        self.criterion = nn.CrossEntropyLoss()

    def forward(self, student_outputs, teacher_outputs, labels):
        soft_teacher_outputs = torch.softmax(teacher_outputs / self.temperature, dim=1)
        soft_student_outputs = torch.log_softmax(student_outputs / self.temperature, dim=1)
        distillation_loss = nn.KLDivLoss()(soft_student_outputs, soft_teacher_outputs) * (self.temperature ** 2)
        student_loss = self.criterion(student_outputs, labels)
        return self.alpha * student_loss + (1 - self.alpha) * distillation_loss

# Training loop
def train(student_model, teacher_model, dataloader, optimizer, criterion, device):
    student_model.train()
    teacher_model.eval()
    for images, labels in dataloader:
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()
        student_outputs = student_model(images)
        with torch.no_grad():
            teacher_outputs = teacher_model(images)
        loss = criterion(student_outputs, teacher_outputs, labels)
        loss.backward()
        optimizer.step()

# Example usage
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
student_model.to(device)
teacher_model.to(device)
optimizer = optim.Adam(student_model.parameters(), lr=0.001)
criterion = DistillationLoss()

# Assuming you have a DataLoader `dataloader`
# train(student_model, teacher_model, dataloader, optimizer, criterion, device)
```

This is a basic example to get you started. You can further customize the training loop and distillation process based on your specific requirements.

If you encounter any issues or need further assistance, please provide a minimum reproducible code example and ensure you are using the latest versions of `torch` and `ultralytics`. This will help us better understand and address your concerns.

Happy coding! 😊

**Comment by ramsiyer1** [comment]
Hi, 
How can the above approach be done for a custom trained yolo model with different backbone ?, or is it only applicable to existing architectures ?
Thank You

**Comment by glenn-jocher** [comment]
Hi @ramsiyer1,

Great question! You can definitely apply knowledge distillation to a custom-trained YOLO model with a different backbone. The approach remains largely the same, but you'll need to ensure that both your teacher and student models are correctly defined and loaded.

Here's a brief outline to get you started:

1. **Load Custom Models**: Ensure you have your custom-trained teacher and student models ready.
2. **Define Distillation Loss**: Use a combination of standard loss and distillation loss.
3. **Training Loop**: Implement the training loop to update the student model based on the combined loss.

Here’s a simplified example:

```python
import torch
import torch.nn as nn
import torch.optim as optim
from ultralytics import YOLO

# Load custom teacher and student models
teacher_model = YOLO('path/to/custom_teacher_model.pt')
student_model = YOLO('path/to/custom_student_model.pt')

# Define distillation loss
class DistillationLoss(nn.Module):
    def __init__(self, temperature=3.0, alpha=0.5):
        super(DistillationLoss, self).__init__()
        self.temperature = temperature
        self.alpha = alpha
        self.criterion = nn.CrossEntropyLoss()

    def forward(self, student_outputs, teacher_outputs, labels):
        soft_teacher_outputs = torch.softmax(teacher_outputs / self.temperature, dim=1)
        soft_student_outputs = torch.log_softmax(student_outputs / self.temperature, dim=1)
        distillation_loss = nn.KLDivLoss()(soft_student_outputs, soft_teacher_outputs) * (self.temperature ** 2)
        student_loss = self.criterion(student_outputs, labels)
        return self.alpha * student_loss + (1 - self.alpha) * distillation_loss

# Training loop
def train(student_model, teacher_model, dataloader, optimizer, criterion, device):
    student_model.train()
    teacher_model.eval()
    for images, labels in dataloader:
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()
        student_outputs = student_model(images)
        with torch.no_grad():
            teacher_outputs = teacher_model(images)
        loss = criterion(student_outputs, teacher_outputs, labels)
        loss.backward()
        optimizer.step()

# Example usage
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
student_model.to(device)
teacher_model.to(device)
optimizer = optim.Adam(student_model.parameters(), lr=0.001)
criterion = DistillationLoss()

# Assuming you have a DataLoader `dataloader`
# train(student_model, teacher_model, dataloader, optimizer, criterion, device)
```

This example should help you get started with knowledge distillation for your custom YOLO models. If you encounter any issues, please ensure you are using the latest versions of `torch` and `ultralytics`. If the problem persists, providing a minimum reproducible code example would be very helpful for further investigation.

Happy coding! 😊

**Comment by alexxony** [comment]
> Got it, thank you very much for the clarifications... but here we go...
> 
> I'm using this example: https://github.com/VainF/Torch-Pruning/blob/master/examples/yolov8/yolov8_pruning.py as suggested by [@ajithvcoder](https://github.com/ajithvcoder). I'm using the Ultralytics YOLOv8.2.2 (because it's the version my model was trained on). However, when I run it, I get this error: Import "ultralytics.yolo..." could not be resolved
> 
> ![Captura de tela 2024-05-09 064626](https://github.com/ultralytics/ultralytics/assets/62450495/44266803-91e2-4fa1-ad5b-6dcc29cca191)
> 
> What should I do?I need to use it in Colab since my notebook's GPU doesn't train YOLO. I need help

hello?  Did you run it successfully now?

**Comment by glenn-jocher** [comment]
Hi @alexxony! The import issues that @Hemilibeatriz encountered are due to changes in the Ultralytics package structure between versions. The `ultralytics.yolo` module path was restructured in newer versions.

For anyone still interested in model optimization techniques like pruning, I'd recommend exploring the built-in optimization approaches. [Model pruning](https://www.ultralytics.com/glossary/model-pruning) is one of several techniques that can be combined with [model quantization](https://www.ultralytics.com/glossary/model-quantization) and [knowledge distillation](https://www.ultralytics.com/glossary/knowledge-distillation) for maximum efficiency.

While we don't have native pruning support in the current YOLO11 release, you can export your models to formats like ONNX or TensorRT that support various optimization techniques during deployment. This often provides better real-world performance improvements than manual pruning approaches.
