### ISSUE TITLE
How to see the number of separated objects in each detection and be able to control the color of these

### ISSUE THREAD

**Issue by devRaziel** [ultralytics/ultralytics#3513]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have this code that was trained to detect two objects but I would like to see how many objects are on the screen of each one and how I could change the color of each one in the code

```
from ultralytics import YOLO
import cv2



model = YOLO("best.pt")

cap = cv2.VideoCapture(0)


while True:

    ret, frame = cap.read()


    resultados = model.predict(frame, imgsz = 640, conf = 0.40)
    


    anotaciones = resultados[0].plot(probs=False)


    
    cv2.imshow("DETECCION Y SEGMENTACION2", anotaciones)


    if cv2.waitKey(1) == 27:
        break

        

cap.release()
cv2.destroyAllWindows()
```

**Comment by glenn-jocher** [comment]
@devRaziel hi there! To see the number of separated objects in each detection using YOLOv8, you can access the `results` variable returned by the `predict` method. This variable contains the predicted objects and their corresponding information.

To count the number of objects in each detection, you can simply use the `len` function on the `results.pred` attribute. This will give you the total number of objects detected in the frame.

Regarding changing the color of each object, in the code you provided, you can modify the `anotaciones` variable to include different colors for each object. You can achieve this by iterating over the objects in `results.pred`, and for each object, you can use OpenCV's `rectangle` function to draw a bounding box with a specific color. You can set different colors based on the object index or any other criteria you prefer.

I hope this helps! If you have any further questions, feel free to ask.
