### ISSUE TITLE
Disable printable output

### ISSUE THREAD

**Issue by Renat2001** [ultralytics/ultralytics#3515]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there a way to disable such outputs when running inference?
![image](https://github.com/ultralytics/ultralytics/assets/61690545/0266942c-084e-4494-8b98-c2777dcfd0af)

**Comment by Laughing-q** [comment]
@Renat2001 pass `verbose=False`, 
```python
model.predict(verbose=False)
```
