### ISSUE TITLE
How to add other evaluation metrics

### ISSUE THREAD

**Issue by eorroot** [ultralytics/ultralytics#3517]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to change the metric to MR-2, but I can't find where to change it

**Comment by glenn-jocher** [comment]
@eorroot hi there! Thank you for your question. To change the evaluation metric to MR-2 in YOLOv8, you will need to modify the relevant code in the repository. Specifically, you need to locate the evaluation code that calculates the metric and make the necessary changes to calculate MR-2 instead.

Please note that YOLOv8 currently does not have built-in support for MR-2 as an evaluation metric. You will need to implement this functionality yourself or look for external libraries or packages that can compute MR-2.

If you have any further questions or need more assistance, please don't hesitate to ask. I'm here to help!

Best regards,
Glenn Jocher

**Comment by eorroot** [comment]
Thank you very much for your help!
Is this the file that needs to be modified?
![image](https://github.com/ultralytics/ultralytics/assets/49010412/a368afb5-34ea-4487-943c-fb663c213fbc)
Because MR-2 is modified according to cocoapi, whether it is to modify this part of the code?
![image](https://github.com/ultralytics/ultralytics/assets/49010412/b324d4ba-9fc9-419c-ba95-2410f35f487f)


> @eorroot hi there! Thank you for your question. To change the evaluation metric to MR-2 in YOLOv8, you will need to modify the relevant code in the repository. Specifically, you need to locate the evaluation code that calculates the metric and make the necessary changes to calculate MR-2 instead.
> 
> Please note that YOLOv8 currently does not have built-in support for MR-2 as an evaluation metric. You will need to implement this functionality yourself or look for external libraries or packages that can compute MR-2.
> 
> If you have any further questions or need more assistance, please don't hesitate to ask. I'm here to help!
> 
> Best regards, Glenn Jocher

Thank you very much for your help!
Is this the file that needs to be modified?
![image](https://github.com/ultralytics/ultralytics/assets/49010412/a368afb5-34ea-4487-943c-fb663c213fbc)
Because MR-2 is modified according to cocoapi, whether it is to modify this part of the code?
![image](https://github.com/ultralytics/ultralytics/assets/49010412/b324d4ba-9fc9-419c-ba95-2410f35f487f)

**Comment by eorroot** [comment]
> @eorroot hi there! Thank you for your question. To change the evaluation metric to MR-2 in YOLOv8, you will need to modify the relevant code in the repository. Specifically, you need to locate the evaluation code that calculates the metric and make the necessary changes to calculate MR-2 instead.
> 
> Please note that YOLOv8 currently does not have built-in support for MR-2 as an evaluation metric. You will need to implement this functionality yourself or look for external libraries or packages that can compute MR-2.
> 
> If you have any further questions or need more assistance, please don't hesitate to ask. I'm here to help!
> 
> Best regards, Glenn Jocher

Thank you very much for your help!

Is this the file that needs to be modified?

![image](https://github.com/ultralytics/ultralytics/assets/49010412/a368afb5-34ea-4487-943c-fb663c213fbc)


Because MR-2 is modified according to cocoapi, whether it is to modify this part of the code?

![image](https://github.com/ultralytics/ultralytics/assets/49010412/b324d4ba-9fc9-419c-ba95-2410f35f487f)

**Comment by glenn-jocher** [comment]
Hi @eorroot, I'm glad I could help!

To change the evaluation metric to MR-2 in YOLOv8, you will indeed need to modify the code. The first image you provided seems to show part of the code related to evaluation. However, please note that YOLOv8 does not currently have built-in support for MR-2 as an evaluation metric.

If you want to implement MR-2 in YOLOv8, you would need to modify the evaluation code and integrate the calculation of MR-2 yourself. The second image you provided seems to show code related to cocoapi, which is used for evaluation in the COCO dataset. If MR-2 is based on cocoapi, you may need to modify that part of the code.

Alternatively, you can look for external libraries or packages that can compute MR-2 and integrate them into YOLOv8. This might involve modifying the evaluation code to call the external library or package for MR-2 calculation.

If you have further questions or need more assistance, feel free to ask. I'm here to support you!

Best regards,
Glenn Jocher

**Comment by eorroot** [comment]
> Hi @eorroot, I'm glad I could help!
> 
> To change the evaluation metric to MR-2 in YOLOv8, you will indeed need to modify the code. The first image you provided seems to show part of the code related to evaluation. However, please note that YOLOv8 does not currently have built-in support for MR-2 as an evaluation metric.
> 
> If you want to implement MR-2 in YOLOv8, you would need to modify the evaluation code and integrate the calculation of MR-2 yourself. The second image you provided seems to show code related to cocoapi, which is used for evaluation in the COCO dataset. If MR-2 is based on cocoapi, you may need to modify that part of the code.
> 
> Alternatively, you can look for external libraries or packages that can compute MR-2 and integrate them into YOLOv8. This might involve modifying the evaluation code to call the external library or package for MR-2 calculation.
> 
> If you have further questions or need more assistance, feel free to ask. I'm here to support you!
> 
> Best regards, Glenn Jocher
![image](https://github.com/ultralytics/ultralytics/assets/49010412/75b4e83a-293c-4e38-b1e7-26d09679d35d)

Thank you very much for your help. The external packages of MR-2 is modified based on cocoapi, which means I can call the modified eval_json function during verification. However, I found that all codes related to the return value 111 of the eval_json function need to be changed. Considering the integration of the YOLOv8 project and my coding capabilities, I think this process is quite complicated. Have you considered adding this metric?

**Comment by glenn-jocher** [comment]
Hi @eorroot, thank you for your question!

Regarding the integration of MR-2 metric into YOLOv8, I understand that it can be a complex process. At this moment, YOLOv8 does not have built-in support for MR-2 as an evaluation metric. However, the possibility of adding this metric is definitely something worth considering.

Adding a new evaluation metric like MR-2 involves modifying the evaluation code and integrating the calculation of MR-2 into the existing evaluation process. This would require making changes to the return values and potentially other parts of the evaluation code where the metric is computed.

While I cannot speak on behalf of the YOLOv8 project, I recommend submitting an issue or feature request on the YOLOv8 GitHub repository, where you can propose the addition of MR-2 as an evaluation metric. This way, the project maintainers can review the request and consider it for future development.

I hope this helps clarify the current situation regarding MR-2 in YOLOv8. If you have any further questions or need additional support, please feel free to ask.

Best regards,
Glenn Jocher

**Comment by yuanyuanpei7** [comment]
I wonder how can I calculate Dice and mIoU instead of mask mAP for segmentation? Who can help me realize that? Thanks.

**Comment by glenn-jocher** [comment]
@yuanyuanpei7 hi there! Thank you for your question.

Dice and mIoU are two commonly used metrics for evaluating the performance of a segmentation model. 

Currently, YOLOv8 does not have built-in support to calculate the Dice coefficient and mean Intersection over Union (mIoU). However, you can certainly modify the code to include these evaluation metrics.

Both Dice and mIoU require the computation of the intersection and union areas between the predicted and ground truth masks. To include them, you would need to modify the evaluation code of YOLOv8 that is responsible for calculating the metrics and integrate the Dice and mIoU calculations yourself.

It's a complicated process and may take some effort, but with solid programming skills, it can be achieved. 

If you have further questions or need additional assistance, feel free to ask. 

Best regards,
Glenn Jocher

**Comment by yuanyuanpei7** [comment]
@glenn-jocher Would you please help me realize that?

**Comment by glenn-jocher** [comment]
@yuanyuanpei7 hi! I'd be glad to provide some guidance.

The first step to implementing Dice and mIoU in YOLOv8 is to find and understand the segment in the code which is responsible for performance evaluation. This is where the logic for calculating the respective metrics occur. 

Next, you would need to implement the calculations for Dice and mIoU yourself. Here's a brief idea of how:

1. **Dice Coefficient**: Dice likeness is a measure of the overlap between two samples. For its calculation, you may need to modify the code to calculate the 2*(Area of Overlap) divided by the total number of pixels in both the predicted and ground truth masks.

2. **mean Intersection over Union (mIoU)**: It is used during training your semantic segmentation network to minimize the loss. To calculate mIoU, you would need to compute the intersection and union areas between the predicted and ground truth masks, and take their average.

Implementing these changes require a good understanding of the existing YOLOv8 code, as well as these two segmentation evaluation metrics.

I hope this helps! If you have any additional questions, please don't hesitate to ask.

Best Regards,
Glenn Jocher.

**Comment by yuanyuanpei7** [comment]
@@glenn-jocher  Thank you for your friendly comments, I've tried several times but can't achieve it.

**Comment by glenn-jocher** [comment]
Hi @yuanyuanpei7, thank you for your response.

I understand that implementing new evaluation metrics like Dice and mIoU in YOLOv8 can be challenging, especially if you're not familiar with the codebase. It's not a simple modification and requires a good understanding of how the current evaluation metrics are being calculated in the code.

However, don't be disheartened. Such challenges often act as great opportunities to learn more about the underlying structure and functionality of the models and evaluation metrics. I would encourage you to continue trying, and maybe break the problem into smaller parts. Try to tackle one metric at a time, understand where and how the current metrics are being calculated and how you can use similar components for the calculation of the new metrics. 

For implementing a metric like Dice or mIoU, you need to focus on how the overlap between the predicted and ground truth segmentation masks are being calculated in your current codebase. 

I hope this provides some guidance. Don't hesitate to reach out here if you have more questions or need further clarification on something.

Good luck with your implementations!

Best regards,
Glenn Jocher
