### ISSUE TITLE
How to not showing labels and confidence text 

### ISSUE THREAD

**Issue by sitifatim** [ultralytics/ultralytics#3519]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, i want to ask how to hidden labels and confidence. I tried with show_labels = False and show_conf=False but the result is still showing the text (i show the image result with cv2 which i attached the code below)
```
results = model.predict(img, show_labels=False, show_conf=False)
frame = results[0].plot()
cv2.imshow("Image", frame)
cv2.waitKey(0)
cv2.destroyAllWindows()
```

Is there any solution to not showing label and confidence text with cv2? 

### Additional

but strangely, if i add `save=True` or `show=True` arguments in `model.predict`, the result is not showing the label and confidence text.

**Comment by Laughing-q** [comment]
@sitifatim hi, if you pass `show_conf` and `show_labels` in `model.predict` then it only works with our internal cv2.imshow, like the following code, it would work:
```python
results = model.predict(img, show_labels=False, show_conf=False, show=True)
```
if you want to show it by your own then you need to pass `conf` and `labels` in `plot()` function:
```python
from ultralytics import YOLO
import cv2
model = YOLO("yolov8n.pt")
results = model.predict()

img = results[0].plot(labels=False, conf=False)
cv2.imshow("Image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()
```

**Comment by sitifatim** [comment]
> @sitifatim hi, if you pass `show_conf` and `show_labels` in `model.predict` then it only works with our internal cv2.imshow, like the following code, it would work:
> 
> ```python
> results = model.predict(img, show_labels=False, show_conf=False, show=True)
> ```
> 
> if you want to show it by your own then you need to pass `conf` and `labels` in `plot()` function:
> 
> ```python
> from ultralytics import YOLO
> import cv2
> model = YOLO("yolov8n.pt")
> results = model.predict()
> 
> img = results[0].plot(labels=False, conf=False)
> cv2.imshow("Image", img)
> cv2.waitKey(0)
> cv2.destroyAllWindows()
> ```

this works very well, thank you

**Comment by glenn-jocher** [comment]
Hi @sitifatim, I'm glad to hear that the solution provided worked well for you! If you pass `show_conf` and `show_labels` as arguments in the `model.predict` function, it will only work when using `show=True` to display the image with our internal `cv2.imshow` function.

On the other hand, if you want to display the image using your own method, you can use the `plot` function and pass `labels=False` and `conf=False` as arguments. This will return an image without the label and confidence text. You can then use `cv2.imshow` to display the modified image.

If you have any more questions or need further assistance, feel free to ask. We're here to help!
