### ISSUE TITLE
object detection: yolov8 vs yolov5

### ISSUE THREAD

**Issue by quangsonle** [ultralytics/ultralytics#352]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i went through a comparison of yolov8 vs yolov5 recently.
https://learnopencv.com/ultralytics-yolov8/
i see the image detection of yolov8 is much better than yolov5's. However the classification of yolov5 x model is better yolov8's

i would like to know the performance of detection here is integration of bounding boxs detection and classification or how is it? as in my case, i care more about the correctness of classification, so i could stay with Yolov5 if the performance of Yolov8 object detection is integration of bounding box and classification

**Comment by Laughing-q** [comment]
@quangsonle hi detection is detection itself, classification is classification itself.
So it you're going to use detection then please go ahead with yolov8. :)

**Comment by dmddmd** [comment]
and would you say for classficiation, using yolov5 could be more reasonable?

**Comment by Laughing-q** [comment]
@dmddmd also recommend yolov8 if you want to use yolo model as backbone. :)
