### ISSUE TITLE
YAML file example for training on a custom dataset in COCO format

### ISSUE THREAD

**Issue by rose-jinyang** [ultralytics/ultralytics#3520]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello
How are you?
Thanks for contributing to this project.
I am going to train a model on my custom dataset in COCO annotation format.
How can I list the annotation file paths in the config YAML file?

### Additional

No

**Comment by glenn-jocher** [comment]
@rose-jinyang hi there!

Thank you for your interest in YOLOv8 and your kind words! We appreciate your contribution to the project.

To list the annotation file paths in the config YAML file for training on a custom dataset in COCO annotation format, you can use the `train: <file>` option in the YAML file. The `<file>` should be the path to your trainset.txt file, which contains the paths to the individual annotated image files.

Here's an example:

```yaml
train: /path/to/trainset.txt
```

In the `trainset.txt` file, each line should contain the path to an annotated image file, relative to the dataset directory. Each image file path should be followed by the corresponding annotation file path, separated by a space.

For example:

```
data/images/train/image1.jpg data/annotations/train/image1.txt
data/images/train/image2.jpg data/annotations/train/image2.txt
...
```

Make sure to adjust the paths in the `trainset.txt` file to match your dataset directory structure.

I hope this helps!  Let me know if you have any further questions.

**Comment by rose-jinyang** [comment]
Thanks

**Comment by glenn-jocher** [comment]
@rose-jinyang hi there!

Thank you for reaching out and showing interest in YOLOv8! We appreciate your support and feedback.

Regarding your question about using YOLOv8 for pose/keypoint estimation, I'm glad to inform you that YOLOv8 does support pose/keypoint estimation as one of its computer vision tasks. This task involves detecting and tracking specific points or keypoints in an image or video frame, which can be useful for applications like tracking movement or estimating pose.

To use YOLOv8 for pose/keypoint estimation, you can follow the same process as for other computer vision tasks with YOLOv8. First, you would need to train the model on a custom dataset containing images with annotated keypoints or points of interest. Then, you can use the trained model to detect and track those keypoints in new images or video frames.

The annotations for keypoints or points of interest can be included in your dataset in a similar format as the bounding box annotations for object detection. Each annotation should include the coordinates or pixel positions of the keypoints along with the corresponding class label if applicable.

During the training process, YOLOv8 will learn to detect and estimate the keypoints based on the provided annotations and optimize its performance through the training iterations.

I hope this clarifies your question. If you have any further inquiries or need assistance with using YOLOv8 for pose/keypoint estimation, please feel free to ask. We are here to help!

Best regards,
Glenn Jocher (Ultralytics Team)
