### ISSUE TITLE
Support YAML structure using custom dataset in COCO format

### ISSUE THREAD

**Issue by rose-jinyang** [ultralytics/ultralytics#3521]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hello
How are you?
Thanks contributing to this project.
I am going to train an instance segmentation model on my custom dataset in COCO format.
Here, I do NOT want to convert the original COCO format to YOLO format.
Could you support YAML structure using custom dataset in COCO annotation  format?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@rose-jinyang hi there,

Thank you for your interest in YOLOv8 and for contributing to the project!

Currently, YOLOv8 supports training on custom datasets in COCO format by converting them to the YOLO format. However, it does not have native support for YAML structure with COCO annotations. The COCO annotations are typically converted to YOLO format to ensure compatibility with the YOLOv8 model.

While it is technically possible to add support for YAML structure with COCO annotations in YOLOv8, this would require modifications to the codebase and the repository. If you are interested in contributing to the project, we would welcome a pull request (PR) with your proposed changes! 

Please let us know if you have any further questions or need assistance with the process.

Thank you again for your support and contribution!

Warm regards,
Glenn Jocher

**Comment by rose-jinyang** [comment]
Thanks

**Comment by glenn-jocher** [comment]
@rose-jinyang hi there,

Thank you for reaching out to us and for your interest in using YOLOv8!

At the moment, YOLOv8 does not natively support the YAML structure with COCO annotations. However, YOLOv8 does support training on custom datasets in the COCO format by converting them to the YOLO format.

To use your custom dataset with YOLOv8, you would need to convert the COCO annotations to the YOLO format, which ensures compatibility with the model. You can find instructions and examples on how to perform this conversion in the YOLOv8 documentation.

If you have any further questions or need assistance with the conversion process, please don't hesitate to ask. We're here to help!

Best regards,

Glenn Jocher
