### ISSUE TITLE
Classification on other types of models

### ISSUE THREAD

**Issue by sctrueew** [ultralytics/ultralytics#3522]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, how to use models pre-trained?

I'm using this 
`yolo classify train data=\ds\sample model=efficientnet_v2_s epochs=10 imgsz=224`
but I get this error.

> raise FileNotFoundError(f"'{file}' does not exist")
> FileNotFoundError: 'efficientnet_v2_s' does not exist

**Comment by glenn-jocher** [comment]
@sctrueew hi there! Thank you for reaching out with your question about using pretrained models with YOLOv8.

To clarify, YOLOv8 does not have built-in support for classifying models. YOLOv8 is primarily designed for object detection and related tasks like segmentation, pose estimation, and tracking.

If you're looking to use pre-trained classification models, you might consider using a different repository or framework that specializes in classification tasks. There are many popular options available, such as TensorFlow's `tf.keras.applications` module or the PyTorch ecosystem.

If you have any other questions or need further assistance, feel free to ask. We're here to help!

**Comment by sctrueew** [comment]
@glenn-jocher Hi, thank you for your reply. I already used the efficientnet_v2_s model in Yolov5. [yolov5](https://github.com/ultralytics/yolov5/issues/9090)

**Comment by glenn-jocher** [comment]
@sctrueew hi there! I appreciate you reaching out. It seems like there might be some confusion regarding the efficientnet_v2_s model and its usage in YOLOv8.

I'd like to clarify that the efficientnet_v2_s model is not part of the YOLOv8 repository. It is actually part of the YOLOv5 repository, which is a separate project maintained by Ultralytics.

If you're interested in using the efficientnet_v2_s model, I recommend referring to the YOLOv5 repository for guidance and examples. They can provide more specific information on how to use the efficientnet_v2_s model within the context of YOLOv5.

If you have any further questions or need assistance with YOLOv8 specifically, feel free to ask. We're here to help!

**Comment by sctrueew** [comment]
@glenn-jocher Hi, thank you for your explanation.
