### ISSUE TITLE
How to save training runs in a different directory from /usr/src/ultralytics/run

### ISSUE THREAD

**Issue by AndreaPi** [ultralytics/ultralytics#3527]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to train YOLOv8 on a custom dataset for testing purposes (object detection). I run YOLOv8 in a Docker image based on https://github.com/ultralytics/ultralytics/blob/main/docker/Dockerfile with a few modifications to make it work in my environment. The training script is

```python
from ultralytics import YOLO

data_path = '../data/my_dataset.yaml'
n_epochs = 100
bs = 16
gpu_id = 0
verbose = True
rng = 0
validate = True

model = YOLO('yolov8n.pt')
results = model.train(
    data=data_path,
    epochs=n_epochs,
    batch=bs,
    device=gpu_id,
    verbose=verbose,
    seed=rng,
    val=validate
)
```

By default, `YOLO` saves training runs in `/usr/src/ultralytics/runs/detect`. I don't like this: I prefer to have all artifacts related to my project (training scripts, training logs, weights, etc.) in the same project (main folder w/ subfolders). How can I do that? Assume I want to write training logs to

`/workspace/myself/myproject/logs`

where of course I have writing permissions.

**NOTE**: I want to be able to specify the absolute path, or at the very least a path relative to where I'm launching the training script. I don't want to just define a subfolder of `/usr/src/ultralytics/runs/detect`

**Comment by glenn-jocher** [comment]
@AndreaPi hi there!

To save your training runs in a different directory, you can modify the `Yolo.train()` method in your training script. Instead of using the default save path (`/usr/src/ultralytics/runs/detect`), you can specify a different directory to save your training logs, weights, and other artifacts.

In your case, if you want to write the training logs to `/workspace/myself/myproject/logs`, you can modify your script as follows:

```python
from ultralytics import YOLO
import os

data_path = '../data/my_dataset.yaml'
n_epochs = 100
bs = 16
gpu_id = 0
verbose = True
rng = 0
validate = True

# Specify the save directory for training runs
save_dir = '/workspace/myself/myproject/logs'
os.makedirs(save_dir, exist_ok=True)

model = YOLO('yolov8n.pt')
results = model.train(
    data=data_path,
    epochs=n_epochs,
    batch=bs,
    device=gpu_id,
    verbose=verbose,
    seed=rng,
    val=validate,
    save_dir=save_dir
)
```

By adding the `save_dir` argument to `model.train()`, you can provide the absolute path or a path relative to where you're launching the training script. You can customize this path to suit your project's folder structure.

I hope this helps! Let me know if you have any further questions or need additional assistance.

**Comment by AndreaPi** [comment]
@glenn-jocher thanks for the reply! Unfortunately it sounds like the `.train` method doesn't have a `save_dir` parameter:

```
/opt/conda/bin/python /workspace/xxxx/configs/yolov8_n_bs16-300e.py 
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to yolov8n.pt...
100%|██████████████████████████████████████| 6.23M/6.23M [00:00<00:00, 11.6MB/s]
Traceback (most recent call last):
  File "/workspace/xxxx/configs/yolov8_n_bs16-300e.py", line 18, in <module>
    results = model.train(
  File "/usr/src/ultralytics/ultralytics/yolo/engine/model.py", line 368, in train
    self.trainer = TASK_MAP[self.task][1](overrides=overrides, _callbacks=self.callbacks)
  File "/usr/src/ultralytics/ultralytics/yolo/engine/trainer.py", line 82, in __init__
    self.args = get_cfg(cfg, overrides)
  File "/usr/src/ultralytics/ultralytics/yolo/cfg/__init__.py", line 118, in get_cfg
    check_cfg_mismatch(cfg, overrides)
  File "/usr/src/ultralytics/ultralytics/yolo/cfg/__init__.py", line 191, in check_cfg_mismatch
    raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'save_dir' is not a valid YOLO argument. Similar arguments are i.e. ['save_crop=False', 'save=True', 'save_period=-1'].

    Arguments received: ['yolo']. Ultralytics 'yolo' commands use the following syntax:

        yolo TASK MODE ARGS

        Where   TASK (optional) is one of ('detect', 'segment', 'classify', 'pose')
                MODE (required) is one of ('train', 'val', 'predict', 'export', 'track', 'benchmark')
                ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
                    See all ARGS at https://docs.ultralytics.com/usage/cfg or with 'yolo cfg'

    1. Train a detection model for 10 epochs with an initial learning_rate of 0.01
        yolo train data=coco128.yaml model=yolov8n.pt epochs=10 lr0=0.01

    2. Predict a YouTube video using a pretrained segmentation model at image size 320:
        yolo predict model=yolov8n-seg.pt source='https://youtu.be/Zgi9g1ksQHc' imgsz=320

    3. Val a pretrained detection model at batch-size 1 and image size 640:
        yolo val model=yolov8n.pt data=coco128.yaml batch=1 imgsz=640

    4. Export a YOLOv8n classification model to ONNX format at image size 224 by 128 (no TASK required)
        yolo export model=yolov8n-cls.pt format=onnx imgsz=224,128

    5. Run special commands:
        yolo help
        yolo checks
        yolo version
        yolo settings
        yolo copy-cfg
        yolo cfg

    Docs: https://docs.ultralytics.com
    Community: https://community.ultralytics.com
    GitHub: https://github.com/ultralytics/ultralytics
    

Process finished with exit code 1
```

This is my environment:

```
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
>>> torch.__version__
'2.0.0'
>>> torchvision.__version__
'0.15.0'
>>> ultralytics.__version__
'8.0.126'
```

**Comment by OmarD-ctrl** [comment]
@AndreaPi Hi, I want to confirm it yolov8 does not have this option but yolov5 does
The only solution that i found is copying the wights fron runs directory continiously.
An alternative is changing the #Dirs section in ultralytics/yolo/enginge/trainer.py and I am still working on it to find how to change the path.
Thanks

**Comment by AndreaPi** [comment]
Hi, I found how to do it with YOLOv8:

```
from ultralytics import YOLO

experiment = 'yolov8_nano_bs8_300e'
data_path = 'configs/mydataset.yaml'
n_epochs = 300
bs = 8
n_workers = bs
gpu_id = 0
verbose = True
rng = 0
validate = True
patience = 0
project = '../../logs/'

model = YOLO('yolov8n.pt')

results = model.train(
    data=data_path,
    epochs=n_epochs,
    batch=bs,
    device=gpu_id,
    verbose=verbose,
    seed=rng,
    val=validate,
    project=project,
    name=experiment,
    workers=n_workers,
    patience=patience
)

```

The `project` parameter contains the path where all training runs are saved, while `name` allows you to specify a specific subfolder of `project` where you want your actual run to be saved. @glenn-jocher you may want to make this more clear in YOLOv8 documentation. Thanks for the great piece of software!

**Comment by iperminov-mythic** [comment]
Putting a path in `project`  makes wandb unhappy: `wandb.errors.UsageError: Invalid project name '/foo': cannot contain characters '/,\\,#,?,%,:', found '/'`

**Comment by AndreaPi** [comment]
@iperminov-mythic thankfully, I don't use wandb, so that works for me. If that's an issue for you, I suggest you open a new issue clarifying that the problem is with wandb and not with ultralytics.

**Comment by OmarD-ctrl** [comment]
@AndreaPi  Glad you found it!
I did not care at project parameter at first and I kept looking for save_dir in validator etc...
Now I understand this line in trainer.py
# Dirs
        project = self.args.project or Path(SETTINGS['runs_dir']) / self.args.task
Really thankful for your clarification. I will try it too.

**Comment by glenn-jocher** [comment]
Hi @AndreaPi,

I'm glad you found a solution to your issue with saving training runs in YOLOv8. 

In YOLOv8, you can set the `project` parameter in the `model.train()` method to specify the root directory where all training runs will be saved. This is useful if you want to organize your runs in a specific location.

Underneath the hood, YOLOv8 uses the `project` parameter to construct the save path for each run. The save path includes the `project` directory and a subdirectory for the specific run name.

I hope this clarifies how to control the location where your YOLOv8 training runs are saved.

Let me know if you have any further questions or need additional assistance.

**Comment by SERPENT47** [comment]
> Hi @AndreaPi,
> 
> I'm glad you found a solution to your issue with saving training runs in YOLOv8.
> 
> In YOLOv8, you can set the `project` parameter in the `model.train()` method to specify the root directory where all training runs will be saved. This is useful if you want to organize your runs in a specific location.
> 
> Underneath the hood, YOLOv8 uses the `project` parameter to construct the save path for each run. The save path includes the `project` directory and a subdirectory for the specific run name.
> 
> I hope this clarifies how to control the location where your YOLOv8 training runs are saved.
> 
> Let me know if you have any further questions or need additional assistance.

Thanks man! Saved my day

**Comment by glenn-jocher** [comment]
@SERPENT47 you're very welcome! I'm glad to hear that the information was useful and helped solved your issue. Don't hesitate to reach out if you have any more questions or need further assistance. Happy training!

**Comment by drbilal216** [comment]
@glenn-jocher I have trained a model with 100 epochs now I’m using resume=True with last.pt to start training from the checkpoint. I’m Using google colab, the problem is that now instead of root directory, I want to save weights in my Google drive, but unable to do so while running these codes.
```python
# Specify the save directory for training runs
save_dir = '/content/drive/MyDrive/ComputerVision/myproject/logs'
os.makedirs(save_dir, exist_ok=True)

# model arguments
data_path = '/content/data_train_2442_val_277_test_56/data.yaml' # My yaml
Project =  '/content/drive/MyDrive/ComputerVision/myproject/logs/' #save_dir # weight save path
experiment = '/content/drive/MyDrive/ComputerVision/myproject/logs/1.yolov8_m_resume_100+300e' #'1.yolov8_m_resume_100+300e' # experiment name
n_epochs = 2 #100
bs = 16 #8
verbose = False
validate = True
patience = 5

m_path = '/content/drive/MyDrive/ComputerVision/Weights/2.data_train_2442_val_277_test_56/last.pt'
from ultralytics import YOLO
model = YOLO(m_path)  # load last.pt
results = model.train(data=data_path, epochs=n_epochs, batch=bs, patience=patience, resume=True, val=validate, verbose =verbose, project=Project, name=experiment)
```

**Comment by glenn-jocher** [comment]
@drbilal216 when training with YOLOv8 and you wish to store your checkpoints to Google Drive while using Google Colab, ensure that you have mounted your Google Drive and are specifying the correct paths in the `project` and `name` arguments. 

For the `project` argument, provide the path to the directory where you want to store your training runs. For the `name` argument, provide a string that you would like to be the name of this specific run's output folder within the project directory.

Below is an updated segment where you set `project` to the base directory and `name` to the name of the folder for this specific training run:

```python
...
project = '/content/drive/MyDrive/ComputerVision/myproject/logs'  # Base directory for saving runs
experiment = '1.yolov8_m_resume_100+300e'  # Name of this specific run
...
results = model.train(
    data=data_path,
    epochs=n_epochs,
    batch=bs,
    patience=patience,
    resume=True,
    val=validate,
    verbose=verbose,
    project=project,
    name=experiment
)
```

With these settings, YOLO will save your training weights and logs to `/content/drive/MyDrive/ComputerVision/myproject/logs/1.yolov8_m_resume_100+300e`. Make sure that the path specified in `project` exists and that Google Drive is successfully mounted on Colab to access the specified path.

**Comment by drbilal216** [comment]
> @drbilal216 when training with YOLOv8 and you wish to store your checkpoints to Google Drive while using Google Colab, ensure that you have mounted your Google Drive and are specifying the correct paths in the `project` and `name` arguments.
> 
> For the `project` argument, provide the path to the directory where you want to store your training runs. For the `name` argument, provide a string that you would like to be the name of this specific run's output folder within the project directory.
> 
> Below is an updated segment where you set `project` to the base directory and `name` to the name of the folder for this specific training run:
> 
> ```python
> ...
> project = '/content/drive/MyDrive/ComputerVision/myproject/logs'  # Base directory for saving runs
> experiment = '1.yolov8_m_resume_100+300e'  # Name of this specific run
> ...
> results = model.train(
>     data=data_path,
>     epochs=n_epochs,
>     batch=bs,
>     patience=patience,
>     resume=True,
>     val=validate,
>     verbose=verbose,
>     project=project,
>     name=experiment
> )
> ```
> 
> With these settings, YOLO will save your training weights and logs to `/content/drive/MyDrive/ComputerVision/myproject/logs/1.yolov8_m_resume_100+300e`. Make sure that the path specified in `project` exists and that Google Drive is successfully mounted on Colab to access the specified path.

@glenn-jocher I have previously trained a model with 100 epochs without specifying the project name, when I use its last.pt and with resume run for extra epochs, I encounter 2 problems.
1.	It runs for 100 more epochs, even if I specify 5 epochs.
2.	It saves the weights in root directory, even if I specify project name and location.
But when I run the model from scratch with project name and location, it saves the data in the desired location.

**Comment by glenn-jocher** [comment]
@drbilal216 for resuming training in YOLOv8 with checkpoints saved to a specific directory on Google Drive, ensure:

1. Google Drive is correctly mounted in Colab.
2. The `project` argument points to the desired base directory for runs.
3. The `name` argument identifies the specific run.

When resuming:
- Use `resume` with the path to `last.pt` that matches the `project` and `name` settings.
- Set `epochs` to the total desired epochs, e.g., for 5 additional epochs after 100, set to 105.

If the weights save elsewhere, double-check paths and mount status. If you still face a problem, please raise an issue with detailed info on steps and observations.

**Comment by drbilal216** [comment]
> @drbilal216 for resuming training in YOLOv8 with checkpoints saved to a specific directory on Google Drive, ensure:
> 
> 1. Google Drive is correctly mounted in Colab.
> 2. The `project` argument points to the desired base directory for runs.
> 3. The `name` argument identifies the specific run.
> 
> When resuming:
> 
> * Use `resume` with the path to `last.pt` that matches the `project` and `name` settings.
> * Set `epochs` to the total desired epochs, e.g., for 5 additional epochs after 100, set to 105.
> 
> If the weights save elsewhere, double-check paths and mount status. If you still face a problem, please raise an issue with detailed info on steps and observations.

Fix my issue, seems like when I ran first epochs without specifying any project name and then continuing from its last.pt but this time with a project name was causing issue. What works for me is that I have trained the model from start with project name and now when I resume the model with same project name everything is working fine. Seems to me specifying a project name is good practice.
I have another question my team is doing annotating daily and this will continue for a while so should I 
1.	Trained the model from the start.
2.	Add new data in the previous trained data and resume.
3.	Trained on only new data with resume.
4.	Freeze some layers and train on only new data.

**Comment by glenn-jocher** [comment]
@drbilal216 Glad to hear specifying a project name resolved the issue! For incorporating new annotations into training:

1. It's not necessary to start from scratch.
2. Typically, you should add new data to the previous dataset and resume training (`last.pt`). This approach benefits from existing learned features while adapting to the new data.
3. Training only on the new data could lead to forgetting previously learned features unless you periodically revisit the old data (incremental learning).
4. Freezing layers is not generally recommended unless you have a small amount of new data and wish to fine-tune only the higher-level features.

Therefore, option 2 is the most balanced and effective approach in most scenarios. Keep validating on a diverse set of images to ensure model robustness.

**Comment by drbilal216** [comment]
> @drbilal216 Glad to hear specifying a project name resolved the issue! For incorporating new annotations into training:
> 
> 1. It's not necessary to start from scratch.
> 2. Typically, you should add new data to the previous dataset and resume training (`last.pt`). This approach benefits from existing learned features while adapting to the new data.
> 3. Training only on the new data could lead to forgetting previously learned features unless you periodically revisit the old data (incremental learning).
> 4. Freezing layers is not generally recommended unless you have a small amount of new data and wish to fine-tune only the higher-level features.
> 
> Therefore, option 2 is the most balanced and effective approach in most scenarios. Keep validating on a diverse set of images to ensure model robustness.

@glenn-jocher really appreciate quick response and for this information. I have few more questions.
1.  The model is detecting slippers as safety boots and hand as gloves, so if I add more unannotated images of slippers and hand will it helps the model to deal with false positives. Will it help as background images for model to differentiate between slippers and boots?
2. I’m working with multiple live cameras and there are places where workers rarely go, to tackle this while data collection, I’m doing augmentation on those cameras, my question is can I use some other technique like generating (Synthetic Data) or what is the best approach for augmentation.

**Comment by glenn-jocher** [comment]
@drbilal216 To address false positives:

1. Adding unannotated images may not directly help; instead, include more annotated examples of slippers and hands, distinguishing them clearly from safety boots and gloves.
2. Synthetic data can be helpful, especially in underrepresented scenarios. Consider diversifying your data with scene context, using proper augmentation techniques that mirror real-world variances. Experiment with lighting, weather, and occlusions. Check the balance between your synthetic and real data to maintain model reliability.

For best augmentation strategies, consult our documentation and explore a mix of geometric and photometric augmentations. Remember to validate your model's performance with a robust validation set.

**Comment by drbilal216** [comment]
@glenn-jocher  We are not training model for the slippers and hands classes. We only want to detect if gloves or boots are present. Sometimes the model identifies hands as gloves and slippers as boots.
What should we do in this case?

**Comment by glenn-jocher** [comment]
@drbilal216 To reduce false positives for non-target classes:

- Add negative examples of slippers and hands to your training dataset and annotate them as 'background' if your dataset format allows, or leave them unannotated otherwise.
- Increase the diversity of the 'boots' and 'gloves' classes with examples in different contexts to improve feature distinction.
- Consider hard negative mining by reviewing false positives and adding similar cases to the training set.

Review and adjust confidence thresholds and non-maximum suppression parameters for predictions.

**Comment by glenn-jocher** [comment]
@drbilal216 If you've reached the maximum epochs and want to continue training with new data, you should initiate a new training session without the `resume` flag, but still using the `last.pt` from the previous training as the starting model. This way, you'll retain the knowledge from the previous training while allowing the model to learn from the new data. Make sure to set the `epochs` to your new desired total and adjust the `project` and `name` parameters to organize your training runs effectively. Keep validating to monitor the model's performance on the updated dataset.

**Comment by Fade-r** [comment]
Found a way to both change runs directory AND use wandb without causing the `wandb.errors.UsageError: Invalid project name '/foo': cannot contain characters '/,\\,#,?,%,:', found '/'` error:
```
from ultralytics import YOLO
from ultralytics.models.yolo.detect import DetectionTrainer
# from ultralytics.utils import SettingsManager  # if use settings
from ultralytics.utils.files import increment_path
from pathlib import Path

project = 'Your_project_name'

runs_dir = 'path/to/runs'
# runs_dir = Path(SettingsManager()["runs_dir"])  # if use settings
save_dir = increment_path(runs_dir/project, exist_ok=True or False)

class MyTrainer(DetectionTrainer):
    def __init__(self, overrides=None, _callbacks=None):
        super().__init__('config.yaml', overrides, _callbacks)

if __name__ == '__main__':
    model = YOLO('yolov8n.yaml')
    results = model.train(
        trainer=MyTrainer,
        data='path/to/data.yaml',
        project=project,
        save_dir=save_dir
    )
```

A `config.yaml` file is needed this way:
```
# SAME WITH `ultralytics/cfg/default.yaml` #

# Additional settings
save_dir:
```

**Comment by glenn-jocher** [comment]
@Fade-r hey there! 😊 Fantastic work finding a solution to use a custom runs directory with wandb and avoid those tricky name errors! Your code example looks great and is super helpful for others trying to achieve the same setup. 

Just a quick tip to keep things tidy: make sure your `config.yaml` mirrors the necessary settings from `ultralytics/cfg/default.yaml` and includes your custom `save_dir` path. This approach maintains the flexibility of YOLOv8 while smoothly integrating with wandb. Thanks for sharing your solution with the community! 👍 

Feel free to reach out if you have more insights or need further assistance. Happy coding!

**Comment by ulrichkemka** [comment]
Hello @glenn-jocher 
Please how to retrieve the storage path after training the model?
like 
```
def train(
    base_model: str | Path,
    data: Path,
    epochs: int = 60,
    imgsz: int = 640,
    batch: int = 16,
    device: list[int] | str | None = None,
    **kwargs,
):
    """
    Train a Yolo base model with data in the data directory.

    Args:
        base_model (str | Path): base model name
        data (Path): training data directory
        epochs (int, optional): epochs. Defaults to 60.
        imgsz (int, optional): image size. Defaults to 640.
        batch (int, optional): batch size. Defaults to 16.
        device (list[int] | str | None, optional): device to use. Defaults to None.
    """
    model = YOLO(base_model)  # load a pretrained model
    results = model.train(
        data=data, epochs=epochs, imgsz=imgsz, batch=batch, device=device, **kwargs
    )
    return results
   
```

I run function and i want get storage path
```
results = train("yolov8m.pt", data=dataset_dir / "dataset.yaml", epochs=1, batch=64, device=[0, 1])
results_dir = Path(results.project)  or  Path(results.save_dir) 
print(f"Results saved to {results}")

```

**Comment by glenn-jocher** [comment]
Hello @ulrichkemka,

Thank you for your question! To retrieve the storage path after training your model, you can access the `save_dir` attribute from the `results` object returned by the `train` method. Here's how you can modify your function to print the results directory:

```python
from ultralytics import YOLO
from pathlib import Path

def train(
    base_model: str | Path,
    data: Path,
    epochs: int = 60,
    imgsz: int = 640,
    batch: int = 16,
    device: list[int] | str | None = None,
    **kwargs,
):
    """
    Train a Yolo base model with data in the data directory.

    Args:
        base_model (str | Path): base model name
        data (Path): training data directory
        epochs (int, optional): epochs. Defaults to 60.
        imgsz (int, optional): image size. Defaults to 640.
        batch (int, optional): batch size. Defaults to 16.
        device (list[int] | str | None, optional): device to use. Defaults to None.
    """
    model = YOLO(base_model)  # load a pretrained model
    results = model.train(
        data=data, epochs=epochs, imgsz=imgsz, batch=batch, device=device, **kwargs
    )
    return results

# Run the training function
results = train("yolov8m.pt", data=dataset_dir / "dataset.yaml", epochs=1, batch=64, device=[0, 1])

# Retrieve and print the results directory
results_dir = Path(results.save_dir)
print(f"Results saved to {results_dir}")
```

This will print the path where the training results are saved. The `save_dir` attribute contains the directory path where all the training artifacts, including logs and model weights, are stored.

If you encounter any issues or have further questions, please ensure you are using the latest versions of `torch` and `ultralytics`. If the problem persists, providing a minimum reproducible example would be very helpful for us to investigate further. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

Happy training! 😊

**Comment by ulrichkemka** [comment]
@glenn-jocher 
Thank you for your answer.
Your code is similar to mine.


**Bug description:**
I try to retrieve the storage path after training the model
I tested the code on my local environment (by reducing the parameter values), I have the storage path displayed.
But when I do it on the workstation, I get this error message:
```py
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], [line 1](vscode-notebook-cell:?execution_count=7&line=1)
----> [1](vscode-notebook-cell:?execution_count=7&line=1) results_dir = Path(results.save_dir) 
      [2](vscode-notebook-cell:?execution_count=7&line=2) print(f"Results saved to {results_dir}")

AttributeError: 'NoneType' object has no attribute 'save_dir'
```

### My MRE
Here is some information about my workstation.

```py
import torch

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

# output:  Setup complete. Using torch 2.3.1+cu121 (NVIDIA RTX A6000)
```

Packages list:

```bash
(venv_name) myname@PC-123456:~/workspace/projetc$ poetry install
Updating dependencies
Resolving dependencies... (15.8s)

Package operations: 0 installs, 10 updates, 0 removals

  - Updating botocore (1.34.127 -> 1.34.129)
  - Updating psutil (5.9.8 -> 6.0.0)
  - Updating tifffile (2024.5.22 -> 2024.6.18)
  - Updating opencv-python-headless (4.10.0.82 -> 4.10.0.84)
  - Updating scikit-image (0.23.2 -> 0.24.0)
  - Updating setuptools (70.0.0 -> 70.1.0)
  - Updating boto3 (1.34.127 -> 1.34.129)
  - Updating opencv-python (4.10.0.82 -> 4.10.0.84)
  - Updating lapx (0.5.9 -> 0.5.9.post1)
  - Updating ultralytics (8.2.34 -> 8.2.35)

Writing lock file
```

The `train` function does not change.
```py
from ultralytics import YOLO
from pathlib import Path

def train(
    base_model: str | Path,
    data: Path,
    epochs: int = 60,
    imgsz: int = 640,
    batch: int = 16,
    device: list[int] | str | None = None,
    **kwargs,
):
    """
    Train a Yolo base model with data in the data directory.

    Args:
        base_model (str | Path): base model name
        data (Path): training data directory
        epochs (int, optional): epochs. Defaults to 60.
        imgsz (int, optional): image size. Defaults to 640.
        batch (int, optional): batch size. Defaults to 16.
        device (list[int] | str | None, optional): device to use. Defaults to None.
    """
    model = YOLO(base_model)  # load a pretrained model
    results = model.train(
        data=data, epochs=epochs, imgsz=imgsz, batch=batch, device=device, **kwargs
    )
    return results

# Run the training function
results = train("yolov8m.pt", data=dataset_dir / "dataset.yaml", epochs=1, batch=64, device=[0, 1])

# Retrieve and print the results directory
results_dir = Path(results.save_dir)
print(f"Results saved to {results_dir}")
```

On output, I have this error:
```py
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], [line 1](vscode-notebook-cell:?execution_count=7&line=1)
----> [1](vscode-notebook-cell:?execution_count=7&line=1) results_dir = Path(results.save_dir) 
      [2](vscode-notebook-cell:?execution_count=7&line=2) print(f"Results saved to {results_dir}")

AttributeError: 'NoneType' object has no attribute 'save_dir'
```

Thank you for your help

**Comment by glenn-jocher** [comment]
Hello @ulrichkemka,

Thank you for providing detailed information about your setup and the issue you're encountering. It looks like you're experiencing an `AttributeError` because `results.save_dir` is `None` on your workstation.

To help us investigate further, could you please ensure the following:

1. **Minimum Reproducible Example**: Verify that your provided code is the minimum reproducible example. If not, please simplify it further. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

2. **Package Versions**: Ensure you are using the latest versions of `torch` and `ultralytics`. From your provided package list, it seems you are using `ultralytics 8.2.35`. Please confirm this is the latest version.

3. **Check for Errors During Training**: Sometimes, the `results` object might not be properly populated if there are errors during training. Ensure that the training process completes successfully without any interruptions.

Here’s a slightly modified version of your code to include some additional checks and logging:

```python
from ultralytics import YOLO
from pathlib import Path

def train(
    base_model: str | Path,
    data: Path,
    epochs: int = 60,
    imgsz: int = 640,
    batch: int = 16,
    device: list[int] | str | None = None,
    **kwargs,
):
    """
    Train a Yolo base model with data in the data directory.

    Args:
        base_model (str | Path): base model name
        data (Path): training data directory
        epochs (int, optional): epochs. Defaults to 60.
        imgsz (int, optional): image size. Defaults to 640.
        batch (int, optional): batch size. Defaults to 16.
        device (list[int] | str | None, optional): device to use. Defaults to None.
    """
    model = YOLO(base_model)  # load a pretrained model
    results = model.train(
        data=data, epochs=epochs, imgsz=imgsz, batch=batch, device=device, **kwargs
    )
    return results

# Run the training function
results = train("yolov8m.pt", data=dataset_dir / "dataset.yaml", epochs=1, batch=64, device=[0, 1])

# Check if results.save_dir is None
if results.save_dir is None:
    print("Error: save_dir is None. Please check if the training completed successfully.")
else:
    # Retrieve and print the results directory
    results_dir = Path(results.save_dir)
    print(f"Results saved to {results_dir}")
```

If `results.save_dir` is still `None`, please provide any additional logs or error messages that appear during the training process. This will help us diagnose the issue more effectively.

Thank you for your patience and cooperation! 😊

**Comment by ulrichkemka** [comment]
@glenn-jocher , Thank you for your answer.

I have a same proble for the predict method.
I can't extract the path of results

```py
from ultralytics import YOLO
from pathlib import Path

def predict(
    model_path: str | Path,
    source: str | Path,
    save_txt: bool = True,
    save_conf: bool = True,
):
    """
    Run prediction on a source using the given model

    Args:
        model_path (str | Path): the model to use for prediction
        source (str | Path): the source of data to predict
        save_txt (bool, optional): save detection results in a txt file. Defaults to True.
        save_conf (bool, optional): save confidence score for each detection.
            Defaults to True.

    Returns:
        list: A list of detection results.
    """
    model = YOLO(model_path)

    # Run inference on the source
    results = model.predict(source, stream=False, save_txt=save_txt, save_conf=save_conf)
    return results

# Load the path of the predicting model results

results_predict_dir = Path(results_predict.path)
print(f"Results detect saved to {results_predict_dir}")
```

Here, we have the errors message
```py
{
	"name": "AttributeError",
	"message": "'list' object has no attribute 'path'",
	"stack": "---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], line 1
----> 1 results_predict_dir = Path(results_predict.path)
      2 print(f\"Results detect saved to {results_predict_dir}\")

AttributeError: 'list' object has no attribute 'path'"
}
```

PS: All my package are update
```toml
python = "~3.10"
tqdm = "^4.66.4"
numpy = "^1.26.4"
ultralytics = "^8.2.38" #the latest version
fiftyone = "^0.24.0"
opencv-python = "^4.10.0.82"
selenium = "^4.21.0"
lapx = "^0.5.9"
moviepy = "^1.0.3"
```

**Comment by glenn-jocher** [comment]
To improve accuracy, ensure your dataset includes diverse examples of gloves and boots, clearly distinguishing them from similar objects. Consider adding more annotated images with these distinctions to help the model learn better.

**Comment by Petros626** [comment]
@AndreaPi your suggestions helps to store results to a specified folder, but when i run training it still saves under the old path `runs/detect/tune/...` data. I'm using `Ray Tune` and expected the default path `~/ray_results is used`.

**Comment by idra79haza** [comment]
# Changing the Default Save Path for Ultralytics YOLO

In recent versions of Ultralytics YOLO (e.g., 8.3.13), the `save_dir` argument is no longer working as expected. Some users suggest using `name` as a relative path (e.g., `"../../runs"`), but this approach causes issues when using tools like WandB.

If you want to change the **default saving path**, you need to modify the source code of Ultralytics directly.

## Steps to Modify the Default Save Path

1. Locate where Ultralytics is installed in your environment.
2. Open the file `cfg/__init__.py`.
3. Find the function `get_save_dir()` and modify it as follows:

### Original Code
```python
def get_save_dir(args, name=None):
    from ultralytics.utils.files import increment_path

    project = args.project or (ROOT.parent / "tests/tmp/runs" if TESTS_RUNNING else RUNS_DIR) / args.task
    name = name or args.name or f"{args.mode}"
    save_dir = increment_path(Path(project) / name, exist_ok=args.exist_ok if RANK in {-1, 0} else True)
    return Path(save_dir)
```

### Modified Code
Replace the function with the following:

```python
def get_save_dir(args, name=None):
    """
    Returns the directory path for saving outputs, derived from arguments or default settings.

    Args:
        args (SimpleNamespace): Namespace object containing configurations such as 'project', 'name', 'task',
            'mode', and 'save_dir'.
        name (str | None): Optional name for the output directory. If not provided, it defaults to 'args.name'
            or the 'args.mode'.

    Returns:
        (Path): Directory path where outputs should be saved.

    Examples:
        >>> from types import SimpleNamespace
        >>> args = SimpleNamespace(project="my_project", task="detect", mode="train", exist_ok=True)
        >>> save_dir = get_save_dir(args)
        >>> print(save_dir)
        my_project/detect/train
    """
    if getattr(args, "save_dir", None):
        save_dir = args.save_dir
    else:
        from ultralytics.utils.files import increment_path

        import os
        project = args.project or (ROOT.parent / "tests/tmp/runs" if TESTS_RUNNING else RUNS_DIR) / args.task
        name = name or args.name or f"{args.mode}"
        save_dir = increment_path(
            os.path.join(f"/home/ubuntu/custom/test1/results", f"{project}/{name}"),
            exist_ok=args.exist_ok if RANK in {-1, 0} else True
        )

    return Path(save_dir)
```

### Explanation of Changes
1. **Custom Save Path**: The base directory for saved runs is now `/home/ubuntu/custom/test1/results`.
2. **Dynamic Path Creation**: The `increment_path` function ensures that the directory is unique and avoids overwriting existing directories.
3. **Compatibility with Existing Logic**: The `args.exist_ok` flag ensures compatibility with existing configurations.

## Example Usage
After applying this change, any YOLO training run will save results under `/home/ubuntu/custom/test1/results/<project>/<name>`.

**Comment by glenn-jocher** [comment]
Thank you for sharing your detailed approach to modifying the default save path in Ultralytics YOLO. While editing the source code as described is a valid option, a more maintainable solution would be to set the `project` and `name` parameters during training or update the `runs_dir` setting dynamically using the `SettingsManager`. For example:

```python
from ultralytics import settings
settings.update({"runs_dir": "/home/ubuntu/custom/test1/results"})
```

This avoids source code modifications and keeps your YOLO installation consistent with future updates. For further details, refer to the [Settings Documentation](https://docs.ultralytics.com/quickstart/#ultralytics-settings).
