### ISSUE TITLE
How to use yolov8-rtdetr?

### ISSUE THREAD

**Issue by Kamizato-Ayaka** [ultralytics/ultralytics#3530]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I noticed that there is a model yaml file named "yolov8-rtdetr in the directory of models. Is it used for detection tasks? How should I use it? If I configure it directly like this: "model=YOLO ('yolov8l-rtdetr. yaml ')", a keyerror will occur:

~/jupyterlab/ultralytics-main/ultralytics/yolo/engine/model.py in _new(self, cfg, task, verbose)
    136         self.cfg = cfg
    137         self.task = task or guess_model_task(cfg_dict)
--> 138         self.model = TASK_MAP[self.task][0](cfg_dict, verbose=verbose and RANK == -1)  # build model
    139         self.overrides['model'] = self.cfg
    140 

KeyError: None

I want to know how to use it. thanks

**Comment by Kayzwer** [comment]
```
from ultralytics import RTDETR


if __name__ == "__main__":
    model = RTDETR("/path/to/.pt")
```

**Comment by glenn-jocher** [comment]
@djandrqh hi there! Thank you for reaching out to us. If you want to use the `yolov8-rtdetr` model for detection tasks, here's how you can do it:

1. First, make sure you have the `ultralytics` package installed.

2. Import the `RTDETR` class from the `ultralytics` module.

3. Instantiate an instance of the `RTDETR` class, passing the path to the `.pt` file of the model as the argument.

   For example:
   ```python
   from ultralytics import RTDETR

   if __name__ == "__main__":
       model = RTDETR("/path/to/.pt")
   ```

   Replace `"/path/to/.pt"` with the actual path to the `.pt` file of your `yolov8-rtdetr` model.

This will create an instance of the `RTDETR` model that you can use for detection tasks.

If you encounter any issues or need further assistance, please feel free to ask.

**Comment by glenn-jocher** [comment]
@djandrqh also you can load the rtdetr YAMLs directly for training, i.e.:

```python
model=RTDETR('yolov8l-rtdetr.yaml')
```

**Comment by ovidedecroly** [comment]
@glenn-jocher , hello. How to use pre-trained yolov8 + RTDETR? thanks

**Comment by glenn-jocher** [comment]
@ovidedecroly hello! I'm glad you are looking to use the pre-trained YOLOv8 model with RTDETR (Realtime Detection Transformers).

To take advantage of a pre-trained YOLOv8 model with RTDETR, follow these steps:

1. Ensure you have the latest `ultralytics` package installed.
2. Load the pre-trained weights using the `RTDETR` class directly.
3. The weights can be specified by their respective file name if they are present in your local directory, or they can be automatically downloaded if you specify one of the pre-trained model weights hosted by Ultralytics.

Make sure that you follow the expected directory structure and file naming conventions to avoid errors. The Ultralytics documentation has specific instructions on how to properly set up your environment, load pre-trained weights, and how to interact with the various functionality that the `RTDETR` class provides.

It's important to ensure consistency in between the version of the Ultralytics package you're using and the pre-trained model weights, as there may be compatibility issues if there is a mismatch.

Remember to also verify the input data format and any specific pre-processing steps that might be required when using pre-trained models for your tasks to get optimal performance.

Happy coding, and thank you for using YOLOv8 with RTDETR. If you have any more questions, feel free to ask!

**Comment by felipetobars** [comment]
@ovidedecroly Were you able to figure out how to train a YOLOv8-rtdetr with initial .pt weights?

**Comment by Salmankm93** [comment]
> @djandrqh also you can load the rtdetr YAMLs directly for training, i.e.:
> 
> model=RTDETR('yolov8l-rtdetr.yaml')

Hello @glenn-jocher, if I want to use the 'Yolov8-rtdetr.yaml', should I run the command "from ultralytics import RTDETR"

**Comment by glenn-jocher** [comment]
@Salmankm93 Yes, that's exactly right. To use the RTDETR model with the YAML file, you need to import the RTDETR class:

```python
from ultralytics import RTDETR

# Load the model from YAML
model = RTDETR('yolov8l-rtdetr.yaml')

# You can then use it for training
results = model.train(data="your_dataset.yaml", epochs=100, imgsz=640)

# Or for inference
results = model("path/to/image.jpg")
```

This is the correct approach for initializing an RTDETR model from a configuration file rather than pre-trained weights.

**Comment by ovidedecroly** [comment]
Hi Glen, How to use Metric Accuracy, IoU and CIoU in yolov8 detect not cls?
Thanks

وَ السَّلاَمُ عَلَيْكُمْ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ
Best regards,

*Ovide Decroly Wisnu Ardhi, S.T., M.Eng*
Universitas Sebelas Maret
Jl. Ir. Sutami 36 A Kentingan Surakarta, 57126 Indonesia
Phone: +62-271-663450

Mobile: +6282220301004
Whatapps: +6282220301004
Website: http://ovide.id/

Pada Sen, 28 Apr 2025 04.57, Glenn Jocher ***@***.***>
menulis:
