### ISSUE TITLE
rtdetr export torchscript error!!

### ISSUE THREAD

**Issue by MINGtoMING** [ultralytics/ultralytics#3535]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

![image](https://github.com/ultralytics/ultralytics/assets/95759947/739018e0-887d-49ef-9baf-632dc4bbb81c)

![image](https://github.com/ultralytics/ultralytics/assets/95759947/69231fbc-fa22-497d-aa3e-21cbabc41b77)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Laughing-q the RTDETR output is a tuple of Tensors, but the last element is None, not sure if that is causing this torchscript error?

**Comment by glenn-jocher** [comment]
@MINGtoMING you're welcome! I'm glad to assist you with any questions you have. If you have any further queries or concerns regarding YOLOv8, please don't hesitate to ask.
