### ISSUE TITLE
how can i implement them for a project with real time

### ISSUE THREAD

**Issue by aTunass** [ultralytics/ultralytics#354]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i have read and used the code in 'docs' and their fps result is only about 10fps, while yolov7 is 30-35fps, i tried to review the predict.py file but I don't understand. Am I wrong somewhere. So hope you can help me
![image](https://user-images.githubusercontent.com/119738823/212483524-e391173e-2f44-456d-b4dd-acd883b34f0f.png)

**Comment by AyushExel** [comment]
@aTunass you can set return_outputs=Fasle to speed things up. Enabling outputs adds latency. Speed may also vary depending upon the model you choose

**Comment by aTunass** [comment]
i tried and it returns outputs is None, i'm using ultralytics-8.0.6

**Comment by AyushExel** [comment]
Yes currently if you enable outputs speed will be reduced but we're working on a fix to address this. But without the outputs you should get the fastest speeds.

**Comment by aTunass** [comment]
![image](https://user-images.githubusercontent.com/119738823/212487182-f67b1b1d-87be-458d-884c-92aa19180467.png)
this is my result in yolov8
![image](https://user-images.githubusercontent.com/119738823/212487205-e9b9519b-3f02-496b-b487-b985966705bc.png)
this is in yolov7
here is the result in yolov7 and yolov8, can see v8 is much faster. but i can load yolov7 with high fps, so i think the problem is in predict file, in yolov7 i can understand and adjust the code but in yolov8 i can't do it right now, so hopefully soon there is 'code for deploy' with higher fps than now

**Comment by AyushExel** [comment]
Yes currently we are working on it. It should be out within a few days

**Comment by yaoshanliang** [comment]
> 

Is this method calculating FPS correct?

**Comment by pderrenger** [comment]
@yaoshanliang yes, the method for calculating FPS in YOLOv8 is correct. If you're experiencing discrepancies, it might be due to specific hardware configurations or settings.
