### ISSUE TITLE
YOLOv8 Pose-estimation txt files

### ISSUE THREAD

**Issue by AshishRaghani23** [ultralytics/ultralytics#3541]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Hello, I have use yolov8l-pose.pt on images for pose estimation and save their txt files for same. In images one person is fully visible in image and all 17 keypoints are visible but second person's head only visible in image and it's all 17 keypoints values save in txt file which is wrong. kindly look into this. Here I'm attaching image and txt file for references.

![test](https://github.com/ultralytics/ultralytics/assets/98545345/fb2a6531-ba0d-49cc-8229-36ecfff018bb)

0 0.48125 0.468981 0.140625 0.676852 0.452597 0.220414 0.457903 0.2066 0.45318 0.205143 0.487874 0.202771 0.476193 0.193337 0.518825 0.290765 0.479555 0.251983 0.534218 0.419136 0.471587 0.33286 0.476884 0.406546 0.436557 0.361915 0.500594 0.479578 0.478875 0.454378 0.484127 0.615122 0.485238 0.576855 0.475615 0.76392 0.497476 0.685193
0 0.71224 0.925463 0.111979 0.143519 0.680156 0.918168 0.680792 0.916146 0.695788 0.91671 0.688384 0.951418 0.748596 0.940323 0.679437 0.991589 0.763706 0.982582 0.664891 0.998989 0.738741 0.989614 0.673551 0.994388 0.684345 0.999104 0.695662 0.98266 0.753482 0.974123 0.677772 0.945588 0.724974 0.930752 0.69127 0.969289 0.725386 0.974794

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AshishRaghani23 thanks for the bug report! It looks like the xy coordinates need obscured outputs too, i.e. `<x, y, obscured>`. I'll add a TODO for this.

**Comment by AshishRaghani23** [comment]
@glenn-jocher Thank you quick reply.

**Comment by glenn-jocher** [comment]
@AshishRaghani23 great news 😃! Your original issue may now be resolved ✅ in PR #3547. This PR should merge to `main` soon and then will be part of the next patch release within 48 hours.

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by AshishRaghani23** [comment]
@glenn-jocher Thank you for PR. I have made changes in results.py you did in PR #3547 but still that second person whose keypoints not visible in image I got keypoint in txt file. Here is updated codes result
![cam7_1_image_42](https://github.com/ultralytics/ultralytics/assets/98545345/c167e5bd-725f-48b1-9d3c-d2b9feeeecaa)
0 0.48125 0.468981 0.140625 0.676852 0.452597 0.220414 0.457903 0.2066 0.45318 0.205143 0.487874 0.202771 0.476193 0.193337 0.518825 0.290765 0.479555 0.251983 0.534218 0.419136 0.471587 0.33286 0.476884 0.406546 0.436557 0.361915 0.500594 0.479578 0.478875 0.454378 0.484127 0.615122 0.485238 0.576855 0.475615 0.76392 0.497476 0.685193
0 0.71224 0.925463 0.111979 0.143519 0.680156 0.918168 0.680792 0.916146 0.695788 0.91671 0.688384 0.951418 0.748596 0.940323 0.679437 0.991589 0.763706 0.982582 0.664891 0.998989 0.738741 0.989614 0.673551 0.994388 0.684345 0.999104 0.695662 0.98266 0.753482 0.974123 0.677772 0.945588 0.724974 0.930752 0.69127 0.969289 0.725386 0.974794

My question is if second person's keypoints are not visible then in txt file I should not get keypoints values, right?

**Comment by AshishRaghani23** [comment]
@glenn-jocher Okay, then why in my image I got all 17 keypoints values for second person?

**Comment by glenn-jocher** [comment]
@AshishRaghani23 just tested the PR branch, everything works correctly. Maybe your `ultralytics` was using the pip install rather than the git clone with the branch checked out. I'll merge the PR now so you can git clone. Remember once you git clone you need to cd to the ultralytics directory and `pip install -e .` for development mode.

**Comment by glenn-jocher** [comment]
@AshishRaghani23 great news 😃! Your original issue may now be resolved ✅ in PR #3547. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!
