### ISSUE TITLE
rows = outputs.shape[0], rows Value too large,Resulting in longer processing time than recognition

### ISSUE THREAD

**Issue by zhang7249** [ultralytics/ultralytics#3542]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

rows = outputs.shape[0], rows Value too large,Resulting in longer processing time than recognition

model_inputs  960*960
input_shape  1920*1024

outputs = self.session.run(None, {self.model_inputs[0].name: image_data})
# Transpose and squeeze the output to match the expected shape
outputs = np.transpose(np.squeeze(outputs[0]))
 # Get the number of rows in the outputs array
 rows = outputs.shape[0]

row = 18899

Recognition only took 14 milliseconds, traversing rows took 42 milliseconds

Please help answer

### Additional

    def detection(self, frame=None, model_name_display=None):
        t1 = int(round(time.time() * 1000))
        img_height, img_width = frame.shape[:2]
        img = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        # Resize the image to match the input shape
        img = cv2.resize(img, (self.input_width, self.input_height))
        # Normalize the image data by dividing it by 255.0
        image_data = np.array(img) / 255.0
        # Transpose the image to have the channel dimension as the first dimension
        image_data = np.transpose(image_data, (2, 0, 1))  # Channel first
        # Expand the dimensions of the image data to match the expected input shape
        image_data = np.expand_dims(image_data, axis=0).astype(np.float32)
        # run
        t3 = int(round(time.time() * 1000))
        outputs = self.session.run(None, {self.model_inputs[0].name: image_data})
        t4 = int(round(time.time() * 1000))
        # Transpose and squeeze the output to match the expected shape
        outputs = np.transpose(np.squeeze(outputs[0]))
        # Get the number of rows in the outputs array
        rows = outputs.shape[0]
        # Lists to store the bounding boxes, scores, and class IDs of the detections
        # 用于存储检测的边界框、分数和类ID的列表
        boxes = []
        scores = []
        class_ids = []
        # Calculate the scaling factors for the bounding box coordinates
        # 计算边界框坐标的比例因子
        x_factor = img_width / self.input_width
        y_factor = img_height / self.input_height
        t7 = int(round(time.time() * 1000))
        # Iterate over each row in the outputs array
        # 在输出数组中的每一行上迭代
        print("rows=", rows)
        for i in range(rows):
            print("-----------------------------")
            # Extract the class scores from the current row
            # 从当前行中提取课堂分数
            t8 = int(round(time.time() * 1000))
            classes_scores = outputs[i][4:]
            t9 = int(round(time.time() * 1000))
            # Find the maximum score among the class scores
            # 找出班级分数中的最高分数
            max_score = np.amax(classes_scores)
            t10 = int(round(time.time() * 1000))
            print(i, t9 - t8, t10 - t9, max_score)
            # If the maximum score is above the confidence threshold
            # Minimum如果最大得分高于置信阈值
            if max_score >= self.confidence_thres:
                # Get the class ID with the highest score
                # 获取得分最高的班级ID
                class_id = np.argmax(classes_scores)
                t11 = int(round(time.time() * 1000))
                # Extract the bounding box coordinates from the current row
                # 从当前行提取边界框坐标
                x, y, w, h = outputs[i][0], outputs[i][1], outputs[i][2], outputs[i][3]
                t12 = int(round(time.time() * 1000))
                # Calculate the scaled coordinates of the bounding box
                # 计算边界框的缩放坐标
                left = int((x - w / 2) * x_factor)
                top = int((y - h / 2) * y_factor)
                width = int(w * x_factor)
                height = int(h * y_factor)
                t13 = int(round(time.time() * 1000))
                # Add the class ID, score, and box coordinates to the respective lists
                # 将类ID、分数和框坐标添加到各自的列表中
                class_ids.append(class_id)
                scores.append(max_score)
                boxes.append([left, top, width, height])
                t14 = int(round(time.time() * 1000))
                print(t11-t10, t12-t11, t13-t12, t14-t13)
                print("++++++++++++++++++++++++++++++++++++++")
        t5 = int(round(time.time() * 1000))
        # Apply non-maximum suppression to filter out overlapping bounding boxes
        # 应用非最大值抑制以过滤掉重叠的边界框
        indices = cv2.dnn.NMSBoxes(boxes, scores, self.confidence_thres, self.iou_thres)
        t6 = int(round(time.time() * 1000))
        # Iterate over the selected indices after non-maximum suppression
        # 在非最大抑制后在选定索引上迭代
        for i in indices:
            # Get the box, score, and class ID corresponding to the index
            # 获取与索引对应的框、分数和类ID
            box = boxes[i]
            score = scores[i]
            class_id = class_ids[i]

            # Draw the detection on the input image
            # 在输入图像上绘制检测
            # Extract the coordinates of the bounding box
            x1, y1, w, h = box
            # Retrieve the color for the class ID
            color = self.color_palette[class_id]
            # Draw the bounding box on the image
            cv2.rectangle(frame, (int(x1), int(y1)), (int(x1 + w), int(y1 + h)), color, 2)
            # Create the label text with class name and score
            # label = f'{self.classes[class_id]}: {score:.2f}'
            label = f'{score:.2f}'
            # Calculate the dimensions of the label text
            (label_width, label_height), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 1)

            # Calculate the position of the label text
            label_x = x1
            label_y = y1 - 10 if y1 - 10 > label_height else y1 + 10

            # Draw a filled rectangle as the background for the label text
            cv2.rectangle(frame, (label_x, label_y - label_height), (label_x + label_width, label_y + label_height),
                          color,
                          cv2.FILLED)

            # Draw the label text on the image
            cv2.putText(frame, label, (label_x, label_y), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1, cv2.LINE_AA)
        cv2.putText(frame, str(model_name_display) + "_count : " + str(len(boxes)), (30, 50), 0, 1, [0, 255, 255],
                    thickness=5,
                    lineType=cv2.LINE_AA)
        t2 = int(round(time.time() * 1000))
        print("1帧处理时间：", t2 - t1, " , runTime:", t4 - t3, ",t1-3:",
              t3 - t1, "t4-5", t5 - t4, "t5-6", t6 - t5, "t6-2", t2 - t6, "t4-7", t7 - t4, "t7-5", t6 - t7)
        return frame

18894 0 0 5.185604e-05
-----------------------------
18895 0 0 4.87566e-05
-----------------------------
18896 0 0 4.6610832e-05
-----------------------------
18897 0 0 5.018711e-05
-----------------------------
18898 0 0 5.4359436e-05
-----------------------------
18899 0 0 6.2704086e-05
1帧处理时间： 199  , runTime: 21 ,t1-3: 6 t4-5 172 t5-6 0 t6-2 0 t4-7 0 t7-5 172

**Comment by zhang7249** [comment]
Linux hange 5.15.0-75-generic #82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
model name	: 13th Gen Intel(R) Core(TM) i9-13900K
MemTotal:       131631256 kB
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:01:00.0  On |                  N/A |
| 30%   38C    P8              25W / 350W |   1599MiB / 24576MiB |      9%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

**Comment by glenn-jocher** [comment]
@zhang7249 based on the system information you provided, it seems that you are running YOLOv8 on a Linux machine with an Intel Core i9-13900K CPU and an NVIDIA GeForce RTX 3090 GPU.

The output from NVIDIA-SMI shows that your GPU is recognized and the driver version along with the CUDA version are compatible with YOLOv8. The GPU utilization is currently at 9% and the memory usage is 1599MiB out of a total of 24576MiB.

This information indicates that YOLOv8 is properly detecting and utilizing your GPU for inference.

If you have any specific issues or questions regarding the usage or performance of YOLOv8 on your system, please provide more details so that we can assist you further.

**Comment by zhang7249** [comment]
@glenn-jocher  Hello! Based on the information you provided, you have trained a batch of data using YOLOv8m, generated a pt model, and converted it into the ONNX format. You have run it on my example code examples/YOLOv8-ONNXRuntime/main.py. You have modified my main code to fit your own logic while retaining all the functionalities.

Since the processing time is a bit long, you have printed a lot of runtime output. From the output, you found that the actual detection only takes 14 milliseconds. However, in the result processing method, when you try to get the number of rows in the outputs array using rows = outputs.shape[0], you noticed that the value of rows is very large (18900), which causes the execution time of this loop to exceed 50 milliseconds. You have tried to optimize this loop using multithreading and managed to reduce the execution time to around 39 milliseconds.

You are requesting help to provide a solution because you need to process a real-time video stream from a drone. You acquire video frames through the RTMP protocol from a video server, process them (draw bounding boxes), and then push the processed frames back to the video server using ffmpeg + RTMP. Since the drone video is at 30fps, you need to keep the processing time for each frame within 30 milliseconds.

Thank you!

**Comment by zhang7249** [comment]
I have identified the time-consuming operation.

 # Find the maximum score among the class scores
 # max_score = np.amax(classes_scores)
 max_score = classes_scores[0]

**Comment by glenn-jocher** [comment]
@zhang7249 based on your description, I understand that you have identified a time-consuming operation in your code. Specifically, you found that the operation where you calculate the maximum score among the class scores is taking a significant amount of time.

To optimize this operation and reduce the execution time, you can replace the `np.amax` function with direct indexing to retrieve the maximum score. In your case, you mentioned that `max_score = classes_scores[0]` provides the desired maximum score.

By using direct indexing, you eliminate the overhead of the `np.amax` function, resulting in faster execution. This optimization should help you achieve your goal of processing each frame within 30 milliseconds for the real-time video stream from the drone.

If you have any further questions or require additional assistance, please let me know.
