### ISSUE TITLE
Continue supporting more rtdetr models of different scales

### ISSUE THREAD

**Issue by MINGtoMING** [ultralytics/ultralytics#3543]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

more rtdetr model  as follow: (https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/rtdetr)
![image](https://github.com/ultralytics/ultralytics/assets/95759947/5eb5d306-2a05-4ef4-8ff9-a424194536f6)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MINGtoMING hi there! Thank you for reaching out and for your interest in YOLOv8.

We greatly appreciate your suggestion to support more RT-DETR models of different scales. The Ultralytics team is always looking for ways to improve and expand the capabilities of our models.

While YOLOv8 currently supports multiple computer vision tasks such as detection, segmentation, classification, and pose/keypoint estimation, we understand the value of adding more RT-DETR models to the repertoire. 

Please know that your feature request has been noted and will be considered for future updates and releases. We encourage you to stay tuned to the repository for any news or updates regarding this.

If you would like to contribute by submitting a pull request, we would be thrilled to receive your assistance. Collaboration from the community is extremely valuable and helps us in enhancing the YOLOv8 project.

Once again, thank you for your suggestion and support. Please feel free to reach out if you have any further questions or ideas. We're here to help!

Best regards,
Glenn Jocher
