### ISSUE TITLE
YOLOv8 Deployment on Jetson Xavier NX with JetPack 4.5/4.6

### ISSUE THREAD

**Issue by Plumess** [ultralytics/ultralytics#3557]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Greetings,

I am currently attempting to deploy YOLOv8 for inference on a Jetson Xavier NX system with JetPack 4.5 or 4.6 installed. Upon reviewing the requirements, I noticed that YOLOv8 necessitates Python >= 3.8. However, JetPack 4.x comes with Python 3.6 as the base version, and the available PyTorch wheel files for Jetson are also compatible with Python 3.6.

Considering these constraints, could you please advise on how I might proceed with running YOLOv8 tasks or converting YOLOv8 models to tensorRT.engine within the JetPack 4.5 or 4.6 environments?

For additional context, I have a PyTorch model already trained and my goal is to export this as a .engine file for further use on Jetson Xavier NX.

Thank you in advance for your guidance.

**Comment by aurelm95** [comment]
If you want to deploy your model with deepstream you just need to export and dont care about the python version. On the other hand, if you want to use a pure python pipeline like ultralytics, I strongly suggest you to reflash your jetson with jetpack 5.0 and use the docker image provided by ultralytics.

**Comment by glenn-jocher** [comment]
@Plumess thank you for your suggestion! If you want to deploy your YOLOv8 model with deepstream, you can simply export it without worrying about the Python version. This allows you to use the model in deepstream without any compatibility issues.

If you prefer using a pure Python pipeline like Ultralytics, I recommend re-flashing your Jetson with JetPack 5.0. JetPack 5.0 includes Python 3.8 as the base version, which is compatible with YOLOv8's Python requirements. Additionally, you can use the Docker image provided by Ultralytics, which simplifies the setup process.

By following these steps, you should be able to seamlessly run YOLOv8 tasks in a Python environment on your Jetson Xavier NX system.

Let me know if you have any further questions or need assistance with anything else!

**Comment by Plumess** [comment]
I greatly appreciate your response. Due to practical constraints, I'm compelled to work within the JetPack 4.5/4.6 environment, and re-flashing my Jetson could adversely impact my other ongoing projects.

In your previous communication, you mentioned DeepStream. I'm curious, is it feasible for me to use a different device to export the TensorRT.engine using CLI, then deploy it on Jetson via DeepStream? From my research, it appears that the TensorRT's .engine is optimized specifically for the device it's used on. If that's the case, would it be necessary for me to first export to ONNX, and subsequently use TensorRT's tools on Jetson to convert this to .engine?

I look forward to your guidance and advice on this matter. Thank you for your time and expertise.

**Comment by Plumess** [comment]
I am writing to further clarify some procedural aspects. I successfully generated a .pt file on a x64 PC using the CLI method and my own dataset for training. I'm now at a stage where I'm trying to deploy the inference of the .engine file on my Jetson (JetPack 4.5/4.6), a process which may require me to organize the model's output using C++.

Could you kindly guide me on the appropriate steps or a recommended process that I can explore further on my own? This guidance would help me to identify and work out the finer details to progress with my implementation.

Thank you again for your assistance, I greatly appreciate your expertise on this matter.

**Comment by Plumess** [comment]
I sincerely appreciate your assistance. I used the export command on my PC to convert my PyTorch model to ONNX. Afterwards, I transferred it to Jetson and used the pre-installed TensorRT.trtexec tool available in JetPack for the direct conversion. This method conveniently bypassed the issues I was experiencing with PyTorch. 

Moving forward, I am now in a position to use DeepStream for inferring from the .engine file. Your valuable insights have greatly facilitated my progress, and I extend my thanks once more for your help.

**Comment by glenn-jocher** [comment]
@Plumess thank you for sharing your progress! It's great to hear that you were able to successfully convert your PyTorch model to ONNX using the export command on your PC and then use TensorRT.trtexec tool on Jetson for direct conversion. This approach bypasses any potential issues you encountered with PyTorch.

Now that you have the .engine file, you can use DeepStream for inference. DeepStream provides a convenient framework for deploying and running AI models on Jetson devices. You can utilize the deepstream-app sample application provided by NVIDIA to run the inference on your Jetson Xavier NX.

To use the .engine file with DeepStream, you will need to create a DeepStream pipeline configuration file. This file defines the input source, pre-processing steps, model settings, and output configuration. You will need to modify the pipeline configuration file to specify the location of your .engine file, configure the input and output settings according to your requirements, and provide any necessary post-processing logic.

Once you have the pipeline configuration file ready, you can launch the deepstream-app binary with the configuration file as a command-line argument. DeepStream will then start the inference process based on the specified configuration, using your YOLOv8 model implemented as a .engine file.

I hope this guidance helps you further with your implementation. If you have any more questions or need additional assistance, please feel free to ask. Best of luck with your project!

**Comment by Plumess** [comment]
Thank you immensely for your assistance. I've successfully completed the initial deployment and processing on Jetson, all thanks to your generous and valuable guidance. I greatly appreciate your help.

**Comment by glenn-jocher** [comment]
@Plumess thank you for reaching out and I'm thrilled to hear that you have successfully completed the initial deployment and processing of YOLOv8 on Jetson! Your hard work and persistence have paid off.

I'm here to provide guidance and support whenever you need it, so feel free to reach out if you have any further questions or need assistance with anything else related to YOLOv8. Your success is our priority, and we're here to help you achieve your goals.

Once again, congratulations on your progress and thank you for your kind words. It was a pleasure assisting you, and I wish you continued success with your project!

**Comment by anjaeju** [comment]
@Plumess @glenn-jocher  This issue is very helpful for me to do the similar project that is running yolov8 object detection model on NVIDIA Jetson Nano 4GB module. Thanks your efforts.

- Currently, Im getting a problem for deploying the .engine file on Jetson Nano with python (based on Pytorch) scripts.
When I run the scripts including the following code snippets, I get error [No module named 'tensorrt'].
```
model = YOLO('best.engine')
results = model.track(frame, persist=True, conf=0.25, iou=0.5, tracker='bytetrack.yaml')
```
I think it is impossible to run the .engine file with the scripts due to complex version errors. Is it  required to inference the model (.engine file) based on Deepstream?

**Comment by Plumess** [comment]
> During my experience, I have encountered issues where the engine cannot perform inference. I believe this may be due to a misalignment in the PyTorch version, causing some operators to not function optimally during model conversion. It's advisable to use the official recommended version for both reasoning and conversion processes. Alternatively, you may explore other third-party projects that have successfully implemented this, and consider using the version they have employed.

**Comment by glenn-jocher** [comment]
@Plumess i'm glad to hear you found our previous discussion helpful for your project!

The error you're encountering seems to suggest that the 'tensorrt' module is not installed in your Python environment. You might need to install it to resolve the error. However, as you are working with a Jetson device, it's important to note that NVIDIA provides versions of TensorRT already pre-installed with the JetPack SDK. 

But the problem seems to be originating from the incorrect version match or compatibility issue.
TensorRT and PyTorch versions should be in alignment for seamless inference from the .engine files by the TensorRT runtime. 

As for your query regarding Deepstream -- yes, you need to use Deepstream or another similar service to perform inference on the .engine file. This is because the .engine file is optimized for TensorRT, which is a part of the Deepstream SDK. This allows you to effectively deploy AI models on NVIDIA platforms.

I hope this helps! Let me know if you have any other questions.

**Comment by jasonlytehouse** [comment]
You can use this [repo](https://github.com/jayfalls/jetson_nano_ubuntu20_docker/tree/main) I created which provides a docker image with python3.11 to run any ultralytics yolo models on Jetson Nano with torch gpu or tensorrt

You can expect about 60-70ms average end-to-end with yolov8n and yolov10n on the Jetson with Python3.11

**Comment by glenn-jocher** [comment]
Hi @jasonlytehouse,

Thank you for sharing your Docker repo! It’s great to see community contributions that help others run YOLO models on Jetson Nano. 🚀

For those experiencing issues with TensorRT and Python scripts, using a Docker image with Python 3.11 and the appropriate dependencies can indeed streamline the setup process. Your repo could be a valuable resource for many.

For anyone encountering issues, please ensure you are using the latest versions of `torch` and `ultralytics`. If the problem persists, providing a minimum reproducible example will help us investigate further. You can find guidelines for this [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

If you have any more questions or need further assistance, feel free to ask!
