### ISSUE TITLE
AttributeError: 'RTDETR' object has no attribute 'names'. 

### ISSUE THREAD

**Issue by saurabheights** [ultralytics/ultralytics#3563]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Integrations, Other

### Bug

The model RTDETR does not have names attribute to map its prediction to class labels (readable names). 

### Environment

- Ultralytics 8.0.125
- Ubuntu 22.04
- Python - 3.10.11

### Minimal Reproducible Example

```
from ultralytics import YOLO, RTDETR
model = YOLO('yolov8n.pt')
print(model.names)
{0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted plant', 59: 'bed', 60: 'dining table', 61: 'toilet', 62: 'tv', 63: 'laptop', 64: 'mouse', 65: 'remote', 66: 'keyboard', 67: 'cell phone', 68: 'microwave', 69: 'oven', 70: 'toaster', 71: 'sink', 72: 'refrigerator', 73: 'book', 74: 'clock', 75: 'vase', 76: 'scissors', 77: 'teddy bear', 78: 'hair drier', 79: 'toothbrush'}

model = RTDETR("rtdetr-l.pt")
print(model.names)
Traceback (most recent call last):
  File "/home/sk/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/231.9161.41/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/sk/miniconda3/envs/test/lib/python3.10/site-packages/ultralytics/vit/rtdetr/model.py", line 173, in __getattr__
    raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
AttributeError: 'RTDETR' object has no attribute 'names'. See valid attributes below.
None
```

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@saurabheights yeah we didn't add that attr, we'll fix it, before that please use `model.model.names` for rtdetr model. :)
@glenn-jocher we can simply add this attr in RTDETR but I think we'll just need a `BaseModel` to add necessary attributes for all these models.

**Comment by glenn-jocher** [comment]
@Laughing-q the FastSAM PR used the YOLO model as a base which was really cool. I added the init code but the base-class usage was by the FastSAM author.

https://github.com/ultralytics/ultralytics/blob/b8cc404ebffa0b5604528c58729c597cd2b9c6e1/ultralytics/yolo/fastsam/model.py#L22-L30

**Comment by glenn-jocher** [comment]
@saurabheights great news 😃! Your original issue may now be resolved ✅ in PR #3934. This PR adds class numbers as default names if no names are provided, so now your code will work without error, and new names can be defined as `model.names = {...}`

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by saurabheights** [comment]
@glenn-jocher Thanks, I have verified the changes work.

**Comment by glenn-jocher** [comment]
You're welcome, @saurabheights! I'm glad to hear that the changes are working as expected. If you encounter any other issues or have further questions, don't hesitate to let us know. Happy coding with YOLOv8!
