### ISSUE TITLE
Add `run_name` for MLfLow

### ISSUE THREAD

**Issue by andrewerf** [ultralytics/ultralytics#3566]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Right now, `run_name` is not provided to `mlflow.start_run`. [It means](https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.start_run) that `a unique name will be generated for the run`. However, the ultralytics params [might contain](https://docs.ultralytics.com/modes/train/#arguments) the `name` option.

I propose using this `name` as a `run_name` for MLFlow.

### Use case

When using MLflow for logging and tracking.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by andrewerf** [comment]
Closing since the PR has been merged.

**Comment by glenn-jocher** [comment]
@andrewerf thank you for your contribution! We appreciate your effort in submitting a pull request to add the `run_name` functionality for MLflow integration. Your PR has been reviewed and merged into the main branch. With the addition of this feature, users can now provide a custom name for their MLflow runs when using YOLOv8.

Feel free to reach out if you have any further questions or if there's anything else we can assist you with. Thank you again for your contribution to the YOLOv8 project!
