### ISSUE TITLE
Issues working with Instance Segmentation

### ISSUE THREAD

**Issue by mahamatnoumai** [ultralytics/ultralytics#3568]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to train an instance segmentation with multi-classes, and hence, when I launched the training it showed only one type of classe. 

please refer to the screenshot below for your reference. 

![image](https://github.com/ultralytics/ultralytics/assets/17758399/2d581257-e37c-4512-9686-a4d5fa9599b1)

it also refereing to all the classes as one class which is 0, if you see in this picture below, it is clearly detecting both different class with same class id 

![image](https://github.com/ultralytics/ultralytics/assets/17758399/1796942c-2588-494f-8ac5-deb6dd126f75)

here is an example of the txt file converted in yolo format 

```
0 0.45859375 0.5 0.4578125 0.50125 0.45703125 0.50125 0.45625 0.5025 0.4578125 0.505 0.4578125 0.50625 0.45625 0.50875 0.45625 0.51 0.45625 0.50875 0.45703125 0.5075 0.4578125 0.50875 0.4578125 0.51125 0.45703125 0.5125 0.45625 0.5125 0.45703125 0.51375 0.45625 0.515 0.45703125 0.51375 0.4578125 0.51375 0.45859375 0.515 0.4578125 0.51625 0.45859375 0.515 0.459375 0.51625 0.459375 0.5175 0.45859375 0.51875 0.4578125 0.51875 0.45625 0.52125 0.4578125 0.51875 0.45859375 0.51875 0.459375 0.5175 0.46015625 0.51875 0.46015625 0.52 0.459375 0.52125 0.45859375 0.52125 0.45703125 0.52375 0.4578125 0.5225 0.45859375 0.52375 0.459375 0.52375 0.4609375 0.52625 0.46015625 0.5275 0.459375 0.5275 0.45859375 0.52625 0.4578125 0.52625 0.45703125 0.5275 0.45625 0.52625 0.45703125 0.5275 0.45625 0.52875 0.45703125 0.5275 0.4578125 0.52875 0.4578125 0.5275 0.45859375 0.52625 0.459375 0.5275 0.46015625 0.5275 0.4609375 0.52875 0.46171875 0.52875 0.4609375 0.52875 0.46015625 0.5275 0.4609375 0.52625 0.4609375 0.525 0.46171875 0.52375 0.4625 0.525 0.4625 0.52625 0.46328125 0.5275 0.46328125 0.52875 0.4640625 0.52875 0.46484375 0.5275 0.465625 0.52875 0.46484375 0.5275 0.46484375 0.52625 0.46484375 0.5275 0.4640625 0.52875 0.4625 0.52625 0.4625 0.525 0.46328125 0.52375 0.46640625 0.52375 0.4671875 0.5225 0.46796875 0.52375 0.47421875 0.52375 0.475 0.525 0.47421875 0.52625 0.46875 0.52625 0.47421875 0.52625 0.47578125 0.52875 0.4765625 0.52875 0.478125 0.52625 0.47890625 0.52625 0.4796875 0.5275 0.47890625 0.52875 0.4796875 0.5275 0.48046875 0.52875 0.48125 0.52875 0.48125 0.5275 0.48046875 0.52625 0.48125 0.525 0.48203125 0.525 0.4828125 0.52625 0.4828125 0.52875 0.4828125 0.5275 0.48359375 0.52625 0.4828125 0.52625 0.48203125 0.525 0.4828125 0.52375 0.4828125 0.5225 0.48203125 0.52125 0.4828125 0.52 0.48359375 0.52 0.484375 0.52125 0.484375 0.52375 0.4859375 0.52625 0.4859375 0.5275 0.48671875 0.52875 0.4859375 0.5275 0.4859375 0.525 0.48515625 0.525 0.484375 0.52375 0.484375 0.5225 0.48515625 0.52125 0.4859375 0.52125 0.48671875 0.5225 0.4859375 0.52125 0.4859375 0.51875 0.48671875 0.5175 0.4859375 0.5175 0.48359375 0.51375 0.4828125 0.51375 0.48203125 0.5125 0.4828125 0.51125 0.48359375 0.51125 0.4828125 0.51125 0.48203125 0.51 0.48125 0.51125 0.48046875 0.51 0.48046875 0.5075 0.4796875 0.50625 0.48046875 0.505 0.4796875 0.505 0.478125 0.5025 0.478125 0.50125 0.47734375 0.5 0.465625 0.5 0.465625 0.50125 0.46484375 0.5025 0.4640625 0.5025 0.4640625 0.505 0.46328125 0.50625 0.4625 0.505 0.46171875 0.50625 0.46015625 0.50625 0.4578125 0.5025 0.4578125 0.50125 0.45859375 0.5 0.4609375 0.50375 0.459375 0.50125 0.46015625 0.5 0.4609375 0.5 0.4625 0.5025 0.4609375 0.5 0.46015625 0.5 0.459375 0.50125
```

or in picture. 
![image](https://github.com/ultralytics/ultralytics/assets/17758399/fd477023-f79b-4b10-abea-020824801419)

I used the following scripts below to convert the masks image to polygon txt file yolo format 

```
import os
import cv2

input_dir = (labels')
output_dir = (output')

for j in os.listdir(input_dir):
    image_path = os.path.join(input_dir, j)
    # load the binary mask and get its contours
    mask = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    _, mask = cv2.threshold(mask, 1, 255, cv2.THRESH_BINARY)

    H, W = mask.shape
    contours, hierarchy = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    # convert the contours to polygons
    polygons = []
    for cnt in contours:
        if cv2.contourArea(cnt) > 200:
            polygon = []
            for point in cnt:
                x, y = point[0]
                polygon.append(x / W)
                polygon.append(y / H)
            polygons.append(polygon)

    # print the polygons
    with open('{}.txt'.format(os.path.join(output_dir, j)[:-4]), 'w') as f:
        for polygon in polygons:
            for p_, p in enumerate(polygon):
                if p_ == len(polygon) - 1:
                    f.write('{}\n'.format(p))
                elif p_ == 0:
                    f.write('0 {} '.format(p))
                else:
                    f.write('{} '.format(p))

        f.close()
````

training code 

![image](https://github.com/ultralytics/ultralytics/assets/17758399/c8d3020e-0f13-4fe9-afd3-c5dd8979756d)

yaml file here 

![image](https://github.com/ultralytics/ultralytics/assets/17758399/cebe0082-66b1-4767-9d2e-0363a581e0a5)

what am I doing wrong in my process of training instance segmentations?

In addition to that, how can I train semantic segmentation from masks labelled data in format of semantics segmentations images.

**Comment by Laughing-q** [comment]
@mahamatnoumai from your script, you just simply assigned your masks to category index 0, so I think that's why you got both `person` and `car` categories to index 0.
```python
                elif p_ == 0:
                    f.write('0 {} '.format(p))
```

**Comment by mahamatnoumai** [comment]
> 

@Laughing-q Thank you for reply, Yeah I think you are right, it is saving all category index to 0, that is why both are predicted to 0. Hence, what are the best tools/scripts to use to convert to yolo datasets format beside roboflow, i have my data, i could see the other classes. 

![image](https://github.com/ultralytics/ultralytics/assets/17758399/6e5ec323-2352-46c7-bf68-b484dded0370)

**Comment by Laughing-q** [comment]
@mahamatnoumai Based on your current script, with minimal modifications I think the simplest way is to assign the correct category then everything is ready to go, since your visualized masks look correct. Just create another variable(probably a list type) to keep category indices while converting rle to masks, then use this variable to save correct indices while converting yolo format from masks.

**Comment by mahamatnoumai** [comment]
> @mahamatnoumai Based on your current script, with minimal modifications I think the simplest way is to assign the correct category then everything is ready to go, since your visualized masks look correct. Just create another variable(probably a list type) to keep category indices while converting rle to masks, then use this variable to save correct indices while converting yolo format from masks.

Thanks @Laughing-q  for your answer, i will try to tweak my code to get the cat_id, and from there, i would be able to convert it successfully, Hence, how to get the class_id if you are converting directly from masks images like below

![image](https://github.com/ultralytics/ultralytics/assets/17758399/a4a66591-a6b0-4919-beed-1d12e6772506)


thank you
