### ISSUE TITLE
Inference get stuck in an infinite loop

### ISSUE THREAD

**Issue by mrmarten** [ultralytics/ultralytics#357]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I have noticed a problem that you can't just inference an image one single time.

`results = model.predict(source="screenshot.jpg", visualize=640, show=True)`

**I get the following output before i hard break the Python running environment:**
_
Ultralytics YOLOv8.0.5  Python-3.9.2 torch-1.11.0+cpu CPU
Fusing layers... 
Model summary: 168 layers, 11126745 parameters, 0 gradients, 28.4 GFLOPs
screen 0 (LTWH): 0,0,1920,1080: 384x640 196.0ms
screen 0 (LTWH): 0,0,1920,1080: 384x640 231.0ms
screen 0 (LTWH): 0,0,1920,1080: 384x640 231.8ms
screen 0 (LTWH): 0,0,1920,1080: 384x640 239.8ms
screen 0 (LTWH): 0,0,1920,1080: 384x640 216.0ms
screen 0 (LTWH): 0,0,1920,1080: 384x640 202.0ms
screen 0 (LTWH): 0,0,1920,1080: 384x640 267.0ms
screen 0 (LTWH): 0,0,1920,1080: 384x640 236.4ms_

I found no arguments for just make it run once?

### Environment

Ultralytics YOLOv8.0.5  Python-3.9.2 torch-1.11.0+cpu CPU
Windows 10 64-bit

### Minimal Reproducible Example

`from ultralytics import YOLO`
`results = model.predict(source="screenshot.jpg", visualize=640, show=True)`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Thanks for reporting we'll verify this and fix all inference related issues soon

**Comment by Laughing-q** [comment]
@mrmarten hi actually I can't reproduce your issue with the same code:
```python
from ultralytics import YOLO
model = YOLO("weights/yolov8n.pt")
results = model.predict(source="./ultralytics/assets/bus.jpg", visualize=640, show=True)
```
it just showed once and progress finished.

**Comment by mrmarten** [comment]
> ```python
> from ultralytics import YOLO
> model = YOLO("weights/yolov8n.pt")
> results = model.predict(source="./ultralytics/assets/bus.jpg", visualize=640, show=True)
> ```

Very weird,I tried copy your code, this time i used Python 3.8 and installed with pip ultralytics again and i get the exact same issue once again.

**Comment by kyoko9000** [comment]
can u try to use pip install --upgrade ultralytics to make the last version of all. or you can go to your lib and delete 2 folder name ultralytics in that lib and try pip install --upgrade ultralytics again

**Comment by mrmarten** [comment]
> can u try to use pip install --upgrade ultralytics to make the last version of all. or you can go to your lib and delete 2 folder name ultralytics in that lib and try pip install --upgrade ultralytics again

Did an: "C:/Program Files/Python38/python.exe" -m pip install --upgrade ultralytics 
Requirement already satisfied: ultralytics in c:\program files\python38\lib\site-packages (8.0.6)
Requirement already satisfied: PyYAML>=5.3.1 in c:\program files\python38\lib\site-packages (from ultralytics) (6.0)
Requirement already satisfied: torchvision>=0.8.1 in c:\program files\python38\lib\site-packages (from ultralytics) (0.13.0+cu116)

I got the same trouble with the infinite loop.
Can it be worth trying Python 3.7 ?

**Comment by pderrenger** [comment]
@mrmarten python 3.7 should work just fine. Feel free to give it a try and let us know if you encounter any further issues.
