### ISSUE TITLE
Only replace first occurence of 'images' in img2label_paths function

### ISSUE THREAD

**Issue by tlpss** [ultralytics/ultralytics#3581]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

The current `img2label_paths` function replaces all occurences of 'images' with 'labels'. I would prefer to only replace the first occurance, as I have a nested structure of my images folder that contains subfolders that are also named 'images', which results in weird errors. This nested strcuture does not seem to contradict the Ultralytics yolo format afaik? So it would be a useful feature imo? If not, a simple check for multiple occurences could be added with a helpful error message.

https://github.com/ultralytics/ultralytics/blob/a254087fcd180223a918aa85ae8f553657b029d1/ultralytics/yolo/data/utils.py#L39

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@tlpss this is not true. The function only replaces the last instances of 'images' with 'labels':

```
img2label_paths(['abc/images/def/images/ghi/images/'])
Out[7]: ['abc/images/def/images/ghi/labels/.txt']
```

This is as intended and correct, and also as described in our dataset docs at https://docs.ultralytics.com/datasets/detect

**Comment by glenn-jocher** [comment]
@tlpss this is not True. The function correctly replaces the last instance of a directory names 'images' with 'labels', and updates the file suffix from any valid image suffix to *.txt:

```python
img2label_paths(['abc/images/def/images/ghi/images/jkl/im.jpg'])
Out[9]: ['abc/images/def/images/ghi/labels/jkl/im.txt']
```

This is explained in our docs at https://docs.ultralytics.com/datasets/detect

**Comment by tlpss** [comment]
@glenn-jocher
> The function correctly replaces only the last instance of a directory names 'images' with 'labels'

sorry, my bad. Thanks for clarifying.

So it only replaces the last occurence. This implies then that the `images/` dir and hence the `labels/` dir cannot contain any subdir named `images`? If so, I had not found this in the format docs (that you also referred to). 

Unless I have overlooked this, I believe it would be useful to add this to the docs or to provide a warning in the code?

**Comment by glenn-jocher** [comment]
@tlpss thank you for bringing this to my attention. I apologize for any confusion caused.

Yes, you are correct. The `img2label_paths` function in YOLOv8 replaces only the last occurrence of the directory named 'images' with 'labels'. This means that if the `images/` directory or the corresponding `labels/` directory contains a subdirectory named 'images', it may lead to unexpected behavior.

I appreciate your suggestion to add this information to the documentation or provide a warning in the code. I will discuss this with the Ultralytics team and we will consider updating the documentation to provide clarity on this limitation and potential workarounds.

Thank you again for bringing this to our attention and helping us improve the YOLOv8 experience. Let me know if you have any further questions or suggestions.
