### ISSUE TITLE
Kaggle using deprecated Python 3.7

### ISSUE THREAD

**Issue by tttdevelop** [ultralytics/ultralytics#3583]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

Error exporting =.

raceback (most recent call last):
  File "/opt/conda/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/conda/lib/python3.7/site-packages/ultralytics/yolo/cfg/__init__.py", line 411, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/opt/conda/lib/python3.7/site-packages/ultralytics/yolo/engine/model.py", line 342, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ultralytics/yolo/engine/exporter.py", line 252, in __call__
    f[8], _ = self.export_edgetpu(tflite_model=Path(f[5]) / f'{self.file.stem}_full_integer_quant.tflite')
  File "/opt/conda/lib/python3.7/pathlib.py", line 1027, in __new__
    self = cls._from_parts(args, init=False)
  File "/opt/conda/lib/python3.7/pathlib.py", line 674, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/opt/conda/lib/python3.7/pathlib.py", line 658, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

### Environment

In Kaggle and locally it is the same error.

Kaggle - just copy and edit. Tested other feature ok. Only this.

Locally on Ubuntu with Python 3.8.10, latest ultralytics install from pip.

### Minimal Reproducible Example

Run in Kaggle yolov8 example 

cell 1 to install and 

Export cell
!yolo export model=yolov8n.pt format=edgetpu

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@tttdevelop this is a Kaggle issue, as they are using Python 3.7 which is now deprecated. See https://endoflife.date/python. The `onnx2tf` package requires Python>=3.8.0, which is a reasonable minimum today. I would raise an issue directly with Kaggle regarding this, and optionally with the onnx2tf author to see if support for Python 3.7 is possible.

<img width="1175" alt="Screenshot 2023-07-07 at 15 58 24" src="https://github.com/ultralytics/ultralytics/assets/26833433/6dbf5c5d-8862-43df-b9b7-6a9716522e80">


Note that EdgeTPU export works correctly in Colab, GitHub CI actions, and every other environment that is Python 3.8.0:

<img width="1018" alt="Screenshot 2023-07-07 at 15 45 33" src="https://github.com/ultralytics/ultralytics/assets/26833433/b3986f76-b459-4da5-9b73-80acad90ab51">

**Comment by tttdevelop** [comment]
Thank you for the update. For others that may read this ...

I did try with 3.8.10 on my own machine and it had the same error. I also tried with running on a docker container with the latest ultralytics/ultralytics:latest with the same error coming up.

Can it be related to tesnorflow_cpu ? I am not using any GPU's for trying to convert this.

I'll close this as I found another thread which also has the same type of problem and it is clearly stated that export is still under development. So I close this and lets see how it goes. https://github.com/ultralytics/ultralytics/issues/1185#issuecomment-1612259990.

**Comment by glenn-jocher** [comment]
@tttdevelop thank you for your update.

I understand that you have tried running YOLOv8 with Python 3.8.10 on your own machine and encountered the same error. Additionally, you also tried running it in a Docker container with the latest `ultralytics/ultralytics:latest` image and faced the same issue.

The error you are experiencing may not be related to using TensorFlow CPU, as YOLOv8 should be able to run without a GPU. However, it is worth noting that the export functionality is still under development, as mentioned in the thread you found (https://github.com/ultralytics/ultralytics/issues/1185#issuecomment-1612259990).

Given the current state of the export feature in YOLOv8, it may not be fully functional yet. I recommend closing this issue for now and keeping an eye on future updates to see if the export functionality improves.

Please let us know if you have any further questions or concerns.
