### ISSUE TITLE
--classes flag in YOLOv8

### ISSUE THREAD

**Issue by lonnylundsten** [ultralytics/ultralytics#359]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In yolov5 I could use the classes flag (i.e., '--classes 5') to constrain the inference so that only selected classes would be detected. How can I similarly accomplish this with YOLOv8? I would like to see examples for both the CLI and python options.

**Comment by Laughing-q** [comment]
@AyushExel I think we haven't added this arg right?

**Comment by AyushExel** [comment]
No we don't have this arg currently

**Comment by Laughing-q** [comment]
@lonnylundsten hi the `classes` has been implemented which you can use it by:
```bash
yolo segment predict model=yolov8n-seg.pt classes=0,1
```
closing the issue, feel free to reopen it if you have related issues! :)
