### ISSUE TITLE
Can you trace the location of an object to count it correctly without being counted multiple times?

### ISSUE THREAD

**Issue by rick13xe** [ultralytics/ultralytics#3590]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I wanted to ask if it is possible that with my Yolov8 model (on fish) I could correctly count the fish and locate their coordinates in the video to know if they go from certain areas to others for example if they go from the center of the screen to right side or the left side.
I have used this code (saves the frames where a fish appears and adds the total fish instances) and I have tried to use others with xyxy, pandas and other things but it has not worked for me, if you can give me some advice I would appreciate it.

import cv2
import os
from ultralytics import YOLO

model = YOLO("C:/Users/Ricardo/runs/detect/fish 40 epoch/weights/best.pt")
video_path = r"C:\Users\Ricardo\Desktop\Colmillejas.mp4"
output_directory = r"C:\Users\Ricardo\Desktop\pez"

cap = cv2.VideoCapture(video_path)
cv2.namedWindow("YOLOv8 Inference", cv2.WINDOW_NORMAL)

count_Fish = 0
frame_count = 0

while cap.isOpened():
    success, frame = cap.read()
    if success:
        frame_count += 1
        if frame is None or frame.shape[0] <= 0 or frame.shape[1] <= 0:
            print("Fotograma inválido:", frame)
            continue
        results = model(frame)
        fish_detected = False
        for result in results:
            annotated_frame = result.keypoints
            count_Fish += len(result.boxes)
            if len(result.boxes) > 0:
                fish_detected = True
                if annotated_frame is not None and annotated_frame.shape[0] > 0 and annotated_frame.shape[1] > 0:
                    cv2.imshow("YOLOv8 Inference", annotated_frame)
        if fish_detected:
            output_path = os.path.join(output_directory, f"frame_{frame_count}.jpg")
            cv2.imwrite(output_path, frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break

print("Número total de instancias de Fish detectadas:", count_Fish)

cap.release()
cv2.destroyAllWindows()
-------------------------

**Comment by glenn-jocher** [comment]
@rick13xe see Track model docs. You want to use Track mode, not Predict mode. https://docs.ultralytics.com/modes/track/

**Comment by rick13xe** [comment]
@glenn-jocher Thank you !!

**Comment by glenn-jocher** [comment]
@rick13xe you're welcome! If you have any further questions or need assistance, feel free to ask. We're here to help!
