### ISSUE TITLE
Unable to train on MPS when training with CLI

### ISSUE THREAD

**Issue by wafiq1211** [ultralytics/ultralytics#3591]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Running on M2 Max 64 GB, I'm trying to train a custom object detection model using Apple's MPS backend but I can't seem to get it working, however it works when training on CPU instead. 

Below are the output of the last 5 lines from the CLI:

    Image sizes 640 train, 640 val
    Using 8 dataloader workers
    Logging results to runs/detect/train4
    Starting training for 50 epochs...

    Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      0%|          | 0/144 [00:00<?, ?it/s]zsh: bus error  yolo task=detect mode=train epochs=50 data=data_custom.yaml model=yolov8m.pt 

### Environment

- YOLO: Ultralytics YOLOv8.0.128 🚀 Python-3.11.4 torch-2.1.0.dev20230705 MPS
- OS: 14.0 Beta 3
- Python: 3.11.4

### Minimal Reproducible Example

    yolo task=detect mode=train model=yolov8s.pt data=PATH-TO/data.yaml epochs=100 imgsz=640 device=mps

### Additional

Model prediction and evaluation works fine when using MPS.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by wafiq1211** [comment]
Never mind, it's working properly now after reinstalling using the nightly version:
`pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu`

**Comment by glenn-jocher** [comment]
Hi @wafiq1211, glad to hear that the issue is resolved after reinstalling using the nightly version of PyTorch. Sometimes, updating to the latest version of PyTorch can solve compatibility issues and ensure smooth functioning.

If you encounter any further issues or have any other questions related to YOLOv8, feel free to ask. We're here to help!
