### ISSUE TITLE
Help Wanted 🙏 NCNN inference in AutoBackend class

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/ultralytics#3599]
@yrik @nihui once place I need some help is in getting NCNN models to run inference correctly. Most of the Ultralytics export formats can be used directly with the package just like a PyTorch model, i.e. you can export to ONNX, OpenVINO, CoreML, etc and then use that exported model to predict or val:

```python
from ultralytics import YOLO

# Load a PyTorch model
model = YOLO('yolov8n.pt')

# Export to ONNX
model.export(format='onnx')

# Load the exported ONNX model
model_onnx = YOLO('yolov8n.onnx')

# Run inference on a source with PyTorch and ONNX models
source = 'https://ultralytics.com/images/bus.jpg'
results = model.predict(source)
results_onnx = model_onnx.predit(source)  # equal to 'results' to numerical precision
```

We use this capability to validate all export formats to make sure they don't lose any accuracy. You can see this in my CI here:
https://github.com/ultralytics/ultralytics/actions/runs/5491624795/jobs/10008335998
<img width="671" alt="Screenshot 2023-07-08 at 18 02 17" src="https://github.com/ultralytics/ultralytics/assets/26833433/489c6334-5af0-4b9c-b1f0-560871f7a511">

I need help constructing this for NCNN please. The relevant code for loading an NCNN model and running inference with it would be here in the AutoBackend class. I put a placeholder for NCNN:

https://github.com/ultralytics/ultralytics/blob/d9db6cd42d8935e51d8f69639024c2b86c53d1a8/ultralytics/nn/autobackend.py#L41-L458

_Originally posted by @glenn-jocher in https://github.com/ultralytics/ultralytics/issues/3529#issuecomment-1627389151_

**Comment by triple-Mu** [comment]
Hi here: https://github.com/ultralytics/ultralytics/pull/3617

**Comment by glenn-jocher** [comment]
@triple-Mu thank you for bringing this up! We appreciate your interest in using NCNN for YOLOv8 inference.

In order to support NCNN models in the AutoBackend class, you would need to add the necessary code in the `autobackend.py` file. Specifically, you would need to implement the loading of the NCNN model and the corresponding inference logic.

To load an NCNN model, you would typically use the NCNN library or its Python wrapper to load the model file and create an NCNN network object. Once you have the network object, you can pass the input data through the network and obtain the output predictions.

You would then need to integrate this logic into the existing `AutoBackend` class to ensure compatibility with the other supported backends.

Please note that we rely on the YOLO community and the Ultralytics team for contributions and developments in the YOLOv8 repo. If you are comfortable with NCNN implementation, you can fork the repo, make the necessary changes to support NCNN, and submit a pull request for review.

We encourage collaboration and appreciate any contributions to the YOLOv8 repository. Should you have any further questions or need any assistance during the process, please let us know. We are here to help!

**Comment by glenn-jocher** [comment]
@triple-Mu do you know why I get these debug files produced during ncnn export? Is there a way to prevent them being created?

```python
yolo export format=ncnn
```

<img width="288" alt="Screenshot 2023-07-11 at 19 50 21" src="https://github.com/ultralytics/ultralytics/assets/26833433/daf65d8d-7add-48da-8668-ef92e1ef6977">
