### ISSUE TITLE
The pretrained model's mAP is lower avarage 0.4% than your github show

### ISSUE THREAD

**Issue by hjg12345** [ultralytics/ultralytics#3608]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I use pretrainede model yolov8n.pt,yolov8s.pt,yolov8m.pt,and execute "yolo detect val data=coco.yaml model=yolov8s.pt"  and so on, get result as below,separately is yolov8n.pt,yolov8s.pt,yolov8m.pt validation result on cocoval2017,they are lower 0.4% than your github shows!
![yolov8n pt验证结果](https://github.com/ultralytics/ultralytics/assets/127812522/c1bfa198-4df9-492c-8111-d9272f8e77a8)
![yolov8s pt验证集结果](https://github.com/ultralytics/ultralytics/assets/127812522/c0bdcaf2-162b-4fef-afb6-df9da0123a0e)
![yolov8m pt验证集结果](https://github.com/ultralytics/ultralytics/assets/127812522/c3e643c1-688d-45cd-8e8a-7ae0a1111942)
![image](https://github.com/ultralytics/ultralytics/assets/127812522/e6e3fe2a-2ee4-473c-b092-e84692bb3a1d)

Why are they different? I didn't change any hypeparameter after cloning! How can I get the map as yours?

**Comment by glenn-jocher** [comment]
@hjg12345 README values are obtained from `pycocotools` to produce the most official metrics. 

<img width="1265" alt="Screenshot 2023-07-09 at 15 00 45" src="https://github.com/ultralytics/ultralytics/assets/26833433/2fee8d9a-4fb8-4601-b013-06c091b091e4">

pycocotools will attempt to run automatically if `data=coco.yaml`

**Comment by hjg12345** [comment]
Sorry, I didn't understand your meaning! I prepare the coco datasets as the first figure shows, and pretrained model is get the link and download, then put it in weights directory. I have "pycocotool==2.0.6", and I don't know how use pycocotool to get the offical result. I follow the way "yolo val detect data=ultralytics/datasets/coco.yaml model=weights/yolov8s.pt", but get 0.4% lower mAP50-95 result.
![image](https://github.com/ultralytics/ultralytics/assets/127812522/d904ff2a-2f9c-40dd-a7bf-d148fc72de9f)

**Comment by hjg12345** [comment]
You say pycocotools will attempt to run automatically if data=coco.yaml, but mine pycocotools didn't be used. Is there something wrong with my setting? when I execute "yolo val detect data=coco.yaml device=0", it will download coco2017labels-segments.zip and use its val.txt. Does the val.txt is not the same with "http://images.cocodataset.org/zips/val2017.zip"?

**Comment by glenn-jocher** [comment]
@hjg12345 something seems to be going wrong with your ultralytics package then. It may be out of date or modified. The following works correctly for me, showing 44.9 mAP for YOLOv8s with pycocotools:

<img width="603" alt="Screenshot 2023-07-09 at 16 52 03" src="https://github.com/ultralytics/ultralytics/assets/26833433/8eee5f1f-fe61-4ebb-8f71-e09e5479636d">

**Comment by hjg12345** [comment]
My ultralytics package is 8.0.124. Is it the latest version? And if I don't use ultralytics package, which directory's code is the execution about pycocotools?

**Comment by glenn-jocher** [comment]
@hjg12345 hi there,

Let me address your questions regarding YOLOv8 and the usage of pycocotools:

1. To obtain the official result when training from scratch, it is recommended to follow the guidelines provided in the documentation for YOLOv8. Ensure that you are using the correct configuration file (e.g., `yolov8s.yaml`) and that you have not made any modifications to the default hyperparameters. It is also essential to use the official COCO dataset and annotations for training and evaluation.

2. The usage of pycocotools can vary depending on the specific command or configuration being used. In some cases, pycocotools may be automatically employed when running certain commands, such as validation (`yolo val detect`). However, there may be instances where pycocotools is not utilized, leading to differences in the results. It is crucial to double-check the command and configuration settings to ensure that pycocotools is being properly utilized.

3. The comparison between the validation result and the pycocotools result is not straightforward. The validation result represents the performance of the model on the validation set based on the chosen evaluation metrics. On the other hand, the pycocotools result is typically obtained using the official COCO evaluation metrics. These metrics evaluate the model's performance across a range of IOU thresholds (mAP50-95), providing a more comprehensive assessment. While there may be variations between the two results, the pycocotools result is generally considered the more accurate representation of the model's performance.

I hope this clarifies your questions. Please let me know if you need any further assistance!

**Comment by hjg12345** [comment]
OK, thanks for your excellent work and reply. I will check the factors and try more times.

**Comment by hjg12345** [comment]
Yes，thanks at first.  Then I absolutely have a question now. It is whether you save some prediction result into coco2017 datasets' label to form the coco2017labels-segments.zip! I want to know whether your coco labels is the same with the coco offical labels. And hope you teach me some save-hybrid experience, I try the --save-hybrid, it makes an image which has 40 targets according to its label become  an image which has 279 targets label. I think it can be resolved by setting conf, but I don't konw how much I shoud set conf as.

**Comment by glenn-jocher** [comment]
@hjg12345 hi there,

Thank you for your question! The `coco2017labels-segments.zip` file provided in this repository is not a modified version of the official COCO dataset labels. It is a separate file that contains additional information about the segmentation of objects in the images.

As for the `--save-hybrid` option, it is used to save both bounding box and segmentation information in the label file. This can result in an increase in the number of targets in the label file compared to the original number of objects in the image.

To address your concern about the number of targets in the label file after using `--save-hybrid`, you can adjust the confidence threshold (`conf`) to control the number of detections saved. By setting a higher value for `conf`, you can filter out detections with lower confidence scores and reduce the number of targets in the label file. However, the specific value to use would depend on your specific dataset and the desired trade-off between sensitivity and specificity.

I hope this clarifies your questions. Please let me know if you need any further assistance!

**Comment by hjg12345** [comment]
Thank you! I want to change your network so I don't want to use your YOLO package. I focus on the detect task, in the val.py there is code below. I execute by "python val.py" it would appear some problems, like "AttributeError: 'dict' object has no attribute 'project'" in code " project = self.args.project or Path(SETTINGS['runs_dir']) / self.args.task". Because I uninstall ultralytics package and want to run by python code without this package!
![image](https://github.com/ultralytics/ultralytics/assets/127812522/b4664246-b70c-48a6-afb1-91a36dfa4a10)
After checking the code, I found the args in "validator = DetectionValidator(args=args)" is a dict, which is "model address and data yaml file address", it isn't a dict containing key "project" like default.yaml, it just has two key "model:model yaml file address; data: data yaml file address". So I want to know how to change code to make args become a dict which has all keys such as below.
![image](https://github.com/ultralytics/ultralytics/assets/127812522/ffe46788-eb00-4134-9ced-7f4abaeaa812)

**Comment by glenn-jocher** [comment]
@hjg12345 hello,

Thank you for reaching out! If you want to run the code without the Ultralytics package and encounter an "AttributeError: 'dict' object has no attribute 'project'" error, it seems that the code expects an `args` object with the `project` key, which is not present in your current `args` dictionary.

To resolve this issue, you can modify the code in `val.py` to add the missing `project` key in the `args` dictionary. You can set it to the desired value, such as `Path(SETTINGS['runs_dir']) / args['task']`.

By adding the `project` key to your `args` dictionary with the appropriate value before initializing the `DetectionValidator`, the error should be resolved.

I hope this helps! If you have any further questions, feel free to ask.
