### ISSUE TITLE
"Fraction" Hyperparameter

### ISSUE THREAD

**Issue by TalhaSarwar113** [ultralytics/ultralytics#3609]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi!
Can any one help me in understanding "fraction" hyperparameter in train settings of default.yaml configuration file of YOLOv8. Does setting this to For example 0.8 mean that training dataloader will pick 80% same data each time or will choose 80% data randomly for each epoch.

**Comment by glenn-jocher** [comment]
@TalhaSarwar113 fraction will pick the first x fraction of the trainset, so i.e. fraction=0.80 will pick the first 80 images in a 100 image trainset. There is no randomness.

**Comment by gWOLF3** [comment]
@TalhaSarwar113 fraction will pick the first x fraction of the trainset, so i.e. fraction=0.80 will pick the first 80 images in a 100 image trainset. There is no randomness.

wait... what.... this is insane
