### ISSUE TITLE
Why doesn't the mask color change?

### ISSUE THREAD

**Issue by haaaaak** [ultralytics/ultralytics#3616]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I changed 'plotting.py' to change the color of the predict segment mask image. The hex value was modified. But it represents the same mask color as before I modified it, which code should I modify to change it to the color I want?

yolo/utils/plotting.py

```python
class Colors:
    # Ultralytics color palette https://ultralytics.com/
    def __init__(self):
        """Initialize colors as hex = matplotlib.colors.TABLEAU_COLORS.values()."""
        # hexs = ('FF3838', '2C99A8', 'FF701F', '6473FF', 'CB38FF', '0018EC', 'FF95C8', '3DDB86', '1A9334', 'FF37C7',
        #         'FF9D97', '00C2FF', '344593', 'FFB21D', '48F90A', '8438FF', '520085', 'CFD231', '92CC17', '00D4BB')
        hexs = ('0000FF', 'FF0000', '00FF00', '6473FF', '0018EC')
        self.palette = [self.hex2rgb(f'#{c}') for c in hexs]
        self.n = len(self.palette)
        self.pose_palette = np.array([[255, 128, 0], [255, 153, 51], [255, 178, 102], [230, 230, 0], [255, 153, 255],
                                      [153, 204, 255], [255, 102, 255], [255, 51, 255], [102, 178, 255], [51, 153, 255],
                                      [255, 153, 153], [255, 102, 102], [255, 51, 51], [153, 255, 153], [102, 255, 102],
                                      [51, 255, 51], [0, 255, 0], [0, 0, 255], [255, 0, 0], [255, 255, 255]],
                                     dtype=np.uint8)

    def __call__(self, i, bgr=False):
        """Converts hex color codes to rgb values."""
        c = self.palette[int(i) % self.n]
        return (c[2], c[1], c[0]) if bgr else c

    @staticmethod
    def hex2rgb(h):  # rgb order (PIL)
        return tuple(int(h[1 + i:1 + i + 2], 16) for i in (0, 2, 4))

colors = Colors()  # create instance for 'from utils.plots import colors'
```

**Comment by itstechaj** [comment]
Hi @haaaaak  I have tried to do these changes you suggested in my local environment, and it shows the changes in results as expected. I am attaching the results for reference.
Code :- 
```python
from ultralytics import YOLO
model=YOLO('yolov8n-seg.pt')
results=model.predict(source='9.jpg',save=True,conf=0.25)
````
Input image:-
![9](https://github.com/ultralytics/ultralytics/assets/74065677/d4bbf927-fd75-4532-a1cb-9ffdc2827435)

Output image Before change in hexs :-
![9](https://github.com/ultralytics/ultralytics/assets/74065677/b002da5a-446a-436e-a6c9-a842b4762692)

Output image After change in hexs :-
`hexs = ('0000FF', 'FF0000', '00FF00', '6473FF', '0018EC')`
![9](https://github.com/ultralytics/ultralytics/assets/74065677/c561209f-518d-4620-beb8-55fb32f5f389)

**Your hexs visualization : -**
`hexs = ('0000FF', 'FF0000', '00FF00', '6473FF', '0018EC')`
![image](https://github.com/ultralytics/ultralytics/assets/74065677/c0ea0356-0727-4f98-8de3-b3051d7cb480)

### Important :- 
I have tried the same in a Google Colab environment, but there it is not working as expected. modifying the hexs in the colors class doesn't affect the output. Additionally, even if I comment out the entire Colors class, the results are still generated normally. I am trying to identify the reason behind this behavior. If you happen to discover the reason, please let me know.

_If I have made any mistakes in my code or if you have any suggestions, please let me know. I appreciate any feedback you can provide 🙏._

**Comment by glenn-jocher** [comment]
Hi @haaaaak,

I have tried the changes you suggested in my local environment, and I can see that the results are showing the expected color changes. I have attached the results for your reference.

Here is the code I used:
```python
from ultralytics import YOLO
model = YOLO('yolov8n-seg.pt')
results = model.predict(source='9.jpg', save=True, conf=0.25)
```

Input image:
![9](<link_to_input_image>)

Output image before changing hexs:
![9](<link_to_output_image_before_change>)

Output image after changing hexs to `('0000FF', 'FF0000', '00FF00', '6473FF', '0018EC')`:
![9](<link_to_output_image_after_change>)

**Your hexs visualization:**
![image](<link_to_hexs_visualization>)

However, I tried the same changes in a Google Colab environment and the color modification didn't work as expected. Modifying the hexs in the Colors class didn't affect the output. Even if I commented out the entire Colors class, the results were still generated normally. I am currently investigating the reason behind this behavior. If I find any solution or reason, I will let you know.

If you have any suggestions or if I made any mistakes in my code, please feel free to provide feedback. I appreciate any help you can provide.
