### ISSUE TITLE
No display FLOPs when runing RT-DETR

### ISSUE THREAD

**Issue by kuguahentian** [ultralytics/ultralytics#3618]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Export

### Bug

![image](https://github.com/ultralytics/ultralytics/assets/139029132/f1ff63c4-91e7-410c-a4a5-12b34e59ffc9)

only summary the layers, parameters, gradients
but didn't display  FLOPs

I have been installed thop package
![image](https://github.com/ultralytics/ultralytics/assets/139029132/ed8a6deb-f069-4800-91bd-c22e7daada5e)

### Environment

Ultralytics YOLOv8.0.131  Python-3.7.10 torch-1.8.0 CUDA:0 (NVIDIA GeForce RTX 4080, 16376MiB)
windows

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kuguahentian hi! Thank you for bringing this issue to our attention.

In YOLOv8, the display of FLOPs (floating-point operations) is not currently supported for the RT-DETR mode. However, the layers, parameters, and gradients are still summarized for you.

To calculate FLOPs in YOLOv8, we recommend using the `thop` package, which you mentioned you have installed. This package can provide you with the FLOPs calculation for the YOLOv8 model.

We appreciate your interest in contributing by submitting a PR. However, at this time, we don't have plans to add FLOPs display specifically for the RT-DETR mode in YOLOv8.

If you have any further questions or need assistance with anything else, please don't hesitate to ask. We're here to help!

**Comment by kuguahentian** [comment]
> 在 YOLOv8 中添加专门针对 RT-DETR 模式的 FLOPs 显示



> @kuguahentian你好！感谢您让我们注意这个问题。
> 
> 在YOLOv8中，RT-DETR模式当前不支持FLOP（浮点运算）的显示。但是，仍然为您总结了图层、参数和渐变。
> 
> 要计算 YOLOv8 中的 FLOP，我们建议使用`thop`您提到的已安装的软件包。该包可以为您提供YOLOv8模型的FLOPs计算。
> 
> 我们感谢您有兴趣通过提交 PR 做出贡献。不过，目前我们还没有计划在 YOLOv8 中添加专门针对 RT-DETR 模式的 FLOPs 显示。
> 
> 如果您还有任何其他问题或需要其他帮助，请随时询问。我们随时为您提供帮助！



> @kuguahentian hi! Thank you for bringing this issue to our attention.
> 
> In YOLOv8, the display of FLOPs (floating-point operations) is not currently supported for the RT-DETR mode. However, the layers, parameters, and gradients are still summarized for you.
> 
> To calculate FLOPs in YOLOv8, we recommend using the `thop` package, which you mentioned you have installed. This package can provide you with the FLOPs calculation for the YOLOv8 model.
> 
> We appreciate your interest in contributing by submitting a PR. However, at this time, we don't have plans to add FLOPs display specifically for the RT-DETR mode in YOLOv8.
> 
> If you have any further questions or need assistance with anything else, please don't hesitate to ask. We're here to help!

Thank you for your reply.

I was upset to hear that your team has no plans to add FLOPs display specifically for RT-DETR mode in YOLOv8.

I intend to improve and apply RT-DETR in the YOLOv8 project, because the yolov8 project is a very structured project that I love and am familiar with.

I sincerely hope that your team can update some yaml files about RT-DETR and solve the display issue of FLOPs of RT-DETR.

thank you very much.

**Comment by glenn-jocher** [comment]
@kuguahentian Thank you for your feedback and your interest in improving and applying RT-DETR in the YOLOv8 project. We appreciate your enthusiasm for the project and your suggestion to update the YAML files related to RT-DETR.

While we don't have immediate plans to add FLOPs display specifically for RT-DETR mode in YOLOv8, we understand that this feature would be valuable to you. We will take your suggestion into consideration for future updates and improvements.

If you have any further questions or need assistance, please feel free to ask. We're here to help!
