### ISSUE TITLE
Co-DETR support

### ISSUE THREAD

**Issue by Kayzwer** [ultralytics/ultralytics#3619]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

support training Co-DETR model.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Kayzwer thank you for your interest in YOLOv8! Currently, YOLOv8 does not support training the Co-DETR model. YOLOv8 is primarily focused on object detection, segmentation, classification, and pose/keypoint estimation tasks. Co-DETR, on the other hand, is a different object detection model that combines YOLO with the DETR architecture.

While we do not currently support training the Co-DETR model in YOLOv8, we appreciate your suggestion. If you would like to contribute and submit a pull request (PR) to add support for Co-DETR training in YOLOv8, we would be happy to review and consider it. Feel free to reach out if you have any further questions or need assistance with YOLOv8.
