### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by Neloy262** [ultralytics/ultralytics#3623]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

`from ultralytics import YOLO
model = YOLO("yolov8n.pt")  
while True:
    results = model("https://ultralytics.com/images/bus.jpg")  
`

Running this code consumes 2.5 GB of memory(RAM). Is this normal? I am running on windows.

**Comment by harshdhamecha** [comment]
You are running it for infinite times (i.e. `while True:`). Run it without any loop. Try the following code:

```
from ultralytics import YOLO
model = YOLO("yolov8n.pt")
results = model("https://ultralytics.com/images/bus.jpg")
```

**Comment by Neloy262** [comment]
The thing is i am using the model to infer on frames received from a rtsp stream. And even there I face the same issue.

**Comment by glenn-jocher** [comment]
Hi @Neloy262, 

Thank you for reaching out. Regarding the high memory usage you're experiencing with YOLOv8, it's important to note that YOLOv8 is a resource-intensive model, and it's normal for it to consume a significant amount of memory when processing images or video frames. 

In your case, running the code in an infinite loop (`while True:`) can exacerbate the memory usage, as the model continuously processes new frames without releasing memory. To mitigate this, I would recommend running the code without the loop and only process the frames you need at the moment.

If you're using the model to infer on frames received from an RTSP stream, you might consider implementing a mechanism to process and release memory after each frame is processed. This can help limit the memory consumption. Additionally, you could consider optimizing other parts of your code or using hardware with more memory capacity to handle the workload more efficiently.

If you have any further questions or need additional assistance, please don't hesitate to ask. Thanks!

**Comment by Neloy262** [comment]
@glenn-jocher by releasing memory do you mean release the processed frames?

**Comment by glenn-jocher** [comment]
Hi @Neloy262,

Releasing memory refers to freeing up the memory that is occupied by the processed frames or any other temporary data that is no longer needed. In the case of using YOLOv8 to infer on frames received from an RTSP stream, you can release memory by ensuring that you are not storing every processed frame in memory indefinitely. Once a frame has been processed and you have extracted the necessary information or made predictions, you can safely discard that frame from memory to free up space for processing the next frame.

By releasing memory after each frame, you can mitigate the issue of high memory usage and ensure more efficient memory management.

If you have any further questions or need additional clarification, please let me know.

Best regards,
Glenn Jocher

**Comment by pedromoraesh** [comment]
@glenn-jocher I'm having the same issue:

- Nvidia 4070TI
- Cuda 11.8
- Intel i9 13900K
- 32 GB RAM

``` python
from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO("yolov8n.pt")

# Define remote image or video URL
source = "video.mp4"

# run 10 times
model.predict(source, save=False, imgsz=416, conf=0.5, device=0, batch=32)
```

When I run the script above, my normal ram consumption grows exponentially while my GPU is only using 1 GB. As you can note, I'm not running Predict inside any loop and not saving any results or even using predictions (yet).

Note: my example video is about 4.8GB, 2 hours, 10 FPS.

That's my HTOP with only 5% of the video being processed.

![image](https://github.com/ultralytics/ultralytics/assets/16081608/d1b268c4-3135-49f4-888a-16e888af7e21)

And here we can note only 1GB of GPU usage, considering there are other processes beyond the usage of Python3

![image](https://github.com/ultralytics/ultralytics/assets/16081608/903faf97-c740-4ead-9082-caa2ddffe52d)

**Comment by 0xSofea** [comment]
> By releasing memory after each frame, you can mitigate the issue of high memory usage and ensure more efficient memory management.

Hi, may i know how to release the memory after each frame?

**Comment by glenn-jocher** [comment]
Absolutely, @0xSofea.

After you process each frame, you can release memory by ensuring variables that hold frame data are reassigned or deleted if they are no longer needed. This could be as simple as overwriting the variable with the next frame or explicitly using `del variable` if you want to manually remove a large object from memory. In Python, the garbage collector automatically frees up memory when objects are no longer in use, but manually managing can help, especially in a loop where references might inadvertently be kept alive.

Always ensure you don't have unnecessary references to data that's no longer needed, and this should help manage your memory usage. For real-time applications, carefully structuring your code to process one frame at a time without holding onto past data is key.

If the problem persists, consider reviewing your code for memory-intensive operations or data structures that could contribute to high memory usage.

**Comment by dcarrion87** [comment]
We're seeing the same issue with RTMP stream. We're looking at ways to make inference as lean as possible. Loading model takes 400MB RAM but as soon as tracking starts blows out to 2.5-3.0GB which is way too much for lean implementation we're trying to achieve.
