### ISSUE TITLE
No utility to print out the environment

### ISSUE THREAD

**Issue by AndreaPi** [ultralytics/ultralytics#3631]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

This codebase is missing a script to print out the enviroment, like the one from MMDetection for example:

https://github.com/open-mmlab/mmdetection/blob/main/mmdet/utils/collect_env.py

Such a script would be very useful. It would make documenting bugs and issues much easier and consistent, because the person opening the issue would simply need to run the script, and a standard description of the enviroment would be printed to screen. This description could then be printed in each issue or bug. Please consider adding such a script to `ultralytics`.

### Use case

A user who's opening a issue would run the `collect_env` script, copy & paste its output in the new issue. This would make issue creation and bug reporting much more consistent.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by harshdhamecha** [comment]
If you have such suggestions, you should open a PR

**Comment by AndreaPi** [comment]
@harshdhamecha no, I shouldn't. It's an usability issue, and I can absolutely raise this point without having to open a PR

**Comment by glenn-jocher** [comment]
Hi @AndreaPi, thank you for your suggestion. I understand that having a script to print out the environment would be useful for documenting bugs and issues consistently. While I appreciate your request, opening a pull request with the implementation would be the best way to contribute this feature to the YOLOv8 repository. The maintainers can then review and discuss the proposed changes. If you need any guidance or assistance while creating the pull request, feel free to ask. Thank you for your understanding.

**Comment by AndreaPi** [comment]
Hi @glenn-jocher I don't have the time to get familiar enough with the codebase, to open a well-integrated PR. However, what I could do at some point in the future, would be to copy (with minor adaptation) this code:

https://github.com/open-mmlab/mmengine/blob/main/mmengine/utils/dl_utils/collect_env.py

1.  would that be enough?
2. where should I put the code? would `ultralytics/yolo/utils` be ok?
3. I will be adding docstrings as required by your PR guide https://github.com/ultralytics/ultralytics/blob/b239246452b9321e17287af8e92a9d449fa2216b/CONTRIBUTING.md, but I won't be adding unit tests, nor will I configure a CI/CD pipeline on my side, to be sure the PR passes all tests. You'll be doing that on your side. Is that ok?

If these conditions are fine with you, I'll open a PR later on, linking this issue.

**Comment by glenn-jocher** [comment]
Hi @AndreaPi, thank you for your willingness to contribute to the YOLOv8 repository. I appreciate your consideration of adding a script to print out the environment for better issue documentation. Here are the answers to your questions:

1. It would be great if you could adapt and provide the code from the given repository. This would help in creating a consistent and standardized environment description for bug reporting.

2. You can place the code in the `ultralytics/yolo/utils` directory. This is a suitable location for utilities that are commonly used within the YOLOv8 codebase.

3. Adding docstrings is definitely encouraged, as it helps with code readability and maintainability. While unit tests and CI/CD pipelines are valuable additions, I understand that not everyone has the resources or expertise to set them up. Don't worry about configuring those on your end. The maintainers will handle the necessary steps for testing and continuous integration during the review process.

If these conditions work for you, please go ahead and open a pull request later on, linking it to this issue. The maintainers will review your contribution and provide further guidance if needed. Thank you again for your initiative and for considering the YOLOv8 repository.
