### ISSUE TITLE
how to show progress while training on jupyter notebook 

### ISSUE THREAD

**Issue by hoangnhien2411** [ultralytics/ultralytics#364]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

how to show progress while training on jupyter notebook . When I training, my notebook don't show anything, I want to track the process[
![Ảnh chụp màn hình_20230115_085110](https://user-images.githubusercontent.com/56782941/212510743-59db5f7d-8257-443d-8455-7c9be705f440.png)

**Comment by Robotatron** [comment]
1. Try their python API, maybe then it will show the progress
2. Try having only `!yolo .....`  in a cell, without `%cd ...`
3. Why not use a command line? :)

**Comment by ichsan2895** [comment]
its strange, it works in my computer.. Jupyter notebooks (from VSCode) show the progres
![image](https://user-images.githubusercontent.com/60387342/212537738-0ca3faa0-26e8-4ad2-a5f6-95c90aa922ce.png)

**Comment by Robotatron** [comment]
Probably because your cell has only 1x command line input. The person had "%cd" as well
