### ISSUE TITLE
set maximum possible object to be detect of Yolov8 during training

### ISSUE THREAD

**Issue by Kayzwer** [ultralytics/ultralytics#3641]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

reduce the maximum number of possible detection to speed up inference.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Kayzwer thank you for reaching out! In YOLOv8, the maximum number of possible detections is determined by the number of anchor boxes and the number of classes in your dataset. If you would like to reduce the maximum number of detections, you can modify the anchor boxes and classes accordingly.

In the YOLOv8 codebase, the anchor boxes are defined in the `anchors.txt` file, and the number of classes is specified in the `yolov8.py` file. Adjusting these values will directly affect the maximum number of detections during inference.

Please note that reducing the maximum number of detections may also affect the model's accuracy, as it may discard potential objects. Additionally, it's important to find the right balance between speed and accuracy, as too few detections may lead to missed objects.

I hope this helps! If you have any further questions or need assistance, please feel free to ask.
