### ISSUE TITLE
Error: CUDA Out of memory when predict segmentation

### ISSUE THREAD

**Issue by z2ao** [ultralytics/ultralytics#3651]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I got CUDA OOM error when I predict segmentation.  
I'd love to know how I can get it to work and avoid that error.  

<br>

Please help me. 🙏  

<br>

## Tries

- I want to predict 100 images  

```python
## Try 1. basic
images = [ image path 1, image path 2, ... ]
model.predict(
    source = images,
    imgsz = 950,           ## same to training argument
    max_det = 1000,
    device = 3,
)
```
```python
## Try 2. images resize smaller
from PIL import Image

images = [ image path 1, image path 2, ... ]
images = [ Image.open(image)  for image in images]
images = [ image.resize((smaller_w, smaller_h )) for image in images]
model.predict(
    source = images,
    imgsz = 950,           ## same to training argument
    max_det = 1000,
    device = 3,
)
```
```python
## Try 3. for loop 1 by 1
preds = []
for image in images:
    pred = model(
        source = image,
        imgsz = 950,
        max_det = 1000,
        device = 3, 
    )
    preds += pred
```
```python
## Try 4. Clear CUDA cache
preds = []
for image in images:
    pred = model(
        source = image,
        imgsz = 950,
        max_det = 1000,
        device = 3, 
    )
    preds += pred
    
    del pred
    gc.collect()
    torch.cuda.empty_cache()
```
```python
## Try 5. Predict use `stream=True`
pred_stream = model(
    source = image,
    stream = True,
    imgsz = 950,
    max_det = 1000,
    device = 3, 
)

preds = []
for pred in pred_stream:
    preds.append(pred)
```
<br>

## Error

- It looks like the problem is in the source on the postprocess side.  

```python
---------------------------------------------------------------------------
OutOfMemoryError                          Traceback (most recent call last)
File <timed exec>:7

File /opt/conda/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py:111, in YOLO.__call__(self, source, stream, **kwargs)
    109 def __call__(self, source=None, stream=False, **kwargs):
    110     """Calls the 'predict' function with given arguments to perform object detection."""
--> 111     return self.predict(source, stream, **kwargs)

File /opt/conda/envs/yolov8/lib/python3.8/site-packages/torch/autograd/grad_mode.py:27, in _DecoratorContextManager.__call__.<locals>.decorate_context(*args, **kwargs)
     24 @functools.wraps(func)
     25 def decorate_context(*args, **kwargs):
     26     with self.clone():
---> 27         return func(*args, **kwargs)

File /opt/conda/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py:255, in YOLO.predict(self, source, stream, **kwargs)
    253     if 'project' in overrides or 'name' in overrides:
    254         self.predictor.save_dir = self.predictor.get_save_dir()
--> 255 return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)

File /opt/conda/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py:190, in BasePredictor.__call__(self, source, model, stream)
    188     return self.stream_inference(source, model)
    189 else:
--> 190     return list(self.stream_inference(source, model))

File /opt/conda/envs/yolov8/lib/python3.8/site-packages/torch/autograd/grad_mode.py:43, in _DecoratorContextManager._wrap_generator.<locals>.generator_context(*args, **kwargs)
     40 try:
     41     # Issuing `None` to a generator fires it up
     42     with self.clone():
---> 43         response = gen.send(None)
     45     while True:
     46         try:
     47             # Forward the response to our caller and get its next request

File /opt/conda/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py:252, in BasePredictor.stream_inference(self, source, model)
    250 # Postprocess
    251 with profilers[2]:
--> 252     self.results = self.postprocess(preds, im, im0s)
    253 self.run_callbacks('on_predict_postprocess_end')
    255 # Visualize, save, write results

File /opt/conda/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/v8/segment/predict.py:37, in SegmentationPredictor.postprocess(self, preds, img, orig_imgs)
     35     if not isinstance(orig_imgs, torch.Tensor):
     36         pred[:, :4] = ops.scale_boxes(img.shape[2:], pred[:, :4], orig_img.shape)
---> 37     masks = ops.process_mask_native(proto[i], pred[:, 6:], pred[:, :4], orig_img.shape[:2])  # HWC
     38 else:
     39     masks = ops.process_mask(proto[i], pred[:, 6:], pred[:, :4], img.shape[2:], upsample=True)  # HWC

File /opt/conda/envs/yolov8/lib/python3.8/site-packages/ultralytics/yolo/utils/ops.py:638, in process_mask_native(protos, masks_in, bboxes, shape)
    635 bottom, right = int(mh - pad[1]), int(mw - pad[0])
    636 masks = masks[:, top:bottom, left:right]
--> 638 masks = F.interpolate(masks[None], shape, mode='bilinear', align_corners=False)[0]  # CHW
    639 masks = crop_mask(masks, bboxes)  # CHW
    640 return masks.gt_(0.5)

File /opt/conda/envs/yolov8/lib/python3.8/site-packages/torch/nn/functional.py:3950, in interpolate(input, size, scale_factor, mode, align_corners, recompute_scale_factor, antialias)
   3948     if antialias:
   3949         return torch._C._nn._upsample_bilinear2d_aa(input, output_size, align_corners, scale_factors)
-> 3950     return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
   3951 if input.dim() == 5 and mode == "trilinear":
   3952     assert align_corners is not None

OutOfMemoryError: CUDA out of memory. Tried to allocate 5.96 GiB (GPU 0; 39.59 GiB total capacity; 32.58 GiB already allocated; 5.31 GiB free; 32.70 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### Additional

[ My env ]  
- OS : ubuntu 18.04  
- Python library :  
  - ultralytics : 8.0.125  
  - torch : 1.13.1  
  - torchvision : 0.14.1

**Comment by Kayzwer** [comment]
@z2ao Hi, I did like to know the imgsz you set when training, seen like 950 is not divisible by 32.

**Comment by z2ao** [comment]
@Kayzwer  

Actually, I set it up that way because I don't have a deep knowledge of machine vision and I was just following along with some examples.  

<br>

There's no particular reason for it, I'm just experimenting with it.  
Thank you for your opinion.

**Comment by z2ao** [comment]
@Kayzwer Ah, could that be a problem?

**Comment by Kayzwer** [comment]
how about you try run the inference in CIL? `yolo detect predict source="/path/to/img_folder/" model="/path/to/.pt" max_det=1000 device=3`

**Comment by z2ao** [comment]
@Kayzwer  Yes, I got same error ... 😭😭😭

**Comment by Kayzwer** [comment]
how about just one image? `yolo segment predict source="/path/to/img" model="/path/to/.pt" max_det=1000 device=3`

**Comment by z2ao** [comment]
@Kayzwer 
- Just one image : OK  
- The ones I've tried usually work up to 17-19.

**Comment by Kayzwer** [comment]
@z2ao can you pay attention to your GPU ram usage when inferring one image? see how much memory does it take.

**Comment by z2ao** [comment]
@Kayzwer 

Here is details.  

- GPU Device : A100-SXM4-40GB  
- Pretrained model : yolov8m-seg  
- Task : segment  
- Class : 54  
- RAM usage  
  - upload model : 1,072MiB / 40,537 MiB  
  - max usage when 1 image : 2,230MiB / 40537 MiB

**Comment by glenn-jocher** [comment]
@z2ao 

Thank you for providing the details. It seems that the GPU memory usage is within the expected range for the YOLOv8 model during inference. The increase in memory usage when processing multiple images is likely due to the accumulation of intermediate results and post-processing operations.

The YOLOv8 model is designed to process images in batches for improved efficiency. If you are processing a large number of images and encountering GPU memory issues, you can try reducing the batch size or processing the images in smaller subsets.

Additionally, you can consider using mixed precision training, which uses lower precision arithmetic to reduce memory usage without sacrificing much accuracy.

I hope this helps! Let me know if you have any further questions.

**Comment by z2ao** [comment]
@glenn-jocher  

Thank you for your reply. 😊  
So, how can I adjust the batches in predict mode ?

**Comment by z2ao** [comment]
@Kayzwer @glenn-jocher 

Currently, I'm using the following with the `upsample=False` option.

I modified the source like this because I only need the **boxes** information for now.  
But if I need to utilize the **masks** information, I'll need to make sure that part is computable.

https://github.com/ultralytics/ultralytics/blob/b239246452b9321e17287af8e92a9d449fa2216b/ultralytics/yolo/v8/segment/predict.py#L39

Thank you guys.

**Comment by z2ao** [comment]
@Kayzwer @glenn-jocher 

Currently, I'm using the following with the `upsample=False` option.  

I modified the source like this because I only need the **boxes** information for now.  
But if I ever need to utilize the **masks** information, I'll need to make sure that part is computable.  

https://github.com/ultralytics/ultralytics/blob/b239246452b9321e17287af8e92a9d449fa2216b/ultralytics/yolo/v8/segment/predict.py#L39

Thank you guys.

**Comment by glenn-jocher** [comment]
@Kayzwer 

Thank you for your question. 

In the YOLOv8 repository, the predict function in the `segment/predict.py` file allows you to adjust the batch size for predicting on multiple images. However, please note that modifying the code in `predict.py` may not directly impact the batch size for prediction.

By default, YOLOv8 performs inference on multiple images simultaneously to improve efficiency. The batch size is determined by the number of images passed to the `predict` function. If you want to adjust the batch size, you can modify the code where you call the `predict` function and provide a smaller subset of images as the input.

For example, instead of passing all 100 images at once, you can split them into smaller subsets (e.g., batches of 10 images) and call the `predict` function multiple times, iterating over each subset. This way, you can control the batch size and potentially reduce the GPU memory usage.

Keep in mind that adjusting the batch size may impact the overall performance and inference time. It's essential to find a balance between batch size, memory usage, and inference speed that suits your specific needs and hardware capabilities.

I hope this clarifies how you can adjust the batch size for prediction in YOLOv8. Let me know if you have any further questions.
