### ISSUE TITLE
Cannot run custome train on GPU:1  , (Cannot specify gpu number in training yolov8 -- single gpu )

### ISSUE THREAD

**Issue by creativesh** [ultralytics/ultralytics#3656]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hi 

I work with : 

ubuntu 20 and the othe requirements are installed as the git repository mentioned.

gpu:0 is busy and I want to run my train code just on gpu:1 , I want single gpu training not multi gpu

but  no matter , in which way I set the device to 1, the train would run on gpu:0 , leading to  memory error:

 these are some ways are tested: 

CUDA_VISIBLE_DEVICES="1"  python  mytrain.py 
os.environ['CUDA_VISIBLE_DEVICES'] = "1"   # in mytrain.py 
yolo detect train  data=drone.yaml model=yolov8x.yaml  pretrained=yolov8n.pt epochs=100 imgsz=640  device=1

Is this a bug or is there any way to change the default gpu number

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@creativesh hi there,

Thank you for reaching out about running custom training on a specific GPU using YOLOv8. I understand that you want to run your training code on GPU:1 and not on GPU:0. However, despite trying different approaches like setting the CUDA_VISIBLE_DEVICES environment variable and specifying the device number in your train command, the training still runs on GPU:0, leading to a memory error.

I apologize for any confusion or frustration this may have caused. Currently, YOLOv8 does not have a built-in option to select a specific GPU for training when using a single GPU setup. By default, PyTorch assigns the first available GPU (GPU:0 in your case) for training.

If you have multiple GPUs and want to train on a specific GPU, you would need to have a multi-GPU setup and use PyTorch's DataParallel or DistributedDataParallel to distribute the training across multiple GPUs.

However, if you have only one GPU and still want to run the training on GPU:1 to avoid the memory error, one possible workaround is to disable GPU:0 for training by using CUDA_VISIBLE_DEVICES="1" when launching the training script or setting the environment variable before running the script.

I hope this clarifies the situation, and I apologize again for any inconvenience. If you have any further questions or need assistance with anything else, please feel free to ask.

Best regards,
Glenn Jocher
