### ISSUE TITLE
Possible solution to avoid uninstalling `wandb` in `Ultralytics` notebooks

### ISSUE THREAD

**Issue by soumik12345** [ultralytics/ultralytics#3659]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Currently `wandb` is being uninstalled while using the `YOLO` CLI in notebooks ([reference](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/utils/checks.py#L334-L335)). Is it possible to avoid uninstalling `wandb` in `ultralytics` notebooks by turning off `wandb` by default and adding a flag to the `YOLO` CLI that turns on the `wandb` usage as mentioned in https://github.com/wandb/wandb/issues/5746?

**Comment by glenn-jocher** [comment]
@soumik12345 hi there! Thank you for reaching out with your question.

Currently, the `wandb` library is being uninstalled when using the `YOLO` CLI in Ultralytics notebooks. This is done by default to avoid any potential conflicts or issues with the `wandb` library.

If you would like to use `wandb` in Ultralytics notebooks, you can manually install it after running the `YOLO` CLI commands. You can reinstall `wandb` by running `pip install wandb` in a code cell.

However, I understand that it would be more convenient to have an option to enable or disable `wandb` directly within the `YOLO` CLI. While this is not currently supported, your suggestion to add a flag to the `YOLO` CLI to control `wandb` usage is interesting. I recommend posting this suggestion as a feature request in the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) page on GitHub. This way, the Ultralytics team can consider implementing this feature in a future update.

Let me know if you have any further questions. Happy coding!

**Comment by soumik12345** [comment]
> @soumik12345 hi there! Thank you for reaching out with your question.
> 
> Currently, the `wandb` library is being uninstalled when using the `YOLO` CLI in Ultralytics notebooks. This is done by default to avoid any potential conflicts or issues with the `wandb` library.
> 
> If you would like to use `wandb` in Ultralytics notebooks, you can manually install it after running the `YOLO` CLI commands. You can reinstall `wandb` by running `pip install wandb` in a code cell.
> 
> However, I understand that it would be more convenient to have an option to enable or disable `wandb` directly within the `YOLO` CLI. While this is not currently supported, your suggestion to add a flag to the `YOLO` CLI to control `wandb` usage is interesting. I recommend posting this suggestion as a feature request in the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) page on GitHub. This way, the Ultralytics team can consider implementing this feature in a future update.
> 
> Let me know if you have any further questions. Happy coding!

Thanks for your response @glenn-jocher!

**Comment by glenn-jocher** [comment]
Thanks for reaching out, @soumik12345! Currently, in YOLOv8, the `wandb` library is uninstalled by default when using the YOLO CLI in Ultralytics notebooks. This is done to prevent any potential conflicts or issues with `wandb`.

If you would like to use `wandb` in Ultralytics notebooks, you can manually install it after running the YOLO CLI commands. You can reinstall `wandb` by running `pip install wandb` in a code cell.

I understand that it would be more convenient to have an option to control `wandb` usage directly within the YOLO CLI. While this feature is not currently supported, your suggestion to add a flag to the YOLO CLI to enable or disable `wandb` usage is interesting. I recommend posting this suggestion as a feature request in the YOLOv8 issues page on GitHub. This way, the Ultralytics team can consider implementing this feature in a future update.

Let me know if you have any further questions or need assistance. Happy coding!
