### ISSUE TITLE
[FR] Rename metric names logged in Tensorboard to be the same as in YOLO5.

### ISSUE THREAD

**Issue by Robotatron** [ultralytics/ultralytics#366]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Rename metric names logged in Tensorboard to be the same as in YOLO5.

ps. If there is a workaround for this please let me know

![image](https://user-images.githubusercontent.com/95919873/212520543-22cc6939-166d-4428-806b-c1f339e67023.png)

### Use case

Comparing runs with Tensorboard from v5 to v8 is a worse user experience since names of graphs are different, see image above

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
We're using that denotation because we need both mask and box metrics. If we use the same name, they will be overwritten.
You can modify your branch to change the metrics name but I think doing that for all users will break the metrics

**Comment by Robotatron** [comment]
> We're using that denotation because we need both mask and box metrics. If we use the same name, they will be overwritten. You can modify your branch to change the metrics name but I think doing that for all users will break the metrics

It seems there is an misunderstanding. The mask metrics have **`(M)`** appended in both YOLO5 and YOLO8 metrics:

- mAP_0.5(M) for YOLO5
- mAP50(M) for YOLO8

The box metrics, for both YOLO5 and 8 have **`(B)`** appended to the metric name.

However the name of e.g.  `mAP_0.5(M)`  from YOLo5 was changed to `mAP50(M)` in YOLO8 so that comparing runs from v5 to v8 in Tensorboard now produces two different graphs (see image above). Renaming `mAP50(M)` from v8 to  `mAP_0.5(M)` (as it is in YOLOv5) will not break or overwrite anything for boxes (because boxes have a different name with `"(B)"` appended to the name) and will make so that metrics from v5 and v8 can be shown in the same graph in Tensorboard.

**Comment by AyushExel** [comment]
@Robotatron ohh I see now I understand. Yes that's a good point. I'll add to todos

**Comment by dickymuhr** [comment]
Just curious, from what metric/mAP calculated? Is it val or test data?

**Comment by pderrenger** [comment]
@dickymuhr the mAP (mean Average Precision) is typically calculated using the validation dataset. This metric measures the accuracy of the object detection model, taking into account both precision and recall, and is commonly used to evaluate the performance of the model.

**Comment by glenn-jocher** [comment]
@pderrenger The mAP is calculated on the validation dataset during training to evaluate the model's performance. 👍
