### ISSUE TITLE
How to train re-detr in YOLOv8?

### ISSUE THREAD

**Issue by remeberWei** [ultralytics/ultralytics#3663]
### Search before asking

- [ ] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hello! I tried to train the rt-detr-l.yaml file on YOLOv8, but the error was "RTDETEDecoder object has no attribute 'stripe'" . May I ask why?Can you help me?

### Minimal Reproducible Example

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/741 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/zhangwei/software/anaconda3/envs/highversion/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/zhangwei/software/anaconda3/envs/highversion/lib/python3.7/site-packages/ultralytics/yolo/cfg/__init__.py", line 407, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/zhangwei/software/anaconda3/envs/highversion/lib/python3.7/site-packages/ultralytics/yolo/engine/model.py", line 373, in train
    self.trainer.train()
  File "/home/zhangwei/software/anaconda3/envs/highversion/lib/python3.7/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/zhangwei/software/anaconda3/envs/highversion/lib/python3.7/site-packages/ultralytics/yolo/engine/trainer.py", line 332, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File "/home/zhangwei/software/anaconda3/envs/highversion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhangwei/software/anaconda3/envs/highversion/lib/python3.7/site-packages/ultralytics/nn/tasks.py", line 44, in forward
    return self.loss(x, *args, **kwargs)
  File "/home/zhangwei/software/anaconda3/envs/highversion/lib/python3.7/site-packages/ultralytics/nn/tasks.py", line 212, in loss
    self.criterion = self.init_criterion()
  File "/home/zhangwei/software/anaconda3/envs/highversion/lib/python3.7/site-packages/ultralytics/nn/tasks.py", line 293, in init_criterion
    return v8DetectionLoss(self)
  File "/home/zhangwei/software/anaconda3/envs/highversion/lib/python3.7/site-packages/ultralytics/yolo/utils/loss.py", line 117, in __init__
    self.stride = m.stride  # model strides
  File "/home/zhangwei/software/anaconda3/envs/highversion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1270, in __getattr__
    type(self).__name__, name))
AttributeError: 'RTDETRDecoder' object has no attribute 'stride'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Rusab** [comment]
Hi @remeberWei,
I think you loaded the RT-DETR model with the YOLO class like this:
model = YOLO('rtdetr-l.yaml')
instead you shoud use the RTDETR class:
model = RTDETR('rtdetr-l.yaml')

**Comment by remeberWei** [comment]
Thanks for your reply! But I don't ues this way to train rt-detr model, I train rt-dter model by "yolo cfg=default.yaml", if I continue using this way, where do I need&nbsp; to adjust? Thank you!



---Original---
From: "Rusab ***@***.***&gt;
Date: Wed, Jul 12, 2023 00:58 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ultralytics/ultralytics] How to train re-detr in YOLOv8? (Issue#3663)




 
Hi @remeberWei,
 I think you loaded the RT-DETR model with the YOLO class like this:
 model = YOLO('rtdetr-l.yaml')
 instead you shoud use the RTDETR class:
 model = RTDETR('rtdetr-l.yaml')

**Comment by glenn-jocher** [comment]
See train example in https://docs.ultralytics.com/models/rtdetr/#python-api

**Comment by remeberWei** [comment]
oh，it's working，thank you very much，



---Original---
From: "Glenn ***@***.***&gt;
Date: Wed, Jul 12, 2023 07:45 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ultralytics/ultralytics] How to train re-detr in YOLOv8? (Issue#3663)




 
See train example in https://docs.ultralytics.com/models/rtdetr/#python-api

**Comment by glenn-jocher** [comment]
@Rusab hi there,

I'm glad to hear that it's working for you! You're welcome and don't hesitate to reach out if you have any further questions or issues.

Best regards,
Glenn

**Comment by remeberWei** [comment]
Just now I found a problem, I don't know why, the time to train RT-DTER, only parameter values without GFLOPs, do you know why?
![1689142718061](https://github.com/ultralytics/ultralytics/assets/91881703/252a5f84-093e-4ab0-a595-a0c5e2b036c3)

**Comment by glenn-jocher** [comment]
@remeberWei hello!

Thank you for bringing this issue to our attention. It looks like you're experiencing an unexpected behavior while training the RT-DTER model in YOLOv8. The training time is being displayed without any GFLOPs (giga floating-point operations per second) values.

There could be a few reasons for this issue. One possibility is that the GFLOPs calculation is not enabled or implemented for the RT-DTER model in YOLOv8. Another possibility is that there may be an issue with the display or calculation of GFLOPs in the specific training scenario you are using.

To further investigate and resolve this issue, I would recommend checking the implementation of the RT-DTER model in YOLOv8 to ensure that GFLOPs calculation is properly enabled or implemented. You can also try comparing your training setup with the examples and documentation provided in the YOLOv8 repository to see if there are any differences or missing configurations.

If the issue persists or you need further assistance, please provide more details about your training setup, command line arguments, and any modifications you made to the YOLOv8 codebase. This will help us understand the issue better and provide more specific guidance.

We appreciate your patience and understanding as we work together to resolve this issue.

Best regards,
Glenn

**Comment by kuguahentian** [comment]
> Just now I found a problem, I don't know why, the time to train RT-DTER, only parameter values without GFLOPs, do you know why? ![1689142718061](https://user-images.githubusercontent.com/91881703/252872543-252a5f84-093e-4ab0-a595-a0c5e2b036c3.png)

I had the same problem. Did you solve it? How did you solve it?

**Comment by glenn-jocher** [comment]
@kuguahentian

I understand that you encountered an issue with the training time of the RT-DTER model in YOLOv8 not displaying the GFLOPs values. Unfortunately, I don't have an immediate solution to this problem. It's possible that the GFLOPs calculation might not be enabled or implemented for the RT-DTER model in YOLOv8. 

To address this issue, I would recommend checking the implementation of the RT-DTER model in YOLOv8 and ensuring that the GFLOPs calculation is properly enabled or implemented. Comparing your training setup with the examples and documentation provided in the YOLOv8 repository might also help identify any differences or missing configurations.

If you have made any progress or found a solution to this issue, I would appreciate it if you could share your findings with the community. This would be helpful for other users who might encounter the same problem.

Thank you for highlighting this issue, and I apologize for any inconvenience caused.

**Comment by dxm620** [comment]
RT-DETR的训练意外中断，使用官方文档的断点继续训练方法后，出现报错AttributeError: 'RTDETRDecoder' object has no attribute stride，如何解决呢？

**Comment by dxm620** [comment]
The training of RT-DETR was unexpectedly interrupted. After using the breakpoint in the official documentation to continue training, an error message AttributeError occurred: 'RTDETRDecoder' object has no attribute stripe. How can we resolve this issue?

**Comment by glenn-jocher** [comment]
Hello,

It seems like there might be a mismatch or an issue with the attribute access in the RT-DETR model. The error you're encountering typically indicates that the code is trying to access an attribute (`stripe`) that doesn't exist in the `RTDETRDecoder` class.

Here are a few steps to troubleshoot and potentially resolve this issue:

1. **Check for Typos:** Ensure that there is no typo in the attribute name in your code or in any modifications you might have made.
2. **Update Your Code:** Make sure you are using the latest version of the YOLOv8 repository as updates might have fixed this issue.
3. **Review Class Definitions:** Look into the `RTDETRDecoder` class definition to confirm if the `stripe` attribute should exist. If it's based on a recent change, updating your repository might help.

If these steps do not resolve the issue, please provide more details about the context in which this error occurs, and we can investigate further.

**Comment by ovidedecroly** [comment]
Hi @glenn-jocher 
I hope you're doing well. I am currently working on a project where I would like to use the YOLOv8 or YOLOv10 model but with pretrained weights from RTDETR-l.pt. I have encountered some challenges in getting this setup to work and would appreciate any guidance or best practices you can provide.

Here are the steps I've followed and the issues I'm encountering:
from ultralytics import YOLO

# Initialize the model with YOLOv10 configuration
model = YOLO("yolov10n.yaml")

# Attempt to load RTDETR-l pretrained weights
model.load("RTDETR-l.pt")

results = model.train(
    data="/content/drive/MyDrive/DISERTASI/DATASET/extracted_harimau/final_data/data.yaml",
    epochs=100,
    optimizer='Adam',
    imgsz=(1920, 1080),
    batch=4,
    amp=True,
    cache='ram'
)

Thanks

**Comment by glenn-jocher** [comment]
Hi @ovidedecroly,

I hope you're doing well too. It seems like you're trying to use pretrained weights from RTDETR-l.pt with a YOLOv10 configuration. Unfortunately, pretrained weights from RT-DETR are not directly compatible with YOLOv8 or YOLOv10 models due to architectural differences.

To proceed, I recommend using the RT-DETR model directly for your project. You can train the RT-DETR model on your dataset by following the examples provided in the [RT-DETR documentation](https://docs.ultralytics.com/models/rtdetr/).

If you encounter any issues, please ensure you are using the latest version of the Ultralytics package. If the problem persists, feel free to provide more details, and we can look into it further.

**Comment by AydinGarnet** [comment]
How do I combine yolo and rtdter models together for object detection?
