### ISSUE TITLE
Is model ensembling available for Yolov8?

### ISSUE THREAD

**Issue by Rusab** [ultralytics/ultralytics#3665]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, @glenn-jocher. Is model ensembling available for ultralytics library? 
You had mentioned two functions in this issue: https://github.com/ultralytics/ultralytics/issues/3036
But I couldn't find them in the ultralytics library.

**Comment by glenn-jocher** [comment]
@Rusab hi,

Yes, model ensembling is available in YOLOv8. The two functions you mentioned in the issue, `ensemble` and `nms`, are indeed part of the Ultralytics library and can be used for ensembling multiple YOLOv8 models or performing non-maximum suppression (NMS) on the predicted bounding boxes.

To use the `ensemble` function, you can pass a list of YOLOv8 models as arguments and it will merge their predictions to generate a single set of bounding box detections.

The `nms` function is used to perform NMS on the predicted bounding boxes. It helps remove redundant and overlapping detections, ensuring that only the most confident and accurate bounding boxes remain.

Please make sure you have the latest version of the Ultralytics library installed, as these functions should be available. If you're still unable to find them, please let us know and we'll be happy to assist you further.

Please note that while ensembling can improve detection accuracy, it may also increase processing time and resource requirements.

I hope this clarifies your query. Let me know if you have any further questions!

Best regards,
Glenn Jocher

**Comment by Rusab** [comment]
Hi @glenn-jocher, thank you for the reply. 

I think the Ensemble class is the one in `ultralytics.nn.tasks` 
I tried loading both models and weights like this:
`model = ultralytics.nn.tasks.Ensemble([YOLO('yolov8m.pt'), YOLO('yolov8m.pt')])`
or like this:
`model = ultralytics.nn.tasks.Ensemble(['weights/best1.pt','weights/best2.pt'])`
but in both cases I get this error:
`TypeError: Ensemble.__init__() takes 1 positional argument but 2 were given`

So, I guess this is not the right format. Can you provide me the correct syntax for using the mentioned function?

Thanks,
Rusab

**Comment by glenn-jocher** [comment]
Hi @Rusab, 

Thank you for reaching out. It seems like there might be a misunderstanding in the usage of the `Ensemble` class in YOLOv8.

To use the `Ensemble` class, you need to provide a list of YOLOv8 models, not just the paths to the weights. Here's the correct syntax:

```python
model = ultralytics.nn.tasks.Ensemble([YOLO('yolov8m.pt'), YOLO('yolov8m.pt')])
```

In this example, we are creating an ensemble with two YOLOv8 models, both loaded from `yolov8m.pt` weights.

Alternatively, you can also load the models and then pass them to the `Ensemble` class:

```python
model1 = YOLO('weights/best1.pt')
model2 = YOLO('weights/best2.pt')
model = ultralytics.nn.tasks.Ensemble([model1, model2])
```

Please make sure you have the latest version of the Ultralytics library installed to ensure the `Ensemble` class is available.

I hope this clarifies the usage of the `Ensemble` class. If you have any further questions, please feel free to ask.

Best regards,
Glenn Jocher

**Comment by Rusab** [comment]
Hi @glenn-jocher ,
I have tried this syntax, I get the followingerror:
![image](https://github.com/ultralytics/ultralytics/assets/29260943/ae7c36b6-1052-4dee-9a85-0e2252b1b655)

**Comment by Rusab** [comment]
Hi @glenn-jocher,
Please note that I have also imported YOLO class via `from ultralytics import YOLO`. It is not in the screenshot. The Ensemble class doesn't seem to be accepting the array of models .

**Comment by glenn-jocher** [comment]
Hi @Rusab,

Thank you for providing the additional information. It seems like you have correctly imported the `YOLO` class from the `ultralytics` module.

Regarding the `Ensemble` class, please note that it currently only supports the `YOLOv5` models from the Ultralytics library, not the `YOLOv8` models. Therefore, you might encounter errors when trying to use the `Ensemble` class with `YOLOv8` models.

If you wish to ensemble multiple `YOLOv8` models, you can manually combine their predictions using your custom logic. You can run each model separately on your input data and then merge their predictions by averaging the bounding box coordinates and object confidence scores or by using other ensemble techniques.

I apologize for any confusion caused. Please let me know if you have any further questions or if there's anything else I can assist you with.

Best regards,
Glenn Jocher

**Comment by prathamgarg911** [comment]
Hi!! @glenn-jocher, when can we expect the Ensemble feature for YOLOv8 and RT-DETR?

**Comment by glenn-jocher** [comment]
@prathamgarg911 hi there! 

Thank you for your interest in the ensemble feature for YOLOv8 and RT-DETR. Unfortunately, at the moment, the ensemble feature is not available for YOLOv8 or RT-DETR in this repository.

We understand that ensemble methods can be beneficial for improving detection accuracy by combining multiple models. However, for now, if you want to ensemble YOLOv8 and RT-DETR models, you will need to manually combine their predictions using custom logic outside of this repository.

We appreciate your feedback and interest in this feature. The Ultralytics team is continuously working to enhance the functionality of YOLOv8 and RT-DETR, and your input is valuable for future development.

If you have any further questions or suggestions, please feel free to ask. We're here to help!

Warm regards,
Glenn Jocher

**Comment by Rusab** [comment]
Hi @glenn-jocher  thank you for the clarification.

**Comment by glenn-jocher** [comment]
Hi @Rusab,

You're welcome! I'm glad I could assist in clarifying the matter for you. If you have any more questions or face any issues related to YOLOv8 in the future, don't hesitate to reach out. We at Ultralytics and the community are always here to help.

Happy coding, and best of luck with your AI and computer vision endeavors!

Best regards,
Glenn Jocher

**Comment by hdnh2006** [comment]
> Hi @Rusab,
> 
> Thank you for providing the additional information. It seems like you have correctly imported the `YOLO` class from the `ultralytics` module.
> 
> Regarding the `Ensemble` class, please note that it currently only supports the `YOLOv5` models from the Ultralytics library, not the `YOLOv8` models. Therefore, you might encounter errors when trying to use the `Ensemble` class with `YOLOv8` models.
> 
> If you wish to ensemble multiple `YOLOv8` models, you can manually combine their predictions using your custom logic. You can run each model separately on your input data and then merge their predictions by averaging the bounding box coordinates and object confidence scores or by using other ensemble techniques.
> 
> I apologize for any confusion caused. Please let me know if you have any further questions or if there's anything else I can assist you with.
> 
> Best regards, Glenn Jocher

Hello Glenn,

I think there is a misinformation here. I am trying to ensemble YOLOv5 models, and I am getting the same issue than @Rusab:

```
from ultralytics import YOLO
from ultralytics.nn.tasks import Ensemble
model = Ensemble([YOLO('yolov5su.pt'), YOLO('yolov5nu.pt')])
Traceback (most recent call last):

  Cell In[1], line 9
    model = Ensemble([YOLO('yolov5su.pt'), YOLO('yolov5nu.pt')])

TypeError: Ensemble.__init__() takes 1 positional argument but 2 were given
```

Same happens with non `u.pt` models and `v8` models.
Can you please check what I am doing wrong here?

Thanks in advance.

**Comment by Pzzzzzzzzz** [comment]
> 嗨，
> 
> 感谢您提供其他信息。似乎您已从模块中正确导入了类。`YOLO``ultralytics`
> 
> 关于该类，请注意，它目前仅支持Ultralytics库中的模型，不支持模型。因此，尝试将类与模型一起使用时可能会遇到错误。`Ensemble``YOLOv5``YOLOv8``Ensemble``YOLOv8`
> 
> 如果要集成多个模型，可以使用自定义逻辑手动组合它们的预测。您可以对输入数据分别运行每个模型，然后通过平均边界框坐标和对象置信度分数或使用其他集成技术来合并其预测。`YOLOv8`
> 
> 对于造成的任何混乱，我深表歉意。如果您有任何其他问题，或者我还有其他可以帮助您的事情，请告诉我。
> 
> 最好的问候，格伦·乔彻

I hope YOLOv8 can incorporate a built-in function for model ensemble earlier. thank you Glenn

**Comment by glenn-jocher** [comment]
@Pzzzzzzzzz hi there!

Thank you for your feedback. At the moment, Ultralytics YOLOv8 does not have built-in support for model ensembling. Model ensembling typically involves combining the predictions of several models to improve the prediction accuracy.

While we aim to continuously evolve and improve the YOLOv8, currently, integrating a model ensembling feature is not in our direct roadmap for Ultralytics YOLOv8.

If you wish to ensemble multiple models, you would need to manually combine the predictions from each model using custom logic. For example, by running each model separately on your input data and then merging their predictions.

We appreciate your understanding, and thank you for your interest in Ultralytics YOLOv8.

Best regards,
Glenn Jocher

**Comment by devchoradia** [comment]
@glenn-jocher 

I get the same issue when tried with yolov5 as well. The following is what shows up:

from ultralytics import YOLO
from ultralytics.nn.tasks import Ensemble
model = Ensemble([YOLO('yolov5su.pt'), YOLO('yolov5nu.pt')])
Traceback (most recent call last):

  Cell In[1], line 9
    model = Ensemble([YOLO('yolov5su.pt'), YOLO('yolov5nu.pt')])

TypeError: Ensemble.__init__() takes 1 positional argument but 2 were given


Please help me fix this issue. Thanks.

**Comment by glenn-jocher** [comment]
Hi @devchoradia,

I appreciate your patience and understand the issue you're facing. However, I would like to clarify that the current version of the Ultralytics YOLOv8 library does not support model ensembling through its Ensemble class. This is why you're encountering the TypeError when trying to pass multiple YOLO models into the ensemble.

Ensembling is a technique that often boosts the model's prediction performance by averaging the output of multiple models. To perform ensembling with YOLOv8 models, you'll need to manually process the predictions from each model. This involves running each model separately on your input data and then merging the resulting predictions using a method of your choice, such as averaging the bounding box locations and confidence scores.

I apologize for any inconvenience this confusion may have caused and hope to see the Ensemble feature available for YOLOv8 models in the future. Let me know if you have any other questions.

Best regards,
Glenn Jocher

**Comment by GT1984901175** [comment]
Hi @glenn-jocher,
Can I use the model ensembling in the classify task?

**Comment by glenn-jocher** [comment]
@GT1984901175 hi there,

Model ensembling is not currently supported in the classify task for YOLOv8. You would need to implement custom logic to ensemble the classification outputs from multiple models.

**Comment by GT1984901175** [comment]
Hi @glenn-jocher ,
I trained a model for image classification. When I use this classification model, I find that there are no detected targets in the image, and it will also display a result on the image. As shown in the picture below.

![微信图片_20240108091120](https://github.com/ultralytics/ultralytics/assets/150104416/ef4fbc3b-9e8e-42f5-bfef-fd461f19fb91)

![微信图片_20240108091127](https://github.com/ultralytics/ultralytics/assets/150104416/3d2c62f7-9bb7-4658-bc2d-ed74476210e5)

I hope that the result of the target will only be displayed if it appears in the image. No results will appear when there are no detected targets in the image.

My problem is that I don't know how to solve this problem. Is there any way to do this?

**Comment by glenn-jocher** [comment]
@GT1984901175 hi there,

For the classification task, the model will always provide a result since it's predicting the class of the input image as a whole, not detecting individual objects. If you want to avoid displaying a result when the model is not confident, you can set a confidence threshold. Only display the classification result if the model's confidence is above this threshold.

**Comment by GT1984901175** [comment]
Hi @glenn-jocher ,
I trained a classification model using a dataset with two categories. Next, I used a dataset with three categories to train the model on the basis of the already trained two categories. The new model obtained can only detect these three categories, and the first two categories cannot be detected.

Only by adding the datasets of the first two categories to the new dataset of the three categories, can the model trained on this dataset with five categories be able to detect the five categories.

Is there any method to allow the new model to inherit the detection category of the previous training model without increasing the dataset?

**Comment by GT1984901175** [comment]
Hi @glenn-jocher ,

Sorry to bother you again.

I saw in your article on image classification that the input size to the model is 224. 
![微信截图_20240112105859](https://github.com/ultralytics/ultralytics/assets/150104416/362dcd91-61a3-45f3-ae24-551055b5b1de)

Will setting imgsz=224 during training for the image below yield the best classification model?
The width of the following image is 640 and the height is 480.

![1_Gaussian-bg](https://github.com/ultralytics/ultralytics/assets/150104416/6e8147c3-f6b6-4158-9ab0-fb92164d1a99)

Or do I choose imgsz=640 to get a better classification model than imgsz=224?

**Comment by glenn-jocher** [comment]
Hi @GT1984901175,

The optimal input size for your classification model can depend on various factors, including the complexity of the images and the level of detail required for accurate classification. While 224x224 is a common size for many classification tasks, it may not be the best choice for all datasets.

If your images have a lot of detail that is important for classification, a larger input size like 640x480 could potentially yield better results as it retains more information. However, larger input sizes also require more computational resources and can lead to longer training times.

It's often a good practice to experiment with different input sizes to find the best compromise between model accuracy and computational efficiency for your specific use case.

**Comment by GT1984901175** [comment]
@glenn-jocher ，
Thank you for all your answers

**Comment by glenn-jocher** [comment]
@GT1984901175 you're welcome! If you have any more questions, feel free to ask. Happy to help! 😊

**Comment by GT1984901175** [comment]
@glenn-jocher Hi,
I want to modify the save location of the trained model, so I added "save_dir='runs/classify/A '" to the training parameter list
![001](https://github.com/ultralytics/ultralytics/assets/150104416/c8352b7a-20aa-47b1-868f-064c650a10ae)

But after the training is completed, the save location of the model is still the original default save location
![002](https://github.com/ultralytics/ultralytics/assets/150104416/3d7060b9-0842-47b2-bf63-f891e24e8f05)

Is there any way to modify the save location of the trained model?

**Comment by glenn-jocher** [comment]
@GT1984901175 Hi,

To modify the save location of the trained model, you should use the `--project` and `--name` flags when running your training command. The `--project` flag specifies the directory where your runs will be saved, and the `--name` flag provides a subdirectory within that project for the specific run. The combination of these two will determine the final save directory for your model.

**Comment by GT1984901175** [comment]
@glenn-jocher ，
I have successfully modified it. Thank you for your answer！

**Comment by glenn-jocher** [comment]
@GT1984901175 Great to hear that! If you need further assistance, feel free to reach out. Happy training! 🚀

**Comment by mvijay2** [comment]
model_1 = YOLO("yolov8m.pt")
model_1 = YOLO("yolov8n.pt")
model_0=model, model_1.train(data=os.path.join(root,'/content/drive/MyDrive/data250.yaml'), epochs=10, patience = 3,batch=8)

* This technique is working, but I don't know whether it is ensemble or transfer learning technique.

**Comment by glenn-jocher** [comment]
@mvijay2 this technique appears to be an instance of transfer learning, where `model_1` is initialized with the weights from "yolov8n.pt" and then further trained on a new dataset. Model ensembling, on the other hand, would involve combining the predictions from both `model_0` and `model_1` during inference, which is not shown in your code snippet.

**Comment by mvijay2** [comment]
Thank you for clarifying that for me.

**Comment by Prem948** [comment]
> @glenn-jocher, hi there,
> 
> Model ensembling is not currently supported in the classify task for YOLOv8. You would need to implement custom logic to ensemble the classification outputs from multiple models.

Can you provide me some reference code for manual load and combine predictions?

**Comment by glenn-jocher** [comment]
@Prem948 hi there! 👋

Sure, here's a simple example of how you might manually load two models and combine their predictions for classification:

```python
from ultralytics import YOLO
import torch

# Load your models
model_1 = YOLO('path/to/first/model.pt')
model_2 = YOLO('path/to/second/model.pt')

# Get predictions for an image
img = 'path/to/your/image.jpg'
preds_1 = model_1.predict(img)
preds_2 = model_2.predict(img)

# Combine predictions by averaging
combined_preds = (preds_1.probs + preds_2.probs) / 2

# If you want to use the class with the highest average score
final_pred = torch.argmax(combined_preds, dim=1)
```

This code averages the probabilities from two models. Depending on your specific needs, you might want to combine the predictions differently, such as voting or weighted averaging. Hope this helps! 😊

**Comment by mvijay2** [comment]
what if we have an imbalance in classes

**Comment by glenn-jocher** [comment]
@mvijay2 hi there! 👋

For handling class imbalance in YOLOv8, you might consider using the `--img-weights` training argument. This option dynamically adjusts the loss to focus more on underrepresented classes. Here's how you can use it:

```bash
yolo train --data your_dataset.yaml --img-weights
```

This should help the model pay more attention to less frequent classes. Hope this helps! Let us know if you have any more questions. 😊

**Comment by mvijay2** [comment]
It is showing that weights is not defined

**Comment by glenn-jocher** [comment]
Hey @mvijay2! 😊 It looks like there might have been a slight misunderstanding. The `--img-weights` option is automatically handled by the YOLOv8 training process to dynamically adjust for class imbalance. You don't need to define `weights` yourself; just ensure you're using the latest version of YOLOv8 and include `--img-weights` in your training command like so:

```bash
yolo train --data your_dataset.yaml --img-weights
```

This command will take care of the class imbalance for you. If you're encountering any specific errors, could you please share the exact command or code snippet you're using? That way, we can help you more effectively!

**Comment by GT1984901175** [comment]
@glenn-jocher Hi，
I am using a classification task to train these two images. These two images are in the same folder, but the sizes of the two images are different. One is 500 x 500, and the other is 564 x 500.
![微信截图_20240229162229](https://github.com/ultralytics/ultralytics/assets/150104416/805069b9-b607-42e4-917c-48cfcf442357)

The following problem occurred after training.
![微信截图_20240229161857](https://github.com/ultralytics/ultralytics/assets/150104416/7f9b9773-9460-4bbf-bb7b-cf25663e6f5b)

What is the reason for this problem?

How to solve this problem?

**Comment by glenn-jocher** [comment]
@GT1984901175 hey there! 😊 It looks like the issue might be related to the different image sizes in your dataset. YOLOv8 expects all training images to have the same dimensions. You can solve this by resizing your images to a common size before training. Here's a quick example on how you could resize images using Python's PIL library:

```python
from PIL import Image

def resize_image(input_path, output_path, size=(500, 500)):
    img = Image.open(input_path)
    img = img.resize(size, Image.ANTIALIAS)
    img.save(output_path)

# Example usage
resize_image('path/to/your/image.jpg', 'path/to/resized/image.jpg')
```

Make sure all images are resized to the same dimensions, and this should help resolve the issue. Let us know how it goes!

**Comment by GT1984901175** [comment]
@glenn-jocher Hi, 
When I unified two images of different sizes into the same size according to your method, I successfully trained them.

But when I put these two images of different sizes in different folders for training,
![微信截图_20240301095609](https://github.com/ultralytics/ultralytics/assets/150104416/45ce24c2-2d6b-49df-8bb4-d3ea80bfb82f)
The following problem has occurred.
![微信截图_20240301101004](https://github.com/ultralytics/ultralytics/assets/150104416/9b3324e7-18bd-484e-8811-89bdcf7a4175)
Is the reason for this problem the same as before? It's because there's no unified size. Or is there an issue with the size of images like 564 x 500?

**Comment by glenn-jocher** [comment]
@GT1984901175 hey there! 😊

Great to hear you successfully trained your images after resizing them! Regarding the new issue, it's likely not due to the images being in different folders but could still relate to how the dataset is processed or the image sizes.

YOLOv8 can handle images of different sizes during training by dynamically resizing them. However, ensure your dataset configuration (`*.yaml`) correctly points to the folders and that all images are accessible. If the problem persists, double-check the dataset paths in your YAML file and ensure there's no issue with image formats or corrupt files.

If everything seems correct and the issue remains, consider resizing all images to a common dimension as a troubleshooting step. This approach often helps isolate the problem. If you need further assistance, feel free to share more details!

**Comment by GT1984901175** [comment]
@glenn-jocher Hi,
Thank you for your answer.

Now I have a new question. I can only see the time spent during the training process, and I don't know how much time is left during the training.
![微信截图_20240304145953](https://github.com/ultralytics/ultralytics/assets/150104416/ad2b3306-4289-471c-95fc-1c172381a058)

Is there any way for me to calculate how much time is left for training?

**Comment by glenn-jocher** [comment]
@GT1984901175 hey there! 😊

Absolutely, you can estimate the remaining training time by calculating the average time per epoch and then multiplying it by the number of epochs left. Here's a quick example:

```python
# Assuming you know these values
total_epochs = 100  # Total number of epochs you plan to train
completed_epochs = 20  # Number of epochs completed so far
time_elapsed = 1200  # Time elapsed in seconds for the completed epochs

# Calculate average time per epoch
avg_time_per_epoch = time_elapsed / completed_epochs

# Calculate remaining epochs
remaining_epochs = total_epochs - completed_epochs

# Estimate remaining time
estimated_time_remaining = avg_time_per_epoch * remaining_epochs

# Convert seconds to a more readable format (hours, minutes)
hours, remainder = divmod(estimated_time_remaining, 3600)
minutes, seconds = divmod(remainder, 60)

print(f"Estimated Time Remaining: {int(hours)}h {int(minutes)}m {int(seconds)}s")
```

This should give you a rough estimate of the remaining training time. Keep in mind, the actual time may vary slightly due to various factors. Happy training! 🚀

**Comment by GT1984901175** [comment]
@glenn-jocher Hi,
Thank you again for your answer.
I have another question.
What are the image formats that the YOLOv8 model can support for detection? Can common image formats such as BMP, jpg, png, tif, gif, pcx, tga, exif, fpx, svg, psd, cdr, pcd, dxf, ufo, eps, ai, raw, WMF, webp, avif, apng be used for detection?

**Comment by glenn-jocher** [comment]
Hi @GT1984901175! 😊

YOLOv8 primarily supports the most common image formats for detection, including JPG, PNG, BMP, and TIF. While it can handle a wide range of formats, not all the ones you listed may be directly supported, especially more specialized formats like PSD, CDR, DXF, or proprietary RAW formats.

For best compatibility, I recommend converting images to JPG or PNG before detection. This ensures smooth processing and compatibility across different environments. If you're working with a specific format not directly supported, consider using a library like PIL (Python Imaging Library) for conversion:

```python
from PIL import Image

image = Image.open('path/to/your/image.any_format')
image.save('path/to/your/image_converted.jpg', 'JPEG')
```

This way, you can easily convert images to a YOLOv8-friendly format. Happy detecting! 🚀

**Comment by GT1984901175** [comment]
@glenn-jocher Hi,
Thank you for your help
In the image classification task, I trained a model using the following training parameters.
![微信截图_20240306182409](https://github.com/ultralytics/ultralytics/assets/150104416/7f5e9557-b4ba-4b55-a972-e4b92f0f0ab2)
The following image '1. jpg' is being detected using this model. The objects in this' 1. jpg 'image have not been trained, while this' 2. jpg' image has been trained. The objects in '2. jpg' are called 'fried shrimp'. When using the trained model to detect '1. jpg', the result shows' fried shrimp 'with a high confidence level of 0.9. But the result I want is that when detecting '1. jpg', the result should show a very low confidence 'fried shrimp', rather than reaching a high confidence value of 0.9
![微信截图_20240306182518](https://github.com/ultralytics/ultralytics/assets/150104416/fb41e3dc-5497-4f64-99e9-5769a72b3e2e)
There are 202 images in the training dataset and 50 images in the validation dataset for the object 'fried shrimp'.
Can we achieve this goal by adjusting the parameters during training?
Or achieve my desired goals through other means.

**Comment by glenn-jocher** [comment]
Hi @GT1984901175! 😊

It sounds like your model might be overfitting to the "fried shrimp" class, especially if it's showing high confidence for unrelated images. Here are a couple of suggestions to improve your model's performance:

1. **Data Augmentation**: Increase the diversity of your training data through augmentation. This can help the model generalize better to unseen images.

2. **Class Balancing**: If your dataset is imbalanced, consider using techniques to balance it, such as oversampling underrepresented classes or adjusting class weights during training.

3. **Review Dataset**: Double-check your training and validation datasets to ensure they're correctly labeled and representative of the problem space.

4. **Regularization**: Employ regularization techniques like dropout or weight decay to prevent overfitting.

5. **Model Complexity**: If your model is too complex for the amount of data, consider using a simpler model or reducing the model's capacity.

6. **Threshold Adjustment**: Post-training, you can adjust the confidence threshold for detection. While this won't change the model's training, it allows you to filter out lower-confidence detections during inference.

Here's a quick example of how you might adjust the confidence threshold during inference:

```python
from ultralytics import YOLO

# Load your trained model
model = YOLO('path/to/your/model.pt')

# Set a lower confidence threshold for detection
results = model.predict('1.jpg', conf=0.3)  # Adjust conf value as needed

# Process and display results...
```

Adjusting training parameters and employing some of the strategies above should help you achieve better results. Keep experimenting! 🚀

**Comment by GT1984901175** [comment]
@glenn-jocher Hi,
Thank you again for your help.
Now I have a question. After each training session, there will always be two models, 'best. pt' and 'last. pt', but all I need is the 'best. pt' model file. Is there any way for me to not generate a 'last. pt' file after training?

**Comment by glenn-jocher** [comment]
Hi @GT1984901175! 😊

Currently, YOLOv8 saves both `best.pt` and `last.pt` by design to offer flexibility in choosing between the best performing model and the final epoch model. If you're looking to only keep `best.pt`, there isn't a direct flag to disable `last.pt` generation. However, you could easily remove `last.pt` after training with a simple command if you're on a Unix-like system:

```bash
rm path/to/your/last.pt
```

Or, if you're using Python, you could add a line to your training script:

```python
import os
os.remove("path/to/your/last.pt")
```

Just ensure this is done after the training process completes. Hope this helps! 🚀

**Comment by GT1984901175** [comment]
@glenn-jocher Hi,
In the image classification task, I only have one object to train.
![微信截图_20240309104100](https://github.com/ultralytics/ultralytics/assets/150104416/7831eac0-7820-4ecf-9947-023c6d6dce74)
After training, use this trained model for detection. The result is that no matter what image I use for detection, it will return a 'carrot rabbit' with a confidence value of 1.0
What is the reason for this? Can't image classification tasks train individual objects?

**Comment by glenn-jocher** [comment]
@GT1984901175 hi there! 😊

It sounds like your model might be overfitting to the "carrot rabbit" class, especially if it's showing a confidence of 1.0 for all images. This can happen in image classification tasks with very limited diversity in the training data.

For a single-object classification task, ensure your dataset includes a variety of backgrounds and conditions for the object. Also, include negative examples (images without the object) to teach the model what *not* to classify as the object.

Here's a quick tip: augment your dataset with more varied images and possibly use a more balanced dataset that includes both positive and negative examples. This should help your model learn better and generalize to new images more effectively.

Hope this helps! Keep experimenting! 🚀

**Comment by GT1984901175** [comment]
@glenn-jocher Hi,
How to add negative samples in the dataset of image classification?
For example, I now have a dataset with three categories: cats, cows, and dogs. I want to add some negative samples to these three categories. Where should I add these negative samples?
![微信截图_20240311144749](https://github.com/ultralytics/ultralytics/assets/150104416/27c84890-2744-4bd2-a323-ec3fd70aa816)

Is it necessary to directly add images without target objects to the folder corresponding to the category?

**Comment by glenn-jocher** [comment]
@GT1984901175 hi there! 😊

For adding negative samples to your dataset, you don't need to place them in the folders of existing categories. Instead, create a new category, often named something like "None" or "Background," and place your negative samples there. This way, your model learns to distinguish between your objects of interest (cats, cows, dogs) and images that don't contain those objects.

Here's a quick example structure:

```
/dataset
    /cats
        cat1.jpg
        cat2.jpg
    /cows
        cow1.jpg
        cow2.jpg
    /dogs
        dog1.jpg
        dog2.jpg
    /none
        none1.jpg
        none2.jpg
```

In your labels, the "none" category would typically be assigned a specific class ID, just like your other categories. This approach helps improve the robustness of your model by teaching it what is *not* a cat, cow, or dog. 🚀

Hope this helps! Keep up the great work!

**Comment by BartuHacilar** [comment]
Hi @glenn-jocher  , I am trying to ensemble two YOLO-V8 models in detection task. Can you provide me some reference code for manual load and combine predictions for detection ?
Thanks for helping .

**Comment by glenn-jocher** [comment]
Hi @BartuHacilar, currently, YOLOv8 does not have built-in support for model ensembling. However, you can manually load two models and combine their predictions by averaging the bounding box coordinates and confidence scores. For more details, please refer to the [Ultralytics documentation](https://docs.ultralytics.com).

**Comment by glenn-jocher** [comment]
Hi,

To retain the previous categories without adding them to the new dataset, you'll need to use a technique like knowledge distillation or fine-tuning with a balanced dataset. Unfortunately, simply training on the new dataset won't retain the old categories.

**Comment by glenn-jocher** [comment]
@GT1984901175 hi,

To retain the ability to detect the original categories without adding them to the new dataset, consider using techniques like knowledge distillation or fine-tuning with a balanced dataset. However, typically, including all categories in the training dataset is necessary to maintain detection capabilities.

**Comment by glenn-jocher** [comment]
Hi,

To retain the previous categories without adding them to the new dataset, you'll need to use techniques like knowledge distillation or fine-tuning with a combined dataset. Unfortunately, simply training on a new dataset won't automatically preserve the old categories.

**Comment by glenn-jocher** [comment]
Hi @GT1984901175,

To retain the ability to classify the original categories without adding them to the new dataset, you would need to use techniques like knowledge distillation or incremental learning, which are not natively supported in the current YOLO framework.
