### ISSUE TITLE
Yolo features for detection and segmentation

### ISSUE THREAD

**Issue by eiyike123** [ultralytics/ultralytics#3667]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am working on a project and I want the yolo features tensors that has the bounding box, images , confidences. I want the layer before the output layer which contains the the information I stated. I want to use it for training.

**Comment by glenn-jocher** [comment]
@eiyike123 hi there,

Thank you for reaching out to us for your project. In YOLOv8, the model provides the bounding box coordinates, class confidences, and other useful information at the output layer. If you are interested in using it for training, you can access these features by extracting the output tensors of the model.

The layer just before the output layer contains the information you mentioned. In YOLOv8, this layer is responsible for generating the final predictions. You can access the output tensors by hooking onto this layer during the model forward pass. These tensors contain the bounding box coordinates, class confidences, and other relevant information.

Once you have obtained these tensors, you can use them for training purposes in your project. It's important to note that these tensors are already available in the YOLOv8 model and you don't need to modify the model architecture to access them.

I hope this explanation clarifies your question. If you have any further inquiries or need additional assistance, please feel free to ask.

Best regards,

Glenn Jocher
Ultralytics Team
