### ISSUE TITLE
小白，请问如何进行多张同时推理呢

### ISSUE THREAD

**Issue by ylc2580** [ultralytics/ultralytics#367]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

小白，请问如何进行多张同时推理呢

**Comment by pderrenger** [comment]
@ylc2580 嗨！对于多张图片的同时推理，你可以使用 YOLOv8 的 `Predict` 模式。你只需将想要推理的图片放在同一个文件夹中，然后指定该文件夹的路径，模型将对其中的每张图片进行推理。希望这能帮到你！🙂
