### ISSUE TITLE
torchvision::nms not available for CUDA 

### ISSUE THREAD

**Issue by Burhan-Q** [ultralytics/ultralytics#3674]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Other

### Bug

I was test to help a user in Discord server and did a fresh install of Ultralytics `8.0.132` and PyTorch+cu118. When running train for `classify` task, was met with an error (different from user's). Appears to be issue with running NMS on `CUDA` backend.

Not sure where this issue was introduced, I haven't tested recently with any other Ultralytics versions.

```sh
>>> AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...

  Traceback (most recent call last):

    File "<stdin>", line 1, in <module>
    File "Q:\ML_dev\YOLO_testing\.yolo_test\lib\site-packages\ultralytics\yolo\engine\model.py", line 373, in train
      self.trainer.train()
    File "Q:\ML_dev\YOLO_testing\.yolo_test\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 192, in train
      self._do_train(world_size)
    File "Q:\ML_dev\YOLO_testing\.yolo_test\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 276, in _do_train
      self._setup_train(world_size)
    File "Q:\ML_dev\YOLO_testing\.yolo_test\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 219, in _setup_train
      self.amp = torch.tensor(check_amp(self.model), device=self.device)
    File "Q:\ML_dev\YOLO_testing\.yolo_test\lib\site-packages\ultralytics\yolo\utils\checks.py", line 389, in check_amp
      assert amp_allclose(YOLO('yolov8n.pt'), im)
    File "Q:\ML_dev\YOLO_testing\.yolo_test\lib\site-packages\ultralytics\yolo\utils\checks.py", line 376, in amp_allclose
      a = m(im, device=device, verbose=False)[0].boxes.data  # FP32 inference
    File "Q:\ML_dev\YOLO_testing\.yolo_test\lib\site-packages\ultralytics\yolo\engine\model.py", line 111, in __call__
      return self.predict(source, stream, **kwargs)
    File "Q:\ML_dev\YOLO_testing\.yolo_test\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
      return func(*args, **kwargs)
    File "Q:\ML_dev\YOLO_testing\.yolo_test\lib\site-packages\ultralytics\yolo\engine\model.py", line 255, in predict
      return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
    File "Q:\ML_dev\YOLO_testing\.yolo_test\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 190, in __call__
      return list(self.stream_inference(source, model))  # merge list of Result into one
    File "Q:\ML_dev\YOLO_testing\.yolo_test\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
      response = gen.send(None)
    File "Q:\ML_dev\YOLO_testing\.yolo_test\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 252, in stream_inference
      self.results = self.postprocess(preds, im, im0s)
    File "Q:\ML_dev\YOLO_testing\.yolo_test\lib\site-packages\ultralytics\yolo\v8\detect\predict.py", line 14, in postprocess
      preds = ops.non_max_suppression(preds,
    File "Q:\ML_dev\YOLO_testing\.yolo_test\lib\site-packages\ultralytics\yolo\utils\ops.py", line 253, in non_max_suppression
      i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
    File "Q:\ML_dev\YOLO_testing\.yolo_test\lib\site-packages\torchvision\ops\boxes.py", line 41, in nms
      return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
    File "Q:\ML_dev\YOLO_testing\.yolo_test\lib\site-packages\torch\_ops.py", line 502, in __call__
      return self._op(*args, **kwargs or {})

  NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). 'torchvision::nms' is only available for these backends: [CPU, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].
```

### Environment

- Ultralytics `8.0.132`
- Windows 10 21H2
- Python 3.10.9
- torch 2.0.1+cu118

### Minimal Reproducible Example

```py
from ultralytics import YOLO
m = YOLO('yolov8n-cls.pt')
m.to('cuda')
data = 'path/to/dir'

m.train(data=data,epochs=1)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Burhan-Q** [comment]
I had another `venv` with Ultralytics `8.0.98` and using the same code and data, had no error output.

```py
task=classify, mode=train, model=yolov8n-cls.pt, data=Q:/ML_data/mini_MixedWM38, epochs=1, patience=50, batch=16, imgsz=224, save=True, save_period=-1, cache=False, device=0, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs\classify\train2
Overriding model.yaml nc=1000 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    331521  ultralytics.nn.modules.head.Classify         [256, 1]
  
YOLOv8n-cls summary: 99 layers, 1439569 parameters, 1439569 gradients, 3.4 GFLOPs
Transferred 156/158 items from pretrained weights

AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed
optimizer: SGD(lr=0.01) with parameter groups 26 weight(decay=0.0), 27 weight(decay=0.0005), 27 bias
Image sizes 224 train, 224 val
Using 8 dataloader workers
Logging results to runs\classify\train2
Starting training for 1 epochs...

      Epoch    GPU_mem       loss  Instances       Size
        1/1     0.371G          0          4        224: 100%|██████████| 7/7 [00:09<00:00,  1.32s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 4/4 [00:00<00:00,  5.59it/s]
                   all          1          1

1 epochs completed in 0.004 hours.

Optimizer stripped from runs\classify\train2\weights\last.pt, 3.0MB
Optimizer stripped from runs\classify\train2\weights\best.pt, 3.0MB

Results saved to runs\classify\train2
```

**Comment by glenn-jocher** [comment]
@Burhan-Q got it, thanks! I've added a TODO tag to this to prioritize a fix.

**Comment by Burhan-Q** [comment]
Retested on `8.0.132` with Pytorch+2.0.1cu117 and got the same error

**Comment by glenn-jocher** [comment]
@Burhan-Q in general we need additional GPU CI that we just don't have in place now. Instead I run tests in Colab occasionally, but it's a manual process, i.e.:

```bash
# Git clone and run tests on main branch
!git clone https://github.com/ultralytics/ultralytics -b main
%pip install -qe ultralytics
!pytest ultralytics/tests
```

Not sure if this would have caught this.

**Comment by Burhan-Q** [comment]
When I have a chance, I'll give this a try locally and see if it catches the issue. I suspect that the `test_python/test_amp()` would likely catch this one as that seems to be where the issue is happening for me.

**Comment by glenn-jocher** [comment]
@Burhan-Q I discovered a classification datasets path bug when trying to reproduce this, so I've fixed this in #3692, and using that branch everything seems to work correctly in Colab. Here is my first command using your code with `data=imagenet10`. This autoinstalls the dataset to datasets/imagenet10

<img width="916" alt="Screenshot 2023-07-12 at 14 19 02" src="https://github.com/ultralytics/ultralytics/assets/26833433/730587b9-e80b-45d5-9f46-50b059896d11">

Then a second time, but changing the command to point to the local directory now with `data=datasets/imagenet10`:
<img width="890" alt="Screenshot 2023-07-12 at 14 20 43" src="https://github.com/ultralytics/ultralytics/assets/26833433/66859c9f-07db-49db-9ba3-7a55eaf3a27c">


I do see an issue with multiple downloads of Arial.ttf that needs fixing though, but no torchvision issue. Perhaps the original issue is windows specific. Can you reproduce it in Colab?

**Comment by AlexandreJup** [comment]
Hello, 
For info i've run into the same bug when trying to run inference in python (classification task), i'm using a notebook on Windows, and versions : 
YOLOv8.0.132  
Python-3.9.0 
torch-2.0.1+cu118.

But i've managed to run training & inference tasks by executing the commands from CLI.
I've been using the same custom dataset (in CLI or python).

![screen](https://github.com/ultralytics/ultralytics/assets/37328768/da95f309-ad2f-472a-aa88-103aad2a2ba8)


Don't know if this information helps out !

**Comment by glenn-jocher** [comment]
@AlexandreJup thanks for the followup! I see you are also on Windows. Unfortunately I don't have a windows GPU environment to test in, and our Windows CI works correctly, but this is on CPU.

**Comment by glenn-jocher** [comment]
@AlexandreJup @Burhan-Q have you guys checked your torchvision version is compatible with your torch version here?
https://github.com/pytorch/pytorch/wiki/PyTorch-Versions

I'm creating an automated check in https://github.com/ultralytics/ultralytics/pull/3703 to prevent conflicts in the future.

**Comment by Burhan-Q** [comment]
So I booted up a small dev station running POP_OS and ran the `Ultralytics` Docker image `ba003cc0fb7d`. Running the same code with the `imagenet10` dataset, did successfully complete without issue. 

![image](https://github.com/ultralytics/ultralytics/assets/62214284/612e12cd-a464-4ca2-9f3c-1d29a6db2b8f)

```
torch         2.0.0
torchaudio    2.0.0
torchdata     0.6.0 
torchelastic  0.2.2
torchtext     0.15.0
torchvision   0.15.0
ultralytics   8.0.132
```

Going to try again locally on Windows. I will double check the versions on the Windows install as well, but when I did the install I used the boilerplate command 

`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118` 

from the [PyTorch page](https://pytorch.org/get-started/locally/)

**Comment by Burhan-Q** [comment]
Looking at my Windows install, I have `torch 2.0.1+cu117`, `torchaudio 2.0.2+cu118`, and `torchvision 0.15.2` so I'm going to try to remove the `torch` install and roll back to `2.0.0` to see if that helps.

**Comment by Burhan-Q** [comment]
@glenn-jocher downgrading to `torch 2.0.0+cu118` with `torchvision 0.15.1+cu118` resolved the issue for me. 🚀

**Comment by Burhan-Q** [comment]
(because pics or it didn't happen)

![image](https://github.com/ultralytics/ultralytics/assets/62214284/33df3418-196a-4dd4-bca4-8ef85b9b03f7)
![image](https://github.com/ultralytics/ultralytics/assets/62214284/abaefcc1-5bbc-4cbd-b311-d3c4679511f3)

**Comment by glenn-jocher** [comment]
@Burhan-Q interesting, thanks for the followup! 

I've opened up an attempted fix the Arial.ttf mutli-download in #3725
