### ISSUE TITLE
Numerical values of precision-confidence curve

### ISSUE THREAD

**Issue by khodabakhshih** [ultralytics/ultralytics#3675]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi
Thanks for your great work. As you know after training, there are plots such as ‘precision-confidence’, ‘recall-confidence’ curves. I want to plot these figures in Matlab to report in the paper. 
Is there any way to have the corresponding numerical vectors (horizontal and vertical) according to these plots?
Best wishes
Hossein

**Comment by glenn-jocher** [comment]
@khodabakhshih hi Hossein,

Thank you for your kind words and for using YOLOv8! I'm glad to hear that you find our work valuable. 

To obtain the corresponding numerical values of the precision-confidence and recall-confidence curves after training, you can use the `Val` mode in YOLOv8. By running the validation mode (`python3 train.py --data coco.yaml --cfg yolov8.yaml --weights yolov8.pt --img-size 640 --task val`), you will have access to the metrics and their numerical values.

In the output log, you will see information about the Precision and Recall values at different Confidence thresholds. You can extract these values and use them to create your own plots in Matlab or any other plotting software of your choice.

I hope this helps! If you have any further questions, please feel free to ask.

Best regards,
Glenn Jocher

**Comment by khodabakhshih** [comment]
@glenn-jocher 
Hi Jocher
Thank you very much for your insightful response. I use ‘google colab’ and I installed YOLOv8 using pip. Hence, I ran the following commands to see the output log:

metrics = model.val(data='/content/drive/MyDrive/YOLO/datasets/Image55_autO.v1i.yolov8/data.yaml',conf=0.001)

Then, in ‘google colab’ I went to the menu ‘runtime/view_runtime_log’. The screenshot of it has been attached.




![log](https://github.com/ultralytics/ultralytics/assets/50246960/1264e5cd-9443-441b-8472-23c5515f84aa)




 As can be seen, I have not access to numerical values of precision-confidence curve.
Would you please tell me if you have any solution for this situation?
Thanks in advance
Best wishes Hossein

**Comment by glenn-jocher** [comment]
@khodabakhshih hi Hossein,

Thank you for your message and for providing the information. I apologize for any confusion caused. 

In order to obtain the numerical values of the precision-confidence curve, you can access the metrics directly from the returned `metrics` object. The `val` method in YOLOv8 returns a dictionary object containing various metrics such as precision, recall, and AP (Average Precision). You can extract the precision and confidence values from this dictionary to create your precision-confidence curve.

To access the precision values, you can use `metrics['precision']`. Similarly, the confidence values can be obtained using `metrics['confidence']`. These arrays will contain the corresponding numerical values for the precision-confidence curve.

I hope this helps! If you have any further questions or need additional assistance, please let me know.

Best regards,
Glenn Jocher

**Comment by khodabakhshih** [comment]
@glenn-jocher 
**Hi Glenn**
**Hope everything is going well with you. Thanks for your time and your great comments. I am using YOLOV8 version ‘8.0.103’ released on 16th of May.  I tried the ‘metrics’ object and here are the results:**
**print(metrics['precision'])**

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-8-e3ce4bb28a1e>](https://localhost:8080/) in <cell line: 1>()
----> 1 metrics['precision']

TypeError: 'SegmentMetrics' object is not subscriptable


 **and here is the result of printing metrics’s contents:**
**print(metrics)**
ultralytics.yolo.utils.metrics.SegmentMetrics object with attributes:

ap_class_index: array([0])
box: ultralytics.yolo.utils.metrics.Metric object
confusion_matrix: <ultralytics.yolo.utils.metrics.ConfusionMatrix object at 0x7b60a205a4a0>
fitness: 1.1146493390762733
keys: ['metrics/precision(B)', 'metrics/recall(B)', 'metrics/mAP50(B)', 'metrics/mAP50-95(B)', 'metrics/precision(M)', 'metrics/recall(M)', 'metrics/mAP50(M)', 'metrics/mAP50-95(M)']
maps: array([     1.0488])
names: {0: 'olive'}
plot: True
results_dict: {'metrics/precision(B)': 0.827296668994252, 'metrics/recall(B)': 0.7513089005235603, 'metrics/mAP50(B)': 0.8614287892595583, 'metrics/mAP50-95(B)': 0.553074687384867, 'metrics/precision(M)': 0.828717285317533, 'metrics/recall(M)': 0.7346129259005937, 'metrics/mAP50(M)': 0.8456753283724117, 'metrics/mAP50-95(M)': 0.4957463429629955, 'fitness': 1.1146493390762733}
save_dir: PosixPath('runs/segment/val4')
seg: ultralytics.yolo.utils.metrics.Metric object
speed: {'preprocess': 0.8436333049427379, 'inference': 340.47646956010294, 'loss': 0.0017556277188387783, 'postprocess': 4.740628329190341}

**As you can see, I have not access to the numerical values of precision-confidence curve. Any idea about this issue will be greatly appreciated.
Best regards
Hossein**

**Comment by glenn-jocher** [comment]
@khodabakhshih hi Hossein,

Thank you for reaching out and providing the information. I apologize for any confusion caused.

To access the numerical values of the precision-confidence curve in YOLOv8, you can use the `SegmentMetrics` object returned by the `val` method. This object contains various attributes such as `results_dict` and `names` that provide relevant information.

The precision values can be obtained using `metrics.results_dict['metrics/precision(B)']` for the background class, and `metrics.results_dict['metrics/precision(M)']` for other classes. Similarly, the confidence values can be accessed using the `confidence` attribute in the `SegmentMetrics` object.

I hope this clarifies the process for accessing the numerical values of the precision-confidence curve in YOLOv8. If you have any further questions or need additional assistance, please let me know.

Best regards,
Glenn Jocher

**Comment by khodabakhshih** [comment]
@glenn-jocher **Many thanks for your responses. I am really confused. Here you said that:** 
metrics.results_dict['metrics/precision(B)'] for the background class, and metrics.results_dict['metrics/precision(M)'] for other classes. 

**and it seems that you have said different things here:**
https://github.com/ultralytics/yolov5/issues/11454
(M) refers to "macro" average, which calculates the average performance metric over each class. (B) refers to "best" performance metric achieved by the model during the training process. So for example, "mAP_0.5 (B)" would refer to the best mean average precision at an IoU threshold of 0.5 achieved by the model during training, while "mAP_0.5 (M)" would refer to the macro average mean average precision at an IoU threshold of 0.5 across all classes.

**would you please tell me which one is correct?**

**By the way, As you see above, metrics.results_dict['metrics/precision(B)'] returns only one scaler value and it does not return a vector of values corresponding to each confidence threshold. Would you please clarify this?
Best wishes 
Hossein**

**Comment by neelsen1994** [comment]
> @glenn-jocher **Many thanks for your responses. I am really confused. Here you said that:** metrics.results_dict['metrics/precision(B)'] for the background class, and metrics.results_dict['metrics/precision(M)'] for other classes.
> 
> **and it seems that you have said different things here:** [ultralytics/yolov5#11454](https://github.com/ultralytics/yolov5/issues/11454) (M) refers to "macro" average, which calculates the average performance metric over each class. (B) refers to "best" performance metric achieved by the model during the training process. So for example, "mAP_0.5 (B)" would refer to the best mean average precision at an IoU threshold of 0.5 achieved by the model during training, while "mAP_0.5 (M)" would refer to the macro average mean average precision at an IoU threshold of 0.5 across all classes.
> 
> **would you please tell me which one is correct?**
> 
> **By the way, As you see above, metrics.results_dict['metrics/precision(B)'] returns only one scaler value and it does not return a vector of values corresponding to each confidence threshold. Would you please clarify this? Best wishes Hossein**

Hi everyone,

Is the above issue resolved. I have the same problem. I want to access the raw values of Precision, Recall, and F1 score with respect to the confidence values and generate the 4 plots namely Precision-Confidence, Recall-Confidence, F1-Confidence and Precision-Recall curve. 

Thanks in advance,

Best wishes,
Neel

**Comment by glenn-jocher** [comment]
Hi Hossein and Neel,

Thank you for your questions. To clarify, (M) refers to the macro average across all classes, while (B) refers to the best performance metric achieved during training. Unfortunately, the current implementation returns scalar values for these metrics. For detailed precision-confidence values, you might need to modify the source code to log these metrics at different confidence thresholds.
