### ISSUE TITLE
“from ultralytics import YOLO” cause core dumped

### ISSUE THREAD

**Issue by xiaoyuerCV** [ultralytics/ultralytics#368]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

On my computer, "from ultralytics import YOLO" caused core dumped:
```shell
$ python
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ultralytics import YOLO
Segmentation fault (core dumped)
```

### Environment

- ubuntu 20.04
- cuda 11.0
- python 3.8
- torch    1.7.1+cu110                  
- torchvision   0.8.2+cu110

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
This problem isn't reproducible for me. Who marked that you'd like to submit a PR to fix this? Please start a PR and we'll try to fix this issue

**Comment by xiaoyuerCV** [comment]
I use gdb to debug coredump file, and finally find it was caused by Pillow package. There are two version Pillow on my computer, one is Pillow 8.2.0 and the other is 7.0.0. I uninstall 8.2.0 and now yolo command works. Thanks @AyushExel
