### ISSUE TITLE
Getting an Error while trying to get detections from yolov8 model using supervision model

### ISSUE THREAD

**Issue by Justin-king-de** [ultralytics/ultralytics#3683]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi @glenn-jocher @plashchynski @diramazioni I am trying to get detections from yolov-8 model using supervision library. However I am getting the following error. I have attached the code to reproduce that error. Your help would be appreciated!

```
OpenCV: FFMPEG: tag 0x58564944/'DIVX' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'

0: 384x640 1 person, 86.9ms
Speed: 12.6ms preprocess, 86.9ms inference, 8.9ms postprocess per image at shape (1, 3, 384, 640)
Detections(xyxy=array([[     272.85,      72.183,        1280,         720]], dtype=float32), mask=None, confidence=array([    0.87802], dtype=float32), class_id=array([1]), tracker_id=None)
{0: 'face', 1: 'person'}
Traceback (most recent call last):
  File "/Users/test_model_results/predict.py", line 63, in <module>
    main()
  File "/Users/test_model_results/predict.py", line 38, in main
    labels = [
  File "/Users/test_model_results/predict.py", line 40, in <listcomp>
    for _, confidence, class_id, _
ValueError: too many values to unpack (expected 4)
```

Code to reproduce that error:

```
import cv2
import supervision as sv
from ultralytics import YOLO

def main():
    
    # save the video
    writer= cv2.VideoWriter('webcam_yolo.mp4', 
                            cv2.VideoWriter_fourcc(*'DIVX'), 
                            7, 
                            (1280, 720))
    
    # define resolution
    cap = cv2.VideoCapture(0)
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

    # specify the model
    model = YOLO("best.pt")

    # customize the bounding box
    box_annotator = sv.BoxAnnotator(
        thickness=2,
        text_thickness=2,
        text_scale=1
    )
    while True:
        ret, frame = cap.read()
        result = model(frame, agnostic_nms=True)[0]
        #print(result)
        detections = sv.Detections.from_yolov8(result)
        print(detections)
        print(model.model.names)
        
        labels = [
            f"{model.model.names[class_id]} {confidence:0.2f}"
            for _, confidence, class_id, _
            in detections
        ]
        break
        #labels=['face','person']
        frame = box_annotator.annotate(
            scene=frame, 
            detections=detections, 
            labels=labels
        ) 
        
        writer.write(frame)
        
        cv2.imshow("yolov8", frame)

        if (cv2.waitKey(30) == 27): # break with escape key
            break
            
    cap.release()
    writer.release()
    cv2.destroyAllWindows()
    
if __name__ == "__main__":
    main()
```

**Comment by glenn-jocher** [comment]
@Justin-king-de hi there!

It seems like you're encountering an error when trying to get detections from the YOLOv8 model using the supervision library. The error message you're seeing indicates that there are too many values to unpack, specifically in the line `labels = [f"{model.model.names[class_id]} {confidence:0.2f}" for _, confidence, class_id, _ in detections]`.

To resolve this issue, you will need to make sure that the `detections` variable is in the correct format. It should be a list of tuples with four elements: `(box_coordinates, confidence, class_id, additional_info)`. Please ensure that `detections` is structured in this way before attempting to unpack its elements in the list comprehension.

If you're still encountering issues, please provide additional information such as the version numbers of the libraries you're using and any relevant dataset samples. This will help us further troubleshoot the problem.

Hope this helps! Let us know if you have any further questions.

**Comment by Justin-king-de** [comment]
@glenn-jocher Firstly, thanks for your quick reply. 

I looked at the detections variable and its basically a list of tuples with 5 elements namely `box_coordinates, mask, confidence, class_id, tracker_id`. So as you said, I tried to remove one tuple from detections list to make it a list with 4 tuples. But when I try to remove it, I get an error saying `TypeError: 'Detections' object doesn't support item deletion`. Then I tried to make a copy of detections to work on the copy and check the output. But on trying that I get  `AttributeError: 'Detections' object has no attribute 'copy'` I am a bit stuck about how to restructure the Detections variable.

So could you please help me out in restructuring this variable may be with what function or module to use to do with some lines of code. My python version is` 3.9 `and supervision version is `0.11.1`. I installed utltralytics using pip.


Thanks in advance!

**Comment by diramazioni** [comment]
detections are populated on the line `detections = sv.Detections.from_yolov8(result)`  and `len(detections)` is 5, so it expect to be unpacked as 5 different variables or a tuple with 5 values, following your example:
`labels = [ f"{model.model.names[class_id]} confidence:{confidence}" for _, _, confidence, class_id,  _ in detections ]`
(I haven't tested the code)

**Comment by Justin-king-de** [comment]
@diramazioni  Its working now. I tried this thing yesterday and for some weird reason, it was not working. But today, it is working. Anyways, thanks again for your help.

**Comment by glenn-jocher** [comment]
@diramazioni I'm glad to hear that it's working now! Sometimes, these things can be a bit unpredictable. If you encounter any further issues or have any more questions, feel free to reach out again. Happy coding!

**Comment by balajik27** [comment]
> 

yes its working fine, Thanks @diramazioni , and i have another doubt , why the detection is slow , is this the problem of my system or the problem in yolov8, i'll share u the output , see the ms how long it take

0: 384x640 1 person, 2825.0ms
Speed: 47.9ms preprocess, 2825.0ms inference, 9.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 1 bed, 2352.7ms
Speed: 8.5ms preprocess, 2352.7ms inference, 11.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 2323.9ms
Speed: 4.9ms preprocess, 2323.9ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 2298.0ms
Speed: 15.1ms preprocess, 2298.0ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 2856.3ms
Speed: 101.3ms preprocess, 2856.3ms inference, 4.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 person, 2513.6ms
Speed: 41.0ms preprocess, 2513.6ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

can u tell me how to get fast detection (during the detection in web cam it gets lag becomes stuck , the video is not smooth and detection also not smooth)

**Comment by glenn-jocher** [comment]
@balajik27 hello! Thank you for reaching out with your question. The speed of the detection in YOLOv8 can be influenced by a few factors. Here are a few things to consider:

1. Hardware: The performance of the detection can depend on the capabilities of your system, including your CPU and GPU. Having a more powerful system can lead to faster detection times.

2. Batch size: Increasing the batch size during inference can often lead to faster detection. This allows the model to process multiple images simultaneously, leveraging parallelism and optimizing GPU usage.

3. Model optimization: There are techniques such as model quantization or model pruning that can be applied to reduce the model size and improve inference speed. However, these techniques might slightly impact the accuracy of the detections.

4. GPU acceleration: Ensure that your system is properly configured to leverage GPU acceleration during inference. This can significantly speed up the detection process.

Please keep in mind that the detection speed can also be influenced by the complexity and size of the images or videos being processed. Larger images or higher-resolution videos will naturally take more time to process.

I hope these suggestions help you optimize the detection speed in YOLOv8. Let us know if you have any further questions or need additional assistance.

**Comment by aniketkanse** [comment]
Hi @glenn-jocher @plashchynski @diramazioni I am trying to do something similar but using webcam. However I am getting the following error. I have attached the code to reproduce that error. Your help would be appreciated!

0: 384x640 (no detections), 28.2ms
Speed: 6.7ms preprocess, 28.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)
Traceback (most recent call last):

  File "C:\Users\Downloads\main.py", line 91, in <module>
    main()

  File "C:\Users\Downloads\main.py", line 60, in main
    detections = sv.Detections.from_yolov8(result)

AttributeError: type object 'Detections' has no attribute 'from_yolov8'

Code to reproduce that error:
`import cv2
import argparse

from ultralytics import YOLO
import supervision as sv
import numpy as np


ZONE_POLYGON = np.array([
    [0, 0],
    [0.5, 0],
    [0.5, 1],
    [0, 1]
])



def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="YOLOv8 live")
    parser.add_argument(
        "--webcam-resolution", 
        default=[1280, 720], 
        nargs=2, 
        type=int
    )
    args = parser.parse_args()
    return args


def main():
    args = parse_arguments()
    frame_width, frame_height = args.webcam_resolution

    cap = cv2.VideoCapture(0)
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, frame_width)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, frame_height)

    model = YOLO("best.pt")

    box_annotator = sv.BoxAnnotator(
        thickness=2,
        text_thickness=2,
        text_scale=1
    )

    zone_polygon = (ZONE_POLYGON * np.array(args.webcam_resolution)).astype(int)
    zone = sv.PolygonZone(polygon=zone_polygon, frame_resolution_wh=tuple(args.webcam_resolution))
    zone_annotator = sv.PolygonZoneAnnotator(
        zone=zone, 
        color=sv.Color.red(),
        thickness=2,
        text_thickness=4,
        text_scale=2
    )

    while True:
        ret, frame = cap.read()
        result = model(frame, agnostic_nms=True)[0]
        #print(result)
        detections = sv.Detections.from_yolov8(result)
        print(detections)
        print(model.model.names)
        
        labels = [
            f"{model.model.names[class_id]} {confidence:0.2f}"
            for _, confidence, class_id, _
            in detections
        ]
        break
        #labels=['face','person']
        frame = box_annotator.annotate(
            scene=frame, 
            detections=detections, 
            labels=labels
        ) 
        
        writer.write(frame)
        
        cv2.imshow("yolov8", frame)

        if (cv2.waitKey(30) == 27): # break with escape key
            break
            
    cap.release()
    writer.release()
    cv2.destroyAllWindows()
    


if __name__ == "__main__":
    main()
    
    
`

**Comment by glenn-jocher** [comment]
@aniketkanse hello there!

The error message you're encountering, `AttributeError: type object 'Detections' has no attribute 'from_yolov8'`, indicates that the `supervision` library's `Detections` class does not have a method called `from_yolov8`. This could be because the library version you are using does not include such a method, or because the method has been defined in a different module or in a different way that is not recognized in your code.

Here are a few things to check and try:

1. **Check supervision library**: Verify that you are using the correct version of the `supervision` library that is expected to have the `from_yolov8` method implemented. Double-check the library documentation or release notes to see if the method is available in the version you are using.

2. **Update libraries**: If your current version of the `supervision` library does not have the method, consider updating it to the latest version. You might also need to ensure that your `ultralytics` package is up to date.

3. **Check the supervision documentation**: Look at the official documentation of the `supervision` library for the proper way to use the `Detections` class and initialization methods available.

As I don't have the ability to inspect or execute code, the suggestions above are your best steps to troubleshoot the problem. If after checking these items you still face the same issue, please consider reaching out to the maintainers of the `supervision` library for further support, or check any community forums or discussions related to this library for assistance.

I hope this points you in the right direction to resolve the error. If you have any issues related to YOLOv8 specifically, feel free to ask!

**Comment by Quelich** [comment]
> ###
> **[aniketkanse](/aniketkanse) ** commented [Nov 14, 2023](#issuecomment-1809119551) •

You may want to try this:
` detections = sv.Detections.from_ultralytics(result)`

**Comment by glenn-jocher** [comment]
@Quelich, it seems like there might be a misunderstanding with the method name. If `from_yolov8` is not available, you could try using `from_ultralytics` instead, if that's a method provided by your version of the `supervision` library. Make sure to check the library's documentation for the correct usage. If the issue persists, consider reaching out to the library's support or community forums for more detailed assistance.

**Comment by yinweinidongle** [comment]
you can try this :

change your python3.11 to python3.10 ;
pip install ultralytics==8.0.230;
then it works!!!

**Comment by glenn-jocher** [comment]
@yinweinidongle thanks for sharing this solution! 😊 Switching to Python 3.10 and installing the specific version of `ultralytics` can indeed resolve compatibility issues for some users. Here's a quick recap for anyone who might need it:

```bash
# Switch to Python 3.10
# Install the specified ultralytics version
pip install ultralytics==8.0.230
```

Appreciate your input! 🌟

**Comment by ErfanRoshan** [comment]
you shoild use this command to find label of object :
labels = [
    model.model.names[class_id]
    for class_id
    in detections.class_id
]

**Comment by glenn-jocher** [comment]
Thank you for sharing that solution! Using `model.model.names[class_id]` is a great way to retrieve object labels from detections.
