### ISSUE TITLE
Possible solution to avoid uninstalling `wandb` in `Ultralytics` notebooks

### ISSUE THREAD

**Issue by soumik12345** [ultralytics/ultralytics#3696]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Currently `wandb` is being uninstalled while using the `YOLO` CLI in notebooks ([reference](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/utils/checks.py#L334-L335)). Is it possible to avoid uninstalling `wandb` in `ultralytics` notebooks by turning off `wandb` by default and adding a flag to the `YOLO` CLI that turns on the `wandb` usage?

### Use case

Use Weights & Biases for experiment tracking with Ultralytics notebooks.

### Additional

References:
- https://github.com/ultralytics/ultralytics/issues/3659
- https://github.com/wandb/wandb/issues/5746

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@soumik12345 hi there! Thank you for reaching out and suggesting a solution to avoid uninstalling `wandb` in Ultralytics notebooks.

While uninstalling `wandb` is currently done by default when using the YOLO CLI in notebooks, it is indeed possible to make `wandb` usage optional and add a flag to the YOLO CLI that turns it on.

This is a great idea and can be helpful for users who want to use Weights & Biases for experiment tracking with Ultralytics notebooks.

If you're willing to contribute and submit a pull request (PR) for this feature, it would be highly appreciated! Our team values the contributions from the YOLO community and your effort would be a fantastic addition to the project.

Feel free to refer to the GitHub issue you mentioned for any further discussion or guidance. And thank you again for your suggestion!

Best regards,
Glenn Jocher, author and maintainer of the Ultralytics YOLOv8 repo

**Comment by soumik12345** [comment]
@glenn-jocher  Thanks for your response! I will start working on a PR for the same.

**Comment by glenn-jocher** [comment]
Hi @soumik12345! That's great to hear. Thank you for taking the initiative to work on a PR for making `wandb` usage optional in Ultralytics YOLOv8 notebooks. Your contribution is highly appreciated.

Please feel free to ask any questions or seek guidance during the process of creating the PR. Our team is here to support you and ensure a smooth integration of this new feature.

Once again, thank you for your willingness to help and for being an active member of the YOLOv8 community.

Best regards,
Glenn Jocher, author and maintainer of the Ultralytics YOLOv8 repo
