### ISSUE TITLE
Input size, resize and square

### ISSUE THREAD

**Issue by pie-leroy** [ultralytics/ultralytics#3697]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello and thank you for your work.

I have a use case where I want to use the smallest possible backbone for embedded applications. I'm currently using the following weights "yolov8n-cls.pt" and I've built a specific head.
The images I want to pass as input to the model are twice as high as they are wide. I want to work with very small resolutions (64 in width and 128 in height).

My question is as follows:
during the training phase, will the model resize the image: 
1) to a square? 
2) to a 224/224 resolution ?
How does the model manage to take rectangles as input? 

Thank you in advance,
Have a good day

**Comment by glenn-jocher** [comment]
@pie-leroy hi there,

Thank you for reaching out and for your interest in YOLOv8!

During the training phase, YOLOv8 does not require square or specific resolutions for the input images. The model can handle images of different shapes and aspect ratios, including rectangles. 

When you pass an image to the model for training or inference, YOLOv8 resizes the input image while maintaining its original aspect ratio. The resizing operation is performed to fit the image into the specified input size defined in the model configuration. In your case, if you set the input size to be 64x128, the model will resize the input image to fit this size while preserving the original aspect ratio.

So, to answer your questions directly:
1) The model does not require the input image to be square during training.
2) The model does not have a fixed resolution requirement like 224x224. Instead, it can handle images of different resolutions, including your specified dimensions of 64x128.

Feel free to let me know if you have any further questions. Have a great day!
