### ISSUE TITLE
how can stop detection with key when detection video is run?

### ISSUE THREAD

**Issue by kyoko9000** [ultralytics/ultralytics#370]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i run yolov8 to detect video.mp3 but i don't know how to stop it when it run with key?

**Comment by ichsan2895** [comment]
You run `yolo task=detect mode=predict source=video.mp4`  via terminal, right?
Just press `ctrl+shift+C` or `ctrl+C` in my computer to stop it.

**Comment by dmddmd** [comment]
And in Python (not CLI but SDK) ?

**Comment by dmddmd** [comment]
> And in Python (not CLI but SDK) ? without terminating the programm

I kindly want to ask again

**Comment by glenn-jocher** [comment]
@dmddmd just type CTRL+C to terminate any streaming source.
