### ISSUE TITLE
How exactly can I pull values of FN, FP, TP, TN values ?

### ISSUE THREAD

**Issue by elnaqieb** [ultralytics/ultralytics#3706]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How exactly can I pull values of FN, FP, TP, TN values after validation process?

**Comment by Burhan-Q** [comment]
> How exactly can I pull values of FN, FP, TP, TN values after validation process?

After validation completes you can get TP and FP using and use those to calculate the FN and TN:

```py
m = YOLO() # model
m.train(data='dataset.yaml')
m.trainer.validator.confusion_matrix.tp_fp() # tuple with TP and FP numpy arrays
m.trainer.validator.confusion_matrix.matrix # will return the entire confusion matrix as numpy array
m.trainer.validator.metrics.box.f1 # AP F1-score if that's also of interest
m.trainer.validator.metrics.box.p # precision
m.trainer.validator.metrics.box.r # recall
```
