### ISSUE TITLE
How to interpret Output Tensor; Box Confidence vs Class Probability vs Objectness

### ISSUE THREAD

**Issue by V1ad20** [ultralytics/ultralytics#3707]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I'm trying to integrate a custom yolov8 model in the Hololens 2 using Unity and the Barracuda library.  I'm testing a yolov8n.onnx model that is trained to only detect 1 class.  

Below is the code I am using to extract the output from the model.  It was adapted from a Hololens 2 project using Yolov7.  It can be found at this link: https://localjoost.github.io/HoloLens-AI-using-Yolo-ONNX-models-to-localize-objects-in-3D-space/

`public YoloItem(Tensor tensorData, int boxIndex, IYoloClassTranslator translator)`
`{`
    `Center = new Vector2(tensorData[0, 0, boxIndex, 0], tensorData[0, 0, boxIndex, 1]);`
    `Size = new Vector2(tensorData[0, 0, boxIndex, 2], tensorData[0, 0, boxIndex, 3]);`
    `TopLeft = Center - Size / 2;`
    `BottomRight = Center + Size / 2;`
    `Confidence = tensorData[0, 0, boxIndex, 4];`
...

Here are the possible ways I can access data in the tensorData tensor:
<img width="447" alt="Screenshot 2023-07-12 at 5 24 44 PM" src="https://github.com/ultralytics/ultralytics/assets/86973499/6e478e44-df32-422a-9e80-ac3dbd220e19">

Here is a Neutron summary of my onnx model:
<img width="490" alt="Screenshot 2023-07-12 at 5 19 38 PM" src="https://github.com/ultralytics/ultralytics/assets/86973499/ce3f9aa9-6c8b-4435-b194-953064de5757">

I had a few questions about how to interpret the output

1. My understanding is that tensorData[0,0,boxIndex, i] should give me data about the bounding box corresponding to boxIndex. tensorData[0,0, boxIndex, 0] should give me the x value of the center point, tensorData[0,0, boxIndex, 1] should give me the y value of the center point, tensorData[0,0, boxIndex, 2] should give me the width of the bounding box, and tensorData[0,0, boxIndex, 3] should give me the height of the bounding box. Does this seem correct?
2. I'm confused about what tensorData[0,0, boxIndex, 4] is about.  
<img width="494" alt="Screenshot 2023-07-12 at 5 33 07 PM" 
src="https://github.com/ultralytics/ultralytics/assets/86973499/04ca0dbf-96fc-4152-8fa9-00c41df713d7">
According to this frame of a video explaining how YOLO works, tensorData[0,0, boxIndex, 4] should be an "objectness score".  Since this is the 5th and thus last piece of data according to the Neutron summary (indicated by the 5 in float32[1,5,8400]), there seems to be a class probability missing from the output of my model.  I read issue #2423, and it seems YOLOv8 combines class probabilities and "box confidence".  What's the difference between objectness score and box confidence? Moreover, what is actually outputed by tensorData[0,0, boxIndex, 4]? I seem to sometimes get a value greater than 1 from it sometimes. Finally, how would I access box confidence and objectness score using this C# notation?

**Comment by Kayzwer** [comment]
This [project](https://github.com/ivilson/Yolov7net) can help. It support yolov8 object detection.

**Comment by glenn-jocher** [comment]
@V1ad20 thank you for sharing the project that supports YOLOv8 object detection. It's great to see community contributions to the YOLOv8 ecosystem. We appreciate your effort in sharing this resource with us.

Please note that this repository is specifically for YOLOv8, and not YOLOv5. If you have any questions or need assistance regarding YOLOv8, feel free to ask. We are here to help!

**Comment by V1ad20** [comment]
> This [project](https://github.com/ivilson/Yolov7net) can help. It supports yolov8 object detection.

I took a look at this project, but I'm not totally sure what's going on in this piece of code.  I have some comments giving my interpretation.
```
private List<YoloPrediction> ParseDetect(DenseTensor<float> output, Image image)
        {
            var result = new ConcurrentBag<YoloPrediction>(); //List of bounding boxes that have good enough class probabilities

            var (w, h) = (image.Width, image.Height); //width and height of unaltered image

            //Not quite sure what this is
            var (xGain, yGain) = (_model.Width / (float)w, _model.Height / (float)h);
            var gain = Math.Min(xGain, yGain);
            var (xPad, yPad) = ((_model.Width - w * gain) / 2, (_model.Height - h * gain) / 2);

            /* output
             * .Buffer: System.Memory<Single>[705600], basically an array with 705600 (84*8400) entries
             * .Dimensions: System.ReadOnlySpan<Int32>[3], basically the array: [1,84,8400]
             * .isFixedSize: true
             * .isReadOnly: false
             * .isReversedStride: false
             * .Length: 705600 (84*8400)
             * .Rank: 3
             * .Strides: System.ReadOnlySpan<Int32>[3], basically the array: [705600,8400,1]
             */

            //output.Dimenions[0] == 1
            //outer for loop analagous to for(int i = 0; i < 1; i++)
            Parallel.For(0, output.Dimensions[0], i =>
            {
                //output.Length == 705600, output.Dimensions[1] == 84,
                //inner for loop analagous to for(int j = 0; j < 8400; j++)
                Parallel.For(0, (int)(output.Length / output.Dimensions[1]), j =>
                {
                    int dim = output.Strides[1]; //8400
                    var span = output.Buffer.Span.Slice(i * output.Strides[0]); //copy of .Buffer

                    //Not quite sure what this means
                    float a = span[j];
                    float b = span[dim + j];
                    float c = span[2 * dim + j];
                    float d = span[3 * dim + j];
                    float xMin = ((a - c / 2) - xPad) / gain; // unpad bbox tlx to original
                    float yMin = ((b - d / 2) - yPad) / gain; // unpad bbox tly to original
                    float xMax = ((a + c / 2) - xPad) / gain; // unpad bbox brx to original
                    float yMax = ((b + d / 2) - yPad) / gain; // unpad bbox bry to original

                   
                    for (int l = 0; l < _model.Dimensions - 4; l++)
                    {
                        var pred = span[(4 + l) * dim + j]; //Basically span[(4 + current_object_class_index) * num_boxes + current_box_index]
                       

                        if (pred < _model.Confidence) continue;
                        var label = _model.Labels[l];
                        result.Add(new YoloPrediction
                        {
                            Label = label,
                            Score = pred,
                            Rectangle = new RectangleF(xMin, yMin, xMax - xMin, yMax - yMin)
                        });
                    }
                });
            });

            return result.ToList();
        }
```

The author seems to access the prediction by accessing span[(4 + l) * dim + j], where dim is the number of boxes (8400).  The "4+l" I assume has something to do with the fact that the first 4 "data values" for a given bounding box are not class probabilities.  However, I'm still not sure how to access the class probabilites using tensor notation. Do you have any ideas?

**Comment by V1ad20** [comment]
> @V1ad20 thank you for sharing the project that supports YOLOv8 object detection. It's great to see community contributions to the YOLOv8 ecosystem. We appreciate your effort in sharing this resource with us.
> 
> Please note that this repository is specifically for YOLOv8, and not YOLOv5. If you have any questions or need assistance regarding YOLOv8, feel free to ask. We are here to help!

Apologies, what I meant to get at in the questions I asked were how to extrapolate values like box confidence, objectness and class probabilites.  In issue #2423, you say:

"model outputs the pre-multiplied confidences, as you mentioned. However, you can still calculate the box confidence by dividing the objectness confidence by the pre-multiplied confidences, as outlined in the [YOLOv3 paper](https://arxiv.org/pdf/1804.02767.pdf) (section 2.2)"

but I'm not quite sure how to get the objectness score (which seems to be a prequiste to getting the box confidence and class probabilites).

At the end of the day I'm trying to filter out the bounding boxes that are probably not indicating objects.  Would I just associate a bounding box with its highest pre multiplied confidence, and then discard it if the highest pre multiplied confidence is not high enough?  Do you also have any ideas how I could access these pre multiplied confidences using Tensor notation?

**Comment by glenn-jocher** [comment]
@V1ad20 hello there! Thank you for reaching out and expressing your question regarding YOLOv8 object detection. I understand that you're trying to filter out bounding boxes that may not indicate objects, and you want to know how to access the pre-multiplied confidences using Tensor notation.

To extract the pre-multiplied confidences and calculate the box confidence, you can follow these steps:
1. Access the objectness confidence from the model's output. The objectness confidence represents the likelihood of an object being present in a bounding box.
2. Divide the objectness confidence by the pre-multiplied confidences to obtain the box confidence. The pre-multiplied confidences are the class probabilities for each bounding box.
3. Once you have the box confidence, you can associate each bounding box with its highest pre-multiplied confidence value.
4. To filter out bounding boxes, you can discard those with low box confidence values or set a threshold for the minimum acceptable confidence level.

Regarding accessing the pre-multiplied confidences using Tensor notation, it seems that the code you shared uses span[(4 + l) * dim + j] to access the class probabilities, where l represents the index of the current object class. This notation allows you to retrieve the corresponding pre-multiplied confidence value for each bounding box.

I hope this explanation clarifies the process of extracting the box confidence and accessing pre-multiplied confidences using Tensor notation. If you have any further questions or need additional assistance, please feel free to ask. We are here to help you!
