### ISSUE TITLE
Instance Segmentation: How?

### ISSUE THREAD

**Issue by Zaryob** [ultralytics/ultralytics#371]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a dataset which is fully annotated using CVAT and I exported it from COCO 1.0 format. How can I train instance segmentation model it using COCO format?

**Comment by AyushExel** [comment]
You need to convert the dataset to yolo segmentation format using this tool https://github.com/ultralytics/JSON2YOLO

**Comment by ichsan2895** [comment]
https://github.com/ultralytics/yolov5/issues/10621

> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> ### Question
> I have a dataset which is fully annotated using CVAT and I exported it from COCO 1.0 format. How can I train instance segmentation model it using COCO format?
> 
> ### Additional
> _No response_

Take a look this thread
https://github.com/ultralytics/yolov5/issues/10621

I created a jupyter notebook that mix the code from JSON2COCO & stackoverflow to converting COCO to YOLO and you can download it here :
https://drive.google.com/file/d/1xhBiWv_Y0HBZQHoWBwF7yjpRrDZhrk4f/view?usp=sharing

Just change the last cell to desired output_path and json_file path. If you want use bbox annotations, just add use_segment=False. Then you run all cells from start to the last.

**Comment by simonbrislin** [comment]
Is there any documentation on the format for instance segmentation annotation? I have some source masks and am writing a generator. I would like to add YOLOv8 support to it but can't figure out exactly how the format works. I have COCO run-length encoding working at the moment.

**Comment by AyushExel** [comment]
You can just run the dataset through the json2yolo repository https://github.com/ultralytics/JSON2YOLO

**Comment by simonbrislin** [comment]
Thanks. Yes I saw that. I'd just like to properly understand the format. I would prefer to write to the native format rather than writing to another format and then rely on a tool to convert to the format I actually want.

**Comment by AyushExel** [comment]
@simonbrislin yeah good point, we'll work to bring that repo here with better docs and even directly support json formats

**Comment by simonbrislin** [comment]
Thanks. Look forward to it

**Comment by ryouchinsa** [comment]
If the "segmentation" in the COCO file contains the polygon arrays, you can use the conversion script.
https://github.com/ultralytics/JSON2YOLO
```
"segmentation": [
    [136, 557, 152, 532, ...]
]
```
If the "segmentation" in the COCO file contains the RLE mask, you can convert the RLE mask to the polygon arrays using cv2.findContours().
https://github.com/cocodataset/cocoapi/issues/476#issuecomment-871804850
```
"segmentation":
{
    "counts": "ie_e03c00...",
    "size": [3317, 4417]
}
```
To reduce the number of polygon points, you can use cv2. approxPolyDP().
https://docs.opencv.org/4.x/d3/dc0/group__imgproc__shape.html#ga0012a5fdaea70b8a9970165d98722b4c

RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can import the COCO segmentation format and export to the YOLO segmentation format.
https://rectlabel.com/help#xml_to_yolo
```
class_index x1 y1 x2 y2 x3 y3 ...
0 0.180027 0.287930 0.181324 0.280698 0.183726 0.270573 ...
```
![yolo_polygon](https://user-images.githubusercontent.com/1954306/214115862-ee479a87-8731-4b49-9997-e3807a7898bb.jpg)

**Comment by pderrenger** [comment]
@ryouchinsa that's great to hear about the new feature! Thanks for updating us. RectLabel seems like a useful tool for converting COCO segmentation format to YOLOv8 segmentation format. Nice find!
