### ISSUE TITLE
How to measure the yolov8 model's parameters and complexity?

### ISSUE THREAD

**Issue by Jess1989** [ultralytics/ultralytics#3710]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I didn't see the file to measure the model parameters and complexity,

**Comment by glenn-jocher** [comment]
@Jess1989 hello! Thank you for reaching out. To measure the parameters and complexity of the YOLOv8 model, you can use the "summary" functionality provided by the PyTorch framework. This functionality allows you to easily inspect the model architecture, including the number of parameters and operations involved. 

To measure the parameters and complexity, you can use the following steps:

1. First, import the necessary libraries:
```
import torch
from torchvision.models import yolov8
```

2. Next, create an instance of the YOLOv8 model:
```
model = yolov8()
```

3. Retrieve the model summary, which includes the number of parameters and operations:
```
summary = torchsummary.summary(model, (3, 224, 224))
```

The `summary` object will provide you with detailed information about the model, including the number of parameters and operations at each layer.

Please note that the `torchsummary` library needs to be installed in order to use the summary functionality. You can install it using the `pip` command:
```
pip install torchsummary
```

I hope this helps! Let me know if you have any further questions.

**Comment by AndywithCV** [comment]
> @Jess1989 hello! Thank you for reaching out. To measure the parameters and complexity of the YOLOv8 model, you can use the "summary" functionality provided by the PyTorch framework. This functionality allows you to easily inspect the model architecture, including the number of parameters and operations involved.
> 
> To measure the parameters and complexity, you can use the following steps:
> 
> 1. First, import the necessary libraries:
> 
> ```
> import torch
> from torchvision.models import yolov8
> ```
> 
> 2. Next, create an instance of the YOLOv8 model:
> 
> ```
> model = yolov8()
> ```
> 
> 3. Retrieve the model summary, which includes the number of parameters and operations:
> 
> ```
> summary = torchsummary.summary(model, (3, 224, 224))
> ```
> 
> The `summary` object will provide you with detailed information about the model, including the number of parameters and operations at each layer.
> 
> Please note that the `torchsummary` library needs to be installed in order to use the summary functionality. You can install it using the `pip` command:
> 
> ```
> pip install torchsummary
> ```
> 
> I hope this helps! Let me know if you have any further questions.

I tried this one, but it seemed like in torchvision there is no yolov8 model!!!! please help to clarify this

**Comment by glenn-jocher** [comment]
@AndywithCV i apologize for the confusion. You're right, the torchvision library currently does not support direct import of the YOLOv8 model.

When I mentioned to use PyTorch's functionality, it assumes that you already have a functioning YOLOv8 model defined in your PyTorch environment. This could have been built manually, or loaded from a pre-trained model file.

Once you have your YOLOv8 model set up in PyTorch, you should be able to use the "summary" functionality provided by the torchsummary library to analyse the model architecture, its layer details, and overall complexity.

This would provide you with the number of parameters for the model, the memory used by the model, and the number of operations at each layer, among other things.

Remember that you should install the torchsummary library using `pip install torchsummary` command if it is not already in your environment.

Sorry again for the confusion - I hope this clarifies things a bit. Let me know if you need any additional assistances, I would be happy to help.

**Comment by AndywithCV** [comment]
> @AndywithCV i apologize for the confusion. You're right, the torchvision library currently does not support direct import of the YOLOv8 model.
> 
> When I mentioned to use PyTorch's functionality, it assumes that you already have a functioning YOLOv8 model defined in your PyTorch environment. This could have been built manually, or loaded from a pre-trained model file.
> 
> Once you have your YOLOv8 model set up in PyTorch, you should be able to use the "summary" functionality provided by the torchsummary library to analyse the model architecture, its layer details, and overall complexity.
> 
> This would provide you with the number of parameters for the model, the memory used by the model, and the number of operations at each layer, among other things.
> 
> Remember that you should install the torchsummary library using `pip install torchsummary` command if it is not already in your environment.
> 
> Sorry again for the confusion - I hope this clarifies things a bit. Let me know if you need any additional assistances, I would be happy to help.

I tried install torch summary and run it with "summary = torchsummary.summary(model, (3, 224, 224))", but it returns error like below:
 File "main_benchmark2.py", line 31, in <module>
    summary = torchsummary.summary(model, (3, 224, 224))
  File "/opt/conda/envs/yolov8benchmark/lib/python3.8/site-packages/torchsummary/torchsummary.py", line 72, in summary
    model(*x)
  File "/root/data/andy/yolov8benchmark/ultralytics/ultralytics/engine/model.py", line 96, in __call__
    return self.predict(source, stream, **kwargs)
  File "/root/data/andy/yolov8benchmark/ultralytics/ultralytics/engine/model.py", line 236, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/root/data/andy/yolov8benchmark/ultralytics/ultralytics/engine/predictor.py", line 194, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/opt/conda/envs/yolov8benchmark/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/data/andy/yolov8benchmark/ultralytics/ultralytics/engine/predictor.py", line 237, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "/root/data/andy/yolov8benchmark/ultralytics/ultralytics/nn/autobackend.py", line 465, in warmup
    self.forward(im)  # warmup
  File "/root/data/andy/yolov8benchmark/ultralytics/ultralytics/nn/autobackend.py", line 333, in forward
    y = self.model(im, augment=augment, visualize=visualize) if augment or visualize else self.model(im)
  File "/opt/conda/envs/yolov8benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/root/data/andy/yolov8benchmark/ultralytics/ultralytics/nn/tasks.py", line 48, in forward
    return self.predict(x, *args, **kwargs)
  File "/root/data/andy/yolov8benchmark/ultralytics/ultralytics/nn/tasks.py", line 65, in predict
    return self._predict_once(x, profile, visualize)
  File "/root/data/andy/yolov8benchmark/ultralytics/ultralytics/nn/tasks.py", line 85, in _predict_once
    x = m(x)  # run
  File "/opt/conda/envs/yolov8benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1547, in _call_impl
    hook_result = hook(self, args, result)
  File "/opt/conda/envs/yolov8benchmark/lib/python3.8/site-packages/torchsummary/torchsummary.py", line 19, in hook
    summary[m_key]["input_shape"] = list(input[0].size())
AttributeError: 'list' object has no attribute 'size'

Please help me on that

**Comment by glenn-jocher** [comment]
@AndywithCV I'm sorry to hear that you're having trouble with the torchsummary.summary call.

The error message you shared seems to be pointing towards an attribute error on 'list' object, specifically 'list' object has no attribute 'size'. It looks like the input being given to the model is in an unexpected data type (a list), where it's expected to be a PyTorch tensor.

Applying torchsummary.summary on a model assumes that the model has a standard forward method that accepts a tensor as input. However, from the error message, it appears YOLOv8 in your environment may have some custom method that may not fit well with the torchsummary.summary.

I'd recommend ensuring that the data is appropriately converted into PyTorch tensors before being input to the model. Also ensure your YOLOv8 model doesn't have custom input handling which might cause conflicts with torchsummary.summary.

Hopefully this provides some guidance. Let me know if you have further questions.

**Comment by tianlianghai** [comment]
LOL, Are you using chatgpt to answer this question? I have the same issue to calculate the parameter of a model from YOLO, I'm currently using YOLOv8m-obb, I know that there is a summary information at the top of the log befor training, but while debuging the training process I find that the summary information seems to assume that input size is always 640.
in summary,is there a way to calculate it according to the input size?

**Comment by glenn-jocher** [comment]
@tianlianghai yes the FLOPs displayed are computed at 640x640 image size. To convert to your actual size you can scale these according the area difference of your actual image.
