### ISSUE TITLE
About PyTorch version of YOLOv8

### ISSUE THREAD

**Issue by Heartful-echo** [ultralytics/ultralytics#3711]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi

Does YOLOv8 support version 2.0.0 of PyTorch?
Should I use PyTorch v1.13.0 or PyTorch v2.0.0?

Any Thank you.

**Comment by Kayzwer** [comment]
PyTorch v2.0.0 is supported

**Comment by Heartful-echo** [comment]
@Kayzwer 

I am happy to receive an answer so quickly.
Thank you very much.

**Comment by glenn-jocher** [comment]
@Kayzwer you're welcome! We strive to provide prompt and helpful assistance to our users. If you have any further questions or need any additional support with YOLOv8, feel free to ask. We're here to help!
