### ISSUE TITLE
Can you get validation outputs for every training epoch where best.pt is replaced?

### ISSUE THREAD

**Issue by tteresi7** [ultralytics/ultralytics#3714]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

So right now, if I want to get the validation plots, especially the validation labels and results, it only occurs once training concludes, so my only option is to pause training periodically, run validation, and restart training..  I have been trying to find a way that once the model completes an epoch, if the epoch is the new best, that it will save these figures.  I was just curious if this exists, or if there is a plan to add it?  It may also be nice if it saved those plots in a folder labelled with the epoch number rather than just the images placed into the training directory.

**Comment by glenn-jocher** [comment]
@tteresi7 hi! Thank you for reaching out to us.

Currently, YOLOv8 does not have a built-in feature to save validation outputs for every training epoch where `best.pt` is replaced. The validation plots and results are only generated when the training concludes.

To achieve what you're looking for, you can manually pause the training periodically, run the validation, and then restart the training. This way, you can obtain the validation outputs for each epoch.

Regarding saving the plots in a folder labelled with the epoch number, this is not a feature of YOLOv8 at the moment. However, you can customize the code to save the validation plots in a separate folder with the desired epoch number label if you wish.

Thank you for your suggestion. While there are no immediate plans to add this specific feature, we appreciate your feedback and will consider it for future updates to improve the user experience.

Please let me know if you have any further questions or if there's anything else I can assist you with!
