### ISSUE TITLE
`new_shape` variable is `None` so NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by hungnguyendc** [ultralytics/ultralytics#3717]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I try to feed a list of images ([1080, 1920, 3] x N) into the model for prediction, got this error while they were performing LetterBox resizing.

```
File "/Users/hungnt/opt/miniconda3/envs/sur-sys/lib/python3.9/site-packages/ultralytics/yolo/engine/predictor.py", line 123, in preprocess
    im = np.stack(self.pre_transform(im))
  File "/Users/hungnt/opt/miniconda3/envs/sur-sys/lib/python3.9/site-packages/ultralytics/yolo/engine/predictor.py", line 144, in pre_transform
    return [LetterBox(self.imgsz, auto=auto, stride=self.model.stride)(image=x) for x in im]
  File "/Users/hungnt/opt/miniconda3/envs/sur-sys/lib/python3.9/site-packages/ultralytics/yolo/engine/predictor.py", line 144, in <listcomp>
    return [LetterBox(self.imgsz, auto=auto, stride=self.model.stride)(image=x) for x in im]
  File "/Users/hungnt/opt/miniconda3/envs/sur-sys/lib/python3.9/site-packages/ultralytics/yolo/data/augment.py", line 562, in __call__
    r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])
TypeError: 'NoneType' object is not subscriptable
```

This is the code block where they got an error
In `ultralytics/yolo/data/augment.py`
```
    def __call__(self, labels=None, image=None):
        """Return updated labels and image with added border."""
        if labels is None:
            labels = {}
        img = labels.get('img') if image is None else image
        shape = img.shape[:2]  # current shape [height, width]
        new_shape = labels.pop('rect_shape', self.new_shape)
        if isinstance(new_shape, int):
            new_shape = (new_shape, new_shape)

        # Scale ratio (new / old)
        r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])
        if not self.scaleup:  # only scale down, do not scale up (for better val mAP)
            r = min(r, 1.0)
```

I have printed and confirmed that the image `np.ndarray` has got here.

Can anyone help me to fix this?

### Environment

- YOLO: Yolo Tracking v10.0.15 🚀 Python-3.9.17 torch-2.0.1 CPU
- OS: MacOS 13.4
- Python 3.9.17

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@hungnguyendc hi there! Thank you for reporting this issue. It looks like there is an error when performing the LetterBox resizing on a list of images.

The error message indicates that the variable `new_shape` is `None`, which leads to the error `'NoneType' object is not subscriptable`. 

To fix this issue, you can try providing a valid value for `new_shape` when calling the YOLOv8 model for prediction. It should be a tuple of integers specifying the desired height and width of the resized image.

For example, you can set `new_shape = (416, 416)` to resize the input images to a size of 416x416 pixels.

Please give it a try and let me know if it resolves the issue. If you need further assistance, don't hesitate to ask.

**Comment by Laughing-q** [comment]
@hungnguyendc can you provide us a Minimal Reproducible Example to reproduce the issue? Thanks!

**Comment by hungnguyendc** [comment]
Hello people, I've figured out this is my mistake. The problem is I forgot to run the `setup_source` function. So the attribute `imgsz` in the `predictor` is now `None`. So, when calling `LetterBox`, the `new_shape` will also be `None`. 

Thanks, everyone for helping me, I will close this issue now.

**Comment by glenn-jocher** [comment]
@hungnguyendc hello,

It appears that the issue you encountered was due to a mistake on your part. The problem arose because you forgot to run the `setup_source` function, which resulted in the `imgsz` attribute in the `predictor` being set to `None`.

As a consequence, when calling the `LetterBox` function, the `new_shape` parameter was also `None`, leading to the error.

Thank you to everyone who offered their assistance. I will now close this issue.

Best regards.
