### ISSUE TITLE
Running Segmentation Only on specific classes

### ISSUE THREAD

**Issue by ahv1373** [ultralytics/ultralytics#3720]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi. Thank your for your great work.

I was wondering if it is possible to apply instance segmentation only for specific classes.
For instance, let's assume that I have a model which first detect all bounding boxes in the image and we have the entire results.boxes data and afterward, it applies instance segmentation for only some specific classes with the goal of increasing the inference speed of the model. Is such feature already implemented in YOLOV8 or should I customize the `SegmentationPredictor` class myself in order to achieve this?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ahv1373 hi there!

Thank you for your kind words and for your interest in YOLOv8. Currently, YOLOv8 does not have a built-in option to apply instance segmentation only for specific classes. However, you can achieve this functionality by customizing the `SegmentationPredictor` class. You would need to modify the code to selectively perform instance segmentation based on the classes you are interested in.

If you would like to contribute to the project, we welcome pull requests! Feel free to submit a pull request with your modifications to the `SegmentationPredictor` class. Our team will review your changes and work with you to integrate them into the YOLOv8 codebase.

Please let us know if you have any further questions or need any assistance with customizing the `SegmentationPredictor` class. We are here to help!

Best regards,
Glenn Jocher

**Comment by Laughing-q** [comment]
@ahv1373 you can simply use this feature by passing `classes`, here's an example for you:
```python
from ultralytics import YOLO

model = YOLO("yolov8n-seg.pt")
model.predict(classes=0, save=True)
```
and you can see only the first class(person) is segmented.
![bus](https://github.com/ultralytics/ultralytics/assets/61612323/687a469b-8908-4408-b914-de1243ed2905)
