### ISSUE TITLE
Data augmentation for yolov8-pose 

### ISSUE THREAD

**Issue by mohamedamara7** [ultralytics/ultralytics#3728]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I apply data augmentation while training yolov8-pose, I mean what code that should I write?

**Comment by Laughing-q** [comment]
@mohamedamara7 The augmentations are all set by default, you don't need to write anything. But if you mean you want to modify augmentations then the code is here:
https://github.com/ultralytics/ultralytics/blob/fadbef84e160c3c98f0a791d7b45850f1449cb75/ultralytics/yolo/data/augment.py#L765-L793
