### ISSUE TITLE
Yolo for face recognition

### ISSUE THREAD

**Issue by sitifatim** [ultralytics/ultralytics#3729]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

is it possible to use yolo for face recognition? i tried with several face recognition pre-trained models already but it gave me worst result when i used these models for real time video, but when i tried yolo for real time video for detecting car, yolo gave me good result with low delay so i wonder, is it possible to use yolo for face recognition?

### Additional

-

**Comment by bit-scientist** [comment]
YOLO is an object _detection_ model, not recognition. Unless your use case is very small number of people for a limited place, object detectors are not good for recognition. I suggest using face recognition models which you can find with a simple google search.

**Comment by sitifatim** [comment]
alright, thanks for the answer and the suggestion

**Comment by glenn-jocher** [comment]
@sitifatim you're welcome! I'm glad I could help. If you have any more questions or need further assistance, feel free to ask. Good luck with your face recognition project!
