### ISSUE TITLE
Cannot find common.py file.

### ISSUE THREAD

**Issue by dhruv-chaurasia** [ultralytics/ultralytics#3733]
Cannot find common.py file.
Can you please help?

_Originally posted by @dhruv-chaurasia in https://github.com/ultralytics/ultralytics/issues/2154#issuecomment-1635318216_

**Comment by Kayzwer** [comment]
@dhruv-chaurasia I think `/ultralytics/ultralytics/nn/modules/` is what you need.

**Comment by dhruv-chaurasia** [comment]
> @dhruv-chaurasia I think `/ultralytics/ultralytics/nn/modules/` is what you need.

Thanks for replying. Actually, in my project, I am using satellite images with multiple bands other than RGB. So, I need to modify the codes for accepting such images. When I searched, it said that I need to modify the load_image() function and model definition in common.py file. I tried to change the load_image() function but now I am not understanding from where to change the model definitions.
Can you please help?

Thank You.

**Comment by harshdhamecha** [comment]
Have you tried running your code after changing `load_image()`? If yes, did you got any errors or warnings? Please post the detailed message if you've got any errors or warnings.

**Comment by dhruv-chaurasia** [comment]
I cloned the github repo for yolo v8 and modified the required function. But now I am not understanding which file to run or how to import the changed YOLO mode. Can you tell me which file should I run since there are so many files.

**Comment by harshdhamecha** [comment]
You can refer [docs](https://docs.ultralytics.com/modes/train/#usage-examples) for that.

**Comment by glenn-jocher** [comment]
@harshdhamecha thank you for your interest in YOLOv8! To run the modified YOLOv8 model and import the changes you made, you need to run the `train.py` file. This is the entry point for training the YOLOv8 model on your custom dataset.

Before running `train.py`, make sure you have made the necessary modifications in the `load_image()` function and any other relevant locations. These modifications should now be applied when the model is trained.

Once you have made the modifications, open your terminal or command prompt and navigate to the YOLOv8 directory. Then run the `train.py` file using the appropriate command for your environment.

After training the model with your custom dataset, you can use the trained model for various tasks like validation, prediction, exporting, tracking, or benchmarking. Each task has its own specific file that you can run, such as `val.py`, `predict.py`, `export.py`, `track.py`, or `benchmark.py`, depending on your requirements.

For more information and usage examples, please refer to the YOLOv8 documentation [here](https://docs.ultralytics.com/modes/train/#usage-examples).

I hope this helps you get started with running your modified YOLOv8 model. If you have any further questions, please feel free to ask.

**Comment by glenn-jocher** [comment]
@Kayzwer you're welcome! I'm glad I could help. If you have any further questions or need assistance with anything related to YOLOv8, feel free to ask. Good luck with your project!

**Comment by dhruv-chaurasia** [comment]
Can you tell what all changes do I need to make in the codes for working with mulltiband images? Just changing the load_image() function doesn't work.

**Comment by has12zen** [comment]
Hi @glenn-jocher I am also working on similar project where I need to take multiple bands as input while training and predicting. I was trying to look through this issue and [this](https://github.com/ultralytics/ultralytics/issues/2154) issue to get how to make the necessary changes. 

## Setting up environment
I first created a conda environment and installed pytorch. then from the quickstart documentation I ran these commands.

```sh
# Clone the ultralytics repository
git clone https://github.com/ultralytics/ultralytics

# Navigate to the cloned directory
cd ultralytics

# Install the package in editable mode for development
pip install -e .
```

## making changes
### Load_images
I found the load_image function in base.py file
```py

    def load_image(self, i):
        """Loads 1 image from dataset index 'i', returns (im, resized hw)."""
        im, f, fn = self.ims[i], self.im_files[i], self.npy_files[i]
        if im is None:  # not cached in RAM
            if fn.exists():  # load npy
                im = np.load(fn)
            else:  # read image
                im = cv2.imread(f)  # BGR
                if im is None:
                    raise FileNotFoundError(f'Image Not Found {f}')
            h0, w0 = im.shape[:2]  # orig hw
            r = self.imgsz / max(h0, w0)  # ratio
            if r != 1:  # if sizes are not equal
                interp = cv2.INTER_LINEAR if (self.augment or r > 1) else cv2.INTER_AREA
                im = cv2.resize(im, (min(math.ceil(w0 * r), self.imgsz), min(math.ceil(h0 * r), self.imgsz)),
                                interpolation=interp)

            # Add to buffer if training with augmentations
            if self.augment:
                self.ims[i], self.im_hw0[i], self.im_hw[i] = im, (h0, w0), im.shape[:2]  # im, hw_original, hw_resized
                self.buffer.append(i)
                if len(self.buffer) >= self.max_buffer_length:
                    j = self.buffer.pop(0)
                    self.ims[j], self.im_hw0[j], self.im_hw[j] = None, None, None

            return im, (h0, w0), im.shape[:2]

        return self.ims[i], self.im_hw0[i], self.im_hw[i]
```
I have numpy installed so I guess it wrould read all the bands of image.
it seems to return the image and the (height, width) of image and shape of image except the height and width I dont think it needs to be changed but If it needs to be changed can you please tell me. 

### Other files.
I am not sure if any other files need to be modified.

## Getting the results
currently in the development environment I am importing the yolo model as 
```
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)
``` 
and then I plan to train it as we would train normal RGB image. 
also If I need to modify the yolo code do I need to run 
```sh
pip install -e .
```

**Comment by glenn-jocher** [comment]
@has12zen hello,

Working with multiband images in YOLOv8 involves some modifications beyond adjusting the load_image() function. Essentially, you have to make sure every part of the pipeline that deals with the input image can handle multiband images.

You are correct in assuming that the load_image() function returns the image and a tuple containing the height and width of the image. You don't necessarily need to change the dimensions, but you have to adjust other areas of the code base to ensure they work with multiband images. Apart from changing how images are loaded, you also need to adjust how they are processed during training and inference.

One of such modifications is in the forward function in the models. YOLOv8 models are designed to take in 3-band (RGB) images for object detection tasks, so you would need to adjust the model's architecture to work with the number of bands present in your new images.

You should also take care to adjust normalization, as the values you would normally use for RGB images might not apply to your multiband images.

As for getting your results, using the YOLO import and instantiation should still work, but remember your model won't be pretrained as usual since the weights are typically trained on RGB images. As for installing the modified YOLO code, you would need to run `pip install -e .` to reflect any changes made.

Keep in mind that working with multiband images is a vast topic on its own, and these adjustments depend largely on the specifics of your dataset and project requirements.

I hope this helps. Let me know if you have any other questions!

**Comment by has12zen** [comment]
@glenn-jocher thank you for explaining. 
## Control 
I first ran the yolo model on RGB images using this [dataset](https://huggingface.co/datasets/Ryukijano/Pothole-detection-Yolov8/blob/main/data.yaml) to check if everything was working correctly I was able to train the model.
## Actual work
Now I want to run it for my actual dataset currently I am ruining for only 8 images to train and 8 in val
I got the following output first.

```sh
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed 
train: Scanning [L:\mywork\train\labels.cache...](file:///L:/mywork/train/labels.cache...) 0 images, 0 backgrounds, 8 corrupt: 100%|██████████| 8/8 [00:00<?, ?it/s]
train: WARNING  [L:\mywork\train\images\1990_0302_combined.tif](file:///L:/mywork/train/images/1990_0302_combined.tif): ignoring corrupt image/label: cannot identify image file 'L:\\mywork\\train\\images\\1990_0302_combined.tif'
train: WARNING  [L:\mywork\train\images\1990_0303_combined.tif](file:///L:/mywork/train/images/1990_0303_combined.tif): ignoring corrupt image/label: cannot identify image file 'L:\\mywork\\train\\images\\1990_0303_combined.tif'
train: WARNING  [L:\mywork\train\images\1990_0304_combined.tif](file:///L:/mywork/train/images/1990_0304_combined.tif): ignoring corrupt image/label: cannot identify image file 'L:\\mywork\\train\\images\\1990_0304_combined.tif'
train: WARNING  [L:\mywork\train\images\1990_0305_combined.tif](file:///L:/mywork/train/images/1990_0305_combined.tif): ignoring corrupt image/label: cannot identify image file 'L:\\mywork\\train\\images\\1990_0305_combined.tif'
train: WARNING  [L:\mywork\train\images\1990_0402_combined.tif](file:///L:/mywork/train/images/1990_0402_combined.tif): ignoring corrupt image/label: cannot identify image file 'L:\\mywork\\train\\images\\1990_0402_combined.tif'
train: WARNING  [L:\mywork\train\images\1990_0403_combined.tif](file:///L:/mywork/train/images/1990_0403_combined.tif): ignoring corrupt image/label: cannot identify image file 'L:\\mywork\\train\\images\\1990_0403_combined.tif'
train: WARNING  [L:\mywork\train\images\1990_0404_combined.tif](file:///L:/mywork/train/images/1990_0404_combined.tif): ignoring corrupt image/label: cannot identify image file 'L:\\mywork\\train\\images\\1990_0404_combined.tif'
train: WARNING  [L:\mywork\train\images\1990_0405_combined.tif](file:///L:/mywork/train/images/1990_0405_combined.tif): ignoring corrupt image/label: cannot identify image file 'L:\\mywork\\train\\images\\1990_0405_combined.tif'
```

then I got this error 

```sh
FileNotFoundError                         Traceback (most recent call last)
Cell In[3], line 6
      4 model = YOLO('yolov8n.pt')  
      5 data_yaml_path = '[L:/mywork/data.yaml](file:///L:/mywork/data.yaml)'
----> 6 model.train(data=data_yaml_path, epochs=10, imgsz=640)

File [l:\mywork\ultralytics\ultralytics\engine\model.py:377](file:///L:/mywork/ultralytics/ultralytics/engine/model.py:377), in Model.train(self, trainer, **kwargs)
    375     self.model = self.trainer.model
    376 self.trainer.hub_session = self.session  # attach optional HUB session
--> 377 self.trainer.train()
    378 # Update model and cfg after training
    379 if RANK in (-1, 0):

File [l:\mywork\ultralytics\ultralytics\engine\trainer.py:192](file:///L:/mywork/ultralytics/ultralytics/engine/trainer.py:192), in BaseTrainer.train(self)
    190         ddp_cleanup(self, str(file))
    191 else:
--> 192     self._do_train(world_size)

File [l:\mywork\ultralytics\ultralytics\engine\trainer.py:276](file:///L:/mywork/ultralytics/ultralytics/engine/trainer.py:276), in BaseTrainer._do_train(self, world_size)
    273 if world_size > 1:
    274     self._setup_ddp(world_size)
--> 276 self._setup_train(world_size)
    278 self.epoch_time = None
    279 self.epoch_time_start = time.time()

File [l:\mywork\ultralytics\ultralytics\engine\trainer.py:240](file:///L:/mywork/ultralytics/ultralytics/engine/trainer.py:240), in BaseTrainer._setup_train(self, world_size)
    238 # Dataloaders
    239 batch_size = self.batch_size // max(world_size, 1)
--> 240 self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
    241 if RANK in (-1, 0):
    242     self.test_loader = self.get_dataloader(self.testset, batch_size=batch_size * 2, rank=-1, mode='val')

File [l:\mywork\ultralytics\ultralytics\models\yolo\detect\train.py:35](file:///L:/mywork/ultralytics/ultralytics/models/yolo/detect/train.py:35), in DetectionTrainer.get_dataloader(self, dataset_path, batch_size, rank, mode)
     33 assert mode in ['train', 'val']
     34 with torch_distributed_zero_first(rank):  # init dataset *.cache only once if DDP
---> 35     dataset = self.build_dataset(dataset_path, mode, batch_size)
     36 shuffle = mode == 'train'
     37 if getattr(dataset, 'rect', False) and shuffle:

File [l:\mywork\ultralytics\ultralytics\models\yolo\detect\train.py:29](file:///L:/mywork/ultralytics/ultralytics/models/yolo/detect/train.py:29), in DetectionTrainer.build_dataset(self, img_path, mode, batch)
     20 """
     21 Build YOLO Dataset.
     22 
   (...)
     26     batch (int, optional): Size of batches, this is for `rect`. Defaults to None.
     27 """
     28 gs = max(int(de_parallel(self.model).stride.max() if self.model else 0), 32)
---> 29 return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == 'val', stride=gs)

File [l:\mywork\ultralytics\ultralytics\data\build.py:74](file:///L:/mywork/ultralytics/ultralytics/data/build.py:74), in build_yolo_dataset(cfg, img_path, batch, data, mode, rect, stride)
     72 def build_yolo_dataset(cfg, img_path, batch, data, mode='train', rect=False, stride=32):
     73     """Build YOLO Dataset"""
---> 74     return YOLODataset(
     75         img_path=img_path,
     76         imgsz=cfg.imgsz,
     77         batch_size=batch,
     78         augment=mode == 'train',  # augmentation
     79         hyp=cfg,  # TODO: probably add a get_hyps_from_cfg function
     80         rect=cfg.rect or rect,  # rectangular batches
     81         cache=cfg.cache or None,
     82         single_cls=cfg.single_cls or False,
     83         stride=int(stride),
     84         pad=0.0 if mode == 'train' else 0.5,
     85         prefix=colorstr(f'{mode}: '),
     86         use_segments=cfg.task == 'segment',
     87         use_keypoints=cfg.task == 'pose',
     88         classes=cfg.classes,
     89         data=data,
     90         fraction=cfg.fraction if mode == 'train' else 1.0)

File [l:\mywork\ultralytics\ultralytics\data\dataset.py:40](file:///L:/mywork/ultralytics/ultralytics/data/dataset.py:40), in YOLODataset.__init__(self, data, use_segments, use_keypoints, *args, **kwargs)
     38 self.data = data
     39 assert not (self.use_segments and self.use_keypoints), 'Can not use both segments and keypoints.'
---> 40 super().__init__(*args, **kwargs)

File [l:\mywork\ultralytics\ultralytics\data\base.py:73](file:///L:/mywork/ultralytics/ultralytics/data/base.py:73), in BaseDataset.__init__(self, img_path, imgsz, cache, augment, hyp, prefix, rect, batch_size, stride, pad, single_cls, classes, fraction)
     71 self.fraction = fraction
     72 self.im_files = self.get_img_files(self.img_path)
---> 73 self.labels = self.get_labels()
     74 self.update_labels(include_class=classes)  # single_cls and include_class
     75 self.ni = len(self.labels)  # number of images

File [l:\mywork\ultralytics\ultralytics\data\dataset.py:124](file:///L:/mywork/ultralytics/ultralytics/data/dataset.py:124), in YOLODataset.get_labels(self)
    122         LOGGER.info('\n'.join(cache['msgs']))  # display warnings
    123 if nf == 0:  # number of labels found
--> 124     raise FileNotFoundError(f'{self.prefix}No labels found in {cache_path}, can not start training. {HELP_URL}')
    126 # Read cache
    127 [cache.pop(k) for k in ('hash', 'version', 'msgs')]  # remove items

FileNotFoundError: train: No labels found in [L:\mywork\train\labels.cache](file:///L:/mywork/train/labels.cache), can not start training. See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data
```

So I am guessing it failed to open any image from the dataset and then as it could not open any image file it is giving this error. I am not familar with the project structure of ultralytics repo or the yolo pipeline can you please tell me which files or parts I need to change.
