### ISSUE TITLE
Failed conversion from custom trained weight to NCNN

### ISSUE THREAD

**Issue by TheoNanu** [ultralytics/ultralytics#3740]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! i'm on a nvidia jetson nano and i want to export a custom trained weight to NCNN format but I get this error: `NCNN: export failure ❌ 4.5s: [Errno 8] Exec format error: '/home/jetson/.local/lib/python3.8/site-packages/ultralytics/pnnx'` when i run this script: 

```
from ultralytics import YOLO

# Create a model
model = YOLO('yolov8_last.pt')

# Export the model to NCNN with arguments
model.export(format='ncnn', half=True, imgsz=640)
```

Here is the full output:
```
jetson@nano:~/Desktop/YOLOv8_Detection$ python3 convertncnn.py
Ultralytics YOLOv8.0.134 🚀 Python-3.8.10 torch-1.12.0a0+git67ece03 CPU
Model summary (fused): 218 layers, 25842655 parameters, 0 gradients

PyTorch: starting from yolov8_last.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 9, 8400) (49.6 MB)

TorchScript: starting export with torch 1.12.0a0+git67ece03...
TorchScript: export success ✅ 47.2s, saved as yolov8_last.torchscript (99.1 MB)

NCNN: starting export with NCNN 1.0.20230517...
NCNN: running '/home/jetson/.local/lib/python3.8/site-packages/ultralytics/pnnx yolov8_last.torchscript pnnxparam=yolov8_last_ncnn_model/model.pnnx.param pnnxbin=yolov8_last_ncnn_model/model.pnnx.bin pnnxpy=yolov8_last_ncnn_model/model_pnnx.py pnnxonnx=yolov8_last_ncnn_model/model.pnnx.onnx ncnnparam=yolov8_last_ncnn_model/model.ncnn.param ncnnbin=yolov8_last_ncnn_model/model.ncnn.bin ncnnpy=yolov8_last_ncnn_model/model_ncnn.py fp16=1 device=cpu inputshape="[1, 3, 640, 640]"'
NCNN: export failure ❌ 4.5s: [Errno 8] Exec format error: '/home/jetson/.local/lib/python3.8/site-packages/ultralytics/pnnx'

Export complete (83.4s)
Results saved to /home/jetson/Desktop/YOLOv8_Detection
Predict:         yolo predict task=detect model=yolov8_last.torchscript imgsz=640 
Validate:        yolo val task=detect model=yolov8_last.torchscript imgsz=640 data=/content/datasets/clips_detection_upper_light-7/data.yaml 
Visualize:       https://netron.app
```

**Comment by glenn-jocher** [comment]
@TheoNanu hi there! It seems like you're encountering an error when exporting a custom trained weight to the NCNN format using YOLOv8. The error message `NCNN: export failure ❌ 4.5s: [Errno 8] Exec format error: '/home/jetson/.local/lib/python3.8/site-packages/ultralytics/pnnx'` indicates that there is an issue with the execution format for the export.

To address this, you can try a couple of potential solutions:
1. Make sure you have the necessary dependencies and libraries installed on your Nvidia Jetson Nano, as the error could be caused by missing dependencies.
2. Verify that you have the appropriate permissions to execute the export script. You might need to grant executable permissions to the `pnnx` file.

If these solutions don't resolve the issue, please provide more details about your system setup (e.g., operating system, NCNN version) and any other relevant information that could help us better understand the problem. That way, we can provide you with more specific guidance.

Thank you for reaching out, and we look forward to assisting you further with this issue!

**Comment by Klinefelters** [comment]
I'm running into the same error on the jetson nano. It's definitely an issue with the Nano, not the library. Has a solution been found? I'm looking at trying to pursue this further, and would be interested to hear if any progress has been made.

**Comment by glenn-jocher** [comment]
@Klinefelters hi there,

Thanks for reaching out. This is quite an intriguing issue you're encountering. There could be a number of things causing the problem and without further information, the exact root is difficult to determine.

The error message you're receiving suggests there might be a problem with executing a certain format. As such, the problem may originate from the hardware compatibility or the version/compatibility of the software (libraries or dependencies) you're using. There could be slight differences in the way Jetson Nano handles certain operations or reads certain formats compared to other systems.

Another area to check is permissions – ensure that the necessary permissions are present for executing scripts or accessing certain files.

If you're confident that everything is configured correctly on your device and with your software, I suggest you report the issue on NCNN's GitHub, as the developers might be able to provide more specific guidance.

As for the progress on this particular issue, I'm currently unaware of a specific fix. It might help to know if others using the Jetson Nano are encountering the same difficulties.

It's feedback and problem-solving attempts like yours that help refine and continuously improve libraries and their compatibility with various systems. Please don't hesitate to share your findings if you discover something useful!

Hope this helps.

**Comment by jeck00119** [comment]
I found the problem, the pnnx binary that ultralytics use isn't compatible with aarch64, we must build it to work

**Comment by jeck00119** [comment]
Could you @glenn-jocher add the pnnx binary for aarch64? The instructions for building the binary is on https://github.com/pnnx/pnnx.

**Comment by glenn-jocher** [comment]
@jeck00119 , thank you for identifying and addressing this issue regarding the pnnx binary compatibility with aarch64 systems. Your contribution is truly appreciated.

The idea of adding a pnnx binary for aarch64 that is compatible with YOLOv8 certainly warrants consideration. This would be beneficial, especially for developers working on aarch64 systems.

Before integrating your binary into the project, it is important that we go through the necessary validation and testing procedures to ensure compatibility and stability. We would also want to make sure the necessary documentation and build instructions are in place for future users.

We encourage you to perhaps maintain a fork with this build option and monitor its stability over time. This could be a good initial step toward wider adoption.
