### ISSUE TITLE
yolov8 NMS is per class?

### ISSUE THREAD

**Issue by ajtao** [ultralytics/ultralytics#3751]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I was doing some comparisons between bot-sort tracking performance using yolov8 vs. yolox and was finding that yolov8 was significantly behind yolox for tracking people (MOT task). The mAPs of yolov8 are clearly superior to mAP of yolox in my application, but the bot-sort tracking performance ends up being quite a bit worse, so i was trying to root cause this.

Something i'm observing is that for the multi-class case, i'm seeing more duplicates generated by yolov8 than with yolox. I *believe* that this might be because [yolov8 ](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/utils/ops.py#L243-L245)is doing per-class NMS whereas [yolox](https://github.com/NirAharon/BoT-SORT/blob/main/yolox/utils/boxes.py#L32-L62) is doing class-agnostic NMS.  In my case, i can get a single person having duplicate detections where the detections classified the person differently, for example one class would be "walking" and the other "standing", something like that. But the boxes heavily overlap, so i would have expected NMS to remove one of the boxes.

I haven't fully stepped through the code, but was wondering if you might be able to confirm this behavior? 

I'd like to try class-agnostic NMS in yolov8. I haven't figured out how to hack the code to do this yet, but if you have any suggestion for that, would be much obliged.

**Comment by ajtao** [comment]
Nevermind, just found the `agnostic` flag, so i'll try that!

**Comment by glenn-jocher** [comment]
@ajtao hello,

I'm glad you found the `agnostic` flag in YOLOv8! By setting the `agnostic` flag to True, you will enable class-agnostic NMS, which should help remove duplicate boxes even if they are classified differently. This can be useful in cases where objects heavily overlap and have different classifications.

I hope this helps with your tracking performance. If you have any further questions or need any additional assistance, please don't hesitate to ask.

Best regards,
Glenn Jocher

**Comment by MarkusFox90** [comment]
> Nevermind, just found the `agnostic` flag, so i'll try that!

Can you please mention where you found that flag? I can not find it anywhere.
