### ISSUE TITLE
What is the maximum value that "imgsz" parameter can be set to?

### ISSUE THREAD

**Issue by dejian-lc** [ultralytics/ultralytics#3752]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

What is the maximum value that "imgsz" parameter can be set to? I have seen people mentioning two common values, 640 and 1280.Does the model.val() method update the parameters of the model? I noticed that the run/train folder contains the same files as the run/val folder, such as val_batch0_pred.jpg.

**Comment by glenn-jocher** [comment]
@dejian-lc hi there! Thank you for your question about the "imgsz" parameter in YOLOv8.

The "imgsz" parameter determines the input image size for YOLOv8. It specifies the maximum size to which the input images are resized before being fed into the model. There isn't a hard limit on the maximum value for "imgsz", as it depends on your hardware limitations and the available video memory.

However, it's worth noting that larger values of "imgsz" can significantly increase the computational and memory requirements during training and inference. So, it's important to consider your hardware capabilities and resources when setting this parameter.

Regarding the "model.val()" method, it is used to validate the trained YOLOv8 model on a validation dataset. It does not update the parameters of the model. The files generated in the "run/val" folder, such as "val_batch0_pred.jpg", are the predictions made by the model during the validation process.

I hope this helps! If you have any more questions, feel free to ask.

**Comment by VdLMV** [comment]
@glenn-jocher: is the current default value (7680) for the max_wh parameter of the non_max_suppression function not a hard limit for CLI users running nms in non-agnostic mode?
