### ISSUE TITLE
How to delete the smoothing line  and smoothing label in results.png?

### ISSUE THREAD

**Issue by SuJackie** [ultralytics/ultralytics#3754]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to delete the smoothing line and smoothing label in results.png?

I have removed 472 in plotting.py but it didn't work
ax[i].plot(x, gaussian_filter1d(y, sigma=3), ':', label='smooth', linewidth=2)  # smoothing line

command used:
yolo cfg=default.yaml

**Comment by glenn-jocher** [comment]
@SuJackie hello! To remove the smoothing line and label in the `results.png` output, you will need to modify the `plotting.py` file.

In the `plot_one_box` function within `plotting.py`, locate the line that contains `ax[i].plot(x, gaussian_filter1d(y, sigma=3), ':', label='smooth', linewidth=2)`. You can simply comment out or remove this line to eliminate the smoothing line.

After making this change, re-run your command `yolo cfg=default.yaml` to generate the updated `results.png` output without the smoothing line and label.

Please note that modifying the code directly like this may affect other visualizations in case they rely on the same `plotting.py` code. If you need further assistance, please provide more context or additional details about your use case.
