### ISSUE TITLE
Resume training for YOLOv8-cls

### ISSUE THREAD

**Issue by uyolo1314** [ultralytics/ultralytics#3758]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Resuming training has not been implemented in YOLOv8-cls!!!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@uyolo1314 hello,

Thank you for reaching out. Currently, resuming training is not implemented in YOLOv8-cls. However, you can start training from where you left off by specifying the `--resume` flag in the command line interface. This flag allows you to resume training from a checkpoint saved during a previous training session.

I hope this clarifies your query. If you need further assistance, feel free to ask.

Best regards,

Glenn Jocher
