### ISSUE TITLE
Is there any way to choose the folder where I want the annotations resulting from the trained model?

### ISSUE THREAD

**Issue by Peanpepu** [ultralytics/ultralytics#3769]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I get the annotations resulting from an image detection it goes to the folder "predict". However, I'm using two different networks and I need the annotations from each network went to a different folder. I want all the detections from one network went to one folder I specify and all the detections from the other network went to another forlder instead of going for each frame to the folder "predict" and "predict2". 
I hope you can understand my question and sorry if not.

**Comment by glenn-jocher** [comment]
@Peanpepu yes you can use `project` and `name` arguments. See https://docs.ultralytics.com/modes/predict/

**Comment by Peanpepu** [comment]
Hi again.
I have now a problem with the real time detection. I'm trying to postprocess a video with two networks I have trained with yolov8 so I want speed for the detections. Once the detections are made I process the txt generated and create a fusion of both networks. The problem comes when I use the parameter Stream=True that generate that the networks don't create the txt files even if I have the parameters save_txt=True, project="Folder" and name="RGB_network".
I would like to know if there is any option to get the txt files even for a video detection and as fast as possible.
Thank you in advance.

**Comment by glenn-jocher** [comment]
@Peanpepu hi there,

Thank you for your question. 

Unfortunately, when the real-time detection is enabled by setting `stream=True`, the default behaviour of the YOLOv8 does not include writing individual annotation files to disk. This design decision is to ensure maximum processing speed during real-time operations.

However, you do have an alternative. You can modify the source code of the `predict` function in `models\experimental.py` to support the writing of detections to text files in real-time mode. Keep in mind that writing to disk is an I/O operation and it might slow down the prediction process somewhat.

I hope this clarifies your concerns. Feel free to let me know if you have any further questions about using YOLOv8.
