### ISSUE TITLE
Error while executing Yolov8 training in python

### ISSUE THREAD

**Issue by moahaimen** [ultralytics/ultralytics#3778]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

@glenn-jocher  as i worked an hour ago on Google Colab i noticed changes on Yolov8, and when executing in Python 
For more explaination i use a file that i write the code in and the executing it  using! python
"#from ultralytics.yolo.engine.model import YOLO
from ultralytics import YOLO

# # Load a model
model = YOLO("/content/yolov8/ultralytics/cfg/models/v8/yolov8.yaml")  # build a new model from scratch
# # model = YOLO("yolov8n.pt")  # load a pre-trained model (recommended for training)
#
# # Use the model
model.train(data="/content/dsw/data.yaml", epochs=150)  # train the model
metrics = model.val()  # evaluate model performance on the validation set
# results = model("bus.jpg")  # predict on an image
"
this error appears
"Traceback (most recent call last):
  File "/content/yolov8/developing_blocks.py", line 2, in <module>
    from ultralytics import YOLO
  File "/content/yolov8/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.engine.model import YOLO
  File "/content/yolov8/ultralytics/engine/model.py", line 8, in <module>
    from ultralytics.engine.exporter import Exporter
  File "/content/yolov8/ultralytics/engine/exporter.py", line 64, in <module>
    from ultralytics.nn.autobackend import check_class_names
  File "/content/yolov8/ultralytics/nn/__init__.py", line 3, in <module>
    from .tasks import (BaseModel, ClassificationModel, DetectionModel, SegmentationModel, attempt_load_one_weight,
  File "/content/yolov8/ultralytics/nn/tasks.py", line 14, in <module>
    from ultralytics.yolo.utils import DEFAULT_CFG_DICT, DEFAULT_CFG_KEYS, LOGGER, colorstr, emojis, yaml_load
  File "/content/yolov8/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/content/yolov8/ultralytics/yolo/v8/__init__.py", line 7, in <module>
    sys.modules['ultralytics.yolo.v8'] = importlib.import_module('ultralytics.models.yolo')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/content/yolov8/ultralytics/models/__init__.py", line 1, in <module>
    from .rtdetr import RTDETR
  File "/content/yolov8/ultralytics/models/rtdetr/__init__.py", line 3, in <module>
    from .model import RTDETR
  File "/content/yolov8/ultralytics/models/rtdetr/model.py", line 11, in <module>
    from ultralytics.engine.exporter import Exporter
ImportError: cannot import name 'Exporter' from partially initialized module 'ultralytics.engine.exporter' (most likely due to a circular import) (/content/yolov8/ultralytics/engine/exporter.py)"
" 
--------------------
 
i am executing in python because i am changing blocks and the file in path of content/yolov8/

**Comment by Kayzwer** [comment]
yolov8 change their project structure recently, try to pull the latest changes

**Comment by moahaimen** [comment]
@Kayzwer  i did install the latest, and i knew that changes happens but why i get this error when using python?

**Comment by Kayzwer** [comment]
@moahaimen hmm, I have no idea why, try git clone instead of using pip package.

**Comment by Laughing-q** [comment]
@moahaimen I'm not able to reproduce the issue for both pip install case and git clone case.
package with pip install 
![image](https://github.com/ultralytics/ultralytics/assets/61612323/3246e5be-345f-4b95-9059-602aed9f5110)
package with git clone and pip install -e.
![image](https://github.com/ultralytics/ultralytics/assets/61612323/7025dccf-3010-4722-9a33-1ebab3098540)

**Comment by moahaimen** [comment]
> @moahaimen I'm not able to reproduce the issue for both pip install case and git clone case. package with pip install ![image](https://user-images.githubusercontent.com/61612323/253873169-3246e5be-345f-4b95-9059-602aed9f5110.png) package with git clone and pip install -e. ![image](https://user-images.githubusercontent.com/61612323/253873285-7025dccf-3010-4722-9a33-1ebab3098540.png)

Sir not importing the yolo, the error while executing the training using python

**Comment by moahaimen** [comment]
@glenn-jocher  what i am doing is the same as last week, nothing changed from my side the difference it was working and now not,
i use this instruction ," !python /content/yolov8/my_training.py"
to call execution on a file inside the Yolov8 
the content of the file is "from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.yaml")  # build a new model from scratch
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

# Use the model
model.train(data="coco128.yaml", epochs=3)  # train the model
metrics = model.val()  # evaluate model performance on the validation set
results = model("https://ultralytics.com/images/bus.jpg")  # predict on an image
path = model.export(format="onnx")  # export the model to ONNX format"

and I use Google Colab  so i dont think the problem from my side, please help

**Comment by glenn-jocher** [comment]
@Kayzwer i understand that you're encountering issues executing your training script in Google Colab. This can certainly be frustrating, especially given that it was working as expected before.

The first thing that comes to mind is that there may have been updates or changes to the YOLOv8 repository that are causing compatibility issues with your current script. I would recommend pulling the latest version of YOLOv8 to make sure you are up-to-date with all the recent changes.

Also, the order of model loading in your script seems to be incorrect. You are first initiating a model from scratch using the "yolov8n.yaml" and then right after loading a pre-trained model using the "yolov8n.pt". These two lines of code are conflicting each other. You should be using either one depending on your need.

Moreover, ensure that the file paths in your script, including the paths to the model files and the data file, are correct and accessible in your Google Colab environment.

Please give these suggestions a try and let us know if the issue persists. We would be glad to provide further assistance.

**Comment by Kayzwer** [comment]
> @Kayzwer i understand that you're encountering issues executing your training script in Google Colab. This can certainly be frustrating, especially given that it was working as expected before.
> 
> The first thing that comes to mind is that there may have been updates or changes to the YOLOv8 repository that are causing compatibility issues with your current script. I would recommend pulling the latest version of YOLOv8 to make sure you are up-to-date with all the recent changes.
> 
> Also, the order of model loading in your script seems to be incorrect. You are first initiating a model from scratch using the "yolov8n.yaml" and then right after loading a pre-trained model using the "yolov8n.pt". These two lines of code are conflicting each other. You should be using either one depending on your need.
> 
> Moreover, ensure that the file paths in your script, including the paths to the model files and the data file, are correct and accessible in your Google Colab environment.
> 
> Please give these suggestions a try and let us know if the issue persists. We would be glad to provide further assistance.

Hi @glenn-jocher your AI reply seem to have problem when tagging person.

**Comment by glenn-jocher** [comment]
@Kayzwer i'm sorry for the confusion there. I understood your issue with running your training script on Google Colab. This could be due to some recent changes or updates in the YOLOv8 repository, leading to compatibility problems with your current script. I recommend updating to the latest version of YOLOv8 to align with all recent developments.

Another possible issue could be related to the sequence in which you're loading your models in your script. You're initially creating a new model with "yolov8n.yaml" and then immediately loading a pre-trained model using "yolov8n.pt". You should instead choose to use either one of these, depending on your requirement, to avoid conflicts.

Also, check the file paths in your script referring to model files and data files. Make sure these are correct and can be accessed in your Google Colab environment.

Please try these suggestions and let us know if you continue to face issues. We're here to support you.
