### ISSUE TITLE
Disable ClearML logging 

### ISSUE THREAD

**Issue by sham1lk** [ultralytics/ultralytics#3780]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hello! My team is writing a framework that integrates YOLOv8. In some cases it's great to use tools like ClearML, but in some cases we want to avoid using it. Is there a way not to use clearml and other integrated callbacks without deleting the libraries (As far as I understand, the use depends on whether it was possible to import the clearML library or not)? It might be possible to add the callbacks=[clearml, wandb, ...] argument.
Thank you for your hard work in creating this great framework!

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sham1lk yeah this is a good point. We can add the integrations to the settings (i.e. 'yolo settings') so that they can be enabled/disabled there. I'll add a TODO to track this.

**Comment by glenn-jocher** [comment]
@sham1lk I've opened #3790 for this. The PR has the disable capability now, I need to add a simple way to update the settings in general, perhaps in this PR or maybe in another one.

**Comment by sham1lk** [comment]
@glenn-jocher Thanks for your work! The current solution looks good. I believe it would be also useful to update multiple parameters via single command:
yolo set integrations.clearml True integrations.wandb False
or even using a list:
yolo set integrations clearml,wandb

**Comment by glenn-jocher** [comment]
Hello @sham1lk,

Thanks for your feedback and suggestions! Implementing the ability to update multiple parameters in a single command is indeed a great idea and can definitely improve the usability of the command line interface. Likewise, using a list to update the integrations could be another useful addition.

I will keep these ideas in mind as we continue to develop and improve YOLOv8. Your continual input is very much appreciated. As always, we strive to make our YOLO frameworks as user-friendly and flexible as possible.

Thanks again for your participation in this community and for helping improve YOLOv8. Cheers!

**Comment by glenn-jocher** [comment]
@sham1lk great news 😃! Your original issue may now be resolved ✅ in PR #3790 and published in a new `ultralytics 8.0.141` release. This PR adds a SettingsManager class that allows for direct viewing and modifying of Ultralytics settings:

<img width="955" alt="Screenshot 2023-07-23 at 16 11 23" src="https://github.com/ultralytics/ultralytics/assets/26833433/1427f5bd-52b6-445a-ab5b-e4c0eeccc10b">

For details see https://docs.ultralytics.com/quickstart

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!
