### ISSUE TITLE
bugs in ultralytics/examples/YOLOv8-ONNXRuntime-CPP /inference.cpp

### ISSUE THREAD

**Issue by BobDLA** [ultralytics/ultralytics#3787]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

[ultralytics](https://github.com/ultralytics/ultralytics/tree/main)/[examples](https://github.com/ultralytics/ultralytics/tree/main/examples)/[YOLOv8-ONNXRuntime-CPP](https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-ONNXRuntime-CPP)
/inference.cpp

1. in this file the was not assigned by classesNum = iParams.classesNum; So the code can't get empty output.
2. for compile on ubuntu gcc, should add several typname , for example
	typename std::remove_pointer<N>::type* output = outputTensor.front().GetTensorMutableData< std::remove_pointer<N>::type>();
shoud be
	std::vector<int64_t>outputNodeDims = tensor_info.GetShape();
	typename std::remove_pointer<N>::type* output = outputTensor.front().GetTensorMutableData<typename std::remove_pointer<N>::type>();

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@BobDLA hi, thank you for your feature suggestion on how to improve YOLO 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
