### ISSUE TITLE
Result in json format

### ISSUE THREAD

**Issue by Joe-KI333** [ultralytics/ultralytics#379]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I would like to get my prediction result in json format.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Robotatron** [comment]
1) Agree, that would be very helpful
2) Even more so, if the prediction JSON format would be in COCO format

**Comment by Joe-KI333** [comment]
> 

Thanks for the reply I want something like this


@robmarkcole sure, that sounds reasonable. Their format is here:

{'predictions': [{'x_max': 819, 'x_min': 633, 'y_min': 354, 'confidence': 99, 'label': 'dog', 'y_max': 546}, {'x_max': 601, 'x_min': 440, 'y_min': 116, 'confidence': 99, 'label': 'person', 'y_max': 516}, {'x_max': 445, 'x_min': 295, 'y_min': 84, 'confidence': 99, 'label': 'person', 'y_max': 514}], 'success': True}

**Comment by ichsan2895** [comment]
I think it more better the result in pandas format, then you can convert it to specific format like csv, json, and even better converted to SHP 💯 

Just like yolov5 from torch hub that convert result in pandas format for object detection. But It wont applied for segmentation..
![image](https://user-images.githubusercontent.com/60387342/212621293-9dd9ef05-3361-4045-904f-8cb78c0c6b6c.png)

**Comment by robmarkcole** [comment]
Pandas is convenient, but then does add this fairly large dependency. If you have json it can be used to create a pandas data frame by the user

**Comment by AyushExel** [comment]
We are working on much better interaction with results here ->https://github.com/ultralytics/ultralytics/pull/314
It'll be released soon.
