### ISSUE TITLE
How can I switch to version 8.0.134

### ISSUE THREAD

**Issue by lindsayshuo** [ultralytics/ultralytics#3795]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

How can I switch to version 8.0.134

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Kayzwer** [comment]
@lindsayshuo if you get the project from pip then just do `pip install -U ultralytics`, if you cloned from github then just do `git pull` && `pip install -e .`.

**Comment by glenn-jocher** [comment]
Hello @Kayzwer, 

Thanks for reaching out. To use a specific version of Ultralytics YOLOv8, you certainly can use version control systems provided by Python pip package manager and git. If you have installed the project from pip, you can upgrade it to the desired version by running `pip install --upgrade ultralytics==8.0.134`.

On the other hand, if you cloned the repository from GitHub, you can checkout to the specific version you want. Simply pull the latest updates from the repo by running `git pull`, then checkout to the desired version using `git checkout tags/<tag_name>`, replace `<tag_name>` with the version number, in your case it would be `8.0.134`. Lastly, run `pip install -e .` to install the packages related to that version.

These steps should allow you to switch to Ultralytics YOLOv8 version `8.0.134` whether you've installed it via pip or cloned it from our Github repository. Let us know if you have other questions or run into any issues!
