### ISSUE TITLE
Get pred[:, :4] = ops.scale_boxes(img.shape[2:], pred[:, :4], orig_img.shape)

### ISSUE THREAD

**Issue by chelsea456** [ultralytics/ultralytics#3796]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hi sir!! how to get boxes in result = model(img)
ultralytics.yolo.engine.results.Results object with attributes:
boxes: ultralytics.yolo.engine.results.Boxes object
keypoints: None
keys: ['boxes']
masks: None
names: {0: 'cap'}
orig_img: array([[[ 6, 14,  0],.....

**Comment by glenn-jocher** [comment]
@chelsea456 hello, thank you for reaching out!

Regarding your question on accessing bounding box information after making predictions with a YOLOv8 model, you can access the 'boxes' attribute of the 'Results' object. 

When you perform model inference with `result = model(img)`, a 'Results' object is returned that contains various attributes, including 'boxes' which holds the bounding box information you're interested in.

The 'boxes' attribute is an object itself which contains the coordinates and confidences of each detected object in your image. 

To access the bounding boxes, you can use `result.boxes`, which should yield the bounding box information for your image.

Please be aware that the returned box coordinates are normalized relative to the image size. If you wish to scale these back to the original image size, you would need to multiply the normalized coordinates by the original image dimensions.

I hope this clears up your question. If you have any further questions or need clarification, please feel free to ask!
