### ISSUE TITLE
Specify ONNX OpSet version on export

### ISSUE THREAD

**Issue by sstainba** [ultralytics/ultralytics#380]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When exporting to an ONNX model, is there a way to provide a target OpSet version?  The current version is not supported by the .NET ONNX Runtime.

**Comment by knoppmyth** [comment]
Yes, this works for me. Note, I'm using OpenCV not .NET.:
`yolo mode=export model=runs/detect/train/weights/best.pt imgsz=[640,640] format=onnx opset=11`

**Comment by sstainba** [comment]
> Yes, this works for me. Note, I'm using OpenCV not .NET.: `yolo mode=export model=runs/detect/train/weights/best.pt imgsz=[640,640] format=onnx opset=11`

Awesome.  Thanks!

**Comment by knoppmyth** [comment]
You're welcome.

**Comment by pderrenger** [comment]
@knoppmyth feel free to reach out if you have any more questions or need further assistance. Happy to help!
