### ISSUE TITLE
binary masks in fast SAM

### ISSUE THREAD

**Issue by carlosjulioph** [ultralytics/ultralytics#3800]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Once the inference is made and the result is displayed, how can I "loop" each of the detected objects to extract features such as area? Or how could I assign an index to each detected object?

**Comment by glenn-jocher** [comment]
@carlosjulioph hello, and thank you for your interesting question.

Within the inference results returned by YOLOv8, individual detections are available and can indeed be looped over to extract additional details such as area, centroids, and more. 

Firstly, the model inference procedure returns predictions as an Nx6 tensor. Each row of the tensor is one object detection bounding box, with the format `[x, y, width, height, confidence, class]`. Each of these fields provides specific information about the detected object.

For each bounding box:

- The `x` and `y` coordinates point to the center of the box.
- The `width` and `height` values refer to the bounding box's dimensions.
- The `confidence` score states the model's certainty about the detection.
- Finally, the `class` value represents the object's class as determined by the model.

To get additional object details such as area, you can create a loop to go over each detected object (represented by each row in the tensor) and use the bounding box dimensions to calculate the area. The area can be calculated as `width * height`.

Regarding assigning an index to each detected object, the order of the detections in the tensor could be used as an index where the first detection is index 0, the second detection is index 1, and so forth. Python's enumerate function can be used for this purpose while iterating over the tensor.

Remember that this approach requires direct interaction with model outputs, so it would be best to include this functionality within a custom script or function to achieve your project-specific targets.

I hope this information helps. Please don't hesitate to reach out if you have any further questions!

**Comment by carlosjulioph** [comment]
Hello, thanks for answering.
I use this code:

`from ultralytics import FastSAM
from ultralytics.models.fastsam import FastSAMPrompt

# Define image path and inference device
IMAGE_PATH = 'cat.jpg'
DEVICE = 'cpu'

# Create a FastSAM model
model = FastSAM('FastSAM-x.pt')  # or FastSAM-x.pt

# Run inference on an image
everything_results = model(IMAGE_PATH,
                           device=DEVICE,
                           retina_masks=True,
                           imgsz=1024,
                           conf=0.4,
                           iou=0.9)

prompt_process = FastSAMPrompt(IMAGE_PATH, everything_results, device=DEVICE)

# Everything prompt
ann = prompt_process.everything_prompt()
prompt_process.plot(annotations=ann, output='salida/')

`
What lines of code should I add to access each detection?

**Comment by glenn-jocher** [comment]
@carlosjulioph hi, thanks for reaching out with your question.

Based on the code you provided, you're using the `FastSAM` model to perform inference on an image and then visualizing the output. If you want to access each individual detection, you'll need to interact with the `everything_results` variable.

The `everything_results` object essentially contains all the information from the model's inference including: bounding box coordinates, classes, scores and other details. Each detection is represented as a separate instance within this collection.

If you want to loop over each detection and extract specific details, you would use a for loop directly on the `everything_results` object. The details of each detected object can then be extracted and manipulated as needed within this loop.

Without providing explicit code, I can't show you the exact lines to add. However, the overall process would be to initiate a for loop on the `everything_results` object and use the aforementioned details within the loop to operate on the detections. You should be able to extract or calculate any necessary features in that context. 

Hope this helps and feel free to ask if you have any other questions!

**Comment by 3DMiller** [comment]
I am also trying to figure out how to get the masks coordinates. Any luck with this?

**Comment by glenn-jocher** [comment]
@3DMiller for obtaining mask coordinates from FastSAM predictions, the `everything_results` object should contain both the binary masks and bounding box detections. The binary masks are typically returned in a separate key alongside the detections. If retina masks are activated during inference, which is indicated in your code snippet, the output should include the mask data for each detected object.

To access the mask coordinates, you would process the 'masks' key within the `everything_results`. These masks are typically represented as binary (0 or 1) pixel matrices corresponding to the size of the input image, where 1 indicates the pixels belonging to the detected object.

Remember that binary mask matrices aren't coordinate lists; they represent an object's shape as it appears on the grid of the image. To get the coordinates (such as the contour points of the mask), you would need to process this binary matrix using image processing techniques like contour detection, which can be done using libraries such as OpenCV.

After obtaining the masks, you could loop over them to apply contour detection and extract the list of coordinates that define the outline of each object. Each mask can be processed independently to retrieve the coordinates for each detected object.

Please be aware that specific instructions on how to manipulate these masks go beyond the scope of this channel. However, the general approach described above should set you on the right path. If you are not experienced with image processing, you may want to look into tutorials or documentation that cover operations on binary images and how to find and use contours.

**Comment by 3DMiller** [comment]
Hello, I will try this approach and see how it works. Thank you.

**Comment by glenn-jocher** [comment]
@3DMiller you're welcome! Experimenting with the approach should indeed help. Feel free to reach out again if you encounter any challenges or have more questions. Happy coding, and best of luck with your FastSAM endeavors!

**Comment by med-tim** [comment]
I have followed these steps but cannot access the masks either. The everything_results are of type: <class 'ultralytics.engine.results.Results'>. And given that,  I cannot access a masks "key". 


Given this code (not shown is that that "frame" was extracted using cap.read() from cv2):

                source = frame

                model = FastSAM('FastSAM-x.pt')  # or FastSAM-s.pt

                #get size of frame
                imgsz_frame = source.shape[0]

                everything_results = model(source, device='cpu', retina_masks=True, imgsz=imgsz_frame, conf=0.1, iou=0.9)

                prompt_process = FastSAMPrompt(source, everything_results, device='cpu')
                

                # Bbox default shape [0,0,0,0] -> [x1,y1,x2,y2]
                ann = prompt_process.box_prompt(bbox=[x1, y1, x2, y2])
                
                #display the segmented image
                prompt_process.plot(annotations=ann, output='./')




How can I get the masks of the object that was detected in the box that I provided? In the code below, ann is returned as a list which looks like this:

[ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
masks: ultralytics.engine.results.Masks object
names: {0: 'object'}
obb: None
orig_img: array([[[205, 208, 194],
        [205, 208, 194],
        [206, 207, 194],
        ...,
        [195, 180, 178],
        [193, 178, 176],
        [189, 174, 173]],

       [[205, 208, 194],
...
path: 'image0.jpg'
probs: None
save_dir: None
speed: {'preprocess': 10.263919830322266, 'inference': 9070.787191390991, 'postprocess': 202.7609348297119}]

**Comment by abrichr** [comment]
@carlosjulioph @3DMiller 

From https://github.com/OpenAdaptAI/OpenAdapt/blob/83131e41e9cc58e7e52912a55ef2dca6662e3909/openadapt/adapters/ultralytics.py:

```
def fetch_segmented_image(
    image: Image,
    model_name: str = MODEL_NAME,
    # TODO: inject from config
    device='cpu',
    retina_masks=True,
    imgsz=1024,
    conf=0.4,
    iou=0.9,
) -> Image:
    """Segment a PIL.Image using ultralytics Fast Segment Anything.

    Args:
        image: The input image to be segmented.
        model_name: The name of the model to use. Must be FastSAM-s.pt or FastSAM-x.pt.
        TODO: document remaining params

    Returns:
        The segmented image as a PIL Image.
    """

    assert model_name in MODEL_NAMES, (model_name, MODEL_NAMES)

    model = FastSAM(model_name)
    
    # Run inference on image
    everything_results = model(
        image,
        device=device,
        retina_masks=retina_masks,
        imgsz=imgsz,
        conf=conf,
        iou=iou,
    )

    # Prepare a Prompt Process object
    prompt_process = FastSAMPrompt(image, everything_results, device='cpu')

    # Everything prompt
    ann = prompt_process.everything_prompt()

    assert len(ann) == 1, len(ann)
    ann_item = ann[0]

    import numpy as np
    ann_item.orig_img = np.ones(ann_item.orig_img.shape)

    with TemporaryDirectory() as tmp_dir:
        ann_item.path = ann_item.path.replace('.jpg', '.png')  # Force the output format to PNG
        prompt_process.plot(
            [ann_item],
            tmp_dir,
            with_contours=False,
            retina=False,
        )
        result_name = os.path.basename(ann_item.path)
        result_name = os.path.basename(ann_item.path).replace('.jpg', '.png')
        logger.info(f"{ann_item.path=}")
        image_path = Path(tmp_dir) / result_name
        image = Image.open(image_path)
        os.remove(image_path)
    return image
```

From https://github.com/OpenAdaptAI/OpenAdapt/blob/5df193ab5d4b3846f9c88c0d5da3477ba4b2f211/openadapt/vision.py:

```
def process_image_for_masks(segmented_image: Image.Image) -> list[np.ndarray]:
    """
    Process the image to find unique masks based on color channels.

    Args:
        segmented_image: A PIL.Image object of the segmented image.

    Returns:
        A list of numpy.ndarrays, each representing a unique mask.
    """
    logger.info(f"starting...")
    segmented_image_np = np.array(segmented_image)

    # Assume the last channel is the alpha channel if the image has 4 channels
    if segmented_image_np.shape[2] == 4:
        segmented_image_np = segmented_image_np[:, :, :3]

    # Find unique colors in the image, each unique color corresponds to a unique mask
    unique_colors = np.unique(segmented_image_np.reshape(-1, segmented_image_np.shape[2]), axis=0)
    logger.info(f"{len(unique_colors)=}")

    masks = []
    for color in unique_colors:
        # Create a mask for each unique color
        mask = np.all(segmented_image_np == color, axis=-1)
        masks.append(mask)

    logger.info(f"{len(masks)=}")
    return masks


def filter_masks_by_size(
    masks: list[np.ndarray],
    min_mask_size: tuple[int, int] = (15, 15),
) -> list[np.ndarray]:
    # Compute convex hull and filter masks based on the minimum size requirements
    size_filtered_masks = []
    for mask in masks:
        hull = morphology.convex_hull_image(mask)
        # Find the bounding box of the convex hull
        coords = np.argwhere(hull)
        if coords.size > 0:
            y_min, x_min = coords.min(axis=0)
            y_max, x_max = coords.max(axis=0)
            hull_height = y_max - y_min + 1
            hull_width = x_max - x_min + 1
            if hull_height >= min_mask_size[0] and hull_width >= min_mask_size[1]:
                size_filtered_masks.append(mask)
    return size_filtered_masks
```

Usage:

```
segmented_image = fetch_segmented_image(image)
masks = process_image_for_masks(segmented_image)
min_size_masks = filter_masks_by_size(masks)
```
