### ISSUE TITLE
How to get pixels related to an object with Yolov8 segmentation ? 

### ISSUE THREAD

**Issue by Smoows** [ultralytics/ultralytics#3801]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm using YoloV8 for segmentation and I want to keep the object detected only. Is there a way to save in a list all pixels related to the object ?

**Comment by glenn-jocher** [comment]
@Smoows hi there,

Thanks for reaching out about using YOLOv8 for segmentation tasks. 

To obtain the pixels related to a detected object in your segmentation task, you can use the output of the model, which includes information about the bounding boxes of detected objects. The bounding box details encompass the coordinates of the top left corner, as well as the width and height of the box. 

Once you have this bounding box information, you can use it to extract the region of your input image that corresponds to the detected object. Every pixel inside this region is associated with the detected object. 

You can then iterate over this extracted region and save the pixel coordinates in a list or any other data structure that suits your application's needs.

Happy coding!

**Comment by CesarQD98** [comment]
Hey hello guys! 👋 

Just a quick question: what if I want to grab all the points that make the contour of the segmented object? I'd like to calculate the number of pixels inside this contour, that's something I managed to do by doing:

`points = masks[0].xy[0].astype(int)`

This line grabs the points related to a detected class, but I haven't been able to match it with its corresponding class. Can't find like an attribute that gives me something like:

`(cls, xy1, xy2, ...)`

So I know that these pixel coordinates correspond to class `cls`. What I'm really struggling now is to get the points that corresponds to an specific class detected in a frame that comes from a video source.

Thanks in advance!

**Comment by CesarQD98** [comment]
I've just found out a way to do this...

```python
for i, box in enumerate(results[0].boxes):
            detected_class = int(box.cls.cpu())
            if results[0].masks:
                points_rollers = results[0].masks[i].xy[0].astype(int)

                # names: {0: 'mass', 1: 'filter', 2: 'splitter', 3: 'rollers'}
                if detected_class == 0:
                    data_points = [tuple(elem) for elem in points_rollers]
                    cv2.fillPoly(bg_img, np.array([data_points]), (255, 255, 255))
                    bg_img_gray = cv2.cvtColor(bg_img, cv2.COLOR_BGR2GRAY)
                    cv2.imshow("rollers", bg_img_gray)
```

Even though, I wonder if there's a dedicated way to obtain this data as `(cls, xy1, xy2, ...)`.

**Comment by glenn-jocher** [comment]
@CesarQD98 hi there,

Great job on finding a solution! Currently in YOLOv8, each bounding box and its corresponding mask are treated separately in the results. So there isn't a direct attribute to provide data in the format `(cls, xy1, xy2, ...)`. Each detected object's class, bounding box and mask can be iterated through separately as you did in your code.

However, you can compile this data into your desired format manually. You would keep iterating over the results as you're currently doing, and for each object, you would make a tuple or a similar data structure. This tuple would include the class of the detected object (which you can obtain from `box.cls`) and the contour points of the segmented mask, which you got from `results[0].masks[i].xy[0].astype(int)`.

This way, for each object, you would end up with a data structure that includes the class of the object and the contour points of the corresponding segmentation mask.

Again, great work on exploring YOLOv8 and coming up with a solution for your task. Cheers!

**Comment by polinamalova0** [comment]
hey, a quick question regarding to the same problem: why `mask.xy[0]` gives off the parameters that are not integers? How to solve it? Shouldn't pixel coordinates be purely integers? or is it just me and something is wrong with my prediction results? Thanks in advance!

**Comment by glenn-jocher** [comment]
Hey @polinamalova0,

The `mask.xy[0]` values are typically in floating-point format because they represent normalized coordinates relative to the image dimensions. This allows the coordinates to be more precise and adaptable to different image sizes.

If you need these coordinates as integers for pixel operations, you can convert them by scaling according to your image dimensions and then using `astype(int)` to convert to integers. Here’s a quick example:

```python
# Assuming 'img_width' and 'img_height' are the dimensions of your image
int_coords = (mask.xy[0] * [img_width, img_height]).astype(int)
```

This should give you the pixel coordinates as integers. Hope this helps! 😊
