### ISSUE TITLE
Will be more classification models added into ultralytics? 

### ISSUE THREAD

**Issue by darouwan** [ultralytics/ultralytics#3806]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

As ultralytics is an awesome model hub for YOLO and other object detection models, or classification model based on YOLO. 
So, is there any plan to add more classification models, like Xception, Inception, Resnet, etc? 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@darouwan thank you for your interest in expanding the Ultralytics model hub and for your willingness to contribute through a PR! 

At present, our primary focus is on enhancing the capabilities of our YOLO models, including YOLOv8. These models currently support various computer vision tasks such as detection, segmentation, classification, and pose/keypoint estimation. As you've mentioned, we use classification as part of the YOLO architecture, which has its own internal classification model.

Integrating more standalone classification models like Xception, Inception, Resnet, etc. into Ultralytics is currently not in our immediate roadmap. Our main priority is improving and optimizing the existing YOLO architectures.

However, we understand the value of including varied model architectures. Hence, we always encourage and welcome contributions from the community. If you wish to start working on integrating these models into Ultralytics as a contributor, your efforts would be very much appreciated. Once you're ready, please feel free to submit a PR, and we can proceed with the review process.

Thank you for your enthusiasm in contributing to the YOLOv8 and Ultralytics ecosystem!
