### ISSUE TITLE
Dense oriented objects and NMS

### ISSUE THREAD

**Issue by mehran66** [ultralytics/ultralytics#3819]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am currently facing an issue with instance segmentation while predicting objects that are closely aligned and rotated in the same direction. When the objects are oriented horizontally or vertically, the non-maximum suppression (NMS) works well, but when they are rotated similarly, their bounding boxes exhibit significant overlap. To ensure accurate predictions for all objects, I have to set a very low IOU threshold (e.g., 0.05).

I would appreciate any suggestions or alternative solutions to improve the instance segmentation performance in such scenarios. Thank you!

**Comment by Laughing-q** [comment]
@mehran66 hi, in your case I think probably using mask iou for nms would be a better option.

**Comment by glenn-jocher** [comment]
@mehran66 @Laughing-q sounds like a good use case for OBB!

**Comment by mehran66** [comment]
@Laughing-q Thank-you! currently I am using the `non_max_suppression` function that only consider bboxes. Do you recommend to first use the `non_max_suppression` with a very low IOU and then run the `mask_iou` function to remove the redundant predictions?

**Comment by jvsluis** [comment]
@glenn-jocher I'm also working on a project that has a similar problem which requires OBB. I saw in issue #624 that there are plans to implement OBB. Is this being implemented already? Is there a timeline on when this could be completed? Otherwise, I'm currently investigating how to implement this myself.

**Comment by glenn-jocher** [comment]
Hi @mehran66, thank you for reaching out. I can confirm that there are indeed plans to implement OBB in YOLOv8. However, as of now, I'm unable to provide an exact timeline for the completion of this feature. Our development process often involves a diverse range of tasks and projects, and the scheduling can depend on the principles of agile development. While we're very aware of the significance of this feature for users like you, it's challenging to promise specific delivery dates.

That being said, we are terrifically excited about the addition of OBB and are giving it the due priority in our development pipeline. Also, as an open-source project, we highly appreciate and encourage contributions. If you feel you can advance the implementation of this feature, we would be very grateful for your involvement.

We'll ensure to communicate any major updates around this feature in the future. Thank you for your understanding and your support for the YOLOv8 project.

**Comment by Laughing-q** [comment]
@mehran66 wait, I'm a little confused, when you say the bounding boxes exhibit significant overlap do you mean you want to keep these or remove these? sound like you want to keep these right? but in fact I think lower iou threshold to nms would make it easier to remove overlapped bboxes rather than keep them.

**Comment by glenn-jocher** [comment]
Hi @mehran66,

No worries at all, we're here to help! Your idea of setting a higher NMS IOU threshold to keep more overlapping boxes and then using a post-processing step to account for excessive overlap sounds like a good approach for tightly packed, similarly oriented objects. Just keep in mind that the trade-off is potentially more false positives, but you might be able to filter those out in your post-processing step.

We appreciate your feedback and efforts in tackling this challenge. If you encounter any further issues or have additional questions, please don't hesitate to ask. Best of luck with your project!
