### ISSUE TITLE
  Label size

### ISSUE THREAD

**Issue by haoaZ** [ultralytics/ultralytics#3829]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

May I ask how to adjust the size of labels during inference? The default size affects the analysis of inference output.

**Comment by haoaZ** [comment]
> You can modify the `line_width` parameter when running on inference. For example: ` model.predict(source = "image.jpg", line_width = 2)`
> 
> You can find more inference arguments in the following link: []inference_parameters(https://docs.ultralytics.com/modes/predict/#inference-arguments)

Oh, thank you. I was careless and didn't look carefully，lol

**Comment by glenn-jocher** [comment]
@haoaZ no problem at all, it's easy to miss! Happy to hear that the advice about adjusting the `line_width` parameter provided fits your needs. Take your time exploring all the available inference parameters, they are designed to offer flexibility in using YOLOv8. Enjoy your work with YOLOv8 and feel free to ask if you have any more questions. The YOLO community and Ultralytics team are here to assist you. Happy coding!
