### ISSUE TITLE
the plots

### ISSUE THREAD

**Issue by hoangnhien2411** [ultralytics/ultralytics#383]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

After training classification, why  I don't have the plots such as F1_curve, P_curve, and confusion matrix ... in my runs folder?

**Comment by sstainba** [comment]
I just pulled the new image and there were a few exceptions from plot.py at the start of my training session.  So I'm guessing they broke it in the last day or two.

**Comment by AyushExel** [comment]
We'll rectify this soon! Thanks for reporting
