### ISSUE TITLE
save_txt in different location 

### ISSUE THREAD

**Issue by sourabmaity** [ultralytics/ultralytics#3832]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to save text file of my prediction in a different directory instead of PWD. 

How to do that ?

### Additional

My code :
`results = model(file,conf=0.2,save_txt=True)`

**Comment by glenn-jocher** [comment]
@sourabmaity use `project` and `name` arguments to save results to `project/name`.

**Comment by sourabmaity** [comment]
I used this but it's creating a new folder with the same name adding 2,3 and it's saving there within another folder labels 
Used code,
`results = model.predict(file,conf=0.2,save_txt=True,project="/content", name="resu_so")`

![image](https://github.com/ultralytics/ultralytics/assets/62734958/643cd3e7-7d42-48f4-9f03-4f3d2fa3c502)

How to solve this?

**Comment by Laughing-q** [comment]
@sourabmaity add `exist_ok=True` if you always want to save it in the same folder.

**Comment by sourabmaity** [comment]
Thanks to all

**Comment by glenn-jocher** [comment]
@sourabmaity you're very welcome! We're glad to have been able to assist you. If you have any other questions or need further clarification, please don't hesitate to ask. The Ultralytics team is always here to help. Remember, the beauty and success of YOLOv8 is not just the work of one but the culmination of contributions from the entire YOLO community.

**Comment by Laughing-q** [comment]
@sourabmaity I'm closing the issue since the solution works to you. :) Please feel free to reopen it if you have any related issues. :)
