### ISSUE TITLE
Frame rate getting lower over time using tracker

### ISSUE THREAD

**Issue by omrir** [ultralytics/ultralytics#3833]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I'm running the tracker on my pc (no GPU). It seems that in the first few minutes of running the frame rate is about 10Hz.
After 1 hour or so, the frame rate goes down to about 2Hz.
Number of objects in the frame did not changed.
Also, restarting the tracker, the frame rate goes back to about 10Hz.

### Minimal Reproducible Example

from ultralytics import YOLO

model = YOLO('yolov8n.pt')

results = model.track(source=0, show=True)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@omrir try `stream=True`. See https://docs.ultralytics.com/modes/predict/
