### ISSUE TITLE
Multi-GPU training

### ISSUE THREAD

**Issue by sabarezaeii** [ultralytics/ultralytics#3838]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[8], line 1
----> 1 model.train(data='data/thirdSet.yaml', epochs=100, imgsz=640, device=[0,1,2,3])

File D:\python\users\Zahra\anaconda3\envs\yolov8-gpu-env\lib\site-packages\ultralytics\engine\model.py:367, in YOLO.train(self, **kwargs)
    365     overrides['resume'] = self.ckpt_path
    366 self.task = overrides.get('task') or self.task
--> 367 self.trainer = TASK_MAP[self.task][1](overrides=overrides, _callbacks=self.callbacks)
    368 if not overrides.get('resume'):  # manually set model only if not resuming
    369     self.trainer.model = self.trainer.get_model(weights=self.model if self.ckpt else None, cfg=self.model.yaml)

File D:\python\users\Zahra\anaconda3\envs\yolov8-gpu-env\lib\site-packages\ultralytics\engine\trainer.py:83, in BaseTrainer.__init__(self, cfg, overrides, _callbacks)
     75 """
     76 Initializes the BaseTrainer class.
     77 
   (...)
     80     overrides (dict, optional): Configuration overrides. Defaults to None.
     81 """
     82 self.args = get_cfg(cfg, overrides)
---> 83 self.device = select_device(self.args.device, self.args.batch)
     84 self.check_resume()
     85 self.validator = None

File D:\python\users\Zahra\anaconda3\envs\yolov8-gpu-env\lib\site-packages\ultralytics\utils\torch_utils.py:82, in select_device(device, batch, newline, verbose)
     79         LOGGER.info(s)
     80         install = 'See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no ' \
     81                   'CUDA devices are seen by torch.\n' if torch.cuda.device_count() == 0 else ''
---> 82         raise ValueError(f"Invalid CUDA 'device={device}' requested."
     83                          f" Use 'device=cpu' or pass valid CUDA device(s) if available,"
     84                          f" i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.\n"
     85                          f'\ntorch.cuda.is_available(): {torch.cuda.is_available()}'
     86                          f'\ntorch.cuda.device_count(): {torch.cuda.device_count()}'
     87                          f"\nos.environ['CUDA_VISIBLE_DEVICES']: {visible}\n"
     88                          f'{install}')
     90 if not cpu and not mps and torch.cuda.is_available():  # prefer GPU if available
     91     devices = device.split(',') if device else '0'  # range(torch.cuda.device_count())  # i.e. 0,1,6,7

ValueError: Invalid CUDA 'device=0,1,2,3' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): True
torch.cuda.device_count(): 1
os.environ['CUDA_VISIBLE_DEVICES']: 0,1,2,3

### Environment

Ultralytics YOLOv8.0.137  Python-3.9.17 torch-2.0.1 

### Minimal Reproducible Example

model=YOLO('yolov8l.pt')
model.train(data='data/thirdSet.yaml', epochs=100, imgsz=640, device=[0,1,2,3])

### Additional

I am trying to get all my 4 tesla v100 GPUs working while I am training my YOLOv8 model. when i use device=0 or device=1 etc, it works, I allows training with a single GPU, But when I try to use more than one GPU device=0,1 or device=[0,1] (device=[0,1,2,3]), it doesn't work. I tried with different syntax and I also tried downgrading pytorch version, none of those worked. 

Can you help me with this issue?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Kamlesh364** [comment]
@sabarezaeii Please, if all the GPUs are accessible, by-
 `torch.cuda.device_count()`
output must be-
`4`

**Comment by glenn-jocher** [comment]
Hi @sabarezaeii, it seems like not all of your GPUs are recognized by PyTorch. From your logs, I can see that `torch.cuda.device_count()` returns 1 instead of 4. This means that PyTorch is only detecting one of your GPUs. To make sure that all of your GPUs are recognized by PyTorch, you can try running `torch.cuda.device_count()`, which should return 4 as you have 4 GPUs. If it doesn't, the issue might be with your CUDA setup, and all the GPUs might not be properly configured or accessible. Please check your environment setup and make sure all GPUs are correctly installed and can be detected by PyTorch.

**Comment by sabarezaeii** [comment]
This is really weird, when I activate my yolov8 environment, and use torch.cuda.device_count() both in the anaconda prompt and also in jupyter, in both cases it shows 4! actually torch can see all my 4 GPUS, but it cannot see that while I am running my yolov8 model training!!!


![image](https://github.com/ultralytics/ultralytics/assets/122474907/f56d5f11-3a23-42f6-a22f-1c3e3763b2b7)
![image](https://github.com/ultralytics/ultralytics/assets/122474907/989a6e6f-e4c6-41d7-8e91-7381ce4623eb)

**Comment by sabarezaeii** [comment]
It is the new ERROR I am seeing today:


-----------------------------------------------------------------------------------------------------------------------------

Ultralytics YOLOv8.0.137  Python-3.9.17 torch-2.0.1 CUDA:0 (Tesla V100-PCIE-32GB, 32633MiB)
                                                      CUDA:1 (Tesla V100-PCIE-32GB, 32633MiB)
                                                      CUDA:2 (Tesla V100-PCIE-32GB, 32633MiB)
                                                      CUDA:3 (Tesla V100-PCIE-32GB, 32633MiB)
engine\trainer: task=detect, mode=train, model=yolov8l.pt, data=data/thirdSet.yaml, epochs=100, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=[0, 1, 2, 3], workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\train5
Overriding model.yaml nc=80 with nc=4

                   from  n    params  module                                       arguments                     
  0                  -1  1      1856  ultralytics.nn.modules.conv.Conv             [3, 64, 3, 2]                 
  1                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  2                  -1  3    279808  ultralytics.nn.modules.block.C2f             [128, 128, 3, True]           
  3                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  4                  -1  6   2101248  ultralytics.nn.modules.block.C2f             [256, 256, 6, True]           
  5                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]              
  6                  -1  6   8396800  ultralytics.nn.modules.block.C2f             [512, 512, 6, True]           
  7                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]              
  8                  -1  3   4461568  ultralytics.nn.modules.block.C2f             [512, 512, 3, True]           
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  3   4723712  ultralytics.nn.modules.block.C2f             [1024, 512, 3]                
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  3   1247744  ultralytics.nn.modules.block.C2f             [768, 256, 3]                 
 16                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  3   4592640  ultralytics.nn.modules.block.C2f             [768, 512, 3]                 
 19                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  3   4723712  ultralytics.nn.modules.block.C2f             [1024, 512, 3]                
 22        [15, 18, 21]  1   5585884  ultralytics.nn.modules.head.Detect           [4, [256, 512, 512]]          
Model summary: 365 layers, 43632924 parameters, 43632908 gradients

Transferred 589/595 items from pretrained weights
DDP command: ['D:\\python\\users\\Zahra\\anaconda3\\envs\\yolov8-gpu-env\\python.exe', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '58736', 'C:\\Users\\zbry8h\\AppData\\Roaming\\Ultralytics\\DDP\\_temp_dk8q2p2k2410653032112.py']
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
Cell In[6], line 1
----> 1 model.train(data='data/thirdSet.yaml', epochs=100, imgsz=640, device=[0,1,2,3])

File D:\python\users\Zahra\anaconda3\envs\yolov8-gpu-env\lib\site-packages\ultralytics\engine\model.py:372, in YOLO.train(self, **kwargs)
    370     self.model = self.trainer.model
    371 self.trainer.hub_session = self.session  # attach optional HUB session
--> 372 self.trainer.train()
    373 # Update model and cfg after training
    374 if RANK in (-1, 0):

File D:\python\users\Zahra\anaconda3\envs\yolov8-gpu-env\lib\site-packages\ultralytics\engine\trainer.py:188, in BaseTrainer.train(self)
    186     subprocess.run(cmd, check=True)
    187 except Exception as e:
--> 188     raise e
    189 finally:
    190     ddp_cleanup(self, str(file))

File D:\python\users\Zahra\anaconda3\envs\yolov8-gpu-env\lib\site-packages\ultralytics\engine\trainer.py:186, in BaseTrainer.train(self)
    184 try:
    185     LOGGER.info(f'DDP command: {cmd}')
--> 186     subprocess.run(cmd, check=True)
    187 except Exception as e:
    188     raise e

File D:\python\users\Zahra\anaconda3\envs\yolov8-gpu-env\lib\subprocess.py:528, in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    526     retcode = process.poll()
    527     if check and retcode:
--> 528         raise CalledProcessError(retcode, process.args,
    529                                  output=stdout, stderr=stderr)
    530 return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '['D:\\python\\users\\Zahra\\anaconda3\\envs\\yolov8-gpu-env\\python.exe', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '58736', 'C:\\Users\\zbry8h\\AppData\\Roaming\\Ultralytics\\DDP\\_temp_dk8q2p2k2410653032112.py']' returned non-zero exit status

**Comment by sabarezaeii** [comment]
I think there is  problem here. So I get two different errors when I am trying to get yolov8 running on my 4 GPUs. I am running two exact similar codes inside the same anaconda environment. 


**CASE 1:** I first run the torch.cuda.device_count() and it returns 4, then I try to train my model.
![image](https://github.com/ultralytics/ultralytics/assets/122474907/46cbaadd-91ff-434a-85c3-6841eb0e996f)





It is the new ERROR I am seeing in this case (it doesnt even let me to train on one GPU):


-----------------------------------------------------------------------------------------------------------------------------

Ultralytics YOLOv8.0.137  Python-3.9.17 torch-2.0.1 CUDA:0 (Tesla V100-PCIE-32GB, 32633MiB)
                                                      CUDA:1 (Tesla V100-PCIE-32GB, 32633MiB)
                                                      CUDA:2 (Tesla V100-PCIE-32GB, 32633MiB)
                                                      CUDA:3 (Tesla V100-PCIE-32GB, 32633MiB)
engine\trainer: task=detect, mode=train, model=yolov8l.pt, data=data/thirdSet.yaml, epochs=100, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=[0, 1, 2, 3], workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\train5
Overriding model.yaml nc=80 with nc=4

                   from  n    params  module                                       arguments                     
  0                  -1  1      1856  ultralytics.nn.modules.conv.Conv             [3, 64, 3, 2]                 
  1                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  2                  -1  3    279808  ultralytics.nn.modules.block.C2f             [128, 128, 3, True]           
  3                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  4                  -1  6   2101248  ultralytics.nn.modules.block.C2f             [256, 256, 6, True]           
  5                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]              
  6                  -1  6   8396800  ultralytics.nn.modules.block.C2f             [512, 512, 6, True]           
  7                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]              
  8                  -1  3   4461568  ultralytics.nn.modules.block.C2f             [512, 512, 3, True]           
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  3   4723712  ultralytics.nn.modules.block.C2f             [1024, 512, 3]                
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  3   1247744  ultralytics.nn.modules.block.C2f             [768, 256, 3]                 
 16                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  3   4592640  ultralytics.nn.modules.block.C2f             [768, 512, 3]                 
 19                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  3   4723712  ultralytics.nn.modules.block.C2f             [1024, 512, 3]                
 22        [15, 18, 21]  1   5585884  ultralytics.nn.modules.head.Detect           [4, [256, 512, 512]]          
Model summary: 365 layers, 43632924 parameters, 43632908 gradients

Transferred 589/595 items from pretrained weights
DDP command: ['D:\\python\\users\\Zahra\\anaconda3\\envs\\yolov8-gpu-env\\python.exe', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '58736', 'C:\\Users\\zbry8h\\AppData\\Roaming\\Ultralytics\\DDP\\_temp_dk8q2p2k2410653032112.py']
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
Cell In[6], line 1
----> 1 model.train(data='data/thirdSet.yaml', epochs=100, imgsz=640, device=[0,1,2,3])

File D:\python\users\Zahra\anaconda3\envs\yolov8-gpu-env\lib\site-packages\ultralytics\engine\model.py:372, in YOLO.train(self, **kwargs)
    370     self.model = self.trainer.model
    371 self.trainer.hub_session = self.session  # attach optional HUB session
--> 372 self.trainer.train()
    373 # Update model and cfg after training
    374 if RANK in (-1, 0):

File D:\python\users\Zahra\anaconda3\envs\yolov8-gpu-env\lib\site-packages\ultralytics\engine\trainer.py:188, in BaseTrainer.train(self)
    186     subprocess.run(cmd, check=True)
    187 except Exception as e:
--> 188     raise e
    189 finally:
    190     ddp_cleanup(self, str(file))

File D:\python\users\Zahra\anaconda3\envs\yolov8-gpu-env\lib\site-packages\ultralytics\engine\trainer.py:186, in BaseTrainer.train(self)
    184 try:
    185     LOGGER.info(f'DDP command: {cmd}')
--> 186     subprocess.run(cmd, check=True)
    187 except Exception as e:
    188     raise e

File D:\python\users\Zahra\anaconda3\envs\yolov8-gpu-env\lib\subprocess.py:528, in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    526     retcode = process.poll()
    527     if check and retcode:
--> 528         raise CalledProcessError(retcode, process.args,
    529                                  output=stdout, stderr=stderr)
    530 return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '['D:\\python\\users\\Zahra\\anaconda3\\envs\\yolov8-gpu-env\\python.exe', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '58736', 'C:\\Users\\zbry8h\\AppData\\Roaming\\Ultralytics\\DDP\\_temp_dk8q2p2k2410653032112.py']' returned non-zero exit status 







**CASE 2:** I just run the yolo train lines without checking number of GPUs, then it lets me to run the training on 1 of the 4 GPUs, either 0 or 1 or 2or 3 . 

![image](https://github.com/ultralytics/ultralytics/assets/122474907/e0a429f0-81ca-4f86-986e-8052c884afca)

But when I try to get all 4 GPUs working I get this error: 

![image](https://github.com/ultralytics/ultralytics/assets/122474907/6e9394c2-ee5c-435d-a2c6-62c0660a6a0a)


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 model.train(data='data/thirdSet.yaml', epochs=100, imgsz=640, device=[0,1])

File D:\python\users\Zahra\anaconda3\envs\yolov8-gpu-env\lib\site-packages\ultralytics\engine\model.py:367, in YOLO.train(self, **kwargs)
    365     overrides['resume'] = self.ckpt_path
    366 self.task = overrides.get('task') or self.task
--> 367 self.trainer = TASK_MAP[self.task][1](overrides=overrides, _callbacks=self.callbacks)
    368 if not overrides.get('resume'):  # manually set model only if not resuming
    369     self.trainer.model = self.trainer.get_model(weights=self.model if self.ckpt else None, cfg=self.model.yaml)

File D:\python\users\Zahra\anaconda3\envs\yolov8-gpu-env\lib\site-packages\ultralytics\engine\trainer.py:83, in BaseTrainer.__init__(self, cfg, overrides, _callbacks)
     75 """
     76 Initializes the BaseTrainer class.
     77 
   (...)
     80     overrides (dict, optional): Configuration overrides. Defaults to None.
     81 """
     82 self.args = get_cfg(cfg, overrides)
---> 83 self.device = select_device(self.args.device, self.args.batch)
     84 self.check_resume()
     85 self.validator = None

File D:\python\users\Zahra\anaconda3\envs\yolov8-gpu-env\lib\site-packages\ultralytics\utils\torch_utils.py:82, in select_device(device, batch, newline, verbose)
     79         LOGGER.info(s)
     80         install = 'See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no ' \
     81                   'CUDA devices are seen by torch.\n' if torch.cuda.device_count() == 0 else ''
---> 82         raise ValueError(f"Invalid CUDA 'device={device}' requested."
     83                          f" Use 'device=cpu' or pass valid CUDA device(s) if available,"
     84                          f" i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.\n"
     85                          f'\ntorch.cuda.is_available(): {torch.cuda.is_available()}'
     86                          f'\ntorch.cuda.device_count(): {torch.cuda.device_count()}'
     87                          f"\nos.environ['CUDA_VISIBLE_DEVICES']: {visible}\n"
     88                          f'{install}')
     90 if not cpu and not mps and torch.cuda.is_available():  # prefer GPU if available
     91     devices = device.split(',') if device else '0'  # range(torch.cuda.device_count())  # i.e. 0,1,6,7

ValueError: Invalid CUDA 'device=0,1' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): True
torch.cuda.device_count(): 1
os.environ['CUDA_VISIBLE_DEVICES']: 0






I really need help with this. I dont know what is happening here and I am very confused.

**Comment by Kamlesh364** [comment]
@sabarezaeii try the below command in cli mode-
`yolo train model=yolov8l.pt data=/path/data.yaml epochs=100 device=0,1,2,3`

prior to running this command, make sure no other process is using the GPUs.
