### ISSUE TITLE
What's the point of forcing people to put datasets in specific directory?

### ISSUE THREAD

**Issue by SkalskiP** [ultralytics/ultralytics#384]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

What is the point of introducing that change into the `8.0.6` release, which forces people to store datasets in the datasets directory?

**Comment by AyushExel** [comment]
Agreed. We should not be doing that. It was probably a typo introduced in the update. We'll start writing release notes soon.

**Comment by SkalskiP** [comment]
Cool. All our YOLOv8 tutorial notebooks broke. We fixed the problems now, but design wise I don’t think it is the right move. Glad you agree :)

**Comment by ichsan2895** [comment]
I love yolov8 8.0.5 where we dont need to save training data in internal yolov8 datasets directory, but yolov8 8.0.6 makes the process difficult since I installing yolov8 inside docker, so I must manually using `docker cp .....`

**Comment by SkalskiP** [comment]
@ichsan2895 exactly! But this is only one of the problems caused by this change.
