### ISSUE TITLE
py-cpuinfo not found when using yolo with docker

### ISSUE THREAD

**Issue by sitifatim** [ultralytics/ultralytics#3840]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hello, i try to create docker for my project with yolo in it but i get error `ModuleNotFoundError: No module named 'cpuinfo'` everytime i running yolo with my docker and it also says:

`requirements: Ultralytics requirement ['py-cpuinfo'] not found, attempting AutoUpdate...`
and `requirements: ❌ AutoUpdate skipped (offline)`

what should i do to solve this error?

**Comment by sitifatim** [comment]
okay, i solved it. apparently i need to add py-cpuinfo in my requirements.

**Comment by glenn-jocher** [comment]
@sitifatim hello,

I'm glad you've found a solution to your issue. Indeed, YOLOv8 requires the 'py-cpuinfo' Python module for gathering information about the CPU. When setting up a Docker container for a project that includes YOLOv8, you should include 'py-cpuinfo' in your list of required packages.

Your 'requirements.txt' file or equivalent should have all the necessary packages listed for your project. When you build your Docker image, those requirements will be installed, ensuring your application has all it needs to run correctly.

If you encounter any other difficulties or have more questions, don't hesitate to ask. We're here to help!
