### ISSUE TITLE
memory usage is bigger and bigger

### ISSUE THREAD

**Issue by ChangX116** [ultralytics/ultralytics#3841]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to know how to solve running in python

model = YOLO(r"E:/runs/detect/train2/weightsbest.pt")
result=model.track(source="", show=True,tracker="botsort.yaml")

The memory usage is getting bigger and bigger at runtime , which finally leads to the problem of cv2 memory error

How can I modify the code to solve this problem

**Comment by Laughing-q** [comment]
@ChangX116 try with `stream=True`.
```python
model = YOLO(r"E:/runs/detect/train2/weightsbest.pt")
results=model.track(source="", show=True,tracker="botsort.yaml", stream=True)
for result in results:
    pass
```
it would return a python generator when using `stream=True` and please remember to use a for loop to activate the generator.
more details please refer to our docs. :) https://docs.ultralytics.com/modes/predict/

**Comment by ChangX116** [comment]
> @ChangX116 try with .`stream=True`
> 
> ```python
> model = YOLO(r"E:/runs/detect/train2/weightsbest.pt")
> results=model.track(source="", show=True,tracker="botsort.yaml", stream=True)
> for result in results:
>     pass
> ```
> 
> it would return a python generator when using and please remember to use a for loop to activate the generator. more details please refer to our docs. :) https://docs.ultralytics.com/modes/predict/`stream=True`

Problem solved! Thank you very much!

**Comment by glenn-jocher** [comment]
I'm glad to hear your issue is resolved, @ChangX116! 

Remember, using `stream=True` enables the model to process the data as a stream, returning a python generator. The for loop is used to activate the generator. It's an effective approach to manage memory consumption in large datasets. 

If you encounter any new issues or have further questions, feel free to ask. Happy coding with YOLOv8!
