### ISSUE TITLE
How can I pass a hyp.yaml in the train() method instead of replacing each parameter?

### ISSUE THREAD

**Issue by yaoshanliang** [ultralytics/ultralytics#3842]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The default hyp is default.yaml. How can I use a custom hyp file?

**Comment by Laughing-q** [comment]
@yaoshanliang 
```bash
yolo cfg=custom.yaml
```

**Comment by yaoshanliang** [comment]
> @yaoshanliang
> 
> ```shell
> yolo cfg=custom.yaml
> ```

Not in the command mode. I am using the python code with the `train()` function.

**Comment by Laughing-q** [comment]
@yaoshanliang it's the same arg:
```python
model = YOLO("yolov8n.pt")
model.train(cfg=cfg)
```
