### ISSUE TITLE
iou and conf hyperparameter modification

### ISSUE THREAD

**Issue by yywjacson** [ultralytics/ultralytics#3843]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thank you for taking time out of your busy schedule to answer my questions
The default iou is 0.7, and the map values ​​displayed during training are map50 and map50-95. I modified the values ​​of iou and conf, why map50 and map50-95 are still displayed during training.
wish you all the best！

**Comment by jackbench** [comment]
已收到。

**Comment by Laughing-q** [comment]
@yywjacson the iou=0.7 there is for nms, not  the metrics.

**Comment by yywjacson** [comment]
> @yywjacson the iou=0.7 there is for nms, not the metrics.

原来是这样。那评价指标的iou阈值能修改吗

**Comment by glenn-jocher** [comment]
您好 @yywjacson，

是的，您的理解是对的，这里的iou=0.7是非极大值抑制（Non-Maximum Suppression, NMS）中使用的，而并非是计算度量（metrics）如mAP时的阈值。

要注意到，在YOLOv8 的评价阶段，用以计算mAP的IoU阈值是固定的。mAP50用的IoU阈值是0.5，mAP50-95则用的是从0.5到0.95，每隔0.05的一系列阈值。这是按照COCO数据集的标准设定的，也是目标检测中广泛接受的设定。此类参数通常不需要用户手动进行修改。

希望我解答了您的疑问，祝顺利！

**Comment by yywjacson** [comment]
> 

谢谢您用中文详细回答了我的问题。您的回答解决了我的疑惑，向你表示敬意！

**Comment by glenn-jocher** [comment]
@jackbench 我很高兴听到您找到了想要的答案，感谢您对我的工作的欣赏。请记住，我在这里只是代表一个更大的社区，我也要感谢YOLO和Ultralytics团队，是他们的努力让这些实现和进步成为了可能。如果您有更多的问题，欢迎随时提问。我们都在这里为您提供帮助。
