### ISSUE TITLE
Why yolov8 can only use cpu on my jetson nano? How to use GPU?

### ISSUE THREAD

**Issue by mochechan** [ultralytics/ultralytics#3844]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Jetson nano/ JetPack 4.6.x/ ubuntu 18.04/ python3.6
Jetson xavier nx/ JetPack 5.1/ ubuntu 20.04/ python3.8

The method `pip install ultralytics` does not work any more due to the original Jetson nano has python3.6 only. The ultralytics is no more supporting python3.6 or previous python3. So, the following steps are executed in my Jetson nano. It is recommended to update installation guides for the outdated machine. 
```
apt install -y python3.8-dev python3-pip python3-setuptools
python3.8 -m pip install -U pip 
python3.8 -m pip install --upgrade pip
python3.8 -m pip install scikit-build
python3.8 -m pip install ultralytics
```
Currently, ultralytics supports pytorch2 by default installation. But Jetson nano is impossible to install pytorch2.0 with GPU due to Jetson nano has lower CUDA version. 

Following messages are ultralytics running in my Jetson nano.

```
Ultralytics YOLOv8.0.138 = Python-3.8.0 torch-2.0.1 CPU (ARMv8 Processor rev 1 (v8l))
YOLOv8x-seg summary (fused): 295 layers, 71797696 parameters, 0 gradients

PyTorch: starting from yolov8x-seg.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) ((1, 116, 8400), (1, 32, 160, 160)) (137.4 MB)

ONNX: starting export with onnx 1.14.0 opset 17...
================ Diagnostic Run torch.onnx.export version 2.0.1 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ONNX: export success  385.4s, saved as yolov8x-seg.onnx (274.1 MB)

Export complete (424.0s)
Results saved to /home/a/nxssd/gitlab/python
Predict:         yolo predict task=segment model=yolov8x-seg.onnx imgsz=640 
Validate:        yolo val task=segment model=yolov8x-seg.onnx imgsz=640 data=coco.yaml 
Visualize:       https://netron.app

0: 480x640 1 bicycle, 1 truck, 1 dog, 1: 480x640 1 bicycle, 1 truck, 1 dog, 22226.1ms
Speed: 55.6ms preprocess, 11113.1ms inference, 34.8ms postprocess per image at shape (1, 3, 480, 640)
```
Wow, the inference consumes 11 seconds.
I prefer pytorch with GPU acceleration rather than higher version pytorch 2. 
Is it possible to install ultralytics with pytorch 1.x (with GPU acceleration) if I can accept lower version pytorch? 
How to install ultralytics with pytorch_GPU 1.x?

**Comment by Laughing-q** [comment]
@mochechan yes you can use 1.x pytorch for ultralytics, I'm also using torch==1.13.1 in my daily work.

**Comment by Klinefelters** [comment]
Hi there, to get ultralytics working on the jetson nano, I had to upgrade to python 3.8 and install torach and torchvision manually. 

Here is the tutorial I used:
https://i7y.org/en/yolov8-on-jetson-nano/

Another option is to use this jetson nano image with python 3.8 and torch+torchvision already installed.

Here is that image:
https://github.com/Qengineering/Jetson-Nano-Ubuntu-20-image

When running on the U20 image I get 10+ fps, which is better than the default jetpack installation.

**Comment by glenn-jocher** [comment]
@mochechan hi, I'm glad to hear you've managed to get ultralytics working on your Jetson Nano. Upgrading to Python 3.8 and manually installing torch and torchvision is indeed a plausible solution.

The tutorial you mentioned could be excellent reference for others having similar issues trying to implement YOLOv8 on their Jetson Nano, as it provides step by step instructions to set up the environment with Python 3.8, torch and torchvision.

Another valuable resource could be the Jetson Nano image you've shared. It already comes with Python 3.8, torch, and torchvision installed, saving developers the overhead of setting up.

Achieving 10+ fps on the U20 image is a great improvement from the default JetPack installation. It's encouraging to hear that these solutions have worked well in your case and will likely be beneficial to others in the community. Thanks for sharing!

**Comment by dreamerYCJ** [comment]
i use the gpu in jetson nano,still slowly,300ms per image

**Comment by glenn-jocher** [comment]
Hi @dreamerYCJ,

Thank you for sharing your experience. Running YOLOv8 on the Jetson Nano can indeed be challenging due to its limited computational resources. Here are a few tips to potentially improve performance:

1. **Model Size**: Consider using a smaller model like YOLOv8n (Nano) instead of larger models like YOLOv8x.
2. **Image Size**: Reduce the input image size to decrease processing time.
3. **TensorRT**: Export your model to TensorRT for optimized inference on NVIDIA hardware.

If you haven't already, enabling MAX Power Mode (`sudo nvpmodel -m 0`) and Jetson Clocks (`sudo jetson_clocks`) can also help maximize performance.

Feel free to reach out if you need further assistance! 🚀

**Comment by Klinefelters** [comment]
Hi!

I worked with yolov8 on a jetson nano last year and had far better results using [this ubuntu 20 image](https://github.com/Qengineering/Jetson-Nano-Ubuntu-20-image).

It has everything you need preinstalled except ultralytics itself. I was able to consistently get over 10fps using it! Goodluck!

**Comment by glenn-jocher** [comment]
Hi @Klinefelters,

Thank you for sharing your experience and the helpful link! It's great to hear that the Ubuntu 20 image worked well for you and provided better performance. Achieving over 10fps on the Jetson Nano is impressive! 🚀

For those looking to replicate your setup, using that preconfigured image could indeed save a lot of time and effort. Best of luck to everyone working on their YOLOv8 projects!

**Comment by jasonlytehouse** [comment]
You can use this [repo](https://github.com/jayfalls/jetson_nano_ubuntu20_docker/tree/main) I created which provides a docker image with python3.11 to run any ultralytics yolo models on Jetson Nano with torch gpu or tensorrt

You can expect about 60-70ms average end-to-end with yolov8n and yolov10n on the Jetson with Python3.11

**Comment by glenn-jocher** [comment]
Hi @jasonlytehouse,

Thank you for sharing your repository! It's fantastic to see community contributions that help streamline the setup process for running YOLO models on the Jetson Nano. Your Docker image with Python 3.11 and support for torch GPU or TensorRT sounds like a valuable resource.

For those looking to achieve better performance without upgrading their Ubuntu installation, this could be a great solution. Achieving 60-70ms average end-to-end inference time with YOLOv8n and YOLOv10n is impressive! 🚀

If anyone encounters issues or has questions about using this setup, please ensure you provide a minimum reproducible code example so we can assist you effectively. You can find more details on creating one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Best of luck with your projects, and thank you again for contributing to the community! 😊
