### ISSUE TITLE
Benchmark models using custom dataset

### ISSUE THREAD

**Issue by maianumerosky** [ultralytics/ultralytics#3849]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

When I run` yolo benchmark model='best.pt' imgsz=640 device=cpu` the exports and benchmarks are run using the default datasets for each task. I exported my own model (trained in my own dataset) and wanted to know if the performance of the resulting model was the same. I saw some questions in the [docs page](https://docs.ultralytics.com/modes/benchmark/?h=benchma#export-formats) asking for the same feature.
I'm already working on a PR to submit if that's a necessary and relevant feature for you folks. Thank you for developing YOLO v8, it's been really useful.

### Use case

Described above

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@maianumerosky hi, thank you for your interest in contributing to YOLOv8!

We're really glad to know you've found the benchmark functionality useful. Your suggestion for enabling benchmarking of custom-trained models indeed sounds like a relevant and valuable enhancement to the repository.

The `benchmark` mode in YOLOv8 is designed to objectively measure the performance of models across various tasks. The feature you're planning to implement would indeed be useful for users who have trained their own models and want to verify their performance. 

Before you get to work on your PR, I would recommend you ensure that the implementation is general enough to handle a variety of cases. We'd suggest the following aspects to consider:
- Make sure the user has an easy way of specifying the path to their custom model.
- Ensure the benchmark script gracefully handles any mismatches between the tasks the model has been trained for and the tasks the benchmarking suite is trying to test.
- Appropriately take into consideration the user's specified `imgsz` and `device` settings.

You're most welcome to get started on this feature. Thank you once again for your contribution to the YOLOv8 community and for making our tool better. We await your PR!
