### ISSUE TITLE
google Colab weights after training to detect on webcam in anaconda

### ISSUE THREAD

**Issue by itmr97** [ultralytics/ultralytics#3855]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

after I finished the training the dataset in google colab and get the wights in best.pt file in google drive I download the run folder  and try to detect by webcam in the computer by anaconda and I get this error:

(yolov8-gpu-env) M:\yolov8-gpu>yolo detect predict model=ar_words\weights\best.pt source="0" show=True
WARNING  ar_words\weights\best.pt appears to require 'ultralytics.utils', which is not in ultralytics requirements.

it's say the best.pt not in ultralytics requirements but both of them in lasted version and reinstall the yolov8 but still not working 
![Screenshot 2023-07-20 192622](https://github.com/ultralytics/ultralytics/assets/40148242/02f3c0de-d71f-4a3a-b0cc-6685542d0b1c)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
You're welcome @itmr97! I'm glad to hear that it's working now. If you encounter any more issues or have further questions about YOLOv8, feel free to share. Happy coding!
