### ISSUE TITLE
Export model do not have postprocessing

### ISSUE THREAD

**Issue by kenneedsleep** [ultralytics/ultralytics#3865]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi 
I try to deploy the model in the C++ for inference. As our kernel only support pb model input, I try to export the pb. THen I found that the postprocessing was cut during the conversion. Is there any way to keep the postprocessing ops when export model. For example, the pb model could return the same output as what it is in the python environment.

**Comment by kenneedsleep** [comment]
Currently the output is a list contain two tensor: 1.  [4 + cls + 32 , 18900] where 18900 is the canidates, 4 for bounding box, cls for number of class and 32 for maskin. And the second output is the [32, 240,240] mask proto as I set input imgse as 960

**Comment by glenn-jocher** [comment]
@kenneedsleep hi there,

You're correct about the output format. The first tensor in the list is for object detections that include the bounding boxes, class predictions, and the mask coefficients. Specifically:

- The "4" represents the bounding box coordinates.
- "cls" corresponds to the number of classes in your model and represents the class probabilities.
- "32" is the number of mask coefficients used in YOLOv8. These coefficients are used to generate instance masks for the detected objects.
- And "18900" is the total number of candidate detections, which is determined by the structure of your model and the input size.

The second tensor in the list is the 'mask prototype', which is a set of learnable masks that are 32 in number (same as the mask coefficients). The specific size of 240x240 is a model parameter and will be the same regardless of the input image size. The mask for each detected object is created by linearly combining these mask prototypes, weighted by the mask coefficients. 

Bear in mind that the post-processing to convert these raw outputs into final bounding boxes, class labels, and instance masks is not done within the model itself, but afterwards in the Python code. As such, when exporting the model to another format (like .pb for TensorFlow), the output will still be these raw values, and you'll need to implement the equivalent post-processing step in your deployment environment. 

The YOLOv8 paper and code should contain the information needed for this post-processing step, you might need to familiarize yourself with these to understand the complete process. 

I hope that helps to clarify how the output of YOLOv8 is structured.

Best of luck with your project!

**Comment by kenneedsleep** [comment]
Thank you for your response! Best wishes

**Comment by Hommoner** [comment]
Hello  @kenneedsleep 

 These repos can help you convert  C++ for inference

https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-ONNXRuntime-CPP
https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp
https://github.com/FeiYull/TensorRT-Alpha

By reference these repos , I had convert my customized yolov8 seg model to do  c++  inference in windows env for
onnx  model by opencv-4.8.0+cudnn
tensorrt mode by TensorRT-8.5.3.1

**Comment by kenneedsleep** [comment]
Thanks. I have already finished the postprocess. The new problem comes up. I try to use the mask in and proto to get the mask for each prediction. Then find the minimun area rectangle of the mask. Then, return the rectangle as a result I can get the rotated bounding box. However, the time for whole project including prepocess, inference and postprocess cost average 2 seconds which was not acceptable. Any idea for that?
> Hello @kenneedsleep

**Comment by kenneedsleep** [comment]
The problem was solved. Thanks for help

**Comment by glenn-jocher** [comment]
@kenneedsleep you're welcome! I'm glad to hear that your problem was solved. If you have any other issues or questions in the future, feel free to ask. Happy coding!
