### ISSUE TITLE
json resulst seems too bad, while validation metric is good.

### ISSUE THREAD

**Issue by wcyjerry** [ultralytics/ultralytics#3866]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, there.
    I want to check out a few things, all the questions are under default configs:
1. When calculating metrics in test set during training, the default nms is doing between different classes (class-agnostic) or not?
2. When I using one trained model to do validation, the output metric is the same as I got during training and the metric is good. Then I set save json to True, and I get a json file. I do a visualization based the json file, and the result is like this which clearly got some duplicated boxes, but as far as I have checked (May be I was wrong), the results save into json have alraedy do nms. Why would I get a result like this:
![image](https://github.com/ultralytics/ultralytics/assets/48686306/65e02996-43fb-477a-9f11-e64587b275cf)
![image](https://github.com/ultralytics/ultralytics/assets/48686306/0a56f8c4-e98b-4b25-874b-28310e80b32d)

**Comment by glenn-jocher** [comment]
@wcyjerry hello,

Thank you for reaching out and providing a detailed description of your issue. 

Regarding your first question on the calculation of metrics in the test set during training, YOLOv8 by default performs Non-Maximum Suppression (NMS) on a class-wise basis. In other words, it's not class-agnostic; it applies NMS for each object class independently.

As for your second question around the visualization of JSON results, there could be several reasons why you're seeing duplicate boxes. One possibility might be related to the confidence threshold set when saving the JSON results. Even after NMS, if the confidence threshold is lower than it should be, it could still result in multiple bounding boxes for the same object. Another factor could be the Intersection Over Union (IOU) threshold used during NMS. If this is too low, it may not effectively suppress overlapping detections.

Checking the confidence threshold and IOU threshold settings could help you address this issue. Also, please note that the JSON results are intended for evaluation purposes and may not necessarily correspond visually to the NMS-processed outputs used in actual inference operations.

I hope this response helps clarify things. Please don't hesitate to reach out if you have any further questions or issues.

Best,
Glenn Jocher

**Comment by wcyjerry** [comment]
Thx for sharing the details. I just cant figure out why the ap50 seems all right, while the visualize result from json seems terrible under the same postprocess(If I'm not wrong, the saved json result is also filtered by the same conf score and iou score of nms).&nbsp;



------------------ Original ------------------
From: Glenn Jocher ***@***.***&gt;
Date: Sat,Jul 22,2023 1:03 AM
To: ultralytics/ultralytics ***@***.***&gt;
Cc: Chenyi Wang ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [ultralytics/ultralytics] json resulst seems too bad, whilevalidation metric is good. (Issue #3866)





 
@wcyjerry hello,
 
Thank you for reaching out and providing a detailed description of your issue.
 
Regarding your first question on the calculation of metrics in the test set during training, YOLOv8 by default performs Non-Maximum Suppression (NMS) on a class-wise basis. In other words, it's not class-agnostic; it applies NMS for each object class independently.
 
As for your second question around the visualization of JSON results, there could be several reasons why you're seeing duplicate boxes. One possibility might be related to the confidence threshold set when saving the JSON results. Even after NMS, if the confidence threshold is lower than it should be, it could still result in multiple bounding boxes for the same object. Another factor could be the Intersection Over Union (IOU) threshold used during NMS. If this is too low, it may not effectively suppress overlapping detections.
 
Checking the confidence threshold and IOU threshold settings could help you address this issue. Also, please note that the JSON results are intended for evaluation purposes and may not necessarily correspond visually to the NMS-processed outputs used in actual inference operations.
 
I hope this response helps clarify things. Please don't hesitate to reach out if you have any further questions or issues.
 
Best,
 Glenn Jocher

**Comment by glenn-jocher** [comment]
Hello @wcyjerry,

I understand your confusion. Let's try to unravel this.

First, it's important to know that AP50 (Average Precision at 50% IoU) mainly focuses on precision at a relatively high IoU threshold, meaning that your model appears to be good at making precise detections. However, seeing multiple bounding boxes in the visualized results could indicate either a lower confidence threshold set when exporting the JSON results, or a relatively low IoU threshold used during NMS.

These settings could cause multiple detections of the same object, especially if there are many detections with different classes near or at the same location. Even though these detections might not impact the AP50 much (since NMS process is class-wise and AP50 is relatively lenient in box overlap), they could still appear in the JSON file and hence in the visualizations.

The filtered results you see in the JSON are more like raw outputs before a more stringent filtering process that you would normally apply in a detection task. So, a good metric on AP50 could still coexist with a weird-looking visualization from the JSON results.

You might want to reevaluate if your application requires higher precision (eliminating duplicate detections) and if so, adjust your NMS and confidence thresholds accordingly.

I hope this helps to clarify the issue.

Kind regards,
Glenn Jocher

**Comment by wcyjerry** [comment]
> Hello @wcyjerry,
> 
> I understand your confusion. Let's try to unravel this.
> 
> First, it's important to know that AP50 (Average Precision at 50% IoU) mainly focuses on precision at a relatively high IoU threshold, meaning that your model appears to be good at making precise detections. However, seeing multiple bounding boxes in the visualized results could indicate either a lower confidence threshold set when exporting the JSON results, or a relatively low IoU threshold used during NMS.
> 
> These settings could cause multiple detections of the same object, especially if there are many detections with different classes near or at the same location. Even though these detections might not impact the AP50 much (since NMS process is class-wise and AP50 is relatively lenient in box overlap), they could still appear in the JSON file and hence in the visualizations.
> 
> The filtered results you see in the JSON are more like raw outputs before a more stringent filtering process that you would normally apply in a detection task. So, a good metric on AP50 could still coexist with a weird-looking visualization from the JSON results.
> 
> You might want to reevaluate if your application requires higher precision (eliminating duplicate detections) and if so, adjust your NMS and confidence thresholds accordingly.
> 
> I hope this helps to clarify the issue.
> 
> Kind regards, Glenn Jocher

Hi, Thanks for your explaination.
Due to the details codes for calculating ap is different between ultralytics and coco api, and I want to check the result I got in my own framework(using coco api) with v8(using ultralytics), So I want to save the result from yolov8 to json, and using coco api to calculate ap again to compare with my framework. But the result using coco api from v8's json is too weird. I don't know where is wrong!
![image](https://github.com/ultralytics/ultralytics/assets/48686306/5107c2bd-b0e0-40db-9d44-ca0b6d7961da)

**Comment by wcyjerry** [comment]
Hi @glenn-jocher ,
Thansk for ur kindly responses. I have fully understood that the AP is much higher when set the conf thresh to 0.001 even it will cause many duplicated boxes. 
So, in practical applications, when I aim for better actual performance (a more balanced trade-off between false positives and false negatives) rather than purely high AP, should I set the conf_thresh to a higher value, for example, 0.3, and then choose the model with the highest AP during the training process based on this conf_thresh?
Best!

**Comment by glenn-jocher** [comment]
Hi @wcyjerry,

Glad to hear that you find the explanations helpful. You are absolutely correct. In practical applications where you need a balance between false positives and false negatives, it could be beneficial to set a higher confidence threshold.

The exact value can depend on a variety of factors like your specific use case, tolerance for false positives/negatives, etc. That being said, the conf_thresh of 0.3 that you suggested can be a good starting point. 

To pick the best model during the training process, you can indeed consider the one that achieves the highest AP at this particular confidence threshold.

Remember, it could be useful to experiment with a few different thresholds to see which yields the best trade-off for your specific use-case and consistently employ it when comparing across models or iterations.

Best regards,

**Comment by wcyjerry** [comment]
Thx a lot. I totally figured out about this. I will re-evalue my model &nbsp;ckpts on a higher conf &nbsp;for better application using rather than purly chasing higher ap.





------------------ Original ------------------
From: Glenn Jocher ***@***.***&gt;
Date: Fri,Jul 28,2023 10:41 PM
To: ultralytics/ultralytics ***@***.***&gt;
Cc: Chenyi Wang ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [ultralytics/ultralytics] json resulst seems too bad, whilevalidation metric is good. (Issue #3866)





 
Hi @wcyjerry,
 
Glad to hear that you find the explanations helpful. You are absolutely correct. In practical applications where you need a balance between false positives and false negatives, it could be beneficial to set a higher confidence threshold.
 
The exact value can depend on a variety of factors like your specific use case, tolerance for false positives/negatives, etc. That being said, the conf_thresh of 0.3 that you suggested can be a good starting point.
 
To pick the best model during the training process, you can indeed consider the one that achieves the highest AP at this particular confidence threshold.
 
Remember, it could be useful to experiment with a few different thresholds to see which yields the best trade-off for your specific use-case and consistently employ it when comparing across models or iterations.
 
Best regards,

**Comment by glenn-jocher** [comment]
Hi @wcyjerry,

I'm glad to hear that the previous explanations have been helpful for you! Your decision to re-evaluate your model checkpoints with a higher confidence threshold definitely sounds like a good strategy for optimizing model performance in a practical application. Remember, tailoring the model to your specific use case, rather than only pursuing higher AP, is critical for achieving the best results. Looking forward to hearing about the progress of your work!

Best of luck!

**Comment by wcyjerry** [comment]
@glenn-jocher Hi,
I have re-evaluated all ckpts in a higher conf_thresh hold which is more suitable for practical application.
Here are the results under 0.01 and 0.3, but the trends seems the same, but I think it is still necessary.
![image](https://github.com/ultralytics/ultralytics/assets/48686306/024ea2fe-4555-4f62-b3d2-7caca79755fc)

**Comment by glenn-jocher** [comment]
Hi @wcyjerry,

Thank you for sharing your validation results.

It’s interesting to see that while the overall trend appears to be the same for both confidence thresholds, the performance with a 0.3 threshold seems to be more stable when compared to the 0.01 threshold.

In practical applications, we often do need to strike a balance between preventing an excessive number of false predictions (which a 0.01 threshold might incur) and missing out too much on correct detections (potential risk with a too high threshold).

In this context, the 0.3 threshold seems like a reasonable choice as it can ensure fewer false positives while still keeping a good recall rate.

I encourage you to continue with this approach and feel free to adjust the threshold based on the specific need of your application. Keep up the great work!

Best regards,
Glenn Jocher
