### ISSUE TITLE
An error occurred while training a custom dataset

### ISSUE THREAD

**Issue by havefunheehee** [ultralytics/ultralytics#387]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/106720376/212582659-ad4fbe58-0e78-488b-bf1f-42928c5b1bff.png)
No error is reported when I use yolov8 to train on coco2017. AssertionError is reported when I use custom data: Image Not Found  D:\hb\Object_detection\yolov8\ultralytics\yolo\v8\datasets\coco128\images\train2017\Tilapia_mossambica_093.jpg

**Comment by AyushExel** [comment]
The error suggests that you have an image missing. Please confirm if that image mentioned in the error msg exists
