### ISSUE TITLE
Slow OpenVINO

### ISSUE THREAD

**Issue by rnoriega** [ultralytics/ultralytics#3871]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have exported the yolov8n model to OpenVINO and it is almost always slower than the default .pt version with CPU, but I have seen that the benchmarks show that it would have to be about three times faster:
![Captura de pantalla 2023-07-21 a las 13 22 26](https://github.com/ultralytics/ultralytics/assets/21258199/21ef6c57-0f09-461f-92a2-af588ca01706)

```
> yolo checks
Ultralytics YOLOv8.0.139 🚀 Python-3.10.12 torch-2.0.1 CPU (11th Gen Intel Core(TM) i7-1165G7 2.80GHz)
Setup complete ✅ (8 CPUs, 31.0 GB RAM, 99.4/934.8 GB disk)

> yolo export model=yolov8n.pt format=openvino half=True
Ultralytics YOLOv8.0.139 🚀 Python-3.10.12 torch-2.0.1 CPU (11th Gen Intel Core(TM) i7-1165G7 2.80GHz)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients

PyTorch: starting from yolov8n.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

ONNX: starting export with onnx 1.14.0 opset 17...
================ Diagnostic Run torch.onnx.export version 2.0.1 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ONNX: export success ✅ 0.4s, saved as yolov8n.onnx (12.2 MB)

OpenVINO: starting export with openvino 2023.0.1-11005-fa1c41994f3-releases/2023/0...
OpenVINO: export success ✅ 0.5s, saved as yolov8n_openvino_model/ (6.3 MB)

Export complete (2.1s)
Results saved to /home/user/iot/models
Predict:         yolo predict task=detect model=yolov8n_openvino_model imgsz=640
Validate:        yolo val task=detect model=yolov8n_openvino_model imgsz=640 data=coco.yaml
Visualize:       https://netron.app

> yolo predict classes=2,7 device=cpu model=yolov8n.pt save=False source=./vehicles.mp4
Speed: 1.5ms preprocess, 24.0ms inference, 0.5ms postprocess per image at shape (1, 3, 384, 640)

> yolo predict classes=2,7 device=cpu model=yolov8n_openvino_model save=False source=./vehicles.mp4
Speed: 1.8ms preprocess, 27.4ms inference, 0.7ms postprocess per image at shape (1, 3, 640, 640)
```

What can be the cause of such poor performance?

Thanks.

**Comment by glenn-jocher** [comment]
@rnoriega hello,

Thank you for your question. The performance of an exported OpenVINO model may depend on various factors including system specifications, the specific model architecture, and the OpenVINO version used.

OpenVINO typically optimizes models to run on specific Intel processors. If your CPU hardware differs significantly from the hardware used during model training or our own benchmark hardware, this could be a cause for the observed slower performance.

If your model architecture or parameters are substantially different from those we used in our benchmarks, the exported OpenVINO model might not perform optimally. It's also worth mentioning that the focus of OpenVINO is predominantly on inference speed enhancement for edge devices. However, it may not always provide improvements when running on more powerful machines or servers.

Lastly, the version of OpenVINO you are using can also have a significant impact on performance. Different versions may have different performance characteristics based on changes to the underlying libraries and optimizations.

To enhance the speed, you might want to try tuning your OpenVINO configuration, such as adjusting the number of inference requests or utilizing OpenVINO's dynamic batching feature, if it's applicable to your model. Also, making sure you're using the latest version of OpenVINO might help as there could be performance improvements in newer releases.

I hope this information was helpful. Let me know if you have any other questions!

Best, 
Glenn
