### ISSUE TITLE
segmentation, save image similar to crop with transparent or no background.

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/ultralytics#3874]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

save_crop_instance = True/False
save_crop_instance_bkgnd = transparent/white/black/#000000/etc.
Save the image with a transparent or configuration defined background.

### Use case

Feature would be enabled and configurable using the yaml configuration and command line arguments.

### Additional

Operating on the segmented object pixels enables more precise color analysis when the background excluded.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@apiszcz hello, 

Thanks for bringing up this feature request of saving segmented images with a configurable background! As of now, YOLOv8 does not have such a feature built-in, but I can certainly understand the utility it would provide for more precise color analysis in different applications. 

You can use YOLOv8's segmentation feature to segment the objects in an image and obtain the segmented object's pixel indices. Once you have these indices, you could potentially change the pixel values of the rest of the image to achieve the background color of your choice. 

Unfortunately, I am not aware of any immediate plans to add this feature to YOLOv8. However, your willingness to contribute is greatly appreciated, and any improvements to YOLOv8 are welcome. 

Please note that the feature would need to be incorporated in a way that does not affect the performance and compatibility of the existing code, and is maintainable in the long term. Your PR would go through a standard review process to ensure it meets these criteria. On completion, it could benefit the wider community of YOLOv8 users. 

Thank you for your interest and involvement in YOLOv8 repo, your contribution is valuable to the community.

Best regards,
Glenn Jocher
