### ISSUE TITLE
How to read the python result object for classification?

### ISSUE THREAD

**Issue by Dirk-27** [ultralytics/ultralytics#3878]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

We tried this code from the documentation (snippet):

```
# Load a model
model = YOLO('yolov8n-cls.pt')  # load an official model

# Predict with the model
results = model('https://ultralytics.com/images/bus.jpg')  # predict on an image
```

We succeeded before using the detection. There with the 'yolov8n.pt' model the result contains boxes and the boxes contains classes (cls).

How do we read the results from the classification model? There seems to be no boxes and no other objects which have classes.

We see https://github.com/ultralytics/ultralytics/issues/201, but there is no example using the python API.

**Comment by glenn-jocher** [comment]
@Dirk-27 hello and thank you for reaching out! 

For classification models, the output `results` does not contain bounding boxes or class labels as you would expect in detection models. 

Instead, the `results` object carries the predictions of the input images and the class that the model predicts for each image. You can access these class predictions using the `pred` attribute of the `results` object. Each class prediction will be a numerical value, which corresponds to the index of the class in the class labels defined during model training.

Keep in mind that these class predictions represent the model's highest confidence guesses and will not carry the positional information provided by bounding boxes in a detection task, as classification models only output the class of the image as a whole and not individual objects.

I hope this helps! If you have further questions or encounter any issues, feel free to raise them. Happy coding!

**Comment by Dirk-27** [comment]
@glenn-jocher : Hello and thank you for your reply!

Unfortunatly we didn't find a pred attribute in the results object.

But in the results[idx].probs object we find this attributes:
- data
- orig_shape: None
- shape: torch.Size([1000])
- top1: 651
- top1conf: tensor(0.7414)
- top5: [651, 827, 598, 550, 760]
- top5conf: tensor([0.7414, 0.0788, 0.0271, 0.0248, 0.0129])

In this way, we were able to determine the class labels and the confidence values:

```
from ultralytics import YOLO

model = YOLO('yolov8n-cls.pt') 
results = model.predict(source="../path/sofa.png")

for r in results:
    for c in range(0, 5):
        id =r.probs.top5[c]
        print(id, r.names[id], r.probs.top5conf.numpy()[c])

```
Is there another better way to get the class labels? Can we get more than five class labels?

**Comment by glenn-jocher** [comment]
Hi @Dirk-27,

Glad to know you have made some progress! 

You've actually found the correct way to retrieve the classification label information. The `probs` attribute is an enumeration of the classes with their corresponding confidences. The `top5` attribute reveals the top 5 most probable classes and `top5conf` gives their respective confidences. 

Please note, though, the `.top5` & `.top5conf` attributes are named in such a way to indicate the default behaviour of providing the top 5 class predictions. If you would like to change the number of predictions you can adjust and build your model accordingly. There is no attribute or method embedded into the Ultralytics system to extract more than the top 5 with the public models.

If you make any changes in the model and retrain it for more than 5 class labels, remember that while increasing this value can provide additional predictions, it can also lead to false positives or a less accurate model. The depth of these predictions is a trade-off which you will need to consider according to your specific application needs.

Thank you for your engagement with the Ultralytics YOLOv8 repository and I'm glad you're making use of our solutions!
