### ISSUE TITLE
How to change the backbone to ResNet50 or 101？

### ISSUE THREAD

**Issue by Hezey** [ultralytics/ultralytics#389]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

@AyushExel @plashchynski 
I want to change backboe of YOLOv8 to resnet50 for comparison experiment，but how to change the backbone to ResNet50 or 101？Who can help me? Thank you so much!

**Comment by AyushExel** [comment]
@Hezey you need to build the model yaml for the kind of model you want. Then you can edit the trainer if you need to. We're building the ultralytics repo to simplify these tasks. Please see customization guide here - https://docs.ultralytics.com/engine/

**Comment by Hezey** [comment]
> @Hezey you need to build the model yaml for the kind of model you want. Then you can edit the trainer if you need to. We're building the ultralytics repo to simplify these tasks. Please see customization guide here - https://docs.ultralytics.com/engine/

**Comment by Hezey** [comment]
> @Hezey you need to build the model yaml for the kind of model you want. Then you can edit the trainer if you need to. We're building the ultralytics repo to simplify these tasks. Please see customization guide here - https://docs.ultralytics.com/engine/

Thank you for your reply.！I will try it

**Comment by Hezey** [comment]
@AyushExel Sorry, I failed to find a solution after referring to the above documents. Could you please tell me how to replace backbone with ResNet50? help me... Thank u！！！

**Comment by MrZhang-YUBO** [comment]
Hello, have you solved this problem now? How did you solve it

**Comment by glenn-jocher** [comment]
Hello @MrZhang-YUBO, to change the backbone of YOLOv8 to ResNet50, you will need to modify the model architecture by creating a new YAML file for ResNet50. 

In the YAML file, you will need to define the backbone as ResNet50 and specify the number of filters for each convolutional layer. Once you've defined the new architecture in the YAML file, you can load it using the `--cfg` flag during training or inference.

Please note that modifying the model architecture may require additional tuning of the hyperparameters, and it is recommended to experiment with different settings to achieve optimal performance.

I hope this helps. If you have any further questions, please feel free to ask.
