### ISSUE TITLE
Train on a subset of labels

### ISSUE THREAD

**Issue by smatton** [ultralytics/ultralytics#3895]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Its not clear how I would train a detection model on a subset of labels. I saw in the yolov5 issues a solution where a list can be defined. I didn’t find something similar in the V8 repository.

For example I have a dataset with 80 classes. I trained a model, but now I have a task where I am only interested 1 or 2 classes from the original data. How do I define this subset to train a detection model that only predicts these 2 classes?

**Comment by glenn-jocher** [comment]
@smatton hi there,

If you desire to train your model on a subset of classes, you would need to create a new dataset that only includes these classes. For your case, this new dataset should only have images and labels corresponding to the 1 or 2 classes you're interested in. 

To create this subset, you would need to go through your original dataset and filter out the labels that don't belong to your classes of interest. After doing so, make sure to adjust the class attributes ('names') in your .yaml file to reflect the classes in your new dataset. 

When training, YOLOv8 should now only predict the classes present in your subsetted dataset. 

I hope this helps. Should you have any more questions, please feel free to ask.

Best,
Glenn Jocher

**Comment by smatton** [comment]
Thanks, I was hoping I missed some convenience settings for this.
