### ISSUE TITLE
how to  change hyperparameters like yolov5

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/ultralytics#3900]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

in yolov5 i can change this 
```

degrees: 0.5
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.7
mosaic: 0.8
mixup: 0.2
copy_paste: 0.0


```
how can i change it in yolov8

**Comment by glenn-jocher** [comment]
@VYRION-Ai see https://docs.ultralytics.com/usage/cfg/#augmentation
