### ISSUE TITLE
KeyError: 'step'

### ISSUE THREAD

**Issue by thesby** [ultralytics/ultralytics#3909]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/lib/python3.7/site-packages/ultralytics/cfg/__init__.py", line 423, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/lib/python3.7/site-packages/ultralytics/engine/model.py", line 372, in train
    self.trainer.train()
  File "/usr/lib/python3.7/site-packages/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/usr/lib/python3.7/site-packages/ultralytics/engine/trainer.py", line 314, in _do_train
    self.optimizer.zero_grad()
  File "/usr/lib/python3.7/site-packages/torch/optim/optimizer.py", line 87, in wrapper
    if time_cost_record.ADD_METRICS and time_cost_record.STEP['step'] % time_cost_record.TIME_LOG_INTERVAL == 0:
KeyError: 'step'
  0%|          | 0/1 [00:00<?, ?it/s]

### Environment

- YOLO: 8.0.141
- python: 3.7.5
- OS: centos7

### Minimal Reproducible Example

yolo pose train data=coco8-pose.yaml model=yolov8n-pose.yaml  epochs=100 imgsz=640

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@thesby I'm not able to reproduce the issue, from you error log it's probably related to the version of torch you were using.

**Comment by thesby** [comment]
```
train: WARNING ⚠️ /images/images/wztu2-1.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0088      1.0074      1.9825      1.9852]
```
But I meet another problem. It complains the error coordinates. The label is:
```
0 0.5067385444743936 0.47734375 0.9838274932614556 0.2109375 0.01752021563342318 0.415625 2 1.0 0.371875 2 1.0 0.5625 2 0.014824797843665768 0.584375 2
```

**Comment by hdkhang6803** [comment]
Hi, I have the same issue when resume training from the last checkpoint.

I am using Kaggle with GPU T4x2. I have trained the YOLOv9 and YOLOv8 on my custom dataset and retrieved best.pt and last.pt for each model. I want to resume training with more epoch on the next run but it throws the error:
------------------------------------------------------------------------------------------------------------------
File /opt/conda/lib/python3.10/site-packages/torch/optim/adamw.py:84, in AdamW.__setstate__(self, state)
     81     group.setdefault("fused", None)
     82 state_values = list(self.state.values())
     83 step_is_tensor = (len(state_values) != 0) and torch.is_tensor(
---> 84     state_values[0]["step"]
     85 )
     86 if not step_is_tensor:
     87     for s in state_values:

KeyError: 'step'
------------------------------------------------------------------------------------------------------------------

The configs for the model are:

from ultralytics import YOLO
model_path = '/kaggle/input/yolov9-train-epoch5/last_checkpoint/yolov9_last_epoch5_autobatch_time12.pt'
model = YOLO(model_path)

EPOCHS = 60
BATCH_SIZE = -1
OPTIMIZER = "auto"
SEED = 42
NAME = f"Yolov9_{EPOCHS}_freeze9"
DEVICE = [0]
VERBOSE = False
RESUME = False
PATIENCE = 20

model.train(
    data = "/kaggle/working/data.yaml",
    task = 'detect',
    imgsz = 1000,
    epochs = EPOCHS,
    batch = BATCH_SIZE,
    optimizer = OPTIMIZER,
    patience = PATIENCE,
    name = NAME,
    seed = SEED,
    val = True,
    resume = True,
    device = DEVICE,
    verbose = VERBOSE,
    save = True,
    save_period = 3,
    time=11, #kaggle limits
    freeze = 9
)

My question is that to resume training, I only need to set the resume flag to True and paste the path to the last.pt to my model as above right? And how can I solve the KeyError problem?

Thank you in advance.
