### ISSUE TITLE
stop scanning when use GPU

### ISSUE THREAD

**Issue by hoangnhien2411** [ultralytics/ultralytics#391]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My model always stops at scanning when I train on command and use GPU. Its work on colab. 
![image_2023-01-16_105003409](https://user-images.githubusercontent.com/56782941/212594691-3a1d1840-c8bf-4619-bcfd-bb40a0ba7037.png)

**Comment by hoangnhien2411** [comment]
> It's still not working. I checked everything is ok

**Comment by AyushExel** [comment]
This is probably a windows specific error. I'll look into this later this week. It'd be much easier to debug if we had a reproducible command
