### ISSUE TITLE
There is a long waiting time between different epochs.

### ISSUE THREAD

**Issue by WageningenKing** [ultralytics/ultralytics#394]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When training on a machine with two 3090 graphics cards, there will be a long waiting time between different epochs.
![image](https://user-images.githubusercontent.com/93059562/212613082-9a4e1a29-5268-405a-a7c0-857dba9a856d.png)

### Environment

Ultralytics YOLOv8.0.6  Python-3.9.13 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24576MiB)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by WageningenKing** [comment]
There will also be a waiting time of more than 15s when switching between the training set and the verification set.
![image](https://user-images.githubusercontent.com/93059562/212613797-ef5d131c-a3f2-4007-a8e5-cab8fe6884c1.png)

**Comment by ichsan2895** [comment]
any dataset and syntax to reproduce your problem?

**Comment by WageningenKing** [comment]
> any dataset and syntax to reproduce your problem?

I used a small dataset with 720 pics in total.

PowerShell command is: 
yolo task=detect mode=train model=yolov8s.pt data=test.yaml epochs=800 batch=3

**Comment by ichsan2895** [comment]
> > any dataset and syntax to reproduce your problem?
> 
> I used a small dataset with 720 pics in total.
> 
> PowerShell command is: yolo task=detect mode=train model=yolov8s.pt data=test.yaml epochs=800 batch=3

BTW you have huge VRAM, **maybe** I think increase batch will increase your speed (for example = 16) and the correct arg is `batch_size=16` instead of `batch=16`

**Comment by AyushExel** [comment]
@WageningenKing this can happen in DDP setting when the process waits to sync. 15-20 secs is not unusually long but there might be some optimizations possible here in the future like checking if some cleanup/plotting/etc operation is taking place. When training large models this time becomes irrelevant but in your case each epoch is taking only a few seconds.
 
Also, there can be hardware bottlenecks too - like maybe your HDD/RAM isn't as fast as your GPU needs so moving datasets to and from GPU takes time.

**Comment by WageningenKing** [comment]
> 

Thank you!

**Comment by Lixinsuccess** [comment]
Is your problem solved?I also have the same problem, yoloV7 is normal, yoloV8 has long delay.

**Comment by nub2927** [comment]
timing it the delay is 1 minute 12 seconds, 
which with 50 epochs adds about an hour

**Comment by WageningenKing** [comment]
@nub2927 @Lixinsuccess 
I have solved by setting workers=0 cache=True.
