### ISSUE TITLE
Does training and validation `imgsz` argument takes different format?

### ISSUE THREAD

**Issue by arnavrneo** [ultralytics/ultralytics#3940]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My images are of the resolution: 2992 x 3992 `(height x width)`.
I trained yolov8 model on in the format: (3992, 2992) `(width, height)` as described below in the docs.

![train](https://github.com/ultralytics/ultralytics/assets/48650781/a11cd3e3-2bd5-47ec-95eb-32c192240263)

I was validating the model using the same `imgsz` format: (3992, 2992) `(width, height)` but when I checked the `val` docs, it shows the `imgsz` in the format `(height, width)`. 

![val](https://github.com/ultralytics/ultralytics/assets/48650781/0633f1c4-474a-4f46-9211-2cf68b85aba3)

Is it a typo or the `val` takes image size in the reverse format than the training?

**Comment by Laughing-q** [comment]
@arnavrneo nice catch! actually I think it would always be an integer for train and val mode. It can be a list of [h, w] only when predict and export mode. 
I'll update the docs. :)
