### ISSUE TITLE
How to apply custom augmentation

### ISSUE THREAD

**Issue by Jhyuny** [ultralytics/ultralytics#3945]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to conduct detection experiments with modified data augmentation, but the changes I made don't seem to take effect. Currently, I have cloned the main branch and made modifications to the augment.py file located at ultralytics > ultralytics > data > augment.py. However, when running the experiments, the augmentation does not seem to be applied.

```python
def v8_transforms(dataset, imgsz, hyp, stretch=False):
    """Convert images to a size suitable for YOLOv8 training."""
    pre_transform = Compose([
        Mosaic(dataset, imgsz=imgsz, p=hyp.mosaic, n=9),
        CopyPaste(p=hyp.copy_paste),
        # RandomPerspective(
        #     degrees=hyp.degrees,
        #     translate=hyp.translate,
        #     scale=hyp.scale,
        #     shear=hyp.shear,
        #     perspective=hyp.perspective,
        #     pre_transform=None if stretch else LetterBox(new_shape=(imgsz, imgsz))
        #     ),
        RandomPerspectiveOnlyBbox(
            degrees=hyp.degrees,
            translate=hyp.translate,
            scale=hyp.scale,
            shear=hyp.shear,
            perspective=hyp.perspective,
            pre_transform=None if stretch else LetterBox(new_shape=(imgsz, imgsz)),
        )])
```

I searched for a solution and found an issue suggesting to modify ultralytics/ultralytics/yolo/data/augment.py for data augmentation. However, I can't find this file in the current main branch.
Also, i want to know how to apply mosaic9. As you can see in the above code, even though 'n=9' is set, the results for mosaic9 are not appearing.

The 'augment' argument in default.yaml is set to False because it is intended for TTA.

**Comment by glenn-jocher** [comment]
@Jhyuny hello!

Let's solve this step by step. Firstly, it's great to hear that you're trying to apply custom data augmentations.

1. Regarding the changes you made not taking effect, ensure you are modifying the correct augment.py script that is being used in your setup. Sometimes, if you've installed Ultralytics as a package, modifications made to the augment.py might not be reflected as the package might be using the version installed during setup. Hence, the changes in the local files wouldn't apply. Uninstalling and installing the package again after changes might resolve this.

2. I noticed that you have `augment` set to False. While it is primarily used for TTA (Test-Time Augmentation), it also controls whether or not augmentations are applied during training. If you're trying to augment the training dataset, you should set `augment` to True in default.yaml.

3. As for mosaic9, even though you set `n=9`, this only means 9 images are used to create the mosaic augmentation. Whether mosaic images appear in the final training images depends on the value of `p=hyp.mosaic`. This value is the probability of applying the augmentation, so if it's set low, the mosaic augment might rarely appear. To get more mosaic9 images, you might try to increase `hyp.mosaic`.

4. It's true that the Ultralytics repositories evolve over time and some paths can get updated. Thus, make sure you're working with the most recent version of the repository and when seeking help, aim to refer to up-to-date sources.

Please try the above suggestions and let us know if your issue gets resolved. Remember to share as many details as possible if further issues arise. Your efforts assist in maintaining an effective and useful repository for all users.

Thank you for using YOLOv8 in your work and contributing to our community!

**Comment by glenn-jocher** [comment]
@Jhyuny hi, thanks for your feedback and we're glad to hear that you love the features provided by YOLOv8.

You're certainly right when it comes to the importance of being able to adjust data augmentation settings. Your point is well taken and we're constantly working to improve and provide easier customizations. 

To adjust the augmentations, you don't necessarily need to modify the code in the library. The most common augmentations parameters can be adjusted directly from your hyperparameters file (usually a YAML file). Here, you can modify values corresponding to different augmentations like translation, scaling, rotation, etc.

We understand the need for more detailed augmentation control and we will consider your feedback for future updates. Meanwhile, if you need to use a brand new type of augmentation not present already, a code change might be required.

We also recommend constantly pulling the newest version of YOLOv8 in order to get updates including potential improvements to augmentations control. 

Please don't hesitate to reach out if you have more questions or need further clarification!

**Comment by Jhyuny** [comment]
I will proceed as you have advised. Thank you for your kind response and guidance :D

**Comment by glenn-jocher** [comment]
@pietz, you're welcome! I'm glad to hear that the information was helpful for you. Don't hesitate to continue the discussion or ask more questions if anything comes up during your progress. We're here to help. Happy coding with YOLOv8! 😊

**Comment by pietz** [comment]
@glenn-jocher I actually didn't see this part of the docs where augmentation parameters are discussed in more detail:

https://docs.ultralytics.com/usage/cfg/?h=config#augmentation

This will do it for me!

**Comment by glenn-jocher** [comment]
@pietz, I'm glad to hear that you found the documentation section on augmentation parameters, and that it meets your needs! Ultralytics strives to provide thorough and user-friendly documentation to aid understanding and application. Should any more questions or clarifications arise, don't hesitate to get in touch. We're always here to help. Happy coding with YOLOv8!
