### ISSUE TITLE
I want to index into the yolo feature vectors using the bounding box or mask

### ISSUE THREAD

**Issue by eiyike123** [ultralytics/ultralytics#3947]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have been able to get the yolo vector from the layer before the output vector. I have a set of detected images but I want to be able to index into the vector using the bounding box or mask. I want to be able to get the corresponding vector for every object detected. Is the architectural diagram for v5 and v8 are they the same. I would have appreciated if I can get the Yolov8 paper.

**Comment by glenn-jocher** [comment]
@eiyike123 hello, and thank you for your questions.

To access the feature vectors corresponding to each detected object using a bounding box or mask from the layer prior to the output, you must use the bounding box coordinates as indices to slice the corresponding vectors from the feature map. Keep in mind that these coordinates must be transformed to match the feature map's size as it is typically downsampled compared to the original image.

Regarding the architectural diagram for YOLOv8 and its comparison with other versions, I can note that while retaining the core ideas, there are significant differences and improvements for YOLOv8 to enhance accuracy and efficiency. YOLOv8 introduces several specific changes and new features, making it distinct from previous versions.

As we deeply value the transparency and thoroughness of our research, we understand your request for the YOLOv8 paper. Unfortunately, a detailed paper specifically for YOLOv8 is not yet available. However, all the latest implementation details and performance information are available within the repository documentation.

I hope that answers your questions. Don't hesitate to reach out if you have any more doubts. Happy coding!
