### ISSUE TITLE
How to add customer module?

### ISSUE THREAD

**Issue by AnthonyF333** [ultralytics/ultralytics#395]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, can I add a custom module like C1, C2, C3, C3TR, SPP, SPPF, Bottleneck, BottleneckCSP, C2f, C3Ghost, C3x, Classify,
Concat, Conv, ConvTranspose, Detect, DWConv, DWConvTranspose2d, Ensemble, Focus, GhostBottleneck, GhostConv, Segment?

**Comment by AyushExel** [comment]
Where do you want to add it?
You can import them from `Ultralytics.nn.modules`

**Comment by AnthonyF333** [comment]
> Where do you want to add it? You can import them from `Ultralytics.nn.modules`

I want to use a shuffleblock in my custom model but I can't find it in Ultralytics.nn.modules

**Comment by AyushExel** [comment]
Oh, then it's not included in the available modules. Can you make a PR for that? I'd be happy to assist you
