### ISSUE TITLE
Feature extraction of detected/segmentated objects

### ISSUE THREAD

**Issue by IzhanVarsky** [ultralytics/ultralytics#3957]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello! I need to implement an algorithm of matching two cars from two different camera views. My pipeline should look like this: I detect them with Yolov8 and after that I want to get their embeddings (feature maps) to check the cosine distance between them. I am new to yolov8 and I did not found info about feature extraction of detected objects. Can you help me?

**Comment by glenn-jocher** [comment]
@IzhanVarsky hello and welcome to the YOLOv8 community!

From your question, it sounds like you want to perform object detection using YOLOv8 and then extract the learned features of those detected objects (in your case, cars) for further processing such as matching. This is a common scenario in many applications including yours.

The feature maps in YOLOv8 can be easily accessed as they are the output of the backbone network before the final object detection stage. YOLOv8, like many other object detection models, uses a convolutional neural network as a backbone to extract features from the input images. These features are then passed through the rest of the network to perform object detection. 

You can access these feature maps directly after running an image through the network, before any post-processing is done to extract bounding boxes. These raw feature maps represent the learned features of the objects in the image and can be further processed as per your requirements. 

You can compare the feature maps of two different images or objects using cosine similarity to measure their similarity. Cosine similarity is one of the most common ways to compare high-dimensional feature vectors like those produced by YOLOv8.

I hope this answers your question. If you have any further questions, don't hesitate to ask!

**Comment by IzhanVarsky** [comment]
Thank you for the answer! I have a bit more questions.
If I use the segmentation model (yolov8n-seg.pt) then which last layers should I drop and how to manipulate with the obtained results?
The structure of the seg-model is:
```
SegmentationModel(
  (model): Sequential(
    (0): Conv(...)
    (1): Conv(...)
    (2): C2f(...)
    (3): Conv(...)
    (4): C2f(...)
    (5): Conv(...)
    (6): C2f(...)
    (7): Conv(...)
    (8): C2f(...)
    (9): SPPF(...)
    (10): Upsample(scale_factor=2.0, mode='nearest')
    (11): Concat()
    (12): C2f(...)
    (13): Upsample(scale_factor=2.0, mode='nearest')
    (14): Concat()
    (15): C2f(...)
    (16): Conv(...)
    (17): Concat()
    (18): C2f(...)
    (19): Conv(...)
    (20): Concat()
    (21): C2f(...)
    (22): Segment(...)
  )
)
```
I want to get the embeddings only of the segmentated automobiles (classes: car, truck, bus). Also I want somehow to analyze the confidences.
My code with dropping the last layer looks like this:
```
im_size = 640
test_img = 'test_img.jpg'
pil_img = Image.open(test_img).resize((im_size, im_size))
tensor_img = torchvision.transforms.functional.pil_to_tensor(pil_img)[None, :] / 255.0

yolo = YOLO('yolov8n-seg.pt')
yolo.model.model = yolo.model.model[:-1]  # drop only last layer (Segment(...))

res = yolo.model(tensor_img)
```
The `res` is a tensor with shape (1, 256, 20, 20). How can I get the tensors for the segmentated objects? Or I can get only the embedding of the full image, but not of the segmentated objects?

**Comment by glenn-jocher** [comment]
@IzhanVarsky the segmentation model output from the YOLOv8 architecture you've posted is not a bounding box detection but a pixel-wise segmentation. This model will generate a map for each class that predicts the probability of each pixel belonging to the respective class. Given that the output of the model is a tensor with dimensions (1, 256, 20, 20), it corresponds to 256 class probability maps of size 20x20, where each pixel in the map corresponds to a region in the input image.

Since you're working with a segmentation model, you can't really extract features from specified objects in the same way as in object detection. When applying object detection, typically, features corresponding to the detected bounding box are used, but in the case of segmentation, you actually consider the whole image as you segment the parts corresponding to the objects of interest.

On the other hand, while you want to get embeddings only for automobile classes like cars, trucks, and buses, you may need to process your output tensor accordingly. Your resulting tensor contains feature maps that correspond to the various classes your model has learned to segment. You should select and use only the feature maps corresponding to these specific classes for your analysis. 

Regarding analyzing confidences, these can be understood as pixel-wise class probabilities in the output tensor. Once you have the tensor for a specific class (car, truck, bus), each value at each pixel of this tensor will represent the confidence that this pixel belongs to that class.

Just remember, although you get a more granular pixel-wise segmentation output from this model, it might not match exactly to the task of matching different instances of automobiles from different camera views, especially if you are comparing pixel-wise features from the segmented regions. You might need additional processing or a different approach to effectively tackle this problem.

**Comment by Vigelos** [comment]
> @IzhanVarsky the segmentation model output from the YOLOv8 architecture you've posted is not a bounding box detection but a pixel-wise segmentation. This model will generate a map for each class that predicts the probability of each pixel belonging to the respective class. Given that the output of the model is a tensor with dimensions (1, 256, 20, 20), it corresponds to 256 class probability maps of size 20x20, where each pixel in the map corresponds to a region in the input image.
> 
> Since you're working with a segmentation model, you can't really extract features from specified objects in the same way as in object detection. When applying object detection, typically, features corresponding to the detected bounding box are used, but in the case of segmentation, you actually consider the whole image as you segment the parts corresponding to the objects of interest.
> 
> On the other hand, while you want to get embeddings only for automobile classes like cars, trucks, and buses, you may need to process your output tensor accordingly. Your resulting tensor contains feature maps that correspond to the various classes your model has learned to segment. You should select and use only the feature maps corresponding to these specific classes for your analysis.
> 
> Regarding analyzing confidences, these can be understood as pixel-wise class probabilities in the output tensor. Once you have the tensor for a specific class (car, truck, bus), each value at each pixel of this tensor will represent the confidence that this pixel belongs to that class.
> 
> Just remember, although you get a more granular pixel-wise segmentation output from this model, it might not match exactly to the task of matching different instances of automobiles from different camera views, especially if you are comparing pixel-wise features from the segmented regions. You might need additional processing or a different approach to effectively tackle this problem.

Hello,

Thanks for your instructions on this question.

Based on your answer, I tried to apply 


> yolo = YOLO("yolov8m-ovi7.pth")
> yolo.model.model = yolo.model.model[:-1]
> feature = yolo.model(img_tensor)

to get the embedding feature of each binding box. But the shape of feature I got is $$[1, 576, 20, 20]$$, which is also not the shape of binding box feature, just like the result generated by segmentation model.

I am quite confused at this point now, is there anything I can do to convert the feature I got to something like the binding box feature I want? Thanks a lot.

**Comment by glenn-jocher** [comment]
@Vigelos hello,

From your updated details, it seems you're trying to obtain bounding box features but the model you're using is giving you a feature map. Let's clarify a few things:

The object detection model, when used for detection, does not output features of bounding boxes. Instead, it predicts bounding boxes' locations, dimensions, class probabilities, and objectness scores. The features you're retrieving are intermediate outputs of the network which ultimately lend themselves to these final predictions.

In terms of the shape of the tensor you're getting ([1, 576, 20, 20]), these are actually high dimensional maps and not bounding box features as you might be expecting. In this tensor, 576 is the number of feature maps, and 20x20 is the spatial dimension of each feature map.

To get embeddings or features specifically of the objects detected, the typical approach would be to utilize these spatial features (your 20x20 maps) and perform a region of interest pooling (a form of spatial feature pooling) based on the detected bounding box coordinates. This, however, calls for custom implementation and the complexity may vary based on the requirements and the exact outcome you desire.

Remember, each channel in your feature map is learning to detect different features in your image. To leverage this for object matching, you can process the feature maps directly or further post-process them as per your need.

Try to explore and understand more about how these feature maps come from and how they're involved in the final predictions made by the model. With that, you should be able to guide your experiments in the right direction. Good luck!

**Comment by Vigelos** [comment]
Got it!

Thanks for your thorough explination! Now I know what I should do next. My question is solved. 👍

**Comment by glenn-jocher** [comment]
You're welcome, @Vigelos! I'm glad I could help clarify things for you. If you ever have more questions or need further assistance as you work through your next steps, don't hesitate to reach out. Good luck with your project, and happy coding! Remember, the YOLO community and the Ultralytics team are always here to support you. 👍
