### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Michael-RDev** [ultralytics/ultralytics#3959]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Hello, I was training a YoloV5 model on a custom dataset, when I kept getting the same error

```Traceback (most recent call last):
  File "f:\GpoAIBot\test.py", line 1, in <module>
    import ultralytics
  File "F:\PythonProjects\envs\cvp\lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.engine.model import YOLO
  File "F:\PythonProjects\envs\cvp\lib\site-packages\ultralytics\engine\model.py", line 7, in <module>
    from ultralytics.cfg import get_cfg
  File "F:\PythonProjects\envs\cvp\lib\site-packages\ultralytics\cfg\__init__.py", line 12, in <module>
    from ultralytics.utils import (DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, ROOT, SETTINGS, SETTINGS_YAML,
  File "F:\PythonProjects\envs\cvp\lib\site-packages\ultralytics\utils\__init__.py", line 840, in <module>
    SETTINGS = SettingsManager()  # initialize settings
  File "F:\PythonProjects\envs\cvp\lib\site-packages\ultralytics\utils\__init__.py", line 780, in __init__
    self.load()
  File "F:\PythonProjects\envs\cvp\lib\site-packages\ultralytics\utils\__init__.py", line 794, in load
    self.update(yaml_load(self.file))
  File "F:\PythonProjects\envs\cvp\lib\site-packages\ultralytics\utils\__init__.py", line 802, in update
    new = dict(*args, **kwargs)
TypeError: 'NoneType' object is not iterable
```

The code I used to check to make sure it wasn't a error on the yolov5 training script was 

```
import ultralytics
print(ultralytics.__version__)
````

I still got the error even after I tried to import Ultralytics, I'm wondering if there is a solution for this.

### Environment

Python 3.10.12
Os - Windows 10
Torch: 2.0.1+cpu
YoloV5 repo - (https://github.com/ultralytics/yolov5)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Jhyuny** [comment]
I also have the same issue 😂
```
Starting training for 3000 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     1/3000      3.84G      1.625      3.124      1.781         28        640: 100%|██████████| 39/39 [00:05<00:0
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/5 [0
Traceback (most recent call last):
  File "train.py", line 138, in <module>
    train()
  File "train.py", line 134, in train
    trainer.train()
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 372, in _do_train
    self.metrics, self.fitness = self.validate()
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 478, in validate
    metrics = self.validator(self)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/engine/validator.py", line 167, in __call__
    self.loss += model.loss(batch, preds)[1]
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 215, in loss
    return self.criterion(preds, batch)
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/utils/loss.py", line 159, in __call__
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
TypeError: 'NoneType' object is not iterable
```

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by whittenator** [comment]
I have the same error.

I am attempting to train using a python file:
```python
from ultralytics import YOLO

DATA_LOCATION = "/home/ubuntu/xod-training/datasets/xod-dataset-anthony/xod.yaml"
PRETRAINED_WEIGHTS = "/home/ubuntu/xod-training/yolov8/weights/yolov8l.pt"
HYP_LOCATION = "/home/ubuntu/xod-training/yolov8/hyp.scratch-high.yaml"

# Load a model
model = YOLO(PRETRAINED_WEIGHTS)  # load a pretrained model (recommended for training)

# Train the model with 8 GPUs
model.train(data=DATA_LOCATION, epochs=50, imgsz=800, batch=128, device=[0, 1, 2, 3, 4, 5, 6, 7],
            workers=8, pretrained=True, patience=50, save=True, save_period=10, single_cls=True,
            amp=True, val=True, augment=True,
            project="XOD", name="xod-yolov8-anthony-89541-800x800-singleClass")
```

I Installed a Virtual Environment with the following requirements file:
```
# Ultralytics requirements
# Usage: pip install -r requirements.txt

# Base ----------------------------------------
matplotlib>=3.2.2
opencv-python>=4.6.0
pillow>=7.1.2
pyyaml>=5.3.1
requests>=2.23.0
scipy>=1.4.1
torch>=1.7.0
torchvision>=0.8.1
tqdm>=4.64.0

# Logging -------------------------------------
tensorboard>=2.13.0
# dvclive>=2.12.0
clearml
# comet

# Plotting ------------------------------------
pandas>=1.1.4
seaborn>=0.11.0

# Export --------------------------------------
# coremltools>=6.0,<=6.2  # CoreML export
onnx>=1.12.0  # ONNX export
onnxsim>=0.4.1  # ONNX simplifier
# nvidia-pyindex  # TensorRT export
# nvidia-tensorrt  # TensorRT export
# scikit-learn==0.19.2  # CoreML quantization
# tensorflow>=2.4.1  # TF exports (-cpu, -aarch64, -macos)
# tflite-support
# tensorflowjs>=3.9.0  # TF.js export
# openvino-dev>=2023.0  # OpenVINO export

# Extras --------------------------------------
psutil  # system utilization
py-cpuinfo  # display CPU info
# thop>=0.1.1  # FLOPs computation
# ipython  # interactive notebook
albumentations>=1.0.3  # training augmentations
# pycocotools>=2.0.6  # COCO mAP
# roboflow
```

I installed Pytorch with pip like so:
pip3 install torch torchvision torchaudio

My xod.yaml file looks like so:
```
train: /home/ubuntu/xod-training/datasets/xod-dataset-anthony/train.txt # 48937 images
val: /home/ubuntu/xod-training/datasets/xod-dataset-anthony/val.txt # 13985 images
test: /home/ubuntu/xod-training/datasets/xod-dataset-anthony/test.txt  # 6992 images

# number of classes
nc: 4

# class names
names: ['drone', 'bird', 'fixed-wing', 'heli']

augmentations:
- Albumentations:
    blur_limit: 7
    brightness_contrast: 
      brightness_limit: 0.1
      contrast_limit: 0.1
    gauss_noise:
      var_limit: (10.0, 50.0)
    horizontal_flip: true
    hue_saturation:
      hue_shift_limit: 20
      sat_shift_limit: 50
    motion_blur:
      blur_limit: 7
    rotate:
      limit: 45
      p: 0.5
```

And this is the traceback I am getting:
```
Traceback (most recent call last):
  File "/home/ubuntu/xod-training/yolov8/train.py", line 1, in <module>
    from ultralytics import YOLO
  File "/home/ubuntu/xod-training/yolov8/yolov8-venv/lib/python3.10/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import start
  File "/home/ubuntu/xod-training/yolov8/yolov8-venv/lib/python3.10/site-packages/ultralytics/hub/__init__.py", line 5, in <module>
    from ultralytics.data.utils import HUBDatasetStats
  File "/home/ubuntu/xod-training/yolov8/yolov8-venv/lib/python3.10/site-packages/ultralytics/data/__init__.py", line 3, in <module>
    from .base import BaseDataset
  File "/home/ubuntu/xod-training/yolov8/yolov8-venv/lib/python3.10/site-packages/ultralytics/data/base.py", line 18, in <module>
    from ultralytics.utils import DEFAULT_CFG, LOCAL_RANK, LOGGER, NUM_THREADS, TQDM_BAR_FORMAT
  File "/home/ubuntu/xod-training/yolov8/yolov8-venv/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 840, in <module>
    SETTINGS = SettingsManager()  # initialize settings
  File "/home/ubuntu/xod-training/yolov8/yolov8-venv/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 780, in __init__
    self.load()
  File "/home/ubuntu/xod-training/yolov8/yolov8-venv/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 794, in load
    self.update(yaml_load(self.file))
  File "/home/ubuntu/xod-training/yolov8/yolov8-venv/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 802, in update
    new = dict(*args, **kwargs)
TypeError: 'NoneType' object is not iterable
Overriding model.yaml nc=80 with nc=4
Transferred 589/595 items from pretrained weights
DDP info: RANK 0, WORLD_SIZE 8, DEVICE cuda:0
```

**Comment by whittenator** [comment]
> I have the same error.
> 
> I am attempting to train using a python file:
> 
> ```python
> from ultralytics import YOLO
> 
> DATA_LOCATION = "/home/ubuntu/xod-training/datasets/xod-dataset-anthony/xod.yaml"
> PRETRAINED_WEIGHTS = "/home/ubuntu/xod-training/yolov8/weights/yolov8l.pt"
> HYP_LOCATION = "/home/ubuntu/xod-training/yolov8/hyp.scratch-high.yaml"
> 
> # Load a model
> model = YOLO(PRETRAINED_WEIGHTS)  # load a pretrained model (recommended for training)
> 
> # Train the model with 8 GPUs
> model.train(data=DATA_LOCATION, epochs=50, imgsz=800, batch=128, device=[0, 1, 2, 3, 4, 5, 6, 7],
>             workers=8, pretrained=True, patience=50, save=True, save_period=10, single_cls=True,
>             amp=True, val=True, augment=True,
>             project="XOD", name="xod-yolov8-anthony-89541-800x800-singleClass")
> ```
> 
> I Installed a Virtual Environment with the following requirements file:
> 
> ```
> # Ultralytics requirements
> # Usage: pip install -r requirements.txt
> 
> # Base ----------------------------------------
> matplotlib>=3.2.2
> opencv-python>=4.6.0
> pillow>=7.1.2
> pyyaml>=5.3.1
> requests>=2.23.0
> scipy>=1.4.1
> torch>=1.7.0
> torchvision>=0.8.1
> tqdm>=4.64.0
> 
> # Logging -------------------------------------
> tensorboard>=2.13.0
> # dvclive>=2.12.0
> clearml
> # comet
> 
> # Plotting ------------------------------------
> pandas>=1.1.4
> seaborn>=0.11.0
> 
> # Export --------------------------------------
> # coremltools>=6.0,<=6.2  # CoreML export
> onnx>=1.12.0  # ONNX export
> onnxsim>=0.4.1  # ONNX simplifier
> # nvidia-pyindex  # TensorRT export
> # nvidia-tensorrt  # TensorRT export
> # scikit-learn==0.19.2  # CoreML quantization
> # tensorflow>=2.4.1  # TF exports (-cpu, -aarch64, -macos)
> # tflite-support
> # tensorflowjs>=3.9.0  # TF.js export
> # openvino-dev>=2023.0  # OpenVINO export
> 
> # Extras --------------------------------------
> psutil  # system utilization
> py-cpuinfo  # display CPU info
> # thop>=0.1.1  # FLOPs computation
> # ipython  # interactive notebook
> albumentations>=1.0.3  # training augmentations
> # pycocotools>=2.0.6  # COCO mAP
> # roboflow
> ```
> 
> I installed Pytorch with pip like so: pip3 install torch torchvision torchaudio
> 
> My xod.yaml file looks like so:
> 
> ```
> train: /home/ubuntu/xod-training/datasets/xod-dataset-anthony/train.txt # 48937 images
> val: /home/ubuntu/xod-training/datasets/xod-dataset-anthony/val.txt # 13985 images
> test: /home/ubuntu/xod-training/datasets/xod-dataset-anthony/test.txt  # 6992 images
> 
> # number of classes
> nc: 4
> 
> # class names
> names: ['drone', 'bird', 'fixed-wing', 'heli']
> 
> augmentations:
> - Albumentations:
>     blur_limit: 7
>     brightness_contrast: 
>       brightness_limit: 0.1
>       contrast_limit: 0.1
>     gauss_noise:
>       var_limit: (10.0, 50.0)
>     horizontal_flip: true
>     hue_saturation:
>       hue_shift_limit: 20
>       sat_shift_limit: 50
>     motion_blur:
>       blur_limit: 7
>     rotate:
>       limit: 45
>       p: 0.5
> ```
> 
> And this is the traceback I am getting:
> 
> ```
> Traceback (most recent call last):
>   File "/home/ubuntu/xod-training/yolov8/train.py", line 1, in <module>
>     from ultralytics import YOLO
>   File "/home/ubuntu/xod-training/yolov8/yolov8-venv/lib/python3.10/site-packages/ultralytics/__init__.py", line 5, in <module>
>     from ultralytics.hub import start
>   File "/home/ubuntu/xod-training/yolov8/yolov8-venv/lib/python3.10/site-packages/ultralytics/hub/__init__.py", line 5, in <module>
>     from ultralytics.data.utils import HUBDatasetStats
>   File "/home/ubuntu/xod-training/yolov8/yolov8-venv/lib/python3.10/site-packages/ultralytics/data/__init__.py", line 3, in <module>
>     from .base import BaseDataset
>   File "/home/ubuntu/xod-training/yolov8/yolov8-venv/lib/python3.10/site-packages/ultralytics/data/base.py", line 18, in <module>
>     from ultralytics.utils import DEFAULT_CFG, LOCAL_RANK, LOGGER, NUM_THREADS, TQDM_BAR_FORMAT
>   File "/home/ubuntu/xod-training/yolov8/yolov8-venv/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 840, in <module>
>     SETTINGS = SettingsManager()  # initialize settings
>   File "/home/ubuntu/xod-training/yolov8/yolov8-venv/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 780, in __init__
>     self.load()
>   File "/home/ubuntu/xod-training/yolov8/yolov8-venv/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 794, in load
>     self.update(yaml_load(self.file))
>   File "/home/ubuntu/xod-training/yolov8/yolov8-venv/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 802, in update
>     new = dict(*args, **kwargs)
> TypeError: 'NoneType' object is not iterable
> Overriding model.yaml nc=80 with nc=4
> Transferred 589/595 items from pretrained weights
> DDP info: RANK 0, WORLD_SIZE 8, DEVICE cuda:0
> ```

So, turns out the single_cls=True argument was causing the problem. Removing this argument allows me to train. However, I would like to train all 4 classes into 1 class only. I thought this was possible with single_cls=True?

**Comment by glenn-jocher** [comment]
@whittenator i'm glad to hear that you found a solution. Your understanding is correct. The `single_cls=True` argument can be used in training to map all classes into a single one. 

With regards to your solution, you've basically ensured that you are using the latest version of the Ultralytics YOLOv8 package which likely contained the fix for the issue you were facing. Good job on finding this workaround. Your approach should be helpful to others who might encounter a similar issue.

Remember to keep your packages up-to-date to incorporate the latest changes, improvements, and potential bug fixes. Let us know if you have any further questions or issues.
