### ISSUE TITLE
Addition of VeLO optimizer

### ISSUE THREAD

**Issue by matdealm** [ultralytics/ultralytics#3965]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! I am wondering if there is a plan to add [VeLO](https://github.com/google/learned_optimization/tree/main/learned_optimization/research/general_lopt) optimizer as an additional optimizer?

**Comment by glenn-jocher** [comment]
@matdealm hi, thank you for your feature suggestion on how to improve YOLO 🚀 with the VeLO optimizer!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
