### ISSUE TITLE
Creating a self contained project structure

### ISSUE THREAD

**Issue by pietz** [ultralytics/ultralytics#3966]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to set up a self contained project structure that stores all data and configuration parameters for training a detection model. That way I can easily manage multiple detection projects with different parameters and datasets, while starting training with always the same command. I had something in mind like this:

```
project
├─ train
│  ├── images
│  ├── labels
├─ val
│  ├── images
│  ├── labels
├─ args.yaml
├─ data.yaml
```

where `train` and `val` are the data folders, `args.yaml` contains the config attributes I want to overwrite from `default.yaml `and `data.yaml` is the dataset definition file. Given this (or a similar) structure, what would my Python code or CLI command look like to start a training using the internal dataset and config parameters?

I cant seem to make it work or find code examples. I believe my problem is connected to using relative paths in data.yaml.

EDIT: I want to make it irrelevant from where the code or command is run.

**Comment by glenn-jocher** [comment]
@pietz just `yolo train cfg=path/to/args.yaml data=path/to/data.yaml`

**Comment by pietz** [comment]
Thanks @glenn-jocher that's exactly what I did, but I'm getting this error:

```
Dataset '/Users/pietz/Datasets/test/Labeled/980029/data.yaml' images not found ⚠️, missing paths ['/Users/pietz/Dev/test/datasets/val']
Note dataset download directory is '/Users/pietz/Dev/test/datasets'. You can update this in '/Users/pietz/Library/Application Support/Ultralytics/settings.yaml'
```

and the data.yaml looks like this:

```
path: .
train: train
val: val

names:
  0: a
  1: b
```
`data` parameter in `args.yaml` is not set

My folder structure looks like above. I don't even know where this` /datasets` path is coming from that it mentioned. It's definitely not in the absolute paths I'm providing to the command.

**Comment by glenn-jocher** [comment]
@pietz thank you for reaching out. For the error you're experiencing, it might be arising due to relative paths specified in your data.yaml file. The 'path: .' in your data.yaml is using a relative path, which assumes that the dataset directory is the same as the directory where you're running the script.

The '/datasets' path that it mentions is the default download directory for datasets in Ultralytics YOLOv8. If the datasets specified aren't found relative to the working directory, it looks in this path.

To handle this, you may want to try changing your paths in data.yaml to absolute paths, so the location of the datasets is unambiguous, regardless of where the command is being run from. For your 'names' field in data.yaml, it should be a list of strings (the names of the classes). If your classes are 'a' and 'b', it should look like this: `names: ['a', 'b']`.

As a best practice, to avoid any issues with paths and ensure that your system always finds the datasets correctly, it is recommended using absolute paths in your configuration files whenever possible.

**Comment by pietz** [comment]
Thank you @glenn-jocher . I expected that's the reason. I will rethink my folder structure. Keep args.yaml and data.yaml where the code is run and keep the data somewhere else.

**Comment by glenn-jocher** [comment]
Thank you @pietz for your valuable feedback and kind words of appreciation. We understand your use case and the need for ease of use in terms of dataset and configuration sharing. Indeed, working with absolute paths does pose a problem when sharing projects across systems, as they tend to differ.

One potential solution could be to package your data and configuration in a manner that becomes independent of the system's file structure. While user-specific absolute paths add some limitations in terms of collaboration and transfers, having relative paths could make the projects more portable.

At YOLOv8 we work continuously to improve and facilitate the best possible user experience. User scenarios, such as the one you've shared, will indeed be given consideration and we look forward to making the collaboration and data sharing process seamless and efficient.

Again, thank you for using our library and for your thoughtful feedback. We appreciate your contribution in helping us enhance our offerings.

**Comment by glenn-jocher** [comment]
@pietz, thank you for sharing your workaround solution for the path handling challenge you were facing. It shows good initiative and resourcefulness, and it's a great way to make the dataset and project folder more portable, as you mentioned before. 

Your Python script essentially automates the process of creating and configuring the data.yaml file based upon the given information. This is a clever solution, ensuring the correct absolute paths are used for each user, without manual intervention needed.

Your approach certainly seems like a practical one for your specific use case and could be beneficial for others facing similar challenges. It’s always helpful hearing about new ways users are adapting and extending the use of YOLOv8 to meet their unique requirements.

We appreciate you taking the time to share this solution with the community and will certainly keep it in mind. Thank you also for the kind words about YOLOv8. We’re glad to hear the library has been useful for you!
