### ISSUE TITLE
MPS apparently does not work with macOS 12.3.x

### ISSUE THREAD

**Issue by DP1701** [ultralytics/ultralytics#3967]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello everyone, has anyone by chance managed to start the training with MPS support under macOS 12.3.x? Unfortunately it does not work for me. See pictures:

<img width="1480" alt="1" src="https://github.com/ultralytics/ultralytics/assets/68444979/540cfbb6-8501-4410-b609-81a8fe76c72e">
<img width="1510" alt="2" src="https://github.com/ultralytics/ultralytics/assets/68444979/5a1d78be-1773-446a-980a-7947d2104aa1">

Current configuration:
macOS 12.6.8
M1 Max
Python 3.10.11
Completely new installation of YOLOv8

**Comment by DP1701** [comment]
PyTorch Preview (Nightly) did not work either

**Comment by glenn-jocher** [comment]
Upgrade your macOS should solve the problem as the warning in your screenshot says.

Works for me on latest macOS.
