### ISSUE TITLE
 ModuleNotFoundError: No module named 'ultralytics.data'

### ISSUE THREAD

**Issue by Xyihang** [ultralytics/ultralytics#3968]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

pip install  ultralytics，why this？？？
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_32152\4208601636.py in <module>
----> 1 from ultralytics.data.annotator import auto_annotate

ModuleNotFoundError: No module named 'ultralytics.data'

**Comment by glenn-jocher** [comment]
@Xyihang works for me. Your `ultralytics` package may be out of date. Try updating with `pip install -U ultralytics`

<img width="689" alt="Screenshot 2023-07-26 at 19 17 53" src="https://github.com/ultralytics/ultralytics/assets/26833433/9d4484e6-ef9a-4694-bafa-e850aa3f3e26">
