### ISSUE TITLE
Image size when training model

### ISSUE THREAD

**Issue by mfloto** [ultralytics/ultralytics#3971]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

We train a model with `imgsz=1280`, but after training the input dimensions are `[608, 1280]`.
1. Why does it use 608 for height?
2. Shouldn't it train on `[1280, 1280]` by default?

When predicting, we use `imgsz=[736, 1280]`, but it predicts on a resolution of `[608, 1280]`.

3. What effect does the parameter `imgsz` have on prediction if it is set to a list that differs from the resolution the model was trained on?
4. Does it replace the first layer?
5. Does this affect the inference time and accuracy, as the model predicts on a larger number of inputs?

**Comment by mfloto** [comment]
Thank you for the detailed description. It really helped a lot to understand how YOLO operates

**Comment by pderrenger** [comment]
@mfloto you're very welcome! I'm glad to hear that the information was helpful for you. If you have any more questions about YOLOv8 or anything else, feel free to ask. Happy to help!
