### ISSUE TITLE
is evolve arg coming back?

### ISSUE THREAD

**Issue by pydoni** [ultralytics/ultralytics#3978]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I've noticed that in the docs we can specify all the hyperparameters on the command, but I've noticed that the evolve arg that helped finding the best hyp params is not available, is this feature on the making, or it was left behind for some specific reason?

**Comment by glenn-jocher** [comment]
@pydoni hello and thank you for your question on the evolve argument!

As of now, we don't have plans to reintroduce the evolve argument in YOLOv8. The evolve argument was previously used for hyperparameter optimization, which essentially performs a genetic algorithm search over a pre-defined hyperparameter space to improve model accuracy.

This feature was actually quite computationally intensive, and our team has found that most users can achieve robust and effective training with the default set of hyperparameters provided in our models.

Moving forward, we are focusing more on improving the default values themselves and the overall performance and efficiency of our models. That said, we are always open to feedback and suggestions from the community, so if there's significant demand, we might consider bringing back such a feature in a future update.

I hope this provides some clarity. Keep up with our updates and, as always, happy training!

**Comment by pydoni** [comment]
Thanks for the answer @glenn-jocher ! I was wondering if it was left behind because of the computing cost, thanks for clarifying that!

**Comment by glenn-jocher** [comment]
You're welcome @pydoni! Indeed, our primary intention is to streamline the process and make it as resource-efficient as possible, while still ensuring high accuracy and performance. We welcome any questions or suggestions you might have in the future. Feel free to raise them. Thank you for being a part of our Ultralytics and YOLOv8 community, and happy coding!
