### ISSUE TITLE
Custom Train issues with Multi GPU

### ISSUE THREAD

**Issue by dbparkJ** [ultralytics/ultralytics#3981]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

It doesn't move on after AMP checks passed
By the way, when using 1 GPU, it works fine, what's the problem?

console msg : 
Ultralytics YOLOv8.0.143 🚀 Python-3.9.16 torch-2.0.1+cu117 CUDA:0 (NVIDIA A40, 45483MiB)
                                                            CUDA:1 (NVIDIA A40, 45483MiB)
                                                            CUDA:2 (NVIDIA A40, 45483MiB)
                                                            CUDA:3 (NVIDIA A40, 45483MiB)
engine/trainer: task=detect, mode=train, model=yolov8x.pt, data=/home/geon_AI/AI_Labeled_Data/test_yolov8/sample_data/model.yaml, epochs=200, patience=50, batch=64, imgsz=640, save=True, save_period=-1, cache=False, device=[0, 1, 2, 3], workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.8, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train2
Overriding model.yaml nc=80 with nc=11

                   from  n    params  module                                       arguments
  0                  -1  1      2320  ultralytics.nn.modules.conv.Conv             [3, 80, 3, 2]
  1                  -1  1    115520  ultralytics.nn.modules.conv.Conv             [80, 160, 3, 2]
  2                  -1  3    436800  ultralytics.nn.modules.block.C2f             [160, 160, 3, True]
  3                  -1  1    461440  ultralytics.nn.modules.conv.Conv             [160, 320, 3, 2]
  4                  -1  6   3281920  ultralytics.nn.modules.block.C2f             [320, 320, 6, True]
  5                  -1  1   1844480  ultralytics.nn.modules.conv.Conv             [320, 640, 3, 2]
  6                  -1  6  13117440  ultralytics.nn.modules.block.C2f             [640, 640, 6, True]
  7                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]
  8                  -1  3   6969600  ultralytics.nn.modules.block.C2f             [640, 640, 3, True]
  9                  -1  1   1025920  ultralytics.nn.modules.block.SPPF            [640, 640, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  3   7379200  ultralytics.nn.modules.block.C2f             [1280, 640, 3]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  3   1948800  ultralytics.nn.modules.block.C2f             [960, 320, 3]
 16                  -1  1    922240  ultralytics.nn.modules.conv.Conv             [320, 320, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  3   7174400  ultralytics.nn.modules.block.C2f             [960, 640, 3]
 19                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   7379200  ultralytics.nn.modules.block.C2f             [1280, 640, 3]
 22        [15, 18, 21]  1   8728561  ultralytics.nn.modules.head.Detect           [11, [320, 640, 640]]
Model summary: 365 layers, 68163201 parameters, 68163185 gradients

Transferred 589/595 items from pretrained weights
DDP command: ['/home/geon_AI/AI_WORK/JM_virtualenv/bin/python3', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '54341', '/home/geon_AI/AI_Labeled_Data/test_yolov8/train/train.py']
Overriding model.yaml nc=80 with nc=11
Transferred 589/595 items from pretrained weights
DDP info: RANK 0, WORLD_SIZE 4, DEVICE cuda:0
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅

### Environment

- Ultralytics YOLOv8.0.143 🚀 Python-3.9.16 torch-2.0.1+cu117 
- CUDA:0 (NVIDIA A40, 45483MiB)
- CUDA:1 (NVIDIA A40, 45483MiB)
- CUDA:2 (NVIDIA A40, 45483MiB)
- CUDA:3 (NVIDIA A40, 45483MiB)

- OS : Centos7
- Python : 3.9.16  

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A40          Off  | 00000000:01:00.0 Off |                    0 |
|  0%   41C    P0    83W / 300W |   1048MiB / 46068MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A40          Off  | 00000000:25:00.0 Off |                    0 |
|  0%   42C    P0    84W / 300W |    780MiB / 46068MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A40          Off  | 00000000:81:00.0 Off |                    0 |
|  0%   40C    P0    79W / 300W |    780MiB / 46068MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A40          Off  | 00000000:C7:00.0 Off |                    0 |
|  0%   42C    P0    80W / 300W |    740MiB / 46068MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     78397      C   ...JM_virtualenv/bin/python3     1046MiB |
|    1   N/A  N/A     78398      C   ...JM_virtualenv/bin/python3      778MiB |
|    2   N/A  N/A     78399      C   ...JM_virtualenv/bin/python3      778MiB |
|    3   N/A  N/A     78400      C   ...JM_virtualenv/bin/python3      738MiB |
+-----------------------------------------------------------------------------+

### Minimal Reproducible Example

from ultralytics import YOLO
import os

os.environ["OMP_NUM_THREADS"] = "4"

model = YOLO('yolov8x.pt')
model.train(
    data=r'/home/geon_AI/AI_Labeled_Data/test_yolov8/sample_data/model.yaml',
    epochs=200,
    batch=16,
    device=[0,1,2,3],
    iou=0.8
)

### Additional

Additionally I'm curious about DDP setting, in my code I've set it up for a threading environment like that but if that's wrong please tell me

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@dbparkJ DDP training works correctly, but I'm not sure what effect your OMP env variable setting may have. You can start very simply with CLI or Python, see https://docs.ultralytics.com/modes/train/#multi-gpu-training

**Comment by dbparkJ** [comment]
@glenn-jocher 
Thank you for your answer.
I've read and run DOCS countless times above, but it didn't work.

I proceeded without additional suspicious parts and the results are as follows.

`import os`
`os.environ["OMP_NUM_THREADS"] = "4"`

If I don't insert this code, you can see the following Warning message in the console window, and the code still stops in the AMP part.
`WARNING:__main__:`
`*****************************************`
`Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.`
`*****************************************`

I also found a part of this link that asked me a similar problem, but I don't think the answer came out yet.
[https://github.com/ultralytics/ultralytics/issues/2927#issuecomment-1636648519](url)

**Comment by glenn-jocher** [comment]
Hi @dbparkJ,

It looks like you are facing difficulties with the AMP part when the "OMP_NUM_THREADS" environment variable is not set to "4", and are receiving a warning about the potential of your system being overloaded.

The warning you're seeing is designed to alert users that setting the "OMP_NUM_THREADS" environment too high might cause the system to be overloaded. It suggests further fine-tuning of this variable for optimal performance as needed. 

The recommended setting for "OMP_NUM_THREADS" does depend on your specific use case and your hardware setup. Often, it is advised to start with a low number and then gradually increase until you reach an optimal performance level that does not overload your system.

On the other hand, the AMP (Automatic Mixed Precision) may not perform well with some specific setups. If the problem persists, it may be worth investigating if your specific environment fully supports AMP. If not, disabling AMP might be worth considering as well.

Regarding the linked issue, our team is regularly monitoring and addressing issues raised by the community. We'll ensure to provide an update as soon as we have one.

Remember, getting the optimal performance is often a task of fine-tuning and experimenting with different settings. Your patience and persistence will pay off!

**Comment by dbparkJ** [comment]
@glenn-jocher 
Thank you for your answer
First of all, changing the amp setting to a false value still does not work.

 So I'm going to ask you one more question about multi-GPU.
As far as I know, multi-GPU learns by dividing the total amount of learning by 1/n.
So I'm trying to use multi-GPU for fast learning speed.

If the concept I know is wrong, please reply.

FYI my GPU A40 has about 48GB of memory per unit However, I only use 25GB of memory for model training with the value I set. 
So, I wonder if that's why multi-GPU doesn't apply

**Comment by glenn-jocher** [comment]
Hi @dbparkJ, 

You're correct that multi-GPU training generally divides the total learning among the GPUs, thereby effectively reducing the learning time. In theory, if you double the number of GPUs, you should be able to complete the training almost twice as fast, assuming everything else remains the same.

The utilization of GPU memory is dependent on several factors, including the size of your model, the batch size, and the complexity of computation graph among other things. It's not uncommon to see that not all the GPU memory is being utilized, especially if you are restricting the memory usage for model training.

Your GPU memory (48GB on A40) should be more than adequate for most deep learning tasks. If not all memory is being used, it's not necessarily an issue. However, if you're seeing that the multi-GPU setup isn't improving the speed as expected, it could be due to other bottleneck factors such as data loading times, inter-GPU communication, etc.

While setting AMP to false didn't resolve your issue, it's worth exploring other potential sources of the problem such as dataset size, model complexity, and training configurations. As always, debugging this requires a systematic approach of ruling out one factor after another.

I hope that helps, and feel free to ask if you have any more questions!

**Comment by dbparkJ** [comment]
@glenn-jocher 
I found something unusual today while trying to turn my model into a multiGPU.
My CUDA version is 11.8
The console window says it uses 11.7 Is this going to be a problem?

Also, interestingly, even with a single GPU, it says 11.7, but it's still trained

Ultralytics YOLOv8.0.146 🚀 Python-3.9.16 torch-2.0.1+cu117 CUDA:0 (NVIDIA A40, 45483MiB)
                                                            CUDA:1 (NVIDIA A40, 45483MiB)
                                                            CUDA:2 (NVIDIA A40, 45483MiB)
                                                            CUDA:3 (NVIDIA A40, 45483MiB)
engine/trainer: task=detect, mode=train, model=yolov8x.pt, data=/home/geon_AI/AI_Labeled_Data/model_file/model_data/model.yaml, epochs=200, patience=50, batch=32, imgsz=640, save=True, save_period=-1, cache=False, device=[0, 1, 2, 3], workers=32, project=None, name=2023.08.02_batch32_imgsz640_workers32, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.8, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/2023.08.02_batch32_imgsz640_workers32
Overriding model.yaml nc=80 with nc=11

                   from  n    params  module                                       arguments
  0                  -1  1      2320  ultralytics.nn.modules.conv.Conv             [3, 80, 3, 2]
  1                  -1  1    115520  ultralytics.nn.modules.conv.Conv             [80, 160, 3, 2]
  2                  -1  3    436800  ultralytics.nn.modules.block.C2f             [160, 160, 3, True]
  3                  -1  1    461440  ultralytics.nn.modules.conv.Conv             [160, 320, 3, 2]
  4                  -1  6   3281920  ultralytics.nn.modules.block.C2f             [320, 320, 6, True]
  5                  -1  1   1844480  ultralytics.nn.modules.conv.Conv             [320, 640, 3, 2]
  6                  -1  6  13117440  ultralytics.nn.modules.block.C2f             [640, 640, 6, True]
  7                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]
  8                  -1  3   6969600  ultralytics.nn.modules.block.C2f             [640, 640, 3, True]
  9                  -1  1   1025920  ultralytics.nn.modules.block.SPPF            [640, 640, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  3   7379200  ultralytics.nn.modules.block.C2f             [1280, 640, 3]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  3   1948800  ultralytics.nn.modules.block.C2f             [960, 320, 3]
 16                  -1  1    922240  ultralytics.nn.modules.conv.Conv             [320, 320, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  3   7174400  ultralytics.nn.modules.block.C2f             [960, 640, 3]
 19                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   7379200  ultralytics.nn.modules.block.C2f             [1280, 640, 3]
 22        [15, 18, 21]  1   8728561  ultralytics.nn.modules.head.Detect           [11, [320, 640, 640]]
Model summary: 365 layers, 68163201 parameters, 68163185 gradients

Transferred 589/595 items from pretrained weights
DDP command: ['/home/geon_AI/AI_WORK/JM_virtualenv/bin/python3', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '34388', '/home/geon_AI/AI_WORK/JM_WORK/2023.07.30_batch64_imgsz320_workers32.py']
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Overriding model.yaml nc=80 with nc=11
Transferred 589/595 items from pretrained weights
DDP info: RANK 0, WORLD_SIZE 4, DEVICE cuda:0
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A40          Off  | 00000000:01:00.0 Off |                    0 |
|  0%   50C    P0   134W / 300W |  26328MiB / 46068MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A40          Off  | 00000000:25:00.0 Off |                    0 |
|  0%   42C    P0    84W / 300W |    780MiB / 46068MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A40          Off  | 00000000:81:00.0 Off |                    0 |
|  0%   40C    P0    80W / 300W |    780MiB / 46068MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A40          Off  | 00000000:C7:00.0 Off |                    0 |
|  0%   42C    P0    80W / 300W |    740MiB / 46068MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     34903      C   ...JM_virtualenv/bin/python3     1046MiB |
|    0   N/A  N/A     35040      C   python3                         25268MiB |
|    1   N/A  N/A     34904      C   ...JM_virtualenv/bin/python3      778MiB |
|    2   N/A  N/A     34905      C   ...JM_virtualenv/bin/python3      778MiB |
|    3   N/A  N/A     34906      C   ...JM_virtualenv/bin/python3      738MiB |
+-----------------------------------------------------------------------------+
