### ISSUE TITLE
Define which class to track

### ISSUE THREAD

**Issue by Chewbathra** [ultralytics/ultralytics#3985]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

It is possible to predict all classes but track only 1,  to increase prediction speed ?
I didn't saw any parameters in the track() method for that.

**Comment by glenn-jocher** [comment]
@Chewbathra hello,

Thank you for reaching out to us with your question. 

Yes, it's indeed possible to predict all classes but track only one to potentially increase prediction speed. While there is no direct parameter in the track() function to control this, it can be achieved indirectly. 

After running a prediction using the YOLOv8 model, you get output which contains the class IDs of the detected objects amongst other details. At this point, you can filter out the class you're interested in and only use the detections of that particular class for tracking.

As of now, implementing this would need some customization in the post-processing and tracking stages of the code. 

Remember, YOLOv8 has been designed with the flexibility to accommodate such custom workflows. It's all about using the output effectively.

Best Regards,
Glenn Jocher
