### ISSUE TITLE
Hugging Face Yolov8 Demo

### ISSUE THREAD

**Issue by kadirnar** [ultralytics/ultralytics#399]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I wrote the demo code of yolov8 on HF platform. Would you like to add this to the readme section?

Demo: https://huggingface.co/spaces/kadirnar/yolov8

**Comment by ichsan2895** [comment]
I already test your huggingface demo and it was great 👍 . 
Hopefully you added segmentation task too

**Comment by fcakyon** [comment]
@ichsan2895 you can use https://huggingface.co/spaces/fcakyon/yolov8-segmentation for yolov8 segmentation demo :+1:
