### ISSUE TITLE
POSE    ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by sarpx** [ultralytics/ultralytics#3990]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I can't find what's the problem here, everything seems right to me

path: .datasets\pose\
train: images/1690456022/
val: images/1690456022/
nc: 1
kpt_shape: [54,2]
flip_idx: [1,0,3,2,8,9,7,6,4,5,13,12,11,10,15,14,17,16,19,18,21,20,23,22,25,24,27,26,29,28,31,30,33,32,35,34,37,36,39,38,41,40,43,42,48,49,50,51,44,45,46,47,53,52]
names: ['ttu']

### Additional

0 0.5 0.361458 0.996875 0.71875 0.89375 0.484375 0.894531 0.20625 0.01875 0.258333 0.354688 0.569792 0.896094 0.458333 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sarpx for Pose data.yaml guidance see https://docs.ultralytics.com/datasets/pose/ and for an example pose dataset see https://docs.ultralytics.com/datasets/pose/coco8-pose/

Also remember the first 5 values in each row should be class, box xywh

**Comment by glenn-jocher** [comment]
@sarpx thank you for your message and feedback. 

From your description, it does seem like possibly there could be some corruption or a formatting issue in your text files. To resolve the issue you're experiencing, I'd recommend double-checking each text file tied to your dataset to ensure the content is correctly formatted based on our guidelines. Please pay extra attention to the first 5 values in each row to confirm they should be formatted as class, box coordinates (x, y, width, height).

As for your suggestion to improve the error logging to include the problematic file, I will share this feedback with our team for further consideration. Enhancements like these could indeed improve the ease of dataset troubleshooting. We appreciate your patience and your contribution to improving YOLOv8.

**Comment by sarpx** [comment]
@glenn-jocher  I found the problem here. There is an expression of 0.000 for the positions that are not in the document. I've seen some text files get corrupted when given this way. The problem went away when I replaced them with 0.000 => 0. Thank you for your interest.

**Comment by glenn-jocher** [comment]
@sarpx I'm glad to hear that you've been able to identify and solve the problem. Indeed, ensuring the correct format and the precision of the coordinates in your text files is crucial for the successful running of your model. Your observation could be helpful to other users facing similar issues. Thank you for sharing your solution, and please don't hesitate to reach out if you have any other questions or concerns. Your contribution to improving YOLOv8 is much appreciated.
