### ISSUE TITLE
YOLOv8 Hyperparameter Tuning: architecture and image size

### ISSUE THREAD

**Issue by cherriesandwine** [ultralytics/ultralytics#3991]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have seen that Ultralytics YOLOv8 incorporates Ray Tune for hyperparameter tuning. Is there a way I can add model architectures (i.e. n, s, m... ) and image size (640, 1080, ...) as tunable parameters as well? If not, how else I could i accomplish this?

**Comment by glenn-jocher** [comment]
@cherriesandwine thank you for your inquiry. The utilization of Ray Tune in Ultralytics YOLOv8 indeed provides a powerful means for hyperparameter optimization.

Direct integration of model architectures and image size into the tuning process is not currently supported. These factors influence the model's complexity and computational requirements, which can dramatically impact the model's performance and training time.

That said, you definitely have the freedom to experiment with various architectures (i.e., 'n', 's', 'm') and image sizes (640, 1080, ...) as part of your model exploration process. You could achieve this by manually setting these parameters and running the Ray Tune hyperparameter tuning for each combination. You can iterate over desired architectures and image sizes, and for each combination, run the hyperparameter search. This lets you observe how each specific architecture and image size impacts the model's learning and performance.

It's important to remember that the search space for hyperparameter tuning can get quite large and can have a significant computational cost. Also, ensure that your image sizes are chosen thoughtfully as they directly impact the amount of memory required during training.

Happy experimenting and let us know if you have any other questions!

**Comment by cherriesandwine** [comment]
Thank you for the feedback @glenn-jocher

**Comment by glenn-jocher** [comment]
@cherriesandwine you're welcome! I'm glad to be of assistance. If you have any more questions or encounter further issues, feel free to ask. Happy experimenting with YOLOv8 and good luck with your work!
