### ISSUE TITLE
Can tracking be performed after detections?

### ISSUE THREAD

**Issue by arturovv21** [ultralytics/ultralytics#3999]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I am currently running the model.track() to track objects in Yolov8. However, I would like to know if I can perform detections in a first step using Yolov8, and then feed those detection to the tracker. Then put back the detection IDs to the corresponding boxes. Thanks!

**Comment by glenn-jocher** [comment]
@arturovv21 hi there,

The design of our YOLOv8 model architecture does indeed support this kind of operation. You can, in a two-step process, perform object detection first using YOLOv8's `model.predict()` method, and then feed the detection results to the tracker.

After completing the object detection, you will receive a list of bounding boxes, each associated with a detected object. These can directly be input into the YOLOv8 tracking function `model.track()`. The tracker will be able to use timestamps and object identities provided by the detections to facilitate in the tracking of detected objects across frames.

You would then be able to append or assign these tracking IDs back to their corresponding bounding boxes, integrating detection and tracking information. This tracking information will be in the form of IDs, allowing you to keep track of objects across video frames.

Feel free to experiment with this approach, and thank you for contributing to the YOLOv8 community with your question!

Best,
Glenn Jocher

**Comment by arturovv21** [comment]
Thanks @glenn-jocher

**Comment by glenn-jocher** [comment]
@arturovv21 you're welcome! I'm here to help. If you have any other questions or need further clarification, please don't hesitate to ask. We appreciate your interest and contribution to the YOLOv8 community!

**Comment by XU-JIA-JUN** [comment]
> @arturovv21 hi there,
> 
> The design of our YOLOv8 model architecture does indeed support this kind of operation. You can, in a two-step process, perform object detection first using YOLOv8's `model.predict()` method, and then feed the detection results to the tracker.
> 
> After completing the object detection, you will receive a list of bounding boxes, each associated with a detected object. These can directly be input into the YOLOv8 tracking function `model.track()`. The tracker will be able to use timestamps and object identities provided by the detections to facilitate in the tracking of detected objects across frames.
> 
> You would then be able to append or assign these tracking IDs back to their corresponding bounding boxes, integrating detection and tracking information. This tracking information will be in the form of IDs, allowing you to keep track of objects across video frames.
> 
> Feel free to experiment with this approach, and thank you for contributing to the YOLOv8 community with your question!
> 
> Best, Glenn Jocher

Hi, Glenn Jocher!

I encounter a similar issue, I want start to track an object when it enters a ROI region, can YOLOv8 make it happen？

But how to input the bounding boxes to the model.track(), it serves as sources or hyperparameters? I checked the  configuration page but I cannot find it. 

Thanks.

**Comment by glenn-jocher** [comment]
@XU-JIA-JUN hi there,

Yes, YOLOv8 can handle this - you can indeed start tracking an object once it enters a Region of Interest (ROI). This can be achieved by checking, during detection phase, whether the bounding box of a detected object intersects with the ROI. If so, you can then pass this object's information to the tracker.

As for your second question, the bounding boxes are not part of the hyperparameters or data sources fed directly into the `model.track()` function. The way it typically works is that the `model.track()` function operates on a sequence of video frames, and the tracking of objects is done frame by frame based on the detections made by the YOLOv8 model. There isn't a direct way to pass specific bounding boxes into the function. Instead, the tracking function will keep track of objects as they move from one frame to the next.

I hope this clarifies the process to you. Should you have more questions, feel free to ask!

Best, Glenn Jocher
