### ISSUE TITLE
Issue with GPU inference.

### ISSUE THREAD

**Issue by Bakar31** [ultralytics/ultralytics#4000]
### Bug

I have found two previous issues facing nearly same issue. I have tried the solutions provided but couldn't solve this. So, this time hoping to get a working solution.

    WARNING  ./weights/best.pt appears to require 'ultralytics.utils', which is not in ultralytics requirements.
    AutoInstall will run now for 'ultralytics.utils' but this feature will be removed in the future.
    Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
    requirements: Ultralytics requirement ['ultralytics.utils'] not found, attempting AutoUpdate...
    requirements:  Command 'pip install --no-cache "ultralytics.utils"  ' returned non-zero exit status 1.
    ModuleNotFoundError: No module named 'ultralytics.utils'
    
 I have also set 
 
     import torch
    torch.cuda.set_device(0)
  
 and 

     torch.cuda.is_available()
     true
     
 the GPU setup is correct because yolov7 runs smoothly.

Codes for loading the models

    from ultralytics import YOLO
    model = YOLO('yolov8n.pt')  # load an official model
    model = YOLO('./weights/best.pt')
    
I also passed device = 0 here as previously suggestebut got this error

    "TypeError: init() got an unexpected keyword argument 'device'"

**Comment by glenn-jocher** [comment]
@Bakar31 thank you for reaching out with your issue.

The error you're encountering seems to result from the model weights file `best.pt` still containing a deprecated dependency, `ultralytics.utils`. These dependencies are saved within model weights during training and loaded during inference. The `ultralytics.utils` package no longer exists in modern implementations of Ultralytics YOLOv8, which explains the `ModuleNotFoundError` you're experiencing.

To resolve this, there are two options:

1. You can retrain your model with the latest version of the Ultralytics YOLOv8 repo. This ensures that the weights file you create uses the current, correct dependencies.

2. You can use an official YOLOv8 model such as `yolov8n.pt` for your inference. These models are always updated to work with the latest Ultralytics packages.

As for the 'device' argument issue, here's an explanation:
The `YOLO('yolov8n.pt', device=0)` command is incorrect as there's no 'device' argument in the `YOLO` model's constructor. The `device` argument allows your model to run inference on a specific GPU if you have multiple GPUs available, but it can't be passed directly to the YOLO model as a parameter.

Instead, once your model is loaded, you can manually move your model to the desired device using `model.to(device)`. Replace 'device' with the ID of your target GPU, such as `model.to('cuda:0')` for GPU 0.

I hope this helps! If you have any more questions or encounter further issues, feel free to ask.
