### ISSUE TITLE
How to get the class of object detection output using yolov8?

### ISSUE THREAD

**Issue by ytl0623** [ultralytics/ultralytics#4007]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I wonder how can I get class of object detection output using yolov8?

The code I run like below:
`
model = YOLO( "models/best.pt" )
`
`
results = model( "data/apple.jpg" )
`

And the output is `tensor([[253.00000,  63.00000, 492.00000, 290.00000,   0.90147,   0.00000]], device='cuda:0')
`

I think the first four value means bounding box, and the last two are confidence and class.
And my problem is how to get the class value from the output?

Thanks in advance!

**Comment by glenn-jocher** [comment]
@ytl0623 sure, I'm glad you've asked this question.

From your output tensor, you're correct that the first four values correspond to the bounding box dimensions. Specifically, they are the x and y coordinates of the box's center, as well as the box's width and height.

As for the last two values, you're partially correct. The fifth value is indeed the confidence score of the detected object – this value represents how certain the model is that it has detected an object.

However, the sixth value is not a confidence value but rather the class index. In your example, the detected object's class index is 0. If you have used a pre-trained YOLO model, this class index corresponds to a certain class label available in the dataset the model was trained on. 

Note: The class index does not carry any inherent meaning by itself. It's just an identifier used to map to the actual class name (object type) in the dataset. 

Let me know if you need further clarification!

**Comment by ytl0623** [comment]
Hi, @glenn-jocher, thanking for replying me.

I have extra question that how can I specify the class name that wanted predicted.
For example, We can use the argument like `--class person` to predict only the person class.

Is there any possible in YOLOv8?

Tnaks in advance!

**Comment by glenn-jocher** [comment]
Hello @ytl0623,

Yes, there is a way to specify the class names you want to be detected with your YOLOv8 model. Just like you stated, it would be through an argument like `--class person`.

In the code where you're setting up your detection parameters, you would need to specify an array or list of class indices that correspond to the classes or objects you want your model to detect. For instance, if the "person" class index in your dataset is 0, you would specify that index 0 in your classes array or list.

Then during detection, only objects that belong to these specified classes would be detected and returned in the output. All other objects would be ignored as if they're not present in the image or video frame.

This allows for a more focused object detection and limits the output to the specific class or classes you are interested in.

Hope this answers your question! Please don't hesitate to reach out if you have any further queries.

**Comment by ytl0623** [comment]
Thank you!!! I tried it successfully.

**Comment by glenn-jocher** [comment]
@ytl0623 i'm glad to hear that you found the information helpful and were able to apply it successfully! Please feel free to return if you have any more questions in the future. Happy coding!
