### ISSUE TITLE
Does data augmentation of hyperparameters increase or transform the training data?

### ISSUE THREAD

**Issue by Soichi9** [ultralytics/ultralytics#4008]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Sorry for the basic question. I am wondering if the number of training images increases when dataagumation is performed in the hyperparameters of default.yaml. For example, when fliplr: 0.5, will only the converted images be used for learning, or will both the original images and the converted images be used for learning?

**Comment by glenn-jocher** [comment]
@Soichi9 hello, thank you for your question!

In the context of YOLOv8, data augmentation does not explicitly increase the number of training images. Rather, it dynamically applies transformations to the original images during training. This means that in each epoch, the model sees slightly different variations of the original images, which helps to improve model generalization and robustness.

To answer your specific query, when you set `fliplr: 0.5` in the hyperparameters, it means that there's a 50% chance that a left-right flip will be applied to an image during each mini-batch of training. Both the original and augmented images aren't stored separately; the augmentations are applied on-the-fly during training, and the original images are used again in the next epoch where they may or may not be augmented again, but in potentially different ways.

The main takeaway is that while data augmentation doesn't increase the raw number of images in your dataset, it effectively increases the diversity and breadth of the training set, aiding the model in learning more versatile and generalizable features. I hope this clears up your question, let me know if you have more queries or clarification needed!

**Comment by Soichi9** [comment]
@glenn-jocher Thank you for your very clear answer. To increase the number of data, it is necessary to do it in advance. It was saved because I was worried about other versions YOLO.

**Comment by glenn-jocher** [comment]
@Soichi9, I'm glad that my previous explanation was helpful to you! 

Yes, you are correct. If you're aiming to directly increase the number of images in your dataset, it should be done in advance by collecting more data or manually creating more variations of the existing data. 

However, keep in mind the power of on-the-fly data augmentation during the training process, as it can effectively enrich your dataset and enhance model performance.

Remember, quality also matters along with quantity. More images may not always lead to performance improvements if those images do not appropriately represent the variety of scenarios the model will encounter during its use.

If you have any further doubt or question, feel free to ask. Happy learning!
