### ISSUE TITLE
Update class or attributes

### ISSUE THREAD

**Issue by Tz09** [ultralytics/ultralytics#4009]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I saw this in documentation where the update(boxes=None, masks=None, probs=None).
How can I use to update the box such as to other classes?
![Screenshot 2023-07-28 163942](https://github.com/ultralytics/ultralytics/assets/93613938/635ffda8-0a2a-4ae5-a5ce-ee825b877b43)

**Comment by glenn-jocher** [comment]
@Tz09 hello, 

Thank you for your question! You're referring to the update function which is used to revise the properties of detected objects such as their bounding boxes, masks, or probabilities. If you want to update the bounding boxes, masks, or probabilities, you'd pass the updated values as parameters to this function.

However, you can't directly alter the class of the detected object with this function as it doesn't handle class attributes. The classification of objects is done during the model's prediction phase and the classes are based on what the model has been trained on.

If you wish to reassign objects to different classes after detection, it would have to be done as a separate step. You could, for example, take the output of the model, look at the class IDs assigned to each bounding box, and then assign new class IDs based on your specific requirements or rules.

As always, please make sure your modifications respect the model’s training. If an object is reassigned to a class it has never seen in training, the results may not be reliable.

I hope this answer was helpful!

**Comment by MilenioScience** [comment]
> @Tz09 hello,
> 
> Thank you for your question! You're referring to the update function which is used to revise the properties of detected objects such as their bounding boxes, masks, or probabilities. If you want to update the bounding boxes, masks, or probabilities, you'd pass the updated values as parameters to this function.
> 
> However, you can't directly alter the class of the detected object with this function as it doesn't handle class attributes. The classification of objects is done during the model's prediction phase and the classes are based on what the model has been trained on.
> 
> If you wish to reassign objects to different classes after detection, it would have to be done as a separate step. You could, for example, take the output of the model, look at the class IDs assigned to each bounding box, and then assign new class IDs based on your specific requirements or rules.
> 
> As always, please make sure your modifications respect the model’s training. If an object is reassigned to a class it has never seen in training, the results may not be reliable.
> 
> I hope this answer was helpful!

Hello i want to update my results how can i do that?, is it result.update(pass new value)?, or just update(pass new value)

**Comment by Tz09** [comment]
Hi, I just manually change the information using loop function instead of using the result.update fucntion.
For instance, you can access the box array and change the information depends on your requirements.

**Comment by glenn-jocher** [comment]
@MilenioScience hi! Yes, you indeed have the right idea! The boxes that are part of the detections can certainly be updated directly in your code after the predictions have been made by the model. You can iteratively go through the detection outputs, access the box information and modify it as per your specific needs. This way, you can change the box sizes, positions, etc.

Please make sure to respect the model's original predictions when making modifications to get the most reliable and accurate results. If you have any other questions, feel free to ask!

**Comment by MilenioScience** [comment]
> @MilenioScience hi! Yes, you indeed have the right idea! The boxes that are part of the detections can certainly be updated directly in your code after the predictions have been made by the model. You can iteratively go through the detection outputs, access the box information and modify it as per your specific needs. This way, you can change the box sizes, positions, etc.
> 
> Please make sure to respect the model's original predictions when making modifications to get the most reliable and accurate results. If you have any other questions, feel free to ask!

Thank you for your answer. Can you please give me real code example how to modify the value of detection outputs, for example there is cls array tensor value inside boxes result right?, let say i want to delete the duplicate cls element value, how can i do that?

**Comment by glenn-jocher** [comment]
@MilenioScience, sure! After you have the detections from the model, you will retrieve the 'boxes' output which is a list of bounding box coordinates. Together with 'boxes', you have 'classes' and 'scores' for each prediction made by the model. If you want to remove duplicate classes you can approach this task in several ways depending on what you mean by "duplicates". 

If by "duplicates" you mean classes that have more than one instance (like two dogs in an image) and you want to keep only one instance per class, you would need to loop over your detected classes and keep track of which classes have already been seen. If you come across a class that has already been seen, you can remove that instance.

If by "duplicates" you mean bounding boxes with the same class that overlap significantly (meaning they are probably detecting the same object in the image), you could remove these duplicates by performing Non-Maximum Suppression (NMS) which is a technique used to remove overlapping boxes. NMS is already being performed inside the YOLOv8's detect function, you can adjust the 'iou_threshold' parameter to change how much overlap is allowed.

Please remember to handle these modifications with care to ensure that the perception of the model's performance remains accurate. If the model was trained to detect multiple instances of the same class in a picture, erasing its ability to do so could unfairly degrade its apparent performance.

If you have more questions or anything is unclear, please let me know!

**Comment by MilenioScience** [comment]
Hello thank you for your answer. So here i attach my image from my code, i try to update cls atribute from result of yolov8, the new cls value is already in torch data type, but when i try to have new value the error say that can't set atribute, please help how can i solve this?
Also, i already try to train new model using iou = 1, but the result when i do prediction it give me more classes value than the iou=0.7, you can see the result from second image. Please help me
![can't set atribute_yolov8](https://github.com/ultralytics/ultralytics/assets/76505573/9e0c92eb-6ffd-44e7-98ae-faf36db8eb65)
![iou_1_result](https://github.com/ultralytics/ultralytics/assets/76505573/89583bbb-2f94-46bb-8621-97720870978c)
