### ISSUE TITLE
Only plot some of the keypoints

### ISSUE THREAD

**Issue by Keplerrrrrrrr** [ultralytics/ultralytics#4016]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, YOLOv8 is an outstanding work! Thanks for your efforts!    

As we all know that there are 17 keypoints in the human body, these keypoints and their connections are plotted in the result. Suppose I want to plot only some of the keypoints of the human body (in my task I only need the skeleton of the upper body).

Is it possible to do this by modifying the configuration file? If so, what is the name and path of the configuration file?

**Comment by Keplerrrrrrrr** [comment]
Sorry, I'd like to add a little more clarification.

If I train a model with only some of the key points on my own dataset, itwould certainly achieve the above.

However, labelling human keypoints is very time-consuming, so I would like to apply your pre-trained model 'yolov8x-pose-p6.pt' to detect human keypoints directly.

In this case, would I still be able to plot only some of the keypoints?
(I have tried to plot using data extracted from keypoints.data, but these coordinates seem to be offset or deflated, and the resulting skeleton maps are very inaccurate)

**Comment by glenn-jocher** [comment]
@Keplerrrrrrrr hello,

When you apply the pre-trained YOLOv8 model that's trained on all 17 keypoints, it's indeed going to detect all the keypoints as they are part of the trained model. However, you have the liberty to select which keypoints you want to plot from the detected keypoints.

Regarding the inaccuracies in the skeleton maps, please ensure that you are correcting the keypoints appropriately for the image dimensions and any transformations applied (like scaling or padding). The keypoints predicted by the model are relative to the height and width of the input model size, not the original image size, so they need to be properly adjusted before plotting.

Remember that modifying the keypoints displayed in the output does not require changes in the configuration file; instead, it is done in the post-processing step. That is where you want to add your logic to only plot certain keypoints.

I hope this helps! Please let me know if you have any other questions.
