### ISSUE TITLE
IndexError: index 100 is out of bounds for dimension 1 with size 100 Error

### ISSUE THREAD

**Issue by ttony0321** [ultralytics/ultralytics#4018]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

during a training i got some Warning and Error..
can i get some advice about this?
the Error is 
`IndexError: index 100 is out of bounds for dimension 1 with size 100`
and i got warnings when i start to train 
`train: WARNING ⚠️ /kaggle/working/yolo/train/img_11401_241.jpg: ignoring corrupt image/label: Label class 114 exceeds dataset class count 100. Possible class labels are 0-99`

and my data.yaml is like this

```
names:
  0: '01'
  1: '02'
  2: '03'
  3: '04'
  4: '05'
  5: '06'
  6: '07'
  7: '08'
  8: '09'
  9: '10'
  10: '11'
  11: '13'
  12: '14'
  13: '15'
  14: '16'
  15: '17'
  16: '18'
  17: '19'
  18: '20'
  19: '21'
  20: '23'
  21: '24'
  22: '25'
  23: '26'
  24: '29'
  25: '30'
  26: '31'
  27: '32'
  28: '34'
  29: '35'
  30: '37'
  31: '38'
  32: '40'
  33: '41'
  34: '42'
  35: '43'
  36: '44'
  37: '45'
  38: '46'
  39: '47'
  40: '48'
  41: '49'
  42: '50'
  43: '51'
  44: '52'
  45: '53'
  46: '54'
  47: '55'
  48: '56'
  49: '57'
  50: '58'
  51: '59'
  52: '60'
  53: '61'
  54: '62'
  55: '63'
  56: '64'
  57: '65'
  58: '67'
  59: '68'
  60: '69'
  61: '70'
  62: '72'
  63: '73'
  64: '74'
  65: '75'
  66: '76'
  67: '77'
  68: '79'
  69: '80'
  70: '81'
  71: '82'
  72: '83'
  73: '84'
  74: '85'
  75: '86'
  76: '87'
  77: '88'
  78: '89'
  79: '90'
  80: '91'
  81: '92'
  82: '93'
  83: '95'
  84: '96'
  85: '97'
  86: '98'
  87: '99'
  88: '100'
  89: '101'
  90: '102'
  91: '103'
  92: '105'
  93: '107'
  94: '108'
  95: '109'
  96: '110'
  97: '111'
  98: '113'
  99: '114'
nc: 100
path: /kaggle/working
train: yolo/train
val: yolo/val
```

and img, txt files are like 
```
/kaggle/working/yolo/label/img_6013_fc9.txt
/kaggle/working/yolo/img/img_6013_fc9.jpg
77 0.523193359375 0.456298828125 0.57666015625 0.79736328125
```

**Comment by glenn-jocher** [comment]
@ttony0321 hello! The error and warning message you're seeing are related to the label class in your data exceeding the class count specified in your data.yaml. 

The error message `IndexError: index 100 is out of bounds for dimension 1 with size 100` indicates that an attempt is being made to access an index (class label) that does not exist in your specified class labels. The labels in YOLO are zero-indexed, thus if you have 100 classes your class labels should range from 0-99. 

Your warning message `train: WARNING ⚠️ /kaggle/working/yolo/train/img_11401_241.jpg: ignoring corrupt image/label: Label class 114 exceeds dataset class count 100. Possible class labels are 0-99` is signifying that there's a label in your dataset (class '114') that exceeds the total number of classes (100) you've defined in your data.yaml file.

Based on the information provided, here's how you could solve your issue:

1. Check your labels: Ensure all your label class values fall within the range specified in your '`names`' mapping in `data.yaml` and do not exceed the highest value specified in your '`nc`' (number of classes).

2. Update your data.yaml file if necessary: If you have more than 100 classes, adjust your `data.yaml` file to represent the correct number of classes in '`nc`' field and map each class label correctly in the '`names`' field.

Remember, labeling in YOLO starts from 0 and ends at n-1 (where n is your total number of classes).

I hope this helps! Let me know if you have more questions.
