### ISSUE TITLE
trying to deploy yolov8 on jetson

### ISSUE THREAD

**Issue by coder-glitche** [ultralytics/ultralytics#4028]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hey @glenn-jocher i tried deploying yolov8 detection model on jetson first i tried git cloning the ultralytics folder and the tried installing requirements,txt listed dependencies but faced alot of issues with matplotlib instead i tried pulling the docker image and was succesfull in doing so but after that i tried running the yolo prediction command i got an error saying YOLO command not found what should i do also how do i proceed further with deepstream did the docker image contain the torch version as well or do i need to reinstall it??

**Comment by glenn-jocher** [comment]
@coder-glitche hello,

Thanks for reaching out about deploying YOLOv8 on Jetson and sorry to hear you're facing some issues!

If you have successfully pulled the Docker image, the necessary dependencies including Torch should be pre-installed within the container. Hence, there shouldn't be any need for additional installations. However, the error message "YOLO command not found" suggests there might be a problem with your PATH environment variable not including the directory where the YOLOv8 scripts reside. In Docker, scripts need to be run with the correct Python command and path. Try using the full path to the script or changing your working directory to the location of the script before running it. 

Regarding your question on DeepStream, YOLOv8 is compatible with DeepStream, but you will need to convert the trained YOLOv8 model to ONNX and then to a TensorRT optimized model. ONNX is an intermediate representation of the model, and TensorRT optimizes the model for inference on NVIDIA GPUs.

I hope this helps! If you encounter any more issues, please don't hesitate to ask.

Best regards,
Glenn
