### ISSUE TITLE
In keypoint estimation task, Is it possible to train only one keypoints?

### ISSUE THREAD

**Issue by yellowjs0304** [ultralytics/ultralytics#4036]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, THank you for nice work.
I want to training one class with one visible/unvisible keypoints.
here's my sample dataset.yaml and the dataset.
<img width="159" alt="image" src="https://github.com/ultralytics/ultralytics/assets/30281608/9cb0d6f5-68c6-4d5f-a557-a71d0a06ee25">

```
0 0.07930107526881722 0.04929577464788733 0.051075268817204304 0.09859154929577466 0.06720430107526883 0.043010752688172046 2.0

# sometimes, there's no keypoints
0 0.5622895622895623 0.19951923076923078 0.051178451178451184 0.39903846153846156 0.0 0.0 0.0
```

I think i made right format. but the code keep consider the nkpt as 2 i think.
![image](https://github.com/ultralytics/ultralytics/assets/30281608/7046066a-c163-4ac7-81b2-2e00158ba9ea)

Could you please tell me the way?

**Comment by glenn-jocher** [comment]
@yellowjs0304 yes you should be able to train on a single keypoint. See https://docs.ultralytics.com/datasets/pose/ for label format
