### ISSUE TITLE
Tracking is extremely slow on CPU

### ISSUE THREAD

**Issue by AndreaPi** [ultralytics/ultralytics#4037]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm using `yolov8_small` fine-tuned on my private dataset as a detection model, and `botsort` as tracker. I launch tracking this way:

```
from pathlib import Path
from ultralytics import YOLO

project = Path(...)
model_weights = project / '.../weights/best.pt'
source = Path('.../20230511_141553.mp4')
tracker = project / '.../custom_botsort.yaml'
device = 'cpu'
verbose = True
seed = 0
confidence_threshold = 0.3
image_size = 1280 
show = False
save = True
save_confidence = True
exist_ok = True
save_dir = project / 'logs/tracking_test'

# launch tracking
model = YOLO(model_weights)
results = model.track(
    source=source,
    tracker=tracker,
    device=device,
    verbose=verbose,
    seed=seed,
    conf=confidence_threshold,
    imgsz=image_size,
    show=show,
    save=save,
    save_conf=save_confidence,
    project=project,
    name=save_dir,
    exist_ok=exist_ok
)
```

When going from GPU (`device=0`) to CPU (`device='cpu'`) the inference time explodes from 5 ms to >910 (!!!) ms. This makes it fairly useless on edge devices. I'm using https://github.com/ultralytics/ultralytics/blob/e324af6a12517d0e2db129c045454d9b56b669f3/docker/Dockerfile as an environment **(NOTE**: it's not the latest one). Also
```
>>> ultralytics.__version__
'8.0.141'
```

Questions:
1. should I switch to https://github.com/ultralytics/ultralytics/blob/main/docker/Dockerfile-cpu? https://github.com/ultralytics/ultralytics/blob/main/docker/Dockerfile-python? Which is the difference?
2. If do switch, should I also retrain my detection model, before rerunning tracking? 

### Additional

Here is the `botsort` configuration, in case it helps:

```
appearance_thresh: 0.25
cmc_method: sparseOptFlow
match_thresh: 0.9
new_track_thresh: 0.6
proximity_thresh: 0.5
track_buffer: 60
track_high_thresh: 0.5
track_low_thresh: 0.1
tracker_type: botsort
with_reid: false
```

**Comment by glenn-jocher** [comment]
@AndreaPi see https://docs.ultralytics.com/modes/predict/ for streaming mode inference, but if you need to run on CPU you're best served exporting to either ONNX or OpenVINO first. See https://docs.ultralytics.com/integrations/openvino/ for CPU benchmarks.

**Comment by glenn-jocher** [comment]
<img width="1352" alt="Screenshot 2023-07-30 at 15 18 39" src="https://github.com/ultralytics/ultralytics/assets/26833433/9bb84064-224e-4e52-9191-fca904d718dc">

**Comment by AndreaPi** [comment]
@glenn-jocher thanks for the suggestions! I didn't know about OpenVINO. I'll try that, and if performances still don't match my target, I'll open another issue. In meantime, do you think using 
 https://github.com/ultralytics/ultralytics/blob/main/docker/Dockerfile-cpu, or is it enough to use https://github.com/ultralytics/ultralytics/blob/e324af6a12517d0e2db129c045454d9b56b669f3/docker/Dockerfile  (as I'm currently doing) and just export to OpenVINO?

**Comment by glenn-jocher** [comment]
@AndreaPi you can certainly try using our Dockerfile specifically designed for CPU (`Dockerfile-cpu`). It's configured and optimized to provide better performance when running on CPU.

However, I recommend trying the current setup but exporting the model to OpenVINO first as it has specific optimizations for running models on CPU. It converts models into a format that is highly optimized for Intel hardware, which considerably improves inference speed.

Remember, the model format is just as important as the environment it's running in, if not more so, when considering performance on specific hardware.
