### ISSUE TITLE
Hard to understand what changes among versions

### ISSUE THREAD

**Issue by AndreaPi** [ultralytics/ultralytics#4039]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

This project doesn't use releases, and there are minor updates nearly daily. 

#### Pros
Bugs are fixed quickly, and we get new features very often

#### Cons
It's difficult to understand which is the current version of the projects, and what are the changes among a version and the other. For example, I'm running `ultralytics 8.0.141`, and the current version (which I determined by looking at the last closed PR https://github.com/ultralytics/ultralytics/pull/4034) seems to be `ultralytics 8.0.145`

#### Questions

-  how do I determine the current version of the project, without having to clone it again and checking the imported version?
- will you consider adding a **"What's new"** section somewhere (either in the docs or in the README) so that users can understand if they should switch to the latest version or not?

**Comment by glenn-jocher** [comment]
@AndreaPi thanks for the feedback! The team is extremely overworked and it's all we can do to update the code, we need additional employees for better issue response and documentation etc. 

For training tasks the code will automatically alert you if a newer version is available. For predict tasks it will not, but you can always run `pip install -U ultralytics` to get the latest, or `git pull` if you git cloned.

Most of the changes and the patch descriptions can be seen directly in the commit history in https://github.com/ultralytics/ultralytics/commits/main

**Comment by AndreaPi** [comment]
Hi @glenn-jocher , thanks for the answer! Good to know that during training the code will tell me about a new version. It would be good to get a summary of the changes, so that one can determine whether to keep the current version (for stability) or to update (to get better features/bug fixes), but I understand that's not currently available. I'll close the issue
