### ISSUE TITLE
How to use stream=True and save a video of results when doing object tracking?

### ISSUE THREAD

**Issue by AndreaPi** [ultralytics/ultralytics#4040]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I run tracking using the configuration shown in https://github.com/ultralytics/ultralytics/issues/4037. **Note** that 

- `show` is set to `False` (I'm running on a headless server)
- `save` is set to `True` (I want to save my results to an `avi` video file)
- `save_conf` is set to `True` too. 

I want to reduce memory consumption, since the final deployment would be on a edge device. For this reason, I want to test the `stream=True` parameter:

```
from pathlib import Path
from ultralytics import YOLO

project = Path('/workspace/andrea/cv-flange-tracking-from-video/')
model_weights = project / 'logs/yolov8_small_bs8_300e_imgsz1280_lr1e-3/weights/best.pt'

source = Path('/data/robotics/flange_tracking/20230511_141553.mp4')
tracker = project / 'src/cv_flange_tracking_from_video/configs/custom_botsort.yaml'
device = 'cpu'
verbose = True
seed = 0
confidence_threshold = 0.3
image_size = 1280 # models were trained with image size 1280
show = False
save = True
save_confidence = True
exist_ok = True
save_dir = project / 'logs/tracking_test'
stream = True

# launch tracking
model = YOLO(model_weights)
results = model.track(
    source=source,
    stream=True,
    tracker=tracker,
    device=device,
    verbose=verbose,
    seed=seed,
    conf=confidence_threshold,
    imgsz=image_size,
    show=show,
    save=save,
    save_conf=save_confidence,
    project=project,
    name=save_dir,
    exist_ok=exist_ok
)
```

However,  when I run this, the process finisheswith exit code 0 nearly immediately (normally, it takes more than 10 minutes) and no result video is saved anywhere. I guess the reason is that when `stream=True`, `model.track` returns a `generator` object, and no inference is actually performed unless I step through the generator.

**Comment by glenn-jocher** [comment]
@AndreaPi results is a python iterator. You're free to loop through it to get each frame's result. See https://docs.ultralytics.com/modes/predict/

<img width="1069" alt="Screenshot 2023-07-30 at 15 16 38" src="https://github.com/ultralytics/ultralytics/assets/26833433/5836d1cd-9c76-480d-ba61-38ce34288fa1">

**Comment by aypetrunin** [comment]
@glenn-jocher, There is a difference in the work of two commands written in Python and CLI. 
Command on CLI works well: **!yolo task=detect mode=predict model='/content/best_V4_task4_yolo8m.pt' conf=0.25 source = '/content/test3.mp4' save=True** - 80 ms frame processing.
Command on Python works bad: **results = model.predict(source='/content/test3.mp4', conf=0.25, save=True)**  - 35000 ms frame processing  and it warns you to use **stream=True**.
After adding stream=True there is no predicate process. **results = model.predict(source='/content/test3.mp4', conf=0.25, save=True, stream=True)**.

How to get a command written in Python to work as CLI?

**Comment by AndreaPi** [comment]
> @AndreaPi `results` is a python generator. You're free to loop through it to get each frame's result. See https://docs.ultralytics.com/modes/predict/

Hi Glenn,

I'm not talking about `predict`, but about `track`. How do I iterate through the `model.track` results in order to write the output video to disk? In other words, how do I complete the following code?

```
results = model.track(
    source=source,
    stream=True,
    tracker=tracker,
    device=device,
    verbose=verbose,
    seed=seed,
    conf=confidence_threshold,
    imgsz=image_size,
    show=show,
    save=save,
    save_conf=save_confidence,
    project=project,
    name=save_dir,
    exist_ok=exist_ok
)
for result in results:
      ????
```

**Comment by glenn-jocher** [comment]
@aypetrunin when you use `stream=True` in `model.track`, indeed it returns a generator object. Typically, in a generator function, the process execution stops and yields a value on every iteration, and the function remembers the state it was during the last yield operation to restart execution from there in subsequent calls.

In the case of `model.track` with `stream=True`, at each iteration it yeops the output for each frame.

Now, for your question about saving the results into a video, you don't need to manually iterate over the results to save them per se. The tracking results should be automatically saved in the `save_dir` defined in your configuration, assuming `save=True`. 

So the script you provided should play the video, perform object tracking, and then save the results in your specified directory - all without needing for you to do anything to the `results` generator.

If the results are not being saved as expected, please provide more details about the issue, including any errors or messages you're seeing, and I can help troubleshoot further.

**Comment by AndreaPi** [comment]
Hi @glenn-jocher, I'll test your suggestion and let you know how it goes.

**Comment by glenn-jocher** [comment]
@AndreaPi hello,

Great! I look forward to your update. Don't hesitate to reach out if you need further assistance or have additional questions. We're here to help.

Best regards,
Glenn Jocher

**Comment by bit-scientist** [comment]
@AndreaPi any updates on this?

**Comment by totogot** [comment]
Not sure if this thread was ever resolved (and I personally couldn't find any solutions elsewhere on other threads), so thought it worth posting here in case it helps others in the future.

The simplest way I found the get the same functionality - be it model.predict() or model.track() -  as you get when not using the stream = True functionality is simply:

```
results = model.predict(
    source=source,
    stream=True
)

for r in results:
next(results)
```

**Comment by glenn-jocher** [comment]
Hello @totogot,

Thank you for sharing the solution that worked for you. Yes, when using a generator with `stream=True`, you can step through it using `next()` or a for-loop to process the frames one by one. This should indeed activate the typical functionalities such as inference and saving output for each iteration. 

It's always useful to share insights like these, as they can help others who might encounter a similar situation. Your contributions to the YOLO community are very much appreciated!

If there's anything else you or others need help with, feel free to ask.
