### ISSUE TITLE
when training classify model, are the images  cropped? how to close the image crop?

### ISSUE THREAD

**Issue by XiangjiBU** [ultralytics/ultralytics#4041]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

when training classify model , are the images  cropped? 
if cropped, how to close the image crop? because I need to keep the whole image.

I tried to set : scale=0, mosaic=0 , but it seems not work, because I find the train_batch0.jpg, train_batch1.jpg are still cropped images

**Comment by XiangjiBU** [comment]
it seems yolov8 always do CenterCrop, but it's not good for may dataset. because it will loss key information

**Comment by glenn-jocher** [comment]
@XiangjiBU hello, thank you for bringing this to attention. 

In YOLOv8, the default preprocessing step does indeed involve modifications to the images, which may include center cropping among other transformations. These processes are designed to aid the model during training by providing different variations and perspectives of the original data, and can dramatically improve model performance.

However, we understand that there are specific use cases like yours where you may want to retain the entire image during training. 

To disable center cropping, you would need to modify the data augmentation settings in the `hyp` dictionary located in the training script. Specifically, you can look for the key related to cropping in this dictionary and set its value to 0.

Please note, by turning off certain image augmentations such as cropping, it may have an impact on the model's performance as it now has less diversified data to learn from. It's always important to thoroughly validate the trained model to ensure it meets your expectations.

We hope this information helps you. Let us know if you have any other questions, we’re here to assist!
