### ISSUE TITLE
GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by marziyemahmoudifar** [ultralytics/ultralytics#4060]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

 I want to train yolov8x_seg and my torch version is '2.0.1+cu117', cuda version is '11.8', python 3.10.12 and when I run ultralytics.checks()
command the output is Ultralytics YOLOv8.0.145 🚀 Python-3.10.12 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24260MiB)
Setup complete ✅ (20 CPUs, 125.5 GB RAM, 436.9/457.1 GB disk). But in train phase this error occurred: RuntimeError: GET was unable to find an engine to execute this computation
can you help me to solve that?
Thanks in advance

**Comment by glenn-jocher** [comment]
@marziyemahmoudifar hi, thanks for bringing this issue to our attention. The error "GET was unable to find an engine to execute this computation" typically arises in PyTorch when there's a mismatch in the versions of CUDA installed on your system and the CUDA version which your PyTorch is built with.

From your system information, it appears you have CUDA version '11.8' installed, but your PyTorch version '2.0.1+cu117' is built with CUDA 11.7. This discrepancy could be causing the issue.

To resolve this, you should install a version of PyTorch that is built with your installed CUDA version. Please keep in mind to update the PyTorch version without changing your Python, CUDA, and system settings.

Alternatively, you may also consider reinstalling the CUDA version to match the one that your PyTorch version was built with. With YOLOv8, we try to ensure compatibility with a range of PyTorch and CUDA versions so it should continue to perform well even if you need to change your setup slightly.

Please try resolving the version mismatch and let us know if the issue persists. We're here to help. Thanks!

**Comment by marziyemahmoudifar** [comment]
Thanks, it was fixed.

**Comment by glenn-jocher** [comment]
@marziyemahmoudifar i'm glad to hear that your issue was resolved! If you encounter any other issues or have questions in the future, please don't hesitate to reopen the issue or create a new one. We're always here to help. Happy coding with YOLOv8!

**Comment by dongrixinyu** [comment]
> 

Excuse me, I have encountered the same problem and read your advice. And I am still confused.

`nvidia-smi` prints a cuda driver version  and `nvcc` also prints a cuda runtime version. These two versions dont match perfectly in many cases. So `pytorch` version should be in consistent with which cuda version?

**Comment by marziyemahmoudifar** [comment]
Pytorch version should be match with nvcc smi cuda version.

**Comment by glenn-jocher** [comment]
@dongrixinyu, thanks for your question. So yes, in general, PyTorch's CUDA version should match the version as per your CUDA runtime (the version you get using `nvcc --version`). The CUDA driver version, on the other hand, should be equal to or greater than the CUDA runtime version.

So, to ensure compatibility, please make sure the CUDA version that your PyTorch is built with is the same as your installed CUDA runtime version. Doing so could help resolving compatibility issues. 

Let me know if you have any more questions.

**Comment by dongrixinyu** [comment]
thank you guys

**Comment by glenn-jocher** [comment]
@dongrixinyu you're welcome! If you have any more questions or need further assistance, feel free to ask. Happy coding with YOLOv8!

**Comment by dongrixinyu** [comment]
> @dongrixinyu you're welcome! If you have any more questions or need further assistance, feel free to ask. Happy coding with YOLOv8!

I still have an algorithm question about small object detection. UAV detection.

for some images captured by cameras fixed on the ground, capturing images of the sky, aiming to detect whether there are uav-s existed in the sky.

![000004](https://github.com/ultralytics/ultralytics/assets/27001062/a4fefe83-1005-4bb5-b55a-b2d2097e1ee4)
![1691637067425](https://github.com/ultralytics/ultralytics/assets/27001062/1fc3a074-97a4-4214-9b66-a0f4e75b43b6)

these uav-s are so small that people and AI models can hardly detect there position like images above. so, will yolo-v9 or yolo-vn consider taking a sequence of previous images into account? in order to detect these mobile small object?

**Comment by glenn-jocher** [comment]
@dongrixinyu That's an interesting question. Currently, YOLOv8 considers each frame in isolation for object detection, without taking into account a sequence of historical images. This architecture works well for many applications but may have limitations in detecting small, moving objects like UAVs in the sky.

Your idea of taking a sequence of previous images into account can be a beneficial approach for detecting these types of objects, as it would allow the model to consider changes in the scene over time. This concept is similar to how recurrent neural networks (RNNs), or more specifically Convolutional LSTM models, work for sequence-based tasks.

As of now, we haven't announced plans for such a feature in future versions of YOLO. However, we appreciate your suggestion and will consider this for our future releases as improving the model's performance on a variety of scenarios is one of our top priorities.

Until then, I'd recommend exploring post-processing techniques like tracking algorithms that might help improve detection for these kinds of scenarios by providing temporal context. Or consider using a video processing network designed to handle sequences, such as 3D convolutional networks or recurrent networks.

Thanks!

**Comment by dongrixinyu** [comment]
Thank you!

If your team wants maintainers, may I introduce myself?

I also maintained several github repos. 
[JioNLP](https://github.com/dongrixinyu/JioNLP), this is a text-preprocessing and parsing tool for Chinese chars.
[jiojio](https://github.com/dongrixinyu/jiojio), this is a word segmentation tool written in C and wrapped with Python.

So, recently I focus my keypoint on image processing and wanna do something interesting. If you need any help, I can try.

**Comment by glenn-jocher** [comment]
Hello @dongrixinyu,

Thank you for expressing your interest in contributing to the YOLOv8 project! It's great to see dedicated contributors like yourself. Given your extensive experience with maintaining repositories like JioNLP and jiojio, your skills would definitely lend themselves well to this project.

The first step to become a maintainer involves actively participating in the project. This can include submitting pull requests, bug reports, or contributing to the discussions. We value consistent and quality contributions over time.

If you're interested in any specific area of our ongoing projects or if you have ideas for new features that could boost the performance, please don't hesitate to reach out and share your thoughts.

Looking forward to your contributions to YOLOv8!

**Comment by Syorst** [comment]
Hello and thanks for your work! I encountered the same problem, when I ran the command yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg' it reported an error,System version: CentOS 7.9 
nvcc -V:Build cuda_11.7.r11.7
Error message：
yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'Ultralytics YOLOv8.0.180 🚀 Python-3.10.13 torch-2.0.1+cu117 CUDA:0 (NVIDIA A30, 24119MiB)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients

Found https://ultralytics.com/images/bus.jpg locally at bus.jpg
Traceback (most recent call last):
  File "/home/aiadmin/anaconda3/envs/xray/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/aiadmin/anaconda3/envs/xray/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 445, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/aiadmin/anaconda3/envs/xray/lib/python3.10/site-packages/ultralytics/engine/model.py", line 236, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/aiadmin/anaconda3/envs/xray/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 199, in predict_cli
    for _ in gen:  # running CLI inference without accumulating any outputs (do not modify)
  File "/home/aiadmin/anaconda3/envs/xray/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/aiadmin/anaconda3/envs/xray/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 237, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "/home/aiadmin/anaconda3/envs/xray/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 465, in warmup
    self.forward(im)  # warmup
  File "/home/aiadmin/anaconda3/envs/xray/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 333, in forward
    y = self.model(im, augment=augment, visualize=visualize) if augment or visualize else self.model(im)
  File "/home/aiadmin/anaconda3/envs/xray/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aiadmin/anaconda3/envs/xray/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 45, in forward
    return self.predict(x, *args, **kwargs)
  File "/home/aiadmin/anaconda3/envs/xray/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 62, in predict
    return self._predict_once(x, profile, visualize)
  File "/home/aiadmin/anaconda3/envs/xray/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 82, in _predict_once
    x = m(x)  # run
  File "/home/aiadmin/anaconda3/envs/xray/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aiadmin/anaconda3/envs/xray/lib/python3.10/site-packages/ultralytics/nn/modules/conv.py", line 42, in forward_fuse
    return self.act(self.conv(x))
  File "/home/aiadmin/anaconda3/envs/xray/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aiadmin/anaconda3/envs/xray/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/aiadmin/anaconda3/envs/xray/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation
please help me thanks

**Comment by glenn-jocher** [comment]
@Syorst hello, and thank you for reaching out!

The error message you've received 'RuntimeError: GET was unable to find an engine to execute this computation' usually points to an incompatibility between the CUDA version that PyTorch was built with and the CUDA runtime version.

You've mentioned that you have CUDA 11.7. However, the error message shows that you've built PyTorch with CUDA version 10.1 (torch-2.0.1+cu101). This discrepancy could be the source of the error.

One way to possibly solve this issue is to reinstall PyTorch using a version that matches your CUDA runtime. In your mentioned case, you should reinstall PyTorch built with CUDA 11.7. 

Please ensure that your PyTorch CUDA version matches your installed CUDA runtime version (which is 11.7 in your case), it might help to resolve compatibility issues.

I hope this helps! If you continue to face problems, please don't hesitate to ask.

**Comment by Syorst** [comment]
> @Syorst hello, and thank you for reaching out!
> 
> The error message you've received 'RuntimeError: GET was unable to find an engine to execute this computation' usually points to an incompatibility between the CUDA version that PyTorch was built with and the CUDA runtime version.
> 
> You've mentioned that you have CUDA 11.7. However, the error message shows that you've built PyTorch with CUDA version 10.1 (torch-2.0.1+cu101). This discrepancy could be the source of the error.
> 
> One way to possibly solve this issue is to reinstall PyTorch using a version that matches your CUDA runtime. In your mentioned case, you should reinstall PyTorch built with CUDA 11.7.
> 
> Please ensure that your PyTorch CUDA version matches your installed CUDA runtime version (which is 11.7 in your case), it might help to resolve compatibility issues.
> 
> I hope this helps! If you continue to face problems, please don't hesitate to ask.

I took a look at the python virtual environment and used torch.__version__, which showed >>> torch.__version__
'2.0.1+cu117'

**Comment by glenn-jocher** [comment]
Hello @Syorst,

Thank you for the additional information. It indeed shows that your PyTorch version should be compatible with your CUDA runtime version.

However, the error you're seeing typically indicates that the runtime can't find a suitable CUDA device to run your computation. One possibility could be that your Nvidia A30 GPU isn't recognized correctly by your CUDA installation.

Check your CUDA installation and ensure the GPU is correctly recognized. You may need to update your driver to the latest version compatible with CUDA 11.7 and your GPU.

If you're using Conda, it might be helpful to create a fresh Conda environment and install PyTorch and torchvision there for the isolation it provides.

This isn't always a straightforward issue to resolve, and it could potentially involve checking your software stack's particulars. If you continue to see this issue after trying these steps, please don't hesitate to let us know.

**Comment by Syorst** [comment]
> Hello @Syorst,
> 
> Thank you for the additional information. It indeed shows that your PyTorch version should be compatible with your CUDA runtime version.
> 
> However, the error you're seeing typically indicates that the runtime can't find a suitable CUDA device to run your computation. One possibility could be that your Nvidia A30 GPU isn't recognized correctly by your CUDA installation.
> 
> Check your CUDA installation and ensure the GPU is correctly recognized. You may need to update your driver to the latest version compatible with CUDA 11.7 and your GPU.
> 
> If you're using Conda, it might be helpful to create a fresh Conda environment and install PyTorch and torchvision there for the isolation it provides.
> 
> This isn't always a straightforward issue to resolve, and it could potentially involve checking your software stack's particulars. If you continue to see this issue after trying these steps, please don't hesitate to let us know.

Thank you for your reply

**Comment by glenn-jocher** [comment]
Hello @Syorst!

I appreciate your confirmations regarding the PyTorch and CUDA versions. Going by the error message you're encountering, the problem seems to arise when your computation is trying to access a CUDA device and not finding a suitable one. One possibility could be that the CUDA installation isn't recognizing your Nvidia A30 GPU correctly.

With that in mind, I'd recommend ensuring that your CUDA installation is correct and that the GPU is being properly recognized. If necessary, updating your driver to a version that is compatible with your CUDA version (11.7) and your GPU might solve the issue.

I noted that you're using Conda. An additional step you may find beneficial is creating a new, isolated Conda environment and installing PyTorch and torchvision there.

This isn't always an easy issue to solve as it might involve inspecting your software setup in greater detail. If these steps don't alleviate the issue, please feel free to update us so we can assist you further.

Thank you for your patience and cooperation!

**Comment by hiyyg** [comment]
The system CUDNN should also match the version pre-built with pytorch. The mismatch can be detected by 
```
python -m detectron2.utils.collect_env
```

**Comment by glenn-jocher** [comment]
@hiyyg hello,

Thank you for bringing this to our attention. You're correct that the cuDNN version must be compatible with the version of PyTorch pre-installed to ensure smooth execution.

The CUDA and cuDNN versions are vital components to consider when configuring your deep learning environment as inconsistencies between them and PyTorch can result in errors or reduced performance.

The command you provided "python -m detectron2.utils.collect_env" checks various elements of your PyTorch environment, including CUDA Toolkit and cuDNN versions. It's a helpful tool for troubleshooting inconsistencies.

To resolve any issues, make sure the cuDNN version matches the one that PyTorch was built with. It requires verifying PyTorch's pre-built cuDNN version and cross-checking it with the system’s cuDNN version. If there is a mismatch, you would need to reinstall cuDNN or PyTorch accordingly to match the proper versions.

Take extra care to ensure compatibility when installing these components. We appreciate your understanding and patience as we seek to facilitate your use of YOLOv8. Let us know if you need any further assistance!

**Comment by VikasAmaraneni** [comment]
Hello Everyone,
I'm using pytorch version=2.2.1 and CUDA=12.1. I'm getting the following error;

'RuntimeError: RuntimeError                              Traceback (most recent call last)
Cell In[16], line 47
     45 num_epochs = 10
     46 for epoch in range(num_epochs):
---> 47     train_loss, train_time = train(model, train_loader, criterion, optimizer)
     48     val_loss, val_accuracy, val_time = validate(model, val_loader, criterion)
     49     print(f'Epoch {epoch+1}[/](http://127.0.0.1:25058/){num_epochs}, Train Loss: {train_loss:.4f}, Train Time: {train_time:.2f}s, '
     50       f'Val Loss: {val_loss:.4f}, Val Accuracy: {val_accuracy:.4f}, Val Time: {val_time:.2f}s')

Cell In[16], line 13, in train(model, train_loader, criterion, optimizer)
     11 outputs = model(inputs)
     12 loss = criterion(outputs, labels)  # Calculate loss between model outputs and ground truth
---> 13 loss.backward()
     14 optimizer.step()
     15 running_loss += loss.item() * inputs.size(0)  # Update running loss

File [~/.conda/envs/torchTest1/lib/python3.12/site-packages/torch/_tensor.py:522](http://127.0.0.1:25058/~/.conda/envs/torchTest1/lib/python3.12/site-packages/torch/_tensor.py#line=521), in Tensor.backward(self, gradient, retain_graph, create_graph, inputs)
    512 if has_torch_function_unary(self):
    513     return handle_torch_function(
    514         Tensor.backward,
    515         (self,),
   (...)
    520         inputs=inputs,
    521     )
--> 522 torch.autograd.backward(
    523     self, gradient, retain_graph, create_graph, inputs=inputs
    524 )

File [~/.conda/envs/torchTest1/lib/python3.12/site-packages/torch/autograd/__init__.py:266](http://127.0.0.1:25058/~/.conda/envs/torchTest1/lib/python3.12/site-packages/torch/autograd/__init__.py#line=265), in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    261     retain_graph = create_graph
    263 # The reason we repeat the same comment below is that
    264 # some Python versions print out the first line of a multi-line function
    265 # calls in the traceback and some print out the last line
--> 266 Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    267     tensors,
    268     grad_tensors_,
    269     retain_graph,
    270     create_graph,
    271     inputs,
    272     allow_unreachable=True,
    273     accumulate_grad=True,
    274 )

RuntimeError: GET was unable to find an engine to execute this computation'

**Comment by glenn-jocher** [comment]
@VikasAmaraneni hello there! 👋

It seems like you're encountering a "RuntimeError" related to CUDA operations in PyTorch. This type of error is often due to a mismatch between the CUDA version and either the PyTorch version or the available CUDA runtime. Here are a couple of things you might want to check out:

1. Ensure your environment is correctly set up for CUDA 12.1. You can verify this with:

```bash
nvcc --version
```

2. Confirm that PyTorch is using the correct CUDA version with:
```python
import torch
print(torch.version.cuda)
```

3. Given the current state of your error, updating PyTorch to match your CUDA version might help, especially since CUDA compatibility can be quite sensitive. To update PyTorch, you can use:
```bash
pip install torch torchvision --upgrade
```
_or install a version known to be compatible with your CUDA._

🤞 I hope this nudges you in the right direction! If the issue persists, providing more details on your setup or the step before the error occurs could help debug further.

**Comment by VikasAmaraneni** [comment]
when I tried "nvcc --version", I got 'nvcc is not a command'. Cuda version is 12.1 and after upgrading the torch. I've run my code, The following is the error I received:

> RuntimeError: CUDA error: device-side assert triggered
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by glenn-jocher** [comment]
@VikasAmaraneni hey there! 👋 It seems like `nvcc` isn't recognized, which typically indicates CUDA's command-line tools aren't correctly set up in your environment path. For the runtime error you're encountering, enabling `CUDA_LAUNCH_BLOCKING=1` can help pinpoint the problem more accurately. You can do this by setting the environment variable in your terminal or directly in your Python script like so:

```python
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
```

Run your script again after setting this. It'll run slower but should give you a more precise location of the error. This detail is crucial for debugging CUDA errors, especially "device-side assert triggered" ones, which often relate to issues with tensor operations that aren't compatible with your CUDA device or incorrect tensor dimensions/indices. 

Hope this helps get you closer to solving the issue! 🛠️

**Comment by VikasAmaraneni** [comment]
Hey @glenn-jocher, Thank you so much for responding to my query. I found out the issue, it's because I'm working with ImageNet-LT dataset which has 1000 classes. I'm using binary Cross Entropy as loss function which is resulting in this error. I need to use categorical cross entropy instead of binary.

However, I'll seek your guidance if at all I received same error again.

Thank you So Much!!!

**Comment by VikasAmaraneni** [comment]
@glenn-jocher, on the second note. Can you explain this "It seems like nvcc isn't recognized, which typically indicates CUDA's command-line tools aren't correctly set up in your environment path." if you don't mind can you please help me fix it.

**Comment by glenn-jocher** [comment]
Hey there! 😊

Absolutely, happy to elaborate on that. `nvcc` not being recognized usually means that the CUDA installation's path isn't included in your system's environment variables. Here's a brief how-to to fix this:

For **Linux**:
1. Open your terminal.
2. Edit your `.bashrc` file with `nano ~/.bashrc`.
3. Add the following lines at the end (substitute `your_cuda_path` with the actual CUDA installation path, usually something like `/user/local/cuda/bin`):
   ```
   export PATH=/your_cuda_path/bin:$PATH
   export LD_LIBRARY_PATH=/your_cuda_path/lib64:$LD_LIBRARY_PATH
   ```
4. Save and close `nano` (Ctrl + O, Enter, Ctrl + X).
5. Reload `.bashrc` by typing `source ~/.bashrc`.

For **Windows**:
1. Search "Environment Variables" in your Start menu and open it.
2. Click on "Edit the system environment variables" > Environment Variables.
3. In "System variables", find the 'Path' variable and click Edit.
4. Add the path to the CUDA `bin` directory (usually something like `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\vX.X\bin`).
5. Click OK to save and close all dialog boxes.

After this, you should be able to use `nvcc --version` in the terminal to confirm it's correctly set up.

Let me know if you need more help!

**Comment by VikasAmaraneni** [comment]
Hey @glenn-jocher!! Thank you so much for quick response. I have a small question. I using conda environment and i don't know how to find path for cuda. I'm attaching a screenshot of cuda packages I have. Can you please help me to get cuda path so that I can do what you suggested.
<img width="880" alt="Screenshot 2024-04-15 at 8 19 41 PM" src="https://github.com/ultralytics/ultralytics/assets/149958082/97e71576-6829-480c-a570-1a53bb0cfa05">

**Comment by VikasAmaraneni** [comment]
Hey @glenn-jocher, Thank you so much. It worked, I've setup mu cuda path in the way you guided. But when I tried '`nvcc --version`'. I'm still getting `-bash: nvcc: command not found`.

**Comment by glenn-jocher** [comment]
Hey there! 😊 Great to hear the setup guidance was helpful. If `nvcc --version` is still giving you trouble, it might be worthwhile to close and reopen your terminal, just to ensure the environment variables are refreshed. If it persists, double-check the path added includes the `bin` directory where `nvcc` actually resides. For a typical installation, the command in your `.bashrc` or terminal should look something like this:

```bash
export PATH=/usr/local/cuda/bin:$PATH
```

Replacing `/usr/local/cuda` with your actual CUDA installation directory. Hope this gets `nvcc` up and running!

**Comment by jpisaac** [comment]
Hi 
Running into the same issue - "RuntimeError: GET was unable to find an engine to execute this computation"
Have followed the following docs/guides

Building pytorch - [PyTorch for Jetson](https://forums.developer.nvidia.com/t/pytorch-for-jetson/72048)
For ultralytics on Jetson - [NVIDIA Jetson - Ultralytics YOLO Docs](https://docs.ultralytics.com/guides/nvidia-jetson/)

Thank you for your support.

Here is my env info :

python3 -m torch.utils.collect_env
Collecting environment information…
PyTorch version: 2.1.0
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (aarch64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.19.1
Libc version: glibc-2.31

Python version: 3.8.19 (default, Mar 20 2024, 19:53:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.10.120-tegra-aarch64-with-glibc2.26
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/aarch64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/aarch64-linux-gnu/libcudnn.so.9.4.0
/usr/lib/aarch64-linux-gnu/libcudnn_adv.so.9.4.0
/usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/aarch64-linux-gnu/libcudnn_cnn.so.9.4.0
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/aarch64-linux-gnu/libcudnn_engines_precompiled.so.9.4.0
/usr/lib/aarch64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.4.0
/usr/lib/aarch64-linux-gnu/libcudnn_graph.so.9.4.0
/usr/lib/aarch64-linux-gnu/libcudnn_heuristic.so.9.4.0
/usr/lib/aarch64-linux-gnu/libcudnn_ops.so.9.4.0
/usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture: aarch64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
CPU(s): 12
On-line CPU(s) list: 0-11
Thread(s) per core: 1
Core(s) per socket: 4
Socket(s): 3
Vendor ID: ARM
Model: 1
Model name: ARMv8 Processor rev 1 (v8l)
Stepping: r0p1
CPU max MHz: 2201.6001
CPU min MHz: 115.2000
BogoMIPS: 62.50
L1d cache: 768 KiB
L1i cache: 768 KiB
L2 cache: 3 MiB
L3 cache: 6 MiB
Vulnerability Itlb multihit: Not affected
Vulnerability L1tf: Not affected
Vulnerability Mds: Not affected
Vulnerability Meltdown: Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1: Mitigation; __user pointer sanitization
Vulnerability Spectre v2: Mitigation; CSV2, but not BHB
Vulnerability Srbds: Not affected
Vulnerability Tsx async abort: Not affected
Flags: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp uscat ilrcpc flagm

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.1.0
[pip3] torchvision==0.16.2+c6f3977
[conda] numpy 1.23.5 pypi_0 pypi
[conda] pytorch-cuda 11.8 h8dd9ede_2 pytorch
[conda] torch 2.1.0 pypi_0 pypi

Getting this exception when trying to export a model

yolo export model=yolov8n.pt format=engine

WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics 8.3.7 🚀 Python-3.8.19 torch-2.1.0 CUDA:0 (Orin, 62800MiB)
YOLOv8n summary (fused): 168 layers, 3,151,904 parameters, 0 gradients
Traceback (most recent call last):
File “/home/jacob/work/github/jpisaac/testproj/env/bin/yolo”, line 8, in
sys.exit(entrypoint())
File “/home/jacob/work/github/jpisaac/testproj/env/lib/python3.8/site-packages/ultralytics/cfg/init.py”, line 831, in entrypoint
getattr(model, mode)(**overrides) # default args from model
File “/home/jacob/work/github/jpisaac/testproj/env/lib/python3.8/site-packages/ultralytics/engine/model.py”, line 736, in export
return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
File “/home/jacob/work/github/jpisaac/testproj/env/lib/python3.8/site-packages/torch/utils/_contextlib.py”, line 115, in decorate_context
return func(*args, **kwargs)
File “/home/jacob/work/github/jpisaac/testproj/env/lib/python3.8/site-packages/ultralytics/engine/exporter.py”, line 265, in call
y = model(im) # dry runs
File “/home/jacob/work/github/jpisaac/testproj/env/lib/python3.8/site-packages/torch/nn/modules/module.py”, line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File “/home/jacob/work/github/jpisaac/testproj/env/lib/python3.8/site-packages/torch/nn/modules/module.py”, line 1527, in _call_impl
return forward_call(*args, **kwargs)
File “/home/jacob/work/github/jpisaac/testproj/env/lib/python3.8/site-packages/ultralytics/nn/tasks.py”, line 111, in forward
return self.predict(x, *args, **kwargs)
File “/home/jacob/work/github/jpisaac/testproj/env/lib/python3.8/site-packages/ultralytics/nn/tasks.py”, line 129, in predict
return self._predict_once(x, profile, visualize, embed)
File “/home/jacob/work/github/jpisaac/testproj/env/lib/python3.8/site-packages/ultralytics/nn/tasks.py”, line 150, in _predict_once
x = m(x) # run
File “/home/jacob/work/github/jpisaac/testproj/env/lib/python3.8/site-packages/torch/nn/modules/module.py”, line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File “/home/jacob/work/github/jpisaac/testproj/env/lib/python3.8/site-packages/torch/nn/modules/module.py”, line 1527, in _call_impl
return forward_call(*args, **kwargs)
File “/home/jacob/work/github/jpisaac/testproj/env/lib/python3.8/site-packages/ultralytics/nn/modules/conv.py”, line 54, in forward_fuse
return self.act(self.conv(x))
File “/home/jacob/work/github/jpisaac/testproj/env/lib/python3.8/site-packages/torch/nn/modules/module.py”, line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File “/home/jacob/work/github/jpisaac/testproj/env/lib/python3.8/site-packages/torch/nn/modules/module.py”, line 1527, in _call_impl
return forward_call(*args, **kwargs)
File “/home/jacob/work/github/jpisaac/testproj/env/lib/python3.8/site-packages/torch/nn/modules/conv.py”, line 460, in forward
return self._conv_forward(input, self.weight, self.bias)
File “/home/jacob/work/github/jpisaac/testproj/env/lib/python3.8/site-packages/torch/nn/modules/conv.py”, line 456, in _conv_forward
return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit

**Comment by glenn-jocher** [comment]
@jpisaac it seems like the issue might be related to a mismatch between your PyTorch build and the CUDA version. Please ensure that your PyTorch version is built with the same CUDA version installed on your system. You might also want to check if all dependencies are correctly installed and compatible. If the issue persists, consider reinstalling PyTorch with the appropriate CUDA version.
