### ISSUE TITLE
Long time needed to get masks using segmentation model

### ISSUE THREAD

**Issue by pisum18** [ultralytics/ultralytics#4064]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I am using a trained segmentation model to detect objects in images sent by a separate computer. Due to the results needing to be processed in realtime, the performance of the script is of utmost importance. When testing the script however, I noticed that most of the time spent by the script was getting the masks from the results object, instead of the inference as expected.
A little bit of further experimenting showed that the time needed to get `mask_list`  significantly exceeded the time needed for inference if the amount of masks was higher than approx. 30.

Is there a faster way to get the masks? Otherwise, would it be possible to optimise this operation?

### Environment

- YOLO: Ultralytics YOLOv8.0.143
- OS: Ubuntu 23.04
- Python: 3.10.12
- GPU: RTX4080
- CPU: Intel i5-13600K

### Minimal Reproducible Example

```
import os
import glob
from ultralytics import YOLO
from PIL import Image
import numpy as np
import time


IMG_DIMS = 1024
MSG_SIZE = IMG_DIMS * IMG_DIMS * 3 + 4


def image_to_bytearray(imgfile, i):
    #get image data
    with Image.open(imgfile) as img:
        data = img.getdata()

    #convert image data to bytearray
    databytes = bytearray()

    databytes += i.to_bytes(length = 4, byteorder = "little", signed = False)

    #print(os.path.basename(imgfile), databytes[0:4], sep="\t")

    for pixel in data:
        for value in pixel:
            databytes += value.to_bytes(length = 1, byteorder = "big", signed = False)

    return databytes

def bytearray_to_numpyarray(databytes):
    index = int.from_bytes(databytes[0:4], "little")
    im0 = np.frombuffer(databytes[4:MSG_SIZE], dtype=np.uint8)
    im = np.reshape(im0, (IMG_DIMS, IMG_DIMS, 3))[:, :, ::-1]       #swap R and B channels

    return im


if __name__ == "__main__":
    model_path = "weights/best.pt"
    source = r"D:\test_sets\active\valid"
    
    imgfiles = glob.glob(os.path.join(source, "*.png"))[0:4]
    image_count = len(imgfiles)    
    image_array = np.zeros((image_count, 3, 1024, 1024), dtype="float32")

    image_list = []
    for imgfile in imgfiles:
        databytes = image_to_bytearray(imgfile, 0)

        imgArray = bytearray_to_numpyarray(databytes)

        image_list.append(imgArray)

    #get model
    model = YOLO(model_path)

    #do warmup
    _ = model(image_list)
    
    #get model results
    print("Getting results")
    meas_time = time.perf_counter()
    results = model(image_list)
    print("Time for inference:", time.perf_counter() - meas_time, "s")

    #go through each result
    for result in results:
        meas_time = time.perf_counter()
        mask_list = result.masks.xy
        print("Time to get masks:", time.perf_counter() - meas_time, "s")

        print(result.path, len(mask_list), sep="\t")
```

### Additional

I will be going on vacation soon so apologies if my answers are slow.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@pisum18 hi there! 

Thanks for providing such a detailed account of your issue. It seems like you're experiencing a performance slowdown while extracting masks from the model results, particularly when the number of masks exceeds around 30. While the utility functions used for extracting mask data are generally optimized for performance, it's possible that their efficiency could be dependent on the specific circumstances of use, such as the size and complexity of the masks, processing power, etc.

In terms of optimizing this operation, there might be two notable points. First, you might want to consider running the mask extraction in batches, particularly for large numbers of masks. This could potentially help better manage memory and compute resources. Second, you could explore parallel processing options, dividing the mask extraction workload across multiple cores or threads if possible, though this will also depend on your specific hardware and software environment. 

While you're exploring these options, we'll also take a look at the code on our end to see if there's any improvements to be made from our side. Thanks for your patience and understanding. Enjoy your vacation and feel free to reply or open another issue if you have further questions!

**Comment by pisum18** [comment]
I know this thread is long closed, but the reason why this was so slow is that I was trying to move tens, if not hundreds of 1024x1024 tensors to the CPU memory all at once. This was taking an incredible amount of time.

The fix was to first filter the results, and then move only the necessary information to the CPU memory

**Comment by glenn-jocher** [comment]
@pisum18 thank you for sharing your findings! Filtering results before moving data to CPU memory is indeed a great optimization step. For others facing similar issues, this approach can significantly reduce processing time, especially with large datasets or high-resolution tensors. Let us know if you have further questions!
