### ISSUE TITLE
When can we use function to visualize feature map?

### ISSUE THREAD

**Issue by sinho-kr** [ultralytics/ultralytics#4077]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello! I have question about 'model.predict' argument(arg : Visualize = True) as below.
  <example>
     model.predict(source, save=True, imgsz=320, conf=0.5, **visualize = True**)

When I use this argument, the message "visualize feature not yet supported" is displayed.

When are you planning to serve this function(visualizing feature)?

**Comment by glenn-jocher** [comment]
@sinho-kr hello,

Thank you for your question about visualizing the feature map in YOLOv8. The 'visualize' argument in the 'model.predict' function is indeed intended for this purpose. However, as the message indicates, this feature has not yet been implemented.

We're always working hard on improving and expanding the features available in our YOLOv8 repository. While I can't provide a specific timeline for the visualization feature, I assure you it's on our radar and we hope to implement it soon.

Please continue to keep an eye on this repo for updates. We appreciate your patience and interest in this feature.

Best regards,
Glenn Jocher
