### ISSUE TITLE
Broken Yolov8 tutorial in Google Colab

### ISSUE THREAD

**Issue by ichsan2895** [ultralytics/ultralytics#409]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Validation, Detection, Export

### Bug

This link is has error when I ran it : https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb#scrollTo=8Go5qqS9LbC5

![image](https://user-images.githubusercontent.com/60387342/212667347-af7c0c2a-3a9e-48dd-8551-d6f99f49d79b.png)

![image](https://user-images.githubusercontent.com/60387342/212667416-2c502e90-d747-4b20-88ba-36dbd3b87683.png)

![image](https://user-images.githubusercontent.com/60387342/212667499-b0e3319e-24cc-4e4a-9840-c01fd19e146c.png)

Maybe the problem that caused by location of datasets and yaml folder, related to this thread:
https://github.com/ultralytics/ultralytics/issues/384

### Environment

Google colab env:
```
Ultralytics YOLOv8.0.6 🚀 Python-3.8.16 torch-1.13.0+cu116 CUDA:0 (Tesla T4, 15110MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 23.0/78.2 GB disk)
```

### Minimal Reproducible Example

```
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.yaml')  # build a new model from scratch
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)

# Use the model
results = model.train(data='coco128.yaml', epochs=3)  # train the model
results = model.val()  # evaluate model performance on the validation set
results = model('https://ultralytics.com/images/bus.jpg')  # predict on an image
success = model.export(format='onnx')  # export the model to ONNX format
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doit-ceo** [comment]
Facing the same issue

**Comment by AyushExel** [comment]
Hey guys! can you try to run only the 1st setup cell and skip the 2nd cell that installs the package from GitHub? Let me know if you still face the same issue
