### ISSUE TITLE
Can i use tracker with pre-defined bboxes ?

### ISSUE THREAD

**Issue by enessanli** [ultralytics/ultralytics#4091]
### Search before asking

- [ ] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, i have an dataset which  i did detection before. I want to track these object with their bboxes. Can i just use tracker of the yolov8 model ? Is it possible ?

**Comment by glenn-jocher** [comment]
@enessanli hello, thank you for your question!

Yes, it's possible to use the tracker in YOLOv8 when you have pre-defined bounding boxes. Essentially, the tracking function in YOLOv8 works by predicting the trajectory of objects, and this function often relies on initial bounding box information to identify objects. In your case, since you have already performed detection, your scenario perfectly fits this requirement.

You can input your dataset along with the associated pre-defined bounding boxes into the tracking function of YOLOv8. The concept is similar to initializing a tracker with the location of an object, and then the tracker will attempt to follow the object in subsequent frames.

Please remember to format the input data correctly. The bounding box coordinates need to be passed in the appropriate format as expected by the tracker function. 

I hope this helps and good luck with your tracking project!

**Comment by enessanli** [comment]
Thank for your respond. I'm new to yolo architecture so i don't get what should i do. Could you please give more details. Here it is what i code.

```
from ultralytics import YOLO

# Path of the yolov8n.pt file
model_path = "weights/yolov8n.pt"

# path of the video file
vid_path = "/content/frames"

import os

# Get the list of all files and directories
path = "/content/frames"
dir_list = os.listdir(path)
dir_list.sort(key=lambda x: int(x.split("/")[-1].split(".")[0]))

# Load Pre-trained ML Model
model = YOLO(model_path)

for i in dir_list:
  path1 = os.path.join(path,i)
  print(path1)
  results = model.track(source=path1,
                      conf=0.3,
                      iou=0.5,
                      persist=True,
                      show=False,
                      save=True,
                      save_txt=True,
                      save_conf=True
                      )
```
NOTE: In this code i did not give the predefined bboxes. If i some how give it to the model will it track it without detect it or i get all the things completely wrong ?

Thanks for your time

**Comment by enessanli** [comment]
Hi @glenn-jocher. I still haven't found any solution. Could you please help me. I'm in little bit rush. Thanks for your time.

Regards.

**Comment by glenn-jocher** [comment]
Hi @enessanli,

Apologies for any confusion caused earlier. Let me try to clarify a bit more.

The object tracker in YOLOv8 is designed with an assumption that the bounding boxes are output by the YOLO detection stage. It does not directly support input of predefined bounding boxes, as the tracker relies primarily on the output of the YOLO detection stage for tracking objects. 

Given that, inputting custom bounding boxes for tracking without the detection stage is not directly possible in the current architecture. This architecture has been designed to ensure optimal performance as the detection and tracking stages have been finely tuned to work in sync with each other. 

If you have already detected bounding boxes and want to track them, a separate object tracking algorithm might be more suitable (like the MOSSE tracker, CSRT, KCF, etc. available in OpenCV). 

Although the YOLOv8 architecture is versatile, inserting predefined bounding boxes into the tracking mechanism may require significant modifications to the source code, which is beyond the intended use and could lead to unexpected results.

I hope this clarifies the situation. I recommend considering either using YOLOv8 as is, which means relying on it for both detection and tracking process, or using a third-party tracking algorithm if you already have predefined bounding boxes.

Feel free to ask if you have more questions. Thank you!

**Comment by ahmadbinshafiq** [comment]
Hi @glenn-jocher 

So, if I have a scenario, where I have a defined ROI. And I want to ensure that the objects have an IOU of over 0.5 against the defined ROI. I want to apply a tracker to them. And once the tracker is assigned is assigned to them, they will be tracked across the whole frame. 
So, in this case, 
1. I will have to first detect the objects
2. Check their IOU against the defined ROI
3. If IOU > 0.5, apply a tracker to that object by sending the bboxes coordinates from the detector to tracker object 
4. Now track that object across the whole frame

So, is there a way to use the yolov8 detector & trackers in any way to accomplish this? Or would I have to use some external tracker for this?

**Comment by glenn-jocher** [comment]
@ahmadbinshafiq hi,

In YOLOv8, the detection and tracking processes are integrated and work hand in hand, meaning the tracker relies on the detection stage for its operation. 

Regarding your question, the YOLOv8 system isn't currently designed for directly inputting predefined regions of interest. You would still run the detection stage first, then the detected objects would be passed to the tracker.

In your case, YOLOv8 would detect and track all objects in your video. Right after that, you could manually filter out the detections and associated tracks that meet your IOU criteria with the ROI you have defined. 

If you wish for the tracker to take your predefined bounding boxes (ROI), and objects with IOU > 0.5 directly, you may need to incorporate a separate object tracking algorithm to your pipeline as YOLOv8 doesn't provide this exact functionality off-the-shelf.

I hope this helps. Let me know if you have other questions.

**Comment by ahmadbinshafiq** [comment]
Perfect! Thank you @glenn-jocher that was really helpful.

> @ahmadbinshafiq hi,
> 
> In YOLOv8, the detection and tracking processes are integrated and work hand in hand, meaning the tracker relies on the detection stage for its operation.
> 
> Regarding your question, the YOLOv8 system isn't currently designed for directly inputting predefined regions of interest. You would still run the detection stage first, then the detected objects would be passed to the tracker.
> 
> In your case, YOLOv8 would detect and track all objects in your video. Right after that, you could manually filter out the detections and associated tracks that meet your IOU criteria with the ROI you have defined.
> 
> If you wish for the tracker to take your predefined bounding boxes (ROI), and objects with IOU > 0.5 directly, you may need to incorporate a separate object tracking algorithm to your pipeline as YOLOv8 doesn't provide this exact functionality off-the-shelf.
> 
> I hope this helps. Let me know if you have other questions.

Perfect! Thank you @glenn-jocher that was really helpful.

**Comment by glenn-jocher** [comment]
@ahmadbinshafiq i'm glad to hear you found the information helpful! If you have any additional questions or come across any other issues while working with YOLOv8, don't hesitate to ask. We're here to help. Good luck with your project.
