### ISSUE TITLE
How to effectively quantize Yolov8 model to int8 ?

### ISSUE THREAD

**Issue by jerin-scalers-ai** [ultralytics/ultralytics#4097]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to use OneDNN optimization with yolov8 int8 model.
So, I exported yolov8 model into onnx and tried onnx dynamic & static quantization on model.

The dynamic quantized int8 model is having poor inference time compared to FP32 model with ONNXruntime (DnnlExecutionProvider). 
Whereas the static quantized model is not working with ONNXruntime(DnnlExecutionProvider). 

I'd like to check if there is any recommended way to effectively quantize yolov8 model?

### Additional

Issue with static quantized model:

onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running DNNL_4424642687171521908_2 node. Name:'DnnlExecutionProvider_DNNL_4424642687171521908_2_2' Status Message: /onnxruntime/onnxruntime/core/providers/dnnl/subgraph/dnnl_dequantizelinear.cc:191 void onnxruntime::ort_dnnl::DnnlDequantizeLinear::ValidateDims(onnxruntime::ort_dnnl::DnnlSubgraphPrimitive&, onnxruntime::ort_dnnl::DnnlNode&) x_scale and x_zero_point dimensions does not match

**Comment by glenn-jocher** [comment]
@jerin-scalers-ai it sounds like you're facing some performance hiccups with INT8 quantization on your YOLOv8 model. Quantization scenarios can indeed be tricky given the complex interplay between model architecture, quantization methods, and specific runtime environments. 

For your specific case, the ONNX model seems to have trouble optimizing the YOLOv8 model in the INT8 static quantization setup. The error message suggests there might be an inconsistency between the scale and zero_point dimensions of your tensors during dequantization. I urge you to double-check if this scenario is consistent across different input sizes and batches.

The quantization process can typically benefit from revisiting a few areas:

1. **Data calibration**: The choice of calibration data can significantly impact the performance of the quantized model. It's typically a good idea to use representative data with diverse scenarios from your target deployment dataset to ensure that the activation ranges reflect the real-world usage.

2. **Quantization scheme**: Different quantization schemes including per-tensor, per-channel, symmetric or asymmetric quantization, can yield different results. The choice of the scheme most often depends on the model and the specifics of the deployment scenario.

Interestingly, you mentioned that there is an increase in inference time with the int8 model as compared to FP32, which is somewhat atypical. This may indicate that the DNNL runtime is not fully optimized for utilizing INT8 computations, and could potentially be alleviated with software updates or a different deployment environment that has more robust support for INT8 computations.

While I understand that you're currently utilizing OneDNN and ONNX, have you considered using a different quantization tool or library? Libraries like TensorRT provide comprehensive support for INT8 quantization and might help you navigate this situation. 

I hope this helps guide your path to a more optimal quantization strategy! Make sure to engage with the broader YOLO and ultralytics community who are always eager to share their knowledge and experiences.

**Comment by srikar242** [comment]
Hello @jerin-scalers-ai  I am also working on the yolov8 model and I want to quantize the yolov8-nano ONNX model. I have performed the Dynamic Quantization of it using onnx.quatization method but my FPS has not increased much with that strategy. I want to try out the static quantization of yolov8 model. But I am unable to find proper resources on how to do it. Could you help me in performing this static quantization of yolov8 model? May be you could point me out to articles or source code using which you did. Your help is appreciated.

**Comment by IrDIE** [comment]
Hi!
@srikar242 , @jerin-scalers-ai 
I hape repo for yolo8 quantization - https://github.com/IrDIE/YOLO8_quantization
(post-training, with accuracy control and without)
+ accuracy test for quantized model
+ explained `ignored_scope` parameter if you don't wanna change some layers

You can check it out, and press :star: if you liked it =)

**Comment by glenn-jocher** [comment]
@Sakshi1510yadav hi there! 👋

Quantizing a YOLOv8 model to INT8 can indeed boost your inference speed. While we don't have a specific script ready for this task, you can start with the ONNX Runtime quantization tool. Here's a quick snippet to get you started:

```python
from onnxruntime.quantization import quantize_dynamic, QuantType

model_fp32 = 'yolov8.onnx'
model_int8 = 'yolov8_quantized.onnx'

# Quantize
quantize_dynamic(model_fp32, model_int8, weight_type=QuantType.QUInt8)
```

This uses dynamic quantization, but it's a good starting point. For static quantization, the process is a bit more involved and currently, ONNX Runtime doesn't directly support it for all models. You might need to explore additional tools or libraries specific to your deployment environment.

Hope this helps! If you have more questions or need further assistance, feel free to ask. 😊

**Comment by Sakshi1510yadav** [comment]
Hey @glenn-jocher Thanks for the suggestion 
I have tried with quantize dynamic and got a few errors after resolving them I got stuck at this point.
"  File "/usr/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not ModelProto"

The snippet of the code:
`# Load the original ONNX model
onnx_model_path = 'model.onnx'
onnx_model = onnx.load(onnx_model_path)

# Specify the name of the output node to be quantized
model_output = 'output0'

# Quantize the model
quantized_model = quantize_dynamic(onnx_model, model_output=model_output)

# Save the quantized model
quantized_model_path = 'quantized_model.onnx'
onnx.save(quantized_model, quantized_model_path)

print("Quantization completed. Quantized model saved to:", quantized_model_path)`

Can you please suggest something regarding this? 
Thanks in advance!

**Comment by glenn-jocher** [comment]
@Sakshi1510yadav hey there! 😊 It looks like the `quantize_dynamic` function expects a file path as input, but you're passing it an ONNX model object directly. Try loading the model file path directly into the `quantize_dynamic` function like this:

```python
from onnxruntime.quantization import quantize_dynamic

# Load the original ONNX model file path
onnx_model_path = 'model.onnx'

# Specify the name of the output node to be quantized
model_output = 'output0'

# Quantize the model directly from the file path
quantized_model_path = 'quantized_model.onnx'
quantize_dynamic(model_input=onnx_model_path, 
                 model_output=quantized_model_path, 
                 per_channel=False,  # Adjust as needed
                 weight_type=QuantType.QUInt8)

print("Quantization completed. Quantized model saved to:", quantized_model_path)
```

This should resolve the `TypeError` you're encountering. Let me know how it goes!

**Comment by glenn-jocher** [comment]
@Sakshi1510yadav hey there! 😊 Great to hear the error was resolved! If Netron shows the model as float32 after quantization, it might mean the quantization process didn't fully apply to all tensors as expected. Dynamic quantization typically targets weights, so activations might still be in float32. For full int8 quantization, including activations, exploring static quantization or a different quantization tool that supports your specific needs might be necessary. Keep up the good work! 👍

**Comment by grimen** [comment]
Excellent article series on the topic:

- https://medium.com/@DeeperAndCheaper/quantization-yolov8-qat-x2-speed-up-on-your-jetson-orin-nano-1-why-quantization-e052a72c506d
- https://medium.com/@DeeperAndCheaper/quantization-yolov8-qat-x2-speed-up-on-your-jetson-orin-nano-2-how-to-achieve-the-best-qat-8077ac0a167b
- https://medium.com/@DeeperAndCheaper/quantization-go-faster-with-relu-yolov8-qat-x2-speed-up-on-your-jetson-orin-nano-3-4d4733c9e435
- https://medium.com/@DeeperAndCheaper/quantization-achieve-accuracy-drop-to-near-zero-yolov8-qat-x2-speed-up-on-your-jetson-orin-nano-e178c4d8a5e3

**Comment by glenn-jocher** [comment]
@grimen hey there! 🌟 Thanks for reaching out and sharing these excellent resources! It looks like you've delved deep into quantization. 👍 If you or anyone else is looking into applying these insights to YOLOv8, remember to adjust quantization settings based on your specific model and hardware capabilities. Here's a quick snippet on how you might start with dynamic quantization using PyTorch for example:

```python
from torch.quantization import quantize_dynamic
import torch

# Load your YOLOv8 model
model = torch.load('yolov8_model_path.pth')

# Specify the layers you want to quantize
model_quantized = quantize_dynamic(model, {torch.nn.Linear, torch.nn.Conv2d}, dtype=torch.qint8)

# Save the quantized model
torch.save(model_quantized.state_dict(), 'yolov8_quantized_model.pth')
```

This is a basic approach, and depending on your exact requirements, you might need a more detailed process, especially for static quantization. Happy quantizing! 😊

**Comment by minhhotboy9x** [comment]
Hi
I quantized yolov8 by pytorch and converted it to onnx. However the quantized onnx model increase the inference time. How is that possible?

**Comment by glenn-jocher** [comment]
@minhhotboy9x hi there! 😊

Quantizing a model should theoretically reduce inference time, especially on platforms optimized for int8 operations. However, if you're seeing an increase in inference time, it might be due to:

1. The framework you're using for inference might not fully support int8 execution, causing it to fall back on slower implementations.
2. Extra overhead from quantization/de-quantization steps if they're not fully optimized or supported in hardware.

For the best performance, ensure your runtime environment (like ONNX Runtime) is set up to utilize the specific quantization optimizations, and consider using hardware that supports int8 acceleration.

If you're using ONNX Runtime, you can specify the use of DNNL or other optimized execution providers that better support quantized models:

```python
import onnxruntime

sess_options = onnxruntime.SessionOptions()
sess_options.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_ENABLE_ALL

# Specify DNNL as the execution provider
session = onnxruntime.InferenceSession("your_model_path.onnx", sess_options, providers=['DnnlExecutionProvider'])
```

Keep exploring, and hopefully, you'll see the expected speedup! 👍

**Comment by minhhotboy9x** [comment]
[](url)@

> @minhhotboy9x hi there! 😊
> 
> Quantizing a model should theoretically reduce inference time, especially on platforms optimized for int8 operations. However, if you're seeing an increase in inference time, it might be due to:
> 
> 1. The framework you're using for inference might not fully support int8 execution, causing it to fall back on slower implementations.
> 2. Extra overhead from quantization/de-quantization steps if they're not fully optimized or supported in hardware.
> 
> For the best performance, ensure your runtime environment (like ONNX Runtime) is set up to utilize the specific quantization optimizations, and consider using hardware that supports int8 acceleration.
> 
> If you're using ONNX Runtime, you can specify the use of DNNL or other optimized execution providers that better support quantized models:
> 
> ```python
> import onnxruntime
> 
> sess_options = onnxruntime.SessionOptions()
> sess_options.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_ENABLE_ALL
> 
> # Specify DNNL as the execution provider
> session = onnxruntime.InferenceSession("your_model_path.onnx", sess_options, providers=['DnnlExecutionProvider'])
> ```
> 
> Keep exploring, and hopefully, you'll see the expected speedup! 👍

I tried, it just speed up both fp32 and int8 models. Still, the int8 model is slower.
You can try a simple model in my Colab notebook here:
[GG colab](https://drive.google.com/file/d/1-2bfKGPXTQP1FItFYRBE82MVFv1hsaEj/view?usp=sharing)
