### ISSUE TITLE
FastSAM very long postprocess time on single image

### ISSUE THREAD

**Issue by synentec** [ultralytics/ultralytics#4105]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm getting really long postprocess times for running inference on a single 4512x4512 image.
```
Speed: 8.5ms preprocess, 74.6ms inference, 10342.1ms postprocess per image at shape (1, 3, 1024, 1024)
```
I also noticed that my memory usage rose 49GB and GPU memory maxed out at 24GB. I have never experienced this issue somewhere else, is there just a fatal flaw in my code? Yes, CUDA support is available and used for inference and I'm using the FastSAM-s.pt model.

That's my code:
```python
class FastSAMUltralytics:
    """Segmentation model using ultralytics FastSAM"""

    def __init__(self, model_weight_path: str) -> None:
        self.target_size: int = 1024
        self.input_size: Tuple[int, int] = (1024, 1024)

        # Load model
        self.model = FastSAM(model_weight_path)
        self.device = "cuda" if torch.cuda.is_available() else "cpu"

    def predict_masks(self, embedding: Dict, prompts: List[Dict]):
        image = embedding["original_image"]
        if len(image.shape) == 2:
            # If the image is grayscale (W, H), we want to merge it to (W, H, 3)
            image = cv2.merge([image, image, image])
        elif image.shape[0] == 1 or image.shape[0] == 2:
            # If the image is grayscale (C, W, H), with only 1/2 channel, we want to merge it to (W, H, 3)
            image = cv2.merge([image[0, :, :], image[0, :, :], image[0, :, :]])
        elif image.shape[2] == 1 or image.shape[0] == 2:
            # If the image is grayscale (W, H, C), with only 1/2 channel, we want to merge it to (W, H, 3)
            image = cv2.merge([image[:, :, 0], image[:, :, 0], image[:, :, 0]])

        everything_results = self.model(
            image,
            device=self.device,
            retina_masks=True,
            imgsz=self.target_size,
            conf=0.4,
            iou=0.7,
        )
        prompt_process = FastSAMPrompt(image, everything_results, device=self.device)
        points, labels = [], []
        box = []
        for prompt in prompts:
            if prompt["type"] == "point":
                points.append(prompt["data"])
                labels.append(prompt["label"])
            elif prompt["type"] == "rectangle":
                box = prompt["data"]
            else:
                raise ValueError(f"Invalid prompt type: {prompt['type']}")

        if len(labels) == 0:  # Prediction using bounding box
            ann = prompt_process.box_prompt(bbox=box)
        else:  # Prediction using points
            ann = prompt_process.point_prompt(points=points, labels=labels)

        # resize mask to original image size
        ann = np.transpose(ann, (2, 1, 0))
        ann = cv2.resize(
            ann, embedding["original_size"], interpolation=cv2.INTER_NEAREST
        )
        return ann
```

**Comment by glenn-jocher** [comment]
@synentec it seems you are encountering an unusually long post-processing duration for inference on a single image using FastSAM with the YOLOv8 model. Memory usage and GPU memory are also showing high levels. Considering that your CUDA support is up to date and correctly applied, your issue might be related to other factors.

The increase in memory can mainly be attributed to the high-resolution of your image (4512x4512), and the FastSAM model, which is optimized for efficient use of memory. That said, a surge to 49GB is not expected and the post-processing time should not be that long.

The size of the image can cause high post-processing times, especially if your model is producing a large number of detections which require time to process. The functionalities such as bounding box adjustments, non-maximum suppression, etc., in the post-processing phase can take time depending on the number of detections.

Your implementation seems quite complex involving several transformations. The issue could possibly lie here as well. You may want to isolate components of the post-processing to see if there's a specific step causing the delay. Double-check these steps and ensure that all computations are indeed necessary and are being performed efficiently.

Lastly, I suggest verifying the conditions under which your image data is being loaded and processed. Any unnecessary operations or conversions could add to the total inference time.
