### ISSUE TITLE
Printing metrics in jupyter notebook YOLOv8.

### ISSUE THREAD

**Issue by tahaer123** [ultralytics/ultralytics#4108]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I have one small question. I know we can observe results in train folder but I want to print them in jupyter notebook separately.(I don't want to use any image read or similar method.)  How can I do this?. Thanks in advance for your response.

**Comment by glenn-jocher** [comment]
@tahaer123 hi there! Thanks for reaching out with your question.

When you run training with YOLOv8, a JSON log file is created that contains training results such as your loss, mAP, and other metrics. This file is saved in your YOLOv8 run directory, under the name 'results.json'.

To display these metrics in your Jupyter notebook, you can leverage Python's standard library, specifically the `json` module. Here's a verbal description of the steps:

1. Import the `json` module in your notebook.
2. Open the 'results.json' file located in your run directory using Python's built-in `open` function. Remember to open your file in 'read' mode.
3. Use the `json.load()` method to load the contents of the file into a Python dictionary.
4. Now, you have your metrics in a Python dictionary and you can print or manipulate them as you wish.

Remember, it's important to note that the 'results.json' files are created and updated after each epoch. So, if you want real-time metrics in your notebook, you might need to re-run your code cells after each epoch ends.

Hope this helps, and let me know if you have any further questions!

**Comment by tahaer123** [comment]
It is good solution but I'm looking for something different. For example we can see confusion matrix with following code
metrics.confusion_matrix.matrix
Is there any other codes for F1, P_curve PR_curve.

**Comment by glenn-jocher** [comment]
Hello @tahaer123, thanks for the clarification.

Regarding the metrics you mentioned, like the F1, the Precision-Recall curve, and others, the underlying model and training processes are designed to calculate a range of performance metrics. However, directly accessing these metrics as objects (just like the confusion matrix with `metrics.confusion_matrix.matrix`) is not currently supported in Ultralytics YOLOv8's API.

The detailed metrics data (which includes Precision, Recall, F1 score and others) are computed during the validation process after each training epoch and saved inside the 'results.json' file, in the run directory. But there's no 'shortcut' way, like the confusion matrix example you provided, to display those metrics directly inside a Jupyter notebook.

But thank you for your feedback, it's a good idea to have a similar approach for accessing these. We'll consider this for future updates to the Ultralytics YOLOv8 repo. Please feel free to reach out if you have any more suggestions or queries.
