### ISSUE TITLE
Personalize export output

### ISSUE THREAD

**Issue by Djkmarco** [ultralytics/ultralytics#4115]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Actual export of yolov8 head:
`return y if self.export else (y, x)`

It would be nice to export the model with three additional options:

splitting outputs: having cls and dbox outputs in a single (actual) or separated (**new**) nodes.
e.g (from head.py)
`return cls.sigmoid(), dbox if self.export else (y, x`)

more options for bbox output format: it would be nice to select the desired bbox format in export.
E.g. "XYXY", "XYWH", "rXYXY", "rXYWH".

swap output axes: it would be nice to swap axes of (anchors x predictions) and (anchors x boxes).
E.g.
`return torch.swapaxes(cls.sigmoid(), 1, 2), torch.swapaxes(dbox, 1, 2) if self.export else (y, x)`

### Use case

Yolov8 is often used as engine in more complex operations.
Adding more options for model outputs during export could help compatibility with other systems, in particular when yolov8 is packed in formats such as .onnx.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Djkmarco hi,

Thank you for bringing up these ideas on exporting more customized configurations for YOLOv8! I agree that these features could definitely enhance the compatibility of our model with other systems, especially when packed in formats like .onnx.

Regarding the splitting of outputs, it would indeed be feasible to allow the class and bounding box predictions to have separate outputs during export.

As for more options for bounding box output formats, this could be done by implementing conversion functionality during the export process. The user could select the desired format for their situation.

Finally, the capability to swap output axes could also be introduced. A function could be developed that takes the axes to be swapped as parameters during export.

Your suggestions for these new features are valuable and we appreciate it. Please keep in mind that adding these features would require careful validation to ensure they function as intended. As an open-source project, these changes would be done as the workload and priorities allow.

Thank you once again for your suggestions and support for the YOLOv8 project. We greatly appreciate your active involvement in the YOLOv8 community!

Best,
Glenn
