### ISSUE TITLE
YOLO-NAS predict fail

### ISSUE THREAD

**Issue by huynhhoanghuy** [ultralytics/ultralytics#4120]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi all, I am researching yolo-nas and I read your document how to use it:

`
from ultralytics import NAS 
`
`
model = NAS('yolo_nas_s')
`
`
results = model.predict('/home/dmp/1.Users/3.huy.hhoang/objectdetect/sample.jpg', save=True)
`
However, it not work, this is error:

![image](https://github.com/ultralytics/ultralytics/assets/32119423/b2c27149-6c04-4721-a2f6-ff7a639519ac)

I have tried yolov5 + yolov8. Both they work!

This is my enviroment:

> 
> Package                       Version
> ----------------------------- ----------
> absl-py                       1.4.0
> alabaster                     0.7.13
> antlr4-python3-runtime        4.9.3
> attrs                         23.1.0
> Babel                         2.12.1
> boto3                         1.28.17
> botocore                      1.31.17
> build                         0.10.0
> cachetools                    5.3.1
> certifi                       2023.7.22
> charset-normalizer            3.2.0
> click                         8.1.6
> cmake                         3.27.0
> coloredlogs                   15.0.1
> contourpy                     1.1.0
> coverage                      5.3.1
> cycler                        0.11.0
> Deprecated                    1.2.14
> docutils                      0.17.1
> einops                        0.3.2
> filelock                      3.12.2
> flatbuffers                   23.5.26
> fonttools                     4.41.1
> future                        0.18.3
> google-auth                   2.22.0
> google-auth-oauthlib          1.0.0
> grpcio                        1.56.2
> humanfriendly                 10.0
> hydra-core                    1.3.2
> idna                          3.4
> imagesize                     1.4.1
> importlib-metadata            6.8.0
> importlib-resources           6.0.0
> Jinja2                        3.1.2
> jmespath                      1.0.1
> json-tricks                   3.16.1
> jsonschema                    4.18.4
> jsonschema-specifications     2023.7.1
> kiwisolver                    1.4.4
> lit                           16.0.6
> Markdown                      3.4.4
> markdown-it-py                3.0.0
> MarkupSafe                    2.1.3
> matplotlib                    3.7.2
> mdurl                         0.1.2
> mpmath                        1.3.0
> networkx                      3.1
> numpy                         1.23.0
> nvidia-cublas-cu11            11.10.3.66
> nvidia-cuda-cupti-cu11        11.7.101
> nvidia-cuda-nvrtc-cu11        11.7.99
> nvidia-cuda-runtime-cu11      11.7.99
> nvidia-cudnn-cu11             8.5.0.96
> nvidia-cufft-cu11             10.9.0.58
> nvidia-curand-cu11            10.2.10.91
> nvidia-cusolver-cu11          11.4.0.1
> nvidia-cusparse-cu11          11.7.4.91
> nvidia-nccl-cu11              2.14.3
> nvidia-nvtx-cu11              11.7.91
> oauthlib                      3.2.2
> omegaconf                     2.3.0
> onnx                          1.13.0
> onnx-simplifier               0.4.33
> onnxruntime                   1.13.1
> opencv-python                 4.8.0.74
> packaging                     23.1
> pandas                        2.0.3
> Pillow                        10.0.0
> pip                           23.2.1
> pip-tools                     7.1.0
> pkg_resources                 0.0.0
> pkgutil_resolve_name          1.3.10
> protobuf                      3.20.3
> psutil                        5.9.5
> py-cpuinfo                    9.0.0
> pyasn1                        0.5.0
> pyasn1-modules                0.3.0
> pycocotools                   2.0.6
> pyDeprecate                   0.3.2
> Pygments                      2.15.1
> pyparsing                     2.4.5
> pyproject_hooks               1.0.0
> python-dateutil               2.8.2
> pytz                          2023.3
> PyYAML                        6.0.1
> rapidfuzz                     3.2.0
> referencing                   0.30.0
> requests                      2.31.0
> requests-oauthlib             1.3.1
> rich                          13.5.2
> rpds-py                       0.9.2
> rsa                           4.9
> s3transfer                    0.6.1
> scipy                         1.10.1
> seaborn                       0.12.2
> setuptools                    44.0.0
> six                           1.16.0
> snowballstemmer               2.2.0
> Sphinx                        4.0.3
> sphinx-rtd-theme              1.2.2
> sphinxcontrib-applehelp       1.0.4
> sphinxcontrib-devhelp         1.0.2
> sphinxcontrib-htmlhelp        2.0.1
> sphinxcontrib-jquery          4.1
> sphinxcontrib-jsmath          1.0.1
> sphinxcontrib-qthelp          1.0.3
> sphinxcontrib-serializinghtml 1.1.5
> stringcase                    1.2.0
> super-gradients               3.1.3
> sympy                         1.12
> tensorboard                   2.13.0
> tensorboard-data-server       0.7.1
> termcolor                     1.1.0
> tomli                         2.0.1
> torch                         2.0.1
> torchmetrics                  0.8.0
> torchvision                   0.15.2
> tqdm                          4.65.0
> treelib                       1.6.1
> triton                        2.0.0
> typing_extensions             4.7.1
> tzdata                        2023.3
> ultralytics                   8.0.146
> urllib3                       1.26.16
> Werkzeug                      2.3.6
> wheel                         0.41.0
> wrapt                         1.15.0
> zipp                          3.16.2

I am using Python3.8 and this CUDA version:
![image](https://github.com/ultralytics/ultralytics/assets/32119423/6186fde5-b820-468f-bd78-b8c4c27d322a)

I don't understand what wrongs. Could you help me?

**Comment by huynhhoanghuy** [comment]
I have installed "pip install pytorch-quantization" for resolving warning. However, it still raise issue like above.

**Comment by glenn-jocher** [comment]
@huynhhoanghuy hello, thank you for using YOLOv8 and reaching out with your issue.

It appears that you are encountering an issue after installing "pytorch-quantization" to address a warning. However, without more context or information about the type of warning you were receiving, it's difficult to provide a direct solution.

"pytorch-quantization" is a library for quantizing PyTorch models, and might not be necessary for your use case. If you continue to face issues after the installation, you may want to consider uninstalling it. 

Start by checking your PyTorch version and ensuring that it's compatible with YOLOv8. Moreover, cross-verify the installation process of the library and try reinstalling it. If the warning persists, kindly provide more information about your environment and the exact warning message. 

Doing so will allow us to provide a more accurate solution. Thank you!

**Comment by Mineru98** [comment]
![스크린샷 2023-08-11 오후 4 45 29](https://github.com/ultralytics/ultralytics/assets/15326932/8a2f9fcb-12e2-4490-a178-9569e2650806)

I seem to have a similar issue.

```python
result = model.predict(images[0])
```

It works fine on yolov5, yolov8.

**Comment by glenn-jocher** [comment]
@Mineru98 thank you for reaching out with your issue. From the information provided, it's not entirely clear what the problem might be. However, the code snippet you've provided should work fine with YOLOv8 if it is working as expected with another version.

First, let's ascertain there aren't any issues with the image or model loading. Make sure your image is correctly loaded in the expected format and the model used matches with the YOLOv8's configurations. 

Lastly, ensure that your environment is set up correctly. Check the versions of PyTorch and the other dependencies to ensure their compatibility with YOLOv8.

To help us provide a more accurate solution, could you provide more specific details regarding the issue? Are there any error messages being displayed? And could you please also share more details about your environment? This information will help identify the source of the problem.

**Comment by qCanoe** [comment]
@Mineru98 @huynhhoanghuy 
just revert the version of super-gradients to 3.1.1 or try 3.1.0
