### ISSUE TITLE
AttributeError: 'list' object has no attribute 'boxes'   Still cant figure out this problem 

### ISSUE THREAD

**Issue by treeone246** [ultralytics/ultralytics#4122]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

keep on getting this error:
File ".\appSuspendedLoad.py", line 58, in <module>
    boxes = results.boxes[0]
AttributeError: 'list' object has no attribute 'boxes'

I have been searching and tried updating the ultralytics version but still not getting any results from finding the problem.
It might be really helplful if someone can figure this problem out Thanks!!

### Environment

ltralytics YOLOv8.0.146 Python-3.7.16 torch-1.7.1+cu118 CUDA:0 (NVIDIA RTX Quadro 5000)

### Minimal Reproducible Example

`import math
import cv2
import numpy as np
from ultralytics import YOLO

def calculate_distance(x1, y1, x2, y2):
    distance = math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)
    return distance

def find_centroid(box):
    x1, y1, x2, y2 = box
    cx = int((x1 + x2) / 2)
    cy = int((y1 + y2) / 2)
    return cx, cy

def draw_boxes_with_labels_and_distance(img, boxes, labels, names):
    class1_bbox = None
    class2_bbox = None

    for box, label in zip(boxes, labels):
        x1, y1, x2, y2 = int(box[0]), int(box[1]), int(box[2]), int(box[3])
        class_label = names[int(label)]
     
        cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.putText(img, class_label, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

        if class_label == 'crane_hook':
            class1_bbox = (x1, y1, x2, y2)
        elif class_label == 'crane_boom':
            class2_bbox = (x1, y1, x2, y2)

    if class1_bbox is not None and class2_bbox is not None:
        cx1, cy1 = find_centroid(class1_bbox)
        cx2, cy2 = find_centroid(class2_bbox)
        distance = calculate_distance(cx1, cy1, cx2, cy2)
 
        cv2.putText(img, f"Distance between crane_hook and crane_boom: {distance:.2f} pixels", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

model = YOLO("C:/Users/Owner/yolov8/runs/detect/train39/weights/best.pt")
img = cv2.imread("C:/Users/Owner/yolov8/inference/testing5.png")
results = model.predict(img)

boxes = results.boxes[0]
labels = results.probs[0].argmax(dim=1)

names = model.names
draw_boxes_with_labels_and_distance(img, boxes, labels, names)

cv2.imshow("Detected Objects with Labels and Distance Measurements", img)
cv2.waitKey(0)
cv2.destroyAllWindows()`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@treeone246 The returned `results` is a list of Results class, so the correct usage is:
```python
results = model.predict(img)[0]
boxes = results.boxes[0]
```
