### ISSUE TITLE
Yolov8 pose model

### ISSUE THREAD

**Issue by karunakr** [ultralytics/ultralytics#4128]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

We are using yolov8 model for pose detection. Wondering is the model gets updated periodically?. Also, is there a option where we can check the last updated date of model?

Thanks
Karunakar

**Comment by glenn-jocher** [comment]
@karunakr hello Karunakar,

Thanks for bringing up this topic! The YOLOv8 model, like other components of the repo, is updated routinely as part of our commitment to push forward with improvements and new features. However, explicit versioning or timestamps for individual updates to pose detection model are not maintained as part of the repo.

You can keep an eye on the commit history to track major changes and updates to the repo and all its components. Of course, substantial changes that may affect model functionality or performance will be communicated through appropriate channels like release notes.

Thank you for using YOLOv8 and being part of our community. We greatly value your query and hope this helps!

Best regards,  
Glenn Jocher
