### ISSUE TITLE
Can not see the result of two functions containing yolov8 detector using multiprocessing

### ISSUE THREAD

**Issue by hamid98reza** [ultralytics/ultralytics#4129]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I need to process two videos using yolov8 and opencv simultaneously so I decided to use two functions and run them in parallel using multiprocessing. but I just get one of the functions (videos) run while executing. I have been digging around for more than a day but I could not find any similar problem or solution for it.

If this way is not a correct way so what would be a feasible solution?

I wanna have the result of two videos at the same time.

I would appreciate it if you could help... .

--> windows11  __  Python 3.10.11 __  Anaconda terminal.

Here is the simplified code:

### Additional

```
`from ultralytics import YOLO
import os
import cv2
import multiprocessing as mp

source1 = os.path.join('.','football-video.mp4')
source2 = os.path.join('.','people.mp4')

class Detection:
    def first_detector():
        model1 = YOLO('yolov8n.pt')
        for i in range(20):
            print(" first_detector is executing ********")
        model1.predict(source=source1,save=False,device='cpu')
    
    def second_detector():
        model2 = YOLO('yolov8n.pt')
        for i in range(20):
            print(" second_detector is executing ********")
        model2.predict(source=source2,save=False,device='cpu')

if __name__=="__main__":
    P1 = mp.Process(target=Detection.first_detector())
    P2 = mp.Process(target=Detection.second_detector())

    P1.start()
    P2.start()
    
    P2.join()
    P2.join()`
```

 I get just the result of the first functions while running on the terminal:

```
`video 1/1 (20/1074) E:\\mine\\mine_venv\\football-video.mp4: 384x640 4 persons, 218.8ms
video 1/1 (21/1074) E:\\mine\\mine_venv\\football-video.mp4: 384x640 4 persons, 234.4ms
video 1/1 (22/1074) E:\\mine\\mine_venv\\football-video.mp4: 384x640 4 persons, 234.4ms
video 1/1 (23/1074) E:\\mine\\mine_venv\\football-video.mp4: 384x640 6 persons, 218.7ms`
```

**Comment by glenn-jocher** [comment]
@hamid98reza hello, 

Thank you for reaching out. You're on the right path using Python's multiprocessing module to process video stream data from two sources in parallel.

From your code snippet, the potential problem I can identify is how you've structured the Process() targets. When specifying the target for multiprocessing, you typically want to reference the function, not call it. 

In your script: 

```python
P1 = mp.Process(target=Detection.first_detector())
P2 = mp.Process(target=Detection.second_detector())
```

you're actually calling the function. Instead, you should just reference it like so:

```python
P1 = mp.Process(target=Detection.first_detector)
P2 = mp.Process(target=Detection.second_detector)
```

Also ensure that 'yolov8n.pt' can be accessed by different detectors at the same time. If not, consider using separate model files for each detector.

Lastly, it might be worth considering CPU and memory limitations. Running multiple detectors in parallel can be very demanding on your resources. 

For debugging, make sure to isolate and test your multiprocessing with a dummy function to confirm that multiprocessing is working as expected on your system.

If you follow the advice above but the problem persists, feel free to provide more information or ask further questions! 

I hope this helps and best of luck with your project.

**Comment by hamid98reza** [comment]
thank you so much @glenn-jocher for your great help.🙌

Yes, It has just resolved by removing the prentices. It was a mistake I didn't realize.

After removing the prentices here is the result: ✌️

`video 1/1 (62/341) K:\mine\mine_venv\people.mp4: 384x640 39 persons, 1 bird, 93.7ms
video 1/1 (62/1074) K:\mine\mine_venv\football-video.mp4: 384x640 1 person, 93.7ms
video 1/1 (63/341) K:\mine\mine_venv\people.mp4: 384x640 36 persons, 78.1ms
video 1/1 (63/1074) K:\mine\mine_venv\football-video.mp4: 384x640 1 person, 93.7ms`

**Comment by hamid98reza** [comment]
👍

**Comment by glenn-jocher** [comment]
You're welcome, @hamid98reza! I'm glad to hear that simply removing the parentheses resolved the issue. Now you should be able to process two videos simultaneously with YOLOv8. It's always satisfying when a small change produces a big result. If you encounter any more situations like this or have additional questions, don't hesitate to reach out. Happy coding!
