### ISSUE TITLE
Is it possible to get the bounding boxes in xyxy format? Just as in previous versions ( results.xyxy)

### ISSUE THREAD

**Issue by Eneko9** [ultralytics/ultralytics#414]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is it possible to get the bounding boxes in xyxy format? Just as in previous versions ( results.xyxy ) 

I have an application that uses the v7 version and I would like to update it to the v8.

here is an example of the code in the previous version:
![example](https://user-images.githubusercontent.com/71316809/212687694-5b4ab21f-b080-45d2-95ba-f5a56a584453.PNG)

**Comment by AyushExel** [comment]
Yes it is coming soon with this PR https://github.com/ultralytics/ultralytics/pull/314

**Comment by dene-** [comment]
Right now you can do like:

```python
pred = model.predict(source="screen", return_outputs=True)

for output in pred:
    for detection in output['det']:
        top_x, top_y, bottom_x, bottom_y, accuracy, type = detection
```
