### ISSUE TITLE
For yolov8 pose model, how do I get tracking id for each keypoint set?

### ISSUE THREAD

**Issue by satwik-stp** [ultralytics/ultralytics#4150]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to confirm if the rows of bounding box data (including the id) and keypoint data in the result of the yolov8 pose model are correctly associated. ie. Is the first row of box data corresponds to the first keypoint data?

Thanks

**Comment by glenn-jocher** [comment]
@satwik-stp yes, you're correct. The tracking ID of each keypoint set is associated with the corresponding bounding box. In the results of the YOLOv8 pose model, the order of the rows for bounding box data and keypoint data is matched. This implies that the first row of bounding box data corresponds to the first keypoint data, the second to the second, and so forth. This allows each set of keypoints to be connected to a specific object in the detection output.

It's important to ensure that you are working with the correct data when handling tracking tasks, especially when the same object appears in consecutive frames. For accurate tracking, ensure that the associations between bounding boxes and keypoints are maintained consistently across different frames.

Your understanding is correct and seems like you are on the right path. Keep experimenting and feel free to drop in any more queries you might have. Best of luck with your work on the YOLOv8 pose model!

**Comment by satwik-stp** [comment]
Thank you the answer

**Comment by glenn-jocher** [comment]
@satwik-stp you're welcome! I'm glad I could assist. If you have any other questions or need further clarification regarding YOLOv8, feel free to ask. We're here to help. Best of luck with your work!
