### ISSUE TITLE
Multiprocessing Errror

### ISSUE THREAD

**Issue by sangramdhurve** [ultralytics/ultralytics#4161]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm training yolov8m.pt for an object detection task with 340 classes, I'm facing issues with Mac m1 pro's 'mps' while training I can't give 100 epochs if I'll give 40 it is running but if I'll increase it is throwing error, please giver me guidance regarding this, thanks in advance.

**Comment by glenn-jocher** [comment]
@sangramdhurve hi there,

It sounds like you're running into a multiprocessing issue with your Mac M1 Pro machine during the training of your YOLOv8 model. 

One thing to note about the Apple's M1 chip is that it uses the ARM architecture, which can behave differently from the more traditional x86-64 architecture when running certain tasks, especially when it comes to multiprocessing within the context of machine learning. There may be specific compatibility issues at play here.

The issue might also be tied to the number of epochs you're trying to run. Training a model for a large number of epochs can be resource-intensive as it involves performing multiple passes over the training dataset. If the dataset is large, this can exceed the available resources on your system, possibly triggering the error you're observing.

Here's what you can do:
* You could try reducing the batch size per epoch, this would consume less resources per epoch and might allow you to increase the number of epochs.
* Increasing your system's resources might help if that's an option. Whether by closing out non-essential processes to free up more processing power and memory, or consider using a machine with more resources.
* Lastly, you might consider updating the multiprocessing library to the latest version, just to rule out the possibility of a bug in the library itself.

Please let us know if you're still experiencing this issue after trying these solutions so we can continue to assist you. I hope this helps, and best of luck with your project!
