### ISSUE TITLE
Specify output folder

### ISSUE THREAD

**Issue by axteroide** [ultralytics/ultralytics#4162]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi!.

I've been looking through the config docs and issues, but I'm not able to find if it's possible to specify the output path for labels and results. I see it's possible to change project's name, but nothing else.

Is it possible?

**Comment by glenn-jocher** [comment]
@axteroide hello! 

Yes, it's definitely possible to specify the output path for your labels and results in YOLOv8. The output directory is typically determined by the `--project` and `--name` arguments during training. The `--project` argument determines your root directory where all projects will be saved, while the `--name` argument specifies the name of the specific project. 

By default, the project's name is 'exp', and if it already exists, the name becomes 'exp2', 'exp3' and so on. But you can specify your own personal project name, and all outputs, including labels and results, will be saved in that directory.

So in brief, just specify your desired directory path with the `--project` argument and your preferred project name with the `--name` argument when you call the training function. 

Remember all paths are relative to your current working directory, if you specify a relative path. For an absolute path, ensure your input starts from the root directory.

I hope this helps! If you have more questions, feel free to ask.

**Comment by gboeer** [comment]
This is just a partial solution, especially for the case, when a project name is configured as well.
The project name will take precedence over the customized runs_dir, hence it is not possible to change the runs_dir when also supplying a project name.

However, the latter is needed e.g. when using an external experiment tracker like mlflow, where the project name at the same time is used to log to the respective mlflow experiment.

I have created a fix a long time ago, however the PR was closed due to inactivity, while all that would be needed is a simple review:
https://github.com/ultralytics/ultralytics/pull/19133

**Comment by glenn-jocher** [comment]
Thanks for raising this. You’re right: when `project` is set it takes precedence over `runs_dir`—that’s the current design in `get_save_dir()`; see the function behavior in the [reference docs](https://docs.ultralytics.com/reference/cfg/__init__/#ultralytics.cfg.get_save_dir). To decouple MLflow experiment naming from filesystem outputs, set the experiment via `MLFLOW_EXPERIMENT_NAME` and leave YOLO’s `project` unset, then control the output root via `runs_dir` (or set `save_dir` directly in Python):

```bash
export MLFLOW_EXPERIMENT_NAME='my_exp'
yolo settings runs_dir='/path/to/runs'
yolo train model=yolo11n.pt data=coco8.yaml name=my_run
```

```python
from ultralytics import YOLO
YOLO("yolo11n.pt").train(data="coco8.yaml", save_dir="/path/to/outputs/my_exp")
```

MLflow usage details are in the [MLflow Integration guide](https://docs.ultralytics.com/integrations/mlflow/) and settings in the [Ultralytics Settings](https://docs.ultralytics.com/quickstart/#ultralytics-settings). For your closed PR, please open a fresh, rebased PR with a minimal, well-scoped change plus tests/docs; we can’t promise timelines, but we’ll review—see the [Contributing Guide](https://docs.ultralytics.com/help/contributing/).
