### ISSUE TITLE
Error in ultralytics

### ISSUE THREAD

**Issue by 26Kenn07** [ultralytics/ultralytics#4163]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 1
----> 1 import ultralytics

File ~/pytorch-test/env/lib/python3.10/site-packages/ultralytics/__init__.py:5
      1 # Ultralytics YOLO 🚀, AGPL-3.0 license
      3 __version__ = '8.0.147'
----> 5 from ultralytics.hub import start
      6 from ultralytics.models import RTDETR, SAM, YOLO
      7 from ultralytics.models.fastsam import FastSAM

File ~/pytorch-test/env/lib/python3.10/site-packages/ultralytics/hub/__init__.py:5
      1 # Ultralytics YOLO 🚀, AGPL-3.0 license
      3 import requests
----> 5 from ultralytics.data.utils import HUBDatasetStats
      6 from ultralytics.hub.auth import Auth
      7 from ultralytics.hub.utils import HUB_API_ROOT, HUB_WEB_ROOT, PREFIX

File ~/pytorch-test/env/lib/python3.10/site-packages/ultralytics/data/__init__.py:3
      1 # Ultralytics YOLO 🚀, AGPL-3.0 license
----> 3 from .base import BaseDataset
      4 from .build import build_dataloader, build_yolo_dataset, load_inference_source
      5 from .dataset import ClassificationDataset, SemanticDataset, YOLODataset

File ~/pytorch-test/env/lib/python3.10/site-packages/ultralytics/data/base.py:18
     15 from torch.utils.data import Dataset
     16 from tqdm import tqdm
---> 18 from ultralytics.utils import DEFAULT_CFG, LOCAL_RANK, LOGGER, NUM_THREADS, TQDM_BAR_FORMAT
     20 from .utils import HELP_URL, IMG_FORMATS
     23 class BaseDataset(Dataset):

File ~/pytorch-test/env/lib/python3.10/site-packages/ultralytics/utils/__init__.py:818
    814 # Run below code on utils init ------------------------------------------------------------------------------------
    815 
    816 # Check first-install steps
    817 PREFIX = colorstr('Ultralytics: ')
--> 818 SETTINGS = SettingsManager()  # initialize settings
    819 DATASETS_DIR = Path(SETTINGS['datasets_dir'])  # global datasets directory
    820 ENVIRONMENT = 'Colab' if is_colab() else 'Kaggle' if is_kaggle() else 'Jupyter' if is_jupyter() else \
    821     'Docker' if is_docker() else platform.system()

File ~/pytorch-test/env/lib/python3.10/site-packages/ultralytics/utils/__init__.py:763, in SettingsManager.__init__(self, file, version)
    760 if not self.file.exists():
    761     self.save()
--> 763 self.load()
    764 correct_keys = self.keys() == self.defaults.keys()
    765 correct_types = all(type(a) == type(b) for a, b in zip(self.values(), self.defaults.values()))

File ~/pytorch-test/env/lib/python3.10/site-packages/ultralytics/utils/__init__.py:777, in SettingsManager.load(self)
    775 def load(self):
    776     """Loads settings from the YAML file."""
--> 777     super().update(yaml_load(self.file))

TypeError: 'NoneType' object is not iterable
<img width="955" alt="Screenshot 2023-08-04 at 5 28 08 PM" src="https://github.com/ultralytics/ultralytics/assets/101725933/36472d85-85ea-4512-b0b3-c143701b6213">

### Environment

pytorch
ultralytics 8.0.147

### Minimal Reproducible Example

import ultralytics

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by guillermovc** [comment]
I have the same problem with version  8.0.147.
I solved it downgrading to version 8.0.112

**Comment by glenn-jocher** [comment]
@26Kenn07 thanks for your feedback! It's interesting to hear that downgrading to version 8.0.112 resolved the issue for you. This information could definitely be valuable and would help us investigate the issue thoroughly and provide better fixes in the future implementations of Ultralytics YOLOv8. We'll certainly look into the difference between the two versions and work on a fix to address this error in the latest version. Thanks for sharing your solution with us and we apologize for any inconvenience caused by this error. For now, you can continue using version 8.0.112 if it's working well for your project.

**Comment by relaxandcodezjmo** [comment]
I had the same issue few days ago and solved it by deleting the settings.yaml in your Ultralytics folder. Check my issue for more details here: https://github.com/ultralytics/ultralytics/issues/4104

**Comment by glenn-jocher** [comment]
@26Kenn07 @relaxandcodezjmo great news 😃! Your original issue may now be resolved ✅ in PR #4180 and pushed to a new pip release `ultralytics 8.0.148`. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!
