### ISSUE TITLE
YOLO-NAS training and inference

### ISSUE THREAD

**Issue by jeck00119** [ultralytics/ultralytics#4167]
### Description

Hi! It will be helpful if you could add training support or at least add .pth support for inference. I think this repo will be useful: https://github.com/naseemap47/YOLO-NAS (you can train and do inference, the trained model is saved as .pth).

**Comment by glenn-jocher** [comment]
@jeck00119 hello,

Thank you for your suggestion! We are always open to feedback to enhance the capabilities of our YOLOv8 repository.

At present, adding training and .pth file support for YOLO-NAS in the YOLOv8 repo is not part of our roadmap. That being said, this suggestion is certainly interesting and we will discuss internally about potentially adding it in future iterations.

Our focus now is to enhance the capabilities and performance of YOLOv8, and we remain committed to continuous optimizations on that front.

We appreciate your understanding and your ideas on how to improve YOLOv8. Your contribution to the community is valuable.

Best regards,
Glenn Jocher.
