### ISSUE TITLE
Any suggestions to improve performance on small objects?

### ISSUE THREAD

**Issue by MR-hyj** [ultralytics/ultralytics#4173]
I evaluated my yolo model against coco annotations.
![image](https://github.com/ultralytics/ultralytics/assets/46344518/f2a52a7c-265f-4b05-8752-69b93da23137)
It is very clear that the yolo model is far from satisfying on small objects. 
Any suggestions? I've tried data augmentation which did little contribution

**Comment by Y-T-G** [comment]
Increase resolution.

**Comment by glenn-jocher** [comment]
@Y-T-G increasing the input image resolution could improve your model's ability to detect smaller objects. Higher resolution images provide more detail and can allow the model to detect smaller objects that it might miss at lower resolutions. 

When working with higher resolution images, you should also ensure your model architecture can effectively learn from these larger input tensors. This might involve adjusting the stride sizes or adding more layers to your model to handle the increase in spatial complexity. 

You can just increase the input size when you initialize your model configuration or update your training configuration file. But keep in mind that higher resolution images might cause an increase in computation time and memory requirement while training. 

And finally, don't forget to adjust your anchor boxes to better suit small objects. You can do this by running k-means clustering on your bounding box data to determine the best sizes for your anchor boxes.

Remember, increasing the resolution is not a guaranteed method to improve detection on small objects and the improvements might also depend on other factors such as the quality of your dataset, the robustness of your model architecture, and the appropriateness of your training procedures. Always consider the trade-offs when you choose to alter the input resolution.

**Comment by MR-hyj** [comment]
> 

Thank you for such detailed information. Increasing the resolution is definitely helpful in improving performance on small objects. Unfortunately, in my case, the resolution is fixed to 640x640 which can't be resized. 
Trying to apply long-tailed detection methods, I noticed there was a `--img-weights` parameter in yolov5 which seemed to be removed in yolov8?

**Comment by MR-hyj** [comment]
> @Y-T-G increasing the input image resolution could improve your model's ability to detect smaller objects. Higher resolution images provide more detail and can allow the model to detect smaller objects that it might miss at lower resolutions.
> 
> When working with higher resolution images, you should also ensure your model architecture can effectively learn from these larger input tensors. This might involve adjusting the stride sizes or adding more layers to your model to handle the increase in spatial complexity.
> 
> You can just increase the input size when you initialize your model configuration or update your training configuration file. But keep in mind that higher resolution images might cause an increase in computation time and memory requirement while training.
> 
> And finally, don't forget to adjust your anchor boxes to better suit small objects. You can do this by running k-means clustering on your bounding box data to determine the best sizes for your anchor boxes.
> 
> Remember, increasing the resolution is not a guaranteed method to improve detection on small objects and the improvements might also depend on other factors such as the quality of your dataset, the robustness of your model architecture, and the appropriateness of your training procedures. Always consider the trade-offs when you choose to alter the input resolution.

Thank you for such detailed information. Increasing the resolution is definitely helpful in improving performance on small objects. Unfortunately, in my case, the resolution is fixed to 640x640 which can't be resized.
Trying to apply long-tailed detection methods, I noticed there was a --img-weights parameter in yolov5 which seemed to be removed in yolov8?

**Comment by HtwoOtwo** [comment]
I am also facing the same problem. I have tried to modify model config file adding 160 x 160 out feature map (backbone is unchanged):
```
# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 12
 
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 15 (P3/8-small)
 
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 2], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [128]]  # 18 (P2/4-xsmall)
 
  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 15], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [256]]  # 21 (P3/8-small)
 
  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [512]]  # 24 (P4/16-medium)
 
  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 27 (P5/32-large)

  - [[18, 21, 24, 27], 1, Detect, [nc]]  # Detect(P2, P3, P4, P5)
  ```
But the effect is not very obvious in my task, maybe you can have a try.

**Comment by glenn-jocher** [comment]
@HtwoOtwo thank you for sharing your approach. Adding additional layers to the model's head, specifically an additional 160 x 160 output feature map, is indeed one way that could potentially help in detecting smaller objects. This approach essentially increases the granularity of the output, allowing the model to make predictions at a more granular scale, which could assist in detecting smaller objects.

However, the effects of adding this feature map heavily depend on your specific task and dataset. If the objects you are trying to detect are significantly smaller and not well represented in the training data, and/or if the model's architecture itself is not well suited to detecting objects of this size, then this modification might have minimal impact.

It's also important to bear in mind that adding additional layers to the model can increase computational cost and complexity, as well as potentially introduce additional noise into the model's predictions.

If adding this feature map didn't noticeably improve your model's performance, alternative strategies could be explored, such as gathering more training data for smaller objects, trying other architectures or models which might be better suited for detecting small objects, or employing techniques like hard negative mining wherein you focus more on training examples where your model performs poorly.

**Comment by sxstone** [comment]
> @Y-T-G increasing the input image resolution could improve your model's ability to detect smaller objects. Higher resolution images provide more detail and can allow the model to detect smaller objects that it might miss at lower resolutions.
> 
> When working with higher resolution images, you should also ensure your model architecture can effectively learn from these larger input tensors. This might involve adjusting the stride sizes or adding more layers to your model to handle the increase in spatial complexity.
> 
> You can just increase the input size when you initialize your model configuration or update your training configuration file. But keep in mind that higher resolution images might cause an increase in computation time and memory requirement while training.
> 
> And finally, don't forget to adjust your anchor boxes to better suit small objects. You can do this by running k-means clustering on your bounding box data to determine the best sizes for your anchor boxes.
> 
> Remember, increasing the resolution is not a guaranteed method to improve detection on small objects and the improvements might also depend on other factors such as the quality of your dataset, the robustness of your model architecture, and the appropriateness of your training procedures. Always consider the trade-offs when you choose to alter the input resolution.



> @HtwoOtwo thank you for sharing your approach. Adding additional layers to the model's head, specifically an additional 160 x 160 output feature map, is indeed one way that could potentially help in detecting smaller objects. This approach essentially increases the granularity of the output, allowing the model to make predictions at a more granular scale, which could assist in detecting smaller objects.
> 
> However, the effects of adding this feature map heavily depend on your specific task and dataset. If the objects you are trying to detect are significantly smaller and not well represented in the training data, and/or if the model's architecture itself is not well suited to detecting objects of this size, then this modification might have minimal impact.
> 
> It's also important to bear in mind that adding additional layers to the model can increase computational cost and complexity, as well as potentially introduce additional noise into the model's predictions.
> 
> If adding this feature map didn't noticeably improve your model's performance, alternative strategies could be explored, such as gathering more training data for smaller objects, trying other architectures or models which might be better suited for detecting small objects, or employing techniques like hard negative mining wherein you focus more on training examples where your model performs poorly.

@glenn-jocher Hello, master. I have encountered the same issue, but I don't understand the concept or method of adjusting anchor sizes in YOLOv8. However, I know that in YOLOv5, it's done using k-means clustering and then setting the anchor sizes. How is this done in YOLOv8?

**Comment by glenn-jocher** [comment]
@sxstone hello,

Thank you for your question.

In YOLOv8, as with other YOLO versions, anchor boxes play a crucial role in object detection, particularly for handling different shapes and sizes of objects.

The anchor box sizes in YOLOv8 can be determined through a similar process as in previous versions, using a clustering algorithm. This should ideally be done on your specific dataset to get the most representative anchor box sizes. However, this has to be performed outside the model as an additional preprocessing step, utilising a tool or script for running the clustering on your bounding box dimensions.

After determining the appropriate anchor sizes, these are then entered into the respective configuration file of the model. They are set as parameters of the model during initialization.

Please be aware that adjusting anchor sizes must be done thoughtfully as changing them could affect the performance of your object detection: it could improve the model's ability to detect objects of certain sizes, but may impair its ability to detect others.

If you notice that modifying the anchor sizes doesn’t significantly improve your model's performance on small objects, you might want to try other strategies. Potential alternatives could include collecting more training data for small objects, adopting different detection architectures that may be better at detecting small objects, or using techniques like hard negative mining, which emphasizes training on examples where your model struggled.

Should you need further assistance with this topic, please don’t hesitate to reach out. We’re here to help.

**Comment by sxstone** [comment]
> @sxstone hello,
> 
> Thank you for your question.
> 
> In YOLOv8, as with other YOLO versions, anchor boxes play a crucial role in object detection, particularly for handling different shapes and sizes of objects.
> 
> The anchor box sizes in YOLOv8 can be determined through a similar process as in previous versions, using a clustering algorithm. This should ideally be done on your specific dataset to get the most representative anchor box sizes. However, this has to be performed outside the model as an additional preprocessing step, utilising a tool or script for running the clustering on your bounding box dimensions.
> 
> After determining the appropriate anchor sizes, these are then entered into the respective configuration file of the model. They are set as parameters of the model during initialization.
> 
> Please be aware that adjusting anchor sizes must be done thoughtfully as changing them could affect the performance of your object detection: it could improve the model's ability to detect objects of certain sizes, but may impair its ability to detect others.
> 
> If you notice that modifying the anchor sizes doesn’t significantly improve your model's performance on small objects, you might want to try other strategies. Potential alternatives could include collecting more training data for small objects, adopting different detection architectures that may be better at detecting small objects, or using techniques like hard negative mining, which emphasizes training on examples where your model struggled.
> 
> Should you need further assistance with this topic, please don’t hesitate to reach out. We’re here to help.

Thank you very much for your detailed advice！

**Comment by vanguard478** [comment]
> After determining the appropriate anchor sizes, these are then entered into the respective configuration file of the model. They are set as parameters of the model during initialization.

How do I set the anchor box sizes in the configuration file of the model? Are they to be set in `yolo8.yaml` ?

**Comment by engrjav** [comment]
@HtwoOtwo  Hey can you explain what changes you made in head and why
i want to implement on my dataset. I will share results with you but i need to understand the changes

**Comment by engrjav** [comment]
@glenn-jocher  how adding a 160x160 layer in head will improve small object detection for yolov8 as you earlier said that yolov8 is anchor free object dtector

**Comment by glenn-jocher** [comment]
@engrjav 

Adding a 160x160 output feature map to the head of the YOLOv8 model can potentially improve small object detection in the following way: 

The aim is to increase the granularity of the model’s output, which in turn could theoretically help the model to make more accurate predictions on a smaller scale. 

In terms of the size of the objects in relation to the output feature map, smaller objects will take up more space in a 160x160 grid compared to a smaller grid. This means that the model can devote more processing capacity to these small objects, which might help it to detect them more accurately.

However, this approach is not surefire. The outcomes depend greatly on your specific task and dataset. If the smaller objects in your task are significantly smaller than and/or not adequately represented in your training data or model architecture, adding extra layers to the model may not result in improvement. 

Furthermore, it's essential to consider the trade-offs: adding layers can increase the computational cost and complexity of the model, and might also introduce additional noise into the model’s predictions. It is always recommended to experiment with multiple strategies for improving small object detection based on your specific use case.

As for the anchoring mechanisms in YOLOv8, it's indeed an anchor-free object detection model. This means the model doesn't rely on predefined anchor boxes to detect objects, but instead, generates bounding boxes dynamically during the detection process. This can potentially yield more flexible and accurate detection results. 

Adding a 160x160 output feature map with this anchor-free approach is simply about allowing the model to make more granular predictions, not about trying to fit detections to predefined anchor boxes.

**Comment by HtwoOtwo** [comment]
```
 - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
 - [[-1, 2], 1, Concat, [1]] 
 - [-1, 3, C2f, [128]] 
 ```
This code actually upsample featuremap to 128x160x160, then input it to Detect head

**Comment by HtwoOtwo** [comment]
> @HtwoOtwo Hey can you explain what changes you made in head and why i want to implement on my dataset. I will share results with you but i need to understand the changes
```
 - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
 - [[-1, 2], 1, Concat, [1]] 
 - [-1, 3, C2f, [128]] 
 ```
This code actually upsample featuremap to 128x160x160, then input it to Detect head.

**Comment by engrjav** [comment]
@HtwoOtwo  ok thanks a lot .
what i understand is that following the generation of an 80 x 80 scale feature map from the FPN module, an upsampling operation is executed to acquire a 160 x 160feature map. Does this code also directly feeds the fused feature map obtained by integrating the 160 x 160 feature map from the shallow layers of the backbone module into the prediction module?

**Comment by HtwoOtwo** [comment]
> @HtwoOtwo ok thanks a lot .
> what i understand is that following the generation of an 80 x 80 scale feature map from the FPN module, an upsampling operation is executed to acquire a 160 x 160feature map. Does this code also directly feeds the fused feature map obtained by integrating the 160 x 160 feature map from the shallow layers of the backbone module into the prediction module?

Certainly! The following code is doing just that: `[[-1, 2], 1, Concat, [1]] ` by fusing feature from backbone(2nd layer).

**Comment by engrjav** [comment]
@HtwoOtwo  thanks a lot 
Can you please also comment on the figure i have made .. does it reflect your codecorrectly
![changes in yolov8](https://github.com/ultralytics/ultralytics/assets/75246709/8907de75-5d0f-4166-9965-1199ca73599c)

can youadd any corrections?

**Comment by glenn-jocher** [comment]
@HtwoOtwo 

The figure you've made is indeed correct in depicting the changes you've implemented. It accurately shows how an 80x80 feature map is upsampled to 160x160. The feature map is then appropriately fused with a 160x160 feature map from shallow layers of the backbone module. Later, this fused feature map is input into the prediction module.

This approach may improve the model's ability to detect small objects by increasing the granularity of the predictions, making it easier for the small objects to be detected and recognized properly.

One minor correction could be the labeling to clearly mention which layer of the backbone the 160x160 feature map is coming from. But overall, the figure is a clear and accurate representation of the pipeline changes.

Hope this clears your doubts and I am glad to assist you in your endeavors. Feel free to ask if you have any more questions!

**Comment by engrjav** [comment]
@glenn-jocher thanks sir

 Based upon the code, i shared above, i am struggling to understand that which is the second layer   of backbone in the diagram as my 160x160 feature map is coming from. feature map is coming from second layer  but to label that i need to identify the second layer in diagram.

i would be happy if you can point it out please

**Comment by glenn-jocher** [comment]
@engrjav sure, I'm happy to help clarify. 

In the YOLOv8 architecture, the backbone is composed of convolutional layers that serve as feature extractors. To identify where the 160x160 feature map is coming from, you need to inspect your architecture and locate the second Convolutional block in your backbone model.

Generally, the backbone layers' outputs are multi-scale feature maps, which means they output feature maps of different sizes. The exact nature of these sizes depends on the configuration of your model and the parameters you've set. In this case, you've upsampled the 80x80 feature map to 160x160 and then fused this with a 160x160 feature map that's coming from the initial layers of the backbone.

However, note that the exact layer providing the 160x160 feature map could vary depending on the specific architecture you're using for YOLOv8. It's usually a layer that retains enough spatial information about the original image while providing a high-level understanding of the objects in the image. You would have to look at your model summary or architecture diagram for the specifics of the layer (like exact layer number).

I hope this helps! Let me know if you have more questions.

**Comment by HtwoOtwo** [comment]
> @HtwoOtwo thanks a lot Can you please also comment on the figure i have made .. does it reflect your codecorrectly ![changes in yolov8](https://user-images.githubusercontent.com/75246709/265187423-8907de75-5d0f-4166-9965-1199ca73599c.jpg)
> 
> can youadd any corrections?

Glad to help! In fact, a more accurate diagram should be:
![image](https://github.com/ultralytics/ultralytics/assets/24851046/e4fbb02a-7f8c-4843-8bbe-649a3ad26cbf)
The second layer of the backbone carries more original information of the image, and can theoretically better detect small objects through fusion with the 160x160 feature map.

**Comment by HtwoOtwo** [comment]
> @HtwoOtwo thanks a lot Can you please also comment on the figure i have made .. does it reflect your codecorrectly ![changes in yolov8](https://user-images.githubusercontent.com/75246709/265187423-8907de75-5d0f-4166-9965-1199ca73599c.jpg)
> 
> can youadd any corrections?

Glad to help! In fact, a more accurate diagram should be:
![image](https://github.com/ultralytics/ultralytics/assets/24851046/60db9c31-621d-45ae-9444-0734fa7f1eaa)
The second layer of the backbone carries more original information of the image, and can theoretically better detect small objects through fusion with the 160x160 feature map. One more thing, in order to completely match the diagram above, you should change the last line of the yaml file to ` - [[15, 18, 24, 27], 1, Detect, [nc]]`

**Comment by engrjav** [comment]
@HtwoOtwo  I am so thankful for the kindness
What i understand is that the second diagram if i change my last line of code to  - [[15, 18, 24, 27], 1, Detect, [nc]]
it means i have upsampled the 80x80 feature map to 160x160 and then fused this with a 160x160 feature map that's coming from the initial layers of the backbone?
also the added 160x180 feature map would be having the dimensions 160x160x128?

**Comment by HtwoOtwo** [comment]
> @HtwoOtwo I am so thankful for the kindness What i understand is that the second diagram if i change my last line of code to - [[15, 18, 24, 27], 1, Detect, [nc]] it means i have upsampled the 80x80 feature map to 160x160 and then fused this with a 160x160 feature map that's coming from the initial layers of the backbone? also the added 160x180 feature map would be having the dimensions 160x160x128?

Exactly!

**Comment by engrjav** [comment]
@HtwoOtwo  
thanks i will rerun my experiments with changed last line of yaml code too and share the updates with you

**Comment by glenn-jocher** [comment]
@HtwoOtwo Sounds good! We look forward to hearing about your findings. Experimentation is a key part of developing and fine-tuning machine learning models, and adjusting the YAML code can potentially lead to performance improvements in certain cases. Run your tests and feel free to share your results or any further questions you might have. Good luck with your experiments!

**Comment by FatmaMazen2021** [comment]
Dear Mr.@glenn-jocher
Could you kindly share with us the complete yaml file and training command?
Thanks in advance

**Comment by glenn-jocher** [comment]
@FatmaMazen2021 hello,

As per your request for information on the YAML file and training command, I can provide you with general guidance on how these are structured for training YOLOv8 models. However, I will not be able to provide direct code or YAML content.

The YAML file for YOLOv8 typically contains various sections that describe the parameters for the dataset, model, and training process. These sections include paths to the dataset, number of classes, names of classes, and model architecture specifics. Each section should be properly formatted according to the YAML standard and specify the model architecture as a list of layer configurations.

As for the training command, it's usually executed via the Command Line Interface (CLI) and incorporates several options that define the dataset, weights, batch size, epochs, and other hyperparameters that control the training process. You may also specify paths and options for logging, checkpointing, and additional tweaks for GPU usage, precision, etc.

For complete details on the structure of the YAML file and the specific CLI arguments for the training command, please refer to the Ultralytics documentation at https://docs.ultralytics.com, which will provide you with thorough and up-to-date instructions on setting up your training environment for YOLOv8.

Remember to replace the placeholders in the command with your actual file paths and parameter values adjusted to suit your specific training scenario.

If you encounter any issues or have further questions, please feel free to reach out for assistance. Good luck with your training!

**Comment by zeobec** [comment]
I aim to detect small and tiny objects. Therefore, I removed the large and medium detection layers at the head and add new detection layer specifically for tiny object. Can you comment on my architecture design cause I got errors when training
![Uploading Image 06-02-2024 at 4.32 PM.jpeg…]()
?


> > @HtwoOtwo thanks a lot Can you please also comment on the figure i have made .. does it reflect your codecorrectly ![changes in yolov8](https://user-images.githubusercontent.com/75246709/265187423-8907de75-5d0f-4166-9965-1199ca73599c.jpg)
> > can youadd any corrections?
> 
> Glad to help! In fact, a more accurate diagram should be: ![image](https://private-user-images.githubusercontent.com/24851046/265203941-60db9c31-621d-45ae-9444-0734fa7f1eaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTczOTQsIm5iZiI6MTcwNzE1NzA5NCwicGF0aCI6Ii8yNDg1MTA0Ni8yNjUyMDM5NDEtNjBkYjljMzEtNjIxZC00NWFlLTk0NDQtMDczNGZhN2YxZWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE4MTgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwZTRlZTMwZjFjNWViNWE1MWU1OGRhZTRmOTdjMzVmMDMzZjcwMmY4MWIxZTk0MWU3OGUyY2RhZjJiMjFmNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7VRnudU_0hlaoVPkF-JV9vBR4781M7lNV7wIaJ1aM78) The second layer of the backbone carries more original information of the image, and can theoretically better detect small objects through fusion with the 160x160 feature map. One more thing, in order to completely match the diagram above, you should change the last line of the yaml file to ` - [[15, 18, 24, 27], 1, Detect, [nc]]`

**Comment by zeobec** [comment]
@HtwoOtwo I aim to detect small and tiny objects. Therefore, I removed the large and medium detection layers at the head and add new detection layer specifically for tiny object. Can you comment on my architecture design cause I got errors when training
![5A2519FD-D830-411F-9530-5BF20FEF5123_1_105_c](https://github.com/ultralytics/ultralytics/assets/96353364/8571416e-e63c-487a-8ec3-0faaa3c7becf)

**Comment by zeobec** [comment]
> > @HtwoOtwo I aim to detect small and tiny objects. Therefore, I removed the large and medium detection layers at the head and add new detection layer specifically for tiny object. Can you comment on my architecture design cause I got errors when training ![5A2519FD-D830-411F-9530-5BF20FEF5123_1_105_c](https://private-user-images.githubusercontent.com/96353364/302711709-8571416e-e63c-487a-8ec3-0faaa3c7becf.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNjcxMDgsIm5iZiI6MTcwNzI2NjgwOCwicGF0aCI6Ii85NjM1MzM2NC8zMDI3MTE3MDktODU3MTQxNmUtZTYzYy00ODdhLThlYzMtMGZhYWEzYzdiZWNmLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwMDQ2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjQ1NGIzNzViZjk4OWNmYTA4OWFiZmMxZDM3ZWRkMWNjNDE2ZWIwYWQ0N2ViNTUyNGExNzU1YmVlODkzYzU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vs5IHKXgcqDXwedtaAKwM4T5H03cAnlBmTBkguTBzTg)
> 
> It would be easier to debug if you could give a screenshot of your code and error

Traceback (most recent call last):
  File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\60111\anaconda3\envs\yolov8_env\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\ultralytics\cfg\__init__.py", line 541, in entrypoint
    model = YOLO(model, task=task)
  File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\ultralytics\engine\model.py", line 132, in __init__
    self._new(model, task=task, verbose=verbose)
  File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\ultralytics\engine\model.py", line 197, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\ultralytics\nn\tasks.py", line 288, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in forward(torch.zeros(1, ch, s, s))])  # forward
  File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\ultralytics\nn\tasks.py", line 287, in <lambda>
    forward = lambda x: self.forward(x)[0] if isinstance(m, (Segment, Pose, OBB)) else self.forward(x)
  File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\ultralytics\nn\tasks.py", line 80, in forward
    return self.predict(x, *args, **kwargs)
  File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\ultralytics\nn\tasks.py", line 98, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\ultralytics\nn\tasks.py", line 119, in _predict_once
    x = m(x)  # run
  File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\ultralytics\nn\modules\conv.py", line 333, in forward
    return [torch.cat](http://torch.cat/)(x, self.d)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 32 but got size 64 for tensor number 1 in the list.
![image](https://github.com/ultralytics/ultralytics/assets/96353364/42ed5f22-9fd2-42ac-b140-bd9ec8c1e40e)

**Comment by zeobec** [comment]
> > > @HtwoOtwo I aim to detect small and tiny objects. Therefore, I removed the large and medium detection layers at the head and add new detection layer specifically for tiny object. Can you comment on my architecture design cause I got errors when training ![5A2519FD-D830-411F-9530-5BF20FEF5123_1_105_c](https://private-user-images.githubusercontent.com/96353364/302711709-8571416e-e63c-487a-8ec3-0faaa3c7becf.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNjcxMDgsIm5iZiI6MTcwNzI2NjgwOCwicGF0aCI6Ii85NjM1MzM2NC8zMDI3MTE3MDktODU3MTQxNmUtZTYzYy00ODdhLThlYzMtMGZhYWEzYzdiZWNmLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwMDQ2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjQ1NGIzNzViZjk4OWNmYTA4OWFiZmMxZDM3ZWRkMWNjNDE2ZWIwYWQ0N2ViNTUyNGExNzU1YmVlODkzYzU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vs5IHKXgcqDXwedtaAKwM4T5H03cAnlBmTBkguTBzTg)
> > 
> > 
> > It would be easier to debug if you could give a screenshot of your code and error
> 
> Traceback (most recent call last): File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "C:\Users\60111\anaconda3\envs\yolov8_env\Scripts\yolo.exe__main__.py", line 7, in File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\ultralytics\cfg__init__.py", line 541, in entrypoint model = YOLO(model, task=task) File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\ultralytics\engine\model.py", line 132, in **init** self._new(model, task=task, verbose=verbose) File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\ultralytics\engine\model.py", line 197, in _new self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1) # build model File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\ultralytics\nn\tasks.py", line 288, in **init** m.stride = torch.tensor([s / x.shape[-2] for x in forward(torch.zeros(1, ch, s, s))]) # forward File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\ultralytics\nn\tasks.py", line 287, in forward = lambda x: self.forward(x)[0] if isinstance(m, (Segment, Pose, OBB)) else self.forward(x) File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\ultralytics\nn\tasks.py", line 80, in forward return self.predict(x, *args, **kwargs) File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\ultralytics\nn\tasks.py", line 98, in predict return self._predict_once(x, profile, visualize, embed) File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\ultralytics\nn\tasks.py", line 119, in _predict_once x = m(x) # run File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl return forward_call(*args, **kwargs) File "C:\Users\60111\anaconda3\envs\yolov8_env\lib\site-packages\ultralytics\nn\modules\conv.py", line 333, in forward return [torch.cat](http://torch.cat/)(x, self.d) RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 32 but got size 64 for tensor number 1 in the list. ![image](https://private-user-images.githubusercontent.com/96353364/302915134-42ed5f22-9fd2-42ac-b140-bd9ec8c1e40e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTU4NjEsIm5iZiI6MTcwNzI5NTU2MSwicGF0aCI6Ii85NjM1MzM2NC8zMDI5MTUxMzQtNDJlZDVmMjItOWZkMi00MmFjLWIxNDAtYmQ5ZWM4YzFlNDBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDA4NDYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2YTMwY2M5NWU0YzZmZWI2NTgwMmRjNjg3MTdkMWIzMjMxMDdjN2M2ZGEzODk0Yzg5MDJlODgwZTUwZGE0ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YMEGLSx4i7WNZxYkAGei8fG5vZQLE_RVWu-dT6YuMhk)

btw I used command, yolo detect train data=data.yaml model=yolov8n-tinysmall.yaml epochs=2 device=0 .i saved the yaml file as yolov8-tinysmall

**Comment by icaroryan** [comment]
@zeobec any updates on your model training for small objects?

**Comment by zeobec** [comment]
@icaroryan currently im still figuring out which method to give the best mAP for small objects

**Comment by icaroryan** [comment]
@zeobec I'm also struggling a lot with that. I tried Yolo-Nas, but also didn't have much success
Please share your experiences when you manage to solve that problem. Thanks a lot

**Comment by zeobec** [comment]
@icaroryan based on my results so far, training using original architecture (without adding tiny detection head) got better mAP compared to the architecture when im adding tiny detection head. so prolly got a problem with my dataset, maybe?
