### ISSUE TITLE
save_crop saves image to ./crops/person but I want it to save to ./person How can i achieve this

### ISSUE THREAD

**Issue by axpect7** [ultralytics/ultralytics#4184]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

save_crop saves image to ./crops/person but I want it to save to ./person How can i achieve this

**Comment by glenn-jocher** [comment]
@axpect7 hi, thanks for your question.

When using the `save_crop` option, the model generates a directory named "crops" by default, where it saves cropped images. This is done to avoid clutter and maintain an organized file structure.

Currently, changing this directory name directly within the model is not built into the functionality of the YOLOv8 repository. The design choice for this is to ensure there is a standardized way for the system to save and catalogue cropped images.

However, an alternative solution could be to create a routine in your script to move the contents of the "crops/person" directory to a "person" directory after the fact.

It's important to note that if you are running the process regularly or on a schedule, you'll want to make sure to also clear out the "person" directory each time before moving the new images, to avoid mixing up different batches of results.

If you need any further clarification, don't hesitate to ask. We're here to help!
