### ISSUE TITLE
The pytorch version of yolov8 is converted to the darknet version

### ISSUE THREAD

**Issue by SuJackie** [ultralytics/ultralytics#4189]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I need darknet version of yolov8, .cfg and .weights files
Not pytorch's .yaml and .pt files

**Comment by glenn-jocher** [comment]
@SuJackie hi there,

Thanks for your question! Currently, YOLOv8 as per this repository, is designed to work with PyTorch and uses .yaml and .pt files. Unfortunately, we don't support the Darknet framework, so we don't provide the .cfg and .weights files.

The use of PyTorch allows for a more dynamic, powerful, and flexible underlying system to optimise the Ultralytics YOLO architecture which led us to focus on this design choice.

If you really want to use YOLOv8 with Darknet, you might have to consider converting the model yourself. That would require quite some work, and understanding of both PyTorch and Darknet as systems, as they use very different paradigms.

We apologize for the inconvenience, and we appreciate your understanding. Happy coding!

**Comment by Umraz-Hussain-MyWorld** [comment]
# hope this will help


1. **Clone YOLO Repository**: Clone the official YOLO repository, which includes the Darknet framework and conversion scripts:

   ```bash
   git clone https://github.com/AlexeyAB/darknet
   cd darknet
   ```

2. **Configure Darknet**: Make sure you have Darknet configured to build with CUDA and OpenCV support by editing the `Makefile` as needed. Refer to the Darknet documentation for instructions specific to your system.

3. **Convert PyTorch Model**: You can use a script like `export.py` from the YOLOv5 repository to convert the PyTorch model to the Darknet format. This script can be found in the YOLOv5 repository:

   ```bash
   git clone https://github.com/ultralytics/yolov5
   cd yolov5
   python export.py --weights /path/to/your/yolov8.pt --img-size 640 --dynamic --simplify
   ```

   Replace `/path/to/your/yolov8.pt` with the path to your YOLOv8 PyTorch model. You can also adjust the `--img-size` parameter based on your requirements.

4. **Find the Converted Weights**: The script will create a `yolov8-exported.onnx` file in the yolov5 repository directory. You can then convert this ONNX file to Darknet format using the `onnx2darknet.py` script, which is also available in the YOLOv5 repository.

   ```bash
   python export.py --weights /path/to/your/yolov8-exported.onnx
   ```

   This command will create a `yolov8.weights` file, which is the Darknet format model.

**Comment by Umraz-Hussain-MyWorld** [comment]
You can refer below lick as well

https://docs.ultralytics.com/yolov5/tutorials/model_export/#exported-model-usage-examples

**Comment by glenn-jocher** [comment]
Hi @Umraz-Hussain-MyWorld,

Thank you for your message. Currently, YOLOv8 as implemented in this Ultralytics repository is primarily designed to work with PyTorch and thus uses .yaml and .pt files. We have not officially provided a means to export these models into Darknet format (.cfg and .weights files). 

Nevertheless, if you're interested in using YOLOv8 with the Darknet framework, you would need to write a conversion script or use existing conversion tools that convert PyTorch models to Darknet. This process involves exporting the PyTorch model into another intermediate format (like ONNX) and then converting that into the Darknet format.

This task is non-trivial and needs a fair understanding of both PyTorch and Darknet. Keep in mind that certain model-based complexities could arise, given that both systems use different formats.

I hope this gives you a better sense of the situation. We appreciate your understanding. Let us know if you have any more questions or if there's anything else we can assist you with.

Happy coding!

**Comment by Roger8** [comment]
Hi @Umraz-Hussain-MyWorld , Thank you for your work .  
I cannot find onnx2darknet.py script  in the YOLOv5 repository  . Then i searched github , found a repo https://github.com/YYEON/onnx2darknet/ , there is a script called onnx2darknet.py, but it cannot work on my trained yolov8.onnx . I would be appreciate if some help given.

**Comment by Etty-Cohen** [comment]
> # hope this will help
> 1. **Clone YOLO Repository**: Clone the official YOLO repository, which includes the Darknet framework and conversion scripts:
>    ```shell
>    git clone https://github.com/AlexeyAB/darknet
>    cd darknet
>    ```
> 2. **Configure Darknet**: Make sure you have Darknet configured to build with CUDA and OpenCV support by editing the `Makefile` as needed. Refer to the Darknet documentation for instructions specific to your system.
> 3. **Convert PyTorch Model**: You can use a script like `export.py` from the YOLOv5 repository to convert the PyTorch model to the Darknet format. This script can be found in the YOLOv5 repository:
>    ```shell
>    git clone https://github.com/ultralytics/yolov5
>    cd yolov5
>    python export.py --weights /path/to/your/yolov8.pt --img-size 640 --dynamic --simplify
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Replace `/path/to/your/yolov8.pt` with the path to your YOLOv8 PyTorch model. You can also adjust the `--img-size` parameter based on your requirements.
> 4. **Find the Converted Weights**: The script will create a `yolov8-exported.onnx` file in the yolov5 repository directory. You can then convert this ONNX file to Darknet format using the `onnx2darknet.py` script, which is also available in the YOLOv5 repository.
>    ```shell
>    python export.py --weights /path/to/your/yolov8-exported.onnx
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    This command will create a `yolov8.weights` file, which is the Darknet format model.

and from where you have cfg file?
