### ISSUE TITLE
tflite output_metadata error?

### ISSUE THREAD

**Issue by NakanoSanku** [ultralytics/ultralytics#4195]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i try export model to tflite，but the output_metadata is not the same as the official model from hub
official
```
   "output_tensor_metadata": [
        {
          "name": "location",
          "description": "The locations of the detected boxes.",
          "content": {
            "content_properties_type": "BoundingBoxProperties",
            "content_properties": {
              "index": [
                1,
                0,
                3,
                2
              ],
              "type": "BOUNDARIES"
            },
            "range": {
              "min": 2,
              "max": 2
            }
          }
        },
        {
          "name": "category",
          "description": "The categories of the detected boxes.",
          "content": {
            "content_properties_type": "FeatureProperties",
            "content_properties": {
            },
            "range": {
              "min": 2,
              "max": 2
            }
          },
          "associated_files": [
            {
              "name": "labelmap.txt",
              "description": "Label of objects that this model can recognize.",
              "type": "TENSOR_VALUE_LABELS"
            }
          ]
        },
        {
          "name": "score",
          "description": "The scores of the detected boxes.",
          "content": {
            "content_properties_type": "FeatureProperties",
            "content_properties": {
            },
            "range": {
              "min": 2,
              "max": 2
            }
          }
        },
        {
          "name": "number of detections",
          "description": "The number of the detected boxes.",
          "content": {
            "content_properties_type": "FeatureProperties",
            "content_properties": {
            }
          }
        }
      ],
```
the model convert from yolov8
```
"output_tensor_metadata": [
        {
          "name": "location",
          "description": "The locations of the detected boxes.",
          "content": {
            "content_properties_type": "BoundingBoxProperties",
            "content_properties": {
              "index": [
                1,
                0,
                3,
                2
              ],
              "type": "BOUNDARIES"
            },
            "range": {
              "min": 2,
              "max": 2
            }
          },
          "stats": {
          }
        }
      ],
```

need 4 but only 1

**Comment by glenn-jocher** [comment]
@NakanoSanku it seems like you're running into an issue when trying to export a YOLOv8 model to the TFLite format. The output metadata of your converted model doesn't match with the official one you're aiming for, which is causing the discrepancy in the number of output tensor metadata. 

The missing tensor metadata sections within your model ('category', 'score', 'number of detections') determine the type of the output and are essential for interpreting the outputs correctly. 

Without diving too deep into the code, the issue might be linked to how the conversion process is implemented. There might be factors that are interrupting the creation of the complete metadata for the output tensors. 

One recommendation would be to recheck your conversion code once more to ensure all necessary steps are being executed correctly. If errors persist, it could require a more in-depth investigation into the exact cause.

Regardless, make sure you're using the latest version of the repository and have met all the necessary requirements before the conversion process. Let us know how it goes, happy coding!
