### ISSUE TITLE
How do I filter inference results?

### ISSUE THREAD

**Issue by Won-JoonChoi** [ultralytics/ultralytics#4204]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm doing a fish detection task by YOLOv8 detection model. I want to detect only objects over 400px in width because inferencing too small fishes decreases the performance based on my custom data. Is there any ways to filter the inference results like this? Any help is appreciated!

**Comment by Kayzwer** [comment]
```
from ultralytics import YOLO
from ultralytics.engine.results import Results


if __name__ == "__main__":
    model = YOLO("yolov8n.pt")
    output: Results = model.predict("path/to/img", save=False)[0]
    bboxes = []
    for bbox in output.boxes.xywh:
        if bbox[2] > 400:
            bboxes.append(bbox.cpu().numpy())
    print(bboxes)
```
