### ISSUE TITLE
How to freeze some layers of the network such as the backbone network for training?

### ISSUE THREAD

**Issue by HtwoOtwo** [ultralytics/ultralytics#4205]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi author, I would like to know how to freeze some layers of the network, I have tried like this:
for i in range(10):
    for param in model.model._modules['model'][i].parameters():
        param.requires_grad = False
model.train(data='MyDataset-seg.yaml', epochs=500, imgsz=640, device='cuda:1', batch = 64)

but it seems doesn't work. Because during training, all "requires_grad" will be set to True. I want to know is there any other way to freeze parameters.

**Comment by Kayzwer** [comment]
@HtwoOtwo up until now there is not official implementation of freezing layers, but you can refer to this https://github.com/ultralytics/ultralytics/issues/793

**Comment by HtwoOtwo** [comment]
> @HtwoOtwo up until now there is no official implementation of freezing layers, but you can refer to this #793

Same as I thought, thanks for the suggestion!
