### ISSUE TITLE
tutorial documentation Removed visual introduction

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#4206]
https://docs.ultralytics.com/modes/predict/

In the tutorial documentation

Removed visual introduction

visualization :
Results [0]. plot()
https://docs.ultralytics.com/reference/engine/results/?h=plot#ultralytics.engine.results.Results.plot

Suggest adding a description of the visualization module in the document

**Comment by Kayzwer** [comment]
@monkeycc try to create a pull request for this.

**Comment by glenn-jocher** [comment]
@monkeycc ah I've rewritten that docs page and created a new Plotting Results section that's expanded with more detail:

https://docs.ultralytics.com/modes/predict/#plotting-results

<img width="1296" alt="Screenshot 2023-08-07 at 11 44 13" src="https://github.com/ultralytics/ultralytics/assets/26833433/36072d4e-e6d7-489f-ba14-7c135ba73dc6">

**Comment by monkeycc** [comment]
```python
from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO('yolov8n.pt')

# Run inference on 'bus.jpg'
results = model('bus.jpg')  # results list

newImage = results[0].plot(labels=True,boxes=True,masks=True,kpt_line=True)
```

How about adding this piece of code again ?

Is it clearer ?

**Comment by glenn-jocher** [comment]
@monkeycc thanks for reaching out. Your question seems to revolve around the visualization feature of YOLOv8.

The provided code is a good starting point for beginners but does come with the assumption that the user has a pre-trained YOLOv8 model ready to use.

In regards to how to add it again, you would follow a process along these lines:
- Import the YOLO model from Ultralytics.
- Load your pre-trained YOLOv8 model.
- Run the inference on your chosen image file. This would return a list of results.
- Finally, you would use the results and the plot function to generate an image of your inference result, with options to include labels, boxes, masks and keypoint lines as visual aids.

Trust this helps clarify your question. If you have further inquiries, don't hesitate to ask. We are all here to learn and grow together.
