### ISSUE TITLE
CUDA out of memory when predicting with CPU

### ISSUE THREAD

**Issue by hoangphucITJP** [ultralytics/ultralytics#4207]
I'm using the detection model with `device='cpu'` yet the below code still gets executed which consumes my GPU:
https://github.com/ultralytics/ultralytics/blob/9a2c0691e3bcb0ae20ec482d25b857ab4c21bfd2/ultralytics/utils/ops.py#L54

Please help me take a look.

**Comment by glenn-jocher** [comment]
@hoangphucITJP thank you for bringing up this issue. It appears that even though you've set `device='cpu'`, CUDA is somehow being invoked and consequently leading to an out-of-memory error. 

The line of code you mentioned (at utils/ops.py on line 54) checks if CUDA is available before attempting to use it. If you've set the device to CPU, then in theory, this code should not execute.

A potential reason could be a setting elsewhere in the code that overrides the 'cpu' with 'cuda' if it's available. I would suggest taking a closer look at your codebase to ensure that the device is not erroneously set to 'cuda'. If that doesn’t seem to be the case, there could be a bug in our code that we need to look into. 

We greatly appreciate your time and patience in this matter, and will do our best to understand the cause and find a suitable solution. Thanks again, and feel free to provide any extra details that could help us troubleshoot this issue more effectively.
