### ISSUE TITLE
Save Crops without showing the boundinboxes

### ISSUE THREAD

**Issue by hmiche** [ultralytics/ultralytics#421]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hello .
is there any ways to do the save_crop  argument without having crops with bounding box . i want only tha cropped area .

![ee05906a-4211-4ba3-af69-40913427b645](https://user-images.githubusercontent.com/63804608/212712597-5e2cb3d1-cb86-41d3-b5ef-a78199855117.jpg)

exemple of the essue .
thanks in advance .

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@hmiche hi, this is a bug which had been fixed long time ago. Please upgrade the package to the latest version. :)
