### ISSUE TITLE
Placing overlay over YOLOv8 segmented area.

### ISSUE THREAD

**Issue by Manueljohnson063** [ultralytics/ultralytics#4210]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I have done a segmentation using Yolov8 which is amazing.But my end goal is to place an   external image over the segmented part.Can you please help me how i proceed further?

### Use case

Placing an external mask over the segmented part

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Manueljohnson063 hello,

Thank you for showing interest in the Ultralytics YOLOv8 model.

With respect to placing an overlay over a segmented part: after segmentation using YOLOv8, you will have a mask that delineates the area of interest. You can use this mask to overlay your external image.

The process will typically involve these steps:

1. Use the segmentation mask to create an area of interest in the original image.
2. Resize your external image to match the dimensions of the segmented area.
3. Overlay the resized external image onto the original image in the segmented area.

Please remember you would do these manipulations after you have performed the segmentation using YOLOv8 and obtained the segmentation mask. Most of these operations can be achieved using popular image processing libraries in Python like PIL or OpenCV which provide functionality for resizing images and manipulating image arrays.

While our team is always ready to assist, this task is slightly beyond the scope of model training and inference. However, there are many resources available online and in Python image processing library documentation that can guide you step-by-step to achieve this.

I hope this will provide a good starting point for your work. Good luck!

**Comment by Manueljohnson063** [comment]
Thanks for the assistance One more question.
Is it possible to get the boundary instead of mask from this code

import cv2
from ultralytics import YOLO
#from yolo_segmentation import YOLOSegmentation

model=YOLO('./yolov8n-seg.pt')
#model = YOLOSegmentation('yolov8n-seg.pt')
video_path="car.mp4"
cap=cv2.VideoCapture(video_path)

while cap.isOpened():
    sucess, frame=cap.read()
    if sucess:
        results = model(frame)
        annotated_frame = results[0].plot()
        cv2.imshow("Yolov8Inference",annotated_frame)

        if  cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

**Comment by glenn-jocher** [comment]
@Manueljohnson063,

Great to see you actively using our YOLOv8 model! As for obtaining borders instead of masks from the object detection, you might want to use the function that draws bounding boxes around detected objects rather than creating a mask.

The code you've posted is running object detection and then using a function to plot the detected objects directly onto the frame. This doesn't provide a boundary or mask but directly annotates the detected objects onto the frame.

If you want a boundary (as in a border of the object), look at the `results` object which you are getting from `model(frame)`. This object contains various properties including the bounding box coordinates of detected objects for each frame.

For each detected object, the `xyxy` property will give you the coordinates (x1, y1, x2, y2) of the bounding box. You can use these coordinates to draw a rectangular boundary around the object using relevant functions in OpenCV.

I hope this helps! If you have further questions, feel free to ask.

**Comment by plutus123** [comment]
> Thanks for the assistance One more question. Is it possible to get the boundary instead of mask from this code
> 
> import cv2 from ultralytics import YOLO #from yolo_segmentation import YOLOSegmentation
> 
> model=YOLO('./yolov8n-seg.pt') #model = YOLOSegmentation('yolov8n-seg.pt') video_path="car.mp4" cap=cv2.VideoCapture(video_path)
> 
> while cap.isOpened(): sucess, frame=cap.read() if sucess: results = model(frame) annotated_frame = results[0].plot() cv2.imshow("Yolov8Inference",annotated_frame)
> 
> ```
>     if  cv2.waitKey(1) & 0xFF == ord("q"):
>         break
> else:
>     break
> ```
> 
> cap.release() cv2.destroyAllWindows()

Hello if you have found the solution for this problem then please can you share it with me

**Comment by pderrenger** [comment]
Hi @plutus123,

To draw boundaries instead of masks, you can use the bounding box coordinates from the `results` object. Here's how you can modify your code:

```python
import cv2
from ultralytics import YOLO

model = YOLO('./yolov8n-seg.pt')
video_path = "car.mp4"
cap = cv2.VideoCapture(video_path)

while cap.isOpened():
    success, frame = cap.read()
    if success:
        results = model(frame)
        for box in results[0].boxes.xyxy:
            x1, y1, x2, y2 = map(int, box)
            cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.imshow("Yolov8Inference", frame)

        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()
```

This code will draw green rectangles around detected objects. Let me know if you need further assistance!

**Comment by plutus123** [comment]
> Hi @plutus123,
> 
> To draw boundaries instead of masks, you can use the bounding box coordinates from the `results` object. Here's how you can modify your code:
> 
> ```python
> import cv2
> from ultralytics import YOLO
> 
> model = YOLO('./yolov8n-seg.pt')
> video_path = "car.mp4"
> cap = cv2.VideoCapture(video_path)
> 
> while cap.isOpened():
>     success, frame = cap.read()
>     if success:
>         results = model(frame)
>         for box in results[0].boxes.xyxy:
>             x1, y1, x2, y2 = map(int, box)
>             cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
>         cv2.imshow("Yolov8Inference", frame)
> 
>         if cv2.waitKey(1) & 0xFF == ord("q"):
>             break
>     else:
>         break
> 
> cap.release()
> cv2.destroyAllWindows()
> ```
> 
> This code will draw green rectangles around detected objects. Let me know if you need further assistance!

Hello pderrenger, thanks a lot for you help but I want a boundry on the segmented object in order to calculate the are of that segmented object. I want my final output to be like the image that I am attaching :

<img width="563" alt="Screenshot 2024-07-13 at 21 00 44" src="https://github.com/user-attachments/assets/520ee22a-8d31-4338-9cc5-774f9edc5a49">

**Comment by pderrenger** [comment]
Hi @plutus123,

To draw boundaries around the segmented objects and calculate their areas, you can use the contours from the segmentation masks. Here's how you can modify your code to achieve this:

```python
from ultralytics import YOLO
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

Pixel_to_cm = 25  # xx pixels are 1cm (assumption, needs to be calibrated in real time) 
Pixel_to_square_cm = 25 * 25

# Load a pretrained segmentation model
model = YOLO('runs/segment/train6/weights/best.pt')

# Run inference on an image
img = cv2.imread("/content/drive/MyDrive/gigazit/images.jpeg")
H, W, _ = img.shape
results = model(img)

for result in results:
    for j, mask in enumerate(result.masks.data):
        mask = mask.numpy()
        mask = cv2.resize(mask, (W, H))
        area = np.sum(mask)
        total_area_cm = round(area / Pixel_to_square_cm, 2)
        
        # Find contours
        contours, _ = cv2.findContours(mask.astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        
        # Draw contours
        cv2.drawContours(img, contours, -1, (0, 255, 0), 2)
        
        # Put the text with the area
        for contour in contours:
            x, y, w, h = cv2.boundingRect(contour)
            cv2.putText(img, f"A: {total_area_cm}cm^2", (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

# Save and show the image
cv2.imwrite('output_with_areas.png', img)
cv2_imshow(img)  # Use cv2_imshow instead of cv2.imshow
```

This code will draw the contours around the segmented objects and display the calculated area. Let me know if you need further assistance!

**Comment by plutus123** [comment]
Thanks a lot @pderrenger

**Comment by pderrenger** [comment]
You're welcome, @plutus123! If you have any more questions or run into any issues, feel free to ask. Happy coding!

**Comment by plutus123** [comment]
> You're welcome, @plutus123! If you have any more questions or run into any issues, feel free to ask. Happy coding!

Sure @pderrenger once again thanks a lot for your help :). Currently I am working on calculating absolute depth. For segmentation I am using yolov8-seg and for calculating depth mask I am using MIDAS. I am encountering an issue in that, I would be really thankful to you if you can also take a look into that.

```
import torch
model_type = "DPT_Large"     # MiDaS v3 - Large     (highest accuracy, slowest inference speed)
#model_type = "DPT_Hybrid"   # MiDaS v3 - Hybrid    (medium accuracy, medium inference speed)
#model_type = "MiDaS_small"  # MiDaS v2.1 - Small   (lowest accuracy, highest inference speed)

midas = torch.hub.load("intel-isl/MiDaS", model_type)
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
midas.to(device)
midas.eval()

midas_transforms = torch.hub.load("intel-isl/MiDaS", "transforms")

if model_type == "DPT_Large" or model_type == "DPT_Hybrid":
    transform = midas_transforms.dpt_transform
else:
    transform = midas_transforms.small_transform

```

```
from ultralytics import YOLO
import cv2
import torch

yolo_model = YOLO('runs/segment/train3/weights/best.pt')

image = cv2.imread('test/162431.jpg')

yolo_results = yolo_model(image)

image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

input_batch = transform(image_rgb).to(device)
with torch.no_grad():
    prediction = midas(input_batch)

    prediction = torch.nn.functional.interpolate(
        prediction.unsqueeze(1),
        size=image_rgb.shape[:2],
        mode="bicubic",
        align_corners=False,
    ).squeeze()

output = prediction.cpu().numpy()

for result in yolo_results:
    for box in result.boxes:
        x1, y1, x2, y2 = map(int, box.xyxy.cpu().numpy())
        depth_value = output[(y2 + y1) // 2, (x2 + x1) // 2]
        print(f"Detected object at depth: {depth_value}")

print(f"Speed: {yolo_results[0].speed}")

```
This is the error that I am encountering
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[78], line 34
     32 for result in yolo_results:
     33     for box in result.boxes:
---> 34         x1, y1, x2, y2 = map(int, box.xyxy.cpu().numpy())
     35         depth_value = output[(y2 + y1) // 2, (x2 + x1) // 2]
     36         print(f"Detected object at depth: {depth_value}")

TypeError: only length-1 arrays can be converted to Python scalars
```
Thanks a lot in advance!!

**Comment by pderrenger** [comment]
You're welcome, @plutus123! 

1. For extracting points/coordinates instead of lines, you can use the contour points directly from the segmentation mask. This will give you the exact coordinates of the boundary points.

2. For the depth calculation issue, the error suggests that `box.xyxy` might be returning an array with more than one element. Ensure you're accessing the bounding box coordinates correctly. If you need further assistance, please check if the issue persists with the latest versions of the packages.

Happy to help!

**Comment by plutus123** [comment]
> You're welcome, @plutus123!
> 
> 1. For extracting points/coordinates instead of lines, you can use the contour points directly from the segmentation mask. This will give you the exact coordinates of the boundary points.
> 2. For the depth calculation issue, the error suggests that `box.xyxy` might be returning an array with more than one element. Ensure you're accessing the bounding box coordinates correctly. If you need further assistance, please check if the issue persists with the latest versions of the packages.
> 
> Happy to help!

@pderrenger Thanks a lot!

**Comment by pderrenger** [comment]
For extracting boundary points, you can use the contour points from the segmentation mask to get the exact coordinates. Regarding the depth calculation issue, it seems `box.xyxy` might be returning an array with more than one element. Ensure you're accessing the bounding box coordinates correctly. Please verify if the issue persists with the latest versions of the packages. If you need further assistance, feel free to ask!

**Comment by pderrenger** [comment]
Great to hear that you've resolved the issue! If you have any more questions or need further assistance, feel free to reach out. Happy coding!

**Comment by akang-ai** [comment]
@plutus123 
Hello, from the above conversation, I can see that you are using midas and yolov8-seg models, and I am also very interested in this. I want to fuse the instance segmentation image output by yolov8-seg with the depth image output by midas. At present, I have trained the weight parameters of yol ov8-seg, but I don’t know how to fuse the two networks to achieve the output image containing both depth information and instance segmentation information (like the picture below). From the above conversation, I guess you are trying to combine this network. If you can provide two help, I will be very grateful.
![image](https://github.com/user-attachments/assets/cbe4073c-6f82-4891-86e2-ab4ea810eb6e)

**Comment by akang-ai** [comment]
@pderrenger Why when I use the above code to predict pictures and use my own trained model for segmentation, there is drift on small objects?
from ultralytics import YOLO
import cv2
import numpy as np

Pixel_to_cm = 25  # xx pixels are 1cm (assumption, needs to be calibrated in real time)
Pixel_to_square_cm = 25 * 25

# Load a pretrained segmentation model
model = YOLO('runs/segment/train/weights/best.pt')

# Run inference on an image
img = cv2.imread("street.jpg")
H, W, _ = img.shape
results = model(img)

for result in results:
    for j, mask in enumerate(result.masks.data):
        mask = mask.cpu().numpy()  # 将mask从GPU移动到CPU，然后转换为NumPy数组
        mask = cv2.resize(mask, (W, H))
        area = np.sum(mask)
        total_area_cm = round(area / Pixel_to_square_cm, 2)

        # Find contours
        contours, _ = cv2.findContours(mask.astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        # Draw contours
        cv2.drawContours(img, contours, -1, (0, 255, 0), 2)

        # Put the text with the area
        for contour in contours:
            x, y, w, h = cv2.boundingRect(contour)
            cv2.putText(img, f"A: {total_area_cm}cm^2", (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

# Save and show the image
cv2.imwrite('output_with_street.png', img)
cv2.imshow('street.jpg',img)  # Use cv2_imshow instead of cv2.imshow
cv2.waitKey(0)  # Wait for a key press to close the window
cv2.destroyAllWindows()
![image](https://github.com/user-attachments/assets/0e285ef5-d93c-4595-adc2-63c9755793be)

**Comment by akang-ai** [comment]
@pderrenger 
![image](https://github.com/user-attachments/assets/e7a7cce0-2a26-45a6-b16f-f3b947306596)
This is the result of the original model I trained myself.

**Comment by plutus123** [comment]
@akang-ai I think you are trying to calculate surface normals from depth image.
If what I am thinking is correct then you must use neighbouring pixel cross product.
For that you can refer to this article
https://stackoverflow.com/questions/34644101/calculate-surface-normals-from-depth-image-using-neighboring-pixels-cross-produc
Hope this helps you :)
