### ISSUE TITLE
GPU usuage

### ISSUE THREAD

**Issue by ahthserhsluk** [ultralytics/ultralytics#422]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Will the model use GPU automatically or do we need to specify something?

I tried running data on a custom dataset and it showed that one epoch will take 14 hours the

**Comment by AyushExel** [comment]
It should use GPU by default if its available. Can you check if `torch.cuda.is_available()` returns true?
Also, the progress logs should show the GPU usage

**Comment by ahthserhsluk** [comment]
thanks man! it's working like a charm now! 

search how to make torch.cuda.is_available() true, there were some configuration problems. 
now one epoch is taking 4.5 min on average.
