### ISSUE TITLE
Segmentation mask without bounding box and labeling using Ultralytics YoLov8 segmentation model

### ISSUE THREAD

**Issue by deepak36ccny** [ultralytics/ultralytics#4224]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I don't feel any control over the segmentation result I get using YOLOv8-segmentaiton model. How can I get rid of the bounding box and the labeling, and just obtain the segmentation mask from this model? Thank you.

**Comment by glenn-jocher** [comment]
@deepak36ccny hello,

Thank you for reaching out with your question. The segmentation feature of YOLOv8 provides the output as a combination of segmentation masks, bounding boxes, and labels. However, if you're specifically interested in the segmentation mask without bounding boxes and labels, you can adjust the post-processing step of the model's output.

When the model processes an image, it provides a segmentation mask as one of its outputs. You can directly access this part of the output without drawing the bounding boxes and labels. Please remember, this might require you to dive into the implementation code and carefully manipulate it to suit your needs.

To elaborate a bit, the segmentation masks are typically saved in a particular portion of the model's output tensor. You might need to modify the code that interprets the model's output to only retain the segmentation mask and discard the bounding boxes and class labels.

Please exercise caution while making these changes to ensure you don't inadvertently affect the operation of other parts of the code. Also, consider creating a backup version of the original code before making these changes for easy reference in case of any issue.

Hope that helps! Let us know if you need further assistance.

Best regards,
Glenn
