### ISSUE TITLE
About the engine/model.py

### ISSUE THREAD

**Issue by wwt123-star** [ultralytics/ultralytics#4228]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![1 (1)](https://github.com/ultralytics/ultralytics/assets/67778649/8db46694-fe14-49b6-8238-e59de7face7a)

I had used the model.load.train() to train, but i found it load twice from the run window in PyCharm, as seen from the image. I wander which is the right for loading model.

**Comment by TaoweiZhang** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> ### Question
> ![1 (1)](https://user-images.githubusercontent.com/67778649/259060041-8db46694-fe14-49b6-8238-e59de7face7a.jpg)
> 
> I had used the model.load.train() to train, but i found it load twice from the run window in PyCharm, as seen from the image. I wander which is the right for loading model.
> 
> ### Additional
> _No response_

The last loading is right, you can look at line 22, nc=8.
