### ISSUE TITLE
Colab Crashing with model(show = True) 

### ISSUE THREAD

**Issue by amrrs** [ultralytics/ultralytics#423]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Google Colab session is crashing (restarting) whenever the inference is made with 

```
result = model("https://ultralytics.com/images/zidane.jpg",show = True)  
```

Without show=True nothing is saved in the result object. 

CLI is working fine. The problem seems to be with Python API.

### Environment

Ultralytics YOLOv8.0.6 🚀 Python-3.8.16 torch-1.13.0+cu116 CUDA:0 (Tesla T4, 15110MiB)

### Minimal Reproducible Example

# Load a model
model = YOLO("yolov8n-seg.pt") #YOLO("yolov8n.pt")  # load a pretrained model
result = model("https://ultralytics.com/images/zidane.jpg",show = True)  # predict on an image

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by amrrs** [comment]
The same problem exist in all the previous versions of 8.0.x

**Comment by amrrs** [comment]
Also nothing is stored in the result object

**Comment by AyushExel** [comment]
@amrrs colab environment doesn't support showing images in opencv. To get the results you can use `return_outputs=True` but that's a temporary solution. We're working on a better and faster solution here and it should be available soon( Tomorrow ) - https://github.com/ultralytics/ultralytics/pull/314

**Comment by amrrs** [comment]
Thanks @glenn-jocher +++

**Comment by AyushExel** [comment]
Now you can install/upgrade from pypi

**Comment by amrrs** [comment]
Thanks, `save=True` works but I need to figure out how to get the saving file path from the `results` object

![image](https://user-images.githubusercontent.com/5347322/212917744-363cf66d-1644-4579-9e06-c8e8dab9089b.png)
