### ISSUE TITLE
Yaml file running error with colab

### ISSUE THREAD

**Issue by maimunul** [ultralytics/ultralytics#4231]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

![Screenshot 2023-08-08 181037](https://github.com/ultralytics/ultralytics/assets/88198398/8806547c-a445-4c2a-94bf-7f637bac8a88)

### Environment

YOLO: yolov8s.pt
Environmnet: Google Colab

### Minimal Reproducible Example

!yolo task=detect mode=train model=yolov8s.pt data=/content/drive/MyDrive/Colab Notebooks/Footaball_Data_YOLO/dataset.yaml epochs=10 imgsz=640 batch=8 project=/content/drive/MyDrive/Colab Notebooks/Footaball_Data_YOLO/training_results name=football

yaml text: 

train: /content/yolo_data/images/train  
val: /content/yolo_data/images/val
nc: 2  
names: ['player','football']

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Kayzwer** [comment]
@maimunul 
`!yolo task=detect mode=train model=yolov8s.pt data="/content/drive/MyDrive/Colab Notebooks/Footaball_Data_YOLO/dataset.yaml" epochs=10 imgsz=640 batch=8 project="/content/drive/MyDrive/Colab Notebooks/Footaball_Data_YOLO/training_results" name=football`
try this command, your directory name contains space

**Comment by glenn-jocher** [comment]
I'm glad to hear your issue has been resolved, @Kayzwer! It's always important to be aware of potential format issues like spacing in paths when working with directory structures. Don't hesitate to reach out if you encounter any other challenges or have further questions. The Ultralytics team and YOLOv8 community is here to help. Keep up the great work!
