### ISSUE TITLE
Display predictions based on target size.

### ISSUE THREAD

**Issue by SimonCL17** [ultralytics/ultralytics#4232]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I have a question. Is it possible to only show detections based on a defined target size? For example, I only want to show detected cars if the detected target has a minimum size of 100x100 pixels. Is this possible?

Thanks,

Simon

**Comment by glenn-jocher** [comment]
@SimonCL17 hello Simon,

It's certainly possible to filter detections based on target size with YOLOv8. The detections generated by the model include the bounding box dimensions, so you can use these to filter out detections below your specified threshold.

Here's a high-level guide:

1. Process your image or video with the YOLOv8 model to get the output detections.
2. Each detection will include details such as the object class, the bounding box coordinates, and the confidence score.
3. From the bounding box coordinates, you can calculate the size of the detected object.
4. You can then set a size threshold and only keep those detections where the bounding box size is above your specified minimum (in your case, 100x100 pixels).

Just be aware that the size of detected objects can be affected by their distance from the camera, so ensure your image data is consistent for best results.

I hope this helps!

Best,
Glenn
