### ISSUE TITLE
Imagenet Yolov8 Classifier for commercial purpose

### ISSUE THREAD

**Issue by giuseppebif3** [ultralytics/ultralytics#4233]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I want to understand better if the models to perform classification tasks are pretrained on Imagenet. I wanna know also if they can be used for commercial purpose, because I read that Imagenet dataset can be used only for research purpose. 

Thanks a lot!

**Comment by glenn-jocher** [comment]
@giuseppebif3 hello,

Thank you for reaching out. Yes, the models used in the YOLOv8 implementation can be pre-trained on ImageNet. The use of ImageNet in this context is simply to provide initial weights that are conducive to generalized learning, thereby improving the model's subsequent performance when training on your specific dataset.

Regarding your second question, the YOLOv8 models themselves can indeed be used for commercial purposes. However, you are correct to note that the ImageNet dataset itself is licensed for non-commercial research purpose only. Still, using weights derived from ImageNet pre-training does not inherit the dataset's license restrictions. So, while you cannot use the ImageNet dataset directly in a commercial application, there is no such restriction on using models pre-trained on it.

Should you need more flexibility, it's worth noting that Ultralytics also provides an Enterprise license for YOLOv8 which allows for commercial product development without the open-source requirements of the repository's AGPL-3.0 license. The main goal of the Enterprise license is to support embedding Ultralytics software and AI models in commercial products and applications.

Please review the licenses of any datasets you use to pre-train your model to ensure you are in compliance. Thank you for your interest in our work, and we look forward to seeing what you accomplish with YOLOv8!

**Comment by sniper0110** [comment]
Hi,
I work with a client company who is looking to buy your enterprise license. They have reached out to you through your website form but haven't got any response from you yet. Can you please look into that?
Thanks!

**Comment by glenn-jocher** [comment]
@sniper0110 hi there,

Thank you for bringing this to our attention, and I apologize for any delay in response your client may have experienced. Our team works diligently to respond to all inquiries as quickly and efficiently as possible.

To assist you further, please ensure that the contact was directed correctly through our form on the website and that the provided contact details are accurate. If the inquiry was correctly sent, rest assured that it is in our queue and will be addressed in the order it was received.

It's important to note that the response time may vary depending on the volume of requests, but we're committed to providing timely and personalized assistance. I encourage you or your client to reach out again if necessary.

Please convey to your client that we greatly appreciate their interest in our enterprise solutions and that we are looking forward to discussing their needs and how the YOLOv8 enterprise license can accommodate their commercial project.

If there's anything else I can assist you with here, please don't hesitate to let me know!

**Comment by karthikbalu** [comment]
if I just use the trained model in my commerical application with my own inference code, do I still need to buy enterprise license?

**Comment by glenn-jocher** [comment]
@karthikbalu yes, if you plan to use our trained YOLOv8 model in a commercial application and require an enterprise-level agreement, purchasing an enterprise license is necessary even if you use your own inference code. This license will grant you the permission needed for commercial product development without the open-source restrictions of AGPL-3.0. 📜✅

**Comment by tinomin** [comment]
if I just use the model (not the pretrained model) in my commerical application with my own inference code, do I still need to buy enterprise license?

**Comment by glenn-jocher** [comment]
@tinomin yes, for commercial use of the YOLOv8 model with your own inference code, an enterprise license is recommended to comply with licensing requirements and to avoid the restrictions of the AGPL-3.0 license. 🛒📃

**Comment by karthikbalu** [comment]
I would rather use yolov7 and even newly launched yolov9 :)

**Comment by houdridi** [comment]
@karthikbalu ,  yolov7 ans yolov9 are free?

**Comment by thecoder00007** [comment]
Yolov7 and 9 are under the same license, I think

**Comment by yinglingyang** [comment]
> hi @glenn-jocher I have some questions because the conditions are not very clear:
> 
> 1. If I use the code to train my own model, do I need an enterprise License?
> 2. What do you mean with sharing the code, here the code is almost the same to train and infer for all the projects. So what we need exactly to be under AGPL-3.0 license?
> 3. If we use Yolo only for internal solution (to check parking, camera, ...) , not under application to be sell, is that considering under commercial?
> 4. How much it cost the license, in the website we saw 'it depends ...', can we have a range as example?
> 
> Thank you

Don't use any copyleft models (such as yolo v8) for commercial purpose, that is very dangerous. You have to open-source anything in your work related to yolo v8, for example, the model trained by your or your client's private data has to be open sourced.

**Comment by glenn-jocher** [comment]
@yinglingyang hi there! Thanks for reaching out with your questions. Let's clarify a bit:

1. **Enterprise License for Training**: If you're training your own model with our code for commercial use, yes, an Enterprise License is recommended to comply with licensing requirements.
2. **Sharing the Code**: Under AGPL-3.0, if you modify or use our code in your project, and if your project is accessible to others (even as a service), you're required to share your project's source code under the same license.
3. **Internal Use**: Using YOLO for internal solutions is still considered commercial use if it supports business operations. An Enterprise License would be necessary.
4. **License Cost**: Pricing varies based on use case, scale, and support needs. It's best to contact us directly for a quote tailored to your specific requirements.

Hope this helps! Feel free to reach out for more detailed discussions or any further assistance. 😊
