### ISSUE TITLE
Error with the save_hybrid flag while running validation

### ISSUE THREAD

**Issue by salkhokhar** [ultralytics/ultralytics#4240]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Validation

### Bug

When I tried running the validation with save_hybrid flag, an error related to mismatching tensor sizes popped up. When I removed the flag, it worked like a charm.
![Capture](https://github.com/ultralytics/ultralytics/assets/61519106/a4601c61-45e0-42bf-a874-1b97de8039d5)

### Minimal Reproducible Example

yolo detect val model=weights\best.pt data=data.yaml batch=2 iou=0.7 save_hybrid=true

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@salkhokhar thank you for raising this issue and sharing the details. 

The `save_hybrid` flag in YOLOv8's validation mode is used for hybrid bounding box creation, which combines both the detected bounding boxes and the ground truth boxes. The error indicating mismatched tensor sizes generally arises when the dimensions of the ground truth and detected boxes don't align. 

Although you've mentioned that removing the `save_hybrid` flag solved the problem, the underlying issue may be related to the differences in sizes or format of boxes in your specific dataset and what the `save_hybrid` functionality expects. 

Also, please ensure that you've applied any necessary transformation to your dataset that matches with the required input format for the model. The `save_hybrid` option expects both the model predictions and the ground truth in a particular format.

In the meantime, I'll look into the problem to see if there's an exception case we missed that might be causing this issue. We appreciate your patience as we work on a resolution. Also, any additional information about the error or the data you're working with could potentially speed up the diagnosis process. 

Again, thank you for your contribution to improving YOLOv8!

**Comment by Laughing-q** [comment]
@salkhokhar Nice catch! I've fixed it here #4245. Thanks for the reporting!

**Comment by salkhokhar** [comment]
> @salkhokhar Nice catch! I've fixed it here #4245. Thanks for the reporting!

Thanks. It worked like a charm!!

**Comment by glenn-jocher** [comment]
Great to hear that the fix worked for you, @salkhokhar! Thank you for bringing this issue to our attention. Your contribution helps improve YOLOv8 for all users. Don't hesitate to raise another issue if you come across any other problems or have other suggestions. Happy coding!

**Comment by glenn-jocher** [comment]
@salkhokhar great news 😃! Your original issue may now be resolved ✅ in PR #4245. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by Petros626** [comment]
> [@salkhokhar](https://github.com/salkhokhar) Nice catch! I've fixed it here [#4245](https://github.com/ultralytics/ultralytics/pull/4245). Thanks for the reporting!

I got ultralytics version 8.3.55 and this PR wasn't in my codebase:
```python
def __init__(self, dataloader=None, save_dir=None, pbar=None, args=None, _callbacks=None):
        """Initialize detection model with necessary variables and settings."""
        super().__init__(dataloader, save_dir, pbar, args, _callbacks)
        self.nt_per_class = None
        self.nt_per_image = None
        self.is_coco = False
        self.is_lvis = False
        self.class_map = None
        self.args.task = "detect"
        self.metrics = DetMetrics(save_dir=self.save_dir, on_plot=self.on_plot)
        self.iouv = torch.linspace(0.5, 0.95, 10)  # IoU vector for mAP@0.5:0.95, 0.05 steps
        self.niou = self.iouv.numel()
        self.lb = []  # for autolabelling

  if self.args.save_hybrid:
            height, width = batch["img"].shape[2:]
            nb = len(batch["img"])
            bboxes = batch["bboxes"] * torch.tensor((width, height, width, height), device=self.device)
            self.lb = [
                torch.cat([batch["cls"][batch["batch_idx"] == i], bboxes[batch["batch_idx"] == i]], dim=-1)
                for i in range(nb)
            ]

        return batch
```
I can't run `save_hybrid` because of shape error:
```txt
val: Scanning /home/heizung1/ultralytics_yolov8-obb_ob_kitti/ultralytics/cfg/datasets/kitti/labels/val.cache... 3699 images, 0 backgrounds, 0 corrupt: 100%|██████████| 3699/3699 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50      mAP70  mAP50-95):   0%|          | 0/232 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/heizung1/ultralytics_yolov8-obb_ob_kitti/ultralytics/val_kitti_obb.py", line 62, in <module>
    metrics = model.val(data='/home/heizung1/ultralytics_yolov8-obb_ob_kitti/ultralytics/cfg/datasets/kitti_bev.yaml', imgsz=640, 
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/heizung1/ultralytics_yolov8-obb_ob_kitti/ultralytics/engine/model.py", line 642, in val
    validator(model=self.model)
  File "/home/heizung1/anaconda3/envs/ultralytics/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/heizung1/ultralytics_yolov8-obb_ob_kitti/ultralytics/engine/validator.py", line 176, in __call__
    batch = self.preprocess(batch)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/heizung1/ultralytics_yolov8-obb_ob_kitti/ultralytics/models/yolo/detect/val.py", line 60, in preprocess
    bboxes = batch["bboxes"] * torch.tensor((width, height, width, height), device=self.device)
             ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1
```

**Comment by glenn-jocher** [comment]
Thanks for providing the detailed error trace. This appears to be an OBB-specific issue where the bounding box tensor includes angle information (5 parameters) while the scaling tensor only accounts for 4 parameters. The fix requires modifying the scaling operation in `models/yolo/detect/val.py` to handle OBB's 5-parameter format:

```python
# Change line 60 in val.py from:
torch.tensor((width, height, width, height), device=self.device)
# To:
torch.tensor((width, height, width, height, 1.0), device=self.device)  # add 1.0 for angle dimension
```

This adjustment ensures proper dimension matching for OBB tasks. The fix will be included in an upcoming release, but you can apply it manually in your local installation meantime. Let us know if you encounter any other issues!

**Comment by Petros626** [comment]
is a fix for the shape mismatch, but what about here https://github.com/ultralytics/ultralytics/pull/19531

**Comment by glenn-jocher** [comment]
Thanks for highlighting PR #19531! We're reviewing community contributions carefully. For OBB validation plots, you're correct that setting `plots=True` in the `val()` method will generate label vs prediction comparison images, as shown in the OBB validation documentation. This functionality exists in the current codebase when using the proper OBB model configuration. Let us know if you encounter any specific issues implementing this with your OBB dataset.
