### ISSUE TITLE
About the minimum version of Pytorch related

### ISSUE THREAD

**Issue by SWHL** [ultralytics/ultralytics#4248]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

In the [documentation](https://github.com/ultralytics/ultralytics#documentation), It shows the minimum PyTorch is 1.7 when pip install the ultralytics package.

But when I install the `torch==1.7.1` to train the detect model, I met the following errors:
```bash
Traceback (most recent call last):
  File "/data/xxx/ObjectDetect/yolov8/train.py", line 5, in <module>
    model.train(data='layout.yaml', epochs=200, imgsz=640, device=[0, 1])
  File "/data/xxx/ObjectDetect/yolov8/ultralytics/engine/model.py", line 377, in train
    self.trainer.train()
  File "/data/xxx/ObjectDetect/yolov8/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/data/xxx/ObjectDetect/yolov8/ultralytics/engine/trainer.py", line 276, in _do_train
    self._setup_train(world_size)
  File "/data/xxx/ObjectDetect/yolov8/ultralytics/engine/trainer.py", line 240, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
  File "/data/xxx/ObjectDetect/yolov8/ultralytics/models/yolo/detect/train.py", line 35, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode, batch_size)
  File "/data/miniconda3/envs/wjh/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/data/xxx/ObjectDetect/yolov8/ultralytics/utils/torch_utils.py", line 43, in torch_distributed_zero_first
    dist.barrier(device_ids=[0])
TypeError: barrier() got an unexpected keyword argument 'device_ids'
```
Then, I look into the `yolov8/ultralytics/utils/torch_utils.py`, and find the error code line:
https://github.com/ultralytics/ultralytics/blob/7dfdb63cde96f299f4d6afe8795512091cada40a/ultralytics/utils/torch_utils.py#L43

I take look [the document of `torch==1.7.1`](https://pytorch.org/docs/1.7.1/distributed.html?highlight=barrier#torch.distributed.barrier), and it does't have the `device_ids` parameter.  But [the documentation of `torch==1.8.0`](https://pytorch.org/docs/1.8.0/distributed.html?highlight=barrier#torch.distributed.barrier) has the parameter.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@SWHL thank you for raising this issue and going through our documentation in detail!

Regarding your observation, it appears there might have been some confusion, my apologies for that. The error you are encountering is due to a difference in the `torch.distributed.barrier` function in PyTorch versions. The 'device_ids' parameter you are referring to was introduced only from version 1.8.0 onwards. In version 1.7.1, it seems this function does not support the 'device_ids' parameter which leads to the error you are observing.

The minimum PyTorch version requirement indicated in our documentation refers to the overall compatibility of PyTorch with our Ultralytics package but it doesn't necessarily guarantee specific function compatibilities. In this particular case, for utilizing the distributed training feature in YOLOv8, you would likely need PyTorch version 1.8.0 or later.

We will take note of this and consider updating our documentation to reflect these specific cases where different PyTorch function compatibilities may affect certain features in YOLOv8. Again, thank you for bringing this issue to our attention and helping us improve the documentation!

**Comment by SWHL** [comment]
The problem has been reported, so I will close the issue firstly.
Thank you also for such a great job.

**Comment by glenn-jocher** [comment]
@SWHL thank you for bringing this issue to our attention and helping us improve YOLOv8. We appreciate your contribution and have noted it down. Thanks again for your acknowledgment and support. Feel free to create new issues if any problem arises in the future. Happy coding!

**Comment by glenn-jocher** [comment]
@SWHL great news 😃! Your original issue may now be resolved ✅ in PR #4299. This bumps torch, torchvision and Python version to 1.8.0, 0.9.0 and 3.8.0 respectively for better clarity for all users.

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by SWHL** [comment]
This update has fixed the issue. 😁
Your work is very efficient. 👍

**Comment by glenn-jocher** [comment]
@SWHL, I'm pleased to hear that the update resolved your issue! Thanks for the feedback, and it's great to know that our work is proving effective for you. If any other questions or problems come up in the future, don't hesitate to let us know. Happy coding with YOLOv8!
