### ISSUE TITLE
Suggestion: Mosaic3 as augmentation

### ISSUE THREAD

**Issue by Leo-Moooon** [ultralytics/ultralytics#4251]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

PR on https://github.com/ultralytics/ultralytics/pull/4250

I suggest a customized mosaic method `_mosaic3`, based on `_mosaic9` in _augment.py_, `class Mosaic.`

I usually prefer to use Mosaic to make my model robust to real world's data, but I found a critical flawness in my project.
The project uses a dataset with a ground view and all the objects in dataset places on the floor. 

But when training with a mosaic4 or mosaic9, mAP goes a bit higher but it also produce FP(False Positive) predictions.
So I customized the existing mosaic methods not to make undesirable height position noises.

It not only takes no additional calculation compared to existing methods, but also written very similar with them.
I don't think that undesirable noise problem is just minor one in certain case.

For these reasons, it would be a good option to add this method.

### Use case

- FP bbox in left top corner with mosaic4

![image](https://github.com/ultralytics/ultralytics/assets/112473734/8c9edc5c-408a-448c-b219-5e675beba279)

- solved with mosaic3 

![image](https://github.com/ultralytics/ultralytics/assets/112473734/dfd50d4c-48ca-41c7-ac7b-896ec69b347b)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@Leo-Moooon hey there! 👋

Thank you for the suggestion! The team appreciates your detailed explanation and use case examples. I think your proposed customized mosaic method, `_mosaic3`, to address the undesirable height position noise issue sounds promising. It's great to hear that it doesn't involve additional computations and aligns well with the existing methods.

We're glad to see your willingness to contribute by submitting a PR. Your input would certainly benefit the community and help improve the robustness of YOLOv8 for real-world scenarios.

If you have any questions or need assistance with the process, feel free to ask. Looking forward to your PR submission! 🚀

**Comment by Leo-Moooon** [comment]
Hi @pderrenger!

Thank you for your interest in my proposal. I'm not familiar with GitHub, so I'm afraid I didn't follow the precautions.
I'll refer back to the PR notes, fix a few line of code, and submit it soon 😀

**Comment by Leo-Moooon** [comment]
Hi @pderrenger!

I just updated my suggestion in PR #6898. 
Feel free to check out my PR and if there are any feedbacks, just let me know. Thanks 😀
