### ISSUE TITLE
get inference time value

### ISSUE THREAD

**Issue by najwabelarbi2** [ultralytics/ultralytics#4252]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, 
I hope someone can answer my question,
I want to get the value of inference time in ms (the value that is displayed of the terminal during predict mode for camera, and i want to use these values to draw a plot. do you know how i can proceed (using Python code)?
I've searched and found that the function responsible for writing this inference value is stream_inference, in BasePredictor class, but i don't know how i can use it in my code to get inference value,

Thank you in advance for your answer

**Comment by glenn-jocher** [comment]
@najwabelarbi2 hi there, 

Thank you for reaching out with your question and for checking previous issues before asking - that's greatly appreciated!

You're correct about the `stream_inference` function in the `BasePredictor` class, this is how inference time is calculated. This time is calculated using Python's built-in `time` module by noting the time before and after inference, and the difference gives the inference time.

While we do not provide code examples per guidelines, what you would need to do is to invoke the `BasePredictor` class and use the `stream_inference` method. However, you don't call these directly. They're used internally when you're running the prediction. If you want to record these values over time for plotting, you might want to modify the function in your local YOLOv8 repo to write these time values to a file that you can then use for your plot.

I hope this helps guide you in the right direction. Do let us know if you have any other questions, happy coding!
