### ISSUE TITLE
Incorrect Ray Tune Docs for result_grid metrics

### ISSUE THREAD

**Issue by SilverStarCoder** [ultralytics/ultralytics#4259]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Integrations

### Bug

On the [Ray tune page](https://docs.ultralytics.com/integrations/ray-tune/), the one section says we can plot the entire history of reported metrics for each trial by running the following code:

## Plotting the Entire History of Reported Metrics for a Trial

You can plot the history of reported metrics for each trial to see how the metrics evolved over time.

```
import matplotlib.pyplot as plt

for result in result_grid:
    plt.plot(result.metrics_dataframe["training_iteration"], result.metrics_dataframe["mean_accuracy"], label=f"Trial {i}")

plt.xlabel('Training Iterations')
plt.ylabel('Mean Accuracy')
plt.legend()
plt.show()
```

However, "**mean_accuracy**" doesn't seem to be an actual metric. These are the columns of the results.metrics_dataframe:
 ```
['metrics/precision(B)', 'metrics/recall(B)', 'metrics/mAP50(B)',
'metrics/mAP50-95(B)', 'val/box_loss', 'val/cls_loss', 'val/dfl_loss',
'epoch', 'time_this_iter_s', 'done', 'training_iteration', 'trial_id',
'date', 'timestamp', 'time_total_s', 'pid', 'hostname', 'node_ip',
'time_since_restore', 'iterations_since_restore']
```

As a result, the given code produces an error and is confusing to users who are new to Ray tune. 

### Environment

Ultralytics: 8.0.147
OS: Linux 5.15.0-1041-azure
Python: 3.9.5
Databricks Cluster Runtime: 12.2 ML (GPU)

### Minimal Reproducible Example

```
from ultralytics import YOLO

# Load a YOLOv8n model
model = YOLO("yolov8n.pt")

# Start tuning hyperparameters for YOLOv8n training on the COCO128 dataset
result_grid = model.tune(data="coco128.yaml")

# Plotting the Entire History of Reported Metrics for a Trial
import matplotlib.pyplot as plt

for result in result_grid:
    plt.plot(result.metrics_dataframe["training_iteration"], result.metrics_dataframe["mean_accuracy"], label=f"Trial {i}")

plt.xlabel('Training Iterations')
plt.ylabel('Mean Accuracy')
plt.legend()
plt.show()
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@SilverStarCoder hello,

Thank you for bringing this to our attention and for providing such a detailed issue report. I appreciate it.

It looks like there may have been a mistake in the metric presented in our documentation for the Ray Tune feature in the YOLOv8 Integration section. As you've correctly pointed out, "mean_accuracy" is indeed not part of the metrics provided by YOLOv8's training process. 

For your specific usage, a useful metric available in the output dataframe might be 'metrics/mAP50(B)' or 'metrics/mAP50-95(B)', which is related to model accuracy. YOLOv8 uses the Mean Average Precision (mAP) at Intersection over Union (IoU) = 0.50:0.95, and at IoU = 0.50, as standard evaluation metrics.

We will promptly update the documentation to reflect the correct usage and provide clarity for users. If you have further queries or issues, feel free to ask. We highly value your input and contribution to improving the YOLOv8 repository.

Best Regards,
Glenn Jocher
