### ISSUE TITLE
Predict

### ISSUE THREAD

**Issue by hoangnhien2411** [ultralytics/ultralytics#428]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to predict a test set and visualize the result. After training, we get the plots about confusion matrix, F1_curve, result... in runs folder. How to get such things after predicting a test set?

**Comment by BenjiKCF** [comment]
just swap your val.txt with test.txt and use task=val

**Comment by AyushExel** [comment]
I hope you've solved this. If not please reopen the issue :)
