### ISSUE TITLE
How to get a slanted object detection box?

### ISSUE THREAD

**Issue by dejian-lc** [ultralytics/ultralytics#4288]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

May I ask that the boxes in the target detection are all rectangular boxes, how to achieve rectangular boxes that change with the position of the object, such as diagonal rectangular boxes?Or I mean rectangular boxes with angles.I know that instance segmentation can get this kind of box based on the edge of the mask, but yolo's instance segmentation and object detection are not a network, and the performance of instance segmentation seems to be lower. And does yolo instance segmentation now support getting angled rectangles directly?

**Comment by andresinsitu** [comment]
They are actually working on implementing that, see pull requests

**Comment by glenn-jocher** [comment]
@dejian-lc thank you for your question. The standard implementation of YOLOv8, much like many object detection models, provides axis-aligned bounding boxes for object detection, which are not able to cater to slanted or rotated objects. 

Modifying YOLOv8 to support rotation or slanting of bounding boxes requires a significant departure from the original architecture and loss function, as it necessitates the bounding boxes to be parametrized in a different manner such as including parameters for angle or orientation. 

As it stands currently, there isn't in-built support in YOLOv8 for such rotated bounding boxes nor for instance segmentation that directly outputs rotated rectangles. 

We are continuously working on improving our models and adding new features, including exploring various ways of handling object detection in complex situations such as rotated or slanted objects. However, at present, there are no immediate developments or pull request in this specific case. We recommend you to keep an eye on our repo for future updates. Your patience and support is much appreciated. 

Please let us know if you have any other questions or concerns.
