### ISSUE TITLE
 yolov8 detect and seg results is none!

### ISSUE THREAD

**Issue by QzYER** [ultralytics/ultralytics#430]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

test a picture have  no any predict output ? i want to get predict class and box. please tell me how to do ?  in predictor.py only preds! it is a tesor .

**Comment by AyushExel** [comment]
@QzYER  you need to pass `return_outputs=True` to get results.. We're fixing this in this PR. Should be merged today
https://github.com/ultralytics/ultralytics/pull/314

**Comment by Lahari-77** [comment]
how to reference the no detections inorder to write the try except block @glenn-jocher

**Comment by glenn-jocher** [comment]
@Lahari-77 hi there! To reference no detections and write a try-except block in YOLOv8, you can utilize the `pred` variable in the `predictor.py` script. 

When there are no detections, `pred` will be an empty tensor. You can check if `pred` is empty using the Python `if` statement. If `pred` is empty, you can handle the no detections scenario inside the `try` block by performing any desired action or raising an exception.

Here's an example of how you could do this:

```python
try:
    # Your code to predict using YOLOv8 model
    pred = model(img)
    
    # Check if detections are found
    if len(pred) == 0:
        # Handle the no detections scenario here
        print("No detections found.")
        # Perform any desired action or raise an exception
        
    # Process the detections
    else:
        # Your code to process the detections here

except Exception as e:
    # Handle any exceptions that occur during prediction
    print("An exception occurred:", str(e))
```

This way, you can handle cases when no detections are found and perform specific actions or handle exceptions accordingly. Remember to replace the comments with your actual code for predicting using the YOLOv8 model and processing the detections.

I hope this helps! Let me know if you have any further questions.

**Comment by Lahari-77** [comment]
I experimented that ven if there are no detection still the length of pred is 1.I have checked it

**Comment by glenn-jocher** [comment]
@Lahari-77 hi there,

Thank you for bringing this to our attention. In YOLOv8, when there are no detections, the length of the `pred` variable should be 0, indicating that there are no predictions. It's possible that there may be some confusion or misunderstanding in your experimentation.

To handle the scenario of no detections, you can use an `if` statement to check if the length of `pred` is equal to 0. If it is, you can then handle the no detections scenario accordingly.

If you're still experiencing issues or have further questions, please let us know and we'll be happy to assist you.

Best regards,
Glenn Jocher
