### ISSUE TITLE
Is there any sample code about to inference(predict) with exported onnx model

### ISSUE THREAD

**Issue by yellowjs0304** [ultralytics/ultralytics#4302]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, Thanks for your work.
First of all, i installed my environment by python. 

```
git clone this repo
pip install -e .
```

And i got exported model by my custom model
```
yolo export model=./best.pt format=onnx
```

Is there any sample code or guide that i can predict with onnx model?

**Comment by Kayzwer** [comment]
@yellowjs0304 depends on what env you want to run your onnx

**Comment by yellowjs0304** [comment]
@Kayzwer The environment is onnx_runtime.

**Comment by glenn-jocher** [comment]
Hello @Kayzwer,

Thanks for utilizing our model and reaching out with your question.

If you've already exported the ONNX model with the Ultralytics export tool, you can very much utilize it in the ONNX Runtime environment.

To use the ONNX model for inference in ONNX Runtime, you'll primarily need to do the following:

* Install ONNX Runtime in your development environment.

* Load the ONNX model with the ONNX Runtime `InferenceSession` method.

* Prepare your input data in a format that matches your trained model's expected input shape and format.

* Run the inference session using the `run` method, which executes the model with the provided inputs.

* The `run` method will return an array of output tensors.

Please consider that the preprocessing and postprocessing steps will need to be handled accurately as per your model's requirements (like normalization, resizing, non-maximum-suppression, etc.).

I hope this general guideline helps you to continue with your project. If you have further questions or face issues, please, don't hesitate to ask. Remember, we are here to help.

Best,
Glenn

**Comment by glenn-jocher** [comment]
@yellowjs0304 just run it normally, i.e. `yolo predict model=yolov8n.onnx`.

These Usage examples are shown to you after export completes, follow those.
