### ISSUE TITLE
Not valid model with converted tflight model 

### ISSUE THREAD

**Issue by SteadyKim** [ultralytics/ultralytics#4305]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

[Situation]
1. i needed the tflight model in android project
2.  i first converted the yolo-seg-model with below code

```
from ultralytics import YOLO
model = YOLO('yolov8n-seg.pt')  

model.export(format='tflight')

```
3. i got yolov8n-seg_float16.tflite but getting trouble with this issue 
![image](https://github.com/ultralytics/ultralytics/assets/88755733/af50d907-265d-4a6e-9b2e-fe4265a6587a)

4. another converted tflight model is ok in android when i used just 'yolov8n-pt' which is not a segment
```
from ultralytics import YOLO
model = YOLO('yolov8n.pt')  

model.export(format='tflight')
```

[help me]
1. i want to get tflight model
 
```
from ultralytics import YOLO
model = YOLO('mycustom-seg.pt')  

model.export(format='tflight')
```

please tell me the solution. thank you.

**Comment by glenn-jocher** [comment]
@SteadyKim thank you for your detailed description of the problem. 

It seems that you're encountering an issue when trying to convert a 'yolov8n-seg.pt' model to a TensorFlow Lite format for use in an Android project. The process seems to work fine when using a non-segmentation model, such as 'yolov8n.pt', but causes problems when using a segmentation model. I understand your need for a solution for your custom segmentation model ('mycustom-seg.pt').

YOLOv8 Tensorflow Lite export currently supports exporting models that focus on detection tasks but may encounter problems with different model architectures such as segmentation models. The issue you're experiencing is most probably tied to these differences. We're constantly working on improving and adding to our model export features, but at the moment, we don't have immediate support for exporting segmentation models to Tensorflow Lite.

In the meantime, you might have to use different architectures or strategies that are more readily convertible to TensorFlow Lite for deployment on Android. You might consider exploring additional tools or platforms that might help bridge the gap in support for segmentation models on mobile platforms. 

Your problem enhances our awareness of this limitation, and this will be considered in our future updates. We appreciate your contribution to the Ultralytics community. Thanks for using Ultralytics YOLOv8.

**Comment by SteadyKim** [comment]
thanks for the answer.

**Comment by Chebulex** [comment]
You wrote:
`model.export(format='tflight')`
but the modle is format is named tflite not tflight.

**Comment by pderrenger** [comment]
@Chebulex Apologies for the confusion. You are absolutely right. The correct format for exporting to TensorFlow Lite is indeed 'tflite', not 'tflight'. Thank you for pointing that out. Have a great day!

**Comment by glenn-jocher** [comment]
@pderrenger My mistake, and thank you for the correction. The correct command should indeed use 'tflite' for TensorFlow Lite export. Appreciate your attention to detail! 👍
