### ISSUE TITLE
Unable to export model ( tflite )

### ISSUE THREAD

**Issue by MuhammadSibtain5099** [ultralytics/ultralytics#431]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

![image](https://user-images.githubusercontent.com/62267102/212811698-315f3183-73eb-4185-99ca-664694c11aba.png)
I am trying to export my yolov8 model best.pt into best.tflite but it shows me this message. 

I have tried some suggested solutions but it is not working for me. 

### Environment

- Yolov8  conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch
- GPU RTC 3090 Ti
- CUDA Version: 11.7 
- NVIDIA-SMI 516.94
- Python 3.7.13
- OS (Windows 11)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
tflite isn't supported yet. We'll work on it later this week

**Comment by MuhammadSibtain5099** [comment]
can you tell me that about tflite implementation in android studio? Will it be the same as yolov5? and its shape.

**Comment by AyushExel** [comment]
Yes once we implement it, it'll be similar to yolov5

**Comment by MuhammadSibtain5099** [comment]
oh Great., Thank you, All the best YOLOv8 team.

**Comment by MuhammadSibtain5099** [comment]
@AyushExel Is your team still working on it?
