### ISSUE TITLE
FileNotFoundError: Found no valid file for the classes runs. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp

### ISSUE THREAD

**Issue by Zoolnurain** [ultralytics/ultralytics#4310]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello!
This is my code for classification: gym-Splitted folder have three folders with the name of "train", "validation" and "test"
But its throwing error.

import os
from ultralytics import YOLO
model = YOLO("yolov8n-cls.pt") #build a new model
results= model.train(data="/content/drive/MyDrive/gym_data/gym_dataset/gym-Splitted",epochs=1)

**Comment by glenn-jocher** [comment]
@Zoolnurain hi there. I think maybe the problem is that your val folder should be called 'val' instead of 'validation'. I'll check to see if this is a failure mode here.

**Comment by glenn-jocher** [comment]
@Zoolnurain great news 😃! Your original issue may now be resolved ✅ in PR #4312. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!
