### ISSUE TITLE
Model definition of YoloV8

### ISSUE THREAD

**Issue by mbenencase** [ultralytics/ultralytics#4311]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi y'all

I'm used to YoloV5 .yaml model files, where I was able to modify the model. But the `ultralytics` package downloads the .yaml model definition file to somewhere that I'm not sure where it is located :sweat_smile: . There's a way to get that file? Or even, there's a tutorial on how to create my own .yaml model?

Thanks in advance!

**Comment by mbenencase** [comment]
I find what I was looking for. It is in the path `ultralytics/ultralytics/cfg/models/v8/`.

I'll close the issue. Thanks!

**Comment by pderrenger** [comment]
@mbenencase glad to hear you found what you were looking for! If you have any more questions or need further assistance, feel free to ask. Happy coding!

**Comment by glenn-jocher** [comment]
@pderrenger Fantastic, I'm glad you located the model definitions! Should you need any additional support or have questions in the future, don't hesitate to reach out. Happy modeling! 😊🚀
