### ISSUE TITLE
Yolov8 tracker weird behavior (AttributeError: 'NoneType')

### ISSUE THREAD

**Issue by herrig** [ultralytics/ultralytics#4315]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am creating a custom code to perform the detection using Yolov8 + tracker to identify weeds and create a csv file with the gps RTK coordinates for each detection. I am facing a problem when my video doesn't have detections and the system return this error:

track_ids = results[0].boxes.id.int().cpu().tolist()
AttributeError: 'NoneType' object has no attribute 'int'

When I have a video with a lot o identifications the code runs perfectly.

Does anyone could help me to find a solution? 
I have copied my snipped code below:

.........
 # Run YOLOv8 tracking on the frame using the selected tracker
        results = model.track(frame, persist=True, tracker=tracker_option)

        # Get the boxes and track IDs
        boxes = results[0].boxes.xywh.cpu()
        confidences = results[0].boxes.conf.cpu()
        class_ids = results[0].boxes.cls.cpu()
        track_ids = results[0].boxes.id.int().cpu().tolist()

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # First horizontal detection line
        line_y1 = int(conf_slider4.get())
        cv2.line(annotated_frame, (0, line_y1), (x_shape, line_y1), (255, 0, 0), 2)

        # Second horizontal detection line
        line_y2 = int(conf_slider5.get())
        cv2.line(annotated_frame, (0, line_y2), (x_shape, line_y2), (255, 0, 0), 2)

        # Split the frame in four horizontal line
        part_width = int(x_shape / 4)
        line1_x = part_width
        line2_x = 2 * part_width
        line3_x = 3 * part_width

        # Vertical lines
        cv2.line(annotated_frame, (line1_x, 0), (line1_x, y_shape), (0, 255, 0), 2)
        cv2.line(annotated_frame, (line2_x, 0), (line2_x, y_shape), (0, 255, 0), 2)
        cv2.line(annotated_frame, (line3_x, 0), (line3_x, y_shape), (0, 255, 0), 2)

        # Loop through detected objects
        for box, confidence, class_ids, track_id in zip(boxes, confidences, class_ids, track_ids):
            if confidence > conf_level:
                x, y, w, h = box
                track = track_history[track_id]
                center_x = x + w / 2
                center_y = y + h / 2

                # Check if the center of the object crossed the line vertically
                if line_y1 < center_y < line_y2:
                    if 0 <= center_x < line1_x:
                        count_section1 += 1
                    elif line1_x <= center_x < line2_x:
                        count_section2 += 1
                    elif line2_x <= center_x < line3_x:
                        count_section3 += 1
                    else:
                        count_section4 += 1

                    if not object_crossed_line.get(track_id, False):
                        object_count += 1
                    object_crossed_line[track_id] = True
                else:
                    object_crossed_line[track_id] = False

    # Adjust text positions based on frame resolution
    text_offset = int(x_shape / 16)
    count_section1_pos = (text_offset, 20)
    count_section2_pos = (line1_x + text_offset, 20)
    count_section3_pos = (line2_x + text_offset, 20)
    count_section4_pos = (line3_x + text_offset, 20)
    text_position = (int(x_shape / 16), int(y_shape - 20))

    # Black background rectangle
    start_point = (0, 25)
    end_point = (1280, 0)
    color = (0, 0, 0)
    thickness = -1
    cv2.rectangle(annotated_frame, start_point, end_point, color, thickness)

    # Print the number of objects identified
    total_count_label.config(text=f"Total Count: {object_count}")
........

**Comment by a-rbsn** [comment]
@herrig did you fix this?

**Comment by herrig** [comment]
@a-rbsn Yes, I used this structure:

        results = model.track(frame, imgsz=img_size, persist=True, conf=conf_level, tracker=tracker_option)
        # print(results)
        if results[0].boxes.id != None:
            boxes = results[0].boxes.xyxy.cpu().numpy().astype(int)
            ids = results[0].boxes.id.cpu().numpy().astype(int)
            confidences = results[0].boxes.conf.cpu().numpy().astype(int)

**Comment by a-rbsn** [comment]
@herrig perfect thanks, I arrived at a similar solution 🙌

**Comment by glenn-jocher** [comment]
That's great to hear @a-rbsn! Thanks for sharing your solution. If you run into any other issues in the future, don't hesitate to bring them up. We're here to help. Happy coding with YOLOv8!

**Comment by kkczw** [comment]
> @a-rbsn Yes, I used this structure:
> 
> ```
>     results = model.track(frame, imgsz=img_size, persist=True, conf=conf_level, tracker=tracker_option)
>     # print(results)
>     if results[0].boxes.id != None:
>         boxes = results[0].boxes.xyxy.cpu().numpy().astype(int)
>         ids = results[0].boxes.id.cpu().numpy().astype(int)
>         confidences = results[0].boxes.conf.cpu().numpy().astype(int)
> ```
Thank you very much for sharing, but I encountered a new error after making the changes according to your method:
   for box, track_id in zip(boxes, track_ids):
NameError: name 'boxes' is not defined

**Comment by NguyenDucQuan12** [comment]
> > @a-rbsn Yes, I used this structure:
> > ```
> >     results = model.track(frame, imgsz=img_size, persist=True, conf=conf_level, tracker=tracker_option)
> >     # print(results)
> >     if results[0].boxes.id != None:
> >         boxes = results[0].boxes.xyxy.cpu().numpy().astype(int)
> >         ids = results[0].boxes.id.cpu().numpy().astype(int)
> >         confidences = results[0].boxes.conf.cpu().numpy().astype(int)
> > ```
> 
> Thank you very much for sharing, but I encountered a new error after making the changes according to your method: for box, track_id in zip(boxes, track_ids): NameError: name 'boxes' is not defined

I also get this error, how to fix it @glenn-jocher

**Comment by NguyenDucQuan12** [comment]
I found other people also had this error and their temporary fix was: 
if results[0].boxes.id != None:
            boxes = results[0].boxes.xyxy.cpu().numpy().astype(int)
            # Check if results[0].boxes.id is not None before accessing int() method
            track_ids = results[0].boxes.id.int().cpu().tolist() if results[0].boxes.id is not None else []
            #track_ids = results[0].boxes.id.cpu().tolist()
            confidences = results[0].boxes.conf.cpu().numpy().astype(int)
But I expect correct and future-proof answers that don't conflict with other features from ultralytics

**Comment by NguyenDucQuan12** [comment]
@glenn-jocher  I want to customize the annotated_frame to contain text, or remove the id, how do I do that?
`from collections import defaultdict
import cv2
import numpy as np
from ultralytics import YOLO


# Load the YOLOv8 model
model = YOLO('./model/best.pt')

# Open the video file
video_path = "./demo/demo.mp4"
cap = cv2.VideoCapture(video_path)

# Store the track history
track_history = defaultdict(lambda: [])

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        #print("compele access video")
        # Run YOLOv8 tracking on the frame, persisting tracks between frames
        results = model.track(frame, persist=True, tracker="bytetrack.yaml")

        # Get the boxes and track IDs
        #print(results[0].boxes.id)
        
        if results[0].boxes.id != None:
            boxes = results[0].boxes.xyxy.cpu().numpy().astype(int)
            # Check if results[0].boxes.id is not None before accessing int() method
            track_ids = results[0].boxes.id.int().cpu().tolist() if results[0].boxes.id is not None else []
            #track_ids = results[0].boxes.id.cpu().tolist()
            confidences = results[0].boxes.conf.cpu().numpy().astype(int)

        labels = [
            f"#{tracker_id} {model.model.names[class_id]} {confidence:0.2f}"
            for _, _, confidence, class_id, tracker_id
            in detections
        ]
        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Plot the tracks
        for box, track_id in zip(boxes, track_ids):
            x, y, w, h = box
            track = track_history[track_id]
            track.append((float(x), float(y)))  # x, y center point
            if len(track) > 30:  # retain 90 tracks for 90 frames
                track.pop(0)

            # Draw the tracking lines
            points = np.hstack(track).astype(np.int32).reshape((-1, 1, 2))
            cv2.polylines(annotated_frame, [points], isClosed=False, color=(230, 230, 230), thickness=10)

        # Display the annotated frame
        cv2.imshow("YOLOv8 Tracking", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()`

**Comment by NguyenDucQuan12** [comment]
@glenn-jocher   I want to customize the annotated_frame to contain text, or remove the id, how do I do that?
.........
from collections import defaultdict
import cv2
import numpy as np
from ultralytics import YOLO


# Load the YOLOv8 model
model = YOLO('./model/best.pt')

# Open the video file
video_path = "./demo/demo.mp4"
cap = cv2.VideoCapture(video_path)

# Store the track history
track_history = defaultdict(lambda: [])

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        #print("compele access video")
        # Run YOLOv8 tracking on the frame, persisting tracks between frames
        results = model.track(frame, persist=True, tracker="bytetrack.yaml")

        # Get the boxes and track IDs
        #print(results[0].boxes.id)
        
        if results[0].boxes.id != None:
            boxes = results[0].boxes.xyxy.cpu().numpy().astype(int)
            # Check if results[0].boxes.id is not None before accessing int() method
            track_ids = results[0].boxes.id.int().cpu().tolist() if results[0].boxes.id is not None else []
            #track_ids = results[0].boxes.id.cpu().tolist()
            confidences = results[0].boxes.conf.cpu().numpy().astype(int)

        labels = [
            f"#{tracker_id} {model.model.names[class_id]} {confidence:0.2f}"
            for _, _, confidence, class_id, tracker_id
            in detections
        ]
        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Plot the tracks
        for box, track_id in zip(boxes, track_ids):
            x, y, w, h = box
            track = track_history[track_id]
            track.append((float(x), float(y)))  # x, y center point
            if len(track) > 30:  # retain 90 tracks for 90 frames
                track.pop(0)

            # Draw the tracking lines
            points = np.hstack(track).astype(np.int32).reshape((-1, 1, 2))
            cv2.polylines(annotated_frame, [points], isClosed=False, color=(230, 230, 230), thickness=10)

        # Display the annotated frame
        cv2.imshow("YOLOv8 Tracking", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()
.........

**Comment by glenn-jocher** [comment]
@NguyenDucQuan12 to customize the `annotated_frame` in YOLOv8, you can modify the `plot()` method's output. If you want to add custom text, use OpenCV's `cv2.putText()` function. To remove the track ID from the annotations, you can adjust the `labels` list comprehension to exclude the `tracker_id`.

Here's a concise guide:

1. **Add Custom Text:**
   - Use `cv2.putText(annotated_frame, text, position, font, fontScale, color, thickness)` after you get `annotated_frame` from `results[0].plot()`.

2. **Remove Track ID:**
   - Modify the `labels` list comprehension to not include `tracker_id`. If you don't want any labels, you can skip creating the `labels` list.

Remember to adjust the `plot()` method if you want to change the default behavior of how annotations are drawn. If you need further customization, you might need to modify the source code of the `plot()` method or create your own visualization function.

**Comment by NguyenDucQuan12** [comment]
@glenn-jocher  thank you for sharing
I tried to run the Plotting Tracks Over Time code provided from the link: https://docs.ultralytics.com/modes/track/#plotting-tracks-over-time but always got an error with tracker_ids, I tried a There are several ways to fix it but it only works for a while and then the error appears again. Please show me how to fix it

**Comment by NguyenDucQuan12** [comment]
`results = model.track(im0, persist=True, show= True)`
it works perfectly with id, class, score, but if i use:
```
if results[0].boxes.id is not None and results[0].masks is not None:
        masks = results[0].masks.xy
        track_ids = results[0].boxes.id.int().cpu().tolist()

        for mask, track_id in zip(masks, track_ids):
            annotator.seg_bbox(mask=mask,
                               mask_color=colors(track_id, True),
                               track_label=str(track_id))
    else:
        print("error")
```
The result always returns "error", whyyyyyyy

**Comment by NguyenDucQuan12** [comment]
@glenn-jocher Can you give me more information about the options in the plot function? 
`results = model.track(frame, persist=True, tracker="bytetrack.yaml, show_labels=False, ...")`
but in `results[0].plot(labels= False)` ,

**Comment by glenn-jocher** [comment]
@NguyenDucQuan12 certainly! The `plot()` function in YOLOv8 provides several options to customize the visualization of your results. The `labels` parameter, when set to `False`, will prevent the drawing of labels (class names, confidence, and track IDs) on the `annotated_frame`. You can use this parameter directly within the `plot()` function call like so:

```python
annotated_frame = results[0].plot(labels=False)
```

This will give you the annotated frame with bounding boxes but without any text labels. For additional customization options, please refer to the documentation at https://docs.ultralytics.com.
