### ISSUE TITLE
)How to specify location of save_txt in model.predict() (purpose is for aws lambda filesystem

### ISSUE THREAD

**Issue by Aravinth-Natarajan** [ultralytics/ultralytics#4317]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there a way to specify where the runs folder will be saves. I'm running ultralytics in a docker deployment and aws lamba has a read only filesystem other than the /tmp/ folder. How can I specify where runs will be put? 

Thanks in advance

**Comment by glenn-jocher** [comment]
@Aravinth-Natarajan use `project` and `name` args to save to `project/name` directory.
