### ISSUE TITLE
 FileNotFoundError: [Errno 2] No such file or directory: 'E:\\ultralytics\\hubconf.py'

### ISSUE THREAD

**Issue by TalalAhmed311** [ultralytics/ultralytics#432]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I was actually to load yolov8  model for my web application but it gives me this error. Does it not support the load model option using Pytorch yet?

`model = torch.hub.load('E:\\ultralytics', 'yolov8', path='yolov8.pt', source='local',force_reload=True)`

**Comment by prince0310** [comment]
`from ultralytics import YOLO`

`model = YOLO("yolov8x.pt")  # load an official model`
try this

**Comment by shahzain110** [comment]
Have you found any solutions for it?Facing same issue

**Comment by SergheiDinu** [comment]
Any solution founded here?

**Comment by pderrenger** [comment]
@SergheiDinu the issue you're encountering is related to the way the model is being loaded using `torch.hub.load`. Currently, YOLOv8 does not support model loading using `torch.hub.load` directly. Instead, you can load the YOLOv8 model using the Ultralytics Python API, as shown in the code snippet below:

```python
from ultralytics import YOLO

model = YOLO("yolov8x.pt")  # Load a YOLOv8 model using the Ultralytics Python API
```

You can directly use this snippet to load the YOLOv8 model for your web application. If you have any further questions or encounter any issues, feel free to ask!
