### ISSUE TITLE
add CUDA FP16 Inference to YOLOv8-ONNXRuntime-CPP demo 

### ISSUE THREAD

**Issue by DennisJcy** [ultralytics/ultralytics#4321]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hello!
My work on the semi-precision inference code was complete.Here I create this PR to add the function to this demo.
PR:https://github.com/ultralytics/ultralytics/pull/4320

# Summary
I added a new feature for semi-precision inference to this project, and added the corresponding content in the ReadMe file and the CMake file simultaneously.

# Walkthrough
1. Adding a specialization of the TypeToTensorType class template in the Ort namespace to map the half (16-bit floating point) type to the ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT16 type in the ONNX API. [link](https://github.com/ultralytics/ultralytics/pull/4320/files#diff-8a52ad28c0e0fa1a4348a3b3d4380f9abafe6985bb935a1eec74d3b77b76fca8R18-R24)
2. Fix some spelling issues in the return of error reports. [link](https://github.com/ultralytics/ultralytics/pull/4320/files#diff-8a52ad28c0e0fa1a4348a3b3d4380f9abafe6985bb935a1eec74d3b77b76fca8R66)
3. Add semi-precision model names to the enumeration of ModelTypes. [link](https://github.com/ultralytics/ultralytics/pull/4320/files#diff-f5d599dd06fc6fe16f8d0baa50c155992f0769af08495431ad265ad74dc4f90fR25-R28)
4. Add fp16 inference post-process code. [link](https://github.com/ultralytics/ultralytics/pull/4320/files#diff-8a52ad28c0e0fa1a4348a3b3d4380f9abafe6985bb935a1eec74d3b77b76fca8R152-R158)
5. Add fp16 model warm-up code. [link](https://github.com/ultralytics/ultralytics/compare/main...DennisJcy:ORT_CPP_AddFP16?expand=1#diff-8a52ad28c0e0fa1a4348a3b3d4380f9abafe6985bb935a1eec74d3b77b76fca8R283-R298)
6. Fix the demo code in ReadMe file.[link](https://github.com/ultralytics/ultralytics/pull/4320/files#diff-8dcaf249262d078e57bbf538f19ad18478ae52f4909bd5d3eb32dd923cd95a4bR51-R54)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@DennisJcy this is great, thanks for the updates!
