### ISSUE TITLE
Yolov8 backbone 

### ISSUE THREAD

**Issue by Caliphamin** [ultralytics/ultralytics#4324]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I was wondering is there a way to change yolov8-seg backbone?

**Comment by Kayzwer** [comment]
the path you need is `ultralytics/ultralytics/cfg/models/v8/yolov8-seg.yaml`

**Comment by Caliphamin** [comment]
> the path you need is `ultralytics/ultralytics/cfg/models/v8/yolov8-seg.yaml`

Oh thank god someone answered my question 
So if i want to change backbone to HRNet or UNet, what should I write in backbone section?


I mean in this part


backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

**Comment by Kayzwer** [comment]
if you mean the python code, you need to add your pytorch module code in one of the file in `/ultralytics/ultralytics/nn/modules/` make sure you also modify `ultralytics/ultralytics/nn/modules/__init__.py` and `ultralytics/ultralytics/nn/tasks.py`

**Comment by Caliphamin** [comment]
> if you mean the python code, you need to add your pytorch module code in one of the file in `/ultralytics/ultralytics/nn/modules/` make sure you also modify `ultralytics/ultralytics/nn/modules/__init__.py` and `ultralytics/ultralytics/nn/tasks.py`

Can you write the example of code and yaml file😃
For a simple backbone?

**Comment by Caliphamin** [comment]
> if you mean the python code, you need to add your pytorch module code in one of the file in `/ultralytics/ultralytics/nn/modules/` make sure you also modify `ultralytics/ultralytics/nn/modules/__init__.py` and `ultralytics/ultralytics/nn/tasks.py`

should i change the .yaml too?

**Comment by Kayzwer** [comment]
> > if you mean the python code, you need to add your pytorch module code in one of the file in `/ultralytics/ultralytics/nn/modules/` make sure you also modify `ultralytics/ultralytics/nn/modules/__init__.py` and `ultralytics/ultralytics/nn/tasks.py`
> 
> should i change the .yaml too?

yes

**Comment by pderrenger** [comment]
@Kayzwer yes, you should also modify the `.yaml` file to specify the new backbone architecture you want to use. Ensure that the changes you make in the Python code for the new backbone are appropriately reflected in the `.yaml` file to complete the backbone replacement.

**Comment by Caliphamin** [comment]
@pderrenger can you just write an example?
Like hrnet backbone
