### ISSUE TITLE
validation 

### ISSUE THREAD

**Issue by hoangnhien2411** [ultralytics/ultralytics#433]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

W
![Ảnh chụp màn hình_20230117_033753](https://user-images.githubusercontent.com/56782941/212850173-1835b8e4-9ad8-406b-94cd-1158c8fc207e.png)
hy is my validation result just like that . What is the problem?

**Comment by HarishGuragol** [comment]
@hoangnhien2411 Have you provided the best.pt weights to the validation command?

**Comment by pderrenger** [comment]
@hoangnhien2411 it looks like the validation result you're seeing might be unexpected. To help diagnose the issue, could you provide more details about your validation setup, such as the dataset you're using and the command you used for validation? This will help us understand the context and provide a more accurate solution. If you're using a custom dataset, please ensure that the annotations are in the correct format and that the classes match the model's configuration.
