### ISSUE TITLE
The label coordinates are inconsistent after the Instances class is initialized

### ISSUE THREAD

**Issue by Ruosong-Zhu** [ultralytics/ultralytics#4330]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

dataset: coco128
environment:
- torch 1.13.1+cu117
- torchvision 0.14.1+cu117
- numpy  1.21.5

During the data loading process, when executing the update_labels_info function, it was found that the coordinates of the labels changed after instantiating the Instances class.

Before Instances instantiating
![87544e743d613c378e358b5bd228cc7](https://github.com/ultralytics/ultralytics/assets/73803863/bbf30294-98f0-48ee-bd04-b6f80b56819e)
boxes is [[    0.73943      0.4845    0.029297    0.013125], [    0.65723     0.57649     0.22723     0.38394]]
same as txt

But after Instances instantiating
![image](https://github.com/ultralytics/ultralytics/assets/73803863/a49cb47c-960a-4051-8a77-9e0f553ec9c6)
label['instances'].bboxes is changed, but during the instantiating of Instances, I did not find any code to change the coordinates format.

then, i try to print it, after all, the code won't lie to me
![image](https://github.com/ultralytics/ultralytics/assets/73803863/a8f405bd-90c4-40df-bd64-c7fc8d060302)
ok，you pycharm！

vscode has same problem
![image](https://github.com/ultralytics/ultralytics/assets/73803863/2f09ec3b-94ca-4e60-9994-31cecefcbd32)

**Comment by confusedgreenhand** [comment]
There is a function named "resample_segments", it resamlpes the original instance label coordinates to 1000 points.
![e05f2429543cab6788504a928df81de](https://github.com/ultralytics/ultralytics/assets/49227338/53558bdc-65a0-4c88-8326-0d72b8d00528)

@glenn-jocher, Hi, I would like to ask you why you do this  "resample_segments" operation, what if the original instance label coordinates exceed 1000 points. I recently encountered the problem that the original instance label coordinates exceed 1000 points, after "resample_segments", the mask obtained by "polygon2mask" function is not correct.
![64406da3d393b8bd1f15904b5b2e8ac](https://github.com/ultralytics/ultralytics/assets/49227338/b6e2d6cd-6f2f-4f53-9109-870b2ed5270d)

@glenn-jocher, Looking forward to your reply, thank you very much.
