### ISSUE TITLE
Lighter Yolov8 Pose model for mobile device

### ISSUE THREAD

**Issue by pseudo-jay** [ultralytics/ultralytics#4333]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Lighter Yolov8 Pose model for mobile device. Current Yolov8n-pose model runs maximum at 6-7 fps on Android as well as iOS device.

### Use case

This will help to use Yolov8 Pose models for tasks like Exercise tracking, Action recognition on mobile devices.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@pseudo-jay hi there! 🌟 YOLOv8 Pose model optimization for mobile devices is a great idea! While the current YOLOv8n-pose model runs at 6-7 fps on Android and iOS devices, we understand the need for lighter models to support use cases like exercise tracking and action recognition. 

You might be interested in exploring model quantization or pruning techniques to reduce model size and improve performance on mobile devices. 

Feel free to check out the YOLOv8 documentation for more information on model optimization techniques. If you have any specific questions or need guidance on this, feel free to ask!
