### ISSUE TITLE
Polygraphy failure in onnx vs. TRT for specific Shape layer in YOLO8

### ISSUE THREAD

**Issue by weiss-israel** [ultralytics/ultralytics#4334]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

We want to utilize `polygraphy` tool from Nvidia for some kind of integration test for YOLO8 in onnx vs. its corresponding TensorRT (TRT) model. 
- When converting YOLO8 model to onnx and running `polygraphy run` on it, there's one specific output which fails the comparison: `Unnamed Layer* 311`. When looking in Netron we can see it corresponds to a Shape layer.
- This happens with the original YOLO8 model without any changes to it, as seen in the attached code below.
- Polygraphy logs are attached [here](https://drive.google.com/file/d/1x2crhpPF2jevA4NSiAkvHS1TnPrRnKV3/view?usp=sharing). Note the line:
```
 Comparing Output: '(Unnamed Layer* 311) [ElementWise]_output' (dtype=int32, shape=(3,)) with '311' (dtype=int64, shape=(4,))
[I]         Tolerance: [abs=0.001, rel=0.001] | Checking elemwise error
[E]         Will not compare outputs of different shapes. Note: Output shapes are (3,) and (4,).
Note: Use --no-shape-check or set check_shapes=False to attempt to compare values anyway.
[E]         FAILED | Output: '(Unnamed Layer* 311) [ElementWise]_output' | Difference exceeds tolerance (rel=0.001, abs=0.001)
```

### Environment

- YOLO: ultralytics==8.0.138
- OS in onnx export: Ubuntu 18.04
- Python in onnx export: 3.7.5
- Polygraphy setup: polygraphy installed by the Nvidia jetpack nvcr.io/nvidia/l4t-tensorrt:r8.5.2.2-devel base image
- onnxruntime version used for polygraphy: onnxruntime==1.15.1 
- numpy version used for numpy==1.21.6

### Minimal Reproducible Example

1. ONNX export code:
```
import torch
from ultralytics import YOLO

original_model = YOLO("yolov8n.pt")
dummy_input = torch.zeros(1, 3, 192, 1440, requires_grad=True)
original_model.export(format='onnx', imgsz=(192, 1440),
                       opset=12, verbose=True)
```

2. Polygraphy run command:
`polygraphy run <path_to_onnx_model> --trt --onnxrt --onnx-outputs mark all --trt-outputs mark all --atol 1e-3 --rtol 1e-3 `

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@weiss-israel thanks for the bug report! I would recommend raising errors generated by downstream/3rd party tools directly with their authors, as these are naturally outside of our control and beyond the scope of our support.

I've also never used this tool, so I can't provide any insight as to what might be the issue with it or with your usage of it.

**Comment by glenn-jocher** [comment]
@weiss-israel note you can always run ONNX and TRT models directly with Ultralytics in Benchmark or Predict modes, i.e. `yolo predict model=yolov8n.onnx` etc. See https://docs.ultralytics.com/modes/ for details.
