### ISSUE TITLE
Conda Install Bug

### ISSUE THREAD

**Issue by nadinator** [ultralytics/ultralytics#4335]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Installing ultralytics with conda leads to an error where torch's CUDA is no longer enabled, even if it was previously downloaded with CUDA enabled (also using conda). I think this might be due to a dependency in the ultralytics conda package because installing ultralytics with pip does NOT lead to this issue.

### Environment

- OS: Ubuntu 20.4
- Python: 3.11
- Conda: 23.7.2

### Minimal Reproducible Example

Run the conda installation for pytorch on linux:
```shell
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
```

Check if CUDA is enabled:
```python
import torch
print(torch.cuda.is_available())
```
This returns `True`.

Now install ultralytics:
```shell
conda install ultralytics -c conda-forge
```

Running the same python command now returns `False`.

**Comment by glenn-jocher** [comment]
@nadinator thanks for the bug report! I'm adding a TODO to track this. 

Another user raised a similar issue and the fix was to install ultralytics in the same line as pytorch, i.e.:
```
conda install pytorch torchvision torchaudio ultralytics pytorch-cuda=11.7 -c pytorch -c nvidia -c conda-forge
```

See https://github.com/ultralytics/ultralytics/issues/4342

**Comment by glenn-jocher** [comment]
@nadinator great news 😃! Your original issue may now be resolved ✅ in PR #4345. This PR updates the docs at https://docs.ultralytics.com/quickstart/ to recommend single-command installs of pytorch-cuda and ultralytics in CUDA environments:

<img width="1404" alt="Screenshot 2023-08-14 at 03 26 10" src="https://github.com/ultralytics/ultralytics/assets/26833433/d69b7a3e-7fae-45f0-82e9-ec714f2ea307">

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by nadinator** [comment]
This gets stuck on the "Solving Envrionment" step. Either that or my computer is very slow (being an i7 Dell, I doubt it...).

**Comment by tranmanhdat** [comment]
I got same problem as [nadinator]
(https://github.com/ultralytics/ultralytics/issues/4335#issuecomment-1678900299).
System: Ubuntu 22.04 LTS with conda, my computer is Legion 5 Pro with Nvidia Geforce RTX 3060
The install took full RAM then it was killed by system (16GB RAM).
![Screenshot from 2023-08-15 20-41-25](https://github.com/ultralytics/ultralytics/assets/30494878/bc23eaff-dd3e-48f2-afd6-7519dd506ccf)

**Comment by pderrenger** [comment]
@tranmanhdat thanks for sharing your experience! Your approach of installing pytorch with GPU support using conda first, followed by installing ultralytics with pip, is a great workaround. This method allows users to leverage the GPU capabilities while ensuring successful installation. If you encounter any other issues or have further feedback, feel free to share them here. Happy coding!

**Comment by glenn-jocher** [comment]
@pderrenger, glad to hear the pip workaround did the trick! 👍 Your feedback is invaluable, and we'll look into streamlining the conda install process. Keep us posted on your progress, and happy coding with YOLOv8! 🚀
