### ISSUE TITLE
Clarification Needed: Versioning Scheme

### ISSUE THREAD

**Issue by beyse** [ultralytics/ultralytics#4338]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Issue Description

I've been exploring this repository and its documentation, as well as going through the issues and discussions, but I couldn't find any explicit information about the versioning scheme that Ultralytics uses. I'm curious to know if the project follows semantic versioning (`MAJOR` `.` `MINOR` `.` `PATCH`) for its releases.

Could someone from the Ultralytics team kindly confirm whether the versioning scheme used for Ultralytics is indeed semantic versioning, with updates being categorized as MAJOR, MINOR, and PATCH? This clarification would be greatly appreciated and would help users like me better understand the significance of version changes.

Thank you for your time and assistance!

Best regards,
Sebastian

**Comment by mikel-brostrom** [comment]
All you need to know regarding the pypi package publishing is here:

https://github.com/ultralytics/ultralytics/blob/b5d1af42d8e34e4019a2c6c031e5fd71dde811d5/.github/workflows/publish.yml#L37-L55

and

https://github.com/ultralytics/ultralytics/blob/b5d1af42d8e34e4019a2c6c031e5fd71dde811d5/.github/workflows/publish.yml#L56-L63

But more specifically you can see here:

https://github.com/ultralytics/ultralytics/blob/b5d1af42d8e34e4019a2c6c031e5fd71dde811d5/.github/workflows/publish.yml#L49-L50

that only `PATCH` is increased by one every release. Actually the pipeline does not allow version updates of either `MAJOR` or `MINOR`

**Comment by beyse** [comment]
Certainly! Here's a suggested reply to the conversation:

---

Hi @mikel-brostrom 

Thank you for sharing the details regarding the versioning scheme Ultralytics uses. Based on the provided information and my understanding of semantic versioning (semver), here are my insights:

**Semver or Not**: 
  - Semver categorizes updates into three segments: MAJOR, MINOR, and PATCH, with the convention being:
      - MAJOR for incompatible changes that require user intervention.
      - MINOR for new features in a backward-compatible manner.
      - PATCH for backward-compatible bug fixes.
      
  - From the provided GitHub workflow, it looks like Ultralytics is incrementing only the PATCH version by 1 for every release, while the pipeline does not allow (or at least discourages) version updates for MAJOR or MINOR (`d[0] == d[1] == 0`).
    
Based on this observation, it seems that Ultralytics does not strictly follow semantic versioning.

**Observations on Bug Fixes, New Features, and Breaking Changes**:
  - From my own experience with YOLOv8, I've analyzed the git history and observed that even though only the PATCH version was being updated, there were instances where there were:
      - Bug fixes.
      - Introduction of new features.
      - And most importantly, **breaking changes**, especially concerning model compatibility. For instance, a model trained on a newer version didn't work on an older one, even though the difference was only in the patch version.
      
This behavior further underscores the deviation from the typical semver approach, where breaking changes would typically increment the MAJOR version, and new features would increment the MINOR version.

**Conclusion**:

While the approach you are using is clear and systematic, it doesn't align completely with the conventions of semantic versioning and the expectations that come with it. 

Please confirm if my assessment and conclusion is correct or if I made a mistake somewhere along my line of reasoning.


**PS: My Concern**:

My concern is, that perhaps many users, when seeing updates only in the PATCH version, would anticipate minor fixes without significant changes. They would not expect breaking changes or new feature additions,

**Comment by mikel-brostrom** [comment]
> While the approach you are using is clear and systematic, it doesn't align completely with the conventions of semantic versioning and the expectations that come with it.
> 
> Please confirm if my assessment and conclusion is correct or if I made a mistake somewhere along my line of reasoning.

Sounds right to me. Notice that this repo turned into a pypi package just a few months back, the pipelines will most certainly mature with time and resources.

**Comment by beyse** [comment]
Thank you for clarifying.

**Comment by pderrenger** [comment]
@beyse you're welcome! If you have any more questions or need further assistance, feel free to ask. 😊
