### ISSUE TITLE
how to transfer a pre-trained model to YOLOv8n.pt model

### ISSUE THREAD

**Issue by yuebaiqinghui** [ultralytics/ultralytics#4339]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to transfer a pre-trained model to YOLOv8n.pt model, I tried to add my pre-trained model’s network to this model, but it seems that the default YOLOv8n.pt model is still used during training, and my transferred model is not used.
code:
```
pretrained_model = Model(feature_dim=128) # 

state_dict = torch.load('pretrained_model.pt') 

pretrained_model.load_state_dict(state_dict)

yolo_model = YOLO('yolov8n.pt')
yolo_m = copy.deepcopy(yolo_model.model.model)

# add layers from pretrained_model‘s f  (encoder)
for name, layer in pretrained_model .f.named_children():
    yolo_model.model.model.add_module(name, layer)
yolo_model.model.model = yolo_model.model.model[:8]
for name, layer in yolo_m.named_children():
    yolo_model.model.model.add_module(str(int(name)+8), layer)

# freeze encoder
for name, param in yolo_model.model.model._modules.items():
        # names in [0-8] are the added layers
        if name in ["0", "1", "2", "3", "4", "5", "6", "7"]:
            for p in param.parameters():
                p.requires_grad = False

# train the model
yolo_model.train(data='data.yaml', epochs=100, imgsz=640, batch=64) 
```
As far as the results are concerned, my operation seems to have no effect at all, and the log also says that the model used the default model=yolov8n.pt
log:
`engine\trainer: task=detect, mode=train, model=yolov8n.pt, data=data.yaml, epochs=100, patience=50, batch=64, imgsz=640, save=True, save_period=-1, cache=False,  ..................`

**Comment by Kayzwer** [comment]
I think you should try `yolo_model = YOLO(full/path/to/your/.pt)`.

**Comment by yuebaiqinghui** [comment]
> I think you should try `yolo_model = YOLO(full/path/to/your/.pt)`.
thank you for your answer.
I have tried, but I don't know the correct method to save the modified YOLO model to my local machine. Do I need to export it to a specific format like `torchscript `or `onnx `?

**Comment by Kayzwer** [comment]
maybe [this](https://docs.ultralytics.com/modes/export/#usage-examples)  can help?

**Comment by yuebaiqinghui** [comment]
thank you, the logs indicate that my changes have taken effect, but currently, there is a negative impact. I might need to modify the yolov8.yaml file.
logs in changed model: `Transferred 4/355 items from pretrained weights`
logs in original yolov8n.pt:`Transferred 319/355 items from pretrained weights`
My modifications resulted in fewer items for transfer learning, but it's okay. I'm still in the preliminary stages of experimentation.
Next,I will modify the yolov8.yaml file

**Comment by pderrenger** [comment]
@yuebaiqinghui it's great to hear that the modifications are taking effect! Yes, modifying the `yolov8.yaml` file can further refine the configuration for your specific use case. Best of luck with your experimentation and feel free to reach out if you have any further questions!
