### ISSUE TITLE
During instance segmentation training, it seems the data loader rotated my images but didn't rotated labels

### ISSUE THREAD

**Issue by samogiisan** [ultralytics/ultralytics#434]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

as mentioned above, during training the train_batch images shows my images got rotated, but labels didn't.  Thank you.

![train_batch2](https://user-images.githubusercontent.com/95013476/212852670-091b4415-f082-4c04-a10d-a3899fb4d97b.jpg)
![train_batch0](https://user-images.githubusercontent.com/95013476/212852600-2b56308a-44bb-46e8-a221-27815cbbf680.jpg)
![train_batch1](https://user-images.githubusercontent.com/95013476/212852647-61ea0e0f-ed72-45ca-a958-a3e3c68926ea.jpg)

### Minimal Reproducible Example

yolo task=segment mode=train model=yolov8s-seg.pt epochs=300 data=custom/data.yaml

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by samogiisan** [comment]
Addition:
  on side note, I have tested the exact same dataset with yolov5 segmentation and it works perfectly fine.

Thank you, any guidance would be much appreciated.

![train_batch0](https://user-images.githubusercontent.com/95013476/213067293-d8c7ec58-828f-4f0c-a0c5-c57c0f8298d4.jpg)
![train_batch1](https://user-images.githubusercontent.com/95013476/213067301-26183a58-de53-4b66-8e8c-c37caa20a258.jpg)
![train_batch2](https://user-images.githubusercontent.com/95013476/213067317-f5108acf-c958-48f6-9610-2d1efca536ba.jpg)

**Comment by Laughing-q** [comment]
@samogiisan can you provide the hyps of augmentation? then we're able to reproduce it.

**Comment by Laughing-q** [comment]
@samogiisan ok got it, I'm able to reproduce it. I'll fix it soon.

**Comment by samogiisan** [comment]
Thank you ^^

**Comment by Laughing-q** [comment]
@samogiisan hi, I made a PR #460 to fix it. this could be merged later today.

**Comment by samogiisan** [comment]
Thank you
