### ISSUE TITLE
How to run Engine file

### ISSUE THREAD

**Issue by Manueljohnson063** [ultralytics/ultralytics#4341]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,I had created engine file using export command in YOLOv8 repo.Now i need a script to run that model for a pre saved video.I had searched a lot but didnt get please help me.

### Additional

Nil

**Comment by glenn-jocher** [comment]
@Manueljohnson063 just follow the Usage examples shown after export, i.e.

```bash
yolo predict model=path/to/your/model.engine source=path/to/your/video.mp4
```

**Comment by Manueljohnson063** [comment]
Thanks for your help.When i train a pt model with 50 samples i am able to get the detections  and segmentation masks  .But when i convert it to engine and run the same test video no detction and no segmentation masks .can you please tell what i am missing .
with this lesser number of data i trained for i got good detections in .pt model. :(

**Comment by Manueljohnson063** [comment]
Hai Sir how to run it in FP32,FP16.INT8 precisions

**Comment by Manueljohnson063** [comment]
Hai ,I have trained with 1500 images (Relation between images are high) and i have converted in to engine file but there is no detection in the output video.Please help me.But the detections are proper in the pt model .After conversion detections are gone.

**Comment by glenn-jocher** [comment]
@Manueljohnson063 hello! If you're experiencing issues with detection or segmentation when using the `.engine` file compared to the `.pt` file, it's possible that there might be a discrepancy between how the model was trained and how the TensorRT engine is optimized. Here are a few things to check:

1. Ensure that the data preprocessing and postprocessing steps are consistent between training and inference.
2. Verify if there are any optimizations or precision changes during the export that could affect the performance of the model on specific hardware. Converting to FP16 or INT8 can result in loss of accuracy if not calibrated correctly.
3. Make sure you're using the correct command line arguments for your model and source when you predict with the engine file.

Regarding running the model in different precisions (FP32, FP16, INT8), this is typically handled during the export process to a TensorRT engine file.

For FP32 and FP16 precision, you can specify the precision during the export using the appropriate flag. INT8 precision usually requires a calibration step to maintain accuracy, and you would also need a representative calibration dataset. The exact commands should be outlined in our documentation.

Keep in mind that support for various precisions and their implementation details might vary depending on the version of the software and the capabilities of the hardware you are using. Always refer to the Ultralytics documentation for the latest and most accurate instructions on how to do this. If there are specific flags or a process for running models in different precisions, our documentation will provide that information.

**Comment by uniquadev** [comment]
> @Manueljohnson063 just follow the Usage examples shown after export, i.e.
> 
> ```shell
> yolo predict model=path/to/your/model.engine source=path/to/your/video.mp4
> ```

How can I perform a prediction from python?
I tried loading and running the model like so:
```py
model = YOLO(CURRENT_PATH, task='detect').cuda(0) # CURRENT_PATH=best.engine
...
model.predict(
    source=cimg,
    # settings
    verbose=False,
    conf=0.40,
    classes=[1],
    max_det=10,
    amp=True,
    imgsz=736,
    device=torch.device('cuda:0')
)[0]
```
However I get the following typeerror:
```
TypeError: model='C:\Repository\epic\model/bestv8.engine' should be a *.pt PyTorch model to run this method, but is a different format. PyTorch models can train, val, predict and export, i.e. 'model.train(data=...)', but exported formats like ONNX, TensorRT etc. only support 'predict' and 'val' modes, i.e. 'yolo predict model=yolov8n.onnx'.
To run CUDA or MPS inference please pass the device argument directly in your inference command, i.e. 'model.predict(source=..., device=0)'
```
