### ISSUE TITLE
Anaconda Specifications Unsatisfiable

### ISSUE THREAD

**Issue by dawson-friesenhahn** [ultralytics/ultralytics#4342]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm struggling to get up to get spun up using yolov8. I'm attempting to follow the [Quickstart Guide](https://docs.ultralytics.com/quickstart/).

1. Create and activate a new environment
`conda create -n yolov8`
`conda activate yolov8`

2. Install Pytorch following instructions [here.](https://pytorch.org/get-started/locally/)

`conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia `

3. Install ultralytics

`conda install -c conda-forge ultralytics`

This fails with the following output: 

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - certifi -> python[version='3.10.*|3.7.*|3.9.*|3.8.*']
  - networkx -> python[version='>=3.7.1,<3.8.0a0']
  - pytorch -> python[version='*|2.7.*|3.5.*|3.6.*|3.6.12|3.6.12|3.7.10|3.7.10|3.7.12|3.8.12|3.8.16|3.9.16|3.9.10|3.7.9|3.6.9|3.6.9|3.6.9|>=2.7,<2.8.0a0|3.6.9|>=3.5,<3.6.0a0|3.4.*|>=3.7|>=3.6|>=3.5|>=3.8',build='*_cpython|0_73_pypy|1_73_pypy|2_73_pypy|0_73_pypy|1_73_pypy|0_73_pypy|5_73_pypy|5_73_pypy|4_73_pypy|3_73_pypy']
  - torchaudio -> python[version='>=3.10,<3.11.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']

Your python: python=3.11

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (pytorch-cuda):

  - ultralytics -> pytorch[version='>=1.7.0'] -> pytorch-cuda[version='11.8.*|>=11.8,<11.9']
  - ultralytics -> torchvision[version='>=0.8.1'] -> pytorch[version='1.10.2|2.0.1']

I tried fixing this problem by manually specifying python=3.7.1 at environment creation and then repeating the steps, but I end up just playing whack-a-mole and introducing more unsatisfiable requirements. 

Can someone point me in the right direction?

**Comment by glenn-jocher** [comment]
@dawson-friesenhahn thanks for the bug report! I use pip myself, but I've been trying to create Conda CI to install and test it in https://github.com/glenn-jocher/ultralytics/pull/5/files, without luck so far. 

One good idea might be to try to merge your steps 2 and 3 into the same step to allow the Conda installer to resolve any conflicts within the same command.

**Comment by dawson-friesenhahn** [comment]
@glenn-jocher That worked a treat!

In a brand new conda environment, I ran

`conda install pytorch torchvision torchaudio ultralytics pytorch-cuda=11.8 -c pytorch -c nvidia -c conda-forge`

And I was off to the races. Thanks so much.

**Comment by glenn-jocher** [comment]
@dawson-friesenhahn great news 😃! Your original issue may now be resolved ✅ in PR #4345. This PR updates the docs at https://docs.ultralytics.com/quickstart/ to recommend single-command installs of pytorch-cuda and ultralytics in CUDA environments:

<img width="1404" alt="Screenshot 2023-08-14 at 03 26 10" src="https://github.com/ultralytics/ultralytics/assets/26833433/d69b7a3e-7fae-45f0-82e9-ec714f2ea307">

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!
