### ISSUE TITLE
'imgsz=640' this parameter does not work during validation

### ISSUE THREAD

**Issue by cl886699** [ultralytics/ultralytics#4346]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Validation

### Bug

When I used imgsz=1280 to train the model, I found that setting imgsz=640 did not work during validation, the problem is in line 292 of ultralytics/engine/model.py

>         if args.imgsz == DEFAULT_CFG.imgsz and not isinstance(self.model, (str, Path)):
Changing the code to this will solve this problem

>         if 'imgsz' not in overrides and not isinstance(self.model, (str, Path)):

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Kayzwer** [comment]
@cl886699 ofc, if your model trained with 1280 imgsz, it wont work for other size (img resized process will be done automatically in ultralytics code).

**Comment by cl886699** [comment]
@Kayzwer No matter what size imgsz training model I use, when validation, as long as the new imgsz is passed, it should be evaluated according to the new imgsz I set.
When using 1280 for training and 640 for evaluation, only the accuracy will be reduced, but it should not be a logical error in the code.

**Comment by cl886699** [comment]
@glenn-jocher That's right, when training use other imgsz， only pass imgsz=640 can not override when validation
