### ISSUE TITLE
Can you add FPS function and customize frame skipping detection video?

### ISSUE THREAD

**Issue by stphtan94117** [ultralytics/ultralytics#435]
HI, sir
I'm currently detecting very complex scenes, but the computer is not good enough. 

Therefore, when detecting video, do not process every frame. 
It may be possible to customize the function of every 10 frames or 30 frames, and the current detected FPS can be displayed in real time in the video.

Hope it can be added in yolov5 or yolov8

**Comment by s4ki3f** [comment]
you can check some options in caping and adjusting fps in detection. 
you may add additional functions like this from the OpenCV library 
` cv2.putText(frame, "FPS: {}".format(fps), (10, 30),
                cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
`
and to show 
` cv2.imshow("YOLOv5 Detection", frame)`

Correct me if I am wrong.. I am interested in this too

**Comment by AyushExel** [comment]
@stphtan94117 you can customize anything in this framework. You can create a custom predictor class inheriting from basePredictor and customize what data is being inferred and what is being skipped. But it might not be a small change. I'll add this as a feature request and support it directly in the repo in future.
Example of trainer customization - https://docs.ultralytics.com/engine/
