### ISSUE TITLE
How to continue training after completion?

### ISSUE THREAD

**Issue by yuebaiqinghui** [ultralytics/ultralytics#4352]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I completed 100 epochs of training, and I feel that I haven't achieved the best results yet. Therefore, I want to continue training. I have tried two methods.
1：
```
yolo_model = YOLO('last.pt')
yolo_model.train(data='data.yaml', epochs=200, imgsz=640, batch=64, workers=0, resume=True) 
```
but it tells me: `AssertionError: last.pt training to 100 epochs is finished, nothing to resume.`

2：
```
yolo_model = YOLO('last.pt')
yolo_model.train(data='data.yaml', epochs=100, imgsz=640, batch=64, workers=0) 
```
I used "last.pt" as the pretrained model and trained for another 100 epochs instead of resuming training. It did indeed train, but overfitting occurred from the first epoch onwards. The loss values were higher than what I had before, and they kept increasing throughout the later training stages.

How do I continue training using the right method?

**Comment by aypetrunin** [comment]
@glenn-jocher, HI! Tell me why you need the "pretrained" parameter? I made the assumption that it is needed just to continue learning if it is set to True.

yolo_model = YOLO('last.pt')
yolo_model.train(data='data.yaml', epochs=100, imgsz=640, batch=64, workers=0, pretrained=True)

**Comment by tarensanders** [comment]
I just want to point out that method 1 above does seem to align with the docs. Specifically:
https://github.com/ultralytics/ultralytics/blob/c7ceb84fb6085e767ed664460cd6abec9ced86d8/docs/modes/train.md?plain=1#L106

> or when you wish to continue training a model with new data or for more epochs

makes it sound like you should be able to resume a model to add additional epochs.

**Comment by glenn-jocher** [comment]
@tarensanders yes, you are correct, the documentation does imply that you can resume training to add additional epochs to an already trained model. However, in the current YOLOv8 implementation, once a model has finished training to the specified number of epochs, the resume function assumes there is nothing more to train and hence raises an AssertionError. A potential workaround is to start a new training but load the weights from the finished model without using the resume parameter, this is essential to avoid resetting the optimizer and the learning rate scheduler. But be mindful of overfitting when adding more epochs. We'll certainly consider clarifying this in our documentation to avoid any confusion. Thank you for pointing it out!

**Comment by yescine** [comment]
@glenn-jocher any fix for resuming v8 model training for the next release ultralytics8.2 ? ( why wasting hours of training while we could simply resume ?!)

**Comment by glenn-jocher** [comment]
Hi @yescine,

Thank you for your feedback! We understand the importance of being able to resume training seamlessly to avoid wasting valuable training time. The current behavior of the `resume` parameter is designed to prevent unintended continuation of training beyond the specified epochs. However, we recognize the need for more flexibility in this area.

For now, you can continue training by loading the weights from your previously trained model and starting a new training session without the `resume` parameter. Here's a quick example:

```python
from ultralytics import YOLO

# Load the model with the previously trained weights
model = YOLO('last.pt')

# Continue training for additional epochs
model.train(data='data.yaml', epochs=200, imgsz=640, batch=64, workers=0)
```

This approach will allow you to extend your training while retaining the learned weights. Be mindful of potential overfitting and adjust your hyperparameters as needed.

We appreciate your patience and will consider enhancing the `resume` functionality in future releases to better support extended training sessions. If you encounter any issues or have further suggestions, please let us know!

**Comment by jeremy-rutman** [comment]
A drawback of the suggested approach 
```
model = YOLO('last.pt')
model.train(data='data.yaml', epochs=200, imgsz=640, batch=64, workers=0)
```
is that, if I understand correctly, the training 'experience' gained e.g. by various backpropagation methods is now lost by not using 'resume', and the model will start from the trained weights, but from scratch with respect to the training experience. As another example learning rates will be reset as well. In practice, what i see is an immediate drop in performance when using this method and very gradual increase, when just before epoch 100 everything was improving steadily.  Is there a way to lift the training information (current learning rates, and training algorithm parameter values) from last.pt ?

**Comment by glenn-jocher** [comment]
Thanks for the follow‑up @PaulV74 and @jeremy-rutman.  

Your understanding is right: starting a fresh `train()` from `last.pt` will reuse the weights but reinitialize the optimizer, LR scheduler, etc.; only `resume=True` restores the full training state (optimizer, scaler, EMA, best fitness) saved in the checkpoint. At the moment, `resume` is intended for interrupted runs and doesn’t officially support “add more epochs after a fully completed run” while keeping that optimizer state, so there isn’t a simple one‑liner for that use case. If you really need it, the advanced option is to `torch.load("last.pt")` and reuse `ckpt["optimizer"]` (and related keys) in your own custom trainer, but that’s outside the stable public API. For now the recommended workflows are to either resume an interrupted run with `resume=True` or start a new fine‑tune from the saved weights with new hyperparameters. If you’d like extended‑resume to be a first‑class feature, please open a new feature request referencing this issue so we can track it. The current behavior and examples are summarized in the [Train mode documentation](https://docs.ultralytics.com/modes/train/).

**Comment by jeremy-rutman** [comment]
This seems to work to get more training beyond initial epochs:


```
# continue_trainer.py
from ultralytics.models.yolo.detect import DetectionTrainer
from ultralytics.utils import LOGGER


class ContinueTrainer(DetectionTrainer):
    """
    Custom trainer that lets you keep training from a completed checkpoint
    avoiding 'training ... is finished, nothing to resume').

  For models with any epochs done already (this being called last_epoch) and `resume=True`:
          - If `epochs` <= last_epoch, we interpret `epochs` as "extra epochs".
            Example: last_epoch=100, epochs=50 -> train to epoch 150 
          - If `epochs` > last_epoch, it behaves like the default trainer:
            resume until total epochs == `epochs`.

      * If the checkpoint has epoch < 0 ( “finished” model):
          - this wont work since the optimizer stuff is stripped, use a full checkpoint
    """

    def resume_training(self, ckpt):
        if ckpt is None or not self.resume:
            return

        last_epoch = ckpt.get("epoch", -1)  # -1 on stripped/final checkpoints
        start_epoch = last_epoch + 1        # 0 if last_epoch == -1

        if last_epoch < 0:
            # "final" checkpoint with optimizer stripped
            LOGGER.info(
                f"Checkpoint has no usable epoch info (epoch={last_epoch}). "
                f"Fine-tuning {self.args.model} for {self.epochs} epochs from provided weights."
            )
        else:
            # Normal resume logic, but allow 'epochs' to mean "extra epochs"
            if self.epochs <= last_epoch:
                extra = self.epochs
                self.epochs = last_epoch + 1 + extra
                LOGGER.info(
                    f"Extending training of {self.args.model}: "
                    f"previously trained to epoch {last_epoch}, "
                    f"running {extra} more epochs (total {self.epochs})."
                )
            else:
                LOGGER.info(
                    f"Resuming training {self.args.model} from epoch {start_epoch} "
                    f"to {self.epochs} total epochs."
                )

        # Load model / EMA / optimizer if present (optimizer may be missing in stripped ckpts)
        self._load_checkpoint_state(ckpt)
        self.start_epoch = start_epoch

        # Respect mosaic closing logic from BaseTrainer
        if start_epoch > (self.epochs - self.args.close_mosaic):
            self._close_dataloader_mosaic()

```

**Comment by glenn-jocher** [comment]
This looks like a reasonable way to extend training while keeping the optimizer/LR state, and your `epoch < 0` branch is exactly what’s needed for stripped checkpoints where optimizer info is gone. Just make sure you always resume from a full checkpoint like `last.pt` (not a `strip_optimizer`‑processed file) and are aware that internal checkpoint keys may change between versions, so this pattern is best treated as an advanced/custom solution. If you’d like to upstream this behavior, you can wrap it as a minimal change to `BaseTrainer.resume_training()` with tests and open a focused PR, following the custom‑trainer patterns in the [advanced customization guide](https://docs.ultralytics.com/usage/engine/).
