### ISSUE TITLE
i want to save the dataset after augmentation  

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/ultralytics#4356]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i have request , i want to save the dataset after augmentation

**Comment by glenn-jocher** [comment]
@VYRION-Ai hi, thank you for your feature suggestion on how to improve YOLO 🚀!

This feature is not currently available, however the fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
