### ISSUE TITLE
Some thoughts on YOLOv8 CLI

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/ultralytics#4361]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

@glenn-jocher 
I am studying the technology of YOLOv8 CLI, where is the CLI program like `yolo predict` in the source code? How can I change it?

![image](https://github.com/ultralytics/ultralytics/assets/41098760/9121aef3-9e66-4109-899b-3df3bea238dd)

**Comment by glenn-jocher** [comment]
@Zengyf-CVer all of the CLI parsing is handled here:
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/__init__.py
