### ISSUE TITLE
Possibly a tiny typo in `utils/ops::non_max_supression` docstring

### ISSUE THREAD

**Issue by sadra-barikbin** [ultralytics/ultralytics#4367]
Hi, In `non_max_supression` docstring, the prediction is described to be as `(batch_size, num_classes + 4 + num_masks, num_boxes)`, while from the code it turns out that it actually is `(batch_size, 4 + num_classes + num_masks, num_boxes) `, i.e. the 4 bbox coordinates come before class probabilities.

https://github.com/ultralytics/ultralytics/blob/4093c1fd64edd00fccb5a424a6dc7df6917b89cd/ultralytics/utils/ops.py#L166

**Comment by pderrenger** [comment]
@sadra-barikbin hi there! 🌟 Thank you for bringing this to our attention. We appreciate your diligence in examining the documentation. We'll review the `non_max_supression` docstring to ensure the accurate description of the prediction format as `(batch_size, 4 + num_classes + num_masks, num_boxes)`. Your contribution helps maintain the clarity and correctness of the documentation. If you have any further questions or observations, please feel free to share them!
