### ISSUE TITLE
export RT-DETR in onnx format with opset=12

### ISSUE THREAD

**Issue by Sujie1528** [ultralytics/ultralytics#4371]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm using the code shown in the below image to export RT-DETR in onnx format. The function exports the model using onnx opset=17. But a later step requires opset=12 (hard requirement). So how do I export using opset=12? 

I could expect another problem when exporting with opset=12: the model involves grid_sample operation which is not supported in onnx opset=12. How do I bypass this?
Thanks in advance!
![nPBtiV1QcB](https://github.com/ultralytics/ultralytics/assets/63102146/99cca7a6-b234-4f89-8de4-706effa3ca14)

**Comment by Johan154** [comment]
You can simply add it to your line of code that you used for export: model.export(format="onnx", opset=12)

**Comment by Sujie1528** [comment]
> You can simply add it to your line of code that you used for export: model.export(format="onnx", opset=12)

Thank you very much for your answer. When I export with opset=12, I got the following error.
![mVUoxTPd7c](https://github.com/ultralytics/ultralytics/assets/63102146/0dfa20cf-d3a9-4154-8362-864dfbd655a8)

**Comment by MarkXCloud** [comment]
> > You can simply add it to your line of code that you used for export: model.export(format="onnx", opset=12)
> 
> Thank you very much for your answer. When I export with opset=12, I got the following error. ![mVUoxTPd7c](https://user-images.githubusercontent.com/63102146/260887506-0dfa20cf-d3a9-4154-8362-864dfbd655a8.jpg)

The `grid_sample` in `torch.nn.funcitonal` is quite new for ONNX opset version 12, so onnx can't directly export this func. 
The `grid_sample` function is used under https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/modules/utils.py#L65:
```python
def multi_scale_deformable_attn_pytorch(value: torch.Tensor, value_spatial_shapes: torch.Tensor,
                                        sampling_locations: torch.Tensor,
                                        attention_weights: torch.Tensor) -> torch.Tensor:
    """
    Multi-scale deformable attention.
    https://github.com/IDEA-Research/detrex/blob/main/detrex/layers/multi_scale_deform_attn.py
    """

    bs, _, num_heads, embed_dims = value.shape
    _, num_queries, num_heads, num_levels, num_points, _ = sampling_locations.shape
    value_list = value.split([H_ * W_ for H_, W_ in value_spatial_shapes], dim=1)
    sampling_grids = 2 * sampling_locations - 1
    sampling_value_list = []
    for level, (H_, W_) in enumerate(value_spatial_shapes):
        # bs, H_*W_, num_heads, embed_dims ->
        # bs, H_*W_, num_heads*embed_dims ->
        # bs, num_heads*embed_dims, H_*W_ ->
        # bs*num_heads, embed_dims, H_, W_
        value_l_ = (value_list[level].flatten(2).transpose(1, 2).reshape(bs * num_heads, embed_dims, H_, W_))
        # bs, num_queries, num_heads, num_points, 2 ->
        # bs, num_heads, num_queries, num_points, 2 ->
        # bs*num_heads, num_queries, num_points, 2
        sampling_grid_l_ = sampling_grids[:, :, :, level].transpose(1, 2).flatten(0, 1)
        # bs*num_heads, embed_dims, num_queries, num_points
------->sampling_value_l_ = F.grid_sample(value_l_,
                                          sampling_grid_l_,
                                          mode='bilinear',
                                          padding_mode='zeros',
                                          align_corners=False)
        sampling_value_list.append(sampling_value_l_)
    # (bs, num_queries, num_heads, num_levels, num_points) ->
    # (bs, num_heads, num_queries, num_levels, num_points) ->
    # (bs, num_heads, 1, num_queries, num_levels*num_points)
    attention_weights = attention_weights.transpose(1, 2).reshape(bs * num_heads, 1, num_queries,
                                                                  num_levels * num_points)
    output = ((torch.stack(sampling_value_list, dim=-2).flatten(-2) * attention_weights).sum(-1).view(
        bs, num_heads * embed_dims, num_queries))
    return output.transpose(1, 2).contiguous()
```

And the code above is used along the way on 
`MSDeformAttn`([transformer.py](https://github.com/ultralytics/ultralytics/blob/9a0555eca477d98cf044c698cb0e9803030441a6/ultralytics/nn/modules/transformer.py#L191C17-L191C17))
↓
`DeformableTransformerDecoderLayer`([transformer.py](https://github.com/ultralytics/ultralytics/blob/9a0555eca477d98cf044c698cb0e9803030441a6/ultralytics/nn/modules/transformer.py#L277))
↓
`RTDETRDecoder`([head.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/modules/head.py#L170)). 
Consequently ONNX opset version 12 can't export rt-detr directly.
One possible way to handle this is replace `F.grid_sample()` by another piece of pure python/torch code, such as grid sample in [mmcv](https://github.com/open-mmlab/mmcv/blob/main/mmcv/ops/point_sample.py#L12). Due to no params in these funcs, replacement shall not force you to train your network form scratch, and you can still load your trained model weights, so try it and hope it will help.

**Comment by pderrenger** [comment]
@MarkXCloud it seems that the `grid_sample` function used in the code is not directly supported by the ONNX opset version 12. As a result, you encountered an error when trying to export the model.

To overcome this issue, one possible approach is to replace `F.grid_sample()` with another piece of pure python/torch code, such as the grid sample function in [mmcv](https://github.com/open-mmlab/mmcv/blob/main/mmcv/ops/point_sample.py#L12). This replacement should not require you to train your network from scratch, allowing you to still load your trained model weights.

I suggest giving this approach a try, and hopefully, it will help resolve the export issue. Let me know if you encounter any further difficulties!

**Comment by vika-ts** [comment]
@pderrenger I updated grid_sample function in the functional.py file by [bilinear_grid_sample function](https://github.com/open-mmlab/mmcv/blob/main/mmcv/ops/point_sample.py#L12) function. I got the error related with size: _view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead._
Maybe you have an idea of how to fix this or you have another idea on how to convert the model with opset=12

**Comment by Noah2018** [comment]
@MarkXCloud Hi, I tried your suggestion and replaced the grid_sample in utils.py, then I export the onnx model based on the pre-trained model, for example, rtdetr-l.pt, it seems like this utils.py file wasn't used during the onnx conversion.
here is the example code of my export process:
`from ultralytics import RTDETR

if __name__ == "__main__":
    model = RTDETR(
        "./runs/detect/train28/weights/best.pt"
    ) 
    # model.export(format="onnx", imgsz=640, opset=16, dynamic=False, simplify=True)
    model.export(format="onnx", imgsz=640, opset=16)`
after the conversion, grid_sample op still exists in the onnx model, could you explain why is that, thx in advance
