### ISSUE TITLE
get name class in classify

### ISSUE THREAD

**Issue by chelsea456** [ultralytics/ultralytics#4372]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

from ultralytics import YOLO

model = YOLO('f:\yolov8\\ultralytics\\runs\classify\\train4\weights\\best.pt')
result = model("F:\yolov8\\ultralytics\\TRAIN_CLS\\train\start\\577.png")[0]
print(result)
i want to get name class

**Comment by Kayzwer** [comment]
@chelsea456 you can get the top 1 obj prob with `print(result.names[result.probs.top1])`
