### ISSUE TITLE
Error occured while converting yolov8x (mode - detect) to tflite model with int8 quantization

### ISSUE THREAD

**Issue by saikiranvarmaJSN** [ultralytics/ultralytics#4375]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

faced error `OSError: SavedModel file does not exist at: yolov8x_saved_model/{saved_model.pbtxt|saved_model.pb}` while converting yolov8x pretrained model to tflite model with int8 quantization. This int8 quantization works good for all models except yolov8x. could someone help me out here?

**Screenshot**
![colab_tflite_problem](https://github.com/ultralytics/ultralytics/assets/89576203/005cddf4-d742-4d7d-ac95-2ae4a751e30c)

### Environment

1. used colab to exporting model.
2. installed ultralytics using pip command. `pip install ultralytics==8.0.154`

### Minimal Reproducible Example

from ultralytics import YOLO

# Load a model
model = YOLO('yolov8x.pt')  # pretrained YOLOv8n model

model.export(format='tflite',int8=True)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hlreicha** [comment]
Which TensorFlow version are you using? I had more success with TensorFlow versions 2.10 or higher.

**Comment by glenn-jocher** [comment]
@hlreicha hello, thank you for reaching out. The error you encountered might be due to the TensorFlow version you're currently using. To perform int8 quantization with YOLOv8, it's preferred to use TensorFlow version 2.10 or higher, as this version introduced fixes and features that enhanced the model conversion process, especially regarding different quantization strategies. If you're using a lower version, please consider upgrading to TensorFlow 2.10 or later. Check your TensorFlow version via Python with `import tensorflow as tf; print(tf.__version__)`. I hope this will help address your issue, but don't hesitate to provide more details if you're still having trouble.

**Comment by HYSzuibai** [comment]
> @hlreicha hello, thank you for reaching out. The error you encountered might be due to the TensorFlow version you're currently using. To perform int8 quantization with YOLOv8, it's preferred to use TensorFlow version 2.10 or higher, as this version introduced fixes and features that enhanced the model conversion process, especially regarding different quantization strategies. If you're using a lower version, please consider upgrading to TensorFlow 2.10 or later. Check your TensorFlow version via Python with `import tensorflow as tf; print(tf.__version__)`. I hope this will help address your issue, but don't hesitate to provide more details if you're still having trouble.

Hi, I recently encountered the same error as him, and my tensorflow version is 2.13.0, and int8 is False


Ultralytics YOLOv8.0.196  Python-3.8.18 torch-1.10.0+cu102 CPU (Intel Core(TM) i7-8750H 2.20GHz)
YOLOv8-FasterNet-cls summary: 94 layers, 200044 parameters, 0 gradients, 0.4 GFLOPs

PyTorch: starting from 'runs\classify\train3\weights\best.pt' with input shape (1, 3, 224, 224) BCHW and output shape(s) (1, 4) (0.4 MB)
requirements: Ultralytics requirements ['onnx2tf>=1.15.4,<=1.17.5', 'onnx_graphsurgeon>=0.3.26', 'tflite_support'] not found, attempting AutoUpdate...
Unable to create process using 'F:\shijue\python.exe F:\shijue\Scripts\pip-script.py install --no-cache "onnx2tf>=1.15.4,<=1.17.5" "onnx_graphsurgeon>=0.3.26" "tflite_support" --extra-index-url https://pypi.ngc.nvidia.com'
requirements:  Command 'pip install --no-cache "onnx2tf>=1.15.4,<=1.17.5" "onnx_graphsurgeon>=0.3.26" "tflite_support" --extra-index-url https://pypi.ngc.nvidia.com' returned non-zero exit status 101.

TensorFlow SavedModel: starting export with tensorflow 2.13.0...

ONNX: starting export with onnx 1.16.0 opset 13...
ONNX: simplifying with onnxsim 0.4.36...
ONNX: export success  0.9s, saved as 'runs\classify\train3\weights\best.onnx' (0.8 MB)
TensorFlow SavedModel: running 'onnx2tf -i "runs\classify\train3\weights\best.onnx" -o "runs\classify\train3\weights\best_saved_model" -nuo --non_verbose'
'onnx2tf' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
TensorFlow SavedModel: export failure  4.7s: SavedModel file does not exist at: runs\classify\train3\weights\best_saved_model\{saved_model.pbtxt|saved_model.pb}
Traceback (most recent call last):
  File "F:\YOLO-V8\V8 Gai Jin\Network structure\ultralytics-All\ONNX导出.py", line 7, in <module>
    success = model.export(format="tflite", simplify=True)
  File "F:\YOLO-V8\V8 Gai Jin\Network structure\ultralytics-All\ultralytics\engine\model.py", line 313, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "F:\ENV\V8\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "F:\YOLO-V8\V8 Gai Jin\Network structure\ultralytics-All\ultralytics\engine\exporter.py", line 261, in __call__
    f[5], keras_model = self.export_saved_model()
  File "F:\YOLO-V8\V8 Gai Jin\Network structure\ultralytics-All\ultralytics\engine\exporter.py", line 122, in outer_func
    raise e
  File "F:\YOLO-V8\V8 Gai Jin\Network structure\ultralytics-All\ultralytics\engine\exporter.py", line 117, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "F:\YOLO-V8\V8 Gai Jin\Network structure\ultralytics-All\ultralytics\engine\exporter.py", line 712, in export_saved_model
    return str(f), tf.saved_model.load(f, tags=None, options=None)  # load saved_model as Keras model
  File "F:\ENV\V8\lib\site-packages\tensorflow\python\saved_model\load.py", line 858, in load
    result = load_partial(export_dir, None, tags, options)["root"]
  File "F:\ENV\V8\lib\site-packages\tensorflow\python\saved_model\load.py", line 963, in load_partial
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "F:\ENV\V8\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 58, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
  File "F:\ENV\V8\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 116, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: runs\classify\train3\weights\best_saved_model\{saved_model.pbtxt|saved_model.pb}
