### ISSUE TITLE
All instances assigned to one class

### ISSUE THREAD

**Issue by Sapf3ar** [ultralytics/ultralytics#4379]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Other

### Bug

![image](https://github.com/ultralytics/ultralytics/assets/66119364/9ced4cf3-a89f-456f-b906-9d7316d3e6d0)
Issue occurs on dataset : https://universe.roboflow.com/public-workspace-8btg0/odometer-gom4y
Labels are correct, multiple classes

### Environment

Ultralytics YOLOv8.0.154 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB)

**Comment by glenn-jocher** [comment]
@Sapf3ar detection datasets should follow the YOLO dataset format described in https://docs.ultralytics.com/datasets/detect/

If your Roboflow dataset is not exporting correctly in this format then you should ask Roboflow for support on the issue.

**Comment by Sapf3ar** [comment]
example of file in train/labels.txt:
![image](https://github.com/ultralytics/ultralytics/assets/66119364/a6905578-2d10-4e4a-bb5c-034750d18569)
All instances are assigned to class named first in "names" filed in data.yaml
Issue persists among different datasets 
data.yaml: 
![image](https://github.com/ultralytics/ultralytics/assets/66119364/7fc43d38-dcb0-4da6-853d-b71e306317ed)

**Comment by Sapf3ar** [comment]
It was a single_cls parameter

**Comment by glenn-jocher** [comment]
@Sapf3ar thank you for sharing the additional details.

The `single_cls` parameter in the dataset configuration (`data.yaml`) is set to `True` might be causing this scenario. This parameter, when set to `True`, considers all instances as a single class during training, regardless of the actual number of classes. In other words, even if your labels have multiple classes, the model will interpret all of them as belonging to a single class.

Please ensure that `single_cls` is set to `False` if you have multiple classes in your dataset and you want each to be trained as a separate class.

If you are still facing the issue after ensuring the correct setting of the `single_cls` parameter, please share more details about your training procedure, we're here to help!
