### ISSUE TITLE
Problem with "setting.yaml" not working in class Settings Manager

### ISSUE THREAD

**Issue by dxt117** [ultralytics/ultralytics#4380]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I got the ultralytics project in a different directory on the same computer. After the detection is performed on the first project, it can be output correctly under "runs" in the current project directory. However, when the detection is run on the second project, the detect results are also output to the runs of the first project. After looking at the source code, I found that a local configuration file 'setting.yaml' is loaded,And it has associated configuration file update operations.and when I deleted this file, the second project could be correctly output to the project path. But the same problem occurs when executing the first project. Or maybe there's something wrong with my computer.
![image](https://github.com/ultralytics/ultralytics/assets/101740114/5b5045fe-8f16-4b71-accc-987f3becc394)

**Comment by pderrenger** [comment]
@dxt117 it sounds like you are experiencing issues with the `setting.yaml` file not working as expected when running detection on multiple projects in different directories. 🤔

The `setting.yaml` file is responsible for managing the local configuration, and it seems that the file's association with the project directories might be causing the detect results to be output to the wrong directory.

It's interesting that deleting the `setting.yaml` file allows the second project to output correctly, but then the same issue occurs when executing the first project. This suggests that the `setting.yaml` file might be overwriting the configurations for the project directories.

To troubleshoot this, you might want to check if there are any absolute paths or conflicting configurations in the `setting.yaml` file that could be causing the issue. Additionally, ensure that the file is being loaded and updated correctly for each project.

It's important to note that the behavior you're encountering doesn't seem to be the standard functionality of YOLOv8, so it might be worth verifying that there are no environmental or permission-related factors on your machine that could be contributing to this behavior.

Feel free to share more details about the contents of the `setting.yaml` file or any specific configurations you've set up. This could help in diagnosing the issue more accurately and providing an effective solution.

**Comment by glenn-jocher** [comment]
Hi @pderrenger, it seems like the `setting.yaml` file is not correctly isolating configurations between your projects. 🛠️

The `setting.yaml` is designed to store local configurations, but it should not cause cross-project interference. If deleting the file temporarily resolves the issue for one project but then affects the other, it's likely that there's a conflict or shared setting that's not project-specific.

Please ensure that each project's `setting.yaml` contains the correct relative paths and that there are no absolute paths that might be redirecting outputs to a single location. Also, check for any permissions issues that might prevent the creation of a new `setting.yaml` in each project directory.

If the problem persists, consider isolating the projects further or manually specifying the output directories as needed. For more detailed guidance on managing settings, you can refer to our documentation.

Let us know if this helps or if you have any more information that could aid in troubleshooting. Good luck! 🍀
