### ISSUE TITLE
How to get accuracy/score per image

### ISSUE THREAD

**Issue by magedhelmy1** [ultralytics/ultralytics#4382]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Currently, when you do model.val(), you get the score with the whole dataset. Is it possible to get it per image?
I want to identify the lowest scoring images.

**Comment by glenn-jocher** [comment]
@magedhelmy1 hi, thank you for your feature suggestion on how to improve YOLO 🚀! 

This feature is not currently available, however the fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
