### ISSUE TITLE
Changing the color of the bounding boxes.

### ISSUE THREAD

**Issue by aminrezaabbasi** [ultralytics/ultralytics#4384]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi there, I trained my model by using Ultralytics hub, right now, when I want to check whether my object detection model works accurate or not, I should review my test images, when I'm looking at them, all the bounding boxes around the wheat heads are yellow, and my pictures backgrounds are mostly yellow. so its kinda hard to see the bounding boxes, is there any way to change the color of the bounding boxes? I attach the screenshot for a better understanding of my question.

### Additional

![image](https://github.com/ultralytics/ultralytics/assets/96463416/f4590819-fe11-4ea3-942f-c0db8a1e453c)

**Comment by waholulu** [comment]
same question!

**Comment by pderrenger** [comment]
@waholulu you can change the color of the bounding boxes by editing the `colors.txt` file in the YOLOv8 repository. Each line in the `colors.txt` file represents a different color in the format `R,G,B`. Just modify the RGB values of the color you want to use for the bounding boxes, and then restart the inference to see the updated colors in your predictions.
