### ISSUE TITLE
Problem with GPU setting

### ISSUE THREAD

**Issue by lovelylightningbug** [ultralytics/ultralytics#4385]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Can only run the yolo model on Cuda:0, cann't switch to other gpus using "device" parameter in simple inference code.

model = YOLO('./weights/FastSAM.pt')
results = model(input,
                    device=device,
                    retina_masks=True,
                    iou=iou_threshold,
                    conf=conf_threshold,
                    imgsz=input_size,)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AlexanderNevarko** [comment]
I am suffering from the same issue. I've made a little workaround and found out that:
1) One should call method .to(device) to put your model to a specified cuda device
2) Even if you do so, the code still does not see any preloaded weights when you call __call__ method and it reinitialize the model, choosing the device automatically to "cuda:0".

**Comment by lovelylightningbug** [comment]
Hi, I figured out the issue
you can set 'device="1",' or 'device="0,1,2,3" instead of 'device="cuda:1"'

**Comment by pderrenger** [comment]
@lovelylightningbug thanks for sharing your findings! You can indeed set the 'device' parameter to '1' for a single GPU or '0,1,2,3' for multiple GPUs to specify which GPU(s) to use for inference. After setting the 'device' parameter, calling the .to(device) method on the model will ensure that the model is placed on the specified device(s) for inference. Let me know if you need further assistance!
