### ISSUE TITLE
Input format for non_max_supression function in ultralytics.utils.ops

### ISSUE THREAD

**Issue by Ahmed-Radwan094** [ultralytics/ultralytics#4386]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, In non_max_supression docstring, the prediction is described to be as (batch_size, num_classes + 4 + num_masks, num_boxes). It is unclear to me how to convert from the results generated by a detection model in prediction mode to the required format of non_max_supression. I am using a tensorRT saved weights and that is why I am trying to use non_max_supression as a post processing process.

**Comment by pderrenger** [comment]
@Ahmed-Radwan094 hi there! The non_max_supression function in ultralytics.utils.ops operates on predictions in the format (batch_size, num_classes + 4 + num_masks, num_boxes). You can obtain this format from the output of your detection model in prediction mode by ensuring that the predictions align with the described dimensions. For your application with tensorRT saved weights, this post-processing step using non_max_supression can help refine the bounding box predictions. If you have further questions or need additional assistance, feel free to ask! 😊

**Comment by glenn-jocher** [comment]
@pderrenger Hello! To prepare your model's output for the `non_max_supression` function, ensure that your predictions tensor matches the required shape `(batch_size, num_classes + 4 + num_masks, num_boxes)`. This means each prediction should include the number of classes, bounding box coordinates, and mask data if applicable. After running your detection model in prediction mode, reshape or transform the output to fit this structure before applying `non_max_supression`. If you need more guidance on this process, our documentation might be helpful, and we're here to assist with any further questions. Happy coding! 😊
