### ISSUE TITLE
Scipy linear sum assignment is working correctly but lap.lapjv works not correctly.

### ISSUE THREAD

**Issue by ZouJiu1** [ultralytics/ultralytics#4388]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection, Other

### Bug

I find something wrong with the linear_sum_assignment usage in [https://github.com/ultralytics/ultralytics/blob/main/ultralytics/trackers/utils/matching.py#L61](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/trackers/utils/matching.py#L61)

the issuse opened in scipy [https://github.com/scipy/scipy/issues/19059](https://github.com/scipy/scipy/issues/19059)

what I find is the lap.lapjv  work properly, and the **scipy.optimize.linear_sum_assignment** works properly too. both are correct.  the scipy's version is **1.11.1**,  the lap's version is **0.5.4**. the wrong place is the codes of using the result of scipy.

- YOLO: [Ultralytics YOLOv8.0.21 🚀](https://github.com/ultralytics/ultralytics)      torch-2.0.1+cpu
- OS: Win10
- Python 3.10.12

### the matrix example

firstly clone the repo [https://github.com/ultralytics/ultralytics](https://github.com/ultralytics/ultralytics), and then using ultralytics to tracking.

```
import sys
sys.path.append(r'C:\Users\10696\Desktop\access\KalmanFilter\ultralytics')
from ultralytics import YOLO
model = YOLO('yolov8n.pt')
results = model.track(source=r"F:\MOT\MOT16-06-raw.webm", conf=0.3, iou=0.5, show=True)
```
[F:\MOT\MOT16-06-raw.webm](https://github.com/scipy/scipy/assets/34758215/abec2023-2546-460d-8eed-139ab1bc09b3)

I will debug into [ultralytics/trackers/utils/matching.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/trackers/utils/matching.py#L20)

this is the debug codes revised by myself.
```
def linear_assignment(cost_matrix, thresh, use_lap=False):
    """Linear assignment implementations with scipy and lap.lapjv."""
    if cost_matrix.size == 0:
        return np.empty((0, 2), dtype=int), tuple(range(cost_matrix.shape[0])), tuple(range(cost_matrix.shape[1]))
    if use_lap:
        # https://github.com/gatagat/lap
        _, x, y = lap.lapjv(cost_matrix, extend_cost=True, cost_limit=thresh)
        matches = [[ix, mx] for ix, mx in enumerate(x) if mx >= 0 and cost_matrix[ix, mx] <= thresh]
        zz = []
        for i in matches:
            zz.append(cost_matrix[i[0], i[1]])
        unmatched_a = np.where(x < 0)[0]
        unmatched_b = np.where(y < 0)[0]
    else:
        # https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.linear_sum_assignment.html
        x, y = scipy.optimize.linear_sum_assignment(cost_matrix)  # row x, col y
        matches = np.asarray([[x[i], y[i]] for i in range(len(x)) if cost_matrix[x[i], y[i]] <= thresh])
        zz = []
        for i in matches:
            zz.append(cost_matrix[i[0], i[1]])
        if len(matches) == 0:
            unmatched_a = list(np.arange(cost_matrix.shape[0]))
            unmatched_b = list(np.arange(cost_matrix.shape[1]))
        else:
            unmatched_a = list(set(np.arange(cost_matrix.shape[0])) - set(matches[:, 0]))
            unmatched_b = list(set(np.arange(cost_matrix.shape[1])) - set(matches[:, 1]))
    return matches, unmatched_a, unmatched_b
```

the first cost_matrix is showed below, it has six rows and five columns.
it is very simple to find that the minimum iou cost is [0.30292, 0.27259, 0.29889, 0.5569, 0.34354] in different row and column.
So let's find the difference between lap.lapjv and scipy.optimize.linear_sum_assignment.

```
cost_matrix = array([[          1,     0.30292,           1,           1,           1],
                                 [          1,           1,     0.27259,           1,           1],
                                 [    0.29889,           1,           1,           1,           1],
                                 [          1,           1,           1,           1,      0.5569],
                                 [          1,           1,           1,     0.34354,           1],
                                 [          1,           1,           1,           1,           1]], dtype=float32)
```

firstly, setting use_lap = True, the **zz**, x, y result of lap.lapjv below, so the result is correct.
```
x = array([ 1,  2,  0,  4,  3, -1])
y = array([2, 0, 1, 4, 3])
zz = [0.30292338, 0.27259243, 0.29888666, 0.5569032, 0.34353834]
```

secondly, setting use_lap = False, the **zz**, x, y result of scipy.optimize.linear_sum_assignment below, so the result is correct.
```
x=array([1, 2, 0, 4, 3], dtype=int64)
y=array([0, 1, 2, 3, 4], dtype=int64)
zz = array([    0.30292,     0.27259,     0.29889,      0.5569,     0.34354], dtype=float32)
```
So the difference is the result returned by scipy or lap.
let's see lap's document [https://github.com/gatagat/lap](https://github.com/gatagat/lap)

`
cost, x, y = lap.lapjv(C)
The function lapjv(C) returns the assignment cost (cost) and two arrays, x, y. If cost matrix C has shape N x M, then x is a size-N array specifying to which column is row is assigned, and y is a size-M array specifying to which row each column is assigned. For example, an output of x = [1, 0] indicates that row 0 is assigned to column 1 and row 1 is assigned to column 0. Similarly, an output of x = [2, 1, 0] indicates that row 0 is assigned to column 2, row 1 is assigned to column 1, and row 2 is assigned to column 0.
`

it this way, both are correct, I want to make sure what happen to using the **lap.lapjv** and pull request.

### Environment

- YOLO: [Ultralytics YOLOv8.0.21 🚀](https://github.com/ultralytics/ultralytics)      torch-2.0.1+cpu
- OS: Win10
- Python 3.10.12

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@ZouJiu1 hi there! Thanks for bringing this to our attention 🚀. We appreciate the detailed analysis and your willingness to contribute! We'll investigate the issue you've described with `lap.lapjv` and `scipy.optimize.linear_sum_assignment` to ensure compatibility with YOLOv8. Your input is valuable, and we'll work to address it in an upcoming release. Our team is committed to enhancing the accuracy and reliability of the YOLOv8 framework. Once again, thank you for your dedication and desire to submit a pull request! If you have any further insights or need any assistance, please feel free to reach out. We're here to support you in your contribution.
