### ISSUE TITLE
YOLOv8 does not support Apple Silicon MPS GPU

### ISSUE THREAD

**Issue by elcolie** [ultralytics/ultralytics#4389]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Validation

### Bug

A.I. does not won on MPS GPU. It does on CPU only :(

### Environment

```bash
absl-py==1.4.0
accelerate==0.21.0
aiofiles==23.1.0
aiohttp==3.8.4
aiosignal==1.3.1
altair==5.0.0
ansiwrap==0.8.4
antlr4-python3-runtime==4.9.3
anyio==3.6.2
appnope==0.1.3
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
async-generator==1.10
async-lru==2.0.4
async-timeout==4.0.2
attrs==23.1.0
autopep8==2.0.2
Babel==2.12.1
backcall==0.2.0
backoff==2.2.1
beautifulsoup4==4.12.2
bleach==6.0.0
bson==0.5.10
build==0.10.0
certifi==2023.5.7
cffi==1.15.1
chardet==5.2.0
charset-normalizer==3.1.0
click==8.1.3
cmake==3.26.4
colorama==0.4.6
coloredlogs==15.0.1
comm==0.1.3
commonmark==0.9.1
contourpy==1.0.7
controlnet-aux==0.0.5
cycler==0.11.0
datasets==2.12.0
debuglater==1.4.4
debugpy==1.6.7
decorator==5.1.1
defusedxml==0.7.1
diffusers==0.19.3
dill==0.3.6
einops==0.6.1
entrypoints==0.4
evaluate==0.4.0
exceptiongroup==1.1.1
executing==1.2.0
fastapi==0.95.2
fastjsonschema==2.17.1
ffmpeg-python==0.2.0
ffmpy==0.3.0
filelock==3.12.0
flatbuffers==23.5.26
fonttools==4.39.4
fqdn==1.5.1
frozenlist==1.3.3
fsspec==2023.5.0
gradio==3.32.0
gradio_client==0.2.5
h11==0.14.0
h5py==3.9.0
httpcore==0.17.2
httpx==0.24.1
huggingface-hub==0.14.1
humanfriendly==10.0
humanize==4.6.0
idna==3.4
imageio==2.31.0
importlib-metadata==6.6.0
invisible-watermark==0.2.0
ipdb==0.13.13
ipykernel==6.23.1
ipython==8.13.2
isoduration==20.11.0
jedi==0.18.2
Jinja2==3.1.2
jprq==2.1.0
json5==0.9.14
jsonpointer==2.4
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
jupyter-events==0.7.0
jupyter-lsp==2.2.0
jupyter_client==8.2.0
jupyter_core==5.3.0
jupyter_server==2.7.0
jupyter_server_terminals==0.4.4
jupyterlab==4.0.4
jupyterlab-pygments==0.2.2
jupyterlab_server==2.24.0
jupytext==1.14.5
kiwisolver==1.4.4
lazy_loader==0.2
linkify-it-py==2.0.2
llvmlite==0.40.1
markdown-it-py==2.2.0
MarkupSafe==2.1.2
matplotlib==3.7.1
matplotlib-inline==0.1.6
mdit-py-plugins==0.3.3
mdurl==0.1.2
mediapipe==0.10.1
mistune==2.0.5
monotonic==1.6
mpmath==1.3.0
multidict==6.0.4
multiprocess==0.70.14
mypy-extensions==1.0.0
nbclient==0.7.4
nbconvert==7.4.0
nbformat==5.8.0
nest-asyncio==1.5.6
networkx==3.1
notebook==7.0.2
notebook_shim==0.2.3
numba==0.57.1
numpy==1.24.3
omegaconf==2.3.0
onnxruntime==1.15.1
openai==0.27.7
opencv-contrib-python==4.7.0.72
opencv-python==4.7.0.72
orjson==3.8.13
outcome==1.2.0
overrides==7.4.0
packaging==23.1
pandas==2.0.1
pandocfilters==1.5.0
papermill==2.4.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.5.0
pip-tools==6.13.0
platformdirs==3.5.1
ploomber==0.22.3
ploomber-core==0.2.10
ploomber-engine==0.0.28
ploomber-scaffold==0.3.1
pooch==1.7.0
posthog==3.0.1
prometheus-client==0.17.1
prompt-toolkit==3.0.38
protobuf==3.20.3
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
py-cpuinfo==9.0.0
pyarrow==12.0.0
pycocotools==2.0.6
pycodestyle==2.10.0
pycparser==2.21
pydantic==1.10.7
pydub==0.25.1
pyflakes==3.0.1
Pygments==2.15.1
PyMatting==1.1.8
pyparsing==3.0.9
pypdf==3.9.0
pyproject_hooks==1.0.0
pyre-extensions==0.0.29
pyrsistent==0.19.3
PySocks==1.7.1
python-dateutil==2.8.2
python-dotenv==1.0.0
python-json-logger==2.0.7
python-multipart==0.0.6
pytz==2023.3
PyWavelets==1.4.1
PyYAML==6.0
pyzmq==25.0.2
referencing==0.30.2
regex==2023.5.5
requests==2.30.0
responses==0.18.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==10.14.0
rpds-py==0.9.2
safetensors==0.3.1
scikit-image==0.21.0
scipy==1.10.1
seaborn==0.12.2
selenium==4.10.0
semantic-version==2.10.0
Send2Trash==1.8.2
simple-photo-gallery @ file:///Users/sarit/study/simple-photo-gallery
six==1.16.0
sniffio==1.3.0
sortedcontainers==2.4.0
sounddevice==0.4.6
soupsieve==2.4.1
SQLAlchemy==2.0.15
sqlparse==0.4.4
stack-data==0.6.2
starlette==0.27.0
super-image==0.1.7
sympy==1.12
tabulate==0.9.0
tenacity==8.2.2
tensorboardX==2.6.1
terminado==0.17.1
textwrap3==0.9.2
tifffile==2023.4.12
tiktoken==0.4.0
timm==0.9.2
tinycss2==1.2.1
tokenizers==0.13.3
toml==0.10.2
tomli==2.0.1
toolz==0.12.0
torch==2.0.1
torchvision==0.15.2
tornado==6.3.2
tqdm==4.65.0
traitlets==5.9.0
transformers==4.31.0
trio==0.22.0
trio-websocket==0.10.3
triton-pre-mlir @ git+https://github.com/vchiley/triton.git@2dd3b957698a39bbca615c02a447a98482c144a3#subdirectory=python
typing-inspect==0.9.0
typing_extensions==4.5.0
tzdata==2023.3
uc-micro-py==1.0.2
ultralytics==8.0.152
uri-template==1.3.0
urllib3==2.0.2
uvicorn==0.22.0
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.1
websockets==11.0.3
wsproto==1.2.0
xformers==0.0.20
xxhash==3.2.0
yarl==1.9.2
zipp==3.15.0
```
OSX: 13.4.1 (c) (22F770820d)
Python: Python 3.11.3

### Minimal Reproducible Example

```python
"""Try train the YOLO from scratch."""
import torch
from ultralytics import YOLO

device: str = "mps" if torch.backends.mps.is_available() else "cpu"

# Load a model
model = YOLO("yolov8n.yaml")  # build a new model from scratch
model.to(device)
model.train(data="coco.yaml", epochs=5)
metrics = model.val()

```

### Additional

<img width="1710" alt="image" src="https://github.com/ultralytics/ultralytics/assets/18206728/00a27ec1-e4a3-4505-852e-288df7996ede">
No GPU load on MPS of M2

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@elcolie don't worry buddy, the usage is just a little different than what you had, but YOLOv8 does support MPS:

https://docs.ultralytics.com/modes/train/#apple-m1-and-m2-mps-training
<img width="1390" alt="Screenshot 2023-08-16 at 04 07 38" src="https://github.com/ultralytics/ultralytics/assets/26833433/e3061020-cb6f-4810-9d4f-0e143c4a162d">

**Comment by elcolie** [comment]
@glenn-jocher 
With new code
```python
import torch
from ultralytics import YOLO

device: str = "mps" if torch.backends.mps.is_available() else "cpu"

# Load a model
model = YOLO("yolov8n.yaml")  # build a new model from scratch
model.train(data="coco.yaml", epochs=3, device=device)
metrics = model.val()

```

It crashes
``bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/multiprocessing/spawn.py", line 129, in _main
    prepare(preparation_data)
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/multiprocessing/spawn.py", line 240, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/multiprocessing/spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/sarit/study/try_openai/appsmiths/run_yolo.py", line 9, in <module>
    model.train(data="coco.yaml", epochs=3, device=device)
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/site-packages/ultralytics/engine/model.py", line 377, in train
    self.trainer.train()
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 276, in _do_train
    self._setup_train(world_size)
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 240, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/site-packages/ultralytics/models/yolo/detect/train.py", line 41, in get_dataloader
    return build_dataloader(dataset, batch_size, workers, shuffle, rank)  # return dataloader
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/site-packages/ultralytics/data/build.py", line 101, in build_dataloader
    return InfiniteDataLoader(dataset=dataset,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/site-packages/ultralytics/data/build.py", line 29, in __init__
    self.iterator = super().__iter__()
                    ^^^^^^^^^^^^^^^^^^
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 441, in __iter__
    return self._get_iterator()
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1042, in __init__
    w.start()
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/multiprocessing/spawn.py", line 158, in get_preparation_data
    _check_not_importing_main()
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/multiprocessing/spawn.py", line 138, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by elcolie** [comment]
I found that `.to(device)` always give me back `cpu`. No idea why.
Here is my quickfix to continue my experiment.
`models.py`
```python
    def to(self, device):
        """
        Sends the model to the given device.

        Args:
            device (str): device
        """
        self._check_is_pytorch_model()
        self.model.to(device)
        self.overrides["device"] = "mps"    <---------- this line
```
and
```python
    def train(self, trainer=None, **kwargs):
        """
        Trains the model on a given dataset.

        Args:
            trainer (BaseTrainer, optional): Customized trainer.
            **kwargs (Any): Any number of arguments representing the training configuration.
        """
        self.overrides["device"] = "mps"
```
No idea why `overrides` dict is not memorize `device` from `to()`. But this dump fix works on my laptop.


<img width="1719" alt="image" src="https://github.com/ultralytics/ultralytics/assets/18206728/9245656c-3a1d-49d4-a299-7f2e75b51f46">

**Comment by alicebear1203** [comment]
I am now using YOLOv8 on M1 pro Max, but it seems like keep using CPU even I set the device to "mps".
Maybe it's kind of like the problem @elcolie faced, but while I changed the code from
```python
results = model(frame, device="mps")
``` 
to
```python
results = model.train(data='coco128.yaml', epochs=100, imgsz=640, device='mps'
``` 
like @elcolie did, it replied
```shell
the zsh: illegal hardware instruction  /Users/... 
``` 
Hope that I can figure out the solution soon or anyone who knows how to solve it would like to help!
I am new to this forum,  hope that my post is fine, thanks!

**Comment by alicebear1203** [comment]
Hi, I am new to this forum, hope that I ask the question in the right way.

Since I saw this video to help my M1 Max to work for YOLOv8, I got a problems.
(video link: https://www.youtube.com/watch?v=kEcWUZ8unmc&t=1739s)
Kind of like @elcolie encountered, the one which kept switch the MPS to CPU even he set deivce="MPS".
He did write down some solutions, but I am still not so sure what I have to adjust, 
so I am here to ask for help since I have tried for a while😢

Here is my code:
```python
import cv2
import torch
from ultralytics import YOLO
import numpy as np

cap = cv2.VideoCapture("/Users/.../dogs.mp4")
model = YOLO("yolov8n.pt")  # Initialize model
 
while True:
    ret, frame = cap.read()
    if not ret:
        break

    results = model(frame,device="mps")
    result = results[0]
    bboxes = np.array(result.boxes.xyxy.cpu(), dtype="int")
    classes = np.array(result.boxes.cls.cpu(), dtype="int")
    for cls, bbox in zip(classes, bboxes):
        (x, y, x2, y2) = bbox
        cv2.rectangle(frame, (x, y), (x2, y2), (0, 0, 225), 2)
        cv2.putText(frame, str(cls), (x, y - 5), cv2.FONT_HERSHEY_PLAIN, 2, (0, 0, 225), 2)


    cv2.imshow("Img", frame)
    key = cv2.waitKey(1)
    if key == 27:
        break

cap.release()
cv2.destroyAllWindows()

``` 
Also I used this to verify the MPS is work on my Mac
```python
import torch
print(torch.backends.mps.is_available())
print(torch.backends.mps.is_built())
``` 
Thanks for helping!!
