### ISSUE TITLE
Fine-tuning pre-trained models with higher image size?

### ISSUE THREAD

**Issue by Robotatron** [ultralytics/ultralytics#439]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Let's say I am using your or mine YOLOv8 model trained with image size of 640. 
Will there be any benefit  fine-tuning such a model with image size of 800 or 1024 or am I better off training from scratch?

ps. Don't see a "--seed" argument on https://docs.ultralytics.com/config/, is there an option to train YOLOv8 without any randomness, to consistently compare runs?

**Comment by AyushExel** [comment]
@Robotatron the seeds are set by default and all experiments should be reproducible. Let me know if you don't see this behavior.
Regarding the size, yes you might see some accuracy improvements but the training will also take longer so you'll have to decide on the tradeoff :)

**Comment by Robotatron** [comment]
Thanks Ayush.

I made two runs with exact same hyper parameters (except for num_epochs) (thanks for integrating ClearML :) ):
![image](https://user-images.githubusercontent.com/95919873/212958871-afa0d04b-79ce-4640-af29-df264c13cf4e.png)

But the results are very, very different (same dataset, same everything, I am doing ablation studies on YOLO8):
![image](https://user-images.githubusercontent.com/95919873/212959242-c6fa250e-7c28-460e-882d-2df11ccb400c.png)

**Comment by AyushExel** [comment]
Yes maps for the test set.. The maps will be different it you set different number of epochs because lr scheduler works on number of epochs.. So you'll only get reproducible results if you have the same parameters.

**Comment by AyushExel** [comment]
@Robotatron test set doubles the train batch size as it only runs on a single GPU. Regarding reproducibility - we've run multiple tests to confirm that runs are reproducible if all the cfg and inputs are the same.

**Comment by Robotatron** [comment]
> test set doubles the train batch size as it only runs on a single GPU

1. Not sure I follow. When training on several GPUs or a single one, the batch size we provide is a batch size per GPU.
I select my batch size as big as my GPU RAM allows, let's say 98% of RAM. So if I set batch size to 64, it will be 64 images or 98% of RAM if I train on a single GPU or several.
If you would then take double the batch size for the test set, you would crash the training with CUDA out of memory error.

2. Is learning logging planned for Tensorboard  and ClearML?
