### ISSUE TITLE
Can't start training using Ultralytics HUB with custom dataset

### ISSUE THREAD

**Issue by kipkoalex** [ultralytics/ultralytics#4396]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

After running this code:
```
hub.login(API_KEY)
model = YOLO(f'https://hub.ultralytics.com/models/{MODEL_ID}')
model.train()
```
In Google Colab I'm getting an error: 
`RuntimeError: Dataset 'DATASET_URL_PREFIX/Glare detection v4.v2i.yolov8.zip' error ❌ `
I hide the first part of dataset url under `DATASET_URL_PREFIX`, there is a relevant storage.googleapis.com url in actual error message.

Also tried the same in Paperspace notebook - no luck.
This appeared to start from today, since yesterday I was able to train models from HUB.

### Environment

- YOLOv8m/YOLOv8s
- Google Colab (https://colab.research.google.com/github/ultralytics/hub/blob/master/hub.ipynb)

### Minimal Reproducible Example

Create a new model from hub with custom dataset and try to run it with provided on Ultralytics Hub instructions

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kipkoalex I think this may be a duplicate of https://github.com/ultralytics/ultralytics/issues/4416 which has been fixed in `ultralytics 8.0.157`. You should try upgrading to see if your issue is resolved in the latest version.
