### ISSUE TITLE
yolov8 can't train properly

### ISSUE THREAD

**Issue by BigBull-man** [ultralytics/ultralytics#4397]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I tried to execute the following command:

yolo detect train data=./data/coco128.yaml model=yolov8n.yaml epochs=100 imgsz=640

yolo detect train data=./data/coco128.yaml model=./werights/yolov8n.pt epochs=100 imgsz=640

yolo detect train data=./data/coco128.yaml model=yolov8n.yaml pretrained=./werights/yolov8n.pt epochs=100 imgsz=640

./werights/    and    ./data/   It's where I store my training files

After executing the command, the program stuck in the middle of execution, did not report an error, and did not continue to execute

I have updated the latest version

I encountered the same situation when training with 1 nvidia a100 and using 3 nvidia a100, and training with single multi-card command.

The execution information is as follows：

<img width="1338" alt="image" src="https://github.com/ultralytics/ultralytics/assets/68015706/28f088c6-9f06-4fd0-abbc-47c19970cee3">
<img width="1332" alt="image" src="https://github.com/ultralytics/ultralytics/assets/68015706/7d452fed-c168-4b9e-9bce-e610c2aef888">

Unable to continue execution at this point
And no errors were reported

The GPU usage is as follows：
<img width="830" alt="image" src="https://github.com/ultralytics/ultralytics/assets/68015706/7b04705c-1eda-4b60-aa2b-8828282cfad2">

The model and data have been loaded into video memory, but utilization is 0

If I "ctrl+C" to end the operation, the existing can not be automatically released, I need to manually "kill PID"

**Comment by Kayzwer** [comment]
@BigBull-man try workers > 0

**Comment by BigBull-man** [comment]
> @BigBull-man尝试工人 > 0

I tried putting "workers=0", but it didn't solve the problem

**Comment by BigBull-man** [comment]
> @BigBull-man try workers > 0

I tried putting "workers=0"，"workers=2" ，"workers=4“ ，"workers=8", but it didn't solve the problem

**Comment by Kayzwer** [comment]
@BigBull-man how about you try to specify `device=0`

**Comment by BigBull-man** [comment]
@glenn-jocher Do you know the reason for this

**Comment by BigBull-man** [comment]
@Kayzwer After a long period of stop, the following error is displayed
<img width="1342" alt="image" src="https://github.com/ultralytics/ultralytics/assets/68015706/b6cf50bd-b4a3-44c4-8032-65d730c22921">
