### ISSUE TITLE
Saving results with save_txt

### ISSUE THREAD

**Issue by ifonya22** [ultralytics/ultralytics#4398]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am solving a segmentation problem. In some cases, for example, when the central part of the found object is covered, the contours that outline object in the image split into two masks instead of one. The problem is that when saving the results to a file, the coordinates of only one of the two masks are saved. If you look at the results[0].mask.x y[0] object, it also only stores the coordinates of one mask. Please tell me a way to save the coordinates of all masks.
Example of yolo inference:
![balk6_left_20-7-2023_16-2-1_jpg rf c5ff157593b8a961e16a9bd9b78bec8c](https://github.com/ultralytics/ultralytics/assets/56118798/694564d5-3005-45aa-8816-ce5c4a27e427)
saved txt file:
[balk6_left_20-7-2023_16-2-1_jpg.rf.c5ff157593b8a961e16a9bd9b78bec8c.txt](https://github.com/ultralytics/ultralytics/files/12357424/balk6_left_20-7-2023_16-2-1_jpg.rf.c5ff157593b8a961e16a9bd9b78bec8c.txt)
visualization of mask from a txt file:
![saved_coordinates](https://github.com/ultralytics/ultralytics/assets/56118798/504a1c76-f51b-4161-9e79-a9f8acca4baf)

**Comment by pderrenger** [comment]
@ifonya22 hey there! It seems like you're encountering some issues with saving the coordinates of all masks during the segmentation problem. YOLOv8 by default saves the coordinates of only one mask per object. To save coordinates for all masks, you'd need to modify the code to handle multiple masks per object, as YOLOv8 currently doesn't provide this functionality out of the box. I'd recommend reviewing the code related to mask generation and saving coordinates to extend this capability. If you have any specific questions about the code or need further assistance, feel free to ask! 😊
