### ISSUE TITLE
v8 guidance for flask_rest_api?

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/ultralytics#440]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Does v8 have a similar capability now or planned similar to v5 flask_rest_api?

**Comment by AyushExel** [comment]
Soon ™️

**Comment by apiszcz** [comment]
Is this in progress now or maybe 2024? If one were to create a rest API will the yolov5 version work with some changes?

**Comment by sarpx** [comment]
@AyushExel 
Could you please tell me when the work on this subject will be finished? We are having a hard time converting the results to json format. We are looking forward.
