### ISSUE TITLE
How to get the AP.75 pose in yolov8-pose? Thanks for your answer

### ISSUE THREAD

**Issue by Kk875** [ultralytics/ultralytics#4400]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to get the AP.75 pose in yolov8-pose? Thanks for your answer

**Comment by pderrenger** [comment]
@Kk875 to get the AP.75 (Average Precision with IoU threshold of 0.75) for pose estimation in YOLOv8, you can use the validation mode to evaluate the model's performance on a specific pose dataset. By running validation with the appropriate data and configuration, the AP.75 metric will be calculated and displayed as part of the validation results. You can refer to the documentation for more details on running the validation mode in YOLOv8.
