### ISSUE TITLE
cannot detect video

### ISSUE THREAD

**Issue by PredyDaddy** [ultralytics/ultralytics#4410]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello Ultralytics, 
I train a model use to detect shoes. Now I have a trained model name ```model=yolov8s_shoes.pt```, I used command 
```bash
root@912f87c63ba9:/app/ultralytics# yolo task=detect mode=predict model=yolov8s_shoes.pt source=test_images.jpg save=True
Ultralytics YOLOv8.0.155 🚀 Python-3.10.6 torch-2.1.0a0+b5021ba CUDA:0 (NVIDIA GeForce RTX 3090, 24260MiB)
Model summary (fused): 168 layers, 11125971 parameters, 0 gradients

image 1/1 /app/ultralytics/test_images.jpg: 640x640 2 shoess, 6.3ms
Speed: 8.5ms preprocess, 6.3ms inference, 459.8ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict5
```

I can get the result at runs/detect/predict5. Then I use command
```bash
root@912f87c63ba9:/app/ultralytics# yolo task=detect mode=predict model=yolov8s_shoes.pt source=video_record.mp4 save=True
Ultralytics YOLOv8.0.155 🚀 Python-3.10.6 torch-2.1.0a0+b5021ba CUDA:0 (NVIDIA GeForce RTX 3090, 24260MiB)
Model summary (fused): 168 layers, 11125971 parameters, 0 gradients

Results saved to runs/detect/predict4
```
I cannot get the result for detecting the video. 

Best Wishes, 
PreddyDaddy

**Comment by glenn-jocher** [comment]
Hello PreddyDaddy,

It seems like you're encountering an issue with running object detection on a video using your trained YOLOv8 model. Based on the information you provided, it looks like the model is not producing the expected results when processing the video.

Here are a few things you can check and try to troubleshoot the issue:

1. **Video Path:** Ensure that the `video_record.mp4` file is located in the correct path and accessible by the Ultralytics script.

2. **Frame Dimensions:** YOLO models are sensitive to the input dimensions of the images they process. Make sure that the dimensions of the frames in your video match the dimensions that the model was trained on. If they are different, you might need to resize or pad the frames to match the input size of the model.

3. **Model Configuration:** Double-check that the configuration used during training (`yolov8s_shoes.yaml` or similar) is the same as the one you're using during inference. Mismatched configurations can lead to unexpected results.

4. **Model Output Format:** The model outputs bounding box coordinates and class predictions. Ensure that you are properly visualizing or interpreting these results on the video frames. If the model is detecting objects but the visualization is incorrect, there might be an issue with how the results are being displayed.

5. **Ultralytics Version:** Ensure that you're using a compatible version of Ultralytics and PyTorch. It's possible that certain versions might have compatibility issues that affect the model's performance.

6. **Console Output:** Check the console output during video processing to see if there are any error messages or warnings that could give you more insights into what might be going wrong.

7. **GPU and Resources:** Ensure that your GPU and system resources are not being fully utilized by other tasks, as this could impact the model's performance.

8. **Model Weights:** Double-check that the model weights file (`yolov8s_shoes.pt`) is present and correctly linked in the command.

If after checking these points you're still facing issues, it might be helpful to provide more details about the configuration files you're using, the dimensions of your video frames, and any error messages you encounter during the process. This additional information would help in diagnosing the problem more accurately.

Best wishes with your shoe detection project! If you continue to face issues, don't hesitate to provide more information for further assistance.

**Comment by PredyDaddy** [comment]
Hello glenn-jocher,
   Thanks for reply. I tried some different version of pytorch container from nvidia. I used version 22.03 which can detect the vedio but lost function of train and export onnx. I used 23.07 pytorch container which cannot detect video but can train and export onnx. This onnx successfully convert to tensorRT engine and deploy to my project. It works.

many many thanks,
PreddyDaddy

**Comment by PredyDaddy** [comment]
Hello glenn-jocher,
   Thanks for reply. I tried some different version of pytorch container from nvidia. I used version 22.03 which can detect the vedio but lost function of train and export onnx. I used 23.07 pytorch container which cannot detect video but can train and export onnx. This onnx successfully convert to tensorRT engine and deploy to my project. It works.

many many thanks,
PreddyDaddy

**Comment by glenn-jocher** [comment]
@PredyDaddy hello PreddyDaddy,

I'm glad to hear that you found a solution to your issue! It's interesting to learn about your experience with different versions of the PyTorch container from NVIDIA. 

It does indeed seems like there might be some compatibility issues between different versions of PyTorch and certain functionalities in the Ultralytics YOLOv8 repository. This could explain the discrepancy in behavior you have encountered.

Your workaround of using different versions for detection and then for training and exporting to ONNX is quite creative. It's great that you were able to use the ONNX model in a TensorRT engine and deploy it to your project successfully.

Your feedback will definitely be valuable to others who may encounter similar issues. I'm sure your experience will contribute to future improvements in the Ultralytics tools and models.

Thank you for sharing your solution with us, and feel free to reach out if you have further issues or questions. We're here to help!

Best regards,
Glenn
