### ISSUE TITLE
Change the initial ID of the YOLOv8 tracker to start from a value other than 1

### ISSUE THREAD

**Issue by ChangX116** [ultralytics/ultralytics#4411]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to modify my tracker to assign IDs that do not start from 1, but rather start from the last ID in my database plus 1 for new targets. After modifying the code in the ultralytics-main\ultralytics\tracker\trackers\basetrack.py file, the tracking IDs for my new videos still start from 1. Here is my code:
class BaseTrack:
    """Base class for object tracking, handling basic track attributes and operations."""

    conn = psycopg2.connect(
        host="localhost",
        database="postgres",
        user="postgres",
        password="",
        port=""
    )
   cursor = conn.cursor()
    cursor.execute("SELECT MAX(id) FROM vehicle_tracking")
    max_id = cursor.fetchone()[0]
    if max_id is not None:
        track_id = max_id
        _count = max_id
    else:
        track_id = 0
        _count = 0

    cursor.close()
    conn.close()
 After modifying the code ，When I run the following code, the IDs assigned to newly tracked objects still start from 1:
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

for result in model.track(source="myvideo.mp4"):
    print(
        result.boxes.id.cpu().numpy().astype(int)
    ) 
May I know where to modify the code？

**Comment by glenn-jocher** [comment]
It seems like you're trying to modify the tracking IDs to start from the last ID in your database plus 1 for new targets. From the code you've provided, it looks like you're attempting to set up the initial tracking ID based on the maximum ID in your `vehicle_tracking` database table. However, the provided code is not directly connected to the tracking process within the `basetrack.py` file or the tracking loop you've shown.

The issue might be related to how the `track_id` and `_count` variables are being used within the tracking process. Without the complete context of how these variables are being used throughout the tracking process, it's difficult to provide an exact solution. However, here's a general approach you could follow to implement the desired behavior:

1. **Initialize the Tracking IDs:**

   Make sure that the initialization of `track_id` and `_count` is properly connected to the tracking process in the `basetrack.py` file. If these variables are class attributes, they need to be updated within the appropriate methods where new objects are being tracked.

2. **Updating Tracking IDs:**

   In the code where new objects are being tracked, you need to increment the tracking IDs based on the last ID in your database plus 1. This should happen each time a new object is detected and assigned a tracking ID.

   Assuming you have a method within the `BaseTrack` class responsible for assigning tracking IDs to newly detected objects, you could do something like this:

   ```python
   class BaseTrack:
       def assign_tracking_id(self, new_track):
           # Increment the tracking ID based on the last ID in the database
           self.track_id = self.max_id + 1
           self._count = self.max_id + 1

           # Update the database with the new tracking ID
           # Code to update the database with the new tracking ID

           # Assign the new tracking ID to the object
           new_track.id = self.track_id
   ```

   Then, within the tracking loop, call the `assign_tracking_id` method for each new detected object.

3. **Database Update:**

   Make sure that the code to update the database with the new tracking ID is correct and functioning as expected. This code is missing from the snippet you provided, so you'll need to implement it appropriately.

Remember that the exact implementation details might vary based on how your tracking system is structured. The key is to ensure that the tracking IDs are being updated properly within the tracking process based on the last ID in your database. If you're still facing issues, please provide more details about how the tracking process is structured in your code, and I'll be happy to help further.
