### ISSUE TITLE
error when custom data train

### ISSUE THREAD

**Issue by hanjoonwon** [ultralytics/ultralytics#4412]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![스크린샷 2023-08-17 122135](https://github.com/ultralytics/ultralytics/assets/125524043/651abcbb-a724-4ce8-87a1-e206a1eb437d)
my data.yaml location is  C:\Git_deep\ultralytics\custom 
there is custom image folder "train" too  and my data.yaml  text is 
train:custom/train/images

nc: 7
names: ['D00', 'D10', 'D20', 'D40', 'D43', 'D44', 'D50']

roboflow:
  workspace: project-i19oj
  project: road_japan-7moph
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/project-i19oj/road_japan-7moph/dataset/1
  
  how can i solve this error?

**Comment by pderrenger** [comment]
@hannaliavoshka to resolve the error, try rewriting the `names` field in your `data.yaml` file as demonstrated in the example provided in the YOLOv8 documentation under the "datasets/detect" section. This method may help in addressing the issue you encountered.
