### ISSUE TITLE
how to set iou in detection

### ISSUE THREAD

**Issue by chelsea456** [ultralytics/ultralytics#4414]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i have use this code to predict : result = model(image)[0], but i want to set arg  such as iou,conf.

**Comment by hannaliavoshka** [comment]
Pass them to the function:
`result = model(image, conf=0.25, iou=0.7)[0]`
More about inference arguments here: https://docs.ultralytics.com/modes/predict/#inference-arguments
As I noticed, `model(img)` and `model.predict(img)` behave the same.

**Comment by pderrenger** [comment]
@hannaliavoshka you can set the confidence threshold and IoU (Intersection over Union) by passing them as arguments to the `model` function for prediction. For example, you can use `result = model(image, conf=0.25, iou=0.7)[0]` to set the confidence threshold to 0.25 and the IoU to 0.7. The `model(img)` and `model.predict(img)` forms are equivalent. You can find more information about inference arguments in the [Ultralytics documentation](https://docs.ultralytics.com/modes/predict/#inference-arguments).
