### ISSUE TITLE
RuntimeError: Dataset 'https://app.roboflow.com/ds/xxxx' error ❌ 

### ISSUE THREAD

**Issue by CropWatchDevelopment** [ultralytics/ultralytics#4416]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Using the ultralytic website with roboflow. I am getting this error whenever I attempt to train the model in Google colab.
I follow the directions as asked, by copying and pasting, and this is the error I get. Not sure why.
The model trains just fine in Roboflow

### Environment

Colab instance that starts when I click train in ultralytics

### Minimal Reproducible Example

Ultralytics HUB: New authentication successful ✅
Ultralytics HUB: View model at https://hub.ultralytics.com/models/xxxxxxxxxxxxx 🚀
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to 'yolov8n.pt'...
100%|██████████| 6.23M/6.23M [00:00<00:00, 92.0MB/s]
Ultralytics YOLOv8.0.156 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB)
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=https://app.roboflow.com/ds/xxxxxxxx?key=xxxxxxxxx, epochs=100, patience=100, batch=-1, imgsz=640, save=True, save_period=-1, cache=ram, device=, workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train
Downloading https://app.roboflow.com/ds/gvmuv1pHha to 'gvmuv1pHha'...
100%|██████████| 11.0M/11.0M [00:00<00:00, 37.3MB/s]
Unzipping gvmuv1pHha to /content/datasets/gvmuv1pHha...: 100%|██████████| 308/308 [00:00<00:00, 2674.43file/s]
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py in __init__(self, cfg, overrides, _callbacks)
    123             elif self.args.data.split('.')[-1] in ('yaml', 'yml') or self.args.task in ('detect', 'segment'):
--> 124                 self.data = check_det_dataset(self.args.data)
    125                 if 'yaml_file' in self.data:

3 frames
StopIteration: 

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py in __init__(self, cfg, overrides, _callbacks)
    126                     self.args.data = self.data['yaml_file']  # for validating 'yolo train data=url.zip' usage
    127         except Exception as e:
--> 128             raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
    129 
    130         self.trainset, self.testset = self.get_dataset(self.data)

RuntimeError: Dataset 'https://app.roboflow.com/ds/xxxx' error ❌ 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@CropWatchDevelopment thanks for the bug report. I'm able to reproduce this error. I've added a TODO tag to work on a fix today.

**Comment by CropWatchDevelopment** [comment]
If there is anything at all i can do to assist, please let me know :)

**Comment by glenn-jocher** [comment]
@CropWatchDevelopment ok I think I have a fix working in https://github.com/ultralytics/ultralytics/pull/4407/commits/1914f24093cfa89d62b8ad023ef70ba1ecf03f21

I'm testing this now and if it works I'll push a new patch update soon.

**Comment by CropWatchDevelopment** [comment]
[celebrate]     Kevin Cantrell reacted to your message:
________________________________

**Comment by glenn-jocher** [comment]
@CropWatchDevelopment great news 😃! Your original issue may now be resolved ✅ in PR #4407. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by CropWatchDevelopment** [comment]
> @CropWatchDevelopment great news 😃! Your original issue may now be resolved ✅ in PR #4407 and published in `ultralytics 8.0.157`.
> 
> To get this update:
> - **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
> - **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
> - **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
> - **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>
> 
> Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

Just checked right now, things are back to working great! You rock!
This bug seems closed to me!

**Comment by glenn-jocher** [comment]
Glad to hear it's working for you now! If you have any more questions or run into issues, feel free to reach out.
