### ISSUE TITLE
yolov8 and opencv 4.8 problem

### ISSUE THREAD

**Issue by ali-liaei** [ultralytics/ultralytics#4420]
Hi
I have a simple code of reading camera as below:

import cv2
#from ultralytics import YOLO
cap = cv2.VideoCapture(0)
if not cap.isOpened():
    print("Cannot open camera")
    exit()
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    # Display the resulting frame
    cv2.imshow('frame', frame)
    if cv2.waitKey(1) == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

Everything is ok until i uncomment  "from ultralytics import YOLO".
When i do that the program hang on "cv2.imshow('frame', frame)" line.

**Comment by rmukh** [comment]
Ubuntu 20, Python 3.9, ultralytics 8.0.156.
Everything works fine with this configuration.

**Comment by Laughing-q** [comment]
@ali-liaei this [thread](https://github.com/ultralytics/ultralytics/issues/3005) might be helpful to you. :)

**Comment by ali-liaei** [comment]
Thank you @Laughing-q 
It worked for me.
pip3 uninstall av
