### ISSUE TITLE
How do I prepare segmentation data for complex shapes that have cutouts given the current label format?

### ISSUE THREAD

**Issue by SilverStarCoder** [ultralytics/ultralytics#4426]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I know that the required format for a YOLOv8 segmentation file is `<class-index> <x1> <y1> <x2> <y2> ... <xn> <yn>`.
But, what happens when I want to segment complex shapes that can have multiple cut-outs or holes in them? Is this not supported by YOLOv8 at the moment? As a trivial example, suppose I want to segment each of these different donuts:
![image](https://github.com/ultralytics/ultralytics/assets/141123187/d60bd178-514c-4552-8c28-b74b408548b4)
It is not clear how to annotate each donut using the require format.

**Comment by glenn-jocher** [comment]
In YOLOv8 segmentation, the format you mentioned `<class-index> <x1> <y1> <x2> <y2> ... <xn> <yn>` is indeed used for annotating objects. However, the format might not directly support annotating complex shapes with cut-outs or holes, as you've described.

For scenarios where you need to segment objects with holes or cut-outs, you can achieve this by using a multi-step approach. Here's a suggestion:

1. **Segment Outer Boundaries:**
   - Annotate the outer boundaries of the complex shapes using the standard YOLOv8 segmentation format.
   - Treat each complex shape (e.g., a donut) as an individual object.

2. **Segment Inner Cut-Outs:**
   - For each complex shape that has cut-outs, create separate annotations for the inner cut-outs.
   - Assign a different class index to these inner cut-outs, distinct from the class index assigned to the outer boundary.
   - These inner cut-outs can also be treated as individual objects, each with its own class index.

3. **Combine Annotations:**
   - During training and inference, treat the outer boundary and inner cut-outs as separate objects with distinct class indices.
   - Post-process the segmentation output to combine the segmentation masks of the outer boundary and its corresponding inner cut-outs.

4. **Connecting Holes:**
   - To connect the holes, you can draw a very thin line (with the same class index as the outer boundary) between the outer boundary and the inner cut-outs.
   - The presence of this thin line can help the model understand that the outer boundary and inner cut-outs are part of the same object.

It's important to note that this approach involves some manual processing and post-processing. The effectiveness of this approach would depend on the complexity of the shapes and the specific requirements of your project. Additionally, this method assumes that the model will be able to generalize well from the annotated data to accurately segment complex shapes with holes during inference.

Keep in mind that the YOLOv8 segmentation format is primarily designed for simpler object segmentation scenarios. For more complex cases like shapes with holes, there might be limitations in directly using the standard format. As a result, custom processing and techniques might be necessary to achieve accurate segmentation results.

**Comment by SilverStarCoder** [comment]
@glenn-jocher thank you for the detailed response. I find the idea of connecting holes very interesting.

- Could you provide more explicit guidance on how this connecting line should be drawn? Is it just one straight line from the outer boundary to an inner cut-out? For objects with multiple holes, should multiple connecting lines be drawn to each cut-out? 
- Have there been any internal tests or experiments that demonstrate the effectiveness of this unique approach?

I appreciate your time and expertise. Looking forward to your insights.

**Comment by glenn-jocher** [comment]
@SilverStarCoder thank you for your follow-up questions. I'm pleased to hear that you find the idea of connecting holes interesting.

The process of drawing the connecting line from the outer boundary to an inner cut-out really depends on the configuration of your shapes. You could certainly just draw one straight line, but the exact form that this line takes can be flexible. The main goal is to create a link between the outer boundary and each hole.

For objects with multiple cuts or holes, you should indeed draw multiple connecting lines to each cut-out. Each cut-out should have at least one connecting line that links it to the outer boundary. This way, the model can infer that these are regions to be excluded from the object of interest.

As for your second question, I should clarify that this approach is more of a method of working around the limitations of the YOLOv8 segmentation for complex shapes. It's not a standard approach that we have formally tested or have internal metrics on. The effectiveness of this method will highly depend on the complexity of the shapes you're working with and the specific requirements of your use case.

Remember, the key objective with this approach is to enable the model to understand the relationship between the boundary and the holes, despite the limitations of the annotation format. Some experimentation will likely be necessary to find the optimal way to apply this in your context. As always, I recommend splitting your dataset and validating the model's performance to ensure it's learning to segment as expected.

Hope this helps! Let me know if you have any other questions.

**Comment by ryouchinsa** [comment]
Using the script [general_json2yolo.py](https://github.com/ryouchinsa/Rectlabel-support/blob/master/general_json2yolo.py), you can convert the RLE mask with holes to the YOLO segmentation format.

The RLE mask is converted to a parent polygon and a child polygon using `cv2.findContours()`.
The parent polygon points are sorted in clockwise order. 
The child polygon points are sorted in counterclockwise order.
Detect the nearest point in the parent polygon and in the child polygon.
Connect those 2 points with narrow 2 lines.
So that the polygon with a hole is saved in the YOLO segmentation format.

```
def is_clockwise(contour):
    value = 0
    num = len(contour)
    for i, point in enumerate(contour):
        p1 = contour[i]
        if i < num - 1:
            p2 = contour[i + 1]
        else:
            p2 = contour[0]
        value += (p2[0][0] - p1[0][0]) * (p2[0][1] + p1[0][1]);
    return value < 0

def get_merge_point_idx(contour1, contour2):
    idx1 = 0
    idx2 = 0
    distance_min = -1
    for i, p1 in enumerate(contour1):
        for j, p2 in enumerate(contour2):
            distance = pow(p2[0][0] - p1[0][0], 2) + pow(p2[0][1] - p1[0][1], 2);
            if distance_min < 0:
                distance_min = distance
                idx1 = i
                idx2 = j
            elif distance < distance_min:
                distance_min = distance
                idx1 = i
                idx2 = j
    return idx1, idx2

def merge_contours(contour1, contour2, idx1, idx2):
    contour = []
    for i in list(range(0, idx1 + 1)):
        contour.append(contour1[i])
    for i in list(range(idx2, len(contour2))):
        contour.append(contour2[i])
    for i in list(range(0, idx2 + 1)):
        contour.append(contour2[i])
    for i in list(range(idx1, len(contour1))):
        contour.append(contour1[i])
    contour = np.array(contour)
    return contour

def merge_with_parent(contour_parent, contour):
    if not is_clockwise(contour_parent):
        contour_parent = contour_parent[::-1]
    if is_clockwise(contour):
        contour = contour[::-1]
    idx1, idx2 = get_merge_point_idx(contour_parent, contour)
    return merge_contours(contour_parent, contour, idx1, idx2)

def mask2polygon(image):
    contours, hierarchies = cv2.findContours(image, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_TC89_KCOS)
    contours_approx = []
    polygons = []
    for contour in contours:
        epsilon = 0.001 * cv2.arcLength(contour, True)
        contour_approx = cv2.approxPolyDP(contour, epsilon, True)
        contours_approx.append(contour_approx)

    contours_parent = []
    for i, contour in enumerate(contours_approx):
        parent_idx = hierarchies[0][i][3]
        if parent_idx < 0 and len(contour) >= 3:
            contours_parent.append(contour)
        else:
            contours_parent.append([])

    for i, contour in enumerate(contours_approx):
        parent_idx = hierarchies[0][i][3]
        if parent_idx >= 0 and len(contour) >= 3:
            contour_parent = contours_parent[parent_idx]
            if len(contour_parent) == 0:
                continue
            contours_parent[parent_idx] = merge_with_parent(contour_parent, contour)

    contours_parent_tmp = []
    for contour in contours_parent:
        if len(contour) == 0:
            continue
        contours_parent_tmp.append(contour)

    polygons = []
    for contour in contours_parent_tmp:
        polygon = contour.flatten().tolist()
        polygons.append(polygon)
    return polygons 

def rle2polygon(segmentation):
    if isinstance(segmentation["counts"], list):
        segmentation = mask.frPyObjects(segmentation, *segmentation["size"])
    m = mask.decode(segmentation) 
    m[m > 0] = 255
    polygons = mask2polygon(m)
    return polygons
```

The RLE mask.

![スクリーンショット 2023-11-22 1 57 52](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/df2dfad5-a13f-49c6-818a-8aba1d3ce83c)

The converted YOLO segmentation format.

![スクリーンショット 2023-11-22 2 11 14](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/cc34027a-075f-4b67-8de7-bd2dddddac59)

To run the script, put the COCO JSON file coco_train.json into `datasets/coco/annotations`.
Run the script. `python general_json2yolo.py  `
The converted YOLO txt files are saved in `new_dir/labels/coco_train`.

![スクリーンショット 2023-11-23 16 39 21](https://github.com/ultralytics/JSON2YOLO/assets/1954306/c3d98120-66f5-4cb8-b74d-a500f0bd811d)

Edit use_segments and use_keypoints in the script.

```
if __name__ == '__main__':
    source = 'COCO'

    if source == 'COCO':
        convert_coco_json('../datasets/coco/annotations',  # directory with *.json
                          use_segments=True,
                          use_keypoints=False,
                          cls91to80=False)
```

To convert the COCO bbox format to YOLO bbox format.
```
use_segments=False,
use_keypoints=False,
```

To convert the COCO segmentation format to YOLO segmentation format.
```
use_segments=True,
use_keypoints=False,
```

To convert the COCO keypoints format to YOLO keypoints format.
```
use_segments=False,
use_keypoints=True,
```

This script originates from Ultralytics [JSON2YOLO](https://github.com/ultralytics/JSON2YOLO) repository.
We hope this script would help your business.

**Comment by glenn-jocher** [comment]
@ryouchinsa thank you for sharing your method and script for converting RLE masks with holes to the YOLO segmentation format. Your detailed script and explanation provide a clear algorithm for handling complex shapes with inner cut-outs.

Your method of utilizing `cv2.findContours()` to obtain parent and child polygons, sorting them, finding the nearest points, and then creating narrow connections is a practical approach to overcome the limitations of simpler segmentation annotation formats.

By connecting polygons with narrow lines and treating holes as counterclockwise child polygons, users can preserve the structural information of complex objects through the YOLO segmentation format.

Even though this workaround may not be a standardized feature in YOLOv8 training, as a community-driven development, we are glad to see innovative adaptations of utility scripts like this being shared. It reflects the collaborative spirit of the open-source community. This approach, explained via your script, can be a valuable reference for users who face similar challenges in their segmentation tasks.

Remember, it's essential to validate the model's performance with these custom annotations to ensure the desired behavior during inference. Complex shapes with interior voids can challenge any segmentation model, and creative solutions like yours contribute to improving model robustness and flexibility.

Thank you for your contribution to the community! Let's continue to support each other in advancing object segmentation techniques. 👍

**Comment by ryouchinsa** [comment]
Thanks for reviewing our script.
We checked whether YOLO can train polygon masks with holes with a small dataset.

[Donut images and YOLO segmentation text files](https://github.com/ryouchinsa/donut) to confirm that YOLO can train polygon masks with holes.

![mak-E-6fFmT1kAw-unsplash](https://github.com/ultralytics/JSON2YOLO/assets/1954306/aeba1a78-f51b-46fd-8939-878aae541bb9)

![aldrin-rachman-pradana-Ilt3lUJP-EA-unsplash](https://github.com/ultralytics/JSON2YOLO/assets/1954306/f3d23fc9-c34e-4fe1-a3eb-7b528dfdacd8)

![brooke-lark-5BbB3WPi128-unsplash](https://github.com/ultralytics/JSON2YOLO/assets/1954306/d1ff30ee-d87d-4ab3-833d-34bcddef00cc)

![xandreasw-NH2S3zVPMaE-unsplash](https://github.com/ultralytics/JSON2YOLO/assets/1954306/d850947f-66f1-434f-8edf-9aa86c6eced6)

**Comment by glenn-jocher** [comment]
@ryouchinsa, it's encouraging to learn about your initiative to test YOLO's capabilities with polygon masks for complex shapes such as donuts with holes. Testing the algorithm on a small dataset is a great first step to validate its effectiveness for shapes with interior voids.

Using real-world images, such as the ones you provided for donuts, ensures that your evaluation reflects practical scenarios. This kind of hands-on experimentation is invaluable as it helps demonstrate how YOLO can handle not only the external contours of objects but also the intricacies that come with more complex geometric forms.

I'm glad to see you pushing the envelop and exploring the boundaries of what's possible with YOLO segmentation. Your work brings a tangible benefit to the community by providing examples and resources that others can learn from and build upon. Keep up the good work!

If there are any insights or results from your tests that you would like to share or if you encounter any issues that need troubleshooting, the community and the Ultralytics team are here to support your efforts.

Thank you for actively engaging and contributing to the continued improvement of YOLO models. Your hands-on testing and iterative approach foster a deeper understanding and future developments in object segmentation with YOLO. 🍩👩‍🔬🚀
