### ISSUE TITLE
Yolov8-pose  we didn't get results when we change structure of model ?

### ISSUE THREAD

**Issue by malareeqi** [ultralytics/ultralytics#4429]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

when we changed the structure of the Yolov8-pose model ? for example, when we replacing the c2f module with another module , we didn't get results for map pose during the training, it just gave me zero (cocc128pos)
so please can anyone help me to explain what happened  ?

**Comment by malareeqi** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/72854576/092caa21-9476-43f5-ba07-49b7cffcaf89)

**Comment by pderrenger** [comment]
@malareeqi when modifying the structure of the YOLOv8-pose model, such as replacing the c2f module with another module, it led to zero results for map pose during training, specifically "coco128pos". This outcome indicates that the model might require adjustments to properly accommodate the structural changes made. It's important to ensure that the new module is compatible with the overall architecture and that any corresponding configuration files or parameters are updated accordingly to reflect the modifications. Additionally, verifying that the training data and the model's output format align with the modifications is crucial for proper evaluation.
