### ISSUE TITLE
Typo in docs. File docs/usage/engine.md, line 17. "get_dataloder" -> "get_dataloader"

### ISSUE THREAD

**Issue by mishadobrits** [ultralytics/ultralytics#4431]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Typo is in this line https://github.com/ultralytics/ultralytics/blob/aaba14e6b25a8ef2ed18fe4449fa3073d96c7c02/docs/usage/engine.md?plain=1#L17 (and therefore in the documentation website https://docs.ultralytics.com/usage/engine/#basetrainer) 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mishadobrits great news 😃! Your original issue may now be resolved ✅ in PR #4432. I'll leave this open to accumulate a few more updates/fixes before merging to main, which will then update the docs.


Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!
