### ISSUE TITLE
Format of the my own datasets and how to write yaml file?thank you very much!!

### ISSUE THREAD

**Issue by xx-xxx** [ultralytics/ultralytics#4439]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to use my own dataset, need an images directory, what file contents do i need to put in the valid and train directory.
What's in it the train.txt and label.txt files and how i organiz them?
![image](https://github.com/ultralytics/ultralytics/assets/62284664/e88a57d1-ea70-40ef-b094-4196efcad8c1)
the train.txt is this now
![image](https://github.com/ultralytics/ultralytics/assets/62284664/0c84ed20-23c9-4b3b-b5e0-2fbc2e5be0d0)
it is the image and label directory
![image](https://github.com/ultralytics/ultralytics/assets/62284664/58792dad-2418-4466-b710-30dd453b258e)
the label file is this

**Comment by xx-xxx** [comment]
i see this https://docs.ultralytics.com/datasets/detect/ but i dont know how to use this still

**Comment by pderrenger** [comment]
@xx-xxx to use your own dataset with YOLOv8, here’s how you can organize it:

1. **Image Directory**: Prepare a directory containing all your images.

2. **Label Directory**: Create a directory with corresponding label files for each image. The label file should be named the same as the image file but with a .txt extension.

For the `train.txt` and `label.txt` files, you can organize them as follows:
- `train.txt`: This file should contain the file paths for all the images in your training dataset, with each path on a new line.
- `label.txt`: This file should contain the class labels for your dataset, such as "dog", "cat", etc., with one label per line.

Once you have organized your dataset in this manner, you can use the YOLOv8 Train mode to train your model on the custom dataset. For a more detailed explanation, you can refer to the [documentation on custom datasets](https://docs.ultralytics.com/datasets/detect/).

I hope this helps! If you have any further questions, feel free to ask.
