### ISSUE TITLE
Using v5loader=true results in non-fatal exception:  _imagingft C module is not installed

### ISSUE THREAD

**Issue by sstainba** [ultralytics/ultralytics#444]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

```
Ultralytics YOLOv8.0.7 🚀 Python-3.8.10 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3060, 12287MiB)
yolo/engine/trainer: task=detect, mode=train, model=yolov8m.pt, data=/datasets/bobbers/data.yaml, epochs=500, patience=50, batch=16, imgsz=800, save=True, cache=False, device=, workers=8, project=None, name=bobbers_v8, exist_ok=False, pretrained=False, optimizer=SGD, verbose=False, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, retina_masks=False, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, hydra={'output_subdir': None, 'run': {'dir': '.'}}, v5loader=True, save_dir=/usr/src/ultralytics/runs/detect/bobbers_v8
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.Conv                  [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.Conv                  [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.C2f                   [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.Conv                  [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.C2f                   [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.Conv                  [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.C2f                   [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.Conv                  [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.C2f                   [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.SPPF                  [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]
 12                  -1  2   1993728  ultralytics.nn.modules.C2f                   [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]
 15                  -1  2    517632  ultralytics.nn.modules.C2f                   [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.Conv                  [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]
 18                  -1  2   1846272  ultralytics.nn.modules.C2f                   [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.Conv                  [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]
 21                  -1  2   4207104  ultralytics.nn.modules.C2f                   [960, 576, 2]
 22        [15, 18, 21]  1   3776275  ultralytics.nn.modules.Detect                [1, [192, 384, 576]]
Model summary: 295 layers, 25856899 parameters, 25856883 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
optimizer: SGD(lr=0.01) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.0005), 83 bias
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
train: Scanning /datasets/bobbers/train/labels.cache... 572 images, 36 backgrounds, 0 corrupt: 100%|██████████| 572/572
val: Scanning /datasets/bobbers/valid/labels.cache... 24 images, 1 backgrounds, 0 corrupt: 100%|██████████| 24/24 [00:00
Image sizes 800 train, 800 val
Using 8 dataloader workers
Logging results to /usr/src/ultralytics/runs/detect/bobbers_v8
Starting training for 500 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/500      10.8G      1.902      8.916      1.151         16        800:   3%|▎         | 1/36 [00:05<03:23,  5.82Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 147, in check_pil_font
    return ImageFont.truetype(str(font) if font.exists() else font.name, size)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 959, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 956, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 219, in __init__
    if core.HAVE_RAQM:
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 58, in __getattr__
    raise ImportError("The _imagingft C module is not installed")
ImportError: The _imagingft C module is not installed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 223, in plot_images
    annotator = Annotator(mosaic, line_width=round(fs / 10), font_size=fs, pil=True, example=names)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 52, in __init__
    self.font = check_pil_font(font='Arial.Unicode.ttf' if non_ascii else font,
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 151, in check_pil_font
    return ImageFont.truetype(str(font), size)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 959, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 956, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 219, in __init__
    if core.HAVE_RAQM:
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 58, in __getattr__
    raise ImportError("The _imagingft C module is not installed")
ImportError: The _imagingft C module is not installed
      1/500      10.8G      1.884      7.166       1.16         31        800:   6%|▌         | 2/36 [00:06<01:35,  2.81Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 147, in check_pil_font
    return ImageFont.truetype(str(font) if font.exists() else font.name, size)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 959, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 956, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 219, in __init__
    if core.HAVE_RAQM:
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 58, in __getattr__
    raise ImportError("The _imagingft C module is not installed")
ImportError: The _imagingft C module is not installed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 223, in plot_images
    annotator = Annotator(mosaic, line_width=round(fs / 10), font_size=fs, pil=True, example=names)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 52, in __init__
    self.font = check_pil_font(font='Arial.Unicode.ttf' if non_ascii else font,
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 151, in check_pil_font
    return ImageFont.truetype(str(font), size)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 959, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 956, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 219, in __init__
    if core.HAVE_RAQM:
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 58, in __getattr__
    raise ImportError("The _imagingft C module is not installed")
ImportError: The _imagingft C module is not installed
      1/500      10.8G      1.834      7.193      1.215         15        800:   8%|▊         | 3/36 [00:07<01:00,  1.84Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 147, in check_pil_font
    return ImageFont.truetype(str(font) if font.exists() else font.name, size)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 959, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 956, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 219, in __init__
    if core.HAVE_RAQM:
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 58, in __getattr__
    raise ImportError("The _imagingft C module is not installed")
ImportError: The _imagingft C module is not installed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 223, in plot_images
    annotator = Annotator(mosaic, line_width=round(fs / 10), font_size=fs, pil=True, example=names)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 52, in __init__
    self.font = check_pil_font(font='Arial.Unicode.ttf' if non_ascii else font,
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 151, in check_pil_font
    return ImageFont.truetype(str(font), size)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 959, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 956, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 219, in __init__
    if core.HAVE_RAQM:
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 58, in __getattr__
    raise ImportError("The _imagingft C module is not installed")
ImportError: The _imagingft C module is not installed
      1/500      10.8G      1.435      3.482      1.045         13        800: 100%|██████████| 36/36 [00:27<00:00,  1.2
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00
                   all         24         23      0.989          1      0.995      0.645

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/500      11.4G      1.096     0.8995     0.9166         10        800: 100%|██████████| 36/36 [00:24<00:00,  1.4
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:03<00
                   all         24         23      0.905       0.83      0.955      0.553
```

### Environment

Yolov8 Docker image dfe3cc7876a9

### Minimal Reproducible Example

Pull current (as of 0900 EST on 2022-Jan-17) docker image.  Run detect/train on standard bbox dataset using v5loader.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Is this problem reproducible in the colab? I cannot reproduce it on my system. Maybe it might be something with your env? try setting up a new env and install ultralytics from pypi

**Comment by sstainba** [comment]
> Is this problem reproducible in the colab? I cannot reproduce it on my system. Maybe it might be something with your env? try setting up a new env and install ultralytics from pypi

I haven't tried colab.  I train locally on my GPU.  I am using the current ultralytics/ultralytics docker image so I wouldn't expect my environment to be an issue.  I am a .NET dev (not Python) but I would assume this means there is some dependency that isn't installed in the image?

**Comment by sstainba** [comment]
Also, to be very clear:  I run the ultralytics docker image via Docker Desktop w/ WSL3 integration.  This error *only* occurs when using the v5loader.  However, if I run the Yolov5 docker image on the same dataset, it works without error.

**Comment by AyushExel** [comment]
What happens when you run it without `v5Loader=True`

**Comment by sstainba** [comment]
> What happens when you run it without `v5Loader=True`

It works then. However, there is another issue reported in [#363](https://github.com/ultralytics/ultralytics/issues/363) that is the reason I'm using the v5loader. My dataset has a few "null" images where the classes I'm training aren't present. So the annotation file is blank. This isn't an issue for Yolov5, but with v8, if I include those images I get a fatal exception "IndexError: boolean index did not match indexed array along dimension."  Using the v5loader corrects that exception, but results in this other, non-fatal issue.

**Comment by Laughing-q** [comment]
@sstainba looks there's something wrong about your PIL/ font. But this error occurs in the image-plotting process of the first epoch, actually it won't affect the training process itself, so there's no need to worry. :)

**Comment by sstainba** [comment]
> @sstainba looks there's something wrong about your PIL/ font. But this error occurs in the image-plotting process of the first epoch, actually it won't affect the training process itself, so there's no need to worry. :)

Yeah, I mentioned that it is non-fatal.  But this is not a problem with *my* anything.  This is a problem with the ultralytics docker image.

**Comment by FrancescoSaverioZuppichini** [comment]
@sstainba given the interaction we had before I am gonna assume you are new to everything. Do you know this is GPL software right? And you cannot use it in your work if you don't pay the license - the fact that you are a .NET dev and you are asking about Docker suggested to me you are going to run this in some infrastructure. 

@AyushExel do not bother with him too much, he was very aggressive on an issue I've opened before so you have been warned

**Comment by AyushExel** [comment]
@FrancescoSaverioZuppichini @sstainba I'm sorry you guys got off on the wrong foot. I sincerely hope it was just 2 nice people having a not-so-nice day and that we can move ahead without any hard feelings.
Also, as the issue isn't a blocker and isn't reproducible on our end, please suggest a solution or make a PR to fix it and I'll be happy to assist.

Regarding the license - it is more nuanced than what is mentioned above. Please feel free to continue using the tool however you intend to. Certain organizations need licenses and you should leave it up to your org to determine if they need it. More than anything else, the license is more of a safety check introduced to prevent unethical uses.

**Comment by FrancescoSaverioZuppichini** [comment]
@AyushExel I am having a wondering day, not sure about our big expert here. I have the same issue btw, but as you said it doesn't prevent training so I've never reported it

**Comment by sstainba** [comment]
> @sstainba given the interaction we had before I am gonna assume you are new to everything. Do you know this is GPL software right? And you cannot use it in your work if you don't pay the license - the fact that you are a .NET dev and you are asking about Docker suggested to me you are going to run this in some infrastructure.
> 
> @AyushExel do not bother with him too much, he was very aggressive on an issue I've opened before so you have been warned

Your assumptions are incorrect all the way around.  I use docker because I don't want to install all of the needed dependencies directly on my system.  If the docker container gets outdated I can simply pull a new one.  I'm not sure why you think docker is only useful in a commercial environment.  That honestly makes no sense.

And to be clear, I was not aggressive.  I made a suggestion to help you and you insulted me to which I responded in kind.  And now, it seems you're stalking my posts, which is a little weird.

**Comment by sstainba** [comment]
> @FrancescoSaverioZuppichini @sstainba I'm sorry you guys got off on the wrong foot. I sincerely hope it was just 2 nice people having a not-so-nice day and that we can move ahead without any hard feelings. Also, as the issue isn't a blocker and isn't reproducible on our end, please suggest a solution or make a PR to fix it and I'll be happy to assist.
> 
> Regarding the license - it is more nuanced than what is mentioned above. Please feel free to continue using the tool however you intend to. Certain organizations need licenses and you should leave it up to your org to determine if they need it. More than anything else, the license is more of a safety check introduced to prevent unethical uses.

So I've continued to see this issue.  However, it may be related to the dataset in some way.  I realized there were a few images in my dataset that were annotated for segmentation.  I saw a message during training that it would use bbox instead for those.  I also had several images that were not tagged and so the annotation file was empty.  The v8 loader seemed to have issue with these, so I started using the v5 loader.  That is how I got this message.  So I would guess this has to do with either the null annotation or the segmentations and the way the v5 loader handles them.

And regarding the license, I am just using this to learn and for a personal game bot.  I use the docker images because the Ultralytics team is clearly much better positioned to ensure all dependencies are met.  With my professional work, I was not willing to take the chance of interference between what is needed for Yolo and what I need for my job.

**Comment by AyushExel** [comment]
Okay got it! I'll try to fix this issue or provide a better error msg if I come across this myself.

**Comment by Laughing-q** [comment]
@sstainba ok I'll add some empty anno files in my case to reproduce the `IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 4` issue.

BTW can you just remove these empty anno files for now? as this issue [https://github.com/ultralytics/ultralytics/issues/363#issuecomment-1384740683](https://github.com/ultralytics/ultralytics/issues/363#issuecomment-1384740683) has been fixed. :)

**Comment by sstainba** [comment]
> @sstainba ok I'll add some empty anno files in my case to reproduce the `IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 4` issue.
> 
> BTW can you just remove these empty anno files for now? as this issue [#363 (comment)](https://github.com/ultralytics/ultralytics/issues/363#issuecomment-1384740683) has been fixed. :)

Yes, the empty annotations when using the v8 loader causes the issue in #363, the v5 loader prevents that issue, but caused this one.

You can remove the files, but as far as I'm aware, they are valid and shouldn't cause an issue.

**Comment by sstainba** [comment]
> Okay got it! I'll try to fix this issue or provide a better error msg if I come across this myself.

I just re-tested with the latest image and 2 different datasets - one had 2 null annotations and the other had 2 segmentation annotations.  The segmentation did still cause the error in #363 (although it's been fixed for nulls), but I didn't get the error from this thread any longer for either the v5 or v8 loaders.  So it l
[seg_test_v8_loader.zip](https://github.com/ultralytics/ultralytics/files/10549316/seg_test_v8_loader.zip)
ooks like this was fixed as far as I can tell.  Attached is the dataset, args and log from my test.
[seg_test_v5_loader.zip](https://github.com/ultralytics/ultralytics/files/10549318/seg_test_v5_loader.zip)

**Comment by pderrenger** [comment]
@sstainba thanks for the update! It's great to hear that the issue seems to have been resolved. If you encounter any further issues or have additional feedback, feel free to let us know. We're here to help!
