### ISSUE TITLE
Polygon Detections instead of Conventional BBox

### ISSUE THREAD

**Issue by Prakash-Reddy-6** [ultralytics/ultralytics#4440]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I want to know how to use polygon based detection(not segmentation) using 4 vertices of bounding box similar to this [PolygonObjectDetection](https://github.com/XinzeLee/PolygonObjectDetection). Is there anyway in yolov8 to achieve that.

**Comment by glenn-jocher** [comment]
@Prakash-Reddy-6 if you're referring to Oriented Bounding Boxes (OBB), we have an open issue to add this task to Ultralytics:
https://github.com/ultralytics/ultralytics/issues/4242
