### ISSUE TITLE
Want to store intermediate weight of yolov8 training

### ISSUE THREAD

**Issue by Hir98** [ultralytics/ultralytics#4446]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello I want to know for intermediate weight store.
I am training yolov8 upto 50 epoch and  i want to store intermediate weight in drive after every 10 epoch so how can we do this things??

**Comment by pderrenger** [comment]
@Hir98 hello! To store intermediate weights during training, you can use the `--save_period` flag in the `train.py` script. Set it to the number of epochs after which you want to save the weights, for example `--save_period 10` will save the weights every 10 epochs. This will store the weights in the `weights` directory by default. Hope this helps! 😊
