### ISSUE TITLE
save_masks for segmentation mode

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/ultralytics#4450]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

configuration items save_masks 
folder name masks, at same level of crops and labels

### Use case

When operating batch mode the masks can be used to extract only the object of interest.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@apiszcz hi, thank you for your feature suggestion on how to improve YOLO 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
