### ISSUE TITLE
Changing the parameters directly in a YOLOv8 model

### ISSUE THREAD

**Issue by nkd7** [ultralytics/ultralytics#4451]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

## Background

I am trying to implement the Model Soup approach (as described here: [paper](https://arxiv.org/pdf/2203.05482.pdf)) with YOLOv8 across 100 model instances I have trained with different hyperparameters. I have verified that I have the correct values for the tensors at each layer of the model that I want to insert but I cannot figure out how to either instantiate a new model with these parameters or set parameters in an existing model to these values. Every model trained was YOLOv8n.

#### Create a state dictionary with new values

```
average_parameters = {key: torch.nn.parameter.Parameter(data=torch.tensor(value / num_models), requires_grad=False) for key, value in summed_parameters.items()}
initial_params = torch.load("yolov8n.pt")
det_mod = DetectionModel()
det_mod.load(params["model"])
det_mod.load_state_dict(average_parameters)
```

Error: RuntimeError: Error(s) in loading state_dict for DetectionModel:
        Missing key(s) in state_dict: "model.0.bn.running_mean", "model.0.bn.running_var", "model.1.bn.running_mean", "model.1.bn.running_var", "model.2.cv1.bn.running_mean", "model.2.cv1.bn.running_var", "model.2.cv2.bn.running_mean", "model.2.cv2.bn.running_var", "model.2.m.0.cv1.bn.running_mean", "model.2.m.0.cv1.bn.running_var", "model.2.m.0.cv2.bn.running_mean", "model.2.m.0.cv2.bn.running_var", "model.3.bn.running_mean", "model.3.bn.running_var", "model.4.cv1.bn.running_mean", "model.4.cv1.bn.running_var", "model.4.cv2.bn.running_mean", "model.4.cv2.bn.running_var", "model.4.m.0.cv1.bn.running_mean", "model.4.m.0.cv1.bn.running_var", "model.4.m.0.cv2.bn.running_mean", "model.4.m.0.cv2.bn.running_var", "model.4.m.1.cv1.bn.running_mean", "model.4.m.1.cv1.bn.running_var", "model.4.m.1.cv2.bn.running_mean", "model.4.m.1.cv2.bn.running_var", "model.5.bn.running_mean", "model.5.bn.running_var", "model.6.cv1.bn.running_mean", "model.6.cv1.bn.running_var", "model.6.cv2.bn.running_mean", "model.6.cv2.bn.running_var", "model.6.m.0.cv1.bn.running_mean", "model.6.m.0.cv1.bn.running_var", "model.6.m.0.cv2.bn.running_mean", "model.6.m.0.cv2.bn.running_var", "model.6.m.1.cv1.bn.running_mean", "model.6.m.1.cv1.bn.running_var", "model.6.m.1.cv2.bn.running_mean", "model.6.m.1.cv2.bn.running_var", "model.7.bn.running_mean", "model.7.bn.running_var", "model.8.cv1.bn.running_mean", "model.8.cv1.bn.running_var", "model.8.cv2.bn.running_mean", "model.8.cv2.bn.running_var", "model.8.m.0.cv1.bn.running_mean", "model.8.m.0.cv1.bn.running_var", "model.8.m.0.cv2.bn.running_mean", "model.8.m.0.cv2.bn.running_var", "model.9.cv1.bn.running_mean", "model.9.cv1.bn.running_var", "model.9.cv2.bn.running_mean", "model.9.cv2.bn.running_var", "model.12.cv1.bn.running_mean", "model.12.cv1.bn.running_var", "model.12.cv2.bn.running_mean", "model.12.cv2.bn.running_var", "model.12.m.0.cv1.bn.running_mean", "model.12.m.0.cv1.bn.running_var", "model.12.m.0.cv2.bn.running_mean", "model.12.m.0.cv2.bn.running_var", "model.15.cv1.bn.running_mean", "model.15.cv1.bn.running_var", "model.15.cv2.bn.running_mean", "model.15.cv2.bn.running_var", "model.15.m.0.cv1.bn.running_mean", "model.15.m.0.cv1.bn.running_var", "model.15.m.0.cv2.bn.running_mean", "model.15.m.0.cv2.bn.running_var", "model.16.bn.running_mean", "model.16.bn.running_var", "model.18.cv1.bn.running_mean", "model.18.cv1.bn.running_var", "model.18.cv2.bn.running_mean", "model.18.cv2.bn.running_var", "model.18.m.0.cv1.bn.running_mean", "model.18.m.0.cv1.bn.running_var", "model.18.m.0.cv2.bn.running_mean", "model.18.m.0.cv2.bn.running_var", "model.19.bn.running_mean", "model.19.bn.running_var", "model.21.cv1.bn.running_mean", "model.21.cv1.bn.running_var", "model.21.cv2.bn.running_mean", "model.21.cv2.bn.running_var", "model.21.m.0.cv1.bn.running_mean", "model.21.m.0.cv1.bn.running_var", "model.21.m.0.cv2.bn.running_mean", "model.21.m.0.cv2.bn.running_var", "model.22.cv2.0.0.bn.running_mean", "model.22.cv2.0.0.bn.running_var", "model.22.cv2.0.1.bn.running_mean", "model.22.cv2.0.1.bn.running_var", "model.22.cv2.1.0.bn.running_mean", "model.22.cv2.1.0.bn.running_var", "model.22.cv2.1.1.bn.running_mean", "model.22.cv2.1.1.bn.running_var", "model.22.cv2.2.0.bn.running_mean", "model.22.cv2.2.0.bn.running_var", "model.22.cv2.2.1.bn.running_mean", "model.22.cv2.2.1.bn.running_var", "model.22.cv3.0.0.bn.running_mean", "model.22.cv3.0.0.bn.running_var", "model.22.cv3.0.1.bn.running_mean", "model.22.cv3.0.1.bn.running_var", "model.22.cv3.1.0.bn.running_mean", "model.22.cv3.1.0.bn.running_var", "model.22.cv3.1.1.bn.running_mean", "model.22.cv3.1.1.bn.running_var", "model.22.cv3.2.0.bn.running_mean", "model.22.cv3.2.0.bn.running_var", "model.22.cv3.2.1.bn.running_mean", "model.22.cv3.2.1.bn.running_var".

#### Get the type of layer and instantiate a layer with my new parameters

```
average_parameters = OrderedDict([(key, torch.nn.parameter.Parameter(data=torch.tensor(np.divide(value, num_sd)), requires_grad=False)) for key, value in summed_parameters.items()])
initial_params = torch.load("yolov8n.pt")
det_mod = DetectionModel()
det_mod.load(params["model"])
modules = [m for m in det_mod.modules()
for i, (layer_name, layer_params) in enumerate(average_parameters.items()):
    layer_type = type(modules[i])
    layer = layer_type(layer_params)
    layers.append((layer_name, layer))
det_mod.load_state_dict(OrderedDict(layers))
```

Error: TypeError: expected str, bytes or os.PathLike object, not Parameter for expression: "layer = layer_type(layer_params)"

I am not sure what I should be giving as an input here... Any help is greatly appreciated!

**Comment by pderrenger** [comment]
@nkd7 it seems like you're attempting to modify the parameters directly within a YOLOv8 model instance. However, modifying the model parameters directly can be complex and may lead to unexpected behavior, especially if not done carefully.

One approach to updating the model parameters is by manually setting them using the model's state dictionary. However, it's essential to ensure that the keys and shapes of the new parameters align with the existing model architecture in detail.

Given your scenario, I'd recommend thoroughly reviewing the model architecture and comparing it with your updated parameters to ensure they match. The error messages you encountered are indicators of discrepancies between the model's expected parameter keys and the provided ones.

If you still intend to proceed with this approach, I suggest carefully validating the shape and keys of the updated parameters to align with the model's architecture.

If you have further questions or need additional assistance, feel free to ask!
