### ISSUE TITLE
Why does yolov8 not have graphs, while yolov5 does

### ISSUE THREAD

**Issue by liuzimo** [ultralytics/ultralytics#4460]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

**Why can't Yolov8 use Tensorboard to see graphs instead？**
**Why can't Yolov8 use Tensorboard to see graphs instead？**
**Why can't Yolov8 use Tensorboard to see graphs instead？**
![image](https://github.com/ultralytics/ultralytics/assets/25811500/3116a224-afc9-45de-91c4-5bf608da3036)

![image](https://github.com/ultralytics/ultralytics/assets/25811500/7825613d-b131-4cab-8337-66020ab7f82d)
**Why can't Yolov8 use Tensorboard to see graphs instead？**

**Comment by glenn-jocher** [comment]
@liuzimo good question! It seems this feature was not transferred over as the TensorBoard logger does not have this capability. I'll add a TODO to transfer this from YOLOv5. If you have time a PR for this would be super helpful!

**Comment by glenn-jocher** [comment]
@liuzimo the place to add this is here BTW:

https://github.com/ultralytics/ultralytics/blob/87ce15d383d7e830a3dc2601bcddcdb9bddfc25f/ultralytics/utils/callbacks/tensorboard.py#L18-L50

**Comment by glenn-jocher** [comment]
@liuzimo great news 😃! Your original issue may now be resolved ✅ in PR #4464. This PR adds TensorBoard Graph visualizations to YOLOv8 :)


<img width="1558" alt="Screenshot 2023-08-21 at 00 40 36" src="https://github.com/ultralytics/ultralytics/assets/26833433/cf532f53-d62c-438e-8215-808c968173cd">


To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by liuzimo** [comment]
@glenn-jocher 
![image](https://github.com/ultralytics/ultralytics/assets/25811500/9fdaa5a8-d2e8-4099-9f06-5b8a115fc9f1)
我用最新的代码训练coco128,但是tensorboard 打开连图表都没了
