### ISSUE TITLE
Aliasing tiny mask possibly caused by incorrect mask loss in yolov8-seg

### ISSUE THREAD

**Issue by gasharper** [ultralytics/ultralytics#4469]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I noticed that the predicted tiny object mask of yolov8-seg shows unexpected aliasing, which may own to the nearest-downsampling of the ground-truth mask during training: 
In loss.py, the ground-truth mask is nearest-downsampled to align lower resolution. 
https://github.com/ultralytics/ultralytics/blob/3acead7e79a8769112a72fad430ef07fc2a4ea48/ultralytics/utils/loss.py#L261
This way may lose the details of GT, resulting in a great influence (aliasing boundary) on tiny object masks.

To address the above issue, I suggest adopting bilinear-upsampling the `pred_mask` instead of downsampling the `gt_mask`.

### Additional

![image](https://github.com/ultralytics/ultralytics/assets/34715974/b0c46b64-a36c-489a-9e80-90bc2a4786b9)
the cropped image (for better visualization) from the original result.  It shows some aliasing effects on tiny objects.

**Comment by glenn-jocher** [comment]
@gasharper no, this is due to mask downsampling. For higher resolution masks you can use retina_mask=True during inference or validation.
