### ISSUE TITLE
how can take frame after predict?

### ISSUE THREAD

**Issue by kyoko9000** [ultralytics/ultralytics#4477]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

now i see yolov8 can export frame before predict by this code:

det_results = det_model(data, stream=True, device=device)
for result in det_results:
      result.orig_img

so if i want to export frame after detect how can i do like that?.
if that not possible please make that funtion because it use too much in the project. please!

**Comment by glenn-jocher** [comment]
@kyoko9000 hello,

Thanks for your interest in YOLOv8 and for bringing up this insightful question regarding exporting frames after detection.

In the current design of YOLOv8, the detection results are bundled into a structured format that goes beyond just the original image, to include the class IDs, bounding boxes, confidence scores, etc. This format is more versatile for subsequent tasks such as post-processing, visualization, or metrics computation.

That said, the model doesn't explicitly return the frames after detection for direct use, but it is still possible to derive these. To obtain an image with annotations (bounding boxes, labels, etc.) overlaid after the detection stage, you can utilize the detection result and original image to draw the bounding boxes manually. The detection result includes the coordinates of bounding boxes, class ids, and scores which will enable you to create an annotated image from your output.

We appreciate your suggestion and will definitely consider adding this functionality in future updates. Your continuous feedback helps us to improve our models and their ease of use. So, thank you!

Best regards,
Glenn Jocher and the Ultralytics team
