### ISSUE TITLE
Yolov8 with 1280 model needed!

### ISSUE THREAD

**Issue by carlos-leitek** [ultralytics/ultralytics#4478]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Can you tell me precise release dates of yolov8 with this feature 1280 model ? or at least a link for the roadmap.
I need this feature since i need detection with high resolution images.

### Use case

this feature is important when using high resolution images.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@carlos-leitek thanks for your feedback! The feature is number 12 in the roadmap here. I can't provide you with an exact date, but we should have these out towards the end of Q3.

https://github.com/orgs/ultralytics/projects/14

**Comment by jigratz** [comment]
Hello- First of all, thank you Glenn Jocher for your incredible contributions to AI. I'm not sure where we'd be without you. Secondarily, I was hoping for an update on the release date for the YOLOv8x6 1280 model, specifically for detection :)
Thank you and Best,
-Joe

**Comment by monkeycc** [comment]
+1

**Comment by glenn-jocher** [comment]
@monkeycc thanks for your interest in YOLOv8! Regarding your question about the YOLOv8x6 1280 model, I'm excited to tell you that our team is working on it as we speak. However, I can't give you an exact date for its release at this moment. 

Our aim for all our models, including YOLOv8x6 1280, is to deliver high-quality, reliable, and accessible solutions for your high-resolution image detection needs. I assure you that we are putting significant effort into bringing this to you as soon as possible. Your patience and continued support are much appreciated.

Keep your eye out for updates and thank you again for your support. Happy coding!
