### ISSUE TITLE
About training yolov8-rtdetr.yaml model

### ISSUE THREAD

**Issue by wwt123-star** [ultralytics/ultralytics#4485]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Could I train the 'yolov8.rtdetr.yaml' model by using the pretrained model of 'yolov8-seg.pt'?

**Comment by Kayzwer** [comment]
@wwt123-star I think it is possible, but not all the parameters in yolov8-seg.pt will be transfer to yolov8-rtdetr as the head structure is different.

**Comment by wwt123-star** [comment]
And whether the rectangle training could work for yolov8-rtdert? I had set the 'rect' = True, but it didn't work out.

**Comment by Laughing-q** [comment]
@wwt123-star no `rect` is not implemented to rtdetr since its training needs square images.
