### ISSUE TITLE
How to change the saving path of cropped boxes from image instead of predict/cropped?

### ISSUE THREAD

**Issue by Zy-23** [ultralytics/ultralytics#4487]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I am currently working on a task to separate human and slideshow from some presentation videos. 

I was able to find out how I may save the cropped area of the input frame, and I am aware that I can change the saving directory for predict() function using 'project' and 'name' parameters. However, is it possible for me to further customize my saving directory?

```python
frames_path = "Project/Frames/presenter's name"
model = YOLO(path_to_model)

for frame in os.listdir(frames_path):
    img_path = os.path.join(frames_path, frame)
    results = model.predict(source=img_path, classes=0, project="presenter's name", save_crop=True)
```
For example, currently, I have set 'project' to be the presenter's name, hence the current path to the saved cropped image will be 'presenter's name/predict/crops/person/output.jpg'

I wish to customize the saved file path to 'presentor's name/person' and have the outputs of the for loop above all saved in this directory, is there any way to do so?

**Comment by glenn-jocher** [comment]
@Zy-23 hello,

In the current version of YOLOv8, the path structure for the saved images is predetermined. You're correct that when using the `save_crop=True` option in the `predict()` function, the cropped images are saved in the `project/predict/crops/classname/image.jpg` directory by default. The only customizable sections of this path are the `project` and `name` parameters that you can specify in the `predict()` function.

Your idea to customize the path such as 'presenter's name/person' and to save all the output images in that specific directory sounds like a valuable feature suggestion. While you can't currently do this directly within the `predict()` function, you can achieve it with a minor workaround.

After the `predict()` function has saved your cropped images, you can move these saved images to your desired directory with a standard file operation. Python's `shutil` library helps with that, offering functions like `shutil.move()` to relocate files from one directory to another.

Remember that your suggestion for further path customizability is a valuable one. We always welcome such innovative ideas as they help us improve the flexibility and usability of our models. Thank you for being a part of the YOLO community. We appreciate your understanding and support.

**Comment by Zy-23** [comment]
@glenn-jocher Hi, thank you for your response, I will be looking at how I shall modify my function to work around it. It's great to hear that my idea may contribute to the future improvement of YOLO!

**Comment by glenn-jocher** [comment]
@Zy-23, you're welcome! I'm glad to hear you found the response helpful! We truly appreciate such constructive ideas from our users and we look forward to implementing suggestions like yours in future updates of YOLOv8. Workarounds can be a bit of an extra step, but they often offer a good bridge until we can make those improvements to the software directly. Thank you for your understanding and participation in our YOLO community!
