### ISSUE TITLE
Allow passing output path/filename to export command

### ISSUE THREAD

**Issue by sstainba** [ultralytics/ultralytics#4503]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I would like to be able to specify the output path/file when exporting a model.

### Use case

I custom train several models via docker and have mapped folders.  It would be easier to export to a single location and provide different file names based on training params or export params.  For example, I export every model with the latest opset and also to opset 15 (for compatibility).  I would like to export the files to something like my_model_opset15.onnx and my_model_latest.onnx.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sstainba thank you for your suggestion and sharing your use case with us.

We understand the need for flexibility when exporting models, especially when working with multiple models and specific naming conventions. Adding the feature to specify an output path or filename during the model export process is indeed a valuable suggestion.

While this feature is not currently available with YOLOv8, we'll definitely consider this for future iterations. We always strive to make the Ultralytics YOLOv8 more user-friendly and efficient by incorporating useful features based on the community feedback.

We appreciate that you have taken the time to give us this feedback and help us improve. Your use case is quite comprehensive, and it will indeed add value to the custom workflow setups in machine learning operations. Please note that the timeline of this feature's implementation would depend on our current development roadmap and priorities.

Don't hesitate to reach out if you have further ideas or suggestions. We greatly value contributions from our community!

**Comment by sstainba** [comment]
Why was this closed as "not planned" when the initial email said it was a great suggestion and useful?
________________________________

**Comment by glenn-jocher** [comment]
Hello @sstainba,

I apologize for any confusion caused, and I appreciate your keen interest in this feature. 

The status of "not planned" doesn't necessarily mean that your suggestion was not valuable. Indeed, we see it as a great suggestion. When deciding about the roadmap of upcoming features, we have to consider multiple aspects like the team's current priorities, development pipeline, and the overall fit with the existing system's architecture.

While your feature suggestion is indeed useful, it might not fit within our immediate plans due to various reasons. However, we maintain a record of all feature suggestions, and they are evaluated regularly. So `not planned` does not mean `never`.

Once again, I appreciate your patience in this matter and your continued support for YOLOv8. Please continue to share your valuable feedback and suggestions. They help us improve and serve the community better.

**Comment by hartwoolery** [comment]
+1 I think this should be a trivial feature to implement

**Comment by glenn-jocher** [comment]
@hartwoolery thank you for your feature request. Currently, the ability to specify an output path or filename directly in the export command is not supported in the Ultralytics YOLOv8 repository. However, I understand how this feature could be beneficial for managing exports, especially when dealing with multiple models and compatibility requirements.

As a workaround, you can use the Python API to export your models and specify the output path and filename. Here's an example of how you could do this:

```python
from ultralytics import YOLO

# Load your custom trained model
model = YOLO('path/to/your/custom_model.pt')

# Export the model to ONNX format with a specific opset and filename
model.export(format='onnx', opset=15, path='path/to/output/my_model_opset15.onnx')
model.export(format='onnx', path='path/to/output/my_model_latest.onnx')
```

In the example above, the `path` argument is used to specify the output directory and filename for the exported model. Please note that this is a hypothetical example, as the current version of YOLOv8 does not support the `path` argument in the `export` method.

If you are not able to submit a PR for this feature, the Ultralytics team will take note of your request and may consider it for future updates. Your feedback is valuable, and such enhancements can help improve the usability of the software for all users. Thank you for contributing to the YOLOv8 community!

**Comment by glenn-jocher** [comment]
@mayorblock hi there! Absolutely, we'd be thrilled to review a PR for this feature 😊. Your contribution would be greatly appreciated by the community. If you need any guidance or have questions as you work on it, feel free to reach out. Looking forward to your PR! 🚀

**Comment by stevezkw1998** [comment]
> hypothetical example

Hi @glenn-jocher , just a kind suggestion, I think highlighting this code snippet as hypothetical example may help reduce potential misunderstandings, in my humble opinion.

Because at first glance, it is very easy to be seen as 'HERE is the executable code'

**Comment by johnnynunez** [comment]
Was this finally done?

**Comment by mayorblock** [comment]
@johnnynunez I had trouble finding the time but aim to have a PR sometime this week.

**Comment by strickvl** [comment]
Just throwing in my experience here. This seems l

> @hartwoolery thank you for your feature request. Currently, the ability to specify an output path or filename directly in the export command is not supported in the Ultralytics YOLOv8 repository. However, I understand how this feature could be beneficial for managing exports, especially when dealing with multiple models and compatibility requirements.
> 
> As a workaround, you can use the Python API to export your models and specify the output path and filename. Here's an example of how you could do this:
> 
> ```python
> from ultralytics import YOLO
> 
> # Load your custom trained model
> model = YOLO('path/to/your/custom_model.pt')
> 
> # Export the model to ONNX format with a specific opset and filename
> model.export(format='onnx', opset=15, path='path/to/output/my_model_opset15.onnx')
> model.export(format='onnx', path='path/to/output/my_model_latest.onnx')
> ```
> 
> In the example above, the `path` argument is used to specify the output directory and filename for the exported model. Please note that this is a hypothetical example, as the current version of YOLOv8 does not support the `path` argument in the `export` method.
> 
> If you are not able to submit a PR for this feature, the Ultralytics team will take note of your request and may consider it for future updates. Your feedback is valuable, and such enhancements can help improve the usability of the software for all users. Thank you for contributing to the YOLOv8 community!

This `model.export(format='onnx', path='...')` trick doesn't seem to work with the current version of ultralytics, btw.

**Comment by johnnynunez** [comment]
> Just throwing in my experience here. This seems l
> 
> > @hartwoolery thank you for your feature request. Currently, the ability to specify an output path or filename directly in the export command is not supported in the Ultralytics YOLOv8 repository. However, I understand how this feature could be beneficial for managing exports, especially when dealing with multiple models and compatibility requirements.
> > As a workaround, you can use the Python API to export your models and specify the output path and filename. Here's an example of how you could do this:
> > ```python
> > from ultralytics import YOLO
> > 
> > # Load your custom trained model
> > model = YOLO('path/to/your/custom_model.pt')
> > 
> > # Export the model to ONNX format with a specific opset and filename
> > model.export(format='onnx', opset=15, path='path/to/output/my_model_opset15.onnx')
> > model.export(format='onnx', path='path/to/output/my_model_latest.onnx')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the example above, the `path` argument is used to specify the output directory and filename for the exported model. Please note that this is a hypothetical example, as the current version of YOLOv8 does not support the `path` argument in the `export` method.
> > If you are not able to submit a PR for this feature, the Ultralytics team will take note of your request and may consider it for future updates. Your feedback is valuable, and such enhancements can help improve the usability of the software for all users. Thank you for contributing to the YOLOv8 community!
> 
> This `model.export(format='onnx', path='...')` trick doesn't seem to work with the current version of ultralytics, btw.



> Just throwing in my experience here. This seems l
> 
> > @hartwoolery thank you for your feature request. Currently, the ability to specify an output path or filename directly in the export command is not supported in the Ultralytics YOLOv8 repository. However, I understand how this feature could be beneficial for managing exports, especially when dealing with multiple models and compatibility requirements.
> > As a workaround, you can use the Python API to export your models and specify the output path and filename. Here's an example of how you could do this:
> > ```python
> > from ultralytics import YOLO
> > 
> > # Load your custom trained model
> > model = YOLO('path/to/your/custom_model.pt')
> > 
> > # Export the model to ONNX format with a specific opset and filename
> > model.export(format='onnx', opset=15, path='path/to/output/my_model_opset15.onnx')
> > model.export(format='onnx', path='path/to/output/my_model_latest.onnx')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the example above, the `path` argument is used to specify the output directory and filename for the exported model. Please note that this is a hypothetical example, as the current version of YOLOv8 does not support the `path` argument in the `export` method.
> > If you are not able to submit a PR for this feature, the Ultralytics team will take note of your request and may consider it for future updates. Your feedback is valuable, and such enhancements can help improve the usability of the software for all users. Thank you for contributing to the YOLOv8 community!
> 
> This `model.export(format='onnx', path='...')` trick doesn't seem to work with the current version of ultralytics, btw.
https://github.com/ultralytics/ultralytics/blob/c47eec898f9b473d71e6262352ffd7107e091c28/ultralytics/engine/exporter.py#L219

```python
        if file.suffix in {".yaml", ".yml"}:
            file = Path(file.name)
            file = Path(self.args.project + '/' + file.name if self.args.project is not None else file.name)
```

**Comment by mayorblock** [comment]
@glenn-jocher (@johnnynunez ) I finally got around to it :) on #11817 

Looking forward to your comments :)

**Comment by glenn-jocher** [comment]
Hi @mayorblock, that's great news! 😊 Thanks for putting in the effort to work on this. We'll review your PR on #11817 soon and get back to you with any feedback. Looking forward to potentially merging your contribution! 🚀

**Comment by cory-garms** [comment]
what is the latest on this?

**Comment by glenn-jocher** [comment]
Hi @cory-garms,

Thanks for following up! The feature to specify an output path/filename during model export has been implemented and is currently under review in PR #11817. We appreciate your patience and contributions to the community. Stay tuned for updates as we finalize this enhancement! 🚀

**Comment by Segnaly-2021** [comment]
Hi there, any news for this feature?

**Comment by glenn-jocher** [comment]
@Segnaly-2021 hi there, the feature to specify an output path/filename during export is under review in PR #11817. Please stay tuned for updates.

**Comment by mayorblock** [comment]
Hi @Segnaly-2021 I made an initial proposal in May that the maintainers did not like. I spent to much time on it and gave up at the time.

I am back and will give another honest attempt :) please have a look at the PR to see if it fits your use case so I can try to make it into something useful.

**Comment by rajhlinux** [comment]
This is why I demise Python and it is unfortunate Python is riddled in the AI industry (Thankfully only in the software realm and not in hardware realm). In the coming future, humans using Python will be worthless, Thanks to AI 😃 Thus AI using lower level language to program AI will be resurrected. 😎

I am using Yolov8 because it's clearly out performs Yolov11 in detection.

Anyhow I find it absurd that it is not possible to specify the location where the model inference would be saved. I get the error below:

```
(myenv) F:\AI_Componets\AI_Projects\mangus_ai>yolo export model=F:\AI_Componets\YOLOv8\Models\detection_coco\yolov8x.pt format=onnx dynamic=False imgsz=640 half=True simplify=False batch=1 device=0 workspace=4096 opset=20 path='F:/AI_Componets/AI_Projects/mangus_ai/Exported_Yolov8_Models/a.onnx'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "F:\AI_Componets\AI_Projects\mangus_ai\myenv\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "F:\AI_Componets\AI_Projects\mangus_ai\myenv\Lib\site-packages\ultralytics\cfg\__init__.py", line 904, in entrypoint
    check_dict_alignment(full_args_dict, overrides)
  File "F:\AI_Componets\AI_Projects\mangus_ai\myenv\Lib\site-packages\ultralytics\cfg\__init__.py", line 486, in check_dict_alignment
    raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'path' is not a valid YOLO argument. Similar arguments are i.e. ['batch=16'].

    Arguments received: ['yolo', 'export', 'model=F:\\AI_Componets\\YOLOv8\\Models\\detection_coco\\yolov8x.pt', 'format=onnx', 'dynamic=False', 'imgsz=640', 'half=True', 'simplify=False', 'batch=1', 'device=0', 'workspace=4096', 'opset=20', "path='F:/AI_Componets/AI_Projects/mangus_ai/Exported_Yolov8_Models/a.onnx'"]. Ultralytics 'yolo' commands use the following syntax:

        yolo TASK MODE ARGS

        Where   TASK (optional) is one of {'pose', 'obb', 'segment', 'classify', 'detect'}
                MODE (required) is one of {'track', 'val', 'export', 'benchmark', 'predict', 'train'}
                ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
                    See all ARGS at https://docs.ultralytics.com/usage/cfg or with 'yolo cfg'

    1. Train a detection model for 10 epochs with an initial learning_rate of 0.01
        yolo train data=coco8.yaml model=yolo11n.pt epochs=10 lr0=0.01

    2. Predict a YouTube video using a pretrained segmentation model at image size 320:
        yolo predict model=yolo11n-seg.pt source='https://youtu.be/LNwODJXcvt4' imgsz=320

    3. Val a pretrained detection model at batch-size 1 and image size 640:
        yolo val model=yolo11n.pt data=coco8.yaml batch=1 imgsz=640

    4. Export a YOLO11n classification model to ONNX format at image size 224 by 128 (no TASK required)
        yolo export model=yolo11n-cls.pt format=onnx imgsz=224,128

    5. Ultralytics solutions usage
        yolo solutions count or in ['heatmap', 'queue', 'speed', 'workout', 'analytics', 'trackzone', 'inference'] source="path/to/video/file.mp4"

    6. Run special commands:
        yolo help
        yolo checks
        yolo version
        yolo settings
        yolo copy-cfg
        yolo cfg
        yolo solutions help

    Docs: https://docs.ultralytics.com
    Solutions: https://docs.ultralytics.com/solutions/
    Community: https://community.ultralytics.com
    GitHub: https://github.com/ultralytics/ultralytics
``` 

Boss man Glenn, gave an AI generated response in using the 'path=' variable which doesn't even work. 🤣

**Comment by glenn-jocher** [comment]
@rajhlinux thank you for your detailed feedback. The `path` argument is currently not supported in the `export` command, which is why you encountered this error. However, specifying a custom output path is a feature being considered for future updates. For now, you can manually move the exported file to your desired location after export. We appreciate your patience and encourage you to stay updated via [our documentation](https://docs.ultralytics.com/). If you’d like to contribute to this functionality, feel free to submit a PR!
