### ISSUE TITLE
Deploy YOLOv8 Model in Azure ML

### ISSUE THREAD

**Issue by Damed911** [ultralytics/ultralytics#4505]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, so recently I've trained a YOLOv8 model using Azure ML with a custom environment. Now, I want to deploy it within the Azure ML itself to run the model in a cloud platform. There's a section where I must store a Python script for inferencing. Is there any reference that I can use for the inferencing script? Thanks!

**Comment by glenn-jocher** [comment]
@Damed911 hello!

First of all, we thank you for choosing the YOLOv8 model in your project and your interest to deploy it in Azure ML.

To deploy your trained YOLOv8 model in Azure ML, you will indeed require a Python script that the deployed service will use for inference. The script would generally need to have two main components: an `init()` function and a `run(data)` function.

The `init()` function is used for the initialization of your model. In this function, you'll typically load your trained model using the respective model loading functionalities of the YOLOv8 Ultralytics API.

The `run(data)` function is then used to run your model on new input data. Here, you would pre-process the input data, run it through your model to get predictions, and finally post-process the predictions before returning them.

Unfortunately, as it stands we don't have a ready reference available for creating this Python script specifically for YOLOv8 with Azure ML. However, the general structure and process would remain the same as described above. I'm confident you can adapt general Python inferencing scripts to work specifically with YOLOv8. 

Remember to use functions from the Ultralytics API to load your model and perform predictions. The YOLOv8 Ultralytics API is rather intuitive to use, so this should be relatively straightforward.

We wish you the best of luck with your deployment, and don't hesitate to ask if you have more questions. We're here to help!

Best Regards,
Ultralytics Team

**Comment by LarsKemmann** [comment]
@glenn-jocher I'm in a similar situation, and it would be really helpful to have an inferencing script reference that we can use for this. Especially for those of us who aren't necessarily Python developers or aren't used to the AI/ML space, having to first learn a whole bunch of Python (with no idea of how much I need to learn) plus figure out what a good "general Python inferencing script" is to use -- and how to adapt it -- are significant friction points that make this almost a non-starter when time-to-market is important.

**Comment by glenn-jocher** [comment]
@LarsKemmann hello, thanks for reaching out and for your interest in deploying YOLOv8 models. 

I understand your concerns the need for an example inferencing script, and how intimidating starting from scratch can seem, especially if you're relatively new to Python or AI/ML in general.

While we currently don't have a pre-made inferencing script available for YOLOv8, the basic structure of one should indeed consist of two parts: `init()` and `run(data)`. 

In `init()`, you will load your model using the respective functions from the Ultralytics API. Then, in `run(data)`, the data preprocessing, prediction generation, and prediction post-processing steps are run. 

Although it might feel overwhelming initially, reusing and adapting existing scripts and examples can prove to be a very effective way of learning, and a practical starting point. 

We are continuously working on improving our documentation and providing more user-friendly guides, and we value your feedback. Providing an example script is something we will take into consideration. 

Feel free to reach out if you have any specific questions about the process, and remember, the ML community is vast and typically very open to helping newcomers.

Best of luck with your deployment!

**Comment by LarsKemmann** [comment]
@glenn-jocher That's disappointing... While we wait (for possibly a very long time) for that example script, could you maybe point us to some existing scripts in the meantime, preferably ones that you know work well with YOLOv8? I literally have no idea where on the Internet I should start.

The best thing would be if your Azure ML guidance was a true end-to-end tutorial that also offered to explain the bits of Python that are being used, instead of just "set up your Conda environment" (add an info tip for 'what's a Conda environment?' that the user can hover on), for example.

**Comment by glenn-jocher** [comment]
@LarsKemmann hello! We certainly understand your concerns and the need for a functional example to better understand the process. While we can't direct you to a specific URL, we can give you some guidance on what you could look for when searching the internet. 

Firstly, the inferencing script is designed to help the Azure ML service to understand how exactly to use your trained model. The script involves two main functions: `init()` and `run()`. 

For the `init()` function, you should look for examples of how to load a trained model using PyTorch or specifically Ultralytics YOLOv8. Usually, it involves specifying the path to your saved model weights and loading these weights into the model architecture. 

For the `run()` function, this is where you provide instructions on what to do with new data that the model sees. Typically this involves preprocessing the new input data into the format expected by the model, running inference or prediction on this data, and then post-processing the output into a format that's easy to understand. 

As for explaining Python, numerous tutorials and courses can help you understand the basics of Python programming. Ideally, you would want to explore Python tutorials that focus on data manipulation, such as understanding how to work with lists, arrays, and matrices, all of which are common data types when working with machine learning models.

Regarding your suggestion for an end-to-end tutorial, we appreciate your feedback and will certainly consider it for our future guides. 

We hope this guidance helps you in finding the right resources. Even though the initial learning process could be challenging, with time, it will start to make sense. Please feel free to ask if you have further questions!

**Comment by ouphi** [comment]
Hi @LarsKemmann @Damed911 here is an example of a script to run inference on an online endpoint:

```python
import os
import json
from ultralytics import YOLO

def init():
    global model
    model_path = os.path.join(
        os.getenv("AZUREML_MODEL_DIR"), "best.pt"
    )
    model = YOLO(model_path)


def run(raw_data):
    image_url = json.loads(raw_data)["image_url"]
    results = model(image_url)
    result = results[0]
    serialized_result = json.loads(result.tojson())
    return serialized_result
```

You can find [an example showing how to deploy it on an AzureML online endpoint here](https://github.com/ouphi/yolov8-with-azureml/tree/main#deploy-model-for-inference). The described solution use a custom Dockerfile and deploys the endpoint with the az cli.

**Comment by glenn-jocher** [comment]
Hello @ouphi and @Damed911,

I see that you're interested in deploying your trained YOLOv8 model on an AzureML online endpoint. The process involves creating a custom Dockerfile and deploying the endpoint with the Azure CLI. 

The deployment is implemented using a scoring script, which consists of two main functions: `init()` and `run(raw_data)`.

In the `init()` function, the model is loaded. This is achieved by defining a global variable, `model`, and assigning it to the YOLOv8 model loaded from the path specified in `"AZUREML_MODEL_DIR"`.

In the `run(raw_data)` function, inference is run on the input image. The function takes `raw_data` as an argument, deriving an image URL from it. The `model` global variable defined in `init()` is then used to perform inference on this image. 

Given results, the function constructs and returns a serialized version of the results object. This serialized object could then ideally be used in the desired application.

I hope this helps you understand the basic structure and functioning of the scoring script for deploying a trained model in AzureML!

Please don't hesitate to ask if you have further questions.
