### ISSUE TITLE
after update ultralytics 8.0.7 nothing working 

### ISSUE THREAD

**Issue by kyoko9000** [ultralytics/ultralytics#451]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

import cv2
from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

# Use the model
results = model("0")  # predict on an image

Ultralytics YOLOv8.0.7  Python-3.9.13 torch-1.13.1+cpu CPU
Fusing layers... 
YOLOv8n summary: 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
1/1: 0...  Success (inf frames 640x480 at 30.00 FPS)

Traceback (most recent call last):
  File "D:\9. python project\71. yolov8\main.py", line 8, in <module>
    results = model("0")  # predict on an image
  File "D:\9. python project\71. yolov8\venv\lib\site-packages\ultralytics\yolo\engine\model.py", line 58, in __call__
    return self.predict(source, stream, verbose, **kwargs)
  File "D:\9. python project\71. yolov8\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\9. python project\71. yolov8\venv\lib\site-packages\ultralytics\yolo\engine\model.py", line 138, in predict
    return predictor(stream=stream, verbose=verbose)
  File "D:\9. python project\71. yolov8\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\9. python project\71. yolov8\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 160, in __call__
    return list(chain(*list(self.stream_inference(source, model, verbose))))  # merge list of Result into one
  File "D:\9. python project\71. yolov8\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 197, in stream_inference
    self.show(p)
  File "D:\9. python project\71. yolov8\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 248, in show
    im0 = self.annotator.result()
AttributeError: 'NoneType' object has no attribute 'result'

i try with webcam, video.mp4 and only working with image when i put save=True

### Environment

GitPython | 3.1.30 | 3.1.30
-- | -- | --
Markdown | 3.4.1 | 3.4.1
MarkupSafe | 2.1.1 | 2.1.1
Pillow | 9.4.0 | 9.4.0
PyYAML | 6.0 | 6.0
Pygments | 2.14.0 | 2.14.0
Werkzeug | 2.2.2 | 2.2.2
absl-py | 1.3.0 | 1.4.0
antlr4-python3-runtime | 4.9.3 | 4.11.1
asttokens | 2.2.1 | 2.2.1
backcall | 0.2.0 | 0.2.0
cachetools | 5.2.1 | 5.2.1
certifi | 2022.12.7 | 2022.12.7
charset-normalizer | 2.1.1 | 3.0.1
colorama | 0.4.6 | 0.4.6
contourpy | 1.0.6 | 1.0.7
cycler | 0.11.0 | 0.11.0
decorator | 5.1.1 | 5.1.1
executing | 1.2.0 | 1.2.0
fonttools | 4.38.0 | 4.38.0
gitdb | 4.0.10 | 4.0.10
google-auth | 2.16.0 | 2.16.0
google-auth-oauthlib | 0.4.6 | 0.8.0
grpcio | 1.51.1 | 1.51.1
hydra-core | 1.3.1 | 1.3.1
idna | 3.4 | 3.4
importlib-metadata | 6.0.0 | 6.0.0
ipython | 8.8.0 | 8.8.0
jedi | 0.18.2 | 0.18.2
kiwisolver | 1.4.4 | 1.4.4
matplotlib | 3.6.2 | 3.6.3
matplotlib-inline | 0.1.6 | 0.1.6
numpy | 1.24.1 | 1.24.1
oauthlib | 3.2.2 | 3.2.2
omegaconf | 2.3.0 | 2.3.0
opencv-python | 4.7.0.68 | 4.7.0.68
packaging | 23.0 | 23.0
pandas | 1.5.2 | 1.5.2
parso | 0.8.3 | 0.8.3
pickleshare | 0.7.5 | 0.7.5
pip | 22.3.1 | 22.3.1
prompt-toolkit | 3.0.36 | 3.0.36
protobuf | 3.20.3 | 4.21.12
psutil | 5.9.4 | 5.9.4
pure-eval | 0.2.2 | 0.2.2
pyasn1 | 0.4.8 | 0.4.8
pyasn1-modules | 0.2.8 | 0.2.8
pyparsing | 3.0.9 | 3.0.9
python-dateutil | 2.8.2 | 2.8.2
pytz | 2022.7 | 2022.7.1
requests | 2.28.1 | 2.28.2
requests-oauthlib | 1.3.1 | 1.3.1
rsa | 4.9 | 4.9
scipy | 1.10.0 | 1.10.0
seaborn | 0.12.2 | 0.12.2
setuptools | 65.5.1 | 66.0.0
six | 1.16.0 | 1.16.0
smmap | 5.0.0 | 5.0.0
stack-data | 0.6.2 | 0.6.2
tensorboard | 2.11.0 | 2.11.2
tensorboard-data-server | 0.6.1 | 0.6.1
tensorboard-plugin-wit | 1.8.1 | 1.8.1
thop | 0.1.1.post2209072238 | 0.1.1.post2209072238
torch | 1.13.1 | 1.13.1
torchvision | 0.14.1 | 0.14.1
tqdm | 4.64.1 | 4.64.1
traitlets | 5.8.1 | 5.8.1
typing-extensions | 4.4.0 | 4.4.0
ultralytics | 8.0.7 | 8.0.7
urllib3 | 1.26.14 | 1.26.14
wcwidth | 0.2.5 | 0.2.6
wheel | 0.38.4 |  
zipp | 3.11.0 |  

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kyoko9000 we've pushed a fix for this issue in #452. Please try this by git cloning main and let us know if it works. It will be part of 8.0.8 scheduled to be deployed tomorrow.

```python
# Git clone install 
!git clone https://github.com/ultralytics/ultralytics
%pip install -qe ultralytics
```
