### ISSUE TITLE
Yolov8 in a pipeline

### ISSUE THREAD

**Issue by coder-glitche** [ultralytics/ultralytics#4525]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey there @glenn-jocher i have my yolov8 detection model running on my onboard jetson on a drone instead of performing rtsp im feeding my images from my camera to model through a folder (more reliable in my case) how do i get the model to predict or inference continuously on newly incoming images into folder without having to load the model again after 1 round of prediction as it takes 10 to 12 seconds for loading the model?? Thanks a lot!!!

**Comment by glenn-jocher** [comment]
@coder-glitche hi there,

Thanks for bringing this issue to light. I understand the need to maintain the efficiency of having the model continuously inference without the delay of loading the model every time there's a new image.  

You can indeed run YOLOv8 continuously on incoming images. The model doesn't need to be reloaded for each new image; instead, it can be loaded once and stay in memory to process new images as they come.

When you start your inference loop, make sure you load the model before entering the loop where you're checking for new images in your folder and performing prediction. This way, the model stays loaded once and the predictions should run continuously as each new image is brought into the folder without having the load delay for every image.

Never hesitate to get in touch if you have further inquiries. Your contributions are highly valued by the YOLOv8 community and the Ultralytics team.

Best Regards,
Glenn Jocher
