### ISSUE TITLE
ModuleNotFoundError: No module named 'ultralytics.models.sam'

### ISSUE THREAD

**Issue by harufumigithub** [ultralytics/ultralytics#4529]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I get this error:
Traceback (most recent call last):
  File "/mnt/1a8b3160-241c-466f-aa1b-79f0591f7f56/workspace/yolov8/anno/mobileSam.py", line 3, in <module>
    from ultralytics.models.sam import Predictor as SAMPredictor
ModuleNotFoundError: No module named 'ultralytics.models.sam'

import os
from ultralytics import SAM
from ultralytics.models.sam import Predictor as SAMPredictor

model = SAM('mobile_sam.pt')
directory_path = 'test_image_folder'
for filename in os.listdir(directory_path):
    if filename.endswith('.png'):  # Check that it's a PNG image
        image_path = os.path.join(directory_path, filename)
        model.predict(image_path, points=[160, 80], labels=[1])

### Environment

Name: ultralytics
Version: 8.0.132
Summary: Ultralytics YOLOv8 for SOTA object detection, multi-object tracking, instance segmentation, pose estimation and image classification.
Home-page: https://github.com/ultralytics/ultralytics
Author: Ultralytics
Author-email: hello@ultralytics.com
License: AGPL-3.0
Location: /home/trupass/miniconda3/lib/python3.9/site-packages
Requires: matplotlib, opencv-python, pandas, Pillow, psutil, PyYAML, requests, scipy, seaborn, torch, torchvision, tqdm
Required-by: 
ubuntu22.04
python 3.9.12

### Minimal Reproducible Example

import os
from ultralytics import SAM
from ultralytics.models.sam import Predictor as SAMPredictor

model = SAM('mobile_sam.pt')
directory_path = 'test_image_folder'
for filename in os.listdir(directory_path):
    if filename.endswith('.png'):  # Check that it's a PNG image
        image_path = os.path.join(directory_path, filename)
        model.predict(image_path, points=[160, 80], labels=[1])

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@harufumigithub for valid usage examples see https://docs.ultralytics.com/models/sam/#sam-prediction-example

<img width="1895" alt="Screenshot 2023-08-24 at 03 16 31" src="https://github.com/ultralytics/ultralytics/assets/26833433/197489e9-1191-4a35-8676-0125fc99301a">
