### ISSUE TITLE
SIGSEGV segmentation fault (address boundary error)

### ISSUE THREAD

**Issue by Dandandooo** [ultralytics/ultralytics#453]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Every time I run anything with YOLO, the code exits with the following error message
```
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```
Whenever I run it in terminal with the CLI interface, it crashes with the following error messages

bash:
```
Segmentation fault: 11
```
zsh:
```
[1]    85359 segmentation fault  yolo task=segment mode=predict model=yolov8n-seg.pt conf=0.25 
```
fish:
```
fish: Job 1, 'yolo task=segment mode=predic...' terminated by signal SIGSEGV (Address boundary error)
```

### Environment

- YOLO: YOLOv8.0.6
- OS: MacOS Ventura (intel)
- CPU: Intel core i5 8210-Y
- Python: 3.10.6
- PyTorch: 1.11.0

### Minimal Reproducible Example

My python file:
``` python3
from ultralytics import YOLO
model = YOLO('yolov8n.pt')
model.predict(source='0')
```

My terminal command:
``` bash
yolo task=segment mode=predict model=yolov8n-seg.pt conf=0.25 source='https://paintingandframe.com/art-imgs/william_strutt/a_warm_response-5596.jpg'
```

### Additional

When I run the command, it runs and then exits. Only sometimes does it output an image though.

``` bash
Found https://paintingandframe.com/art-imgs/william_strutt/a_warm_response-5596.jpg locally at a_warm_response-5596.jpg
Ultralytics YOLOv8.0.6 🚀 Python-3.10.6 torch-1.11.0 CPU
Fusing layers... 
YOLOv8n-seg summary: 195 layers, 3404320 parameters, 0 gradients, 12.6 GFLOPs
image 1/1 /my_directory/a_warm_response-5596.jpg: 640x608 1 dog, 325.5ms
Speed: 2.9ms pre-process, 325.5ms inference, 14.8ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/segment/predict
fish: Job 1, 'yolo task=segment mode=predic...' terminated by signal SIGSEGV (Address boundary error)
```

IT ALSO JUST CRASHES WHEN I WRITE 'YOLO' IN THE TERMINAL
``` bash
yolo
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
I'm not able to reproduce this. Is this problem reproducible for you?

**Comment by Dandandooo** [comment]
It happens whenever I use yolov8. I switched to yolov5 and it seemed to work

**Comment by pderrenger** [comment]
@Dandandooo it's great to hear that you found a workaround with YOLOv5. While YOLOv8 is constantly being improved, sometimes different versions or models can behave differently based on specific use cases. If you encounter any other issues or need further assistance, feel free to let us know!

**Comment by gth-ai** [comment]
hi @Dandandooo 
I get the same issue, i've just updated ultralytics, torch and numpy:

- pip install --upgrade ultralytics
- pip install --upgrade numpy
- pip install --upgrade torch
