### ISSUE TITLE
prediction count

### ISSUE THREAD

**Issue by DarkLord-13** [ultralytics/ultralytics#4535]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am using custom-trained weights to detect objects, how do I get the number of bounding boxes being made on every image?
Is there some hyper-parameter or different code to extract the number of bounding boxes being made per image.

**Comment by Kayzwer** [comment]
@DarkLord-13 
```
model = YOLO("./path/to/pt")
result = model.predict("./path/to/img")[0]
print(len(result.data))
```

**Comment by andresinsitu** [comment]
@DarkLord-13 You mean before NMS or the final detections? if it is the final detections it would be easy to just save the detections and then count the rows of every txt file with a little script.

**Comment by DarkLord-13** [comment]
> @DarkLord-13 You mean before NMS or the final detections? if it is the final detections it would be easy to just save the detections and then count the rows of every txt file with a little script.

after the detection, the image is saved in the runs/detect/predict folder, all i want is to extract the number of bounding boxes made on that image by the model, i just want the integer value to display.

**Comment by DarkLord-13** [comment]
> @DarkLord-13
> 
> ```
> model = YOLO("./path/to/pt")
> result = model.predict("./path/to/img")[0]
> print(len(result.data))
> ```

not working bro
AttributeError: 'Results' object has no attribute 'data'. See valid attributes below.

**Comment by andresinsitu** [comment]
> > @DarkLord-13 You mean before NMS or the final detections? if it is the final detections it would be easy to just save the detections and then count the rows of every txt file with a little script.
> 
> after the detection, the image is saved in the runs/detect/predict folder, all i want is to extract the number of bounding boxes made on that image by the model, i just want the integer value to display.

To display where?

**Comment by Kayzwer** [comment]
> > @DarkLord-13
> > ```
> > model = YOLO("./path/to/pt")
> > result = model.predict("./path/to/img")[0]
> > print(len(result.data))
> > ```
> 
> not working bro AttributeError: 'Results' object has no attribute 'data'. See valid attributes below.

mbmb, change the line `print(len(result.data))` to `print(len(result.boxes.data))`

**Comment by DarkLord-13** [comment]
> > > @DarkLord-13 You mean before NMS or the final detections? if it is the final detections it would be easy to just save the detections and then count the rows of every txt file with a little script.
> > 
> > 
> > after the detection, the image is saved in the runs/detect/predict folder, all i want is to extract the number of bounding boxes made on that image by the model, i just want the integer value to display.
> 
> To display where?

i want to display it on my streamlit interface
input: image
output: image with bounding box and number of bounding boxes made(basically number of objects detected)

**Comment by DarkLord-13** [comment]
> print(len(result.boxes.data))

yes bro, that works! Thanks a lot!!!

**Comment by glenn-jocher** [comment]
@Kayzwer i'm glad to hear that the solution worked for you! Counting the length of the result.boxes.data gives you the total number of bounding boxes (i.e., detections) made on each image. If you have any other questions or run into any issues, feel free to post here. Thanks for using YOLOv8, and happy coding!

**Comment by DarkLord-13** [comment]
Just got to know that you are fucking creator of YOLO8.
Bro all the love and support for you, hopefully will be supporting the
cause financially too, very soon, as I finish college in 1.5 years.
Keep going brother!

If possible do help me out this another issue i posted... #4547

regards,
Nishant Kumar

**Comment by DarkLord-13** [comment]
Thanks bro.

Love and support❤️💪

**Comment by glenn-jocher** [comment]
@DarkLord-13,

It's support from users like you that keeps us going and wanting to do better. So, the gratitude is mutual!

Thank you for being part of the YOLOv8 community and for fostering such a positive environment. We appreciate your kind words and continued support.

Keep up the great work and never hesitate to reach out if you have further questions or issues.

Best,

Glenn Jocher

**Comment by DarkLord-13** [comment]
Definitely bhai (it means brother). Hope to talk to face to face some day,
I wish you the best health and life.

Great talking to you, even for a bit

Warm regards,
Nishant Kumar

**Comment by glenn-jocher** [comment]
@DarkLord-13 hey Nishant,

Your kind and encouraging words truly made my day. It's users like you, committed, supportive, and open to learning & sharing, who make our YOLOv8 community a fantastic place. 

I'm equally thrilled to have this conversation with you, and hopefully, we will get a chance to meet in person someday. Till then, keep experimenting, keep learning, and let's continue to push the boundaries of what's possible with object detection.

Take care of yourself and best of luck with everything.

Warm regards, 

Glenn Jocher

**Comment by glenn-jocher** [comment]
@DarkLord-13 Nishant,

Thank you so much for your kind and heartfelt words. The positive energy truly is inspiring. You and our other users are the reason we continue to strive and make YOLOv8 better every day.

May your journey in machine learning and AI be filled with many successes. Let's keep in touch, surely, and remember, the YOLOv8 community is here for you.

Take care and best wishes,

Glenn Jocher
