### ISSUE TITLE
training DetectionModel using only 1 class

### ISSUE THREAD

**Issue by catica** [ultralytics/ultralytics#4542]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello 👋 , 

I am trying to train a DetectionModel() using only one class. To do that, I'm specifying the number of classes on the Model instantiation and passing through the names variable. 

Below you can find a working (with error) example. 

```
import torch
from omegaconf import OmegaConf
from ultralytics import YOLO
from ultralytics.nn.tasks import (
    DetectionModel,
)
from ultralytics.utils.loss import v8DetectionLoss


class WrapperDetectionModel:
    def __init__(self, model, args):
        self.model = model
        self.model.model = model.model
        self.model.args = args


names = ["boat"]
n_classes = 1
# Load a model
model = DetectionModel(cfg="yolov8.yaml", nc=n_classes).to("cpu")
model.load(
    weights=torch.load(
        "yolov8n.pt"
    )
)

model.names = {nc: names[nc] for nc in range(n_classes)}
wrapped_model = WrapperDetectionModel(
    model=model, args=OmegaConf.create({"box": 7.5, "cls": 0.5, "dfl": 1.5})
) # This wrapping is only meant to make the new model usable by the loss function. 

loss = v8DetectionLoss(model=wrapped_model.model)

input_batch = torch.zeros((8, 3, 640, 640))
output = wrapped_model.model(input_batch)

batch = {}
batch["batch_idx"] = torch.arange(len(input_batch))
batch["bboxes"] = torch.rand((8, 4))
batch["cls"] = torch.ones(8)
loss_val = loss(preds=output, batch=batch)
```

However, I am getting the following error:

```
bbox_scores[mask_gt] = pd_scores[ind[0], :, ind[1]][mask_gt]  # b, max_num_obj, h*w
IndexError: index 1 is out of bounds for dimension 1 with size 1
```

It works if I change the n_classes to 2 and the corresponding names. 

My question is if there a way to train the model using a single class? Or if I can achieve this in another way. 

Ps. I would like to try and only use the DetectionModel class and the DetectionLoss class. 

Thanks 🙏

**Comment by glenn-jocher** [comment]
@catica hello,

Training a model with a single class is indeed possible. The problem you're experiencing is related to the tensor sizes during the loss computation. When you use only one class, the tensor dimensions are altered, which seems to be causing the index out of bounds error.

It appears that the model expects at least two classes for proper tensor construction. As a workaround, you could include a dummy class in your data, effectively training the model as a binary classifier (the object of interest or not). This means that you would keep the number of classes as 2, but only focus on the detection and metrics of your one class of interest. The dummy class will act as a placeholder and solve the dimensional issue without affecting your goal of detecting a single class.

This should fix the problem you're having. Can you please try it out and let me know? If you still have issues, we're here to assist you.

Thank you for using YOLOv8!
