### ISSUE TITLE
extract detected image from the model.predict() itself

### ISSUE THREAD

**Issue by DarkLord-13** [ultralytics/ultralytics#4547]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

AIM:
I am trying to create a basic streamlit based project, where my input is the image upoaded by user
I then want to give it to the model to predict the object in it(empty disk slots in data centre racks)
I am also extracting the number of objects detected via 'len(result.boxes.data)'
Now i want to finally display the bounded image and the number of objects detected

ISSUE:
Not able to give the YOLO model the uploaded image in a suitable format to carry out the prediction.
since i am deploying it on streamlit, i do not want to access any directory where the photo will be saved, i simply want it in some variable, so that i can display it from there itself

Please Help!!!

### Additional

current code:
import streamlit as st
from PIL import Image
from ultralytics import YOLO
import io
import os
from contextlib import redirect_stdout

img_path='[lens.google.com][80537].jpg'
def process_uploaded_image(uploaded_image):
    # Perform any image processing here (e.g., YOLO detection)
    # For demonstration purposes, simply return the same image
    image = Image.open(uploaded_image)
    model = YOLO('best.pt')
    with open(os.devnull, 'w') as devnull:
        with redirect_stdout(devnull):
            result = model.predict(image)[0]
    model.predict(image, save=True, verbose=False, line_width=1, show_labels=False, show_conf=False)[0]
    length = len(result.boxes.data)
    return image, length

st.title("Image Uploader")

uploaded_image = st.file_uploader("Choose an image...", type=["jpg", "png", "jpeg"])
if uploaded_image is not None:
    pil_image = Image.open(uploaded_image)

    image_width, image_height = pil_image.size
    
    st.image(uploaded_image, caption="Uploaded Image", width=image_width*1.5)
    process_button = st.button("Process Image")

    if process_button:
        # Process the uploaded image here (e.g., apply YOLO detection)
        processed_image, length = process_uploaded_image(uploaded_image)
        string = 'runs\detect\predict13\\' + img_path
        st.image(string, caption="Processed Image", width=image_width*1.5)
        st.subheader(f'EMPTY SLOTS: {length}')

**Comment by Kayzwer** [comment]
```
import cv2
from ultralytics import YOLO
from ultralytics.utils.plotting import Annotator


if __name__ == "__main__":
    model = YOLO("./path/to/.pt")
    img = cv2.imread("./path/to/img")
    result = model.predict(img)[0]
    color_list = [] # fill with color in (R, G, B)
    annotator = Annotator(img)
    for label in result.boxes.data:
        annotator.box_label(
            label[0:4],
            f"{result.names[label[-1].item()]} {round(label[-2], 2)}",
            color_list[label[-1].item()])
    cv2.imwrite("./img file name to save", annotator.im)
```

**Comment by glenn-jocher** [comment]
@Kayzwer the above code reads an image with `cv2.imread()` and performs object detection using the `model.predict()` function. It then creates an instance of the `Annotator` class, objects of which are used to add annotations (bounding boxes and labels, in this case) to the image.

For every detection in `result.boxes.data`, it adds a bounding box with the corresponding label to the image. The label is a combination of the predicted class name (accessed with `result.names[label[-1].item()]`) and confidence score (rounded to two decimal places).

The `box_label` function parameters are:
- `label[0:4]`: These are the bounding box coordinates.
- `f"{result.names[label[-1].item()]} {round(label[-2], 2)}"`: It is a formatted string that concatenates the detected class name and its corresponding confidence score.
- `color_list[label[-1].item()]`: This parameter corresponds to the color of the bounding box and its label.

Finally, it writes the image with annotations to the disk with `cv2.imwrite()`. Note that the file name should include the full path where you want the image to be saved along with the name of the image file itself.

Keep in mind that `color_list` should have enough colors for each unique class in your dataset since the class index is used to pick the color. Also ensure your model file (`.pt`) and image file paths are set correctly for your environment.

**Comment by DarkLord-13** [comment]
Thank you for your response, I'll get right to it.

**Comment by glenn-jocher** [comment]
@DarkLord-13 hi,

The explanation is indeed providing an overview of the python code you are working with. The code is designed to perform object detection in images. It uses the OpenCV library to read an image and then feeding this image to the YOLOv8 model to predict objects in the image.

The Annotator class in the code is used to overlay output from the YOLOv8 model (i.e., bounding boxes and labels) on the input image. Each object that is detected by the model is boxed with a distinct color and label, which indicates the class of the object and the model's confidence score for this prediction. These bounding boxes are plotted based on coordinates provided in the detection results.

Subsequently, the `box_label` function is called to draw these bounding boxes and the associated labels onto the image.

Finally, the processed image is saved to a file. The filename should include the desired path where the image should be saved.

It's important to ensure that there are enough distinct colors specified for all unique classes that exist in your dataset, otherwise there might be confusion in the drawn bounding boxes. Furthermore, it's essential to set the correct paths for your model and image files.

Hope that clarifies things for you! Let me know if you have any other questions.

**Comment by DarkLord-13** [comment]
> ```
> import cv2
> from ultralytics import YOLO
> from ultralytics.utils.plotting import Annotator
> 
> 
> if __name__ == "__main__":
>     model = YOLO("./path/to/.pt")
>     img = cv2.imread("./path/to/img")
>     result = model.predict(img)[0]
>     color_list = [] # fill with color in (R, G, B)
>     annotator = Annotator(img)
>     for label in result.boxes.data:
>         annotator.box_label(
>             label[0:4],
>             f"{result.names[label[-1].item()]} {round(label[-2], 2)}",
>             color_list[label[-1].item()])
>     cv2.imwrite("./img file name to save", annotator.im)
> ```

Thanks brother!

**Comment by DarkLord-13** [comment]
> @DarkLord-13 hi,
> 
> The explanation is indeed providing an overview of the python code you are working with. The code is designed to perform object detection in images. It uses the OpenCV library to read an image and then feeding this image to the YOLOv8 model to predict objects in the image.
> 
> The Annotator class in the code is used to overlay output from the YOLOv8 model (i.e., bounding boxes and labels) on the input image. Each object that is detected by the model is boxed with a distinct color and label, which indicates the class of the object and the model's confidence score for this prediction. These bounding boxes are plotted based on coordinates provided in the detection results.
> 
> Subsequently, the `box_label` function is called to draw these bounding boxes and the associated labels onto the image.
> 
> Finally, the processed image is saved to a file. The filename should include the desired path where the image should be saved.
> 
> It's important to ensure that there are enough distinct colors specified for all unique classes that exist in your dataset, otherwise there might be confusion in the drawn bounding boxes. Furthermore, it's essential to set the correct paths for your model and image files.
> 
> Hope that clarifies things for you! Let me know if you have any other questions.

Yes, I made the changes, my code is working exactly fine, let me know if i should post the code here for reference.
Thanks a lot!

**Comment by glenn-jocher** [comment]
@DarkLord-13, 

I'm glad to hear that your code is working well now! While it's not necessary to post your code here, feel free to do so if you believe it could benefit others in the community. Your willingness to contribute is greatly appreciated. 

Remember, if you encounter any other issues or have further questions in the future, we're here to help. Happy coding!

**Comment by DarkLord-13** [comment]
Thanks for you support bro! @glenn-jocher 

![image](https://github.com/ultralytics/ultralytics/assets/91314457/b23cbae0-11d4-4375-bebb-c4905ec40a41)


here is the proper working code:

BASIC WORKING:
1. It takes the image input from the user
2. Predicts the object 
3. Displays the original image and bounded image side by side
4. Also displays number of objects detected and its dimensions in xywh format
5. Just replace the model path with your own path
6. Gives you the option to select model confidence before detection

```
import PIL
import streamlit as st
from ultralytics import YOLO

# Give the path of the best.pt (best weights)
model_path = 'best.pt'

# Setting page layout
st.set_page_config(
    page_title="NISH(Neural Intelligence Synthesis Hub)",  # Setting page title
    page_icon="NK logo.jpeg",     # Setting page icon
    layout="wide",      # Setting layout to wide
    initial_sidebar_state="expanded",    # Expanding sidebar by default
    
)

# Creating sidebar
with st.sidebar:
    st.header("Image Config")     # Adding header to sidebar
    # Adding file uploader to sidebar for selecting images
    source_img = st.file_uploader(
        "Upload an image...", type=("jpg", "jpeg", "png", 'bmp', 'webp'))

    # Model Options
    confidence = float(st.slider(
        "Select Model Confidence", 25, 100, 40)) / 100

# Creating main page heading
st.title("Object Detection")
st.caption('Updload a photo by selecting :blue[Browse files]')
st.caption('Then click the :blue[Detect Objects] button and check the result.')
# Creating two columns on the main page
col1, col2 = st.columns(2)

# Adding image to the first column if image is uploaded
with col1:
    if source_img:
        # Opening the uploaded image
        uploaded_image = PIL.Image.open(source_img)
        image_width, image_height = uploaded_image.size
        # Adding the uploaded image to the page with a caption
        st.image(source_img,
                 caption="Uploaded Image",
                 width=image_width
                 )

try:
    model = YOLO(model_path)
except Exception as ex:
    st.error(
        f"Unable to load model. Check the specified path: {model_path}")
    st.error(ex)

if st.sidebar.button('Detect Objects'):
    res = model.predict(uploaded_image,
                        conf=confidence,
                        line_width=1, 
                        show_labels=False, 
                        show_conf=False
                        )
    boxes = res[0].boxes
    res_plotted = res[0].plot(labels=False, line_width=1)[:, :, ::-1]
    with col2:
        st.image(res_plotted,
                 caption='Detected Image',
                 width=image_width                 
                 )
        try:
            st.write(f'Number of empty slots detected: {len(boxes)}')
            with st.expander("Detection Results (xywh)"):                
                for box in boxes:
                    st.write(box.xywh)
        except Exception as ex:
            st.write("No image is uploaded yet!")
```import PIL
import streamlit as st
from ultralytics import YOLO

# Give the path of the best.pt (best weights)
model_path = 'best.pt'

# Setting page layout
st.set_page_config(
    page_title="NISH(Neural Intelligence Synthesis Hub)",  # Setting page title
    page_icon="NK logo.jpeg",     # Setting page icon
    layout="wide",      # Setting layout to wide
    initial_sidebar_state="expanded",    # Expanding sidebar by default
    
)

# Creating sidebar
with st.sidebar:
    st.header("Image Config")     # Adding header to sidebar
    # Adding file uploader to sidebar for selecting images
    source_img = st.file_uploader(
        "Upload an image...", type=("jpg", "jpeg", "png", 'bmp', 'webp'))

    # Model Options
    confidence = float(st.slider(
        "Select Model Confidence", 25, 100, 40)) / 100

# Creating main page heading
st.title("Object Detection")
st.caption('Updload a photo by selecting :blue[Browse files]')
st.caption('Then click the :blue[Detect Objects] button and check the result.')
# Creating two columns on the main page
col1, col2 = st.columns(2)

# Adding image to the first column if image is uploaded
with col1:
    if source_img:
        # Opening the uploaded image
        uploaded_image = PIL.Image.open(source_img)
        image_width, image_height = uploaded_image.size
        # Adding the uploaded image to the page with a caption
        st.image(source_img,
                 caption="Uploaded Image",
                 width=image_width
                 )

try:
    model = YOLO(model_path)
except Exception as ex:
    st.error(
        f"Unable to load model. Check the specified path: {model_path}")
    st.error(ex)

if st.sidebar.button('Detect Objects'):
    res = model.predict(uploaded_image,
                        conf=confidence,
                        line_width=1, 
                        show_labels=False, 
                        show_conf=False
                        )
    boxes = res[0].boxes
    res_plotted = res[0].plot(labels=False, line_width=1)[:, :, ::-1]
    with col2:
        st.image(res_plotted,
                 caption='Detected Image',
                 width=image_width                 
                 )
        try:
            st.write(f'Number of empty slots detected: {len(boxes)}')
            with st.expander("Detection Results (xywh)"):                
                for box in boxes:
                    st.write(box.xywh)
        except Exception as ex:
            st.write("No image is uploaded yet!")

**Comment by glenn-jocher** [comment]
@DarkLord-13 hi there, 

Thank you for sharing your solution encapsulating YOLOv8 model integration with the Streamlit app, it indeed seems quite insightful. 

The key functionality of your code revolves around uploading an image and passing it through the YOLOv8 model for object detection, while also allowing slider-based confidence level configuration. 

The use of Streamlit constructs like sidebar, columns and sliders presents a pretty neat way to make these processes and results quite interactive. 

After prediction and plotting, you're displaying the number of detected objects and their respective positions in the xywh format. This is a great demonstration of how the YOLOv8 inference data can be displayed.

Just a word of caution to users though, they must ensure that the path to the YOLOv8 model is correctly specified to avoid exceptions while loading the model.

Your endeavour certainly sets a good example of leveraging AI models into interactive web apps. Good work!

**Comment by DarkLord-13** [comment]
@glenn-jocher Hey there,

Thanks a lot bro for your consistent insights, it were really helpful to complete it!!!

**Comment by glenn-jocher** [comment]
@DarkLord-13

Hi,

I'm glad to hear that you found the insights helpful and were able to complete your task! It's always rewarding to know that my assistance can positively impact another developer's work. If you need any more help or have any questions in the future, feel free to reach out.

Happy coding!

**Comment by zoltanmaric** [comment]
Here's a much shorter version that gets you a `PIL`-image:
```python
    result = model.predict(input_image)

    # TODO: use all results, not just the first one
    bgr_array = result[0].plot()
    # For some reason, result.plot() returns a BGR array, so we have to invert
    # it like this. I found this in the docstring of plot.
    rgb_array = bgr_array[..., ::-1]
    output_image = Image.fromarray(rgb_array)
```

**Comment by glenn-jocher** [comment]
Hey there! 👋

Your approach looks good! Just a quick note: you're right about the BGR to RGB conversion. It's a common step when working with images in different libraries that handle color channels differently. Your code snippet effectively handles this conversion and creates a `PIL` image from the results. Nicely done!

If you ever need to handle multiple detections, you might consider iterating over `result` if it contains more than one detection. Here's a quick example:

```python
for detection in result:
    bgr_array = detection.plot()
    rgb_array = bgr_array[..., ::-1]
    output_image = Image.fromarray(rgb_array)
    # Now you can do something with each output_image
```

Keep up the great work! If you have more questions or need further assistance, feel free to ask. Happy coding! 🚀

**Comment by Leprechault** [comment]
> st.write(f'Number of empty slots detected: {len(boxes)}')
>             with st.expander("Detection Results (xywh)"):                
>                 for box in boxes:
>                     st.write(box.xywh)
>         except Exception as ex:
>             st.write("No image is uploaded yet!")

Please, it possible to show the number of detections by different objects? In my case, I have two custom objects and in `st.write(f'Number of empty slots detected: {len(boxes)}')` , but it shows all the sections and is not separated by target eg.:
Number of detection of 0: 3
Numeber of detection of 1: 15

**Comment by glenn-jocher** [comment]
@Leprechault hello!

Certainly, you can display the number of detections for each type of object by modifying your code to count occurrences of each class. Here’s a quick way to achieve this:

```python
from collections import Counter

# Assuming 'boxes' contains your detection results and each 'box' has a 'cls' attribute for the class index
class_counts = Counter([result.names[box.cls] for box in boxes])

# Display the counts for each class
for class_name, count in class_counts.items():
    st.write(f'Number of detection of {class_name}: {count}')
```

This code uses Python's `Counter` from the `collections` module to tally up how many times each class appears in your detections, and then it displays these counts. Make sure that `result.names` correctly maps class indices to their respective names as per your model's configuration.

Let me know if this helps or if you need further assistance!

**Comment by Leprechault** [comment]
> @Leprechault hello!
> 
> Certainly, you can display the number of detections for each type of object by modifying your code to count occurrences of each class. Here’s a quick way to achieve this:
> 
> ```python
> from collections import Counter
> 
> # Assuming 'boxes' contains your detection results and each 'box' has a 'cls' attribute for the class index
> class_counts = Counter([result.names[box.cls] for box in boxes])
> 
> # Display the counts for each class
> for class_name, count in class_counts.items():
>     st.write(f'Number of detection of {class_name}: {count}')
> ```
> 
> This code uses Python's `Counter` from the `collections` module to tally up how many times each class appears in your detections, and then it displays these counts. Make sure that `result.names` correctly maps class indices to their respective names as per your model's configuration.
> 
> Let me know if this helps or if you need further assistance!

Hello @glenn-jocher and thanks!! But not yet. My `boxes.cls[1:]` output is:

```
0: 5024x4032 9 bsbs, 8 wsbs, 27363.1ms
Speed: 273.4ms preprocess, 27363.1ms inference, 8.0ms postprocess per image at shape (1, 3, 5024, 4032)
tensor([0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 1.])
```
I  think that I need to take just only `tensor([0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 1.])` and count 0. and 1., but `Counter` doesn't work. I have an error:

```
class_counts = Counter(boxes.cls)
print(class_counts)
Counter({tensor(0.): 1, tensor(0.): 1, tensor(1.): 1, tensor(1.): 1, tensor(0.): 1, tensor(1.): 1, tensor(0.): 1, tensor(1.): 1, tensor(0.): 1, tensor(0.): 1, tensor(0.): 1, tensor(1.): 1, tensor(1.): 1, tensor(1.): 1, tensor(0.): 1, tensor(1.): 1})

```
Thanks in advance!

**Comment by glenn-jocher** [comment]
Hello @Leprechault,

Thanks for providing the additional details. It seems the issue arises because the `Counter` is trying to count tensor objects directly, which can lead to unexpected behavior due to how tensors are handled in memory.

To resolve this, you can convert the tensor values to integers before passing them to the `Counter`. Here's how you can modify your code:

```python
from collections import Counter

# Convert tensor values to integers
class_indices = [int(cls) for cls in boxes.cls]
class_counts = Counter(class_indices)

# Assuming 'result.names' maps class indices to names
for class_index, count in class_counts.items():
    class_name = result.names[class_index]
    st.write(f'Number of detection of {class_name}: {count}')
```

This approach ensures that the class indices are handled as standard integers, which should work seamlessly with the `Counter`. Let me know if this adjustment solves the issue! 🚀

**Comment by Leprechault** [comment]
> Hello @Leprechault,
> 
> Thanks for providing the additional details. It seems the issue arises because the `Counter` is trying to count tensor objects directly, which can lead to unexpected behavior due to how tensors are handled in memory.
> 
> To resolve this, you can convert the tensor values to integers before passing them to the `Counter`. Here's how you can modify your code:
> 
> ```python
> from collections import Counter
> 
> # Convert tensor values to integers
> class_indices = [int(cls) for cls in boxes.cls]
> class_counts = Counter(class_indices)
> 
> # Assuming 'result.names' maps class indices to names
> for class_index, count in class_counts.items():
>     class_name = result.names[class_index]
>     st.write(f'Number of detection of {class_name}: {count}')
> ```
> 
> This approach ensures that the class indices are handled as standard integers, which should work seamlessly with the `Counter`. Let me know if this adjustment solves the issue! 🚀

Thank you very much @glenn-jocher problem solved!! 🥇

**Comment by glenn-jocher** [comment]
Hello @Leprechault,

Fantastic to hear that the solution worked out for you! 🎉 If you have any more questions or need further assistance as you continue to work on your project, feel free to reach out. Happy coding! 🚀

**Comment by Leprechault** [comment]
> Hello @Leprechault,
> 
> Fantastic to hear that the solution worked out for you! 🎉 If you have any more questions or need further assistance as you continue to work on your project, feel free to reach out. Happy coding! 🚀

Thank you a lot @glenn-jocher you are an inspiration for us!! 👏👏👏👏👏👏

**Comment by glenn-jocher** [comment]
Hello @Leprechault,

Thank you for your kind words! I'm thrilled to be of help. If you have any more questions in the future or need further assistance, don't hesitate to ask. Keep up the great work on your project! 🚀

**Comment by Leprechault** [comment]
> Thanks for you support bro! @glenn-jocher 
> 
> ![image](https://github.com/ultralytics/ultralytics/assets/91314457/b23cbae0-11d4-4375-bebb-c4905ec40a41)
> 
> 
> here is the proper working code:
> 
> BASIC WORKING:
> 1. It takes the image input from the user
> 2. Predicts the object 
> 3. Displays the original image and bounded image side by side
> 4. Also displays number of objects detected and its dimensions in xywh format
> 5. Just replace the model path with your own path
> 6. Gives you the option to select model confidence before detection
> 
> ```
> import PIL
> import streamlit as st
> from ultralytics import YOLO
> 
> # Give the path of the best.pt (best weights)
> model_path = 'best.pt'
> 
> # Setting page layout
> st.set_page_config(
>     page_title="NISH(Neural Intelligence Synthesis Hub)",  # Setting page title
>     page_icon="NK logo.jpeg",     # Setting page icon
>     layout="wide",      # Setting layout to wide
>     initial_sidebar_state="expanded",    # Expanding sidebar by default
>     
> )
> 
> # Creating sidebar
> with st.sidebar:
>     st.header("Image Config")     # Adding header to sidebar
>     # Adding file uploader to sidebar for selecting images
>     source_img = st.file_uploader(
>         "Upload an image...", type=("jpg", "jpeg", "png", 'bmp', 'webp'))
> 
>     # Model Options
>     confidence = float(st.slider(
>         "Select Model Confidence", 25, 100, 40)) / 100
> 
> # Creating main page heading
> st.title("Object Detection")
> st.caption('Updload a photo by selecting :blue[Browse files]')
> st.caption('Then click the :blue[Detect Objects] button and check the result.')
> # Creating two columns on the main page
> col1, col2 = st.columns(2)
> 
> # Adding image to the first column if image is uploaded
> with col1:
>     if source_img:
>         # Opening the uploaded image
>         uploaded_image = PIL.Image.open(source_img)
>         image_width, image_height = uploaded_image.size
>         # Adding the uploaded image to the page with a caption
>         st.image(source_img,
>                  caption="Uploaded Image",
>                  width=image_width
>                  )
> 
> try:
>     model = YOLO(model_path)
> except Exception as ex:
>     st.error(
>         f"Unable to load model. Check the specified path: {model_path}")
>     st.error(ex)
> 
> if st.sidebar.button('Detect Objects'):
>     res = model.predict(uploaded_image,
>                         conf=confidence,
>                         line_width=1, 
>                         show_labels=False, 
>                         show_conf=False
>                         )
>     boxes = res[0].boxes
>     res_plotted = res[0].plot(labels=False, line_width=1)[:, :, ::-1]
>     with col2:
>         st.image(res_plotted,
>                  caption='Detected Image',
>                  width=image_width                 
>                  )
>         try:
>             st.write(f'Number of empty slots detected: {len(boxes)}')
>             with st.expander("Detection Results (xywh)"):                
>                 for box in boxes:
>                     st.write(box.xywh)
>         except Exception as ex:
>             st.write("No image is uploaded yet!")
> ```import PIL
> import streamlit as st
> from ultralytics import YOLO
> 
> # Give the path of the best.pt (best weights)
> model_path = 'best.pt'
> 
> # Setting page layout
> st.set_page_config(
>     page_title="NISH(Neural Intelligence Synthesis Hub)",  # Setting page title
>     page_icon="NK logo.jpeg",     # Setting page icon
>     layout="wide",      # Setting layout to wide
>     initial_sidebar_state="expanded",    # Expanding sidebar by default
>     
> )
> 
> # Creating sidebar
> with st.sidebar:
>     st.header("Image Config")     # Adding header to sidebar
>     # Adding file uploader to sidebar for selecting images
>     source_img = st.file_uploader(
>         "Upload an image...", type=("jpg", "jpeg", "png", 'bmp', 'webp'))
> 
>     # Model Options
>     confidence = float(st.slider(
>         "Select Model Confidence", 25, 100, 40)) / 100
> 
> # Creating main page heading
> st.title("Object Detection")
> st.caption('Updload a photo by selecting :blue[Browse files]')
> st.caption('Then click the :blue[Detect Objects] button and check the result.')
> # Creating two columns on the main page
> col1, col2 = st.columns(2)
> 
> # Adding image to the first column if image is uploaded
> with col1:
>     if source_img:
>         # Opening the uploaded image
>         uploaded_image = PIL.Image.open(source_img)
>         image_width, image_height = uploaded_image.size
>         # Adding the uploaded image to the page with a caption
>         st.image(source_img,
>                  caption="Uploaded Image",
>                  width=image_width
>                  )
> 
> try:
>     model = YOLO(model_path)
> except Exception as ex:
>     st.error(
>         f"Unable to load model. Check the specified path: {model_path}")
>     st.error(ex)
> 
> if st.sidebar.button('Detect Objects'):
>     res = model.predict(uploaded_image,
>                         conf=confidence,
>                         line_width=1, 
>                         show_labels=False, 
>                         show_conf=False
>                         )
>     boxes = res[0].boxes
>     res_plotted = res[0].plot(labels=False, line_width=1)[:, :, ::-1]
>     with col2:
>         st.image(res_plotted,
>                  caption='Detected Image',
>                  width=image_width                 
>                  )
>         try:
>             st.write(f'Number of empty slots detected: {len(boxes)}')
>             with st.expander("Detection Results (xywh)"):                
>                 for box in boxes:
>                     st.write(box.xywh)
>         except Exception as ex:
>             st.write("No image is uploaded yet!")


Please, @glenn-jocher, it's possible to not add a single image, but all the images inside a directory? The idea is to choose a directory and all the images are read by the app detected and the detection outputs are sent to the same directory, but something like a new folder 'results' contains detected images and *txt file. I don't want to remove a single image function, but create a new one function (eg. Batch detection).

**Comment by glenn-jocher** [comment]
Certainly! You can extend your Streamlit app to handle batch detection by allowing users to upload a directory of images. The app can then process each image in the directory and save the detection results in a new folder. Here's a concise way to approach this:

1. Add an option for directory upload.
2. Process each image in the directory.
3. Save the results in a new folder.

You can use `os` and `shutil` libraries to handle directory operations. Ensure you maintain the single image upload functionality while adding the batch detection feature.

If you need further assistance or specific code examples, feel free to ask!

**Comment by glenn-jocher** [comment]
Thank you for your kind words! The real credit goes to the YOLO community and the Ultralytics team. If you have more questions, feel free to ask.

**Comment by glenn-jocher** [comment]
Thank you for your kind words! The Ultralytics team and the YOLO community are here to support you. If you have more questions, feel free to ask.
