### ISSUE TITLE
Add Weights and Bias support back in

### ISSUE THREAD

**Issue by sstainba** [ultralytics/ultralytics#455]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Apparently Weights and Bias integration was removed just recently.  I'd request that it be added back in.

### Use case

WandB is super useful for comparing my training runs, it also stores the artifacts for me for easy retrieval.  Using WandB is as simple as creating an account and passing in an API key.  It doesn't require me to run any other utilities or other packages. I rain via the ultralytics docker images so I don't have to reinstall the entire environment on my PC.  I'd prefer not to install other analytics packages either.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by solisoares** [comment]
I haven't looked yet, but have you found any others model loggers that are supported (already have integration in source code)? I like wandb, ude it with yolov5, and if they decide not to support it anymore, it'd be nice to have a replacement.

**Comment by fennecinspace** [comment]
This is necessary.

**Comment by ashutoshIITK** [comment]
Please add W&B back! It is necessary.

**Comment by dickymuhr** [comment]
Sure, give it back please

**Comment by luigisaetta** [comment]
well, I also recommend adding gain support for W&B

**Comment by BraunGe** [comment]
Please add W&B back! It is necessary.

**Comment by OrenLederman** [comment]
Same. Adding W&B back will be very useful

**Comment by FnSK4R17s** [comment]
Can we add it back manually?

**Comment by Irikos** [comment]
Does anyone have the script to use W&B manually? I started working on it but I'm far from having logged all the information that yolov5 has.

**Comment by Irikos** [comment]
@glenn-jocher @AyushExel can you please tell us if wandb was purposefully not added and will not be added in the future? We're clearly big supporters of wandb integration, but the most important part is knowing what awaits.

**Comment by fennecinspace** [comment]
@Irikos Here's some insight on how to do it: 
- You can specify behaviors like `on_train_end` and `on_fit_epoch_end` in the `yolo/utils/callbacks/base.py` file, these are already in the code and are executed by default.


Here's some insight on what you need to do when the training ends to save the model (trainer.wandb is an attribute that I initialize right before trainer.train(... in `yolo/utils/engine/model.py` ) : 

```
def on_train_end(trainer):
    if trainer.wandb:
        path = trainer.last.parent

        model_artifact = wandb.Artifact(
            'run_' + wandb.run.id + '_model',
            type='model',
            metadata={
                'original_url': str(path),
                'epochs_trained': trainer.epoch + 1,
                'total_epochs': trainer.epochs,
                'fitness_score': trainer.fitness,
                'best_fitness_score': trainer.best_fitness
            }
        )

        model_artifact.add_file(str(path / 'best.pt'))
        model_artifact.add_file(str(path / 'last.pt'))
        wandb.log_artifact(
            model_artifact,
            aliases=['latest', 'last', 'epoch ' + str(trainer.current_epoch), 'best']
        )
        print(f"Saving model artifacts")
```

This is needed to metrics after each epoch's end : 

```
def on_train_epoch_end(trainer):
    if trainer.wandb:
        trainer.current_epoch += 1
        print(trainer.current_epoch)


def on_fit_epoch_end(trainer, metrics, fitness):
    if trainer.wandb:
        
        keys, vals = list(metrics.keys()), list(metrics.values())
        ### keys : ['metrics/precision(B)', 'metrics/recall(B)', 'metrics/mAP50(B)', 'metrics/mAP50-95(B)', 'val/box_loss', 'val/cls_loss', 'val/dfl_loss']

        # log best results
        if trainer.best_fitness == fitness:
            best_keys = ['best/epoch', 'best/precision', 'best/recall', 'best/mAP50', 'best/mAP50-95']
            best_results = [trainer.epoch] + vals[0:4]
            for i, name in enumerate(best_keys):
                trainer.wandb.summary[name] = best_results[i]  # log best results in the summary
        trainer.wandb.log(metrics)
```

You'll need to modify the callback calls in `yolo/utils/engine/model.py` to pass the required attributes (trainer, fitness, ...etc)

Sorry that I shared the solution in this way, but I have it implemented directly into the code and have other proprietary code that I can't share. If you find issues reimplementing this, don't hesitate to ask !

**Comment by Irikos** [comment]
@fennecinspace Thanks, it is useful! I'll take a look tomorrow and try to integrate it into my code. So far I've only played with yoloV8 and plan on doing more serious training but need to fix wandb (or similar) logging before I can do that.

**Comment by herbat** [comment]
Any info/ ETA on the addition of WandB logging? At least some guide on logging with an experiment tracking application would be nice!

**Comment by lyhue1991** [comment]
I make it done by drag the wb.py  from ultralytics 8.0.0, and fix a little bug.
here is how we can use the wandb in ultralytics.

```python
from ultralytics import YOLO 
from wandb_callback import callbacks 

model = YOLO('yolov8s.pt') 

for event,func in callbacks.items():
    model.add_callback(event,func)

results = model.train(data = 'coco128.yaml', epochs = 400, workers=8)
```
see more: 

https://github.com/lyhue1991/YOLOv8_tools

**Comment by pathikg** [comment]
> I make it done by drag the wb.py from ultralytics 8.0.0, and fix a little bug. here is how we can use the wandb in ultralytics.
> 
> ```python
> from ultralytics import YOLO 
> from wandb_callback import callbacks 
> 
> model = YOLO('yolov8s.pt') 
> 
> for event,func in callbacks.items():
>     model.add_callback(event,func)
> 
> results = model.train(data = 'coco128.yaml', epochs = 400, workers=8)
> ```
> 
> see more:
> 
> https://github.com/lyhue1991/YOLOv8_tools

perfect!

**Comment by pderrenger** [comment]
@pathikg hi there! It's great to see you've managed to integrate wandb into YOLOv8 successfully. Thanks for sharing the method and the link to your work. Your contributions are valuable to the community, and they make a big difference in improving the overall user experience with YOLOv8. If you need further assistance or have any questions, feel free to ask. Keep up the excellent work!
