### ISSUE TITLE
Inferencing Yolov8 Pose NMS Time limit exceeded

### ISSUE THREAD

**Issue by sard0r** [ultralytics/ultralytics#4551]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When I am running yolov8 pose model on video more than 1000 frames the inferencing is freezing and giving NMS time limit exceeded. I believe that there should be a solution to that.

![image](https://github.com/ultralytics/ultralytics/assets/61651742/f2a88c27-d8cb-4fa3-bc84-f608d47ea1d6)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sard0r your usage for long videos is incorrect. See https://docs.ultralytics.com/modes/predict/ for streaming mode.

**Comment by sard0r** [comment]
If I set stream=True then the model is not even initializing.
