### ISSUE TITLE
Does the flops change if I export the pytorch file to onnx?

### ISSUE THREAD

**Issue by ohjunee** [ultralytics/ultralytics#4553]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm testing with yolov8 and resnet18, mobilenetv2, and I'm looking for a code to calculate gflops on onnx.

**Comment by glenn-jocher** [comment]
No.
