### ISSUE TITLE
When I use yolov8n-pose.pt for predicting bus.jpg, the results are correct. However, when I use yolov8n-pose.onnx to predict bus.jpg, the results are incorrect.

### ISSUE THREAD

**Issue by LS-YQ** [ultralytics/ultralytics#4557]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

1、This is my code:

`from ultralytics import YOLO
import torch
print(torch.cuda.is_available())  # True
model = YOLO("yolov8n-pose.pt")
results = model("ultralytics/assets/bus.jpg", save=True)
success = model.export(format="onnx")`

Terminal：
PyTorch: starting from 'yolov8n-pose.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 56, 8400) (6.5 MB)

ONNX: starting export with onnx 1.14.0 opset 13...
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
ONNX: export success  1.1s, saved as 'yolov8n-pose.onnx' (12.8 MB)

2、Upon employing YOLOv8-ONNXRuntime/main.py, the outcomes are inaccurate.

```
if __name__ == '__main__':
    # Create an argument parser to handle command-line arguments
    parser = argparse.ArgumentParser()
    parser.add_argument('--model', type=str, default='yolov8n-pose.onnx', help='Input your ONNX model.')
    parser.add_argument('--img', type=str, default=str(ASSETS / 'bus.jpg'), help='Path to input image.')
    parser.add_argument('--conf-thres', type=float, default=0.5, help='Confidence threshold')
    parser.add_argument('--iou-thres', type=float, default=0.5, help='NMS IoU threshold')
```
I made alterations solely to the name of the model.
![UP~$Q0)F1}3O_N94_7ITJLJ](https://github.com/ultralytics/ultralytics/assets/141985033/04fb5971-beac-4b14-80c3-f1976c14d7f4)

**Comment by glenn-jocher** [comment]
@LS-YQ YOLOv8 ONNX Pose estimation works correctly:

```python
from ultralytics import YOLO

model = YOLO('yolov8n-pose.onnx')

results = model('ultralytics/assets/bus.jpg')
```
