### ISSUE TITLE
Yolo classify training fails immediately if I use resume=True 

### ISSUE THREAD

**Issue by xumix** [ultralytics/ultralytics#4562]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Preamble in #4514

If I try using `resume=true` in my training then it looks like yolo tries to use cuda `device=2` instead of cli specified `device=0`, `best.pt` is also trained on `device=0` if that matters

`yolo classify train model=~/yolo-pip/pp-cat/first/weights/best.pt device=0 data=~/images batch=200 cfg=cfg.yaml epochs=3 resume=true`
I always get this error:

```
Overriding /home/tambovtsev/yolo-pip/lib/python3.10/site-packages/ultralytics/cfg/default.yaml with cfg.yaml
New https://pypi.org/project/ultralytics/8.0.162 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.161 🚀 Python-3.10.12 torch-2.0.1+cu118
Traceback (most recent call last):
  File "/home/tambovtsev/yolo-pip/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 432, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/ultralytics/engine/model.py", line 372, in train
    self.trainer = trainer(overrides=overrides, _callbacks=self.callbacks)
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/ultralytics/models/yolo/classify/train.py", line 39, in __init__
    super().__init__(cfg, overrides, _callbacks)
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 86, in __init__
    self.device = select_device(self.args.device, self.args.batch)
  File "/home/tambovtsev/yolo-pip/lib/python3.10/site-packages/ultralytics/utils/torch_utils.py", line 81, in select_device
    raise ValueError(f"Invalid CUDA 'device={device}' requested."
ValueError: Invalid CUDA 'device=2' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: None
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.

Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
```
Setting `resume=false` fixes the error and training goes as expected
```
yolo classify train model=~/yolo-pip/pp-cat/first/weights/best.pt device=0 data=~/images batch=200 cfg=cfg.yaml epochs=3 resume=false
Overriding /home/tambovtsev/yolo-pip/lib/python3.10/site-packages/ultralytics/cfg/default.yaml with cfg.yaml
Ultralytics YOLOv8.0.162 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (NVIDIA GeForce RTX 3090 Ti, 24248MiB)
engine/trainer: task=classify, mode=train, model=yolov8m-cls.pt, data=/home/tambovtsev/images, epochs=3, patience=50, batch=200, imgsz=300, save=True, save_period=1, cache=True, device=0, workers=8, project=pp-cat, name=first, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.3, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=pp-cat/first3
train: /home/tambovtsev/images/train... found 1766934 images in 4355 classes ✅
val: /home/tambovtsev/images/val... found 220851 images in 4355 classes ✅
test: /home/tambovtsev/images/test... found 223068 images in 4355 classes ✅
Overriding model.yaml nc=1000 with nc=4355
....
```
### Environment

Ultralytics YOLOv8.0.161 🚀 Python-3.10.12 torch-2.0.1+cu118

### Minimal Reproducible Example

same as in #4514

**Comment by glenn-jocher** [comment]
@xumix `resume=True` is for crashed trainings. You can use it like this:

```bash
yolo train model=path/to/last.pt resume=True
```

Or you can start a completely new training from last.pt from epoch 0:
```bash
yolo train model=path/to/last.pt resume=True
```

**Comment by glenn-jocher** [comment]
Note you don't need to pass any arguments when resuming, as they are all remembered from the checkpoint. See https://docs.ultralytics.com/modes/train/#resuming-interrupted-trainings

<img width="1603" alt="Screenshot 2023-08-25 at 15 37 23" src="https://github.com/ultralytics/ultralytics/assets/26833433/154cb356-27ef-4e4c-999c-106f249ef903">

**Comment by xumix** [comment]
> @xumix `resume=True` is for crashed trainings. You can use it like this:
> 
> ```shell
> yolo train model=path/to/last.pt resume=True
> ```
> 
> Or you can start a completely new training from last.pt from epoch 0:
> 
> ```shell
> yolo train model=path/to/last.pt
> ```

Yes, this is exactly what I was doing: trying to resume training with new data (as described in docs)
So the error is caused by parameters that are passed via cli? This looks suspicious because I pass device=0 and the error says device=2

**Comment by glenn-jocher** [comment]
@xumix good catch, it does seem unexpected that `device=0` in your command gets overridden to `device=2`. The model checkpoint you're trying to resume from contains the training arguments used previously, including the device it was trained on. When `resume=True`, these arguments are loaded and they may override your current command-line inputs. If the previous model was trained on `device=2`, it may explain this behavior.

However, it's unusual since Ultralytics YOLOv8 should operate fine with your specified device regardless of what device was used to save the checkpoint. We will investigate this matter, and I'll keep you updated on our progress. Your patience and understanding are much appreciated.

**Comment by amazon** [comment]
Same problem wile trying to resume  in Colab environment after runtime disconnect. Is there any workaround?
Ultralytics YOLOv8.0.164 🚀 Python-3.10.12 torch-2.0.1+cu118

**Comment by glenn-jocher** [comment]
@amazon thanks for sharing your experience. When you use `resume=True`, YOLOv8 loads the arguments used previously when training, this includes the device the model was trained on. It seems that these saved arguments might be overriding the command-line inputs leading to the issue. We are investigating this matter and appreciate your patience. It's reassuring that you could resume training with `yolo train model=path/to/best.pt resume=True`. This implies that the existing arguments used previously are successfully loaded and allow the training to continue.

**Comment by xumix** [comment]
> It's reassuring that you could resume training with `yolo train model=path/to/best.pt resume=True`. This implies that the existing arguments used previously are successfully loaded and allow the training to continue.

This does not work, I tried my previous best.pt and still it fails with `device=2 error`

**Comment by glenn-jocher** [comment]
@xumix i apologise for the inconvenience caused. It seems there is an inconsistency in how the training device is handled during the resumption of the training. We are currently investigating this matter. The device argument from the previous training session should not affect the resume operation, but in your case, it appears to be causing an issue. Thank you for your patience while we further look into this matter and work on a solution.

**Comment by sarpx** [comment]
I see that the dependencies for continuing training are not being met and I need to start retraining from scratch. Interestingly enough, it gives the error that the device cannot be accessed.

**Comment by sarpx** [comment]
@glenn-jocher I think this is specifically due to the conda environment. If you are taking and keeping cuda access paths and using it in the rerun command, there may be a problem here.. because there is no problem when retraining from scratch. There doesn't seem to be any other logical explanation for getting the device error when I say continue the training.

**Comment by xumix** [comment]
> @glenn-jocher I think this is specifically due to the conda environment. If you are taking and keeping cuda access paths and using it in the rerun command, there may be a problem here.. because there is no problem when retraining from scratch. There doesn't seem to be any other logical explanation for getting the device error when I say continue the training.

I'm not using conda and still get the error
