### ISSUE TITLE
How to use yesterday's default version of yolov8?

### ISSUE THREAD

**Issue by CnoyZ** [ultralytics/ultralytics#4572]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi Sir! I noticed that you updated YOLOv8's Python package yesterday. I am working on my final project and my experiment results are different if I use the state-of-the-art version. TAT I have collected most of the experiment results required for my project's report, but there are still a few that need to be experimented and collected. Are there any ways to use the previous version of YOLOv8?  (I really don't want to do these again and collect again. TAT)

**Comment by CnoyZ** [comment]
Oh, I get that! Thank u!

**Comment by glenn-jocher** [comment]
@CnoyZ you're welcome! I'm glad to hear the information provided was helpful. If you have any other questions or issues with YOLOv8, please don't hesitate to ask. We’re here to help. Happy coding!

**Comment by CnoyZ** [comment]
@glenn-jocher sincerely thanks for your kind response! YOLOv8 really helps me a lot in my studying and projects. Good luck to every team member of you! :)
