### ISSUE TITLE
Regarding yolo semantic segmentation sample labeling, the target area contains background or non-target areas

### ISSUE THREAD

**Issue by liuqinglong110** [ultralytics/ultralytics#4582]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm doing a semantic segmentation task on grass areas. The task requires that I only need to segment the grass area, and the non-grass area can be regarded as the background.

There is a picture in the scene as shown below：
![1](https://github.com/ultralytics/ultralytics/assets/23652342/14244f4c-d892-417b-bfcb-3f1d60d0487c)
I marked the outline of the grass area and named it Lawn. A black item (sponge block) in the middle of the grass. Obviously this black item should not belong to the grass area. I marked the black item and named the category name __background__. I set all the group ids of __background__ to 0.

After labeling, my sample bitmap looks like this:
![2](https://github.com/ultralytics/ultralytics/assets/23652342/d689eadf-b808-4d3a-a1d2-2a37db4fac50)

The annotation tools I use are as follows: https://github.com/yatengLG/ISAT_with_segment_anything

I used the following command to process the labeled data: python json2txt.py --json-dir /app/mineData/LawnMower/second_data/black_data/black --save-dir /app/mineData/LawnMower/second_data/black_data/txt - -classes 'lawn' 
Obviously I know this is problematic, but I'm a bit confused about how to handle it.
Because in the future sample set, there will be more than one kind of item on the grass, unless I name all the items on the grass as "item category". The others are background classes.
I'm curious, how this scenario should handle the sample set. Because I searched for other people's cases, there is almost no reference to this situation, or it is not detailed.

According to my previous practice, during the training process, the marked pictures that appear are obviously problematic, as shown in the following figure:
train_batch1.jpg
![train_batch1](https://github.com/ultralytics/ultralytics/assets/23652342/cb20c10a-7fc0-4412-b869-6f9260538dd0)
The results of val_batch0_labels.jpg are as follows:
![val_batch0_labels](https://github.com/ultralytics/ultralytics/assets/23652342/61953dc5-155b-4a51-8308-da4a5c540202)

The final test result is that when the black object is in the central area of the grass field, it cannot be segmented.
The result is as follows:
![black_20cm_0824_left0267](https://github.com/ultralytics/ultralytics/assets/23652342/59fdfaf1-a5ff-423c-ba11-5f638dea3ab6)
I'm roughly aware of the problem, maybe I shouldn't be treating the item in the middle of the grass as a "background" class. However, I'm hoping to know the best way to go about it. Please help to see how to deal with the best results.
Thank you everyone

**Comment by glenn-jocher** [comment]
@liuqinglong110 in semantic segmentation tasks, it's important to correctly classify every pixel in the image. In your case, you're dealing with two categories: 'grass' and 'background'. The black item (sponge block) within the grass area, even though it's not grass, should not be assigned as part of the background class. This is because it is not actually part of the background, but an object on the grass. 

When you label this item as 'background', the model might get confused and end up classifying it as grass since the majority of surrounding pixels are grass. This could explain the problems you are encountering in your training results.

In terms of handling this, one approach could be to have an 'other' or 'unknown' class for these types of objects. This way, every pixel inside the boundary of the object (the sponge block, for example) would be labeled as 'other'. 

Remember that the goal of semantic segmentation is to assign a class to every pixel in the image. So in situations like these, where an object that is neither 'background' nor 'grass' appears in the grass area, it needs its own unique classification assignment that distinctively separates it from the grass and the background. This will likely enhance the performance of your model.

I hope this explanation helps clarify how to handle such a situation. Feel free to continue discussing if you have more questions.

**Comment by liuqinglong110** [comment]
> @liuqinglong110 in semantic segmentation tasks, it's important to correctly classify every pixel in the image. In your case, you're dealing with two categories: 'grass' and 'background'. The black item (sponge block) within the grass area, even though it's not grass, should not be assigned as part of the background class. This is because it is not actually part of the background, but an object on the grass.🔄  ❓
> 
> When you label this item as 'background', the model might get confused and end up classifying it as grass since the majority of surrounding pixels are grass. This could explain the problems you are encountering in your training results.🔄  ❓
> 
> In terms of handling this, one approach could be to have an 'other' or 'unknown' class for these types of objects. This way, every pixel inside the boundary of the object (the sponge block, for example) would be labeled as 'other'.🔄  ❓
> 
> Remember that the goal of semantic segmentation is to assign a class to every pixel in the image. So in situations like these, where an object that is neither 'background' nor 'grass' appears in the grass area, it needs its own unique classification assignment that distinctively separates it from the grass and the background. This will likely enhance the performance of your model.🔄  ❓
> 
> I hope this explanation helps clarify how to handle such a situation. Feel free to continue discussing if you have more questions.🔄  ❓

Thank you very much for your answer, I also understand what you mean. I have followed your suggestion and named the items in the grass (such as sponge blocks) as "obstacles". After retraining the model, the result is exactly as expected: the items on the grass are segmented. Thanks again for your answer.
In addition, I have another question: In my task, I only want to focus on the grass area for the time being, so that the smart lawn mower can output the driving area in the future. Therefore, I don't care about the types of items on the grass, because no matter what kind of items, as long as it is not grass, the lawn mower needs to avoid obstacles. There may be a variety of items on the lawn, such as manhole covers, trees, fences, footballs, flower beds, and other items that may be seen in various home lawns. If I mark these items as samples, I will classify them into one category, such as "other" or "obstacle". Is this approach inelegant? I mean, forcing irrelevant items to be classified into the same category will cause the model training to not converge or the accuracy of the model in the future will not be high? After all, the image features of these items named "other" or "obstacle" are quite different.
If I name these unconcerned items strictly according to the corresponding category names, that is, name the items such as manhole covers, trees, fences, footballs, and flower beds with a category name, although in the end my task does not need to know the obstacles on the grass However, is this method of naming each type of item separately more accurate than the previous method of uniformly naming "others" or "obstacles", or in other words, is it better to use the model performance? Of course, this naming method will be more troublesome when used for labeling a large amount of data, especially if I want to make products for sale in the future, I will face many scenarios.
The above is one of my questions. I know that this question may not belong to yolo's question. This is just my further thinking. Thank you very much for reading my long essay. Looking forward to in-depth communication with you, thanks again!

**Comment by glenn-jocher** [comment]
@liuqinglong110 thanks for your response and for your new inquiry. Indeed, these are valid concerns to consider when setting up your task.

When you aggregate a set of dissimilar objects under a single class, such as "obstacles" or "other", your model could struggle to learn the common features, especially if they varying significantly. The result could be a model that is less clear-cut in its decision boundaries for these diverse examples, and that might lead to lower precision for that class.

On the other hand, labeling each unique item type with separate classes might result in a more accurate model, as it can learn specific features associated with each individual class. However, as you rightly pointed out, this approach needs significantly more annotation work, and might be not feasible for large-scale production. 

Moreover, if your end-goal does not necessarily require distinguishing among the various different types of non-grass objects, it may not be meaningful to enforce such a fine-grained classification scheme.

Ultimately, the best option might depend on the specific requirements of your project and the resources that are available for data annotation. It is often a delicate balance between model accuracy, resources, and the practical needs of your task. 

Feel free to share additional details or concerns for further discussion. I appreciate your thoughtful questions!

**Comment by Laughing-q** [comment]
@shen865069799 try predict with `retina_masks=True`

**Comment by Laughing-q** [comment]
@liuqinglong110 
> In addition, I have another question: In my task, I only want to focus on the grass area for the time being, so that the smart lawn mower can output the driving area in the future. Therefore, I don't care about the types of items on the grass, because no matter what kind of items, as long as it is not grass, the lawn mower needs to avoid obstacles. There may be a variety of items on the lawn, such as manhole covers, trees, fences, footballs, flower beds, and other items that may be seen in various home lawns. If I mark these items as samples, I will classify them into one category, such as "other" or "obstacle". Is this approach inelegant? I mean, forcing irrelevant items to be classified into the same category will cause the model training to not converge or the accuracy of the model in the future will not be high? After all, the image features of these items named "other" or "obstacle" are quite different.

yeah you can try this, labeling all the backgrounds as a `item` category, I think it'll work and won't affect accuracy that much.

**Comment by shen865069799** [comment]
@Laughing-q 

I tried what you said, and in some cases, it is indeed possible to segment the edge of the left image，
Thank you so much;
But on other pictures, this parameter will make the edge of the right image not be segmented, even if it makes up for the segmentation effect of the edge of the left image：
without `retina_masks=True`
![Screenshot from 2023-08-31 14-53-37](https://github.com/ultralytics/ultralytics/assets/31476124/5c701681-26db-4881-8793-7598d95618dd)
with `retina_masks=True`
![Screenshot from 2023-08-31 14-54-04](https://github.com/ultralytics/ultralytics/assets/31476124/09ff27d6-1d92-418e-a37e-e95e3a2fb08b)

Please carefully compare the left and right edges of the image
Can I understand it as a post-processing strategy problem？because I see that during training and validation, the model's performance is very good

**Comment by glenn-jocher** [comment]
@shen865069799 it's great to hear that enabling `retina_masks` improves some results, and thank you for sharing additional images and your observations!

In YOLOv8, enabling `retina_masks` can change how the model handles prediction across the edges of the image. Instances where this fails could be due to corner cases the model was not trained on. 

However, as you noted, it's interesting that while the model's training performance is good, the post-processing strategy does not always maintain this performance. 

Indeed, the post-processing strategy can greatly affect the model's final predictions. In this case, it might be transforming the model output in a way that leads to missing segments at the right edges. Remember, the model's raw outputs are not usually interpretable as segmentation maps directly, but undergo transformations and thresholding during post-processing to produce the final result.

Therefore, it's possible that by tuning your post-processing strategy, you might see improvements in these edge cases. This could involve adjusting various parameters, such as the thresholds for class scores and non-max suppression, or even trying different strategies for transforming the raw model output into a final prediction.

I hope this helps, let me know if you have further questions.

**Comment by liuqinglong110** [comment]
> @Laughing-q
> 
> I tried what you said, and in some cases, it is indeed possible to segment the edge of the left image， Thank you so much; But on other pictures, this parameter will make the edge of the right image not be segmented, even if it makes up for the segmentation effect of the edge of the left image： without `retina_masks=True` ![Screenshot from 2023-08-31 14-53-37](https://private-user-images.githubusercontent.com/31476124/264560057-5c701681-26db-4881-8793-7598d95618dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDQyOTcsIm5iZiI6MTcwMzE0Mzk5NywicGF0aCI6Ii8zMTQ3NjEyNC8yNjQ1NjAwNTctNWM3MDE2ODEtMjZkYi00ODgxLTg3OTMtNzU5OGQ5NTYxOGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA3MzMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMjM2MzU5ZTk1MTIwYTA1ZjVlZjM2Y2EzODA1NjFmMzM4Y2M1MDc4ODYxYmMwOGMxYWNjMGQ5OTNlY2U5MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AaaffDqaLsnhwQeFuycXY-grPtsLOf0f77AXA_4lK3g) with `retina_masks=True` ![Screenshot from 2023-08-31 14-54-04](https://private-user-images.githubusercontent.com/31476124/264560096-09ff27d6-1d92-418e-a37e-e95e3a2fb08b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDQyOTcsIm5iZiI6MTcwMzE0Mzk5NywicGF0aCI6Ii8zMTQ3NjEyNC8yNjQ1NjAwOTYtMDlmZjI3ZDYtMWQ5Mi00MThlLWEzN2UtZTk1ZTNhMmZiMDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA3MzMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNWU5YzIzYzQ1NjljZjQ5NmFmMzUxMGNjMTFkNmJlMzk3ODMyNWRjMWQwYzViZGE3MzEwZjY5MWE1ZjFlNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xpsnsGQoTxaR-FDzk3TFpw9QfMK6LOTr3mLeK04h9Ek)
> 
> Please carefully compare the left and right edges of the image Can I understand it as a post-processing strategy problem？because I see that during training and validation, the model's performance is very good

--------------------------------------------------------------------------------------------------------------------------------------------
Hello. I'm thinking about how to use a simpler way to complete grass segmentation and obstacle detection. I saw that in the results you showed, in addition to grass, other obstacles were also identified in the form of semantic segmentation. I feel that this method will be very difficult to label data. 
First of all, there are so many types of obstacles, and deep learning can only identify categories that have been labeled before. Secondly, each type of obstacle must be marked with outlines, which requires a lot of manual labor. Therefore, my idea is to segment the grass using a semantic segmentation algorithm, and use a target detection algorithm for obstacles, because the target detection categories in the public data set are very rich, and the annotation cost is relatively low. The target detection algorithm can be trained to produce results faster. Therefore, this requires both semantic segmentation and target detection algorithms to run simultaneously.

However, I feel that the two algorithms consume more computing resources, so it is best to use one model to do semantic segmentation and target detection at the same time. I recently read the yolopv2 algorithm(https://github.com/CAIC-AD/YOLOPv2) and felt that this algorithm might be able to solve this multi-task scenario. But I think the yolopv2 algorithm is aimed at autonomous driving scenarios and detects vehicles, lane lines, and drivable areas at the same time. These three categories of goals almost always appear together. If yolovp2 is used to train grass and obstacles on grass, does that also mean that there will be many samples of grass and obstacles appearing at the same time? If I have a large number of samples that are grasslands marked by semantic segmentation, and another batch of samples are target obstacles in the form of rectangular boxes in coco or voc. Mixing the two samples together will inevitably not produce good training results. I don’t know how you think about this issue? At the same time, I am also considering whether yolo can be transformed into a form of target frame detection for certain categories, and some categories are in the form of semantic segmentation. We seem to be engaged in the same industry and hope to communicate and learn together.

**Comment by shen865069799** [comment]
你好来信已收到

**Comment by liuqinglong110** [comment]
> @liuqinglong110 in semantic segmentation tasks, it's important to correctly classify every pixel in the image. In your case, you're dealing with two categories: 'grass' and 'background'. The black item (sponge block) within the grass area, even though it's not grass, should not be assigned as part of the background class. This is because it is not actually part of the background, but an object on the grass.
> 
> When you label this item as 'background', the model might get confused and end up classifying it as grass since the majority of surrounding pixels are grass. This could explain the problems you are encountering in your training results.
> 
> In terms of handling this, one approach could be to have an 'other' or 'unknown' class for these types of objects. This way, every pixel inside the boundary of the object (the sponge block, for example) would be labeled as 'other'.
> 
> Remember that the goal of semantic segmentation is to assign a class to every pixel in the image. So in situations like these, where an object that is neither 'background' nor 'grass' appears in the grass area, it needs its own unique classification assignment that distinctively separates it from the grass and the background. This will likely enhance the performance of your model.
> 
> I hope this explanation helps clarify how to handle such a situation. Feel free to continue discussing if you have more questions.

--------------------------------------------------------------------------------------------------------------------------------------------

Hello. I am thinking about how to use a simpler way to complete grass segmentation and obstacle detection on the grass. That is, I hope to use semantic segmentation to segment the grass and use rectangular boxes to detect various obstacles, such as pedestrians and vehicles. , cats, dogs, trees, etc. Because the cost of labeling semantic segmentation samples is too high, it is difficult to find segmentation samples for obstacles. The current sample also has some problems. For example, there are usually not many obstacles on the grass. That is to say, there are relatively few grass and obstacles at the same time. There are also relatively few grassland data sets in the public data sets (samples from the lawnmower perspective).

I recently read the yolopv2 (https://github.com/CAIC-AD/YOLOPv2) algorithm and feel that this algorithm may be able to solve this multi-task scenario. But I think the yolopv2 algorithm is aimed at autonomous driving scenarios and detects vehicles, lane lines, and drivable areas at the same time. These three categories of goals almost always appear together. If yolovp2 is used to train grass and obstacles on grass, does that also mean that there will be many samples of grass and obstacles appearing at the same time? If I have a large number of samples that are grasslands marked by semantic segmentation, and another batch of samples are target obstacles in the form of rectangular boxes in coco or voc. Mixing the two samples together will inevitably not produce good training results. I don’t know how you think about this issue?
In addition, can yolo's algorithm be changed to detect certain categories using semantic segmentation and other categories using target detection?

**Comment by glenn-jocher** [comment]
@liuqinglong110 For your scenario, you can indeed use a combination of semantic segmentation for the grass and detection for various obstacles. If you only care about differentiating between grass and non-grass obstacles, you can simplify the labeling process by marking all obstacles with bounding boxes under a single obstacle category. This would reduce the complexity of having multiple obstacle classes and still serve the purpose for your smart lawn mower application.

Regarding the combination of tasks, YOLOv8 is designed for object detection, but some YOLO variants have been adapted for multiple tasks, including semantic segmentation. YOLOPv2 is one such multi-task model, although primarily for autonomous driving, where related objects typically appear together, as you mentioned.

If you're considering YOLO variants that can simultaneously handle detection and segmentation, the key is to ensure the model architecture supports multi-task learning and that your dataset is appropriately annotated to train for both tasks. You may need to carefully design the integration of the two tasks to ensure each one benefits from the other.

To directly adapt YOLOv8 for a combination of detection (bounding boxes) and segmentation (pixel-wise classification), it would require significant changes to the model architecture and training pipeline, as it's not a built-in feature of YOLOv8.

For your case with limited grass-obstacle samples, consider data augmentation or leveraging transfer learning from a model pre-trained on diverse datasets to enhance performance. A well-tuned model should generalize well even from fairly disparate training samples if set up correctly.

**Comment by qulishen** [comment]
@liuqinglong110 您好，能否交流一下智能割草机的事宜？

**Comment by shen865069799** [comment]
你好来信已收到

**Comment by glenn-jocher** [comment]
@shen865069799 of course! 😊 If there's any specific question or discussion point you have in mind regarding the smart lawnmower or YOLOv8, feel free to share. We're here to help!

**Comment by liuqinglong110** [comment]
> @liuqinglong110 您好，能否交流一下智能割草机的事宜？

当然可以，可以先给我的邮箱发邮件 1270413423@qq.com

**Comment by liuqinglong110** [comment]
> 你好来信已收到

您好，可以交换一下联系方式吗？麻烦您先给我单独发个邮件吧。1270413423@qq.com

**Comment by liuqinglong110** [comment]
您好：
       我们都是从事割草机行业的同行，希望能和您交流一下。微信号：lql18681563969   













在 2024-03-17 13:59:59，"瞿立燊" ***@***.***> 写道：

@liuqinglong110 您好，能否交流一下智能割草机的事宜？

**Comment by shen865069799** [comment]
你好来信已收到

**Comment by glenn-jocher** [comment]
@shen865069799 i'm sorry, but I can't assist with this request.

**Comment by kishan2910** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> ### Question
> I'm doing a semantic segmentation task on grass areas. The task requires that I only need to segment the grass area, and the non-grass area can be regarded as the background.
> 
> There is a picture in the scene as shown below： ![1](https://private-user-images.githubusercontent.com/23652342/263470940-14244f4c-d892-417b-bfcb-3f1d60d0487c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTA2MjAsIm5iZiI6MTcxNTU5MDMyMCwicGF0aCI6Ii8yMzY1MjM0Mi8yNjM0NzA5NDAtMTQyNDRmNGMtZDg5Mi00MTdiLWJmY2ItM2YxZDYwZDA0ODdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA4NTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZDRjYmU0OGU1ZGEzMTEyY2ZmZGFjOTJmOTQ0YjkwOTI4Zjg1ZjA5YTc5MjBiZjMzMmM4MDMwNmVkODZkMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tKkPF__Uepcl1qli-jCtN9gdNYtXKF83QCqysyuU3Y0) I marked the outline of the grass area and named it Lawn. A black item (sponge block) in the middle of the grass. Obviously this black item should not belong to the grass area. I marked the black item and named the category name **background**. I set all the group ids of **background** to 0.
> 
> After labeling, my sample bitmap looks like this: ![2](https://private-user-images.githubusercontent.com/23652342/263471131-d689eadf-b808-4d3a-a1d2-2a37db4fac50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTA2MjAsIm5iZiI6MTcxNTU5MDMyMCwicGF0aCI6Ii8yMzY1MjM0Mi8yNjM0NzExMzEtZDY4OWVhZGYtYjgwOC00ZDNhLWExZDItMmEzN2RiNGZhYzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA4NTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZjIzZWZhYmQ4NmYwZDJiZTI5NTY1OGQ2NTI1MWJjNGVlMmE0NzFjMWZiNjcwMzljMTA1NDIyODllODVmMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gTzoOwd1l6MIx0m-NVg3ke9l3jHVh_WNibBZHxvH8uY)
> 
> The annotation tools I use are as follows: https://github.com/yatengLG/ISAT_with_segment_anything
> 
> I used the following command to process the labeled data: python json2txt.py --json-dir /app/mineData/LawnMower/second_data/black_data/black --save-dir /app/mineData/LawnMower/second_data/black_data/txt - -classes 'lawn' Obviously I know this is problematic, but I'm a bit confused about how to handle it. Because in the future sample set, there will be more than one kind of item on the grass, unless I name all the items on the grass as "item category". The others are background classes. I'm curious, how this scenario should handle the sample set. Because I searched for other people's cases, there is almost no reference to this situation, or it is not detailed.
> 
> According to my previous practice, during the training process, the marked pictures that appear are obviously problematic, as shown in the following figure: train_batch1.jpg ![train_batch1](https://private-user-images.githubusercontent.com/23652342/263471582-cb20c10a-7fc0-4412-b869-6f9260538dd0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTA2MjAsIm5iZiI6MTcxNTU5MDMyMCwicGF0aCI6Ii8yMzY1MjM0Mi8yNjM0NzE1ODItY2IyMGMxMGEtN2ZjMC00NDEyLWI4NjktNmY5MjYwNTM4ZGQwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA4NTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMzdkMTNkZDc2MWVhMzM5ZjVkMWEwNGU2MmY1ODg0YzVkZTA3MTQ4ODI3OTcyNjcwNDMwZWQ2ODY0NjZlODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XtH_7611SbqCZ0XVwcuoypSlFyfa8Ll6n48ceU-eYng) The results of val_batch0_labels.jpg are as follows: ![val_batch0_labels](https://private-user-images.githubusercontent.com/23652342/263471626-61953dc5-155b-4a51-8308-da4a5c540202.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTA2MjAsIm5iZiI6MTcxNTU5MDMyMCwicGF0aCI6Ii8yMzY1MjM0Mi8yNjM0NzE2MjYtNjE5NTNkYzUtMTU1Yi00YTUxLTgzMDgtZGE0YTVjNTQwMjAyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA4NTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YTI2OTU5YWFjMzljZWZmNmM0NzhmZmNiNmY3NjAzNWM2N2VjNWUwNjdhYmU5YWU1MTdiZjE1ZTM2N2I5ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tz21bPDbOpdrZEul-HUDpRi019GqRFjMQFaUU8_8glc)
> 
> The final test result is that when the black object is in the central area of the grass field, it cannot be segmented. The result is as follows: ![black_20cm_0824_left0267](https://private-user-images.githubusercontent.com/23652342/263471683-59fdfaf1-a5ff-423c-ba11-5f638dea3ab6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTA2MjAsIm5iZiI6MTcxNTU5MDMyMCwicGF0aCI6Ii8yMzY1MjM0Mi8yNjM0NzE2ODMtNTlmZGZhZjEtYTVmZi00MjNjLWJhMTEtNWY2MzhkZWEzYWI2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA4NTIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNDIwZGUzMzQ1YTM2Y2ZjOTFjNWMxOGM3ZjJiMzdiMjE2MDlmNTZkNDM4Yjk5MzUyNDA0YTQ5YTY0NDZkOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hQxypGUgRA8-XpSSDNJl8jIZFnyZzuq9nW7wtQUqi2w) I'm roughly aware of the problem, maybe I shouldn't be treating the item in the middle of the grass as a "background" class. However, I'm hoping to know the best way to go about it. Please help to see how to deal with the best results. Thank you everyone
> 
> ### Additional
> _No response_

Have you used YOLOv8 for semantic segmentation? I am bit confused here. YOLOv8 is for instance segmentation and not for semantic segmentation. I also want to use YOLOv8/ YOLOv9 for semantic segmentation. Can you please give me more details about it?

**Comment by shen865069799** [comment]
你好来信已收到

**Comment by glenn-jocher** [comment]
Hello! Thank you for your message, I've received it. If you have any specific questions or need further assistance, feel free to ask. Happy to help! 😊
