### ISSUE TITLE
CSI stream

### ISSUE THREAD

**Issue by coder-glitche** [ultralytics/ultralytics#4588]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey @glenn-jocher thanks alot with  a watchdog i could get the model to inference on incoming images from drone camera continuously.
I have another issue im unable to give my CSI camera  as a source for inference
 im able to give usb camera by passing source=0 as argument but same is not working with csi camera any suggestions thanks alot !!!!

**Comment by glenn-jocher** [comment]
@coder-glitche hello,

I'm delighted to hear that you've successfully deployed the YOLOv8 model to inference on incoming images from a drone camera. Great work!

Regarding your issue with the CSI camera, when you mention passing source=0, it generally relates to the default webcam on your computer. The CSI camera likely has a different identifier for its source. Usually, CSI cameras need a specific path to be identified as the source.

This path tends to be located in a different place on the system than the default webcam. Unfortunately, without knowing your exact setup and the specific model of your CSI camera, I can't provide an exact solution. I would suggest checking the documentation specific to your camera model and your setup, it should be able to guide you on how to find and use the correct source path for your CSI camera.

Remember, once you have the correct path, you just need to pass it as an argument to the source parameter. Hope this leads you in the right direction.

Best of luck!
