### ISSUE TITLE
Yolo function not taking yolo nano object detection 

### ISSUE THREAD

**Issue by dsnsabari** [ultralytics/ultralytics#4589]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

The checking of yolov8 n size is 22.4 

### Environment

I am using latest ultralytics for training the yolov8 nano object detection model.

I am training the model on AWS Ubuntu. When checked the weights folder the size of pt is 22.4MB 

``#def train_yolo_v8(learning_rate, batch_size, optimizer, num_epochs, architecture, activation, loss, augmentation):
  model = YOLO('yolov8n.pt')
  model.train(data='/content/depondfi_2/data.yaml', epochs=50, imgsz=640, batch=128, name="yolov8n_h", cache=True, device=0) ``

This is code i used for training. Even when i checked the log and the model size is 3M parameters but check point weight so High.

What's the reason?

### Minimal Reproducible Example

  model = YOLO('yolov8n.pt')
  model.train(data='/content/depondfi_2/data.yaml', epochs=50, imgsz=640, batch=128, name="yolov8n_fish", cache=True, device=0)

### Additional

I will share the saved checkpoint screenshot later.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
The model size could be larger while training because the pt file includes extra info like optimizer:
```python
        ckpt = {
            'epoch': self.epoch,
            'best_fitness': self.best_fitness,
            'model': deepcopy(de_parallel(self.model)).half(),
            'ema': deepcopy(self.ema.ema).half(),
            'updates': self.ema.updates,
            'optimizer': self.optimizer.state_dict(),
            'train_args': vars(self.args),  # save as dict
            'date': datetime.now().isoformat(),
            'version': __version__}
``` 
The pt files would be stripped when the training is done so you might get larger pt file if you interrupted your training. [https://github.com/ultralytics/ultralytics/blob/9e58c32c15835e54e57f7b8c925367a64cb94951/ultralytics/yolo/engine/trainer.py#L516](https://github.com/ultralytics/ultralytics/blob/9e58c32c15835e54e57f7b8c925367a64cb94951/ultralytics/yolo/engine/trainer.py#L516)

Also our official models have stripped these extra keys, so the model size is smaller.
If you run `strip_optimizer` with your trained model, the model size should be similar with the official ones.
```python
from ultralytics.yolo.utils.torch_utils import strip_optimizer
strip_optimizer("model.pt")
```

And the file size is not equivalent to param size.

**Comment by dsnsabari** [comment]
@Laughing-q , when we checkout the model into tf . The size would be same or it will be equal to 22MB?

**Comment by dsnsabari** [comment]
@Laughing-q could you share the script for converting the trained model into tf version ( after strip optimisation)

**Comment by Laughing-q** [comment]
@dsnsabari The size should be the same, about 6M if it's fp16, about 12M if it's fp32 type.
I don't really use tensorflow so I don't have such a script, but we've already supported some formats of tensorflow, you can checkout our docs here https://docs.ultralytics.com/modes/export/#export-formats.

**Comment by dsnsabari** [comment]
@Laughing-q , I tried but i was getting the below error. 

```
from ultralytics import YOLO
import cv2
# Load a model
model = YOLO('best.pt')  # pretrained YOLOv8n model
success = model.export(format='saved_model')

```


```
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

```

**Comment by glenn-jocher** [comment]
@dsnsabari this error appears to be related to your current `protobuf` version. The protobuf for python >= 3.19.0 seems to have a problem with its backwards compatibility, and a bug has been reported, but not yet fixed.

To resolve this issue, a workaround could be to downgrade your protobuf package to a version <=3.20.x. You can do this by running `pip install protobuf==3.20.0` and it should solve the error. 

Alternatively, you could try setting the environment variable `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION` to `python` as suggested in the error message. However, this will use a pure-Python implementation which could be much slower. 

Remember to uninstall and reinstall your YOLO package after downgrading/updating the protobuf package.

**Comment by dsnsabari** [comment]
@glenn-jocher , I have installed the  `pip install protobuf==3.20.0` but i am getting different error now. 

```
from ultralytics import YOLO
import cv2
# Load a model
model = YOLO(r'D:\Yolo_format\yolov8n_best\weights\best_py\best.pt')  # pretrained YOLOv8n model
success = model.export(format='saved_model')
# Run batched inference on a list of images

print(success)
```

```
Exception has occurred: OSError
SavedModel file does not exist at: D:\Yolo_format\yolov8n_best\weights\best_py\best_saved_model\{saved_model.pbtxt|saved_model.pb}
  File "D:\object_face_person_detection\convertPytorch2TF2.py", line 5, in <module>
    success = model.export(format='saved_model')
```

**Comment by glenn-jocher** [comment]
@dsnsabari, regarding the first error, it seems the saved_model folder is not found at the mentioned path. YOLOv8 looks for a 'saved_model.pb' or a 'saved_model.pbtxt' file in the provided directory. Please ensure that these files are there and path provided is correct.

For the second error you shared, it seems like you are calling a function 'enable_op_determinism' that doesn't exist within tensorflow module. In the latest versions of tensorflow post v2.4.0, this function is not available and thus is causing an error. Make sure to match the script with the tensorflow version you are using or use the specific tensorflow version that supports the functions called in the script.

**Comment by dsnsabari** [comment]
@glenn-jocher , I am using tensorflow 2.7.0 version for conversion. Do you think the issue is with ONNX's new version? 

I had some problems while converting the custom ONNX models into tf using the new ONNX version.

**Comment by glenn-jocher** [comment]
@dsnsabari hello, it's hard to say for certain without more information, but the problem could potentially be related to compatibility issues with recent versions of ONNX and TensorFlow 2.7.0. 

There have been notable changes and updates in both libraries, and it's possible that the methods and operations used for model conversion are no longer compatible or functioning as expected. 

Regarding issues with custom ONNX models, it could be due to operations in your model that are not supported by your current ONNX or TensorFlow version. It might be beneficial to ensure that your model is using operations supported by both ONNX and TensorFlow libraries.

It would be of great benefit to monitor the respective ONNX and TensorFlow communities and repositories for any known issues that might be related to your situation. It could be beneficial to try the conversion with older or newer versions of both TensorFlow and ONNX, as appropriate, to see if the issue persists.

Remember to always keep both your ONNX and TensorFlow libraries updated to enjoy the latest features and bug fixes.

**Comment by dsnsabari** [comment]
@glenn-jocher Thank you. could you tell me how to convert the yolov8n pt file into tf 2.7.0 version?

**Comment by glenn-jocher** [comment]
@dsnsabari hi there, to convert your `yolov8n.pt` file to TensorFlow version 2.7.0, you would first need to export the model to ONNX format. In the Ultralytics YOLOv8 API, there is a method called `model.export()` that exports the model to ONNX format. You would use it like this: `model.export('name_of_your_onnx_model.onnx')`.

Once you have the ONNX model, you can use the `tf2onnx` package to convert it to TensorFlow. First, you install `tf2onnx` via pip. Then, you run a command similar to this in your terminal: `python -m tf2onnx.convert --opset 13 --onnx name_of_your_onnx_model.onnx --output model.pb`.

This will create a `model.pb` file which is your TensorFlow model.

Please note that this is a general guideline and you might need to adjust some parameters, like the `--opset` flag, depending on your project requirements and the specificities of your model. Be sure to refer to the official documentation of these tools for more detailed instructions.

**Comment by dsnsabari** [comment]
@glenn-jocher 

Thank you. I can convert the models into tf2 using TensorFlow 2.10, but the problem is prediction.  The exported model doesn't have "serving_default". Could you tell me how to solve this issue? 
converted Model: [yolov8n_saved_model_2.10.0.zip](https://github.com/ultralytics/ultralytics/files/12470957/yolov8n_saved_model_2.10.0.zip)


```
import tensorflow as tf
import numpy as np

# Load the saved model
saved_model_path = "/Yolo_format/yolov8n_saved_model_2.10.0/"
loaded_model = tf.saved_model.load(saved_model_path)
#loaded_model = tf.keras.models.load_model(saved_model_path)

shape = (1, 3, 640, 640)
zero_matrix = np.zeros(shape, dtype=np.float32)
image = np.asarray(zero_matrix)


# The input needs to be a tensor, convert it using `tf.convert_to_tensor`.
input_tensor = tf.convert_to_tensor(image)


model_fn = loaded_model.signatures['serving_default']
output_dict = model_fn(input_tensor)
````

**Comment by dsnsabari** [comment]
@glenn-jocher ,  I can run the do prediction, but I cannot do post-processing.   The model output shape is **(1, 6, 8400)**

````
Input name  : images
Input shape : [1, 3, 640, 640]
Input type  : tensor(float)
Output name  : output0
Output shape : [1, 6, 8400]
Output type  : tensor(float)

````

I've included for you the model output numpy file. How can I get xmin,ymin, xmax,ymax, scores, and classes from the output? 

[gustavo-alves-YOXSC4zRcxw-unsplash.zip](https://github.com/ultralytics/ultralytics/files/12494598/gustavo-alves-YOXSC4zRcxw-unsplash.zip)

input image: ![gustavo-alves-YOXSC4zRcxw-unsplash](https://github.com/ultralytics/ultralytics/assets/46018083/4cbf5c04-00ce-498e-a45b-7ff34de5dca0)

**Comment by glenn-jocher** [comment]
@dsnsabari, the model output you're observing is the raw result produced by the YOLOv8 model. This output consists of a prediction for each of the 8400 anchor boxes, with each prediction giving 6 values which correspond to the bounding box coordinates (4 values: xmin, ymin, xmax, ymax), object confidence score (1 value) and class confidence scores (1 value). 

However, these raw output values need to go through a post-processing step to get the final bounding box coordinates, object scores, and class scores. The post-processing generally involves applying a threshold to the confidence scores to filter out weak predictions, and applying Non-Maximum Suppression (NMS) to handle overlapping boxes and keep the ones with the highest score.

In your case, you would need to define a function to apply these post-processing steps to the network output and convert it into detected bounding boxes and their corresponding object and class scores. It's important to note that coordinates are typically output as offsets from a given anchor box and need to be adjusted to give pixel values, and also that class scores may need to be extracted based on your model's specific output format.

Please make sure to understand the entire process from raw model output to final predictions in detail, as per the definitions in the YOLO algorithm and your specific implementation.

**Comment by Codedrainer** [comment]
@dsnsabari have you solved this problem. i think i got caught with same problem. i have deployed model with docker tensorflow/serving but wont be able to infer because of "serving_default" is not present. i have used below command to export the model

`yolo export model==best.pt format=saved_model imgsz=416 keras=True`

@glenn-jocher would be great help if you can suggest some solutions

**Comment by glenn-jocher** [comment]
@Codedrainer, if you're still facing the issue with the missing `serving_default` signature, it's likely due to the export process not defining this signature explicitly. When using the `yolo export` command, ensure that the export creates the necessary TensorFlow Serving signatures.

For the user encountering a similar problem, I recommend checking the export logs to see if there were any warnings or errors during the export process that could indicate why the `serving_default` signature wasn't created. If the issue persists, consider re-exporting the model and verifying that all steps are followed correctly as per the YOLOv8 documentation.

If you need further assistance, please provide more details on the error messages or issues you're encountering, and we'll do our best to help you resolve them.

**Comment by Codedrainer** [comment]
@glenn-jocher where can i check exported logs

**Comment by glenn-jocher** [comment]
@Codedrainer, the export logs should be available in the console output where you ran the `yolo export` command. If you've redirected the output to a file, please check that file. If you can't find the logs, consider re-running the export command and observe the console output for any messages.

**Comment by Codedrainer** [comment]
@glenn-jocher  i have exported model using this command `!yolo export model=/content/drive/MyDrive/gst-ocr/yolov8/runs/detect/train2/weights/best.pt format=saved_model imgsz=416 keras=True`

can you explain what's the actual usecase of ` keras=True` previously, i thought that's for Signaturedef but it's still not adding signature on exported saved model

please find my exported logs below 

`Ultralytics YOLOv8.0.236 🚀 Python-3.10.12 torch-2.1.0+cu121 CPU (Intel Xeon 2.20GHz)
YOLOv8x summary (fused): 268 layers, 68158236 parameters, 0 gradients, 257.6 GFLOPs

PyTorch: starting from '/content/drive/MyDrive/gst-ocr/yolov8/runs/detect/train2/weights/best.pt' with input shape (1, 3, 416, 416) BCHW and output shape(s) (1, 40, 3549) (130.4 MB)
2024-01-07 17:45:20.754795: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

TensorFlow SavedModel: starting export with tensorflow 2.10.0...

ONNX: starting export with onnx 1.15.0 opset 17...
ONNX: simplifying with onnxsim 0.4.35...
ONNX: export success ✅ 31.3s, saved as '/content/drive/MyDrive/gst-ocr/yolov8/runs/detect/train2/weights/best.onnx' (260.1 MB)
TensorFlow SavedModel: running 'onnx2tf -i "/content/drive/MyDrive/gst-ocr/yolov8/runs/detect/train2/weights/best.onnx" -o "/content/drive/MyDrive/gst-ocr/yolov8/runs/detect/train2/weights/best_saved_model" -nuo --non_verbose'
Estimated count of arithmetic ops: 111.410 G  ops, equivalently 55.705 G  MACs
Estimated count of arithmetic ops: 111.410 G  ops, equivalently 55.705 G  MACs
TensorFlow SavedModel: export success ✅ 94.1s, saved as '/content/drive/MyDrive/gst-ocr/yolov8/runs/detect/train2/weights/best_saved_model' (650.5 MB)

Export complete (102.0s)
Results saved to /content/drive/MyDrive/gst-ocr/yolov8/runs/detect/train2/weights
Predict:         yolo predict task=detect model=/content/drive/MyDrive/gst-ocr/yolov8/runs/detect/train2/weights/best_saved_model imgsz=416  
Validate:        yolo val task=detect model=/content/drive/MyDrive/gst-ocr/yolov8/runs/detect/train2/weights/best_saved_model imgsz=416 data=./config/data.yaml  
Visualize:       https://netron.app/
💡 Learn more at https://docs.ultralytics.com/modes/export`
