### ISSUE TITLE
DDP only 1 gpu works problem

### ISSUE THREAD

**Issue by GiUKim** [ultralytics/ultralytics#4598]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

hi, i'm training yolov8 with ddp. 
i have rtx3090 x 4, cuda version 11.1 . 
i try to train using ddp with following code

`from ultralytics import YOLO

model = YOLO("./ultralytics/cfg/models/v8/yolov8.yaml")

model.train(data="ultralytics/cfg/datasets/VisDrone.yaml", epochs=100, device=[0, 1, 2, 3], batch=128, imgsz=640, workers=12)`

but, when train starts, only 1st gpu work seems like to train 128 batch alone. so it died with CUDA OOM.
my current git version is latest.  
(`ultralytics 8.0.164` new StreamLoader `stream_buffer` argument (#4596))

remain 3 gpus are not trained and not loaded any memory. any problem with my training script?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@GiUKim Thanks for the reporting! probably this is a bug introduced by me yesterday when I was trying to fix a test of ddp in our ci tests:(. I'll take a look soon.

**Comment by Laughing-q** [comment]
@GiUKim Please use ultralytics=8.0.163 before the bug fixed. :)

**Comment by GiUKim** [comment]
@Laughing-q got it. thanks much!

**Comment by Laughing-q** [comment]
@GiUKim or try passing device arg this way `device="0,1,2,3"` for 8.0.164, I just figured I forgot to include list type, which I'll add it later. :)

**Comment by GiUKim** [comment]
@Laughing-q Thanks now it's worked well! by "Fix DDP when device is a list (https://github.com/ultralytics/ultralytics/pull/4600)"

**Comment by Laughing-q** [comment]
@GiUKim That's good to know! I'm closing this issue then, please feel free to reopen it if you have any related issues! :)
