### ISSUE TITLE
All losses went to nan and precision & recall went low & static

### ISSUE THREAD

**Issue by ahthserhsluk** [ultralytics/ultralytics#461]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

What inference should I take from this? 

I ran YOLO v8 for 300 epochs but after 7 epochs all loss values went to nan, and precision & recall went static to very low. 

![image](https://user-images.githubusercontent.com/52717339/213082804-b2652fdf-c3c5-4092-9df4-44d09b998e12.png)

**Comment by Laughing-q** [comment]
@ahthserhsluk hi, may I ask if there're corrupt labels in your datasets?
![oRFtMgd2vI](https://user-images.githubusercontent.com/61612323/213076139-3ec3d352-42ca-4b8a-82ed-3834b40364c2.jpg)
actually I just found that we got a mismatch issue if there's corrupt label in datasets, so if you guys got corrupt labels then your issues could be solved by this PR. #460

**Comment by ahthserhsluk** [comment]
no corrupt labels!

**Comment by fcakyon** [comment]
@ahthserhsluk what is your imgsz during training?

**Comment by ahthserhsluk** [comment]
i tried with 640*360


now planning to do with 1920*1080, but will take time

**Comment by luigisaetta** [comment]
@ahthserhsluk I have a similar issue, not exactly the same. I have a dataset and I was able to train yolo v8. Then I have added 30 images obtained through Albumentations controlled augmentation. The training goes fine for let's say 50 epochs and then suddenly precision and recall and mAP50 goes really close t 0 (let's say 1e-5). With yolo v5 it works ok. Have you tried any explanation?

**Comment by ahthserhsluk** [comment]
my dataset is highly imbalanced, so i think that may be the problem.

**Comment by fcakyon** [comment]
I am having a similar issue on a custom dataset of only 1 class. It may be not related to the imbalance.

**Comment by AyushExel** [comment]
Guys we're trying to figure out this issue. Please keep a lookout here 
https://github.com/ultralytics/ultralytics/issues/186

**Comment by ahthserhsluk** [comment]
is batchsize of 2-4 okay? if i go any further, it shows a paging error.

**Comment by Laughing-q** [comment]
@ahthserhsluk @fcakyon @luigisaetta hi guys, the nan loss issue could be solved in this PR #490. We'll merge it later today. :)
