### ISSUE TITLE
about Accuray metric

### ISSUE THREAD

**Issue by xbkaishui** [ultralytics/ultralytics#4620]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi guys: 

I check the metric but can't find the Accuracy metric,  is it necceary ？

**Comment by xbkaishui** [comment]
got it thanks

**Comment by glenn-jocher** [comment]
@xbkaishui you're welcome! If you have any other questions or run into any issues, feel free to reach out. Happy coding with YOLOv8!
