### ISSUE TITLE
Precision and Recall and mAP50 goes to zero after some epochs

### ISSUE THREAD

**Issue by luigisaetta** [ultralytics/ultralytics#463]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have added 30 images to a dataset already used. When retraining yolo v8 after several epochs Precision, Recall and mAP50 goes to values really low (mAP50 is 1e-5). I'm able to train with YOLO v5. What could be the problem? What should I check? For now I have gone back to v5, but I seriously wanted to use v8

**Comment by AyushExel** [comment]
https://github.com/ultralytics/ultralytics/issues/186
Please keep an eye out here. We're trying to find the reason for this issue
