### ISSUE TITLE
Сontinue (resume) of training

### ISSUE THREAD

**Issue by Egorundel** [ultralytics/ultralytics#4642]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Do you have the opportunity to continue your training if for some reason the training has not been completed to the end?

**Comment by glenn-jocher** [comment]
@Egorundel yes of course! See https://docs.ultralytics.com/modes/train/#resuming-interrupted-trainings

**Comment by Egorundel** [comment]
@glenn-jocher Thanks for help!

**Comment by glenn-jocher** [comment]
@Egorundel you're welcome! I'm glad I could help. If you have any more questions about YOLOv8 or run into any problems, feel free to post again. Happy training!
