### ISSUE TITLE
yolov5 with yolov8 (ultralytics pip package)

### ISSUE THREAD

**Issue by velastin** [ultralytics/ultralytics#4647]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello. 
From some preliminary tests I have done, it appears that it is possible to use yolov5 models (e.g. yolov5lu.pt) within the yolov8 "environment" i.e. "pip install ultralytics" followed by using the CLI interface ("yolo model= ...."). Is this the case?
However, the yolov5 documentation (https://docs.ultralytics.com/yolov5/quickstart_tutorial/) does not seem to refer to this and it uses for example "python train.py ....").

1. So, what is the current preferred way of working? Perhaps you are moving to the newer yolov8 "API"?
2. Are there licensing issues? (e.g. I think at some time it was not possible to use Yolov8 for commercial implementations).
3. Is it possible to use yolov5/yolov8 with source unchanged in commercial applications under the standard open source licence?)
4. Are there actually differences between the latest (v7.0?) yolov5 and yolov8 architectures or is it mainly changes in API?
Thank you

**Comment by glenn-jocher** [comment]
@velastin hello,

Thank you for your interest in YOLOv8 and taking the time to formulate these detailed questions.

1. As you have observed, YOLOv8 indeed provides a CLI interface that allows for various operations such as training, validation, prediction etc. The preferred mode of operation is largely a user's choice, and depends on their familiarization with the command line interface or Python scripting. The Ultralytics team is continuously working to improve the user experience, and updates to the CLI interface and API are rolled out regularly.

2. In terms of licensing, YOLOv8 is generally available under the AGPL-3.0 License, which mandates that any project that uses the code must also be open-sourced under the AGPL. However, we do offer an Enterprise License that provides more flexibility for closed-source commercial use.

3. Yes, it's possible to use YOLOv8 in commercial applications either under the AGPL-3.0 license (where your modifications and dependent work will need to be open sourced) or under the Enterprise License, which has different conditions suitable for commercial use.

4. The major changes from previous versions to YOLOv8 are centred around enhanced performance, output quality, and scalability. YOLOv8 also offers several new features and improvements over previous versions, however the architectural differences between YOLOv5 and YOLOv8 are more specific and technical in nature.

We appreciate your questions and hope this provides clear answers. The Ultralytics team, along with the broader YOLO community, remains committed to providing useful tools and resources to facilitate your work.

Best Regards,
Glenn Jocher

**Comment by velastin** [comment]
Thank you Glenn for your (usual) prompt response. So, I understand that yolov5 and yolov8 are separate. What I am not sure is if the pip package "ultralytics" (ie. the one that supports CLI and Python) can/should be used to train/predict/etc with yolov5 models. If that were the case, then there would just be a single "API"? But would this keep pace with changes in yolov5? Sorry if I am still a little bit confused.

**Comment by velastin** [comment]
Thanks again Glenn.
The very specific point is this: Say I install the ultralytics pip package. Say I then use the CLI to issue something like (sorry if not exactly correct): yolo train model=XXXX ....
Where XXXX is one of the pre-trained **yolov5** models (e.g., yolov5lu).
Would that train a model with a yolov5 architecture i.e., be equivalent to having cloned the yolov5 repo and done the training using that repo?

**Comment by glenn-jocher** [comment]
Hello @velastin,

Ultralytics YOLOv8 pipeline, including the pip package and its CLI capability, is designed specifically for YOLOv8 models. While you are correct that commands issued using the Ultralytics CLI will execute tasks like training, the pipeline is not setup to directly use pre-trained YOLO models that are not within the YOLOv8 architecture.

In other words, when you issue a 'train' command using the Ultralytics CLI while specifying a pre-trained YOLOv8 model, it will train a model under the YOLOv8 architecture, not YOLOv5 or any other YOLO version.

I hope this clarifies the specifics of the Ultralytics YOLOv8 pipeline. Feel free to ask if you have any other queries.

**Comment by velastin** [comment]
Hello Glenn. I do appreciate the time you use to answer questions, even if they are trivial ones.
Some days ago I did in fact do what I outlined above i.e., use the pip package and then the CLI to run something like
yolo train model=yolov5lu.pt .... and after training yolo val model=best.pt ....
The results were very good. So what do you think happened? Have I effectively trained a yolov8 model by doing this?
Many thanks

**Comment by glenn-jocher** [comment]
Hello @velastin,

Thanks for your question and kind words, they aren't trivial at all. It is indeed possible that executing the 'yolo train' command with a model specified appeared to run successfully, and even yielded good results for specific tasks. 

What happened under the hood is that our YOLOv8 pipeline interpreted the parameters provided and the CLI training command as best it could, and proceeded with the training on a YOLOv8 model. While you specified 'yolov5lu.pt' as the model in the command, this would not have translated into training a YOLOv5 model. The training process would have been done within the YOLOv8 architecture and any resulting model would conform to this structure.

Do note that due to differences in architecture and implementations across different versions of YOLO, it's recommended to use the corresponding training pipeline for each specific model to ensure that you're fully utilizing the benefits and improvements of that particular version.

I trust this provides some clarity to what you experienced. Thanks for your interest in YOLOv8, and feel free to reach out any time.

Best Regards,
Glenn Jocher

**Comment by imPdhar** [comment]
Hey @glenn-jocher, Thanks for all the work you do! I need to instantiate yolov8 and yolov5 in the same python file for research purposes. How do I call, export for onnx and predict from both of their models separately (not at the same time though) without using CLI and other internal clashes?

**Comment by glenn-jocher** [comment]
Hey there! 🌟 Thanks for your kind words and for bringing your question to us. You can definitely work with YOLOv8 and YOLOv5 models in the same Python script. Here's a quick way to do it for instantiation, export, and prediction, along with extracting bbox values from results.

```python
from ultralytics import YOLO  # For YOLOv8
import torch  # Assuming you have the YOLOv5 repository for YOLOv5

# Instantiate YOLOv8
model_v8 = YOLO('path/to/yolov8/model.pt')

# Export YOLOv8 to ONNX
model_v8.export(format='onnx', imgsz=640)

# Predict with YOLOv8
results_v8 = model_v8('path/to/image.jpg')
boxes_v8 = results_v8[0].boxes.xyxy[0]  # Assuming the first result

# For YOLOv5, ensure you have the YOLOv5 repo and use torch.hub.load or equivalent to load the model
model_v5 = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/yolov5/model.pt')

# Export YOLOv5 to ONNX is a bit more manual, refer to YOLOv5 documentation

# Predict with YOLOv5
results_v5 = model_v5('path/to/another/image.jpg')
boxes_v5 = results_v5.xyxy[0]  # Bboxes, scores, classes

# Note: for bbox values with YOLOv5, 'results.xyxy[0]' already contains bbox in xyxy format.
```
Make sure to adjust 'path/to/model.pt' and 'path/to/image.jpg' to your actual paths. This should help you manage both models without causing any internal clashes. 😊

Let me know if you need further assistance. Happy researching!

**Comment by imPdhar** [comment]
> Hey there! 🌟 Thanks for your kind words and for bringing your question to us. You can definitely work with YOLOv8 and YOLOv5 models in the same Python script. Here's a quick way to do it for instantiation, export, and prediction, along with extracting bbox values from results.
> 
> ```python
> from ultralytics import YOLO  # For YOLOv8
> import torch  # Assuming you have the YOLOv5 repository for YOLOv5
> 
> # Instantiate YOLOv8
> model_v8 = YOLO('path/to/yolov8/model.pt')
> 
> # Export YOLOv8 to ONNX
> model_v8.export(format='onnx', imgsz=640)
> 
> # Predict with YOLOv8
> results_v8 = model_v8('path/to/image.jpg')
> boxes_v8 = results_v8[0].boxes.xyxy[0]  # Assuming the first result
> 
> # For YOLOv5, ensure you have the YOLOv5 repo and use torch.hub.load or equivalent to load the model
> model_v5 = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/yolov5/model.pt')
> 
> # Export YOLOv5 to ONNX is a bit more manual, refer to YOLOv5 documentation
> 
> # Predict with YOLOv5
> results_v5 = model_v5('path/to/another/image.jpg')
> boxes_v5 = results_v5.xyxy[0]  # Bboxes, scores, classes
> 
> # Note: for bbox values with YOLOv5, 'results.xyxy[0]' already contains bbox in xyxy format.
> ```
> 
> Make sure to adjust 'path/to/model.pt' and 'path/to/image.jpg' to your actual paths. This should help you manage both models without causing any internal clashes. 😊
> 
> Let me know if you need further assistance. Happy researching!

![image](https://github.com/ultralytics/ultralytics/assets/37359679/02f8d3f0-0719-41c2-aa66-6ea8b2ce2326)
Btw I am getting this error if I try to run this. Not sure why. Tested with other files too.

**Comment by glenn-jocher** [comment]
Hey there! 😊 Glad you found the guide helpful!
Regarding the error you're encountering, it looks like an issue with the path to the model or the image file. Ensure the path exactly matches where your models and images are stored. If the issue persists, double-check if the model files are correctly downloaded and not corrupted.

```python
# Double-check your paths
model_v8_path = 'path/to/yolov8/model.pt'
model_v5_path = 'path/to/yolov5/model.pt'
image_v8_path = 'path/to/image.jpg'
image_v5_path = 'path/to/another/image.jpg'

model_v8 = YOLO(model_v8_path)
results_v8 = model_v8(image_v8_path)

model_v5 = torch.hub.load('ultralytics/yolov5', 'custom', path=model_v5_path)
results_v5 = model_v5(image_v5_path)
```

If paths look correct, and the issue isn't resolved, feel free to share more details or error messages, and we'll dive deeper! 🕵️‍♂️
