### ISSUE TITLE
yolov8 memory usage while training - higher than v5 using same config

### ISSUE THREAD

**Issue by renatoviolin** [ultralytics/ultralytics#465]
I'm trying to migrate my project from v5 to v8, using the same dataset, batchsize, imgsize and model size (yolov8m.pt) but with v8 I get OOM in the first epoch.
To train I need to reduce the batch or the image size.
Has anyone have had some issue like this?

**Comment by ichsan2895** [comment]
Yes, from my experient, `Yolov8` is using **little bit** more memory for training than `Yolov5`, but the accuracy increased much more **drastically**. Take a look in my draft for duel between each version of yolo (`v5m`, `v7`, and `v8m`)

https://colab.research.google.com/drive/1GbC5LNxh_BuV-zEl6UBcSdSZvtC48PUJ?usp=sharing

Yolov5 is still good with if your target is the speed and low memory usage when training.

**Comment by AyushExel** [comment]
We'll fix this issue soon. Ultralytics framework will use the same memory as v5

**Comment by ytylalal** [comment]
> We'll fix this issue soon. Ultralytics framework will use the same memory as v5
Two week has been passed =~=
I suggest to reuse the code style of yolov5， the new code style is much more difficult to read, modify and locate bug than before.

**Comment by Ss-shuang123** [comment]
> We'll fix this issue soon. Ultralytics framework will use the same memory as v5

**Comment by rnditdev** [comment]
Having OOM issues too.

**Comment by glenn-jocher** [comment]
@rnditdev sorry to hear that you're experiencing OOM issues. Generally, to overcome OOM issues, you can try reducing the batch size, reducing the image size, or optimizing your code to make it more memory-efficient. Additionally, you can consider using mixed-precision training or parallel training to reduce the memory usage. Other possible solutions may depend on your specific use case, so feel free to provide more details if you'd like us to suggest any specific approaches.

**Comment by rnditdev** [comment]
Just trying to train vanilla coco. It crashes at 45 GBs of memory. Tried reducing the  batch size to 8, and reducing the image size to 320, but the amount of needed memory seems to be stable.

**Comment by glenn-jocher** [comment]
@rnditdev thanks for providing additional information. Even with reduced batch size and image size, you're still experiencing OOM issues which suggest that maybe reducing the batch size or image size further might not be sufficient to prevent OOM errors. In this case, you may want to consider using mixed-precision training, which can help to reduce the memory usage during training by using half-precision floating-point format. Additionally, you can try to reduce the amount of memory used by your model itself, by reducing the size of the model architecture, or optimizing your code to be more memory-efficient. You may also want to look into the memory usage of other processes on your machine during training to ensure they're not interfering with your training process.
