### ISSUE TITLE
Un-expected image size upon inference

### ISSUE THREAD

**Issue by Lihi-Gur-Arie** [ultralytics/ultralytics#4651]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello!

I must start by acknowledging the remarkable work you are doing! I am currently running inference using a custom YOLOv8n model, utilizing the model.predict() function. The input consists of a list of 4 numpy RGB images, originally sized at 2048x1536 pixels. However, I employed the imgsz=1024 parameter to downsize the images during both training and inference. I assumed that this would result in the input images having dimensions of 1024x1024 pixels when inputted into the model. Yet, upon inspection, I observed that during inference, the image dimensions are actually 1024x768 pixels, without any padding. I am curious to know if this is the expected behavior or a potential bug. Additionally, I am wondering if the input size during training was also 1024x768 pixels, similar to the inference.

Thank you for your support!

**Comment by glenn-jocher** [comment]
@Lihi-Gur-Arie hello,

Thank you for your words of appreciation. I'm glad to hear you're finding our work useful!

In regards to your question, the 'imgsz=1024' attribute scales the largest dimension of an image to 1024 pixels. This is why you're seeing a change in dimensions for your input images, as the implementation aims to preserve the original aspect ratio of the images without any padding.

So, if your original images are of size 2048x1536, when 'imgsz=1024' is used, it scales down the larger dimension (2048) to 1024 pixels. The other dimension then becomes 1024*(1536/2048) = 768 pixels, maintaining the same aspect ratio.

The same process is applied during both training and inference, so, in your case, the input size during training would also have been 1024x768 pixels. 

This behavior is as expected, and not a bug, as it helps in maintaining the aspect ratio, which is often critical in object detection tasks.

I hope this clarifies your question. Feel free to ask if you need more information on this or any other aspect of your work with YOLOv8.

Best regards,
Glenn

**Comment by Laughing-q** [comment]
@Lihi-Gur-Arie This is because we have a internal param `auto=True` during inference, it'll resize and pad the image to rectangle other than square for better speed performance. Please passing image size as a tuple or a list `imgsz=[1024,1024]` if you want it to be a square image.

About training, the images would be resized and padded to square size by default during training.
