### ISSUE TITLE
save results as .CSV or TXT

### ISSUE THREAD

**Issue by abdalluhahmed** [ultralytics/ultralytics#4655]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I extend my gratitude for your thoughtful contributions. I come bearing a question: I am interested in preserving the validation outcomes for segmentation and detection. Specifically, I aim to save these results within a .csv or .txt file. Your insights and guidance regarding this matter would be greatly appreciated.
 
Thank you and best regards,

### Additional

This function work for training , but for validation not 

    def plot_metrics(self):
        """Plots metrics from a CSV file."""
        plot_results(file=self.csv, on_plot=self.on_plot)  # save results.png

_No response_

**Comment by glenn-jocher** [comment]
@abdalluhahmed the simplest way would just be to handle the results and save them as you see fit, i.e.

```python
results = model.val()

# Save results to CSV or *.txt
for r in results:
    # custom handling here
```

**Comment by abdalluhahmed** [comment]
Thank you brother :)

**Comment by abdalluhahmed** [comment]
Thank you very much brother. I resolved it by directly extracting the results from the metrics, including f, p, r, and so on

**Comment by glenn-jocher** [comment]
@abdalluhahmed, 

I'm very glad to hear that you've successfully managed to extract the results from the metrics, including f, p, r, and so forth. It's excellent news, and your self-driven approach to finding a solution is commendable. 

Your method of direct metric extraction is indeed an effective way of handling your requirement to preserve validation outcomes. By doing so, you've leveraged the inherent flexibility of the Ultralytics software stack, which has been designed with customization and extensibility in mind. 

If you have any other queries or if there's anything else you wish to discuss about YOLOv8 or any other models in the future, don't hesitate to contact us. Enjoy your ongoing work with the Ultralytics YOLOv8 repo!

Best wishes,
Glenn Jocher
