### ISSUE TITLE
How to get the class of pose (frontal or sideways) from YOLO V8 Pose Estimation

### ISSUE THREAD

**Issue by tawfiq1200** [ultralytics/ultralytics#4657]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

YOLO V8 pre-trained models provide a confidence score. Is there anyway I can extract the class of pose from YOLO V8? The classes of pose can be frontal, sideways or back.

@glenn-jocher may be you can help with this question too, you answered my question [here](https://github.com/ultralytics/ultralytics/issues/4581#issuecomment-1694484568).

**Comment by glenn-jocher** [comment]
@tawfiq1200 hello and thank you for your question about YOLOv8 pose estimation.

Generally, in a pose estimation use case, YOLOv8 would typically detect different keypoints on the objects in the images, then the pose type (frontal, sideways, or back) can be determined based on the relative positions of these keypoints.

As per your question regarding extracting pose class directly from YOLOv8, it may require training a model specifically for this task, where each pose type would be a different class. This would involve annotating your dataset in a way that distinguishes between frontal, sideways, or back poses.

Keep in mind that the confidence score provided by YOLOv8 indicates the model's certainty of the detection, and not the class of pose. 

Please note that the pose estimation and determining the pose type should be treated as two different tasks. The first task is handled by YOLOv8, but the latter would either need a custom model specifically trained for detecting pose types, or post-processing of estimated keypoints to classify the pose.

Hope this explanation clears up your query. Don't hesitate to ask if you have more questions.
