### ISSUE TITLE
I still haven't been able to give pose training.

### ISSUE THREAD

**Issue by sarpx** [ultralytics/ultralytics#4662]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have installed the latest versions. I have read all the documents many times. I set the tags as I gave an example in the attachment below. My yaml file is as follows, but when I train, only detect training works, no pose training. What could I be missing here?

`path:\datasets\pose
train: images/1690529926/
val: images/1690529926/
nc: 1
kpt_shape: [54,2]
flip_idx: [1,0,3,2,8,9,7,6,4,5,13,12,11,10,15,14,17,16,19,18,21,20,23,22,25,24,27,26,29,28,31,30,33,32,35,34,37,36,39,38,41,40,43,42,48,49,50,51,44,45,46,47,53,52]
names: ['abc']

download: https://ultralytics.com/assets/coco8-pose.zip`

`yolo detect train data=\datasets\pose\1690456022.yaml model=yolov8x-pose-p6.pt epochs=100 imgsz=640`

### Additional

[14260763416800.txt](https://github.com/ultralytics/ultralytics/files/12483466/14260763416800.txt)
[14263296101500.txt](https://github.com/ultralytics/ultralytics/files/12483467/14263296101500.txt)

**Comment by glenn-jocher** [comment]
@sarpx hello,

Thank you for bringing this issue to our attention. Based on your description, it seems like you've done everything correctly with the configuration to qualify for pose training. However, there may be a number of reasons why only the detect training is functioning.

Before digging into the possible issues, let's ensure that your dataset is correctly set up for pose estimation. Specifically, does your dataset include keypoints in its annotations? Also, make sure your annotations are compatible with YOLOv8's pose estimation requirements.

Furthermore, ensure that you are using the correct model for pose estimation. Not all models support every feature. For pose training, make sure you are using a model configuration that has been specifically designed for this task.

Lastly, remember that pose estimation and object detection are different tasks. Depending on the model configuration and input data, it may be that pose training isn't happening because the model isn't recognizing an opportunity to do so. You might need to adjust your model configuration or dataset.

If you're still facing issues, please share with us more information, such as the model configuration you are using and the detailed logs produced during training. This will help to narrow down the issue and provide a more tailored solution.

Best regards,
Glenn

**Comment by sarpx** [comment]
@glenn-jocher,
I started getting an error like this:
`raceback (most recent call last):
  File "C:\Users\sy\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sy\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "dd\venv\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "dd\venv\lib\site-packages\ultralytics\cfg\__init__.py", line 446, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "dd\venv\lib\site-packages\ultralytics\engine\model.py", line 341, in train
    self.trainer.train()
  File "dd\venv\lib\site-packages\ultralytics\engine\trainer.py", line 196, in train
    self._do_train(world_size)
  File "dd\venv\lib\site-packages\ultralytics\engine\trainer.py", line 333, in _do_train
    for i, batch in pbar:
  File "dd\venv\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "dd\venv\lib\site-packages\ultralytics\data\build.py", line 38, in __iter__
    yield next(self.iterator)
  File "dd\venv\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "dd\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "dd\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "dd\venv\lib\site-packages\torch\_utils.py", line 425, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "dd\venv\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "dd\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "dd\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "dd\venv\lib\site-packages\ultralytics\data\base.py", line 240, in __getitem__
    return self.transforms(self.get_image_and_label(index))
  File "dd\venv\lib\site-packages\ultralytics\data\augment.py", line 55, in __call__
    data = t(data)
  File "dd\venv\lib\site-packages\ultralytics\data\augment.py", line 739, in __call__
    labels['keypoints'] = torch.from_numpy(instances.keypoints)
TypeError: expected np.ndarray (got NoneType)`

**Comment by glenn-jocher** [comment]
@sarpx hello,

Based on your traceback, it seems like the error is related to the keypoint labels in your dataset. The message "TypeError: expected np.ndarray (got NoneType)" indicates that the model is expecting the `keypoints` attribute to be a NumPy array but instead it's receiving a NoneType object. 

In the context of image annotation for object detection models like YOLOv8, keypoints are locations in an image that define certain regions, or "parts" of an object. When the model is being trained on a dataset for keypoint estimation tasks, it uses these keypoints as reference points to recognize patterns and learn to identify similar instances in new data. 

The error might be a result of one of three possibilities; either your dataset doesn't contain any keypoint information, the keypoint data is incorrectly formatted or missing for some data points, or there may be a software bug that is leading to this incorrect data type error.

Before another attempt at training, please review your dataset and make sure that all your annotations contain keypoint data where applicable and that the data is correctly formatted as an array.

If you believe the issue could be a bug, it would be very beneficial to provide a full report that includes steps for reproduction and any additional details about your dataset and setup. That way, we can more quickly confirm, investigate, and resolve any potential software issues.

Thank you for your understanding and for helping us improve the repository.

Best,
Glenn.

**Comment by sarpx** [comment]
I found the broken tags and fixed them. And I installed ultralytics from scratch for the new version and finally I was able to provide training, thank you

**Comment by pderrenger** [comment]
@sarpx you're welcome! I'm glad to hear that you were able to resolve the issue and successfully provide the training. If you have any more questions or encounter any further difficulties, feel free to ask. We're here to help! Good luck with your project!

**Comment by WissamKasti** [comment]
Hey @sarpx, what was the broken tags? How did you find them? And how did you fixed it? I am currently at the exactly same problem like you have. Thank you in advance

**Comment by KevinQuaid-tencent** [comment]
Hey @WissamKasti,  I got this same error because I was missing newlines at the end of my label data.  Adding \n to the end of my python strings before saving each label file fixed everything and I could train.
