### ISSUE TITLE
How can I obtain the output of the intermediate layers in yolov8-cls?

### ISSUE THREAD

**Issue by eorroot** [ultralytics/ultralytics#4665]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/ultralytics/ultralytics/assets/49010412/408e6a1b-c44a-42e2-91c2-b8a56b45fd90)

![image](https://github.com/ultralytics/ultralytics/assets/49010412/16268e5b-1f9c-4da4-bd4a-a966884bb107)
"I want to obtain the features of the intermediate layers in the yolov8-cls model, but I don't know how to get them. How can I do that?

**Comment by glenn-jocher** [comment]
@eorroot hello,

Thank you for reaching out and being part of the YOLOv8 community!

To access the output of intermediate layers in a yolov8-cls model, you would first need to identify the layers of interest by studying the model's architecture. After you have identified the layers you are interested in, you have to modify your model to output these intermediary features.

In practice, this usually involves adjusting the forward pass of your model to return not only the final output but also the outputs of the intermediate layers you've selected. It's like creating multiple exit points in your model's architecture, where each exit point corresponds to an intermediate layer whose output you want to investigate.

Just keep in mind that working with these intermediate features can be quite advanced depending on your use case, as these features are often high-dimensional, non-linear transformations of your input data. 

I hope this helps and if you need further assistance, feel free to ask. 

Best regards,
Glenn Jocher
