### ISSUE TITLE
Random Crop Train on small size, Validate and Predict on Full image?

### ISSUE THREAD

**Issue by BingoNate** [ultralytics/ultralytics#4667]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

1. The image size is very large (i.e. 4096x2048) and the defects are small. We can do RandomCrop based on Albumentations class in Ultralytics. Q1: Does this Random Crop Transforms do correctly both support detection and instance segmentation?

class Albumentations:
    """YOLOv8 Albumentations class (optional, only used if package is installed)"""

    def __init__(self, crop_size=640, p=1.0):
        """Initialize the transform object for YOLO bbox formatted params."""
        self.p = p
        self.transform = None
        self.crop_size = crop_size
        prefix = colorstr('albumentations: ')
        try:
            import albumentations as A

            check_version(A.__version__, '1.0.3', hard=True)  # version requirement

            # T = [A.PadIfNeeded(min_height=self.crop_size, min_width=self.crop_size, always_apply=True, border_mode=cv2.BORDER_CONSTANT)]
            T = [A.RandomCrop(self.crop_size, self.crop_size, always_apply=True, p=1.0)]
            T += [
                A.Blur(p=0.01),
                A.MedianBlur(p=0.01),
                A.ToGray(p=0.01),
                A.CLAHE(p=0.01),
                A.RandomBrightnessContrast(p=0.0),
                A.RandomGamma(p=0.0),
                A.ImageCompression(quality_lower=75, p=0.0)]  # transforms            
            self.transform = A.Compose(T, bbox_params=A.BboxParams(format='yolo', label_fields=['class_labels']))

            LOGGER.info(prefix + ', '.join(f'{x}'.replace('always_apply=False, ', '') for x in T if x.p))
        except ImportError:  # package not installed, skip
            pass
        except Exception as e:
            LOGGER.info(f'{prefix}{e}')

    def __call__(self, labels):
        """Generates object detections and returns a dictionary with detection results."""
        img = labels['img']
        cls = labels['cls']
        if len(cls):
            h, w, _ = img.shape
            instances = labels['instances']
            instances.convert_bbox('xywh')
            instances.normalize(w, h)

            bboxes = instances.bboxes
            segments = instances.segments
            
            if len(segments):            
                masks = polygons2masks((h, w), segments, color=1)
                
            if self.transform and random.random() < self.p:
                
                # crop_x = random.randint(0, w - self.crop_size)
                # crop_y = random.randint(0, h - self.crop_size)
                
                # img_crop = img[crop_y : crop_y + self.crop_size, crop_x : crop_x + self.crop_size]
                # masks_crop = masks[:, crop_y : crop_y + self.crop_size, crop_x : crop_x + self.crop_size]
                # transformed = self.transform(image=img_crop, bboxes=bboxes, masks=masks_crop, class_labels=cls) 
                while True:
                    transformed = self.transform(image=img, bboxes=bboxes, class_labels=cls)
                    if len(transformed['class_labels']) > 0:
                        break
                # transformed = self.transform(image=img, bboxes=bboxes, masks=masks, class_labels=cls)
                # if len(transformed['class_labels']) > 0:
                labels['img'] = transformed['image']
                labels['cls'] = np.array(transformed['class_labels'])
                bboxes = np.array(transformed['bboxes'], dtype=np.float32)
                
                masks = transformed['masks'] if 'masks' in transformed else None
                
                if masks is not None:
                    segments = self.masks2polygons(masks)
                        
            labels['instances'].update(bboxes=bboxes)
            # labels['instances'].update(bboxes=bboxes, segments=segments)
            # labels['masks'] = masks
            # Check if labels['instances'] is empty or >70% of crop image size.
        return labels
    
    def masks2polygons(self, masks):
        polygons = []
        for mask in masks:
            contours, _ = cv2.findContours(mask.astype(np.uint8), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
            for contour in contours:
                polygon = contour.squeeze().tolist()
                if len(polygon) >= 3:
                    polygons.append(polygon)
        return polygons
        
       2. When we do model train, as this transforms will be applied to datasets in build_transforms method. How do we correctly do validation? The validation is wrong since the model is trained on small size (like 640x640), while the image size remains its original size with labels. How to modify the val.py to adjust the right validation?
       
       3. Last, how to quickly/correctly to do inference on full size image with the crop trained model? With SAHI? or other best practices?
       
       Thank you!

**Comment by glenn-jocher** [comment]
@BingoNate 1. The Albumentations class that you've specified is indeed configured to support both detection and instance segmentation tasks. However, note that it's important to ensure that the 'bboxes' and 'class_labels' fields are correctly formatted for the YOLOv8 object detection model and that instance segmentation masks are correctly processed and formatted as well.

2. For validation, if you've trained your model on cropped images of a certain size, you'll need to ensure that the validation images are processed in the same way to maintain consistency. This means you'd also apply the same crop to these images before passing them through the model. If this is not possible due to varying image sizes in your validation dataset, you might need to implement a custom solution that can handle different image sizes appropriately.

3. One straightforward method to infer on the larger, uncropped images is to slide a window over the entire image and then pass each windowed section through the model as if it were a separate image. The predicted outputs would then need to be re-composited back onto the larger image. However, this can be computationally expensive if the images are large. Libraries like SAHI provide faster alternatives for inference on large images by implementing strategies such as dynamic sliding windows and mask merging. Note, however, that the specific method would depend on the distinctive characteristics of your application, such as the size of the objects of interest relative to the whole image.

**Comment by BingoNate** [comment]
1. Actually, the ablumentation library support both detection and instance segmentation, as we do in train (above code) to generate random cropped image with labels adjuted.
2. You mean that the validation cannot directly do random crop transform as in train loop? By now, I have tried to do same transformation without modifying the validation codes (just change the transform as in method 'build_transform'), the codes does not run correctly, throughout errors. How can we do same transform on validation, samples? Or, due to the randomness of the transform on validation, the metrics seems not make sense to qualify the model. This means we should also do validation with full image size, which is much more complicated? (Or some code samples suggestion?)

**Comment by glenn-jocher** [comment]
@BingoNate 1. You're correct that the Albumentations library does support both detection and instance segmentation. It's crucial to ensure, as you have done, that 'bboxes' and 'class_labels' fields are appropriately formatted for your object detection model, and your instance segmentation masks are correctly processed.

2. For validation, it's indeed recommended not to use random cropping as in the training loop. The reason for this is that we want to validate the model under conditions that are as close as possible to how it will be used during inference. While you can technically use the same transformations in validation as in training, it may not always give you a realistic measure of your model's performance .

3. If you want to evaluate your model on full-sized images during validation, you'll need to adapt your approach as this can be more complex. For instance, one way to do this could be to implement a sliding window approach where you pass parts of the image through the model and then reassemble the predictions. However, this can be computationally intensive, especially for large images.  There are optimization techniques to speed this process up, although the best approach does depend on the specifics of your setting, such as the relative size of the objects you're interested in detecting. 

Please ensure that the same processes applied for training the model are reflected in your validation step to maintain consistency in the overall accuracy and effectiveness of your model.

**Comment by BingoNate** [comment]
1. Actually, the transforms do correct jobs to adjust the labels and images already.
2. If we do not use cropping transforms in validation, how can we validate the right metrics in validation with these batch images so large? You mean that sliding window method as in SAHI for inference can help. However, the codes can be complicated in modifying the validation method as in val.py? If there is a more simple and correct way to do in validation, it will be very helpful for me to quickly learn and modify the codes if you suggest these samples or methods.

**Comment by glenn-jocher** [comment]
@BingoNate, 

1. It's great that the transforms correctly adjust the labels and images already. Ensuring proper transformation is a key step in efficiently training models, and it's helpful that you've already accomplished that. 

2. When processing large images during validation, one common strategy, as you mentioned, is to use a sliding window. That said, implementation could indeed become complex, particularly when modifying existing code such as in val.py. 

The approach typically involves segmenting your large images into smaller, overlapping crops, processing each individually and then reassembling the crops into a full image of predictions. Considerations such as window size and overlap extent would need to be managed correctly.

There's no shortcut around this complexity, but understanding the fundamentals of the sliding window approach could help in your code modification process. 

Remember, the ultimate validation of your model are results on the real-world usage or test data which resemble the scenarios in which the model will be applied. Configuring your validation setup to be as similar as possible to these conditions can be more beneficial for accurate model evaluation.

**Comment by BingoNate** [comment]
@glenn-jocher The modification of validation requires quite a lot of efforts to make the codes correct. Now, I have modified the load_image method to do crop first, however, the labels are not adjustable yet. How I can correctly modify the labels['bboxes'] or labels['segments'] to update the right coordinates corresponding to the cropped image? Now, if we do crop in a method like generate_patches_with_labels, the cropped image is right while the change of labels does not make sense. Where does this modification do can take effects?
