### ISSUE TITLE
Problem loading multiple ONNX models in a single pipeline

### ISSUE THREAD

**Issue by akashlp27** [ultralytics/ultralytics#4670]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection, Export

### Bug

Hi, thanks for the great repo,
The problem or bug which I am facing is, I have 3 v8 ONNX models, I am trying to load them in a single pipeline, 
But from `model.predict(img_src)`, i am getting results as empty list 
![image](https://github.com/ultralytics/ultralytics/assets/52736048/474021c5-e89b-4c8e-9ece-b766c378bb44)

but when ran individual scripts, I am able to get the predictions, also the ONNX model is loading when I call `model.predict()`, instead of `YOLO("model_path", task = "detect")`

Any suggestions here how can I run 3 different v8 ONNX models in a single pipeline?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by sunshine2176** [comment]
Hello @akashlp27 , How to implement loading multiple ONNX models in a single pipeline?
