### ISSUE TITLE
Evaluating YOLOv8 Segmentation models pixel-wise

### ISSUE THREAD

**Issue by SilverStarCoder** [ultralytics/ultralytics#4688]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

After performing validation on my test dataset, I see various files are produced, such as the confusion matrix, `predictions.json` file, and precision, recall and f1 curves. Is there a built-in way to determine the pixel accuracy of the segmentation predictions? I know I can use the predicted bounding boxes to calculate TP, FP and FN metrics with my own script, but was hoping there was an existing tool to determine how closely the predicted mask matches the ground-truth annotation. 

Also, I noticed in the [segmentation val.py script,](https://github.com/ultralytics/ultralytics/blob/263bfd1e93a0ebab898892501bdb3ae36aa4aa0b/ultralytics/models/yolo/segment/val.py#L221) that there is an `eval_json` function. However, it doesn't seem to actually be used anywhere. How do I enable it? Should the docstring for it not be changed, because it says `"""Return COCO-style object detection evaluation metrics."""` instead of  `"""Return COCO-style segmentation evaluation metrics."""`?

**Comment by glenn-jocher** [comment]
@SilverStarCoder hello,

Thank you for your inquiry.

For evaluating segmentation models in YOLOv8, we don't have a built-in feature to determine the pixel accuracy currently. However, we continually work towards incorporating helpful features based on user feedback, and your suggestion is a good one. Meanwhile, you are correct in your understanding of using the predicted bounding boxes and your own script for the evaluation.

As per the `eval_json` function, it's mostly used internally during the validation process to produce evaluation metrics. The method does generally cater to object detection metrics, hence the description. Even though you see it in the segmentation val.py script, it is not directly connected to segmentation evaluation, and changes in the docstring might lead to confusion. Indeed, it could be made clearer, and I appreciate your suggestion.

Thank you for your vigilance, constructive criticism and suggestions. It helps us make the project better for everyone.

Regards,
Glenn Jocher
