### ISSUE TITLE
v8 using previous model's log directory for training results

### ISSUE THREAD

**Issue by 35grain** [ultralytics/ultralytics#469]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Experiencing something odd. I have a Colab notebook where I am comparing the performance of YOLOv5, v7 and v8 and outputting the training results into separate directories by simply changing the working directory before running each model. For YOLOv8, however, changing the working directory seems to not have any affect when writing out the training results and instead places the files into the last run YOLOv7 directory. The pre-trained weights file yolov8n.pt oddly enough is placed correctly into the YOLOv8 directory. Basic example of what I'm doing:

```
...
os.remove("/content/dataset/train/labels.cache") # remove YOLOv5 label cache
os.remove("/content/dataset/valid/labels.cache")

# YOLOv7 tiny
%cd /content/yolov7
!python train.py --workers 8 --device 0 --batch-size 16 --data /content/dataset/data.yaml --img 1280 --cfg /content/yolov7/cfg/training/yolov7-tiny.yaml --weights /content/yolov7/yolov7-tiny.pt --name yolov7-tiny --hyp /content/yolov7/data/hyp.scratch.tiny.yaml --epochs 130 --cache-images

os.remove("/content/dataset/train/labels.cache") # remove YOLOv7 label cache
os.remove("/content/dataset/valid/labels.cache")

os.mkdir('/content/yolov8')

# YOLOv8n
%cd /content/yolov8

!yolo task=detect mode=train model=yolov8n.pt data=/content/dataset/data.yaml epochs=130 name=yolov8n device=0 batch=16 workers=8 imgsz=1280

...
Logging results to /content/yolov7/runs/detect/yolov8n
...
```
Is there some setting I must use? YOLOv7 is handling the directory change from v5 as expected.

**Comment by glenn-jocher** [comment]
@35grain thanks for the bug report!

@AyushExel we need to pop project and run from defaults on training from another custom trained checkpoint.

**Comment by glenn-jocher** [comment]
@AyushExel this is already happening in model.py here no?

```python
    @staticmethod
    def _reset_ckpt_args(args):
        args.pop("project", None)
        args.pop("name", None)
        args.pop("batch", None)
        args.pop("epochs", None)
        args.pop("cache", None)
        args.pop("save_json", None)

        # set device to '' to prevent from auto DDP usage
        args["device"] = ''
```

**Comment by glenn-jocher** [comment]
@35grain in general project=PROJECT name=NAME will overwrite the default runs directory to PROJECT/NAME.  Is this not happening for you?

**Comment by AyushExel** [comment]
> @35grain thanks for the bug report!
> 
> @AyushExel we need to pop project and run from defaults on training from another custom trained checkpoint.

We're already doing that... A reproducible example would be great!

**Comment by 35grain** [comment]
I will try to figure out the exact part of code that is causing this and let you know (going through the whole notebook takes quite long). Quickly ran only v7 and v8 model training blocks on CPU and that behaved as expected, files are placed under working directory.

**Comment by 35grain** [comment]
Alright so my only guess is that this was some Colab weirdness as I didn't change anything and it worked as expected on another run. Go figure. Anyways, great work guys, can't wait for the edgetpu export format to be ready😋
