### ISSUE TITLE
Adding the NMS Plugin to the model

### ISSUE THREAD

**Issue by Egorundel** [ultralytics/ultralytics#4690]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, in my file for exporting the model `export.py` I indicated that the output should have an NMS module. But after viewing the received model on the `netron.app` website, I realized that the NMS module was not there. Why can this be?

- OS: Ubuntu 20.04
- Python: 3.8

**export.py**
![Screenshot from 2023-09-01 12-15-28](https://github.com/ultralytics/ultralytics/assets/65890558/d0a6a2c5-eb11-4cfa-9091-c5a3b1e71a19)

**model in netron.app**
![Screenshot from 2023-09-01 12-15-11](https://github.com/ultralytics/ultralytics/assets/65890558/3f21f873-cf1f-4e16-8466-98f83761ce52)

**Terminal output when exporting a model**
![Screenshot from 2023-09-01 12-14-49](https://github.com/ultralytics/ultralytics/assets/65890558/dfbd5767-abac-4ec7-90fb-8233e343c9b6)

**Comment by Egorundel** [comment]
I read from you that adding an NMS module is available only for export in CoreML format. Is it possible to add, for example, EfficientNMSPlugin to the ONNX model?

**Comment by glenn-jocher** [comment]
@Egorundel yes that right, the `nms` argument only affects CoreML exports currently. Adding this for ONNX would be great!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by m-dawoud** [comment]
Somone do it please 😂

**Comment by Egorundel** [comment]
@m-dawoud I kind of found a solution in the repository at [triple-Mu/YOLOv8-TensorRT](https://github.com/triple-Mu/YOLOv8-TensorRT)

**Comment by glenn-jocher** [comment]
Hi @m-dawoud,

That's great news that you've found a potential solution for your question! I appreciate your active approach in finding solutions and thank you for sharing your findings with the community. However, please note that we cannot fully endorse or take responsibility for recommendations or solutions from outside repositories, as they may have different implementations or optimizations specific to their use-cases.

Nonetheless, we encourage our users to leverage diverse resources available in the open-source community, like the one you mentioned, to aid with unique challenges that might emerge in their projects.

Going forward, if you experience further issues with your YOLOv8 implementation in our repo, feel free to raise them here. The Ultralytics team and our vibrant community are always ready to assist.

Have a good one!

**Comment by Egorundel** [comment]
@glenn-jocher by the way, you can embed the code from this repository into your own, since it really works correctly :)

**Comment by glenn-jocher** [comment]
Hi @Egorundel,

Thank you for the kind suggestion! Collaboration and shared improvements are what make the open-source community so vibrant and successful. We always welcome contributions that can enhance the YOLOv8 project.

However, integrating external code into our repository is subject to a thorough review process. We must ensure that any new code aligns with our standards for quality, maintainability, license compatibility, and user experience. Additionally, any significant changes need to be planned and scheduled appropriately.

If you believe that the integration of the EfficientNMSPlugin or similar improvements would be beneficial to the Ultralytics YOLOv8 repository, the best course of action is to open a new discussion or issue on the repo, outlining the benefits and linking to the external implementation you've found useful. This can initiate an official dialogue about potential integration.

In the case of suggestions for enhancements, we often encourage community members to contribute via pull requests. This not only accelerates the development process but also allows contributors to get rightfully credited for their work.

Again, thanks for your active participation and for thinking of ways to improve YOLOv8. Your input is valued!
