### ISSUE TITLE
agnostic_nms and nms

### ISSUE THREAD

**Issue by Egorundel** [ultralytics/ultralytics#4694]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

What is the difference between agnostic_nms and just nms when training a model?

**Comment by HtwoOtwo** [comment]
https://github.com/ultralytics/ultralytics/blob/2bc6e647c76f28cbd1114e1d5112a4cd1e6d4108/ultralytics/utils/ops.py#L157-L158
The ordinary NMS will act on different classes separately, agnostic_nms will be applied to all classes at once.

**Comment by glenn-jocher** [comment]
@Egorundel the key distinction between `agnostic_nms` and regular `nms` (Non-Maximum Suppression) lies in the way they handle bounding boxes across multiple classes during post-processing.

Regular `nms` operates separately on each class. This means it undergoes the Non-Maximum Suppression operation within each class independently. The aim is to suppress (i.e., remove) bounding boxes considered "non-maximum" or "less important" within their respective classes in favor of ones that the model confidence is maximal.

On the other hand, `agnostic_nms` is class-agnostic. It applies the Non-Maximum Suppression operation across all classes, considering bounding boxes of different classes collectively. This methodology is helpful when the class distinction is not of significant importance in your application or in scenarios where class labels are not mutually exclusive.

The appropriate choice between `agnostic_nms` and regular `nms` will depend on the specifics of your use-case and the nature of your dataset.
