### ISSUE TITLE
YOLOv8 training too slow on apple silicon m1 pro

### ISSUE THREAD

**Issue by MShahnoor** [ultralytics/ultralytics#4695]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I tried training YOLOv8x for detection on 10 images for 5 epochs and it was completed in some reasonable time. Then I switched to the actual task, around 5k images of sports balls, and the first epoch wasn't even completed in 1 hour and 40 minutes.

I'm using the following machine:
M1 Pro 2020, 16GB Ram.

It is normal to be that slow on M1 or I'm doing something wrong, as the process is taking around 70-80% of GPU and 8-15.5 GB of RAM out of 16.

### Environment

Ultralytics YOLOv8.0.168 🚀 Python-3.11.4 torch-2.1.0.dev20230831 MPS (Apple M1)
OS: Ventura 13.5.1
torch and torch vision: Nightly

### Minimal Reproducible Example

!yolo task=detect mode=train model=yolov8x.pt data=/Users/shahnoor/Desktop/shahnoor/Programming/HighLevel/Python/CricketAnalytics/Training_with_COCO_and_Custom_dataset/data.yaml epochs=100 imgsz=640 batch=8 project=/Users/shahnoor/Desktop/shahnoor/Programming/HighLevel/Python/CricketAnalytics/Training_with_COCO_and_Custom_dataset/YOLO name=cricket device=mps 

### Additional

For batch = 16, the temperature of the laptop was high and it was causing Kernal Panics. I reduced it to batch = 8, and now the temperature is normal, and no Kernal Panic.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
In my experiments on M2 `device=mps` results in significant speedup in train epoch time vs CPU. 

I see a slowdown in val epoch time, probably due to the changing shape on rect=True val. I can experiment with setting `rect = device != 'mps'` to see if that improves val speed.


### yolo train data=coco128.yaml epochs=3 device=mps
```bash
Starting training for 3 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        1/3         0G      1.439      4.116       1.28        178        640: 100%|██████████| 8/8 [00:11<00:00,  1.49s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:27<00:00,  6.92s/it]
                   all        128        929      0.657      0.506      0.588      0.439

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        2/3         0G      1.425      3.753      1.266        231        640: 100%|██████████| 8/8 [00:15<00:00,  1.93s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:25<00:00,  6.44s/it]
                   all        128        929      0.654      0.527      0.607      0.449

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        3/3         0G      1.392       3.52      1.269        178        640: 100%|██████████| 8/8 [00:17<00:00,  2.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:24<00:00,  6.22s/it]
                   all        128        929      0.625      0.552      0.608       0.45

3 epochs completed in 0.035 hours.
```

### yolo train data=coco128.yaml epochs=3 device=cpu
```bash
Starting training for 3 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        1/3         0G      1.096      1.365      1.202        201        640: 100%|██████████| 8/8 [00:42<00:00,  5.35s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:16<00:00,  4.20s/it]
                   all        128        929      0.647      0.518      0.594      0.441

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        2/3         0G      1.216      1.443      1.268        136        640: 100%|██████████| 8/8 [00:44<00:00,  5.57s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:20<00:00,  5.10s/it]
                   all        128        929      0.666      0.537      0.617      0.458

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        3/3         0G      1.193      1.342      1.242        206        640: 100%|██████████| 8/8 [00:50<00:00,  6.36s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:19<00:00,  4.91s/it]
                   all        128        929      0.668      0.551      0.626      0.466

3 epochs completed in 0.055 hours.
```

**Comment by MShahnoor** [comment]
I guess for a dataset of 5-10k images and YOLOv8x model the slow speed is expected on Apple Silicon. We're planning to switch to NVIDIA. What GPUs you would suggest for this size of the dataset and YOLOv8x model?

**Comment by glenn-jocher** [comment]
@MShahnoor indeed, for a larger dataset and especially for computationally heavy models like YOLOv8x, Apple Silicon might not provide the desired speed for training. 

Switching to NVIDIA GPUs is an excellent choice. The specific GPU model to choose really depends on a few factors: your budget, computational needs, and how quick you want the training to be. 

For a dataset of 5-10k images and the YOLOv8x model, a mid-range GPU like the NVIDIA RTX 2070 Super or 2080 Super could perform quite well. They have sufficient memory and offer a good balance between cost and performance. 

If your budget allows and you're looking for more power, the NVIDIA RTX 30 series, such as the RTX 3080 or 3090, would offer much higher speeds for your training. 

However, these are just suggestions, and the optimal GPU can vary greatly depending on other factors I mentioned. I recommend comparing the options, considering your specific project requirements and constraints.
