### ISSUE TITLE
Multi GPU training raises error in PyCharm but not in CLI

### ISSUE THREAD

**Issue by AdrianStkr** [ultralytics/ultralytics#4699]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Multi-GPU

### Bug

> Ultralytics` YOLOv8.0.168 🚀 Python-3.11.4 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 2080, 7982MiB) CUDA:1 (NVIDIA GeForce RTX 2080, 7960MiB)
engine/trainer: task=classify, mode=train, model=yolov8n-cls.pt, data=/data/tr3d_species/images, epochs=100, patience=50, batch=2, imgsz=224, save=True, save_period=-1, cache=False, device=[0, 1], workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer=AdamW, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs/classify/train5
train: /data/images/train... found 63744 images in 33 classes ✅ 
val: /data/images/val... found 7084 images in 33 classes ✅ 
test: None...
Overriding model.yaml nc=1000 with nc=33
                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]           
  9                  -1  1    372513  ultralytics.nn.modules.head.Classify         [256, 33]                     
YOLOv8n-cls summary: 99 layers, 1480561 parameters, 1480561 gradients
Transferred 156/158 items from pretrained weights
DDP: debug command/home/anaconda3/envs/yolov8/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port "REMOVED BY AUTHOR" /snap/pycharm-community/344/plugins/python-ce/helpers/pydev/pydevconsole.py
WARNING:_main_:
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 255) local_rank: 0 (pid: 41290) of binary: /home/anaconda3/envs/yolov8/bin/python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/anaconda3/envs/yolov8/lib/python3.11/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/home/anaconda3/envs/yolov8/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
File "/home/anaconda3/envs/yolov8/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/anaconda3/envs/yolov8/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/anaconda3/envs/yolov8/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/yolov8/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/snap/pycharm-community/344/plugins/python-ce/helpers/pydev/pydevconsole.py FAILED
Failures:
[1]:
  time      : 2023-09-01_16:43:41
  host      : "REMOVED BY AUTHOR"
  rank      : 1 (local_rank: 1)
  exitcode  : 255 (pid: 41291)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
Root Cause (first observed failure):
[0]:
  time      : 2023-09-01_16:43:41
  host      : "REMOVED BY AUTHOR"
  rank      : 0 (local_rank: 0)
  exitcode  : 255 (pid: 41290)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/snap/pycharm-community/344/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 7, in <module>
  File "/home/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/engine/model.py", line 341, in train
    self.trainer.train()
  File "/home/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 191, in train
    raise e
  File "/home/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 189, in train
    subprocess.run(cmd, check=True)
  File "/home/anaconda3/envs/yolov8/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/anaconda3/envs/yolov8/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', "REMOVED BY AUTHOR", '/snap/pycharm-community/344/plugins/python-ce/helpers/pydev/pydevconsole.py']' returned non-zero exit status 1.

### Environment

- YOLO 8.0.168  
- Python-3.11.4 
- torch-2.0.1+cu117 
- Ubuntu 18.04

### Additional

Hi, 

I tried to simply train a YOLO classification model on my own data set using the following script inside the PyCharm 2023.2.1 (Community Edition) console:

```python
from ultralytics import YOLO

model = YOLO('yolov8n-cls.pt')

results = model.train(data='/data/tr3d_species/images', epochs=100, batch=2, device=[0,1], optimizer='AdamW')
``` 
This failed producing the above presented error. When I changed "device" to CPU or to a single GPU the training worked. So I thought there must be an CUDA or torch issue going on. However, when I ran the same multi-GPU training command from the CLI it worked as well.

Particularly the following error may indicate that the bug is on rather on the side of PyCharm than on YOLO's:

/snap/pycharm-community/344/plugins/python-ce/helpers/pydev/pydevconsole.py FAILED

However, since I don't have any clue even on where to start looking into it, your help is very much appreciated!

best wishes,
Adrian

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AdrianStkr thanks for the bug report. We run Multi-GPU training as part of our CI and everything works correctly there, though this is for detect tasks only. I'll try to reproduce for classify tasks.

**Comment by glenn-jocher** [comment]
@AdrianStkr this command is working correctly for me in Python in our Docker image, I'm unable to reproduce any DDP Classify training errors.

```python
from ultralytics import YOLO

model = YOLO('yolov8n-cls.pt')

results = model.train(data='imagenet10', epochs=100, batch=2, device=[0,1], optimizer='AdamW')
```


<img width="1459" alt="Screenshot 2023-09-01 at 20 19 49" src="https://github.com/ultralytics/ultralytics/assets/26833433/f1c933da-880b-4781-a4d6-134950281ec6">



We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
