### ISSUE TITLE
ValueError: Cannot load file containing pickled data when allow_pickle=False

### ISSUE THREAD

**Issue by RodolfoFR** [ultralytics/ultralytics#4700]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I'm trying to do a model training, but with 2% process of first epoch appear the following error: 

Traceback (most recent call last):
  File "simple_train.py", line 16, in <module>
    train = model.train(
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/engine/model.py", line 372, in train
    self.trainer.train()
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/engine/trainer.py", line 315, in _do_train
    for i, batch in pbar:
  File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/data/build.py", line 38, in __iter__
    yield next(self.iterator)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1325, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.8/dist-packages/torch/_utils.py", line 644, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/data/base.py", line 240, in __getitem__
    return self.transforms(self.get_image_and_label(index))
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/data/base.py", line 246, in get_image_and_label
    label['img'], label['ori_shape'], label['resized_shape'] = self.load_image(index)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/data/base.py", line 149, in load_image
    im = np.load(fn)
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/npyio.py", line 435, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False

i tried uniinstall package numpy and install numpy=1.22.2 (its specificed in yolov8 requirements), but don't worked

### Environment

-OS: Ubuntu 20.04
- Python 3.8.10

### Minimal Reproducible Example

from ultralytics import YOLO

\# Parameters for train the model
dataset = "/home/rodolfo/desenvolvimento/project_dataset/dataset/data.yaml"
weights = "/home/rodolfo/desenvolvimento/yolov8/train_640large_v2/result/weights/last.pt"
epochs = 1500
batch_size = 16
img_size = 640
device  = 0
result_folder  = "/home/rodolfo/desenvolvimento/yolov8/train_640large_v2"
verbose = True

model = YOLO(weights)
train = model.train(
                          data=dataset,
                          epochs = epochs,
                          batch = batch_size,
                          imgsz = img_size,
                          device = device,
                          project=result_folder,
                          name="result",
                          pretrained = False,
                          optimizer = "SGD",
                          verbose=verbose,
                          resume=True)
                                                                                    
                     

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@RodolfoFR hi I've tried to implement a fix for your issue in PR #4704. Can you install this branch and try to retrain your data to see if this fixes your error? The command to install this branch is:

```
pip install git+https://github.com/ultralytics/ultralytics.git@npsave
```

**Comment by glenn-jocher** [comment]
@RodolfoFR good news 😃! Your original issue may now be fixed ✅ in PR #4704. 

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://bit.ly/yolov5-paperspace-notebook"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by RodolfoFR** [comment]
Glenn, thanks, I used the script to remove numpy files and it worked correctly. the training is normal.

**Comment by glenn-jocher** [comment]
@RodolfoFR i'm glad to hear that the script to remove numpy files solved your issue and that your training is now running smoothly. As you continue your work, please don't hesitate to reach out if you encounter any other concerns or issues. I am always here to help. Happy training with YOLOv8!
