### ISSUE TITLE
Queries upon YOLOv8 Pose Estimation model

### ISSUE THREAD

**Issue by Zy-23** [ultralytics/ultralytics#4707]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I am using YOLOv8's pose estimation model for my project. Currently, I have these few lines of codes:
```
from ultralytics import YOLO

model = YOLO('yolov8m-pose.pt')

result = model.predict('path_to_img', conf=0.85, hide_labels=True, hide_conf=True, boxes=False)
```

I want my output not to show labels, confidence, and the box itself, and display the key points identified by the model. However, when I run `result[0].keypoints`, it displays the list of confidence scores and the x and y-axis of the key points identified, including those below the threshold set. I am wondering if this is the output I am supposed to expect. If not, what could have gone wrong?
```
ultralytics.engine.results.Keypoints object with attributes:

conf: tensor([[9.9134e-01, 9.9065e-01, 9.8936e-01, 9.1377e-01, 9.3336e-01, 9.1841e-01, 8.5177e-01, 2.9545e-02, 1.7638e-02, 3.5555e-02, 2.6750e-02, 4.9789e-03, 4.3263e-03, 2.4630e-03, 2.0777e-03, 4.7868e-04, 4.8645e-04]], device='cuda:0')
data: tensor([[[1.1617e+02, 8.1918e+01, 9.9134e-01],
         [1.3166e+02, 6.8682e+01, 9.9065e-01],
         [1.0202e+02, 6.6058e+01, 9.8936e-01],
         [1.4874e+02, 7.9931e+01, 9.1377e-01],
         [8.0515e+01, 7.4935e+01, 9.3336e-01],
         [1.8293e+02, 1.4593e+02, 9.1841e-01],
         [4.4491e+01, 1.4562e+02, 8.5177e-01],
         [1.9876e+02, 1.6900e+02, 2.9545e-02],
         [2.3752e+01, 1.6900e+02, 1.7638e-02],
         [1.6865e+02, 1.6598e+02, 3.5555e-02],
         [4.6437e+01, 1.5851e+02, 2.6750e-02],
         [1.6632e+02, 1.5554e+02, 4.9789e-03],
         [8.6781e+01, 1.5636e+02, 4.3263e-03],
         [1.6891e+02, 1.6373e+02, 2.4630e-03],
         [8.0948e+01, 1.5892e+02, 2.0777e-03],
         [7.9373e+01, 1.6900e+02, 4.7868e-04],
         [1.2519e+02, 1.6900e+02, 4.8645e-04]]], device='cuda:0')
has_visible: True
orig_shape: (169, 215)
shape: torch.Size([1, 17, 3])
xy: tensor([[[116.1662,  81.9182],
         [131.6587,  68.6825],
         [102.0206,  66.0585],
         [148.7446,  79.9315],
         [ 80.5152,  74.9345],
         [182.9317, 145.9327],
         [ 44.4912, 145.6199],
         [198.7622, 169.0000],
         [ 23.7523, 169.0000],
         [168.6533, 165.9827],
         [ 46.4367, 158.5088],
         [166.3174, 155.5356],
         [ 86.7807, 156.3622],
         [168.9113, 163.7303],
         [ 80.9481, 158.9202],
         [ 79.3725, 169.0000],
         [125.1898, 169.0000]]], device='cuda:0')
xyn: tensor([[[0.5403, 0.4847],
         [0.6124, 0.4064],
         [0.4745, 0.3909],
         [0.6918, 0.4730],
         [0.3745, 0.4434],
         [0.8508, 0.8635],
         [0.2069, 0.8617],
         [0.9245, 1.0000],
         [0.1105, 1.0000],
         [0.7844, 0.9821],
         [0.2160, 0.9379],
         [0.7736, 0.9203],
         [0.4036, 0.9252],
         [0.7856, 0.9688],
         [0.3765, 0.9404],
         [0.3692, 1.0000],
         [0.5823, 1.0000]]], device='cuda:0')
```

Furthermore, when I plot the output, I find out that the box, label, and confidence level are still shown in the plot.
```
for r in result:
    im_array = r.plot()
    im = Image.fromarray(im_array[..., ::-1])
    im.show()
```
![image](https://github.com/ultralytics/ultralytics/assets/83623077/5d7a2129-36c3-4d30-8770-89c0d7b15258)

I am wondering why is it so when I have set hide_conf, hide_labels to True, and boxes to False.

**Comment by RizwanMunawar** [comment]
@Zy-23! You can display the keypoints only with a few modifications in predict arguments. you can use a mentioned line of codes to achieve this. Unfortunately, the confidence and bounding box coordinates can not be removed, they can only be hidden because these are directly associated with model predictions.

```
from ultralytics import YOLO

model = YOLO('yolov8m-pose.pt')

result = model.predict('path_to_img', conf=0.85, hide_labels=True, hide_conf=True, show=True, boxes=False, save=True)
```

**Comment by glenn-jocher** [comment]
Hello @Zy-23,

The list of confidence scores and the x, y coordinates of the keypoints identified is indeed the expected output when you call `result[0].keypoints`. The `conf` attribute represents the confidence score of each identified keypoint while the `data` attribute gives you the keypoints' coordinates along with their corresponding confidence scores.

Regarding hiding the box, label, and confidence level in the plot, it's important to clarify that the `hide_labels` and `hide_conf` options, in your call to `model.predict()`, only affect the text displayed on the predictions (i.e., class-labels and confidence scores). These do not impact the bounding boxes around the objects.

In your case, the bounding boxes are still seen because the `boxes` boolean in the predict method does not control the visibility of the boxes in the plot, but rather it's for whether to include bounding boxes in the predictions or not.

If you want not to display the boxes as well, you would need to modify the plot method of the Results object. Currently, out-of-the-box, the visualization methods in the Ultralytics framework display bounding boxes for object localization along with their corresponding keypoints. You can edit the plotting utilities to meet your specific visualization requirements.

I hope this clears up your query, let me know if you have any more issues or questions.

**Comment by Zy-23** [comment]
Hi @glenn-jocher, thanks for your clarification. To add to my query, may I know the sequence of the coordinates returned in the result as I could not find it in the documentation? For example, the first set of coordinates and confidence score refers to left eyes, the second set refers to right eyes, etc.

**Comment by glenn-jocher** [comment]
@RizwanMunawar hello, 

Thank you for your query. The sequence of the coordinates in the result follows a certain order consistent with the COCO dataset's keypoint annotations. Specifically, for a pose estimation task, the keypoints detected are typically sorted as follows:

1. Nose 
2. Left Eye
3. Right Eye
4. Left Ear
5. Right Ear
6. Left Shoulder
7. Right Shoulder
8. Left Elbow
9. Right Elbow
10. Left Wrist
11. Right Wrist
12. Left Hip
13. Right Hip
14. Left Knee
15. Right Knee
16. Left Ankle
17. Right Ankle

Note that the order may change depending on how you've labeled your dataset or if there are missing keypoints. Always cross-reference with your dataset labeling to accurately interpret the keypoints.

If there are specific details about this order that are not clear or if you're facing any other issues with YOLOv8, please feel free to ask. We're here to help.

**Comment by glenn-jocher** [comment]
@kavya-seeramsetty hello! 🌟

It's great to hear that you're exploring integrating YOLOv8 with 3D coordinate detection for your robotic project. Indeed, MediaPipe offers an efficient path for 3D object localization, but it's more tailored to predefined object categories.

To integrate YOLOv8's versatile detection capabilities with 3D coordinate extraction, one approach could be to use YOLOv8 for object detection and then apply MediaPipe on the detected object regions for 3D coordinate estimation. Here's a pseudo-code idea:

```python
# Use YOLOv8 to detect objects
objects = yolov8.detect(image)

# For each detected object...
for obj in objects:
    # Crop the object region from the image
    object_region = crop(image, obj.bbox)

    # Apply MediaPipe on the cropped region for 3D estimation
    three_d_coordinates = mediapipe_estimation(object_region)
```

This way, you leverage YOLOv8's broad detection capabilities and MediaPipe's efficient 3D estimation within the same pipeline.

For non-stereovision 3D coordinate estimation, looking into depth cameras like Intel RealSense might also be worth exploring. They come with SDKs that simplify depth data acquisition and can potentially work alongside the detection framework you choose.

Hope this helps! Keep innovating! 💡✨

**Comment by kavya-seeramsetty** [comment]
> @kavya-seeramsetty hello! 🌟
> 
> It's great to hear that you're exploring integrating YOLOv8 with 3D coordinate detection for your robotic project. Indeed, MediaPipe offers an efficient path for 3D object localization, but it's more tailored to predefined object categories.
> 
> To integrate YOLOv8's versatile detection capabilities with 3D coordinate extraction, one approach could be to use YOLOv8 for object detection and then apply MediaPipe on the detected object regions for 3D coordinate estimation. Here's a pseudo-code idea:
> 
> ```python
> # Use YOLOv8 to detect objects
> objects = yolov8.detect(image)
> 
> # For each detected object...
> for obj in objects:
>     # Crop the object region from the image
>     object_region = crop(image, obj.bbox)
> 
>     # Apply MediaPipe on the cropped region for 3D estimation
>     three_d_coordinates = mediapipe_estimation(object_region)
> ```
> 
> This way, you leverage YOLOv8's broad detection capabilities and MediaPipe's efficient 3D estimation within the same pipeline.
> 
> For non-stereovision 3D coordinate estimation, looking into depth cameras like Intel RealSense might also be worth exploring. They come with SDKs that simplify depth data acquisition and can potentially work alongside the detection framework you choose.
> 
> Hope this helps! Keep innovating! 💡✨

Hey @glenn-jocher 
Thanks much!

**Comment by kavya-seeramsetty** [comment]
> Hey @kavya-seeramsetty! 🚀
> 
> Thrilled to see your enthusiasm! Absolutely, blending YOLOv8 with MediaPipe for 3D detection in robotics sounds like a cutting-edge venture. The provided strategy should serve as a solid starting point for experimenting with 2D detections from YOLOv8 and enhancing them to 3D with MediaPipe. 🌐✨
> 
> And yes, exploring depth cameras such as Intel RealSense could also enrich your project by directly offering 3D data, complementing your YOLOv8 and MediaPipe integration beautifully.
> 
> Happy coding, and can't wait to see where your project goes! If you hit any bumps or have further queries, we're here to help. 🛠️💡

Thanks @glenn-jocher for your sincere help : )

**Comment by glenn-jocher** [comment]
You're most welcome, @kavya-seeramsetty! 😄

It sounds like you're onto something really exciting! If there’s anything you need or more questions pop up along the way, feel free to drop a message. Excited to see how your project develops! 🌟 Happy coding!
