### ISSUE TITLE
Yolov8 export error

### ISSUE THREAD

**Issue by farah-rostom98** [ultralytics/ultralytics#4709]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

yolov8 export int8 is not working and returns a onnx model with weights type float32

### Minimal Reproducible Example

main_model = YOLO('best.pt')

main_model.export(format='onnx',int8=True)

or
!yolo export model='/content/gdrive/MyDrive/Brightskies/epoch59.pt' opset=12 format=onnx imgsz=480,640 int8

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@farah-rostom98 `int8` argument is not supported for ONNX exports. You can see ONNX export supported arguments in our docs at https://docs.ultralytics.com/modes/export/#export-formats

<img width="1495" alt="Screenshot 2023-09-03 at 17 47 07" src="https://github.com/ultralytics/ultralytics/assets/26833433/5c7261f6-bd6f-44e2-87d5-75fee9da3175">
