### ISSUE TITLE
Filter prediction by class using CLI

### ISSUE THREAD

**Issue by rusvagzur** [ultralytics/ultralytics#471]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi there Ultralytics,

Is it somehow possible to filter the predictions by class using CLI? For example, I only want to predict the class car from a video.

Many thanks

**Comment by glenn-jocher** [comment]
@rusvagzur no, not out of the box, you'd have to filter inference results after inference runs.

**Comment by rusvagzur** [comment]
@GianniGi exactly, that's what I meant

**Comment by prince0310** [comment]
@GianniGi Cheak out the recent modification for filtering the class [filter](https://github.com/Kamlesh364/ultralytics)
