### ISSUE TITLE
How to prevent YOLOv8 from applying augmentations from commandline?

### ISSUE THREAD

**Issue by AsafKov** [ultralytics/ultralytics#4710]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello. I've been trying to train a YOLOv8 model and noticed it applies augmentation automatically. 
I'm using the command:
`yolo train --resume model=yolov8n.pt imgsz=480 data=data.yaml epochs=20 cache=True workers=2`
Adding an argument `--augment=False` does not seem to work, as the output of the training still indicates it is applying augmentations:

![image](https://github.com/ultralytics/ultralytics/assets/35013356/d689f01f-5e54-42f9-b9a1-eccdee97dbda)

From what I've seen there should be some file that I can edit that will prevent this but I have no idea where to find it (I didn't clone the repo, only installed ultralytics through pip).

**Comment by glenn-jocher** [comment]
@AsafKov hello and thank you for your question. To control the augmentations in your YOLOv8 model training,  it's necessary to modify the data YAML configuration file that you are using. 

The data YAML file usually contains the path to the train and validation datasets along with the list of classes, but it can also contain specifications for augmentations. If you'd like to turn off the augmentations, you can set the 'augment' field to False in your data YAML file. Once you make this change, the YOLOv8 training will not apply augmentations, regardless of the command line arguments.

To make these changes, you don't need to clone the repository, you just need to locate and edit your data YAML file. If you have installed Ultraytics through pip, your data YAML file should be in the same directory where you run your command line instructions.

I hope this helps! Please let us know if you have more questions.

**Comment by glenn-jocher** [comment]
@AsafKov also just run `pip uninstall albumentations`

**Comment by cmilanes93** [comment]
Can i use this method to select the specific augmentations that im interest in.
How would it be?

**Comment by glenn-jocher** [comment]
@cmilanes93 hello, thanks for your question!

Yes, absolutely. In YOLOv8, you can select specific augmentations by editing the YAML data configuration file used for training. In the YAML file, there is an 'augment' field where you can specify the types of augmentations you're interested in. 

You will need to enter the names of the specific augmentations you'd like to use. Please ensure that the names match exactly with those specified in the YOLOv8 documentation or source code. If you wish to use multiple types of augmentations, you can list them all in the 'augment' field.

Once you've made these changes to your YAML file, YOLOv8 will only apply the augmentations you've specified during training. 

Remember, the augmentations you include in your dataset can greatly impact model performance so try a couple of different combinations to see what works best for your data and task.

Let us know if you need any more help!

**Comment by cmilanes93** [comment]
im having this on my config.yaml file:
path: C:\Users\cmilanes\Desktop\RAS3_Project_Leader\Deep Learning\YOLO1\data
train: train
val: train

# Classes
names:
  0: 0
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5
  6: 6
  7: 7
  8: 8
  9: 9

# Augmentation settings
augment:
  hsv_h: 0.05
  hsv_s: 0.2
  hsv_v: 0.2
  degrees: 0.0
  translate: 0.1
  scale: 0.2
  shear: 0.1
  perspective: 0.0001
  flipud: 0.0
  fliplr: 0.0
  mosaic: 0.0
  mixup: 0.0
  copy_paste: 0.0
  
  But the data keep assuming the default configuration of the parameters

**Comment by glenn-jocher** [comment]
@cmilanes93 hello, thank you for your question. You've made a good start by defining your augmentations in the YAML data configuration file. However, the augmentations you defined are not recognized because YOLOv8 does not natively support per-dataset or per-user customization of augmentations through the YAML file. As a result, it reverts to its default setting.

Currently, to change augmentation parameters, you need to modify them directly in the code base where the augmentations are applied. These changes would typically be applied in the dataset or transforms file/script. 

Keep in mind that while changing these augmentation settings, the model behavior may significantly vary, so interpret the results accordingly and experiment to find the right balance for your specific project.

**Comment by tadyvn** [comment]
hi @glenn-jocher, I want to turn off augmentation for my classification task. this is my training log:
```
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8m-cls.pt to 'yolov8m-cls.pt'...
100%|██████████| 32.7M/32.7M [00:00<00:00, 70.9MB/s]
Ultralytics YOLOv8.0.175 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (NVIDIA A100-SXM4-40GB, 40514MiB)
engine/trainer: task=classify, mode=train, model=yolov8m-cls.pt, data=/content/16_mix5type_task3_min_area_split/, epochs=150, patience=50, batch=16, imgsz=1024, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs/classify/train
train: /content/16_mix5type_task3_min_area_split/train... found 14303 images in 2 classes ✅ 
val: /content/16_mix5type_task3_min_area_split/val... found 804 images in 2 classes ✅ 
test: /content/16_mix5type_task3_min_area_split/test... found 1123 images in 2 classes ✅ 
Overriding model.yaml nc=1000 with nc=2

                   from  n    params  module                                       arguments                     
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]                 
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]                
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]             
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]               
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]           
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]              
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]           
  7                  -1  1   2655744  ultralytics.nn.modules.conv.Conv             [384, 768, 3, 2]              
  8                  -1  2   7084032  ultralytics.nn.modules.block.C2f             [768, 768, 2, True]           
  9                  -1  1    988162  ultralytics.nn.modules.head.Classify         [768, 2]                      
YOLOv8m-cls summary: 141 layers, 15774898 parameters, 15774898 gradients
Transferred 228/230 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs/classify/train', view at http://localhost:6006/
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to 'yolov8n.pt'...
100%|██████████| 6.23M/6.23M [00:00<00:00, 106MB/s]
AMP: checks passed ✅
train: Scanning /content/16_mix5type_task3_min_area_split/train... 14303 images, 0 corrupt: 100%|██████████| 14303/14303 [00:05<00:00, 2809.85it/s]
train: New cache created: /content/16_mix5type_task3_min_area_split/train.cache
albumentations: RandomResizedCrop(p=1.0, height=1024, width=1024, scale=(0.5, 1.0), ratio=(0.75, 1.3333333333333333), interpolation=1), HorizontalFlip(p=0.5), ColorJitter(p=0.5, brightness=[0.6, 1.4], contrast=[0.6, 1.4], saturation=[0.30000000000000004, 1.7], hue=[-0.015, 0.015]), Normalize(p=1.0, mean=(0.0, 0.0, 0.0), std=(1.0, 1.0, 1.0), max_pixel_value=255.0), ToTensorV2(always_apply=True, p=1.0, transpose_mask=False)
val: Scanning /content/16_mix5type_task3_min_area_split/val... 804 images, 0 corrupt: 100%|██████████| 804/804 [00:00<00:00, 2441.02it/s]
val: New cache created: /content/16_mix5type_task3_min_area_split/val.cache
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 38 weight(decay=0.0), 39 weight(decay=0.0005), 39 bias(decay=0.0)
Image sizes 1024 train, 1024 val
Using 8 dataloader workers
Logging results to runs/classify/train
Starting training for 150 epochs...
```

As the log, `augment = False` but when I see result training, I still see augmentated image in "/content/runs/classify/train/train_batch0.jpg". 
I tried set `augment = False` in my python and in .yaml file.

**Comment by cmilanes93** [comment]
It is better if you fix the parameters of the augmentation to “0” in your Python file…

**Comment by glenn-jocher** [comment]
@tadyvn hi, thank you for reaching out!

Given your scenario, the best approach would be to explicitly set all the applicable augmentation parameters to "0" in your Python script. The `augment` parameter in YOLOv8 controls whether augmentations are used or not, but some functions might still consider default values if certain parameters aren't set to "0". 

Therefore, if you want to completely turn off data augmentation, it's safer to go into your Python script and manually set all relevant augmentation parameters to "0". This should ensure that no augmentations will be applied during training.

Let me know if this helps or if you need further assistance. Thank you.

**Comment by balintfazekas** [comment]
Hi!

I could not modify augmentation options throughout .yaml file, however all the augmentation modification will take effect after you specified them in CLI.

Hope this help.

**Comment by glenn-jocher** [comment]
@balintfazekas hello,

Thank you for reaching out. You're correct that the augmentation settings currently cannot be modified directly in the YAML configuration file. This file primarily helps in defining the structure of the model and dataset.

To modify the augmentation parameters, you need to alter these settings directly in the command line interface (CLI) or directly in the code where the augmentations are applied. Once these changes are made in the CLI or in the respective function in the code, they should take effect.

Remember that depending on your specific task and experimentation requirements, carefully choose and balance the augmentation techniques. Happy experimenting with your model training!

Let us know if you need any more help. Your success is important to us!

**Comment by omrir** [comment]
@glenn-jocher, can you give an example or refer to how to change augmentation directly in the CLI?
Also, where can i find the augmentation parameters i can change?

Thanks!

**Comment by glenn-jocher** [comment]
@omrir hello, thank you for reaching out with your questions!

To modify augmentation parameters directly via the command line interface (CLI), you can include them as arguments when you start your training command. For example, if you are adjusting the `hsv_h` parameter, you would include something like `--hsv_h 0.5` at the end of your training command. Of course, replace '0.5' with your desired value.

You can apply similar changes for other augmentation parameters by replacing `hsv_h` with the name of the parameter you want to adjust. Also, remember that the changes made via CLI will override the values present in your script or configuration file for that run of the algorithm.

As for where you can find the augmentation parameters you can change, they are generally located within the code files responsible for handling data loading and preprocessing, often they would be in scripts like 'datasets.py' or 'transforms.py'. This is where you would find parameters such as hue, saturation, exposure, rotation, shift, scale etc. Please explore the codebase for the exact file and parameter names.

I hope that helps! Let us know if you need any further assistance.

**Comment by fyang5** [comment]
Hi, 
How could I only turn off the data augmentation for val.py and use it for testing? In Yolov5, it is easy to turn off the data augmentation in for val.py and use it for testing, which will get same results as using detect.py, but with more quatitative results such as confusion metrics, mAPs, etc. Thanks!

**Comment by glenn-jocher** [comment]
@fyang5 hi there,

In YOLOv8, similar to YOLOv5, data augmentation settings are typically turned off by default during the validation and testing phases to ensure a more accurate assessment of the model's performance on untouched data. 

When you run the validation or testing procedures, YOLOv8 should perform these steps without applying any of the training-time augmentations. The training-time augmentations are intended to make the model more robust and prevent overfitting, but for evaluation (such as validation/testing), you would want to see how the model handles the original, unaltered data. 

For additional commands and operations specific to YOLOv8 that might be slightly different from YOLOv5, you can refer to our official documentation, which details the proper usage and functions available for different tasks and modes, including validation and testing.

If there's any discrepancy or if you require augmentations to be explicitly disabled, you may look into the validation script or validation configuration in the code to ensure no unwanted augmentations are being applied. 

For quantitative results like confusion matrices and mAP scores, using the `val` mode is indeed the correct approach.

Should you have further questions or need more detailed support, please don't hesitate to ask. Happy to assist you in your YOLOv8 journey!

Best regards.

**Comment by fyang5** [comment]
Hi Glenn-Jocher @glenn-jocher ,

Thanks for your reply!

I got different results using detect and val with the same conf threshold and iou threshold (based on 5433 images for one class detection). Here is the details:
1. Using detect.py: **yolo detect predict model=./ultralytics/runs/detect/train5/weights/best.pt source=./datasets/splitteddata/images/test/positive/**/*jpg device=0 save_txt=True imgsz=640 save_conf=True save=True max_det=300 iou=0.45 conf=0.1
2. Using val.py:  yolo detect val model=./ultralytics/runs/detect/train5/weights/best.pt data=./ultralytics/cfg/datasets/mydataset.yaml split=test imgsz=640 batch=16 save_hybrid=True conf=0.1 iou=0.45 max_det=300 device=0.  
in mydataset.yaml file, the test part is as below: "...
test: ./datasets/splitteddata/images/test/positive "
However, with the first command, 4145 labels of 5433 images were detected objects, a precision of 1 and a recall of 1 were obtained, along with mAP@50% is 0.995. Also, in the confusion matrix it showed that a total of 5433+720 images were used (See the image attached).  

![image](https://github.com/ultralytics/ultralytics/assets/85182870/f010fb0e-bf92-48c3-82c3-4c75852b413d).

Thanks!

**Comment by glenn-jocher** [comment]
@fyang5 Hello,

First off, I would like to address your concern about the different results between `detect` and `val` modes. It is indeed expected to have equivalent behavior regarding the detection functionality of the model when using the same configuration parameters (e.g., confidence and IoU thresholds). However, there could be a few reasons why discrepancies occur:

1. **Dataset Composition**: Ensure that the exact same images are being evaluated in both `detect` and `val`. Any difference in the test sets could produce varying results.
2. **Data Loading**: The way images are loaded and preprocessed might differ slightly between `detect` and `val` modes. This could affect the input to the model and, subsequently, the performance metrics.
3. **Model State**: Confirm that both commands are indeed loading the same model with the same weights and that the model is in evaluation mode during both tests to disable any training-specific behaviors, like dropout.
4. **Output Processing**: Check if there is any post-processing (such as non-maximum suppression) being applied differently between the two modes.

The discrepancy in the number of images processed, as reflected in the confusion matrix (i.e., 5433 vs. 5433+720), indicates that there might be a misconfiguration in the dataset file, or during validation, additional images are being included that are not part of the test set.

It's worth carefully reviewing your dataset configuration and the commands you used for consistency. For more detailed assistance, you may want to provide this feedback as an issue on our GitHub repository.

Regarding the perfect precision and recall values you're getting in `val`, if these metrics don't align with what you observe with `detect`, this could be a sign of an issue with the validation process or data configuration. It's incredibly rare to obtain a perfect score on a realistic dataset without some form of data or metric inconsistency.

Lastly, while the community may provide valuable insights, thorough debugging often requires a closer look at the source code and configurations. Our comprehensive documentation can serve as a guide, and if you continue to encounter issues, please don't hesitate to file an issue with all the relevant specifics in our repository.

I hope this helps to clarify the steps you need to take. Please reach out if you have more queries or need further guidance.

**Comment by fyang5** [comment]
Thanks, Glenn-Jocher, for your reply.

I think there is a bug for the val.py for detect mode. Since the confusion matrix is with 5433+720 images while in command window it was shown only 5433 images. I checked the val.py but didn't find where the issue was . I just open a bug issue file.

**Comment by glenn-jocher** [comment]
@fyang5 Hello,

Thank you for the update, and I appreciate your diligence in identifying a potential issue with the YOLOv8 model. Creating a bug issue in the GitHub repository is indeed the right course of action. The team will review the details of your issue and consider it with the highest priority.

In the interim, it’s beneficial to ensure that:

1. Your dataset is properly structured, and the dataset configuration reflects the actual contents and layout of the test set.
2. No additional images from outside the specified test set are being inadvertently pulled into the validation process due to configuration errors or file path issues.

When reporting a bug, it's helpful to provide as much information as possible, including steps to reproduce the issue, expected vs. actual behavior, and any relevant output or error messages. This can significantly aid in the debugging process and lead to a more timely resolution.

If there's any additional information you can provide or any other way the community or I can assist you further, please let us know.

Thank you for your contribution and patience as we work to address this matter. Your feedback is invaluable in improving YOLOv8 for everyone.

Best regards.

**Comment by MoAbbasid** [comment]
I have the same question and uninstall albumentation doesnt work, none of these gpt answers work, did anyone find out how to turn off augmentation during training?

**Comment by glenn-jocher** [comment]
@MoAbbasid hello! Sorry to hear you're facing issues turning off augmentations during training. 😕 While disabling albumentations directly might not work, you could try setting augmentation parameters to minimal values directly in your dataset's YAML file or when executing your training command. For example:

```yaml
hsv_h: 0.0  # hue
hsv_s: 0.0  # saturation
hsv_v: 0.0  # value
degrees: 0.0  # rotation
translate: 0.0  # translate
scale: 0.0  # scale
shear: 0.0  # shear
perspective: 0.0  # perspective
flipud: 0.0  # flip up-down
fliplr: 0.0  # flip left-right
mosaic: 0.0  # mosaic
mixup: 0.0  # mixup
```

Or, use `--noaugment` in your training command if supported by your version of YOLOv8. If issues persist, opening an issue in the repo with specific details could help find a targeted solution! 🛠️

Hope this helps!

**Comment by Y-T-G** [comment]
Change this to false

https://github.com/ultralytics/ultralytics/blob/911a0edd2d1b47c28e1eef657859dbb9bcffb13f/ultralytics/data/build.py#L93

**Comment by glenn-jocher** [comment]
@Y-T-G hey there! 👋 Looks like you're pointing out the line that enables augmentations by default. If you're aiming to disable augmentations during training, simply update that line in your local clone of the repository to `False`:

```python
hsv_h, hsv_s, hsv_v, degrees, translate, scale, shear, perspective, flipud, fliplr, mosaic, mixup = (
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, False, False)
```

This sets all augmentation parameters to minimal impact, effectively disabling them. Let me know if there's anything else you need help with! Happy coding! 😄

**Comment by bavo96** [comment]
Can we have a single parameter to turn off all augmentations at once? @glenn-jocher it would be nice because if there's any new augmentation we can't control it and have to recheck the code/configuration. If we want to use augmentation, we'll activate it by ourselves.

**Comment by BangSiliconprime** [comment]
Many thanks for your help ^^

**Comment by bavo96** [comment]
Many thanks for your help ^^

**Comment by glenn-jocher** [comment]
You're welcome! 😊 If there's anything else you need, feel free to ask. Happy coding!

**Comment by FlySka** [comment]
Hi @glenn-jocher 

where can I get the default settings of the augmentations that yolov8 training has?

(these same parameters, but with the default values)

```
hsv_h: 0.0  # hue
hsv_s: 0.0  # saturation
hsv_v: 0.0  # value
degrees: 0.0  # rotation
translate: 0.0  # translate
scale: 0.0  # scale
shear: 0.0  # shear
perspective: 0.0  # perspective
flipud: 0.0  # flip up-down
fliplr: 0.0  # flip left-right
mosaic: False  # mosaic
mixup: False  # mixup
```

**Comment by glenn-jocher** [comment]
Hi @FlySka,

You can find the default augmentation settings for YOLOv8 in the `default.yaml` configuration file within the Ultralytics repository. This file contains all the default parameters used during training, including augmentation settings. If you have any further questions or need additional assistance, feel free to ask.

**Comment by didik12ax** [comment]
Hi @glenn-jocher , I would like to recall it again regarding the augmentation. If we apply the augmentation like this setting 
augment:
hsv_h: 0.05
hsv_s: 0.2
hsv_v: 0.2
degrees: 0.0
translate: 0.1
scale: 0.2
shear: 0.1
perspective: 0.0001
flipud: 0.0
fliplr: 0.0
mosaic: 0.0
mixup: 0.0
copy_paste: 0.0

will the system do 7 augmentations on each image? so if we have 400 images, we could have 2800 image for the total?
is it ok to train like that? that will it be an over-augmentation?

**Comment by glenn-jocher** [comment]
Hi, applying these settings will apply each augmentation to every image, but it doesn't multiply the dataset size. Instead, each image is augmented once per epoch, maintaining the original dataset size of 400 images. This approach is generally fine and helps improve model robustness without over-augmenting.

**Comment by viren-joshi** [comment]
Does setting `auto_augment` parameter to `None` in `model.train()` turn the augmentations performed by YOLO off? 

>  [Setting to None disables automated augmentation.](https://docs.ultralytics.com/guides/yolo-data-augmentation/#copy-paste-mode-copy_paste_mode)

The wording in the documentation confused me, automated augmentation is same ones performed by YOLO inherently right?

**Comment by glenn-jocher** [comment]
No—`auto_augment=None` only disables the classification auto policies (RandAugment/AutoAugment/AugMix); detection/segmentation augments are controlled by their own args and must be set to 0/False to disable, for example:

```python
from ultralytics import YOLO
model = YOLO("yolov8n.pt")
model.train(
    data="data.yaml",
    epochs=100,
    hsv_h=0.0, hsv_s=0.0, hsv_v=0.0,
    degrees=0.0, translate=0.0, scale=0.0, shear=0.0, perspective=0.0,
    flipud=0.0, fliplr=0.0,
    mosaic=0.0, mixup=0.0, cutmix=0.0, copy_paste=0.0, close_mosaic=0
)
```

See the classification-only note for `auto_augment` in the [Data augmentation guide](https://docs.ultralytics.com/guides/yolo-data-augmentation/) and the full list of train-time augmentation knobs in the [Train mode reference](https://docs.ultralytics.com/modes/train/).
