### ISSUE TITLE
How is  'target_cls' calculated?

### ISSUE THREAD

**Issue by andresinsitu** [ultralytics/ultralytics#4722]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi!
I am implementing a custom library for calculating metrics in YOLO format based on ultralytics library. I am stuck at calculating ` target_cls (np.ndarray): Array of true classes of the detections`.  And I found that it comes from ` cls = batch['cls'][idx]` https://github.com/ultralytics/ultralytics/blob/aa9133bb886e2e4d7aa04461178290c8090477f6/ultralytics/models/yolo/detect/val.py#L94C13-L94C36 . However I cant find how batch['cls'] is calculated, any help?

**Comment by andresinsitu** [comment]
After looking the function https://github.com/ultralytics/ultralytics/blob/d2cf7acce0dde0a5aece4b4e50132c40a09acd23/ultralytics/utils/metrics.py#L408 closely, I think the argument ` target_cls (np.ndarray): Array of true classes of the detections` is just the array of the classes of the ground of truth labels and it is used only to count the number of labels per class, so that implies that the docstring documentation is not correct, as the array is not of the detections and even it doesnt need to be in any specific order. 

Is this right?

**Comment by glenn-jocher** [comment]
@andresinsitu hi there,

You're absolutely right. `target_cls` is indeed an array of the classes of the ground truth labels, not the detections as the docstring may have suggested. This array is indeed used to calculate the number of samples per class in the ground truth set.

The order of the elements in `target_cls` does not impact the computation, as the function is interested in the overall counts per class, not the order in which they appear.

Thank you for pointing out the ambiguity in the documentation, we appreciate your diligence and feedback. We will update it to better reflect the function's use.

To other users who might be reading this, always remember to diligently read and understand the function's purpose, especially in the field of machine learning where every detail can significantly impact your results.

Best regards,
Glenn Jocher, Ultralytics.
