### ISSUE TITLE
Pandas FutureWarnings in training

### ISSUE THREAD

**Issue by Burhan-Q** [ultralytics/ultralytics#4729]
This is more informational than a true "issue" as everything appears to be working.

I installed Ultralytics 8.0.170  in a new `venv` and at the start of training, received numerous `FutureWarnings` when `trainer` started plotting labels. Screenshot shows sample of output (continues for several more lines).

![Screenshot from 2023-09-04 17-14-33_051458.png](https://github.com/ultralytics/ultralytics/assets/62214284/4cf47b9d-2324-4579-88f4-aba3f148a82d)

## The features being warned about are:

- `pd.api.types.is_categorical_dtype`
- `pd.option_context('mode.use_inf_as_na')`

both appear to be from the `seaborn` library.

## Possible fixes
- [ ] suppress warnings when plotting with `seaborn`
- [ ] use new version of `seaborn` that replaced these (if exists)
- [ ] use a different library for plotting

**Comment by glenn-jocher** [comment]
@Burhan-Q yo thanks for the info! I saw this also recently on a CI test. By default the pip install will use the latest version of every package, so this just seems to be a seaborn issue in their usage.

I'm assuming they'll fix this but I'll raise an issue on their repo and disable these warnings so users don't get spooked. As you said warnings are more informational than anything but a lot of newcomers get worried when seeing this.

**Comment by glenn-jocher** [comment]
@Burhan-Q great news 😃! Your original issue may now be resolved ✅ in PR #4748. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by glenn-jocher** [comment]
@Burhan-Q seaborn team has released a new version v0.13.0 that resolves this per https://github.com/mwaskom/seaborn/issues/3462#issuecomment-1742056756
