### ISSUE TITLE
IndexError: boolean index did not match indexed array along dimension 0; dimension is 32 but corresponding boolean dimension is 29

### ISSUE THREAD

**Issue by SkalskiP** [ultralytics/ultralytics#473]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I run `!yolo task=segment mode=train model=yolov8s-seg.pt data={dataset.location}/data.yaml epochs=10 imgsz=640` in Google Colab, and I see errors like this:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/sentry_sdk/integrations/threading.py", line 69, in run
    reraise(*_capture_exception())
  File "/usr/local/lib/python3.8/dist-packages/sentry_sdk/_compat.py", line 59, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 262, in plot_images
    image_masks = masks[idx]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 32 but corresponding boolean dimension is 29
```

### Environment

Google Colab

### Minimal Reproducible Example

Here is our Google Colab, where we experience that problem: https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/train-yolov8-instance-segmentation-on-custom-dataset.ipynb#scrollTo=D2YkphuiaE7_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@SkalskiP thanks I'll take a look. This one might be a bit hard to debug. Could this be one of those mixed boxes - segments datasets you guys were talking about? Right now we can only accept all boxes or all segments.

**Comment by SkalskiP** [comment]
@glenn-jocher that dataset is bure segmentation dataset

**Comment by SkalskiP** [comment]
Hi @glenn-jocher and @AyushExel here is fully reproducible example of that issue: https://colab.research.google.com/drive/1VyZulDnFdyZmz613v-nVc8gYuNCToz7s?usp=share_link
