### ISSUE TITLE
YOLOv8-ONNXRuntime-CPP visualization error ,bbox can not draw on the target, when inputsize=1280*1280

### ISSUE THREAD

**Issue by xmzhuxm** [ultralytics/ultralytics#4734]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

visualization error ,bbox can not draw on the target,visualization error ,bbox can not draw on the target

### Environment

YOLOv8-ONNXRuntime-CPP
os: windows
device:cpu

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by xmzhuxm** [comment]
when inputsize is 640, visualization normal, when inputsize=1280, bbox can not draw on the target

**Comment by glenn-jocher** [comment]
@xmzhuxm thanks for bringing this issue to our attention. The problem of not being able to draw bounding boxes on the target with an input size of 1280 seems to be related to the scaling of coordinates. 

When you increase the input size, the coordinates of your bounding box predictions are normalised to that input size. It sounds like the code that's supposed to rescale these coordinates back to the original image size for visualization might not be doing that correctly.

I suggest checking the function responsible for drawing the bounding boxes. Make sure it is rescaling the bounding box coordinates correctly according to the input size. Also, verify that your bounding box coordinates are not exceeding the image bounds when the input size is 1280.

Please let us know if this helps, or if you have more information to share!

**Comment by xmzhuxm** [comment]
﻿﻿﻿﻿﻿﻿yes, it works，thank you!在 2023年9月5日，19:44，Glenn Jocher ***@***.***> 写道：﻿
@xmzhuxm thanks for bringing this issue to our attention. The problem of not being able to draw bounding boxes on the target with an input size of 1280 seems to be related to the scaling of coordinates.
When you increase the input size, the coordinates of your bounding box predictions are normalised to that input size. It sounds like the code that's supposed to rescale these coordinates back to the original image size for visualization might not be doing that correctly.
I suggest checking the function responsible for drawing the bounding boxes. Make sure it is rescaling the bounding box coordinates correctly according to the input size. Also, verify that your bounding box coordinates are not exceeding the image bounds when the input size is 1280.
Please let us know if this helps, or if you have more information to share!

**Comment by glenn-jocher** [comment]
I'm glad to hear the solution worked for you, @xmzhuxm! That's excellent news. Your question was very helpful in our quest to continuously improve YOLOv8. If you have any other comments, questions, or run into more issues, please don't hesitate to open another issue. We always learn from your valuable input. Happy coding and best of luck with your work on YOLOv8!
