### ISSUE TITLE
infinite stop when using torchrun

### ISSUE THREAD

**Issue by sung0471** [ultralytics/ultralytics#4741]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

when I use torchrun for training in multigpu, It was stuck

library :
  - torch==2.0.0, cuda==11.8 (GPU=4090)
  - wandb==0.15.9
  - ultralytics==8.0.124

python : 
```python
from ultralytics import YOLO
from ultralytics.yolo.utils import DEFAULT_CFG  # ultralytics==8.0.124
# from ultralytics.utils import DEFAULT_CFG
# from wandb.integration.yolov8 import add_callbacks as add_wandb_callbacks
from args.arguments import parse_args
from args.utils import filter_args

cfg = vars(DEFAULT_CFG)
cfg_keys = cfg.keys()
YOLOv8_MODEL_ARGS = list(cfg_keys)


def train(args):
    # model = YOLO(args.model_cfg)
    model = YOLO(args.weight)
    # add_wandb_callbacks(model, project=args.project, run_name=args.name)

    m_args = filter_args(args, YOLOv8_MODEL_ARGS)
    print(m_args)
    model.train(**m_args)


if __name__ == '__main__':
    args = parse_args(phase='train')
    print(args)
    train(args)
```
command : 
```shell
  torchrun --nproc_per_node 2 --master_port 9527 train.py --batch_size 128 --optimizer Adam --data data/custom_data_seg.yaml --project Project_name --img 640 --device 2,3 --epoch 50 --lr0 1.2683988509209527e-04 --lrf 9.77966113159812e-3 2>&1 | sudo tee train.log
```
shell output : 
```shell
New https://pypi.org/project/ultralytics/8.0.170 available 😃 Update with 'pip install -U ultralytics'
Overriding model.yaml nc=80 with nc=11
Transferred 411/417 items from pretrained weights
DDP info: RANK 0, WORLD_SIZE 2, DEVICE cuda:0
wandb: Currently logged in as: sung16biz. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.15.9
wandb: Run data is saved locally in /usr/src/yolov8-seg-custom/wandb/run-20230905_054756-02q4o2i5
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run v8_aihub_Adam_lr1.268e-4_lrf9.780e-3
wandb: ⭐️ View project at https://wandb.ai/sung16biz/FEDM-Segment
wandb: 🚀 View run at https://wandb.ai/sung16biz/FEDM-Segment/runs/02q4o2i5
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
```

after AMP: checks, I had waited 1 hour.
If you have some ideas, I would appreciate your help.

### Additional

reason for using ultralytics==8.0.124 : 
Because it is not compatible with wandb, from wandb.integration.yolov8 import add_callbacks does not work.

**Comment by glenn-jocher** [comment]
Hello @sung0471,

It's good to hear from you and thank you for trying out the recommended solutions. I understand that you're unfortunately still experiencing an issue.

Concerning your upgrades, I noticed there might be a misunderstanding regarding PyTorch. As of now, PyTorch version 1.10.0 is the latest release - there appears to be a typo. To make sure you're using the latest stable version, I recommend installing it via `pip install torch==1.10.0`.

Regarding the hanging problem at AMP check, it might be related to the PyTorch DataLoader or the num_workers. In some instances, increasing num_workers doesn't resolve the issue, and in rare conditions, it's better to set num_workers = 0 if you're facing multi-threading issues.

You might also want to investigate where exactly the script hangs. One technique to do this is to add print statements before and after the AMP check so you can break down if it's within the AMP check or right after it. Finding where exactly the script is getting stuck can help highlight what might be causing this.

Lastly, it will be helpful to raise this issue in the PyTorch or CUDA forums, as this might be a PyTorch or a CUDA-specific multi-processing issue that is not directly related to YOLOv8.

**Comment by sung0471** [comment]
Hello @glenn-jocher !

It's been a long time since I wrote.
We confirmed that this issue continues to occur even in the latest version, and we also found a way to work around the bug.

### 1. Cause of bug occurrence
  - Occurs when learning using multi-GPU (torchrun ~)

### 2. How to avoid bugs
  - This can be avoided by assigning a non-adjacent graphics card number.

2.1 Error case
  - device = 0, 1
  - device = 1, 2
  - device = 2, 3

2.2 Cases that work correctly
  - device = 0, 2
  - device = 1, 3

I tried everything you suggested for a long time while doing other things, but unfortunately it didn't work. (update ultralytics version, change version of torch, change num_workers, )

Using the above method, we were able to learn the model by avoiding the bug. Of course, this problem may only occur in my case, but if not, I share the thought that it may occur when using the torchrun command in ultralytics.

Thank you

**Comment by glenn-jocher** [comment]
Hello @sung0471,

Thank you for the update and for sharing your findings! It's quite intriguing that specifying non-adjacent GPU device numbers resolves the issue. This could be indicative of an underlying system-specific peculiarity, possibly related to how resources are allocated across GPUs.

Your discovery is valuable and could indeed be helpful to others experiencing similar issues. We'll keep an eye out for any related patterns that emerge with `torchrun` usage in YOLOv8.

In the meantime, if you come across any more insights or if there's anything else we can assist you with, please don't hesitate to reach out. Happy modeling! 🚀
