### ISSUE TITLE
how to reduce line_width and label font size?

### ISSUE THREAD

**Issue by geoxpert0001** [ultralytics/ultralytics#4743]
![image](https://github.com/ultralytics/ultralytics/assets/141697815/0514c514-a122-429e-a09e-99bdbfca77ba)
this is a track code result, but its font size and line width are so large.
how to reduce size?

this is my code
```
from collections import defaultdict
import cv2
import numpy as np
from ultralytics import YOLO


model = YOLO('best.pt')


video_path = "DJI_0082.mp4"
cap = cv2.VideoCapture(video_path)


output_video_name = "output_tracking.mp4"
frame_width = int(cap.get(3))
frame_height = int(cap.get(4))
fps = int(cap.get(5))
fourcc = cv2.VideoWriter_fourcc(*'mp4v')  
output_video = cv2.VideoWriter(output_video_name, fourcc, fps, (frame_width, frame_height))


roi_top_left = (400, 500)
roi_bottom_right = (900, 850)


roi2_top_left = (1000, 450)
roi2_bottom_right = (1800, 750)


track_history = defaultdict(lambda: [])


track_history_roi2 = defaultdict(lambda: [])


detected_ids = set()


detected_ids_roi2 = set()


target_count = 0


target_count_roi2 = 0

while cap.isOpened():
    success, frame = cap.read()

    if success:

        roi = frame[roi_top_left[1]:roi_bottom_right[1], roi_top_left[0]:roi_bottom_right[0]]


        roi2 = frame[roi2_top_left[1]:roi2_bottom_right[1], roi2_top_left[0]:roi2_bottom_right[0]]


        results = model.track(frame, persist=True, conf=0.3, iou=0.5, tracker="bytetrack.yaml", imgsz=1280, device=0)


        boxes = results[0].boxes.xywh.cpu()
        track_ids = results[0].boxes.id.int().cpu().tolist()


        annotated_frame = results[0].plot()


        for box, track_id in zip(boxes, track_ids):
            x, y, w, h = box


            if roi_top_left[0] <= x <= roi_bottom_right[0] and roi_top_left[1] <= y <= roi_bottom_right[1]:

                detected_ids.add(track_id)

                target_count = len(detected_ids)


            if roi2_top_left[0] <= x <= roi2_bottom_right[0] and roi2_top_left[1] <= y <= roi2_bottom_right[1]:

                detected_ids_roi2.add(track_id)

                target_count_roi2 = len(detected_ids_roi2)


            track = track_history[track_id]
            track.append((float(x), float(y)))  
            if len(track) > 30: 
                track.pop(0)


            points = np.hstack(track).astype(np.int32).reshape((-1, 1, 2))
            cv2.polylines(annotated_frame, [points], isClosed=False, color=(230, 230, 230), thickness=10)


        cv2.rectangle(annotated_frame, roi_top_left, roi_bottom_right, (0, 255, 0), 2)


        cv2.rectangle(annotated_frame, roi2_top_left, roi2_bottom_right, (0, 0, 255), 2)


        cv2.putText(annotated_frame, f'ROI 1: {target_count}', (10, 40),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
        cv2.putText(annotated_frame, f'ROI 2: {target_count_roi2}', (10, 80),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)


        output_video.write(annotated_frame)

        cv2.imshow("YOLOv8", annotated_frame) # when built cog, needed to disable this line 

        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        break


output_video.release()

cap.release()
cv2.destroyAllWindows()
```

**Comment by RizwanMunawar** [comment]
@geoxpert0001! You can comment ```annotated_frame = results[0].plot()``` and replace your for loop with the mentioned code, which can help you to adjust the detections bounding box size etc.

```
for box, track_id in zip(boxes, track_ids):
    x, y, w, h = box
    
    #...Modification...
    x1, y1,x2, y2 = x-w/2, y-h/2, x+w/2, y+h/2
    cv2.rectangle(frame, (int(x1),int(y1)),(int(x2),int(y2)), (0, 0, 255), 1)
    t_size = cv2.getTextSize(str(track_id), 0, fontScale=1 / 1, thickness=1)[0]
    cv2.rectangle(frame, (int(x1), int(y1) - t_size[1] - 3),(int(x1) + t_size[0], int(y1)+3),  (0,255,0),-1)
    cv2.putText(frame, str(track_id), (int(x1), int(y1) - 2), 0, 1 / 1,[0,0,0], thickness=2, lineType=cv2.LINE_AA)
    #.................


    if roi_top_left[0] <= x <= roi_bottom_right[0] and roi_top_left[1] <= y <= roi_bottom_right[1]:

        detected_ids.add(track_id)

        target_count = len(detected_ids)


    if roi2_top_left[0] <= x <= roi2_bottom_right[0] and roi2_top_left[1] <= y <= roi2_bottom_right[1]:

        detected_ids_roi2.add(track_id)

        target_count_roi2 = len(detected_ids_roi2)


    track = track_history[track_id]
    track.append((float(x), float(y)))  
    if len(track) > 30: 
        track.pop(0)


    points = np.hstack(track).astype(np.int32).reshape((-1, 1, 2))
    cv2.polylines(frame, [points], isClosed=False, color=(230, 230, 230), thickness=10)
```

### **Expected Output**

![Bounding boxes plot](https://github.com/ultralytics/ultralytics/assets/62513924/6be28c14-9274-40f3-853c-2034fc24f964)

**Comment by geoxpert0001** [comment]
@RizwanMunawar 
I hope that each class has its own color, and I also need the class name and confidence to be displayed.

**Comment by geoxpert0001** [comment]
Yolov5 has these "--line_thickness --hide-labels -hide-conf" arguments, but it seems that Yolov8 does not have these arguments.

**Comment by RizwanMunawar** [comment]
@geoxpert0001! You can embed the mentioned code to show confidence, class name, and tracking ID. Every class color you can change according to your needs.

```
boxes = results[0].boxes.xywh.cpu()
track_ids = results[0].boxes.id.int().cpu().tolist()
confs = results[0].boxes.conf.float().cpu().tolist()
clss = results[0].boxes.cls.cpu().tolist()
namess = results[0].names

for box, track_id,conf,cls in zip(boxes, track_ids,confs,clss):
    x, y, w, h = box
    
    #...Modification...
    x1, y1,x2, y2 = x-w/2, y-h/2, x+w/2, y+h/2
    cv2.rectangle(frame, (int(x1),int(y1)),(int(x2),int(y2)), (0, 0, 255), 1)
    label = namess[cls]+" " +str(track_id)+" "+str(format(conf,'.2f'))
    t_size = cv2.getTextSize(label, 0, fontScale=3 / 3, thickness=1)[0]
    cv2.rectangle(frame, (int(x1), int(y1) - t_size[1] - 3),(int(x1) + t_size[0], int(y1)+3),  (0,255,0),-1)
    cv2.putText(frame, label, (int(x1), int(y1) - 2), 0, 3 / 3,[0,0,0], thickness=2, lineType=cv2.LINE_AA)
    
Same code ......
```

**Comment by geoxpert0001** [comment]
may i ask if i have 5 classes, so i need these 5 classes which have each color.

**Comment by RizwanMunawar** [comment]
You can use the mentioned code to change the color of classes.

```
boxes = results[0].boxes.xywh.cpu()
track_ids = results[0].boxes.id.int().cpu().tolist()
confs = results[0].boxes.conf.float().cpu().tolist()
clss = results[0].boxes.cls.cpu().tolist()
namess = results[0].names

for box, track_id,conf,cls in zip(boxes, track_ids,confs,clss):
    x, y, w, h = box
    
    #...Modification...
    x1, y1,x2, y2 = x-w/2, y-h/2, x+w/2, y+h/2

    if int(cls)==0: #class 1 
        cv2.rectangle(frame, (int(x1),int(y1)),(int(x2),int(y2)), (0, 255, 0), 1)
    if int(cls)==1: #class 2 
        cv2.rectangle(frame, (int(x1),int(y1)),(int(x2),int(y2)), (0, 0, 255), 1)
    if int(cls)==2: #class 3 
        cv2.rectangle(frame, (int(x1),int(y1)),(int(x2),int(y2)), (255,0,255), 1)
    if int(cls)==3: #class 4 
        cv2.rectangle(frame, (int(x1),int(y1)),(int(x2),int(y2)), (0, 110, 255), 1)
    if int(cls)==4: #class 5 
        cv2.rectangle(frame, (int(x1),int(y1)),(int(x2),int(y2)), (0, 20, 255), 1)
        
    label = namess[cls]+" " +str(track_id)+" "+str(format(conf,'.2f'))
    t_size = cv2.getTextSize(label, 0, fontScale=3 / 3, thickness=1)[0]
    cv2.rectangle(frame, (int(x1), int(y1) - t_size[1] - 3),(int(x1) + t_size[0], int(y1)+3),  (0,255,0),-1)
    cv2.putText(frame, label, (int(x1), int(y1) - 2), 0, 3 / 3,[0,0,0], thickness=2, lineType=cv2.LINE_AA)
    
Same code ......
```

**Comment by glenn-jocher** [comment]
@RizwanMunawar, definitely! YOLOv8 has the flexibility to customize the bounding box color for each class. 

For this, you need to incorporate a conditional statement that will check the class ID and choose the color accordingly. You have five classes, so you'll have five conditions in your code determining the bounding box color for each class uniquely. 

Example: 
- If your class ID is 1, you might select the color green (0, 255, 0) for the bounding boxes.
- If the class ID is 2, you can choose to draw your bounding boxes in red (0, 0, 255).
- Accordingly for classes 3, 4, and 5, you can set different colors.

This allows each class to be visually distinguishable, making it easier to interpret your results visually. Please make sure to alter your code accordingly and it should handle your requirements perfectly. 

Remember, the color is defined by the BGR code (Blue, Green, Red), and these numbers are from 0 to 255. You can also search for BGR color picker in your internet browser to find more colors.

**Comment by geoxpert0001** [comment]
@glenn-jocher 
So, is there no other easy way to add line width and font size functionality? Just like this:
result = model.track(frame, line-width=2 ,font-size=1 ,persist=True, conf=0.3, iou=0.5, tracker="bytetrack.yaml", imgsz=1280, device=0) ?

**Comment by glenn-jocher** [comment]
@geoxpert0001 hello, currently YOLOv8 does not directly support the addition of line width or font size as explicit parameters in the tracking function. In order to adjust these details, modifications can be made within the method of the corresponding class involved with the bounding box and text drawing.

For line width, it's associated with the function/method that draws the bounding boxes. As for font size, it's related to the method that handles drawing the text over the bounding boxes.

While we understand your requirement for an easier way to modify the line width and font size directy through the track function, please know that such functionality isn't currently supported in this version of YOLOv8.

Your suggestion is valuable and we will definitely consider it for future improvements of the model to further enhance the user-friendliness of the model's parameters. Thank you for bringing this to our attention!

**Comment by stphtan94117** [comment]
> 您可以使用上述代碼更改類的顏色。
> 
> ```
> boxes = results[0].boxes.xywh.cpu()
> track_ids = results[0].boxes.id.int().cpu().tolist()
> confs = results[0].boxes.conf.float().cpu().tolist()
> clss = results[0].boxes.cls.cpu().tolist()
> namess = results[0].names
> 
> for box, track_id,conf,cls in zip(boxes, track_ids,confs,clss):
>     x, y, w, h = box
>     
>     #...Modification...
>     x1, y1,x2, y2 = x-w/2, y-h/2, x+w/2, y+h/2
> 
>     if int(cls)==0: #class 1 
>         cv2.rectangle(frame, (int(x1),int(y1)),(int(x2),int(y2)), (0, 255, 0), 1)
>     if int(cls)==1: #class 2 
>         cv2.rectangle(frame, (int(x1),int(y1)),(int(x2),int(y2)), (0, 0, 255), 1)
>     if int(cls)==2: #class 3 
>         cv2.rectangle(frame, (int(x1),int(y1)),(int(x2),int(y2)), (255,0,255), 1)
>     if int(cls)==3: #class 4 
>         cv2.rectangle(frame, (int(x1),int(y1)),(int(x2),int(y2)), (0, 110, 255), 1)
>     if int(cls)==4: #class 5 
>         cv2.rectangle(frame, (int(x1),int(y1)),(int(x2),int(y2)), (0, 20, 255), 1)
>         
>     label = namess[cls]+" " +str(track_id)+" "+str(format(conf,'.2f'))
>     t_size = cv2.getTextSize(label, 0, fontScale=3 / 3, thickness=1)[0]
>     cv2.rectangle(frame, (int(x1), int(y1) - t_size[1] - 3),(int(x1) + t_size[0], int(y1)+3),  (0,255,0),-1)
>     cv2.putText(frame, label, (int(x1), int(y1) - 2), 0, 3 / 3,[0,0,0], thickness=2, lineType=cv2.LINE_AA)
>     
> Same code ......
> ```

i change fontScale=1, and it looks also so large for font. I want the font displayed to be very very small.

**Comment by geoxpert0001** [comment]
> You can use the mentioned code to change the color of classes.
> 
> ```
> boxes = results[0].boxes.xywh.cpu()
> track_ids = results[0].boxes.id.int().cpu().tolist()
> confs = results[0].boxes.conf.float().cpu().tolist()
> clss = results[0].boxes.cls.cpu().tolist()
> namess = results[0].names
> 
> for box, track_id,conf,cls in zip(boxes, track_ids,confs,clss):
>     x, y, w, h = box
>     
>     #...Modification...
>     x1, y1,x2, y2 = x-w/2, y-h/2, x+w/2, y+h/2
> 
>     if int(cls)==0: #class 1 
>         cv2.rectangle(frame, (int(x1),int(y1)),(int(x2),int(y2)), (0, 255, 0), 1)
>     if int(cls)==1: #class 2 
>         cv2.rectangle(frame, (int(x1),int(y1)),(int(x2),int(y2)), (0, 0, 255), 1)
>     if int(cls)==2: #class 3 
>         cv2.rectangle(frame, (int(x1),int(y1)),(int(x2),int(y2)), (255,0,255), 1)
>     if int(cls)==3: #class 4 
>         cv2.rectangle(frame, (int(x1),int(y1)),(int(x2),int(y2)), (0, 110, 255), 1)
>     if int(cls)==4: #class 5 
>         cv2.rectangle(frame, (int(x1),int(y1)),(int(x2),int(y2)), (0, 20, 255), 1)
>         
>     label = namess[cls]+" " +str(track_id)+" "+str(format(conf,'.2f'))
>     t_size = cv2.getTextSize(label, 0, fontScale=3 / 3, thickness=1)[0]
>     cv2.rectangle(frame, (int(x1), int(y1) - t_size[1] - 3),(int(x1) + t_size[0], int(y1)+3),  (0,255,0),-1)
>     cv2.putText(frame, label, (int(x1), int(y1) - 2), 0, 3 / 3,[0,0,0], thickness=2, lineType=cv2.LINE_AA)
>     
> Same code ......
> ```

I want the font displayed to be very very small

**Comment by glenn-jocher** [comment]
@stphtan94117 in OpenCV, the font size in the putText function corresponds to the 'fontScale' parameter. The 'fontScale' parameter is not in point size, unlike in certain desktop publishing programs, but rather it's a factor by which the font is scaled. So 'fontScale' = 1 means that the font is of original size defined by underlying graphics implementation.

If the font scale of 1 is still too big for your needs, you can lower it to decimals such as 0.5, 0.2 or even smaller until you find the size that suits your needs best. 

Please note changes in 'thickness' parameter might also affect the appearance of the font size. If the thickness setting is too high, even a small font could appear large. Thus, you may want to adjust that parameter as well.

**Comment by geoxpert0001** [comment]
@RizwanMunawar last question
if i use yolov8s-seg.pt to detect object, how to show the mask color (segment polygon color)?
thanks

**Comment by glenn-jocher** [comment]
@geoxpert0001, sure! To display the mask color or segmentation polygon color in YOLOv8, you'll need to access the mask information in the detection results. This information is part of the model's output and it encodes the shape of the detected object in the image. 

To visualize it, you'd typically create a color overlay that follows the mask's shape and then superimpose this overlay on your original image. The color of the overlay can be customized as per your liking. It's important to ensure that the overlay is semi-transparent so that the original image is still visible beneath it. 

The color is defined by the BGR code (Blue, Green, Red), the numbers are from 0 to 255. You can also search for BGR color picker in your internet browser to find more colors. 

While creating the overlay, you may want to consider the pixel intensity values. If you want a solid color overlay regardless of the pixel intensity, simply assign the desired BGR color code to all pixels corresponding to the mask. If you want to retain the original gradients, the pixel intensity value could be used to modulate the intensity of your chosen overlay color.

I hope this helps! Please feel free to ask if you have further questions.

**Comment by geoxpert0001** [comment]
> @geoxpert0001, 當然! 要在YOLOv8中顯示掩碼顏色或分段多邊形顏色,您需要在檢測結果中訪問掩碼信息。該信息是模型輸出的一部分,它編碼圖像中檢測到的對象的形狀。
> 
> 要可視化它,通常將創建跟隨蒙版形狀的顏色覆蓋,然後將其疊加在原始圖像上。覆蓋物的顏色可以根據您的喜好進行自定義。確保覆蓋物是半透明的,以使原始圖像在其下方仍然可見,這一點很重要。
> 
> 顏色由BGR代碼(藍色,綠色,紅色)定義,數字從0到255。您還可以在Internet瀏覽器中搜索BGR顏色選擇器以查找更多顏色。
> 
> 創建覆蓋時,您可能要考慮像素強度值。如果要使用純色覆蓋而不管像素強度如何,只需將所需的BGR顏色代碼分配給與蒙版相對應的所有像素。如果要保留原始漸變,則可以使用像素強度值來調製所選疊加顏色的強度。
> 
> 希望這有幫助! 請隨時詢問您是否還有其他問題。

i didnot know how to display.
can you provide a sample code to display  mask color.

**Comment by glenn-jocher** [comment]
@geoxpert0001, to display mask colors in YOLOv8, you'll need to first access the mask outputs from the model's predictions. These are included as part of the prediction details for each detected object.

Next, use these masks to create a color overlay. Masks are binary, meaning they can be used to select the pixels in the image that correspond to the detected object. For each object, create a color overlay on the original image where the overlay color is applied only to the pixels selected by the mask.

Please note, the transparency of the overlay will determine how much of the original image shows through beneath the color. You can set this to your liking, but typically, a certain level of transparency is used so that the original details of the image are still visible.

The exact color used for the overlay can also be set to your preference. You can use different colors for different classes, or even for different objects. Just remember that colors will be defined in BGR format.

Finally, to display the image with the overlay, you can use OpenCV's imshow function. This function displays an image in a window and should properly show your colored overlays.

I hope this helps! Please don't hesitate to reach out if you have additional questions.

**Comment by geoxpert0001** [comment]
can you add code to display?

**Comment by glenn-jocher** [comment]
@geoxpert0001, apologies for any confusion, but at the moment, we aren't providing specific code implementations as responses on this repository. However, I can definitely point you in the right direction.

You would require the mask outputs from your model's predictions, which would be used to create a colored overlay on your original image. 

The mask output is essentially a binary output that highlights the pixels corresponding to the detected object. You need to use this mask to select the corresponding pixels in the image and color them accordingly.

Finally, you can utilize functions such as imshow from the OpenCV library in Python to display the final image with the colored overlay.

I hope that helps! If you have further questions or need more clarification, feel free to ask!
