### ISSUE TITLE
how to use "P2, P3, P4' layer only?

### ISSUE THREAD

**Issue by GiUKim** [ultralytics/ultralytics#4746]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hi i'm using yolov8 far well. i want to make model config .yaml file composed 3 detect layer P2, P3, P4. 
the "yolov8-p2.yaml" seem to have 4 layer P2 P3 P4 P5. (x-small, small, middle, large). 
if i want to use only "P2 P3 P4" (x-small, small, middle) layer, how to modify .yaml file?

**Comment by glenn-jocher** [comment]
@GiUKim hello,

Thank you for using YOLOv8. To adapt the model configuration laid out in the 'yolov8-p2.yaml' file for three detection layers (P2, P3, P4), you need to adjust the architecture in the .yaml file.

The architecture in the configuration file is defined by an array of layer names (e.g., [P2, P3, P4, P5]). The model dimensions reduce as you progress through the layers, matching with the variations x-small, small, middle, and large.

To limit the layers to just P2, P3, and P4, you should modify this array of layers in the .yaml file to just include these three. Essentially, you'll remove the P5 (large) layer from your configuration.

Remember, this will change the model's architecture significantly and may impact the model's performance. Each layer is responsible for detecting objects at different scales, so removing a layer will affect how well the model can detect objects at the corresponding scale.

Let me know if you have any further questions. Your contributions help make our YOLOv8 project better. 

Best, 
Glenn.
