### ISSUE TITLE
Torchscript export with dynamic shape

### ISSUE THREAD

**Issue by pfeatherstone** [ultralytics/ultralytics#4747]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Running `net.export(format='torchscript')` does not allow dynamic shape. It would be nice if it did. I don't see any reason for it not to.

### Use case

I would like to use a TorchScript model with dynamic shape.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
@pfeatherstone! Can you share the command you have used to export the model to Torchscript?

**Comment by RizwanMunawar** [comment]
I encountered no issues while exporting, and I have used the mentioned code to export the PyTorch model to TorchScript.

```
from ultralytics import YOLO
net = YOLO('yolov8n-pose.pt')
net.export(format='torchscript',dynamic=True)
```

### **Result**
![TorchScript Export](https://github.com/ultralytics/ultralytics/assets/62513924/cf0cd0de-f010-4fc3-8056-a558f1ada1ad)

**Comment by pfeatherstone** [comment]
Ah, i didn't use `dynamic=True`

**Comment by pfeatherstone** [comment]
It's worth saying that `torchvision.ops.batched_nms()` can be used in ONNX export! Not CoreML though.

**Comment by pfeatherstone** [comment]
So i'm wrapping the YOLO model in another `nn.Module`, adding NMS and exporting to ONNX. works a treat.

**Comment by pfeatherstone** [comment]
The following can be exported to both TorchScript and ONNX:
```
class Yolov8(nn.Module):
    def __init__(self, jit_path):
        super().__init__()
        self.net = torch.jit.load(jit_path)
        self.conf_thresh = 0.3
        self.nms_thresh  = 0.7
        self.do_nms      = True
    
    def forward(self, x):
        dets        = self.net(x).transpose(1,2)
        idxs        = torch.where(dets[...,4] > self.conf_thresh)
        dets        = dets[idxs]
        x,y,w,h     = dets[...,:4].chunk(4, -1)
        dets[:,:4]  = torch.cat([x-w/2,y-h/2,x+w/2,y+h/2],-1)

        if not self.do_nms:
            return idxs[0], dets
    
        return self.nms(idxs[0], dets, self.nms_thresh)
        
    @torch.no_grad()
    def nms(self, indices, dets, nms_thresh):
        nms     = torchvision.ops.batched_nms(dets[:,:4], dets[:,4], indices, nms_thresh)
        indices = indices[nms]
        dets    = dets[nms]
        return indices, dets 
```

**Comment by pfeatherstone** [comment]
Anyway, I'll close the issue. Thank you for quick response!

**Comment by glenn-jocher** [comment]
@RizwanMunawar you're welcome! I'm glad I could assist. Please don't hesitate to reach out if you encounter any other issues or have any more questions regarding YOLOv8. Thanks for engaging with the Ultralytics community. Happy coding!
