### ISSUE TITLE
Max Resolution for YOLOv8n/YOLOv8s on Google Coral EdgeTPU

### ISSUE THREAD

**Issue by malleyconnor** [ultralytics/ultralytics#4754]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have had success in the past exporting int8 quantized 15-class YOLOv5s models to the Google Coral EdgeTPU at resolutions up to 320x320. However, I cannot export even YOLOv8n at that same resolution, even though it has less parameters than YOLOv5s (the export will finish successfully, but many of the operations must be completed on the CPU which is will prevent the model from running in real-time on an edge device). In fact, I have to export YOLOv8n at significantly lower resolution (e.g. 224x224). I attached some example output from running the YOLOv5 and YOLOv8 export scripts below:

**YOLOv5s int8 edgetpu export (320x320)**

Export command: 
`python3 export.py --weights best.pt --imgsz 320 320 --int8 --include edgetpu`

Output: 
```
Edge TPU Compiler version 16.0.384591198
Searching for valid delegate with step 10
Try to compile segment with 262 ops
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 7220 ms.

Input model: best-int8.tflite
Input size: 7.06MiB
Output model: best-int8_edgetpu.tflite
Output size: 7.27MiB
On-chip memory used for caching model parameters: 6.85MiB
On-chip memory remaining for caching model parameters: 164.00KiB
Off-chip memory used for streaming uncached model parameters: 24.75KiB
Number of Edge TPU subgraphs: 1
Total number of operations: 262
Operation log: best-int8_edgetpu.log

Operator                       Count      Status

CONCATENATION                  17         Mapped to Edge TPU
PAD                            7          Mapped to Edge TPU
RESHAPE                        6          Mapped to Edge TPU
ADD                            10         Mapped to Edge TPU
STRIDED_SLICE                  9          Mapped to Edge TPU
MAX_POOL_2D                    3          Mapped to Edge TPU
LOGISTIC                       66         Mapped to Edge TPU
QUANTIZE                       7          Mapped to Edge TPU
MUL                            75         Mapped to Edge TPU
CONV_2D                        60         Mapped to Edge TPU
RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
Compilation child process completed within timeout period.
Compilation succeeded! 
```

**YOLOv8n int8 edgetpu export (320x320)**

Export command: 
`yolo export model=best.pt format=edgetpu imgsz=320,320 int8=True`

Output:
```
Edge TPU Compiler version 16.0.384591198
Searching for valid delegate with step 10
Try to compile segment with 257 ops
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 1917 ms.

Input model: best_saved_model/best_full_integer_quant.tflite
Input size: 2.96MiB
Output model: best_saved_model/best_full_integer_quant_edgetpu.tflite
Output size: 3.31MiB
On-chip memory used for caching model parameters: 3.06MiB
On-chip memory remaining for caching model parameters: 4.47MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 257
Operation log: best_saved_model/best_full_integer_quant_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 233
Number of operations that will run on CPU: 24

Operator                       Count      Status

SOFTMAX                        1          More than one subgraph is not supported
CONV_2D                        63         Mapped to Edge TPU
CONV_2D                        1          More than one subgraph is not supported
LOGISTIC                       1          More than one subgraph is not supported
LOGISTIC                       57         Mapped to Edge TPU
RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
RESHAPE                        3          More than one subgraph is not supported
RESHAPE                        2          Mapped to Edge TPU
CONCATENATION                  3          More than one subgraph is not supported
CONCATENATION                  16         Mapped to Edge TPU
MAX_POOL_2D                    3          Mapped to Edge TPU
QUANTIZE                       1          More than one subgraph is not supported
QUANTIZE                       2          Mapped to Edge TPU
PAD                            7          Mapped to Edge TPU
TRANSPOSE                      2          Mapped to Edge TPU
TRANSPOSE                      3          Operation is otherwise supported, but not mapped due to some unspecified limitation
SUB                            2          More than one subgraph is not supported
ADD                            6          Mapped to Edge TPU
ADD                            2          More than one subgraph is not supported
STRIDED_SLICE                  16         Mapped to Edge TPU
STRIDED_SLICE                  4          More than one subgraph is not supported
MUL                            57         Mapped to Edge TPU
MUL                            3          More than one subgraph is not supported
Compilation child process completed within timeout period.
Compilation succeeded! 
============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

```

**YOLOv8n int8 edgetpu export (224x224)**

Export command: 
`yolo export model=best.pt format=edgetpu imgsz=224,224 int8=True`

Output:
```
Edge TPU Compiler version 16.0.384591198
Searching for valid delegate with step 10
Try to compile segment with 257 ops
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 2229 ms.

Input model: best_saved_model/best_full_integer_quant.tflite
Input size: 2.96MiB
Output model: best_saved_model/best_full_integer_quant_edgetpu.tflite
Output size: 6.24MiB
On-chip memory used for caching model parameters: 5.81MiB
On-chip memory remaining for caching model parameters: 1.28MiB
Off-chip memory used for streaming uncached model parameters: 18.19KiB
Number of Edge TPU subgraphs: 1
Total number of operations: 257
Operation log: best_saved_model/best_full_integer_quant_edgetpu.log

Operator                       Count      Status

MUL                            60         Mapped to Edge TPU
SOFTMAX                        1          Mapped to Edge TPU
CONCATENATION                  19         Mapped to Edge TPU
LOGISTIC                       58         Mapped to Edge TPU
CONV_2D                        64         Mapped to Edge TPU
QUANTIZE                       3          Mapped to Edge TPU
RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
STRIDED_SLICE                  20         Mapped to Edge TPU
TRANSPOSE                      5          Mapped to Edge TPU
PAD                            7          Mapped to Edge TPU
MAX_POOL_2D                    3          Mapped to Edge TPU
RESHAPE                        5          Mapped to Edge TPU
ADD                            8          Mapped to Edge TPU
SUB                            2          Mapped to Edge TPU
Compilation child process completed within timeout period.
Compilation succeeded! 
============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================
```

YOLOv8n uses significantly less parameters than YOLOv5s, so intuitively you would think that YOLOv8n could be run at a _**higher**_ resolution if anything. I'm unsure if this is an issue with YOLOv8, the EdgeTPU compiler, some limitation of the Coral itself, or if this is just a misconception I have. Has anyone else run into this issue? Is there some limitation on the intermediate tensor sizes not related to the number of model parameters?

**Comment by glenn-jocher** [comment]
@malleyconnor thank you for your detailed question and for providing extensive context. The situation you describe indeed seems counterintuitive given the parameters of YOLOv8n and YOLOv5s respectively. However, one thing to keep in mind is that the max resolution for a model not only depends on its number of parameters, but also on the intermediate tensor sizes, the operations used in the model and how they are supported by the specific hardware, and the implementation of these operations.

When it comes to the Google Coral EdgeTPU, there might indeed be a limitation for the intermediate tensor sizes that isn't directly related to the number of model parameters. Operationally, there might as well be some model operations in YOLOv8n that cause the export to require CPU computation. This is suggested by the presence of operations in the YOLOv8n export output that are not supported by Edge TPU.

While theoretically YOLOv8n might seem to be expected to run at at least the same or higher resolution given its number of parameters, the practical limitations imposed by the hardware and the architecture of the model itself could result in these seemingly inconsistent results.

One possible workaround for this might be to explore different versions of the Edge TPU compiler, different ways to quantize the model, or even alternate model architectures that are more compatible with Edge TPU. Ultimately the key is to find an alignment between the model, the compiler, and hardware which supports your use case. Alternatively, consider reaching out to Google Coral EdgeTPU support with the details of the operations that require CPU computation for further assistance.

**Comment by glenn-jocher** [comment]
Hello @bogdannedelcu,

Appreciate your contribution and engagement with the YOLOv8 project regarding your Coral EdgeTPU findings. It indeed sounds like an intricate problem, with potential solutions residing in a combination of factors such as the model, the compiler, and the hardware used.

If you come across a feasible workaround that allows all operations to be executed on the Coral EdgeTPU, it would be highly valuable if you could share your findings here. It would undoubtedly benefit the community as a whole. 

Similarly, if we find a solution on our end, we will definitely update this topic. We look forward to your continuous engagement and contributions towards resolving this issue.

Best regards.

**Comment by samuk** [comment]
Has anyone had any recent success with Coral?

**Comment by bogdannedelcu** [comment]
I managed to run a v5n model fully on the edge tpu, not yet v8.

Runs ok on Usb Coral stick and on Coral Dev Mini.

See here a demo of the raltime edge tpu processing on images from AirSim drone camera.

https://youtu.be/cdaIjJBYFMo?si=zaEn1noDoJpgf7jn

**Comment by samuk** [comment]
Thanks, I've just found this where it looks like they're having some success with V8 https://github.com/blakeblackshear/frigate/discussions/7650#discussioncomment-6897406

**Comment by glenn-jocher** [comment]
@samuk that's great to hear! It's encouraging to see community members finding success with YOLOv8 on the Coral EdgeTPU. The shared experiences and solutions within the community are invaluable for advancing the practical application of our models on edge devices. Thank you for pointing out the discussion on Frigate's repository. It's a good reference for others who might be facing similar challenges. Keep experimenting and sharing your findings! 🚀
