### ISSUE TITLE
How to show the map of every class ? 

### ISSUE THREAD

**Issue by sssimpleboy** [ultralytics/ultralytics#4755]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I can only see like this :
![57KP` DND9NLT$T_3 1QIF1](https://github.com/ultralytics/ultralytics/assets/100906198/f1863533-1408-4ed2-9570-ef5e4b402718)
But I could not see the message of every class.

**Comment by sssimpleboy** [comment]
Although I have set verbose=True in default.yaml

**Comment by glenn-jocher** [comment]
@sssimpleboy mAP for every class is shown on final validation after training completes, or also by directly running `yolo val model=path/to/model.pt`
