### ISSUE TITLE
Why did I download the Ultralytics-main package and extract the code ultralytics-main\ultralytics\yolo\v8 only in __init__.py?

### ISSUE THREAD

**Issue by woyaozuoniunan** [ultralytics/ultralytics#4757]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why did I download the Ultralytics-main package and extract the code ultralytics-main\ultralytics\yolo\v8 only in __init__.py?

**Comment by glenn-jocher** [comment]
@woyaozuoniunan yolo directory has been deprecated code moved to [ultralytics/models/yolo](https://github.com/ultralytics/ultralytics/tree/main/ultralytics/models/yolo)
