### ISSUE TITLE
Is the ''project" arguement in YOLO V5 still avaliable?

### ISSUE THREAD

**Issue by leyangjin** [ultralytics/ultralytics#4775]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In YOLOv5, the framework has the arguement "--project" in detect.py, which is very useful when I want to use a certain directory to save the cropped image when doing prediction. However, this arguement disapper in YOLOv8 [Inference arguement](https://docs.ultralytics.com/modes/predict/#inference-sources). Is there any way I can determine the directory to save the cropped image in YOLOv8, like what I have done in "--project" arguement in YOLOv5, when I use pretrained YOLOv8 models to inference? Thank you!

**Comment by Laughing-q** [comment]
@leyangjin yeah it's still there, just pass `project=xx`.
for cli:
```bash
yolo detect train model=yolov8n.pt project=runs
```
for python
```python
model.train(project="runs")
```

**Comment by leyangjin** [comment]
@Laughing-q  Hi, Thank you for your help. 
Sorry that I didn't make my question clear. I want to use the "--project" arguement when I use pretrained YOLOv8 models to inference (in my situation, do object detection) on my own dataset. This arguement can determine where the cropped images are saved. However, this arguement disappears in YOLOv8 [Inference Arguement](https://docs.ultralytics.com/modes/predict/#inference-sources). I wonder whether the place to save cropped images when doing object detection using YOLOv8 can still be achieved by passing arguement.

**Comment by Laughing-q** [comment]
@leyangjin oh, this arg `project` and arg `name` are applied to all the modes, including train, val, predict and export mode.
you can also use it when predicting.
```bash
yolo detect predict model=yolov8n.pt project=runs
```
```python
model.predict(project="runs")
```
