### ISSUE TITLE
I want to change the maximum ID value for tracking

### ISSUE THREAD

**Issue by ameiba00** [ultralytics/ultralytics#4778]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am currently tracking with yolov8 bootsort.

I would like to be able to set a maximum value for the tracking ID.
What file is the variable that specifies the maximum ID value?

Also, is there an easy way to change the maximum ID value?

**Comment by glenn-jocher** [comment]
@ameiba00 sure! In YOLOv8 with BoTorch, tracking IDs are typically managed by the tracker that you are using. I believe you are referring to the maximum value a tracker can assign to a newly detected object.

This matter is handled within the tracking algorithm, not by YOLOv8 directly. The tracking algorithm assigns a unique ID to each detected object and handles its management. If you're using a library like SORT (Simple Online and Realtime Tracking), the ID is determined internally by this library.

The maximum ID value is typically not set manually but gets incremented as new objects are detected. If you wish to set a maximum value for tracking IDs, you would need to modify the tracking algorithm's code, more specifically inside the tracking library you are using.

As a friendly reminder, any modifications to the tracking library used should be done with care, taking into account that these changes may have other implications, such as mishandling the object ID tracking upon reaching the maximum ID value.

**Comment by ameiba00** [comment]
Understood.
Thank you.

**Comment by glenn-jocher** [comment]
You're welcome @ameiba00! I'm glad I could help. If you have any other questions or issues with YOLOv8 in the future, don't hesitate to ask. Our team and community here are always ready to assist. Happy coding!
