### ISSUE TITLE
YOLOv8 keeps reinitializing after detection on each frame of a video.

### ISSUE THREAD

**Issue by DaniyalAhmadKhan-LUMS** [ultralytics/ultralytics#478]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

What I am doing is reading a video(using cv2) frame by frame and trying to get detection on each frame using "model.predict(frame)". But the YOLOv8 model keeps reinitializing after each frame. Is there a way around this?  

### Additional

![image](https://user-images.githubusercontent.com/60844063/213250983-19dc69b9-f8ee-462a-a0ad-f17bdc188953.png)

**Comment by AyushExel** [comment]
@DaniyalAhmadKhan-LUMS fixed in this PR -> https://github.com/ultralytics/ultralytics/pull/477
it'll be merged in main tonight.

**Comment by DaniyalAhmadKhan-LUMS** [comment]
Thanks
