### ISSUE TITLE
How to use Adan optimizer in yolov8, is that possible?

### ISSUE THREAD

**Issue by karan16mehta** [ultralytics/ultralytics#4780]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can I use adan optimizer in Yolov8 for training. If yes, what are the steps to do so?

**Comment by HtwoOtwo** [comment]
Hi, try:
`model.train(data='coco128.yaml', epochs=100, imgsz=640, optimizer='Adam')`
for more details, please refer to https://docs.ultralytics.com/modes/train/#arguments

**Comment by karan16mehta** [comment]
> Hi, try: `model.train(data='coco128.yaml', epochs=100, imgsz=640, optimizer='Adam')` for more details, please refer to https://docs.ultralytics.com/modes/train/#arguments

Actually, i meant Adan not Adam, I was going through techniques how to reduce training time and came across a paper(https://www.frontiersin.org/articles/10.3389/fpls.2023.1174556/full)  and github repo(https://github.com/sail-sg/Adan) on Adan. I want to know how can i use adan in my case

**Comment by HtwoOtwo** [comment]
Sorry i misunderstood you. If you want to use Adan, it means you need to implement an optimizer yourself, which is a bit complicated. You can try the following steps:
1. implement Adan
```python
class Adan(Optimizer):
    def __init__(self):
        pass

    torch.no_grad()
    def step(self):
        pass
```
2. change engine/trainer.py
https://github.com/ultralytics/ultralytics/blob/602022a56ea97801b0826b404a6afeec69193dff/ultralytics/engine/trainer.py#L671-L677
add
```python
elif name == 'Adan'
    optimizer = Adan(...)
```
3. change cfg/default.yaml
`optimizer: Adan # (str) optimizer to use, choices=[SGD, Adam, Adamax, AdamW, NAdam, RAdam, RMSProp, auto, Adan]`
Hope it will help you!

**Comment by glenn-jocher** [comment]
@HtwoOtwo thank you for your interest in innovative optimizers like Adan for YOLOv8!

While the YOLOv8 source code doesn't natively support Adan optimizer, it is possible to add it by following these general steps:

1. **Implement the Adan algorithm**: You need to create a new Python class that inherits from PyTorch's Optimizer base class and implement the Adan algorithm in it.
2. **Modify the training optimizer**: Next, you will have to modify the 'train' mode of YOLOv8 in 'trainer.py' to add an option to use your custom Adan optimizer.
3. **Update the config file**: Finally, update the 'default.yaml' configuration file to include 'Adan' in the list of available optimizers.

Remember, adding and testing a new optimizer requires an understanding of its behavior, potential impact on the model performance, and careful tuning. It's a challenging process but can be a rewarding experience. Good luck!

**Comment by Wang-taoshuo** [comment]
@glenn-jocher How do you modify the parameters for the AdamW optimizer in YOLOv8? thanks
