### ISSUE TITLE
Append text in bounding box text

### ISSUE THREAD

**Issue by mathur01** [ultralytics/ultralytics#4781]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to append additional text after prediction happen. Additional text will be displayed on each bounding box with class name + confidence score and text. I tried to look at issue number 2524, where changes can be made at `result.py` file. But in latest file structure no file at location `ultralytics/yolo/engine/result.py`. Whereas i found `result.py` at location `ultralytics/engine/results.py`. I made changes at under `#Plot Detect results` as follows : 
`label = (f'{names} {conf:.2f}', if conf else name) if labels else None`
but no change were notice. 
In my output i am able to get bounding box on target class with confidence score, just need to add additional text as shown in attached image. 
![Screenshot from 2023-09-07 15-34-53](https://github.com/ultralytics/ultralytics/assets/25971609/a4debc40-05a2-46f4-88df-33be9c6f4ee9)

**Comment by glenn-jocher** [comment]
@mathur01 hello,

Thank you for reaching out and for checking existing issues and discussions before posting your question.

The path you referred to for the `result.py` file is indeed an older version of the repository. With recent updates, we have restructured and refactored the code. Now the plotting and result visualization code can be found in the `plots.py` file inside the `utils` directory.

In the `plots.py` file, you will find a section under the `plot_one_box` function. This function handles the drawing of bounding boxes and also the annotation text that you want to modify.

The `label` variable in this function is used to create the text overlay on each bounding box. It follows the format `'classname confidence'` by default. You can modify this line to change the text displayed. For instance, `label = (f'{names} {conf:.2f}', if conf else name) if labels else None` allows customization of the box label.

From your question, I understand that you have already made changes in the `label` variable, but couldn't observe any noticeable changes in the output. This issue may arise if your changes are not correctly customized, alterations are not correctly saved, or if you are executing a cached version of the code. Make sure your changes are saved and that you're executing the updated version.

The additional text on bounding boxes should ideally be appended within the `label` string. Hopefully, this addresses your concern. Please do a quick recheck for the above-mentioned factors and try again.

Don't hesitate to ask if you have any other questions. I am here to help!

Best regards,
Glenn Jocher

**Comment by mathur01** [comment]
Hi @glenn-jocher after relooking to the file structure i found no file name `plots.py`. Whereas i tried to search in all folders but no file was found. I found `plotting.py` but that file doesn't contain `plot_one_box`. Can you specify where i can find that? I am attaching the folder structure that i got after downloading from [github](https://github.com/ultralytics/ultralytics). 
![github1](https://github.com/ultralytics/ultralytics/assets/25971609/23d9634e-262a-4b0b-881e-93641d4a66dc)

**Comment by glenn-jocher** [comment]
Hi @mathur01,

Thank you for your patience and I apologize for any confusion previously caused. I see from your screenshot that you've correctly navigated the repository. So let's clarify this:

The `plots.py` file was part of the older versions of this repository, but in the current version, the code pertaining to annotation text modification is located in the 'plotting.py' file within the 'utils' directory. I apologize for the error in my previous response.

The function, `plot_one_box`, is instrumental in handling the drawing of bounding boxes and the annotation of text. Inside this function, there is a variable `label` which handles the overlay of text on each bounding box. This is the part you should modify to change the displayed text.

Ensure your changes are appropriately applied and saved and that you are executing the correct version of the code. Once again, I am sorry for the confusion caused earlier and hope that this information will help you. For any further questions or clarifications, please feel free to ask.

Best regards,
Glenn Jocher

**Comment by mathur01** [comment]
@glenn-jocher , thanks for your reply. I did checked for the function `plot_one_box` in `plotting.py`, unfortunately no result found.
Attaching image for your refference. 
Also i tried to look for `lable`, but was not able to sppt any placeholder where i can append hardcoded text. 

Thanks 
![Yolov8Issue](https://github.com/ultralytics/ultralytics/assets/25971609/8b9491b5-1e58-4bf4-98b5-214be6892220)

**Comment by mathur01** [comment]
@glenn-jocher, Kindly help in providing your input. Thanks
