### ISSUE TITLE
YOLOv8 on NVIDIA Jetson Nano Developer Kit

### ISSUE THREAD

**Issue by pablomuo** [ultralytics/ultralytics#4782]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am running YOLOv8 on my NVIDIA Jetson Nano Developer Kit with custom training. My question is about the time YOLO takes to detect each frame, which is excessive in my opinion. When I run the detection on a video, webcam or through an IP Camera, YOLO takes almost one second to detect each frame. 
Is this normal? 
I suppose that the time to detect depends on the power and capacity of the computer. If this is true, is there a minimum CPU or GPU size or capacity required to run YOLO adequately, with a normal delay?
Thank you.

**Comment by glenn-jocher** [comment]
@pablomuo hello,

Thank you for bringing your question to the attention of the Ultralytics team and community.

To answer your question, the time taken for YOLOv8 to detect each frame can indeed depend on the computational power and capacity of your hardware. The NVIDIA Jetson Nano Developer Kit, while an excellent choice for many applications, has less computing power compared to some desktop GPUs. As a result, the detection time might be longer.

In terms of a minimum CPU or GPU requirement, there's no definitive limit as it can variable based on the complexity of the model, the resolution of the input data, and other factors. However, for real-time or near real-time detections, a more powerful GPU may be advisable. 

Furthermore, you might be able to improve your performance by adjusting the resolution, choosing a smaller and simpler model, or using techniques such as quantization and pruning to reduce the computational resources needed for detections.

Hope this information helps. Happy coding!

Best regards,
Ultralytics Team
