### ISSUE TITLE
Distorted masks for segmentation 

### ISSUE THREAD

**Issue by rzamarefat** [ultralytics/ultralytics#4786]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey there, thanks for this awesome repo. I have a problem related to the ground-truth masks. when the training starts, when I look at the mosaic images I see the following:
![Screenshot from 2023-09-07 23-38-51](https://github.com/ultralytics/ultralytics/assets/79300456/4a461659-dd82-4b6f-b061-4d8ad7939fe3)
I have correct masks:
1- I only consider the edge of the masked area
2- each row in GT txt files relates to one instance
3- they are all normalized
4- I verified the GT for multiple times using a simple draw method in opencv and they are all fine.

but YOLOv8 keeps learning such distorted masks and I believe it is due to the GTs. 
The only thing which may causes problem is that the GT points around one instance of a mask are not in clockwise or counter-clockwise order when iterating through the edge of the mask. Could you please tell me what might cause this problem?

**Comment by glenn-jocher** [comment]
@rzamarefat yes it's likely that your points are out of order. Please submit points in a clockwise order. You can check COCO8-seg to verify the correct sort order, i.e. run this to autodownload the dataset:

```
yolo train model=yolov8n-seg.pt data=coco8-seg.yaml
```

**Comment by glenn-jocher** [comment]
Also see https://docs.ultralytics.com/datasets/segment/coco/

Correct labels should look like this:
![image](https://github.com/ultralytics/ultralytics/assets/26833433/4e374d3e-1dfa-4ff3-9115-fcddde9b4295)

**Comment by glenn-jocher** [comment]
To order the points of a polygon in a clockwise fashion (which is commonly needed for various computer vision tasks), you can use computational geometry algorithms. In Python, this can be done conveniently using the `shapely` library. For a convex polygon, the Graham's scan algorithm can also be used to obtain a convex hull in a clockwise order, which may be useful in some cases.

Here's a Python function that takes a list of points as input and returns a new list with the points ordered in a clockwise direction:

```python
from shapely.geometry import Polygon
import numpy as np

def order_points_clockwise(points: list) -> list:
    """
    Re-orders a list of points that define a polygon to be in clockwise order.

    Args:
        points (list): List of points in the format [x1, y1, x2, y2, ..., xn, yn].

    Returns:
        list: List of points re-ordered to be in clockwise order in the same format.
    """

    # Re-arrange the points into (x, y) tuples
    points_tuples = [(points[i], points[i + 1]) for i in range(0, len(points), 2)]

    # Create a Polygon object using shapely
    polygon = Polygon(points_tuples)
    
    # If the polygon is not in clockwise order, reverse it
    if polygon.exterior.is_ccw:
        points_tuples = points_tuples[::-1]

    # Flatten the list of tuples back into a list
    ordered_points = np.array(points_tuples).flatten().tolist()

    return ordered_points

# Example usage:
# Class index is usually the first element in a YOLO segmentation model annotation, skip it for this function.
segment_points = [0.1, 0.2, 0.5, 0.6, 0.7, 0.8, 0.3, 0.4]
ordered_points = order_points_clockwise(segment_points)
print(f"Ordered points: {ordered_points}")
```

This function takes the points as input, constructs a `Polygon` object from them, and then checks whether the points are ordered in a counter-clockwise fashion by accessing the `is_ccw` attribute of the polygon's exterior ring. If the points are counter-clockwise, it reverses the list to make it clockwise.

Note: The `is_ccw` attribute assumes that the polygon's points are in a counter-clockwise order to begin with. If they're not, the `is_ccw` attribute will still return `True` or `False` based on the current ordering of the points. Therefore, this function assumes that the input points form a simple, non-intersecting polygon.

**Comment by rzamarefat** [comment]
@glenn-jocher  the order was the problem. I sort them in the clockwise order and everything is expected. I didnt use your sorting code but really appreciated it that you are very responsive to the community. I hope others would benefit from this. Thanks

**Comment by glenn-jocher** [comment]
Hello @rzamarefat,

I'm glad to hear that sorting the points in a clockwise order resolved your issue! Your experience will indeed be beneficial to other users facing a similar problem. Sharing our knowledge and practical solutions with each other is what helps our community grow stronger. 

If you encounter any other issues or have further questions, please don't hesitate to ask. We're here to help! Also, if you have any ideas or suggestions for improving YOLOv8, we would be very interested to hear them.

Thank you for your kind words and for being a part of the YOLO community!

Best regards,
Glenn Jocher

**Comment by Cung-AGA** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> ### Question
> Hey there, thanks for this awesome repo. I have a problem related to the ground-truth masks. when the training starts, when I look at the mosaic images I see the following: ![Screenshot from 2023-09-07 23-38-51](https://private-user-images.githubusercontent.com/79300456/266385243-4a461659-dd82-4b6f-b061-4d8ad7939fe3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NDc2NDcsIm5iZiI6MTcxMzU0NzM0NywicGF0aCI6Ii83OTMwMDQ1Ni8yNjYzODUyNDMtNGE0NjE2NTktZGQ4Mi00YjZmLWIwNjEtNGQ4YWQ3OTM5ZmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDE3MjIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MmM3ZDFiYTE5NmE5ZmNhMzRkZjY3YzQ4ZDhkNTAxMjFiYWMzYmQ0OWRlMzYzZjY3N2M0ZDk0ZTU4MmI3NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.agwI7psTVIN4rK8-4CIPZxB39_E_uzI45QPb1-Svwz0) I have correct masks: 1- I only consider the edge of the masked area 2- each row in GT txt files relates to one instance 3- they are all normalized 4- I verified the GT for multiple times using a simple draw method in opencv and they are all fine.
> 
> but YOLOv8 keeps learning such distorted masks and I believe it is due to the GTs. The only thing which may causes problem is that the GT points around one instance of a mask are not in clockwise or counter-clockwise order when iterating through the edge of the mask. Could you please tell me what might cause this problem?
> 
> ### Additional
> _No response_

Can you give me your solution, I have labeled clockwise but not, my data has 2 classes

**Comment by glenn-jocher** [comment]
I'm glad you found a solution to the ordering issue! 🎉 While I can't provide the exact code you used, for sorting points in a clockwise order, a common approach is to calculate the centroid of your points and then sort based on the angle each point forms with the centroid. Here's a quick snippet in Python using numpy that might help:

```python
import numpy as np

def sort_points_clockwise(points):
    # Calculate centroid
    centroid = np.mean(points, axis=0)
    # Calculate angles from centroid
    angles = np.arctan2(points[:, 1] - centroid[1], points[:, 0] - centroid[0])
    # Sort by angle
    return points[np.argsort(angles)]

# Example usage
points = np.array([[1, 2], [2, 3], [3, 1], [2, 2]])  # Replace with your points
sorted_points = sort_points_clockwise(points)
```

This might not be the exact way you've implemented your solution, but it's one of the straightforward methods to achieve clockwise ordering! If your approach differs or you have suggestions, sharing them could indeed benefit the community. 😊
