### ISSUE TITLE
Inference on rectangular image returns padded mask

### ISSUE THREAD

**Issue by yhshin11** [ultralytics/ultralytics#4796]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello all.

I am running inference on a yolov8-seg model trained with 640x640 square inputs. Unfortunately the predictor returns masks that seems to be padded to fit the square input size. Naively resizing the mask to the original image size results in inconsistent output as shown in the image below. Is there an easy way to undo this padding and obtain a binary mask that has the same size as the original input image? Perhaps using `ultralytics.data.augment.LetterBox`?

This could of course be calculated by users, but dealing with different aspect ratios could be a bit error prone and it seems like a common enough use case that would fit very naturally in `ultralytics.engine.Results`.

Thanks in advance for your help!

![sample](https://github.com/ultralytics/ultralytics/assets/5031800/828fe0d2-f8b1-4324-ad7d-c0bccd9b96eb)

**Comment by glenn-jocher** [comment]
@yhshin11 hello!

Thank you for bringing this up. Yes, YOLOv8-seg resizes the input images to a square resolution (e.g., 640x640) before passing them to the model. This process may involve padding your original image if its aspect ratio is not 1:1.

As you pointed out, naively resizing the output mask to the original image size can potentially distort the aspect ratios. This procedure might not always result in optimal segmentation results. 

The function you mentioned, `ultralytics.data.augment.LetterBox`, is indeed designed for maintaining the original aspect ratio during the pre-processing stage, however, it's not intended for recovering the original image size from the padded results.

To get a binary mask that perfectly fits your original image size, you might have to manually remove the padding from the output mask. This process would involve understanding how the model pre-processes your images before inference.

Rescaling the bounding boxes in the original image aspect ratio is something we realize might benefit many users of our models, and we appreciate your feedback suggesting its inclusion in `ultralytics.engine.Results`. I will discuss this with the development team and see if it would be possible to automate this in future versions.

Your patience and understanding are appreciated as we look into this further.

**Comment by yhshin11** [comment]
Thanks for the quick response! Glad to hear that I wasn't completely off base.

I do think it is very important for users to be able to recover the unpadded binary masks without manual calculation of the padding.
Since `LetterBox` is responsible for padding the input image, IMHO it seemed most natural to modify it to also save the "ROI" of the padded image corresponding to the original input, similar to how it's modifying the label instances:

https://github.com/ultralytics/ultralytics/blob/3c88bebc9514a4d7f70b771811ddfe3a625ef14d/ultralytics/data/augment.py#L597

I'd be open to submitting a pull request with some guidance.

Thanks again!

**Comment by glenn-jocher** [comment]
@yhshin11 your suggestion about modifying the `LetterBox` function to record the region of interest is an insightful one. It does seem like a intuitive place for such functionality considering it's already working with the image padding, as you have highlighted. 

A pull request would be welcome indeed! Here are some steps to guide you: 

1. First, you'll want to track the dimensions of the area in the padded image that corresponds to the original image within the `LetterBox` function, as you suggested.

2. Then, you'll want to add the code to use these dimensions to crop the output mask correctly after the YOLOv8-seg model completes its inference.

3. Finally, make sure the cropping process doesn't interfere with other parts of the pipeline, paying special attention to the training and validation loops.

Take your time with these modifications and don't hesitate to reach out if you need any further clarity.

Thanks so much for your contribution! Your input is much appreciated and will certainly help in improving our models and methods.
