### ISSUE TITLE
How convert outputs from YOLOv8-seg onnx model to bboxes, masks and probs ?

### ISSUE THREAD

**Issue by medphisiker** [ultralytics/ultralytics#480]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, thank you for your work and framework )

I convert **yolov8l.pt** detection model to **onnx** format by command from **tutorial.ipynb**.
`!yolo mode=export model=yolov8l.pt format=onnx`

Then I run it by **onnxrunner**, and I get output by

```
# Inference for ONNX model
import cv2
cuda = True
w = "yolov8l.onnx"
img = cv2.imread('bus.jpg')

import cv2
import time
import requests
import random
import numpy as np
import onnxruntime as ort
from PIL import Image
from pathlib import Path
from collections import OrderedDict,namedtuple

providers = ['CUDAExecutionProvider', 'CPUExecutionProvider'] if cuda else ['CPUExecutionProvider']
session = ort.InferenceSession(w, providers=providers)


def letterbox(im, new_shape=(640, 640), color=(114, 114, 114), auto=True, scaleup=True, stride=32):
    # Resize and pad image while meeting stride-multiple constraints
    shape = im.shape[:2]  # current shape [height, width]
    if isinstance(new_shape, int):
        new_shape = (new_shape, new_shape)

    # Scale ratio (new / old)
    r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])
    if not scaleup:  # only scale down, do not scale up (for better val mAP)
        r = min(r, 1.0)

    # Compute padding
    new_unpad = int(round(shape[1] * r)), int(round(shape[0] * r))
    dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]  # wh padding

    if auto:  # minimum rectangle
        dw, dh = np.mod(dw, stride), np.mod(dh, stride)  # wh padding

    dw /= 2  # divide padding into 2 sides
    dh /= 2

    if shape[::-1] != new_unpad:  # resize
        im = cv2.resize(im, new_unpad, interpolation=cv2.INTER_LINEAR)
    top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
    left, right = int(round(dw - 0.1)), int(round(dw + 0.1))
    im = cv2.copyMakeBorder(im, top, bottom, left, right, cv2.BORDER_CONSTANT, value=color)  # add border
    return im, r, (dw, dh)

names = ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 
         'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 
         'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 
         'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 
         'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 
         'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 
         'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 
         'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 
         'hair drier', 'toothbrush']
colors = {name:[random.randint(0, 255) for _ in range(3)] for i,name in enumerate(names)}

img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

image = img.copy()
image, ratio, dwdh = letterbox(image, auto=False)
image = image.transpose((2, 0, 1))
image = np.expand_dims(image, 0)
image = np.ascontiguousarray(image)

im = image.astype(np.float32)
im /= 255
im.shape

outname = [i.name for i in session.get_outputs()]
outname

inname = [i.name for i in session.get_inputs()]
inname

inp = {inname[0]:im}

# ONNX inference
outputs = session.run(outname, inp)[0]
outputs.shape
```
and I get this
`(1, 84, 8400)`

I also visualised **yolov8l.onnx** model by **https://netron.app** and I get

![image](https://user-images.githubusercontent.com/4876436/213260942-2bd68ed4-b53f-4ba4-8078-ec144f7f7a4c.png)

Output shapes from **netron** and **onnxrunner** are identical =)
How to translate this tensor **outputs** into **bboxes and probs** ?

Perhaps there is some **function** that, receiving such an **output** tensor from the model and translate it into a **results class** which **contain bboxes and probs** ?
```
for result in results:
    boxes = results.boxes # Boxes object for bbox outputs
    probs = results.probs # Class probabilities for classification outputs
```

I convert **yolov8l-seg.pt** segmentation model to **onnx** format by command from **tutorial.ipynb**.
`!yolo mode=export model=yolov8l-seg.pt format=onnx`

I also visualised **yolov8l-seg.pt** model by **https://netron.app** and I get
![image](https://user-images.githubusercontent.com/4876436/213262300-68fc7de7-ef1e-4cb5-b45d-73ce29463ee3.png)

There are we have two outputs: **output0** and **output1**.

I also run it by onnxrunner like below. I get that result:

```
# ONNX inference
outputs = session.run(outname, inp)
print(outputs[0].shape) # (1, 116, 8400)
print(outputs[1].shape)# (1, 32, 160, 160)
```

For this model, I have the same question)
How can I get **bboxes, masks and probs** from **output0** and **output1** ?
```
for result in results:
    boxes = results.boxes # Boxes object for bbox outputs
    masks = results.masks # Masks object for segmenation masks outputs
    probs = results.probs # Class probabilities for classification outputs
```

**Comment by rgkannan676** [comment]
@medphisiker . I used the following method for the detection model.
Output shape: (1, 84, 8400)
- 4 (Bounding boxes) + 80 (Confidence of the 80 classes) 
- 8400 - Total number of detections.

For bounding box conversion, use: https://github.com/ultralytics/ultralytics/blob/0cb87f7dd340a2611148fbf2a0af59b544bd7b1b/ultralytics/yolo/utils/ops.py#L312

**Comment by medphisiker** [comment]
Hello, @rgkannan676.

**Thank you very much for you help** )
Thank you for the link to a useful module with various functions for processing the output from the YOLO neural network.

I would also like to understand how masks are arranged and why the segmentation version of YOLO already has two exits. As I understand it, YOLO has two heads, one is responsible for detecting boxes, and the second for segmentation.

Dimensions are also interesting.
Detection **output0** has (1, 84, 8400) - 4 (Bounding boxes) + 80 (Confidence of the 80 classes) as you write.

My assumption that
Segmentation **output0** has (1, 116, 8400) - 4 (Bounding boxes) + 80 (Confidence of the 80 classes) and probably 32 masks ?
And probably **output1** has (1, 32, 160, 160) are coding masks ? =)

There  is one intresting question ) 
It turns out that this is the output from a pure model, and first we need to apply Non Maximum suppression to it? )
https://github.com/ultralytics/ultralytics/blob/0cb87f7dd340a2611148fbf2a0af59b544bd7b1b/ultralytics/yolo/utils/ops.py#L101

**Comment by AyushExel** [comment]
Hey guys we have documented all the operations here https://docs.ultralytics.com/reference/ops/

**Comment by rgkannan676** [comment]
@AyushExel Thank you for the information. 
Can you explain the 2 outputs for the segmentation onnx model.

For image dimensions 640x640

1)name: output0 : type: float32[1,116,8400]     
   Is it  4(bbox) + 80(number of class) + 32 (number of mask) = 116, in order?

2)name: output1 : type: float32[1,32,160,160] 
   What is in this output?

Please advise thanks.

**Comment by AyushExel** [comment]
@rgkannan676 the second output is downsampled mask prototypes which can be converted into the actual masks.
Maybe we should include that operation in the export itself. @glenn-jocher ?

**Comment by rgkannan676** [comment]
@AyushExel So the second output can hold only 32 masks. Does that mean 32 is the max number of segmentation? Please correct me If I am wrong.

Also in output0(float32[1,116,8400]). I know it contains 4 values of bbox and 80 class confidence,  what are the 32 places of mask value contains or represents? Please advise.

**Comment by AyushExel** [comment]
@rgkannan676 no those are just 32 mask prototypes. These are processed to produce any number of masks. We'll work to output the final masks directly soon!

**Comment by medphisiker** [comment]
@AyushExel, thank you for explanation )

**Output 1** contains the mask prototypes that are specified as parameter protos in functions([link to docs](https://docs.ultralytics.com/reference/ops/) and [link to source code](https://github.com/ultralytics/ultralytics/blob/0cb87f7dd340a2611148fbf2a0af59b544bd7b1b/ultralytics/yolo/utils/ops.py#L312) ): **process_mask**, **process_mask_upsample**,  **process_mask_native** ?

I also have a question with these functions )
We take the output0 from our model and feed it to Non-max suppression(NMS) function:(https://github.com/ultralytics/ultralytics/blob/0cb87f7dd340a2611148fbf2a0af59b544bd7b1b/ultralytics/yolo/utils/ops.py#L10

Then we have bboxes and masks from NMS. To get the final version of the masks should we give **output1** from YOLO as parameter **protos**, bboxes from NMS as parameter **bboxes**, masks from NMS as parameter **masks_in** to **process_mask**, **process_mask_upsample**,  **process_mask_native** ?

**Comment by rgkannan676** [comment]
> @rgkannan676 no those are just 32 mask prototypes. These are processed to produce any number of masks. We'll work to output the final masks directly soon!

@AyushExel thank you for the update. Can you please advise when will the direct mask feature be added? Thanks

**Comment by medphisiker** [comment]
> We'll work to output the final masks directly soon!

Thank you and all your team for this decision ) The implementation of the output of the final masks by the model itself would also be convenient for conversion to `onnx` and `TensorRT`. This will also simplify their use.
In the current implementation, we can choose between getting high-resolution segmentation masks(by retina_masks = False) and just masks, but faster. 
Will it still be possible to choose the quality of output masks and NMS ? It turns out that for this you need to be able to create slightly different models of neural networks with different final output of the model?

**Comment by pderrenger** [comment]
@medphisiker Thanks for your feedback. We'll keep improving the model for flexibility and ease of use. Multiple model configurations are one approach, but we'll also explore other options. Thank you for your suggestions and patience!
