### ISSUE TITLE
How to count tracked objects? *ultralytics, tracking, counting*

### ISSUE THREAD

**Issue by olakrajna** [ultralytics/ultralytics#4800]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In my project, I'm working on acne detection and tracking skin changes on detected faces. However, I'm not entirely sure how to obtain information about the number of tracked objects. I tried to implement code for counting, but I'm not sure if it's the correct approach. I also attempted to assign IDs, but they ended up being 'None'. I'm sharing my code below, and thank you in advance for your help. 

` new_spots = []
            number_of_pimples_detected = []
            most_pimples_detected = []

            if face_react is not None:
                x, y, w, h = face_react
                cropped_face = flipped_frame[y - 70:y + h, x:x + w]  # Crop the face from the frame
                if cropped_face.shape[0] == 0 or cropped_face.shape[1] == 0:
                    continue
                # results = model(source=cropped_face)
                results = model.track(source=cropped_face, show=True, tracker="bytetrack.yaml")
                cv2.rectangle(flipped_frame, (x, y - 70), (x + w, y + h), (0, 0, 255), 2)
                print(results)
            for res in results:
                boxes = res.boxes
                print(boxes.is_track)
                for box in boxes:
                    x1, y1, x2, y2 = box.xyxy[0]
                    cx, cy = int((x1 + x2) / 2), int((y1 + y2) / 2)
                    # dis = distance(cx, cy, spot33[0], spot33[1])
                    if (cx, cy) not in new_spots:
                        new_spots.append((cx, cy))
                        number_of_pimples_detected.append((len(new_spots)))
                        most_pimples_detected.append(max(number_of_pimples_detected))
                        # cv2.circle(cropped_face, (cx, cy), 3, (0, 0, 255), -1)

            if most_pimples_detected:
                if max(most_pimples_detected) > max_value:
                    max_value = max(number_of_pimples_detected)
                    with open('amount_of_pimples.pickle', 'wb') as f:
                        pickle.dump(max_value, f)
                print("Amount of pimples: ", max_value)
            else:
                max_value = 0
                with open('amount_of_pimples.pickle', 'wb') as f:
                    pickle.dump(max_value, f)`

 Additionally, when I print the information using print(boxes), is_track is set to False, and I'm wondering why that is the case..

![image](https://github.com/ultralytics/ultralytics/assets/105561199/6f66e59d-c58b-4eac-8afc-89c5f9d650e3)

**Comment by glenn-jocher** [comment]
@olakrajna based on your question, it seems you are trying to implement tracking and counting of detected objects using YOLOv8. 

For counting the number of detections, you typically want to access the length of the detections list that the model produces per frame or image. However, from your code it seems like you're trying to count newly appeared detections based on their coordinates, which might not be the most effective strategy if the objects are moving or disappearing and reappearing between frames.

As per the track IDs being 'None', it's difficult to say without knowing the specifics of your tracking implementation and configuration. But typically, track IDs are assigned by a tracker, which usually requires a special tracking function or algorithm in combination with the detection model to work properly.

Regarding the `is_track` set to False, it seems like your tracking may not be correctly configured or functioning. The 'is_track' property is supposed to indicate whether the bounding boxes are attributed to tracked objects or not. 

Remember, for the tracking to work properly, it needs to be appropriately configured and the objects need to be consistently detected in subsequent frames. Consider checking your tracking configuration and ensure that your objects are being reliably detected.

**Comment by olakrajna** [comment]
> @olakrajna based on your question, it seems you are trying to implement tracking and counting of detected objects using YOLOv8.
> 
> For counting the number of detections, you typically want to access the length of the detections list that the model produces per frame or image. However, from your code it seems like you're trying to count newly appeared detections based on their coordinates, which might not be the most effective strategy if the objects are moving or disappearing and reappearing between frames.
> 
> As per the track IDs being 'None', it's difficult to say without knowing the specifics of your tracking implementation and configuration. But typically, track IDs are assigned by a tracker, which usually requires a special tracking function or algorithm in combination with the detection model to work properly.
> 
> Regarding the `is_track` set to False, it seems like your tracking may not be correctly configured or functioning. The 'is_track' property is supposed to indicate whether the bounding boxes are attributed to tracked objects or not.
> 
> Remember, for the tracking to work properly, it needs to be appropriately configured and the objects need to be consistently detected in subsequent frames. Consider checking your tracking configuration and ensure that your objects are being reliably detected.

How to access the length of the detections list and how to properly configure tracking, and what exactly reliable object detection in consecutive frames means... I'm new to these topics and I don't fully understand everything yet.

**Comment by glenn-jocher** [comment]
@olakrajna sure, I'd be happy to help clarify!

Accessing the length of the detections list simply means checking how many objects have been identified in one frame or image. After your model performs object detection on an image, it should return a list (or similar data structure) containing the identified objects. The length of this list is equal to the number of detected objects.

As for tracking configuration, it generally involves setting up a separate tracking algorithm alongside your object detection. This algorithm assigns unique IDs to each detected object and attempts to "follow" them across multiple frames, allowing the system to tell when the same object appears in more than one frame.

The term 'reliably detected' in the context of object tracking generally implies that the object detector needs to accurately detect objects across consecutive frames to facilitate object tracking. If an object is detected in one frame but not in the next, it will appear as though the object has disappeared which can disrupt the tracking process.

These are fairly complex topics, so don't worry if you're finding them a little challenging as a newcomer. Keep experimenting, learning and asking questions and you'll get the hang of it in no time!

**Comment by Ajantha-Aravind** [comment]
@glenn-jocher Hello, I am using the YOLov8 model for my custom dataset for detection, and I used my trained model for tracking and counting with a normal tracking and association algorithm. Everything was perfect as I expected. I am working on a video with multi-object detection, tracking, and counting. The issue is that I used a YOLOv8 model dataset from Roboflow for training and detection, now I want to calculate the metric MOTA. I looked for so many possibilities, but I didn't get the MOTA. Can you please tell me the correct path?

**Comment by glenn-jocher** [comment]
@Ajantha-Aravind to calculate MOTA (Multiple Object Tracking Accuracy) for your YOLOv8 tracking results, you'll need ground truth annotations with track IDs and a MOTA evaluation library. The Ultralytics package doesn't include built-in MOTA calculation, but you can use external libraries like `motmetrics` or `TrackEval`. You'll need to format your tracking results and ground truth data to match the expected input format (typically MOT Challenge format), then use these libraries to compute MOTA alongside other tracking metrics like MOTP, IDF1, and ID switches.
