### ISSUE TITLE
Training issue tensorboard --logdir runs/detect/train ?

### ISSUE THREAD

**Issue by TapendraBaduwal** [ultralytics/ultralytics#4803]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to train directly without below option how to do ?

TensorBoard: Start with 'tensorboard --logdir runs/detect/train', view at http://localhost:6006/
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:

**Comment by TapendraBaduwal** [comment]
Solve by creating new venv.

**Comment by glenn-jocher** [comment]
@TapendraBaduwal if you'd like to train without TensorBoard and WandB prompt, you could adjust the settings in your train.py file. 

For TensorBoard, the presence of logs is triggered by the 'log_imgs' argument in the train function. You can set this to zero to disable logging. 

For WandB, it's a bit more involved. Assuming you have cloned the latest version of our YOLOv8 repository, there is a flag '--no-wandb' which you can use while starting your training. This should enable training without initializing WandB. If it still prompts for WandB login, you could comment out the WandB related lines of code. However, tread carefully as these lines also handle essential aspects of the training process like logging and saving the trained model.

Always remember that while tweaking these settings may adjust the training environment to your preferences, it could also hinder your ability to monitor the training process effectively.

Recreating your virtual environment worked for you, which is great to hear. However, adjusting the settings as I've described would be a more targeted solution for those who wish to disable these features.

Remember, our objective is to make YOLOv8 an efficient and flexible tool for everyone. We appreciate your input in making this happen.

**Comment by chaimaexy** [comment]
i have the same issue . whatever choice i make , the training stops . what do i do?

**Comment by glenn-jocher** [comment]
@chaimaexy it sounds like you're encountering an unexpected interruption during training. To resolve this, ensure your environment meets all the necessary requirements and that you have the latest version of the repo. If the issue persists, please open a new issue with detailed error logs and system information so we can help you troubleshoot effectively. 🛠️

**Comment by clebemachado** [comment]
Using the ultralytics version to disable, do I have to pass any arguments? I didn't find it in the documentation.

Or defining a local path to the project (I'm using colab) avoids using the wandb?

**Comment by glenn-jocher** [comment]
You can disable WandB by setting `WANDB_MODE="disabled"` in your environment before running the training. For local logging, specify a custom `project` path in your training command.
