### ISSUE TITLE
Add object count to streamed video.

### ISSUE THREAD

**Issue by GianniGi** [ultralytics/ultralytics#481]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When running a prediction for a video (http or rtsp...), for example like

`results = model.predict(source=rtsp, show=True, line_thickness=1)`

https://docs.ultralytics.com/predict/

is it possible to work with "results" https://docs.ultralytics.com/reference/results/ and then show them in the image, maybe to: 

- **modify the boxes** (scale change color etc)

- **adding overlay info** to the streaming video, for example like an object count??

Thanks

### Additional

maybe something like this, which was available in yolov5?

https://github.com/ultralytics/yolov5/issues/381

**Comment by AyushExel** [comment]
@GianniGi Short answer: no, it's currently not supported in the high-level python interface. 

Long answer: This is something you might achieve by using the engine directly and adding a callback to basePredictor class. We don't have a lot of documentation of this kind right now. We only have one customization tutorial for building your custom trainer here https://docs.ultralytics.com/engine/

**Comment by GianniGi** [comment]
Is yolov8 going to be a standalone product, or will it need to be used through opencv? 

I don't understand what can I use the video detection for, if I don't have any usable output...

For example like this?
https://github.com/DAVIDNYARKO123/yolov8-silva

**Comment by AyushExel** [comment]
You can just pass `show=True` in predict function to display results
