### ISSUE TITLE
multiple gpu not working

### ISSUE THREAD

**Issue by i2w3** [ultralytics/ultralytics#4810]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, The code is not working and the program is not running. Now stop at AMP.
```python
import ultralytics
from ultralytics import YOLO

ultralytics.checks()

model = YOLO("yolov8n-seg.pt")
model.train(data='./good_pointer/data.yaml', epochs=100, imgsz=1280,device=[1,2,3,4],
            project="./",name="MeterSeg")
```
I would like to use devices 1, 2, 3, and 4 for training, as device 0 is currently being used.
![que.png](https://i.postimg.cc/KYHK84K0/que.png)

**Comment by kincjf** [comment]
https://github.com/ultralytics/ultralytics/issues/2744#issuecomment-1558184982

Hello, I am using ultralytics hub well. I am always grateful.
Referring to the previous answer as shown below, I set the code as shown below when running in the hub, but all three codes always use train only in gpu:0.

I was told to set the cfg yaml file, but I'm not sure where to set it when running train in the hub execution environment;
I created a file called "default.yaml" in the same path as the ipynb file and saved the gpu number related settings. But maybe I did something wrong, but the GPU number is still only recognized as 0.

```python
model.train(device=[0,1])
model.train(device=[0])
model.train(device=1)
```

**Comment by glenn-jocher** [comment]
@i2w3 hello,

Thank you for using Ultralytics and appreciating our work!

I see you're trying to use multiple GPUs for training. When specifying the device in `model.train()`, the `device` parameter should be a string representing the IDs of the GPU devices you want your model to be trained on, separated by commas. For example, if you'd like to use GPUs 0 and 1, the argument to the `device` parameter should be '0,1'.

In your case, you've passed the GPU IDs as a list, which might not be the correct way to specify it. Try passing them as a string and the `model.train()` method should recognize the GPUs correctly.

Also, you should create a YAML configuration file for your custom settings. In this file, you can specify the GPU by adding a line such as `device: '2,3'` for GPUs 2 and 3, and then refer to this configuration file whilst running your training script.

Please try these suggestions and let us know if you still face any issues.

Best regards,
Glenn

**Comment by i2w3** [comment]
> @i2w3 hello,
> 
> Thank you for using Ultralytics and appreciating our work!感谢您使用Ultralytics并欣赏我们的工作！
> 
> I see you're trying to use multiple GPUs for training. When specifying the device in `model.train()`, the `device` parameter should be a string representing the IDs of the GPU devices you want your model to be trained on, separated by commas. For example, if you'd like to use GPUs 0 and 1, the argument to the `device` parameter should be '0,1'.我看到你在尝试使用多个GPU进行训练。当在 `model.train()` 中指定设备时， `device` 参数应该是一个字符串，表示希望在其上训练模型的GPU设备的ID，用逗号分隔。例如，如果您想使用GPU 0和1， `device` 参数的参数应该是'0，1'。
> 
> In your case, you've passed the GPU IDs as a list, which might not be the correct way to specify it. Try passing them as a string and the `model.train()` method should recognize the GPUs correctly.在您的示例中，您已经将GPU ID作为列表传递，这可能不是指定它的正确方式。尝试将它们作为字符串传递， `model.train()` 方法应该能正确识别GPU。
> 
> Also, you should create a YAML configuration file for your custom settings. In this file, you can specify the GPU by adding a line such as `device: '2,3'` for GPUs 2 and 3, and then refer to this configuration file whilst running your training script.此外，您应该为您的自定义设置创建一个YAML配置文件。在此文件中，您可以通过为GPU 2和GPU 3添加一行（例如 `device: '2,3'` ）来指定GPU，然后在运行训练脚本时参考此配置文件。
> 
> Please try these suggestions and let us know if you still face any issues.请尝试这些建议，如果您仍然面临任何问题，请告诉我们。
> 
> Best regards, Glenn

Hello,I think the code has found a suitable device, but it still stops at AMP check passed.
[![333.png](https://i.postimg.cc/RhWJQW0Y/333.png)](https://postimg.cc/m1GrT2C3)

**Comment by glenn-jocher** [comment]
Hello @i2w3,

Thank you for the screenshot, it is very helpful for understanding your issue. From your screenshot, it can be seen that the model found the device and is not showing any obvious errors. 

The step it's stuck on, 'AMP check passed', is associated with Automatic Mixed Precision, a type of training that uses both 16-bit and 32-bit floating-point types to make model training faster and require less memory. In some cases, if the AMP check doesn't pass, it might be because of hardware compatibility issues. 

Please make sure that you are using the latest versions of PyTorch and CUDA Toolkit, and that the GPUs you are using are compatible with mixed precision training. 

If the problem persists, it may be helpful to check the system's resource usage during the training to see if there might be a resource issue causing the training to stall.

If all seems well with your system and software, you may want to try disabling Automatic Mixed Precision by setting "--amp" to "False" when calling the training function.

Let us know if these suggestions are helpful or if you have any more questions. We are here to help!

**Comment by i2w3** [comment]
> Hello @i2w3,
> 
> Thank you for the screenshot, it is very helpful for understanding your issue. From your screenshot, it can be seen that the model found the device and is not showing any obvious errors.
> 
> The step it's stuck on, 'AMP check passed', is associated with Automatic Mixed Precision, a type of training that uses both 16-bit and 32-bit floating-point types to make model training faster and require less memory. In some cases, if the AMP check doesn't pass, it might be because of hardware compatibility issues.
> 
> Please make sure that you are using the latest versions of PyTorch and CUDA Toolkit, and that the GPUs you are using are compatible with mixed precision training.
> 
> If the problem persists, it may be helpful to check the system's resource usage during the training to see if there might be a resource issue causing the training to stall.
> 
> If all seems well with your system and software, you may want to try disabling Automatic Mixed Precision by setting "--amp" to "False" when calling the training function.
> 
> Let us know if these suggestions are helpful or if you have any more questions. We are here to help!

Thank you for your reply. Do you have any suggestions for using multiple GPUs with Ubuntu 18, such as configuring the Linux software and environment.

**Comment by glenn-jocher** [comment]
Hi @i2w3,

When using multiple GPUs on Ubuntu 18 for training, it's essential to update your software environment, notably your graphics driver, CUDA toolkit, and deep learning libraries, to their latest versions for compatibility and performance reasons.

Once updated, you should be able to indicate the GPUs to use for training using their IDs. In the command you use to start training, there should be an argument where you can specify this (often called --device, --gpu, etc.). You should list the GPU IDs separated by commas, such as '0,1' for GPUs 0 and 1.

Keep in mind that if you want to use NVIDIA's CUDA with multiple GPUs, each GPU should have a compute capability of 3.5 or higher and they should all be of the same type/model for optimal results.

When using multiple GPUs, the GPUs compute the forward pass in parallel, aggregate the results for the backward pass, and then update the model parameters. This process requires GPU memory and CPU memory, so ensure that your system has enough resources.

One last point, if you're using PyTorch, it provides a data parallelism feature that can help you utilize multiple GPUs. 

Remember that running deep learning models on multiple GPUs can be challenging and results may vary. It is best to start with a single GPU and scale up keeping an eye on system resources usage.

Let us know if you have more questions or need further assistance.  

Best regards,
Ultralytics team

**Comment by i2w3** [comment]
> Hi @i2w3,
> 
> When using multiple GPUs on Ubuntu 18 for training, it's essential to update your software environment, notably your graphics driver, CUDA toolkit, and deep learning libraries, to their latest versions for compatibility and performance reasons.
> 
> Once updated, you should be able to indicate the GPUs to use for training using their IDs. In the command you use to start training, there should be an argument where you can specify this (often called --device, --gpu, etc.). You should list the GPU IDs separated by commas, such as '0,1' for GPUs 0 and 1.
> 
> Keep in mind that if you want to use NVIDIA's CUDA with multiple GPUs, each GPU should have a compute capability of 3.5 or higher and they should all be of the same type/model for optimal results.请记住，如果您想将NVIDIA的CUDA与多个GPU一起使用，则每个GPU的计算能力都应达到3.5或更高，并且它们都应具有相同的类型/型号以获得最佳效果。
> 
> When using multiple GPUs, the GPUs compute the forward pass in parallel, aggregate the results for the backward pass, and then update the model parameters. This process requires GPU memory and CPU memory, so ensure that your system has enough resources.当使用多个GPU时，GPU并行计算前向传递，聚合后向传递的结果，然后更新模型参数。此过程需要GPU内存和CPU内存，因此请确保系统具有足够的资源。
> 
> One last point, if you're using PyTorch, it provides a data parallelism feature that can help you utilize multiple GPUs.
> 
> Remember that running deep learning models on multiple GPUs can be challenging and results may vary. It is best to start with a single GPU and scale up keeping an eye on system resources usage.
> 
> Let us know if you have more questions or need further assistance.如果您有更多问题或需要进一步帮助，请联系我们。
> 
> Best regards, Ultralytics team

Hi, May I ask if cuda12 will fail to run?

```bash
Ultralytics YOLOv8.0.180 🚀 Python-3.9.17 torch-2.0.1+cu118 CUDA:0 (NVIDIA A800 80GB PCIe, 81053MiB)
Setup complete ✅ (112 CPUs, 503.5 GB RAM, 587.8/845.6 GB disk)
Ultralytics YOLOv8.0.180 🚀 Python-3.9.17 torch-2.0.1+cu118 CUDA:4 (NVIDIA A800 80GB PCIe, 81053MiB)
                                                            CUDA:5 (NVIDIA A800 80GB PCIe, 81053MiB)
                                                            CUDA:6 (NVIDIA A800 80GB PCIe, 81053MiB)
                                                            CUDA:7 (NVIDIA A800 80GB PCIe, 81053MiB)
engine/trainer: task=segment, mode=train, model=yolov8s-seg.pt, data=/home/baode/CNN/ultralytics-main/four_repointer/data.yaml, epochs=200, patience=50, batch=32, imgsz=2560, save=True, save_period=-1, cache=False, device=[4, 5, 6, 7], workers=8, project=./MeterSeg, name=train, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=MeterSeg/train20
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments                     
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]                 
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]             
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]           
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]              
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]           
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]                 
 22        [15, 18, 21]  1   2770931  ultralytics.nn.modules.head.Segment          [1, 32, 128, [128, 256, 512]] 
YOLOv8s-seg summary: 261 layers, 11790483 parameters, 11790467 gradients

Transferred 411/417 items from pretrained weights
DDP: debug command /home/baode/anaconda3/envs/pytorch2.0/bin/python -m torch.distributed.run --nproc_per_node 4 --master_port 56263 /home/baode/LONGXIONGB/MeterSeg/yolov8_train.py
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Ultralytics YOLOv8.0.180 🚀 Python-3.9.17 torch-2.0.1+cu118 CUDA:0 (NVIDIA A800 80GB PCIe, 81053MiB)
Setup complete ✅ (112 CPUs, 503.5 GB RAM, 587.8/845.6 GB disk)
Ultralytics YOLOv8.0.180 🚀 Python-3.9.17 torch-2.0.1+cu118 CUDA:4 (NVIDIA A800 80GB PCIe, 81053MiB)
                                                            CUDA:5 (NVIDIA A800 80GB PCIe, 81053MiB)
                                                            CUDA:6 (NVIDIA A800 80GB PCIe, 81053MiB)
                                                            CUDA:7 (NVIDIA A800 80GB PCIe, 81053MiB)
Overriding model.yaml nc=80 with nc=1
Transferred 411/417 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
```
still stop at AMP: checks passed ✅

**Comment by glenn-jocher** [comment]
@i2w3 hi,

Regarding your question about CUDA 12, there shouldn't be any incompatibility issues with using CUDA 12 and YOLOv8, as long as all your software components including the graphics driver and deep learning libraries, are up-to-date.

Your logs show that the process does not proceed after the AMP checks, which implies that the issue might not be CUDA-related, since it seems to initialize correctly and recognize your GPUs. There may be other factors such as insufficient resources, issues with your dataset or a problematic model state causing the training to stall.

Suggestions to debug:

1. Review your system resources during execution, such as memory usage and CPU load, to identify any bottlenecks. 
2. Check if your model and data inputs are correctly configured and that there are no inconsistencies or errors in your data.
3. Try running your training with a smaller batch size or on a single GPU to see if there's any change.

Please provide us with more details about your setup or any error messages you're seeing if the issue persists, so we can assist you better.

Best regards,
Ultralytics team

**Comment by i2w3** [comment]
> @i2w3 hi,
> 
> Regarding your question about CUDA 12, there shouldn't be any incompatibility issues with using CUDA 12 and YOLOv8, as long as all your software components including the graphics driver and deep learning libraries, are up-to-date.
> 
> Your logs show that the process does not proceed after the AMP checks, which implies that the issue might not be CUDA-related, since it seems to initialize correctly and recognize your GPUs. There may be other factors such as insufficient resources, issues with your dataset or a problematic model state causing the training to stall.
> 
> Suggestions to debug:
> 
> 1. Review your system resources during execution, such as memory usage and CPU load, to identify any bottlenecks.
> 2. Check if your model and data inputs are correctly configured and that there are no inconsistencies or errors in your data.
> 3. Try running your training with a smaller batch size or on a single GPU to see if there's any change.
> 
> Please provide us with more details about your setup or any error messages you're seeing if the issue persists, so we can assist you better.
> 
> Best regards, Ultralytics team

Hi, I have fixed this issue because my server did not disable ACS. Now I can train with multiple cards. Thank you for your reply!
```python
import os
os.environ['NCCL_P2P_DISABLE'] = '1'
```

**Comment by glenn-jocher** [comment]
@i2w3 hi there,

I'm glad to hear that you've resolved the issue! Your solution to disable ACS (Access Control Services) within the server environment seems to have effectively addressed your training stalling problem. 

The Python code you provided indeed helps force NCCL (the NVIDIA Collective Communications Library) to avoid using P2P (Peer-to-peer) capabilities, which can help in scenarios where there's hardware or software limitations preventing successful multi-GPU training. 

Just be aware that this may affect the speed of the training process to some degree, as data transfer between GPUs might end up being less efficient depending on your specific setup.

Thank you for sharing your solution with us, this could definitely be helpful to other users facing similar issues with multi-GPU setups.

Best of luck with your project!

-Ultralytics team

**Comment by dbparkJ** [comment]
@i2w3 
Hi i2w3, I couldn't solve it because I was experiencing the same problem as you, but writing the same code you wrote down solved it. Thank you so much!

**Comment by i2w3** [comment]
> @i2w3 Hi i2w3, I couldn't solve it because I was experiencing the same problem as you, but writing the same code you wrote down solved it. Thank you so much!

You are welcome, you can modify the bios settings to completely solve it.

**Comment by glenn-jocher** [comment]
@dbparkJ hi there,

I'm glad to know that the solution provided by i2w3 was of big help for you! That's great news. As is mentioned, you might also want to consider adjusting your BIOS settings for a more permanent fix. Many times, the appropriate GPU configurations in the BIOS can prevent similar issues. Make sure to refer to your GPU's or system's documentation for additional guidance about this.

Please be aware of the potential impacts on other system aspects and use caution when modifying BIOS settings. Don't hesitate to reach out if you run into any other problems, we're here to help!

-Ultralytics Team

**Comment by ychuest** [comment]
> > @i2w3你好，
> > 关于您对 CUDA 12 的问题，只要您的所有软件组件（包括图形驱动程序和深度学习库）都是最新的，使用 CUDA 12 和 YOLOv8 就不会存在任何不兼容问题。
> > 您的日志显示，在 AMP 检查后，该过程没有继续，这意味着问题可能与 CUDA 无关，因为它似乎可以正确初始化并识别您的 GPU。可能还有其他因素导致训练停滞，例如资源不足、数据集存在问题或模型状态有问题。
> > 调试建议：
> > 
> > 1. 执行期间检查系统资源，例如内存使用情况和 CPU 负载，以识别任何瓶颈。
> > 2. 检查您的模型和数据输入是否配置正确，以及数据中是否存在不一致或错误。
> > 3. 尝试使用较小的批量大小或在单个 GPU 上运行训练，看看是否有任何变化。
> > 
> > 如果问题仍然存在，请向我们提供有关您的设置或您看到的任何错误消息的更多详细信息，以便我们更好地为您提供帮助。
> > 谨致问候，Ultralytics 团队
> 
> 您好，我已经修复了这个问题，因为我的服务器没有禁用 ACS。现在我可以用多张卡进行训练了。谢谢您的回复！
> 
> ```python
> import os
> os.environ['NCCL_P2P_DISABLE'] = '1'
> ```

it's work for me too, thanks!!!!!
