### ISSUE TITLE
How to disable data augmentation in the training?

### ISSUE THREAD

**Issue by maxmelichov** [ultralytics/ultralytics#4812]
### Search before asking

- [ ] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to disable data augmentation in the training?
`results= model.train(data="/content/drive/MyDrive/Computer vision project/config_border.yaml", epochs=50,augment =False,hsv_h =0,hsv_s =0,hsv_v =0,degrees =0,translate =0,scale =0,shear =0,flipud =0,fliplr=0,mixup =0,agnostic_nms =False,cos_lr =False)`

it still augmenting the training data I'm working on.
The object itself is small and with augmention on it cannot detect it, Please help.
Thanks

**Comment by glenn-jocher** [comment]
@maxmelichov you can set any augmentations you don't want to use to 0.0 during training as you've done. For a full list of arguments see https://docs.ultralytics.com/modes/train/#arguments

**Comment by ThomasDeLange** [comment]
@glenn-jocher It seems that the list of augmentations is nog available anymore on the site that you have linked. Is there another page which included used annotations?

**Comment by glenn-jocher** [comment]
Hi @ThomasDeLange, thank you for pointing out the broken link.

The list of augmentations typically includes transformations such as hue, saturation, exposure, rotation (degrees), scale, and shear, along with flipping the images either up-down (flipud) or left-right (fliplr), and translating the images horizontally or vertically. 

If you wish to disable data augmentation, you can set the corresponding values to 0 when calling the train function, as you had previously done. Please keep in mind that disabling data augmentation could potentially affect the model's ability to generalize to unseen data.

Sorry for the inconvenience, and we'll work to update the documentation soon. Your participation makes this project better for everyone. Thanks again!
