### ISSUE TITLE
Save data in Excel

### ISSUE THREAD

**Issue by aavci22** [ultralytics/ultralytics#4816]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I'm new to this. I searched and couldn't find any similar solutions. I want to record the information about the detected object line by line at the same time as other information. can you help me.

I am recording to Excel with User, Date, Fps data. In addition to this data, I want to instantly add the information of the detected object. These include information such as object name, class, id, location, xyz, accuracy rate, respectively.

I could not adapt it with the Results information in the documents.

### Additional

 import os
 import datetime
 import xlsxwriter
 import cv2
 import tkinter as tk
 from tkinter import ttk
 from ultralytics import YOLO
 from PIL import Image, ImageTk
 import time
 import socket

class WebcamApp:
    def __init__(self, window, window_title):
        self.log_file = None
        self.log_filename = None
        self.start_time = None
        self.frame_count = None
        self.window = window
        self.window.title(window_title)

        self.main_frame = tk.Frame(window)
        self.main_frame.pack()

        
        self.left_frame = tk.Frame(self.main_frame, bg="")
        self.left_frame.grid(row=0, column=0, padx=5, pady=20, sticky="nw")

       
        self.right_frame = tk.Frame(self.main_frame, bg="")
        self.right_frame.grid(row=0, column=1, padx=5, pady=20, sticky="nw")

        self.button_style = ttk.Style()
        self.button_style.configure("Custom.TButton", font=("Helvetica", 12), padding=5)

        self.button_state = False
        self.button_text = tk.StringVar()
        self.button_text.set("Başlat")
        self.button = ttk.Button(
            self.left_frame,
            textvariable=self.button_text,
            style="Custom.TButton",
            command=self.toggle_button
        )
        self.button.grid(row=0, column=0, padx=10, pady=5, sticky="ne")

        self.camera_var = tk.StringVar(value="0")
        self.camera_combo = ttk.Combobox(self.left_frame, textvariable=self.camera_var, values=["0", "1", "2"])
        self.camera_combo.grid(row=1, column=0, padx=0, pady=20, sticky="nw")

        self.fps_label = tk.Label(self.left_frame, text="FPS: 0")
        self.fps_label.grid(row=2, column=0, padx=0, pady=5, sticky="nw")

        self.datetime_label = tk.Label(self.left_frame, text="")
        self.datetime_label.grid(row=3, column=0, padx=0, pady=5, sticky="nw")

        self.canvas = tk.Canvas(self.right_frame, width=700, height=640)
        self.canvas.grid(row=0, column=0, columnspan=2)

        self.model = None
        self.cap = None
        self.update()

        self.log_folder = None
        self.image_counter = 0
        self.excel_file_name = None  

        
        self.excel_file = None
        self.excel_worksheet = None

      
        self.folder_creation_datetime = None

    def toggle_button(self):
        self.button_state = not self.button_state
        if self.button_state:
            self.button_text.set("Stop")
            self.model = YOLO('best.pt')
            camera_index = int(self.camera_var.get())
            self.cap = cv2.VideoCapture(camera_index)
            self.start_time = time.time()
            self.frame_count = 0

            # Get the directory where the script is located
            script_dir = os.path.dirname(os.path.abspath(__file__))

      
            computer_name = socket.gethostname()

            # Specify the absolute path to the folder where you want to save data
            folder_name = os.path.join(script_dir, "Control", "DataSave", computer_name)

            os.makedirs(folder_name, exist_ok=True)

     
            self.folder_creation_datetime = datetime.datetime.now()
            current_date = self.folder_creation_datetime.strftime("%d-%m-%Y-%H-%M")
            folder_name = os.path.join(folder_name, current_date)
            os.makedirs(folder_name, exist_ok=True)

     
            self.log_folder = folder_name

            if not os.path.exists(self.log_folder):
                os.makedirs(self.log_folder)

            self.log_filename = os.path.join(self.log_folder, f"{current_date}.txt")
            self.log_file = open(self.log_filename, "w")

 
            self.excel_file_name = os.path.join(self.log_folder, f"{current_date}.xlsx")
            self.excel_file = xlsxwriter.Workbook(self.excel_file_name)
            self.excel_worksheet = self.excel_file.add_worksheet()
            self.excel_worksheet.write(0, 0, "Pc Name")
            self.excel_worksheet.write(0, 1, "Date")
            self.excel_worksheet.write(0, 2, "FPS")

        else:
            self.button_text.set("Start")
            if self.cap:
                self.cap.release()
                self.cap = None
            self.model = None

            if self.log_file:
                self.log_file.close()
                self.log_file = None

            
            if self.excel_file:
                self.excel_file.close()
                self.excel_file = None
                self.excel_worksheet = None

    def save_image(self, image, filename):
        save_path = os.path.join(self.log_folder, filename)
        image.save(save_path)

    def save_detected_images(self, results):
        for result in results:
            annotated_frame = result.plot()
            img = Image.fromarray(cv2.cvtColor(annotated_frame, cv2.COLOR_BGR2RGB))
            timestamp = datetime.datetime.now().strftime('%d-%m-%Y-%H-%M')
            filename = f"{timestamp}_detected_image_{self.image_counter}.jpg"

           
            save_path = os.path.join(self.log_folder, filename)
            img.save(save_path)

            self.image_counter += 1

           
            if self.excel_worksheet:
                row = self.image_counter
                computer_name = socket.gethostname()
                current_datetime = datetime.datetime.now().strftime("%d-%m-%Y-%H-%M")
                fps = self.frame_count / (time.time() - self.start_time)
                self.excel_worksheet.write(row, 0, computer_name)
                self.excel_worksheet.write(row, 1, current_datetime)
                self.excel_worksheet.write(row, 2, fps)

    def update(self):
        if self.cap is not None and self.cap.isOpened():
            success, frame = self.cap.read()

            if success:
                resized_frame = cv2.resize(frame, (600, 400))
                results = self.model(resized_frame, conf=0.1, save_txt=True)

                if self.button_state and len(results) > 0:
                    self.save_detected_images(results)

                img = Image.fromarray(cv2.cvtColor(resized_frame, cv2.COLOR_BGR2RGB))
                img = ImageTk.PhotoImage(image=img)
                self.canvas.create_image(0, 0, image=img, anchor=tk.NW)
                self.canvas.img = img

                self.frame_count += 1
                current_time = time.time()
                elapsed_time = current_time - self.start_time
                if elapsed_time >= 1.0:
                    fps = self.frame_count / elapsed_time
                    self.fps_label.config(text=f"FPS: {fps:.2f}")
                    self.start_time = current_time
                    self.frame_count = 0

                    if self.log_file:
                        current_datetime = datetime.datetime.now().strftime("%d-%m-%Y-%H-%M")
                        log_line = f"{current_datetime} - FPS: {fps:.2f}\n"
                        self.log_file.write(log_line)

        current_datetime = datetime.datetime.now().strftime("%d-%m-%Y-%H-%M")
        self.datetime_label.config(text=current_datetime)

        self.window.after(10, self.update)

    def run(self):
        self.window.mainloop()

 if __name__ == "__main__":
    root = tk.Tk()
    app = WebcamApp(root, "Control")
    app.run()

**Comment by glenn-jocher** [comment]
@aavci22 hello,

Thanks for reaching out and welcome to the YOLOv8 world. Your question is clear: you want to enhance your Excel logging to include object detection information for each detected object - features like the object name, class, id, location, xyz, and accuracy rate, besides existing User, Date, Fps data. 

The solution lies within the "results" variable as you rightly figured out. You see, the "results" object contains detection results per image. Every result in "results" is an array of detected objects. Each object in this array is an instance of a class that (among other data) includes: object name, class, id, location (xyxy), and confidence. 

In your 'toggle_button' function, you've already set up a system for writing PC Name, Date, and FPS to the excel worksheet. You can apply a similar method within the 'save_detected_images' loop to include detected object data.

First, you'll want to iterate over the detentions in each result. For each detected object, fetch the required details and write them to your excel worksheet at the appropriate indices. If you want to write each object on a new row, ensure you increment the row index appropriately.

Also, bear in mind that certain details like location (xyxy) and xyz may require special handling if you want to store them in separate excel cell(s) because they themselves are arrays.

I hope the explanation is clear enough. Let me know if you have any follow up questions.

Happy coding!

**Comment by aavci22** [comment]
unfortunately. I couldn't do it. It would be nice if you could show it with sample code. thank.

**Comment by glenn-jocher** [comment]
Hi @aavci22,

I'm sorry to hear that you're still having trouble. Let's try to break it down a bit more.

In the YOLOv8 codebase, after performing object detection on an image, the results are stored in the "results" object you mentioned. Each item in this object's array represents a detected object within the image.

For each detected object, it has many attributes like the object class, id, name, location, and confidence score, among other things. These attributes correspond to the details you want to log in your Excel file.

What you'd want to do is iterate through these detection results stored in the "results" object. For each detected object (result), you can then extract the necessary information (name, class, id, location, xyz, accuracy) and write them to a new row in your Excel file, just as you're already doing with the User, Date, FPS values.

For attributes that are arrays themselves, such as location, you'd have to think about how you want to store them in your Excel file. You could write the entire array into one cell, or you could split the array across multiple cells. 

It's very much the same process that you're using to write the User, Date, FPS data, just applied to each detected object. Remember to increase the row index to avoid overwriting data each time a detected object is logged.

I hope this gives a better understanding. I'm confident that you can do it, just give it another shot. If you have more questions, feel free to ask. Good luck!
