### ISSUE TITLE
Keypoints Extraction

### ISSUE THREAD

**Issue by zohaibmaqsoodahmad** [ultralytics/ultralytics#4818]
### Discussed in https://github.com/orgs/ultralytics/discussions/4817

<div type='discussions-op-text'>

<sup>Originally posted by **zohaibmaqsoodahmad** September 10, 2023</sup>
Hi!
I want to extract  keypoints from an image which may contain 1 human or multiple human. But I only want keypoints. I don't want to display the image. just want to extract keypoints.</div>

**Comment by glenn-jocher** [comment]
Hello @zohaibmaqsoodahmad,

Absolutely, YOLOv8 is capable of doing keypoint detection, which is useful for pose estimation tasks. In your case, you would like to extract keypoints from the images, and YOLOv8 can handle that efficiently, even with multiple humans in the image.

After running the model on your images, you would receive a set of keypoints for each detected person in the image. A keypoint represents a specific point of interest in the image and is given by its 2D location (x, y coordinates) in the image. For a human, keypoints are typically associated with specific body joints like elbow, knee, etc.

To avoid displaying the image you just need to not call the function for visualizing the image. The keypoints you need are available in the model’s output. You don't need to display the image if you do not need to.

Keep in mind that the number and position of keypoints depend on the model used, and YOLOv8 returns a specific set of keypoints, defined by the model's architecture.

I hope this helps! Let me know if you have any other questions.
