### ISSUE TITLE
Output inferred image in python code using model.predict

### ISSUE THREAD

**Issue by DaniyalAhmadKhan-LUMS** [ultralytics/ultralytics#482]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The following code only returns the bounding box, class, and confidence of the predicted image. Is there any way I can get the inferred image and store it in a variable in my code?

### Additional

![image](https://user-images.githubusercontent.com/60844063/213303727-da468c57-c83e-48a2-9fb4-f18d7b999b48.png)

**Comment by ichsan2895** [comment]
Related to this thread:
https://github.com/ultralytics/ultralytics/issues/430 

Hopefully it works
```
results = model.predict(source=0, stream=True, return_outputs=True)
```

**Comment by kadirnar** [comment]
> return_outputs

This parameter doesn't work
``return_outputs is not a valid key. Similar keys: []```

**Comment by AyushExel** [comment]
Please see the docs here for usage - https://docs.ultralytics.com/predict/

**Comment by DaniyalAhmadKhan-LUMS** [comment]
![image](https://user-images.githubusercontent.com/60844063/213404788-d8747fbe-232a-4390-a474-8c5e2d06ed40.png)

It isn't clear how to draw bounding boxes on the original image. Should I do it manually?

**Comment by AyushExel** [comment]
@kadirnar to draw a bounding box in the input image? You can just pass `save=True`. But if you want to draw a bounding box on the in-memory object, currently we don't support that but we might implement it in the future

**Comment by DaniyalAhmadKhan-LUMS** [comment]
Great! Thank you.

**Comment by shrroylee** [comment]
@AyushExel the boxes result is undefined. Can you please take a look here [https://github.com/ultralytics/ultralytics/issues/516](https://github.com/ultralytics/ultralytics/issues/516). I'm not sure if this is a bug.

**Comment by alikarimi120** [comment]
@shrroylee 
Install new version

pip install ultralytics

**Comment by dharun9** [comment]
import streamlit as st
from PIL import Image
from ultralytics import YOLO

Load your YOLOv8 model with 'best27.pt'
model = YOLO('best27.pt')

Streamlit app
st.title('Cow Breed Detection with YOLOv8')

Allow the user to upload an image
uploaded_image = st.file_uploader("Upload an image for cow breed detection", type=["jpg", "png", "jpeg"])

if uploaded_image is not None:
# Display the uploaded image
st.image(uploaded_image, caption='Uploaded Image', use_column_width=True)

# Make a prediction when the user clicks a button
if st.button('Detect Cow Breeds'):
    image = Image.open(uploaded_image)

    # Run object detection
    results = model(image)

    # Initialize a list to store detected cow breeds
    detected_breeds = []

    # Iterate over detected objects
    for i in range(len(results.xyxy)):
        left, top, right, bottom = results.xyxy[i].cpu().numpy()
        conf = results.conf[i].item()
        class_id = results.cls[i].item()

        # Get the class name using the 'names' dictionary
        class_name = model.names[class_id]

        # You can add your logic to determine the breed using class_name and confidence
        # For simplicity, let's assume 'Cow' if confidence is above a threshold
        breed = class_name if conf > 0.5 else "Unknown"

        detected_breeds.append(breed)

    # Display the detected cow breeds
    if detected_breeds:
        st.write('Detected Cow Breeds:')
        for i, breed in enumerate(detected_breeds):
            st.write(f"{i + 1}: {breed}")
    else:
        st.write('No cows detected in the image.')

    st.success('Cow breed detection completed.')
The Error I've been facing

0: 544x640 1 charolois, 399.4ms
Speed: 15.6ms preprocess, 399.4ms inference, 0.0ms postprocess per image at shape (1, 3, 544, 640)
2023-11-07 12:20:19.839 Uncaught app exception
Traceback (most recent call last):
File "C:\Users\Dharun prasanth\anaconda3\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
exec(code, module.dict)
File "C:\Users\Dharun prasanth\OneDrive\Documents\Cow_IP\yolo.py", line 29, in
for i in range(len(results.xyxy)):
AttributeError: 'list' object has no attribute 'xyxy'

But im getting the correct output the vscode is something wrong with my Streamlit

**Comment by glenn-jocher** [comment]
@dharun9 hello,

I understand that you're encountering issues when using the YOLOv8 model within a Streamlit application, and you are receiving an `AttributeError` as the result object does not have an `xyxy` attribute. 

To address this issue, make sure that the object returned from the model prediction is what you expect it to be. Typically, invoking the model on an image should return a results object that you can interact with and extract the prediction details such as bounding boxes, confidences, and class IDs.

The way you are attempting to access detections seems to imply you are expecting the results object to have a particular structure. YOLOv8 provides a results object that includes various details about the predictions made. It is likely structured differently than you are expecting in your Streamlit app.

Please carefully review how the results object is structured after invoking the prediction so you can properly iterate over detections and extract the necessary information. The `results` would generally contain the predictions, and you might need to adapt your code to fit the data structure used by the YOLOv8 model. You will want to check the length and attributes of the `results` variable.

Ensure that you're correctly parsing the model's output. You need to handle the results as per the defined structure by the YOLOv8 inference process. Typically, you might iterate over each detection in a result and verify that you're accessing attributes that exist.

Remember to debug your application by printing out intermediates and ensuring that variables contain the data you expect at each step.

I hope this guidance is helpful. Good luck with your cow breed detection application!
