### ISSUE TITLE
Torchscript to TFLite or another format ?

### ISSUE THREAD

**Issue by shubhank008** [ultralytics/ultralytics#4837]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I had exported my model to torchscript format a few weeks ago (.torchscript.ptl) for mobile usage, but forgot to save original model and data.  
Now my torchscript model works fine, but is it possible to use it to export to another format like tflite or onnx ?  

I tried export method but seems it wants original .pt model, is there any way to do this ?

**Comment by glenn-jocher** [comment]
@shubhank008 hello,

Thanks for reaching out. Generally speaking, the Ultralytics YOLOv8 repo does not support direct conversion from a TorchScript format to other formats like ONNX or TFLite out of the box. Exporting to these formats typically requires the original PyTorch model (.pt).

This is due to the way these models are structured and serialized. The .torchscript.ptl format preserves the model's architecture and weights but does not retain detailed information needed to convert to other formats. It's a bit like trying to convert a finished product back into its raw materials - you need the original blueprint (i.e., the .pt model file).

It's always good practice to keep a version of your original .pt model and training data for situations like these. In your case, if there was a way to somehow retrieve or recreate the original .pt model, you would have more flexibility in converting to other formats. 

I hope this answers your question, and sorry for the inconvenience.

**Comment by shubhank008** [comment]
> @shubhank008 hello,
> 
> Thanks for reaching out. Generally speaking, the Ultralytics YOLOv8 repo does not support direct conversion from a TorchScript format to other formats like ONNX or TFLite out of the box. Exporting to these formats typically requires the original PyTorch model (.pt).
> 
> This is due to the way these models are structured and serialized. The .torchscript.ptl format preserves the model's architecture and weights but does not retain detailed information needed to convert to other formats. It's a bit like trying to convert a finished product back into its raw materials - you need the original blueprint (i.e., the .pt model file).
> 
> It's always good practice to keep a version of your original .pt model and training data for situations like these. In your case, if there was a way to somehow retrieve or recreate the original .pt model, you would have more flexibility in converting to other formats.
> 
> I hope this answers your question, and sorry for the inconvenience.

Ah crap, actually we had gotten this model made by a freelancer who only provided us the torchscript file (well, I believe it is a pytorch live file as its .torchscript.ptl) and while it worked in our mobile app, we are now updating things and it stopped working.  

Tried to contact the freelancer but hes MIA and he never sent us the .pt main model file.  
The model is made in yolov8 but using it directly via terminal or in python throws error. Python throwing some XNNPACK error (google colab testing) and running with yolo in mac/terminal with a image file some dimension error


`yolo predict model=torch.torchscript source=image.png`

<img width="1541" alt="Screenshot 2023-09-12 at 7 43 20 AM" src="https://github.com/ultralytics/ultralytics/assets/3790163/271cf276-694f-471f-8bca-681f2c96916a">


![image](https://github.com/ultralytics/ultralytics/assets/3790163/a06e736e-8df4-416d-be5d-6f1d08106dda)


```
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', or 'pose'.
Ultralytics YOLOv8.0.175 🚀 Python-3.11.5 torch-2.0.1 CPU (Apple M1 Pro)
Loading torch.torchscript for TorchScript inference...
WARNING ⚠️ Metadata not found for 'model=torch.torchscript'

Traceback (most recent call last):
  File "/opt/homebrew/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ultralytics/cfg/__init__.py", line 445, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ultralytics/engine/model.py", line 238, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 199, in predict_cli
    for _ in gen:  # running CLI inference without accumulating any outputs (do not modify)
  File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 253, in stream_inference
    preds = self.inference(im, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 133, in inference
    return self.model(im, augment=self.args.augment, visualize=visualize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ultralytics/nn/autobackend.py", line 335, in forward
    y = self.model(im)
        ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/ultralytics/nn/tasks/___torch_mangle_1783.py", line 162, in forward
    _94 = torch.split(torch.view(_93, [_90, 4, _91]), 2, 1)
    lt, rb, = _94
    x1y1 = torch.sub(CONSTANTS.c64, lt)
           ~~~~~~~~~ <--- HERE
    x2y2 = torch.add(CONSTANTS.c64, rb)
    c_xy = torch.div(torch.add(x1y1, x2y2), CONSTANTS.c65)

Traceback of TorchScript, original code (most recent call last):
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/ultralytics/yolo/utils/tal.py(199): dist2bbox
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/ultralytics/nn/modules.py(411): forward
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/torch/nn/modules/module.py(1182): _slow_forward
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/torch/nn/modules/module.py(1194): _call_impl
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/ultralytics/nn/tasks.py(57): _forward_once
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/ultralytics/nn/tasks.py(194): forward
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/torch/nn/modules/module.py(1182): _slow_forward
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/torch/nn/modules/module.py(1194): _call_impl
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/torch/jit/_trace.py(976): trace_module
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/torch/jit/_trace.py(759): trace
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/ultralytics/yolo/engine/exporter.py(255): _export_torchscript
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/ultralytics/yolo/engine/exporter.py(102): outer_func
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/ultralytics/yolo/engine/exporter.py(203): __call__
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/torch/autograd/grad_mode.py(27): decorate_context
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py(181): export
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/torch/autograd/grad_mode.py(27): decorate_context
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/ultralytics/yolo/cfg/__init__.py(251): entrypoint
/Users/rlebouc/workspace/ai/ultralytics/env/bin/yolo(8): <module>
RuntimeError: The size of tensor a (18900) must match the size of tensor b (8400) at non-singleton dimension 2
```

**Comment by shubhank008** [comment]
@glenn-jocher other code examples I have tried to use the model with

```
import numpy as np
from PIL import Image 
import tensorflow as tf

image_path = "/content/scene.png"
input_size = 960
stride = 32

input_data_type = np.float32
image = np.array(Image.open(image_path).resize((input_size,input_size)), dtype=input_data_type)
print(image.shape)
if input_data_type == np.float32:
    image = image / 255.

if image.shape == (1, input_size, input_size):
    image = np.stack(image*3, axis=0)
    print(image.shape)
image = np.expand_dims(image, axis=0)
image = torch.from_numpy(image)
print(image.shape)

with torch.inference_mode():
  all_encoder_layers, pooled_output = loaded_model(*image)
```

Output
```
(960, 960, 3)
torch.Size([1, 960, 960, 3])
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-45-e5b24c1af9d3>](https://localhost:8080/#) in <cell line: 22>()
     21 
     22 with torch.inference_mode():
---> 23   all_encoder_layers, pooled_output = loaded_model(*image)

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1499                 or _global_backward_pre_hooks or _global_backward_hooks
   1500                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501             return forward_call(*args, **kwargs)
   1502         # Do not call functions when jit is used
   1503         full_backward_hooks, non_full_backward_hooks = [], []

RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/ultralytics/nn/tasks/___torch_mangle_1783.py", line 7, in forward
  def forward(self: __torch__.ultralytics.nn.tasks.___torch_mangle_1783.DetectionModel,
    x: Tensor) -> Tensor:
    _0 = ops.prepacked.conv2d_clamp_run(x, CONSTANTS.c0)
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    input = torch.silu_(_0)
    _1 = ops.prepacked.conv2d_clamp_run(input, CONSTANTS.c1)

Traceback of TorchScript, original code (most recent call last):
  File "", line 4, in forward
          %transposed:bool, %output_padding:int[], %groups:int, %benchmark:bool,
          %deterministic:bool, %cudnn_enabled:bool, %allow_tf32:bool):
        %r = aten::conv2d(%a, %w, %b, %stride, %padding, %dilation, %groups)
             ~~~~ <--- HERE
        return (%r) 
RuntimeError: required rank 4 tensor to use channels_last format
```



```
!TORCH_XNNPACK_DISABLE=1
from ultralytics import YOLO

# Load a model
model = YOLO("/content/torch.torchscript")  # load a pretrained model (recommended for training)

# Use the model
#model.train(data="coco128.yaml", epochs=3)  # train the model
#metrics = model.val()  # evaluate model performance on the validation set
#results = model("https://ultralytics.com/images/bus.jpg")  # predict on an image
#path = model.export(format="tflite")  # export the model to ONNX format

# Run inference on an image
results = model('/content/scene.png')  # list of 1 Results object
```



Output
```
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', or 'pose'.
Loading /content/torch.torchscript for TorchScript inference...
WARNING ⚠️ Metadata not found for 'model=/content/torch.torchscript'

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-36-35a6ec1b6075>](https://localhost:8080/#) in <cell line: 14>()
     12 
     13 # Run inference on an image
---> 14 results = model(['/content/scene.png'])  # list of 1 Results object

9 frames
[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1499                 or _global_backward_pre_hooks or _global_backward_hooks
   1500                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501             return forward_call(*args, **kwargs)
   1502         # Do not call functions when jit is used
   1503         full_backward_hooks, non_full_backward_hooks = [], []

RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/ultralytics/nn/tasks/___torch_mangle_1783.py", line 162, in forward
    _94 = torch.split(torch.view(_93, [_90, 4, _91]), 2, 1)
    lt, rb, = _94
    x1y1 = torch.sub(CONSTANTS.c64, lt)
           ~~~~~~~~~ <--- HERE
    x2y2 = torch.add(CONSTANTS.c64, rb)
    c_xy = torch.div(torch.add(x1y1, x2y2), CONSTANTS.c65)

Traceback of TorchScript, original code (most recent call last):
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/ultralytics/yolo/utils/tal.py(199): dist2bbox
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/ultralytics/nn/modules.py(411): forward
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/torch/nn/modules/module.py(1182): _slow_forward
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/torch/nn/modules/module.py(1194): _call_impl
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/ultralytics/nn/tasks.py(57): _forward_once
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/ultralytics/nn/tasks.py(194): forward
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/torch/nn/modules/module.py(1182): _slow_forward
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/torch/nn/modules/module.py(1194): _call_impl
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/torch/jit/_trace.py(976): trace_module
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/torch/jit/_trace.py(759): trace
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/ultralytics/yolo/engine/exporter.py(255): _export_torchscript
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/ultralytics/yolo/engine/exporter.py(102): outer_func
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/ultralytics/yolo/engine/exporter.py(203): __call__
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/torch/autograd/grad_mode.py(27): decorate_context
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py(181): export
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/torch/autograd/grad_mode.py(27): decorate_context
/Users/rlebouc/workspace/ai/ultralytics/env/lib/python3.9/site-packages/ultralytics/yolo/cfg/__init__.py(251): entrypoint
/Users/rlebouc/workspace/ai/ultralytics/env/bin/yolo(8): <module>
RuntimeError: The size of tensor a (18900) must match the size of tensor b (8400) at non-singleton dimension 2
```

**Comment by glenn-jocher** [comment]
@shubhank008 hello and thank you for using YOLOv8!

For the first error, a potential reason might be that your input tensor does not have the right shape. The error "required rank 4 tensor to use channels_last format" suggests that it requires a tensor of four dimensions while the tensor being fed has a different rank. Please verify the dimensions of your input image tensor. Remember, the typical shape of an input tensor for a convolutional network is [batch_size, channels, width, height].

In the second error, the traceback "The size of tensor a (18900) must match the size of tensor b (8400) at non-singleton dimension 2", indicates a mismatch in tensor sizes during a mathematical operation. This often arises when combining two tensors in a way that requires their shapes to match, for instance, during an addition, subtraction or other similar operation. Please ensure the sizes and dimensions of all tensors used in these types of operations are compatible with each other.

If the problem persists and the above suggestions do not work, could you please provide some more details such as the versions of the PyTorch and other libraries you are using? This would help us understand the issues better and provide more accurate solutions.

If you have any more questions or issues, feel free to ask. We're here to help.

**Comment by shubhank008** [comment]
> @shubhank008 hello and thank you for using YOLOv8!
> 
> For the first error, a potential reason might be that your input tensor does not have the right shape. The error "required rank 4 tensor to use channels_last format" suggests that it requires a tensor of four dimensions while the tensor being fed has a different rank. Please verify the dimensions of your input image tensor. Remember, the typical shape of an input tensor for a convolutional network is [batch_size, channels, width, height].
> 
> In the second error, the traceback "The size of tensor a (18900) must match the size of tensor b (8400) at non-singleton dimension 2", indicates a mismatch in tensor sizes during a mathematical operation. This often arises when combining two tensors in a way that requires their shapes to match, for instance, during an addition, subtraction or other similar operation. Please ensure the sizes and dimensions of all tensors used in these types of operations are compatible with each other.
> 
> If the problem persists and the above suggestions do not work, could you please provide some more details such as the versions of the PyTorch and other libraries you are using? This would help us understand the issues better and provide more accurate solutions.
> 
> If you have any more questions or issues, feel free to ask. We're here to help.

Thank you so much for such a detailed reply, you were right and your pointers led me into right direction to make it work (somehow).  
It seems the model is indeed made to accept image data only and at specific size (instead of a image directly like `yolo image.png`)


I had to read raw image data, resize to 960 and then feed it into model (both yolo and pytorch worked).  
And it indeed wanted `[batch_size, channels, width, height]` while I was under assumption it was `[batch_size, width, height, channels]`

I had a few followup questions if you don't mind ?

Here are the codes that worked

**1. In this code, the normal way of reading image and turning it into a tensor would not work, throw me a error, while transforming the image using torch's inbuild image transformation methods worked. 
Am I doing anything wrong in normal way of pre-processing my image ? I donot want to rely on torch's methods as I want to rewrite python version of code to java/swift when I use the model in mobile, and donot want to rely on torch library specific methods.**

```
import numpy as np
from PIL import Image, ImageDraw 
import tensorflow as tf

import torch
import torchvision
from torch.utils.mobile_optimizer import optimize_for_mobile

loaded_model = torch.jit.load("/content/yolov8s.960.v110423.torchscript.ptl")
#loaded_model = torch.jit.load("/content/yolov5s.torchscript.ptl")
#loaded_model = torch.jit.load("/content/torch.torchscript")
loaded_model.eval()

image_path = "/content/test3.jpeg"
input_size = 960
stride = 32

input_data_type = np.float32

## THIS DID NOT WORK
image = np.array(Image.open(image_path).resize((input_size,input_size)), dtype=input_data_type)
print(image.shape)
if input_data_type == np.float32:
    image = image / 255.

if image.shape == (1, input_size, input_size):
    image = np.stack(image*3, axis=0)
    print(image.shape)
image = np.expand_dims(image, axis=0)
image = torch.from_numpy(image)
## ABOVE DID NOT WORK

## THIS DID WORK
img = Image.open(image_path)
transform = torchvision.transforms.Compose([torchvision.transforms.Resize((input_size,input_size)),torchvision.transforms.ToTensor()])
tensor = transform(img)
input_tensor = torch.unsqueeze(tensor, 0)
## ABOVE DID WORK

image = input_tensor

print(image.shape)

with torch.inference_mode():
  pooled_output = loaded_model(image)
  #print(pooled_output)
  print(pooled_output.shape)
  max = torch.max(pooled_output)
  print(max)
```

Output
```
(960, 960, 3)
torch.Size([1, 3, 960, 960])
torch.Size([1, 56, 18900])
tensor(955.42712)
```

**2. Another problem was, I had the right results/output but was not able to parse/process them properly to get the detected class id (highest score), I lost the code I was using for it but tried various versions from publicly available examples of using Yolo in Python 
Ultimately, I had to resort using the model with Yolo library, which again I want to avoid to not rely on library specific code so I can use the model in other languages/devices.**  

Below is the code I use to access the parsed data, the model was processed through Yolo instead of pytorch

```
!TORCH_XNNPACK_DISABLE=1
from ultralytics import YOLO

# Load a model
model = YOLO("/content/torch.torchscript")  # load a pretrained model (recommended for training)

## THIS DID NOT WORK EITHER, SO AGAIN I USED THE SAME IMAGE PROCESSED THROUGH PYTORCH FROM ABOVE ## CODE
#img = cv2.imread(image_path)
#(H, W) = img.shape[:2]
#blob = cv2.dnn.blobFromImage(img, 1 / 255.0, (input_size, input_size),swapRB=True, crop=False)

results = model.predict(image)  # list of 1 Results object
```


**Processing The results**
```
import cv2
from ultralytics.utils.plotting import Annotator
from google.colab.patches import cv2_imshow
from PIL import ImageFont

def convert_to_original_size(box, size, original_size):
  x_scale=float(original_size[0]/size[0])
  y_scale=float(original_size[1]/size[1])
  #print(x_scale,y_scale)
  x_upper_right=int(np.round(box[0]*x_scale))
  y_upper_right=int(np.round(box[1]*y_scale))
  x_lower_left=int(np.round(box[2]*x_scale))
  y_lower_left=int(np.round(box[3]*y_scale))
  return [x_upper_right,y_upper_right,x_lower_left,y_lower_left]

# Blue color in BGR
color = (255, 0, 0)
#frame = cv2.imread(image_path)
frame = img
#print(results[0])
result = results[0]
output = []

draw = ImageDraw.Draw(img)
#print(img.size)
print(np.array(img.size))

for box in result.boxes:
    x1, y1, x2, y2 = [
      round(x) for x in box.xyxy[0].tolist()
    ]
    #print(box.xyxy[0].tolist())
    boxi = convert_to_original_size(box.xyxy[0].tolist(), np.array([input_size,input_size]), np.array(frame.size))
    draw.rectangle(boxi, outline=color)    
    class_id = box.cls[0].item()
    prob = round(box.conf[0].item(), 2)
    print(class_id)
    #print(result.names)
    output.append([
      x1, y1, x2, y2, classes[int(class_id)][0], prob
    ])
    #label
    label = classes[int(class_id)][0]
    fontsize = 15 
    #font = ImageFont.truetype("Arial.ttf", fontsize) 
    #txt_width, txt_height = font.getsize(label)
    txt_width, txt_height = (100,50)
    draw.text((box.xyxy[0][0], box.xyxy[0][1] - txt_height + 1), label, fill=color, font=None) 
    #cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)


#cv2_imshow(frame)
#img.show()
display(img)
print(output)
```


Output (class ids)
```
[1200  900]
43.0
47.0
39.0
39.0
47.0
12.0
3.0
13.0
13.0
12.0
3.0
51.0
```

**Comment by glenn-jocher** [comment]
Hello @shubhank008,

I'm glad to hear that the pointers helped and you were able to get the model to work.

In response to your questions:

1. The value error you're experiencing when using numpy could be due to the fact that numpy arranges the shape of the image differently from PyTorch's transformations. PyTorch uses the (C, H, W) format (channels, height, width) for images, but the shape of your numpy array seems to be (H, W, C). To achieve the desired tensor format without PyTorch, you may need to re-order the dimensions of your numpy array to match the (C, H, W) format before converting it into a tensor. 

   In terms of translating the code to other languages, the transformation methods used are pretty standard in image processing, and equivalent methods should be available in Java or Swift. For resizing and normalization (dividing by 255), you can find similar functions regardless of the programming language you're using.

2. Parsing the output of the model can be complex due to the nature of the YOLO model's output. The output tensor includes information about the bounding boxes, class probabilities, and more. In general, the output must be processed through several steps (including applying a threshold to the class scores, non-max suppression, etc.) to obtain the final list of bounding boxes. 

   Although you want to avoid relying on specific library functions for this, it may be hard to avoid, because the parsing is not necessarily straightforward. However, the process should be similar across platforms, with the needed functions being available in most programming libraries for deep learning. Hence, it should be possible to implement in Java and Swift, provided that you have a deep understanding of the output tensor structure. 

I hope this helps and I encourage you to continue exploring and experimenting. You're making great progress! If you encounter more questions or issues, please don't hesitate to ask.
