### ISSUE TITLE
its possible to run two yolov8 models at the same time ?

### ISSUE THREAD

**Issue by Rasantis** [ultralytics/ultralytics#4842]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a face detection model using yolov8 and apply functions to blur these faces. and I also use a bag detection model. can i run these two models at the same time in a video?

**Comment by RizwanMunawar** [comment]
@Rasantis yes, you can use multi-threading for this task. Keep in mind, that it will also affect the inference speed because you will run two models in parallel.

**Sample Code**
```
import cv2
import threading
from pathlib import Path

from ultralytics import YOLO
def run_tracker_in_thread(filename, model):
    video = cv2.VideoCapture(filename)
    frames = int(video.get(cv2.CAP_PROP_FRAME_COUNT))
    for _ in range(frames):
        ret, frame = video.read()
        if ret:
            cv2.imshow("test", frame)
            #......
            #......
            #......
            # Processing the video file

# Load the models
model1 = YOLO('face detection model file.pt')
model2 = YOLO('bag detection model file.pt')

# Define the video files for the trackers
video_file1 = 'video file path'
video_file2 = 'video file path'

# Create the detection threads
detection_thread1 = threading.Thread(target=run_tracker_in_thread, args=(video_file1, model1))
detection_thread2 = threading.Thread(target=run_tracker_in_thread, args=(video_file2, model2))

# Start the detection threads
detection_thread1.start()
detection_thread2.start()

# Wait for the detection threads to finish
detection_thread1.join()
detection_thread2.join()

# Clean up and close windows
cv2.destroyAllWindows()
```

For more information, you can check [docs.ultralytics.com](https://docs.ultralytics.com/modes/track/#multithreaded-tracking)
