### ISSUE TITLE
imgsz 1280 in openvino optimization

### ISSUE THREAD

**Issue by Rasantis** [ultralytics/ultralytics#4850]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

i would like to request to add imgsz as argument in openvino optimization for 1280 not only 640. thanks for this amazing tool

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Rasantis thank you for your suggestion regarding the addition of `imgsz` as an argument in OpenVINO optimization for 1280, not just 640. This sounds like an excellent idea and a useful feature to include.

Given that the size of the input image can significantly impact the performance and accuracy of the model, it's important to provide flexibility and adaptability for various use cases. I'll share this with the Ultralytics team and consider implementing this feature in the next release.

Your feedback like this helps us ensure we are continuing to develop and optimize YOLOv8 to meet the needs of many diverse users and scenarios. As always, we appreciate contributions from our community, and we look forward to more collaboration in the future.
