### ISSUE TITLE
how to extract polygon coordinates when using onnyruntime

### ISSUE THREAD

**Issue by davidvct** [ultralytics/ultralytics#4851]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I can extract polygon coordinates with the code below in Yolo v8:
```
model = YOLO(model_path)
result = model(image, conf=conf)[0]
polygon= result.masks.xy
```
How can I extract the same data when using onnxruntime?

**Comment by glenn-jocher** [comment]
@davidvct certainly! When utilizing ONNXRuntime with Ultralytics' YOLOv8, the inference process will return an output in the form of a tensor, similar to how it operates in the native framework. This tensor will include all the post-processing information that the model needs, including the detection boxes, class probabilities, and segmentations (if you're working with mask predictions as well).

In the particular case you're addressing, where you want to extract polygon coordinates, the output tensor will hold this information. You need to manually parse these details from the output tensor. This functionality isn't provided natively in ONNXRuntime like in the YOLOv8 Python code you provided, so you'll need to create a custom function to obtain and format this output.

This custom function will need to re-implement the post-processing steps that the native YOLOv8's "Result" class applies on the model's raw output to retrieve detections and their polygons. This essentially involves translating the corresponding post-processing code in Ultralytics' YOLO to work with the output you're obtaining from ONNXRuntime.

I hope this helps! We recommend considering the ease of use and the rich post-processing functionality of native Ultralytics prediction pipeline before deciding to move to ONNXRuntime in your project. The differences between them can be quite large, and the native framework offers these benefits right out of the box.
