### ISSUE TITLE
Predict - Ultralytics YOLOv8 Docs

### ISSUE THREAD

**Issue by scohill** [ultralytics/ultralytics#4855]
<div type='discussions-op-text'>
Hello, is there a way to change the crops names from imagename2, imagename3,.. to imagename-2 imagename-3 

</div>

**Comment by glenn-jocher** [comment]
@scohill yes, this is controlled by the internal `separator` argument here. You could modify this by hand to the desired separator.

https://github.com/ultralytics/ultralytics/blob/3c88bebc9514a4d7f70b771811ddfe3a625ef14d/ultralytics/utils/files.py#L85-L118

**Comment by scohill** [comment]
> @scohill yes, this is controlled by the internal `separator` argument here. You could modify this by hand to the desired separator.
> 
> https://github.com/ultralytics/ultralytics/blob/3c88bebc9514a4d7f70b771811ddfe3a625ef14d/ultralytics/utils/files.py#L85-L118

Thank you so much and have a nice rest of the day :D

**Comment by glenn-jocher** [comment]
Hi @scohill, 

You're very welcome and I'm glad that you found the information helpful! 

As you've correctly mentioned, the crop names are indeed influenced by the internal `separator` parameter. If you wish to change it, you can adjust the separator to your desired format directly in the code where it is defined.

I hope this solution assists you in achieving your project goals. Should you have additional questions or need further clarification, please don't hesitate to ask.

Enjoy the rest of your day and best of luck with your work on YOLOv8!
