### ISSUE TITLE
return_outputs is not a valid key. Similar keys: [] An exception has occurred, use %tb to see the full traceback.  SystemExit

### ISSUE THREAD

**Issue by pamudu123** [ultralytics/ultralytics#486]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

---------------------------------------------------------------------------
SystemExit                                Traceback (most recent call last)
[<ipython-input-54-ae27232b4efa>](https://localhost:8080/#) in <module>
      5 img_path = r'/content/drive/MyDrive/Yolo_chess_project/YOLOv8/datasets/Modified-Chess-Peaces-1/test/images/test_10_jpg.rf.44086d2f859d70828ece83be6da120ff.jpg'
      6 img_path = save_path
----> 7 results = model.predict(source=img_path, conf=0.25,return_outputs=True)
      8 #results = model.predict(source=', conf=0.25)
      9 

4 frames
[/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/configs/hydra_patch.py](https://localhost:8080/#) in check_config_mismatch(overrides, cfg)
     72         LOGGER.info(f"{colorstr(option)} is not a valid key. Similar keys: {get_close_matches(option, cfg, 3, 0.6)}")
     73     if mismatched:
---> 74         sys.exit()
     75 
     76 

SystemExit:

### Environment

Google Colab Environment

### Minimal Reproducible Example

It was working earlier, but with the never version it is not working.

```
!pip install ultralytics

!yolo mode=Predict 
......

source=img_path, conf=0.25,return_outputs=True) 
#This line gives the error
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@pamudu123 you don't need returns_outputs anymore. We've updated it and made it much faster.
Here's the usage - https://docs.ultralytics.com/predict/

**Comment by leberert** [comment]
can we also get the prediction image from the result?

**Comment by AyushExel** [comment]
@leberert no its not possible right now but we might implement it in the near future. Thanks

**Comment by shersoni610** [comment]
Hello,

Some of the examples from Huggingfaces allows us to get  Boxes, classID, scale =  model(img, return_outputs=true).  Can it still be used in the latest version?

**Comment by AyushExel** [comment]
@shersoni610 can you provide links to such examples? The current usage is here https://docs.ultralytics.com/predict/ .
return_outputs=True is no longer needed

**Comment by jpinzonc** [comment]
@AyushExel I tried the new method and it is not returning outputs to the code, but to a text file, and I do not get .boxes, .mask, .prob from the predict. 

    results = model(frame, show = False, save =  True, save_txt = True, save_conf = True, name = 'test', conf = 0.40, verbose = False) 
    for r in results: 
        print('RRRRRRRR')
        print(r.boxes)
        print(r.masks )
        print(r.probs)

Is there something I am missing.

**Comment by AyushExel** [comment]
The above code isn't working ? Can you paste what error it's throwing

**Comment by jpinzonc** [comment]
I am not getting any errors. It runs and creates an image and a txt file

**Comment by dmddmd** [comment]
ultralytics versio 8.0.14 still gives 
None for `result.masks` and` result.probs`

**Comment by AyushExel** [comment]
> I am not getting any errors. It runs and creates an image and a txt file
> 
> This is the output: Results saved to runs/detect/pd2 13 labels saved to runs/detect/pd2/labels RRRRRRRR Ultralytics YOLO <class 'ultralytics.yolo.engine.results.Boxes'> masks type: <class 'torch.Tensor'> shape: torch.Size([1, 6]) dtype: torch.float32 None None

This is fixed the in the latest version please try again after upgrading

**Comment by AyushExel** [comment]
> ultralytics version 8.0.14 still gives None for `result.masks` and` result.probs` using the pretrained model yolov8n.pt . See also #201

This is expected behaviour
