### ISSUE TITLE
Tuning requires repeated user interaction

### ISSUE THREAD

**Issue by trnikon** [ultralytics/ultralytics#4865]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Evolution

### Bug

When tuning, if the user doesn't require wandb tracking of the experiment, they have to repeatedly select '(3) Don't visualize my results' after each training iteration finishes. There are ways around this like login in to wandb but a better user experience would be to remember user choices from the first selection. Here is a related issue: [https://github.com/ultralytics/yolov5/issues/5772](https://github.com/ultralytics/yolov5/issues/5772)

### Environment

YOLO: v8.0.175

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi thanks for letting us know about this problem. 

You can run 'yolo settings wandb=False' before starting. This should disable wandb logging from ultralytics.
