### ISSUE TITLE
How do I know how many instances were used in training with the YOLOv8 model?

### ISSUE THREAD

**Issue by LJM0213** [ultralytics/ultralytics#4868]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have datasets which have many instances in 1 image.

So, when I finished training, I can't know how many instances used in training.

**Comment by glenn-jocher** [comment]
@LJM0213 that's a great question! You're interested in knowing the total number of instances that the model has seen during training. When training with YOLOv8, the training process logs are printed to the console and saved to a `.txt` file in the `runs/train` directory which include key indicators of the training process.

There should be a line in the log that mentions the number of images and labels (or instances). The instance count shows the total number of instances that the model trained on, across all images in the dataset.

If you have already trained a model and have the logs from that training, you can find the information there. If not, you could start a new training run and check the console output or the log file to get this information. 

I hope this helps, and if you have further questions, don't hesitate to ask!
