### ISSUE TITLE
AttributeError: module 'torch.cuda' has no attribute 'OutOfMemoryError'

### ISSUE THREAD

**Issue by BoscoShin** [ultralytics/ultralytics#487]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi :)

i downloaded ultralytics using pip command. it's well

 but importing the ultralytics, i am getting this error in my anaconda CLI & jupyter notebook..

can you help me for this?

thank you

my torch version - 1. 10
my python version - 3.9

![image](https://user-images.githubusercontent.com/75238411/213365968-4a85badf-f04c-477e-963f-8ffd4ddc47d7.png)

![image](https://user-images.githubusercontent.com/75238411/213367934-28d2d7cd-511e-4eb6-ba4b-9a31d3148474.png)

**Comment by kalfazed** [comment]
Hello, from torch.cuda documentation(https://pytorch.org/docs/1.13/cuda.html), it seems that torch.cuda.OutOfMemoryError can only be found since torch version 1.13.

**Comment by BoscoShin** [comment]
> 
oh,,  for using yolov8 , do i need upgrading pytoch version 

thanks for reply!

**Comment by AyushExel** [comment]
@BoscoShin this is a bug, we'll fix it soon

**Comment by BoscoShin** [comment]
> @BoscoShin this is a bug, we'll fix it soon

@AyushExel okay. I'll wait until you fix it! thank you :)

**Comment by Robotatron** [comment]
Downgrade to 8.0.9 for the meantime
