### ISSUE TITLE
MobileSAM scores

### ISSUE THREAD

**Issue by sandratreneska7** [ultralytics/ultralytics#4878]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I get the confidence scores of masks generated by MobileSAM?

**Comment by glenn-jocher** [comment]
@sandratreneska7 hello,

To obtain the confidence scores of masks generated by MobileSAM in YOLOv8, you'll first need to perform a forward pass with your model on your input data. After computing the forward pass, the model will output a set of predictions. Each prediction consists of various pieces of information, including both the bounding box coordinates and a confidence score. 

For the output of MobileSAM, the confidence scores are included in the prediction results right after the bounding box coordinates. Those scores reflect the model's confidence that the detected object belongs to a specific class.

You can programmatically access these scores by parsing the model's output. Look for the indices corresponding to the confidence score in the prediction tensor. It should be part of the information returned for each detected object.

I hope this information is useful. Let us know if you need further clarification or assistance. Happy coding!

**Comment by Jordan-Pierce** [comment]
@Y-T-G do you have an answer to this? I can't seem to find a way to get the scores for any of the implemented SAM models (v1, v2, mobile, or fast). I see you can get it from the generate method, but I'm looking for scores for each individual prompt.

Also, this repo's implementation doesn't use multiple points in conjunction for the same object? It uses each point for a different object?

**Comment by Y-T-G** [comment]
@Jordan-Pierce The `conf` in `result.boxes` should correspond to the confidence of the masks.

**Comment by Y-T-G** [comment]
@Jordan-Pierce Multiple points for the same object should work, as long as it's one object at a time during inference. Not sure if it supports multiple points for multiple objects at the same time. The underlying code just uses SAM's `PromptEncoder` `model.model.prompt_encoder`.

**Comment by Y-T-G** [comment]
I guess it's due to this:

https://github.com/ultralytics/ultralytics/blob/bf51faeac592da6a6943dc369acba329d35c7dac/ultralytics/models/sam/predict.py#L245-L246

So it's expecting a single point per object.

**Comment by Jordan-Pierce** [comment]
@Y-T-G bummer, but I appreciate you double checking my work. Will switch back to original SAM and MobileSAM. @glenn-jocher perhaps we can add this as a future feature?

**Comment by Y-T-G** [comment]
@Jordan-Pierce https://github.com/ultralytics/ultralytics/pull/16643
