### ISSUE TITLE
How to set more number of trails in ray tuner

### ISSUE THREAD

**Issue by ashray21** [ultralytics/ultralytics#4881]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm using ray tuner of ultralytics to get the optimal values of hyperparameter of the model. When I run the run_ray_tune() function from ultralytics.utils.tuner by default it runs for 10 number of trials everytime. Following is the code I'm using

from ultralytics import YOLO
from ultralytics.utils.tuner import run_ray_tune

model = YOLO("yolov8n.pt")

run_ray_tune(model, data=yaml_path, grace_period=10)

How can I change the number of trails? 
Also what are the list of arguments I can pass in the run_ray_tune() function?

**Comment by glenn-jocher** [comment]
@ashray21 see https://docs.ultralytics.com/integrations/ray-tune/#usage for setting arguments like `iterations`

**Comment by glenn-jocher** [comment]
Added a reference to the Ray Tune docs in https://github.com/ultralytics/ultralytics/pull/4875/commits/a1748b8161e3a7071fa58f36d2dae1dfe602dc1f to help future users.
