### ISSUE TITLE
Object-Tracking yaml-files downloaded automatically?

### ISSUE THREAD

**Issue by jakobjung10** [ultralytics/ultralytics#4884]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Trying to track objects with botsort.yaml.
Unfortunately, it does not work.
Should the file "botsort.yaml" be downloaded automatically?
(as the yolo-config is downloaded automatically too...  self._Model = YOLO("yolov8n.pt"))
In my case, there is no "botsort.yaml" in my workspace.

`results = self._Model.track(frame, persist=True, verbose=True, conf=CONFIDENCE_THRESHOLD, tracker='botsort.yaml')
`

**Comment by glenn-jocher** [comment]
@jakobjung10 hello, thanks for reaching out with your question.

The "botsort.yaml" file should indeed be automatically downloaded when you run the `track` function, provided that it is available in the the repository. Generally, all required files for the functioning of Ultralytics YOLO models should be downloaded and available in your workspace upon initializing the model.

If the file is not getting downloaded automatically, there might be an issue with internet connectivity or file access permissions on your machine.

You might want to try re-running your process to see if it's a temporary issue. If the problem persists, it could be a bug that we need to look into. In that case, please provide additional details about your environment (operating system, Python version, etc.) and any error messages you are receiving. 

Hopefully we can get your tracking function working soon. Please let us know how you get on. Thank you for bringing this to our attention.
