### ISSUE TITLE
Load a model via torch.hub.load() throwing ultralytics import error

### ISSUE THREAD

**Issue by corey-dawson** [ultralytics/ultralytics#4888]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When trying to load a Yolov5 model with custom trained weights using the torch.hub.load() function, why is ultralytics throwing an import error?

<h3> Command </h3>

```python
model = torch.hub.load('ultralytics/yolov5', 'custom', path='/yolov5/runs/train/exp9/weights/best.pt', force_reload=True)
```

<h3> Exception </h3>

```shell
File ~/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py:33, in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     17 """Creates or loads a YOLOv5 model
     18 
     19 Arguments:
   (...)
     29     YOLOv5 model
     30 """
     31 from pathlib import Path
---> 33 from models.common import AutoShape, DetectMultiBackend
     34 from models.experimental import attempt_load
     35 from models.yolo import ClassificationModel, DetectionModel, SegmentationModel

File ~/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:38
     35     os.system('pip install -U ultralytics')
     36     import ultralytics
---> 38 from ultralytics.utils.plotting import Annotator, colors, save_one_box
     40 from utils import TryExcept
     41 from utils.dataloaders import exif_transpose, letterbox

File /opt/conda/lib/python3.10/site-packages/ultralytics/utils/__init__.py:25
     22 import yaml
     23 from tqdm import tqdm as tqdm_original
---> 25 from ultralytics import __version__
     27 # PyTorch Multi-GPU DDP Constants
     28 RANK = int(os.getenv('RANK', -1))

ImportError: cannot import name '__version__' from 'ultralytics' (unknown location)
```

I am running this in AWS Sagemaker using the Pytorch 2.0.0 Python 3.10 image. Here are the version of torch and ultralytics

torch: 2.0.0
ultralytics: 8.0.177

Any suggestions would be appreciated!

**Comment by glenn-jocher** [comment]
@corey-dawson great news 😃! Your original issue may now be resolved ✅ in PR #4891. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by xReniar** [comment]
@corey-dawson did you solved it?

**Comment by JulioZhao97** [comment]
same issue here

**Comment by glenn-jocher** [comment]
If you're encountering the same issue, please ensure your `torch` and `ultralytics` versions are compatible. Additionally, consider updating to the latest versions using `pip install --upgrade ultralytics` and `pip install torch --upgrade`. If the issue persists, providing a Minimum Reproducible Example (MRE) as outlined [here](https://docs.ultralytics.com/help/minimum-reproducible-example/) would help us assist you better.
