### ISSUE TITLE
model.track, can supervision read the results?

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/ultralytics#4893]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Frame by frame reading of the input video file.

I can iterate through results, for r in results: print(r) and some data is present, no detections in some cases, no mask, and track # id.

The same loop with model.predict vs model.track is ok.

Using supervision I am getting the following Error, am I missing a configuration parameter or track() argument?

```
for frame in container.decode(video=0):
    results = model.track(frame.to_image(), verbose=False, device=0, stream=True, show=False, persist=True)
    detections = sv.Detections.from_ultralytics(results)
```

Error:
lib/_venvlnx/lib/python3.11/site-packages/supervision/detection/core.py", line 259, in from_ultralytics
    xyxy=ultralytics_results.boxes.xyxy.cpu().numpy(),
         ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'generator' object has no attribute 'boxes'

**Comment by glenn-jocher** [comment]
@apiszcz hi there,

The error message you're seeing suggests that the output being passed to `sv.Detections.from_ultralytics()` is not what the function expects. The output provided by `model.track()` is a generator object, not a standard result with attributes like 'boxes'. 

The `model.track()` function offers real-time object tracking in video streams and its output is regularly updated as new frames are processed. Hence, it provides results as a Python generator which yield results one by one as they become available. The `model.predict()`, on the other hand, runs all the predictions at once and returns a full result set.

This is why you're seeing a discrepancy between the behavior of `model.track()` and `model.predict()`. 

Depending on what your needs are, you might have to process each tracking result separately as they are being generated, or consider using an alternative function such as `model.predict()`, which does provide results with 'boxes' attribute suitable for `sv.Detections.from_ultralytics()`. 

I hope this information helps!

Thanks,

Glenn

**Comment by apiszcz** [comment]
all set my error

supervision is great

**Comment by glenn-jocher** [comment]
@apiszcz hello,

I'm glad to hear that you could resolve your issue. Indeed, supervision is a powerful tool that greatly enhances the usability and functionality of YOLOv8.

If you have any more questions or run into any other issues, please don't hesitate to reach out. We're here to help.

Happy coding!

Best regards,
Glenn

**Comment by Abhijeet241093** [comment]
How you solve error ? 

Getting Same Error : 
AttributeError: 'generator' object has no attribute 'boxes'

![image](https://github.com/ultralytics/ultralytics/assets/38974232/5648f9a7-604f-449b-b01d-600a3f6da145)

**Comment by apiszcz** [comment]
in my case had inserted the result set into a another list, so it was my
mistake

**Comment by glenn-jocher** [comment]
@apiszcz hey there,

It looks like you found the root of the issue was nesting the result set inside another list by mistake. That's a pretty easy mistake to make and a good catch on your part! 👍

Just for clarity for anyone else who might encounter a similar error, when working with `model.track()` in YOLOv8, which returns a generator, you would typically process results using a loop like this:

```python
results = model.track(...)
for result in results:
    # Now you can access result.boxes and other attributes directly
```

If dealing with generators is new and somewhat confusing, it happens! The key takeaway is to remember how to iterate over the generated results correctly.

Happy tracking, and let us know if there’s anything else we can help with!
