### ISSUE TITLE
Hello experts, I have a question. Is there a specific order or pattern to the keypoints in YOLOv8's keypoint detection? I'm trying to understand how the names of the keypoints are determined.

### ISSUE THREAD

**Issue by zdj-1995** [ultralytics/ultralytics#4896]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a model that outputs three sets of coordinates, and I want to assign names to these three points. If there is a specific order to these points, I can hard-code them. I would like to understand how the underlying logic works. How do the experts typically approach this?

**Comment by zdj-1995** [comment]
I've gone through a lot of resources, but I haven't found any explanations on how the sorting and post-processing work in this context. Could someone provide some insights and clarification?

**Comment by zdj-1995** [comment]
xy: tensor([[[391.7563, 384.6177],
         [333.8856, 316.4843],
         [433.3235, 320.4894]]], device='cuda:0')At present, the model output consists of just three points. Is there any specific ordering or logic behind these points?

**Comment by zdj-1995** [comment]
I have discovered an issue, and it is closely related to the training you underwent.

**Comment by zdj-1995** [comment]
I have now resolved this issue, and it is actually strongly related to your training setup

**Comment by glenn-jocher** [comment]
@zdj-1995 that's great to hear that you have resolved your issue!

As for your question, the order of the keypoints in the output from the YOLOv8 model is indeed dependent on how you set up your training. 

When you create your dataset for training the model, the order in which you define and label the keypoints affects the output when making predictions with the trained model. The model will return the coordinates for each keypoint in the order they were defined during training. 

So, to assign names to these points, think back to your training process and remember in which order you labeled the keypoints. This should give you the ordering logic you're looking for.

Keep experimenting and don't hesitate to raise issues or questions. It's always a pleasure to see users actively working with the repo and the YOLOv8 model. It's thanks to contributions and insights like yours that we can continuously improve the models. Happy coding!
