### ISSUE TITLE
different result in different V8 code version

### ISSUE THREAD

**Issue by a773783082** [ultralytics/ultralytics#4897]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

On my owndataset, I found different results in different code version.
In ver8.0.160（first experiment code version）
```
Ultralytics YOLOv8.0.160 🚀 Python-3.9.1 torch-1.11.0+cu113 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)
YOLOv8m summary (fused): 218 layers, 25909240 parameters, 0 gradients, 79.1 GFLOPs
val: Scanning /workspace/TSD2023-2/test/labels... 3016 images, 0 backgrounds, 0 corrupt: 100%|██████████| 3016/3016 [00:01<00:00, 2300.02it/s]
val: New cache created: /workspace/TSD2023-2/test/labels.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 189/189 [00:56<00:00,  3.36it/s]
                   all       3016       8261      0.875      0.617      0.765      0.635
                     i       3016       1631      0.954      0.846      0.946      0.702
...
```

While, you said there is a bug(Classify) in ver8.0.160, so I changed to ver8.0.175.
```
Ultralytics YOLOv8.0.175 🚀 Python-3.9.1 torch-1.11.0+cu113 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)
YOLOv8m summary (fused): 218 layers, 25909240 parameters, 0 gradients, 79.1 GFLOPs
val: Scanning /workspace/TSD2023-2/test/labels... 3016 images, 0 backgrounds, 0 corrupt: 100%|██████████| 3016/3016 [00:01<00:00, 2173.05it/s]
val: New cache created: /workspace/TSD2023-2/test/labels.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 189/189 [01:28<00:00,  2.14it/s]
                   all       3016       8261      0.777      0.634      0.729      0.603
                     i       3016       1631      0.916      0.872      0.943      0.694
...
```
And then I try ver8.0.178(latest), result is same as ver8.0.175.
```
Ultralytics YOLOv8.0.178 🚀 Python-3.9.1 torch-1.11.0+cu113 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)
YOLOv8m summary (fused): 218 layers, 25909240 parameters, 0 gradients, 79.1 GFLOPs
val: Scanning /workspace/TSD2023-2/test/labels.cache... 3016 images, 0 backgrounds, 0 corrupt: 100%|██████████| 3016/3016 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 189/189 [01:06<00:00,  2.83it/s]
                   all       3016       8261      0.777      0.634      0.729      0.603
                     i       3016       1631      0.916      0.872      0.943      0.694
...
```

This is result on test dataset, while, in val is same. 
**I want to know why this happend, and which one is correct result?**

Thank you.

**Comment by a773783082** [comment]
I just used `model.predict()` to get detect results in different two versions(v8.0.160, v8.0.178). And I found the predicted results(`.txt`) are same in `v8.0.160` and `v8.0.178`. So I think there is some chanes in model.val() to compute the final metrics?

**Comment by glenn-jocher** [comment]
@a773783082 correct, the `model.predict()` function should yield the same output across different versions given that the model weights and input data remained the same.  

Differences in performance metrics across different Ultralytics YOLOv8 versions might come from updates or changes in the validation mechanics (`model.val()` function), as this step involves several processes like non-maxima suppression, objectness/confidence thresholding, and IOU thresholding that might affect the metrics calculation. 

Therefore it is possible that different versions of the software calculate performance metrics slightly differently, hence the discrepancy that you're observing. Do remember that the higher the version of Ultralytics YOLOv8, the more recent (and usually more accurate) the code is. 

I hope this helps to answer your question!
