### ISSUE TITLE
CPU is used even if GPU is specified

### ISSUE THREAD

**Issue by shoi0321soccer** [ultralytics/ultralytics#4904]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

YOLOv8 image classification. 

I tried the following two methods, but the GPU was not used and the CPU was used to predict.

①
`model = model.to(device)`

②
`results = model.predict(image_path, device=device)`

However, when executed in the CLI, the GPU was automatically used.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
@shoi0321soccer your issue can not be reproduced. I have used the mentioned code for testing (CPU and GPU device) the `predict` method of classification.

### For GPU
```
from ultralytics import YOLO
model = YOLO('yolov8n-cls.pt')
results = model(source="ultralytics\videos\classify-test.mp4", device=0)
```

The Inference speed with GPU average is ~8ms.
```

video 1/1 (1/680) ultralytics\videos\classify-test.mp4: 224x224 syringe 0.08, maze 0.04, safety_pin 0.03, 7.5ms
video 1/1 (2/680) ultralytics\videos\classify-test.mp4: 224x224 racer 0.11, greenhouse 0.03, cab 0.03, 9.5ms
video 1/1 (3/680) ultralytics\videos\classify-test.mp4: 224x224 racer 0.10, syringe 0.06, beer_bottle 0.03, 10.5ms
```

### For CPU
```
from ultralytics import YOLO
model = YOLO('yolov8n-cls.pt')
results = model(source="ultralytics\videos\classify-test.mp4", device="cpu")
```

The Inference speed with CPU average is ~18ms.
```

video 1/1 (1/680) ultralytics\videos\classify-test.mp4: 224x224 syringe 0.08, racer 0.07, safety_pin 0.03, 22.1ms
video 1/1 (2/680) ultralytics\videos\classify-test.mp4: 224x224 racer 0.11, syringe 0.06, lawn_mower 0.04, 14.5ms
video 1/1 (3/680) ultralytics\videos\classify-test.mp4: 224x224 racer 0.10, syringe 0.06, bobsled 0.03, 15.1ms
```

**Comment by glenn-jocher** [comment]
@shoi0321soccer @RizwanMunawar @AyushExel thanks for the bug report!

Currently devices must be passed directly to the predict method, passing the model to a device first does not suffice. We are working on updates to handle this better in the future, but for now the correct usage (and this is working correctly) is:

```python
from ultralytics import YOLO

# Create model
model = YOLO('yolov8n.pt')

# Run inference with device argument as 'cpu' or '0' etc.
results = model('path/to/source', device='cpu')
```
