### ISSUE TITLE
Disable Progress Bar in Python Training

### ISSUE THREAD

**Issue by BradyJ27** [ultralytics/ultralytics#4906]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When using the Python API to train (`model.train(**arguments)`) within a Gitlab ci job, the progress bar of training fills up the Gitlab logs extremely quickly because Gitlab ci doesn't support progress bars in the raw outputs. Is there any way to disable the progress bar and just print once or twice per epoch? Something like "epoch 1/100 started." Then "epoch 2/100 completed".

Or is there any other way to decrease the amount of logging? 

Thanks!

**Comment by BradyJ27** [comment]
> @BradyJ27 there's the global verbose env variable you could use to disable console outputs, i.e. but there is no TQDM specific variable you can set. If you pair this with a logging tool like Comet or Ultralytics HUB then perhaps that might work for your use case.
> 
> ```
> YOLO_VERBOSE=False yolo train 
> ```

Hi @glenn-jocher , does this flag work with the Python API? I have set the environment variable to false and Yolo is still logging the same amount.

**Comment by glenn-jocher** [comment]
Yes of course. Just define it before you run your command, i.e.

```
os.environ['YOLO_VERBOSE'] = 'false'

from ultralytics import YOLO

# do you thing...
```

**Comment by BradyJ27** [comment]
> Yes of course. Just define it before you run your command, i.e.
> 
> ```python
> os.environ['YOLO_VERBOSE'] = 'false'
> 
> from ultralytics import YOLO
> 
> # do your thing...
> ```

This doesn't seem to be working for me. I've set verbose to false both in the environment and the argument being passed to the python function. I've also attempted to set stdout to devnull before training in Python (`sys.stdout = open(os.devnull, 'w')`). This may have something to do with how Gitlab ci handles their output?

**Comment by glenn-jocher** [comment]
@BradyJ27 I see you are still having issues, apologies for the inconvenience. The `YOLO_VERBOSE` flag should in theory reduce the logging done during training. However, it's possible that the GitLab CI environment handles stdout differently, which could be preventing the flag from fully suppressing the logs.

I understand it would be ideal to have more granular control over logging such as the ability to suppress the progress bar but print the start and end of each epoch. Unfortunately, at present, we do not have a specific setting or flag in our repository to do this.

However, your feedback is valuable, and I'll raise this issue with our development team. We're always looking to improve and this could indeed be a useful feature to add in future updates. Thank you for bringing it to my attention.

**Comment by glenn-jocher** [comment]
@BradyJ27 another possibility is your `ultralytics` package may be out of date, try updating with `pip install -U ultralytics`

**Comment by glenn-jocher** [comment]
@BradyJ27 That's great to hear that the output you were mentioning about the training progress is no longer there after updating the `ultralytics` package! As for the progress display during the model download, that is generally useful to many users as it informs them about the download status. In the context of CI, it may not be absolutely necessary, but it's hardwired and is not silenced by the `YOLO_VERBOSE` flag. We appreciate your feedback and we'll take it into account for future updates.

**Comment by BradyJ27** [comment]
For future viewers: redirecting stdout AND stderr ended up working best for me. This way I still have access to the training logs after the fact and can have all of the verbose info. It would look something like this:

`yolo train etc. &> train.log` 

Closing issue as I've found a workaround, but additional logging options in the future would be beneficial, especially for CI pipelines.

**Comment by glenn-jocher** [comment]
@BradyJ27, I'm glad you found a workaround that suits your needs by redirecting stdout and stderr to a log file. Your feedback regarding more granular control over logging is well noted. We agree that such added functionality could be beneficial for workflows like CI pipelines. Your insights are valuable in helping improve YOLOv8. Thank you for sharing your solution. We'll keep this in mind as we continue to enhance our logging features.
