### ISSUE TITLE
Set all the other loss to 0.

### ISSUE THREAD

**Issue by Miroun** [ultralytics/ultralytics#4912]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

It might be a strange question but since I am sing the segment model, I do not understand why I am getting the graphs about the box_loss, cls_loss or dfl_loss.
Moreover, I've seen in here :https://docs.ultralytics.com/usage/cfg/#train 
that it is possible to put a specific weight on a specific loss but I did not find seg_loss. Finally, do you think it is not a good idea to set all the loss except seg to 0 ?

Kind regards,

**Comment by glenn-jocher** [comment]
@Miroun hello,

Great question! The segmentation model you are using falls under the YOLOv8 architecture, which is inherently a detection model. Thus, even when training for tasks like semantic segmentation, you may still see losses such as box_loss, cls_loss and obj_loss. These are generated from the YOLOv8 architecture working to run the detection task in parallel.

As for weighting the losses, the YOLOv8 configuration does indeed have the feature to adjust loss weights for the object detection task. However, the seg_loss you are looking for is related to the segmentation task.

With regards to setting all other loss except seg_loss to zero, it isn't exactly suggested. By setting these loss weights to 0, you are practically ignoring the detection part of your model, which might not be beneficial given how the YOLOv8 architecture is built. If the focus of your project is on segmentation, then you likely want segmentation loss to have a larger weight, but not at the expense of completely ignoring the other aspects of the model.

Hope this helps, let me know if you have any other questions! YOLOv8's versatility with different computer vision tasks and the adaptability of the loss weights are features we're definitely proud of at Ultralytics.

Best regards,
