### ISSUE TITLE
Multi-process calls and the model cannot start training

### ISSUE THREAD

**Issue by mumusanren** [ultralytics/ultralytics#4915]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I'm trying to write a application based on yolov8 and django, deploying the application on an x86 host in ubuntu 22.04 where the GPU is an RTX3060. 

The class containing the yolov8 training is called via multiprocessing to start model training, and after the model is loaded, the process stays stuck and does not start model training. 
![1694740904247](https://github.com/ultralytics/ultralytics/assets/83314953/32728d98-5e7b-4b6e-9b44-a977afadb34c)

I think ultralytics is causing the program to get stuck when it doesn't have permissions to access any files, but I don't know exactly which ones. 

Looking forward to your answers. Thanks.

### Environment

- YOLO: Ultralytics YOLOv8.0.21 🚀 Python-3.8.10 torch-1.13.1+cu117 CUDA:0 (A100-SXM-80GB, 81251MiB)
- OS: Ubuntu 22.04
- Python: 3.10.12

### Minimal Reproducible Example

#-----------./application/webserver/views.py----django interfaces----------#
import multiprocessing
from web_server.train.train import Trainer
from web_server.utils.create_files import check_data_path
# Create your views here.
work_path = os.getcwd()

# train_treading = None
train_process = None

def get_train_task_info(request):
    # global trainprocess
    global train_process
    med = request.method
    error_data = {
        "msg": "err",
        "code": "111111"
    }
    success_data = {
        "msg": "ok",
        "code": "000000"
    }
    if med == "GET":
        task_id = request.GET.get("task_id") 
        algorithm_category = request.GET.get("algorithm_category") 
        dataset_path = request.GET.get("dataset_path") 
        model_accuracy = request.GET.get("model_accuracy")
        train_weight_use = request.GET.get("train_weight_use")
        train_weight_path = request.GET.get("train_weight_path")
        epochs_setting = request.GET.get("epochs_setting")
        optimizer_setting = request.GET.get("optimizer_setting")
        cos_lr_use = request.GET.get("cos_lr_use")
        # train_label_list = request.GET.get("train_label_list")
        # train_label_list = train_label_list.split('-')
        result = generate_data_yaml(dataset_path, algorithm_category)
        resume = False
        if result:
            trainer = Trainer('process_'+str(task_id), int(algorithm_category), int(train_weight_use), train_weight_path, int(model_accuracy),
                                   int(epochs_setting), optimizer_setting, int(cos_lr_use), resume)

            train_process = multiprocessing.Process(target=trainer.process)
            train_process.start()
            # train_treading = threading.Thread(target=trainer.process)
            # train_treading.start()
        else:
            return JsonResponse(error_data)
        return JsonResponse(success_data)
    else:
        return JsonResponse(error_data)

#-------------------./application/webserver/train/train.py----------YOLOv8 class----------------------------------#
from ultralytics import YOLO
import time
from tqdm import tqdm
import os
import csv
import shutil
import math
os.environ["WANDB_API_KEY"] = '+++++++++++' 
os.environ["WANDB_MODE"] = "offline"  

work_path = os.getcwd()
root_path = work_path + "\\web_server\\train"
# root_path = work_path

model_name_list = ["yolov8l.pt", "yolov8m.pt", "yolov8s.pt", "yolov8l-seg.pt", "yolov8m-seg.pt",
              "yolov8s-seg.pt", "yolov8l-cls.pt", "yolov8m-cls.pt", "yolov8s-cls.pt"]

model_structure_list = ["yolov8l.yaml", "yolov8m.yaml", "yolov8s.yaml", "yolov8l-seg.yaml", "yolov8m-seg.yaml",
              "yolov8s-seg.yaml", "yolov8l-cls.yaml", "yolov8m-cls.yaml", "yolov8s-cls.yaml"]

for i in tqdm(range(100)):
    time.sleep(0.01)

class Trainer:
    def __init__(self, project_name, algorithm_category, train_weight_use, train_weight_path, model_accuracy, epochs_nums, optimizer, cos_lr_use, resume):
        if resume == False:
            algorithm_name = ""
            if algorithm_category == 0:
                algorithm_name = "detect"
            elif algorithm_category == 1:
                algorithm_name = "segment"
            elif algorithm_category == 2:
                algorithm_name = "classify"
            data_file = root_path + "/data/" + str(algorithm_name) + ".yaml"

            cos_lr = False if cos_lr_use == 0 else True

            # Load a model
            model_idx = int(algorithm_category * 3 + model_accuracy)
            model_path = ""
            if train_weight_use == 0:
                model_path = train_weight_path
            elif train_weight_use == 1:
                model_name = model_name_list[model_idx]
                model_path = root_path + "/weights/" + model_name
            model_structure = model_structure_list[model_idx]
            model_structure_path = root_path + "/models/v8/" + model_structure
            print("model_idx-------------", model_idx)
            print("train_weight_use-------------", train_weight_use)
            print("model_path--------------", model_path)
            self.model = YOLO(model_path)
            # self.model = YOLO(model_structure_path).load(model_path)

            self.args = {
                    'task': algorithm_name,
                    'data': data_file, 
                    'epochs': epochs_nums, 
                    'patience': 50, 
                    'batch': 4, 
                    'imgsz': 640,
                    'save': True,
                    'save_period': -1,
                    'cache': True, 
                    'device': 0,
                    'workers': 0, 
                    'project': project_name, 
                    'name': 'exp', 
                    'exist_ok': False,
                    'pretrained': True, 
                    'optimizer': optimizer, 
                    'verbose': True,
                    'seed': 0, 
                    'cos_lr': cos_lr
                    }
        else:
            self.model = YOLO(train_weight_path)
            self.args = {'resume': True}

    def process(self):
        # Train the model
        self.model.train(**self.args)

if __name__ == '__main__':
    # There is no problem with using the main process directly to carry out training
    # change root_path = work_path
    trainer = Trainer('process_1', 0, 1, "", 1, 1, "auto", 1, False)
    trainer.process()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Thank you for the detailed bug report. The issue seems to be related to how the Ultralytics YOLOv8 training process is initiated from a Django view using Python's multiprocessing. This is a very specific setup that can have multiple sources of issues, including permission issues and resource locking.

Here are some things to consider:

1. **File Permissions**: Make sure the directory where YOLO will be writing (e.g., saving checkpoints, logging, etc.) has the right permissions.

2. **Multiprocessing**: Check if you need to set the multiprocessing start method appropriately, especially on Unix systems. Try setting `multiprocessing.set_start_method('spawn')` at the beginning of your script.

3. **Debugging**: If possible, try to print the internal logs from the YOLOv8 training process to diagnose where it's getting stuck.

4. **Environment**: Your setup environment seems adequate, but just to be sure, ensure you are not running out of memory or hitting any system-level limits (e.g., open files, processes).

5. **Asynchronous Task Queues**: You may want to consider using an asynchronous task queue like Celery for running long-running background tasks instead of multiprocessing directly from Django views.

Here is how you could refactor `get_train_task_info` to include some debugging prints, ensuring the working directory and checking for folder permissions. This is just an example and should be adapted to your code:

```python
from pathlib import Path
import os

def get_train_task_info(request):
    global train_process
    
    work_path = Path.cwd()
    print(f"Current work directory: {work_path}")

    try:
        os.makedirs(work_path / 'your_yolo_folder', exist_ok=True)
    except PermissionError:
        print("No permission to create folder")
        return JsonResponse({"msg": "err", "code": "111111"})
    
    # Your existing code here...
    if result:
        print("About to start the training process")
        trainer = Trainer(...)
        train_process = multiprocessing.Process(target=trainer.process)
        train_process.start()
        print("Training process started")
        # ... rest of your code
```

This code uses Python's `pathlib` package to work with paths, as per your specifications. It also adds some debugging print statements to help diagnose where the process might be getting stuck. Make sure to check your server logs to see these outputs.

If you find out that it's a specific Ultralytics YOLOv8 issue, it would be helpful to submit a bug report on the GitHub repository.
