### ISSUE TITLE
How can i set multi-scale training mode?

### ISSUE THREAD

**Issue by lion-ops** [ultralytics/ultralytics#4921]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I set imgsz=640, image scale=0.5，but i find the training imgsz is still 640, which is not multi-scale.

**Comment by glenn-jocher** [comment]
@lion-ops hello, thanks for bringing up this query on multi-scale training.

Within YOLOv8, the `imgsz` parameter you mentioned sets the square training image size (e.g., 640 for 640x640). While `imgsz` does set the size of the images, it's not directly involved with multi-scale training.

In the case of multi-scale training, YOLOv8 periodically adjusts the size of images during training to generate bounding boxes of varying sizes which helps the model generalize better. The image scale setting isn't a direct control for multi-scale changes. This variation is governed by the multi-scale training mode settings.

The YOLOv8 implementation does support multi-scale training. Kindly revisit your setup and confirm that multi-scale training is enabled properly. The default behavior should handle scaling appropriately based on the configuration you have set.

If the issue persists, please provide more details about your training setup and how it is that you're concluding the image sizes aren't changing appropriately, so we can assist you better in troubleshooting.

Don't hesitate to ask if you need more clarification!
