### ISSUE TITLE
lossing video stream source when cmaera's fps is less then 25fps

### ISSUE THREAD

**Issue by MoussaGRICHE** [ultralytics/ultralytics#4922]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Hello,

I had a problem with yolo.predict when I use rtsp video when th camera's fps is less then 25fps.

when camera's fps=25, there is no problem.
when camera's fps=20, I got WARNING  Waiting for stream 0
when camera's fps=18, I got WARNING  Waiting for stream 0

predictions = model.track(source=rtsp_url, stream=True, tracker="./track_cfg.yaml")

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MoussaGRICHE this has been resolved a couple releases ago. Please update with `pip install -U ultralytics`
