### ISSUE TITLE
Add the possibility to customize logging format

### ISSUE THREAD

**Issue by SadmiB** [ultralytics/ultralytics#4923]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

when using some logging tools we may need to have one logging format to interpret logs correctly, when checking ultralytics code the logging format is predefined and can't be changed.

### Use case

For example: shipping logs to datadog

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@SadmiB if none of the default loggers works for you we've made it super easy to create your own custom logger also. Just follow the examples here for the existing loggers and create your own to do anything you want:
https://github.com/ultralytics/ultralytics/tree/main/ultralytics/utils/callbacks

**Comment by SadmiB** [comment]
@glenn-jocher This looks like enabling to log extra information, but in my case, I wanted to override the logging format of the LOGGER which is setup here https://github.com/ultralytics/ultralytics/blob/e7401f5872ec0eca6239474a6f3afbd85753fb9d/ultralytics/utils/__init__.py#L224

**Comment by glenn-jocher** [comment]
Hi @SadmiB,

In YOLOv8, the logging format is initially set in the utils/__init__.py as you've pointed out. The current logging configuration in the repository is designed to provide a general solution for the majority of users. While it's not currently designed for custom format specifications, your request is a valid one.

Allowing customization of the logging format could be a valuable feature for other users as well, especially in applications where logs need to be interpreted by external systems or services.

I encourage you to make a pull request for this feature, as it will be an excellent addition to real-world applications and use-cases. When creating your pull request, please provide a clear explanation of your changes and how they can benefit other users. This will help us expedite the process of reviewing, testing and potentially merging your update into the codebase.

Thank you for your proactive approach towards improving YOLOv8! The community will undoubtedly benefit from your work.
