### ISSUE TITLE
Using YoloV8 with Torchserve

### ISSUE THREAD

**Issue by Krokha18** [ultralytics/ultralytics#493]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I think guide for using YoloV8 with Torchserve will be very useful. Just provide minimal example how to write a handler for YoloV8 (it was simpler to do with YoloV5, but about V8 i feel a bit confused).

### Use case

Guide can be used for deploying YoloV8 models with Torchserve

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by jarutis** [comment]
I have this gist which might be useful. https://gist.github.com/jarutis/f57a3db7b4c37b59163a2ff5d8c8d54e

**Comment by glenn-jocher** [comment]
@jarutis thanks for the example!

**Comment by Chappie74** [comment]
@glenn-jocher did you get it to work?

I used the ultralytics converter to make the yolov8m.torchscript model. 

ran the archiver like so
```
torch-model-archiver --model-name yolov8m --version 1.0 --serialized-file yolov8m.torchscript --handler handler.py --extra-files index_to_name.json  -f
```

but no luck , for some reason its not able to load the weights.

![image](https://user-images.githubusercontent.com/21108487/227751973-64091223-9307-4faf-b187-26641af52b43.png)

**Comment by glenn-jocher** [comment]
@Chappie74 no, I haven't used torchserve myself before, sorry.

**Comment by kaangoksal** [comment]
If anyone else is trying this, here is my short guide on how to do it, first export the weights as torchscript 

`yolo export model=yolov8x.pt format=torchscript`

second, archive the model, HOWEVER, we need rename the `yolov8x.torchscript` to `yolov8x_torch.pt` due to above issue.

`torch-model-archiver --model-name yolov8x --version 1.0 --serialized-file yolov8x_torch.pt --handler handler.py --extra-files index_to_name.json -f`

this will give you a mar file.   

Launch a torch serve container like this 

```
docker run --rm -it --gpus all \
-e MODEL_LIST="yolov8x=yolov8x.mar" \
-v ./src/models:/home/model-server/model-store \
-p 127.0.0.1:8080:8080 \
-p 127.0.0.1:8081:8081 \
-p 127.0.0.1:8082:8082 \
--entrypoint /bin/bash \
pytorch/torchserve:latest-gpu
```
execute this 

`torchserve --start --model-store model-store --models yolov8x=/models/yolov8x.mar --foreground --no-config-snapshots`

check the loaded models with this get api

`GET localhost:8081/models`

You can send a predcition like this 

`curl http://localhost:8080/predictions/yolov8x -T test_data/photo.jpg`

however, at the moment its failing for me with the following error

```
2023-10-30T01:13:09,252 [INFO ] W-9000-yolov8x2_1.0-stdout MODEL_LOG - Backend received inference at: 1698628389
2023-10-30T01:13:09,617 [INFO ] W-9000-yolov8x2_1.0-stdout MODEL_LOG - Invoking custom service failed.
2023-10-30T01:13:09,617 [INFO ] W-9000-yolov8x2_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2023-10-30T01:13:09,617 [INFO ] W-9000-yolov8x2_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/service.py", line 134, in predict
2023-10-30T01:13:09,618 [INFO ] W-9000-yolov8x2_1.0-stdout MODEL_LOG -     ret = self._entry_point(input_batch, self.context)
2023-10-30T01:13:09,618 [INFO ] W-9000-yolov8x2_1.0 ACCESS_LOG - /172.17.0.1:37286 "POST /predictions/yolov8x2 HTTP/1.1" 503 368
2023-10-30T01:13:09,618 [INFO ] W-9000-yolov8x2_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/torch_handler/base_handler.py", line 359, in handle
2023-10-30T01:13:09,618 [INFO ] W-9000-yolov8x2_1.0 TS_METRICS - Requests5XX.Count:1.0|#Level:Host|#hostname:bbab94b4716b,timestamp:1698628389
2023-10-30T01:13:09,618 [INFO ] W-9000-yolov8x2_1.0-stdout MODEL_LOG -     output = self.postprocess(output)
2023-10-30T01:13:09,618 [INFO ] W-9000-yolov8x2_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/f62c7875ebe740bf995013c4eccda674/handler.py", line 71, in postprocess
2023-10-30T01:13:09,618 [DEBUG] W-9000-yolov8x2_1.0 org.pytorch.serve.job.Job - Waiting time ns: 72346, Inference time ns: 367242637
2023-10-30T01:13:09,618 [INFO ] W-9000-yolov8x2_1.0-stdout MODEL_LOG -     outputs = np.array([cv2.transpose(inference_output[0].numpy())])
2023-10-30T01:13:09,618 [DEBUG] W-9000-yolov8x2_1.0 org.pytorch.serve.wlm.WorkerThread - sent a reply, jobdone: true
2023-10-30T01:13:09,618 [INFO ] W-9000-yolov8x2_1.0-stdout MODEL_LOG - TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
2023-10-30T01:13:09,618 [INFO ] W-9000-yolov8x2_1.0 org.pytorch.serve.wlm.WorkerThread - Backend response time: 366
2023-10-30T01:13:09,618 [INFO ] W-9000-yolov8x2_1.0 TS_METRICS - WorkerThreadTime.Milliseconds:1.0|#Level:Host|#hostname:bbab94b4716b,timestamp:1698628389
```

I'll update this as i discover more

**Comment by glenn-jocher** [comment]
@kaangoksal great work, and thank you for sharing your guide with the community! Your steps are a good starting point to using YOLOv8 with TorchServe. 

The issues you were seeing are primarily due to running operations on a tensor that's on a GPU device. PyTorch tensors need to be moved to the cpu before they can be converted to numpy arrays.

Updating to use `.cpu().numpy()` does exactly that - it moves the tensor to cpu first and then converts to a numpy array. Your change in the output return seems to be catering to the specific output format that your application or service might be expecting from the model.

Your offer to write additional documentation is appreciated, as it will definitely benefit others trying to use YOLOv8 with TorchServe. Please feel free to share any further developments or discoveries. That kind of collaborative approach is what makes open-source communities thrive.

Keep up the good work with your experiments!

**Comment by TimTreurniet** [comment]
@kaangoksal If you managed to create a final working handler script, I would love to see it!

**Comment by belapyc** [comment]
Hi, I am trying to run as you suggested @kaangoksal. And it seems from Docker log that the predictions are made, however the curl returns 
```
{
  "code": 503,
  "type": "InternalServerException",
  "message": "number of batch response mismatched"
}
```.

I've tried playing around with handler and how it returns detections in postprocess but it seems it doesn't change anything. Even if I completely comment out the `postprocess()` it runs with the same error.

**Comment by kaangoksal** [comment]
I will reply, going through some life events rn. Will help everyone

**Comment by glenn-jocher** [comment]
Take the time you need, @kaangoksal. Life events always come first. We'll be here when you're ready to share your insights. Stay strong! 💪

**Comment by kaangoksal** [comment]
```python
"""Custom TorchServe model handler for YOLOv8 models.
"""
from ts.torch_handler.base_handler import BaseHandler
import numpy as np
import base64
import torch
import torchvision.transforms as tf
import io
from PIL import Image
import cv2


class ModelHandler(BaseHandler):
    """
    Model handler for YoloV8 bounding box model
    """

    img_size = 640
    """Image size (px). Images will be resized to this resolution before inference.
    """

    def __init__(self):
        # call superclass initializer
        super().__init__()

    def preprocess(self, data):
        """Converts input images to float tensors.

        Args:
            data (List): Input data from the request in the form of a list of image tensors.

        Returns:
            Tensor: single Tensor of shape [BATCH_SIZE, 3, IMG_SIZE, IMG_SIZE]
        """
        images = []

        transform = tf.Compose([
            tf.ToTensor(),
            tf.Resize((self.img_size, self.img_size))
        ])

        # handle if images are given in base64, etc.
        for row in data:
            # Compat layer: normally the envelope should just return the data
            # directly, but older versions of Torchserve didn't have envelope.
            image = row.get("data") or row.get("body")
            if isinstance(image, str):
                # if the image is a string of bytesarray.
                image = base64.b64decode(image)

            # If the image is sent as bytesarray
            if isinstance(image, (bytearray, bytes)):
                image = Image.open(io.BytesIO(image))
            else:
                # if the image is a list
                image = torch.FloatTensor(image)

            # force convert to tensor
            # and resize to [img_size, img_size]
            image = transform(image)

            images.append(image)

        # convert list of equal-size tensors to single stacked tensor
        # has shape BATCH_SIZE x 3 x IMG_SIZE x IMG_SIZE
        images_tensor = torch.stack(images).to(self.device)

        return images_tensor

    def postprocess(self, inference_output):
        is_old_cv = cv2.__version__ == '4.5.0' # for jetson nano compability....

        outputs = np.array([cv2.transpose(inference_output[0].cpu().numpy())])
        rows = outputs.shape[1]

        boxes = []
        scores = []
        class_ids = []

        for i in range(rows):
            classes_scores = outputs[0][i][4:]
            (minScore, maxScore, minClassLoc, (x, maxClassIndex)) = cv2.minMaxLoc(classes_scores)
            if maxScore >= 0.25:
                box = [
                    outputs[0][i][0] - (0.5 * outputs[0][i][2]),
                    outputs[0][i][1] - (0.5 * outputs[0][i][3]),
                    outputs[0][i][2], outputs[0][i][3]
                ]
                boxes.append(box)
                scores.append(maxScore)
                class_ids.append(maxClassIndex)

        if is_old_cv:
            integer_array = [[int(num) for num in inner_list] for inner_list in boxes]
            boxes = integer_array

        print(f"Boxes {boxes} {type(boxes)}")
        print(f"scores {scores} {type(scores)}")

        result_boxes = cv2.dnn.NMSBoxes(boxes, scores, 0.25, 0.45, 0.5)

        print(f"result_boxes {result_boxes}, {type(result_boxes)}")

        if is_old_cv:
            result_boxes = result_boxes.flatten()

        detections = []
        for i in range(len(result_boxes)):
            index = result_boxes[i]
            box = boxes[index]
            print(f"box {box}")

            if is_old_cv:
                box_ref = box
            else:
                box_ref = [c.item() for c in box],

            detection = {
                'class_id': class_ids[index],
                'class_name': self.mapping[str(class_ids[index])],
                'confidence': scores[index],
                'box': box_ref,
                'scale': self.img_size / 640}
            print(detection)
            detections.append(detection)

        # format each detection
        return [{'result': detections}]
```

**Comment by kaangoksal** [comment]
install the nvidia toolkit for docker
```bash
# Add nvidia repository
curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
  && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list \
  && \
    sudo apt-get update

# this is the toolkit
sudo apt-get install -y nvidia-container-toolkit
# configure docker with nvidia runtime
sudo nvidia-ctk runtime configure --runtime=docker
sudo systemctl restart docker
# configure the containerd, which I don't know whether we use with docker
sudo nvidia-ctk runtime configure --runtime=containerd
sudo systemctl restart containerd

# you should see nvidia in here. Like this `Runtimes: nvidia runc io.containerd.runc.v2`
docker info | grep -i runtime
```

**Comment by kaangoksal** [comment]
Sorry for posting bits like this, if there is more interest, i can do a pr to the repo if you let me know where would this content fit in

**Comment by glenn-jocher** [comment]
No worries, @kaangoksal. Your contributions are valuable to the community. If you're interested in creating a PR, you might consider adding a new section in the documentation specifically for deployment, which could include your guide on using YOLOv8 with TorchServe. This would be a great addition to our existing docs. Thanks for your initiative! 🚀

**Comment by hungtrieu07** [comment]
> ```python
> """Custom TorchServe model handler for YOLOv8 models.
> """
> from ts.torch_handler.base_handler import BaseHandler
> import numpy as np
> import base64
> import torch
> import torchvision.transforms as tf
> import io
> from PIL import Image
> import cv2
> 
> 
> class ModelHandler(BaseHandler):
>     """
>     Model handler for YoloV8 bounding box model
>     """
> 
>     img_size = 640
>     """Image size (px). Images will be resized to this resolution before inference.
>     """
> 
>     def __init__(self):
>         # call superclass initializer
>         super().__init__()
> 
>     def preprocess(self, data):
>         """Converts input images to float tensors.
> 
>         Args:
>             data (List): Input data from the request in the form of a list of image tensors.
> 
>         Returns:
>             Tensor: single Tensor of shape [BATCH_SIZE, 3, IMG_SIZE, IMG_SIZE]
>         """
>         images = []
> 
>         transform = tf.Compose([
>             tf.ToTensor(),
>             tf.Resize((self.img_size, self.img_size))
>         ])
> 
>         # handle if images are given in base64, etc.
>         for row in data:
>             # Compat layer: normally the envelope should just return the data
>             # directly, but older versions of Torchserve didn't have envelope.
>             image = row.get("data") or row.get("body")
>             if isinstance(image, str):
>                 # if the image is a string of bytesarray.
>                 image = base64.b64decode(image)
> 
>             # If the image is sent as bytesarray
>             if isinstance(image, (bytearray, bytes)):
>                 image = Image.open(io.BytesIO(image))
>             else:
>                 # if the image is a list
>                 image = torch.FloatTensor(image)
> 
>             # force convert to tensor
>             # and resize to [img_size, img_size]
>             image = transform(image)
> 
>             images.append(image)
> 
>         # convert list of equal-size tensors to single stacked tensor
>         # has shape BATCH_SIZE x 3 x IMG_SIZE x IMG_SIZE
>         images_tensor = torch.stack(images).to(self.device)
> 
>         return images_tensor
> 
>     def postprocess(self, inference_output):
>         is_old_cv = cv2.__version__ == '4.5.0' # for jetson nano compability....
> 
>         outputs = np.array([cv2.transpose(inference_output[0].cpu().numpy())])
>         rows = outputs.shape[1]
> 
>         boxes = []
>         scores = []
>         class_ids = []
> 
>         for i in range(rows):
>             classes_scores = outputs[0][i][4:]
>             (minScore, maxScore, minClassLoc, (x, maxClassIndex)) = cv2.minMaxLoc(classes_scores)
>             if maxScore >= 0.25:
>                 box = [
>                     outputs[0][i][0] - (0.5 * outputs[0][i][2]),
>                     outputs[0][i][1] - (0.5 * outputs[0][i][3]),
>                     outputs[0][i][2], outputs[0][i][3]
>                 ]
>                 boxes.append(box)
>                 scores.append(maxScore)
>                 class_ids.append(maxClassIndex)
> 
>         if is_old_cv:
>             integer_array = [[int(num) for num in inner_list] for inner_list in boxes]
>             boxes = integer_array
> 
>         print(f"Boxes {boxes} {type(boxes)}")
>         print(f"scores {scores} {type(scores)}")
> 
>         result_boxes = cv2.dnn.NMSBoxes(boxes, scores, 0.25, 0.45, 0.5)
> 
>         print(f"result_boxes {result_boxes}, {type(result_boxes)}")
> 
>         if is_old_cv:
>             result_boxes = result_boxes.flatten()
> 
>         detections = []
>         for i in range(len(result_boxes)):
>             index = result_boxes[i]
>             box = boxes[index]
>             print(f"box {box}")
> 
>             if is_old_cv:
>                 box_ref = box
>             else:
>                 box_ref = [c.item() for c in box],
> 
>             detection = {
>                 'class_id': class_ids[index],
>                 'class_name': self.mapping[str(class_ids[index])],
>                 'confidence': scores[index],
>                 'box': box_ref,
>                 'scale': self.img_size / 640}
>             print(detection)
>             detections.append(detection)
> 
>         # format each detection
>         return [{'result': detections}]
> ```

Hi @kaangoksal , I have a question: I have a ONNX model and was written a custom handler with that, but I'm confused with post-process output. Can I use your post-process function above?
