### ISSUE TITLE
mlflow on_pretrain_routine_end fails if the experiment name does not exist

### ISSUE THREAD

**Issue by Gornoka** [ultralytics/ultralytics#4930]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

code causing the bug https://github.com/ultralytics/ultralytics/blob/e7401f5872ec0eca6239474a6f3afbd85753fb9d/ultralytics/utils/callbacks/mlflow.py#L33
````python
       experiment_name = os.environ.get('MLFLOW_EXPERIMENT_NAME') or trainer.args.project or '/Shared/YOLOv8'
        run_name = os.environ.get('MLFLOW_RUN') or trainer.args.name
        experiment = mlflow.get_experiment_by_name(experiment_name)
        if experiment is None:
            mlflow.create_experiment(experiment_name)
        mlflow.set_experiment(experiment_name)

        prefix = colorstr('MLFlow: ')
        try:
            run, active_run = mlflow, mlflow.active_run()
            if not active_run:
                active_run = mlflow.start_run(experiment_id=experiment.experiment_id, run_name=run_name)
````
`if experiment is None` block does not reset it to a value, resulting in an Attribute error if that was the case.

changing it to the following will fix the bug, as mlflow now does the automatic creation internally (presumably since mlflow 2.0)
````python
experiment = mlflow.set_experiment(experiment_name)
````
There are other things broken with the MLFLOW-related callbacks.
Would you be interested in a PR fixing that for recent versions of mlflow, or do you plan to drop the support for it entirely?
(I am just wondering since it is not part of your official Documentation)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Gornoka yes please submit a PR with MLFlow fixes. I don't use it myself so I haven't been able to tell if it's working correctly or not.

**Comment by Gornoka** [comment]
I have found weird behaviour, with Uploding metrics on Linux, do you happen to be aware of anything OS-dependent in the implementation of callback handling during training or any ideas where you would expect something like that?

**Comment by glenn-jocher** [comment]
@Gornoka hello, thank you for bringing this to our attention. In the Ultralytics YOLOv8 implementation, we strive to ensure that the codebase is cross-platform and does not rely on OS-specific behaviors. However, it is possible that some nuances specific to different operating systems could exist, especially when dealing with file system operations, character encoding, or threading. This might manifest in different ways such as issues in logging, metrics uploading, etc.

The behaviour of callback handling during training should not vary significantly across different operating systems. However, if you are encountering any issues, could you please provide a bit more detail about the problems you're facing? This would help us diagnose potential discrepancies in the implementation or unexpected points of failure.

Looking forward to your response so we can get a better understanding of your encounter and address this effectively. Thank you!

**Comment by Gornoka** [comment]
I was facing issues with the on_fit_end callback of the MLFLOW integration not working, resulting in incomplete uploads, where only the initial params and the end_of_run artifacts were logged, I have about 20 test runs with that behaviour against different stages of code changes I made to the ultraltics repo, I was not able to isolate the issue. At the same time, the same code ran on my Windows machine.
From the perspective of the MLFLOW-server the respective API endpoints for the metrics were not called in those cases.
The only change I made that I could see fixing this behaviour is one change to the on_train_end callback, where I reduced the number of artifacts stored.

**Comment by glenn-jocher** [comment]
@Gornoka hello,

Thank you for sharing your experience working with YOLOv8 and the MLflow integration. It seems like you've encountered a peculiar issue where the on_fit_end callback of the MLflow integration does not work as expected on your Linux system, whereas it works fine on your Windows. This behavior has resulted in incomplete uploads, which is indeed concerning.

Posting metrics or logging artifacts will depend on the callback functions and how they interact with MLflow. If the callbacks were not properly executed, this may result in the absence of some logs in MLflow. 

Although you have mentioned that reducing the number of artifacts stored in the on_train_end callback seemed to correct this issue, it would be quite unusual if this were the core issue, unless there is a memory or storage limit being exceeded unknowingly. 

Unfortunately, without further information on the specific changes you made to the Ultralytics repository, we can only conjecture.

However, what you've pointed out could very well be critical in improving the overall functionality of YOLOv8. Ideally, anomalies such as these should not arise as YOLOv8 is designed to work uniformly across different platforms.

We appreciate your input and would like to explore it further. If you would be willing to provide us with more detailed information about the changes you've made, such as the specific edits and the resulting behaviors, it would greatly help us in identifying the bug and improving the codebase.

Thank you once again, and looking forward to your response.

**Comment by Gornoka** [comment]
This can be closed. I have monitored the trainings of the last month, and After the changes to the MLFLOW integration from #4959 I did not see any runs with dropped metrics.

**Comment by glenn-jocher** [comment]
@Gornoka hello, 

Thank you for reaching out and for monitoring the training processes in the past month! We're glad to hear that the changes to the MLFLOW integration from #4959 have been working well for you and you have not encountered runs with dropped metrics.

If you need more support or have any other issues or topics you'd like to discuss, please do not hesitate to create another ticket. Your contributions to the community are appreciated!

I'll proceed to close this issue now. Thanks again for your help in improving YOLOv8!

Best regards.
