### ISSUE TITLE
Convert coco no longer works on RLE segments

### ISSUE THREAD

**Issue by kymillev** [ultralytics/ultralytics#4931]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

An update to the Yolo codebase (I think it's this commit: https://github.com/ultralytics/ultralytics/commit/1db9afc2e5036aba428f63f436eb6ad6102d43db#diff-75efef96e07c9d4ff2cd886cf936b1ee920f98058cf4abd2194a668f90d3655f) removed the inclusion of dictionary objects when converting from the COCO format in Ultralytics/data/converter.py to the YOLO format, basically breaking support for RLE-encoded segments. 

I'm not sure if this was an intended change, as RLE is officially supported by COCO. If it was an intended change, perhaps add this to the documentation that a COCO polygon format is required.

 When running the same script using Ultraltyicsv8.0.139, it works fine as before.  The resulting label segmentations will not be 100% accurate if the mask cannot be represented by a polygon, but the trained model results are surprisingly good. 

### Environment

Ultralytics YOLOv8.0.180

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kymillev ah thanks the bug report! Can you submit a PR to reintroduce this?

It was removed because it was showing zero coverage when exporting COCO segments so I wasn't sure what it's purpose was.

**Comment by vittorio-prodomo** [comment]
Hey guys! I recently came across this problem, too. Basically, when using the CVAT labeling tool and exporting some labels to COCO format, the masks objects are translated into RLE encoding in the output json file. If I then want to convert this json to Yolo format using [this function](https://docs.ultralytics.com/reference/data/converter/#ultralytics.data.converter.convert_coco), things are not gonna work because such a function only looks for 'segmentation' key in the coco dictionaries. Any idea if this was eventually planned to be fixed. Or do you know any workaround?

Thanks, and keep up the good work!

**Comment by glenn-jocher** [comment]
@vittorio-prodomo thanks for the additional context! The issue with RLE-encoded segments from CVAT export is indeed a known limitation after the removal mentioned by @kymillev.

For a workaround, you can convert RLE masks back to polygons before using `convert_coco`. Here's a quick approach:

```python
from pycocotools import mask as coco_mask
import json

# Load your COCO JSON
with open('your_coco_file.json', 'r') as f:
    data = json.load(f)

# Convert RLE to polygons
for ann in data['annotations']:
    if 'segmentation' in ann and isinstance(ann['segmentation'], dict):  # RLE format
        # Decode RLE to binary mask
        binary_mask = coco_mask.decode(ann['segmentation'])
        # Convert to polygon (you'll need to implement polygon extraction from binary mask)
        # This is more complex and may require additional libraries like opencv or scikit-image

# Then use convert_coco normally
from ultralytics.data.converter import convert_coco
convert_coco(labels_dir="path/to/annotations/", use_segments=True)
```

We're tracking this for a proper fix to support RLE natively in the converter again.
