### ISSUE TITLE
import another python code when running yolo

### ISSUE THREAD

**Issue by luigisa1** [ultralytics/ultralytics#4934]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to create a code in which I instantiate yolo and through the detection I track the detection with my camera.

The problem comes when I try to import another script.py created by me.

I have tried to do it in two ways. First of all, create all the codes in the same ultralytics folder. Having in this way two own codes, the code that I want to import and the main code in which I try to import my secondary code (calc_move.py) and YOLO. In this way I encounter the problem "import move.py could not be resolved ".

The other option that I have tried is to create a folder that is located within the same ultralytics folder in which I have my codes. In this case I manage to import my secondary code correctly but when I execute I get an error in the "from ultralytics inport YOLO" and it says ModuleNotFoundError: No module named "ultralytics".

Could you help me organize my codes so that they work? Thank you so much.

**Comment by glenn-jocher** [comment]
@luigisa1 thank you for bringing up this issue; I believe it's related to how Python handles paths and imports.

When trying to import a script that is in the same directory as your main code, it should be as straightforward as using `import calc_move` given that `calc_move.py` is indeed in the same directory as your current Python script. The error message "import move.py could not be resolved" might indicate that Python does not locate the specified file in your current working directory. Make sure your main code and `calc_move.py` are in the same folder.

In the second scenario, when you isolate your code in a new folder within the ultralytics directory and you get an error on `from ultralytics import YOLO`, this typically indicates that Python does not know where to find the Ultralytics yolo module. To solve this, you might need to append your path to include the ultralytics directory so Python knows where to search for modules.

Given that YOLOv8 and your scripts are under the ultralytics directory, I would recommend first trying to make sure the Python paths are properly set up. Try to understand and differentiate among absolute and relative imports in Python, your project's folder structure, and how PYTHONPATH and sys.path work.

Moreover, if you need more flexibility in managing different versions of Python or organizing your project's dependencies separately, I would recommend using virtual environments, i.e., venv or conda. These tools might help you manage your Python environment more systematically, avoiding any interference between different Python versions or environments that you might have installed on your system. 

Remember, whenever you change your Python scripts' location or your working directory, it can influence how Python imports modules. Therefore, always ensure that your Python environment is well-managed and your scripts are correctly located concerning the directories of the modules they depend on.
