### ISSUE TITLE
May I ask if the YOLOv8 segmentation model supports cityspace/ApolloScapeAuto as a data format

### ISSUE THREAD

**Issue by umie0128** [ultralytics/ultralytics#4949]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

May I ask if the YOLOv8 segmentation model supports Cityspace/ApolloScapeAuto as a data format
This dataset format stores labels on a grayscale image, with the grayscale value being its label number
Cityspace:https://www.cityscapes-dataset.com/
ApolloScapeAuto:https://github.com/ApolloScapeAuto/dataset-api

**Comment by codename-cn** [comment]
@umie0128 Did you manage the conversion?
