### ISSUE TITLE
How to modify the overall font size of the confusion matrix

### ISSUE THREAD

**Issue by yaomumu** [ultralytics/ultralytics#4951]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

For the generated results, if there are multiple types, the display will be relatively small. How can I modify the font size of the confusion matrix
![confusion_matrix_normalized](https://github.com/ultralytics/ultralytics/assets/81569436/d6b74504-f846-46ab-8836-bbaea0f3e8eb)

**Comment by yaomumu** [comment]
Modifications can be made through \ultralytics\utils\metrics.py.

**Comment by glenn-jocher** [comment]
@yaomumu thank you for your question! 

The font size of the confusion matrix is managed within the `utils/metrics.py` script, specifically in the `plot_confusion_matrix()` function. You can adjust the font size there. 

To do this, you'll want to locate the specific part of this function where matplotlib is used to generate the plot. There, you should see some parameters related to font size in methods like `xlabel()`, `ylabel()`, `title()`, and `xticks()` - these are typically set via the `fontsize=` option. 

By modifying these parameters, you should be able to adjust the font size to better suit your needs. Remember to save your changes and rerun your detections to see the changes in your new confusion matrix.

I hope this helps, please let me know if you have any further queries!

**Comment by glenn-jocher** [comment]
Hello @fordfelicity, thanks for your suggestion! 🌟

The snippet you provided is a great way to increase the font size of labels in a confusion matrix plot. Here’s a concise integration:

```python
disp.plot()
for labels in disp.text_.ravel():
    labels.set_fontsize(30)  # Sets the font size to 30
plt.show()
```
Just ensure this snippet follows the `disp = ConfusionMatrixDisplay(...)` initialization in your code. This should make the labels clearer, especially in plots with multiple categories!

Let us know if there's anything else we can help with! 😊
