### ISSUE TITLE
During object detection with the YOLOv8 model, a 'zsh: killed' error occurs

### ISSUE THREAD

**Issue by Bak-sejun** [ultralytics/ultralytics#4954]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

<img width="1624" alt="스크린샷 2023-09-18 오후 4 14 16" src="https://github.com/ultralytics/ultralytics/assets/73810902/2d92e623-a857-46ef-85c5-a930f8f89efc">

Please understand in advance that the question may be difficult as I am not good at English and am not a professional developer.

The laptop is MacBook Pro 14, and the chip is Apple M1 Pro.

I am experiencing an error when performing detection with the yolov8 model in vscode.

As shown in the picture above, while detection is in progress, the phrase 'zsh: killed' appears and detection ends.

https://stackoverflow.com/questions/66295155/zsh-killed-python3-on-m1-macbook-pro

Referring to the link above, I attempted to solve the problem as shown in the link below, but it did not work.

https://stackoverflow.com/questions/77123759/during-object-detection-with-the-yolov8-model-a-zsh-killed-error-occurs

How can I solve this problem?

**Comment by RizwanMunawar** [comment]
@Bak-sejun It appears that the error is occurring because the detection process is consuming all available memory. Could you please confirm whether the memory is not fully utilized during inference with YOLOv8?

**Comment by Bak-sejun** [comment]
<img width="1547" alt="스크린샷 2023-09-18 오후 7 47 07" src="https://github.com/ultralytics/ultralytics/assets/73810902/f69e4730-5ee7-41e0-8349-06ed52b128e1">
<img width="1547" alt="스크린샷 2023-09-18 오후 7 47 15" src="https://github.com/ultralytics/ultralytics/assets/73810902/39883e5e-b261-40df-a40c-6b77e8136d26">
<img width="1547" alt="스크린샷 2023-09-18 오후 7 47 25" src="https://github.com/ultralytics/ultralytics/assets/73810902/6ac12301-26b3-4006-95f8-2593f52fdf5c">
<img width="1547" alt="스크린샷 2023-09-18 오후 7 47 33" src="https://github.com/ultralytics/ultralytics/assets/73810902/18425f10-726c-4919-a6bf-ae65e76760c3">

Memory is being used as shown in the attached screenshot.

**Comment by Bak-sejun** [comment]
<img width="1030" alt="스크린샷 2023-09-18 오후 8 32 19" src="https://github.com/ultralytics/ultralytics/assets/73810902/abb13c3a-94ef-4a35-a388-0df0485ff02a">
<img width="1030" alt="스크린샷 2023-09-18 오후 8 33 11" src="https://github.com/ultralytics/ultralytics/assets/73810902/de1c08b1-fbbf-4f18-b7be-38a6e70eb0b8">

Thank you for pointing out the memory shortage issue. If you hadn't pointed it out, I still wouldn't have found the solution.

I found out that 'model.predict' is running out of memory because all the results accumulated until the end of inference are stored in memory.

Fixed memory shortage via stream=True function.

There is one thing I would like to ask.

To summarize what I understand about this problem, 'model.predict' stores the results of inferring every frame of the video in memory, and when you use the 'stream=true' function, it does not store them in memory, but the nth frame of the video. The inferred value is erased when inferring the n+1th frame.
So, if you use 'results = model.predict()', all the inference results will be returned to the results variable and you can extract the results from this results variable, and if you use the 'stream=True' function, you can use 'print(results)' Even if you do this, because there is no value inside, only the result '<generator object BasePredictor.stream_inference at 0x179ff1120>' is produced.

Do I understand this correctly?

**Comment by RizwanMunawar** [comment]
@Bak-sejun, you are absolutely correct.

When you execute `results = model.predict()`, the 'results' variable will contain all the inference data. You can extract this information as per your requirements. Since it's stored in memory, you have easy access to it. However, if you opt for `stream=True`, it won't retain all the results in memory, except for the frame currently being inferred. This is why if you attempt to `print(results)`, it will display the memory location of the object rather than providing details about the inference.

**Comment by Bak-sejun** [comment]
Thank you for answer. Additionally, I tried inferring with the 'yolov8n.pt' model, but the session was terminated due to a memory problem, so it seems difficult to obtain a video where video detection was performed with yolov8. I will use yolov5 or look for another method. Thank you.

**Comment by glenn-jocher** [comment]
@Bak-sejun, I understand your situation and thank you for trying to use YOLOv8. You're right, considering your current hardware's memory constraints, it appears that using `yolov8n.pt` for video inference can be demanding. I appreciate your understanding and the steps you have taken towards resolving the issue. If you have any more questions or issues related to YOLOv8, feel free to ask. Good luck with your ongoing exploration of object detection models!

**Comment by RizwanMunawar** [comment]
I am closing this issue. Please reopen if the issue persists
