### ISSUE TITLE
urgent help required yolov8 model Results saved to runs\detect\predict3 issue

### ISSUE THREAD

**Issue by anut123** [ultralytics/ultralytics#4965]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In this github link --> https://github.com/ultralytics/ultralytics in yolov8 model
where I can find this line --> Results saved to runs\detect\predict3  as I need to replace Results saved to runs\detect\predict3 with c://users//images  
as output images are storing in this path Results saved to runs\detect\predict3 but i want to store the output images  in this folder path c://users//images how to do this i have tired alot but couldnt the solution
 it would be grateful if you could help me out with this very urgent help required

@glenn-jocher 
@AyushExel

**Comment by RizwanMunawar** [comment]
@anut123, by utilizing the 'Project Argument' within the 'predict' command, you can save prediction results in various locations.

### Python Code
```
from ultralytics import YOLO

model = YOLO('yolov8n.pt')

model.predict('bus.png', save=True, imgsz=320, conf=0.5,
              project="C:\\Users\\ultralytics\\issues\\test9")

```

### CLI Command
```
yolo task=detect mode=predict source="path/to/image.png" project="C:\\Users\\ultralytics\\issues\\test9" save=True
```

**Comment by anut123** [comment]
Okay and thankyou@RizwanMunawar error has been solved

**Comment by RizwanMunawar** [comment]
@anut123, We're delighted to learn that your issue has been successfully resolved.

This issue is now being closed as it has been resolved. If you encounter any additional issues in the future, please don't hesitate to create a new issue for assistance.

Regards
Ultralytics Team
