### ISSUE TITLE
What are the parameters of albumentations and how many photos are generating?

### ISSUE THREAD

**Issue by thegkhn** [ultralytics/ultralytics#4966]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, good work. I saw that albumentations properties are used for Yolov8. When I tried to change these albumentations parameters myself, I saw that no change was reflected. In other words, when I add the "albumentations:" parameter to the data.yaml document, I still get "albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))" I see this. My question is:
1- How can I add the parameters I want to add extra?
2- Do I have a chance to increase the number of augment photos using these parameters?
3- How many different photos are created using the albumentations parameters in the Yolov8l model?
Thank you very much for your answer and interest.

### Additional

I use YoloV8 for object detection.

**Comment by glenn-jocher** [comment]
@thegkhn hi there,

Thanks for your interest in YOLOv8 and for bringing up a good question about Albumentations.

1- To add extra parameters to the Albumentations configurations used in YOLOv8, you would alter the 'albumentations' section of your data.yaml. You should take care to use the certification proper names and format for Albumentations transformations. Remember to properly format the YAML to indicate Albumentations as the augmentation strategy and listing your transformations.

2- The number of images generated by Albumentations doesn't increase the number of images in your dataset. The purpose of these transformations is to artificially extend the variety of data the model is exposed to, by modifying your existing pictures during training, thus making the model more robust to a wider range of scenarios.

3- For each image in your dataset, Albumentations applies a random transformation at every step in the training process. Therefore, technically you can say it generates a 'unique' version of each of your photos at each step. However, the total number of images in your dataset remains constant.

I hope this clarifies your concerns, but do feel free to ever reach out to us in the future with any questions related to YOLOv8. We are here to help!

Best regards,
Glenn

**Comment by thegkhn** [comment]
Thank you very much for your reply. Also, finally, do you think it would make more sense to do a training in 1920x1088 size (ie using the rect parameter) or to train in 1280 size? 
Again, thank you very much for your answer and interest.

> @thegkhn hi there,
> 
> Thanks for your interest in YOLOv8 and for bringing up a good question about Albumentations.
> 
> 1- To add extra parameters to the Albumentations configurations used in YOLOv8, you would alter the 'albumentations' section of your data.yaml. You should take care to use the certification proper names and format for Albumentations transformations. Remember to properly format the YAML to indicate Albumentations as the augmentation strategy and listing your transformations.
> 
> 2- The number of images generated by Albumentations doesn't increase the number of images in your dataset. The purpose of these transformations is to artificially extend the variety of data the model is exposed to, by modifying your existing pictures during training, thus making the model more robust to a wider range of scenarios.
> 
> 3- For each image in your dataset, Albumentations applies a random transformation at every step in the training process. Therefore, technically you can say it generates a 'unique' version of each of your photos at each step. However, the total number of images in your dataset remains constant.
> 
> I hope this clarifies your concerns, but do feel free to ever reach out to us in the future with any questions related to YOLOv8. We are here to help!
> 
> Best regards, Glenn

Thank you very much for your reply. Also, finally, do you think it would make more sense to do a training in 1920x1088 size (ie using the rect parameter) or to train in 1280 size? 
Again, thank you very much for your answer and interest.
