### ISSUE TITLE
How to use old cached file?

### ISSUE THREAD

**Issue by LordonCN** [ultralytics/ultralytics#4967]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thanks for your wonderful work. 
I want to know how to use cached file when second training? Because it takes long time when I use 1000,000 images to finetune.

**Comment by thegkhn** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> ### Question
> Thanks for your wonderful work. I want to know how to use cached file when second training? Because it takes long time when I use 1000,000 images to finetune.
> 
> ### Additional
> _No response_

Hello,

After the first scan, the labels.cache file is created. In this, the necessary information is saved. You can use this.
It will be enough to copy the cache files to each folder (train and val).

**Comment by RizwanMunawar** [comment]
Hello @LordonCN 

Following the initial scan, a labels.cache file is generated, which stores essential information. You can utilize this file. Simply copying the cache files to both the 'train' and 'val' folders will suffice.

**Comment by LordonCN** [comment]
👌

**Comment by RizwanMunawar** [comment]
@LordonCN, I am closing this issue because it's resolved. Should you encounter any further problems, don't hesitate to open a new issue for it.

Best regards,
Ultralytics Team
