### ISSUE TITLE
I get an error when predicting segmentation with custom model

### ISSUE THREAD

**Issue by initdebugs** [ultralytics/ultralytics#497]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Ultralytics YOLOv8.0.10 🚀 Python-3.8.10 torch-1.13.1+cu116 CUDA:0 (Tesla T4, 15110MiB)
Fusing... 
Model summary: 268 layers, 68124531 parameters, 0 gradients, 257.4 GFLOPs
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/cli.py", line 148, in entrypoint
    cli(cfg)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/cli.py", line 84, in cli
    func(cfg)
  File "/usr/local/lib/python3.8/dist-packages/hydra/main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/v8/segment/predict.py", line 107, in predict
    predictor.predict_cli()
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/predictor.py", line 165, in predict_cli
    for _ in gen:  # running CLI inference without accumulating any outputs (do not modify)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/predictor.py", line 200, in stream_inference
    results = self.postprocess(preds, im, im0s)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/v8/segment/predict.py", line 16, in postprocess
    p = ops.non_max_suppression(preds[0],
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/ops.py", line 183, in non_max_suppression
    xc = prediction[:, 4:mi].amax(1) > conf_thres  # candidates
IndexError: amax(): Expected reduction dim 1 to have non-zero size.

### Environment

Ultralytics YOLOv8.0.10 🚀 Python-3.8.10 torch-1.13.1+cu116 CUDA:0 (Tesla T4, 15110MiB)

### Minimal Reproducible Example

I trained a segmentation model. When trying to use the model for prediction I get this error

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Thanks for bug report. please provide a reproducible example.

**Comment by initdebugs** [comment]
I trained a model using this dataset I made: https://app.roboflow.com/lesley-natrop-zgywz/traffic-detection-road-addon-uaogd/5

I used the YoloV8X.pt base model for the training. The training was 150 epochs. Everything else was default settings for training. Training went fine without errors.

When trying to predict using that model, the error above showed up and it won't predict (it doesn't start).

Is this enough information? Please let me know, I want to help as good as possible :)

**Comment by r-dh** [comment]
Same error. The issue occurs only for `task=segment`, using the default Colab tutorial.

**Comment by initdebugs** [comment]
Indeed. It is in the colab notebook.
What I found out is that it works when pasting the full path of the model file instead of `{HOME}/runs/detect/train/weights/best.pt`

**Comment by initdebugs** [comment]
Nevermind this is not the case. It's only when using `task=segment`

**Comment by AyushExel** [comment]
Well yolov8x.pt is a detection model, you can't run segmentation task on it

**Comment by initdebugs** [comment]
![image](https://user-images.githubusercontent.com/75781464/213707735-06eadaea-444a-42e2-b1a7-0d4c01a6b185.png)
Then why is it listed under the segmentation tab?

But besides that, the yolov8n and yolov8m model don't work either.

**Comment by remy-radix** [comment]
You will need to append `-seg` behind the model name, e.g. `task=segment mode=train model=yolov8x-seg.pt`.

Hover the links of your screenshot and it will become clear why.

**Comment by r-dh** [comment]
You will need to append `-seg` behind the model name, e.g. `task=segment mode=train model=yolov8x-seg.pt`.

Hover the links of your screenshot and it will become clear why.

**Comment by initdebugs** [comment]
Okay I hovered over it before sending the last message and it showed the model links without `-seg`. Thanks for changing :)
