### ISSUE TITLE
how to sort YOLOv8 output boxes in predict mode

### ISSUE THREAD

**Issue by enekuie** [ultralytics/ultralytics#4971]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

as far as I know yolo sorts output boxes in predict mode by their confidence score, is there anyway to sort them by their position?
when I searched about it I found that for yolov5 you have to edit detect.py file to do so but there's no such file in yolov8.

Thanks in advance!

**Comment by zshariff6506** [comment]
I can submit a PR for this as a feature.

**Comment by zshariff6506** [comment]
@glenn-jocher Ok I'm going to go ahead and work on a PR.
This will be my first-ever PR to a community repo... I'll need some time and guidance, but I am on the right track.

Thanks!

**Comment by zshariff6506** [comment]
Two questions:
1. Should I add an option that gives people the choice to have it sorted, or change so it becomes the default?
2. Should it be sorted from top to bottom (along y axis) or left to right (along x axis)?

**Comment by glenn-jocher** [comment]
@zshariff6506 hi there,

Great to hear you are proceeding with the PR!

1. For your first question - it would be best to add an option that allows users to choose their preferred method of sorting. Not everyone may want this new sorting functionality, so it's important we give users the option to choose which works best for their use case.

2. Regarding your second question - if possible, it would be excellent to give users the option to sort in both ways i.e., top to bottom and left to right. The appropriateness of these two methods can depend on the application of the model, so offering both can make the tool more versatile.

Looking forward to seeing your contributions to the YOLOv8 repo. Feel free to ask if you have any more questions throughout the process. Good luck on your first PR!

**Comment by enekuie** [comment]
> @glenn-jocher Ok I'm going to go ahead and work on a PR. This will be my first-ever PR to a community repo... I'll need some time and guidance, but I am on the right track.
> 
> Thanks!

so glad to see my question helped to improve this repo for better. i could wrote a code to modify yolo outputs (changed are not made within Ultralytics package). i can share the ode with you if you're intersted

**Comment by glenn-jocher** [comment]
@enekuie Hello,

Thank you for showing interest in contributing to the YOLOv8 repo. Your proactivity in wanting to enhance the functionality of YOLOv8 is appreciated.

As for your code, while it's great that you've managed to write code to modify YOLO output outside of the Ultralytics package, our main focus here is on changes that can be integrated directly into the YOLOv8 codebase for the benefit of all users. 

We aim to ensure that functionalities are streamlined and consistent across the various modes of operation, which is why contributions ideally should involve modifications to the base package.

Again, thank you for your willingness to participate in this open-source project. Please feel free to reach out if you have any other ideas or suggestions.

**Comment by NishaAkole** [comment]
Is this logic implemented? Where to check the documentation for this?

**Comment by glenn-jocher** [comment]
@NishaAkole hi there! 😊 

Yes, the feature you're inquiring about is indeed implemented. For more detailed info and examples, please check out our documentation right [here](https://docs.ultralytics.com/). If you're looking for something specific in the code, a quick search or browsing through the repo should also help.

Should you have any more questions or need further clarification, just let us know. Happy coding!
