### ISSUE TITLE
Ray Tuning doesnt start

### ISSUE THREAD

**Issue by martoliod** [ultralytics/ultralytics#4980]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug
When trying to run the Ray Tuning Training process, i get the following error:

```
WARNING ⚠️ search space not provided, using default search space.
2023-09-19 14:13:01,110	INFO worker.py:1642 -- Started a local Ray instance.
2023-09-19 14:13:01,647	INFO tune.py:229 -- Initializing Ray automatically. For cluster usage or custom Ray initialization, call `ray.init(...)` before `Tuner(...)`.
2023-09-19 14:13:01,648	INFO tune.py:655 -- [output] This will use the new output engine with verbosity 1. To disable the new output and use the legacy output engine, set the environment variable RAY_AIR_NEW_OUTPUT=0. For more information, please see https://github.com/ray-project/ray/issues/36949
Traceback (most recent call last):
  File "hyperparam_tuning.py", line 7, in <module>
    result_grid = model.tune(data='waldteich_1407.yaml', use_ray=True)
  File "/home/becker/anaconda3/envs/yolo/lib/python3.7/site-packages/ultralytics/engine/model.py", line 406, in tune
    return run_ray_tune(self, *args, **kwargs)
  File "/home/becker/anaconda3/envs/yolo/lib/python3.7/site-packages/ultralytics/utils/tuner.py", line 117, in run_ray_tune
    tuner.fit()
  File "/home/becker/anaconda3/envs/yolo/lib/python3.7/site-packages/ray/tune/tuner.py", line 372, in fit
    return self._local_tuner.fit()
  File "/home/becker/anaconda3/envs/yolo/lib/python3.7/site-packages/ray/tune/impl/tuner_internal.py", line 579, in fit
    analysis = self._fit_internal(trainable, param_space)
  File "/home/becker/anaconda3/envs/yolo/lib/python3.7/site-packages/ray/tune/impl/tuner_internal.py", line 700, in _fit_internal
    **args,
  File "/home/becker/anaconda3/envs/yolo/lib/python3.7/site-packages/ray/tune/tune.py", line 869, in run
    restore=restore,
  File "/home/becker/anaconda3/envs/yolo/lib/python3.7/site-packages/ray/tune/experiment/experiment.py", line 208, in __init__
    experiment_dir_name=name,
  File "/home/becker/anaconda3/envs/yolo/lib/python3.7/site-packages/ray/train/_internal/storage.py", line 455, in __init__
    self.storage_path, storage_filesystem
  File "/home/becker/anaconda3/envs/yolo/lib/python3.7/site-packages/ray/train/_internal/storage.py", line 308, in get_fs_and_path
    return pyarrow.fs.FileSystem.from_uri(storage_path)
  File "pyarrow/_fs.pyx", line 470, in pyarrow._fs.FileSystem.from_uri
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: URI has empty scheme: './runs/tune'
```

## Im using Anaconda
```
platform: linux-64
_libgcc_mutex=0.1=main
_openmp_mutex=5.1=1_gnu
aiosignal=1.3.1=pypi_0
appdirs=1.4.4=pypi_0
attrs=23.1.0=pypi_0
backcall=0.2.0=pypi_0
ca-certificates=2023.05.30=h06a4308_0
certifi=2022.12.7=py37h06a4308_0
charset-normalizer=3.2.0=pypi_0
click=8.1.7=pypi_0
cycler=0.11.0=pypi_0
decorator=5.1.1=pypi_0
docker-pycreds=0.4.0=pypi_0
filelock=3.12.2=pypi_0
fire=0.5.0=pypi_0
fonttools=4.38.0=pypi_0
frozenlist=1.3.3=pypi_0
fsspec=2023.1.0=pypi_0
gitdb=4.0.10=pypi_0
gitpython=3.1.36=pypi_0
idna=3.4=pypi_0
imagecodecs=2021.11.20=pypi_0
imageio=2.31.2=pypi_0
importlib-metadata=6.7.0=pypi_0
importlib-resources=5.12.0=pypi_0
ipython=7.34.0=pypi_0
jedi=0.19.0=pypi_0
jsonschema=4.17.3=pypi_0
kiwisolver=1.4.5=pypi_0
ld_impl_linux-64=2.38=h1181459_1
libffi=3.4.4=h6a678d5_0
libgcc-ng=11.2.0=h1234567_1
libgomp=11.2.0=h1234567_1
libstdcxx-ng=11.2.0=h1234567_1
matplotlib=3.5.3=pypi_0
matplotlib-inline=0.1.6=pypi_0
msgpack=1.0.5=pypi_0
ncurses=6.4=h6a678d5_0
networkx=2.6.3=pypi_0
numpy=1.21.6=pypi_0
nvidia-cublas-cu11=11.10.3.66=pypi_0
nvidia-cuda-nvrtc-cu11=11.7.99=pypi_0
nvidia-cuda-runtime-cu11=11.7.99=pypi_0
nvidia-cudnn-cu11=8.5.0.96=pypi_0
opencv-python=4.8.0.76=pypi_0
openssl=1.1.1v=h7f8727e_0
packaging=23.1=pypi_0
pandas=1.3.5=pypi_0
parso=0.8.3=pypi_0
pathtools=0.1.2=pypi_0
pexpect=4.8.0=pypi_0
pickleshare=0.7.5=pypi_0
pillow=9.5.0=pypi_0
pip=22.3.1=py37h06a4308_0
pkgutil-resolve-name=1.3.10=pypi_0
prompt-toolkit=3.0.39=pypi_0
protobuf=4.24.3=pypi_0
psutil=5.9.5=pypi_0
ptyprocess=0.7.0=pypi_0
py-cpuinfo=9.0.0=pypi_0
pyarrow=12.0.1=pypi_0
pybboxes=0.1.6=pypi_0
pycocotools=2.0.7=pypi_0
pygments=2.16.1=pypi_0
pyparsing=3.1.1=pypi_0
pyrsistent=0.19.3=pypi_0
python=3.7.16=h7a1cb2a_0
python-dateutil=2.8.2=pypi_0
pytz=2023.3=pypi_0
pywavelets=1.3.0=pypi_0
pyyaml=6.0.1=pypi_0
ray=2.7.0=pypi_0
readline=8.2=h5eee18b_0
requests=2.31.0=pypi_0
sahi=0.11.14=pypi_0
scikit-image=0.19.3=pypi_0
scipy=1.7.3=pypi_0
seaborn=0.12.2=pypi_0
sentry-sdk=1.31.0=pypi_0
setproctitle=1.3.2=pypi_0
setuptools=65.6.3=py37h06a4308_0
shapely=2.0.1=pypi_0
six=1.16.0=pypi_0
smmap=5.0.1=pypi_0
sqlite=3.41.2=h5eee18b_0
tensorboardx=2.6.2.2=pypi_0
termcolor=2.3.0=pypi_0
terminaltables=3.1.10=pypi_0
tifffile=2021.11.2=pypi_0
tk=8.6.12=h1ccaba5_0
torch=1.13.1=pypi_0
torchvision=0.14.1=pypi_0
tqdm=4.66.1=pypi_0
traitlets=5.9.0=pypi_0
typing-extensions=4.7.1=pypi_0
ultralytics=8.0.145=pypi_0
urllib3=2.0.4=pypi_0
wandb=0.15.10=pypi_0
wcwidth=0.2.6=pypi_0
wheel=0.38.4=py37h06a4308_0
xz=5.4.2=h5eee18b_0
zipp=3.15.0=pypi_0
zlib=1.2.13=h5eee18b_0
```

### Minimal Reproducible Example

```
from ultralytics import YOLO

# Load a YOLOv8n model
model = YOLO('yolov8n.pt')

# Start tuning hyperparameters for YOLOv8n training on the COCO8 dataset
result_grid = model.tune(data='waldteich_1407.yaml', use_ray=True)
```

### Additional

I tried different combinations of Ray Tuning, as well as providing full paths and relative paths to the model and yaml file. Im not sure, what the problem might be?

Thanks in advance!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@martoliod great news 😃! Your original issue may now be resolved ✅ in PR #4964. This fix is live in `main` branch and will be part of `8.0.182` published later today.

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by martoliod** [comment]
@glenn-jocher wow, perfect timing , thanks alot! :)

**Comment by NathanielJVallee** [comment]
Because 2.7.0 isn't currently supported I found downgrading ray tune to a lower version to fix this issue. so in the mean time you could do that. Hope this helps!

`pip install "ray[tune]"==2.6.3`

**Comment by ashray21** [comment]
Hi @martoliod 
You can use ray tuner in this way 

from ultralytics import YOLO
from ultralytics.utils.tuner import run_ray_tune

model = YOLO("model_path")

run_ray_tune(model, data="ymal_file_path", grace_period=30, gpu_per_trial=1)

**Comment by martoliod** [comment]
Thanks for alle the answers! i made it work by upgrading ultralytics, like @glenn-jocher suggested, and downgrading raytune, like mentioned in @NathanielJVallee s answer. 

@ashray21 thanks for answer. is there a difference in using `model.tune` or `run_ray_tune` ?

**Comment by ashray21** [comment]
@martoliod As far as I know there is no difference between the two.

**Comment by glenn-jocher** [comment]
@ashray21, I'm glad to hear that you found a solution! Yes, both `model.tune` and `run_ray_tune` essentially do the same thing. They both serve to facilitate hyperparameter tuning using the Ray Tune package. The primary function call may be different but the desired outcome remains the same. Please let me know if you have any other questions!

**Comment by tshu-w** [comment]
For those who came to this issue because of errors caused by using ray, starting from ray 2.7.0, `storage_path` does not support relative paths. You can avoid the error by using `Path("./relative_path").resolve()`.

**Comment by glenn-jocher** [comment]
@tshu-w, thank you for sharing this information. 

From version 2.7.0 onwards, Ray no longer supports relative paths for `storage_path`. Therefore, using the `resolve()` method of the `Path` library with your relative path can help convert it into an absolute path and bypass this error when using YOLOv8. So, if you were previously using a relative path, you must convert it to an absolute path before inputting it into `storage_path`.

Please let us know if this resolves your issue or if you need further assistance!

**Comment by lyzyn** [comment]
When I referenced an absolute path, the following error occurred, which troubled me a lot.
  **File "pyarrow\_fs.pyx", line 348, in pyarrow._fs.FileSystem.from_uri
  File "pyarrow\error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: URI has empty scheme: '~/ray_result'**

**Comment by tshu-w** [comment]
> When I referenced an absolute path, the following error occurred, which troubled me a lot.
> **File "pyarrow_fs.pyx", line 348, in pyarrow._fs.FileSystem.from_uri File "pyarrow\error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status File "pyarrow\error.pxi", line 99, in pyarrow.lib.check_status pyarrow.lib.ArrowInvalid: URI has empty scheme: '~/ray_result'**

`~/ray_result` is not a absolute path, it should be something like `/home/username/ray_result`

**Comment by glenn-jocher** [comment]
@tshu-w apologies for the confusion, but `~/ray_result` is not an absolute path. The symbol `~` is a shorthand that commonly stands for the user's home directory in Unix-like operating systems, but it's not recognized as such in all contexts. The error you're seeing indicates that the involved library (pyarrow) doesn't interpret it that way.

In your case, you need to provide a fully qualified directory path. Rather than using `~`, you should manually replace it with the full path to your home directory. For example, if your username on the system is "User", the absolute path would look something like `/home/User/ray_result`. Please replace "User" with your actual username.

Try using this absolute path. Let us know if this resolves the issue.
