### ISSUE TITLE
How do I use prediction without showing the bounding box for segmentation?

### ISSUE THREAD

**Issue by initdebugs** [ultralytics/ultralytics#499]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm building a custom segmentation model. When predicting I don't want the bounding box with confidence shown. I just want the segmentation mask. How would I do that. I looked in the docs but can't find anything.

**Comment by DavidBerschauer** [comment]
```sh
yolo task=segment mode=predict model=... source=... hide_labels=True
```
If you want the label and scores to be smaller, add *line_thickness=1*

**Comment by initdebugs** [comment]
Getting back to this, `hide_labels=True` does indeed hide the label for detection, but I want the bounding box for the segmentation to not be visible. `line_thickness=0` does not work either.

**Comment by AyushExel** [comment]
@initdebugs currently it's not possible but its a good feature request. I'll see if this can be a quick thing to add in the existing PR

**Comment by DavidBerschauer** [comment]
@AyushExel 2 lines of code in [ultralytics/yolo/utils/plotting.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/utils/plotting.py) have to be changed:
- [Line 56](https://github.com/ultralytics/ultralytics/blob/e9ab157330236ddcacb2421943760c5698cc2e21/ultralytics/yolo/utils/plotting.py#L56) 
   ```python
   self.lw = line_width or max(round(sum(im.shape) / 2 * 0.003), 2)  # line width
   TO:
   self.lw = max(round(sum(im.shape) / 2 * 0.003), 2) if line_width is None else line_width  # line width 
   ```
- [Line 75](https://github.com/ultralytics/ultralytics/blob/e9ab157330236ddcacb2421943760c5698cc2e21/ultralytics/yolo/utils/plotting.py#L75)
   ```python
   cv2.rectangle(self.im, p1, p2, color, thickness=self.lw, lineType=cv2.LINE_AA)
   TO:
   if self.lw > 0:
      cv2.rectangle(self.im, p1, p2, color, thickness=self.lw, lineType=cv2.LINE_AA)
   ```

This allows ```line_thickness=0``` to do the trick

**Comment by AyushExel** [comment]
I did this here https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/v8/segment/predict.py#L90:
```
self.annotator.box_label(d.xyxy.squeeze(), label, color=colors(c, True)) if self.args.boxes else None
```
seems to work for me. Let me know if you guys had a different use case in mind. Head over to the PR for usage.
https://github.com/ultralytics/ultralytics/pull/580

**Comment by Super-IoT-Group** [comment]
> I did this here https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/v8/segment/predict.py#L90:
> 
> ```
> self.annotator.box_label(d.xyxy.squeeze(), label, color=colors(c, True)) if self.args.boxes else None
> ```
> 
> seems to work for me. Let me know if you guys had a different use case in mind. Head over to the PR for usage. #580

can this be done after the model has been trained? or it has to be before? take example when i have already trained the model and i am trying to apply
 it for segmentation. How can i play with the code?

**Comment by glenn-jocher** [comment]
@Super-IoT-Group the changes mentioned in the given code snippet need to be made before training the model. These modifications affect the prediction process by hiding the bounding box for segmentation. If you have already trained the model and want to apply it for segmentation without showing the bounding box, you would need to make these changes and retrain the model.

To play with the code, you can navigate to the file mentioned in the code snippet, which is `predict.py` located in the `ultralytics/yolo/v8/segment` directory. You can modify the code as described and then run your segmentation prediction script. Keep in mind that any modifications made to the code will only take effect when you rerun the prediction script.

Please note that it's important to follow best practices when modifying the code and ensure that you understand the potential impacts of your changes on the overall functionality and performance of the model.

**Comment by Atharva-Madiwale** [comment]
I am training the model on Google Colab and running inference locally on my laptop. I've implemented the steps mentioned above but am still unable to get rid of the bounding box. I was able to get predictions without labels, but the bounding box is still there. Any suggestions ?

**Comment by glenn-jocher** [comment]
@Atharva-Madiwale thank you for reaching out and explaining the steps you've taken. I apologize for any confusion caused. To remove the bounding box for segmentation in YOLOv8, you can modify the code in the `predict.py` file as mentioned earlier. However, please note that these changes need to be made before training the model.

If you have already trained the model and are still seeing the bounding box during inference, it might be due to the model's weights not being updated with the modified code. In this case, you would need to retrain the model with the updated code to ensure the changes take effect.

Please ensure that you have made the modifications to the appropriate lines of code in `predict.py` and that you have fully retrained the model after making the changes. This should allow you to get predictions for segmentation without the bounding box.

If you have followed these steps and are still facing issues, please provide more details about your setup, the specific modifications you made, and any error messages you are encountering. This will help us further troubleshoot the issue and provide you with more targeted assistance.

**Comment by JiayuanWang-JW** [comment]
yolo task=segment mode=predict model=... source=... --hide_labels=True --boxes=False

This command works for me. It will close labels which include boxes and text.

**Comment by glenn-jocher** [comment]
@JiayuanWang-JW that is correct, specifying `--hide_labels=True` and `--boxes=False` as command-line arguments during prediction with YOLOv8 effectively hides both the object classification labels and the bounding boxes for segmentation tasks. 

When `--hide_labels=True` is used, the labels associated with each detected object (i.e., the classification) are not displayed on the output visualization. Similarly, when `--boxes=False` is used, the bounding boxes that typically surround each detected object on the output visualization are also hidden. 

This allows your segmentation model to output only the segmentation mask without any additional annotations. It's a useful feature when you are only interested in the segmentation results. 

Thanks for sharing your successful command-line sequence, as it might be helpful for other users in similar scenarios. Let's keep building an effective and efficient YOLOv8 community together!

**Comment by ErikMamet** [comment]
In detect.py 
replace line 196 
--------
annotator.box_label(xyxy, label, color=colors(c, True))
by
+++++
if not hide_labels: annotator.box_label(xyxy, label, color=colors(c, True))

This way when you add the --hide-label tag no bounding boxes or labels will be displayed

**Comment by Mehreganbeiki** [comment]
Hi, Does anyone know how I can merge the masks the model predicted for the same object with different confidence scores together?

**Comment by glenn-jocher** [comment]
@Mehreganbeiki to merge predicted masks for the same object with different confidence scores, you can apply a mask merging technique such as weighted averaging based on confidence scores or use logical operations like 'OR' to combine the masks. Post-processing methods like Non-Maximum Suppression (NMS) for masks can also be adapted to refine overlapping masks and select the most representative one. Consider exploring post-processing strategies that best suit your specific use case and dataset.

**Comment by glenn-jocher** [comment]
@Mehreganbeiki, it sounds like you're on the right track with your current approach. To handle overlapping masks, consider implementing a post-processing step that merges them based on their confidence scores and spatial overlap. This could involve a custom script that processes the saved contour coordinates, applying a merging strategy like Intersection over Union (IoU) or weighted averaging. Working directly with the predicted masks before converting to text files might simplify the process and reduce inaccuracies. Experiment with both methods to determine which yields the most accurate results for your use case.

**Comment by Mehreganbeiki** [comment]
Thanks @glenn-jocher! 

I'm wondering if there's a way to obtain the masks directly in binary format without relying on the txt files and converting them to binary mask contours. I'm currently using OpenCV for this conversion, but it struggles with txt files containing multiple segmented objects. Typically, the output txt from the YOLO model looks like this:
Object 0 x1 y1 …. xn yn 
Object 1 x1 y1 …. xn yn 

While I can manually divide the coordinate points for each object and convert them using OpenCV, I'm curious if there's a more efficient method available.

**Comment by glenn-jocher** [comment]
@Mehreganbeiki, you can modify the output processing part of your code to directly save the masks in binary format instead of as text files. This would involve using the predicted segmentation masks to create binary images where the masks are filled in (typically with pixel value 255 for the mask and 0 for the background). Libraries like OpenCV or PIL can be used to handle this within your script. This direct approach should be more efficient and avoid the need for manual division and conversion of coordinate points.

**Comment by Mehreganbeiki** [comment]
Thanks @glenn-jocher! 

Apologies for the numerous questions, but to generate predictions on the test set, I initially load the model and then execute the following line of code:
Model.predict( source = “path of image”, show= True, save= True, conf= 0.5 , save_txt = True) 

This line saves the images with a red mask overlay and also saves the coordinate points of the contour. I'm uncertain whether I can directly access the binary masks here or if I need to work with the images with the mask overlay. My images have an orange-reddish hue, and although I attempted to use the inRange() function, the low contrast between the mask and the mask overlay of the images impedes its effectiveness.

**Comment by glenn-jocher** [comment]
@Mehreganbeiki to perform predictions with your custom segmentation model and only display the segmentation masks without the bounding boxes, you can use the `show_boxes=False` argument in the `predict()` method. Here's a concise example of how to do this in Python:

```python
from ultralytics import YOLO

# Load your custom trained segmentation model
model = YOLO('path/to/your/custom-model.pt')

# Perform prediction on an image without showing bounding boxes
results = model.predict('path/to/your/image.jpg', show_boxes=False)

# To visualize and save the segmentation masks
for result in results:
    mask_image = result.masks.plot()
    mask_image.save('path/to/save/mask_image.jpg')
```

This will ensure that only the segmentation masks are plotted and saved, without the bounding boxes. 🎨🔍

**Comment by Mehreganbeiki** [comment]
@glenn-jocher,

Thank you for following up on the problem.

Unfortunately, this doesn't work as the masks object has no attribute 'plot'. I was able to plot the result itself, but not the masks.

**Comment by glenn-jocher** [comment]
@Mehreganbeiki to perform prediction with your custom segmentation model and only display the segmentation masks without the bounding boxes, you can use the `plot()` method of the `Results` object and set the `boxes` argument to `False`. Here's a concise example in Python:

```python
from ultralytics import YOLO

# Load your custom trained segmentation model
model = YOLO('path/to/your/custom-model.pt')

# Perform prediction
results = model('path/to/your/image.jpg')

# Plot and save the segmentation mask without bounding boxes
segmentation_only = results[0].plot(boxes=False)
segmentation_only.save('segmentation_only.jpg')
```

This will generate an image with only the segmentation masks applied, omitting the bounding boxes and confidence scores. 🎨

**Comment by codename-cn** [comment]
@glenn-jocher 

Does not work for me:
`Traceback (most recent call last):
  File "../yolo-segmentation.py", line 11, in <module>
    segmentation_only.save('segmentation_only.jpg')
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'numpy.ndarray' object has no attribute 'save'. Did you mean: 'ravel'?`

**Comment by glenn-jocher** [comment]
@codename-cn hi there! It looks like you're trying to save a NumPy array directly, which doesn't have a `save` method. Instead, you can use OpenCV to save the image. Here's how you can do it:

```python
import cv2

# Your existing code to get the segmentation_only array
# ...

# Save the segmentation mask as an image
cv2.imwrite('segmentation_only.jpg', segmentation_only)
```

This should save your segmentation mask without any issues. Happy coding! 😊👨‍💻

**Comment by codename-cn** [comment]
> @Mehreganbeiki to perform predictions with your custom segmentation model and only display the segmentation masks without the bounding boxes, you can use the `show_boxes=False` argument in the `predict()` method. Here's a concise example of how to do this in Python:
> 
> ```python
> from ultralytics import YOLO
> 
> # Load your custom trained segmentation model
> model = YOLO('path/to/your/custom-model.pt')
> 
> # Perform prediction on an image without showing bounding boxes
> results = model.predict('path/to/your/image.jpg', show_boxes=False)
> 
> # To visualize and save the segmentation masks
> for result in results:
>     mask_image = result.masks.plot()
>     mask_image.save('path/to/save/mask_image.jpg')
> ```
> 
> This will ensure that only the segmentation masks are plotted and saved, without the bounding boxes. 🎨🔍

@glenn-jocher, I want to use `predict(..)`  instead of `model(..)` and hide the bounding boxes with `show_boxes=False`. Unfortunately this does not work for `predict(..)`, why?

BTW why `predict(..)` returns a list of results? Is it possible to get more than one result for one prediction on one image?

```python3
from pathlib import Path
from ultralytics import YOLO

model = YOLO('yolov8n.pt')

for path in Path('dataset/').rglob('*.png'):
    results = model.predict(
        source=path,
        show_boxes=False
    )

    results[0].save('output/' + results[0].path.split('/')[-1])
```

**Comment by glenn-jocher** [comment]
Hey @codename-cn! 😊 The `predict()` method is designed to handle batch predictions, which is why it returns a list of results - allowing for multiple images to be processed in a single call. For a single image, you'd still access the first item in the list.

Regarding `show_boxes=False` not working with `predict()`, it seems there might be a misunderstanding. The `predict()` method doesn't directly support `show_boxes=False` as an argument. Instead, you can control the visualization aspects (like hiding bounding boxes) when you're plotting or saving the results after prediction.

Here's a quick fix for saving the segmentation masks without bounding boxes:

```python
from pathlib import Path
import cv2
from ultralytics import YOLO

model = YOLO('yolov8n.pt')

for path in Path('dataset/').rglob('*.png'):
    results = model.predict(source=str(path))
    # Assuming you want to save the segmentation mask
    mask = results[0].masks.numpy()  # Convert masks to numpy array if needed
    # Save the mask using OpenCV
    cv2.imwrite('output/' + path.name, mask)
```

This code snippet directly accesses the segmentation masks and saves them. Note that `results[0].masks.numpy()` is a placeholder to indicate you might need to convert the masks to a suitable format for saving, depending on how your model outputs them. 

Hope this helps! Let me know if you have any more questions. 🚀

**Comment by codename-cn** [comment]
@glenn-jocher your code did not work for me.

Anyway, I managed to get it running with this code:

```python3
from PIL import Image
from ultralytics import YOLO

model = YOLO('yolov8n.pt')

results = model.predict(source='input.png')

img_array = results[0].plot(boxes=False)

img = Image.fromarray(img_array[..., ::-1])
img.save('output.png')
```

**Comment by glenn-jocher** [comment]
@codename-cn hey there! 🌟 I'm glad you found a solution that works for you. Your approach using PIL to handle the image array is spot on. Thanks for sharing your code; it might help others facing similar issues. If you have any more questions or run into other challenges, feel free to reach out. Happy coding! 🚀

**Comment by zai1318** [comment]
yolo predict model=best.pt source=8.jpg show_labels=False show_boxes=False
you can just simply put this code in the cmd and it will hide both labels and boxes, depending on whichever you want to hide.

**Comment by glenn-jocher** [comment]
@zai1318 hey there! 👋 Thanks for reaching out. To hide both labels and boxes during prediction, you can indeed use the `show_labels=False` and `show_boxes=False` arguments. However, these options are typically used when plotting or saving images programmatically in Python, rather than directly via the command line. Here's a quick Python example on how you might use them:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('best.pt')

# Perform prediction
results = model.predict(source='8.jpg')

# Plot or save without boxes and labels
img = results[0].plot(show_labels=False, show_boxes=False)
img.save('output.png')
```

This approach gives you the flexibility to control the visibility of labels and boxes in your output images. Let me know if this helps or if you have any more questions! 😊

**Comment by jehanjen** [comment]
@glenn-jocher hii,
 i want to detect by using yolov8 but the result detection  without of mask, just have bounding box ?

**Comment by glenn-jocher** [comment]
@jehanjen to achieve detection with only bounding boxes and no masks using YOLOv8, ensure you're using a detection model like `yolov8n.pt` instead of a segmentation model. If you have further questions, feel free to ask!

**Comment by zai1318** [comment]
> show_boxes=False

**Comment by glenn-jocher** [comment]
To hide bounding boxes during prediction, use the `plot()` method with `boxes=False` after obtaining the results.
