### ISSUE TITLE
Distributed run asks for existing best weights when specifying "device='0,1,2,3'" in model.train before initial training run

### ISSUE THREAD

**Issue by LaserRider** [ultralytics/ultralytics#500]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Multi-GPU

### Bug

Command spins up 4 GPUs, loads model but then attempts to load existing weights. It's not a path error, there is no best.pt saved. If I remove the device parameter, training runs fine.

"
FileNotFoundError: [Errno 2] No such file or directory: 'runs/detect/train/weights/best.pt'
"

Detailed:

ultralytics/yolo/engine/model.py in train(self, **kwargs)
    203         self.trainer.train()
    204         # update model and configs after training
--> 205         self.model, _ = attempt_load_one_weight(str(self.trainer.best))
    206         self.overrides = self.model.args
    207 

ultralytics_/ultralytics/nn/tasks.py in attempt_load_one_weight(weight, device, inplace, fuse)
    359     from ultralytics.yolo.utils.downloads import attempt_download
    360 
--> 361     ckpt = torch.load(attempt_download(weight), map_location='cpu')  # load
    362     args = {**DEFAULT_CONFIG_DICT, **ckpt['train_args']}  # combine model and default args, preferring model args
    363     model = (ckpt.get('ema') or ckpt['model']).to(device).float()  # FP32 model

### Minimal Reproducible Example

results = model.train(data="/my_data.yaml", epochs=100, imgsz=640, cache=True, device="0,1,2,3")

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ichsan2895** [comment]
Seems similar problem with this thread

https://github.com/ultralytics/ultralytics/issues/334

Their problem solved after updating to the newest yolo.

They also use CLI, for example
``
`yolo task=detect mode=train data="my_data.yaml" device=\'0,1,2,3\'
```

**Comment by AyushExel** [comment]
@LaserRider what's the version that you're using. You might want to update to the latest version by running `pip install --upgrade ultralytics`

**Comment by joelwebb** [comment]
On SageMaker, I am also running into a similar issue using python, not the CLI, for training with 4 GPUs and have upgraded ultalytics to 8.0.11. The exact same code works perfect on one GPU with device=0 or leaving off the device parameter.  Testing with V5loader=True didn't fix the issue. On my side, it looks like the training finishes but then it prints out an error for FileNotFoundError: [Errno 2] No such file or directory after training. Comparing times with the 4 GPUs vs running on one, it is running around ~4x faster, so it must be using the GPUs during training, but throwing an error after the training.

**Comment by AyushExel** [comment]
@glenn-jocher @Laughing-q are you guys aware of this issue?

**Comment by Laughing-q** [comment]
@joelwebb this happens after training right?
@AyushExel I'll try to reproduce later today.

**Comment by termlim** [comment]
Same issue arises when attempting to perform multi-gpu training via python:
`FileNotFoundError: [Errno 2] No such file or directory: 'runs/detect/train/weights/best.pt'`

This seems to occur with this line:
[https://github.com/ultralytics/ultralytics/blob/6eec39162a9f4153d1ce5f71102fdee3d64188ec/ultralytics/yolo/engine/model.py#L205](https://github.com/ultralytics/ultralytics/blob/6eec39162a9f4153d1ce5f71102fdee3d64188ec/ultralytics/yolo/engine/model.py#L205)

Where it attempts to load the `best.pt` weight when it does not exist.
Haven't tested with CLI, but from the reporting above, it seems like this is python specific issue.

**Comment by Gabijke** [comment]
> @glenn-jocher @Laughing-q Та же проблема возникает при попытке выполнить обучение с несколькими графическими процессорами через python: `FileNotFoundError: [Errno 2] No such file or directory: 'runs/detect/train/weights/best.pt'`
> 
> Кажется, это происходит с этой строкой:
> 
> https://github.com/ultralytics/ultralytics/blob/6eec39162a9f4153d1ce5f71102fdee3d64188ec/ultralytics/yolo/engine/model.py#L205
> 
> Где он пытается загрузить `best.pt`вес, когда он не существует. К вашему сведению, обучение прекращается сразу после этой ошибки, которая возникает сразу после `model.train()`вызова и завершается успешно.
> 
> Не тестировал CLI, но из приведенного выше отчета кажется, что это проблема, специфичная для python.
> 
> Ниже приведена команда python, используемая для обучения:
> 
> ```
> model = YOLO("yolov8n.pt") 
> model.train(device="0,1,2,3,4,5,6,7", data="custom.yaml", epochs=300, imgsz=640, workers=8, batch=128)
> ```

Yes, I also observe this error when starting with through Python

**Comment by joelwebb** [comment]
@Laughing-q  - yes, right after training is about to finish. Here is the log output where it starts to fail, happy to send you full outputs with training included if necessary. Watching it again this morning the training runs fine until the very end, and it fails exactly where @termlim calls out missing best.pt. Unless I am interpreting the attached logs incorrectly,  it looks like one of the GPU instances finds it and starts the next steps, but then a SIGTERM is thrown making the training fail(possibly from other workers on different GPUs that can't find the best.pt). 
[sagemaker_yolov8_parallel_failure_logs.pdf](https://github.com/ultralytics/ultralytics/files/10466658/sagemaker_yolov8_parallel_failure_logs.pdf)

**Comment by ashutoshIITK** [comment]
I am also facing the same issue. It is asking for best.pt file.

**Comment by joelwebb** [comment]
@Laughing-q  - any idea if version 8.0.12 fixes these issues?

**Comment by LaserRider** [comment]
@AyushExel tried on various releases, including the latest ones
the CLI input device=\'0,1,2,3\' works only for the default model, i.e. if you don't provide the "model" input
currently I see it failing after the first epoch, asking for best.pt again

**Comment by Laughing-q** [comment]
guys, I really can't reproduce the same error(can't find best.pt error) with python interface and DDP.
tested command:
```python
from ultralytics.yolo.engine.model import YOLO
import torch

model = YOLO("yolov8n.yaml")
model.train(data="runs/balloon.yaml", epochs=10, device="0,1,2,3", exist_ok=True, batch=32)
```
But I actually found another error which has fixed in this PR #700 . probably this fix also works for you guys?🤔
```bash
RuntimeError: PytorchStreamReader failed reading file data/265: invalid header or archive is corrupted
```

**Comment by Zigars** [comment]
Same issue as them,I uesd the 8.0.22 version and 8.0.23 version, but both of them doesn't work. the same error occured in docker images and CLI.
```bash 
yolo task=detect mode=train model=yolov8n.pt data=coco128.yaml device=\'0,1,2,3\'
```

**Comment by pderrenger** [comment]
@Zigars i understand your frustration. The `FileNotFoundError: [Errno 2] No such file or directory: 'runs/detect/train/weights/best.pt'` issue has been a point of concern among users. I recommend that you try using the latest version of YOLOv8, as several fixes and improvements have been made to address similar issues. In addition, please keep an eye on the ongoing discussions and updates in the PR #700, as it may provide a resolution to the problem you are encountering.

Feel free to reach out to the Ultralytics community for further assistance and to stay updated on any potential fixes. Thank you for your patience and understanding as we work to address this issue.
