### ISSUE TITLE
What really stands the "B" and "M" in Detect and Segmetation results.csv?

### ISSUE THREAD

**Issue by nuno1197** [ultralytics/ultralytics#5003]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I did two different trainings with two different "modes" of training, one through detect where I obtained the results in csv. This csv contained several metrics, some with a "(B)" (Precision(B) among others). 
I did another training session with segmentation, and I also got other metrics with (B) and (M) (Precision(B) or (M)).
I wanted to try to understand what this "B" and "M" meant in their context but I got more confused, because there are two different answers.

Here: #[11454](https://github.com/ultralytics/yolov5/issues/11454)

The "B" -> "(B) refers to the "best" performance metric achieved by the model during the training process."
The "M"->(M) refers to "macro" average, which calculates the average performance metric over each class.

But here :  [#1694](https://github.com/ultralytics/ultralytics/issues/1694)

The "B"-> Bounding Boxes
The "M" -> Masks

My question is, what does the "B" mean in the detect training "mode", in the segmentation training "mode", as well as the "M"?

Sorry if my question is stupid!

**Comment by glenn-jocher** [comment]
@nuno1197 Box and Mask

**Comment by nuno1197** [comment]
Thanks :)

**Comment by pderrenger** [comment]
@nuno1197 you're welcome! If you have any more questions or need further assistance, feel free to ask. Happy to help!
