### ISSUE TITLE
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

### ISSUE THREAD

**Issue by lpc-eol** [ultralytics/ultralytics#501]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I am training a detection model yolov8x with two 3090 GPUs in a single machine.

``yolo/engine/trainer: task=detect, mode=train, model=yolov8x.pt, data=datasets/SoccerNet_Tracking/player-ball.yaml, epochs=50, patience=50, batch=14, imgsz=1280, save=True, cache=False, device=0,1, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=False, seed=0, deterministic=True, single_cls=False, image_weights=True, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, retina_masks=False, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, hydra={'output_subdir': None, 'run': {'dir': '.'}}, v5loader=True, save_dir=runs/detect/train``

        Ultralytics YOLOv8.0.2 🚀 Python-3.9.15 torch-1.12.0 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)
                                                             CUDA:1 (NVIDIA GeForce RTX 3090, 24268MiB)
        Overriding model.yaml nc=80 with nc=2
        
                           from  n    params  module                                       arguments                     
          0                  -1  1      2320  ultralytics.nn.modules.Conv                  [3, 80, 3, 2]                 
          1                  -1  1    115520  ultralytics.nn.modules.Conv                  [80, 160, 3, 2]               
          2                  -1  3    436800  ultralytics.nn.modules.C2f                   [160, 160, 3, True]           
          3                  -1  1    461440  ultralytics.nn.modules.Conv                  [160, 320, 3, 2]              
          4                  -1  6   3281920  ultralytics.nn.modules.C2f                   [320, 320, 6, True]           
          5                  -1  1   1844480  ultralytics.nn.modules.Conv                  [320, 640, 3, 2]              
          6                  -1  6  13117440  ultralytics.nn.modules.C2f                   [640, 640, 6, True]           
          7                  -1  1   3687680  ultralytics.nn.modules.Conv                  [640, 640, 3, 2]              
          8                  -1  3   6969600  ultralytics.nn.modules.C2f                   [640, 640, 3, True]           
          9                  -1  1   1025920  ultralytics.nn.modules.SPPF                  [640, 640, 5]                 
         10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
         11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]                           
         12                  -1  3   7379200  ultralytics.nn.modules.C2f                   [1280, 640, 3]                
         13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
         14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]                           
         15                  -1  3   1948800  ultralytics.nn.modules.C2f                   [960, 320, 3]                 
         16                  -1  1    922240  ultralytics.nn.modules.Conv                  [320, 320, 3, 2]              
         17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]                           
         18                  -1  3   7174400  ultralytics.nn.modules.C2f                   [960, 640, 3]                 
         19                  -1  1   3687680  ultralytics.nn.modules.Conv                  [640, 640, 3, 2]              
         20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]                           
         21                  -1  3   7379200  ultralytics.nn.modules.C2f                   [1280, 640, 3]                
         22        [15, 18, 21]  1   8719894  ultralytics.nn.modules.Detect                [2, [320, 640, 640]]          
        Model summary: 365 layers, 68154534 parameters, 68154518 gradients, 258.1 GFLOPs
        
        Transferred 589/595 items from pretrained weights
        WARNING:__main__:
        *****************************************
        Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
        *****************************************
        DDP settings: RANK 0, WORLD_SIZE 2, DEVICE cuda:0
        Overriding model.yaml nc=80 with nc=2
        
                           from  n    params  module                                       arguments                     
          0                  -1  1      2320  ultralytics.nn.modules.Conv                  [3, 80, 3, 2]                 
          1                  -1  1    115520  ultralytics.nn.modules.Conv                  [80, 160, 3, 2]               
          2                  -1  3    436800  ultralytics.nn.modules.C2f                   [160, 160, 3, True]           
          3                  -1  1    461440  ultralytics.nn.modules.Conv                  [160, 320, 3, 2]              
          4                  -1  6   3281920  ultralytics.nn.modules.C2f                   [320, 320, 6, True]           
          5                  -1  1   1844480  ultralytics.nn.modules.Conv                  [320, 640, 3, 2]              
          6                  -1  6  13117440  ultralytics.nn.modules.C2f                   [640, 640, 6, True]           
          7                  -1  1   3687680  ultralytics.nn.modules.Conv                  [640, 640, 3, 2]              
          8                  -1  3   6969600  ultralytics.nn.modules.C2f                   [640, 640, 3, True]           
          9                  -1  1   1025920  ultralytics.nn.modules.SPPF                  [640, 640, 5]                 
         10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
         11             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]                           
         12                  -1  3   7379200  ultralytics.nn.modules.C2f                   [1280, 640, 3]                
         13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
         14             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]                           
         15                  -1  3   1948800  ultralytics.nn.modules.C2f                   [960, 320, 3]                 
         16                  -1  1    922240  ultralytics.nn.modules.Conv                  [320, 320, 3, 2]              
         17            [-1, 12]  1         0  ultralytics.nn.modules.Concat                [1]                           
         18                  -1  3   7174400  ultralytics.nn.modules.C2f                   [960, 640, 3]                 
         19                  -1  1   3687680  ultralytics.nn.modules.Conv                  [640, 640, 3, 2]              
         20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]                           
         21                  -1  3   7379200  ultralytics.nn.modules.C2f                   [1280, 640, 3]                
         22        [15, 18, 21]  1   8719894  ultralytics.nn.modules.Detect                [2, [320, 640, 640]]          
        Model summary: 365 layers, 68154534 parameters, 68154518 gradients, 258.1 GFLOPs
        
        Transferred 589/595 items from pretrained weights
        optimizer: SGD(lr=0.01) with parameter groups 97 weight(decay=0.0), 104 weight(decay=0.000546875), 103 bias
        train: Scanning /home/cihe-max/CQL-CIHE/ultralytics/datasets/SoccerNet_Tracking/labels/train.cache... 28500 images, 0 backgrounds, 0 corrup
        val: Scanning /home/cihe-max/CQL-CIHE/ultralytics/datasets/SoccerNet_Tracking/labels/val.cache... 14250 images, 0 backgrounds, 0 corrupt: 1
        Image sizes 1280 train, 1280 val
        Using 14 dataloader workers
        Logging results to runs/detect/train
        Starting training for 50 epochs...
        
              Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
               1/50        23G       1.22      2.463      1.041        139       1280: 100%|██████████| 2036/2036 [26:42<00:00,  1.27it/s]
                         Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1018/1018 [07:58<00:00,  2.13it/s]
                           all      14250     227557       0.83      0.721      0.729      0.413
        
              Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
               2/50      22.7G      1.174      2.166      1.028        158       1280: 100%|██████████| 2036/2036 [26:12<00:00,  1.29it/s]
                         Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1018/1018 [07:58<00:00,  2.13it/s]
                           all      14250     227557      0.816      0.714      0.728      0.417
        
              Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
               3/50      22.7G      1.184      2.198      1.028        100       1280: 100%|██████████| 2036/2036 [26:04<00:00,  1.30it/s]
                         Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1018/1018 [07:54<00:00,  2.15it/s]
                           all      14250     227557      0.836      0.694      0.718      0.414
        
              Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
               4/50      22.7G      1.171      2.135      1.034        142       1280: 100%|██████████| 2036/2036 [25:54<00:00,  1.31it/s]
                         Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1018/1018 [07:52<00:00,  2.15it/s]
                           all      14250     227557      0.823      0.714      0.726      0.418
        
              Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
               5/50      22.7G      1.141      2.058      1.025        206       1280: 100%|██████████| 2036/2036 [25:51<00:00,  1.31it/s]
                         Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1018/1018 [07:52<00:00,  2.15it/s]
                           all      14250     227557      0.833      0.719      0.735      0.429
        
              Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
          0%|          | 0/2036 [00:00<?, ?it/s]Exception ignored in: <function Image.__del__ at 0x7fade698ed30>
        Traceback (most recent call last):
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 4017, in __del__
            self.tk.call('image', 'delete', self.name)
        RuntimeError: main thread is not in main loop
               6/50      22.7G      1.074      2.071     0.9903        206       1280:   0%|          | 5/2036 [00:04<27:26,  1.23it/s]Exception ignored in: <function Variable.__del__ at 0x7fade7671430>
        Traceback (most recent call last):
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
            if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
        RuntimeError: main thread is not in main loop
        Exception ignored in: <function Variable.__del__ at 0x7fade7671430>
        Traceback (most recent call last):
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
            if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
        RuntimeError: main thread is not in main loop
        Exception ignored in: <function Variable.__del__ at 0x7fade7671430>
        Traceback (most recent call last):
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
            if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
        RuntimeError: main thread is not in main loop
        Exception ignored in: <function Variable.__del__ at 0x7fade7671430>
        Traceback (most recent call last):
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
            if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
        RuntimeError: main thread is not in main loop
        Exception ignored in: <function Image.__del__ at 0x7fade698ed30>
        Traceback (most recent call last):
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 4017, in __del__
            self.tk.call('image', 'delete', self.name)
        RuntimeError: main thread is not in main loop
        Exception ignored in: <function Variable.__del__ at 0x7fade7671430>
        Traceback (most recent call last):
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
            if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
        RuntimeError: main thread is not in main loop
        Exception ignored in: <function Variable.__del__ at 0x7fade7671430>
        Traceback (most recent call last):
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
            if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
        RuntimeError: main thread is not in main loop
        Exception ignored in: <function Variable.__del__ at 0x7fade7671430>
        Traceback (most recent call last):
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
            if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
        RuntimeError: main thread is not in main loop
        Exception ignored in: <function Variable.__del__ at 0x7fade7671430>
        Traceback (most recent call last):
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
            if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
        RuntimeError: main thread is not in main loop
        Exception ignored in: <function Image.__del__ at 0x7fade698ed30>
        Traceback (most recent call last):
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 4017, in __del__
            self.tk.call('image', 'delete', self.name)
        RuntimeError: main thread is not in main loop
        Exception ignored in: <function Variable.__del__ at 0x7fade7671430>
        Traceback (most recent call last):
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
            if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
        RuntimeError: main thread is not in main loop
        Exception ignored in: <function Variable.__del__ at 0x7fade7671430>
        Traceback (most recent call last):
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
            if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
        RuntimeError: main thread is not in main loop
        Exception ignored in: <function Variable.__del__ at 0x7fade7671430>
        Traceback (most recent call last):
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
            if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
        RuntimeError: main thread is not in main loop
        Exception ignored in: <function Variable.__del__ at 0x7fade7671430>
        Traceback (most recent call last):
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/tkinter/__init__.py", line 363, in __del__
            if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
        RuntimeError: main thread is not in main loop
        Tcl_AsyncDelete: async handler deleted by the wrong thread
        WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3390590 closing signal SIGTERM
        WARNING:torch.distributed.elastic.multiprocessing.api:Unable to shutdown process 3390590 via 15, forcefully exitting via 9
        ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 3390589) of binary: /home/cihe-max/anaconda3/envs/yolov8/bin/python
        Traceback (most recent call last):
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/runpy.py", line 197, in _run_module_as_main
            return _run_code(code, main_globals, None,
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/runpy.py", line 87, in _run_code
            exec(code, run_globals)
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/run.py", line 765, in <module>
            main()
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
            return f(*args, **kwargs)
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/run.py", line 761, in main
            run(args)
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
            elastic_launch(
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
            return launch_agent(self._config, self._entrypoint, list(args))
          File "/home/cihe-max/anaconda3/envs/yolov8/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
            raise ChildFailedError(
        torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
        ============================================================
        /home/cihe-max/.config/Ultralytics/DDP/_temp_mflprl3z140330287700384.py FAILED
        ------------------------------------------------------------
        Failures:
          <NO_OTHER_FAILURES>
        ------------------------------------------------------------
        Root Cause (first observed failure):
        [0]:
          time      : 2023-01-19_19:17:23
          host      : user-Super-Server
          rank      : 0 (local_rank: 0)
          exitcode  : -6 (pid: 3390589)
          error_file: <N/A>
          traceback : Signal 6 (SIGABRT) received by PID 3390589
        ============================================================

### Environment

Ultralytics YOLOv8.0.2 🚀 torch-1.12.0 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)  CUDA:1 (NVIDIA GeForce RTX 3090, 24268MiB).

-OS Ubuntu 20.04
-Python-3.9.15 

### Minimal Reproducible Example

yolo task=detect mode=train data=datasets/SoccerNet_Tracking/player-ball.yaml model=yolov8x.pt epochs=50 imgsz=1280 batch=14 image_weights=True device=\'0,1\' v5loader=True

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by jzw0707** [comment]
I met the same error, are your solving this problem?

**Comment by lpc-eol** [comment]
> I met the same error, are your solving this problem?

I haven't figured out the reason causing this problem, I restarted the training programme and modified the Linux sleep setting to never. 
There are few suggestions:
1. Internet connection 
2.

**Comment by lpc-eol** [comment]
> I met the same error, are your solving this problem?

I have yet to figure out the reason causing this problem. I restarted the training programme and modified the Linux sleep setting to never. 
There are a few suggestions:
1. Internet connection 
2. Linux system sleep setting
3. GPU memory overflow

**Comment by starsky68** [comment]
> > I met the same error, are your solving this problem?
> 
> I have yet to figure out the reason causing this problem. I restarted the training programme and modified the Linux sleep setting to never. There are a few suggestions:
> 
> 1. Internet connection
> 2. Linux system sleep setting
> 3. GPU memory overflow

请问有具体的解决方案吗

**Comment by lpc-eol** [comment]
Maybe you can take a reference from the following link.
https://github.com/ultralytics/ultralytics/issues/688#issuecomment-1407907496

**Comment by hnumrx** [comment]
It is possible that some data has not been moved to cuda
