### ISSUE TITLE
Loss Value Oscillation Problems ？

### ISSUE THREAD

**Issue by sunmooncode** [ultralytics/ultralytics#5010]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When the model is trained just after two epochs the losses are all Nan, I checked the data and there is no problem, so I modified the loss.py to add 1e-6 after each loss to get a solution. But after 47 epochs, the problem reappears.
![image](https://github.com/ultralytics/ultralytics/assets/86471590/6a7f1ac0-6a54-41cd-bee7-1a3e589bf6a8)

**Comment by sunmooncode** [comment]
These are my training parameters.
`
# Ultralytics YOLO 🚀, AGPL-3.0 license
# Default training settings and hyperparameters for medium-augmentation COCO training

task: detect  # (str) YOLO task, i.e. detect, segment, classify, pose
mode: train  # (str) YOLO mode, i.e. train, val, predict, export, track, benchmark

# Train settings -------------------------------------------------------------------------------------------------------
model: data/yolov8m-p2.yaml  # (str, optional) path to model file, i.e. yolov8n.pt, yolov8n.yaml
data:  # (str, optional) path to data file, i.e. coco128.yaml
epochs: 300  # (int) number of epochs to train for
patience: 50  # (int) epochs to wait for no observable improvement for early stopping of training
batch: 32  # (int) number of images per batch (-1 for AutoBatch)
imgsz: 640  # (int | list) input images size as int for train and val modes, or list[w,h] for predict and export modes
save: True  # (bool) save train checkpoints and predict results
save_period: -1 # (int) Save checkpoint every x epochs (disabled if < 1)
cache: False  # (bool) True/ram, disk or False. Use cache for data loading
device: 0,1,2,3 # (int | str | list, optional) device to run on, i.e. cuda device=0 or device=0,1,2,3 or device=cpu
workers: 4  # (int) number of worker threads for data loading (per RANK if DDP)
project: runs/detect/   # (str, optional) project name
name:  # (str, optional) experiment name, results saved to 'project/name' directory
exist_ok: False  # (bool) whether to overwrite existing experiment
pretrained: weights/yolov8m.pt  # (bool | str) whether to use a pretrained model (bool) or a model to load weights from (str)
optimizer: AdamW  # (str) optimizer to use, choices=[SGD, Adam, Adamax, AdamW, NAdam, RAdam, RMSProp, auto]
verbose: True  # (bool) whether to print verbose output
seed: 0  # (int) random seed for reproducibility
deterministic: True  # (bool) whether to enable deterministic mode
single_cls: False  # (bool) train multi-class data as single-class
rect: False  # (bool) rectangular training if mode='train' or rectangular validation if mode='val'
cos_lr: False  # (bool) use cosine learning rate scheduler
close_mosaic: 10  # (int) disable mosaic augmentation for final epochs
resume: True  # (bool) resume training from last checkpoint
amp: True  # (bool) Automatic Mixed Precision (AMP) training, choices=[True, False], True runs AMP check
fraction: 1.0  # (float) dataset fraction to train on (default is 1.0, all images in train set)
profile: False  # (bool) profile ONNX and TensorRT speeds during training for loggers
# Segmentation
overlap_mask: True  # (bool) masks should overlap during training (segment train only)
mask_ratio: 4  # (int) mask downsample ratio (segment train only)
# Classification
dropout: 0.0  # (float) use dropout regularization (classify train only)

# Val/Test settings ----------------------------------------------------------------------------------------------------
val: True  # (bool) validate/test during training
split: val  # (str) dataset split to use for validation, i.e. 'val', 'test' or 'train'
save_json: False  # (bool) save results to JSON file
save_hybrid: False  # (bool) save hybrid version of labels (labels + additional predictions)
conf: 0.75 # (float, optional) object confidence threshold for detection (default 0.25 predict, 0.001 val)
iou: 0.5  # (float) intersection over union (IoU) threshold for NMS
max_det: 300  # (int) maximum number of detections per image
half: False  # (bool) use half precision (FP16)
dnn: False  # (bool) use OpenCV DNN for ONNX inference
plots: True  # (bool) save plots during train/val

# Prediction settings --------------------------------------------------------------------------------------------------
source:  # (str, optional) source directory for images or videos
show: False  # (bool) show results if possible
save_txt: False  # (bool) save results as .txt file
save_conf: False  # (bool) save results with confidence scores
save_crop: False  # (bool) save cropped images with results
show_labels: True  # (bool) show object labels in plots
show_conf: True  # (bool) show object confidence scores in plots
vid_stride: 1  # (int) video frame-rate stride
line_width:   # (int, optional) line width of the bounding boxes, auto if missing
visualize: False  # (bool) visualize model features
augment: False  # (bool) apply image augmentation to prediction sources
agnostic_nms: False  # (bool) class-agnostic NMS
classes:  # (int | list[int], optional) filter results by class, i.e. class=0, or class=[0,2,3]
retina_masks: False  # (bool) use high-resolution segmentation masks
boxes: True  # (bool) Show boxes in segmentation predictions

# Export settings ------------------------------------------------------------------------------------------------------
format: torchscript  # (str) format to export to, choices at https://docs.ultralytics.com/modes/export/#export-formats
keras: False  # (bool) use Kera=s
optimize: False  # (bool) TorchScript: optimize for mobile
int8: False  # (bool) CoreML/TF INT8 quantization
dynamic: False  # (bool) ONNX/TF/TensorRT: dynamic axes
simplify: False  # (bool) ONNX: simplify model
opset:  # (int, optional) ONNX: opset version
workspace: 4  # (int) TensorRT: workspace size (GB)
nms: False  # (bool) CoreML: add NMS

# Hyperparameters ------------------------------------------------------------------------------------------------------
lr0: 0.0001  # (float) initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
lrf: 0.01  # (float) final learning rate (lr0 * lrf)
momentum: 0.937  # (float) SGD momentum/Adam beta1
weight_decay: 0.001  # (float) optimizer weight decay 5e-4
warmup_epochs: 3.0  # (float) warmup epochs (fractions ok)
warmup_momentum: 0.8  # (float) warmup initial momentum
warmup_bias_lr: 0.1  # (float) warmup initial bias lr
box: 7.5  # (float) box loss gain
cls: 0.5  # (float) cls loss gain (scale with pixels)
dfl: 1.5  # (float) dfl loss gain
pose: 12.0  # (float) pose loss gain
kobj: 1.0  # (float) keypoint obj loss gain
label_smoothing: 0.0  # (float) label smoothing (fraction)
nbs: 128  # (int) nominal batch size
hsv_h: 0.015  # (float) image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # (float) image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # (float) image HSV-Value augmentation (fraction)
degrees: 0.0  # (float) image rotation (+/- deg)
translate: 0.1  # (float) image translation (+/- fraction)
scale: 0.5  # (float) image scale (+/- gain)
shear: 0.0  # (float) image shear (+/- deg)
perspective: 0.0  # (float) image perspective (+/- fraction), range 0-0.001
flipud: 0.5  # (float) image flip up-down (probability)
fliplr: 0.5  # (float) image flip left-right (probability)
mosaic: 1.0  # (float) image mosaic (probability)
mixup: 0.4  # (float) image mixup (probability)
copy_paste: 0.0  # (float) segment copy-paste (probability)

# Custom config.yaml ---------------------------------------------------------------------------------------------------
cfg:  # (str, optional) for overriding defaults.yaml

# Tracker settings ------------------------------------------------------------------------------------------------------
tracker: botsort.yaml  # (str) tracker type, choices=[botsort.yaml, bytetrack.yaml]
`

**Comment by glenn-jocher** [comment]
@sunmooncode thank you for reaching out with your training parameters in YOLOv8. Overall your configuration seems well-set for most tasks. Without specific information about your use case or any problems you're encountering, it's a bit hard to give specific advice.

However, I would like to point out that your selection of image augmentations can have a big impact on the model's performance. Parameters such as 'degrees', 'translate', 'scale', 'shear', 'perspective', 'flipud', 'fliplr', 'mosaic', 'mixup', 'copy_paste' are all related to augmentations in your dataset. Carefully adjust these depending on your specific use-case.

Additionally, for your optimizer, you are currently using 'AdamW'. Depending upon your dataset and model complexity, you might want to experiment with other optimizers like 'SGD', 'Adam', 'Adamax', etc. as well, to see which gives better results.

Finally, be mindful of training for many epochs without improvement. 'Patience' is currently set at 50, meaning it will keep training for 50 epochs without observed improvement before stopping. Tune this depending upon your system's computation power and the time you are willing to spend on training. 

Remember that training a deep learning model involves lot of parameter tuning and experimentation. What works best largely depends on your specific dataset and task. I hope this helps, and please don't hesitate to reach out if you have further questions or need more assistance.

**Comment by sunmooncode** [comment]
@glenn-jocher The occurrence of NaN and Inf in the val_loss."What is the reason for this?"
```

                  epoch,         train/box_loss,         train/cls_loss,         train/dfl_loss,   metrics/precision(B),      metrics/recall(B),       metrics/mAP50(B),    metrics/mAP50-95(B),           val/box_loss,           val/cls_loss,           val/dfl_loss,                 lr/pg0,                 lr/pg1,                 lr/pg2
                      1,                 2.1769,                 5.2344,                 2.1134,                0.15088,                0.01789,                0.08443,                 0.0703,                  1.418,                 3.7803,                 1.5478,               0.066701,             3.3332e-05,             3.3332e-05
                      2,                 1.5104,                 3.8213,                 1.5319,                0.20674,                 0.0205,                0.11423,                0.09692,                 1.3787,                 3.7993,                 1.4612,               0.033401,             6.6445e-05,             6.6445e-05
                      3,                  1.292,                 3.0198,                 1.3569,                0.10167,                0.00262,                0.05216,                0.04336,                 1.5785,                 4.1157,                  1.553,             0.00010074,             9.9339e-05,             9.9339e-05
                      4,                 1.1606,                 2.4776,                 1.2561,                0.14721,                0.00534,                0.07628,                0.06582,                 1.4053,                 4.0408,                 1.4385,              9.901e-05,              9.901e-05,              9.901e-05
                      5,                 1.0847,                 2.1537,                 1.2012,                0.54849,                0.03568,                0.29214,                0.26276,                 1.1113,                  3.411,                 1.2618,              9.901e-05,              9.901e-05,              9.901e-05
                      6,                 1.0301,                 1.9361,                 1.1609,                0.93258,                0.17163,                0.55218,                0.50085,                 0.8827,                 2.0689,                 1.1058,              9.868e-05,              9.868e-05,              9.868e-05
                      7,                0.99249,                   1.79,                 1.1366,                0.97438,                0.34538,                0.65981,                0.59909,                0.76939,                 1.4109,                 1.0283,              9.835e-05,              9.835e-05,              9.835e-05
                      8,                0.96292,                 1.6724,                 1.1163,                0.96708,                0.46794,                0.71768,                0.64943,                 0.7192,                 1.1091,                0.98973,              9.802e-05,              9.802e-05,              9.802e-05
                      9,                0.93657,                 1.5804,                 1.1001,                0.96118,                 0.5418,                0.75241,                0.67909,                0.69044,                 0.9628,                0.96753,              9.769e-05,              9.769e-05,              9.769e-05
                     10,                0.91515,                 1.5003,                 1.0847,                0.95329,                0.58799,                0.77056,                 0.6945,                0.67041,                 0.8996,                0.95233,              9.736e-05,              9.736e-05,              9.736e-05
                     11,                0.90096,                 1.4418,                 1.0759,                 0.9495,                0.61986,                0.78492,                0.70717,                0.65611,                    inf,                 0.9417,              9.703e-05,              9.703e-05,              9.703e-05
                     12,                0.88624,                 1.3966,                 1.0674,                0.94673,                0.64241,                0.79451,                0.71582,                0.64521,                    inf,                0.93342,               9.67e-05,               9.67e-05,               9.67e-05
                     13,                0.87384,                 1.3509,                 1.0588,                0.94446,                0.65822,                0.80188,                  0.723,                 0.6355,                    inf,                0.92653,              9.637e-05,              9.637e-05,              9.637e-05
                     14,                0.86002,                  1.308,                 1.0517,                0.94231,                0.67098,                0.80751,                 0.7287,                0.62715,                    inf,                0.92088,              9.604e-05,              9.604e-05,              9.604e-05
                     15,                0.84942,                  1.272,                  1.044,                0.94096,                0.68255,                0.81286,                0.73408,                0.61936,                    inf,                0.91556,              9.571e-05,              9.571e-05,              9.571e-05
                     16,                0.84102,                 1.2403,                 1.0386,                0.94131,                 0.6909,                0.81787,                 0.7395,                0.61321,                    inf,                0.91142,              9.538e-05,              9.538e-05,              9.538e-05
                     17,                0.83126,                 1.2126,                 1.0331,                0.94099,                0.69706,                0.82052,                 0.7426,                0.60739,                    inf,                0.90785,              9.505e-05,              9.505e-05,              9.505e-05
                     18,                0.82467,                 1.1865,                 1.0283,                 0.9409,                0.70357,                0.82441,                0.74701,                0.60199,                    inf,                0.90435,              9.472e-05,              9.472e-05,              9.472e-05
                     19,                0.81598,                 1.1615,                 1.0232,                0.94067,                0.70936,                0.82712,                 0.7502,                0.59746,                    inf,                0.90112,              9.439e-05,              9.439e-05,              9.439e-05
                     20,                0.81288,                 1.1469,                 1.0213,                0.94116,                0.71407,                0.83002,                0.75329,                0.59326,                    inf,                0.89868,              9.406e-05,              9.406e-05,              9.406e-05
                     21,                 0.8074,                 1.1295,                 1.0175,                 0.9416,                0.71952,                0.83292,                0.75622,                0.58935,                0.63667,                0.89571,              9.373e-05,              9.373e-05,              9.373e-05
                     22,                0.79849,                 1.1048,                 1.0125,                0.94336,                0.72193,                0.83639,                0.76049,                0.58578,                0.60663,                0.89348,               9.34e-05,               9.34e-05,               9.34e-05
                     23,                0.79433,                 1.0962,                 1.0107,                0.94392,                0.72525,                0.83892,                0.76357,                0.58187,                0.59588,                0.89119,              9.307e-05,              9.307e-05,              9.307e-05
                     24,                0.78875,                 1.0758,                 1.0073,                0.94443,                0.72903,                0.84127,                0.76606,                0.57908,                0.58725,                0.88949,              9.274e-05,              9.274e-05,              9.274e-05
                     25,                0.78642,                 1.0653,                 1.0047,                0.94472,                0.73047,                0.84236,                0.76769,                0.57606,                0.57841,                0.88731,              9.241e-05,              9.241e-05,              9.241e-05
                     26,                0.78017,                 1.0489,                 1.0013,                0.94538,                0.73429,                0.84446,                0.77011,                0.57335,                0.57115,                0.88591,              9.208e-05,              9.208e-05,              9.208e-05
                     27,                0.77595,                 1.0349,                 0.9988,                0.94572,                0.73695,                0.84596,                0.77175,                0.57115,                0.56475,                0.88465,              9.175e-05,              9.175e-05,              9.175e-05
                     28,                0.77285,                 1.0289,                 0.9978,                0.94482,                0.74041,                0.84718,                0.77321,                0.56871,                0.55929,                0.88341,              9.142e-05,              9.142e-05,              9.142e-05
                     29,                0.77004,                 1.0173,                0.99578,                 0.9457,                0.74284,                0.84904,                0.77539,                0.56632,                0.55235,                0.88204,              9.109e-05,              9.109e-05,              9.109e-05
                     30,                0.76483,                  1.004,                0.99271,                0.94566,                0.74524,                0.85024,                 0.7766,                0.56454,                0.54695,                0.88091,              9.076e-05,              9.076e-05,              9.076e-05
                     31,                 0.7629,                0.99454,                0.99072,                0.94598,                 0.7469,                0.85116,                0.77773,                 0.5629,                0.54243,                0.87933,              9.043e-05,              9.043e-05,              9.043e-05
                     32,                0.75904,                0.98633,                0.98932,                0.94594,                0.74965,                 0.8528,                0.77949,                0.56157,                0.53815,                0.87804,               9.01e-05,               9.01e-05,               9.01e-05
                     33,                0.75721,                0.97966,                0.98616,                0.94587,                0.75121,                0.85362,                0.78076,                0.55924,                0.53267,                0.87672,              8.977e-05,              8.977e-05,              8.977e-05
                     34,                0.75413,                 0.9692,                0.98551,                0.94647,                0.75317,                0.85485,                0.78221,                0.55797,                0.52858,                0.87556,              8.944e-05,              8.944e-05,              8.944e-05
                     35,                0.74931,                0.95798,                0.98276,                0.94636,                0.75537,                0.85606,                0.78374,                0.55613,                0.52572,                0.87439,              8.911e-05,              8.911e-05,              8.911e-05
                     36,                0.74774,                0.95115,                0.98202,                0.94643,                0.75561,                0.85625,                0.78407,                 0.5552,                0.52405,                0.87365,              8.878e-05,              8.878e-05,              8.878e-05
                     37,                0.75041,                0.95331,                0.98232,                0.94697,                  0.756,                0.85636,                0.78441,                0.55406,                0.52139,                0.87321,              8.845e-05,              8.845e-05,              8.845e-05
                     38,                0.74737,                 0.9497,                0.98127,                  0.946,                0.75857,                0.85735,                0.78526,                0.55323,                0.51891,                 0.8729,              8.812e-05,              8.812e-05,              8.812e-05
                     39,                0.74594,                0.94204,                0.98066,                0.94663,                0.75928,                 0.8579,                0.78593,                0.55256,                0.51621,                0.87233,              8.779e-05,              8.779e-05,              8.779e-05
                     40,                0.74174,                0.93416,                0.97795,                0.94706,                0.76063,                0.85902,                0.78732,                0.55077,                0.51256,                0.87156,              8.746e-05,              8.746e-05,              8.746e-05
                     41,                0.73951,                0.92971,                0.97605,                0.94753,                0.76181,                0.86003,                0.78867,                0.54971,                0.50949,                0.87051,              8.713e-05,              8.713e-05,              8.713e-05
                     42,                0.73712,                0.92297,                0.97433,                0.94713,                0.76221,                0.85994,                0.78883,                0.54848,                0.50695,                0.86935,               8.68e-05,               8.68e-05,               8.68e-05
                     43,                0.73597,                0.91628,                0.97362,                0.94772,                0.76378,                0.86083,                 0.7898,                0.54766,                0.50513,                0.86892,              8.647e-05,              8.647e-05,              8.647e-05
                     44,                0.73478,                0.91242,                0.97367,                0.94751,                0.76405,                0.86112,                0.79022,                0.54623,                0.50284,                0.86822,              8.614e-05,              8.614e-05,              8.614e-05
                     45,                  0.733,                  0.909,                 0.9711,                0.94851,                0.76535,                 0.8621,                0.79134,                0.54522,                0.50023,                0.86736,              8.581e-05,              8.581e-05,              8.581e-05
                     46,                0.72982,                0.89804,                0.96962,                0.94818,                0.76706,                 0.8627,                0.79201,                0.54421,                0.49804,                0.86673,              8.548e-05,              8.548e-05,              8.548e-05
                     47,                    nan,                    nan,                    nan,                0.94836,                0.73889,                0.84927,                0.77858,                    nan,                    nan,                    nan,              8.515e-05,              8.515e-05,              8.515e-05
                     48,                0.72712,                0.88907,                 0.9679,                0.94837,                0.73917,                0.84935,                0.77891,                    nan,                    nan,                    nan,              8.482e-05,              8.482e-05,              8.482e-05
                     47,                0.72002,                0.86876,                0.96486,                0.94724,                0.76883,                0.86327,                0.79237,                0.54384,                0.49719,                0.86631,              8.515e-05,              8.515e-05,              8.515e-05

```

**Comment by sunmooncode** [comment]
Where I can find the code for calculating the validation loss?

**Comment by glenn-jocher** [comment]
@sunmooncode hello,

Thanks for reaching out with your question!

The validation loss calculation can be found in the training loop of the main script.

Specifically, once an epoch of training is completed, the model is set into evaluation mode with `model.eval()`. In this mode, batch-wise validation data is then passed through the model, and the loss is computed and stored. This loss reflects how close the predictions of the model are to the actual values in our validation set.

Keep in mind that the validation loss is calculated in the same way as the training loss but using the validation data instead of the training data. The specific loss function used depends on the one defined during the model configuration.

Please note that the model parameters are not updated during validation, thus the model does not learn anything from this data. The purpose of this process is primarily to monitor the performance of the model on unseen data, and to avoid overfitting.

I hope this answers your question, but if you have further inquiries, don't hesitate to ask.

Best Regards

**Comment by sunmooncode** [comment]
Does this mean that the val loss has no impact on the train loss? After encountering Nan in the train loss, I added 1e-6 after the three losses to prevent it from happening again, but it doesn't seem to have any effect. The result above shows that even after adding 1e-6 to all three losses, it still turns into Nan.

**Comment by glenn-jocher** [comment]
@sunmooncode,

Correct, the validation loss does not directly impact the training loss. The role of validation loss is to assess model performance on unseen data, providing insights on how well the model generalizes. However, indirectly, we do use the validation metrics to adjust hyperparameters and prevent overfitting through techniques like early stopping.

Regarding the appearance of `NaN` in your training loss, there could be multiple causes. Here are some common reasons that might lead to `NaN` values in your loss during training:

1. **Learning Rate:** A learning rate that's too high can cause the model's weights to update in such large increments that the loss escalates to `NaN`. 

2. **Data Issues:** Even though you mentioned checking the data, it might be worth revisiting this, ensuring there are no corrupt or overly large/small values that could throw off the loss calculations.

3. **Numerical Stability:** While adding a small epsilon (1e-6) can help in some cases, other parts of the loss function or downstream calculations could still be causing instability.

4. **Model Architecture:** Issues in the model configuration, such as extremely large weight initializations, could also result in `NaN` values.

5. **Batch Normalization:** If you aren’t careful with your batch sizes or have too small a batch, batch normalization layers can sometimes cause numerical instability.

Troubleshooting these `NaN` values can be tricky. Here's what you might consider doing:

- Double-check the data preprocessing steps to ensure the inputs to your model are within a reasonable range.
- Try using a much smaller learning rate, or employ learning rate schedulers that adjust the rate over time.
- Gradually simplify your model or reduce the complexity to identify if any particular layer or block is responsible.
- Implement gradient clipping to avoid large updates in weights.

Moreover, inspect the training procedure to catch when exactly `NaN` values appear and under what circumstances (e.g., during backpropagation, after a particular layer, etc.).

I understand this can be frustrating, but these challenges are part of the iterative process of training robust deep learning models. Keep experimenting with controlled changes, and track the outcomes to guide you toward the source of the instability.

If you continue to face difficulties, consider visiting the YOLOv8 repository discussions or submitting an issue with detailed logs and reproducible steps. The Ultralytics team and the community could possibly provide more help.

Best of luck with your model training!
