### ISSUE TITLE
ONNX exported model does not run faster on CPU

### ISSUE THREAD

**Issue by xaristeidou** [ultralytics/ultralytics#5017]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I exported "yolov8m.pt" in ONNX format, then loaded onnx model and run inference. 

```
from ultralytics import YOLO

model = YOLO("yolov8m.pt")
model.export(format = "onnx")

model = YOLO("yolov8m.onnx")

model.predict(source = 0, device = "cpu")
```

When I load `"yolov8m.pt"` and run inference using `device = "cpu"`, my inference time is 165ms - 235ms

When I load `"yolov8m.onnx" `and run inference using `device = "cpu"`, my inference time is 260ms - 270ms

CPU: Ryzen 7 5800H

Why does ONNX model runs even slower on CPU?

**Comment by RizwanMunawar** [comment]
@xaristeidou! I've conducted tests using the PyTorch and Onnx models, and I've observed a notable increase in speed when utilizing Onnx. The encountered error is more likely associated with the CPU device `Ryzen 7 5800H`, whereas successful testing has been performed on an `Intel CPU`.

### Pytorch

```
0: 480x640 1 person, 1 bench, 1 chair, 2 couches, 1 potted plant, 528.9ms
0: 480x640 1 person, 1 bench, 1 chair, 1 couch, 1 potted plant, 536.5ms
0: 480x640 1 person, 1 chair, 2 couches, 1 potted plant, 515.9ms
```

### Onnx

```
0: 640x640 1 person, 1 chair, 2 couches, 1 potted plant, 2 cell phones, 322.2ms
0: 640x640 1 person, 1 chair, 2 couches, 1 potted plant, 1 cell phone, 323.0ms
0: 640x640 1 person, 2 chairs, 2 couches, 1 potted plant, 1 cell phone, 315.4ms
```

Thanks

**Comment by RizwanMunawar** [comment]
I am closing this issue. Please reopen if the issue persists
