### ISSUE TITLE
Can not run Val with onnx model and a shape miss match between train and val

### ISSUE THREAD

**Issue by AbdelsalamHaa** [ultralytics/ultralytics#502]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Validation

### Bug

I have exported the model to onnx.
I tried to validate the model with the onnx model but I get an ![D4D67F33-C3AD-4840-A937-89D961EC034A](https://user-images.githubusercontent.com/35866217/213485618-8df84adb-8711-4dc1-81b7-fc65d3e6a172.jpeg)

### Environment

Yolov8 torch 1.13 +cuda 11
Python 3.9

### Minimal Reproducible Example

Yolo task=detect mode=Val  model=./best.onnx data= ./data.yaml device=cpu 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AbdelsalamHaa** [comment]
I have debugged the issue. I found out that model class doesn't have another variable named model when the model is ONNX. 

I managed to solve that but then I got into another error with the shape. Apparently, the data loaders will not change the images to square images. it actually depends on the input image. like in my case the data loader during training has the size of 360x640. But if I run val.py It will have the shape of 384x672. I think this is because of the 32 padding. 

Although the shape is not right val.py with pt model is still working. But when running with onnx model I get the following error


```
Error executing job with overrides: ['model=./yolo8n.onnx', 'data=./BubbleDataset.yaml', 'device=cpu']
Traceback (most recent call last):
  File "C:\Users\User\Documents\Abdelsalam\Yolo5_traningCode\ultralytics\ultralytics\yolo\v8\detect\val.py", line 243, in val
    validator(model=cfg.model)
  File "C:\Users\User\anaconda3\envs\yolo8env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\User\anaconda3\envs\yolo8env\lib\site-packages\ultralytics\yolo\engine\validator.py", line 145, in __call__
    preds = model(batch["img"])
  File "C:\Users\User\anaconda3\envs\yolo8env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\User\anaconda3\envs\yolo8env\lib\site-packages\ultralytics\nn\autobackend.py", line 262, in forward
    y = self.session.run(self.output_names, {self.session.get_inputs()[0].name: im})
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: images for the following indices
 index: 2 Got: 384 Expected: 640
 index: 3 Got: 672 Expected: 640
 Please fix either the inputs or the model.
```

I debugged around but couldn't really find the exact source of the issue. Also I'm not sure if the shape was intended to be this way or it should be square images

**Comment by AbdelsalamHaa** [comment]
@AyushExel
I would be very glad if you could comment on this. Also, I don't mind working on this and try to fix it. But wanted to clarify this behaviour and wanted to check  wither it is intended or not.

**Comment by AyushExel** [comment]
@AbdelsalamHaa thanks for tagging me. I respond to tags more frequently.
First, can you update the package if you haven't already to make sure the problem still exists? 
Exports have been built by Glenn so I have less context about what the problem could be. But if you confirm the issue still exists in the latest version I'll tag him

**Comment by AbdelsalamHaa** [comment]
Hi @AyushExel, thank you for your reply. I have update to the latest version. But the issue still the same. 

I also wonder if the image size during training should be a square image or it should follow the same ratio between w or h. Current code is not a square images.

**Comment by AbdelsalamHaa** [comment]
@AyushExel Hi any update on this 
Thanks

**Comment by sakshamprakash01** [comment]
@AbdelsalamHaa  were you able to solve the issue? It still persists as of ultralytics version 8.0.91
fyi @AyushExel

**Comment by glenn-jocher** [comment]
@sakshamprakash01 thank you for letting us know that you were able to solve the issue. Passing the imgsz parameter sets the input image size for the network, which helped you get the model working with your input images. In the future, if you have any further issues with YOLOv8, please don't hesitate to reach out to us for support.
