### ISSUE TITLE
How can I change the working directory with Ray Tune ?

### ISSUE THREAD

**Issue by Miroun** [ultralytics/ultralytics#5022]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I don't understand how I can set the directory for ray Tune because like #4997, I feel I am facing path problem which is not my fault. This might also be related to a bug.

To sum up for the first problem :  A file is recognized by the train function but not the tune one.

When I use the code for a training, it works fine:

```
    model = YOLO('yolov8s-seg.pt')
    # results = model.train(data="small.yaml",device="0",batch=32,epochs=300, imgsz=640,seed=18,patience=50,save_period=50, cache=False,project=f"small_results_2")
```

When I using the code for a tuning, it does not detect the file anymore : 

```
    model = YOLO('yolov8s-seg.pt')
    result_grid = model.tune(data="small.yaml",
                         epochs=50,
                         use_ray=True,gpu_per_trial=1)
```

I tried to take an inner look into the code and found this line in checks.py :

`       files = glob.glob(str(ROOT / 'cfg' / '**' / file), recursive=True)`

Which makes me able, I might be wrong, to see that the directory is :

`C:\Users\pseudo\AppData\Local\Programs\Python\Python38\Lib\site-packages\ultralytics`

So I used an absolute path and now the tuning starts (it might also be related to the problem #4997). I have the feeling that raytune is not using the location of the script as the "current" directory. 

I also get those kind of warnings while looking at the std_out and I do not know how I can change this :

1) Exception in thread WARNING  TensorBoard not initialized correctly, not logging this run. [Errno 2] No such file or directory: b'runs\\segment\\train\\events.out.tfevents.1695300730.DESKTOP-OF9E4E1.29756.2'

2) Could not upload checkpoint to c://\Users\Haroun\Desktop\yolov8\runs\detect\tune8\_tune_2023-09-21_14-46-07\_tune_d9d21_00002_2_box=0.1487,cls=3.8442,copy_paste=0.3222,degrees=36.1742f the credentials expired and that the remote filesystem is supported. For large checkpoints or artifacts, consider increasing `SyncConfig(sync_timeout)` (current value: 1800 seconds).

3) I also do not understand why ray tune tried to save in run/detect/XXX since I am clearly using a seg model with a segmentation dataset.

`c://\Users\pseudo\Desktop\yolov8\runs\detect\tune9\_tune_2023-09-21_15-00-57`

Thanks for your help.

**Comment by glenn-jocher** [comment]
@Miroun RayTune is working correctly for me in Colab. You can define a custom logging dir using the `project` and `name` arguments to log to `project/name`

**Comment by glenn-jocher** [comment]
<img width="1768" alt="Screenshot 2023-09-21 at 16 48 47" src="https://github.com/ultralytics/ultralytics/assets/26833433/cc581287-7ba7-49b7-86cb-8cdb4b2d5958">

**Comment by lyzyn** [comment]
> <img alt="截图 2023-09-21 16 48 47" width="1768" src="https://user-images.githubusercontent.com/26833433/269676254-cc581287-7ba7-49b7-86cb-8cdb4b2d5958.png">

May I ask what version of Ray you are using? The version I use is Ray 2.7.0, and the same problem has occurred. Now I wonder if the problem is due to the version.This issue is very troubling for me and I hope to receive your reply.

**Comment by glenn-jocher** [comment]
@lyzyn hello,

Thanks for bringing this to my attention. There can indeed be issues that arise due to different versions of third-party packages like Ray. It's important to ensure that all dependencies, including Ray, are up-to-date and compatible with YOLOv8.

Firstly, I recommend you make sure you're using the latest version of YOLOv8. We continually make updates and fixes that often resolve these sorts of issues. If you're already using the latest version of YOLOv8, then it might be worth trying a couple of different versions of Ray to see if this resolves the problem.

If trying different versions of Ray doesn't work, it would be helpful to get a bit more information about the exact error you're seeing. If you could describe what happens when the error occurs, and any error messages you're getting, that would be very helpful in diagnosing the problem.

Best,
Glenn

**Comment by Petros626** [comment]
@glenn-jocher How can bring `Ray Tune` to save the results in the default folder `~/ray_results`? 

In my current implementation it uses alway the default of `settings.json`, which is `"weights_dir": "/home/rlab10/ultralytics_yolov8-obb_ob_kitti/ultralytics/weights",
  "runs_dir": "/home/rlab10/ultralytics_yolov8-obb_ob_kitti/ultralytics/runs",`. I've set the `project=kitti_bev_yolo_rayt` and `name=tune_experiment` in `model.tune()`.
  
  Thank you!

**Comment by glenn-jocher** [comment]
To save Ray Tune results in the default `~/ray_results` folder, you can override the storage path used by the `run_ray_tune` function. Set `storage_path="~/ray_results"` in the `RunConfig` within the `model.tune()` method. For more details, refer to [Ray Tune integration in the YOLO Docs](https://docs.ultralytics.com/integrations/ray-tune/). Let us know if you need further clarification!

**Comment by Petros626** [comment]
Unfortunately the guide don't describe that, it's a `Ray Tune` realted issue.

**Comment by glenn-jocher** [comment]
For Ray Tune to save results in the `~/ray_results` directory, ensure you set `storage_path="~/ray_results"` in the `RunConfig` when calling `model.tune()`. You can refer to the [Ray Tune documentation](https://docs.ray.io/en/latest/tune/index.html) for additional details.
