### ISSUE TITLE
How to obtain the bounding box information predicted by yolov8

### ISSUE THREAD

**Issue by Xiao-Qi-Guai** [ultralytics/ultralytics#5024]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In object detection, how can I obtain and save the predicted categories, bounding box centers, lengths, and widths of the targets from yolov8?

**Comment by RizwanMunawar** [comment]
@Xiao-Qi-Guai, you can obtain the desired information using the following sample code:

```python
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('yolov8n.pt')

# Perform inference on an image
results = model('https://ultralytics.com/images/bus.jpg')

# Extract bounding boxes, classes, names, and confidences
boxes = results[0].boxes.xyxy.tolist()
classes = results[0].boxes.cls.tolist()
names = results[0].names
confidences = results[0].boxes.conf.tolist()

# Iterate through the results
for box, cls, conf in zip(boxes, classes, confidences):
    x1, y1, x2, y2 = box
    confidence = conf
    detected_class = cls
    name = names[int(cls)]
```

**Comment by RizwanMunawar** [comment]
I am closing this issue. Please reopen if the issue persists
