### ISSUE TITLE
pip install ultralytics (ERROR: No matching distribution found for ultralytics)

### ISSUE THREAD

**Issue by b3r-prog** [ultralytics/ultralytics#503]
I am trying to install the pip install the repo but getting errors

`pip install ultralytics` _ERROR: Could not find a version that satisfies the requirement ultralytics (from versions: none)_
_ERROR: No matching distribution found for ultralytics_

When i try the alternative approach and clone `git clone https://github.com/ultralytics/ultralytics.git` and `pip install -e .`, i get a gitpython version error _ERROR: No matching distribution found for GitPython>=3.1.24_

Any suggestions on how to go about this @glenn-jocher

**Comment by AlonLek** [comment]
@b3r-prog 
What os do you have?
Do you use virtual env? conda?
Are you using the regular pypi or you have some cache or proxy?

**Comment by b3r-prog** [comment]
@AlonLek its linux with a virtual env, python3 and regular pypi

**Comment by prince0310** [comment]
@b3r-prog try by updating the pip version

**Comment by b3r-prog** [comment]
Thanks @prince0310, I found the issue. its python version, has to be >=3.7

**Comment by ice6** [comment]
if you are a newbie like me encountering `pip install ultralytics[explorer]` with same error message.
just change to the command to `pip install "ultralytics[explorer]"`.
yes, "The special symbols[]" need to be enclosed in double quotation marks.

**Comment by glenn-jocher** [comment]
@ice6 great catch! Special characters like brackets can sometimes be interpreted differently by the shell, so enclosing the package name and extras in quotes is a good practice to ensure the command is executed correctly. Happy coding with YOLOv8! 😊🚀
