### ISSUE TITLE
How to make “retina_masks=True” when performing onnxruntime inference based on c++

### ISSUE THREAD

**Issue by hwang52** [ultralytics/ultralytics#5030]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, when I exported the onnx file, I set it: 
 - **model.export(format='onnx', dynamic=False, retina_masks=True, opset=12)**
but when I performed onnxruntime inference based on C++, **I found that "retina_masks=True" did not work**?
could you please answer my questions? thank you very much!

**Comment by RizwanMunawar** [comment]
Hello @hwang52, please note that the `retina_masks` functionality is not compatible with the `onnx` export mode. You can find detailed information about this in the [Ultralytics YOLOv8 Export Documentation](https://docs.ultralytics.com/tasks/detect/#export). 

Thanks.
