### ISSUE TITLE
Corrupt prediction labels

### ISSUE THREAD

**Issue by pjoyce1995** [ultralytics/ultralytics#5039]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

When running prediction of the YOLOv8x-seg model, in some cases, a class is being predicted, but no polygon follows.
e.g. the prediction .txt would look like:
cls x y x y x y ....
cls
cls x y x y x y ....

I could not find any other issues raised on this issue. Note that I have not modified any of the files in the model or inference code.

### Environment

Ultralytics YOLOv8.0.145 🚀 Python-3.8.16 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)
Setup complete ✅ (64 CPUs, 125.7 GB RAM, 83.8/464.9 GB disk)
None

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
@pjoyce1995, would you be able to provide the image file on which you conducted your testing? Based on our experiments, the segmentation module appears to be functioning correctly. 

Thanks
