### ISSUE TITLE
How to get the length and height of the detected object in YoloV8?

### ISSUE THREAD

**Issue by YugantGotmare** [ultralytics/ultralytics#5040]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to get the length and height of the detected object in YOLOv8 ?

**Comment by RizwanMunawar** [comment]
@YugantGotmare, you can retrieve the width and height information of bounding boxes by extracting the results using the provided sample code:

```python
from ultralytics import YOLO

# Load a pre-trained YOLOv8 model
model = YOLO('yolov8n.pt')

# Specify the source image
source = 'https://ultralytics.com/images/bus.jpg'

# Make predictions
results = model.predict(source, save=True, imgsz=320, conf=0.5)

# Extract bounding box dimensions
boxes = results[0].boxes.xywh.cpu()
for box in boxes:
    x, y, w, h = box
    print("Width of Box: {}, Height of Box: {}".format(w, h))
```

This code snippet demonstrates how to obtain the width and height values of the bounding boxes in the detected objects using the Ultralytics YOLOv8 model. 

If you have any further questions or need clarification, feel free to ask. Thanks!

**Comment by YugantGotmare** [comment]
Actually, I have 32 objects detected in an image I want to know the length of each of the objects in an image, and by the way I am doing Instance segmentation YOLOv8

**Comment by glenn-jocher** [comment]
@YugantGotmare to obtain the lengths (typically the width in pixels) and heights (in pixels) of each detected object in an image when performing instance segmentation with YOLOv8, you can simply extract the bounding boxes' dimensions from the results after running a prediction. In instance segmentation, each detected object is represented by a bounding box and a mask.

After performing the prediction, you receive a list of detections, where each detection is attributed to an object instance and includes both the bounding box and the segmentation mask. The bounding box is generally described by its coordinates `(x, y)` for the center, as well as its width `w` and height `h`.

To get the length and height of each detected object, you can iterate through the results and print out the width and height for every bounding box. These values correspond to the pixel dimensions of the bounding boxes encapsulating the segmented objects in the image.

Keep in mind that the actual physical length and height would require a known scale if you are translating pixel dimensions to real-world measurements, which is not directly provided by the detection and segmentation process.

If you have any further questions about utilizing the results from YOLOv8's instance segmentation capabilities or need more assistance, feel free to ask. Your inquiries are always welcome, and we're here to help to ensure you can fully leverage YOLOv8 for your projects.

**Comment by ikashifullah** [comment]
> Keep in mind that the actual physical length and height would require a known scale if you are translating pixel dimensions to real-world measurements, which is not directly provided by the detection and segmentation process.

Hi, can you provide an example snippet or a starting point for this please?

**Comment by glenn-jocher** [comment]
@ikashifullah hi there! 👋

Certainly! If you're looking to convert pixel dimensions to real-world measurements, you'll need a reference scale. For instance, if you know the actual width of an object in the image, you can calculate the pixels-per-metric unit.

Here's a simple example to get you started:

```python
# Known width of an object in your image (e.g., in meters)
KNOWN_WIDTH = 1.0  # replace with your object's real-world width

# Width of the object in pixels (from your YOLOv8 segmentation results)
pixel_width = box_width  # replace with the pixel width from your detection

# Calculate the pixels-per-metric unit
pixels_per_metric = pixel_width / KNOWN_WIDTH

# Now you can convert any pixel dimension to real-world measurements
real_world_length = pixel_length / pixels_per_metric  # for length
real_world_height = pixel_height / pixels_per_metric  # for height
```

Just replace `box_width`, `pixel_length`, and `pixel_height` with the actual values from your detection results. Hope this helps you make the conversion! If you need more guidance, feel free to ask. 😊

Happy coding!

**Comment by ikashifullah** [comment]
Hi @glenn-jocher 

thank you for the quick response. I am using the `cv2.VideoCapture(0)` and I am not sure about the actual width or height of an object in livestream, for example, if I have a laptop or TV how to find the approximate width and height, I hope you get my point of view.

**Comment by glenn-jocher** [comment]
@ikashifullah hi there!

For live streams where the actual size of objects isn't known, you could estimate dimensions by using a reference object with a known size that appears in the same plane as the objects you're interested in. For example, if you have a standard-sized item like a credit card or a sheet of paper, you can use it to estimate the pixels-per-metric ratio.

Here's a quick example using a standard A4 paper (which is 297mm in height) as a reference:

```python
# Assume you've detected an A4 paper and found its height in pixels
a4_height_in_pixels = detected_a4_height  # replace with your detected value

# Known height of an A4 paper in millimeters
a4_height_in_mm = 297

# Calculate the pixels-per-millimeter ratio
pixels_per_mm = a4_height_in_pixels / a4_height_in_mm

# Now you can estimate the size of any object in millimeters
estimated_object_height = object_height_in_pixels / pixels_per_mm
```

Just make sure the reference object and the object you're measuring are at a similar distance from the camera to keep the scale consistent.

Hope this helps you get a rough estimate of object sizes in your live stream! If you have more questions, feel free to ask. 😊

**Comment by AphroDatalyst** [comment]
how can we have a fixed size for each object detection (crop image size) ??
how can we implement it in Non-Maximum Suppression (NMS) function ?

**Comment by glenn-jocher** [comment]
Hi @ikashifullah,

You're on the right track! Using a multi-dimensional array to store the actual sizes of known objects is a smart approach. You can then match the detected object with its corresponding real-world dimensions in your array. Here's a simplified example:

```python
# Dictionary of known objects with their actual widths (in mm)
known_widths = {
    'A4': 210,
    'Laptop 13"': 325,
    'LED 32"': 708,
    # Add more as needed
}

# Function to get the actual width based on the object type
def get_actual_width(object_type, pixel_width):
    actual_width = known_widths.get(object_type, None)
    if actual_width:
        pixels_per_mm = pixel_width / actual_width
        return pixels_per_mm
    else:
        return None

# Usage
object_type = 'A4'  # replace with your detected object type
pixel_width = 500   # replace with your detected pixel width
pixels_per_mm = get_actual_width(object_type, pixel_width)
```

This way, you can dynamically adjust your pixels-per-metric calculation based on the detected object type. Hope this helps, and if you have more questions, I'm here to assist! 😊

**Comment by glenn-jocher** [comment]
@CaioZen hi there! 😊

When using a drone, where objects frequently change planes and distances, a fixed reference object might not be as effective. Instead, consider dynamic methods like depth estimation or using drone telemetry data (if available) to estimate distances. This can help adjust for the varying planes and distances of objects.

For depth estimation, you might explore stereo vision (if your drone has multiple cameras) or machine learning models trained for depth perception.

If you're using telemetry data, you can calculate the object's size based on the drone's altitude and camera angle. Here's a very simplified example:

```python
# Assuming you know the drone's altitude (in meters) and the camera's field of view
altitude = 100  # Drone's altitude in meters
fov = 90  # Camera's field of view in degrees

# Calculate the real-world height of the object based on the altitude and pixel height
real_world_height = (object_pixel_height / image_height) * (2 * altitude * math.tan(math.radians(fov / 2)))

```

This approach requires knowing your camera's specifics and might need calibration for accurate results. Hope this gives you a starting point! Let me know if you have more questions.

**Comment by CaioZen** [comment]
@glenn-jocher Hi, thank you for your help last time, however, it seems I am running into some error
Using your code, it appears the height calculated by the code changes depending on the distance from the camera and that is not how it is supposed to be. How can I make so that the height is not altered with the distance of the object detected from the camera?

**Comment by glenn-jocher** [comment]
@CaioZen hi there! 😊

It sounds like you're encountering issues with perspective distortion, where the perceived size of an object changes with distance due to the camera's perspective. To maintain a consistent object size measurement regardless of distance, you'd typically need depth information, which isn't directly available from a single camera image.

One workaround, if you're working in controlled environments, is to use known markers or objects at the same distance as your target object to calibrate your measurements. However, for a more general solution, you might consider using depth sensors or stereo cameras that can provide depth information alongside the visual feed.

For applications like drones or moving cameras, integrating telemetry data (like altitude and camera angles) can help estimate distances and adjust measurements accordingly.

Unfortunately, without additional depth data or reference points, accurately compensating for distance changes in size measurements with a single camera setup is quite challenging.

Hope this helps clarify things a bit! Let me know if you have more questions.

**Comment by g2Min** [comment]
Hi, @glenn-jocher, can I detect an object's size using a 3D camera without knowing the distance beforehand? I'm having trouble with it

**Comment by glenn-jocher** [comment]
Hi there! 😊

Yes, you can definitely detect an object's size using a 3D camera, as it inherently provides depth information. To calculate the size, you can simply subtract the smallest depth value of the object from the largest depth value within the detected area in each dimension (X, Y, Z).

Here's a simplified example using pseudo-code:

```python
# Let's assume 'depth_data' is a 3D array containing depth information
object_depths = depth_data[mask]  # 'mask' isolates the object
width = object_depths[:, :, 0].max() - object_depths[:, :, 0].min()
height = object_depths[:, :, 1].max() - object_depths[:, :, 1].min()
depth = object_depths[:, :, 2].max() - object_depths[:, :, 2].min()
```

This code calculates the dimensions based on the spread of depth values across the detected object. Make sure your camera setup and data access methods support this kind of analysis!

If you're running into specific issues, let me know! Happy to help further. 🚀

**Comment by g2Min** [comment]
First, thank you for the answer, @glenn-jocher! But I think my question might have been a bit different. I'm curious if there's a method to gauge the length of an object using just a depth camera like the Intel RealSense 435i, without having to directly compare it to the length of a known object?

**Comment by glenn-jocher** [comment]
Hi there!

Absolutely! If you're using a depth camera like the Intel RealSense 435i, you can measure the length of an object directly using the depth data alone. Essentially, you would map the pixel dimensions of the object to real-world units (like meters) based on the depth values provided by the camera.

Here's a basic idea on how you might implement it in Python using the RealSense SDK:

```python
import pyrealsense2 as rs

pipeline = rs.pipeline()
config = rs.config()
config.enable_stream(rs.stream.depth, 640, 480, rs.format.z16, 30)
pipeline.start(config)

try:
    frames = pipeline.wait_for_frames()
    depth_frame = frames.get_depth_frame()
    if not depth_frame:
        return

    # Define the region of interest (ROI) where the object is located
    x, y, w, h = 100, 100, 50, 50  # Modify as per your object's location
    depth = depth_frame.get_distance(x + w // 2, y + h // 2)

    # Calculate the real world dimension based on depth
    real_world_dimension = depth * some_calibration_factor  # Calibrate this factor based on your specific needs

finally:
    pipeline.stop()
```
This code snippet gets the depth information at the center point of a defined box. Assuming you have calibration data (like how many units in the real world a single unit of depth measurement represents), you can calculate the object's real-world dimensions.

Feel free to tweak this based on your precise requirements! 😊

**Comment by Madhanbs67** [comment]
How to get length of the shoulders usin yolov8 can anyone pls provide me complete code on this

**Comment by glenn-jocher** [comment]
Hi there! 😊

To measure the length of the shoulders using YOLOv8, you can use the pose estimation feature to detect keypoints and then calculate the distance between the shoulder keypoints. Here's a concise example:

```python
from ultralytics import YOLO
import numpy as np

# Load the YOLOv8 model for pose estimation
model = YOLO('yolov8n-pose.pt')

# Run inference on an image
results = model('path/to/image.jpg')

# Extract keypoints for shoulders (assuming keypoints 5 and 6 are shoulders)
for result in results:
    keypoints = result.keypoints.xy
    left_shoulder = keypoints[5]
    right_shoulder = keypoints[6]
    shoulder_length = np.linalg.norm(left_shoulder - right_shoulder)
    print(f'Shoulder length: {shoulder_length:.2f} pixels')
```

This will give you the shoulder length in pixels. You can convert it to real-world units if needed. Let me know if you need further assistance! 🚀

**Comment by Madhanbs67** [comment]
I got index error: index 5 is out of bounds for dimension 0 with size 1

**Comment by Madhanbs67** [comment]
Hi I got can you tell me how to convert pixels in to real world units

**Comment by glenn-jocher** [comment]
Hi there! 😊

To convert pixels to real-world units, you'll need a conversion factor that relates pixel measurements to actual distances. This factor can be derived from known dimensions in your scene or using camera calibration techniques.

Here's a basic approach:

1. **Calibration**: Place an object with known dimensions in the scene and measure its size in pixels.
2. **Calculate Conversion Factor**: Divide the known real-world size by the measured pixel size to get the conversion factor.
3. **Apply Conversion**: Multiply your pixel measurements by this factor to get real-world units.

Here's a simple example in Python:

```python
# Known real-world size (e.g., in meters)
real_world_size = 1.0  # 1 meter

# Measured size in pixels
pixel_size = 100  # Example pixel size

# Conversion factor
conversion_factor = real_world_size / pixel_size

# Convert pixel measurement to real-world units
real_world_measurement = pixel_measurement * conversion_factor
```

This will give you the real-world measurement. If you need more detailed guidance, feel free to ask! 🚀

**Comment by NamLe0412** [comment]
Hi, I'm currently using segmentation masks from YOLOv8 to calculate the size of the objects. Will imgsz which is used for model inference affect the conversion factor?

**Comment by glenn-jocher** [comment]
@NamLe0412 hi there! 😊

Great question! Yes, the `imgsz` parameter used for model inference will affect the conversion factor. When you resize your original frame (540, 720) to the model's input size (480, 640), the pixel dimensions of the objects will change accordingly.

To accurately convert the pixel measurements from the resized image back to real-world units, you need to account for the scaling factor introduced by resizing. Here's a quick example:

1. **Calculate Scaling Factors**:
   ```python
   scale_x = original_width / resized_width
   scale_y = original_height / resized_height
   ```

2. **Apply Scaling to Measurements**:
   ```python
   real_world_width = pixel_width * scale_x * conversion_factor
   real_world_height = pixel_height * scale_y * conversion_factor
   ```

In your case:
```python
original_width, original_height = 720, 540
resized_width, resized_height = 640, 480

scale_x = original_width / resized_width
scale_y = original_height / resized_height

# Assuming you have a conversion factor from pixels to real-world units
conversion_factor = 0.01  # Example factor

# Example pixel measurements from the resized image
pixel_width = 50
pixel_height = 30

real_world_width = pixel_width * scale_x * conversion_factor
real_world_height = pixel_height * scale_y * conversion_factor

print(f"Real-world width: {real_world_width} meters")
print(f"Real-world height: {real_world_height} meters")
```

This way, you can ensure that your measurements are accurate. If you have any more questions or need further assistance, feel free to ask! 🚀

**Comment by NamLe0412** [comment]
Thanks for the fast response @glenn-jocher! Your answer is informative and helpful! I have another question regarding this. I'm currently rotating the mask using cv2.warpAffine. What should I use for the rotation, the original frame shape or the mask shape (resized frame shape) to make sure that the conversion is correct?

**Comment by NamLe0412** [comment]
Please ignore the question that I posted. I tested both options and the results are the same so I guess this does not matter. However, regarding the scaling factor, if I set 'retina_masks=True', will it handle the mask scaling for me?

**Comment by glenn-jocher** [comment]
Hi there!

Great to hear that you found the previous information helpful! 😊

Regarding your question about `retina_masks=True`: Yes, setting `retina_masks=True` will indeed help handle the mask scaling for you. When `retina_masks` is enabled, the model will generate high-resolution masks that better align with the original image dimensions, reducing the need for additional scaling adjustments.

This feature ensures that the masks are more precise and maintain their quality, which can be particularly useful for tasks requiring high accuracy in object segmentation.

If you have any more questions or need further assistance, feel free to ask. Happy coding! 🚀

**Comment by germancruzram** [comment]
Hi. The topic is interesting. 

Remember that this can work if the object is taken in a flat view. It does not apply if it is a depth image where the vanishing point of the image generates differences in length and height. In this case, the measurements in the real world may be different depending on the area of ​​the image where you want to infer the length and height.

**Comment by glenn-jocher** [comment]
Hi there! 😊

You bring up an excellent point about the limitations of using 2D images for real-world measurements, especially when dealing with perspective distortions and depth variations. Indeed, measurements can vary significantly depending on the object's position within the image.

To address this, you might consider using depth sensors or stereo cameras to capture depth information, which can help correct for perspective distortions. Alternatively, if you have a known reference object in the scene, you can use it to calibrate and adjust your measurements accordingly.

For more advanced applications, integrating YOLOv8 with 3D reconstruction techniques or leveraging multi-view geometry could provide more accurate real-world measurements.

If you have any further questions or need additional guidance, feel free to ask. Happy coding! 🚀

**Comment by schemaphicGopa** [comment]
How to get the real-world length of the detected object in YOLOv8?

**Comment by akdenmikail** [comment]
> Merhaba! 😊
> 
> Omuzların uzunluğunu YOLOv8 kullanarak ölçmek için, anahtar noktaları tespit etmek ve ardından omuz anahtar noktaları arasındaki mesafeyi hesaplamak için poz tahmini özelliğini kullanabilirsiniz. İşte özlü bir örnek:
> 
> ```python
> from ultralytics import YOLO
> import numpy as np
> 
> # Load the YOLOv8 model for pose estimation
> model = YOLO('yolov8n-pose.pt')
> 
> # Run inference on an image
> results = model('path/to/image.jpg')
> 
> # Extract keypoints for shoulders (assuming keypoints 5 and 6 are shoulders)
> for result in results:
>     keypoints = result.keypoints.xy
>     left_shoulder = keypoints[5]
>     right_shoulder = keypoints[6]
>     shoulder_length = np.linalg.norm(left_shoulder - right_shoulder)
>     print(f'Shoulder length: {shoulder_length:.2f} pixels')
> ```
> 
> Bu size omuz uzunluğunu piksel cinsinden verecektir. Gerekirse bunu gerçek dünya birimlerine dönüştürebilirsiniz. Daha fazla yardıma ihtiyacınız olursa bana bildirin! 🚀

Hello, I am detecting vehicle images taken from bridges using YOLO and I want to determine the size of these detected vehicles. Can you help me with this?

**Comment by glenn-jocher** [comment]
Hello! To determine the size of detected vehicles using YOLOv8, you can use the bounding box dimensions provided by the model. If you need real-world measurements, you'll need a conversion factor from pixels to real-world units, which can be derived from known dimensions in your scene or through camera calibration. If you need further assistance, please let me know!

**Comment by akdenmikail** [comment]
> Hello! To determine the size of detected vehicles using YOLOv8, you can use the bounding box dimensions provided by the model. If you need real-world measurements, you'll need a conversion factor from pixels to real-world units, which can be derived from known dimensions in your scene or through camera calibration. If you need further assistance, please let me know!

Thank you very much for your answer. After performing camera calibration, how can I use the results of that calibration? Could you provide a brief roadmap?

**Comment by glenn-jocher** [comment]
Certainly! After performing camera calibration, you can use the calibration matrix and distortion coefficients to correct the image and accurately map pixel measurements to real-world units. Here's a brief roadmap:

1. Use the calibration matrix and distortion coefficients to undistort the image.
2. Apply the perspective transformation to map pixel coordinates to real-world coordinates.
3. Use the corrected bounding box dimensions to calculate real-world sizes.

For detailed steps, you can refer to the camera calibration documentation in OpenCV. If you need further assistance, feel free to ask!

**Comment by akdenmikail** [comment]
> Certainly! After performing camera calibration, you can use the calibration matrix and distortion coefficients to correct the image and accurately map pixel measurements to real-world units. Here's a brief roadmap:
> 
> 1. Use the calibration matrix and distortion coefficients to undistort the image.
> 2. Apply the perspective transformation to map pixel coordinates to real-world coordinates.
> 3. Use the corrected bounding box dimensions to calculate real-world sizes.
> 
> For detailed steps, you can refer to the camera calibration documentation in OpenCV. If you need further assistance, feel free to ask!

Thank you very much. After performing the calibration, I will work on implementing my application. You are an excellent team, and I am grateful for all the help you have provided us in this matter."

**Comment by glenn-jocher** [comment]
@akdenmikail thank you for your kind words! We're glad to hear that our guidance has been helpful. If you encounter any issues or have further questions while implementing your application, feel free to reach out. Best of luck with your project!

**Comment by akdenmikail** [comment]
> @akdenmikail thank you for your kind words! We're glad to hear that our guidance has been helpful. If you encounter any issues or have further questions while implementing your application, feel free to reach out. Best of luck with your project!

Hello again :))). After camera calibration, as the object moves away from the camera, the size measurement in the image gets smaller. What should I do to solve this problem?

**Comment by glenn-jocher** [comment]
To address the issue of size measurement changes as objects move away from the camera, you can use depth information or multiple camera views to account for perspective distortion. Alternatively, you can apply a perspective transformation to map pixel coordinates to real-world coordinates more accurately. If you need further assistance, please let us know!

**Comment by akdenmikail** [comment]
> 2\. Apply the perspective transformation to map pixel coordinates to real-world coordinates.

Hello, could you help me with obtaining real-world coordinates by applying perspective transformation? I didn’t quite understand it.

**Comment by glenn-jocher** [comment]
@akdenmikail certainly! To obtain real-world coordinates using perspective transformation, you'll need to use a homography matrix. This matrix can be computed using known points in both the image and the real world. Once you have the homography matrix, you can transform the pixel coordinates to real-world coordinates. For detailed steps, please refer to the OpenCV documentation on perspective transformation. If you need further assistance, feel free to ask!

**Comment by akdenmikail** [comment]
> Hello, I am detecting vehicle images taken from bridges using YOLO and I want to determine the size of these detected vehicles. Can you help me with this?

homography_matrix, mask = cv2.findHomography(src_points, dst_points, cv2.RANSAC, 5.0)
What data will I use for src points and dst points in this function? In my research, I came across these dst points as the corresponding coordinates of the points in the real world.

**Comment by glenn-jocher** [comment]
To determine the size of detected vehicles using homography, `src_points` should be the coordinates of known points in the image, and `dst_points` should be the corresponding real-world coordinates. These points can be obtained from a calibration process or known reference points in your scene. If you need further assistance, please let us know!

**Comment by biswajitschemaphic** [comment]
Hello @glenn-jocher , you are very knowledgeable, informative and helpful! 

Will you kindly help me how can I detect length of an iron billet? I have made a custom yolov8 model of the iron billets. But I want to detect the length of each detected billet as well. Example image attached.
![Screenshot 2024-12-16 174435](https://github.com/user-attachments/assets/c1a0a324-2ec5-4be0-be00-d0abd0558f47)

**Comment by glenn-jocher** [comment]
Thank you for your question! To detect the length of an iron billet, you can calculate it from the bounding box dimensions provided by your YOLOv8 model. If the length needs to be in real-world units, you’ll need to apply a scaling factor derived from camera calibration or known reference dimensions in the scene. Let me know if you need further clarification!

**Comment by biswajitschemaphic** [comment]
Okay, thanks for your replies @glenn-jocher . Can you give me an example? Suppose in real world scenario the iron billet size is 6 meter long. Then how will I calculate this?

**Comment by glenn-jocher** [comment]
@biswajitschemaphic to calculate the real-world length of a detected iron billet (e.g., 6 meters), you need to establish a pixel-to-meter scaling factor. This requires a reference object of known size in the same image or using camera calibration to map pixels to real-world units. Multiply the detected bounding box length (in pixels) by this scaling factor to estimate the real-world length. Let me know if you need further clarification!

**Comment by glenn-jocher** [comment]
Thank you for your question! To detect the length of iron billets without prior knowledge of their size, you will need to calibrate your camera to establish a pixel-to-real-world conversion factor. This can be done using a reference object or by leveraging camera calibration techniques. Once calibrated, you can use the bounding box dimensions from YOLO detections to estimate the length of the billets in real-world units. If you'd like a specific example script for this workflow, let us know!

**Comment by biswajitschemaphic** [comment]
Many thanks @glenn-jocher for your spontaneous response. 

But as I said earlier I didn't have such experience ever before so I ask you to give practical example. I mean like through a script and elaborate with some examples etc. But your current answers is too much theoretical. I am not getting any desired help from your such theoretical answers.

If you have real world practical examples kindly help me to sought out my question.

**Comment by glenn-jocher** [comment]
Thank you for your feedback. To estimate the real-world length of objects like iron billets, you can use camera calibration to obtain a pixel-to-meter scaling factor. For practical implementation, you can refer to OpenCV's camera calibration and homography functions. Additionally, I recommend exploring the [Distance Calculation guide](https://docs.ultralytics.com/guides/distance-calculation/) for practical examples on using YOLO models with spatial measurements. Let me know if you have further questions!

**Comment by srg000** [comment]
Hello, I now want to identify the size of the ore on the surface of the minecart, if I want to use the actual ore size as a reference, the number of ores in the minecart is too much, it doesn't feel very reasonable, what should I use as a reference?

**Comment by glenn-jocher** [comment]
To estimate ore sizes on a minecart, consider using a fixed reference object with known dimensions placed in the scene (e.g., a ruler or marker). This allows you to calculate a pixel-to-real-world scaling factor for accurate measurements. Let me know if you need further assistance!

**Comment by srg000** [comment]
Thank you for your reply, because this scene is taken directly above the minecart, and the picture includes the carriage, so I use the parameters of the carriage as a reference object, and then calculate the scale factor of pixels to the real world, and then I can get the specific size of the ore in the image

**Comment by srg000** [comment]
Thank you for your reply. Since this scene was shot directly above the mine cart, and the image includes the cart, I used the cart's parameters as a fixed reference object to calculate the scale factor from pixels to the real world. In the end, I was able to obtain the specific dimensions of the ore in the image.

**Comment by srg000** [comment]
Thank you for your reply. Because this scene was taken directly above the mine cart and the picture contains the carriage, I used the parameters of the carriage as a fixed reference object to calculate the scale factor from pixels to the real world. Finally, I can get the specific size of the ore in the image.

**Comment by glenn-jocher** [comment]
You're on the right track! Using the carriage's parameters as a fixed reference to calculate the pixel-to-real-world scale factor is a practical and effective approach. Let us know if you encounter any challenges or need further assistance with your implementation.

**Comment by safi397** [comment]
Hello @glenn-jocher 
I am working on the identification and quantification of waste. 
While I have successfully implemented YOLOv8 for the identification and mask extraction phases, I am encountering challenges with the quantification aspect. Specifically, I am working to estimate the volumes of three different types of objects as a percentage within a single image.
For example, I want to determine, within a single image, the volume proportions of wood, stone, and plastic. If the percentage volume of wood in the image does not exceed a specified limit, I can disregard that waste and move on to other waste where the wood volume reaches or exceeds the defined threshold.
I would be truly grateful if you could provide any guidance, resources, or suggestions to help address this issue. If there are any videos, articles, or notes that might assist me, I would be delighted to review them. 
Thank you for your time and consideration. I truly appreciate the work you do and look forward to hearing from you.

**Comment by glenn-jocher** [comment]
Thank you for your question! Estimating volume proportions requires combining YOLOv8's segmentation capabilities with additional post-processing techniques. You could calculate the pixel area covered by each object type's mask and use it as a proxy for volume percentages, assuming uniform depth. For more advanced methods, integrating depth estimation (e.g., stereo cameras or LiDAR) can provide better volume measurements. Feel free to review the [segmentation guide](https://docs.ultralytics.com/tasks/segment/) or explore OpenCV and relevant tools for further implementation. Let us know if you need more help!

**Comment by safi397** [comment]
Thank you very much Mr. @glenn-jocher

**Comment by glenn-jocher** [comment]
You're very welcome! If you have any further questions or need assistance with YOLOv8 or related tasks, feel free to ask. The YOLO community and the Ultralytics team are here to support you!

**Comment by Prathamesh9284** [comment]
I want to measure the dimensions of the object from the image without the reference object is it possible

**Comment by glenn-jocher** [comment]
Yes, measuring real-world dimensions without a reference object isn't possible, as pixel measurements alone lack scale. To convert detected bounding box pixel dimensions (width/height via `results.boxes.xywh`) to real-world units, you **must** establish a scaling factor using a known reference object in your scene or via camera calibration. For implementation details, see our [Distance Calculation guide](https://docs.ultralytics.com/guides/distance-calculation/).

**Comment by glenn-jocher** [comment]
@gaganhanglimbu The width and height values returned by `results[0].boxes.xywh.cpu()` are in pixels, not inches. To convert these pixel measurements to real-world units, you'll need to establish a pixel-to-inch conversion factor using either camera calibration or a reference object with known dimensions in your scene. YOLO itself doesn't calculate DPI as it works with pixel coordinates directly. If you need to determine DPI dynamically, you would need to integrate this conversion factor calculation into your processing pipeline based on known reference dimensions in your images.

**Comment by anjukumawat29** [comment]
@glenn-jocher I am working on a road inspection system using YOLOv8.

I trained a detection model to detect potholes and speed breakers. 
Now I want to extract size and position information for each pothole and save it into JSON.

Currently, I am using:

x, y, w, h = box.xywh[0]

This gives bounding box size, but not the exact pothole shape.

My goal:
- Get pothole size
- Get pothole position in frame
- Later attach GPS coordinates

Question:
Should I switch to YOLO segmentation to compute exact pixel area?
Or is bounding box size sufficient for practical road inspection tasks?

Any guidance on best practice would be appreciated.

**Comment by glenn-jocher** [comment]
If you need the *shape* (pixel-accurate outline/area) of a pothole, switch to a segmentation model/dataset; detection boxes (`xywh`/`xyxy`) are only a rectangle and are usually fine for coarse severity ranking or “presence/position” reporting, but not for “exact size.” If you eventually need real-world dimensions (cm/m), even segmentation still needs camera calibration / a ground-plane mapping to turn pixels into meters (see the [Distance Calculation guide](https://docs.ultralytics.com/guides/distance-calculation/)).

Here’s a minimal way to serialize per-object position/size to JSON (and include mask polygon if you run a seg model), using the [Results API](https://docs.ultralytics.com/reference/engine/results/):

```python
from ultralytics import YOLO
import json

model = YOLO("your-model.pt")  # detection or segmentation model
r = model("frame.jpg")[0]

boxes = r.boxes
masks = r.masks  # None for detection models

items = []
for i in range(len(boxes)):
    item = {
        "cls": int(boxes.cls[i].item()),
        "conf": float(boxes.conf[i].item()),
        "xyxy": boxes.xyxy[i].cpu().tolist(),   # absolute pixels
        "xywh": boxes.xywh[i].cpu().tolist(),   # absolute pixels
        "xyxyn": boxes.xyxyn[i].cpu().tolist(), # normalized 0-1
        "xywhn": boxes.xywhn[i].cpu().tolist(), # normalized 0-1
    }
    if masks is not None:
        item["polygon"] = masks.xy[i].tolist()              # list of (x,y) points in pixels
        item["mask_area_px"] = int(masks.data[i].sum().item())  # pixel area (approx volume proxy in 2D)
    items.append(item)

with open("road_findings.json", "w") as f:
    json.dump(items, f, indent=2)
```

For GPS, the common approach is to add `frame_index` and a `timestamp` to each JSON record and join it later with your GPS stream (or embed the latest GPS fix at inference time if you have it in-process). If you share an example of your input (image/video) viewpoint (dashcam vs top-down) and what “size” means for you (pixel area vs real-world area), I can suggest the simplest workflow.
