### ISSUE TITLE
PT to TFLITE?

### ISSUE THREAD

**Issue by pythonsus** [ultralytics/ultralytics#5049]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How do I convert a pt file to a tflite file? Can someone please provide me the full complete code?

**Comment by RizwanMunawar** [comment]
Hi @pythonsus!

To convert a PyTorch `pt` file to a TensorFlow Lite `tflite` model, you can achieve this using the CLI commands below:

### CLI 

```CLI
# Install the ultralytics package
pip install ultralytics

# Tflite Conversion
yolo export model=yolov8n.pt format=tflite

# Tflite Int8 Conversion
yolo export model=yolov8n.pt format=tflite int8=True
```

Thanks

**Comment by RizwanMunawar** [comment]
I am closing this issue. Please reopen if the issue persists.

Thanks
