### ISSUE TITLE
predict video from gopro process slow

### ISSUE THREAD

**Issue by lurunawjan** [ultralytics/ultralytics#5053]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, currently I'm working on object detection using yolov8 and I wanted to predict the detection by using my Gopro video. Turns out during the predict process, the detection video process very slow. Is there any solution about this?

Thank you

**Comment by RizwanMunawar** [comment]
Hey @lurunawjan! I'm curious, which Ultralytics YOLOv8 model are you currently using? Is it `yolov8m.pt`, `yolov8s.pt`, or `yolov8l.pt`?

**Comment by lurunawjan** [comment]
Hello, thank you for the reply. I'm using yolov8m.pt and the gopro model that I'm using is gopro 10 and the video is in 120fps

**Comment by RizwanMunawar** [comment]
@lurunawjan, while `yolov8m.pt` offers higher accuracy, it does come with the trade-off of longer processing times, which can result in slower speeds. If speed is a priority for your application, you might want to consider using the `yolov8n.pt` file, as it's tailored for edge devices and provides faster performance.

Thanks

**Comment by RizwanMunawar** [comment]
I am closing this issue. Please reopen if the issue persists
