### ISSUE TITLE
ModuleNotFoundError: No module named 'ultralytics.utils'

### ISSUE THREAD

**Issue by enekuie** [ultralytics/ultralytics#5054]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

for predict mode, there's no problem when I use CLI commands but when I try to write the code in a python file like `detect.py` and run it in CLI by `python3 detect.py` I get the below error. surprisingly if I run the same file through an IDE line by line I don't get this error and everything works properly

WARNING ⚠️ v8n/test/weights/best.pt appears to require 'ultralytics.utils', which is not in ultralytics requirements.
AutoInstall will run now for 'ultralytics.utils' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
requirements: Ultralytics requirement "ultralytics.utils" not found, attempting AutoUpdate...
ERROR: Could not find a version that satisfies the requirement ultralytics.utils (from versions: none)
ERROR: No matching distribution found for ultralytics.utils
requirements: ❌ Command 'pip install --no-cache "ultralytics.utils"  ' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/media/user/c0d272ed-6e21-4185-bea8-fbdfd5c1db3e/ultralytics/ultralytics/nn/tasks.py", line 511, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "/home/user/.local/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/user/.local/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/user/.local/lib/python3.10/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'ultralytics.utils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/user/c0d272ed-6e21-4185-bea8-fbdfd5c1db3e/ultralytics/detect.py", line 6, in <module>
    model = YOLO('v8n/test/weights/best.pt')  # pretrained YOLOv8n model
  File "/media/user/c0d272ed-6e21-4185-bea8-fbdfd5c1db3e/ultralytics/ultralytics/yolo/engine/model.py", line 107, in __init__
    self._load(model, task)
  File "/media/user/c0d272ed-6e21-4185-bea8-fbdfd5c1db3e/ultralytics/ultralytics/yolo/engine/model.py", line 156, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/media/user/c0d272ed-6e21-4185-bea8-fbdfd5c1db3e/ultralytics/ultralytics/nn/tasks.py", line 571, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/media/user/c0d272ed-6e21-4185-bea8-fbdfd5c1db3e/ultralytics/ultralytics/nn/tasks.py", line 526, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "/home/user/.local/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/user/.local/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/user/.local/lib/python3.10/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'ultralytics.utils'

### Environment

Ultralytics YOLOv8.0.184 🚀 Python-3.10.12 torch-2.0.1+cu117 CUDA:0 (Tesla T4, 14972MiB)
Setup complete ✅ (10 CPUs, 29.3 GB RAM, 72.2/76.7 GB disk)

OS                  Linux-6.2.0-26-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 29.33 GB
CPU                 Intel Xeon Gold 5220R 2.20GHz
CUDA                11.7

matplotlib          ✅ 3.7.1>=3.3.0
seaborn             ✅ 0.12.2>=0.11.0
requests            ✅ 2.31.0>=2.23.0
pandas              ✅ 2.0.0>=1.1.4
torchvision         ✅ 0.15.2>=0.9.0
WARNING ⚠️ invalid check_version(9.0.0, ) requested, please check values.
py-cpuinfo          ✅ 9.0.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.0.1>=1.8.0
opencv-python       ✅ 4.6.0.66>=4.6.0
pillow              ✅ 9.5.0>=7.1.2
numpy               ✅ 1.23.0>=1.22.2
pyyaml              ✅ 6.0.1>=5.3.1
WARNING ⚠️ invalid check_version(5.9.4, ) requested, please check values.
psutil              ✅ 5.9.4
tqdm                ✅ 4.65.0>=4.64.0

### Minimal Reproducible Example

here's detect.py :
```
from ultralytics import YOLO

model = YOLO('yolov8n.pt')
model = YOLO('v8n/test/weights/best.pt')  # pretrained YOLOv8n model

source = 'datasets/ic/images/test/'

results = model(source, stream=True, project="v8n", name='test', save_txt=False, save_crop=False)  # generator of Results objects

for result in results:
    boxes = result.boxes  # Boxes object for bbox outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Probs object for classification outputs
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by partheee** [comment]
[check this issue ](https://github.com/ultralytics/ultralytics/issues/3856)

**Comment by glenn-jocher** [comment]
@enekuie 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
When I run your code in PyCharm everything works correctly for me:

<img width="1150" alt="Screenshot 2023-09-24 at 17 24 04" src="https://github.com/ultralytics/ultralytics/assets/26833433/6cee2a60-01c7-419a-927e-539c27595c62">

**Comment by glenn-jocher** [comment]
Same in Colab:

<img width="1474" alt="Screenshot 2023-09-24 at 17 25 36" src="https://github.com/ultralytics/ultralytics/assets/26833433/f00cec3e-e503-4f16-b046-c44721023061">

**Comment by enekuie** [comment]
> [check this issue ](https://github.com/ultralytics/ultralytics/issues/3856)

thanks for your reply! I saw that post before and tried to update ultralytics and train a new model with it but the problem is still there

**Comment by enekuie** [comment]
> When I run your code in PyCharm everything works correctly for me:
> 
> <img alt="Screenshot 2023-09-24 at 17 24 04" width="1150" src="https://user-images.githubusercontent.com/26833433/270174412-6cee2a60-01c7-419a-927e-539c27595c62.png">

thanks you! yes as i said there no problem when i run the code in pycharm console but the problem is i need to run it through CLI and when i do it i get that error! my guess is there is something wrong during saving the weights in new updates of ultralytics. it should be `ultralytics.yolo.utils` but it's `ultralytics.utils`

**Comment by glenn-jocher** [comment]
@enekuie hi, thanks for the additional information. It seems like the issue might be related to how the environment is being set when running through the CLI. If it's running an older or different version of the Ultralytics library or, the library is not correctly imported, it could cause this type of confusion where certain modules or functions can't be found. 

You can try to specifically check the library version or the library path when you run the script from CLI by printing it out. This way you can verify if the CLI is indeed using the correct and updated version of Ultralytics. 

Also, double-check your PYTHONPATH and ensure that it's not inadvertently pointing to a different version of the library. 

When it comes to the naming of 'ultralytics.yolo.utils' versus 'ultralytics.utils', it might be a change that occurred in the newer versions. Hence, it's crucial to make sure that your script and the environment that you are running on is up to date. 

Please verify these points and let us know.

**Comment by enekuie** [comment]
yes, you're right. For the first time I installed ultralytics older version by cloning its GitHub repository and then used `pip install --u ultralytics` to update it where the file tree has been modified in recent updates so installing ultralytics right from the beginning solved this error!
thanks again!

**Comment by glenn-jocher** [comment]
@enekuie i'm glad to hear that installing Ultralytics from the beginning resolved your issue! The changes in the file tree structure of the library in recent updates can indeed cause such problems if you initially cloned an older version. This is a good reminder of the importance of keeping our libraries up-to-date and doing a fresh install when significant updates have been made. 

If you run into any more issues or have further questions about YOLOv8, feel free to ask. We're here to help!

**Comment by elfailali** [comment]
In the terminal add:
**pip install --no-cache "ultralytics.utils"**

**Comment by glenn-jocher** [comment]
Hi @elfailali, it appears you're trying to install a package named "ultralytics.utils" via pip. It's important to note that "ultralytics.utils" is not a standalone package that can be installed on its own. Instead, it's a module within the larger Ultralytics library, specifically within YOLOv8.

To make use of "ultralytics.utils", you would first need to install the entire Ultralytics library. This will give you access to all its modules, including "ultralytics.utils". Please note that you need to install the latest version of the library to get all recent updates and changes to the library file structure.

You can do this by simply running "pip install --no-cache ultralytics" in the terminal.

Let me know if you're still experiencing issues after that. Happy coding!

**Comment by animeesh** [comment]
copy ultralytics dir from the ultralytics git and you are good to go.

**Comment by glenn-jocher** [comment]
Hi there! 😊 It looks like you've found a simple solution, but just to clarify for anyone else who might see this - copying the `ultralytics` directory directly from the [Ultralytics GitHub repo](https://github.com/ultralytics/ultralytics) can indeed provide a quick fix to certain issues. However, always ensure you're using the latest version for the best experience and compatibility. A quick way to keep everything up-to-date is using pip:

```bash
pip install --upgrade ultralytics
```

This command refreshes your Ultralytics installation, ensuring all modules, including `ultralytics.utils`, are correctly aligned with the latest library updates. Happy coding! 🚀

**Comment by animeesh** [comment]
> Hi there! 😊 It looks like you've found a simple solution, but just to clarify for anyone else who might see this - copying the `ultralytics` directory directly from the [Ultralytics GitHub repo](https://github.com/ultralytics/ultralytics) can indeed provide a quick fix to certain issues. However, always ensure you're using the latest version for the best experience and compatibility. A quick way to keep everything up-to-date is using pip:
> 
> ```shell
> pip install --upgrade ultralytics
> ```
> 
> This command refreshes your Ultralytics installation, ensuring all modules, including `ultralytics.utils`, are correctly aligned with the latest library updates. Happy coding! 🚀

I tried the same it didn't work out. got a similar error as ultralytics.utils module not found

**Comment by glenn-jocher** [comment]
Hey there! 😊 I'm sorry to hear you're still facing troubles. It sounds like the install might not be updating as expected. Sometimes, especially if you've had a version manually copied over before, pip might not replace everything cleanly. 

One quick thing you might want to try is a complete reinstall. You can first uninstall Ultralytics:
```shell
pip uninstall ultralytics
```
And then reinstall it:
```shell
pip install ultralytics
```

Making sure you're in the correct environment when you do this can also help avoid any mix-ups. If you're still stuck after giving that a shot, it might be helpful to check if `ultralytics.utils` is being specifically referenced in your code or if there are any dependencies that need updating. Let us know how it goes! 🚀
