### ISSUE TITLE
Validating on datasets without labels

### ISSUE THREAD

**Issue by JonasVerbickas** [ultralytics/ultralytics#5055]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I have trained an object detection model and now I would like to validate it on unlabelled footage, however 
calling `yolo detect val model=./new_model/best.pt data=./dataset.yaml save_json=True`
raises `ValueError: All labels empty in /home/.../labels.cache, can not start training without labels`.

I presume to go around this error I would have to implement a validation script myself. It would make sense for YOLO to support validating on labeless dataset for false positive benchmarking.

### Environment

Ultralytics YOLOv8.0.124 🚀 Python-3.8.16 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24260MiB)
Setup complete ✅ (20 CPUs, 31.2 GB RAM, 905.1/913.3 GB disk)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@JonasVerbickas I think you might be misunderstanding validation. At the ideal conf-thresh of 0.0 there will be about 10,000 FPs per image at imgsz 640, the distribution of these across the confidence space is what is used to create mAP, but this requires labels.

Validating unlabelled data is not a meaningful concept in ML.
