### ISSUE TITLE
DVC logger is broken

### ISSUE THREAD

**Issue by shcheklein** [ultralytics/ultralytics#5058]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Integrations

### Bug

The `DCVLive` integration got broken because of this change: https://github.com/ultralytics/ultralytics/pull/4894/files#r1333816643

I can change it back, but would love to have more context first.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@shcheklein hi thanks for the bug report!

Apologies for the breaking change, I didn't know the package is lacking the __version__ attribute. I'd highly recommend adding it in as it seems to be standard practice. I think all of our other dependencies have it.

The change is because I'm trying to eliminate package_resources from the repo as we keep getting deprecation notices for it. We've replaced it mainly with `importlib` and the breaking change PR applies this change in a number of places including the DVClive logger.

**Comment by shcheklein** [comment]
@glenn-jocher no worries. 

So, there are two things happening in that code:

```python
from importlib.metadata import version
import pkg_resources as pkg
ver = version('dvclive')
if pkg.parse_version(ver) < pkg.parse_version('2.11.0'):
```

`pkg_resources` was used to compare versions (not to extract it). The newer `importlib.metadata` is being used for this. Which is:

````
New in version 3.8.
Changed in version 3.10: importlib.metadata is no longer provisional.
```

I agree on removing the `pkg_resources`, replacing it with the internal helper hopefully, but I think it's fine to keep the `from importlib.metadata import version` wdyt? I think `__version__` is getting quickly [outdated](https://stackoverflow.com/questions/72167802/adding-version-attribute-to-python-module/72168209#72168209).

**Comment by glenn-jocher** [comment]
@shcheklein oh that's super interesting, thanks for the link. I'm using the version attribute as the single source of truth and reading that in setup.py currently.

I've learned that unfortunately we need to trail the ideal by a couple years to allow the community to adapt, i.e. there's a few cool Python 3.8 features I'd like to use now that 3.7 is deprecated but about 10% of our users are still on 3.7, so there's a long tail of late adopters we need to keep unofficially catering to. The version attribute removal appears to be the same, would be great to simplify it but I feel we'll be with it for quite a while to come.

Speaking of updating, I need to migrate from setup.py to the newer toml, but haven't been able to yet either :(

In this case I think just using the version() function is a good fix.

**Comment by glenn-jocher** [comment]
@shcheklein fix attempt in #5068. Can you try this and see if it works?

**Comment by shcheklein** [comment]
@glenn-jocher yep, thanks! I see that `version()` is already used in the utils and like the direction of the fix - makes it simple and nice. 

I can try to run today and confirm that it works ...

**Comment by glenn-jocher** [comment]
@shcheklein great news 😃! Your original issue may now be resolved ✅ in PR #5068 and published in `ultralytics 8.0.168`. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by shcheklein** [comment]
It should be fixed now, closing the issue.

**Comment by glenn-jocher** [comment]
@shcheklein thanks for your patience. Based on your recent discussions, we've implemented necessary changes and the problem you reported should now be resolved. As such, we'll be closing this issue for now. 

If you encounter any further questions or issues related to this, feel free to reopen the issue or create a new one. We really appreciate your valuable feedback and contributions to the YOLOv8 community!
