### ISSUE TITLE
Best way to detect buidings in a very large area

### ISSUE THREAD

**Issue by twoyoung91** [ultralytics/ultralytics#5060]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello

I am currently using YOLOv8 for the identification of building footprints within aerial maps. The model has been trained using a specialized dataset and has good accuracy

However, I am encountering a challenge when processing large-scale maps of entire cities (dimensions: 50 miles x 50 miles, resolution: 30cm per pixel). The composite map TIFF file for each city reaches sizes up to 35GB, making it unfeasible to run predictions on the entire map in a single instance.

My current methodology involves dividing the city map into over 2000 smaller maps, each being 3200x3200 pixels. I perform predictions on each individual map and subsequently merge the detected bounding boxes into a single file. An issue arises with buildings located on the edges of smaller maps, as they are splitted into two sections on two distinct maps. Consequently, a single building is identified as two contiguous but separate objects in the final output. To rectify this, I integrate a 1600 pixels padding during image segmentation and used a non-maximum suppression algorithm to omit duplicate bounding boxes in the consolidated output file.

I am reaching out to inquire if there exists a more optimized, elegant approach or any innovative solutions to address these challenges.

Thanks a lot for your work and help! Yolo indeed saved my research life！

**Comment by glenn-jocher** [comment]
@twoyoung91 hello!

I'm delighted to hear about your success in applying YOLOv8 to the important task of identifying building footprints in aerial maps. Handling large-scale maps for such high-resolution images indeed poses significant challenges, particularly when considering computational resources and the precision needed to avoid the fragmentation of detected objects.

Your current strategy of segmenting large images into manageable tiles and then merging the results is a common and efficient approach. Including overlap between tiles mitigates the risk of cutting objects at the borders, which you've already implemented.

To further improve upon your methodology:

1. **Overlap Size Tuning**: Consider tuning the size of the overlap based on the average size of the buildings you're detecting. If the structures are generally large, a more significant overlap may be necessary to reduce the split-object occurrences.

2. **Post-Processing Techniques**: Your use of non-maximum suppression (NMS) is correct; you might also investigate advanced variations of NMS that consider context or are adaptive to the specific characteristics of your data.

3. **Batch Predictions for Efficiency**: Analyze whether small images can be batched together to make more efficient use of your GPU resources during inference. This can help reduce total processing time.

4. **Edge-aware Detection**: Some researchers develop 'edge-aware' methods where the model predictions on the periphery of the tile are handled differently knowing that they may only represent part of an object.

5. **Custom Collation Function**: Create a function to collate predictions from neighboring tiles with overlapping regions. This can be based on spatial coordinates of detections to couple pieces of a larger object detected in adjacent tiles.

6. **Error Detection Module**: Implement a module to cross-reference detections specifically at tile edges and correct any obvious split detections.

If you haven't checked already, the Ultralytics Docs at https://docs.ultralytics.com contain more guidance and tips that may help refine your approach and enhance performance.

I'm thrilled that YOLO has been instrumental in your research, and I appreciate your kind words! Remember that each dataset and use case is unique, so experimentation is key to finding the most suitable solution. Keep up the excellent work, and feel free to reach out if you have more questions or need further assistance.
