### ISSUE TITLE
How can i save video 

### ISSUE THREAD

**Issue by nae-room** [ultralytics/ultralytics#5062]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello

I use yolov8 object tracking for person tracking.
I use "save_crop" to save the results. But, I want to save the results for video. Can I save the video of the result by save_crop?
Or can I save separately by id?
And when I put the YouTube link in the source, the resulting video is too fast. The original video is 2:30, but the results video is 0:01. Can I control the length of the video? Or why is the resulting video getting faster?

Thank you :)

My code :
import cv2
import ultralytics
from ultralytics import YOLO

model = YOLO('yolov8m.pt')
results = model.track(source='https://youtu.be/RaZl64yR7Oc?si=otywE18_wizKkUNT', save=True, show=True, project='./result' , tracker="bytetrack.yaml", classes=0, save_txt=True, save_crop=True)

**Comment by RizwanMunawar** [comment]
@nae-room, if you want to save the video during object tracking, you can use the `save=True` argument. Here's a breakdown of related options:

- `save_crop` for cropping detected objects.
- `save_txt` to store detection labels.
- `save` to save the output video.

Example code snippet:

```python
import cv2
import ultralytics
from ultralytics import YOLO

model = YOLO('yolov8m.pt')
results = model.track(source='https://youtu.be/RaZl64yR7Oc?si=otywE18_wizKkUNT', \
save=True, show=True, project='./result', tracker="bytetrack.yaml", classes=0)
```

When using a YouTube link as the source, YOLOv8 may process frames faster, leading to a shorter video duration than the original.

Thanks

**Comment by Dmitrii-Smirnov** [comment]
Hi Guys,
Guys, I have a video with multiple objects(people) on the video. 
I need to calculate distance between each detected person on the each frame and to save results to csv file.
Can you help me with that task?
It will be really cool if you will share documentation=)
As I understood relevant method for my task is DistanceCalculation(names=names[0], view_img=True).calculate_distance(obj1, obj2), am I correct?

**Comment by glenn-jocher** [comment]
@Dmitrii-Smirnov hi,

Yes, you can use the `DistanceCalculation` class for your task. To save results to a CSV file, you can modify the example provided in the [distance calculation documentation](https://docs.ultralytics.com/guides/distance-calculation/). This will guide you through calculating distances between detected persons and saving the results. If you need further assistance, please refer to the documentation for detailed instructions.
