### ISSUE TITLE
(Question) How to start training without ClearML logging?

### ISSUE THREAD

**Issue by Robotatron** [ultralytics/ultralytics#507]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to start training without ClearML logging?
I remember in YOLO5 there was a flag to disable all logs and an easy way to see all arguments by inspecting train.py, sadly in YOLO8 I am not sure where the code for all the arguments for training are?

**Comment by glenn-jocher** [comment]
@Robotatron Maybe just `pip uninstall clearml` when you don't need it.

@thepycoder is there a simple clearml command to temporarily disable logging?

**Comment by AyushExel** [comment]
@glenn-jocher we should have a command `cloud_logging=False` which should be true by default

**Comment by Robotatron** [comment]
> cloud_logging=False

Did not work: `cloud_logging is not a valid key. Similar keys: []`

**Comment by Robotatron** [comment]
> @Robotatron Maybe just `pip uninstall clearml` when you don't need it.
> 
> @thepycoder is there a simple clearml command to temporarily disable logging?

I think YOLO5 had a command line argument to disable cloud logging, would be awesome to have it with YOLO8 as well.
Installing and re-installing a package several times a day would take more time and probably break some things eventually that it is faster for me to just manually delete the clearML task every time the run fails (due to bugs or user error or quick tests)

**Comment by AyushExel** [comment]
> > cloud_logging=False
> 
> Did not work: `cloud_logging is not a valid key. Similar keys: []`

Ohh I meant we should have it in the future. It's currently not supported :)

**Comment by rusmux** [comment]
@Robotatron Could you please tell what option that was in YOLOv5? I try to disable ClearML logging (without uninstalling it) in YOLOv5 and can't find it
