### ISSUE TITLE
Disable logger ouput during inference

### ISSUE THREAD

**Issue by EvdoTheo** [ultralytics/ultralytics#5079]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I've got a question about how I can disable the Logger output during inferencing 
_0: 480x640 (no detections), 32.0ms
Speed: 6.7ms preprocess, 32.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)_

I only need to extract the bbox of the detected object and nothing else. What modification should I do? Thank you!

**Comment by mrtera** [comment]
Look here #872
you can set verbose=False
model(img, save=True, verbose=False)

**Comment by glenn-jocher** [comment]
@EvdoTheo hello, 

To stop the Logger from outputting during the inferencing stage, you can indeed set `verbose=False` in your model call, as you mentioned. When the `verbose` parameter is set to False, the model's inference behavior changes, and it will not output the logging information you're seeing. 

So, your model call would look something like this: `model(image, save=True, verbose=False)`. 

This change should allow you to run your inference while only extracting the bounding box of the detected object, without the additional Logger output.

I hope this answers your question. Please reach out if you have further queries.

Best regards,
Glenn

**Comment by EvdoTheo** [comment]
Great, thank you!

**Comment by glenn-jocher** [comment]
@EvdoTheo you're welcome! I'm glad I could help. If you have any other questions or concerns regarding the use of YOLOv8, please feel free to reach out. We're always here to assist. Happy coding!
