### ISSUE TITLE
[Bug or FR] Unable to use args.yaml from a complete run to start new training.

### ISSUE THREAD

**Issue by Robotatron** [ultralytics/ultralytics#508]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I'd like to use an identical set-up I did in a previous run. YOLO being awesome as it is automatically saves all your hyperpara in the run folder under the file `args.yaml`

However, if I now want to reproduce my last run and use  `args.yaml` as an input config for training with `yolo cfg=args.yaml name=asd01` the training fails:

```
Ultralytics: Overriding default config with args.yaml
save_dir is not a valid key. Similar keys: ['save_crop', 'save', 'save_hybrid']
```

1) It is quite clear why it fails (not a valid key in args.yaml) but I am not sure if this is a bug or a potential feature request, to be able to provide saved yaml as an input for a new training run.

2) Otherwise (if not a bug) what is the easiest way to reproduce a run without manually removing the keys from args.yaml ? It would be nice to be able to feed this config when starting a new training run.

3) Removing "save_dir" from arg.yaml let's me train a new run. The fix for the code base seems quite easy -> ignore save_dir key if config is used for training

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Good feature request! I'll fix this
