### ISSUE TITLE
Missing assignment statement in parse_key_value_pair function

### ISSUE THREAD

**Issue by javierganan99** [ultralytics/ultralytics#5080]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

In the function def parse_key_value_pair the **re.sub** result is not assigned back to the **pair** variable.

def parse_key_value_pair(pair):
    """Parse one 'key=value' pair and return key and value."""
    re.sub(r" *= *", "=", pair)  # remove spaces around equals sign
    k, v = pair.split("=", 1)  # split on first '=' sign
    assert v, f"missing '{k}' value"
    return k, smart_value(v)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by javierganan99** [comment]
@glenn-jocher Thank you for your quick response. The PR is already merged.

**Comment by glenn-jocher** [comment]
@javierganan99, you're most welcome! It's our pleasure to assist in your contributions to the YOLOv8 repo. Thank you for submitting the PR in such a timely manner. Your diligent work helps enhance the performance and functionality for all users. We greatly appreciate your support for YOLOv8's development! If you have any additional inquiries or need further assistance, please don't hesitate to ask.
