### ISSUE TITLE
Indexerror: list out of range while training in YOLOv8

### ISSUE THREAD

**Issue by saugatleo** [ultralytics/ultralytics#5085]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

![image](https://github.com/ultralytics/ultralytics/assets/146007866/cc45144c-829c-4ff4-8aaa-0fabbc5c5a87)

### Environment

YOLO : YOLO v8 Pytorch (PIP package : !pip install ultralytics)
OS : Windows 10
Python : 3.9.18

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@saugatleo hello, thank you for your interest in YOLOv8 and for reporting this issue.

The "list index out of range" error typically indicates that your code is trying to access an item at an index that does not exist in the list. 

In the context of YOLOv8, this error might occur during the training process for a variety of reasons. A common cause is a mismatch between the number of specified classes in your .yaml config file and your dataset. For example, if you are working with a custom dataset, ensure that the number of classes specified in your config file accurately reflects the true number of different classes in your dataset annotations.

Alternatively, this error can also appear if there's an issue with the dataset file paths. Please ensure all your file paths in your dataset are correct and the corresponding images/annotations exist. 

As another potential point, make sure that your images and labels are correctly formatted and matched. Any discrepancies there could also lead to the occurrence of such an error. 

Without a concrete reproducible example, it's a bit difficult to provide a precise solution, but I hope that these suggestions can help you to sort out the problem.

Please let us know if you have any further questions or if the problem persists after checking these points!

**Comment by RizwanMunawar** [comment]
@saugatleo, these errors commonly occur when the number of classes specified in your `data.yaml` file exceeds the actual classes you've annotated. I recommend double-checking your `data.yaml` file. If the issues persist, please share your configuration file.

Thanks

**Comment by senarvi** [comment]
I get the same error. This is the indicated line: [https://github.com/ultralytics/ultralytics/blob/2624fc04fb4dc76708d8eafdcfacf0781510757d/ultralytics/models/yolo/detect/val.py#L146](https://github.com/ultralytics/ultralytics/blob/2624fc04fb4dc76708d8eafdcfacf0781510757d/ultralytics/models/yolo/detect/val.py#L146)

The only indexing here is `stats[-1]`, meaning that `DetectionValidator.stats` must be empty. The previous line is only executed if `stats` is not empty, but this line is executed in any case, which sounds like a bug.

Another question is why `DetectionValidator.stats` is empty. I have no idea. This happens after running validation on all the validation images.

**Comment by senarvi** [comment]
Thanks @glenn-jocher . In my case it seemed to be a problem when converting the labels to the Ultralytics format.

**Comment by rabion1234** [comment]
i have only 2 classes in my image but having 60 each in one image. so what should be correct format for labeling file because i am getting this error. i.e. i labeled my images by labellmg and downloaded from yolo format. looking for your help @glenn-jocher

**Comment by glenn-jocher** [comment]
@rabion1234 the correct format for a YOLOv8 labeling file for each image should have one row per object, with each row containing five values: class index (starting from 0), x_center, y_center, width, and height. All values should be normalized between 0 and 1 relative to the image size. For two classes, your class indices will be 0 and 1. Ensure that your label files match this format and that they correspond to the correct image files. If you continue to experience issues, please verify the integrity of your label files and ensure they are properly associated with your images.

**Comment by rabion1234** [comment]
i checked it. It still giving me error. Althogh it is plotting an image according to my annotation.

**Comment by rabion1234** [comment]
This is my error message: 
in plot(self, max_samples_per_plot, n_plots, plot_transformed_data)
    527             n_subplot = int(np.ceil(max_samples_per_plot**0.5))
    528             for img_i in range(min(max_samples_per_plot, len(self))):
--> 529                 index = img_i + plot_i * 16
    530             if index < len(self):
    531              print(f"Processing index {index}...")

/usr/local/lib/python3.10/dist-packages/super_gradients/training/datasets/detection_datasets/detection_dataset.py in __getitem__(self, index)
    425         The output of this function will be collated to form batches.
    426 
--> 427         :param index:   Index refers to the index of the sample in the dataset, AFTER filtering (if relevant). 0<=index<=len(dataset)-1
    428         :return:        Sample, i.e. a dictionary including at least "image" and "target"
    429         """

/usr/local/lib/python3.10/dist-packages/super_gradients/training/datasets/detection_datasets/detection_dataset.py in get_sample(self, index, ignore_empty_annotations)
    440         """Get raw sample, before any transform (beside subclassing).
    441         :param index:                       Index refers to the index of the sample in the dataset, AFTER filtering (if relevant). 0<=index<=len(dataset)-1
--> 442         :param ignore_empty_annotations:    If True, empty annotations will be ignored
    443         :return:                            Sample, i.e. a dictionary including at least "image" and "target"
    444         """

/usr/local/lib/python3.10/dist-packages/super_gradients/training/datasets/detection_datasets/detection_dataset.py in _get_sample_annotations(self, index, ignore_empty_annotations)
    237         :return:                            Dict representing the annotation of a specific image
    238         """
--> 239         print("Index:", index)
    240         print("Ignore Empty Annotations:", ignore_empty_annotations)
    241         print("_non_empty_sample_ids:", self._non_empty_sample_ids)

IndexError: list index out of range

**Comment by glenn-jocher** [comment]
@rabion1234 it appears that the error you're encountering is an `IndexError`, which suggests that the code is trying to access an index in a list that doesn't exist. This could happen if the dataset size is smaller than expected or if there's an issue with the dataset indexing logic.

Please verify the integrity of your dataset and ensure that the number of samples is consistent with the indices being accessed in the code. Also, check that any filtering applied to the dataset does not result in an empty list or fewer items than expected. If the problem persists, consider reviewing the logic that calculates the indices to ensure it aligns with the dataset's actual size.

**Comment by rabion1234** [comment]
Yes, I found it. It was indexing issue in my code. Thank you for your support.

**Comment by glenn-jocher** [comment]
@rabion1234 You're welcome! I'm glad to hear you resolved the indexing issue. If you need further assistance in the future, feel free to reach out. Happy coding! 🚀
