### ISSUE TITLE
How to filter only objects I want in prediction?

### ISSUE THREAD

**Issue by LuisTabile** [ultralytics/ultralytics#5086]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would like to know if I can only show objects that I want in the prediction, for example, if I put a video of a traffic light, it ignores people and only shows cars

Command i'm using:
`yolo task=detect mode=predict model=yolov8n-seg.pt source='input/car.mp4' show=True`

**Comment by RizwanMunawar** [comment]
@LuisTabile, If your goal is to identify particular objects, you can achieve this by using the class arguments. For example:

```python
# To exclusively detect a person
yolo task=detect mode=predict model=yolov8n-seg.pt source='input/car.mp4' show=True classes=0

# If your intention is to detect only cars
yolo task=detect mode=predict model=yolov8n-seg.pt source='input/car.mp4' show=True classes=2
```

Thanks.

**Comment by LuisTabile** [comment]
> @LuisTabile, If your goal is to identify particular objects, you can achieve this by using the class arguments. For example:
> 
> ```python
> # To exclusively detect a person
> yolo task=detect mode=predict model=yolov8n-seg.pt source='input/car.mp4' show=True classes=0
> 
> # If your intention is to detect only cars
> yolo task=detect mode=predict model=yolov8n-seg.pt source='input/car.mp4' show=True classes=2
> ```
> 
> Thanks.

Tysm, one more question, where i can see the classes numbers?
