### ISSUE TITLE
Windows v8 dataloader lag between epochs

### ISSUE THREAD

**Issue by CDEV500** [ultralytics/ultralytics#509]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I've noticed that when finishing an epoch, and starting a new epoch, it can take 10-20 seconds before the next epoch starts training. Is this expected?

**Comment by kosmicznemuchomory123pl** [comment]
I think you use too many validate images.

**Comment by CloneableDev** [comment]
My dataset I'm testing with is actually very small. 158 train, 8 val, 6 test

**Comment by kosmicznemuchomory123pl** [comment]
Can you show your terminal while training?
In my training, I have < 1 sec:

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      2.21G        nan        nan        nan         18        384: 100%|██████████| 418/418 [01:14<00:00,  5.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  2.11it/s]
                   all          7        250     0.0536      0.415       0.12     0.0574

**Comment by lanyeeee** [comment]
same problem here  
in my case, in each epoch, firt load something into memory before the train, then memory is freed at the end of the train, load something into memory before the validate, then memory is freed again at the end of the validate. Then go on, the next epoch and load something into memory before train...  
**load something into memory** is the reason for slow, it also causes the GPU underutilized

**Comment by lanyeeee** [comment]
```python
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO('weights/yolov8s.pt')
    model.train(data='data/mycoco.yaml', epochs=700, imgsz=640, project='runs')
```
This is the code I train the model

**Comment by CloneableDev** [comment]
So right now, for me, this is isolated to windows.

Testing on Linux Mint, the time from stopping an epoch, and starting a new epoch is nearly instant. 

On both I am using GPU

**Comment by lanyeeee** [comment]
> So right now, for me, this is isolated to windows.
> 
> Testing on Linux Mint, the time from stopping an epoch, and starting a new epoch is nearly instant.
> 
> On both I am using GPU

Yeah you are right, I just tested in linux mint and **it works well**. Maybe I should train in linux and then take the trained model to windows to use :)

**Comment by kosmicznemuchomory123pl** [comment]
> @kosmicznemuchomory123pl why is your losses nan?

I have problem with them. Maybe something with CUDA version or pytorch with my graphic card or system.
https://github.com/ultralytics/ultralytics/issues/280#issuecomment-1398994716

**Comment by BraunGe** [comment]
I think that may caused by your CPU. It takes time to load images for next epoch. What is your workers number? I encountered the same issue before, when I changed to a more powerful CPU and with cache in disk, this issue fixed.

**Comment by lanyeeee** [comment]
> @BraunGe  I think that may caused by your CPU. It takes time to load images for next epoch. What is your workers number? I encountered the same issue before, when I changed to a more powerful CPU and with cache in disk, this issue fixed.

My CPU is `i5-12600KF`, my workers number is **8**, I had tried to use **cache in disk** like this  
```python
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO('weights/yolov8s.pt')
    model.train(data='data/mycoco.yaml', epochs=700, imgsz=640, project='runs', cache=True)
```
After using `cache=True`, my `RAM` and `SSD` almost 100% usage when loading images, but **the loading time between each epoch** is rather **longer**. In other words, maybe I should not use `cache=True`  

But when I moved from `Windows` to `Linux`, I run this code in `Linux`
```python
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO('weights/yolov8s.pt')
    model.train(data='data/mycoco.yaml', epochs=700, imgsz=640, project='runs')
```
it works well in `Linux`, That **long loading time** is gone  

I have no idea why this happen

**Comment by BraunGe** [comment]
> 

While your GPU is good enough. My experience is based on YOLOv5. "After using cache=True, my RAM and SSD almost 100% usage when loading images, but the loading time between each epoch is rather longer", longer time is weird. Seems that YOLOv8 may have some bugs.

**Comment by CloneableDev** [comment]
This is definitely a bug in windows. After a fresh install of windows, I'm encountering the same issue. The data takes a long time to load before each epoch. In Linux, the loading time between epochs is nearly instant.

**Comment by sipie800** [comment]
same here, stuck for almost 30s between epochs......

**Comment by darouwan** [comment]
@sipie800  I have found the issue cause. It is caused by this line:
https://github.com/ultralytics/ultralytics/blob/a5410ed79e6ff30ee56d359c43f3c49d6d840ced/ultralytics/yolo/engine/validator.py#L135

> 

If I test the code block in the loop, it's 0.5 s, however it takes 35s of overall loop and there is one loop in this part.

**Comment by sipie800** [comment]
> @sipie800 I have found the issue cause. It is caused by this line:
> 
> https://github.com/ultralytics/ultralytics/blob/a5410ed79e6ff30ee56d359c43f3c49d6d840ced/ultralytics/yolo/engine/validator.py#L135
> 
> > 
> 
> The code block in this loop takes 0.35s and the whole loop takes 35s. I test this loop in console and it's still very slow. I have tried several versions of tqdm and every one have the same issue. May is caused by the dataloader used to construct the tqdm

Perhaps every tqdm bar wrapping a dataloader will slow down, not only in validator.

**Comment by sipie800** [comment]
> How can apply a temporary fix for this, is using worker_num=0 enough?

Yes. But a fix is essential to get it to full speed.

**Comment by ddjukic** [comment]
In the absence of a fix: https://fizzylogic.nl/2022/11/02/how-to-set-up-cuda-and-pytorch-in-ubuntu-22-04-on-wsl2

Getting pytorch to run with GPU support on WSL is a breeze, and there are no slowdowns between epochs this way with using dataloader workers during training :)

**Comment by darouwan** [comment]
> > @sipie800 I have found the issue cause. It is caused by this line:
> > https://github.com/ultralytics/ultralytics/blob/a5410ed79e6ff30ee56d359c43f3c49d6d840ced/ultralytics/yolo/engine/validator.py#L135
> > 
> > > 
> > 
> > 
> > The code block in this loop takes 0.35s and the whole loop takes 35s. I test this loop in console and it's still very slow. I have tried several versions of tqdm and every one have the same issue. May is caused by the dataloader used to construct the tqdm
> 
> Perhaps every tqdm bar wrapping a dataloader will slow down, not only in validator.

Exactly. Now I use wsl ubuntu instead of Windows local python to run my code with CUDA, and it works well.

**Comment by megachomba** [comment]
im having the same exact issue, slow times between epoch and validation ( epoch takes 53s with batch size 512 for 30k images, validation takes 1:30 mins + a solid 30-40s before it starts validation... a lot of of time wasted
> In the absence of a fix: https://fizzylogic.nl/2022/11/02/how-to-set-up-cuda-and-pytorch-in-ubuntu-22-04-on-wsl2
> 
> Getting pytorch to run with GPU support on WSL is a breeze, and there are no slowdowns between epochs this way with using dataloader workers during training :)

i've attempted this, but for some reason it takes ages to to scan the images for train and valid, and once training is about to start i get a segmentation fault........

**Comment by Vincentzyx** [comment]
> 

I have the exact same issue, long between epoch time on windows and get segmentation fault using wsl2. Turn down batch size to really low can help avoiding the segmentation fault but low batch size can't utilize the GPU at all.

**Comment by Vincentzyx** [comment]
> 

Yeah, but that's also slow though

**Comment by YFforever2022** [comment]
Guys, I have this problem too, how do I solve it now, virtual memory is loaded before each iteration, memory is released after completion of iteration, memory is loaded again, mAP is started to be calculated, and memory is loaded after completion, the time spent on loading memory is too high Many, resulting in very long iterations

**Comment by YFforever2022** [comment]
Now I use the command to temporarily solve this problem, yolo detect train data=coco128.yaml model=yolov8n.pt epochs=100 workers=0 name=test batch=20 cache=FALSE

**Comment by ZJDATY** [comment]
I have encountered the same problem. Under Windows 10, it may take 30 seconds or more before two times.

**Comment by ZJDATY** [comment]
> > 
> 
> I have the exact same issue, long between epoch time on windows and get segmentation fault using wsl2. Turn down batch size to really low can help avoiding the segmentation fault but low batch size can't utilize the GPU at all.

With wsl2, can it use gpu for training?

**Comment by darouwan** [comment]
setting workers=0 can solve it

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by voxupe** [comment]
Same issue.
Set workers=0 can resolve freezing between epoch.
But it can not use full gpu performance.

With yolov5 train works good.
Seems this issue only occurs in yolov8.

**Comment by glenn-jocher** [comment]
@voxupe are you using the latest version of ultralytics? What's your environment and commands to reproduce?

**Comment by voxupe** [comment]
> @voxupe are you using the latest version of ultralytics? What's your environment and commands to reproduce?

@glenn-jocher 
Yes I'm using latest version of this.

Environment:
Win11 cuda11.7 torch1.13.1 python3.9

Here is my commands.
```
from ultralytics import YOLO
def main():
    model = YOLO(r'C:\XXXX\ultralytics\models\v8\yolov8n.yaml')  
    model.train(task="detect", mode="train", data=r'C:\XXXX\ultralytics\datasets\coco128.yaml', epochs=4000, imgsz=320, cache=True, project="C:\XXXX\TrainingModel", val=False, batch=-1)

if __name__ == "__main__":
    main()
```

**Comment by glenn-jocher** [comment]
@voxupe ok got it. This seems like a Windows issue, but I'm not able to reproduce this since we don't have any Windows machines. I develop on macOS and then train on Linux. We have a legacy YOLOv5 dataloader in ultralytics that can be used for detect training (but not anything else). Does the slowdown occur there also?

```bash
yolo train   # v8 loader (default)
yolo train v5loader
```

@AyushExel @Laughing-q do you guys have access to a Windows machine? It looks like Windows is suffering from slowdowns between epochs. I can't remember if we modified the infinite dataloader in v8, I'll take a look.

**Comment by BraunGe** [comment]
> @voxupe ok got it. This seems like a Windows issue, but I'm not able to reproduce this since we don't have any Windows machines. I develop on macOS and then train on Linux. We have a legacy YOLOv5 dataloader in `ultralytics` that can be used for **detect** training (but not other tasks like segment/classify). Does the slowdown occur there also?
> 
> ```shell
> yolo train   # v8 loader (default)
> yolo train v5loader
> ```
> 
> @AyushExel @Laughing-q do you guys have access to a Windows machine? It looks like Windows is suffering from slowdowns between epochs. I can't remember if we modified the infinite dataloader in v8, I'll take a look.

I tried using v5loader, there's no improvement. Same in the Windows

**Comment by voxupe** [comment]
@glenn-jocher 
Tried v5loader too. Still no improvement.

**Comment by glenn-jocher** [comment]
@voxupe oh ok. Then there should be no difference with v5 performance, as this is the same dataloader in YOLOv5.

**Comment by nikkoxgonzales** [comment]
Any update on this, still experiencing this issue on 8.0.58.

**Comment by awetzel-lionpower** [comment]
Experiencing the same issue here on Windows. Still need a fix.

**Comment by andrewwetzel23** [comment]
I am not receiving any error messages, but I am attempting to train a yolov8n model on a Windows machine. 

I have trained the same data with the same setting on yolov5 and the training takes around 5 seconds per epoch and validation takes around 6 seconds. Running the yolov8 training with the same settings takes around 11 seconds per epoch with around 75 seconds for validation and then a noticeable gap before training the next epoch.

I am training with cache='ram' and with the device as an RTX3090.

**Comment by glenn-jocher** [comment]
@andrewwetzel23 the YOLOv8 model has more layers than YOLOv5, which may contribute to longer training and validation times. Additionally, the use of 'cache='ram'' can increase the memory usage of the training process, which may impact performance. 

One suggestion to improve the training time is to try reducing the batch size. With a larger model, you may need to reduce the batch size in order to fit the model in memory. You can also try adjusting the number of workers used by the DataLoader, as this may impact the speed at which data is loaded during training.

Lastly, it could be helpful to check the system usage during training and validation, to ensure that there are no bottlenecks such as limited disk or CPU speed that are causing slower performance.

**Comment by awetzel-lionpower** [comment]
I attempted the training as well with the batch size cut in half but saw about the same timings. I was also under the impression that reducing the number of workers will reduce GPU utilization. Is the point of reducing the number of workers that the time it saves during loading the model memory will be less than the extra time during training?

I'll check the system performance during training and report back.

**Comment by glenn-jocher** [comment]
@awetzel-lionpower reducing the number of workers can be beneficial in situations where there is a bottleneck in the CPU-GPU communication, which can happen when there are too many workers loading data onto the GPU at the same time. This can lead to decreased GPU utilization and longer training times. By reducing the number of workers, you can reduce the number of data loading requests on the CPU and allow for more efficient communication with the GPU, which can lead to increased GPU utilization and faster training times. The impact of reducing the number of workers will depend on your specific hardware and dataset, and I recommend benchmarking different configurations to find the optimal settings. Please let me know if you have any further questions.

**Comment by glenn-jocher** [comment]
Removing TODO tag as issue is now resolved.
