### ISSUE TITLE
sudden increase in cpu utilization while training

### ISSUE THREAD

**Issue by sc-deeraj** [ultralytics/ultralytics#5095]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

![CPU Utilization](https://github.com/ultralytics/ultralytics/assets/104832750/6fb442c2-38c3-4552-a7c8-a9e9f1e22729)

### Environment

OS                  Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-glibc2.17
Environment         Linux
Python              3.10.13
Install             pip
RAM                 30.81 GB
CPU                 Intel Xeon Platinum 8259CL 2.50GHz
CUDA                11.7
GPU Memory    16 GB

matplotlib          ✅ 3.8.0
numpy               ✅ 1.26.0
opencv-python       ✅ 4.8.0.76
pillow              ✅ 10.0.1
pyyaml              ✅ 6.0.1
requests            ✅ 2.31.0
scipy               ✅ 1.11.2
torch               ✅ 2.0.1
torchvision         ✅ 0.15.2
tqdm                ✅ 4.66.1
pandas              ✅ 2.1.1
seaborn             ✅ 0.12.2
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0

### Minimal Reproducible Example

While training images on Yolov8 with a batch size of 8, I experienced a sudden increase in CPU utilization.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
@sc-deeraj, could you provide additional details, please?

- It appears that you are training Ultralytics YOLOv8 on a Windows PC, is that correct?
- What is the size of your RAM?
- How many workers are you utilizing during the training process?

**Note:** I would recommend using `workers=1` during training on a Windows machine since it tends to run multiple threads. Additionally, you might experience a sudden increase when the system is generating cache files for training and validation data.

Thanks.

**Comment by sc-deeraj** [comment]
Nope, it's clearly mentioned `OS Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-glibc2.17` in the Environment Section. I have not specified the number of workers.

**Comment by RizwanMunawar** [comment]
@sc-deeraj What is the RAM size and what is the CPU memory?

**Comment by sc-deeraj** [comment]
## Environment

OS Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-glibc2.17
Environment Linux
Python 3.10.13

---

RAM 30.81 GB
CPU Intel Xeon Platinum 8259CL 2.50GHz
CUDA 11.7
GPU Memory: 16 GB

**Comment by glenn-jocher** [comment]
@sc-deeraj hello, thank you for providing detailed information about your environment.

Based on the details shared, everything looks in order for running YOLOv8. The provided hardware setup, with an Intel Xeon Platinum CPU and 16 GB of GPU memory, is more than sufficient to handle the demands of YOLOv8 training.

Your Python version and CUDA version are also compatible with YOLOv8. Remember to ensure that your PyTorch version is compatible with the CUDA version you're using. 

Lastly, ensure that your runtime environment has sufficient disk space, as the training process generates a substantial amount of intermediate data.

If you have any specific issues or errors during training, feel free to share more details so we can provide more focused assistance.

Enjoy using YOLOv8!
