### ISSUE TITLE
Evaluation ptfalls

### ISSUE THREAD

**Issue by Wovchena** [ultralytics/ultralytics#5096]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I identified the following problems while working on https://github.com/ultralytics/ultralytics/pull/5069:

1. `DetectionValidator` has hard coded `multi_label=True` in `postprocess()`, but `DetectionPredictor` uses default value, which if `False`. Since these values are different, you may want to make it configurable. If you do so, please, export the value in https://github.com/ultralytics/ultralytics/blob/f2ed2075712d389a29c0ad67950e89343a1b99f7/ultralytics/engine/exporter.py#L391
2. `DetectionValidator` shouldn't modify ground truth values. Detector predictions should be casted to ground truth format instead. Currently there are multiple scaling/shifting/clipping applied to ground truth. This float arithmetic, clipping and possible bugs in modification of ground truth may introduce deviations and affect the resulting metric.
3. I wasn't able to find a way to compute mAP for `DetectionPredictor`. This leaves a possibility for `DetectionPredictor` implementation and reported mAP to be misaligned.

I suspect, these problems exist not only for detection task.
Here's my attempt to solve these problems for detector: https://github.com/ultralytics/ultralytics/pull/5069#issuecomment-1733571506.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Wovchena thank you for pointing out these potential issues in our implementation. Your input is greatly appreciated. I will address each point separately:

1. You're correct in noticing this discrepancy between `DetectionValidator` and `DetectionPredictor`. Making this configurable could indeed encapsulate various scenarios better. Your suggestion to export the value in the `exporter.py` could provide a traceability solution for the configuration.

2. Your point about not modifying ground truth values in `DetectionValidator` and casting detector predictions to ground truth format instead, is a valuable perspective. We should indeed maintain the integrity of the ground truth data to avoid any unintended consequences in evaluations. We will look closer at the potential improvements you highlighted.

3. Finally, as for the mAP computation for `DetectionPredictor`, it's something we currently do not have but will certainly consider forming part of our future plans. A method to compute mAP could indeed help in the alignment check between the `DetectionPredictor` and the reported mAP.

These are all insights we can potentially incorporate for not just the detection task, but others as well.

We welcome your insights and absolutely appreciate your effort in attempting to solve these issues as seen in your comment. Please, if you're comfortable with it, continue your proposed changes and submit a PR. We'll be glad to review and offer inputs.

Thank you once again for your valuable perspective!
