### ISSUE TITLE
How to crop detected images from yolov8 boxes?

### ISSUE THREAD

**Issue by kunwarashok** [ultralytics/ultralytics#5097]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I tried to crop and save detected images from yolov8 boxes using following code but it didn't work
```
for i, box in enumerate(result.boxes):
    x1, y1, x2, y2 = [round(x) for x in box.xyxy[0].tolist()]
    w = x2-x1
    h = y2-y1
    object = resized_image[y1:h, x1:w]
    cv2.imwrite('crop_' + str(i) + '.jpg', object)
```

I get following error:
(-215:Assertion failed) !_img.empty() in function 'imwrite'

**Comment by kunwarashok** [comment]
@RizwanMunawar Thank you , it worked !!!

**Comment by RizwanMunawar** [comment]
You're welcome! I'm glad to hear that it worked for you! If you have any more questions or need further assistance, feel free to ask.
