### ISSUE TITLE
Colors cant be found

### ISSUE THREAD

**Issue by moahaimen** [ultralytics/ultralytics#5100]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i need to import the colors from Yolov8 so when i write "
!pip install ultralytics
!pip install ensemble-boxes   
!pip3 install --upgrade ultralytics 
 from ultralytics import YOLO
from ultralytics.yolo.utils.plotting import colors

 i receive this error "ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-3-e58a3bcbf2e5>](https://localhost:8080/#) in <cell line: 2>()
      1 from ultralytics import YOLO
----> 2 from ultralytics.yolo.utils.plotting import colors

ModuleNotFoundError: No module named 'ultralytics.yolo'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by glenn-jocher** [comment]
@moahaimen there's no more ultralytics.yolo, instead import directly from ultralytics.utils:
```
from ultralytics.utils.plotting import colors
```
