### ISSUE TITLE
results = model.track()  occurs error 'YOLO' object has no attribute 'track' in object tracking

### ISSUE THREAD

**Issue by Jeong-m1n** [ultralytics/ultralytics#5106]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I am following object tracking code using YOLOv8 on OpenCV, without any modification. I cloned code but when I run the code, error occurs - this is the error message.
```
" 'Yolo' object has no attribute 'track' 
  File "C:\Users\infoworks\Downloads\source_code\yolov8\yolov8.py", line 18, in <module>
    results = model.track(frame, persist=True)
              ^^^^^^^^^^^
AttributeError: 'YOLO' object has no attribute 'track'"
```

![image](https://github.com/ultralytics/ultralytics/assets/105257911/58a9a56e-4b54-49ae-b8c4-6cd5f311f25a)
 
I tried to find out what cause the error, but every example includes `results = model.track(source = "", show = True)` or `results = model.track(frame, persist= True)`

How can I resolve this problem? 
This is entire code
```
import cv2
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('yolov8n.pt')

# Open the video file
video_path = "los_angeles.mp4"
cap = cv2.VideoCapture(video_path)

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 tracking on the frame, persisting tracks between frames
        results = model.track(frame, persist=True)

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Display the annotated frame
        cv2.imshow("YOLOv8 Tracking", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()

```

Thanks

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
Hello @Jeong-m1n! The code you've supplied functions correctly when using `ultralytics==8.0.184`. Please ensure that you have installed the latest version of Ultralytics, and it should certainly function as expected.

Thanks.

**Comment by Jeong-m1n** [comment]
Thanks! It was very simple problem 😂

**Comment by glenn-jocher** [comment]
Hello @Jeong-m1n, we're glad to hear you were able to resolve the issue! It happens to the best of us, sometimes the simplest things can trip us up. If you have any more questions or run into anymore problems, don't hesitate to let us know. Happy coding!

**Comment by charlotepencier** [comment]
I have the same issue. 

import os

os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

from ultralytics import YOLO
model_path = r"C:\visu_ai\Face_recognition\code\yolov8n-face.pt"

model = YOLO(model_path)
results = model.track(source=0, show=True, tracker = "bytetrack.yaml")

This is my code. 

I am getting this error 
Traceback (most recent call last):
  File "c:\visu_ai\Face_recognition\code\person_track.py", line 9, in <module>
    results = model.track(source=0, show=True, tracker = "bytetrack.yaml")
AttributeError: 'YOLO' object has no attribute 'track'
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-Break to quit

My torch version is 2.2 and ultralytics is 8.1
