### ISSUE TITLE
Track only specific objects

### ISSUE THREAD

**Issue by pamudu123** [ultralytics/ultralytics#5109]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I want to track specific objects detected by the YOLO model. When I use tracking, it currently tracks everything it detects, but I only want to track one or two specific objects.
The code I am using is this
```
results = model.track(frame, persist=True)
annotated_frame = results[0].plot()
```

### Use case

Sometimes, it's unnecessary to track small objects, and I only need to track specific objects. I believe this feature should be implemented. If it can be implemented, please let me know how to do it.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
Hey there, @pamudu123! To focus on tracking a specific class, you can utilize the `classes` parameter. Below, you'll find a sample command for achieving this:

### Command Line Interface (CLI)
```cli
# To detect the 'person' class
yolo track model=yolov8n.pt source="https://youtu.be/8r8hYenr5j8" persist=True, show=True, classes=0
```

### Python
```python
# Import cv2
from ultralytics import YOLO

# Load the YOLO model
model = YOLO('yolov8n.pt')

# Perform tracking for the 'person' class
results = model.track(0, persist=True, show=True, classes=0)
```

This allows you to specifically track objects belonging to the 'person' class.

**Comment by zama-sarib** [comment]
I want my model to draw bounding box on all classes but track only specific class. The above solution draws and tracks the bounding box on the only specified class.

**Comment by glenn-jocher** [comment]
@zama-sarib understood! For your use case, you'll want to modify the tracking behavior after detection. First, perform detection normally to draw bounding boxes on all classes. Then, filter the `results` to only include the specific classes you want to track before passing them to the tracking function. Currently, this requires custom post-processing of the `results` object. Please refer to the documentation for guidance on manipulating the `results` object for tracking specific classes. 📘

**Comment by zama-sarib** [comment]
Got it. Thank for the assistance.

**Comment by glenn-jocher** [comment]
@zama-sarib you're welcome! If you have any more questions or need further assistance, feel free to reach out. Happy tracking! 😊🚀
