### ISSUE TITLE
model.predict

### ISSUE THREAD

**Issue by Wearant** [ultralytics/ultralytics#511]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Please tell me how to get data about the class that was detected ?
Why names is returned empty
![DJs3HVa - Imgur](https://user-images.githubusercontent.com/78465917/213546007-11d5497c-0723-445b-a40c-f23365f0b572.png)

**Comment by Wearant** [comment]
The issue is resolved

**Comment by manuelgutierrezchaves** [comment]
How did you resolve it @Wearant ? I can't get the names of the classes either.

**Comment by JakobStadlhuber** [comment]
Same, the problem is still not solved

**Comment by pderrenger** [comment]
@JakobStadlhuber you can retrieve the class information by parsing the model's prediction dictionary. The "names" field being empty may indicate that the model wasn't loaded with a dataset that includes class names. Make sure to train the model on a dataset with labeled classes such as COCO, VOC, or others, and then validate the model to ensure the class names are properly loaded.
