### ISSUE TITLE
Start training without pretrained model

### ISSUE THREAD

**Issue by Egorundel** [ultralytics/ultralytics#5113]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello!
How to start training without pre-trained weights? 
Am I running the training correctly without pre-trained weights? 
Look at my Python configuration file, my startup folder, and the terminal output.

#### Configure of network (train.py):
![Screenshot from 2023-09-27 11-58-31](https://github.com/ultralytics/ultralytics/assets/65890558/13c15367-242b-4d5e-94c6-38d54899549e)

#### The folder from which I run the training (startup folder):
![Screenshot from 2023-09-27 12-01-42](https://github.com/ultralytics/ultralytics/assets/65890558/6af14bbb-3a90-4a0c-9c98-c2dfba956d3e)

#### The terminal output (console):
![Screenshot from 2023-09-27 12-02-33](https://github.com/ultralytics/ultralytics/assets/65890558/d794f90b-6a7b-4752-ac70-1c8750c7c76d)

Why is it starting `"AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n..."` with YOLOv8n.pt if I specify `pretrained=False` ?

**Comment by glenn-jocher** [comment]
@Egorundel hello!

Firstly, thanks for reaching out and providing detailed information about your configuration and the output you're observing. That's very helpful!

When starting training without pretrained weights, setting `pretrained=False` is indeed the recommended approach. The YOLOv8 repo is designed to automatically load pretrained weights when it's available, unless you instruct it otherwise.

However, the `"AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n..."` log line you're seeing is not associated with the model weights. It's actually a part of a setup routine that checks for the compatibility of your system with Automatic Mixed Precision (AMP) technology.

YOLOv8n.pt in this context does not refer to a set of pretrained weights, but rather to a network configuration for YOLOv8. The training script uses this configuration to setup and verify the compatibility of your hardware with AMP, among other things. That's why you're seeing this message although you've set `pretrained=False`.

So to answer your question, yes, as far as your description and screenshots indicate, you're correctly running the training without loading pretrained weights.

Hope this helps and do let me know if you have any further questions!

Best,
Glenn

**Comment by Egorundel** [comment]
@glenn-jocher Thanks for your answer!

**Comment by glenn-jocher** [comment]
@Egorundel, you're welcome! I'm glad I could assist. If you have any additional questions or concerns regarding YOLOv8, feel free to bring them up. We're always here to help. Wishing you good luck with your model training!

**Comment by Egorundel** [comment]
@glenn-jocher I also wanted to ask why I specify the folder to save the way I want, and it still doesn't change when I start learning?

### My config file (train.py):
![Screenshot from 2023-09-29 09-06-40](https://github.com/ultralytics/ultralytics/assets/65890558/bb92ca8d-a34b-463c-9d7a-4b010230d1f3)

### Start of training:
![Screenshot from 2023-09-29 09-07-08](https://github.com/ultralytics/ultralytics/assets/65890558/a36c5c1f-031d-4f7c-94d0-a8f83a1752cf)

**Comment by glenn-jocher** [comment]
@Egorundel, hello again!

From your provided screenshots, I can see that you have correctly specified the directory for the saved model in the configuration file.

However, when training starts, YOLOv8 by default creates a new directory under the root directory called `runs/train` to save all your training information. This is done to ensure an organized structure and prevent potential overwriting of files from previous training runs.

The name of the training run directory will be an incrementing value - like `exp`, `exp2`, `exp3`, etc. - to distinguish between different training runs. It includes all outputs including model weights, results.png, results.txt, etc.

Therefore, while your weights are being saved as per your specification in the config file, all the training details by default get saved in a separate directory structure under `runs/train`.

I hope this clarifies the confusion. If you have further questions or if anything is unclear, feel free to ask!

Best,
Glenn

**Comment by thanhhuyenpt** [comment]
@glenn-jocher I train yolov8-pose with model: yolov8s-pose-p2.yaml (add P2 branch to head), and I set pretrained = True. However, I saw that there is NO file yolov8-pose-p2.yaml in ultralytics/cfg/models /v8/ (config model). I wonder if I set pretrained = True, and train with yolov8s-pose-p2.yaml, what will a pretrained model be used?

**Comment by glenn-jocher** [comment]
Hello @thanhhuyenpt,

When you set `pretrained=True` in your configuration file and start training with `yolov8s-pose-p2.yaml`, the Ultralytics YOLOv8 training script will attempt to first locate a pretrained model. However, considering you mentioned there's no `yolov8s-pose-p2.yaml` file under `ultralytics/cfg/models/v8/`, it implies there are no specific pretrained weights for this model configuration available in the repo.

In such a situation, the training operation defaults to using the weights of a model that is compatible as a starting point. Keep in mind, these pretrained weights essentially serve as a good starting point for the model's weights before training begins and aren't necessarily tied to a specific model configuration.

Hope that helps clarify how pretraining works with YOLOv8.

Best,
Glenn

**Comment by QxNam** [comment]
Can you show me the yaml file you put in the model?

**Comment by glenn-jocher** [comment]
@QxNam certainly! The YAML file used for the model defines the architecture and is included in the repository. However, I cannot show the file contents here. You can find all model YAML files within the `models` directory of the YOLOv8 repository. Please refer to the documentation for guidance on how to navigate and use these files for your training purposes.

**Comment by farhan-hafizh** [comment]
@glenn-jocher Hi, i wonder what if i change the yaml file of, e.g. yolo12 adding some attention block, and set the `pretrained=True`, if i trained the loaded yolo12 modified model, will it using the pretrained weight of the yolo12 as the starting point? or is it loaded untrained model if i do like `model = YOLO('yolo12n.yaml')` and i change the yolo12n.yaml

**Comment by glenn-jocher** [comment]
@farhan-hafizh when you modify the YAML file (like adding attention blocks to YOLO12) and set `pretrained=True`, the system will attempt to load the original pretrained weights, but only layers with matching names and dimensions will be loaded. The new attention blocks you added will be randomly initialized since they don't exist in the original pretrained model. You'll likely see warnings about mismatched keys during loading. For significant architectural changes like this, it's often better to set `pretrained=False` to train from scratch, or use a custom pretrained path if you have compatible weights for your modified architecture.

**Comment by Edwardzdh** [comment]
@glenn-jocher Hello, I encountered two issues related to the WARNING AMP message during model training, and I would appreciate some guidance.

### Issue 1: AMP warning on local training (GTX 1660 Ti)
I'm training the model on my local machine with a GTX 1660 Ti GPU, which has limited performance. After starting the training script, I receive the following warning:
`WARNING AMP: checks failed. AMP training on an NVIDIA GeForce GTX 1660 Ti GPU may cause NaN losses or zero-mAP results, so AMP will be disabled during training.`
I understand that AMP will simply be disabled, and the training itself can still proceed normally. However, I would like to confirm: **Does this warning or the AMP disablement have any negative impact on the final training results?**

### Issue 2: AMP check triggers download failure on Google Colab (T4 GPU)
When training on Google Colab with a T4 GPU, I see this message during AMP checks:
`AMP: running Automatic Mixed Precision (AMP) checks...`
`WARNING ⚠️ Download failure, retrying 1/3 https://github.com/ultralytics-main/assets/releases/download/v8.3.0/yolo11n.pt... HTTP Error 404: Not Found`
This eventually causes the training to fail with:
`FileNotFoundError: [Errno 2] No such file or directory: 'yolo11n.pt'.`
My question is: **Do I need to manually download yolo11n.pt and place it in a specific directory, or is this an unexpected behavior in the AMP check process?**

Thank you very much for your help and for maintaining this project!

**Comment by glenn-jocher** [comment]
@Edwardzdh Thanks for the detailed notes. On GTX 1660 Ti, the AMP warning is expected; we disable AMP on that GPU class and this does not hurt final accuracy—only speed/VRAM—so you can silence it with `amp=False` (see the [check_amp reference](https://docs.ultralytics.com/reference/utils/checks/) and the [Train settings](https://docs.ultralytics.com/modes/train/)). For Colab, you don’t need to manually download `yolo11n.pt`; the AMP check fetches it automatically—your 404 usually means an outdated install or a transient network issue—please upgrade and restart the runtime, or bypass AMP checks as shown below.

bash
pip install -U ultralytics

python
from ultralytics import YOLO
model = YOLO("yolo11n.pt")  # or your model
model.train(data="coco8.yaml", amp=False)

bash
yolo train model=yolo11n.pt data=coco8.yaml amp=False

If this persists, open a new issue for visibility with the text output of `yolo checks`, your full traceback, and the exact command; the troubleshooting guide may also help: [Troubleshooting Common YOLO Issues](https://docs.ultralytics.com/guides/yolo-common-issues/).
