### ISSUE TITLE
save_dir is not a valid key.

### ISSUE THREAD

**Issue by ZicsX** [ultralytics/ultralytics#512]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection, Export

### Bug

I am facing an error while trying to run the YOLO in my command line, specifically when trying to specify 'save_dir' key. The error message states that 'save_dir' is not a valid key and suggests similar keys like 'save_crop', 'save' and 'save_hybrid'.
```bash
yolo task=detect mode=predict model=best.pt source='./' save_txt=True save_dir='./'
save_dir is not a valid key. Similar keys: ['save_crop', 'save', 'save_hybrid']
```
![image](https://user-images.githubusercontent.com/36122092/213551150-b7d36ade-4bb0-42df-ac11-a6549eb79191.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Robotatron** [comment]
Similar issue https://github.com/ultralytics/ultralytics/issues/508

Seems like a general bug?

**Comment by glenn-jocher** [comment]
@ZicsX @Robotatron save_dir is not a valid key. To save to PROJECT/NAME directory.

```
yolo train project=PROJECT name=NAME
```

**Comment by dmddmd** [comment]
and the SDK way, please?

**Comment by alexandercronin** [comment]
@dmddmd  please see an example of how to use this below: 
```
from ultralytics import YOLO
import subprocess

# Load a model
model = YOLO("yolov8n.pt")  # load an official model

# Predict with the model
results_detection = model(source="https://ultralytics.com/images/bus.jpg", 
                            show=True,        # only works in standard python environment and when operating on a PIL Image
                            save_txt=True,    # works correctly: generates the labels folder with text files,  
                                                #  the name of the file is the same as the name of the image with the extension .txt,
                                                #  the file contains the class number and the 4 co-ords for the bounding box
                            save_conf=True,   # has no effect if set to True or False
                            save_crop=True,   # works correctly 
                            # visualize=True, # not yet supported
                            classes=0,        # works correcly by filtering for the person class
                            boxes=True,        # has no effect if set to True or False unless doing segmentation
                            project="my_project_name", 
                            name="my_experiment_name"
                         )
```

**Comment by Robotatron** [comment]
> @ZicsX @Robotatron save_dir is not a valid key. To save to PROJECT/NAME directory:
> 
> ```
> yolo train project=PROJECT name=NAME
> ```

Yes, it's not a valid key but it would be nice to ignore this key to be able to use "args.yaml" as an input config for new runs, please see here https://github.com/ultralytics/ultralytics/issues/508

**Comment by apiszcz** [comment]
need save_dir or equivalent for predict, as noted elsewhere not in documentaton.

**Comment by DavideMammana** [comment]
Hi @glenn-jocher, I have the same problem, I understand that save_dir is not supported at the moment, but that means we can't save results directory in the root experiment of training.

I give you an example, I use Hydra to mange configurations which automatically create an experiment for me under a specific folder let's say
my_experiment/timestamp

I don't want to have yolo results under
my_experiment/timestamp/detection/train

but directly under 
my_experiment/timestamp

Right now this is currently not possible as if I specify an empty string for project and name defaults value are used, I can cheat on project by putting ./ but i can't do the same for name as a folder will be created as

my_experiment/timestamp/.2/

Would it be nice to be able to specify a save_dir also to have a greater customization :D, it seems to me like a free code change, there is already an if else checking this behaviour.
