### ISSUE TITLE
BUG when deploy YOLO to GPU.

### ISSUE THREAD

**Issue by Harxis** [ultralytics/ultralytics#5136]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### 1. When I first deploy the yolo model to a particular GPU, which is not specified at the time of prediction, I can see that the calculations are performed on CUDA:0, but a certain amount of VRAM is taken up on CUDA:2.
![image](https://github.com/ultralytics/ultralytics/assets/35892232/6cb8fb6d-500b-4131-a778-e08df22f5a43)
![image](https://github.com/ultralytics/ultralytics/assets/35892232/5a39ea15-120d-40c8-a0d7-62a5c51b6719)

### 2. When I first deploy the yolo model to a specific GPU and specify the GPU when predicting, it can be seen that the calculation is performed on CUDA:2, but a certain amount of VRAM is occupied on CUDA:0. (Contrary to case 1.)
![image](https://github.com/ultralytics/ultralytics/assets/35892232/cc81f441-9c6a-4f7e-a4f9-9bdfc65d434e)
![image](https://github.com/ultralytics/ultralytics/assets/35892232/0a5f8dbb-d835-4906-b0a8-ccd9d48e11e3)

### 3. When I do not deploy yolo to a specific GPU in advance and only specify the GPU device used when making predictions, the calculation is performed on the specified GPU. However, CUDA:0 also takes up a certain amount of VRAM. 

*Note that the device is a class of torch.device.*
![image](https://github.com/ultralytics/ultralytics/assets/35892232/ce955d61-6293-48f5-b219-d57503947926)
![image](https://github.com/ultralytics/ultralytics/assets/35892232/19bedc1f-fe47-4c8e-81d0-62515472bc1b)

### 4. When I specify the GPU as an integer in the prediction, the GPU used for the calculation is correct and no extra VRAM is taken on CUDA:0.
![image](https://github.com/ultralytics/ultralytics/assets/35892232/b64908d2-e64f-4246-a84a-423458f46e11)
![image](https://github.com/ultralytics/ultralytics/assets/35892232/c9238933-7e38-461d-8d4f-962a9bcdb41c)

### 5. When I do predictions with multiprocessing, if the device specified is of type torch.device, it takes up extra VRAM on CUDA:0.
![image](https://github.com/ultralytics/ultralytics/assets/35892232/f688d2bc-3e5d-415c-ba79-d8e42e4ae864)
![image](https://github.com/ultralytics/ultralytics/assets/35892232/54cecf43-aabc-4082-ae64-7c3097afb932)

### 6. When the specified GPU is an integer number, the computation is correct on the specified GPU.
![image](https://github.com/ultralytics/ultralytics/assets/35892232/4c9b8e3b-bb77-41e6-9dec-696b71dfa3a3)
![image](https://github.com/ultralytics/ultralytics/assets/35892232/b38e87a6-f866-4b5f-8414-0114ea509c0e)

**It looks like specifying an integer when specifying a device solves the problem, but specifying it as an integer causes the problem in #4941 again.**

### Environment

Ultralytics YOLOv8.0.186 🚀 
Python-3.10.11 
torch-1.13.1 
CUDA: NVIDIA GeForce RTX 4090

### Minimal Reproducible Example

``` python
import torch
from ultralytics.models import YOLO
from torch.multiprocessing import Process


def single_process(gpu_idx=2):
     yolo = YOLO('yolov8n.pt')
     device = torch.device(f'cuda:{gpu_idx}')
    #  yolo.to(device)
     yolo.predict('demovideo.mp4', device=gpu_idx)  # change device here


def multi_process(gpu_idxs=[1, 2, 3, 4]):
     processes = []
     for i in range(len(gpu_idxs)):
          p = Process(target=single_process, args=(gpu_idxs[i],))
          processes.append(p)
          p.start()
     
     for p in processes:
          p.join()

if __name__ == '__main__':
     single_process()
    #  multi_process()



### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Harxis** [comment]
In addition, regarding the extra memory usage on CUDA:0, I found that it is caused by ``torch.cuda.synchronize()`` in line 58 of ``ultralytics/utils/ops.py``, but I don't know why.

**Comment by glenn-jocher** [comment]
@Harxis thanks for the bug report! We've been making some updates recently around device handling. Is this issue still present in the latest version (8.0.188?)

**Comment by Harxis** [comment]
@glenn-jocher Hi, I have tested on the latest version (8.0.188) and the problem still exist. A simple example to reproduce the bug is
```python
import torch
from ultralytics.models import YOLO
from ultralytics import checks

def single_process(gpu_idx=2):
     checks()
     yolo = YOLO('yolov8n.pt')
     device = torch.device(f'cuda:{gpu_idx}')
     yolo.predict('demovideo.mp4', device=device)

if __name__ == '__main__':
     single_process()
```
You can see some memory usage on ``CUDA:0``, even though the device I specified to compute on is ``CUDA:2``.   
![image](https://github.com/ultralytics/ultralytics/assets/35892232/011a7733-aa12-47c5-94ef-b550f6315984)

**Comment by RizwanMunawar** [comment]
@Harxis, it's possible that memory usage could be affected if there are other programs running concurrently. The key factor to focus on is 'GPU utilization,' which is evident from the activity on `CUDA:2.` This indicates that GPU 2 is mainly engaged in the training process.

Thank you.

**Comment by Harxis** [comment]
@RizwanMunawar Thank you for your answer. There are in fact no other memory-using programs running, this is quite strange. As shown in `Case 5`, if I enable multi-process prediction processing for multiple videos, a large amount of extra memory will be loaded on my CUDA:0, and it reduces the utilization of CUDA:0. You can easily reproduce the bugs I encountered using the example code I provided.

**Comment by glenn-jocher** [comment]
@Harxis, thank you for your detailed observations and your patience. From your description, it seems like there might be an unusual allocation of memory in the multi-GPU environment, and I appreciate your effort to help us understand the problematic scenario.

Below are my thoughts:

- When calling torch functions that utilize CUDA, PyTorch often initializes on GPU 0 by default before moving operations to designated GPUs.
- In a multi-GPU environment, CUDA context and device memory allocation is somehow referenced on GPU 0 which might be causing some memory overhead on CUDA:0 even when other GPUs are carrying out computations.
- When multiprocessing is involved, each process might initialize CUDA context independently, and this could cause the increased memory usage on CUDA:0.

Unfortunately, without involving coding workaround, the solution may be a complex one as it resides deep within how PyTorch CUDA operations interact with the GPU infrastructure. The PyTorch forum might have similar discussions around this topic which might be worth exploring.

Meanwhile, we will take a note of this and explore if there's an optimization we can implement in future YOLOv8 versions to better manage the GPU memory allocation in multi-GPU settings. Thanks again for raising this valuable point.

**Comment by Harxis** [comment]
@glenn-jocher Thank you very much for your excellent work. I sincerely hope that you can follow up with questions about GPU deployment.

**Comment by glenn-jocher** [comment]
@Harxis, thank you for your kind words and for bringing this issue regarding GPU deployment to our attention. We're always working to improve the capabilities of YOLOv8, and user feedback plays a significant role in that process.

From your description, it sounds like there are issues with the way memory is allocated across multiple GPUs under certain circumstances. This is indeed a complex problem, as it involves the architecture of PyTorch and how it interacts with CUDA and GPU hardware infrastructure.

In a multi-GPU environment, memory allocation can sometimes be initialized or referenced on a default GPU before moving to other specified GPUs for computation. This may cause unexpected memory usage on the default GPU. When multiprocessing, each process may initialize its own CUDA context independently, potentially leading to increased memory usage on the default GPU.

We understand that optimizing memory allocation in multi-GPU settings is important for efficiency and performance. Rest assured, we'll explore this based on your feedback and consider possible enhancements in future updates of YOLOv8.

Thanks again for bringing this to our attention. Your detailed observations and insights are greatly appreciated.
