### ISSUE TITLE
Training with non-square network? 

### ISSUE THREAD

**Issue by majnas** [ultralytics/ultralytics#514]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Really appratiate your hardwork :+1: 
I have a dataset of rectanglular images with sizes around 3840x1440 when I set imgsz=640 the network will resize all images to 640x640 and train it. I want to set sth like imgsz=[1280,480] to train the network, I don't know to set that!?

```
# works fine
yolo task=detect mode=train model=yolov8n.pt data=A.yaml batch=8 epochs=3 imgsz=640 

# I want sth like this
yolo task=detect mode=train model=yolov8n.pt data=A.yaml batch=8 epochs=3 imgsz=1280,640 
```

**Comment by CySlider** [comment]
simply set imgsz=1280 and rect=True

You can validate it working by looking at train_batch0.jpg file in the model folder

**Comment by pderrenger** [comment]
@CySlider simply set `imgsz=1280` and `rect=True` to train the network with your non-square images. You can validate it by examining the `train_batch0.jpg` file in the model folder. Happy training! 😊
