### ISSUE TITLE
Wandb finish training method call

### ISSUE THREAD

**Issue by Rephil2** [ultralytics/ultralytics#5141]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Integrations

### Bug

in callbacks/wb.py
I found that there is no call to stop the exp tracking at wanb. so I simply just added the line: wb.run.finish() at the bottom of the  method:

def on_train_end(trainer):
    """Save the best model as an artifact at end of training."""
    _log_plots(trainer.validator.plots, step=trainer.epoch + 1)
    _log_plots(trainer.plots, step=trainer.epoch + 1)
    art = wb.Artifact(type='model', name=f'run_{wb.run.id}_model')
    if trainer.best.exists():
        art.add_file(trainer.best)
        wb.run.log_artifact(art, aliases=['best'])
    wb.run.finish()

This seemed to fix the problem. I can't tell if it was left out for some odd reason that I have yet to understand, if so please explain.  

### Environment

Ultralytics YOLOv8.0.188 🚀 Python-3.10.11 torch-2.0.1 CUDA:0 (NVIDIA GeForce RTX 4090, 24184MiB)
Setup complete ✅ (20 CPUs, 125.6 GB RAM, 795.4/911.8 GB disk)

### Minimal Reproducible Example

Run a train exp with wandb as logger.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Rephil2 hi there! Thank you for reaching out with your question and potentially catching something important.

The `wb.run.finish()` method indeed stops an experiment's tracking with wandb, and it's typically necessary to call this at the end of the training to ensure all data is accurately logged. 

Your addition seems like it'd correct the issue you're seeing and finish logging the run as expected. I can't think of any immediate reason why it was left out; it may very well be an oversight.

However, the team will need to thoroughly assess it to ensure there are no ripple effects or it doesn't counteract other mechanisms. It's crucial that the intricate system within YOLOv8's training process continues to work seamlessly. 

We genuinely appreciate your time and effort for bringing this to our attention. This kind of proactive community engagement is vital for improving open-source repositories like YOLOv8! 

If there's anything else you have concerns about in the future, feel free to reach out again!
