### ISSUE TITLE
Deepsparse with custom model

### ISSUE THREAD

**Issue by MohammadsAdrA-AI** [ultralytics/ultralytics#5146]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi there 
I want to use the deepsparse and my own custom model, but I couldn't find anything neither from your docs or deepsparse docs on how to do that. 
can you help me?

**Comment by glenn-jocher** [comment]
@MohammadsAdrA-AI hello,

Thank you for exploring YOLOv8. To use Deepsparse with your custom model, you would typically need to perform a few steps. Firstly, train your model using the train mode provided by YOLOv8. Once your model is trained, you need to export your model using the export mode. This mode helps to provide deployment-ready model files in formats like ONNX, TorchScript, and CoreML.

Now for Deepsparse integration, you should import your custom-trained model in the ONNX format. Remember that Deepsparse accepts ONNX models. 

So, you have to export your custom model using YOLOv8's export mode to ONNX, then you can load this ONNX model into Deepsparse.

Hopefully, this clears up the process for you. If you have more questions or need further clarifications, feel free to ask.

Best Regards,
Glenn Jocher

**Comment by MohammadsAdrA-AI** [comment]
@glenn-jocher Thank you so much for reply.
This is the code that I used for deepsparse: 
```
from deepsparse import Pipeline
import time
# list of images in local filesystem
images = ["test.jpg", "test.jpg"]
# create Pipeline
model_stub = 'yolov8s.onnx'
yolo_pipeline = Pipeline.create(
    task="yolo",
    model_path=model_stub,
)
while True: 
    time1 = time.time()
    pipeline_outputs = yolo_pipeline(images=images, iou_thres=0.6, conf_thres=0.001, imgsz=640)
    print(time.time() - time1)
    ```
    and the results: 
    ```
0.41994380950927734
0.42912912368774414
0.4206986427307129
0.44445300102233887
0.5158634185791016
```
but If I used the yolov8s.onnx by it's self:
the simple code is: 
```
from ultralytics import YOLO
import time
# Load a model
model = YOLO('yolov8s.onnx')
images = ["test.jpg", "test.jpg"]

while True: 
    time1 = time.time()
    #outputs = compiled_model([frame,frame]) 
    results = model(images)

    print(time.time() - time1)
 ```
```
0: 640x640 1 person, 1 chair, 3 refrigerators, 1: 640x640 1 person, 1 chair, 3 refrigerators, 381.7ms
Speed: 2.0ms preprocess, 190.8ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 640)
0.5797970294952393

0: 640x640 1 person, 1 chair, 3 refrigerators, 1: 640x640 1 person, 1 chair, 3 refrigerators, 356.5ms
Speed: 2.3ms preprocess, 178.3ms inference, 0.8ms postprocess per image at shape (1, 3, 640, 640)
0.5510389804840088

0: 640x640 1 person, 1 chair, 3 refrigerators, 1: 640x640 1 person, 1 chair, 3 refrigerators, 371.2ms
Speed: 2.1ms preprocess, 185.6ms inference, 0.8ms postprocess per image at shape (1, 3, 640, 640)
0.5561480522155762

0: 640x640 1 person, 1 chair, 3 refrigerators, 1: 640x640 1 person, 1 chair, 3 refrigerators, 380.4ms
Speed: 2.1ms preprocess, 190.2ms inference, 0.8ms postprocess per image at shape (1, 3, 640, 640)
0.5618157386779785

0: 640x640 1 person, 1 chair, 3 refrigerators, 1: 640x640 1 person, 1 chair, 3 refrigerators, 404.7ms
Speed: 2.6ms preprocess, 202.4ms inference, 0.8ms postprocess per image at shape (1, 3, 640, 640)
0.6188490390777588
```
my question is what am I missing that I can't reach 5x faster as they promissed

**Comment by glenn-jocher** [comment]
Hi @MohammadsAdrA-AI,

The performance enhancement claims made by Deepsparse are typically based on benchmarks and specific hardware they have used for testing. The actual speedup that you experience can vary based on a variety of factors including the specific model, the system capabilities, GPU and CPU being used, optimization settings, batch size, and more.

In your case, there could be multiple factors at play causing the difference between your experiences and the claims. For example, Deepsparse makes use of sparse operations which can lead to significant speedups if used properly. The extent of sparsity in your model could be one contributing factor. Also, the pipeline performance can be influenced by input preprocessing or differences in the postprocessing and NMS steps. Additionally, the time taken for disk I/O operations when loading images could influence the overall inference time.

Finally, it's worth noting that Deepsparse engine thrives on CPU-bound environments, so if you're comparing it with a GPU-optimized environment, the results may not be as pronounced.

For a more in-depth analysis of the performance, you might want to engage with the Deepsparse team directly, as they would be better equipped to provide specific insights as per your environment and model.

Best Regards,
Glenn Jocher

**Comment by Hemilibeatriz** [comment]
> @glenn-jocher Thank you so much for reply. This is the code that I used for deepsparse:
> 
> ```
> from deepsparse import Pipeline
> import time
> # list of images in local filesystem
> images = ["test.jpg", "test.jpg"]
> # create Pipeline
> model_stub = 'yolov8s.onnx'
> yolo_pipeline = Pipeline.create(
>     task="yolo",
>     model_path=model_stub,
> )
> while True: 
>     time1 = time.time()
>     pipeline_outputs = yolo_pipeline(images=images, iou_thres=0.6, conf_thres=0.001, imgsz=640)
>     print(time.time() - time1)
>     ```
>     and the results: 
>     ```
> 0.41994380950927734
> 0.42912912368774414
> 0.4206986427307129
> 0.44445300102233887
> 0.5158634185791016
> ```
> 
> but If I used the yolov8s.onnx by it's self: the simple code is:
> 
> ```
> from ultralytics import YOLO
> import time
> # Load a model
> model = YOLO('yolov8s.onnx')
> images = ["test.jpg", "test.jpg"]
> 
> while True: 
>     time1 = time.time()
>     #outputs = compiled_model([frame,frame]) 
>     results = model(images)
> 
>     print(time.time() - time1)
> ```
> 
> ```
> 0: 640x640 1 person, 1 chair, 3 refrigerators, 1: 640x640 1 person, 1 chair, 3 refrigerators, 381.7ms
> Speed: 2.0ms preprocess, 190.8ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 640)
> 0.5797970294952393
> 
> 0: 640x640 1 person, 1 chair, 3 refrigerators, 1: 640x640 1 person, 1 chair, 3 refrigerators, 356.5ms
> Speed: 2.3ms preprocess, 178.3ms inference, 0.8ms postprocess per image at shape (1, 3, 640, 640)
> 0.5510389804840088
> 
> 0: 640x640 1 person, 1 chair, 3 refrigerators, 1: 640x640 1 person, 1 chair, 3 refrigerators, 371.2ms
> Speed: 2.1ms preprocess, 185.6ms inference, 0.8ms postprocess per image at shape (1, 3, 640, 640)
> 0.5561480522155762
> 
> 0: 640x640 1 person, 1 chair, 3 refrigerators, 1: 640x640 1 person, 1 chair, 3 refrigerators, 380.4ms
> Speed: 2.1ms preprocess, 190.2ms inference, 0.8ms postprocess per image at shape (1, 3, 640, 640)
> 0.5618157386779785
> 
> 0: 640x640 1 person, 1 chair, 3 refrigerators, 1: 640x640 1 person, 1 chair, 3 refrigerators, 404.7ms
> Speed: 2.6ms preprocess, 202.4ms inference, 0.8ms postprocess per image at shape (1, 3, 640, 640)
> 0.6188490390777588
> ```
> 
> my question is what am I missing that I can't reach 5x faster as they promissed

Hi @MohammadsAdrA-AI, which version of Ultralytics does this code work with? Could you please let me know? I'm trying to run it with Ultralytics YOLOv8.2.2 but I'm getting an error:

![image](https://github.com/ultralytics/ultralytics/assets/62450495/2407a779-ce73-4902-bbde-10aad5646407)

**Comment by glenn-jocher** [comment]
Hi @Hemilibeatriz,

It seems like there's a version mismatch or a specific compatibility issue with the error you're encountering. First, ensure that you've installed the correct version of our library and dependencies. The code you've posted should work well with the majority of the YOLOv8 series, provided the correct versions are used.

Could you possibly check your environment setup and ensure that everything is updated? Here’s a quick checklist:

- Update Ultralytics YOLO to the latest version (`pip install -U ultralytics`)
- Ensure your ONNX model (`yolov8s.onnx`) is properly converted and compatible with your version of Ultralytics YOLO.

If you continue to face issues, kindly provide:

- The exact error message you're encountering.
- The version of the Ultralytics library you're currently using.

This information will help us pinpoint the issue more accurately! 🎯

**Comment by glenn-jocher** [comment]
Hi there!

Yes, it's generally recommended to use the same version of Ultralytics YOLO for both training and deploying your model. This ensures compatibility and helps avoid potential issues that might arise due to version differences.

To check if your ONNX model is compatible with your version of Ultralytics YOLO, you can try loading the model using the YOLO class:

```python
from ultralytics import YOLO

# Attempt to load the ONNX model
try:
    model = YOLO('path_to_your_model.onnx')
    print("Model loaded successfully!")
except Exception as e:
    print(f"Failed to load model: {e}")
```

If the model loads without throwing an error, it's a good sign that it's compatible with your version of Ultralytics YOLO.

Hope this helps! 😊 Let me know if there's anything else you need!

**Comment by Hemilibeatriz** [comment]
it´s works, my model.onnx and my Ultralytics version are compatibility:

![image](https://github.com/ultralytics/ultralytics/assets/62450495/54a0219e-4dd7-4569-b438-7d14d970cbe3)

So, why can't I use the code below without encountering the IndexError: tuple index out of range?

```
from deepsparse import Pipeline
import time
# list of images in local filesystem
images = ["test.jpg", "test.jpg"]
# create Pipeline
model_stub = 'yolov8s.onnx'
yolo_pipeline = Pipeline.create(
    task="yolo",
    model_path=model_stub,
)
while True: 
    time1 = time.time()
    pipeline_outputs = yolo_pipeline(images=images, iou_thres=0.6, conf_thres=0.001, imgsz=640)
    print(time.time() - time1)

```

**Comment by glenn-jocher** [comment]
@Hemilibeatriz hey there,

Great to hear your model is compatible! Regarding the `IndexError`, it might be related to how the `images` array is handled within the `Pipeline.create` method. Ensure that the image paths are directly accessible from the directory where your script runs, or provide absolute paths to the images.

If everything seems correct and you're still facing issues, it might be helpful to check the specific line of code triggering this error for a deeper insight. Sometimes, slight modifications in how lists or arrays are indexed or iterated can resolve such errors.

Hope this helps! If the issue persists, feel free to share a bit more detail, especially the exact error message and line of code it points to! 😊
