### ISSUE TITLE
How to print out the Performance results for each layer of modules with Flops, parameters, inferencen time??

### ISSUE THREAD

**Issue by AndywithCV** [ultralytics/ultralytics#5153]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I want to print out the values of Flops, parameters, inference time of each layers the trained model like in the table, how can i do that? thank you,,,
![image](https://github.com/ultralytics/ultralytics/assets/94813960/f2b60183-540b-472a-9f4a-431f7d8db7b5)
![image](https://github.com/ultralytics/ultralytics/assets/94813960/9446aaff-996f-4cfd-a423-778ac48fbbd9)

**Comment by glenn-jocher** [comment]
@AndywithCV hello,

It's great to see you're interested in assessing the performance of each layer in your trained model. 

For a breakdown of Flops and parameters for each module, you can utilize the model.summary() function in PyTorch. This will provide you with a comprehensive list of all the layers alongside their corresponding parameter count and memory usage. Unfortunately, it does not feature FLOPs computations out of the box.

On the other hand, to measure the inference time you can use the time module in Python. By calling time functions before and after the inference function of your model, you can calculate the inference time for each layer.

Remember to run these measures appropriately for your use case, batching your measures to reduce noise and to accurate reflect the inference times you would see in a production environment.

Let me know if you need further clarifications.

Best regards,
Glenn

**Comment by glenn-jocher** [comment]
@AndywithCV hello,

Sorry for the confusion, YOLOv8 in its current form doesn't have a built-in summary method.

The PyTorch's model.summary() method is generally provided in some high-level API libraries for PyTorch models (like torchvision, torchsummary, etc.), but is not included in the primary nn.Module class, which is the parent class for Ultralytics models. That explains why you're getting an 'AttributeError: 'YOLO' object has no attribute 'summary'' error message when you try to call model.summary() on your model.

For an overview of the model architecture, you can utilize torchsummary (an external library) or create a custom function to provide details on the parameters, shapes and potentially even compute FLOPs, although this can be quite involved due to the dynamic nature of some models.

For measuring inference time, you can still use Python's built-in time module and make calls before and after the model inference call, which will provide a rudimentary way to measure inference time for the entire model.

I hope this clarifies the issue. Let me know if you have more questions.

Best regards,
Glenn

**Comment by AndywithCV** [comment]
> @AndywithCV hello,
> 
> Sorry for the confusion, YOLOv8 in its current form doesn't have a built-in summary method.
> 
> The PyTorch's model.summary() method is generally provided in some high-level API libraries for PyTorch models (like torchvision, torchsummary, etc.), but is not included in the primary nn.Module class, which is the parent class for Ultralytics models. That explains why you're getting an 'AttributeError: 'YOLO' object has no attribute 'summary'' error message when you try to call model.summary() on your model.
> 
> For an overview of the model architecture, you can utilize torchsummary (an external library) or create a custom function to provide details on the parameters, shapes and potentially even compute FLOPs, although this can be quite involved due to the dynamic nature of some models.
> 
> For measuring inference time, you can still use Python's built-in time module and make calls before and after the model inference call, which will provide a rudimentary way to measure inference time for the entire model.
> 
> I hope this clarifies the issue. Let me know if you have more questions.
> 
> Best regards, Glenn

Hello Jocher, thank you so much for your support, but i am not able to use torch summary to print out my model's info.
I tried install torch summary and run it with "summary = torchsummary.summary(model, (3, 224, 224))", but it returns error like below:
 File "main_benchmark2.py", line 31, in <module>
    summary = torchsummary.summary(model, (3, 224, 224))
  File "/opt/conda/envs/yolov8benchmark/lib/python3.8/site-packages/torchsummary/torchsummary.py", line 72, in summary
    model(*x)
  File "/root/data/andy/yolov8benchmark/ultralytics/ultralytics/engine/model.py", line 96, in __call__
    return self.predict(source, stream, **kwargs)
  File "/root/data/andy/yolov8benchmark/ultralytics/ultralytics/engine/model.py", line 236, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/root/data/andy/yolov8benchmark/ultralytics/ultralytics/engine/predictor.py", line 194, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/opt/conda/envs/yolov8benchmark/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/data/andy/yolov8benchmark/ultralytics/ultralytics/engine/predictor.py", line 237, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "/root/data/andy/yolov8benchmark/ultralytics/ultralytics/nn/autobackend.py", line 465, in warmup
    self.forward(im)  # warmup
  File "/root/data/andy/yolov8benchmark/ultralytics/ultralytics/nn/autobackend.py", line 333, in forward
    y = self.model(im, augment=augment, visualize=visualize) if augment or visualize else self.model(im)
  File "/opt/conda/envs/yolov8benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/root/data/andy/yolov8benchmark/ultralytics/ultralytics/nn/tasks.py", line 48, in forward
    return self.predict(x, *args, **kwargs)
  File "/root/data/andy/yolov8benchmark/ultralytics/ultralytics/nn/tasks.py", line 65, in predict
    return self._predict_once(x, profile, visualize)
  File "/root/data/andy/yolov8benchmark/ultralytics/ultralytics/nn/tasks.py", line 85, in _predict_once
    x = m(x)  # run
  File "/opt/conda/envs/yolov8benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1547, in _call_impl
    hook_result = hook(self, args, result)
  File "/opt/conda/envs/yolov8benchmark/lib/python3.8/site-packages/torchsummary/torchsummary.py", line 19, in hook
    summary[m_key]["input_shape"] = list(input[0].size())
AttributeError: 'list' object has no attribute 'size'

Please help me on that

**Comment by glenn-jocher** [comment]
@AndywithCV hello, 

It seems like you're encountering some difficulties with using torchsummary on your YOLOv8 model. When using torchsummary, it requires a fixed input size (you specified (3, 224, 224)). However, in the case of YOLOv8, the model expects an input of variable size, and it seems like the model you're using is returning a list of tensors instead of a single tensor, which results in the error that you're seeing.

An alternative suggestion for obtaining model information such as the number of parameters, you might manually go through each module in your model, and for each module, iterate through its parameters with the named_parameters() method. For each Parameter object returned by this method, call numel() to get the number of elements, and sum these up for the total number of parameters.

As for the inference time, Python's built-in time module can be used, as mentioned before. By writing a loop over your dataset, you can time your forward passes and then calculate the average. Please note that, the first iteration through the model could take significantly longer than subsequent iterations due to the CUDA initialization overhead, you might want to run a warm-up step before timing the forward passes.

In terms of Flops, computing them manually for a model might be a challenging task considering that the Flops can depend on the exact operations used in each layer, which could vary a lot from model to model. 

Hope it helps and let us know if you have more questions.

Best,
Glenn

**Comment by Lishumuzixin** [comment]
> @AndywithCV hello,
> 
> It seems like you're encountering some difficulties with using torchsummary on your YOLOv8 model. When using torchsummary, it requires a fixed input size (you specified (3, 224, 224)). However, in the case of YOLOv8, the model expects an input of variable size, and it seems like the model you're using is returning a list of tensors instead of a single tensor, which results in the error that you're seeing.
> 
> An alternative suggestion for obtaining model information such as the number of parameters, you might manually go through each module in your model, and for each module, iterate through its parameters with the named_parameters() method. For each Parameter object returned by this method, call numel() to get the number of elements, and sum these up for the total number of parameters.
> 
> As for the inference time, Python's built-in time module can be used, as mentioned before. By writing a loop over your dataset, you can time your forward passes and then calculate the average. Please note that, the first iteration through the model could take significantly longer than subsequent iterations due to the CUDA initialization overhead, you might want to run a warm-up step before timing the forward passes.
> 
> In terms of Flops, computing them manually for a model might be a challenging task considering that the Flops can depend on the exact operations used in each layer, which could vary a lot from model to model.
> 
> Hope it helps and let us know if you have more questions.
> 
> Best, Glenn

Hello, where can I find the information in the picture? I need this information.
![image](https://github.com/ultralytics/ultralytics/assets/68452249/470fa81e-ef02-4a02-8101-c3c6f34d2d57)

**Comment by glenn-jocher** [comment]
@Lishumuzixin hello,

The image you're referring to appears to be a screenshot of a detailed model summary which includes information about the layers, output shapes, parameters, and more. It might come from a tool or feature provided by a specific machine learning library or toolset.

The YOLOv8 model natively does not have a built-in .summary() function, therefore it does not directly produce a summary like in your attached picture. 

However, you can obtain similar information by iterating over the modules and parameters of the YOLOv8 model using PyTorch functionality. This can give you a count of the parameters in each layer, as well as the total number of parameters.

As for the inference time, try to use Python's built-in time module, write a loop over your data, and time your forward passes to calculate the average time for inference.

Keep in mind that obtaining Flops manually for a model can be complex, as the Flops can vary considerably depending on the operations used in each layer.

I hope this helps to clear up the issue!

Best,
Glenn

**Comment by Lishumuzixin** [comment]
> @Lishumuzixin hello,
> 
> The image you're referring to appears to be a screenshot of a detailed model summary which includes information about the layers, output shapes, parameters, and more. It might come from a tool or feature provided by a specific machine learning library or toolset.
> 
> The YOLOv8 model natively does not have a built-in .summary() function, therefore it does not directly produce a summary like in your attached picture.
> 
> However, you can obtain similar information by iterating over the modules and parameters of the YOLOv8 model using PyTorch functionality. This can give you a count of the parameters in each layer, as well as the total number of parameters.
> 
> As for the inference time, try to use Python's built-in time module, write a loop over your data, and time your forward passes to calculate the average time for inference.
> 
> Keep in mind that obtaining Flops manually for a model can be complex, as the Flops can vary considerably depending on the operations used in each layer.
> 
> I hope this helps to clear up the issue!
> 
> Best, Glenn

Thank you for your answer. I actually want to get a summary of the model validation. But how do I get this information?

**Comment by glenn-jocher** [comment]
Hi @Lishumuzixin, 

Thank you for your clarification. To obtain a summary of model validation, you would need to run the YOLOv8 model on a dataset and evaluate the performance based on the actual outcomes vs model's predictions.

Here's a brief process on how to do that:

1. Load your validation dataset.
2. Pass the data through the model to get predicted outputs.
3. Apply the loss function to the predicted outputs and the actual outcomes. Keep track of these calculated losses after each epoch. 

This will give you the validation loss, which is an important metric to check if your model is learning well.

In addition to validation loss, you can calculate other metrics such as Precision, Recall, and F1 Score. These metrics can help you further understand the model's performance.

Please make sure that your validation dataset never overlaps with your training dataset to avoid learning artefacts.

Note that this process is general and might differ slightly based on your specific needs.

I hope this helps and you're able to successfully gather the validation information you seek.

Best, 
Glenn
