### ISSUE TITLE
How to run model.val() and model.info on a specific GPU?

### ISSUE THREAD

**Issue by AndywithCV** [ultralytics/ultralytics#5157]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello team,

I am trying to validate the trained model on our Linux server, but I cannot specify the GPU device (like device = 0, 1 or something like when we do the training like model.train(data="/root/data.yaml", epochs = 400, batch = 16, device = 3 for example)) ), for model.val() it always goes with the GPU 0 which is always in use already, then there is not enough Vram to run the validation, I want to specify to a different GPU but dont know how to specify it? please help...

results = model.val()
model.info()

Our GPU 0 is always in used already
![image](https://github.com/ultralytics/ultralytics/assets/94813960/b13296cb-dab3-4a6d-8cf6-a1601eaf8507)

I tried this syntax: 
model = YOLO("/root/data/best.pt", device = 2)
results = model.val()
model.info()

then I got 
![image](https://github.com/ultralytics/ultralytics/assets/94813960/c5caa0ba-6d4e-4ec2-b54d-def65da0a369)

**Comment by glenn-jocher** [comment]
@AndywithCV run `model.val(device=2)`. See https://docs.ultralytics.com/modes/val/#arguments
