### ISSUE TITLE
How to export YOLOv8 to a .pt format?

### ISSUE THREAD

**Issue by Maya084** [ultralytics/ultralytics#5163]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there a way to export a loaded model to a `.pt` file? The docs imply that for this format there is no argument in the `export()` function but the default is `torchscript`. 

![image](https://github.com/ultralytics/ultralytics/assets/37115588/bd5b03d4-8c7e-443c-a80a-e95e8c164c66)
![image](https://github.com/ultralytics/ultralytics/assets/37115588/3e6ade95-7779-4dc7-85bd-c67c8b573a08)

I have loaded a model, changed the names of the classes and now I want to export it to a `.pt` format to use in the same way without retraining.

**Comment by glenn-jocher** [comment]
@Maya084 hello,

Firstly, I appreciate your efforts in searching before asking.

You can use PyTorch's native torch.save() to save your changed model. After loading and modifying the YOLOv8 model class names, all you have to do is call `torch.save(model, 'model.pt')`, where `model` is your modified model.

This will save it in PyTorch's .pt format. You can reload the model later on for inferencing or additional training using `torch.load('model.pt')`.

Please note that the Ultralytics `export()` function is designed specifically to convert models into more universal or deployment-friendly formats like ONNX or TorchScript, which are better suited for integration into other platforms and languages. For use within PyTorch itself, the native torch.save() function is sufficient. 

Remember, saving and loading models this way preserves the entire model, including both the architecture and the trained parameters.

Let us know if you need further assistance. Happy coding!
