### ISSUE TITLE
Extract name of result

### ISSUE THREAD

**Issue by pt2241701** [ultralytics/ultralytics#5177]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to extract name of object when detecting, i want to add name of object to work with them

**Comment by glenn-jocher** [comment]
@pt2241701 thank you for reaching out with your question!

When you run object detection with YOLOv8, the model returns a list of detection results. Each detection is a dictionary containing various details about the detected object, like the coordinates of the bounding box, the confidence score, and the class of the object.

The "class" field will give you the numerical class ID of the object. However, you likely want the name of the class (like "person", "car", etc.), not just the ID.

To convert from class IDs to class names, you can use the class names stored in the .names file used by your model. This file contains a list of class names in the same order that the classes are numbered. Simply use the class ID as an index into this list to get the class name.

Here's a notional walk through:

- Locate the detection result you're interested in.
- Locate the 'class' field in the detection result.
- Use the value in the 'class' field to index into the class names from the .names file.

Following this process will give you the name of the detected object. You can then use this name in the rest of your application as required.
