### ISSUE TITLE
How to disable output on screen

### ISSUE THREAD

**Issue by shersoni610** [ultralytics/ultralytics#518]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I am using Yolov8 for detection purpose. The code prints messages as follows. Is there a way to suppress
these for messages?

YOLOv8n summary: 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
Ultralytics YOLOv8.0.5 🚀 Python-3.8.12 torch-1.13.1 CPU
Fusing layers...
image 1/1 /Users/csverma/Projects/CompVis/YOLO/yolov8/frame910.png: 384x640 1 traffic light, 168.0ms
Speed: 1.5ms pre-process, 168.0ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 640)
YOLOv8n summary: 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

### Additional

Nothing

**Comment by AyushExel** [comment]
For cli:
```
yolo... verbose=False
```
for python it is false by default.

**Comment by glenbenson** [comment]
I have the same issue running from Python. I get _U**ltralytics YOLOv8.0.23  Python-3.9.16 torch-1.13.1+cpu CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs**_ etc etc
This remains in the screen output regardless of the verbose setting for me.
I can parse it out, but would be nice to set a flag "show/dontshow":)

**Comment by Natriumpikant** [comment]
Same for me.

The verbose flag deactivates the following infos:
`image 1/1 /home/hans/src/input/bus.jpg: 768x1024 2 persons, 1 bus, 1497.4ms
Speed: 14.9ms preprocess, 1497.4ms inference, 4.8ms postprocess per image at shape (1, 3, 1024, 1024)
Results saved to /home/hans/src/predict`

But nevertheless the screen message always appears:
`Ultralytics YOLOv8.0.43 🚀 Python-3.9.2 torch-1.13.1 CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs`

**Comment by hectorgarciatorres** [comment]
same

**Comment by s-m-asjad** [comment]
1) Go to your conda environment or wherever you have installed the ultralytics dependency/ pip package.

2) Go to yolo > engine > predictor.py

3) Replace the code with the code below

`# Ultralytics YOLO 🚀, GPL-3.0 license
"""
Run prediction on images, videos, directories, globs, YouTube, webcam, streams, etc.

Usage - sources:
    $ yolo mode=predict model=yolov8n.pt --source 0                               # webcam
                                                  img.jpg                         # image
                                                  vid.mp4                         # video
                                                  screen                          # screenshot
                                                  path/                           # directory
                                                  list.txt                        # list of images
                                                  list.streams                    # list of streams
                                                  'path/*.jpg'                    # glob
                                                  'https://youtu.be/Zgi9g1ksQHc'  # YouTube
                                                  'rtsp://example.com/media.mp4'  # RTSP, RTMP, HTTP stream

Usage - formats:
    $ yolo mode=predict model=yolov8n.pt                 # PyTorch
                              yolov8n.torchscript        # TorchScript
                              yolov8n.onnx               # ONNX Runtime or OpenCV DNN with dnn=True
                              yolov8n_openvino_model     # OpenVINO
                              yolov8n.engine             # TensorRT
                              yolov8n.mlmodel            # CoreML (macOS-only)
                              yolov8n_saved_model        # TensorFlow SavedModel
                              yolov8n.pb                 # TensorFlow GraphDef
                              yolov8n.tflite             # TensorFlow Lite
                              yolov8n_edgetpu.tflite     # TensorFlow Edge TPU
                              yolov8n_paddle_model       # PaddlePaddle
"""
import platform
from collections import defaultdict
from pathlib import Path

import cv2

from ultralytics.nn.autobackend import AutoBackend
from ultralytics.yolo.cfg import get_cfg
from ultralytics.yolo.data import load_inference_source
from ultralytics.yolo.data.augment import classify_transforms
from ultralytics.yolo.utils import DEFAULT_CFG, LOGGER, SETTINGS, callbacks, colorstr, ops
from ultralytics.yolo.utils.checks import check_imgsz, check_imshow
from ultralytics.yolo.utils.files import increment_path
from ultralytics.yolo.utils.torch_utils import select_device, smart_inference_mode


class BasePredictor:
    """
    BasePredictor

    A base class for creating predictors.

    Attributes:
        args (SimpleNamespace): Configuration for the predictor.
        save_dir (Path): Directory to save results.
        done_setup (bool): Whether the predictor has finished setup.
        model (nn.Module): Model used for prediction.
        data (dict): Data configuration.
        device (torch.device): Device used for prediction.
        dataset (Dataset): Dataset used for prediction.
        vid_path (str): Path to video file.
        vid_writer (cv2.VideoWriter): Video writer for saving video output.
        annotator (Annotator): Annotator used for prediction.
        data_path (str): Path to data.
    """

    def __init__(self, cfg=DEFAULT_CFG, overrides=None):
        """
        Initializes the BasePredictor class.

        Args:
            cfg (str, optional): Path to a configuration file. Defaults to DEFAULT_CFG.
            overrides (dict, optional): Configuration overrides. Defaults to None.
        """
        self.args = get_cfg(cfg, overrides)
        project = self.args.project or Path(SETTINGS['runs_dir']) / self.args.task
        name = self.args.name or f'{self.args.mode}'
        self.save_dir = increment_path(Path(project) / name, exist_ok=self.args.exist_ok)
        if self.args.conf is None:
            self.args.conf = 0.25  # default conf=0.25
        self.done_warmup = False
        if self.args.show:
            self.args.show = check_imshow(warn=True)

        # Usable if setup is done
        self.model = None
        self.data = self.args.data  # data_dict
        self.imgsz = None
        self.device = None
        self.dataset = None
        self.vid_path, self.vid_writer = None, None
        self.annotator = None
        self.data_path = None
        self.source_type = None
        self.batch = None
        self.callbacks = defaultdict(list, callbacks.default_callbacks)  # add callbacks
        callbacks.add_integration_callbacks(self)

    def preprocess(self, img):
        pass

    def get_annotator(self, img):
        raise NotImplementedError('get_annotator function needs to be implemented')

    def write_results(self, results, batch, print_string):
        raise NotImplementedError('print_results function needs to be implemented')

    def postprocess(self, preds, img, orig_img):
        return preds

    def __call__(self, source=None, model=None, stream=False):
        if stream:
            return self.stream_inference(source, model)
        else:
            return list(self.stream_inference(source, model))  # merge list of Result into one

    def predict_cli(self, source=None, model=None):
        # Method used for CLI prediction. It uses always generator as outputs as not required by CLI mode
        gen = self.stream_inference(source, model)
        for _ in gen:  # running CLI inference without accumulating any outputs (do not modify)
            pass

    def setup_source(self, source):
        self.imgsz = check_imgsz(self.args.imgsz, stride=self.model.stride, min_dim=2)  # check image size
        if self.args.task == 'classify':
            transforms = getattr(self.model.model, 'transforms', classify_transforms(self.imgsz[0]))
        else:  # predict, segment
            transforms = None
        self.dataset = load_inference_source(source=source,
                                             transforms=transforms,
                                             imgsz=self.imgsz,
                                             vid_stride=self.args.vid_stride,
                                             stride=self.model.stride,
                                             auto=self.model.pt)
        self.source_type = self.dataset.source_type
        self.vid_path, self.vid_writer = [None] * self.dataset.bs, [None] * self.dataset.bs

    @smart_inference_mode()
    def stream_inference(self, source=None, model=None):
        if self.args.verbose:
            #LOGGER.info('')
            donothing = True

        # setup model
        if not self.model:
            self.setup_model(model)
        # setup source every time predict is called
        self.setup_source(source if source is not None else self.args.source)

        # check if save_dir/ label file exists
        if self.args.save or self.args.save_txt:
            (self.save_dir / 'labels' if self.args.save_txt else self.save_dir).mkdir(parents=True, exist_ok=True)
        # warmup model
        if not self.done_warmup:
            self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
            self.done_warmup = True

        self.seen, self.windows, self.dt, self.batch = 0, [], (ops.Profile(), ops.Profile(), ops.Profile()), None
        self.run_callbacks('on_predict_start')
        for batch in self.dataset:
            self.run_callbacks('on_predict_batch_start')
            self.batch = batch
            path, im, im0s, vid_cap, s = batch
            visualize = increment_path(self.save_dir / Path(path).stem, mkdir=True) if self.args.visualize else False

            # preprocess
            with self.dt[0]:
                im = self.preprocess(im)
                if len(im.shape) == 3:
                    im = im[None]  # expand for batch dim

            # inference
            with self.dt[1]:
                preds = self.model(im, augment=self.args.augment, visualize=visualize)

            # postprocess
            with self.dt[2]:
                self.results = self.postprocess(preds, im, im0s)
            self.run_callbacks('on_predict_postprocess_end')

            # visualize, save, write results
            n = len(im)
            for i in range(n):
                self.results[i].speed = {
                    'preprocess': self.dt[0].dt * 1E3 / n,
                    'inference': self.dt[1].dt * 1E3 / n,
                    'postprocess': self.dt[2].dt * 1E3 / n}
                if self.source_type.tensor:  # skip write, show and plot operations if input is raw tensor
                    continue
                p, im0 = (path[i], im0s[i].copy()) if self.source_type.webcam or self.source_type.from_img \
                    else (path, im0s.copy())
                p = Path(p)

                if self.args.verbose or self.args.save or self.args.save_txt or self.args.show:
                    s += self.write_results(i, self.results, (p, im, im0))

                if self.args.show:
                    self.show(p)

                if self.args.save:
                    self.save_preds(vid_cap, i, str(self.save_dir / p.name))
            self.run_callbacks('on_predict_batch_end')
            yield from self.results

            # Print time (inference-only)
            if self.args.verbose:
                #LOGGER.info(f'{s}{self.dt[1].dt * 1E3:.1f}ms')
                donothing = True

        # Release assets
        if isinstance(self.vid_writer[-1], cv2.VideoWriter):
            self.vid_writer[-1].release()  # release final video writer

        # Print results
        if self.args.verbose and self.seen:
            t = tuple(x.t / self.seen * 1E3 for x in self.dt)  # speeds per image
            # LOGGER.info(f'Speed: %.1fms preprocess, %.1fms inference, %.1fms postprocess per image at shape '
            #             f'{(1, 3, *self.imgsz)}' % t)
        if self.args.save or self.args.save_txt or self.args.save_crop:
            nl = len(list(self.save_dir.glob('labels/*.txt')))  # number of labels
            s = f"\n{nl} label{'s' * (nl > 1)} saved to {self.save_dir / 'labels'}" if self.args.save_txt else ''
            LOGGER.info(f"Results saved to {colorstr('bold', self.save_dir)}{s}")

        self.run_callbacks('on_predict_end')

    def setup_model(self, model, verbose=True):
        device = select_device(self.args.device, verbose=verbose)
        model = model or self.args.model
        self.args.half &= device.type != 'cpu'  # half precision only supported on CUDA
        self.model = AutoBackend(model,
                                 device=device,
                                 dnn=self.args.dnn,
                                 data=self.args.data,
                                 fp16=self.args.half,
                                 verbose=verbose)
        self.device = device
        self.model.eval()

    def show(self, p):
        im0 = self.annotator.result()
        if platform.system() == 'Linux' and p not in self.windows:
            self.windows.append(p)
            cv2.namedWindow(str(p), cv2.WINDOW_NORMAL | cv2.WINDOW_KEEPRATIO)  # allow window resize (Linux)
            cv2.resizeWindow(str(p), im0.shape[1], im0.shape[0])
        cv2.imshow(str(p), im0)
        cv2.waitKey(500 if self.batch[4].startswith('image') else 1)  # 1 millisecond

    def save_preds(self, vid_cap, idx, save_path):
        im0 = self.annotator.result()
        # save imgs
        if self.dataset.mode == 'image':
            cv2.imwrite(save_path, im0)
        else:  # 'video' or 'stream'
            if self.vid_path[idx] != save_path:  # new video
                self.vid_path[idx] = save_path
                if isinstance(self.vid_writer[idx], cv2.VideoWriter):
                    self.vid_writer[idx].release()  # release previous video writer
                if vid_cap:  # video
                    fps = int(vid_cap.get(cv2.CAP_PROP_FPS))  # integer required, floats produce error in MP4 codec
                    w = int(vid_cap.get(cv2.CAP_PROP_FRAME_WIDTH))
                    h = int(vid_cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
                else:  # stream
                    fps, w, h = 30, im0.shape[1], im0.shape[0]
                save_path = str(Path(save_path).with_suffix('.mp4'))  # force *.mp4 suffix on results videos
                self.vid_writer[idx] = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc(*'mp4v'), fps, (w, h))
            self.vid_writer[idx].write(im0)

    def run_callbacks(self, event: str):
        for callback in self.callbacks.get(event, []):
            callback(self)
`

**Comment by s-m-asjad** [comment]
1) Go to your conda environment or wherever you have installed the ultralytics dependency/ pip package.

2) Go to yolo > engine > predictor.py

3) Replace the code with the code below

[predictor.zip](https://github.com/ultralytics/ultralytics/files/10984912/predictor.zip)

**Comment by nico00** [comment]
Try with:
`results = model(inputs, verbose=False)`

**Comment by glenn-jocher** [comment]
You can disable ALL YOLO output by setting environment variable `YOLO_VERBOSE=False`

**Comment by dnhuan** [comment]
The issue persists. I tried using both `YOLO_VERBOSE=False` and `verbose=False` but I still got the model summary.

Ultralytics YOLOv8.0.20 🚀 Python-3.8.15 torch-1.13.1 CPU, MacOS 12.5

**Comment by glenn-jocher** [comment]
@dnhuan in that case, you can modify the `models/common.py` file, and in the `check_requirements()` function, replace `verbose=True` to `verbose=False` to turn off the model summary. 

However, it is recommended to keep the model summary as it provides the user with some essential information about the model like the number of layers, parameters, and GFLOPs, so they can have an idea of how powerful the model is.

**Comment by Sakamaki-Izayoi** [comment]
Try set `verbose=False` on both `torch_utils.select_device` & `torch_utils.model_info` can hide extra console output which isn't controlled by args.verbose.

**Comment by glenn-jocher** [comment]
@Sakamaki-Izayoi to suppress the additional console output, ensure you set `verbose=False` in both `torch_utils.select_device` and `torch_utils.model_info` within your Python code. This should help in reducing the output that is not controlled by the `verbose` argument in the model's methods.

**Comment by ES-Hector** [comment]
`export YOLO_VERBOSE=False` works for me.

**Comment by glenn-jocher** [comment]
@ES-Hector glad to hear `export YOLO_VERBOSE=False` worked for you! 😊 If you run into any other issues or have more questions, feel free to reach out. Happy detecting with YOLOv8! 🚀

**Comment by goodevile** [comment]
in `./ultralytics/ultralytics/utils/__init__.py` you can set the global verbose to `False` manually:

`VERBOSE = str(os.getenv("YOLO_VERBOSE", True)).lower() == "False"  # global verbose mode`

**Comment by ghnikien** [comment]
hello, is it possible to input some code in an iPython notebook file (specifically inputting some code to a shell inside the IPYNB file) to remove these outputs? if so, what is the appropriate code? thanks

**Comment by glenn-jocher** [comment]
@ghnikien hello! 😊 Yes, you can control the verbosity directly in your iPython notebook. To suppress the output, you can set the `YOLO_VERBOSE` environment variable right within your notebook before importing or initializing your YOLO model. Here's how you can do it:

```python
import os

# Set YOLOv8 to quiet mode
os.environ['YOLO_VERBOSE'] = 'False'

# Now you can import and use your model without the extra logging
from ultralytics import YOLO
model = YOLO('yolov8n.pt', verbose=False)  # Make sure to use verbose=False here as well
```

This should help keep your notebook output clean and focused on your specific outputs. Happy coding!

**Comment by ghnikien** [comment]
TypeError: YOLO.__init__() got an unexpected keyword argument 'verbose'

Hello, this is the error I encountered while I input the line = YOLO ('yolov8n.pt', verbose = False) in my iPython Notebook. Do you have any idea how to fix this error? Thank you!

**Comment by glenn-jocher** [comment]
@ghnikien hello! 😊 It looks like you encountered an issue because the `YOLO` class initialization doesn't expect a `verbose` argument directly. To suppress verbose output, you can set the `YOLO_VERBOSE` environment variable before loading your model. Here’s how you can adjust your code:

```python
import os
from ultralytics import YOLO

# Set YOLO to quiet mode
os.environ['YOLO_VERBOSE'] = 'False'

# Load your model
model = YOLO('best.pt')  # You can use 'best.pt' here
```

This will help you load your custom trained model `'best.pt'` quietly in your iPython Notebook. Let us know if you need further assistance! Happy coding! 🚀

**Comment by ghnikien** [comment]
Hi! The code seems to be working now as I utilize the iPython Notebook, however, I really want my model size to be less than 10MB so that it will be more lightweight. As of now, my model size is 21MB. Do you have any idea how to significantly reduce the model size? Thank you!

**Comment by dnhuan** [comment]
Please create a separate thread for new problems

**Comment by glenn-jocher** [comment]
@dnhuan hi there! 👋 Reducing your model size can be quite effective for deployment. One approach is to use model pruning and quantization. Pruning removes less important parameters, and quantization reduces the precision of the numbers used to represent model parameters. You might also consider retraining with a smaller architecture. 

Here's a quick example of applying quantization with PyTorch:

```python
import torch
model = torch.load('best.pt')
model_quantized = torch.quantization.quantize_dynamic(model, {torch.nn.Linear}, dtype=torch.qint8)
torch.save(model_quantized, 'best_quantized.pt')
```

Remember to thoroughly test your quantized model to ensure its performance remains acceptable for your needs. Hope this helps! 😊

**Comment by ghnikien** [comment]
Hi! I am able to run this code, however, it did not significantly decrease the file size of my model, only reducing by just a few hundred kilobytes. Aside from quantization, do you have any idea to reduce significantly the model file size? Thank you.

**Comment by ghnikien** [comment]
Hi! I've tried to prune as well the code, however, it still generated the same model file size. Would the dataset file size be the ultimate sole reason now behind the size of generated model? Or do you have any idea what another ways of reducing the 'best.pt' file size aside from these? Thanks

**Comment by Ssangam1999** [comment]
import os
import cv2
import shutil
from ultralytics import YOLO
from ultralytics.utils.plotting import Annotator, colors

# Load the YOLO model
model = YOLO("best.pt")
names = model.names

# Read the image
im0 = cv2.imread('/LateBlight02.jpg')

# Create a directory for cropped images if it doesn't exist
crop_dir_name = "img_crop"
if not os.path.exists(crop_dir_name):
    os.mkdir(crop_dir_name)

# Perform prediction
results = model.predict(im0,show=False)
boxes = results[0].boxes.xyxy.cpu().tolist()
clss = results[0].boxes.cls.cpu().tolist()
confidences = results[0].boxes.conf.cpu().tolist()

# Combine boxes, classes, and confidences into a single list of tuples
combined = list(zip(boxes, confidences))

# Sort the combined list by confidence scores in descending order
combined.sort(key=lambda x: x[1], reverse=True)

# Select the top 3 entries with the highest confidence scores
top_3 = combined[:3]
print(top_3)
Hello, I dont have to display the image. I only want to display bounding boxes. how can I do it ?
Although show=False it doesnt work. I also tried visualize = False. It didnt work either

**Comment by johnpayne-gc** [comment]
> @ghnikien hello! 😊 It looks like you encountered an issue because the `YOLO` class initialization doesn't expect a `verbose` argument directly. To suppress verbose output, you can set the `YOLO_VERBOSE` environment variable before loading your model. Here’s how you can adjust your code:
> 
> ```python
> import os
> from ultralytics import YOLO
> 
> # Set YOLO to quiet mode
> os.environ['YOLO_VERBOSE'] = 'False'
> 
> # Load your model
> model = YOLO('best.pt')  # You can use 'best.pt' here
> ```
> 
> This will help you load your custom trained model `'best.pt'` quietly in your iPython Notebook. Let us know if you need further assistance! Happy coding! 🚀

Can we reopen this issue? This is a really dumb workaround for (what should be) a simple patch.

**Comment by pderrenger** [comment]
@goodevile thank you for your feedback. While the current workaround using the `YOLO_VERBOSE` environment variable is effective, we understand the desire for a more straightforward solution. We are continuously working on improving the library, and your input is valuable. If you encounter any further issues or have additional suggestions, please let us know.

**Comment by johnpayne-gc** [comment]
> reopen? why? I would rather let them work on Yolov10.
> 
> this is not broken. You can use what he said
> 
> ```
> # Set YOLO to quiet mode
> os.environ['YOLO_VERBOSE'] = 'False'
> ```

This is a hack, not a solution, and we shouldn't encourage "it works so who cares" mentality for obviously bad code. That being said, I understand if the ultralytics team is too busy to fix this, I can maybe find time to fix it myself, it just needs to be recognized as an issue.

**Comment by pderrenger** [comment]
@johnpayne-gc thank you for your feedback. We appreciate your perspective on the matter. While the current workaround is effective, we understand the need for a more integrated solution. We encourage contributions from the community, and if you have the time to address this, your efforts would be greatly valued. Please feel free to submit a pull request, and we will review it promptly. Your input helps us improve the library for everyone. Thank you for your understanding and support.

**Comment by dangkhoa1612** [comment]
> Try with: `results = model(inputs, verbose=False)`

thanks. it works for me

**Comment by glenn-jocher** [comment]
You're welcome! Glad it worked for you. If you have further questions, feel free to ask.

**Comment by ilmari99** [comment]
If you're unable to suppress inference output like this:  

```
0: 384x640 2 elephants, 3.6m  
Speed: 0.8ms preprocess, 3.6ms inference, 0.5ms postprocess per image at shape (1, 3, 384, 640)
```

using the methods mentioned above, please ensure that you set the following **before importing** `YOLO`:

```python
import os
os.environ['YOLO_VERBOSE'] = 'False'
from ultralytics import YOLO
```

⚠️ **Important:** The global `VERBOSE` variable is set in `ultralytics/utils/__init__.py` when something from `ultralytics` is imported. If `YOLO_VERBOSE` is not set beforehand, it may not take effect.

**Comment by glenn-jocher** [comment]
@ilmari99 thank you for sharing this important clarification! 🌟 For those needing to control YOLO verbosity, the recommended approach is indeed setting `YOLO_VERBOSE=False` before importing as shown. This aligns with the [Model configuration parameters](https://docs.ultralytics.com/reference/engine/model/#ultralytics.engine.model.Model) in our documentation. We appreciate community contributions that help improve implementation clarity for all users.

**Comment by dscherrenburg** [comment]
I would like to enable verbose for the training stage and disable it for the prediction stage. Unfortunately, as @ilmari99 correctly pointed out, it is only possible to call this `os.environ` workaround before the YOLO module is imported. This makes it impossible to change this `'YOLO_VERBOSE'` variable in between the train and predict stages. Has anyone found a workaround for this? Thanks in advance!

**Comment by idantene** [comment]
@dscherrenburg and for anyone else who still wants some clarity on this flow:
The way this works in Ultralytics is that they define verbosity at the top-level [here](https://github.com/ultralytics/ultralytics/blob/18fee3e7778af501bc69a34c21d768add20e2e43/ultralytics/utils/__init__.py#L43), so it's set immediately when you import anything from the ultralytics Python package, and also why you must set it as an environment variable prior to importing.

I'd say this is simply frustrating at best, potentially bad/non-standard at worst (e.g. seems like it could've easily been converted to e.g. a top-level function that actively reads the environment variable, allowing users to toggle it via the flag).

At any case, for the logger itself, this only affects the reported level of logs, as defined [here](https://github.com/ultralytics/ultralytics/blob/18fee3e7778af501bc69a34c21d768add20e2e43/ultralytics/utils/__init__.py#L534).
So, **tl;dr**, if you want to control the logging verbosity on-the-fly, you can do something like this:

```python
import logging
from ultralytics.utils import LOGGER as YOLO_LOGGER

YOLO_LOGGER.setLevel(logging.INFO)
# Do stuff with high verbosity
YOLO_LOGGER.setLevel(logging.ERROR)
# Do stuff with low verbosity
```
