### ISSUE TITLE
Exported ONNX not working in my application

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/ultralytics#5186]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello!

I have been using YoloR successfully for some time now, and would like to test yoloV8. I trained the network, and explorted it with this command:

    yolo export model="/media/cnnserver/Data/best.pt" format=onnx opset=12 imgsz=1280

In the application i am using the onnx file is not working, i do not get any detections. the trained network works great if tested on a dataset. I compared the two ONNX files in netron and noticed a few differences:

YoloR onnx:

![image](https://github.com/ultralytics/ultralytics/assets/67956327/53ebcec3-a6c5-4bfa-a6ca-bafaa0b219ff)

YoloV8 onnx:

![image](https://github.com/ultralytics/ultralytics/assets/67956327/40aa0655-9eb7-4e87-9adb-7c72f54b34d3)
![image](https://github.com/ultralytics/ultralytics/assets/67956327/47ee8565-2ae5-4382-9916-42486e3cdf15)

is there anything i can do to export the onnx file so it is compatibile with the old one? i do not have access to the source code where i am loading the onnx file, so my only chance is to work on the onnx file.

Any help is greatly appreciated.

Thank you

**Comment by MasIgor** [comment]
Thank you for your Feedback.

Yep the onnx file works as expected since i can run inference on it and it detects everything.. unfortunately i already exported it matching opset and image size, but without luck. I understand that at this point the problem is out of your area of operation, and will try to get the source code of the program somehow. Thank you anyway for taking the time to answer and explain!

**Comment by glenn-jocher** [comment]
@MasIgor hi there, thanks for your response.

You're correct in your understanding that, based on the details provided, the ONNX export file from our YOLOv8 pipeline is working correctly. If it manages to perform inference and detects objects as expected in a controlled environment, we can be reasonably confident that the model and its exported version are functioning as intended.

That said, the compatibility issue you described appears to be rooted at the specific level of your application implementation. While I empathize with the challenges this presents, resolving integration issues with the specific application code falls outside the scope of our project’s responsibility.

I see that you are planning to obtain the source code for your application. This will likely be the most definitive way to identify and resolve the conflict, and I hope that works out for you. Even without access to the specific application, keep in mind that you can still experiment with the parameters for exporting the ONNX model, as minor differences in these settings might affect the model's compatibility with specific applications.

I hope this brings some clarity. And no problem at all, we're happy to help and clarify things where we can. I very much appreciate your understanding and patience as we discussed this! If you encounter any other issues or questions related to YOLOv8 in the future, don't hesitate to reach out. Best of luck with your continued work.

**Comment by MasIgor** [comment]
@glenn-jocher Thank you very much! I actually have one more question... With netron.app i can check the structure of the onnx file, but i am not able to understand how the values are stored in the result in the first place. 

the output shape is 1, 324, 33600. my model has 320 classes, so i was expecting 325 for the second value. isnt the box and confidence also stored there? For the old onnx it was 1, 102000, 325...

Is tehre a tool for me to check a output and understand where is what? thank you!

**Comment by glenn-jocher** [comment]
Hi @MasIgor, thanks for another great question!

Firstly, the number of output channels in YOLOv8 is defined as num_classes + 4 + 1, where num_classes signifies the number of different object categories (320 in your case), "4" denotes bounding box parameters (x, y, width, height), and the last "1" corresponds to the object confidence score. That is why you're expecting 320 + 4 + 1 = 325 output channels, like in your previous model.

However, in YOLOv8, an additional stride-aware detection scheme was introduced wherein the bounding box and class label predictions are stored separately. This is why the output shape of your ONNX model is (1, 324, 33600),.

You can use the ONNX helper function to view the model output details more specifically. Similarly, Netron can also be used to visualize the structure of the ONNX file as it serves as an interactive viewer for ONNX model files. With it, you can navigate through the graph to better understand the model's architecture and operators.

Hope this helps you! Do reach out if you have any more queries
