### ISSUE TITLE
Free Image Annotation Tool for Segmentation Model 

### ISSUE THREAD

**Issue by karankhatri13** [ultralytics/ultralytics#519]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Any Free Annotation tool apart from Roboflow ....!

**Comment by ryouchinsa** [comment]
Read this comment.
https://github.com/ultralytics/yolov5/issues/10621#issuecomment-1382230893

Labeling using an open source annotation tool Labelme, export to the COCO format, and convert to the YOLO format using the JSON2YOLO script.
https://github.com/wkentaro/labelme
https://github.com/ultralytics/JSON2YOLO

**Comment by pderrenger** [comment]
@ryouchinsa thank you for reaching out! Labelme and RectLabel are popular choices for image annotation. It's good to hear that you found a tool that works for you. Both tools enable users to export annotations to the COCO format, which can then be converted to the YOLO segmentation format using the appropriate script. Best of luck with your segmentation project! 🖼️

**Comment by ryouchinsa** [comment]
We updated our [general_json2yolo.py](https://github.com/ryouchinsa/Rectlabel-support/blob/master/general_json2yolo.py) script so that the RLE mask with holes can be converted to the YOLO segmentation format correctly.
https://github.com/ultralytics/ultralytics/issues/917#issuecomment-1821375321

**Comment by glenn-jocher** [comment]
@ryouchinsa that's excellent news! It sounds like you're making great progress. Having updated scripts that handle RLE masks with holes can significantly improve the workflow for segmentation tasks. The community often benefits from such contributions, so thanks for taking the time to refine the tools available for YOLOv8. Keep up the good work, and don't hesitate to reach out if you have any further questions or insights to share. Your efforts help drive the field forward! 🚀
