### ISSUE TITLE
Can I run the v8 trained model in the same way with the v5 validation code?

### ISSUE THREAD

**Issue by yellowjs0304** [ultralytics/ultralytics#5190]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, Thank you for steady update.

Can I run the v8 trained model in the same way with the v5 [validation code](https://github.com/ultralytics/yolov5/blob/master/val.py)?

I think in your YOLO class wrapping way, It seems complicated to understand, non-intuitive, and therefore difficult to apply.
Is there any similar example code or tutorial which are not using your wrapping class like previous v5 codes?

**Comment by RizwanMunawar** [comment]
Certainly, here's the response for your git query:

@yellowjs0304, yes, you can execute the YOLOv8-trained model for validation using the provided code snippet:

```
yolo detect val model=yolov8n.pt  # val official model
yolo detect val model=path/to/best.pt  # val custom model
```

For more detailed information, please refer to the [YOLOv8 Validation documentation](https://docs.ultralytics.com/tasks/detect/#val).

If you'd like to explore the implementation details of YOLOv8 validation, you can examine the code in the [YOLOv8 validation implementation](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/validator.py#L104). This will provide you with insights into how it's done.

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by yellowjs0304** [comment]
Thanks I'll try on.

**Comment by glenn-jocher** [comment]
@yellowjs0304 you're welcome! Feel free to test the validation with your YOLOv8 trained model. If you have any further questions or if anything is unclear during your process, don't hesitate to ask. Enjoy working with YOLOv8, and remember, we're here to assist you!
