### ISSUE TITLE
yolov8 model for tracking multiple streams

### ISSUE THREAD

**Issue by MrNeither** [ultralytics/ultralytics#5193]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello! Please tell me if I can use the yolov8 model for tracking multiple streams. I have a limited memory size on the video card, which is only enough for 1 yolov8 model. At the same time, I have 4 streams, each of which needs to be tracked. Is it possible to get the tracker itself from YOLO and tell it to use the same model? I process streams sequentially, that is, the inference call will also be called sequentially in one stream/process.

Thank you very much for any help in this

**Comment by RizwanMunawar** [comment]
Hello @MrNeither, we have already provided support for multi-stream object tracking. However, this feature was initially designed for video files. In a few hours, we will be introducing support for webcams, IP cameras, and external cameras. I recommend keeping an eye on the [Ultralytics Object Tracking Documentation](https://docs.ultralytics.com/modes/track/#multithreaded-tracking) for updates and detailed information.

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by MrNeither** [comment]
Thank you very much for the quick response!!!. Сould you please also tell, if I form a batch of 4 elements, how will the tracker work out? will each element in the batch be processed by the tracker independently? If yes, then I can form a batch of 4 streams and thus solve my problem

**Comment by RizwanMunawar** [comment]
@MrNeither, indeed, you have the option to stack a list of images and create trackers based on the number of images. However, for the detection part, you can run the same detector on four image tensors.

This approach should streamline your workflow, and it's worth noting that the tracking model won't consume excessive memory or processing time.

**Comment by MrNeither** [comment]
I understand, thank you very much!!

**Comment by glenn-jocher** [comment]
You're welcome, @MrNeither! I'm glad I could help. If you have any more questions or need further understanding about YOLOv8, don't hesitate to ask. We're here to assist you. Happy tracking!
