### ISSUE TITLE
When will a tag version of the code be released?

### ISSUE THREAD

**Issue by WangQvQ** [ultralytics/ultralytics#5209]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi there,

I'm interested in knowing when a tagged version of the code will be released.  

Thank you!

**Comment by glenn-jocher** [comment]
@WangQvQ hello,

Thanks for your interest in the YOLOv8 project. Currently, we are working diligently on refining and vetting the software's capabilities and functionalities. We understand the importance of tagged versions of the repo for reproducibility and version-specific developments.

Unfortunately, I cannot provide a definite timeline for when the tagged version will be released. It depends on various factors including but not limited to, the scale of changes introduced, testing time, and feedback from the community.

However, rest assured that we are committed to delivering high-quality, reliable software to all our users. The release will be communicated as soon as it's available. Please keep an eye on the repo's updates for any news about this.

Thank you for your patience and support for the YOLOv8 project.

Best,
Glenn
