### ISSUE TITLE
How to crop the detected object after training in yolov8?

### ISSUE THREAD

**Issue by HarishGuragol** [ultralytics/ultralytics#521]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to crop the detected object after training in yolov8? Can you please let me know the syntax what needs to be added in the command line

**Comment by Alimustoofaa** [comment]
you can try get boxes xyxy and then convert to numpy integer next crop image

``` result = model.predict(image)[0]
boxes = result.boxes.xyxy.to('cpu').numpy().astype(int)
confidences = result.boxes.conf.to('cpu').numpy().astype(float)
labels = result.boxes.cls.to('cpu').numpy().astype(int) 

for box, conf, label in zip(boxes, confidences, labels):
    x_min, y_min, x_max, y_max = box
    image_crop = image[y_min:y_max, x_min:x_max]
