### ISSUE TITLE
Discrepancy between `update` method and its Docstring in `metrics.py`

### ISSUE THREAD

**Issue by beyse** [ultralytics/ultralytics#5214]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Val

#### Summary:

There appears to be a mismatch between the docstring and the actual implementation of the `update` method in `metrics.py`. This inconsistency can lead to confusion or even subtle bugs.

##### Code in Question:

The `update` method in `metrics.py` has the following implementation:

```python
def update(self, results):
    """
    Args:
        results (tuple): A tuple of (p, r, ap, f1, ap_class)
    """
    self.p, self.r, self.f1, self.all_ap, self.ap_class_index = results
```

The docstring suggests that the method expects a tuple `(p, r, ap, f1, ap_class)`. However, the code unpacks it into `self.p, self.r, self.f1, self.all_ap, self.ap_class_index`, which does not align with the docstring. Notice how `f1` and `ap` appear to be in the wrong order.

##### Calling Code:

Further examination reveals that this `update` method is called within the `process` method as follows:

```python
results = ap_per_class(tp,
                       conf,
                       pred_cls,
                       target_cls,
                       plot=self.plot
                       save_dir=self.save_dir,
                       names=self.names,
                       on_plot=self.on_plot)[2:]
self.box.update(results)
```

The values for `results` come from `ap_per_class()` and start from the third element (`[2:]`), making `results` a subset of `(p, r, f1, ap, unique_classes.astype(int))`.

##### Return Values in `ap_per_class`:

The function `ap_per_class()` ends with:

```python
return tp, fp, p, r, f1, ap, unique_classes.astype(int)
```

#### Points of Concern:

1. There is a discrepancy between the docstring in the `update` method and the actual variables to which the values from `results` are being assigned.
2. The `process` method uses only a subset of the output from `ap_per_class()`, which may not be entirely clear for future maintainers or users.

#### Proposed Steps:

1. Update the `update` method's docstring to correctly reflect the tuple it actually expects.
2. Ensure that the `ap_per_class()` function's output aligns with how it is used in the `process` method.
3. Check all instances where the `update` method is called and ensure that they comply with the correct tuple format.

I hope this issue can be addressed promptly to enhance the code quality and maintainability.

### Environment

**Branch**: Current `main` as of today but I was using `ultralytics 8.0.119` when I first found the discrepancy.

The issue is present regardless of the hardware and operating system used.

### Minimal Reproducible Example

Navigate to `metrics.py` and examine the `update` method located around line 624:

```python
def update(self, results):
    """
    Args:
        results (tuple): A tuple of (p, r, ap, f1, ap_class)
    """
    self.p, self.r, self.f1, self.all_ap, self.ap_class_index = results
```

Also, examine the `process` method which calls `update` and is located around line 675:

```python
def process(self, tp, conf, pred_cls, target_cls):
    """Process predicted results for object detection and update metrics."""
    results = ap_per_class(tp,
                           conf,
                           pred_cls,
                           target_cls,
                           plot=True,
                           save_dir=self.save_dir,
                           names=self.names,
                           on_plot=self.on_plot)[2:]
    self.box.update(results)
```

And finally, the `ap_per_class` function that returns the tuple:

```python
return tp, fp, p, r, f1, ap, unique_classes.astype(int)
```

### Additional

The discrepancy between the code and the docstring may lead to confusion among developers who are trying to extend or maintain the codebase. It could also lead to subtle bugs in the future if the tuple format is misunderstood. Proper documentation is crucial for code maintainability and effective collaboration. I hope this issue could be prioritized to improve the code quality and documentation consistency.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@beyse thank you for your detailed and thorough bug report! Your attentiveness to our project's code quality and documentation consistency is much appreciated.

From your description, it indeed appears that there's a discrepancy between the docstring and the actual `update` method implementation. I agree with your proposed steps to address this issue:

1. We should correct the `update` method's docstring to match the actual tuple it expects. This will clarify the method usage for other developers.
2. It would be wise to re-evaluate the `ap_per_class()` function's output to align with how it's used in the `process` method. We want to make sure all parts work harmoniously to efficiently achieve the intended functionality.
3. Surveying all instances where the `update` method is called will ensure they all comply with the correct tuple format, further increasing code reliability.

Your valuable feedback will undoubtedly greatly contribute to the maintainability, efficiency, and ease-of-use of the YOLOv8 codebase. 

Since you've indicated your willingness to contribute by submitting a PR, I'd welcome your involvement. The updates you suggest are straight-forward and should be manageable to implement. This will provide an opportunity for you to directly impact our project's quality and give other developers an easier time understanding and using our code. 

Once again, thank you for your helpful contributions to the YOLOv8 community.

Best regards,
Glenn Jocher

**Comment by glenn-jocher** [comment]
@beyse great news 😃! Your original issue may now be resolved ✅ in PR #5233. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by beyse** [comment]
@glenn-jocher Thank you very much, Sir for considering these changes. I appreciate it.

**Comment by glenn-jocher** [comment]
You're welcome @beyse, and thank you for your diligent contribution. I truly appreciate your effort in identifying the discrepancy and suggesting improvements. It's through valuable contributions like yours that we can continue to improve the codebase. We look forward to your continued collaboration and feel free to report any issues or suggest additional enhancements you come across. Happy coding!
