### ISSUE TITLE
Python sdk image segmentation does not correspond to categories

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/ultralytics#522]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

PyTorch Hub

### Bug

@glenn-jocher @AyushExel 
I referred to the link https://docs.ultralytics.com/predict/ and found that `results.masks.segments` does not correspond to `results.boxes.cls`, in other words, the list of segmentation coordinates does not correspond to the detected category .

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@Zengyf-CVer hey it could be because of this line https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/engine/results.py#L260-L260 as the segments are calculated in reverse order. Can you please confirm this removing this fixes your issue and I'll make a PR to main? Thanks!

**Comment by Zengyf-CVer** [comment]
@AyushExel Through debugging, it is indeed caused by the reverse order of the image segmentation list.

**Comment by AyushExel** [comment]
@Zengyf-CVer okay we'll fix it

**Comment by AyushExel** [comment]
This should be fixed. Please let me know if it isnt

**Comment by Zengyf-CVer** [comment]
Fixed, thanks a lot.

**Comment by pderrenger** [comment]
@Zengyf-CVer you're welcome! If you have any more questions or run into any other issues, feel free to ask. Happy coding!
