### ISSUE TITLE
What is difference between validation data and test data?

### ISSUE THREAD

**Issue by srheomtear** [ultralytics/ultralytics#5222]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to perform object detection using YOLOv8 in Python. When I execute the following script①, it loads the validation (val) data, and metrics like mAP are calculated.
-------------------------------------------------------------------------------------------------------
① !yolo task=detect mode=train model=yolov8s.pt data={dataset.location}/data.yaml epochs=100 batch=32 plots=True
-------------------------------------------------------------------------------------------------------
I have learned that validation data is used to adjust hyperparameters. Here, is my understanding correct that I should adjust the number of epochs and batch size to increase mAP through repeated training?

Once I determine the appropriate hyperparameters with the validation data, I plan to end the training and evaluate the model with the test data. However, is it inappropriate to consider the final mAP (maximum value) obtained when adjusting hyperparameters with validation data as the accuracy of the model? From the process of splitting the data into train, validation, and test sets, I understand that the test data should also be used somewhere, but I don't fully grasp the difference between validation and test data.

I understand that the model evaluation must be done with the test data. However, when I execute the following script②, only a portion of the results from the above script is outputted. Since there is no argument like mode=test, I think I should evaluate the model with mode=val. But the default data used for evaluation seems to be the validation data. If I try to evaluate the model with the test data by inputting split=test, an error message like the one below is displayed. Should I input the directory of the test data in the val section of data.yaml? Or is my understanding wrong that mode=val is used to evaluate the model with test data? If that's the case, what is the purpose of the test data?
-------------------------------------------------------------------------------------------------------
② !yolo task=detect mode=val model={HOME}/runs/detect/train/weights/best.pt data={dataset.location}/data.yaml split=val
-------------------------------------------------------------------------------------------------------
/content/drive/MyDrive
'split' is not a valid YOLO argument. Similar arguments are ['simplify', 'plots'].

    YOLOv8 'yolo' CLI commands use the following syntax:

        yolo TASK MODE ARGS

        Where   TASK (optional) is one of [detect, segment, classify]
                MODE (required) is one of [train, val, predict, export]
                ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
                    See all ARGS at https://docs.ultralytics.com/cfg or with 'yolo cfg'

    1. Train a detection model for 10 epochs with an initial learning_rate of 0.01
        yolo detect train data=coco128.yaml model=yolov8n.pt epochs=10 lr0=0.01

    2. Predict a YouTube video using a pretrained segmentation model at image size 320:
        yolo segment predict model=yolov8n-seg.pt source='https://youtu.be/Zgi9g1ksQHc' imgsz=320

    3. Val a pretrained detection model at batch-size 1 and image size 640:
        yolo detect val model=yolov8n.pt data=coco128.yaml batch=1 imgsz=640

    4. Export a YOLOv8n classification model to ONNX format at image size 224 by 128 (no TASK required)
        yolo export model=yolov8n-cls.pt format=onnx imgsz=224,128

    5. Run special commands:
        yolo help
        yolo checks
        yolo version
        yolo settings
        yolo copy-cfg
        yolo cfg

    Docs: https://docs.ultralytics.com/cli
    Community: https://community.ultralytics.com
    GitHub: https://github.com/ultralytics/ultralytics
-------------------------------------------------------------------------------------------------------

**Comment by glenn-jocher** [comment]
@srheomtear the difference between validation and test data lies in their purpose and usage during the machine learning model design process. 

Validation data is used during the model training process to tune the parameters (hyperparameters) of the model, such as number of epochs, batch size, etc. It provides a way to assess the performance of the model during training allowing you to make adjustments. By evaluating your model's performance on the validation set, you can determine how well the model is learning and generalizing from the training data, adjust your learning rate, add regularization etc to prevent overfitting or underfitting.

Test data, on the other hand, is used after the model has been trained to evaluate how well the model will perform on unseen data. This is the final evaluation step before deploying a model for production use. The concept is to provide a final, unbiased estimate of the model's capacity to generalize to new data.

Regarding your issue with the 'split' argument not being recognized, it seems this might be due to a misunderstanding. The 'split' argument is not recognized as it's not a valid argument for the YOLOv8 CLI. If you want to evaluate your model with the test data, you should update the 'val' field in your dataset's YAML file to the location of your test data.

Your confusion might stem from the fact that in YOLOv8 'val' is used to refer to the data that the model is evaluated against which is traditionally the validation data. However, you can replace it with your test data for final evaluation. This is a common practice and will enable you to measure the performance of your model on unseen data, giving you a better idea of how it might perform when deployed.

**Comment by srheomtear** [comment]
@glenn-jocher

Thank you so much!!
I could understand.

**Comment by tjasmin111** [comment]
I have a question on the same line:
How can I evaluate the model on a test dataset? Is there a cli command for that? I want all possible metrics like map and F1, precision, recall as well.

**Comment by glenn-jocher** [comment]
@tjasmin111 sure, you can certainly evaluate your model on a test dataset. To do this, you would use the `test` command. This command will run an evaluation of your model on a specified dataset and will generate various evaluation metrics including precision, recall, F1 score, and mAP among others.

Please bear in mind that you will need to specify the location of your test data in the appropriate YAML file before running this command, and you may be required to alter the path in the `data` argument to point to this file.

This process will allow you to understand how well your model will likely perform on unseen real-world data, hence providing an estimation of its future performance. If you want to fine-tune your model further based on these results, you could adjust the parameters of your model, perhaps perform additional training, and then re-evaluate.

I hope this information is helpful to you! If you have any further questions, please don't hesitate to ask.

**Comment by tjasmin111** [comment]
Thanks. But how to run the test command? Is it mode=test? I didn't see test being in the list of modes. Only saw val.

**Comment by glenn-jocher** [comment]
@tjasmin111, in YOLOv8, testing on a dataset is achieved by using the 'val' mode with your test data path. To clarify, there isn't a separate 'test' mode in the command line interface. The 'val' mode is used to evaluate the model's performance against a specified dataset.

Based on your needs, you can switch the dataset path in the YAML file to point to your test data when you want to evaluate your model's performance on the test dataset. After changing the data path, run the 'val' mode again, this time it will consider your test dataset for evaluation and provide you with the metrics you're interested in, including the F1 score, precision, recall and mAP.

I hope this clears up any confusion! Please let me know if you have any further questions.

**Comment by fransachmadhw** [comment]
Hello @glenn-jocher, in your opinion, **_which way is better to evaluate the model performance between using validation set or using test set?_** When I do augmentation in Roboflow, there are train set, validation set, and test set. But, when I do mode val in YOLOv8, test set isn't used.

**Comment by glenn-jocher** [comment]
@fransachmadhw hello, 

When it comes to evaluating model performance, both validation and test sets play crucial roles but serve different purposes. 

The validation set is used during the model training process to fine-tune the model parameters (hyperparameters). It allows you to assess the performance of your model during training and make necessary adjustments. This helps in preventing overfitting or underfitting.

On the other hand, the test set is used after your model has been trained. It's an unbiased way to evaluate how well your model will perform on unseen data. This evaluation is important before deploying a model for production use as it provides a final estimate of the model's capacity to generalize to new data. 

In YOLOv8, testing and validation are conflated in the 'val' command, so if you want to test your model’s performance on unseen data, you would have to replace the validation set path in your data.yaml file with the test set path. Then, you run the 'val' mode with this updated data.yaml file. The output metrics will provide an evaluation of the model's performance on your test set.

Both validation during training and evaluation on the test set are essential for building a robust model. The validation set is crucial for tuning and the test set is used for the final performance check.

We highly recommend using both for comprehensive and effective evaluation of your model's performance.

**Comment by OmerAlpSahin** [comment]
Hello @glenn-jocher, I would like to ask you if we can assume that the 'val' mode in yolov8 is the same as the 'test,' then can we assume that the results of the validation right after the training are actually the test results? I'm asking that because I want to test my model with 30% of my data, but as long as I see in the issues part of the yolov8, there is not a specific 'test' mode, so that I will use the 'val' mode as 'test' mode. Is there anything else you'd be able to provide about the 'test' mode issue?

**Comment by glenn-jocher** [comment]
Hello there! 👋 You're correct in observing that YOLOv8 primarily uses a 'val' mode for both validation and testing purposes. While traditional ML workflows distinguish between validation (for tuning) and test sets (for final evaluation), YOLOv8 simplifies this into one mode.

To use 'val' mode as your 'test' mode effectively, point the data file (e.g., `data.yaml`) used in the 'val' command to your test dataset. This way, after training, you can get unbiased performance metrics on unseen data by running:

```bash
yolo detect val model=path/to/your/model.pt data=path/to/your/test_data.yaml
```

Make sure your test data is never used in training to maintain an unbiased evaluation. By doing so, you'll be assessing your model's generalization capability as you intended. There's currently no separate 'test' mode in YOLOv8, so using 'val' mode with your test data is the way to go! 

Hope this helps! Let me know if you have any more questions.

**Comment by DavidScanu** [comment]
@glenn-jocher Can you confirm that this line of Python would achieve an evaluation on my "test" images ? 

```
metrics = custom_model.val(split="test")
```

My dataset comes from Roboflow and have a single data.yaml file. 

```
train: ./train/images
val: ./valid/images
test: ./test/images

nc: 4
names: ['boat', 'cargo', 'cruise ship', 'sailboat']

roboflow:
  workspace: david-scanu-mfhtq
  project: aerial-views-of-boats
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/david-scanu-mfhtq/aerial-views-of-boats/dataset/1
```

**Comment by glenn-jocher** [comment]
Hey there! 👋 Yes, you've got it exactly right. Utilizing that snippet will evaluate your model on your "test" images, assuming your `data.yaml` is correctly set up with a "test" section as you've shown. The `plots=True` parameter will indeed save prediction and ground-truth images (like "val_batch0_pred.jpg" and "val_batch0_label.jpg") for your test set. Just make sure your `custom_model` and `data.yaml` are properly prepared for evaluation.

Here's a quick example again for clarity:
```python
metrics = custom_model.val(split="test", plots=True)
```

And your `data.yaml` looks properly set up based on your description. You're all good to go! 👍 If you have any other questions or need further clarification, feel free to ask. Happy evaluating!

**Comment by DIANSLEE** [comment]
If the model is evaluated using the 'val' dataset, does the model will leak information leading to a higher evaluation score (such as detect the object that the model should be missed, or higher mAP)? Because the 'val' dataset was used in training for hyperparameter variations?

**Comment by glenn-jocher** [comment]
Evaluating on the 'val' dataset can lead to optimistic scores if it influenced hyperparameter tuning. For unbiased results, use a separate test set not involved in training.

**Comment by hemanthmandava945** [comment]
i am using yolov8 for instance segmentation. i want to know whether pretrained yolo model can do instance segmentation on 2d lidar generated images. i inferenced yolov8 model on 50 lidar images and did a good job. i want evaluate model on lidar images.do i need to make another test data which i didnot used for inferencing and anotating data saving as test data to evaluate?
how can i get iou values or can i get images for it?

**Comment by glenn-jocher** [comment]
@hemanthmandava945 yes, to properly evaluate your YOLOv8 model on 2D LiDAR images, you should use a separate test dataset that was not used during training or inference. Annotate these test images appropriately and include them in a `data.yaml` file under the `test` section. Then, run `val` mode using this YAML file to evaluate the model and obtain metrics like IoU and mAP, as well as visualizations of predictions and ground truths.

**Comment by hemanthmandava945** [comment]
@glenn-jocher i had annotated the 22 lidar images and i want evaluate the pre trained model performances 
from ultralytics import YOLO
import os

# Initialize the YOLOv8 model for segmentation
model = YOLO("yolov8x-seg.pt")

# Path to  dataset
dataset = "/home/./././tesing-yolo-1/a.yaml" # Replace with the actual path to your dataset YAML

 # Folder with 50  test images # give 50 unseen images 
  # Folder with 50 unseen test images


# Evaluate the model on your dataset
results = model.val(
    data= dataset,      # Path to the dataset YAML (must include test set annotations)
    conf=0.25,              # Confidence threshold(lower the confidence higher it detects)
    iou=0.45,               # IoU threshold
    save_json=True,         # Save results in COCO JSON format
    device='cpu'            # Use GPU 0 (set to "cpu" if no GPU)
)

# Display results
print("Precision:", results.box.map50)
print("Recall:", results.box.map)

print("mAP@50:", results.box.map50)
print("mAP@50-95:", results.box.map)
i am encountering the following error:
FileNotFoundError: 
Dataset '/home/mandava/myenv/src/tesing-yolo-1/a.yaml' images not found ⚠️, missing path '/home/mandava/myenv/src/tesing-yolo-1/val/images'
Note dataset download directory is '/home/mandava/datasets'. You can update this in '/home/mandava/.config/Ultralytics/settings.json'
i had only included path for test data in yaml,you can find below:
test: ./test/images 
val: ../val/images 
train: ../train/images
can you help me to solve issue

**Comment by hemanthmandava945** [comment]
i dont included validaion data because i want to check the pre trained yolo model would be able to inference on ouster lidar 2d images. i had done inferencing on 100 images.

**Comment by glenn-jocher** [comment]
To evaluate the pretrained YOLO model on your test dataset without validation data, you can set up your `data.yaml` with only the `test` section and then run the `val` mode. This will evaluate the model on your test images and provide metrics like mAP and IoU. Ensure your `test` dataset is annotated properly.

**Comment by hemanthmandava945** [comment]
@glenn-jocher i am gettting the following error:
FileNotFoundError:
Dataset '/home/mandava/myenv/src/tesing-yolo-1/a.yaml' images not found ⚠️, missing path '/home/mandava/myenv/src/tesing-yolo-1/val/images'
Note dataset download directory is '/home/mandava/datasets'. You can update this in '/home/mandava/.config/Ultralytics/settings.json'
 i just created test set annotated it and provided coressponding path to test set.

**Comment by glenn-jocher** [comment]
The error indicates that the `val` path is missing in your `data.yaml`. Even if you're only using a test set, YOLOv8 expects a `val` key. You can set it to a placeholder path (e.g., an empty directory) to resolve the error. Update your `data.yaml` file as follows:

```yaml
train: ../train/images
val: ./empty_dir  # Placeholder for validation
test: ./test/images
```
