### ISSUE TITLE
Model.predict 

### ISSUE THREAD

**Issue by ChinmayBH** [ultralytics/ultralytics#5239]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can we use multiple labels to predict in the model.predict? How can we use it ? also model's predict function returns what sized list in response?

### Additional

YOLO v8 prediction

**Comment by RizwanMunawar** [comment]
Hey, @ChinmayBH, the `predict` function in `detect` provides several output values, including `bounding boxes`, `confidence scores`, `class names`, and `class IDs`. Here's an example of how to use it in Python:

```python
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('yolov8n.pt')

# Perform inference on an image
results = model('https://ultralytics.com/images/bus.jpg')

# Extract bounding boxes, class IDs, class names, and confidences
boxes = results[0].boxes.xyxy.tolist()
class_ids = results[0].boxes.cls.tolist()
class_names = results[0].names
confidences = results[0].boxes.conf.tolist()
```

You can use multiple labels to predict multiple classes in an image.

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by aarias-iballistix** [comment]
Is there a way to get the cofidence score specifically for a mask?

**Comment by glenn-jocher** [comment]
@aarias-iballistix yes, the `predict` function in YOLOv8 provides detailed output, including the confidence scores. When you use a model trained for instance segmentation tasks, the `predict` function outputs a list for each detected object in the image, and it includes the class ID, bounding box coordinates, and confidence scores.

The confidence score you're asking about specifically corresponds to the predicted mask. This score represents the model's confidence that the predicted mask correctly identifies the object in the image. It's calculated on the basis of the model's training and represents how likely the model thinks that this specific object is correctly identified and segmented.

Please note that the actual process may vary depending on the specifics of your implementation and the exact version of the model you're using. Make sure to refer to our API documentation and the comments in the code for more detailed guidance. 

I hope this reply clearly answers your question. If you have more questions, feel free to ask!
