### ISSUE TITLE
detect.py equivalent in yoloV8

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/ultralytics#5242]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I've made some tests with yolo V5 few months back, and it was nice to have the detect.py file to edit. i tried to make a custom version, where i modified the "run" function inside detect.py to write some custom text, to have a custom dataloader (gen-e camera) and return few more things i needed for my test. that worked great. 

I would like to make the same test now with yolo V8, but noticed that it works differently now. I call yolo instead of python and no script this time.. 

How would i get the raw results inside my python script to draw the rectangles on my own with yoloV8?
The best case scenario would be to avoid editing yolo files, so that updates are not affected by this.

Thank you 

best regards

**Comment by glenn-jocher** [comment]
@MasIgor i'm glad to hear that you found what you needed in our documentation, specifically on how to work with YOLOv8 directly from your Python scripts.

To get raw results in YOLOv8, you would generally want to use the model’s `predict()` function, which should return the raw prediction outputs. This can include the objectness scores, class probabilities, and bounding box parameters. As you mentioned, the ideal scenario is to avoid modifying the original codebase, and work with the model within your own scripts instead.

Regarding the custom functionalities you mentioned - like writing custom text and having a custom data loader - you might want to wrap the Ultralytics functions on your end.

For drawing rectangles on the image or video frames, you could use the bounding box parameters returned by the `predict()` function. 

Keep in mind that if you're using a custom data loader, you might have to adjust the inputs to the model accordingly. 

Remember the ultimate goal is to keep the Ultralytics codes untouched and to add your custom functions to your own scripts. Then, updates to YOLOv8 shouldn't affect your custom functionalities.

Let me know if you need any additional help. I'm here to assist you.

**Comment by wq247726404** [comment]
> Never mind.. found all i needed here:
> 
> https://docs.ultralytics.com/usage/python/

How was it solved

**Comment by glenn-jocher** [comment]
@wq247726404 great to hear you found what you needed in our documentation! If you have any more questions or need further assistance as you integrate YOLOv8 into your workflow, don't hesitate to reach out. Happy coding! 😊🚀
