### ISSUE TITLE
Distribution of images into folders according to class

### ISSUE THREAD

**Issue by HayoiGlich** [ultralytics/ultralytics#5243]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a folder in which images are stored, I need to sort them into other folders in accordance with the predicted classes in the model (class machine - the image is transferred to this folder.). How to doing this or how to get a class on predict model. I used result[0].names , but this is not work.

**Comment by glenn-jocher** [comment]
@HayoiGlich hello,

It seems like you are trying to sort and distribute images into respective folders corresponding to their predicted classes by the YOLOv8 model. 

The function `result[0].names` you've used wouldn't work as it is not intended to provide class predictions. The object 'result' is a class of 'yolov8.Detections' that contains predictions, and this class doesn't have a 'names' attribute.

What you should do is to make use of the object's 'pred' attribute which returns all predictions. Each prediction includes the bounding box and the class ID.

You iterate over the predictions and use each 'class_id' to determine the correct folder for the image. For each image, you classify it, obtain the ‘class_id’, and then move the image to the corresponding folder.

Remember to create those folders before the process and handle any exception that may arise if a prediction for a particular class doesn't exist.

I hope this response helps. If you have further questions or face any issues, please feel free to ask.

**Comment by HayoiGlich** [comment]
Can you show me an example of what it should look like?

**Comment by glenn-jocher** [comment]
@HayoiGlich,

Certainly, I can explain how the process should look. 

Once you've run your images through the model, the predictions you receive for each image will include a class_id. The class_id represents class predictions made by the YOLOv8 model. 

You would then need a mapping function that corresponds these class IDs to respective folders. For example, if class_id '0' refers to the class 'machine', when an image receives a class_id of '0' in prediction, you would move that image to the directory named 'machine'. 

You would need to repeat this process for each image in your initial folder. This involves:
1. Load the image
2. Predict the class using YOLOv8
3. Get the class_id from prediction
4. Move the image to its respective folder based on class_id 

By the end of this procedure, you should have all your images in the initial directory moved into folders named after their predicted classes. Each folder will contain images that YOLOv8 has predicted to belong to the class corresponding to that folder's name.

Please let me know if this answers your question, or if there's anything else you'd like to know.

**Comment by HayoiGlich** [comment]
How do this in python code? Sorry for stupid question.

**Comment by glenn-jocher** [comment]
@HayoiGlich no question is a stupid question, we're here to help! 

In general, what you can do is:
1. Loop through each image file in the directory using os.listdir or glob.
2. For each image, use YOLOv8 to predict the class. The predicted class can be found within YOLOv8's returned object.
3. Once you have the predicted class, use os.rename or shutil.move function to move your image from current directory to the directory named after the predicted class.

Remember to check if the target directory exists before moving the image. If it doesn't exist yet, you can use os.mkdir to create it.

Again, keep in mind the key parts you'd need are looping through images, predicting classes using YOLOv8, and moving files to appropriate directories in Python.

I hope this helps! If you have further questions please do not hesitate to ask.

**Comment by HayoiGlich** [comment]
Can you tell me what to fix here or delete altogether?
`from ultralytics import YOLO
import os
import shutil

model = YOLO("runs/classify/train/weights/best.pt")

image_dir = "new_images/"
results = model.predict(source=image_dir)

output_dirs = []
for i in range(27):
    output_dirs.append(f"sorters/{i}")

for directory in output_dirs:
    os.makedirs(directory, exist_ok=True)


files = os.listdir(image_dir)

for file in files:
    source_path = os.path.join(image_dir, file)
    for r in results:
        class_id = r.probs.top1
        if 0 <= class_id <= 27:
            
            target_directory_index = int(class_id * 1)

            
            if target_directory_index < 0:
                target_directory_index = 0
            elif target_directory_index >= 27:
                target_directory_index = 26

            target_directory = output_dirs[target_directory_index]

            
            target_path = os.path.join(target_directory, file)

            
            shutil.copyfile(source_path, target_path)
        else:
            print(f"Значение classes для файла {file} вне допустимого диапазона.")

print("Файлы перемещены в соответствующие каталоги.")`

**Comment by glenn-jocher** [comment]
@HayoiGlich in the script you’ve provided, you’re using the YOLOv8 model to classify images in your directory and organizing these images into folders based on their predicted classes. Your approach seems absolutely correct - you're making predictions on each image in the directory and then, based on the predicted class, placing these images inside respective folders. 

That said, there might be an issue with the way you're getting the class_id from predictions. As per the model, you will get an object of Detections class. I would suggest examining this object in more detail to understand its structure and to check how to extract the top-1 most probable class. 

Also, please take note that the code snippet provided above is making folders for classes from 0 to 26. If your classes IDs extend beyond this range or you have less than 27 classes you will need to adjust this accordingly. 

Hope this information is helpful and assists you in sorting out the image files based on their predicted classes.

**Comment by guhuajun** [comment]
Greetings,

It's true. 
I am a new comer in model training area. And I am playing nuscenes dataset these days.

Some findings:

1. After searching a lot, I found that I need one extra parent folder (test) to start the training: 
```
/opt/data/datasets/nuscenes-coco/train/test
[root@nfsserver test]# ls -lh
total 2.2M
drwxr-xr-x 2 nobody nobody 120K Nov 21 15:44 images
drwxr-xr-x 2 nobody nobody 120K Nov 21 15:45 labels
```
2. `data.yaml` and `cfg.yaml` is different. In the quick start guide,  the note is missing. Finally, I run `yolo copy-cfg` to generate the config file. The start the training with `yolo train cfg='config.yaml'`
https://docs.ultralytics.com/quickstart/#use-ultralytics-with-cli

3. Dataset preparation is important. We should make sure we have the right number of class (nc) when we only want to do some tests with a smaller set of images. And we should follow the format requirements.
https://roboflow.com/formats/yolov8-pytorch-txt

![image](https://github.com/ultralytics/ultralytics/assets/14121694/1e2545bd-599a-48ab-b0e7-e50c722edd5d)

Happy YoloV8ing!

> @HayoiGlich in the script you’ve provided, you’re using the YOLOv8 model to classify images in your directory and organizing these images into folders based on their predicted classes. Your approach seems absolutely correct - you're making predictions on each image in the directory and then, based on the predicted class, placing these images inside respective folders.
> 
> That said, there might be an issue with the way you're getting the class_id from predictions. As per the model, you will get an object of Detections class. I would suggest examining this object in more detail to understand its structure and to check how to extract the top-1 most probable class.
> 
> Also, please take note that the code snippet provided above is making folders for classes from 0 to 26. If your classes IDs extend beyond this range or you have less than 27 classes you will need to adjust this accordingly.
> 
> Hope this information is helpful and assists you in sorting out the image files based on their predicted classes.
