### ISSUE TITLE
Issues when trying to train on a multi-GPU device

### ISSUE THREAD

**Issue by SilverStarCoder** [ultralytics/ultralytics#5244]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When switching to a multi-GPU device, I encountered the following error: `RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.` I then added `distributed.init_process_group(backend='nccl') ` at the start of my notebook, but then this resulted in `RuntimeError: trying to initialize the default process group twice!`. for some reason. I think this was because my `device` parameter in the config file was still set as the default value (which I believe is 'None'. After manually changing this parameter according to my new GPU configuration, I no longer get any printout on my notebook during model training, and it seems to just hang.

This is what I have at the start of the notebook (since I have different cluster configurations I want to use, depending on the task):
 ```
import torch
import torchvision
import torch.distributed as distributed

num_gpus = torch.cuda.device_count()
if num_gpus > 1:
    #distributed.init_process_group(backend='nccl')
    device = list(range(num_gpus))
else:
    device = "0" if torch.cuda.is_available() else "cpu"
```

I then use 'device' to override the 'device' parameter in the config file. 

Before I could see output like this after running` model.trainer.train()` in a single GPU device:

![Capture_working](https://github.com/ultralytics/ultralytics/assets/141123187/5af55d79-3b27-448d-90bc-dd7ed545bc11)

Now all I see is this (no printout/indication what is happening):

![Capture_not_working](https://github.com/ultralytics/ultralytics/assets/141123187/aa2ffae8-9ecb-4ea5-a01d-ab0050b7bc88)

What could be the reason why this is not working with a mulit-GPU setup?
 

### Additional

GPU details of cluster
```
PyTorch version           2.0.1+cu118
Torchvision version       0.15.2+cu118
CUDA Available            True
CUDA version              11.8
CUDNN version             8700
Number of GPUs            2
GPU 0                     Tesla V100-PCIE-16GB
GPU 1                     Tesla V100-PCIE-16GB
Environment variables:
RANK                      0
WORLD_SIZE                1
```

All my attempts use the latest Ultralytics library version 😪

### Update

Now even with a single GPU device (i.e no multi-GPU), I now get the same error as before when I used a multi-GPU cluster:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File <command-2157645179311703>, line 2
      1 print("Starting Model training...")
----> 2 model.trainer.train()
      3 # Update model and cfg after training
      4 if RANK in (-1, 0):

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/ultralytics/engine/trainer.py:195, in BaseTrainer.train(self)
    192         ddp_cleanup(self, str(file))
    194 else:
--> 195     self._do_train(world_size)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/ultralytics/engine/trainer.py:293, in BaseTrainer._do_train(self, world_size)
    291 if world_size > 1:
    292     self._setup_ddp(world_size)
--> 293 self._setup_train(world_size)
    295 self.epoch_time = None
    296 self.epoch_time_start = time.time()

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/ultralytics/engine/trainer.py:258, in BaseTrainer._setup_train(self, world_size)
    256 # Dataloaders
    257 batch_size = self.batch_size // max(world_size, 1)
--> 258 self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
    259 if RANK in (-1, 0):
    260     self.test_loader = self.get_dataloader(self.testset, batch_size=batch_size * 2, rank=-1, mode='val')

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/ultralytics/models/yolo/detect/train.py:52, in DetectionTrainer.get_dataloader(self, dataset_path, batch_size, rank, mode)
     50     shuffle = False
     51 workers = self.args.workers if mode == 'train' else self.args.workers * 2
---> 52 return build_dataloader(dataset, batch_size, workers, shuffle, rank)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/ultralytics/data/build.py:98, in build_dataloader(dataset, batch, workers, shuffle, rank)
     96 nd = torch.cuda.device_count()  # number of CUDA devices
     97 nw = min([os.cpu_count() // max(nd, 1), batch if batch > 1 else 0, workers])  # number of workers
---> 98 sampler = None if rank == -1 else distributed.DistributedSampler(dataset, shuffle=shuffle)
     99 generator = torch.Generator()
    100 generator.manual_seed(6148914691236517205 + RANK)

File /databricks/python/lib/python3.10/site-packages/torch/utils/data/distributed.py:68, in DistributedSampler.__init__(self, dataset, num_replicas, rank, shuffle, seed, drop_last)
     66     if not dist.is_available():
     67         raise RuntimeError("Requires distributed package to be available")
---> 68     num_replicas = dist.get_world_size()
     69 if rank is None:
     70     if not dist.is_available():

File /databricks/python/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:1196, in get_world_size(group)
   1193 if _rank_not_in_group(group):
   1194     return -1
-> 1196 return _get_group_size(group)

File /databricks/python/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:576, in _get_group_size(group)
    572 """
    573 Helper that gets a given group's world size.
    574 """
    575 if group is GroupMember.WORLD or group is None:
--> 576     default_pg = _get_default_group()
    577     return default_pg.size()
    578 return group.size()

File /databricks/python/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:707, in _get_default_group()
    703 """
    704 Getting the default process group created by init_process_group
    705 """
    706 if not is_initialized():
--> 707     raise RuntimeError(
    708         "Default process group has not been initialized, "
    709         "please make sure to call init_process_group."
    710     )
    711 return GroupMember.WORLD

RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```

GPU details for this cluster:
```
PyTorch version           2.0.1+cu118
Torchvision version       0.15.2+cu118
CUDA Available            True
CUDA version              11.8
CUDNN version             8700
Number of GPUs            1
GPU 0                     NVIDIA A100 80GB PCIe
Environment variables:
RANK                      0
WORLD_SIZE                1
```

**Comment by glenn-jocher** [comment]
@SilverStarCoder hello,

Thank you for your detailed explanation and we're sorry to hear that you're having difficulties. Based on your description, it seems that your issue may be occurring due to one or both of the following considerations:

1. **Initialization of Distributed Data Parallel (DDP) Context** - The errors suggest that there is an issue with the initialization of your DDP context. In PyTorch, proper initialization of the DDP context is important when working with multiple GPUs. It seems that you are trying to implement the initialization of the process group manually. You might not need to explicitly initialize this and it could be handled internally by the `model.trainer.train()` function in YOLOv8. Your efforts to manually initialize it may actually be leading to some of the issues you're experiencing.

2. **Device Configuration** - The switch from using a single GPU to multiple GPUs would entail changing the 'device' parameter, which appears to be correct in your code. However, again it might be the case that the YOLOv8 library is designed to automatically manage these details internally, and manually overriding these settings might be causing issues.

For both considerations, a good approach would be to revisit the documentation or examples provided with the YOLOv8 library, specifically focused on running it with multiple GPUs. You should be able to train your model without having to manually initialize the DDP context or specify the device list. If you're still encountering issues after trying this, please provide us an update so we can assist further.

And regarding the last RuntimeError which also appears on a single GPU, it appears that the error is related to Distributed Data Parallel process as well. This is strange, as a single GPU setup should not need to invoke DDP functionalities. Perhaps some settings were mistakenly not reset after your multi-GPU tries. You might want to ensure that all the DDP related parts of your code are not being invoked when you try to run the training on a single GPU.

I hope this helps and all the best in your model training!

**Comment by SilverStarCoder** [comment]
> @SilverStarCoder hello,
> 
> Thank you for your detailed explanation and we're sorry to hear that you're having difficulties. Based on your description, it seems that your issue may be occurring due to one or both of the following considerations:
> 
> 1. **Initialization of Distributed Data Parallel (DDP) Context** - The errors suggest that there is an issue with the initialization of your DDP context. In PyTorch, proper initialization of the DDP context is important when working with multiple GPUs. It seems that you are trying to implement the initialization of the process group manually. You might not need to explicitly initialize this and it could be handled internally by the `model.trainer.train()` function in YOLOv8. Your efforts to manually initialize it may actually be leading to some of the issues you're experiencing.
> 2. **Device Configuration** - The switch from using a single GPU to multiple GPUs would entail changing the 'device' parameter, which appears to be correct in your code. However, again it might be the case that the YOLOv8 library is designed to automatically manage these details internally, and manually overriding these settings might be causing issues.
> 
> For both considerations, a good approach would be to revisit the documentation or examples provided with the YOLOv8 library, specifically focused on running it with multiple GPUs. You should be able to train your model without having to manually initialize the DDP context or specify the device list. If you're still encountering issues after trying this, please provide us an update so we can assist further.
> 
> And regarding the last RuntimeError which also appears on a single GPU, it appears that the error is related to Distributed Data Parallel process as well. This is strange, as a single GPU setup should not need to invoke DDP functionalities. Perhaps some settings were mistakenly not reset after your multi-GPU tries. You might want to ensure that all the DDP related parts of your code are not being invoked when you try to run the training on a single GPU.
> 
> I hope this helps and all the best in your model training!

Hi @glenn-jocher , thank you for the reply.  I don't see a section on the documentation specifically related to multi-GPU training: I have read issues/questions related to it [here](https://github.com/ultralytics/ultralytics/issues/3308)  and [here](https://github.com/ultralytics/ultralytics/issues/3838). I can see from the yaml configuration file that a device parameter is available: `device:  # (int | str | list, optional) device to run on, i.e. cuda device=0 or device=0,1,2,3 or device=cpu`. I can see from the code that it its default value is None, which means that it either specifies cpu or device '0' if a GPU is available. So this has to be set to do multi-GPU training. I suspect the issue has to do with package versions; I have downgraded my environment runtime, but still getting this error for a mulit-GPU cluster (single cluster is now working with downgraded torch and cuda versions):

```
"---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
File <command-642264254244848>:2
      1 print("Starting Model training...")
----> 2 model.trainer.train()

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/ultralytics/engine/trainer.py:190, in BaseTrainer.train(self)
    188     subprocess.run(cmd, check=True)
    189 except Exception as e:
--> 190     raise e
    191 finally:
    192     ddp_cleanup(self, str(file))

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/ultralytics/engine/trainer.py:188, in BaseTrainer.train(self)
    186 try:
    187     LOGGER.info(f'{colorstr("DDP:")} debug command {" ".join(cmd)}')
--> 188     subprocess.run(cmd, check=True)
    189 except Exception as e:
    190     raise e

File /usr/lib/python3.9/subprocess.py:528, in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    526     retcode = process.poll()
    527     if check and retcode:
--> 528         raise CalledProcessError(retcode, process.args,
    529                                  output=stdout, stderr=stderr)
    530 return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '['/local_disk0/.ephemeral_nfs/envs/pythonEnv-fbbac946-6382-4608-b36d-7f7034e2fe10/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '32821', '/databricks/python_shell/scripts/db_ipykernel_launcher.py']' returned non-zero exit status 1."
```
I am using the latest Ultralytics release: 8.0.194

**Comment by SilverStarCoder** [comment]
@glenn-jocher , I have verified that I am able to do multi-GPU training normally on the cluster, so doesn't this indicate that there is an issue with Ultralytics?:
```
import torch

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA version used by PyTorch: {torch.version.cuda}")
num_gpus = torch.cuda.device_count()
```

```
print(f"Number of GPUs available: {num_gpus}")

for i in range(num_gpus):
    print(f"GPU {i}: {torch.cuda.get_device_name(i)}")
```
    
`%sh nvidia-smi`

```
import torch
import torch.nn as nn

# Define a simple neural network
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.fc = nn.Linear(10, 10)

    def forward(self, x):
        # Print which GPU is used for this chunk of the input
        print(f"Forward pass on GPU: {x.device}")
        return self.fc(x)

# Check if CUDA (GPU support) is available
if torch.cuda.is_available():
    # Move the model to GPU and use DataParallel to utilize multiple GPUs
    model = SimpleNet().cuda()
    model = nn.DataParallel(model)

    # Generate some random input data
    input_data = torch.randn(32, 10).cuda()  # batch size of 32, 10 features

    # Forward pass
    output = model(input_data)
    print("Output shape:", output.shape)
else:
    print("CUDA is not available.")
```


I get the following output:

```
PyTorch version: 1.13.1+cu117
CUDA version used by PyTorch: 11.7
```
```
Number of GPUs available: 2
GPU 0: Tesla V100-PCIE-16GB
GPU 1: Tesla V100-PCIE-16GB
```
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000001:00:00.0 Off |                  Off |
| N/A   26C    P0    25W / 250W |      4MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  Off  | 00000002:00:00.0 Off |                  Off |
| N/A   25C    P0    24W / 250W |      4MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
```
Forward pass on GPU: cuda:0
Forward pass on GPU: cuda:1
Output shape: torch.Size([32, 10])
```

**Comment by SilverStarCoder** [comment]
@Laughing-q , will you be able to provide some insights on this issue? I still can't seem to get multi-gpu training to work.

**Comment by Laughing-q** [comment]
@SilverStarCoder well the logic behind DDP in ultralytics is to create a temporary file and launch ddp with this file in background, I suppose this workflow is not compatible with jupyter notebook for now I think(I haven't tested it with the notebook way but I've seen similar issues before). 
I recommend you to use command to launch ddp training, something like this:
```bash
yolo detect train model=yolov8n.pt device=0,1,2,3 data=...
```

**Comment by AI-noobie** [comment]
@SilverStarCoder  I also get "CalledProcessError" you mentioned in the comments, how did you solve this?

**Comment by glenn-jocher** [comment]
Hello @AI-noobie,

The "CalledProcessError" usually occurs when the subprocess that is being called from the main process encounters an error. The Ultralytics framework utilizes this approach for multi-GPU training where each GPU is treated as a separate subprocess using Python's DistributedDataParallel (DDP) mode.

For the YOLOv8 model, the most common reason for this error is incorrect CUDA device specification. Make sure you are specifying the CUDA devices correctly as per your system configuration.

Another common reason could be an issue with the CUDA version compatibility with PyTorch and your system. Please ensure your PyTorch version and CUDA version are compatible.

As for your data and model, ensure they are correctly configured and there aren't any inherent issues with them, such as incorrect file paths or unsupported formats.

I hope this helps. If the issue persists, please provide more specifics about your configuration and the exact error message for more clarified assistance.
