### ISSUE TITLE
Default process group has not been initialized - Issue with Azure databrics env, google colab works fine

### ISSUE THREAD

**Issue by metarun** [ultralytics/ultralytics#5247]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I am running this simplest toy example, just to make sure that my envs are setup properly.

```
!pip install -q ultralytics

import os
from ultralytics import YOLO
# Load model 
model = YOLO('yolov8m-cls.pt')
results = model.train(data='mnist160', epochs=1, imgsz=64)
```

This code works perfectly in google colab on GPU.
However as soon as I run the same code on Azure databrics, I get below error 

```
Ultralytics YOLOv8.0.193 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 16128MiB)
train: /Workspace/Users1234@456.com/image_poc/datasets/mnist160/train... found 80 images in 10 classes ✅ 
val: None...
test: /Workspace/Users/1234@456.com/image_poc/datasets/mnist160/test... found 80 images in 10 classes ✅ 
Overriding model.yaml nc=1000 with nc=10
YOLOv8m-cls summary: 141 layers, 15785146 parameters, 15785146 gradients, 41.9 GFLOPs
Transferred 228/230 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs/classify/train7', view at http://localhost:6006/
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to 'yolov8n.pt'...
100%|██████████| 6.23M/6.23M [00:00<00:00, 62.4MB/s]
/databricks/python/lib/python3.10/site-packages/torch/nn/modules/conv.py:459: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)
  return F.conv2d(input, weight, bias, self.stride,
AMP: checks passed ✅
train: Scanning /Workspace/Users/1234@456.com/image_poc/datasets/mnist160/train... 80 images, 0 corrupt: 100%|██████████| 80/80 [00:00<?, ?it/s]
**RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.**
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File <command-4013391729241841>, line 7
      5 # Load model 
      6 model = YOLO('yolov8m-cls.pt')
----> 7 results = model.train(data='mnist160', epochs=1, imgsz=64)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-a6cf08fc-1469-4cc3-91ee-1f1f115bb145/lib/python3.10/site-packages/ultralytics/engine/model.py:334, in Model.train(self, trainer, **kwargs)
    332     self.model = self.trainer.model
    333 self.trainer.hub_session = self.session  # attach optional HUB session
--> 334 self.trainer.train()
    335 # Update model and cfg after training
    336 if RANK in (-1, 0):

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-a6cf08fc-1469-4cc3-91ee-1f1f115bb145/lib/python3.10/site-packages/ultralytics/engine/trainer.py:195, in BaseTrainer.train(self)
    192         ddp_cleanup(self, str(file))
    194 else:
--> 195     self._do_train(world_size)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-a6cf08fc-1469-4cc3-91ee-1f1f115bb145/lib/python3.10/site-packages/ultralytics/engine/trainer.py:293, in BaseTrainer._do_train(self, world_size)
    291 if world_size > 1:
```

### Environment

```
OS macos 13.5.2 (22G91) 
env Azure databrics Jupyter noteboook
Databricks Runtime Version - Python 3.10.12, 14.1 ML Beta (includes Apache Spark 3.5.0, GPU, Scala 2.12)

```

### Minimal Reproducible Example

import os
from ultralytics import YOLO
# Load model 
model = YOLO('yolov8m-cls.pt')
results = model.train(data='mnist160', epochs=1, imgsz=64)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@metarun could you run `yolo checks` and paste the output here?

**Comment by metarun** [comment]
@glenn-jocher  yes, here it is. 

Ultralytics YOLOv8.0.194 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15110MiB)
Setup complete ✅ (4 CPUs, 22.5 GB RAM, 39.6/250.9 GB disk)

**Comment by glenn-jocher** [comment]
@metarun everything seems fine in your environment. How can I reproduce the same on Azure Databricks? Is there a quickstart tutorial to setting up an environment there? 

I've never used Azure or Databricks before.

**Comment by metarun** [comment]
You create a free trial account on azure, there databrics comes pre-installed. You just need to spin up databrics instance and use it. I can setup 10mins meeting and show you live if you want. reach2tarun@gmail.com is my email.

**Comment by glenn-jocher** [comment]
@metarun actually maybe you could help us update our AzureML quickstart. We have a Guide for it here but it was submitted by a user and I'm not sure if it's correct. It doesn't mention databricks anywhere either.
https://docs.ultralytics.com/guides/azureml-quickstart

Then everyone can get started better with Azure instead of just myself.

**Comment by glenn-jocher** [comment]
The exact error your seeing though seems to be because ultralytics is trying to start your training as a DDP training. This should only happen if you specifically request multiple GPUs, otherwise it should default to device=0 on a multi-GPU machine.

Very strange.

**Comment by Maxwell12345** [comment]
I'm experiencing the same exact errors. Is there a workaround?

**Comment by totogot** [comment]
likewise, this is causing a complete blocker in training all ultralytics models in Databricks. is there any possible solution @glenn-jocher?

**Comment by glenn-jocher** [comment]
@Maxwell12345, I'm sorry to hear that you're encountering this issue. We're working on a solution to make sure YOLOv8 works seamlessly on the Databricks environment. 

In the meantime, you could try manually setting the device to a specific GPU index. From the error message it seems the error is related to initiating DistributedDataParallel (DDP) training. 

If the issue persists, it would be beneficial if you could provide any additional information or specific steps you're taking when running Databricks. This could give us further insight into the issue and help us find a fix sooner.

We appreciate your patience and feedback as we work on resolving this.

**Comment by totogot** [comment]
@Maxwell12345 After looking around for a bit, I believe the following documentation provides an adequate workaround: https://docs.databricks.com/en/machine-learning/train-model/distributed-training/spark-pytorch-distributor.html

In effect, simply setting the backend before executing model.train seems to do the trick:
`
if torch.cuda.is_available():
  print('GPU available')
  device_type = 0
  dist.init_process_group('nccl')
else:
  print('No GPU available - using CPU')
  device_type = 'cpu'
  dist.init_process_group('gloo')

results = model.train(
    data = "/dbfs/mnt/<s3-bucket>/segmentation/configs/yolo_segmentation_demo.yaml",
    epochs = 20,
    project = "/Users/totogot@dummyuser.com/segmentation-runs", # output path root
    name = "YOLO_segmentation_run_1", # output folder = 'project + name'
    device = device_type
    )
`

@glenn-jocher , one thing which would be extremely useful to understand though is the logic that the train function uses for saving the outputs to drive. For example, in the above code I can read my configs and training images/txt files from a mounted s3 bucket, however, when I try to save to s3 by stating 'project = /dbfs/mnt/<s3-bucket>/segmentation/segmentation-runs' I get an error thrown: "RESOURCE_DOES_NOT_EXIST: Parent directory /dbfs/mnt/<s3-bucket>/segmentation"

It seems strange that it is able to read from the s3 path (therefore the parent directory evidently does exist), but runs into issues when trying to write? As a result, the project output path stated above points to my Databrick file structure within the workspace, which works but in many cases is sub-optimal as I'd like to read and write directly to the mounted cloud storage

**Comment by glenn-jocher** [comment]
Hi @totogot,

Thanks for sharing your workaround with us. It's great to hear that initializing the backend allows you to execute `model.train`.

As for your question regarding the logic that the `train` function uses for saving the outputs, the function first checks for an existing output directory using the provided `project` and `name` arguments. If it doesn't exist, it attempts to create it. 

The error you encountered - "RESOURCE_DOES_NOT_EXIST: Parent directory /dbfs/mnt/example-s3-bucket/segmentation" - suggests that the function was not able to successfully create the directory at the specified path, even though it was able to read from it.

One possible reason could be that the S3 bucket permissions are set to read-only, which would explain why it can read but not write to it. I would recommend checking the bucket's permissions and making sure that they allow for write operations.

Regarding your question about saving model training outputs to S3, you're right that the current functionality is a result of its interaction with Databricks MLFlow and doesn't allow you to directly save outputs to S3. Unfortunately, overriding this default functionality isn't currently possible. However, this is an interesting point that we will take into consideration for future improvements. 

Again, thank you for your valuable feedback. If you have any further questions or encounter new issues, feel free to share them with us.

**Comment by Maxwell12345** [comment]
@totogot 
Thank you for the workaround! I'm going to try it out in my environment and will update if it is successful.

@glenn-jocher 
For reference, I've tried setting the device explicitly as well, however, this brings up great insight as I dive into how ultralytics can help with some research!

**Comment by Maxwell12345** [comment]
@totogot 
I used the workaround you suggested and it works perfectly!

Thank you :)

**Comment by glenn-jocher** [comment]
That's great to hear @Maxwell12345! We're glad that the suggested workaround was effective for your case. Understanding these various configurations will undoubtedly be valuable for users working on similar environments.

Your feedback and collaboration helps in the continuous improvement of YOLOv8 making it easier and more efficient for other users in the future. Thanks for sharing your experience!
