### ISSUE TITLE
Reset default path for models and data saving

### ISSUE THREAD

**Issue by IzhanVarsky** [ultralytics/ultralytics#5255]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello! I am sure that this question was asked, but I couldn't find it. I have a problem: the results of training or exporting models are saved not to the current project folder from which the scripts were called, but to completely different folders of other projects (where I also used yolov8). Where can I find and reset the settings responsible for such data paths?

**Comment by glenn-jocher** [comment]
@IzhanVarsky hi there,

Thanks for reaching out with your question. YOLOv8 does default to certain paths for saving models and data. These defaults are specified in the configuration files.

However, to direct the output to a specific directory, you can use the `--project` argument followed by your desired path when you call the train, export or any other YOLOv8 script from the command line. Please note that you'll need to substitute "your desired path" with the actual path where you want the results to be saved.

For resetting paths, it might be best to directly edit the related configuration files or arguments in your scripts to make sure the data stays in expected locations and is not scattered across various projects.

I hope this helps! Let us know if you have any more questions.

Best,
Glenn
