### ISSUE TITLE
Multi Edge-Tpu Support

### ISSUE THREAD

**Issue by yikang-shen** [ultralytics/ultralytics#5269]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi I have a device with multiple edge tpus. Does the tflite interpreter support specify which tpu to use? 
I usually use `pycoral.utils.edgetpu.make_interpreter(model_path,device,delegate)`(https://coral.ai/docs/reference/py/pycoral.utils/#module-pycoral.utils.edgetpu) to specify the device on usb or pci. Is it possible to add pycoral library for edgetpu inference with the device argument?  I'd like to implement this if it is okay to use the external pycoral library.

**Comment by glenn-jocher** [comment]
@yikang-shen hello,

Thank you for your query regarding multiple Edge-TPU support in our YOLOv8 repository.

While we're currently not equipped to specify Edge-TPUs for training purposes, the idea to incorporate the Coral `pycoral` library is an interesting direction. Doing so might help in routing the Edge-TPU model configuration to specific devices, especially when you have multiple TPUs.

We, however, advise cautiousness in adding new dependencies. Before implementing your idea of adding `pycoral` as an external library, it's recommended to consider potential compatibility issues, or how the usage of the library could alter the behavior of existing code.

We appreciate your contribution, and we're open to discuss any modifications that could enhance the functionality of our codebase. Please ensure you post your proposal via a Pull Request for us to properly review the changes.

Looking forward to your contribution!
