### ISSUE TITLE
YoloV8 Segmentation fault model.predict 

### ISSUE THREAD

**Issue by harith75** [ultralytics/ultralytics#5274]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Hello everyone. 

I decided to try yolov8 on my raspberry PI4 2 GB and followed the necessary step whom are : 
         -git clone the repository
         -pip install -r requirements.txt

I tested with a virtual environment with venv and then the classic linux env and got the same output. 

I try to reinstall my whole configuration (erase sd card then reinstall) thinking there was kind of a memory leak.
I increase the swap memory and the the gpu to. 
nothing works

the command line I used is : `yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'`

the output : 
```
Ultralytics YOLOv8.0.195 🚀 Python-3.9.2 torch-2.1.0 CPU (Cortex-A72)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

Found https://ultralytics.com/images/bus.jpg locally at bus.jpg
Segmentation fault
```

Thank you. 

### Environment

```
yolo checks
Ultralytics YOLOv8.0.195 🚀 Python-3.9.2 torch-2.1.0 CPU (Cortex-A72)
Setup complete ✅ (4 CPUs, 1.8 GB RAM, 7.1/29.0 GB disk)

OS                  Linux-6.1.21-v8+-aarch64-with-glibc2.31
Environment         Linux
Python              3.9.2
Install             pip
RAM                 1.76 GB
CPU                 Cortex-A72
CUDA                None

matplotlib          ✅ 3.8.0
numpy               ✅ 1.26.0
opencv-python       ✅ 4.8.1.78
pillow              ✅ 8.1.2
pyyaml              ✅ 6.0.1
requests            ✅ 2.25.1
scipy               ✅ 1.11.3
torch               ✅ 2.1.0
torchvision         ✅ 0.16.0
tqdm                ✅ 4.66.1
pandas              ✅ 2.1.1
seaborn             ✅ 0.13.0
psutil              ✅ 5.8.0
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238

```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@harith75 hi there,

Thank you for providing a comprehensive report of the issue you're experiencing. It seems like a segmentation fault issue is occurring during the prediction step on your Raspberry Pi setup.

Segmentation faults are usually related to accessing memory that the process doesn't have permission to, or trying to read/write from/to a portion of memory that doesn't exist.

Although YOLOv8 supports most environments, the potential incompatibility between the CPU (Cortex-A72) and some components of the model pipeline might be the primary issue here. The Raspberry Pi 4 CPU might not be sufficient to handle the load required by YOLOv8, causing it to attempt to allocate more memory than available which leads to a segmentation fault.

As much as we would like to support a large variety of hardware, ensuring compatibility with every possible setup is quite challenging. You might want to consider testing the model on a device with higher computational resources.

We'll continue to investigate this matter and update when we find a more concrete solution to this problem. Your patience is much appreciated.

**Comment by harith75** [comment]
Ok no problem, I do understand. 
But I have the same problem with yolov5. 
Anyway I'll try with tensorRT and a jetson nano. 
Thanks !

**Comment by glenn-jocher** [comment]
Thank you for your understanding, @harith75. 

Migrating to a more powerful system like the Jetson Nano should indeed help eliminate these issues. Its integrated GPU should be capable enough to handle the complex computations required for object detection models like YOLOv8. Additionally, optimizing the model with TensorRT will also significantly reduce the computational resources required without sacrificing accuracy. 

Please feel free to update us on your progress with TensorRT and the Jetson Nano, or if you encounter any other issues with YOLOv8. We are here to assist you. 

Thank you for your interest in our project and best of luck with your work!

**Comment by glenn-jocher** [comment]
@andrewaggb hello, thanks for reporting the issue.

Segmentation faults usually occur when a process attempts to access unavailable memory, or when trying to read/write a non-existent portion of memory. This can occur due to a number of reasons, including incompatibility issues, outdated/inaccurate model weights, or an error within the PyTorch environment, as you suggested. 

Given that you're experiencing similar issues across two YOLO models and even with different virtual environments, it does seem like the issues could be related to PyTorch rather than the YOLOv8 or the super-gradients library. While we strive to ensure our model works across various setups, the Raspberry Pi setup can be particularly challenging due to limited computational resources and potential compatibility concerns.

You might want to consider reinstalling PyTorch and making sure it's up-to-date, or potentially trying a different device that has greater computational resources. Until then, we will continue to investigate this matter and seek solutions to these kind of problems frequently faced by users.

Thanks for your patience and understanding.

**Comment by Natriumpikant** [comment]
Hello. 

I have the same problem after updating Ultralytics framework to the newest version. 

Before updating, everything worked fine. Now always a "segmentation fault".

**Comment by harith75** [comment]
> Hello.
> 
> I had the same problem after updating my Rasperry Pi 4B to the newest OS "Debian Bookworm".
> 
> After downgrading to "Debian Bullseye" yolo works fine again.

What is the version of pytorch and ultralytics you use ?

**Comment by glenn-jocher** [comment]
@Natriumpikant hello,

Thank you for reporting back your findings. It's interesting that the issue occurs with "Debian Bookworm", but resolves after downgrading to "Debian Bullseye". 

As for your question, it would be helpful if you could provide more details about the exact versions of both PyTorch and Ultralytics that you're using. You can check this by running `pip show torch` and `pip show ultralytics` in your command line, and it will display the version for each.

It could be that some compatibility issues between the newer version of the Debian OS and the versions of PyTorch and Ultralytics you're using are causing this issue. We will look into this matter. Thanks for your patience and understanding.

**Comment by Shu2023a** [comment]
Hello.

I'm trying yolov8 on a raspberry PI4B 4GB.

pip show ultralytics
Name: ultralytics
Version: 8.0.197

pip show torch
Name: torch
Version: 2.1.0

In this environment, the inference will eventually result in a segmentation fault.

pip uninstall torch torchvision
pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2

pip show torch
Name: torch
Version: 2.0.1

Then,
yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'
can be successfully inferred.

**Comment by Natriumpikant** [comment]
> Hello.
> 
> I'm trying yolov8 on a raspberry PI4B 4GB.
> 
> pip show ultralytics Name: ultralytics Version: 8.0.197
> 
> pip show torch Name: torch Version: 2.1.0
> 
> In this environment, the inference will eventually result in a segmentation fault.
> 
> pip uninstall torch torchvision pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2
> 
> pip show torch Name: torch Version: 2.0.1
> 
> Then, yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg' can be successfully inferred.

I can confirm this, after downgrading to  _pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2_ its working fine again, also on Debian Bookworm 64bit for Rasperry PI's.

**Comment by harith75** [comment]
Hello just tested, it works fine with the command line : `yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'`
thank you by the way I am using the version of pytorch, torchision that you are mentioning, but for yolo i have the  Version :8.0.196 and os : bulseye 64bits 

So it would mean that as @glenn-jocher said it is mostly related to torch rather than Yolo

**Comment by glenn-jocher** [comment]
@harith75 hello,

Thank you for confirming the change made to your environment has resolved your issue. It's valuable to have your confirmation that downgrading to PyTorch version 2.0.1 enabled successful execution of the model. 

As we initially suspected, it appears that the issue is not with YOLOv8, but rather an incompatibility between version 2.1.0 of PyTorch and your system. Indeed, the segmentation error was remedied by reverting to an older version of the PyTorch library.

This information will be useful for the developer community. We recommend users that encounter similar issues to consider downgrading the PyTorch version they are using.

We appreciate your update, as this might help others that run into the same problem.

**Comment by glenn-jocher** [comment]
@Natriumpikant hello, 

I'm glad to hear that the method worked for you! It's always great when we can find solutions that benefit multiple users. If you encounter any further issues or have more questions, please don't hesitate to reach out. Your feedback helps us to continuously improve the system. 

Happy coding!

**Comment by Mohammadakhavan75** [comment]
> pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2

This works for me also! Thank you.

**Comment by glenn-jocher** [comment]
@Mohammadakhavan75 hello,

I'm glad to hear that the solution worked for you too! Thanks for taking the time to share this. This information will surely benefit others who encounter a similar issue while working with YOLOv8.  Don't hesitate to reach out if you have more questions or if there's anything else we can assist you with. 

Happy coding!

**Comment by jenius-eagle** [comment]
I am running yolov5 on raspberry pi 4b 64 bit os.
followed instructions on here https://docs.ultralytics.com/guides/raspberry-pi/ to install yolov5... got segmentation fault 
then below
pip uninstall torch torchvision
pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2

pip show torch
Name: torch
Version: 2.0.1

no more segmentation fault...

Thanks for posting a solution!

**Comment by glenn-jocher** [comment]
@jenius-eagle hello, 

I'm glad to hear that you found a solution for the segmentation fault issue. Yes, downgrading Torch to version 2.0.1 seems to be a viable solution to this issue as it resolves the compatibility problem some users report while using YOLOv8 on Raspberry Pi models. This information is valuable to the community, and we appreciate your efforts to share it.

Should you have more queries or encounter any other issues, kindly let us know. We are here to assist you. 

Happy coding!

**Comment by glenn-jocher** [comment]
@belongtothenight hello,

I'm glad to hear that the solution worked perfectly for you! It's great to see our community finding and sharing solutions that help others effectively. Thank you for the feedback and contribution. If you encounter any further difficulties or have more questions, please don't hesitate to reach out.

Happy coding!

**Comment by drewjgray** [comment]
This does appear to be an issue with torch 2.1 and YOLOv8, I am getting the same seg fault on the Orin Nano. Downgrading to 2.0.1 fixes the issue for me as well.

**Comment by glenn-jocher** [comment]
@drewjgray hello,

Thank you for confirming the issue with torch 2.1 and YOLOv8 and sharing that downgrading to version 2.0.1 solved the problem. Your experience aligns with what others in the community have reported. It seems that there might be some compatibility issues between the latest version of PyTorch and some hardware configurations, causing a segmentation fault.

We appreciate you sharing your solution as this can help others facing a similar problem. We're always thankful to community members like yourself for helping continuously improve the usability and robustness of YOLOv8.

Happy coding!

**Comment by Jagatheeswariravi** [comment]
Facing this issue for long time.. Thanks for solving it

**Comment by vipinstechstack** [comment]
pip uninstall torch torchvision
pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2

This worked for me

**Comment by glenn-jocher** [comment]
@vipinstechstack I'm glad to hear that downgrading torch and torchvision versions has resolved your issue. It seems that there have been a few compatibility problems reported with the later versions of these libraries.

This makes your contribution very significant to the community. Understanding the solutions that have worked for others is often the best way to pinpoint the source of issues and prevent future ones.

Thank you for sharing and don't hesitate to reach out if you have any other questions or concerns.

Happy coding!

**Comment by Quant1766** [comment]
For orange pi 5 this work too.
pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2

**Comment by glenn-jocher** [comment]
@Quant1766 hello,

Thank you for confirming that the solution of downgrading torch and torchvision versions has also worked for your Orange Pi 5. The community greatly benefits from this shared knowledge as it provides context for different types of hardware configurations.

If you encounter any more issues or have further questions, please don't hesitate to reach out. 

Happy coding!

**Comment by BatmanofZuhandArrgh** [comment]
> Hello.
> 
> I'm trying yolov8 on a raspberry PI4B 4GB.
> 
> pip show ultralytics Name: ultralytics Version: 8.0.197
> 
> pip show torch Name: torch Version: 2.1.0
> 
> In this environment, the inference will eventually result in a segmentation fault.
> 
> pip uninstall torch torchvision pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2
> 
> pip show torch Name: torch Version: 2.0.1
> 
> Then, yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg' can be successfully inferred.

As person with similar set up and Debian Bookworm. I can confirm 2 things:
1. This solves the segmentation fault for me
2. You're the greatest person alive
I love solving a bug without knowing why it happened

**Comment by Shu2023a** [comment]
Hello,

I'm trying yolov8 on a raspberry PI4B 4GB.

With today's confirmation,
By using a virtual environment, in my environment, both Debian Bookworm and Debian Bulseye
Even with PyTorch version 2.1.1, in my environment, inference worked without segment faults by using a virtual environment.

(Example) yolo is any name
python3 -m venv yolo
source yolo/bin/activate

https://docs.ultralytics.com/guides/raspberry-pi/?h=raspberry+pi#initiate-tcp-stream-with-libcamera
Install it according to the steps below, and after restarting

Re-enter the virtual environment
source yolo/bin/activate

pip show ultralytics
Name: ultralytics
Version: 8.0.211

pip show torch
Name: torch
Version: 2.1.1

Then,
yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'
can be successfully inferred.

I thought there was a possibility of using a virtual environment other than downgrading PyTorch.

**Comment by Shu2023a** [comment]
Hello, I'm Shu2023a.

I made a comment about the virtual environment earlier,
raspberry PI4B 4GB + USBEdgeTPU (https://coral.ai/products/accelerator)
When using YOLOv8 with

I have not been able to get USBEdgeTPU to work in a virtual environment.

Therefore, when I use EdgeTPU, the OS is Debian Bullseye,
I am downgrading PyTorch=2.0.1 without using a virtual environment.

**Comment by glenn-jocher** [comment]
Hello @Shu2023a,

Thank you for the updates and for detailing your experiences with both using a virtual environment and trying to integrate with the USBEdgeTPU on a Raspberry Pi 4GB setup. Your contributions are invaluable and give insight into potential workarounds and solutions for various configurations.

It's interesting to note that the virtual environment solution allowed you to use PyTorch version 2.1.1 without segmentation faults on Debian Bookworm and Bullseye, while for USBEdgeTPU compatibility, you reverted to the downgrading approach without a virtual environment. The dichotomy of solutions provides an excellent reference for those experimenting with similar setups.

While virtual environments can offer isolation from the system Python and ease dependency management, they might not resolve all interoperability issues with external hardware accelerators like the Coral USB Edge TPU. These devices often require specific drivers and libraries that might need to be installed system-wide.

Thank you again for sharing your findings. Don't hesitate to keep the community informed with any new discoveries or questions you may have. Your hands-on experience is greatly beneficial for others who may be navigating similar challenges.

Happy experimenting! 🚀

**Comment by StreakingJerry** [comment]
> Hello.
> 
> I'm trying yolov8 on a raspberry PI4B 4GB.
> 
> pip show ultralytics Name: ultralytics Version: 8.0.197
> 
> pip show torch Name: torch Version: 2.1.0
> 
> In this environment, the inference will eventually result in a segmentation fault.
> 
> pip uninstall torch torchvision pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2
> 
> pip show torch Name: torch Version: 2.0.1
> 
> Then, yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg' can be successfully inferred.

Thank you so much! You save my day.

**Comment by glenn-jocher** [comment]
@StreakingJerry hello,

Fantastic to hear that downgrading to the specific versions of torch and torchvision resolved the segmentation fault issue for you! Your feedback is important, and it’s great to see the community helping each other out.

Happy to see you're up and running with YOLOv8! If you have any more questions or need further assistance in the future, feel free to ask.

Happy detecting! 🚀

**Comment by huyyxy** [comment]
> Hello. 你好。
> 
> I'm trying yolov8 on a raspberry PI4B 4GB.我正在树莓 PI8B 4GB 上尝试 yolov4。
> 
> pip show ultralytics pip 显示 ultralytics Name: ultralytics 常用中文名：ultralytics Version: 8.0.197 版本： 8.0.197
> 
> pip show torch pip 显示火炬 Name: torch 名称：火炬 Version: 2.1.0 版本： 2.1.0
> 
> In this environment, the inference will eventually result in a segmentation fault.在这种环境中，推理最终会导致分段错误。
> 
> pip uninstall torch torchvisionpip 卸载火炬 torchvision pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2pip 安装火炬==2.0.1 torchvision==0.15.2 torchaudio==2.0.2
> 
> pip show torch pip 显示火炬 Name: torch 名称：火炬 Version: 2.0.1 版本： 2.0.1
> 
> Then, 然后 yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'YOLO 预测模型=yolov8n.pt source=' https://ultralytics.com/images/bus.jpg' can be successfully inferred.可以成功推断。

Thanks! This method also works for me! my enviroment is aws ec2 p3.2xlarge 。AMI is Deep Learning AMI GPU PyTorch 1.13.1 (Amazon Linux 2) 20230818。Python 3.10.13, torch 2.1.2 。downgrading to the specific versions of torch and torchvision resolved the segmentation fault issue。

**Comment by glenn-jocher** [comment]
@huyyxy hello,

I'm glad to hear that downgrading the torch and torchvision versions resolved the segmentation fault issue on your AWS EC2 p3.2xlarge instance. It's always great to see the community finding and sharing solutions that work across different environments.

If you have any more questions or need further assistance, feel free to reach out.

Happy detecting with YOLOv8! 🚀

**Comment by ClarlieLuo** [comment]
Hello everyone,

I recently encountered the following issue after updating to the latest version of YOLOv8. My Ultralytics version is 8.1.4, Torch version is 2.0.1, torchvision version is 2.1.0, and Python version is 3.8.17.

If anyone has experienced a similar problem or has insights on how to resolve it, I would greatly appreciate your input

**Comment by Shu2023a** [comment]
Hello.

Today I went through the same steps again as before.

I'm trying yolov8 on a raspberry PI4B 4GB.
The OS is 64bit_Legacy Debian Bullseye from a clean install.
Python 3.9.2

https://docs.ultralytics.com/guides/raspberry-pi/?h=raspberry+pi#install-necessary-packages_1
Install by following the steps in

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get autoremove -y

pip3 install ultralytics

sudo reboot

pip show ultralytics
Name: ultralytics
Version: 8.1.4

pip show torch
Name: torch
Version: 2.1.2

An error occurs when running inference

pip uninstall torch torchvision
pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2

pip show torch
Name: torch
Version: 2.0.1

Then,
yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'
can be successfully inferred.

**Comment by ClarlieLuo** [comment]
@Shu2023a @glenn-jocher 
Thank you for your response,

I've identified the issue I'm facing when making predictions using a model trained on my own dataset. However, for the image with source='https://ultralytics.com/images/bus.jpg' and using model=yolov8n.pt, my environment successfully produces predictions.

Upon extensive research, it seems that the problem lies in the torch-cuda version being 11.8, while my GPU has CUDA version 12.2. Currently, I am still grappling with how to downgrade the GPU version to the appropriate one.

**Comment by glenn-jocher** [comment]
@ClarlieLuo hello,

It's good to hear that you can successfully make predictions with the pre-trained `yolov8n.pt` model. Regarding the CUDA version mismatch, you typically don't need to downgrade your GPU's CUDA capability; instead, you should install a PyTorch version that is compatible with your installed CUDA version (12.2 in your case).

Please check the PyTorch website for the version that matches your CUDA 12.2 environment and install it accordingly. This should align the torch-cuda version with your GPU's CUDA version and resolve the issue.

Keep up the great work, and if you encounter any further issues, feel free to reach out.

Happy detecting! 🚀

**Comment by ClarlieLuo** [comment]
@glenn-jocher hello,

Thank you for your suggestion.
I have upgraded the version to pytorch=2.1.0 and CUDA=12.2. Successfully predicting with the YOLO model using yolov8n.pt on the source 'https://ultralytics.com/images/bus.jpg'.

However, when attempting to use my self-trained model for predictions on a specific image, it still leads to a Segmentation fault (core down).

**Comment by saitarslanboun** [comment]
> @harith75 hi there,
> 
> Thank you for providing a comprehensive report of the issue you're experiencing. It seems like a segmentation fault issue is occurring during the prediction step on your Raspberry Pi setup.
> 
> Segmentation faults are usually related to accessing memory that the process doesn't have permission to, or trying to read/write from/to a portion of memory that doesn't exist.
> 
> Although YOLOv8 supports most environments, the potential incompatibility between the CPU (Cortex-A72) and some components of the model pipeline might be the primary issue here. The Raspberry Pi 4 CPU might not be sufficient to handle the load required by YOLOv8, causing it to attempt to allocate more memory than available which leads to a segmentation fault.
> 
> As much as we would like to support a large variety of hardware, ensuring compatibility with every possible setup is quite challenging. You might want to consider testing the model on a device with higher computational resources.
> 
> We'll continue to investigate this matter and update when we find a more concrete solution to this problem. Your patience is much appreciated.

Hello!

I encounter with the same issue on my server, with 200TB memory, 128 cores and 8 x A100 GPUs. If I need higher computational resources, then maybe I have to rent a whole datacenter, that might help?

**Comment by Shu2023a** [comment]
Hello.

Today I went through the same steps again as before.

Even without downgrading PyTorch, no segmentation faults occurred.

I'm trying yolov8 on a raspberry PI4B 4GB.
The OS is 64bit_Legacy Debian Bullseye from a clean install.
Python 3.9.2

https://docs.ultralytics.com/guides/raspberry-pi/?h=raspberry+pi#install-necessary-packages_1
Install by following the steps in

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get autoremove -y

pip3 install ultralytics

sudo reboot

pip show ultralytics
Name: ultralytics
Version: 8.1.9

pip show torch
Name: torch
Version: 2.2.0

yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'
can be successfully inferred.

**Comment by glenn-jocher** [comment]
@Shu2023a hello,

Great to hear that you've successfully run predictions with YOLOv8 on your Raspberry Pi 4B without encountering segmentation faults, and without the need to downgrade PyTorch. It seems that the latest updates and versions are working well for you.

Keep up the good work, and if you have any further questions or run into issues, feel free to reach out.

Happy detecting with YOLOv8! 🚀

**Comment by semanurbilada** [comment]
> Hello.
> 
> Today I went through the same steps again as before.
> 
> Even without downgrading PyTorch, no segmentation faults occurred.
> 
> I'm trying yolov8 on a raspberry PI4B 4GB. The OS is 64bit_Legacy Debian Bullseye from a clean install. Python 3.9.2
> 
> https://docs.ultralytics.com/guides/raspberry-pi/?h=raspberry+pi#install-necessary-packages_1 Install by following the steps in
> 
> sudo apt-get update sudo apt-get upgrade -y sudo apt-get autoremove -y
> 
> pip3 install ultralytics
> 
> sudo reboot
> 
> pip show ultralytics Name: ultralytics Version: 8.1.9
> 
> pip show torch Name: torch Version: 2.2.0
> 
> yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg' can be successfully inferred.

Hello everyone,
First of all, thxx for all the solutions that you offer but I can't install ultralytics on my raspberry pi 4 4gb currently. How am I going to resolve this issue?

I already check nearly all solutions on the internet and none of them worked! Torch and ultralytics and even opencv-python cannot be installed in raspberry pi right now :(((

**Comment by glenn-jocher** [comment]
@semanurbilada hello there! 😊

It sounds like you're running into some tricky installation issues on your Raspberry Pi. Since you've already tried many solutions, let's try a fresh approach. Could you please try installing the dependencies in a virtual environment? This often helps manage package versions and dependencies more smoothly. Here's a quick guide:

1. Create a new virtualenv:
   ```bash
   python3 -m venv yolovenv
   ```
   
2. Activate it:
   ```bash
   source yolovenv/bin/activate
   ```

3. Try installing the packages again within this environment:
   ```bash
   pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
   pip install ultralytics
   ```

This method might help bypass some of the issues you're facing. If you're still having trouble, it could be helpful to share the error messages you're encountering. Sometimes, the devil is in the details. 🕵️‍♂️

Let us know how it goes! We're here to help you get unstuck.

**Comment by Shu2023a** [comment]
Hello.

Today I created the OS image again and verified it.

Even without downgrading PyTorch, no segmentation faults occurred.

I'm trying yolov8 on a raspberry PI4B 4GB.
The OS is 64bit_Legacy Debian Bullseye from a clean install.
Python 3.9.2

https://docs.ultralytics.com/guides/raspberry-pi/?h=raspberry+pi#install-necessary-packages_1
Install by following the steps in

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get autoremove -y

pip3 install ultralytics

sudo reboot

pip show ultralytics
Name: ultralytics
Version: 8.1.37

pip show torch
Name: torch
Version: 2.2.2

yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'
can be successfully inferred.


How about checking the following?
- Is the network connected?
- Clean install the OS again and install ultralytics

**Comment by glenn-jocher** [comment]
@Shu2023a hello! 🎉

Great to hear you've got YOLOv8 running smoothly on your Raspberry Pi 4GB without segmentation faults. It looks like your setup is spot-on, and both `ultralytics` and `torch` are at the right versions. 

If someone is running into similar issues, a clean OS install and following the steps you've outlined, just like in [Ultralytics Raspberry Pi Guide](https://docs.ultralytics.com/guides/raspberry-pi/?h=raspberry+pi#install-necessary-packages_1), is indeed a solid approach. Ensuring a stable network connection during the setup can also make a significant difference. 🚀

Thanks for sharing this with the community. Your contribution might help others facing similar challenges. Keep enjoying YOLOv8, and don't hesitate to reach out if you have any more insights or queries!

**Comment by semanurbilada** [comment]
@glenn-jocher Thank you so much for your response!

I tried your solution and some other tricks again but here is the result:

![Screenshot 2024-03-30 at 8 28 45 PM](https://github.com/ultralytics/ultralytics/assets/96194982/8f5956ad-1ddc-4d07-a9d6-b4dc3bd1e700)

So, I'm going to install the Raspberry Pi OS again but 64bit this time as @Shu2023a offered. I'll let you know what happens, thxx again!

**Comment by glenn-jocher** [comment]
@semanurbilada, you're welcome! 😊 Reinstalling with the 64-bit Raspberry Pi OS sounds like a plan. Crossing my fingers that it resolves the issue for you. 🤞 Please do keep us updated on your progress, and if there's anything else we can assist with, don't hesitate to reach out. Good luck!

**Comment by semanurbilada** [comment]
@glenn-jocher Hi again!
Here is the updates so far;

- Firstly, I re-installed and setup the Raspian 64-bit Bullseye OS and now I can install the ultralytics and torch but only with python environment. is it normal that it just runs with venv?
- Second, opencv is not opening the camera in real time and there is no error, 


I am trying to resolve these issues but other than that, the library installation problems gone, I hope it helps to someone else's problems!

Thxx again to everyone who even try this publicly and give an idea!

**Comment by glenn-jocher** [comment]
Hi @semanurbilada!

I'm thrilled to hear you've made progress after switching to the Raspbian 64-bit Bullseye OS! 🎉 About your questions:

- Using a virtual environment (`venv`) is a common and recommended practice for Python projects, including when working with `ultralytics` and `torch`. It helps manage dependencies and ensures your projects run smoothly without conflicts. So yes, it's normal and even beneficial!

- For the `opencv` camera issue, sometimes it's a matter of permissions or specific camera drivers. You could try running your script with `sudo` to see if it's permission-related. Also, double-check if your Pi's camera is enabled (`sudo raspi-config` > Interface Options > Camera) and try a simple OpenCV script to test camera functionality:
```python
import cv2

cap = cv2.VideoCapture(0)  # Use 0 for the default camera

if not cap.isOpened():
    print("Cannot open camera")
    exit()

while True:
    ret, frame = cap.read()
    if not ret:
        print("Can't receive frame. Exiting ...")
        break
    cv2.imshow('frame', frame)
    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
```

Glad the library installation issues are sorted, and I appreciate your spirit of sharing solutions with the community! If there's more we can delve into, just let me know. Keep experimenting and exploring!

**Comment by Shu2023a** [comment]
Hello.

Today, I reconfirmed the Rasberry Pi OS (64-bit) Debian Bookworm.
I think this procedure can be used even if the 64bit_Legacy Debian Bullseye.

raspberry PI4B 4GB.
Rasberry Pi OS (64-bit) Debian Bookworm.

use a virtual environment
python -m venv env #(env is an arbitrary name)
source env/bin/activate

python --version
Python 3.11.2

https://docs.ultralytics.com/guides/raspberry-pi/?h=raspberry+pi#install-necessary-packages_1
Install by following the steps in

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get autoremove -y

pip3 install ultralytics

sudo reboot

source env/bin/activate

pip show ultralytics
Name: ultralytics
Version: 8.1.42

pip show torch
Name: torch
Version: 2.2.2

yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'
can be successfully inferred.

For cameras
yolo predict model=yolov8n.pt source=0 show=true
can be successfully inferred.

**Comment by glenn-jocher** [comment]
@Shu2023a hey there!

Fantastic to hear about your success with the Raspberry Pi OS (64-bit) Debian Bookworm and the Raspberry Pi 4B 4GB setup! 😊 Your confirmation that the procedure also works smoothly on the 64bit Legacy Debian Bullseye is super helpful.

It's great to see you're utilizing a virtual environment; it's such an effective way to manage packages and dependencies. Plus, your Python `3.11.2`, `ultralytics` version `8.1.42`, and `torch` version `2.2.2` setup looks spot on.

Your step-by-step recap is much appreciated and will certainly serve as a handy guide for others working in similar environments.

The camera inference command you shared is a neat addition too! It's always exciting to see YOLOv8 in action with real-time sources. 📸

Thanks for sharing your update and keep enjoying your exploration with YOLOv8 on the Raspberry Pi! If you stumble upon any more insights or questions, the community is here to dive in alongside you. Happy coding!
