### ISSUE TITLE
Help! GPU_mem shows 0G while training using VisDrone. Also, I'm not learning anything at all.

### ISSUE THREAD

**Issue by yukkin1021** [ultralytics/ultralytics#5275]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi.
I have never done any programming before and have never used YOLOv8, but I would like to train them using the VisDrone dataset.
Environment: M1 Mac book pro, Anaconda -jupyter notebook

Code
from ultralytics import YOLO
model = YOLO("yolov8n.pt")
model.train(data="VisDrone.yaml", epochs=50, batch=8)

Result
Starting training for 100 epochs...
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100         0G      1.928      3.933       1.13       1484        640:  
      

It stopped here and did not work at all (more than 30 minutes)

1. ultralytics is already installed.
2. downloaded VisDrone training files, etc.
3. the .yaml file path is fine
4. had learned it once, and it was fine then
5. when I tried to train with ultralytics HUB, it stopped working as well...

Need quick help. I will provide any information you need, but I have never programmed before and I use a google translator, so I may not understand the meaning well.

**Comment by glenn-jocher** [comment]
@yukkin1021 hi there,

Sorry to hear you're encountering difficulties. Let's see if we can find a solution for you.

As you are working with an M1 Mac, there could be compatibility issues with PyTorch and the M1 processor, subsequently leading the GPU memory to show as 0G. YOLOv8 depends on PyTorch, which currently might not fully support the M1 chip. 

Another issue could be from the batch size (batch = 8). Given the hardware you're using, it's possible that the batch size might be too large and is causing your system to run out of memory. Try reducing the batch size to see if this improves performance.

Finally, please ensure that both the Python environment and the Jupyter notebook have been properly configured to use the GPU, and that your GPU drivers are up to date. 

I understand that you are new to programming, but don't be discouraged! Everyone has to start somewhere, and it's great that you are learning.

Please go through these points, and see if the problem persists. If it does, let's continue this thread and we'll figure it out.
