### ISSUE TITLE
cls_loss is not 0 when training in single class mode

### ISSUE THREAD

**Issue by CesareDavidePace** [ultralytics/ultralytics#528]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

cls_loss is not 0 when training in single class mode

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by bluemellophone** [comment]
From what I can tell, this is because there are technically two "classes" in single class mode: the positive class (index 0) and the background class.

**Comment by CesareDavidePace** [comment]
technically yes, but in yolov5 the loss was always 0

**Comment by Laughing-q** [comment]
@CesareDavidePace yeah we have objectness branch in v5 so it doesn't need cls loss when there's only one class. But in v8 we removed the objectness branch so we actually treat single-cls as two classes(postive class and background).
