### ISSUE TITLE
Get coordinate during running predict with a cam.

### ISSUE THREAD

**Issue by Douilol** [ultralytics/ultralytics#5283]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to obtain all the corner coordinates of the detected objects while the program runs on a camera. But I don't know how to get them...

**Comment by RizwanMunawar** [comment]
@Douilol, you can obtain bounding box coordinates using the provided code snippet:

```python
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('yolov8n.pt')

# Perform inference on an image
results = model('https://ultralytics.com/images/bus.jpg')

boxes = results[0].boxes.xyxy.tolist()  # Bounding Boxes
classes = results[0].boxes.cls.tolist()  # Class IDs
names = results[0].names  # Class names
confidences = results[0].boxes.conf.tolist()  # Confidence scores

# Iterate through the results
for box, cls, conf in zip(boxes, classes, confidences):
    x1, y1, x2, y2 = box
    confidence = conf
    detected_class = cls
    name = names[int(cls)]
```

This code allows you to extract bounding box coordinates, class IDs, class names, and confidence scores from YOLOv8 model inference results.

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by Douilol** [comment]
thanks, man, this is very helpful. what is the link with 0 in the results? what does it represent?

**Comment by Douilol** [comment]
And how can I print variables during a run.

**Comment by RizwanMunawar** [comment]
To perform indexing operations, you can utilize [0]. If you want to display the values, you can achieve that by using the print(variable name) statement.

Hope this helps! Let me know if you have any additional questions. I am closing this issue, feel free to reopen it If the issue persists.
Thanks
