### ISSUE TITLE
How to collected boxes?

### ISSUE THREAD

**Issue by shersoni610** [ultralytics/ultralytics#529]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, 
I have followed the document as posted on the web. However, I do not get the correct boxes. My code is as follows
from ultralytics import YOLO
import sys
import cv2

model = YOLO('./models/yolov8n.pt')
filename = sys.argv[1]
img = cv2.imread(filename)
results = model.predict(source=img, stream=True)
for result in results:
    boxes = result.boxes.xyxy
    print(boxes)
cv2.imshow("Objects", img)
cv2.waitKey(0)

I get the following messages. What wrong I am doing? 

Ultralytics YOLOv8.0.11 🚀 Python-3.8.12 torch-1.13.1 CPU
Fusing...
YOLOv8n summary: 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
Traceback (most recent call last):
  File "yolo_detect_image.py", line 13, in <module>
    boxes = result.boxes.xyxy
AttributeError: 'list' object has no attribute 'boxes'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

**Comment by aminrabinia** [comment]
Similar question: how can I get the result image without saving the file? 

In yolov5 there used to be a render() for that. Any solution?

**Comment by shersoni610** [comment]
Working with the files is a performance bottleneck. Wish there is an API working with OpenCV images directly giving all the information directly to the user and not dump the information in "runs" folder.

**Comment by aminrabinia** [comment]
I had to force write_results() in yolo/v8/segment/predict.py to return img_annotated = self.annotatior.result()
Not the most elegant way to do it but at least now I have access to the cv2 result image

**Comment by akashlinux10may** [comment]
While try to retrivieng the results of detection in yolov8
it was working fine with yolov5

code is:

labels, cordinates = results.xyxyn[0][:, -1], results.xyxyn[0][:, :-1]
AttributeError: 'list' object has no attribute 'xyxyn'

Any solution to this?

**Comment by AyushExel** [comment]
results is a list. see example here https://docs.ultralytics.com/predict/
