### ISSUE TITLE
OpenImagesV7 yolov8 weight set

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/ultralytics#5292]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Has anyone created/trained a set of OpenImavesV7 weight set with a range of models similar to the ones you provide? 
I noted the steps to do this on the ultralytics site:

https://docs.ultralytics.com/datasets/detect/open-images-v7/

**Comment by glenn-jocher** [comment]
@apiszcz YOLOv8 is already available pretrained for OpenImagesV7 as shown in the README:

<img width="1511" alt="Screenshot 2023-10-09 at 17 42 26" src="https://github.com/ultralytics/ultralytics/assets/26833433/2492cbf4-5dc0-45e9-bace-c7613f266a0d">

**Comment by apiszcz** [comment]
Wow, I missed that update, perfect, thank you.

**Comment by glenn-jocher** [comment]
@apiszcz you're welcome! I'm glad to hear that the information was helpful. If you have any further questions or come across any issues while working with the OpenImagesV7 weights in YOLOv8, feel free to reach out. The Ultralytics team and YOLO community are here to help. Happy detecting!

**Comment by jinyoungkim927** [comment]
This doesn't seem true - clicking the link marked in the GitHub shows it is only trained on coco. Where can I access the model pretrained on OpenImagesV7?

**Comment by apiszcz** [comment]
go to the main page, select the traingle next to openimages section will open with the files

![image](https://github.com/ultralytics/ultralytics/assets/1430861/c0fb590c-1a69-4274-82fe-2da374bf660b)

**Comment by glenn-jocher** [comment]
@apiszcz apologies for the confusion earlier. To access the YOLOv8 model pretrained on OpenImagesV7, you can navigate to the main page of the Ultralytics repository. There, you'll find a section dedicated to OpenImages. Clicking the triangle next to this section will expand it, revealing the files available for download.

Here's a quick snippet to help you download the pretrained weights using `wget` in case you need it:

```bash
wget https://github.com/ultralytics/ultralytics/releases/download/v1.0.0/yolov8-openimages.pt
```

Let me know if you need any more help! 😊
