### ISSUE TITLE
Yolov8 Region Counter - how to freely move in the region 

### ISSUE THREAD

**Issue by yeongnamtan** [ultralytics/ultralytics#5300]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Reference to below,  could you help me understand how to 'freely move the region anywhere' after the video plays?
I don't understand how this is  possible when the programme is doing inference ?

https://github.com/ultralytics/ultralytics/blob/main/examples/YOLOv8-Region-Counter/readme.md

"After the video begins playing, you can freely move the region anywhere within the video by simply clicking and dragging using the left mouse button."

**Comment by RizwanMunawar** [comment]
@yeongnamtan Sure!

When you execute the provided command, it will initiate the inference process, allowing you to observe real-time object detection. Subsequently, two types of boxes, namely Polygon and Rectangle, will become visible on the screen. To interact with these boxes, simply left-click on any of their coordinates and drag them anywhere.

Here's the command for your reference:

```shell
python yolov8_region_counter.py --source "path/to/video.mp4" --save-img --view-img
```

**Comment by yeongnamtan** [comment]
@RizwanMunawar thanks. I am using sagemaker studio instance and there is nothing visible on the screen.  I can only see the polygons after inference is completed and I downloaded the mp4

**Comment by RizwanMunawar** [comment]
@yeongnamtan, to relocate a region, you must display the video stream; otherwise, the region will remain stationary.

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by RizwanMunawar** [comment]
@yeongnamtan you can run the Region counting solution on your local machine. Because Google colab does not support mouse events directly.

**Comment by yeongnamtan** [comment]
Thank you @glenn-jocher for the clarification

**Comment by DANISHFAYAZNAJAR** [comment]
@RizwanMunawar Can we have regions drawing and moving in real time. Like if we start detection on live inference via camera, we may need to select some area, which will be dynamic so, if we can draw and move region dynamically that will be more useful.

**Comment by RizwanMunawar** [comment]
@DANISHFAYAZNAJAR This feature is not supported yet, we will add support for this in the coming days.

Thanks
