### ISSUE TITLE
high CPU utilization while training YOLOv8 on coco dataset

### ISSUE THREAD

**Issue by christopher-park** [ultralytics/ultralytics#5301]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm trying to train YOLOv8 on coco dataset using following cli command:

`yolo detect train data=coco.yaml model=yolov8n.pt epochs=100 imgsz=640 device=`

While training, it looks like YOLOv8 is using gpu properly, but the cpu utilization goes up to 100% for all of my 16 cores.
Is this an expected behavior? If so, is there any parameter to control the number of cores to use while training?

Below is the terminal output of the command:

```
Ultralytics YOLOv8.0.196 🚀 Python-3.10.12 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 4090, 24214MiB)
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=coco.yaml, epochs=100, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=0, workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train7

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]           
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]                  
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]                
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]                 
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 22        [15, 18, 21]  1    897664  ultralytics.nn.modules.head.Detect           [80, [64, 128, 256]]          
Model summary: 225 layers, 3157200 parameters, 3157184 gradients, 8.9 GFLOPs

Transferred 355/355 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs/detect/train7', view at http://localhost:6006/
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning /home/chanwook/datasets/coco/labels/train2017.cache... 117266 images, 1021 backgrounds, 0 corrupt: 100%|██████████| 118287/118287 [
val: Scanning /home/chanwook/datasets/coco/labels/val2017.cache... 4952 images, 48 backgrounds, 0 corrupt: 100%|██████████| 5000/5000 [00:00<?, ?it
Plotting labels to runs/detect/train7/labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: SGD(lr=0.01, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs/detect/train7
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100       2.7G      1.111      1.384       1.17        224        640:   2%|▏         | 169/7393 [00:38<27:15,  4.42it/s]^C
```

Below is the output of `yolo checks`:
```
Ultralytics YOLOv8.0.196 🚀 Python-3.10.12 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 4090, 24214MiB)
Setup complete ✅ (16 CPUs, 94.2 GB RAM, 809.3/937.3 GB disk)

OS                  Linux-6.2.0-33-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 94.20 GB
CPU                 Intel Core(TM) i9-9900KF 3.60GHz
CUDA                11.7

matplotlib          ✅ 3.5.1>=3.3.0
numpy               ✅ 1.24.3>=1.22.2
opencv-python       ✅ 4.7.0.72>=4.6.0
pillow              ✅ 9.3.0>=7.1.2
pyyaml              ✅ 5.4.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.8.0>=1.4.1
torch               ✅ 2.0.1>=1.8.0
torchvision         ✅ 0.15.2>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
pandas              ✅ 1.3.5>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
```

While training, htop results:
![Screenshot from 2023-10-10 10-20-12](https://github.com/ultralytics/ultralytics/assets/103473542/0cd0c341-24c5-4778-a5a1-faadaab5742a)

Similar question https://github.com/ultralytics/ultralytics/issues/5095 did not help me.

**Comment by RizwanMunawar** [comment]
Indeed, CPU memory usage appears to be acceptable. This can be attributed to the dataset size and the batch size employed during training. If you opt to decrease the batch size, it will lead to a reduction in CPU memory consumption.

### Adjust Batch Size
```
yolo detect train data=coco.yaml model=yolov8n.pt epochs=100 imgsz=640 batch=8
```

### Adjust No Of Workers 
Additionally, you have the flexibility to select the number of workers based on your requirements.
```
yolo detect train data=coco.yaml model=yolov8n.pt epochs=100 imgsz=640 workers=4
```

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by christopher-park** [comment]
Thanks for answering! Indeed, decreasing batch size and/or number of workers help with a penalty of increasing training time.
However, with those method, it is still using all of my 16 cores, which I would like to avoid (because I'm planning to run YOLOv8 in another machine that has 112 cores shared with other people.)

Is there any way to limit the number of cpus to use while training?

Thanks!

**Comment by PiyushKamboj1503** [comment]
To narrow down your question, you are looking to implement something on the lines of "n_jobs" that is available in scikit and other python libraries to limit the number of cores that are used while training.

**Comment by christopher-park** [comment]
Exactly. `n_jobs` would solve my problem. 
Although this would be achieved by running it on docker container with a limited number of cores, it would be great if YOLOv8 provides a generic way to do so.

By the way, any idea if PyTorch provides such implementation?
I'm using `torch==2.0.1` and `torch.set_num_threads(1)` doesn't seem to do anything. Please correct if I'm wrong.

**Comment by PiyushKamboj1503** [comment]
@christopher-park you can refer to the following document: https://pytorch.org/docs/stable/notes/multiprocessing.html

Let me know how it goes!

**Comment by glenn-jocher** [comment]
@christopher-park certainly. PyTorch provides options to manage the number of threads through settings for intra and inter op parallelism. These settings should be defined before any computations are done for them to take effect. 

For specifically limiting the number of CPU cores used, you can set `torch.set_num_threads(1)` but you will have to make sure PyTorch does not override this in any of the imported modules. You may also try setting the `OMP_NUM_THREADS` environment variable to tell OpenMP (which PyTorch uses for threading) to limit the number of cores. Be sure to specify this before starting the Python interpreter.

Also, reducing the number of workers in your DataLoader to a smaller value (which should be less than or equal to the number of cores) should also aid in reducing the CPU usage.

While this can limit the CPU core usage, please note that this can have an impact on the training time. And it may be necessary to run your own benchmarks to choose the best parameters considering both time and resources.

If you're intending to use your model in a shared environment, using Docker could indeed be a more suitable alternative, as it allows for more granular control of resources.

As always, please perform tests to ensure these settings work as expected in your specific environment.

**Comment by christopher-park** [comment]
@PiyushKamboj1503 @glenn-jocher Thanks a lot. My concern is pretty much resolved. Meanwhile I'll look into torch side for constraining cpu usage.

**Comment by glenn-jocher** [comment]
@christopher-park, thank you for providing your valuable insights, and I'm glad to hear that your concern has been largely addressed!

As you delve into the PyTorch side to limit CPU utilization while running YOLOv8, you might want to look into controlling thread usage in PyTorch. Specifically, try adjusting the parameters for intra and inter op parallelism. Just be sure to define these settings prior to executing any computations to ensure they take effect.

Also, remember to consider the 'workers' parameter in your DataLoader. Reducing the number of workers to a smaller value, which should ideally be less or equal to the number of cores, could also aid in controlling CPU usage.

Just be aware that while these modifications can restrict CPU core usage, they may also impact the training time. It would be commendable to run benchmarks to identify the best balance between time efficiency and resource utilization under your specific conditions.

Stay curious and keep exploring. Looking forward to hearing about your progress!

**Comment by christopher-park** [comment]
@glenn-jocher thank you for very helpful advises.

Just to help anyone having similar issue as mine, I've noticed that,

`export OMP_NUM_THREADS=1` works for me as suggested in https://github.com/pytorch/pytorch/issues/3146. 
As mentioned in the link, setting `MKL_NUM_THREADS` was not necessary.

I also found `ENV OMP_NUM_THREADS=1` in some YOLOv8 Dockerfiles.


Other than this, some other threads, which seemingly are related to my issue, such as,
https://github.com/pytorch/pytorch/issues/25010
https://github.com/pytorch/pytorch/pull/52815
https://discuss.pytorch.org/t/cpu-usage-far-too-high-and-training-inefficient/57228/5
suggested `torch.set_num_threads(1)` and/or `pin_memory=False` did not work.
I set these in the beginning of `ultralytics/models/yolo/model.py` but it did not show any difference.

**Comment by glenn-jocher** [comment]
@christopher-park, thank you for sharing your findings. Your contribution will undoubtedly be beneficial to others who encounter similar issues.

Using `export OMP_NUM_THREADS=1` indeed seems to be an effective way to command OpenMP (which PyTorch uses for threading) to limit the number of cores it should use. This strategy can be particularly beneficial in reducing overhead due to excessive inter-thread communication, thereby expediting the training process.

I'm sorry to hear that `torch.set_num_threads(1)` and `pin_memory=False` didn't yield the desired results for you. These options may not always result in a substantial difference, especially as different tools or system setups may interpret and handle these settings differently.

It's interesting that you didn't observe this high CPU usage issue when running with multiple GPUs. This may pertain to how PyTorch schedules tasks on multiple GPUs as opposed to a CPU or a single GPU.

Again, thank you for your valuable input. Your observations lend substantial insight into the nuances of handling CPU usage in training YOLOv8 using PyTorch. It's discoveries like yours that help enhance the collective knowledge of the community.

**Comment by pnthai88** [comment]
> Exactly. `n_jobs` would solve my problem. Although this would be achieved by running it on docker container with a limited number of cores, it would be great if YOLOv8 provides a generic way to do so.
> 
> By the way, any idea if PyTorch provides such implementation? I'm using `torch==2.0.1` and `torch.set_num_threads(1)` doesn't seem to do anything. Please correct if I'm wrong.

jeez! this make me headache whole day because i never know why onnx use too much cpu compare with i use onnx runtime. Thanks for your help man . You saved me
