### ISSUE TITLE
Load network only once

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/ultralytics#5304]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I tested YoloV5 i noticed that it loaded the network on every new inference, thus I customized the code to run the "load_network" function  on startup and then run the "run" function with the image. that reduced drastically the inference time for every image...

now, i am testing yolov8, and the documentation says:

```
    from ultralytics import YOLO

# Load a pretrained YOLOv8n-seg Segment model
model = YOLO('yolov8n-seg.pt')

# Run inference on an image
results = model('bus.jpg')  # results list

# View results
for r in results:
    print(r.masks)  # print the Masks object containing the detected instance masks
```

will the "model = YOLO('whatever.pt')" row load the model or just define it and load it when the inference happens? in case it is the latter, is it possible to load it once and keep it loaded?

Thank you!

**Comment by MasIgor** [comment]
I found the time to make some tests and found that the network is loaded only when the inference is done.

To replicate:

- run "model = YOLO('yolov8n-seg.pt')"
- add a long pause in code
- rename or delete the PT file 
- try to run "results = model('bus.jpg')"

you get the error " ERROR - Inference error: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from C:\Users\ADMI......"

If it would have been loaded at step 1, it would have the network in memory and would not notice the missing file. 

In YoloV5 this could be done by running the "load_network" function indipendently from the "run" function. but required some minor code editing. (it worked, i tried it few months back)

Can this be done in YoloV8 without editing the original code?

Thank you very much!

**Comment by glenn-jocher** [comment]
@MasIgor hello, 

I appreciate your efforts for extensively testing and providing detailed insights. The command `model = YOLO('yolov8n-seg.pt')` initializes the YOLO object with the network specifications loaded from the given path. However, the actual model weights are loaded into memory later when you run an inference, i.e., `model('bus.jpg')`.

Your suggestion of creating a method like `model.preload()` does make sense, which will load the model into memory right after the object initialization. This indeed could save inference time especially in applications where such minor time differences are critical.

Currently, YOLOv8 does not provide an out-of-the-box feature to achieve this, and you have to manually edit the code to accommodate this functionality.

Your suggestion is valuable, it will help in improving the efficiency of the model. We will consider this for our upcoming updates. And thank you for testing and providing such a constructive suggestion, it greatly aids the YOLOv8 and Ultralytics community in refining the project further.

**Comment by MasIgor** [comment]
Hi @glenn-jocher !

Thanks for your feedback! I've only minimal experience in python coding, but will try to do it on my own for these tests. For my personal application, this functionality would be fundamental to take the decision to switch to yoloV8. (currently running with omron object recognition) 

aside from my application, i agree with you that it would be a great addition, since most of the time the model will not change between one inference and the other, and reloading the model on every inference (almost doubling the execution time) does in most application bring no advantage. especially now, when each neural network pushes towards speed (and accuracy.. ;p ) cutting down the time by a factor of almost 2 is huge..

again thanks, I will try to code it on my own and see what happens.. a nice day to you all!

**Comment by MasIgor** [comment]
is my assumption correct that the red marked code does the model loading if its not yet loaded? if it is already loaded it skips the loading entirely and does the prediction? (green box)

I assume that this check is for video, so it does not load the model between each frame.. 

![image](https://github.com/ultralytics/ultralytics/assets/67956327/bec8cb9b-518c-4064-91c9-361b7cf5abb2)

**Comment by MasIgor** [comment]
hey this was easier than expected! made it quick and dirty in the source code.. would be cool to have it in the official code so it can be updated without problems..

Inside engine\model.py

```
     def preload(self, predictor=None, **kwargs):
        """
        Perform prediction using the YOLO model.

        Args:
            predictor (BasePredictor): Customized predictor.
            **kwargs : Additional keyword arguments passed to the predictor.
                Check the 'configuration' section in the documentation for all available options.
        Returns:
            True If the model has been loaded,
            False if the model has not been loaded or was already loaded
        """

        is_cli = (sys.argv[0].endswith('yolo') or sys.argv[0].endswith('ultralytics')) and any(
            x in sys.argv for x in ('predict', 'track', 'mode=predict', 'mode=track'))

        custom = {'conf': 0.25, 'save': is_cli}  # method defaults
        args = {**self.overrides, **custom, **kwargs, 'mode': 'predict'}  # highest priority args on the right
        prompts = args.pop('prompts', None)  # for SAM-type models

        if not self.predictor:
            self.predictor = (predictor or self._smart_load('predictor'))(overrides=args, _callbacks=self.callbacks)
            self.predictor.setup_model(model=self.model, verbose=is_cli)
            return True;
        else:  # only update args if predictor is already setup
            self.predictor.args = get_cfg(self.predictor.args, args)
            if 'project' in args or 'name' in args:
                self.predictor.save_dir = get_save_dir(self.predictor.args)
            return False;

    def predict(self, source=None, stream=False, predictor=None, **kwargs):
    ...
    ...
    ...

```

**Comment by glenn-jocher** [comment]
@MasIgor hello,

Congratulations on figuring out a solution for preloading models! Your approach of adding a separate method `preload()` in `engine\model.py` for loading models into memory ahead of inference time seems to be on point.

You're right in your understanding that the model is only loaded if it is not pre-loaded. This is indeed optimized for video inference, where loading the model for each frame would drastically impact performance.

The Ultralytics team constantly aims to improve the efficiency of YOLOv8, and suggestions like yours tremendously help us in refining the project further. In future updates, we'll definitely consider adding a feature for preloading models, given how critical it can be for reducing inference time.

Please feel free to share any other insights or suggestions you may have. Your contributions are greatly appreciated!

Thank you!

**Comment by MasIgor** [comment]
@glenn-jocher good day! Is there a time estimate on when this could be implemented? as of now i have a custom code and keeping yolo up to date is not as straight forward as it could be..  

i was hoping since it is a rather small change that it can be implemented anytime soon.. 

Thanks!

**Comment by glenn-jocher** [comment]
Hello @MasIgor,

Your suggestion for preloading the model has certainly caught our attention and is in consideration for future updates. However, as of now, we can't provide an exact timeline for its implementation. The YOLOv8 team is constantly working on fixes, improvements, and new features, but prioritizing them takes into account various factors, including complexity, impact, and the overall roadmap.

We truly understand your concern about maintaining your customized code while keeping up to date with our updates. Rest assured, we'll make this process more seamless in the future.

We very much appreciate your input and patience, and we'll strive to meet your expectations.
Thank you!
