### ISSUE TITLE
Show only 2 best predictions on image when plotting

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/ultralytics#5309]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello!

If i plot the results on the image, is it possible to limit it to the 2 with highest score? or do I need to iterate the restult.boxes? If so, are they ordered by score or are they random and need to be checked all?

thank you!

**Comment by PiyushKamboj1503** [comment]
@MasIgor you can use the 'max_det=2' argument while predicting

**Comment by MasIgor** [comment]
perfect thank you!

**Comment by glenn-jocher** [comment]
@PiyushKamboj1503 you're welcome! I'm glad I could help. Don't hesitate to reach out if you have any more questions or run into any issues. Happy coding with YOLOv8!
