### ISSUE TITLE
Resuming training does not work - AssertionError: Resume checkpoint f{last} not found

### ISSUE THREAD

**Issue by Robotatron** [ultralytics/ultralytics#532]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

For some reason resume does not work for me, it does not find the model (tried the path without quotes as well)
I triple checked the path is correct, in fact I right clicked on the file and selected "copy path" from the Jupyter UI

```
yolo cfg="../custom.yaml" resume="/YOLOv8/Sagemaker/09-X-800-<scratch>/weights/last.pt"
Ultralytics: Overriding /opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/configs/default.yaml with ../custom.yaml
Ultralytics YOLOv8.0.13 🚀 Python-3.8.15 torch-1.10.1 CUDA:0 (A100-SXM4-40GB, 40536MiB)
                                                      CUDA:1 (A100-SXM4-40GB, 40536MiB)
Traceback (most recent call last):
  File "/opt/conda/envs/oneformer/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/configs/__init__.py", line 209, in entrypoint
    func(cfg)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/v8/segment/train.py", line 151, in train
    model.train(**vars(cfg))
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 199, in train
    self.trainer = self.TrainerClass(overrides=overrides)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/v8/segment/train.py", line 25, in __init__
    super().__init__(config, overrides)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 84, in __init__
    self.check_resume()
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 509, in check_resume
    assert args_yaml.is_file(), \
AssertionError: Resume checkpoint f{last} not found. Please pass a valid checkpoint to resume from, i.e. yolo resume=path/to/last.pt
```

### Environment

Ultralytics YOLOv8.0.13 🚀 Python-3.8.15 torch-1.10.1

### Minimal Reproducible Example

yolo cfg=custom.yaml resume='runs/Sagemaker/03-X-600-hyp-default/weights/last.pt'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by suryan-s** [comment]
same issue here!!

**Comment by AyushExel** [comment]
resume might not be working as expected. This is a known issue along with tf export as mentioned on the readme. We'll fix this soon

**Comment by Robotatron** [comment]
> resume might not be working as expected. This is a known issue along with tf export as mentioned on the readme. We'll fix this soon

Thanks! Any rough ETA on this?

**Comment by Martin-N3T** [comment]
I had a similar issue: trained on Colab and got to 39/100 epochs and training stopped for no apparent reason. How do I trouble shoot why training has stopped? And more importantly, how do I resume interrupted training (Transfer learning)? This worked well in YOLOv5. Many thanks for fixing this. Otherwise YOLOv8 is awesome. Great work !!!

**Comment by msabrimas** [comment]
try like this:

!yolo 'task=detect' 'mode=train' 'resume' 'model=/content/drive/MyDrive/Object_Detection/runs/detect/train/weights/last.pt' 'data=custom_data.yaml'

**Comment by shaiful019** [comment]
> try like this:
> 
> !yolo 'task=detect' 'mode=train' 'resume' 'model=/content/drive/MyDrive/Object_Detection/runs/detect/train/weights/last.pt' 'data=custom_data.yaml'

Thanks. It works for me.

**Comment by pderrenger** [comment]
@shaiful019 glad to hear it worked for you! If you encounter any other issues or need further assistance, feel free to ask. Keep up the great work!
