### ISSUE TITLE
AIFI implementation causing RT-DETR GPU inferencing using too much CPU

### ISSUE THREAD

**Issue by SteveHawk** [ultralytics/ultralytics#5328]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

When running RT-DETR inference on GPU, it would also take up all the available CPU cores, which is not ideal.

I believe the `build_2d_sincos_position_embedding` function in AIFI implementation is the root cause:

https://github.com/ultralytics/ultralytics/blob/7517667a33b08a1c2f7cca0dd3e2fa29f335e9f3/ultralytics/nn/modules/transformer.py#L73-L103

The three `torch.arange` calls does not have device specified, so they will be created on CPUs by default, and causing PyTorch to take up all the CPUs in the following computations.

I propose adding the device parameter, which appears to solve the issue.

```python
def forward(self, x):
    ...
    pos_embed = self.build_2d_sincos_position_embedding(w, h, c, device=x.device)
    ...

@staticmethod
def build_2d_sincos_position_embedding(w, h, embed_dim=256, temperature=10000.0, device="cpu"):
    ....
    grid_w = torch.arange(int(w), dtype=torch.float32, device=device)
    grid_h = torch.arange(int(h), dtype=torch.float32, device=device)
    ...
    omega = torch.arange(pos_dim, dtype=torch.float32, device=device) / pos_dim
    ...
```

### Environment

```bash
Ultralytics YOLOv8.0.196 🚀 Python-3.11.4 torch-2.0.1 CUDA:0 (NVIDIA GeForce RTX 3090, 24260MiB)
Setup complete ✅ (24 CPUs, 196.6 GB RAM, 75.0/98.9 GB disk)                                    
                                                                                                
OS                  Linux-5.4.0-139-generic-x86_64-with-glibc2.31                               
Environment         Linux                                                                       
Python              3.11.4                                                                      
Install             git                                                                         
RAM                 196.59 GB                                                                   
CPU                 Intel Xeon Gold 6226R 2.90GHz                                               
CUDA                11.8                                                                        
                                                                                                
matplotlib          ✅ 3.7.2>=3.3.0                                                             
numpy               ✅ 1.24.3>=1.22.2                                                           
opencv-python       ✅ 4.8.0.74>=4.6.0                                                          
pillow              ✅ 9.4.0>=7.1.2                                                             
pyyaml              ✅ 6.0>=5.3.1                                                               
requests            ✅ 2.31.0>=2.23.0                                                           
scipy               ✅ 1.11.1>=1.4.1                                                            
torch               ✅ 2.0.1>=1.8.0                                                             
torchvision         ✅ 0.15.2>=0.9.0                                                            
tqdm                ✅ 4.65.0>=4.64.0                                                           
pandas              ✅ 2.0.3>=1.1.4                                                             
seaborn             ✅ 0.12.2>=0.11.0                                                           
psutil              ✅ 5.9.5                                                                    
py-cpuinfo          ✅ 9.0.0                                                                    
thop                ✅ 0.1.1-2209072238>=0.1.1                                                  
```

### Minimal Reproducible Example

```bash
yolo detect predict \
    model=./rtdetr-runs/train/weights/best.pt \
    source=./dataset/test/test-images/ \
    project=rtdetr-runs \
    line_width=1 \
    device=0 \
    half=true
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@SteveHawk thank you for bringing this issue to our attention and for the detailed explanation. As per your findings, it seems that specifying the `device` parameter in the `torch.arange` calls within the `build_2d_sincos_position_embedding` function might solve the issue. This function currently does not consider where tensor computations should be carried out and it attempts to default to CPUs, thereby causing the high CPU utilization during GPU inferencing.

Your suggestion to add the `device` parameter is very insightful, as this will allow the tensor operations to be performed on the GPU, which should greatly reduce the CPU usage. 

We appreciate that you have even provided the proposed changes in the code. Our team will further investigate and test these changes to ensure they're safe and valid. Once the tests pass, we anticipate including these changes in the next YOLOv8 release. Thank you for contributing to YOLOv8 and helping us improve.

**Comment by SteveHawk** [comment]
Thanks for the reply! Looking forward to the update.
