### ISSUE TITLE
Issue with mlflow logging | TypeError: PosixPath object is not subscriptable

### ISSUE THREAD

**Issue by ChiragGarg-TomTom** [ultralytics/ultralytics#5334]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I am using yolov8 in azureml workspace with mlflow. Everything works fine without mlflow. With mlflow, I am getting an error at the end.  I have attached screenshot for  the same. The error originates from [here ](https://github.com/ultralytics/ultralytics/blob/7fd5dcbd867554063de87a1e621d2080bc1d0580/ultralytics/utils/callbacks/mlflow.py#L59C1-L59C43)
![image](https://github.com/ultralytics/ultralytics/assets/136709613/28325dec-106c-4367-ae28-1cfcdca677f3)

### Environment

Ultralytics YOLOv8.0.196 🚀 Python-3.11.6 torch-2.1.0+cu121 CPU (Intel Xeon E5-2690 v4 2.60GHz)
Setup complete ✅ (6 CPUs, 110.0 GB RAM, 102.6/118.1 GB disk)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ChiragGarg-TomTom hello,

There appears to be an issue when integrating mlflow with YOLOv8, and judging from the error message, I believe it might be related to how we handle PosixPath objects in our mlflow callback function. Your error seems to be thrown when we try to subscript a PosixPath object, which isn't supported in Python.

Just as background, PosixPath is a Python class used for handling file paths in a more convenient and safe manner than just raw strings. However, unlike strings, you cannot access individual elements of a PosixPath object using indexing, which is termed as subscripting in Python.

We utilize PosixPath instances extensively throughout our code, including the mlflow logging function. I suspect that your error is a result of this discrepancy. Our team will thoroughly investigate this issue, and I assure you that we will do our best to release a fix as soon as possible.

In the meantime, as a workaround, you might want to disable mlflow logging or replace the PosixPath instances with string instances in your local copy of YOLOv8, although this last approach might potentially create other problems as well.

Thank you for finding this bug and helping us improve the quality of our code! We truly appreciate your contribution and patience while we work on this.

**Comment by ChiragGarg-TomTom** [comment]
@glenn-jocher Thanks for the explanation. I suspected the same issue. I have provided a [comment](https://github.com/ultralytics/ultralytics/commit/742ec7fb1debbf5f683ff0f6eb00c786d7de0535#r129721655)  at the exact location. May be its helpful.

**Comment by glenn-jocher** [comment]
@ChiragGarg-TomTom, thank you for your comment and reference. It indeed is insightful and will be very helpful in addressing this issue.

The section you've pointed out does seem to be handling PosixPath objects incorrectly, which as you and I have both noted, are not subscriptable. This is likely the cause of the error you're experiencing.

To fix the error, we will most likely need to convert the PosixPath objects to strings before handling them in this manner. However, we will need to carefully consider the potential consequences in the rest of the code.

Thank you again for your input. We appreciate your cooperation and patience as we work on this. Please hang tight while we develop a fix – we aim to get it to you as quickly as possible. Your contribution to the YOLOv8 community is greatly appreciated!

**Comment by ChiragGarg-TomTom** [comment]
@glenn-jocher Looking forward to the solution.

**Comment by glenn-jocher** [comment]
Hi @ChiragGarg-TomTom, 

Thank you so much for your patience! The Ultralytics team is working hard to remedy this issue with our mlflow integration. We understand the importance of this function to your workflow, and we want to ensure we provide the best solution possible. 

Your contribution has been valuable in helping us identify and understand the problem. We'll notify you as soon as we have an update or fix for this issue.

Thanks again for your understanding and patience. We appreciate you being part of the YOLOv8 community!

**Comment by glenn-jocher** [comment]
@ChiragGarg-TomTom do you think you could do us a favor and implement a test for mlflow logging? I've never used it myself so it's hard for me to debug.

@AyushExel @RizwanMunawar @fcakyon another MLFlow issue, we really need to add it to tests.

**Comment by ChiragGarg-TomTom** [comment]
Hi @glenn-jocher I was on vacation. I will try to see if I can provide something soon.

**Comment by glenn-jocher** [comment]
@ChiragGarg-TomTom, thank you for your response. We understand and hope you had a wonderful vacation. When you are available, your contribution would be greatly appreciated. If you need any assistance or need to discuss further when you're back, feel free to reach out. We value your input and patience as we work towards improving YOLOv8!
