### ISSUE TITLE
Connection of key points with an object on consecutive frames

### ISSUE THREAD

**Issue by vorobevnd** [ultralytics/ultralytics#5336]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello to the ultralyrics team!
First of all, thank you for this wonderful product!

In my task I have to get the key points from a video with several objects (people). But as a result (result.keypoints) I see several tensors of key points without binding them to a specific object. How can I understand which key points belong to which of the objects? For example, in the case when the object disappears from the frame for a few seconds?

Do I understand correctly that the order of the groups of key points is guaranteed to be unchanged? That is, if one of the objects was conditionally selected first, then on all frames its key points will be first in the list?
If this is the case, what should we do in the scenario, for example, with object 2, if the first one disappeared from the frame in the middle of the video recording, that is, the key points of object 2 will be the first in the list?

To simplify the question, is there any way to link the key points of the same object on consecutive frames, taking into account the fact that the number of objects on the video may vary?

**Comment by zshariff6506** [comment]
Howdy!

I don't know a way to link key points throughout multiple frames as it is inferred that your key points would be moving and could be mixed with similar key points that pass by close.

**Comment by glenn-jocher** [comment]
@vorobevnd hello,

Thank you for reaching out on this great point and it's indeed a complex problem to address.

In the tracking scenario, it's important to understand that YOLOv8 architecture outputs predictions per image, without any temporal continuity or object identity information across frames. However, you can track keypoints or objects across frames by adding an additional tracking logic on the top of the model's output. 

This typically involves comparing keypoints in consecutive frames and using a technique such as the Hungarian algorithm, Optical Flow, or Kalman Filters to associate keypoints from one frame to the next.

With regards to objects disappearing and then reappearing, you would need an algorithm capable of tracking object "identities" over time. When an object leaves a frame and reenters, that object would be considered a new, distinct object from the model's perspective. If the object's "identity" is stored and its features haven't changed significantly, you could potentially reidentify it when it reappears using a feature comparison method. But please note that these are more advanced topics and often depend heavily on the specifics of the video and objects you are tracking. 

I hope this helps! Please explore these methods in detail for your use-case and let us know if you have any more questions in making YOLOv8 even better. The contributions and innovations of our community play a big part in the iterative progress of this project.

Best,
Glenn Jocher
