### ISSUE TITLE
LOW FRAMERATE ON VIDEO AFTER DETECTION

### ISSUE THREAD

**Issue by Drexk26** [ultralytics/ultralytics#5344]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi!
For my university project I am trying to implement object recognition on Webcam videostream or generical videos showing roads, cars, pedestrians and other typical objects could be found in the street.
My python script is running on Jetson Orin and currently a yolov8n.pt model is being used.
The detection and segmentation work very good but, when I show (using the cv2.imshow() method) the frame with the bounding boxes, the fps drop to 2-3 despite the original video has an average of 30 fps.

Which could be the issues or other aspects I am not correctly considering to optimize the framerate? 

Thanks!! ;-)

**Comment by PiyushKamboj1503** [comment]
@Drexk26 you can adjust the size of the frames which you are feeding to the model to reduce your load. On lower resolutions, the detection is much faster. Also check if the arguement 'Stream=True' is enabled while processing the frames.

**Comment by Drexk26** [comment]
> @Drexk26 you can adjust the size of the frames which you are feeding to the model to reduce your load. On lower resolutions, the detection is much faster. Also check if the arguement 'Stream=True' is enabled while processing the frames.

Hi! Thanks you. I have just downsized the frames from 720x1080 to 480x640 and the fps are low the same. Where should I check the argument Stream=True in the code?

**Comment by RizwanMunawar** [comment]
@Drexk26, your comprehensive issue description is greatly appreciated!

It's important to note that directly displaying video frames via OpenCV can lead to a drop in FPS. If you aim to improve the FPS, here are some options to consider:

- **Avoid Video Display:** Rather than displaying the video in real-time, opt to write it to a video file.
- **Resize Images:** Reducing the image size, for instance, to 640 x 360, can significantly boost FPS performance.
- **Hardware Upgrade:** Enhance your system's capabilities by utilizing a GPU for model execution. CPUs often yield lower FPS in comparison.

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by Drexk26** [comment]
@RizwanMunawar Hi!
How could I enhance the detection by correctly exploting the Nvidia Jetson Orin's GPU? What is the basic way to access to the GPU? Unfortunately, I am still learning on how to deal with this kind of technologies.
Thank you!

**Comment by RizwanMunawar** [comment]
@Drexk26, if you're working with a Jetson Orin, I'd highly advise optimizing your model's performance by utilizing a TensorRT engine. Converting the YOLOv8 model to a TensorRT engine and running inference with it can result in a significant boost in FPS.

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by PiyushKamboj1503** [comment]
> > @Drexk26 you can adjust the size of the frames which you are feeding to the model to reduce your load. On lower resolutions, the detection is much faster. Also check if the arguement 'Stream=True' is enabled while processing the frames.
> 
> Hi! Thanks you. I have just downsized the frames from 720x1080 to 480x640 and the fps are low the same. Where should I check the argument Stream=True in the code?

look for the following lines in your code: 'results=model(source="/path/to/vid", imgsz= 480, stream=True)'

**Comment by glenn-jocher** [comment]
Hi @Drexk26! It seems like you're looking for the use of the 'stream' argument in the model. You can try checking where you are calling your model for prediction after loading it. There you will pass your video source and image size, along with the stream argument. It would look something like this: 

results = model(source="/path/to/vid", imgsz=480, stream=True)

Please note that the 'stream' argument helps in fast processing of the video frames by utilizing a buffer mechanism. Setting 'stream=True' might help improve the frames per second (fps) while working with video inputs. Make sure to adjust the 'imgsz' parameter according to your needs and capabilities of your device.
