### ISSUE TITLE
YOLO-NAS inference broken.

### ISSUE THREAD

**Issue by Y-T-G** [ultralytics/ultralytics#5345]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

When you run YOLO-NAS inference, it throws an error:

`RuntimeError: Inference tensors do not track version counter.`

### Environment

Ultralytics YOLOv8.0.196 🚀 Python-3.8.10 torch-1.10.0+cu113 CUDA:0 (NVIDIA A100 80GB PCIe, 81085MiB)
Setup complete ✅ (96 CPUs, 503.6 GB RAM, 488.2/3519.3 GB disk)

OS                  Linux-5.4.0-150-generic-x86_64-with-glibc2.29
Environment         Docker
Python              3.8.10
Install             pip
RAM                 503.63 GB
CPU                 AMD EPYC 7643 48-Core Processor
CUDA                11.3

matplotlib          ✅ 3.7.1>=3.3.0
numpy               ✅ 1.23.0>=1.22.2
opencv-python       ✅ 4.8.0.76>=4.6.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.28.2>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 1.10.0+cu113>=1.8.0
torchvision         ✅ 0.11.0+cu113>=0.9.0
tqdm                ✅ 4.64.1>=4.64.0
pandas              ✅ 1.3.5>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

```
from ultralytics import NAS

# Load a COCO-pretrained YOLO-NAS-s model
model = NAS('yolo_nas_m.pt')

# Run inference with the YOLO-NAS-s model on the 'bus.jpg' image
results = model("video.mp4", save=True)
```

### Additional

Error is resolved if you modify https://github.com/ultralytics/ultralytics/blob/7fd5dcbd867554063de87a1e621d2080bc1d0580/ultralytics/utils/torch_utils.py#L50

to only return `torch.nograd`.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
It's also broken for versions above super-gradients==3.1.2. So this version should be enforced.

**Comment by glenn-jocher** [comment]
@Y-T-G thanks for making us aware of this issue. It appears there could be compatibility issues with versions of `super-gradients` above 3.1.2. We appreciate your suggestion to enforce this version. Our team will look into this matter more and consider specifying this version requirement in the dependencies during the installation process to ensure best performance. We're always thankful for the support and vigilance of our user community in helping us maintain and improve the project!

**Comment by bsridatta** [comment]
Any updates here, still running into this. Thanks!

**Comment by glenn-jocher** [comment]
@bsridatta we're currently investigating the bug with YOLO-NAS inference. Please refer to the open issue on the Ultralytics YOLOv8 repo for the latest updates. Your patience is appreciated as we work to resolve this. 😊🔧
