### ISSUE TITLE
how to print all predition values of every class?

### ISSUE THREAD

**Issue by Anikcb** [ultralytics/ultralytics#5347]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i was running a model but couldn't get the prediction values for every class. "probs" shows None. how to print the values??

### Additional

import os
from ultralytics import YOLO
import cv2

cap = cv2.VideoCapture(0)
model_path = os.path.join('.', 'content', 'runs', 'detect', 'train', 'weights', 'last.pt')

model = YOLO(model_path) 

threshold = 0.0
class_name_dict = {0: 'Glass',1:'Metal',2:'Paper',3:'Plastic',4:'Trash'}

i=1
while (cap.isOpened()):
    ret, frame = cap.read()
    results = model(frame)[0]
    print(results)
    
    for result in results.boxes.data.tolist():
        x1, y1, x2, y2, score, class_id = result
        if score > threshold:
            name = class_name_dict[int(class_id)]+' '+str(round(score,2))
            cv2.rectangle(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0, 255, 0), 4)
            cv2.putText(frame, name.upper(), (int(x1), int(y1 - 10)),
                        cv2.FONT_HERSHEY_SIMPLEX, 1.3, (0, 255, 0), 3, cv2.LINE_AA)
    if ret==True:
        cv2.imshow('frame',frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    print(i)
    i=i+1

cap.release()
cv2.destroyAllWindows()

**Comment by RizwanMunawar** [comment]
@Anikcb, the provided code allows you to obtain prediction values for each class effectively.

```python
import os
from ultralytics import YOLO
import cv2

cap = cv2.VideoCapture(0)
model_path = os.path.join('.', 'content', 'runs', 'detect', 'train', 'weights', 'last.pt')

model = YOLO(model_path)

threshold = 0.0
class_name_dict = {0: 'Glass', 1: 'Metal', 2: 'Paper', 3: 'Plastic', 4: 'Trash'}

i = 1
while cap.isOpened():
    ret, frame = cap.read()
    if ret:
        results = model(frame)[0]
        boxes = results[0].boxes.xywh.cpu()
        clss = results[0].boxes.cls.cpu().tolist()
        names = results[0].names
        confs = results[0].boxes.conf.float().cpu().tolist()

        for box, cls, conf in zip(boxes, clss, confs):
            x1, y1, x2, y2 = box
            score = conf  # probability of each bounding box
            class_id = cls
            if score > threshold:
                name = class_name_dict[int(class_id)] + ' ' + str(round(score, 2))
                cv2.rectangle(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0, 255, 0), 4)
                cv2.putText(frame, name.upper(), (int(x1), int(y1 - 10)),
                            cv2.FONT_HERSHEY_SIMPLEX, 1.3, (0, 255, 0),
                            3, cv2.LINE_AA)

        cv2.imshow('frame', frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

    print(i)
    i = i + 1
```

Hope this helps! Let me know if you have any additional questions.
Thanks
