### ISSUE TITLE
Query about yolo license 

### ISSUE THREAD

**Issue by nishanth-cn** [ultralytics/ultralytics#5349]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi 

I was going through AGPL license. After reading i have a small doubt.
Do I need to declare by entire project open source, If I want to just use a yolo model + opencv for commercial purpose and distribution. Also I am not doing any changes to source code or datasets.

Thanks
Nishanth

**Comment by glenn-jocher** [comment]
@nishanth-cn thank you for reaching out and for your interest in using Ultralytics' models.

Yes, any project that incorporates Ultralytics models, architecture, or code, whether modified or not, requires open-sourcing under the AGPL license. This means that if you're using a YOLO model from Ultralytics in your project and distributing it for commercial purposes, you are obligated to make the entire project open-source, even if you haven't made any changes to the original code or datasets.

I understand licensing can be complex, so I highly recommend consulting with legal counsel to ensure full compliance with AGPL and any other relevant licenses, especially when considering commercial applications.

**Comment by nishanth-cn** [comment]
Thank you very much @glenn-jocher

**Comment by glenn-jocher** [comment]
@nishanth-cn you're welcome! I'm glad that I could assist you. If you have any more questions or issues related to YOLOv8, please don't hesitate to reach out. The YOLO community and the Ultralytics team are always here to help. Happy coding!
