### ISSUE TITLE
Discussion of IoU based matching 

### ISSUE THREAD

**Issue by yermandy** [ultralytics/ultralytics#5351]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Well. I feel the need to reopen the discussion concerning #4708 

First, I am sorry for being so intrusive but it is still not the correct implementation. Second, I wrongly swapped function outputs which means that the results I was getting should be wrong. So, instead of
``` python
labels_idx, detections_idx = scipy.optimize.linear_sum_assignment(cost_matrix, maximize=True)
valid = cost_matrix[labels_idx, detections_idx] > 0
if valid.any():
    correct[detections_idx[valid], i] = True
```
there should be:
``` python
row_indices, column_indices = scipy.optimize.linear_sum_assignment(cost_matrix, maximize=True)
valid = cost_matrix[row_indices, column_indices] > 0
if valid.any():
    correct[row_indices[valid], i] = True
```

What I said here https://github.com/ultralytics/ultralytics/pull/4708#issuecomment-1704328057 is wrong, and the Hungarian algorithm that maximizes the sum of IoUs for a given threshold can in principle swap its decision. To verify, there is the simplest example which uses a 3x2 matrix (3 labels and 2 detections). I wrote a code that shows that it can change its decision for other IoU thresholds:

``` python
import numpy as np
from scipy.optimize import linear_sum_assignment

iou = np.asarray(
    [
        [0.1, 0.5],
        [0.5, 0.9],
        [0.2, 0.3],
    ]
)

thresholds = np.linspace(0, 1, 11)

correct = np.full((iou.shape[0], 11), np.nan)

print()
print(iou)
print()

for i, threshold in enumerate(thresholds):
    matrix = (iou >= threshold) * iou
    if matrix.any():
        row_indices, col_indices = linear_sum_assignment(matrix, maximize=True)
        costs = matrix[row_indices, col_indices]
        valid = costs > 0
        print("cost:", costs.sum(), f" for θ: {threshold:.1f}")
        if valid.any():
            row_indices = row_indices[valid]
            col_indices = col_indices[valid]
            correct[row_indices, i] = col_indices
    else:
        print("cost:", 0.0, f" for θ: {threshold:.1f}")

idx_to_letter = {0: "A", 1: "B", 2: "C", 3: "D"}

print()
print("θ:", thresholds)
print()
# print(correct)

for i, c in enumerate(correct):
    print(f"{idx_to_letter[i]}: {c}")

print()
```

For lazy, there is an output:

<img width="378" alt="Screenshot 2023-10-12 at 17 14 30" src="https://github.com/ultralytics/ultralytics/assets/39454881/29be5ddb-7707-4c3f-a15b-f6c955d7b868">

Fourth, this matching changes statistics a lot compared to cocoeval. The easiest way to see what is going on would be to manually examine image matches where those items (where there are just a few instances) are present:

* matches by IoU from main branch
```
               toaster       5000          9      0.593      0.222      0.433      0.311
            hair drier       5000         11          1          0    0.00606    0.00425
```

* matches by Hungarian:
```
               toaster       5000          9          1      0.428      0.508      0.347
            hair drier       5000         11          1          0          0          0
```

**Comment by glenn-jocher** [comment]
@yermandy thank you for your detailed analysis and observations regarding the IoU-based matching and the Hungarian algorithm implementation, and for sharing your findings about the statistics differences with the mAP calculation.

In response to the points brought up:

1. The corrections to the "scipy.optimize.linear_sum_assignment" function outputs swapping certainly make sense. The proper indexing should be applied consistently throughout the code.

2. Concerning the Hungarian algorithm changing decision for different IoU thresholds, I understand your observation. Indeed, based on threshold variations, the algorithm might prioritize different matches. This variability might impact the mAP calculation, especially for thresholds closer to 1. We've seen this behavior in your provided examples and would consider this during updates or revisions to the matching logic.

3. As for the difference in mAP scores between cocoeval and our implementation, it is expected due to the inherent differences in the matching techniques used. The Hungarian algorithm optimizes global rather than local IoU sum, which might lead to different matchings for some objects in some situations. These differences can affect low instance categories more noticeably.

We greatly appreciate your keen attention to detail. Understanding these subtleties can be complicated, and we truly value the effort you've taken to provide this description to the community. This makes a profound contribution to the further improvement of the YOLOv8 model for better detection and analysis of objects.

**Comment by yermandy** [comment]
@glenn-jocher thank you for confirming my hypothesis, this is exactly what I wanted to hear:

> The Hungarian algorithm optimizes global rather than local IoU sum, which might lead to different matchings for some objects in some situations

I am interested in specific cases where it happens in practice. I will investigate it and will try to conclude my findings. For now, there is a synthetic case from my previous code comparing the two approaches:

``` python
import numpy as np
from scipy.optimize import linear_sum_assignment

iou = np.asarray(
    [
        [0.1, 0.5],
        [0.5, 0.9],
        [0.2, 0.3],
    ]
)


print()
print(iou)
print()


def matching(iou, thresholds, hungarian=True):
    n_thresholds = len(thresholds)

    correct = np.full((iou.shape[0], n_thresholds), np.nan)

    for i, threshold in enumerate(thresholds):
        if hungarian:
            cost_matrix = (iou >= threshold) * iou
            if cost_matrix.any():
                row_indices, col_indices = linear_sum_assignment(cost_matrix, maximize=True)
                costs = cost_matrix[row_indices, col_indices]
                valid = costs > 0
                print("cost:", costs.sum(), f" for θ: {threshold:.1f}")
                if valid.any():
                    row_indices = row_indices[valid]
                    col_indices = col_indices[valid]
                    correct[row_indices, i] = col_indices
            else:
                print("cost:", 0.0, f" for θ: {threshold:.1f}")

        else:
            matches = np.nonzero(iou >= threshold)
            matches = np.array(matches).T
            if matches.shape[0]:
                if matches.shape[0] > 1:
                    matches = matches[iou[matches[:, 0], matches[:, 1]].argsort()[::-1]]
                    matches = matches[np.unique(matches[:, 1], return_index=True)[1]]
                    # matches = matches[matches[:, 2].argsort()[::-1]]
                    matches = matches[np.unique(matches[:, 0], return_index=True)[1]]

                costs = iou[matches[:, 0], matches[:, 1]]
                print("cost:", costs.sum(), f" for θ: {threshold:.1f}")
                correct[matches[:, 1].astype(int), i] = matches[:, 0]
            else:
                print("cost:", 0.0, f" for θ: {threshold:.1f}")

    return correct


n_thresholds = 11
thresholds = np.linspace(0, 1, n_thresholds)

correct = matching(iou, thresholds, hungarian=True)
print()
correct = matching(iou, thresholds, hungarian=False)

print()
print("thr θ:", thresholds)
print()
# print(correct)

for i, c in enumerate(correct):
    print(f"row {i}: {c}")

print()
```

and outputs:


``` python
[[0.1 0.5]
 [0.5 0.9]
 [0.2 0.3]] 

----------------------------------------------------
Hungarian:
cost: 1.1  for θ: 0.0
cost: 1.1  for θ: 0.1
cost: 1.1  for θ: 0.2
cost: 1.0  for θ: 0.3
cost: 1.0  for θ: 0.4
cost: 1.0  for θ: 0.5
cost: 0.9  for θ: 0.6
cost: 0.9  for θ: 0.7
cost: 0.9  for θ: 0.8
cost: 0.9  for θ: 0.9
cost: 0.0  for θ: 1.0

    θ: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ] 

row 0: [nan nan nan  1.  1.  1. nan nan nan nan nan]
row 1: [ 1.  1.  1.  0.  0.  0.  1.  1.  1.  1. nan]
row 2: [ 0.  0.  0. nan nan nan nan nan nan nan nan]


----------------------------------------------------
Current:
cost: 0.5  for θ: 0.0
cost: 0.5  for θ: 0.1
cost: 0.5  for θ: 0.2
cost: 0.5  for θ: 0.3
cost: 0.5  for θ: 0.4
cost: 0.5  for θ: 0.5
cost: 0.9  for θ: 0.6
cost: 0.9  for θ: 0.7
cost: 0.9  for θ: 0.8
cost: 0.9  for θ: 0.9
cost: 0.0  for θ: 1.0

    θ: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ] 

row 0: [ 1.  1.  1.  1.  1.  1. nan nan nan nan nan]
row 1: [nan nan nan nan nan nan  1.  1.  1.  1. nan]
row 2: [nan nan nan nan nan nan nan nan nan nan nan]
```

**Comment by yermandy** [comment]
Okay, I am sorry for the confusion here, the current implementation is correct, I just realized that my **cost_matrix** (**iou** matrix) was not Labels x Detections but Detections x Labels, this is why I incorrectly inserted results in the **correct** matrix.

**Comment by glenn-jocher** [comment]
@yermandy thank you for your update and no problem at all. Mistakes happen and it's great that you figured out the issue in your cost_matrix dimensions. The correct organization should indeed be Labels x Detections for your IoU matrix in the context of the Hungarian algorithm implementation in YOLOv8. In your correct matrix, the row index refers to the ground truth (Labels) and the column index refers to the Detections, resulting in the correct matches. Your understanding and contributions are much appreciated. Feel free to reach out if you have any more questions or insights!
