### ISSUE TITLE
AttributeError: 'Results' object has no attribute 'plot

### ISSUE THREAD

**Issue by Usman2217** [ultralytics/ultralytics#5353]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i have trained my v8 model on colab and trying to make a web app of it for detection but getting this error.Following is my code
import PIL

import streamlit as st
from ultralytics import YOLO

#  path of weight file
model_path = '/content/datasets/Damaged_Cars-1/runs/detect/train/weights/best.pt'

# Setting page layout
st.set_page_config(
    page_title="Object Detection using YOLOv8",  # Setting page title
    page_icon="🤖",     # Setting page icon
    layout="wide",      # Setting layout to wide
    initial_sidebar_state="expanded"    # Expanding sidebar by default
)

# Creating sidebar
with st.sidebar:
    st.header("Image/Video Config")     # Adding header to sidebar
    # Adding file uploader to sidebar for selecting images
    source_img = st.file_uploader(
        "Choose an image...", type=("jpg", "jpeg", "png", 'bmp', 'webp'))

    # Model Options
    confidence = float(st.slider(
        "Select Model Confidence", 25, 100, 40)) / 100

# Creating main page heading
st.title("Object Detection using YOLOv8")

# Creating two columns on the main page
col1, col2 = st.columns(2)

# Adding image to the first column if image is uploaded
with col1:
    if source_img:
        # Opening the uploaded image
        uploaded_image = PIL.Image.open(source_img)
        # Adding the uploaded image to the page with a caption
        st.image(source_img,
                 caption="Uploaded Image",
                 use_column_width=True
                 )

try:
    model = YOLO(model_path)
except Exception as ex:
    st.error(
        f"Unable to load model. Check the specified path: {model_path}")
    st.error(ex)

if st.sidebar.button('Detect Objects'):
    res = model.predict(uploaded_image,
                        conf=confidence
                        )
    boxes = res[0].boxes
    res_plotted = res[0].plot()[:, :, ::-1]
    with col2:
        st.image(res_plotted,
                 caption='Detected Image',
                 use_column_width=True
                 )
        try:
            with st.expander("Detection Results"):
                for box in boxes:
                    st.write(box.xywh)
        except Exception as ex:
            st.write("No image is uploaded yet!")
            if anyone can help mw with it please.

**Comment by glenn-jocher** [comment]
@Usman2217 hello,

Thank you for reaching out and providing a detailed description of your issue.

The error message `'Results' object has no attribute 'plot'` usually means you're trying to call a method that doesn't exist in the `Results` object. In the Ultralytics YOLOv8 implementation, the `Results` object does not have a `plot` method, hence why you're encountering an `AttributeError`.

The `Results` object returned by the `model.predict()` method in YOLOv8 includes the predicted bounding boxes, labels, and confidence scores, among others. In your case, you are trying to access predicted bounding boxes using `res[0].boxes`, which is correct as `boxes` attribute exists.

For displaying detection results on the image, you might need to manipulate the image and bounding boxes manually. Python libraries like OpenCV or PIL could be used for this. These libraries allow you to draw boxes, text, etc., on your images. 

I hope this addresses your query. Let us know if you need any further assistance.

Best,
The Ultralytics Team

**Comment by glenn-jocher** [comment]
@lms-mt hey there! 😊

We're really sorry you're facing issues with the YOLOv8 project. It seems like there might have been some updates that we missed reflecting in the documentation. Thanks for bringing this to our attention! 🙏

For the error you're encountering, could you please try the following adjustment? Instead of using a `plot` method (which isn't available), you can visualize the results using libraries like OpenCV or PIL. Here's a quick example using OpenCV:

```python
import cv2
from ultralytics import YOLO

# Load your model
model = YOLO('path/to/your/model.pt')

# Predict
results = model.predict('path/to/your/image.jpg')

# Draw boxes on the image
for box in results[0].boxes:
    x1, y1, x2, y2 = map(int, box.xyxy)
    cv2.rectangle(results.imgs[0], (x1, y1), (x2, y2), (255, 0, 0), 2)

# Display the image
cv2.imshow('Detected Image', results.imgs[0])
cv2.waitKey(0)
cv2.destroyAllWindows()
```

We'll make sure to update our documentation ASAP to avoid such confusion in the future. If you have any more feedback or need further assistance, feel free to reach out. We're here to help!
