### ISSUE TITLE
Enable training for Mac M1

### ISSUE THREAD

**Issue by NamanMakkar** [ultralytics/ultralytics#536]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Was trying to run this on Mac M1 GPU and tried changing the device from 'cuda' to 'mps' in trainer.py but it doesn't recognise my GPU and still trains on the CPU instead.  I was wondering if there was anyway to fix this since there is no way to carry out FP16 training on Mac M1 as far as I am aware and I would have to change a lot of the code to successfully run it. Could you please look into this.

**Comment by Yusepp** [comment]
Half flag is set true by default maybe if you set it false the model will run FP32

**Comment by NamanMakkar** [comment]
No the half flag is set to False by default

**Comment by James4Ever0** [comment]
Mine currently raise exceptions instead, pytorch version: `1.13.0.dev20220824`

It says: `The operator 'aten::_slow_conv2d_forward' is not current implemented for the MPS device.`

**Comment by Yusepp** [comment]
> Mine currently raise exceptions instead, pytorch version: `1.13.0.dev20220824`
> 
> It says: `The operator 'aten::_slow_conv2d_forward' is not current implemented for the MPS device.`

[Found this stackoverflow post](https://stackoverflow.com/questions/72416726/how-to-move-pytorch-model-to-gpu-on-apple-m1-chips) where they solve it by setting the environment variable PYTORCH_ENABLE_MPS_FALLBACK=1

**Comment by pderrenger** [comment]
@Yusepp hi there! It seems like the issue you're facing is related to certain operations not being currently implemented for the MPS device on Apple Silicon. Setting the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` may resolve this issue for you. This allows PyTorch to fallback to an alternative implementation when certain operations are not implemented for the MPS device. Give it a try and see if it resolves the problem for you! If you have any further questions or encounter any other issues, feel free to ask. Good luck!

**Comment by glenn-jocher** [comment]
Hi @pderrenger! 👋 It looks like you're encountering limitations with the MPS backend in PyTorch. Indeed, setting `PYTORCH_ENABLE_MPS_FALLBACK=1` as an environment variable might help bypass the missing ops for MPS. This tells PyTorch to use CPU implementations when GPU ones are unavailable. Give this workaround a shot and let us know how it goes! If you run into more hurdles, we're here to help. Happy coding! 🚀

**Comment by johnnynunez** [comment]
M1 Max it has no float64 support and neither fp16. Use fp32
