### ISSUE TITLE
Is it possible to detect variable number of key points from an object? 

### ISSUE THREAD

**Issue by sounok1234** [ultralytics/ultralytics#5364]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is it possible to custom train a key points detection model that detects variable number of key-points for a single class?

**Comment by glenn-jocher** [comment]
@sounok1234 yes, it is indeed possible to train a model to detect a varying number of keypoints for a single class using the YOLOv8 suite. The key point detection task in YOLOv8 is designed to detect specific points in an image or frame, which can be used to track movement or to estimate pose.

To custom train such a model, you would first need to prepare your dataset with the appropriate annotations for the variable key points you want to detect on your objects. The annotations should include the coordinates of each key point for each object of interest in your image. 

Once your data is prepared, you can use the 'Train' mode of YOLOv8 to train a model on this custom dataset. You should consider experimenting with different hyperparameters for optimal results in detecting variable keypoints.

During validation or prediction, the model should be able to detect these keypoints in new images or video frames, regardless of the number of keypoints present. Remember, the performance of the model greatly depends on the quality and diversity of the training data. 

It's quite an interesting problem you're working on; best of luck with your project! Don't hesitate to reach out if you have more questions regarding this.

**Comment by hnsywangxin** [comment]
@glenn-jocher amazing work, if I want to detect keypoints like this image:https://www.sylvain-ard.fr/temp/feuille.png
,my keypoints is arbitrary in different image,maybe 10 points,maybe 9 points or maybe 17 points, etc. How should I modify a configuration file or code, can you give me advice?
thank you very much

**Comment by sounok1234** [comment]
Hey @hnsywangxin one approach that could work: 

Estimate the highest number of points (N) that you may want to detect from an image and set that as your kpt_shape ([N, 2] or [N, 3]) in your config file. And for every training image, you can set the labels for residual points (N - n, n being the number of keypoints for that particular training image) to 0. 

Maybe @glenn-jocher will have a better solution than this.

**Comment by hnsywangxin** [comment]
@sounok1234 I will try this method , but I'm suspect that the results may not be very good because the numbers of points are quite large difference.
thank you very much

**Comment by sounok1234** [comment]
@hnsywangxin you could check out this repo too: https://github.com/tlpss/keypoint-detection. Seems to suit your purpose better.

**Comment by hnsywangxin** [comment]
> @hnsywangxin you could check out this repo too: https://github.com/tlpss/keypoint-detection. Seems to suit your purpose better.
Thank you so much, it seems like that repository is indeed suitable for my task. I will study it thoroughly. Best wishes!

**Comment by glenn-jocher** [comment]
You're welcome, @sounok1234! I'm glad that the repository mentioned could be a good fit for your task. Definitely, take your time to explore it. I'm confident that you'll be able to adapt it to your specific needs. If you have any more questions or need assistance as you continue to navigate this, don't hesitate to reach out. Best of luck with your project!

**Comment by hnsywangxin** [comment]
@sounok1234 @glenn-jocher hello,I have experimented with [keypoint-detection](https://github.com/tlpss/keypoint-detection) and yolo-v8, but the results were not satisfactory.my keypoints is arbitrary in different image,I use yolo which result is the worst, and the ap=0 always:

**Comment by glenn-jocher** [comment]
Hello @hnsywangxin, 

It seems like you've made progress with the keypoint-detection experiment, that's great!

Regarding the YOLOv8 model, it can be a bit challenging to pinpoint the exact issue without more information, but a few potential areas to look into could be the size of your dataset, the diversity of the data, and the hyperparameters.

Your dataset size of around 2000 images might be a bit small for the complexity of the task. If possible, try increasing the size of your dataset and incorporate more diversity in terms of lighting conditions, different room types, camera angles, etc.

In terms of hyperparameters, you may need to experiment with these to optimize your model's performance. A different learning rate, a different optimizer, or even a different model architecture might yield better results.

Additionally, keep in mind that YOLOv8 is primarily an object detection model and the keypoint detection might not be as robust as specialized keypoint detection models for tasks with a variable number of keypoints.

Lastly, make sure that your annotation process doesn't have any errors and your labels are in the correct format expected by YOLOv8.

Keep iterating and experimenting. Best of luck!

**Comment by sunmingqi-1** [comment]
> @glenn-jocher令人惊叹的工作，如果我想检测像这样的图像的关键点： ，我只检测单个类，即叶子，但我的关键点在不同的图像中是任意的，可能是 10 点，可能是 9 点，也可能是 17 点等。我应该如何修改一个配置文件或代码，你能给我建议吗？ 非常感谢 <img alt="图像" width="300" src="https://private-user-images.githubusercontent.com/18531174/275781531-a60866d1-f634-4927-872a-a7b1570e1d98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDIzOTQsIm5iZiI6MTcwNDEwMjA5NCwicGF0aCI6Ii8xODUzMTE3NC8yNzU3ODE1MzEtYTYwODY2ZDEtZjYzNC00OTI3LTg3MmEtYTdiMTU3MGUxZDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA5NDEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNTJlNTBjOWE0MDkxMDkwOGE5OTNkZWQwNWQzNGVmNTU5MzQ5NDY2OGI2NzUxZDJiNDNmMThiMWU4NGE3Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0NtHFn7TTbX0tk-O_19k77tNhpyvko-qPkI2tmNJEwo">

I also recently encountered the need to "solve a single class of variable number of critical point detection", which is very similar to your task, how did you do it?

**Comment by glenn-jocher** [comment]
@sunmingqi-1 hello! For detecting a variable number of keypoints in YOLOv8, you might consider setting the maximum number of keypoints you expect to detect as your model's output dimension. During training, label the keypoints that are present and use a consistent method to handle images with fewer keypoints, such as padding the absent keypoints with a specific value that your model can learn to ignore.

Remember, YOLOv8 is primarily designed for object detection, and while it can be adapted for keypoint detection, achieving optimal results for variable keypoints might require significant customization or even a different approach or architecture more suited for this specific task.

For more detailed guidance on model configuration and training, please refer to our documentation at https://docs.ultralytics.com. Keep experimenting and fine-tuning! 🚀

**Comment by wzfovo** [comment]
> @sounok1234 @glenn-jocher你好，我尝试过[关键点检测](https://github.com/tlpss/keypoint-detection)和yolo-v8，但结果不太令人满意。我的关键点在不同的图像中是相同的，我使用yolo，结果最差，并且poseap总是= 0 （我的火车imgs编号大约2000）： 我的yolo结果是这样的：并且 我已经可视化了这个标记的img，它的说明注释是正确的： <img alt="图像" width="1381" src="https://private-user-images.githubusercontent.com/18531174/278594092-4b371869-e4f6-4f87-bc1d-b750bbf74369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyOTcxNDMsIm5iZiI6MTcxMjI5Njg0MywicGF0aCI6Ii8xODUzMTE3NC8yNzg1OTQwOTItNGIzNzE4NjktZTRmNi00Zjg3LWJjMWQtYjc1MGJiZjc0MzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA2MDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhOWU5NGVmZmU0N2FiOGZkMGRlZGVjYzZhM2RmNjMwODgwYzU4ZmU0N2I2OWVlMTkxNGFhMzRkNGUzNjBkMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5ceTFVAPHDf_J0g7E76RHrW1yiQ7UfMdzcioCnbXnss"> <img alt="图像" width="222" src="https://private-user-images.githubusercontent.com/18531174/278594308-777ac5a9-ddde-441b-b6e6-4ee73b3cfe35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyOTcxNDMsIm5iZiI6MTcxMjI5Njg0MywicGF0aCI6Ii8xODUzMTE3NC8yNzg1OTQzMDgtNzc3YWM1YTktZGRkZS00NDFiLWI2ZTYtNGVlNzNiM2NmZTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA2MDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjM2I5OWFkYjIyOTQxNjRlMTcyYmE1YTBiZjE4MDdjYzBlZGIyY2UwODdlMDI3M2Q1ZjM5NzJiZmNlNDczNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WY47b9WaWR36GeZmckLxQ6GbCkKDdaiF8BnkVuW0jLs"> <img alt="图像" width="236" src="https://private-user-images.githubusercontent.com/18531174/278594911-463e8b60-ca6f-4439-9129-cc0a22a17341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyOTcxNDMsIm5iZiI6MTcxMjI5Njg0MywicGF0aCI6Ii8xODUzMTE3NC8yNzg1OTQ5MTEtNDYzZThiNjAtY2E2Zi00NDM5LTkxMjktY2MwYTIyYTE3MzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA2MDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NGY1MDczMWIwYWM4YjVlZjI2MjA3ZTE4NWM1OTIxMTRmODcxMGE2ZTIxZTQwMTQzYWI3ZTA5YTkwMGQ1YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IYCriEmYBVjK5UOQnRqIVgQ79rfZmG9Az6A5X7WLock"> <img alt="图像" width="255" src="https://private-user-images.githubusercontent.com/18531174/278595348-e9ac0afa-9a4b-4670-8a77-17048d59dbbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyOTcxNDMsIm5iZiI6MTcxMjI5Njg0MywicGF0aCI6Ii8xODUzMTE3NC8yNzg1OTUzNDgtZTlhYzBhZmEtOWE0Yi00NjcwLThhNzctMTcwNDhkNTlkYmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA2MDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2YzEwNGUxYzNiMzFlYWQxYzM0NGUzMTUwMDkzMTJkZjE3NzYzMmMxNDA1Zjk0OTg1OGVhOWNhNTFmYzNjNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1CdVYJXpkq5mak4OILeTuWrAeEkiO2kumeLMRwB3-z8">
> 
> 我的关键点检测结果相对较好。 是什么导致了我的 yolo 问题？我的目标是检测房间墙壁的角落。谢谢 <img alt="图像" width="233" src="https://private-user-images.githubusercontent.com/18531174/278596563-c9ac97b2-6ce8-402c-990d-ed06931b5b6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyOTcxNDMsIm5iZiI6MTcxMjI5Njg0MywicGF0aCI6Ii8xODUzMTE3NC8yNzg1OTY1NjMtYzlhYzk3YjItNmNlOC00MDJjLTk5MGQtZWQwNjkzMWI1YjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA2MDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMTdhYmYyMzcyNTAyYTE3NTEwMjhiYWM3MTM2MjdiNmJjYzQyNGJmMTFhMmIxMTQ5NTE3ZjBlOTI1MGE0YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ApeFkoJTtMMxWtzU4opHmMtCp5TiGD1AlnBSyTwOSBE"> <img alt="图像" width="242" src="https://private-user-images.githubusercontent.com/18531174/278597186-bce6e112-780e-4aa4-940c-bab85924efc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyOTcxNDMsIm5iZiI6MTcxMjI5Njg0MywicGF0aCI6Ii8xODUzMTE3NC8yNzg1OTcxODYtYmNlNmUxMTItNzgwZS00YWE0LTk0MGMtYmFiODU5MjRlZmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA2MDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMzgyNDQyMzFlMmY2NmU4YTcwOGQwNGE3OGM2MGJkMmE3MmJiYWIxOGE3ODNkNWJmY2E2MmYxZmNmMTIzODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cQKFJMslpFFEtzhPCOVISCeTcncxdGUuaqroyj_1zDA">

What method did you use to detect this feature point? I'm working on a similar project.

**Comment by glenn-jocher** [comment]
Hey @wzfovo, it appears you've delved deep into both the [keypoint-detection](https://github.com/tlpss/keypoint-detection) repository and YOLOv8 for detecting keypoints. It's unfortunate to hear about the challenges you've encountered with YOLOv8, especially with the variability in the keypoints per image. For tasks with such unique requirements, achieving high accuracy might indeed require specialized approaches or tailored model configurations.

Your exploration into variable keypoint detection per image is certainly intriguing. If the off-the-shelf YOLOv8 model doesn't yield satisfactory results, consider these tweaks:
1. Ensure your dataset is diverse and robust enough to train the model effectively.
2. Experiment with adjusting the architecture or training process of YOLOv8 to better accommodate variable keypoints detection, like dynamically adjusting the output layer based on the maximum number of expected keypoints.

For the variability issue, focusing more on the keypoints-detection specific repository might offer better flexibility and accuracy due to its specialization in this area. Meanwhile, I'll highlight your findings and concerns to the team for further insights on adapting YOLOv8 more effectively for such unique tasks.

Sharing your annotations and a few sample images was a great move, ensuring that the labelling accuracy isn't the issue. If you're open to it, experimenting with different frameworks or seeking contributions from the community could unveil new approaches or refinements to your existing strategy. 

Keep up the innovative work, and please keep us posted on your progress! 🌟

**Comment by aleph17** [comment]
Hey, thank you everyone for above comments. It was very helpful for the project I am working on. Guys can you specify what tool you are using to annotate your images like this? I mean how are you annotating existing keypoints on the image and saving it  - while padding all absent features with a consistent value like (0,0)
