### ISSUE TITLE
Is it possible use on Darknet ?

### ISSUE THREAD

**Issue by hongu0603** [ultralytics/ultralytics#540]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want run yolov8 on Darknet, is it possible. If possible, how to change .pt to .weight and yaml to cfg, I have no idea now. thanks a lot

**Comment by AyushExel** [comment]
No it's not. Could you describe your use case with darknet?

**Comment by hongu0603** [comment]
The task (breast cancer detect ) before i was use yolov4 by Darknet, and now i want to use yolov8 replace yolov4

**Comment by knoppmyth** [comment]
Assuming you still have the dataset, retrain with YOLOv8. If memory serves (from when I experimented w/ YOLOv4), all you should need as a YAML file pointing to the location of your dataset and start the training.
`path: /usr/src/datasets/Hand/  # dataset root dir
train:
    - V1/images/train  # train images (relative to 'path')
    - V2/images/train
val: V1/images/val  # val images (relative to 'path')
test:  # test images (optional)

# Classes
nc: 1  # number of classes
names: ['Hand']  # class names`

**Comment by hongu0603** [comment]
@knoppmyth Sorry i can't really understand, in Darknet we need .cfg and .weight but if I retrain with YOLOv8 i just get .pt, i dosen't need to do any transform ?

**Comment by knoppmyth** [comment]
@hongu0603 You cannot take a YOLOv4 cfg and weights and run them with YOLOv8. If you want to use YOLOv8, you need to train a new model with it.

**Comment by AyushExel** [comment]
You can train any model with ultralytics repo. You can even train yolov4,v3 or even non-yolo model. You just have to prepare the cfg file properly. We'll add support for it soon.

**Comment by hongu0603** [comment]
@knoppmyth yes, i konw i need to train a new model.
@AyushExel  Thanks for reply, i know i nees to prepare the cfg file, i just no ida how to transform yaml file to cfg file
