### ISSUE TITLE
Issue with multi gpu training

### ISSUE THREAD

**Issue by suryan-s** [ultralytics/ultralytics#544]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

while setting up training for yolov8 for multi-GPU, I'm getting this error:
`Traceback (most recent call last):
  File "/opt/conda/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/conda/lib/python3.7/site-packages/ultralytics/yolo/configs/__init__.py", line 167, in entrypoint
    v = v.replace(" ", "").replace('')  # handle device=[0, 1, 2, 3]
TypeError: replace() takes at least 2 arguments (1 given)`

used CLI command: `!yolo task=detect mode=train model=yolov8m.pt data=dataset.yaml epochs=500 imgsz=640 device=\'0,1\'`

### Minimal Reproducible Example

'''
 `!yolo task=detect mode=train model=yolov8m.pt data=dataset.yaml epochs=500 imgsz=640 device=\'0,1\'`
'''

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by termlim** [comment]
I am having the same error message as well. Even when `cfg` argument is not set.
Either the `DEFAULT_CFG_PATH` is improperly being injected, or the default config file is invalid.
