### ISSUE TITLE
Using exported model

### ISSUE THREAD

**Issue by Wiqzard** [ultralytics/ultralytics#547]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In your docs it says "model.export(format=)  # TODO: "
However it seems to be already implemented. But if i try to use the exported model 
model = YOLO(example.engine) for prediction it spits out the error:

"----> 2 exported_model = YOLO(exported_path)
[/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/model.py](https://localhost:8080/#) in __init__(self, model, type)
     54 
     55         # Load or create new YOLO model
---> 56         {'.pt': self._load, '.yaml': self._new}[Path(model).suffix](model)
     57 
     58     def __call__(self, source=None, stream=False, verbose=False, **kwargs):
KeyError: ".engine'"

Is this an error on my side? Can I fix this somehow?

PS: Thank you for doing this amazing job. So far it helped me make great progress in my project.

**Comment by Wiqzard** [comment]
Implemented.

**Comment by Tyler-Do** [comment]
@Wiqzard I also got the same error. How did you fix it?

**Comment by Wiqzard** [comment]
> @Wiqzard I also got the same error. How did you fix it?

I think i used the predictor class (in yolo/engine/predictor.py) directly and used the setup_model method, which calls the autobackend class.

**Comment by Wiqzard** [comment]
> 
I think i used the predictor class (in yolo/engine/predictor.py) directly and used the setup_model method, which calls the autobackend class.
