### ISSUE TITLE
Docs: result instead of results

### ISSUE THREAD

**Issue by dmddmd** [ultralytics/ultralytics#549]
Just also without s in the docs below. 
See screenshot
(And thank You for  #524 )
![grafik](https://user-images.githubusercontent.com/33686690/213890297-baa6d8e9-5521-413c-9e9a-3e99137fed4e.png)

**Comment by pderrenger** [comment]
@dmddmd thank you for bringing this to our attention! We've noted the typo and will address it promptly in the documentation. Your feedback is greatly appreciated and helps us improve the quality of our resources. If you come across any other issues or have further suggestions, please feel free to let us know. Keep up the great collaboration! 😊
