### ISSUE TITLE
How to get the frame outputs of a detection (on a live stream)?

### ISSUE THREAD

**Issue by dmddmd** [ultralytics/ultralytics#551]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to show the output stream with the bounding boxes and labels and probabilities into a pyQTDesigner  window.

How can I get the frame outputs of the object detection on my camera livestream?

**Comment by prince0310** [comment]
@dmddmd For getting output frame you have add a pair of word during prediction `show = True`

**Comment by suryan-s** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> ### Question
> I want to show the output stream with the bounding boxes and labels and probabilities into a pyQTDesigner window.
> 
> How can I get the frame outputs of the object detection on my camera livestream?
> 
> ### Additional
> _No response_

Well I'm not sure about implementing this in QT but i have done it in a Flask project. You could use the below method:
`while cam.isOpened():
                    frame_counter += 1
                    start_time = time.perf_counter()
                    # 
                    #
                    # Your rest of the code 
                    # 
                    #
                    end_time = time.perf_counter()
                    fps = 1 / np.round(end_time - start_time, 3)
                    cv2.putText( input, f"FPS: {int(fps)}", (20, 450), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2, )
                    #  To your desired output
`
Before entering into the detection part, record the time into a variable 'start'. after detection do the same with another variable 'end'.  Do the math to get FPS as shown and hola printout into the stream!

**Comment by dmddmd** [comment]
but you are manually printing the predictions in your expected window. right?

**Comment by suryan-s** [comment]
> but you are manually printing the predictions in your expected window. right?

on the stream output window

**Comment by pderrenger** [comment]
@suryan-s yes, you can integrate object detection with YOLOv8 into a live camera stream and display the output with bounding boxes, labels, and probabilities in a pyQTDesigner window. You would need to continuously grab frames from the camera stream, perform object detection on each frame, and then display the processed frames with predictions in your pyQTDesigner window.

To achieve this, you can use the method mentioned earlier to obtain the frames from the live camera stream. Once you have each frame, you can apply YOLOv8 object detection to it and draw bounding boxes and labels on the frame. Finally, you can display the processed frames with predictions in your pyQTDesigner window.

The FPS can also be calculated and displayed on the live stream window as per the provided method.

Please let me know if you need further assistance with integrating YOLOv8 into your pyQTDesigner window!
