### ISSUE TITLE
Will TensorRT support be added?

### ISSUE THREAD

**Issue by lanyeeee** [ultralytics/ultralytics#552]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

In **yolov5**, I turn **model.pt** into **model.engine** via export.py, and then I just need to change the name from **model.pt** to **model.engine** when I load the model.  

But in **yolov8**, although I successfully generate model.engine, it fails when I try
```python
from ultralytics import YOLO
model = YOLO("yolov8s.engine")
```  

it seems yolov8 only support models in **.pt** format, will TensorRT support be added? Make it as easy to use as using .engine in yolov5.  
 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@lanyeeee yes support for this should be arriving in the next few weeks.
