### ISSUE TITLE
How to delimit the livestream frame on which object detection should be done?

### ISSUE THREAD

**Issue by dmddmd** [ultralytics/ultralytics#553]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to delimit the livestream frame on which object detection should be done? (in order to only get the relevant part, like zoomed in)
I tried it with cv2:```

 Capture1 = cv2.VideoCapture()

        Capture1.open(cameraNumber + 0 + cv2.CAP_DSHOW)
        Capture1.set(3,3840)
        Capture1.set(4,2160)
  results = model(source=Capture1, stream=True, save=True)
```
but that throws:

> AssertionError: Expected PIL/np.ndarray image type, but got <class 'cv2.VideoCapture'>

### Additional

**Comment by prince0310** [comment]
Expected PIL/np.ndarray image type, but got <class 'cv2.VideoCapture'> it shows you are not feeding the image try cv2.Videocapture(0) for webcam else the source of video

**Comment by dmddmd** [comment]
is there another way then using cv2 ?

**Comment by dmddmd** [comment]
I kindly want to ask again

> is there another way than using cv2 ?

**Comment by pderrenger** [comment]
@dmddmd you can use PyTorch's `torchvision` library to process the live stream frames for object detection. Here's a quick example of how you might use it:

```python
import torch
import torchvision.transforms as T
from torchvision import models, transforms
from PIL import Image

# Open the video capture
cap = cv2.VideoCapture(0)  # Or use the path to the video file

# Define the model and its transformations
model = models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
model.eval()
transform = T.Compose([T.ToTensor()])

# Loop through the live stream frames
while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Perform the object detection on the frame
    input_img = Image.fromarray(frame)
    input_tensor = transform(input_img)
    input_batch = input_tensor.unsqueeze(0)
    with torch.no_grad():
        output = model(input_batch)

    # Display the frame with detected objects
    # (add your visualization code here)
```

In this example, we use the `torchvision` library to create a transformation pipeline and process the live stream frames. We then feed the processed frame into a pre-trained object detection model.
