### ISSUE TITLE
Label map with default model (yolov8x.pt)

### ISSUE THREAD

**Issue by JakobStadlhuber** [ultralytics/ultralytics#554]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How is it possible to get the label of a found box `result.boxes.cls` returns the index of the label but there is no string value.

**Comment by JakobStadlhuber** [comment]
My current fix is a label map with the following dict. Important: YOLOv8 seems to have no `unlabeled` label therefore the index has to be incremented by one

**Comment by dmddmd** [comment]
it's `model.model.names `
(they will fix it in later versions to `model.names`, see #555 )

**Comment by glenn-jocher** [comment]
@JakobStadlhuber issue should be resolved in #566 by @AyushExel merged just now and scheduled for 8.0.15 deployment soon. Closing issue, but please let us know if this resolves your problem and if you have any more suggestions or bug report. Thanks!
