### ISSUE TITLE
Model.NAMES? How can I get the classes in Yolo8

### ISSUE THREAD

**Issue by jpinzonc** [ultralytics/ultralytics#555]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In yolov5 model.names prints the classes in the model. Where is this information in YoloV8?

**Comment by AyushExel** [comment]
Okay, we'll fix this. Right now .model is not exposed at the top level. You can do `model.model.names` for now and we'll fix this in the next release

**Comment by glenn-jocher** [comment]
@jpinzonc issue should be resolved in #566 by @AyushExel merged just now and scheduled for 8.0.15 deployment soon. Closing issue, but please let us know if this resolves your problem and if you have any more suggestions or bug report. Thanks!

**Comment by jpinzonc** [comment]
model.model.names will do. Thanks.

**Comment by pderrenger** [comment]
@jpinzonc you're welcome! If you have any more questions or need further assistance, feel free to ask. Happy to help!
