### ISSUE TITLE
Adding "Freeze layers" for transfer learning

### ISSUE THREAD

**Issue by evia1** [ultralytics/ultralytics#562]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I am trying to train yolov8 on a subset of COCO dataset, specifically on cars, buses, trucks and motorcycles.
I know that it is a good practice to train the model first when all the model's layers are frozen, except the last one, before training the whole model. however, there is no option to freeze layers, according to https://docs.ultralytics.com/cfg/
That feature exist on yolov5 (--freeze x)

Would be great if it added, similar to yolov5

Thanks!

Eviatar

### Use case

The feature will be used for  transfer learning
It will be used by anyone who wants to train yolo on a custom dataset.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@evia1 hi Eviatar,

Thanks for reaching out! In YOLOv8, the ability to freeze layers for transfer learning is indeed a useful feature. Currently, this functionality is not explicitly exposed in the configuration file as it is in YOLOv5.

I'll make sure to bring up your suggestion to the team for consideration and potentially add this feature to YOLOv8 in the future. In the meantime, you can achieve a similar effect by setting a higher learning rate for the last layer during training, effectively "unfreezing" only the last layer.

Let me know if you have any more questions or need further assistance!

Cheers!
Paula
