### ISSUE TITLE
How to get the predicted label/s name/s ?

### ISSUE THREAD

**Issue by dmddmd** [ultralytics/ultralytics#563]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to get the name of the label found (not only on the window, but in the code)

Currently, I am doing detection with ultralytics 8.0.14.

My first idea was to map the name by my own with `model.model.names` and
```
    for result in results: 
        boxes = result.boxes  # Boxes object for bbox outputs
        print(boxes)
        for box in boxes: #there could be more than one detection
            box=box.numpy()
            print(box[0]) 
            #print(box[0][5]) #index out of bounds
            #print(box[5])     #index out of bounds

```
The output is:

> [[        169         263         454         480     0.55015           0]]
> [[        169         263         454         480     0.55015           0]]

My idea was to get the 6th item in the list and map it to the label name).
But I couldn't unpack 'box', as You can see.

The predicted labels should be accessible out of the box, right?

**Comment by AyushExel** [comment]
@Laughing-q this should be possible right?

**Comment by AyushExel** [comment]
@dmddmd the boxes class is a wrapper around tensor. you can access the raw tensor directly by doing boxes.data..

**Comment by Laughing-q** [comment]
@dmddmd also you can use box.cls to access the predicted cls id.

**Comment by dmddmd** [comment]
thanks, `model.names.get(box.cls.item())`  meets my requirement

**Comment by dmddmd** [comment]
@gurselturkeri the answer is above, or what do You need exactly?

**Comment by gurselturkeri** [comment]
I run with this command: `yolo task=detect mode=predict model=yolov8n.pt source="0" format="onnx" show=True` and I dont know in which python file this class is published.

**Comment by dmddmd** [comment]
OK you're using the CLI
Maybe #375 helps

**Comment by gurselturkeri** [comment]
> OK you're using the CLI Maybe #375 helps

Yes but I would like to use with python script

**Comment by pderrenger** [comment]
@gurselturkeri to retrieve the class data as a string in the Python script, you can use the `model.names` attribute to reference the class names. You can access the class names by indexing `model.names` with the predicted class ID from the results.

Here's an example:

```python
from ultralytics import YOLO

model = YOLO("yolov8n.pt") 
results = model.predict(source="0")

for item in results.xyxy[0]:  # Iterate through the results objects
    class_id = item[-1]  # Get the class ID
    class_name = model.names[int(class_id)]  # Get the class name using class ID
    print(class_name)
```

This will allow you to retrieve the class data such as "person", "car", etc., as strings in your Python script.

**Comment by boritopalito** [comment]
> I just want to get class data like: _person, car, truck, dog_ as a string
> 
> **Python script:**
> 
> ```
> from ultralytics import YOLO
> 
> model = YOLO("yolov8n.pt") 
> results = model.predict(source="0")
> ```
> 
> **Output:**
> 
> ```
> 0: 480x640 1 person, 1 car, 7.1ms
> 0: 480x640 1 person, 1 car, 7.2ms
> 0: 480x640 1 person, 1 car, 7.1ms
> 0: 480x640 1 person, 1 car, 7.1ms
> 0: 480x640 1 person, 1 car, 7.1ms
> 0: 480x640 1 person, 7.9ms
> 0: 480x640 1 person, 7.1ms
> 0: 480x640 1 person, 1 car, 7.1ms
> 0: 480x640 1 person, 1 car, 7.1ms
> ```

Not sure if still relevant but I get the names by doing this:


```
from ultralytics import YOLO

model = YOLO("best.pt")  # path to model file
results = model('test1000.png', show=True)

for result in results:
    for box in result.boxes:
        class_id = int(box.data[0][-1])
        print(model.names[class_id])

```

**Comment by noorkhokhar99** [comment]
for results in results.pred[0]:
                   ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'pred'

 I am getting an error.

**Comment by noorkhokhar99** [comment]
**full code** 

from ultralytics import YOLO

model = YOLO("yolov8n.pt") 
results = model.predict(source=0,show=True)

for box in results.xyxy[0]:
    class_name = model.names[int(box[5])]  # Index with the class ID.
    print(class_name). 


error 

 for box in results.xyxy[0]:
               ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'xyxy'

**Comment by glenn-jocher** [comment]
@noorkhokhar99 i apologize for the confusion. To access the predicted class names from the `results`, you should iterate over the `results` list directly, as it contains the predictions. Here's the correct way to do it:

```python
for pred in results:
    for *xyxy, conf, cls in pred:  # Unpack the prediction object
        class_name = model.names[int(cls)]  # Retrieve the class name using the class ID
        print(class_name)
```

This will print the class names for each detection in your results.

**Comment by noorkhokhar99** [comment]
> @noorkhokhar99 i apologize for the confusion. To access the predicted class names from the `results`, you should iterate over the `results` list directly, as it contains the predictions. Here's the correct way to do it:
> 
> ```python
> for pred in results:
>     for *xyxy, conf, cls in pred:  # Unpack the prediction object
>         class_name = model.names[int(cls)]  # Retrieve the class name using the class ID
>         print(class_name)
> ```
> 
> This will print the class names for each detection in your results.

this is not work   


I am using this one this code works for object names only 


from ultralytics import YOLO
import cv2
import torch
import numpy as np

model = YOLO('yolov8n.pt')
results = model(source=0, show=True)


counts = {}
for result in results:
    boxes = result.boxes.cpu().numpy()
    for box in boxes:
        cls = int(box.cls[0])
        if not cls in counts.keys():
            counts[cls] = 1
        else:
            counts[cls] += 1
for key in counts.keys():
    print(model.names[key] + " : " + str(counts[key]))

**Comment by glenn-jocher** [comment]
@noorkhokhar99 i'm glad to hear you've found a solution that works for you. To iterate over the results and count the occurrences of each class, your approach is correct. You're using the `.boxes` attribute and then accessing the class IDs to count them. Keep up the good work, and if you have any more questions or need further assistance, feel free to ask. Happy coding! 🌟

**Comment by Georgin-joseph** [comment]
yolo = YOLO('best.pt')  
            image = Image.open(filepath)
            filename = os.path.basename(filepath)  # Extract filename from the filepath
            detections = yolo.predict(image, save=True)
            
            nohelmet_detected = False
            
            for i, r in enumerate(detections):
                im_array = r.plot()  # plot a BGR numpy array of predictions
                im = Image.fromarray(im_array[..., ::-1])
                predicted_image_path = os.path.join('predicted_images', filename)
                im.save(predicted_image_path)  # save image
                
                if re.search('nohelmet', r.names):  # Use regular expression for better matching
                    nohelmet_detected = True
                    break
                    
           if nohelmet_detected:
                print("No helmet detected in the image:", filename)
            else:
                print("Helmet detected in the image:", filename)
                
               i want to check the nohelmet is label in the predicted _images

**Comment by glenn-jocher** [comment]
@Georgin-joseph to access the predicted class labels and their corresponding names, you can use the `cls` attribute of the `Boxes` object, which contains the class indices. Then, you can map these indices to the class names using the `names` attribute of the `Results` object. Here's how you can do it:

```python
from ultralytics import YOLO

# Load a pretrained YOLOv8 model
model = YOLO('yolov8n.pt')

# Perform object detection on an image
results = model('https://ultralytics.com/images/bus.jpg')

# Iterate over the results
for result in results:
    boxes = result.boxes  # Boxes object for bbox outputs
    class_indices = boxes.cls  # Class indices of the detections
    class_names = [result.names[int(cls)] for cls in class_indices]  # Map indices to names
    print(class_names)
```

This will print the names of the detected classes for each bounding box in the image. The `result.names` attribute contains the list of class names that the model can predict, and `boxes.cls` provides the indices of the predicted classes for each detection.

**Comment by lycalague20** [comment]
Hello @glenn-jocher, could you also help me get the class label. In my project, I get first the position of the detected object and I want to specify what class is in that specific position. I hope you'll help me. Thank you.
This is my code:
`from ultralytics.utils.plotting import Annotator
from ultralytics import YOLO
import cv2
import serial
import time

# Load a pre-trained or fine-tuned YOLO model
model = YOLO('wpp.pt')

# Access the webcam
cap = cv2.VideoCapture(0)

# Specify the directory to save the images
save_directory = '/home/group2/thesis/yolov8/myvenv/Captured Images/'

# Initialize counter for filename indexing
image_counter = 1

# Define the width and height of the image
image_width, image_height = 640, 480


# Flag to determine whether to show live feed or captured image
show_live_feed = True

while True:
    if show_live_feed:
        # Capture a frame from the webcam only if live feed is active
        ret, frame = cap.read()

    # Display live feed or captured image
    if show_live_feed:
        cv2.imshow('Feed', frame)
    else:
        cv2.imshow('Captured Image', captured_frame)

    # Check for key press
    key = cv2.waitKey(1) & 0xFF

    # Capture an image if the spacebar is pressed
    if key == ord(' '):  # Spacebar key
        # Construct filename with numerical index
        filename = save_directory + 'captured_image_{}.jpg'.format(image_counter)

        # Save the captured image with the filename
        cv2.imwrite(filename, frame)
        print("Image captured and saved as:", filename)

        # Process the captured image with YOLO
        source = cv2.imread(filename)
        results = model(source)

        # Extract results
        fruit_positions = []

        for i, box in enumerate(results[0].boxes.xyxy.cpu()):
            x_min, y_min, x_max, y_max = box.tolist()
            # Draw bounding box on the image
            cv2.rectangle(frame, (int(x_min), int(y_min)), (int(x_max), int(y_max)), (0, 255, 0), 2)

            # Calculate the center position of the bounding box
            center_x = (x_min + x_max) / 2
            center_y = (y_min + y_max) / 2

            # Determine if the fruit is at the center, left, or right
            if center_x < image_width / 4:
                position = "Right"
                
            elif center_x > image_width * 3 / 4:
                position = "Left"
            else:
                position = "Center"

            print("Fruit position {}: {}".format(i+1, position))

            fruit_positions.append((position, (x_min, y_min, x_max, y_max)))

        # Combine positions and annotations
        combined_annotation = ", ".join(["{} at {}".format(position, box) for position, box in fruit_positions])
        #//print("Combined annotation:", combined_annotation)

        # Save the annotated image (without annotations)
        annotated_filename = save_directory + 'annotated_image_{}.jpg'.format(image_counter)
        cv2.imwrite(annotated_filename, frame)
       #// print("Annotated image saved as:", annotated_filename)

        # Increment the image counter
        image_counter += 1

        # Switch to captured image view
        captured_frame = frame
        show_live_feed = False

        # Close the window displaying live feed
        cv2.destroyWindow('Feed')

    # Switch back to live feed if 'c' key is pressed
    if key == ord('c'):
        show_live_feed = True
        cv2.destroyWindow('Captured Image')  # Close the captured image window

    # Exit the loop if the 'q' key is pressed
    if key == ord('q'):
        break

# Release the webcam and close OpenCV windows
cap.release()
cv2.destroyAllWindows()

`

**Comment by glenn-jocher** [comment]
Hey there! Your project sounds really interesting! 😊 To get the class label for each detected object in specific positions, you can modify your loop like this:

```python
for i, box in enumerate(results[0].boxes.xyxy.cpu()):
    x_min, y_min, x_max, y_max, conf, cls_id = box.tolist()  # Unpack the box to include class_id
    class_label = results.names[int(cls_id)]  # Get the class label using the class_id
    
    # Your existing code for calculating position
    ...
    
    # Now, you can also print the class label
    print(f"Fruit position {i+1}: {position}, Class: {class_label}")
    ...
```

This tweak allows you to access the class label (`class_label`) for each detection and use it as needed in your project. Keep us posted on how things go! Happy coding! 🚀
