### ISSUE TITLE
use CPU for Prediction 

### ISSUE THREAD

**Issue by osamaalschame** [ultralytics/ultralytics#569]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hello, 

I want to use cpu rather than using gpu because i run out memory while using gpu

**Comment by AyushExel** [comment]
You can do model.to('cpu') . Or pass model=cpu when running from cli
