### ISSUE TITLE
remove the box and confidence level generated by yolov8 seg

### ISSUE THREAD

**Issue by 8410ttt** [ultralytics/ultralytics#5714]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to remove the box and confidence level generated by yolov8 seg? I only want to keep the generated mask and label, how can I change it?

**Comment by glenn-jocher** [comment]
@8410ttt yes you can do this like this:

```
yolo predict model=yolov8n-seg.pt boxes=False hide_labels=True
```

![zidane](https://github.com/ultralytics/ultralytics/assets/26833433/0fb8a742-4300-4653-9a30-4e68dacdd1c5)

**Comment by glenn-jocher** [comment]
@ultralytics/yolo BTW guys this naming convention is terrible, i.e. `boxes=False hide_labels=True`. Plotting args should all be opt-in or opt-out but not both.
