### ISSUE TITLE
.pt to .onnx model have issue with OpenCV

### ISSUE THREAD

**Issue by shersoni610** [ultralytics/ultralytics#572]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I converted .pt to .onnx model as specified ih the document. Howver, while opening the model in OpenCV, I got the following error.

Model: ./models/yolov8l.onnx
[ERROR:0@0.365] global onnx_importer.cpp:1054 handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [Reshape]:(onnx_node!/model.22/dfl/Reshape) from domain='ai.onnx'
libc++abi: terminating with uncaught exception of type cv::Exception: OpenCV(4.7.0) /Users/Software/OpenCV/opencv-4.7.0/modules/dnn/src/onnx/onnx_importer.cpp:1073: error: (-2:Unspecified error) in function 'handleNode'
> Node [Reshape@ai.onnx]:(onnx_node!/model.22/dfl/Reshape) parse error: OpenCV(4.7.0) /Users/Software/OpenCV/opencv-4.7.0/modules/dnn/src/layers/reshape_layer.cpp:109: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'computeShapeByReshapeMask'
>
[1]    72141 abort      objdetect ../bicycles.jpg

### Additional

Onnx models worked with yoioV7.

**Comment by knoppmyth** [comment]
The ONNX output is slight different in the v8 exporter. I've posted code on #457 that works with v8.

**Comment by shersoni610** [comment]
Thank you very much. I was trying to use c++ using onnx model. Is there any solution  for c++?

**Comment by knoppmyth** [comment]
You're welcome. Unfortunately, I don't know of a solution for C++. Looking at my code, pay attention to the parts with `if model == "yolov8":` These are the only changes need to make it work with v8. The same code works with v7. Well, the "official" v7 as I've not worked with the other.

**Comment by shersoni610** [comment]
Hello, 

It did not work for. It failed at "readNet" in openCV. The problem may be in the converted model  to onnx.

**Comment by knoppmyth** [comment]
Are you specifying an opset? This is what I use to export.
`yolo mode=export model=runs/detect/train/weights/best.pt imgsz=[640,640] format=onnx opset=11`

**Comment by shersoni610** [comment]
Thank you very much. I do not know what opset does but let me try out.

**Comment by shersoni610** [comment]
Hello,  
Thank you. At least now the code did not crash. Howver, the bounding boxes are two small and incorrect compared to YoloV7. Debugging the code now.

**Comment by shersoni610** [comment]
Hello, 

Do you have your code posted somewhere? While copying, i lost the python indents.

**Comment by knoppmyth** [comment]
You can find the method [here](https://pastebin.com/kxHeDytN).
You should note, there might not be anything wrong with your code with respect to the bounding boxes. YOLOv7 might simply be better then v8 for what it is you're trying to detect. 

For my custom dataset, I've tried YOLOv5 - 8. V6 performs the best for me. Surprising, going from YOLOv6.1 to 6.2, I saw issues like you described above. However going to 6.3 from 6.2, the performance returned and was improved.

**Comment by knoppmyth** [comment]
You're very welcome.
I do believe Ultralytics is on the right track with v8. Sure documentation of certain items could have been better but that is where we can help.

**Comment by superbayes** [comment]
![image](https://user-images.githubusercontent.com/56495942/214590194-576a571c-862a-4ae9-9521-8f07e6e9233a.png)
* same question

**Comment by JustasBart** [comment]
@shersoni610 Did you figure this out in the end?

Currently my SOTA for yolov8 C++ is this:
![image](https://user-images.githubusercontent.com/40023722/216022017-66516363-d57b-4892-9e1c-471e1fe7a66e.png)

Which let me be honest with you... It's not great :laughing:

**Comment by JustasBart** [comment]
@shersoni610 I've solved this issue [here](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX) if you're still pursuing this :rocket:

**Comment by diogovazguerra** [comment]
> @shersoni610 Did you figure this out in the end?
> 
> Currently my SOTA for yolov8 C++ is this: ![image](https://user-images.githubusercontent.com/40023722/216022017-66516363-d57b-4892-9e1c-471e1fe7a66e.png)
> 
> Which let me be honest with you... It's not great 😆

Hi JustaBart. How did you fixed that problem where object detection is completely wrong? Because I have the same issue but only with recorded video with a GPU but with my webcam it works fine. With more clarity of my problem here is a issue that I made #3125
