### ISSUE TITLE
The question from tracking mode

### ISSUE THREAD

**Issue by BoyceL** [ultralytics/ultralytics#5723]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi Developers:
When I was using the tracking mode in yolov8, I found that in the byte_tracker.py, the STrack was initilazed by the tlwh from the results of yolo, but the property `_tlwh` was initialized by: 
```python
self._tlwh = np.asarray(self.tlbr_to_tlwh(tlwh[:-1]), dtype=np.float32)
``` 
Is that reasonable to transform the tlwh to tlwh by the methods `tlbr_to_tlwh`? With this problem, the bytetrack mode was not working with good results. The object id was changed frequently, but the botsort mode didn't seem to be influenced.

When I changed this line into:
```python
self._tlwh = np.asarray(tlwh[:-1], dtype=np.float32)
```
 I found that the tracking results was better but with a wrong bounding box.
Is there any mistakes in my understanding of your code?

Thanks for your wonderful code and your kind response in advance.

**Comment by glenn-jocher** [comment]
@BoyceL hello,

Thanks for your detailed description. It seems there was a misunderstanding regarding the bounding box representation.

In YOLOv8, we typically receive bounding box predictions in the form of `(top left x, top left y, width, height)` i.e., `tlwh`. Theoretically, converting `tlwh` to `tlwh` via `tlbr_to_tlwh` shouldn't change any values.

The discrepancy in tracking results you observed probably stems from the differences in initialization, not from the conversion method itself. If directly setting `_tlwh = tlwh[:-1]` improves your tracking results but yields incorrect bounding box, that may imply there's an inconsistent assumption about the bounding box representation somewhere in the code. 

Therefore, it's worth revisiting where the initial bounding boxes for the STracks are sourced, and how those bounding boxes are assumed to be formatted throughout the codebase.

Remember that for the tracker to work effectively, there must be consistency in the bounding box format from the detection phase all the way through tracking. If there are inconsistencies, they could lead to the object ID changing frequently, as you're seeing.

Thank you for bringing up this question. It's through engaging dialogues like these that we continuously improve our models and codebase.

**Comment by BoyceL** [comment]
Thanks for your quick but detailed response.
After raising this question, I have checked the parameters again. I printed out the input parameter `tlwh` of `STrack.__init__()` and the quality self.`_tlwh` of STrack for comparison.
I found that 
```python
tlwh[:-1]==[450.89 255.59 465.33 277.19]
self._tlwh[:-1]==[450.89 255.59 14.439 21.595]
```
in my test example. It seems like that the input parameter `tlwh` is actually equal to the `[top left bottom right]`. Therefore it's quite reasonable that after methods `tlbr_to_tlwh`, a correct bounding box 'self_tlwh' could be obtained. But I haven't check how the yolo output  transformed into `tlwh`, so it is just my assumption.

Should the name of input parameter `tlwh` be changed into `tlbr` for less misleading?

By the way, the problem of tracking results on my example may have nothing to do with this, but also thank you for your patient explaination.

**Comment by glenn-jocher** [comment]
Hi @BoyceL,

I'm glad you've managed to track down the source of the inconsistent tracking results. Indeed, when your input bounding boxes are in the form of `[top, left, bottom, right]` instead of `[top, left, height, width]`, using the `tlbr_to_tlwh` function of STrack provides the correct bounding box.

You're completely correct that the `tlwh` variable would then be misleading and renaming it to `tlbr` would make the code much easier to follow, as it more precisely communicates what it contains and how it should be interpreted.

This additional context is always incredibly helpful for understanding the workings of the model and improving its performance. Thanks for sharing your findings. Feedback like this contributes greatly to the continued development and improvement of YOLOv8. It's really appreciated!
