### ISSUE TITLE
Why is yolov8s‘FLOPS 28.8 instead of 28.6?

### ISSUE THREAD

**Issue by hjg12345** [ultralytics/ultralytics#5727]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I train from scratch with yolov8s（I didn't change anything）,the display GFLOPS is 28.8, but in your table which is 28.6.And in yolov8.yaml，it also writes “yolov8s 28.8GFLOPS”, How to get the 28.6 result?

**Comment by RizwanMunawar** [comment]
Appreciate your attention to this matter, @hjg12345! I'd like to confirm that the values specified in the YAML are indeed accurate. It's possible that there's a typographical error in the documentation. We'll be sure to address this internally, make the necessary updates, and keep you informed. Thank you for bringing it to our attention.
