### ISSUE TITLE
Show only one the top 1 in Classification

### ISSUE THREAD

**Issue by takanashiZero** [ultralytics/ultralytics#5729]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to filter out 1 class in the output? 

### Additional

For context i have 3 classes. in classify.py it show all 3 depending on the confidence i want to out only one how to do it?

**Comment by RizwanMunawar** [comment]
You can simply utilize the highest score from all three classes to effectively indicate the model's classification of the actual object. Thanks

**Comment by takanashiZero** [comment]
how to do that? thanks for the help

**Comment by RizwanMunawar** [comment]
@takanashiZero, you can employ the provided code to display the Top 1 Accuracy.

```python
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n-cls.pt')  # load an official model

# Predict with the model
results = model('https://ultralytics.com/images/bus.jpg')  # predict on an image

names = results[0].names
print("Top 1 Class Name : {}".format(names[results[0].probs.top1]))
print("Top 1 Class Accuracy : {}".format(results[0].probs.top1conf.cpu()))
``` 

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by takanashiZero** [comment]
how can i use this with the camera?
tried to modify it myself but still the same

**Comment by RizwanMunawar** [comment]
You can utilize the provided code to perform real-time classification with Ultralytics YOLOv8 on a webcam stream.

```python
from ultralytics import YOLO

model = YOLO('yolov8n-cls.pt')

results = model(source="0", show=True)

names = results[0].names
print("Top 1 Class Name : {}".format(names[results[0].probs.top1]))
print("Top 1 Class Accuracy : {}".format(results[0].probs.top1conf.cpu()))

```
