### ISSUE TITLE
Is it possible to get a mask of overlapping area?

### ISSUE THREAD

**Issue by saka3324** [ultralytics/ultralytics#573]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

If object A. and object B. are overlaping in the segmentation result, you will get the mask for the one in front, and the one behind will be hollowed out.
To get the whole behind mask, you have to stack it with the front one, but that leaves a very small gap.
In such a case, even if I annotate the overlapping area for both objects explicitly, will the result be only the one in the front?

Thank you.

**Comment by Laughing-q** [comment]
@saka3324 hi the segmentation training is with `overlap_mask=True` by default to save memory and speed-up training. you can set `overlap_mask=True` when training, then the model is able to get the whole mask of both front one and behind one.

**Comment by saka3324** [comment]
@Laughing-q Hi.
That's what I'm looking for!
I'm trying later.
Thank you so much :)

**Comment by saka3324** [comment]
By the way, 
overlap_mask=True is dafault and that removes overlapping masks , right?
I can't find any document about that parameter, but only found in the original code which is True in default.
So I should set overlap_mask=False, and get both overlapping masks, right?

 Thank you.

**Comment by Laughing-q** [comment]
@saka3324 yes!

**Comment by saka3324** [comment]
@Laughing-q 
Thank you!
