### ISSUE TITLE
How should I store the result of val into txt

### ISSUE THREAD

**Issue by minwim** [ultralytics/ultralytics#5751]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

val: WARNING ⚠️ /home/disk/wlm/yolov8/segment/workspace/data/asc1_sxyw_1016/large-sx/images/1685603561166151.jpg: corrupt JPEG restored and saved
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:07<00:00,  1.10it/s]
                   all        123        493          1          1      0.995      0.995    0.00342    0.00347    0.00174    0.00104
                     A        123        153          1          1      0.995      0.995          0          0          0          0
                     B        123         91          1          1      0.995      0.995          0          0          0          0
                     C        123        177          1          1      0.995      0.995          0          0          0          0
                     D        123         72          1          1      0.995      0.995     0.0137     0.0139    0.00694    0.00417

### Additional

![image](https://github.com/ultralytics/ultralytics/assets/86920530/0df03706-78b4-4cdd-82ff-d9f10f50b2c2)
I want to save val results to txt ， what i should do ?

**Comment by RizwanMunawar** [comment]
@minwim Thanks for sharing the information. You can use the provided code to save validation results in JSON files. The text file-saving feature is not supported yet!

```python
from ultralytics import YOLO

model = YOLO('yolov8n.pt')  # load a YOLOv8n model

# Validate the model
metrics = model.val(save_json=True)
```

For more information, you can visit [Ultralytics Validation Docs](https://docs.ultralytics.com/modes/val/#arguments)

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by minwim** [comment]
@RizwanMunawar thanks, i want to get **Image**s and  **Instances**,  I didn't find the relevant parameters in metrics,
the parameters as below:
![image](https://github.com/ultralytics/ultralytics/assets/86920530/f269b8b4-46f1-4210-b24a-85acd894f520)

**Comment by minwim** [comment]
but i can get **names** in metrics
![image](https://github.com/ultralytics/ultralytics/assets/86920530/480e4fe7-4562-46a4-80d7-fd8287166092)

**Comment by glenn-jocher** [comment]
@minwim, thank you for bringing this to our attention. Currently, the `metrics` object contains evaluation metrics for each class (precision, recall, mAP, etc.) under the class names in the 'names' field.

However, the 'Instances' and 'Images' data you are requesting, namely the number of images and instances per class, is not currently included in the 'metrics' output. 

The metrics object is primarily designed to provide users with detailed model performance metrics rather than dataset statistics, which is why 'Instances' and 'Images' data aren't included. 

This said, we're always open to potential enhancements in future updates, and we appreciate your feedback!

**Comment by minwim** [comment]
@glenn-jocher thanks

**Comment by glenn-jocher** [comment]
@minwim you're welcome! If you have any further questions or run into any issues with anything else, don't hesitate to ask. We're always here to help. Remember, the strength of our community, including contributors like yourself, is what makes this project successful. 
Best of luck with your work using YOLOv8!
