### ISSUE TITLE
Results manipulation

### ISSUE THREAD

**Issue by coder-glitche** [ultralytics/ultralytics#5752]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey @glenn-jocher i was try to access my predicted class name and b box cordinates through my code instead of save_txt =True
But im getting error like ''list has no attribute names"
What should my syntax be if there are n number of classes and i want to extract them in case of both my detection and classification model....

**Comment by RizwanMunawar** [comment]
"@coder-glitche, you can utilize the provided code to extract class names following the model's processing of the frames."

### Object Detection
```python
from ultralytics import YOLO

model = YOLO('yolov8n.pt')
results = model('https://ultralytics.com/images/bus.jpg')

# Extract bounding boxes, classes, names, and confidences
boxes = results[0].boxes.xyxy.tolist()
classes = results[0].boxes.cls.tolist()
names = results[0].names   # Classes names
confidences = results[0].boxes.conf.tolist()

# Iterate through the results
for box, cls, conf in zip(boxes, classes, confidences):
    x1, y1, x2, y2 = box
    name = names[int(cls)]    # detected object class name
    #..... continue according to your need
```

### Image Classification
```python
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n-cls.pt')  # load an official model

# Predict with the model
results = model('https://ultralytics.com/images/bus.jpg')  # predict on an image

names = results[0].names   # Classes names
print("Top 1 Class Name : {}".format(names[results[0].probs.top1]))
print("Top 1 Class Accuracy : {}".format(results[0].probs.top1conf.cpu()))
```

Hope this helps! Let me know if you have any additional questions.
Thanks
