### ISSUE TITLE
Yolo predict stops predicting abruptly after 43 frames 

### ISSUE THREAD

**Issue by BenMaslen** [ultralytics/ultralytics#5753]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Trying to use yolov8 predict on an MP4 video using a custom trained model, however the prediction stops abruptly after 43 frames with no error message. 

Below is the code I used to predict my custom model (file locations and names replaced with ellipses):

yolov8_venv/bin/yolo detect predict model = .../weights/best.pt \
source='.../GP032138.MP4' \
name=.../GP032138_predictions imgsz = 1088 save_txt = True \
save_conf = True

And here is the output (again file locations and names replaces with ellipses):

Loading python/3.9.4
  Loading requirement: intel-mkl/2020.1.217
Ultralytics YOLOv8.0.53 🚀 Python-3.9.4 torch-1.13.1+cu117 CUDA:0 (Tesla P100-SXM2-16GB, 16276MiB)
Model summary (fused): 268 layers, 43609692 parameters, 0 gradients, 164.8 GFLOPs

video 1/1 (1/53100) ... 1 Lates calcarifer, 35.8ms
video 1/1 (2/53100) ... (no detections), 34.7ms
video 1/1 (3/53100) ... (no detections), 34.7ms
video 1/1 (4/53100) ... (no detections), 34.7ms
video 1/1 (5/53100) ... (no detections), 34.8ms
video 1/1 (6/53100) ... (no detections), 34.7ms
video 1/1 (7/53100) ... (no detections), 32.9ms
video 1/1 (8/53100) ... (no detections), 33.0ms
video 1/1 (9/53100) ... (no detections), 33.1ms
video 1/1 (10/53100) ... (no detections), 33.2ms
video 1/1 (11/53100) ... (no detections), 33.2ms
video 1/1 (12/53100) ... (no detections), 33.2ms
video 1/1 (13/53100) ... (no detections), 33.2ms
video 1/1 (14/53100) ... (no detections), 33.2ms
video 1/1 (15/53100) ... (no detections), 33.3ms
video 1/1 (16/53100) ... (no detections), 33.2ms
video 1/1 (17/53100) ... (no detections), 33.2ms
video 1/1 (18/53100) ... (no detections), 33.2ms
video 1/1 (19/53100) ... (no detections), 33.2ms
video 1/1 (20/53100) ... (no detections), 33.2ms
video 1/1 (21/53100) ... (no detections), 33.2ms
video 1/1 (22/53100) ... (no detections), 33.1ms
video 1/1 (23/53100) ... (no detections), 33.2ms
video 1/1 (24/53100) ... (no detections), 33.2ms
video 1/1 (25/53100) ... (no detections), 33.3ms
video 1/1 (26/53100) ... (no detections), 33.2ms
video 1/1 (27/53100) ... (no detections), 33.3ms
video 1/1 (28/53100) ... (no detections), 33.2ms
video 1/1 (29/53100) ... (no detections), 33.3ms
video 1/1 (30/53100) ... (no detections), 33.2ms
video 1/1 (31/53100) ... (no detections), 33.2ms
video 1/1 (32/53100) ... (no detections), 33.2ms
video 1/1 (33/53100) ... (no detections), 33.2ms
video 1/1 (34/53100) ... 1 Lates calcarifer, 33.1ms
video 1/1 (35/53100) ... 1 Lates calcarifer, 33.2ms
video 1/1 (36/53100) ... (no detections), 33.2ms
video 1/1 (37/53100) ... (no detections), 33.3ms
video 1/1 (38/53100) ... 1 Lates calcarifer, 33.2ms
video 1/1 (39/53100) ... 1 Lates calcarifer, 33.2ms
video 1/1 (40/53100) ... 1 Lates calcarifer, 33.2ms
video 1/1 (41/53100) ... 1 Lates calcarifer, 33.2ms
video 1/1 (42/53100) ... 1 Lates calcarifer, 33.2ms
video 1/1 (43/53100) ... 1 Lates calcarifer, 33.2ms
Speed: 0.4ms preprocess, 33.4ms inference, 2.5ms postprocess per image at shape (1, 3, 1088, 1088)
Results saved to ...
9 labels saved to ...

### Environment

Ultralytics YOLOv8.0.53 🚀 Python-3.9.4 torch-1.13.1+cu117 CUDA:0 (Tesla P100-SXM2-16GB, 16276MiB)
Model summary (fused): 268 layers, 43609692 parameters, 0 gradients, 164.8 GFLOPs

python/3.9.4
intel-mkl/2020.1.217

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
@BenMaslen There could be several factors contributing to the prediction stop. I recommend monitoring memory usage during inference as it can provide insights into any memory-related issues. Additionally, it's a good idea to verify the video file's integrity, as corruption can also be a potential cause.

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by BenMaslen** [comment]
Hi @RizwanMunawar thank you for your quick response. I believe it is related to memory usage as when altering the number of CPU's I allocate to run the code I am able to gain a couple of more frames. I am trying to use the video streaming capabilities using CLI code as above (following https://docs.ultralytics.com/usage/cfg/#predict), however setting stream = True or stream_buffer = True both results in the below error messages. Do you know if there is a way to stream videos using CLI code? 

SyntaxError: 'stream' is not a valid YOLO argument.

SyntaxError: 'stream_buffer' is not a valid YOLO argument.

**Comment by glenn-jocher** [comment]
Hi @BenMaslen, 

It looks like the error is hinting that the `stream` or `stream_buffer` argument is not recognized or supported within the version of YOLO v8 CLI that you're using. Some versions of YOLO don't support certain functionalities, hence the unrecognized command error. 

At present, streaming videos for prediction via CLI in YOLOv8 could be unsupported, or it could be implemented differently than how it's set in the YOLO configuration files you're referring to. You might need to refer to YOLO v8 specific documentation or resources for the correct set of commands to use for your task.

For handling the memory issue while processing video frames, make sure you're using a configuration that doesn't exceed the hardware capabilities of your machine. Consider using smaller batch sizes or a lower resolution, if possible.

I hope this response provides some guidance!
