### ISSUE TITLE
How to suppress any output while predicting?

### ISSUE THREAD

**Issue by haimat** [ultralytics/ultralytics#5756]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am predicting via YOLOv8 like this:

```python
    yolo_model = YOLO(yolo_model_path)
    results = yolo_model(image, imgsz=yolo_imgsz, conf=0.75, max_det=1)
    for r in results:
        x, y, w, h = r.boxes.xywh[0]
```

This prints the results from prediction, somehing like this:

> 0: 800x1280 1 Animal, 9.4ms
> Speed: 4.9ms preprocess, 9.4ms inference, 1.7ms postprocess per image at shape (1, 3, 800, 1280)

How can I turn off or suppress all that output?

**Comment by RizwanMunawar** [comment]
You can use the option `verbose=False`. i.e

```python
model = YOLO(yolo_model_path)
results = model.predict(image, imgsz=yolo_imgsz, conf=0.75, max_det=1,verbose=False)
for r in results:
    x, y, w, h = r.boxes.xywh[0]
```

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by haimat** [comment]
@RizwanMunawar Thanks!

**Comment by glenn-jocher** [comment]
@haimat hi RizwanMunawar,

You're welcome! If there's anything else you need assistance with regarding YOLOv8, please feel free to reach out. Your feedback and questions contribute to this project's continuous improvement. Let's continue to make YOLOv8 even better!

Enjoy developing with YOLOv8, and keep up the great work!

Best Regards,
Glenn Jocher
