### ISSUE TITLE
Problem in resume training yolov8

### ISSUE THREAD

**Issue by AZIZMOH9** [ultralytics/ultralytics#5762]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

SyntaxError                               Traceback (most recent call last)
[<ipython-input-14-f78c85f34829>](https://localhost:8080/#) in <cell line: 1>()
----> 1 results = model.train(
      2     epochs=20
      3     ,resume=True
      4 )

8 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py](https://localhost:8080/#) in check_dict_alignment(base, custom, e)
    200             match_str = f'Similar arguments are i.e. {matches}.' if matches else ''
    201             string += f"'{colorstr('red', 'bold', x)}' is not a valid YOLO argument. {match_str}\n"
--> 202         raise SyntaxError(string + CLI_HELP_MSG) from e
    203 
    204 

SyntaxError: 'hydra' is not a valid YOLO argument. 
'v5loader' is not a valid YOLO argument. 
'fl_gamma' is not a valid YOLO argument. 
'image_weights' is not a valid YOLO argument. 

    Arguments received: ['yolo', '-f', '/root/.local/share/jupyter/runtime/kernel-7b08a458-2dac-4610-9aff-5c77e2d8f467.json']. Ultralytics 'yolo' commands use the following syntax:

        yolo TASK MODE ARGS

        Where   TASK (optional) is one of ('detect', 'segment', 'classify', 'pose')
                MODE (required) is one of ('train', 'val', 'predict', 'export', 'track', 'benchmark')
                ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
                    See all ARGS at https://docs.ultralytics.com/usage/cfg or with 'yolo cfg'

    1. Train a detection model for 10 epochs with an initial learning_rate of 0.01
        yolo train data=coco128.yaml model=yolov8n.pt epochs=10 lr0=0.01

    2. Predict a YouTube video using a pretrained segmentation model at image size 320:
        yolo predict model=yolov8n-seg.pt source='https://youtu.be/LNwODJXcvt4' imgsz=320

    3. Val a pretrained detection model at batch-size 1 and image size 640:
        yolo val model=yolov8n.pt data=coco128.yaml batch=1 imgsz=640

    4. Export a YOLOv8n classification model to ONNX format at image size 224 by 128 (no TASK required)
        yolo export model=yolov8n-cls.pt format=onnx imgsz=224,128

    5. Run special commands:
        yolo help
        yolo checks
        yolo version
        yolo settings
        yolo copy-cfg
        yolo cfg

    Docs: https://docs.ultralytics.com/
    Community: https://community.ultralytics.com/
    GitHub: https://github.com/ultralytics/ultralytics

### Minimal Reproducible Example

results = model.train(
    epochs=20
    ,resume=True
)

### Additional

I have trained yolov8 for 35 epochs earlier and then i want to resume training the model using the code below

results = model.train(
    epochs=20
    ,resume=True
)
and faced this error:

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AZIZMOH9 the error message you're seeing indicates that certain arguments provided are not recognized as valid arguments for YOLOv8. The arguments in question are 'hydra', 'v5loader', 'fl_gamma', and 'image_weights'. It seems these do not belong to the allowed set of arguments for the 'model.train' function.

In regards to your issue with resuming training, the feature should work if used correctly. Make sure you're using the latest version of YOLOv8. When you save your model after initial training, it should create a `.pt` file. This is the file you want to load in when resuming training.

For example, generally, it would look something like this in code:

```python
model.train(resume='path_to_your_saved_weights.pt')
```

In your case, you should add the path to your previously saved weights file within the 'resume' argument in the model.train function. If that isn't working there might be a different issue at play.

**Comment by jrsaffy** [comment]
Want to mention that I'm having the same issue with the same error: model.train(resume=True).

**Comment by glenn-jocher** [comment]
@jrsaffy i appreciate the additional information you've provided. If you've attempted to resume training by setting `resume=True` or by providing the path to your checkpoint file and are still facing the same error, this suggests that the issue isn't with the resume functionality itself, but with an incorrect setup elsewhere in your training configuration or the way you're invoking the training command.

When you encounter this kind of error, it is beneficial to revisit your entire training command and configuration setup to ensure no inadvertent or incompatible arguments are being passed. Carefully examine your configuration files and any command line arguments to ensure they align with YOLOv8's expected arguments.

Additionally, double-check the integrity of your `"path/to/last.pt"` file. Please ensure that the file exists at the specified location and isn't corrupted.

If after reviewing your setup the problem persists, it would be helpful to see the full context in which you're calling `model.train()`, including any configuration files or additional arguments you might be passing. This additional context often holds the key to resolving such issues.

Remember that the YOLOv8 training command should match the API as described in our documentation and should not contain any leftover or unrelated arguments from different versions of YOLO or different frameworks that could be causing conflicts. If there were recent changes in the repository or updates, make sure to pull the latest changes and review the updated documentation to ensure compatibility.

**Comment by sathyanarayanaRP** [comment]
raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'fl_gamma' is not a valid YOLO argument.
'v5loader' is not a valid YOLO argument.
'image_weights' is not a valid YOLO argument.


the same error arised twice, but the configuration i gave was almost correct 

yolo detect train data=D:\KATHIAR\springset\23FEB24\NEW\data.yaml model=yolov8n.yaml epochs=5000 batch=16 imgsz=640 device=0 project=D:\rollingstockkathiar\springset name=training23feb24  patience=500 pretrained=D:\rollingstockkathiar\springset\training09feb2\weights\best.pt resume=D:\rollingstockkathiar\springset\training23feb24\weights\last.pt


the arguements i passed and the path are also correct. 
yolo detect train pretrained="D:\rollingstockkathiar\springset\training23feb24\weights\last.pt" resume=True

this is the resume arguements  i passed, the problem arose when i  tried to initiate another training which caused the cuda memory allocation error .this happened twice .is there any solution for this types of bug

**Comment by glenn-jocher** [comment]
@sathyanarayanaRP hey there! 👋 It looks like you're encountering a syntax error due to some arguments that aren't recognized by YOLOv8. The arguments `fl_gamma`, `v5loader`, and `image_weights` are indeed not valid for YOLOv8. 

For resuming training, you should use either `resume=True` to automatically resume from the last checkpoint or specify the path to the checkpoint file without the `resume` argument, like so:

```bash
yolo detect train data=data.yaml model=yolov8n.yaml ... pretrained="path/to/last.pt"
```

If you're facing a CUDA memory allocation error, it might be due to insufficient GPU memory. Try reducing the batch size or image size to alleviate memory usage. If the problem persists, feel free to share more details, and we'll be happy to help you out! 🚀
