### ISSUE TITLE
Run openvino model after changing from model YOLOV8 to openvino

### ISSUE THREAD

**Issue by NMThanh123** [ultralytics/ultralytics#5768]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to get bounding box in openvino model. Here is my code but I don't how to get bouding box

import openvino as ov
import cv2 as cv
import numpy as np
from ultralytics.utils import ops

core = ov.Core()
det_model_xml = "model/det/det/det.xml"
model = core.read_model(model=det_model_xml)
compiled_model = core.compile_model(model=model, device_name="CPU")
input_layer = compiled_model.input(0)
output_layer = compiled_model.output(0)
image = cv.imread('Bicycles/0000_00532_b.jpg')
N, C, H, W = input_layer.shape
resized_image = cv.resize(src=image, dsize=(W, H))
input_data = np.expand_dims(np.transpose(resized_image, (2, 0, 1)), 0).astype(np.float32)
result = compiled_model([input_data])[output_layer]

output_layer has shape
<ConstOutput: names[output0] shape[1,5,8400] type: f32>

**Comment by saim212** [comment]
Hi @NMThanh123, I hope this will help you. [link](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/230-yolov8-optimization)

**Comment by NMThanh123** [comment]
Thanks for everyone. I found the solution to solve the problem.

**Comment by glenn-jocher** [comment]
@NMThanh123 hello,

I'm glad to hear that you've found a solution to your problem! If there are any other questions or challenges you face in your work with YOLOv8, don't hesitate to ask. Your successful use of our models is important to us. Remember, there's a wealth of knowledge in our YOLO community that you can tap into – we're all here to help each other!

Thank you for using Ultralytics YOLOv8. Wishing you continued success in your AI projects!

Best regards,
Glenn Jocher

**Comment by sharoseali** [comment]
> Thanks for everyone. I found the solution to solve the problem.

how @NMThanh123  I am getting this issue of so much boxes on OPenVino model
