### ISSUE TITLE
Long memory load times before train and validate in each epochs

### ISSUE THREAD

**Issue by lanyeeee** [ultralytics/ultralytics#577]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

```python
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO('weights/yolov8s.pt')
    model.train(data='data/mycoco.yaml', epochs=700, imgsz=640, project='runs')
```
This is the code I used for training model, but it is slow, then I found the **memory loading time before training and validate** was very long in each epoch  

in my case, each epoch, first load something into memory before train, then memory is freed at the end of the train, load something into memory before validate, then memory is freed again at the end of the validate. Then go on, the next epoch and load something into memory before train  

**loading something into memory** before train takes about **30s**, and the same before validate. But the total time to do train and validate is only about **40s**, for 30s before train and validate, the GPU is idle  

I tried to trace the code and it seems that the 30s before train occurs in
```python
#ultralytics/yolo/engine/trainer.py line:269
pbar = enumerate(self.train_loader)
```

Is this **load time** normal? There is no such **load time** in yolov5. When I train the model in yolov5, the GPU is almost always 100%.

my dataset is 2694 train, 496 val, without test  

similar issues #509

**Comment by lanyeeee** [comment]
https://github.com/ultralytics/ultralytics/issues/509#issuecomment-1399660901
I just tested in **Linux Mint** and it works well. Maybe this issue only occurs in **Windows**

**Comment by glenn-jocher** [comment]
@lanyeeee I haven't seen long load times in Google Colab or Docker on our server, but I don't have a windows machine to test that os.

BTW we temporarily have the YOLOv5 dataloader here also, you can enable it (for detection training only) with `v5loader=True`

**Comment by lanyeeee** [comment]
> @lanyeeee I haven't seen long load times in Google Colab or Docker on our server, but I don't have a windows machine to test that os.
> 
> BTW we temporarily have the YOLOv5 dataloader here also, you can enable it (for detection training only) with `v5loader=True`

I have tried using `v5loader=True` like that
```python
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO('weights/yolov8s.pt')
    model.train(data='data/mycoco.yaml', epochs=700, imgsz=640, project='runs', v5loader=True)
```
But it works the same as before, loading before train and validate each epoch. Am I using `v5loader=True` in the right way?

**Comment by darouwan** [comment]
Meet the same problem on Windows. The problem is caused by the slow validation time. In my case, training time for each epoch is only 5seconds, while validation time always takes more than 30seconds.

**Comment by darouwan** [comment]
2/100      9.02G      3.448      6.119      4.326          6        640: 100%|██████████| 5/5 [00:04<00:00,  1.13it/s]
Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:36<00:00, 36.36s/it]

**Comment by darouwan** [comment]
I have found the potential cause of this issue. 
The slow process is 
https://github.com/ultralytics/ultralytics/blob/a5410ed79e6ff30ee56d359c43f3c49d6d840ced/ultralytics/yolo/engine/validator.py#L135

> 

But I am still not sure why this line is so slow.

**Comment by ddjukic** [comment]
In the absence of a fix: https://fizzylogic.nl/2022/11/02/how-to-set-up-cuda-and-pytorch-in-ubuntu-22-04-on-wsl2

Getting pytorch to run with GPU support on WSL is a breeze, and there are no slowdowns between epochs this way with using dataloader workers during training :)

**Comment by megachomba** [comment]
i have exactly the same problem on windows, validation is slow, and terrible long time between epoch->validation and validation -> epoch

**Comment by ytylalal** [comment]
For this question， I have met and found solution.
The bug is probably due to config: "close_mosaic: 10".
The config lead to load data for each epoch.

**Comment by VivizSun** [comment]
For this question, I found that there are 3 code in trainer.py (as follows picture) that are very time consuming on windows 11.
![001](https://user-images.githubusercontent.com/98437625/221500819-15bd893a-ead2-4774-934c-4791fbe982e6.png)

I tried using v5loader, but it didn‘t improve. (as follows picture)
![002](https://user-images.githubusercontent.com/98437625/221500916-1e29d2e8-eddf-4c0b-a7d2-96e549697aab.png)

I also tried using workers=0 or cache=False, but it didn’t improve the iteration speed.

Is there anything else I can do with? :((

My equipment and environment are as follows:
CPU : Amd R9 5900HX
GPU : RTX 3080 Laptop
Python : 3.10.4 
ultralytics : 8.0.47

**Comment by ytylalal** [comment]
![image](https://user-images.githubusercontent.com/38555034/221504664-80841297-fcf5-412b-b6a7-1c27253dddf6.png)
![image](https://user-images.githubusercontent.com/38555034/221504781-ce033d98-4baf-42b0-9918-5627377550a6.png)

Sorry，I didn't make it clear  before，the key is changing to use InfiniteDataloader，as shown above。
This is effective。But further research is needed for the possibility of over-fitting。 

By the way ,happy to use the same equipment.(¬‿¬)

**Comment by VivizSun** [comment]
@ytylalal 
Thank you for your help. :))
Improved training speed after modifying line 144 of v5loader.py.
![000](https://user-images.githubusercontent.com/98437625/221514984-dbedda96-25ad-4536-bd75-eeda726690a0.png)

**Comment by darouwan** [comment]
It seems that this issue has been solved. Now I set the workers=16 and the training speed is much faster than workers=0

**Comment by pderrenger** [comment]
Hello @darouwan,

Thank you for sharing your findings and for helping improve the training speed. It's great to hear that you were able to address the issue by modifying the `v5loader.py` file and setting `workers=16`. This setting significantly improved the training speed, and it's fantastic that you experienced such a noticeable difference. Your experience will likely be beneficial to others facing similar challenges.

If you encounter any further issues or have more insights to share, please feel free to do so. Your contributions and collaboration are greatly appreciated!

Wishing you continued success with your training! 😊
