### ISSUE TITLE
Can onnx do target tracking?

### ISSUE THREAD

**Issue by fusang1337** [ultralytics/ultralytics#5777]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi developer, can I convert the model to onnx and still do target tracking? How should the tracking be done? Can you give a Python example? What if I convert onnx to a bmodel model for the algorithmic edge inference platform?

**Comment by sxstone** [comment]
same questions haha

**Comment by glenn-jocher** [comment]
@fusang1337 hi, thanks for your questions. 

The tracking functionality in YOLOv8 is integrated within the detection pipeline of the model. When you convert the model to ONNX format, it'll essentially convert the detection part of the pipeline. While the ONNX version of a YOLOv8 can still perform object detection, it might not support built-in target tracking.

However, you can implement a tracking system alongside the ONNX model. When you run object detection on a video sequence, the model will output the locations of detected objects in each frame. You can use these outputs to implement various tracking algorithms, keeping track of the movement of detected objects from frame to frame.

As for your question regarding the conversion of an ONNX model to a bmodel for the Algorithmic Edge Inferencing platform, the process would depend on the requirements and capabilities of that specific platform. Typically, you would employ a tool or a set of tools provided by the platform to convert the ONNX model to the native model format (bmodel in this case).

Remember, the ONNX format is an open standard meant for exchanging models across different deep learning frameworks. They maintain the structure and the learned weights of the network but may lack certain specific functionalities integrated within the original model, such as custom tracking.

I hope this clarifies your queries!

**Comment by fusang1337** [comment]
thanks

**Comment by glenn-jocher** [comment]
Hello @fusang1337,

Thanks for your questions. When you convert the YOLOv8 model to the ONNX format, it generally preserves the core functionalities like object detection and classifications, but not the custom features like target tracking.

For implementing target tracking with your ONNX model, you can consider using the output data from the model, i.e., object locations from each video frame, and feeding this data into a custom tracking algorithm of your choice. This will allow you to track the movement of detected objects across a sequence of frames manually.

Regarding your question about bmodel conversion, ONNX models are typically used to ensure interoperability between different deep learning frameworks. Converting an ONNX model to a bmodel for use on the Algorithmic Edge Inferencing platform would primarily rely on the conversion tools provided by the platform. Therefore, you should explore the documentation of your desired platform to see if they support this conversion.

It's important to note that while these ONNX exports facilitate the flexibility of use across different frameworks, particular features like custom tracking, which were built in the original native platform, may not be preserved post conversion.

I hope this helps answer your queries. Let me know if you have any more questions!

Best regards,
Glenn
