### ISSUE TITLE
WARNING ⚠️ Environment does not support cv2.imshow() or PIL Image.show() in docker env

### ISSUE THREAD

**Issue by yongjer** [ultralytics/ultralytics#5781]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

## is there any way to show the webcam in the container?
I'm using ```ultralytics/ultralytics:latest```
here is my devcontainer.json:
```

{
	"image": "ultralytics/ultralytics:latest",


	"runArgs": [
		"--gpus", "all",
		"--ipc=host",
		"--ulimit", "memlock=-1",
		"--ulimit", "stack=67108864",
		"--device", "/dev/video0:/dev/video0",
		"--net=host",
		"-e", "DISPLAY=$DISPLAY",
		"-v", "/tmp/.X11-unix/:/tmp/.X11-unix"
	],
	"customizations": {
		"vscode": {
			"extensions": [
				"ms-python.python",
				"ms-toolsai.jupyter",
				"GitHub.copilot",
				"GitHub.copilot-chat"
			]
		}
	}
}
```

**Comment by RizwanMunawar** [comment]
@yongjer, your input is appreciated. In a Docker environment, it's important to note that cv2.imshow() won't function as expected. To address this, you should utilize opencv-python-headless within your Docker environment.

Hope this helps! Let me know if you have any additional questions.
Thanks
