### ISSUE TITLE
Logging even with verbose=False

### ISSUE THREAD

**Issue by maltesilber** [ultralytics/ultralytics#5785]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I want to turn off logging, since when training on multiple gpu's I get multiple logs and the output becomes unreadable. However, even with verbose=False is still get the same output. 

I think the reason is that when building the model inside the `DetectionTrainer` we have `verbose=True` as a default. However, inside the `Model` class verbose is not specified. Is this on purpose? Also, is the behaviour of every GPU outputting logs on purpose?

Here the `get_model` function from the `DetectionTrainer`
![trainer](https://github.com/ultralytics/ultralytics/assets/113178571/2cd657ed-39fe-46bd-b26e-3824b0fae603)

And here where it's called inside the `Model` class
![model](https://github.com/ultralytics/ultralytics/assets/113178571/8d1d8dc4-96cd-46a0-bafc-4dff8906e2de)

### Minimal Reproducible Example
```
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO(model="yolov8n.yaml", task='detect')
    model.train(mode='train',
                name='sanity_check',
                data='coco128.yaml',
                verbose=False)
```

**Comment by RizwanMunawar** [comment]
@maltesilber the `verbose` setting is functional solely during prediction, segmentation, and tracking. But it will not work with training.

Hope this helps! Let me know if you have any additional questions.
Thanks
