### ISSUE TITLE
Faster dataset scanning

### ISSUE THREAD

**Issue by fcakyon** [ultralytics/ultralytics#579]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

A 100k image dataset takes around 20-30 mins to scan before training starts.

It is taking seconds when v5loader=True.

Can you update yolov8 loader to scan dataset faster (maybe utilizing threads)?

### Use case

With faster dataset scanning, we could save 20-30 mins per training.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@Laughing-q any ideas?

**Comment by glenn-jocher** [comment]
@fcakyon this was caused a few versions ago from a threadpool to pool switch in the v8loader, but has since been resolved. Latest pip uses identical threadpool processing for both v8 and v5 dataloaders. Can you try again with latest to verify issue is resolved? Thanks!
