### ISSUE TITLE
Robloflow labels are incorrent when uploading because of extra line

### ISSUE THREAD

**Issue by guillermovc** [ultralytics/ultralytics#5798]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hello everyone!, 
Recently i have been facing a problem when i uploaded my new labeled images predicted by a YOLO model (using predict) to Roboflow, the platform was not recognizing label names with its corresponding id's, which caused that you couldn't use your model to label new images.
I've sent a support ticket to Roboflow team and they fixed this, i just open this issue for they who are facing the same problem and to make ultralytics team that there was this little issue. I know it is easy to create a script to trim the .txt files but since ultralytics has really well integration with roboflow platform i think they will fix this to work seamlessly.

Hope i can help creating this issue, have a nice day.
Thank you.

![image](https://github.com/ultralytics/ultralytics/assets/43889001/2c770936-ca7e-4677-881f-54442f021d16)
![image](https://github.com/ultralytics/ultralytics/assets/43889001/c13584e9-a0b4-4df8-85d1-a731c0673889)

### Environment

Ultralytics 8.0.200

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
Thank you, @guillermovc, for sharing this information. We will certainly review it. Much appreciated.

**Comment by yeldarby** [comment]
Just a heads up we fixed this on the Roboflow side already. Thanks for reporting.

**Comment by glenn-jocher** [comment]
@yeldarby thank you for letting us know, and for your swift response and support in handling this issue on the Roboflow side. Your assistance helps ensure a smoother experience for all YOLOv8 users. We appreciate your collaboration and hope to continue working together to improve our shared community.
