### ISSUE TITLE
In predict mode, the device setting doesn't work.

### ISSUE THREAD

**Issue by HtwoOtwo** [ultralytics/ultralytics#5801]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

![image](https://github.com/ultralytics/ultralytics/assets/24851046/90b93358-5b57-44dc-8a7f-e2d73d6c73de)
Although i set ` device="1" `, the device is set back to 0, as shown in the above figure. 

I think the problem lies in https://github.com/ultralytics/ultralytics/blob/b9b0fd8bf409c822b7fcb21d65722b242f5307fc/ultralytics/utils/torch_utils.py#L134-L137
device is set to cuda:0 regardless of your device setting.

### Environment

Ultralytics YOLOv8.0.196 🚀 Python-3.10.13 torch-2.1.0 CUDA:0 (NVIDIA GeForce RTX 4090, 24217MiB)
Setup complete ✅ (96 CPUs, 503.5 GB RAM, 161.5/641.4 GB disk)

OS                  Linux-6.1.0-13-amd64-x86_64-with-glibc2.31
Environment         Linux
Python              3.10.13
Install             pip
RAM                 503.53 GB
CPU                 Intel Xeon Gold 5318Y 2.10GHz
CUDA                11.8

matplotlib          ✅ 3.8.0>=3.3.0
numpy               ✅ 1.26.1>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.28.2>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 2.1.0>=1.8.0
torchvision         ✅ 0.16.0>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.1.1>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

nvidia-smi:
![image](https://github.com/ultralytics/ultralytics/assets/24851046/bb8cadc2-68d9-42e7-ba67-5de28e59668e)

### Minimal Reproducible Example

```
from ultralytics import YOLO

yolo = YOLO("path to your model")
res = yolo("path to your image", device="1")
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@HtwoOtwo thank you for bringing this to our attention and volunteering to submit a PR!

Your inquiry seems to revolve around the device setting apparently not being respected in 'predict' mode. You're correct, the python code snippet you've pointed out does seem to set the device to 'cuda:0' regardless of your input.

The intended use of the `device` option is to allow the user to specify the hardware acceleration approach for model inference. For instance, a user might want to force the use of CPU even if CUDA-compatible GPUs are available, or specify a particular GPU device for CUDA operations. 

We appreciate your contribution and it sounds like it's worthy of further investigation to improve our handling of multi-GPU and CPU-GPU combinations. Please submit your PR and the team will review it. Your contribution will help YOLO v8 accommodate a wider variety of hardware configurations.

Thank you once again for your contribution! Is there anything else we can assist you with?
