### ISSUE TITLE
Issue with Generated Weight Saving Paths During Training

### ISSUE THREAD

**Issue by Dddzihan** [ultralytics/ultralytics#5802]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![JNPGQQC}1A72(N(0KLZJMBB](https://github.com/ultralytics/ultralytics/assets/103739748/287fa831-103d-4303-a5c7-5e4b3cb65cf7)
Why are the runs files generated during YOLOv8 training always saved in this fixed path rather than in the root directory of the project? Even when I retrain using the Ultralytics source code downloaded from GitHub, they are still stored in this path.

**Comment by glenn-jocher** [comment]
@Dddzihan thanks for reaching out!

The saving path you see is part of YOLOv8's design. During training, model weights, logs, and results are generally stored in a run directory, usually in the format `runs/train/exp`. 

Each new training creates its own directory (like `exp2`, `exp3`, and so on) to keep things organized and to prevent overwriting previous results. This allows you to conveniently compare different training runs.

This location is usually relative to where you run your script from, not necessarily the project's root directory. 

If you want to change the directory where files are saved, you can adjust the code accordingly. However, having self-contained directories is a good practice in ensuring reproducibility and avoiding clutter.

Also, while retraining or rerunning the model, it's normal to still see results in this path. This is because every new run generates a new experiment directory, maintaining the structure for the simplicity of result interpretation. 

Let us know if you have further questions. I hope this helps!

**Comment by Dddzihan** [comment]
Thank you very much for your response. I believe I didn't explain my issue clearly. Currently, when I train in a new project, the generated weight files still have the fixed path as shown in the picture and are not saved in the new project directory. Could you please provide a more detailed explanation? Thank you very much.

**Comment by PiyushKamboj1503** [comment]
> Thank you very much for your response. I believe I didn't explain my issue clearly. Currently, when I train in a new project, the generated weight files still have the fixed path as shown in the picture and are not saved in the new project directory. Could you please provide a more detailed explanation? Thank you very much.

@Dddzihan in your configured environment, you can use the cli command 'yolo settings' to see the information related to the saving directory. You can modify the same in the config and settings file to get your models to save in the correct directory. I hope this helps you

**Comment by Dddzihan** [comment]
Thank you for your response. When I input the CLI command 'yolo settings,' it displays this path. Why is it not the path of my current project?
![image](https://github.com/ultralytics/ultralytics/assets/103739748/c0b89403-9647-4f99-bf7d-cf18e3e7cec3)

**Comment by Dddzihan** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/103739748/f970dfa4-8767-4867-ba74-a1f65e7be5be)

**Comment by Dddzihan** [comment]
My project path is 'E:\Project_deeplearning\ultralytics,' but the 'runs' directory is located in 'E:\GitHub Project\Seg_YoloV8\runs.'

**Comment by PiyushKamboj1503** [comment]
@Dddzihan @glenn-jocher this is actually something that needs to be examined deeply. Even on few instances I have seen that the results are saved in some directory/project which is not even a subdirectory of the project from where I am running the script from.
For example:
My Train Script Directory is: '/home/projects/project1/workspace.py
My Runs saving directory is: '/home/projects/project2/runs/predict/train(n)

however, it is worth noting that this is environment specific. When I made the enviroment, I was working in project2 but when I utlilised the same environment in Project1 using conda, the runs still goes to the project2 directory. 

![image](https://github.com/ultralytics/ultralytics/assets/54760385/09229c65-ebbb-47ce-a801-f0f30d0fac78)

**Comment by PiyushKamboj1503** [comment]
@Dddzihan however, the fix to this is here: 

from ultralytics import settings

# Update a setting
settings.update({'runs_dir': '/path/to/runs'})

# Update multiple settings
settings.update({'runs_dir': '/path/to/runs', 'tensorboard': False})

# Reset settings to default values
settings.reset()

as mentioned in https://docs.ultralytics.com/quickstart/?h=settings#modifying-settings

**Comment by glenn-jocher** [comment]
@PiyushKamboj1503, I'm glad your issue has been resolved!

If you've set your 'runs_dir' to a specific folder and you want to maintain this for future projects, you do not need to reset the settings – they will persist. However, if you intend to have the runs directory change per project, then you would need to update the settings to the new path for each project accordingly. 

If your current project setting meets your needs, there is no need to reset it every time you start a new project. Only reset or change the settings when you need to modify the path of the runs directory, or any other settings, for successive projects.

Remember that the primary use case of the settings feature is to help you manage global settings persistently across different projects and contexts, and it's designed to provide flexibility in how you organize and manage your workflows and files.

Let me know if you have any further questions!
