### ISSUE TITLE
howto change the format of output

### ISSUE THREAD

**Issue by youthong** [ultralytics/ultralytics#5805]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

how can I change the format of output when I finish the predict?such from avi(default) to mp4

**Comment by glenn-jocher** [comment]
Hello @youthong,

Thank you for reaching out and your interest in YOLOv8!

In YOLOv8, the format of the output video from the prediction function is handled in the predictor.py script. The 'VideoWriter' class, which is used for assembling the frames into a video, takes a parameter to specify the output format. Normally, this is set to output AVI format.

To change into MP4 format, you would need to adjust this parameter in the 'VideoWriter' instance - particularly modifying the 'fourcc' property, a code that signifies the video codec to be used. For an mp4 format, you would update this 'fourcc' code to represent mp4.

However, I'd like to caution you that any change to the source code may affect the software operation and stability. Therefore, should you encounter any difficulties, just revert to the original code or feel free to ask for help here.

I hope this answers your question. Let me know if you need more guidance!

**Comment by youthong** [comment]
OK，thanks for reply.I have resolve this question

**Comment by glenn-jocher** [comment]
Hi @youthong,

Great to hear that you've managed to solve the problem! If you run into any other challenges or have additional questions about YOLOv8, don't hesitate to reach out. We're here to help. Enjoy using YOLOv8!

Best,
Glenn Jocher

**Comment by Shaadalam9** [comment]
Hello @glenn-jocher ,
I am also trying to save the model in mp4 format.
I am using these lines of codes

`model = YOLO(params.model)
model.predict(source = f"{params.output_path}/{video_title}_{params.resolution}.mp4", save= True, save_frames = False, conf= params.confidence, 
              save_txt=False, show=params.render, line_thickness = params.line_thickness, 
              hide_labels= params.hide_labels, hide_conf = params.hide_conf)`

But I am not able to change to do so

**Comment by glenn-jocher** [comment]
Yes, if you update the specified file in your conda environment's Ultralytics package, it should output videos in .mp4 format by default when you load the package in your environment.
