### ISSUE TITLE
IndexError: index 1 is out of bounds for dimension 1 with size 1

### ISSUE THREAD

**Issue by manoj-samal** [ultralytics/ultralytics#5807]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

i have tried to train a model in yolov8 but gave me this error

### Environment

i'm doing this in google-colab

### Minimal Reproducible Example

Ultralytics YOLOv8.0.200 🚀 Python-3.10.12 torch-2.0.1+cu118 CPU (Intel Xeon 2.20GHz)
engine/trainer: task=segment, mode=train, model=yolov8n-seg.pt, data=/content/drive/MyDrive/road_data/data.yaml, epochs=20, patience=50, batch=4, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=1, project=/content/drive/MyDrive/road_data/, name=train3, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=/content/drive/MyDrive/road_data/train3
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]           
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]                  
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]                
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]                 
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 22        [15, 18, 21]  1   1004275  ultralytics.nn.modules.head.Segment          [1, 32, 64, [64, 128, 256]]   
YOLOv8n-seg summary: 261 layers, 3263811 parameters, 3263795 gradients, 12.1 GFLOPs

Transferred 381/417 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir /content/drive/MyDrive/road_data/train3', view at http://localhost:6006/
Freezing layer 'model.22.dfl.conv.weight'
train: Scanning /content/drive/MyDrive/road_data/train/labels.cache... 400 images, 2 backgrounds, 2 corrupt: 100%|██████████| 402/402 [00:00<?, ?it/s]
train: WARNING ⚠️ /content/drive/MyDrive/road_data/train/images/Autopista_Taylor-_Chicken-_Alaska-_Estados_Unidos-_2017-08-28-_DD_102_jpg.rf.865fe07abd9674e2ca0c5d1413741ccd.jpg: ignoring corrupt image/label: Label class 2 exceeds dataset class count 1. Possible class labels are 0-0
train: WARNING ⚠️ /content/drive/MyDrive/road_data/train/images/back0506b_jpg.rf.95f6d47bbc7a663a6df32a97045d0e35.jpg: ignoring corrupt image/label: Label class 2 exceeds dataset class count 1. Possible class labels are 0-0
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
val: Scanning /content/drive/MyDrive/road_data/valid/labels.cache... 11 images, 0 backgrounds, 0 corrupt: 100%|██████████| 11/11 [00:00<?, ?it/s]
Plotting labels to /content/drive/MyDrive/road_data/train3/labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.0005), 76 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to /content/drive/MyDrive/road_data/train3
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/100 [00:03<?, ?it/s]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-4-091e0abdaf27>](https://localhost:8080/#) in <cell line: 10>()
      8 
      9 # Use the model
---> 10 results = model.train(data="/content/drive/MyDrive/road_data/data.yaml", epochs=20, workers=1, batch=4,imgsz=640 , project ="/content/drive/MyDrive/road_data/" )  # train the model

11 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/utils/tal.py](https://localhost:8080/#) in get_box_metrics(self, pd_scores, pd_bboxes, gt_labels, gt_bboxes, mask_gt)
    153         ind[1] = gt_labels.squeeze(-1)  # b, max_num_obj
    154         # Get the scores of each grid for each gt cls
--> 155         bbox_scores[mask_gt] = pd_scores[ind[0], :, ind[1]][mask_gt]  # b, max_num_obj, h*w
    156 
    157         # (b, max_num_obj, 1, 4), (b, 1, h*w, 4)

IndexError: index 1 is out of bounds for dimension 1 with size 1

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@manoj-samal hello,

Thank you for reaching out. The error message indicates an 'IndexError: index 1 is out of bounds for dimension 1 with size 1'. This suggests that there might be a dimension mismatch in the array you're using. It seems you might be trying to access an element with index 1 in a dimension that only has 1 element (i.e., index 0).

This issue could potentially originate from several scenarios. 

One possibility is that there might only be one class being detected in your dataset, but the code somewhere seems to be expecting more than one class. Confirm that your dataset is correctly formatted and that the number of classes defined matches what's in your dataset. 

The error could also arise if the label indices used in the segmentation task don't match the classification task. Make sure that label indexing is consistent throughout the whole processing pipeline. 

Also, specifically for YOLOv8, make sure that your training data and configuration file align correctly, particularly with regards to the number of output classes.

I hope this helps! If the error persists after checking these factors, please do not hesitate to follow up with additional information on your dataset or configurations.

Best regards.

**Comment by manoj-samal** [comment]
Hi @glenn-jocher  I got to know that I had 2 classes in my labels were in txt we should have only one class when we have given `number of classes = 1` in yaml file

**Comment by manoj-samal** [comment]
thank you it helped

**Comment by glenn-jocher** [comment]
@manoj-samal hello,

I'm glad to hear that you've identified the source of the problem. Indeed, for every project, the number of classes in the labels should match the number of classes specified in your YAML configuration file.

In your case, it seems that your YAML file is set up for one class (class count 1), but there are instances of class 2 in your dataset (as indicated by the "Label class 2 exceeds dataset class count 1" warning). Since zero-indexing is used, this implies that you have two classes in your labels (class 0 and class 1) instead of one.

You must ensure that your labels only contain class indices that correspond to the classes defined in your YAML file. If you only have one class, all labels should be 0.

Please rectify this mismatch, and your YOLOv8 training should carry on without any issues. Happy training!

Best regards.
