### ISSUE TITLE
Inferencing on a stream

### ISSUE THREAD

**Issue by vivekbharadhwajsa** [ultralytics/ultralytics#581]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I have checked the YOLO8 repo and the inference applies to images and videos if the path is given. But I cannot pass an image variable to the predict function. If a stream is proivided as a variable to the predict function, the `p = str(Path(p).resolve())` throws an error and the inference on stream cannot be applied. 

Is there a way to do something like `model(open-cv-image-variable, conf=0.25, return_outputs=True)` or `model(PIL-image-variable, conf=0.25, return_outputs=True)` ? 
This feature would be really helpful than having to always give paths or strings as inputs to the predict function

### Use case

This is a very useful feature for many people who really want to use YOLOv8 but are slightly limited because it cannot be readily applied on a stream

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by vivekbharadhwajsa** [comment]
The new version of PIP ultralytics üackage has a Stream loader LoadPilAndNumpy

**Comment by pderrenger** [comment]
@vivekbharadhwajsa hello! Thanks for reaching out. 😊 I appreciate your interest in leveraging YOLOv8 for stream inferencing. 

Great news! In the latest PIP package update, a new stream loader `LoadPilAndNumpy` has been added, enabling you to directly pass PIL or NumPy image variables to the `predict` function. This allows for seamless inferencing on image streams without the need for providing file paths. 

Feel free to update your PIP package and give it a try. If you have any more questions or need further assistance, please don't hesitate to ask!
