### ISSUE TITLE
Adding Deep Sort and Strong Sort to YOLOv8

### ISSUE THREAD

**Issue by chinhong11** [ultralytics/ultralytics#5815]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi, is it possible for Ultralytics to add the Deep Sort and Strong Sort algorithm as well into YOLOv8 as I need to use it in my project now. Thank you very much.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@chinhong11 hi there,

Thank you for your interest in extending the capabilities of YOLOv8. We always appreciate innovative ideas from our user community!

Adding Deep Sort and Strong Sort algorithms directly into YOLOv8 is quite an interesting proposal. These algorithms have proven their effectiveness in object tracking, which can certainly complement the object detection capabilities of YOLOv8. However, adding these might also complicate the overall architecture and may not align with the general objectives and design simplicity of YOLOv8.

That being said, our current focus on the YOLOv8 project involves enhancing object detection performance and efficiency and any decision to integrate additional algorithms would be governed by these priorities.

To use Deep Sort and Strong Sort in your project, a practical approach could be deploying YOLOv8 for the object detection phase and then feeding the detection results into separate Deep Sort and Strong Sort models for the object tracking phase.

Although we appreciate your generous offer to contribute, decisions about incorporating additional functionalities must align with the core goals of this project. We encourage you to implement the hybrid approach using both YOLOv8 and the sorting algorithms in your own fork, and then sharing your experience with the community to enable others to benefit from your work.

Thank you again for your interest and involvement in the YOLOv8 project!

Best regards,
Glenn Jocher
