### ISSUE TITLE
YOLOv7 and YOLO-NAS does not show the summary of training results

### ISSUE THREAD

**Issue by ramonseugling** [ultralytics/ultralytics#5819]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am running tests with YOLOv7 and YOLO-NAS, and they do not provide a training results summary like YOLOv5 and YOLOv8. Is there any way to obtain these results from training?

YOLOv7:
![image](https://github.com/ultralytics/ultralytics/assets/49564337/24479a00-c08a-41cb-8aa8-3e73b28ca275)

YOLO-NAS:
![image](https://github.com/ultralytics/ultralytics/assets/49564337/5f236d11-6f21-4bf7-ab39-b7c0a74c12c4)

What I want (YOLOv8 example):
![image](https://github.com/ultralytics/ultralytics/assets/49564337/4741db42-9ebb-4e1d-a4d6-4090f6a6c3cb)

**Comment by glenn-jocher** [comment]
@ramonseugling hello and thank you for your question!

Both YOLOv7 and YOLO-NAS have slightly different output schematics from YOLOv8. Currently, they do not directly provide a training results summary in the same format as YOLOv8. 

That said, it is possible to obtain similar metrics outlined in YOLOv8 training summary by leveraging the logging functionality built into these models. You can access information like training and validation loss, mAP, and other details from the log files generated during model training. Please ensure logging is enabled and configured correctly to capture these details. 

Do note that it may require some additional work to parse and format these logs into a summary similar to the one presented in YOLOv8. The support for a similar summary in YOLOv7 and YOLO-NAS for future versions is a feature request we could consider implementing based on user demand.

Your feedback is very useful and contributes to improving our services. Thanks once again for reaching out!

**Comment by ramonseugling** [comment]
Thanks @glenn-jocher

**Comment by glenn-jocher** [comment]
@ramonseugling hello, I appreciate your message. 

If you're looking to get a summary of training results for YOLOv7 and YOLO-NAS similar to what you see in YOLOv8, it's currently not a direct feature in these models. While YOLOv8 includes a comprehensive training summary, YOLOv7 and YOLO-NAS operate slightly differently. 

That said, you can still access comparable metrics by utilizing the logging system that is integrated into these models during training. Using this feature, you should be able to generate logs that contain metrics like training and validation losses, precision, recall, and mAP, among others. These logs could then be parsed and converted into a summary view.

I'll also take your feedback into account as we continue to develop these models. A summary view feature in YOLOv7 and YOLO-NAS might be something we can look into for future releases, depending on user needs.

As always, your feedback helps guide our continued efforts to improve. Thank you for your contribution to the YOLOv8 project's success.
