### ISSUE TITLE
key point detection

### ISSUE THREAD

**Issue by RamatovInomjon** [ultralytics/ultralytics#583]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi there. Thanks for the great project! I wanted to know if you are planning to add landmark/key point detection with detection model, (it might be:face landmark, human pose , or custom object key points).

### Use case

It can be used for face alignment, human pose estimation, hand gesture recognition, custom object alignment (for example : licence plate detection and recognition, if there possibility of licence plate alignments  recognition accuracy will be much higher , for this task we need licence plate's corner key points, and so on)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Yes, we are planning to add keypoint tasks in the future whenever we are able to prioritize that. Thanks!

**Comment by Otabeek** [comment]
Inomjon Yahshimisiz? siz bilan qanaqa qilib boglansek boladi?

**Comment by Otabeek** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.
> 
> ### Description
> Hi there. Thanks for the great project! I wanted to know if you are planning to add landmark/key point detection with detection model, (it might be:face landmark, human pose , or custom object key points).
> 
> ### Use case
> It can be used for face alignment, human pose estimation, hand gesture recognition, custom object alignment (for example : licence plate detection and recognition, if there possibility of licence plate alignments recognition accuracy will be much higher , for this task we need licence plate's corner key points, and so on)
> 
> ### Additional
> _No response_
> 
> ### Are you willing to submit a PR?
> * [ ]  Yes I'd like to help by submitting a PR!

Inomjon Yahshimisiz siz bilan qanaqa qilib boglansek boladi?

**Comment by RamatovInomjon** [comment]
> 

inomjonramatov7@gmail.com yoki @InomjonRamatov telegram

**Comment by RamatovInomjon** [comment]
> 

inomjonramatov7@gmail.com yoki @InomjonRamatov telegram

**Comment by FlyleafPaopao** [comment]
Hi, my repo may help. https://github.com/FlyleafPaopao/yolov8-multi-keypoint
