### ISSUE TITLE
Error Running EdgeTPU Model With PyCoral

### ISSUE THREAD

**Issue by Craftzman7** [ultralytics/ultralytics#5876]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict, Export

### Bug

When attempting to run the Minimal Reproducible Example (MRE) I get this error. For context I have trained my own model using the Yolo CLI. In this case I am using `yolov8n`. I have exported it to Tflite using the following code:

```python
model.export(format='tflite', imgsz=256, int8=True)
```

I used the EdgeTPU compiler to compile the Tflite model to EdgeTPU. Using the following command:
```
edgetpu_compiler runs/detect/train/weights/best_saved_model/best_full_integer_quant.tflite 
```

Error from MRE:

```
Traceback (most recent call last):
  File "C:\Users\user\Desktop\bunnybots-YOLO\webcam_pi.py", line 46, in <module>
    objs = get_objects(interpreter, 0.7)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pycoral\adapters\detect.py", line 214, in get_objects
    elif common.output_tensor(interpreter, 3).size == 1:
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pycoral\adapters\common.py", line 29, in output_tensor
    return interpreter.tensor(interpreter.get_output_details()[i]['index'])()
IndexError: list index out of range
```

### Environment

```
Ultralytics YOLOv8.0.134  Python-3.9.13 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce RTX 4070 Ti, 12282MiB)
Setup complete  (32 CPUs, 31.8 GB RAM, 454.2/917.6 GB disk)
```

### Minimal Reproducible Example

```python
import cv2

from pycoral.utils.edgetpu import make_interpreter
from pycoral.utils.edgetpu import run_inference
from pycoral.utils.dataset import read_label_file
from pycoral.adapters.common import input_size
from pycoral.adapters.detect import get_objects

def append_objs_to_img(cv2_im, inference_size, objs, labels):
    height, width = cv2_im.shape
    scale_x, scale_y = width / inference_size[0], height / inference_size[1]
    for obj in objs:
        bbox = obj.bbox.scale(scale_x, scale_y)
        x0, y0 = int(bbox.xmin), int(bbox.ymin)
        x1, y1 = int(bbox.xmax), int(bbox.ymax)

        percent = int(100 * obj.score)
        label = '{}% {}'.format(percent, labels.get(obj.id, obj.id))

        cv2_im = cv2.rectangle(cv2_im, (x0, y0), (x1, y1), (0, 255, 0), 2)
        cv2_im = cv2.putText(cv2_im, label, (x0, y0+30),
                             cv2.FONT_HERSHEY_SIMPLEX, 1.0, (255, 0, 0), 2)
    return cv2_im

interpreter = make_interpreter("model.tflite")
interpreter.allocate_tensors()
labels = read_label_file("labels.txt")
inference_size = input_size(interpreter)
cap = cv2.VideoCapture(0)
frame_width = int(cap.get(3)) 
frame_height = int(cap.get(4)) 
size = (frame_width, frame_height) 
result = cv2.VideoWriter('out.avi',  
                         cv2.VideoWriter_fourcc(*'MJPG'), 
                         10, size) 

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    cv2_im = frame

    cv2_im_rgb = cv2.cvtColor(cv2_im, cv2.COLOR_BGR2RGB)
    cv2_im_rgb = cv2.resize(cv2_im_rgb, inference_size)
    run_inference(interpreter, cv2_im_rgb.tobytes())
    objs = get_objects(interpreter, 0.7)
    cv2_im = append_objs_to_img(cv2_im, inference_size, objs, labels)

    # write frame to disk 
    result.write(frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

```

### Additional

I've already had a look at #4869 and still get the error.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Craftzman7 i'm sorry to hear that you're experiencing this error. It seems that the function `output_tensor` is trying to access an index that doesn't exist in the output details of the interpreter. This might mean that the model you are using doesn't follow the same structure that `pycoral` expects. 

Here are some steps to help with your debugging process: 

1. **Check the model's output description**: Try printing out `interpreter.get_output_details()` to understand the structure of the model's output. The information you find here might differ from what you expect, indicating the source of the problem.

2. **Check the quantization steps**: There might be an issue with your export and subsequent quantization using the Edge TPU compiler. Make sure each process has been executed correctly. 

Remember that various third party libraries like `pycoral` might support specific model structures — not all YOLOv8 outputs may be compatible. It would be best if you can confirm `pycoral`'s compatibility with your model. If you find that it is not compatible, you may want to explore other inference libraries, or create your own inference function. 

Feel free to provide any additional insights or ask further questions! We would be equally keen to know the solution to your problem.

**Comment by FoxieK** [comment]
Hello! sorry for reopening this issue, but i think i think my problem is quite related to this one.

I've trained and exported successfully a YOLOv8 model using `yolo export model={MODEL_PATH} format=edgetpu int8=True imgsz=192` into a quantized compatible model for my coral edgetpu.
![image](https://github.com/ultralytics/ultralytics/assets/92261030/4e973583-e799-4dd3-847e-cc6733a362d0)
which it looks like this in netron: 
![image](https://github.com/ultralytics/ultralytics/assets/92261030/0197d6af-8534-4ecd-9f83-a195a2331d25)
![image](https://github.com/ultralytics/ultralytics/assets/92261030/23922273-fb09-445d-bb0a-c593a6ef1064)
So my output tensor has a shape of `(1,5,756)` because i down scaled the images to 192x192px and detect only 1 class.

The problem is when i use this model to do inference using pycoral libraries, i encountered the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "webstream_edgetpu.py", line 157, in detect_motion
    objs = get_objects(interpreter, 0.25)
  File "/opt/plcnext/.local/lib/python3.8/site-packages/pycoral/adapters/detect.py", line 214, in get_objects
    elif common.output_tensor(interpreter, 3).size == 1:
  File "/opt/plcnext/.local/lib/python3.8/site-packages/pycoral/adapters/common.py", line 29, in output_tensor
    return interpreter.tensor(interpreter.get_output_details()[i]['index'])()
IndexError: list index out of range
```
The error is generated by this piece of code:
```
run_inference(interpreter, cv2_im_rgb.tobytes())
objs = get_objects(interpreter, 0.25) <--- The error is here
cv2_im = append_objs_to_img(cv2_im, inference_size, objs, labels)
```
I think the problem here is that the `get_objects()` function tries to iterate on the output data but i only got one index:
```
[{'name': 'PartitionedCall:0', 'index': 1, 'shape': array([  1,   5, 756], dtype=int32), 'shape_signature': array([  1,   5, 756], dtype=int32), 'dtype': <class 'numpy.int8'>, 'quantization': (0.013924574479460716, -117), 'quantization_parameters': {'scales': array([0.01392457], dtype=float32), 'zero_points': array([-117], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
```

So i tried something else:
```
output_data = interpreter.get_tensor(output_details[0]['index'])[0]
```
and the `output_data` tensor looks like this:
```
[[-113 -109 -107 ...  -92  -76  -69]
 [-112 -111 -113 ...  -51  -52  -51]
 [-108 -102  -97 ...   46   67   15]
 [-107 -105 -109 ...   24   23   36]
 [-117 -117 -117 ... -117 -117 -117]]
```

Now the fact is i don't know how to decode the bounding box coordinates, class score, and other relevant information from that tensor which row is the bboxes, scores etc..?
How did you manage to read the data and draw the bboxes and scores? @Craftzman7 

If someone knows please let me know, thank you!

**Comment by FoxieK** [comment]
Ok but how did you fixed this error in particular?

```
> Traceback (most recent call last):
>   File "C:\Users\user\Desktop\bunnybots-YOLO\webcam_pi.py", line 46, in <module>
>     objs = get_objects(interpreter, 0.7)
>   File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pycoral\adapters\detect.py", line 214, in get_objects
>     elif common.output_tensor(interpreter, 3).size == 1:
>   File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pycoral\adapters\common.py", line 29, in output_tensor
>     return interpreter.tensor(interpreter.get_output_details()[i]['index'])()
> IndexError: list index out of range

That error is caused here:
> while cap.isOpened():
>     ret, frame = cap.read()
>     if not ret:
>         break
>     cv2_im = frame
> 
>     cv2_im_rgb = cv2.cvtColor(cv2_im, cv2.COLOR_BGR2RGB)
>     cv2_im_rgb = cv2.resize(cv2_im_rgb, inference_size)
>     run_inference(interpreter, cv2_im_rgb.tobytes())
>     objs = get_objects(interpreter, 0.7) <---- HERE
>     cv2_im = append_objs_to_img(cv2_im, inference_size, objs, labels)

My code is nearly the same, that's why i was asking you about the fix

**Comment by glenn-jocher** [comment]
@Craftzman7 i understand the frustration with compatibility issues. It seems that the `pycoral` library expects a certain output tensor structure that may not align with the YOLOv8 EdgeTPU export. If the `pycoral` library is not compatible with the YOLOv8 EdgeTPU model structure, using an alternative model or library that is known to work with the EdgeTPU, as you did with `tflite-model-maker` and `efficientdetlite0`, is a practical solution. 

For future reference, if anyone encounters similar issues, exploring other models or libraries that are confirmed to be compatible with the EdgeTPU, or waiting for updates that address these compatibility issues, would be the recommended course of action. Thank you for sharing your workaround!
