### ISSUE TITLE
results manipulation

### ISSUE THREAD

**Issue by coder-glitche** [ultralytics/ultralytics#5881]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hey @glenn-jocher im facing doubts in accesing and matching bounding box coordinates of the detection model lets say i have a image with 6 detection im unable to match the bounding box coordinates as there maybe many images with same coordinate iwant to match their b box cordinates with their cropped image names.

say 1.jpg had 1 circles 1 triangle 1 circle and then 1 rectangle and then 1 more triangle then the model  would have saved them in output_folder  under test1-->crops-->respective_class_named subfolder,so under the triangle 2 triangles would be saved as 1.jpg and 12.jpg and 13.jpg and circles would be saved as 1.jpg 12.jpg under circle folder .so now for all of these we are supposed to match class_indexes class names and bounding boxes and save them with respective cropped image path

how do i match them idk the logic to even extract the class name and bbox coordinates and list them or sort them as there can be multiple instances of same class in prediction list

can you please help me with a python snippet.

**Comment by glenn-jocher** [comment]
@coder-glitche hello,

Thank you for your interest in our YOLOv8 repo and the detailed explanation of your issue!

To obtain bounding box coordinates and class names, you'll want to explore the structure of the output tensor from the model's inference method. The output tensor will typically have a shape similar to (N, 6), where N is the number of detected objects. Each detection is represented by a row in the tensor, and the row's components typically represent the following: [x1, y1, x2, y2, objectness score, class].

As for sorting the detections and cropping them based on the class, you can loop through the detections, storing the bounding box data and class information for each.

Moreover, in YOLOv8, the class_id correspond to indices in a list of class labels that is provided when initializing the model. This list of labels is also used when saving cropped images into class-named subfolders, like you mentioned in your post.

To correlate files in your 'crops' directories with the original detections, consider saving the detected objects using a naming scheme that includes the class name and the original detection's index within the output tensor.

Please note that this explanation is kept general and might need minor adjustments based on the actual configuration and setup of your model.

I hope this helps to clarify your issue! Please don't hesitate to raise a new issue in the repo if you have further questions.

Best,
Glenn
