### ISSUE TITLE
Does yolov8 have an official paper？

### ISSUE THREAD

**Issue by 8410ttt** [ultralytics/ultralytics#5887]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Does yolov8 have an official paper？I would like to know more details.

**Comment by RizwanMunawar** [comment]
@8410ttt There is no official paper on YOLOv8, but rather a series of improvements and extensions made by Ultralytics to the YOLOv5 architecture. Most of the changes made in YOLOv8 relate to model scaling and architecture tweaks, which can be found in the code and the documentation in the Ultralytics YOLOv8 repository. For more information, you can visit mentioned links.

Ultralytics GitHub: https://github.com/ultralytics/ultralytics
Ultralytics Docs: https://docs.ultralytics.com/

Hope this helps! Let me know if you have any additional questions.
Thanks
