### ISSUE TITLE
Cannot get confidence using model.predict() on model segment

### ISSUE THREAD

**Issue by minwim** [ultralytics/ultralytics#5890]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

using **save_txt = true,  save = true,**, 
under the folder labels， i get  123.txt.
context as bleow:

**1 0.522359 0.370833 0.521044 0.371875 0.521044 0.377083 0.522359 0.378125 0.523674 0.378125 0.526305 0.380208 0.526305 0.38125 0.52762 0.382292 0.528935 0.382292 0.530251 0.38125 0.531566 0.38125 0.531566 0.376042 0.526305 0.371875 0.52499 0.371875 0.523674 0.370833
2 0.296138 0.2625 0.294822 0.263542 0.294822 0.302083 0.296138 0.303125 0.296138 0.304167 0.297453 0.304167 0.297453 0.303125 0.298768 0.302083 0.298768 0.298958 0.300083 0.297917 0.300083 0.295833 0.298768 0.294792 0.298768 0.263542 0.297453 0.2625**

![image](https://github.com/ultralytics/ultralytics/assets/86920530/8a804bcf-84eb-4890-9735-8114cb406533)
can't find confidence on saved txt
why?

### Additional

no additional

**Comment by RizwanMunawar** [comment]
Indeed, when using the `save_txt=True` option for object segmentation in YOLOv8, the confidence score will not be included unless you also include the option `save_conf=True`. 

For more information, you can refer to the [Ultralytics YOLOv8 Inference Arguments](https://docs.ultralytics.com/modes/predict/#inference-arguments) for more details.

Hope this helps! Let me know if you have any additional questions.
Thanks
