### ISSUE TITLE
Yolov8CPPInference  compile error make error

### ISSUE THREAD

**Issue by xx-xxx** [ultralytics/ultralytics#5893]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I encountered a compilation error，Probably a ld problem 
i run make command.it's encountered not found libgio-2.0.so.0 .

/usr/bin/ld: warning: libgio-2.0.so.0, needed by /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_emblemed_icon_get_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_task_return_error'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_drive_get_icon'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_app_info_launch_default_for_uri'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_task_set_name'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_task_get_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_mount_get_icon'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_info_get_display_name'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_hash'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_volume_get_name'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_enumerate_children_finish'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_find_enclosing_mount'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_get_child_for_display_name'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_themed_icon_new'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_equal'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_mount_operation_set_anonymous'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_info_set_attribute'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0: undefined reference to `g_app_launch_context_get_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_bus_get_sync'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_volume_monitor_get_mounts'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_query_info'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_enumerator_close_finish'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_info_get_is_hidden'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_load_contents'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_resolve_relative_path'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_icon_get_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_mount_get_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_is_native'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_input_stream_read'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `g_list_model_items_changed'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_dbus_connection_call'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_mount_enclosing_volume'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_drive_get_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_content_type_is_a'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_drive_is_media_removable'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_get_basename'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_dbus_connection_call_finish'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_info_set_attribute_boolean'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_volume_get_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_monitor_file'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_cancellable_new'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_content_type_equals'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_task_set_return_on_cancel'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_volume_get_drive'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_get_path'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0: undefined reference to `g_app_info_get_icon'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_drive_poll_for_media'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_info_get_modification_time'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_themed_icon_new_with_default_fallbacks'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_task_return_new_error'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_monitor_cancel'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_resources_open_stream'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_emblemed_icon_get_icon'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_content_type_guess'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_volume_get_activation_root'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_mount_get_name'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_drive_is_media_check_automatic'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_volume_monitor_get'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_volume_monitor_get_connected_drives'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_task_is_valid'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_query_info_finish'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_task_run_in_thread'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_icon_new'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_task_propagate_pointer'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_icon_get_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_loadable_icon_load'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_mount_enclosing_volume_finish'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_info_get_icon'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_mount_get_root'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_enumerate_children_async'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_mount_operation_get_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_emblemed_icon_get_emblems'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_get_parse_name'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0: undefined reference to `g_app_info_get_name'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_themed_icon_get_names'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_info_dup'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_task_set_source_tag'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_io_error_quark'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_info_get_file_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_content_type_get_icon'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0: undefined reference to `g_app_info_get_executable'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_mount_get_volume'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_get_parent'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_drive_poll_for_media_finish'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_themed_icon_get_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_memory_input_stream_new_from_bytes'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_query_exists'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_query_info_async'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_cancellable_cancel'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_info_get_attribute_data'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_dbus_connection_call_sync'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_mount_operation_set_password_save'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_task_return_boolean'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_resources_lookup_data'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_info_has_attribute'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined reference to `g_list_model_get_n_items'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_get_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_task_propagate_boolean'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0: undefined reference to `g_desktop_app_info_get_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_has_prefix'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_task_get_cancellable'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_enumerator_close_async'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_cancellable_is_cancelled'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_volume_mount'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_task_get_source_tag'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0: undefined reference to `g_desktop_app_info_get_filename'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_output_stream_get_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_input_stream_read_bytes_async'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_task_new'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_emblem_get_icon'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_get_uri'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_info_get_attribute_byte_string'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_make_directory'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_task_had_error'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_drive_get_name'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_get_child'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_mount_operation_set_password'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_input_stream_read_bytes_finish'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_monitor_directory'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_info_get_size'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_info_get_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_mount_operation_reply'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_new_for_path'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_enumerator_next_files_finish'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_volume_monitor_get_volumes'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_content_type_from_mime_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_mount_operation_set_domain'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_mount_operation_set_username'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_new_for_uri'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_resources_get_info'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_task_get_name'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_output_stream_write'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_io_error_from_errno'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_drive_get_volumes'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_info_get_name'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_cancellable_get_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_icon_get_file'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_replace_contents'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_loadable_icon_get_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_task_get_task_data'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_info_get_content_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_mount_operation_set_choice'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_volume_mount_finish'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_input_stream_get_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_task_return_pointer'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_content_type_get_mime_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_volume_get_icon'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `g_list_model_get_type'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_volume_get_mount'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_info_get_is_backup'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_enumerator_next_files_async'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_parse_name'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined reference to `g_task_set_task_data'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_file_info_get_attribute_as_string'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0: undefined reference to `g_mount_operation_get_password_save'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/Yolov8CPPInference.dir/build.make:127: Yolov8CPPInference] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/Yolov8CPPInference.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

### Additional

i run this `sudo apt-get install libglib2.0-dev`.
i got `Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libglib2.0-dev is already the newest version (2.72.4-0ubuntu2.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

i run this`locate libgio-2.0.so.0`
i got `/home/lhj/anaconda3/lib/libgio-2.0.so.0
/home/lhj/anaconda3/lib/libgio-2.0.so.0.6901.0
/home/lhj/anaconda3/pkgs/glib-2.69.1-he621ea3_2/lib/libgio-2.0.so.0
/home/lhj/anaconda3/pkgs/glib-2.69.1-he621ea3_2/lib/libgio-2.0.so.0.6901.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/x86_64-linux-gnu/libgio-2.0.so.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/x86_64-linux-gnu/libgio-2.0.so.0.7200.4`

not found in /lib/x86_64-linux-gnu/  but in /anaconda3/lib/ what's i cound do?I've been troubled by this problem for a long time.If anyone can give advice, thank you very much！！！

**Comment by xx-xxx** [comment]
The problem was solved by removed the anaconda environment variable

**Comment by glenn-jocher** [comment]
@xx-xxx great to hear that you were able to solve the issue by removing the Anaconda environment variable. It seems your system configuration or other installed packages within that environment may have been causing a conflict. For future reference, users encountering similar issues can consider manipulating their environment variables or creating a new environment.

Remember to keep your Anaconda environment clean and isolated to avoid such conflicts. Thanks for using YOLOv8 and we look forward to assisting you with any further queries you may have. Happy coding!
