### ISSUE TITLE
plot result

### ISSUE THREAD

**Issue by lkw052715** [ultralytics/ultralytics#5896]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

If I want to print on each frame of the video, the target category and the corresponding number on the image of that frame, how do I do it?

**Comment by glenn-jocher** [comment]
@lkw052715 hi, thanks for your interest in using YOLOv8!

To achieve the task of printing the target category and the corresponding number on each frame of the video, you would use the 'Predict' mode of YOLOv8. During runtime, as the frames are processed, you can extract the class labels and their counts that the model predicts.

The results of the prediction include a list of bounding boxes, each containing the coordinates of the box, the confidence score, and the class label. When the prediction is completed for each frame, you can iterate through these results to count the number of each class label that is detected, which is the target category and corresponding number you want.

To print these on the image of that particular frame, you'll want to use a library that can handle image manipulation or annotation, such as Pillow or OpenCV. With these libraries, you can draw text or shapes directly onto the images before saving or displaying them.

Remember, for real-time applications you will want to ensure this additional processing doesn't slow down the overall frame rate too significantly.

I hope this helps! Please let us know if you have any other questions.
