### ISSUE TITLE
How to get a boolean mask array for each class from segmentation?

### ISSUE THREAD

**Issue by KDeser** [ultralytics/ultralytics#5905]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Using the most current version of the YOLOv8 segmentation model, how would I obtain in numpy an array that indicates all pixels belonging to a given class?  For example, I would like to know which pixels contain a person, dog, cat, etc. 

Thanks!

**Comment by glenn-jocher** [comment]
@KDeser hello, I appreciate your question regarding object segmentation using YOLOv8.

The functionality you are asking about is known as semantic segmentation. This process produces a mask over an image where each pixel in the mask corresponds to a specific class, such as person, dog, cat, etc. 

To obtain a numpy array that illustrates this mask, you would first need to run inference with your model on an input image. The resulting output will be a 2D tensor where the value of each element corresponds to the class of the object at the corresponding pixel location in the input image. 

This 2D tensor, or mask, can easily be converted to a numpy array. Just remember that the numerical value of each pixel in the output numpy array will correspond to the class of the same pixel in the input image.

You can then loop over the unique class labels present in the mask to create individual binary masks for each class. In the binary masks, pixels belonging to the respective class would be marked as `True`, and all other pixels would be marked as `False`.

I hope this explanation helps guide you in accomplishing your task. Don't hesitate to comment if you need further clarification.

**Comment by KDeser** [comment]
Thanks Glenn!

**Comment by glenn-jocher** [comment]
@KDeser you're welcome! If you have any more questions or require further clarifications, feel free to ask. Remember, the strength of open-source projects like YOLOv8 lies in the community’s collaborative effort to continually improve and extend its capabilities. Let's keep the conversation going to make YOLOv8 even better for everyone. Thanks again for your interest and support. Happy developing!
