### ISSUE TITLE
How to get training's information from terminal?

### ISSUE THREAD

**Issue by Thangtran27** [ultralytics/ultralytics#5910]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am creating an application for training yolov8 by PyQt5 and I want to display training's information into QPlaintextedit. How can I get this?

![image](https://github.com/ultralytics/ultralytics/assets/93766218/2e4f4cb8-148b-4a50-b25a-7b318a0da224)

**Comment by glenn-jocher** [comment]
@Thangtran27 hello,

The YOLOv8 model outputs an extensive log of training information directly to the terminal, which includes details such as current epoch, batch number, loss metrics, precision and recall, among other metrics. This output is available anytime you train the model.

If you want to redirect this information into a PyQt5 QPlainTextEdit widget, you'll need to launch your training script as a subprocess from within your PyQt5 application. When you do this, you can capture the stdout (standard output) and stderr (standard error) of the training process, which includes all the log messages printed to the console. Then you can redirect these messages to your QPlainTextEdit widget.

The Python subprocess module's subprocess.Popen() function could be useful here. It allows you to spawn new processes, connect to their input/output/error pipes, and obtain their return codes. 

Please keep in mind that parsing and organizing these logs in a meaningful way to display into your PyQt5 application will be a programming task you'll need to work through. 

Hope this helps, and happy coding!

**Comment by Thangtran27** [comment]
thanks
