### ISSUE TITLE
Using argparse results in error

### ISSUE THREAD

**Issue by minwim** [ultralytics/ultralytics#5919]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

when i train my own data , i use scripts as below:
from ultralytics import YOLO

import argparse

# parser = argparse.ArgumentParser(description='Command line arguments example')
# parser.add_argument('--dfgdfgdfg', help='opset version (optional)', type=int, default=2)
# args = parser.parse_args()

def run():
    # Load a model
    modelpath = '/home/disk/wlm/yolov8/segment/workspace/models/weights/best.pt'
    pretrainedModel  = modelpath
    model = YOLO(pretrainedModel)  # load a pretrained model (recommended for training)
    print(f'train------')
    # Train the model
    model.train(data='/home/disk/wlm/yolov8/segment/workspace/yaml/infect_asc1_1016.yaml', 
                epochs=2, 
                imgsz=[320,320], 
                batch= 20,
                device = [0,1,2,3],
                workers= 12,
                patience = 200
                # resume = True
                )   
if __name__ == '__main__':
    print(f'start-----')
    run()

**It can be trained sucess!**

but  When I use parser, script as below:

from ultralytics import YOLO

import argparse

**_parser = argparse.ArgumentParser(description='Command line arguments example')
parser.add_argument('--dfgdfgdfg', help='opset version (optional)', type=int, default=2)
args = parser.parse_args()_**

def run():
    # Load a model
    modelpath = '/home/disk/wlm/yolov8/segment/workspace/models/weights/best.pt'
    pretrainedModel  = modelpath
    model = YOLO(pretrainedModel)  # load a pretrained model (recommended for training)
    print(f'train------')
    # Train the model
    model.train(data='/home/disk/wlm/yolov8/segment/workspace/yaml/infect_asc1_1016.yaml', 
                epochs=2, 
                imgsz=[320,320], 
                batch= 20,
                device = [0,1,2,3],
                workers= 12,
                patience = 200
                # resume = True
                )   
if __name__ == '__main__':
    print(f'start-----')
    run()

it occurs errorr: logs as below:
start-----
train------
^AUltralytics YOLOv8.0.199 🚀 Python-3.8.18 torch-1.8.0+cu111 CUDA:0 (NVIDIA RTX A4000, 16117MiB)
                                                            CUDA:1 (NVIDIA RTX A4000, 16117MiB)
                                                            CUDA:2 (NVIDIA GeForce RTX 2080 Ti, 11019MiB)
                                                            CUDA:3 (NVIDIA GeForce RTX 2080 Ti, 11019MiB)
WARNING ⚠️ Upgrade to torch>=2.0.0 for deterministic training.
engine/trainer: task=segment, mode=train, model=/home/disk/wlm/yolov8/segment/workspace/models/weights/best.pt, data=/home/disk/wlm/yolov8/segment/workspace/yaml/infect_asc1_1016.yaml, epochs=2, patience=200, batch=20, imgsz=[320, 320], save=True, save_period=-1, cache=False, device=[0, 1, 2, 3], workers=12, project=None, name=train11, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs/segment/train11

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]           
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]                  
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]                
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]                 
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 22        [15, 18, 21]  1   1004860  ultralytics.nn.modules.head.Segment          [4, 32, 64, [64, 128, 256]]   
YOLOv8n-seg summary: 261 layers, 3264396 parameters, 3264380 gradients, 12.1 GFLOPs

Transferred 417/417 items from pretrained weights
DDP: debug command /home/data/anaconda3/envs/v8_env/bin/python -m torch.distributed.launch --nproc_per_node 4 --master_port 59901 /home/disk/wlm/yolov8/segment/workspace/mytrain.py
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
usage: mytrain.py [-h] [--dfgdfgdfg DFGDFGDFG]
mytrain.py: error: unrecognized arguments: --local_rank=3
usage: mytrain.py [-h] [--dfgdfgdfg DFGDFGDFG]
mytrain.py: error: unrecognized arguments: --local_rank=0
Killing subprocess 52925
Killing subprocess 52926
Killing subprocess 52927
Killing subprocess 52929
Traceback (most recent call last):
  File "/home/data/anaconda3/envs/v8_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/data/anaconda3/envs/v8_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/data/anaconda3/envs/v8_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/data/anaconda3/envs/v8_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/data/anaconda3/envs/v8_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/data/anaconda3/envs/v8_env/bin/python', '-u', '/home/disk/wlm/yolov8/segment/workspace/mytrain.py', '--local_rank=3']' returned non-zero exit status 2.
Traceback (most recent call last):
  File "mytrain.py", line 27, in <module>
    run()
  File "mytrain.py", line 16, in run
    model.train(data='/home/disk/wlm/yolov8/segment/workspace/yaml/infect_asc1_1016.yaml', 
  File "/home/data/anaconda3/envs/v8_env/lib/python3.8/site-packages/ultralytics/engine/model.py", line 341, in train
    self.trainer.train()
  File "/home/data/anaconda3/envs/v8_env/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 187, in train
    raise e
  File "/home/data/anaconda3/envs/v8_env/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 185, in train
    subprocess.run(cmd, check=True)
  File "/home/data/anaconda3/envs/v8_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/data/anaconda3/envs/v8_env/bin/python', '-m', 'torch.distributed.launch', '--nproc_per_node', '4', '--master_port', '59901', '/home/disk/wlm/yolov8/segment/workspace/mytrain.py']' returned non-zero exit status 1.

### Additional

Will the parser module affect training? **How to solve this problem? When I need parser to pass parameters**

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@minwim argparse works correctly for in my example script here:

```python
import argparse

from ultralytics import YOLO


def main(epochs: int, imgsz: int):
    """
    Train a YOLO model with the given epochs and image size.

    Args:
        epochs (int): Number of epochs for training.
        imgsz (int): Image size for training.
    """
    # Load a model
    model = YOLO('yolov8n.pt')  # Load a pretrained model (recommended for training)

    # Train the model
    results = model.train(data='coco128.yaml', epochs=epochs, imgsz=imgsz)
    print(f"Training complete. Results: {results}")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Train a YOLO model.')
    parser.add_argument('--epochs', type=int, default=100, help='Number of epochs for training.')
    parser.add_argument('--imgsz', type=int, default=640, help='Image size for training.')
    args = parser.parse_args()

    main(args.epochs, args.imgsz)
```


<img width="1707" alt="Screenshot 2023-10-26 at 20 02 56" src="https://github.com/ultralytics/ultralytics/assets/26833433/bee42752-9308-49c5-a567-6bb1223396ec">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by cy810557** [comment]
Hi, @glenn-jocher, When I add multiple gpu_ids setting (e.g. device=[2,3]) in model.train function in your example script, I can reproduce @minwim 's issue:

Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
usage: samples.py [-h] [--epochs EPOCHS] [--imgsz IMGSZ]
samples.py: error: unrecognized arguments: --local_rank=0
usage: samples.py [-h] [--epochs EPOCHS] [--imgsz IMGSZ]
samples.py: error: unrecognized arguments: --local_rank=1
Killing subprocess 49239
Killing subprocess 49240
