### ISSUE TITLE
Change the fixed confidence threshold of the trained model

### ISSUE THREAD

**Issue by houdewu** [ultralytics/ultralytics#5929]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

yolov8 automatically matches the optimal solution to get the summary model, but I want to get a recall rate and precision rate model with a fixed confidence threshold. Due to the particularity of the data, I have to sacrifice the accuracy rate to ensure the recall rate as high as possible, but I don't understand how to get such a summary model with a fixed confidence threshold. Normally trained models balance these two values

**Comment by PiyushKamboj1503** [comment]
@houdewu you want to add the threshold in training or prediciton?

**Comment by houdewu** [comment]
> 是否要在训练或预测中添加阈值？

Hello, Master, here's the thing. My predecessors on scaled yolov4 adjusted the confidence threshold to 0.054, sacrificing part of the accuracy while greatly improving the recall rate, to about p=50%,r=93%. But I, with the same data, With yolov8, only a balance state such as p=75% and r=75% was obtained. I don't know what went wrong. I looked up the data and it seems that the confidence threshold cannot be changed during training, but the model he obtained during training is already such an indicator

**Comment by glenn-jocher** [comment]
@houdewu hello,

In the YOLOv8 model, the confidence threshold is indeed harder to manipulate during training. Generally, the model is designed to strike a good balance between precision (p) and recall (r) rates in its default state. If you seek to improve the recall rate at the expense of precision, there are a few parameters you could consider adjusting, particularly during inference:

1. **Confidence Threshold**: Lowering the confidence threshold means that the model will be more likely to predict an object even if it's not very certain. This change can increase the recall rate (more objects are identified), but at the expense of precision (more false positives).

2. **Non-Maximum Suppression (NMS) Threshold**: Increasing the NMS threshold allows more overlapping bounding boxes to be retained. This change could lead to higher recall as well since more detections are kept, but again, the rate of false positives might increase.

3. **Anchor Boxes Configuration**: The configuration of anchor boxes can also impact the precision-recall trade-off. You could experiment with the number, size, and ratios of these anchor boxes.

Remember, adjusting these parameters is not a simple task and requires a deep understanding of your data and the model. It will always be a balancing act between precision and recall based on your specific needs. 

I hope this helps, and good luck with your work!

**Comment by houdewu** [comment]
> @houdewu hello,
> 
> In the YOLOv8 model, the confidence threshold is indeed harder to manipulate during training. Generally, the model is designed to strike a good balance between precision (p) and recall (r) rates in its default state. If you seek to improve the recall rate at the expense of precision, there are a few parameters you could consider adjusting, particularly during inference:
> 
> 1. **Confidence Threshold**: Lowering the confidence threshold means that the model will be more likely to predict an object even if it's not very certain. This change can increase the recall rate (more objects are identified), but at the expense of precision (more false positives).
> 2. **Non-Maximum Suppression (NMS) Threshold**: Increasing the NMS threshold allows more overlapping bounding boxes to be retained. This change could lead to higher recall as well since more detections are kept, but again, the rate of false positives might increase.
> 3. **Anchor Boxes Configuration**: The configuration of anchor boxes can also impact the precision-recall trade-off. You could experiment with the number, size, and ratios of these anchor boxes.
> 
> Remember, adjusting these parameters is not a simple task and requires a deep understanding of your data and the model. It will always be a balancing act between precision and recall based on your specific needs.
> 
> I hope this helps, and good luck with your work!



> @houdewu hello,
> 
> In the YOLOv8 model, the confidence threshold is indeed harder to manipulate during training. Generally, the model is designed to strike a good balance between precision (p) and recall (r) rates in its default state. If you seek to improve the recall rate at the expense of precision, there are a few parameters you could consider adjusting, particularly during inference:
> 
> 1. **Confidence Threshold**: Lowering the confidence threshold means that the model will be more likely to predict an object even if it's not very certain. This change can increase the recall rate (more objects are identified), but at the expense of precision (more false positives).
> 2. **Non-Maximum Suppression (NMS) Threshold**: Increasing the NMS threshold allows more overlapping bounding boxes to be retained. This change could lead to higher recall as well since more detections are kept, but again, the rate of false positives might increase.
> 3. **Anchor Boxes Configuration**: The configuration of anchor boxes can also impact the precision-recall trade-off. You could experiment with the number, size, and ratios of these anchor boxes.
> 
> Remember, adjusting these parameters is not a simple task and requires a deep understanding of your data and the model. It will always be a balancing act between precision and recall based on your specific needs.
> 
> I hope this helps, and good luck with your work!

Thank you for your help. I also want to ask if I can't set the confidence threshold in the training file, does it mean that the threshold cannot be adjusted during the training? Could you please advise which file code should be found and modified? Due to the particularity of my data set, the recall rate should be increased as much as possible, and the accuracy rate is not particularly important. At present, all the indicators (except these two values) have been improved, so I am very eager to know the solution. I am wondering why the training results of scaled yolov4 have a high recall rate and low accuracy rate, but yolov8 can not directly change them. Thank you again for your patience.

**Comment by houdewu** [comment]
> @houdewu hello,
> 
> In the YOLOv8 model, the confidence threshold is indeed harder to manipulate during training. Generally, the model is designed to strike a good balance between precision (p) and recall (r) rates in its default state. If you seek to improve the recall rate at the expense of precision, there are a few parameters you could consider adjusting, particularly during inference:
> 
> 1. **Confidence Threshold**: Lowering the confidence threshold means that the model will be more likely to predict an object even if it's not very certain. This change can increase the recall rate (more objects are identified), but at the expense of precision (more false positives).
> 2. **Non-Maximum Suppression (NMS) Threshold**: Increasing the NMS threshold allows more overlapping bounding boxes to be retained. This change could lead to higher recall as well since more detections are kept, but again, the rate of false positives might increase.
> 3. **Anchor Boxes Configuration**: The configuration of anchor boxes can also impact the precision-recall trade-off. You could experiment with the number, size, and ratios of these anchor boxes.
> 
> Remember, adjusting these parameters is not a simple task and requires a deep understanding of your data and the model. It will always be a balancing act between precision and recall based on your specific needs.
> 
> I hope this helps, and good luck with your work!

@glenn-jocher Hello!
Thank you for your help. I also want to ask if I can't set the confidence threshold in the training file, does it mean that the threshold cannot be adjusted during the training? Could you please advise which file code should be found and modified? Due to the particularity of my data set, the recall rate should be increased as much as possible, and the accuracy rate is not particularly important. At present, all the indicators (except these two values) have been improved, so I am very eager to know the solution. I am wondering why the training results of scaled yolov4 have a high recall rate and low accuracy rate, but yolov8 can not directly change them. Thank you again for your patience.

**Comment by glenn-jocher** [comment]
@houdewu In YOLOv8, the confidence threshold is more associated with the post-processing step after the model makes its predictions, not directly during the training itself. Consequently, there isn't typically a setting within the training file where you could manipulate this threshold. 

With respect to your particular use-case of prioritizing recall rate over precision, you can experiment with tweaking the confidence threshold, the Non-Maximum Suppression (NMS) threshold, and Anchor Boxes Configuration during the prediction or inference stages after the model has been trained. 

Lowering the confidence threshold can help the model identify more objects (increase the recall rate) even at the risk of making uncertain predictions. Likewise, increasing the NMS threshold can retain more overlapping bounding boxes, possibly leading to higher recall. Altering the parameters of the anchor boxes can also impact the precision-recall balance. 

In comparison to Scaled-YOLOv4, YOLOv8 may have different underlying optimization strategies that result in different precision-recall outcomes at default settings. 

Remember that making such adjustments will necessitate a deep understanding of your dataset and iterative experimentations to get optimal outcomes for your specific needs. 

I hope this clarifies your concerns. Good luck with your project!
