### ISSUE TITLE
Plot more label while Training

### ISSUE THREAD

**Issue by sezer-muhammed** [ultralytics/ultralytics#593]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

It would be good to see more training sample images in order to follow if there is any mistake in dataset

### Use case

Some labels in my dataset are shifting while training with --rect but Im not sure if its dataset problem or not. So I need to draw more labels while training

### Additional

there might be arg like this plot=90
then draws 90 training batch in the folder

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@sezer-muhammed hi there! 🌟 It's great to see your enthusiasm for enhancing the training visualization in YOLOv8. To address your use case, we recommend using the [Val](https://docs.ultralytics.com/modes/val) mode following your training run. The Val mode visualizes predictions on the validation set, allowing you to inspect how the model is performing and verify if there are any erroneous labels or shifts.

While there isn't a built-in option to plot additional training sample images during the training process, analyzing the validation results can help troubleshoot any label shifting issues. Keep an eye on the bounding box predictions in the validation images to identify and rectify any dataset anomalies. 

Your proactive approach and willingness to submit a PR are truly appreciated! If you have any further questions or need assistance with the PR, feel free to ask. Good luck with your dataset refinement! 🚀
