### ISSUE TITLE
yolov8 running best.pt on Jetson Nano

### ISSUE THREAD

**Issue by issamadine** [ultralytics/ultralytics#594]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can install ultralytics for ubuntu

**Comment by prince0310** [comment]
go to your terminal and try  `pip install ultralytics`

**Comment by Denizzje** [comment]
I think Jetson Nano is on Python 3.6 by default, you should check if its possible to get on 3.7 or above first. Then indeed try to install ultralytics via pip. The nano is too weak to run any other model than perhaps a nano sized model natively though you should try to get it to run with TensorRT.

**Comment by MAVProxyUser** [comment]
hand compile cmake-3.25.2.tar.gz  Python-3.10.0.tar.xz torch vision branch v0.13.0, and PyTorch release/1.12. Then pip install the requirements explicitly using 3.10. Do not try to use 3.11, you will fail.

**Comment by MAVProxyUser** [comment]
"The nano is too weak to run any other model than perhaps a nano sized model natively based on my experience with yolov5." 

v7 runs MUCH better than v5 fwiw. Your python version can absolutely make a difference on performance too. 

![FnNYJCyWIAEojcN](https://user-images.githubusercontent.com/2904396/214225525-9f6cf8f8-39ad-4ba0-a88c-c7372a65382c.png)

![FnNmYrJWAAAw1n6](https://user-images.githubusercontent.com/2904396/214225542-fcf1df57-2fb5-4f0c-9137-8a5c37b5604c.jpeg)

**Comment by AyushExel** [comment]
It's possible to run v8 models on jetson devices. We currently don't have an official tutorial yet but we'll have that in coming weeks.

**Comment by merhovon** [comment]
> It's possible to run v8 models on jetson devices. We currently don't have an official tutorial yet but we'll have that in coming weeks.

Any Updates?

**Comment by oriaj3** [comment]
> https://github.com/triple-Mu/YOLOv8-TensorRT You can try in jetson using this repo.`TensorRT`

Is this the way to run YOLOv8 to get the best speed in Jetson?  

Or is it better to use ultralytics directly in a python script?

**Comment by triple-Mu** [comment]
> > https://github.com/triple-Mu/YOLOv8-TensorRT You can try in jetson using this repo.`TensorRT`
> 
> Is this the way to run YOLOv8 to get the best speed in Jetson?
> 
> Or is it better to use ultralytics directly in a python script?

You'd best try cpp to speed up your YOLOv8 model.
There is an example in https://github.com/triple-Mu/YOLOv8-TensorRT in `csrc/detect/end2end`.
Python is slower in Jetson.

**Comment by oriaj3** [comment]
> > > https://github.com/triple-Mu/YOLOv8-TensorRT Puede probar Jetson usando este repositorio.`TensorRT`
> > 
> > 
> > ¿Es esta la forma de ejecutar YOLOv8 para obtener la mejor velocidad en Jetson?
> > ¿O es mejor usar ultralíticos directamente en un script de python?
> 
> Será mejor que pruebe cpp para acelerar su modelo YOLOv8. Hay un ejemplo en https://github.com/triple-Mu/YOLOv8-TensorRT en formato `csrc/detect/end2end`. Python es más lento en Jetson.

Thank you very much, I will try to try it this week.

**Comment by glenn-jocher** [comment]
@oriaj3 you're welcome! Good luck and feel free to reach out if you have any other questions or issues.
