### ISSUE TITLE
.tif image files where the pixel values range between 0 to 1.

### ISSUE THREAD

**Issue by has12zen** [ultralytics/ultralytics#5946]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have .tif image files where the pixel values range between 0 to 1 and I am trying to train a yolo model on them. but yolo is saying the images are currupted. I can convert them to normal pixel values but it is leading to data losss. 
what are the supproted image types i know yolo supports .tif but what about float values?

**Comment by glenn-jocher** [comment]
@has12zen thank you for your inquiry!

The Ultralytics YOLOv8 is primarily designed to handle image types like `.jpg`, `.jpeg`, `.png` and `.bmp` that conform to standard 8-bit representations, with pixel values typically ranging from 0-255. While it can also handle `.tif` images, the pixel value range of 0 to 1 (floating-point representation) may be the reason why the model perceives the images as corrupted.

One solution to overcome this, as you've mentioned, is to rescale the images to have pixel values in the standard 8-bit range (0-255). While this can possibly introduce minimal data loss or distortion, it generally shouldn't substantially impact the performance of the model.

At the moment, YOLOv8 does not natively support float values in image datasets. We continuously strive to enhance the functionality of our models based on community feedback like yours. We'll take your inquiry on board for future reference and potential improvements.

Feel free to follow up with further questions if any. Your contribution to the Ultralytics community is truly appreciated!
