### ISSUE TITLE
Coreml is not working in Xcode

### ISSUE THREAD

**Issue by spyhunter1280** [ultralytics/ultralytics#5948]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, everyone!
I have trained yolov8 mode with custom datasets.

```
yolo = YOLO('yolov8n.pt')
yolo.train(data='./data.yaml', epochs=25)
valid_results = yolo.val()
print(valid_results)
```

```
model=YOLO('./runs/detect/train/weights/best.pt')

model.export(format='coreml', nms=True)
```

All things were good
I imported coreml in Xcode successfully
I open the model in Xcode, and click the preview panel
and drag and drop the image in preview panel
But model doesn't detect the object.

Please help me

**Comment by glenn-jocher** [comment]
@spyhunter1280 thanks for the bug report! I see the same result. If I run a CoreML model Xcode crashes.

In this case it's best to reach out to Apple and Xcode's support teams directly for more specialized assistance. They should be able to provide you with in-depth troubleshooting and possibly a fix for the issue you're facing.

Nothing on our side has changed with regards to CoreML exports, so this may be due to updated in macOS or Xcode.

<img width="1112" alt="Screenshot 2023-10-27 at 12 47 50" src="https://github.com/ultralytics/ultralytics/assets/26833433/1b7bb913-be33-4880-aa6a-b6ec8caccbc2">

**Comment by glenn-jocher** [comment]
@sergiossm looks like Xcode inference is no longer working :(

**Comment by spyhunter1280** [comment]
> @sergiossm looks like Xcode inference is no longer working :(

Thanks for your consideration.
Do you think, the reason is in Xcode?

**Comment by spyhunter1280** [comment]
@glenn-jocher  
Hello
I am trying to convert yolov8 model to CoreML(Neural Network)
TO do this, I downed the python version to 3.8
also downed the coremLtools version
But it requires only coremltools 7.0
How can I export to CoreML(Neural Network)

**Comment by glenn-jocher** [comment]
@spyhunter1280 hi there,

The requirements for YOLOv8 model conversion to CoreML are Python 3.7 or later and coremltools. The coremltools version required depends on the specific functionalities you want to use. If you want to use the NeuralNetworkBuilder, it requires coremltools version 0.8. Older versions of coremltools might not have the necessary tools for the conversion process.

However, if you're facing issues with version compatibility, an effective workaround could be setting up a new Python virtual environment where you can install the specific Python and coremltools versions needed without disturbing your global Python environment.

Please keep in mind that the output CoreML model adheres to the version of coremltools used for conversion, and the CoreML model versioning can have consequences on which devices can support the model.

In addition, please ensure your PyTorch version is compatible with the coremltools version you're using for the conversion, as incompatibilities between these libraries can sometimes occur, which might cause the model conversion to fail.

Ultimately, if you have followed the steps properly and still can't convert the model, it might be a good idea to report the specific error or issues you're facing. There might be a bug or an unforeseen incompatibility affecting your conversion process. We continually strive to improve our documentation and tools based on user feedback and error reports, so your experience is vital to us.

Hope this helps, and let us know if you still face any issues!

**Comment by all-for-code** [comment]
> @spyhunter1280 thanks for the bug report! I see the same result. If I run a CoreML model Xcode crashes.
> 
> In this case it's best to reach out to Apple and Xcode's support teams directly for more specialized assistance. They should be able to provide you with in-depth troubleshooting and possibly a fix for the issue you're facing.
> 
> Nothing on our side has changed with regards to CoreML exports, so this may be due to updated in macOS or Xcode.
> 
> <img alt="Screenshot 2023-10-27 at 12 50 20" width="1251" src="https://private-user-images.githubusercontent.com/26833433/278620355-c636fcd5-5fcb-4e16-bbc0-804a21c62197.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDU5NDEsIm5iZiI6MTcwMTI0NTY0MSwicGF0aCI6Ii8yNjgzMzQzMy8yNzg2MjAzNTUtYzYzNmZjZDUtNWZjYi00ZTE2LWJiYzAtODA0YTIxYzYyMTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA4MTQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNjk0Yzc5ZDcyZGE5YTgyYzQyNmQ5NTMxYzE5ZjFhYjY4OGQ4NzM2MDM1MjliN2Y2NjQyOGJhNmY0MjI0Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mNuOxuDxxfqVJkKqFMzjKHLIPTBh1581bhQFdptm2K0"> <img alt="Screenshot 2023-10-27 at 12 47 50" width="1112" src="https://private-user-images.githubusercontent.com/26833433/278619850-1b7bb913-be33-4880-aa6a-b6ec8caccbc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDU5NDEsIm5iZiI6MTcwMTI0NTY0MSwicGF0aCI6Ii8yNjgzMzQzMy8yNzg2MTk4NTAtMWI3YmI5MTMtYmUzMy00ODgwLWFhNmEtYjZlYzhjYWNjYmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA4MTQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZmIxMzk5NGIxZjY5ODQwZTNiYWRhZTI3YzAxNWE5NDg3YzEwZTAxNGU1MWFhYTU1NzllMWU0NzU1OGIwNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zTi3rXQ9KkkUuoKZuy7kgovL7mc7rLBYZaHz8BNQF-U">
@glenn-jocher Hi, coreml only supported in macOS or xcode?

**Comment by glenn-jocher** [comment]
@all-for-code CoreML is an Apple technology designed primarily for integration with iOS, macOS, watchOS, and tvOS apps. While CoreML model conversions traditionally occur on a macOS machine using coremltools, the deployment and use of the CoreML models are intended for Apple's ecosystems, which include Xcode for app development. 

Regarding your conversion issue to CoreML (Neural Network) format, it sounds like you are on the right path with regard to Python and coremltools versions. If you are encountering specific error messages or issues with your environment setup, I would recommend diving into the documentation provided by coremltools and ensuring your system meets all the other dependency requirements for successful model conversion.

Keep in mind that when working with CoreML, it's not only about the support in macOS or Xcode, but it's also about the compatibility of your model with the version of coremltools you are using. In addition, the CoreML model needs to be compatible with the target device’s hardware and operating system version, as there might be certain features of CoreML that only work with specific versions of iOS, for example.

Remember to consider the compatibility across these different components for successful deployment of your YOLOv8 model in an Apple environment. If you continue to face difficulties exporting to CoreML, documenting the issues in detail could help the community to provide more specific guidance.
