### ISSUE TITLE
Device issue

### ISSUE THREAD

**Issue by Tsai-chia-hsiang** [ultralytics/ultralytics#5956]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I would like to ask about device problem.

![image](https://github.com/ultralytics/ultralytics/assets/84863554/b61bf3ae-60fd-4294-8f49-4f5401f59854)

But it seens that it still tries to use GPU to run.

How can I use cpu only ?
Thanks

**Comment by RizwanMunawar** [comment]
@Tsai-chia-hsiang, kindly provide additional details to help us better comprehend your query. Based on the image you've shared, it appears that the model is running on a CPU.

Thanks
