### ISSUE TITLE
Disk usage at 100% after training (Windows)

### ISSUE THREAD

**Issue by jtpaquet** [ultralytics/ultralytics#597]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I started training an image detection model last week on yolov5. I noticed that after training (cpu) my pc became really slow and that the disk usage was always at 100% to a point where it was unusable and I couldn't do anything. This weekend I factory resetted my pc because I need it to work. Everything worked fine, like a new pc.

I installed yolov8 to train with my GPU hoping it would change but no. The epochs were running way faster though. I had to abort mid training because my pc went to sleep. There were to many epochs left and I needed my computer. After that, the disk usage was at 100% and it's still really slow.

My dataset folder isn't even big, it's ~1000 images and it's size is under 30Mo. There no error whatsoever. I've seen this can be due to the images being stored sequentially on the hard drive or models that are saved in a `Temp` folder, but I'm not running that many epochs and my dataset is small.

Why does it take disk usage AFTER training is done and how can I solve this issue?

### Environment

- Yolov8: pytorch 1.13.1+cu117
- Python 3.10.4 64-bits
- OS: Windows 10 64-bits
- NVIDIA-SMI 516.01, Driver Version: 516.01, CUDA Version: 11.7
- GPU: NVIDIA GeForce GTX 1060 3GB
- HDD 1TB

### Minimal Reproducible Example

Here's the command I used for yolov5 in command line:
``
python train.py --img 640 --batch 32 --epochs 50 --data data.yaml --weights last.pt
``

And here's my script for yolov8:
```
from ultralytics import YOLO

def main():
    model = YOLO("runs/detect/train2/weights/last.pt")  # load a pretrained model (recommended for training)
    results = model.train(data="data.yaml", epochs=50, imgsz=640, batch=16, device=0) # GPU training

if __name__ == '__main__':
    main()
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AbdelsalamHaa** [comment]
@jtpaquet Hi 
I'm not sure what could  be wrong with ur PC. But wanted to check how much is your RAM ?
Btw HDD is much slower compared to SSD. so if you have SSD in ur PC I would recommend you, to move ur data to the SSD.

**Comment by knoppmyth** [comment]
Do you have the same issue if you drop the batch size to 16? I'd also try a lower resolution. While you can do training on your GPU, with only 3 GB of RAM, you're pushing it.

**Comment by glenn-jocher** [comment]
@pderrenger That's great news! 🎉 Transitioning to an SSD often provides a substantial performance boost, and it's good to hear that it's made a positive difference for your training process. Sticking with a batch size of 8 is a wise choice given your GPU's memory constraints. It's all about finding that sweet spot between batch size, resolution, and your hardware's capabilities to maintain smooth operations.

Should you run into any more issues or have additional queries, don't hesitate to ask. We're here to help! Happy training! 🚀
