### ISSUE TITLE
Objects365 pretrained model for YOLOv8

### ISSUE THREAD

**Issue by israfilagir** [ultralytics/ultralytics#5974]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can anyone provide the pretrained model on the objects365 classes for YOLOv8?

**Comment by RizwanMunawar** [comment]
We do not provide official support for pretrained models on the Objects365 dataset; our support is limited to models trained on the COCO dataset. However, you can fine-tune the Ultralytics pretrained models for use with the Objects365 dataset independently.

Hope this helps! Let me know if you have any additional questions.
Thanks
