### ISSUE TITLE
Classify Validation .val()

### ISSUE THREAD

**Issue by MouMsal** [ultralytics/ultralytics#5985]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val

### Bug

When attempting with model.val(workers = 0)
![image](https://github.com/ultralytics/ultralytics/assets/36175212/0ba316bd-ab16-478e-9f3c-be3ae834df0e)

With model.val()

![image](https://github.com/ultralytics/ultralytics/assets/36175212/ed04fbd4-2bfd-4333-8291-13defb9868db)

### Environment

Using Google Colab -
```
Ultralytics YOLOv8.0.202 🚀 Python-3.10.12 torch-2.1.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 27.4/78.2 GB disk)
```

### Minimal Reproducible Example

Training:
```
model = YOLO('yolov8n-cls.pt') 
results = model.train(data='/content/datasets',epochs = 1,imgsz=256)
```
Validate:
```
metrics = model.val()
```
Dataset used: https://www.kaggle.com/datasets/masoudnickparvar/brain-tumor-mri-dataset

### Additional

Training works as expected and even validates at the end:
![image](https://github.com/ultralytics/ultralytics/assets/36175212/33216f7b-fa3d-46e6-b10c-881f00cf26b0)

Validation works as expected when using model`.trainer.validate()` and model`.val(rect=False)` - Found by @Burhan-Q 

While I don't have any evidence, I believe this change may have been due to Ultralytics or a package update, as it was working at one point until it suddenly wasn't.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Burhan-Q** [comment]
Following up on the details provided by @MouMsal from our conversation in the Discord server.

Could be that the addition of [`custom = {'rect':True}`](https://github.com/ultralytics/ultralytics/blob/e58db228c2fd9856e7bff54a708bf5acde26fb29/ultralytics/engine/model.py#L272) in `engine/model.py` could be the source of the issue. I was able to confirm that this issue occurs when using `yolov8n-cls.pt` after training on Linux. 

## Train results
![image](https://github.com/ultralytics/ultralytics/assets/62214284/29fcaa20-5233-4bdf-bde3-e42dedef1363)

## Val method error
![image](https://github.com/ultralytics/ultralytics/assets/62214284/23174331-0a34-4256-9716-dc5988de5faa)

## Using trainer.validate() method

**Comment by Burhan-Q** [comment]
Additionally tested using `detect`, `segment`, and `pose` tasks with `nano` pretrained model starting weights. Only `classify` task appears to cause this error.

# Minimal Reproducible Examples

## No error for Detect Task

```py
from ultralytics import YOLO
m = YOLO()
m.train(data='coco128.yaml', epochs=3, val=False)
... # results from training
m.val()
... # validation results, no error occurs
```

Interim step, close python instance and start with new python instance.

## Error for Classify Task
```py
from ultralytics import YOLO
m = YOLO('yolov8n-cls.pt')
m.train(data='imagenet10', epochs=3, val=False)
... # results from training
m.val()
# validation fails, error occurs
>> RuntimeError: stack expects each tensor to be equal size, but got [3, 192, 224] at entry 0 and [3, 160, 224] at entry 2

# reattempt
m.val(rect=False)
... # no error, validation results shown
```

Interim step, close python instance and start with new python instance.

## No error for Segment Task
```py
from ultralytics import YOLO
m = YOLO('yolov8n-seg.pt')
m.train(data='coco8-seg.yaml', epochs=3, val=False)
... # results from training
m.val()
... # validation results, no error occurs
```

Interim step, close python instance and start with new python instance.

## No error for Pose Task
```py
from ultralytics import YOLO
m = YOLO('yolov8n-pose.pt')
m.train(data='coco8-pose.yaml', epochs=3, val=False)
... # results from training
m.val()
... # validation results, no error occurs
```

## Environment
Ultralytics YOLOv8.0.192 
Python 3.10.12
torch-2.0.1+cu118
POP_OS! 22.04 LTS (similar to Ubuntu) 64-bit

### Installed packages

<details>

  ```
  Package                  Version
  ------------------------ --------------------
  Brotli                   1.1.0
  certifi                  2023.7.22
  charset-normalizer       3.2.0
  cmake                    3.27.2
  contourpy                1.1.0
  cycler                   0.11.0
  Cython                   3.0.4
  filelock                 3.12.3
  fonttools                4.42.1
  idna                     3.4
  Jinja2                   3.1.2
  kiwisolver               1.4.5
  lapx                     0.5.5
  lit                      16.0.6
  MarkupSafe               2.1.3
  matplotlib               3.7.2
  mpmath                   1.3.0
  mutagen                  1.47.0
  networkx                 3.1
  numpy                    1.25.2
  nvidia-cublas-cu11       11.10.3.66
  nvidia-cuda-cupti-cu11   11.7.101
  nvidia-cuda-nvrtc-cu11   11.7.99
  nvidia-cuda-runtime-cu11 11.7.99
  nvidia-cudnn-cu11        8.5.0.96
  nvidia-cufft-cu11        10.9.0.58
  nvidia-curand-cu11       10.2.10.91
  nvidia-cusolver-cu11     11.4.0.1
  nvidia-cusparse-cu11     11.7.4.91
  nvidia-nccl-cu11         2.14.3
  nvidia-nvtx-cu11         11.7.91
  opencv-contrib-python    4.8.1.78
  packaging                23.1
  pandas                   2.1.0
  Pillow                   10.0.0
  pip                      22.0.2
  psutil                   5.9.5
  py-cpuinfo               9.0.0
  pycryptodomex            3.19.0
  pyparsing                3.0.9
  python-dateutil          2.8.2
  pytz                     2023.3
  PyYAML                   6.0.1
  requests                 2.31.0
  scipy                    1.11.2
  seaborn                  0.12.2
  setuptools               59.6.0
  six                      1.16.0
  sympy                    1.12
  thop                     0.1.1.post2209072238
  torch                    2.0.1+cu118
  torchvision              0.15.2+cu118
  tqdm                     4.66.1
  triton                   2.0.0
  typing_extensions        4.7.1
  tzdata                   2023.3
  ultralytics              8.0.192
  urllib3                  2.0.4
  websockets               12.0
  wheel                    0.41.2
  yt-dlp                   2023.10.13
  ```
  
</details>
