### ISSUE TITLE
Segmentation task bbox is something wrong in scaling

### ISSUE THREAD

**Issue by yellowjs0304** [ultralytics/ultralytics#5998]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, Thanks for steady updates.

I tried to train to predict the contour line in documents with segmentation task.
But in training, especially in scaling up(make it larger) augmentation cases, the bounding box coming out weird.. 
I can't get it why the bounding box is cracked sometimes..

example training batch : number 6, 7 Unlike the original ratio, you can see that only a very small box comes out.
<img width="688" alt="image" src="https://github.com/ultralytics/ultralytics/assets/30281608/7ec0c866-c216-4bf2-b724-1d0b85300c1e">

**Comment by glenn-jocher** [comment]
@yellowjs0304 hello,

Thanks for reaching out and for going through the existing issues before posting your question; it's much appreciated!

It definitely seems peculiar that the bounding boxes are not scaling as you'd expect. In the YOLOv8 model, the bounding boxes are typically computed based on the original image size and the augmentations applied should not alter their ratios drastically. However, in a scenario where intensive scaling up is applied, the bounding boxes calculated pre-augmentation might indeed behave peculiarly.

I'm going to suggest a couple of potential reasons this could be happening, based on what I understand from your query:

1. It could relate to how the ground truth bounding boxes were defined. If the ground truth was defined based on the original, non-scaled image, it may not translate correctly after scaling.

2. If the scaling operation is significantly large (for example, 2x, 3x, or larger), the default YOLOv8 anchoring scheme might not accommodate well. In such cases, the model would require manual adjustment in the anchor settings. 

3. Occasionally, the model might face difficulty in learning to predict the boundary when the scale or size of the boundary significantly deviates from what it has been trained on previously.

It's a bit challenging to diagnose the exact problem without a deeper dive into the specifics of your dataset and your scaling settings. If these suggestions do not shed some light on your case, don't hesitate to provide more context or further details about your scenario.

Thank you for your interest in the YOLOv8 repository, and for your participation in this community!

Best, 
Glenn

**Comment by yellowjs0304** [comment]
It's not the model results.
The above image is a training batch image(just the dataloader's preprocessed results) before training.

I just gave the config option "self.scale" to 0.7
And the original data is 2480 * 3508(A4, 200ppi)
