### ISSUE TITLE
Bad shuffle when using .txt files for train and val paths

### ISSUE THREAD

**Issue by AidanAbramson** [ultralytics/ultralytics#602]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Hi, I am reposting issue #442 as I haven't gotten any reply and I have found more details about this bug.

When I provide in the .yaml file paths to .txt files as my data paths (which is a viable option as per the YOLOv5 documentation)
.yaml file looks like this:
```
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: /mnt/ssdHot/YOLO_Dataset/640_yolov8  # dataset root dir
train: /mnt/ssdHot/YOLO_Dataset/640_yolov8/train_0.txt  # train images
val: /mnt/ssdHot/YOLO_Dataset/640_yolov8/val_0.txt  # val images
#test:   # test images (optional)

names:
  0: bird
  1: cat
  2: dog
```

Now when I train, the grids which are created just before the first epoch show completely wrong bounding boxes for the images. 
After digging and following the code, it seems that the shuffle does not shuffle the image np.ndarrays (batch['imgs']) and the bounding boxes (batch['bboxes']) together, the bounding boxes do match the image file paths (batch['img_file']) though.

I tried checking if the reason for this is maybe augmentations but after disabling all, I came to the conclusion that the problem is with the shuffling, as when I hardcoded the value to be False, it worked as it should, but resulted in bad training results.

After not getting any feeback from my original ticket, I have moved all my dataset images to two directories of images and labels and updated my .yaml file, which was not a good solution as there are many images with not much disk space. This has fixed my problem completely.

My suspicion is that it is programmed to shuffle both the image paths and bounding boxes together, as the most commonly used format of data paths is giving directory paths, and does not account for the images read from paths given by a .txt file.

### Environment

Ultralytics YOLOv8.0.17 🚀 Python-3.9.16 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3080 Ti, 12051MiB)
Python 3.9.16 (also happened on Python 3.7.15)

### Minimal Reproducible Example

create .txt files which include paths for every image (labels be at the exact same path with .txt in the end instead). Should look like this:

```
path/to/img.png
path/to/img.png
path/to/img.png
...
```

Then create an .yaml file which looks like this:
```
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: /mnt/ssdHot/YOLO_Dataset/640_yolov8  # dataset root dir
train: /mnt/ssdHot/YOLO_Dataset/640_yolov8/train_0.txt  # train images
val: /mnt/ssdHot/YOLO_Dataset/640_yolov8/val_0.txt  # val images
#test:   # test images (optional)

names:
  0: bird
  1: cat
  2: dog
```

Then train using the python API

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AidanAbramson** [comment]
In addition, it seems you simply just don't use the batch['imgs'] when reading from a directory and instead leave it a list of None, making this bug understandable. This results in the read of the image paths every batch which slows down training speed by about 2X and creates a GPU graph which looks like this: 
![image](https://user-images.githubusercontent.com/66694780/214289083-5762480c-45c1-4caf-8a40-d01726dc19f7.png)

**Comment by AyushExel** [comment]
@AidanAbramson is this dataset working as expected in yolov5? If so, you can use `v5loader=True` temporarily while we get to the bottom of this issue

**Comment by AidanAbramson** [comment]
@AyushExel Thanks for the reply, I haven't tested it with yolov5 (I am looking to see if I should upgrade from yolov7). Right now i'm still mid training, and although it doesn't have the pace i'm looking for I will have to deal with it for now. I also already moved all my images to different directories as I didn't have the space to copy all of them...😓
