### ISSUE TITLE
unable to load pt file. appears to be an ultralyticsv5 model

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/ultralytics#6023]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hi all! 

I am having issues with a trained model. I trained it with yolo V8 according to the documentation, and it went well. i also converted the PT file to onnx. 

the onnx file is working, but the PT file is not. when i try to load the PT file I get this error message:

![image](https://github.com/ultralytics/ultralytics/assets/67956327/da4357f9-779d-4e6a-acc0-6069d086b8ec)

As you can see from the netron screen it indeed is a v8 network.. what could be the reason for this? If it would be a Y5 file, the generated onnx wouldnt work too..

thank you!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MasIgor this logic is here. Your model is requesting a 'models' module that YOLOv5 has but YOLOv8 does not.

https://github.com/ultralytics/ultralytics/blob/465df3024f44fa97d4fad9986530d5a13cdabdca/ultralytics/nn/tasks.py#L546-L584

**Comment by MasIgor** [comment]
@glenn-jocher thank you, does this mean that there is something wrong in my training? how could this happen? i am training in a  conda environment where only v8 is installed. (not the newest version tough..)

**Comment by glenn-jocher** [comment]
Hi @MasIgor,

It seems like there may have been some kind of ambiguity during your training process. Even though you have ensured that you only have YOLOv8 installed, sometimes, pretrained weights from different versions could cause compatibility issues.

Normally, when you train YOLOv8 models, the output `.pt` file should contain all the necessary weights, settings, and hyperparameters that exactly match the YOLOv8 structure. When this output file deviates from this standard, loading failures can occur.

Given that YOLOv8 is installed correctly, there are a few possible reasons for this issue:

- The pretrained weights loaded during the training might have been incompatible or mismatched with YOLOv8.
- There could be a potential bug in the version of YOLOv8 that you have used for training.
- The model architecture may have been modified manually during the training process in a way that does not conform to YOLOv8.

To troubleshoot, you might want to consider the following approaches:

- Check the source or integrity of your pretrained weights if you used any.
- Confirm if there were any modifications to the model architecture during your training process.
- Try updating your YOLOv8 to the latest version and retrain your model.

I hope the above suggestions can help you resolve the problem. Please let us know how it goes, we're here to support you.

**Comment by MasIgor** [comment]
thank you, will go trhough all these steps and try to see if it solves. in the meanwhile i found out that it only happens if i load it to the GPU. not with the CPU. CPU works just fine.

**Comment by glenn-jocher** [comment]
@MasIgor i'm glad that you've found some progress in solving the problem. It's intriguing that loading the model onto the GPU causes this issue, while CPU execution works without a hitch. This suggests that the problem may lie in the GPU compatibility or setup.

It's essential to ensure that your GPU drivers, CUDA and PyTorch versions are up to date and compatible. In addition to this, keep in mind that not all operations are supported on the GPU, especially if they pertain to specific modules.

Keep trying to load the model onto the GPU while monitoring the error messages and exceptions that are thrown. They might provide more clues into why this is happening.

Should you continue to experience the issue, remember that you can always op to utilize the CPU for running your model as it seems to work as expected, albeit possibly at slower processing speeds.

I hope these suggestions can guide your debugging process. We appreciate your patience and persistence in working this out! Let us know how it goes or if you have any other queries.
