### ISSUE TITLE
DOTA class name error during coversion to yolo-obb format

### ISSUE THREAD

**Issue by vijeth-dza** [ultralytics/ultralytics#6025]
https://github.com/ultralytics/ultralytics/blob/465df3024f44fa97d4fad9986530d5a13cdabdca/ultralytics/data/converter.py#L201

Kindly change 'soccer ball-field' to 'soccer-ball-field' to resolve the error during conversion.

**Comment by glenn-jocher** [comment]
@vijeth-dza great news 😃! Your original issue may now be resolved ✅ in PR #6026. This should be merged to main and available in 8.0.204 later today or tomorrow.

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by vijeth-dza** [comment]
Thanks @glenn-jocher!

**Comment by glenn-jocher** [comment]
@vijeth-dza you're welcome! I'm glad to hear that the fix should resolve the issue. Please don't hesitate to reach out if you encounter any other challenges while using YOLOv8 or if you have additional questions. We're always here to help. Happy training!
