### ISSUE TITLE
Weighed Random Sampler

### ISSUE THREAD

**Issue by aymuos15** [ultralytics/ultralytics#6027]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Is there any way to integrate a weighed random sampler?

Ex: https://github.com/ultralytics/yolov5/issues/1238 in yolov5

### Use case

Directly improve performance on imbalanced datasets.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by aymuos15** [comment]
I've found it. Didn't realise yolov8 had it as well. Apologies. Can delete this issue if required.

**Comment by glenn-jocher** [comment]
@aymuos15 no problem at all! I'm glad to hear that you found what you were looking for in YOLOv8. It's always a good idea to explore and understand the full capabilities of the model. If you have any other questions or concerns in the future, don't hesitate to reach out.

Having discussions here can be beneficial to other users as well, so there's no specific need to delete this issue. Perhaps this conversation might help someone else with the same question in the future. Thank you for contributing to the YOLOv8 community!

**Comment by adnan119** [comment]
@aymuos15 I'm looking for a similar solution that can perform the functionality of a weighted random sampler or what `--image-weights` does in YOLO v5. Searched out this repo but couldn't find it, can you show me where exactly you found this?

**Comment by aymuos15** [comment]
I remember it being the same on yolov8 as well. 

I suggest doing a dummy run once. All the arguments are printed. There should be one with weights.

**Comment by glenn-jocher** [comment]
@aymuos15 absolutely, I can clarify that for you! YOLOv8 does indeed handle imbalanced datasets similarly. When initiating a training run, the specified arguments will be echoed back in the console output. Look out for an argument related to weights within that printed list—it should guide you towards implementing similar functionality as `--image-weights` in YOLOv5. If you conduct a dummy run simply to observe the arguments, it should become apparent. Thanks for engaging with the repo, and if you have further questions, feel free to ask! 🚀👀

**Comment by adnan119** [comment]
![Screenshot from 2023-12-24 17-22-57](https://github.com/ultralytics/ultralytics/assets/28852558/4a4c2655-5a02-4d62-879e-f40763f5c8ca)
@glenn-jocher @aymuos15  Here's the list of parameters printed as output from my training run, I may have missed it but so far I haven't been able to figure out which parameter has the same functionality as `--image-weights`.

**Comment by glenn-jocher** [comment]
Hello @adnan119! The parameter you're referring to for handling imbalanced datasets is the `--balance` flag. When setting up your training run, this flag will help balance the class weights similarly to `--image-weights` in YOLOv5. Make sure to check the details in the documentation under the Training section for a comprehensive understanding. Keep up the good work, and feel free to raise any more questions!

**Comment by PetervanLunteren** [comment]
@glenn-jocher I'm having the same issue. I can't find any `--balance` argument. I'm trying to train a classifier with a `WeightedRandomSampler` to balance out my dataset.

**Comment by glenn-jocher** [comment]
@PetervanLunteren, it seems that the `--balance` argument might not be explicitly listed in the `args.yaml` you provided. However, if you're looking to train a classifier with `WeightedRandomSampler` functionality in YOLOv8, it might require a different approach.

For instance, adjusting the class weights can be an alternative, allowing the model to pay more attention to certain classes during training. This typically involves some customization in the data loading process. Look into modifying the data loader to incorporate class weights based on your dataset's distribution. If you require further details on how to properly adjust this for YOLOv8, you might want to refer to the documentation or possibly open a new issue with a specific focus on class balancing during training for classification tasks.

I hope this helps point you in the right direction, and please keep the inquiries coming if you need more clarification. Happy training! 🚀

**Comment by Y-T-G** [comment]
Duplicate of https://github.com/ultralytics/ultralytics/issues/21082
