### ISSUE TITLE
Does Yolov8 support TensorRT exports yet 

### ISSUE THREAD

**Issue by GeorgePearse** [ultralytics/ultralytics#604]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Script or function to export models to TensorRT format. 

### Use case

To run models realtime on Jetson Orin

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by 35grain** [comment]
Not yet unfortunately, but it is definitely in the works https://github.com/ultralytics/ultralytics/pull/209. Can't wait myself either :D

**Comment by 35grain** [comment]
I believe Tensor formats are still in the works, but definitely hyped for edge tpu and tflite myself.

**Comment by triple-Mu** [comment]
https://github.com/triple-Mu/YOLOv8-TensorRT
You can try this repo for end2end detection in jetson

**Comment by pderrenger** [comment]
@triple-Mu thank you for sharing this repository! We're continually exploring various export formats, including TensorRT, to enable seamless deployment for different platforms. Our team appreciates the valuable input from the community as we work towards making YOLOv8 compatible with a wide range of inference environments. If you have any questions or need further assistance, feel free to ask!
