### ISSUE TITLE
Line thickness for the Keypoints

### ISSUE THREAD

**Issue by x0ddf** [ultralytics/ultralytics#6041]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I'm trying to find out how to control line thickness when drawing key points, but I found it impossible. Due to the static constant usage: [current implementation](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/plotting.py#L214)
Are there any plans to change it in the future?

**Comment by x0ddf** [comment]
could be easily added by merging: [this PR](https://github.com/ultralytics/ultralytics/pull/6042)

**Comment by glenn-jocher** [comment]
@x0ddf thank you for your suggestion. The pull request you mentioned seems to be a potential solution to provide control over line thickness when drawing keypoints. The Ultralytics team always appreciates constructive feedback from our community. We will take a closer look at the changes suggested in the pull request and evaluate its potential incorporation into the YOLOv8 pipeline. We strive to continuously improve the functionality of our models while maintaining coding efficiency and execution performance. Adding the capability to control line thickness could potentially provide better visual clarity for keypoints. Please remain patient while we evaluate this update. Your understanding and cooperation are much appreciated. Please feel free to submit any further suggestions or feedback you might have.

**Comment by x0ddf** [comment]
Thank you so much, I would be happy to see it merged :)

**Comment by glenn-jocher** [comment]
@x0ddf, thank you for your patience and your active contribution to improving YOLOv8. Your significant input is vital for pushing the project forward. We're happy to hear your enthusiasm and appreciation for the enhancements proposed.
  
Pull requests like these are carefully evaluated to ensure they align with our vision for YOLOv8. Changes that provide additional user control, like line thickness for keypoints, can indeed enhance user experience significantly. We're glad to have collaborative contributors like you in our community who share the same drive and passion for continual evolution and improvement. 

Stay tuned for updates on the progress and eventual decision about this pull request. We will do our best to keep you informed. Thank you, once again, for your effort and interest in advancing YOLOv8.
