### ISSUE TITLE
Outputs are different

### ISSUE THREAD

**Issue by YuhyunNa** [ultralytics/ultralytics#6047]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Hello

I've encountered a bug with Ultralytics version 8.0.203.

In the “Ultralytics YOLOv8 Docs”, it’s mentioned that there are two methods for tracking. However, the outputs are different. Specifically, the first code works perfectly as expected, while the latter one doesn't seem to function correctly.

It's worth noting that both of these codes perform the same task seamlessly when using Ultralytics version 8.0.199.

I’ve tried to find the root cause, but unfortunately, I couldn’t pinpoint it. I kindly request your assistance in resolving this bug, and if possible, could you provide insight into the solution?

Thank you for your support.

### **Tracking**

```python
from ultralytics import YOLO

# Load an official or custom model
model = YOLO('yolov8n-pose.pt')  # Load an official Pose model

# Perform tracking with the model
results = model.track(source="source.mp4", show=True, stream=False, persist=True, conf=0.5, tracker="botsort.yaml")  # Tracking with default tracker
```

### **Streaming for-loop with tracking**
```
import cv2
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('yolov8n-pose.pt')

# Open the video file
video_path = "source.mp4"
cap = cv2.VideoCapture(video_path)

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 tracking on the frame, persisting tracks between frames
        results = model.track(frame, persist=True, stream=False, conf=0.5, tracker="botsort.yaml")

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Display the annotated frame
        cv2.imshow("YOLOv8 Tracking", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()
```

### Environment

Ultralytics YOLOv8.0.203 🚀 Python-3.8.18 torch-2.1.0 CUDA:0 (NVIDIA GeForce RTX 4060 Ti, 16061MiB)
Setup complete ✅ (20 CPUs, 62.6 GB RAM, 119.3/935.5 GB disk)

OS                  Linux-5.15.0-87-generic-x86_64-with-glibc2.17
Environment         Linux
Python              3.8.18
Install             pip
RAM                 62.63 GB
CPU                 12th Gen Intel Core(TM) i7-12700F
CUDA                11.8

matplotlib          ✅ 3.7.3>=3.3.0
numpy               ✅ 1.24.3>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.0.1>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.1.0>=1.8.0
torchvision         ✅ 0.16.0>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
@YuhyunNa, could you please describe the error you're encountering?

Thanks

**Comment by glenn-jocher** [comment]
@YuhyunNa thank you for detailing the issue you're experiencing with the "Streaming for-loop with tracking" code, specifically when using Ultralytics version 8.0.203. It appears that there might indeed be a bug causing inconsistent results, especially if the same code used to work correctly with version 8.0.199. 

Our engineering team will look into this and will try to reproduce the issue using the codes and model weights you've provided as well as examining the changes between the two versions. 

We will update you as soon as possible. In the meantime, your patience is highly appreciated!

**Comment by PeterDryskull** [comment]
I am also experiencing a similar issues with recently trained models performing much worse than before. 

My task is predicting bounding boxes for images using the pre trained yolov8n.pt model and training it on the same data set as before produces a 100% false negative validation. 

I can still predict correctly by using the best weights from previous runs, and using the pre trained model without any training results in decent output, but it seems that any attempt to train the model results in bad accuracy.

**Comment by glenn-jocher** [comment]
@YuhyunNa we appreciate your report about experiencing similar issues with recent training attempts resulting in lower performance, specifically with the yolov8n.pt model. 

One possible issue could be differences in the training configuration or data preprocessing between your previous runs and the recent ones. Variations in these factors could potentially affect the model performance.

Also, another factor to consider may be the potential changes that have been introduced in recent updates of YOLOv8. These could potentially affect how the model is trained and hence the resulting performance.

Our team will investigate this issue further to identify the possible cause. In the meantime, continue to use the weights from previous successful runs, and perhaps experiment with different training parameters to see if this can improve the training performance.

We value your feedback and thank you for your patience as we work to improve and troubleshoot these issues.
