### ISSUE TITLE
Load Yolov8 models in Pytorch.

### ISSUE THREAD

**Issue by eumentis-madhurzanwar** [ultralytics/ultralytics#6048]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, 

As yolov5 has a method of loading custom models with the help _torch.hub.load()_, is there a similar method in yolov8? Or how can I load a yolov8 model with the help of torch? I don't want to use the YOLO package. Is there any other way in yolov8? If no, then what exactly YOLO() is doing ?

Thank you.

**Comment by glenn-jocher** [comment]
@eumentis-madhurzanwar hello,

Yes, you can indeed load YOLOv8 models using PyTorch. For this, you would typically use the `torch.load()` function. The loaded model can then be used for inference, further training, or whatever other purpose you have in mind.

If you refer specifically to the `torch.hub.load()` method which YOLOv5 uses, YOLOv8 follows a similar approach. If you don't want to use the YOLO package, you can directly load the models using `torch.load('path_to_your_model')`. Please make sure the path is correct and the model file is in the expected directory.

The YOLO() class is essentially a wrapper around the underlying architecture that enables the YOLO functionalities such as object detection and other computer vision tasks. This class takes care of the specifics of loading the configuration and weights of the model, setting the model in evaluation mode, and providing an interface for making predictions.

I hope this clarifies your question. If you have any other inquiries, feel free to let us know! Thanks for your interest in YOLOv8.

Best Regards,
Glenn Jocher
Ultralytics YOLOv8 Repo Maintainer

**Comment by eumentis-madhurzanwar** [comment]
Thank you for the answer. So using torch.load() it is getting loaded as a python dict and then I need to access the model['model'] part. After that why do I need to convert it into model.float()? 

And my second question - model.prerict works even if I give a image to it without converting it to tensor and without applying any normalisation whereas while writing the inference code in pytoch, without using yolo library, do I need to convert it to tensor,normalise it and then give it to the model? I'm a bit confused.

**Comment by eumentis-madhurzanwar** [comment]
I'm not able to figure out why yolov8 `model.predict` code and my custom predict code using pytorch are not able to get the same results. 
Here's my yolov8 predict code - 
`from ultralytics import YOLO
import glob
import cv2

# loading a custom model
model = YOLO('best.pt')

for images in glob.glob(path_to_test_dataset + "*.jpg"):
    image = cv2.imread(images)
    imagename_withoutextension = images.split('\\')[8]
    results = model.predict(images,imgsz=640,conf=0.25,iou=0.45)
    results = results[0]  
    for i in range(len(results.boxes)):
        box = results.boxes[i]
        tensor = box.xyxy[0]
        x1 = int(tensor[0].item())
        y1 = int(tensor[1].item())
        x2 = int(tensor[2].item())
        y2 = int(tensor[3].item())
        cv2.rectangle(image,(x1,y1),(x2,y2),(255,0,255),3)   
    cv2.imwrite(path_to_store_bounding_boxes + imagename_withoutextension,image)`

And my custom pytorch code - 
`import torch
import cv2
from torchvision import transforms


def calculate_IOU(a,b):
    areaA = a[2] * a[3]
    areaA_bottom_right_x_coordinate = a[0] + a[2]
    areaA_bottom_right_y_coordinate = a[1] + a[3]
    
    if areaA <= 0.0:
        return 0.0

    areaB = b[2] * b[3]
    
    if areaB <= 0.0:
        return 0.0

    areaB_bottom_right_x_coordinate = b[0] + b[2]
    areaB_bottom_right_y_coordinate = b[1] + b[3]

    intersection_left_x = max(a[0], b[0])
    intersection_left_y = max(a[1], b[1])
    intersection_bottom_x = min(areaA_bottom_right_x_coordinate, areaB_bottom_right_x_coordinate)
    intersection_bottom_y = min(areaA_bottom_right_y_coordinate, areaB_bottom_right_y_coordinate)

    intersection_width = max(intersection_bottom_x - intersection_left_x, 0)
    intersection_height = max(intersection_bottom_y - intersection_left_y, 0)

    intersection_area = intersection_width * intersection_height

    return intersection_area / (areaA + areaB - intersection_area)
    



def nonMaxSuppresion(boxes,threshold):
    newBoxes = sorted(boxes,key = lambda x:x['score'],reverse=True)

    selected = []
    active = [True] * len(boxes)
    num_active = len(active)
    print(active)

    done=False

    for i in range(len(boxes)):
        if active[i]:
            box_a = newBoxes[i]
            selected.append(box_a)

            for j in range(i+1,len(newBoxes)):
                if active[j]:
                    box_b = newBoxes[j]

                    # IOU Implementation
                    iou = calculate_IOU(box_a['bounds'],box_b['bounds'])

                    if iou > threshold:
                        active[j] = False
                        num_active -=1

                        if num_active <=0:
                            done = True
                            break
            if done:
                break
    return selected

                
model = model['model'].float()

convert_tensor = transforms.ToTensor()
image_tensor = convert_tensor(image)
image_tensor = image_tensor.unsqueeze(0)

with torch.no_grad():
    results = model(image_tensor)[0]

# getting the predictions
results = results[0]

filtered_results = []
number_of_columns = results.shape[1]
# print('number_of-columns',number_of_columns)
for i in range(number_of_columns):
    scores = (results[4][i].item())
    scores = "{:.5f}".format(scores)
    if(scores >= '0.25'):
        x1 = results[0][i].item()
        y1 = results[1][i].item()
        w = results[2][i].item()
        h = results[3][i].item()

        bounding_boxes = (x1,y1,w,h)
        result = {
        'classIndex': 'drone',
        'score': scores,
        'bounds': bounding_boxes,
        }
        filtered_results.append(result)
iou_threshold = 0.45
final_boxes = nonMaxSuppresion(filtered_results,iou_threshold)

print('final_boxes',final_boxes)`


Both give me a single bounding box coordinate but the values differ. Can anyone help me where i am going wrong ?

**Comment by goldwater668** [comment]
@eumentis-madhurzanwar 

Have you solved it? I also want to know how this should be done. The U version is a bit too big.

**Comment by glenn-jocher** [comment]
@goldwater668 hello,

Yes, YOLOv8 has some significant size requirements due to the increased complexity and feature sets. If you're dealing with space and computational limitations, you could try a few things:

1. Optimize the Model: PyTorch provides several optimization methods such as quantization and pruning which can help reduce the model size and computational requirements, without significantly affecting the performance.

2. Use a smaller version: If the size of the model is still an issue, you might want to consider using a smaller version of YOLOv8. The smaller versions are designed to provide a good trade-off between speed and precision.

3. Tweak Hyperparameters: Adjusting certain hyperparameters can also help in reducing the model size and improving computational efficiency. You might need to experiment a bit to find a balance.

I hope this helps. Please reply with any further questions you have.

Best Regards,

**Comment by goldwater668** [comment]
@glenn-jocher 

I mean I use torch.load
Load yolov8.pt, and then reason according to your code. The reason why the data is incorrect appears. The code is as follows:
from ultralytics.nn.tasks import attempt_load_one_weight
    from ultralytics.utils import ops
    from ultralytics.data.augment import LetterBox


    def pre_transform(im):
        letterbox = LetterBox([640, 640], auto=True and True, stride=32)
        return [letterbox(image=x) for x in im]
    device = torch.device('cuda')
    model, ckpt = attempt_load_one_weight('best.pt')
    model.float()
    model = model.to(device)
    model.eval()
    img_dir = "/data"
    for idx,img_name in enumerate(os.listdir(img_dir)):
        img_path = os.path.join(img_dir, img_name)
        if idx ==0:
            im_src = cv2.imread(img_path)
            orig_imgs = im_src.copy()
            im0 = [im_src.copy()]
            #TODO:1.preprocess
            im = np.stack(pre_transform(im0))
            im = im[..., ::-1].transpose((0, 3, 1, 2))
            im = np.ascontiguousarray(im)
            im = torch.from_numpy(im)
            
            im = im.to(device)
            im = im.float()
            im /= 255

            #TODO:2.Inference
            preds = model(im)

            #TODO:3.Postprocess
            conf=0.25
            iou=0.7
            agnostic_nms=False
            max_det=300
            classes=None
            names={0: 'hand'}

            preds = ops.non_max_suppression(preds,
                                            conf,
                                            iou,
                                            agnostic=agnostic_nms,
                                            max_det=max_det,
                                            classes=classes,
                                            nc=len(model.names))
                

            results = []
            kpt_shape = [21,3]
            for i, pred in enumerate(preds):
                orig_img = orig_imgs[i]
                pred[:, :4] = scale_boxes(im.shape[2:], pred[:, :4], orig_img.shape).round()
                pred_kpts = pred[:, 6:].view(len(pred), *kpt_shape) if len(pred) else pred[:, 6:]
                pred_kpts = scale_coords(im.shape[2:], pred_kpts, orig_img.shape)
                print(pred[:, :6])
                print(pred_kpts)



The results are as follows：
tensor([[  0.0000, 245.0000,   0.0000, 365.0000,   0.7373,   0.0000]], device='cuda:0')
tensor([[[  0.0000, 322.9018,   0.5410],
         [  0.0000, 302.2499,   0.5500],
         [  0.0000, 283.7432,   0.5425],
         [  0.0000, 267.0714,   0.5012],
         [  0.0000, 251.4065,   0.4650],
         [  0.0000, 286.1008,   0.5002],
         [  0.0000, 304.3473,   0.5182],
         [  0.0000, 312.3517,   0.5305],
         [  0.0000, 310.7260,   0.5229],
         [  0.0000, 299.1289,   0.4809],
         [  0.0000, 317.5443,   0.4847],
         [  0.0000, 321.9820,   0.4926],
         [  0.0000, 318.7391,   0.4888],
         [  0.0000, 314.3396,   0.4835],
         [  0.0000, 330.7378,   0.4840],
         [  0.0000, 334.8665,   0.4964],
         [  0.0000, 332.1172,   0.4955],
         [  0.0000, 330.6639,   0.5091],
         [  0.0000, 342.0481,   0.5118],
         [  0.0000, 348.8803,   0.5219],
         [  0.0000, 351.8106,   0.5258]]], device='cuda:0')


The correct result is as follows：
tensor([[5.7700e+02, 6.2000e+02, 7.6100e+02, 8.6500e+02, 8.4668e-01, 0.0000e+00]], device='cuda:0')
tensor([[[584.0806, 766.5533,   0.9891],
         [609.6811, 723.1566,   0.9928],
         [643.1436, 690.7297,   0.9942],
         [670.2478, 663.8416,   0.9929],
         [679.6243, 636.3875,   0.9885],
         [686.3129, 713.9988,   0.9958],
         [711.7093, 737.7370,   0.9949],
         [692.3127, 741.0548,   0.9954],
         [671.4061, 737.4154,   0.9949],
         [688.1328, 742.5029,   0.9966],
         [703.2917, 760.7209,   0.9963],
         [685.7848, 761.9529,   0.9969],
         [669.9461, 761.1208,   0.9962],
         [682.9196, 773.8772,   0.9965],
         [700.3987, 789.2111,   0.9964],
         [682.3715, 790.8799,   0.9973],
         [663.7191, 789.7189,   0.9970],
         [672.9756, 804.9667,   0.9950],
         [704.2615, 825.8693,   0.9947],
         [725.7499, 836.4265,   0.9946],
         [745.2925, 843.4180,   0.9938]]], device='cuda:0')

**Comment by eumentis-madhurzanwar** [comment]
> @glenn-jocher
> 
> I mean I use torch.load Load yolov8.pt, and then reason according to your code. The reason why the data is incorrect appears. The code is as follows:
> 
> ```
> from ultralytics.nn.tasks import attempt_load_one_weight
> from ultralytics.utils import ops
> from ultralytics.data.augment import LetterBox
> 
> 
>     def pre_transform(im):
>         letterbox = LetterBox([640, 640], auto=True and True, stride=32)
>         return [letterbox(image=x) for x in im]
>     device = torch.device('cuda')
>     model, ckpt = attempt_load_one_weight('best.pt')
>     model.float()
>     model = model.to(device)
>     model.eval()
>     img_dir = "/data"
>     for idx,img_name in enumerate(os.listdir(img_dir)):
>         img_path = os.path.join(img_dir, img_name)
>         if idx ==0:
>             im_src = cv2.imread(img_path)
>             orig_imgs = im_src.copy()
>             im0 = [im_src.copy()]
>             #TODO:1.preprocess
>             im = np.stack(pre_transform(im0))
>             im = im[..., ::-1].transpose((0, 3, 1, 2))
>             im = np.ascontiguousarray(im)
>             im = torch.from_numpy(im)
>             
>             im = im.to(device)
>             im = im.float()
>             im /= 255
> 
>             #TODO:2.Inference
>             preds = model(im)
> 
>             #TODO:3.Postprocess
>             conf=0.25
>             iou=0.7
>             agnostic_nms=False
>             max_det=300
>             classes=None
>             names={0: 'hand'}
> 
>             preds = ops.non_max_suppression(preds,
>                                             conf,
>                                             iou,
>                                             agnostic=agnostic_nms,
>                                             max_det=max_det,
>                                             classes=classes,
>                                             nc=len(model.names))
>                 
> 
>             results = []
>             kpt_shape = [21,3]
>             for i, pred in enumerate(preds):
>                 orig_img = orig_imgs[i]
>                 pred[:, :4] = scale_boxes(im.shape[2:], pred[:, :4], orig_img.shape).round()
>                 pred_kpts = pred[:, 6:].view(len(pred), *kpt_shape) if len(pred) else pred[:, 6:]
>                 pred_kpts = scale_coords(im.shape[2:], pred_kpts, orig_img.shape)
>                 print(pred[:, :6])
>                 print(pred_kpts)
> ```
> 
> ```
> The results are as follows：
> tensor([[  0.0000, 245.0000,   0.0000, 365.0000,   0.7373,   0.0000]], device='cuda:0')
> tensor([[[  0.0000, 322.9018,   0.5410],
>          [  0.0000, 302.2499,   0.5500],
>          [  0.0000, 283.7432,   0.5425],
>          [  0.0000, 267.0714,   0.5012],
>          [  0.0000, 251.4065,   0.4650],
>          [  0.0000, 286.1008,   0.5002],
>          [  0.0000, 304.3473,   0.5182],
>          [  0.0000, 312.3517,   0.5305],
>          [  0.0000, 310.7260,   0.5229],
>          [  0.0000, 299.1289,   0.4809],
>          [  0.0000, 317.5443,   0.4847],
>          [  0.0000, 321.9820,   0.4926],
>          [  0.0000, 318.7391,   0.4888],
>          [  0.0000, 314.3396,   0.4835],
>          [  0.0000, 330.7378,   0.4840],
>          [  0.0000, 334.8665,   0.4964],
>          [  0.0000, 332.1172,   0.4955],
>          [  0.0000, 330.6639,   0.5091],
>          [  0.0000, 342.0481,   0.5118],
>          [  0.0000, 348.8803,   0.5219],
>          [  0.0000, 351.8106,   0.5258]]], device='cuda:0')
> 
> 
> The correct result is as follows：
> tensor([[5.7700e+02, 6.2000e+02, 7.6100e+02, 8.6500e+02, 8.4668e-01, 0.0000e+00]], device='cuda:0')
> tensor([[[584.0806, 766.5533,   0.9891],
>          [609.6811, 723.1566,   0.9928],
>          [643.1436, 690.7297,   0.9942],
>          [670.2478, 663.8416,   0.9929],
>          [679.6243, 636.3875,   0.9885],
>          [686.3129, 713.9988,   0.9958],
>          [711.7093, 737.7370,   0.9949],
>          [692.3127, 741.0548,   0.9954],
>          [671.4061, 737.4154,   0.9949],
>          [688.1328, 742.5029,   0.9966],
>          [703.2917, 760.7209,   0.9963],
>          [685.7848, 761.9529,   0.9969],
>          [669.9461, 761.1208,   0.9962],
>          [682.9196, 773.8772,   0.9965],
>          [700.3987, 789.2111,   0.9964],
>          [682.3715, 790.8799,   0.9973],
>          [663.7191, 789.7189,   0.9970],
>          [672.9756, 804.9667,   0.9950],
>          [704.2615, 825.8693,   0.9947],
>          [725.7499, 836.4265,   0.9946],
>          [745.2925, 843.4180,   0.9938]]], device='cuda:0')
> ```

    image = cv2.imread(image_path)

    # converting the image to RGB format. Opencv reads image in BGR format, so we need to convert
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Resize the image to match the input shape
    image = cv2.resize(image, (640,640)) 

    # defining tensor
    convert_tensor = transforms.ToTensor()

    # converting image to tensor
    image_tensor = convert_tensor(image)

    # adding dimension - [B,C,W,H]
    image_tensor = image_tensor.unsqueeze(0)

    # converting tensor to float ( Float32 )
    image_tensor = image_tensor.float()
    
    with torch.no_grad():
      results = model(image_tensor)[0]


These are the steps I followed and I'm getting the correct answer.

**Comment by eumentis-madhurzanwar** [comment]
@goldwater668 Hi,
Try removing the step were you divide the image data by 255. Adding that step in my code is also giving me unexpected results. I do not know the reason though. Maybe @glenn-jocher could help us understand more.

**Comment by eumentis-madhurzanwar** [comment]
> > @glenn-jocher
> > I mean I use torch.load Load yolov8.pt, and then reason according to your code. The reason why the data is incorrect appears. The code is as follows:
> > ```
> > from ultralytics.nn.tasks import attempt_load_one_weight
> > from ultralytics.utils import ops
> > from ultralytics.data.augment import LetterBox
> > 
> > 
> >     def pre_transform(im):
> >         letterbox = LetterBox([640, 640], auto=True and True, stride=32)
> >         return [letterbox(image=x) for x in im]
> >     device = torch.device('cuda')
> >     model, ckpt = attempt_load_one_weight('best.pt')
> >     model.float()
> >     model = model.to(device)
> >     model.eval()
> >     img_dir = "/data"
> >     for idx,img_name in enumerate(os.listdir(img_dir)):
> >         img_path = os.path.join(img_dir, img_name)
> >         if idx ==0:
> >             im_src = cv2.imread(img_path)
> >             orig_imgs = im_src.copy()
> >             im0 = [im_src.copy()]
> >             #TODO:1.preprocess
> >             im = np.stack(pre_transform(im0))
> >             im = im[..., ::-1].transpose((0, 3, 1, 2))
> >             im = np.ascontiguousarray(im)
> >             im = torch.from_numpy(im)
> >             
> >             im = im.to(device)
> >             im = im.float()
> >             im /= 255
> > 
> >             #TODO:2.Inference
> >             preds = model(im)
> > 
> >             #TODO:3.Postprocess
> >             conf=0.25
> >             iou=0.7
> >             agnostic_nms=False
> >             max_det=300
> >             classes=None
> >             names={0: 'hand'}
> > 
> >             preds = ops.non_max_suppression(preds,
> >                                             conf,
> >                                             iou,
> >                                             agnostic=agnostic_nms,
> >                                             max_det=max_det,
> >                                             classes=classes,
> >                                             nc=len(model.names))
> >                 
> > 
> >             results = []
> >             kpt_shape = [21,3]
> >             for i, pred in enumerate(preds):
> >                 orig_img = orig_imgs[i]
> >                 pred[:, :4] = scale_boxes(im.shape[2:], pred[:, :4], orig_img.shape).round()
> >                 pred_kpts = pred[:, 6:].view(len(pred), *kpt_shape) if len(pred) else pred[:, 6:]
> >                 pred_kpts = scale_coords(im.shape[2:], pred_kpts, orig_img.shape)
> >                 print(pred[:, :6])
> >                 print(pred_kpts)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > The results are as follows：
> > tensor([[  0.0000, 245.0000,   0.0000, 365.0000,   0.7373,   0.0000]], device='cuda:0')
> > tensor([[[  0.0000, 322.9018,   0.5410],
> >          [  0.0000, 302.2499,   0.5500],
> >          [  0.0000, 283.7432,   0.5425],
> >          [  0.0000, 267.0714,   0.5012],
> >          [  0.0000, 251.4065,   0.4650],
> >          [  0.0000, 286.1008,   0.5002],
> >          [  0.0000, 304.3473,   0.5182],
> >          [  0.0000, 312.3517,   0.5305],
> >          [  0.0000, 310.7260,   0.5229],
> >          [  0.0000, 299.1289,   0.4809],
> >          [  0.0000, 317.5443,   0.4847],
> >          [  0.0000, 321.9820,   0.4926],
> >          [  0.0000, 318.7391,   0.4888],
> >          [  0.0000, 314.3396,   0.4835],
> >          [  0.0000, 330.7378,   0.4840],
> >          [  0.0000, 334.8665,   0.4964],
> >          [  0.0000, 332.1172,   0.4955],
> >          [  0.0000, 330.6639,   0.5091],
> >          [  0.0000, 342.0481,   0.5118],
> >          [  0.0000, 348.8803,   0.5219],
> >          [  0.0000, 351.8106,   0.5258]]], device='cuda:0')
> > 
> > 
> > The correct result is as follows：
> > tensor([[5.7700e+02, 6.2000e+02, 7.6100e+02, 8.6500e+02, 8.4668e-01, 0.0000e+00]], device='cuda:0')
> > tensor([[[584.0806, 766.5533,   0.9891],
> >          [609.6811, 723.1566,   0.9928],
> >          [643.1436, 690.7297,   0.9942],
> >          [670.2478, 663.8416,   0.9929],
> >          [679.6243, 636.3875,   0.9885],
> >          [686.3129, 713.9988,   0.9958],
> >          [711.7093, 737.7370,   0.9949],
> >          [692.3127, 741.0548,   0.9954],
> >          [671.4061, 737.4154,   0.9949],
> >          [688.1328, 742.5029,   0.9966],
> >          [703.2917, 760.7209,   0.9963],
> >          [685.7848, 761.9529,   0.9969],
> >          [669.9461, 761.1208,   0.9962],
> >          [682.9196, 773.8772,   0.9965],
> >          [700.3987, 789.2111,   0.9964],
> >          [682.3715, 790.8799,   0.9973],
> >          [663.7191, 789.7189,   0.9970],
> >          [672.9756, 804.9667,   0.9950],
> >          [704.2615, 825.8693,   0.9947],
> >          [725.7499, 836.4265,   0.9946],
> >          [745.2925, 843.4180,   0.9938]]], device='cuda:0')
> > ```
> 
> ```
> image = cv2.imread(image_path)
> 
> # converting the image to RGB format. Opencv reads image in BGR format, so we need to convert
> image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
> 
> # Resize the image to match the input shape
> image = cv2.resize(image, (640,640)) 
> 
> # defining tensor
> convert_tensor = transforms.ToTensor()
> 
> # converting image to tensor
> image_tensor = convert_tensor(image)
> 
> # adding dimension - [B,C,W,H]
> image_tensor = image_tensor.unsqueeze(0)
> 
> # converting tensor to float ( Float32 )
> image_tensor = image_tensor.float()
> 
> with torch.no_grad():
>   results = model(image_tensor)[0]
> ```
> 
> These are the steps I followed and I'm getting the correct answer.

You are also doing the same steps. Maybe @glenn-jocher can help as to why you are getting a different answer than expected

**Comment by goldwater668** [comment]
@eumentis-madhurzanwar
The data problem is solved, thank you for your timely answer.

**Comment by eumentis-madhurzanwar** [comment]
> @eumentis-madhurzanwar The data problem is solved, thank you for your timely answer.

May I know what did you do to solve it ?

**Comment by glenn-jocher** [comment]
@eumentis-madhurzanwar i'm glad to hear that your issue has been resolved! In order to help others who may encounter a similar issue, would you mind sharing which changes or steps you took to solve this problem?

**Comment by mehdiimsv** [comment]
@goldwater668 Hi! May I know what did you do to solve it? I faced the same problem
@glenn-jocher Can you help me with this issue?

**Comment by advaitp** [comment]
@eumentis-madhurzanwar @glenn-jocher can you help I am also facing the same issue, how did you solve it ?

**Comment by glenn-jocher** [comment]
Hi there! 😊 It sounds like you're encountering a similar issue with YOLOv8 model loading and inference. The solution that worked for @advaitp involved ensuring the image preprocessing steps matched exactly what the model expects. This includes converting images to RGB, resizing to the model's input size, converting to a tensor, and normalizing the pixel values.

Here's a quick recap of the steps:

```python
import cv2
import torch
from torchvision import transforms

# Load your image
image_path = 'path/to/your/image.jpg'
image = cv2.imread(image_path)

# Convert BGR to RGB
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Resize the image
image = cv2.resize(image, (640, 640))

# Convert to tensor
image_tensor = transforms.ToTensor()(image)

# Add batch dimension and convert to float
image_tensor = image_tensor.unsqueeze(0).float()

# Load your model (make sure it's in eval mode)
model = torch.load('path/to/your/model.pt')
model.eval()

# Perform inference
with torch.no_grad():
    preds = model(image_tensor)
```

Make sure your model is loaded correctly and in evaluation mode with `.eval()`. If you've followed these steps and are still facing issues, could you provide more details about the error or unexpected results you're getting? This will help us pinpoint the solution more effectively.

**Comment by AminBT-ADI** [comment]
Hello, I loaded the model as @glenn-jocher stated but the detection head appears to be different than the trained model. More specifically, loading it from pytorch yields this detection head:

      (cv4): ModuleList(
        (0): Sequential(
          (0): Conv(
            (conv): Conv2d(64, 51, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(51, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (1): Conv(
            (conv): Conv2d(51, 51, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(51, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (2): Conv2d(51, 51, kernel_size=(1, 1), stride=(1, 1))
        )
        (1): Sequential(
          (0): Conv(
            (conv): Conv2d(128, 51, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(51, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (1): Conv(
            (conv): Conv2d(51, 51, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(51, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (2): Conv2d(51, 51, kernel_size=(1, 1), stride=(1, 1))
        )
        (2): Sequential(
          (0): Conv(
            (conv): Conv2d(256, 51, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(51, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (1): Conv(
            (conv): Conv2d(51, 51, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (bn): BatchNorm2d(51, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
            (act): SiLU(inplace=True)
          )
          (2): Conv2d(51, 51, kernel_size=(1, 1), stride=(1, 1))
        )
      )
    )
  )
)

while loading it using the ultralytics.YOLO model yields this:

        (cv4): ModuleList(
          (0): Sequential(
            (0): Conv(
              (conv): Conv2d(64, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (2): Conv2d(16, 9, kernel_size=(1, 1), stride=(1, 1))
          )
          (1): Sequential(
            (0): Conv(
              (conv): Conv2d(128, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (2): Conv2d(16, 9, kernel_size=(1, 1), stride=(1, 1))
          )
          (2): Sequential(
            (0): Conv(
              (conv): Conv2d(256, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (1): Conv(
              (conv): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
              (act): SiLU(inplace=True)
            )
            (2): Conv2d(16, 9, kernel_size=(1, 1), stride=(1, 1))
          )
        )
      )
    )
  )
)

Is there a way to make the detection heads match?

**Comment by Vijayhegde11** [comment]
Hi @glenn-jocher, I'm trying to implement the above code given by you. But getting the below error


  File "/home/vijay/Object_detection/obj_detect.py", line 98, in main
    detector = YOLOv8PyTorch(model_path)
  File "/home/vijay/Object_detection/obj_detect.py", line 44, in __init__
    self.model = torch.load(model_path, map_location="cpu") 
  File "/home/vijay/.local/lib/python3.10/site-packages/torch/serialization.py", line 1025, in load
    return _load(opened_zipfile,
  File "/home/vijay/.local/lib/python3.10/site-packages/torch/serialization.py", line 1446, in _load
    result = unpickler.load()
  File "/home/vijay/.local/lib/python3.10/site-packages/torch/serialization.py", line 1439, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'ultralytics'

**Comment by glenn-jocher** [comment]
Hi @Vijayhegde11,

The error you're encountering suggests that the 'ultralytics' module is not installed or not found in your environment. Please ensure you have the latest version of the Ultralytics package installed using `pip install ultralytics`. If the issue persists, try running your script in a clean virtual environment.

**Comment by Vikramank** [comment]
Hi folks, 
While this approach works well for Image Classification, how about Object detection? The model returns raw outputs. Any suggestions to use Torch only?

**Comment by glenn-jocher** [comment]
For object detection with Torch-only inference using Ultralytics YOLO models, you can load the model with `torch.load()` and manually handle preprocessing/postprocessing. The raw outputs require decoding (xywh format) and NMS. We recommend using `ops.non_max_suppression` from our utils for postprocessing, which handles these steps automatically. For implementation details, see the [Ultralytics documentation on model inference](https://docs.ultralytics.com/modes/predict/).

**Comment by Vikramank** [comment]
hi @glenn-jocher ,
Thanks for the info!

**Comment by glenn-jocher** [comment]
Hi there! 👋 It looks like you're encountering a `ModuleNotFoundError` because the `ultralytics` package isn't installed in your environment. To resolve this, simply run:

```bash
pip install ultralytics
```

This will install the required dependencies. For more details, see our [Installation Guide](https://docs.ultralytics.com/quickstart/#install-ultralytics). Let us know if you need further assistance! 😊
