### ISSUE TITLE
Question about annotation format for classification

### ISSUE THREAD

**Issue by Aoobi** [ultralytics/ultralytics#605]
Hello, 

I have a quick question: 
What is the format (or folder structure) for annotations for classification training?
Do i just put images of each class in separate folders? 

I searched but couldn't find the answer. 

Thank you!

**Comment by knoppmyth** [comment]
Each class goes into a separate folder.

**Comment by pderrenger** [comment]
@knoppmyth yes, for classification training, each class should be placed in its own separate folder. The folder structure should be organized such that each class has its own folder containing the images relevant to that class. If you have any other questions about YOLOv8 or any other models, feel free to ask! 😊
