### ISSUE TITLE
Modifications to head.py

### ISSUE THREAD

**Issue by FabioskySG** [ultralytics/ultralytics#6054]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I am trying to modify YOLOv8's head to perform 3D Object Detection. My first step is to modify head.py file, and I accomplish to modify the Detect forward method (I can see changes, i.e. prints) but when I try to modify the __init__ method, I have found that changes don´t have any effect. For example, if I make a print statement in the __init__, nothing happens.

I understand that this may happen because of inheritances accross the different parts of a model. However, I have tried to follow the inheritance tree and I did not find where the head.Detect class is instantiated. 

So, my question is, how can I modify the __init__ so that my changes make effect? 

I hope everything is clear enough, if not, let me know. Thanks in advance!

Greetings,

Fabio

**Comment by FabioskySG** [comment]
Hi @glenn-jocher ,

Thank you so much for your quick response. In the end, it was all a concept failure (as it usually is, I guess). I was trying to load a pretrained model from yolov8n.pt, so the changes in `__init__` had no effect, what caused my `Detect` class to perform as it was expected from the pretraining. 

Finally, I came up with the fact that I can actually do the following: 

`model = YOLO('yolov8n.yaml').load('yolov8n.pt')`

So that the pretrained model is built onto the .yaml, which effectively introduces the changes to the `__init__` methods. 

Now I think that my YOLOv8 head is finally built for a 3D object detection task since the tensor dimensions match. However, I cannot test it yet since I need to do the next step: training. I am sure that I will contact you again since your answer was so fast and helpful. Thanks again!

Greetings,

Fabio

**Comment by glenn-jocher** [comment]
@FabioskySG hello Fabio,

It's wonderful to hear back from you, and I'm glad you've made progress with your YOLOv8 customizations for 3D object detection!

You've done an excellent job troubleshooting the issue and arriving at a solution—understanding the intricacies of a pretrained model's loading behavior is crucial when making architectural changes.

By rebuilding the model using the modified YAML configuration file and then loading the weights, you've taken the right approach to integrate your customizations while leveraging pretrained weights. It seems you've found an efficient way to ensure your `__init__` modifications are included in the model's architecture.

As you move forward with training your newly configured model, your observation on the tensor dimensions seems promising. Training will be the ultimate test of your modifications and should help you fine-tune your approach.

We're here if you have any questions or hit any roadblocks during training or further development of your project. Thank you for your kind words, and please don't hesitate to reach out again.

Good luck with your 3D object detection task using YOLOv8, and we look forward to hearing about your successes!

Best regards,

**Comment by syedaraheen** [comment]
@FabioskySG Greetings, I wanted to ask what steps I need to take to make my YOLO head 3D what parameters I need to change and further how to efficiently test it. can you provide me a proper guideline. Your help would be appreciated.
Regards.
