### ISSUE TITLE
Train and val folder missing stuff

### ISSUE THREAD

**Issue by CastingSpell** [ultralytics/ultralytics#606]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

It's been happening from the last week, train and validation works like normal, no errors, no warnings, nothing. But when the the codes end its execution, nothing comes in the results folder. No graphics, confusion matrix, train or val batches... Only the things you see on the screenshot below.
![image](https://user-images.githubusercontent.com/32511790/214325863-bb24b895-609a-4092-8a7d-10f1d81b5a2a.png)

The output when the training ends its the following:
```
Stopping training early as no improvement observed in last 50 epochs. Best results observed at epoch 223, best model saved as best.pt.
To update EarlyStopping(patience=50) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

273 epochs completed in 2.985 hours.
Optimizer stripped from runs/detect/train/weights/last.pt, 22.6MB
Optimizer stripped from runs/detect/train/weights/best.pt, 22.6MB

Validating runs/detect/train/weights/best.pt...
```

Followed by the metrics chart.

Any help is appreciated, thanks before hand,.

### Environment

Ultralytics YOLOv8.0.18 🚀 Python-3.8.10 torch-1.13.1+cu116 CUDA:0 (Tesla T4, 15110MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 23.9/78.2 GB disk)
Google Colab

### Minimal Reproducible Example

```
from ultralytics import YOLO
model = YOLO("./models/yolov8s.pt") 
results = model.train(data="./data.yaml", epochs=300, batch=4, imgsz=1280)
model.val()
```

### Additional
Might it have something to do with early stopping?

**Comment by CastingSpell** [comment]
Works as expected when running from scripts using `!yolo task=detect [...]`

**Comment by pderrenger** [comment]
@theotherp hey there! It looks like you're encountering an issue with your training and validation process in YOLOv8. I'd be happy to help you out with this.

From the information you've provided, it seems that the training and validation process completes without any errors or warnings, but the results folder ends up empty, without the expected graphics, confusion matrix, or train and val batches.

One thing to consider is that when running the training and validation directly from a script using `!yolo task=detect [...]` it works as expected. This suggests that the issue might be related to the way you're calling the training and validation in your example code.

Regarding the early stopping, it's unlikely to be the cause of the issue as it's a mechanism to stop the training process early based on certain conditions, but it shouldn't affect the generation of the results in the output folder.

To troubleshoot this further, I'd recommend checking the paths and configurations in your example code, ensuring that the necessary paths for saving the results are correctly specified. Additionally, you might want to check the write permissions for the output folder to ensure that the files can be successfully written there.

If you can provide any additional details or a more complete example of your code, that would be very helpful in diagnosing the issue. Feel free to provide more information, and we'll work together to get this sorted out! 😊

**Comment by glenn-jocher** [comment]
Hello @pderrenger! I'm sorry to hear you're experiencing issues with the output in the results folder. It's great that you've checked for errors and warnings and found none; this helps narrow down the potential causes.

If the results are generated as expected when running from scripts using `!yolo task=detect [...]`, but not when using the Python environment, it might be an issue with the environment setup or a discrepancy in the way the results are being saved or accessed.

Please ensure that the paths to the results directory are correctly specified in your Python environment and that the directory has the necessary write permissions. Also, verify that the results are not being saved in a different directory than expected.

Early stopping is designed to halt training when no improvement is observed, but it should not affect the saving of results. The fact that you're seeing the metrics chart suggests that some outputs are being generated, so it's worth double-checking the output paths.

If the issue persists, please provide more details or the complete code snippet, and we'll continue to troubleshoot this together. Thanks for your patience! 😊
