### ISSUE TITLE
About Training Parameters——pretrained

### ISSUE THREAD

**Issue by LazyShark2001** [ultralytics/ultralytics#6060]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I have two questions to seek answers from you.

1.In your official training example document, three methods were used to create the model:
`
model = YOLO('yolov8n.yaml')  # build a new model from YAML

model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)

model = YOLO('yolov8n.yaml').load('yolov8n.pt')  # build from YAML and transfer weights
`These three methods correspond to creating a new model, continuing to train existing models, creating a new model, and loading weights.

Do you only need to choose one of the creation methods according to your needs in actual use？

2.What is the difference between setting the value of pretraine'd to True, False, or the weight file path? If a weight file is ledoaded when creating the model, is the setting of this parameter still meaningful?

Looking forward to your reply and wishing you success in your work.

**Comment by glenn-jocher** [comment]
@LazyShark2001 hello,

Thank you for reaching out and for your interest in the YOLOv8 model. I'm glad to help clarify your queries.

1. The three methods indeed provide different functionalities. 

   - `model = YOLO('yolov8n.yaml')`: This operation builds an entirely new model based on the configuration specified in the 'yolov8n.yaml' file. This is suitable when you want to start training a model from scratch.

   - `model = YOLO('yolov8n.pt')`: Here, a pre-trained model('yolov8n.pt') is loaded which is recommended when you want to leverage pre-existing learning and reduce training time.

   - `model = YOLO('yolov8n.yaml').load('yolov8n.pt')`: In this case, a new model is built as per the configuration and then the weights from an existing model ('yolov8n.pt') are loaded. This is helpful when you want to start with a particular configuration but do not want to start the learning from the beginning.

As per your requirement, you can choose the appropriate creation method.

2. The `pretrained` parameter determines whether to load the backbone network's pre-trained weights or not. 

   - If `pretrained` is set to `True`, the model loads the pre-trained weights which can accelerate the training process.
   
   - If `pretrained` is set to `False`, the model will not load any pre-trained weights and it essentially means that you are training the model from scratch.

The path to the weight file is useful when you have specific weights that you want to load up to your model. Therefore, even though you have loaded weights when creating the model, you can still use `pretrained` to determine whether to use the backbone network's pre-trained weights or not.

I hope this answers your questions. Your success with YOLOv8 is a testament to the hard work of our entire team and the broader YOLO community. Best of luck with your work!

**Comment by LazyShark2001** [comment]
Thank you for your answer. I already know what to do.

Thank you again for your answer.

**Comment by LazyShark2001** [comment]
> 你好
> 
> 感谢您的联系和对 YOLOv8 模型的关注。我很高兴能帮助澄清您的疑问。
> 
> 1. 这三种方法确实提供了不同的功能。
>    
>    * `model = YOLO('yolov8n.yaml')`：此操作基于“yolov8n.yaml”文件中指定的配置构建一个全新的模型。当您想从头开始训练模型时，这很合适。
>    * `model = YOLO('yolov8n.pt')`：这里加载了一个预训练模型（'yolov8n.pt'），当您想利用预先存在的学习并减少训练时间时，建议使用该模型。
>    * `model = YOLO('yolov8n.yaml').load('yolov8n.pt')`：在这种情况下，根据配置构建一个新模型，然后加载现有模型 （'yolov8n.pt'） 的权重。当您想从特定配置开始，但又不想从头开始学习时，这很有帮助。
> 
> 根据您的要求，您可以选择合适的创建方法。
> 
> 2. 该参数决定是否加载骨干网络的预训练权重。`pretrained`
>    
>    * 如果设置为 ，则模型将加载预训练权重，从而加快训练过程。`pretrained``True`
>    * 如果设置为 ，则模型不会加载任何预先训练的权重，这实质上意味着您正在从头开始训练模型。`pretrained``False`
> 
> 当您有要加载到模型的特定权重时，权重文件的路径非常有用。因此，即使您在创建模型时加载了权重，您仍然可以用来确定是否使用骨干网络的预训练权重。`pretrained`
> 
> 我希望这能回答你的问题。您在 YOLOv8 上的成功证明了我们整个团队和更广泛的 YOLO 社区的辛勤工作。祝你工作顺利！

Thank you for your answer. I already know what to do

Thank you again for your answer

**Comment by LazyShark2001** [comment]
> @LazyShark2001 hello,
> 
> Thank you for reaching out and for your interest in the YOLOv8 model. I'm glad to help clarify your queries.
> 
> 1. The three methods indeed provide different functionalities.
>    
>    * `model = YOLO('yolov8n.yaml')`: This operation builds an entirely new model based on the configuration specified in the 'yolov8n.yaml' file. This is suitable when you want to start training a model from scratch.
>    * `model = YOLO('yolov8n.pt')`: Here, a pre-trained model('yolov8n.pt') is loaded which is recommended when you want to leverage pre-existing learning and reduce training time.
>    * `model = YOLO('yolov8n.yaml').load('yolov8n.pt')`: In this case, a new model is built as per the configuration and then the weights from an existing model ('yolov8n.pt') are loaded. This is helpful when you want to start with a particular configuration but do not want to start the learning from the beginning.
> 
> As per your requirement, you can choose the appropriate creation method.
> 
> 2. The  parameter determines whether to load the backbone network's pre-trained weights or not.`pretrained`
>    
>    * If  is set to , the model loads the pre-trained weights which can accelerate the training process.`pretrained``True`
>    * If  is set to , the model will not load any pre-trained weights and it essentially means that you are training the model from scratch.`pretrained``False`
> 
> The path to the weight file is useful when you have specific weights that you want to load up to your model. Therefore, even though you have loaded weights when creating the model, you can still use to determine whether to use the backbone network's pre-trained weights or not.`pretrained`
> 
> I hope this answers your questions. Your success with YOLOv8 is a testament to the hard work of our entire team and the broader YOLO community. Best of luck with your work!

Thank you for your answer. I already know what to do.

Thank you again for your answer.

**Comment by glenn-jocher** [comment]
You're welcome @LazyShark2001! I'm glad to hear that you found the information helpful. Don't hesitate to reach out if you have any more questions. Best of luck with your work on YOLOv8!

**Comment by liuqinglong110** [comment]
> @LazyShark2001 hello,
> 
> Thank you for reaching out and for your interest in the YOLOv8 model. I'm glad to help clarify your queries.
> 
> 1. The three methods indeed provide different functionalities.
>    
>    * `model = YOLO('yolov8n.yaml')`: This operation builds an entirely new model based on the configuration specified in the 'yolov8n.yaml' file. This is suitable when you want to start training a model from scratch.
>    * `model = YOLO('yolov8n.pt')`: Here, a pre-trained model('yolov8n.pt') is loaded which is recommended when you want to leverage pre-existing learning and reduce training time.
>    * `model = YOLO('yolov8n.yaml').load('yolov8n.pt')`: In this case, a new model is built as per the configuration and then the weights from an existing model ('yolov8n.pt') are loaded. This is helpful when you want to start with a particular configuration but do not want to start the learning from the beginning.
> 
> As per your requirement, you can choose the appropriate creation method.
> 
> 2. The `pretrained` parameter determines whether to load the backbone network's pre-trained weights or not.
>    
>    * If `pretrained` is set to `True`, the model loads the pre-trained weights which can accelerate the training process.
>    * If `pretrained` is set to `False`, the model will not load any pre-trained weights and it essentially means that you are training the model from scratch.
> 
> The path to the weight file is useful when you have specific weights that you want to load up to your model. Therefore, even though you have loaded weights when creating the model, you can still use `pretrained` to determine whether to use the backbone network's pre-trained weights or not.
> 
> I hope this answers your questions. Your success with YOLOv8 is a testament to the hard work of our entire team and the broader YOLO community. Best of luck with your work!
----------------------------------------------------------------------------------------------------------------------------------------
Thank you very much for your answers to related questions. But I still have some doubts that I want to confirm with you.
In particular, I am not using YOLOv8 through CLI commands. I am using YOLOv8 code directly.
Each training parameter is implemented by modifying the content in ultralytics/cfg/default.yaml.
Therefore, I carefully read the comments behind each parameter in default.yaml.
I checked other people's issues and found that very few people use default.yaml directly. This may be because
I need to modify the network structure and have other modifications to the code.

I am a little confused about the use of model and pretrained in default.yaml. Here are the issues I'm having:
First, I modified the network structure. The new network structure is represented by yolov8-seg-Lawn.yaml.
I built the Basic_Dataset data set from a large number of pictures downloaded from the Internet. Using this data set,
I trained a new network structure from scratch with yolov8-seg-Lawn.yaml, and got ./runs/segment/train/weights/best.pt.
The specific configuration parameters are shown in the figure below:
![1702901764739_FBD9EBB7-44D9-41dd-AFB5-EA918007623F](https://github.com/ultralytics/ultralytics/assets/23652342/5b443e09-7391-4184-ac3e-d5539055fcf6)

Then, I used ./runs/segment/train/weights/best.pt to fine-tune on the new Fine_Tuning dataset.
So, I modified the model and pretrained in default.yaml. That is, change the model to ./runs/segment/train/weights/best.pt
And changed pretrained to true. At this time, I started training again, and then I really started to fine-tune best.pt. The specific parameter configuration is shown in the figure below:
![1702901825850_4AE64AD4-51D8-4457-A623-1F29A2192B51](https://github.com/ultralytics/ultralytics/assets/23652342/d7c454c1-efc6-4c5b-88ad-6ca0cc044c97)
I don't know if my understanding is correct.

**Comment by LazyShark2001** [comment]
@liuqinglong110 hello,

There is nothing wrong with your understanding.

Your operation is to pre-train the model on the Basic_Dataset data set, and then put the trained model and weights into the Fine_Tuning data set for fine-tuning.

`model: best.pt` This means that you create a network with the same structure and weights as best.pt

**Comment by glenn-jocher** [comment]
@LazyShark2001 hello,

Your understanding is correct. By setting `model` to `./runs/segment/train/weights/best.pt`, you are indeed using the weights from your initial training on the Basic_Dataset for further fine-tuning on the Fine_Tuning dataset. The `pretrained: true` setting is appropriate for this scenario, as it indicates that you are starting with a model that has already been trained. Keep up the good work!
