### ISSUE TITLE
Training Issues

### ISSUE THREAD

**Issue by PericoSpart** [ultralytics/ultralytics#6071]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

![Immagine](https://github.com/ultralytics/ultralytics/assets/149265400/cd71925c-ce50-4f59-bd72-683f7b213753)

### Environment

OS                  Windows-10-10.0.19044-SP0
Environment         Windows
Python              3.11.0
Install             pip
RAM                 15.91 GB
CPU                 AMD Ryzen 5 5600X 6-Core Processor
CUDA                None

matplotlib           3.8.0>=3.3.0
numpy                1.26.1>=1.22.2
opencv-python        4.8.1.78>=4.6.0
pillow               10.1.0>=7.1.2
pyyaml               6.0.1>=5.3.1
requests             2.31.0>=2.23.0
scipy                1.11.3>=1.4.1
torch                2.1.0>=1.8.0
torchvision          0.16.0>=0.9.0
tqdm                 4.66.1>=4.64.0
pandas               2.1.2>=1.1.4
seaborn              0.13.0>=0.11.0
psutil               5.9.6
py-cpuinfo           9.0.0
thop                 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

yolo train data=data.yaml model=yolov8n.pt epochs=25

### Additional

While training, It shows me 0G on GPU_mem even though I should've had 14G or less.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@PericoSpart you're training on CPU, hence 0G of GPU memory used.

**Comment by PericoSpart** [comment]
@glenn-jocher then how do I train on GPU?

**Comment by glenn-jocher** [comment]
@PericoSpart great question! By default, Ultralytics YOLOv8 will automatically train on the GPU if one is available. However, it seems in your case no CUDA-compatible GPU is found, hence the training shifts to the CPU.

Ensure that you have a CUDA-compatible GPU installed and the necessary drivers, as well as CUDA, are correctly set up. The GPU should be correctly connected and recognized by your system. You can validate this by running the `nvidia-smi` command in your terminal, which should display information about your GPU.

If your setup is correct and the GPU is still not recognized by YOLOv8, check that PyTorch can see your GPU (it's the library YOLOv8 utilizes for GPU acceleration). In your Python environment, execute: `import torch; print(torch.cuda.is_available())`. If it returns True, then PyTorch can access your GPU. If it returns False, it means PyTorch can't access your GPU, and you should look at your installation and setup of CUDA and PyTorch.

**Comment by PericoSpart** [comment]
I got a new error, I will make a new issue.

**Comment by glenn-jocher** [comment]
@PericoSpart, thank you for keeping the issues separate. That approach greatly helps manage the different problems and their corresponding solutions. Please don't forget to provide as much detail as possible in your new issue, including the error message, the context in which it occurs, and the steps to reproduce it. This will enable us and the YOLOv8 community to help you more effectively. We look forward to addressing your new issue soon.
