### ISSUE TITLE
Can you please confirme the `(bs, channel, height, width)` order?

### ISSUE THREAD

**Issue by hdnh2006** [ultralytics/ultralytics#6083]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello Ultralytics team!

I have a question regarding the documentation, in all modes, the parameter `imgsz` is described as follows: "image size as scalar or (h, w) list, i.e. (640, 480)":
https://github.com/ultralytics/ultralytics/blob/main/docs/modes/export.md#arguments

So I don't know if this is a mistake in (h,w) or in (640,480). Because for rectangular images, width is usually greater than height, so I think it should be (480, 640). 

My question is, if I want to export my model to inference on rectangular images with width=640 and height=480, how it should be set this parameter?

Thanks

**Comment by glenn-jocher** [comment]
@hdnh2006 dear user,

Thank you for your inquiry. 

The `imgsz` argument denotes the image size and you're correct to notice it's stated as a (height, width) configuration. In the Ultralytics YOLOv8 implementation, the height comes before the width when specifying the image size, in line with the convention used in the PyTorch community.

So, when you want to export your model to perform inference on rectangular images with width=640 and height=480, you should set the `imgsz` parameter as (480, 640).

The `(bs, channel, height, width)` you referenced initially is the standard tensor dimension order for images in PyTorch, with `bs` signifying the batch size. This is consistent with the `(height, width)` structure used in the `imgsz` parameter.

I hope this clears your doubt. If you have more questions, feel free to ask.

Best regards,
Glenn Jocher
