### ISSUE TITLE
Can you confirm the order of width and height?

### ISSUE THREAD

**Issue by hdnh2006** [ultralytics/ultralytics#6084]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello Ultralytics team!

I have a question regarding the documentation, in all modes, the parameter `imgsz` is described as follows: "image size as scalar or (h, w) list, i.e. (640, 480)":
https://github.com/ultralytics/ultralytics/blob/main/docs/modes/export.md#arguments

So I don't know if this is a mistake in (h,w) or in (640,480). Because for rectangular images, width is usually greater than height, so I think it should be (480, 640). 

My question is, if I want to export my model to inference on rectangular images with width=640 and height=480, how it should be set this parameter?

Thanks

**Comment by glenn-jocher** [comment]
@hdnh2006 hello,

Thank you for pointing out your query. The `imgsz` parameter does indeed take the image size as a scalar or as a tuple in the form of (height, width). So you're correct that for a rectangular image with a width of 640 and a height of 480, you would set this parameter as (480, 640).

I realize this might go against the traditional (width, height) format, but this (height, width) convention aligns with the shape representation used in many computer vision libraries, including OpenCV and NumPy.

I hope this clears your doubts. If you have further questions, feel free to ask!

Best Regards,
Glenn Jocher YOLOv8 maintainer at Ultralytics

**Comment by hdnh2006** [comment]
Ok, got it!

I highly recommend to change the documentation. All modes are having the same issue:
https://github.com/ultralytics/ultralytics/blob/main/docs/modes/export.md#arguments
https://github.com/ultralytics/ultralytics/blob/main/docs/modes/predict.md#arguments

**Comment by glenn-jocher** [comment]
@hdnh2006 thank you for your recommendation. We value consistent and clear documentation, and I appreciate your vigilance in ensuring that our documentation meets those standards. We'll take your feedback into account and review the relevant sections of the documentation to ensure the parameter description is accurate and clear for all users. Your attention to detail is beneficial to the whole community, and such contributions help us maintain the quality and usability of our products.

If there are any other aspects of our documentation or software that you believe could be improved, or if you need further assistance, please don't hesitate to let us know.

Thank you once again for bringing this to our attention.

Warm
