### ISSUE TITLE
YoloV8 Tracking Example works on M1 Mac, but not on hosted hardware like AWS EC2 instance or Colab Notebook

### ISSUE THREAD

**Issue by NickLojewski** [ultralytics/ultralytics#6096]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict, Track

### Bug

Consider this script that was found in the YoloV8 Documentation, with modifications to accommodate my model file and input video along with writing the frames to a mp4:

found here: https://docs.ultralytics.com/modes/track/#plotting-tracks-over-time

```from collections import defaultdict

import cv2
import numpy as np

from ultralytics import YOLO


# Load the YOLOv8 model
model = YOLO('best_crowd.pt')

# Open the video file
video_path = "vid1.mp4"
cap = cv2.VideoCapture(video_path)

writer = cv2.VideoWriter('out.mp4', cv2.VideoWriter_fourcc(*'mp4v'), 10.0, (640,360))


# Store the track history
track_history = defaultdict(lambda: [])

while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 tracking on the frame, persisting tracks between frames
        results = model.track(frame, persist=True, augment=True, half=False)

        # Get the boxes and track IDs
        boxes = results[0].boxes.xywh.cpu()
        track_ids = results[0].boxes.id.int().cpu().tolist()
        print(track_ids)

        # Visualize the results on the frame
        annotated_frame = results[0].plot(line_width=1)

        # Plot the tracks
        for box, track_id in zip(boxes, track_ids):
            x, y, w, h = box
            track = track_history[track_id]
            track.append((float(x), float(y)))  # x, y center point
            if len(track) > 30:  # retain 90 tracks for 90 frames
                track.pop(0)

            # Draw the tracking lines
            points = np.hstack(track).astype(np.int32).reshape((-1, 1, 2))
            cv2.polylines(annotated_frame, [points], isClosed=False, color=(230, 230, 230), thickness=1)

        # Display the annotated frame
        cv2.imshow("YOLOv8 Tracking", annotated_frame)
        writer.write(annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
writer.release()
cap.release()
cv2.destroyAllWindows()
```

When I run this script on my mac, everything works and tracking is correct, paths are traced correctly:

<img width="227" alt="Screenshot 2023-11-02 at 2 24 46 PM" src="https://github.com/ultralytics/ultralytics/assets/11874286/0c2324fc-e891-4d97-b0cc-9c28093da691">

But when I run the same exact script on an EC2 instance, it seems like the tacks stop persisting and get freshly initiated every single frame, resulting in jumpy tracks. On every individual frame IDs always start at 1, and end at the number of tracks. This is similar to what you would see if persist=False, but it truly is the same script and Persist=True.

<img width="236" alt="Screenshot 2023-11-02 at 2 25 18 PM" src="https://github.com/ultralytics/ultralytics/assets/11874286/f5df4b62-94b3-435f-a98e-6212d74711a2">

I am a bit confused by the behavior, and am hoping for someone else to either reproduce it. I have personally found that tracking works on my Apple M1 laptop, but does not work on a colab notebook or on an EC2 instance.

Thanks for any help!

### Environment

EC2 Instance

```
Ultralytics YOLOv8.0.203 🚀 Python-3.10.9 torch-2.1.0+cu121 CUDA:0 (Tesla M60, 7613MiB)
Setup complete ✅ (16 CPUs, 119.9 GB RAM, 31.2/50.0 GB disk)

OS                  Linux-5.10.192-183.736.amzn2.x86_64-x86_64-with-glibc2.26
Environment         Linux
Python              3.10.9
Install             pip
RAM                 119.86 GB
CPU                 Intel Xeon E5-2686 v4 2.30GHz
CUDA                12.1

matplotlib          ✅ 3.8.1>=3.3.0
numpy               ✅ 1.26.1>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.28.2>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 2.1.0>=1.8.0
torchvision         ✅ 0.16.0>=0.9.0
tqdm                ✅ 4.64.1>=4.64.0
pandas              ✅ 2.1.2>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
```

M1 Mac

```
Ultralytics YOLOv8.0.202 🚀 Python-3.10.3 torch-2.1.0 CPU (Apple M1 Pro)
Setup complete ✅ (10 CPUs, 16.0 GB RAM, 562.6/926.4 GB disk)

OS                  macOS-14.0-arm64-arm-64bit
Environment         Darwin
Python              3.10.3
Install             pip
RAM                 16.00 GB
CPU                 Apple M1 Pro
CUDA                None

matplotlib          ✅ 3.8.0>=3.3.0
numpy               ✅ 1.26.1>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 2.1.0>=1.8.0
torchvision         ✅ 0.16.0>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.1.2>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
```

### Minimal Reproducible Example

Included in main question.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by NickLojewski** [comment]
Update:

I kept digging and realized that I was running YOLOv8.0.202 on the M1 Mac and YOLOv8.0.203 on the notebook and EC2 instance as it is the latest.

I downgraded the version on the EC2 instance to YOLOv8.0.202 and the issue is fixed. It appears some bug may have been introduced in YOLOv8.0.203.

```
pip uninstall ultralytics
pip install ultralytics==8.0.202
```

**Comment by glenn-jocher** [comment]
@NickLojewski thank you for your update, and it's great to hear you found a workaround!

From your description, it seems like you might have come across some kind of problem or bug linked to the YOLOv8.0.203 version. Without specific details it's hard to say exactly what might have gone wrong, but it's important to flag this issue, so changes or updates in YOLOv8.0.203 don't interrupt your work or the work of others.

We recommend always running the latest version of the package, so this is definitely something we want to investigate. I'll share your findings with our development team so they can look into any potential issues associated with the YOLOv8.0.203 version.

In the meantime, continue with the downgraded version that is currently more stable and suitable for your specific project needs. Please don't hesitate to reach out if you encounter further issues or if you have any more information or updates that you think might be helpful to share. Your feedback helps us make our tool better.

Thanks again!

**Comment by glenn-jocher** [comment]
@NickLojewski bug seems to be identified here by another user:
https://github.com/ultralytics/ultralytics/commit/465df3024f44fa97d4fad9986530d5a13cdabdca#r131579367

**Comment by glenn-jocher** [comment]
@Laughing-q it looks like one of the lines in https://github.com/ultralytics/ultralytics/pull/5979 is causing issues in the tracker example in our docs with the lines resetting every frame. The line is here according to a user:
https://github.com/ultralytics/ultralytics/commit/465df3024f44fa97d4fad9986530d5a13cdabdca#r131579367

**Comment by glenn-jocher** [comment]
@NickLojewski great news 😃! Your original issue may now be resolved ✅ in PR #6145 and published in `ultralytics 8.0.207`. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by NickLojewski** [comment]
Confirming that the bug is fixed in the newest release!

**Comment by glenn-jocher** [comment]
@NickLojewski that's fantastic news! We're thrilled to hear that the latest release has resolved the bug you were experiencing. Your feedback is invaluable, and it's a big part of how we improve our offerings. Rest assured, our team is committed to providing the best possible experience with YOLOv8, and we're always here to support you.

If you encounter any more issues or have further feedback in the future, please don't hesitate to reach out. Your contributions help us ensure YOLOv8 remains a powerful and reliable tool for the community. Happy detecting, and we wish you continued success with your projects using YOLOv8!
