### ISSUE TITLE
how to train a model with keypoints

### ISSUE THREAD

**Issue by Joaofelipe14** [ultralytics/ultralytics#6106]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have images with 21 key points as follows

`
path: ./
val: valid

train: train # train images (relative to 'path') val: valid #val images (relative to 'path')

kpt_shape: [21,3]

names:
  0: mao
`

My label `0 0.41627358490566035 0.596875 0.30542452830188677 0.73125 0.4622149169445038 0.29286280274391174 0.508120596408844 0.37367188930511475 0.5243274569511414 0.47323644161224365 0.5193498730659485 0.5566926002502441 0.5087950229644775 0.610885739326477 0.5135531425476074 0.5467778444290161 0.5323033928871155 0.6980131268501280.5392429232597351 0.7884784936904907 0.5443596243858337 0.8653091192245483 0.46553295850753784 0.53912353515625 0.4568563997745514 0.7119987607002258 0.44901689887046814 0.8192725777626038 0.44390758872032166 0.9039645195007324 0.4201620817184448 0.49723756313323975 0.3918296992778778 0.6496049165725708 0.37157225608825684 0.7451557517051697 0.35645318031311035 0.8194926977157593 0.3823433518409729 0.4391724765300751 0.3370039463043213 0.525426983833313 0.3100035786628723 0.5830339789390564 0.2890143394470215 0.6354591846466064 `

Exception has occurred: ValueError
not enough values to unpack (expected 3, got 0)
  File "C:\python\treinamento.py", line 6, in <module>
    model.train(
ValueError: not enough values to unpack (expected 3, got 0)

how to resolve?

**Comment by RizwanMunawar** [comment]
Replace `kpt_shape: [21,3]` with `kpt_shape: [21,2]` in your code, @Joaofelipe14, and it should work fine. Your images are 2D, and the key points are 2D as well, not 3D keypoints.

**Comment by ACanFirat** [comment]
I have an issue while training

sample txt file:
"""
0 
0.48935185185185187 0.4830729166666667 0.8268518518518518 0.2671875 
0.1425925925925926 0.3578125 2 0.862037037037037 0.36614583333333334 2 0.8851851851851852 0.6052083333333333 2 0.0962962962962963 0.5989583333333334 2
"""

yaml file:
"""
path: path_to_data/front_side 
train: images/train 
val: images/val  
kpt_shape: [4, 3]  # 4 for each point, 3 for there are x, y and visuality
flip_idx: [0, 1, 2, 3]  
names:   
    0: front_side 
"""

train.py:
"""
from ultralytics import YOLO   
model = YOLO("yolov8n-pose.pt") 
model.train(data=r"path_to_yaml\dataset.yaml", epochs=200, 
                                  imgsz=640, project="front_side_keypoint") 
"""

Issue:
"""
File "...\ultralytics\data\dataset.py", line 125, in get_labels
    len_cls, len_boxes, len_segments = (sum(x) for x in zip(*lengths))
ValueError: not enough values to unpack (expected 3, got 0)
"""

I run it on A5000 and ultralytics: 8.0.227

Everything seems good but i dont understand why it isnt running

**Comment by glenn-jocher** [comment]
@ACanFirat it looks like there is an issue with the data parsing. Please ensure that your label format follows the correct structure for keypoint detection as outlined in the Ultralytics documentation. Also, confirm that the `kpt_shape` in your YAML file matches the format and actual keypoint data present in your label files. If the problem persists, double-check paths to your dataset and make sure you're using the most recent version of the Ultralytics YOLOv8 repository.
