### ISSUE TITLE
how can i get mAP50 in prediction

### ISSUE THREAD

**Issue by futurelee2** [ultralytics/ultralytics#6108]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

when i predict I want to get prediction bounding box coordinates with completed NMS and mAP50 
I wonder which part should be modified and used to get the mAP50 value simply.

I got bbox coordinates, but I haven't got mAP50 yet
My code is written like this.

for img in img_list:
    source = "img_folder_path"
    results = model(source, save = True, conf = 0.5)
    for result in results:
        box = result.boxes

If this code is wrong, please let me know how to get coordinates with completed NMS and mAP50  at once

**Comment by RizwanMunawar** [comment]
@futurelee2 you can use the mentioned code to get the map50 values easily.

```python
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')  # load an official model
model = YOLO('path/to/best.pt')  # load a custom model

# Validate the model
metrics = model.val()  # no arguments needed, dataset and settings remembered
metrics.box.map50  # map50
```

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by futurelee2** [comment]
How can I get prediction coordinates with completed NMS  from the code you told me?

**Comment by Gandalf-Xu** [comment]
Hello, for related issues, there are some questions here.
How can i get mAP50 or F1-Score in the prediction of an image(label present)? is there existing 'valuation' API?
Additionly，for a video dataset，how to calculate the relevant metrics mentioned above? is it just the average value of each video frame?
I am a beginner, and i would greatly appreciate it if you could help me or give me some tips! Thanks a lot!

**Comment by glenn-jocher** [comment]
@futurelee2 hello,

Let's tackle your questions one by one:

1. For calculating mAP50 or F1-Score in the prediction of an image, Ultralytics YOLOv8 provides built-in functionality for this. When you validate your trained model (`model.val()`), it internally calculates these metrics for you. You may access these metrics within the returned object. Please check the validation examples in the usage documentation.

2. For a video dataset, metrics like mAP50 or F1-Score are essentially averaged over all the frames. It would be a calculation of the metrics for each frame and then an average over the total number of frames. You could take this approach to get your answer.

Remember, understanding the metrics and how they inform your model's performance is a critical part of machine learning and improving your model. Your questions indicate you're on the right path.

Let us know if you need further assistance. Keep exploring and happy coding!

Best,
Glenn

**Comment by Gandalf-Xu** [comment]
Thank you for answer! :)

**Comment by glenn-jocher** [comment]
@Gandalf-Xu you're very welcome! I'm glad I could assist. If you have further questions or encounter any issues, don't hesitate to reach back out. Happy coding with YOLOv8!
