### ISSUE TITLE
How do you use coco guidelines for evaluation?

### ISSUE THREAD

**Issue by op-newman** [ultralytics/ultralytics#6112]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In my use of yolov8 I find that I can't use coco for evaluation, I would like to ask if there is a specific solution for this, because the metrics aps apl and apm in coco are very important for me

**Comment by glenn-jocher** [comment]
@op-newman thanks for raising your question. 

When using YOLOv8, you can evaluate your trained model against datasets like COCO. The evaluation method includes metrics like APs, APL, and APM, which you mentioned are important for your project.

In our repo, when `val.py` is run to perform validation on the trained model, the function `coco_evaluator()` is used. Inside this function, it calculates precision, recall, and the AP and plots them for the different categories in the COCO dataset.

If you are running a training session, validation using COCO standards is done automatically at the end of every epoch if you have the flag `--val` set. The validation data will automatically use the same metrics used by COCO, including APs, APL, and APM.

Remember that you need to format your data in the COCO style Dataset for this to work, which essentially requires bounding box coordinates, class labels, and an indication of which images are for training and which are for validation. Of course, the COCO dataset itself will already be formatted appropriately.

Hope this helps and happy training!

**Comment by op-newman** [comment]
I'm very sorry, I guess I still don't understand how to use it, can you explain it more clearly. I am still in doubt about how to implement it, thank you very much for your help.

**Comment by glenn-jocher** [comment]
@op-newman no problem at all, I understand that these concepts can be complex when starting out.

When you train a model with YOLOv8 on a dataset like COCO, evaluation using the desired metrics (APs, APL, and APM) happens automatically at the end of each epoch if the `--val` flag is enabled during training. "Epoch" in this context means a full pass through the dataset during training. 

In YOLOv8, evaluation is performed using COCO-style metrics. The relevant evaluation function called `coco_evaluator()` is invoked when validation is performed. The computed metrics include precision, recall, and average precision (AP), which are key indicators of your model's performance.

For this to work, your data needs to be in the COCO format, meaning, it should include bounding box coordinates, class labels, and should identify which images are for training and which are for validation.

In case you make any modifications in the code and want to adjust the evaluation metrics, you can look for the `coco_evaluator()` function that is responsible for calculating these performance measures.

I hope this clears up the process. If you still have questions, feel free to ask. I'm here to help!
