### ISSUE TITLE
Bounding box outside of the image

### ISSUE THREAD

**Issue by salihmarangoz** [ultralytics/ultralytics#6117]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a dataset with bounding boxes and keypoints, and there are many bounding boxes with some of them on the edges of the image, sometimes more than half of the bounding boxes are located outside of the image.

Is there any way to disable clipping? Can YOLO estimate bounding boxes in case of the object is not fully observed (including cases where a part of object is outside of the image)?

**Comment by glenn-jocher** [comment]
@salihmarangoz hello,

Thank you for reaching out with your question.

From the way YOLOv8 works, bounding boxes with parts outside the image have their coordinates clipped to stay within the image boundaries, mainly to ensure the bounding boxes reflect real regions in the obtained output. 

However, I understand your requirement, but currently, our YOLOv8 model does not have an integrated feature to disable this bounding box clipping. 

As for estimating bounding boxes even when an object is not fully observed, that really depends on the training data and how well the model has been trained to recognize partially visible instances of the objects.

Your feedback is valuable to us and could infer potential updates to our model. In the meanwhile, you may consider implementing custom function to cater for your specific needs.

Cheers!
