### ISSUE TITLE
Yolov8 POST Requests Without User Notification 🎁

### ISSUE THREAD

**Issue by FourierMourier** [ultralytics/ultralytics#6119]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

**Hello there, let's discuss user privacy.**

# Short info
Some member of my team found out that setting logging mode to debug
`logging.basicConfig(level=logging.DEBUG)`
resulted in the following print statement:

> 2023-11-03 x:z:x,yyy DEBUG urllib3.connectionpool Starting new HTTPS connection (1): www.google-analytics.com:443
> 2023-11-03 x:z:x,yyy DEBUG urllib3.connectionpool https://www.google-analytics.com:443 "POST /mp/collect?measurement_id=G-X8NCJYTQXM&api_secret=QLQrATrNSwGRFRLE-cbHJw HTTP/1.1" 204 0

whenever the model.predict method was called (!).

So it turned out the package itself sends some data in the following code:
 /ultralytics/hub/utils.py lines 211-215:
```
        # Time is over rate limiter, send now
        data = {'client_id': SETTINGS['uuid'], 'events': self.events}  # SHA-256 anonymized UUID hash and events list

        # POST equivalent to requests.post(self.url, json=data)
        smart_request('post', self.url, json=data, retry=0, verbose=False)
```
I see that it's hashed etc, but I don't want any other software sending my data over the internet without my consent. Furthermore, the URL is hidden in a class declaration and it sends settings that include local paths - it would be much better to ask users for that or at least notify and provide method to disable it.

Also, I found that there was an issue about it, but it hasn't been answered yet for 6 months: https://github.com/ultralytics/ultralytics/issues/2250#issue-1684710313

# How to get rid of it
There're several ways that seem to work:
## Manually change defaults configuration
In the ultralytics/utils/__init__.py you can find self.defaults argument starting from line 767:
 ```
       self.defaults = {
            'settings_version': version,
            'datasets_dir': str(datasets_root / 'datasets'),
            'weights_dir': str(root / 'weights'),
            'runs_dir': str(root / 'runs'),
            'uuid': hashlib.sha256(str(uuid.getnode()).encode()).hexdigest(),
            'sync': True,
```
change here 'sync': True -> 'sync': False. 
But as soon as new package version is installed you'll get the initial behavior.

## Disable defaults by importing events:
You can actually import from ultralytics/hub/utils.py `Events`  and set events.enabled=False BEFORE you actually do .predict
so wherever you do your imports please add the following lines of the code:
```
from ultralytics.hub.utils import events
events.enabled = False
```

## Write your own wrapper for model predictions
You actually can rewrite the model predictors themselves and make sure there's no suspicious actions are taken - just clear up all callbacks the initial version has right now.

**Comment by glenn-jocher** [comment]
@FourierMourier hello,

Thank you for bringing this to our attention and for your thorough suggestion. Privacy and user consent are critical issues in today's age. The feature you mentioned was implemented with an intention to provide better support and understand the usage of our tool more accurately. However, we value user trust and privacy above all.

The debug logs for google-analytics.com that you're seeing are part of our anonymized usage analytics. It's important to note that the sent information is completely anonymized and is used purely for understanding usage patterns and improving our software.

However, we do understand your concern and realize we should have made this more transparent to our users. We certainly had no intention of hiding this information from you or anyone using our repo.

Based on your feedback, we will further improve our documentation and will provide a clearer description of our analytics approach as well as provide instructions on how to disable this feature. I appreciate your suggestions on how to modify the package's default configuration to disable this feature. These changes clearly reflect the importance we place on our community's input.

To address this specific issue, we'll look to implement an opt-out feature in a future update to allow users to disable this tracking if they choose to.

Meanwhile, your workaround suggestions can be implemented if users want to stop sending anonymized analytics data. But remember, future updates to YOLOv8 might revert these changes.

Once again, thank you for your feedback. It's invaluable in helping us make our tools better.

Best regards,
Glenn Jocher

**Comment by glenn-jocher** [comment]
@FourierMourier thank you for sharing your concerns about user privacy and the observations made while in debug mode. We truly appreciate your vigilance as security and data privacy is something we hold in high regard. We have designed options for users to comfortably opt out of data collection should they choose to.

The behavior noticed is a part of our initiative to gather anonymized usage statistics and crash reports, aiming to enhance user experience and uphold the reliability of our software. This is elaborated in our [Data Collection for Ultralytics Python Package](https://docs.ultralytics.com/help/privacy) documentation. Rest assured, the data relayed to Google Analytics is anonymized and aggregated, with no personally identifiable information (PII) or local path names being collected.

However, we appreciate that users may wish to opt out of this data collection, and offer a simple way to do so. You can set `sync=False` in your YOLO settings to opt out of sending analytics and crash reports. Here's how you can do it in Python:

```python
from ultralytics import settings

# Disable analytics and crash reporting
settings.update({'sync': False})
```

Alternatively, you can use the command-line interface to modify your settings:

```bash
# Disable analytics and crash reporting
yolo settings sync=False
```

Your settings will be respected across all sessions using the Ultralytics package and saved to disk for future sessions. If you update your `ultralytics` package in the future your current settings including any opt-outs will be remembered and will only change if you choose to update your settings again.

Additionally, if you have any further questions or concerns about our data collection practices, feel free to reach out to us via our [contact form](https://ultralytics.com/contact) or via [support@ultralytics.com](mailto:support@ultralytics.com). We are dedicated to ensuring our users feel informed and confident in their privacy when using our package.

**Comment by FourierMourier** [comment]
Hi @glenn-jocher , thank you for your prompt response. I recently reviewed the documentation, probably two days ago, and might have missed part about it. I'm glad it's clarified in your documentation now. It seems settings.update results in disabling events too.

**Comment by glenn-jocher** [comment]
@FourierMourier hello,

I'm glad to hear that your concerns were addressed. Indeed, the `settings.update` function when used with the parameter `{'sync': False}` not only disables the sending of anonymized usage statistics but effectively disables event collections as well. Our aim in implementing this was to allow users to have full control over privacy settings according to their preferences.

Please don't hesitate to raise any more questions or issues you might encounter. We're here to help and ensure your experience with YOLOv8 is enjoyable and productive. Thank you for being part of the YOLOv8 community!

Best Regards,
Glenn Jocher
