### ISSUE TITLE
Struggling to run the model

### ISSUE THREAD

**Issue by Safouane** [ultralytics/ultralytics#6130]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey,
i'm trying to test YOLOv8, but im struggling to run the command that trains the model:
`model.train(data="dataset_config.yaml", epochs=3)`
the **_dataset_config.yaml_** file is in the same directory as the Jupyter Notebook file.
Here is the content of my **_dataset_config.yaml_** file:

```
path: C:\Users\safou\Documents\ML\Datasets\Plantvillage_strawberries  # dataset root dir
train:\images\train  # train images (relative to 'path') 
val: images\val  # validate images (relative to 'path') 
test:  # test images (optional)

# Classes (2 Strawberry classes)
names:
  0: Not_Healthy
  1: Healthy
```

And here is the error messages i got:
```
Ultralytics YOLOv8.0.206  Python-3.11.5 torch-2.1.0+cpu CPU (AMD Ryzen 9 4900HS with Radeon Graphics)
engine\trainer: task=classify, mode=train, model=yolov8n-cls.yaml, data=dataset_config.yaml, epochs=3, patience=50, batch=16, imgsz=224, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train6, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs\classify\train6

Dataset not found , missing path C:\Users\safou\My Drive\V2\Strawberries\training\yolov5\datasets\dataset_config.yaml, attempting download...
Dataset download success  (0.0s), saved to C:\Users\safou\My Drive\V2\Strawberries\training\yolov5\datasets\dataset_config.yaml
```

**by tw, i dont know why it randomly points to this random directory in the last line.
because of that error, i cleaned then reinstalled, Anaconda, Python, and pip installed Ultralytics again.**

**Here is the full python error :**

```
FileNotFoundError                         Traceback (most recent call last)
File C:\ProgramData\anaconda3\Lib\site-packages\ultralytics\engine\trainer.py:114, in BaseTrainer.__init__(self, cfg, overrides, _callbacks)
    113 if self.args.task == 'classify':
--> 114     self.data = check_cls_dataset(self.args.data)
    115 elif self.args.data.split('.')[-1] in ('yaml', 'yml') or self.args.task in ('detect', 'segment', 'pose'):

File C:\ProgramData\anaconda3\Lib\site-packages\ultralytics\data\utils.py:377, in check_cls_dataset(dataset, split)
    376 nc = len([x for x in (data_dir / 'train').glob('*') if x.is_dir()])  # number of classes
--> 377 names = [x.name for x in (data_dir / 'train').iterdir() if x.is_dir()]  # class names list
    378 names = dict(enumerate(sorted(names)))

File C:\ProgramData\anaconda3\Lib\site-packages\ultralytics\data\utils.py:377, in <listcomp>(.0)
    376 nc = len([x for x in (data_dir / 'train').glob('*') if x.is_dir()])  # number of classes
--> 377 names = [x.name for x in (data_dir / 'train').iterdir() if x.is_dir()]  # class names list
    378 names = dict(enumerate(sorted(names)))

File C:\ProgramData\anaconda3\Lib\pathlib.py:931, in Path.iterdir(self)
    928 """Iterate over the files in this directory.  Does not yield any
    929 result for the special paths '.' and '..'.
    930 """
--> 931 for name in os.listdir(self):
    932     yield self._make_child_relpath(name)

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\safou\\My Drive\\V2\\Strawberries\\training\\yolov5\\datasets\\dataset_config.yaml\\train'

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
Cell In[11], line 1
----> 1 model.train(data="dataset_config.yaml", epochs=3)

File C:\ProgramData\anaconda3\Lib\site-packages\ultralytics\engine\model.py:333, in Model.train(self, trainer, **kwargs)
    330 if args.get('resume'):
    331     args['resume'] = self.ckpt_path
--> 333 self.trainer = (trainer or self._smart_load('trainer'))(overrides=args, _callbacks=self.callbacks)
    334 if not args.get('resume'):  # manually set model only if not resuming
    335     self.trainer.model = self.trainer.get_model(weights=self.model if self.ckpt else None, cfg=self.model.yaml)

File C:\ProgramData\anaconda3\Lib\site-packages\ultralytics\models\yolo\classify\train.py:39, in ClassificationTrainer.__init__(self, cfg, overrides, _callbacks)
     37 if overrides.get('imgsz') is None:
     38     overrides['imgsz'] = 224
---> 39 super().__init__(cfg, overrides, _callbacks)

File C:\ProgramData\anaconda3\Lib\site-packages\ultralytics\engine\trainer.py:120, in BaseTrainer.__init__(self, cfg, overrides, _callbacks)
    118             self.args.data = self.data['yaml_file']  # for validating 'yolo train data=url.zip' usage
    119 except Exception as e:
--> 120     raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
    122 self.trainset, self.testset = self.get_dataset(self.data)
    123 self.ema = None

RuntimeError: Dataset 'dataset_config.yaml' error  [WinError 3] The system cannot find the path specified: 'C:\\Users\\safou\\My Drive\\V2\\Strawberries\\training\\yolov5\\datasets\\dataset_config.yaml\\train'
```

**Comment by Safouane** [comment]
I think I had a problem in the dataset structure:
I want to use the YOLOv8 classification model `yolov8-cls`
but in my dataset, I had images that contain different classes in the same image, while in the dataset structure of the classification model, I can only structure classes in different folders, each class in a separate folder.

**Comment by glenn-jocher** [comment]
@Safouane hello,

From your query, it seems you are intending to perform a multi-label image classification, but you are not sure how to structure your dataset in this type of task.

Let me explain how you can achieve this. YOLOv8 supports multi-label classification, where a single image can belong to multiple classes. However, this requires a different dataset layout compared to one class per folder. 

In a multi-label classification task, typically, we don't structure classes into different folders. Instead, we accompany our dataset with a .csv or .txt file that specifies the labels for each image. Each image filename would be listed in this file, along with its corresponding labels.

Regarding your dataset structure issue, what you can do is to create a file that contains all your image paths along with their labels. For each image, if it belongs to multiple classes, you can assign all those classes in the same line separated by spaces, tabs, or any delimiters of your choice. 

Once you've structured your dataset in this way and created your label file, you can train your model directly with this data.

I hope this answers your question. Do let us know if you need further assistance.

Happy training!

**Comment by RizwanMunawar** [comment]
@Safouane Thanks for sharing the detailed information!

I think you are using a Windows machine. Your `dataset_config.yaml` file should be like the one I mentioned


### dataset_config.yaml
```
path: "C:\\Users\\safou\\Documents\\ML\\Datasets\\Plantvillage_strawberries"  # dataset root dir
train: "images\\train"  # train images (relative to 'path') 
val: "images\\val"  # validate images (relative to 'path') 
test:  # test images (optional)

# Classes (2 Strawberry classes)
names:
  0: Not_Healthy
  1: Healthy
```

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by Safouane** [comment]
> @Safouane hello,
> 
> From your query, it seems you are intending to perform a multi-label image classification, but you are not sure how to structure your dataset in this type of task.
> 
> Let me explain how you can achieve this. YOLOv8 supports multi-label classification, where a single image can belong to multiple classes. However, this requires a different dataset layout compared to one class per folder.
> 
> In a multi-label classification task, typically, we don't structure classes into different folders. Instead, we accompany our dataset with a .csv or .txt file that specifies the labels for each image. Each image filename would be listed in this file, along with its corresponding labels.
> 
> Regarding your dataset structure issue, what you can do is to create a file that contains all your image paths along with their labels. For each image, if it belongs to multiple classes, you can assign all those classes in the same line separated by spaces, tabs, or any delimiters of your choice.
> 
> Once you've structured your dataset in this way and created your label file, you can train your model directly with this data.
> 
> I hope this answers your question. Do let us know if you need further assistance.
> 
> Happy training!

Thanks for the explanations. Just one question: if i follow your steps, should i use  `yolov8n` or `yolov8n-cls`

**Comment by glenn-jocher** [comment]
Hello @Safouane,

Both `yolov8n` and `yolov8n-cls` models can be used for multi-label classification. The difference between the two models is in their use cases. `yolov8n` is generally used for object detection tasks, where the goal is to find the location of an object in an image, while `yolov8n-cls` is used for pure classification tasks, where the goal is to classify an image into one or more classes without locating the object in the image.

In your case, since you are trying to classify images with multiple labels but not interested in locating the objects, you should use `yolov8n-cls`. 

Do let us know if you have more questions or need further assistance. Happy training!

**Comment by Safouane** [comment]
Thanks for your helpful comment.
Actually, my goal is to **classify images with multiple labels, BUT I'm interested in locating the objects inside the images**. To give you a clear idea, I want to classify if a plant leaf is healthy or not, so in some cases one image could have a healthy and not healthy leaf in the same time, and I want to locate the object using YOLO's bounding boxes.

**Comment by glenn-jocher** [comment]
@Safouane hello,

I appreciate the clarity in your project goals. If you want to classify and also locate objects within the same image using YOLOv8, that's a task well-suited for object detection, not just classification. Given your requirement to identify whether plant leaves are healthy or not and to determine their specific locations within the images, you would indeed require the full capabilities of YOLOv8's object detection model.

For such a task, you should annotate your images with bounding boxes around each leaf, labeling them accordingly as 'Healthy' or 'Not Healthy'. This annotated dataset will train the YOLOv8 object detection model to recognize and localize the healthy and unhealthy leaves in any given image.

During training, the model will learn both the appearances of the different leaf conditions and their spatial positions in the image frame. Once trained, YOLOv8 will be able to provide you with bounding boxes for each leaf classifier, thereby satisfying your dual requirements of classification and localization.

Feel free to proceed with this approach, and we look forward to hearing about your success with YOLOv8 in your project to classify and locate plant leaf health!

Best regards and happy training!

**Comment by akashi3008** [comment]
Hey,
i'm trying to test YOLOv8, but i'm struggling to run the command that trains the model:
model.train(data="datasetv8.yaml", epochs=3)
the datasetv8.yaml file is in the same directory as the Jupyter Notebook file.
Here is the content of my datasetv8.yaml file:

path: "C:\\Users\\91960\\Desktop\\python projects\\yolov8\\datav8"
train: "images\\train"
val: "images\\val"

# Classes
nc : 17 
names : ['dog','person','cat','tv','car','meatballs','marinara sauce','tomato soup','chicken noodle soup','french onion soup','chicken breast', 'ribs', 'pulled pork', 'hamburger','cavity','awake','drowsy']

And I'm getting this error:
FileNotFoundError                         Traceback (most recent call last)
~\anaconda3\lib\site-packages\ultralytics\engine\trainer.py in __init__(self, cfg, overrides, _callbacks)
    132             elif self.args.data.split(".")[-1] in ("yaml", "yml") or self.args.task in ("detect", "segment", "pose"):
--> 133                 self.data = check_det_dataset(self.args.data)
    134                 if "yaml_file" in self.data:

~\anaconda3\lib\site-packages\ultralytics\data\utils.py in check_det_dataset(dataset, autodownload)
    266 
--> 267     file = check_file(dataset)
    268 

~\anaconda3\lib\site-packages\ultralytics\utils\checks.py in check_file(file, suffix, download, hard)
    497         if not files and hard:
--> 498             raise FileNotFoundError(f"'{file}' does not exist")
    499         elif len(files) > 1 and hard:

FileNotFoundError: 'datasetv8.yaml' does not exist

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_16860/3520225275.py in <module>
----> 1 model.train(data="datasetv8.yaml", epochs=1)

~\anaconda3\lib\site-packages\ultralytics\engine\model.py in train(self, trainer, **kwargs)
    633             args["resume"] = self.ckpt_path
    634 
--> 635         self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
    636         if not args.get("resume"):  # manually set model only if not resuming
    637             self.trainer.model = self.trainer.get_model(weights=self.model if self.ckpt else None, cfg=self.model.yaml)

~\anaconda3\lib\site-packages\ultralytics\engine\trainer.py in __init__(self, cfg, overrides, _callbacks)
    135                     self.args.data = self.data["yaml_file"]  # for validating 'yolo train data=url.zip' usage
    136         except Exception as e:
--> 137             raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
    138 
    139         self.trainset, self.testset = self.get_dataset(self.data)

RuntimeError: Dataset 'datasetv8.yaml' error  'datasetv8.yaml' does not exist
​
