### ISSUE TITLE
On the hyperparametric problem of yolov8s

### ISSUE THREAD

**Issue by Iwill-github** [ultralytics/ultralytics#6140]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

     Hello, due to academic reasons, I did not use pre trained weights to reproduce your YOLOV8S and did not achieve the effect of 44.9. Is it because my hyperparameter settings were incorrect or some settings were omitted? My training commands are as follows, and the remaining hyperparameters follow the default settings.

`yolo detect train data=coco.yaml model=yolov8s.yaml epochs=300 batch=128`

**Comment by RizwanMunawar** [comment]
Based on my interpretation, it seems you're indicating that you couldn't achieve results matching those in the YOLOv8 benchmarks, and you haven't utilized the pretrained model from Ultralytics YOLOv8.

If that's the situation, please be aware that we can only offer feedback on the Ultralytics YOLOv8 models. We may not be able to assist with other implementations.

Hope this helps! Let me know if you have any additional questions.

Thanks 
Muhammad, Ultralytics
