### ISSUE TITLE
About on different methods of training models

### ISSUE THREAD

**Issue by gailun-lungai** [ultralytics/ultralytics#6146]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

**Question**
`I attempted to modify the yolov8.yaml file and trained it on the same dataset using the following two methods. Strangely, there are differences between the results obtained from the two training sessions and the PT file viewed by nerton. May I ask what the reason is?`
The two training methods are as follows：
1. 
```
model = YOLO('yolov8_modified.yaml')  # build a new model from YAML
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)

```
2. 
`model = YOLO('yolov8_modified.yaml').load('yolov8n.pt')  # build from YAML and transfer weights`
When using nerton to view pt files, the first method trains the visualization results to be the same as the yolov8n. pt network structure, while the second method is the modified yaml file structure. In addition, the training time and final indicators of the two methods are also different. Can the author please explain the reason?

**Comment by gailun-lungai** [comment]
您发送的邮件我已收到，感谢对工作的支持！

**Comment by glenn-jocher** [comment]
@gailun-lungai hello, thank you for your detailed question about the methods of training models in YOLOv8.

From what you've described, it appears you're training the model in two different ways, which is causing the disparity in results. 

For the first method, the model is initially built from your modified YAML file (‘yolov8_modified.yaml’), and then overwritten by loading the pretrained 'yolov8n.pt'. So in this sequence, your changes to the YAML file are effectively ignored. This is why the network structure is the same as 'yolov8n.pt' when you visualize the trained model using Netron.

In contrast, with the second method, you're building the model from your modified YAML file and then only transferring the weights from the pretrained 'yolov8n.pt'. This means the architecture is maintained from your YAML file, hence you see the modified YAML file structure in Netron. In this case, the pretrained weights start the training from a presumably more optimized state which can lead to differences in the final model performance and training time.

In brief, the first method ignores the modifications you've made in YAML file, while the second one preserves them but transfers the weights from the pretrained model, leading to differences in structure, performance, and training time.

**Comment by gailun-lungai** [comment]
Thanks for the answer! Your answer was very helpful to me, thank you again!

**Comment by glenn-jocher** [comment]
@gailun-lungai you're welcome! I'm glad to hear that the information was helpful to you. Feel free to ask if you have any other questions regarding YOLOv8 - we're here to help. Happy coding and best of luck with your work!
