### ISSUE TITLE
how to get detected object coordinates from real-time instance segmentation detection.

### ISSUE THREAD

**Issue by tjdwo8577** [ultralytics/ultralytics#6148]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi I trained my custom dataset and extract best.pt file. I would like to use real-time detect instance segmentation and also get coordinates of detected object from webcam. 

Is there any source code for both real-time detect instance segmentation and get coordinates of detected object?

Thank you in advance.

**Comment by glenn-jocher** [comment]
@tjdwo8577 hi,

In YOLOv8, you can accomplish both tasks during real-time detection. For object detection and instance segmentation, the detection results include bounding boxes around detected objects. These bounding boxes in return provide the coordinates of the detected objects from the camera feed.

For using this with a webcam, you would process your camera's video frames in real-time with your trained YOLOv8 model. The model's output will include the bounding boxes for detected objects which are defined by their coordinates in the frame. Additionally, if configured appropriately, the instance segmentation masks for these objects will also be generated.

While I cannot provide specific code here, you should prepare your program to handle these outputs of the model, extracting the coordinates of the detected objects and their instance segmentation masks from the model predictions.

Make sure to use the real-time capture functionality of the camera and feed the captured frames into the YOLOv8 inferencing engine. The output, as explained, will include the information about the bounding boxes and segmentation masks you require.

Best of luck with your project! And don't hesitate to post again if you have more questions.

Best,
Glenn
