### ISSUE TITLE
How to extrack backbone and neck of yolov8

### ISSUE THREAD

**Issue by zhaowenZhou** [ultralytics/ultralytics#6155]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thank you for your great work and this amazing structure!
This model has inspired me a lot and Im willing to work on my own project using its backbone and neck structure with its pretrained-weight as well.
So, after initializing the model using the pretrained weight, how can I know extract the backbone and necks part of it?

### Additional

No

**Comment by glenn-jocher** [comment]
@zhaowenZhou hello and thanks for your enthusiasm towards YOLOv8! It's great to see your interest in working with the backbone and neck components of the model. 

To start, the `Model` class in YOLOv8 is structured in a way that each component of the model, including the backbone and neck, is presented as separate modules. This can be accessed using the `.model` attribute.

The `model.model` attribute returns an `nn.Sequential` object that encompasses all the layers including the backbone and neck. The `model.model` is essentially a list, so you can access the backbone and the neck by indexing into it.

Typically in YOLOv8, the backbone is the initial part of the model up to and including the Darknet/CSPDarknet component. Following this, you find the neck which includes the PANet and FPN. 

For a specific example, let's say your model is `model`. You would use `model.model[0]` to access the backbone parts, and `model.model[1]` onwards to access the neck parts.

Keep in mind property names could vary depending on the version and specific model architecture, so make sure to familiarise yourself with the model structure either by examining the source code or by exploring the model interactively in your dev environment.

Hope this helps to guide you in the right direction! Happy coding.

**Comment by zhaowenZhou** [comment]
> @zhaowenZhou hello and thanks for your enthusiasm towards YOLOv8! It's great to see your interest in working with the backbone and neck components of the model.
> 
> To start, the `Model` class in YOLOv8 is structured in a way that each component of the model, including the backbone and neck, is presented as separate modules. This can be accessed using the `.model` attribute.
> 
> The `model.model` attribute returns an `nn.Sequential` object that encompasses all the layers including the backbone and neck. The `model.model` is essentially a list, so you can access the backbone and the neck by indexing into it.
> 
> Typically in YOLOv8, the backbone is the initial part of the model up to and including the Darknet/CSPDarknet component. Following this, you find the neck which includes the PANet and FPN.
> 
> For a specific example, let's say your model is `model`. You would use `model.model[0]` to access the backbone parts, and `model.model[1]` onwards to access the neck parts.
> 
> Keep in mind property names could vary depending on the version and specific model architecture, so make sure to familiarise yourself with the model structure either by examining the source code or by exploring the model interactively in your dev environment.
> 
> Hope this helps to guide you in the right direction! Happy coding.

Thank you for your kindly reply, this answer has given me lots of hints. 
First I did what you said then it gave me error
`from ultralytics import YOLO
from ultralytics.models.yolo.model import DetectionModel
from ultralytics.engine.model import Model

model = YOLO('./yolov8/weights/best.pt')
print(model.model[0])`
with error message TypeError: 'DetectionModel' object is not subscriptable
However, I still manage to get access to backbone and neck of the model by
`model = YOLO('./best.pt')
start_idx = 0
end_idx = 22
bb_neck_layers = model.model._modules['model'][start_idx:end_idx]
image_branch = nn.Sequential(*bb_neck_layers)
image_branch.cuda()
image_branch.load_state_dict(model.state_dict(), strict=False)`
Then I want to know the shape of output value so I create a fake input data as follow
`fake_input = torch.zeros((6, 3, 256, 256)).float().to('cuda')
with torch.no_grad():
    feats = image_branch(fake_input)
    pprint.pprint(feats)`
This gives me error message
Traceback (most recent call last):
  File "image_branch/eval.py", line 17, in <module>
    feats = image_branch(fake_input)
  File "/home/zhouzhaowen/miniconda3/envs/ct_mm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhouzhaowen/miniconda3/envs/ct_mm/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/zhouzhaowen/miniconda3/envs/ct_mm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhouzhaowen/miniconda3/envs/ct_mm/lib/python3.8/site-packages/ultralytics/nn/modules/conv.py", line 315, in forward
    return torch.cat(x, self.d)
TypeError: cat() received an invalid combination of arguments - got (Tensor, int), but expected one of:

**Comment by HalkScout** [comment]
I got your error as well. It was due to me calling `model.model.model` and not `model.model`.

If you do:
```python
model = model.model
print(model)
```

You should see:
```
DetectionModel(
  (model): Sequential(
  ...
```

Then you can mess around with it:
```python
model.model = model.model[:22]

out = model(input)
```
