### ISSUE TITLE
Extracting the bounding boxes we get in images after prediction.

### ISSUE THREAD

**Issue by ShafiJiskani** [ultralytics/ultralytics#6157]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I want code that extracts the bounding boxes (ROI) after predicting any class in the set of images.
I have trained the Yolov8 on my custom dataset and i have successfully detected insulators in the set of images. The detected insulators come in bounding box. I want that when detecting there should also be option of extracting these bounding boxes and save in different folder. Then i will classify further for the anomaly in extracted images.

### Use case

This feature will be used to further classify the faults in the images covered in the bounding boxes.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Kayzwer** [comment]
```
result = model("path/to/img")[0]
boxes = result.boxes
```

**Comment by glenn-jocher** [comment]
@ShafiJiskani thank you for reaching out with your question! The code snippet you have provided is essentially using the trained YOLOv8 model to generate a prediction on a single image and then trying to extract the bounding box of the detected objects.

The `model('path/to/img')` is making a prediction on the image at the provided path. The `[0]` following the prediction is used to retrieve the result for the first (and in this case, only) image. Therefore, `result` would contain the detection result of the image.

Continuing, `boxes = result.boxes` would then extract the bounding boxes coordinates from the prediction result. These bounding boxes are what encapsulate the detected objects in the image.

To save the bounding box images, you would need to use the bounding box coordinates to crop the original image and then save those cropped images to your desired location. You should note that this extraction process is separate to the object detection step and the extraction process will need to be managed by you.

I hope this helps clarify your query! If you have more questions, feel free to ask. The YOLOv8 community and the Ultralytics team are here to assist you.
