### ISSUE TITLE
How to convert mask.segments to binary mask?

### ISSUE THREAD

**Issue by ykzzyk** [ultralytics/ultralytics#616]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to convert mask.segments to binary mask?

**Comment by medphisiker** [comment]
Hi, @ykzzyk.

As I understand when we make prediction by YOLOv8 we get `results` [link to dics](https://docs.ultralytics.com/python/).

```
# results would be a list of Results object including all the predictions by default
# but be careful as it could occupy a lot memory when there're many images, 
# especially the task is segmentation.
# 1. return as a list
results = model.predict(source="folder")

# results would be a generator which is more friendly to memory by setting stream=True
# 2. return as a generator
results = model.predict(source=0, stream=True)

for result in results:
    # detection
    result.boxes.xyxy   # box with xyxy format, (N, 4)
    result.boxes.xywh   # box with xywh format, (N, 4)
    result.boxes.xyxyn  # box with xyxy format but normalized, (N, 4)
    result.boxes.xywhn  # box with xywh format but normalized, (N, 4)
    result.boxes.conf   # confidence score, (N, 1)
    result.boxes.cls    # cls, (N, 1)

    # segmentation
    **result.masks.masks**     # masks, (N, H, W)
    **result.masks.segments**  # bounding coordinates of masks, List[segment] * N

    # classification
    result.probs     # cls prob, (num_class, )

# Each result is composed of torch.Tensor by default, 
# in which you can easily use following functionality:
result = result.cuda()
result = result.cpu()
result = result.to("cpu")
result = result.numpy()
```
We can get `result.masks.masks` instead `result.masks.segments`. They are binary masks.

**Comment by medphisiker** [comment]
I also write some code to get binary masks from YOLOv8 by python interface and overlay them on original image by OpenCV [link](https://github.com/ultralytics/ultralytics/issues/561#issuecomment-1403079910). But I get problem with mask upsampling.

**Comment by pderrenger** [comment]
@medphisiker thank you for your code contribution! However, regarding your original question about converting `mask.segments` to binary mask, in the context of YOLOv8, you can directly access the binary masks using `result.masks.masks` rather than `result.masks.segments`. The `result.masks.masks` attribute already contains the binary masks. Therefore, you can utilize the binary masks directly for further processing or visualization.

**Comment by glenn-jocher** [comment]
Hi @pderrenger, I appreciate your engagement with the YOLOv8 community! 👍

To address your original question, YOLOv8 provides binary masks directly via `result.masks.masks`, which you can use for your tasks without needing to convert from `mask.segments`. This should simplify your workflow and save you some steps. Keep up the great work! 😊

**Comment by HasnatHridoy** [comment]
> @medphisiker thank you for your code contribution! However, regarding your original question about converting `mask.segments` to binary mask, in the context of YOLOv8, you can directly access the binary masks using `result.masks.masks` rather than `result.masks.segments`. The `result.masks.masks` attribute already contains the binary masks. Therefore, you can utilize the binary masks directly for further processing or visualization.

Hello, using  `result.mask.mask` gives attribute error.
