### ISSUE TITLE
onnx to engine with int8 failed

### ISSUE THREAD

**Issue by 7788zun** [ultralytics/ultralytics#6167]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to transform an onnx model to engine with int8, but when i use the engine model to predict a video, the error happened, please help me

(base) root@autodl-container-408811a93c-192be558:~/autodl-tmp/testlzy/test_on_class# python demo.py
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', or 'pose'.
Loading /root/autodl-tmp/testlzy/test_on_class/best.engine for TensorRT inference...
[11/07/2023-10:18:10] [TRT] [I] [MemUsageChange] Init CUDA: CPU +328, GPU +0, now: CPU 771, GPU 437 (MiB)
Traceback (most recent call last):
File "demo.py", line 18, in
results = model(frame)
File "/root/miniconda3/lib/python3.8/site-packages/ultralytics/engine/model.py", line 95, in call
return self.predict(source, stream, **kwargs)
File "/root/miniconda3/lib/python3.8/site-packages/ultralytics/engine/model.py", line 228, in predict
self.predictor.setup_model(model=self.model, verbose=is_cli)
File "/root/miniconda3/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 305, in setup_model
self.model = AutoBackend(model or self.args.model,
File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "/root/miniconda3/lib/python3.8/site-packages/ultralytics/nn/autobackend.py", line 174, in init
metadata = json.loads(f.read(meta_len).decode('utf-8')) # read metadata
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 4: invalid continuation byte

**Comment by glenn-jocher** [comment]
@7788zun hello,

Thank you for bringing up this issue with int8 conversion for ONNX to TensorRT engine models. The error message indicates that there might be an issue related to the decoding of metadata in the conversion or inference process.

The warning about automatically guessing the model task suggests that the task was not explicitly specified. Make sure when you run your script, you define the task argument corresponding to the model you are using (`'task=detect'`, `'segment'`, `'classify'`, or `'pose'` if using non-detection models). This ensures the correct configuration is applied for inference.

Concerning the `UnicodeDecodeError`, it seems there is an issue with metadata that cannot be read as UTF-8 encoded text. This problem could occur if there was data corruption or an unexpected format of the metadata within your model file. Verify that your model file was not corrupted during the conversion process and that it is in the correct format expected by the predictor system.

Please review your conversion process and ensure that all steps are correctly followed, particularly those related to the TensorRT engine build and metadata handling. You may need to reconvert your ONNX model to the TensorRT engine, making sure to specify the correct task and check the integrity of the model and metadata files.

If the issue persists, providing precise details about the steps you took during the conversion process and any additional error messages could help further diagnose the problem.

Best regards,
Glenn Jocher

**Comment by 7788zun** [comment]
> @7788zun hello,
> 
> Thank you for bringing up this issue with int8 conversion for ONNX to TensorRT engine models. The error message indicates that there might be an issue related to the decoding of metadata in the conversion or inference process.
> 
> The warning about automatically guessing the model task suggests that the task was not explicitly specified. Make sure when you run your script, you define the task argument corresponding to the model you are using (`'task=detect'`, `'segment'`, `'classify'`, or `'pose'` if using non-detection models). This ensures the correct configuration is applied for inference.
> 
> Concerning the `UnicodeDecodeError`, it seems there is an issue with metadata that cannot be read as UTF-8 encoded text. This problem could occur if there was data corruption or an unexpected format of the `metadata` within your model file. Verify that your model file was not corrupted during the conversion process and that it is in the correct format expected by the predictor system.
> 
> Please review your conversion process and ensure that all steps are correctly followed, particularly those related to the TensorRT engine build and metadata handling. You may need to reconvert your ONNX model to the TensorRT engine, making sure to specify the correct task and check the integrity of the model and metadata files.
> 
> If the issue persists, providing precise details about the steps you took during the conversion process and any additional error messages could help further diagnose the problem.
> 
> Best regards, Glenn Jocher

thank you for reply
and I would like to ask ,how can I verify the things you have mentioned before. Here is my code

main.py
`import tensorrt as trt
import os
from calibrator import Calibrator

LOGGER = trt.Logger(trt.Logger.VERBOSE)

def buildEngine(onnx_file, engine_file, quantification, batch_size, FP16_mode, INT8_mode,
                img_height, img_wdith, calibration_images, calibration_cache):
    builder = trt.Builder(LOGGER)
    network = builder.create_network(1<<int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
    parser = trt.OnnxParser(network, LOGGER)
    config = builder.create_builder_config()
    parser.parse_from_file(onnx_file)

    config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 16*(1<<30))

    if FP16_mode == True:
        config.set_flag(trt.BuilderFlag.FP16)
    elif INT8_mode == True:
        config.set_flag(trt.BuilderFlag.INT8)
        config.int8_calibrator = Calibrator(quantification, batch_size, img_height, img_wdith, calibration_images, calibration_cache)
    engine = builder.build_serialized_network(network, config)
    if engine is None:
        print("EXPORT ENGINE FAILED!")
        # exit(0)

    with open(engine_file, "wb") as f:
        f.write(engine)


def main():
    quantification = 1  # 量化次数
    batch_size = 1
    img_height = 1920
    img_wdith = 1088
    calibration_images = "/root/autodl-tmp/testlzy/test_on_class/val/images"
    onnx_file = "/root/autodl-tmp/testlzy/test_on_class/best.onnx"
    engine_file = "/root/autodl-tmp/testlzy/test_on_class/best.engine"
    calibration_cache = "/root/autodl-tmp/testlzy/test_on_class/calibration.cache"

    '''
    模型使用单精度量化，设置 FP16_mode = False & INT8_mode = False  (FP32)
    模型使用半精度量化，设置 FP16_mode = True  & INT8_mode = False  (FP16)
    模型使用 Int8量化,设置 FP16_mode = False & INT8_mode = True   (INT8)
    '''
    FP16_mode = False
    INT8_mode = True

    if not os.path.exists(onnx_file):
        print("LOAD ONNX FILE FAILED: ", onnx_file)

    print('Load ONNX file from:%s \nStart export, Please wait a moment...'%(onnx_file))
    buildEngine(onnx_file, engine_file, quantification, batch_size, FP16_mode, INT8_mode,
                img_height, img_wdith, calibration_images, calibration_cache)
    print('Export ENGINE success, Save as: ', engine_file)


if __name__ == '__main__':
    main()`



calibrator.py

`import os
import tensorrt as trt
import pycuda.driver as cuda
import pycuda.autoinit
import logging
import numpy as np
import cv2

class Calibrator(trt.IInt8EntropyCalibrator2):
    def __init__(self, quantification=1, batch_size=1, height=640, width=640, calibration_images="", cache_file=""):
        trt.IInt8EntropyCalibrator2.__init__(self)
        self.index = 0
        self.length = quantification
        self.batch_size = batch_size
        self.cache_file = cache_file
        self.height = height
        self.width = width
        self.img_list = [calibration_images + '/' + l for l in os.listdir(calibration_images)]
        self.calibration_data = np.zeros((self.batch_size, 3, self.height, self.width), dtype=np.float32)
        self.d_input = cuda.mem_alloc(self.calibration_data.nbytes)

    def next_batch(self):
        if self.index < self.length:
            for i in range(self.batch_size):
                img = cv2.imread(self.img_list[i + self.index*self.batch_size])
                img = self.preprocess(img)
                self.calibration_data[i] = img
            self.index += 1
            return np.ascontiguousarray(self.calibration_data, dtype=np.float32)
        else:
            return np.array([])

    def __len__(self):
        return self.length

    def get_batch_size(self):
        return self.batch_size

    def get_batch(self, name):
        batch = self.next_batch()
        if not batch.size:
            return None
        cuda.memcpy_htod(self.d_input, batch)
        return [int(self.d_input)]

    def read_calibration_cache(self):
        # If there is a cache, use it instead of calibrating again. Otherwise, implicitly return None.
        if os.path.exists(self.cache_file):
            with open(self.cache_file, "rb") as f:
                return f.read()

    def write_calibration_cache(self, cache):
        with open(self.cache_file, "wb") as f:
            f.write(cache)

    def preprocess(self, img):
        h, w, c = img.shape
        image = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        r_w = self.width / w
        r_h = self.height / h
        if r_h > r_w:
            tw = self.width
            th = int(r_w * h)
            tx1 = tx2 = 0
            ty1 = int((self.height - th) / 2)
            ty2 = self.height - th - ty1
        else:
            tw = int(r_h * w)
            th = self.height
            tx1 = int((self.width - tw) / 2)
            tx2 = self.width - tw - tx1
            ty1 = ty2 = 0
        image = cv2.resize(image, (tw, th))
        image = cv2.copyMakeBorder(image, ty1, ty2, tx1, tx2, cv2.BORDER_CONSTANT, (128, 128, 128))
        image = image.astype(np.float32)
        image /= 255.0
        image = np.transpose(image, [2, 0, 1])
        return image`

**Comment by glenn-jocher** [comment]
Hello @7788zun,

Thank you for your follow-up and for sharing your code snippets. To verify the model and calibrator details you mentioned, you may consider the following steps:

1. Ensure the ONNX model has been successfully exported from the training framework and contains the necessary metadata. This is crucial for the TensorRT engine to understand the model structure and any preprocessing requirements.

2. Before converting the ONNX model to a TensorRT engine, test the ONNX model separately to validate that it is functioning as expected. This will help to isolate the issue to either the ONNX model or the conversion process to TensorRT.

3. Review the directory paths and file names in your script to ensure they are correct and that the relevant files are accessible. Given that your script reads and writes to various directories, confirm these paths are valid and there are no permission issues.

4. The quality and diversity of images used for calibration can significantly impact INT8 quantization. Make sure your calibration dataset is representative of the data the model will encounter in the real world.

5. After running your calibration, inspect the produced cache file. This file should be non-empty and reflect the calibration data. If no cache file is generated or if it is empty, there may be an issue with the calibration process.

6. Watch for any additional output messages or logs generated during the conversion process—these may give more insights into where and why the process is failing.

If after these checks you are still encountering issues, you might want to reduce complexity by simplifying the process. For instance, try converting the model without INT8 quantization first (i.e., use FP32 or FP16 mode) to see if the problem is specific to the INT8 quantization process.

Lastly, if the problem persists, gather the error messages and details about your environment (e.g., TensorRT version, platform) and share these with the community. It helps others reproduce the issue and assist you more effectively.

We appreciate your efforts and look forward to assisting you further.

Best regards.
