### ISSUE TITLE
Error when using Pythonnet to invoke YOLOv8 for inference on CPU in a C# client

### ISSUE THREAD

**Issue by MrXin95** [ultralytics/ultralytics#6176]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

The issue arises from invoking get_cpu_info() in [cpuinfo.py](http://cpuinfo.py/), which keeps generating a new process. I attempted to modify get_cpu_info_json() to retrieve CPU information in the new process, but it still doesn't work. This problem only occurs when using Pythonnet to invoke YOLOv8 for CPU inference, as it runs without issue in a pure Python environment.
![image](https://github.com/ultralytics/ultralytics/assets/43596264/bd203258-f4c9-4bd6-970b-7fb71552500c)
![image](https://github.com/ultralytics/ultralytics/assets/43596264/c3da8a20-39f1-47d9-abf9-4722baa0df62)

### Environment

Ultralytics YOLOv8.0.201  
Python-3.8.10 torch-1.9.1 
CPU: AMD Ryzen 7 5800H with Radeon Graphics
System: Windows 11
C# pythonnet package: Python.Runtime 2.5.2.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MrXin95** [comment]
Thank you very much. I disabled the get_cpu_info() function in torch_utils.py, and now everything is working fine!

**Comment by glenn-jocher** [comment]
@MrXin95 hi there,

I'm glad to hear that you managed to resolve the issue by disabling the `get_cpu_info()` function in `torch_utils.py`. It's always satisfying to find a solution that gets things up and running. 

Just as a note for the future, selectively disabling certain functions is a useful strategy when dealing with cross-platform or cross-language integration issues like the one you've encountered. However, always ensure that any changes you make do not disrupt the functionality you need from YOLOv8.

While modifications to internal functions can be a quick fix, keep an eye out for updates to YOLOv8 that might affect your customizations. It’s a good practice to document any changes you made for easier troubleshooting or updates in the future.

If you encounter any further issues or if you have questions about YOLOv8, please don't hesitate to reach out.

Warm regards and happy coding! 

The Ultralytics Team

**Comment by HouseWei** [comment]
Thank you, I got it

**Comment by glenn-jocher** [comment]
@HouseWei you're welcome! I'm glad to hear that the solution worked for you. If you encounter any more issues or have further questions, feel free to reach out. For future reference, if you run into any other challenges, providing a minimal reproducible example can greatly help in diagnosing and resolving issues more efficiently. You can find more details on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Keep up the great work, and happy coding! 😊
