### ISSUE TITLE
How to pass the result of model.predict() to a variable?

### ISSUE THREAD

**Issue by FireCat999** [ultralytics/ultralytics#6178]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I execute the following code:

![image](https://github.com/ultralytics/ultralytics/assets/100002098/951e2fa9-ea31-4008-a4bb-63660087daf7)

I get the following information in the terminal:

`image 1/1 /home/zxcqwe123/Desktop/small_image_9.jpg: 640x640 2 Plants, 1 Stairs, 1 Window, 585.7ms`
`Speed: 1.3ms preprocess, 585.7ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 640)`

I need to pass the results of the predictions, namely `Plants, Stairs, Window` to a variable, say `answer` for further work.
How can I do this?

**Comment by urorontea** [comment]
I have a similar question.

I execute this cord.
<img width="205" alt="image" src="https://github.com/ultralytics/ultralytics/assets/99313754/7a2191a0-9c1d-41e2-8505-af4371d98dad">

When i print results, I get the following information in the terminal.
<img width="430" alt="image" src="https://github.com/ultralytics/ultralytics/assets/99313754/1442e1bc-efdc-48b5-8f18-67b005c6dfbc">

I don't need this results information.
The info I need is this.
<img width="487" alt="image" src="https://github.com/ultralytics/ultralytics/assets/99313754/f507016c-7d94-4b7c-bd57-c19d2a3d02ff">

I want to output this for variable.
How can I do?

**Comment by glenn-jocher** [comment]
@urorontea hello there! When you perform detection and want to access the prediction details such as class IDs, confidence scores, and bounding box coordinates without terminal output (like the one shown in your screenshot), you would typically work with the `results` object's attributes directly.

For example, after performing the prediction:

```python
results = model.predict(image_path)
```

The `results` object contains the predictions in a structured format. You can access the bounding boxes, class IDs, and confidence scores with:

```python
# Extract bounding box coordinates, labels and confidence scores
boxes = results.xyxy[0]  # xyxy is a tensor of shape (n, 6) with [x_min, y_min, x_max, y_max, confidence, class]
```

The `xyxy[0]` tensor here will have all the information you need. Each row of the tensor corresponds to a detected object and contains the bounding box coordinates, the confidence score, and the class ID, which you can extract and handle as per your application's logic.

You can then loop over this tensor and collect the required information for each detected object:

```python
# Example to access the information you need
for box in boxes:
    x_min, y_min, x_max, y_max, confidence, class_id = box
    label = results.names[int(class_id)]  # Get the class label string
    # Here you can create your custom format or storage
    detection_result = {
        "label": label,
        "confidence": confidence,
        "x_min": x_min,
        "y_min": y_min,
        "x_max": x_max,
        "y_max": y_max,
    }
    # Now 'detection_result' holds the data you need and can
    # be used further as you need, such as appending to a list
```

By following the example above, you should be able to extract the detection results and store them in a variable for further processing without printing the default terminal output. Let me know if you need any more help! 😊
