### ISSUE TITLE
Validate multiple models and save the results in CSV 

### ISSUE THREAD

**Issue by DP1701** [ultralytics/ultralytics#6179]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

 I would like to save the results in a CSV file after validating several models in Python. To get the metrics is no problem but how do I get the information about how many images and instances (for each class) were used in the validation? This is displayed in the console (see image) but I would like to query the values myself in Python. 

![Bildschirmfoto 2023-11-07 um 11 38 11](https://github.com/ultralytics/ultralytics/assets/68444979/264062aa-913f-4e5b-92df-5c5eefcf21a5)

**Comment by glenn-jocher** [comment]
@DP1701 hello,

Thank you for reaching out with your question regarding how to obtain the details of images and instances used in validation for saving to a CSV file.

After you perform validation with multiple models, the results are summarized and printed to the console, which includes the information on the number of images and instances for each class.

To programmatically access this information inside your Python script, you can capture the output that is usually printed to the console. The validation procedure returns a results dictionary containing all the relevant metrics and statistics about the validation run. This includes the number of images and instances per class, as reported in the console output.

You will find this information in the returned dictionary under specific keys (for instance, `results['counts']` may contain the number of instances per class), which you can then loop through to extract the necessary details and write to a CSV file using Python's built-in `csv` module or `pandas` library.

Please refer to the validation function documentation and return values for the exact structure of the results dictionary, as it contains a comprehensive overview of all the data you can use to populate your CSV file.

I hope this guides you in the right direction. If you have further questions or require more assistance, please feel free to ask.

Best regards,
Glenn Jocher

**Comment by DP1701** [comment]
@glenn-jocher Hello, 

Sorry, maybe I'm just getting it wrong, but when I write results['counts'] I get an error message when I run it. 

```
from ultralytics import YOLO

model = YOLO('best.pt') 
results = model.val(data='data.yaml', split='val')
print(results['counts'])
```

Error
```
    print(results['counts'])
TypeError: 'SegmentMetrics' object is not subscriptable
```

**Comment by DP1701** [comment]
@ Maybe you could show me the line in the code where this information is called, which is output formatted on the console? In any case, I can't find the information about the number of images and instances during validation in the dictionary.

**Comment by glenn-jocher** [comment]
@DP1701 hello there,

Thank you for reaching out and sharing the issue you're encountering.

It seems there's been a bit of a misunderstanding regarding the structure of the results object returned by the `model.val` function in YOLOv8. The error you're seeing indicates that the object returned doesn't support direct subscripting like a dictionary does, which would explain why attempting to access `results['counts']` is not successful.

The results from YOLOv8 validation runs are encapsulated in class instances that organize metrics and other relevant details in a structured format. To obtain the number of images and instances per class, there are specific methods and attributes provided within this class. 

Unfortunately, without providing code I cannot point to the exact line or method you would need to call, but I recommend looking into the documentation string (docstring) of the `SegmentMetrics` class or where the validation results are printed to the console within the source code of YOLOv8 for clues on how this information is retrieved internally.

Typically, the procedure for accessing such details will involve invoking a method or accessing an attribute of the results object. The class attributes should store all the necessary information about metrics and counts from the validation, but accessing them will require understanding of the methods provided by the `SegmentMetrics` class or its parent classes.

Within the source code, find where the `val` function is defined and track how the results are compiled and printed to the console. Wherever the console output is formatted with information about the number of images and instances, you'll find the code responsible for gathering these statistics, which you can then use as a guide to retrieve the same data within your Python environment.

I suggest you look into these class definitions or relevant sections of the documentation for further information on how to programmatically access the information you're interested in.

I hope this helps you move in the right direction, and please let us know if you have any further questions.

Warm regards,
Glenn Jocher

**Comment by DP1701** [comment]
@glenn-jocher 

Thank you for the detailed explanation!

If anyone should have a similar problem. Here is my solution:

```
from ultralytics.models.yolo.segment import SegmentationValidator

# Create a dictionary which contains the data for the validation   
arguments = dict(model='weights.pt', data='data.yaml', split='val')

# Validation is carried out with the validator
validator = SegmentationValidator(args=arguments)
validator()

for i in validator.metrics.ap_class_index:
    
    # Number of images used for validation
    img_number = validator.seen

    # Number of instances
    instance_number = validator.nt_per_class[i]
    
    # Results for the first class
    class_result = validator.metrics.class_result(i)
    
    print(str(img_number) + " " + str(instance_number) + " " + str(class_result))
```

**Comment by glenn-jocher** [comment]
@DP1701,

Thank you for sharing your solution with the community! It's delightful to see users engaging with the tools we provide, and your approach to access the validation metrics will surely be useful to others with similar queries.

Your snippet shows a good understanding of interacting with the classes and methods within the YOLOv8 architecture to retrieve specific information, such as the number of images used for validation and the number of instances per class. This will indeed help others in achieving similar tasks in their projects.

If you have any other questions or need further assistance with YOLOv8, feel free to ask. Keep up the great work, and happy coding!

Warm
