### ISSUE TITLE
Add labels to masks after predictions

### ISSUE THREAD

**Issue by Miroun** [ultralytics/ultralytics#6181]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hello,

While using this piece of code:
model = YOLO('yolov8l-seg.pt')
results = model.predict(params)
for element in results : 
        masks = element.masks.data.cpu().numpy()

I would like to know in advance which mask corresponds to which detected labels.
Currently we just have multiple masks into one table.

In order to be clearer, I wanted to segment (as a part of a workflow) body part. So I decided to use the coco pre-trained weights. Nevertheless, I just want to segment human an not other elements (such as furniture or animal).

I do not know if I am doing with the good manner. I know for sure that I would be able to do it if it was possible to know which label correspond to the predicted mask.

Kind regards,

Miroun

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Miroun hello Miroun,

Thank you for reaching out with your request regarding the handling of masks after predictions using Ultralytics YOLOv8.

To associate predicted masks with their corresponding labels, you can utilize the `results` object which contains both the `masks` and `pred` attributes. The `pred` attribute itself holds the predictions where each prediction includes the bounding box coordinates as well as the class label and confidence score.

When you iterate over `results`, ensure to also index into `results.pred` to retrieve the class labels that align with the masks. Each mask in the `masks` tensor is associated with a detection, and these detections are in the same order within the `pred` tensor. You can obtain the label for each mask by looking at the class indices provided in the respective entries of the `pred` tensor.

By following this approach, you will be able to filter the masks that correspond to the class labels of interest—in your case, human class labels, potentially filtering out other classes such as animals or furniture.

Remember to apply the proper indexing and alignment of masks with the detected class labels, which should be quite straightforward when using the predictions object. You can map the class indices to their string names using the class names list that the YOLO model provides if needed.

I hope this explanation helps you progress with your segmentation workflow. If you run into any further issues or have more questions, feel free to reach out.

Kind regards,
Glenn Jocher
On behalf of the Ultralytics team

**Comment by Miroun** [comment]
@glenn-jocher Are you sure ?

It didn't work and seeing the Traceback, it is not an attribute :
AttributeError: 'Results' object has no attribute 'pred'. See valid attributes below.

    A class for storing and manipulating inference results.

    Args:
        orig_img (numpy.ndarray): The original image as a numpy array.
        path (str): The path to the image file.
        names (dict): A dictionary of class names.
        boxes (torch.tensor, optional): A 2D tensor of bounding box coordinates for each detection.
        probs (torch.tensor, optional): A 1D tensor of probabilities of each class for classification task.
        keypoints (List[List[float]], optional): A list of detected keypoints for each object.

    Attributes:
        orig_img (numpy.ndarray): The original image as a numpy array.
        orig_shape (tuple): The original image shape in (height, width) format.
        boxes (Boxes, optional): A Boxes object containing the detection bounding boxes.
        masks (Masks, optional): A Masks object containing the detection masks.
        probs (Probs, optional): A Probs object containing probabilities of each class for classification task.
        keypoints (Keypoints, optional): A Keypoints object containing detected keypoints for each object.
        speed (dict): A dictionary of preprocess, inference, and postprocess speeds in milliseconds per image.
        names (dict): A dictionary of class names.
        path (str): The path to the image file.
        _keys (tuple): A tuple of attribute names for non-empty attributes.

**Comment by Miroun** [comment]
Do I have a wrong version ?

**Comment by glenn-jocher** [comment]
@Miroun apologies for the confusion earlier. It seems there's been a misunderstanding regarding the structure of the `Results` object after running predictions with YOLOv8. Thank you for providing the `Results` object attributes.

Based on the attributes you've listed, it appears you are using a correct version that has indeed gone through some updates, thereby changing the structure of the `Results` object from the one I initially described.

To access the class labels associated with each predicted mask, you should look into the `boxes` attribute, which contains the `Boxes` object. Inside the `Boxes` object, there are bounding box coordinates and, importantly, class indices corresponding to detections. To map the masks to their corresponding labels, follow these steps:

1. Iterate over the `boxes` attribute to get information about each detection, including class indices.
2. Simultaneously iterate over the `masks` attribute to access the masks.
3. The class indices from the `boxes` object can be used to understand which mask belongs to which class.

This way, you can filter for detections of interest, such as humans, and use only the masks that correspond to this class.

If you find that in practice it still doesn't align with what you're observing, it might be beneficial to ensure you are using the latest stable version of the YOLOv8 repository, as there could be updates or changes made that alter how the API works. If the issue persists, do not hesitate to reach out for further clarification. We aim for your experience with YOLOv8 to be as seamless as possible.

**Comment by sandorkonya** [comment]
If someone finds this thread... take this:

https://github.com/orgs/ultralytics/discussions/2547#discussioncomment-8387690

**Comment by glenn-jocher** [comment]
Hello @sandorkonya,

Thank you for sharing the link to the discussion! For anyone else encountering similar issues, here's a concise approach to associating masks with their corresponding labels in YOLOv8:

1. **Ensure Latest Versions**: First, make sure you are using the latest versions of `torch` and `ultralytics`. You can update them using:
    ```bash
    pip install --upgrade torch ultralytics
    ```

2. **Accessing Masks and Labels**: When you run predictions, the `Results` object contains both `masks` and `boxes`. Each mask corresponds to a detection, and you can access the class labels from the `boxes` attribute.

Here’s a streamlined example to illustrate this:

```python
from ultralytics import YOLO

# Load the model
model = YOLO('yolov8l-seg.pt')

# Run predictions
results = model.predict('path/to/your/image.jpg')

# Process results
for result in results:
    masks = result.masks.data.cpu().numpy()
    boxes = result.boxes
    class_indices = boxes.cls.cpu().numpy()  # Class indices for each detection

    # Map masks to their corresponding class labels
    for mask, class_idx in zip(masks, class_indices):
        class_name = result.names[int(class_idx)]
        print(f"Mask for class: {class_name}")
        # Further processing with mask and class_name
```

This code snippet will help you identify which mask corresponds to which class label, allowing you to filter out unwanted classes like furniture or animals.

If you encounter any issues or have further questions, please ensure you provide a minimum reproducible example as outlined in our [documentation](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us investigate and provide a solution more effectively.

Happy coding! 😊
