### ISSUE TITLE
Using only one cpu core to load data

### ISSUE THREAD

**Issue by tarv33** [ultralytics/ultralytics#6194]
### Search before asking

- [ ] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

training process is very slow and it seems using only one cpu core.
top info
![image](https://github.com/ultralytics/ultralytics/assets/31963320/c2c802dd-6035-4d59-b7fd-b33b345c02e6)
training script as follow
``` python 
from ultralytics import YOLO

model = YOLO("./pretrain/yolov8n.pt")

model.train(
    data="./data.yaml",
    epochs=150,
    name="mec",
    workers=4,
    batch=64,
    device=1,
    cache=True,
)
```

**Comment by RizwanMunawar** [comment]
@tarv33 Thank you for sharing this information! From the command you've provided, it appears that you're utilizing GPU resources for model training, while the CPU cores are primarily responsible for data loading. I recommend examining the GPU's memory and usage for further insights.

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by tarv33** [comment]
@RizwanMunawar i got 24 core cpu, but it only use one, no matter how many workers i set; the whole training process gets slow because of dataloading problem, while gpu is 0 most of time. Is that any solution?
![image](https://github.com/ultralytics/ultralytics/assets/31963320/8eceb157-0d5d-44bb-b3d9-0f74d53d73e0)
