### ISSUE TITLE
Custom yolov8 integration with SAHI

### ISSUE THREAD

**Issue by akashsateesha** [ultralytics/ultralytics#6195]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained a model on visdrone data using pre-trained weights for yolov8 . It is giving a map 0f around 30 . is it a good score ? . Also my next plan of action is to integrate the model I've built with SAHI because most of the objects in visdrone dataset are small . 
how should I go about it ? Also can I implement tracking algorithms for the above integration with SAHI ?

Thank you !!😊

**Comment by RizwanMunawar** [comment]
@akashsateesha, indeed, the map is acceptable, and there's room for improvement with more training epochs.

We've already provided the code for integrating YOLOv8 and SAHI, which you can explore by visiting this link: [YOLOv8-SAHI Integration Code](https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-SAHI-Inference-Video)

It's worth noting that you can implement object tracking with YOLOv8+SAHI, but currently, you'll need to handle the integration yourself, as Object Tracking support hasn't been included in the SAHI inference example.

I hope this information is helpful. Feel free to reach out if you have any more questions.
Thanks!
