### ISSUE TITLE
Yolov8n in Unity?

### ISSUE THREAD

**Issue by dragan07-07** [ultralytics/ultralytics#620]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Are anyone try to implement Yolov8n model into Unity?

**Comment by pderrenger** [comment]
@dragan07-07 hey there! 😊 YOLOv8 is currently not directly integrated with Unity. However, you can export a trained YOLOv8 model to a deployment-ready format using the Export mode and then integrate it with Unity for object detection. If you need any further assistance with this, feel free to ask!

**Comment by Zafoue** [comment]
> @dragan07-07 hey there! 😊 YOLOv8 is currently not directly integrated with Unity. However, you can export a trained YOLOv8 model to a deployment-ready format using the Export mode and then integrate it with Unity for object detection. If you need any further assistance with this, feel free to ask!

i try to use Unity Sentis to make real Time Inferance but i'm new to AI any help !

**Comment by wojciechp6** [comment]
Hello, you could try my solution: [https://github.com/wojciechp6/YOLOv8Unity](https://github.com/wojciechp6/YOLOv8Unity). It supports both detection and segmentation. 
Good luck!

**Comment by pderrenger** [comment]
@wojciechp6 currently, there isn't a direct implementation of YOLOv8 for Unity available in our repository. However, you can export the YOLOv8 model to ONNX format using the `export` mode and then use the ONNX model within Unity through the [ONNX Runtime](https://github.com/microsoft/onnxruntime), which is compatible with C# and can be integrated into Unity projects.

Here's a brief example of how to export a YOLOv8 model to ONNX:

```python
from ultralytics import YOLO

# Load a pretrained YOLOv8 model
model = YOLO('yolov8n.pt')

# Export the model to ONNX format
model.export(format='onnx')
```

After exporting the model, you can use the ONNX Runtime in Unity to run the model for inference. Keep in mind that you might need to handle pre-processing and post-processing of the data within Unity to match the requirements of the YOLOv8 model.

If you have further questions or need assistance with the integration, feel free to reach out to the community in our [discussions](https://github.com/ultralytics/ultralytics/discussions). Good luck with your project! 🚀

**Comment by AntoineChauviere** [comment]
How can I integrate your YOLOv8 ONNX model into OpenCV, @dragan07-07 ? 
Do you have any code for pre-processing, inference, and post-processing? Thanks in advance

**Comment by yujuJeonDev** [comment]
> Hello, you could try my solution: https://github.com/wojciechp6/YOLOv8Unity. It supports both detection and segmentation. Good luck!

Thank you so much it works perfectly. Just have a quick question. Are you planning to implement Instance segmentation with Sentis as well?

**Comment by glenn-jocher** [comment]
Hey @yujuJeonDev, I'm thrilled to hear that the solution is working out for you! 🎉 As for instance segmentation with Sentis, it's not on the roadmap just yet, but it's a great suggestion. Keep an eye on the repo for any future updates! If you have any more questions or ideas, feel free to share them. Happy coding!

**Comment by cmilanes93** [comment]
> [yujuJeonDev](/yujuJeonDev)

Hi, have you try it on mobile, i cant achive good FPS

**Comment by cmilanes93** [comment]
> Thanks, I managed to convert to ONNX, and insert it via opencv. @pderrenger


Hi, have you try it on mobile, i cant achive good FPS

**Comment by pderrenger** [comment]
Hi @cmilanes93, achieving good FPS on mobile can be challenging due to hardware limitations. Ensure you're using the latest versions of ONNX Runtime and OpenCV optimized for mobile. Additionally, consider using quantization (e.g., INT8) to speed up inference. If the issue persists, you might need to profile your app to identify bottlenecks. Good luck!
