### ISSUE TITLE
When will YOLOv8 support tflite? 

### ISSUE THREAD

**Issue by SeongheaPark** [ultralytics/ultralytics#621]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, YOLOv8 team
Thank you for making YOLOv8

I am making an android app with YOLOv8.
And to do that, I have to convert it to tflite.
I have read on issue pages that you are working on it.
If you don't mind, I want to know when will YOLOv8 support tflite roughly.

Best regards

**Comment by MuhammadSibtain5099** [comment]
Same Question. I am waiting for it. Have you found any other solution.

**Comment by lea-marlenka** [comment]
Hi :)

This is what I did.
YOLOv8 → OpenVINO → tensorflow → tflite
https://github.com/PINTO0309/openvino2tensorflow

But this way is not stable so now I use YOLOv5.

Hope this helps.

**Comment by MuhammadSibtain5099** [comment]
Hi, Thanks for reply. I am also using yolov5 but I need to new algo

**Comment by Laughing-q** [comment]
@MuhammadSibtain5099 hi I think it's already supported. :)
```bash
yolo export model=yolov8n.pyt format=tflite
```

**Comment by thusinh1969** [comment]
Yes indeed it supports conversion to TFlite with Tensorflow 2.11 in my case... Thanks much.

**Comment by MuhammadSibtain5099** [comment]
Yes, It is working now. But issue is shape of .tflite is changed [1,  8,8400]. It is unlike to yolov5. Anyone have implemented it in android?

**Comment by pderrenger** [comment]
@MuhammadSibtain5099 if my memory serves me right, the .tflite model follows the YOLOv8 head architecture, leading to the unusual shape [1, 8, 8400]. You might need to preprocess the model output in your Android app to match the expected output format. I'm not entirely sure about Android implementation, but modifying the output shape should help in integrating the model correctly.
