### ISSUE TITLE
question about yolov8 output objectness

### ISSUE THREAD

**Issue by youngjae-avikus** [ultralytics/ultralytics#6214]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hello. It's a simple question. 
In Yolov5, `Objectness` was included in the output array, but in yolov8, there is no separate one. **Is the score and Objectness already multiplied and reflected in the output stage?**

**Comment by glenn-jocher** [comment]
@youngjae-avikus hello!

Thank you for reaching out with your question regarding the output of YOLOv8 in comparison to YOLOv5.

Indeed, YOLOv8 has undergone several refinements from its predecessors. One of these changes pertains to the output structure you mentioned. In the YOLOv8 model, what you previously recognized as 'Objectness' in YOLOv5 is now integrated into the confidence score. Essentially, this means that the score you see in the output does reflect both the objectness of the bounding box and the class confidence combined.

This change was made to streamline the output and improve the efficiency of the model's prediction stage. By multiplying the objectness and class confidence scores internally, YOLOv8 provides a single confidence score that simplifies subsequent processing.

I hope this clarifies your question. Should you have any further inquiries or require additional assistance, feel free to ask. The community and our team are always here to help!

Best regards,
Glenn Jocher

**Comment by youngjae-avikus** [comment]
It's a clear answer. Thank you

**Comment by glenn-jocher** [comment]
@youngjae-avikus you're welcome!

I'm glad to hear that my explanation helped clarify your query about the output structure of YOLOv8. If you have any more questions or need further assistance as you continue your work with the model, please don't hesitate to reach out. We highly value your engagement with the YOLO community and are here to support your efforts.

Happy developing, and best of luck with your projects!

Best,
Glenn Jocher

**Comment by dkyman** [comment]
Does yolov8's output tensor (b, 84, 8400) contain conf and objectness? If it is included, in which dimension is he located?

**Comment by glenn-jocher** [comment]
@dkyman in YOLOv8, the model output tensor structure has been designed for efficiency, and the confidence score already encapsulates the concept of objectness. This means that for each detected bounding box, the score combines the objectness (i.e., the likelihood that the bounding box contains any object) and the class confidence (i.e., probability of the object belonging to a particular class) into a single value.

For a typical YOLOv8 output tensor with the shape (b, 84, 8400) - the dimensions usually represent:

1. **b**: The batch size, indicating how many images you are processing simultaneously.
2. **84**: This dimension often includes all the bounding box attributes and class predictions. A typical structure might be:
    - 4 values for the bounding box (x, y, width, height)
    - 1 value for the combined objectness and class confidence score
    - 79 values for the class probabilities (assuming 80 classes, like in COCO dataset)
   
3. **8400**: The number of anchor boxes (bounding boxes predictions) generated by the model for an image.

In the output tensor, the specific index or location for the confidence score would be within that second dimension (84 elements). You typically have the bounding box coordinates first, followed by the combined objectness and class confidence score, and then the individual class probabilities.

If you are referring specifically to a format where objectness and class confidence seem separate, this would usually be derived post-processing. However, with changes from YOLOv5 to YOLOv8, you can expect this to be simplified into the confidence score as part of the 84-dimensional vector for each anchor box.

Keep in mind that the exact indices can vary, so the best reference would be the official documentation or the codebase itself for precise information on tensor structure. Without delving into the code, this explanation can serve as a general guide. If you require more detailed information, please visit our documentation at https://docs.ultralytics.com for specifics on YOLOv8's output format.

**Comment by lsutardja** [comment]
@YoungjaeDev @dkyman 

Reviving this for anyone who needs an answer.

If you refer to https://github.com/ultralytics/ultralytics/issues/5823#issuecomment-1963407552, you will see that in the YoloV8 detection head, the regression for objectness and therefore the objectness loss is removed. Instead we have the dfl loss which models the distance from the anchor to each side of the detection as a general probability distribution.

DFL is first defined here https://arxiv.org/pdf/2006.04388. If you take a look at Figure 3, you can see that for each side, for each detection, there will be a discrete probability distribution (in YoloV8 the default range is bound to [0, 15]) . Page 5 describes the probability distribution and how it is used to regress the expected value. 

The easiest way to get a pseudo-objectness measure is to use this probability distribution (without retraining). If you notice in the paper, inaccurate regressions are associated with flat and or long tailed probability distributions. You can take the maximum of the probability distribution and calculate its slope on either side and combine them to create some sort of measure for objectness. This means that you can determine not only the objectness but your confidence for each side of the regression separately (or average them if you don't care.

An alternative is to assume the probability function approximates a normal distribution. You can use the standard deviation (smaller std means higher objectness and a sharper peak) or p-value of the measure.

Here is the DFL loss:

https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/modules/block.py#L61

Here is some unfinished pseudo-ish code for the modifications needed.
```
x = x.view(b, 4, self.c1, a).transpose(2, 1)
v_x = x.clone()
x = x.softmax(1)
P_x = x.clone()
x = self.self.conv(x).view(b, 4, a)
mu_x = x.clone()

return x
```

Now with the cloned tensors, do the following, while broadcasting the shapes to match:


$stdev = \sqrt{ \sum \left( v \_x - mu \_x \right)^2 * P \_x}$

From there, you can get the z-score,

$z = \frac{\left(v_x - mu_x\right)}{stdev} $

and from there you can calculate the p-value

$p = 1 - {cdf}\left( z\right) * 2$

where cdf is the cumulative distribution function.

Alternatively, if you feel like spending some compute, it looks like there is a newer version of the  Generalized Focal Loss by the same author of DFL. If you note on page 4 describing the new loss, they take the top-k probabilities from the distribution and the mean of the distribution and feed it through a small MLP, which spits out an objectness scalar.

**Comment by shengyu27** [comment]
> @dkyman in YOLOv8, the model output tensor structure has been designed for efficiency, and the confidence score already encapsulates the concept of objectness. This means that for each detected bounding box, the score combines the objectness (i.e., the likelihood that the bounding box contains any object) and the class confidence (i.e., probability of the object belonging to a particular class) into a single value.
> 
> For a typical YOLOv8 output tensor with the shape (b, 84, 8400) - the dimensions usually represent:
> 
> 1. **b**: The batch size, indicating how many images you are processing simultaneously.
> 2. **84**: This dimension often includes all the bounding box attributes and class predictions. A typical structure might be:
>    
>    * 4 values for the bounding box (x, y, width, height)
>    * 1 value for the combined objectness and class confidence score
>    * 79 values for the class probabilities (assuming 80 classes, like in COCO dataset)
> 3. **8400**: The number of anchor boxes (bounding boxes predictions) generated by the model for an image.
> 
> In the output tensor, the specific index or location for the confidence score would be within that second dimension (84 elements). You typically have the bounding box coordinates first, followed by the combined objectness and class confidence score, and then the individual class probabilities.
> 
> If you are referring specifically to a format where objectness and class confidence seem separate, this would usually be derived post-processing. However, with changes from YOLOv5 to YOLOv8, you can expect this to be simplified into the confidence score as part of the 84-dimensional vector for each anchor box.
> 
> Keep in mind that the exact indices can vary, so the best reference would be the official documentation or the codebase itself for precise information on tensor structure. Without delving into the code, this explanation can serve as a general guide. If you require more detailed information, please visit our documentation at https://docs.ultralytics.com for specifics on YOLOv8's output format.

But I found that the results of the output model do not match what you said：
> 2. **84**: This dimension often includes all the bounding box attributes and class predictions. A typical structure might be:
>    
>    * 4 values for the bounding box (x, y, width, height)
>    * 80 values for the class probabilities (assuming 80 classes, like in COCO dataset)
there is no combined objectness and class confidence score. Are you sure what you said is correct?
