### ISSUE TITLE
How can I show the labeled frame using label and frame? 

### ISSUE THREAD

**Issue by ragahdtareg** [ultralytics/ultralytics#6216]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want code/tool that I can used to show the labeled frame ; 
By giving the frame **.png** (Not labeled) and labels **.txt** . 
and the output should be : a new frame.png that labeled

is there any tool i can use for this?

### Additional

Input: frame.png + label.txt
output: labeled frame .png

**Comment by RizwanMunawar** [comment]
@ragahdtareg, to my understanding, the [labelImg tool](https://github.com/HumanSignal/labelImg) can fulfill this requirement!

If you have any more questions, feel free to ask. Thanks!

**Comment by ragahdtareg** [comment]
> @ragahdtareg, to my understanding, the [labelImg tool](https://github.com/HumanSignal/labelImg) can fulfill this requirement!
> 
> If you have any more questions, feel free to ask. Thanks!

I don' want to manually annotate, and i beleive this tool for manaualy annoatte. I have the .TXT and .PNG i just want a tool to make them togther in one frame

**Comment by glenn-jocher** [comment]
Hello @ragahdtareg,

I understand that you already have your annotation files and images, and you're looking to superimpose the labels onto the images automatically.

YOLOv8, and other YOLO versions, typically produce a `.txt` file for each image with labels in YOLO format. These annotation files can be combined with the corresponding images to visualize the bounding boxes.

In the YOLOv8 repository, we have Python scripts that are used for various tasks including training, validation, and prediction, which inherently include functions to draw bounding boxes on images based on the associated label files.

To achieve the visualization of labels on your `.png` images, you would typically use the plot function provided within the repository which reads the `.txt` label files, extracts the bounding box coordinates and class labels, and then superimposes them on the corresponding images. These labeled images can then be saved as new `.png` files.

You can utilize the `Predict` mode to input your `.png` files, and the script will reference your `.txt` files for the annotations. The result will be output images with the bounding boxes and class labels drawn on the images.

Please refer to the repository's documentation on using the `Predict` mode for more detailed instructions, or you can ask further questions here, and I'd be glad to assist you. Thank you for reaching out, and I wish you success with your work using YOLOv8!
