### ISSUE TITLE
how to change the label text of bounding boxes instead of class name, can I give the class key, from the model.names

### ISSUE THREAD

**Issue by Sairahul07-25** [ultralytics/ultralytics#6217]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I custom trained my model which is performing nice, but I want to use its result for the ocr , work I want to classify the bounding boxes , so instead of the class names on the label can we get the class keys as the label text, so that it would be easier to recognize to which class the box belongs to 
and one more doubt is 
can we add the class keys to the results.boxes.xyxy list 
so that we could differentiate the boxes there as well
![cropped_box_0](https://github.com/ultralytics/ultralytics/assets/98158320/e5f27f6a-61a9-49fa-806e-e529f7d4c9a2)

### Additional

if any one know any methods how to do it
I'm in so need

**Comment by Sairahul07-25** [comment]
class_mapping = {   
    0: 'DIM',
    1: 'Datum',
    2: 'View',
    3: 'dimension',
    4: 'feature_control_frame',
    5: 'tolerance',
    6: 'tolerance_lower',
    7: 'tolerance_upper'
}

I want the label names to be given the class keys not the class names

**Comment by RizwanMunawar** [comment]
@Sairahul07-25, thank you for the comprehensive information. You can indeed display class keys using the provided code snippet below.

```python
import cv2
import sys
from ultralytics import YOLO
from ultralytics.utils.plotting import Annotator

model = YOLO("path/to/best.pt")

video_path = "path/to/video.mp4"
cap = cv2.VideoCapture(video_path)

if not cap.isOpened():
    print("Error reading video file")
    sys.exit()

while cap.isOpened():
    success, frame = cap.read()
    if success:

        results = model.track(frame, verbose=False)
        boxes = results[0].boxes.xywh.cpu()
        clss = results[0].boxes.cls.cpu().tolist()
        annotator = Annotator(frame, line_width=2, example=str(names))
        for box, cls in zip(boxes, clss):
            x, y, w, h = box
            label = int(cls)
            x1, y1, x2, y2 = x - w / 2, y - h / 2, x + w / 2, y + h / 2
            annotator.box_label([x1, y1, x2, y2], label=label, color=(0, 0, 255))
```

There isn't a direct way to add class keys in `results.boxes.xyxy` list, but it's achievable with custom code implementation! 

Feel free to reach out if you have any further questions. Thanks!

**Comment by Sairahul07-25** [comment]
@RizwanMunawar  
The Code worked
`import cv2
import sys
from ultralytics import YOLO
from ultralytics.utils.plotting import Annotator

model = YOLO("/pathto_best.pt")

image_path = "/pathtoimage"  
frame = cv2.imread(image_path)

if frame is None:
    print("Error reading image file")
    sys.exit()

results = model(frame, save=True, show=True)
boxes = results[0].boxes.xywh.cpu()
clss = results[0].boxes.cls.cpu().tolist()
annotator = Annotator(frame, line_width=2, example=str(model.names))
for box, cls in zip(boxes, clss):
    x, y, w, h = box
    label = int(cls)
    x1, y1, x2, y2 = x - w / 2, y - h / 2, x + w / 2, y + h / 2
    annotator.box_label([x1, y1, x2, y2], label=str(label), color=(0, 0, 255))

# Save the annotated image
cv2.imwrite("annotated_image.png", annotator.im)
cv2.waitKey(0)
cv2.destroyAllWindows()
`
![annotated_image](https://github.com/ultralytics/ultralytics/assets/98158320/374cd804-c295-479e-8054-d51e9169d0ab)

Thanks a lot man
I really needed that.
Have a Wonderful Day.

**Comment by glenn-jocher** [comment]
@Sairahul07-25 i'm glad to hear that the code worked out for you! It's wonderful to see the YOLOv8 model being used effectively for your OCR tasks. If you have any more queries or need further assistance as you proceed with your project, don't hesitate to reach out. The community and team here at Ultralytics are always eager to help. Enjoy using YOLOv8, and have a fantastic day too!
