### ISSUE TITLE
After training YOLOv8 the labels size is changing

### ISSUE THREAD

**Issue by ragahdtareg** [ultralytics/ultralytics#6218]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I tried to extract frames from a video using CV2 , and the labels .txt  from CVAT after annotation the video. 

My issue is the labels are not correct placing in the frame when I check the train_batch0.jpg, so I see that the size of the boxes different. 

I'm sure about the frames size is the same size when I did the annotation. 

So, what do you think is the probelm? if you need any code snippet let me know.

**Comment by glenn-jocher** [comment]
@ragahdtareg hello,

Thank you for reaching out with your issue concerning label sizes after training your YOLOv8 model.

Based on what you've described, it sounds like there may be a discrepancy between the annotation coordinates in the label files and the dimensions of the input frames during training. In YOLOv8, during training, images are often resized and augmented, which may affect the relative positioning of the bounding boxes if the original annotation coordinates aren't scaled appropriately.

A few things for you to check or consider:

1. Ensure that the label coordinates in your `.txt` files are normalized with respect to the original image dimensions - they should be in the format [class x_center y_center width height], with all values normalized between 0 and 1 relative to the image width and height.

2. Verify that during training, the image augmentation and resizing maintain the aspect ratio or else appropriately adjust the bounding box coordinates to match the new dimensions.

3. If your annotations were made on the original frame sizes, confirm that these sizes are consistent with the input resolution of the model at training time. Discrepancies here can lead to incorrect scaling of the bounding boxes.

4. Double-check the integrity of the annotation export process from CVAT to ensure no transformation on the coordinates occurred without your intention.

It is critical that the label formats are consistent with what YOLOv8 expects, and the preprocessing steps that the training data undergoes matches these label details to avoid such issues.

If you have verified all these and still encounter problems, please provide additional details on the preprocessing steps and have a look at the debug images saved during training to ensure that the augmentations applied to your dataset are as expected.

We appreciate your effort in checking past issues and discussions before posting, and hopefully, these pointers will help you diagnose the issue more precisely.

Best regards,
The Ultralytics Team
