### ISSUE TITLE
Training with non-annotated image

### ISSUE THREAD

**Issue by bakiuzun** [ultralytics/ultralytics#6235]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I checked what you gave to the v8DetectionLoss ( batch_idx, cls, bboxes)
and I was wondering if the txt file of the corresponding image do not contain any object that we want to detect what should we give to the loss as batch  ` def __call__(self, preds, batch):` signature of the method.
Should I just give an empty array for  batch_idx,cls, and bboxes  ? 

Thanks 
Baki

**Comment by glenn-jocher** [comment]
@bakiuzun hello Baki,

When dealing with images that do not contain any annotated objects, you should indeed provide empty arrays for `batch_idx`, `cls`, and `bboxes`. In YOLOv8, during training, the loss function can handle batches where some images do not have any corresponding annotations. This is a common scenario, especially in datasets with a mixture of annotated and non-annotated images.

For an image without annotations, your annotation `.txt` file corresponding to that image should be present but empty. This indicates to the model that there are no objects of interest in that particular image. The YOLOv8 training process is designed to interpret empty annotation files correctly and will treat them as images with no targets.

This approach is useful for training better detectors that can discern between scenes with and without objects of interest, aiding in reducing false positives.

If you have other questions or need further clarification, feel free to check the Ultralytics Docs or reach out again.
