### ISSUE TITLE
Segment prediciton / Mirroring bug? 

### ISSUE THREAD

**Issue by svenor31** [ultralytics/ultralytics#6238]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have only a Question, because i dont understand this.

I train my models with segment marking but everytime in detection segment marking is completly RIGHT but the class prediction completly wrong :-( . 
I have 3000 pictures for every class.  Is there maybe a mirroring bug? Because some segments looks really same when mirrored, BUT i deactivate flip etc. Or Maybe i forgot something ? :-(

**Comment by RizwanMunawar** [comment]
@svenor31, could you please provide more details? It would be helpful if you could attach sample pictures illustrating the issues. This will allow us to investigate internally and provide you with updates. Thanks!
