### ISSUE TITLE
Image classification training :WARNING no model scale passed. Assuming scale='n'.

### ISSUE THREAD

**Issue by ly1035327995** [ultralytics/ultralytics#6247]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Image classification training :WARNING no model scale passed. Assuming scale='n'.

**Comment by glenn-jocher** [comment]
Pass a model with a scale, i.e. "yolov8n" instead of "yolov8"

**Comment by PTA00** [comment]
See Reply https://github.com/ultralytics/ultralytics/issues/4084#issuecomment-1912297433 in Question 4084

**Comment by glenn-jocher** [comment]
@PTA00 the warning you're seeing indicates that a specific model scale was not provided during your training setup. In YOLOv8, model names typically end with a letter that denotes their scale, such as 'n' for nano, 's' for small, 'm' for medium, and so on.

To resolve this, ensure you specify the model scale when you set up your training. For example, use 'yolov8n' for a nano-scale model. This will give the training process the necessary information about the model architecture you intend to use.

For more details on model scales and naming conventions, please refer to our documentation. 📚
