### ISSUE TITLE
How to view live training images via tensorboard like yolov5？

### ISSUE THREAD

**Issue by ChanryX** [ultralytics/ultralytics#6248]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

A surname，I want to use tensorboard to to view live training images via tensorboard like yolov5,coud u tell me what can i do,plz

**Comment by RizwanMunawar** [comment]
@ChanryX During the training process, you can monitor training metrics by following these steps:

1. Execute the training command in the command-line interface (CLI):

```yolo detect train data=coco128.yaml model=yolov8n.pt epochs=100 imgsz=640```

2. Visualize the metrics on Tensorboard using the following CLI command:

```tensorboard --logdir ultralytics/runs```

For additional details, refer to the [Ultralytics Docs on logging using Tensorboard](https://docs.ultralytics.com/modes/train/#tensorboard).

**Comment by xylcbd** [comment]
how to activate it when the task is segment training?

**Comment by glenn-jocher** [comment]
@xylcbd for a segmentation task, if you're not seeing images on Tensorboard, please ensure that the `--img-summary` flag is set to your train command. This option enables the logging of images to Tensorboard.

Here's what you should check:

1. Make sure that the `--img-summary` flag is included when starting the training process. This will log sampled images during training which can be viewed on Tensorboard.
   
2. After starting the training with the appropriate flags, Tensorboard should automatically log the images if everything is set up correctly.

3. Run Tensorboard by pointing it to the directory where the training logs are saved. For example:

```tensorboard --logdir ultralytics/runs```

4. Open a web browser and visit the Tensorboard URL, typically `http://localhost:6006`, and navigate to the 'Images' tab to view the live training images.

If following these steps doesn't resolve your issue, you might want to verify that your environment has all the Tensorboard dependencies installed and that there are no conflicts between versions. Always check the latest documentation or release notes for any additional instructions or updates related to Tensorboard integration.

**Comment by glenn-jocher** [comment]
@Ambarish-Ombrulla yes, Tensorboard can be used locally during training. Simply start your train command with the necessary Tensorboard flags, and then run Tensorboard by pointing it to the correct log directory from the command line. Open the provided URL in a web browser to view your training metrics. 📊🚀

**Comment by GPatiA2** [comment]
How can I visualize images used for segmentation training using the Python API?

**Comment by glenn-jocher** [comment]
@GPatiA2 to view live training images via TensorBoard with YOLOv8, you can follow these steps:

1. **Enable TensorBoard Logging:**
   When you start training your YOLOv8 model, make sure to enable TensorBoard logging by setting the `--tensorboard` flag to `True`. If you're using the Python API, you can do this by adding `tensorboard=True` to your `train()` function call.

2. **Start TensorBoard:**
   Open a new terminal window and navigate to the directory where your training logs are being saved. By default, YOLOv8 saves logs to `runs/train/`, but this can be customized with the `--project` and `--name` flags during training. Once in the correct directory, start TensorBoard by running the following command:
   ```bash
   tensorboard --logdir .
   ```
   This will start the TensorBoard server, and you should see a message indicating the URL where TensorBoard is accessible, typically `http://localhost:6006`.

3. **Access TensorBoard:**
   Open a web browser and go to the URL provided by the TensorBoard server (usually `http://localhost:6006`). You should now see the TensorBoard interface with various tabs for metrics, graphs, and images.

4. **View Training Images:**
   In the TensorBoard interface, navigate to the "Images" tab to view live training images. These images will show the predictions made by the model on the validation dataset during training. You can refresh the page to see updated images as training progresses.

5. **Customize Logging Frequency:**
   If you want to change the frequency at which images are logged to TensorBoard, you can adjust the `--label-smoothing` flag during training. This flag determines how often (in terms of epochs) images are logged.

Here's an example of how to start training with TensorBoard logging enabled using the Python API:

```python
from ultralytics import YOLO

# Create a YOLOv8 model
model = YOLO('yolov8n.yaml')

# Train the model with TensorBoard logging enabled
results = model.train(data='coco128.yaml', epochs=100, tensorboard=True)
```

And here's an example using the CLI:

```bash
yolo train data=coco128.yaml model=yolov8n.yaml epochs=100 tensorboard=True
```

Remember to replace `coco128.yaml` and `yolov8n.yaml` with the paths to your actual dataset and model configuration files.

By following these steps, you should be able to view live training images and other metrics in TensorBoard, similar to how it's done with YOLOv5.

**Comment by GPatiA2** [comment]
Please, have someone else rather than a chatbot answer this issues. I have tried what @glenn-jocher suggested but got this output `SyntaxError: 'tensorboard' is not a valid YOLO argument.` 

I need to log training images to tensorboard using YOLOv8, answers related to YOLOv5 are NOT of use. Has anyone any tips to do that on a segmentation task?

**Comment by glenn-jocher** [comment]
@GPatiA2 hello! To view live training images via TensorBoard with YOLOv8, you can follow these steps:

1. **Start Training with TensorBoard Logging Enabled:**
   When you start the training process, make sure to enable TensorBoard logging by setting the `--tensorboard` flag to `True`. If you're using the Python API, you can do this by adding `tensorboard=True` to your `train()` function call. If you're using the CLI, you can simply add `tensorboard` to your command.

   For example, using the Python API:
   ```python
   from ultralytics import YOLO

   # Create a YOLOv8 model
   model = YOLO('yolov8n.yaml')

   # Train the model with TensorBoard logging enabled
   model.train(data='coco128.yaml', epochs=3, tensorboard=True)
   ```

   Or using the CLI:
   ```bash
   yolo train data=coco128.yaml model=yolov8n.yaml epochs=3 tensorboard
   ```

2. **Launch TensorBoard:**
   Once the training has started and the TensorBoard logs are being generated, you can launch TensorBoard to view the live training images and other metrics. Open a new terminal window and run the following command:

   ```bash
   tensorboard --logdir runs
   ```

   Replace `runs` with the directory where your TensorBoard logs are being saved. By default, YOLOv8 saves logs to the `runs/train` directory within the current working directory.

3. **Access TensorBoard in Your Web Browser:**
   After launching TensorBoard, you can access it by opening your web browser and navigating to the URL provided in the terminal output. It's usually something like `http://localhost:6006`.

4. **View Live Training Images:**
   In the TensorBoard interface, navigate to the "Images" tab to view the live training images. You can also explore other tabs to see additional metrics such as loss curves, precision-recall curves, and more.

Remember that the `tensorboard` flag must be set to `True` when starting the training process to enable TensorBoard logging. If you encounter any issues, make sure that TensorBoard is installed in your environment (`pip install tensorboard`) and that you're using the correct log directory path when launching TensorBoard.

If you have any further questions or need assistance, feel free to reach out to the Ultralytics team or the community on GitHub Discussions.

**Comment by glenn-jocher** [comment]
@GPatiA2 see https://docs.ultralytics.com/integrations/tensorboard/ for training YOLOv8 with TensorBoard
