### ISSUE TITLE
ONNX opset version: 17

### ISSUE THREAD

**Issue by q465414859** [ultralytics/ultralytics#625]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

PyTorch: starting from yolov8n.pt with output shape (1, 84, 8400) (6.2 MB)

ONNX: starting export with onnx 1.13.0...
ONNX: export failure  0.1s: Unsupported ONNX opset version: 17

### Environment

YOLOV8
onnx 1.13.0
torch                   1.7.1+cu110
torchaudio              0.7.2
torchvision             0.8.2+cu110
win10
1060 5G

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@q465414859 should be resolved in #626 which makes opset argument optional (default None). Can you pull this branch and try your command again?

**Comment by q465414859** [comment]
can not find

**Comment by glenn-jocher** [comment]
@q465414859 #626 has been merged and deployed in 8.0.20, so you should be able to export correctly now with 8.0.20.

**Comment by JHLee1221** [comment]
well.. my yolov8 verson is 8.0.21, pytorch is 1.12.0 + cuda 113 and onnx is 1.12.0. I have the same problem. Cannot export onnx

**Comment by charlielito** [comment]
I can confirm I can export it with `opset=13`

**Comment by pderrenger** [comment]
@charlielito great to hear that! If you have any more questions or need further assistance, feel free to ask. Happy exporting!
