### ISSUE TITLE
AttributeError: 'BoTSORT' object has no attribute 'reset'

### ISSUE THREAD

**Issue by luke110** [ultralytics/ultralytics#6264]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

WARNING ⚠️ Environment does not support cv2.imshow() or PIL Image.show()

[32m2023-11-10 23:38:41.835[0m | [32m[1mSUCCESS [0m | [36mboxmot.appearance.reid_model_factory[0m:[36mload_pretrained_weights[0m:[36m207[0m - [32m[1mSuccessfully loaded pretrained weights from "/data/run01/scw6492/luke/yolo_track/examples/weights/osnet_x0_25_msmt17.pt"[0m
[32m2023-11-10 23:38:41.835[0m | [33m[1mWARNING [0m | [36mboxmot.appearance.reid_model_factory[0m:[36mload_pretrained_weights[0m:[36m211[0m - [33m[1mThe following layers are discarded due to unmatched keys or layer size: ('classifier.weight', 'classifier.bias')[0m
Traceback (most recent call last):
  File "/HOME/scw6492/run/luke/yolo_track/examples/track_luke.py", line 231, in <module>
    run(opt)
  File "/HOME/scw6492/.conda/envs/yolo-track/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/HOME/scw6492/run/luke/yolo_track/examples/track_luke.py", line 102, in run
    for frame_idx, r in enumerate(results):
  File "/HOME/scw6492/.conda/envs/yolo-track/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/data/run01/scw6492/luke/yolo_track/ultralytics/ultralytics/engine/predictor.py", line 269, in stream_inference
    self.run_callbacks('on_predict_postprocess_end')
  File "/data/run01/scw6492/luke/yolo_track/ultralytics/ultralytics/engine/predictor.py", line 362, in run_callbacks
    callback(self)
  File "/data/run01/scw6492/luke/yolo_track/ultralytics/ultralytics/trackers/track.py", line 48, in on_predict_postprocess_end
    predictor.trackers[i].reset()
AttributeError: 'BoTSORT' object has no attribute 'reset'

### Environment

Ultralytics YOLOv8.0.208 🚀 Python-3.9.18 torch-2.0.1 CPU (AMD EPYC 7282 16-Core Processor)
Setup complete ✅ (32 CPUs, 251.6 GB RAM, 102.9/540.6 GB disk)

OS                  Linux-3.10.0-1160.25.1.el7_lustre.x86_64-x86_64-with-glibc2.17
Environment         Linux
Python              3.9.18
Install             pip
RAM                 251.61 GB
CPU                 AMD EPYC 7282 16-Core Processor
CUDA                None

matplotlib          ✅ 3.8.1>=3.3.0
numpy               ✅ 1.24.4>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.0.1>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 2.0.1>=1.8.0
torchvision         ✅ 0.15.2>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.1.2>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

# Mikel Broström 🔥 Yolo Tracking 🧾 AGPL-3.0 license

import argparse
from functools import partial
from pathlib import Path

import torch

from boxmot import TRACKERS
from boxmot.tracker_zoo import create_tracker
from boxmot.utils import ROOT, WEIGHTS
from boxmot.utils.checks import TestRequirements
from examples.detectors import get_yolo_inferer

__tr = TestRequirements()
__tr.check_packages(('ultralytics @ git+https://github.com/mikel-brostrom/ultralytics.git',))  # install

from ultralytics import YOLO
from ultralytics.data.utils import VID_FORMATS
from ultralytics.utils.plotting import save_one_box

from examples.utils import write_mot_results

def on_predict_start(predictor, persist=False):
    """
    Initialize trackers for object tracking during prediction.

    Args:
        predictor (object): The predictor object to initialize trackers for.
        persist (bool, optional): Whether to persist the trackers if they already exist. Defaults to False.
    """

    assert predictor.custom_args.tracking_method in TRACKERS, \
        f"'{predictor.custom_args.tracking_method}' is not supported. Supported ones are {TRACKERS}"

    tracking_config = \
        ROOT / \
        'boxmot' / \
        'configs' / \
        (predictor.custom_args.tracking_method + '.yaml')
    trackers = []
    for i in range(predictor.dataset.bs):
        tracker = create_tracker(
            predictor.custom_args.tracking_method,
            tracking_config,
            predictor.custom_args.reid_model,
            predictor.device,
            predictor.custom_args.half,
            predictor.custom_args.per_class
        )
        # motion only modeles do not have
        if hasattr(tracker, 'model'):
            tracker.model.warmup()
        trackers.append(tracker)

    predictor.trackers = trackers

@torch.no_grad()
def run(args):
    yolo = YOLO(
        args.yolo_model if 'yolov8' in str(args.yolo_model) else 'yolov8n.pt',
    )

    results = yolo.track(
        source=args.source,
        conf=args.conf,
        iou=args.iou,
        show=args.show,
        stream=True,
        device=args.device,
        show_conf=args.show_conf,
        save_txt=args.save_txt,
        show_labels=args.show_labels,
        save=args.save,
        verbose=args.verbose,
        exist_ok=args.exist_ok,
        project=args.project,
        name=args.name,
        classes=args.classes,
        imgsz=args.imgsz,
        vid_stride=args.vid_stride,
        line_width=args.line_width
    )

    yolo.add_callback('on_predict_start', partial(on_predict_start, persist=True))

    if 'yolov8' not in str(args.yolo_model):
        # replace yolov8 model
        m = get_yolo_inferer(args.yolo_model)
        model = m(
            model=args.yolo_model,
            device=yolo.predictor.device,
            args=yolo.predictor.args
        )
        yolo.predictor.model = model

    # store custom args in predictor
    yolo.predictor.custom_args = args

    for frame_idx, r in enumerate(results):

        if r.boxes.data.shape[1] == 7:

            if yolo.predictor.source_type.webcam or args.source.endswith(VID_FORMATS):
                p = yolo.predictor.save_dir / 'mot' / (args.source + '.txt')
                yolo.predictor.mot_txt_path = p
            elif 'MOT16' or 'MOT17' or 'MOT20' in args.source:
                p = yolo.predictor.save_dir / 'mot' / (Path(args.source).parent.name + '.txt')
                yolo.predictor.mot_txt_path = p

            if args.save_mot:
                write_mot_results(
                    yolo.predictor.mot_txt_path,
                    r,
                    frame_idx,
                )

            if args.save_id_crops:
                for d in r.boxes:
                    print('args.save_id_crops', d.data)
                    save_one_box(
                        d.xyxy,
                        r.orig_img.copy(),
                        file=(
                                yolo.predictor.save_dir / 'crops' /
                                str(int(d.cls.cpu().numpy().item())) /
                                str(int(d.id.cpu().numpy().item())) / f'{frame_idx}.jpg'
                        ),
                        BGR=True
                    )

    if args.save_mot:
        print(f'MOT results saved to {yolo.predictor.mot_txt_path}')

"""                          version 1
--source
E:\ProgramData\Anaconda3_projects\yolo_tracking\data\48s.mp4
--img
886
1920
--name
basketball
"""

def parse_opt():
    parser = argparse.ArgumentParser()
    parser.add_argument('--yolo-model', type=Path, default=r'/data/run01/scw6492/luke/yolo_track/examples/weights/yolov8n.pt',
                        help='yolo model path')
    parser.add_argument('--reid-model', type=Path, default=r'/data/run01/scw6492/luke/yolo_track/examples/weights/osnet_x0_25_msmt17.pt',
                        help='reid model path')
    parser.add_argument('--tracking-method', type=str, default='botsort',
                        help='deepocsort, botsort, strongsort, ocsort, bytetrack')
    parser.add_argument('--source', type=str, default='../data/videos/MOT17-02-DPM_30fps.mp4',
                        help='file/dir/URL/glob, 0 for webcam')
    parser.add_argument('--imgsz', '--img', '--img-size', nargs='+', type=int, default=[640],
                        help='inference size h,w')
                        # 指定推断（inference）的图像尺寸，格式是 [h,w]
    parser.add_argument('--conf', type=float, default=0.5,
                        help='confidence threshold')
                        # 指定置信度阈值
    parser.add_argument('--iou', type=float, default=0.7,
                        help='intersection over union (IoU) threshold for NMS')
                        # 指定非极大值抑制（NMS）的IoU（交并比）阈值
    parser.add_argument('--device', default='0',
                        help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
                        # 指定使用的设备，可以是GPU（如 '0' 或 '0,1,2,3'）或CPU（ 'cpu' ），默认为 '0'。
    parser.add_argument('--show', action='store_true', default=True,
                        help='display tracking video results')
                        # 是否显示跟踪视频结果
    parser.add_argument('--save', action='store_true', default=True,
                        help='save video tracking results')
                        # 是否保存跟踪视频结果
    # class 0 is person, 1 is bycicle, 2 is car... 79 is oven
    parser.add_argument('--classes', nargs='+', type=int,
                        help='filter by class: --classes 0, or --classes 0 2 3')
                        # 指定要筛选的类别
    parser.add_argument('--project', default=ROOT / 'outputs' / 'track',
                        help='save results to project/name')
                        # 指定保存结果的项目路径
    parser.add_argument('--name', default='exp',
                        help='save results to project/name')
                        # 指定结果保存的名称
    parser.add_argument('--exist-ok', action='store_true',
                        help='existing project/name ok, do not increment')
                        # 如果项目/名称已经存在，是否覆盖
    parser.add_argument('--half', action='store_true',
                        help='use FP16 half-precision inference')
                        # 是否使用半精度（FP16）推断
    parser.add_argument('--vid-stride', type=int, default=1,
                        help='video frame-rate stride')
                        # 视频帧率步幅
    parser.add_argument('--show-labels', action='store_false', default=True,
                        help='either show all or only bboxes')
                        # 是否显示标签
    parser.add_argument('--show-conf', action='store_false', default=True,
                        help='hide confidences when show')
                        # 是否显示置信度（confidence）
    parser.add_argument('--save-txt', action='store_true', default=True,
                        help='save tracking results in a txt file')
                        # 是否将跟踪结果保存为文本文件
    parser.add_argument('--save-id-crops', action='store_true', default=True,
                        help='save each crop to its respective id folder')
                        # 是否将每个检测框保存到其相应的ID文件夹
    parser.add_argument('--save-mot', action='store_true', default=True,
                        help='save tracking results in a single txt file')
                        # 是否将跟踪结果保存为单个文本文件
    parser.add_argument('--line-width', default=None, type=int,
                        help='The line width of the bounding boxes. If None, it is scaled to the image size.')
                        # 指定边界框的线宽，默认为 None，自动根据图像大小缩。
    parser.add_argument('--per-class', default=True, action='store_true',
                        help='not mix up classes when tracking')
                        # 是否在跟踪时不混合不同的类别
    parser.add_argument('--verbose', default=True, action='store_true',
                        help='print results per frame')
                        # 是否打印每帧的结果
    parser.add_argument('--vid_stride', default=1, type=int,
                        help='video frame-rate stride')
                        # 视频帧率步幅

    opt = parser.parse_args()
    return opt

if __name__ == "__main__":
    opt = parse_opt()
    run(opt)

### Additional

I am executing a .sh file, and the code in the sh file is as follows:

#!/bin/bash
module purge
module load anaconda/2022.10
module load cuda/11.8 gcc/9.3

source activate yolo-track
export PYTHONUNBUFFERED=1

python /HOME/scw6492/run/luke/yolo_track/examples/track_luke.py --source /HOME/scw6492/run/luke/yolo_track/data/videos/MOT17-02-DPM_30fps.mp4  --save --save-mot --name MOT17-02-DPM_30fps

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. Botsort tracking works correctly in our tests:

<img width="1089" alt="Screenshot 2023-11-11 at 13 27 00" src="https://github.com/ultralytics/ultralytics/assets/26833433/4069b42c-0826-4529-b8e9-2ce4db30aa7e">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
When passing 2 videos and the tracker needs to reset everything still works correctly:

<img width="944" alt="Screenshot 2023-11-11 at 13 31 00" src="https://github.com/ultralytics/ultralytics/assets/26833433/89c3a898-4b35-44b2-b51f-b1e17a92c005">

**Comment by luke110** [comment]
> 当传递 2 个视频并且跟踪器需要重置时，一切仍然正常工作：
> 
> <img alt="截图 2023-11-11 13 31 00" width="944" src="https://user-images.githubusercontent.com/26833433/282241887-89c3a898-4b35-44b2-b51f-b1e17a92c005.png">

Thank you very much for your reply, I solved this problem by returning to 8.1x's yolov8, the latest yolov8 does not seem to solve this problem.

**Comment by luke110** [comment]
> 当输入 2 个视频并且跟踪器需要重置时，一切仍然正常工作：
> 
> <img alt="截图 2023-11-11 13 31 00" width="944" src="https://user-images.githubusercontent.com/26833433/282241887-89c3a898-4b35-44b2-b51f-b1e17a92c005.png">

I was reproducing the error that occurred when using yolov8 in a yolo-tracking project. This is yolov8’s GitHub URL https://github.com/mikel-brostrom/yolo_tracking.
The command I used is: python examples/track.py --yolo-model yolov8n.

**Comment by glenn-jocher** [comment]
@luke110 i'm glad to hear you found a workaround by reverting to an earlier version of YOLOv8. We continuously work to improve our models and sometimes regressions can occur. If using the version 8.1x of YOLOv8 resolves the issue for your current needs, that's a satisfactory temporary solution.

However, it would be beneficial for the community and the development of the YOLOv8 project to understand the root of this problem with the latest version. If you have the time and ability, I encourage you to open an issue in the appropriate YOLOv8 GitHub repository with details of the problem, including the error message, environment details, and the steps to reproduce the issue using the latest version. This way, the development team can look into it and work on a fix that will enable you to use the most up-to-date version without this issue in future releases.

If you choose to report this issue, please include specific information about your environment, the exact steps or code that leads to the error, and any other relevant details that could help us understand and replicate the problem. Your contributions in this way are valuable to the ongoing improvement of the project.

**Comment by luke110** [comment]
> @luke110我很高兴听到您通过恢复到 YOLOv8 的早期版本找到了解决方法。我们不断努力改进我们的模型，有时可能会出现回归。如果使用 YOLOv8 8.1x 版本可以解决您当前需求的问题，那么这是一个令人满意的临时解决方案。
> 
> 然而，了解最新版本的这个问题的根源对于社区和YOLOv8项目的开发都是有益的。如果您有时间和能力，我鼓励您在相应的 YOLOv8 GitHub 存储库中提出问题，并提供问题的详细信息，包括错误消息、环境详细信息以及使用最新版本重现问题的步骤。这样，开发团队就可以研究它并进行修复，使您能够在未来的版本中使用最新版本而不会出现此问题。
> 
> 如果您选择报告此问题，请提供有关您的环境的具体信息、导致错误的确切步骤或代码，以及可以帮助我们理解和重现问题的任何其他相关详细信息。您以这种方式做出的贡献对于项目的持续改进非常有价值。

Have you reproduced the error I mentioned? Do you have a solution?

**Comment by glenn-jocher** [comment]
@luke110 i apologize for any confusion earlier. As a maintainer, I cannot directly reproduce errors or implement solutions, but I can guide you based on the information provided.

The error you mentioned, `AttributeError: 'BoTSORT' object has no attribute 'reset'`, suggests that the BoTSORT tracker object being used does not have a `reset` method implemented. Considering that you are working with a custom integration of YOLOv8 within the yolo-tracking project, it is likely that the specific error is due to code within the yolo-tracking project that is expecting a `reset` method that may not exist or has been refactored or renamed in the latest version of YOLOv8.

To address the issue, here’s what you could do:

1. **Check the yolo-tracking project code**: Look for the `BoTSORT` implementation and verify whether a `reset` method should be present.

2. **Check YOLOv8 updates**: If `reset` was part of an earlier YOLOv8 implementation and has been removed or changed, the yolo-tracking project may need an update to align with the new YOLOv8 architecture.

3. **Compatibility**: Ensure that the yolo-tracking project is compatible with the YOLOv8 version you are using. It may be that the project was built for an earlier version as you guessed.

4. **Report the issue**: If you're still encountering issues, please submit a well-documented bug report on the appropriate repository- in this case, most likely the yolo-tracking project's repository, specifying the version of YOLOv8 you are using and detailing the problem.

Meanwhile, if the earlier version of YOLOv8 is stable for your use-case, it's a reasonable approach to use that version while any potential compatibility issues are resolved. 

Remember to communicate specifics such as exact error messages, code snippets, and environment details to facilitate troubleshooting and resolution of the issue.
