### ISSUE TITLE
Assign Unique ID to Target Object (object tracking)

### ISSUE THREAD

**Issue by Chiauwen** [ultralytics/ultralytics#6269]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi.

I'm currently doing car tracking with YOLOv8. I wonder how to assign a unique ID to each target object other than the default ID, such as 1, 2 and 3. 
I've searched through Github issues, and it looks like it can't replace the default ID (1, 2, 3, ..) with another custom ID.
But what if I get the ID of the target object and externally assign it with the other ID?

For Example:
I have 2 objects being tracked, the first object has ID 1 and the second object has ID 2.
For an object with ID 1, I will assign it with value x. Meanwhile, for object ID 2, I will assign it will value y. Then different IDs will get a different value. And the ID with its respective value will remain till I terminate my program.

Is it possible to do that?
Because I wanted to assign car plate numbers for different cars that come into the region.

Current code I'm doing:
`
```
import cv2
from ultralytics import YOLO
from ultralytics.utils.plotting import Annotator, colors

model = YOLO("track/pklot.pt")

cap = cv2.VideoCapture(0)

while cap.isOpened():
    success, frame = cap.read()

    if success:
        # Run YOLOv8 tracking on the frame, persisting tracks between frames
        results = model.track(frame, persist=True)
        print(results)

        # Visualize the results on the frame
        annotated_frame = results[0].plot()
        print(annotated_frame)

        cv2.imshow("YOLOv8 Tracking", annotated_frame)

        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()`
```

Project Im currently doing:
![image](https://github.com/ultralytics/ultralytics/assets/90367441/bcedba26-ac9b-4749-9521-b19a9dc39d21)

Thank you.

**Comment by glenn-jocher** [comment]
@Chiauwen hello!

Assigning customizable IDs, such as a car plate number, to tracked objects using YOLOv8 tracking data is certainly possible, though this functionality is not built directly into the model itself. However, you can achieve this with post-processing on the tracking results.

Once you receive the IDs and bounding box coordinates, you can map the default numerical IDs to your custom identifiers. This mapping would exist in your application logic outside the model's processing. Remember, each default ID corresponds directly to a tracked object, so by maintaining an external mapping between the default IDs and the custom IDs (e.g., the car plate numbers), you can make this translation persist as long as the objects are tracked.

For example, when object ID 1 is first detected, your code could prompt for a car plate number (x), and then maintain a dictionary where `custom_IDs[1] = x`. In future frames, you simply use this dictionary to look up the car plate number assigned to each tracked object. Make sure to handle cases where objects leave and re-enter the frame, causing the tracker to potentially assign a new ID to what may be the same object.

The key is to build a robust system for maintaining the association between YOLOv8's IDs and your custom IDs throughout the lifespan of your tracking application. This typically involves matching objects between frames based on additional criteria such as bounding box overlap, appearance similarity, or other heuristics.

Good luck with your car tracking project! If you need more in-depth guides and information, you can refer to the Ultralytics documentation.

**Comment by Chiauwen** [comment]
> @Chiauwen hello!
> 
> Assigning customizable IDs, such as a car plate number, to tracked objects using YOLOv8 tracking data is certainly possible, though this functionality is not built directly into the model itself. However, you can achieve this with post-processing on the tracking results.
> 
> Once you receive the IDs and bounding box coordinates, you can map the default numerical IDs to your custom identifiers. This mapping would exist in your application logic outside the model's processing. Remember, each default ID corresponds directly to a tracked object, so by maintaining an external mapping between the default IDs and the custom IDs (e.g., the car plate numbers), you can make this translation persist as long as the objects are tracked.
> 
> For example, when object ID 1 is first detected, your code could prompt for a car plate number (x), and then maintain a dictionary where `custom_IDs[1] = x`. In future frames, you simply use this dictionary to look up the car plate number assigned to each tracked object. Make sure to handle cases where objects leave and re-enter the frame, causing the tracker to potentially assign a new ID to what may be the same object.
> 
> The key is to build a robust system for maintaining the association between YOLOv8's IDs and your custom IDs throughout the lifespan of your tracking application. This typically involves matching objects between frames based on additional criteria such as bounding box overlap, appearance similarity, or other heuristics.
> 
> Good luck with your car tracking project! If you need more in-depth guides and information, you can refer to the Ultralytics documentation.

Thanks, I have solved this problem in my project!

But I have a question would like to ask.
Is there any method to remove the confidence score on the bounding box in the case of car tracking? I tried with "show_conf=False" in `results = model.track(frame, persist=True, show_conf=False, conf=0.5)`. But the confidence score still shows along with the bounding box.

**Comment by glenn-jocher** [comment]
Hello @Chiauwen,

Great to hear you've resolved the custom ID mapping!

Regarding the confidence score, currently, there isn't a direct option like `show_conf` to control the display of confidence levels during object tracking. The confidence scores are a part of the default annotations for tracked objects. As of my last update, if you wish to remove them from your visual output, you’ll need to modify the plot or annotator routines within your own script.

For example, you could access the Annotator class to customize the annotations according to your preferences. Remember, any alterations for this behavior are done post-processing, outside the core model's tracking outputs. Please consult the Ultralytics documentation for a deeper look into the customization of the plotting functionality.

**Comment by himalivaghela** [comment]
Hello, I am also using the model yolov8x-pose and facing id skipped issue. I am using for one task where people are entering in one space and leaving that space. For example, once any person is entering in that space, It will assign the id "1" for example. 
What my requirement is if any people entering and leaving that space then the same id should not assign to anyone and it should be always incremental. 1,2,3 .. so on. But It's not happening. Once person is out of that space it's assigning same id to another person. S
Another issue I am facing that it's skipping the sequence. So, Can you help me which hyperparameter I can set so it should remains sequential rather than skipping.?? 
Please can you help me regarding this.?

**Comment by AbdelrhmanNile** [comment]
@Chiauwen 
can you share with us how did you solve it?
