### ISSUE TITLE
Extract mask info from FastSAM

### ISSUE THREAD

**Issue by 3DMiller** [ultralytics/ultralytics#6276]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I am following the tutorial here (https://docs.ultralytics.com/models/fast-sam/) and it works great to use an example image and export the segmented image with masks. I need to get the pixel row,col info for the masks. Not the box but the actual row,col for each vertex in the mask. Is this possible? Hope that makes sense. 

### Additional

See above for question.

**Comment by glenn-jocher** [comment]
@3DMiller hello!

I'm glad to hear that the tutorial has been helpful for you. To obtain the row and column information for each vertex in the mask generated by FastSAM, you can use the output of the model which returns a segmentation mask. The segmentation mask is a 2D array where each unique value corresponds to a different detected object.

To access the pixel-level information, iterate over each unique value in this 2D array (except the background, usually denoted by zero). For each unique object identifier, create a binary mask where the pixels belonging to the current object are set to `True` (or `1`) and all other pixels are set to `False` (or `0`). Then, you can extract the row and column coordinates where the binary mask is `True`, which will give you the specific pixel locations of the mask vertices.

These operations can typically be done using libraries like NumPy or OpenCV in Python. You can find the exact pixel indices using functions such as `numpy.where`.

Remember to refer to the Ultralytics Docs, as they provide comprehensive information about the different models and their outputs, which may further assist in manipulating and understanding the mask information.

If you need any specific help regarding the use of our tools, feel free to raise an issue in the Ultralytics YOLOv8 repository, and we will be there to assist you!
