### ISSUE TITLE
command not found: yolo

### ISSUE THREAD

**Issue by liumingxing** [ultralytics/ultralytics#6281]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hi every one, I'm new to Yolo8.
My Computer runs MacOS(Sonoma 14.0)，Python, 3.9.6.
After my first step, "pip3 install ultralytics", It seems yolo8 successfully installed, But when I execute yolo in shell, It shows "command not found: yolo"

I also checked source code in https://github.com/ultralytics/ultralytics, I still didn't found /bin/yolo in source code. So what is the location of yolo?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by liumingxing** [comment]
pip3 install ultralytics

Requirement already satisfied: ultralytics in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (8.0.208)
Requirement already satisfied: matplotlib>=3.3.0 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from ultralytics) (3.7.2)
Requirement already satisfied: tqdm>=4.64.0 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from ultralytics) (4.66.1)
Requirement already satisfied: opencv-python>=4.6.0 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from ultralytics) (4.8.1.78)
Requirement already satisfied: requests>=2.23.0 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from ultralytics) (2.31.0)
Requirement already satisfied: scipy>=1.4.1 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from ultralytics) (1.11.2)
Requirement already satisfied: psutil in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from ultralytics) (5.9.4)
Requirement already satisfied: torch>=1.8.0 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from ultralytics) (2.0.1)
Requirement already satisfied: py-cpuinfo in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from ultralytics) (9.0.0)
Requirement already satisfied: pandas>=1.1.4 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from ultralytics) (2.1.3)
Requirement already satisfied: thop>=0.1.1 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from ultralytics) (0.1.1.post2209072238)
Requirement already satisfied: torchvision>=0.9.0 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from ultralytics) (0.15.2)
Requirement already satisfied: seaborn>=0.11.0 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from ultralytics) (0.13.0)
Requirement already satisfied: pyyaml>=5.3.1 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from ultralytics) (6.0)
Requirement already satisfied: pillow>=7.1.2 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from ultralytics) (10.0.0)
Requirement already satisfied: numpy>=1.22.2 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from ultralytics) (1.26.1)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from matplotlib>=3.3.0->ultralytics) (5.12.0)
Requirement already satisfied: python-dateutil>=2.7 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from matplotlib>=3.3.0->ultralytics) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from matplotlib>=3.3.0->ultralytics) (1.4.4)
Requirement already satisfied: fonttools>=4.22.0 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from matplotlib>=3.3.0->ultralytics) (4.39.4)
Requirement already satisfied: packaging>=20.0 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from matplotlib>=3.3.0->ultralytics) (23.1)
Requirement already satisfied: contourpy>=1.0.1 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from matplotlib>=3.3.0->ultralytics) (1.0.6)
Requirement already satisfied: cycler>=0.10 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from matplotlib>=3.3.0->ultralytics) (0.11.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from matplotlib>=3.3.0->ultralytics) (3.0.9)
Requirement already satisfied: tzdata>=2022.1 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from pandas>=1.1.4->ultralytics) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from pandas>=1.1.4->ultralytics) (2023.3.post1)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from requests>=2.23.0->ultralytics) (3.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from requests>=2.23.0->ultralytics) (2022.9.24)
Requirement already satisfied: idna<4,>=2.5 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from requests>=2.23.0->ultralytics) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from requests>=2.23.0->ultralytics) (1.26.16)
Requirement already satisfied: sympy in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from torch>=1.8.0->ultralytics) (1.11.1)
Requirement already satisfied: jinja2 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from torch>=1.8.0->ultralytics) (3.1.2)
Requirement already satisfied: typing-extensions in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from torch>=1.8.0->ultralytics) (4.6.2)
Requirement already satisfied: filelock in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from torch>=1.8.0->ultralytics) (3.12.2)
Requirement already satisfied: networkx in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from torch>=1.8.0->ultralytics) (2.8.8)
Requirement already satisfied: zipp>=3.1.0 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib>=3.3.0->ultralytics) (3.15.0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.15.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from jinja2->torch>=1.8.0->ultralytics) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /Users/liumingxing/Library/Python/3.9/lib/python/site-packages (from sympy->torch>=1.8.0->ultralytics) (1.2.1)

**Comment by liumingxing** [comment]
Problem resolved. 
It's because my /usr/local/bin/ directory is not writable. I install ultralytics in ubuntu, and copy the file of yolo to another diretory in $PATH on my MacOS.

**Comment by liumingxing** [comment]
Problem resolved.

**Comment by glenn-jocher** [comment]
@liumingxing glad to hear you resolved the problem! It's important to ensure that your environment is set up correctly and that all binaries or scripts are installed in directories included in your system's $PATH. If you have any more queries or run into issues in the future, feel free to reach out. Happy coding with YOLOv8!

**Comment by hariouat** [comment]
> Problem resolved. It's because my /usr/local/bin/ directory is not writable. I install ultralytics in ubuntu, and copy the file of yolo to another diretory in $PATH on my MacOS.

please i have the same problem. Could you give me your solution?

**Comment by liumingxing** [comment]
you can make a new file in /usr/local/bin/yolo, with the context:



#!/usr/bin/python3

# -*- coding: utf-8 -*-

import re

import sys

from ultralytics.cfg import entrypoint

if __name__ == '__main__':

&nbsp; &nbsp; sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])

&nbsp; &nbsp; sys.exit(entrypoint())



and execute "chmod +x /usr/local/bin/yolo" in shell


刘明星
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/ultralytics"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月6日(星期三) 下午5:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/ultralytics] command not found: yolo (Issue #6281)





  
Problem resolved. It's because my /usr/local/bin/ directory is not writable. I install ultralytics in ubuntu, and copy the file of yolo to another diretory in $PATH on my MacOS.
  
please i have the same problem. Could you give me your solution?

**Comment by hariouat** [comment]
> you can make a new file in /usr/local/bin/yolo, with the context: #!/usr/bin/python3 # -*- coding: utf-8 -*- import re import sys from ultralytics.cfg import entrypoint if __name__ == '__main__': &nbsp; &nbsp; sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0]) &nbsp; &nbsp; sys.exit(entrypoint()) and execute "chmod +x /usr/local/bin/yolo" in shell 刘明星 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ultralytics/ultralytics" ***@***.***&gt;; 发送时间:&nbsp;2023年12月6日(星期三) 下午5:35 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ultralytics/ultralytics] command not found: yolo (Issue #6281) Problem resolved. It's because my /usr/local/bin/ directory is not writable. I install ultralytics in ubuntu, and copy the file of yolo to another diretory in $PATH on my MacOS. please i have the same problem. Could you give me your solution? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Thanks for your replay. I modified the yolo file like this but still have the same error: "yolo not found" 

#!/opt/conda/bin/python3.10
# -*- coding: utf-8 -*-
import re
import sys
from ultralytics.cfg import entrypoint
if __name__ == '__main__':
 &nbsp; &nbsp; sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])

 &nbsp; &nbsp; sys.exit(entrypoint())

**Comment by hariouat** [comment]
> you can make a new file in /usr/local/bin/yolo, with the context: #!/usr/bin/python3 # -*- coding: utf-8 -*- import re import sys from ultralytics.cfg import entrypoint if __name__ == '__main__': &nbsp; &nbsp; sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0]) &nbsp; &nbsp; sys.exit(entrypoint()) and execute "chmod +x /usr/local/bin/yolo" in shell 刘明星 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ultralytics/ultralytics" ***@***.***&gt;; 发送时间:&nbsp;2023年12月6日(星期三) 下午5:35 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ultralytics/ultralytics] command not found: yolo (Issue #6281) Problem resolved. It's because my /usr/local/bin/ directory is not writable. I install ultralytics in ubuntu, and copy the file of yolo to another diretory in $PATH on my MacOS. please i have the same problem. Could you give me your solution? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Thank you for your replay. I modified the yolo file like this, but still have the same error: yolo not found. 

#!/opt/conda/bin/python3.10
# -*- coding: utf-8 -*-
import re
import sys
from ultralytics.cfg import entrypoint
if __name__ == '__main__':
 &nbsp; &nbsp; sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])

 &nbsp; &nbsp; sys.exit(entrypoint())

**Comment by liumingxing** [comment]
You can execute with absolute path in shell "/usr/local/bin/yolo" or you can add "/usr/local/bin" to your $PATH environments.




刘明星
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/ultralytics"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月6日(星期三) 晚上6:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/ultralytics] command not found: yolo (Issue #6281)





  
you can make a new file in /usr/local/bin/yolo, with the context: #!/usr/bin/python3 # -- coding: utf-8 -- import re import sys from ultralytics.cfg import entrypoint if name == 'main': &nbsp; &nbsp; sys.argv[0] = re.sub(r'(-script.pyw|.exe)?$', '', sys.argv[0]) &nbsp; &nbsp; sys.exit(entrypoint()) and execute "chmod +x /usr/local/bin/yolo" in shell 刘明星 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ultralytics/ultralytics" @.&gt;; 发送时间:&nbsp;2023年12月6日(星期三) 下午5:35 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [ultralytics/ultralytics] command not found: yolo (Issue #6281) Problem resolved. It's because my /usr/local/bin/ directory is not writable. I install ultralytics in ubuntu, and copy the file of yolo to another diretory in $PATH on my MacOS. please i have the same problem. Could you give me your solution? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
Thanks for your replay. I modified the yolo file like this but still have the same error: "yolo not found"
 
#!/opt/conda/bin/python3.10
 
-- coding: utf-8 --
 
import re
 import sys
 from ultralytics.cfg import entrypoint
 if name == 'main':
 &nbsp; &nbsp; sys.argv[0] = re.sub(r'(-script.pyw|.exe)?$', '', sys.argv[0])
 
&nbsp; &nbsp; sys.exit(entrypoint())

**Comment by glenn-jocher** [comment]
@liumingxing to resolve the "yolo not found" error, you might need to ensure that the `/usr/local/bin` directory is in your system's `$PATH` environment variable. You can add it by running the following command in your shell:

```bash
export PATH="/usr/local/bin:$PATH"
```

If you want this change to be permanent, you can add the above line to your shell's profile file (e.g., `.bashrc`, `.zshrc`, etc.).

Alternatively, if you'd prefer to run the `yolo` command directly without modifying the `$PATH`, use the full path:

```bash
/usr/local/bin/yolo [arguments]
```

Make sure the `yolo` script is executable with the proper permissions:

```bash
chmod +x /usr/local/bin/yolo
```

Once you do this, you should be able to run the `yolo` command as expected.

**Comment by kpboyle25** [comment]
I had this same issue after using pip to install, but I had to add the ~/.local/bin to my PATH instead.

I found this when running the pip install command. The first "Requirement Already Satisfied" shows the path where to find the yolo script. If you run the script in that folder with no args, it will show a help page, this means you found the correct script.

**Comment by glenn-jocher** [comment]
Hello @kpboyle25,

Thank you for sharing your experience and solution! It's great to hear that you were able to resolve the issue by adding `~/.local/bin` to your `$PATH`.

For anyone encountering a similar issue, here's a quick summary of the steps you can follow:

1. **Identify the Installation Path**: When you run `pip install ultralytics`, note the path where the `yolo` script is installed. This is typically displayed in the first "Requirement Already Satisfied" message.

2. **Add to PATH**: If the `yolo` script is installed in a directory like `~/.local/bin`, you can add this directory to your `$PATH` environment variable. You can do this by running:
   ```bash
   export PATH="$HOME/.local/bin:$PATH"
   ```
   To make this change permanent, add the above line to your shell's profile file (e.g., `~/.bashrc`, `~/.zshrc`).

3. **Verify the Installation**: You can verify that the `yolo` command is correctly installed by running:
   ```bash
   yolo
   ```
   This should display the help page, confirming that the script is correctly found and executable.

If you continue to experience issues, please ensure you are using the latest versions of `torch` and `ultralytics`. You can upgrade them using:
```bash
pip install --upgrade torch ultralytics
```

If the problem persists, please provide a minimal reproducible example so we can investigate further. You can find more details on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Thank you for your patience and for contributing to the community! If you have any more questions or need further assistance, feel free to ask. 😊
