### ISSUE TITLE
Only saving preticted images with conf > 0.5 in yolov8

### ISSUE THREAD

**Issue by IIrkan** [ultralytics/ultralytics#6282]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi all,
I am looking for saving preticted images with a conf >0.5 in yolov8.
Tried many things but only capable of saving all preticted images without discrimination (all the images, even without detection)

Thanks in advance :)

**Comment by IIrkan** [comment]
Finally found

**Comment by glenn-jocher** [comment]
@IIrkan great to hear you've found a solution! If you encounter any more questions or issues, feel free to raise them in the repo discussions or issues section. Your contributions help improve the experience for the whole YOLOv8 community. Happy detecting!
