### ISSUE TITLE
DDP: multi node training

### ISSUE THREAD

**Issue by baudneo** [ultralytics/ultralytics#6286]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have been experimenting with DDP multi node training Yolov8. I had it working, started a new session and now it hangs after scanning the training images, it does not proceed on to scanning the validation image/labels.

I had to make minor alterations to some of the ultralytics code to get it to work but, it was working across multiple nodes. The code I changed is the same code in this issue (https://github.com/ultralytics/ultralytics/issues/2132). Basically, RANK is passed instead of LOCAL_RANK which caused the CUDA device id error.

I confirmed that both nodes were being used for training by stopping training with DDP and training using a single node, the epoch time was approximately doubled on a single node.

I removed the DDP specific parts from the train.py script and ran it on a single machine and it trains.

# Code
## train.py
```python3
"""
use python3 -m torch.distributed.run to run this script.
nproc_per_node: number of GPUs per node (can change between nodes if one machine has less/more)
nnodes: number of nodes (machines) to use (elastic <min>:<max>)

Example:


python -m torch.distributed.run \
--nproc_per_node 1 --nnodes 1:2 --node_rank 0 --master_addr "10.0.20.1" --master_port 8456 \
/root/train.py
"""
import os
import time
from pathlib import Path

import ultralytics
from ultralytics.utils import RANK, LOCAL_RANK
import torch.distributed as dist


if __name__ == "__main__":
    print(f"{RANK=} -- {LOCAL_RANK=}")
    dist.init_process_group(
        backend="nccl",
        init_method="env://",
        world_size=2,
        rank=RANK,
    )
    model_path = Path("/shared/models/yolo")
    model_name = "yolov8n.pt"
    working_dir = Path("/root/proj/output")
    yaml_file = "/root/proj/data.yaml"
    max_epochs = 150
    batch_size = 16
    imgsz = 640
    name = "DDP"
    print(f"About to load model: {model_path/model_name}")
    model = ultralytics.models.YOLO((model_path / model_name).as_posix())
    print(f"About to train model: {model_path/model_name}")
    start = time.perf_counter()
    results = model.train(
        task="detect",
        data=yaml_file,
        epochs=max_epochs,
        batch=batch_size,
        imgsz=imgsz,
        project=working_dir.as_posix(),
        name=name,
        device=[LOCAL_RANK],
    )
    print(f"Training took {time.perf_counter() - start:.5f} seconds to run")
    success = None
    if RANK in (0, -1):
        success = model.val()
        if success:
            model.export()

```

## Node 0
```bash
torchrun --nproc_per_node 1 --nnodes 2 --node_rank 0 --master_addr "10.0.20.1" --master_port 8456 --local_addr "10.0.20.1" /root/train.py
```

## Node 1
```bash
torchrun --nproc_per_node 1 --nnodes 2 --node_rank 1 --master_addr "10.0.20.1" --master_port 8456 --local_addr "10.0.20.3" /root/train.py
```

# Output

## Node 0
```log
╭─   ~ ───────────────────────────────────────────────────────────────────────────────  ultralytics with root@pve740 at  10:54:49 AM
╰─❯ torchrun \
--nproc_per_node 1 --nnodes 2 --node_rank 0 --master_addr "10.0.20.1" --master_port 8456 --local_addr "10.0.20.1" \
/root/train.py
RANK=0 -- LOCAL_RANK=0
About to load model: /root/proj/output/DDP4/weights/last.pt
About to resume training: /root/proj/output/DDP4/weights/last.pt
Ultralytics YOLOv8.0.208 🚀 Python-3.9.2 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce GTX 1660 Ti, 5937MiB)
Transferred 355/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
WARNING ⚠️ NMS time limit 0.550s exceeded
AMP: checks passed ✅
train: Scanning /root/proj/labels/train.cache... 101718 images, 2 backgrounds, 35327 corrupt: 100%|██████████| 101718/101718 [00:00<?, ?it
train: WARNING ⚠️ /root/proj/images/train/94a6a782-23f0-11e9-a79a-e7fb5b835158.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0731]
train: WARNING ⚠️ /root/proj/images/train/94a6a7d2-23f0-11e9-a79b-1779a5fc7332.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0731]
train: WARNING ⚠️ /root/proj/images/train/fcbb387a-5952-11ec-ae06-bbd85f941044.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0739]

# log continues with train: corrupted image/label pair and freezes before moving onto val:
```

## Node 1
```log
(ultralytics) root@training:~# torchrun --nproc_per_node 1 --nnodes 2 --node_rank 1 --master_addr "10.0.20.1" --master_port 8456 --local_addr "10.0.20.3" /root/train.py
RANK=1 -- LOCAL_RANK=0
About to load model: /shared/models/last.pt
About to resume training: /shared/models/last.pt
train: Scanning /root/proj/labels/train.cache... 101718 images, 2 backgrounds, 35327 corrupt: 100%|██████████| 101718/101718 [00:00<?, ?it
Traceback (most recent call last):
  File "/root/train.py", line 55, in <module>
    results = model.train(
  File "/root/venv/lib/python3.10/site-packages/ultralytics/engine/model.py", line 338, in train
    self.trainer.train()
  File "/root/venv/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 190, in train
    self._do_train(world_size)
  File "/root/venv/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 286, in _do_train
    self._setup_train(world_size)
  File "/root/venv/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 251, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
  File "/root/venv/lib/python3.10/site-packages/ultralytics/models/yolo/detect/train.py", line 56, in get_dataloader
    with torch_distributed_zero_first(
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/root/venv/lib/python3.10/site-packages/ultralytics/utils/torch_utils.py", line 39, in torch_distributed_zero_first
    dist.barrier(device_ids=[0])
  File "/root/venv/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/root/venv/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3696, in barrier
    work = default_pg.barrier(opts=opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1331, internal error - please report this issue to the NCCL developers, NCCL version 2.18.1
ncclInternalError: Internal check failed.
Last error:
Socket recv failed while polling for opId=0x7fcb3dd87d80
[2023-11-12 18:06:45,168] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 14000) of binary: /root/venv/bin/python3
Traceback (most recent call last):
  File "/root/venv/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/venv/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/venv/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/root/venv/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/root/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/root/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-12_18:06:45
  host      : training.localdomain
  rank      : 1 (local_rank: 0)
  exitcode  : 1 (pid: 14000)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

# Thoughts
It seems to me that the model.train() method is freezing on node 0 before moving onto the val: dataset scan but, only when using DDP. It works fine when not using DDP.

IDK if the NCLL error on the slave node is a red herring. If the master node is frozen and not returning keep alives or whatever, then this error may occur.

Any thoguhts would be helpful.

TIA!

### Additional

I have tried:
-  deleting the train.cache and val.cache files on both nodes
- running training separately on each node, which works
- deleting and re-adding dataset on each node

**Comment by glenn-jocher** [comment]
@baudneo it seems like you're encountering a hang in the distributed training process after making changes for multi-node training with DDP. This kind of problem can be tricky to diagnose as it often involves inter-node communication and synchronization issues.

The logs you've provided indicate that the training hangs after scanning the training images on Node 0 and an NCCL error on Node 1. The NCCL error suggests there might be an issue with the collective communication across the nodes.

Here are a few steps you could take to debug and hopefully resolve your issue:

1. **Ensure Consistent Environment**: Make sure that the software environment, including PyTorch and NCCL versions, is consistent across all nodes. NCCL is particularly sensitive to version mismatches. 

2. **Network Connectivity**: Verify that your nodes have the proper network setup for NCCL communication. This typically means they should be on the same subnet and that firewalls or other network policies aren't interfering with the specified ports.

3. **Test NCCL Independently**: Test your NCCL installation independently of PyTorch to ensure it is functioning correctly. NCCL comes with test scripts that can diagnose issues outside of your PyTorch code.

4. **Examine Cache Files**: Although you've already tried deleting `.cache` files, make sure that all nodes generate these files again successfully and that they are reading the correct paths. Any discrepancy can cause synchronization problems.

5. **Synchronization Points**: Add synchronization points in your code to check that processes are correctly waiting for each other at the right times. For example, use `torch.distributed.barrier()` before and after significant events, such as after initializing the process group or after loading models.

6. **Logging and Verbosity**: Increase the logging verbosity of NCCL and PyTorch distributed operations. This could provide more insights into what may be causing the hangup.

7. **Minimal Example**: Try distilling your code down to a minimal example that can reproduce the issue. Sometimes, this can help isolate the part of the code that's causing the problem.

8. **Isolate Rank 0 Operations**: Consider if there are any operations that are happening on Rank 0 that are not properly synced with other ranks. This is a common source of deadlocks.

9. **Hardware and System Checks**: Verify that each node has access to the GPU as expected and that there are no system-level issues with shared filesystems or resource contention.

Remember that multi-node DDP can introduce complexities not present in single-node or single-GPU training scenarios. Distributed training requires careful orchestration between the different processes and nodes involved.

If these suggestions do not resolve the issue, I recommend checking the system logs and detailed error messages for all nodes involved, and try searching for any NCCL-related issues in the context of PyTorch's distributed training. For further detailed troubleshooting, you may refer to the Ultralytics documentation or consider reaching out to the community on the appropriate GitHub issue discussions or forums.

**Comment by baudneo** [comment]
Well, this is weird. After a reboot of Node 0, everything is working as it should.

```log
val: WARNING ⚠️ /root/proj/images/val/fd147a48-5952-11ec-b45d-7bb4b2df3cf7.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0276]
Plotting labels to /root/proj/output/DDP4/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: SGD(lr=0.01, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /root/proj/output/DDP4
Starting training for 150 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/150      1.24G      1.249     0.8266      1.164         38        640:  35%|███▍      | 1439/4150 [08:22<15:40,  2.88it/s]

```

Both GPUs are crunching away!

**Comment by glenn-jocher** [comment]
@baudneo great to hear that your system is functioning correctly after a reboot. It's not uncommon for DDP and NCCL-related hiccups to resolve with a system restart, which often resets the state of network interfaces, clears any potential deadlocks in the GPU communication, and generally provides a clean slate for distributed operations to commence.

System resets can address a range of issues from hardware (like GPU states) to software (like lingering processes or port usage) which might otherwise be difficult to diagnose in complex distributed setups.

Remember that if you face similar issues in the future, a reboot can be a good initial troubleshooting step, especially if the system was previously working fine under similar conditions.

As your training is now proceeding as expected, continue to monitor both nodes for consistency in performance and to ensure that there are no further interruptions or anomalies. Happy training with YOLOv8!

**Comment by Python123wbl456** [comment]
@baudneo Hello, I'd like to ask which parts of the code you changed to enable multi-node training. I had some issues when trying to train across multiple nodes.
