### ISSUE TITLE
What should I pass to YOLODataset?

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [ultralytics/ultralytics#629]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to run the dataset by itself, to understand how it works

```python
from ultralytics.yolo.data.dataset import YOLODataset
from pathlib import Path

src = Path("/Users/giuliocesare/Documents/ultralytics/data/train")

ds = YOLODataset(
    img_path=str(src / 'images'),
    label_path=str(src / 'labels')
)

print(ds[0])
```

But

```
  ds = YOLODataset(
  File "/Users/giuliocesare/Documents/ultralytics/ultralytics/yolo/data/dataset.py", line 45, in __init__
    super().__init__(img_path, imgsz, label_path, cache, augment, hyp, prefix, rect, batch_size, stride, pad,
  File "/Users/giuliocesare/Documents/ultralytics/ultralytics/yolo/data/base.py", line 73, in __init__
    self.transforms = self.build_transforms(hyp=hyp)
  File "/Users/giuliocesare/Documents/ultralytics/ultralytics/yolo/data/dataset.py", line 140, in build_transforms
    transforms = mosaic_transforms(self, self.imgsz, hyp) if mosaic else affine_transforms(self.imgsz, hyp)
  File "/Users/giuliocesare/Documents/ultralytics/ultralytics/yolo/data/augment.py", line 647, in mosaic_transforms
    Mosaic(dataset, imgsz=imgsz, p=hyp.mosaic, border=[-imgsz // 2, -imgsz // 2]),
AttributeError: 'NoneType' object has no attribute 'mosaic'
```

It looks like I need to pass `hyp` somehow but I don't know the current structure of that dict. 

Would it be possible to document it?

Thanks.

Cheers,

Fra

**Comment by FrancescoSaverioZuppichini** [comment]
F

**Comment by pderrenger** [comment]
@FrancescoSaverioZuppichini hi Fra,

It seems like you encountered an issue with passing the `hyp` argument to the YOLODataset. The `hyp` stands for hyperparameters and it controls the augmentation and transformation parameters used during training. You can create a `hyp` dictionary with the desired augmentation parameters based on the structure defined in the augment.py file, or simply pass `None` as the `hyp` argument to use the default augmentation settings.
