### ISSUE TITLE
'.engine' model loading not implemented

### ISSUE THREAD

**Issue by kaiii0328** [ultralytics/ultralytics#6295]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

after exporting trained YOLOv8 model to engine, cannot load the engine file using YOLO api

![image](https://github.com/ultralytics/ultralytics/assets/44935316/4b219de5-de0b-4a07-b5ed-f6df021e71f5)

Results inconsistent with screen shots in [#1225](https://github.com/ultralytics/ultralytics/issues/1225#issuecomment-1451192713)

### Use case

Loading engine model and support predict in detect task mode.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
@kaiii0328, appreciate the information! I've tried to replicate the issue but couldn't encounter it. The inference appears to be functioning correctly.

![Screenshot 2023-11-13 104306](https://github.com/ultralytics/ultralytics/assets/62513924/e8e0e74e-d5c4-413e-98e7-94cfcd027756)

Hope this helps! Let me know if you have any additional questions.
Thanks
