### ISSUE TITLE
How to use the sam model on high-resolution images with SAHI?

### ISSUE THREAD

**Issue by zouxiaodong** [ultralytics/ultralytics#6298]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to use the sam model on high-resolution images with SAHI?
my image resolution is very huge :5762x3648

**Comment by RizwanMunawar** [comment]
Integration of SAHI with the SAM model, @zouxiaodong, is currently not supported. There is a possibility that this feature might be implemented in the upcoming updates. Thanks.
