### ISSUE TITLE
from ultralytics.engine.model import TASK_MAP

### ISSUE THREAD

**Issue by AFallDay** [ultralytics/ultralytics#6299]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I can‘t find the TASK_MAP.
![image](https://github.com/ultralytics/ultralytics/assets/144637847/14595f71-f679-48fe-b8ca-a1d00f79922e)
![image](https://github.com/ultralytics/ultralytics/assets/144637847/cb6b0bb3-6908-42bc-8bc4-1bef31ab7a15)
If it's a problem with it's version , then how do I download the other version? thanks.

**Comment by RizwanMunawar** [comment]
@AFallDay, appreciate the detailed information. To resolve this issue, use the mentioned approach to call task_map:

```python
from ultralytics.engine.model import Model
Model.task_map
```

Hope this helps! Let me know if you have any additional questions.
Thanks
