### ISSUE TITLE
coco128 datasets with yolov8

### ISSUE THREAD

**Issue by moshiour** [ultralytics/ultralytics#630]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

yolo model has always been train (by defaults) with coco128 datasets in the tutorial. Have you ever checked mismatched between images and labels files name of coco128? However, total no. of files in both images and labels are 128. One example of mismatches:   images/train2017/000000000250.jpg and same file is not available in labels/train2017/
there are more .......
How does model start training without any complain? It must be serious issue for validation and accuracy.

**Comment by AyushExel** [comment]
When training on coco128 you should see in the log that there are only 126 images and 2 background images. So only 126 images that have labels are considered for training. 
You can see the log in official colab

**Comment by dmddmd** [comment]
how many epochs do I need at least, to get some predictions?

**Comment by AyushExel** [comment]
Depends on you. You can get predictions without any epochs also if you'd like.
