### ISSUE TITLE
How to apply Non Maximal Suppression from CLI

### ISSUE THREAD

**Issue by sunhoro** [ultralytics/ultralytics#6315]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I was not able to find any information for applying Non Max Suppression (select one bounding box from many overlapping) from https://docs.ultralytics.com/usage/cli/#train.

Can anyone help me out on how I can apply NMS both on CLI and Python script?

Thank you,

**Comment by glenn-jocher** [comment]
@sunhoro non-Maximal Suppression (NMS) is already integrated into the detection process of YOLOv8. When you run the YOLOv8 model for predictions using the CLI or a Python script, NMS is applied by default to filter out overlapping bounding boxes and keep only the ones with the highest confidence scores.

For the CLI, when you run inference with YOLOv8 using the `predict` mode, the NMS operation is performed automatically, and you do not need to apply it separately.

Similarly, in a Python environment, when using our YOLOv8 model to perform predictions, the NMS is applied internally as part of the detection pipeline. If you wish to adjust the NMS parameters, such as the IoU (Intersection over Union) threshold or the confidence threshold, you can do so by modifying the corresponding arguments in the model's configuration before running the detection.

For more detailed instructions on how to adjust these parameters, kindly refer to the documentation at https://docs.ultralytics.com, which provides comprehensive information on how to customize various settings of the model.
