### ISSUE TITLE
ONNX export bug with dynamic axes

### ISSUE THREAD

**Issue by wvalcke** [ultralytics/ultralytics#632]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

The following code is an extract of the export.py file
```
            elif isinstance(self.model, DetectionModel):
                dynamic['output0'] = {0: 'batch', 1: 'anchors'}  # shape(1,25200,85)
```
I think that this piece of code is a leftover of the yolov5 code, where the dynamic axis for the anchors was at  index 1, but now the anchors are at index 2. For a simple (1, 3, 640, 640) input we have for the v8 detection model (onnx) (1, 84, 8400) as output. Also the comment after the line says shape(1, 25200, 85) which is the output shape of yolov5 in export mode. Which is correct (80*80*3+40*40*3+20*20*3 = 25200) is the amount of anchors. But not anymore for yolov8.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by q465414859** [comment]
PyTorch: starting from yolov8n.pt with output shape (1, 84, 8400) (6.2 MB)

ONNX: starting export with onnx 1.13.0...
ONNX: export failure 0.1s: Unsupported ONNX opset version: 17

**Comment by nikbobo** [comment]
> PyTorch: starting from yolov8n.pt with output shape (1, 84, 8400) (6.2 MB)
> 
> ONNX: starting export with onnx 1.13.0... ONNX: export failure 0.1s: Unsupported ONNX opset version: 17

Seems your pytorch version is too old.
When I using pytorch 1.11.0 I got the same error.
You can upgrade pytorch to 1.13.0, which is support onset 17.

**Comment by AyushExel** [comment]
Hey guys. We now have official example tutorials for using ONNX export inference with Python and C++ 
https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-OpenCV-ONNX-Python

I think that'll resolve the issue. If not, please reopen
