### ISSUE TITLE
Hi @glenn-jocher @plashchynski @diramazioni I am trying to do something similar but using webcam. However I am getting the following error. I have attached the code to reproduce that error. Your help would be appreciated!

### ISSUE THREAD

**Issue by aniketkanse** [ultralytics/ultralytics#6324]
Hi @glenn-jocher @plashchynski @diramazioni I am trying to do something similar but using webcam. However I am getting the following error. I have attached the code to reproduce that error. Your help would be appreciated!

0: 384x640 (no detections), 28.2ms
Speed: 6.7ms preprocess, 28.2ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)
Traceback (most recent call last):

  File "C:\Users\Downloads\main.py", line 91, in <module>
    main()

  File "C:\Users\Downloads\main.py", line 60, in main
    detections = sv.Detections.from_yolov8(result)

AttributeError: type object 'Detections' has no attribute 'from_yolov8'

Code:

import cv2
import argparse

from ultralytics import YOLO
import supervision as sv
import numpy as np

ZONE_POLYGON = np.array([
    [0, 0],
    [0.5, 0],
    [0.5, 1],
    [0, 1]
])

def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="YOLOv8 live")
    parser.add_argument(
        "--webcam-resolution", 
        default=[1280, 720], 
        nargs=2, 
        type=int
    )
    args = parser.parse_args()
    return args

def main():
    args = parse_arguments()
    frame_width, frame_height = args.webcam_resolution

    cap = cv2.VideoCapture(0)
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, frame_width)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, frame_height)

    model = YOLO("best.pt")

    box_annotator = sv.BoxAnnotator(
        thickness=2,
        text_thickness=2,
        text_scale=1
    )

    zone_polygon = (ZONE_POLYGON * np.array(args.webcam_resolution)).astype(int)
    zone = sv.PolygonZone(polygon=zone_polygon, frame_resolution_wh=tuple(args.webcam_resolution))
    zone_annotator = sv.PolygonZoneAnnotator(
        zone=zone, 
        color=sv.Color.red(),
        thickness=2,
        text_thickness=4,
        text_scale=2
    )

    while True:
        ret, frame = cap.read()
        result = model(frame, agnostic_nms=True)[0]
        #print(result)
        detections = sv.Detections.from_yolov8(result)
        print(detections)
        print(model.model.names)
        
        labels = [
            f"{model.model.names[class_id]} {confidence:0.2f}"
            for _, confidence, class_id, _
            in detections
        ]
        break
        #labels=['face','person']
        frame = box_annotator.annotate(
            scene=frame, 
            detections=detections, 
            labels=labels
        ) 
        
        writer.write(frame)
        
        cv2.imshow("yolov8", frame)

        if (cv2.waitKey(30) == 27): # break with escape key
            break
            
    cap.release()
    writer.release()
    cv2.destroyAllWindows()
    

if __name__ == "__main__":
    main()

_Originally posted by @aniketkanse in https://github.com/ultralytics/ultralytics/issues/3683#issuecomment-1809119551_

**Comment by RizwanMunawar** [comment]
@aniketkanse, appreciate the detailed information you've shared. It appears that the error primarily originates from the supervision module. I recommend directing your queries to the Supervision Issue section for assistance.

Thanks
Ultralytics Team!
