### ISSUE TITLE
yolov8-pose

### ISSUE THREAD

**Issue by jdhewd** [ultralytics/ultralytics#6332]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can yolov8-pose be used to train a model to detect key points on two different types of objects at the same time?

**Comment by RizwanMunawar** [comment]
@jdhewd, absolutely! Feel free to utilize that!

For additional details, you may refer to our article: [Pose Estimation on Custom Data with Ultralytics YOLOv8](https://medium.com/@ultralytics/pose-estimation-on-custom-data-using-ultralytics-yolov8-ef63e103daea)
