### ISSUE TITLE
yolov8 local inference

### ISSUE THREAD

**Issue by vinirmith** [ultralytics/ultralytics#6333]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I already trained the YOLOv8 model using Google Colab. Right now, I want to use PyCharm and the [best.pt](http://best.pt/)
 file (trained previously in Google Colab) in order to develop a 'pothole manhole and speed breaker detection'. However, I cannot find the way to run the prediction in python code. can you please help me with this

**Comment by RizwanMunawar** [comment]
@vinirmith Appreciate the comprehensive details. Feel free to utilize the provided code to execute inference with the fine-tuned model for Pothole Detection.

```python
import cv2
from ultralytics import YOLO
from ultralytics.utils.plotting import Annotator
from pathlib import Path

# Load the YOLOv8 model
model = YOLO("path/to/best.pt")

# Path to Video
video_path = "path/to/video.mp4"

if not Path(video_path).exists():
    raise FileNotFoundError(f"Source path {video_path} does not exist.")

names = model.model.names
cap = cv2.VideoCapture(video_path)

while cap.isOpened():
    success, frame = cap.read()

    if success:
        results = model.predict(frame)
        boxes = results[0].boxes.xyxy.tolist()
        classes = results[0].boxes.cls.tolist()
        confidences = results[0].boxes.conf.tolist()
        annotator = Annotator(frame, line_width=2, example=str(names))

        # Iterate through the results
        for box, cls, conf in zip(boxes, classes, confidences):
            annotator.box_label(box, names[int(cls)], (255, 42, 4))

        cv2.imshow("YOLOv8 Detection", frame)
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break

    else:
        break

cap.release()
cv2.destroyAllWindows()
```

Hope this helps! Let me know if you have any additional questions.
Thanks
