### ISSUE TITLE
Training Custom Model Export Directory

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#6338]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

```python
from ultralytics import YOLO

# Load a model
model = YOLO('path/to/last.pt')  # load a partially trained model

results = model.train(data="X.yaml,project="Hello",name="123","save_dir="D:/XXX/")
```

Not saved according to this directory
`D:/XXX/Hello/123`

https://docs.ultralytics.com/modes/train/#arguments
This parameter is not included in the document parameters `save_dir`

How to specify the export model directory ?

**Comment by RizwanMunawar** [comment]
@monkeycc currently, we do not offer support for exporting the model to a custom path. An alternative approach is to save the PyTorch model file to the specific location where you intend to store the exported model.

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by lonngxiang** [comment]
> @monkeycc currently, we do not offer support for exporting the model to a custom path. An alternative approach is to save the PyTorch model file to the specific location where you intend to store the exported model.
> 
> Hope this helps! Let me know if you have any additional questions. Thanks

Follow-up support?
