### ISSUE TITLE
How to change the color of the predict bounding box？

### ISSUE THREAD

**Issue by hagrid-105** [ultralytics/ultralytics#634]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am a novice code learner, I have completed the object detection training process, I want to change the color of the prediction bounding box, how do I modify the code, thank you😀😀.

**Comment by bit-scientist** [comment]
@hagrid-105 you may modify `Color` class' `hexs` set in `ultralytics/yolo/utils/plotting`. Look through the code there to understand more.

**Comment by AyushExel** [comment]
@hagrid-105 you can just plot results for yourself in any color my just getting the prediction results( boxes and masks)

**Comment by hagrid-105** [comment]
> 
thank you! your suggestion is very useful

**Comment by pderrenger** [comment]
You're welcome, @hagrid-105! I'm glad I could help. If you have any more questions, feel free to ask. Happy coding! 😊
