### ISSUE TITLE
Unable to play saved video

### ISSUE THREAD

**Issue by AnnaFHub** [ultralytics/ultralytics#6346]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I searched and only found #790 which did not include a solution for my problem.

I am using yolov8x-pose for pose estimations on my videos. The input video type is mp4. 
I run the following lines in a Jupyter Notebook (used python version 3.10.13):
`from ultralytics import YOLO`

`model = YOLO("yolov8x-pose.pt")`

`path = "D:\\path\\to\\my\\video\\"`
`source = "videoName"`
`source_type= ".mp4"`

`results = model(path+source+source_type, show=True, conf=0.3, save=True, project=path, name=source+'_yoloV8')`

I also tried to have the video in the same folder as the notebook and to save the video in the default location without setting project and name. This created a runs folder and predictX folder in it, however the video inside is also not playable.
**Edit 2:** also tried with show=False, video is still not playable.

In the window that is visible while inference, the pose estimation and video frame are displayed correctly. This window does not close after the whole video was inferred, also using the close button does not close the window. I can only close it by aborting the currently running cell in the Jupyter Notebook.

A new folder named videoName_yoloV8 is created at D:\\path\\to\\my\\video\\ and it contains a file videoName.avi. Opening this video does not work, I tried multiple video players.
**Edit**: Video file size is 0 bytes.

I am working on a Laptop with Windows 11. GPU GTX 1050. I have cuda enabled.

1) Is there any known solution for this issue?

2) Also, is there a way to save the video as mp4 instead of avi?

**Comment by atmadeep** [comment]
If there's any possibility, the issue is still not resolved. I've checked https://github.com/ultralytics/ultralytics/issues/790 and I have the commit. However, I've tried multiple different videos, and none of the videos play. Cannot use CLI as it's a custom script utilizing "model.track" or "model,predict" API.
