### ISSUE TITLE
Error while training on coco (not coco128)

### ISSUE THREAD

**Issue by dmddmd** [ultralytics/ultralytics#635]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I use Python 3.9.4, ultralytics 8.0.18/19/20 and  run
```
model3=YOLO("yolov8n.yaml")
model3.train(data="coco.yaml", epochs=1)
```

gives 

Dataset 'coco.yaml' not found , missing paths ['C:\\Users\\User\\Documents\\datasets\\coco\\val2017.txt']

OSError: [WinError 123] The syntax of the file names, directory names or the disk label is wrong: 'https:\\github.com\\ultralytics\\yolov5\\releases\\download\\v1.0\\coco2017labels-segments.zip'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@glenn-jocher are you aware of this?

**Comment by bit-scientist** [comment]
@dmddmd did you try replacing `/` with `\` in the path like `C:/Users/User/Documents/datasets/coco/val2017.txt`? Also, it's very strange that you path has `Users/User`, check that too.

**Comment by dmddmd** [comment]
,User' is actually the name of the User. 
Replace where?

**Comment by bit-scientist** [comment]
@dmddmd , It looks like the program didn't find your `coco.yaml` file's location, so try specifying the whole path as an arg for `data` here `model3.train(data="coco.yaml", epochs=1)`.
