### ISSUE TITLE
An error occurred while I was running the screen detection function

### ISSUE THREAD

**Issue by Joel512089954** [ultralytics/ultralytics#6350]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

from ultralytics import YOLO

model = YOLO(r'F:/ultralytics-main/runs/detect/train-DNF/weights/best.pt', task='detect')
for result in model.predict(source='screen 1120 0 800 600', stream=True, save=True, device="cuda"):
    pass
There was an error when I ran the detection code：
Traceback (most recent call last):
  File "F:\ultralytics-main\predict.py", line 5, in <module>
    for result in model.predict(source='screen 1120 0 800 600', stream=True, save=True, device="cuda"):
  File "E:\anaconda3\envs\pytorch-gpu2.0-yolov8\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "F:\ultralytics-main\ultralytics\engine\predictor.py", line 243, in stream_inference
    self.setup_source(source if source is not None else self.args.source)
  File "F:\ultralytics-main\ultralytics\engine\predictor.py", line 220, in setup_source
    self.dataset = load_inference_source(source=source,
  File "F:\ultralytics-main\ultralytics\data\build.py", line 174, in load_inference_source
    dataset = LoadImages(source, imgsz=imgsz, vid_stride=vid_stride)
  File "F:\ultralytics-main\ultralytics\data\loaders.py", line 287, in __init__
    raise FileNotFoundError(f'{p} does not exist')
FileNotFoundError: screen 1120 0 800 600 does not exist

I am not sure if other methods are needed to implement this function, so I made modifications to the source code and the function can run normally

 ultralytics\data\build.py
 
 def check_source(source):
    """Check source type and return corresponding flag values."""
    webcam, screenshot, from_img, in_memory, tensor = False, False, False, False, False
    if isinstance(source, (str, int, Path)):  # int for local usb camera
        source = str(source)
        is_file = Path(source).suffix[1:] in (IMG_FORMATS + VID_FORMATS)
        is_url = source.lower().startswith(('https://', 'http://', 'rtsp://', 'rtmp://', 'tcp://'))
        webcam = source.isnumeric() or source.endswith('.streams') or (is_url and not is_file)
        # screenshot = source.lower() == 'screen'
        if 'screen' in source.lower():
            screenshot = source.lower()
        if is_url and is_file:
            source = check_file(source)  # download

### Environment

Ultralytics YOLOv8.0.208  Python-3.10.0 torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce GTX 1050, 4096MiB)
Setup complete  (8 CPUs, 15.9 GB RAM, 64.8/138.5 GB disk)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Joel512089954 hello! Thank you for your detailed bug report and willingness to help with submitting a PR.

Based on the error message you've provided, there seems to be an issue with recognizing the screen capture source. In the current implementation of the YOLOv8 predict function, it expects file paths or sources that are directly compatible, such as local images, video files, URLs, or webcam indexes. The 'screen' syntax you've used might not be supported directly, which is resulting in the `FileNotFoundError`.

It's constructive to hear that you've made local modifications to the source code and got it working. Your approach to modify the `check_source` function, allowing it to recognize 'screen' followed by geometry as a valid source, seems like a sensible solution to this problem.

However, for changes like this to be incorporated into the main codebase, they need to be carefully reviewed to ensure they align with the overall design and don't introduce unintended side effects. I encourage you to document your changes clearly and submit a PR for review. It's contributions from community members like you that help improve the ecosystem, and we greatly appreciate it!

Please ensure your PR follows the contribution guidelines, provide a clear explanation of the problem, and how your changes resolve it. The team will review your PR and provide feedback or accept it accordingly.

In the meantime, if users need to capture the screen for predictions, they should first utilize third-party software to save their screen capture as a video or image sequence and then use the saved files as the source input to the model.predict method.

Your enthusiasm and contribution to making YOLOv8 better are greatly appreciated, and we're thankful to have community members like you. Once again, thank you for your efforts and looking forward to your PR! If you have further questions or need guidance with your contribution, please consult the documentation at https://docs.ultralytics.com.
