### ISSUE TITLE
cv2.VideoCapture timeout

### ISSUE THREAD

**Issue by MoussaGRICHE** [ultralytics/ultralytics#6351]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,
I am working on a project about object tracking using yolov8 and rtsp video.

When the rtsp video is lost and befor getting this error messge "[tcp @ 0x203f5bf0] Connection to tcp://192.168.10.64:554?timeout=0 failed: No route to host", cv2.VideoCapture managed to recapture the rtsp video.

But after getting this message error, it is impossible to recapture the rtsp video.

In the case of loosing the camera for some minutes, I would like to know how could I increase the cv2.VideoCapture timeout in order recapture the rtsp video even when the loss time is long.

note that I am using opencv 4.8.1 on ubuntu 22.04

Thank you.

**Comment by RizwanMunawar** [comment]
@MoussaGRICHE To increase the cv2.VideoCapture timeout for RTSP video in case of connection loss, set `cv2.CAP_PROP_FPS` to a higher value. For example:

```python
import cv2

cap = cv2.VideoCapture("rtsp://192.168.10.64:554?timeout=0")
cap.set(cv2.CAP_PROP_FPS, 5000)

if not cap.isOpened():
    print("Error: Could not open camera.")
else:
    while True:
        ret, frame = cap.read()
        if not ret:
            print("Error: Failed to capture frame.")
            break
        # Your processing or tracking logic here

cap.release()
```

Adjust the timeout value according to your needs. This change extends the time OpenCV waits for the connection to be established after encountering an error.

Hope this helps! Let me know if you have any additional questions.
Thanks
