### ISSUE TITLE
CUDA out of memory error on inference

### ISSUE THREAD

**Issue by plashchynski** [ultralytics/ultralytics#636]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

The inference of a video file sometimes ends up in the CUDA out of memory error on 16 GB GPU machine. I've checked the nvidia-smi command output and noticed that the used CUDA memory is constantly growing while inference code process each new frame. It looks like a memory leak.

The code:
```python
from ultralytics import YOLO
model = YOLO("train16/weights/best.pt")
model.predict(source="20211218_124322000_iOS.MOV", save=True, verbose=True)
```

The output (truncated in the middle):
```
Ultralytics YOLOv8.0.20 🚀 Python-3.7.10 torch-1.13.1+cu117 CUDA:0 (Tesla T4, 15110MiB)
YOLOv8n-seg summary (fused): 195 layers, 3259039 parameters, 0 gradients, 12.0 GFLOPs
video 1/1 (1/2647) /tmp/20211218_124322000_iOS.MOV: 640x384 1 circle, 1 circle2, 1 mask1, 1 mask2, 2 mask3, 19.7ms
video 1/1 (2/2647) /tmp/20211218_124322000_iOS.MOV: 640x384 1 circle, 1 circle2, 1 mask1, 1 mask2, 2 mask3, 9.9ms
video 1/1 (3/2647) /tmp/20211218_124322000_iOS.MOV: 640x384 1 circle, 1 circle2, 1 mask1, 1 mask2, 2 mask3, 9.6ms
video 1/1 (4/2647) /tmp/20211218_124322000_iOS.MOV: 640x384 1 circle, 1 circle2, 1 mask1, 1 mask2, 2 mask3, 10.3ms
........SKIPED........
video 1/1 (2082/2647) /tmp/20211218_124322000_iOS.MOV: 640x384 1 circle, 1 circle2, 1 mask1, 1 mask2, 2 mask3, 10.2ms
video 1/1 (2083/2647) /tmp/20211218_124322000_iOS.MOV: 640x384 1 circle, 1 circle2, 1 mask1, 1 mask2, 2 mask3, 9.4ms
video 1/1 (2084/2647) /tmp/20211218_124322000_iOS.MOV: 640x384 1 circle, 1 circle2, 1 mask1, 1 mask2, 2 mask3, 10.2ms
---------------------------------------------------------------------------
OutOfMemoryError                          Traceback (most recent call last)
<ipython-input-6-4c7e4229a494> in <module>
----> 1 model.predict(source="/tmp/20211218_124322000_iOS.MOV", save=True, verbose=True)

/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     25         def decorate_context(*args, **kwargs):
     26             with self.clone():
---> 27                 return func(*args, **kwargs)
     28         return cast(F, decorate_context)
     29 

/opt/conda/lib/python3.7/site-packages/ultralytics/yolo/engine/model.py in predict(self, source, stream, verbose, **kwargs)
    144         else:  # only update args if predictor is already setup
    145             self.predictor.args = get_cfg(self.predictor.args, overrides)
--> 146         return self.predictor(source=source, stream=stream, verbose=verbose)
    147 
    148     @smart_inference_mode()

/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     25         def decorate_context(*args, **kwargs):
     26             with self.clone():
---> 27                 return func(*args, **kwargs)
     28         return cast(F, decorate_context)
     29 

/opt/conda/lib/python3.7/site-packages/ultralytics/yolo/engine/predictor.py in __call__(self, source, model, verbose, stream)
    156             return self.stream_inference(source, model, verbose)
    157         else:
--> 158             return list(self.stream_inference(source, model, verbose))  # merge list of Result into one
    159 
    160     def predict_cli(self):

/opt/conda/lib/python3.7/site-packages/ultralytics/yolo/engine/predictor.py in stream_inference(self, source, model, verbose)
    203 
    204                 if verbose or self.args.save or self.args.save_txt or self.args.show:
--> 205                     s += self.write_results(i, self.results, (p, im, im0))
    206 
    207                 if self.args.show:

/opt/conda/lib/python3.7/site-packages/ultralytics/yolo/v8/segment/predict.py in write_results(self, idx, results, batch)
     70             colors=[colors(x, True) for x in det.cls],
     71             im_gpu=torch.as_tensor(im0, dtype=torch.float16).to(self.device).permute(2, 0, 1).flip(0).contiguous() /
---> 72             255 if self.args.retina_masks else im[idx])
     73 
     74         # Segments

/opt/conda/lib/python3.7/site-packages/ultralytics/yolo/utils/plotting.py in masks(self, masks, colors, im_gpu, alpha, retina_masks)
    107 
    108         inv_alph_masks = (1 - masks * alpha).cumprod(0)  # shape(n,h,w,1)
--> 109         mcs = (masks_color * inv_alph_masks).sum(0) * 2  # mask color summand shape(n,h,w,3)
    110 
    111         im_gpu = im_gpu.flip(dims=[0])  # flip channel

OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 14.76 GiB total capacity; 13.29 GiB already allocated; 5.75 MiB free; 13.73 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### Environment

Ultralytics YOLOv8.0.20 🚀 Python-3.7.10 torch-1.13.1+cu117 CUDA:0 (Tesla T4, 15110MiB)
YOLOv8n-seg summary (fused): 195 layers, 3259039 parameters, 0 gradients, 12.0 GFLOPs

on 4 vCPU + 16 GiB + 1 GPU AWS ml.g4dn.xlarge instance

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@plashchynski yes the output will keep growing as the result is a list of all outputs. That is the default behavior. But to tackle this problem we've provided an optional `stream` mode. Just pass `stream=True` and instead of returning a list, it'll return a generator. See the example and details here - https://docs.ultralytics.com/predict/
Let me know if this solves your problem :)

**Comment by plashchynski** [comment]
Hi @AyushExel, but ```save=True``` doesn't work with ```stream=True```. It won't save results. It will return the generator instead. So I think with ```save=True```, it's reasonable to assume that it should use streaming under the hood to not overflow the memory and to save the result, isn't it?

**Comment by AyushExel** [comment]
@plashchynski I just checked save=True is working with stream=True. Can you provide a reproducible example where its not saving?
This seems to work for me:
```
model = YOLO("yolov8n.pt")
res = model("ultralytics/assets", stream=True, save=True, verbose=True)
for _ in res:
    pass
```

**Comment by plashchynski** [comment]
Hi @AyushExel thank you for the snippet. It's a bit counterintuitive, but works anyway.

**Comment by AyushExel** [comment]
@plashchynski I didn't get you, what is counterintuitive about generators? I'd like to fix it

**Comment by plashchynski** [comment]
@AyushExel I'd expect that ```save=True``` option would process and save results without any additional parameters and code. I think it would use streaming under the hood. It's a bit counterintuitive that I need to pass additional parameters and code to avoid an error. I'd expect that ```stream=True``` is needed if I want to process the result myself, and not for the model to simply save the annotated result. Thank you.

**Comment by AyushExel** [comment]
@plashchynski it's not needed to save. Only save=True is needed to save. It works independently

**Comment by plashchynski** [comment]
@AyushExel yes, but ```save=True``` without additional parameters and code causes ```CUDA out of memory``` with a relatively small video file (3000 frames) on a relatively big GPU w (16 GB memory). This is confusing.

**Comment by AyushExel** [comment]
okay. This is the usage:
- stream = True for getting generators instead of a list.
- save = True for saving outputs.
Both of them can be used independently. Another thing that I can think of is to suggest users to turn on stream=True when a video input is encountered

**Comment by glenn-jocher** [comment]
Great solution! Using `stream=True` and iterating the generator processes frames efficiently while saving results. This aligns with the [Predict mode documentation](https://docs.ultralytics.com/modes/predict/#streaming-mode) recommendations for memory management with videos/large datasets. Thanks for sharing your working approach! 🚀
