### ISSUE TITLE
Table zebra in dark mode has light background.

### ISSUE THREAD

**Issue by piotratlz** [ultralytics/ultralytics#6360]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

As you can see in the table below across all the docs zebra in dark mode has light background which makes text unreadable.

<img width="606" alt="image" src="https://github.com/ultralytics/ultralytics/assets/130975307/1011b161-e654-4acf-b0ab-1b8105b2a7c7">

### Environment

N/A

### Minimal Reproducible Example

1. Enter https://docs.ultralytics.com/usage/cfg/#train
2. Enable dark mode

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@piotratlz @sergiuwaxmann @Burhan-Q great news 😃! Your original issue may now be resolved ✅ in PR #6365. Here's the fixed docs now:

<img width="1993" alt="Screenshot 2023-11-15 at 16 15 38" src="https://github.com/ultralytics/ultralytics/assets/26833433/26318d0e-aa80-4bd9-a0b8-05b842cfb36d">

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!thank you for the bug report!

**Comment by piotratlz** [comment]
Hi @glenn-jocher thank you for response. 
Unfortunately I am still able to see no update in zebra
<img width="1025" alt="image" src="https://github.com/ultralytics/ultralytics/assets/130975307/ea5ed288-70be-41cb-b796-573f25d28e69">

**Comment by glenn-jocher** [comment]
Hello @piotratlz,

I apologize for the inconvenience caused. It seems there might have been a delay or issue in the changes propagating to the live documentation. I assure you that the team is aware of this issue, and we are working to ensure that the documentation styling is optimal for all our users, whether they prefer light or dark mode.

In the meantime, could you please try clearing your browser cache and refreshing the docs page to see if that resolves the issue? Sometimes, cached pages can prevent updates from showing immediately.

If the problem persists after this, rest assured that it has been noted and a fix should be visible soon as part of our continuous effort to improve the documentation.

Your understanding and patience are much appreciated. Please reach out if you have any further issues or questions.

**Comment by Burhan-Q** [comment]
Just checked with non-primary browser in private mode and tables are looking good
![image](https://github.com/ultralytics/ultralytics/assets/62214284/70ea72a1-ac13-4921-9612-5116f673f81f)

**Comment by piotratlz** [comment]
Hi @glenn-jocher, thank you for the response. Looks fine now, thank you! :)

**Comment by glenn-jocher** [comment]
You're welcome, @piotratlz! I'm glad to hear that everything is displaying correctly now. 😊 If you encounter any more issues or have further questions as you continue to use YOLOv8, please don't hesitate to reach out. Your feedback helps us improve. Happy detecting! 🚀🎉
