### ISSUE TITLE
setting dataset path before the first run (docker)

### ISSUE THREAD

**Issue by Liquidmasl** [ultralytics/ultralytics#6367]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have some issues describing my problem. 

When ultralytics is imported the first time, it just creates a settings yaml in the user folder (which, in my opinion is already an issue)
the dataset folder is then set to the current working directory + "datasets"
Then, when training, the folder descriptions that are in the training yaml are somewhat ignored, if they are relative, its not relative from the yaml file, but kinda.. post fixed to the default dataset path in the settings file.

Its easy enough to change the settings file manually after the first run, but its really annoying to do so when switching machines, or envionments, especially in docker. 

So i thought i can just change the settings programmatically. But that does not work either. the settings file is read or created on inport, and any edit to settings is not updated into memory. 
So thats fine on a local machion, on the second run it will work, but that again does not work in docker. 

So a few things i dont understand. Why is there even any settings file in the user directoty? why not store it in the working directory? 
and why is the dataset_dir in the settings folder absolute, while weights_dir and runs_dir is relative?

And how can i just please run this in docker without writing a script that fixes this path?

If you say: well just place your dataset in a folder thats named datasets, so the path is correct:
I tried that. then it want the data in datasets/datasets, I also changed the relative paths in the training yaml, and moved the training yaml around. 
I only really get it to run when i manually change the settings file after the first run. but this is just not an option in docker. 

I will have to change the settings directory via environment variable, and manually write the settings file before the first start.
this is incredibly cumbersum and i just dont see why its nescessary. 
I think it would all clear up if the dataset_dir in the settings.yaml is relative, like the other paths.

**Comment by glenn-jocher** [comment]
@Liquidmasl hello,

Thank you for providing detailed feedback about your experience with setting up the dataset path, especially when working within a Docker environment.

I understand the configuration can be somewhat cumbersome and might not seem intuitive initially. The settings file is intended to provide a persistent configuration that is user-specific and survives across sessions, which is particularly useful for individuals working on their local machines. However, this does seem to pose challenges when deploying within more ephemeral environments such as Docker.

Concerning the handling of relative paths and default dataset directory configuration, I'll take your suggestions back to the team for consideration in future updates. Meanwhile, if the settings require programmatic modification on each run, and it's not feasible to manually change the settings file, you might consider scripting the generation or alteration of the settings file as part of your Docker container's entrypoint or command. I realize this is not the most elegant solution and can be frustrating when scaling across different environments.

As for the dataset directory, its absolute path in the settings file is intended to ensure consistency across runs. However, I can see how standardizing the behavior of all paths in the settings file to be relative to a certain directory would simplify matters, especially when dealing with containerized deployments.

Please note that we are continuously working to improve the flexibility and user experience of our models and tools. Your specific use case provides valuable insight and highlights areas where we can further enhance the usability of our software.

In the meantime, for detailed guidance on suggested practices and potential workarounds, you might find our documentation (https://docs.ultralytics.com) helpful, which contains a wealth of information that might address some of your concerns.

I apologize for the inconvenience and appreciate your patience as we strive to make the Ultralytics YOLOv8 more adaptable to various deployment scenarios such as yours. Your feedback is instrumental in driving our efforts to improve.

**Comment by glenn-jocher** [comment]
@Liquidmasl you can update settings to any values you'd like. See https://docs.ultralytics.com/quickstart/#ultralytics-settings

You can set datasets dir to either a relative or absolute path, whichever you prefer.

```bash
 yolo settings
💡 Learn about settings at https://docs.ultralytics.com/quickstart/#ultralytics-settings
Printing '/Users/glennjocher/Library/Application Support/Ultralytics/settings.yaml'

settings_version: 0.0.4
datasets_dir: /Users/glennjocher/PycharmProjects/datasets
weights_dir: /Users/glennjocher/PycharmProjects/ultralytics/weights
runs_dir: /Users/glennjocher/PycharmProjects/ultralytics/runs
uuid: ad0ee59a08709c231a955095a01f1cb1fabbafab3bfffc2633bdc4fa64c17016
sync: true
api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true

```

**Comment by Liquidmasl** [comment]
> @Liquidmasl you can update settings to any values you'd like. See https://docs.ultralytics.com/quickstart/#ultralytics-settings
> 
> You can set datasets dir to either a relative or absolute path, whichever you prefer.

Ah shucks, i missed the settings.reset() method
I saw that most of the settings are set on import, and did not see a way to "reimport" easily. but yeah this makes this easier!

I still think when the settings file is created autoamtically on first run, all 3 paths should be automatically set as relative paths, and not 2 as relative and 1 as absolute.
Especially because I think the default absolute path will be wrong most of the times! 

Thanks for the quick response!
