### ISSUE TITLE
 Box overlapping problem in one object

### ISSUE THREAD

**Issue by jungms4536** [ultralytics/ultralytics#637]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

It was trained through custom data.
In the process of detecting through the learned model, multiple boxes overlap in one object, resulting in a result.
I don't know what part it is for.

### Additional

![image](https://user-images.githubusercontent.com/82021950/214724953-e1ac7b67-4212-4fcd-9acd-cb5399f8e0da.png)

**Comment by AyushExel** [comment]
The problem is most likely related to the dataset or a result of bad training.

**Comment by jungms4536** [comment]
Labeling in the dataset was done with fish eyes and mouth margins.
Are you saying that labeling could be a problem?

**Comment by bit-scientist** [comment]
@jungms4536 inconsistent labeling could cause such outcomes. Could you plot your labels (`bbox`) on some of the respective images in train set and see if they are as you intended?
