### ISSUE TITLE
Docs - Checkmark for Dark Mode

### ISSUE THREAD

**Issue by Burhan-Q** [ultralytics/ultralytics#6373]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

[ Pedantic ]

## Documentation Models Pages - Supported Modes Table

- Currently uses `:heavy_check_mark` emoji ✔ (difficult to see/read in Docs dark theme)

![image](https://github.com/ultralytics/ultralytics/assets/62214284/3c1b1121-dc72-4888-bf61-2d4c81f3f8ab)
![image](https://github.com/ultralytics/ultralytics/assets/62214284/b3b4ba53-3175-4b53-b45f-2e8a20d5cbb4)

- Proposed change: `:white_check_mark` emoji ✅ (easier to see in Docs dark+light theme)

![image](https://github.com/ultralytics/ultralytics/assets/62214284/e2c1707f-0243-4150-9486-73a4064181aa)
![image](https://github.com/ultralytics/ultralytics/assets/62214284/5adc7505-e060-4d22-bf9f-86d081a66701)

### Use case

Used anytime someone enables Dark Theme for Documentation page.

### Additional

+ would like to see emoji centered, but that's perhaps too pedantic 😅

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Burhan-Q ah! This is a great idea. We should definitely do this. Thanks for bringing it up. I'll try to do a search and replace in my current `dev` branch PR.

**Comment by glenn-jocher** [comment]
@Burhan-Q @kalenmike @sergiuwaxmann @RizwanMunawar we need a new issue Label called 'Great Idea' haha

**Comment by glenn-jocher** [comment]
@Burhan-Q ok this is implemented now in https://github.com/ultralytics/ultralytics/pull/6407/commits/14af8420481293f13a9bddd4910c1d05651d9759

Maybe I'll update the red X also to an emoji to standardize.

**Comment by glenn-jocher** [comment]
@Burhan-Q red X updated in https://github.com/ultralytics/ultralytics/pull/6407/commits/40c540f8a44f8ead2bdfe813a144f88385dc89ad
