### ISSUE TITLE
How to use multiple GPUs when training with Ultralytics Hub

### ISSUE THREAD

**Issue by jansdhillon** [ultralytics/ultralytics#6374]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello all,

First, the training experience with YOLOv5/v8 has been great. I've been able to train several models on several different datasets using the v8 CLI and Python API. 

I see that the Ultralytics HUB lets you train and upload models, however, the issue I am running into is the usage of multiple GPUs. I have two RTX A4000s, each with about 17GB of RAM. The dataset I am trying to train is about 10k images, and I keep getting CUDA out of memory errors on Colab, so I tried the "Bring your own agent" option to train it locally, however, I am unable to use both of my GPUs. 

```
>>> from ultralytics import YOLO, checks, hub
>>> checks()
Ultralytics YOLOv8.0.210 🚀 Python-3.9.18 torch-2.1.0 CUDA:0 (NVIDIA RTX A4000, 16376MiB)
Setup complete ✅ (36 CPUs, 62.6 GB RAM, 108.9/1006.9 GB disk)
>>> checks(device=[0,1])
Ultralytics YOLOv8.0.210 🚀 Python-3.9.18 torch-2.1.0 CUDA:0 (NVIDIA RTX A4000, 16376MiB)
                                                      CUDA:1 (NVIDIA RTX A4000, 16376MiB)
Setup complete ✅ (36 CPUs, 62.6 GB RAM, 108.9/1006.9 GB disk)
>>> hub.login('xxxxx')
Ultralytics HUB: Authenticated ✅
>>> model = YOLO('https://hub.ultralytics.com/models/xxx', device=[0,1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'device'
>>> model = YOLO('https://hub.ultralytics.com/models/xxxx')
Ultralytics HUB: View model at https://hub.ultralytics.com/models/xxxx 🚀
>>> model.train(device=[0,1])
WARNING ⚠️ using HUB training arguments, ignoring local training arguments.
Ultralytics YOLOv8.0.210 🚀 Python-3.9.18 torch-2.1.0 CUDA:0 (NVIDIA RTX A4000, 16376MiB)
```

As shown, both the GPUs are available, and when training normally, I can use both. However, we see that choosing the devices is overwritten when training with Ultralytics HUB. Because of this, when the training starts, I get 
```
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Which is weird because 

```
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      12.5G      1.451      3.727      1.489        983        640:   1%|          | 2/178 [00:02<03:46,  1.29s/it]
      
```

It looks like the first epoch (where it crashes) is only using about 12.5G, which should be fine for a single GPU anyways. I am using WSL so I'm not sure if that has something to do with how much memory is available.

The reason I want to train it while connected to Ultralytics HUB is because I want to be able to upload my model. Is there any way to use multiple GPUs when doing it this way?

Thank you.

### Additional

As a follow up, is there a way to upload a YOLO model to Ultralytics HUB without training it this way?

**Comment by glenn-jocher** [comment]
@jansdhillon hello,

Thank you for your positive feedback and for sharing your experience with YOLOv5/v8. It's great to hear that you've been having a good training experience across multiple datasets.

Regarding the use of multiple GPUs during training with Ultralytics HUB, you're correct that the "Bring your own agent" feature allows for local training. Using multiple GPUs can be managed through the PyTorch Data Parallel or Distributed Data Parallel functionality. However, let me clarify some points to help you leverage your dual RTX A4000 setup.

You observed that the `device` argument isn't working as expected. When initiating a model via the `YOLO` class for training with the HUB, you should be able to specify the GPUs using the checks function. When you start the training process, if you are still experiencing CUDA out of memory issues, it may be related to other factors, such as the model size, input image resolution, or the batch size being too large for the available memory on a single GPU.

For WSL, it's possible that the way it handles GPU memory could be limiting the memory available to your process. I recommend double-checking the WSL configuration, ensuring that you allocate sufficient memory and resources for your training task.

Now, regarding your second query about uploading a YOLO model to the Ultralytics HUB without using the "Bring your own agent" method: We currently don't support direct model uploads to the HUB. The preferred method is to train your model using our provided system and then the trained model gets automatically uploaded. We strive to enhance the user experience constantly, so please keep an eye out for future updates that might introduce new functionalities.

If you require more detailed, step-by-step guidance or troubleshooting for the memory issues or any other training concerns, please refer to the YOLOv8 documentation at https://docs.ultralytics.com for extensive explanations and instructions on how to effectively use the functionalities of YOLOv8, including multi-GPU training setups.

**Comment by jansdhillon** [comment]
Hi @glenn-jocher, thanks for your swift response. 

I tried specifying the GPUs in the `checks()` function, and it looks like it accepts it:

```
//with only device 0
>>> checks()
Ultralytics YOLOv8.0.210 🚀 Python-3.9.18 torch-2.1.0 CUDA:0 (NVIDIA RTX A4000, 16376MiB)
Setup complete ✅ (36 CPUs, 62.6 GB RAM, 108.9/1006.9 GB disk)

//with both
>>> checks(device=[0,1])
Ultralytics YOLOv8.0.210 🚀 Python-3.9.18 torch-2.1.0 CUDA:0 (NVIDIA RTX A4000, 16376MiB)
                                                      CUDA:1 (NVIDIA RTX A4000, 16376MiB)
Setup complete ✅ (36 CPUs, 62.6 GB RAM, 108.9/1006.9 GB disk)
```

However, the issue is this seems to be overwritten, even when I specify it again in the `model.train()` function:

```
>>> model.train(device=[0,1])
WARNING ⚠️ using HUB training arguments, ignoring local training arguments.
Ultralytics YOLOv8.0.210 🚀 Python-3.9.18 torch-2.1.0 CUDA:0 (NVIDIA RTX A4000, 16376MiB)
```

It is only using device 0 for training.

It's really not the end of the world, it's just because I am experimenting with a dataset from Roboflow which has an existing (Roboflow 2) model, so I cannot upload my new YOLOv8 model there to use with the inference API, so I wanted to try out the Ultralytics one.

**Comment by glenn-jocher** [comment]
@jansdhillon oh I see. Yes this is because HUB outbound trainings do not support DDP yet. We are fixing this first on inbound trainings, a new feature that lets you log in locally and train models to HUB. This should be released before the end of the year. 

In the meantime I believe HUB is restricted to single-GPU training.

**Comment by jansdhillon** [comment]
@glenn-jocher Gotcha. Well thanks anyways. I am looking forward to the new features.

**Comment by glenn-jocher** [comment]
You're welcome, @jansdhillon! It's great to hear your anticipation for the upcoming features. In the meantime, if you have any more questions or need further support with single-GPU training or any other aspect of using YOLOv8, please don't hesitate to reach out.

We appreciate your patience and understanding as we work on enhancing the functionalities and user experience of our platform. Your feedback is invaluable to us. Happy training! 🚀
