### ISSUE TITLE
RuntimeError: Allocation is out of device memory on current platform

### ISSUE THREAD

**Issue by samarthDeGirum** [ultralytics/ultralytics#6375]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I am trying to offload YOLOv8 training to an Intel ARC GPU. When I try to run the  code attached, I am seeing **RuntimeError: Allocation is out of device memory on current platform.**

Output of the console logs (seems like Line 227 in ultralytics/utils/ops is causing this issue. Any help would be appreciate 
<img width="1079" alt="Screenshot 2023-11-15 at 11 40 42 AM" src="https://github.com/ultralytics/ultralytics/assets/105819481/d3d96049-4752-4f37-8615-dbd9d43a63ef">

### Environment

Ultralytics YOLOv8.0.210 🚀 Python-3.10.12 torch-2.0.1a0+cxx11.abi CPU (13th Gen Intel Core(TM) i5-13600K)
Setup complete ✅ (20 CPUs, 15.4 GB RAM, 98.9/457.4 GB disk)

OS                  Linux-5.19.0-46-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 15.36 GB
CPU                 13th Gen Intel Core(TM) i5-13600K
CUDA                None

### Minimal Reproducible Example

```python
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)
device_str = "xpu:0"
device = torch.device(device_str)

model = model.to(device)
check_amp(model)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@samarthDeGirum hello and thank you for reaching out with your issue regarding the "RuntimeError: Allocation is out of device memory" error you encountered during YOLOv8 training.

It appears that your Intel ARC GPU is running out of memory during the allocation required by the training process. This is a common issue when training deep learning models, often related to the size of the model or the input data, the batch size, or the specific hardware limitations.

Here are a few suggestions that might help you resolve this issue:

1. **Batch Size**: The first step you could take is to decrease the batch size during training. A smaller batch size requires less memory and may allow your training to fit within the available device memory.

2. **Model Complexity**: If you are using a large and complex model, you might want to try a lighter model which has fewer parameters and would require less memory.

3. **Input Data**: Check the size of the input data being used. Large input sizes can lead to high memory usage. You could resize your images to a smaller dimension if possible.

4. **Gradient Accumulation**: If lowering the batch size impacts the training stability, you could also consider using gradient accumulation to effectively train with a larger batch size without increasing memory usage.

5. **Mixed Precision Training**: If not already in use, mixed precision training can significantly reduce memory usage while also providing a speedup in training. It uses a mix of float16 and float32 to utilize memory more efficiently.

6. **Hardware Limits**: Ensure that no other processes are consuming GPU memory. If needed, you can close other applications or free up memory by stopping other computations on the GPU.

7. **Software Versions**: Ensure that the drivers for your GPU are up to date and that you are using the latest stable versions of PyTorch and other relevant libraries, as there may be memory efficiency improvements in newer versions.

For more detailed instructions and best practices for model training, refer to our official documentation at https://docs.ultralytics.com. If after following the suggestions your issue persists, consider providing more detailed information about your training configuration and the steps leading up to the issue. This will enable us to assist you more effectively.

Lastly, as this is a memory-related issue that can be specific to the hardware, it is also worth checking the Intel ARC GPU's documentation and support forums for any known issues or recommendations regarding deep learning workloads.

Best of luck with your training, and please feel free to reach out if you have any more questions or concerns!

**Comment by samarthDeGirum** [comment]
Hi @glenn-jocher, thank you for your response. If you see the code I have attached to reproduce this example, this is only calling the check_amp function of the ultralytics repository, and is not going through a full-training pipeline. The part where this code leads to an error is running inference on a bus.jpg image hosted in the Ultralytics repository itself. Any ideas what could be causing this?
