### ISSUE TITLE
How to run a prediction on CPU (instead of GPU) using YOLO command

### ISSUE THREAD

**Issue by tjasmin111** [ultralytics/ultralytics#6377]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm using the Yolo predict mode to run inference on a video, which by default uses the GPU. Is there a way to force it running on CPU?

`yolo task=detect mode=predict model=best.pt source=video.mp4`

I want to run a comparison of the inference speed on GPU vs CPU.

**Comment by PaVaNTrIpAtHi** [comment]
try this device="CPU"

**Comment by RizwanMunawar** [comment]
@tjasmin111, if you wish to compare the inference results on both GPU and CPU, you can utilize the provided command-line interface (CLI) commands.

**For CPU:**
```yolo task=detect mode=predict model=best.pt source=video.mp4 device="cpu"```

**For GPU:**
```yolo task=detect mode=predict model=best.pt source=video.mp4 device="0"```

Hope this helps! Let me know if you have any additional questions.
Thanks
