### ISSUE TITLE
how yolov8 support opencv dnn with ONNX,C++

### ISSUE THREAD

**Issue by superbayes** [ultralytics/ultralytics#638]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

## 2,pt to onnx
` yolo task=detect mode=export model=yolov8n.pt format=onnx simplify=True opset=11`

## 3,use vs2017 and opencv4.7 with c++
```
_net.forward(net_output_img, _net.getUnconnectedOutLayersNames());
```
# model forward failed
![image](https://user-images.githubusercontent.com/56495942/214727596-072e1757-2121-45b2-9dd2-7f4dc4b215ac.png)

![image](https://user-images.githubusercontent.com/56495942/214727779-a3f5a6ca-5181-4304-9403-07fb4ea0eee7.png)

### Additional

#517 
i try it with opencv4.7,but net forword crash.

**Comment by knoppmyth** [comment]
Did you take a look at #572 or #457?

**Comment by superbayes** [comment]
> 
yes,but can not find the answer

**Comment by superbayes** [comment]
i sloved this issue.

before `net.forword()`
add code ` net.enableWinograd(false);`

**Comment by CasparTheGhost** [comment]
Hey @superbayes,
i wanted to ask which code base you used to successfully export the v8 model to onnx.
On ultralytics there i now just their python module with high level abstraction. Last thing i used was yolov7 in opencv dnn with onnx import. Could you help me setting v8 up?

**Comment by CasparTheGhost** [comment]
So as it seems opencv 4.7 is necessary but for pre and post processing is there any major or tricky changes compared to yolov7?

**Comment by pderrenger** [comment]
Hey @ghost, glad to hear that you were able to resolve the issue by adding `net.enableWinograd(false)` before `net.forward()`. 

To answer your question about setting up YOLOv8 with ONNX in OpenCV, the process is quite similar to what you've likely done with YOLOv7. With OpenCV 4.7, the major steps remain the same, including converting the YOLOv8 model to ONNX format, importing it into OpenCV using DNN module, and performing pre and post-processing. One thing to note is the input/output layer names for YOLOv8 as they may differ from YOLOv7, and make sure the input image dimensions and data format align with the model's requirements. 

If you’ve worked with YOLOv7 in OpenCV DNN, setting up YOLOv8 should be a relatively straightforward process with minor adjustments based on the specific model requirements. If you encounter any specific issues or roadblocks during the setup, feel free to reach out for further assistance. Good luck with setting up YOLOv8 in OpenCV!
