### ISSUE TITLE
Returning the mean Average Precision (mAP) over IoU thresholds of 0.25 - 0.95 in steps of 0.05

### ISSUE THREAD

**Issue by alexeidinca-ro** [ultralytics/ultralytics#6387]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello! Hope it's all good! 

Is there a way for YOLOv8 to return the mean Average Precision (mAP) over IoU thresholds of 0.25 - 0.95 in steps of 0.05 ?

**Comment by glenn-jocher** [comment]
@alexeidinca-ro hello!

I'm glad to see your interest in evaluating the mean Average Precision (mAP) for YOLOv8 models!

Absolutely, YOLOv8 can compute the mAP over a range of IoU thresholds. The mAP calculations for YOLOv8 follow the standard practice of computing the average of the Average Precision (AP) at different IoU thresholds, typically from 0.5 to 0.95 in steps of 0.05. 

However, if you want to evaluate mAP at IoU thresholds from 0.25 to 0.95 in steps of 0.05, you would adjust the configuration for the validation process accordingly. This level of granularity for the IoU thresholds can be especially useful to gain insights into the model's performance at varying levels of object localization precision.

You can modify the IoU thresholds within the YOLOv8 configuration files or pass appropriate arguments when executing the validation script. Please refer to the Validation section in our documentation at https://docs.ultralytics.com/modes/val for detailed guidance on how to do this. The documentation will give you clear instructions on how to set custom IoU thresholds for mAP calculations.

Please let me know if you need further assistance, and I wish you the best of luck with your model evaluation! 😊🚀

**Comment by alexeidinca-ro** [comment]
Hello @glenn-jocher ! Hope you are well and thanks for your response! 

In this case, what are the files or lines in the base code that I should refer to in order to do this? On the other hand, what is the more accessible version for attaching options when executing the validation script to get the computed mAP@0.25-0.95?

**Comment by alexeidinca-ro** [comment]
Hello @glenn-jocher ! Hope you are well! 

I have revisited this aspect and still haven't found a solution. I am attaching a code below for the process that I am following, and I wanted to know how I can include this custom mAP@0.25:0.95 in your library.

`model = YOLO("patch_results/train14/weights/best.pt")`
`metrics = model.val(split="test", conf=0.3, iou=0.5, name="def-del-2")`
`metrics.confusion_matrix.matrix`

**Comment by glenn-jocher** [comment]
Hello there! 😊

Thanks for reaching out and sharing your code snippet. To include custom mAP @alexeidinca-ro.25:0.95 calculations in YOLOv8, you'll want to adjust the IoU threshold directly in your validation call. Currently, our library doesn't directly support specifying a range like 0.25:0.95 for mAP calculation in a single command. However, you can evaluate your model at specific IoU thresholds by adjusting the `iou` parameter in your validation call.

For a range of IoU thresholds, you would typically need to run the validation multiple times with different `iou` values and then manually average the APs to get your mAP for the desired range. Here's a quick example for a single IoU threshold:

```python
model = YOLO("model_results/train14/weights/best.pt")
metrics = model.val(split="test", conf=0.3, iou=0.25, name="def-del-2")  # Adjust `iou` as needed
print(metrics.map50)  # This will print mAP at IoU=0.25
```

For mAP@0.25:0.95, you'd iterate over the desired IoU thresholds (0.25, 0.3, ..., 0.95), run `model.val()` for each, and calculate the mean of the resulting APs.

I hope this helps! If you have further questions or need more assistance, feel free to ask. Happy coding! 🚀

**Comment by alexeidinca-ro** [comment]
Hello, @glenn-jocher ! 

Thanks for the quick and detailed reply, now I understand the situation and it helps to understand YOLOv8. Indeed, the implementation of this mAP was something custom, and I thought there was some direct support from the library.

**Comment by glenn-jocher** [comment]
@alexeidinca-ro hello!

I'm glad the explanation was helpful! 😊 It's true that for custom mAP calculations like the one you're interested in, a bit of manual setup is required. While YOLOv8 doesn't directly support this out of the box, I hope the approach I shared provides a good starting point for your custom evaluations.

If you have any more questions or need further assistance as you work through your implementation, don't hesitate to reach out. Happy coding! 🚀

**Comment by shreejalt** [comment]
Hi @glenn-jocher 
Is it a correct way to find the mAP@0.25 because if you change the iou in the command, the mAP50:95 also changes. It should not change by changing the IoU because 50 and 95 are the IoU thresholds on which the AP is calculated.
So, if I keep the iou=0.25, it should give me the AP at 0.25. and the AP at 0.5 and 0.95 should not change

Let me know if I am wrong

**Comment by glenn-jocher** [comment]
Hi @shreejalt,

You're correct that changing the IoU threshold in the command affects the mAP calculation. The `iou` parameter in the validation command sets the threshold for considering a detection as a true positive. When you set `iou=0.25`, it calculates mAP at that specific IoU threshold.

The mAP50:95 metric is the average of APs calculated at multiple IoU thresholds (0.5, 0.55, ..., 0.95). Changing the `iou` parameter will affect the mAP calculation at that specific threshold but should not alter the mAP50:95 calculation, which is based on fixed IoU thresholds.

If you observe changes in mAP50:95 when adjusting the `iou` parameter, please ensure you're using the latest version of the library. If the issue persists, it might be worth investigating further.
