### ISSUE TITLE
Predict mode: Save individual frames from video inference

### ISSUE THREAD

**Issue by tensorturtle** [ultralytics/ultralytics#6390]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Currently, if 'predict' mode is run on a video, `save=True` outputs a video.
For some use cases, a user might want each frame separately as an image.
I'm ready to submit a PR that lets the user select `save_frames=True` to output JPEG images instead of a video.

In addition, having an output that is identical in structure to a YOLO-compatible dataset seems like the right thing to do.

With `save=True`, `save_txt=True`, and toggling `save_frames=True/False`, the output directories would look like:
```
runs/detect
├── predict (save_frames = False)
│   ├── my_video1.avi
│   ├── my_video2.avi
│   └── labels
└── predict2 (save_frames = True)
    ├── images (contains JPEG images with the same file name as 'labels' except extension.
    └── labels
```

### Use case

Any user who wants to save each individual inferenced frame from a video.

My personal use case is that I'm using YOLOv8 to pre-label a dataset using videos that will be further reviewed by humans, then that reviewed dataset will be used to train another YOLOv8 model. Therefore it helps to keep the format the same as the training dataset.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@tensorturtle hello there! 👋

Thank you for your interest in the YOLOv8 repository and for the thoughtful feature request you've presented. It's great to see users involved in enhancing the functionality and usability of the tools we offer.

Regarding your proposal of adding a `save_frames` option to the `predict` mode, I appreciate the use case you've described. It certainly makes sense for users who want to work with individual frames, particularly when employing YOLOv8 for creating or refining datasets.

The idea of maintaining a consistent structure that aligns with a YOLO-compatible dataset is also sensible and would streamline processes for users following the workflow you've outlined.

Your contribution through a PR is welcome, as community-driven improvements are a big part of what makes open-source projects like YOLOv8 thrive. As you prepare your PR, please ensure that the feature is integrated cleanly with the existing codebase, follows our coding standards, and includes any necessary updates to the documentation to help users understand and apply the new option.

Moreover, consider the efficiency and potential performance implications of this feature during implementation. Make sure to provide clear explanations and usage instructions in the PR description and update the related sections of the Ultralytics Docs accordingly.

We look forward to reviewing your PR and seeing this feature come to life. Your involvement is a testament to the collaborative spirit of the YOLO community, and I'm sure many users will benefit from this additional functionality. Let's keep enhancing YOLOv8 together! 🚀

If any questions arise as you work on your PR, don't hesitate to reach out.

Thank you once again for your initiative and contribution! 🙌

**Comment by MaxRondelli** [comment]
I'm facing with the same siutation: I would like to all the save frames in a specific folder but the arg `save_frames = True` does not work. 
Viceversa, the arg `save = True` works but I only save my last inferenced frame. Is there a bug or I am doing something wrong? 
Thank you. 
    
```python 
def get_video(FPS, OUTPUT_VIDEO_NAME, VIDEO_PATH, MODEL_PATH_YOLO):
    model = YOLO(MODEL_PATH_YOLO)

    # Start capturing the feed and converting video into frames
    cap = cv2.VideoCapture(VIDEO_PATH)
    video_length = int(cap.get(cv2.CAP_PROP_FRAME_COUNT)) - 1
    print ("Number of frames: ", video_length)
    print ("Converting video..\n")

    progress_bar = tqdm(total=min(video_length, 1500))  # Set progress bar for 1500 frames
    frame_counter = 0

    while cap.isOpened() and frame_counter < 1500:
        # Extract the frame
        ret, frame = cap.read()
        if not ret:
            break

        # Make the inference on the current frame
        result = model.predict(source = frame,
                            save_frames = True,
                            show_labels = False,
                            show_conf = False,
                            line_width = 2,
                            project="inferenced_frames", 
                            name="inference", 
                            exist_ok=True
                            )
        
        frame_counter += 1
        progress_bar.update(1) # Continue with next frame
    
    progress_bar.close()```

**Comment by tensorturtle** [comment]
Hi @MaxRondelli 
Reading your code, I notice that you've built your own while loop, and running `model.predict()` on each frame.
`save_frames=True` is designed for the use case where you directly pass in the video path into `model.predict()`.
The ultralytics code can 'automatically' detect that what you pass in is a video and it has the code internally to step through each frame of it. 
Refer to https://docs.ultralytics.com/modes/predict/#key-features-of-predict-mode section "Inference Sources". You can pass in the video path (.mp4). Let me know if that works.

**Comment by MaxRondelli** [comment]
Hi @tensorturtle, thank you for your time. I am trying with this new code but in both case none of the frames are saved in the predict folder. The first solution is referred to the link you gave me, [this](https://docs.ultralytics.com/modes/predict/#inference-sources).

```python
from ultralytics import YOLO

def get_video(VIDEO_PATH, MODEL_PATH_YOLO):
    model = YOLO(MODEL_PATH_YOLO)
    source = VIDEO_PATH

    # First solution
    results = model(source, stream=True, save_frames = True) 

    # Second solution
    results = model.predict(source, stream = True, save_frames = True)

**Comment by MaxRondelli** [comment]
This is the solution that works now to save all the inferenced frames into a folder. The arg `save_frames` did not work with me. I'm probably doing something wrong.
```python
def get_video(VIDEO_PATH, MODEL_PATH_YOLO):
    model = YOLO(MODEL_PATH_YOLO)
    source = VIDEO_PATH
    results = model(source, stream=True)
    
    # Process results generator
    count = 0
    for result in results:
        boxes = result.boxes  # Boxes object for bounding box outputs
        masks = result.masks  # Masks object for segmentation masks outputs
        keypoints = result.keypoints  # Keypoints object for pose outputs
        probs = result.probs  # Probs object for classification outputs
        obb = result.obb  # Oriented boxes object for OBB outputs
        result.save(filename=f"inferenced/frame_{count}.jpg")  # save to disk
        count += 1

**Comment by pderrenger** [comment]
Thank you for sharing your solution. It appears that `save_frames=True` might not be functioning as expected in your case. To ensure this isn't a bug, please verify that you are using the latest version of the Ultralytics package. If the issue persists, consider opening a bug report on the GitHub repository with details of your environment and the problem.

Your approach of manually saving each frame using the `result.save()` method is a valid workaround. If you need further assistance or have additional questions, feel free to ask here.

**Comment by MaxRondelli** [comment]
Hi @pderrenger, 
I have already opened a bug #14943. I have received some hints but still `save_frames=True` does not work in my case.

**Comment by tensorturtle** [comment]
@MaxRondelli Have you tried passing in save=True, save_txt=True in adition to save_frames=True? I can't remember the code off the top of my head but in the above description it seems I had them turned on.

Also, the ultralytics crew regrettably use a lot of LLM AI bullshit responses (like the one by @pderrenger just now) so be wary of that.

**Comment by MaxRondelli** [comment]
@tensorturtle still, it does not work. 
Both ways:
```python 
results = model(source, stream=True, save=True, save_txt=True, save_frames=True)
```
and
```python 
results = model.predict(source, stream=True, save=True, save_txt=True, save_frames=True)
```
I've even tried with `save_crop=True` but nothing. It does not even start the prediction.

**Comment by MaxRondelli** [comment]
@tensorturtle I have found the solution. You can find it in the issue #14943. 
Thank you for your time. You can close the issue again.

**Comment by tensorturtle** [comment]
Great! Right so it seems like you needed to 'use up' the generator that was created. Generators are one of python's slightly more advanced features so I see how it was confusing. You're welcome and best wishes.

**Comment by pderrenger** [comment]
I'm glad you found the solution. Generators can indeed be a bit tricky. If you encounter any more issues or have further questions, feel free to reach out. Best of luck with your project!

**Comment by Namanm1994** [comment]
`--save_frames=True` flag does not work for me either inspite of using with all the other flags `stream=True, save=True, save_txt=True, save_frames=True` on a single video or on a directory of videos. Tomorrow, I will try solution by @MaxRondelli 
Hope that works for me.

**Comment by MaxRondelli** [comment]
@Namanm1994 did you find a solution about this problem?

**Comment by Namanm1994** [comment]
@MaxRondelli 
The flag `--save_frames` doesn't work, if I get time this week, I will check it out in yolo code, it probably just doesn't work bc of mismatch of code version or some merge.
I tried the solution by you from the other page(issue 14943 report: [link](https://github.com/ultralytics/ultralytics/issues/14943))
This worked like a charm
My code, inspired from issue/14943:
```
import os
from ultralytics import YOLO

def get_video(VIDEO_PATH, MODEL_PATH_YOLO):
    model = YOLO(MODEL_PATH_YOLO)
    source = VIDEO_PATH
    base_name=source.split('/')[-1].split('.')[0]

    # results = model(source, stream=True, save=True, save_frames=True)    # Process results generator
    results = model(source, 
                    stream=True, 
                    # save=True, 
                    save_frames=True,
                    show_labels=False,
                    show_conf=False,
                    save_txt=True,
                    classes=0
                    )

    count = 1
    for result in results:
        save_path=os.path.join(result.save_dir, "images")
        os.makedirs(save_path, exist_ok=True)
        result.save(filename=f"{save_path}/{base_name}_{count}.jpg")  # save to disk
        count += 1

if __name__ == "__main__":
    MODEL_PATH_YOLO='yolov8x.pt'
    _dir="/path/to/videos"
    for file in os.listdir(_dir):
        # Run inference for every video 
        get_video(os.path.join(_dir, file), MODEL_PATH_YOLO)
```
Note:
1) There is no error handling in this code(Please beware of that)
2) `--save` flag did not work for me, wether `True` or `False` detections are saved in both cases.

Your issue 14943 helped me a lot. Kudos to that!
Let me know if this helped or you were loking for something else.
