### ISSUE TITLE
Could the tracking id be reset now?

### ISSUE THREAD

**Issue by tangyipeng100** [ultralytics/ultralytics#6393]
While we use the object tracking, we need to evaluate the model on different videos, and the code shows below:

`  
for video_path in paths:
        result = model.track(
                   source=video_path,
                   tracker='ultralytics/tracker/cfg/botsort.yaml', 
                   show=True,
                   save = False,)
`

And the id seems can not be reset when changing to another video. Like in the first video, there exists 1, 2, 3 tracking IDs,  and  in the second video, the tracking ID begins from 4,.
There seems to have a similar question:[https://github.com/ultralytics/ultralytics/issues/4945#issuecomment-1730076116](url)

**Comment by RizwanMunawar** [comment]
If you wish to reset the track ID for each video, it is advisable to reinitialize the model for every video.

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by tangyipeng100** [comment]
Thanks for your reply, I have tried to reload the model again as be following codes shows
```
for video_path in paths:
    results = []
    result=[]
    tracking_id_l = []  # collection of tracking id in each frame
    model = YOLO("yolov8x.pt")  # or a segmentation model .i.e yolov8n-seg.pt
    clip_id = video_path.split('/')[-1]

    result = model.track(
        source=video_path,
        tracker="ultralytics/tracker/cfg/botsort.yaml",  # or 'bytetrack.yaml'
        show=True,
        save = False,
        #stream= True,
    )
    del model
```
But the ID seems that has not been reset. Can you provide code for reinitializing the model ? Thx.

**Comment by RizwanMunawar** [comment]
@tangyipeng100 You can use the mentioned code.

```python
from ultralytics import YOLO

paths = ["ultralytics\videos\\test1.mp4",
              "ultralytics\videos\\test2.mp4"]

for video_path in paths:
    model = YOLO("yolov8n.pt")
    result = model.track(source=video_path, tracker="bytetrack.yaml",show=True)
```

After running this code, I can clearly see the ID's reinitialization.

Thanks

**Comment by tangyipeng100** [comment]
Thanks, I update the code and it worked! Thx!

**Comment by glenn-jocher** [comment]
@tangyipeng100 you're most welcome! I'm glad to hear that the update has resolved the tracking ID issue for you. If you have any more questions or need further assistance, don't hesitate to reach out. Happy tracking with YOLOv8, and best of luck with your evaluations! 🚀💡

**Comment by mahavird** [comment]
The same tracking id is assigned if the object leaves the frame, how do we fix that? Can we get a different tracking id if object leaves the frame and enters again.

**Comment by glenn-jocher** [comment]
@mahavird to ensure a different tracking ID is assigned when an object leaves the frame and re-enters, you can modify the tracking parameters related to the expiration age of tracks or the re-identification feature of the chosen tracker.

If further assistance is needed, please let us know. Happy tracking! 😊👍

**Comment by JustinMBrown** [comment]
You can also reset tracking manually by calling model.predictor.trackers[0].reset()

**Comment by glenn-jocher** [comment]
@JustinMBrown absolutely, you can manually reset the tracking ID by invoking the `reset()` method on the tracker object. Here's a quick example of how to do it:

```python
model.predictor.trackers[0].reset()
```

This line will reset the tracking for your YOLOv8 model, ensuring that objects re-entering the frame can get assigned new tracking IDs. If you have more scenarios or need further tweaks, just give a shout! 😄🚀
