### ISSUE TITLE
demo数据集在哪儿？

### ISSUE THREAD

**Issue by AIlaowong** [ultralytics/ultralytics#6399]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

你们把demo数据集藏哪儿了？哪哪儿都找不到

**Comment by PiyushKamboj1503** [comment]
@AIlaowong 所有演示数据集均可在 https://github.com/ultralytics/ultralytics/tree/main/ultralytics/cfg/datasets 中找到

**Comment by glenn-jocher** [comment]
@PiyushKamboj1503 您好！演示数据集会在您第一次使用时自动下载。如果您需要查看数据集的配置文件，它们位于我们的GitHub仓库的 `ultralytics/cfg/datasets` 目录中。更多关于数据集和如何使用它们的信息，您可以参考我们的文档。希望这有助于您开始使用YOLOv8！🚀😊
