### ISSUE TITLE
Scale

### ISSUE THREAD

**Issue by ezyzzy** [ultralytics/ultralytics#6408]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to set 'scale' in .yaml?

**Comment by glenn-jocher** [comment]
@ezyzzy hello!

The 'scale' parameter in a YOLOv8 dataset .yaml file is used to adjust the image size during training by a certain scale factor. However, in the context of YOLOv8, this parameter is not directly exposed or used in the .yaml configuration files.

Instead, image resizing is handled automatically by the data augmentation process, which considers the `img-size` parameter you specify when running training commands. The `img-size` defines the target size that images will be resized to during training, and it is a more straightforward way to control the input image dimensions for your model.

For training, simply ensure that you set the `img-size` to the desired value either in your train command or within your .yaml file under the `img_size` key. This will effectively control the size without the need for a 'scale' parameter. Additionally, the augmentation process will apply random scaling as part of its routines to improve generalization.

If you're looking to do something different, and you specifically need to adjust scaling in a way not supported by default, you might have to modify the source code to introduce your custom scaling factor. However, this is usually not necessary for typical YOLOv8 use cases.

Please, refer to our Docs for more information about configuration options for training YOLOv8 models and image resizing options. If you have more questions, feel free to ask! 😊
