### ISSUE TITLE
[ Colab ] dataset from Google Drive directory can't be detected

### ISSUE THREAD

**Issue by chiboreache** [ultralytics/ultralytics#6411]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

ps: yeah i know there is a ticket, but no answer there 😑

### YOLOv8 Component

Train

### Bug

`WARNING ⚠️ no labels found in detect set, can not compute metrics without labels`

### Environment

colab

### Additional

it works perfectly fine on my local machine, but can't run on colab 🤷‍♂️

![2023-11-18x00:31:26](https://github.com/ultralytics/ultralytics/assets/16459251/35074f68-a37d-4672-b2c7-2a048411afaa)
![2023-11-18x00:30:54](https://github.com/ultralytics/ultralytics/assets/16459251/b1af8fd2-6046-4280-8684-ff7abb2daa93)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
@chiboreache, appreciate you providing the information.

If the process runs smoothly on your local machine, it should perform well on Google Colab too. The error appears to be related to the path. Please ensure to double-check the path, as large datasets in Colab may sometimes result in path-related issues.

**Comment by chiboreache** [comment]
@RizwanMunawar 

`model.train` simply can't work with dataset from gdrive directory

meanwhile yaml config from gdrive works correctly

so the only way to run it - from root folder -_-

_zipping - unzipping - downloading_ 

![2023-11-18x17:38:26](https://github.com/ultralytics/ultralytics/assets/16459251/d2b3a02b-0974-4b2f-a521-c16599a582be)
![2023-11-18x17:38:04](https://github.com/ultralytics/ultralytics/assets/16459251/39c95384-0cb6-4e1b-920f-6f4ec8f5c6f3)
