### ISSUE TITLE
How can I restrict the number of IDs being tracked without increasing the ID count in a byte track? 

### ISSUE THREAD

**Issue by ImSuMyatNoe** [ultralytics/ultralytics#6413]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I restrict the number of IDs being tracked without increasing the ID count in a byte track? Are there specific strategies or methods, such as implementing configuration settings, that can help manage and limit the total number of tracked IDs within the system based on known object counts?

**Comment by RizwanMunawar** [comment]
@ImSuMyatNoe, appreciate you sharing the information.

There isn't a direct method to accomplish this. However, you can implement custom code to prevent an increase in the ID count in bytetrack. The specified code line is responsible for assigning a new ID to a new object.

https://github.com/ultralytics/ultralytics/blob/b6baae584c3cf8560300a8eb1c267f68e63554bb/ultralytics/trackers/byte_tracker.py#L102

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by iuiu34** [comment]
hi,

i think limiting the number of id's is a very common case for tracking.

What you're suggesting @RizwanMunawar is that we do monkey patching?

there's not a native option for that? nor planned?

thanks
