### ISSUE TITLE
install yolov8 should be: pip install yolov8 and pip install ultralytics

### ISSUE THREAD

**Issue by kyoko9000** [ultralytics/ultralytics#642]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

it may make someone faster to remember yolov8 more then "pip install ultralytics"

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Ultralytics repo supports all yolo and can support non-yolo models, so it won't make any sense to call the package yolov8

**Comment by kyoko9000** [comment]
your sound is good but hard for you to put the name of new version look like yolov9 or 10. in that case if we want to use yolov9 we use "pip install Ultralytics" but how can use yolov8 again if that is not change. but so thank to yolo team. what think you guy make so great!

**Comment by pderrenger** [comment]
@kyoko9000 i appreciate your kind words! 🙏 The YOLO community and the Ultralytics team have indeed contributed greatly to the development of YOLOv8 and its predecessors. As for using YOLOv8, you can continue to install it using "pip install ultralytics" as before. The naming convention in the installation process remains consistent for all YOLO versions. If you have any more questions or need further assistance, feel free to ask!

**Comment by glenn-jocher** [comment]
Thank you for your support, @pderrenger! 🌟 To use YOLOv8, simply continue with "pip install ultralytics". This package includes YOLOv8 and allows for seamless transitions between versions. If you need further guidance, the Ultralytics Docs are always there to help. Keep up the great work!
