### ISSUE TITLE
How to get mAPs, mAPm, mAPl during validation

### ISSUE THREAD

**Issue by rusvagzur** [ultralytics/ultralytics#6438]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi there,

I was wondering how I can easily print the mAPsmall, mAPmedium, mAPlarge (as per COCO notation: https://cocodataset.org/#detection-eval) for instance segmentation in a custom dataset.

I have seen the eval_json function in [ultralytics/models/yolo/segment/val.py L221](https://github.com/ultralytics/ultralytics/blob/17edc5cf1b6f54c844666ef0caa023b1527fd1c8/ultralytics/models/yolo/segment/val.py#L221) But I can't find a reference to it in the rest of the code. Normally eval.summarize() should print this information already. However this function seems to never be called and I am confused about where in the code the predictions.json is actually created.

Many thanks

**Comment by glenn-jocher** [comment]
@rusvagzur hello!

I'm glad you're diving deep into the validation details of instance segmentation using YOLOv8. In YOLOv8, when you run the validation process using the `Val` mode, the mean Average Precision (mAP) is calculated for the different object sizes, namely small (mAPs), medium (mAPm), and large (mAPl). Understanding how to access these metrics can provide valuable insights into how your model is performing across different object scales.

During validation, YOLOv8 automatically calculates and prints out the average precision for each object size category as part of the evaluation summary. Though you've referenced the `eval_json` function, which prepares the data for COCO evaluation, the actual computation of the mAP metrics for different object sizes is managed within the COCO API that YOLOv8 calls during validation.

To see the mAPs, mAPm, mAPl metrics, you should simply run the validation, and these metrics will be printed in the console output. When you run validation, the `predictions.json` is created and filled with the detection results from evaluating your dataset, which is subsequently used by the COCO API to compute the various mAP metrics.

Make sure your dataset is properly formatted according to the COCO-style annotations, and your validation pipeline is correctly set up. Then, by the end of the evaluation process, you'll see a breakdown of the mAP for various IoU thresholds and object sizes.

Let me know if you encounter any specific issues or have further questions. The Ultralytics team appreciates your interest and dedication to advancing with YOLOv8. 🚀

**Comment by rusvagzur** [comment]
Hi @glenn-jocher ,

Many thanks for the great answer. From the code I understand exactly what you're pointing at. However, it's not working for me:

First, the eval_json in L224 of the segment/val.py [where the ground truth is read](https://github.com/ultralytics/ultralytics/blob/17edc5cf1b6f54c844666ef0caa023b1527fd1c8/ultralytics/models/yolo/segment/val.py#L224) forces the file to be called instances_val2017.json and be under annotations directory. 

Then, image_id provided in [L207](https://github.com/ultralytics/ultralytics/blob/17edc5cf1b6f54c844666ef0caa023b1527fd1c8/ultralytics/models/yolo/segment/val.py#L207) only works if your images are named 0.jpg, 1.jpg... In my case my image_id gets assigned a string with the name of the image which then is not found in the ground truth, since image_id should be an integer.

Even after fixing these partes, I have made sure that the ground truth ids and ids in the predictions.json are correct. But I still don't see anything being printed when validating. Am I missing something?

**Comment by glenn-jocher** [comment]
@rusvagzur i appreciate your follow-up and the details of the issues you're experiencing when trying to validate with instance segmentation metrics using YOLOv8.

It sounds like you're encountering a couple of specific concerns:

1. The ground truth file name and location expectation: If you've already adapted the code or your data structure to comply with the expected instances JSON file format, that's a primary step.

2. The `image_id` not matching the naming scheme of the COCO dataset can certainly cause issues if your images are named differently. This requires ensuring that the `image_id` in your predictions JSON aligns with those in your annotation JSON.

After you've ensured that your dataset annotations are in the proper COCO format and image IDs are matching as integers, there are a few more steps that you may want to verify:

- Ensure that `save_json=True` is properly activating the code block that generates `predictions.json`. This block should be in the `val.py` where the validation loop processes each image and collects prediction data.
- After the detection results are saved in the `predictions.json`, the COCO evaluation should be triggered, which calls the `COCOeval` function to evaluate the detections against the ground truths using this file.

If these steps are correct, the COCO API should produce the mAP metrics you're looking for, including mAPs, mAPm, and mAPl. If the process completes correctly and your results are still not showing, there might be an issue with the execution flow or a conditional statement that's preventing the printing of these metrics.

You might also want to make sure that the validation dataset is large enough to contain a variety of object sizes, as the COCO API needs enough samples to compute size-specific metrics reliably.

Lastly, double-check that the version of the COCO API installed in your environment is up to date and functioning as expected. If necessary, look at the output logs to see if any errors or warnings are being emitted that could give clues as to why the expected output isn't appearing.

It can indeed be quite complex, but these checks should steer you in the right direction. Please keep the community posted on your progress or reach out if further clarification is needed, and we'll do our best to support you. Your careful work and insights are valuable to improving the YOLOv8 experience for everyone.👍

**Comment by timecollision** [comment]
After I ran the /yolo/segment/val.py file, the "counts" in the output preditions.json file are all garbled, how can I solve this?
[{"image_id": 499, "category_id": 0, "bbox": [202.953, 116.714, 84.71, 50.938], "score": 0.72763, "segmentation": {"size": [192, 500], "counts": "c\\V1b0^50O2O00000O1O1O10000O1000000N11000OO200O10O1000000N101000N20O011MXOlJg0T5300000000O10O10N02000O0100O10OO2OO20000O01N2000O0100000M300000O01N20O100O10000O1N200O1O1N200O1L4N202M[^W1"}}, {"image_id": 499, "category_id": 0, "bbox": [191.89, 125.712, 77.472, 39.747], "score": 0.00518, "segmentation": {"size": [192, 500], "counts": "jTT14l50O4K20000O101O00001N3L20000O1000000O1N2000000O10000N20N20O10O100000O10O10O1O01O10O01000O1N2O100000O1000O01OO11000O01O1O10O01000O01N2O11OO100000000O100000SP[1"}}, 
[predictions.json](https://github.com/user-attachments/files/18064039/predictions.json)

**Comment by glenn-jocher** [comment]
The issues you're encountering with the "counts" field being garbled and the mismatch in "category_id" values in your `predictions.json` file are likely due to a mismatch in your dataset formatting or issues during the evaluation pipeline. Here's how to address them:

1. **"Counts" Field Issue**: The "counts" field in the segmentation output uses RLE (Run-Length Encoding) to represent the segmentation mask. If it appears garbled, ensure that:
   - Your dataset is formatted correctly in COCO format, especially the `instances_val2017.json` file.
   - The `image_id` and `category_id` fields in your dataset annotations align with the model's expected input/output structure.

2. **"Category_id" Mismatch**: The `category_id` in `predictions.json` is indexed starting from 0, whereas COCO's `instances_val2017.json` uses `category_id` starting from 1. This is expected behavior, as the model's category indexing is zero-based. You can adjust this post-processing if needed for alignment with COCO's one-based indexing.

Make sure your dataset adheres to the [COCO format](https://docs.ultralytics.com/datasets/detect/coco/) and that any custom changes to `val.py` (e.g., for file paths or IDs) are correctly implemented. If the issue persists, share minimal reproducible steps for further investigation.

**Comment by timecollision** [comment]
I wrote a piece of code that changed the categoryid from 0 to 1 in the generated json file:
import json

def change_category_id(json_file_path):
   
    with open(json_file_path, 'r') as f:
        data = json.load(f)

   
    for item in data:
        item["category_id"] = 1

  
    with open(json_file_path, 'w') as f:
        json.dump(data, f, indent=4)

change_category_id('D:\JetBrains 2023\Yolov8seg/ultralytics-main/runs\segment/val5\predictions.json')

After that, run the following code to print all the required mAP metrics normally：

from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval


# accumulate predictions from all images
# load instances_val2017.json
coco_true = COCO(annotation_file="D:\JetBrains 2023\Yolov8seg/ultralytics-main\datasets\coco/annotations\instances_val2017.json")
# load predictions.json 通过change_json_category_0-1.py修改后的json文件
coco_pre = coco_true.loadRes(r'D:\JetBrains 2023\Yolov8seg\ultralytics-main/runs\segment/val5\predictions.json')

coco_evaluator = COCOeval(cocoGt=coco_true, cocoDt=coco_pre, iouType="segm")
coco_evaluator.evaluate()
coco_evaluator.accumulate()
coco_evaluator.summarize()

**Comment by glenn-jocher** [comment]
@timecollision thank you for sharing your approach! Your script to adjust `category_id` and use `pycocotools` for evaluation is a valid workaround to resolve the `category_id` mismatch and compute COCO metrics like mAP. This ensures compatibility between your `predictions.json` and `instances_val2017.json`. If further adjustments or validation are needed, feel free to ask. Great work!

**Comment by handsome2456** [comment]
> I wrote a piece of code that changed the categoryid from 0 to 1 in the generated json file:
> 
> import json
> 
> 
> 
> def change_category_id(json_file_path):
> 
>    
> 
>     with open(json_file_path, 'r') as f:
> 
>         data = json.load(f)
> 
> 
> 
>    
> 
>     for item in data:
> 
>         item["category_id"] = 1
> 
> 
> 
>   
> 
>     with open(json_file_path, 'w') as f:
> 
>         json.dump(data, f, indent=4)
> 
> 
> 
> change_category_id('D:\JetBrains 2023\Yolov8seg/ultralytics-main/runs\segment/val5\predictions.json')
> 
> 
> 
> After that, run the following code to print all the required mAP metrics normally：
> 
> 
> 
> from pycocotools.coco import COCO
> 
> from pycocotools.cocoeval import COCOeval
> 
> 
> 
> 
> 
> # accumulate predictions from all images
> 
> # load instances_val2017.json
> 
> coco_true = COCO(annotation_file="D:\JetBrains 2023\Yolov8seg/ultralytics-main\datasets\coco/annotations\instances_val2017.json")
> 
> # load predictions.json 通过change_json_category_0-1.py修改后的json文件
> 
> coco_pre = coco_true.loadRes(r'D:\JetBrains 2023\Yolov8seg\ultralytics-main/runs\segment/val5\predictions.json')
> 
> 
> 
> coco_evaluator = COCOeval(cocoGt=coco_true, cocoDt=coco_pre, iouType="segm")
> 
> coco_evaluator.evaluate()
> 
> coco_evaluator.accumulate()
> 
> coco_evaluator.summarize()

Hi, have you solved the problem with yolov8-seg getting coco indicator?If solved, can you share the method?

**Comment by timecollision** [comment]
> > I wrote a piece of code that changed the categoryid from 0 to 1 in the generated json file:
> > import json
> > def change_category_id(json_file_path):
> > ```
> > with open(json_file_path, 'r') as f:
> > 
> >     data = json.load(f)
> > 
> > 
> > 
> > 
> > 
> > for item in data:
> > 
> >     item["category_id"] = 1
> > 
> > 
> > 
> > 
> > 
> > with open(json_file_path, 'w') as f:
> > 
> >     json.dump(data, f, indent=4)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > change_category_id('D:\JetBrains 2023\Yolov8seg/ultralytics-main/runs\segment/val5\predictions.json')
> > After that, run the following code to print all the required mAP metrics normally：
> > from pycocotools.coco import COCO
> > from pycocotools.cocoeval import COCOeval
> > # accumulate predictions from all images
> > # load instances_val2017.json
> > coco_true = COCO(annotation_file="D:\JetBrains 2023\Yolov8seg/ultralytics-main\datasets\coco/annotations\instances_val2017.json")
> > # load predictions.json 通过change_json_category_0-1.py修改后的json文件
> > coco_pre = coco_true.loadRes(r'D:\JetBrains 2023\Yolov8seg\ultralytics-main/runs\segment/val5\predictions.json')
> > coco_evaluator = COCOeval(cocoGt=coco_true, cocoDt=coco_pre, iouType="segm")
> > coco_evaluator.evaluate()
> > coco_evaluator.accumulate()
> > coco_evaluator.summarize()
> 
> Hi, have you solved the problem with yolov8-seg getting coco indicator?If solved, can you share the method?

You need to create a .py file first, write the following code and run it:
from ultralytics import YOLO
if __name__ == '__main__':
    model = YOLO('The path to your .pth file that has been trained ')
    model.val(save_json=True)

After that, you need to create another .py file to write and run:
import json
def change_category_id(json_file_path):
    with open(json_file_path, 'r') as f:
        data = json.load(f)
    for item in data:
        item["category_id"] = 1
    with open(json_file_path, 'w') as f:
        json.dump(data, f, indent=4)
change_category_id('When the code in the first step is run, you will get a file called predictions.json, which you will fill here')

Finally, create a .py file to write and run，you will see all the indicators on the terminal :
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval
coco_true = COCO(annotation_file="The path where the val.json files in your COCO dataset are saved")
coco_pre = coco_true.loadRes('When the code in the first step is run, you will get a file called predictions.json, which you will fill here')
coco_evaluator = COCOeval(cocoGt=coco_true, cocoDt=coco_pre, iouType="segm")
coco_evaluator.evaluate()
coco_evaluator.accumulate()
coco_evaluator.summarize()

**Comment by glenn-jocher** [comment]
@timecollision yes, your outlined method is correct and aligns with the process needed to generate COCO-style metrics for YOLOv8-seg. By ensuring category IDs are correctly mapped between your dataset and predictions, and running the `pycocotools` evaluation, you can compute the required metrics. If further clarification is needed, feel free to ask!
