### ISSUE TITLE
Can't import ultralytics in Jupyter Notebook error in set_logging

### ISSUE THREAD

**Issue by JorgeT42** [ultralytics/ultralytics#6446]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

    .\venv\lib\site-packages\ultralytics\utils\__init__.py:233, in set_logging(name, verbose)
    231 # Configure the console (stdout) encoding to UTF-8
    232 if WINDOWS:  # for Windows
--> 233     sys.stdout.reconfigure(encoding='utf-8')
    235 # Create and configure the StreamHandler
    236 stream_handler = logging.StreamHandler(sys.stdout)

AttributeError: 'OutStream' object has no attribute 'reconfigure'

### Environment

Error in a python 3.10 enviroment in Windows, only in Jupyter Notebook cells, 8.0.211 ultralytics 8.0.212 and 8.0.213 (8.0.211 doesn't have this error), can't import ultralytics in Jupyter Notebook

### Minimal Reproducible Example

In Python 3.10

pip install ultralytics==8.0.212
or
pip install ultralytics==8.0.213

In Jupyter Notebook Cell:
import ultralytics

### Additional

![Imagen de WhatsApp 2023-11-19 a las 20 50 05_0c8fb298](https://github.com/ultralytics/ultralytics/assets/63155200/d4c1c43d-7426-426d-98bf-3302a58c95fe)

Left code is from  ultralytics 8.0.211, doesn't have the bug
Right code is from  ultralytics 8.0.212, there is the bug

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
@JorgeT42, appreciate your comprehensive information. Be assured that we'll conduct internal testing. If all goes smoothly, we'll proceed to merge your pull request.

Thank you for your dedication and support.

Best regards,
Ultralytics Team

**Comment by glenn-jocher** [comment]
@JorgeT42 testing a fix in #6459 that's a little different than your PR. Can you try this on the `windows-utf8` branch and verify that this solves your problem?

**Comment by JorgeT42** [comment]
232 if WINDOWS and sys.stdout.encoding != 'utf-8':
    233     import io
--> 234     sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
    236 # Create and configure the StreamHandler
    237 stream_handler = logging.StreamHandler(sys.stdout)

AttributeError: 'OutStream' object has no attribute 'buffer'

There is another problem now

**Comment by glenn-jocher** [comment]
@JorgeT42 got it! I merged the PR with a try: except loop that will essentially do nothing if the attempts fail, but I don't know if this will resolve the issue.

In your environment can you run this code successfully?

```python
import sys

sys.stdout.encoding = 'utf-8'
```

**Comment by glenn-jocher** [comment]
Maybe I should update the code with a final line like you had, but in my environment I get this warning that the value can not be set:
<img width="585" alt="Screenshot 2023-11-20 at 14 22 29" src="https://github.com/ultralytics/ultralytics/assets/26833433/f573278a-3ea4-46f2-b65c-76816467d144">

**Comment by JorgeT42** [comment]
@glenn-jocher 

import sys

sys.stdout.encoding = 'utf-8'

It works in Jupyter Notebook, but I get this in .py files: 
 sys.stdout.encoding = 'utf-8'
AttributeError: readonly attribute

**Comment by glenn-jocher** [comment]
@JorgeT42 ok got it. So do you think the above code will work then or will it just pass to the except clause?

Can you try https://github.com/ultralytics/ultralytics/pull/6463 with:
```
pip install git+https://github.com/ultralytics/ultralytics.git@fix
```

**Comment by glenn-jocher** [comment]
@MartinKlefas when you pip install the `fix` branch do you see emojis on windows then with the `yolo checks` command?

**Comment by MartinKlefas** [comment]
> @MartinKlefas when you pip install the `fix` branch do you see emojis on windows then with the `yolo checks` command?

I do, yes, I'm specifcally in a jupyter notebook, and I can see emojis there where I used to get the error messages you've posted

**Comment by glenn-jocher** [comment]
Oh great! Everything seems all set then, I'll go ahead and push this in a new version.

**Comment by UyeYwb** [comment]
File "D:\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO

  File "D:\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR

  File "D:\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR

  File "D:\ultralytics\models\rtdetr\model.py", line 10, in <module>
    from ultralytics.engine.model import Model

  File "D:ultralytics\engine\model.py", line 9, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir

  File "D:\ultralytics\cfg\__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,

  File "D\ultralytics\utils\__init__.py", line 265, in <module>
    LOGGER = set_logging(LOGGING_NAME, verbose=VERBOSE)  # define globally (used in train.py, val.py, predict.py, etc.)
             │           │                     └ True
             │           └ 'ultralytics'
             └ <function set_logging at 0x000002701DDF65E0>

  File "D:\\ultralytics\utils\__init__.py", line 233, in set_logging
    if WINDOWS and sys.stdout.encoding != 'utf-8':
       │           │   └ None
       │           └ <module 'sys' (built-in)>
       └ True

AttributeError: 'NoneType' object has no attribute 'encoding'

Why am I encountering this error? My version is 8.0.218.

**Comment by MartinKlefas** [comment]
> File "D:\ultralytics__init__.py", line 5, in from ultralytics.models import RTDETR, SAM, YOLO
> 
> File "D:\ultralytics\models__init__.py", line 3, in from .rtdetr import RTDETR
> 
> File "D:\ultralytics\models\rtdetr__init__.py", line 3, in from .model import RTDETR
> 
> File "D:\ultralytics\models\rtdetr\model.py", line 10, in from ultralytics.engine.model import Model
> 
> File "D:ultralytics\engine\model.py", line 9, in from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
> 
> File "D:\ultralytics\cfg__init__.py", line 10, in from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
> 
> File "D\ultralytics\utils__init__.py", line 265, in LOGGER = set_logging(LOGGING_NAME, verbose=VERBOSE) # define globally (used in train.py, val.py, predict.py, etc.) │ │ └ True │ └ 'ultralytics' └ <function set_logging at 0x000002701DDF65E0>
> 
> File "D:\ultralytics\utils__init__.py", line 233, in set_logging if WINDOWS and sys.stdout.encoding != 'utf-8': │ │ └ None │ └ <module 'sys' (built-in)> └ True
> 
> AttributeError: 'NoneType' object has no attribute 'encoding'
> 
> Why am I encountering this error? My version is 8.0.218.

This appears to be a new issue on a new version of the codebase - please can you raise it as such for someone to look into it?

**Comment by glenn-jocher** [comment]
@MartinKlefas thank you for bringing this issue to my attention. It seems there is a problem with the `sys.stdout.encoding` attribute being `None`. This can happen in some environments where the standard streams are redirected, such as Jupyter Notebooks or certain IDE consoles.

To help us address this issue effectively, could you please open a new issue on the YOLOv8 repository detailing the steps to reproduce this error, your operating system, and any other relevant environment details? Your participation is very valuable, and opening a new issue will allow us to track and resolve it in an organized manner.

Meanwhile, as a temporary workaround, you might want to check if the error persists in a different environment or terminal. Thank you for your support, and we look forward to resolving this swiftly! 🚀

**Comment by spacewalk01** [comment]
got the same problem!

**Comment by glenn-jocher** [comment]
@spacewalk01 thank you for reporting the issue. It appears to be an environment-specific problem on Windows. Could you please open an issue on our YOLOv8 GitHub repo with the details of your setup and the steps leading to the problem? We'll investigate and aim to resolve it as soon as possible. 🛠️
