### ISSUE TITLE
Request for Updated YOLO Pretrained models - Inspired by RT-DETR

### ISSUE THREAD

**Issue by PraveenKumar-Rajendran** [ultralytics/ultralytics#6448]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

- **Observation**: RT-DETR, a real-time transformer-based detection model, showed significant performance improvement in RT-DETR on the COCO dataset validation when pretrained with the Object365 dataset.

RT-DETR: https://github.com/lyuwenyu/RT-DETR

- **Test Results**: Comparison between the original COCO-only pretrained RT-DETR and the Object365+COCO pretrained version demonstrates a notable performance jump

<img width="688" alt="rt-detr-graph-latest" src="https://github.com/ultralytics/yolov5/assets/53290706/e36d2bfa-68ee-422b-8855-3c3baf33f5c7">

PS: Confirmed this with the custom dataset for training and validation.

- **Request**: Please consider adopting a similar pretraining approach for YOLO models, utilizing the Object365 dataset in addition to the standard COCO pretraining.

### Use case

- **Potential Impact**: This methodology could enhance YOLO models' performance (both v5  and v8), benefiting the broader YOLO community and advancing object detection capabilities.

### Additional

- **Appreciation**: Thank you for your ongoing contributions to object detection research and development.

Thank you for considering this request.

FYI, 
raised a same request in yolov5 repository [here](https://github.com/ultralytics/yolov5/issues/12397)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
@PraveenKumar-Rajendran, appreciate your comprehensive information. Be assured that we'll conduct internal testing. If all goes smoothly, we'll proceed to merge your pull request.

Thank you for your dedication and support.

Best regards,
Ultralytics Team
