### ISSUE TITLE
ModuleNotFoundError: No module named 'ultralytics' 

### ISSUE THREAD

**Issue by Auth0rM0rgan** [ultralytics/ultralytics#646]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi @AyushExel, 

Im trying to load the yolov8 weights file with pytorch load however im getting following error. 
```
Traceback (most recent call last):
  File "/home/anaconda3/envs/camaleonic/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-42e8ca6e45b7>", line 1, in <cell line: 1>
    torch.load('/home/Documents/detection/objects/yolov8m.pt')
  File "/home/anaconda3/envs/camaleonic/lib/python3.8/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/anaconda3/envs/camaleonic/lib/python3.8/site-packages/torch/serialization.py", line 1046, in _load
    result = unpickler.load()
  File "/home/anaconda3/envs/camaleonic/lib/python3.8/site-packages/torch/serialization.py", line 1039, in find_class
    return super().find_class(mod_name, name)
  File "/snap/pycharm-professional/316/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'ultralytics'
```

Is there any way to load the weight file with `torch.load(w, map_location='CPU')` without installing ultralytics and not with ultralytics functions?

**Comment by AyushExel** [comment]
No you need to use ultralytics module to load the trained models. There are many custom modules used that torch doesn't support directly.

**Comment by XUhaozhi88** [comment]
I am not sure whether this is right or not.
you may use this code as follows.
`
import torch
from ultralytics.nn.tasks import attempt_load_one_weight

model_path = 'yolov8l.pt'

model, ckpt = attempt_load_one_weight(model_path)
csd = model.float().state_dict()
torch.save(csd, './new_yolov8.pth')`

**Comment by XUhaozhi88** [comment]
I am not sure if this is correct.
you may use the following code.

```
import torch
from ultralytics.nn.tasks import attempt_load_one_weight

model_path = 'yolov8l.pt'

model, ckpt = attempt_load_one_weight(model_path)
csd = model.float().state_dict()
torch.save(csd, './new_yolov8.pth')```

**Comment by XUhaozhi88** [comment]
I am not sure if this is correct.
you may use the following code.

```
import torch
from ultralytics.nn.tasks import attempt_load_one_weight

model_path = 'yolov8l.pt'

model, ckpt = attempt_load_one_weight(model_path)
csd = model.float().state_dict()
torch.save(csd, './new_yolov8.pth')
```

**Comment by pderrenger** [comment]
@XUhaozhi88 great suggestion! This code snippet effectively uses the `attempt_load_one_weight` function from Ultralytics to load the YOLOv8 weights and subsequently saves the model in a PyTorch-compatible format. This approach ensures compatibility with the custom modules used in YOLOv8.
