### ISSUE TITLE
How to load pretrained model when i using yaml load model?

### ISSUE THREAD

**Issue by z1069614715** [ultralytics/ultralytics#647]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to load pretrained model when i using yaml load model?

**Comment by pderrenger** [comment]
@z1069614715 to load a pretrained model using YAML, you can specify the pretrained model's YAML configuration file when loading the model. The YAML file contains the settings and parameters for the pretrained model, and it's used to initialize the model with the correct architecture and weights. When loading the model, simply provide the path to the pretrained model's YAML file, and the model will be initialized with the pretrained weights and settings.

You can directly reference the path to the pretrained model's YAML configuration file within the load model command to easily initialize the model with the pretrained weights and settings.
