### ISSUE TITLE
Where is the coco-seg.yaml?

### ISSUE THREAD

**Issue by zhangyang2057** [ultralytics/ultralytics#6476]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I can find the description about segment in README.md, "Reproduce by yolo val segment data=coco-seg.yaml device=0". 
So where is the coco-seg.yaml?

I could find the following yamls for datasets.

```
-rw-rw-r-- 1 zhangyang zhangyang  2856 Oct 31 14:59 Argoverse.yaml
-rw-rw-r-- 1 zhangyang zhangyang  1862 Oct 31 14:59 coco128-seg.yaml
-rw-rw-r-- 1 zhangyang zhangyang  1846 Oct 31 14:59 coco128.yaml
-rw-rw-r-- 1 zhangyang zhangyang   895 Oct 31 14:59 coco8-pose.yaml
-rw-rw-r-- 1 zhangyang zhangyang  1797 Oct 31 14:59 coco8-seg.yaml
-rw-rw-r-- 1 zhangyang zhangyang  1777 Oct 31 14:59 coco8.yaml
-rw-rw-r-- 1 zhangyang zhangyang  1542 Oct 31 14:59 coco-pose.yaml
-rw-rw-r-- 1 zhangyang zhangyang  2521 Oct 31 14:59 coco.yaml
-rw-rw-r-- 1 zhangyang zhangyang  1149 Oct 31 14:59 DOTAv2.yaml
-rw-rw-r-- 1 zhangyang zhangyang  1981 Oct 31 14:59 GlobalWheat2020.yaml
-rw-rw-r-- 1 zhangyang zhangyang 42446 Nov  8 22:15 ImageNet.yaml
-rw-rw-r-- 1 zhangyang zhangyang  9255 Oct 31 14:59 Objects365.yaml
-rw-rw-r-- 1 zhangyang zhangyang 12421 Oct 31 14:59 open-images-v7.yaml
-rw-rw-r-- 1 zhangyang zhangyang  2427 Oct 31 14:59 SKU-110K.yaml
-rw-rw-r-- 1 zhangyang zhangyang   797 Oct 31 14:59 tiger-pose.yaml
-rw-rw-r-- 1 zhangyang zhangyang  3007 Oct 31 14:59 VisDrone.yaml
-rw-rw-r-- 1 zhangyang zhangyang  3505 Oct 31 14:59 VOC.yaml
-rw-rw-r-- 1 zhangyang zhangyang  5153 Oct 31 14:59 xView.yaml
```

**Comment by glenn-jocher** [comment]
@zhangyang2057 hello! All of the data YAML files are in this directory:
https://github.com/ultralytics/ultralytics/tree/main/ultralytics/cfg/datasets

**Comment by glenn-jocher** [comment]
Hello @zhangyang2057 👋!

For reproducing segmentation performance on the full COCO dataset, you should indeed use the `coco.yaml`, and specify the 'segment' task when you use the validation command. This will use the full COCO dataset configured in the YAML file with segmentation annotations.

Just as a reminder, you can always reference the segmentation task in our documentation over at https://docs.ultralytics.com/tasks/segment for additional guidance. Enjoy your object segmentation journey! 🚀✨

**Comment by zhangyang2057** [comment]
@glenn-jocher Thank you.

**Comment by glenn-jocher** [comment]
@zhangyang2057 you're welcome! If you have any more questions or need further assistance, feel free to ask. Happy training and good luck with your segmentation tasks! 😊👍
