### ISSUE TITLE
about label abnormal in train_batch*.jpg

### ISSUE THREAD

**Issue by fuzhao123232** [ultralytics/ultralytics#6479]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

![image](https://github.com/ultralytics/ultralytics/assets/115547529/a6268bc2-1b08-4c72-b90d-d93de418fdd9)
Dear authors, thanks to your wanderful job. I am using yolov8-seg model. I used boptoolkit and Blenderproc (https://github.com/DLR-RM/BlenderProc) to render data by CAD model. And i get the label as follow:
![image](https://github.com/ultralytics/ultralytics/assets/115547529/ed14832d-3828-4f33-b39c-c5a886d7d5d5)
Then I use contours,hit = cv2.findContours(binary,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE) to get the mask's boundary coordinates because the coco-seg's label is txts with :cls_id, x1 y1 x2 y2 x3 y3. Then I check my label by draw the boudary coordinates, and i think it is no problem, demo as follow:
![image](https://github.com/ultralytics/ultralytics/assets/115547529/1381ed5c-aec0-40d7-bb30-98eb76ae8145)
Then i run the yolov8-seg,but the labes in train_batch.jpg is very bad as you see. 
![image](https://github.com/ultralytics/ultralytics/assets/115547529/e63ca73a-4da2-4653-88a4-9a8e2e4127c7)
So what's the reason? Is the data augment's problem? I really need your help! Thanks very much.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by fuzhao123232** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/115547529/c6434aed-f4ff-4661-8ecd-54a6958f0310)
I try to set the data augment to 0 , but the train_batch.jpg is also bad.
![image](https://github.com/ultralytics/ultralytics/assets/115547529/82d6a500-c53d-469b-b66c-5708255e28cf)

**Comment by glenn-jocher** [comment]
@fuzhao123232 I think there may be an issue with the order of your segments. If your segments are sorted vertically for example then perhaps the rendering bouncing back vectors left and right rather than tracing a steady outline on the image. I think the order should be clockwise or counterclockwise to create a convex shape correctly. 

See https://docs.ultralytics.com/datasets/segment/#usage and make sure that your point order is similar to the COCO point order and that your cv2 findcountours thresholding is being applied correctly.

**Comment by glenn-jocher** [comment]
@fuzhao123232 that's great to hear! I'm thrilled to know you resolved the issue. 😄 If you have any more questions or need further assistance with YOLOv8, don't hesitate to reach out. The YOLO community and the Ultralytics team are always here to support. Happy detecting! 🚀
