### ISSUE TITLE
Save period while training

### ISSUE THREAD

**Issue by creativepix** [ultralytics/ultralytics#648]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Will be added argument which is responsible for saving every N epoch?

### Use case

Getting the checkpoint from particular epoch

### Additional

This feature is in YOLOv5 as save-period

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by twoyoung91** [comment]
I am also wondering the same question
model.train does not accept "save-period" as a parameter

**Comment by Laughing-q** [comment]
@twoyoung91 @Vlad-Lucky now the feature has been supported. :)
```python
model.train(save_period=...)
```

**Comment by pigeongcc** [comment]
@Laughing-q I don't see the `save_period` in the CLI version parameter list. Can I use it with CLI?

**Comment by glenn-jocher** [comment]
@pigeongcc all arguments are common between CLI and Python. You can use save_period in CLI just like any other train arg:
```
yolo train save_period=1
```

See https://docs.ultralytics.com/modes/train/#arguments for details.
