### ISSUE TITLE
A method to plot training dataset 

### ISSUE THREAD

**Issue by Ichiruchan** [ultralytics/ultralytics#6481]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

According to the [this issue](https://github.com/ultralytics/ultralytics/issues/6035), to plot my training dataset, I need to load dataset by my YAML config and then use dataset().show. The first question is when i programed as following: 
```
with open(".\\battery_kp.yaml", "r") as f:
    data_dict = yaml.safe_load(f)

test = YOLODataset(data=data_dict)
```

And then I get this error **TypeError: __init__() missing 1 required positional argument: 'img_path'**

My config yaml is:
```
path: ./kp_data
train: train
val: test
test:

kpt_shape: [1, 3]
flip_idx: [0]

names:
  0: pole
```
And it works `model.train(data=ds_yaml,
                          epochs=epoch,
                          imgsz=img_size,
                          project=os.path.join("output", model_name))`
Second question is that i do not find show function in the following [documentation](https://docs.ultralytics.com/reference/data/dataset).

**Comment by PiyushKamboj1503** [comment]
@Ichiruchan in your yaml file, add the following: 
`path: ./kp_data
train: train/images #your image folder name
val: val/images #if present
test: test/images #if applicable

kpt_shape: [1, 3]
flip_idx: [0]

names:
  0: pole`

**Comment by Ichiruchan** [comment]
> @Ichiruchan in your yaml file, add the following: `path: ./kp_data train: train/images #your image folder name val: val/images #if present test: test/images #if applicable
> 
> kpt_shape: [1, 3] flip_idx: [0]
> 
> names: 0: pole`

Actually, I don't have test dataset and all image are under train/val folder. There is no subfolder _images_.

**Comment by glenn-jocher** [comment]
@Ichiruchan thank you for your message, and for detailing your issue with loading and visualizing your dataset in YOLOv8.

Regarding the error you encountered, it seems that YOLODataset is expecting an additional argument that you need to pass when you instantiate it. When you create an instance of YOLODataset, make sure that you are passing all required arguments correctly. Unfortunately, without more context or a code snippet, I cannot provide you with a specific solution, but you can consult the documentation on the requirements for initializing the YOLODataset correctly.

For your second question, if you're looking to visualize your dataset, the method to plot or show images may vary depending on the structure or changes in the API. I would recommend checking out the latest documentation in the data and dataset sections, which provide information on how to use the dataset class and visualization tools provided by YOLOv8. You can refer to the documentation at https://docs.ultralytics.com. If you cannot find the `show` function it is possible that it has been replaced or renamed, so consulting the latest documentation or looking into the dataset class methods is the best course of action.

If your image directories are directly under `train/` and `val/` without an `images/` subfolder, your yaml should reflect that structure. Ensure that the `train`, `val`, and if needed, the `test` entries in your YAML file correctly point to these folders. For example:

```yaml
path: ./kp_data
train: train
val: val
test:  # Include only if you have a test set
```

Following these steps should help you to initialize your dataset and visualize it appropriately. Please check the documentation for the most up-to-date instructions and feel free to reach out if you have any more questions. Good luck with your training! 🚀

**Comment by PiyushKamboj1503** [comment]
> > @Ichiruchan in your yaml file, add the following: `path: ./kp_data train: train/images #your image folder name val: val/images #if present test: test/images #if applicable
> > 
> > kpt_shape: [1, 3] flip_idx: [0]
> > 
> > names: 0: pole`
> 
> Actually, I don't have test dataset and all image are under train/val folder. There is no subfolder _images_.

See if you are working with object detection dataset, you must be having 1 image and 1 label folder.

**Comment by Ichiruchan** [comment]
> > > @Ichiruchan in your yaml file, add the following: `path: ./kp_data train: train/images #your image folder name val: val/images #if present test: test/images #if applicable
> > > kpt_shape: [1, 3] flip_idx: [0]
> > > names: 0: pole`
> > 
> > 
> > Actually, I don't have test dataset and all image are under train/val folder. There is no subfolder _images_.
> 
> See if you are working with object detection dataset, you must be having 1 image and 1 label folder.

Thank for your reply, and I find if I want to use YOLODataset, I need to initialize like this
```
ds = YOLODataset(
    img_path,
    label_path
)
``` 
But right now, my structure of **keypoint** dataset is following:

- train
   - img1.jpg
   - img1.txt (each line is _class center_x center_y box_w box_h keypoint_x keypoint_y visible_)
   - img2.jpg
   - img2.txt
   - ...
   - ....
 
So should I change my structure of dataset?

**Comment by PiyushKamboj1503** [comment]
> > > > @Ichiruchan in your yaml file, add the following: `path: ./kp_data train: train/images #your image folder name val: val/images #if present test: test/images #if applicable kpt_shape: [1, 3] flip_idx: [0] names: 0: pole`
> > > 
> > > 
> > > Actually, I don't have test dataset and all image are under train/val folder. There is no subfolder _images_.
> > 
> > 
> > See if you are working with object detection dataset, you must be having 1 image and 1 label folder.
> 
> Thank for your reply, and I find if I want to use YOLODataset, I need to initialize like this
> 
> ```
> ds = YOLODataset(
>     img_path,
>     label_path
> )
> ```
> 
> But right now, my structure of **keypoint** dataset is following:
> 
> * train
>   
>   * img1.jpg
>   * img1.txt (each line is _class center_x center_y box_w box_h keypoint_x keypoint_y visible_)
>   * img2.jpg
>   * img2.txt
>   * ...
>   * ....
> 
> So should I change my structure of dataset?

@Ichiruchan kindly make 2 folders insde train by the name 'images' and 'labels'. Seperate out your txt and images in these folders. Then in your YAML file add the train as 'train: train/images' as I mentioned earlier. Do this for Validation as well. Also you can look at the issue mentioned by you above, it has the correct structure marked which you can use for your reference.

**Comment by Ichiruchan** [comment]
It helps me lot. Thank for your reply. I will try this method.

**Comment by glenn-jocher** [comment]
You're welcome, @Ichiruchan! I'm glad to hear that the information provided was helpful. If you run into any more issues or have further questions as you try out the method, don't hesitate to reach out. We're here to help ensure your success with YOLOv8. Happy coding and best of luck with your keypoint detection project! 🌟
