### ISSUE TITLE
How to extract the model architecture(n, s, m, l, x) from a loaded YOLOv8 model?

### ISSUE THREAD

**Issue by SilverStarCoder** [ultralytics/ultralytics#6489]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am currently working with YOLOv8 models and during my workflow, I often save models without the architecture type explicitly in the filename, especially in cases where I use transfer learning or resume training (e.g., using a file named "best.pt"). While I can typically read the name of a freshly trained YOLOv8 model using `model.trainer.args.model`, this approach does not seem to work with files like "best.pt" that do not contain the architecture type (such as "n", "s", "m", "l", "x")  in their name.

Is there a recommended method or a specific attribute within the YOLOv8 model object that I can access to reliably determine the architecture type of a given model file? This information is important for my project's documentation. 

I appreciate any guidance or suggestions you can provide on this matter.

**Comment by glenn-jocher** [comment]
@SilverStarCoder hello,

Thank you for reaching out with your question. When you load a YOLOv8 model using the standard procedures outlined in our documentation, the model object contains all pertinent details including its architecture. If you've lost the original filename that includes the architecture designation, you can still retrieve the architecture type from the model object itself.

Once a YOLOv8 model is loaded into your Python environment, you can inspect the `yaml` attribute of the model object, which holds the model configuration. This configuration includes the structure of the model, like depth and width multiples, which are unique to each "n", "s", "m", "l", "x" architecture variant. By comparing these depth and width multiples with the standard configurations provided in the Ultralytics YOLOv8 model zoo, you can determine which architecture variant your model corresponds to.

Please remember to refer to the comprehensive documentation on our website should you require more detailed guidance on model attributes or working with your YOLOv8 models. Our documentation is designed to help you navigate common tasks and answer many of the questions you might have during your project development.

I hope this information assists you with your project's documentation needs. If you have any more questions or need further assistance, feel free to reach out. We're here to help!

**Comment by PiyushKamboj1503** [comment]
@SilverStarCoder you can look at the architecture using code like Nuetron. Also, the size of the models is a key thing to check.Also, while training, if you are using verbose=True, you can check the args.yaml to determine which kind of model was trained.
