### ISSUE TITLE
ModuleNotFoundError: No module named 'ultralytics.nn.modules.conv'; 'ultralytics.nn.modules' is not a package

### ISSUE THREAD

**Issue by DEHowe25** [ultralytics/ultralytics#6492]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

我想把我自己训练的pt模型转换成onnx模式，但是用如下的代码将会报错
`
from ultralytics import YOLO

model = YOLO("./best4.pt")  

path = model.export(format="onnx",simplify=True,opset=13) 
`

同时，如果运行如下代码，将不会报错。
`
from ultralytics import YOLO

model = YOLO("./best4.pt")  

path = model.export(format="onnx",simplify=True,opset=13) 
`
请提供一种能把pt转换成onnx的方法：用python代码，或用命令行，谢谢！

**Comment by glenn-jocher** [comment]
@DEHowe25 您好！感谢您使用YOLOv8。

看起来您遇到了导入模块的问题。您提供的两份代码片段是相同的，我猜测第二个代码片段可能是您想展示不会导致错误的代码。对于`ModuleNotFoundError`的问题，这通常是由于安装过程中发生的问题，或者您的环境可能还没有设置正确。

确保您已正确安装了YOLOv8，并且您的环境变量是指向正确的位置。假设您使用的是包含YOLOv8的正确环境，您可以尝试重新安装YOLOv8以确保所有依赖都已正确安装。

关于将`.pt`模型转换为`.onnx`格式的部分，利用我们的命令行界面（CLI）是一个非常直接的方法。您可以使用以下命令：

```
python path/to/yolov8/export.py --weights ./best4.pt --img-size 640 640 --batch-size 1 --device 0 --simplify --opset 13 --include onnx
```

此命令将会加载您的`best4.pt`模型，并将其导出为`.onnx`格式，同时也会使用您指定的简化和opset版本。确保把`path/to/yolov8/`替换为实际YOLOv8代码所在目录的路径。

如果您希望继续使用Python代码来完成转换，您可能需要提供更多的错误信息才能确切地找到问题所在。但首先，请确保您已正式从我们的repo里安装了YOLOv8，并且确认`ultralytics`包是可以在您的环境中正确找到的。

希望这能帮助到您！如果还有其他问题，欢迎您继续在[issues](https://github.com/ultralytics/ultralytics/issues)中提问。🤗
