### ISSUE TITLE
Сhanging the aspect ratio of an image

### ISSUE THREAD

**Issue by SafrMSD** [ultralytics/ultralytics#650]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

When training, the image is resized to a given size while maintaining the aspect ratio, I would like to be able to turn off the aspect ratio or manually set the desired aspect ratio of the image

### Use case

When working with images that have a large difference between the width and height, information is lost, which significantly worsens the learning result.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@SafrMSD hi there! 😊

When training with YOLOv8, the images are indeed resized to a given size while maintaining their aspect ratio. To manually control the aspect ratio or disable it, you can modify the resize process in the data augmentation pipeline within your training script. This can be achieved by customizing the image transformation logic to suit your specific needs.

Adapting the aspect ratio handling in the data augmentation pipeline should help preserve information in images with significant differences between their width and height, improving the training results.

If you have any questions on how to implement this customization, feel free to ask for further guidance!
