### ISSUE TITLE
Allow to disable mosaic image uploading in debug samples in ClearML

### ISSUE THREAD

**Issue by darouwan** [ultralytics/ultralytics#6501]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I find if I enable visualization tool like ClearML to collect training metrics, the ClearML plugin will upload the mosaic images and it may cause potential privacy risk in the company. Should we consider implementing a parameter that allows the disabling of mosaic image uploading function?

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@darouwan hello! Thank you for reaching out with your feature request and offering to contribute via a PR.

We understand your concern regarding the potential privacy risk when using visualization tools like ClearML in a company environment. It's definitely a valid point to consider implementing an option to disable the uploading of mosaic images to maintain privacy.

The idea of adding a parameter to control this is a good one, and we're open to improvements that help ensure the privacy and security of our users' data. Your initiative to submit a PR is much appreciated, and we encourage contributions that enhance the functionality and usability of YOLOv8 for all members of the community.

Considering your readiness to help, you can go ahead and implement the parameter that toggles the mosaic visualizations on and off. Make sure the default setting keeps the current behavior (which is to upload images), so the change is backwards compatible. Once you have your PR ready, please follow the contributing guidelines detailed in our repository and submit your PR for review.

We look forward to your contribution, and should you have any further questions or require assistance as you work on this, feel free to reach out!

Happy coding 😊!

**Comment by PiyushKamboj1503** [comment]
@darouwan I would love to look at your solution as I am facing a similar issue. If you need any help in this, please reach out to me so that I can contribute to the work as well. Also, can we extend the same to COMET and WANDB?

**Comment by darouwan** [comment]
@PiyushKamboj1503  Sure. I am happy to do the same implementation on CONMET and WANDB.

**Comment by darouwan** [comment]
@PiyushKamboj1503  I have uploaded my code on https://github.com/darouwan/ultralytics/tree/feature/disable-mosaic-image-uploading and you can test it. But I cannot find the mosaic image uploading function in WANDB, can you help to find it?

**Comment by darouwan** [comment]
Ref #6576

**Comment by PiyushKamboj1503** [comment]
> @PiyushKamboj1503  I have uploaded my code on https://github.com/darouwan/ultralytics/tree/feature/disable-mosaic-image-uploading and you can test it. But I cannot find the mosaic image uploading function in WANDB, can you help to find it? 

Sure, let me have a look and I will update!

**Comment by darouwan** [comment]
@PiyushKamboj1503 By the way , I also add the  best model uploading disabling feature to avoid privacy issue.

**Comment by glenn-jocher** [comment]
@darouwan @PiyushKamboj1503 this already exists with `plots=False`. 

You can also add any custom requirements you have rather than updating the codebase with callbacks, i.e. in `on_model_save` you can delete checkpoints and then no checkpoints will upload. 

https://docs.ultralytics.com/reference/utils/callbacks/base/?h=on_model_#ultralytics.utils.callbacks.base.on_model_save
