### ISSUE TITLE
facial recognition + yolov8

### ISSUE THREAD

**Issue by Rasantis** [ultralytics/ultralytics#6506]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi ultralytics team, its possible to run facial recognition in yolov8 ? If it´s not yet i would like to contrib in this feature !

**Comment by RizwanMunawar** [comment]
@Rasantis YOLOv8 currently provides support for object detection, pose estimation, object segmentation, and object tracking. Unfortunately, facial recognition is not available at the moment. We have plans to include this feature in the next year. If you're interested in contributing, please feel free to open a pull request (PR).

Thanks
