### ISSUE TITLE
checkpoint state_dict as FP32

### ISSUE THREAD

**Issue by AFallDay** [ultralytics/ultralytics#6508]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm using the pruning method for yolov5s and I'm getting the error shown below.
![image](https://github.com/ultralytics/ultralytics/assets/144637847/617e1ec1-8832-4806-8a96-d452665b8063)
how can I solve the problem, thanks.

**Comment by RizwanMunawar** [comment]
@AFallDay, the problem pertains to Ultralytics YOLOv5. Kindly create this issue within the YOLOv5 repository. I am closing this issue here!

Thanks
