### ISSUE TITLE
 ModuleNotFoundError: No module named 'super_gradients'

### ISSUE THREAD

**Issue by manoj-samal** [ultralytics/ultralytics#6514]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

yolo predict model=yolo_nas_s.pt source= bus.jpg

i ran the code but got the following error in python version 3.8.0

### Additional

WARNING ⚠️ yolo_nas_s.pt appears to require 'super_gradients', which is not in ultralytics requirements.
AutoInstall will run now for 'super_gradients' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
requirements: Ultralytics requirement ['super_gradients'] not found, attempting AutoUpdate...
  error: subprocess-exited-with-error

  × Building wheel for pycocotools (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/pycocotools
      copying pycocotools/cocoeval.py -> build/lib.linux-x86_64-cpython-38/pycocotools
      copying pycocotools/coco.py -> build/lib.linux-x86_64-cpython-38/pycocotools
      copying pycocotools/mask.py -> build/lib.linux-x86_64-cpython-38/pycocotools
      copying pycocotools/__init__.py -> build/lib.linux-x86_64-cpython-38/pycocotools
      running build_ext
      Compiling pycocotools/_mask.pyx because it changed.
      [1/1] Cythonizing pycocotools/_mask.pyx
      building 'pycocotools._mask' extension
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/common
      creating build/temp.linux-x86_64-cpython-38/pycocotools
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/tmp/pip-build-env-ve2eu19i/overlay/lib/python3.8/site-packages/numpy/core/include -I./common -I/home/TCL_env/include -I/usr/include/python3.8 -c ./common/maskApi.c -o build/temp.linux-x86_64-cpython-38/./common/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
      ./common/maskApi.c: In function ‘rleToBbox’:
      ./common/maskApi.c:151:32: warning: unused variable ‘xp’ [-Wunused-variable]
           uint h, w, xs, ys, xe, ye, xp, cc; siz j, m;
                                      ^~
      ./common/maskApi.c: In function ‘rleFrPoly’:
      ./common/maskApi.c:197:3: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
         for(j=0; j<k; j++) x[j]=(int)(scale*xy[j*2+0]+.5); x[k]=x[0];
         ^~~
      ./common/maskApi.c:197:54: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
         for(j=0; j<k; j++) x[j]=(int)(scale*xy[j*2+0]+.5); x[k]=x[0];
                                                            ^
      ./common/maskApi.c:198:3: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
         for(j=0; j<k; j++) y[j]=(int)(scale*xy[j*2+1]+.5); y[k]=y[0];
         ^~~
      ./common/maskApi.c:198:54: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
         for(j=0; j<k; j++) y[j]=(int)(scale*xy[j*2+1]+.5); y[k]=y[0];
                                                            ^
      ./common/maskApi.c: In function ‘rleToString’:
      ./common/maskApi.c:243:7: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
             if(more) c |= 0x20; c+=48; s[p++]=c;
             ^~
      ./common/maskApi.c:243:27: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
             if(more) c |= 0x20; c+=48; s[p++]=c;
                                 ^
      ./common/maskApi.c: In function ‘rleFrString’:
      ./common/maskApi.c:251:3: warning: this ‘while’ clause does not guard... [-Wmisleading-indentation]
         while( s[m] ) m++; cnts=malloc(sizeof(uint)*m); m=0;
         ^~~~~
      ./common/maskApi.c:251:22: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘while’
         while( s[m] ) m++; cnts=malloc(sizeof(uint)*m); m=0;
                            ^~~~
      ./common/maskApi.c:259:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
           if(m>2) x+=(long) cnts[m-2]; cnts[m++]=(uint) x;
           ^~
      ./common/maskApi.c:259:34: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
           if(m>2) x+=(long) cnts[m-2]; cnts[m++]=(uint) x;
                                        ^~~~
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/tmp/pip-build-env-ve2eu19i/overlay/lib/python3.8/site-packages/numpy/core/include -I./common -I/home/TCL_env/include -I/usr/include/python3.8 -c pycocotools/_mask.c -o build/temp.linux-x86_64-cpython-38/pycocotools/_mask.o -Wno-cpp -Wno-unused-function -std=c99
      pycocotools/_mask.c:47:10: fatal error: Python.h: No such file or directory
       #include "Python.h"
                ^~~~~~~~~~
      compilation terminated.
      /tmp/pip-build-env-ve2eu19i/overlay/lib/python3.8/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-p66t7c6i/pycocotools_b050950f4e6446d0b117a955664c1bdd/pycocotools/_mask.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects

[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
requirements: ❌ Command 'pip install --no-cache "super_gradients" ' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/TCL_env/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 567, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "/home/TCL_env/lib/python3.8/site-packages/torch/serialization.py", line 1014, in load
    return _load(opened_zipfile,
  File "/home/TCL_env/lib/python3.8/site-packages/torch/serialization.py", line 1422, in _load
    result = unpickler.load()
  File "/home/TCL_env/lib/python3.8/site-packages/torch/serialization.py", line 1415, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'super_gradients'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/TCL_env/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/TCL_env/lib/python3.8/site-packages/ultralytics/cfg/__init__.py", line 419, in entrypoint
    model = YOLO(model, task=task)
  File "/home/TCL_env/lib/python3.8/site-packages/ultralytics/engine/model.py", line 97, in __init__
    self._load(model, task)
  File "/home/TCL_env/lib/python3.8/site-packages/ultralytics/engine/model.py", line 149, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/home/TCL_env/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 628, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/home/TCL_env/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 583, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "/home/TCL_env/lib/python3.8/site-packages/torch/serialization.py", line 1014, in load
    return _load(opened_zipfile,
  File "/home/TCL_env/lib/python3.8/site-packages/torch/serialization.py", line 1422, in _load
    result = unpickler.load()
  File "/home/TCL_env/lib/python3.8/site-packages/torch/serialization.py", line 1415, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'super_gradients'

**Comment by manoj-samal** [comment]
guys i got this issue solved 
https://github.com/Deci-AI/super-gradients/tree/master

in this link you will find  `src/super_gradients`

so copy that super_gradients and paste into  your internal site-packages

**Comment by glenn-jocher** [comment]
@manoj-samal hello and thank you for sharing your solution with the community!

It's great to hear that you've managed to resolve the issue with the `super_gradients` module by manually copying it to your virtual environment's site-packages. Your proactive approach can certainly help others who might encounter similar issues.

For users who may come across this discussion, keep in mind that manually copying dependencies into the site-packages directory is an unorthodox solution and generally not recommended because it might lead to inconsistent environments and hard-to-debug issues in the future. It's better to manage dependencies through the package manager (`pip`) whenever possible.

Moreover, using the official Ultralytics models, such as `yolov8n.pt`, should typically bypass the need for `super_gradients` and other dependencies not included in the Ultralytics requirements.

If any other questions or issues arise, feel free to reach out. The YOLO community and Ultralytics team are here to support your work with YOLOv8!

Happy coding! 😊
