### ISSUE TITLE
Issue when using tensors as prediction inputs

### ISSUE THREAD

**Issue by lucalazzaroni** [ultralytics/ultralytics#6519]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I want to pass a tensor to the `model()` function. However, I noticed that, when I use an image as an input (1280x960), it is automatically resized to 640x480 and the output is correctly printed. On the other hand, when I use the same image as a tensor, it is not resized (original dimension is kept) and the prediction is different. Also, the tensor prediction output is BGR instead of RGB.

Here you can find two results when not resizing the input by hand.
![image_prediction](https://github.com/ultralytics/ultralytics/assets/26137413/7d9d62f4-674a-4f59-a6c5-9e4ff57cd2af)

![tensor_prediction](https://github.com/ultralytics/ultralytics/assets/26137413/5d84e3eb-0dec-4f56-8058-3f34a9296725)

### Environment

Ultralytics YOLOv8.0.215 🚀 Python-3.8.18 torch-1.13.0+cu116 CUDA:0 (NVIDIA GeForce RTX 3050 Ti Laptop GPU, 3913MiB)
Setup complete ✅ (16 CPUs, 15.4 GB RAM, 113.4/122.5 GB disk)

OS                  Linux-5.15.0-89-generic-x86_64-with-glibc2.17
Environment         Linux
Python              3.8.18
Install             pip
RAM                 15.36 GB
CPU                 11th Gen Intel Core(TM) i7-11800H 2.30GHz
CUDA                11.6

matplotlib          ✅ 3.7.4>=3.3.0
numpy               ✅ 1.24.2>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 1.13.0+cu116>=1.8.0
torchvision         ✅ 0.14.0+cu116>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

Here is the code to reproduce:
```
from PIL import Image
from ultralytics import YOLO
from torchvision import transforms

model = YOLO('your_model.pt')
image = Image.open('path/to/img')
image_t = transforms.ToTensor()(image)
image_t = image_t[None,:,:,:]
results = model(image)
results_t = model(image_t)
# Show the results
for r in results:
    im_array = r.plot()  # plot a BGR numpy array of predictions
    im = Image.fromarray(im_array[..., ::-1])  # RGB PIL image
    im.show()  # show image
    
# Show the results
for r in results_t:
    im_array = r.plot()  # plot a BGR numpy array of predictions
    im = Image.fromarray(im_array[..., ::-1])  # RGB PIL image
    im.show()  # show image
```
If I resize both images prediction results are compliant but tensor prediction is still in BGR:
```
from PIL import Image
from ultralytics import YOLO
from torchvision import transforms

model = YOLO('your_model.pt')
image = Image.open('path/to/img')
resizer = transforms.Resize((384, 640))
image_t = resizer(image)
image = resizer(image)
image_t = transforms.ToTensor()(image_t)
image_t = image_t[None,:,:,:]
results = model(image)
results_t = model(image_t)
# Show the results
for r in results:
    im_array = r.plot()  # plot a BGR numpy array of predictions
    im = Image.fromarray(im_array[..., ::-1])  # RGB PIL image
    im.show()  # show image
    
# Show the results
for r in results_t:
    im_array = r.plot()  # plot a BGR numpy array of predictions
    im = Image.fromarray(im_array[..., ::-1])  # RGB PIL image
    im.show()  # show image
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@lucalazzaroni hello and thank you for bringing up this issue. Let's address the concerns you've raised regarding the behavior you've experienced when using tensors as prediction inputs.

Firstly, regarding the automatic resizing when using images: YOLOv8's `model()` function is designed to handle input preprocessing, including resizing, for you when working directly with image files. This ensures that the images are in an expected format that the network can properly interpret.

As for the tensor inputs, when you convert an image to a tensor, the preprocessing steps that were automatically applied to an image file are not implicitly applied to the tensor. Therefore, if you'd like to pass a tensor to the `model()` function, you would need to handle resizing and color conversion (RGB to BGR or vice versa) manually. This explains why you need to resize the image tensor before passing it to the model to get the correct results and why the channels are not in the expected order.

In summary, to ensure consistent predictions between image inputs and tensor inputs, pre-process your tensors to match the input requirements of the model (in terms of both size and color channel ordering). The results you've shown after resizing both the image and tensor inputs indicate that you are on the right path. To address the issue of BGR vs RGB channel ordering, ensure that tensors you pass to the model are in the correct color space as expected by YOLOv8, which generally operates on RGB input.

If you'd like more detailed guidelines on how each component of YOLOv8 handles different types of inputs and expected formats, please refer to the Ultralytics Documentation.

Your willingness to share this problem helps us improve the documentation and tools for everyone in the YOLO community. We encourage users to continue to post any findings that may help others effectively use YOLOv8. If you have any follow-up questions or need further assistance, feel free to ask. Thank you for your contribution! 🙌

**Comment by lucalazzaroni** [comment]
@glenn-jocher  thank you for your prompt response. Wouldn't be good to point this out in the documentation? From what I found [here](https://docs.ultralytics.com/modes/predict/#inference-sources) it is not that evident, especially the RGB-BGR difference when using tensors and when using images.

Also, I noticed that. when using tensors, the BGR issue is visible also in bounding boxes, which may indicates that the issue is internal to the library(?). Could you help in understanding where should I put hands in the code to fix this?

**Comment by glenn-jocher** [comment]
Hello @lucalazzaroni, I appreciate your feedback regarding the documentation. It's vital for us to have clear instructions, and your input helps us improve the user experience.

Your suggestion to make the preprocessing requirements more transparent in the documentation, particularly about the color space and image resizing when using tensors, is a good one. Clarifying these aspects can indeed help future users avoid similar issues. I will take your suggestion into consideration to enhance our documentation, ensuring that it provides clearer guidance on how to prepare input data in different formats.

Regarding the BGR issue with tensors, including the appearance of this problem in bounding box colors, you're raising an interesting point that might suggest an area for internal review. I will investigate this behavior to understand whether there is a deeper cause within the library that needs addressing. We aim to ensure consistent behavior and output, regardless of input format, and insights like yours are invaluable for this process.

Once again, thank you for your contributions. Your attention to detail and willingness to engage with us helps to enhance YOLOv8 for everyone. If you encounter any more anomalies or have additional suggestions, please don't hesitate to reach out. We're here to support and work with the community in strengthening our toolset. 👍
