### ISSUE TITLE
Input Images Size

### ISSUE THREAD

**Issue by REZIZ-TER** [ultralytics/ultralytics#6540]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I saw it in the documentation for Yolo v8. That the default image size is 640 pixels. I have a question if the image that I exported from the Roboflow website to train the model uses a custom size, such as 1920x1080.

![image](https://github.com/ultralytics/ultralytics/assets/67143657/5437725b-909c-450e-b7e8-bc824138bf99)
![image](https://github.com/ultralytics/ultralytics/assets/67143657/cdca1028-8b57-4f4d-95d0-30b9f503fc39)

**Comment by RizwanMunawar** [comment]
If you've exported an image with a custom size, like 1920x1080, for training a YOLOv8 model, it's important to note that YOLOv8 can handle custom image sizes. However, you may need to make adjustments in the training configuration to ensure optimal performance with these dimensions.

You can set the imgsz during training that matches your needs. i.e

```yolo task=detect mode=train data=data.yaml imgsz=1920```

For more info, you can check our docs: https://docs.ultralytics.com/modes/train/#usage-examples

Thanks
