### ISSUE TITLE
The folder numbers during the training process are not in order.

### ISSUE THREAD

**Issue by jaylongnwnr** [ultralytics/ultralytics#6541]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

During the training process, I found that my folder can be changed from 1 to 2, but when it changes from 2 to 3, it will become 22. I think it is quite strange. I wonder if anyone has encountered similar problems.

**Comment by RizwanMunawar** [comment]
@jaylongnwnr, appreciate you sharing this information. Could you provide more details about the issue you're encountering? Additionally, could you elaborate on what you mean by the folder change?

**Comment by jaylongnwnr** [comment]
@RizwanMunawar  Hello,
For example, if I run 200 epochs during training, it will not produce train 1~train 200.
Are the folders in order? But when I want to generate train3, the field will change to train22.
I think this is abnormal. This problem occurred after I updated your package.

**Comment by glenn-jocher** [comment]
Hello @jaylongnwnr, thank you for reporting this and providing additional context.

The training runs should indeed be sequentially named in ascending order, typically starting from 'train1' for the first run, 'train2' for the second, and so on. However, it seems like you're experiencing a naming discrepancy where 'train3' becomes 'train22' unexpectedly.

This behavior is non-standard and could potentially be related to a recent change in the codebase or a unique situation in your environment. To help resolve this, please ensure you've pulled the latest version from the YOLOv8 repo and that there are no remnants from previous experiments that might cause conflicts with the new run's directory creation.

If the issue persists after making sure everything is up-to-date and clean, please open a new issue on the YOLOv8 GitHub repository, providing the full details and any error logs you encounter. This will allow the team to investigate further. Your contributions help improve YOLOv8 for everyone, and we truly value your feedback.

Remember, our documentation can always be referred to for the latest guidance and instructions. Thank you for participating actively in our community! 🚀
