### ISSUE TITLE
Yolo val mode for yolo_nas models

### ISSUE THREAD

**Issue by tjasmin111** [ultralytics/ultralytics#6550]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

According to Ultralytics docs [here](https://docs.ultralytics.com/models/yolo-nas/#usage-examples), we can use yolo to do predictions/val of a yolo-nas model like below:
`yolo val model=yolo_nas_s.pt data=coco8.yaml
`

I trained my NAS model following [this tutorial](https://www.google.com/amp/s/blog.roboflow.com/yolo-nas-how-to-train-on-custom-dataset/amp/?espv=1), but it produces a .pth model (not .pt). So when I pass it to yolo, it complains about it. What should I do?

**Comment by glenn-jocher** [comment]
@tjasmin111 hello,

Thank you for reaching out. The YOLOv8 `val` mode indeed expects a `.pt` file, which is the standard extension for models saved after training with YOLOv8.

The `.pth` file you have could be from a training session not using our standard YOLOv8 training pipeline. To resolve this, you would need to ensure that you're following the procedures from the Ultralytics documentation, especially for training a YOLO-NAS model. The output from training with our tools should save the model as a `.pt` file by default.

If you did train the model using our YOLOv8 pipeline and the file is still saved as `.pth`, this might suggest a possible issue with the training script or environment. In that case, please double-check the training command and make sure all necessary dependencies are correctly installed.

For detailed insights specific to YOLO-NAS and other YOLOv8 models, please refer to our comprehensive documentation available at https://docs.ultralytics.com, which will guide you through the correct usage and expected outcomes.
