### ISSUE TITLE
local variable 'ckpt_file' referenced before assignment

### ISSUE THREAD

**Issue by shortsonghh** [ultralytics/ultralytics#6560]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I followed the tutorial and did this, but why did I get an error?  (‾◡◝)
![Snipaste_2023-11-24_14-21-37](https://github.com/ultralytics/ultralytics/assets/130122649/e33700da-5f87-449b-87b0-f3a9b169d0d6)

![Snipaste_2023-11-24_14-21-48](https://github.com/ultralytics/ultralytics/assets/130122649/d8b15dab-90b8-46a0-ac8f-ab5429a8c768)

**Comment by glenn-jocher** [comment]
@shortsonghh hello! Thank you for reaching out with your issue regarding the 'ckpt_file' variable. This error typically occurs if there's a problem with the checkpoint file path or the directory structure expected by the script. To resolve the issue, ensure you're providing the correct path to your checkpoint file and your directory structure matches what the training script expects.

Please double-check the path you've specified and the command you're using to initiate your training or evaluation script. If the checkpoint file is not in the expected location or if it's missing, you will encounter this error.

The error you experienced is not a typical behavior and might indicate an edge case that the community or I have not handled yet. For further assistance, you can utilize the Ultralytics Docs, which provide an extensive guide to help you through the correct setup and running processes. If the problem persists, feel free to raise an issue in the YOLOv8 repo with the exact command and scenarios that lead to the failure, so we can help you more effectively.

Remember, the entire Ultralytics team is here to support you, and contributions from users like you help us make the models better for everyone. Thank you for being a part of the YOLO community! 😊👍

**Comment by shortsonghh** [comment]
I guess it's an issue with library installation. Previously, I didn't install Ultratics as a third-party library, but directly dragged it into my project file. After the later corrections, the program can run normally.
From my observation, when not installed as a third-party library, 'subprocess' was unable to start the child process of the 'yolo ' command, resulting in an error.

![image](https://github.com/ultralytics/ultralytics/assets/130122649/c3a8f22a-7936-485b-9f23-71b5fe73380c)

Also, may I ask if YOLO has a clear interface for image preprocessing. I can't find them     ≡(▔﹏▔)≡

**Comment by glenn-jocher** [comment]
@shortsonghh, I'm glad to hear you were able to resolve the issue by correctly installing Ultralytics as a library. Regarding subprocess issues, it's indeed crucial that the environment is set up correctly to ensure the `subprocess` module can invoke the necessary commands.

About image preprocessing, YOLOv8, like other YOLO versions, encapsulates preprocessing operations within the model's pipeline. These steps are handled automatically during training and inference. Preprocessing typically includes operations such as resizing, normalization, and augmentation, which are integral to ensure the model receives data in the correct format.

If you're looking to customize or understand the preprocessing steps, you can review the Ultralytics Docs, specifically designed to cover all aspects of model usage including data preprocessing. Although a direct preprocessing interface is not standalone, the data loader and dataset configuration manage these functionalities for you.

For special preprocessing needs beyond the standard pipeline, you can write custom code to preprocess your images before feeding them into the YOLOv8 model. Keep in mind that any custom preprocessing should align with the expectations of the input layer of the model to ensure optimal performance.

If you have any further questions or require more detailed guidance on the preprocessing steps, please refer back to the Ultralytics Docs or ask specific questions in the repo's issues; the community and the Ultralytics team are always eager to help! 🤝😄

**Comment by 1468mikasa** [comment]
Good work, good answers,

**Comment by glenn-jocher** [comment]
@1468mikasa thank you so much for the kind words! 😊 If you have any more questions or need further assistance, feel free to ask. Happy coding! 🚀

**Comment by LennyJS** [comment]
Hey,
I usted pip install to install ultralytics, but still have the unbounded error. I want to tune the hyperparameters of a non-pretrained yolov8 model and a custom dataset. Can somebody help me with that?

**Comment by glenn-jocher** [comment]
@LennyJS hey there! 👋

It looks like you may be encountering issues after installation. To tune hyperparameters for a non-pretrained YOLOv8 model on a custom dataset, ensure that your installation of Ultralytics is up-to-date and properly set up. You can do this by running:

```bash
pip install ultralytics --upgrade
```

Then to adjust hyperparameters, you can edit the `hyp.yaml` file linked to your train command, like so:

```bash
yolo train --data your_dataset.yaml --cfg yolov8.yaml --weights '' --hyp your_hyp.yaml
```

In `your_hyp.yaml`, you can customize hyperparameters according to your needs. If the "unbounded error" persists, could you provide more detail about the error message? This will help in offering a more specific solution. 🙂

Happy tuning!

**Comment by LennyJS** [comment]
@glenn-jocher  hey,
well I already upgraded it and now I want to use the model.tune() method with this code:

model = YOLO('yolov8n.yaml')

# Tune hyperparameters on custom dataset for 30 epochs
model.tune(data='datasets/master/data.yaml', epochs=30, iterations=300, optimizer='Adam', plots=True, save=False, val=True)

when entering the code I get the same error as above:
UnboundLocalError: local variable 'ckpt_file' referenced before assignment

**Comment by LennyJS** [comment]
Hey,
is the issue solved?
I tried to run the code above, but still get the same error.

**Comment by glenn-jocher** [comment]
@LennyJS hey! 👋

Sorry to hear you're still facing the issue. It seems like there's a hiccup where the checkpoint file (ckpt_file) isn't being properly referenced or generated during the tuning process. This might be due to how the tuning setup is initializing. 

Could you try explicitly defining the checkpoint path in your code to see if that resolves the issue? Here's a quick modification you can make:

```python
model.tune(data='datasets/master/data.yaml', epochs=30, iterations=300, optimizer='Adam', plots=True, save=False, val=True, ckpt_path='path/to/your/checkpoint.ckpt')
```

Please replace `'path/to/your/checkpoint.ckpt'` with the actual path where you'd like your checkpoint file to be saved. This might help bypass the hiccup. If the error persists, would you mind providing the full error message or any additional context? That would greatly aid in pinpointing the solution. 

Thanks for your patience!

**Comment by LennyJS** [comment]
@glenn-jocher  Hey,
I don't get the ckpt_file so I guess it is not generated.

I tried again and get exactly the same error as in the image at which started this conversation.

**Comment by glenn-jocher** [comment]
@LennyJS hey there! 🙋‍♂️

It sounds like there's an issue generating or finding the checkpoint file during the `tune()` process. Let's try defining a checkpoint path explicitly to guide the process a bit. Here’s how you can adjust your code:

```python
model.tune(data='datasets/master/data.yaml', epochs=30, iterations=300, optimizer='Adam', plots=True, save=True, val=True, ckpt_path='runs/train/exp')
```

By setting `save=True`, we ensure that the model checkpoints get saved, and specifying `ckpt_path` directs where those checkpoints should go. The path `'runs/train/exp'` is just an example; please adjust it to fit your directory structure. 

If this doesn't resolve the issue or you’re already doing something similar, could you verify the write permissions in your target directory or try a different location to save the checkpoints? Sometimes, simple things like directory permissions can trip us up.

Let me know how it goes!

**Comment by LennyJS** [comment]
So I tried the old code again and your update:
This is the error of the old code:
UnboundLocalError                         Traceback (most recent call last)
[<ipython-input-8-66f4cfff59fa>](https://localhost:8080/#) in <cell line: 8>()
      6 ckpt_path='contents/dataset/tune'
      7 # Tune hyperparameters on custom skate spot dataset for 30 epochs
----> 8 model.tune(data='/content/datasets/Masterthesis-12/data.yaml', epochs=30, iterations=300, optimizer='Adam', plots=True, save=True, val=True)

1 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/tuner.py](https://localhost:8080/#) in __call__(self, model, iterations, cleanup)
    205                     shutil.copy2(ckpt, self.tune_dir / 'weights')
    206             elif cleanup:
--> 207                 shutil.rmtree(ckpt_file.parent)  # remove iteration weights/ dir to reduce storage space
    208 
    209             # Plot tune results

UnboundLocalError: local variable 'ckpt_file' referenced before assignment


using the new code which has ckpt_file='mypath/to' in the tune argument results in this error:
File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File ["<ipython-input-9-0982539e3ef4>"](https://localhost:8080/#), line 8, in <cell line: 8>
    model.tune(data='/content/datasets/Masterthesis-12/data.yaml', epochs=30, iterations=300, optimizer='Adam', plots=True, save=True, val=True, ckpt_path='contents/dataset/tune')

  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 366, in tune
    return Tuner(args=args, _callbacks=self.callbacks)(model=self, iterations=iterations)

  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/tuner.py", line 68, in __init__
    self.args = get_cfg(overrides=args)

  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 113, in get_cfg
    check_dict_alignment(cfg, overrides)

  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 203, in check_dict_alignment
    raise SyntaxError(string + CLI_HELP_MSG) from e

  File "<string>", line unknown
SyntaxError: 'ckpt_path' is not a valid YOLO argument. Similar arguments are i.e. ['copy_paste=0.0'].

**Comment by glenn-jocher** [comment]
Hey there! 👋 It looks like there's a bit of confusion around the `ckpt_path` argument, which isn't a recognized argument for the `tune()` method, hence the errors you're encountering.

The `UnboundLocalError` suggests a problem with how the checkpoint file path is being handled internally. Since specifying `ckpt_path` directly in `tune()` isn't working (and isn't accepted according to the error message you received), let's skip specifying it and ensure `save=True` is set, as you've done. This should save the checkpoints in a default directory. 

Here’s a snippet without `ckpt_path`:
```python
model.tune(data='/content/datasets/Masterthesis-12/data.yaml', epochs=30, iterations=300, optimizer='Adam', plots=True, save=True, val=True)
```

Make sure your `data.yaml` and paths are correctly set, and try running your tuning operation again. If the issue persists, it might be good to check for any updates or existing issues in the Ultralytics GitHub repo that might shed some light on this error. Sometimes, the solution is just an update away! 🚀

Hope this helps, and let me know if you have any further questions!

**Comment by georgelele1** [comment]
i have faced the exactly same error is there any solution to the problem ?

**Comment by glenn-jocher** [comment]
Hey there! 👋 It seems like you're experiencing an issue with the `UnboundLocalError` during model tuning. This error might be related to internal checkpoint handling.

As a quick suggestion, make sure you're using the latest version of the Ultralytics package. You can update by running:

```bash
pip install ultralytics --upgrade
```

Then, for tuning, you don't need to specify a `ckpt_path`. Simply use:

```python
model.tune(data='your_data.yaml', epochs=30, iterations=300, optimizer='Adam', plots=True, save=True, val=True)
```

Make sure your paths and file names are correct, and keep `save=True` for automatically managing checkpoints.

If the issue persists, it could be helpful to check if there's an open issue or consider opening a new one on the [Ultralytics GitHub](https://github.com/ultralytics/ultralytics) page for more specific guidance.

Hope this helps! 🚀

**Comment by georgelele1** [comment]
unfortunate, the solustion you have provided dose not help at all the problem still exist 
<img width="1400" alt="image" src="https://github.com/ultralytics/ultralytics/assets/43303561/b5d07365-f0f9-4c25-9935-a9a37cd3b8dd">
in this case i even used exactly code you have provided and it still cause me error for the same reason!
Looking forward to hear you back!

**Comment by glenn-jocher** [comment]
Hey there! 🌟 Thanks for reaching out and sharing the details of the issue you're encountering during the tuning process. It looks like there's an `UnboundLocalError`, which typically points to a variable being used before it has been assigned a value within the local scope.

For the tune method in Ultralytics YOLO, ensuring all required parameters are correctly set up is crucial. If you're following the exact provided code snippet and still facing issues, this could hint at an internal bug or a specific scenario that isn't handled as expected.

From your end, please make sure:
- Your dataset path in `data.yaml` is correct and accessible.
- You're using the latest version of the Ultralytics library. (`pip install ultralytics --upgrade`)

In the meantime, our team will investigate this issue for potential bugs. 🐛 If you could open an issue on our GitHub with the error log and details about your environment (`python version`, `library version`, etc.), it will be super helpful!

Thanks for your patience! 🚀
