### ISSUE TITLE
Yolov8 Region Counter - How do I decide what object class to count

### ISSUE THREAD

**Issue by yeongnamtan** [ultralytics/ultralytics#6566]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In Yolov8 region counter, how do I tell the counter what object to count ?  eg. there could be people, objects, etc within the polygon area.

**Comment by RizwanMunawar** [comment]
@yeongnamtan The `classes` argument is currently not supported in the `YOLOv8 Region Counter`. We plan to add this feature soon!

Thanks,
Ultralytics Team!

**Comment by RizwanMunawar** [comment]
@yeongnamtan `classes` argument has been added now! Thanks

**Comment by yeongnamtan** [comment]
Thank you @RizwanMunawar . How do u know what classes belong to what? Eg. I only want to count people

**Comment by yeongnamtan** [comment]
@RizwanMunawar can we get region counter to count Boolean AND of object class  "people" and  "handbags". That means only people with handbags are counted

**Comment by RizwanMunawar** [comment]
@yeongnamtan, when using the pretrained model of Ultralytics YOLOv8, you can retrieve information about class IDs and names from the configuration file. This file is accessible at the following link: [Ultralytics YOLOv8 Config File](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/datasets/coco.yaml#L17)

For instance, if your goal is to detect only the 'person' class, you can utilize the provided command:
```
python yolov8_region_counter.py --source "path/to/video.mp4" --classes 0 --weights "yolov8n.pt"
```

It's important to note that there is no built-in support for Boolean operations; if needed, you'll need to implement these independently.

I trust this information proves helpful! Feel free to reach out if you have any further questions.
Thanks.

**Comment by RizwanMunawar** [comment]
@yeongnamtan, I am closing this issue, as it has been successfully resolved. If the problem persists, feel free to reopen the issue.

Thanks.
Ultralytics Team!
