### ISSUE TITLE
Can't find detected output image

### ISSUE THREAD

**Issue by MohamedAtef321** [ultralytics/ultralytics#657]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Trying to detect an image using this code.
```python
%cd {HOME}
!yolo task=detect mode=predict \
 model="/content/drive/MyDrive/yolov8/runs/detect/train7/weights/best.pt" \
 source="/content/drive/MyDrive/yolov8/1.jpg" \
 imgsz=1024
```
and got output saying it's done !
```
/content
Ultralytics YOLOv8.0.20 🚀 Python-3.8.10 torch-1.13.1+cu116 CUDA:0 (Tesla T4, 15110MiB)
Model summary (fused): 168 layers, 3011888 parameters, 0 gradients, 8.1 GFLOPs
image 1/1 /content/drive/MyDrive/yolov8/1.jpg: 1024x768 13.5ms
Speed: 0.9ms pre-process, 13.5ms inference, 0.8ms postprocess per image at shape (1, 3, 1024, 1024)
```
but I can not find output detected image in `runs/detect/`.

### Environment

Google Colab

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MohamedAtef321 sorry for the confusion. No detections were made on your image, therefore no output image was saved. You can lower confidence to force more detections to appear, i.e. `yolo detect model=yolov8n.pt conf=0.01`

You can also pass a project/name combination to save outputs to a specific location: `yolo detect model=yolov8n.pt project=PROJECT name=NAME exist_ok=True`

**Comment by RabbitEngin3er** [comment]
Hello, I made a prediction and I can't find the folder runs/predict or runs/detect/predict. I received this message after launching predict command: 

Ultralytics YOLOv8.0.21 🚀 Python-3.8.10 torch-1.13.1+cu116 CPU
Model summary (fused): 168 layers, 3178697 parameters, 0 gradients, 8.9 GFLOPs
image 1/1 /content/ultralytics/ultralytics/assets/immagine1.jpg: 640x640 1 traffic sign, 1 traffic sign, 257.1ms
Speed: 3.7ms pre-process, 257.1ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

**Comment by mclopes1** [comment]
I'm having the same issue right now. It was working some days ago when I had tested the repository for the first time

**Comment by pcismyname** [comment]
Same problem here even the detection was made
`!yolo task=detect mode=predict model=yolov8n.pt conf=0.01 source='https://media.roboflow.com/notebooks/examples/dog.jpeg'`

`Ultralytics YOLOv8.0.20 🚀 Python-3.8.10 torch-1.13.1+cu116 CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
Found https://media.roboflow.com/notebooks/examples/dog.jpeg locally at dog.jpeg
image 1/1 /content/dog.jpeg: 640x384 5 persons, 3 cars, 1 truck, 2 dogs, 8 backpacks, 9 handbags, 1 tie, 2 bottles, 1 apple, 126.7ms
Speed: 1.2ms pre-process, 126.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)
`

**Comment by pcismyname** [comment]
> @MohamedAtef321 sorry for the confusion. No detections were made on your image, therefore no output image was saved. You can lower confidence to force more detections to appear, i.e. `yolo detect model=yolov8n.pt conf=0.01`

I think no detection is not a problem here. In my case detection was made and there was no output image.
`Ultralytics YOLOv8.0.20 🚀 Python-3.8.10 torch-1.13.1+cu116 CPU YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs Found https://media.roboflow.com/notebooks/examples/dog.jpeg locally at dog.jpeg image 1/1 /content/dog.jpeg: 640x384 5 persons, 3 cars, 1 truck, 2 dogs, 8 backpacks, 9 handbags, 1 tie, 2 bottles, 1 apple, 126.7ms Speed: 1.2ms pre-process, 126.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)`

**Comment by AyushExel** [comment]
pass `save=True`

**Comment by jwillemssens** [comment]
Thanks ! just with the param "save=True" works like a charm!

**Comment by lsylvyy** [comment]
> 通过`save=True`

thx sir!

**Comment by Laughing-q** [comment]
@MohamedAtef321 closing the issue as it's solved, feel free to reopen it if you have any related issues. :)
