### ISSUE TITLE
[Example] YOLOv8 models using Rust and ONNXRuntime (ALL YOLO Tasks included)

### ISSUE THREAD

**Issue by jamjamjon** [ultralytics/ultralytics#6580]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

About issue #6567 

I will provide yolov8 example using ONNXRuntime and Rust which support all yolo tasks(Classification, Segmentation, Detection, Pose(Keypoints)-Detection).

## Main features:
- Using `ort` crate, which is `ONNXRuntime` wrapper for Rust.
- Support `Classification`, `Segmentation`, `Detection`, `Pose(Keypoints)-Detection` tasks.
- Support `FP16` & `FP32` models.
- Support `CUDA` and `TensorRT` execution provider to accelerate computation.
- Support dynamic inputs (`batch`, `width`, `height`).

## Example directory structure
```
YOLOv8-ONNXRuntime-Rust/
├── Cargo.toml
├── README.md
└── src
    ├── ort_backend.rs
    ├── cli.rs
    ├── lib.rs
    ├── main.rs
    ├── model.rs
    ├── yolo_result.rs
    └── roboto-mono-stripped.ttf
```
`Cargo.toml` : Cargo’s configuration. Cargo is Rust’s build system and package manager.

`src/main.rs`, `src/lib.rs`: binary and libraray crate. (https://doc.rust-lang.org/book/ch07-01-packages-and-crates.html)

`cli.rs`:  Command Line Argument Parser.

`ort_backend.rs`:  focus on ONNX model parsing and ort engine building for YOLOv8 model.

`model.rs`: YOLOV8 model predictor.

`yolo_result.rs`: All tasks outputs of each images.
```
YOLOResult {
        Probs(top5): None,
        Bboxes: Some(
            [
                Bbox {
                    xmin: 2.1948547,
                    ymin: 229.68993,
                    width: 799.5898,
                    height: 511.7051,
                    id: 5,
                    confidence: 0.95922613,
                },
                Bbox {
                    xmin: 50.233482,
                    ymin: 399.9382,
                    width: 197.19203,
                    height: 504.88116,
                    id: 0,
                    confidence: 0.92526156,
                },
                ...
            ],
        ),
        Keypoints: None,
        Masks: None,
    },
```

## CLI Arguments
- `--cuda`: use CUDA execution provider to speed up inference.
- `--trt`: use TensorRT execution provider to speed up inference.
- `--fp16`: use TensorRT fp16 model.
- `--device_id`: used for choosing specific device when multi-gpus exists.
- `--model`: onnx model.
- `--source`: image or directory.
- `--plot`: for save results. It will generate a plotted image in `runs` directory.
- `--profile`: It will show time consumed in each stage.
- `--batch` : inference batch. By default, 1.
- `--batch_min` : TensorRT dynamic min_batch. By default, 1.
- `--batch_max` : TensorRT dynamic max_batch. By default, 1.
- `--task`: all ONNX model exported by YOLOv8 will do the task inference automactically. When your onnx model is not exported by YOLOv8 code, you may need to specify your model task.
- `--conf` : confidence threshold
- `--kconf` : keypoint confidence threshold
- `--iou` : iou threshold
- `--width, --height`: used for dynamic input shape(height and width), and model that is not exported by YOLOv8, you should set fixed size before predict.

### generally, run Inference
```
cargo run --release -- --model <MODEL_PATH> --source <IMAGE_PATH> --plot --cuda
```

### Classification
using `CPU`
```
cargo run --release -- --model ../assets/weights/yolov8s-cls.onnx --source ../assets/images/cat.jpg --plot
```
![cls](https://github.com/ultralytics/ultralytics/assets/51357717/6ecf0729-4627-4482-8ad0-d8dfef0b0384)

### Object Detection

using `CUDA` and dynamic input size `--height 640 --width 480`

```
cargo run --release -- --cuda --model ../assets/weights/yolov8m-dynamic.onnx --source ../assets/images/bus.jpg --plot
```
![det](https://github.com/ultralytics/ultralytics/assets/51357717/ee49dbfc-b7f5-4ce8-9686-50a7b602879e)

### Pose

using `TensorRT`

```
cargo run --release -- --trt --model ../assets/weights/yolov8m-pose.onnx --source ../assets/images/bus.jpg --plot
```
![kpt](https://github.com/ultralytics/ultralytics/assets/51357717/bd1fb8b3-4fc5-46cf-be7d-077f6504580a)

### Instance Segmentation

using `TensorRT` and FP16 model `--fp16`

```
cargo run --release --  --trt --fp16 --model ../assets/weights/yolov8m-seg.onnx --source ../assets/images/0172.jpg --plot
```
![seg](https://github.com/ultralytics/ultralytics/assets/51357717/08ebc508-ea12-4bdb-a19f-c4334d58736b)

### Additional

All Rust code passed the tests by `cargo clippy`(https://github.com/rust-lang/rust-clippy#clippy)   and  followed by `cargo fmt`.

That's all about the YOLOv8 Rust example.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jamjamjon hello! 👋

It's genuinely fantastic to hear about your initiative to provide a YOLOv8 example using ONNXRuntime and Rust, supporting all the key YOLO tasks like Classification, Segmentation, Detection, and Pose/Keypoint-Detection. Your effort to build a bridge for YOLOv8 into the Rust ecosystem is an excellent addition to the community. The features you're aiming to include, such as FP16 & FP32 model support and dynamic inputs, are crucial for flexible and efficient model deployment – impressive work! 🚀

I appreciate the detail you've shared about the example directory structure and the functionality each component provides. Also, the variety of CLI arguments ensures users have the control they need to tweak performance and output – that's really thoughtful design.

Your use case examples provide clear insight into the operational setup and potential of the tool, which will be beneficial to those in the Rust community looking to work with YOLOv8 models. The screenshots you've added are sure to make understanding the output much easier for new users.

Your willingness to contribute with a PR is the spirit of open-source at its best, and we would be delighted to review your contribution. Please ensure that the code follows the current repository standards and guidelines regarding code review processes. When you're ready, submit your PR, and we'll take it from there! 🤝

Thank you for enhancing the accessibility and usability of YOLOv8 in such an impactful way! 

If you have any further questions or need assistance, feel free to reach out. Keep up the great work! 🌟

**Comment by jamjamjon** [comment]
Please review the PR!

**Comment by glenn-jocher** [comment]
@jamjamjon thank you for submitting a PR! 🎉

I will be sure to review it as promptly as possible. In the review process, I'll be checking for adherence to our code standards and ensuring the changes align well with the existing YOLOv8 repository structure and functionality. 🧐

Once I've gone through the PR, I will provide feedback directly within the GitHub PR discussion thread. If there are any modifications or additional details needed, we can iterate on that together to get the PR in the best shape for merging. Keep an eye out for comments or requests for changes in the PR thread!

Again, your contribution is very much appreciated, and I'm looking forward to seeing your hard work integrated into the project. Thank you for being a valued member of the YOLO and Ultralytics community! 👍

**Comment by AyushExel** [comment]
@jamjamjon This should be addressed as the PR is merged. Closing this, please re-open in case we missed something
