### ISSUE TITLE
Missing class name when model is exported to Tensorrt for inference

### ISSUE THREAD

**Issue by tung-msol** [ultralytics/ultralytics#659]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

A custom Yolov8 model is exported to engine format. When doing model inference, class names are missing.

The below is the output in log:
video 1/1 (1/7502) sample.mp4: 384x640 4 class0s, 0.0ms
video 1/1 (2/7502) sample.mp4: 384x640 5 class0s, 2.1ms
video 1/1 (3/7502) sample.mp4: 384x640 4 class0s, 0.0ms
video 1/1 (4/7502) sample.mp4: 384x640 5 class0s, 0.0ms

While checking the code, it is found that when calling **AutoBackend** of **[predictor.py](https://github.com/ultralytics/ultralytics/blob/15b3b0365ab2f12993a58985f3cb7f2137409a0c/ultralytics/yolo/engine/predictor.py)**, argument **data** is missing (by default data is None)
`model = AutoBackend(model, device=device, dnn=self.args.dnn, fp16=self.args.half)`

After changing the code to 
`model = AutoBackend(model, device=device, dnn=self.args.dnn, data=self.args.data, fp16=self.args.half)`
class names is correctly presented.

### Environment

-ultralytics: 8.0.5
-pytorch: 1.13.1+cu116
-python: 3.9.12
-window 10 64bit

### Minimal Reproducible Example

yolo task=detect mode=predict model=best.engine source=sample.mp4 imgsz=[384,640] data=custom.yaml

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
yes please make a PR!
