### ISSUE TITLE
Cannot be executed using python 3.12

### ISSUE THREAD

**Issue by yihong1120** [ultralytics/ultralytics#6599]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Cannot be executed using python 3.12

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by yihong1120** [comment]
Cannot be executed using python 3.12

**Comment by glenn-jocher** [comment]
@yihong1120 `torch` does not support 3.12 yet.
