### ISSUE TITLE
pip install  ultralytics is for student or  commercial 

### ISSUE THREAD

**Issue by manoj-samal** [ultralytics/ultralytics#6604]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi Ultralytics, 
As we know  yolov8 is open source and also of commercial cases, but when i do  `pip install  ultralytics` does it gives me student license  or commercial.  
if we do `pip install  ultralytics` please let us know it   will charge us  for callings API's  or not. And if its free we can train a custom model and use it as we want.?

**Comment by glenn-jocher** [comment]
@manoj-samal hello! Thank you for reaching out with your question. 😊

When you use `pip install ultralytics`, you are installing the AGPL-3.0 licensed version of our software, which is free to use for both academic and commercial purposes. However, if you are planning to use it in a commercial product or application, please be aware of the requirements of the AGPL-3.0 license, which stipulates that any modifications to the code or derived works must also be open-sourced.

You will not be charged for calling APIs with the AGPL-3.0 licensed version. You are free to train custom models and use them as you see fit, respecting the conditions of the AGPL-3.0 license.

If your use case requires embedding our software in a commercial product without open-sourcing your derivative works, you're looking at the Enterprise License, which provides that flexibility. The Enterprise License is a separate offering outside the scope of a simple `pip install`.

For more detailed info about the different modes and tasks you can perform with the installed software, you can visit our docs at https://docs.ultralytics.com.

Hope this clears things up for you! If you have any other questions or need further clarification, feel free to ask. Happy coding! 🚀
