### ISSUE TITLE
A dockerfile path matching mistake on Usage Examples at docker/Dockerfile-conda

### ISSUE THREAD

**Issue by NormanBeta** [ultralytics/ultralytics#6607]
On main branch, 29th line at docker/Dockerfile-conda, the name of dockerfile to build should be docker/Dockerfile-conda instead of docker/Dockerfile-cpu

**Comment by glenn-jocher** [comment]
@NormanBeta hello there!

Thank you for bringing this to our attention. It indeed seems like there's a small typo in the path specified in our Usage Examples within the `Dockerfile-conda`. The correct name of the Dockerfile for the Conda environment setup is indeed `docker/Dockerfile-conda`, not `docker/Dockerfile-cpu`. We will make sure to correct this in the documentation to prevent any future confusion.

We always appreciate the community's keen eye for detail, and it's thanks to users like you that we can continue to improve. If you notice anything else or have further feedback or questions, please don't hesitate to tell us.

Happy coding! 🚀
