### ISSUE TITLE
Can't convert mask to numpy array

### ISSUE THREAD

**Issue by Genei565** [ultralytics/ultralytics#6612]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

 I'm trying to use this command "masks = result.masks.cpu().numpy().xy"

And try to print the mask array but can't. I get the following error: 
 
 'Masks' object has no attribute 'xy'. See valid attributes below.

### Environment

I'm using ultralytics 8.0.218 Tried with 8.0.219 and I get the same error.

### Minimal Reproducible Example

from ultralytics import YOLO
import cv2

model = YOLO("Legos2.pt")

cap = cv2.VideoCapture(0)

while True:

    ret, frame = cap.read()

    results = model.predict(frame, imgsz = 640, conf = 0.6)

    for result in results:
        box = result.boxes.cpu().numpy()
        print("Results = ", end="")
        print(len(box))
        if len(box) > 0:
            masks = result.masks.cpu().numpy()
            MyMask = masks.xy
            if box.cls[0] == 0:
                print('Blue Brick')
            elif box.cls[0] == 1:
                print('Red Brick')
            elif box.cls[0] == 2:
                print('Yellow Brick')
            XCoordinate = box.xywh[0][0]
            YCoordinate = box.xywh[0][1]
            print("X = {}".format(XCoordinate))
            print("Y = {}".format(YCoordinate))
            print(MyMask)

    labels = results[0].plot()

    cv2.imshow("Detection", labels)

    if cv2.waitKey(1) == 27:
        break

cap.release()
cv2.destroyAllWindows()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Genei565** [comment]
Solve the issued. I just used the result.mask.xy directly instead

        if len(box) > 0:
            masks = result.masks.xy
            for maskI in masks:
                cv2.polylines(frame, np.int32([maskI]), True, (125, 255, 0), 2)

            if box.cls[0] == 0:
                print('Blue Brick')
            elif box.cls[0] == 1:
                print('Red Brick')
            elif box.cls[0] == 2:
                print('Yellow Brick')
            XCoordinate = box.xywh[0][0]
            YCoordinate = box.xywh[0][1]
            print("X = {}".format(XCoordinate))
            print("Y = {}".format(YCoordinate))
            print(masks[0])

**Comment by glenn-jocher** [comment]
@Genei565 great to hear that you've resolved the issue! 😊 It seems that using `result.masks.xy` directly was the correct approach. Remember, the `xy` attribute is a property of each individual mask object rather than the numpy array. It's rewarding when the community shares solutions. This benefits others who may run into similar challenges. Keep up the good work and don't hesitate to reach out if you encounter any more questions or need further assistance. Happy coding with YOLOv8! 🚀
