### ISSUE TITLE
Error when training on the xView dataset

### ISSUE THREAD

**Issue by holma91** [ultralytics/ultralytics#6613]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

The following code snippets can be found at the documentation for the xView dataset (https://docs.ultralytics.com/datasets/detect/xview/#dataset-yaml):
```py
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)

# Train the model
results = model.train(data='xView.yaml', epochs=100, imgsz=640)
```

However, there seems to be something wrong with the dataset, because if I run the code snippet above I get the following error:
```txt
Dataset 'xView.yaml' images not found ⚠️, missing path '/content/datasets/xView/images/autosplit_val.txt'
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py](https://localhost:8080/#) in __init__(self, cfg, overrides, _callbacks)
    115             elif self.args.data.split('.')[-1] in ('yaml', 'yml') or self.args.task in ('detect', 'segment', 'pose'):
--> 116                 self.data = check_det_dataset(self.args.data)
    117                 if 'yaml_file' in self.data:

3 frames
<string> in <module>

<string> in convert_labels(fname)

FileNotFoundError: [Errno 2] No such file or directory: '/content/datasets/xView/xView_train.geojson'

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py](https://localhost:8080/#) in __init__(self, cfg, overrides, _callbacks)
    118                     self.args.data = self.data['yaml_file']  # for validating 'yolo train data=url.zip' usage
    119         except Exception as e:
--> 120             raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
    121 
    122         self.trainset, self.testset = self.get_dataset(self.data)

RuntimeError: Dataset 'xView.yaml' error ❌ [Errno 2] No such file or directory: '/content/datasets/xView/xView_train.geojson'
```

It seems like something in the configuration of how to download the dataset is wrong.

### Environment

(I get the same error message on a colab instance with a V100 GPU, I doubt this is a hardware specific bug)
Ultralytics YOLOv8.0.217 🚀 Python-3.11.4 torch-2.1.1 CPU (Apple M1 Pro)
Setup complete ✅ (8 CPUs, 32.0 GB RAM, 397.0/460.4 GB disk)

OS                  macOS-13.3.1-arm64-arm-64bit
Environment         Darwin
Python              3.11.4
Install             pip
RAM                 32.00 GB
CPU                 Apple M1 Pro
CUDA                None

matplotlib          ✅ 3.8.2>=3.3.0
numpy               ✅ 1.26.2>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 2.1.1>=1.8.0
torchvision         ✅ 0.16.1>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.1.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

```py
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)

# Train the model
results = model.train(data='xView.yaml', epochs=100, imgsz=640)
```

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@holma91 xView is manual download. See here:

https://github.com/ultralytics/ultralytics/blob/a5390de2f1091847b1036de9b11e82ca79772651/ultralytics/cfg/datasets/xView.yaml#L136-L142
