### ISSUE TITLE
For YOLO v8 human tracking, how to lower down confidence threshold for the human pose estimation

### ISSUE THREAD

**Issue by YUXIAOQUN** [ultralytics/ultralytics#6622]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I used yolo v8 to track human and extracted human skeleton data. I found that when the confidence score is lower than 0.5, the estimated joint position data would be (0, 0). How to lower down the confidence threshold for human tracking in YOLO v8？ Simple code is shown below and extraced csv file is attached. 
[test_pose.csv](https://github.com/ultralytics/ultralytics/files/13484005/test_pose.csv)

 
model = YOLO('../yolov8s-pose.pt')
results = model.track(frame, persist=True)
poses = results[0].keypoints.cpu().numpy()

**Comment by glenn-jocher** [comment]
@YUXIAOQUN hello! It sounds like you want to adjust the confidence threshold for pose estimation in human tracking with YOLOv8. To lower the confidence threshold, you may modify the `--conf-thres` flag when using the model for tracking. This flag sets the minimum confidence for the detections to be considered.

For instance, if you want to set the confidence threshold to 0.3, you would include `--conf-thres 0.3` in your tracking command. Adjust this value according to your requirements for sensitivity and specificity.

For detailed information on how to incorporate this into your tracking setup with YOLOv8's CLI or within a Python script, please visit our documentation on the Track mode. The Pose/Keypoint Estimation section might also offer more insights into customizing the keypoints thresholding.

If you've further queries or need additional guidance, feel free to reach out through the repo's Issues or Discussions. Happy tracking! 😊

**Comment by YUXIAOQUN** [comment]
@glenn-jocher Hi! Thank you very much for your prompt reply. Following your guidance, I checked the Track model as well as Pose section, I only found the "conf" parameter in "track" function which is designed for adjusting tracking algorithm. I want to lower down the confidence threshold for key point estimation. I am still struggling on incorporating --conf-thres flag in my python code instead of the CLI.  Could you kindly provide additional guidance? Thank you very much!

**Comment by glenn-jocher** [comment]
Hello again @YUXIAOQUN! My apologies for any confusion. To adjust the confidence threshold for keypoint estimation specifically within your Python code, you would typically access the confidence threshold setting directly in the model's pipeline configuration. This is not adjusted with a `--conf-thres` flag, as that's more common when invoking the CLI.

Instead, look for a parameter that corresponds to keypoint confidence within the model's configuration or options. It's usually a value that can be set when you load the model or pass to the model before performing inference.

The exact parameter name and how to adjust it can be found in the Pose/Keypoint Estimation documentation. Ensure to peruse the relevant sections, which explain how to set various thresholds and parameters relevant to keypoints.

Should you still have uncertainties or encounter any issues, don't hesitate to continue the conversation on our Issues or Discussions page and the community or our team will assist you. Your journey towards seamless human pose estimation is important to us! 🌟

**Comment by YUXIAOQUN** [comment]
@glenn-jocher Thank you for your kind reply. After searching around, I found one related bug report from this link [issue 2837](https://github.com/ultralytics/ultralytics/issues/2837). It seems I have to modify the save_txt funciton in **yolo/engine/results.py ** to change **k_conf < 0.5** to **k_conf < the lowered confidence** so that the keypoint position data would not be zero when the pose estimation quality is not high. However, I cann't find this file. Could you provide more clear guidance? Thank you in advance!

**Comment by glenn-jocher** [comment]
Hi @YUXIAOQUN! I'm glad to see you're actively researching possible solutions. It looks like you've come across a discussion that suggests modifying an internal function within the Ultralytics codebase to adjust the keypoint confidence threshold.

If you can't find the `results.py` file, it might be due to updates in the repository structure since that issue was posted. Instead of looking for the `save_txt` function, you should look for the appropriate method or class that handles the keypoints within your currently checked-out version of the YOLOv8 codebase. 

While I can't point you directly to the code—since we're avoiding code examples here—I recommend you search for the keypoints or pose estimation logic within the repository. Once you locate it, look for a line where the confidence threshold is applied to keypoints. It could look something like an if-statement with a hardcoded confidence value.

After identifying the confidence check, modify it to the threshold value you desire. Remember to review the latest YOLOv8 documentation for any additional insights and consider reaching out on the Issues page should you need further assistance.

Your contributions and questions help improve YOLOv8 for everyone involved, and we appreciate your engagement with the community. Keep it up! 🚀

**Comment by rafaelgildin** [comment]
@glenn-jocher Thanks for the answers, but the problem still remains the same.
@YUXIAOQUN did you solve it? If not, I think it's easier to use the object detection, which has the confidence on it's parameters and apply a tracker engine.

**Comment by glenn-jocher** [comment]
@rafaelgildin, if modifying the threshold for keypoint confidence directly within the codebase is proving challenging, it may indeed be simpler to approach this by separating the object detection and pose estimation steps. 

After running object detection with your desired confidence threshold, you could then apply a tracking engine to the detected humans and perform pose estimation separately on the tracked objects. 

Explore the Detection and Track mode documentation for guidance on adjusting confidence thresholds and applying tracking. Remember, any further concerns or code-related issues can be discussed on the repo's Issues page for dedicated support. Keep innovating! 🌟

**Comment by YUXIAOQUN** [comment]
@rafaelgildin Hi, I still couldn't solve this issue fully. However, I found a simple walkaround for my task. I just added a small value (0.0001) to the zeros to avoid 0/0 error for my code.
