### ISSUE TITLE
Warmup support for benchmark

### ISSUE THREAD

**Issue by cristilummetry** [ultralytics/ultralytics#6626]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Parameter in the benchmark method for warmup iterations.

### Use case

When benchmarking a PyTorch torchscript model several warmups are needed in order to have a more accurate timing.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@cristilummetry hello and thank you for your interest in contributing to the YOLOv8 project! Your suggestion regarding warmup iterations for the benchmarking process is quite valuable as it would indeed provide more accurate timing results by mitigating initial cold-start latency in the model's performance evaluation.

Introducing a parameter to specify the number of warmup iterations before the actual benchmarking begins would improve the robustness of the benchmarks. This enhancement aligns well with our aim to provide precise and realistic model performance metrics.

If you'd like to proceed with a PR, we encourage you to review the contributing guidelines in the repository's documentation. Your implementation would likely involve adding an optional argument to the benchmark method to allow users to specify the desired number of warmup iterations. Don't forget to also update the corresponding documentation with this new feature and any necessary explanation.

We appreciate your willingness to improve YOLOv8 and are looking forward to your pull request. If you have further questions, feel free to ask. Good luck! 🚀😊

**Comment by cristilummetry** [comment]
> @cristilummetry hello and thank you for your interest in contributing to the YOLOv8 project! Your suggestion regarding warmup iterations for the benchmarking process is quite valuable as it would indeed provide more accurate timing results by mitigating initial cold-start latency in the model's performance evaluation.
> 
> Introducing a parameter to specify the number of warmup iterations before the actual benchmarking begins would improve the robustness of the benchmarks. This enhancement aligns well with our aim to provide precise and realistic model performance metrics.
> 
> If you'd like to proceed with a PR, we encourage you to review the contributing guidelines in the repository's documentation. Your implementation would likely involve adding an optional argument to the benchmark method to allow users to specify the desired number of warmup iterations. Don't forget to also update the corresponding documentation with this new feature and any necessary explanation.
> 
> We appreciate your willingness to improve YOLOv8 and are looking forward to your pull request. If you have further questions, feel free to ask. Good luck! 🚀😊

@glenn-jocher hello
I already made a PR but I accidentally made a different issue when requesting it.
It is at https://github.com/ultralytics/ultralytics/pull/6627

Thank you for the feedback!

**Comment by glenn-jocher** [comment]
Hello @cristilummetry, great job on taking the initiative to submit a PR for the warmup support in the benchmarking method. It's not a problem that you accidentally created a different issue for it. These things happen, and we can certainly work with that.

I'll take a look at your PR at https://github.com/ultralytics/ultralytics/pull/6627, review the changes, and provide feedback if necessary. Thank you for enhancing the YOLOv8 benchmarking functionality and for your contribution to the project. If more discussions are needed regarding the PR, we'll carry on in the pull request comments section.

Keep up the fantastic work! 👍😊
