### ISSUE TITLE
Mlflow model logging

### ISSUE THREAD

**Issue by xecarlox94** [ultralytics/ultralytics#6638]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello guys,

I have tried your framework and I found it really great. I am now trying to connect to a mlflow remote server.

The auto-logging of parameters, metrics and artefacts is working perfectly but not the Yolo model itself. The model object is logged as another artefact. I need to log it as a model as the pytorch library by running this function that you can find at [here](https://mlflow.org/docs/latest/python_api/mlflow.pytorch.html#mlflow.pytorch.log_model).

I believe the "mlflow.log_model" function needs:
- the pytorch model (the "best.pt", I believe)
- the model's signature with includes the inputs and targets (shape and data types)
- the python virtual environment (conda or pip)

I have read the your documentation on regarding the [mlflow integration](https://docs.ultralytics.com/reference/utils/callbacks/mlflow/) and even your code [here](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/callbacks/mlflow.py)

After studying the code, I believe we could log the model by calling "mlflow.log_model" in the "train_end" function callback, that can be found in this [link](https://github.com/ultralytics/ultralytics/blob/a5390de2f1091847b1036de9b11e82ca79772651/ultralytics/utils/callbacks/mlflow.py#L91)

Please let me know if this is possible, and I am even willing to contribute if this is a change the maintainers are happy to have.

Is this something we could work on?

**Comment by glenn-jocher** [comment]
@xecarlox94 hello,

Great to hear you're finding the framework useful! 😊 MLflow integration is indeed a powerful feature for experiment tracking and model management.

As for logging the model as an MLflow PyTorch model, this indeed involves the `mlflow.pytorch.log_model` function, which would require the `.pt` file (often `best.pt` in the context of training completion), and potentially a model signature of inputs and outputs.

Regarding the `train_end` callback within our current MLflow integration, that's a plausible location to integrate such a logging feature considering it's invoked at the end of training when `best.pt` would typically be saved.

While we're always open to community contributions, we'd recommend discussing any proposed changes in a new issue or discussion on the repository. This allows the wider community to offer insights, and ensures that any contributions align with the roadmap and standards of the project.

Feel free to outline your proposal on GitHub. Contributions are always welcome, and we can work together to review and refine your suggestions. Your willingness to assist is very much appreciated by our team and the YOLO community!

Don't forget to pull the latest changes to your fork before working on any contributions, and follow our contribution guidelines to ensure a smooth integration process.

Wishing you the best with your machine learning endeavors!

Warm

**Comment by xecarlox94** [comment]
Hello @glenn-jocher 

Thank you very much for your detailed feedback! I appreciate it. I also agree that MlFlow is a really nice model management framework.

Regarding your technical review, I believe this matches what I had in mind so I feel ready to take this to the next steps (recommending a change) and I will take your suggestion as the extra technical insight on how I could formally recommend this change. 

Before I propose this, should I create a "Feature request" type of issue? Also, I can I mention you in this new post so that you could be keeping track of the progress of this, or it is not necessary, in your opinion? It is one of the first contributions for a big project so it could be useful for me.


Best Regards

**Comment by alexlopezcifuentes** [comment]
Just in case anyone drops into this issue with the same problem, I have been testing and, as far as I know, there is no real Ultralytics solution for this.

However, after testing some approaches, I think I found a solution for this.

The basic problem here is that the native YOLO variable that comes from the `.train()` method contains a DataLoader, which basically is not serializable, thus not being compatible with the PyTorch MLFlow flavor. 
The solution involves saving the model as a `.pt` file and then reloading it again in order to remove all this training stuff that might not be necessary for inference. Here's the **drawback**: we are removing some training artifacts, so beware that there might be some problems later if you intend to do more than inference with the model, I have not really tested that.

So the code should look something similar to:

```python
def clean_YOLO_model(model: YOLO) -> YOLO:
    """
    Save model to temporary location and reload it. This removes training artifacts and data loaders.
    """
    with tempfile.NamedTemporaryFile(suffix='.pt', delete=False) as tmp:
        model.save(tmp.name)
        # Create a fresh YOLO instance from the saved weights
        clean_model = YOLO(tmp.name)
        return clean_model

# We set this so that MLFlow run does not end when .train() method finishes
os.environ["MLFLOW_KEEP_RUN_ACTIVE"] = "true"
# Instantiate model
model = YOLO("yolo11n-seg")
# Train the model
model.train(data=data_path)
# Log model
mlflow.pytorch.log_model(pytorch_model=clean_YOLO_model(model))
```
With this, you should be able to log the model and then be able to load it from an MLFlow run or Model Registry without issue.

**Comment by glenn-jocher** [comment]
@alexlopezcifuentes thank you for sharing this practical workaround! Your approach of cleaning the YOLO model by saving and reloading to remove non-serializable training artifacts is clever and should indeed resolve the MLflow PyTorch model logging issue.

The temporary file approach you've outlined effectively strips away the DataLoader and other training-specific components that prevent direct serialization, which is exactly what's needed for MLflow compatibility. Your note about potential limitations for post-inference operations is also valuable context for users.

This is a great interim solution while we consider implementing native support for this in the MLflow callback system. Thanks for contributing to help the community! 🙏
