### ISSUE TITLE
yolov8n-obb.yaml not found 

### ISSUE THREAD

**Issue by rkinas** [ultralytics/ultralytics#6640]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Hi,
is implementation of OBB available for training? I followed instruction on your page (https://docs.ultralytics.com/datasets/obb/dota-v2/#sample-data-and-annotations) and unfortunately I am not able to run OBB training.

```
from ultralytics import YOLO

# Create a new YOLOv8n-OBB model from scratch
model = YOLO('yolov8n-obb.yaml')

# Train the model on the DOTAv2 dataset
results = model.train(data='DOTAv2.yaml', epochs=100, imgsz=640)
```

I got an error:
FileNotFoundError: 'yolov8n-obb.yaml' does not exist

It seems to me that yolov8-obb model architecture and checkpoint is not available in git repository.

### Environment

Ultralytics YOLOv8.0.219  Python-3.9.13 torch-2.1.1+cu121 CUDA:0 (NVIDIA RTX A5000, 24248MiB)
Setup complete ✅ (24 CPUs, 125.6 GB RAM, 669.8/937.3 GB disk)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by rkinas** [comment]
As I can see yolo-obb is developed in separate branch: https://github.com/ultralytics/ultralytics/tree/obb (not in main branch). Is it right?

**Comment by rkinas** [comment]
@glenn-jocher thank you very much for answer. I ran training on obb branch and it works on DOTA sample dataset without problem. The only thing that remains is during training the script does not download the model yolov8n-obb.pt (file not found). Only training from scratch is possible. Where can the pretrained model be downloaded from?

**Comment by glenn-jocher** [comment]
@rkinas, I'm glad to hear that the training on the OBB branch is working well for you with the DOTA sample dataset! Regarding the pretrained `yolov8n-obb.pt` model, it's possible that a pre-trained checkpoint for this specific variant may not yet be available to the public.

Pretrained models are typically provided to facilitate transfer learning, which can help improve performance and reduce training time. If such a checkpoint is not present in the repository or is not being downloaded automatically, it may indicate that the model is still under development or validation.

For the time being, training from scratch, as you have done, is the correct approach. Once the Ultralytics team finalizes and releases any official pre-trained OBB models, they will likely be announced in the repository's release notes or the official documentation.

Keep an eye on the YOLOv8 updates through the official Ultralytics [Documentation](https://docs.ultralytics.com), and if a pre-trained OBB model is released, it will be documented there along with instructions on how to use it.

Thank you for your understanding and for being part of the YOLO community. 😊🚀
