### ISSUE TITLE
wrong coordinates for pose inference 

### ISSUE THREAD

**Issue by stefp** [ultralytics/ultralytics#6641]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I noticed that after I run the inference on a pose model (3 keypoints: left, center, right) despite the output image seems ok (see below) 
![img](https://github.com/ultralytics/ultralytics/assets/5663984/fb2b9ee4-3e8c-4071-8dc4-3a70772d4dea)

but the output keypoint coordinates for py for the center point (should be column 11) are all very close to each other (see below output) as they are all very close to 0.99.  Do you know why this is happening? 

0 0.511719 0.47013 0.351562 0.103896 0.365281 0.462741 0.992865 0.53169 0.48335 0.999601 0.67001 0.434278 0.996767 0.880745
0 0.498698 0.792208 0.445312 0.12987 0.293382 0.761047 0.988575 0.505809 0.781855 0.999604 0.69707 0.76664 0.997248 0.813232
0 0.502604 0.161039 0.09375 0.0415584 0.465629 0.15709 0.999451 0.51068 0.16495 0.999975 0.542479 0.165906 0.999758 0.78905
0 0.50651 0.228571 0.127604 0.0467532 0.451342 0.22082 0.998609 0.513952 0.231842 0.999974 0.558061 0.235471 0.999723 0.746449
0 0.511719 0.897403 0.523438 0.122078 0.267877 0.862014 0.996493 0.506695 0.902091 0.999865 0.734995 0.908471 0.996401 0.738819
0 0.505208 0.276623 0.208333 0.0545455 0.416454 0.267079 0.999512 0.523214 0.279332 0.99967 0.597787 0.28562 0.998073 0.731764
0 0.536458 0.7 0.354167 0.0961039 0.369708 0.675103 0.998411 0.501395 0.708742 0.999672 0.696648 0.678114 0.99577 0.717109
0 0.511719 0.320779 0.263021 0.0493506 0.390299 0.325808 0.999803 0.52087 0.317877 0.999885 0.626624 0.308389 0.998553 0.698538
0 0.497396 0.77013 0.4375 0.0961039 0.296763 0.753093 0.988835 0.502709 0.767655 0.998666 0.701114 0.751951 0.991952 0.662809
0 0.507812 0.401299 0.21875 0.0649351 0.415053 0.398357 0.999371 0.51514 0.405177 0.99995 0.599366 0.388923 0.998956 0.65429
0 0.481771 0.57013 0.364583 0.0961039 0.311333 0.551922 0.995635 0.511028 0.558041 0.999719 0.645832 0.563999 0.998633 0.613258
0 0.497396 0.367532 0.229167 0.0545455 0.401701 0.374781 0.997963 0.515844 0.366209 0.999898 0.593055 0.358879 0.999303 0.514918
0 0.528646 0.962338 0.453125 0.0753247 0.302245 0.952639 0.906409 0.518646 0.983787 0.932723 0.711803 0.965842 0.680283 0.513824
0 0.516927 0.127273 0.0494792 0.025974 0.498032 0.123178 0.998961 0.512685 0.128756 0.999945 0.532704 0.127268 0.999489 0.455763
0 0.518229 0.681818 0.375 0.127273 0.353313 0.659482 0.994749 0.504021 0.685233 0.999763 0.673116 0.656369 0.997345 0.381513
0 0.50651 0.628571 0.377604 0.109091 0.331625 0.626256 0.992779 0.494064 0.643437 0.999553 0.664515 0.601238 0.998045 0.30573
0 0.516927 0.950649 0.507812 0.0935065 0.283147 0.925219 0.881377 0.517772 0.951911 0.967494 0.716229 0.953191 0.889595 0.298742
0 0.544271 0.881818 0.458333 0.111688 0.328862 0.855293 0.970518 0.494397 0.881631 0.996195 0.746214 0.897512 0.992195 0.200615
0 0.494792 0.654545 0.21875 0.0675325 0.389451 0.65294 0.986463 0.487543 0.660225 0.999549 0.581522 0.639082 0.996294 0.131824
0 0.510417 0.0974026 0.03125 0.0181818 0.498963 0.0933035 0.996917 0.509706 0.101509 0.999708 0.521964 0.0944841 0.998108 0.129296
0 0.513021 0.653247 0.369792 0.0909091 0.35423 0.635999 0.997555 0.493114 0.65717 0.999719 0.636893 0.620243 0.996247 0.115769
0 0.483073 0.967532 0.361979 0.0649351 0.319551 0.953305 0.97443 0 0 0.384505 0 0 0.0949896 0.104144

Thanks

**Comment by stefp** [comment]
ok sorry I solved it,  was actually looking for the wrong column

**Comment by glenn-jocher** [comment]
@stefp glad to hear you've resolved the issue! If you have any more questions or run into any other troubles, feel free to ask. We're here to help. Happy detecting with YOLOv8! 😊🚀
