### ISSUE TITLE
Issue when using the new API to load an old yolov5 model trained using the old API

### ISSUE THREAD

**Issue by vivekbharadhwajsa** [ultralytics/ultralytics#665]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When using the ultralyics package to load the yolov5 model (trained using the old yolov5 repo API : https://github.com/ultralytics/yolov5) 

Loading command : `model = YOLO(model_path, type="v5")`

I get the issue :
<img width="800" alt="image" src="https://user-images.githubusercontent.com/51442925/215085480-d8d544d4-feaf-492d-9351-4adda1838974.png">

Any solution?

**Comment by Laughing-q** [comment]
@vivekbharadhwajsa yeah we haven't supported loading yolov5 models which trained from yolov5 repo yet. But we'll release yolov5 pretrained weights which trained by this repo soon! :)

**Comment by mbenami** [comment]
Hi @Laughing-q 
Any chance of supporting old Yolov5 model training with the YOLOV5 repo? 
so for inference, we can use the new repo to load the old models and not retrain them with the new repo or have the inference code support both repos
Thanks

**Comment by Laughing-q** [comment]
@mbenami hi, we've launched pretrained yolov5u models which were trained by this repo. You can see the benchmark here. [https://github.com/ultralytics/ultralytics/tree/main/ultralytics/models](https://github.com/ultralytics/ultralytics/tree/main/ultralytics/models)
Also you can easily use these model by:
```python
from ultralytics import YOLO

model = YOLO("yolov5nu.pt")
```

**Comment by mbenami** [comment]
Hi @Laughing-q 
yes I already saw that 
but we already have several models trained with YOLOv5 that we are using 
+ some news with YOLOv8 
for the simplicity of the inference code, I would like to have only the YOLOv8 inference code that supports YOLOv5 models (and not train again all the YOLOv5 models with the YOLOv8 repo)
is that possible?

Thanks
