### ISSUE TITLE
Using yolo pose result to make a dataset to train the model again

### ISSUE THREAD

**Issue by navidTerraNova** [ultralytics/ultralytics#6657]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I convert YOLOv8-pose output key points to Coco keypoint dataset labels (with visibility flag, 0, 1, 2)?

**Comment by s0966066980** [comment]
> @RizwanMunawar I found the method to do so, I just have to use "save_txt()". It will return a text file for the generated image with the labels, but it is without the visibility flag, I guess I have to write a script to detect whether a key-point is in the bounding box or not.

Did you succeed? I will encounter this problem, have you encountered it?
#13170
