### ISSUE TITLE
Problem with prediction code arguments , default.yaml wan not updated by given values from windows CIL

### ISSUE THREAD

**Issue by devendraswamy** [ultralytics/ultralytics#667]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

CIL arguments are not updated when i run the "./ultralytics\ultralytics\yolo\v8\detect\predict.py" code , I am trying to do the predictions through my windows command prompt but default arguments are not updated.

cmd :- python "./ultralytics\ultralytics\yolo\v8\detect\predict.py" task=detetct mode=predict model=./ultralytics\runs\ASB_V12_CheckMap_yolov8\weights\best.onnx imgsz=640 conf=0.25 source="D:/Pictures/asbottom_tubes.jpg"

getting none in arguments values :- None "cfg.model" (print of config model)
               None "cfg.source" (print of config source )

Please help me out , how to update the yaml file with given arguments from CIL, Thank you in advance.

**Comment by AyushExel** [comment]
This command seems to work for me. It loads the m model:
```
yolo detect predict model=yolov8m.pt
```
Maybe check your installation and install the latest version
