### ISSUE TITLE
yolov8 custom dataset with quantization aware training capability.

### ISSUE THREAD

**Issue by harufumigithub** [ultralytics/ultralytics#6676]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

We need to the same accuracy and performance gain in tflite of integer_quant.

### Use case

Use on edge device with accuracy.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@harufumigithub thank you for reaching out with your feature request! I appreciate your interest in enhancing YOLOv8's capability with quantization-aware training (QAT).

As of my last update, native support for QAT in YOLOv8 has not been included. While this feature may be valuable for deployment to edge devices where model size and inference speed are crucial, there are complexities associated with maintaining accuracy during quantization.

For now, if you need to quantize a YOLOv8 model for an edge device, you could train the model normally, and then post-process it with TensorFlow's or PyTorch's quantization tools before converting it to TFLite format. This does not guarantee the same level of accuracy as QAT might, but it is a currently viable path.

When deploying on an edge device, it's also essential to consider the balance between accuracy and performance gains from quantization. Sometimes, further fine-tuning or calibration may be needed after quantization to reach the desired accuracy levels.

If you or anyone else from the community is interested in helping by submitting a PR for QAT in YOLOv8, that would be fantastic! Contributions are always welcome, and they help drive the project forward.

Keep an eye on the official documentation at https://docs.ultralytics.com for any updates on new features and capabilities, including potential future support for QAT. 🚀

Your interest and support for YOLOv8 help make it better for everyone. Thanks again for your input!

**Comment by IamShubhamGupto** [comment]
@glenn-jocher is this repository https://github.com/jahongir7174/YOLOv8-qat good for qat for yolov8? I am trying to use the repository but it supports only COCO2017 txt format compared to the yolov8 config format.

I am interested in helping with a pr but let me know if this is a good starting point. thanks

**Comment by glenn-jocher** [comment]
@IamShubhamGupto currently, YOLOv8 does not natively support quantization-aware training (QAT) directly within its training pipeline. However, you can still perform post-training quantization to deploy YOLOv8 models on edge devices with integer precision.

Here's a general approach to achieve this:

1. **Train Your Model**: Train a YOLOv8 model on your custom dataset as you normally would. Ensure that you achieve the desired accuracy without quantization first.

2. **Export to ONNX**: Export your trained YOLOv8 model to ONNX format, which is an intermediate representation that can be converted to various deployment formats, including TensorFlow Lite (TFLite).

    ```python
    from ultralytics import YOLO

    # Load your trained YOLOv8 model
    model = YOLO('path/to/your/custom_trained_model.pt')

    # Export the model to ONNX format
    model.export(format='onnx')
    ```

3. **Convert ONNX to TensorFlow**: Use the [ONNX-TensorFlow](https://github.com/onnx/onnx-tensorflow) converter to convert the ONNX model to a TensorFlow SavedModel.

4. **Quantize with TensorFlow Lite**: Apply post-training quantization using TensorFlow Lite's converter. This step can convert the model to use integer-only operations, which is suitable for edge devices.

    ```python
    import tensorflow as tf

    # Convert the TensorFlow SavedModel to a quantized TFLite model
    converter = tf.lite.TFLiteConverter.from_saved_model('path/to/your/saved_model')
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8  # or tf.uint8
    converter.inference_output_type = tf.int8  # or tf.uint8
    converter.representative_dataset = representative_data_gen  # Provide a data generator function

    tflite_quant_model = converter.convert()

    # Save the quantized model
    with open('path/to/your/quantized_model.tflite', 'wb') as f:
        f.write(tflite_quant_model)
    ```

5. **Test the Quantized Model**: It's crucial to test the quantized model on a representative dataset to ensure that the accuracy is acceptable for your use case.

6. **Deploy on Edge Device**: Once you have a quantized TFLite model, you can deploy it on your edge device and run inference.

Please note that quantization can affect the model's accuracy, so it's important to validate the performance of the quantized model thoroughly.

If you require quantization-aware training (QAT) specifically, you might need to implement a custom training loop using TensorFlow or PyTorch with QAT support, and then convert the model to TFLite. This is a more complex process and would require significant modifications to the training pipeline.

As for submitting a PR, since you indicated that you're not willing to submit one, you might want to keep an eye on the Ultralytics YOLOv8 repository for any updates regarding QAT support or consider reaching out to the maintainers to express your interest in this feature.

**Comment by kuber-petlibro** [comment]
@glenn-jocher , Hi, thanks for sharing the procedure for Post Training Quantization. I wanted to know what is this "representative_data_gen" function, you talked about? How do we generate/ define one such function?

**Comment by glenn-jocher** [comment]
The `representative_data_gen` function provides a small sample of your dataset to calibrate the model's activations during quantization. It should yield batches of input data in the same format as your model's input.

**Comment by glenn-jocher** [comment]
Here's a simple example of a `representative_data_gen` function for YOLOv8 quantization:

```python
def representative_data_gen():
    dataset = load_dataset("path/to/calibration/images")  # Load a small subset of your dataset
    for image in dataset:
        # Preprocess image same way as training
        input_data = preprocess_image(image)
        # The function must yield batches of data
        yield [input_data]

def preprocess_image(image):
    # Resize to model input size (e.g., 640x640)
    img = cv2.resize(image, (640, 640))
    # Normalize to float32 [0,1]
    img = img.astype(np.float32) / 255.0
    # Add batch dimension
    img = np.expand_dims(img, axis=0)
    return img
```

This function should process around 100-1000 representative images from your dataset to calibrate the quantization parameters effectively. The images should cover the range of scenarios your model will encounter during deployment. Make sure the preprocessing matches exactly what you'll use during inference.

For more details on model export and deployment, please see the Export guide at https://docs.ultralytics.com/modes/export/.

**Comment by MECHAAMER** [comment]
very helpfull, thank you.
Note: during Convert ONNX to TensorFlow, I face an issue: 
`BackendIsNotSupposedToImplementIt: Resize version 18 is not implemented.`

I solve it by using python 3.8.1, tensorflow>=2.13.0,<=2.15.0, keras==2.13.1, keras_applications==1.0.8

Also I used this magical python [code](https://github.com/onnx/onnx-tensorflow/blob/main/example/onnx_to_tf.py)

**Comment by MECHAAMER** [comment]
I have another question:
1. In this method we convert the yolo trained model into onnx, then convert the onnx to tensorflow model, then quantize it , why not convert the trained model directly to tf model using yolo model export function?
2. Is the function yolo model.export(format="edgetpu") can do a full quantization automatically as this method do? 
3. Is activate the int8 = TRUE parameter at training can do full quantization?

**Comment by glenn-jocher** [comment]
Thank you for sharing your experience and your representative_data_gen implementation. Let me address your questions:

1. While YOLO does support direct TF export, the ONNX intermediate step is often preferred as it provides better compatibility and optimization opportunities. However, you can indeed use direct TF export if it meets your needs.

2. The model.export(format="edgetpu") does perform full integer quantization automatically, but requires a representative dataset. You would still need to provide a calibration dataset similar to your implementation.

3. Setting int8=True during training is not the same as post-training quantization. It enables int8 training but doesn't perform the full quantization needed for edge deployment.

Your representative_data_gen implementation looks good, though consider using pathlib for more robust path handling. For detailed information about model export formats and quantization options, see https://docs.ultralytics.com/modes/export/.

**Comment by MECHAAMER** [comment]
Hello, sorry for submitting again and aging.
after I do the quantization using this code:

```
def representative_data_gen():
    image_paths = "/.../images/"
    op_ = 0

    for image_path in os.listdir(image_paths):
        op_ = op_ + 1 
      image = cv2.imread("/home/at-am/datasets/VisDrone/VisDrone2019-DET-train/images/"+image_path)    
      image = cv2.resize(image, (640, 640))
      image = np.array(image).astype(np.float32) / 255.0 
      image = np.transpose(image, (2, 0, 1))  # (H, W, C) -> (C, H, W)
      image = np.expand_dims(image, axis=0)  # Add batch dimension
  
      if op_ == 950:
        break
      yield [image] 
      print(" next   ")
```

I try to inference the model on the edge coral using this code:


```
model = ultralytics.YOLO('/home/mendel/YOLO_quant_test/quantized_model_def_int8.tflite', task = 'detect') #$


file = '/home/mendel/720p/city.mp4'
# Open the video file
cap = cv2.VideoCapture(file)
i = 0

while True:
    i = i + 1
    ret, frame = cap.read()
    if not ret:
        print("no frames")
        break

results = model(frame)
```

I get this error:
`ValueError: Cannot set tensor: Dimension mismatch. Got 640 but expected 3 for dimension 1 of input 0`


I try change the dimensions of images to meet the model requirements:

`frame = np.reshape(frame, (1, 3, frame.shape[0], frame.shape[1]))`

I get this error:

`cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgproc/src/resize.cpp:3789: error: (-215:Assertion failed) !dsize.empty() in function 'resize'`

Also I try to resize the input image using:

`frame = cv2.resize(frame, (640,640))`

but no changes,

can you help me please, thanks.

**Comment by glenn-jocher** [comment]
The issue likely stems from mismatched input dimensions between the TFLite model and the provided video frames during inference. TFLite models exported for object detection typically expect input in the format `(1, height, width, channels)` with `channels = 3` for RGB images.

Ensure the input frame is properly preprocessed before passing it to the model. Update your code to preprocess the `frame` as follows:

```python
frame = cv2.resize(frame, (640, 640))  # Resize to match the model's input size
frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)  # Convert BGR to RGB
frame = np.expand_dims(frame, axis=0)  # Add the batch dimension
frame = frame.astype(np.float32) / 255.0  # Normalize to [0, 1]
```

Pass this processed `frame` to the model for inference. If the error persists, confirm the input signature and expected dimensions of your TFLite model using TensorFlow Lite's `Interpreter`:

```python
import tensorflow as tf

interpreter = tf.lite.Interpreter(model_path='/path/to/quantized_model.tflite')
interpreter.allocate_tensors()
print(interpreter.get_input_details())
```

This will show the exact input requirements. Adjust your preprocessing accordingly. If you need further assistance, refer to the documentation for inference-related specifics: https://docs.ultralytics.com/integrations/tflite/.
