### ISSUE TITLE
Key point size in google colab.

### ISSUE THREAD

**Issue by adkbbx** [ultralytics/ultralytics#6677]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I looked at the issue #3130 and understood its possible to change the size of key points but I was wondering how I can do the same using Google Colab.

**Comment by timtensor** [comment]
Hi @RizwanMunawar - Thanks first of all for such a clean implementation example. I had similar question , and thus i thought i would just put a comment out here 
1. How can customize the skeleton output. For example if i just want to draw a line from mid hip to the head and if i want to display and write angles how can i do that ? Is there a quick example you could show ? 
2. Is there a way to process videos on batch ? Lets say there are a bunch of videos in folder `input` and i want to process and store the results in an `output folder`
3. Do you have a suggestion on which model to use ? I want to test estimation on a bit complex enviroment with water / aquatic in scene 
Regards T

**Comment by RizwanMunawar** [comment]
@timtensor Thanks :) Yes, offcourse!

1- You can use the mentioned code to display the line from hip to the head and also the angle (degree), but the counts will not work, because at the moment we only support "push-ups", "pull-ups" and "ab workout" exercises monitoring.
``` python
from ultralytics import YOLO
from ultralytics.solutions import ai_gym
import cv2

model = YOLO("yolov8n-pose.pt")
cap = cv2.VideoCapture("path/to/video/file.mp4")
assert cap.isOpened(), "Error reading video file"

gym_object = ai_gym.AIGym()  # init AI GYM module
gym_object.set_args(line_thickness=2,
                    view_img=True,
                    pose_type="pullup",
                    kpts_to_check=[0, 5, 11]  # or [0, 6, 12]
                    )

frame_count = 0
while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break
    frame_count += 1
    results = model.predict(im0, verbose=False)
    im0 = gym_object.start_counting(im0, results, frame_count)

cv2.destroyAllWindows()
```

2- Yes you can process the video in a batch,  you can utilize the mentioned code below.
```python
import os

from ultralytics import YOLO
from ultralytics.solutions import ai_gym
import cv2
import os

model = YOLO("yolov8n-pose.pt")

gym_object = ai_gym.AIGym()  # init AI GYM module
gym_object.set_args(line_thickness=2,
                    view_img=True,
                    pose_type="pullup",
                    kpts_to_check=[0, 5, 11]  # or [0, 6, 12]
                    )

# Videos processing
videos_folder = "ultralytics"
output_folder = "ultralytics-out"

if not os.path.exists(output_folder):
    os.mkdir(output_folder)
for ind, vid in enumerate(os.listdir(videos_folder)):


    cap = cv2.VideoCapture(os.path.join(videos_folder, vid))
    assert cap.isOpened(), "Error reading video file"

    # Video Writer
    video_writer = cv2.VideoWriter(os.path.join(output_folder, "workouts_{}.avi".format(ind)),
                                   cv2.VideoWriter_fourcc(*'mp4v'),
                                   int(cap.get(5)),
                                   (int(cap.get(3)), int(cap.get(4))))

    frame_count = 0
    while cap.isOpened():
        success, im0 = cap.read()
        if not success:
            print("Video processing has been successfully completed.")
            break

        frame_count += 1
        results = model.predict(im0, verbose=False)
        im0 = gym_object.start_counting(im0, results, frame_count)
        video_writer.write(im0)

    video_writer.release()
    cap.release()

cv2.destroyAllWindows()

```

3- The `yolov8l` model can perform well in complex environments.


I hope this helps! Let me know if you have any additional questions.

Thanks and Regards
Ultralytics Team!

**Comment by timtensor** [comment]
Thanks a lot.  I will have a go . Do I need to call the AIGym function for visualisation? I am just wondering if there is like a visualisation function that could be modified and overlaid on the video stream .

**Comment by glenn-jocher** [comment]
@timtensor, glad to assist! For customization in visualization like drawing lines between keypoints or overlaying angles, no need to call the AI Gym function unless you're using its specific features for exercise counting.

YOLOv8 provides an `Annotator` class that can be used to handle custom visualizations. You can modify or extend this class to draw custom lines or angles between keypoints directly on your video frames.

To overlay these custom visualizations, you'd need to process each frame of the video stream, apply your custom drawing functions to the keypoints detected, and then write the modified frame back to the video or display it in real-time.

Best of luck with your implementation, and keep exploring the powerful features of YOLOv8! 🚀

**Comment by RizwanMunawar** [comment]
@timtensor, the support for custom annotation functionality is not available at the moment. However, we have plans to implement this feature in the coming days.

We would suggest you keep a close watch on https://docs.ultralytics.com/ for updates.

Thanks,
Ultralytics Team!

**Comment by timtensor** [comment]
@RizwanMunawar thanks a lot . Yes i will. I think this feature would be really useful as much of the analysis is quite a visual based computer which makes it intuitive as well.

**Comment by RizwanMunawar** [comment]
@timtensor Yes you can perform pose estimation in conjunction with object tracking. Subsequently, you can apply this to monitor workouts or analyze key points.

Thanks
Ultralytics Team!

**Comment by pmahan00** [comment]
Hi @glenn-jocher / @RizwanMunawar  i was following the thread here and i guess you mean something like this right ? 
Just drawing mid hip to mid head a line.  

```
import sys
import cv2
from google.colab.patches import cv2_imshow
from ultralytics import YOLO
from ultralytics.utils.plotting import Annotator

model = YOLO("yolov8s-pose.pt")
names = model.model.names # classes names

cap = cv2.VideoCapture("path/to/video.mp4")

if not cap.isOpened():
   print("Error reading video file")
   sys.exit()

while cap.isOpened():
   success, im0 = cap.read()

   if success:
       results = model.predict(im0)[0]
       boxes = results.boxes.xyxy.cpu()
       clss = results.boxes.cls.cpu().tolist()
       kptss = results.keypoints.data

       annotator = Annotator(im0, line_width=3, example=names)

       for kpt in reversed(kptss):
           frame = annotator.kpts(kpt, shape=(640, 640), radius=5)
           
           # Get the mid-head and mid-hip keypoints
           mid_head = kpt[1][:2]
           mid_hip = kpt[8][:2]
           
           # Draw a line between the mid-head and mid-hip points
           cv2.line(im0, tuple(mid_head), tuple(mid_hip), color=(255, 0, 0), thickness=2)

       for box, cls in zip(boxes, clss):
           label = str(names[int(cls)])
           frame = annotator.box_label(box, label=label, color=(0, 0, 255))
       
       cv2_imshow(im0) # for google colab display
   else:
       break

cap.release()
cv2.destroyAllWindows()
```
And how can you use tracker in conjuction ? For some reference i am trying to get similar to this as an inspiration : https://www.instagram.com/reel/Cqqu5RpL1RQ/?igsh=MWt1YXIwYnJhd3dpdw%3D%3D

**Comment by glenn-jocher** [comment]
@pmahan00, your code snippet is on the right track for drawing a line between keypoints. To incorporate tracking, you would integrate a tracking algorithm that updates the object's location frame by frame. YOLOv8's `Track` mode can be used for this purpose.

For a visual reference similar to the Instagram reel, you would combine pose estimation with tracking to maintain the identity of each person across frames while also analyzing their pose. This would involve running the pose estimation model on each tracked object.

Keep in mind that integrating these features requires a good understanding of both pose estimation and object tracking principles. The documentation provides guidance on using each mode separately, and you can combine them in your code logic to achieve simultaneous tracking and pose estimation.

Best of luck with your project! 🌟

**Comment by pmahan00** [comment]
Hi @glenn-jocher / @RizwanMunawar thanks i could manage to do custom visualization taking in consideration of also the confidence scores . It was well explained. I however had one question, i wanted to calculate the angle  between the three points `kpts 5, kpts 7, kpts 9 ` and display the acute angle at `kpts7` and perhaps even to draw an ellipse. Is there a function i can call explicitely ? I did try to find the angles but they seem to be giving me the wrong answer

**Comment by glenn-jocher** [comment]
@pmahan00, great to hear you've made progress with custom visualization! For calculating angles between keypoints, you would typically use geometric functions to determine the angle based on the positions of the points. There isn't a built-in function in YOLOv8 specifically for angle calculation between keypoints.

To calculate the acute angle at `kpts7` formed by `kpts5`, `kpts7`, and `kpts9`, you would use the dot product formula or the law of cosines. Ensure your keypoints are accurately detected and that you're converting the angle from radians to degrees if necessary.

For drawing an ellipse, OpenCV has functions like `cv2.ellipse()` that you can use to draw on the image based on the keypoints' coordinates.

Keep experimenting, and refer to the documentation for more details on the available functions and how to use them effectively. 🛠️
