### ISSUE TITLE
Memory leak when running val function on TensorRT model

### ISSUE THREAD

**Issue by meirdrago** [ultralytics/ultralytics#6690]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

When running validation report
```
model = YOLO(os.path.join(model_path, 'best.engine'))
model.val(data=MY_DATA_PATH)
```
on model converted to **tensorRT** the RAM memory consumption  is constantly increasing and very soon the machine is run out of memory.

The origin of the problem is 
https://github.com/ultralytics/ultralytics/blob/e5045204482ba0e947ec42aa21cc778aa5160429/ultralytics/models/yolo/detect/val.py#L126
where the tensors from the Gpu are not released.

Possible solution could be primarily release the tensors
changing this line into:
```
self.stats.append((
    [i.detach().cpu().numpy().copy() for i in correct_bboxes],
    pred[:, 4].detach().cpu().numpy().copy(),
    pred[:, 5].detach().cpu().numpy().copy(),
    cls.squeeze(-1).detach().cpu().numpy().copy()
))
```
and then changing 
https://github.com/ultralytics/ultralytics/blob/e5045204482ba0e947ec42aa21cc778aa5160429/ultralytics/models/yolo/detect/val.py#L142
to:
```
stats = [np.concatenate(x, axis=0) for x in zip(*self.stats)]
```

### Environment

Ubuntu 22.04
Driver Version: 525.147.05   CUDA Version: 12.0 **RTX A2000** and **Quadro RTX 5000**
tensorflow==2.13.1
ultralytics==8.0.211
tensorrt==8.6.1.post1
tensorrt-bindings==8.6.1
tensorrt-libs==8.6.1
python3.10

### Minimal Reproducible Example

```
import torch
from ultralytics import YOLO
import os

model_size = 'L'
model_path = ('/home/magosuser/magosML/yolov8/L/weights'
              if model_size == 'L'
              else '/home/magosuser/magosML/yolov8/M/weights')

if __name__ == '__main__':
    #model = YOLO(os.path.join(model_path, 'best.pt'))
    model = YOLO(os.path.join(model_path, 'best.engine'))
    model.val(data="/home/magosuser/magosML/test/model.yaml", imgsz=1280, plots=True)
    #model.export(format='tensorRT', half=True)

```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@meirdrago hello! Thank you for such a detailed bug report regarding the memory leak during the validation process of the YOLOv8 model in TensorRT format.

Your investigation into the memory leak issue is much appreciated and provides a solid starting point for addressing this problem. The suggested changes for managing tensor allocation and deallocation make sense in a garbage-collected environment like PyTorch.

I understand the significance of preventing memory leaks especially when working with limited resources on specific GPUs. This could potentially be a very important fix to improve the robustness of the YOLOv8 inference in production environments.

I am glad that you are willing to contribute by submitting a Pull Request. I recommend forking the repository, implementing your recommended changes, ensuring they solve the issue without introducing any new ones, and then submitting a PR. Your proposed approach will then be thoroughly reviewed by our team regarding its efficacy and impact on the broader YOLOv8 codebase.

In the meantime, our developers will also look into this matter as it seems quite critical. Thank you again for your commitment to improving YOLOv8!

Please let us know if there are any more details or insights you uncover as you work on this issue. Your collaboration with the community is what helps us all make YOLOv8 even better. 😊🛠️
