### ISSUE TITLE
Multi-GPU inference using DataParallel approach

### ISSUE THREAD

**Issue by Renat2001** [ultralytics/ultralytics#6697]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have 4 GPUs and I need to use them for model inference to process video data so 4 GPUs will process video frames in parallel:
![image](https://github.com/ultralytics/ultralytics/assets/61690545/5c3aab42-84ef-482e-be34-cdfc11517b59)
The ```BATCH_SIZE=4``` so 4 GPUs will process this batch.
The code to recreate the problem:
```
import cv2
import time
import torch
import numpy as np
from torchvision import transforms
from torch.utils.data import Dataset, IterableDataset, DataLoader
from ultralytics import YOLO

PATH = 'your path to video'
SEGMENT = 'path to model'
POSE = 'path to model'
CONF = 0.7 # confidence threshold for segment and pose models
BATCH = 4

# Initialize models

segment = YOLO(SEGMENT)
pose = YOLO(POSE)

# placing device

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

# Create DataLoader class to work with video

class VideoDataset(Dataset):
    def __init__(self, path):
        self.cap = cv2.VideoCapture(path)

    def __getitem__(self, index):
        self.cap.set(cv2.CAP_PROP_POS_FRAMES, index)
        ret, frame = self.cap.read()
        return frame

    def __len__(self):
        return int(self.cap.get(cv2.CAP_PROP_FRAME_COUNT))

# initialize video loader

video_loader = DataLoader(VideoDataset(PATH), batch_size=BATCH, shuffle=False)

# put model to DataParallel

if torch.cuda.device_count() > 1:
    print("Let's use", torch.cuda.device_count(), 'GPUs!')
    segment = torch.nn.DataParallel(segment)
segment.to(device)

# Apply DataLoader on multi gpu

start = time.time()
j = 0
for data in video_loader:
    data = data.to(device)
    data = data.permute(0, 3, 1, 2)
    data = transforms.Resize(size=(384, 640), antialias=True)(data)
    data = torch.div(data, 255)                  
    print('Frame:', j, end='\r')
    results = segment(data, classes=1, verbose=True, max_det=1, conf=CONF)
    j += 1
print('The process took', time.time()-start, 'seconds')
```
When I run this code I turned on ```verbose=True``` to see if this code really works in parallel. As output I get:
```
Frame: 0



0: 384x640 1 Гидроключ, 26.0ms
Speed: 0.0ms preprocess, 26.0ms inference, 4.3ms postprocess per image at shape (1, 3, 384, 640)
0: 384x640 1 Гидроключ, 16.6ms
Speed: 0.1ms preprocess, 16.6ms inference, 8.0ms postprocess per image at shape (1, 3, 384, 640)
0: 384x640 1 Гидроключ, 16.8ms
Speed: 0.2ms preprocess, 16.8ms inference, 7.9ms postprocess per image at shape (1, 3, 384, 640)
0: 384x640 1 Гидроключ, 16.6ms
Speed: 0.2ms preprocess, 16.6ms inference, 7.9ms postprocess per image at shape (1, 3, 384, 640)
```
Following this error:
```
TypeError: Results.__init__() missing 2 required positional arguments: 'path' and 'names'
```
What ways can you suggest to overcome such issue?

**Comment by Renat2001** [comment]
Hello @glenn-jocher! Thank you for providing time to have a look at my issue, really appreciate that! Carefully read your answer and decided to switch to ```DistributedDataParallel``` approach. Here I resolved my issue and ready to show the answer to users who also struggling with **Multi-GPU Inference.**
Also, really grateful to **Pytorch** team for this [https://www.youtube.com/watch?v=-LAtx9Q6DA8](url) tutorial on ```DDP```.
First, imported needed libraries:
```
import cv2
import torch
import os
import time
import torch.multiprocessing as mp
from torch.utils.data.distributed import DistributedSampler
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.distributed import init_process_group, destroy_process_group
from torchvision import transforms
from torch.utils.data import Dataset, IterableDataset, DataLoader
from ultralytics import YOLO
```
I don't think you need deep explanation on libraries used as it is pretty understandable.
Next, setting ```DDP``` to use local machine as ```MASTER``` (the reason to use ```localhost``` for ```MASTER_ADDR```) at any free port (in my case, ```12355```):
```
def ddp_setup(rank, world_size):
    '''
    Args:
        rank: Unique identifier of each process
        world_size: Total number of processes
    '''
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '12355'
    init_process_group(backend='nccl', rank=rank, world_size=world_size)
```
In code below I configured ```Inferencer``` class representing YOLOv8 segmentation model. It takes the ```model``` itself, ```data``` as ```DataLoader``` and ```gpu_id``` which refers to **CUDA** devices that will run in parallel:
```
class Inferencer:
    def __init__(self, model, data, gpu_id):
        self.gpu_id = gpu_id
        self.model = model.to(gpu_id)
        self.data = data
        # self.model = DDP(self.model, device_ids=[self.gpu_id]) not usable since model does not train

    def predict(self, classes, conf, verbose, max_det):
        print(f'Utilizing GPU{self.gpu_id}') 
        for inp in self.data:
            inp = inp.to(self.gpu_id)
            inp = inp.permute(0, 3, 1, 2)
            inp = transforms.Resize(size=(384, 640), antialias=True)(inp)
            inp = torch.div(inp, 255)
            result = self.model(inp, classes=classes, conf=conf, verbose=verbose, max_det=max_det)
```
Here, ```VideoDataset``` and ```VideoIterator``` refer to ```Dataset``` and ```IterableDataset``` objects respectively. Actually on single GPU without using ```DistributedSampler```, ```VideoIterator``` runs much faster (~5x faster) than ```VideoDataset```. But I figured out ```DistributedSampler``` requires ```Dataset``` object since it needs to evenly distribute the data into GPUs:
```
class VideoDataset(Dataset):
    def __init__(self, path):
        self.cap = cv2.VideoCapture(path)

    def __getitem__(self, index):
        self.cap.set(cv2.CAP_PROP_POS_FRAMES, index)
        ret, frame = self.cap.read()
        return frame

    def __len__(self):
        return int(self.cap.get(cv2.CAP_PROP_FRAME_COUNT))

class VideoIterator(IterableDataset):
    def __init__(self, path):
        self.cap = cv2.VideoCapture(path)

    def generate(self):
        while self.cap.isOpened():
            ret, frame = self.cap.read()
            if ret == False:
                break
            yield frame

    def __iter__(self):
        return iter(self.generate())
````
This function creates ```DataLoader``` applying ```DistributionSampler```:
```
def prepare_dataloader(dataset, batch_size):
    return DataLoader(dataset, 
                      batch_size=batch_size, 
                      pin_memory=True, 
                      shuffle=False, 
                      sampler=DistributedSampler(dataset))
```
The last code starts process using 4 GPUs with ```batch_size=1``` (1 batch per GPU):
```
def main(rank, world_size):
    ddp_setup(rank, world_size)
    model = YOLO('/home/r.abdrakhmanov/tumar/models/best.pt')
    dataset = VideoDataset('/home/r.abdrakhmanov/tumar/data/video.mp4')
    data = prepare_dataloader(dataset, batch_size=1)
    inferencer = Inferencer(model, data, rank)
    inferencer.predict(classes=1, conf=0.7, verbose=False, max_det=1)
    destroy_process_group()

if __name__ == '__main__':
    import sys
    start = time.time()
    world_size = torch.cuda.device_count()
    mp.spawn(main, args=(world_size,), nprocs=world_size)
    print('The process took', time.time()-start, 'seconds')
```
Results:
Single-GPU:
```
# Apply DataLoader on single GPU

start = time.time()
j = 0
for data in video_loader:
    data = data.to(device)
    data = data.permute(0, 3, 1, 2)
    data = transforms.Resize(size=(384, 640), antialias=True)(data)
    data = torch.div(data, 255)
    print('Frame:', j, end='\r')
    results = segment(data, classes=1, verbose=False, max_det=1, conf=CONF)
    j += 1
print('The process took', time.time()-start, 'seconds')
```
Output:
```
The process took 849.6888828277588 seconds
```
Multi-GPU:
```
python multi.py
```
Output:
```
Utilizing GPU1
Utilizing GPU2
Utilizing GPU0
Utilizing GPU3
The process took 247.27135705947876 seconds
```

Feel free to ask questions or propose suggestions to improve the solution!

**Comment by glenn-jocher** [comment]
@Renat2001 Fantastic progress! It's great to hear you've successfully implemented the DistributedDataParallel (DDP) setup for your multi-GPU inference requirements. I'm pleased to know the resources and advice provided were helpful in your endeavor. DDP is indeed a solid choice for leveraging multiple GPUs effectively. It excellently distributes the workload and often provides more scalable performance compared to using DataParallel.

It's also reassuring to see that you've taken the initiative to refine your code to better suit the DDP model, and you have shared a comprehensive approach that others can follow. Your contribution will surely assist many users who are facing similar challenges.

I am particularly impressed by your detailed code structure and the systematic process you've followed to resolve the issues at hand. This kind of community-driven solution sharing is invaluable and aligns perfectly with our ethos at Ultralytics. Your results also speak volumes: reducing the processing time significantly highlights the potential of DDP for intensive video processing tasks.

The shift from using VideoIterator to VideoDataset to conform with DistributedSampler represents a keen insight into data handling mechanisms for parallel processing. It signifies a refined approach to dealing with video streams in a distributed environment.

Your willingness to share insights and solutions such as this further reinforces the collaboration and collective problem-solving that we value within the YOLO and Ultralytics community. Thank you for your contributions, and best of luck with your future endeavors using YOLOv8 and DDP. If new questions or issues arise, please don't hesitate to open a discussion on our GitHub page. Your participation helps make our tools and community stronger! 🚀🤖👍

**Comment by Dharneesh-13** [comment]
> Hello @glenn-jocher! Thank you for providing time to have a look at my issue, really appreciate that! Carefully read your answer and decided to switch to `DistributedDataParallel` approach. Here I resolved my issue and ready to show the answer to users who also struggling with **Multi-GPU Inference.** Also, really grateful to **Pytorch** team for this [https://www.youtube.com/watch?v=-LAtx9Q6DA8](url) tutorial on `DDP`. First, imported needed libraries:
> 
> ```
> import cv2
> import torch
> import os
> import time
> import torch.multiprocessing as mp
> from torch.utils.data.distributed import DistributedSampler
> from torch.nn.parallel import DistributedDataParallel as DDP
> from torch.distributed import init_process_group, destroy_process_group
> from torchvision import transforms
> from torch.utils.data import Dataset, IterableDataset, DataLoader
> from ultralytics import YOLO
> ```
> 
> I don't think you need deep explanation on libraries used as it is pretty understandable. Next, setting `DDP` to use local machine as `MASTER` (the reason to use `localhost` for `MASTER_ADDR`) at any free port (in my case, `12355`):
> 
> ```
> def ddp_setup(rank, world_size):
>     '''
>     Args:
>         rank: Unique identifier of each process
>         world_size: Total number of processes
>     '''
>     os.environ['MASTER_ADDR'] = 'localhost'
>     os.environ['MASTER_PORT'] = '12355'
>     init_process_group(backend='nccl', rank=rank, world_size=world_size)
> ```
> 
> In code below I configured `Inferencer` class representing YOLOv8 segmentation model. It takes the `model` itself, `data` as `DataLoader` and `gpu_id` which refers to **CUDA** devices that will run in parallel:
> 
> ```
> class Inferencer:
>     def __init__(self, model, data, gpu_id):
>         self.gpu_id = gpu_id
>         self.model = model.to(gpu_id)
>         self.data = data
>         # self.model = DDP(self.model, device_ids=[self.gpu_id]) not usable since model does not train
> 
>     def predict(self, classes, conf, verbose, max_det):
>         print(f'Utilizing GPU{self.gpu_id}') 
>         for inp in self.data:
>             inp = inp.to(self.gpu_id)
>             inp = inp.permute(0, 3, 1, 2)
>             inp = transforms.Resize(size=(384, 640), antialias=True)(inp)
>             inp = torch.div(inp, 255)
>             result = self.model(inp, classes=classes, conf=conf, verbose=verbose, max_det=max_det)
> ```
> 
> Here, `VideoDataset` and `VideoIterator` refer to `Dataset` and `IterableDataset` objects respectively. Actually on single GPU without using `DistributedSampler`, `VideoIterator` runs much faster (~5x faster) than `VideoDataset`. But I figured out `DistributedSampler` requires `Dataset` object since it needs to evenly distribute the data into GPUs:
> 
> ```
> class VideoDataset(Dataset):
>     def __init__(self, path):
>         self.cap = cv2.VideoCapture(path)
> 
>     def __getitem__(self, index):
>         self.cap.set(cv2.CAP_PROP_POS_FRAMES, index)
>         ret, frame = self.cap.read()
>         return frame
> 
>     def __len__(self):
>         return int(self.cap.get(cv2.CAP_PROP_FRAME_COUNT))
> 
> class VideoIterator(IterableDataset):
>     def __init__(self, path):
>         self.cap = cv2.VideoCapture(path)
> 
>     def generate(self):
>         while self.cap.isOpened():
>             ret, frame = self.cap.read()
>             if ret == False:
>                 break
>             yield frame
> 
>     def __iter__(self):
>         return iter(self.generate())
> ```
> 
> This function creates `DataLoader` applying `DistributionSampler`:
> 
> ```
> def prepare_dataloader(dataset, batch_size):
>     return DataLoader(dataset, 
>                       batch_size=batch_size, 
>                       pin_memory=True, 
>                       shuffle=False, 
>                       sampler=DistributedSampler(dataset))
> ```
> 
> The last code starts process using 4 GPUs with `batch_size=1` (1 batch per GPU):
> 
> ```
> def main(rank, world_size):
>     ddp_setup(rank, world_size)
>     model = YOLO('/home/r.abdrakhmanov/tumar/models/best.pt')
>     dataset = VideoDataset('/home/r.abdrakhmanov/tumar/data/video.mp4')
>     data = prepare_dataloader(dataset, batch_size=1)
>     inferencer = Inferencer(model, data, rank)
>     inferencer.predict(classes=1, conf=0.7, verbose=False, max_det=1)
>     destroy_process_group()
> 
> if __name__ == '__main__':
>     import sys
>     start = time.time()
>     world_size = torch.cuda.device_count()
>     mp.spawn(main, args=(world_size,), nprocs=world_size)
>     print('The process took', time.time()-start, 'seconds')
> ```
> 
> Results: Single-GPU:
> 
> ```
> # Apply DataLoader on single GPU
> 
> start = time.time()
> j = 0
> for data in video_loader:
>     data = data.to(device)
>     data = data.permute(0, 3, 1, 2)
>     data = transforms.Resize(size=(384, 640), antialias=True)(data)
>     data = torch.div(data, 255)
>     print('Frame:', j, end='\r')
>     results = segment(data, classes=1, verbose=False, max_det=1, conf=CONF)
>     j += 1
> print('The process took', time.time()-start, 'seconds')
> ```
> 
> Output:
> 
> ```
> The process took 849.6888828277588 seconds
> ```
> 
> Multi-GPU:
> 
> ```
> python multi.py
> ```
> 
> Output:
> 
> ```
> Utilizing GPU1
> Utilizing GPU2
> Utilizing GPU0
> Utilizing GPU3
> The process took 247.27135705947876 seconds
> ```
> 
> Feel free to ask questions or propose suggestions to improve the solution!

Hello @Renat2001 , I have also implemented DDP in my  inference. In my case I use fast api which calls the inference function, but i got a feedback that model is loading for api request. I would love to hear ways such that model is loaded once and used for further requests.

**Comment by glenn-jocher** [comment]
Hello! To ensure the model is loaded once and reused for subsequent API requests, you can initialize the model as a global variable when the FastAPI app starts. This way, the model remains in memory and is accessible for all incoming requests. If you need further assistance, feel free to ask!
