### ISSUE TITLE
Set batch size in predict

### ISSUE THREAD

**Issue by dmascali** [ultralytics/ultralytics#670]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I couldn't find any hints on how to change the batch size during prediction. It seems that the batch size is set to 1. How can I increase it?

**Comment by nub2927** [comment]
id also like to know this, 
also is there a way to control batch size in training?

**Comment by AyushExel** [comment]
Batch size in prediction is fixed to 1 in most case.
for training you set batch size by passing `batch=value`

**Comment by IzhanVarsky** [comment]
Hi, is it true that passing a list of images for predicting won't change the batch size and it will remain the same (=1) anyway? Is it somehow possible to improve performance during prediction by increasing the size of the batch?

**Comment by Laughing-q** [comment]
@IzhanVarsky it'll concat the images first if you pass a list of images.
```python
# the batch_size will automatically set to 2 if there're two images.
model.predict(source["path/img1", "path/img2"])
```

**Comment by mehran66** [comment]
@Laughing-q Which way would be faster for a very large dataset? having the `source` directing to a folder and run prediction one by one OR we create a list of lists like [[img1, img2,img3], [img4,img5,img6]...], assuming batch size is 3 here, and run the model.predict for each sublist sequentially (we can parallelize this as well)?

**Comment by mehran66** [comment]
Ran a few experiments and found out that 1) it is the slowest if passing one list including all images to the model.predict 2) there is not much difference between setting `source` into the image folder or passing images one by one or in small batches into the model.predict.

**Comment by IzhanVarsky** [comment]
> Ran a few experiments and found out that 1) it is the slowest if passing one list including all images to the model.predict 2) there is not much difference between setting `source` into the image folder or passing images one by one or in small batches into the model.predict.

That's what I did too, I couldn't see almost any differences between processing a batch by one image in loop or processing a batch by providing it as a list to the .predict() method. That's why I concluded that batch_size is fixed and it's not possible to encourage speed by somehow changing it. Am I right or maybe there's a way to speed up processing a folder with images?

**Comment by Laughing-q** [comment]
@mehran66 @IzhanVarsky 
> there is not much difference between setting source into the image folder or passing images one by one or in small batches into the model.predict.

actually it could be, as we're allowed to use rect inference when bs=1 which is faster but for now rect is not supported for a batch inference unless the img shapes in one batch are the same.
Then the speed of bs=1 benefits from rect interface and bs>1 benefits from batches inference, so the overall speed could be almost the same...
