### ISSUE TITLE
Cannot export RT-DETR to TensorRT engine

### ISSUE THREAD

**Issue by SmithLiu95** [ultralytics/ultralytics#6700]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

Hi, I failed to export my model to the tensorRT. The code can be found below.
full log:
```
[2K
[2K
Ultralytics YOLOv8.0.220 🚀 Python-3.10.6 torch-2.0.0 CUDA:0 (NVIDIA A100-SXM4-80GB MIG 0g.10gb, 9728MiB)
Setup complete ✅ (128 CPUs, 1007.0 GB RAM, 1327.1/3519.8 GB disk)
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics YOLOv8.0.220 🚀 Python-3.10.6 torch-2.0.0 CUDA:0 (NVIDIA A100-SXM4-80GB MIG 0g.10gb, 9728MiB)
rt-detr-l summary: 494 layers, 32148140 parameters, 0 gradients

[34m[1mPyTorch:[0m starting from 'rtdetr-l.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 84) (63.4 MB)

[34m[1mONNX:[0m starting export with onnx 1.13.1rc2 opset 17...
================ Diagnostic Run torch.onnx.export version 2.0.0 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

[34m[1mONNX:[0m simplifying with onnxsim 0.4.35...
2023-11-30 13:05:17.438620970 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 74486, index: 1, mask: {2, 66, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
...(too many similar lines, skipped)
2023-11-30 13:05:19.457094608 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 77685, index: 47, mask: {48, 112, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2023-11-30 13:05:19.457104502 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 77655, index: 17, mask: {18, 82, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
[34m[1mONNX:[0m simplifier failure: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Type Error: Type 'tensor(float16)' of input parameter (/model.28/Constant_18_output_0) of operator (Range) in node (/model.28/Range) is invalid.
[34m[1mONNX:[0m export success ✅ 10.7s, saved as 'rtdetr-l.onnx' (61.6 MB)

[34m[1mTensorRT:[0m starting export with TensorRT 8.6.1...
[11/30/2023-13:05:19] [TRT] [I] [MemUsageChange] Init CUDA: CPU +2, GPU +0, now: CPU 1191, GPU 740 (MiB)
[11/30/2023-13:05:25] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1657, GPU +310, now: CPU 2925, GPU 1050 (MiB)
[11/30/2023-13:05:25] [TRT] [I] ----------------------------------------------------------------
[11/30/2023-13:05:25] [TRT] [I] Input filename:   rtdetr-l.onnx
[11/30/2023-13:05:25] [TRT] [I] ONNX IR version:  0.0.8
[11/30/2023-13:05:25] [TRT] [I] Opset version:    17
[11/30/2023-13:05:25] [TRT] [I] Producer name:    pytorch
[11/30/2023-13:05:25] [TRT] [I] Producer version: 2.0.0
[11/30/2023-13:05:25] [TRT] [I] Domain:           
[11/30/2023-13:05:25] [TRT] [I] Model version:    0
[11/30/2023-13:05:25] [TRT] [I] Doc string:       
[11/30/2023-13:05:25] [TRT] [I] ----------------------------------------------------------------
[11/30/2023-13:05:25] [TRT] [W] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[11/30/2023-13:05:25] [TRT] [W] onnx2trt_utils.cpp:400: One or more weights outside the range of INT32 was clamped
[11/30/2023-13:05:25] [TRT] [E] ModelImporter.cpp:771: While parsing node number 483 [Range -> "/model.28/Range_output_0"]:
[11/30/2023-13:05:25] [TRT] [E] ModelImporter.cpp:772: --- Begin node ---
[11/30/2023-13:05:25] [TRT] [E] ModelImporter.cpp:773: input: "/model.28/Constant_18_output_0"
input: "/model.28/Cast_output_0"
input: "/model.28/Constant_19_output_0"
output: "/model.28/Range_output_0"
name: "/model.28/Range"
op_type: "Range"

[11/30/2023-13:05:25] [TRT] [E] ModelImporter.cpp:774: --- End node ---
[11/30/2023-13:05:25] [TRT] [E] ModelImporter.cpp:777: ERROR: builtin_op_importers.cpp:3578 In function importRange:
[8] Assertion failed: (inputs.at(0).isInt32() || inputs.at(0).isFp32()) && "This version of TensorRT only supports int32 and float input types for Range!"
[34m[1mTensorRT:[0m export failure ❌ 16.8s: failed to load ONNX file: rtdetr-l.onnx
Traceback (most recent call last):
  File "ultralytics/debug.py", line 29, in <module>
    model.export(format='TensorRT', half=True)
  File "ultralytics/ultralytics/engine/model.py", line 310, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "ultralytics/ultralytics/engine/exporter.py", line 252, in __call__
    f[1], _ = self.export_engine()
  File "ultralytics/ultralytics/engine/exporter.py", line 122, in outer_func
    raise e
  File "ultralytics/ultralytics/engine/exporter.py", line 117, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "ultralytics/ultralytics/engine/exporter.py", line 604, in export_engine
    raise RuntimeError(f'failed to load ONNX file: {f_onnx}')
RuntimeError: failed to load ONNX file: rtdetr-l.onnx
```

### Environment

Ultralytics YOLOv8.0.220 🚀 Python-3.10.6 torch-2.0.0 CUDA:0 (NVIDIA A100-SXM4-80GB MIG 0g.10gb, 9728MiB)
Setup complete ✅ (128 CPUs, 1007.0 GB RAM, 1324.2/3519.8 GB disk)

onnx==1.13.1rc2
onnxruntime-gpu==1.16.3
onnxsim==0.4.35
tensorrt==8.6.1

### Minimal Reproducible Example

```
model = RTDETR("rtdetr-l.pt")
model.export(format='TensorRT', half=True)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello again @SmithLiu95! It's great to hear that you were successful with exporting the YOLOv8 large model to a TensorRT engine. Regarding the RT-DETR model, this does indeed sound like a specific issue related to how the RT-DETR operators and data types are handled in the ONNX simplification process and subsequent TensorRT conversion.

Here are a few steps we recommend to align your environment more closely with successful export outcomes for RT-DETR models:

1. **Configuration**: Confirm that the specific versions of PyTorch, ONNX, ONNX-simplifier, and TensorRT that you're using are compatible and have been tested successfully with RT-DETR. Compatibility can often be a moving target with evolving software updates, but aligning with known-good configurations is key.

2. **Half Precision**: When using half precision, ensure that the environment, including the hardware and libraries, fully supports FP16 operations. It’s worth mentioning that not all parts of a model may be compatible with FP16 conversion, and sometimes a mixed-precision approach might be more feasible.

3. **TensorRT Version**: Different versions of TensorRT may have different operator support. If possible, try with multiple versions of TensorRT that are known to have robust support for the operators used in RT-DETR.

4. **DataType Casting**: Some manual intervention may be necessary to cast INT64 weights to INT32 before starting the export pipeline. Consider reviewing the ONNX model to identify and resolve any type incompatibilities which could be causing the export process to fail.

If there's any further detail that emerges from your attempts or debugging information, that would be valuable for identifying a more specific cause or solution. It’s quite a complex process, and the precise combinations of hardware, software and model architecture can be critical.

Unfortunately, without explicit permission and consent from Ultralytics, we're not at liberty to directly provide our internal setup specifications. However, the documentation is regularly updated with recommended practices, and these recommended configurations are intended to be a good starting reference.

We appreciate your efforts with troubleshooting this issue and your willingness to support the YOLOv8 community. If you find a solution, sharing your insights or submitting a pull request would be incredibly beneficial to other users who may encounter similar issues. Your contributions make a difference! 😊🚀

**Comment by SmithLiu95** [comment]
> @SmithLiu95 follow the guidance in the error message. This error is unrelated to ultralytics:
> 
> > SymbolicValueError: Unsupported: ONNX export of operator get_pool_ceil_padding, input size not accessible. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues

@glenn-jocher I did not encounter this error. May I know the version of tensorRT, onnx and onnxsim that you successfully export the TensorRT engine of RT-DETR with FP16? Thanks.

**Comment by glenn-jocher** [comment]
@SmithLiu95 The successful export of RT-DETR models to TensorRT with FP16 precision typically requires specific versions of ONNX, onnx-simplifier, and TensorRT that are compatible with the model and each other. Please ensure that you have installed the versions recommended in our documentation. A mismatch in versions can often lead to the issues you're encountering. For RT-DETR, it's not uncommon for the environment requirements to be fairly strict due to the complexity of the operations involved. If there's a specific setup known to work, it will be detailed in our documentation. Check the Export section for additional tips and potential version requirements. If the issue persists after verifying your setup, further investigation will be needed to resolve the compatibility problem. Thank you for your efforts in working with YOLOv8! 😊🛠️

**Comment by SmithLiu95** [comment]
> onnx==1.15
> onnxruntime-gpu==1.16.3
> onnxsim==0.4.35
> tensorrt==8.6.1

hi @glenn-jocher , the versions are listed above. This meets the version requirements. However, I still cannot successfully export the model.

**Comment by glenn-jocher** [comment]
@SmithLiu95 It appears that you've got the recommended versions of the libraries. However, as the export for RT-DETR to TensorRT is still failing, it's likely due to an issue that is not version-related. It might be an unsupported operation or data type issue specific to RT-DETR when attempting the conversion. This could require a more detailed look into how the operations in the RT-DETR model are being handled during export. Make sure to refer to the documentation for any model-specific export guidance, and keep an eye on updates to our repository, as any fixes or workarounds to such issues will be documented there. Your patience and contributions are valued as we work through these complex export scenarios. 😊🛠️

**Comment by shreejalt** [comment]
@glenn-jocher @SmithLiu95 , were you able to solve this?

**Comment by glenn-jocher** [comment]
@shreejalt Currently, there's no known solution to this specific RT-DETR export issue. We're continually working to improve compatibility and address such challenges. Please stay tuned for updates, and thank you for your patience. 😊🛠️

**Comment by SmithLiu95** [comment]
> @glenn-jocher @SmithLiu95 , were you able to solve this?

I am still not able to solve this. However, using ONNX + TensoRTExecutionProvider is a work-around. I tried it and it worked well.

**Comment by glenn-jocher** [comment]
@SmithLiu95 as of now, the direct export to a TensorRT engine for RT-DETR has unresolved issues. The suggested workaround using ONNX with the TensorRTExecutionProvider is the alternative approach that has been successfully implemented. Keep an eye on the repository for any updates or solutions in the future. Thank you for your understanding and contribution! 😊🛠️

**Comment by Zephyr69** [comment]
Is exporting to tensorRT supported now?

**Comment by glenn-jocher** [comment]
@Zephyr69 it appears that you are encountering an issue when trying to export the RT-DETR model to a TensorRT engine. The error message indicates that there is an issue with the ONNX model, specifically with a `Range` node that has an input of type `tensor(float16)` which is not supported by TensorRT.

Here are a few steps you can take to troubleshoot and potentially resolve the issue:

1. **Check ONNX Model Compatibility:**
   Ensure that the ONNX model is compatible with TensorRT. TensorRT has certain limitations on the operators it supports. You can use the `trtexec` command-line tool provided by TensorRT to check if the ONNX model can be parsed successfully.

2. **Use Compatible Opset Version:**
   The ONNX model is using opset version 17. You might want to try exporting the model with a lower opset version that is known to be compatible with TensorRT. You can specify the opset version during export with the `opset` argument.

3. **Avoid Half-Precision in Unsupported Layers:**
   The error message suggests that the `Range` operator does not support `float16` inputs. You may need to ensure that this operator receives `float32` inputs instead. This might involve modifying the model or the export script to cast the inputs of the `Range` operator to `float32` before exporting to ONNX.

4. **Update TensorRT:**
   If you are not using the latest version of TensorRT, consider updating to the latest version as it may have added support for more operators and data types.

5. **Modify the Model:**
   If certain operations are not supported in TensorRT, you may need to modify the model architecture or replace unsupported operations with alternatives that are supported by TensorRT.

6. **Use ONNX Graph Surgeon:**
   The ONNX Graph Surgeon tool allows you to modify the ONNX graph directly. You can use it to remove or replace unsupported nodes or subgraphs.

7. **Contact NVIDIA Support:**
   If you are unable to resolve the issue, consider reaching out to NVIDIA support or the TensorRT GitHub repository for assistance.

8. **Submit a Bug Report:**
   If you believe this is a bug with TensorRT's handling of the ONNX model, you can submit a bug report to the TensorRT GitHub repository with all the details and the minimal reproducible example.

Remember that when submitting a PR to help with this issue, it's important to provide a clear description of the problem, the steps taken to resolve it, and any changes made to the codebase. If the issue is related to compatibility with TensorRT, the PR might involve changes to the export functionality to ensure compatibility or to provide clearer error messages to the user.

**Comment by youarefree123** [comment]
> Is exporting to tensorRT supported now?

Maybe you should update the version of TensorRT, such as 8.6.1, and set half=False.

**Comment by youarefree123** [comment]
> Is exporting to tensorRT supported now?

I tried to export the weights of f16 in RT-DETR, and it seems to have succeeded. The steps are as follows：

First, export the simplified onnx weights：

```python
model = RTDETR(r'rtdetr-l.pt')
model.export(format='onnx',opset=17,simplify=True,half=True)
```

Then, run the following code, noting that the version of TensorRT is 8.6.1：

```python

import json
# import os
import tensorrt as trt  
from pathlib import Path

f_onnx = './rt-detr.onnx'    
file = Path(f_onnx)
f = file.with_suffix('.engine')   

TRT_LOGGER = trt.Logger(trt.Logger.WARNING)  
builder = trt.Builder(TRT_LOGGER)
network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
parser = trt.OnnxParser(network, TRT_LOGGER)

success = parser.parse_from_file(f_onnx)
for idx in range(parser.num_errors):
    print(parser.get_error(idx))

if not success:
    pass # Error handling code here

config = builder.create_builder_config()

config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 30) # 1 MiB
config.set_tactic_sources(1 << int(trt.TacticSource.CUBLAS))

config.set_flag(trt.BuilderFlag.FP16) # set f16

serialized_engine = builder.build_serialized_network(network, config)


metadata = {'description': 'Ultralytics rtdetr-l...sunny.yaml', 'author': 'Ultralytics', 'license': 'AGPL-3.0 https://ult...om/license', 'date': '2024-03-09T19:14:58.861682', 'version': '8.0.230', 'stride': 32, 'task': 'detect', 'batch': 1, 'imgsz': [640, 640], 'names': {0: 'bus', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'person', 5: 'rider', 6: 'truck'}}



t = open(f, 'wb')
meta = json.dumps(metadata)
t.write(len(meta).to_bytes(4, byteorder='little', signed=True))
t.write(meta.encode())
# Model
t.write(serialized_engine)

t.close()
```

The metadata needs to be modified to meet your requirements

**Comment by youarefree123** [comment]
> > Is exporting to tensorRT supported now?
> 
> I tried to export the weights of f16 in RT-DETR, and it seems to have succeeded. The steps are as follows：
> 
> First, export the simplified onnx weights：
> 
> ```python
> model = RTDETR(r'rtdetr-l.pt')
> model.export(format='onnx',opset=17,simplify=True,half=True)
> ```
> 
> Then, run the following code, noting that the version of TensorRT is 8.6.1：
> 
> ```python
> import json
> # import os
> import tensorrt as trt  
> from pathlib import Path
> 
> f_onnx = './rt-detr.onnx'    
> file = Path(f_onnx)
> f = file.with_suffix('.engine')   
> 
> TRT_LOGGER = trt.Logger(trt.Logger.WARNING)  
> builder = trt.Builder(TRT_LOGGER)
> network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
> parser = trt.OnnxParser(network, TRT_LOGGER)
> 
> success = parser.parse_from_file(f_onnx)
> for idx in range(parser.num_errors):
>     print(parser.get_error(idx))
> 
> if not success:
>     pass # Error handling code here
> 
> config = builder.create_builder_config()
> 
> config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 30) # 1 MiB
> config.set_tactic_sources(1 << int(trt.TacticSource.CUBLAS))
> 
> config.set_flag(trt.BuilderFlag.FP16) # set f16
> 
> serialized_engine = builder.build_serialized_network(network, config)
> 
> 
> metadata = {'description': 'Ultralytics rtdetr-l...sunny.yaml', 'author': 'Ultralytics', 'license': 'AGPL-3.0 https://ult...om/license', 'date': '2024-03-09T19:14:58.861682', 'version': '8.0.230', 'stride': 32, 'task': 'detect', 'batch': 1, 'imgsz': [640, 640], 'names': {0: 'bus', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'person', 5: 'rider', 6: 'truck'}}
> 
> 
> 
> t = open(f, 'wb')
> meta = json.dumps(metadata)
> t.write(len(meta).to_bytes(4, byteorder='little', signed=True))
> t.write(meta.encode())
> # Model
> t.write(serialized_engine)
> 
> t.close()
> ```
> 
> The metadata needs to be modified to meet your requirements

By the way, the engine exported in this way can actually be used for inference using the predict API. You only need to modify the postprocess function of RTDETRPredictor：

```python
def postprocess(self, preds, img, orig_imgs):
        """
        Postprocess the raw predictions from the model to generate bounding boxes and confidence scores.

        The method filters detections based on confidence and class if specified in `self.args`.

        Args:
            preds (torch.Tensor): Raw predictions from the model.
            img (torch.Tensor): Processed input images.
            orig_imgs (list or torch.Tensor): Original, unprocessed images.

        Returns:
            (list[Results]): A list of Results objects containing the post-processed bounding boxes, confidence scores,
                and class labels.
        """
        nd = preds[0].shape[-1]
        bboxes, scores = preds[0].split((4, nd - 4), dim=-1)
        
        # FIX shape bug , engine need [1,300,4]
        if len(bboxes.shape) == 2:
            bboxes = torch.unsqueeze(bboxes, dim=0)
        
        if len(scores.shape) == 2:
            scores = torch.unsqueeze(scores, dim=0)
        

        if not isinstance(orig_imgs, list):  # input images are a torch.Tensor, not a list
            orig_imgs = ops.convert_torch2numpy_batch(orig_imgs)

        results = []
        for i, bbox in enumerate(bboxes):  # (300, 4)
            bbox = ops.xywh2xyxy(bbox)
            score, cls = scores[i].max(-1, keepdim=True)  # (300, 1)
            idx = score.squeeze(-1) > self.args.conf  # (300, )
            if self.args.classes is not None:
                idx = (cls == torch.tensor(self.args.classes, device=cls.device)).any(1) & idx
            pred = torch.cat([bbox, score, cls], dim=-1)[idx]  # filter
            orig_img = orig_imgs[i]
            oh, ow = orig_img.shape[:2]
            pred[..., [0, 2]] *= ow
            pred[..., [1, 3]] *= oh
            img_path = self.batch[0][i]
            results.append(Results(orig_img, path=img_path, names=self.model.names, boxes=pred))
        return results
```

 Now, you can perform model inference through model.predict()， just like:
 ```python
 model = RTDETR(r'last.engine')
 metrics = onnxmodel.predict(source=path, project='runs/test',save=True,visualize=False,profile=True)  

 ```

**Comment by glenn-jocher** [comment]
Thanks for sharing your solution, @youarefree123! 🌟 It's great to see you've successfully exported the RT-DETR model to TensorRT using FP16 precision. Your detailed steps and code snippets are incredibly helpful. 

For anyone looking to follow this approach, remember to adjust the metadata to fit your specific model requirements. Also, the custom postprocess function for the `RTDETRPredictor` is a neat trick to ensure compatibility with the exported engine. 

This workaround demonstrates the flexibility and power of YOLOv8 and TensorRT for optimizing deep learning models for inference. If anyone has further questions or needs clarification, feel free to ask! Happy coding! 😊
