### ISSUE TITLE
No image rotation in classify task (parameter degrees is ignored in training, data augmentation)

### ISSUE THREAD

**Issue by HoLue** [ultralytics/ultralytics#6703]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Augmentation

### Bug

When training a classification YOLOv8 model the parameter degrees is ignored.
I proved it in a colab notebook:
[YOLOv8_cls_bug03.zip](https://github.com/ultralytics/ultralytics/files/13513832/YOLOv8_cls_bug03.zip)

Same problems seem to be at least with parameters scale and translate. (Perhaps even more.)

### Environment

Colab

### Minimal Reproducible Example

(It's the code from th ipynb in the zip above.)
`
%pip install ultralytics
import ultralytics
ultralytics.checks()

# Load YOLOv8n-cls, train it on mnist160
from ultralytics import YOLO

model_def = YOLO('yolov8n-cls.pt')  # load a pretrained YOLOv8n classification model
model_def.train(data='mnist160', imgsz=224, epochs=3, degrees=20)  # train the model

# Train images, no rotation, parameter degrees is ignored
from IPython.display import Image
print('No rotation')
Image('/content/runs/classify/train/train_batch0.jpg', width=800, height=800)
`

### Additional

I think especially in the classification task data augmentation rotation, scale and translate are essential for training!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@HoLue thank you for bringing this to our attention, and I'm sorry to hear you're experiencing issues with image rotation during training in the classify task.

The parameter `degrees` is indeed intended to apply rotation augmentation during training, and if it's not functioning as expected, this is something we need to investigate further. In regards to the other parameters such as `scale` and `translate`, these are important for robust training as they provide additional data variability.

Your detailed report and the inclusion of your Colab notebook will be very useful for us. We take issues like this seriously as they can affect the performance of models trained using our software.

I would encourage you to monitor the issue tracker as we will look into this problem and provide updates on the progress of resolving it. Your testing and report are valuable contributions, so thank you for your effort.

If you have any further observations or if you encounter other issues, please feel free to share them with us. It's through insights from users like you that we can continue to improve our YOLO models. 

Thanks for your dedication to making YOLOv8 better! 🚀
