### ISSUE TITLE
MLFlow: Not all metrics are reported

### ISSUE THREAD

**Issue by ggiret-thinkdeep** [ultralytics/ultralytics#6706]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I currently use the MLFLow callbacks to report the metrics of my runs (I do object detection).

However, I noticed that only the metrics concerning the evaluation were reported 
* metrics/mAP50-95B
* metrics/mAP50B
* metrics/precisionB
* metrics/recaIlB
* val/box_loss
* val/cls_loss
* val/dfl_loss

![image](https://github.com/ultralytics/ultralytics/assets/146845847/50d9ba58-f889-4d4b-862d-ff3c51c733a0)

So I have no trace of train losses or the evolution of learning rates. However, this information is present in the 'results.csv' file.

It is therefore impossible to visualize an overfitting in terms of losses for example, which is really annoying.

I searched the source code for the error. I found what causes this error. Locally, I solved the problem by making a modification in the trainer.py. However, my modification would break other loggers. Not having access to other loggers, I cannot issue a complete patch.

But I know exactly what caused the bug. Note that according to the code I read, the bug occurs on several other loggers as well!

I think we should rethink how the metrics are managed in the trainer, and modify the reporting of information in the loggers accordingly.

This is not technically very difficult. The most complex thing is being able to test on several loggers at the same time.

The results after my modifiaction: 

![image](https://github.com/ultralytics/ultralytics/assets/146845847/d4182ada-38a1-46bb-9676-58223448fe24)

I put the resolution in the Additional part

### Additional

To patch the bug locally for MLFlow only, I made these modifications:

```py
if RANK in (-1, 0):

                # Validation
                self.ema.update_attr(self.model, include=['yaml', 'nc', 'args', 'names', 'stride', 'class_weights'])
                final_epoch = (epoch + 1 == self.epochs) or self.stopper.possible_stop

                if self.args.val or final_epoch:
                    self.metrics, self.fitness = self.validate()
                self.save_metrics(metrics={**self.label_loss_items(self.tloss), **self.metrics, **self.lr})
                self.stop = self.stopper(epoch + 1, self.fitness)
```

I just modify as well:

```py
if RANK in (-1, 0):

                # Validation
                self.ema.update_attr(self.model, include=['yaml', 'nc', 'args', 'names', 'stride', 'class_weights'])
                final_epoch = (epoch + 1 == self.epochs) or self.stopper.possible_stop

                if self.args.val or final_epoch:
                    self.metrics, self.fitness = self.validate()
                self.metrics = {**self.label_loss_items(self.tloss), **self.metrics, **self.lr}
                self.save_metrics(metrics=self.metrics)
                self.stop = self.stopper(epoch + 1, self.fitness)
```

Why ?

In the MLFlow callback, only the information from the "metrics" variable is sent back to MLFlow.

Of course, we could modify the MLFlow callback directly so as not to impact the trainer. But there is a similar problem in many other callbacks.

It would therefore be more judicious to centralize the information to be reported in the loggers in a single variable in traine.py, then to use it in all my callbacks.

Also, I added the same line of code in the final_eval() function:

```py
def final_eval(self):
        """Performs final evaluation and validation for object detection YOLO model."""
        for f in self.last, self.best:
            if f.exists():
                strip_optimizer(f)  # strip optimizers
                if f is self.best:
                    LOGGER.info(f'\nValidating {f}...')
                    self.validator.args.plots = self.args.plots
                    self.metrics = self.validator(model=f)
                    self.metrics.pop('fitness', None)
                    self.metrics = {**self.label_loss_items(self.tloss), **self.metrics, **self.lr}
                    self.run_callbacks('on_fit_epoch_end')
```

Note that here, no train losses will be reported. I don't know the relevance of reporting the information to the logger here too (for the case of MLFlow at least)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ggiret-thinkdeep should be resolved now in #6732

**Comment by Youho99** [comment]
Hello
This is my main account (ggiret-thinkdeep)

I reopen the issue, because the fix does not work. It is indeed missing the activation of on_train_epoch_end

I'll come up with a PR to fix this. I tested it and it's working

**Comment by glenn-jocher** [comment]
Hello @Youho99,

Thank you for the update and for your continued efforts to improve YOLOv8. If you've identified the missing activation of `on_train_epoch_end` and have a working solution, we welcome your PR. Your contributions are greatly valued, and we're looking forward to reviewing your fix. 🛠️
