### ISSUE TITLE
Yolov8 Inference via OpenCV::dnn - ONNX with C++

### ISSUE THREAD

**Issue by JustasBart** [ultralytics/ultralytics#671]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi guys,

Have any of you figured out how to use yolov8 exported .onnx models with OpenCVs dnn backend in C++ yet?
Or is the race still on?

Thanks :rocket:

**Comment by JustasBart** [comment]
@wvalcke Thanks a mil for you reply!

Is there any chance you could either provide me with a sample of some sort or guide me to what you think is a good place to start? I'd love to try it!

This is what it currently looks like on OpenCV 4.7.0 (As running the same code for yolov5 models):
![image](https://user-images.githubusercontent.com/40023722/215132500-771c476d-bf67-4a0b-aad7-0b21e625ee4d.png)

**Comment by JustasBart** [comment]
@wvalcke Actually, I found this which seems pretty good so I'll take it from [here](https://github.com/itsnine/yolov5-onnxruntime).

**Comment by wvalcke** [comment]
https://github.com/wvalcke/onnxruntimetests.git

Here is a repo with some samples, some use the yolov5 model in onnx format, the InferenceYolov8.cpp gives you an example how to load the yolo V8 model in onnx format, preprocess the image, do the inference, postprocess (like NMS) and finally show the image + save it with the annotations. The other examples use yolov5. Keep in mind that yolo v8 uses a different output compared to yolov5. 
Rougly said : the output is (1, 5, 8200) for an image 640x640 and using 1 class. The first is the batch size (must be 1), the 2nd dimension is CX (Center X), CY (Center Y), W (Width), H (Height), Score cls id 1 (So 5 values in total). The CX, XY, W, H are in pixels in the 640x640 resolution. Class score is a value 0-1. The last dimension (8200 values) are the possible detections. 
For Yolov5 this is different the output is (1, 25200, 6)  (if we have 1 class). Mind that the last 2 dimensions are swapped compared to yolov8.

**Comment by JustasBart** [comment]
Cheers @wvalcke! I'll play around with all of this!

**Comment by BrianP8701** [comment]
The last dimension (8200 values) are the possible detections.

So how do I choose the one with the best confidence?

**Comment by JustasBart** [comment]
@BrianP8701 Unfortunately I thought that I had it figured out already, but no, my current C++ example works with only the first class (index 0) which is wrong. I still need to learn the difference of what had actually changed between yolov5 and yolov8...

**Comment by BrianP8701** [comment]
@JustasBart Okay. When you do figure it out could you @ me? This is my first time working with an open source project so I'm really bad and slow at navigating all this stuff

**Comment by JustasBart** [comment]
@BrianP8701 I'm a C++ dev myself so I'm also a bit slow when it comes to figuring this out, but I am stubborn though! And so you bet you I'll PM you as soon as I have it figured out! :rocket:

**Comment by JustBrandonLim** [comment]
> https://github.com/wvalcke/onnxruntimetests.git
> 
> Here is a repo with some samples, some use the yolov5 model in onnx format, the InferenceYolov8.cpp gives you an example how to load the yolo V8 model in onnx format, preprocess the image, do the inference, postprocess (like NMS) and finally show the image + save it with the annotations. The other examples use yolov5. Keep in mind that yolo v8 uses a different output compared to yolov5. Rougly said : the output is (1, 5, 8200) for an image 640x640 and using 1 class. The first is the batch size (must be 1), the 2nd dimension is CX (Center X), CY (Center Y), W (Width), H (Height), Score cls id 1 (So 5 values in total). The CX, XY, W, H are in pixels in the 640x640 resolution. Class score is a value 0-1. The last dimension (8200 values) are the possible detections. For Yolov5 this is different the output is (1, 25200, 6) (if we have 1 class). Mind that the last 2 dimensions are swapped compared to yolov8.

Using OpenCVSharp, all the class scores have a value of more than 0-1, is this normal?

```csharp
using Mat detections = output.Reshape(0, output.Size(2), output.Size(1));
            for (int rowIndex = 0; rowIndex < detections.Rows; rowIndex++)
            {
                using Mat row = detections.Row(rowIndex);
                row.GetArray(out float[] rowData);

                List<float> classScores = rowData.Skip(4).ToList();
                int bestClassId = classScores.IndexOf(classScores.Max());
                
                float score = classScores[bestClassId];
                
                if (score >= 0.90f && bestClassId.Equals(4))
                {
                    int centerX = (int)rowData[0];
                    int centerY = (int)rowData[1];
                    int width = (int)rowData[2];
                    int height = (int)rowData[3];

                    Debug.WriteLine(score);

                    boundingBoxes.Add(new Rect(centerX - (width / 2), centerY - (height / 2), width, height));
                    scores.Add(score);
                }
            }
```

**Comment by JustasBart** [comment]
For anyone looking at this at a later time, the sample is now a part of the Ultralytics repo and a stand-alone sample with exported models can also be found [here](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX).

Good luck! :rocket:

**Comment by BrianP8701** [comment]
Thanks!!!

**Comment by schrifta** [comment]
I tried running the Yolovv8 inference sample from Ultralytics repo,
[JustasBart](https://github.com/JustasBart)/ 
but it fails in OpenCV dnn module, in scale_shift.cpp, ScaleShiftOp::forward, lines 131-135, when weights size is compared to input size.
I'm using OpenCV 4.5.5. Can that be the reason for the failure?

[yolov8_CPP_Inference_OpenCV_ONNX](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX)

**Comment by JustasBart** [comment]
Hi, @schrifta I believe that OpenCV 4.5.5 is the one that still has the INF_ENGINE flag as well as the N_GRAPH build flags along with the rest of the flags such as WITH_ONNX etc... Can you please confirm this and rebuild with those additional flags and or try rebuilding on the latest version if that's optional for you.

You can refer to this:
![238269073-71a884ee-3ef6-4853-9531-7fd005e6d0e9](https://github.com/ultralytics/ultralytics/assets/40023722/5dcfc2a6-bf0a-4d99-a907-824fd25635b3)

**Comment by glenn-jocher** [comment]
Hi, @schrifta! Thanks for reporting the issue. The problem you are encountering when running the Ultralytics YOLOv8 inference sample from the JustasBart repo can be caused by a version conflict between the installed version of OpenCV and the version for which the sample is built. OpenCV 4.5.5 should be compatible, but it is possible that a compilation with additional flags, such as INF_ENGINE and N_GRAPH, would be necessary. Otherwise, updating to the latest version of OpenCV may help resolve the issue. Please also make sure that your model size is correct for exporting/running inference, as this could also cause problems. Hope this helps!

**Comment by schrifta** [comment]
Thank you very much Glenn.
I could not make OpenCV-4.5.5 work, but 4.7.0 works for me!

**Comment by glenn-jocher** [comment]
You're welcome, @schrifta! I'm glad to hear that updating to OpenCV 4.7.0 solved the issue for you. As I mentioned before, version conflicts between the installed version of OpenCV and the version for which the sample is built can cause issues, and updating to the latest version can sometimes help resolve the issue. Thanks for reporting the issue, and please let me know if there's anything else you need help with. Have a great day!

**Comment by schrifta** [comment]
Thank you very much JustasBurt
I could not make OpenCV-4.5.5 work, but 4.7.0 works for me!

**Comment by JustasBart** [comment]
@schrifta I'm glad to hear that you got it up and running, well done and good luck 🚀

**Comment by glenn-jocher** [comment]
Great news, @JustasBart! I'm glad to hear that updating to OpenCV 4.7.0 solved the issue of running the Ultralytics YOLOv8 inference sample for you. Remember that the correct model size for exporting/running inference is essential, especially since incorrect size can lead to issues, so be sure to keep that in mind when working with YOLOv8 models. Best of luck with your project!

**Comment by shubham-mishra-verificient** [comment]
@JustasBart @glenn-jocher I'm getting following errow while running the example
[ERROR:0@0.702] global E:\oc\opencv-4.6.0\modules\dnn\src\net_impl.cpp (1171) cv::dnn::dnn4_v20220524::Net::Impl::getLayerShapesRecursively OPENCV/DNN: [Reshape]:(onnx_node!Reshape_219): getMemoryShapes() throws exception. inputs=1 outputs=1/1 blobs=0
[ERROR:0@0.702] global E:\oc\opencv-4.6.0\modules\dnn\src\net_impl.cpp (1174) cv::dnn::dnn4_v20220524::Net::Impl::getLayerShapesRecursively     input[0] = [ 1 64 8400 ]
[ERROR:0@0.702] global E:\oc\opencv-4.6.0\modules\dnn\src\net_impl.cpp (1178) cv::dnn::dnn4_v20220524::Net::Impl::getLayerShapesRecursively     output[0] = [ ]
[ERROR:0@0.702] global E:\oc\opencv-4.6.0\modules\dnn\src\net_impl.cpp (1184) cv::dnn::dnn4_v20220524::Net::Impl::getLayerShapesRecursively Exception message: OpenCV(4.6.0) E:\oc\opencv-4.6.0\modules\dnn\src\layers\reshape_layer.cpp:108: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'cv::dnn::computeShapeByReshapeMask'

OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.6.0) Error: Assertion failed (total(srcShape, srcRange.start, srcRange.end) == maskTotal) in cv::dnn::computeShapeByReshapeMask, file E:\oc\opencv-4.6.0\modules\dnn\src\layers\reshape_layer.cpp, line 108

**Comment by glenn-jocher** [comment]
@shubham-mishra-verificient from the error message, it seems the input size to the Reshape layer in your network does not match the expected size. This is likely because the input size of your model does not match the size of the input data you are feeding into the network. Make sure these sizes match. Check your model configuration and ensure you're using the correct input size when performing inference. It is also advisable to use the same OpenCV version in which your model was trained or exported to avoid discrepancies. If the problem persists, you might need to rebuild or re-export your model.

**Comment by mohkan1** [comment]
> You're welcome, @schrifta! I'm glad to hear that updating to OpenCV 4.7.0 solved the issue for you. As I mentioned before, version conflicts between the installed version of OpenCV and the version for which the sample is built can cause issues, and updating to the latest version can sometimes help resolve the issue. Thanks for reporting the issue, and please let me know if there's anything else you need help with. Have a great day!

It also worked for me when updating opencv to 4.7.0. Thank you for this.

Here is a link on how to update: https://www.samontab.com/web/2023/02/installing-opencv-4-7-0-in-ubuntu-22-04-lts/
