### ISSUE TITLE
how to let predict labels display other languages？ 

### ISSUE THREAD

**Issue by lonngxiang** [ultralytics/ultralytics#6714]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

how to let predict labels display other languages？ 

yolo detect predict ***

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@lonngxiang hello there! 😊

To display predictions in other languages, you'll need to modify the class names in your labels file, which is typically a `.names` file containing the class labels that the model uses for inference. Here's a quick guide:

1. Locate your `.names` file, which should contain the list of class labels in English or the language used during training.
2. Replace the English labels with labels in your desired language. Ensure that you maintain the same order as the original labels, as the index of each label corresponds to the class predictions made by the model.
3. Save the changes to this `.names` file.
4. When running predictions, make sure YOLOv8 is referencing your updated `.names` file to display the prediction labels in the new language.

The labels will now appear in the language of your choice when you perform predictions. It's important to keep the structure and format of the `.names` file intact.

Remember to refer to our documentation regarding customization options to further guide you with any additional adjustments you might need. If there's anything else the community can assist you with, feel free to let us know. Good luck with your PR, and thank you for contributing to the YOLO community! 🚀

**Comment by lonngxiang** [comment]
> @lonngxiang hello there! 😊
> 
> To display predictions in other languages, you'll need to modify the class names in your labels file, which is typically a `.names` file containing the class labels that the model uses for inference. Here's a quick guide:
> 
> 1. Locate your `.names` file, which should contain the list of class labels in English or the language used during training.
> 2. Replace the English labels with labels in your desired language. Ensure that you maintain the same order as the original labels, as the index of each label corresponds to the class predictions made by the model.
> 3. Save the changes to this `.names` file.
> 4. When running predictions, make sure YOLOv8 is referencing your updated `.names` file to display the prediction labels in the new language.
> 
> The labels will now appear in the language of your choice when you perform predictions. It's important to keep the structure and format of the `.names` file intact.
> 
> Remember to refer to our documentation regarding customization options to further guide you with any additional adjustments you might need. If there's anything else the community can assist you with, feel free to let us know. Good luck with your PR, and thank you for contributing to the YOLO community! 🚀

What if i just want replace the label in another language when the model predicts without train step

**Comment by glenn-jocher** [comment]
@lonngxiang understood! You can change the labels that appear during predictions without retraining the model. You still need to modify the labels as they are displayed in the prediction output, which typically involves the following steps:

1. Open the `.names` file that contains the class labels your YOLOv8 model is currently using for predictions.
2. Directly translate the labels into your preferred language within this file, preserving the original order of the labels.
3. Save your updated `.names` file.

Once this file is saved, YOLOv8 will use these new labels for displaying predictions. Make sure that when you run the predict mode, YOLOv8 uses this updated `.names` file. This will result in the predictions being displayed with the labels in your preferred language without altering the training process.

Head to our documentation for any additional guidance you may require on output customization. If you have further questions, the community is here to help. Good luck! 🙂

**Comment by lonngxiang** [comment]
> @lonngxiang understood! You can change the labels that appear during predictions without retraining the model. You still need to modify the labels as they are displayed in the prediction output, which typically involves the following steps:
> 
> 1. Open the `.names` file that contains the class labels your YOLOv8 model is currently using for predictions.
> 2. Directly translate the labels into your preferred language within this file, preserving the original order of the labels.
> 3. Save your updated `.names` file.
> 
> Once this file is saved, YOLOv8 will use these new labels for displaying predictions. Make sure that when you run the predict mode, YOLOv8 uses this updated `.names` file. This will result in the predictions being displayed with the labels in your preferred language without altering the training process.
> 
> Head to our documentation for any additional guidance you may require on output customization. If you have further questions, the community is here to help. Good luck! 🙂

where is the location of  .names file? and how to use in code?

**Comment by glenn-jocher** [comment]
@lonngxiang my apologies for any confusion. The class names for YOLOv8 are not stored in a `.names` file like in some previous YOLO versions. Names are typically stored within the model’s `yaml` configuration file associated with the dataset used during training. 

Please follow these steps to update your class labels for prediction:

1. Find the YAML file used for your dataset. It usually resides in the `data` directory and contains dataset specifications, including class names.
2. In this YAML file, you will see a list key named `names` followed by the class labels in square brackets (e.g., `names: ['person', 'car', ...]`).
3. Translate each original label into your preferred language, making sure to preserve the order.
4. Save your changes to the YAML file.

When you run the predict mode, ensure that YOLOv8 is configured to use the YAML file with your updated labels. This will allow predictions to be displayed with the class names in the language you have set.

Refer to our documentation for detailed instructions on customizing your data configurations. If clarification is necessary or additional help is needed, don't hesitate to reach out to the Ultralytics community. Your contributions and queries greatly enhance our collaborative efforts! 🌟

**Comment by hannaliavoshka** [comment]
Also, this can be made in code by referring to the model.names dictionary:

`from ultralytics import YOLO
model = YOLO('yolov8n.pt')

# display model names dict
model.names

# change names dict by index
model.names[0] = 'new name'

# rewrite names dict by new names dict
model.names = new_names_dict`

**Comment by lonngxiang** [comment]
> Also, this can be made in code by referring to the `model.names` dictionary:
> 
> ```
> from ultralytics import YOLO
> model = YOLO('yolov8n.pt')
> 
> # display model names dict
> model.names
> 
> # change names dict by index
> model.names[0] = 'new name'
> 
> # rewrite names dict by new names dict
> model.names = new_names_dict
> ```

tks，this works

**Comment by lonngxiang** [comment]
> @lonngxiang my apologies for any confusion. The class names for YOLOv8 are not stored in a `.names` file like in some previous YOLO versions. Names are typically stored within the model’s `yaml` configuration file associated with the dataset used during training.
> 
> Please follow these steps to update your class labels for prediction:
> 
> 1. Find the YAML file used for your dataset. It usually resides in the `data` directory and contains dataset specifications, including class names.
> 2. In this YAML file, you will see a list key named `names` followed by the class labels in square brackets (e.g., `names: ['person', 'car', ...]`).
> 3. Translate each original label into your preferred language, making sure to preserve the order.
> 4. Save your changes to the YAML file.
> 
> When you run the predict mode, ensure that YOLOv8 is configured to use the YAML file with your updated labels. This will allow predictions to be displayed with the class names in the language you have set.
> 
> Refer to our documentation for detailed instructions on customizing your data configurations. If clarification is necessary or additional help is needed, don't hesitate to reach out to the Ultralytics community. Your contributions and queries greatly enhance our collaborative efforts! 🌟

sounds canot work, when predict trained model there have not a ymal file

![image](https://github.com/ultralytics/ultralytics/assets/40717349/7895a9e4-4175-4250-926e-eb8ce818f882)

**Comment by lonngxiang** [comment]
> ```python
> YOLO('yolov8n.pt', YAML='path/to/custom_dataset.yaml')
> ```

![image](https://github.com/ultralytics/ultralytics/assets/40717349/7f77185f-190c-49ee-a500-5e377867b10d)

**Comment by glenn-jocher** [comment]
@lonngxiang, my sincerest apologies for the confusion. The provided example contained an error; there is no `YAML` parameter in the `YOLO` class constructor. Instead, upon loading the model with `YOLO('yolov8n.pt')`, the class names are loaded from the model file itself.

Your provided code for manipulating the `model.names` attribute directly in Python is indeed a practical solution to update labels for prediction. To clarify for anyone else reading:

```python
from ultralytics import YOLO

# Load the model
model = YOLO('yolov8n.pt')

# Modify the `model.names` attribute with your new labels
model.names[0] = 'new name for class 0'
model.names[1] = 'new name for class 1'
# ...and so on for all classes you want to rename

# Alternatively, define a complete new_names_dict with all class indices
new_names_dict = {
    0: 'new name for class 0',
    1: 'new name for class 1',
    # ...and so on for each class
}

# Assign the new names dictionary to `model.names`
model.names = new_names_dict
```

Using this approach, you can update the labels that the model will use for predictions without modifying any YAML files. Thank you for contributing to the community with your question, and if there are further points to discuss or you need more assistance, please reach out again! 🌟
