### ISSUE TITLE
How do I cancel random cropping and scaling and moscia data enhancement when training?

### ISSUE THREAD

**Issue by ZhangBoL** [ultralytics/ultralytics#6716]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Dir ultralytics Im your fans and now,I use v8 have a question How do I cancel random cropping and caling and moscia data enhancement when training? Thankyou verymuch.

**Comment by glenn-jocher** [comment]
@ZhangBoL hello! Thank you for reaching out with your question, and I'm glad to hear about your interest in YOLOv8!

To disable random cropping, scaling, and mosaic data augmentation during training, you'll need to modify the data configuration file (typically YAML) that specifies the augmentation parameters for your training session.

In the data YAML, look for the augmentation settings, which may include keys such as `mosaic`, `mixup`, `random_perspective`, and so on. To turn off these augmentations, you can set the `mosaic` and `mixup` values to `false`, and ensure that parameters associated with scaling and random perspective (like `degrees`, `translate`, `scale`, `shear`) are set to `0` or an equivalent non-active state.

After you've made these changes, the training process should proceed without applying the specified augmentations.

For additional guidance on the exact parameters to adjust, please refer to the documentation on the dataset configuration at the Ultralytics Docs. The documentation will provide detailed explanations of each parameter and how they influence the training procedure.

If you run into any further issues or have more questions, don't hesitate to reach out again. Happy training! 🚀
