### ISSUE TITLE
Yolo export imgsz warning

### ISSUE THREAD

**Issue by JustasBart** [ultralytics/ultralytics#672]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi guys,

I'm not really sure but is this meant to happen?
![image](https://user-images.githubusercontent.com/40023722/215130725-6c93860a-b429-427d-a741-416948871e60.png)

Did it not just update my (640x640) to (640x640) and warned me about this change?
It's not really a major bug or anything the export did work, but just wondering what's going on here...

Thanks! :rocket:

**Comment by glenn-jocher** [comment]
@JustasBart thanks for the bug report! Should be resolved in #681.

**Comment by JustasBart** [comment]
@glenn-jocher Thanks!
