### ISSUE TITLE
Where are the live inference results stored in Onnx runtime model for Yolov8n and same for the OpenVino?

### ISSUE THREAD

**Issue by Stealthzer** [ultralytics/ultralytics#6720]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

1. Where are the live inference results stored in Onnx runtime model for Yolov8n and same for the OpenVino?
2. Can OpenVino be used for live webcam inference?
I am trying to obtain live inference predictions and speak them out using gTTS but cannot figure out how to access these predictions, 
Any help would be greatly appreciated.
Thanks in advance!

**Comment by glenn-jocher** [comment]
@Stealthzer hello! I'm glad to assist with your questions regarding live inference results and using YOLOv8 with ONNX Runtime and OpenVINO.

1. For ONNX Runtime, when you perform live inference using YOLOv8, the predictions are typically obtained from the output of the model's forward pass. The results are not stored on disk by default; they are held in memory. If you're running a Python script, that would be in the form of a variable that holds the output tensors, which include the bounding boxes, class probabilities, and class IDs for the detected objects.

   For OpenVINO, it serves a similar process. The model's inference results are extracted from the outputs of the `InferRequest` objects after being processed by an `ExecutableNetwork`. The inferred results remain in memory where they're accessed by your application to perform further actions, such as speaking out predictions using gTTS.

2. Yes, OpenVINO can be used for live webcam inference. You can feed the video frames from a webcam source into the OpenVINO inference engine in real-time. The pipeline typically involves capturing frames from the webcam, processing them if necessary (e.g., resizing or converting color spaces), and then passing them to the model for inference.

For speaking out predictions using gTTS, you would need to collect the inference output after each forward pass (i.e., after each frame is processed) and then convert the obtained detection data to a spoken format.

I hope this clarifies things for you! Please check the `Predict` section in the Ultralytics Docs for more insights on how to handle live predictions, and the `Export` section to understand about exporting YOLOv8 models to ONNX or OpenVINO format.

**Comment by Stealthzer** [comment]
Wow! Thanks for your quick and detailed reply.
Also, can we train models and use them for our business like inventory management or is there some sort of differant licence for that?
Thanks
