### ISSUE TITLE
Why is there no background in my class, but there is a background in Confusion Matrix Normalized? Can I ignore the background? How to set it up?

### ISSUE THREAD

**Issue by ChanryX** [ultralytics/ultralytics#6728]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why is there no background in my class, but there is a background in Confusion Matrix Normalized? Can I ignore the background? How to set it up?
![F6DE422A30CEF5FC6E11BB489CE4BC69](https://github.com/ultralytics/ultralytics/assets/49508950/3128d258-88cf-43de-9122-3f50ab018717)

**Comment by ChanryX** [comment]
@glenn-jocher Does this background appear by default? I only want the confusion matrix of these 3 categories without involving the background, because my labels only have 3 categories. what should I do?

**Comment by ChanryX** [comment]
@glenn-jocher I found the problem because I have several empty txt annotation files. After I deleted these files, there was no background. Thank you.
![微信截图_20231202141112](https://github.com/ultralytics/ultralytics/assets/49508950/edbcbcc1-8452-4cab-901d-2f5060c86c10)
![微信截图_20231202141408](https://github.com/ultralytics/ultralytics/assets/49508950/3d0b74fc-7aea-4dc1-aa6d-e057441a31ea)

**Comment by MH-DOT156** [comment]
> 我发现了这个问题，因为我有几个空的 txt 注释文件。删除这些文件后，没有背景。谢谢。 ![微信截图_20231202141112](https://private-user-images.githubusercontent.com/49508950/287425062-edbcbcc1-8452-4cab-901d-2f5060c86c10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjA5NDEsIm5iZiI6MTcxMzg2MDY0MSwicGF0aCI6Ii80OTUwODk1MC8yODc0MjUwNjItZWRiY2JjYzEtODQ1Mi00Y2FiLTkwMWQtMmY1MDYwYzg2YzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA4MjQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMTdkZTFhNTM5NDhkYTI1N2IwYWY4MGIwYmJjYzkyMDgzYjU5OGZkYmY3YTBmMDM3MGYwZDViYjYyOTVmNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X64iXo7PNtKRqYhX2-jvJcgd_p-ShNm30tN7DZ9lnps) ![微信截图_20231202141408](https://private-user-images.githubusercontent.com/49508950/287425079-3d0b74fc-7aea-4dc1-aa6d-e057441a31ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjA5NDEsIm5iZiI6MTcxMzg2MDY0MSwicGF0aCI6Ii80OTUwODk1MC8yODc0MjUwNzktM2QwYjc0ZmMtN2FlYS00ZGMxLWFhNmQtZTA1NzQ0MWEzMWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA4MjQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNGVjZGE4OGM5NmI3MmI3M2Y3ZGMyNjQ2YTE3MThjZDhlYTQzNjczOGU4NjZmNzIzNTBhMzc0YjJmOWYwZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SGug5W8HYAqtYO37ChcLh-NSD5OvS43IFCg1FPOBixY)

我也出现了和你同样的情况，但我不知道从上面地方找到这些空白文本文件，你能告诉我你是怎么弄的吗，拜托了

**Comment by glenn-jocher** [comment]
Great to hear you've identified the issue and resolved it by removing empty annotation files, @MH-DOT156! 🎉 Empty annotation files can indeed mislead the confusion matrix into showing a 'background' class, as it might interpret these as regions without objects of interest. This adjustment ensures the confusion matrix accurately reflects only the classes you're focused on.

For anyone encountering a similar situation, checking for and removing or modifying empty annotation files in your dataset can be crucial for maintaining accuracy in your model's evaluation metrics. You can look for these empty files by checking for annotation files with zero-byte sizes or by scripting a quick check, for example in Linux:

```bash
find YourAnnotationDirectory -type f -size 0 -print
```

This command finds and lists all empty files in your specified annotation directory, allowing you to review or remove them as needed.

Thanks for sharing your solution, and happy training! If you have more questions or need further assistance, feel free to reach out. 🚀
