### ISSUE TITLE
YOLOv8 int8 tflite preprocess and postprocess function Updation Request

### ISSUE THREAD

**Issue by wamiqraza** [ultralytics/ultralytics#6729]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I would like to request to update the script if you have any information as I have gone through many issue and couln't find solid resolution for most of the issues related int8 tflite scaling dat

### Use case

Hi, I would like to request to update the script if you have any information as I have gone through many issue and couln't find solid resolution for most of the issues related int8 tflite scaling data.

So a bit of description I converted model into `int8 tflite`  model via CLI `export` after that I validate on my test images using YOLO CLI for detect and it draw perfeclty the bounding box.

Now I am taking script for python from [here](https://github.com/ultralytics/ultralytics/blob/main/examples/YOLOv8-ONNXRuntime/main.py) official github repo and for float32.tflite it work after I update for tflite model.

Now I want to use the same script to load int8.tflite model to do the inference but can't get bounding box around object. I have gone through many issue and found that will need to scale which I can't found appropriate solution. I paste the snippet of  preprocess and postprocess function can a team do the changes accordgly in that so that after it got fix I can confirm here and many of the issues can be closed with this clean reference.

```
def preprocess(self):
self.img = cv2.imread(self.input_image)
        self.img_height, self.img_width = self.img.shape[:2]
        img = cv2.cvtColor(self.img, cv2.COLOR_BGR2RGB)
        img = cv2.resize(img, (self.input_width, self.input_height))
        image_data = np.array(img) / 255.0
        print("shape before", image_data.shape)
        image_data = np.expand_dims(image_data, axis=0).astype(np.float32)
        print("shape after", image_data.shape)
        return image_data
```

and
```
def postprocess(self, input_image, output):
        outputs = np.transpose(np.squeeze(output[0]))
        rows = outputs.shape[0]
        boxes = []
        scores = []
        class_ids = []
        x_factor = self.img_width / self.input_width
        y_factor = self.img_height / self.input_height
                for i in range(rows):
            classes_scores = outputs[i][4:]
            max_score = np.amax(classes_scores)
            if max_score >= self.confidence_thres:
                class_id = np.argmax(classes_scores)
                x, y, w, h = outputs[i][0], outputs[i][1] , outputs[i][2], outputs[i][3] 
                left = int((x - w / 2) * x_factor)
                top = int((y - h / 2) * y_factor)
                width = int(w * x_factor)
                height = int(h * y_factor)         
                class_ids.append(class_id)
                scores.append(max_score)
                boxes.append([left, top, width, height])
        indices = cv2.dnn.NMSBoxes(boxes, scores, self.confidence_thres, self.iou_thres)
        for i in indices:
            # Get the box, score, and class ID corresponding to the index
            box = boxes[i]
            score = scores[i]
            class_id = class_ids[i]
            self.draw_detections(input_image, box, score, class_id)
        return input_image
 ```
Please let me know if you need additional information of snippet of the code or some value to be print.
Note: That the scaling requested are generic that are being used already in the `yolo detect mode=predict ......` portion as I can't find this file to see the portion if model type is int8 do this operation. You may have better access to it so would be great if I can receive the response also link here the predict file.py so that I can see for better understanding.

Thanks looking forward to it

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wamiqraza hello!

Thank you for bringing this to our attention. It seems you require assistance with scaling data properly for an `int8` quantized `tflite` model after converting it using the export mode of YOLOv8.

You're right that the preprocessing and postprocessing functions need some adjustments for `int8` models. With `int8` quantization, input images often need to be scaled to the range the model was quantized on, typically `[0, 255]` for `uint8` or `[-128, 127]` for `int8`. Similarly, the output might also require a de-quantization step to bring the predictions into the original scale.

For preprocessing, the image pixel values should be scaled accordingly. You might need to check the quantization parameters of the model to know the exact scaling required. The post-processing function might require you to adjust for the output scale, as well as an offset if the zero point is not zero.

Without providing specific code, I would recommend you to examine the exact quantization parameters used during the export of your `int8` tflite model. Once you know these parameters, you can adapt your preprocessing function to scale images to the quantized range properly, and adjust your postprocessing function to dequantize the model outputs back to the float32 range.

The predict CLI in YOLOv8 automatically takes care of these steps, which is why you are able to get accurate results when using it. If you are able to get a hold of the code used there, that should provide a good reference for how to perform these operations.

Our documentation at Ultralytics Docs should provide a solid starting point for understanding the export formats, including TFLite. Moreover, familiarizing yourself with the TFLite quantization documentation could also offer valuable insights into adapting your scripts for int8 models. 

I am afraid I cannot directly link you to the predict file you are asking for but if you navigate through the repository's file structure, specifically in the detect mode's corresponding documentation section, you should be able to find the relevant information.

I hope this guidance helps, and I appreciate your understanding as well as your efforts in improving the YOLOv8 experience for the community! If you require further assistance, feel free to reach out. 🚀

**Comment by glenn-jocher** [comment]
Hello @wamiqraza,

It's great to hear you've made some progress with your `int8 tflite` model. The issues you are encountering with the outputs suggest there may still be a few areas that need attention:

1. Scaling of Model Outputs: It appears that your post-processing may not be accounting for the scale and zero point of the quantized outputs. Like with the inputs, these need to be dequantized back to the floating-point values your post-processing algorithm can interpret correctly.

2. Bounding Box Coordinates: The huge values for `x`, `y`, `width`, and `height` indicate a likely mismatch in the way your model scales its outputs. These values should typically correspond to positions and sizes relative to the original image dimension, so they would need to be scaled appropriately.

3. Debugging Post-processing: The `print` statements in your post-processing might be showing the raw, quantized outputs which are not yet dequantized. As you've detected no bounding boxes, this likely means that there's a significant discrepancy between the output the model is giving and how your post-process algorithm expects the data to be formatted.

It's clear that to resolve this, you will need to ascertain the correct dequantization for your model's outputs, which should be informed by the quantization parameters in the TFLite model files. Then, apply these to scale back the output values to their original floating-point range before proceeding with your bounding box extraction logic.

The documentation for YOLOv8 provides guidance on how to handle inference post-processing, and I would suggest checking the quantization section of TFLite documentation for additional details. Also, reviewing similar quantized model implementations can provide valuable insights into appropriate strategies for correct scaling and dequantization.

Keep experimenting and examining each step of your preprocess and postprocess functions to find the correct operations needed for the quantized data. Good luck! 🚀

**Comment by wamiqraza** [comment]
Hi @glenn-jocher, Yes indeed you are write and I did some changes in the code. Here is the updated code:

```

```

**Comment by glenn-jocher** [comment]
Hello @wamiqraza,

It looks like you've made significant strides. The changes you've implemented in the preprocessing and postprocessing functions seem to be working, as indicated by your terminal output showing valid detections.

To address your concerns:

1. **Debugging Negative Width and Height**: This usually indicates an issue during the coordinate scaling process. Ensure that the output values for the width and height of your detection boxes are being calculated and scaled correctly.

2. **Correctly Scaling Coordinates**: The outputs from the model are in a normalized format and need to be scaled according to the original image dimensions. Verify that the dequantization process is correctly restoring the values to their expected ranges before applying these scales.

3. **Drawing the Bounding Boxes**: Negative values for width or height will cause issues in bounding box calculations. Once the above points are fixed, this should naturally resolve. Make sure the calculated `left` and `top` coordinates, along with the width and height, are used properly to draw the rectangles.

Keep refining the process, and with a little more debugging, you should have a fully functional post-processing pipeline. Remember to double-check each step and make sure all transformations and scales align with the data types and quantization parameters of your model.

Great work so far, and keep pushing through!

**Comment by wamiqraza** [comment]
Hi @glenn-jocher,

Thank you for your feedback and sure now tying to working on that hopefully will resolve it soon then will push PR for int8  tflite deployment.

**Comment by glenn-jocher** [comment]
Hello @wamiqraza,

Looking forward to your PR, and glad to hear that you're making progress with the `int8 tflite` deployment. Keep up the good work! If you encounter any further issues or have questions, feel free to reach out.

Best of luck!

**Comment by wamiqraza** [comment]
Issues are rectified, refer to: [PR](https://github.com/ultralytics/ultralytics/pull/7317)
or implementation: [script ](https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-OpenCV-int8-tflite-Python)

**Comment by glenn-jocher** [comment]
@wamiqraza great to hear the issues have been addressed! For those following, please refer to the linked PR for the resolution details and check out the updated script for `int8 tflite` deployment with YOLOv8. Your contributions help improve the project for everyone. Thank you for your efforts! 🌟

**Comment by wamiqraza** [comment]
@glenn-jocher, yeah indeed I am following up with many tflite issues and seem its being solved for many active issues. Feel good to help community.

**Comment by glenn-jocher** [comment]
@wamiqraza, it's fantastic to see your active engagement and contributions helping to resolve tflite issues. Your efforts are greatly appreciated by the community! Keep up the excellent work. 😊👍
