### ISSUE TITLE
Metric names differ from previous YOLO versions

### ISSUE THREAD

**Issue by 35grain** [ultralytics/ultralytics#675]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When visualizing the metrics from training on a graph, for example, the metric names all differ from the standard used in YOLOv5 and v7 (haven't tried others). For comparison:
| YOLOv5, v7  | YOLOv8 |
| ------------- | ------------- |
| metrics/precision | metrics/precision(B) |
| metrics/recall | metrics/recall(B) |
| metrics/mAP_0.5 | metrics/mAP50(B) and so on |

This makes comparing the results a bit tedious. Is there a reason for outputting the results in this way or can this be changed?

**Comment by Laughing-q** [comment]
@35grain hi, we added suffix `(B)` here to distinguish the metrics of segmentation. .i.e `metrics/precision(B)` for detection and `metrics/precision(M)` for segmentation. :)

**Comment by parkitny** [comment]
Is there an easy way to re-name the metric to exclude the suffix for the detect task for example?

**Comment by Laughing-q** [comment]
@parkitny hmm I don't think there is one, it's hardcoded to help us identify the metrics from different tasks. If you want to modify it then you need to modify the source code here:
[https://github.com/ultralytics/ultralytics/blob/d1107ca4cb5ef2a94a583e0a0247172f7f972f9a/ultralytics/yolo/utils/metrics.py#L697](https://github.com/ultralytics/ultralytics/blob/d1107ca4cb5ef2a94a583e0a0247172f7f972f9a/ultralytics/yolo/utils/metrics.py#L697)

**Comment by properallan** [comment]
This change is actually unfortunate, since the new names completely broke compatibility with ray tune, that does not accept some special characters in the name of the metrics. Very annoying...

**Comment by glenn-jocher** [comment]
I understand the inconvenience. You might consider modifying the source code to adjust metric names or explore using a custom logging solution to rename metrics post-training.

**Comment by parkitny** [comment]
> This change is actually unfortunate, since the new names completely broke compatibility with ray tune, that does not accept some special characters in the name of the metrics. Very annoying...

It's possible to get around this by adding to the results dictionary per training step end. You can do it by modifying the source code directly, but it's cleaner to do it with callbacks.

A callback with a hook to `on_train_step_end` is where you make the necessary mods. Copy the metric value you want from the results dictionary, and add another key with your monitor metric name and the corresponding metric value. 

For Ray Tune, you can do it by implementing a ray tune callback, and overwrite `on_step_end` with the extra logic.

**Comment by glenn-jocher** [comment]
You can address this by using a callback to modify the results dictionary at each training step. Implement a Ray Tune callback and override `on_step_end` to adjust the metric names as needed.
