### ISSUE TITLE
Save dir for validation in YOLOv8

### ISSUE THREAD

**Issue by Alonelymess** [ultralytics/ultralytics#6753]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there a way to modify the save_dir in validation mode in YOLOv8?
I have tried "save_dir=" but it raise error "'save_dir' is not a valid YOLO argument. Similar arguments are ['save_crop', 'save', 'save_hybrid']."

**Comment by Alonelymess** [comment]
@RizwanMunawar  tks for your response

**Comment by trianta2** [comment]
> @Alonelymess! Correct, there is no `save_dir` argument for Ultralytics YOLOv8 validation, and by default, there's no option to save validation results to a different location. If you wish to store the validation results, you can clone the 'ultralytics' code and adjust the paths to suit your needs. 👍🏻
> 
> For more information, you can check [Ultralytics YOLOv8 Validation Docs](https://docs.ultralytics.com/modes/val/#usage-examples)
> 
> Feel free to reach out if you have any further questions.
> 
> Thanks, Ultralytics Team!

This seems kind of wild. There should probably be an argument to override the settings default of just littering the cwd.
