### ISSUE TITLE
YOLOv8 training error 

### ISSUE THREAD

**Issue by Nuna7** [ultralytics/ultralytics#6754]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I am trying to continue my training of yolo but this error keep coming up. After investigating I observe that even when trying to import tensorflow, the same error came up. 

```
Kernel Restarting

The kernel for Documents/Computer Vision/Football Field Detection/Football Field detection.ipynb appears to have died. It will restart automatically
```

Further I also try running in vscode and terminal but different error popped up.
```
nuntea@Zonunmawias-MacBook-Air Football Field Detection % yolo detect train model=./runs/detect/train48/weights/last.pt  epochs=5 optimizer=Adam warmup_epochs=4 warmup_momentum=0.9 weight_decay=0.0001 lr0=0.09 data=config.yaml

zsh: illegal hardware instruction  yolo detect train model=./runs/detect/train48/weights/last.pt epochs=5
```

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Python [6270]
Path:                  /Library/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python
Identifier:            org.python.python
Version:               3.9.0 (3.9.0)
Code Type:             X86-64 (Translated)
Parent Process:        Python [3145]
Responsible:           Terminal [2804]
User ID:               501

Date/Time:             2023-12-03 00:43:26.6514 +0530
OS Version:            macOS 14.1.2 (23B92)
Report Version:        12
Anonymous UUID:        F7E462E7-6380-C3DA-E2EC-5CF01A61D195

Sleep/Wake UUID:       F52A47B6-6FDF-4AC6-9730-03C83BC08460

Time Awake Since Boot: 17000 seconds
Time Since Wake:       1577 seconds

System Integrity Protection: enabled

Notes:
PC register does not match crashing frame (0x0 vs 0x13BCB1371)

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 4 Illegal instruction: 4
Terminating Process:   exc handler [6270]

Error Formulating Crash Report:
PC register does not match crashing frame (0x0 vs 0x13BCB1371)

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   _pywrap_tf2.so                	       0x13bcb1371 pybind11::module_::create_extension_module(char const*, char const*, PyModuleDef*) + 17
```

### Environment

Ultralytics YOLOv8.0.221 🚀 Python-3.9.0 torch-2.1.1 CPU (Apple M1)
Setup complete ✅ (8 CPUs, 8.0 GB RAM, 185.2/228.3 GB disk)

OS                  macOS-10.16-x86_64-i386-64bit
Environment         Darwin
Python              3.9.0
Install             pip
RAM                 8.00 GB
CPU                 Apple M1
CUDA                None

matplotlib          ✅ 3.8.2>=3.3.0
numpy               ✅ 1.23.5>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 2.1.1>=1.8.0
torchvision         ✅ 0.16.1>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.1.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

jupyter notebook

```
model = YOLO("./runs/detect/train48/weights/best.pt",task="detect")

model.train(data="config.yaml", epochs=5,optimizer="Adam",warmup_epochs=4,warmup_momentum=0.9,
            weight_decay=0.0001,lr0=0.09)
```

config.yaml

```
train: /Users/nuntea/Documents/Computer Vision/Football Field Detection/aug_data/Train/images
val: /Users/nuntea/Documents/Computer Vision/Football Field Detection/aug_data/Validation/images

names:
     0 : Referee
     1 : Player
     2 : GoalKeeper
     3 : Ball
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pahaht** [comment]
Hey, I'm facing the same problem, I tried to run (train on custom data) YOLOv8  but I got this: 'The kernel appears to have died. It will restart automatically'.

**Comment by glenn-jocher** [comment]
@pahaht hello! The "kernel appears to have died" message typically indicates a system resource issue or an environment incompatibility. Here's what I suggest:

1. Ensure your machine has enough resources (RAM, CPU) to handle the training workload.
2. Check that your Python environment matches the requirements for YOLOv8 and is clean from conflicting dependencies. The use of a fresh virtual environment may also be beneficial.
3. If you're using an M1 Mac, make sure you have versions of `torch` and other dependencies that are compatible with the ARM architecture.

Should the issue persist, feel free to open an issue with detailed logs and system info for more tailored support. Keep up the great work with YOLOv8! 🌟

**Comment by pahaht** [comment]
Thank you @glenn-jocher  for your quick reply, sorry I was sick, and I couldn't work to give you feedback.
1. Processor: Intel(R) Core(TM) i7 CPU @3.20ghZ  and RAM(16GB) ...Intel(R) UHD Graphic 630 and NVIDIA GeForce RTC2060.
2. About the Python environment I think it matches with YOLOv8 because YOLOv8 inference(using Ultralytics weight or my custom weight that I ran on my laptop)  ran well on my Desktop but only the training process did not work. Let me check conflict dependencies.
3. I'm using Windows.

**Comment by glenn-jocher** [comment]
@pahaht no worries, I hope you're feeling better!

Based on your system specs and the fact that inference runs without issues, it's likely not a hardware capability issue. Ensure all drivers, particularly NVIDIA CUDA drivers, are up-to-date as YOLOv8 training heavily relies on these for GPU acceleration.

Also, verify that your Windows environment has the proper versions of PyTorch with CUDA support installed. Conflicting dependencies can still cause issues even if inference works, as training is generally more intensive and may hit code paths not used during inference.

Keep me posted on your progress after checking for conflicting dependencies. All the best!

**Comment by pahaht** [comment]
Thank you  @glenn-jocher now I'm feeling better, I will keep you posted on my progress.

**Comment by glenn-jocher** [comment]
Great to hear you're feeling better, @pahaht! Looking forward to hearing about your progress. If you run into any more issues, just let me know. Best of luck!

**Comment by ztj1224** [comment]
I have same the problem. When I install tensorboard and ultralytics in the same env, the training of yolov8 will break up. Maybe  there are conflict between tensorboard and ultralytics.

**Comment by glenn-jocher** [comment]
@ztj1224 hey there! 😊 It sounds like there might be a version conflict causing the issue. Could you try installing a specific version of TensorBoard that's known to work well with Ultralytics YOLOv8? For example:

```bash
pip install tensorboard==2.4.1
```

Adjust the version number as needed based on compatibility. If the problem persists, please share any error messages you're seeing for more targeted advice. Happy coding!
