### ISSUE TITLE
YOLOv8 on NVIDIA DeepStream

### ISSUE THREAD

**Issue by marcoslucianops** [ultralytics/ultralytics#676]
Repository to use YOLOv8 model on NVIDIA DeepStream SDK

Link: https://github.com/marcoslucianops/DeepStream-Yolo

NOTE: Only object detection for now.

#### Config

```
board = NVIDIA Tesla V100 (AWS: p3.2xlarge)
batch-size = 1
eval = val2017 (COCO)
sample = 1920x1080 video
```

#### NMS config

- Eval

```
nms-iou-threshold=0.6
pre-cluster-threshold=0.001
topk=300
```

- Test

```
nms-iou-threshold=0.45
pre-cluster-threshold=0.25
topk=300
```

#### Results (comming soon)

| DeepStream         | Precision | Resolution | IoU=0.5:0.95 | IoU=0.5 | IoU=0.75 | FPS<br />(without display) |
|:------------------:|:---------:|:----------:|:------------:|:-------:|:--------:|:--------------------------:|
| YOLOv8x            | FP16      | 640        |         |    |     |                      |
| YOLOv8l            | FP16      | 640        |         |    |     |                      |
| YOLOv8m            | FP16      | 640        |         |    |     |                      |
| YOLOv8s            | FP16      | 640        |         |    |     |                      |
| YOLOv8n            | FP16      | 640        |         |    |     |                      |

**Comment by pderrenger** [comment]
@marcoslucianops it's great to see the integration of the YOLOv8 model with the NVIDIA DeepStream SDK for object detection! YOLOv8 offers impressive speed and accuracy for real-time object detection.

Based on your configuration, it seems you're using the NVIDIA Tesla V100 with a batch size of 1 and evaluating on the COCO val2017 dataset. The various NMS configurations for both evaluation and testing will surely fine-tune the model's detection performance.

I'm eager to see the results for YOLOv8x, YOLOv8l, YOLOv8m, YOLOv8s, and YOLOv8n on your setup. It would be interesting to compare their precision, resolution, IoU thresholds, and FPS performance without display.

Feel free to reach out if you need any further assistance or have any questions about YOLOv8! Good luck with your evaluation and testing, and I look forward to seeing the results.
