### ISSUE TITLE
Confidence scores in image classification

### ISSUE THREAD

**Issue by fnoroozi** [ultralytics/ultralytics#677]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to use YOLOv8 for image classification and need to get the confidence scores of all classes for each image. When I run my model, it prints the confidence scores in the command prompt, but when I try to run:

results = model(file)
results.save()

it throws the following error:

AttributeError: 'NoneType' object has no attribute 'save'

**Comment by kyoko9000** [comment]
Try with results = model(file, save = True)

**Comment by fnoroozi** [comment]
This will save an image like the otiginal one, with the confidence scores
overlayed, which I do not know how to retrieve. Instead, I need the
confidence scores either returned as variables, or written to a text file
or something like that, because I would like to keep those for further
analysis.
