### ISSUE TITLE
RayTune + ClearML -> unusual logging behavior

### ISSUE THREAD

**Issue by kirill-ionkin** [ultralytics/ultralytics#6778]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello everyone, i research HPO(Hyper Params Optimization) in YOLO and found a little bit(in my opinion) unusuall behavior.

I try to found some hyperparams, that help improve model's metrics ans write simple script, based on run_ray_tune.py scipt inside ultralytics repo.
[tune.txt](https://github.com/ultralytics/ultralytics/files/13546776/tune.txt) - my script to tune YOLO model.

Also, i run this script with settings:
[run_tune.txt](https://github.com/ultralytics/ultralytics/files/13546796/run_tune.txt)

I have configured clearml and of course, my experiments always is logging with ClearML, but at this time was created only 2 tasks(screen here
![Screenshot from 2023-12-04 17-00-34](https://github.com/ultralytics/ultralytics/assets/56236621/61872514-50a7-477e-bbb9-53137598b347)
) inside ClearML server and at the end of trainig one experiment, next experiment continue logging on the same ClearML task - it looks strange i think - not possible to compare or check hpo experiments independently, so my question - is this behavior good/usual  or someone could improve this and how?

Thanks a lot for your attention!

**Comment by glenn-jocher** [comment]
@kirill-ionkin hello! It seems you're encountering an issue with task logging in ClearML when running hyperparameter optimization with the `run_ray_tune.py` script. If only two tasks are created and subsequent experiments are logging under the same task in ClearML, this could potentially hinder separate analysis of each HPO experiment.

Each individual experiment during HPO should ideally generate its own task to allow for independent comparison and analysis. The current logging behavior you're experiencing isn't typical and might be related to the configuration of your script or a specific interaction between Ray Tune and ClearML.

To address this, you might want to verify that a new ClearML task is explicitly created for each Ray Tune trial within your script. If everything seems configured correctly, it might be helpful to look into the loggers within RayTune or the callbacks used for ClearML integration to ensure they are initiating new tasks correctly.

If the issue persists, please consider opening a detailed issue in our repo under discussions for further assistance. Our community and team will be glad to help you troubleshoot this unusual behavior.

Thank you for bringing this to our attention, and we appreciate your contribution to improving the YOLOv8 model training process! 😊

For further reading on modes like Train, Val, Predict, and others, feel free to visit the Ultralytics Docs.

**Comment by kirill-ionkin** [comment]
Thank you, @glenn-jocher, for fast answer. I spent a little bit more time of problem by logging RayTune experiments to ClearML and unfourtunately couldn't solve this problem(if it is will be someone helpful, env. variables, like 'RAY_memory_usage_threshold' = 1, 'RAY_memory_monitor_refresh_ms'=0 can't help to correct logging, also gpu_per_trial=1 or 2 or more GPU devices doesn't affect of logging to ClearML), but also found new problems, like OOM Error, when trying to HPO with RayTune.

So, my decision was to use custom Tuner from ultralitics repo and, fortunately, it works well ang logging experiments as I expected at the start of HPO experiments, BUT one question about `class Tunes.__init__`: self.space = {default hyp. settings} 
Maybe, is it good idea to allow update self.space by get in __init__ **kwargs with space={new hyp. settings}
ans change creating self.space from `self.space = {default hyp. settings}`
to `self.space = {default hyp. settings} if not hasattr(self, 'space')`? 
I understand, that i can change source code manually of course, but with implementation abowe it's possible to just create new dictionary with needed hyperparams and pass it it Tuner? - what do you think about it?

Thank you for your attention)

**Comment by glenn-jocher** [comment]
@kirill-ionkin, thanks for your persistence in finding a suitable solution! I'm glad to hear that switching to the custom Tuner from our repo has resolved the ClearML logging issue for you.

Regarding your suggestion to make the `self.space` attribute in the `Tuner.__init__` method more flexible by allowing updates through `**kwargs`: this is indeed a valuable proposal. Allowing users to pass a hyperparameter space dictionary directly when initializing the Tuner would offer increased flexibility and convenience.

For now, you can certainly modify the source code to implement your preferred behavior. Meanwhile, your idea seems like it could benefit others as well. I suggest opening a discussion or feature request in our repo. This way, the community can weigh in, and we can consider making changes in a future update of the software.

Your feedback is important to us, as it helps to enhance the YOLOv8 experience. Thank you for your contribution! 😊🚀

**Comment by kirill-ionkin** [comment]
Hello @glenn-jocher , i created  feature request: https://github.com/ultralytics/ultralytics/issues/6856, so, i hope, anyone will find  this idea  needed)

**Comment by glenn-jocher** [comment]
@kirill-ionkin, thank you for submitting the feature request! We value community contributions and will review your suggestion. We encourage further discussion on the issue you created to allow others in the community to provide their insights and feedback. Keep an eye on the issue for updates or additional comments from the team and the community! 👀🚀
