### ISSUE TITLE
very urgent help required in json for image classification

### ISSUE THREAD

**Issue by anut123** [ultralytics/ultralytics#6779]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

very urgent help required in json for image classification
how to do this format in json i have tired alot but could not find any solution ---> {'predictions': [{'confidence': 99, 'label': 'car',}, {'confidence': 99, 'label': 'dog', }, { 'confidence': 99, 'label': 'person'}]}
@glenn-jocher
@AyushExel
@RizwanMunawar

**Comment by RizwanMunawar** [comment]
@anut123 you can get image classification prediction results using Ultralytics YOLOv8 in JSON format with the mentioned code below.

```python
from ultralytics import YOLO

json_format = {'predictions':[]}
model = YOLO('yolov8n-cls.pt')  # load a custom model

results = model('https://ultralytics.com/images/bus.jpg', verbose=False)  # Predict with the model

clss_index = results[0].probs.top5
clss_conf = results[0].probs.top5conf
names = results[0].names

for ind, conf in zip(clss_index, clss_conf):
    json_format['predictions'].append([{'confidence': f'{int(conf * 100)}', 'label': f'{names[int(ind)]}'}])
print(json_format)
```

Hope this helps! Let me know if you have any additional questions.

Thanks
Ultralytics Team!

**Comment by RizwanMunawar** [comment]
@anut123 The code is working on myside without any error.

Thanks

**Comment by anut123** [comment]
@RizwanMunawar what modules or libraries you have imported to fix this error ---> AttributeError: 'Tensor' object has no attribute 'top5' as i am getting this error tired multiple ways

**Comment by RizwanMunawar** [comment]
@anut123 Excellent! I am closing this issue for the time being. You're welcome to reopen it if the issue persists.

Thanks
Ultralytics Team!
