### ISSUE TITLE
Standard way of training

### ISSUE THREAD

**Issue by Pixelogical** [ultralytics/ultralytics#6781]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I know that my question has multiple answers, I want to know how many epochs with how much data should I train the model to have results with the least number of false positives. I've experienced in few scenarios that the model not improved on lessen **FP** as expected. for example in my last project, I trained a YOLOv8 model to detect animals in a field but I have some false positive with high confidence in some frames of a video. I don't know what to do how to avoid that. my general experience is that YOLOv8 not improve well and **FP** remains. I usually train 20-25 epochs on a pretrained model.

**Comment by PiyushKamboj1503** [comment]
hey @Pixelogical, for benchmarking purposes I highly recommend going for atleast 300 epochs. You need to scale your patience of the training accordinly. The default is set to 100. With that number of epochs, hopefully you will be able to achieve the results you want. Also, you can utilise the 'yolov8_.yaml' architectures if your object is not in close relationship with the pretrained objects in the given classes. In case you need any help, feel free to connect.
