### ISSUE TITLE
yolo commad classify why use detect？

### ISSUE THREAD

**Issue by lonngxiang** [ultralytics/ultralytics#6783]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

[https://docs.ultralytics.com/datasets/classify/#dataset-format](url)
![image](https://github.com/ultralytics/ultralytics/assets/40717349/57ee4ae8-254a-4e1f-8720-2f135ba4c6a5)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@lonngxiang hello! Thanks for reaching out. It seems you've noticed some unexpected behavior when utilizing our classification mode and it's defaulting to detection instead.

Please ensure you are using the correct command for classification when running the model. Our classification mode is distinct from the detection mode, although both share underlying architecture. If you're still having issues, double-check your dataset format and the commands you're using against our `classify` documentation.

For any specific bugs, consider opening an issue with details about the command you're running and the unexpected behavior you're observing. The willingness to submit a PR is highly appreciated! 🌟 Should you decide to do so, please follow our contribution guidelines and provide all necessary details.

Happy coding! 🚀

**Comment by tigerdhl** [comment]
I also confused about the classify model in  “onnx” format. I have converted my training classify model  “.pt” to ".onnx", and found the "task" information in the onnx is "detect". But, I found the "yolov8n-cls.onnx" converted from "yolov8n-cls.pt", which the "task" information is the right "classify".

**Comment by glenn-jocher** [comment]
@tigerdhl hello! The 'task' metadata in the ONNX model should indeed reflect the nature of the model—'classify' for a classification model. If your converted ONNX model indicates 'detect' instead of 'classify', it's possible that the conversion process might have retained metadata from a previous detection model. Please cross-verify the model conversion steps as outlined in our `Export` documentation. Remember to start the conversion with the correct classification model `.pt` file. If the issue persists, please open a detailed issue, and we'll investigate further. Thanks for contributing to the YOLOv8 community! 🛠️👀

**Comment by tigerdhl** [comment]
> @tigerdhl hello! The 'task' metadata in the ONNX model should indeed reflect the nature of the model—'classify' for a classification model. If your converted ONNX model indicates 'detect' instead of 'classify', it's possible that the conversion process might have retained metadata from a previous detection model. Please cross-verify the model conversion steps as outlined in our `Export` documentation. Remember to start the conversion with the correct classification model `.pt` file. If the issue persists, please open a detailed issue, and we'll investigate further. Thanks for contributing to the YOLOv8 community! 🛠️👀

I found the problem come from the set of the file "ultralytics/cfg/default.yaml". Thank u.

**Comment by glenn-jocher** [comment]
@tigerdhl Great to hear you've located the source of the issue! Configurations can often be the culprit with these kinds of mix-ups. If you have any further queries or need assistance in the future, feel free to reach out. Thank you for being proactive in solving this, and for being a part of our community! Happy detecting... or classifying! 😄👍
