### ISSUE TITLE
How to specify screen number?

### ISSUE THREAD

**Issue by TheUntitledGoose** [ultralytics/ultralytics#6784]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The CLI arguments for source only allows 1 argument. How do I specify for it to use only my left monitor. Say monitor 0.

**Comment by Johan154** [comment]
Source refers to a directory of images or videos, so the source of the data you want to run inference on. E.g. 'ultralytics/assets'

**Comment by glenn-jocher** [comment]
@Johan154 in YOLOv8, the `source` parameter is designed to specify the location of your input data, such as a directory of images or videos where inference is to be performed. It is not meant to select monitors or hardware devices directly. If you aim to process visuals from a specific monitor, you would typically capture the output of that monitor to a file or stream and then pass that as the source for your YOLOv8 task. ✨

**Comment by Johan154** [comment]
@glenn-jocher that is exactly what I wanted to say to @TheUntitledGoose

**Comment by TheUntitledGoose** [comment]
I kind of wanted to avoid making a python script for capturing of the monitor. But thanks either way.

**Comment by glenn-jocher** [comment]
@TheUntitledGoose understood! While a Python script is indeed a common approach for such tasks, do explore other methods of capturing your monitor's output that might align better with your workflow. Happy exploring! 🚀
