### ISSUE TITLE
INITIALIZING MODELS WITH LARGER ONES

### ISSUE THREAD

**Issue by PiyushKamboj1503** [ultralytics/ultralytics#6785]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

The availability of Pretrained Yolov8 Models are one of the pioner features of this framework. However, a larger model with 80 classes sometimes creates a lot of load on the system. To tackle this problem, we have been using 'classes' argument. However, with the recent techniques coming into light, it is vital to implement improvements to make those pre trained weights available as smaller models with classes selection. 

In this feild. a research paper by the name 'INITIALIZING MODELS WITH LARGER ONES' has come up recently. The paper is available at: https://arxiv.org/pdf/2311.18823.pdf
Code is available at: https://github.com/OscarXZQ/weight-selection

I would like the fellow developers and contributors to have a look into this and let's see if we can implement this with Yolov8 framework as well.

### Use case

The use case includes:
1. Class selection in pretrained weights to initilaze smaller models.
2. 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@PiyushKamboj1503 hello and thanks for your interest in improving the YOLOv8 framework! We appreciate your initiative in bringing this research to our attention. The idea of initializing models with a selected subset of classes from larger pretrained models to reduce system load is intriguing. 🤔

We're continuously looking to adopt innovative methods that enhance the capability and efficiency of YOLOv8. While incorporating strategies like the one you've pointed out requires careful consideration of the system design and testing, we encourage contributions that align with our goals.

For those interested in contributing to this area, it would be beneficial to start by evaluating the method's compatibility with YOLOv8's architecture and how it might integrate with our current class selection features.

Please consider discussing further implementation details and potential integration strategies directly in the YOLOv8 GitHub discussions or by submitting a preliminary PR for review. Your collaboration is highly valued, and we look forward to seeing how such innovations could meld with YOLOv8 to benefit users looking to customize model classes while optimizing performance. 😊

For more guidelines on contributing, please refer to our documentation at https://docs.ultralytics.com. Thank you for being proactive in our community!
