### ISSUE TITLE
Track selected bounding box

### ISSUE THREAD

**Issue by akshaydhame2001** [ultralytics/ultralytics#6787]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm trying to track objects with pan-tilt servos. I'm able to track only single object with class and id passed. If multiple objects of same classes but different unique id are in frame then how to track object on which mouse is clicked by getting id or directly getting box coordinates?

Here is my code snippet -

                for j, (output) in enumerate(outputs[i]):

                        bbox = output[0:4]
                        id = output[4]
                        cls = output[5]
                        conf = output[6]

                        # to MOT format
                        bbox_left = output[0]
                        bbox_top = output[1]
                        bbox_w = output[2] - output[0]
                        bbox_h = output[3] - output[1]

                        print(f"cls : {cls}, id : {id}")
                        if(names[int(cls)] == "cat" and id == 1):

                            objX= bbox_left + int(bbox_w/2)
                            objY= bbox_top + int(bbox_h/2)
               
                            errorPan=objX-width/2
                            errorTilt=objY-height/2
                            if abs(errorPan)>15:
                                    pan=pan-errorPan/75
                            if abs(errorTilt)>15:
                                    tilt=tilt+errorTilt/75

**Comment by glenn-jocher** [comment]
@akshaydhame2001 hello! To achieve tracking of a specific object based on mouse clicks, you'll need to integrate an event handler into your application that records mouse events. When a user clicks on the object, your handler should record the coordinates of the click. Then, compare these coordinates with the bounding box coordinates of detected objects to determine which object is being selected.

You'd have to manage the state of the selected object's ID once clicked, allowing you to keep following that particular object even when multiple instances of the same class are present. The selection logic needs to be outside and prior to the tracking loop in your snippet above.

If this needs further clarification or guidance on implementation, you might find our documentation at https://docs.ultralytics.com helpful, especially the Track Mode section for insights. Remember to strictly respect privacy and ethical guidelines while tracking individuals or sensitive subjects. 🛠️✨
