### ISSUE TITLE
AGPL-3.0 license : Third party framework inference, ONNX model, whether protocol compliance is required

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#6789]
Third party framework inference, ONNX model, whether protocol compliance is required
AGPL-3.0 license

onnxruntime + yolov8 onnx
Do we need to comply with the open source agreement ?

Convert onnx format
Should we comply with the onnx open source protocol ?
Apache-2.0

**Comment by glenn-jocher** [comment]
@monkeycc hello there! 👋 When you use our YOLOv8 models and operate under the AGPL-3.0 license, any modifications to the software or incorporation into an open-source project are expected to adhere to AGPL-3.0 terms. If you use ONNX models with onnxruntime in a third-party framework, the obligation to comply with AGPL-3.0 depends on how the model and software are used and distributed; this can be a complex area.

If the ONNX conversion is a part of your project’s pipeline, and if the project is distributed, then compliance with AGPL-3.0 is necessary. ONNX itself is under Apache-2.0 license, which is more permissive, but it doesn't negate the AGPL-3.0 requirements of our YOLOv8 models.

If you seek a more permissive license that grants additional flexibility for proprietary work, consider our Enterprise license, allowing integration into closed-source projects without the obligations of AGPL-3.0.

For detailed guidance on licensing, you might want to consult with a legal professional. Thank you for engaging with the YOLO community and Ultralytics! 😊
