### ISSUE TITLE
How to save output detect text for images 

### ISSUE THREAD

**Issue by totoadel** [ultralytics/ultralytics#679]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to get output detected text like what happened in Yolo v5, --save-txt how to do that

**Comment by prince0310** [comment]
you can  add a line no 78 in `ultralytics/yolo/v8/detect/predic.py`  
`print(self.model.names[int(c)])`

**Comment by AyushExel** [comment]
@totoadel pass `save_txt=True`

**Comment by totoadel** [comment]
@AyushExel thank you
