### ISSUE TITLE
Custom path 

### ISSUE THREAD

**Issue by ajanujaj** [ultralytics/ultralytics#6791]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, 

I am new to computer vision and trying to learn Yolo.
 
I am able to use YOLO very easily.  and I just have a little concern about how I pass the variable to CLI rather than passing the whole path.

This is working:
`!yolo task=segment mode=train model=yolov8n-seg.pt conf=0.25 data='/Users/Desktop/Side_Project/Task1/human detection dataset/Obj-Person-Detection-1/data.yaml' epochs=4`

But this is not:
`homepath = '/Users/Desktop/Side_Project/Task1/human detection dataset/'
datapath = homepath + 'Obj-Person-Detection-1/data.yaml'
print(datapath)
/Users/Desktop/Side_Project/Task1/human detection dataset/Obj-Person-Detection-1/data.yaml`

`!yolo task=segment mode=train model=yolov8n-seg.pt conf=0.25 data=datapath epochs=4

raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
RuntimeError: Dataset 'datapath' error ❌ 'datapath' does not exist`

**Comment by PiyushKamboj1503** [comment]
@ajanujaj the CLI won't hold the values like a regular python program. For such functionality you can create this in a python file.

**Comment by ajanujaj** [comment]
Thanks @PiyushKamboj1503 , for your reply

**Comment by glenn-jocher** [comment]
@ajanujaj you're welcome! If you're using the CLI, you'll need to pass the full path directly. For dynamic path handling, consider using a Python script instead. Happy coding! 😊👍
