### ISSUE TITLE
While running multiple RTSP streams with MultiThreading approach, inference time is too high

### ISSUE THREAD

**Issue by VM8198** [ultralytics/ultralytics#6792]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello @glenn-jocher 

My use case is to run multiple RTSP streams( max 8) in a single system.

I've used multi threading approach to resolve this. It works fine but the issue is inference time is too high i.e. around 4000ms. Because of this the live detection feature is not working and detection speed is very slow. Below is the code. Please check and let me know if I'm making any mistakes.

```python
import cv2
import logging
import concurrent.futures
import cv2
from ultralytics import YOLO
import torch


device = torch.device('cpu')
    
def modelSelector(videoStream, config):
    model = YOLO('yolov8n.pt')
    while True:
        ret, frame = videoStream.read()
        
        if not ret:
            videoStream = cv2.VideoCapture(config.get("serverUrl"))
            continue

        if frame is None:
            continue
            
        plotted_frame = None
            
        detected = model.track(frame, persist=True, device=device, classes=[0])
        
        plotted_frame = detected[0].plot()

        cv2.imshow("Frame", plotted_frame)
       

def process_camera_config(config):
    
    videoStream = cv2.VideoCapture(config.get("url"))
        
    modelSelector(
        videoStream,
        config
    )

def main():
    try:
        data = {"streams": [{"1": {"url": "stream1"},"2": {"url": "stream2"},"3": {"url": "stream3"},"4": {"url": "stream4"}}]}

        camConfig = [*data.get("streams")[0].values()]

        with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:
            executor.map(process_camera_config, camConfig)


    except Exception as e:
        logging.error(f"Error occurred in main: {e}")


if __name__ == "__main__":
    while True:
        main()
```

Thanks.

**Comment by PiyushKamboj1503** [comment]
@VM8198 have you tried running multiple streams using the 'source='list.streams''. Please check with this one and share the results. https://docs.ultralytics.com/modes/predict/#inference-sources

**Comment by VM8198** [comment]
Thanks @PiyushKamboj1503, I will try this

**Comment by PiyushKamboj1503** [comment]
> Thanks @PiyushKamboj1503, I will try this
> 

Any update?

**Comment by glenn-jocher** [comment]
@VM8198 great to hear that the solution worked for you! If you have any more questions or need further assistance, feel free to reach out. Happy detecting! 😊🚀

**Comment by VM8198** [comment]
Hello @glenn-jocher. does list.stream works with multi threading or multi processing in background?  because still I'm facing issue with the inference time latency. and the live detection is not working it is always 5-7 minutes behind the live stream and it is also skipping many frames.

I also noticed that if vid_stride=10 is applied to the inference it takes, more inference time than vid_stride=1. Is it possible? or am I doing any mistakes. please clarify.

**Comment by glenn-jocher** [comment]
Hello @VM8198. The `list.streams` approach should work with both multi-threading and multi-processing. However, if you're experiencing latency issues, I recommend checking if the latest package versions are installed. Regarding `vid_stride`, using a higher stride should generally reduce inference time, not increase it. Please ensure your implementation is correct and consider testing with different configurations to identify the bottleneck. If the issue persists, feel free to provide more details for further assistance.
