### ISSUE TITLE
TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by jiubie89** [ultralytics/ultralytics#6795]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I use Yolov8 to perform instance segmentation training, an error is reported at the beginning：

Transferred 651/657 items from pretrained weights
Traceback (most recent call last):
  File "train_yolo_55x7.py", line 13, in <module>
    results = model.train('/shiyanshi2/user/caozhongji/ultralytics-main/train_yolo_55x7.yaml', epochs=300, imgsz=640, device=[1])
  File "/shiyanshi2/user/caozhongji/ultralytics-main/ultralytics/engine/model.py", line 333, in train
    self.trainer = (trainer or self._smart_load('trainer'))(overrides=args, _callbacks=self.callbacks)
TypeError: 'str' object is not callable

Please help

**Comment by RizwanMunawar** [comment]
@jiubie89 Thanks for sharing the information, can you please share the file `train_yolo_55x7.yaml`? It will help us to look into the issue in more detail.

Thanks
Ultralytics Team!

**Comment by jiubie89** [comment]
> @jiubie89 Thanks for sharing the information, can you please share the file `train_yolo_55x7.yaml`? It will help us to look into the issue in more detail.
> 
> Thanks Ultralytics Team!
It's yaml config information：

path: /shiyanshi2/user/caozhongji/ultralytics-main/datasets/yolo_55x7 
train: images/train
val: images/val
# test: test-dev2017.txt  # 20288 of 40670 images, submit to https://competitions.codalab.org/competitions/20794

# Classes
names:
  0: Grp
  1: GrpOC

**Comment by jiubie89** [comment]
> @jiubie89 Thanks for sharing the information, can you please share the file `train_yolo_55x7.yaml`? It will help us to look into the issue in more detail.
> 
> Thanks Ultralytics Team!
![41bac88df524fec078419c71297f427](https://github.com/ultralytics/ultralytics/assets/149553348/144f96bc-827d-476e-a186-018c20611fcd)

**Comment by jiubie89** [comment]
> @jiubie89 Thanks for sharing the information, can you please share the file `train_yolo_55x7.yaml`? It will help us to look into the issue in more detail.
> 
> Thanks Ultralytics Team!

that's the yaml config information

**Comment by jiubie89** [comment]
I'm not using the yolo command，this is my train.py : 
![Uploading da4c2e702f36855bac06ab658daeb57.png…]()

**Comment by jiubie89** [comment]
> @jiubie89 Thanks for sharing the information, can you please share the file `train_yolo_55x7.yaml`? It will help us to look into the issue in more detail.
> 
> Thanks Ultralytics Team!

I'm not using the yolo command，this is my train.py :
![da4c2e702f36855bac06ab658daeb57](https://github.com/ultralytics/ultralytics/assets/149553348/0e49d852-8253-47dd-8fec-e3b6a2875b8b)

**Comment by jiubie89** [comment]
> @jiubie89 Thanks for sharing the information, can you please share the file `train_yolo_55x7.yaml`? It will help us to look into the issue in more detail.
> 
> Thanks Ultralytics Team!

Last week, I was able to start training normally on linux, but this week it suddenly didn't work

**Comment by jiubie89** [comment]
> @jiubie89 Thanks for sharing the information, can you please share the file `train_yolo_55x7.yaml`? It will help us to look into the issue in more detail.
> 
> Thanks Ultralytics Team!

Sorry，It's been solved，results=model.train（data=‘’），I forgot to add data

**Comment by glenn-jocher** [comment]
@jiubie89 great to hear that the issue is resolved! If you encounter any more questions or difficulties, feel free to reach out. Happy training with YOLOv8! 🚀

**Comment by glenn-jocher** [comment]
@agbozo1 it seems like there might be an issue with how the `trainer` is being set. Ensure that the `trainer` parameter is not being passed as a string. If you need further assistance, please check the documentation or share more details about your setup.

**Comment by agbozo1** [comment]
Solved it @glenn-jocher . Thank you. 
it is important to indicate the arguments. Without indicating data='...yaml file', it was detecting the yaml file as the trainer.
`model.train(**data=**"/content/dataset/coco8.yaml", epochs=100, batch=8)`

**Comment by glenn-jocher** [comment]
Glad to hear you resolved it! Specifying the `data` argument is indeed crucial. If you have more questions, feel free to ask.

**Comment by cainiao123s** [comment]
D:\Anaconda\envs\KDYOLO\python.exe E:/KD/main.py
Ultralytics 8.3.99 🚀 Python-3.10.18 torch-2.7.0+cu128 CUDA:0 (NVIDIA GeForce RTX 5090, 32607MiB)
engine\trainer: task=detect, mode=train, model=E:\KD\runs\detect\train31\weights\last.pt, data=E:\KD\VOC.yaml, epochs=100, time=None, patience=100, batch=24, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=0, project=None, name=train31, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=E:\KD\runs\detect\train31\weights\last.pt, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=None, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.0, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\train31

                   from  n    params  module                                       arguments                     
  0                  -1  1      2784  ultralytics.nn.modules.conv.Conv             [3, 96, 3, 2]                 
  1                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]               
  2                  -1  2    389760  ultralytics.nn.modules.block.C3k2            [192, 384, 2, True, 0.25]     
  3                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]              
  4                  -1  2   1553664  ultralytics.nn.modules.block.C3k2            [384, 768, 2, True, 0.25]     
  5                  -1  1   5309952  ultralytics.nn.modules.conv.Conv             [768, 768, 3, 2]              
  6                  -1  2   5022720  ultralytics.nn.modules.block.C3k2            [768, 768, 2, True]           
  7                  -1  1   5309952  ultralytics.nn.modules.conv.Conv             [768, 768, 3, 2]              
  8                  -1  2   5022720  ultralytics.nn.modules.block.C3k2            [768, 768, 2, True]           
  9                  -1  1   1476864  ultralytics.nn.modules.block.SPPF            [768, 768, 5]                 
 10                  -1  2   3264768  ultralytics.nn.modules.block.C2PSA           [768, 768, 2]                 
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 13                  -1  2   5612544  ultralytics.nn.modules.block.C3k2            [1536, 768, 2, True]          
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 16                  -1  2   1700352  ultralytics.nn.modules.block.C3k2            [1536, 384, 2, True]          
 17                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]              
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 19                  -1  2   5317632  ultralytics.nn.modules.block.C3k2            [1152, 768, 2, True]          
 20                  -1  1   5309952  ultralytics.nn.modules.conv.Conv             [768, 768, 3, 2]              
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 22                  -1  2   5612544  ultralytics.nn.modules.block.C3k2            [1536, 768, 2, True]          
 23        [16, 19, 22]  1   3168652  ultralytics.nn.modules.head.Detect           [20, [384, 768, 768]]         
YOLO11x summary: 357 layers, 56,896,876 parameters, 56,896,860 gradients, 195.6 GFLOPs

Transferred 1015/1015 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Scanning E:\KD\VOC2007+2012\VOC2007+2012\labels\train.cache... 22136 images, 0 backgrounds, 0 corrupt: 100%|██████████| 22136/22136 [00:00<?, ?it/s]
val: Scanning E:\KD\VOC2007+2012\VOC2007+2012\labels\val.cache... 4952 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4952/4952 [00:00<?, ?it/s]
Plotting labels to runs\detect\train31\labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: SGD(lr=0.01, momentum=0.9) with parameter groups 167 weight(decay=0.0), 174 weight(decay=0.0005625000000000001), 173 bias(decay=0.0)
Resuming training E:\KD\runs\detect\train31\weights\last.pt from epoch 88 to 100 total epochs
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to runs\detect\train31
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     88/100      21.8G      0.592      0.492      1.052        137        640:  61%|██████    | 561/923 [04:32<02:55,  2.06it/s]
Traceback (most recent call last):
  File "E:\KD\main.py", line 17, in <module>
    model.train(data=r"E:\KD\VOC.yaml",batch=24,epochs=100, workers=0,resume=True)
  File "D:\Anaconda\envs\KDYOLO\lib\site-packages\ultralytics\engine\model.py", line 791, in train
    self.trainer.train()
  File "D:\Anaconda\envs\KDYOLO\lib\site-packages\ultralytics\engine\trainer.py", line 211, in train
    self._do_train(world_size)
  File "D:\Anaconda\envs\KDYOLO\lib\site-packages\ultralytics\engine\trainer.py", line 367, in _do_train
    for i, batch in pbar:
  File "D:\Anaconda\envs\KDYOLO\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "D:\Anaconda\envs\KDYOLO\lib\site-packages\ultralytics\data\build.py", line 59, in __iter__
    yield next(self.iterator)
  File "D:\Anaconda\envs\KDYOLO\lib\site-packages\torch\utils\data\dataloader.py", line 733, in __next__
    data = self._next_data()
  File "D:\Anaconda\envs\KDYOLO\lib\site-packages\torch\utils\data\dataloader.py", line 789, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anaconda\envs\KDYOLO\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda\envs\KDYOLO\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda\envs\KDYOLO\lib\site-packages\ultralytics\data\base.py", line 368, in __getitem__
    return self.transforms(self.get_image_and_label(index))
  File "D:\Anaconda\envs\KDYOLO\lib\site-packages\ultralytics\data\augment.py", line 202, in __call__
    data = t(data)
  File "D:\Anaconda\envs\KDYOLO\lib\site-packages\ultralytics\data\augment.py", line 202, in __call__
    data = t(data)
  File "D:\Anaconda\envs\KDYOLO\lib\site-packages\ultralytics\data\augment.py", line 396, in __call__
    mix_labels = [self.dataset.get_image_and_label(i) for i in indexes]
  File "D:\Anaconda\envs\KDYOLO\lib\site-packages\ultralytics\data\augment.py", line 396, in <listcomp>
    mix_labels = [self.dataset.get_image_and_label(i) for i in indexes]
  File "D:\Anaconda\envs\KDYOLO\lib\site-packages\ultralytics\data\base.py", line 380, in get_image_and_label
    label = deepcopy(self.labels[index])  # requires deepcopy() [https://github.com/ultralytics/ultralytics/pull/1948 fix shallow copy by Laughing-q · Pull Request #1948 · ultralytics/ultralytics](https://github.com/ultralytics/ultralytics/pull/1948) fix shallow copy by Laughing-q · Pull Request #1948 · ultralytics/ultralytics  
  File "D:\Anaconda\envs\KDYOLO\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "D:\Anaconda\envs\KDYOLO\lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\Anaconda\envs\KDYOLO\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
TypeError: 'str' object is not callable

Process finished with exit code 1

I made a similar mistake. Could you please tell me how to solve it?

**Comment by glenn-jocher** [comment]
@cainiao123s this is a different error from the original issue in this thread. Your error is occurring during data augmentation processing, specifically during deepcopy of labels. This typically indicates a data format issue in your dataset labels.

Try disabling augmentations temporarily to isolate the issue:

```python
model.train(data="E:\KD\VOC.yaml", batch=24, epochs=100, workers=0, resume=True, mixup=0.0, mosaic=0.0, copy_paste=0.0)
```

If training works without augmentations, the issue is likely with your label format or corrupted label files. Please create a new issue with your specific error details for proper assistance.
