### ISSUE TITLE
Training without Visibility Flag 

### ISSUE THREAD

**Issue by navidTerraNova** [ultralytics/ultralytics#6810]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I trained the model without using the visibility flag, label.txt files are like this:

`0 0.850000 0.528646 0.300000 0.564236 0.902405 0.340540 0.917863 0.332757 0.000000 0.000000 0.958274 0.353383 0.000000 0.000000 0.968450 0.464557 0.933433 0.389054 0.917802 0.610631 0.905097 0.481406 0.825219 0.651606 0.847482 0.521757 0.906190 0.623152 0.874554 0.569051 0.857551 0.693905 0.801032 0.597744 0.855234 0.773934 0.760685 0.668444`

`<cls> <x> <y> <w> <h> <x1> <y1> <x2> <y2> ...`

I didn't include visibility flag (39 total number)

I also changed the data-set.yaml file to kpt_shape: [17, 2]

is this correct?
because when I tried to test the model the out put was like this:

![results](https://github.com/ultralytics/ultralytics/assets/115950927/89abbc42-3d09-4c6d-b65c-2d7648681e91)

withou the skeleton.

**Comment by glenn-jocher** [comment]
@navidTerraNova hello! It looks like your labels are formatted for keypoints with `x`, `y` coordinates but are missing the visibility flag for each keypoint. The visibility flag is important as it indicates whether a keypoint is visible or not, which helps the model during training and prediction.

The usual format for keypoints in our system is `<cls> <x> <y> <v> <x1> <y1> <v1>...` where `v` denotes visibility (1 for visible, 0 for not visible). Your `kpt_shape: [17, 2]` setting correctly represents 17 keypoints with 2 values each (ignoring visibility), but you should adjust this to `[17, 3]` to include the visibility flags.

You will need to add visibility flags to your label files and update the dataset configuration to properly reflect the keypoint shapes, including visibility. After these adjustments, you should retrain your model for the skeleton to be correctly predicted.

Please refer to our docs for a more elaborate walkthrough on using keypoints and visibility flags with YOLOv8. 📚
