### ISSUE TITLE
Can we anyhow skip the frames when it is list.streams as source?

### ISSUE THREAD

**Issue by VM8198** [ultralytics/ultralytics#6812]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello @glenn-jocher 

I'm using list.streams as source to track objects in RTSP stream. Current issue is when we provide list.streams, it tracks all the frames. I wanted to know if there is any option to skip the frames or decrease the FPS while using list.streams? 

Below is the code

```python

import cv2
from ultralytics import YOLO
import torch
import random

device = torch.device('cpu')
model = YOLO('yolov8n.pt')

def main():
    try:           
        results = model.track(source='list.streams', persist=True, device=device, stream=True, vid_stride=1, stream_buffer=True)
        for result in results:
            counter += 1
            frame = result.plot()
            cv2.imwrite('images/' + str(random.random()) + '.jpg', frame)
    except Exception as e:
        print(e)  

if __name__ == "__main__":
        main()

### Additional

_No response_

**Comment by glenn-jocher** [comment]
@VM8198 hello!

You can indeed control the frame rate by adjusting the `vid_stride` parameter in the tracking function. If you want to skip frames, set `vid_stride` to a number higher than 1. For instance, `vid_stride=3` would process every third frame, effectively reducing the frame rate to one third of the original stream.

Remember that skipping frames can affect the tracking accuracy since temporal information between frames is valuable for maintaining consistent track identities.

Happy tracking! 😊🚀

**Comment by VM8198** [comment]
Thanks @glenn-jocher. I have one more question. While using list.streams the tracking id I'm getting are global. That means the tracking ids are shared across 2 streams. So, if tracking id 1 is assigned to stream 1 tracking id 2 will be assigned to stream 2. So, the 1st stream will get tracking id 3 next time. So, is there any way to give the tracking ids stream wise? My goal is to assign stream wise tracking id. So the output of stream 1 will be 1-10 and for stream to also it will be 1-10.

**Comment by glenn-jocher** [comment]
@VM8198 you're welcome! Happy to help. If you have any more questions, feel free to ask. Good luck with your project! 😊👍

**Comment by VM8198** [comment]
@glenn-jocher I'm facing issues with tracking id's when tracking is used with list.streams. The tracking ids are not  permanent. For example, if 2 streams are given in list.streams and ```model.track``` is applied with ```persist=True``` for each frame of both videos same objects are being assigned different ids. So, I'm not able to handle the tracking functionality which I need.

P.S. If I run single stream with same codebase tracking ids are permanent.

Please let me know if this is the default behaviour or I'm  making any mistakes?

**Comment by VM8198** [comment]
That's so sad :( @glenn-jocher. Can you tell me how list.stream executes?

**Comment by VM8198** [comment]
Thanks @glenn-jocher for your inputs. I think I can use the below approach listed on Ultralytics docs. Please let me know your thoughts..

```python
import threading
import cv2
from ultralytics import YOLO


def run_tracker_in_thread(filename, model, file_index):
    """
    Runs a video file or webcam stream concurrently with the YOLOv8 model using threading.

    This function captures video frames from a given file or camera source and utilizes the YOLOv8 model for object
    tracking. The function runs in its own thread for concurrent processing.

    Args:
        filename (str): The path to the video file or the identifier for the webcam/external camera source.
        model (obj): The YOLOv8 model object.
        file_index (int): An index to uniquely identify the file being processed, used for display purposes.

    Note:
        Press 'q' to quit the video display window.
    """
    video = cv2.VideoCapture(filename)  # Read the video file

    while True:
        ret, frame = video.read()  # Read the video frames

        # Exit the loop if no more frames in either video
        if not ret:
            break

        # Track objects in frames if available
        results = model.track(frame, persist=True)
        res_plotted = results[0].plot()
        cv2.imshow(f"Tracking_Stream_{file_index}", res_plotted)

        key = cv2.waitKey(1)
        if key == ord('q'):
            break

    # Release video sources
    video.release()


# Load the models
model1 = YOLO('yolov8n.pt')
model2 = YOLO('yolov8n-seg.pt')

# Define the video files for the trackers
video_file1 = "path/to/video1.mp4"  # Path to video file, 0 for webcam
video_file2 = 0  # Path to video file, 0 for webcam, 1 for external camera

# Create the tracker threads
tracker_thread1 = threading.Thread(target=run_tracker_in_thread, args=(video_file1, model1, 1), daemon=True)
tracker_thread2 = threading.Thread(target=run_tracker_in_thread, args=(video_file2, model2, 2), daemon=True)

# Start the tracker threads
tracker_thread1.start()
tracker_thread2.start()

# Wait for the tracker threads to finish
tracker_thread1.join()
tracker_thread2.join()

# Clean up and close windows
cv2.destroyAllWindows()
```

Thanks.

**Comment by glenn-jocher** [comment]
@VM8198 the threading approach you've outlined seems like a solid strategy for running multiple independent tracking instances concurrently. This will allow you to handle each stream separately while keeping the application responsive.

Regarding consistent IDs across streams, utilizing a method like DeepSORT could potentially help, but you're correct that it requires embeddings. While YOLOv8 does not directly provide embeddings, you might extract features using an additional network or custom layers if you're familiar with model modification and have the resources to handle the extra computational load.

Keep in mind that synchronizing IDs across different threads or streams would require careful cross-referencing logic and potentially a centralized tracking management system. It's an advanced task, but with some creative engineering, it should be possible. Good luck!

**Comment by VM8198** [comment]
Thanks for the information @glenn-jocher

**Comment by glenn-jocher** [comment]
You're welcome @VM8198! If you need further assistance, feel free to reach out. 😊👍
