### ISSUE TITLE
AttributeError: 'Annotator' object has no attribute 'draw'

### ISSUE THREAD

**Issue by Akshayvasav** [ultralytics/ultralytics#6813]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

 File "C:\Users\<username>\.conda\envs\yolov8\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\<username>\.conda\envs\yolov8\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\<username>\.conda\envs\yolov8\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\<username>\.conda\envs\yolov8\lib\site-packages\ultralytics\cfg\__init__.py", line 448, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "C:\Users\<username>\.conda\envs\yolov8\lib\site-packages\ultralytics\engine\model.py", line 239, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "C:\Users\<username>\.conda\envs\yolov8\lib\site-packages\ultralytics\engine\predictor.py", line 207, in predict_cli
    for _ in gen:  # running CLI inference without accumulating any outputs (do not modify)
  File "C:\Users\<username>\.conda\envs\yolov8\lib\site-packages\torch\autograd\grad_mode.py", line 44, in generator_context
    response = gen.send(None)
  File "C:\Users\<username>\.conda\envs\yolov8\lib\site-packages\ultralytics\engine\predictor.py", line 284, in stream_inference
    s += self.write_results(i, self.results, (p, im, im0))
  File "C:\Users\<username>\.conda\envs\yolov8\lib\site-packages\ultralytics\engine\predictor.py", line 178, in write_results
    self.plotted_img = result.plot(**plot_args)
  File "C:\Users\<username>\.conda\envs\yolov8\lib\site-packages\ultralytics\engine\results.py", line 248, in plot
    annotator.box_label(d.xyxy.squeeze(), label, color=colors(c, True))
  File "C:\Users\<username>\.conda\envs\yolov8\lib\site-packages\ultralytics\utils\plotting.py", line 109, in box_label
    self.draw.rectangle(box, width=self.lw, outline=color)  # box
AttributeError: 'Annotator' object has no attribute 'draw'

### Environment

                                                                 yolo checks
Ultralytics YOLOv8.0.219 🚀 Python-3.8.18 torch-1.8.0+cpu CPU (11th Gen Intel Core(TM) i5-1145G7 2.60GHz)
Setup complete ✅ (8 CPUs, 15.7 GB RAM, 219.6/237.2 GB disk)

OS                  Windows-10-10.0.22621-SP0
Environment         Windows
Python              3.8.18
Install             pip
RAM                 15.69 GB
CPU                 11th Gen Intel Core(TM) i5-1145G7 2.60GHz
CUDA                None

matplotlib          ✅ 3.7.0>=3.3.0
numpy               ✅ 1.24.4>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 1.8.0>=1.8.0
torchvision         ✅ 0.9.0>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

yolo detect predict model=<custom_model_path> source="<folder path>"

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
@Akshayvasav, appreciate the detailed information you provided. I'm unable to replicate the issue you encountered. I executed the mentioned command for processing:

```bash
yolo detect predict model=yolov8n.pt source=ultralytics.mp4 show=True
```

### Results
```
Ultralytics YOLOv8.0.222 🚀 Python-3.9.13 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3050, 8192MiB)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

video 1/1 (1/246) ultralytics.mp4: 384x640 2 persons, 171.9ms
video 1/1 (2/246) ultralytics.mp4: 384x640 2 persons, 15.6ms
video 1/1 (3/246) ultralytics.mp4: 384x640 2 persons, 15.6ms
video 1/1 (4/246) ultralytics.mp4: 384x640 2 persons, 16.0ms
video 1/1 (5/246) ultralytics.mp4: 384x640 2 persons, 15.6ms
video 1/1 (6/246) ultralytics.mp4: 384x640 2 persons, 15.6ms
```

Thanks
Ultralytics Team!

**Comment by glenn-jocher** [comment]
@Akshayvasav hello! It's possible that the error might be associated with high-resolution images causing a unique issue within the drawing function. Although it's not typical, one potential solution could be to resize the high-resolution images before passing them through YOLOv8's prediction function to see if that resolves the problem. Lower-resolution images working correctly suggests that this might be linked to how the drawing function handles image size or memory.

For additional help, you could check our documentation on Predict mode and ensure your environment meets all the necessary requirements. If this doesn't solve the issue, the community might benefit from discussing it further on our issues page, allowing our team to investigate.

Thanks for supporting YOLOv8, and keep up the great work! 🚀
