### ISSUE TITLE
RAM Optimization during Inference on high resolution images such as 8000 * 8000 pixel 

### ISSUE THREAD

**Issue by aymanaboghonim** [ultralytics/ultralytics#6814]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to inquire about optimizing RAM usage for the YOLO model. Should I open a new issue or initiate a discussion? I am keen on running inference on high-resolution images, such as 8096 x 8096 (equivalent to 96 images of size 512 x 512). This approach can help reduce the occurrence of repeated objects on the image margins but running inference on 4k images requires about 0.6 GB RAM, so I am seeking for possible ways to reduce RAM usage.
I tried using buffer stream but it can not save more RAM .
![image](https://github.com/ultralytics/ultralytics/assets/62246708/94949d07-8ae8-4942-a0e0-4f6760f5c964)

here is the code that I used for inference 
`yolo predict task=segment model=./best_27_11_2023.pt device=cpu source=sample_malqa512 imgsz=8096`

### Additional

Environment:

```
/opt/conda/envs/yolo/lib/python3.8/site-packages/torch/cuda/init.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11060). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org/ to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
return torch._C._cuda_getDeviceCount() > 0
Ultralytics YOLOv8.0.221 🚀 Python-3.8.17 torch-2.1.1+cu121 CPU (Intel Xeon 2.30GHz)
Setup complete ✅ (96  CPUs, 640 GB RAM, 261.1/4921.3 GB disk)

OS Linux-4.19.0-25-cloud-amd64-x86_64-with-glibc2.10
Environment Linux
Python 3.8.17
Install pip
RAM 640 GB
CPU Intel Xeon 2.30GHz
CUDA None

matplotlib ✅ 3.7.4>=3.3.0
numpy ✅ 1.24.4>=1.22.2
opencv-python ✅ 4.8.1.78>=4.6.0
pillow ✅ 10.1.0>=7.1.2
pyyaml ✅ 6.0.1>=5.3.1
requests ✅ 2.31.0>=2.23.0
scipy ✅ 1.10.1>=1.4.1
torch ✅ 2.1.1>=1.8.0
torchvision ✅ 0.16.1>=0.9.0
tqdm ✅ 4.66.1>=4.64.0
pandas ✅ 2.0.3>=1.1.4
seaborn ✅ 0.13.0>=0.11.0
psutil ✅ 5.9.5
py-cpuinfo ✅ 9.0.0
thop ✅ 0.1.1-2209072238>=0.1.1 
```

**Comment by glenn-jocher** [comment]
@aymanaboghonim hi! Thanks for bringing up RAM optimization during high-resolution image inference using YOLOv8. To address RAM usage effectively, consider the following steps:

1. **Resize Images**: If the fine details are not crucial, downsizing your images before inference can decrease memory consumption significantly.
2. **Batch Processing**: Splitting the image into smaller crops and processing them in batches can also manage RAM usage. Be mindful of context loss around edges if objects lie on boundaries.
3. **Tiling**: Consider a tiling approach with overlap to reduce edge artifacts. Implement a mechanism to merge detection from adjacent tiles.
4. **Model Pruning**: Pruning the model to reduce its size and complexity may also alleviate RAM usage, though it may affect accuracy.
5. **Optimize Precision**: Using lower precision like FP16 or INT8 during inference can reduce RAM usage without a substantial loss in performance.

If you have code-specific optimization questions or discussions about best practices, initiating a discussion would be appropriate. For performance issues that seem like bugs or enhancements, opening an issue could be the right path.

For more in-depth guides and model-specific advice, please refer to the Ultralytics Docs.

Keep exploring! Your contributions help improve YOLOv8 for everyone 🚀.

**Comment by aymanaboghonim** [comment]
> @aymanaboghonim hi! Thanks for bringing up RAM optimization during high-resolution image inference using YOLOv8. To address RAM usage effectively, consider the following steps:
Hi @glenn-jocher Thanks for your prompt answer and support.

> 
> 1. **Resize Images**: If the fine details are not crucial, downsizing your images before inference can decrease memory consumption significantly.
> 2. **Batch Processing**: Splitting the image into smaller crops and processing them in batches can also manage RAM usage. Be mindful of context loss around edges if objects lie on boundaries.
I am using this model to segment building from satellite images so I care about fine details and objects (buildings)  may lie in edges so resizing and batch processing won't be suitable in my use-case.
> 3. **Tiling**: Consider a tiling approach with overlap to reduce edge artifacts. Implement a mechanism to merge detection from adjacent tiles.
Regarding tiling approach, I have used "SAHI" as the docs recommended but the inference quality was degraded and I suffer from high RAM consumption when I tried with 4 k images.

> 4. **Model Pruning**: Pruning the model to reduce its size and complexity may also alleviate RAM usage, though it may affect accuracy.
> 5. **Optimize Precision**: Using lower precision like FP16 or INT8 during inference can reduce RAM usage without a substantial loss in performance.
I care about accuracy more than resources so I think neither pruning nor using lower precision model weight will be suitable here.
> 
> If you have code-specific optimization questions or discussions about best practices, initiating a discussion would be appropriate. For performance issues that seem like bugs or enhancements, opening an issue could be the right path.
> 
I am asking a general question about RAM optimization while preserving the same accuracy performance.
> For more in-depth guides and model-specific advice, please refer to the Ultralytics Docs.
I read the docs and only thing that I could leverage regrading RAM consumption was using `stream buffer = True`
I appreciate your time and consideration and seeking more possible ways that can optimize RAM without any side-effect on accuracy performance .
> Keep exploring! Your contributions help improve YOLOv8 for everyone 🚀.
