### ISSUE TITLE
Classification Task not accepting dataset YAML

### ISSUE THREAD

**Issue by JCab09** [ultralytics/ultralytics#6818]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

`Traceback (most recent call last):
  File "/opt/conda/bin/ultralytics", line 33, in <module>
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'ultralytics')())
  File "/usr/src/ultralytics/ultralytics/cfg/__init__.py", line 448, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/src/ultralytics/ultralytics/engine/model.py", line 333, in train
    self.trainer = (trainer or self._smart_load('trainer'))(overrides=args, _callbacks=self.callbacks)
  File "/usr/src/ultralytics/ultralytics/models/yolo/classify/train.py", line 39, in __init__
    super().__init__(cfg, overrides, _callbacks)
  File "/usr/src/ultralytics/ultralytics/engine/trainer.py", line 120, in __init__
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
RuntimeError: Dataset '/srv/data/_data/a371d697d6e2d80f7dcc4b90e85bf4d36c8d4f1b06a7fce6ea9fc062c6c4b560/classification_dl/data_00/data.yaml' error ❌ ❌  Download failure for https://github.com/ultralytics/yolov5/releases/download/v1.0//srv/data/_data/a371d697d6e2d80f7dcc4b90e85bf4d36c8d4f1b06a7fce6ea9fc062c6c4b560/classification_dl/data_00/data.yaml.zip. Environment is not online.`

### Environment

Ultralytics YOLOv8.0.220 🚀 Python-3.10.13 torch-2.1.0 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)
Setup complete ✅ (12 CPUs, 37.6 GB RAM, 76.4/251.0 GB disk)

OS                  Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31
Environment         Docker
Python              3.10.13
Install             git
RAM                 37.58 GB
CPU                 AMD Ryzen 5 3600X 6-Core Processor
CUDA                12.1

matplotlib          ✅ 3.8.2>=3.3.0
numpy               ✅ 1.23.5>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.0.1>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 2.1.0>=1.8.0
torchvision         ✅ 0.16.0>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
pandas              ✅ 2.1.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

Create a dataset.yaml and pass it as the value for the `data` argument with `task=classify` and `mode=train`.

My subprocess args for executing the script inside my yolov8 container:
`'docker', 'exec', 'yolov8', 'ultralytics', 'task=classify', 'mode=train', 'model=yolov8m-cls.pt', 'data=/srv/data/_data/a371d697d6e2d80f7dcc4b90e85bf4d36c8d4f1b06a7fce6ea9fc062c6c4b560/classification_dl/data_00/dataset.yaml'`

My dataset.yaml:
```yaml
path: /srv/data/_data/a371d697d6e2d80f7dcc4b90e85bf4d36c8d4f1b06a7fce6ea9fc062c6c4b560/classification_dl/data_00
train: train/images
val: val/images
test: test/images

nc: 2
names: ['IO', 'NIO']
```

### Additional

Using the same schema for detection tasks works.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by giuseppebif3** [comment]
following

**Comment by JCab09** [comment]
Closing this issue as it is now a feature request.

**Comment by glenn-jocher** [comment]
@JCab09 issue #6874 closed as it has transitioned to a feature request. 🚀 Thank you for your contribution!
