### ISSUE TITLE
How to use the camera from the app enersight as a source

### ISSUE THREAD

**Issue by shahbazahmed108** [ultralytics/ultralytics#6821]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello All,

## i am running the yolov8 on windows cmd## i am not a computer expert, i just followed a tutorial
I have an app installed on my laptop called Enersight, this app connects with the microscope and shows me the video of my objects under microscope. Since the video in this app is not from webcam i am not able to use the source=0. If i go to manage camera settings in my windows laptop, the two camera that it shows as connected are my webcame and the second one is ivesta 3 (integrated camera). ivesta 3 is microscope name. i tried using the source=1 but it gives an error of failed to read images from 1. could you all please help me how to use this integrated camera in an app as a source to run detection on with yolov8. thank you for reading and helping

### Additional

<img width="863" alt="Screenshot 2023-12-06 084734" src="https://github.com/ultralytics/ultralytics/assets/57543325/895e11bc-b28e-4b11-aa23-a2640ffbf040">

**Comment by glenn-jocher** [comment]
@shahbazahmed108 hello!

To use the microscope camera with YOLOv8, you’ll need to ensure that the camera is accessible to your system as a standard video input. If your microscope camera appears as a standard camera source (like a webcam), you should be able to reference it by its index, as you've tried with `source=1`. If that's not working, it suggests that the camera may not be accessible in the same way as a webcam.

It's possible that the Enersight app is exclusively accessing the camera, preventing other applications from using it simultaneously. You can try closing the Enersight app to see if that frees up the camera for other uses. Additionally, you could explore whether Enersight or your microscope manufacturer offers any software tools or APIs to integrate with third-party applications.

If your camera simply can't be accessed as a typical webcam, a workaround could be to capture the output from the Enersight app using screen capture software and then input that data into YOLOv8. But, as this type of integration can be complex, professional assistance might be advisable if you’re not comfortable with such technical tasks.

For detailed instructions on setting up different data sources with the YOLOv8 model and for further assistance on various modes and tasks, please reference our documentation at https://docs.ultralytics.com. 😊

Good luck with your project!

**Comment by shahbazahmed108** [comment]
Thank you glenn for all the input. i can capture the video my objects using enersight app and feed that to yolo just fine. it is just that i wanted to do live detection for one of my project.

**Comment by glenn-jocher** [comment]
@shahbazahmed108, delighted to hear that you're able to capture video for analysis with YOLOv8!

For live detection, you may need to check if the Enersight app can output a live video feed in a format that can be recognized by YOLOv8, such as an RTSP or HTTP stream. If so, you can then set this stream as your `source`. Otherwise, consider contacting the app's support team to inquire about the possibility of accessing the live feed programmatically or through some form of integration. Unfortunately, without direct compatibility, YOLOv8 requires a standard video stream to process live data.

Keep exploring and best of luck with your live detection project! 😄🔬

**Comment by shahbazahmed108** [comment]
@glenn-jocher since i have you here. may i ask you another question. is there a way to save the results of number of images detected as a file in my directory? basically I want it to count the number of objects it detected in an image and save that information in the directory on computer?

**Comment by glenn-jocher** [comment]
@shahbazahmed108, absolutely! After running predictions on your images with YOLOv8, the results, including detection counts, are compiled into a `.json` file by default. This file will be saved within your runs directory, listing detection counts among other details for each image processed. You can then use this file to further analyze the detection statistics or integrate the results into your project. Happy object counting! 😊📊

**Comment by shahbazahmed108** [comment]
is there a command for it? i am using in CLI

yolo task=detect mode=predict model=best.pt show=True conf=0.5 source=test.jpeg

it only saves a folder name predict where my image is stored with bounding boxes around the objects. i don't get any .json files or other files. sorry for bothering you with all these questions
Shahbaz

**Comment by glenn-jocher** [comment]
@shahbazahmed108, no worries at all – happy to help! When you use the detect command, you can enable the saving of results to a `.json` file by adding `--save-json` to your command. This will create a `labels` folder within the `runs/detect/exp*` directory containing `.json` files with your detection results, including object counts for each image. Keep exploring, and don't hesitate to reach out if you have more questions! 😃👍

**Comment by shahbazahmed108** [comment]
@glenn-jocher I tried the argument but it gave an error, my command in cli was
yolo task=detect mode=predict model=best.pt show=True conf=0.5 source=test.jpeg --save-json

first warning was  WARNING ⚠️ '--save-json' does not require leading dashes '--', updating to 'save-json'.
it then followed up by 

SyntaxError: 'save-json' is not a valid YOLO argument. Similar arguments are i.e. ['save_json=False', 'save_conf=False', 'version=<function entrypoint.<locals>.<lambda> at 0x000001F9759E0670>'].

i then tried 'save_json=False and 'save_json=True, code runs but doesn't save anything in prediction folder.

**Comment by glenn-jocher** [comment]
@shahbazahmed108, apologies for the confusion. To save your detection results to JSON, please use the argument `save-json`. Correct your command to include only `save-json` without the leading dashes or boolean assignment:

`yolo task=detect mode=predict model=best.pt show=True conf=0.5 source=test.jpeg save-json`

This will save the detection counts and other details in a `.json` file within the resulting run directory. Thank you for your patience! 😊👨‍💻

**Comment by shahbazahmed108** [comment]
@glenn-jocher there is still an error with save-json



SyntaxError: 'save-json' is not a valid YOLO argument. Similar arguments are i.e. ['save_json=False', 'save_conf=False', 'version=<function entrypoint.<locals>.<lambda> at 0x000001DF02510670>'].


(yolov8_custom) C:\Users\Shahbaz\Desktop\leica>yolo task=detect mode=predict model=best.pt show=True conf=0.5 source= test.jpeg save-json
Traceback (most recent call last):
  File "C:\Users\Shahbaz\anaconda3\envs\yolov8_cusom\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Shahbaz\anaconda3\envs\yolov8_cusom\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Shahbaz\anaconda3\envs\yolov8_cusom\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\Shahbaz\anaconda3\envs\yolov8_cusom\lib\site-packages\ultralytics\cfg\__init__.py", line 384, in entrypoint
    check_dict_alignment(full_args_dict, {a: ''})
  File "C:\Users\Shahbaz\anaconda3\envs\yolov8_cusom\lib\site-packages\ultralytics\cfg\__init__.py", line 205, in check_dict_alignment
    raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'save-json' is not a valid YOLO argument. Similar arguments are i.e. ['save_json=False', 'save_conf=False', 'version=<function entrypoint.<locals>.<lambda> at 0x000001FC69E10670>'].

    Arguments received: ['yolo', 'task=detect', 'mode=predict', 'model=best.pt', 'show=True', 'conf=0.5', 'source=', 'test.jpeg', 'save-json']. Ultralytics 'yolo' commands use the following syntax:

        yolo TASK MODE ARGS

        Where   TASK (optional) is one of ('detect', 'segment', 'classify', 'pose')
                MODE (required) is one of ('train', 'val', 'predict', 'export', 'track', 'benchmark')
                ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
                    See all ARGS at https://docs.ultralytics.com/usage/cfg or with 'yolo cfg'

    1. Train a detection model for 10 epochs with an initial learning_rate of 0.01
        yolo train data=coco128.yaml model=yolov8n.pt epochs=10 lr0=0.01

    2. Predict a YouTube video using a pretrained segmentation model at image size 320:
        yolo predict model=yolov8n-seg.pt source='https://youtu.be/LNwODJXcvt4' imgsz=320

    3. Val a pretrained detection model at batch-size 1 and image size 640:
        yolo val model=yolov8n.pt data=coco128.yaml batch=1 imgsz=640

    4. Export a YOLOv8n classification model to ONNX format at image size 224 by 128 (no TASK required)
        yolo export model=yolov8n-cls.pt format=onnx imgsz=224,128

    5. Run special commands:
        yolo help
        yolo checks
        yolo version
        yolo settings
        yolo copy-cfg
        yolo cfg

    Docs: https://docs.ultralytics.com
    Community: https://community.ultralytics.com
    GitHub: https://github.com/ultralytics/ultralytics

**Comment by glenn-jocher** [comment]
@shahbazahmed108, it seems there is a bit of confusion. The proper argument to save detection results to a JSON file is `save_json`, not `save-json`. Your command should look like this:

`yolo task=detect mode=predict model=best.pt show=True conf=0.5 source=test.jpeg save_json`

Ensure there are no spaces around the `=` signs in the command. This will save a `*_predictions.json` file in the `runs/detect/exp*/labels` directory. Thank you for your understanding, and keep up the great work with YOLOv8! 😊👍

**Comment by shahbazahmed108** [comment]
@glenn-jocher i think i am talking to chatgpt for past couple messages. anyway like i mentioned before --save-json doesn't work, program tells me to run save-json instead. but when i run that it says save-json is not a valid YOLO argument. i then tried save_json. save_json makes the code run but it doesn't save anything in the predict folder
