### ISSUE TITLE
DetectionTrainer cfg does not contain key 'project'

### ISSUE THREAD

**Issue by guishilike** [ultralytics/ultralytics#684]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Traceback (most recent call last):
  File "H:/github/ultralytics/ultralytics/yolo/v8/detect/train.py", line 217, in <module>
    train()
  File "H:/github/ultralytics/ultralytics/yolo/v8/detect/train.py", line 212, in train
    trainer = DetectionTrainer(args)
  File "H:\github\ultralytics\ultralytics\yolo\engine\trainer.py", line 82, in __init__
    self.args = get_cfg(cfg, overrides)
  File "H:\github\ultralytics\ultralytics\yolo\cfg\__init__.py", line 93, in get_cfg
    if isinstance(cfg[k], (int, float)):
KeyError: 'project'

### Minimal Reproducible Example

Thera is a command to reproduce.
```
python ultralytics/yolo/v8/detect/train.py model=yolov8s.yaml data=coco128.yaml epochs=50 imgsz=640 batch=2
```
Error at this
```
# Type checks
for k in 'project', 'name':
    if isinstance(cfg[k], (int, float)):
        cfg[k] = str(cfg[k])
```

The dict args only  contains three key values(mode, data, device).
```
def train(cfg=DEFAULT_CFG, use_python=False):
    model = cfg.model or "yolov8n.pt"
    data = cfg.data or "coco128.yaml"  # or yolo.ClassificationDataset("mnist")
    device = cfg.device if cfg.device is not None else ''

    args = dict(model=model, data=data, device=device)
    if use_python:
        from ultralytics import YOLO
        YOLO(model).train(**args)
    else:
        trainer = DetectionTrainer(args)
        trainer.train()
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@guishilike hi the same command works fine to me, can you try it again with the latest package version?
![pic-full-230130-1047-27](https://user-images.githubusercontent.com/61612323/215376959-0bcc98c7-7a98-4f30-810a-ce0eb5758132.png)

**Comment by guishilike** [comment]
```
if use_python:
    from ultralytics import YOLO
    YOLO(model).train(**args)
else:
    trainer = DetectionTrainer(overrides=args)
    trainer.train()
```
It works fine when set overrides=args.

**Comment by pderrenger** [comment]
@guishilike great to hear that using `overrides=args` resolved the issue for you! This approach allows for the correct initialization of the `DetectionTrainer`. If you encounter any further challenges or have additional questions, feel free to ask!
