### ISSUE TITLE
yolov8 ray tuner network problem

### ISSUE THREAD

**Issue by unrue** [ultralytics/ultralytics#6842]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm using ray to tune yolov8 model, on HPC cluster which nodes does not have internet connections. I get:

```
`from ultralytics import YOLO

model = YOLO('models/yolov8x.pt')

result_grid = model.tune(data='***/Deep_Learning/MIC_DL/detectron2_alternative/yolov5_env/yolov5/datasets/new_dataset_yolov5/data.yaml', use_ray=True)
`

`WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x1508a6bfb430>: Failed to establish a new connection: [Errno 101] La rete non è raggiungibile')': /simple/protobuf/
f0>: Failed to establish a new connection: [Errno 101] La rete non è raggiungibile')': /simple/ray/
ERROR: Cannot install ray[tune]==2.8.1 and tensorboardx==2.6.2.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    ray[tune] 2.8.1 depends on protobuf!=3.19.5 and >=3.15.3
    tensorboardx 2.6.2.2 depends on protobuf>=3.20

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

`
```

I already successfully iinstalled ray. Why It attempt to make further download? How can I disable such behaviour?

And another little question: How do I resume a ray tuning? Thanks.

**Comment by glenn-jocher** [comment]
@unrue hello! When using Ray to tune YOLOv8 models within an environment without an internet connection, such as an HPC cluster, it's crucial to have all the necessary dependencies pre-installed in your environment since Ray can attempt to download dependencies required for different trials. 

Your error suggests a conflict between the required `protobuf` versions for `ray[tune]` and `tensorboardx`. To resolve this, make sure you manually align the versions by installing compatible versions beforehand. You might want to look into using a virtual environment where you can control the exact versions of the installed packages.

Concerning resuming Ray tuning, you should be able to resume from the last checkpoint as long as the checkpoints were properly saved before the interruption. Check the Ray documentation or directives for information on checkpointing and resuming tuning sessions, which often involves specifying the path to the saved checkpoints.

For further details on these processes, consider referring to our documentation for advanced usage and troubleshooting, and for Ray-specific instructions, their documentation would be the best guide. 😊📘

**Comment by unrue** [comment]
I installed as the manual suggest: 

`pip install -U ultralytics "ray[tune]"`

Thanls for the suggest:

> @unrue hello! When using Ray to tune YOLOv8 models within an environment without an internet connection, such as an HPC cluster, it's crucial to have all the necessary dependencies pre-installed in your environment since Ray can attempt to download dependencies required for different trials.
> 
> Your error suggests a conflict between the required `protobuf` versions for `ray[tune]` and `tensorboardx`. To resolve this, make sure you manually align the versions by installing compatible versions beforehand. You might want to look into using a virtual environment where you can control the exact versions of the installed packages.
> 
> Concerning resuming Ray tuning, you should be able to resume from the last checkpoint as long as the checkpoints were properly saved before the interruption. Check the Ray documentation or directives for information on checkpointing and resuming tuning sessions, which often involves specifying the path to the saved checkpoints.
> 
> For further details on these processes, consider referring to our documentation for advanced usage and troubleshooting, and for Ray-specific instructions, their documentation would be the best guide. 😊📘

Thanks Glenn, I'll check the dependencies.

**Comment by glenn-jocher** [comment]
@unrue you're welcome! Yes, checking and manually aligning the dependencies should do the trick. Make sure that all packages are compatible with each other in your offline environment. If issues persist, consider using a virtual environment where you can have a clean state to manage your packages more effectively. For resuming Ray tuning, indeed, proper checkpointing is key. Dive into Ray's checkpointing documentation, and you should be able to pick up tuning from where you left off. Good luck! 🚀

**Comment by unrue** [comment]
Hi glenn, 

thansk to your suggestions now Ray tune run but just for few minutes. I see:

```

Trial status: 4 RUNNING | 6 PENDING
Current time: 2024-01-11 11:09:08. Total running time: 3min 30s
Logical resource usage: 3**2.0/32 CPUs, 0/4 GPUs** (0.0/1.0 accelerator_type:PG506)
```

I suppose is doing a lot of test changing tuning parameters. The thing unknown is, why is using 32 CPUs and not GPus?  I have to set something? After some minutes I get the following error:

`ImportError: The pyarrow installation is not built with support for 'S3FileSystem'`

Why S3 system is involved? Can I avoid such error in some manner? Thanks.

**Comment by glenn-jocher** [comment]
Hi @unrue,

Great to hear that Ray tune is now running! Regarding the CPU usage, Ray will default to using CPUs if GPUs are not specified or if the necessary GPU support is not configured. To ensure Ray uses GPUs, you need to set the appropriate GPU resources in your Ray tune configuration.

The `S3FileSystem` error is likely due to Ray attempting to access remote resources or checkpoints. If your environment doesn't require S3, you can avoid this by ensuring your data and checkpoints are stored locally and your configuration does not reference S3 paths.

Keep an eye on the simulation; if it's still running, it may be proceeding with local resources despite the error. For more detailed guidance, please refer to our documentation and Ray's documentation on resource allocation and handling of file systems. 📚👍

**Comment by unrue** [comment]
Thanks Glenn,

I'm reading the following example:

[https://docs.ray.io/en/latest/tune/tutorials/tune-resources.html](url)

And the example reported:

`# If you have 8 GPUs, this will run 8 trials at once.
trainable_with_gpu = tune.with_resources(trainable, {"gpu": 1})
tuner = tune.Tuner(
    trainable_with_gpu,
    tune_config=tune.TuneConfig(num_samples=10)
)
results = tuner.fit()`

At the moment, I tune as:
```

model = YOLO('models/yolov8x.pt')
result_grid = model.tune(data='dataset.yaml', use_ray=True)

I don't understand how to merge two snippets. Where I have to pass the yaml file? The MNIST example creates itself a dataloader. In this case I have to do the same or there is some way to pass just the yaml ? Thanks.
```

**Comment by glenn-jocher** [comment]
Hi @unrue,

To utilize GPUs during tuning with YOLOv8 and Ray, you don't need to merge the snippets directly. Instead, you can specify the GPU resources in the `tune()` method of the YOLOv8 model. The `data` parameter for your dataset YAML should remain as is. Here's a simplified example:

```python
model = YOLO('models/yolov8x.pt')
result_grid = model.tune(data='dataset.yaml', use_ray=True, resources_per_trial={"gpu": 1})
```

This will allocate one GPU per trial if available. The dataset YAML file will be automatically used by the YOLOv8 model to create the necessary data loaders.

Regarding resuming tuning, Ray typically handles this internally by saving and loading checkpoints. Ensure that Ray's checkpointing is correctly set up, and refer to Ray's documentation for the exact steps to resume a tuning session.

I hope this helps clarify your queries! 🌟

**Comment by unrue** [comment]
Hi Glenn,

I get:


`SyntaxError: 'resources_per_trial' is not a valid YOLO argument.
`
I'm using ray 2.9.0 and ultralytics 8.1.0. I need more updated version?

**Comment by glenn-jocher** [comment]
Hi @unrue,

The `resources_per_trial` argument is not directly used in the YOLOv8 `tune()` method. Instead, you should ensure that your Ray environment is set up to recognize and utilize available GPUs. Please check your Ray setup and ensure it's configured to use GPUs.

For the `ValueError` you're encountering, it seems Ray is trying to resume from a previous state but can't find the checkpoint files. If you want to start a fresh tuning session, you can clear out the previous `tune*` directories or specify a new unique directory for the current tuning session to avoid conflicts with past runs.

Make sure you're using the latest versions of both Ray and Ultralytics YOLOv8, as updates may contain important fixes and improvements. If issues persist, consult the Ray documentation for handling resources and checkpoints.

**Comment by unrue** [comment]
I Glenn,

I'm a bit confused. So, _resurces_per_trial_ argument should not be used? I'm using Raytune latest version (2.9.0). How can I check if Raytune is configured to use GPU? I just installed following the instructions. I need to add some configurations?

**Comment by glenn-jocher** [comment]
Hi @unrue,

The `resources_per_trial` argument is specific to Ray Tune and not directly used in the YOLOv8 `tune()` method. To ensure Ray is configured to use GPUs, you can set the `num_gpus` argument in your Ray Tune configuration. When installing Ray, no additional GPU configuration is typically needed, but you should ensure your machine's CUDA drivers are properly installed and recognized by Ray.

For a fresh tuning session, you can specify a new directory for the results to avoid conflicts with previous runs. If you're still facing issues, please refer to the Ray documentation for detailed instructions on configuring Ray for GPU usage. 🖥️🔧

**Comment by scm-aiml** [comment]
https://docs.ultralytics.com/integrations/ray-tune/#tune-method-parameters

**Comment by glenn-jocher** [comment]
@scm-aiml apologies for the confusion earlier. The `tune()` method in YOLOv8 does not use the `resources_per_trial` argument. For GPU configuration and other parameters, please refer to our documentation on Ray Tune integration, specifically the section on Tune method parameters. This will guide you on how to properly set up your tuning session with the necessary resources. 📖👍
