### ISSUE TITLE
Bugs in Tracking 

### ISSUE THREAD

**Issue by Yang-202104** [ultralytics/ultralytics#6845]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I was using YOLOv8 old version (8.0.119) to inference my trained model before with tracking. It worked fine. But with updating the new version (8.0.223) today, there is a bug during the tracking with same trained model. Like when using botsort tracker, it always output id=1or 2 for all detected objects. There is no more new id to the different objects. I an wondering maybe there is something wrong with newest version? 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Yang-202104 hello! Thank you for bringing this to our attention. It's possible there may have been changes between version 8.0.119 and 8.0.223 that are affecting the tracking functionality. Could you please ensure you're following the [Track mode guidelines](https://docs.ultralytics.com/modes/track) from our documentation? If the issue persists, we would appreciate if you could open a new issue detailing the unexpected behavior with the latest YOLOv8 version.

If you could include specifics such as any error messages, a description of the expected versus actual behavior, and the command you used to run the tracker, it would greatly assist us in identifying and resolving the issue. We value your contribution to improving YOLOv8! 🚀

**Comment by glenn-jocher** [comment]
@RizwanMunawar could you try to reproduce this?

**Comment by glenn-jocher** [comment]
@Yang-202104 I'm able to reproduce:

- 8.0.222 good
- 8.0.223 bad

**Comment by glenn-jocher** [comment]
@Yang-202104 @RizwanMunawar fixed in 8.0.225 now! Thanks for reporting the bug and let us know if you have any other issues. Happy tracking!

**Comment by RizwanMunawar** [comment]
@glenn-jocher @Yang-202104 I've encountered this issue using `ultralytics=8.0.223`. After conducting tests with both `ultralytics=8.0.222` and the **latest version** `ultralytics=8.0.225`, I found that object tracking is functioning correctly with the latter. I've included visual samples for each pip version below:

### Ultralytics (8.0.222) [Working Properly]
![Screenshot 2023-12-08 105139](https://github.com/ultralytics/ultralytics/assets/62513924/110f4c9b-9028-454e-b6bf-0da6f74b23f2)

### Ultralytics (8.0.225) [Working Properly]
![Screenshot 2023-12-08 105104](https://github.com/ultralytics/ultralytics/assets/62513924/3a0e7334-46b9-4178-847e-1561901e218e)

@Yang-202104, could you please try uninstalling the Ultralytics package and then reinstalling it? You can use the following commands:

- `pip uninstall ultralytics`
- `pip install ultralytics`

I hope this will resolves the issue. Feel free to reach out if you have any further questions.

Thanks,
Ultralytics Team!

**Comment by Yang-202104** [comment]
@RizwanMunawar @glenn-jocher  Thanks for your kind help! I fixed the problems on my side. Now, everything goes well ! I really appreciate your quick response and support.

**Comment by RizwanMunawar** [comment]
@Yang-202104, we're pleased to assist you! Don't hesitate to ask if you have additional questions.

I am closing this issue now, reopen it If the issue persists.

Best regards,
The Ultralytics Team!
