### ISSUE TITLE
What would be the problem if I load the PT model and directly use ['model '] to export ONNX myself

### ISSUE THREAD

**Issue by jungyin** [ultralytics/ultralytics#6852]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to convert my model to an onnx model and then convert it to another model to run on edge devices, but recently I found that my export method is a bit problematic. The official recommendation is to use the export method, but I am using YOLO() ['model '] and then using the traditional pytorch method to export to an onnx model. Is this acceptable?

### Additional

my code:

dataroot = "./data/"
modelpath = os.path.join(dataroot, "yolov8n-pose.pt")
net = torch.load(modelpath)['model']
net.eval()  # ※这个要有
net.float()
onnxpath = os.path.join(dataroot, "yolov8n_pose.onnx") # 定义onnx文件保存目录
im = torch.randn(1, 3, 640, 640).cpu() # 定义输入变量，维度重要，内容不重要

torch.onnx.export(net,
                  im,
                  onnxpath,
                  verbose=False,
                  training=torch.onnx.TrainingMode.EVAL,
                  do_constant_folding=True,
                  input_names=['images'],
                  output_names=['output'],
                  dynamic_axes=None,
                  opset_version=11)

**Comment by glenn-jocher** [comment]
@jungyin while exporting the `.pt` model to ONNX format by directly using `['model']` from the PyTorch checkpoint and then employing the traditional PyTorch method to export to ONNX may seem straightforward, this approach can be problematic. The recommended practice is to use the `export` mode provided within the Ultralytics YOLOv8 repository for a few reasons:

1. The official `export` mode handles any model-specific layers or operations that may not be standard in PyTorch, ensuring proper translation into ONNX.
2. It includes additional settings and checks that may be necessary for the model to function correctly once exported, which you might miss while doing it manually.
3. Using the provided export mode ensures compatibility with ONNX and follow-on tools or frameworks you may be using for deployment to edge devices.

By not following the official export procedure, you risk encountering issues with the resulting ONNX model, such as unsupported layers, mismatched dimensions, or improperly set export flags that can lead to operational failures on your target edge devices. To ensure the best results, I recommend referring to and using the `export` mode provided in the documentation. 📖😊
