### ISSUE TITLE
add more flexibility to class Tuner by initialize custom search space with args

### ISSUE THREAD

**Issue by kirill-ionkin** [ultralytics/ultralytics#6856]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hello, everyone, my proposal is just a little bit improve `class Tuner`: as you can see init method from repo: 
```
    def __init__(self, args=DEFAULT_CFG, _callbacks=None):
        """
        Initialize the Tuner with configurations.

        Args:
            args (dict, optional): Configuration for hyperparameter evolution.
        """
        self.args = get_cfg(overrides=args)
        self.space = {  # key: (min, max, gain(optional))
            # 'optimizer': tune.choice(['SGD', 'Adam', 'AdamW', 'NAdam', 'RAdam', 'RMSProp']),
            'lr0': (1e-5, 1e-1),
            'lrf': (0.0001, 0.1),  # final OneCycleLR learning rate (lr0 * lrf)
            'momentum': (0.7, 0.98, 0.3),  # SGD momentum/Adam beta1
            'weight_decay': (0.0, 0.001),  # optimizer weight decay 5e-4
            'warmup_epochs': (0.0, 5.0),  # warmup epochs (fractions ok)
            'warmup_momentum': (0.0, 0.95),  # warmup initial momentum
            'box': (1.0, 20.0),  # box loss gain
            'cls': (0.2, 4.0),  # cls loss gain (scale with pixels)
            'dfl': (0.4, 6.0),  # dfl loss gain
            'hsv_h': (0.0, 0.1),  # image HSV-Hue augmentation (fraction)
            'hsv_s': (0.0, 0.9),  # image HSV-Saturation augmentation (fraction)
            'hsv_v': (0.0, 0.9),  # image HSV-Value augmentation (fraction)
            'degrees': (0.0, 45.0),  # image rotation (+/- deg)
            'translate': (0.0, 0.9),  # image translation (+/- fraction)
            'scale': (0.0, 0.95),  # image scale (+/- gain)
            'shear': (0.0, 10.0),  # image shear (+/- deg)
            'perspective': (0.0, 0.001),  # image perspective (+/- fraction), range 0-0.001
            'flipud': (0.0, 1.0),  # image flip up-down (probability)
            'fliplr': (0.0, 1.0),  # image flip left-right (probability)
            'mosaic': (0.0, 1.0),  # image mixup (probability)
            'mixup': (0.0, 1.0),  # image mixup (probability)
            'copy_paste': (0.0, 1.0)}  # segment copy-paste (probability)
        self.tune_dir = get_save_dir(self.args, name='tune')
        self.tune_csv = self.tune_dir / 'tune_results.csv'
        self.callbacks = _callbacks or callbacks.get_default_callbacks()
        self.prefix = colorstr('Tuner: ')
        callbacks.add_integration_callbacks(self)
        LOGGER.info(f"{self.prefix}Initialized Tuner instance with 'tune_dir={self.tune_dir}'\n"
                    f'{self.prefix}💡 Learn about tuning at https://docs.ultralytics.com/guides/hyperparameter-tuning')
```

Init method doesn't allow users to create custom search space without manually changing source code, but i think it is easy to implement and helpful for reseachers to avoid changing source code every time, when need non default search space.

### Use case

Most common case - if someone needs to HPO, using custom Tuner. It's a little bit confused, if someone need non default serach space, or more uncomfortable, if someone reseach using jupyter-noteook - on both cases, i think, comfortable to pass dict with custom search space to Tuner class and just use it=)

### Additional

I already experiments with this idea and it works good)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kirill-ionkin thank you for your suggestion to enhance the `class Tuner` by enabling the initialization of custom search spaces through the arguments. It's great to hear that your experiments with this idea have yielded positive results, and your willingness to submit a PR is much appreciated.

Having the ability to define a custom search space without altering the source code directly would certainly be a more user-friendly approach, especially for researchers and those working within environments like Jupyter notebooks.

Your proposed change aligns with our goal of making YOLOv8 more flexible and accessible for various use cases. Please feel free to work on this enhancement and submit a PR when you're ready. Your contribution is valuable, and it's community-driven improvements like these that help advance our project.

Looking forward to reviewing your PR, and thank you for being a part of the YOLO community! 🚀

**Comment by kirill-ionkin** [comment]
Hello, @glenn-jocher , PR was created: https://github.com/ultralytics/ultralytics/pull/6882. Hope it looks good)

**Comment by glenn-jocher** [comment]
Hello @kirill-ionkin, thank you for submitting the PR. We'll review it shortly and provide feedback or merge it if everything is in order. Your contributions are appreciated! 🙌
