### ISSUE TITLE
Increase the cut-off threshold for automated batch size calculation during training

### ISSUE THREAD

**Issue by MartinKlefas** [ultralytics/ultralytics#6857]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

The Auto-batch feature during training is a very well implemented feature, and has successfully kept all of my training runs in VRAM - even when using a computer that's using it's GPU for other functions at the same time.

However, when on a dedicated ML server, I'd rather use more than 60% of VRAM and thus I've been running the auto-batch to get a guess, then doubling it before running again with that number of images instead of just using the automatic tool.

This works, but wastes 10 minutes at the start of each training run fiddling about.

My suggestion is to keep the standard behaviour when batch=-1 but add a second mode that optimistically tries to use 90% of VRAM. This would obviously be problematic for some users - which is why it shouldn't be the default - but it's better for people who have a dedicated machine and a large training task to complete.

### Use case

Training on rented or dedicated machines can be sped up and more fully automated

### Additional

I've already coded this, and will be submitting a PR momentarily.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MartinKlefas hi there,

First of all, thank you for your contributions and the positive feedback regarding the auto-batch feature! 🚀

I appreciate your initiative to improve the efficiency of resource utilization in dedicated ML environments by introducing a more aggressive VRAM usage mode. It sounds like a valuable enhancement for users with access to dedicated hardware who want to maximize their system's capabilities.

Your proposal to add an alternative mode that targets a higher percentage of VRAM while maintaining the standard behavior as default seems like a sensible way to provide more options without affecting existing workflows.

We look forward to reviewing your pull request! Please ensure your changes are well documented and tested across different scenarios for robust integration.

Your efforts to make YOLOv8 better for everyone are truly commendable. Keep up the fantastic work! 🌟
