### ISSUE TITLE
How to specify test batch size and test image size durning train?

### ISSUE THREAD

**Issue by sipie800** [ultralytics/ultralytics#686]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I have huge images in task. say 3000x3000px, so I use only batch size 6.
That's very small but OOM happens durning validating, because the testing batch size is set to 2*6 forcely.
It's not right to decrease 6 to 4 because that would hurt metrics.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by prince0310** [comment]
cheak  `ultralytics/yolo/engine/trainer.py` line no 107

**Comment by AyushExel** [comment]
@sipie800 good question! Yes right now we do force val bs to bs*2.. @glenn-jocher @Laughing-q thoughts on this?
