### ISSUE TITLE
The value of the epoch in best.pt checkpoint in DDP mode

### ISSUE THREAD

**Issue by younesslanda** [ultralytics/ultralytics#6860]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to access the best_epoch corresponding to best_fitness using a callback:

```
from ultralytics import YOLO
from ultralytics.utils import RANK
import os

def my_callback(trainer):
        if RANK in (-1, 0, 1):
            best_epoch = trainer.stopper.best_epoch
            with open(os.path.join(trainer.wdir, f'bestepoch_{best_epoch}'), 'w') as f:
                f.write(str(best_epoch))
            print('>>> my_callback >>>')

model = YOLO("yolov8n.pt") 
model.add_callback("on_train_end", my_callback)

model.train(data="coco128.yaml", epochs=3, device="0,1")
```

But the callback don't print the message nor does it save the write the file in the weight directory.

The callback works in non distributed mode.

**Comment by younesslanda** [comment]
@glenn-jocher Thank you for your response !

**Comment by glenn-jocher** [comment]
You're welcome, @younesslanda! If you have further questions or encounter any issues, feel free to reach out. Happy coding! 🚀
