### ISSUE TITLE
how to add a new class when doing transfer learning with yolov8

### ISSUE THREAD

**Issue by ycwdaaaa** [ultralytics/ultralytics#6867]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

how to add a new class when doing transfer learning with yolov8

### Additional

how to add a new class when doing transfer learning with yolov8

**Comment by glenn-jocher** [comment]
@ycwdaaaa to add a new class for transfer learning with YOLOv8, you'll need to update your dataset's annotation files to include the new class and increment the class count in your model's configuration file accordingly. The addition of a new class requires retraining the model with the updated dataset for the changes to take effect. Remember to start your training with the weights pre-trained on a similar dataset to leverage the benefits of transfer learning. For detailed steps, please consult the training documentation available on our Ultralytics Docs site under the Train mode section. Happy training! 😊🚀

**Comment by prince0310** [comment]
@ycwdaaaa You need to update your dataset and `data.yaml` file. when you will start training o previously trained weight using updated dataset you will find the precession improvement and converging time of model will be improved.
