### ISSUE TITLE
Add c++ cls inference ,follow the latest ultralytics's change, fix some bugs

### ISSUE THREAD

**Issue by DennisJcy** [ultralytics/ultralytics#6870]
Hello! I open this issue for my [PR](https://github.com/ultralytics/ultralytics/pull/6868).

Here are the changes:
1. change the class name from `DCSP`（I used to name this for detect\cls\seg\pose,which is not readable） to `YOLO_V8`.
2. add cls-inference implement and add some description in readme
3. I noted there is a transpoe op added to the model.I make the corresponding changes in cpp implement.
4. add centercrop preprocess for cls inference corresponding to the python implement 
5. Unify the naming of inconsistent variable

Wait for your suggestions and corrections.
@onuralpszr Could you please test on apple and linux? I have no such device.

# Test Log
## detect in cpu
![Detect_cpu](https://github.com/ultralytics/ultralytics/assets/106725464/3a4d9758-8197-45d4-9ceb-62c95c43d858)

## detect in fp32
![Detect](https://github.com/ultralytics/ultralytics/assets/106725464/cc44e4c5-33d7-439f-9837-274a89031c12)

## detect in fp16
![Detect_half](https://github.com/ultralytics/ultralytics/assets/106725464/23b198ca-98b4-4bec-92e5-8b0230c426ee)

## cls in fp32
![cls](https://github.com/ultralytics/ultralytics/assets/106725464/7e5fa83f-82a6-40df-a7c2-1929fc73f998)

**Comment by onuralpszr** [comment]
Sure let me test on other devices and check the code as well.

**Comment by DennisJcy** [comment]
@glenn-jocher  I will add pose inference code soon :smile:

**Comment by glenn-jocher** [comment]
@DennisJcy that sounds fantastic! Looking forward to your contribution to the pose inference feature. 😄👏
