### ISSUE TITLE
dynamic batch

### ISSUE THREAD

**Issue by Lishumuzixin** [ultralytics/ultralytics#6875]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to export the model, batch is dynamic, BUT the height and width are fixed. How should this be modified?Because of the acceleration with tensorrt, I hope to process data in batches.

**Comment by glenn-jocher** [comment]
@Lishumuzixin hello! For exporting a YOLOv8 model with a dynamic batch size but fixed height and width, you can specify the desired dimensions during the export process using the `--batch-size` flag for the dynamic batch and setting the height and width using the `--imgsz` flag. When exporting to an optimized format like TensorRT, this configuration allows you to take advantage of batch processing for inference acceleration while maintaining a consistent spatial input size. Please view the Export mode in our documentation for more detailed instructions on the export process. Have a great day! 🚀

**Comment by zoumaguanxin** [comment]
> @Lishumuzixin hello! For exporting a YOLOv8 model with a dynamic batch size but fixed height and width, you can specify the desired dimensions during the export process using the `--batch-size` flag for the dynamic batch and setting the height and width using the `--imgsz` flag. When exporting to an optimized format like TensorRT, this configuration allows you to take advantage of batch processing for inference acceleration while maintaining a consistent spatial input size. Please view the Export mode in our documentation for more detailed instructions on the export process. Have a great day! 🚀

Do you mind giving a CLI as the following?

```
yolo export model='yolov8m.pt' format=onnx batch=-1 imgsz=224
```
