### ISSUE TITLE
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 69976) of binary: 

### ISSUE THREAD

**Issue by jzw0707** [ultralytics/ultralytics#688]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I am dealing with a problem with using DataParallel and DistributedDataParallel to parallelize YOLOV8n model into multiple GPUS. This bug occurs during validation. I get the error "ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 2762685)".
I cannot locate the key problem according to this error report. How to resolve this issue?

### Environment

python:3.8.16
torch: 1.10.0+cu111
ultralytics: 8.0.4
matplotlib: 3.6.3 
opencv-python: 4.7.0.68
ubuntu 5.4.0

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by jzw0707** [comment]
![捕获](https://user-images.githubusercontent.com/56501057/215258337-454875ca-8d82-49dd-ae37-b05b1b995103.PNG)

**Comment by Laughing-q** [comment]
@jzw0707 hi can you try it with the latest version?

**Comment by Shen52-YC** [comment]
> ![捕获](https://user-images.githubusercontent.com/56501057/215258337-454875ca-8d82-49dd-ae37-b05b1b995103.PNG)

hey! I got the same issue. Have u solved it? :)

**Comment by glenn-jocher** [comment]
@Shen52-YC hi there! If you're encountering issues with DistributedDataParallel, it's often related to environment setup or configuration. Make sure that your environment is correctly configured for distributed training and that you're following the guidelines in our documentation for setting up your system. If the issue persists, please ensure you're using the latest version of our software, as updates often contain bug fixes and improvements. If you've already tried these steps and the problem remains, consider opening an issue on our GitHub with full error logs and system details for further assistance. 🛠️
