### ISSUE TITLE
Error when exporting SAM model from .pt to .onnx format.

### ISSUE THREAD

**Issue by Hanning-Liu** [ultralytics/ultralytics#6881]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

This is my code, only 3 lines:
```
from ultralytics import SAM

model = SAM('sam_b.pt')

model.export(format='onnx')
```

I get this error message:
```
(ultralytics) PS C:\Users\77950\Desktop\Ultralytics> & C:/Users/77950/miniconda3/envs/ultralytics/python.exe c:/Users/77950/Desktop/Ultralytics/test_ModelExport.py
Traceback (most recent call last):
  File "c:/Users/77950/Desktop/Ultralytics/test_ModelExport.py", line 5, in <module>
    model.export(format='onnx')
  File "C:\Users\77950\miniconda3\envs\ultralytics\lib\site-packages\ultralytics\engine\model.py", line 308, in export
    custom = {'imgsz': self.model.args['imgsz'], 'batch': 1, 'data': None, 'verbose': False}  # method defaults
  File "C:\Users\77950\miniconda3\envs\ultralytics\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Sam' object has no attribute 'args'
```

### Environment

Ultralytics YOLOv8.0.223 🚀 Python-3.8.18 torch-2.1.1 CUDA:0 (NVIDIA GeForce GTX 1660 Ti, 6144MiB)
Setup complete ✅ (12 CPUs, 15.9 GB RAM, 304.0/931.2 GB disk)

### Minimal Reproducible Example

```
from ultralytics import SAM

model = SAM('sam_b.pt')

model.export(format='onnx')
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Hanning-Liu thank you for reporting this issue! It appears there might be a bug during the export process of the SAM model to ONNX format. We'll investigate this promptly. Meanwhile, ensure your local repository is updated with the latest commits as we actively fix bugs. This error suggests that the SAM object is missing an 'args' attribute, required for exporting.

For immediate assistance, refer to our Docs, especially the sections related to Export mode, to check for any updates on the correct usage. If you continue experiencing this issue after updating, please open a new issue providing all the relevant details, and we will address it as soon as possible. 🛠️

**Comment by glenn-jocher** [comment]
@Hanning-Liu I've tried SAM export and it fails due to the underlying differences with the ultralytics models, but you can export FastSAM to ONNX correctly, I'd recommend this route:

<img width="1039" alt="Screenshot 2023-12-10 at 16 26 55" src="https://github.com/ultralytics/ultralytics/assets/26833433/ca52c74e-290d-4c01-aded-17ceaddb189e">

**Comment by glenn-jocher** [comment]
@Hanning-Liu I'm updating the docs for SAM and mobile SAM to reflect the lack of export capability now.

**Comment by Hanning-Liu** [comment]
Hi @glenn-jocher ,
Thank you for your reply, I will give Fast-SAM a try!

**Comment by glenn-jocher** [comment]
@Hanning-Liu you're welcome! If you encounter any issues or have further questions while using Fast-SAM, please feel free to reach out. Happy coding! 😊🚀
