### ISSUE TITLE
Provide the same folder Prediction

### ISSUE THREAD

**Issue by chanakya009** [ultralytics/ultralytics#6888]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hey guys i am back with new feature that u guys can work on and it is heplfull for every one as i can see lots of request are rising how extarct the bounding boxes data form the predicted data 

### Use case

Create the same out put folder for Predict same like your creating folder for train where you can see the required files in it also where you guys can provide the text files of object files for the predicted file which consists of list of predicted bounding boxes with the object class labels.

### Additional

I have seen that losts of them are trying to extarct the bounding box corrdinates and object class using resuts.txt after training is done with the cudtom data if you implement the above feature i have asked for i hope this will help full everyone and specially who are using Ultralytics for custom datasets, As of now i can see the only output is that its creating the predict folder in runs only with images of predicted which is showing the bounding boxes on the images (!yolo task=detect mode=predict model='runs/detect/train/weights/best.pt' conf=0.25 source='/folder/Images') i am using this code snippet 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@chanakya009 hello! Thank you for bringing up this feature request regarding the prediction output folder structure and inclusion of bounding box data in a text file format. Your suggestion for enhancing the user experience and making it easier to access bounding box coordinates and class labels post-prediction is acknowledged. 🌟

We understand that obtaining detailed predictions is crucial for various use cases and that having a structured output directory similar to the one created for training could streamline workflows. Your insight that users are currently extracting this information from `results.txt` illustrates the need for a more direct method of retrieving prediction data.

Although providing prediction details in a dedicated text file is not currently a standard feature of YOLOv8, I recognize the value it could add for users working with custom datasets. We're always looking for ways to improve the usability and functionality of our models, and user feedback is a key component of that process.

We'll take your suggestion into consideration for future updates. I invite you to keep an eye on our repository for any announcements related to this feature. Additionally, if anyone in the community is interested in contributing to this aspect, they are more than welcome to explore the possibility of submitting a PR.

Meanwhile, for further information on how YOLOv8 operates or for other details, please refer to our documentation at https://docs.ultralytics.com. We appreciate your enthusiasm and support for YOLOv8 and the Ultralytics community! 😊
