### ISSUE TITLE
Help with .tflite int8 imgsz=320

### ISSUE THREAD

**Issue by Rasantis** [ultralytics/ultralytics#6893]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I did custom training on a yolo v8n and exported it to .tflite, as I will try to run it on a Raspberry Pi4 in real time (or close to it), I got these results when testing the model:
Ultralytics YOLOv8.0.225 🚀 Python-3.10.12 torch-2.1.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
Loading /content/runs/detect/train3/weights/best_saved_model/best_int8.tflite for TensorFlow Lite inference...
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

image 1/1 /content/aabbcc-1/train/images/img103_png.rf.939531a3cfe0822bdc78624547ac6071.jpg: 320x320 15 persons, 137.2ms
Speed: 2.6ms preprocess, 137.2ms inference, 1.8ms postprocess per image at shape (1, 3, 320, 320)
Results saved to runs/detect/predict4
💡 Learn more at https://docs.ultralytics.com/modes/predict
I didn't find this script related to this prediction, could you give it to me? I have been trying to run this more "optimized" model, with int8, half, batch=16

**Comment by RizwanMunawar** [comment]
Thank you, @Rasantis, for sharing the details. The prediction script can be found in the [Ultralytics Code](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/models/yolo/detect/predict.py). 

Additionally, we have included the parameters for the tflite configuration in our documentation. You can utilize them directly without modifying anything in predict.py. For more information, please refer to our Docs: https://docs.ultralytics.com/modes/export/#export-formats

Hope this helps! Let me know if you have any additional questions.

Thanks and Regards
Ultralytics Team!
