### ISSUE TITLE
the problem is exporting the item

### ISSUE THREAD

**Issue by Kirillh993** [ultralytics/ultralytics#6894]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

As I understand it, I have disabled auto-update. I do not know how to turn it on!!!

I've been waiting like this for a very long time and nothing is happening
![Screenshot_9](https://github.com/ultralytics/ultralytics/assets/153268853/e2390ef7-b690-4fd4-9e0b-db31ef5844fd)

the result after the command: Pip uninstall onnx
![Screenshot_10](https://github.com/ultralytics/ultralytics/assets/153268853/f49bd78e-2636-4712-bc30-9991c3766dcc)

reinstall ultralyrics doesn't work
pip3 install --upgrade ultralytics doesn't work

### Environment

Ultralytics YOLOv8.0.225 🚀 Python-3.11.6 torch-2.1.1+cu121 CUDA:0 (NVIDIA GeForce RTX 2060 SUPER, 8192MiB)
Setup complete ✅ (12 CPUs, 15.9 GB RAM, 120.2/476.3 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.11.6
Install             pip
RAM                 15.91 GB
CPU                 AMD Ryzen 5 5600X 6-Core Processor
CUDA                12.1

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
Thank you, @Kirillh993, for providing the details. Could you kindly verify the model you are utilizing for exporting? Are you using the YOLOv8 model, or is it a different one such as YOLOv5, YOLOv6, or a custom model?

Since I can successfully export the YOLOv8 model to ONNX.

![Screenshot 2023-12-10 144554](https://github.com/ultralytics/ultralytics/assets/62513924/523fdb03-bc9b-4b3d-bae1-d1213ca583bb)

Thanks and Regards
Ultralytics Team!

**Comment by Kirillh993** [comment]
> Спасибо, @Kirillh993, за предоставление подробной информации. Не могли бы вы, пожалуйста, подтвердить модель, которую вы используете для экспорта? Используете ли вы модель YOLOv8 или это другая модель, такая как YOLOv5, YOLOv6 или пользовательская модель?
> 
> Поскольку я могу успешно экспортировать модель YOLOv8 в ONNX.
> 
> [![Скриншот 2023-12-10 144554](blob:https://github.com/fbf7e671-a330-4004-a78c-eeda34976230)](https://private-user-images.githubusercontent.com/62513924/289349810-523fdb03-bc9b-4b3d-bae1-d1213ca583bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMDI3ODUsIm5iZiI6MTcwMjIwMjQ4NSwicGF0aCI6Ii82MjUxMzkyNC8yODkzNDk4MTAtNTIzZmRiMDMtYmM5Yi00YjNkLWJhZTEtZDEyMTNjYTU4M2JiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDEwMDEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjZGY0MDkwNzNmZDYzZDIyZDYzNTU1M2NjMTcxYTBmY2Y0OWViZmU1YTg2NjNjZWNhY2Y4MmJjOTRhYTI3NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nKSRTEnYyNuE5d0eUl8eiTGwxBEDekYhZvrEH9SspHA)
> 
> Спасибо и с уважением Команда Ultralytics!

Thank you very much for the reply. Yes, I use YOLOv8

**Comment by RizwanMunawar** [comment]
Thank you, @Kirillh993. However, your issue cannot be replicated. I recommend attempting the export process in Google Colab. It seems that the problem may be associated with the packages on your local machine.

Thanks and Regards
Ultralytics Team!

**Comment by Kirillh993** [comment]
Thank you! I will try! We are in touch with you!

**Comment by glenn-jocher** [comment]
You're welcome, @Kirillh993! Feel free to reach back if further assistance is needed. Good luck with the process!
