### ISSUE TITLE
failed install ultralytics

### ISSUE THREAD

**Issue by DnEcing** [ultralytics/ultralytics#6900]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I failed to install using python setup.py develop，the error shown below

### Additional

![image](https://github.com/ultralytics/ultralytics/assets/114732610/c090c404-da14-4af9-9a4c-a6abb19e0387)

**Comment by RizwanMunawar** [comment]
@DnEcing, Thanks for the update. Could you please attempt the installation of the `ultralytics` package using the provided steps?

1. `git clone https://github.com/ultralytics/ultralytics`
2. `cd ultralytics`
3. `python setup.py install`

Feel free to reach out if you encounter any further inquiries.

Best regards,
The Ultralytics Team

**Comment by RizwanMunawar** [comment]
@DnEcing Great! Closing this issue now. Feel free to reopen if the problem persists.

Best regards,
The Ultralytics Team
