### ISSUE TITLE
能不能多链接写公开的数据

### ISSUE THREAD

**Issue by q465414859** [ultralytics/ultralytics#691]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

新人，想多找些数据集训练，但没有合适的，希望能多有些数据集

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@q465414859 hi there! Thanks for reaching out. 🌟 YOLOv8 supports training on popular datasets like COCO, VOC, and ImageNet, which are automatically downloaded on first use. These common datasets cover a wide range of object classes and are great for getting started with YOLOv8. Additionally, you can explore various open datasets available online such as Open Images, KITTI, or Cityscapes, which can be used for custom training. Feel free to check out the Ultralytics Docs for more details on dataset options and how to use them with YOLOv8. Happy training! 😊
