### ISSUE TITLE
YOLOv8 heatmap documentation

### ISSUE THREAD

**Issue by geoxpert0001** [ultralytics/ultralytics#6911]
I referred to the YOLOv8 heatmap documentation and successfully created a heatmap video. 
However, I have a question: why doesn't the color gradually fade away when an object doesn't appear for some time? 
For example, in the video between 1:26 and 1:39, there's a noticeable period where no cars are present in the middle lane, but the heatmap color persists.
video
https://drive.google.com/file/d/1lGdE1D8H8066Y28LobicQHIEgYQhNsUq/view?usp=sharing

result video
https://drive.google.com/file/d/1E0fIR3M8JGYvvqWXknhnPufL40hJ6-Zz/view?usp=sharing

![image](https://github.com/ultralytics/ultralytics/assets/141697815/adb840bc-bd97-477d-805b-769d95fcdd87)

```
from ultralytics import YOLO
from ultralytics.solutions import heatmap
import cv2

model = YOLO("yolov8m.pt")   # YOLOv8 custom/pretrained model
cap = cv2.VideoCapture("456.mp4")
assert cap.isOpened(), "Error reading video file"

# Video writer
video_writer = cv2.VideoWriter("heatmap_output.mp4",
                               cv2.VideoWriter_fourcc(*'mp4v'),
                               int(cap.get(5)),
                               (int(cap.get(3)), int(cap.get(4))))

classes_for_heatmap = [0, 2]

# Heatmap init
heatmap_obj = heatmap.Heatmap()
heatmap_obj.set_args(colormap=cv2.COLORMAP_TURBO,
                     imw=cap.get(4),  # should same as im0 width
                     imh=cap.get(3),  # should same as im0 height
                     view_img=True)

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        exit(0)
    results = model.track(im0, persist=True, classes=classes_for_heatmap, device=0, tracker="botsort.yaml")
    im0 = heatmap_obj.generate_heatmap(im0, tracks=results)
    video_writer.write(im0)
```

I wish the heatmap could dynamically adjust color intensity based on time. If there's a period without object tracking, I hope the heatmap color gradually fades or disappears.

thanks.

**Comment by geoxpert0001** [comment]
@RizwanMunawar 
can you edit this code?

**Comment by RizwanMunawar** [comment]
@geoxpert0001, appreciate the information you shared! Currently, this feature is not supported, but we plan to include it in upcoming releases.

Best regards,
Ultralytics Team

**Comment by geoxpert0001** [comment]
@RizwanMunawar 
I noticed your update to heatmap.py and decided to test it immediately. 
There is a bug where the heatmap disappears temporarily when there are no objects on the screen. It only reappears when an object appears. For example, in the video from 7:50 to 8:00 in the following link.

https://drive.google.com/file/d/1ZR_uD9_7_oEhrNqOde7GI43OMdEqtS21/view?usp=sharing

please fix it, thanks.

**Comment by geoxpert0001** [comment]
> @geoxpert0001, great job, and thank you for bringing this to our attention! I've identified the issue, and we'll work on resolving it in the near future!
> 
> Thanks Ultralytics Team!

if you fix this bug (no object detected when heatmap disappear), please notify me.
thanks

**Comment by glenn-jocher** [comment]
@geoxpert0001, will do! We'll update the changelog and notify you once the bug is fixed. Thanks for your patience!

**Comment by RizwanMunawar** [comment]
@geoxpert0001, appreciate the update. We've internally verified the heatmap results, and it appears that the code is functioning as expected. Please note that the heatmap may take 5-10 seconds to disappear if a frame contains no objects. The heatmap won't be created or removed for every frame directly.

Kindly retest, and inform me if the heatmap persists on frames without objects after the specified time. You have the option to expedite this process by reducing the `decay_factor` value, for example, setting it to `0.5` will allow the algorithm to delete the heatmap area immediately when there will be no objects.

Hope this helps! Let me know if you have any additional questions.

Thanks and Regards
Ultralytics Team!

**Comment by geoxpert0001** [comment]
@RizwanMunawar 
After the update, the heatmap still disappears (if there are no objects on the screen). I have set the decay_factor to 0.997. I want the heatmap to persist even when there are no objects on the screen.

just look this 3 frames
![image](https://github.com/ultralytics/ultralytics/assets/141697815/6c312add-00b9-48a8-92a5-86e1d6dcd520)
![image](https://github.com/ultralytics/ultralytics/assets/141697815/b3177b0f-46a5-4045-a42e-42283ee220c1)
![image](https://github.com/ultralytics/ultralytics/assets/141697815/faac585b-ef71-446a-b6b7-eed40ce51b69)

**Comment by RizwanMunawar** [comment]
@geoxpert0001 Appreciate the information you shared! If you prefer to keep the heatmaps without any objects in the frame, you can set `decay_factor=1`.

Thanks,
Ultralytics Team!

**Comment by geoxpert0001** [comment]
@RizwanMunawar 
I set decay_factor=1, but the heatmap still disappears.
maybe you can try this video to test.
there are no object in the video from 7:50 to 8:00.

https://drive.google.com/file/d/180TQ0qZ-nv3VcXbC1imIkdxIbboPlrup/view?usp=sharing

**Comment by geoxpert0001** [comment]
@RizwanMunawar 
do you have any updated?

**Comment by geoxpert0001** [comment]
@RizwanMunawar 
please fix this issue.
thanks

**Comment by glenn-jocher** [comment]
@geoxpert0001, acknowledged! We're looking into the issue and will address it as soon as possible. Thank you for your patience.

**Comment by geoxpert0001** [comment]
@glenn-jocher 
any update?

**Comment by RizwanMunawar** [comment]
@geoxpert0001 The issue should be resolved now. It took some time for a comprehensive fix, but hopefully, you can now enjoy using heatmaps :)

**Comment by geoxpert0001** [comment]
@RizwanMunawar 
![image](https://github.com/ultralytics/ultralytics/assets/141697815/1fef7050-ba07-41cf-ba78-8cc5509259f7)

just update your heatmap.py and displayed error msg.

    self.im0 = cv2.addWeighted(self.im0, 1 - self.heatmap_alpha, heatmap_colored, self.heatmap_alpha, 0)
cv2.error: OpenCV(4.8.1) /io/opencv/modules/core/src/arithm.cpp:647: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'arithm_op'

**Comment by RizwanMunawar** [comment]
@geoxpert0001 Please make sure to update your `ultralytics` package and then try again :)

Thanks

**Comment by geoxpert0001** [comment]
> @geoxpert0001 Please make sure to update your `ultralytics` package and then try again :)
> 
> Thanks

i have used pip install --upgrade ultralytics 
but still displayed error msg

**Comment by glenn-jocher** [comment]
@geoxpert0001 It seems there might be a mismatch in the dimensions of the images being processed. Please ensure that the dimensions of `self.im0` and `heatmap_colored` are identical. If the issue persists, consider checking for any recent updates or changes in the repository that might address this.

**Comment by Burhan-Q** [comment]
@geoxpert0001 the error you're encountering is due to your video capture properties being numbers, which you have backwards. I recommend using the [property attributes instead](https://docs.opencv.org/4.8.0/d4/d15/group__videoio__flags__base.html#gaeb8dd9c89c10a5c63c139bf7c4f5704d) so it's easier to "see" what you're working with.

```diff
from ultralytics import YOLO
from ultralytics.solutions import heatmap
import cv2

model = YOLO("yolov8m.pt")   # YOLOv8 custom/pretrained model
cap = cv2.VideoCapture("456.mp4")
assert cap.isOpened(), "Error reading video file"

# Video writer
video_writer = cv2.VideoWriter("heatmap_output.mp4",
                               cv2.VideoWriter_fourcc(*'mp4v'),
                               int(cap.get(5)),
                               (int(cap.get(3)), int(cap.get(4))))

classes_for_heatmap = [0, 2]

# Heatmap init
heatmap_obj = heatmap.Heatmap()
heatmap_obj.set_args(colormap=cv2.COLORMAP_TURBO,
-                     imw=cap.get(4),  # should same as im0 width
-                     imh=cap.get(3),  # should same as im0 height
+                     imw=cap.get(cv2.CAP_PROP_FRAME_WIDTH),  # should same as im0 width
+                     imh=cap.get(cv2.CAP_PROP_FRAME_HEIGHT),  # should same as im0 height
                     view_img=True)

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        exit(0)
    results = model.track(im0, persist=True, classes=classes_for_heatmap, device=0, tracker="botsort.yaml")
    im0 = heatmap_obj.generate_heatmap(im0, tracks=results)
    video_writer.write(im0)
    ```

**Comment by geoxpert0001** [comment]
> @geoxpert0001 the error you're encountering is due to your video capture properties being numbers, which you have backwards. I recommend using the [property attributes instead](https://docs.opencv.org/4.8.0/d4/d15/group__videoio__flags__base.html#gaeb8dd9c89c10a5c63c139bf7c4f5704d) so it's easier to "see" what you're working with.
> 
> ```diff
> from ultralytics import YOLO
> from ultralytics.solutions import heatmap
> import cv2
> 
> model = YOLO("yolov8m.pt")   # YOLOv8 custom/pretrained model
> cap = cv2.VideoCapture("456.mp4")
> assert cap.isOpened(), "Error reading video file"
> 
> # Video writer
> video_writer = cv2.VideoWriter("heatmap_output.mp4",
>                                cv2.VideoWriter_fourcc(*'mp4v'),
>                                int(cap.get(5)),
>                                (int(cap.get(3)), int(cap.get(4))))
> 
> classes_for_heatmap = [0, 2]
> 
> # Heatmap init
> heatmap_obj = heatmap.Heatmap()
> heatmap_obj.set_args(colormap=cv2.COLORMAP_TURBO,
> -                     imw=cap.get(4),  # should same as im0 width
> -                     imh=cap.get(3),  # should same as im0 height
> +                     imw=cap.get(cv2.CAP_PROP_FRAME_WIDTH),  # should same as im0 width
> +                     imh=cap.get(cv2.CAP_PROP_FRAME_HEIGHT),  # should same as im0 height
>                      view_img=True)
> 
> while cap.isOpened():
>     success, im0 = cap.read()
>     if not success:
>         exit(0)
>     results = model.track(im0, persist=True, classes=classes_for_heatmap, device=0, tracker="botsort.yaml")
>     im0 = heatmap_obj.generate_heatmap(im0, tracks=results)
>     video_writer.write(im0)
>     ```
> ```

```
+                     imw=cap.get(cv2.CAP_PROP_FRAME_WIDTH),  # should same as im0 width
+                     imh=cap.get(cv2.CAP_PROP_FRAME_HEIGHT),  # should same as im0 height
```

thanks a lot. there is working now.

but there is still have bug if object is gone, heatmap also disapeared.

video
https://github.com/ultralytics/ultralytics/assets/141697815/fea94afa-a246-4546-8e66-3435e5d9678a

output
https://github.com/ultralytics/ultralytics/assets/141697815/6c99a469-72d8-439d-9d42-0e09fba5278b

**Comment by glenn-jocher** [comment]
@geoxpert0001 Great to hear the dimension issue is resolved! Regarding the heatmap persistence, this behavior is by design to reflect real-time object presence. If objects are no longer detected, the heatmap will fade accordingly. If you need a more persistent heatmap, you might consider adjusting the decay rate or implementing a custom accumulation strategy. Thanks for your feedback, and we appreciate your contribution to improving YOLOv8! 🚀

**Comment by geoxpert0001** [comment]
I understand that heatmaps are generated based on the presence or absence of objects to achieve a fade effect. However, in real-world applications, it's possible that one moment there are no objects at all, so the model shouldn't make the heatmap disappear entirely. If there was a heatmap in the previous second because an object was present but then moves out of the detection area the next second, resulting in the entire heatmap disappearing until another object appears in the frame, I think this approach is not quite reasonable.

My scenario is 24/7.

**Comment by glenn-jocher** [comment]
@geoxpert0001 For 24/7 scenarios, a custom heatmap decay strategy could be implemented to retain heatmap traces for a longer duration, even when objects are temporarily absent. This would provide a more continuous visualization over time. Adjusting the heatmap decay parameter could help achieve the desired effect. 🌟

**Comment by marcospgp** [comment]
> a custom heatmap decay strategy could be implemented to retain heatmap traces for a longer duration, even when objects are temporarily absent

What does this mean in practice?

> Adjusting the heatmap decay parameter could help achieve the desired effect

I updated to the latest version (`8.1.18`) but could not get around the issue where the heatmap (all active tracks, and the generalized blue tint) disappears from the output image when there are no detections on the current frame.

This seems to be a bug, which remains even though there are two reports of it being fixed in this thread 😅 it looks like there may be a misunderstanding of what the issue is about?

Is there any chance this issue could be reopened and addressed?

**Comment by geoxpert0001** [comment]
> > a custom heatmap decay strategy could be implemented to retain heatmap traces for a longer duration, even when objects are temporarily absent
> 
> What does this mean in practice?
> 
> > Adjusting the heatmap decay parameter could help achieve the desired effect
> 
> I updated to the latest version (`8.1.18`) but could not get around the issue where the heatmap (all active tracks, and the generalized blue tint) disappears from the output image when there are no detections on the current frame - even with different values for the `decay_factor` setting (such as not setting it at all or setting it to `0`, `0.01`, `0.99`, and `1`)
> 
> This seems to be a bug, which remains even though there are two reports of it being fixed in this thread 😅 it looks like there may be a misunderstanding of what the issue is about?
> 
> Is there any chance this issue could be reopened and addressed?

like this video in 5s?
https://www.youtube.com/watch?v=hzBb5lNKl9c

**Comment by glenn-jocher** [comment]
@geoxpert0001 hey there! 😊 Thanks for bringing this to our attention and for the detailed explanation. It sounds like the behavior you're experiencing with the heatmap not persisting as expected is indeed not ideal for continuous monitoring scenarios.

In practice, a custom heatmap decay strategy would involve adjusting how quickly the heatmap "fades" over time when no detections are present. This could mean, for example, gradually reducing the intensity of heatmap colors over a set period rather than immediately dropping to zero.

Given your observations with the `decay_factor` not producing the expected results, it does seem like there might be a deeper issue at play. We definitely want to ensure the heatmap functionality aligns with real-world use cases like yours.

I'll reopen the issue and take another look into it. In the meantime, if you're comfortable tweaking the code, you might experiment with manually adjusting the heatmap update logic to ensure it retains some intensity even when detections are momentarily absent. Here's a pseudo-code snippet to illustrate a potential approach:

```python
if current_frame_has_detections:
    update_heatmap_with_current_detections()
else:
    decay_heatmap_intensity_slowly()
```

This is just a rough idea, and the actual implementation would depend on how the heatmap is being generated and updated in your setup. We appreciate your patience and feedback on this, and we'll aim to get a fix or workaround sorted out as soon as possible! 🚀

**Comment by marcospgp** [comment]
@glenn-jocher You didn't actually reopen the issue however - are these comments LLM generated?

The wording is unnecessarily abstract and verbose, and the sample code is simplified to the point that it is no longer useful.

On top of that, none of the information is specific enough that it can be mapped back to actual ultralytics-interfacing code.

Looking back, this seems to be generalized across your other comments as well.
