### ISSUE TITLE
How can I add custom callback for tensorboard in multi-GPU training

### ISSUE THREAD

**Issue by Twinparadox** [ultralytics/ultralytics#6913]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

First, Thank you for your great project.

I'm trying to train your YOLOv8 for object detection by referring [Detection Docs](https://docs.ultralytics.com/tasks/detect/)
Your `ultralytics.utils.callbacks.tensorboard` package make me add a callback to record metrics on the tensorboard easier, so I used it.
Your tools were helpful enough, but I added custom callbacks because I needed additional things to record data on the tensorboard.
Here is my code.

```python
try:
    from torch.utils.tensorboard import SummaryWriter
    WRITER = None  # TensorBoard SummaryWriter instance

except (ImportError, AssertionError, TypeError):
    SummaryWriter = None


def on_train_start(trainer):
    print(trainer.args)
    global WRITER
    if WRITER is None:
        WRITER = SummaryWriter(str(trainer.save_dir))
    WRITER.add_text("args", str(trainer.args).replace("\n", "<br/>"))


def on_fit_epoch_end(trainer):
    global WRITER
    if WRITER is None:
        WRITER = SummaryWriter(str(trainer.save_dir))
    if trainer.best_fitness == trainer.fitness:
        best_metrics = "best_epoch: {}<br/>{}"\
            .format(trainer.epoch, str(trainer.metrics).replace("\n", "<br/>"))

        WRITER.add_text("best_metrics", best_metrics)


def train(args):
    # Do something
    model = YOLO(args.pretrained)  # load a pretrained model (recommended for training)
    model.info()

    # tensorboard callback
    for k, v in callbacks.items():
        model.add_callback(k, v)
    model.add_callback("on_train_start", func=on_train_start)
    model.add_callback("on_fit_epoch_end", func=on_fit_epoch_end)

    # Do something
```

However, custom callbacks didn't work in multi-GPU(`device=0,1`) training.
I've tested in single GPU(`device=0`) and CPU(`device=cpu`) as well,
but I've seen that both settings have no issues, and it only doesn't work in multiple GPU.

I think it is same issue(#6168), but i'm not sure.
I also tried to manually run DDP mode with torchrun or torch.distributed.run,

`python -m torch.distributed.run --nproc_per_node=2 ./train.py` 

this solution works for my custom callback, but not your callbacks.
I got some errors `AttributeError: 'NoneType' object has no attribute 'items'` in your tensorboard callbacks(`_log_scalar`).

Please give me any advices for this issue.

### Additional

```
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/model.py", line 338, in train
    self.trainer.train()
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 190, in train
    self._do_train(world_size)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 391, in _do_train
    self.run_callbacks('on_fit_epoch_end')
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 155, in run_callbacks
    callback(self)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/utils/callbacks/tensorboard.py", line 69, in on_fit_epoch_end
    _log_scalars(trainer.metrics, trainer.epoch + 1)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/utils/callbacks/tensorboard.py", line 21, in _log_scalars
    for k, v in scalars.items():
AttributeError: 'NoneType' object has no attribute 'items'
[2023-12-11 09:37:10,861] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 36 closing signal SIGTERM
[2023-12-11 09:37:11,026] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 37) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 810, in <module>
    main()
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
```

**Comment by glenn-jocher** [comment]
@Twinparadox hello and thank you for reaching out with your question!

Custom callbacks for multi-GPU training involving TensorBoard can indeed be a bit more complex due to the nature of distributed training. The issue you're describing seems to be related to the way TensorBoard logging is handled within the multi-GPU context. When training with Distributed Data Parallel (DDP), only the process running on the main GPU (rank 0) should write to TensorBoard to avoid conflicts.

To resolve this, ensure that your custom TensorBoard logging is wrapped with a condition that checks for the process rank. The global rank of the process can be accessed via `trainer.global_rank`, and you should only perform the logging if `trainer.global_rank == 0`. This condition ensures that only the main process logs to TensorBoard, preventing conflicts and potential errors related to writing from multiple processes.

Also, regarding the error `'NoneType' object has no attribute 'items'`, it suggests that at some point, the expected dictionary containing metrics is not being instantiated correctly, possibly due to the DDP context. You might want to investigate where and how the `trainer.metrics` is being set or modified in your training loop to avoid encountering a `NoneType` when it is expected to be a dictionary.

It's great to hear our tools have been helpful, and we encourage you to continue using these best practices when extending functionality within the YOLOv8 framework. Remember to check for `trainer.global_rank == 0` when adding any logging or file-writing operations within your custom callbacks to avoid conflicts with the multi-GPU setup.

If you continue to face challenges, consider utilizing the Discussions section where you may find additional insights from the community, and where our team regularly contributes. Also, please refer to our [Docs](https://docs.ultralytics.com) for detailed guidance on training, callbacks, and more.

Keep up the good work, and good luck with your YOLOv8 object detection project! 🚀😊

**Comment by Twinparadox** [comment]
@glenn-jocher,

Thank you for your kind and quick advice.
I tried to check global rank in for my code with reference to your advice.

```python
def on_train_start(trainer):
    if trainer.global_rank == 0 and WRITER:
        # Do something...
```

However, this code didn't work.
I launched my code without `-m torch.distributed.run --nproc_per_node=2`, and I couldn't log my model.
Also, I launched my code with that options, I got a errors: `AttributeError: 'DetectionTrainer' object has no attribute 'global_rank'`

I think there is no `trainer.global_rank` in trainer of detection model, and my custom callbacks didn't call when training without `-m torch.distributed.run --nproc_per_node=2` option.
What should i do in this situation?

And I have another question.
Whether I use `-m torch.distributed.run --nproc_per_node=2` option or not, if I train my model with multi-GPU environment, does it always run in DDP mode?
Because i got this log with multi-GPU always.

```
DDP: debug command /opt/conda/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port  /workspace/yolov8/.config/Ultralytics/DDP/_temp_23vn5uiz140532944535024.py
```

I'm sorry it might be a boring question and I'm always grateful for your advice.

**Comment by Twinparadox** [comment]
Oh, I think I found some solution.
I use your `ultralytics.utils.RANK` module, It works.
Can you please advise if this is the appropriate way to do it?

```
def on_train_epoch_end(trainer):
    if RANK in (-1, 0) and WRITER:
        # do something...
```

**Comment by glenn-jocher** [comment]
@Twinparadox apologies for the confusion earlier. Yes, using `ultralytics.utils.RANK` is indeed an appropriate method for identifying the main process (rank 0) in a distributed training environment. Your conditional check ensures that the writing operation is only performed by the main process or in a non-distributed setting (`RANK == -1`).

Regarding your previous message, you typically don't need to manually use the `-m torch.distributed.run` command if you are running the training script without it. The YOLOv8 training pipeline internally handles the DDP setup when multiple GPUs are specified.

In any multi-GPU setup within YOLOv8, DDP mode is implicitly used to optimally distribute the workload across the available GPUs. The log you see is indicative of the DDP initialization process that YOLOv8 manages for you.

Good work finding a solution for your custom callbacks, and feel free to continue using the `ultralytics.utils.RANK` utility as part of your multi-GPU training strategy. Keep up the excellent work! 👍🚀

**Comment by Twinparadox** [comment]
@glenn-jocher 
Thank you for your confirm. :)

Anyway, I have one more question(may be last question in this issue) about `running the training script`.

> Regarding your previous message, you typically don't need to manually use the -m torch.distributed.run command if you are running the training script without it. The YOLOv8 training pipeline internally handles the DDP setup when multiple GPUs are specified.

Does it mean using CLI script like `yolo detect train data=coco128.yaml model=yolov8n.pt epochs=100 imgsz=640`?
In my case, I tried to train not CLI but python code.
Is it possible to train without manually command?

**Comment by glenn-jocher** [comment]
@Twinparadox You're welcome! To clarify, whether using the CLI command you've mentioned or invoking the training within your Python code, YOLOv8 will automatically manage the DDP setup for multi-GPU training. You do not need to manually run the `-m torch.distributed.run` command in either case when you are using the YOLOv8 training pipeline. 😊👍

**Comment by Twinparadox** [comment]
Thank you for your kind response, and I hope the project will help more people. :)

**Comment by glenn-jocher** [comment]
@Twinparadox It's my pleasure to assist you! I'm delighted to hear you find the project helpful. Wishing you the best with your work using YOLOv8! 😊🚀

**Comment by Buckler89** [comment]
Hi @glenn-jocher 

I'm trying to implement multi-GPU training directly from Python using PyTorch Ignite's [`Parallel`](https://pytorch.org/ignite/generated/ignite.distributed.launcher.Parallel.html#:~:text=for%20both%20options%3A-,%23%20main.py%0A%0Aimport%20ignite.distributed%20as%20idist%0A%0Adef%20training(local_rank,%2C%20config%2C%20a%3D1%2C%20b%3D2),-Single%20node%2C%20Multi) context manager, as opposed to initiating it from the command line. I've encountered issues when setting up distributed training, specifically with initializing the process group and managing devices for model training. Here's a brief overview of my setup:

main.py
```
...get hyper_params...
hyper_params["yolo_train"]["device"] = list(range(torch.cuda.device_count())) # equal to [0,1,2,3]

if __name__ == "__main__":
      backend = "nccl"  
      spawn_kwargs = {
          "nproc_per_node": len_available_devices,
          "init_method": "tcp://0.0.0.0:50001" # without this I got some problem with the default port 22222 already in use
      }
      print(f"Training on {len_available_devices} GPUs with backend {backend}")
      from experiment import main_experiment_wrapper
      with idist.Parallel(backend=backend, **spawn_kwargs) as parallel:
          parallel.run(main_experiment, hyper_params)
```

experiment.py
```
import os
import torch
import gc

import pandas as pd
import numpy as np
import time
import wandb
from wandb import util as wandb_util
from sklearn.metrics import confusion_matrix, f1_score
import plotly.figure_factory as ff
from tqdm import tqdm
import pickle
from pathlib import Path
import signal

try:
    import ignite.distributed as idist
except ImportError:
    print("ignite.distributed not installed. Install it with pip install pytorch-ignite")


def main_experiment(local_rank, hyper_params, **kwargs):
    print(f"PID = {os. getpid()} \t get_rank = {idist.get_rank()} \t backend= {idist.backend()}")
    print(f"{local_rank = } --- {kwargs = }")
    hyper_params["experiment_name"] = f"{hyper_params['group']}_gpu{local_rank}"
    hyper_params["wandb_run_id"] = wandb_util.generate_id()
    hyper_params["rank"] = local_rank

    # from ultralytics import YOLO
    # from ultralytics.engine.trainer import
    from ultralytics.utils import RANK, LOCAL_RANK # <---------------------- the import in this point let the env variable to be properly set
    from fine_tuning.custom_yolo_model import YOLO
    from wandb.integration.ultralytics import add_wandb_callback
    import wandb_callbackv2 as wandb_callback

    # from ultralytics.utils.callbacks import wb
    # from ultralytics.models.yolo.detect.train import DetectionTrainer
    # from ultralytics.cfg import get_cfg, cfg2dict, DEFAULT_CFG

    actual_epoch = 0
    wandb_step = 0
    # RANK = hyper_params["rank"]
    print(f'Starting wandb run with id {hyper_params["wandb_run_id"]} \n {RANK = } \n {LOCAL_RANK = }')

  with wandb.init(project=hyper_params["project"],
                      group=hyper_params["group"],
                      job_type=hyper_params["job_type"],
                      name=hyper_params["experiment_name"],
                      id=hyper_params["wandb_run_id"],
                      resume="allow",
                      allow_val_change=True) as run:
            if  hyper_params["rank"] == 0: # <--------------------------------------------------- here I add my custom callbacks only to one process         
              for event, func in wandb_callback.callbacks.items():   
                  # model.add_callback(event, lambda trainer: func(trainer, start_step=wandb_step))
                  model.add_callback(event, func)

            model.train(
                project=hyper_params["project"],
                name=hyper_params["experiment_name"],
                data=hyper_params["yolo_train"]["data_yolo_path"],
                cfg=hyper_params["cfg"],
                # parameters for training
                device=hyper_params["yolo_train"]["device"],    <---------------------------------------------- Do I need to manage this somehow?
               .......others parameters....
            )
```

The training process starts correctly across multiple processes with distinct ranks. 
```
--------------------
PID = 30186      get_rank = 0    backend= nccl
local_rank = 0 --- kwargs = {}
Starting wandb run with id 7oj8384j 
 RANK = 0
 LOCAL_RANK = 0
--------------------

PID = 30187      get_rank = 1    backend= nccl
local_rank = 1 --- kwargs = {}
Starting wandb run with id p4e6j10h 
 RANK = 1 
 LOCAL_RANK = 1
--------------------

PID = 30189      get_rank = 3    backend= nccl
local_rank = 3 --- kwargs = {}
Starting wandb run with id nymfkbo6 
 RANK = 3
 LOCAL_RANK = 3
--------------------

PID = 30188      get_rank = 2    backend= nccl
local_rank = 2 --- kwargs = {}
Starting wandb run with id k1wpvsje 
 RANK = 2
 LOCAL_RANK = 2
--------------------
```

However, I encounter a RuntimeError regarding the reinitialization of the default process group for each process I see that error 4 times in the log)
```
          Traceback (most recent call last):
      File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
        fn(i, *args)
      File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/ignite/distributed/comp_models/native.py", line 341, in _dist_worker_task_fn
        fn(local_rank, *args, **kw_dict)
      File "/teamspace/studios/this_studio/code/fine_tuning/experiment.py", line 54, in main_experiment_wrapper
        main_experiment(hyper_params)
      File "/teamspace/studios/this_studio/code/fine_tuning/experiment.py", line 159, in main_experiment
        model.train(
      File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/ultralytics/engine/model.py", line 391, in train
        self.trainer.train()
      File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 208, in train
        self._do_train(world_size)
      File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 321, in _do_train
        self._setup_ddp(world_size)
      File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 224, in _setup_ddp
        dist.init_process_group(
      File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
        func_return = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
      File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1100, in init_process_group
        raise RuntimeError("trying to initialize the default process group twice!")
    RuntimeError: trying to initialize the default process group twice!
```

Here are my specific questions:

1. Could you provide a corrected example of how to initialize and manage multi-GPU training using PyTorch Ignite's `Parallel`, ensuring that the process group is only initialized once and correctly?

2. In the `model.train()` method, is there a need to explicitly manage the `device` parameter differently for distributed training, or does Ignite handle this automatically?

3. I'm not entirely confident in my handling of custom callbacks, especially ensuring they're only added to one process (rank 0). Could you review my approach and suggest any necessary adjustments?

For additional context, I'm successfully able to run multi-GPU training using the Ultralytics library's built-in methods, but my custom callbacks do not execute as expected, prompting this manual approach.

Thank you for your guidance on these issues.

**Comment by ddroghini-ics** [comment]
Hi @glenn-jocher ,
I've identified a potential issue in our training framework when using multi-GPU setups with PyTorch's Distributed Data Parallel (DDP). Specifically, callbacks that are initialized in the main instance of the trainer do not seem to be passed to the subprocesses spawned by DDP. This is evident from examining the `trainer.py` implementation, particularly around the DDP command generation [trainer.py#L201](https://github.com/ultralytics/ultralytics/blob/5cb05a85c7daa2bdca54d4bd2541265eadc0d40a/ultralytics/engine/trainer.py#L201).

In a DDP setup, the main process doesn't directly participate in the training but spawns multiple subprocesses that each handle a portion of the training on separate GPUs. It appears that only the callbacks added in the `__init__` method of the base trainer class are being utilized in these subprocesses.


I'm seeking advice on how to best implement one of these solutions, or if there's an alternative approach that could be more effective for ensuring that callbacks work correctly in a multi-GPU training environment. Any insights or suggestions from the community would be greatly appreciated.

**Comment by Buckler89** [comment]
Hi @glenn-jocher ,
I've identified a potential issue in our training framework when using multi-GPU setups with PyTorch's Distributed Data Parallel (DDP). Specifically, callbacks that are initialized in the main instance of the trainer do not seem to be passed to the subprocesses spawned by DDP. This is evident from examining the `trainer.py` implementation, particularly around the DDP command generation [trainer.py#L201](https://github.com/ultralytics/ultralytics/blob/5cb05a85c7daa2bdca54d4bd2541265eadc0d40a/ultralytics/engine/trainer.py#L201).

In a DDP setup, the main process doesn't directly participate in the training but spawns multiple subprocesses that each handle a portion of the training on separate GPUs. It appears that only the callbacks added in the `__init__` method of the base trainer class are being utilized in these subprocesses.


I'm seeking advice on how to best implement one of these solutions, or if there's an alternative approach that could be more effective for ensuring that callbacks work correctly in a multi-GPU training environment. Any insights or suggestions from the community would be greatly appreciated.

**Comment by glenn-jocher** [comment]
@Buckler89 hello! Thank you for reaching out and for your kind words about the project.

It seems like you're encountering an issue with custom callbacks during multi-GPU training. The error you're seeing, `AttributeError: 'NoneType' object has no attribute 'items'`, suggests that the `scalars` object being passed to `_log_scalars` is `None`.

This could be related to the way the distributed data parallel (DDP) mode handles processes. In DDP, each process operates independently, and it's possible that the `scalars` object isn't being properly synchronized across processes.

Here are a few suggestions that might help resolve the issue:

1. **Ensure Proper Synchronization**: When using DDP, make sure that any data you want to log is properly gathered from all processes. You might need to use `torch.distributed.reduce` or `torch.distributed.gather` to collect the data before logging it.

2. **Use a Single Process for Logging**: Often, it's easier to designate one process (usually rank 0) to handle all logging activities. You can wrap your logging code with a condition to check if the current process is the main one:
   ```python
   if trainer.local_rank == 0:
       # Your logging code here
   ```

3. **Review the Callbacks**: Double-check your custom callbacks to ensure they are compatible with DDP. They should not rely on any shared state that isn't properly synchronized across processes.

4. **Debugging**: Add print statements or use a debugger to inspect the state of your variables right before the error occurs. This can help you understand why `scalars` is `None`.

5. **TensorBoard Writer**: Ensure that the `SummaryWriter` instance is created and used correctly within the DDP context. It might be necessary to pass the `SummaryWriter` instance to each process or create it within each process separately.

6. **Consult the Documentation**: Review the [PyTorch DDP documentation](https://pytorch.org/docs/stable/notes/ddp.html) for best practices and common pitfalls.

7. **Community Help**: If the issue persists, consider opening a discussion on the [Ultralytics GitHub Discussions](https://github.com/ultralytics/ultralytics/discussions) page. The community and maintainers can provide more targeted assistance.

If you believe this is a bug with the Ultralytics YOLOv8 implementation, please feel free to open an issue on the [GitHub repository](https://github.com/ultralytics/ultralytics/issues) with a detailed description and any relevant code snippets.

I hope these suggestions help! If you have further questions or need more assistance, don't hesitate to ask. Good luck with your training! 🚀
