### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by QuanhuiZhao** [ultralytics/ultralytics#6915]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

RuntimeError: Dataset 'yolo_bvn.yaml' error
Dataset 'yolo_bvn.yaml' images not found , missing path 'D:\Program\school\water_git\ultralytics-main\datasets\datasets\bvn\images\val'
Note dataset download directory is 'D:\Program\school\water_git\datasets'. You can update this in 'C:\Users\86176\AppData\Roaming\Ultralytics\settings.yaml'
<img width="993" alt="2eec797fa14c7f096d0ef0716a65259" src="https://github.com/ultralytics/ultralytics/assets/149856108/50dd213b-aa25-48d8-b2ff-d7b6378d0d63">

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@QuanhuiZhao hi there! It looks like you're encountering a path issue with your dataset. The error suggests that YOLOv8 is expecting to find your validation images at `D:\Program\school\water_git\ultralytics-main\datasets\datasets\bvn\images\val` but it can't locate them. 

To resolve this, please ensure that:
1. The path specified in your `yolo_bvn.yaml` file accurately points to the location of your 'val' images.
2. The 'val' folder actually exists at the path provided and that it contains your validation images.

Additionally, review the `settings.yaml` file to make sure that the dataset download directory is set correctly, and adjust it if necessary. 

Best of luck with your project! If you need further clarification, the YOLOv8 documentation on our website should be of assistance. 😊

**Comment by sirineHD** [comment]
Hello,
I encountered the same issue but after dubugging it seems that the yaml file structure is wrong so you need to nc which is the number of classes and the path should be absolute path this is an example of how it should be:


path: "absolute path to your dataset"

# Define dataset splits
train: images/train  # Train images directory
val: images/test     # Validation images directory

nc: 1 
# Define the class names
names:
  0: class_name# If you have multiple classes, add them here

**Comment by glenn-jocher** [comment]
@sirineHD thank you for sharing your experience! For YOLO dataset YAML files, we recommend using relative paths and letting `nc` auto-detect from the `names` list, as shown in our [COCO8 YAML example](https://docs.ultralytics.com/datasets/detect/coco8/#dataset-yaml). Absolute paths can cause issues when sharing projects. The `names` list length automatically defines `nc`, so explicit `nc` declarations aren't required.
