### ISSUE TITLE
Unable to run YoloV8 on Jetson Nano

### ISSUE THREAD

**Issue by Hasnain1997-ai** [ultralytics/ultralytics#6916]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi there!

I am trying to run the YoloV8 model on Jetson Nano JetPack 4
In Jetpack 4 default Python is 3.6 which is not compatible with YoloV8, so I made a docker with Base Image Python 3.8

Inside this docker I installed all the necessary libraries and PyTorch using pip(CPU Version)

I am trying to run the code using the command:
yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'

And I get:
Ultralytics YOLOv8.0.226 🚀 Python-3.8.18 torch-2.1.1 CPU (ARMv8 Processor rev 1 (v8l))
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

Found https://ultralytics.com/images/bus.jpg locally at bus.jpg
Illegal instruction (core dumped)

Does anyone know the issue, or is the Nano not able to run the YoloV8? Any Idea about the issue?

**Comment by Hasnain1997-ai** [comment]
thank you for response @glenn-jocher 

The latest Jetpack supported by Jetson Nano is Jetpack 4.6, which includes Python 3.6. However, the PyTorch wheels available are also for Python 3.6. There are no PyTorch wheels or Docker base images available for Jetpack 4.6 and Python versions greater than 3.6.

Now, let's discuss the Yolo dependencies. YoloV8 requires Python greater than 3.7. Therefore, I used Python 3.8 as the base image and installed PyTorch using pip. Then, I installed Ultralytics using pip and ran the Yolo simple inference, but encountered the above error

**Comment by glenn-jocher** [comment]
Hello @Hasnain1997-ai, for the Jetson Nano, complexity arises when needing to accommodate the right versions of Python, PyTorch, and YOLOv8 dependencies. Since the native JetPack Python version (3.6) isn't compatible with YOLOv8, and the ARM-compatible PyTorch wheels are for Python 3.6, you are in a challenging spot.

Creating a Python 3.8 environment was a logical step, but you might still face compatibility issues with the ARM processor if the PyTorch version installed via pip wasn't built for it specifically.

As a solution, consider manually compiling PyTorch for Python 3.8 from source on the Jetson Nano, ensuring the build is compatible with the ARM architecture. Although more time-consuming, this approach has been successfully used by others in similar situations.

Keep an eye on our documentation for any updates or additional instructions that could facilitate this process for you in the future. Good luck, and I'm here to help with any further questions! 😊🛠️

**Comment by Hasnain1997-ai** [comment]
@glenn-jocher I run the docker using the command

`sudo docker run --network host    -v code_directory:/docker_folder   -e DISPLAY=$DISPLAY --privileged    --name yolo_cont -d -e TERM=xterm --tty yolo_image:v1`

Inside it, I encountered the **Illegal instruction (core dumped)** issue. Since I had no luck resolving it, I switched from Docker to the host machine. I installed Python 3.8, created its virtual environment, and installed Ultralytics, and it worked.

So, with the same instructions, it was not working within Docker, but it is now working on the host machine.

I don't know why this  happened

**Comment by glenn-jocher** [comment]
@Hasnain1997-ai, glad to hear YOLOv8 is running on the host machine! The 'Illegal instruction' error within the Docker container suggests a mismatch between the software and the CPU instructions available. This can occur if the Docker image uses compiled binaries or libraries that don't align with the host's ARM CPU capabilities. 

When you switched to the host, you likely installed packages that built natively on your hardware, ensuring compatibility. For Docker, ensure you're using ARM-compatible base images and building your dependencies (like PyTorch) from source if necessary.

Running complex AI models like YOLOv8 on specialized hardware often requires delicate balancing of dependencies. Keep up the good work, and reach out if you hit any more snags! 😊🚀

**Comment by Matheusp-Silva** [comment]
i have the same problem but on my host machine, i have the python 3.8 and my jetson nano setup is:

Platform:
Ubuntu 18.04
Release: 4.9.337-tegra
CUDA: 10.2.300
cuDNN: 8.2.1.32
TensorRT: 8.2.1.8
OpenCV: 4.5.1 with CUDA: YES
L4T: 32.7.4
Jetpack: 4.6.4

I created a virtualenv using python 3.8, i runned pip install ultralytics and the installation was successful, but when i run my script, i receive "Illegal instruction (core dumped)" 

can help me with this problem?

**Comment by glenn-jocher** [comment]
@Matheusp-Silva hello! The "Illegal instruction (core dumped)" error on your Jetson Nano suggests that the binaries or libraries used are not compatible with the ARM architecture. Since you're using Python 3.8 and have installed Ultralytics via pip, it's possible that the PyTorch version or other dependencies are not built for ARM.

To resolve this, you should ensure that you're using ARM-compatible versions of PyTorch and other libraries. You may need to build PyTorch from source to match your CUDA and cuDNN setup. Also, verify that all other dependencies are compatible with your system's architecture.

Keep in mind that running AI models on Jetson devices often requires specific versions of libraries that are optimized for ARM and CUDA, so using the versions provided by NVIDIA for Jetpack is crucial. Good luck, and I hope this helps! 😊🛠️

**Comment by TimotheeWrightFicha** [comment]
For all the people that will end up on this thread in the future, facing the same compatibility issues, I've tried to answer this in a stackoverflow thread:
[https://stackoverflow.com/q/78607175/13123667](https://stackoverflow.com/q/78607175/13123667)

**Comment by glenn-jocher** [comment]
Hello @TimotheeWrightFicha,

Thank you for sharing your experience and the StackOverflow thread link! It's great to see the community coming together to solve these issues. 😊

For those encountering the "Illegal instruction (core dumped)" error on Jetson Nano, here's a more detailed approach to ensure compatibility:

1. **Verify Python and PyTorch Compatibility**:
   Ensure that you are using a PyTorch version compatible with your Jetson Nano's architecture and CUDA version. NVIDIA provides pre-built PyTorch wheels optimized for Jetson devices. You can find the appropriate versions [here](https://developer.download.nvidia.com/compute/redist/jp/v46/pytorch/).

2. **Install PyTorch and Torchvision**:
   Follow these steps to install the correct versions:
   ```bash
   # Remove existing installations
   pip uninstall torch torchvision

   # Install PyTorch for JetPack 4.6
   sudo apt-get install -y libopenblas-base libopenmpi-dev
   wget https://developer.download.nvidia.com/compute/redist/jp/v46/pytorch/torch-1.10.0+nv21.11-cp38-cp38-linux_aarch64.whl
   pip install torch-1.10.0+nv21.11-cp38-cp38-linux_aarch64.whl

   # Install Torchvision from source
   sudo apt install -y libjpeg-dev zlib1g-dev
   git clone --branch v0.11.1 https://github.com/pytorch/vision torchvision
   cd torchvision
   python3 setup.py install --user
   ```

3. **Install Ultralytics**:
   Ensure you have the latest version of Ultralytics installed:
   ```bash
   pip install ultralytics[export] --upgrade
   ```

4. **Run Your Script**:
   Now, try running your YOLOv8 script again:
   ```bash
   yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'
   ```

If the issue persists, please provide a minimum reproducible example of your code. This will help us investigate further. You can find guidelines for creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions or need further assistance. We're here to help! 🚀

**Comment by jasonlytehouse** [comment]
You can use this [repo](https://github.com/jayfalls/jetson_nano_ubuntu20_docker/tree/main) I created which provides a docker image with python3.11 to run any ultralytics yolo models on Jetson Nano with torch gpu or tensorrt

You can expect about 60-70ms average end-to-end with yolov8n and yolov10n on the Jetson with Python3.11

**Comment by glenn-jocher** [comment]
Hello @jasonlytehouse,

Thank you for sharing your Docker repo! It's great to see community contributions that help others run YOLO models on Jetson Nano. For those facing compatibility issues, your Docker image with Python 3.11 and support for torch GPU or TensorRT could be a valuable resource.

For anyone experiencing issues, please ensure you are using the latest versions of `torch` and `ultralytics`. If the problem persists, providing a minimum reproducible example will help us investigate further. You can find guidelines for creating one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to try out @jayfalls' Docker image and share your experiences. We're here to help if you need further assistance! 😊🚀
