### ISSUE TITLE
How to use with datasets in different resolutions?

### ISSUE THREAD

**Issue by NikonD850** [ultralytics/ultralytics#692]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm a newbie in image detecting. How can I use this model to train images set with different resolutions? such as the visdrone by Tianjin Univ. Thanks!

**Comment by knoppmyth** [comment]
There is nothing special you have to do for images in your dataset with different resolutions. It just works. This is how I train as well.

**Comment by NikonD850** [comment]
> There is nothing special you have to do for images in your dataset with different resolutions. It just works. This is how I train as well.

Thanks!

**Comment by AyushExel** [comment]
Bt default the imgsz is set to 640 for training. You can set it to any value you'd like by setting `imgsz=value`. Feel free to reopen the issue if you encounter any bugs :)
