### ISSUE TITLE
Yolov8 training and ONNX inférence 

### ISSUE THREAD

**Issue by Titibo26** [ultralytics/ultralytics#6923]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I need informations about the inference of exported ONNX model of custom trained Yolov8.

1) When training on a dataset, does yolov8 automatically resize image (respecting aspect ratio) to the imgzs input parameter ?
2) Does the exported ONNX model perform the resizing itself or do i need to do it myself ?
3) When exporting ONNX model we can specifies the input of image, does it means it does the resize ?

for exemple 
Training : done with 1920*1080 pictures as they should be resized (regarding prvious posts)
yolo train data=config.yaml model=yolov8n-pose.pt imgsz=320,320 device=0

Export : 
yolo export model=best.pt format=onnx imgsz=320,320 opset=9

4) for inference, i have to input a resized and Normalized image 320*320 into the model, right ?

What if i export the onnx model with a different input size like :
yolo train data=config.yaml model=yolov8n-pose.pt imgsz=1920,1080  device=0
Does the model will resize the input image from 1920*1080 to 320*320 ?

Thanks,

**Comment by glenn-jocher** [comment]
@Titibo26 hello! I'll answer your questions regarding training and ONNX inference with YOLOv8:

1) During training, YOLOv8 does indeed resize images to match the `imgsz` input parameter while maintaining the aspect ratio via letterboxing.

2) The exported ONNX model doesn't handle resizing. Preprocessing, including resizing the images to the required input size, needs to be done before passing them to the model for inference.

3) Specifying the input image size during export defines the expected input dimensions for the ONNX model. It's a fixed size and doesn't mean the model will resize images for you during inference.

4) Yes, for inference, your image should be preprocessed to match the input size expected by the ONNX model, like 320x320 in your case, and also normalized according to the preprocessing steps used during training.

Exporting the ONNX model with a different input size like 1920x1080 is a standalone step and doesn't affect how the model processes input images during inference. You still need to provide preprocessed images that match the exported model's defined input size.

For more detailed information, you can refer to our documentation at https://docs.ultralytics.com. 📚

Happy training and inferring with YOLOv8! 🚀

**Comment by Titibo26** [comment]
Hello, thanks for your fast and detailed answer. I can understand the relationship between input training and inference and how ONNX model is integrated in this.
I decided to train yolov8 with imgz=640, feeding 1920*1080 images without normalization; I'll test results of inference with letterboxed images (from 896*504 to 640*640) without normalization. 

Thanks again.
TD

**Comment by glenn-jocher** [comment]
@Titibo26, you're welcome! Your approach to train with `imgsz=640` and test inference with letterboxed images without normalization seems fine. Keep an eye on the results since the lack of normalization might affect performance depending on your dataset and use case. If you have any more questions or need assistance, feel free to reach out. Good luck with your YOLOv8 project! 🚀
