### ISSUE TITLE
Strange behavior while train with resume = True 

### ISSUE THREAD

**Issue by dimkoss11** [ultralytics/ultralytics#6931]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to continue to train segmentation model.
I load weights from checkpoint:

```
model = YOLO(Config.weights_path)
results = model.train(
batch=Config.batch_size,
device=[0, 1],
data="./data.yaml",
epochs=Config.epochs,
imgsz=Config.img_size,
resume=True
        )
```

set to epoch number to 1. 
but get: 
`engine/trainer: task=segment, mode=train, model=/kaggle/input/rcp-pipe-segm-yolov8-weights/yolov8m_280ep_last.pt, data=./data.yaml, epochs=100,`
And training run for 100 epoch, not 1, Why? If resume is false, training run 1 epoch, as I want.

**Comment by glenn-jocher** [comment]
@dimkoss11 hello! Resuming training with `resume=True` typically continues from the last saved epoch and uses the number of epochs saved in the last checkpoint, overriding the epoch number you've set manually. To train only 1 epoch after resuming, you would need to adjust the epochs in your existing checkpoint metadata to indicate the desired stopping point. However, if you wish to do a fixed 1-epoch fine-tuning, using `resume=False` is indeed the correct step, and it appears you're on the right path there. If further clarification or assistance is needed, feel free to refer to our docs or open an issue. 😊 Happy training!

**Comment by dimkoss11** [comment]
@glenn-jocher thanks! How to edit the checkpoint metadata?
