### ISSUE TITLE
Cannot load backend 'QtAgg' which requires the 'qt' interactive framework, as 'headless' is currently running

### ISSUE THREAD

**Issue by chenj133** [ultralytics/ultralytics#6939]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Traceback (most recent call last):
  File "train_student.py", line 4, in <module>
    model.train(data="student.yaml", epochs=100, batch=32, imgsz=640, device=2, name="stu", optimizer='SGD')
  File "/home/zhongdaa/.local/lib/python3.7/site-packages/ultralytics/engine/model.py", line 377, in train
    self.trainer.train()
  File "/home/zhongdaa/.local/lib/python3.7/site-packages/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/zhongdaa/.local/lib/python3.7/site-packages/ultralytics/engine/trainer.py", line 372, in _do_train
    self.metrics, self.fitness = self.validate()
  File "/home/zhongdaa/.local/lib/python3.7/site-packages/ultralytics/engine/trainer.py", line 478, in validate
    metrics = self.validator(self)
  File "/home/zhongdaa/.local/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/zhongdaa/.local/lib/python3.7/site-packages/ultralytics/engine/validator.py", line 180, in __call__
    stats = self.get_stats()
  File "/home/zhongdaa/.local/lib/python3.7/site-packages/ultralytics/models/yolo/detect/val.py", line 127, in get_stats
    self.metrics.process(*stats)
  File "/home/zhongdaa/.local/lib/python3.7/site-packages/ultralytics/utils/metrics.py", line 682, in process
    on_plot=self.on_plot)[2:]
  File "/home/zhongdaa/.local/lib/python3.7/site-packages/ultralytics/utils/metrics.py", line 488, in ap_per_class
    plot_pr_curve(px, py, ap, save_dir / f'{prefix}PR_curve.png', names, on_plot=on_plot)
  File "/home/zhongdaa/.local/lib/python3.7/site-packages/ultralytics/utils/__init__.py", line 199, in wrapper
    plt.switch_backend(original_backend)
  File "/home/zhongdaa/.local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 293, in switch_backend
    newbackend, required_framework, current_framework))
ImportError: Cannot load backend 'QtAgg' which requires the 'qt' interactive framework, as 'headless' is currently running

### Environment

pip package version:
matplotlib                         3.5.3
ultralytics                        8.0.145

python=3.7.6

ubuntu20.04

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@chenj133 it appears that your environment is running in 'headless' mode which may not support the 'QtAgg' backend required by Matplotlib. This could happen if you are using a remote server with no display connected or a Docker container without GUI support.

To resolve this issue, you can set an appropriate Matplotlib backend for a headless environment before running your script. You could set the backend to 'Agg' which is designed for use in a headless environment.

Refer to the official Matplotlib documentation on how to modify the backend. Additionally, check out the YOLOv8 Ultralytics Docs for potential custom configurations and ensure that your environment meets the prerequisites for running YOLOv8. 😊

**Comment by chenj133** [comment]
> @chenj133 it appears that your environment is running in 'headless' mode which may not support the 'QtAgg' backend required by Matplotlib. This could happen if you are using a remote server with no display connected or a Docker container without GUI support.
> 
> To resolve this issue, you can set an appropriate Matplotlib backend for a headless environment before running your script. You could set the backend to 'Agg' which is designed for use in a headless environment.
> 
> Refer to the official Matplotlib documentation on how to modify the backend. Additionally, check out the YOLOv8 Ultralytics Docs for potential custom configurations and ensure that your environment meets the prerequisites for running YOLOv8. 😊

Thanks，It's useful.

**Comment by glenn-jocher** [comment]
Glad to hear the solution was useful, @chenj133! If you encounter any more issues or have further questions as you continue working with YOLOv8, feel free to reach out. Happy coding! 😊

**Comment by huynhkhoa44** [comment]
hello @glenn-jocher, I encountered this error when training the YOLOv8 model with image size 1024. After training until epoch 145, it stopped. However, with this environment configuration, when I train the YOLOv8 model with image size 640, the training process occurs normally without any problems. Can you elaborate more on how to fix this error?
![image](https://github.com/ultralytics/ultralytics/assets/104811779/d75c6cb3-6dba-4aa5-b8ae-190f6b53fa68)

**Comment by glenn-jocher** [comment]
@huynhkhoa44 hello! The issue you're experiencing with the image size of 1024 could be related to system resource limitations, such as GPU memory. Training with larger image sizes requires more memory, and if the system runs out of it, the training process can be interrupted.

To address this, you could try the following:
1. Reduce the batch size to lower memory consumption.
2. Use a machine with more GPU memory.
3. Implement gradient accumulation if reducing the batch size impacts the training stability.

For more detailed guidance, please refer to the Training section in the Ultralytics Docs. If the problem persists, consider opening an issue with the full error log for further assistance.

**Comment by huynhkhoa44** [comment]
@glenn-jocher hello. After reduce batch size it still the same issue. I think my issue in the image is not relate to system resource limitation because. One detail I forgot to mention is that this error started appearing when I reinstalled the cuda driver for the server. Before reinstalling cuda, I performed the training process with size 1024 normally. Currently the version of my cuda driver is 11.4 and the torch version is 11.8. I wonder if it is the reason for the error in the photo?

**Comment by glenn-jocher** [comment]
@huynhkhoa44, it seems the issue might be related to the CUDA driver and PyTorch version compatibility. Ensure that the PyTorch version you're using is compatible with CUDA 11.4. You might need to align the versions properly or consider downgrading to a CUDA version that was previously working well with your setup. Check the PyTorch website for the compatible CUDA version for your specific PyTorch build.
