### ISSUE TITLE
Make validation mode changeable either `val` or `test`

### ISSUE THREAD

**Issue by validatedev** [ultralytics/ultralytics#694]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Right now, I couldn't change the dataset used in validation, it defaults only on validation set provided in `data.yaml`. It should be changeable via changing validation mode like in YOLOv5. As `data.yaml` provides `test` dataset path.

CLI example:
`>yolo val classify data=path mode="val"` -> Defaults to val if not set
`>yolo val classify data=path mode="test"`

Python example:
`results = model.val(mode='val')` -> Defaults to val if not set
`results = model.val(mode='test')`

### Use case

I want to see how my data performs also with test dataset, but now the only thing I can do is using predict, which is not viable if I want to see the performance of the model with a batch of data.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by validatedev** [comment]
For example: https://github.com/ultralytics/yolov5/issues/7741

**Comment by AyushExel** [comment]
Yes please make a PR.

**Comment by validatedev** [comment]
Closing the issue as the PR has merged.

**Comment by pderrenger** [comment]
@validatedev glad to hear that the PR has been merged! If you have any more suggestions or ideas, feel free to open a new issue. Thanks for your contribution!
