### ISSUE TITLE
How can I use yolov8n-p2.yaml with yolov8n-seg.pt

### ISSUE THREAD

**Issue by vraziel** [ultralytics/ultralytics#6942]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello. Thanks for sharing yolov8.

How can I use yolov8n-p2.yaml with yolov8n-seg.pt? I tried with:

model = YOLO('yolov8n-p2.yaml').load('yolov8n-seg.pt')
model = YOLO('yolov8n-seg-p2.yaml').load('yolov8n-seg.pt')
model = YOLO('yolov8n-p2-seg.yaml').load('yolov8n-seg.pt')

but error is thrown.

Is it possible to use  yolov8n-p2.yaml for segmentation tasks?

**Comment by glenn-jocher** [comment]
@vraziel hello! Thanks for reaching out.

To use a YOLOv8 segmentation model like `yolov8n-seg.pt`, you'll need to ensure that the configuration YAML file matches the segmentation model's architecture. Generally, `yolov8n-p2.yaml` is for detection tasks, not directly compatible with a segmentation model.

If you want to perform segmentation, use a YAML already configured for segmentation like `yolov8n-seg.yaml`. You just need to make sure you're using the correct model weights that correspond to segmentation models indicated with `-seg`.

To resolve the error, load your segmentation model with the proper segmentation-configured YAML by calling the load function with the correct paths to both the model `'.pt'` file and the segmentation YAML. Remember to review the tasks documentation on segmentation for more context on the correct usage of segmentation models with YOLOv8.

If you have such a correct YAML for segmentation tasks and still encounter errors, please provide the exact error message so we can assist more effectively. 😊

Happy to help with any further questions or clarifications!

**Comment by vraziel** [comment]
Thanks. It was clear from docs. 
But is there a way to configure backbone params for segmentation task? I did not find such info in docs.

**Comment by glenn-jocher** [comment]
Hi @vraziel,

Glad to hear the documentation was helpful!

For configuring the backbone parameters for segmentation tasks, you'd generally create a custom YAML defining the model's architecture, including the backbone modifications you desire. While our documentation doesn't explicitly cover backbone customization for segmentation, the process mirrors that of customizing models for detection tasks.

You would edit the .yaml file to adjust the backbone layers, channels, and other architectural details, keeping in mind the requirements of the segmentation head.

If you need further guidance on the specifics of this configuration, our team is ready to assist in the GitHub discussions page where the community and maintainers can better support detailed customization inquiries.

Hope this points you in the right direction! 🚀

**Comment by lonngxiang** [comment]
> ect model weights th

same question

**Comment by glenn-jocher** [comment]
Apologies for any previous confusion, @lonngxiang.

To adjust the backbone used in a segmentation model, you will need to create or edit a custom YAML file. This file should properly define your desired backbone and any other model parameters. The Ultralytics documentation does not provide a specific example for this task for segmentation models, but the customization process would be akin to customizing any other YOLOv8 model.

Please use the same methods as those described for detection tasks, adjusting them as necessary for segmentation. Should you require detailed assistance, consider opening a discussion on our GitHub repository.
