### ISSUE TITLE
change the path from '.config/Ultralytics' to a custom path

### ISSUE THREAD

**Issue by Arihant0408** [ultralytics/ultralytics#6944]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

While running the yolov8 model in training mode via CLI , i am getting an error that my .config/Ultralytics folder is full . So i want to change the directory where Ultralytics saves its configuration from .config/Ultralytics to a custom directory.

Please help me resolve this . Thanks
<img width="642" alt="Screenshot 2023-12-12 at 7 00 53 PM" src="https://github.com/ultralytics/ultralytics/assets/60618764/bf2c9ac3-406f-4ac1-98af-ebfa6b46126b">

**Comment by glenn-jocher** [comment]
@Arihant0408 hi there! 👋

If you're looking to change the default directory where YOLOv8 saves its configuration, you can set the `YOLO_CONFIG_DIR` environment variable to specify a custom path before running the training. Here's a simplified guide on how to do it: 

1. Open your terminal (or an environment where you'll run YOLOv8).
2. Set the `YOLO_CONFIG_DIR` variable with the command specific to your operating system (use `export` for Unix-like systems or `set` for Windows).
3. Run the YOLOv8 training command as usual.

This should redirect the configuration files to your specified directory. Please ensure that the directory you choose exists and has adequate storage space and permissions. 

Good luck with your training, and if you face any more hurdles, feel free to check the Docs or reach out again! Happy detecting! 🚀
